### ISSUE TITLE
./configure fails uuid/uuid.h missing, libuuid-devel package required

### ISSUE THREAD

**Issue by jimsalterjrs** [zfsonlinux/zfs#10004]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Clear Linux
Distribution Version	|  32310
Linux Kernel	|  4.19.103-113.lts2018
Architecture	| x86_64
ZFS Version	| 0.8.3
SPL Version	| 

### Describe the problem you're observing

Attempting to build ZFS manually on Clear Linux. 

./configure fails "uuid/uuid.h missing, libuuid-devel package required". There is no such package under Clear Linux; uuid.sh is present on the system under /usr/include/linux and elsewhere, but I cannot determine where the ./configure script is actually trying (and failing) to find it, so I'm stuck.

### Describe how to reproduce the problem

Download 0.8.3 and run ./configure on a Clear Linux system or VM.

### Include any warning/errors/backtraces from the system logs

```
configure: error: in `/home/jim/zfs-0.8.3':
configure: error:
           *** uuid/uuid.h missing, libuuid-devel package required
See `config.log' for more details.
```

**Comment by behlendorf** [comment]
The `uuid/uuid.h` header will be installed as `/usr/include/uuid/uuid.h` on most Linux distributions.      Sorry, I've never used Clear Linux so I'm not sure what package provides this header.  But if it's based on `apt` or `dnf` you should be able to ask it which package provides the missing header. 

```sh
$ apt-file search /usr/include/uuid/uuid.h
uuid-dev: /usr/include/uuid/uuid.h
```

```sh
$ dnf provides /usr/include/uuid/uuid.h
...
libuuid-devel-2.34-3.fc31.i686 : Universally unique ID library
Repo        : fedora
Matched from:
Filename    : /usr/include/uuid/uuid.h
```

**Comment by jimsalterjrs** [comment]
Thanks Brian--the problem wasn't "I don't know what package installs this" it was "I don't know where configure is trying to find it."

Clear seems to have put the header in /usr/include/linux rather than /usr/include/uuid. I'll see if I can monkey patch from here.

**Comment by behlendorf** [comment]
Sorry, I should have been more clear.  The file `/usr/include/linux/uuid.h` is an entirely different unrelated header, it hasn't been misplaced by Clear.  Everything under `/usr/include/linux` is there to provide the userland interface to the kernel.  What the configure script is looking for are the headers for the `/usr/lib64/libuuid.so.1` library.  Which appear to not be installed.

**Comment by jimsalterjrs** [comment]
Ooh, lib64! That gives me something new to look for; there were no bundles 
(what clear calls its packages) related to uuid, but I haven't checked for 
lib64-dev or similar.

Thanks again.

**Comment by jimsalterjrs** [comment]
And no, this thing isn't based on apt or rpm. It's... well, it's its own thing. Uses something called "swupd". I think your hints got me where I needed to be, though; swupd search-file uuid.h got me too many hits to be useful, but swupd search-file libuuid.so.1 came up with both os-core [installed] and os-core-dev... which is _not_ installed.

**Comment by jimsalterjrs** [comment]
Yep, that did it. If anybody else is trying to make this work and stuck on this step with Clear Linux, `swupd bundle-add os-core-dev` is the command you're looking for. (You'll also need `swupd bundle-add linux-lts-dev` if you're running on the LTS kernel, or `swupd bundle-add linux-dev` if you're on the native kernel—but the native kernel is currently newer than the OpenZFS project supports, so, may the Force be with you.)

Thank you again Brian.
