### ISSUE TITLE
Question: aes-256-gcm results in only 150MiB/s read, expected?

### ISSUE THREAD

**Issue by lord-carlos** [zfsonlinux/zfs#10016]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Debian
Distribution Version	| Buster with backports
Linux Kernel	| 5.3
Architecture	| amd64
CPU | AMD 2700X
ZFS Version	| 0.8.3

### Describe the problem you're observing
Hi guys
I already asked on IRC and reddit, but no one could help me.
I created a dataset with aes-256-gcm as I have been told it would be the new default and would be faster with hardware acceleration.
With 0.8.2 and stock kernel I only got ~80 MiB/s read speed. Fine, but I expected a significant increase with 0.8.3 and SIMD fixes.
Both simple read or fio test result in slow speeds on **encrypted** dataset:
```
pv /media/raid/test2/testfile22.img  > /dev/null
16.4GiB 0:01:55 [ 145MiB/s]
```
FIO https://pastebin.com/xCuuiMwX
While **unencrypted** it's way faster with less load on same pool.
```
pv /penis/testfile22.img > /dev/null
16.4GiB 0:00:48 [ 343MiB/s]
```
**Is this as expected?**
I only ask because other encryptions like luks can do Gigabit/s just fine.
And I read that gcm should be fast with hardware acceleration. 
But then I also saw this PR #9749 
So .. now i'm confused.

### Describe how to reproduce the problem

- Create a fast'ish pool
- Create a unencryptet dataset
- Create a encryptet dataset with aes-256-gcm with ZoL and SIMD fixes
- Compare read speeds with FIO on both dataset
- expect the results to be about equal on modern CPU.

### Include any warning/errors/backtraces from the system logs
Perf top shows hardware acceleration works: https://pastebin.com/En73v5vs
reddit thread: https://www.reddit.com/r/zfs/comments/f3w6v0/encrypted_dataset_still_slow_and_high_load_with/
#9749

**Comment by AttilaFueloep** [comment]
#9749 was merged after 0.8.3 was cut and is tagged for inclusion into OpenZFS 2.0. So your options are to try a current master (e.g the experimental zfs build repo mentioned in the redit thread) or to wait for OpenZFS 2.0.

**Comment by lord-carlos** [comment]
Hey @AttilaFueloep 
Thank you for your swift replay.
I'm aware that #9749 is not part of 0.8.3, sadly I don't have the resources at hand to test ZoL master.

My question was if people who use ZoL encryption, can confirm that 150 - 200 MiB/s is indeed common on a modern CPU with hardware acceleration. It seems to slow, that I have a hard time believing it. 
I expected LUKS like performance.

with kind regards

**Comment by AttilaFueloep** [comment]
Depending on your disks and the load on the system, that might be a bit slow. Looking at my notes:

```
$ dd if=random_data of=/dev/null bs=1M status=progress 
68538073088 bytes (69 GB, 64 GiB) copied, 152 s, 451 MB/s
```
NVMe mirror, six core Intel Coffee Lake @ 2.2 - 4.1 GHz, all cores at 100%.

As explained in #9749 there is a substantial overhead in saving and restoring the FPU state and IIRC the Ryzens are particularly slow at that. So that could explain the lower figures you are seeing.

**Comment by lord-carlos** [comment]
Thank you. My question has been answered.
I was just caught off guard, as none of the guides I read (Debian Wiki, Arch Wiki, this Wiki) mentioned encryption / decryption speed so I assumed similar performance as other solutions.
