### ISSUE TITLE
ZFS 0.8.3 erroneously ships a populated ./etc/init.d/zfs-functions

### ISSUE THREAD

**Issue by mason-redhat** [zfsonlinux/zfs#10020]
This is incorrect - it should only ship zfs-functions.in so that install variables can be correctly populated.

**Comment by mason-redhat** [comment]
Clarification: The issue is with the tarball. 0.8.3 includes the populated version, where 0.8.2 just included the source version, which worked correctly.

**Comment by behlendorf** [comment]
Thanks for filing an issue.  This is currently being worked on in #9955.

**Comment by mason-redhat** [comment]
Ah, sorry. I scanned through a few issues and didn't see this one. It doesn't show up on the front page. 

Oh, it's filed as a pull request... I'm guessing that's why. Glad it's being addressed, anyway.
