### ISSUE TITLE
Processes accessing ZFS/ZPOOL stuck

### ISSUE THREAD

**Issue by basic6** [zfsonlinux/zfs#1040]
I've set up a zpool with 5 drives (RAID-Z2). While this pool was in use, I disconnected one of the drives, to see what happens (if a drive dies). The drive's status (zpool status) changed from "ONLINE" to "UNAVAIL" (and stayed that way, even when I reconnected the drive).
Some time later (copy processes have been running the whole time writing data to this zpool), ZFS got stuck.
Every zpool command (e.g., zpool status) would get stuck. Every process trying to access the zpool gets stuck, even a simple ls. None of those stuck processes can be terminated, not even killed (SIGKILL).

Ctrl + Alt + SysRq + W (after echo 1 > /proc/sys/kernel/sysrq) shows a lot of call traces, most of them from udisks-helper. Here are the last 3:
http://pastebin.com/W8A4ynkV

Using the Ubuntu Natty stable repository package (on Debian):
ii  zfsutils                             0.6.0.80-0ubuntu1~natty1          Native ZFS management utilities for Linux

**Comment by behlendorf** [comment]
This issue was addressed by commit 417104bdd3c7ce07ec58674dd078f9891c3bc780.  It was possible for commands like `zpool status` to trigger a disk I/O which would never complete when a pool went offline due to the loss of too many devices.
