### ISSUE TITLE
System takes a long time to suspend when zfs_txg_timeout is large.

### ISSUE THREAD

**Issue by yshui** [zfsonlinux/zfs#1054]
I'm not sure if this is a bug or just something I shouldn't do, but I'm reporting it anyway and let you judge.

When setting zfs_txg_timeout to a large number (like 500, but I think 60 is enough), the system will take a long time to suspend (it won't suspend till a txg_timeout occurs, I guess).

Example:
```
[ 8695.707155] PM: Syncing filesystems ... done.
[ 8818.193226] PM: Preparing system for mem sleep

**Comment by behlendorf** [comment]
Closing.  This could be improved if someone is so inclined but lets just avoid doing that.
