### ISSUE TITLE
zfs receive allows snapshot destruction during receive and fails

### ISSUE THREAD

**Issue by wrouesnel** [zfsonlinux/zfs#1059]
Just spent a few hours diagnosing what I believe to be a bug with the way zfs receive operates when receiving send streams containing multiple incremental snapshots.

Specifically, the system I was receiving on was using a timed zfs-auto-snapshot script, which destroys old datasets when making new ones at 15 minute intervals.

While doing some partition resizing (and thus needing to remove my old pool and restore from a file), I found that the receive operation would get about 70% of the way through and then fail with "invalid backup stream".

After disabling cron, the receive worked though. The problem, seemed to be that when the receive got to a set of newer datasets with auto-snapshot might want to remove, it would remove one which was needed to receive the next incremental snapshot in the send stream, and cause the whole receive operation to fail.

A similar bug was previously fixed with the zfs send operation, which marks dependent datasets as held until it completed. It seems to me that zfs receive should do the same thing - mark a just received dataset as held, until either the operation completes or the next dataset is received.

**Comment by behlendorf** [comment]
With the addition on resumable send/recv this code has seen considerable change.  At the moment all the test cases are passing so I believe this issue was fixed.  If not we can reopen it.
