### ISSUE TITLE
ZFS should create a BIOS Boot Partition when doing GPT partitioning

### ISSUE THREAD

**Issue by ryao** [zfsonlinux/zfs#1061]
Currently, GRUB2 is the only bootloader available for installing Linux on a ZFS rootfs and it requires a BIOS Boot Partition (code EF02) to function when GPT partitioning is in use. Creating a BIOS boot partiton from sector 48 to sector 2047 when  `zpool create` is run would make such installs much easier. We could use partition 2 for it.

Note that there are a few more sectors available before sector 48, but I think that logical sector 48 is a good choice because it ensures alignment on drives with 8KB physical sectors.

**Comment by rlaager** [comment]
Copying from #2062:
The more I think about this whole thing, the less I think it's the right answer. If you start going down this rabbit hole, you'll run into things like UEFI on mirrors. Is ZFS going to mirror that FAT filesystem (yuck!) or is ZFS going to setup an MD array? It's just madness. I've given up the fight on wholedisk. Not even Solaris used wholedisk for their bootable pools. It just falls down in so many ways.

Plus, this would require distro installers to use more ZFS-specific code. Letting them partition the disk as normal and then throw ZFS on a partition is a lot simpler to integrate.
