### ISSUE TITLE
Immortal processes & ZoL

### ISSUE THREAD

**Issue by nightwalk** [zfsonlinux/zfs#1070]
Ok, let me first state that I don't think this belongs in the ZoL bug tracker since it's an issue I've known ZoL to cause, but which is actually a flaw in the way the kernel proper handles modules (in my opinion). I'm finally caving and submitting it because Mr. Yao has been insisting I do so for months.

Basically, at times, a process using a file on a zfs dataset or zvol will block in a syscall forever and thus become what I call an immortal process. Since it's inside of a syscall (notably, sys_read, or more commonly with ZoL, sys_write), the process is effectively unkillable even by kill -9. Likewise, the filesystem can't be unmounted in a way that decrements the module usage counter, and that in turn keeps the backing modules from being able to be unloaded.

Since removing the module is often the 'fix' for *all* of the issues (as far as ZoL is concerned anyway), it's something of a catch 22. One is left with a reboot as the only remaining option, and that's just plain silly.

I don't have a consistent way to reproduce this behavior, but pointing dovecot at users' Maildir directories on a zfs dataset comes close sometimes. Having deduplication and compression enabled on the dataset also seems to up the odds significantly (especially dedup). The common denominator seems to be inordinately high latency, and that makes me wonder if it isn't causing something in kernel land to fall on the wrong side of a race condition, assumption, or something.

**Comment by behlendorf** [comment]
Closing as not a ZoL issue based on @nightwalk's comments above.
