### ISSUE TITLE
Drives labeled by WWN inconsistently available at mount time?

### ISSUE THREAD

**Issue by rdlugosz** [zfsonlinux/zfs#1103]
I've been building out a new storage pool on Ubuntu 12.04 and have run into a peculiar issue that I suspect may be a race condition with drive/label availability at ZFS automount time.

Upon a reboot, a ```zpool status``` will often report my pool as degraded, with one or more of the drives listed as unavailable due to label missing. Typically it's just one, but sometimes it is two. I've not seen more than two listed as unavailable (yet). There are no errors related to the drive(s) in dmesg, logs or the BIOS. **Issuing a ```zpool export``` followed by an immediate ```zpool import``` resolves the problem and all drives are listed as available.**

A scrub shows no issues, large transfers don't cause any problems and I've tried some of the obvious things like switching out sata cables & ports. Nothing seems to make a difference.

My older pool does *not* exhibit this behavior at all, even if I run it on the same controller/ports as the new pool. The only major difference (beyond capacity) is that I created the new pool using the WWN label instead of the more typical identifier that includes the interface. Here's my create statement:
```
sudo zpool create -o ashift=12 -f keg raidz2 /dev/disk/by-id/wwn-0x5000c5004e8f4dd4 /dev/disk/by-id/wwn-0x5000c5004e8c845e /dev/disk/by-id/wwn-0x5000c5004e8eaea7 /dev/disk/by-id/wwn-0x5000c5004e8c76b3
```

So, at this point I am relatively convinced that there's nothing wrong with the drives but rather there's some kind of timing issue related to when ZFS attempts to mount the pool and the existence of that drive's label in the system...

Any thoughts on how I can debug this? Any reason to suspect that the WWN names are at fault & I should switch them out for the more traditional disk identifier? (And, if I wanted to test that, do I just ```detatch``` each drive one by one and ```attach``` them again with their alternate label or do I need to use the ```replace``` command and have each one rebuilt?)

Here's some info on my current package versions:
```
ryan@nas:~$ dpkg -l | grep zfs
ii  libzfs1                                0.6.0.86-0ubuntu1~precise1              Native ZFS filesystem library for Linux
ii  mountall                               2.36.1-zfs1                             filesystem mounting tool
ii  ubuntu-zfs                             6~precise                               Native ZFS filesystem metapackage for Ubuntu.
ii  zfs-dkms                               0.6.0.86-0ubuntu1~precise1              Native ZFS filesystem kernel modules for Linux
ii  zfsutils                               0.6.0.86-0ubuntu1~precise1              Native ZFS management utilities for Linux
ryan@nas:~$ uname -a
Linux nas 3.2.0-33-generic #52-Ubuntu SMP Thu Oct 18 16:29:15 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
```
And some info on the pools:
```
ryan@nas:~$ sudo zpool status
  pool: keg
 state: ONLINE
 scan: scrub repaired 0 in 1h31m with 0 errors on Wed Nov 21 09:55:35 2012
config:

	NAME                        STATE     READ WRITE CKSUM
	keg                         ONLINE       0     0     0
	  raidz2-0                  ONLINE       0     0     0
	    wwn-0x5000c5004e8f4dd4  ONLINE       0     0     0
	    wwn-0x5000c5004e8c845e  ONLINE       0     0     0
	    wwn-0x5000c5004e8eaea7  ONLINE       0     0     0
	    wwn-0x5000c5004e8c76b3  ONLINE       0     0     0

errors: No known data errors

  pool: tank
 state: ONLINE
 scan: scrub repaired 0 in 2h50m with 0 errors on Wed Nov 21 04:21:54 2012
config:

	NAME                                            STATE     READ WRITE CKSUM
	tank                                            ONLINE       0     0     0
	  raidz1-0                                      ONLINE       0     0     0
	    ata-Hitachi_HDT721010SLA360_STF605MH1K5EPW  ONLINE       0     0     0
	    ata-ST31000528AS_9VP1YGNE                   ONLINE       0     0     0
	    ata-WDC_WD6400AAKS-75A7B0_WD-WMASY2713477   ONLINE       0     0     0

errors: No known data errors
ryan@nas:~$ sudo zpool list 
NAME   SIZE  ALLOC   FREE    CAP  DEDUP  HEALTH  ALTROOT
keg   7.25T  2.01T  5.24T    27%  1.00x  ONLINE  -
tank  1.73T  1.50T   241G    86%  1.08x  ONLINE  -
```
Output of ```zdb -C```: https://gist.github.com/3a6fc5c86fefd31ca2b8
Output of ```dmesg```: https://gist.github.com/71ca347dacb641aa933a

**Comment by behlendorf** [comment]
Closing.  Several patch have been merged which should have improved this.
