### ISSUE TITLE
ZFS send dedup multi-thread

### ISSUE THREAD

**Issue by mcr-ksh** [zfsonlinux/zfs#1112]
Hi,

the "zfs send -vD" is dedup of the stream which is performing very badly. I figured it uses just one core of a multi-core system. So if we have a 28 core machine we wouldn't see any improvement.

Therefore, the feature request to make zfs send dedup multi-threaded.

Best.

**Comment by ryao** [comment]
zfsonlinux/zfs@5c3f61eb498e8124858b1369096bf64b86a938e7 implemented a larger receive buffer.

**Comment by behlendorf** [comment]
zfsonlinux/zfs@b738bc5a0f8ccd0281ed06831c34fbe31d2b2138 also significantly improved performance by improving the prefetch.
