### ISSUE TITLE
KVM Live Snapshot Support

### ISSUE THREAD

**Issue by behlendorf** [zfsonlinux/zfs#1129]
Integrating with this new functionality looks very doable and very cool.  Someone should investigating writing the needed hooks for ZFS.

https://events.linuxfoundation.org/slides/2011/linuxcon-japan/lcj2011_sorensen.pdf

**Comment by rlaager** [comment]
If you are talking about ZFS in a guest, then the required functionality is freeze/thaw, for which we have issue #260.

If you are talking about ZFS on the host, then qemu and/or libvirt need to support calling `zfs snapshot`, which is an issue for those projects. (There has been work in this area; libvirt supports ZFS for its storage pools, but I don't think snapshot support has been written yet.)

**Comment by lenucksi** [comment]
Although the ZFS integration into libvirt and especially the virt-manager does not seem to be exactly prime-time but rather experimental. See here: https://libvirt.org/storage.html#StorageBackendZFS
