### ISSUE TITLE
Permit `zpool create -o whole_disk=1`

### ISSUE THREAD

**Issue by ryao** [zfsonlinux/zfs#1162]
There are situations where it is desireable to set the whole_disk attribute so that ZFS will control the IO elevator, but ZFS does not permit it.

One scenario involved issue #1149, which resulted in an exception being added to the IO elevator behavior. Another scenario involves virtual machines on zvols. With raw disks, ZFS does partitioning and leaves space for an additional partition to be added for the bootloader. With zvols, ZFS does no partitioning. This poses a problem when a guest operating system's bootloader requires a separate partition to host its stage2 loader. If ZFS did do partitioning on zvols, we would lose flexibility when configuring pools on zvols.

In both scenarios, it would be helpful to override the default whole_disk attribute setting when creating the pool. This should be safe because the worst case scenario on Linux would be the use of a suboptimal IO elevator. This would only happen when the user explicitly requests it.

The rationale for whole_disk is stated on Wikipedia:

> On Solaris, when entire disks are added to a ZFS pool, ZFS automatically enables their write cache. This is not done when ZFS only manages discrete slices of the disk, since it does not know if other slices are managed by non-write-cache safe filesystems, like UFS. The FreeBSD implementation can handle disk flushes for partitions thanks to its GEOM framework, and therefore does not suffer from this limitation

The consequence is that FreeBSD unconditionally sets whole_disk. While it could be undesirable to do the same, it should be perfectly fine to allow users to override the default choice when creating a pool.

**Comment by rlaager** [comment]
The elevator thing is gone or going away. I'm closing this in favor of #3452, which has more notes for an implementation.
