### ISSUE TITLE
Reduce ZFS related processes/tasks

### ISSUE THREAD

**Issue by devsk** [zfsonlinux/zfs#118]
These are apart from the worker threads.
<pre>
# ps|grep "\[z"
root      2710     2  0 Feb22 ?        00:00:00      0       0   0 S zvol/0          [zvol/0]
root      2711     2  0 Feb22 ?        00:00:00      0       0   0 S zvol/1          [zvol/1]
root      2712     2  0 Feb22 ?        00:00:00      0       0   0 S zvol/2          [zvol/2]
root      2713     2  0 Feb22 ?        00:00:00      0       0   0 S zvol/3          [zvol/3]
root      3073     2  0 Feb22 ?        00:00:00      0       0   0 S z_null_iss/0    [z_null_iss/0]
root      3074     2  0 Feb22 ?        00:00:00      0       0   0 S z_null_int/0    [z_null_int/0]
root      3075     2  0 Feb22 ?        00:00:00      0       0   0 S z_rd_iss/0      [z_rd_iss/0]
root      3076     2  0 Feb22 ?        00:00:00      0       0   0 S z_rd_iss/1      [z_rd_iss/1]
root      3077     2  0 Feb22 ?        00:00:00      0       0   0 S z_rd_iss/2      [z_rd_iss/2]
root      3078     2  0 Feb22 ?        00:00:00      0       0   0 S z_rd_iss/3      [z_rd_iss/3]
root      3079     2  0 Feb22 ?        00:00:00      0       0   0 S z_rd_iss/4      [z_rd_iss/4]
root      3080     2  0 Feb22 ?        00:00:00      0       0   0 S z_rd_iss/5      [z_rd_iss/5]
root      3081     2  0 Feb22 ?        00:00:00      0       0   0 S z_rd_iss/6      [z_rd_iss/6]
root      3082     2  0 Feb22 ?        00:00:00      0       0   0 S z_rd_iss/7      [z_rd_iss/7]
root      3083     2  0 Feb22 ?        00:00:00      0       0   0 S z_rd_int/0      [z_rd_int/0]
root      3084     2  0 Feb22 ?        00:00:00      0       0   0 S z_rd_int/1      [z_rd_int/1]
root      3085     2  0 Feb22 ?        00:00:00      0       0   0 S z_rd_int/2      [z_rd_int/2]
root      3086     2  0 Feb22 ?        00:00:00      0       0   0 S z_rd_int/3      [z_rd_int/3]
root      3087     2  0 Feb22 ?        00:00:00      0       0   0 S z_wr_iss/0      [z_wr_iss/0]
root      3088     2  0 Feb22 ?        00:00:00      0       0   0 S z_wr_iss/1      [z_wr_iss/1]
root      3089     2  0 Feb22 ?        00:00:00      0       0   0 S z_wr_iss/2      [z_wr_iss/2]
root      3090     2  0 Feb22 ?        00:00:00      0       0   0 S z_wr_iss/3      [z_wr_iss/3]
root      3091     2  0 Feb22 ?        00:00:00      0       0   0 S z_wr_iss_h/0    [z_wr_iss_h/0]
root      3092     2  0 Feb22 ?        00:00:00      0       0   0 S z_wr_iss_h/1    [z_wr_iss_h/1]
root      3093     2  0 Feb22 ?        00:00:00      0       0   0 S z_wr_iss_h/2    [z_wr_iss_h/2]
root      3094     2  0 Feb22 ?        00:00:00      0       0   0 S z_wr_iss_h/3    [z_wr_iss_h/3]
root      3095     2  0 Feb22 ?        00:00:00      0       0   0 S z_wr_iss_h/4    [z_wr_iss_h/4]
root      3096     2  0 Feb22 ?        00:00:00      0       0   0 S z_wr_int/0      [z_wr_int/0]
root      3097     2  0 Feb22 ?        00:00:00      0       0   0 S z_wr_int/1      [z_wr_int/1]
root      3098     2  0 Feb22 ?        00:00:00      0       0   0 S z_wr_int/2      [z_wr_int/2]
root      3099     2  0 Feb22 ?        00:00:00      0       0   0 S z_wr_int/3      [z_wr_int/3]
root      3100     2  0 Feb22 ?        00:00:00      0       0   0 S z_wr_int/4      [z_wr_int/4]
root      3101     2  0 Feb22 ?        00:00:00      0       0   0 S z_wr_int/5      [z_wr_int/5]
root      3102     2  0 Feb22 ?        00:00:00      0       0   0 S z_wr_int/6      [z_wr_int/6]
root      3103     2  0 Feb22 ?        00:00:00      0       0   0 S z_wr_int/7      [z_wr_int/7]
root      3104     2  0 Feb22 ?        00:00:00      0       0   0 S z_wr_int/8      [z_wr_int/8]
root      3105     2  0 Feb22 ?        00:00:00      0       0   0 S z_wr_int/9      [z_wr_int/9]
root      3106     2  0 Feb22 ?        00:00:00      0       0   0 S z_wr_int/10     [z_wr_int/10]
root      3107     2  0 Feb22 ?        00:00:00      0       0   0 S z_wr_int/11     [z_wr_int/11]
root      3108     2  0 Feb22 ?        00:00:00      0       0   0 S z_wr_int/12     [z_wr_int/12]
root      3109     2  0 Feb22 ?        00:00:00      0       0   0 S z_wr_int/13     [z_wr_int/13]
root      3110     2  0 Feb22 ?        00:00:00      0       0   0 S z_wr_int/14     [z_wr_int/14]
root      3111     2  0 Feb22 ?        00:00:00      0       0   0 S z_wr_int/15     [z_wr_int/15]
root      3112     2  0 Feb22 ?        00:00:00      0       0   0 S z_wr_int_h/0    [z_wr_int_h/0]
root      3113     2  0 Feb22 ?        00:00:00      0       0   0 S z_wr_int_h/1    [z_wr_int_h/1]
root      3114     2  0 Feb22 ?        00:00:00      0       0   0 S z_wr_int_h/2    [z_wr_int_h/2]
root      3115     2  0 Feb22 ?        00:00:00      0       0   0 S z_wr_int_h/3    [z_wr_int_h/3]
root      3116     2  0 Feb22 ?        00:00:00      0       0   0 S z_wr_int_h/4    [z_wr_int_h/4]
root      3117     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/0      [z_fr_iss/0]
root      3118     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/1      [z_fr_iss/1]
root      3119     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/2      [z_fr_iss/2]
root      3120     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/3      [z_fr_iss/3]
root      3121     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/4      [z_fr_iss/4]
root      3122     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/5      [z_fr_iss/5]
root      3123     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/6      [z_fr_iss/6]
root      3124     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/7      [z_fr_iss/7]
root      3125     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/8      [z_fr_iss/8]
root      3126     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/9      [z_fr_iss/9]
root      3127     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/10     [z_fr_iss/10]
root      3128     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/11     [z_fr_iss/11]
root      3129     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/12     [z_fr_iss/12]
root      3130     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/13     [z_fr_iss/13]
root      3131     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/14     [z_fr_iss/14]
root      3132     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/15     [z_fr_iss/15]
root      3133     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/16     [z_fr_iss/16]
root      3134     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/17     [z_fr_iss/17]
root      3135     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/18     [z_fr_iss/18]
root      3136     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/19     [z_fr_iss/19]
root      3137     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/20     [z_fr_iss/20]
root      3138     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/21     [z_fr_iss/21]
root      3139     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/22     [z_fr_iss/22]
root      3140     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/23     [z_fr_iss/23]
root      3141     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/24     [z_fr_iss/24]
root      3142     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/25     [z_fr_iss/25]
root      3143     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/26     [z_fr_iss/26]
root      3144     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/27     [z_fr_iss/27]
root      3145     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/28     [z_fr_iss/28]
root      3146     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/29     [z_fr_iss/29]
root      3147     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/30     [z_fr_iss/30]
root      3148     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/31     [z_fr_iss/31]
root      3149     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/32     [z_fr_iss/32]
root      3150     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/33     [z_fr_iss/33]
root      3151     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/34     [z_fr_iss/34]
root      3152     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/35     [z_fr_iss/35]
root      3153     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/36     [z_fr_iss/36]
root      3154     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/37     [z_fr_iss/37]
root      3155     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/38     [z_fr_iss/38]
root      3156     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/39     [z_fr_iss/39]
root      3157     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/40     [z_fr_iss/40]
root      3158     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/41     [z_fr_iss/41]
root      3159     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/42     [z_fr_iss/42]
root      3160     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/43     [z_fr_iss/43]
root      3161     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/44     [z_fr_iss/44]
root      3162     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/45     [z_fr_iss/45]
root      3163     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/46     [z_fr_iss/46]
root      3164     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/47     [z_fr_iss/47]
root      3165     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/48     [z_fr_iss/48]
root      3166     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/49     [z_fr_iss/49]
root      3167     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/50     [z_fr_iss/50]
root      3168     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/51     [z_fr_iss/51]
root      3169     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/52     [z_fr_iss/52]
root      3170     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/53     [z_fr_iss/53]
root      3171     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/54     [z_fr_iss/54]
root      3172     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/55     [z_fr_iss/55]
root      3173     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/56     [z_fr_iss/56]
root      3174     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/57     [z_fr_iss/57]
root      3175     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/58     [z_fr_iss/58]
root      3176     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/59     [z_fr_iss/59]
root      3177     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/60     [z_fr_iss/60]
root      3178     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/61     [z_fr_iss/61]
root      3179     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/62     [z_fr_iss/62]
root      3180     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/63     [z_fr_iss/63]
root      3181     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/64     [z_fr_iss/64]
root      3182     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/65     [z_fr_iss/65]
root      3183     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/66     [z_fr_iss/66]
root      3184     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/67     [z_fr_iss/67]
root      3185     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/68     [z_fr_iss/68]
root      3186     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/69     [z_fr_iss/69]
root      3187     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/70     [z_fr_iss/70]
root      3188     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/71     [z_fr_iss/71]
root      3189     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/72     [z_fr_iss/72]
root      3190     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/73     [z_fr_iss/73]
root      3191     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/74     [z_fr_iss/74]
root      3192     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/75     [z_fr_iss/75]
root      3193     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/76     [z_fr_iss/76]
root      3194     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/77     [z_fr_iss/77]
root      3195     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/78     [z_fr_iss/78]
root      3196     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/79     [z_fr_iss/79]
root      3197     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/80     [z_fr_iss/80]
root      3198     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/81     [z_fr_iss/81]
root      3199     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/82     [z_fr_iss/82]
root      3200     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/83     [z_fr_iss/83]
root      3201     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/84     [z_fr_iss/84]
root      3202     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/85     [z_fr_iss/85]
root      3203     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/86     [z_fr_iss/86]
root      3204     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/87     [z_fr_iss/87]
root      3205     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/88     [z_fr_iss/88]
root      3206     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/89     [z_fr_iss/89]
root      3207     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/90     [z_fr_iss/90]
root      3208     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/91     [z_fr_iss/91]
root      3209     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/92     [z_fr_iss/92]
root      3210     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/93     [z_fr_iss/93]
root      3211     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/94     [z_fr_iss/94]
root      3212     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/95     [z_fr_iss/95]
root      3213     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/96     [z_fr_iss/96]
root      3214     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/97     [z_fr_iss/97]
root      3215     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/98     [z_fr_iss/98]
root      3216     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_iss/99     [z_fr_iss/99]
root      3217     2  0 Feb22 ?        00:00:00      0       0   0 S z_fr_int/0      [z_fr_int/0]
root      3218     2  0 Feb22 ?        00:00:00      0       0   0 S z_cl_iss/0      [z_cl_iss/0]
root      3219     2  0 Feb22 ?        00:00:00      0       0   0 S z_cl_int/0      [z_cl_int/0]
root      3220     2  0 Feb22 ?        00:00:00      0       0   0 S z_ioctl_iss/0   [z_ioctl_iss/0]
root      3221     2  0 Feb22 ?        00:00:00      0       0   0 S z_ioctl_int/0   [z_ioctl_int/0]
root      3226     2  0 Feb22 ?        00:00:00      0       0  39 S zfs_iput_taskq/ [zfs_iput_taskq/]
</pre>

**Comment by behlendorf** [comment]
Resolved by zfsonlinux/spl@f7a973d99b5e272f4a6223b8fb7db4fc6d363b41 and aa9af22cdf8d16c197974c3a478d2053b3bed498.
