### ISSUE TITLE
zpool autoexpand doesn't work

### ISSUE THREAD

**Issue by fajarnugraha** [zfsonlinux/zfs#120]
zpool autoexpand doesn't work. This feature is desirable if you use LVM or SAN that can resize their LUN as zpool vdev.

<pre>
# dd if=/dev/zero of=/data/vbd/vdev1.img bs=1M count=0 seek=1024
0+0 records in
0+0 records out
0 bytes (0 B) copied, 3.2411e-05 seconds, 0.0 kB/s

# zpool create testpool /data/vbd/vdev1.img

# zpool get autoexpand testpool
NAME      PROPERTY    VALUE   SOURCE
testpool  autoexpand  off     default

# zpool set autoexpand=on testpool

# zpool get autoexpand testpool
NAME      PROPERTY    VALUE   SOURCE
testpool  autoexpand  on      local

# zpool list testpool
NAME       SIZE  ALLOC   FREE    CAP  DEDUP  HEALTH  ALTROOT
testpool  1016M  82.5K  1016M     0%  1.00x  ONLINE  -

# ls -lash /data/vbd
total 1.2M
4.0K drwxr-xr-x 2 root  root  4.0K Feb 24 14:01 .
4.0K drwxr-xr-x 6 build build 4.0K Feb 24 14:00 ..
1.2M -rw-r--r-- 1 root  root  1.0G Feb 24 14:02 vdev1.img

# dd if=/dev/zero of=/data/vbd/vdev1.img bs=1M count=0 seek=2048
0+0 records in
0+0 records out
0 bytes (0 B) copied, 2.9672e-05 seconds, 0.0 kB/s

# ls -lash /data/vbd
total 1.2M
4.0K drwxr-xr-x 2 root  root  4.0K Feb 24 14:01 .
4.0K drwxr-xr-x 6 build build 4.0K Feb 24 14:00 ..
1.2M -rw-r--r-- 1 root  root  2.0G Feb 24 14:05 vdev1.img

# zpool list testpool
NAME       SIZE  ALLOC   FREE    CAP  DEDUP  HEALTH  ALTROOT
testpool  1016M  82.5K  1016M     0%  1.00x  ONLINE  -

# zpool export testpool

# zpool import -d /data/vbd/ testpool

# zpool list testpool
NAME       SIZE  ALLOC   FREE    CAP  DEDUP  HEALTH  ALTROOT
testpool  1016M   132K  1016M     0%  1.00x  ONLINE  -
</pre>

For comparison, autoexpand works in zfs-fuse as long as you export-import the pool.

**Comment by hvisage** [comment]
okay, Debian9, 0.6.5.9, and I don't get this autoexpand going
```ii  libzfs2linux                  0.6.5.9-5                      amd64        OpenZFS filesystem library for Linux
ii  libzpool2linux                0.6.5.9-5                      amd64        OpenZFS pool library for Linux
ii  zfs-dkms                      0.6.5.9-5                      all          OpenZFS filesystem kernel modules for Linux
ii  zfs-zed                       0.6.5.9-5                      amd64        OpenZFS Event Daemon
ii  zfsutils-linux                0.6.5.9-5                      amd64        command-line tools to manage OpenZFS filesystems

root@tracsftpqa01:~# zpool export test
root@tracsftpqa01:~# zpool import -o expand=on test
root@tracsftpqa01:~# zpool list
NAME   SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
test  15.9G   234K  15.9G         -     0%     0%  1.00x  ONLINE  -
root@tracsftpqa01:~# fdisk -l /dev/disk/*/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1
Disk /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1: 145 GiB, 155692564480 bytes, 304087040 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 896E82DA-56D8-FD4C-8B30-858036CE594F

Device                                                         Start       End   Sectors  Size Type
/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1-part1      2048 304068607 304066560  145G Solaris
/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1-part9 304068608 304084991     16384    8M Solaris

root@tracsftpqa01:~# zpool get autoexpand test
NAME  PROPERTY    VALUE   SOURCE
test  autoexpand  on      local
```
