### ISSUE TITLE
ARC Prevents Huge Page Allocation

### ISSUE THREAD

**Issue by eatnumber1** [zfsonlinux/zfs#1212]
When the ARC is filling memory, normal memory allocations will cause the ARC to shrink, but increasing the huge page reserve size (by writing to `/proc/sys/vm/nr_hugepages`) will fail. Additionally, when overcommitting of huge pages is allowed, allocations beyond the reserve size will fail, even if it is still below the overcommit limit.

Also, I'd imagine the ARC would benefit from itself using huge pages.

**Comment by aucampia** [comment]
@behlendorf is there a specific issue to track progress or planning for ARC and page cache unification ?

**Comment by behlendorf** [comment]
@aucampia unfortunately no.  But there should probably be some sort of task list written down to clearly show what steps are required.  Finalizing the ABD patches in #3441 is the first big step.

**Comment by behlendorf** [comment]
Moving the ARC to pages is targeted for 0.7.0.  Determine how/if those pages should be integrated as page cache pages won't be until 0.8.0 or latter.

**Comment by behlendorf** [comment]
Now that ABD has been merged this should be largely addressed in master.

7657def Introduce ARC Buffer Data (ABD)
