### ISSUE TITLE
Large zvol swap makes system almost hang

### ISSUE THREAD

**Issue by valri** [zfsonlinux/zfs#1218]
On my system with 8G of RAM, a zvol swap of 9G works normally, but a 20G zvol swap makes the system go **really** slowly (almost hang) when swap is used.

* lshw: http://bpaste.net/show/71023/
* zpool list: http://bpaste.net/show/71027/
* zfs status: http://bpaste.net/show/71028/
* zfs get all rpool/funtoo/swap **broken**: http://bpaste.net/show/71022/
* zfs get all rpool/funtoo/swap **working**: http://bpaste.net/show/71026/

**Comment by behlendorf** [comment]
Closing as stale, refer to the [swap section](https://github.com/zfsonlinux/zfs/wiki/FAQ#using-a-zvol-for-a-swap-device) of the wiki for additional configuration information.
