### ISSUE TITLE
arcstats show arc_meta_used perpetually exceeding arc_meta_limit

### ISSUE THREAD

**Issue by mooinglemur** [zfsonlinux/zfs#1261]
From \#zfsonlinux FreeNode (UTC-7)

2013-02-04 05:52:01 <@ryao> MooingLemur: It looks like the ARC metadata is not being properly evicted. Your arc_meta_limit is about 13GB, but your arc_meta_used is about 25GB.
2013-02-04 05:52:25 <@ryao> MooingLemur: Would you file an issue in the github tracker for this?

zfs/spl 0.6.0_rc13

-[~:#]- cat /proc/spl/kstat/zfs/arcstats 
4 1 0x01 77 3696 22027237887 1282930888900540
name                            type data
hits                            4    2338004333
misses                          4    349509271
demand_data_hits                4    1915599183
demand_data_misses              4    1623038
demand_metadata_hits            4    345221726
demand_metadata_misses          4    282531804
prefetch_data_hits              4    155903
prefetch_data_misses            4    25322
prefetch_metadata_hits          4    77027521
prefetch_metadata_misses        4    65329107
mru_hits                        4    71265942
mru_ghost_hits                  4    67588182
mfu_hits                        4    2189585139
mfu_ghost_hits                  4    277463230
deleted                         4    5770819
recycle_miss                    4    336216731
mutex_miss                      4    667035
evict_skip                      4    333435274085
evict_l2_cached                 4    4747871106048
evict_l2_eligible               4    3338279337472
evict_l2_ineligible             4    779170207232
hash_elements                   4    9109341
hash_elements_max               4    9109365
hash_collisions                 4    70226897
hash_chains                     4    1952143
hash_chain_max                  4    16
p                               4    2594001755
c                               4    41504028088
c_min                           4    6509559808
c_max                           4    52076478464
size                            4    41494662632
hdr_size                        4    2593099248
data_size                       4    22466341376
other_size                      4    15997946376
anon_size                       4    1403392
anon_evict_data                 4    0
anon_evict_metadata             4    0
mru_size                        4    6033657344
mru_evict_data                  4    739427840
mru_evict_metadata              4    6029312
mru_ghost_size                  4    35467316736
mru_ghost_evict_data            4    12599742976
mru_ghost_evict_metadata        4    22867573760
mfu_size                        4    16431280640
mfu_evict_data                  4    16045605888
mfu_evict_metadata              4    200192
mfu_ghost_size                  4    2925335040
mfu_ghost_evict_data            4    14339072
mfu_ghost_evict_metadata        4    2910995968
l2_hits                         4    180963397
l2_misses                       4    168545822
l2_feeds                        4    1306614
l2_rw_clash                     4    352253
l2_read_bytes                   4    4639391288320
l2_write_bytes                  4    1000437387264
l2_writes_sent                  4    479074
l2_writes_done                  4    479074
l2_writes_error                 4    0
l2_writes_hdr_miss              4    1697
l2_evict_lock_retry             4    395
l2_evict_reading                4    0
l2_free_on_write                4    721209
l2_abort_lowmem                 4    742
l2_cksum_bad                    4    0
l2_io_error                     4    0
l2_size                         4    27754786304
l2_hdr_size                     4    462997728
memory_throttle_count           4    0
memory_direct_count             4    25908
memory_indirect_count           4    5629
arc_no_grow                     4    0
arc_tempreserve                 4    0
arc_loaned_bytes                4    0
arc_prune                       4    226397015
arc_meta_used                   4    24708841960
arc_meta_limit                  4    13019119616
arc_meta_max                    4    25356992032

**Comment by behlendorf** [comment]
Closing.  Resolved by ca0bf58d65f77e944b9905571df9a2eae647aeca and a few other small improvements since 0.6.3.  Expect further improvements as the ABD work is finalized and merged.
