### ISSUE TITLE
ZFS Swap Lockup

### ISSUE THREAD

**Issue by behlendorf** [zfsonlinux/zfs#1274]
Am 04.02.2013 07:03, schrieb Darik Horn:
>
> Try this:
>
>    # zfs set com.sun:auto-snapshot=false SSD/swap
>    # zfs set sync=always SSD/swap
>    # zfs set primarycache=none SSD/swap
>
> And repeat the test a second time.
Thx. I tried:

datakanja@multi-os-host:~$ zfs get all SSD/swap
NAME      PROPERTY               VALUE                  SOURCE
SSD/swap  type                   volume                 -
SSD/swap  creation               Mo Feb  4 16:11 2013   -
SSD/swap  used                   17,0G                  -
SSD/swap  available              17,2G                  -
SSD/swap  referenced             20K                    -
SSD/swap  compressratio          1.00x                  -
SSD/swap  reservation            none                   default
SSD/swap  volsize                16G                    local
SSD/swap  volblocksize           4K                     -
SSD/swap  checksum               on                     default
SSD/swap  compression            off                    default
SSD/swap  readonly               off                    default
SSD/swap  copies                 1                      default
SSD/swap  refreservation         17,0G                  local
SSD/swap  primarycache           none                   local
SSD/swap  secondarycache         all                    default
SSD/swap  usedbysnapshots        0                      -
SSD/swap  usedbydataset          20K                    -
SSD/swap  usedbychildren         0                      -
SSD/swap  usedbyrefreservation   17,0G                  -
SSD/swap  logbias                latency                default
SSD/swap  dedup                  off                    default
SSD/swap  mlslabel               none                   default
SSD/swap  sync                   always                 local
SSD/swap  refcompressratio       1.00x                  -
SSD/swap  written                20K                    -
SSD/swap  com.sun:auto-snapshot  false                  local

but even here, as soon as the regular swap partition ran out of space and swapping to zfs would kick in, the machine locked up again.

This is the test code to eat the RAM:

```
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

int main(int argc, char** argv) {
    int max = -1;
    int mb = 0;
    char* buffer;

    if(argc > 1)
        max = atoi(argv[1]);

    while((buffer=malloc(1024*1024)) != NULL && mb != max) {
        memset(buffer, 0, 1024*1024);
        mb++;
        printf("Allocated %d MB\n", mb);
    }
        return 0;
}
```

> If it works, then try:
>
>    # zfs set primarycache=metadata SSD/swap
>
> And repeat the test a third time.
>

-- 

         \|||/
         (o o)
  ----ooO-(_)-Ooo----

    Kilroy was here!
  And so was Datakanja

**Comment by ryao** [comment]
With zfsonlinux/spl#474, I am no longer able to cause deadlocks with swap on zvols on recent kernels.

**Comment by behlendorf** [comment]
Closing as stale, refer to the [swap section](https://github.com/zfsonlinux/zfs/wiki/FAQ#using-a-zvol-for-a-swap-device) of the wiki for additional configuration information.
