### ISSUE TITLE
Rebuild Performance

### ISSUE THREAD

**Issue by behlendorf** [zfsonlinux/zfs#1277]
http://wiki.lustre.org/images/f/ff/Rebuild_performance-2009-06-15.pdf

**Comment by kernelOfTruth** [comment]
that file moved - new place:

http://wiki.old.lustre.org/images/f/ff/Rebuild_performance-2009-06-15.pdf

**Comment by behlendorf** [comment]
Closing.  Sequential rebuilds were implemented in 0.8.

**Comment by MyPod** [comment]
Sequential rebuilds are already in git master.

**Comment by mailinglists35** [comment]
>already in git master.

I know, but "were implemented in 0.8" suggests 0.8 was already released, which is not.
