### ISSUE TITLE
INFO: task zfs:11829 blocked for more than 120 seconds.

### ISSUE THREAD

**Issue by byteharmony** [zfsonlinux/zfs#1301]
This is happening only on heavier load servers with slower system drives (USB Sticks running the base linux system) centos 6.3, ext4 with raid 1 for system drives. Seems to happen more when raid resync is allowed to go faster.

sysctl.conf: 
dev.raid.speed_limit_max = 5000
Helped but still happening, moving to 2000 (which will limit resync speed to 2MBps, pretty slow. This is USB2, usb3 may help, i think it'd be nice to increase the timeouts. This is usually only an issue onsystems with LOTS of snapshots lots of programs listing snapshots to send the right data back and forth.

This machine is on rc13, haven't started workon rc14 yet.
BK

INFO: task zfs:11829 blocked for more than 120 seconds.
"echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
zfs           D 0000000000000002     0 11829  11827 0x00000080
 ffff88068f84b9e8 0000000000000082 ffff88068f84baa8 ffff880841e2f538
 0000000000000000 ffff880841e2f500 ffff88086ce60aa0 0000000000000000
 ffff880841e2fab8 ffff88068f84bfd8 000000000000fb88 ffff880841e2fab8
Call Trace:
 [<ffffffff81500605>] rwsem_down_failed_common+0x95/0x1d0
 [<ffffffff81500763>] rwsem_down_write_failed+0x23/0x30
 [<ffffffff8127ea53>] call_rwsem_down_write_failed+0x13/0x20
 [<ffffffff814ffc62>] ? down_write+0x32/0x40
 [<ffffffff81092170>] ? autoremove_wake_function+0x0/0x40
 [<ffffffffa02bf2b9>] dsl_dataset_clone_swap+0x1d9/0x460 [zfs]
 [<ffffffffa02b1cea>] dmu_recv_end+0xaa/0x220 [zfs]
 [<ffffffffa02a9d61>] ? dmu_objset_rele+0x11/0x20 [zfs]
 [<ffffffffa0312a91>] ? get_zfs_sb+0x61/0xd0 [zfs]
 [<ffffffffa0317cbf>] zfs_ioc_recv+0x8af/0xf50 [zfs]
 [<ffffffffa01c07db>] ? kmem_free_debug+0x4b/0x150 [spl]
 [<ffffffffa029ed69>] ? dbuf_rele_and_unlock+0x159/0x200 [zfs]
 [<ffffffffa01c07db>] ? kmem_free_debug+0x4b/0x150 [spl]
 [<ffffffffa02ec39e>] ? spa_name_compare+0xe/0x30 [zfs]
 [<ffffffffa02edc52>] ? spa_lookup+0x62/0xc0 [zfs]
 [<ffffffffa02e3bfc>] ? spa_open_common+0x23c/0x370 [zfs]
 [<ffffffffa031574d>] zfsdev_ioctl+0xfd/0x1d0 [zfs]
 [<ffffffff8118e4f2>] vfs_ioctl+0x22/0xa0
 [<ffffffff8118e694>] do_vfs_ioctl+0x84/0x580
 [<ffffffff812136c6>] ? security_file_permission+0x16/0x20
 [<ffffffffa03f84d3>] ? kvm_on_user_return+0x73/0x80 [kvm]
 [<ffffffff8118ec11>] sys_ioctl+0x81/0xa0
 [<ffffffff8100b0f2>] system_call_fastpath+0x16/0x1b

**Comment by behlendorf** [comment]
Closing.  This is no longer believed to be an issue with the latest code.
