### ISSUE TITLE
CONFIG_EFI_PARTITION has weird behavior with ZoL

### ISSUE THREAD

**Issue by devsk** [zfsonlinux/zfs#1316]
I did not have this kernel config option enabled when I created my pools. All my pools are visible and importable in a kernel which does not have this option enabled.

I have two kinds of pools: 1. with whole disks (3x1TB disks). 2. using individual partitions.

As soon as I enable this option in the kernel, the pools with whole disks are no longer visible (zpool import does not show them). The pools using the individual partitions continue to be importable.

One more quirk: I recently bought 2x4TB WD Black drives to run a mirror but I can't create a pool with those, with or without this option:

1. With this option in the kernel, the zpool create fails saying /dev/sdf1 does not exist, no matter whether the label on disk is msdos or gpt. I make sure that there is no partition on the disk before I fire the zpool create. ZFS seems to be creating two partitions if the label is "gpt".

2. With this option removed from the kernel, the zpool create creates the pool with 2TB of space avaliable.

My fundamental problem continues to be the missing existing pool with EFI_PARTITION enabled.

Please let me know what other information you need.

**Comment by behlendorf** [comment]
Closing, related to #489

**Comment by FeepingCreature** [comment]
Update: I'm having some success importing a pool created before CONFIG_EFI_PARTITION was required on. For some reason, all my labels ended up at 512-byte offsets from the start of the disk. So I just made loopback devices at a 512-byte offset and the pool imports fine.

As a more permanent solution I'm moving my zfs data into partitions with `tail -c +513 devfile1 |cat> devfile2p1`, and those also seem to import fine.
