### ISSUE TITLE
Heavy IO lockup from Linux 3.5->3.6 change

### ISSUE THREAD

**Issue by DeHackEd** [zfsonlinux/zfs#1342]
ryao says this may be mmap related. For now I'll dump the info I know here and update as I get more. Feel free to update the description if I take too long coming up with something better.

Hung task stack traces: http://pastebin.com/n2E2Mq6d

Slapd (OpenLDAP using BDB as its backend) is doing a replication database receive. It's slowed down by what I assume to be #1297 but that's not the issue.
<pre>
# zpool status
  pool: lxc-iscsi
 state: ONLINE
status: The pool is formatted using a legacy on-disk format.  The pool can
	still be used, but some features are unavailable.
action: Upgrade the pool using 'zpool upgrade'.  Once this is done, the
	pool will no longer be accessible on software that does not support
	feature flags.
  scan: scrub repaired 0 in 0h46m with 0 errors on Mon Mar  4 16:27:28 2013
config:

	NAME                                                       STATE     READ WRITE CKSUM
	lxc-iscsi                                                  ONLINE       0     0     0
	  mirror-0                                                 ONLINE       0     0     0
	    ip-10.50.8.10:3260-iscsi-iqn.2012-06.net.blahblahblah  ONLINE       0     0     0
	    ip-10.50.8.11:3260-iscsi-iqn.2012-06.net.blahblahblah  ONLINE       0     0     0

errors: No known data errors
</pre>

Host is a custom build kernel, KVM guest with 8 cores and 10 gigs of RAM. All ZFS options at default. Currently running build 0b4d1b5853791e1e447d74f0b229800d65b53071

Hang usually takes anywhere from 5-30 minutes to manifest itself. It may be a Linux kernel regression as a 3.2 kernel appeared stable but a 3.8 kernel would jam up pretty quickly. Some earlier kernels (~3.4) would run overnight successfully. I'm trying to bisect a possible upstream regression but the irregular nature of the lockup means some guesswork is involved.

Update history: Old title was "Heavy IO lockup"

**Comment by behlendorf** [comment]
The original reported issue was [determined to be due to a kernel bug](https://github.com/zfsonlinux/zfs/issues/1342#issuecomment-14843995) by @DeHackEd, the original reporter.  It's possible subsequent improvements in ZoL have also improved things.  Closing.
