### ISSUE TITLE
zfs receive does neither support -o property=value nor -x property

### ISSUE THREAD

**Issue by maverick1601** [zfsonlinux/zfs#1350]
Receiving ZFS datastreams on Solaris allows properties to be overwritten using -o or ignored using -x, which is useful, e.g. to enable compression on replication servers. This is not supported in ZoL's zfs command.

**Comment by micw** [comment]
I wonder a bit because on my debian wheezy box zfs recv shows:

    usage:
        receive [-vnFu] [-d | -e] [-o <property>] ... [-x <property>] ... [-l <filesystem|volume>] ...  <filesystem|volume|snapshot>
    
    For the property list, run: zfs set|get

So I expected that was already included. Today I set up a new box with debian jessie (official zfs build as well, same version: 0.6.4) - and there "-x"/"-o" are missing:

    usage:
	receive [-vnFu] <filesystem|volume|snapshot>
	receive [-vnFu] [-d | -e] <filesystem>
    
    For the property list, run: zfs set|get

Note that the reference to the property list is still there...

**Comment by FransUrbo** [comment]
> I wonder a bit because on my debian wheezy box zfs recv shows:
> 
Are you using my debs on that machine? I included the #1867 pull
request in those.
> So I expected that was already included. Today I set up a new box with debian jessie (official zfs build as well, same version: 0.6.4) - and there "-x"/"-o" are missing:
What version exactly? Because it should have been included in
the Jessie packages as well.

**Comment by micw** [comment]
Wheezy: zfsutils 0.6.4-1.1-1-wheezy
Jessie: zfsutils 0.6.4-1.2-1

**Comment by FransUrbo** [comment]
> Wheezy: zfsutils 0.6.4-1.1-1-wheezy
> Jessie: zfsutils 0.6.4-1.2-1
> 
Hmm, that's weird. I have to investigate this. The packaging should be the same,  as should the pull requests etc being applied.

**Comment by chani** [comment]
I am not sure where to post this and I am a bit confused due to the several issues for -o and -x here. What is the current state? From my tests neither -x is working nor overriding using -o is with 0.6.5.4 regardless of -p, is that correct?

**Comment by devZer0** [comment]
i`m also sadly missing this feature

**Comment by tinuzz** [comment]
And to add to the confusion, the official ZoL packages in Debian are also missing this feature, so when you upgrade from ZoL provided 0.6.5.7-8-* to Debian provided 0.6.5.8-1, you face the regression of losing -x / -o support :-(
