### ISSUE TITLE
Copying data from snapshot slows pool down to 1 MB/s

### ISSUE THREAD

**Issue by basic6** [zfsonlinux/zfs#1356]
This is about a ZPOOL (RAIDZ2) with several datasets. Dataset X (1.6T) has a snapshot.
When copying data (200G, using cp) from that snapshot back onto the current dataset X, write speeds seem to decrease significantly.
While running this copy job, copying a file from the snapshot onto another dataset Y of the same pool (using dd):
3318784+0 records in
3318784+0 records out
1699217408 bytes (1.7 GB) copied, 1467.51 s, 1.2 MB/s

Copying zero's onto X during that time:
$ dd if=/dev/zero of=test1Gzero bs=1M count=1024
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB) copied, 38.3023 s, 28.0 MB/s

Reading a file from the snapshot during that time (of=/dev/null):
3318784+0 records in
3318784+0 records out
1699217408 bytes (1.7 GB) copied, 46.8674 s, 36.3 MB/s

Writing zero's before the copy job started (system idle):
$ dd if=/dev/zero of=test1Gzero bs=1M count=1024 
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB) copied, 2.58445 s, 415 MB/s

**Comment by behlendorf** [comment]
Closing as stale.
