### ISSUE TITLE
zfs send takes a long time before data is sent

### ISSUE THREAD

**Issue by byteharmony** [zfsonlinux/zfs#1357]
I can't say this is critical, but given the magic the team has put out lately I could see someone making this improvement.

When I do a zfs send I usually send the data into pipe viewer (pv) which shows how much data is flowing through the pipe. In some cases with pools with large numbers of volumes and snapshots the data takes time before it starts flowing. Sometimes over a minute.

BK

**Comment by behlendorf** [comment]
Closing as stale.  Several zfs send/recv performance improvements have been made to master.
