### ISSUE TITLE
zpool import internal error

### ISSUE THREAD

**Issue by darkfires** [zfsonlinux/zfs#1385]
Hi,

Just had a power failure, when the power came back I have been unable to remount or see my ZFS pool on it's own

```
# zpool import -a
internal error: Value too large for defined data type
Aborted
# zpool status
no pools available
# ls -l /etc/zfs/zpool.cache
ls: cannot access /etc/zfs/zpool.cache: No such file or directory
```

I eventually got it to mount with zpool import -f 14468898483350887172, but I do not believe it should be erroring like that with import -a ?

Thanks

**Comment by behlendorf** [comment]
Closing as stale, the `zpool import` code has undergone numerous improvements since this was initially reported.  Please go ahead and open a new issue if this behavior is observed again.
