### ISSUE TITLE
Fix errors detected by cppcheck

### ISSUE THREAD

**Issue by ghost** [zfsonlinux/zfs#1392]
While running cppcheck on your code (git head 9d248f7), it found these memory leaks and two other issues, they might be false positives, but I'll let you decided. (You might be interested in running it yourself and with more options).

C:\Cppcheck>cppcheck --quiet C:\repo\zfs
[C:\repo\zfs\cmd\zpool\zpool_vdev.c:1319]: (error) Memory leak: child
[C:\repo\zfs\lib\libefi\rdwr_efi.c:1036]: (error) Memory leak: efi_label
[C:\repo\zfs\lib\libzfs\libzfs_sendrecv.c:2824]: (error) Dereferencing 'cp' after it is deallocated / released
[C:\repo\zfs\lib\libzfs\libzfs_util.c:953]: (error) Dangerous usage of 'path_name' (strncpy doesn't always null-terminate it).

**Comment by behlendorf** [comment]
Several additional errors have been introduced since this issue was originally filed.  Ideally, we could resolve this small number of error and then add this is a step in the automated PR testing.

```
$ cppcheck . --force --quiet
[cmd/zinject/zinject.c:1068]: (error) Uninitialized variable: dataset
[cmd/zpool/zpool_iter.c:317]: (error) Uninitialized variable: nvroot
[cmd/zpool/zpool_vdev.c:1526]: (error) Memory leak: child
[lib/libuutil/uu_misc.c:207]: (error) va_list 'args' was opened but not closed by va_end().
[lib/libzfs/libzfs_sendrecv.c:3279]: (error) Dereferencing 'cp' after it is deallocated / released
[module/zfs/vdev_raidz_math_impl.h:113]: (error) Syntax error. Not enough parameters for macro 'VR4_'.
[tests/zfs-tests/cmd/randfree_file/randfree_file.c:90]: (error) Memory leak: buf
```
