### ISSUE TITLE
zvol IO errors and SSD array lockup

### ISSUE THREAD

**Issue by byteharmony** [zfsonlinux/zfs#1405]
Today I had an array of 4x intel SSD drives configured in a raidz1 connected to a dell t310 onboard perc controller fail. The error was bizzar, IO errors accessing zvol?? I've seen checksum errors in the past with failing volumes but there were no check sum errors on the ssd individual volumes. 

The system accessing the volume was still kind of working, a few KBps. Here's where it gets really interesting. I was able to do a zfs send to the spindle based array on the machine and move data at a sustained rate of over 100MBps (as fast as the spindles could take it). The system locked up 2x during the transfer, but this was MUCH faster than getting the data from the spindles on another system that had my backup. 

So after the data was on the spindles the system has run for 11 + hours now with no problems without the SSD volumes in the box any longer. Some loads really high (20 - 30) with no reliability issues. 

I thought perhaps it was the controller, we've had some issues with SSD volumes on unified storage systems (SAS/SATA). So I put the intel drives on an intel onboard controller system that has run with 4 spindles for at least 2 months no issues. The SSD drives imported just fine.  Again I tested doing zfs send and again the transfer rates were as high as the spindles could take it. Again the system would crash within minutes. 

Thinking the crashes were load based I sent the zfs data through a rate limited pipe restricting transfer to 10 MBps again the system would lockup. No errors during all these lockups. The only errors were found during the first failure with the zvol errors.

I'm not sure yet how this SSD volume is crashing the system. Tomorrow if I REALLY need the speed (and I don't use the SAS drives I'm going to have the team put together tomorrow morning) I'll need to see if I can get some kernel debug info via Serial. 

Maybe you've got some ideas while i sleep?

In general I can tell you SSD zvols tend to slow as time progresses and drives grow to more than 50% full. Any ideas? 

Thanks,
BK

**Comment by ilovezfs** [comment]
This looks like it had happened before in https://github.com/zfsonlinux/zfs/issues/1343

O3X is getting the same panic: https://github.com/openzfsonosx/zfs/issues/343

**Comment by behlendorf** [comment]
Closing.  Resolved log ago by a127e841dee20340b300e98b6d4b62f9ad41a47b/
