### ISSUE TITLE
Kernel oops every few hours

### ISSUE THREAD

**Issue by richardcooper** [zfsonlinux/zfs#1414]
I am running CentOS 6.4 on an x86_64 server with 12 GB of RAM. Kernel version is kernel-2.6.32-358.2.1.el6.x86_64. ZFS version is zfs-0.6.1-1.el6.x86_64 installed as per http://zfsonlinux.org/epel.html.

The server has 7 * 3TB drives. They are GPT partitioned with a few GB taken to provide ext4 "/" "/boot" and swap partitions. The bulk of the drive is then used to create a raidz1 pool mounted on /srv. `Zpool scrub` completes without finding any problems.

I am testing zfs by running a workload of 1 to 10 concurrent rsync jobs reading from the network and writing to the zfs. This workload causes the server to consistently crash with a kernel oops after approximately 2 to 6 hours of uptime.

Below is the log from a kernel crash dump.

	BUG: unable to handle kernel paging request at ffffc900a7404419
	IP: [<ffffffffa0411c6b>] zap_leaf_array_read+0x19b/0x200 [zfs]
	PGD 33feb6067 PUD 2bb2df067 PMD 2935e2067 PTE 0
	Oops: 0000 [#1] SMP 
	last sysfs file: /sys/firmware/memmap/10/type
	CPU 5 
	Modules linked in: sunrpc ipv6 ipt_REJECT nf_conntrack_ipv4 nf_defrag_ipv4 xt_state nf_conntrack iptable_filter ip_tables zfs(P)(U) zcommon(P)(U) znvpair(P)(U) zavl(P)(U) zunicode(P)(U) spl(U) zlib_deflate serio_raw i2c_i801 iTCO_wdt iTCO_vendor_support sg r8169 mii i7core_edac edac_core shpchp ext4 mbcache jbd2 raid456 async_raid6_recov async_pq raid6_pq async_xor xor async_memcpy async_tx raid1 sd_mod crc_t10dif pata_acpi ata_generic pata_jmicron ahci nouveau ttm drm_kms_helper drm i2c_algo_bit i2c_core mxm_wmi video output wmi dm_mirror dm_region_hash dm_log dm_mod [last unloaded: scsi_wait_scan]

	Pid: 5435, comm: rsync Tainted: P           ---------------    2.6.32-358.2.1.el6.x86_64 #1 MSI MS-7522/MSI X58 Pro-E (MS-7522)
	RIP: 0010:[<ffffffffa0411c6b>]  [<ffffffffa0411c6b>] zap_leaf_array_read+0x19b/0x200 [zfs]
	RSP: 0018:ffff880102c2bb28  EFLAGS: 00010206
	RAX: ffffc900a7284000 RBX: ffff88021b4b2440 RCX: ffffc900a7404418
	RDX: ffffc900a7404419 RSI: 000000000000ffff RDI: ffff88021b4b2440
	RBP: ffff880102c2bb48 R08: 0000000000000008 R09: 0000000000000001
	R10: 0000000000000200 R11: fb57bc0000000000 R12: ffff880102c2bd58
	R13: 0000000000000000 R14: ffff880102c2bba8 R15: ffff880336a06a80
	FS:  00007fe1fa764700(0000) GS:ffff8800282a0000(0000) knlGS:0000000000000000
	CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
	CR2: ffffc900a7404419 CR3: 0000000137c14000 CR4: 00000000000007e0
	DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
	DR3: 0000000000000000 DR6: 00000000ffff0ff0 DR7: 0000000000000400
	Process rsync (pid: 5435, threadinfo ffff880102c2a000, task ffff88033627c080)
	Stack:
	 ffff880102c2bba8 0000000000000001 0000000000000000 ffff880102c2bba8
	<d> ffff880102c2bb78 ffffffffa04122c2 ffff880102c2bd58 0000000000000002
	<d> ffff880102c2bd08 ffff88021b4b2440 ffff880102c2bc08 ffffffffa041073b
	Call Trace:
	 [<ffffffffa04122c2>] zap_entry_read+0x72/0x90 [zfs]
	 [<ffffffffa041073b>] fzap_cursor_retrieve+0x29b/0x2a0 [zfs]
	 [<ffffffffa03aa4d9>] ? dbuf_find+0xf9/0x100 [zfs]
	 [<ffffffffa04155cb>] zap_cursor_retrieve+0x17b/0x2f0 [zfs]
	 [<ffffffffa03b4679>] ? dmu_prefetch+0x169/0x220 [zfs]
	 [<ffffffffa0435f0a>] zfs_readdir+0x17a/0x510 [zfs]
	 [<ffffffff811961e0>] ? filldir+0x0/0xe0
	 [<ffffffff8150f116>] ? __mutex_lock_killable_slowpath+0x116/0x1d0
	 [<ffffffff811961e0>] ? filldir+0x0/0xe0
	 [<ffffffffa044ba7c>] zpl_readdir+0x5c/0x90 [zfs]
	 [<ffffffff811961e0>] ? filldir+0x0/0xe0
	 [<ffffffff81196460>] vfs_readdir+0xc0/0xe0
	 [<ffffffff811965e9>] sys_getdents+0x89/0xf0
	 [<ffffffff8100b072>] system_call_fastpath+0x16/0x1b
	Code: 66 41 89 04 24 eb a9 8b 4f 30 0f b7 f6 48 8b 47 40 48 8d 14 76 83 e9 05 41 d3 e2 49 63 ca 48 8d 14 91 48 8d 4c 50 30 48 8d 51 01 <0f> b6 49 01 0f b6 42 07 48 c1 e1 38 48 09 c8 0f b6 4a 01 48 c1 
	RIP  [<ffffffffa0411c6b>] zap_leaf_array_read+0x19b/0x200 [zfs]
	 RSP <ffff880102c2bb28>
	CR2: ffffc900a7404419

**Comment by behlendorf** [comment]
Closing as stale.  All of this code has been has been reworked and improved since 2013.
