### ISSUE TITLE
implement IO delay histograms

### ISSUE THREAD

**Issue by nedbass** [zfsonlinux/zfs#1446]
Histograms of IO request times would help storage administrators quickly identify slow disks that may be negatively impacting overall pool performance.
ZFS already times each request for purposes of generating events for outliers, so it should be easy to track this data.  A possible approach follows.

- Store the per-vdev histogram as a packed nvpair in the vdev label.  The histogram contains per-bucket counters containing the history of all requests since it was added to the pool.
- Add a new command 'zpool iodelay [-v] [-r range] \<pool> [vdev]' to display the histograms.  The -r option allows selection of arbitrary time ranges, defaulting to the life of the pool or device.  The -v option displays data for all vdevs.  Statistics for the pool and for virtual vdevs are automatically aggregated from the physical vdev data.
- Enhance 'zpool iostat' by displaying IO delay statistics when extra verbosity is requested (i.e. -vv).  Distill a few statistics that would make suspect drives stand out.  For example, average request times for device lifetime, last day, and last iostat sample interval.   Suspect drives may show wide deviation over time compared to healthy drives.

**Comment by behlendorf** [comment]
Closing this functionally was added in commit 193a37cb2430960ce759daf12ce5cc804818aba1.
