### ISSUE TITLE
Potential data race issue with zpool status messages

### ISSUE THREAD

**Issue by aarond10** [zfsonlinux/zfs#1490]
It looks like there's a race issue in the zpool status code to do with resilvering time. I think I managed to zpool status after resilvering had finished but before the time taken to resilver was set. See output below. 

# zpool status
  pool: tank
 state: ONLINE
status: One or more devices is currently being resilvered.  The pool will
	continue to function, possibly in a degraded state.
action: Wait for the resilver to complete.
  scan: resilver in progress since Sat Jun  1 16:52:09 2013
    1.75G scanned out of 2.38T at 2.30M/s, 300h54m to go
    1.63G resilvered, 0.07% done
config:

	NAME                                       STATE     READ WRITE CKSUM
	tank                                       ONLINE       0     0     0
	  mirror-0                                 ONLINE       0     0     0
	    scsi-SATA_ST31000524AS_9VPDLQ1K        ONLINE       0     0     0
	    scsi-SATA_ST31500341AS_9VS57VTT-part3  ONLINE       0     0     0
	  mirror-1                                 ONLINE       0     0     0
	    scsi-SATA_ST2000DL003-9VT_6YD1LJL9     ONLINE       0     0     0
	    scsi-SATA_ST2000DL003-9VT_5YD6JQ0G     ONLINE       0     0    12  (resilvering)

errors: No known data errors
# zpool status
  pool: tank
 state: ONLINE
status: One or more devices has experienced an unrecoverable error.  An
	attempt was made to correct the error.  Applications are unaffected.
action: Determine if the device needs to be replaced, and clear the errors
	using 'zpool clear' or replace the device with 'zpool replace'.
   see: http://zfsonlinux.org/msg/ZFS-8000-9P
  scan: resilvered 1.65G in 307445734561445285h24m with 0 errors on Thu Jan  1 10:00:00 1970
config:

	NAME                                       STATE     READ WRITE CKSUM
	tank                                       ONLINE       0     0     0
	  mirror-0                                 ONLINE       0     0     0
	    scsi-SATA_ST31000524AS_9VPDLQ1K        ONLINE       0     0     0
	    scsi-SATA_ST31500341AS_9VS57VTT-part3  ONLINE       0     0     0
	  mirror-1                                 ONLINE       0     0     0
	    scsi-SATA_ST2000DL003-9VT_6YD1LJL9     ONLINE       0     0     0
	    scsi-SATA_ST2000DL003-9VT_5YD6JQ0G     ONLINE       0     0    12

errors: No known data errors
# zpool status
  pool: tank
 state: ONLINE
status: One or more devices has experienced an unrecoverable error.  An
	attempt was made to correct the error.  Applications are unaffected.
action: Determine if the device needs to be replaced, and clear the errors
	using 'zpool clear' or replace the device with 'zpool replace'.
   see: http://zfsonlinux.org/msg/ZFS-8000-9P
  scan: resilvered 1.65G in 0h12m with 0 errors on Sat Jun  1 17:05:08 2013
config:

	NAME                                       STATE     READ WRITE CKSUM
	tank                                       ONLINE       0     0     0
	  mirror-0                                 ONLINE       0     0     0
	    scsi-SATA_ST31000524AS_9VPDLQ1K        ONLINE       0     0     0
	    scsi-SATA_ST31500341AS_9VS57VTT-part3  ONLINE       0     0     0
	  mirror-1                                 ONLINE       0     0     0
	    scsi-SATA_ST2000DL003-9VT_6YD1LJL9     ONLINE       0     0     0
	    scsi-SATA_ST2000DL003-9VT_5YD6JQ0G     ONLINE       0     0    12

**Comment by behlendorf** [comment]
Closing as a duplicte of #5186.  This relatively harmless issue is likely still here and needs someone to investigate it.
