### ISSUE TITLE
Module build fails RT kernels - PlanetCCRMA - Ubuntu linux-low-latency

### ISSUE THREAD

**Issue by witchbutter** [zfsonlinux/zfs#1510]
Just adding this issue per the FAQ.  I can't get ZFS to install on any RT kernel that I've tried for Fedora 18.  Here is the error after a clean install:
<pre><code>[root@~]# yum install zfs
Loaded plugins: langpacks, presto, refresh-packagekit
zfs                                                                                                                  | 2.9 kB  00:00:00     
zfs/primary_db                                                                                                       | 6.5 kB  00:00:00     
Resolving Dependencies
--> Running transaction check
---> Package zfs.x86_64 0:0.6.1-1.fc18 will be installed
--> Processing Dependency: zfs-test = 0.6.1 for package: zfs-0.6.1-1.fc18.x86_64
--> Processing Dependency: zfs-dracut = 0.6.1 for package: zfs-0.6.1-1.fc18.x86_64
--> Processing Dependency: spl = 0.6.1 for package: zfs-0.6.1-1.fc18.x86_64
--> Processing Dependency: zfs-kmod >= 0.6.1 for package: zfs-0.6.1-1.fc18.x86_64
--> Running transaction check
---> Package spl.x86_64 0:0.6.1-1.fc18 will be installed
--> Processing Dependency: spl-kmod >= 0.6.1 for package: spl-0.6.1-1.fc18.x86_64
---> Package zfs-dkms.noarch 0:0.6.1-1.fc18 will be installed
---> Package zfs-dracut.x86_64 0:0.6.1-1.fc18 will be installed
---> Package zfs-test.x86_64 0:0.6.1-1.fc18 will be installed
--> Processing Dependency: lsscsi for package: zfs-test-0.6.1-1.fc18.x86_64
--> Running transaction check
---> Package lsscsi.x86_64 0:0.26-2.fc18 will be installed
---> Package spl-dkms.noarch 0:0.6.1-1.fc18 will be installed
--> Finished Dependency Resolution

Dependencies Resolved
...

Running Transaction Check
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : spl-dkms-0.6.1-1.fc18.noarch                                                                                             1/7 
Loading new spl-0.6.1 DKMS files...
First Installation: checking all kernels...
Building only for 3.8.13-201.rt8.1.fc18.ccrma.x86_64.rt
Building initial module for 3.8.13-201.rt8.1.fc18.ccrma.x86_64.rt
Error! Bad return status for module build on kernel: 3.8.13-201.rt8.1.fc18.ccrma.x86_64.rt (x86_64)
Consult /var/lib/dkms/spl/0.6.1/build/make.log for more information.
warning: %post(spl-dkms-0.6.1-1.fc18.noarch) scriptlet failed, exit status 10
Non-fatal POSTIN scriptlet failure in rpm package spl-dkms-0.6.1-1.fc18.noarch
  Installing : spl-0.6.1-1.fc18.x86_64                                                                                                  2/7 
  Installing : zfs-dkms-0.6.1-1.fc18.noarch                                                                                             3/7 
Loading new zfs-0.6.1 DKMS files...
First Installation: checking all kernels...
Building only for 3.8.13-201.rt8.1.fc18.ccrma.x86_64.rt
Building initial module for 3.8.13-201.rt8.1.fc18.ccrma.x86_64.rt
configure: error: 
	*** Please make sure the kmod spl devel <kernel> package for your
	*** distribution is installed then try again.  If that fails you
	*** can specify the location of the spl objects with the
	*** '--with-spl-obj=PATH' option.
Error! Bad return status for module build on kernel: 3.8.13-201.rt8.1.fc18.ccrma.x86_64.rt (x86_64)
Consult /var/lib/dkms/zfs/0.6.1/build/make.log for more information.
warning: %post(zfs-dkms-0.6.1-1.fc18.noarch) scriptlet failed, exit status 10
Non-fatal POSTIN scriptlet failure in rpm package zfs-dkms-0.6.1-1.fc18.noarch
  Installing : lsscsi-0.26-2.fc18.x86_64                                                                                                4/7 
  Installing : zfs-dracut-0.6.1-1.fc18.x86_64                                                                                           5/7 
  Installing : zfs-0.6.1-1.fc18.x86_64                                                                                                  6/7 
  Installing : zfs-test-0.6.1-1.fc18.x86_64                                                                                             7/7 
  Verifying  : zfs-test-0.6.1-1.fc18.x86_64                                                                                             1/7 
  Verifying  : zfs-dracut-0.6.1-1.fc18.x86_64                                                                                           2/7 
  Verifying  : spl-dkms-0.6.1-1.fc18.noarch                                                                                             3/7 
  Verifying  : lsscsi-0.26-2.fc18.x86_64                                                                                                4/7 
  Verifying  : spl-0.6.1-1.fc18.x86_64                                                                                                  5/7 
  Verifying  : zfs-0.6.1-1.fc18.x86_64                                                                                                  6/7 
  Verifying  : zfs-dkms-0.6.1-1.fc18.noarch                                                                                             7/7 

Installed:
  zfs.x86_64 0:0.6.1-1.fc18                                                                                                                 

Dependency Installed:
  lsscsi.x86_64 0:0.26-2.fc18         spl.x86_64 0:0.6.1-1.fc18         spl-dkms.noarch 0:0.6.1-1.fc18    zfs-dkms.noarch 0:0.6.1-1.fc18   
  zfs-dracut.x86_64 0:0.6.1-1.fc18    zfs-test.x86_64 0:0.6.1-1.fc18   

Complete!
</code></pre>

**Comment by K1773R** [comment]
seems @ryao gave up on this, anyone else capable on fixing this?

**Comment by K1773R** [comment]
This is still an issue. I'm affected as i do audio stuff where i need a low-latency/rt kernel.

**Comment by kernelOfTruth** [comment]
@K1773R would using a kernel with

```
threadirqs
```

appended to the bootup parameters

and additionally running a BFS-patched kernel be a temporary improvement ?

**Comment by K1773R** [comment]
@kernelOfTruth im already using threadirqs, w/o its even worse. i didnt try a bfs patched kernel so far, im using noop.

**Comment by behlendorf** [comment]
@K1773R could you please post in the build failure you get with 0.6.5.1?  A lot has changed since the original post.

**Comment by K1773R** [comment]
@behlendorf i just tried compiling 0.6.5.1 on a 14.04 ubuntu with the default linux-lowlatency.. and it worked! seems i tried a somewhat older version before.

**Comment by behlendorf** [comment]
@K1773R that's great news.  I thought that might be the case since the code implicated in the build failure above has been dropped.  Please let us know how it works for you and if everything looks good we'll close this out.

**Comment by K1773R** [comment]
so far it works really well, not a single xrun :) i really appreciate this!

**Comment by K1773R** [comment]
after 2 days of using it, there hasnt be a single problem.

**Comment by kernelOfTruth** [comment]
sweet :+1:

**Comment by behlendorf** [comment]
Nice!  OK, then I'm going to call this one fixed.  Enjoy!
