### ISSUE TITLE
ARC memory pressure is pushing into swap

### ISSUE THREAD

**Issue by byteharmony** [zfsonlinux/zfs#1514]
When running a system with many tasks AND zfs the RAM can fill. When it fills the ARC is supposed to reduce itself. At present I have swappiness set at 0, but if RAM is full instead of the ARC reducing the system is pushing into swap. Swap based ARC is not good.

Any ideas other than to make ARC so small that it's not an issue (I used to run at 1G, but 1G gives poor performance).

**Comment by behlendorf** [comment]
@byteharmony is this swap issue something you're still seeing or can this be closed?  I expect that ca0bf58d65f77e944b9905571df9a2eae647aeca, which is in the 0.6.5 releases, should have improved this.  The ABD patches should further improve things.

**Comment by behlendorf** [comment]
Closing as stale, refer to the [swap section](https://github.com/zfsonlinux/zfs/wiki/FAQ#using-a-zvol-for-a-swap-device) of the wiki for additional configuration information.
