### ISSUE TITLE
Removing cache device fails

### ISSUE THREAD

**Issue by huiser** [zfsonlinux/zfs#1530]
I try to remove a cache device from my pool, but it fails:

<pre>
 zpool status
   pool: data
  state: ONLINE
   scan: scrub repaired 0 in 6h50m with 0 errors on Mon Jun 17 11:53:35 2013
 config:

	NAME                                 STATE     READ WRITE CKSUM
	data                                 ONLINE       0     0     0
	  mirror-0                           ONLINE       0     0     0
	    ata-ST3000DM001-1CH166_Z1F0WPCZ  ONLINE       0     0     0
	    ata-ST3000DM001-1CH166_Z1F0XJRS  ONLINE       0     0     0
	cache
	  l2arc                              UNAVAIL      0     0     0

 errors: No known data errors
</pre>

<pre>
 #zpool remove data l2arc
 cannot remove l2arc: no such device in pool
</pre>

OS: Ubuntu 12.04 LTS amd64

<pre>
dpkg -l | grep zfs
ii  dkms                              2.2.0.3-1ubuntu3.1+zfs6~precise1 Dynamic Kernel Module Support Framework
ii  libzfs1                           0.6.1-1~precise                  Native ZFS filesystem library for Linux
ii  mountall                          2.36.4-zfs2                      filesystem mounting tool
ii  ubuntu-zfs                        7~precise                        Native ZFS filesystem metapackage for Ubuntu.
ii  zfs-dkms                          0.6.1-1~precise                  Native ZFS filesystem kernel modules for Linux
ii  zfsutils                          0.6.1-1~precise                  Native ZFS management utilities for Linux
</pre>

**Comment by DanielSmedegaardBuus** [comment]
Funny, just today I finally got around to upgrade my server to Ubuntu 14.10, and I did some changes to my pool configuration while I was at it. I have two SSDs, and whereas one was previously dedicated as a cache device, this time I opted for partitioning the two to use two cache devices instead.

I did this with an Ubuntu LiveCD, and had the SSDs partitioned with GPTs, and I used their labels to add the partitions as cache devices /dev/disk/by-partlabel/zfs-cache-a and -b.

As it turned out, the Ubuntu Server installer wasn't too happy about the GPTs when it came to installing GRUB, so I repartitioned with MBRs instead. Naturally, when importing the pool afterwards, "zfs-cache-a" and "zfs-cache-b" were both UNAVAIL, and I was unable to remove them as described in this thread.

zfs -C didn't mention them, but zfs -s did list the full path (and I could still remember it anyway), so I was able to remove the devices using zpool remove titanic /dev/disk/by-partlabel/zfs-cache-a and -b.

**Comment by AdamDanischewski** [comment]
I just started playing around with ZFS on Linux (Ubuntu 14.04) and I had this same problem, my zpool status showed the device name without the /disk/
`    (trusty)cronkilla@localhost:/MYWINPOOL$ sudo zpool status`
`     pool: MYWINPOOL`
`       state: ONLINE`
`        scrub: scrub completed after 0h1m with 0 errors on Tue Feb 17 08:39:03 2015`
`      config:`

	NAME                                                        STATE     READ WRITE CKSUM
	MYWINPOOL                                                   ONLINE       0     0     0
	  mirror-0                                                  ONLINE       0     0     0
	    disk/by-id/usb-Generic_STORAGE_DEVICE_FUNWAY091147-0:0  ONLINE       0     0    82  492K repaired
	    disk/by-id/usb-Generic_STORAGE_DEVICE_FUNWAY091067-0:0  ONLINE       0     0     0  236K repaired
	  mirror-1                                                  ONLINE       0     0     0
	    disk/by-id/usb-Generic_STORAGE_DEVICE_FUNWAY091552-0:0  ONLINE       0     0     0  53K repaired
	    disk/by-id/usb-Generic_STORAGE_DEVICE_FUNWAY091125-0:0  ONLINE       0     0     0  50K repaired
	cache
	  disk/by-id/usb-Generic_STORAGE_DEVICE_FUNWAY090855-0:0    ONLINE       0     0     0

     (trusty)cronkilla@localhost:/MYWINPOOL$ sudo zpool remove MYWINPOOL disk/by-id/usb-  Generic_STORAGE_DEVICE_FUNWAY090855-0:0
     cannot remove disk/by-id/usb-Generic_STORAGE_DEVICE_FUNWAY090855-0:0: no such device in pool

Yet when I tried again using the same exact syntax that I used to create the cache, with /dev/ in front it worked: 

     (trusty)cronkilla@localhost:/MYWINPOOL$ sudo zpool remove MYWINPOOL /dev/disk/by-id/usb-Generic_STORAGE_DEVICE_FUNWAY090855-0:0
     (trusty)cronkilla@localhost:/MYWINPOOL$

     pool: MYWINPOOL
     state: ONLINE
     scrub: scrub completed after 0h1m with 0 errors on Tue Feb 17 08:39:03 2015
    config:
     NAME                                                        STATE     READ WRITE CKSUM                           MYWINPOOL                                                   ONLINE       0     0     0
 	  mirror-0                                                  ONLINE       0     0     0
	    disk/by-id/usb-Generic_STORAGE_DEVICE_FUNWAY091147-0:0  ONLINE       0     0     0  492K repaired
	    disk/by-id/usb-Generic_STORAGE_DEVICE_FUNWAY091067-0:0  ONLINE       0     0     0  236K repaired
	  mirror-1                                                  ONLINE       0     0     0
	    disk/by-id/usb-Generic_STORAGE_DEVICE_FUNWAY091552-0:0  ONLINE       0     0     0  53K repaired
	    disk/by-id/usb-Generic_STORAGE_DEVICE_FUNWAY091125-0:0  ONLINE       0     0     0  50K repaired

Device cache is now gone. 

Not sure how you can find out what the exact syntax you used to create the cache if you don't know it offhand, however if you are the only user think of your habits or try guessing what possible commands created it. Otherwise I'm not sure if the -f option will work on a cache, but it may be worth a shot something like `zpool remove -f POOL CACHE_DEVICE`

**Comment by GregorKopka** [comment]
'zpool history' might have the information you seek.

**Comment by dorvan** [comment]
Same problem today with git master version....

**Comment by jdieter** [comment]
Ok, I've managed to come up with a workaround that at least worked for me.  Background is, I was converting from FreeNAS to zfsonlinux, and my old cache device was /dev/ada3b.

1. Add a new cache device, zpool add <pool> cache <new-cache-device>
2. Remove new cache device, zpool remove <pool> <new-cache-device>
3. In /dev, run mknod <old-cache-device> b <major of new-cache-device> <minor of new-cache-device>
4. zpool export <pool>
5. zpool import <pool>
At this point, your old cache device should say it's ONLINE rather than UNAVAIL
6. Run zdb -l /dev/<old-cache-device> to get guid
7. Run zpool remove <pool> <guid>

Voilà! At this point, the old cache device should be gone and you can either add a new cache device or continue without it.

**Comment by jdieter** [comment]
So, for me, I did the following

1. zpool add pool cache /dev/sdc4
2. zpool remove pool /dev/sdc4
3. ls -l /dev/sdc4
brw-rw----. 1 root disk 8, 36 Oct  2 12:34 /dev/sdc4
4. mknod /dev/ada3b b 8 36
5. zpool export pool
6. zpool import pool
    zpool status
  pool: pool
 state: ONLINE
  scan: scrub repaired 0 in 20h10m with 0 errors on Sun Sep 13 09:25:33 2015
config:

	NAME      STATE     READ WRITE CKSUM
	pool           ONLINE       0     0     0
	  raidz1-0   ONLINE       0     0     0
	    sda        ONLINE       0     0     0
	    sdb        ONLINE       0     0     0
	    sdd        ONLINE       0     0     0
	logs
	  sdc3        ONLINE       0     0     0
	cache
	  ada3b     ONLINE       0     0     0
7. zdb -l /dev/ada3b
--------------------------------------------
LABEL 0
--------------------------------------------
    version: 5000
    state: 4
    guid: 18390889124957047666
--------------------------------------------
LABEL 1
--------------------------------------------
    version: 5000
    state: 4
    guid: 18390889124957047666
--------------------------------------------
LABEL 2
--------------------------------------------
    version: 5000
    state: 4
    guid: 18390889124957047666
--------------------------------------------
LABEL 3
--------------------------------------------
    version: 5000
    state: 4
    guid: 18390889124957047666

8. zpool remove pool 18390889124957047666
    zpool status
  pool: pool
 state: ONLINE
  scan: scrub repaired 0 in 20h10m with 0 errors on Sun Sep 13 09:25:33 2015
config:

	NAME      STATE     READ WRITE CKSUM
	pool           ONLINE       0     0     0
	  raidz1-0   ONLINE       0     0     0
	    sda        ONLINE       0     0     0
	    sdb        ONLINE       0     0     0
	    sdd        ONLINE       0     0     0
	logs
	  sdc3        ONLINE       0     0     0

**Comment by huiser** [comment]
I followed your procedures, but after importing my pool again, status still give UNAVAIL

**Comment by jdieter** [comment]
For step 4, did you mknod /dev/gpt/l2arc or /dev/l2arc

**Comment by huiser** [comment]
Fixed :)

I tried 'mknod /dev/gpt/l2arc b 8 36' first, but that didn't work.

Originally the ZFS pool was created with following command:
zpool create data mirror gpt/disk1.nop gpt/disk2.nop cache gpt/l2arc

Steps to fix:
* created an empty partition somewhere:  /dev/sdb4
* created a directory:  /dev/gpt
* symlinked /dev/sdb4 to /dev/gpt/l2arc
* zpool export <pool>
* zpool import <pool>
* zpool status showed device 'l2arc' was ONLINE !!!!
* retrieved GUID of device 'l2arc':
 zdb -l /dev/gpt/l2arc  | grep guid
* zpool remove <pool> <guid>

Done :)

**Comment by jdieter** [comment]
Great!!  Glad to help!

**Comment by jdieter** [comment]
I'll modify my instructions to indicate that a symlink works as easily as mknod

**Comment by huiser** [comment]
Thanks for pointing in the right direction !

**Comment by thistleknot** [comment]
I had a similar issue:

# zdb -s tank

outputted ID:
/dev/disk/by-id/ata-MARVELL_Raid_VD_dcd8483d3baa0000-part2

# zpool remove tank /dev/disk/by-id/ata-MARVELL_Raid_VD_dcd8483d3baa0000-part2
# zpool status -v tank

**Comment by behlendorf** [comment]
The guid for a vdev can now be printed using the `-g` option to `zpool status`.  If this occurs again this option can be used to obtain the guid instead of having to use zdb.

**Comment by ThHirsch** [comment]
I am having the exact same problem, now with version 0.6.5.11-1 on debian9 (proxmox).
I had exact same config on 2 nodes of my cluster.
I was able to remove log and cache pool members for a failed disk (e.g. just removed the log/cache disk)
On one node this was not a problem at all. Imported the pool with -m option, then removed by GUIDs.
But on the other node (which was exactly same configuration level) I was NOT able to remove the log device. Removing it by GUID doen't give an error, but after that zpool status is still showing the device as UNAVAI but is not listing in zdb any more.
Any attempt to have it removed failed until now...
Is this still a known bug? Any mitigation known?

**Comment by AdamDanischewski** [comment]
Did you try my advice above?

**Comment by ThHirsch** [comment]
Yes - tried every possible device naming (getting GUIDs from zdb, getting IDs/paths from /dev/disk/by-....,  using the very same commandline from 'zpool history' when creating/adding the device.
Offlining it, Onlining it, trying to 'detach' first, and even 'replacing' it with a new device (which fails as well).
If I bring back the removed device, node boots up fine and is using the log device.
But even with having the log device online available (not missing any more), I am NOT able to remove and/or replace the device.

One thing that came to my attention is, that the log device which I can't remove is showing strange entries for usage  in 'zpool iostat -v' and in 'zpool list -v' (having Exabytes?!  used - 'E' in Size indicator?)
Output:
```
root@pven01:~# zpool iostat -v
                                          capacity     operations    bandwidth
pool                                   alloc   free   read  write   read  write
-------------------------------------  -----  -----  -----  -----  -----  -----
rpool                                  1.31T  4.13T      1     30  26.0K  85.3K
  raidz1                               1.31T  4.13T      1     30  25.2K  83.5K
    sdc2                                   -      -      0      9  9.25K  88.9K
    sdd2                                   -      -      0      9  9.18K  89.0K
    sde2                                   -      -      0      9  9.33K  89.1K
logs                                       -      -      -      -      -      -
  ata-ASMT109x-_Safe_2_Lx_DwY__-part1  **16.0E**  4.63G      0      0    884  1.77K
cache                                      -      -      -      -      -      -
  ata-ASMT109x-_Safe_2_Lx_DwY__-part2  60.2M  19.7G      0      1     86  40.5K
-------------------------------------  -----  -----  -----  -----  -----  -----

root@pven01:~# zpool list -v
NAME   SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
rpool  5.44T  1.31T  4.13T         -    16%    24%  1.00x  ONLINE  -
  raidz1  5.44T  1.31T  4.13T         -    16%    24%
    sdc2      -      -      -         -      -      -
    sdd2      -      -      -         -      -      -
    sde2      -      -      -         -      -      -
log      -      -      -         -      -      -
  ata-ASMT109x-_Safe_2_Lx_DwY__-part1  4.62G  16.0**E**  4.63G         -     0%  **3714566310%**
cache      -      -      -         -      -      -
  ata-ASMT109x-_Safe_2_Lx_DwY__-part2  19.8G  60.2M  19.7G         -     0%     0%

```
(I will try next to get a new device, partition it the same and link to it with by setting a link with the old name of now missing devices partition to the new partitin. 
Thus letting (hopfefully) using ZFS that pratition as if it were the old device, then trying to remove.

Any oder ideas/recommendations on how to remove this device?!
Any help or insight or some pointer to some know/suspected bug reports are greatly aprreciated.
