### ISSUE TITLE
fully automated testsuite

### ISSUE THREAD

**Issue by maci0** [zfsonlinux/zfs#1534]
I would like to automate building of kmod- packages for fedora. 

But instead of just building the packages and pushing them into an internal repo i would like to run some tests.

Ive seen there are some in the zfs-tests package but iirc nothing that would be like a full-scale test of most features in an automated fashion.

i would like to test it in an VM of course so i can add dozens of drives with different kinds of emulated controllers etc.

in my opinion there should be an automated testsuite to run a regression test on each commit, possibly via jenkins (which is also able to start/stop vms, etc etc etc)

**Comment by eses2014** [comment]
@FransUrbo: I am trying to install and run the ZFS test suite on CentOS box. I am very new to ZFS. What steps should I follow to install and run the test suite. Please forgive me, if this is not the right place to ask this question.

**Comment by FransUrbo** [comment]
> @FransUrbo: I am trying to install and run the ZFS test suite on CentOS box. I am very new to ZFS. What steps should I follow to install and run the test suite. Please forgive me, if this is not the right place to ask this question.
> 

If you don't know what you're doing, DO NOT INSTALL OR USE THIS!!!

It will, very (most) likely destroy your system if not careful!! This is, at the moment, ONLY (!!) for VERY experienced developers with in-depth knowledge of ZFS and ZoL.

If you insist, and your system and/or pool is destroyed without any trace and possibility to recover/retrieve, please do not come here and complain and/or create issues.


But what you're asking for is in README.md. It IS enough to get it to destroy your system, just be warned!=

**Comment by thegreatgazoo** [comment]
It seemed this PR added a new empty file _tests/zfs-tests/tests/stress/Makefile.am_. But _make distclean_ will remove this file:
```
% git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
% make distclean
% git status    
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    tests/zfs-tests/tests/stress/Makefile.am

no changes added to commit (use "git add" and/or "git commit -a")
```

If this file is needed and should be under version control, then _make distclean_ should not remove it.

**Comment by behlendorf** [comment]
@thegreatgazoo yup, you're right that's definitely a bug.  If you already have a fix for this please open a PR.
