### ISSUE TITLE
General protection faults with memory pressure

### ISSUE THREAD

**Issue by hyegeek** [zfsonlinux/zfs#1535]
I'm running a gentoo system with

gentoo-sources-3.2.45 (I've tried a lot over different version, on up to 3.8.x all seem equally unstable)
Xen 4.2

The machine has 8G of memory, but only 3.5 allocated to the dom0. zfs_arc_max set to 2147483648 running 4 VMs, but all are pretty low load.

The stability issues arise when backing up to or from this machine. Backups to the machine are with rsync backups from (to offsite server) are with zfs send over ssh. The last crash did not produce a general protection fault that I could capture, but I will include one that made it to my syslog server from a previous boot. Load at the time of fault and lockup was over 54 (had been hovering around 4 before something went wrong).

I have yet to see a crash until swap is used. I have swapiness set to 0, and things do great until I actually run out of memory and have to swap, though time from swap to crash varies from seconds to hours, so it seems more like a race condition than anything else.

Here's a general protection fault and trace from my syslog server

 Jun 18 12:16:00 river kernel: SLUB: Unable to allocate memory on node -1 (gfp=0x20)
Jun 18 12:16:00 river kernel: cache: kmalloc-4096, object size: 4096, buffer size: 4096, default order: 3, min order: 0
Jun 18 12:16:00 river kernel: node 0: slabs: 659, objs: 3893, free: 0
Jun 18 12:16:00 river kernel: z_wr_iss/0: page allocation failure: order:0, mode:0x4020
Jun 18 12:16:00 river kernel: Pid: 8903, comm: z_wr_iss/0 Tainted: P           O 3.2.46-gentoo.zfs #2
Jun 18 12:16:00 river kernel: Call Trace:
Jun 18 12:16:00 river kernel: <IRQ>  [<ffffffff810b955e>] warn_alloc_failed+0x110/0x125
Jun 18 12:16:00 river kernel: [<ffffffff8130453e>] ? process_backlog+0x171/0x171
Jun 18 12:16:00 river kernel: [<ffffffff810bbe65>] __alloc_pages_nodemask+0x6d4/0x77c
Jun 18 12:16:00 river kernel: [<ffffffff81426d9e>] ? __slab_alloc+0x3df/0x406
Jun 18 12:16:00 river kernel: [<ffffffff810e89ec>] alloc_pages_current+0xcd/0xee
Jun 18 12:16:00 river kernel: [<ffffffffa02454ab>] ? br_handle_local_finish+0x3f/0x3f [bridge]
Jun 18 12:16:00 river kernel: [<ffffffff810f0cb8>] new_slab+0xb6/0x24d
Jun 18 12:16:00 river kernel: [<ffffffff81426cbd>] __slab_alloc+0x2fe/0x406
Jun 18 12:16:00 river kernel: [<ffffffff812fa880>] ? dev_alloc_skb+0x16/0x2c
Jun 18 12:16:00 river kernel: [<ffffffff810f2e03>] __kmalloc_node_track_caller+0xd5/0x17e
Jun 18 12:16:00 river kernel: [<ffffffff813494ed>] ? tcp4_gro_receive+0x9a/0x9c
Jun 18 12:16:00 river kernel: [<ffffffff812fa880>] ? dev_alloc_skb+0x16/0x2c
Jun 18 12:16:00 river kernel: [<ffffffff812fa7a7>] __alloc_skb+0x68/0x12b
Jun 18 12:16:00 river kernel: [<ffffffff812fa880>] dev_alloc_skb+0x16/0x2c
Jun 18 12:16:00 river kernel: [<ffffffffa0170634>] nv_alloc_rx_optimized+0x47/0x203 [forcedeth]
Jun 18 12:16:00 river kernel: [<ffffffffa0172c83>] ? nv_rx_process_optimized+0x17c/0x229 [forcedeth]
Jun 18 12:16:00 river kernel: [<ffffffffa0173d7d>] nv_napi_poll+0x505/0x50a [forcedeth]
Jun 18 12:16:00 river kernel: [<ffffffff8142b7be>] ? _raw_spin_lock+0x9/0xd
Jun 18 12:16:00 river kernel: [<ffffffff81304746>] net_rx_action+0x74/0x1b2
Jun 18 12:16:00 river kernel: [<ffffffff81344ff2>] ? tcp_keepalive_timer+0x1fc/0x1fc
Jun 18 12:16:00 river kernel: [<ffffffff8104db7a>] __do_softirq+0xb8/0x198
Jun 18 12:16:00 river kernel: [<ffffffff81092067>] ? handle_edge_irq+0xd8/0xea
Jun 18 12:16:00 river kernel: [<ffffffff81252d8b>] ? __xen_evtchn_do_upcall+0x1a2/0x1df
Jun 18 12:16:00 river kernel: [<ffffffff8142d6ac>] call_softirq+0x1c/0x30
Jun 18 12:16:00 river kernel: [<ffffffff81012f17>] do_softirq+0x41/0x7e
Jun 18 12:16:00 river kernel: [<ffffffff8104de0f>] irq_exit+0x44/0x9e
Jun 18 12:16:00 river kernel: [<ffffffff812546c8>] xen_evtchn_do_upcall+0x2c/0x39
Jun 18 12:16:00 river kernel: [<ffffffff8142d6fe>] xen_do_hypervisor_callback+0x1e/0x30
Jun 18 12:16:00 river kernel: <EOI>  [<ffffffffa0014059>] ? longest_match+0x2a/0x1f4 [zlib_deflate]
Jun 18 12:16:00 river kernel: [<ffffffffa0014687>] ? deflate_slow+0xf1/0x395 [zlib_deflate]
Jun 18 12:16:00 river kernel: [<ffffffffa001520e>] ? zlib_deflate+0x1af/0x2ba [zlib_deflate]
Jun 18 12:16:00 river kernel: [<ffffffffa0022fa8>] ? z_compress_level+0x86/0xd8 [spl]
Jun 18 12:16:00 river kernel: [<ffffffffa00d6099>] ? gzip_compress+0x31/0x5c [zfs]
Jun 18 12:16:00 river kernel: [<ffffffffa0123cbe>] ? zio_compress_data+0x6b/0xaa [zfs]
Jun 18 12:16:00 river kernel: [<ffffffffa0120121>] ? zio_buf_alloc+0x232/0x545 [zfs]
Jun 18 12:16:00 river kernel: [<ffffffffa011f9c4>] ? zio_execute+0xca/0x29b [zfs]
Jun 18 12:16:00 river kernel: [<ffffffffa001f3e8>] ? taskq_destroy+0x34d/0x478 [spl]
Jun 18 12:16:00 river kernel: [<ffffffff81040393>] ? try_to_wake_up+0x243/0x243
Jun 18 12:16:00 river kernel: SLUB: Unable to allocate memory on node -1 (gfp=0x20)
Jun 18 12:16:00 river kernel: cache: kmalloc-4096, object size: 4096, buffer size: 4096, default order: 3, min order: 0
Jun 18 12:16:00 river kernel: node 0: slabs: 659, objs: 3893, free: 0
Jun 18 12:16:00 river kernel: [<ffffffff810e89ec>] alloc_pages_current+0xcd/0xee
Jun 18 12:16:00 river kernel: [<ffffffffa02454ab>] ? br_handle_local_finish+0x3f/0x3f [bridge]
Jun 18 12:16:00 river kernel: [<ffffffff810f0cb8>] new_slab+0xb6/0x24d
Jun 18 12:16:00 river kernel: [<ffffffffa0170634>] nv_alloc_rx_optimized+0x47/0x203 [forcedeth]
Jun 18 12:16:00 river kernel: [<ffffffffa0172c83>] ? nv_rx_process_optimized+0x17c/0x229 [forcedeth]
Jun 18 12:16:00 river kernel: [<ffffffff8142d6ac>] call_softirq+0x1c/0x30
Jun 18 12:16:00 river kernel: [<ffffffff81012f17>] do_softirq+0x41/0x7e
Jun 18 12:16:00 river kernel: [<ffffffff8104de0f>] irq_exit+0x44/0x9e
Jun 18 12:16:00 river kernel: 845509 pages reserved
Jun 18 12:16:00 river kernel: 27417 pages shared
Jun 18 12:16:00 river kernel: [<ffffffff8142d500>] ? segment_not_present+0x30/0x30
Jun 18 12:16:00 river kernel: [<ffffffff810bbe65>] __alloc_pages_nodemask+0x6d4/0x77c
Jun 18 12:16:00 river kernel: [<ffffffff810e89ec>] alloc_pages_current+0xcd/0xee
Jun 18 12:16:00 river kernel: [<ffffffff812fa77a>] __alloc_skb+0x3b/0x12b
Jun 18 12:16:00 river kernel: [<ffffffff8134485c>] tcp_send_ack+0x29/0xcc
Jun 18 12:16:00 river kernel: [<ffffffff8134499b>] tcp_send_delayed_ack+0x9c/0xc4
Jun 18 12:16:00 river kernel: [<ffffffff8133c026>] __tcp_ack_snd_check+0x6f/0x7d
Jun 18 12:16:00 river kernel: Node 0 DMA per-cpu:
Jun 18 12:16:00 river kernel: active_file:12333 inactive_file:12840 isolated_file:0
Jun 18 12:16:00 river kernel: unevictable:31 dirty:43 writeback:0 unstable:0
Jun 18 12:16:00 river kernel: free:8581 slab_reclaimable:5608 slab_unreclaimable:17657
Jun 18 12:16:00 river kernel: mapped:2061 shmem:1064 pagetables:2093 bounce:0
Jun 18 12:16:00 river kernel: Node 0 DMA free:9892kB min:12kB low:12kB high:16kB active_anon:0kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB isolated(anon):0kB isolated(file):0kB present:9644kB mlocked:0kB dirty:0kB writeback:0kB mapped:0kB shmem:0kB slab_reclaimable:0kB slab_unreclaimable:8kB kernel_stack:0kB pagetables:0kB unstable:0kB bounce:0kB writeback_tmp:0kB pages_scanned:0 all_unreclaimable? yes
Jun 18 12:16:00 river kernel: lowmem_reserve[]: 0 2991 8031 8031
Jun 18 12:16:00 river kernel: Node 0 DMA32 free:21732kB min:4268kB low:5332kB high:6400kB active_anon:7104kB inactive_anon:6936kB active_file:47524kB inactive_file:47480kB unevictable:28kB isolated(anon):0kB isolated(file):0kB present:3062912kB mlocked:28kB dirty:80kB writeback:0kB mapped:6832kB shmem:4208kB slab_reclaimable:15440kB slab_unreclaimable:33212kB kernel_stack:184kB pagetables:4184kB unstable:0kB bounce:0kB writeback_tmp:0kB pages_scanned:0 all_unreclaimable? no
Jun 18 12:16:00 river kernel: lowmem_reserve[]: 0 0 5040 5040
Jun 18 12:16:00 river kernel: [<ffffffffa0173d72>] nv_napi_poll+0x4fa/0x50a [forcedeth]
Jun 18 12:16:00 river kernel: [<ffffffff81304746>] net_rx_action+0x74/0x1b2
Jun 18 12:16:00 river kernel: [<ffffffff812faec7>] ? __kfree_skb+0x75/0x79
Jun 18 12:16:00 river kernel: [<ffffffff8104db7a>] __do_softirq+0xb8/0x198
Jun 18 12:16:00 river kernel: [<ffffffff81092067>] ? handle_edge_irq+0xd8/0xea
Jun 18 12:16:00 river kernel: [<ffffffff81252d8b>] ? __xen_evtchn_do_upcall+0x1a2/0x1df
Jun 18 12:16:00 river kernel: [<ffffffff8142d6fe>] xen_do_hypervisor_callback+0x1e/0x30
Jun 18 12:16:00 river kernel: <EOI>  [<ffffffffa0014059>] ? longest_match+0x2a/0x1f4 [zlib_deflate]
Jun 18 12:16:00 river kernel: [<ffffffffa0123cbe>] ? zio_compress_data+0x6b/0xaa [zfs]
Jun 18 12:16:00 river kernel: [<ffffffff81040393>] ? try_to_wake_up+0x243/0x243
Jun 18 12:16:00 river kernel: [<ffffffff810e89ec>] alloc_pages_current+0xcd/0xee
Jun 18 12:16:00 river kernel: [<ffffffff810f0cb8>] new_slab+0xb6/0x24d
Jun 18 12:16:00 river kernel: [<ffffffff81426cbd>] __slab_alloc+0x2fe/0x406
Jun 18 12:16:00 river kernel: [<ffffffff812fa77a>] ? __alloc_skb+0x3b/0x12b
Jun 18 12:16:00 river kernel: [<ffffffff8106f1a1>] ? tick_nohz_handler+0xd0/0xd0
Jun 18 12:16:00 river kernel: [<ffffffff81064b18>] ? run_posix_cpu_timers+0x27/0x656
Jun 18 12:16:00 river kernel: [<ffffffff81039cea>] ? resched_task+0x24/0x68
Jun 18 12:16:00 river kernel: [<ffffffff810f1258>] kmem_cache_alloc_node+0x5c/0x109
Jun 18 12:16:00 river kernel: [<ffffffff812fa77a>] __alloc_skb+0x3b/0x12b
Jun 18 12:16:00 river kernel: [<ffffffff8134485c>] tcp_send_ack+0x29/0xcc
Jun 18 12:16:00 river kernel: [<ffffffff813049a0>] dev_gro_receive+0x11c/0x26b
Jun 18 12:16:00 river kernel: [<ffffffff81305167>] napi_gro_receive+0xf8/0x10e
Jun 18 12:16:00 river kernel: [<ffffffffa0172c83>] nv_rx_process_optimized+0x17c/0x229 [forcedeth]
Jun 18 12:16:00 river kernel: [<ffffffffa0173d72>] nv_napi_poll+0x4fa/0x50a [forcedeth]
Jun 18 12:16:00 river kernel: [<ffffffff81304746>] net_rx_action+0x74/0x1b2
Jun 18 12:16:00 river kernel: [<ffffffff812faec7>] ? __kfree_skb+0x75/0x79
Jun 18 12:16:00 river kernel: [<ffffffff81012f17>] do_softirq+0x41/0x7e
Jun 18 12:16:00 river kernel: [<ffffffff8104de0f>] irq_exit+0x44/0x9e
Jun 18 12:16:00 river kernel: [<ffffffff812546c8>] xen_evtchn_do_upcall+0x2c/0x39
Jun 18 12:16:00 river kernel: [<ffffffff8142d6fe>] xen_do_hypervisor_callback+0x1e/0x30
Jun 18 12:16:00 river kernel: [<ffffffffa0120121>] ? zio_buf_alloc+0x232/0x545 [zfs]
Jun 18 12:16:00 river kernel: [<ffffffffa0173d72>] nv_napi_poll+0x4fa/0x50a [forcedeth]
Jun 18 12:16:00 river kernel: [<ffffffff81304746>] net_rx_action+0x74/0x1b2
Jun 18 12:16:00 river kernel: [<ffffffff812faec7>] ? __kfree_skb+0x75/0x79
Jun 18 12:16:00 river kernel: [<ffffffff8104db7a>] __do_softirq+0xb8/0x198
Jun 18 12:16:00 river kernel: [<ffffffff81092067>] ? handle_edge_irq+0xd8/0xea
Jun 18 12:16:00 river kernel: [<ffffffff81252d8b>] ? __xen_evtchn_do_upcall+0x1a2/0x1df
Jun 18 12:16:00 river kernel: [<ffffffff8142d6fe>] xen_do_hypervisor_callback+0x1e/0x30
Jun 18 12:16:00 river kernel: <EOI>  [<ffffffffa0014059>] ? longest_match+0x2a/0x1f4 [zlib_deflate]
Jun 18 12:16:00 river kernel: [<ffffffffa0014687>] ? deflate_slow+0xf1/0x395 [zlib_deflate]
Jun 18 12:16:00 river kernel: [<ffffffffa001520e>] ? zlib_deflate+0x1af/0x2ba [zlib_deflate]
Jun 18 12:16:00 river kernel: Node 0 DMA free:9892kB min:12kB low:12kB high:16kB active_anon:0kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB isolated(anon):0kB isolated(file):0kB present:9644kB mlocked:0kB dirty:0kB writeback:0kB mapped:0kB shmem:0kB slab_reclaimable:0kB slab_unreclaimable:8kB kernel_stack:0kB pagetables:0kB unstable:0kB bounce:0kB writeback_tmp:0kB pages_scanned:0 all_unreclaimable? yes
Jun 18 12:16:00 river kernel: Node 0 Normal: 339*4kB 0*8kB 4*16kB 1*32kB 6*64kB 1*128kB 1*256kB 1*512kB 0*1024kB 0*2048kB 0*4096kB = 2732kB
Jun 18 12:16:00 river kernel: 26906 total pagecache pages
Jun 18 12:16:00 river kernel: 662 pages in swap cache
Jun 18 12:16:00 river kernel: Swap cache stats: add 2414, delete 1752, find 2/2
Jun 18 12:16:00 river kernel: SLUB: Unable to allocate memory on node -1 (gfp=0x20)
Jun 18 12:16:00 river kernel: cache: kmalloc-256, object size: 256, buffer size: 256, default order: 0, min order: 0
Jun 18 12:16:00 river kernel: [<ffffffffa02454ab>] ? br_handle_local_finish+0x3f/0x3f [bridge]
Jun 18 12:16:00 river kernel: lowmem_reserve[]: 0 2991 8031 8031
Jun 18 12:16:00 river kernel: Swap cache stats: add 2414, delete 1752, find 2/2
Jun 18 12:16:00 river kernel: Free swap  = 2087492kB

**Comment by behlendorf** [comment]
Closing as stale.
