### ISSUE TITLE
Deleting Files Doesn't Free Space, unless I unmount the filesystem

### ISSUE THREAD

**Issue by fabiokorbes** [zfsonlinux/zfs#1548]
We are experiencing the same problem reported in issue https://github.com/zfsonlinux/zfs/issues/1188 . When we delete a file, its disk space is not free'd.

We are testing the use of a ZFS volume to store logs. We delete old logs in the same pace we write new ones. So, the disk usage should be constant in a short term. But it isn't. it always increase (as reported by df or zfs list commands). Although, the disk usage reported by du command remains constant.

It takes a full month to reach 100% of the disk. So I don't think it is an asynchronous-delete or recently-freed issues. I have already stopped the writing process for several hours, so it is not a load issue neither. And we aren't doing any snapshots.

It only releases the space of the deleted files when I unmount the filesystem. And it takes about 10 minutes to unmount.

Is this a bug? or is there something I could do to make the deletions work?

Besides, is there a command to manually release the space without I need to unmount the filesystem?

Here, some info of my system:

```
# zdb 
gfs:
    version: 5000
    name: 'gfs'
    state: 0
    txg: 4
    pool_guid: 12548299384193180756
    hostid: 3943305418
    hostname: 'margari.tpn.terra.com'
    vdev_children: 1
    vdev_tree:
        type: 'root'
        id: 0
        guid: 12548299384193180756
        create_txg: 4
        children[0]:
            type: 'disk'
            id: 0
            guid: 776557494125630754
            path: '/dev/sdb1'
            whole_disk: 0
            metaslab_array: 33
            metaslab_shift: 32
            ashift: 9
            asize: 730802946048
            is_log: 0
            create_txg: 4
    features_for_read:


# zpool status   
  pool: gfs
 state: ONLINE
  scan: scrub repaired 0 in 4h6m with 0 errors on Sat Jun  8 00:42:59 2013
config:

        NAME        STATE     READ WRITE CKSUM
        gfs         ONLINE       0     0     0
          sdb1      ONLINE       0     0     0

errors: No known data errors


# zfs list -t all
NAME   USED  AVAIL  REFER  MOUNTPOINT
gfs    364G   305G   364G  /gfs


# zfs get all
NAME  PROPERTY              VALUE                  SOURCE
gfs   type                  filesystem             -
gfs   creation              Tue Apr  9 13:13 2013  -
gfs   used                  364G                   -
gfs   available             305G                   -
gfs   referenced            364G                   -
gfs   compressratio         5.30x                  -
gfs   mounted               yes                    -
gfs   quota                 none                   default
gfs   reservation           none                   default
gfs   recordsize            64K                    local
gfs   mountpoint            /gfs                   default
gfs   sharenfs              off                    default
gfs   checksum              off                    local
gfs   compression           gzip-9                 local
gfs   atime                 off                    local
gfs   devices               on                     default
gfs   exec                  on                     default
gfs   setuid                on                     default
gfs   readonly              off                    default
gfs   zoned                 off                    default
gfs   snapdir               hidden                 default
gfs   aclinherit            restricted             default
gfs   canmount              on                     default
gfs   xattr                 on                     default
gfs   copies                1                      default
gfs   version               5                      -
gfs   utf8only              off                    -
gfs   normalization         none                   -
gfs   casesensitivity       sensitive              -
gfs   vscan                 off                    default
gfs   nbmand                off                    default
gfs   sharesmb              off                    default
gfs   refquota              none                   default
gfs   refreservation        none                   default
gfs   primarycache          all                    default
gfs   secondarycache        all                    default
gfs   usedbysnapshots       0                      -
gfs   usedbydataset         364G                   -
gfs   usedbychildren        88.2M                  -
gfs   usedbyrefreservation  0                      -
gfs   logbias               latency                default
gfs   dedup                 off                    default
gfs   mlslabel              none                   default
gfs   sync                  standard               default
gfs   refcompressratio      5.30x                  -
gfs   written               364G                   -
gfs   snapdev               hidden                 default
```

**Comment by Falken42** [comment]
Just to provide another data point, I think I've run into this issue as well.

I have a dataset on my ZFS pool used for Time Machine backups with a quota set on it so the backups don't fill the entire pool.  This has worked fine for about six months until yesterday when I was told I needed to recreate a backup of one of my machines: https://discussions.apple.com/article/HT4076

There wasn't enough space to recreate the backup though, so I had to go through and nuke some older backups from a different machine to free up space.  This is when I found that ZFS wasn't reclaiming the space properly:

> cheddar ~ # zfs list
> NAME               USED  AVAIL  REFER  MOUNTPOINT
> tank              1.95T   747G   873G  /
> tank/Data         84.7M   747G  84.7M  /home/Data
> tank/Media         192G   747G   192G  /home/Media
> tank/TimeMachine   928G  96.3G   928G  /home/TimeMachine

But a du -k showed:

> cheddar ~ # du -k /home/TimeMachine/
> 628050893       /home/TimeMachine/Falken’s iMac.sparsebundle/bands
> 628050941       /home/TimeMachine/Falken’s iMac.sparsebundle
> 682748  /home/TimeMachine/raichu.sparsebundle/bands
> 682779  /home/TimeMachine/raichu.sparsebundle
> 628733737       /home/TimeMachine/

I first tried stopping all related processes (netatalk, samba) to see if there was an open handle leftover, but that didn't seem to have any effect.  After finding this bug and attempting a unmount on the dataset, the free space was recovered:

> cheddar ~ # zfs unmount /home/TimeMachine/
> cheddar ~ # zfs list
> NAME               USED  AVAIL  REFER  MOUNTPOINT
> tank              1.63T  1.05T   873G  /
> tank/Data         84.7M  1.05T  84.7M  /home/Data
> tank/Media         192G  1.05T   192G  /home/Media
> tank/TimeMachine   600G   424G   600G  /home/TimeMachine
> cheddar ~ # zfs mount tank/TimeMachine
> cheddar ~ # zfs list
> NAME               USED  AVAIL  REFER  MOUNTPOINT
> tank              1.63T  1.05T   873G  /
> tank/Data         84.7M  1.05T  84.7M  /home/Data
> tank/Media         192G  1.05T   192G  /home/Media
> tank/TimeMachine   600G   424G   600G  /home/TimeMachine

It also took a good 15 minutes or so for the unmount to complete, and CPU usage was 100% the entire time during the unmount process.

FWIW, I'm running ZFS 0.6.3 on Gentoo, with ZFS on root:

> [    2.559789] SPL: Loaded module v0.6.3-r0-gentoo
> [    2.603726] ZFS: Loaded module v0.6.3-r0-gentoo, ZFS pool version 5000, ZFS filesystem version 5

If there's any other information I can provide to help track this down further, please let me know!

**Comment by deajan** [comment]
Is your pool configured with xattr=sa ?

**Comment by kpande** [comment]
Can you update to zfs-9999 on that machine? There's a number of fixes currently in HEAD that aren't in 0.6.3-r0.

**Comment by Falken42** [comment]
@deajan: Looks like I used the default of xattr=on:

> cheddar ~ # zfs get xattr
> NAME              PROPERTY  VALUE  SOURCE
> tank              xattr     on     default
> tank/Data         xattr     on     default
> tank/Media        xattr     on     default
> tank/TimeMachine  xattr     on     default

I assume xattr is configurable per dataset?  I have no problem with nuking tank/TimeMachine and recreating it with xattr=sa.

@kpande: I was planning on upgrading to zfs-0.6.4 sometime soon, but haven't had the time yet.  Would you still recommend HEAD over 0.6.4?

**Comment by kpande** [comment]
@Falken42 /I/ would. 0.6.4 was kinda-sorta rushed even though @behlendorf tried as hard as he could to get all the regressions hammered out. I requested to him that we get a point release ASAP with various issues covered.. so in summary, look over the commit list since the tag to see if things look good to you. Use it for a while.. integrate fixes if you need them.

**Comment by deajan** [comment]
@Falken42 I had that issue with some testing builds between 0.6.2 and 0.6.3 when files were created over smb and xattr was set to on, and yes, xattr=sa is set per dataset.
Setting xattr=sa isn't retroactive, you have indeed to nuke the dataset and recreate it with that option, which should resolve your issue (at least it worked for me).

**Comment by behlendorf** [comment]
@Falken42 I've tagged the point release @kpande mentioned this morning.  My suggestion would be to update to 0.6.4.1 once it's available for your distribution.

**Comment by nareshv** [comment]
I have experienced the same problem today with one of the volumes (`tank/jobs`). Here are some details

```
[    2.687411] SPL: Loaded module v0.6.4-1
[    2.768120] ZFS: Loaded module v0.6.4-1, ZFS pool version 5000, ZFS filesystem version 5
[    5.199000] SPL: using hostid 0x00000000
```

1. Volume is 100% full and i have tried un-mounting the volume to re-claim the free space. But no luck.
2. `xattr=on` is the setting when the volume was created with 0.6.3 and its still the the same now.
3. Did `zpool export tank` and `zpool import tank` with no luck 

I have thought of creating a new volume with `xattr=sa` and use the old-mountpoint (/jobs). During that process i have ran `zfs set mountpoint=/old-jobs tank/jobs`. Surprisingly, the disk space was getting freed when i tried to change the mount-point of the volume.

**Comment by efocht** [comment]
We just saw the issue with an NFS exported ZFS volume on 0.6.4.1

Dropping the caches with
echo 3 > /proc/sys/vm/drop_caches
helped. It's the easiest cure. Thanks @behlendorf for the hint!

**Comment by tobydarling** [comment]
We're also experiencing this with 0.6.4.2 (upgraded from 0.6.4.1) and an NFSv3 exported volume using /etc/exports not sharenfs. This is on Scientific Linux 6.6 - 2.6.32-504.23.4.el6.x86_64. 
```
SPL: Loaded module v0.6.4.1-1
ZFS: Loaded module v0.6.4.2-1, ZFS pool version 5000, ZFS filesystem version 5
SPL: using hostid 0x00000000
```
(no changes to SPL between 0.6.4.1 and 0.6.4.2 so I'm guessing it didn't rebuild? https://github.com/zfsonlinux/spl/compare/spl-0.6.4-release...spl-0.6.4.2). 

I'm still trying to nail a reproducible test case. Currently, I still have 6765 ZAP entries in the delete queue  after deleting a directory structure of 76k files about 8 hours ago; directory was copied in yesterday and a snapshot taken during the night.

**Comment by darky83** [comment]
Same issue, this is on a blank new system (VM):

/data01 is my raidz test drive:
```bash
dd if=/dev/zero of=/data01/zerofile1 bs=1M count=1024
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB) copied, 4.45455 s, 241 MB/s

ls -lh /data01/
total 1.0G
-rw-r--r--. 1 root root 1.0G Jul 28 22:42 zerofile1

df -h | grep data01
data01                    15G  1.0G   14G   7% /data01
rm -rf zerofile*
ls -lh /data01/
total 0
df -h | grep data01
data01                    15G  1.0G   14G   7% /data01
```

But if you unmount the drive and mount the drive again the disk space is free again:
```bash
umount /data01/
zfs mount data01
df -h | grep data
data01                    15G     0   15G   0% /data01
```
unmounting is the only way of getting space back.


Centos 7.1 on VMware 
```bash
rpm -qa | grep -i zfs
zfs-0.6.4.2-1.el7.centos.x86_64
zfs-release-1-2.el7.centos.noarch
zfs-dkms-0.6.4.2-1.el7.centos.noarch
libzfs2-0.6.4.2-1.el7.centos.x86_64

# zpool status
  pool: data01
 state: ONLINE
  scan: none requested
config:

	NAME        STATE     READ WRITE CKSUM
	data01      ONLINE       0     0     0
	  raidz1-0  ONLINE       0     0     0
	    sdb     ONLINE       0     0     0
	    sdc     ONLINE       0     0     0
	    sdd     ONLINE       0     0     0
	  sde       ONLINE       0     0     0

errors: No known data errors
```

**Comment by discostur** [comment]
Hello,

i'm experiencing the same problem on Centos 7.1 with 

<pre>
dmesg | egrep 'SPL:|ZFS:'

[    3.768400] SPL: Loaded module v0.6.4.2-1
[    3.873355] ZFS: Loaded module v0.6.4.2-1, ZFS pool version 5000, ZFS filesystem version 5
</pre>

ZFS shows me that there are 28GB used by the dataset, but actually there are only about 4G used:

<pre>
zfs list
NAME                                                    USED  AVAIL  REFER  MOUNTPOINT
dpool01                                                60,5G   853G  1,07G  /dpool01
...
dpool01/dataset1  27,4G  1,23G  28,1G  /var/lib/lxc/dataset1/
</pre>

compared to:

<pre>
du -h --max-depth=1
...
3,4G	.
</pre>

Dataset looks like this:

<pre>
used                  27,4G                                               -
dpool01/dataset1  available             1,23G                                               -
dpool01/dataset1  referenced            28,1G                                               -
dpool01/dataset1  compressratio         1.68x                                               -
dpool01/dataset1  compression           lz4                                                 inherited from dpool01
dpool01/dataset1  usedbysnapshots       70,4M                                               -
dpool01/dataset1  usedbydataset         27,3G                                               -
dpool01/dataset1  xattr                 off                                                 inherited from dpool01
</pre>

Some more outputs:

<pre>
db -d dpool01/dataset1
Dataset dpool01/dataset1 [ZPL], ID 477, cr_txg 720, 28.1G, 1399979 objects
</pre>


zdb -dddd gives me a never ending list of entries in the delete queue (shortened):

<pre>
    Object  lvl   iblk   dblk  dsize  lsize   %full  type
         3    3    16K    16K  27.0M  32.0M  100.00  ZFS delete queue
	dnode flags: USED_BYTES USERUSED_ACCOUNTED 
	dnode maxblkid: 2049
	Fat ZAP stats:
		Pointer table:
			2048 elements
			zt_blk: 1025
			zt_numblks: 1
			zt_shift: 11
			zt_blks_copied: 0
			zt_nextblk: 0
		ZAP entries: 314118
		Leaf blocks: 2048
		Total blocks: 2050
		zap_block_type: 0x8000000000000001
		zap_magic: 0x2f52ab2ab
		zap_salt: 0x11346a6c7
		Leafs with 2^n pointers:
			  0:   2048 ****************************************
		Blocks with n*5 entries:
			  9:   2048 ****************************************
		Blocks n/10 full:
			  6:    161 *****
			  7:   1557 ****************************************
			  8:    326 *********
			  9:      4 *
		Entries with n chunks:
			  3: 314118 ****************************************
		Buckets with n entries:
			  0: 768758 ****************************************
			  1: 247567 *************
			  2:  30269 **
			  3:   1915 *
			  4:     67 *

		118cce = 1150158 
		120468 = 1180776 
		20da73 = 2153075 
		206138 = 2122040 
		119a54 = 1153620 
		4ec7f = 322687 
		51d9f = 335263 
...
</pre>

The strange thing is that i have 4 of these Datasets with similary content and i'm only seeing the behaviour one of the Datasets. Unmounting / Remounting the Dataset clears the free Space, but it takes a long time for me ... 20-30 minutes.

Greets
Kilian

**Comment by erocm123** [comment]
Well, at least I know I am not alone. I am running ZFS on CentOS 7.1 and it is not freeing up space properly until I unmount the dataset.

Here is an example:

> [root@CentOS7 Replication]# zfs get usedbysnapshots
NAME                                             PROPERTY         VALUE     SOURCE
...
volume1/Data/Archive_TV                          usedbysnapshots  0         -


> [root@CentOS7 Replication]# zfs list
NAME                       USED  AVAIL  REFER  MOUNTPOINT
...
volume1/Data/Archive_TV   57.5G   110G  57.5G  /volume1/Data/Archive_TV

> [root@CentOS7 Archive_TV]# du -h --max-depth=1
512     .


After I unmount/remount it:

> [root@CentOS7 Archive_TV]# zfs list
NAME                       USED  AVAIL  REFER  MOUNTPOINT
volume1/Data/Archive_TV     19K   197G    19K  /volume1/Data/Archive_TV


> [root@CentOS7 Archive_TV]# dmesg | egrep 'SPL:|ZFS:'
[    0.981090] SPL: Loaded module v0.6.5.3-1
[    0.992885] ZFS: Loaded module v0.6.5.3-1, ZFS pool version 5000, ZFS filesystem version 5
[    4.442455] SPL: using hostid 0x00000000

As you can see, I had about 57GB missing until I unmounted. Any help would be appreciated.

**Comment by dylhager** [comment]
Getting this exact same situation. Any logs I can provide I would feel free. One dataset works fine the other does not. 

Deleted like 5TB of data and it would not free any space until i rebooted. I was unable to unmount due to the sheet amount of processes using my pool. After the reboot the storage had free'd up. Nothing had the files open that I had removed.

**Comment by kernelOfTruth** [comment]
@erocm123  @dylhager doing a manual ``` sync ``` in a terminal at least 2 or 3 consecutive times (with a few seconds in between) doesn't have any effect ?

e.g. when I'm deleting snapshot or "large" amounts of files (several gigabytes) it takes several seconds for ZFS to release

**Comment by dylhager** [comment]
I ran sync about 5 times after the delete and still show the same usage after file delete. I also have selinux disabled as well.

**Comment by erocm123** [comment]
I did not run sync, but I didn't notice the fact that the free space wasn't freeing up until quite a while later. In my example above, there were about 10 files of about 57 GB of data. I had deleted them a few days before. A few days later things seemed fishy with how much free space I had so I started investigating.

**Comment by tobydarling** [comment]
Hi

ZFS version numbers would be useful here (dmesg | egrep "ZFS|SPL"). I'm not
certain yet, but with 0.6.5.2 I'm seeing far less of this issue

Cheers
Toby

**Comment by dylhager** [comment]
# dmesg | egrep "ZFS|SPL"
[    5.356157] SPL: Loaded module v0.6.5.3-1
[    5.416386] ZFS: Loaded module v0.6.5.3-1, ZFS pool version 5000, ZFS filesystem version 5
[    7.110370] SPL: using hostid 0x00000000

Kernel: version 3.10.0-229.14.1.el7.x86_64x86_64
OS: CentOS Linux release 7.1.1503 (Core)

**Comment by erocm123** [comment]
[root@CentOS7 Archive_TV]# dmesg | egrep 'SPL:|ZFS:'
[ 0.981090] SPL: Loaded module v0.6.5.3-1
[ 0.992885] ZFS: Loaded module v0.6.5.3-1, ZFS pool version 5000, ZFS filesystem version 5
[ 4.442455] SPL: using hostid 0x00000000

[root@CentOS7 ~]# uname -a
Linux CentOS7 3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Sep 15 15:05:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[root@CentOS7 ~]# cat /etc/redhat-release
CentOS Linux release 7.1.1503 (Core)

Maybe I am just noticing this because my disk space has been running low, but I feel like this popped up with a recent build. I could be wrong though.

**Comment by discostur** [comment]
@kernelOfTruth

that's true, xattr=off was off in my pool, but first it was set to xattr=on, then i noticed the strange behaviour of my pool and i disabled it on the fly (without reboot). But that didn't change anything ...

Now i'm running with xattr=sa, zfs 0.6.5.3-2 and i have done a reboot after setting xattr=sa. I'll keep an eye on it the next weeks ...

**Comment by ringingliberty** [comment]
@discostur Remember that each file must be created with xattr=sa set, in order for it to work. If you have existing files, you'll need to copy them (e.g. to a new dataset).

**Comment by Nukien** [comment]
Ugh - is there any way to do that in-place ?  I have 500G free on a 10T filesystem ...

**Comment by ringingliberty** [comment]
@Nukien cp each filename to filename.new and then mv it back. This still won't guarantee you won't have any downtime. The files might be in use, after all.

**Comment by Nukien** [comment]
Doh.  Must be early, should have thought of that.  Scripting time - I would like to keep the filetime for each one ...  Let's see, "find /zfs1/sys1 -type f -exec ...

**Comment by kernelOfTruth** [comment]
@Nukien From what I read - the only guarantee to have no issues in the future is to create the filesystem anew with xattr=sa - but that surely is no option in your case

@ringingliberty 's solution appears to be the optimal one - not sure if it's enough concerning the filesystem data

CC: @dweeezil

**Comment by MasterCATZ** [comment]
Started getting this problem after last upgrade

SPL: Loaded module v0.6.5.3-1~trusty
ZFS: Loaded module v0.6.5.3-1~trusty, ZFS pool version 5000, ZFS filesystem version 5

NAME       PROPERTY  VALUE  SOURCE
ZFSRaidz2  xattr     on     default
I am a little scared to try changing this .. as I use an FreeBSD recovery disk for when Ubuntu does break on me  

dd if=/dev/null of=syslog.tar.gz
rm syslog.tar.gz

I have  0'd out a few hundred gig of files and removed them 
free space is still not freeing up , unmounted / remounted etc 

NAME        USED  AVAIL  REFER  MOUNTPOINT
ZFSRaidz2  10.5T      0  10.5T  /ZFSRaidz2
 ( how ever the USED space here changed to lower number but AVAIL never increased )

NAME        SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
ZFSRaidz2  16.2T  15.8T   464G         -     3%    97%  1.00x  ONLINE  -

running out of files to try removing 
only thing not done is a scrub as I don't have the needed 19 hrs untill next week

**Comment by truatpasteurdotfr** [comment]
same here: upgraded from zfs-0.6.2 to 0.6.5.3 -> 100% full
tried zpool upgrade -> no change
zfs destroy a few fs to make room && zfs umount -a && zfs mount -a: unchanged situation.
zfs set xattr=sa && zfs destroy && zfs umount && zfs mount : no changes
zpool scrub in progress

```
SPL: Loaded module v0.6.5.3-1
ZFS: Loaded module v0.6.5.3-1, ZFS pool version 5000, ZFS filesystem version 5
SPL: using hostid 0x00000000

df:
...
mpool/private           4125696   4125696          0 100% /mpool/private
mpool/pub/esxi          2052736   2052736          0 100% /mpool/pub/esxi
mpool/pub/livecd         429952    429952          0 100% /mpool/pub/livecd
mpool/pub/raspbian      1016192   1016192          0 100% /mpool/pub/raspbian
mpool/pub/videos       90928384  90928384          0 100% /mpool/pub/videos

```

**Comment by RichardSharpe** [comment]
Hmm,

Running 0.6.5.3-1 but space does not seem to be reclaimed after a delete.

I am running with xattr=on NOT xattr=sa.

**Comment by yesbox** [comment]
I just found this issue on 0.6.5.4-1. I stored all files in the root filesystem instead of in datasets, but has since created datasets and been moving the files to them. Then I noticed the reported disk usage of the root filesystem only increasing both in "zfs list" and "df" when moving files from it. I don't have any other information other than that I do rely on SELinux and xattr is set to the default on. I could reboot the system and that freed up space.

**Comment by odoucet** [comment]
Same bug here with SPL/ZFS v0.6.4.2-1 + kernel 3.10.76 ;
data is stored on a child (not directly on root). xattr=on
zfs umount did the trick but took several minutes.

**Comment by jcphill** [comment]
Looks like the same bug with zfs-0.6.5.4 and kernel 3.10.0-327.
Deleting files does not reclaim space even in child datasets.
Tried "echo 3 > /proc/sys/vm/drop_caches" which ran for several minutes but no change.
Export and import does reclaim the space.
Setting xattr=sa fixes the issue for newly created files.
Setting xattr=off has no effect, even on newly created files.

**Comment by kpande** [comment]
disabling selinux doesn't help me at all.

**Comment by DeHackEd** [comment]
I ran into this, but I was focusing on the inode counts rather than space usage as it wasn't a lot of space.

Before unmounting, 151616 inodes were in use. Unmounting took a moment, and after remounting it was 6. Yes, I `rm -rf`'d everything.

**Comment by DarwinSurvivor** [comment]
We are seeing the same problem on a large (3-digit TB) fully updated CentOS 7 machine.
kernel version: 3.10.0-327.28.3.el7
zfs (and zfs-dkms) version: 0.6.5.7-1.el6

setting drop_caches to 0 caused the machine to stop responding over NFS for 15-20 minutes. The mounts block locally except on one mount at a time (is suspect it was blocking on whichever mount it was clearing files for at the time). After the interruption, about 5 TB of space was cleared, but running it again during a cron job is not having the same effect (it seems to have only worked once). The machine is in near-constant use, so we haven't had a chance to try unmounting, exporting or rebooting since then.

**Comment by DarwinSurvivor** [comment]
Using a temporary filesystem I was able to clear some deleted files by un-mounting and re-mounting the specific filesystem. Obviously we would like to avoid this, but the work-around does work in a pinch.

**Comment by DarwinSurvivor** [comment]
Slight correction to my earlier comment, we are setting drop_caches to 3 (0 is what it reads before the value is set).

**Comment by DeHackEd** [comment]
`drop_caches` is not a stored value, it's a signal to perform an action. Your shell will block until the operation completes and it will always read as 0.

**Comment by DarwinSurvivor** [comment]
I'm aware that it performs the function during the "write" (and thus blocks). When I do the write, it does block for a few seconds to a few minutes (depending on the last time it was done), but cat is definitely showing it as having a value of 3. It's probably just be reporting the last value that passed to it.

**Comment by kernelOfTruth** [comment]
Anyone using quotas and has this issue ?

in that case https://github.com/zfsonlinux/zfs/commit/db707ad094431a8869123cb2389a4b768d5583a0 OpenZFS 6940 - Cannot unlink directories when over quota 

might help

**Comment by leeuwenrjj** [comment]
Also seeing this issue.
CentOS 7.2, zfs-0.6.5.7-1.el7.
Default xattr, running with compression on.

umount/mount will solve it.
We saw a high txg_sync and z_fr_iss when doing the umount/mount if that helps...

Changing to xattr=sa seem to work

**Comment by mrjester888** [comment]
Just a "Me Too" comment.  I was moving 1TB of data between datastores, using a SSD datastore/pool in between for speed. (tank/DS1 -> SSD -> tank/DS2)   Had to umount/mount the SSD datastore between each chunk of data for the SSD datastore to reflect the available space.

**Comment by kernelOfTruth** [comment]
That's a really hard to pinpoint target !

It used to work for me,

now I just realized that upon wiping out a directory of 110 GB and several snapshots, that the space isn't freed:

branch used is https://github.com/kernelOfTruth/zfs/commits/zfs_kOT_04.12.2016_2

**no xattr is used,**

**no SELinux is used**

Kernel is 4.9.0 rt based

**Comment by fermulator** [comment]
a "me too" comment;

My situation was:
- had a simple 1TB mirror pool with a handful of datasets
- realized I wanted more granular control over a set of sub-dirs in one of the datasets
- so went to start creating more child datasets
   - (roughly it was : move dir FOO into FOO_TMP, create dataset, clone ACLs, mv FOO_TMP/* FOO/)
- one of the sub-dirs was huge (200GB+)
- quickly observed ALLOC of the dataset creeping and FREE dropping!! eventually got here

```$ sudo zfs list -r zfsmain
NAME                                           USED  AVAIL  REFER  MOUNTPOINT
zfsmain                                        829G      0    96K  /zfsmain
zfsmain/SNIPD                              212G      0   212G  /zfsmain/SNIPD
zfsmain/storage                                352G      0   315G  /zfsmain/storage
zfsmain/storage/SNIPA                     454M      0   454M  /zfsmain/storage/SNIPA
zfsmain/storage/SNIPA@2018-06-05_LOCKED      0      -   454M  -
zfsmain/storage/SNIPT                   1.02G      0  1.02G  /zfsmain/storage/SNIPT
zfsmain/storage/SNIPF                        35.9G      0  35.9G  /zfsmain/storage/SNIPF
zfsmain/SNIPU                                265G      0   265G  /zfsmain/SNIPU
```

The USED adds up roughly. In this state i was in the middle of something like:
`mv /zfsmain/storage/SNIPF_TMP/* /zfsmain/storage/SNIPF/`

Despite all the MOVE operations (~36GB into SNIPF), there was still a WHACK of usage in SNIPF_TMP.
```$ du -hsc SNIPF_TMP | grep total
246G    total
```

My "storage" dir has loads of important live/active services in sub-dirs ... it's impossible for me unmount it right now.
```$ sudo zfs get all zfsmain/storage | grep -i mount
zfsmain/storage  mounted               yes                    -
zfsmain/storage  mountpoint            /zfsmain/storage       default
zfsmain/storage  canmount              on                     default
```

I have verified that the move operation IS deleting files off the filesystem by diffing the "_TMP" dir to the DEST directory too.

Tried echo-ing non-zero value into `/proc/sys/vm/drop_caches`, blocked for a few moments, insignificant zpool iostat activity ... -- no affect on AVAIL storage.

**Comment by kpande** [comment]
please upgrade to the 0.7 series if you still experience this issue. closing as stale, my reproducible case for this no longer causes an issue.
