### ISSUE TITLE
/.zfs/snapshot can be abused to manipulate snapshots without history logging

### ISSUE THREAD

**Issue by DeHackEd** [zfsonlinux/zfs#1571]
So I ran into this while fooling around and it's potentially a concern.

<pre>
# zpool create testpool /dev/sdb
# cd /testpool/.zfs/snapshot
# mkdir snapshot1
# mkdir snapshot2
# mkdir snapshot3
# rmdir snapshot2
# zfs list -o name
NAME
testpool
testpool@snapshot1
testpool@snapshot3
# zpool history
</pre>

Expected output: history of snapshot creation and deletion
Actual output: no snapshot activity is displayed

While snapshot creation/destruction is logged and display with `zpool hsitory -i` it does lack details. Whether this is a big problem is open for debate.

(All output is hand crafted to prove a point, not necessarily my having actually made a pool and copy/pasted my shell session)

**Comment by DeHackEd** [comment]
I noticed 0500e835af3ea1f3abe27a572f7b2328b4cde386 now made this behaviour off by default. Think that's good enough to satisfy this bug?

**Comment by behlendorf** [comment]
It would be good to still log it.   Let's leave it open so we remember to implement this. This should be a bite sized patch if someone wants to get in to the code.

**Comment by behlendorf** [comment]
This was resolved.
