### ISSUE TITLE
zdb -R crash when decompressing 

### ISSUE THREAD

**Issue by mikeldy** [zfsonlinux/zfs#1582]
zdb -R tries every type of decompression with every possible resulting logical block size. 

Unfortunately zle decompression has a problem/feature.... any input string is valid zle AND the function zle_decompress can write outside the destination buffer. As I discovered with valgrind:

==15104== Invalid write of size 1
==15104==    at 0x59B518A: zle_decompress (zle.c:81)
==15104==    by 0x405EA8: main (zdb.c:2883)
==15104==  Address 0x8fd0360 is 0 bytes after a block of size 131,072 alloc'd
==15104==    at 0x4C28BED: malloc (vg_replace_malloc.c:263)
==15104==    by 0x405AEA: main (umem.h:87)

In principle zle_decompress can write up to one run sequence after the end of the destination buffer as the following code does not check d_end within this while loop:

```
78:                int len = 1 + *src++;
79:                if (len <= n) {
80:                       while (len-- != 0)
81:                                *dst++ = *src++;
```

I fixed this for myself in zdb.c by allocating lbuf & lbuf2 with size SPA_MAXBLOCKSIZE+512. But its so ugly I wouldn't dream of submitting as a patch.

There are wider concerns.... I imagine it would be possible to fabricate some zle blocks on a pendrive (or other removable media) that could cause a buffer overrun in kernel and maybe provoke corruption or panics etc. when accessed.

As far as I can tell zle is the only decompression method that can overrun the output buffer. I suspect it would be better/safer to alter the zle_decompress code.

**Comment by behlendorf** [comment]
This has been improved in the latest version.
