### ISSUE TITLE
swapping blocked by memory allocations

### ISSUE THREAD

**Issue by prometheanfire** [zfsonlinux/zfs#1602]
Here's the sysrq-w

http://dev.gentoo.org/~prometheanfire/bugs/github/zfsonlinux/2013-07-20_01.cap

I've rebooted this system, but I might be able to reproduce.

**Comment by ryao** [comment]
@behlendorf This should have been fixed in 0.6.4.

**Comment by behlendorf** [comment]
Yup, this was also resolved.  Closing.
