### ISSUE TITLE
slog devices go offline upon reboot

### ISSUE THREAD

**Issue by likewhoa** [zfsonlinux/zfs#1630]
I have a problem which just started happening after adding a new slog mirror since my previous slog device failed. Now upon a reboot my slog mirror shows as being unavailable and can be fixed with <code>zpool online pool device</code>. I am not sure what is the cause of this but each reboot they seem to go offline but the cache devices are just fine and are on the same drives as the slog devices so it's not an issue with the drives.

**Comment by rlaager** [comment]
Use /dev/disk/by-id names?
