### ISSUE TITLE
txg_sync hangs zpool or zfs commands *without* maxing out CPU

### ISSUE THREAD

**Issue by localoptimum** [zfsonlinux/zfs#1640]
This issue looks similar to the following closed / investigated issues, with one difference.  My CPUs are idle.  I can reproduce this by simply unmounting my pool, disconnecting the disks and powering them down, then trying to remount it all again, hence I open a new issue as this might be a different angle or a different problem entirely.

The existing similar issues are:
https://github.com/zfsonlinux/zfs/issues/1070
https://github.com/zfsonlinux/zfs/issues/1101
https://github.com/zfsonlinux/zfs/issues/1600

I am using latest stable ubuntu-zfs release from the ppa, on August 9th 2013.  I am using ubuntu 13.04.

My trace is:

Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862355] INFO: task txg_sync:4738 blocked for more than 120 seconds.
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862358] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862359] txg_sync        D ffff88016fa53f40     0  4738      2 0x00000000
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862362]  ffff88007af2bb98 0000000000000046 ffff880034511740 ffff88007af2bfd8
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862365]  ffff88007af2bfd8 ffff88007af2bfd8 ffff880076bd1740 ffff880034511740
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862368]  ffff880034511740 ffff88016fa547f8 ffff880059d294b0 0000000000000001
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862370] Call Trace:
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862377]  [<ffffffff816cba89>] schedule+0x29/0x70
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862379]  [<ffffffff816cbb5f>] io_schedule+0x8f/0xd0
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862397]  [<ffffffffa01ac458>] cv_wait_common+0xa8/0x1b0 [spl]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862400]  [<ffffffff8107dd30>] ? finish_wait+0x80/0x80
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862407]  [<ffffffffa01ac578>] __cv_wait_io+0x18/0x20 [spl]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862431]  [<ffffffffa02d44d3>] zio_wait+0x103/0x1a0 [zfs]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862448]  [<ffffffffa0268958>] dsl_pool_sync+0x348/0x5d0 [zfs]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862466]  [<ffffffffa027f8c8>] spa_sync+0x3e8/0xa60 [zfs]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862470]  [<ffffffff810ac008>] ? ktime_get_ts+0x48/0xe0
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862488]  [<ffffffffa028efa3>] txg_sync_thread+0x323/0x590 [zfs]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862506]  [<ffffffffa028ec80>] ? txg_init+0x250/0x250 [zfs]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862512]  [<ffffffffa01a4c08>] thread_generic_wrapper+0x78/0x90 [spl]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862518]  [<ffffffffa01a4b90>] ? __thread_create+0x340/0x340 [spl]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862519]  [<ffffffff8107d420>] kthread+0xc0/0xd0
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862521]  [<ffffffff8107d360>] ? kthread_create_on_node+0x120/0x120
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862524]  [<ffffffff816d516c>] ret_from_fork+0x7c/0xb0
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862525]  [<ffffffff8107d360>] ? kthread_create_on_node+0x120/0x120
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862528] INFO: task mount.zfs:20919 blocked for more than 120 seconds.
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862529] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862530] mount.zfs       D ffff88016fa13f40     0 20919      1 0x00000004
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862532]  ffff88012ab95758 0000000000000082 ffff880166685d00 ffff88012ab95fd8
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862534]  ffff88012ab95fd8 ffff88012ab95fd8 ffff880076ad8000 ffff880166685d00
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862536]  ffff880166685d00 ffff88016fa147f8 ffff8800028977e0 0000000000000001
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862538] Call Trace:
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862541]  [<ffffffff816cba89>] schedule+0x29/0x70
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862543]  [<ffffffff816cbb5f>] io_schedule+0x8f/0xd0
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862549]  [<ffffffffa01ac458>] cv_wait_common+0xa8/0x1b0 [spl]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862551]  [<ffffffff8107dd30>] ? finish_wait+0x80/0x80
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862557]  [<ffffffffa01ac578>] __cv_wait_io+0x18/0x20 [spl]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862574]  [<ffffffffa02d44d3>] zio_wait+0x103/0x1a0 [zfs]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862586]  [<ffffffffa023c5a4>] dbuf_read+0x314/0x7e0 [zfs]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862598]  [<ffffffffa023ce3c>] __dbuf_hold_impl+0x3cc/0x450 [zfs]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862609]  [<ffffffffa023cbdc>] __dbuf_hold_impl+0x16c/0x450 [zfs]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862620]  [<ffffffffa023cbdc>] __dbuf_hold_impl+0x16c/0x450 [zfs]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862631]  [<ffffffffa023cbdc>] __dbuf_hold_impl+0x16c/0x450 [zfs]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862642]  [<ffffffffa023cbdc>] __dbuf_hold_impl+0x16c/0x450 [zfs]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862653]  [<ffffffffa023cbdc>] __dbuf_hold_impl+0x16c/0x450 [zfs]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862665]  [<ffffffffa023cf4d>] dbuf_hold_impl+0x8d/0xc0 [zfs]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862676]  [<ffffffffa023cfe0>] dbuf_hold+0x20/0x40 [zfs]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862691]  [<ffffffffa0253790>] dnode_hold_impl+0x2d0/0x5f0 [zfs]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862695]  [<ffffffff8117da5d>] ? __kmalloc+0x13d/0x170
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862700]  [<ffffffffa01a1e16>] ? kmem_alloc_debug+0x96/0x3b0 [spl]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862714]  [<ffffffffa0253ac9>] dnode_hold+0x19/0x20 [zfs]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862726]  [<ffffffffa024322a>] dmu_buf_hold+0x4a/0x1b0 [zfs]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862729]  [<ffffffff816ca30d>] ? mutex_lock+0x1d/0x50
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862747]  [<ffffffffa02a226a>] zap_lockdir+0x5a/0x760 [zfs]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862764]  [<ffffffffa02dbd86>] ? zrl_init+0x36/0x40 [zfs]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862766]  [<ffffffff816ca30d>] ? mutex_lock+0x1d/0x50
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862784]  [<ffffffffa02a3e3a>] zap_lookup_norm+0x4a/0x190 [zfs]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862801]  [<ffffffffa02a4013>] zap_lookup+0x33/0x40 [zfs]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862818]  [<ffffffffa02bca07>] zfs_get_zplprop+0x57/0xc0 [zfs]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862834]  [<ffffffffa02bd936>] zfs_sb_create+0xa6/0x560 [zfs]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862836]  [<ffffffff816cabf2>] ? down_write+0x12/0x40
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862852]  [<ffffffffa02bf72f>] zfs_domount+0x2f/0x270 [zfs]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862855]  [<ffffffff811964c0>] ? get_anon_bdev+0x110/0x110
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862871]  [<ffffffffa02da970>] ? zpl_mount+0x30/0x30 [zfs]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862886]  [<ffffffffa02da97e>] zpl_fill_super+0xe/0x20 [zfs]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862888]  [<ffffffff81197246>] mount_nodev+0x56/0xb0
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862904]  [<ffffffffa02da965>] zpl_mount+0x25/0x30 [zfs]
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862906]  [<ffffffff811981a3>] mount_fs+0x43/0x1b0
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862909]  [<ffffffff811b2ba4>] vfs_kern_mount+0x74/0x110
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862912]  [<ffffffff811b4f1f>] do_mount+0x21f/0xac0
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862915]  [<ffffffff81133dae>] ? __get_free_pages+0xe/0x50
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862917]  [<ffffffff811b4b86>] ? copy_mount_options+0x36/0x170
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862919]  [<ffffffff811b584e>] sys_mount+0x8e/0xe0
Aug  9 17:23:53 pmb-LinuxBookAir kernel: [23723.862921]  [<ffffffff816d521d>] system_call_fastpath+0x1a/0x1f
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675395] INFO: task txg_sync:4738 blocked for more than 120 seconds.
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675399] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675400] txg_sync        D ffff88016fa53f40     0  4738      2 0x00000000
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675404]  ffff88007af2bb98 0000000000000046 ffff880034511740 ffff88007af2bfd8
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675407]  ffff88007af2bfd8 ffff88007af2bfd8 ffff880076bd1740 ffff880034511740
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675409]  ffff880034511740 ffff88016fa547f8 ffff880059d294b0 0000000000000001
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675412] Call Trace:
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675419]  [<ffffffff816cba89>] schedule+0x29/0x70
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675422]  [<ffffffff816cbb5f>] io_schedule+0x8f/0xd0
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675443]  [<ffffffffa01ac458>] cv_wait_common+0xa8/0x1b0 [spl]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675447]  [<ffffffff8107dd30>] ? finish_wait+0x80/0x80
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675454]  [<ffffffffa01ac578>] __cv_wait_io+0x18/0x20 [spl]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675482]  [<ffffffffa02d44d3>] zio_wait+0x103/0x1a0 [zfs]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675501]  [<ffffffffa0268958>] dsl_pool_sync+0x348/0x5d0 [zfs]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675522]  [<ffffffffa027f8c8>] spa_sync+0x3e8/0xa60 [zfs]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675525]  [<ffffffff810ac008>] ? ktime_get_ts+0x48/0xe0
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675546]  [<ffffffffa028efa3>] txg_sync_thread+0x323/0x590 [zfs]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675567]  [<ffffffffa028ec80>] ? txg_init+0x250/0x250 [zfs]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675573]  [<ffffffffa01a4c08>] thread_generic_wrapper+0x78/0x90 [spl]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675579]  [<ffffffffa01a4b90>] ? __thread_create+0x340/0x340 [spl]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675582]  [<ffffffff8107d420>] kthread+0xc0/0xd0
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675584]  [<ffffffff8107d360>] ? kthread_create_on_node+0x120/0x120
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675586]  [<ffffffff816d516c>] ret_from_fork+0x7c/0xb0
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675588]  [<ffffffff8107d360>] ? kthread_create_on_node+0x120/0x120
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675591] INFO: task mount.zfs:20919 blocked for more than 120 seconds.
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675592] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675593] mount.zfs       D ffff88016fa13f40     0 20919      1 0x00000004
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675595]  ffff88012ab95758 0000000000000082 ffff880166685d00 ffff88012ab95fd8
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675598]  ffff88012ab95fd8 ffff88012ab95fd8 ffff880076ad8000 ffff880166685d00
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675600]  ffff880166685d00 ffff88016fa147f8 ffff8800028977e0 0000000000000001
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675603] Call Trace:
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675605]  [<ffffffff816cba89>] schedule+0x29/0x70
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675608]  [<ffffffff816cbb5f>] io_schedule+0x8f/0xd0
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675615]  [<ffffffffa01ac458>] cv_wait_common+0xa8/0x1b0 [spl]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675617]  [<ffffffff8107dd30>] ? finish_wait+0x80/0x80
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675623]  [<ffffffffa01ac578>] __cv_wait_io+0x18/0x20 [spl]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675643]  [<ffffffffa02d44d3>] zio_wait+0x103/0x1a0 [zfs]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675656]  [<ffffffffa023c5a4>] dbuf_read+0x314/0x7e0 [zfs]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675670]  [<ffffffffa023ce3c>] __dbuf_hold_impl+0x3cc/0x450 [zfs]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675682]  [<ffffffffa023cbdc>] __dbuf_hold_impl+0x16c/0x450 [zfs]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675694]  [<ffffffffa023cbdc>] __dbuf_hold_impl+0x16c/0x450 [zfs]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675707]  [<ffffffffa023cbdc>] __dbuf_hold_impl+0x16c/0x450 [zfs]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675719]  [<ffffffffa023cbdc>] __dbuf_hold_impl+0x16c/0x450 [zfs]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675732]  [<ffffffffa023cbdc>] __dbuf_hold_impl+0x16c/0x450 [zfs]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675745]  [<ffffffffa023cf4d>] dbuf_hold_impl+0x8d/0xc0 [zfs]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675757]  [<ffffffffa023cfe0>] dbuf_hold+0x20/0x40 [zfs]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675773]  [<ffffffffa0253790>] dnode_hold_impl+0x2d0/0x5f0 [zfs]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675778]  [<ffffffff8117da5d>] ? __kmalloc+0x13d/0x170
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675785]  [<ffffffffa01a1e16>] ? kmem_alloc_debug+0x96/0x3b0 [spl]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675800]  [<ffffffffa0253ac9>] dnode_hold+0x19/0x20 [zfs]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675814]  [<ffffffffa024322a>] dmu_buf_hold+0x4a/0x1b0 [zfs]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675816]  [<ffffffff816ca30d>] ? mutex_lock+0x1d/0x50
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675837]  [<ffffffffa02a226a>] zap_lockdir+0x5a/0x760 [zfs]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675856]  [<ffffffffa02dbd86>] ? zrl_init+0x36/0x40 [zfs]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675859]  [<ffffffff816ca30d>] ? mutex_lock+0x1d/0x50
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675879]  [<ffffffffa02a3e3a>] zap_lookup_norm+0x4a/0x190 [zfs]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675898]  [<ffffffffa02a4013>] zap_lookup+0x33/0x40 [zfs]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675917]  [<ffffffffa02bca07>] zfs_get_zplprop+0x57/0xc0 [zfs]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675936]  [<ffffffffa02bd936>] zfs_sb_create+0xa6/0x560 [zfs]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675938]  [<ffffffff816cabf2>] ? down_write+0x12/0x40
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675957]  [<ffffffffa02bf72f>] zfs_domount+0x2f/0x270 [zfs]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675960]  [<ffffffff811964c0>] ? get_anon_bdev+0x110/0x110
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675978]  [<ffffffffa02da970>] ? zpl_mount+0x30/0x30 [zfs]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675996]  [<ffffffffa02da97e>] zpl_fill_super+0xe/0x20 [zfs]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.675998]  [<ffffffff81197246>] mount_nodev+0x56/0xb0
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.676016]  [<ffffffffa02da965>] zpl_mount+0x25/0x30 [zfs]
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.676021]  [<ffffffff811981a3>] mount_fs+0x43/0x1b0
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.676025]  [<ffffffff811b2ba4>] vfs_kern_mount+0x74/0x110
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.676028]  [<ffffffff811b4f1f>] do_mount+0x21f/0xac0
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.676032]  [<ffffffff81133dae>] ? __get_free_pages+0xe/0x50
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.676035]  [<ffffffff811b4b86>] ? copy_mount_options+0x36/0x170
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.676037]  [<ffffffff811b584e>] sys_mount+0x8e/0xe0
Aug  9 17:25:53 pmb-LinuxBookAir kernel: [23843.676039]  [<ffffffff816d521d>] system_call_fastpath+0x1a/0x1f

**Comment by behlendorf** [comment]
Closing as stale.  If anyone still hitting this let us know and we'll reopen it.
