### ISSUE TITLE
Contention between ZFS and SPL kernel threads on CPU 0

### ISSUE THREAD

**Issue by wbrown** [zfsonlinux/zfs#1666]
In ZoL, there are kernel threads that are locked to CPU 0, such as:

* `spl_kmem_cache`
* `z_rd_int/0`
* `z_ioctl_int/0`
* `z_wr_iss_h/0`
* `z_wr_iss/0`

Under an extremely heavy load, these kernel threads contend with each other on CPU 1, independently of `spl_kmem_cache`'s devour-all-humans behavior.  This is especially problematic when you consider that things like Infiniband and HBA adapters typically have their interrupt affinity bound to particular CPU's.

With the combination of `spl_kmem_cache` and the other kernel threads, my I/O pipeline is starved when they contend with each other.  While I'd like to figure out why `spl_kmem_cache` is doing this, I'd like to determine if there's a way to move the other threads that are contending with `spl_kmem_cache` to other CPU's.

![itermscreensnapz039](https://f.cloud.github.com/assets/36844/998398/ca398aee-09fd-11e3-8d36-81c850f1a429.png)

**Comment by behlendorf** [comment]
Sounds like no one objects.  Closing.
