### ISSUE TITLE
Putting ZFS into an end-of-disk DOS partition breaks zpool import when libblkid is not used

### ISSUE THREAD

**Issue by ryao** [zfsonlinux/zfs#1684]
If you place ZFS into an end-of-disk DOS partition and the ZFS utilties were built without libblkid, the import scan will spot the end of disk labels on raw block device and fail before examining the actual partition.

Using libblkid should mitigate this this, but unfortunately, the autotools check for that is broken. I filed issue #1683 for that.

**Comment by behlendorf** [comment]
Resolved in master libblkid is now mandatory.
