### ISSUE TITLE
vdev_id is brocken with multipath on RHEL6

### ISSUE THREAD

**Issue by antst** [zfsonlinux/zfs#1692]
Stock vddv_id goes crazy when I have 24 disks attached via multi path.

One reason is probably different output format of "multipath" from one used for script writing. 
Another reason is that script can not process correctly /dev/mapper/mpathp , because it assumes that "p" belongs to partition.

**Comment by behlendorf** [comment]
Closing.  This appears to be working as expected in CentOS 6.
