### ISSUE TITLE
configure doesn't support cross compiling

### ISSUE THREAD

**Issue by steev** [zfsonlinux/zfs#1715]
Just creating a bug because the configure script (as of 0.6.2) doesn't properly set ARCH when attempting to cross compile.

env EXTRA_ECONF='--enable-linux-builtin --with-linux=/home/steev/sandbox/images/chromebook-zfs/kernel --with-linux-obj=/home/steev/sandbox/images/chromebook-zfs/kernel --build=armv7a-hardfloat-linux-gnueabi --target=armv7a-hardfloat-linux-gnueabi' ebuild /usr/portage/sys-kernel/spl/spl-0.6.2.ebuild clean configure

still looks in arch/x86 for things instead of arch/arm as evidenced by:

5:40 PM <•ryao> steev: This line reveals the problem: /home/steev/sandbox/images/chromebook-zfs/kernel/arch/x86/include/asm/atomic64_64.h:89:33: error: unknown type name ‘atomic64_t’

**Comment by behlendorf** [comment]
Closing, cross-compiling can be accomplished as described in [comment](https://github.com/zfsonlinux/spl/issues/344#issuecomment-159696705).
