### ISSUE TITLE
Clang static analysis

### ISSUE THREAD

**Issue by chrisrd** [zfsonlinux/zfs#1721]
The code base (zfs + spl) should come up clean under static analysis by clang (and others?). To assist getting and keeping clean, the build tools should be updated to include this analysis, e.g. "make clang".

See Also:

http://thread.gmane.org/gmane.linux.file-systems.zfs.user/1503

**Comment by behlendorf** [comment]
Related to #1392.  For anyone interested in working on this the first step would be getting the existing  code base to pass the static analyzer without errors.

**Comment by behlendorf** [comment]
We've adopted Coverity as our static checker.  That said I'd love to be running multiple checkers, for example it would be nice to run this against every PR which we can't do with Coverity.  However, until someone has time to work on this I'm closing the issue.

https://scan.coverity.com/projects/zfsonlinux-zfs
