### ISSUE TITLE
zpool list hanged after iSCSI initiator login to iSCSI portal

### ISSUE THREAD

**Issue by arturpzol** [zfsonlinux/zfs#1725]
Hello,

We experienced hung for zpool list command after login to iSCSI portal. We are using 0.6.2 version.

Sep 16 16:30:45 [kern.notice] kernel: [  908.993196] sd 9:0:0:25: [sdaa] Attached SCSI disk
Sep 16 16:30:45 [kern.notice] kernel: [  908.996010] sd 9:0:0:26: [sdab] Attached SCSI disk
Sep 16 16:30:45 [kern.notice] kernel: [  908.996090] sd 9:0:0:27: [sdac] Attached SCSI disk
Sep 16 16:32:12 [kern.info] kernel: [  996.176833]  zd0: unknown partition table
Sep 16 16:33:18 [kern.err] kernel: [ 1062.369985] INFO: rcu_sched self-detected stall on CPU { 1}  (t=6000 jiffies)
Sep 16 16:33:18 [kern.err] kernel: [ 1062.369992] Pid: 24292, comm: zvol_id Tainted: P           O 3.4.61-oe64-00000-gc5bf7c4 #30
Sep 16 16:33:18 [kern.err] kernel: [ 1062.369994] Call Trace:
Sep 16 16:33:18 [kern.err] kernel: [ 1062.369996]  <IRQ>  [<ffffffff8100fcca>] ? update_vsyscall+0xaa/0xd0
Sep 16 16:33:18 [kern.err] kernel: [ 1062.370000]  [<ffffffff8109e32e>] ? __rcu_pending+0xbe/0x420
Sep 16 16:33:18 [kern.err] kernel: [ 1062.370000]  [<ffffffff8109e6af>] ? rcu_pending+0x1f/0x50
Sep 16 16:33:18 [kern.err] kernel: [ 1062.370000]  [<ffffffff8109ee85>] ? rcu_check_callbacks+0x25/0x60
Sep 16 16:33:18 [kern.err] kernel: [ 1062.370000]  [<ffffffff81048e1f>] ? update_process_times+0x3f/0x80
Sep 16 16:33:18 [kern.err] kernel: [ 1062.370000]  [<ffffffff8107436b>] ? tick_sched_timer+0x5b/0xa0
Sep 16 16:33:18 [kern.err] kernel: [ 1062.370000]  [<ffffffff8105b348>] ? __run_hrtimer+0x68/0x100
Sep 16 16:33:18 [kern.err] kernel: [ 1062.370000]  [<ffffffff81074310>] ? tick_do_update_jiffies64+0xc0/0xc0
Sep 16 16:33:18 [kern.err] kernel: [ 1062.370000]  [<ffffffff8105b4b7>] ? hrtimer_interrupt+0xd7/0x230
Sep 16 16:33:18 [kern.err] kernel: [ 1062.370000]  [<ffffffff810269c3>] ? smp_apic_timer_interrupt+0x63/0xa0
Sep 16 16:33:18 [kern.err] kernel: [ 1062.370000]  [<ffffffff815fb5ca>] ? apic_timer_interrupt+0x6a/0x70
Sep 16 16:33:18 [kern.err] kernel: [ 1062.370000]  <EOI>  [<ffffffff812b8ba8>] ? kobject_put+0x18/0x50
Sep 16 16:33:18 [kern.err] kernel: [ 1062.370000]  [<ffffffff8111a1c6>] ? __blkdev_get+0xc6/0x3e0
Sep 16 16:33:18 [kern.err] kernel: [ 1062.370000]  [<ffffffff81102c6f>] ? inode_init_always+0xff/0x1b0
Sep 16 16:33:18 [kern.err] kernel: [ 1062.370000]  [<ffffffff8111a810>] ? blkdev_get+0x330/0x330
Sep 16 16:33:18 [kern.err] kernel: [ 1062.370000]  [<ffffffff8111a6a6>] ? blkdev_get+0x1c6/0x330
Sep 16 16:33:18 [kern.err] kernel: [ 1062.370000]  [<ffffffff81057df8>] ? wake_up_bit+0x18/0x40
Sep 16 16:33:18 [kern.err] kernel: [ 1062.370000]  [<ffffffff811199f3>] ? bdget+0x123/0x130
Sep 16 16:33:18 [kern.err] kernel: [ 1062.370000]  [<ffffffff815f4b85>] ? _raw_spin_lock+0x5/0x10
Sep 16 16:33:18 [kern.err] kernel: [ 1062.370000]  [<ffffffff8111a810>] ? blkdev_get+0x330/0x330
Sep 16 16:33:18 [kern.err] kernel: [ 1062.370000]  [<ffffffff810e8891>] ? __dentry_open+0x131/0x300
Sep 16 16:33:18 [kern.err] kernel: [ 1062.370000]  [<ffffffff810f6a1a>] ? do_last+0x35a/0x920
Sep 16 16:33:18 [kern.err] kernel: [ 1062.370000]  [<ffffffff810f8592>] ? path_openat+0xe2/0x420
Sep 16 16:33:18 [kern.err] kernel: [ 1062.370000]  [<ffffffff810f907f>] ? do_path_lookup+0x2f/0xd0
Sep 16 16:33:18 [kern.err] kernel: [ 1062.370000]  [<ffffffff810e4274>] ? kmem_cache_free+0x14/0xa0
Sep 16 16:33:18 [kern.err] kernel: [ 1062.370000]  [<ffffffff810fa35c>] ? do_filp_open+0x4c/0xc0
Sep 16 16:33:18 [kern.err] kernel: [ 1062.370000]  [<ffffffff81100146>] ? dput+0x186/0x1a0
Sep 16 16:33:18 [kern.err] kernel: [ 1062.370000]  [<ffffffff8110510f>] ? alloc_fd+0xdf/0x120
Sep 16 16:33:18 [kern.err] kernel: [ 1062.370000]  [<ffffffff810e856e>] ? do_sys_open+0x10e/0x1f0
Sep 16 16:33:18 [kern.err] kernel: [ 1062.370000]  [<ffffffff810e86bf>] ? sys_open+0x6f/0x100
Sep 16 16:33:18 [kern.err] kernel: [ 1062.370000]  [<ffffffff810ef66b>] ? sys_newstat+0x4b/0x50
Sep 16 16:33:18 [kern.err] kernel: [ 1062.370000]  [<ffffffff815fab39>] ? system_call_fastpath+0x16/0x1b
Sep 16 16:36:18 [kern.err] kernel: [ 1242.399984] INFO: rcu_sched self-detected stall on CPU { 1}  (t=24003 jiffies)
Sep 16 16:36:18 [kern.err] kernel: [ 1242.399991] Pid: 24292, comm: zvol_id Tainted: P           O 3.4.61-oe64-00000-gc5bf7c4 #30
Sep 16 16:36:18 [kern.err] kernel: [ 1242.399993] Call Trace:
Sep 16 16:36:18 [kern.err] kernel: [ 1242.399995]  <IRQ>  [<ffffffff8100fcca>] ? update_vsyscall+0xaa/0xd0
Sep 16 16:36:18 [kern.err] kernel: [ 1242.400001]  [<ffffffff8109e32e>] ? __rcu_pending+0xbe/0x420
Sep 16 16:36:18 [kern.err] kernel: [ 1242.400001]  [<ffffffff8109e6af>] ? rcu_pending+0x1f/0x50
Sep 16 16:36:18 [kern.err] kernel: [ 1242.400001]  [<ffffffff8109ee85>] ? rcu_check_callbacks+0x25/0x60
Sep 16 16:36:18 [kern.err] kernel: [ 1242.400001]  [<ffffffff81048e1f>] ? update_process_times+0x3f/0x80
Sep 16 16:36:18 [kern.err] kernel: [ 1242.400001]  [<ffffffff8107436b>] ? tick_sched_timer+0x5b/0xa0
Sep 16 16:36:18 [kern.err] kernel: [ 1242.400001]  [<ffffffff8105b348>] ? __run_hrtimer+0x68/0x100
Sep 16 16:36:18 [kern.err] kernel: [ 1242.400001]  [<ffffffff81074310>] ? tick_do_update_jiffies64+0xc0/0xc0
Sep 16 16:36:18 [kern.err] kernel: [ 1242.400001]  [<ffffffff8105b4b7>] ? hrtimer_interrupt+0xd7/0x230
Sep 16 16:36:18 [kern.err] kernel: [ 1242.400001]  [<ffffffff810269c3>] ? smp_apic_timer_interrupt+0x63/0xa0
Sep 16 16:36:18 [kern.err] kernel: [ 1242.400001]  [<ffffffff815fb5ca>] ? apic_timer_interrupt+0x6a/0x70
Sep 16 16:36:18 [kern.err] kernel: [ 1242.400001]  <EOI>  [<ffffffff812aa4cc>] ? exact_lock+0xc/0x20
Sep 16 16:36:18 [kern.err] kernel: [ 1242.400001]  [<ffffffff8111a18f>] ? __blkdev_get+0x8f/0x3e0
Sep 16 16:36:18 [kern.err] kernel: [ 1242.400001]  [<ffffffff8111a178>] ? __blkdev_get+0x78/0x3e0
Sep 16 16:36:18 [kern.err] kernel: [ 1242.400001]  [<ffffffff81102c6f>] ? inode_init_always+0xff/0x1b0
Sep 16 16:36:18 [kern.err] kernel: [ 1242.400001]  [<ffffffff8111a810>] ? blkdev_get+0x330/0x330
Sep 16 16:36:18 [kern.err] kernel: [ 1242.400001]  [<ffffffff8111a6a6>] ? blkdev_get+0x1c6/0x330
Sep 16 16:36:18 [kern.err] kernel: [ 1242.400001]  [<ffffffff81057df8>] ? wake_up_bit+0x18/0x40
Sep 16 16:36:18 [kern.err] kernel: [ 1242.400001]  [<ffffffff811199f3>] ? bdget+0x123/0x130
Sep 16 16:36:18 [kern.err] kernel: [ 1242.400001]  [<ffffffff815f4b85>] ? _raw_spin_lock+0x5/0x10
Sep 16 16:36:18 [kern.err] kernel: [ 1242.400001]  [<ffffffff8111a810>] ? blkdev_get+0x330/0x330
Sep 16 16:36:18 [kern.err] kernel: [ 1242.400001]  [<ffffffff810e8891>] ? __dentry_open+0x131/0x300
Sep 16 16:36:18 [kern.err] kernel: [ 1242.400001]  [<ffffffff810f6a1a>] ? do_last+0x35a/0x920
Sep 16 16:36:18 [kern.err] kernel: [ 1242.400001]  [<ffffffff810f8592>] ? path_openat+0xe2/0x420
Sep 16 16:36:18 [kern.err] kernel: [ 1242.400001]  [<ffffffff810f907f>] ? do_path_lookup+0x2f/0xd0
Sep 16 16:36:18 [kern.err] kernel: [ 1242.400001]  [<ffffffff810e4274>] ? kmem_cache_free+0x14/0xa0
Sep 16 16:36:18 [kern.err] kernel: [ 1242.400001]  [<ffffffff810fa35c>] ? do_filp_open+0x4c/0xc0
Sep 16 16:36:18 [kern.err] kernel: [ 1242.400001]  [<ffffffff81100146>] ? dput+0x186/0x1a0
Sep 16 16:36:18 [kern.err] kernel: [ 1242.400001]  [<ffffffff8110510f>] ? alloc_fd+0xdf/0x120
Sep 16 16:36:18 [kern.err] kernel: [ 1242.400001]  [<ffffffff810e856e>] ? do_sys_open+0x10e/0x1f0
Sep 16 16:36:18 [kern.err] kernel: [ 1242.400001]  [<ffffffff810e86bf>] ? sys_open+0x6f/0x100
Sep 16 16:36:18 [kern.err] kernel: [ 1242.400001]  [<ffffffff810ef66b>] ? sys_newstat+0x4b/0x50
Sep 16 16:36:18 [kern.err] kernel: [ 1242.400001]  [<ffffffff815fab39>] ? system_call_fastpath+0x16/0x1b

**Comment by behlendorf** [comment]
Closing as stale.
