### ISSUE TITLE
Zfs incremental recv fails with dataset is busy error

### ISSUE THREAD

**Issue by olw2005** [zfsonlinux/zfs#1761]
Dear All,
First let me say, keep up the great work!  Happy to see my tax dollars funding something useful.

Brief problem description:
We have two servers setup to send rotating incremental snapshots of the local zvol to each other (zfs send -I).  In the main this works well, but about once a week the zfs recv fails with a 'dataset is busy' error.

Dmesg output is:
Buffer I/O error on device zd16, logical block 0
Buffer I/O error on device zd16, logical block 0
Buffer I/O error on device zd16, logical block 0

Expected dmesg output:
 zd16:
GPT:Primary header thinks Alt. header is not at the end of the disk.
GPT:34358689719 != 34359738367
GPT:Alternate GPT header not at the end of the disk.
GPT:34358689719 != 34359738367
GPT: Use GNU Parted to correct GPT errors.
 p1
(The zvol is used as the disk for a drbd resource.  Drbd uses the last bit of the disk to store its own metadata, presenting a slightly smaller disk to layers above it.  Thus the spurious GPT warning is normal / expected.)

After this error, all subsequent zfs recv's on that particular zvol [pool/chicagorepl] with the same error.  Only way to clear the error is to reboot the server.  Meanwhile, the two other zvols [arch/archive and pool/detroit] on the server continue to work fine, creating / sending / destroying snapshots w/o issue.

Server Configuration / Setup Info:
HP DL380p Gen8, 192 GB RAM, four external disk chassis [48 disks], two ssd's setup as l2arc cache disks
CentOS 6.4 with recent updates
zfs & spl 0.6.2

[root@dtc-san2 ~]# uname -a
Linux dtc-san2.stc.ricplc.com 2.6.32-358.18.1.el6.x86_64 #1 SMP Wed Aug 28 17:19:38 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

[root@dtc-san2 ~]# cat /etc/modprobe.d/zfs.conf
options zfs zfs_nocacheflush=1 zfs_arc_max=154618822656 zfs_arc_min=1073741824

[root@dtc-san2 ~]# zpool status
  pool: arch
 state: ONLINE
  scan: none requested
config:

        NAME        STATE     READ WRITE CKSUM
        arch        ONLINE       0     0     0
          raidz2-0  ONLINE       0     0     0
            sdan    ONLINE       0     0     0
            sdao    ONLINE       0     0     0
            sdap    ONLINE       0     0     0
            sdaq    ONLINE       0     0     0
            sdar    ONLINE       0     0     0
            sdas    ONLINE       0     0     0
            sdat    ONLINE       0     0     0
            sdau    ONLINE       0     0     0
            sdav    ONLINE       0     0     0
            sdaw    ONLINE       0     0     0
            sdax    ONLINE       0     0     0
        spares
          sday      AVAIL

errors: No known data errors

  pool: pool
 state: ONLINE
  scan: none requested
config:

        NAME        STATE     READ WRITE CKSUM
        pool        ONLINE       0     0     0
          raidz2-0  ONLINE       0     0     0
            sdd     ONLINE       0     0     0
            sde     ONLINE       0     0     0
            sdf     ONLINE       0     0     0
            sdg     ONLINE       0     0     0
            sdh     ONLINE       0     0     0
            sdi     ONLINE       0     0     0
            sdj     ONLINE       0     0     0
            sdk     ONLINE       0     0     0
            sdl     ONLINE       0     0     0
            sdm     ONLINE       0     0     0
          raidz2-1  ONLINE       0     0     0
            sdp     ONLINE       0     0     0
            sdq     ONLINE       0     0     0
            sdr     ONLINE       0     0     0
            sds     ONLINE       0     0     0
            sdt     ONLINE       0     0     0
            sdu     ONLINE       0     0     0
            sdv     ONLINE       0     0     0
            sdw     ONLINE       0     0     0
            sdx     ONLINE       0     0     0
            sdy     ONLINE       0     0     0
          raidz2-2  ONLINE       0     0     0
            sdab    ONLINE       0     0     0
            sdac    ONLINE       0     0     0
            sdae    ONLINE       0     0     0
            sdaf    ONLINE       0     0     0
            sdag    ONLINE       0     0     0
            sdah    ONLINE       0     0     0
            sdai    ONLINE       0     0     0
            sdaj    ONLINE       0     0     0
            sdak    ONLINE       0     0     0
        cache
          sdb       ONLINE       0     0     0
          sdc       ONLINE       0     0     0
        spares
          sdn       AVAIL
          sdo       AVAIL
          sdz       AVAIL
          sdaa      AVAIL
          sdal      AVAIL
          sdam      AVAIL

errors: No known data errors

[root@dtc-san2 ~]# zfs list
NAME               USED  AVAIL  REFER  MOUNTPOINT
arch              19.8T  4.20T  65.8K  none
arch/archive      19.8T  4.20T  19.1T  -
pool              20.8T  40.6T  64.5K  none
pool/chicagorepl  5.98T  40.6T  4.77T  -
pool/detroit      14.6T  40.6T  13.8T  -
pool/vdistore      177G  40.6T   177G  -

Abbreviated zpool history:
History for 'arch':
...
2013-09-30.14:16:07 zfs snapshot arch/archive@hour-20130930141601
2013-09-30.14:16:33 zfs send -I arch/archive@hour-20130930131601 arch/archive@hour-20130930141601
2013-09-30.14:28:10 zfs destroy arch/archive@hour-20130930101601
2013-09-30.15:16:07 zfs snapshot arch/archive@hour-20130930151601
2013-09-30.15:16:31 zfs send -I arch/archive@hour-20130930141601 arch/archive@hour-20130930151601

History for 'pool':
...
2013-09-30.12:05:11 zfs recv -F pool/chicagorepl
2013-09-30.12:05:33 zfs destroy pool/chicagorepl@hour-20130930070101
2013-09-30.12:14:13 zfs destroy pool/detroit@hour-20130930064601
2013-09-30.12:14:20 zfs destroy pool/detroit@hour-20130930074601
2013-09-30.12:42:06 zfs snapshot pool/detroit@4hour-20130930124201
2013-09-30.12:42:32 zfs destroy pool/detroit@4hour-20130929124201
2013-09-30.12:46:06 zfs snapshot pool/detroit@hour-20130930124601
2013-09-30.12:46:49 zfs send -I pool/detroit@hour-20130930114601 pool/detroit@hour-20130930124601
2013-09-30.12:54:15 zfs destroy pool/detroit@hour-20130930084601
2013-09-30.13:20:01 zfs recv -F pool/chicagorepl
2013-09-30.13:20:20 zfs destroy pool/chicagorepl@hour-20130930080101
2013-09-30.13:46:07 zfs snapshot pool/detroit@hour-20130930134601
2013-09-30.13:46:53 zfs send -I pool/detroit@hour-20130930124601 pool/detroit@hour-20130930134601
2013-09-30.14:00:29 zfs destroy pool/detroit@hour-20130930094601
2013-09-30.14:01:23 zfs destroy pool/chicagorepl@4hour-20130929125601
---->  2013-09-30.14:02:40 zfs recv -F pool/chicagorepl
2013-09-30.14:46:06 zfs snapshot pool/detroit@hour-20130930144601
2013-09-30.14:46:47 zfs send -I pool/detroit@hour-20130930134601 pool/detroit@hour-20130930144601

Line marked with ----> is where it went south.  Note the subsequent snapshot and send operations of "pool/detroit" and "arch/archive" had no errors...

If I can provide more information, please let me know.  I'm an engineer / IT guy not a developer, but I can read and follow instructions well.  =)  I have purposefully left the system as-is.  It is non-primary storage, so it can be rebooted / recompiled / whatever as needed.  Looking forward to hear from you!

Regards,
Owen L. Wieck
Ricardo, Inc.

**Comment by kpande** [comment]
this is resolved for me as of 0.6.4

**Comment by behlendorf** [comment]
Yes.  This should be fixed, I'll close it out.

**Comment by kpande** [comment]
i'm actually having trouble with this now... shouldn't have said anything!

**Comment by setaou** [comment]
I am having the same problem. For now i use zvol_inhibit_dev=1 as a workaround, but it is only acceptable because I dont need to actually use the zvols on the destination server.
