### ISSUE TITLE
Strange error when setting zpool property

### ISSUE THREAD

**Issue by kolczykm** [zfsonlinux/zfs#1764]
I was testing zpool set command and I have found strange issue. I got one zpool called test1 and I was trying to set some properties on this zpool. Actually it was working correctly but I found that in some cases I got strange errors. To be honest I was plying with it around to learn about zpool set and I have done following thing in bash:

```
while true; echo "aa"; do zpool set autoexpand=on test1; zpool set comment=jesteme test1; done
```

When I run this small script from time to time zpool reported following error:

```
cannot set property for 'test1': invalid argument for this pool operation
```

I was also able to manually cause this error by just executing command:

```
zpool set comment=jesteme test1
```

a couple of times.
That will sound really strange but when I have changed value of comment property to for example "test abc" it was working correctly. This comment "jesteme" is just random typed characters that I have typed to test what will happen when I set this property. Is this value forbidden for comment property or it is some kind of error.

I'm asking this question because I would like to write script that is able to set some properties for zpool (more than one), this properties will be set in some king of loop - one after another. I just wondering if this kind of setting properties is safe, I mean when zpool set exits can I attempt to set next property or should I wait some time?

**Comment by behlendorf** [comment]
Closing as stale.
