### ISSUE TITLE
Hang on import

### ISSUE THREAD

**Issue by guggemand** [zfsonlinux/zfs#1769]
0.6.2 on ubuntu 12.04 - kernel http://paste2.org/a31mv102

zpool configuration

   pool: device
     id: 14134663061318631327
  state: ONLINE
 status: One or more devices were being resilvered.
 action: The pool can be imported using its name or numeric identifier.
 config:

        device                     ONLINE
          device01                 ONLINE
          device02                 ONLINE
          device03                 ONLINE
          device04                 ONLINE
          device05                 ONLINE
          device06                 ONLINE
          device07                 ONLINE
          device08                 ONLINE
          device09                 ONLINE
          device10                 ONLINE
          replacing-10             ONLINE
            devicetest             ONLINE
            device11               ONLINE

[  278.028884] VERIFY3(0 == dmu_object_info(os, bpo.bpo_phys->bpo_subobjs, &doi)) failed (0 == 22)
[  278.029399] SPLError: 4172:0:(bpobj.c:112:bpobj_free()) SPL PANIC
[  278.029743] SPL: Showing stack for process 4172
[  278.029748] Pid: 4172, comm: txg_sync Tainted: PF          O 3.8.0-31-generic #46~precise1-Ubuntu
[  278.029751] Call Trace:
[  278.029777]  [<ffffffffa02274d7>] spl_debug_dumpstack+0x27/0x40 [spl]
[  278.029788]  [<ffffffffa02287d2>] spl_debug_bug+0x82/0xe0 [spl]
[  278.029824]  [<ffffffffa02e7530>] bpobj_free+0x350/0x360 [zfs]
[  278.029872]  [<ffffffffa035422a>] ? spa_feature_is_active+0x8a/0xa0 [zfs]
[  278.029910]  [<ffffffffa031039e>] dsl_deadlist_free+0x6e/0x1a0 [zfs]
[  278.029918]  [<ffffffff8118464b>] ? kfree+0x3b/0x150
[  278.029945]  [<ffffffffa02e9569>] ? dbuf_rele_and_unlock+0x169/0x210 [zfs]
[  278.029971]  [<ffffffffa02e99bf>] ? dmu_buf_rele+0x2f/0x40 [zfs]
[  278.029997]  [<ffffffffa02e9569>] ? dbuf_rele_and_unlock+0x169/0x210 [zfs]
[  278.030022]  [<ffffffffa02e99bf>] ? dmu_buf_rele+0x2f/0x40 [zfs]
[  278.030056]  [<ffffffffa03021a0>] ? dnode_rele+0x80/0x90 [zfs]
[  278.030082]  [<ffffffffa02e95b0>] ? dbuf_rele_and_unlock+0x1b0/0x210 [zfs]
[  278.030117]  [<ffffffffa030c854>] dsl_dataset_destroy_sync+0x584/0xf80 [zfs]
[  278.030142]  [<ffffffffa02e9569>] ? dbuf_rele_and_unlock+0x169/0x210 [zfs]
[  278.030168]  [<ffffffffa02e99bf>] ? dmu_buf_rele+0x2f/0x40 [zfs]
[  278.030212]  [<ffffffffa035366d>] ? zap_count+0x4d/0x70 [zfs]
[  278.030251]  [<ffffffffa031f2f3>] dsl_sync_task_group_sync+0x123/0x210 [zfs]
[  278.030288]  [<ffffffffa031736b>] dsl_pool_sync+0x41b/0x530 [zfs]
[  278.030329]  [<ffffffffa032cca4>] spa_sync+0x414/0xae0 [zfs]
[  278.030336]  [<ffffffff810ae8ac>] ? ktime_get_ts+0x4c/0xe0
[  278.030379]  [<ffffffffa033dcef>] txg_sync_thread+0x2df/0x540 [zfs]
[  278.030421]  [<ffffffffa033da10>] ? txg_init+0x250/0x250 [zfs]
[  278.030434]  [<ffffffffa022fc08>] thread_generic_wrapper+0x78/0x90 [spl]
[  278.030445]  [<ffffffffa022fb90>] ? __thread_create+0x310/0x310 [spl]
[  278.030452]  [<ffffffff8107f1d0>] kthread+0xc0/0xd0
[  278.030458]  [<ffffffff8107f110>] ? flush_kthread_worker+0xb0/0xb0
[  278.030465]  [<ffffffff816fcb2c>] ret_from_fork+0x7c/0xb0
[  278.030470]  [<ffffffff8107f110>] ? flush_kthread_worker+0xb0/0xb0

**Comment by behlendorf** [comment]
Closing as stale.
