### ISSUE TITLE
Feature: canmount property for volumes

### ISSUE THREAD

**Issue by GregorKopka** [zfsonlinux/zfs#1796]
Proposal: enable logic behind canmount property of filesystems for volumes.

**on**
device nodes created at pool import / volume creation|recv (default as of now)
**noauto**
device nodes can be created by issuing `zfs mount <volume>` 
  and removed by `zfs umount <volume>` or `zfs umount -a`
**off**
device nodes will not be created on zfs mount <volume> with same error as with filesystems (cannot mount '<volume>': 'canmount' property is set to 'off')

A different name for the property would make sense (like with snapdir and snapdev), which would have the additional benefit of the property being inerhitable (which canmount is not) and be setable on container filesystems without affecting them.
Suggestion: **devnode** 

**Problem with current behaviour**

SSD pool (fast but limited space) for active zvols (f.ex. as iSCSI targets) is backed up /send/recv) to a HDD pool (slow cheap space to keep a long chain of snapshots) on the same machine.
- /dev is cluttered with zd\* devices from the backup tree.
- the only reliable way to access the 'right' volume is through /dev/zvol/<path> since the symlinks (created by udev from data in the zvols) in /dev/disk/by-[label|partlabel|partuuid|uuid] point to the last /dev/zd\* zfs has created,
  this makes them kind-of nondeterministic and useless.

Should one be able to supress creation of /dev/zd\* in the backup pool (or as suggested on per-volume basis or dataset subtree through inheritance) then the symlinks created through udev could be useful, since one could make sure to only have 'live' ones show up.

Also backup servers which hold volumes (but will never mount them) won't have /dev cluttered up with unneeded zd*, this would lead to faster pool import and less overhead on zfs recv <volume> since the /dev nodes don't have to be destroyed/recreated.

**Comment by loli10K** [comment]
Sorry to revive an old issue but i've seen this requested again in the mailing list:

http://list.zfsonlinux.org/pipermail/zfs-discuss/2017-May/028228.html

>Is it possible to inhibit the creation of ZVOLs for just one pool or dataset? I know there's a module knob, but I'm in a situation where I have several pools, one of them serving as backup pool, and I'm hitting a race condition with ZVOL creation. Sometimes I am unable to receive into the pool because dataset it busy - most likely zvol_id doing its thing...
>
>In another situation, I am mounting a filesystem on a ZVOL by label, and when second pool on the same machine gets this dataset it can get confused a bit...
>
>Thanks
>
>Jan

Is anyone already working on this? I don't know much about ZVOL code so i would like to try implementing this.

**Comment by lundman** [comment]
Doesn't FreeBSD have the volmode property, as in
`volmode=default | geom | dev | none`

where you can set a volume to `none`, perhaps porting that feature over, but skipping `geom` would be an idea. We have considered it for OsX as well, with `iokit` as the `geom` option.

**Comment by loli10K** [comment]
@lundman nice, thanks! It's definitely worth checking out the existing FreeBSD code, i wonder why it has not been upstreamed (yet), seems a nice feature to have.

**Comment by DeHackEd** [comment]
This was discussed in #3438 in the past. Some ideas were thrown around for porting to Linux.

**Comment by behlendorf** [comment]
I think it's definitely worth investigating porting the FreeBSD `volmode` property.  In the process it would be good to determine how to adapt/extend it so it makes sense for Linux and OsX.
