### ISSUE TITLE
system freezes when starting to swap to zvol

### ISSUE THREAD

**Issue by maci0** [zfsonlinux/zfs#1798]
<pre>
root@nb0815 ~ # free -m
             total       used       free     shared    buffers     cached
Mem:          3832       1735       2097          0          0        230
-/+ buffers/cache:       1504       2328
Swap:         8191          0       8191

root@nb0815 ~ # zpool status
  pool: rpool
 state: ONLINE
  scan: scrub repaired 0 in 0h31m with 0 errors on Thu Oct 17 18:55:01 2013
config:

	NAME                              STATE     READ WRITE CKSUM
	rpool                             ONLINE       0     0     0
	  ata-ST9250410AS_5VGB002J-part2  ONLINE       0     0     0

errors: No known data errors

130 root@nb0815 ~ # zfs get all rpool/swap                                   :(
NAME        PROPERTY               VALUE                  SOURCE
rpool/swap  type                   volume                 -
rpool/swap  creation               Wed Oct  2 23:53 2013  -
rpool/swap  used                   8.50G                  -
rpool/swap  available              152G                   -
rpool/swap  referenced             264M                   -
rpool/swap  compressratio          2.59x                  -
rpool/swap  reservation            none                   default
rpool/swap  volsize                8G                     local
rpool/swap  volblocksize           4K                     -
rpool/swap  checksum               on                     default
rpool/swap  compression            on                     local
rpool/swap  readonly               off                    default
rpool/swap  copies                 1                      default
rpool/swap  refreservation         8.50G                  local
rpool/swap  primarycache           metadata               local
rpool/swap  secondarycache         none                   local
rpool/swap  usedbysnapshots        0                      -
rpool/swap  usedbydataset          264M                   -
rpool/swap  usedbychildren         0                      -
rpool/swap  usedbyrefreservation   8.25G                  -
rpool/swap  logbias                latency                default
rpool/swap  dedup                  off                    default
rpool/swap  mlslabel               none                   default
rpool/swap  sync                   always                 local
rpool/swap  refcompressratio       2.59x                  -
rpool/swap  written                264M                   -
rpool/swap  snapdev                hidden                 default
rpool/swap  com.sun:auto-snapshot  false                  local

root@nb0815 ~ # swapon -s      
Filename				Type		Size	Used	Priority
/dev/zd0                               	partition	8388604	0	-1

root@nb0815 ~ # zfs list -t all
NAME                                                  USED  AVAIL  REFER  MOUNTPOINT
rpool                                                84.7G   144G    31K  none
rpool/ROOT                                           6.64G   144G  4.27G  /
rpool/ROOT@zfs-auto-snap_daily-2013-10-05-1808       16.0M      -  2.22G  -
rpool/ROOT@zfs-auto-snap_daily-2013-10-06-0114       14.4M      -  2.21G  -
rpool/ROOT@zfs-auto-snap_daily-2013-10-07-0944       21.1M      -  2.27G  -
rpool/ROOT@zfs-auto-snap_daily-2013-10-08-0111       17.6M      -  2.28G  -
rpool/ROOT@zfs-auto-snap_daily-2013-10-09-1431       8.09M      -  2.21G  -
rpool/ROOT@zfs-auto-snap_daily-2013-10-10-0935       1.33M      -  2.21G  -
rpool/ROOT@zfs-auto-snap_weekly-2013-10-10-0955      1.34M      -  2.21G  -
rpool/ROOT@zfs-auto-snap_daily-2013-10-11-0834       12.1M      -  2.24G  -
rpool/ROOT@zfs-auto-snap_daily-2013-10-12-0144       11.6M      -  2.30G  -
rpool/ROOT@zfs-auto-snap_daily-2013-10-13-0123       13.4M      -  2.30G  -
rpool/ROOT@zfs-auto-snap_daily-2013-10-14-0920       15.7M      -  3.09G  -
rpool/ROOT@zfs-auto-snap_daily-2013-10-15-1019       18.6M      -  3.11G  -
rpool/ROOT@zfs-auto-snap_daily-2013-10-16-0143       84.8M      -  3.21G  -
rpool/ROOT@zfs-auto-snap_daily-2013-10-17-1125       33.1M      -  3.23G  -
rpool/ROOT@zfs-auto-snap_daily-2013-10-18-0127        680K      -  3.50G  -
rpool/ROOT@zfs-auto-snap_weekly-2013-10-18-0147       684K      -  3.50G  -
rpool/ROOT@zfs-auto-snap_daily-2013-10-19-1150       16.0M      -  3.51G  -
rpool/ROOT@zfs-auto-snap_daily-2013-10-20-0126        949K      -  3.56G  -
rpool/ROOT@zfs-auto-snap_hourly-2013-10-20-0501       980K      -  3.56G  -
rpool/ROOT@zfs-auto-snap_hourly-2013-10-20-1001      5.54M      -  3.56G  -
rpool/ROOT@zfs-auto-snap_hourly-2013-10-20-1101      2.69M      -  3.56G  -
rpool/ROOT@zfs-auto-snap_hourly-2013-10-20-1201      2.08M      -  3.56G  -
rpool/ROOT@zfs-auto-snap_hourly-2013-10-20-1501      3.15M      -  3.56G  -
rpool/ROOT@zfs-auto-snap_hourly-2013-10-20-1601      2.33M      -  3.56G  -
rpool/ROOT@zfs-auto-snap_hourly-2013-10-20-1701      3.73M      -  3.56G  -
rpool/ROOT@zfs-auto-snap_hourly-2013-10-20-1801      7.25M      -  3.57G  -
rpool/ROOT@zfs-auto-snap_hourly-2013-10-20-1901      7.09M      -  3.57G  -
rpool/ROOT@zfs-auto-snap_hourly-2013-10-20-2101      1.32M      -  3.57G  -
rpool/ROOT@zfs-auto-snap_hourly-2013-10-20-2201      1.34M      -  3.57G  -
rpool/ROOT@zfs-auto-snap_hourly-2013-10-20-2301      1.23M      -  3.57G  -
rpool/ROOT@zfs-auto-snap_hourly-2013-10-21-0001      1.23M      -  3.57G  -
rpool/ROOT@zfs-auto-snap_hourly-2013-10-21-0101      1.23M      -  3.57G  -
rpool/ROOT@zfs-auto-snap_daily-2013-10-21-0138       1.21M      -  3.57G  -
rpool/ROOT@zfs-auto-snap_hourly-2013-10-21-0201      1.22M      -  3.57G  -
rpool/ROOT@zfs-auto-snap_hourly-2013-10-21-0301      1.20M      -  3.57G  -
rpool/ROOT@zfs-auto-snap_hourly-2013-10-21-0401      1.22M      -  3.57G  -
rpool/ROOT@zfs-auto-snap_hourly-2013-10-21-0501      1.25M      -  3.57G  -
rpool/ROOT@zfs-auto-snap_hourly-2013-10-21-0601      1.27M      -  3.57G  -
rpool/ROOT@zfs-auto-snap_hourly-2013-10-21-0701      3.46M      -  3.57G  -
rpool/ROOT@zfs-auto-snap_hourly-2013-10-21-1001      15.2M      -  3.62G  -
rpool/ROOT@zfs-auto-snap_hourly-2013-10-21-1101      16.5M      -  4.27G  -
rpool/ROOT@zfs-auto-snap_hourly-2013-10-21-1201       826K      -  4.27G  -
rpool/ROOT@zfs-auto-snap_frequent-2013-10-21-1215     785K      -  4.27G  -
rpool/ROOT@zfs-auto-snap_frequent-2013-10-21-1230     812K      -  4.27G  -
rpool/ROOT@zfs-auto-snap_frequent-2013-10-21-1245     890K      -  4.27G  -
rpool/ROOT@zfs-auto-snap_frequent-2013-10-21-1300     808K      -  4.27G  -
rpool/ROOT@zfs-auto-snap_hourly-2013-10-21-1301      1.07M      -  4.27G  -
rpool/backup                                         58.5M   144G  58.1M  /backup
rpool/backup@zfs-auto-snap_daily-2013-10-05-1808         0      -  58.1M  -
rpool/backup@zfs-auto-snap_daily-2013-10-06-0114         0      -  58.1M  -
rpool/backup@zfs-auto-snap_daily-2013-10-07-0944         0      -  58.1M  -
rpool/backup@zfs-auto-snap_daily-2013-10-08-0111         0      -  58.1M  -
rpool/backup@zfs-auto-snap_daily-2013-10-09-1431         0      -  58.1M  -
rpool/backup@zfs-auto-snap_daily-2013-10-10-0935         0      -  58.1M  -
rpool/backup@zfs-auto-snap_weekly-2013-10-10-0955        0      -  58.1M  -
rpool/backup@zfs-auto-snap_daily-2013-10-11-0834         0      -  58.1M  -
rpool/backup@zfs-auto-snap_daily-2013-10-12-0144         0      -  58.1M  -
rpool/backup@zfs-auto-snap_daily-2013-10-13-0123         0      -  58.1M  -
rpool/backup@zfs-auto-snap_daily-2013-10-14-0920         0      -  58.1M  -
rpool/backup@zfs-auto-snap_daily-2013-10-15-1019         0      -  58.1M  -
rpool/backup@zfs-auto-snap_daily-2013-10-16-0143         0      -  58.1M  -
rpool/backup@zfs-auto-snap_daily-2013-10-17-1125         0      -  58.1M  -
rpool/backup@zfs-auto-snap_daily-2013-10-18-0127         0      -  58.1M  -
rpool/backup@zfs-auto-snap_weekly-2013-10-18-0147        0      -  58.1M  -
rpool/backup@zfs-auto-snap_daily-2013-10-19-1150         0      -  58.1M  -
rpool/backup@zfs-auto-snap_daily-2013-10-20-0126         0      -  58.1M  -
rpool/backup@zfs-auto-snap_hourly-2013-10-20-0501        0      -  58.1M  -
rpool/backup@zfs-auto-snap_hourly-2013-10-20-1001        0      -  58.1M  -
rpool/backup@zfs-auto-snap_hourly-2013-10-20-1101        0      -  58.1M  -
rpool/backup@zfs-auto-snap_hourly-2013-10-20-1201        0      -  58.1M  -
rpool/backup@zfs-auto-snap_hourly-2013-10-20-1501        0      -  58.1M  -
rpool/backup@zfs-auto-snap_hourly-2013-10-20-1601        0      -  58.1M  -
rpool/backup@zfs-auto-snap_hourly-2013-10-20-1701        0      -  58.1M  -
rpool/backup@zfs-auto-snap_hourly-2013-10-20-1801        0      -  58.1M  -
rpool/backup@zfs-auto-snap_hourly-2013-10-20-1901        0      -  58.1M  -
rpool/backup@zfs-auto-snap_hourly-2013-10-20-2101        0      -  58.1M  -
rpool/backup@zfs-auto-snap_hourly-2013-10-20-2201        0      -  58.1M  -
rpool/backup@zfs-auto-snap_hourly-2013-10-20-2301        0      -  58.1M  -
rpool/backup@zfs-auto-snap_hourly-2013-10-21-0001        0      -  58.1M  -
rpool/backup@zfs-auto-snap_hourly-2013-10-21-0101        0      -  58.1M  -
rpool/backup@zfs-auto-snap_daily-2013-10-21-0138         0      -  58.1M  -
rpool/backup@zfs-auto-snap_hourly-2013-10-21-0201        0      -  58.1M  -
rpool/backup@zfs-auto-snap_hourly-2013-10-21-0301        0      -  58.1M  -
rpool/backup@zfs-auto-snap_hourly-2013-10-21-0401        0      -  58.1M  -
rpool/backup@zfs-auto-snap_hourly-2013-10-21-0501        0      -  58.1M  -
rpool/backup@zfs-auto-snap_hourly-2013-10-21-0601        0      -  58.1M  -
rpool/backup@zfs-auto-snap_hourly-2013-10-21-0701        0      -  58.1M  -
rpool/backup@zfs-auto-snap_hourly-2013-10-21-1001        0      -  58.1M  -
rpool/backup@zfs-auto-snap_hourly-2013-10-21-1101        0      -  58.1M  -
rpool/backup@zfs-auto-snap_hourly-2013-10-21-1201        0      -  58.1M  -
rpool/backup@zfs-auto-snap_frequent-2013-10-21-1215      0      -  58.1M  -
rpool/backup@zfs-auto-snap_frequent-2013-10-21-1230      0      -  58.1M  -
rpool/backup@zfs-auto-snap_frequent-2013-10-21-1245      0      -  58.1M  -
rpool/backup@zfs-auto-snap_frequent-2013-10-21-1300      0      -  58.1M  -
rpool/backup@zfs-auto-snap_hourly-2013-10-21-1301        0      -  58.1M  -
rpool/downloads                                      18.5G   144G  18.5G  /home/maci/Downloads
rpool/home                                           28.4G   144G  23.7G  /home
rpool/home@zfs-auto-snap_daily-2013-10-05-1808       10.9M      -  12.8G  -
rpool/home@zfs-auto-snap_daily-2013-10-06-0114       41.9M      -  12.8G  -
rpool/home@zfs-auto-snap_daily-2013-10-07-0944        272M      -  12.1G  -
rpool/home@zfs-auto-snap_daily-2013-10-08-0111       27.1M      -  11.9G  -
rpool/home@zfs-auto-snap_daily-2013-10-09-1431       14.5M      -  11.9G  -
rpool/home@zfs-auto-snap_daily-2013-10-10-0935       57.5K      -  12.9G  -
rpool/home@zfs-auto-snap_weekly-2013-10-10-0955      57.5K      -  12.9G  -
rpool/home@zfs-auto-snap_daily-2013-10-11-0834       25.0M      -  12.9G  -
rpool/home@zfs-auto-snap_daily-2013-10-12-0144       64.3M      -  12.9G  -
rpool/home@zfs-auto-snap_daily-2013-10-13-0123       26.2M      -  20.8G  -
rpool/home@zfs-auto-snap_daily-2013-10-14-0920        303M      -  21.1G  -
rpool/home@zfs-auto-snap_daily-2013-10-15-1019       36.5M      -  20.8G  -
rpool/home@zfs-auto-snap_daily-2013-10-16-0143       14.6M      -  22.4G  -
rpool/home@zfs-auto-snap_daily-2013-10-17-1125       15.1M      -  23.4G  -
rpool/home@zfs-auto-snap_daily-2013-10-18-0127         74K      -  23.7G  -
rpool/home@zfs-auto-snap_weekly-2013-10-18-0147        77K      -  23.7G  -
rpool/home@zfs-auto-snap_daily-2013-10-19-1150       58.8M      -  23.7G  -
rpool/home@zfs-auto-snap_daily-2013-10-20-0126       6.93M      -  24.0G  -
rpool/home@zfs-auto-snap_hourly-2013-10-20-0501      6.91M      -  24.0G  -
rpool/home@zfs-auto-snap_hourly-2013-10-20-1001       164M      -  23.8G  -
rpool/home@zfs-auto-snap_hourly-2013-10-20-1101      9.86M      -  23.7G  -
rpool/home@zfs-auto-snap_hourly-2013-10-20-1201      11.2M      -  23.7G  -
rpool/home@zfs-auto-snap_hourly-2013-10-20-1501      9.40M      -  23.7G  -
rpool/home@zfs-auto-snap_hourly-2013-10-20-1601      9.32M      -  23.7G  -
rpool/home@zfs-auto-snap_hourly-2013-10-20-1701       193M      -  23.9G  -
rpool/home@zfs-auto-snap_hourly-2013-10-20-1801      8.59M      -  23.7G  -
rpool/home@zfs-auto-snap_hourly-2013-10-20-1901      8.30M      -  23.7G  -
rpool/home@zfs-auto-snap_hourly-2013-10-20-2101      6.94M      -  23.7G  -
rpool/home@zfs-auto-snap_hourly-2013-10-20-2201      6.84M      -  23.7G  -
rpool/home@zfs-auto-snap_hourly-2013-10-20-2301      6.83M      -  23.7G  -
rpool/home@zfs-auto-snap_hourly-2013-10-21-0001      6.84M      -  23.7G  -
rpool/home@zfs-auto-snap_hourly-2013-10-21-0101      4.17M      -  23.7G  -
rpool/home@zfs-auto-snap_daily-2013-10-21-0138        478K      -  23.7G  -
rpool/home@zfs-auto-snap_hourly-2013-10-21-0201      3.13M      -  23.7G  -
rpool/home@zfs-auto-snap_hourly-2013-10-21-0301      6.83M      -  23.7G  -
rpool/home@zfs-auto-snap_hourly-2013-10-21-0401      6.84M      -  23.7G  -
rpool/home@zfs-auto-snap_hourly-2013-10-21-0501      6.83M      -  23.7G  -
rpool/home@zfs-auto-snap_hourly-2013-10-21-0601      6.84M      -  23.7G  -
rpool/home@zfs-auto-snap_hourly-2013-10-21-0701      7.33M      -  23.7G  -
rpool/home@zfs-auto-snap_hourly-2013-10-21-1001      18.1M      -  23.7G  -
rpool/home@zfs-auto-snap_hourly-2013-10-21-1101      8.36M      -  23.7G  -
rpool/home@zfs-auto-snap_hourly-2013-10-21-1201          0      -  23.7G  -
rpool/home@zfs-auto-snap_frequent-2013-10-21-1215        0      -  23.7G  -
rpool/home@zfs-auto-snap_frequent-2013-10-21-1230        0      -  23.7G  -
rpool/home@zfs-auto-snap_frequent-2013-10-21-1245    88.5K      -  23.7G  -
rpool/home@zfs-auto-snap_frequent-2013-10-21-1300      73K      -  23.7G  -
rpool/home@zfs-auto-snap_hourly-2013-10-21-1301       140K      -  23.7G  -
rpool/images                                         22.5G   144G  22.5G  /images
rpool/images@zfs-auto-snap_daily-2013-10-05-1808         0      -  22.0G  -
rpool/images@zfs-auto-snap_daily-2013-10-06-0114         0      -  22.0G  -
rpool/images@zfs-auto-snap_daily-2013-10-07-0944         0      -  22.5G  -
rpool/images@zfs-auto-snap_daily-2013-10-08-0111         0      -  22.5G  -
rpool/images@zfs-auto-snap_daily-2013-10-09-1431         0      -  22.5G  -
rpool/images@zfs-auto-snap_daily-2013-10-10-0935         0      -  22.5G  -
rpool/images@zfs-auto-snap_weekly-2013-10-10-0955        0      -  22.5G  -
rpool/images@zfs-auto-snap_daily-2013-10-11-0834         0      -  22.5G  -
rpool/images@zfs-auto-snap_daily-2013-10-12-0144         0      -  22.5G  -
rpool/images@zfs-auto-snap_daily-2013-10-13-0123         0      -  22.5G  -
rpool/images@zfs-auto-snap_daily-2013-10-14-0920         0      -  22.5G  -
rpool/images@zfs-auto-snap_daily-2013-10-15-1019         0      -  22.5G  -
rpool/images@zfs-auto-snap_daily-2013-10-16-0143         0      -  22.5G  -
rpool/images@zfs-auto-snap_daily-2013-10-17-1125         0      -  22.5G  -
rpool/images@zfs-auto-snap_daily-2013-10-18-0127         0      -  22.5G  -
rpool/images@zfs-auto-snap_weekly-2013-10-18-0147        0      -  22.5G  -
rpool/images@zfs-auto-snap_daily-2013-10-19-1150         0      -  22.5G  -
rpool/images@zfs-auto-snap_daily-2013-10-20-0126         0      -  22.5G  -
rpool/images@zfs-auto-snap_hourly-2013-10-20-0501        0      -  22.5G  -
rpool/images@zfs-auto-snap_hourly-2013-10-20-1001        0      -  22.5G  -
rpool/images@zfs-auto-snap_hourly-2013-10-20-1101        0      -  22.5G  -
rpool/images@zfs-auto-snap_hourly-2013-10-20-1201        0      -  22.5G  -
rpool/images@zfs-auto-snap_hourly-2013-10-20-1501        0      -  22.5G  -
rpool/images@zfs-auto-snap_hourly-2013-10-20-1601        0      -  22.5G  -
rpool/images@zfs-auto-snap_hourly-2013-10-20-1701        0      -  22.5G  -
rpool/images@zfs-auto-snap_hourly-2013-10-20-1801        0      -  22.5G  -
rpool/images@zfs-auto-snap_hourly-2013-10-20-1901        0      -  22.5G  -
rpool/images@zfs-auto-snap_hourly-2013-10-20-2101        0      -  22.5G  -
rpool/images@zfs-auto-snap_hourly-2013-10-20-2201        0      -  22.5G  -
rpool/images@zfs-auto-snap_hourly-2013-10-20-2301        0      -  22.5G  -
rpool/images@zfs-auto-snap_hourly-2013-10-21-0001        0      -  22.5G  -
rpool/images@zfs-auto-snap_hourly-2013-10-21-0101        0      -  22.5G  -
rpool/images@zfs-auto-snap_daily-2013-10-21-0138         0      -  22.5G  -
rpool/images@zfs-auto-snap_hourly-2013-10-21-0201        0      -  22.5G  -
rpool/images@zfs-auto-snap_hourly-2013-10-21-0301        0      -  22.5G  -
rpool/images@zfs-auto-snap_hourly-2013-10-21-0401        0      -  22.5G  -
rpool/images@zfs-auto-snap_hourly-2013-10-21-0501        0      -  22.5G  -
rpool/images@zfs-auto-snap_hourly-2013-10-21-0601        0      -  22.5G  -
rpool/images@zfs-auto-snap_hourly-2013-10-21-0701        0      -  22.5G  -
rpool/images@zfs-auto-snap_hourly-2013-10-21-1001        0      -  22.5G  -
rpool/images@zfs-auto-snap_hourly-2013-10-21-1101        0      -  22.5G  -
rpool/images@zfs-auto-snap_hourly-2013-10-21-1201        0      -  22.5G  -
rpool/images@zfs-auto-snap_frequent-2013-10-21-1215      0      -  22.5G  -
rpool/images@zfs-auto-snap_frequent-2013-10-21-1230      0      -  22.5G  -
rpool/images@zfs-auto-snap_frequent-2013-10-21-1245      0      -  22.5G  -
rpool/images@zfs-auto-snap_frequent-2013-10-21-1300      0      -  22.5G  -
rpool/images@zfs-auto-snap_hourly-2013-10-21-1301        0      -  22.5G  -
rpool/root                                            991K   144G   104K  /root
rpool/root@zfs-auto-snap_daily-2013-10-05-1808         30K      -  68.5K  -
rpool/root@zfs-auto-snap_daily-2013-10-06-0114         31K      -  72.5K  -
rpool/root@zfs-auto-snap_daily-2013-10-07-0944         33K      -  74.5K  -
rpool/root@zfs-auto-snap_daily-2013-10-08-0111         30K      -    74K  -
rpool/root@zfs-auto-snap_daily-2013-10-09-1431         30K      -  75.5K  -
rpool/root@zfs-auto-snap_daily-2013-10-10-0935           0      -  74.5K  -
rpool/root@zfs-auto-snap_weekly-2013-10-10-0955          0      -  74.5K  -
rpool/root@zfs-auto-snap_daily-2013-10-11-0834       30.5K      -  75.5K  -
rpool/root@zfs-auto-snap_daily-2013-10-12-0144          1K      -    77K  -
rpool/root@zfs-auto-snap_daily-2013-10-13-0123          1K      -    77K  -
rpool/root@zfs-auto-snap_daily-2013-10-14-0920         35K      -    79K  -
rpool/root@zfs-auto-snap_daily-2013-10-15-1019         34K      -    78K  -
rpool/root@zfs-auto-snap_daily-2013-10-16-0143         53K      -  98.5K  -
rpool/root@zfs-auto-snap_daily-2013-10-17-1125       41.5K      -   104K  -
rpool/root@zfs-auto-snap_daily-2013-10-18-0127           0      -   106K  -
rpool/root@zfs-auto-snap_weekly-2013-10-18-0147          0      -   106K  -
rpool/root@zfs-auto-snap_daily-2013-10-19-1150         35K      -   104K  -
rpool/root@zfs-auto-snap_daily-2013-10-20-0126           0      -   106K  -
rpool/root@zfs-auto-snap_hourly-2013-10-20-0501          0      -   106K  -
rpool/root@zfs-auto-snap_hourly-2013-10-20-1001        35K      -   104K  -
rpool/root@zfs-auto-snap_hourly-2013-10-20-1101          0      -   104K  -
rpool/root@zfs-auto-snap_hourly-2013-10-20-1201          0      -   104K  -
rpool/root@zfs-auto-snap_hourly-2013-10-20-1501          0      -   104K  -
rpool/root@zfs-auto-snap_hourly-2013-10-20-1601          0      -   104K  -
rpool/root@zfs-auto-snap_hourly-2013-10-20-1701          0      -   104K  -
rpool/root@zfs-auto-snap_hourly-2013-10-20-1801          0      -   104K  -
rpool/root@zfs-auto-snap_hourly-2013-10-20-1901          0      -   104K  -
rpool/root@zfs-auto-snap_hourly-2013-10-20-2101          0      -   106K  -
rpool/root@zfs-auto-snap_hourly-2013-10-20-2201          0      -   106K  -
rpool/root@zfs-auto-snap_hourly-2013-10-20-2301          0      -   106K  -
rpool/root@zfs-auto-snap_hourly-2013-10-21-0001          0      -   106K  -
rpool/root@zfs-auto-snap_hourly-2013-10-21-0101          0      -   106K  -
rpool/root@zfs-auto-snap_daily-2013-10-21-0138           0      -   106K  -
rpool/root@zfs-auto-snap_hourly-2013-10-21-0201          0      -   106K  -
rpool/root@zfs-auto-snap_hourly-2013-10-21-0301          0      -   106K  -
rpool/root@zfs-auto-snap_hourly-2013-10-21-0401          0      -   106K  -
rpool/root@zfs-auto-snap_hourly-2013-10-21-0501          0      -   106K  -
rpool/root@zfs-auto-snap_hourly-2013-10-21-0601          0      -   106K  -
rpool/root@zfs-auto-snap_hourly-2013-10-21-0701          0      -   106K  -
rpool/root@zfs-auto-snap_hourly-2013-10-21-1001         1K      -   106K  -
rpool/root@zfs-auto-snap_hourly-2013-10-21-1101      36.5K      -   106K  -
rpool/root@zfs-auto-snap_hourly-2013-10-21-1201          0      -   104K  -
rpool/root@zfs-auto-snap_frequent-2013-10-21-1215        0      -   104K  -
rpool/root@zfs-auto-snap_frequent-2013-10-21-1230        0      -   104K  -
rpool/root@zfs-auto-snap_frequent-2013-10-21-1245        0      -   104K  -
rpool/root@zfs-auto-snap_frequent-2013-10-21-1300        0      -   104K  -
rpool/root@zfs-auto-snap_hourly-2013-10-21-1301      36.5K      -   104K  -
rpool/swap                                           8.50G   152G   264M  -
root@nb0815 ~ # 
</pre>

as soon as I run  <pre>memtester 3000m</pre> my system freezes.
same happens when I just use it normally and some java process happens to eat up most of my memory

**Comment by behlendorf** [comment]
Closing as stale, refer to the [swap section](https://github.com/zfsonlinux/zfs/wiki/FAQ#using-a-zvol-for-a-swap-device) of the wiki for additional configuration information.
