### ISSUE TITLE
nfsd blocked for more than 120 seconds with 0.6.2 on Ubuntu 12.04.3

### ISSUE THREAD

**Issue by jayjaysch** [zfsonlinux/zfs#1804]
I have an Ubuntu 12.04 (3.5.0-23-generic x86_64) server running with zfs 0.62.
Mem: 96G, CPU 2x XEON E5-2650

zpool contains 44x 1T Sata disks, ssd zil (mirror)  and l2arc

Under heavy load the server stops working and leaving the following following messages in the kernel.log:

Oct 14 06:55:51 zfs01 kernel: [2909945.364431] INFO: task nfsd:3108 blocked for more than 120 seconds.
Oct 14 06:55:52 zfs01 kernel: [2909945.364634] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Oct 14 06:55:53 zfs01 kernel: [2909945.364880] nfsd            D ffffffff8180cbe0     0  3108      2 0x00000000
Oct 14 06:55:53 zfs01 kernel: [2909945.364884]  ffff88102538b560 0000000000000046 000000000000222c ffff880ffbf774f0
Oct 14 06:55:53 zfs01 kernel: [2909945.364889]  ffff88102538bfd8 ffff88102538bfd8 ffff88102538bfd8 00000000000139c0
Oct 14 06:55:53 zfs01 kernel: [2909945.364893]  ffff881029792e00 ffff8810097f1700 ffff88102538b570 ffff88046573a210
Oct 14 06:55:53 zfs01 kernel: [2909945.364898] Call Trace:
Oct 14 06:55:53 zfs01 kernel: [2909945.364908]  [<ffffffff8169d8b9>] schedule+0x29/0x70
Oct 14 06:55:53 zfs01 kernel: [2909945.364930]  [<ffffffffa019467d>] cv_wait_common+0xfd/0x1b0 [spl]
Oct 14 06:55:53 zfs01 kernel: [2909945.364934]  [<ffffffff8169c39d>] ? mutex_lock+0x1d/0x50
Oct 14 06:55:53 zfs01 kernel: [2909945.364939]  [<ffffffff81078450>] ? add_wait_queue+0x60/0x60
Oct 14 06:55:53 zfs01 kernel: [2909945.364947]  [<ffffffffa0194785>] __cv_wait+0x15/0x20 [spl]
Oct 14 06:55:53 zfs01 kernel: [2909945.364970]  [<ffffffffa020d64b>] dbuf_read+0x3ab/0x860 [zfs]
Oct 14 06:55:53 zfs01 kernel: [2909945.364988]  [<ffffffffa0220f33>] dmu_tx_check_ioerr+0xc3/0x140 [zfs]
Oct 14 06:55:53 zfs01 kernel: [2909945.365005]  [<ffffffffa02213df>] dmu_tx_count_write+0x42f/0x6d0 [zfs]
Oct 14 06:55:53 zfs01 kernel: [2909945.365011]  [<ffffffffa018924e>] ? kmem_alloc_debug+0x8e/0x3b0 [spl]
Oct 14 06:55:53 zfs01 kernel: [2909945.365017]  [<ffffffffa018924e>] ? kmem_alloc_debug+0x8e/0x3b0 [spl]
Oct 14 06:55:53 zfs01 kernel: [2909945.365022]  [<ffffffffa018924e>] ? kmem_alloc_debug+0x8e/0x3b0 [spl]
Oct 14 06:55:53 zfs01 kernel: [2909945.365039]  [<ffffffffa02216c4>] dmu_tx_hold_write+0x44/0x60 [zfs]
Oct 14 06:55:53 zfs01 kernel: [2909945.365063]  [<ffffffffa02980a6>] zfs_write+0x346/0xc50 [zfs]
Oct 14 06:55:53 zfs01 kernel: [2909945.365066]  [<ffffffff8169c39d>] ? mutex_lock+0x1d/0x50
Oct 14 06:55:53 zfs01 kernel: [2909945.365083]  [<ffffffffa0225174>] ? dnode_rele+0x54/0x90 [zfs]
Oct 14 06:55:53 zfs01 kernel: [2909945.365087]  [<ffffffff8169e7de>] ? _raw_spin_lock+0xe/0x20
Oct 14 06:55:53 zfs01 kernel: [2909945.365109]  [<ffffffffa02aca72>] zpl_write_common+0x52/0x80 [zfs]
Oct 14 06:55:53 zfs01 kernel: [2909945.365129]  [<ffffffffa02acb08>] zpl_write+0x68/0xa0 [zfs]
Oct 14 06:55:53 zfs01 kernel: [2909945.365137]  [<ffffffffa0195c20>] ? tsd_exit+0x2a0/0x2d0 [spl]
Oct 14 06:55:53 zfs01 kernel: [2909945.365156]  [<ffffffffa02acaa0>] ? zpl_write_common+0x80/0x80 [zfs]
Oct 14 06:55:53 zfs01 kernel: [2909945.365160]  [<ffffffff81188179>] do_loop_readv_writev+0x59/0x90
Oct 14 06:55:53 zfs01 kernel: [2909945.365163]  [<ffffffff8118848e>] do_readv_writev+0x1ae/0x1d0
Oct 14 06:55:53 zfs01 kernel: [2909945.365182]  [<ffffffffa02ac5b0>] ? zpl_release+0x80/0x80 [zfs]
Oct 14 06:55:53 zfs01 kernel: [2909945.365184]  [<ffffffff811855e7>] ? do_dentry_open+0x257/0x2b0
Oct 14 06:55:53 zfs01 kernel: [2909945.365188]  [<ffffffff8108052a>] ? lg_local_unlock+0x1a/0x20
Oct 14 06:55:53 zfs01 kernel: [2909945.365190]  [<ffffffff811a6556>] ? mntput_no_expire+0x46/0x160
Oct 14 06:55:53 zfs01 kernel: [2909945.365193]  [<ffffffff811884ec>] vfs_writev+0x3c/0x50
Oct 14 06:55:53 zfs01 kernel: [2909945.365202]  [<ffffffffa03ef659>] nfsd_vfs_write.isra.13+0xe9/0x2d0 [nfsd]
Oct 14 06:55:53 zfs01 kernel: [2909945.365208]  [<ffffffffa03f1ce8>] nfsd_write+0xf8/0x110 [nfsd]
Oct 14 06:55:53 zfs01 kernel: [2909945.365214]  [<ffffffffa03f8f6f>] nfsd3_proc_write+0x9f/0xe0 [nfsd]
Oct 14 06:55:53 zfs01 kernel: [2909945.365220]  [<ffffffffa03ebb1e>] nfsd_dispatch+0xbe/0x1c0 [nfsd]
Oct 14 06:55:53 zfs01 kernel: [2909945.365234]  [<ffffffffa036d358>] svc_process_common+0x328/0x5e0 [sunrpc]
Oct 14 06:55:53 zfs01 kernel: [2909945.365238]  [<ffffffff8108a360>] ? try_to_wake_up+0x200/0x200
Oct 14 06:55:53 zfs01 kernel: [2909945.365246]  [<ffffffffa036d716>] svc_process+0x106/0x160 [sunrpc]
Oct 14 06:55:53 zfs01 kernel: [2909945.365251]  [<ffffffffa03eb285>] nfsd+0xb5/0x1a0 [nfsd]
Oct 14 06:55:53 zfs01 kernel: [2909945.365255]  [<ffffffffa03eb1d0>] ? nfsd_last_thread+0x70/0x70 [nfsd]
Oct 14 06:55:53 zfs01 kernel: [2909945.365258]  [<ffffffff81077b73>] kthread+0x93/0xa0
Oct 14 06:55:53 zfs01 kernel: [2909945.365261]  [<ffffffff816a8324>] kernel_thread_helper+0x4/0x10
Oct 14 06:55:53 zfs01 kernel: [2909945.365264]  [<ffffffff81077ae0>] ? flush_kthread_worker+0xb0/0xb0
Oct 14 06:55:53 zfs01 kernel: [2909945.365266]  [<ffffffff816a8320>] ? gs_change+0x13/0x13

zpool status
  pool: pool0
 state: ONLINE
  scan: none requested
config:

        NAME                                               STATE     READ WRITE CKSUM
        pool0                                              ONLINE       0     0     0
          raidz1-0                                         ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023015703-lun-1   ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023015703-lun-2   ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023015703-lun-3   ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023015703-lun-4   ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023015703-lun-5   ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023015703-lun-6   ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023015703-lun-7   ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023015703-lun-8   ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023015703-lun-9   ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023015703-lun-10  ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023015703-lun-11  ONLINE       0     0     0
          raidz1-1                                         ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023015703-lun-12  ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023015703-lun-13  ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023015703-lun-14  ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023015703-lun-15  ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023015703-lun-16  ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023015703-lun-17  ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023015703-lun-18  ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023015703-lun-19  ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023015703-lun-20  ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023015703-lun-22  ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023015703-lun-23  ONLINE       0     0     0
          raidz1-2                                         ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023019f36-lun-1   ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023019f36-lun-2   ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023019f36-lun-3   ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023019f36-lun-4   ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023019f36-lun-5   ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023019f36-lun-6   ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023019f36-lun-7   ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023019f36-lun-8   ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023019f36-lun-9   ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023019f36-lun-10  ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023019f36-lun-11  ONLINE       0     0     0
          raidz1-3                                         ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023019f36-lun-12  ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023019f36-lun-13  ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023019f36-lun-14  ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023019f36-lun-15  ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023019f36-lun-16  ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023019f36-lun-17  ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023019f36-lun-18  ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023019f36-lun-19  ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023019f36-lun-21  ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023019f36-lun-22  ONLINE       0     0     0
            pci-0000:06:00.0-fc-0x210000d023019f36-lun-23  ONLINE       0     0     0
        logs
          mirror-4                                         ONLINE       0     0     0
            pci-0000:04:00.0-sas-0x4433221106000000-lun-0  ONLINE       0     0     0
            pci-0000:04:00.0-sas-0x4433221107000000-lun-0  ONLINE       0     0     0
        cache
          pci-0000:04:00.0-sas-0x4433221105000000-lun-0    ONLINE       0     0     0
        spares
          pci-0000:06:00.0-fc-0x210000d023015703-lun-21    AVAIL
          pci-0000:06:00.0-fc-0x210000d023015703-lun-0     AVAIL
          pci-0000:06:00.0-fc-0x210000d023019f36-lun-0     AVAIL

**Comment by behlendorf** [comment]
Closing as stale, resolved in 0.6.5.x.
