### ISSUE TITLE
soft lockup

### ISSUE THREAD

**Issue by tcf909** [zfsonlinux/zfs#1806]
I'm seeing consistent soft lockups issuing zpool commands after boot:

Stack:
Centos 6.4
Kernel 3.11 (No preempt - some scst patches)
zfs/spl 0.6.2
2 zpools (1 -  iscsi devices in various vdevs)

(fresh reboot)

**Comment by behlendorf** [comment]
Closing as stale.  There have been no reports of this for over a year.
