### ISSUE TITLE
Metadata not getting evicted from ARC

### ISSUE THREAD

**Issue by Hydrar** [zfsonlinux/zfs#1871]
My zfs system has after 17 days uptime managed to use more metadata space in ARC than arc_meta_limit, while simultaneously also going above the ARC max 
echoing 3 to drop_caches does nothing, it only seemed to jump up and down ~60MB in metadatasize but never change from that. System crashed last night from OOM
arcstats: http://bpaste.net/show/149591/
kmem/slab: http://bpaste.net/show/149597/

Kernel 3.10.17-gentoo
ZoL ebuild 0.6.2-r2

**Comment by behlendorf** [comment]
Closing as out of date.  Much as changed in the ARC since late 2013.
