### ISSUE TITLE
Destroy Zpool Failed On SPARC64

### ISSUE THREAD

**Issue by cloud4life** [zfsonlinux/zfs#1879]
When Destory it . Failed !!!
<pre><code>
Message from syslogd@localhost at Nov 17 21:22:23 ...
 kernel:[ 2323.364763] SPLError: 4668:0:(metaslab.c:129:metaslab_class_destroy()) ASSERTION(mc->mc_space == 0) failed

Message from syslogd@localhost at Nov 17 21:22:23 ...
 kernel:[ 2323.412622] SPLError: 4668:0:(metaslab.c:129:metaslab_class_destroy()) SPL PANIC
</code></pre>

dmesg is 
<pre><code>
[ 2323.364763] SPLError: 4668:0:(metaslab.c:129:metaslab_class_destroy()) ASSERTION(mc->mc_space == 0) failed
[ 2323.412622] SPLError: 4668:0:(metaslab.c:129:metaslab_class_destroy()) SPL PANIC
[ 2323.437957] SPL: Showing stack for process 4668
[ 2323.437982] Call Trace:
[ 2323.438997]  [00000000101e51c0] metaslab_class_destroy+0x13c/0x210 [zfs]
[ 2323.439574]  [00000000101f0784] spa_deactivate+0x480/0x740 [zfs]
[ 2323.440152]  [00000000101f7714] spa_export_common+0x338/0x3f0 [zfs]
[ 2323.440765]  [000000001023b000] zfs_ioc_pool_destroy+0xc/0x34 [zfs]
[ 2323.441351]  [000000001023b39c] zfsdev_ioctl+0x140/0x1c8 [zfs]
[ 2323.441387]  [00000000004f92cc] vfs_ioctl+0x20/0x88
[ 2323.441409]  [00000000004f9900] do_vfs_ioctl+0x52c/0x57c
[ 2323.441432]  [00000000004f9978] SyS_ioctl+0x28/0x50
[ 2323.441467]  [0000000000406254] linux_sparc_syscall+0x34/0x44
</code></pre>

step  1
<code># zpool create tank /dev/sdb</code>
step 2
<code># zfs create tank/data</code>
step 3
<code># cd /tank/data</code>
step 4
<code># dd if=/dev/zero of=DATA count=100M bs=10</code>
step 5
<code># Ctrl + C </code>
step 6
<code>#  zpool destroy tank</code>

And Failed.

**Comment by behlendorf** [comment]
Closing as stale.  I'm unable to reproduce this in master with the provided reproducer.
