### ISSUE TITLE
zfs send should have an option not to abort on read errors

### ISSUE THREAD

**Issue by dechamps** [zfsonlinux/zfs#1897]
Consider the following scenario (which actually happened in my case):

- You notice that your disks are on the verge of failing and the pool is already showing some (isolated) read/checksum errors.
- You want to get the data out of there ASAP using `zfs send` to secure the data before the pool experiences catastrophic failures.

Problem is, `zfs send` considers read errors as fatal, which makes it useless for this scenario.

Steps to reproduce:

    # dd if=/dev/zero of=/tmp/testpool bs=1 count=1 seek=128M
    # zpool create testpool /tmp/testpool
    # dd if=/dev/zero of=/testpool/foo bs=1M count=90
    # zpool export testpool
    # dd if=/dev/urandom of=/tmp/testpool bs=1M count=1 seek=16 conv=notrunc
    # zpool import -d /tmp testpool
    # zfs snapshot testpool@snap
    # zfs send -v testpool@snap >/dev/null
    send from @ to testpool@snap estimated size is 90.2M
    total estimated size is 90.2M
    TIME        SENT   SNAPSHOT
    warning: cannot send 'testpool@snap': Input/output error

Ideally, `zfs send` should have a command-line option to run it in "I don't care about read errors, just salvage what you can" mode.

**Comment by ilovezfs** [comment]
@behlendorf Can this issue be closed?

**Comment by behlendorf** [comment]
@ilovezfs ideally we wanted to add a command line option for this functionality.  But since I doubt someone will get to that any time soon and we have a workable module option I think we can close this.  If someone wants to revive this we can absolutely file a new issue or reopen this one.

**Comment by ilovezfs** [comment]
@behlendorf Thanks for clarifying. @lundman and I were debating whether the fact that this was still open was implying a desire for a CLI option or not.

**Comment by jimsalterjrs** [comment]
I would certainly like a CLI option. Or just feedback from a failed ZFS 
send pointing the admin to the /proc workaround would be fine.  I'm a 
little worried that the /proc workaround is obscure enough to end up 
buried and difficult to find when you need it.

**Comment by mailinglists35** [comment]
Hi,

I just hit this. The problem with the module parameter is that is disabled by default so to enable it you would have to export all live pools in order remove the modules and reload the modules, which implies unnecesary downtime.

Is it still challenging today to make it a zfs send option?

**Comment by richardelling** [comment]
> you would have to export all live pools in order remove the modules and reload the modules

According to the docs, this tunable is dynamic and does not require re-importing pools.
https://github.com/zfsonlinux/zfs/wiki/ZFS-on-Linux-Module-Parameters#zfs_send_corrupt_data

**Comment by mailinglists35** [comment]
that's correct, thank you! I assumed it's a read-only parameter.
however I think it still should be useful for `zfs send` to reference at least this issue or a short message about `zfs_send_corrupt_data` when it encounters the errors.
