### ISSUE TITLE
zfs inherit for exec property - different behavior

### ISSUE THREAD

**Issue by kolczykm** [zfsonlinux/zfs#1908]
I have observed different behavior for zfs inherit command for exec property of dataset. First I will explain what it works for me in case of other properties, for example compression property:

```
zfs get compression
NAME                     PROPERTY     VALUE     SOURCE
Zpool1                   compression  off       default
Zpool1/dataset1          compression  off       default

zfs set compression=lz4 Zpool1/dataset1
zfs get compression
NAME                     PROPERTY     VALUE     SOURCE
Zpool1                   compression  off       default
Zpool1/dataset1          compression  lz4       local

zfs inherit compression Zpool1/dataset1

zfs get compression
NAME                     PROPERTY     VALUE     SOURCE
Zpool1                   compression  off       default
Zpool1/dataset1          compression  off       default

```

What I have showed for compression property and inherit command is that it works as I expected. But when I try the same thing with exec property it works the following way:

```
zfs set exec=off Zpool1/dataset1
zfs get exec
NAME                     PROPERTY  VALUE  SOURCE
Zpool1                   exec      on     default
Zpool1/dataset1          exec      off    local

zfs inherit exec Zpool1/dataset1

zfs get exec
NAME                     PROPERTY  VALUE  SOURCE
Zpool1                   exec      on     default
Zpool1/dataset1          exec      off    temporary

```
exec property after inherit doesn't reverted to on and source is set to temporary. This is different from what happens with for example compression property. Now when I unmount and mount again dataset exec property will switch back to on and source will be shown as default. My question is why behavior of zfs inherit command with exec property is different from other properties? Why dataset need to be remounted in case of exec property to inherit command take effect? I just add that I have also tried -r and -S switches but in case of exec property there were no difference.

**Comment by behlendorf** [comment]
This should now by resolved by temporary mount options which were implemented in 0282c4137e7409e6d85289f4955adf07fac834f5
