### ISSUE TITLE
list a zfs directory hang

### ISSUE THREAD

**Issue by lidaof** [zfsonlinux/zfs#1930]
Hi All,

I recently did an system upgrade and seems got some problem with my system
I was not able to list some of the directory, and there are lots of errors in syslog shown below.

I am using Ubuntu 12.04.3 LTS. Any one have some suggestions to fix it?
Please let me know if you need more information. Many thanks.

Dec  5 09:27:16 corona kernel: [  956.594281] VERIFY(BSWAP_32(sa_hdr_phys->sa_magic) == SA_MAGIC) failed
Dec  5 09:27:16 corona kernel: [  956.594720] SPLError: 3729:0:(sa.c:1303:sa_build_index()) SPL PANIC
Dec  5 09:27:16 corona kernel: [  956.595076] SPL: Showing stack for process 3729
Dec  5 09:27:16 corona kernel: [  956.595081] Pid: 3729, comm: ls Tainted: P           O 3.2.0-23-generic #36-Ubuntu
Dec  5 09:27:16 corona kernel: [  956.595083] Call Trace:
Dec  5 09:27:16 corona kernel: [  956.595103]  [<ffffffffa01344d7>] spl_debug_dumpstack+0x27/0x40 [spl]
Dec  5 09:27:16 corona kernel: [  956.595111]  [<ffffffffa01357c2>] spl_debug_bug+0x82/0xe0 [spl]
Dec  5 09:27:16 corona kernel: [  956.595153]  [<ffffffffa0217ffe>] sa_build_index+0x10e/0x110 [zfs]
Dec  5 09:27:16 corona kernel: [  956.595187]  [<ffffffffa021973a>] sa_handle_get_from_db+0xda/0x120 [zfs]
Dec  5 09:27:16 corona kernel: [  956.595224]  [<ffffffffa02683bf>] zfs_znode_sa_init.isra.7+0x9f/0xd0 [zfs]
Dec  5 09:27:16 corona kernel: [  956.595260]  [<ffffffffa0268c8c>] zfs_znode_alloc+0xdc/0x540 [zfs]
Dec  5 09:27:16 corona kernel: [  956.595296]  [<ffffffffa0273f9d>] ? zio_wait+0x12d/0x1c0 [zfs]
Dec  5 09:27:16 corona kernel: [  956.595317]  [<ffffffffa01da5d7>] ? dbuf_read+0x337/0x860 [zfs]
Dec  5 09:27:16 corona kernel: [  956.595337]  [<ffffffffa01d92d5>] ? dbuf_create+0x325/0x370 [zfs]
Dec  5 09:27:16 corona kernel: [  956.595345]  [<ffffffff8165af6d>] ? mutex_lock+0x1d/0x50
Dec  5 09:27:16 corona kernel: [  956.595352]  [<ffffffff8103dbb9>] ? default_spin_lock_flags+0x9/0x10
Dec  5 09:27:16 corona kernel: [  956.595375]  [<ffffffffa01e1904>] ? dmu_object_info_from_dnode+0x144/0x1b0 [zfs]
Dec  5 09:27:16 corona kernel: [  956.595411]  [<ffffffffa026b238>] zfs_zget+0x168/0x200 [zfs]
Dec  5 09:27:16 corona kernel: [  956.595447]  [<ffffffffa02434a1>] ? zap_lookup_norm+0xd1/0x1c0 [zfs]
Dec  5 09:27:16 corona kernel: [  956.595482]  [<ffffffffa024a653>] zfs_dirent_lock+0x4c3/0x5d0 [zfs]
Dec  5 09:27:16 corona kernel: [  956.595518]  [<ffffffffa024a7eb>] zfs_dirlook+0x8b/0x300 [zfs]
Dec  5 09:27:16 corona kernel: [  956.595554]  [<ffffffffa024734d>] ? zfs_zaccess+0x9d/0x430 [zfs]
Dec  5 09:27:16 corona kernel: [  956.595565]  [<ffffffffa0145e00>] ? tsd_exit+0x2a0/0x2d0 [spl]
Dec  5 09:27:16 corona kernel: [  956.595601]  [<ffffffffa0264261>] zfs_lookup+0x2e1/0x330 [zfs]
Dec  5 09:27:16 corona kernel: [  956.595636]  [<ffffffffa0279ed8>] zpl_lookup+0x78/0xf0 [zfs]
Dec  5 09:27:16 corona kernel: [  956.595641]  [<ffffffff8165c46e>] ? _raw_spin_lock+0xe/0x20
Dec  5 09:27:16 corona kernel: [  956.595646]  [<ffffffff811827e5>] d_alloc_and_lookup+0x45/0x90
Dec  5 09:27:16 corona kernel: [  956.595653]  [<ffffffff8118ff25>] ? d_lookup+0x35/0x60
Dec  5 09:27:16 corona kernel: [  956.595657]  [<ffffffff81184972>] do_lookup+0x202/0x310
Dec  5 09:27:16 corona kernel: [  956.595661]  [<ffffffff8118eea6>] ? dput+0x1e6/0x290
Dec  5 09:27:16 corona kernel: [  956.595665]  [<ffffffff811866ac>] path_lookupat+0x11c/0x750
Dec  5 09:27:16 corona kernel: [  956.595673]  [<ffffffff81318c77>] ? __strncpy_from_user+0x27/0x60
Dec  5 09:27:16 corona kernel: [  956.595677]  [<ffffffff81186d11>] do_path_lookup+0x31/0xc0
Dec  5 09:27:16 corona kernel: [  956.595681]  [<ffffffff81187819>] user_path_at_empty+0x59/0xa0
Dec  5 09:27:16 corona kernel: [  956.595717]  [<ffffffffa0261f29>] ? zfs_getattr_fast+0xd9/0x160 [zfs]
Dec  5 09:27:16 corona kernel: [  956.595721]  [<ffffffff8165c46e>] ? _raw_spin_lock+0xe/0x20
Dec  5 09:27:16 corona kernel: [  956.595728]  [<ffffffff8117c6b8>] ? cp_new_stat+0xf8/0x110
Dec  5 09:27:16 corona kernel: [  956.595732]  [<ffffffff81187871>] user_path_at+0x11/0x20
Dec  5 09:27:16 corona kernel: [  956.595736]  [<ffffffff8117c8da>] vfs_fstatat+0x3a/0x70
Dec  5 09:27:16 corona kernel: [  956.595740]  [<ffffffff8117c92e>] vfs_lstat+0x1e/0x20
Dec  5 09:27:16 corona kernel: [  956.595744]  [<ffffffff8117caca>] sys_newlstat+0x1a/0x40
Dec  5 09:27:16 corona kernel: [  956.595750]  [<ffffffff81664a82>] system_call_fastpath+0x16/0x1b

**Comment by behlendorf** [comment]
There have been several fixes applied to master regarding corrupted SA which could have caused this issue.  Since those problems have been resolved I'm closing this issue.
