### ISSUE TITLE
Heavy lock contention in zfs_zinactive causing ARC metadata to grow

### ISSUE THREAD

**Issue by DeHackEd** [zfsonlinux/zfs#1932]
This is just mostly throwing fuel on the fire that is the ARC meta limit growing without bounds problem.

Kernel thread `arc_adapt` appears to be single-handedly responsible for pruning the metadata buffer, but it's very possible for it to get stuck doing mutex waiting. The following stack trace came from an otherwise fully working system while it overran its `zfs_arc_meta_limit`.

<pre>arc_adapt       D 0000000000000000     0  3386      2 0x00000000
 ffff880412983b00 0000000000000046 ffffffffa01a7bb0 ffff880412982010
 ffff88041845b9f0 0000000000010a40 ffff880412983fd8 0000000000004000
 ffff880412983fd8 0000000000010a40 ffff8804184599c0 ffff88041845b9f0
Call Trace:
 [&lt;ffffffffa00eec10&gt;] ? arc_buf_eviction_needed+0x5f/0x69 [zfs]
 [&lt;ffffffffa00f71a4&gt;] ? dbuf_rele_and_unlock+0x19d/0x1a2 [zfs]
 [&lt;ffffffffa00f74d6&gt;] ? dmu_buf_rele+0x25/0x2c [zfs]
 [&lt;ffffffff8130ef22&gt;] schedule+0x5f/0x61
 [&lt;ffffffff8130f15c&gt;] schedule_preempt_disabled+0x9/0xb
 [&lt;ffffffff8130d9d8&gt;] __mutex_lock_slowpath+0xde/0x123
 [&lt;ffffffff8109836b&gt;] ? unmap_mapping_range+0x15d/0x16e
 [&lt;ffffffff8130d872&gt;] mutex_lock+0x16/0x27
 [&lt;ffffffffa016d8d0&gt;] zfs_zinactive+0x67/0xd6 [zfs]
 [&lt;ffffffffa0166078&gt;] zfs_inactive+0x112/0x1ac [zfs]
 [&lt;ffffffff81087c2b&gt;] ? truncate_pagecache+0x51/0x59
 [&lt;ffffffffa017c95a&gt;] zpl_evict_inode+0x23/0x27 [zfs]
 [&lt;ffffffff810d1428&gt;] evict+0xa2/0x155
 [&lt;ffffffff810d1985&gt;] dispose_list+0x3d/0x4a
 [&lt;ffffffff810d1c5b&gt;] prune_icache_sb+0x2c9/0x2d8
 [&lt;ffffffff810bfb43&gt;] prune_super+0xe3/0x158
 [&lt;ffffffffa01630aa&gt;] zfs_sb_prune+0x76/0x9b [zfs]
 [&lt;ffffffffa017ca1b&gt;] ? zpl_prune_sbs+0x37/0x37 [zfs]
 [&lt;ffffffffa017ca36&gt;] zpl_prune_sb+0x1b/0x1d [zfs]
 [&lt;ffffffff810bf162&gt;] iterate_supers_type+0x43/0xbf
 [&lt;ffffffffa017c9e4&gt;] ? zpl_inode_alloc+0x70/0x70 [zfs]
 [&lt;ffffffffa017ca14&gt;] zpl_prune_sbs+0x30/0x37 [zfs]
 [&lt;ffffffffa004d793&gt;] ? __thread_create+0x2e3/0x2e3 [spl]
 [&lt;ffffffffa00f30c7&gt;] arc_adjust_meta+0x136/0x195 [zfs]
 [&lt;ffffffffa00f3126&gt;] ? arc_adjust_meta+0x195/0x195 [zfs]
 [&lt;ffffffffa00f3126&gt;] ? arc_adjust_meta+0x195/0x195 [zfs]
 [&lt;ffffffffa004d793&gt;] ? __thread_create+0x2e3/0x2e3 [spl]
 [&lt;ffffffffa00f317d&gt;] arc_adapt_thread+0x57/0x138 [zfs]
 [&lt;ffffffffa004d7ff&gt;] thread_generic_wrapper+0x6c/0x79 [spl]
 [&lt;ffffffffa004d793&gt;] ? __thread_create+0x2e3/0x2e3 [spl]
 [&lt;ffffffff8103e6fa&gt;] kthread+0x84/0x8c
 [&lt;ffffffff813112d4&gt;] kernel_thread_helper+0x4/0x10
 [&lt;ffffffff8103e676&gt;] ? kthread_freezable_should_stop+0x58/0x58
 [&lt;ffffffff813112d0&gt;] ? gs_change+0xb/0xb
</pre>

During this time the arcstat `arc_prune` would stop counting. I'm not sure if it's one lock being held for a long time or many locks `arc_prune` is slowly trudging through. On my system I find `arc_adapt` making very slow progress and not completely frozen up - maybe one count of `arc_prune` per 5 or 10 seconds.

By executing `killall -STOP` on the jobs doing I/O `arc_adapt` would unwedge and be able to prune the cache fairly quickly. Collecting stack traces multiple times between pausing/restarting the disk jobs gives the same backtraces.

ryao suggested I apply pull request #1696 as a possible solution - early impressions are good.

Other issues (eg: #1224) have similar stack traces. Once the metadata buffer fills too much the system may reach a state of real deadlock. ZFS is the first to go but general memory allcoations across all of Linux may seize as well.

**Comment by DeHackEd** [comment]
I believe this was fixed by 2cbb06b561f500732de2214eb590149d0c4f3cf5 which means this can be closed. Yes?

**Comment by behlendorf** [comment]
Yes, you're right.  Closing.
