### ISSUE TITLE
Large File Delete Timeout

### ISSUE THREAD

**Issue by tcf909** [zfsonlinux/zfs#1939]
Latest ZoL head. Have a filesystem exported via nfs. Single VMDK in the filesystem. Deleted the VMDK from vcenter and the delete of the actual file blocked the nfsd from responding to vcenter. Share shows as offline.

Failed at the guest level and /var/log/messages shows:

txg_sync is busy doing something (going on 10 minutes)

Dec  7 12:55:22 storage1 kernel: INFO: task nfsd:20576 blocked for more than 120 seconds.
Dec  7 12:55:22 storage1 kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Dec  7 12:55:22 storage1 kernel: nfsd            D 0000000000000000     0 20576      2 0x00000080
Dec  7 12:55:22 storage1 kernel: ffff88050b513c58 0000000000000046 ffff88050b513fd8 0000000000013fc0
Dec  7 12:55:22 storage1 kernel: ffff88050b512010 0000000000013fc0 0000000000013fc0 0000000000013fc0
Dec  7 12:55:22 storage1 kernel: ffff88050b513fd8 0000000000013fc0 ffff8807c294a300 ffff8802a06b0100
Dec  7 12:55:22 storage1 kernel: Call Trace:
Dec  7 12:55:22 storage1 kernel: [<ffffffff81591d79>] schedule+0x29/0x70
Dec  7 12:55:22 storage1 kernel: [<ffffffff8159206e>] schedule_preempt_disabled+0xe/0x10
Dec  7 12:55:22 storage1 kernel: [<ffffffff815906a7>] __mutex_lock_slowpath+0x177/0x220
Dec  7 12:55:22 storage1 kernel: [<ffffffff8119b0d8>] ? inode_permission+0x18/0x50
Dec  7 12:55:22 storage1 kernel: [<ffffffff8159050b>] mutex_lock+0x2b/0x50
Dec  7 12:55:22 storage1 kernel: [<ffffffffa09eb074>] nfsd_unlink+0xc4/0x220 [nfsd]
Dec  7 12:55:22 storage1 kernel: [<ffffffffa09f1783>] nfsd3_proc_remove+0x83/0x120 [nfsd]
Dec  7 12:55:22 storage1 kernel: [<ffffffffa09e329b>] nfsd_dispatch+0xeb/0x230 [nfsd]
Dec  7 12:55:22 storage1 kernel: [<ffffffffa0889cb4>] svc_process_common+0x344/0x640 [sunrpc]
Dec  7 12:55:22 storage1 kernel: [<ffffffffa09e3940>] ? nfsd_pool_stats_release+0x50/0x50 [nfsd]
Dec  7 12:55:22 storage1 kernel: [<ffffffffa088a2ef>] svc_process+0xff/0x150 [sunrpc]
Dec  7 12:55:22 storage1 kernel: [<ffffffffa09e39ff>] nfsd+0xbf/0x130 [nfsd]
Dec  7 12:55:22 storage1 kernel: [<ffffffffa09e3940>] ? nfsd_pool_stats_release+0x50/0x50 [nfsd]
Dec  7 12:55:22 storage1 kernel: [<ffffffff81082a6e>] kthread+0xce/0xe0
Dec  7 12:55:22 storage1 kernel: [<ffffffff810829a0>] ? kthread_freezable_should_stop+0x70/0x70
Dec  7 12:55:22 storage1 kernel: [<ffffffff8159b7ac>] ret_from_fork+0x7c/0xb0
Dec  7 12:55:22 storage1 kernel: [<ffffffff810829a0>] ? kthread_freezable_should_stop+0x70/0x70
Dec  7 12:55:22 storage1 kernel: INFO: task nfsd:20578 blocked for more than 120 seconds.
Dec  7 12:55:22 storage1 kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Dec  7 12:55:22 storage1 kernel: nfsd            D ffffffff815b6c00     0 20578      2 0x00000080
Dec  7 12:55:22 storage1 kernel: ffff880822eefc58 0000000000000046 ffff880822eeffd8 0000000000013fc0
Dec  7 12:55:22 storage1 kernel: ffff880822eee010 0000000000013fc0 0000000000013fc0 0000000000013fc0
Dec  7 12:55:22 storage1 kernel: ffff880822eeffd8 0000000000013fc0 ffffffff818ac420 ffff88050970c180
Dec  7 12:55:22 storage1 kernel: Call Trace:
Dec  7 12:55:22 storage1 kernel: [<ffffffff81591d79>] schedule+0x29/0x70
Dec  7 12:55:22 storage1 kernel: [<ffffffff8159206e>] schedule_preempt_disabled+0xe/0x10
Dec  7 12:55:22 storage1 kernel: [<ffffffff815906a7>] __mutex_lock_slowpath+0x177/0x220
Dec  7 12:55:22 storage1 kernel: [<ffffffff8119b0d8>] ? inode_permission+0x18/0x50
Dec  7 12:55:22 storage1 kernel: [<ffffffff8159050b>] mutex_lock+0x2b/0x50
Dec  7 12:55:22 storage1 kernel: [<ffffffffa09eb074>] nfsd_unlink+0xc4/0x220 [nfsd]
Dec  7 12:55:22 storage1 kernel: [<ffffffffa09f1783>] nfsd3_proc_remove+0x83/0x120 [nfsd]
Dec  7 12:55:22 storage1 kernel: [<ffffffffa09e329b>] nfsd_dispatch+0xeb/0x230 [nfsd]
Dec  7 12:55:22 storage1 kernel: [<ffffffffa0889cb4>] svc_process_common+0x344/0x640 [sunrpc]
Dec  7 12:55:22 storage1 kernel: [<ffffffffa09e3940>] ? nfsd_pool_stats_release+0x50/0x50 [nfsd]
Dec  7 12:55:22 storage1 kernel: [<ffffffffa088a2ef>] svc_process+0xff/0x150 [sunrpc]
Dec  7 12:55:22 storage1 kernel: [<ffffffffa09e39ff>] nfsd+0xbf/0x130 [nfsd]
Dec  7 12:55:22 storage1 kernel: [<ffffffffa09e3940>] ? nfsd_pool_stats_release+0x50/0x50 [nfsd]
Dec  7 12:55:22 storage1 kernel: [<ffffffff81082a6e>] kthread+0xce/0xe0
Dec  7 12:55:22 storage1 kernel: [<ffffffff810829a0>] ? kthread_freezable_should_stop+0x70/0x70
Dec  7 12:55:22 storage1 kernel: [<ffffffff8159b7ac>] ret_from_fork+0x7c/0xb0
Dec  7 12:55:22 storage1 kernel: [<ffffffff810829a0>] ? kthread_freezable_should_stop+0x70/0x70

**Comment by alek-p** [comment]
Looks like this issue is addressed w/ a patch that's waiting on code reviews here https://reviews.csiden.org/r/218/

**Comment by behlendorf** [comment]
Resolved by 4bda3bd0e72d582a785b6552ce16b99e04414fbe in master.
