### ISSUE TITLE
Criteria for `arc_warm` may be incorrect

### ISSUE THREAD

**Issue by prakashsurya** [zfsonlinux/zfs#1966]
Looking at the code, I have a feeling the criteria for which `arc_warm` is based on is incorrect. It appears as though it transitions from `B_FALSE` to `B_TRUE` only when the ARC's shrinker is called:

```
2538 static int                                                                      
2539 __arc_shrinker_func(struct shrinker *shrink, struct shrink_control *sc)         
2540 {                                                                               
2541         uint64_t pages;                                                         
2542                                                                                 
2543         /* The arc is considered warm once reclaim has occurred */              
2544         if (unlikely(arc_warm == B_FALSE))                                      
2545                 arc_warm = B_TRUE;
```

Thus, if the ARC is sized such that the kernel never calls the shrinker, `arc_warm` will never become `B_TRUE`; even if the ARC is completely full of data. I'm worried about the performance implications this might have on the L2ARC.

**Comment by behlendorf** [comment]
Closing.  This code has been brought back inline with the exception of the `__arc_shrinker_func()` which will also set arc_warm = B_TRUE.
