### ISSUE TITLE
Hang during import after power outage while scrubbing pool

### ISSUE THREAD

**Issue by kpande** [zfsonlinux/zfs#2018]
ZFS is not allowing me to run 'zpool list' after forcibly rebooting a server while it was scrubbing a pool. I was running patch #1967+1994 but reverted to latest HEAD and re-attempted just in case they caused an error:
[  238.393485] lp: driver loaded but no devices found
[  238.427083] ppdev: user-space parallel port driver
[  240.305591] Ebtables v2.0 registered
[  240.472947] ip_tables: (C) 2000-2006 Netfilter Core Team
[  240.558472] ip6_tables: (C) 2000-2006 Netfilter Core Team
[  240.927385] INFO: task l2arc_feed:1236 blocked for more than 120 seconds.
[  240.930534] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  240.933779] l2arc_feed      D ffff880c1fcf3640     0  1236      2 0x00000000
[  240.933785]  ffff8805f2da7d10 0000000000000046 ffff8805feee81c0 ffff8805f2da7fd8
[  240.933794]  ffff8805f2da7fd8 0000000000013640 ffff880600c0ea30 ffff8805feee81c0
[  240.933806]  ffff8805f2da7d20 ffffffffa05e06b0 ffffffffa05e06b4 0000000000000002
[  240.933817] Call Trace:
[  240.933838]  [<ffffffff8135cb95>] ? schedule_preempt_disabled+0x9/0xb
[  240.933846]  [<ffffffff8135bcdb>] ? __mutex_lock_common.isra.6+0x149/0x165
[  240.933864]  [<ffffffffa0504142>] ? __thread_create+0x2d2/0x2d2 [spl]
[  240.933873]  [<ffffffff8135bb06>] ? mutex_lock+0x1a/0x2d
[  240.933882]  [<ffffffff8135c7d6>] ? _cond_resched+0x9/0x1d
[  240.933902]  [<ffffffffa05282c7>] ? l2arc_dev_get_next+0x10/0xcf [zfs]
[  240.933920]  [<ffffffffa0529b19>] ? l2arc_feed_thread+0x90/0x778 [zfs]
[  240.933929]  [<ffffffff810f1063>] ? virt_to_head_page+0x6/0x29
[  240.933936]  [<ffffffff810f1410>] ? __cache_free.isra.38+0xe7/0x1a5
[  240.933949]  [<ffffffffa0500709>] ? kmem_free_debug+0xc5/0x10d [spl]
[  240.933961]  [<ffffffffa0504142>] ? __thread_create+0x2d2/0x2d2 [spl]
[  240.933970]  [<ffffffff810f19d6>] ? kfree+0x57/0x76
[  240.933981]  [<ffffffffa0500709>] ? kmem_free_debug+0xc5/0x10d [spl]
[  240.933990]  [<ffffffff8135d2cc>] ? _raw_spin_unlock_irqrestore+0xc/0xd
[  240.934000]  [<ffffffff8105c7a9>] ? set_user_nice+0xd0/0x108
[  240.934017]  [<ffffffffa0529a89>] ? l2arc_evict+0x248/0x248 [zfs]
[  240.934028]  [<ffffffffa0504142>] ? __thread_create+0x2d2/0x2d2 [spl]
[  240.934041]  [<ffffffffa05041ac>] ? thread_generic_wrapper+0x6a/0x75 [spl]
[  240.934052]  [<ffffffff81051e2b>] ? kthread+0x67/0x6f
[  240.934061]  [<ffffffff813636a4>] ? kernel_thread_helper+0x4/0x10
[  240.934070]  [<ffffffff81051dc4>] ? kthread_freezable_should_stop+0x3c/0x3c
[  240.934078]  [<ffffffff813636a0>] ? gs_change+0x13/0x13
[  244.623947] tun: Universal TUN/TAP device driver, 1.6
[  244.623950] tun: (C) 1999-2004 Max Krasnyansky <maxk@qualcomm.com>
[  267.380609] br1: port 2(vnet0) entered disabled state
[  360.897266] INFO: task l2arc_feed:1236 blocked for more than 120 seconds.
[  360.897376] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  360.897494] l2arc_feed      D ffff880c1fcf3640     0  1236      2 0x00000000
[  360.897500]  ffff8805f2da7d10 0000000000000046 ffff8805feee81c0 ffff8805f2da7fd8
[  360.897508]  ffff8805f2da7fd8 0000000000013640 ffff880600c0ea30 ffff8805feee81c0
[  360.897514]  ffff8805f2da7d20 ffffffffa05e06b0 ffffffffa05e06b4 0000000000000002
[  360.897520] Call Trace:
[  360.897540]  [<ffffffff8135cb95>] ? schedule_preempt_disabled+0x9/0xb
[  360.897545]  [<ffffffff8135bcdb>] ? __mutex_lock_common.isra.6+0x149/0x165
[  360.897560]  [<ffffffffa0504142>] ? __thread_create+0x2d2/0x2d2 [spl]
[  360.897564]  [<ffffffff8135bb06>] ? mutex_lock+0x1a/0x2d
[  360.897568]  [<ffffffff8135c7d6>] ? _cond_resched+0x9/0x1d
[  360.897586]  [<ffffffffa05282c7>] ? l2arc_dev_get_next+0x10/0xcf [zfs]
[  360.897600]  [<ffffffffa0529b19>] ? l2arc_feed_thread+0x90/0x778 [zfs]
[  360.897606]  [<ffffffff810f1063>] ? virt_to_head_page+0x6/0x29
[  360.897610]  [<ffffffff810f1410>] ? __cache_free.isra.38+0xe7/0x1a5
[  360.897619]  [<ffffffffa0500709>] ? kmem_free_debug+0xc5/0x10d [spl]
[  360.897627]  [<ffffffffa0504142>] ? __thread_create+0x2d2/0x2d2 [spl]
[  360.897632]  [<ffffffff810f19d6>] ? kfree+0x57/0x76
[  360.897639]  [<ffffffffa0500709>] ? kmem_free_debug+0xc5/0x10d [spl]
[  360.897645]  [<ffffffff8135d2cc>] ? _raw_spin_unlock_irqrestore+0xc/0xd
[  360.897650]  [<ffffffff8105c7a9>] ? set_user_nice+0xd0/0x108
[  360.897664]  [<ffffffffa0529a89>] ? l2arc_evict+0x248/0x248 [zfs]
[  360.897673]  [<ffffffffa0504142>] ? __thread_create+0x2d2/0x2d2 [spl]
[  360.897681]  [<ffffffffa05041ac>] ? thread_generic_wrapper+0x6a/0x75 [spl]
[  360.897688]  [<ffffffff81051e2b>] ? kthread+0x67/0x6f
[  360.897694]  [<ffffffff813636a4>] ? kernel_thread_helper+0x4/0x10
[  360.897699]  [<ffffffff81051dc4>] ? kthread_freezable_should_stop+0x3c/0x3c
[  360.897704]  [<ffffffff813636a0>] ? gs_change+0x13/0x13
[  480.863112] INFO: task l2arc_feed:1236 blocked for more than 120 seconds.
[  480.863222] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  480.863340] l2arc_feed      D ffff880c1fcf3640     0  1236      2 0x00000000
[  480.863345]  ffff8805f2da7d10 0000000000000046 ffff8805feee81c0 ffff8805f2da7fd8
[  480.863353]  ffff8805f2da7fd8 0000000000013640 ffff880600c0ea30 ffff8805feee81c0
[  480.863359]  ffff8805f2da7d20 ffffffffa05e06b0 ffffffffa05e06b4 0000000000000002
[  480.863365] Call Trace:
[  480.863385]  [<ffffffff8135cb95>] ? schedule_preempt_disabled+0x9/0xb
[  480.863390]  [<ffffffff8135bcdb>] ? __mutex_lock_common.isra.6+0x149/0x165
[  480.863404]  [<ffffffffa0504142>] ? __thread_create+0x2d2/0x2d2 [spl]
[  480.863409]  [<ffffffff8135bb06>] ? mutex_lock+0x1a/0x2d
[  480.863413]  [<ffffffff8135c7d6>] ? _cond_resched+0x9/0x1d
[  480.863432]  [<ffffffffa05282c7>] ? l2arc_dev_get_next+0x10/0xcf [zfs]
[  480.863447]  [<ffffffffa0529b19>] ? l2arc_feed_thread+0x90/0x778 [zfs]
[  480.863452]  [<ffffffff810f1063>] ? virt_to_head_page+0x6/0x29
[  480.863457]  [<ffffffff810f1410>] ? __cache_free.isra.38+0xe7/0x1a5
[  480.863465]  [<ffffffffa0500709>] ? kmem_free_debug+0xc5/0x10d [spl]
[  480.863474]  [<ffffffffa0504142>] ? __thread_create+0x2d2/0x2d2 [spl]
[  480.863478]  [<ffffffff810f19d6>] ? kfree+0x57/0x76
[  480.863486]  [<ffffffffa0500709>] ? kmem_free_debug+0xc5/0x10d [spl]
[  480.863491]  [<ffffffff8135d2cc>] ? _raw_spin_unlock_irqrestore+0xc/0xd
[  480.863497]  [<ffffffff8105c7a9>] ? set_user_nice+0xd0/0x108
[  480.863511]  [<ffffffffa0529a89>] ? l2arc_evict+0x248/0x248 [zfs]
[  480.863519]  [<ffffffffa0504142>] ? __thread_create+0x2d2/0x2d2 [spl]
[  480.863528]  [<ffffffffa05041ac>] ? thread_generic_wrapper+0x6a/0x75 [spl]
[  480.863535]  [<ffffffff81051e2b>] ? kthread+0x67/0x6f
[  480.863541]  [<ffffffff813636a4>] ? kernel_thread_helper+0x4/0x10
[  480.863546]  [<ffffffff81051dc4>] ? kthread_freezable_should_stop+0x3c/0x3c
[  480.863551]  [<ffffffff813636a0>] ? gs_change+0x13/0x13
[  480.863621] INFO: task zfs:6501 blocked for more than 120 seconds.
[  480.863715] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  480.863833] zfs             D ffff880c1fcf3640     0  6501   6484 0x00000000
[  480.863838]  ffff880bf92fdd28 0000000000000082 ffff880bf1d1b710 ffff880bf92fdfd8
[  480.863844]  ffff880bf92fdfd8 0000000000013640 ffff880bfecea300 ffff880bf1d1b710
[  480.863850]  0000000000000000 ffffffffa05e06b0 ffffffffa05e06b4 0000000000000002
[  480.863856] Call Trace:
[  480.863863]  [<ffffffff8135cb95>] ? schedule_preempt_disabled+0x9/0xb
[  480.863868]  [<ffffffff8135bcdb>] ? __mutex_lock_common.isra.6+0x149/0x165
[  480.863873]  [<ffffffff8135bb06>] ? mutex_lock+0x1a/0x2d
[  480.863903]  [<ffffffffa056962e>] ? spa_all_configs+0x6b/0x10a [zfs]
[  480.863930]  [<ffffffffa058acde>] ? zfs_ioc_pool_configs+0x15/0x44 [zfs]
[  480.863955]  [<ffffffffa058f2a0>] ? zfsdev_ioctl+0x366/0x40f [zfs]
[  480.863960]  [<ffffffff81360273>] ? do_page_fault+0x311/0x38d
[  480.863965]  [<ffffffff8110bf6a>] ? vfs_ioctl+0x1e/0x31
[  480.863969]  [<ffffffff8110c7ab>] ? do_vfs_ioctl+0x3f1/0x433
[  480.863973]  [<ffffffff810da5bc>] ? do_munmap+0x2a7/0x2cf
[  480.863977]  [<ffffffff8110c838>] ? sys_ioctl+0x4b/0x6f
[  480.863982]  [<ffffffff813623b9>] ? system_call_fastpath+0x16/0x1b
[  480.863987] INFO: task zpool:6585 blocked for more than 120 seconds.
[  480.864083] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  480.864200] zpool           D ffff880c1fcf3640     0  6585   6513 0x00000000
[  480.864205]  ffff880c00229d28 0000000000000086 ffff880bf8162870 ffff880c00229fd8
[  480.864211]  ffff880c00229fd8 0000000000013640 ffff880600c0ea30 ffff880bf8162870
[  480.864217]  0000000000000000 ffffffffa05e06b0 ffffffffa05e06b4 0000000000000002
[  480.864223] Call Trace:
[  480.864230]  [<ffffffff8135cb95>] ? schedule_preempt_disabled+0x9/0xb
[  480.864234]  [<ffffffff8135bcdb>] ? __mutex_lock_common.isra.6+0x149/0x165
[  480.864240]  [<ffffffff8135bb06>] ? mutex_lock+0x1a/0x2d
[  480.864269]  [<ffffffffa056962e>] ? spa_all_configs+0x6b/0x10a [zfs]
[  480.864295]  [<ffffffffa058acde>] ? zfs_ioc_pool_configs+0x15/0x44 [zfs]
[  480.864321]  [<ffffffffa058f2a0>] ? zfsdev_ioctl+0x366/0x40f [zfs]
[  480.864325]  [<ffffffff81360273>] ? do_page_fault+0x311/0x38d
[  480.864329]  [<ffffffff8110bf6a>] ? vfs_ioctl+0x1e/0x31
[  480.864333]  [<ffffffff8110c7ab>] ? do_vfs_ioctl+0x3f1/0x433
[  480.864337]  [<ffffffff810da5bc>] ? do_munmap+0x2a7/0x2cf
[  480.864341]  [<ffffffff8110c838>] ? sys_ioctl+0x4b/0x6f
[  480.864345]  [<ffffffff813623b9>] ? system_call_fastpath+0x16/0x1b

**Comment by behlendorf** [comment]
Closing as stale.
