### ISSUE TITLE
Improve ashift handling

### ISSUE THREAD

**Issue by FransUrbo** [zfsonlinux/zfs#2024]
I just got three additional 3TB disks to replace disks in a vdev with 1.5TB disks that isn't under warranty any more.

The pool was originally created like this (all 1.5TB disks, five vdevs with three disks in each as a RAIDz):

```
History for 'share':
2011-11-03.22:41:47 zpool create -f -o ashift=12 share raidz1 scsi-SATA_ST31500341AS_9VS3S9YD scsi-SATA_ST31500341AS_9VS08THF scsi-SATA_ST31500341AS_9VS16S63
2011-11-03.22:41:50 zpool add -f share raidz1 scsi-SATA_ST31500341AS_9VS4XK4T scsi-SATA_ST31500341AS_9VS4Q3F4 scsi-SATA_ST1500DL003-9VT_5YD1F2KF
2011-11-03.22:41:54 zpool add -f share raidz1 scsi-SATA_ST31500341AS_9VS3SAWS scsi-SATA_ST31500341AS_9VS0DR98 scsi-SATA_ST31500341AS_9VS13W11
2011-11-03.22:41:58 zpool add -f share raidz1 scsi-SATA_ST31500341AS_9VS4VT5R scsi-SATA_ST31500341AS_9VS4Q38C scsi-SATA_ST31500341AS_9VS4WM30
2011-11-03.22:42:00 zpool add -f share raidz1 scsi-SATA_ST31500341AS_9VS4VT5X scsi-SATA_ST31500341AS_9VS4WWPA scsi-SATA_ST31500341AS_9VS0H3A9
```

The disks in the first vdev was replaced with 3TB disks some months ago:

```
2013-04-20.14:08:08 zpool replace -f share scsi-SATA_ST31500341AS_9VS08THF scsi-SATA_ST3000DM001-9YN_Z1F0X41F
2013-04-23.09:40:23 zpool replace share scsi-SATA_ST31500341AS_9VS3S9YD scsi-SATA_ST3000DM001-9YN_Z1F0WJSN
2013-04-24.21:55:34 zpool replace share scsi-SATA_ST31500341AS_9VS16S63 scsi-SATA_ST3000DM001-9YN_Z1F0X3P4
```

This naturally worked just fine, so I didn't have any suspicion that the current replace would fail. But I got 'devices have different sector alignment'. Googling this, I found #1381.

So double checking with zdb I found:

```
celia(ZFSRoot):~# zdb | grep ashift
            ashift: 12
            ashift: 9
            ashift: 9
            ashift: 9
            ashift: 9
```

So the <code>zpool add</code> didn't create the vdevs with ashift=12, but the default ashift=9!

This was _not_ expected. I had expected the ashift to be inherited  (all documentation talks about 'use ashift=12 when creating the pool' - which I did).

One could argue that this is a documentation issue, but I think that would be a (to) easy fix. Currently I see that '-o ashift=xx' is allowed for <code>add</code>, but I'm _quite_ sure it wasn't when I created the pool a year ago. Don't remember the exact version I used then, but some of the 0.6.0 rc versions I think. 0.6.0-rc11 was stable at the time, so I guess that's the one...

PS. I've now done the first replace using '-o ashift=9' (been resilvering for about 14h, 16h to go at ~200M/s). So this explains why my pool have been so darn slow! I thought it was cpu/mem/controller that wasn't fast enough so I never bothered to investigate further - it was fast enough for my use case...

**Comment by JKDingwall** [comment]
I've just been bitten by the assumption that the value used at create time is inherited for subsequent attach operations.  Specifically the FAQ http://zfsonlinux.org/faq.html says:

    "This tuning can only be set when the pool is first created and it will result in a decrease of capacity." 

I think this should be clarified asap.

**Comment by FransUrbo** [comment]
<code>zpool(8)</code>:

```
ashift
  […]
  Keep  in  mind is that the ashift is vdev specific and is not a pool global.
  This means that when adding new vdevs to an existing pool you may
  need to specify the shift.
```

It's clearly there… If you/people don't read the documentation, then it doesn't matter how or where we put it...

**Comment by JKDingwall** [comment]
I did read the documentation and it told me that the property can only be set when the pool is first created.  It seems reasonable to assume that the documentation is consistent and correct whether that is the man page or the FAQ.  As it stands I consider the FAQ text contradicts the  and suggest it should be amended for clarity or that it should simply refer man page if that is the authoritative source rather than making a contradictory statement.

The line in the man page was added in https://github.com/zfsonlinux/zfs/commit/022f7bf68e2868890a4b1957d5ee0a67909dfd1a which is pre-dated by https://web.archive.org/web/20140307194846/http://zfsonlinux.org/faq.html.

**Comment by FransUrbo** [comment]
There is no contradiction! Both apply:

```
The following property can be set at creation time:

ashift
  […]
  Additionally, the minimum (disk) write size will be set to the specified size, so this represents a space vs. performance trade-off.
  […]
  Since the property cannot be changed after pool creation […]
  […]
  Keep  in  mind is that the ashift is vdev specific and is not a pool global.
```

**Comment by JKDingwall** [comment]
I perceive a contradiction because my interpretation of the FAQ text is that the ashift value cannot be changed once the zpool has been created.  This is correct in the sense that for the original vdev it cannot but it also implies that all vdevs which are subsequently attached will use the same value which is not true and was clarified by the man page commit.  It would be helpful for the FAQ to make the same clarification as the man page that the parameter only applies to the initial vdev and that future operations should use the ashift option again when necessary.

**Comment by FransUrbo** [comment]
> my interpretation of the FAQ text is that the ashift value cannot be changed once the zpool has been created.

Correct.

> it also implies that all vdevs which are subsequently attached will use the same value

And that's where the man page comes in:

```
[…] ashift is vdev specific […] when adding new vdevs to an existing pool you may need to specify the ashift.
```

> It would be helpful for the FAQ to make the same clarification as the man page that the parameter only applies to the initial vdev and that future operations should use the ashift option again when necessary.

I could agree on that. BUT,

1. Code trumps man page
2. Man page trumps FAQ
3. FAQ trumps HOWTO


If you want to create a FAQ update, feel free to create a pull request against https://github.com/zfsonlinux/zfsonlinux.github.com.

**Comment by behlendorf** [comment]
@JKDingwall I'm all for updating the FAQ if you could propose some clear language to avoid confusion.

**Comment by Sachiru** [comment]
Perhaps instead of the sentence

>This tuning can only be set when the pool is first created and it will result in a decrease of capacity. 

We can word it as 

>This tuning can only be set when devices are first added to a pool, such as when the pool is first created or when a new vdev is added. Do note that this setting will result in a decrease of capacity.

**Comment by FransUrbo** [comment]
Sounds good to me! @Sachiru do you also just happen, perchance, have a wording for the FAQ? :)

**Comment by Sachiru** [comment]
I've created a pull request with the updated FAQ here:

https://github.com/zfsonlinux/zfsonlinux.github.com/pull/30

**Comment by behlendorf** [comment]
@Sachiru thank you, I've merged your updated FAQ entry.

**Comment by rincebrain** [comment]
This really seems like a problem - I got burned by this as well, setting ashift=12 at creation time, not realizing that it would need me to also set ashift=12 every time I ever added a device to a pool again if I didn't want to mix them.

If I cut a pull request that changed the zpool add behavior to default to the pool-wide ashift property if set to non-zero, and require -f if it's set to 9 and one or more of the devices report =12, would it be likely to be taken?

**Comment by FransUrbo** [comment]
@rincebrain Sounds likely to be accepted. IF you do the same for <code>replace</code> as well :). I've been planning on doing something similar, but I haven't had the energy or enough interest in doing it :).
