### ISSUE TITLE
SPL/ZFS rpm kmod build issue with kernel 3.12.x

### ISSUE THREAD

**Issue by greg-hydrogen** [zfsonlinux/zfs#2046]
Hello Everyone,

I am currently having an issue building the kmod packages for 3.12.x kernel branch.

After checking out the lastest git and running the autogen.sh, when attempting to build the rpm-kmod utils for both spl and zfs I get the following error:

Installing spl-kmod-0.6.2-22_gd58a99a.el6.src.rpm
error: Failed build dependencies:
    kernel-devel-uname-r = 3.12.7 is needed by spl-kmod-0.6.2-22_gd58a99a.el6.x86_64
make[1]: **\* [rpm-common] Error 1

I do have the proper kernel-devel installed on my system:

sudo yum list installed | grep kernel-devel
kernel-devel.x86_64     3.12.7-5        @/kernel-devel-3.12.7-5.x86_64 

Commenting out the following lines in the scripts/kmodtool allows the build to complete and install without any issues:

BuildRequires:    kernel-devel-uname-r = ${kernel_uname_r}
Requires:         kernel-devel-uname-r = ${kernel_uname_r}
BuildRequires:    kernel-devel-uname-r = ${kernel_uname_r}
Requires:         kernel-uname-r  ${kernel_uname_r}

The last line is required for the spl-kmod to install otherwise it complains about the incorrect kernel version, even though the correct one is installed

**Comment by kpande** [comment]
we're still seeing this in CentOS 6.8

```
Installing zfs-kmod-0.7.0-rc1.el6.src.rpm
error: Failed build dependencies:
        kmod-spl-devel = 0.7.0 is needed by zfs-kmod-0.7.0-rc1.el6.x86_64
        kernel-devel-uname-r = 4.4.20 is needed by zfs-kmod-0.7.0-rc1.el6.x86_64
        kmod-spl-uname-r = 4.4.20 is needed by zfs-kmod-0.7.0-rc1.el6.x86_64
        kmod-spl-devel-uname-r = 4.4.20 is needed by zfs-kmod-0.7.0-rc1.el6.x86_64
make[1]: *** [rpm-common] Error 1
```

**Comment by gmelikov** [comment]
I have this issue on zfs 0.7 RC (from this summer) if i didn't install spl packages before zfs compilation, kernel with CONFIG_DEBUG_LOCK_ALLOC:
```
uname -a
Linux runner-f4af3829-project-39-concurrent-0 3.10.0-693.11.1.el7.x86_64 #1 SMP Mon Dec 4 23:52:40 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
```
  - cd spl
  - sh autogen.sh
  - ./configure --with-spec=redhat
  - make pkg-utils pkg-kmod
  - cd ../zfs
  - sh autogen.sh
  - ./configure --with-spec=redhat
  - make pkg-utils pkg-kmod
...
make  pkg="zfs-kmod" \
	def='--define "_without_debug 1" --define "kernels 3.10.0-693.11.1.el7.x86_64.debug" --define "require_spldir /builds/internal/spl-zfs-lustre/spl" --define "require_splobj /builds/internal/spl-zfs-lustre/spl" --define "ksrc /usr/src/kernels/3.10.0-693.11.1.el7.x86_64.debug" --define "kobj /usr/src/kernels/3.10.0-693.11.1.el7.x86_64.debug"' rpm-common
make[1]: Entering directory `/builds/internal/spl-zfs-lustre/zfs'
make[2]: Entering directory `/builds/internal/spl-zfs-lustre/zfs'
make[2]: Leaving directory `/builds/internal/spl-zfs-lustre/zfs'
error: Failed build dependencies:
	kmod-spl-devel = 0.7.0 is needed by zfs-kmod-0.7.0-rc3.el7.centos.x86_64
Installing zfs-kmod-0.7.0-rc3.el7.centos.src.rpm
make[1]: *** [rpm-common] Error 1
make[1]: Leaving directory `/builds/internal/spl-zfs-lustre/zfs'
make: *** [rpm-kmod] Error 2
```

**Comment by behlendorf** [comment]
Closing.  The spl and zfs packages have been merged for the upcoming release.
