### ISSUE TITLE
zfs set propogation latency

### ISSUE THREAD

**Issue by globalcitizen** [zfsonlinux/zfs#2053]
This may be a 'design feature' but I call it a bug.

I am using zfs dataset metadata to store some application-specific volume management attributes.

The behaviour I observe is `zfs set ...` followed by `zfs get ...` leading to a failure to read newly set attributes.  Adding the old `sleep 1` between them fixes the problem.

This is particularly annoying as part of ZFS' attraction is its supposed speed.

Environment: zfs-0.6.2 on 3.11.2 SMP x86_64

**Comment by loli10K** [comment]
This doesn't seem to be reproducible on any recent version, the ZTS should be able to catch this (`set_n_check_prop` in "zfs_set_common.kshlib")
