### ISSUE TITLE
Feature Request:  Add -U and -B flags to zpool create for bootable pools

### ISSUE THREAD

**Issue by aarcane** [zfsonlinux/zfs#2062]
As per a post on the mailing list, here is the following feature request:

I'd like to request that a command line argument be added to zpool create (and possibly to zpool attach, zpool replace, and anywhere else we may insert a disk into a pool) that will add either a GPT BIOS_GRUB (-B) partition to the beginning of a disk automatically, or a 128MiB UEFI System Partition (-U) to the beginning of a disk when the partition table is created.

The purpose is to facilitate "Whole disk" installs ala rlaager's guide without manual disk manipulation, and to expand the method to UEFI system disks  As this seems a trivial feature to implement, it'd be lovely to see it in 0.6.3.

I'd also like to note that -U and -B needn't be mutually exclusive, and it should in theory be possible to make a USB drive live install that can boot from either.  Therefore I propose adding the UEFI partition at the beginning of the drive alligned at 1MiB and ending at 129MiB.  

The GPT BIOS_GRUB partition should begin at 48s and end at 2047s

**Comment by behlendorf** [comment]
Proposed patch in #4848.

**Comment by rlaager** [comment]
The more I think about this whole thing, the less I think it's the right answer. If you start going down this rabbit hole, you'll run into things like UEFI on mirrors. Is ZFS going to mirror that FAT filesystem (yuck!) or is ZFS going to setup an MD array? It's just madness. I've given up the fight on wholedisk. Not even Solaris used wholedisk for their bootable pools. It just falls down in so many ways.

Plus, this would require distro installers to use more ZFS-specific code. Letting them partition the disk as normal and then throw ZFS on a partition is a lot simpler to integrate.
