### ISSUE TITLE
what's with all the context switches (3.13.2, git master as of bug open date)

### ISSUE THREAD

**Issue by prometheanfire** [zfsonlinux/zfs#2127]
#      Time   UID       PID   kB_rd/s   kB_wr/s kB_ccwr/s   cswch/s nvcswch/s  Command
     1392352908     0         1      0.00      0.00      0.00      0.20      0.00  init
     1392352908     0         3      0.00      0.00      0.00    235.90      0.00  ksoftirqd/0
     1392352908     0         7      0.00      0.00      0.00      6.70      0.00  rcu_sched
     1392352908     0        10      0.00      0.00      0.00      0.20      0.00  watchdog/0
     1392352908     0        11      0.00      0.00      0.00      0.20      0.00  watchdog/1
     1392352908     0        13      0.00      0.00      0.00      0.20      0.00  ksoftirqd/1
     1392352908     0        16      0.00      0.00      0.00      0.20      0.00  watchdog/2
     1392352908     0        21      0.00      0.00      0.00      0.20      0.00  watchdog/3
     1392352908     0        23      0.00      0.00      0.00      0.10      0.00  ksoftirqd/3
     1392352908     0        26      0.00      0.00      0.00      0.20      0.00  watchdog/4
     1392352908     0        29      0.00      0.00      0.00      3.90      0.00  kworker/4:0
     1392352908     0        31      0.00      0.00      0.00      0.20      0.00  watchdog/5
     1392352908     0        36      0.00      0.00      0.00      0.20      0.00  watchdog/6
     1392352908     0        39      0.00      0.00      0.00      1.30      0.00  kworker/6:0
     1392352908     0        41      0.00      0.00      0.00      0.20      0.00  watchdog/7
     1392352908     0       841      0.00      0.00      0.00      2.60      0.00  kworker/5:1
     1392352908     0       848      0.00      0.00      0.00      4.00      0.00  kworker/1:1
     1392352908     0       956      0.00      0.00      0.00      0.10      0.00  khugepaged
     1392352908     0       957      0.00      0.00      0.00      5.10      0.00  spl_kmem_cache/
     1392352908     0       968      0.00      0.00      0.00      1.00      0.00  arc_adapt
     1392352908     0       969      0.00      0.00      0.00      1.00      0.00  l2arc_feed
     1392352908     0      1172      0.00      0.00      0.00      1.00      0.00  kipmi0
     1392352908     0      5368      0.00      0.00      0.00      4.00      0.00  z_null_iss/0
     1392352908     0      5369      0.00      0.00      0.00      1.40      0.00  z_null_int/0
     1392352908     0      5370   5759.60      0.00      0.00    428.50      0.20  z_rd_iss/0
     1392352908     0      5371   5959.20      0.00      0.00    421.20      0.10  z_rd_iss/1
     1392352908     0      5372   5927.60      0.00      0.00    429.40      0.20  z_rd_iss/2
     1392352908     0      5373   5721.20      0.00      0.00    415.60      0.10  z_rd_iss/3
     1392352908     0      5374   5775.20      0.00      0.00    414.80      0.00  z_rd_iss/4
     1392352908     0      5375   5976.80      0.00      0.00    428.60      0.30  z_rd_iss/5
     1392352908     0      5376   5891.60      0.00      0.00    420.00      0.50  z_rd_iss/6
     1392352908     0      5377   5939.20      0.00      0.00    421.60      0.00  z_rd_iss/7
     1392352908     0      5378  19156.80      0.00      0.00   2663.70      0.10  z_rd_int/0
     1392352908     0      5379  18668.80      0.00      0.00   2722.40      0.10  z_rd_int/1
     1392352908     0      5380  18350.40      0.00      0.00   2651.80      0.00  z_rd_int/2
     1392352908     0      5381  18936.80      0.00      0.00   2674.40      0.10  z_rd_int/3
     1392352908     0      5382  18812.80      0.00      0.00   2688.90      0.20  z_rd_int/4
     1392352908     0      5383  18138.40      0.00      0.00   2654.60      0.10  z_rd_int/5
     1392352908     0      5384      0.00      0.00      0.00      1.70      0.00  z_wr_iss/0
     1392352908     0      5385      0.00      0.00      0.00      1.20      0.00  z_wr_iss/1
     1392352908     0      5386      0.00      0.00      0.00      1.80      0.00  z_wr_iss/2
     1392352908     0      5387      0.00      0.00      0.00      1.70      0.00  z_wr_iss/3
     1392352908     0      5388      0.00      0.00      0.00      0.90      0.00  z_wr_iss/4
     1392352908     0      5389      0.00      0.00      0.00      1.70      0.00  z_wr_iss/5
     1392352908     0      5395      0.00      0.00      0.00      2.90      0.00  z_wr_int/0
     1392352908     0      5396      0.00      0.00      0.00      3.10      0.00  z_wr_int/1
     1392352908     0      5397      0.00      0.00      0.00      2.90      0.00  z_wr_int/2
     1392352908     0      5398      0.00      0.00      0.00      3.40      0.10  z_wr_int/3
     1392352908     0      5399      0.00      0.00      0.00      3.00      0.00  z_wr_int/4
     1392352908     0      5400      0.00      0.00      0.00      3.10      0.00  z_wr_int/5
     1392352908     0      5401      0.00      0.00      0.00      3.20      0.00  z_wr_int/6
     1392352908     0      5402      0.00      0.00      0.00      3.00      0.00  z_wr_int/7
     1392352908     0      5403      0.00      0.00      0.00      3.00      0.00  z_wr_int/8
     1392352908     0      5404      0.00      0.00      0.00      2.70      0.00  z_wr_int/9
     1392352908     0      5405      0.00      0.00      0.00      2.90      0.00  z_wr_int/10
     1392352908     0      5406      0.00      0.00      0.00      3.00      0.00  z_wr_int/11
     1392352908     0      5407      0.00      0.00      0.00      3.30      0.00  z_wr_int/12
     1392352908     0      5408      0.00      0.00      0.00      2.70      0.00  z_wr_int/13
     1392352908     0      5409      0.00      0.00      0.00      3.00      0.00  z_wr_int/14
     1392352908     0      5410      0.00      0.00      0.00      2.80      0.00  z_wr_int/15
     1392352908     0      5416      0.00      0.00      0.00      0.20      0.00  z_fr_iss_0/0
     1392352908     0      5417      0.00      0.00      0.00      0.10      0.00  z_fr_iss_0/1
     1392352908     0      5418      0.00      0.00      0.00      0.20      0.00  z_fr_iss_0/2
     1392352908     0      5422      0.00      0.00      0.00      0.10      0.00  z_fr_iss_1/2
     1392352908     0      5423      0.00      0.00      0.00      0.10      0.00  z_fr_iss_1/3
     1392352908     0      5424      0.00      0.00      0.00      0.10      0.00  z_fr_iss_2/0
     1392352908     0      5425      0.00      0.00      0.00      0.10      0.00  z_fr_iss_2/1
     1392352908     0      5427      0.00      0.00      0.00      0.10      0.00  z_fr_iss_2/3
     1392352908     0      5432      0.00      0.00      0.00      0.10      0.00  z_fr_iss_4/0
     1392352908     0      5433      0.00      0.00      0.00      0.10      0.00  z_fr_iss_4/1
     1392352908     0      5434      0.00      0.00      0.00      0.10      0.00  z_fr_iss_4/2
     1392352908     0      5435      0.00      0.00      0.00      0.10      0.00  z_fr_iss_4/3
     1392352908     0      5437      0.00      0.00      0.00      0.10      0.00  z_fr_iss_5/1
     1392352908     0      5440      0.00      0.00      0.00      0.20      0.00  z_fr_iss_6/0
     1392352908     0      5442      0.00      0.00      0.00      0.10      0.00  z_fr_iss_6/2
     1392352908     0      5451      0.00      0.00      0.00      0.20      0.00  z_ioctl_iss/0
     1392352908     0      5452      0.00      0.00      0.00      2.70      0.00  z_ioctl_int/0
     1392352908     0      5470      0.00      0.00      0.00      0.20      0.00  txg_quiesce
     1392352908     0      5471      0.00      0.00      0.00   2037.70      0.00  txg_sync
     1392352908     0      5472      0.00      0.00      0.00      1.40      0.00  kworker/7:2
     1392352908     0      5911      0.00      0.00      0.00      5.60      0.00  kworker/3:7
     1392352908     0      6387      0.00      0.00      0.00      2.10      0.00  kworker/6:2
     1392352908     0      7380      0.00      0.00      0.00   2318.70      0.10  haveged
     1392352908   102      7425      0.00      0.00      0.00      2.00      0.00  nrpe
     1392352908     0      8283      0.00      0.00      0.00      3.20      0.00  kworker/2:2
     1392352908     0     12362      0.00      0.00      0.00      3.50      0.00  kworker/2:0
     1392352908     0     13633      0.00      0.00      0.00      2.80      0.00  kworker/5:2
     1392352908     0     15420      0.00      0.00      0.00      1.50      0.00  kworker/7:1
     1392352908     0     16675      0.00      0.00      0.00      0.10      0.00  sshd
     1392352908     0     18639      0.00      0.00      0.00    595.80     79.70  kworker/0:0
     1392352908     0     18647      0.00      0.00      0.00    661.30     79.80  kworker/0:4
     1392352908     0     21507      0.00      0.00      0.00      3.50      0.00  kworker/3:1
     1392352908     0     21508      0.00      0.00      0.00     73.80      0.00  kworker/1:0
     1392352908     0     22606      0.00      0.00      0.00      2.80      0.00  kworker/4:1
     1392352908     0     22974      0.00      0.00      0.00   1946.10    762.00  kworker/0:5
     1392352908     0     23074      0.00      0.00      0.00    915.00    239.00  kworker/0:1
     1392352908     0     23220      0.00      0.00      0.00    516.10    112.60  kworker/0:6
     1392352908     0     23980      0.00      0.00      0.00      1.30      0.00  kworker/u32:2
     1392352908     0     23982      0.00      0.00      0.00      0.10     69.10  pidstat

**Comment by prometheanfire** [comment]
I'd say it's about 2x more effecient right now, for z_rd_int at least. neato

**Comment by behlendorf** [comment]
@prometheanfire great, thanks for following up.
