### ISSUE TITLE
one ZFS file system always starts with readonly=on   temporary on boot

### ISSUE THREAD

**Issue by timothyjlaurent** [zfsonlinux/zfs#2133]
I am running Ubuntu 12.04.
So I have created a zpool and put my /home directory in a zfs called _volume/home_.

I discovered after not being able to log in that my home directory was readonly.

Look here:

```
root@supaserva:/home/dadmin# zfs get all | grep readonly
volume              readonly              off                    default
volume/home         readonly              on                     temporary
volume/movies       readonly              off                    default
volume/music        readonly              off                    default
volume/pictures     readonly              off                    default
volume/vault        readonly              off                    default
```

So if I do `zfs set readonly=off volume/home` I am able to log in and everything is good until I reboot and the volume/home mounts as readonly again, but the listing in `zfs get all` remains the same.

Can anyone help figure out how to fix this issue?

**Comment by DarwinAwardWinner** [comment]
I'm seeing similar behavior with /opt on my Ubuntu 14.04 system:

```
$ zfs get all | grep readonly
rpool                                                             readonly                    off                           default
rpool/TimeCapsule                                                 readonly                    off                           default
rpool/home                                                        readonly                    off                           default
rpool/home/ryan                                                   readonly                    off                           default
rpool/home/ryan/BTSync                                            readonly                    off                           default
rpool/home/ryan/Downloads                                         readonly                    off                           default
rpool/opt                                                         readonly                    on                            temporary
rpool/root-backup                                                 readonly                    off                           default
rpool/seafile                                                     readonly                    off                           default
rpool/transmission-daemon                                         readonly                    off                           default
$ mount
/dev/mapper/mneme-mneme on / type ext4 (rw,errors=remount-ro)
proc on /proc type proc (rw,noexec,nosuid,nodev)
sysfs on /sys type sysfs (rw,noexec,nosuid,nodev)
none on /sys/fs/cgroup type tmpfs (rw)
none on /sys/fs/fuse/connections type fusectl (rw)
none on /sys/kernel/debug type debugfs (rw)
none on /sys/kernel/security type securityfs (rw)
udev on /dev type devtmpfs (rw,mode=0755)
devpts on /dev/pts type devpts (rw,noexec,nosuid,gid=5,mode=0620)
tmpfs on /run type tmpfs (rw,noexec,nosuid,size=10%,mode=0755)
none on /run/lock type tmpfs (rw,noexec,nosuid,nodev,size=5242880)
none on /run/shm type tmpfs (rw,nosuid,nodev)
none on /run/user type tmpfs (rw,noexec,nosuid,nodev,size=104857600,mode=0755)
none on /sys/fs/pstore type pstore (rw)
rpool on /rpool type zfs (rw)
rpool/TimeCapsule on /mnt/TimeCapsule type zfs (rw)
rpool/home on /home type zfs (rw)
rpool/home/ryan on /home/ryan type zfs (rw)
rpool/home/ryan/BTSync on /home/ryan/BTSync type zfs (rw)
rpool/home/ryan/Downloads on /home/ryan/Downloads type zfs (rw)
rpool/opt on /opt type zfs (ro)
rpool/root-backup on /rpool/root-backup type zfs (rw)
rpool/seafile on /srv/seafile type zfs (rw)
rpool/transmission-daemon on /var/lib/transmission-daemon type zfs (rw)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,noexec,nosuid,nodev)
systemd on /sys/fs/cgroup/systemd type cgroup (rw,noexec,nosuid,nodev,none,name=systemd)
$ cat /etc/fstab
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
/dev/mapper/mneme-mneme /               ext4    errors=remount-ro 0       1
# swap was on /dev/sdb1 during installation
UUID=6aeb2b6d-b6b9-48fa-8836-e4e25ce6e7f9 none            swap    sw,pri=0              0       0
UUID=dc89622c-71b8-4731-9d71-4566b91be76a none            swap    sw,pri=0              0       0
UUID=d9097ff2-e1b4-43da-b145-38d67551afdf none            swap    sw,pri=0              0       0
$ uname -a
Linux mneme.homenet.org 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty
```

**Comment by UltraSalem** [comment]
Same issue for me on 14.04.02 64bit. Using the zfs in-built mounting, not fstab. Was working fine until I did a dist-upgrade a few weeks or so ago. As per OP above, if I manually set readonly=off, I can write to the pool, but the property still shows as readonly=on

$ sudo zfs get all | grep readonly
zdata  readonly              on                     temporary

$ sudo aptitude versions zfs
Package libzfs-dev:                 
p   0.6.3-5~trusty                                                      trusty                                           1001

Package libzfs-dev:i386:
p   0.6.3-5~trusty                                                      trusty                                           1001

Package libzfs1:
p   0.6.2-1~saucy                                                                                                        100 
p   0.6.2-2~trusty                                                      trusty                                           1001

Package libzfs1-dbg:
p   0.6.2-2~trusty                                                      trusty                                           1001

Package libzfs1-dbg:i386:
p   0.6.2-2~trusty                                                      trusty                                           1001

Package libzfs1:i386:
p   0.6.2-2~trusty                                                      trusty                                           1001

Package libzfs2:
i A 0.6.3-5~trusty                                                      trusty                                           1001

Package libzfs2-dbg:
p   0.6.3-5~trusty                                                      trusty                                           1001

Package libzfs2-dbg:i386:
p   0.6.3-5~trusty                                                      trusty                                           1001

Package libzfs2:i386:
p   0.6.3-5~trusty                                                      trusty                                           1001

Package ubuntu-zfs:
i   8~trusty                                                            trusty                                           1001

Package ubuntu-zfs:i386:
p   8~trusty                                                            trusty                                           1001

Package zfs-auto-snapshot:
p   1.1.0-0ubuntu1~trusty                                               trusty                                           1001

Package zfs-dkms:
i   0.6.3-5~trusty                                                      trusty                                           1001

Package zfs-dkms:i386:
p   0.6.3-5~trusty                                                      trusty                                           1001

Package zfs-doc:
i A 0.6.3-5~trusty                                                      trusty                                           1001

Package zfs-doc:i386:
p   0.6.3-5~trusty                                                      trusty                                           1001

Package zfs-fuse:
p   0.7.0-10.1                                                          trusty                                           500 

Package zfs-fuse:i386:
p   0.7.0-10.1                                                          trusty                                           500 

Package zfs-initramfs:
p   0.6.3-5~trusty                                                      trusty                                           1001

Package zfs-initramfs:i386:
p   0.6.3-5~trusty                                                      trusty                                           1001

Package zfsutils:
i   0.6.3-5~trusty                                                      trusty                                           1001

Package zfsutils-dbg:
p   0.6.3-5~trusty                                                      trusty                                           1001

Package zfsutils-dbg:i386:
p   0.6.3-5~trusty                                                      trusty                                           1001

Package zfsutils:i386:
p   0.6.3-5~trusty                                                      trusty                                           1001

**Comment by myii** [comment]
@timothyjlaurent @ank @hydro-b @DarwinAwardWinner @UltraSalem

I've been using ZFS-based home directories on a number of Ubuntu computers (10.04, 12.04 & 14.04) for around 2 years and haven't faced this problem - until yesterday.

**In my case**, this wasn't a bug in ZFS but rather an issue in my startup configuration - as an example, I was able to resolve the situation in the following way:

* After reboot, immediately opened up a virtual terminal (i.e. `Ctrl-Alt-F1`)
* Logged in as `root`
* Identified all the `readonly` datasets; in my case, `$POOL/home` and `$POOL/home/$USER`
* Attempted to unmount: `zfs unmount $POOL/home/$USER` - this informed me that the dataset was in use
* As suggested, used `lsof /home/$USER` - and this found the offending cause (which is specific to my startup):
  * There were a number of `gunicorn` processes running - I had recently been testing an `Upstart` configuration
  * After killing the processes, was able to unmount, first the `$POOL/home/$USER` dataset and then `$POOL/home`
  * Immediately mounted both datasets again (obviously `home`, then `home/$USER`) and neither was `readonly`
* So to test this properly, I removed the `Upstart` job and then rebooted the computer - no problem
* Just to make sure, have rebooted 3 times - no issues since

In essence, my suggestion is to find out if you have any startup processes that are causing this problem.  The procedure above may help to identify those.

**Comment by gdevenyi** [comment]
I just ran into this today with 0.6.5.7-1~trusty

**Comment by Ofloo** [comment]
Would that be an accurate reading?

`# zpool iostat
                capacity     operations     bandwidth
pool          alloc   free   read  write   read  write
------------  -----  -----  -----  -----  -----  -----
freenas-boot  8.22G   208G      3      4  68.8K  51.9K
lake          19.7T  14.7T    879      0   **406M**  9.51K
lake2         1.36T  24.1T      4    490  53.7K   **396M**
------------  -----  -----  -----  -----  -----  -----
`

**Comment by phiresky** [comment]
I had the same issue with my root partition always mounting read only with "temporary". I don't have zfs in my fstab and haven't overridden anything, just following the instructions in the ZFS on root partition arch wiki page.

My kernel commandline was just `cryptdevice=... zfs=bootfs`.

Turns out the linux kernel defaults to having the root partition read only, and zfs marks this as "temporary". So it was fixed by changing the commandline to `cryptdevice=... zfs=bootfs rw`
