### ISSUE TITLE
Prefetch should disable itself to avoid wasting precious IOPs

### ISSUE THREAD

**Issue by prakashsurya** [zfsonlinux/zfs#2160]
Running the 0.6.2 tag underneath a Lustre MDS I noticed a particular workload causing a significant number of prefect reads with a 100% miss rate. Here is a snippet from arcstat while it was in this state:

```
# vesta-mds1 /root > arcstat.py 1                                                  
    time  read  miss  miss%  dmis  dm%  pmis  pm%  mmis  mm%  arcsz     c          
13:09:08   234   147     62   125   58    22  100   147   64    15G   15G          
13:09:09   28K   15K     54   11K   46  4.2K  100   15K   58    15G   15G          
13:09:10   23K   14K     59   10K   52  3.5K  100   14K   61    15G   15G          
13:09:11   23K   14K     60  9.9K   51  4.3K  100   14K   61    15G   15G          
13:09:12   23K   14K     61   11K   55  3.6K  100   14K   62    15G   15G          
13:09:13   24K   14K     58   10K   50  3.9K  100   14K   60    15G   15G          
13:09:14   28K   15K     55   11K   48  3.7K  100   15K   60    15G   15G          
13:09:15   24K   13K     56   10K   48  3.7K  100   13K   60    15G   15G          
13:09:16   26K   14K     55   10K   47  4.0K  100   14K   58    15G   15G          
13:09:17   25K   14K     56   11K   49  3.6K  100   14K   58    15G   15G          
13:09:18   24K   14K     59   10K   50  4.1K  100   14K   60    15G   15G          
13:09:19   25K   14K     57   10K   49  4.0K  100   14K   59    15G   15G          
13:09:20   24K   13K     56   10K   48  3.8K  100   13K   60    15G   15G          
13:09:21   27K   14K     52   10K   45  4.0K  100   14K   56    15G   15G          
13:09:22   22K   13K     60  9.9K   52  3.8K  100   13K   61    15G   15G          
13:09:23   24K   14K     61   10K   52  4.2K  100   14K   61    15G   15G          
13:09:24   23K   13K     57  9.9K   49  3.8K  100   13K   60    15G   15G          
13:09:25   27K   14K     53   10K   46  3.8K  100   14K   56    15G   15G          
13:09:26   27K   15K     54   11K   47  3.9K  100   15K   58    15G   15G          
13:09:27   22K   13K     58  9.9K   51  3.4K  100   13K   61    15G   15G          
13:09:28   25K   14K     59   11K   52  3.8K  100   14K   61    15G   15G
```

I then disabled the prefetch code and reran arcstat:

```
# vesta-mds1 /root > echo 1 > /sys/module/zfs/parameters/zfs_prefetch_disable
# vesta-mds1 /root > arcstat.py 1                                               
    time  read  miss  miss%  dmis  dm%  pmis  pm%  mmis  mm%  arcsz     c       
13:09:57   266   167     62   168   62     0    0   168   66    15G   15G       
13:09:58   29K   17K     60   17K   60     0    0   17K   65    15G   15G       
13:09:59   28K   17K     62   17K   62     0    0   17K   66    15G   15G       
13:10:00   22K   15K     68   15K   68     0    0   15K   68    15G   15G       
13:10:01   26K   17K     64   17K   64     0    0   17K   67    15G   15G       
13:10:02   27K   16K     61   16K   61     0    0   16K   66    15G   15G       
13:10:03   29K   18K     61   18K   61     0    0   18K   65    15G   15G       
13:10:04   27K   17K     62   17K   62     0    0   17K   66    15G   15G       
13:10:05   25K   16K     64   16K   64     0    0   16K   67    15G   15G       
13:10:06   25K   16K     65   16K   65     0    0   16K   68    15G   15G       
13:10:07   25K   16K     64   16K   64     0    0   16K   67    15G   15G       
13:10:08   26K   17K     63   17K   63     0    0   17K   67    15G   15G       
13:10:09   25K   16K     65   16K   65     0    0   16K   67    15G   15G       
13:10:10   24K   16K     65   16K   65     0    0   16K   67    15G   15G       
13:10:11   26K   17K     66   17K   66     0    0   17K   67    15G   15G       
13:10:12   27K   17K     64   17K   64     0    0   17K   67    15G   15G       
13:10:13   28K   16K     60   16K   60     0    0   16K   65    15G   15G       
13:10:14   29K   18K     62   18K   62     0    0   18K   66    15G   15G       
13:10:15   23K   15K     67   15K   67     0    0   15K   68    15G   15G       
13:10:16   25K   17K     66   17K   66     0    0   17K   68    15G   15G       
13:10:17   29K   17K     59   17K   59     0    0   17K   65    15G   15G
```

As is expected, the prefetch reads and misses dropped to zero. The more interesting bit, which is a little hard to make out, is the total number of reads processed in those two 20 second intervals increased by about 5% with prefetch disabled. That might not seem significant, but looking at the `MDops/s` field in `ltop`, the number of opens and closes during that time "seemed" to go up by about 40% (it's a little hard to tell due to the dynamic nature of `ltop` but it appeared to go from ~950 ops/s to ~1400 ops/s).

Although this is a bit of a vague report, because I don't know exactly what the workload was or the exact user visible performance numbers; I think there might be some perfomance gains to be had for certain workloads by making the prefetch code smart enough to turn itself off when it is being detrimental.

**Comment by kiranfractal** [comment]
What kind of workloads the prefetch option needs to be disabled ?

**Comment by behlendorf** [comment]
Prefetching was significantly improved in master, 755065f3dce1123eac03e2b25c81647026b8e49b, a6fb32b85acb2245260aa1cbe396aea1f16b9dd3, 7f60329a261bd48558a498fb10e9b29638eab33b.

**Comment by gleventhal** [comment]
I actually think there is a pretty notable locking issue with the prefetch that makes multithreaded, IO-bound applications really suffer.

**Comment by RubenKelevra** [comment]
@behlendorf I think we still need an automation that looks back to the success rate and turns this feature off. I'm using ZFS below a badger database, and the hit rate isn't pretty.

![Screenshot_20210323_083734-1](https://user-images.githubusercontent.com/614929/112110708-9202dc80-8bb3-11eb-8caf-d693d542b025.png)

**Comment by RubenKelevra** [comment]
@behlendorf 

Here's a more detailed example:

recordsize for the whole pool is 8 KByte.

Prefetch decision size is (when access is below x KByte - `zfs_vdev_cache_max`): 16 KByte

If true, then inflate the reads to (`zfs_vdev_cache_bshift`): 64 KByte.

Since there's quite a high chance that reads on a 8 KByte recordsize pool with databases are less than 16 KByte a large portion of the read requests gets inflated:

![Screenshot_20210323_125113-1](https://user-images.githubusercontent.com/614929/112142546-03a05200-8bd7-11eb-84b1-9892c9bdaf1a.png)

_(demand 90K, and 10K gets added just for prefetches)_

How useful is that? Well:

![Screenshot_20210323_124857-1](https://user-images.githubusercontent.com/614929/112142646-2468a780-8bd7-11eb-9eca-a33d04ed19cc.png)

It's 99.1% of the time **not** useful.

I now turned it down to: 512 Bytes and 512 Bytes and let the host system deal with the read overhead by inflating my read requests if necessary - since I don't know what kind of SSD storage backend the hoster is using.

It looks like the system got more performance this way. But I let others with benchmarks decide. :)

**Comment by amotin** [comment]
@RubenKelevra I am confused by what prefetcher are you talking about here? zfs_prefetch_data_hits is a counter of ARC level, while zfs_vdev_cache_max/zfs_vdev_cache_bshift are tunables of vdev level caching, which should be disabled by default, since zfs_vdev_cache_size i set to zero.

**Comment by RubenKelevra** [comment]
@amotin yeah, sorry. Found that out as well - the reason for my drop in prefetching was the change in ARC size I experimented with as well.

`zfs_vdev_cache_size` indeed is set to zero, so `zfs_vdev_cache_max` and `zfs_vdev_cache_bshift` have no influence on zfs by default.

I settled on switching off the arc prefetcher by setting `zfs_prefetch_disable`. Which removes the unnecessary prefetching for me.

Is there anything I can do to optimize the prefetching for my usecase?

**Comment by amotin** [comment]
I may be wrong, but I think you may also misinterpret the zfs.prefetch_* counters.  As I understand the code, when speculative prefetcher issues read for data that is not in ARC, it ends up accounted as zfs.prefetch_data_miss, but it does not mean prefetch is useless, only that the prefetch itself missed the ARC, that is kind of expected, since hit there would mean CPU waste.
