### ISSUE TITLE
arc_shrink() shrinks MRU only

### ISSUE THREAD

**Issue by thegreatgazoo** [zfsonlinux/zfs#2167]
In change:
https://github.com/prakashsurya/zfs/commit/cb737c7a830148c680912f84bf5dd7eff997bc6e
The arc_p was shrank based on the bytes argument in a same way as arc_c.

Suppose:
1. arc_c == 2000M, arc_p == 1000M, i.e. we have a workload where the MRU/MFU ratio is 1.
2. Now arc_shrink(bytes==500M) is called.
3. New arc_c is 2000M - 500M = 1500M. New arc_p is 1000M - 500M = 500M.
                                                                                                                                                                
Now the MRU/MFU ratio has dropped to 500/1000 = 0.5, while the workload hasn't changed - i.e. the MRU cache has taken all the hit of -500M while the MFU hasn't seen any change.

In the Illumos source:
http://src.illumos.org/source/xref/illumos-gate/usr/src/uts/common/fs/zfs/arc.c#2171                                                                            

atomic_add_64(&arc_p, -(arc_p >> arc_shrink_shift));                                                                                                            
                       
I.e. the arc_p is reduced by the same ratio as the arc_c. And MRU/MFU = arc_p/(c - arc_p), so it follows that the MRU/MFU would stay intact. Actually the zfsonlinux code works the same way when arc_shrink() is called with bytes=0. So I think it's ideal to keep the MRU/MFU ratio intact - i.e. both the MRU and MFU should be reduced in size.

**Comment by behlendorf** [comment]
To be resolved in #3533.
