### ISSUE TITLE
Note the requirements for a "in-tree kernel builtin module building" for ZFS + SPL

### ISSUE THREAD

**Issue by peterbowey** [zfsonlinux/zfs#2172]
Looking at these given steps (for creating in-tree kernel builtin module kernel build" for ZFS + SPL):

Original ZFS and SPL references are here:

A) https://github.com/zfsonlinux/zfs/commit/4ab8a725ce8a2bcf26a9df6902f8ee893e62fe6e
B) https://github.com/zfsonlinux/spl/commit/744038069d3dc65e721b5b8cc5c37d8c7fcbd8c0

However, there are some extra notes to add to the above A) + B) references: (as I found during using using the given A) + B) guides)

1) A "in-tree builtin module 'zfs + spl' build" requires "CONFIG_KALLSYMS" in the kernel. See: https://github.com/zfsonlinux/spl/issues/338

2) Additionally, The kernel setup requires to have enabled: A) Solaris Porting Layer (CONFIG_SPL), B) ZFS filesystem support (CONFIG_ZFS), and C) EFI GUID Partition support (CONFIG_EFI_PARTITION)

**Comment by Freeaqingme** [comment]
Does this happen to be documented somewhere? I surely would be interested in making a kernel build that includes ZFS. If not, I can always give it some shots and document it somewhere of course... :)

**Comment by behlendorf** [comment]
@Freeaqingme it's not particularly well documented but it would be a great addition to the wiki if you'd like to write something up.  The process is straight forward and there is a [simple script](https://github.com/zfsonlinux/zfs-buildbot/blob/master/scripts/bb-build-linux.sh) which is used by the buildbot to make sure we don't break this functionality.
