### ISSUE TITLE
Include debug information in all builds

### ISSUE THREAD

**Issue by jvsalo** [zfsonlinux/zfs#2173]
Richard Yao suggested we should make sure that ZoL modules always contain debug info to allow debugging crashes, eg. figuring out line numbers, with gdb. On some build systems this works, but on others (eg. my Debian DKMS) you get

```
Reading symbols from /lib/modules/3.2.0-4-amd64/updates/dkms/zfs.ko...(no debugging symbols found)...done.
(gdb) list *(arc_read+0x5fe)
No symbol table is loaded.  Use the "file" command.
```

**Comment by behlendorf** [comment]
Closing as unnecessary until I hear otherwise.
