### ISSUE TITLE
Rollback must invalidate mmap'd pages

### ISSUE THREAD

**Issue by alexfouche** [zfsonlinux/zfs#2186]
Rollback does not always rollback

Using MongoDB (i believe it is mmaped), i update some records, then fsync+lock, then issue a `zfs snapshot`, then unlock DB. I also tried with process stop and restart instead of fsync+lock. Repeat multiple times

When i issue a `zfs rollback` with or without `-r` depending of the rollback i try to restore, i can still see the newer DB records. DB file mdate also shows files are not restored. When i look into `.zfs/snapshot/...` DB files, i can see that they are correct for the point in time the snapshot was made.

If instead i was not using MongoDB, but simply touching or overwriting some files from shell commands, rollback works fine. But if at some point i start MongoDB, stop it, and try to rollback, then rollback does not rollback. Filesystem is not busy (tested with lsof), and `zfs rollback -r` shows no error

I tried with explicitely unmounting the zfs filesystem, then rollback, then mounting, and this works. I believe then the issue is about auto-remount when restoring a snapshot. In my case, there was never anything keeping the filesystem busy (tested with `lsof`), yet restored snapshot would not show

Maybe this is related to #1214.

Here are steps to reproduce:

``` bash
now=`date +%F_%H:%M:%S`

# Insert data
mongo db2 --quiet <<EOF
    db.now.drop()
    db.now.save({now:"$now"})
EOF

# Stop or fsync+lock
service mongod stop
sleep 3

# Do snapshot
zfs snapshot zfs/mongo_data@$now

# restart for next insert
service mongod start
sleep 1

# REPEAT AGAIN
```

``` bash
pwd
/zfs

service mongod stop
Stopping mongod:                                           [  OK  ]

lsof -nP |grep mongo_data
# <- no output, no open files on this filesystem

zfs list -t snapshot
NAME                                 USED  AVAIL  REFER  MOUNTPOINT
zfs/mongo_data@2014-03-13_09:02:29   180K      -   228K  -
zfs/mongo_data@2014-03-13_09:02:37   184K      -   232K  -
zfs/mongo_data@2014-03-13_09:02:47   184K      -   232K  -
zfs/mongo_data@2014-03-13_09:02:54   120K      -   232K  -

# Current value in DB
strings /zfs/mongo_data/db2.* |grep 2014
2014-03-13_09:02:54

# Restore snapshot
zfs rollback -r zfs/mongo_data@2014-03-13_09:02:47
#  <- no output, no error

# Current value in DB is NOT RESTORED !
strings /zfs/mongo_data/db2.* |grep 2014
2014-03-13_09:02:54  # <- OLD VALUE !

# What is in the snapshot
strings /zfs/mongo_data/.zfs/snapshot/2014-03-13_09\:02\:47/db2.* |grep 2014
2014-03-13_09:02:47  # <- yet the snapshot has the correct point in time value

# Explicitely umount+mount, even afterwards solves issue
zfs umount zfs/mongo_data
zfs mount zfs/mongo_data
strings /zfs/mongo_data/db2.* |grep 2014
2014-03-13_09:02:47  # <- FINALLY MY SNAPSHOT WAS CORRECTLY RESTORED !
```

**Comment by behlendorf** [comment]
Closing.  The solution mentioned above is recommended and things have been further improved by commit 8614ddf9b42d7aca60f7a4218b62f3c5957fe5a0.

**Comment by 4Ykw** [comment]
Hi there,

I have encountered a problem with a similar situation with a memory-mapped file, where the app could still find non-rolled back data in memory, and this solution worked out.

I am using the ubuntu 20 version:
```
zfs --version
zfs-0.8.3-1ubuntu12.14
zfs-kmod-2.1.4-0ubuntu0.1
```

Is there a way to create zfs pools/vols that mandatory invalidate caches specifically for the volumes/pools in question for this reason? if this could be a property that will bring peace of mind for most problems like this.

Cheers

**Comment by ryao** [comment]
@alexfouche This is a super late reply, but all of the dirty is safely in ARC, so there is no safety issue from invalidating the page cache.

@4Ykw Please file a new issue for the regression. It will not get much attention in an old closed issue.

**Comment by ryao** [comment]
> Is there a way to create zfs pools/vols that mandatory invalidate caches specifically for the volumes/pools in question for this reason?

It already invalidates as needed. In the new issue, please include information on how to reproduce this.

**Comment by behlendorf** [comment]
This may be related to #13608
