### ISSUE TITLE
ZFS takes 5-6 seconds to import and mount a pool

### ISSUE THREAD

**Issue by turl** [zfsonlinux/zfs#2190]
I'm filling this issue by @ryao's request

    Turl> I'm playing with systemd-analyze
    Turl> and saw zfs takes 5-6s to start
    Turl> is that a normal time for it?
    Turl> I have a single disk pool
    ryao> Turl: One of the OSv developers had this problem, but I did not think it affected us.
    ryao> Turl: What could be happening is that zil replay is being done on import because there was no flush on export.
    ryao> I think raphaelsc in #osv was the person who caught it. I have a fast SSD, so I had not noticed. File an issue.
    ryao> Turl: What I described is the issue OSv had.

![plot](https://f.cloud.github.com/assets/619540/2417937/5b7a5bb8-ab30-11e3-864b-f79c762dcad0.png)

The ZFS unit contains

    ExecStart=/usr/bin/modprobe zfs
    ExecStart=/usr/bin/zpool import -c /etc/zfs/zpool.cache -aN
    ExecStart=/usr/bin/zfs mount -a
    ExecStart=/usr/bin/zfs share -a
    ExecStop=/usr/bin/zfs umount -a

I'm using Arch Linux, ZoL 0.6.2, Linux 3.13.6

**Comment by behlendorf** [comment]
Import times may be further reduced with #4794.

**Comment by behlendorf** [comment]
Closing.  Import time have been reduced considerably by various commits.  There's definitely still room for improvement in some areas but lets file new issues as needed.
