### ISSUE TITLE
Never boots, saying rpool is in use from other system

### ISSUE THREAD

**Issue by jgoerzen** [zfsonlinux/zfs#2195]
On every boot on this system, I get this message:

```
FAIL: zpool import -c /etc/zfs/zpool.cache -N rpool . Retrying...
FAIL: zpool import -N -d /dev/disk/by-id rpool . Retrying...

Command: zpool import -N -d /dev/disk/by-id rpool
Message: cannot import 'rpool': pool may be in use from other system
use '-f' to import anyway
Error: 1

Manually import the root pool at the command prompt then exit.
Hint: Try: zpool import -R / -N rpool
```

Running:

```
zpool imprt -fR / -N rpool; exit
```

lets the system boot.

This issue was first reported on the mailing list at https://groups.google.com/a/zfsonlinux.org/d/topic/zfs-discuss/RggMKyj-64A/discussion but no resolution was reached.  I am unsure if it is a zfs or zfs-pkg bug.  I do not appear to have hostid issues.  The disk is never in use by another system.

**Comment by behlendorf** [comment]
Closing, this was fixed in master.
