### ISSUE TITLE
dm_crypt -> ZFS -> NFS: copying data -> stalls

### ISSUE THREAD

**Issue by cousins** [zfsonlinux/zfs#2203]
I've been testing a ZFS pool made of disks that have been encrypted with dm_crypt (using cryptsetup and LUKS) on CentOS 6.4 and 6.5 systems. All goes fine until I NFS mount the volume and start copying data to it. After a short while the transfer stalls out and it actually stalls out the whole interface on the ZFS/NFS server such that other communication going over the same network interface stall too. 

I have tried it with a raidz2 pool and a single drive on two different servers. One is with zfs 0.6.1 and the other is 0.6.2.

I first thought it was dm-crypt and NFS somehow having troubles but then I tried it with an XFS file system instead and it was fine. I should mention that CPU load isn't a problem.

I am exporting the ZFS volume in /etc/exports as opposed to using sharenfs as I was never able to get good results with sharenfs. 

I can supply more details but I first wanted to know if this rings a bell with anyone? 

Thanks,

Steve

**Comment by kpande** [comment]
closing as stale
