### ISSUE TITLE
High CPU Load caused machine to stop.

### ISSUE THREAD

**Issue by pozar** [zfsonlinux/zfs#2208]
I am running Ubunut 13.10 server with ..

Meta:         1
Name:         zfs
Branch:       1.0
Version:      0.6.2
Release:      1~saucy
Release-Tags: relext

I suspect that with some high I/O load the array may have gotten into some strange state so that the bringing up the box again and when it tries to mount the pool it creates a high load (>35) and blocks ZFS processes...

[  722.193597] INFO: task txg_sync:2388 blocked for more than 120 seconds.
[  722.193610] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  722.193623] txg_sync        D ffff88043ed94580     0  2388      2 0x00000000
[  722.193628]  ffff8803d05f5bc8 0000000000000046 ffff8803d05f5fd8 0000000000014580
[  722.193635]  ffff8803d05f5fd8 0000000000014580 ffff880415adddc0 ffff88043ed94e28
[  722.193641]  ffff88040ceac9d8 ffff88040ceaca08 0000000000000001 0000000000000002
[  722.193647] Call Trace:
[  722.193653]  [<ffffffff816ea87d>] io_schedule+0x9d/0x130
[  722.193667]  [<ffffffffa03cfe0d>] cv_wait_common+0x9d/0x1a0 [spl]
[  722.193673]  [<ffffffff81085580>] ? wake_up_atomic_t+0x30/0x30
[  722.193686]  [<ffffffffa03cff68>] __cv_wait_io+0x18/0x20 [spl]
[  722.193733]  [<ffffffffa05d4c23>] zio_wait+0x103/0x1c0 [zfs]
[  722.193778]  [<ffffffffa0570356>] dsl_scan_sync+0x466/0xa60 [zfs]
[  722.193827]  [<ffffffffa0580354>] spa_sync+0x474/0xae0 [zfs]
[  722.193835]  [<ffffffff810b7ae8>] ? ktime_get_ts+0x48/0xe0
[  722.193886]  [<ffffffffa058fc92>] txg_sync_thread+0x302/0x580 [zfs]
[  722.193937]  [<ffffffffa058f990>] ? txg_quiesce_thread+0x380/0x380 [zfs]
[  722.193950]  [<ffffffffa03c871a>] thread_generic_wrapper+0x7a/0x90 [spl]
[  722.193962]  [<ffffffffa03c86a0>] ? __thread_exit+0xa0/0xa0 [spl]
[  722.193969]  [<ffffffff810847b0>] kthread+0xc0/0xd0
[  722.193976]  [<ffffffff810846f0>] ? kthread_create_on_node+0x120/0x120
[  722.193981]  [<ffffffff816f516c>] ret_from_fork+0x7c/0xb0
[  722.193988]  [<ffffffff810846f0>] ? kthread_create_on_node+0x120/0x120
[  722.193992] INFO: task spa_async:2464 blocked for more than 120 seconds.
[  722.194005] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  722.194018] spa_async       D ffff88043edd4580     0  2464      2 0x00000000
[  722.194023]  ffff8803ae85ddd0 0000000000000046 ffff8803ae85dfd8 0000000000014580
[  722.194029]  ffff8803ae85dfd8 0000000000014580 ffff880415fd2ee0 ffffffffa0610f20
[  722.194035]  ffffffffa0610f24 ffff880415fd2ee0 00000000ffffffff ffffffffa0610f28
[  722.194041] Call Trace:
[  722.194048]  [<ffffffff816eb4d9>] schedule_preempt_disabled+0x29/0x70
[  722.194054]  [<ffffffff816e951f>] __mutex_lock_slowpath+0x13f/0x1c0
[  722.194107]  [<ffffffffa0587030>] ? spa_vdev_resilver_done+0x140/0x140 [zfs]
[  722.194114]  [<ffffffff816e890f>] mutex_lock+0x1f/0x2f
[  722.194162]  [<ffffffffa058722c>] spa_async_thread+0x1fc/0x280 [zfs]
[  722.194169]  [<ffffffff81091c55>] ? set_user_nice+0xd5/0x180
[  722.194217]  [<ffffffffa0587030>] ? spa_vdev_resilver_done+0x140/0x140 [zfs]
[  722.194230]  [<ffffffffa03c871a>] thread_generic_wrapper+0x7a/0x90 [spl]
[  722.194242]  [<ffffffffa03c86a0>] ? __thread_exit+0xa0/0xa0 [spl]
[  722.194248]  [<ffffffff810847b0>] kthread+0xc0/0xd0
[  722.194255]  [<ffffffff810846f0>] ? kthread_create_on_node+0x120/0x120
[  722.194261]  [<ffffffff816f516c>] ret_from_fork+0x7c/0xb0
[  722.194267]  [<ffffffff810846f0>] ? kthread_create_on_node+0x120/0x120
pozar@FS:~$ 

The work around was to bring up FreeBSD 10, do a force import on the array and export the array.  Ubuntu/LoZ was able to import the array at that point with out the blocking.

Anything else you need to help on this?

Tim

**Comment by behlendorf** [comment]
This is believed to be resolved in master.

**Comment by pozar** [comment]
When did this get "fixed".  A couple of months ago, I ran into the problem again.  I am also wondering if this is related to say slow I/O.  I have since purchased an LSI SAS/SATA controller with 8 lanes of SATA on it.  Will install and try to replicate.
