### ISSUE TITLE
zfs destroy causes "dataset is busy" although all descriptors are closed

### ISSUE THREAD

**Issue by arturpzol** [zfsonlinux/zfs#2219]
Hello 

I test ZOL 0.6.3 from repository and have problem with destroying zvol although all descriptors are closed. I use iSCSI SCST with kernel 3.10.

Scenario:
I have two zvols. iSCSI initiator is connected to iSCSI SCST host with ZOL 0.6.3. Write operation is running from initiator. I get error when I try to remove zvols:

root@localhost:~# /root/remove_target "ap" && dmesg -c &&  /usr/sbin/zfs destroy Pool-0/2 && /usr/sbin/zfs destroy Pool-0/1

[ 9234.298245] iscsi-scst: Deleting session b000037010040 with initiator iqn.1991-05.com.microsoft:win-55uao1vsoip (ffff88000baa5500)
[ 9234.410776] scst: Waiting for 2 active commands to complete... This might take few minutes for disks or few hours for tapes, if you use long executed commands, like REWIND or FORMAT. In case, if you have a hung user space device (i.e. made using scst_user module) not responding to any commands, if might take virtually forever until the corresponding user space program recovers and starts responding or gets killed.
[ 9235.221206] scst: All active commands completed
[ 9235.225090] scst: Removed LUN 1 from group ap (target ap)
[ 9235.391611] dev_vdisk: Detached virtual device 5c79653767732f41 ("/dev/Pool-0/2")
[ 9235.391628] scst: Detached from virtual device 5c79653767732f41 (id 22)
[ 9235.391632] dev_vdisk: Virtual device 5c79653767732f41 unregistered
[ 9235.517433] scst: Removed LUN 0 from group ap (target ap)
[ 9235.631875] dev_vdisk: Detached virtual device acdf7fd661376d7c ("/dev/Pool-0/1")
[ 9235.631893] scst: Detached from virtual device acdf7fd661376d7c (id 21)
[ 9235.631896] dev_vdisk: Virtual device acdf7fd661376d7c unregistered
[ 9235.747694] scst: Target ap for template iscsi unregistered successfully
cannot destroy 'Pool-0/2': dataset is busy

Please note that SCST handlers and iSCSI target are removed before attempt to destroy zvols as dmesg showed.

When I try to add sleep before destroying zvol everything works:
root@localhost:~# /root/remove_target "ap" && dmesg -c && sleep 1 &&  /usr/sbin/zfs destroy Pool-0/2 && /usr/sbin/zfs destroy Pool-0/1

I suppose that ZOL need to synchronize data for some time after remove the iSCSI target but can I check if all operations are finished? Is sleep only one solution? 

Thanks in advance

**Comment by behlendorf** [comment]
Is this still an issue in the latest master source?

**Comment by behlendorf** [comment]
Closing as out of date.
