### ISSUE TITLE
filesystems disappearing on reboot

### ISSUE THREAD

**Issue by ldonzis** [zfsonlinux/zfs#2224]
Sorry if this is a duplicate, but I've searched and can't find anything exactly like this.  And sorry for the lack of details, but I think I can reproduce it as it's happened twice.

We have two NAS servers that are sync'ed by almost continuous replication of snapshots, and it works very well.

However, after rebooting the secondary server (the one that's running zfs recv), a couple of filesystems have vanished.  (zfs list does not show them.)  However, doing a zfs create on one of the missing ones does not return any error, yet the created filesystem still doesn't show up.  Attempting to destroy the filesystem says that it doesn't exist.  The only recovery I've found so far is to destroy the parent filesystem, then re-create the parent and children, and then do a full replication.

It's entirely possible/likely that a recv was in progress when a "reboot" command was issued, which may or may not be related.  If you have any suggestions for obtaining better information that would be useful, I'm willing to try it.

Thanks,
lew

**Comment by behlendorf** [comment]
Closing as out of date.
