### ISSUE TITLE
Vdev states remain ONLINE when disks were removed from system

### ISSUE THREAD

**Issue by ab-oe** [zfsonlinux/zfs#2245]
Hello,
I've noticed strange behavior with Adaptec 3805 controller. I created a pool with one raidz1 vdev then I removed two disks. Both disks are removed from system and all their symlinks from /dev are removed. When I tried to write data to them I/O errors occurred and pool has been suspended but zpool status shows that pool and removed devices are online. 

zpool status
  pool: Pool1
 state: ONLINE
status: One or more devices are faulted in response to IO failures.
action: Make sure the affected devices are connected, then run 'zpool clear'.
   see: http://zfsonlinux.org/msg/ZFS-8000-HC
  scan: none requested
config:

```
NAME                              STATE     READ WRITE CKSUM
Pool1                             ONLINE       0    35     0
  raidz1-0                        ONLINE       0    52     0
    scsi-SAdaptec_vol01_8AD15019  ONLINE       3    61     0
    scsi-SAdaptec_vol00_D6995019  ONLINE       3    65     0
    scsi-SAdaptec_vol02_D3216019  ONLINE       0     0     0
```

errors: 18 data errors, use '-v' for a list

I did the same test with iSCSI devices and after I/O operation removed disks are marked as unavailable.

Tests has been done on the latest ZFS version from git repository.

**Comment by behlendorf** [comment]
Commit 976246fadde25790cec3de50c01c689d98d84e0c will now fault vdevs which experience a certain number of IO or checksum errors within a certain time interval.
