### ISSUE TITLE
oops while replacing disk

### ISSUE THREAD

**Issue by iceisfun** [zfsonlinux/zfs#2267]
events leading up to oops

Hardware configuration
Areca 1680 controller with 20x1.5tb seagate drives connected
1 Pool - raidz3, 1 SSD cache

scrub on tank
disk sdl fails
controller throws sdl also
physically replace sdl
linux sees new sdl as the correct new drive

root@iceisfunzfs:~# zpool replace -f tank /dev/sdl /dev/sdl

Message from syslogd@iceisfunzfs at Apr 20 17:02:47 ...
 kernel:[68476.606813] Oops: 0000 [#1] SMP

Message from syslogd@iceisfunzfs at Apr 20 17:02:47 ...
 kernel:[68476.606938] Stack:

Message from syslogd@iceisfunzfs at Apr 20 17:02:47 ...
 kernel:[68476.606957] Call Trace:

Message from syslogd@iceisfunzfs at Apr 20 17:02:47 ...
 kernel:[68476.607126] Code: c4 fe 48 8b 3d db d3 03 00 e8 19 96 c4 fe e8 52 4b 00 00 58 5b 5d 41 5c 41 5d e9 ac 2f fb ff 48 ff cf be 30 02 00 00 48 c1 ef 09 <48> 8b 3c fd f0 76 5c a1 e9 4f 82 c4 fe 55 b9 a5 06 00 00 45 31

Message from syslogd@iceisfunzfs at Apr 20 17:02:47 ...
 kernel:[68476.607176] CR2: ffffffffa15e76e8

Apr 20 17:00:06 iceisfunzfs kernel: [68316.253397] sd 0:0:2:6: Attached scsi generic sg11 type 0
Apr 20 17:00:06 iceisfunzfs kernel: [68316.253418] sd 0:0:2:6: [sdl] physical block alignment offset: 512
Apr 20 17:00:06 iceisfunzfs kernel: [68316.253423] sd 0:0:2:6: [sdl] 2930277168 512-byte logical blocks: (1.50 TB/1.36 TiB)
Apr 20 17:00:06 iceisfunzfs kernel: [68316.253566] sd 0:0:2:6: [sdl] Write Protect is off
Apr 20 17:00:06 iceisfunzfs kernel: [68316.253784] sd 0:0:2:6: [sdl] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
Apr 20 17:00:07 iceisfunzfs kernel: [68316.477506]  sdl: sdl1 sdl9
Apr 20 17:00:07 iceisfunzfs kernel: [68316.479778] sd 0:0:2:6: [sdl] Attached SCSI disk
Apr 20 17:02:43 iceisfunzfs kernel: [68472.994095]  sdl: sdl1 sdl9
Apr 20 17:02:47 iceisfunzfs kernel: [68476.606807] PGD 1607067 PUD 160b063 PMD 1f51b7067 PTE 0
Apr 20 17:02:47 iceisfunzfs kernel: [68476.606817] CPU 3 
Apr 20 17:02:47 iceisfunzfs kernel: [68476.606818] Modules linked in: iscsi_trgt(O) crc32c nfsd nfs nfs_acl auth_rpcgss lockd fscache sunrpc loop zfs(P) zunicode(P) zavl(P) zcommon(P) znvpair(P) snd_pcm spl(O) snd_page_alloc i2c_i801 snd_timer zlib_deflate snd soundcore evdev serio_raw psmouse iTCO_wdt iTCO_vendor_support pcspkr processor i2c_core thermal_sys coretemp asus_atk0110 button ext4 crc16 jbd2 mbcache sg sd_mod crc_t10dif ata_generic pata_jmicron uhci_hcd r8169 mii ahci libahci ata_piix firewire_ohci mpt2sas raid_class scsi_transport_sas libata firewire_core crc_itu_t atl1e ehci_hcd arcmsr scsi_mod usbcore usb_common [last unloaded: scsi_wait_scan]
Apr 20 17:02:47 iceisfunzfs kernel: [68476.606868] 
Apr 20 17:02:47 iceisfunzfs kernel: [68476.606871] Pid: 14126, comm: vdev_open/0 Tainted: P           O 3.2.0-4-amd64 #1 Debian 3.2.54-2 System manufacturer System Product Name/P5Q PRO TURBO
Apr 20 17:02:47 iceisfunzfs kernel: [68476.606878] RIP: 0010:[<ffffffffa158ab47>]  [<ffffffffa158ab47>] zio_buf_alloc+0xc/0x19 [zfs]
Apr 20 17:02:47 iceisfunzfs kernel: [68476.606895] RSP: 0018:ffff8800559cdd08  EFLAGS: 00010217
Apr 20 17:02:47 iceisfunzfs kernel: [68476.606898] RAX: ffffffffffffe000 RBX: ffff8800793e88f0 RCX: 0000000000000017
Apr 20 17:02:47 iceisfunzfs kernel: [68476.606902] RDX: 00000000007fffff RSI: 0000000000000230 RDI: 0000000000003fff
Apr 20 17:02:47 iceisfunzfs kernel: [68476.606905] RBP: 0000000000800000 R08: ffffc90018743000 R09: 0000000000002000
Apr 20 17:02:47 iceisfunzfs kernel: [68476.606909] R10: 0000000000000000 R11: 0000000000000000 R12: ffff88013d477000
Apr 20 17:02:47 iceisfunzfs kernel: [68476.606912] R13: ffff88020c410000 R14: ffff8800c74b9120 R15: 000000000000c441
Apr 20 17:02:47 iceisfunzfs kernel: [68476.606916] FS:  0000000000000000(0000) GS:ffff88021fd80000(0000) knlGS:0000000000000000
Apr 20 17:02:47 iceisfunzfs kernel: [68476.606920] CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
Apr 20 17:02:47 iceisfunzfs kernel: [68476.606923] CR2: ffffffffa15e76e8 CR3: 0000000001605000 CR4: 00000000000406e0
Apr 20 17:02:47 iceisfunzfs kernel: [68476.606927] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
Apr 20 17:02:47 iceisfunzfs kernel: [68476.606930] DR3: 0000000000000000 DR6: 00000000ffff0ff0 DR7: 0000000000000400
Apr 20 17:02:47 iceisfunzfs kernel: [68476.606934] Process vdev_open/0 (pid: 14126, threadinfo ffff8800559cc000, task ffff8800c74b9120)
Apr 20 17:02:47 iceisfunzfs kernel: [68476.606940]  ffffffffa158c43a ffff8800793e88f0 0000000000020000 0000000000000001
Apr 20 17:02:47 iceisfunzfs kernel: [68476.606946]  ffff8801f51ff800 ffff8800c74b9120 ffffffffa158c895 ffff88013d477000
Apr 20 17:02:47 iceisfunzfs kernel: [68476.606951]  ffff88020a888b80 ffff8800926d88f0 0000000000000000 0000000000000002
Apr 20 17:02:47 iceisfunzfs kernel: [68476.606972]  [<ffffffffa158c43a>] ? zio_vdev_io_start+0xce/0x220 [zfs]
Apr 20 17:02:47 iceisfunzfs kernel: [68476.606988]  [<ffffffffa158c895>] ? zio_nowait+0xf9/0x11b [zfs]
Apr 20 17:02:47 iceisfunzfs kernel: [68476.607008]  [<ffffffffa155629f>] ? vdev_probe+0x187/0x1af [zfs]
Apr 20 17:02:47 iceisfunzfs kernel: [68476.607028]  [<ffffffffa1557121>] ? vdev_accessible+0x49/0x49 [zfs]
Apr 20 17:02:47 iceisfunzfs kernel: [68476.607047]  [<ffffffffa15581f8>] ? vdev_set_state+0x95/0x1b5 [zfs]
Apr 20 17:02:47 iceisfunzfs kernel: [68476.607067]  [<ffffffffa1558c20>] ? vdev_open+0x2ff/0x36a [zfs]
Apr 20 17:02:47 iceisfunzfs kernel: [68476.607086]  [<ffffffffa1559362>] ? vdev_open_child+0x19/0x2c [zfs]
Apr 20 17:02:47 iceisfunzfs kernel: [68476.607093]  [<ffffffffa01d7770>] ? taskq_thread+0x290/0x3e6 [spl]
Apr 20 17:02:47 iceisfunzfs kernel: [68476.607099]  [<ffffffff8103f6ba>] ? try_to_wake_up+0x197/0x197
Apr 20 17:02:47 iceisfunzfs kernel: [68476.607105]  [<ffffffffa01d74e0>] ? task_done+0x110/0x110 [spl]
Apr 20 17:02:47 iceisfunzfs kernel: [68476.607110]  [<ffffffff8105f681>] ? kthread+0x76/0x7e
Apr 20 17:02:47 iceisfunzfs kernel: [68476.607115]  [<ffffffff81356ef4>] ? kernel_thread_helper+0x4/0x10
Apr 20 17:02:47 iceisfunzfs kernel: [68476.607119]  [<ffffffff8105f60b>] ? kthread_worker_fn+0x139/0x139
Apr 20 17:02:47 iceisfunzfs kernel: [68476.607123]  [<ffffffff81356ef0>] ? gs_change+0x13/0x13
Apr 20 17:02:47 iceisfunzfs kernel: [68476.607174]  RSP <ffff8800559cdd08>
Apr 20 17:02:47 iceisfunzfs kernel: [68476.607180] ---[ end trace 7e218a74c2fdcf82 ]---
root@iceisfunzfs:~#

**Comment by behlendorf** [comment]
Closing as out of date.
