### ISSUE TITLE
Importing pools with vdev leaves on end of disk partitions fails on udev symlinks.

### ISSUE THREAD

**Issue by dscherger** [zfsonlinux/zfs#2271]
single disk pool "backup" on /dev/sdg2
last partition of disk with no trailing space

zpool import backup succeeds and imports with /dev/sdg2
zpool import -d /dev/disk/by-id backup fails 

import by id fails when ata-... or wwn-.. whole device symlinks for /dev/sdg exist

removing whole device symlinks in /dev/disk/by-id and leaving only partition symlinks allows the by-id import to work

**Comment by kpande** [comment]
this was fixed some time ago with additional checks during `zpool import`, please reopen if it is still a problem in your configuration.
