### ISSUE TITLE
zraid2: uncorrectable I/O failure after deleting huge number of corrupt files

### ISSUE THREAD

**Issue by aer71** [zfsonlinux/zfs#2281]
Summary: zraid2 pool with 8x 2TB and 4x 4TB disks. All disks show "ONLINE". Import hangs with "uncorrectable I/O failure". Pool was partially corrupted during simultaneous replacement of 4 disks (although no issues were reported at the time). After replacement, scrub ran at 100k/sec. Many files reported data errors, but many files were still intact and readable. I cancelled the scrub and deleted all files known to be corrupt. After a reboot, pool is inaccessible.

os: Ubuntu 13.10, linux-3.11.0-18-generic, x64
mem: 8GB
pool: raidz2 ("tank3")
mobo: ASUS E45M1-I DELUXE
storage: 4 disks via SATA3 on mobo, 8 disks (originally via SAS/SATA3 AOC-SASLP-MV8, also tried eSATA)

The pool had 12x 2TB disks. I connected 4x 4TB disks (so there were 16 disks connected at the same time) and issued four "zpool replace" commands. At some point, one of the 2TB disks (not sure if it was one of the ones being replaced) went offline (not unusual), and the server was rebooted to bring it back online. So there was some resilvering activity in the middle. All four replacements completed, the old 2TB disks were disconnected, and I started a full scrub.

This scrub went unbelievably slowly, around 100k/sec, and after a few days it was up to 3 or 4% done with a LOT of data errors being reported. I began to think that the slowness of the scrub was partly caused by the number of data errors, so I made a list of all the corrupted files and then created a script to delete them all. I was prepared to accept some data loss, and many of the files were backed up or otherwise replaceable. After deleting around 250,000 files, I rebooted the machine, and since that point the pool has been completely inaccessible.

The error is: SPLError: 4180:0:(spl-err.c:67:vcmn_err()) WARNING: Pool 'tank3' has encountered an uncorrectable I/O failure and has been suspended.

I've tried connecting the disks two different ways: AOC-SASLP-MV8 (original config), and RaidSonic ICY BOX IB-3640SU3 (eSATA).
I've tried removing the zpool.cache file and reimporting. 
I've tried importing the pool via FreeBSD 10. I can't use OpenSolaris etc because it's already level 5000.

If it's an IO fault with one of the disks, I can try unplugging that disk, but I don't know which disk could be causing the problem and it might be more than one. I would have to try 78 different combinations.

I'm mentally prepared for the possibility that I have to wipe and start again, and I don't care about the media files (music, TV, movies), but I'd really rather salvage as much of my other data as possible.

Hindsight: I should have run a full scrub _before_ replacing any disks, replaced each disk separately, and scrubbed after each replacement. But in 6 years I haven't had any serious issues with ZFS, and I was impatient...

SLAB: https://gist.github.com/aer71/11366313
ARCSTATS: https://gist.github.com/aer71/11366429
DMIDECODE: https://gist.github.com/aer71/11366322
DMESG: https://gist.github.com/aer71/11366335
IOSTAT: https://gist.github.com/aer71/11366375
IMPORT: https://gist.github.com/aer71/11366406
STATUS: https://gist.github.com/aer71/11366466

**Comment by behlendorf** [comment]
Closing as stale.
