### ISSUE TITLE
BUG: on import of damaged pool

### ISSUE THREAD

**Issue by kkretschmer** [zfsonlinux/zfs#2289]
I get a kernel BUG when trying to import a pool that is probably damaged. Running zdb on this pool consumes all of the machine’s 8 GiB of RAM and gets OOM-killed.

Versions:
- kernel 3.13.10-200.fc20.x86_64 (Fedora 20)
- spl-0.6.2-36-g703371d
- zfs-0.6.2-261-g1758498

The pool consist of a single mirror vdev made up of two partitions (160 GiB) on two Samsung 840 Pro SSDs. I saved images of the two partitions. I tried importing with only one partition available (tested both) and with zfs_recover=1 – same result. This pool contains the system’s root filesystem, so I cannot access the latest logs at the moment. The system was running Gentoo using the RHEL6-based OpenVZ kernel with git versions of spl and zfs from late December 2013 at the time of the crash, I can find out the specific versions if it would help.

Full information: http://www.apc.univ-paris7.fr/Downloads/astrog/kkretsch/zfs/
- dmesg
- zdb -ii
- zdb -l
- partial output of zdb

abbreviated dmesg output:

vgaarb: bridge control possible 0000:05:01.0
uhci_hcd: USB Universal Host Controller Interface driver
[  260]    32   260    10498      321      24        0             0 rpcbind
SPL: using hostid 0xa8c01300
BUG: unable to handle kernel paging request at 00000000000020ec
IP: [<ffffffffa00056ec>] spl_kmem_cache_alloc+0x3c/0xd50 [spl]
PGD 20bcd3067 PUD 20be35067 PMD 0 
Oops: 0002 [#1] SMP 
Modules linked in: zfs(POF) ata_generic pata_acpi firewire_ohci e1000e skge firewire_core crc_itu_t pata_atiixp usb_storage ptp pps_core mvsas 3w_9xxx libsas scsi_transport_sas sunrpc zunicode(POF) zavl(POF) zcommon(POF) znvpair(POF) spl(OF) [last unloaded: zfs]
CPU: 0 PID: 2067 Comm: zpool Tainted: PF          O 3.13.10-200.fc20.x86_64 #1
Hardware name: System manufacturer System Product Name/M2R32-MVP, BIOS 1009    10/30/2007
task: ffff88003415d640 ti: ffff88020b64e000 task.ti: ffff88020b64e000
RIP: 0010:[<ffffffffa00056ec>]  [<ffffffffa00056ec>] spl_kmem_cache_alloc+0x3c/0xd50 [spl]
RSP: 0018:ffff88020b64f438  EFLAGS: 00010246
RAX: 00000000f98da800 RBX: 000000000000008c RCX: ffffffffa04034e0
RDX: 0000000000000000 RSI: 0000000000000230 RDI: 000000000000008c
RBP: ffff88020b64f4f8 R08: 7461bd8cd2a21367 R09: 7461bd8cd2a21367
R10: ffff88020b64f508 R11: ffff8800340aa0a8 R12: 0000000000000001
R13: ffff880078d04d60 R14: 0000000000000230 R15: 00000000000020ec
FS:  00007f7ac255fbc0(0000) GS:ffff88021fc00000(0000) knlGS:0000000000000000
CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
CR2: 00000000000020ec CR3: 000000020b1e2000 CR4: 00000000000007f0
Stack:
 ffff88020b64f488 ffffffff810a6ab6 ffffffff8101b1c3 ffff88020b64f460
 ffffffff8101b239 ffff88020fb6ecc0 ffff88021fc145f8 ffff88021fc14580
 0000000000000001 0000000000000001 ffff88020b64f4d8 ffffffff810a730e
Call Trace:
 [<ffffffff810a6ab6>] ? dequeue_entity+0x106/0x530
 [<ffffffff8101b1c3>] ? native_sched_clock+0x13/0x80
 [<ffffffff8101b239>] ? sched_clock+0x9/0x10
 [<ffffffff810a730e>] ? dequeue_task_fair+0x42e/0x640
 [<ffffffff810125f9>] ? __switch_to+0x169/0x4c0
 [<ffffffffa03c3653>] zio_buf_alloc+0x23/0x30 [zfs]
 [<ffffffffa0326325>] arc_get_data_buf.isra.19+0x345/0x4b0 [zfs]
 [<ffffffffa0328b3c>] arc_buf_alloc+0xdc/0x110 [zfs]
 [<ffffffffa0329379>] arc_read+0x369/0x8e0 [zfs]
 [<ffffffffa000fe67>] ? cv_wait_common+0xb7/0x1a0 [spl]
 [<ffffffffa0388da0>] ? vdev_mirror_worst_error+0x80/0x80 [zfs]
 [<ffffffffa0341422>] traverse_prefetch_metadata+0x92/0xa0 [zfs]
 [<ffffffffa03414d4>] prefetch_dnode_metadata+0xa4/0xc0 [zfs]
 [<ffffffffa0341c64>] traverse_visitbp+0x524/0x740 [zfs]
 [<ffffffffa0341b7b>] traverse_visitbp+0x43b/0x740 [zfs]
 [<ffffffffa0341b7b>] traverse_visitbp+0x43b/0x740 [zfs]
 [<ffffffffa0341b7b>] traverse_visitbp+0x43b/0x740 [zfs]
 [<ffffffffa0341b7b>] traverse_visitbp+0x43b/0x740 [zfs]
 [<ffffffffa0341b7b>] traverse_visitbp+0x43b/0x740 [zfs]
 [<ffffffffa0341b7b>] traverse_visitbp+0x43b/0x740 [zfs]
 [<ffffffffa03424f5>] traverse_dnode+0x75/0x120 [zfs]
 [<ffffffffa0341d71>] traverse_visitbp+0x631/0x740 [zfs]
 [<ffffffffa0009476>] ? taskq_dispatch+0x66/0x320 [spl]
 [<ffffffffa0341fee>] traverse_impl+0x16e/0x340 [zfs]
 [<ffffffffa0342204>] traverse_dataset+0x44/0x50 [zfs]
 [<ffffffffa036bd10>] ? spa_l2cache_drop+0x90/0x90 [zfs]
 [<ffffffffa0342388>] traverse_pool+0x178/0x1b0 [zfs]
 [<ffffffffa036bd10>] ? spa_l2cache_drop+0x90/0x90 [zfs]
 [<ffffffffa036bd10>] ? spa_l2cache_drop+0x90/0x90 [zfs]
 [<ffffffffa03718c2>] spa_load+0x1882/0x1e40 [zfs]
 [<ffffffffa000ad29>] ? taskq_create+0x319/0x4f0 [spl]
 [<ffffffffa0371ecd>] spa_load_best+0x4d/0x260 [zfs]
 [<ffffffffa002f314>] ? zpool_get_rewind_policy+0x194/0x1b0 [zcommon]
 [<ffffffffa037358a>] spa_import+0x16a/0x6b0 [zfs]
 [<ffffffffa03a1544>] zfs_ioc_pool_import+0xe4/0x120 [zfs]
 [<ffffffffa03a3e96>] zfsdev_ioctl+0x466/0x4e0 [zfs]
 [<ffffffff811cbae8>] do_vfs_ioctl+0x2d8/0x4a0
 [<ffffffff811bab4e>] ? ____fput+0xe/0x10
 [<ffffffff811cbd31>] SyS_ioctl+0x81/0xa0
 [<ffffffff816928fe>] ? do_page_fault+0xe/0x10
 [<ffffffff81696e69>] system_call_fastpath+0x16/0x1b
Code: 55 41 54 53 48 89 fb 48 81 ec 98 00 00 00 f6 05 5a 49 01 00 01 74 0d f6 05 5a 49 01 00 08 0f 85 db 00 00 00 4c 8d bb 60 20 00 00 <f0> ff 83 60 20 00 00 fa 66 66 90 66 66 90 48 8d 45 b0 4c 8d 9b 
RIP  [<ffffffffa00056ec>] spl_kmem_cache_alloc+0x3c/0xd50 [spl]
 RSP <ffff88020b64f438>
CR2: 00000000000020ec
---[ end trace 8616b5f0a4958f47 ]---
BUG: unable to handle kernel paging request at 00000000000020ec
IP: [<ffffffffa00056ec>] spl_kmem_cache_alloc+0x3c/0xd50 [spl]
PGD 0 
Oops: 0002 [#2] SMP 
Modules linked in: zfs(POF) ata_generic pata_acpi firewire_ohci e1000e skge firewire_core crc_itu_t pata_atiixp usb_storage ptp pps_core mvsas 3w_9xxx libsas scsi_transport_sas sunrpc zunicode(POF) zavl(POF) zcommon(POF) znvpair(POF) spl(OF) [last unloaded: zfs]
CPU: 1 PID: 87 Comm: spl_system_task Tainted: PF     D    O 3.13.10-200.fc20.x86_64 #1
Hardware name: System manufacturer System Product Name/M2R32-MVP, BIOS 1009    10/30/2007
task: ffff88020f9c5640 ti: ffff880035048000 task.ti: ffff880035048000
RIP: 0010:[<ffffffffa00056ec>]  [<ffffffffa00056ec>] spl_kmem_cache_alloc+0x3c/0xd50 [spl]
RSP: 0018:ffff8800350496c8  EFLAGS: 00010246
RAX: 00000000f98da800 RBX: 000000000000008c RCX: ffffffffa04034e0
RDX: 0000000000000000 RSI: 0000000000000230 RDI: 000000000000008c
RBP: ffff880035049788 R08: 7461bd8cd2a21367 R09: 7461bd8cd2a21367
R10: ffff880035049798 R11: ffff8800340aa0a8 R12: 0000000000000001
R13: ffff8800812a0658 R14: 0000000000000230 R15: 00000000000020ec
FS:  00007f7ac255fbc0(0000) GS:ffff88021fc80000(0000) knlGS:0000000000000000
CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
CR2: 00000000000020ec CR3: 000000020b1e2000 CR4: 00000000000007e0
Stack:
 ffff880035049718 ffffffff810a6ab6 ffffffff8101b1c3 ffff8800350496f0
 ffffffff8101b239 ffff88020f9c56a8 ffff88021fc945f8 ffff88021fc94580
 0000000000000001 0000000000000001 ffff880035049768 ffffffff810a730e
Call Trace:
 [<ffffffff810a6ab6>] ? dequeue_entity+0x106/0x530
 [<ffffffff8101b1c3>] ? native_sched_clock+0x13/0x80
 [<ffffffff8101b239>] ? sched_clock+0x9/0x10
 [<ffffffff810a730e>] ? dequeue_task_fair+0x42e/0x640
 [<ffffffff810125b6>] ? __switch_to+0x126/0x4c0
 [<ffffffffa03c3653>] zio_buf_alloc+0x23/0x30 [zfs]
 [<ffffffffa0326325>] arc_get_data_buf.isra.19+0x345/0x4b0 [zfs]
 [<ffffffffa0328b3c>] arc_buf_alloc+0xdc/0x110 [zfs]
 [<ffffffffa0329379>] arc_read+0x369/0x8e0 [zfs]
 [<ffffffffa03c3653>] ? zio_buf_alloc+0x23/0x30 [zfs]
 [<ffffffffa0326335>] ? arc_get_data_buf.isra.19+0x355/0x4b0 [zfs]
 [<ffffffffa0341422>] traverse_prefetch_metadata+0x92/0xa0 [zfs]
 [<ffffffffa03414d4>] prefetch_dnode_metadata+0xa4/0xc0 [zfs]
 [<ffffffffa0341c64>] traverse_visitbp+0x524/0x740 [zfs]
 [<ffffffffa0341b7b>] traverse_visitbp+0x43b/0x740 [zfs]
 [<ffffffffa0341b7b>] traverse_visitbp+0x43b/0x740 [zfs]
 [<ffffffffa0341b7b>] traverse_visitbp+0x43b/0x740 [zfs]
 [<ffffffffa0341b7b>] traverse_visitbp+0x43b/0x740 [zfs]
 [<ffffffffa0341b7b>] traverse_visitbp+0x43b/0x740 [zfs]
 [<ffffffffa0341b7b>] traverse_visitbp+0x43b/0x740 [zfs]
 [<ffffffffa03424f5>] traverse_dnode+0x75/0x120 [zfs]
 [<ffffffffa0341d71>] traverse_visitbp+0x631/0x740 [zfs]
 [<ffffffffa0342443>] traverse_prefetch_thread+0x83/0xc0 [zfs]
 [<ffffffffa03414f0>] ? prefetch_dnode_metadata+0xc0/0xc0 [zfs]
 [<ffffffffa000a5fd>] taskq_thread+0x21d/0x480 [spl]
 [<ffffffff8109e410>] ? wake_up_state+0x20/0x20
 [<ffffffffa000a3e0>] ? taskq_cancel_id+0x1e0/0x1e0 [spl]
 [<ffffffff8108f2f2>] kthread+0xd2/0xf0
 [<ffffffff8108f220>] ? insert_kthread_work+0x40/0x40
 [<ffffffff81696dbc>] ret_from_fork+0x7c/0xb0
 [<ffffffff8108f220>] ? insert_kthread_work+0x40/0x40
Code: 55 41 54 53 48 89 fb 48 81 ec 98 00 00 00 f6 05 5a 49 01 00 01 74 0d f6 05 5a 49 01 00 08 0f 85 db 00 00 00 4c 8d bb 60 20 00 00 <f0> ff 83 60 20 00 00 fa 66 66 90 66 66 90 48 8d 45 b0 4c 8d 9b 
RIP  [<ffffffffa00056ec>] spl_kmem_cache_alloc+0x3c/0xd50 [spl]
 RSP <ffff8800350496c8>
CR2: 00000000000020ec
---[ end trace 8616b5f0a4958f48 ]---

**Comment by behlendorf** [comment]
This kind of damage is now handled gracefully, see commit 5f6d0b6f5aa9af2ee5be74ac415a574b732c2c0f.
