### ISSUE TITLE
Not setting whole_disk flag when using /dev/mapper devices

### ISSUE THREAD

**Issue by stevecs** [zfsonlinux/zfs#2296]
On ubuntu 12.04LTS  w/ 0.6.2 stable
Linux loki 3.2.0-61-generic #92-Ubuntu SMP Mon Mar 31 23:47:59 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
ii  libzfs1                              0.6.2-1~precise                   Native ZFS filesystem library for Linux
ii  mountall                             2.36.4-zfs2                       filesystem mounting tool
ii  ubuntu-zfs                           7~precise                         Native ZFS filesystem metapackage for Ubuntu.
ii  zfs-dkms                             0.6.2-1~precise                   Native ZFS filesystem kernel modules for Linux
ii  zfsutils                             0.6.2-1~precise                   Native ZFS management utilities for Linux

I have all my devices in /dev/mapper configured through multipath.conf, each drive is a sas dual ported drive configured with load balancing between the two paths.   I creating a new array with:

zpool  create -f -O atime=off -O mountpoint=none -O canmount=off -O sync=disabled -o ashift=12 -o version=28 scratch0 \
 raidz1 \
        /dev/mapper/c5t0d01 \
        /dev/mapper/c5t0d02 \
        /dev/mapper/c5t0d03 \
        /dev/mapper/c5t0d04 \
        /dev/mapper/c5t0d05 \
        /dev/mapper/c5t0d06 \
        /dev/mapper/c5t0d07 \
        /dev/mapper/c5t0d08 \
        /dev/mapper/c5t0d09 \
        /dev/mapper/c5t0d10 \
        /dev/mapper/c5t0d11 \
        /dev/mapper/c5t0d12 \
        /dev/mapper/c5t0d13 \
        /dev/mapper/c5t0d14 \
        /dev/mapper/c5t0d15 \
        /dev/mapper/c5t0d16 \
        /dev/mapper/c5t0d17 \
        /dev/mapper/c5t0d18 \
        /dev/mapper/c5t0d19 \
        /dev/mapper/c5t0d20 \
        /dev/mapper/c5t0d21 \
        /dev/mapper/c5t0d22 \
        /dev/mapper/c5t0d23 \
        /dev/mapper/c5t0d24 \
        /dev/mapper/c5t0d25
   --------

zdb shows that the drives were NOT added as full disks:

scratch0:
    version: 28
    name: 'scratch0'
    state: 0
    txg: 4
    pool_guid: 13749966790813321487
    hostname: 'loki'
    vdev_children: 1
    vdev_tree:
        type: 'root'
        id: 0
        guid: 13749966790813321487
        create_txg: 4
        children[0]:
            type: 'raidz'
            id: 0
            guid: 15025852784433851352
            nparity: 1
            metaslab_array: 31
            metaslab_shift: 36
            ashift: 12
            asize: 7499880857600
            is_log: 0
            create_txg: 4
            children[0]:
                type: 'disk'
                id: 0
                guid: 16225799384315451584
                path: '/dev/mapper/c5t0d01'
                whole_disk: 0
                create_txg: 4
            children[1]:
                type: 'disk'
                id: 1
                guid: 6597105523044823550
                path: '/dev/mapper/c5t0d02'
                whole_disk: 0
                create_txg: 4
            children[2]:
                type: 'disk'
                id: 2
                guid: 650442448426342640
                path: '/dev/mapper/c5t0d03'
                whole_disk: 0
                create_txg: 4
            children[3]:
                type: 'disk'
                id: 3
                guid: 13662897834876943385
                path: '/dev/mapper/c5t0d04'
                whole_disk: 0
                create_txg: 4
   (snip)

  -----
ls -l /dev/mapper/c5*
brw-rw---- 1 root disk 252,   0 May  3 09:45 c5t0d01
brw-rw---- 1 root disk 252,   4 May  3 09:45 c5t0d02
brw-rw---- 1 root disk 252,   1 May  3 09:45 c5t0d03
brw-rw---- 1 root disk 252,   2 May  3 09:45 c5t0d04
brw-rw---- 1 root disk 252,   3 May  3 09:45 c5t0d05
brw-rw---- 1 root disk 252,   5 May  3 09:45 c5t0d06
brw-rw---- 1 root disk 252,   6 May  3 09:45 c5t0d07
brw-rw---- 1 root disk 252,   7 May  3 09:45 c5t0d08
brw-rw---- 1 root disk 252,   8 May  3 09:45 c5t0d09
brw-rw---- 1 root disk 252,   9 May  3 09:45 c5t0d10
brw-rw---- 1 root disk 252,  10 May  3 09:45 c5t0d11
brw-rw---- 1 root disk 252,  11 May  3 09:45 c5t0d12
brw-rw---- 1 root disk 252,  12 May  3 09:45 c5t0d13
brw-rw---- 1 root disk 252,  13 May  3 09:45 c5t0d14
brw-rw---- 1 root disk 252,  14 May  3 09:45 c5t0d15
brw-rw---- 1 root disk 252,  16 May  3 09:45 c5t0d16
brw-rw---- 1 root disk 252,  15 May  3 09:45 c5t0d17
brw-rw---- 1 root disk 252,  17 May  3 09:45 c5t0d18
brw-rw---- 1 root disk 252,  18 May  3 09:45 c5t0d19
brw-rw---- 1 root disk 252,  19 May  3 09:45 c5t0d20
brw-rw---- 1 root disk 252,  20 May  3 09:45 c5t0d21
brw-rw---- 1 root disk 252,  21 May  3 09:45 c5t0d22
brw-rw---- 1 root disk 252,  22 May  3 09:45 c5t0d23
brw-rw---- 1 root disk 252,  23 May  3 09:45 c5t0d24
brw-rw---- 1 root disk 252,  24 May  3 09:45 c5t0d25

 ============

I have nothing in the vdev.conf file, everything is controlled through multipath.conf.   My guess is that zpool is mis-understanding /dev/mapper devices and thinks that they are partitions instead of raw devices.

**Comment by behlendorf** [comment]
Closing as documentation.
