### ISSUE TITLE
Document or distribute memory fragmentation workarounds in 0.6.3

### ISSUE THREAD

**Issue by bassu** [zfsonlinux/zfs#2298]
I assume that one of the major issues in ZOL related ARC over-consumption and Linux memory management, causing deadlocks, has not been fully addressed yet. 

If that's the case, I suggest that there should be either a script to workaround by dropping cache, sync, etc. to be distributed in 0.6.3 or at least you guys should document the problem with more detail along with possible workarounds in the upcoming release so people know how to deal with it.

**Comment by behlendorf** [comment]
As of 0.6.4.2 the ARC issues have been significantly mitigated and further improvements are expected as the ABD patches are merged.
