### ISSUE TITLE
Deadlock with crashdump

### ISSUE THREAD

**Issue by lukemarsden** [zfsonlinux/zfs#2304]
I've started collecting kernel crashdumps and dmesg output of the ZoL deadlocks I'm able to reproduce:

http://hybridcluster.net/zol-hangs/201405060819/

This is now on Ubuntu 14.04, with kernel `3.13.0-24-generic #47-Ubuntu SMP`, and the following `zfs` module info:

```
filename:       /lib/modules/3.13.0-24-generic/updates/dkms/zfs.ko
version:        0.6.2-2.1~trusty~13.gbp7d6f55
license:        CDDL
author:         Sun Microsystems/Oracle, Lawrence Livermore National Laboratory
description:    ZFS
srcversion:     8EAC8D11923CD437A7B0573
```

The machine was potentially running concurrent snapshot/destroy/mount/unmount operations at the time of the deadlock.  Hopefully the crashdump will elucidate us.

**Comment by behlendorf** [comment]
Closing as a duplicate of #2301 was has been resolved.
