### ISSUE TITLE
Hang under memory pressure

### ISSUE THREAD

**Issue by andreevmipt** [zfsonlinux/zfs#2308]
Hang (sometimes complete, sometimes recoverable with SysRq + E) on a computer with 4G phys memory under  heavy memory pressure.
3.14.2-aufs #4 SMP PREEMPT
spl: 0.6.2-36_g703371d
zfs: 0.6.2-274_g2c33b91

Following kernel params set:
Hang detection timeout reduced to 20 sec (for debug)
CONFIG_TRANSPARENT_HUGEPAGE is not set
vm.dirty_ratio = 10

What else can be done to reduce chance to get this condition?

[ 2341.763203] INFO: task systemd:1 blocked for more than 20 seconds.
[ 2341.763207]       Tainted: P        W  O 3.14.2-aufs #4
[ 2341.763208] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 2341.763209] systemd         D ffff88012fb93280  4072     1      0 0x00000000
[ 2341.763213]  ffff880129ac3628 0000000000000002 ffff880129ae0000 ffff880129ac3fd8
[ 2341.763215]  0000000000013280 0000000000013280 ffff880129ae0000 ffff8800c6d1b890
[ 2341.763217]  ffff8800c6d1b890 ffff880129ae0000 ffff8800c6d1b898 0000000000000246
[ 2341.763220] Call Trace:
[ 2341.763226]  [<ffffffff8176a41e>] schedule_preempt_disabled+0x2e/0x80
[ 2341.763229]  [<ffffffff8176cedf>] __mutex_lock_slowpath+0x12f/0x3a0
[ 2341.763231]  [<ffffffff8176d173>] mutex_lock+0x23/0x33
[ 2341.763251]  [<ffffffffa01550e5>] vdev_queue_io+0x85/0x180 [zfs]
[ 2341.763262]  [<ffffffffa018be57>] zio_buf_free+0xc07/0x17b0 [zfs]
[ 2341.763273]  [<ffffffffa018ea96>] zio_nowait+0xb6/0x180 [zfs]
[ 2341.763284]  [<ffffffffa015413f>] vdev_config_sync+0xaff/0xd80 [zfs]
[ 2341.763295]  [<ffffffffa0153780>] ? vdev_config_sync+0x140/0xd80 [zfs]
[ 2341.763305]  [<ffffffffa018bea7>] zio_buf_free+0xc57/0x17b0 [zfs]
[ 2341.763315]  [<ffffffffa018ea96>] zio_nowait+0xb6/0x180 [zfs]
[ 2341.763321]  [<ffffffffa00f7b8a>] arc_read+0x31a/0x960 [zfs]
[ 2341.763327]  [<ffffffffa00fe414>] dbuf_read+0x254/0xd00 [zfs]
[ 2341.763334]  [<ffffffffa00fee3a>] dbuf_read+0xc7a/0xd00 [zfs]
[ 2341.763340]  [<ffffffffa00fef36>] dbuf_hold_impl+0x76/0xa0 [zfs]
[ 2341.763346]  [<ffffffffa00ff1eb>] dbuf_hold+0x1b/0x30 [zfs]
[ 2341.763353]  [<ffffffffa0105efd>] dmu_buf_hold+0x29d/0x6b0 [zfs]
[ 2341.763360]  [<ffffffffa01068b7>] dmu_read+0x97/0x2d0 [zfs]
[ 2341.763362]  [<ffffffff8176cd09>] ? mutex_unlock+0x9/0x10
[ 2341.763373]  [<ffffffffa017a75d>] zfs_getpage+0x12d/0x200 [zfs]
[ 2341.763383]  [<ffffffffa0193d40>] ? zpl_putpage+0x220/0x830 [zfs]
[ 2341.763392]  [<ffffffffa0193d67>] zpl_putpage+0x247/0x830 [zfs]
[ 2341.763395]  [<ffffffff81134fca>] read_cache_pages+0xba/0x120
[ 2341.763404]  [<ffffffffa0193bb9>] zpl_putpage+0x99/0x830 [zfs]
[ 2341.763406]  [<ffffffff81134df4>] __do_page_cache_readahead+0x1d4/0x290
[ 2341.763408]  [<ffffffff8113555c>] ra_submit+0x1c/0x20
[ 2341.763410]  [<ffffffff8112a5a5>] filemap_fault+0x385/0x420
[ 2341.763412]  [<ffffffff8114ff1e>] __do_fault+0x6e/0x530
[ 2341.763414]  [<ffffffff81153893>] handle_mm_fault+0x1c3/0xcb0
[ 2341.763416]  [<ffffffff8176e249>] ? _raw_spin_unlock_irqrestore+0x19/0x40
[ 2341.763419]  [<ffffffff811db390>] ? timerfd_poll+0x50/0x60
[ 2341.763421]  [<ffffffff811d7e5f>] ? ep_send_events_proc+0x9f/0x1c0
[ 2341.763423]  [<ffffffff817717bc>] __do_page_fault+0x16c/0x580
[ 2341.763426]  [<ffffffff810f7087>] ? acct_account_cputime+0x17/0x20
[ 2341.763428]  [<ffffffff81084b37>] ? account_user_time+0x87/0x90
[ 2341.763430]  [<ffffffff8176e213>] ? _raw_spin_unlock+0x13/0x30
[ 2341.763432]  [<ffffffff8108502f>] ? vtime_account_user+0x4f/0x60
[ 2341.763434]  [<ffffffff81771bee>] do_page_fault+0x1e/0x70
[ 2341.763436]  [<ffffffff8176ec92>] page_fault+0x22/0x30
[ 2341.763441] INFO: task kswapd0:62 blocked for more than 20 seconds.
[ 2341.763442]       Tainted: P        W  O 3.14.2-aufs #4
[ 2341.763443] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 2341.763444] kswapd0         D ffff88012664be00  3464    62      2 0x00000000
[ 2341.763446]  ffff880124fad968 0000000000000002 ffff880129390000 ffff880124fadfd8
[ 2341.763448]  0000000000013280 0000000000013280 ffff880129390000 ffff8800c6a4e428
[ 2341.763450]  ffff8800c6a4e268 ffff8800c6a4e430 0000000000000000 ffff8800c6a4e3c0
[ 2341.763452] Call Trace:
[ 2341.763454]  [<ffffffff81769ea4>] schedule+0x24/0x70
[ 2341.763459]  [<ffffffffa006916d>] __cv_destroy+0x19d/0x1d0 [spl]
[ 2341.763462]  [<ffffffff810927e0>] ? prepare_to_wait_event+0xf0/0xf0
[ 2341.763466]  [<ffffffffa00691b0>] __cv_wait+0x10/0x20 [spl]
[ 2341.763476]  [<ffffffffa0149423>] txg_wait_open+0x83/0xb0 [zfs]
[ 2341.763485]  [<ffffffffa01110c5>] dmu_tx_wait+0x305/0x310 [zfs]
[ 2341.763487]  [<ffffffff8176cd09>] ? mutex_unlock+0x9/0x10
[ 2341.763501]  [<ffffffffa0111165>] dmu_tx_assign+0x95/0xc90 [zfs]
[ 2341.763520]  [<ffffffffa01809cb>] zfs_inactive+0x15b/0x210 [zfs]
[ 2341.763530]  [<ffffffffa019524f>] zpl_vap_init+0x64f/0x7b0 [zfs]
[ 2341.763532]  [<ffffffff811ac77b>] evict+0xab/0x1a0
[ 2341.763534]  [<ffffffff811ac8a1>] dispose_list+0x31/0x40
[ 2341.763535]  [<ffffffff811ad832>] prune_icache_sb+0x42/0x50
[ 2341.763538]  [<ffffffff81195a10>] super_cache_scan+0x100/0x170
[ 2341.763540]  [<ffffffff8113881b>] shrink_slab_node+0x14b/0x2f0
[ 2341.763543]  [<ffffffff810d236f>] ? css_next_descendant_pre+0x1f/0x60
[ 2341.763545]  [<ffffffff8113a8c6>] shrink_slab+0x86/0x180
[ 2341.763547]  [<ffffffff8113d1c5>] kswapd_shrink_zone+0x125/0x1c0
[ 2341.763550]  [<ffffffff8113e786>] kswapd+0x4c6/0x890
[ 2341.763552]  [<ffffffff8113e2c0>] ? mem_cgroup_shrink_node_zone+0x180/0x180
[ 2341.763555]  [<ffffffff8107094f>] kthread+0xdf/0x100
[ 2341.763557]  [<ffffffff8108519e>] ? arch_vtime_task_switch+0x8e/0xa0
[ 2341.763559]  [<ffffffff81070870>] ? kthread_create_on_node+0x1a0/0x1a0
[ 2341.763561]  [<ffffffff81775efc>] ret_from_fork+0x7c/0xb0
[ 2341.763563]  [<ffffffff81070870>] ? kthread_create_on_node+0x1a0/0x1a0
[ 2341.763571] INFO: task z_rd_int/0:691 blocked for more than 20 seconds.
[ 2341.763572]       Tainted: P        W  O 3.14.2-aufs #4
[ 2341.763573] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 2341.763574] z_rd_int/0      D ffff88012fa13280  5304   691      2 0x00000000
[ 2341.763576]  ffff880035d25cd8 0000000000000002 ffff8800c651c6f0 ffff880035d25fd8
[ 2341.763578]  0000000000013280 0000000000013280 ffff8800c651c6f0 ffff8800c6d1b890
[ 2341.763580]  ffff8800c6d1b890 ffff8800c651c6f0 ffff8800c6d1b898 0000000000000246
[ 2341.763582] Call Trace:
[ 2341.763584]  [<ffffffff8176a41e>] schedule_preempt_disabled+0x2e/0x80
[ 2341.763586]  [<ffffffff8176cedf>] __mutex_lock_slowpath+0x12f/0x3a0
[ 2341.763588]  [<ffffffff8176d173>] mutex_lock+0x23/0x33
[ 2341.763599]  [<ffffffffa0155226>] vdev_queue_io_done+0x46/0x36d0 [zfs]
[ 2341.763601]  [<ffffffff8176cd09>] ? mutex_unlock+0x9/0x10
[ 2341.763611]  [<ffffffffa018bbb0>] zio_buf_free+0x960/0x17b0 [zfs]
[ 2341.763620]  [<ffffffffa018caa6>] zio_execute+0xa6/0x140 [zfs]
[ 2341.763624]  [<ffffffffa0065d38>] taskq_cancel_id+0x2e8/0x490 [spl]
[ 2341.763626]  [<ffffffff81081870>] ? wake_up_state+0x10/0x10
[ 2341.763629]  [<ffffffffa0065b80>] ? taskq_cancel_id+0x130/0x490 [spl]
[ 2341.763631]  [<ffffffff8107094f>] kthread+0xdf/0x100
[ 2341.763633]  [<ffffffff8108519e>] ? arch_vtime_task_switch+0x8e/0xa0
[ 2341.763635]  [<ffffffff81070870>] ? kthread_create_on_node+0x1a0/0x1a0
[ 2341.763637]  [<ffffffff81775efc>] ret_from_fork+0x7c/0xb0
[ 2341.763638]  [<ffffffff81070870>] ? kthread_create_on_node+0x1a0/0x1a0
[ 2341.763640] INFO: task z_rd_int/1:692 blocked for more than 20 seconds.

**Comment by behlendorf** [comment]
Closing as stale.

**Comment by ioquatix** [comment]
I'm almost completely convinced that the problems I was experience was due to faulty hardware.
