### ISSUE TITLE
Exporting a fresh pool causes it to disappear

### ISSUE THREAD

**Issue by tuxoko** [zfsonlinux/zfs#2314]
spl/zfs is on current HEAD
```
$ sudo zpool create p1 sdd -R /mnt
$ sudo zpool export p1
$ sudo zpool import
$
$ sudo zpool create p1 sdd -R /mnt
$ sudo cp asdf /mnt/p1/
$ sudo zpool export p1
$ sudo zpool import
   pool: p1
     id: 5641224663899505410
  state: ONLINE
 action: The pool can be imported using its name or numeric identifier.
 config:

	p1          ONLINE
	  sdd      ONLINE
```

Aside from copy file, create a filesystem also seems to work.

**Comment by tuxoko** [comment]
Some update on this issue.
It seems sometimes creating a fresh pool and export it immediately the partition table is not synced correctly.

So I created a pool qq on /dev/sde and export it.
```
$ sudo zpool create qq /dev/sde
$ sudo zpool export qq
$ sudo zpool import
no pools available to import
$ sudo blkid
/dev/sde1: PARTLABEL="zfs" PARTUUID="36d5e0e9-7f06-1a4b-9a65-fe12f5cff036"
/dev/sde9: PARTUUID="a9b7eb12-7a45-5143-8f5c-e017abf1efb5"
```
Notice there's no `UUID` or `zfs_member` in it.
Now if I supply `-d` option:
```
$ sudo zpool import -d /dev
   pool: qq
     id: 5453390886577953194
  state: ONLINE
 action: The pool can be imported using its name or numeric identifier.
 config:

	qq          ONLINE
	  sde       ONLINE
```
It actually shows up.
And if I import it with `-d` and export it again. blkid becomes normal.
```
$ sudo zpool import -d /dev qq
$ sudo zpool export qq
$ sudo blkid
/dev/sde1: LABEL="qq" UUID="5453390886577953194" UUID_SUB="7913141484346817201" TYPE="zfs_member" PARTLABEL="zfs" PARTUUID="36d5e0e9-7f06-1a4b-9a65-fe12f5cff036"
/dev/sde9: PARTUUID="a9b7eb12-7a45-5143-8f5c-e017abf1efb5"
```

**Comment by behlendorf** [comment]
Or perhaps the blkid cache us stale.   The -d option forces the directory scanning.

**Comment by tuxoko** [comment]
OK, blkid was v2.26.2 on my VM. I tried v2.27 and the issue was gone.

**Comment by behlendorf** [comment]
As an aside, this is the primary reason we've thus far not made blkid mandatory and left it up to the distributions.  There are older versions of blkid out there which can't 100% of the time identify a ZFS label.  Although at this point I'm not sure how many distributions still have that issue.
