### ISSUE TITLE
cannot remove device links for '<ZFS volume>': Device or resource busy: dataset is busy

### ISSUE THREAD

**Issue by jmgobrien** [zfsonlinux/zfs#2315]
Hi,

  While performing a send/receive for a ZFS volume on one server to another a failure occurred. Now I cannot destroy the destination volume as I get the error 'cannot remove device links' as above.

  Is there any way to force the destroy? I've tried using the -f switch and have also rebooted the server (3.2.0-4-amd64 #1 SMP Debian 3.2.57-3 x86_64).

  Regards,
    Gerry

**Comment by behlendorf** [comment]
@jmgobrien were you ever able to destroy the volume?  Has this occurred more than once and is it an issue which still needs to be resolved?

**Comment by behlendorf** [comment]
Closing as stale.
