### ISSUE TITLE
'zpool list' with interval does not refresh properties

### ISSUE THREAD

**Issue by DeHackEd** [zfsonlinux/zfs#2331]
<pre># zpool list -o name,allocated,free,freeing 1
NAME     ALLOC   FREE  FREEING
offsite   484G  1.34T    82.1G
offsite   484G  1.34T    82.1G
offsite   484G  1.34T    82.1G
offsite   484G  1.34T    82.1G
offsite   484G  1.34T    82.1G
offsite   484G  1.34T    82.1G
offsite   484G  1.34T    82.1G
offsite   484G  1.34T    82.1G
offsite   484G  1.34T    82.1G
offsite   484G  1.34T    82.1G
offsite   484G  1.34T    82.1G
offsite   484G  1.34T    82.1G
offsite   484G  1.34T    82.1G
offsite   484G  1.34T    82.1G
^C
</pre>

Expected result: FREEING shrinks with each iteration, ALLOC and FREE change accordingly at least within TXG timeout increments. This mirrors `zpool get all $poolname` behaviour.

Actual result: The same values are always printed each time.

This makes `zpool list` in incremental mode only useful for detecting when the set of imported pools changes.

**Comment by behlendorf** [comment]
@DeHackEd do you know if this is still the case?

**Comment by DeHackEd** [comment]
I don't know when this was fixed, but I just tried it now and it's working correctly.

Closing.

**Comment by behlendorf** [comment]
@DeHackEd me either but I'll take it.
