### ISSUE TITLE
Document hostid configuration

### ISSUE THREAD

**Issue by ryao** [zfsonlinux/zfs#2346]
The system hostid and the initramfs hostid have been observed to fall out of sync on Gentoo. Commit 1cbae971c5ef215d1036b65511a839879e446c4c makes this apparent when previously, nothing wrong would be reported.

Running `printf "$(hostid | sed 's/\([0-9A-F]\{2\}\)/\\x\1/gI')" > /etc/hostid` will make it go away. We should document this somewhere after investigating it more.

**Comment by behlendorf** [comment]
@ryao if you think this should be in 0.6.4 can you open a pull request with the proposed patch.

**Comment by behlendorf** [comment]
Bumping to 0.6.5.  This shouldn't hold up the tag.

**Comment by ilovezfs** [comment]
@ryao Any idea why your command above and the C program on the Arch Wiki (https://wiki.archlinux.org/index.php/Installing_Arch_Linux_on_ZFS#After_the_first_boot) end up outputting /etc/hostid files with different contents?


```
openzfs ~ # rm /etc/hostid
openzfs ~ # hostid
9dd27601
openzfs ~ # cat /etc/hostid
cat: /etc/hostid: No such file or directory
openzfs ~ # ./writehostid 
openzfs ~ # cat /etc/hostid
vҝopenzfs ~ # 
openzfs ~ # hostid
9dd27601
openzfs ~ # printf "$(hostid | sed 's/\([0-9A-F]\{2\}\)/\\x\1/gI')" > /etc/hostid
openzfs ~ # hostid
0176d29d
openzfs ~ # cat /etc/hostid
Òvopenzfs ~ # 
openzfs ~ # ./writehostid 
openzfs ~ # cat /etc/hostid
Òvopenzfs ~ # 
openzfs ~ # hostid
0176d29d
openzfs ~ # rm /etc/hostid
openzfs ~ # hostid
9dd27601
openzfs ~ # ./writehostid 
openzfs ~ # hostid
9dd27601
openzfs ~ # cat /etc/hostid
vҝopenzfs ~ # 
openzfs ~ # 
```

**Comment by behlendorf** [comment]
Closing, the MMP feature includes additional information describing when to set the hostid.
