### ISSUE TITLE
zpool list hangs on gentoo with hardened-sources-3.13.10 and zfs-0.6.2-r5

### ISSUE THREAD

**Issue by THX-1138** [zfsonlinux/zfs#2347]
same machine,same setup works in production with hardened-sources-3.11.7 and zfs-0.6.2-r3
dmesg:
[ 1188.329344] SPL: Loaded module v0.6.2-1
[ 1188.653303] ZFS: Loaded module v0.6.2-1, ZFS pool version 5000, ZFS filesystem version 5
[ 1190.235257] PAX: size overflow detected in function dmu_buf_hold_array_by_dnode /var/tmp/portage/sys-fs/zfs-kmod-0.6.2-r5/work/zfs-zfs-0.6.2/module/zfs/../../module/zfs/dmu.c:399 cicus.464_174 min, count: 2
[ 1190.235263] CPU: 4 PID: 12943 Comm: zpool Tainted: P           O 3.13.10-hardened #2
[ 1190.235265] Hardware name: Intel Corporation S2600GZ/S2600GZ, BIOS SE5C600.86B.02.02.0002.122320131210 12/23/2013
[ 1190.235266]  0000000000000001 ffff881faf6af998 ffffffff81510669 ffff881fbfc8c858
[ 1190.235269]  ffff881f84936e60 ffff881faf6af9a8 ffffffff811450c4 ffff881faf6afa38
[ 1190.235271]  ffffffffa020702e 000000000000001b ffff881fb2d4a710 ffff881fb2d4a710
[ 1190.235274] Call Trace:
[ 1190.235281]  [<ffffffff81510669>] dump_stack+0x46/0x5e
[ 1190.235286]  [<ffffffff811450c4>] report_size_overflow+0x24/0x30
[ 1190.235315]  [<ffffffffa020702e>] dmu_prefetch+0x84e/0xcd0 [zfs]
[ 1190.235321]  [<ffffffffa029f13f>] ? zvol_fini+0xcaf/0x2fd50 [zfs]
[ 1190.235328]  [<ffffffffa0207a49>] dmu_read+0xe9/0x790 [zfs]
[ 1190.235332]  [<ffffffff8112ca21>] ? alloc_pages_current+0xb1/0x180
[ 1190.235336]  [<ffffffff810f0f89>] ? __get_free_pages+0x9/0x50
[ 1190.235342]  [<ffffffffa01529e8>] ? kmem_alloc_debug+0x78/0x140 [spl]
[ 1190.235346]  [<ffffffffa029e5f6>] zvol_fini+0x166/0x2fd50 [zfs]
[ 1190.235351]  [<ffffffffa02b793d>] ? zvol_fini+0x194ad/0x2fd50 [zfs]
[ 1190.235364]  [<ffffffffa0242f8a>] spa_vdev_remove+0xe8a/0x26e0 [zfs]
[ 1190.235375]  [<ffffffffa023ef4e>] ? spa_prop_clear_bootfs+0xe0e/0x10d0 [zfs]
[ 1190.235384]  [<ffffffffa0244248>] spa_vdev_remove+0x2148/0x26e0 [zfs]
[ 1190.235391]  [<ffffffffa0244598>] spa_vdev_remove+0x2498/0x26e0 [zfs]
[ 1190.235394]  [<ffffffff81134e28>] ? check_heap_object+0x48/0x110
[ 1190.235399]  [<ffffffffa02a25e0>] ? zvol_fini+0x4150/0x2fd50 [zfs]
[ 1190.235405]  [<ffffffffa02447ee>] spa_open+0xe/0x20 [zfs]
[ 1190.235416]  [<ffffffffa02763e0>] pool_status_check+0x40/0x290 [zfs]
[ 1190.235421]  [<ffffffffa02a2870>] ? zvol_fini+0x43e0/0x2fd50 [zfs]
[ 1190.235426]  [<ffffffffa02a2870>] ? zvol_fini+0x43e0/0x2fd50 [zfs]
[ 1190.235433]  [<ffffffffa02765d6>] pool_status_check+0x236/0x290 [zfs]
[ 1190.235437]  [<ffffffff8115486b>] do_vfs_ioctl+0x9b/0x770
[ 1190.235440]  [<ffffffff81516628>] ? retint_swapgs+0x9/0xc
[ 1190.235442]  [<ffffffff81516628>] ? retint_swapgs+0x9/0xc
[ 1190.235445]  [<ffffffff81154f8b>] SyS_ioctl+0x4b/0x90
[ 1190.235447]  [<ffffffff81516d8e>] system_call_fastpath+0x16/0x1b

**Comment by cs0rbagomba** [comment]
This is the only open PAX issue left, it would be nice to have ZFS + full PAX.
https://github.com/zfsonlinux/zfs/issues/3032 says "Gentoo packages needlessly require CONFIG_PAX_RANDKSTACK=n", can these 2 issues can be merged?

**Comment by cs0rbagomba** [comment]
Can this be closed as well as the linked issue?

**Comment by prometheanfire** [comment]
I think so

**Comment by behlendorf** [comment]
Yup, closing.  Thanks.
