### ISSUE TITLE
Default zvol_threads and zfs_top_maxinflight values causes heavy load.

### ISSUE THREAD

**Issue by arko-pl** [zfsonlinux/zfs#2352]
Hello,
I use ZFS zvols as SCST targets. There is problem with default zfs parameters, especially zvol_threads and zfs_top_maxinflight (during scrub operation). Value of 32 causes load about 20-30% load and about 50-60% wa on all cores even when compression and deduplication is disabled. This causes various problems on the initiator side. Tested machine has two Intel(R) Xeon(R) CPU E5-2609 CPUs and 128 MB of RAM. I used the latest zfs version from git repository.
Experimentally I changed value of these parameters to 75% of CPU cores count. After this change load and wa dropped down and problem doesn't occur. I also didn't noticed impact on performance.
How new values may impact on ZFS performance?

Also I have question about zfs_arc_max increasing it to about 95% of available RAM caused out of memory errors. I made some changes and set zfs module values as follows:

zfs_arc_max = 60% of RAM memory
zfs_dirty_data_max_percent = 10
zfs_dirty_data_max_max_percent = 15

Should these values prevent me from oom errors?

**Comment by behlendorf** [comment]
Closing.  The zvol threads pool has been eliminated entirely so this shouldn't be an issue any longer.

**Comment by Binarus** [comment]
Please excuse that I am re-activating this one, but I just saw it by accident ...

@behlendorf 
> Closing. The zvol threads pool has been eliminated entirely so this shouldn't be an issue any longer.

But from `man zfs-module-parameters` in an installation of OpenZFS 2.0.0 (which is the newest versions AFAIK):

       zvol_threads (uint)
                   Max number of threads which can handle zvol I/O requests concurrently.

So you state that the thread pool does not exist any more, but the manual still lists the tunable. Where is my misunderstanding?

**Comment by DeHackEd** [comment]
Unwritable module parameters just means they have to be set at module load time and can't be changed dynamically.

As for the zvol's behaviour, I still see zvol threads on my system and the source code says the taskq is still being used.
