### ISSUE TITLE
SPLError: 534:0:(zfs_vfsops.c:400:zfs_space_delta_cb()) SPL PANIC

### ISSUE THREAD

**Issue by mmehnert** [zfsonlinux/zfs#2354]
Today I got the following SPL panic. The pool seems to be without errors, however.
Is that a consistency problem or a bug?

    Jun  2 18:26:21 localhost kernel: [  294.383270] VERIFY3(sa.sa_magic == 0x2F505A) failed (1400610936 == 3100762)
    Jun  2 18:26:21 localhost kernel: [  294.383279] SPLError: 534:0:(zfs_vfsops.c:400:zfs_space_delta_cb()) SPL PANIC
    Jun  2 18:26:21 localhost kernel: [  294.383281] SPL: Showing stack for process 534 
    Jun  2 18:26:21 localhost kernel: [  294.383284] CPU: 0 PID: 534 Comm: txg_sync Tainted: P           O 3.13-1-amd64 #1 Debian 3.13.10-1
    Jun  2 18:26:21 localhost kernel: [  294.383285] Hardware name: Dell Inc. Studio 1537/0P132H, BIOS A08 02/10/2009
    Jun  2 18:26:21 localhost kernel: [  294.383287]  ffffc900c5acfac8 ffffffff814a1997 0000000000000000 ffffffffa01fb50f
    Jun  2 18:26:21 localhost kernel: [  294.383291]  ffffffffa020ec21 0000000000000000 ffffc900ba828200 ffffffffa02ff3b7
    Jun  2 18:26:21 localhost kernel: [  294.383294]  00000000537ba078 0000000000000001 0000000000000000 0000000000000005
    Jun  2 18:26:21 localhost kernel: [  294.383297] Call Trace:
    Jun  2 18:26:21 localhost kernel: [  294.383304]  [<ffffffff814a1997>] ? dump_stack+0x41/0x51
    Jun  2 18:26:21 localhost kernel: [  294.383336]  [<ffffffffa01fb50f>] ? spl_debug_bug+0x6f/0xd0 [spl]
    Jun  2 18:26:21 localhost kernel: [  294.383364]  [<ffffffffa02ff3b7>] ? zfs_space_delta_cb+0x177/0x180 [zfs]
    Jun  2 18:26:21 localhost kernel: [  294.383379]  [<ffffffffa0290bff>] ? dmu_objset_userquota_get_ids+0xbf/0x3f0 [zfs]
    Jun  2 18:26:21 localhost kernel: [  294.383382]  [<ffffffff814a60c9>] ? mutex_lock+0x9/0x25
    Jun  2 18:26:21 localhost kernel: [  294.383398]  [<ffffffffa029e122>] ? dnode_sync+0xb2/0xac0 [zfs]
    Jun  2 18:26:21 localhost kernel: [  294.383415]  [<ffffffffa028fe9c>] ? dmu_objset_sync_dnodes+0xbc/0xe0 [zfs]
    Jun  2 18:26:21 localhost kernel: [  294.383429]  [<ffffffffa0290098>] ? dmu_objset_sync+0x1d8/0x300 [zfs]
    Jun  2 18:26:21 localhost kernel: [  294.383439]  [<ffffffffa027a190>] ? arc_cksum_compute.isra.15+0xa0/0xa0 [zfs]
    Jun  2 18:26:21 localhost kernel: [  294.383450]  [<ffffffffa0279140>] ? arc_evictable_memory+0x80/0x80 [zfs]
    Jun  2 18:26:21 localhost kernel: [  294.383461]  [<ffffffffa027c730>] ? l2arc_read_done+0x3b0/0x3b0 [zfs]
    Jun  2 18:26:21 localhost kernel: [  294.383479]  [<ffffffffa02ab44a>] ? dsl_pool_sync+0x8a/0x450 [zfs]
    Jun  2 18:26:21 localhost kernel: [  294.383498]  [<ffffffffa02c20b6>] ? spa_sync+0x426/0xb00 [zfs]
    Jun  2 18:26:21 localhost kernel: [  294.383503]  [<ffffffff81096b4f>] ? __wake_up+0x2f/0x50
    Jun  2 18:26:21 localhost kernel: [  294.383507]  [<ffffffff810b406d>] ? ktime_get_ts+0x3d/0xe0
    Jun  2 18:26:21 localhost kernel: [  294.383525]  [<ffffffffa02d1b33>] ? txg_sync_thread+0x393/0x5d0 [zfs]
    Jun  2 18:26:21 localhost kernel: [  294.383544]  [<ffffffffa02d17a0>] ? txg_quiesce_thread+0x350/0x350 [zfs]
    Jun  2 18:26:21 localhost kernel: [  294.383552]  [<ffffffffa020238f>] ? thread_generic_wrapper+0x6f/0x80 [spl]
    Jun  2 18:26:21 localhost kernel: [  294.383559]  [<ffffffffa0202320>] ? __thread_exit+0xa0/0xa0 [spl]
    Jun  2 18:26:21 localhost kernel: [  294.383562]  [<ffffffff8107bb51>] ? kthread+0xc1/0xe0
    Jun  2 18:26:21 localhost kernel: [  294.383565]  [<ffffffff8107ba90>] ? kthread_create_on_node+0x180/0x180
    Jun  2 18:26:21 localhost kernel: [  294.383568]  [<ffffffff814aeacc>] ? ret_from_fork+0x7c/0xb0
    Jun  2 18:26:21 localhost kernel: [  294.383570]  [<ffffffff8107ba90>] ? kthread_create_on_node+0x180/0x180

**Comment by behlendorf** [comment]
@mmehnert do you know if this is still an issue in master which can happen under stress?

**Comment by mmehnert** [comment]
I have only seen this on one machine. I actually  destroyed the pool in question about a week ago. I think I did not see that SPL Panic during the last 6 months.

**Comment by behlendorf** [comment]
OK, I haven't heard any new reports of this either and we have made some SA fixes which could explain this.  I'd like to close this out for now but anyone observes it again we can reopen it.
