### ISSUE TITLE
disable modprobe zfs from inside libzfs 

### ISSUE THREAD

**Issue by edamato** [zfsonlinux/zfs#2358]
Hi All,

From what I can see ZFS on linux has at least 3 ways of loading its kernel modules on boot:

/etc/init.d/zfs
/lib/udev/rules.d/90-zfs.rules 
libzfs.so 

Due to (maybe paranoid) HA requirements, I need to make sure that ZFS kernel modules do not load on boot. 

- Specifically if there could be debris on zpool.cache, which could lead to a double activation of a pool in 2 hosts.
- Also because the nodes not running ZFS export their luns via iscsi, and zfs shouldn't touch them unless there's a failover
- so I don't want ZFS modules to be loaded and its caches created and kernel tainting uncecessarily.

I have seen that for 0.6.3 a large code change was done to change the packaging of libzfs, the patch below assumes 0.6.2 codebase

Proposition is to change libzfs not to force the loading of the modules, making it std linux, where modprobes are not done inside a DSO

Alternatively, if this patch is highly undesirable, I could come up with a patch that looks for a file called /etc/zfs/libzfs.conf and put an autoload=no there, so that the library keeps the same functionality but doesn't hardcode the modprobe

```diff
diff -ru zfs-0.6.2.orig/lib/libzfs/libzfs_util.c zfs-0.6.2.new/lib/libzfs/libzfs_util.c
--- zfs-0.6.2.orig/lib/libzfs/libzfs_util.c     2013-07-01 22:19:28.000000000 +0100
+++ zfs-0.6.2.new/lib/libzfs/libzfs_util.c      2014-06-03 18:19:40.271431802 +0100
@@ -675,13 +675,6 @@
 {
        libzfs_handle_t *hdl;
 
-       if (libzfs_load_module("zfs") != 0) {
-               (void) fprintf(stderr, gettext("Failed to load ZFS module "
-                              "stack.\nLoad the module manually by running "
-                              "'insmod <location>/zfs.ko' as root.\n"));
-               return (NULL);
-       }
-
        if ((hdl = calloc(1, sizeof (libzfs_handle_t))) == NULL) {
                return (NULL);
        }
```

Could this patch or other alternatives pls be considered?

thanks,
Eduardo.

**Comment by behlendorf** [comment]
This has been resolved by commit 87abfcba2283bfeb6636caf9aa2a72186d7708c4.  By default modules are no longer automatically loaded as part of `libzfs_init()`.  To make this an easy transition to the new behavior the previous behavior can be re-enabled by setting ZFS_MODULE_LOADING="yes" in the environment.  However, this functionality will be removed in a subsequent release.
