### ISSUE TITLE
systemd unit zfs-import-scan.service fails

### ISSUE THREAD

**Issue by Rudd-O** [zfsonlinux/zfs#2368]
When there are no importable pools, /sbin/zpool import -d .... which is the command that the unit file runs, exits with a status code of 1.

This causes the unit to fail.

That all pools have already been imported should not be an error -- it should be a no-op.

**Comment by behlendorf** [comment]
This behavior was fixed in 0.6.4 by commit 6466b61db6b4def6b077882ebbd4c3e83e917613.
