### ISSUE TITLE
Set fault beacon on drive failure

### ISSUE THREAD

**Issue by behlendorf** [zfsonlinux/zfs#2375]
For JBOD style configurations it's desirable to set the device's fault beacon on drive failures.  This can be done either through proc interface or through the `sg_ses` utilities.  The relevant zed scripts (cmd/zed/zed.d/io-spare.sh), should be updated to take advantage of this functionality.  The tricky bit is to map the device name to an enclosure and slot location.

```
# Set the fault beacon through proc
$ echo 1 >/sys/class/enclosure/6:0:9:0/000/fault

# Set the fault beacon with sg_ses
$ sg_ses --dev-slot-num=0 --set=ident /dev/sg3
$ sg_ses --dev-slot-num=0 --clear=ident /dev/sg3
```

**Comment by cvoltz** [comment]
I'm working on implementing this feature. [identify_failed_drive.feature.txt](https://github.com/zfsonlinux/zfs/files/382233/identify_failed_drive.feature.txt) provides a detailed feature description.

**Comment by rlaager** [comment]
@cvoltz Your description looks solid, except that I disagree that the UID light should be on. I would think only the fault light should be controlled. What is the advantage of adjusting both lights in lock-step? I think the UID should be left for administrator use.

**Comment by joehandzik** [comment]
@rlaager The UID could certainly be dropped, but there is potential value in a large configuration. With the UID + disk FAULT LED, customers know which chassis AND which disk a bit more easily.

**Comment by tonyhutter** [comment]
@cvoltz I'm working on pretty much the same thing at LLNL.  Have you had any luck with using libstoragemgmt to blink the LEDs?  Have you tried it for multipath devices as well?

**Comment by cvoltz** [comment]
I updated the feature specification to remove the references to the UID lights on the drive.

**Comment by behlendorf** [comment]
For anyone following this issue you may want to checkout the latest master source which now has improved infrastructure for generically managing a devices SES LEDs, 1bbd8770490f0e5b8c575865ab70f6853bca2a2a.  The zedlet's environment will now contain a `ZEVENT_VDEV_ENC_SYSFS_PATH` variable when the SES sysfs path can be determined.  This can be used to easily control the LEDs without any additional dependencies beyond the `ses.ko` kernel module.  See the `statechange-led.sh` zedlet as an example.

This infrastructure is still being worked on but any feedback or testing on a wider range of configurations and hardware would be welcome.
