### ISSUE TITLE
Sometimes fails to mount a dataset because "it's not empty"

### ISSUE THREAD

**Issue by FransUrbo** [zfsonlinux/zfs#2382]
I'm filing this on the behalf of people on the mailing list that have (had) this problem. I have been unable to reproduce it reliably but it needs to be tracked.

The latest thread about this is https://groups.google.com/a/zfsonlinux.org/forum/#!topic/zfs-discuss/Ibr2X0VRYRk.

My suspicion is that there's a timing error some where - zfs isn't removing the directory for some reason after it have successfully unmounted the/its dataset.

Lets say you have the following datasets with corresponding mount points (the pool <code>rpool</code> mounted on <code>/rpool</code>):

```
    DATASET         MOUNTPOINT
    dir1            /rpool/dir1
    dir2            /rpool/dir2
    dir3            /rpool/dir3
    dir3/dirA       /rpool/dir3/dirA
    dir3/dirA/dirZ  /rpool/dir3/dirA/dirZ
    dir3/dirB       /rpool/dir3/dirB
    dir4            /rpool/dir4
```

ZFS will first create the mount point and then mount them (one procedure at a time - <code>mkdir /dir1 ; mount dir1 ; mkdir /dir2 ; mount dir2</code> etc) in the order written here, one at a time.

The unmount is in reverse, removing the mount point just after it have unmounted the filesystem - <code>umount dir4 ; rmdir /dir4 ; umount dir3/dirB ; rmdir /dir3/dirB</code> etc..

(And yes, that's <code>;</code>, not <code>&&</code>!)

Now, if (for whatever reason), zfs fails to remove the <code>/dir3/dirA/dirZ</code> directory after its unmounting, the mount procedure at the next boot will be messed up.

It will refuse to mount the <code>dir3/dirA</code> dataset, but _will_ mount the  <code>dir3/dirA/dirZ</code> dataset which _do_ have a (empty) mount point.

In this case, simply unmount <code>dir3/dirA/dirZ</code>, remove the directory <code>/dir3/dirA/dirZ</code> and reissue <code>zfs mount -a</code> should solve this.

Looking at the code, I notice that <code>lib/libzfs/libzfs_mount.c:remove_mountpoint()</code> will call <code>rmdir()</code> but silently ignore any errors.

In this case, this is wrong - we need to know why the <code>rmdir()</code> and possibly retry...

**Comment by behlendorf** [comment]
Anybody know if this is still an issue?

**Comment by UbuntuNewbie** [comment]
not from my side. But i am just a peaceful and happy zfs user, who refrains from using it for system root. But in the time since this was a problem, i cannot recall this ever coming back.

**Comment by jplitza** [comment]
Yes, I still have this issue. Debian Jessie, zfsutils-linux 0.6.5.9-2~bpo8+1
On boot I get the following:
```
Feb 23 08:57:41 yori systemd[1]: Starting Mount ZFS filesystems...
Feb 23 08:57:42 yori zfs[1916]: cannot mount '/srv/data': directory is not empty
```
Because it mounted for example `/srv/data/Audio` (zvol pool/data/Audio) before it did `/srv/data` (zvol pool/data) and created its mountpoint.
