### ISSUE TITLE
Zvol with wrong volblocksize is created when -o volblocksize=size is used instead -b size

### ISSUE THREAD

**Issue by ab-oe** [zfsonlinux/zfs#2393]
Hello,
I've noticed that properties passed in zfs create function are stored as strings in props nvlist but all functions tries to get volblocksize property as uint64_t.  It causes that when zvol is created with command: `zfs create -V 1G -o volblocksize=512 tank/zvol1` volblocksize will be 8192 but zfs get volblocksize will report 512.

For example in zvol_create_cb function there is:
```c
	if (nvlist_lookup_uint64(nvprops,
zfs_prop_to_name(ZFS_PROP_VOLBLOCKSIZE), &volblocksize) != 0)
volblocksize = zfs_prop_default_numeric(ZFS_PROP_VOLBLOCKSIZE);
```
It will fail and volblocksize will be set to default 8192.

**Comment by behlendorf** [comment]
Closing as stale.
