### ISSUE TITLE
Another spl_kmem_cache hang, 0.6.2+HEAD from april

### ISSUE THREAD

**Issue by spacelama** [zfsonlinux/zfs#2394]
Another metadata heavy workload (rsync + a large `find`).  Performance getting worse, cache and buffers down to about 40MB, but free memory up around 800MB (ie, the usual circumstances where ZFS starts to "crash" for me).  Whilst I'm not running 0.6.3, I am running git HEAD from about April after the metadata heavy arc/l2arc fixes were supposedly put in.

spl_kmem_cache taking 100% of 1 core, but some progress being occasionally made.  Until I try to `echo 3 >| /proc/sys/vm/drop_caches` (works first few times).

> top
  PID USER      PR  NI  VIRT  RES  SHR S  %CPU %MEM    TIME+  COMMAND                                       
  991 root      39  19     0    0    0 R  98.9  0.0  62:21.06 spl_kmem_cache/

`iostat -k 1` is showing consistent 300tps and 12MB/s read from the SSD device that is simultaneously my swap, root filesystem (ext4) and SLOG/l2arc.

attached will be sysrq t & sysrq l listings.  Unfortunately, I just lost my last working xterm with a root shell running, so that's probably the final debugging I can get (no remote syslog)

**Comment by behlendorf** [comment]
Closing.  The have been many improvements made to the ARC since 0.6.3 and there are more on the way with the ABD patches.  This should be resolved, however if you're still seeing issue we'll open a new issue for it and track it there.
