### ISSUE TITLE
libspl includes missing prefix

### ISSUE THREAD

**Issue by FransUrbo** [zfsonlinux/zfs#2401]
When doing a 'make install', the libspl includes installs into <code>/usr/local/include/libspl</code> (and with a package without the <code>local/</code> part).

So including

```
#include <libspl/sys/types.h>
```

will give the error

```
/usr/local/include/libspl/sys/types.h:30:26: fatal error: sys/isa_defs.h: No such file or directory
```

Prefixing all the relevant includes with <code>libspl/</code> seems in order.

**Comment by behlendorf** [comment]
This is probably something we should tackle when the spl sources and added to the zfs repository.  That should involve a fair bit of code cleanup and refactoring.
