### ISSUE TITLE
SLOG random write performance much slower than sequential performance

### ISSUE THREAD

**Issue by oliver8888** [zfsonlinux/zfs#2412]
Greetings,

i am trying to understand this SLOG behavior, and i just do not. i suspect this may be aberrant behavior/bug

My system is: a 24GB memory, ubuntu 14.04 -  with zfs 0.6.3, tagretcli to share block devices to clients via 8GB Fibre Channel.

my intention is to create a large high performance zfs block device for write intensive activities.

ZFS options, had previously set into /etc/modules.d/zfsonlinux.conf though they appear still active despite being commented out since prior reboots...
# options zfs zfs_txg_synctime_ms=3000
# options zfs zfs_txg_timeout=3

pool created with ashift=12 ( these are technically 512 byte sector devices)
ZFS Pool
vDev - 2x Pliant 406S SSD (200gb partition - aligned), mirror. 
SLOG - 2x ZeusRAM (6GB partition - aligned), Mirror.

I create a block device from this pool: say 20GB, synch=always, 4kb block size, and shared to client.

on Client i fire up iometer, 100% writes
Sequentially - I can write 4kb @ around 20k iops
Randomly - I can write 4kb @ 3k-5k iops (this actually spikes at times between 0 - 10k at times, but spikes are less frequent).

What i do not understand is if i am watching with "zpool iostat -v 1" the slog gets low numbers of writes/bytes--if memory is correct at about the same MB/s as client see's. the vDev will get about 4x the MB/s as the SLOG, and the writes are continuous to the vDEV. (not on a 3 second tx flush interval). it's like most writes are bypassing the SLOG, and a multiplier of client writes in MB/s are going into each vDEV device. this perplexes me.

If i change an iometer setting on client to write to "Maximum disk Size - Sectors" on the volume--to say 10,000 while still writing randomly, i get the higher performance of around 20k, and more writes to SLOG--and If i continue to increase the "Maximum disk Size - Sectors" to higher values, this performance continues to scale downward.

So my question: is this expected? My understanding is the SLOG should absorb ALL writes regardless of Sequential/random nature, and  at the speed of the slog-- and then flush into the appropriate vDEV's at the transaction group commit intervals. This does not appear to be happening.

also the SSd's backing the vDEV should not be a bottleneck in this scenario as they can write 4k randomly around a around 20k IOPS if i export the bare SSD directly via targetcli, so txcommits should easily keep up....

I apologize at lack of screenshots, or outputs at this post creation-- if there is anything specifically you would like, please let me know and i should be able to get it for you this weekend.

**Comment by bash99** [comment]
@behlendorf 

I also suffer from this problem.
If logbias=latency, what is expect for random async writes? 
for example fio --ioengine=libaio --iodepth=32 --rw=randwrite workloads?

We have a ELK setup. KVM on xfs on zol, randwrite performance is around 1K. 
hardware setup is ssd is intel 3710 200G,  as zil and l2arc for raid10 10K SAS.

Direct test on ssd service can go over 20K iops, test on zvol (blocksize 8k) is around 1K , and most write go to SAS directly when view with ```zpool iostat 5 -v```.

Is it expected performance as zfs is not a ssd cache like bc-cache/flash-cache? or It's a bug in zol?

**Comment by kpande** [comment]
closing as stale, @bash99 your question seems better suited for the [zfs-discuss mailing list](http://list.zfsonlinux.org).
