### ISSUE TITLE
zpool -d /dev/disk/by-id misses partitions

### ISSUE THREAD

**Issue by tomposmiko** [zfsonlinux/zfs#2450]
Fresh new pool:

$ zpool status
  pool: tank
 state: ONLINE
  scan: none requested
config:

	NAME        STATE     READ WRITE CKSUM
	tank        ONLINE       0     0     0
	  mirror-0  ONLINE       0     0     0
	    sdc     ONLINE       0     0     0
	    sdd     ONLINE       0     0     0
	  mirror-1  ONLINE       0     0     0
	    sda3    ONLINE       0     0     0
	    sdb3    ONLINE       0     0     0

errors: No known data errors

$ zpool export tank
$ zpool import tank -d /dev/disk/by-id/
cannot import 'tank': one or more devices are already in use
$ zpool status
no pools available
$ zpool import -d /dev/disk/by-id/
   pool: tank
     id: 3589532515861118860
  state: UNAVAIL
 status: One or more devices contains corrupted data.
 action: The pool cannot be imported due to damaged devices or data.
   see: http://zfsonlinux.org/msg/ZFS-8000-5E
 config:

	tank                                            UNAVAIL  insufficient replicas
	  mirror-0                                      ONLINE
	    ata-INTEL_SSDSC2BB800G4_BTWL413104A8800RGN  ONLINE
	    ata-INTEL_SSDSC2BB800G4_BTWL413204YK800RGN  ONLINE
	  mirror-1                                      UNAVAIL  insufficient replicas
	    ata-INTEL_SSDSC2BB800G4_BTWL413204Z7800RGN  UNAVAIL
	    ata-INTEL_SSDSC2BB800G4_BTWL413106AN800RGN  UNAVAIL

It is working with classical device names:

$ zpool import
   pool: tank
     id: 3589532515861118860
  state: ONLINE
 action: The pool can be imported using its name or numeric identifier.
 config:

	tank        ONLINE
	  mirror-0  ONLINE
	    sdc     ONLINE
	    sdd     ONLINE
	  mirror-1  ONLINE
	    sda3    ONLINE
	    sdb3    ONLINE

If I created the pool with ata id's and try to import with '-d /dev/' it's OK.

$ zpool import
   pool: tank
     id: 3589532515861118860
  state: UNAVAIL
 status: One or more devices contains corrupted data.
 action: The pool cannot be imported due to damaged devices or data.
   see: http://zfsonlinux.org/msg/ZFS-8000-5E
 config:

	tank                                            UNAVAIL  insufficient replicas
	  mirror-1                                      UNAVAIL  insufficient replicas
	    ata-INTEL_SSDSC2BB800G4_BTWL413204Z7800RGN  UNAVAIL
	    ata-INTEL_SSDSC2BB800G4_BTWL413106AN800RGN  UNAVAIL

   pool: tank
     id: 850847612126728262
  state: ONLINE
 action: The pool can be imported using its name or numeric identifier.
 config:

	tank                                                  ONLINE
	  mirror-0                                            ONLINE
	    ata-INTEL_SSDSC2BB800G4_BTWL413104A8800RGN        ONLINE
	    ata-INTEL_SSDSC2BB800G4_BTWL413204YK800RGN        ONLINE
	  mirror-1                                            ONLINE
	    ata-INTEL_SSDSC2BB800G4_BTWL413204Z7800RGN-part3  ONLINE
	    ata-INTEL_SSDSC2BB800G4_BTWL413106AN800RGN-part3  ONLINE
$ zpool import -d /dev/
   pool: tank
     id: 3589532515861118860
  state: UNAVAIL
 status: One or more devices contains corrupted data.
 action: The pool cannot be imported due to damaged devices or data.
   see: http://zfsonlinux.org/msg/ZFS-8000-5E
 config:

	tank         UNAVAIL  insufficient replicas
	  mirror-1   UNAVAIL  insufficient replicas
	    sda      UNAVAIL
	    sdb      UNAVAIL

   pool: tank
     id: 850847612126728262
  state: ONLINE
 action: The pool can be imported using its name or numeric identifier.
 config:

	tank        ONLINE
	  mirror-0  ONLINE
	    sdc     ONLINE
	    sdd     ONLINE
	  mirror-1  ONLINE
	    sda3    ONLINE
	    sdb3    ONLINE

ps.: As you can see, 'zpool create -f' doesn't destroy the previously existing pool entry properly.

**Comment by behlendorf** [comment]
@tomposmiko is this still an issue or can it be closed out?

**Comment by tomposmiko** [comment]
AFAIK this part of the code was not changed since I faced this issue.
Anyway, it can be reopened if it's still true.
