### ISSUE TITLE
Infinite Loop (Needed to reimage machine...)

### ISSUE THREAD

**Issue by amy** [zfsonlinux/zfs#2469]
- create pool: zpool create pool sda
- create zvol: zfs create -V 1g pool/test
  (its labeled as zd0 in my dev folder)
- zpool add pool zd0

....I needed to reimage my machine after that.

**Comment by kpande** [comment]
this is fixed in latest git master - at least, we're running pool-on-layer-on-pool with a block device driver running as follows:

```
disks -> zpool (x2) -> zvol (x2) -> storage tiering device -> zpool (x1) -> zvol, zpl
```

this configuration is working without issue, as well as the more direct and simplified "pool on zvol".
