### ISSUE TITLE
Ubuntu: Not all /dev/disk/ symlinks are available when mountall runs

### ISSUE THREAD

**Issue by frymaster** [zfsonlinux/zfs#2472]
I have a pool where the devices were added using their /dev/disk/by-id aliases.  When I reboot, one device is always consistently offline with the status UNAVAIL.  `zpool online` always succeeds, and `zpool scrub` never finds any errors, either after or just before the reboot.  There are no indications from the SMART data of any problems (timeouts, reallocated sectors etc.)

If I export the pool and reimport with `-d /dev/disk` instead of `-d /dev/disk-by-id` then I can reboot fine without issues.

Putting a sleep statement in `mountall.conf` has no effect (other than delaying boot), even if values up to a minute or over are used.

The system's root drive is an SSD connected to an add-on card and is (almost) the last disk to be initialised - it starts after the offending disk but completes before.  A previous incarnation of this system (Ubuntu 12, ZFS 0.6.2) had the root drive on a USB stick, which was initialised *much* earlier, and in that system, the pool didn't mount at all, as too many devices were missing.  I don't know how the best way to  debug before you have a disk to write to, but I was able to output the resuts of `ls /dev/disk/by-id` to the screen on that system and the symlinks were missing, even though the actual devices in `/dev/` were present.

The workaround was to add wait_for_udev in the initramfs scripts, as if I were trying to have ZFS as my root filesystem (or use /dev/ instead of /dev/disk/by-id)

So there seems to be some kind of race condition where the mountall script is run before udev has finished adding the symlinks

Title in #1103 seems related but the description is very different - for one thing, adding a delay makes no difference in my case

````
root@gregor:~# dpkg -l | grep zfs
ii  dkms                                2.2.0.3-1.1ubuntu5+zfs9~trusty      all          Dynamic Kernel Module Support Framework
ii  libzfs2                             0.6.3-2~trusty                      amd64        Native ZFS filesystem library for Linux
ii  mountall                            2.53-zfs1                           amd64        filesystem mounting tool
ii  ubuntu-zfs                          8~trusty                            amd64        Native ZFS filesystem metapackage for Ubuntu.
ii  zfs-dkms                            0.6.3-2~trusty                      amd64        Native ZFS filesystem kernel modules for Linux
ii  zfsutils                            0.6.3-2~trusty                      amd64        Native ZFS management utilities for Linux
root@gregor:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04 LTS
Release:        14.04
Codename:       trusty
root@gregor:~# uname -a
Linux gregor 3.13.0-30-generic #55-Ubuntu SMP Fri Jul 4 21:40:53 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
````

I added the following to the `mountall.conf` script, just before the `exec mountall` line:

```bash
exec >>/dev/.initramfs/myjob.log 2>&1
set -x

echo "=== Sleeping for 10 seconds"
/bin/sleep 10 || true
echo "=== Output of /dev"
/bin/ls -lh /dev/sd* || true
/bin/ls -lh /dev/disk/by-id || true
```

The output of this, along with the zdb output (using both /dev and /dev/disk/by-id) are at https://gist.github.com/frymaster/0f864b579943d53b9107

The devices corresponding to the pool are a,b,d,e,f and g.  Note the partrition symlinks for sdg are missing, but are present in `dev`

i7 920 CPU, 18GB of RAM.  The RAM is non-ECC but I am not reporting a data corruption issue. The system is **not** running under virtualisation.

**Comment by behlendorf** [comment]
I'm closing this issue out due to age.  It's gotten a bit stale and with Ubuntu moving to systemd and shipping a version of ZoL with 16.04 this exact issue seems no longer relevant.
