### ISSUE TITLE
even with a zpool.cache file, zfs module imports pools on load even when zfs_autoimport_disable=1

### ISSUE THREAD

**Issue by aarcane** [zfsonlinux/zfs#2474]
When a zpool.cache file is present in the initramfs on debian wheezy 7.5 with zfs version 0.6.3, the initramfs zfs hook calls 
    modprobe zfs zfs_autoimport_disable=1
The pools specified in zpool.cache are still automatically imported.  Clearly this is not the intended behaviour.

**Comment by behlendorf** [comment]
Closing.  This is working as intended in current releases.
