### ISSUE TITLE
zpool in use on another system debian 7.5 zfs 0.6.3 root fresh install

### ISSUE THREAD

**Issue by aarcane** [zfsonlinux/zfs#2476]
The problem that led to the discovery of #2474 and #2475 is that when rebooting a fresh install of debian 7.5 and zfs 0.6.3 root, I was forced to manually import the rpool with the -f parameter because zpool import failed saying the pool was in use on another system.  This occured despite zdb reporting no "hostid" attribute.  hostid was 0x00000000 both in the initramfs and the running OS.  the "errata" column of zdb -l was 0, and the hostname column of zdb -l was "(none)", which matched the value of hostname as run from the initramfs but not from the host OS.  Despite the hostid being absent and the hostname matching, zpool still refused to import the pool.  The only solution was to copy zpool.cache from the initramfs to the host, continue booting, then re-insert the zpool.cache into the initramfs, which led to the discovery of #2474 on subsequent boots.

**Comment by behlendorf** [comment]
This is believe to be resolved in master.
