### ISSUE TITLE
No zvol devices in /dev. Almost no zfs pointers in /sys

### ISSUE THREAD

**Issue by AeonJJohnson** [zfsonlinux/zfs#2537]
I have an issue where I have fully functioning zpools and mounted zfs file systems but no zvols in /dev. I researched the problem and found many references to udev links not being created without necessary pointers in /sys. Three separate systems with brand new OS and zfs/spl installs are the same in this respect.

There are no zvol /dev entries when I create a new zpool or export/re-import a zpool. 
Once created or imported they work fine and at expected performance.

I started with CentOS 6.5 and zfs/spl 0.6.2 on kernel 2.6.32-431.11.2.el6.x86_64

I tried updating to kernels 2.6.32-431.20.3.el6.x86_64 and 3.15.6 with no change to the issue. 

I completely removed zfs/spl 0.6.2 and installed 0.6.3-1 using the epel method with no change to the issue. 

I tried a few of the manual udev approaches and none of them worked:
udevadm control --reload
udevadm trigger
udevadm trigger -v --subsystem-match=block --sysname-match=zd* --action=change

From what I can tell the issue stems from not having the required entries in /sys. In fact I have no zfs related entries in the /sys tree other than modules and module information. Nothing in /sys/block or similar hardware subdirectory locations.

I'm assuming this is something I have done or overlooked but I cannot determine what that might be. I don't normally go looking for zvol devices in /dev but I have a specific need that caused me to look and find them absent.

Ideas?

--Jeff

**Comment by behlendorf** [comment]
Is anyone still observing this behavior in the latest 0.6.5.6 release?  Or can this be closed?

**Comment by behlendorf** [comment]
Closing as stale.
