### ISSUE TITLE
Can't upgrade from v28 or older to v5000 without enabling all feature flags

### ISSUE THREAD

**Issue by DeHackEd** [zfsonlinux/zfs#2546]
Users wanting backwards compatibility in their pools while upgrading will find it's currently impossible to upgrade to version 5000 without having each feature flag immediately promoted from `disabled` to `enabled`. 'zpool upgrade' does this automatically and it's not possible to upgrade using `zpool set version=5000`. Of course it's not possible to disable a feature once enabled either.

The workaround is to perform the upgrade on a host with the minimum feature-set you intend to be compatible with. This leaves all other features in an implicit disabled state.

**Comment by DeHackEd** [comment]
Just for future reference, this also works:
<pre>
# zpool create testpool /dev/sdb -d -O compress=lz4
[error]
# zpool create testpool /dev/sdb -d -O compress=lz4 -o feature@lz4_compres=enabled
[success]
</pre>

So you can enable exact features at pool creation time even if there are potential conflicts as indicated.

**Comment by rlaager** [comment]
In reading the manual page, I expected `zpool upgrade -V 5000` to enable feature flags, but no particular features. Instead, it enables everything.

**Comment by behlendorf** [comment]
Closing.  The procedure is documented above, the ability to disable certain feature flags on pool creation is now implemented by commit e4010f2719e3381ae15563d50b99e51ffe2b2168.
