### ISSUE TITLE
btrfs bedup equivalent

### ISSUE THREAD

**Issue by bjquinn** [zfsonlinux/zfs#2554]
ZFS dedup is painfully RAM intensive.  I'm wondering if there are some compromises to be made that might allow for some deduplication functionality without all of the overhead.  Btrfs has bedup which simply does a scan of the filesystem looking for files with identical hashes, then compares actual files for the hash matches, and if the files are truly identical, it submits the file to be deduplicated.  Not sure exactly how the internals of this works, but I assume it's a bit like how cp --reflink works.

Anyway, this doesn't have that kind of RAM overhead, and uses a sqlite table to keep up with files it's already hashed.  It's file-level only, not block-level.  But it seems like this would be very useful for backups.  Yes, snapshots and clones are helpful, but not when someone renames a file, or worse, a large tree of files -- if someone simply renames "PHOTO 2014" to "PHOTOS 2014" you're going to store an entire additional copy of that entire folder tree, which in my case is sometimes 100s of GB of incompressible data, which is quite annoying.

Is this something that's possible?  I'd be happy to do some work on this, although I'd need some direction.  I think I'd be reasonably capable on the userland side of the tool, but I wouldn't know where to start in terms of what hooks I'd need into ZoL or what changes might be required there.

**Comment by rlaager** [comment]
The scope of this seems unclear and it seems unlikely to happen.

**Comment by the8472** [comment]
> The scope of this seems unclear

Well, the btrfs extent_same ioctl would basically do the job for deduping from userspace.

**Comment by giox069** [comment]
Just to add a note: NTFS, starting from windows server 2012, has offline deduplication. It runs automatically when the system is idle, and it's suspended when there is system load.
This saved a lot of space on some general purpose fileservers, where my customers keeps many office files, images, emails, attachments. After 5-6 years of work, we find that 30-40% of used space is duplicated, and automatic NTFS background deduplication saved us that space.
I tried to do the same with zfs online deduplication, but the ram usage grew up to more than 16GB. And not only ram was a problem, but mount time! It took a lot of time to remount a deduplicated disk after a reboot.
I think that offline deduplication for zfs will be a very interesting feature.
For a deduplicating backup system, as asked on the 1st post, which avoids big transfers after a simple directory rename, look for (borg backup)[https://github.com/borgbackup].

**Comment by Zocker1999NET** [comment]
Sorry to post something in an old thread like this one, but I want to add one correction before a newby learns something wrong by accident:

Renaming a folder does not (normally) create a copy of all the files inside, it just modifies the name of the directory. That should be true for most modern filesystems. Making a snapshot in ZFS and then diffing it shows that ZFS snapshots also understands that only a rename was done. So using ZFS Snapshots and sending them incrementally to a target does not retransmit all the renamed files, it just retransmits the inodes of the renamed directory (or files, if their names were changed as well).

However, moving files between different partitions or datasets does require retransmitting them. Also external backup tools might need to retransmit them, depending on how they might detect the renames.
