### ISSUE TITLE
Parameter zfs_arc_max ignored when using zvol

### ISSUE THREAD

**Issue by cstoerkel** [zfsonlinux/zfs#2560]
With 0.6.3 it seems that there is no possibility to limit the memory zfs uses in conjunction with zvols.
Config:
/etc/modprobe.d/zfs.conf:
options zfs zfs_arc_max=8589934592
Steps to reproduce:
1.) create zvol with zfs create -V 500G pool-data/vms/testlun
2.) parted -s /dev/pool-data/vms/testlun mktable gpt
3.) parted -s /dev/pool-data/vms/testlun mkpart Primary 2048s 100%
4.) mkfs.ext4 /dev/pool-data/vms/testlun-part1
5.) zpool export pool-data
6.) rmmod zfs
7.) Note Memory used: 1 323 808
8.) modprobe zfs
9.) zpool Import pool-data
10.) mount /dev/pool-data/vms/testlun-part1 /local
11.) dd if=/dev/zero of=/local/abc bs=2M count=20000
12.) get coffee
13.) Note Memory used: 62 232 276
14.) umount /local
15.) Note Memory used: 20 266 608
16.) zpool-export pool-data
17.) rmmod zfs
18.) Note Memory used: 1 325 700

My thought was that limiting mem to 8GB should result in 9.5 GB usage by ZFS instead of 18 GB used in reality.

OS: Ubuntu 14.04 with 3.13.0-32-generic

Yust working on the plain zfs with dd or file copy the memory is used as estimated.

Any suggestions ?

**Comment by behlendorf** [comment]
Closing as stale.  Can be reopened if needed.
