### ISSUE TITLE
CENTOS 7 Root fails to start

### ISSUE THREAD

**Issue by greg-hydrogen** [zfsonlinux/zfs#2563]
Hello Everyone,

I am having an issue booting a centos 7 zfs root.  I currently have no issues with Centos 6.5 and Fedora 20

I have a small ext4 boot partition that is used for grub and related boot files (kernel, initramfs, etc). I have build the initramfs with all the necessary zfs modules.  However, when booting the system I keep getting dropped to a dracut emergency shell.  Below is the relevant parts of a capture from the output of rd.debug

[    1.700874] localhost.localdomain dracut-mount[1369]: //lib/dracut/hooks/mount/98-mount-zfs.sh@12(): case "$root" in
[    1.701177] localhost.localdomain dracut-mount[1369]: //lib/dracut/hooks/mount/98-mount-zfs.sh@15(): '[' zfs:rpool/CENTOS7 = zfs:AUTO ']'
[    1.701455] localhost.localdomain dracut-mount[1369]: //lib/dracut/hooks/mount/98-mount-zfs.sh@47(): zfsbootfs=rpool/CENTOS7
[    1.701734] localhost.localdomain dracut-mount[1369]: //lib/dracut/hooks/mount/98-mount-zfs.sh@48(): pool=rpool
[    1.702024] localhost.localdomain dracut-mount[1369]: //lib/dracut/hooks/mount/98-mount-zfs.sh@49(): zpool list -H rpool
[    1.713355] localhost.localdomain dracut-mount[1369]: ///lib/dracut/hooks/mount/98-mount-zfs.sh@64(): zfs get -H -o value mountpoint rpool/CENTOS7
[    1.721114] localhost.localdomain dracut-mount[1369]: cannot open 'rpool/CENTOS7': dataset does not exist
[    1.721580] localhost.localdomain dracut-mount[1369]: //lib/dracut/hooks/mount/98-mount-zfs.sh@64(): mountpoint=
[    1.721873] localhost.localdomain dracut-mount[1369]: //lib/dracut/hooks/mount/98-mount-zfs.sh@65(): '[' '' = legacy ']'
[    1.722164] localhost.localdomain dracut-mount[1369]: //lib/dracut/hooks/mount/98-mount-zfs.sh@68(): mount -o zfsutil -t zfs rpool/CENTOS7 /sysroot
[    1.729971] localhost.localdomain dracut-mount[1369]: filesystem 'rpool/CENTOS7' cannot be mounted, unable to open the dataset

If I type exit from the dracut emergency shell it fails back to the shell, but has /sysroot mounted, typing exit another time will boot the system without an issues.

It appears for some reason that discover the mounpoint on startup...

Performing the same command from the emergency shell 
 zfs get -H -o value mountpoint rpool/CENTOS7
produces the expected output "legacy"

I have also tried using the bootfs property but the same occurs...

Any ideas?

**Comment by loli10K** [comment]
Closing as stale and supposedly fixed.
