### ISSUE TITLE
rcu_sched self-detected stall on CPU when using Xen kernel and thin / thick provisioned zfs volumes

### ISSUE THREAD

**Issue by abraunegg** [zfsonlinux/zfs#2564]
When using a Xen enabled kernel, and provisioning a ZFS thick or thin volume for use by Xen (as a physical back end device) or as an iSCSI target using scsi-target-utils (tgtadm), if the system is rebooted or a power loss occurs the system fails to boot, creating a rcu_sched stall when attempting to access the zd\* volumes:

![img_0478a](https://cloud.githubusercontent.com/assets/4956234/3792208/34ec1f5c-1b6c-11e4-9498-6321d4a1aca3.jpg)

This issue does not occur on VMware (workstation, ESXi), nor on non physical Xen enabled systems, thus must be something particular to how a Xen enabled kernel is accessing / looking at the zd\* /dev devices when the SPL / ZFS modules is loaded.

I am able to reproduce this on any physical system I have where I can enable Xen. Happy to take any advice or suggestions on Kernel config or debugging SPL / ZFS to help track this down.

<h3>Test Platform:</h3>

- Intel S5000xvn / 8GB ECC
- Raid 1 boot (EXT4)
- CentOS 6.5 based 
- Kernel 3.10.48 / 3.12.26
- Xen 4.2.2 / Xen 4.4.0
- ZFS / SPL 0.6.2 / 0.6.3

<h3>Reproduction Steps:</h3>

1.     Enable Xen on the system (Xen 4.2.x or 4.4.x)
2.  Create a zfs volume using “/sbin/zfs create -s -b 128K –V <size> <path>” or “/sbin/zfs create -b 128K –V <size> <path>”
3.  Reboot / reset the system / simulate a power outage

On reboot, after running through udev, the system will go into an rcu_sched detected stall loop – see attached images. On this particular system I have 2 such zfs volumes that when working get detected as zd0 and zd16.

The system just performs an endless detected stall and never boots. Further rcu_sched debug diagnostsics / kernel diagnostics is not currently displayed.

The stall occurs after UDEV completes if "rhgb quiet" is used as part of the boot loader string.

This issue feels very similar to https://github.com/zfsonlinux/spl/issues/252 - although this occurs after the switchroot has occurred and UDEV service has started.

<h3>Recovery from the error:</h3>

The only way to recover the system from the error is to boot with the install CD, perform a system recovery, manually modprobe SPL / ZFS modules, import the known storage pools then export them.

Once this is done, booting the system returns to normal, then have to manually re-import the zfs pools again.

**Comment by abraunegg** [comment]
Potential fix through kernel configuration:

Broken kernel configuration:
======================
# CONFIG_PREEMPT_RCU is not set
CONFIG_PREEMPT_NOTIFIERS=y
CONFIG_PREEMPT_NONE=y
# CONFIG_PREEMPT_VOLUNTARY is not set
# CONFIG_PREEMPT is not set

Potential working configuration:
=========================
# CONFIG_PREEMPT_RCU is not set
CONFIG_PREEMPT_NOTIFIERS=y
# CONFIG_PREEMPT_NONE is not set
CONFIG_PREEMPT_VOLUNTARY=y
# CONFIG_PREEMPT is not set


I need to perform some further regression testing against Xen / iSCSI and ZFS thin / thick volumes tonight, however initial testing thus far shows that 'CONFIG_PREEMPT_VOLUNTARY=y' resolves this issue.

**Comment by behlendorf** [comment]
@abraunegg Thanks for following up, please let us know if this does really resolve the problem.

**Comment by abraunegg** [comment]
@behlendorf - After 24+ hrs going through regression testing the issue appears to be resolved with the kernel modification. Still assessing any performance impacts - perceived or otherwise.

**Comment by raphael-luciano** [comment]
@abraunegg 
Did you fix your problem only with these kernel changes?

# CONFIG_PREEMPT_RCU is not set
CONFIG_PREEMPT_NOTIFIERS=y
# CONFIG_PREEMPT_NONE is not set
CONFIG_PREEMPT_VOLUNTARY=y
# CONFIG_PREEMPT is not set

And, where is the kernel configuration file you edited? Is it the /etc/default/grub ? (I'm using ubuntu for both, host and guest).

Thank you in advance!

**Comment by abraunegg** [comment]
@raphael-luciano

The kernel config changes were made to the configuration file (.config) when compiling the kernel used by the host (not guest). I use CentOS myself, so I cant advise on Ubuntu kernel changes.

By setting the following in the kernel configuration:

```
 CONFIG_PREEMPT_VOLUNTARY=y
```

I have not had any issues since Jan 2015 (close to 3 years now) with the original issue I posted after implementing the kernel fix.

Best regards,

Alex

**Comment by raphael-luciano** [comment]
@abraunegg 
Thank you very much for your quick answer, my friend.
Since the new operational systems don't even need to reconfigure/recompile kernels do set/enable hypervisors, I think I can figure other approaches to do it. 
If I fail, I will try your suggestion then.
Have a great day!

**Comment by behlendorf** [comment]
Closing this issue.  As described in https://github.com/zfsonlinux/zfs/issues/2564#issuecomment-346471729 above the recommended solution is to make sure your kernel is built with `CONFIG_PREEMPT_VOLUNTARY=y`.  This is the default value for the CentOS 7 and Ubuntu 16.04 kernels.

**Comment by cwedgwood** [comment]
@behlendorf detect this and WARN on module load?

**Comment by behlendorf** [comment]
That's a good idea.  As I understand it this issue has _only_ been observed when using a Xen enabled kernel with `CONFIG_PREEMPT_VOLUNTARY=n` .  It would be ideal to target that specific configuration.
