### ISSUE TITLE
hrtime_t timestruc_t undefined with musl libc

### ISSUE THREAD

**Issue by salazaj** [zfsonlinux/zfs#2566]
Using gcc and musl libc results in the following error.
```
  CC       getexecname.lo
In file included from /usr/include/sys/resource.h:9:0,
                 from /usr/include/sys/param.h:31,
                 from ../../lib/libspl/include/sys/param.h:30,
                 from ../../lib/libspl/include/sys/types.h:33,
                 from ../../lib/libspl/include/unistd.h:43,
                 from ../../lib/libspl/getexecname.c:29:
../../lib/libspl/include/sys/time.h:61:1: error: unknown type name 'hrtime_t'
../../lib/libspl/include/sys/time.h:62:25: error: unknown type name 'timestruc_t'
Makefile:646: recipe for target 'getexecname.lo' failed
```

musl sys/resource.h has an include for sys/time.h (in contrast to glibc) which incorrectly pulls in the libspl sys/time.h. This header includes the system sys/time.h and local sys/types.h, but sys/types.h was already included so its declarations of hrtime_t and timestruc_t aren't reached prior to usage.
Temporary fix results from moving the include sys/param.h to the end of lib/libspl/include/sys/types.h as shown in [stef's commit 6296d1](https://github.com/stef/zfs/commit/6296d14f69d42e30fff089cc865f9f1b3c13b6c3).

**Comment by behlendorf** [comment]
Resolved by 1ad32f0a18657b3905bb127463e1a0653e0ef4ad, issue #4459.
