### ISSUE TITLE
_DATE_FMT undeclared when using musl libc

### ISSUE THREAD

**Issue by salazaj** [zfsonlinux/zfs#2567]
Using gcc with musl libc results in the following error.

```
  CC       timestamp.lo
../../lib/libspl/timestamp.c: In function 'print_timestamp':
../../lib/libspl/timestamp.c:43:21: error: '_DATE_FMT' undeclared (first use in this function)
../../lib/libspl/timestamp.c:43:21: note: each undeclared identifier is reported only once for each function it appears in
Makefile:709: recipe for target 'timestamp.lo' failed
```

glibc's langinfo.h defines both D_FMT and _DATE_FMT
```
  D_FMT,                        /* Date format for strftime.  */
#define D_FMT                   D_FMT
...
  _DATE_FMT,            /* strftime format for date.  */
#define _DATE_FMT       _DATE_FMT
```
Musl only defines D_FMT. Applying a guard to timestamp.c, as shown in [stef's commit 796062](https://github.com/stef/zfs/commit/796062fa139d5e3e77382976a1f0e66d6d8659be), allows the build to progress, and no change in behavior on glibc systems.

**Comment by behlendorf** [comment]
Closing, resolved by 43148eaef2819eeda68e6846c03f0bd4672245a7.
