### ISSUE TITLE
deadlock because of zpl_evict_inode requiring more memory

### ISSUE THREAD

**Issue by avg-I** [zfsonlinux/zfs#2570]
One of our test loads can easily put a system in a deadlocked state where a machine can be pinged but pretty much nothing else works. It seems that this is caused by the following chain of calls:
any call to allocate pages while there is a page shortage -> try_to_free_pages -> super_cache_scan -> prune_icache_sb -> destroy_inode -> zpl_inode_destroy -> iput-> zpl_evict_inode -> zfs_rmnode -> arc_read -> spl_kmem_cache_alloc -> alloc_pages_current.
All active threads seem to be in the above state.

**Comment by behlendorf** [comment]
@avg-I has this been resolved in newer versions of ZoL or is it still and issue?

**Comment by behlendorf** [comment]
Closing as stale.  There have been several recent fixes to master which should further improve things.
