### ISSUE TITLE
0.6.3 spl+zfs kernel modules fail to build in wheezy with backported 3.14 kernel

### ISSUE THREAD

**Issue by zenny** [zfsonlinux/zfs#2583]
UPDATE 0: Also tried with the zfs wheezy-daily repo with the same compilation problem!
UPDATE 1: Downgraded the kernel to 3.10.11 and the problem persists. Hmmmm...

Tried to install using the zfs debian repo on the backported 3.14 kernel in Debian wheezy. It fails with:

> Building only for 3.14-0.bpo.2-amd64
> Building initial module for 3.14-0.bpo.2-amd64
> configure: error: in `/var/lib/dkms/spl/0.6.3/build':
> configure: error: C compiler cannot create executables
> See`config.log' for more details
> Error! Bad return status for module build on kernel: 3.14-0.bpo.2-amd64 (x86_64)
> Consult /var/lib/dkms/spl/0.6.3/build/make.log for more information."
# gcc --version

> gcc (Debian 4.7.2-5) 4.7.2
> Copyright (C) 2012 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE."
# cat /var/lib/dkms/spl/0.6.3/build/make.log

> DKMS make.log for spl-0.6.3 for kernel 3.14-0.bpo.2-amd64 (x86_64)
> Mon Aug 11 15:58:22 GMT 2014
> make: **\* No targets specified and no makefile found.  Stop."
# Same as above error with zfs-dkms.

Also tried to symlink with no go:

> # ln -s /lib/modules/$(uname -r)/build /lib/modules/$(uname -r)/source
# uname -r

> 3.14-0.bpo.2-amd64
# dpkg -l *spl* *zfs* | grep ^i

> ii  debian-zfs                        7~wheezy                           amd64        Native ZFS filesystem metapackage for Debian.
> ii  libzfs2                           0.6.3-1~wheezy                     amd64        Native ZFS filesystem library for Linux
> ii  nocatsplash                       0.92-4                             amd64        gateway daemon for open public network
> ii  spl                               0.6.3-7~wheezy                     amd64        Solaris Porting Layer user-space utilities for Linux
> ii  spl-dkms                          0.6.3-7~wheezy                     all          Solaris Porting Layer kernel modules for Linux
> ii  zfs-dkms                          0.6.3-1~wheezy                     all          Native ZFS filesystem kernel modules for Linux
> ii  zfsonlinux                        2~wheezy                           all          archive.zfsonlinux.org trust package
> ii  zfsutils                          0.6.3-1~wheezy                     amd64        command-line tools to manage ZFS filesystems
# cat /etc/apt/sources.list.d/zfsonlinux.list

> deb http://archive.zfsonlinux.org/debian wheezy main
> # deb-src http://archive.zfsonlinux.org/debian wheezy main contrib

**Comment by dennisbirkholz** [comment]
I had the same problem. The debian-zfs package should have dependencies to build-essentials, linux-source and linux-headers to avoid this misleading error message.

**Comment by FransUrbo** [comment]
They (<code>spl-dkms</code> and <code>zfs-dkms</code>) both depends on <code>dkms</code> which depends on the relevant parts:

```
Package: dkms
Depends: module-init-tools, gcc, make | build-essential | dpkg-dev, coreutils (>= 7.4), patch
Recommends: fakeroot, menu | sudo, linux-headers-686-pae | linux-headers-amd64 | linux-headers-generic | linux-headers, linux-image
```

**Comment by dennisbirkholz** [comment]
@FransUrbo that is odd, I had to pull in build-essentials myself. Also linux-headers seems not to be optional, it is required to build the modules. I will try to reproduce that (will take some days). Maybe dkms has missing dependencies.

**Comment by behlendorf** [comment]
Closing, packaging for Debian is now handled by Debian.
