### ISSUE TITLE
zpool create reports device unavailable after repartitioning

### ISSUE THREAD

**Issue by ahamilto** [zfsonlinux/zfs#2593]
Attempting to create a new zpool using 6x WD 900GB SAS drives. All of the drives have entries in /etc/zfs/vdev_id.conf and appear in /dev/disk/by-vdev/ as pool0 - pool5. After fixing problems related to Issue 2493, the command zpool create pool raidz2 /dev/disk/by-vdev/pool0 /dev/disk/by-vdev/pool1 ... /dev/disk/by-vdev/pool5 reported that one or more of the devices was unavailable. I was able to create the pool using the /dev/sdX device nodes, and afterwards could export the pool and reimport it using the links under /dev/disk/by-vdev/

I am running ZFS 0.6.3 with the efi_rescan() patch on Kernel 3.14.16. The system does have multipath-tools installed for some disks that are accessed via iSCSI, however, the wwids of the directly-attached drives are blacklisted in multipath.conf.

**Comment by gmelikov** [comment]
Close as stale.
