### ISSUE TITLE
zfs recv / broken memory management 

### ISSUE THREAD

**Issue by hjjg** [zfsonlinux/zfs#2618]
I have two identical boxes. One of them is my primary NFS server that serves files for a webserver, the other one is a stand by machine that replicates the data every once in a while (manually until I know that this works without problems). I discovered a really bad send/recv performance after the box runs for a while. If I send a snapshot, the box receives it in a few seconds but it needs several minutes and even up to hours to commit the snapshots to disk. When looking at dstat, a tool that show multiple system statistics, I can see that after and while receiving the data from the sending machine, the disks are writing many MB/s. After the snapshot is sent (mbuffer quits, no network activity), zfs recv does a lot of read IOPS on all disks. This can be fixed by rebooting the receiving box or, and I'm not quite sure about that though it worked the first time I tried, when dropping the caches with:

 echo 3 > /proc/sys/vm/drop_caches

I've seen zfs recv taking 4 minutes to add a snapshot with 14MB in size. After a reboot, the box is able to receive over 361 MB in 25 seconds. I thought that this is a problem after sending an initial stream (4.3 TB dataset in my case) but I did a reboot yesterday to fix it and today it was slow again. Like I said, the receiving machine is not doing anything except receiving snapshots.

I already discussed this on the mailing list with the topic "ZFS send/receive performance".

The receiving system is running Ubuntu 14.04. with kernel 3.13.0-34-generic and zfs-dkms 0.6.3-2~trusty. In the output below you can see that zpool scrub runs four hours to check the 4.3TB data with ~300 MB/s. 

The hardware I use in both nodes:

Xeon CPU E5-2630L
64GB ECC RAM
6 \* 4 TB SAS 7200rpm for the zpool (three mirrors)

root@nfs02:~# zpool status
  pool: nfs02
 state: ONLINE
  scan: scrub repaired 0 in 4h16m with 0 errors on Mon Aug 18 14:32:49 2014
config:

```
    NAME                        STATE     READ WRITE CKSUM
    nfs02                       ONLINE       0     0     0
      mirror-0                  ONLINE       0     0     0
        wwn-0x5000cca03b62c5d0  ONLINE       0     0     0
        wwn-0x5000cca03b62b9dc  ONLINE       0     0     0
      mirror-1                  ONLINE       0     0     0
        wwn-0x5000cca03b62adf8  ONLINE       0     0     0
        wwn-0x5000cca03b615b78  ONLINE       0     0     0
      mirror-2                  ONLINE       0     0     0
        wwn-0x5000cca03b62afc8  ONLINE       0     0     0
        wwn-0x5000cca03b62a258  ONLINE       0     0     0
```

errors: No known data errors

**Comment by behlendorf** [comment]
Closing as stale.
