### ISSUE TITLE
txg_sync or zfs blocked for more than n seconds during snapshot creation

### ISSUE THREAD

**Issue by mailinglists35** [zfsonlinux/zfs#2623]
every morning zfs-auto-snapshot runs the daily task. every now and then I get this message.
zfs-auto-snapshot is the last daily job run by run-parts (cron runs *.d scripts serially in alphabetical order and zfs-.. is the last. before that, a rsync also runs in the same daily batch and fills the cache)

hung_task_timeout_secs is 15 because I do not want to wait for default 120 (the machine has a low workload doing mostly nothing all the time so if something hangs in I/O for more than 15 seconds it is already a sing of something going wrong)

the complete stack dump is pasted here http://p.defau.lt/?_50q39szJEBbhL4mR4U7iw as github has a limit of 262144 characters.

using zfs 0.6.3 on debian wheezy with kernel 3.14amd64 from backports

Aug 25 06:40:30 homerouter kernel: [12299.036035] INFO: task txg_sync:1078 blocked for more than 15 seconds.
Aug 25 06:40:30 homerouter kernel: [12299.036068]       Tainted: P           O 3.14-0.bpo.2-amd64 #1
Aug 25 06:40:30 homerouter kernel: [12299.036093] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Aug 25 06:40:30 homerouter kernel: [12299.036140] txg_sync        D ffff88011bc94340     0  1078      2 0x00000000
Aug 25 06:40:30 homerouter kernel: [12299.036170]  ffff8800369632b0 0000000000000046 ffff8800d8cbfe70 ffff880116f109a0
Aug 25 06:40:30 homerouter kernel: [12299.036212]  0000000000014340 ffff8800d15abfd8 0000000000014340 ffff8800369632b0
Aug 25 06:40:30 homerouter kernel: [12299.036254]  ffff8800d15abb38 ffff88011bc94bd0 ffff8800369632b0 ffffc9001331b210
Aug 25 06:40:30 homerouter kernel: [12299.036296] Call Trace:
Aug 25 06:40:30 homerouter kernel: [12299.036320]  [<ffffffff814f9c47>] ? io_schedule+0x87/0xd0
Aug 25 06:40:30 homerouter kernel: [12299.036356]  [<ffffffffa05a41d9>] ? cv_wait_common+0xa9/0x1b0 [spl]
Aug 25 06:40:30 homerouter kernel: [12299.036385]  [<ffffffffa059d4b0>] ? taskq_dispatch_ent+0x70/0x1d0 [spl]
Aug 25 06:40:30 homerouter kernel: [12299.036412]  [<ffffffff810a69a0>] ? __wake_up_sync+0x10/0x10
Aug 25 06:40:30 homerouter kernel: [12299.036455]  [<ffffffffa075b33b>] ? zio_wait+0xeb/0x1a0 [zfs]
Aug 25 06:40:30 homerouter kernel: [12299.036492]  [<ffffffffa06f4667>] ? dsl_scan_sync+0x427/0xb70 [zfs]
Aug 25 06:40:30 homerouter kernel: [12299.036518]  [<ffffffff810a69a0>] ? __wake_up_sync+0x10/0x10
Aug 25 06:40:30 homerouter kernel: [12299.036556]  [<ffffffffa07035bd>] ? spa_sync+0x45d/0xaf0 [zfs]
Aug 25 06:40:30 homerouter kernel: [12299.036581]  [<ffffffff810a6603>] ? __wake_up+0x43/0x70
Aug 25 06:40:30 homerouter kernel: [12299.036605]  [<ffffffff810c55fd>] ? ktime_get_ts+0x3d/0xd0
Aug 25 06:40:30 homerouter kernel: [12299.036643]  [<ffffffffa0714fb8>] ? txg_sync_thread+0x398/0x5f0 [zfs]
Aug 25 06:40:30 homerouter kernel: [12299.036682]  [<ffffffffa0714c20>] ? txg_init+0x250/0x250 [zfs]
Aug 25 06:40:30 homerouter kernel: [12299.036710]  [<ffffffffa059cb85>] ? thread_generic_wrapper+0x75/0x90 [spl]
Aug 25 06:40:30 homerouter kernel: [12299.036739]  [<ffffffffa059cb10>] ? __thread_create+0x310/0x310 [spl]
Aug 25 06:40:30 homerouter kernel: [12299.036766]  [<ffffffff81086f3c>] ? kthread+0xbc/0xe0
Aug 25 06:40:30 homerouter kernel: [12299.036789]  [<ffffffff81086e80>] ? flush_kthread_worker+0xa0/0xa0
Aug 25 06:40:30 homerouter kernel: [12299.036816]  [<ffffffff81504f4c>] ? ret_from_fork+0x7c/0xb0
Aug 25 06:40:30 homerouter kernel: [12299.036840]  [<ffffffff81086e80>] ? flush_kthread_worker+0xa0/0xa0
Aug 25 06:40:30 homerouter kernel: [12299.036900] INFO: task zfs:20473 blocked for more than 15 seconds.
Aug 25 06:40:30 homerouter kernel: [12299.036925]       Tainted: P           O 3.14-0.bpo.2-amd64 #1
Aug 25 06:40:30 homerouter kernel: [12299.036948] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Aug 25 06:40:30 homerouter kernel: [12299.037494] zfs             D ffff88011bc94340     0 20473  19732 0x00000080
Aug 25 06:40:30 homerouter kernel: [12299.037523]  ffff8800c694f3b0 0000000000000086 ffff880035e4f250 ffff880116f109a0
Aug 25 06:40:30 homerouter kernel: [12299.037565]  0000000000014340 ffff88009eccbfd8 0000000000014340 ffff8800c694f3b0
Aug 25 06:40:30 homerouter kernel: [12299.037606]  0000000000000202 ffff880035e4f2a0 0000000000000002 ffff880035e4f1f8
Aug 25 06:40:30 homerouter kernel: [12299.037648] Call Trace:
Aug 25 06:40:30 homerouter kernel: [12299.037670]  [<ffffffffa05a4255>] ? cv_wait_common+0x125/0x1b0 [spl]
Aug 25 06:40:30 homerouter kernel: [12299.037697]  [<ffffffff810a69a0>] ? __wake_up_sync+0x10/0x10
Aug 25 06:40:30 homerouter kernel: [12299.037734]  [<ffffffffa071418b>] ? txg_wait_synced+0xab/0x180 [zfs]
Aug 25 06:40:30 homerouter kernel: [12299.037769]  [<ffffffffa0768770>] ? dsl_destroy_snapshot_check_impl+0x80/0x80 [zfs]
Aug 25 06:40:30 homerouter kernel: [12299.037817]  [<ffffffffa0768600>] ? dsl_destroy_head_sync+0xc0/0xc0 [zfs]
Aug 25 06:40:30 homerouter kernel: [12299.037856]  [<ffffffffa06f5039>] ? dsl_sync_task+0xc9/0x240 [zfs]
Aug 25 06:40:30 homerouter kernel: [12299.037891]  [<ffffffffa0768770>] ? dsl_destroy_snapshot_check_impl+0x80/0x80 [zfs]
Aug 25 06:40:30 homerouter kernel: [12299.037939]  [<ffffffffa0768600>] ? dsl_destroy_head_sync+0xc0/0xc0 [zfs]
Aug 25 06:40:30 homerouter kernel: [12299.037973]  [<ffffffffa0768905>] ? dsl_destroy_snapshots_nvl+0x85/0x100 [zfs]
Aug 25 06:40:30 homerouter kernel: [12299.038023]  [<ffffffffa073c250>] ? zfs_ioc_destroy_snaps+0x120/0x140 [zfs]
Aug 25 06:40:30 homerouter kernel: [12299.038061]  [<ffffffffa073c541>] ? zfsdev_ioctl+0x181/0x510 [zfs]
Aug 25 06:40:30 homerouter kernel: [12299.038088]  [<ffffffff811aae11>] ? do_vfs_ioctl+0x81/0x4e0
Aug 25 06:40:30 homerouter kernel: [12299.038113]  [<ffffffff811ab309>] ? SyS_ioctl+0x99/0xb0
Aug 25 06:40:30 homerouter kernel: [12299.038137]  [<ffffffff814fd1c8>] ? page_fault+0x28/0x30
Aug 25 06:40:30 homerouter kernel: [12299.038161]  [<ffffffff81504ff9>] ? system_call_fastpath+0x16/0x1b
Aug 25 06:40:32 homerouter kernel: [12301.045600]  [<ffffffff81096c80>] ? try_to_wake_up+0x280/0x280
Aug 25 06:40:32 homerouter kernel: [12301.045600]  [<ffffffff811997b5>] ? vfs_read+0x105/0x180
Aug 25 06:40:32 homerouter kernel: [12301.045600]  [<ffffffff811ad361>] ? SyS_poll+0x61/0xf0
Aug 25 06:40:32 homerouter kernel: [12301.045600]  [<ffffffff810f34cc>] ? __audit_syscall_entry+0x8c/0xe0
Aug 25 06:40:32 homerouter kernel: [12301.045600]  [<ffffffff81504ff9>] ? system_call_fastpath+0x16/0x1b
Aug 25 06:40:32 homerouter kernel: [12301.045600] polkitd         S ffff88011bc94340     0  7193      1 0x00000080
Aug 25 06:40:32 homerouter kernel: [12301.045600]  ffff8800d73d4e20 0000000000000086 0000000000000002 ffff880035d60510
Aug 25 06:40:32 homerouter kernel: [12301.045600]  0000000000014340 ffff8800b90c7fd8 0000000000014340 ffff8800d73d4e20
Aug 25 06:40:32 homerouter kernel: [12301.045600]  ffff88011bc14340 0000000000000000 0000000000000000 0000000000000000

**Comment by behlendorf** [comment]
Closing, [ZFS Channel Programs](https://www.illumos.org/issues/7431) have been merged which provides us a more efficient mechanism for these kinds of large operations.
