### ISSUE TITLE
combination of casesensitivity = insensitive and samba case sensitive = true does strange, bad things

### ISSUE THREAD

**Issue by bjquinn** [zfsonlinux/zfs#2634]
I saw a suggestion somewhere (https://lists.samba.org/archive/samba-technical/2014-February/098084.html) that with casesensitivity=insensitive on a zfs filesystem and then case sensitive = true on a Samba share, you can get around Samba's performance issues with large numbers of files in a single directory.  You actually use case sensitive = true on Samba (not false, as you might expect), to disable the inefficient file searching algorithms, as you might as well tell Samba to force case sensitivity if ZFS is going to handle the insensitivity part.  So I tried this, and strange things happened.

I had a directory full of files, and the directory name was lower case (let's call it "pictures"), and then I tried to write to it (by adding more files) over Samba from Windows, and the path specified from the Windows box was Pictures (with a capital "P").  This works.  But if I go to the command line of the Samba server, I can cd to pictures and do "ls" and all looks fine.  But then if I cd to Pictures (capital P) and do "ls", I get a bunch of files with ?????? permissions that can't be accessed or deleted.

If I delete the directory and start over, then I can cd to "pictures", "Pictures", or "PICTURES" from the command line and it all looks fine and all works as expected, but as soon as I try to add files to that folder over Samba with case sensitive = true, it does the above strange things.  Please correct me (and my apologies) if I'm wrong, but it seems that this must be a ZFS problem, as I don't see how a userland program (Samba) should be allowed to cause this kind of corruption.  If ZFS is truly case insensitive with the casesensitivity=insensitive option, Samba shouldn't be able to create a scenario where things look different based on which case you use to access a directory.

Finally, on a side note, on the project I was working on, I needed case insensitivity on the file system level, not just the speed improvement from the combination of ZFS and Samba settings described above.  With the Samba setting case sensitive = false, all works great.  I don't get the speed benefit, but I get the case insensitivity (without the odd issues described above), which is what I really needed in this particular scenario (yes, I know, Samba is supposed to do this, but it didn't work in my particular scenario).  I thought I should document this strange situation in any case, as it might be useful.

**Comment by kpande** [comment]
using casesensitivity=insensitive performance woes in ZFS, too.

**Comment by behlendorf** [comment]
Various fixed for case insensitivity had been made including c5d0287011679d76288c2617c409252245172a32.  This is believed to no longer be an issue.
