### ISSUE TITLE
readonly property returned incorrectly

### ISSUE THREAD

**Issue by jimsalterjrs** [zfsonlinux/zfs#2653]
The readonly property of a filesystem is frequently returned as "on" even if it's actually been turned off, and is in fact off.  Demonstration:

<pre>root@locutus:~# zfs get readonly data/target/lolz
NAME              PROPERTY  VALUE   SOURCE
data/target/lolz  readonly  on      local
root@locutus:~# touch /data/target/lolz/thing
touch: cannot touch ‘/data/target/lolz/thing’: Read-only file system</pre>

So far, so good.  But now what happens when I turn readonly off again?

<pre>root@locutus:~# zfs set readonly=off data/target/lolz
root@locutus:~# zfs get readonly data/target/lolz
NAME              PROPERTY  VALUE   SOURCE
data/target/lolz  readonly  on      temporary</pre>

Well that's no good.  Not only did I just set it off, it actually IS off, as I can now write to the filesystem:

<pre>root@locutus:~# touch /data/target/lolz/thing
root@locutus:~# zfs get readonly data/target/lolz
NAME              PROPERTY  VALUE   SOURCE
data/target/lolz  readonly  on      temporary</pre>

But even after WRITING to the filesystem, the readonly property still reads as "on".  Wtf?

I'm using Ubuntu 14.04 LTS, with ubuntu-zfs installed from the zfs-native/stable repo.

<pre>root@locutus:~# uname -a
Linux locutus 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
root@locutus:~# apt-cache policy ubuntu-zfs
ubuntu-zfs:
  Installed: 8~trusty
  Candidate: 8~trusty
  Version table:
 *** 8~trusty 0
       1001 http://ppa.launchpad.net/zfs-native/stable/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status</pre>

**Comment by gmelikov** [comment]
Close as stale.
