### ISSUE TITLE
Received filesystems is mounted in bulk when the whole receive is finished instead of individually when received

### ISSUE THREAD

**Issue by FransUrbo** [zfsonlinux/zfs#2673]
Sending 4TB and 174 filesystems takes _a while_ and the mount happens when all 174 is transfered.

It would be better/nicer if each filesystem was mounted after it have been transfered instead of waiting two days...

**Comment by behlendorf** [comment]
Closing, won't fix.  As was mentioned above we should wait until to end before mounting to ensure to mount point dependencies are honored.
