### ISSUE TITLE
duplicate extended attribute creation

### ISSUE THREAD

**Issue by mmehnert** [zfsonlinux/zfs#2686]
When the xattr attribute of a filesystem is  first set to "on", attributes are created and then xattr is set to "sa", it is possible to have two attributes for the same file that have the same name by creating another appropriately named attribute. 

One of them is removable by the "attr" command while the other is untouchable by the attr command until xattr is set back to "on". (although the attribute is visible all the time via "attr -l")

It would be preferable if after such a switch in configuration, attributes could be handled without this confusion. If those attributes are for example used by Samba to store Windows ACLs, the problems caused by the behavior  described above can be a bit confusing. (I had/have files with two NTACL attributes.)

**Comment by behlendorf** [comment]
This was resolved.
