### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [zfsonlinux/zfs#2694]
I would like to point out that identifiers like "[```_LIBZFS_H```](https://github.com/zfsonlinux/zfs/blob/9b67f605601c77c814037613d8129562db642a29/include/libzfs.h#L30)" and "[```_ZFS_PROP_H```](https://github.com/zfsonlinux/zfs/blob/962d52421236fc9cd61d59b4f18cff3276077da9/include/zfs_prop.h#L26)" [do not fit](https://www.securecoding.cert.org/confluence/display/seccode/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by rlaager** [comment]
@behlendorf Can you make a call on whether this is an actual problem?

There is a LOT of code in ZFS that uses the underscore prefix in violation of the standard. A naive grep gives 3407 lines. A lot of that is legit, but based on some quick review, I'd say the real amount is 1000+ lines of things to change.

Basically, do we:
A) Change nothing, and close this issue now.
B) Change only the header file guards.
C) Change everything with an underscore prefix that isn't coming from some other code (e.g. the kernel).

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

**Comment by behlendorf** [comment]
@elfring @rlaager keep in mind that the reason for this rule is that these names are reserved for the compiler and **system library headers**.  When ZFS was written it was as a core system component of Solaris and it was therefore appropriate to use the underscore prefix.  I'd argue that's still the case and it would be misleading and disruptive to remove them now.

**Comment by elfring** [comment]
I am unsure if the mentioned categorisation of the affected source files as "system library headers" can really improve the situation generally.
I got the impression that this software could only be safely used so far as another component for the implementation of a compiler for the programming languages "C" and/or "C++" because of [the discussed identifier selection](http://en.cppreference.com/w/cpp/language/identifiers#In_declarations "Checking usage of reserved identifiers?").
