### ISSUE TITLE
RPMs built from git do not have strict dependencies

### ISSUE THREAD

**Issue by ryao** [zfsonlinux/zfs#2706]
zfs-0.6.3-75_g2d50158.fc20 will happily accept libzfs2-0.6.3-1 to satisfy a dependency. The dependency should be tightened.

**Comment by behlendorf** [comment]
Closing.  We can't rely on a release number to express a dependency.  This field is intentionally left to the downstream distributions for their own use.  The version number must be sufficient and if we change the library API we must bump the version numbers in the correct way.
