### ISSUE TITLE
`zfs recv -F`: cannot restore to [...]: destination already exists (only if clone exist)

### ISSUE THREAD

**Issue by seletskiy** [zfsonlinux/zfs#2739]
Steps to reproduce:

```
zfs create zroot/src
zfs snap zroot/src@1
zfs send zroot/src@1 | zfs recv zroot/dst
zfs snap zroot/dst@blah
zfs clone zroot/dst@blah zroot/dst-blah
zfs snap zroot/src@2
zfs send -i zroot/src@1 zroot/src@2 | zfs recv -F zroot/dst@2
```

Result:

```
cannot restore to zroot/dst@2: destination already exists
```

Expected: recv command successfully completes or correct error message is reported.

It's reproduceable in 100% of cases on 0.6.3.

If clone is not created or flag `-F` is not used issue will not reproduce.

**Comment by behlendorf** [comment]
This is still reproducible in master using the original test case above.  Destroying the clone allows the stream to be received.
