### ISSUE TITLE
Cannot get ZFS pool created in OSX to import on Linux system

### ISSUE THREAD

**Issue by zhro** [zfsonlinux/zfs#2742]
As I'm new to ZFS, I don't know if this is a configuration error on my part or an actual bug. I've asked this question on serverfault and linked it here:

http://serverfault.com/questions/631124/cannot-get-zfs-pool-created-in-osx-to-import-on-linux-system

The latest OpenZFS 0.6.3-1 is installed on both systems. I initially created a pool from within OSX where it is mountable and checks out OK. But when I boot into Linux, ZFS reports it as corrupt.

**Comment by gildegoma** [comment]
Wow, I am facing the exactly same issue! Thanks everybody for sharing and helping, it seems that I won't lose as much time as @Zhro did (not tried yet, but will very soon :-)
