### ISSUE TITLE
zfs send/recv VERY slow for large files (>5GB)

### ISSUE THREAD

**Issue by lintonv** [zfsonlinux/zfs#2746]
I have been using ZFS SEND/RECV over SSH. The speeds are excellent for small files. But for large files (>2GB), it is terrible. 

- File Size less than 5 GB, the speed : 112MB/s (which is excellent and using the full speed of the interface)
- File Size greater than 5 GB, the speed is 10MB/s (very, very slow)

Initially, I thought the bottleneck was SSH and the MTU. But despite using jumbo frames (9000 MTU) and using other transfer tools like netcat, there is no change in the transfer speeds. 

The bottleneck has to be ZFS. After reading the code in zfs_log.c, I was convinced that zfs_immediate_write_sz was the problem. There is a hard coded limit of 4K in there. But even after tweaking that value, I still saw no performance gain.

**Comment by lintonv** [comment]
@behlendorf 

Just wanted to update you on some results from further testing and debug this week. 

We were using a record size of 4K on the ZFS Filesystems were using for send/receive. By increasing this to 128K, we saw the send speed increase from 11 MB/sec to 38 MB/sec. 

Could you let me know what other parameter I am using below could affect the speeds we are seeing. We should be at least getting 120 MB/sec. 

Here are the pool parameters : 

NAME         PROPERTY                    VALUE                       SOURCE
ssn-0-12-36  size                        5.81T                       -
ssn-0-12-36  capacity                    1%                          -
ssn-0-12-36  altroot                     -                           default
ssn-0-12-36  health                      ONLINE                      -
ssn-0-12-36  guid                        16967859640226627487        default
ssn-0-12-36  version                     -                           default
ssn-0-12-36  bootfs                      -                           default
ssn-0-12-36  delegation                  on                          default
ssn-0-12-36  autoreplace                 off                         default
ssn-0-12-36  cachefile                   -                           default
ssn-0-12-36  failmode                    wait                        default
ssn-0-12-36  listsnapshots               off                         default
ssn-0-12-36  autoexpand                  off                         default
ssn-0-12-36  dedupditto                  0                           default
ssn-0-12-36  dedupratio                  1.00x                       -
ssn-0-12-36  free                        5.72T                       -
ssn-0-12-36  allocated                   91.2G                       -
ssn-0-12-36  readonly                    off                         -
ssn-0-12-36  ashift                      12                          local
ssn-0-12-36  comment                     -                           default
ssn-0-12-36  expandsize                  0                           -
ssn-0-12-36  freeing                     0                           default
ssn-0-12-36  fragmentation               0%                          -
ssn-0-12-36  leaked                      0                           default
ssn-0-12-36  feature@async_destroy       enabled                     local
ssn-0-12-36  feature@empty_bpobj         active                      local
ssn-0-12-36  feature@lz4_compress        active                      local
ssn-0-12-36  feature@spacemap_histogram  active                      local
ssn-0-12-36  feature@enabled_txg         active                      local
ssn-0-12-36  feature@hole_birth          active                      local
ssn-0-12-36  feature@extensible_dataset  enabled                     local
ssn-0-12-36  feature@embedded_data       active                      local
ssn-0-12-36  feature@bookmarks           enabled                     local


Here is the parameter of one FS in the pool above: 

[root@ssn-0-12-36 tmp]# zfs get all ssn-0-12-36/g_2G
NAME              PROPERTY                     VALUE                        SOURCE
ssn-0-12-36/g_2G  type                         filesystem                   -
ssn-0-12-36/g_2G  creation                     Fri Feb 20 15:05 2015        -
ssn-0-12-36/g_2G  used                         162K                         -
ssn-0-12-36/g_2G  available                    4.74T                        -
ssn-0-12-36/g_2G  referenced                   162K                         -
ssn-0-12-36/g_2G  compressratio                1.00x                        -
ssn-0-12-36/g_2G  mounted                      yes                          -
ssn-0-12-36/g_2G  quota                        none                         default
ssn-0-12-36/g_2G  reservation                  none                         default
ssn-0-12-36/g_2G  recordsize                   128K                         local
ssn-0-12-36/g_2G  mountpoint                   /ssn-0-12-36/g_2G            default
ssn-0-12-36/g_2G  sharenfs                     off                          default
ssn-0-12-36/g_2G  checksum                     on                           default
ssn-0-12-36/g_2G  compression                  off                          default
ssn-0-12-36/g_2G  atime                        off                          local
ssn-0-12-36/g_2G  devices                      on                           default
ssn-0-12-36/g_2G  exec                         on                           default
ssn-0-12-36/g_2G  setuid                       on                           default
ssn-0-12-36/g_2G  readonly                     off                          default
ssn-0-12-36/g_2G  zoned                        off                          default
ssn-0-12-36/g_2G  snapdir                      hidden                       default
ssn-0-12-36/g_2G  aclinherit                   restricted                   default
ssn-0-12-36/g_2G  canmount                     on                           default
ssn-0-12-36/g_2G  xattr                        on                           default
ssn-0-12-36/g_2G  copies                       1                            default
ssn-0-12-36/g_2G  version                      5                            -
ssn-0-12-36/g_2G  utf8only                     off                          -
ssn-0-12-36/g_2G  normalization                none                         -
ssn-0-12-36/g_2G  casesensitivity              sensitive                    -
ssn-0-12-36/g_2G  vscan                        off                          default
ssn-0-12-36/g_2G  nbmand                       off                          default
ssn-0-12-36/g_2G  sharesmb                     off                          default
ssn-0-12-36/g_2G  refquota                     none                         default
ssn-0-12-36/g_2G  refreservation               none                         default
ssn-0-12-36/g_2G  primarycache                 metadata                     local
ssn-0-12-36/g_2G  secondarycache               metadata                     local
ssn-0-12-36/g_2G  usedbysnapshots              0                            -
ssn-0-12-36/g_2G  usedbydataset                162K                         -
ssn-0-12-36/g_2G  usedbychildren               0                            -
ssn-0-12-36/g_2G  usedbyrefreservation         0                            -
ssn-0-12-36/g_2G  logbias                      latency                      default
ssn-0-12-36/g_2G  dedup                        off                          default
ssn-0-12-36/g_2G  mlslabel                     none                         default
ssn-0-12-36/g_2G  sync                         standard                     default
ssn-0-12-36/g_2G  refcompressratio             1.00x                        -
ssn-0-12-36/g_2G  written                      162K                         -
ssn-0-12-36/g_2G  logicalused                  12.5K                        -
ssn-0-12-36/g_2G  logicalreferenced            12.5K                        -
ssn-0-12-36/g_2G  snapdev                      hidden                       default
ssn-0-12-36/g_2G  acltype                      off                          default
ssn-0-12-36/g_2G  context                      none                         default
ssn-0-12-36/g_2G  fscontext                    none                         default
ssn-0-12-36/g_2G  defcontext                   none                         default
ssn-0-12-36/g_2G  rootcontext                  none                         default
ssn-0-12-36/g_2G  relatime                     off                          default
ssn-0-12-36/g_2G  redundant_metadata           all                          default
ssn-0-12-36/g_2G  overlay                      off                          default
ssn-0-12-36/g_2G  ssn:snap_reserve_percentage  100                          local
ssn-0-12-36/g_2G  ssn:template                 0                            local
ssn-0-12-36/g_2G  ssn:snap_space_used          0                            local
ssn-0-12-36/g_2G  ssn:thin                     0                            local
ssn-0-12-36/g_2G  ssn:snap_enabled             TRUE                         local
ssn-0-12-36/g_2G  ssn:snap_space_total         2048                         local
ssn-0-12-36/g_2G  ssn:vol_size                 2048                         local

**Comment by lintonv** [comment]
@behlendorf Just FYI, we are using 8 SSDs in a RAID-Z1 setup

**Comment by kernelOfTruth** [comment]
@lintonv please take a look at https://github.com/zfsonlinux/zfs/pull/3171

**Comment by lintonv** [comment]
@kernelOfTruth Thank you, but the bottle neck I am seeing looks like the ZFS SEND code. The main problem is that it is a highly serial operation as it reads the blocks from disk and builds the SEND stream. 

I had a ZFS-DISCUSSION thread on this and the Delphix team is working on a prefetch mechanism that will ensure the blocks already exist in cache to mitigate the serial nature of the SEND operation. 

Here is a pointer to that thread (look for Prakash Surya's responses):
https://groups.google.com/a/zfsonlinux.org/forum/#!topic/zfs-discuss/OtWL-gO4y1o

Thoughts, comments?

**Comment by lintonv** [comment]
The root cause is as identified in the above comment. 

But I found a way around the slow ZFS send performance. We increased the number of devices presented in the zpool by striping the disks. We use 8 SSDs and created 4 partitions for each. Therefore, zpool sees a total of 32 devices. This reduces the impact of the highly-serial ZFS send operation, as multiple threads are created in parallel (for each device) and the stream is build quicker. 

With this, we are saturating our 1GIG link consistently. 

@behlendorf Do you want me to close this issue now?

**Comment by behlendorf** [comment]
@lintonv the fix for this from illumos, b738bc5a0f8ccd0281ed06831c34fbe31d2b2138, was merged in to ZoL and  is part of the 0.6.4 tag.  I'm going to close this issue out, but if you have the time it would be great to verify this change improves things for you even under the old configuration.

**Comment by lintonv** [comment]
@behlendorf
We reverted back to the old configuration and tested with 0.6.4. I saw a 6X speed increase. This is fantastic! Thank you for the fix.

**Comment by kpande** [comment]
@lintonv in addition, can you give #2865 + `send -b` to a system with 2865 also applied?

**Comment by AndCycle** [comment]
just got something probably related,

I found an fs on my system use for store huge ISO file accidently use recordsize=16k in the past, 
lot's of files on it have 16k dblk,
rsync can stress out the bandwidth, but the send speed is slow as 6MB/s under 0.6.4,
I can't test if there is any different compare to 0.6.3 because I already upgrade the pool.

**Comment by lintonv** [comment]
@AndCycle Were you able to determine where exactly the bottleneck is? Is it in 'zfs send' or 'zfs recv' or 'ssh'? (assuming you are using ssh for the actual transfer)

0.6.4 has changes for hole_birth and prefetch amount. The hole_birth should help with the transfer of files with holes and the prefetch should help with the transfer of larger files (>1GB)

**Comment by AndCycle** [comment]
@lintonv my backup storage is attached by sata multiplier, I know it's not that good, but that's the  affordable solution for me,

I will try to explain my case,

my system is AMD FX-8350, with 32G ECC memory,
running personal service and few vm, usually have 10GB memory spare for ZFS,
mostly have heavy metadata workload on it due to CrashPlan backup service,

I set arc_max as 4GB, figure larger than this will trigger reboot on my machine with 0.6.4,
in the past I let it use up to 16GB which is fine on 0.6.3 but it's no longer the case,

ztank is original create at 0.6.3
zbackup is newly created at 0.6.4

ztank is 5TBx6 raidz2
zbackup is 4TBx8 raidz1

iso fs is about 1TB,

I use zrep to backup ztank/prod/iso to zbackup/ztank-prod/iso them found this performance issue,
taking few days to init backup 1TB isn't reasonable,

after the backup done, I rename zbackup/ztank-prod/iso to zbackup/ztank-prod/iso-orig,
iso-orig the original fs that contain files with 16k recordsize,

then I destroy ztank/prod/iso, recreate with default 128k recordsize,  do rsync to new iso fs,
zrep ztank/prod/iso to zbackup/ztank-prod/iso, a clean one with 128k recordsize and no past,

zrep won't keep original snapshot set, so there is only one full snapshot at zbackup,
````
zbackup/ztank-prod/iso@zrep_000000
zbackup/ztank-prod/iso-orig@zrep_000000
````

````
zfs send zbackup/ztank-prod/iso-orig@zrep_000000 | pv -trab > /dev/null
 443MiB 0:00:30 [16.7MiB/s] [14.8MiB/s]

zfs send zbackup/main/ztank-prod/iso@zrep_000000 | pv -trab > /dev/null
1.93GiB 0:00:30 [62.6MiB/s] [65.8MiB/s]
````

rsync from iso-orig can stress the bandwidth on PCI esata card at 100MB/s,
there are all DVD/BD iso file so this is expected,

the bottleneck is still there on zfs send,

but I am not sure is this related to your case.

**Comment by lintonv** [comment]
@AndCycle  
Not sure if it is related. 

In 0.6.3, without the new prefetch code (and tuning parameter), my ZFS SEND speeds were approximately 10MiB/s. In 0.6.4, with the prefetch code, I am seeing 6x speeds that is approximately  75MiB/s. 

The ZFS SEND is a highly serialized operation. The bottleneck (as I state in one of the comments above) is the way the stream is build - it reads block by block and builds the stream. The fix would be to parallellize the building of this stream. 

The other work around is to increase the partitions on your drives and present them all to the pool. This way you have multiple devices in this pool and you create the parallelism in that manner. In this setup, I was able to saturate my 1GIG link (getting 112 MiB/s)

**Comment by denis-b** [comment]
Hello, 
I have the same problem on my server, debian wheezy 3.16 / zfsonlinux 6.5.7
On a pool with 2 x 5 SATA disks (raidz2) and 128 G SSD l2arc, sending zvols is very slow, sometimes less than 100ko/s !
sending datasets from the same pool runs at normal speed (50Mo/s), and read operations on kvm VMs using ZVOLs exported with ISCSI runs at the same speed.

Hole_birth is active, and disk i/os are very low.

**Comment by hcw70** [comment]
Actually i also saw slow send / receive for my pool. About 10MB/s on an EVO850 SSD.

What helped a lot was: https://everycity.co.uk/alasdair/2010/07/using-mbuffer-to-speed-up-slow-zfs-send-zfs-receive/ 

So i did (since cloning local partitins) a 

`zfs send -R rpool-mediasrv@move-to-8k | mbuffer -s 128k -m 1g | zfs receive -F -v rpool-mediasrv-4k
`

**Comment by Sawtaytoes** [comment]
> 

What's `mbuffer` and how did it help you?

I'm using TrueNAS and don't have access to the command itself, but my transfers are going at 1/3rd the VPN speed even though local transfers are much faster. I'm wondering if it's something to do with latency when doing a zfs send over SSH and if it's even related to the topic in this thread.

**Comment by ryao** [comment]
mbuffer is a userland memory buffer. For example, you can do ` zfs send | ssh 'mbuffer -s 128k -m 1g | zfs receive ...'` to cache things in mbuffer so that transfers over the network are not blocked by a buffer on the other end unless the buffer is so full that it does not make sense to keep receiving.
