### ISSUE TITLE
Consolidate non-ZFS modules into libgenunix.ko

### ISSUE THREAD

**Issue by ryao** [zfsonlinux/zfs#2748]
The modules znvpair, zcommon, zunicode, zavl and the future ztaskq are collectively part of genunix on Illumos. It might make sense to consolidate them rather than keep them broken up into separate modules. The name genunix itself is too generic, but one possible name would be libgenunix. It would make sense to those coming from Illumos/Solaris, but not be so generic that we would risk name conflicts. I am posting this issue for feedback on the idea.

**Comment by behlendorf** [comment]
Closing.  We intend to do something like this for 0.8.0 but there's no need to keep the issue open.
