### ISSUE TITLE
Enable KSM for memory allocated for ARC cache

### ISSUE THREAD

**Issue by Sachiru** [zfsonlinux/zfs#2772]
For non-deduplicated datasets or filesystems, ARC cache retains full blocks in memory even if they are duplicates of something else. On systems that serve as backing storage for users (shared folder containing material/model/cad libraries/library families and/or versioned executables), this can result in several duplicate objects stored in RAM, which can be viewed as a waste of ARC resources.

KSM (Kernel Same Page Merging, http://en.wikipedia.org/wiki/Kernel_SamePage_Merging_(KSM) ) is supposed to optimize memory usage especially for memory-heavy applications. Although it is true that blocks have variable sizes, they are still allocated as 4k pages in memory (IIRC), which can then be examined and deduplicated. 

This is beneficial even if the recovered memory ratios of ARC is small due to the inherently large nature of ARC allocations. Even if only duplicated data is around 10% of ARC, due to typically large ARC sizes significant data gains are observed. Deduplicating ARC contents by means of KSM also means that more data gets fitted into the ARC cache, and that the deduplication code need not be maintained by ZoL devs, only the glue code that allows ARC to be seen by KSM.

**Comment by kernelOfTruth** [comment]
great idea !

there were some suggested improvements to KSM handling in the linux kernel mailing list (in April if I remember correctly), I'll see whether I can post them here for reference, hopefully they'll make it into the kernel soon

so the performance impact should be fairly negligible

**Comment by kpande** [comment]
:+1:

**Comment by kernelOfTruth** [comment]
@kpande it also affects ZFS ?

for my kind of workflow there in general wasn't much data reported to be merged: 10-200 MiB or with lots of firefox,  chromium tabs and PDF files some more

**Comment by kpande** [comment]
for me with 2GB of ram is invaluable to compress even just 500MB of pages.

**Comment by kernelOfTruth** [comment]
Agreed :)

**Comment by behlendorf** [comment]
This situation here will be considerably better in the 0.7.0 release.  ARC buffers are now compressed in memory and the ARC is better about not keeping multiple copies of the same buffer.

**Comment by spacelama** [comment]
> This situation here will be considerably better in the 0.7.0 release.  ARC buffers are now compressed in memory and the ARC is better about not keeping multiple copies of the same buffer.

Gosh, looking forward to this.  Thanks for all your good work, Brian!

-- 
Tim Connors
