### ISSUE TITLE
ZFS should check SMART data for drives which report it

### ISSUE THREAD

**Issue by kpande** [zfsonlinux/zfs#2777]
There's been a lot (sorry for just throwing around a numberless word) of issues reported lately which end up being hardware faults.

Most of the time, ZFS says there are no errors. zpool status doesn't return any hints where to look, the only usual symptom is having tasks hang or pause in zio_wait or other zio-related incidents.

A solution I've been considering, can ZFS probe SMART data when it is available, and show those potential issues in zpool status?

**Comment by wmantly** [comment]
Any update on this feature?

**Comment by drescherjm** [comment]
zpool status implemented this months ago.

**Comment by tonyhutter** [comment]
`zpool status -c smart,smartx`

Unfortunately there's no good library to read in SMART stats, so it would be hard to integrate it into ZED. The `smartctl` people don't seem eager to write one (https://www.smartmontools.org/ticket/501) and the only other attempt stopped development years ago (http://0pointer.de/blog/projects/being-smart.html).  If someone were to come along and write a proper SMART library, I think it would be very popular!

**Comment by rlaager** [comment]
https://github.com/zfsonlinux/zfs/pull/7178 https://github.com/zfsonlinux/zfs/pull/7193
