### ISSUE TITLE
yum update breaks zfs for Centos 7

### ISSUE THREAD

**Issue by rhagu** [zfsonlinux/zfs#2800]
I am using the repositories mentioned here: http://zfsonlinux.org/epel.html for Centos 7 and get an error message after the last update of zfs:

[root@localhost ~]# zpool status
Failed to load ZFS module stack.
Load the module manually by running 'insmod <location>/zfs.ko' as root.

The pools are not imported either, dmesg shows no results, when greped for: zfs ZFS or spl.

Except for bug #2755 the setup worked prior to the update.

[root@localhost ~]# yum info zfs
Geladene Plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
- base: ftp.hosteurope.de
- epel: ftp.icm.edu.pl
- extras: mirror2.hs-esslingen.de
- updates: ftp.uni-bayreuth.de
  Installierte Pakete
  Name       : zfs
  Architektur : x86_64
  Version    : 0.6.3
  Ausgabe    : 1.1.el7.centos
  Größe : 697 k
  Quelle      : installed
  Aus Quelle  : zfs
  Zusammenfassung: Commands to control the kernel modules and libraries
  URL        : http://zfsonlinux.org/
  Lizenz      : CDDL
  Beschreibung: This package contains the ZFS command line utilities.

[root@localhost ~]# yum info zfs-dkms
Geladene Plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
- base: ftp.hosteurope.de
- epel: mirror.euserv.net
- extras: mirror2.hs-esslingen.de
- updates: ftp.uni-bayreuth.de
  Installierte Pakete
  Name       : zfs-dkms
  Architektur : noarch
  Version    : 0.6.3
  Ausgabe    : 1.1.el7.centos
  Größe : 11 M
  Quelle      : installed
  Aus Quelle  : zfs
  Zusammenfassung: Kernel module(s) (dkms)
  URL        : http://zfsonlinux.org/
  Lizenz      : CDDL
  Beschreibung: This package contains the dkms ZFS kernel modules.

[root@localhost ~]# yum info spl-dkms
Geladene Plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
- base: ftp.hosteurope.de
- epel: ftp.icm.edu.pl
- extras: mirror2.hs-esslingen.de
- updates: ftp.uni-bayreuth.de
  Installierte Pakete
  Name       : spl-dkms
  Architektur : noarch
  Version    : 0.6.3
  Ausgabe    : 1.1.el7.centos
  Größe : 2.9 M
  Quelle      : installed
  Aus Quelle  : zfs
  Zusammenfassung: Kernel module(s) (dkms)
  URL        : http://zfsonlinux.org/
  Lizenz      : GPLv2+
  Beschreibung: This package contains the dkms kernel modules required to emulate
          : several interfaces provided by the Solaris kernel.

[root@localhost ~]# uname -r
3.10.0-123.el7.x86_64

[root@localhost ~]# find /lib/modules/$(uname -r)/ -name zfs.ko
[root@localhost ~]#

**Comment by gmelikov** [comment]
Close as stale.

If it's actual - feel free to reopen.
