### ISSUE TITLE
Do not are working commands ZFS...

### ISSUE THREAD

**Issue by apaxucok** [zfsonlinux/zfs#2803]
Hello! I compiled the kernel with modules SPL and ZFS for my Parallella board, everything has been successful. After that, I loaded the Ubuntu 14.04 with this kernel and decided to test the native ZFS, but faced with such a problem does not work ZFS commands. Here is the log:

linaro-nano:~> dmesg | grep -i zfs

ZFS: Loaded module v0.6.3-99_g83e9986, ZFS pool version 5000, ZFS filesystem version 5

linaro-nano:~> dmesg | grep -i spl

SPL: Loaded module v0.6.3-10_ge302072
SPLAT: Loaded module v0.6.3-10_ge302072

linaro-nano:~> sudo su

root@linaro-nano:/home/linaro# cd /usr/local/sbin/

root@linaro-nano:/usr/local/sbin# ls

spl  splat  zdb  zfs  zinject  zpios  zpool  ztest

root@linaro-nano:/usr/local/sbin# zpool

bash: /usr/local/sbin/zpool: No such file or directory

root@linaro-nano:/usr/local/sbin# z
zcat          zenity        zinject       zipnote       zpool
zcmp          zfgrep        zip           zipsplit      zpool_layout
zdb           zforce        zipcloak      zless         zsoelim
zdiff         zfs           zipdetails    zmore         ztest
zdump         zgrep         zipgrep       znew  
zegrep        zic           zipinfo       zpios  
root@linaro-nano:/usr/local/sbin# ./zpool 

bash: ./zpool: No such file or directory
root@linaro-nano:/usr/local/sbin# 

And now I do not know what to do next.Please help me...

**Comment by behlendorf** [comment]
Closing as stale.
