### ISSUE TITLE
Pool gets stuck in "replacing" state

### ISSUE THREAD

**Issue by elan** [zfsonlinux/zfs#2806]
Pool shown [here](https://gist.github.com/elan/408fca48b6cf6f624404).

What happened to get into that state:

- I pulled two drives which were showing errors (scsi-SATA_ST3000DM001-1CH_S1F0WL4R and scsi-SATA_ST3000DM001-1CH_S1F0XNEG) and replaced them.
- I made the actual replacements:

```
2014-10-14.00:47:35 zpool replace whopper -o ashift=9 scsi-SATA_ST3000DM001-1CH_S1F0XNEG scsi-SATA_HGST_HDN724030A_PK2234P8JJEUYY
2014-10-14.00:49:29 zpool replace -f whopper -o ashift=9 scsi-SATA_ST3000DM001-1CH_S1F0WL4R scsi-SATA_WDC_WD30EFRX-68_WD-WMC4N1871345
```

- It started resilvering, and during this process, a third drive showed errors. It stayed online, thankfully and the resilvering completed showing 2 errors.
- I did a `status -v` to see the two corrupted files, and deleted them.
- I was then left with `status -v` showing me this:

```
        whopper/media/movies:<0x405b>
        whopper/media/movies:<0x43a0>
```

- Based on a tip I read [here](http://unixetc.co.uk/2012/01/22/zfs-corruption-persists-in-unlinked-files/) I started and then stopped a scrub. This made the errors go away and it moved to showing the usual `No known data errors`.
- Based on advice from @ryao, I started a scrub and let it run to completion. During this scrub the pesky third drive failed and was moved into `FAULTED` state.
- Once the scrub finished, the two "replacing" drives successfully finished their replacement, and all was back to normal (except for the drive which needs replacing, but that's unrelated).

**Comment by behlendorf** [comment]
Closing as out of date.
