### ISSUE TITLE
ZED does not detect a pool transitioning to DEGRADED state

### ISSUE THREAD

**Issue by dswartz** [zfsonlinux/zfs#2808]
CentOS 7 host.  A pool tank-copy with two drives in a mirror.  If I offline one drive, the pool goes degraded as expected, but I never get an email notification.  If I online the drive, I do get a notification that the pool has finished resilvering.  While the latter is nice to know, I would argue the current behavior is completely backward.  Looking at /var/log/messages, on the offline I see:

Oct 18 14:45:01 centos7-ha3 zed: eid=81 class=config.sync pool=tank-copy

whereas the online yields:

Oct 18 14:45:26 centos7-ha3 zed: eid=82 class=statechange
Oct 18 14:45:26 centos7-ha3 zed: eid=83 class=resilver.start pool=tank-copy
Oct 18 14:45:27 centos7-ha3 zed: eid=84 class=config.sync pool=tank-copy
Oct 18 14:45:27 centos7-ha3 zed: eid=85 class=resilver.finish pool=tank-copy

I'm guessing here that the culprit is the config.sync event for the offline is not generating a statechange?  What I mean by 'behavior backward' is that while it's nice to know the pool is redundant again, it's far more critical to know when it stopped being redundant.

**Comment by EloProf** [comment]
Is there an update on this?

I am currently experimenting on Ubuntu 14.04 LTS Trusty with a raidz2 pool with 5 drives and spare. To try and test zed and autoreplace I shut down the machine and removed one of the drives.

I was expecting autoreplace to switch to the spare, but I saw a mention somewhere that this is not implemented yet. But at least I was expecting to get an E-Mail about the now "degraded" pool.

Feel free to ask for more information if that helps with the issue.

**Comment by Ralithune** [comment]
Would be nice to know if this code change went in or not.

**Comment by behlendorf** [comment]
It has not.  But it's something we should consider pulling in with the related FMA work in PR #4673.

**Comment by behlendorf** [comment]
This issue has been resolved as part of the recent FMA work in commit 976246fadde25790cec3de50c01c689d98d84e0c and 0df15db98f185c948239c236c9e51d7ce14adb71.  State change events are now generated for additional state changes.

**Comment by Ralithune** [comment]
@behlendorf When will these changes be live in the centos yum repository?  The current version available appears to be .6.5.7, which is even behind what's on the website.
