### ISSUE TITLE
zap_increment() and zap_increment_int() not thread-safe

### ISSUE THREAD

**Issue by thegreatgazoo** [zfsonlinux/zfs#2818]
Comments in include/sys/zap.h claims:
- The ZAP routines are thread-safe.
- The ZAP's locking scheme makes its routines thread-safe.

But it seems not true for zap_increment() and zap_increment_int(): zap_lookup(old_value); zap_update(old_value+delta); - there could be other updates between lookup and update.

ZFS only calls them in the txg_sync thread: dsl_pool_sync()->dmu_objset_do_userquota_updates()->do_userquota_update()->zap_increment_int(). So it's not a problem. But it can cause trouble to Lustre and any future caller.

It's possible to serialize at the callers but I think it makes sense to do it at ZAP layer since it'd need exclusive access to do zap_update() anyway.

**Comment by behlendorf** [comment]
Upon further reflection I think the comment about the ZAP's being thread-safe is correct.  The `zap_increment()` functions are implemented in such a way where it's technically safe to have concurrent callers.  However, they are not atomic.  Callers need to take care to perform this serialization themselves.
