### ISSUE TITLE
'zfs set mountpoint=xxx' missing from history

### ISSUE THREAD

**Issue by behlendorf** [zfsonlinux/zfs#2825]
The `zfs set mountpoint=xxx` command is not logged for non-root datasets.  Other `zfs set` commands appear to be logged properly.

```
$ zpool create tank /dev/vdb
$ zfs create tank/fish
$ zfs set mountpoint=/var/lib/tank tank
$ zfs set mountpoint=/var/lib/fish tank/fish

$ zpool history 
History for 'tank':
2014-10-23.18:34:49 zpool create tank /dev/vdb
2014-10-23.18:34:55 zfs create tank/fish
2014-10-23.18:35:54 zfs set mountpoint=/var/lib/tank tank
<missing zfs set...>
```

**Comment by loli10K** [comment]
Is this still an issue? After some testing on older versions i think this was fixed in https://github.com/zfsonlinux/zfs/commit/fb8e608d9dacf2f6703da8c853f6086e4dd79824.

**Comment by behlendorf** [comment]
Yup, this was fixed and just not closed.  The zfs_history regression tests verify this functionality now to avoid any future accidental regressions.
