### ISSUE TITLE
sparse file based zpool import via loop device fails

### ISSUE THREAD

**Issue by richtekp** [zfsonlinux/zfs#2830]
When I want to import a zpool after exporting it via a loop device it fails although it suceeds when invoking `zpool import` with `-d` option pointing to the parent directory of the sparse file (vdev).

Issue and reproduction:

    # sudo -i
    # truncate -s 64M ~/test.img
    # zpool create test ~/test.img
    # zpool list
    NAME      SIZE  ALLOC   FREE    CAP  DEDUP  HEALTH  ALTROOT
    test     59,5M    91K  59,4M     0%  1.00x  ONLINE  -
    # zpool export test
    # MYLOOP=`losetup -f`
    # echo $MYLOOP
    /dev/loop0
    # losetup $MYLOOP ~/test.img 
    # zpool import
       pool: test
         id: 16873090859680272297
      state: UNAVAIL
     status: One or more devices are missing from the system.
     action: The pool cannot be imported. Attach the missing
	    devices and try again.
       see: http://zfsonlinux.org/msg/ZFS-8000-3C
     config:
    
	    test          UNAVAIL  insufficient replicas
	      /dev/loop0  UNAVAIL  cannot open
    # zpool import test
    cannot import 'test': no such device in pool
	    Destroy and re-create the pool from
        a backup source.
    # zpool import -d ~
       pool: test
         id: 16873090859680272297
      state: ONLINE
     action: The pool can be imported using its name or numeric identifier.
     config:
    
	    test              ONLINE
    	  /root/test.img  ONLINE

Running 0.6.3 on Ubuntu 14.04 amd64.

**Comment by behlendorf** [comment]
Closing.  This is behaving as expected.
