### ISSUE TITLE
Ubuntu package : missing "file" package dependency

### ISSUE THREAD

**Issue by benalbrecht** [zfsonlinux/zfs#2833]
#1755 applies to Ubuntu as well; there should be a dependency on "file"

Setting up spl-dkms (0.6.3-1~trusty) ...
Loading new spl-0.6.3 DKMS files...
First Installation: checking all kernels...
Building only for 3.13.0-24-generic
Building initial module for 3.13.0-24-generic
/var/lib/dkms/spl/0.6.3/build/configure: line 6452: /usr/bin/file: No such file or directory

**Comment by rlaager** [comment]
This is fixed in the packages that have been merged in Ubuntu.
