### ISSUE TITLE
ZFS Linux AIO Support error compilation? Spl?

### ISSUE THREAD

**Issue by MrJookie** [zfsonlinux/zfs#2835]
Hello,
I am getting error while compiling ZFS Linux AIO Support.
I've compiled spl and installed, then failed at zfs compiling.

I think it is the problem related to spl? I cloned spl repo, but which version should I use?

Thanks

/tmp/zfs-build-root-NvrYIZ3r/BUILD/zfs-kmod-0.6.3/_kmod_build_3.2.0-4-amd64/module/zfs/../../../zfs-0.6.3/module/zfs/spa_config.c:35:2                         5: fatal error: sys/utsname.h: No such file or directory
compilation terminated.
  CC [M]  /tmp/zfs-build-root-NvrYIZ3r/BUILD/zfs-kmod-0.6.3/_kmod_build_3.2.0-4-amd64/module/zfs/../../../zfs-0.6.3/module/zfs/spa_err                         log.o
make[9]: *** [/tmp/zfs-build-root-NvrYIZ3r/BUILD/zfs-kmod-0.6.3/_kmod_build_3.2.0-4-amd64/module/zfs/../../../zfs-0.6.3/module/zfs/spa                         _config.o] Error 1
make[9]: *** Waiting for unfinished jobs....
make[8]: *** [/tmp/zfs-build-root-NvrYIZ3r/BUILD/zfs-kmod-0.6.3/_kmod_build_3.2.0-4-amd64/module/zfs] Error 2
make[7]: *** [_module_/tmp/zfs-build-root-NvrYIZ3r/BUILD/zfs-kmod-0.6.3/_kmod_build_3.2.0-4-amd64/module] Error 2
make[6]: *** [sub-make] Error 2
make[5]: *** [all] Error 2
make[5]: Leaving directory `/usr/src/linux-headers-3.2.0-4-amd64'
make[4]: *** [modules] Error 2
make[4]: Leaving directory `/tmp/zfs-build-root-NvrYIZ3r/BUILD/zfs-kmod-0.6.3/_kmod_build_3.2.0-4-amd64/module'
make[4]: Entering directory `/tmp/zfs-build-root-NvrYIZ3r/BUILD/zfs-kmod-0.6.3/_kmod_build_3.2.0-4-amd64'
make[4]: Nothing to be done for `all-am'.
make[4]: Leaving directory `/tmp/zfs-build-root-NvrYIZ3r/BUILD/zfs-kmod-0.6.3/_kmod_build_3.2.0-4-amd64'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/tmp/zfs-build-root-NvrYIZ3r/BUILD/zfs-kmod-0.6.3/_kmod_build_3.2.0-4-amd64'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/tmp/zfs-build-root-NvrYIZ3r/BUILD/zfs-kmod-0.6.3/_kmod_build_3.2.0-4-amd64'
error: Bad exit status from /tmp/zfs-build-root-NvrYIZ3r/TMP/rpm-tmp.WqaR00 (%build)

**Comment by ryao** [comment]
Is there anything left for us to do here?

**Comment by behlendorf** [comment]
Not a thing.  I just lost track of this one.  Closing it out.
