### ISSUE TITLE
0.6.3 can't start (oops) on gentoo current

### ISSUE THREAD

**Issue by 2011** [zfsonlinux/zfs#2836]
Sorry, if I am missing something obvious (both in terms of spotting the problem and reporting the problem) - i am pretty much a neophyte at this.

Everything was working fine on 0.6.2 with kernels 3.10.x. Just upgraded everything (kernel 3.16.5, gcc 4.8.3, zfs 0.6.3, and know when I attempt to start zfs, I get:

# /etc/init.d/zfs start
* Starting ZFS ...
* Checking if ZFS modules present
* Checking if zfs userspace tools present
/etc/init.d/zfs: line 52: 11827 Killed modprobe $ZFS_MODULE
* Failed to load the zfs module, check 'dmesg|tail'. [ !! ]
* ERROR: zfs failed to start

And in the system log:

[ 3741.878046] SPL: Loaded module v0.6.3-r0-gentoo
[ 3741.878408] BUG: unable to handle kernel paging request at 0000000100000004
[ 3741.878412] IP: [<ffffffff814b6e92>] _raw_spin_lock+0x5/0x1c
[ 3741.878416] PGD 26bf96067 PUD 0 
[ 3741.878418] Oops: 0002 [#1] SMP 
[ 3741.878419] Modules linked in: znvpair(PO+) spl(O) vboxnetflt(O) vboxnetadp(O) vboxdrv(O) nvidia(PO)
[ 3741.878425] CPU: 0 PID: 11827 Comm: modprobe Tainted: P O 3.16.5-gentoo #1
[ 3741.878427] Hardware name: MSI MS-7586/P55-CD53 (MS-7586) , BIOS V1.11 03/03/2011
[ 3741.878429] task: ffff8802e423f600 ti: ffff8802e41e8000 task.ti: ffff8802e41e8000
[ 3741.878431] RIP: 0010:[<ffffffff814b6e92>] [<ffffffff814b6e92>] _raw_spin_lock+0x5/0x1c
[ 3741.878434] RSP: 0018:ffff8802e41ebd28 EFLAGS: 00010286
[ 3741.878435] RAX: 0000000000000100 RBX: 0000000100000000 RCX: 0000000000000000
[ 3741.878437] RDX: ffff8802e4290000 RSI: ffff8802e41ebd60 RDI: 0000000100000004
[ 3741.878438] RBP: ffff8802e41ebd50 R08: 00000000000143a0 R09: ffffea0002002e00
[ 3741.878440] R10: 8080808080808080 R11: ffffffff81108edc R12: ffff8802e41ebd60
[ 3741.878441] R13: ffffffff81815020 R14: 0000000000000000 R15: 0000000000000001
[ 3741.878443] FS: 00007fb00bd42700(0000) GS:ffff88032fc00000(0000) knlGS:0000000000000000
[ 3741.878445] CS: 0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 3741.878446] CR2: 0000000100000004 CR3: 00000002e41a0000 CR4: 00000000000007f0
[ 3741.878447] Stack:
[ 3741.878448] ffffffffa0a6b02b 0000000000000000 00007ffffffff000 0000000000000000
[ 3741.878450] 0000000000000000 00007ffffffff000 ffffffffa0a6b0dd ffff8803214ea8e0
[ 3741.878453] ffff880322c343c0 ffffffffa0a7c748 ffff88030dba3a40 ffffffffa0a6b74c
[ 3741.878455] Call Trace:
[ 3741.878459] [<ffffffffa0a6b02b>] ? set_fs_pwd+0x1a/0x5f [spl]
[ 3741.878466] [<ffffffffa0a6b0dd>] ? vn_set_pwd+0x6d/0x90 [spl]
[ 3741.878471] [<ffffffffa0a7c748>] ? nvlist_lookup_nvpair_embedded_index+0x13/0x13 [znvpair]
[ 3741.878474] [<ffffffffa0a6b74c>] ? spl_setup+0xc/0x21 [spl]
[ 3741.878479] [<ffffffffa0a7c74d>] ? init_module+0x5/0x8 [znvpair]
[ 3741.878482] [<ffffffff81000391>] ? do_one_initcall+0x17a/0x18d
[ 3741.878485] [<ffffffff810a6ee0>] ? load_module+0x1680/0x1b7c
[ 3741.878487] [<ffffffff810a48cc>] ? store_uevent+0x30/0x30
[ 3741.878490] [<ffffffff810fcea4>] ? vfs_read+0xfb/0x11e
[ 3741.878493] [<ffffffff810a74b8>] ? SyS_finit_module+0x4a/0x5e
[ 3741.878495] [<ffffffff814b760b>] ? tracesys+0xdd/0xe2
[ 3741.878496] Code: f0 81 2f 00 01 00 00 48 8b 3c 24 be 00 02 00 00 e9 e7 96 ba ff c6 07 00 be 00 02 00 00 48 8b 3c 24 e9 d6 96 ba ff b8 00 01 00 00 <f0> 66 0f c1 07 0f b6 d4 38 c2 74 0a 8a 07 38 d0 74 04 f3 90 eb 
[ 3741.878514] RIP [<ffffffff814b6e92>] _raw_spin_lock+0x5/0x1c
[ 3741.878516] RSP <ffff8802e41ebd28>
[ 3741.878517] CR2: 0000000100000004
[ 3741.878519] ---[ end trace a81552371d939114 ]---

Let me know what additional information you need to help track this down.

Thank you in advance.

**Comment by behlendorf** [comment]
Closing.  This was a Gentoo specific issue for an old release.
