### ISSUE TITLE
zvol threads are created whether zvol is in use or not

### ISSUE THREAD

**Issue by thegreatgazoo** [zfsonlinux/zfs#2838]
I have many servers that don't use zvol at all, yet there's always 32 zvol threads on each (see zvol_init()). It'd be nice if they are created on demand. Or maybe the zvol can be built into a separate module that gets loaded on demand.

**Comment by behlendorf** [comment]
Resolved by zfsonlinux/spl@f7a973d99b5e272f4a6223b8fb7db4fc6d363b41 and aa9af22cdf8d16c197974c3a478d2053b3bed498.
