### ISSUE TITLE
Disappearing snapshots

### ISSUE THREAD

**Issue by TyberiusPrime** [zfsonlinux/zfs#2841]
Hello,

I have a reoccurring occurrence where a snapshot that was accessed just now suddenly has no files in .zfs/snapshot/xyz. It was being accessed via samba - mostly an sqlite file being reopened often (websystem...) inside the snapshot.

The data is not gone though.
- rebooting restores the snapshot
- I believed I once was able to restore it by unmounting/mounting the zfs in question
- but now I think it might have been a timeout thing - because the snapshot once reappeared
after about 10 minutes (300 second timeout?) - and because I haven't been able
to unmount the zfs in question during later occurrences.
- toggling snapdir = visible and back to hidden does not help.

I can not mount the snapshot somewhere else with mount -t zfs - it claims
it is already mounted.
This suggests to me that it's not the unmount behavior that's causing the disappearance.

I'm on ubuntu 14.04 with the current 8~trusty package from zfs-native/stable.
Scrub is clean, RAM is ecc.

I've made a lengthy zfs-discuss thread where I kept posting 'life', 
but I think the above description distills the relevant information:
https://groups.google.com/a/zfsonlinux.org/forum/#!topic/zfs-discuss/aAJsQoSY3BQ

Best regards
Florian

**Comment by Mic92** [comment]
@behlendorf It exists. From my understanding https://github.com/yshui/zfs/commit/3ab9d33578e0ad26c31bb7c6a55a795e3b5e1af5 should only affect only one snapshot, but in my case it affects all snapshots. My questions is, why the second argument ends with a ` (deleted)` suffix.

**Comment by behlendorf** [comment]
@Mic92 `(deleted)` will be automatically appended to a directory entry (dentry) which isn't hashed in the dcache.  I think you're definitely on the right track here, the key will be figuring out how and why the dentry is getting unhashed.

**Comment by marco-prati** [comment]
I've tried pulling yshui@3ab9d33 but the problem still persists.

**Comment by behlendorf** [comment]
@maci0 what kernel version are you using?  This may only impact 3.18 kernels.

**Comment by Mic92** [comment]
@behlendorf Yes 3.18 breaks this feature.

**Comment by behlendorf** [comment]
I've proposed a patch in issue #3344 to address this.
