### ISSUE TITLE
error while scrubbing

### ISSUE THREAD

**Issue by webgur** [zfsonlinux/zfs#2843]
Recently my zfs share started to behave strange. I can read all files, but I can't create new files or new directories in some directories.

the scrub seems to be stuck at 35.93%

sudo zpool status

  pool: arkiv
 state: ONLINE
status: One or more devices has experienced an unrecoverable error.  An
        attempt was made to correct the error.  Applications are unaffected.
action: Determine if the device needs to be replaced, and clear the errors
        using 'zpool clear' or replace the device with 'zpool replace'.
   see: http://zfsonlinux.org/msg/ZFS-8000-9P
  scan: scrub in progress since Sun Oct 19 23:11:20 2014
    6.55T scanned out of 18.2T at 13.6M/s, 250h55m to go
    2.50M repaired, 35.93% done
config:

        NAME                                          STATE     READ WRITE CKSUM
        arkiv                                         ONLINE       0     0     0
          raidz2-0                                    ONLINE       0     0     0
            ata-WDC_WD30EFRX-68EUZN0_WD-WMC4N1549394  ONLINE       0     0     2  (repairing)
            ata-WDC_WD30EFRX-68EUZN0_WD-WMC4N1671754  ONLINE       0     0     2  (repairing)
            ata-WDC_WD30EFRX-68EUZN0_WD-WMC4N1671886  ONLINE       0     0     1  (repairing)
            ata-WDC_WD30EFRX-68EUZN0_WD-WMC4N1672798  ONLINE       0     0     1  (repairing)
            ata-WDC_WD30EFRX-68EUZN0_WD-WMC4N1830211  ONLINE       0     0     0
            ata-WDC_WD30EFRX-68EUZN0_WD-WMC4N1839805  ONLINE       0     0     0
            ata-WDC_WD30EFRX-68EUZN0_WD-WMC4N1841065  ONLINE       0     0     3  (repairing)
            ata-WDC_WD30EFRX-68EUZN0_WD-WMC4N1841833  ONLINE       0     0     0
            ata-WDC_WD30EFRX-68EUZN0_WD-WMC4N1842525  ONLINE       0     0     3  (repairing)
            ata-WDC_WD30EFRX-68EUZN0_WD-WMC4N1848381  ONLINE       0     0     2  (repairing)

errors: No known data errors

I run dmesg on that server and see this
http://pastebin.com/dWzzWhNT

Can someone give me a pointer on how to continue the troubleshooting?

**Comment by behlendorf** [comment]
Closing.  There's not enough information here to be actionable.
