### ISSUE TITLE
ZFS tries to import zpool using whole disk device instead of partition

### ISSUE THREAD

**Issue by dpfountain** [zfsonlinux/zfs#2844]
Following from a discussion on [zfs-discuss](https://groups.google.com/a/zfsonlinux.org/forum/#!topic/zfs-discuss/h3a1xdakS0A):

Problem:
When I try to import my zpool 'ashes' from my external USB-3 disk, ZFS attempts to import using the whole disk device name instead of the disk partition. The zpool 'ashes' is located on the first partition. After posting the issue to zfs-discuss, a number of things were discussed, but ultimately it looks like a bug in ZFS' ability to distinguish whether the zpool is in a partition or the whole disk. 
https://gist.github.com/dpfountain/00fa63aa51803070d9b4#file-zpool-import

Secondary Problem:
While diagnosing the problem of the still offline zpool 'ashes', this happened. 
```
#zdb -C ashes
zdb: can't open 'ashes' : No such file or directory

#zdb -C -e ashes
Segmentation fault (core dumped)
```

Workaround:
If I create a directory somewhere else, create a softlink to the disk partition, and tell zpool import to look in that directory instead, then my zpool will import. But if I reboot, ZFS again attempts to read from the whole disk instead of the partition, and then I have to manually import again using the new directory. This is not desirable, as I need the disk to be plug'n'backup, as it was before. 

zpool status (with workaround)
https://gist.github.com/dpfountain/a6d50fc14d37012130ce#file-gistfile1-txt

Expectations:
ZFS should behave like mdraid and filesystems such as ext4, autodetecting and mounting any zpools, regardless if they're in a partition, whole disk, external, USB, etc.

Erasing my zpool and creating a new one without setting up partitions is not an acceptable solution. I really want to keep using ZFS, but if it can't handle partitions, I'd rather go back to ext4 on the external disk and use rsync. 

Background:
ZFS automounted this disk just fine before I upgraded to Ubuntu 14.04. After upgrading, the systemd/udev device naming scheme changed. I also have a raidz on internal hard drives (six disks, on partition 4), which suffered from the device name problem, but I was able to create softlinks in the /dev/disk/by-id directory and ZFS grabbed the correct devices and partitions fine. However, this did not work for my external USB-3 disk.

I'd like to point out that mdraid and ext4 on the same server had no problem with the device name changes (picked up automatically) and do not have a problem with partitions.

Phoenix is a home office storage and backup server running Ubuntu 14.04. It has 6 internal hard disks, partitioned, with mdraid 1 for /boot, mdraid 6 for /, mdraid 1 for /swap, and raidz2 for /cavern (main storage). System backup is on zpool 'ashes', located on an external Seagate hard disk via USB-3.

Sorry, I do not have specific information for Ubuntu, the device names, or ZFS versions before the upgrade to 14.04.

System Information:
```
Linux phoenix 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
32G RAM non-ECC

All the files:
https://gist.github.com/dpfountain/f649d115350d99d804a9

**Comment by Finkregh** [comment]
i anybody needs some more data: i got some W)

**Comment by kpande** [comment]
@Finkregh check out #3145

**Comment by Finkregh** [comment]
@kpande thanks a bunch for the hint, i'll try the patch

**Comment by behlendorf** [comment]
@Finkregh Actually can you please test #3219, it's an improved version of #3145.

**Comment by Finkregh** [comment]
as far as i can see #3219 has been merged into the latest version?
I have tried again with debian 8/jessie and ZOL v0.6.4-1.1-1 and again get the hdd itself with a label and not just the partition.

```
# zpool create -o ashift=12 tank /dev/sdb2
# zpool import -R /mnt tank
cannot import 'tank': a pool with that name already exists
use the form 'zpool import <pool | id> <newpool>' to give it a new name
# zdb -l /dev/sdb | head -n 30
--------------------------------------------
LABEL 0
--------------------------------------------
failed to unpack label 0
--------------------------------------------
LABEL 1
--------------------------------------------
failed to unpack label 1
--------------------------------------------
LABEL 2
--------------------------------------------
    version: 5000
    name: 'tank'
    state: 0
    txg: 24
    pool_guid: 1221358822546281551
    errata: 0
    hostid: 162571048
    hostname: 'aller'
    top_guid: 9946132713576826893
    guid: 9946132713576826893
    vdev_children: 1
    vdev_tree:
        type: 'disk'
        id: 0
        guid: 9946132713576826893
        path: '/dev/sdb2'
        whole_disk: 0
        metaslab_array: 35
        metaslab_shift: 34

# zdb -l /dev/sdb2 | head -n 30
--------------------------------------------
LABEL 0
--------------------------------------------
    version: 5000
    name: 'tank'
    state: 0
    txg: 24
    pool_guid: 1221358822546281551
    errata: 0
    hostid: 162571048
    hostname: 'aller'
    top_guid: 9946132713576826893
    guid: 9946132713576826893
    vdev_children: 1
    vdev_tree:
        type: 'disk'
        id: 0
        guid: 9946132713576826893
        path: '/dev/sdb2'
        whole_disk: 0
        metaslab_array: 35
        metaslab_shift: 34
        ashift: 12
        asize: 2998438461440
        is_log: 0
        create_txg: 4
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
--------------------------------------------
# parted -l
[...]
Model: ATA 
Disk /dev/sdb: 3001GB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags: pmbr_boot

Number  Start   End     Size    File system  Name  Flags
 3      1049kB  2097kB  1049kB                     bios_grub
 1      2097kB  2150MB  2147MB  ext3
 2      2150MB  3001GB  2998GB

```

:(

**Comment by dasjoe** [comment]
Not related to the issue, but you are aware you just overwrote `/dev/sdb2`'s old pool with a newly created one?
That's why `zpool import -R /mnt tank` shows an error, you created a new pool with the same name on `/dev/sdb2`. Creating a pool makes it active/imported at the same time.

**Comment by Finkregh** [comment]
Well, i did run ```zpool labelclear -f ``` before that on the device and the partition...
Or is there a better/recommended way to remove ZFS-metadata from a device?

**Comment by Finkregh** [comment]
should i create a new bug for this?
