### ISSUE TITLE
Kernel doesn't start when zfs disk is connected

### ISSUE THREAD

**Issue by gregfr** [zfsonlinux/zfs#2846]
I have this weird behavior: my kernel doesn't start (hangs just after grub) if zfs is installed AND a zfs disk is connected.
What lead me to this weird conclusion is this history:
- I was using ubuntu 12 on a HD and the kernel was booting ok
- I discovered zfs and decided to give it a try ; I installed and rebooted
- I created my first zfs volume on a separated HD, after reboot I got my first kernel hang (100% reproducible)
- I moved my system to a SSD, same behavior
- I recently installed ubuntu 14 on a SSD on the same computer, booting was ok (with zfs disk connected)
- I installed zfs on my new ubuntu 14 and the kernel hang reappeared

Note that I have to physically unplug the zfs disk for the kernel to start, and I have to replug it fast so the disks are available when the zfs kernel module is loaded.

The only reason I can see is that zfs messes up with root volume signature (or something like that) and grub cannot start the kernel properly. But even with that I don't understand why a non-zfs kernel boots ok with the disks connected.

Any idea?

TIA

greg

**Comment by loli10K** [comment]
Closing as stale.
