### ISSUE TITLE
SPLError: 18718:0:(zil.c:1084:zil_lwb_commit()) ASSERTION(zilog_is_dirty(zilog) || spa_freeze_txg(zilog->zl_spa) != UINT64_MAX) failed

### ISSUE THREAD

**Issue by seletskiy** [zfsonlinux/zfs#2860]
Server, running 0.6.3 with debug just died with that kernel message. Unfortunately, there is no other messages or stacktrace.

**Comment by behlendorf** [comment]
Closing as stale.
