### ISSUE TITLE
Zpool import throws spl_PANIC in spl_kmem_alloc

### ISSUE THREAD

**Issue by sempervictus** [zfsonlinux/zfs#2862]
Suffered a crash on a Z2 pool which now results in an inability to import the pool under any recent build of ZFS. Import -F suffers the same fate, and there is no zpool.cache on the system at all (which strikes me as odd). Unfortunately the crash happened during a send by the looks of it, meaning i dont actually have a viable backup on the recipient pool.

Stack traces: http://dpaste.com/026FNS5

Suggestions very welcome... thanks.

**Comment by behlendorf** [comment]
Closing as stale.
