### ISSUE TITLE
MySQL expects AIO and DIO

### ISSUE THREAD

**Issue by behlendorf** [zfsonlinux/zfs#2872]
From #2864: I can't move on to the HEAD, as it reports AIO as supported, but there's no direct IO support yet - this breaks mysql innodb engine, it tries to use both AIO and Direct IO, but only detects if AIO support is present. Effectively this nukes all MySQL instances and as we're OpenVZ based container host, people would kill me.

**Comment by behlendorf** [comment]
@snajpa while I would have liked to address this for 0.6.4 I don't want O_DIRECT support to hold up the next tag any longer.  This is just something we're going to have to explicitly call out in the release notes.

**Comment by snajpa** [comment]
I understand, I've meanwhile tinkered with the code a bit, commented out the three AIO functions mappings in the vfs operations struct, so it's not really a pressing issue at all, we're now using HEAD as I mentioned in my other tickets.

**Comment by rageagainstthebugs** [comment]
O_DIRECT is ready in https://github.com/zfsonlinux/zfs/commit/a584ef26053065f486d46a7335bea222cb03eeea, can this ticket be closed?

**Comment by behlendorf** [comment]
@rageagainstthebugs yes, I believe so.  O_DIRECT will be included in 0.8.
