### ISSUE TITLE
External drive in pool not mounting at boot, running master on Ubuntu 14.10

### ISSUE THREAD

**Issue by satmandu** [zfsonlinux/zfs#2881]
I'm thinking this a timeout issue at boot with detection of the drive.  I've managed to detach and reattach the failed drive just fine.

I've set ZFS_INITRD_PRE_MOUNTROOT_SLEEP='90' in /etc/default/zfs

Is there anything else I should do to force zfs to wait to mount volumes at boot?

```
  pool: tank3
 state: DEGRADED
status: One or more devices could not be used because the label is missing or
	invalid.  Sufficient replicas exist for the pool to continue
	functioning in a degraded state.
action: Replace the device using 'zpool replace'.
   see: http://zfsonlinux.org/msg/ZFS-8000-4J
  scan: resilvered 132G in 0h49m with 0 errors on Sat Nov  8 15:56:29 2014
config:

	NAME                      STATE     READ WRITE CKSUM
	tank3                     DEGRADED     0     0     0
	  mirror-0                DEGRADED     0     0     0
	    sdg2                  ONLINE       0     0     0
	    11071018879035514900  UNAVAIL      0     0     0  was /dev/disk/by-id/ieee1394-0014ee12070affad:000438:0000-part2

errors: No known data errors
```

**Comment by rlaager** [comment]
Ubuntu 14.10 has been EOL for over a year now.

You might try Ubuntu 16.04 and set the rootdelay option (to an integer, in seconds) in GRUB_CMDLINE_LINUX. When that option is set, the initrd script will try to repeatedly import the pool read-only until either it comes ONLINE or the timeout expires. Once either of those events happens, the pool will be imported read-write. So you set the delay to the longest you are willing to wait.
