### ISSUE TITLE
Bogus write ops/second being reported by 'zpool iostat'.

### ISSUE THREAD

**Issue by dswartz** [zfsonlinux/zfs#2888]
2-disk mirror with sata drives, and ssd slog.  I am doing a crystaldiskmark bench from a vsphere VM via NFS virtual disk. Here is what I am seeing:

```
                             capacity     operations    bandwidth
pool                      alloc   free   read  write   read  write
------------------------  -----  -----  -----  -----  -----  -----
tank-copy                  483G  1.34T    143  4.44K  1.12M  69.2M
  mirror                   483G  1.34T    143  4.09K  1.12M  32.0M
    wwn-5000c5002e38e0eb      -      -     69    288   559K  32.0M
    wwn-5000c5002e3aa680      -      -     73    287   590K  32.0M
logs                          -      -      -      -      -      -
  wwn-5000c500301004bf    78.2M   186G      0    358      0  37.2M
------------------------  -----  -----  -----  -----  -----  -----
```

note that the read ops for the two mirror components add up to the total for the vdev.  the write total is preposterously large though.

**Comment by ahrens** [comment]
@behlendorf Since we now use "elevator=none", Is it still the case that the Linux (outside ZFS) block layer will be merging anything?

**Comment by kpande** [comment]
from Linux documentation `noop` does merge IOs but does not sort them.
