### ISSUE TITLE
Add resize command

### ISSUE THREAD

**Issue by rhagu** [zfsonlinux/zfs#2904]
Hi,

I am running ZFS with a ZVOL. I had XFS installed onto this ZVOL and tried to increase the size of the zvol today. While doing this, I accidentally switched two numbers and thereby decreased the zvol size with:

zfs set volsize=7600G poolname/volumename

The filesystem on the ZVOL is now corrupted, which would have been avoided, if I double checked what I wrote.

As this can happen to everyone, I would suggest adding a command to zfsonlinux like this:

zfs resize poolname/volumename [+-]?\d+[KMGTPE]

(thanks to DHE for the suggestion)

zfs resize poolname/volumename +2G

This would make increasing zvol sizes safer.

edit: Added changes regarding krichter722s questions

**Comment by kpande** [comment]
it would still be possible to accidentally use `zfs set volsize` when you meant to use `zfs resize`, I don't think it will solve the problem like `zfs snapshot` or `zpool checkpoint` would. you could also use an external project like [vzvol](https://github.com/RainbowHackerHorse/vzvol) courtesy of @RainbowHackerHorse that may be able to accommodate you by wrapping the existing `zfs set` commands with safe alternates.
