### ISSUE TITLE
BUG: unable to handle kernel NULL pointer dereference at  (null)

### ISSUE THREAD

**Issue by muzyk10** [zfsonlinux/zfs#2914]
After zpool export of one of two pools, kernel splits out:
[czw lis 20 11:07:25 2014] BUG: unable to handle kernel NULL pointer dereference at           (null)
[czw lis 20 11:07:25 2014] IP: [<ffffffff8104dc72>] __wake_up_common+0x26/0x80
[czw lis 20 11:07:25 2014] PGD 2714e7067 PUD 60db20067 PMD 0 
[czw lis 20 11:07:25 2014] Oops: 0000 [#1] SMP 
[czw lis 20 11:07:25 2014] Modules linked in: nf_conntrack_netlink nfnetlink xt_state veth vhost_net macvtap macvlan tun iptable_mangle ERADE xt_conntrack ipt_REJECT xt_tcpudp iptable_filter xt_nat iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntles x_tables dcdbas radeon i2c_algo_bit drm_kms_helper ttm drm i2c_core backlight bnx2 ioatdma joydev pcspkr pata_acpi coretemp i5kreq dca kvm_intel kvm microcode mperf freq_table button processor thermal_sys bridge stp llc ipv6 zfs(PO) zunicode(PO) zavl(PO) zcir(PO) spl(O) rtc_cmos xts gf128mul aes_x86_64 cbc sha256_generic libiscsi scsi_transport_iscsi tg3 ptp pps_core libphy e1000 fufs lockd sunrpc jfs multipath linear raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor
[czw lis 20 11:07:25 2014]  xor async_tx raid6_pq raid1 raid0 dm_snapshot dm_crypt dm_mirror dm_region_hash dm_log dm_mod hidd_samsung hid_pl hid_petalynx hid_gyration sl811_hcd usbhid xhci_hcd ohci_hcd uhci_hcd usb_storage ehci_pci ehci_hcd usbcoribsas lpfc crc_t10dif qla2xxx megaraid_sas megaraid_mbox megaraid_mm megaraid aacraid sx8 DAC960 cciss 3w_9xxx 3w_xxxx mptmptfc scsi_transport_fc scsi_tgt mptspi mptscsih mptbase atp870u dc395x qla1280 imm parport dmx3191d sym53c8xx gdth advansr aic7xxx aic79xx scsi_transport_spi sg pdc_adma sata_inic162x sata_mv ata_piix ahci libahci sata_qstor sata_vsc sata__nv sata_via sata_svw sata_sil24 sata_sil sata_promise pata_sl82c105 pata_cs5530 pata_cs5520 pata_via
[czw lis 20 11:07:25 2014]  pata_jmicron pata_marvell pata_sis pata_netcell pata_sc1200 pata_pdc202xx_old pata_trifle_amd pata_ali pata_it8213 pata_pcmcia pcmcia pcmcia_core pata_ns87415 pata_ns87410 pata_serverworks pata_artop pata_ix2n pata_hpt3x3 pata_hpt37x pata_hpt366 pata_cmd64x pata_efar pata_rz1000 pata_sil680 pata_radisys pata_pdc2027x pata
[czw lis 20 11:07:25 2014] CPU: 3 PID: 29693 Comm: zpool Tainted: P           O 3.10.41-gentoo-r1 #2
[czw lis 20 11:07:25 2014] Hardware name: Dell Inc. PowerEdge 2950/0H603H, BIOS 2.7.0 10/30/2010
[czw lis 20 11:07:25 2014] task: ffff8807192f30c0 ti: ffff8801221aa000 task.ti: ffff8801221aa000
[czw lis 20 11:07:25 2014] RIP: 0010:[<ffffffff8104dc72>]  [<ffffffff8104dc72>] __wake_up_common+0x26/0x80
[czw lis 20 11:07:25 2014] RSP: 0018:ffff8801221abcc8  EFLAGS: 00010086
[czw lis 20 11:07:25 2014] RAX: 0000000000000086 RBX: ffff8806fccd2420 RCX: 0000000000000000
[czw lis 20 11:07:25 2014] RDX: 0000000000000000 RSI: 0000000000000003 RDI: ffff8806fccd2428
[czw lis 20 11:07:25 2014] RBP: ffff8801221abd08 R08: 0000000000000000 R09: ffff8806fccd2ec0
[czw lis 20 11:07:25 2014] R10: ffff8801388cbc80 R11: ffff8807106b9908 R12: 0000000000000003
[czw lis 20 11:07:25 2014] R13: 0000000000000000 R14: 0000000000000003 R15: 0000000000000000
[czw lis 20 11:07:25 2014] FS:  00007fb09c115b80(0000) GS:ffff88073fcc0000(0000) knlGS:0000000000000000
[czw lis 20 11:07:25 2014] CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
[czw lis 20 11:07:25 2014] CR2: 0000000000000000 CR3: 000000012c907000 CR4: 00000000000027e0
[czw lis 20 11:07:25 2014] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[czw lis 20 11:07:25 2014] DR3: 0000000000000000 DR6: 00000000ffff0ff0 DR7: 0000000000000400
[czw lis 20 11:07:25 2014] Stack:
[czw lis 20 11:07:25 2014]  ffff8801221abd08 ffff8806fccd2428 ffff8801221abd08 ffff8806fccd2420
[czw lis 20 11:07:25 2014]  0000000000000086 ffff880718c035a0 0000000000000003 0000000000000000
[czw lis 20 11:07:25 2014]  ffff8801221abd48 ffffffff8104e268 2222222222222222 0000000000000000
[czw lis 20 11:07:25 2014] Call Trace:
[czw lis 20 11:07:25 2014]  [<ffffffff8104e268>] __wake_up+0x34/0x48
[czw lis 20 11:07:25 2014]  [<ffffffff812f5f10>] __blk_drain_queue+0xfe/0x12a
[czw lis 20 11:07:25 2014]  [<ffffffff812f602a>] blk_cleanup_queue+0x7d/0xd5
[czw lis 20 11:07:25 2014]  [<ffffffffa087a098>] zrl_is_locked+0x148f/0x1525 [zfs]
[czw lis 20 11:07:25 2014]  [<ffffffffa087a953>] zvol_remove_minors+0xcf/0xfc [zfs]
[czw lis 20 11:07:25 2014]  [<ffffffffa0854f23>] zfs_secpolicy_smb_acl+0x29e0/0x3dc6 [zfs]
[czw lis 20 11:07:25 2014]  [<ffffffffa0857fba>] pool_status_check+0x38b/0x457 [zfs]
[czw lis 20 11:07:25 2014]  [<ffffffff810dd855>] vfs_ioctl+0x21/0x34
[czw lis 20 11:07:25 2014]  [<ffffffff810de0a7>] do_vfs_ioctl+0x3b1/0x3f4
[czw lis 20 11:07:25 2014]  [<ffffffff81053519>] ? vtime_account_user+0x48/0x5a
[czw lis 20 11:07:25 2014]  [<ffffffff810de12a>] SyS_ioctl+0x40/0x6e
[czw lis 20 11:07:25 2014]  [<ffffffff814a654b>] tracesys+0xdd/0xe2
[czw lis 20 11:07:25 2014] Code: 89 47 08 5d c3 55 48 89 e5 41 57 41 89 d7 41 56 41 55 41 89 cd 41 54 41 89 f4 53 48 7 08 48 89 7d c8 <4c> 8b 0a 48 8d 42 e8 49 8d 59 e8 eb 34 44 8b 30 4c 89 c1 4c 89 
[czw lis 20 11:07:25 2014] RIP  [<ffffffff8104dc72>] __wake_up_common+0x26/0x80
[czw lis 20 11:07:25 2014]  RSP <ffff8801221abcc8>
[czw lis 20 11:07:25 2014] CR2: 0000000000000000
[czw lis 20 11:07:25 2014] ---[ end trace 430526fb5af0bea7 ]---

Sadly it said 'anihilated'. So I guess export didin't finish properly.
Just after this action i did "zpool import" and now it hangs on console almost an hour.
Strace on it's pid also hangs, so i can't add more. I'm going to reboot machine by hand because load is increasing slow but steadily.

specs:
uname:  3.10.41-gentoo-r1 #2 SMP Wed Nov 12 10:23:24 CET 2014 x86_64 Intel(R) Xeon(R) CPU  5450 @ 3.00GHz GenuineIntel GNU/Linux
system:  Gentoo
zfs ver: 6.3 (gentoo ebuild)

**Comment by behlendorf** [comment]
Closing, this issue is believed to have been resolved.
