### ISSUE TITLE
Case insensitive directory lookups not working with Linux 3.17.3 and ZFS 0.6.3-130-g0ec0724

### ISSUE THREAD

**Issue by chungy** [zfsonlinux/zfs#2916]
I use a separate filesystem for Wine with `casesensitivity=insensitive`, and after some Wine programs were no longer operating as they should (random crashes, etc), I've noticed that directories are not being treated correctly with names that are not the exact same case they're stored as. However, regular files seem to be unaffected.

Just a quick example of what I mean:
```
chungy@turanga:.wine$ ls
dosdevices  drive_c  system.reg  userdef.reg  user.reg
chungy@turanga:.wine$ file USER.reg
USER.reg: ASCII text
chungy@turanga:.wine$ ls drive_c/
Bejeweled 3  Program Files  Program Files (x86)  users  windows
chungy@turanga:.wine$ ls Drive_C
ls: cannot access Drive_C: Input/output error
```

I'm running Arch Linux with demizerone's ZFS repo enabled, using his packages.

**Comment by behlendorf** [comment]
Case insensitivity has been fixed.
