### ISSUE TITLE
resilvering to dmcrypt device is unnecessarily slow

### ISSUE THREAD

**Issue by jjYBdx4IL** [zfsonlinux/zfs#2923]
I get only about 30 MB/s write throughput when resilvering to a dmcrypt device. There are no CPU/source/target device bandwidth limitations that can explain that: everything is capable of doing at least 100 MB/s. Source device is not encrypted. Alignments are not the issue, I tested that. Strangely, the pretty constant rate (25-30 MB/s) gets up to pretty much constant 50 MB/s when I have a 100% load on one core.

**Comment by behlendorf** [comment]
Closing as stale.
