### ISSUE TITLE
Bug with CONFIG_SCHED_AUTOGROUP and kernel.sched.autogroup_enabled

### ISSUE THREAD

**Issue by voidzero** [zfsonlinux/zfs#2925]
I'm not really sure how to formulate this as a proper bug report, but here's what's happened to me recently.

I build my kernels manually, with my own config and zfs built into the kernel. Last week I noticed that I had compiled a server kernel with `CONFIG_SCHED_AUTOGROUP=y`. If enabled, this kernel option creates a boolean sysctl `kernel.sched_autogroup_enabled`.

Because this kernel option was not required for this system, I decided to toggle this sysctl to 0, both on the command line, and in sysctl.conf. Shouldn't have done that. The system crashed after I restarted sshd, and after rebooting, there were spurious lockups.

At the time, I didn't realise it was caused by the sysctl. In fact, I thought it could have been the SSDs that I added as mirrored log devices. So my first reaction was to remove those from the pool. I tried, and one of the two was succesfully removed, but the other one wouldn't budge no matter what I tried, even just offlining the device didn't work - "log device has unplayed intent logs."

I was afraid that debugging would take more time than restoring the pool from a duplicate server. So I did that - destroyed the pool, re-created it, sent the data over from that other server.. but still spurious errors and lockups. It was only then that I realised I played with the sysctl. So, I set it back - voila, everything worked again like normal. Urgh.

However, this did make me curious what would happen if I would recompile my kernel with `CONFIG_SCHED_AUTOGROUP=n`. Obviously the sysctl was no longer there, but other than that, the system has been runing smoothly. So apparently, the only time these problems might occur is with `CONFIG_SCHED_AUTOGROUP=y` and `kernel.sched_autogroup_enabled=0`.

Most annoying part of it is that I had to re-create specific things like ssh host keys and so forth.. not a pleasant outcome. So I hope this is enough to track down what causes these problems, and that no one else has to go through a similar situation.

**Comment by behlendorf** [comment]
Closing, because there isn't anything actionable here but I'm glad to have the issue report for future reference.
