### ISSUE TITLE
Serious: zpool will not load without forced import, Ubuntu 14.04 since recent zfs update

### ISSUE THREAD

**Issue by TimJWatts** [zfsonlinux/zfs#2927]
Ubuntu 14.04, running on 64 bit Intel platform (Dell 7440 laptop) with SSD storage.

uname -a
Linux squidward 3.13.0-39-generic #66-Ubuntu SMP Tue Oct 28 13:30:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

A few packages updated between the last reboot on the 20th Nov and today's reboot on 23rd Nov - most notably these:

2014-11-21 08:02:00 status installed zfs-doc:amd64 0.6.3-3~trusty
2014-11-21 08:04:11 status installed zfs-dkms:amd64 0.6.3-3~trusty
2014-11-21 08:04:18 status installed libzfs2:amd64 0.6.3-3~trusty
2014-11-21 08:04:25 status installed zfsutils:amd64 0.6.3-3~trusty

Since that and on the first reboot since apt-get upgrade ran, the system will not mount any ZFS filesystems.

From memory as I cannot reproduce and type at the same time:
OS filesystems are not on ZFS (good)
Log in as root to console:

zpool list

> no pools

zpool import

> blah blah zpool0, something about other system, use -f to force

zpool import -f zpool0

> OK...

zfs mount -a

> Everything is fine.

reboot

> back to square 1.

https://groups.google.com/a/zfsonlinux.org/forum/#!topic/zfs-discuss/0QbmxJXZO5Y

suggests at least one other person is affected to date.

**Comment by Finkregh** [comment]
is it possible that this is connected to #2844 (label on partition as well as on the disk)?
