### ISSUE TITLE
Can't cancel scrub / can't issue zpool commands

### ISSUE THREAD

**Issue by pdemarino** [zfsonlinux/zfs#2929]
After a kernel update to the newest Fedora 20, Zfs wouldn't install (wait_bit issue). I manually applied the edits, and things were just fine.

However, I'm facing a different issue: a zpool scrub is underway (7 x 2Tb RAID-Z 38% full - reported progress is 100.4% - no I/O, no movement over the past 24 hours) and I can't cancel it. zpool scrub -s hangs (uninterruptible sleep), and so do virtually all other "zpool" commands. zfs commands appear to work fine.

Further context: the L2ARC device failed mid-way through the scrub, and is correctly reported UNAVAIL. Rebooting didn't help.

Help would be very welcome :-) , as well as any indication of what information could be useful.

**Comment by gmelikov** [comment]
Close as stale.

If it's actual - feel free to reopen.
