### ISSUE TITLE
VERIFY(c < (1ULL << 17) >> 9) failed, PANIC at zio.c:263:zio_data_buf_alloc() on import

### ISSUE THREAD

**Issue by akorn** [zfsonlinux/zfs#2932]
Hi,

I have a pool that had the "ASSERTION(c < SPA_MAXBLOCKSIZE >> SPA_MINBLOCKSHIFT) failed, SPLError: 5408:0:(zio.c:263:zio_data_buf_alloc()) SPL PANIC" problem like in #2678:

```
kernel: resource.fs.zfs.statechange version=0x0 pool_guid=0xf949f2e99b5a4f92
kernel:  pool_context=0x1 vdev_guid=0x905ba2ae29ed389a vdev_state=0x7 time=[ 
kernel:  0x54744898 0xff08fce ] eid=0x1c
kernel: ASSERTION(c < SPA_MAXBLOCKSIZE >> SPA_MINBLOCKSHIFT) failed
kernel: SPLError: 5408:0:(zio.c:263:zio_data_buf_alloc()) SPL PANIC
kernel: SPL: Showing stack for process 5408
kernel: CPU: 4 PID: 5408 Comm: zpool Tainted: P           O 3.10.16-vs2.3.6.6-superguppy #1
kernel: Hardware name: Supermicro H8SGL/H8SGL, BIOS 3.0        08/31/2012
kernel:  0000000000000000 ffff8807f355b358 ffffffff814eb2db ffff8807f355b370
kernel:  ffffffffa010b40b 0000000000000000 ffff8807f355b390 ffffffffa010c65a
kernel:  000000000000003b ffffffffa02b8bc8 ffff8807f355b510 ffffffffa0115e78
kernel: Call Trace:
kernel:  [<ffffffff814eb2db>] dump_stack+0x19/0x1b
kernel:  [<ffffffffa010b40b>] spl_debug_dumpstack+0x46/0x49 [spl]
kernel:  [<ffffffffa010c65a>] spl_debug_bug+0x88/0xcd [spl]
kernel:  [<ffffffffa0115e78>] spl_PANIC+0x9d/0xc6 [spl]
kernel:  [<ffffffff8102e181>] ? __switch_to+0x13d/0x3b8
kernel:  [<ffffffff8108073e>] ? mmdrop+0x11/0x20
kernel:  [<ffffffff81081a10>] ? finish_task_switch+0x7b/0xab
kernel:  [<ffffffffa0262520>] zio_data_buf_alloc+0x3e/0x53 [zfs]
kernel:  [<ffffffffa02076e6>] spa_load_verify_cb+0x93/0x181 [zfs]
kernel:  [<ffffffffa01d5850>] traverse_visitbp+0x332/0x712 [zfs]
kernel:  [<ffffffffa01d5208>] ? traverse_prefetch_metadata+0x3e/0x9b [zfs]
kernel:  [<ffffffffa01d6311>] traverse_dnode+0x9b/0xaa [zfs]
kernel:  [<ffffffffa01d5ae6>] traverse_visitbp+0x5c8/0x712 [zfs]
kernel:  [<ffffffffa01d59bd>] traverse_visitbp+0x49f/0x712 [zfs]
kernel:  [<ffffffffa01d59bd>] traverse_visitbp+0x49f/0x712 [zfs]
kernel:  [<ffffffffa01d59bd>] traverse_visitbp+0x49f/0x712 [zfs]
kernel:  [<ffffffffa01d59bd>] traverse_visitbp+0x49f/0x712 [zfs]
kernel:  [<ffffffffa01d59bd>] traverse_visitbp+0x49f/0x712 [zfs]
kernel:  [<ffffffffa01d59bd>] traverse_visitbp+0x49f/0x712 [zfs]
kernel:  [<ffffffffa01d62d2>] traverse_dnode+0x5c/0xaa [zfs]
kernel:  [<ffffffffa01d5bb3>] traverse_visitbp+0x695/0x712 [zfs]
kernel:  [<ffffffffa01d5f34>] traverse_impl+0x304/0x3ec [zfs]
kernel:  [<ffffffffa01d604b>] traverse_dataset+0x2f/0x31 [zfs]
kernel:  [<ffffffffa0207653>] ? spa_async_suspend+0x8d/0x8d [zfs]
kernel:  [<ffffffffa01d6152>] traverse_pool+0x105/0x150 [zfs]
kernel:  [<ffffffffa0207653>] ? spa_async_suspend+0x8d/0x8d [zfs]
kernel:  [<ffffffffa020deb4>] spa_load+0x169f/0x1a5e [zfs]
kernel:  [<ffffffffa020d546>] spa_load+0xd31/0x1a5e [zfs]
kernel:  [<ffffffffa020a5ef>] ? spa_activate+0x45e/0x481 [zfs]
kernel:  [<ffffffffa020e2dd>] spa_load_best+0x6a/0x242 [zfs]
kernel:  [<ffffffffa0134dc8>] ? zpool_get_rewind_policy+0x4d/0x141 [zcommon]
kernel:  [<ffffffffa020e5d3>] spa_open_common+0x11e/0x317 [zfs]
kernel:  [<ffffffffa020e820>] spa_get_stats+0x39/0x275 [zfs]
kernel:  [<ffffffffa02406e9>] zfs_ioc_pool_stats+0x22/0x57 [zfs]
kernel:  [<ffffffffa02450d5>] zfsdev_ioctl+0x354/0x40c [zfs]
kernel:  [<ffffffff8113fd6f>] vfs_ioctl+0x18/0x34
kernel:  [<ffffffff81140577>] do_vfs_ioctl+0x362/0x41c
kernel:  [<ffffffff81081a10>] ? finish_task_switch+0x7b/0xab
kernel:  [<ffffffff814ee508>] ? __schedule+0x4b3/0x593
kernel:  [<ffffffff81140683>] SyS_ioctl+0x52/0x7d
kernel:  [<ffffffff81052b66>] ? do_page_fault+0x9/0xb
kernel:  [<ffffffff814efd56>] system_call_fastpath+0x1a/0x1f
```

I rebuilt zfsonlinux (spl as well as zfs) using current git master (so it has the fix from 4a7480a7ac3a350bed802344b852368bf734dc10) and tried with that. Now I get a different panic message on import:

```
[  183.954795] resource.fs.zfs.statechange version=0x0 pool_guid=0xf949f2e99b5a4f92
[  183.961518]  pool_context=0x2 vdev_guid=0x905ba2ae29ed389a vdev_state=0x7 time=[ 
[  183.968563]  0x5474567f 0x1be4365a ] eid=0xf

[  203.365009] VERIFY(c < (1ULL << 17) >> 9) failed
[  203.368489] PANIC at zio.c:263:zio_data_buf_alloc()
[  203.372227] Showing stack for process 5225
[  203.375136] CPU: 3 PID: 5225 Comm: zpool Tainted: P           O 3.10.16-vs2.3.6.6-superguppy #1
[  203.382721] Hardware name: Supermicro H8SGL/H8SGL, BIOS 3.0        08/31/2012
[  203.388714]  0000000000000000 ffff880c07507468 ffffffff814eb2db ffff880c07507478
[  203.395274]  ffffffffa010f603 ffff880c07507610 ffffffffa010f6cb ffff880c07507620
[  203.401865]  ffffffff81089a5d ffff880c00000028 ffff880c07507620 ffff880c075075b8
[  203.408406] Call Trace:
[  203.409665]  [<ffffffff814eb2db>] dump_stack+0x19/0x1b
[  203.413686]  [<ffffffffa010f603>] spl_dumpstack+0x3d/0x3f [spl]
[  203.418483]  [<ffffffffa010f6cb>] spl_panic+0xc6/0xf9 [spl]
[  203.422920]  [<ffffffff81089a5d>] ? load_balance+0xc2/0x61a
[  203.427311]  [<ffffffff81035879>] ? native_sched_clock+0x39/0x3b
[  203.432167]  [<ffffffff8102e181>] ? __switch_to+0x13d/0x3b8
[  203.436558]  [<ffffffff8108073e>] ? mmdrop+0x11/0x20
[  203.440361]  [<ffffffff81081a10>] ? finish_task_switch+0x7b/0xab
[  203.445380]  [<ffffffffa03a571b>] zio_data_buf_alloc+0x3e/0x53 [zfs]
[  203.450699]  [<ffffffffa034ab59>] spa_load_verify_cb+0x93/0x189 [zfs]
[  203.456085]  [<ffffffffa0319917>] traverse_visitbp+0x336/0x722 [zfs]
[  203.461397]  [<ffffffffa02fc23c>] ? arc_read+0xbf4/0xc08 [zfs]
[  203.466187]  [<ffffffffa03a7f33>] ? zio_nowait+0x231/0x27c [zfs]
[  203.471118]  [<ffffffffa031a3f5>] traverse_dnode+0x9b/0xaa [zfs]
[  203.476079]  [<ffffffffa0319bb3>] traverse_visitbp+0x5d2/0x722 [zfs]
[  203.481390]  [<ffffffffa0319a87>] traverse_visitbp+0x4a6/0x722 [zfs]
[  203.486716]  [<ffffffffa0319a87>] traverse_visitbp+0x4a6/0x722 [zfs]
[  203.491981]  [<ffffffffa0319a87>] traverse_visitbp+0x4a6/0x722 [zfs]
[  203.497268]  [<ffffffffa0319a87>] traverse_visitbp+0x4a6/0x722 [zfs]
[  203.502595]  [<ffffffffa0319a87>] traverse_visitbp+0x4a6/0x722 [zfs]
[  203.507920]  [<ffffffffa0319a87>] traverse_visitbp+0x4a6/0x722 [zfs]
[  203.513234]  [<ffffffffa031a3b6>] traverse_dnode+0x5c/0xaa [zfs]
[  203.518212]  [<ffffffffa0319c84>] traverse_visitbp+0x6a3/0x722 [zfs]
[  203.523542]  [<ffffffffa031a00a>] traverse_impl+0x307/0x3f9 [zfs]
[  203.528598]  [<ffffffffa031a12b>] traverse_dataset+0x2f/0x31 [zfs]
[  203.533767]  [<ffffffffa034aac6>] ? spa_async_suspend+0x94/0x94 [zfs]
[  203.539150]  [<ffffffffa031a232>] traverse_pool+0x105/0x150 [zfs]
[  203.544315]  [<ffffffffa034aac6>] ? spa_async_suspend+0x94/0x94 [zfs]
[  203.549794]  [<ffffffffa0351381>] spa_load+0x16b5/0x1a6d [zfs]
[  203.554622]  [<ffffffffa03517a3>] spa_load_best+0x6a/0x242 [zfs]
[  203.559480]  [<ffffffffa0146e12>] ? zpool_get_rewind_policy+0x97/0x141 [zcommon]
[  203.565818]  [<ffffffffa0352dca>] spa_import+0x18b/0x5fb [zfs]
[  203.570607]  [<ffffffffa03835fd>] zfs_ioc_pool_import+0xac/0xf1 [zfs]
[  203.576025]  [<ffffffffa0388231>] zfsdev_ioctl+0x354/0x40c [zfs]
[  203.580850]  [<ffffffff81121036>] ? __cache_free.isra.48+0x1c7/0x1d5
[  203.586026]  [<ffffffff8113fd6f>] vfs_ioctl+0x18/0x34
[  203.589935]  [<ffffffff81140577>] do_vfs_ioctl+0x362/0x41c
[  203.594264]  [<ffffffff8113b4b2>] ? final_putname+0x2f/0x32
[  203.598647]  [<ffffffff8113b617>] ? putname+0x22/0x24
[  203.602514]  [<ffffffff81140683>] SyS_ioctl+0x52/0x7d
[  203.606442]  [<ffffffff81052b66>] ? do_page_fault+0x9/0xb
[  203.610652]  [<ffffffff814efd56>] system_call_fastpath+0x1a/0x1f
```

Would it make sense to try importing a previous txg using zpool import -T?

Also, fwiw, this box has ECC memory.

**Comment by cointer** [comment]
Quick question regarding this bug. I have had this problem in the past (my post is referenced in the first post in this thread) but have subsequently destroyed any related pools. I am, however, still using xattr=sa and acltype=posixacl.

I do need posixacl set, but is this error mitigated by setting xattr to default instead of sa? Or is this problem still possible when acltype=posixacl is set without xattr=sa?

Just looking to stop this error from happening again altogether until a fix is out.

**Comment by cointer** [comment]
@dweeezil Quick question regarding this bug. I have had this problem in the past (my post is referenced in the first post in this thread) but have subsequently destroyed any related pools. I am, however, still using xattr=sa and acltype=posixacl.

I do need posixacl set, but is this error mitigated by setting xattr to default instead of sa? Or is this problem still possible when acltype=posixacl is set without xattr=sa?

Just looking to stop this error from happening again altogether until a fix is out.

**Comment by dweeezil** [comment]
@cointer AFAIK, the last of the SA problems should be fixed by 4254acb which is not in any current release tag.  I suppose some packages might have included it in their point releases but I'd not know about that.

**Comment by cointer** [comment]
@dweeezil Thanks, good to know. I'm not in a position where I will be able to update the ZFS build for a while though. So, in the meantime, will rsyncing to a dataset with acltype=posixacl and xattr=dir be sufficient to avoid this potential problem?

**Comment by dweeezil** [comment]
@cointer Yes, but the correct option is ```xattr=on``` .

**Comment by alexanderhaensch** [comment]
Dont know if this is related, but i have a similar problem with 0.6.5 during a scrub.
The scrub is deadlocked and zfs commands do not work any more after this:

[64345.893387] VERIFY3(mintxg == dsl_dataset_phys(ds1)->ds_prev_snap_txg) failed (6614665 == 6614099)
[64345.893391] PANIC at dsl_scan.c:983:dsl_scan_ds_clone_swapped()
[64345.893392] Showing stack for process 6430
[64345.893395] CPU: 6 PID: 6430 Comm: txg_sync Tainted: P           O 3.14.51-hardened #1
[64345.893396] Hardware name: Supermicro X9DR3-F/X9DR3-F, BIOS 3.0b 06/30/2014
[64345.893398]  00000000000003d7 ffff882024bdb918 ffffffff815f25a5 ffffffffa0ad68df
[64345.893401]  ffff882024bdb928 ffffffffa07790ef ffff882024bdbaa8 ffffffffa07791a7
[64345.893402]  ffff88201e672000 ffff882000000030 ffff882024bdbab8 ffff882024bdba58
[64345.893404] Call Trace:
[64345.893427]  [<ffffffff815f25a5>] dump_stack+0x45/0x56
[64345.893473]  [<ffffffffa0ad68df>] ? _fini+0x2ce36/0x7b2a3 [zfs]
[64345.893480]  [<ffffffffa07790ef>] spl_dumpstack+0x3f/0x50 [spl]
[64345.893486]  [<ffffffffa07791a7>] spl_panic+0xa7/0xe0 [spl]
[64345.893495]  [<ffffffffa09c1949>] ? dmu_buf_rele+0x9/0x10 [zfs]
[64345.893510]  [<ffffffffa0a561bd>] ? zap_unlockdir+0x5d/0x110 [zfs]
[64345.893524]  [<ffffffffa0a5639e>] ? zap_lookup_norm+0xbe/0x1b0 [zfs]
[64345.893537]  [<ffffffffa0a564be>] ? zap_lookup+0x2e/0x30 [zfs]
[64345.893551]  [<ffffffffa0a50fad>] ? zap_lookup_int_key+0x4d/0x60 [zfs]
[64345.893566]  [<ffffffffa0a09930>] dsl_scan_ds_clone_swapped+0xc0/0x470 [zfs]
[64345.893578]  [<ffffffffa09f0467>] dsl_dataset_clone_swap_sync_impl+0x757/0x830 [zfs]
[64345.893590]  [<ffffffffa09dc10e>] dmu_recv_end_sync+0xbe/0x400 [zfs]
[64345.893605]  [<ffffffffa0a0b59a>] dsl_sync_task_sync+0x12a/0x130 [zfs]
[64345.893618]  [<ffffffffa0a02b33>] dsl_pool_sync+0x493/0x5e0 [zfs]
[64345.893634]  [<ffffffffa0a24785>] spa_sync+0x365/0xde0 [zfs]
[64345.893649]  [<ffffffffa0a3946a>] txg_sync_thread+0x3ba/0x690 [zfs]
[64345.893665]  [<ffffffffa0a390b0>] ? txg_thread_wait+0xd0/0xd0 [zfs]
[64345.893670]  [<ffffffffa07751d5>] thread_generic_wrapper+0x75/0xb0 [spl]
[64345.893675]  [<ffffffffa0775160>] ? __thread_exit+0x20/0x20 [spl]
[64345.893681]  [<ffffffff81062614>] kthread+0xc4/0xe0
[64345.893683]  [<ffffffff81062550>] ? kthread_create_on_node+0x160/0x160
[64345.893687]  [<ffffffff815f88c9>] ret_from_fork+0x49/0x80
[64345.893689]  [<ffffffff81062550>] ? kthread_create_on_node+0x160/0x160

**Comment by behlendorf** [comment]
Closing.  This should be resolved in the current master branch.

@alexanderhaensch your issue looks a little different, can you open a new issue for it.
