### ISSUE TITLE
Please adjust error message ZFS-8000-5E

### ISSUE THREAD

**Issue by mailinglists35** [zfsonlinux/zfs#2933]
Sometimes (I could not identify exactly what triggers but I suspect maybe kernel device name change) my two-way mirrored pool is listed as UNAVAIL with it's devices listed as FAULTED.

user@host:~$ sudo zpool status -x  
  pool: mypool
 state: UNAVAIL
status: One or more devices could not be used because the label is missing 
        or invalid.  There are insufficient replicas for the pool to continue
        functioning.
action: Destroy and re-create the pool from
        a backup source.
   see: http://zfsonlinux.org/msg/ZFS-8000-5E
  scan: none requested
config:

```
    NAME        STATE     READ WRITE CKSUM
    mypool    UNAVAIL      0     0     0  insufficient replicas
      mirror-0  UNAVAIL      0     0     0  insufficient replicas
        sdc     FAULTED      0     0     0  corrupted data
        sdd     FAULTED      0     0     0  corrupted data
```

This is incorrect as the drives really are sdc and sdd (I have even created the pool using /dev/disk/by-id/\* naming, using wholedisk/gpt, and zdb -l confirms it!), and a simple zpool export poolname followed by zpool import -a correctly activates the pool.

The message displayed http://zfsonlinux.org/msg/ZFS-8000-5E/ is creepy and scares the hell out of new users.

Please include this small tip in the message displayed by zpool and in the url
Using zfs daily version 0.6.3 on ubuntu 14.04 lts

**Comment by mailinglists35** [comment]
not yet :(

**Comment by behlendorf** [comment]
Closing as stale.
