### ISSUE TITLE
Importing ZFS RAIDZ after reboot fails

### ISSUE THREAD

**Issue by cyberius0** [zfsonlinux/zfs#2935]
Hello,

every time after I reboot I can't import my ZFS RAIDZ, I get an error: "Importing XXX failed, XXX is already imported"

I have to export it first and re-import directly after that, then everything goes fine.

My RAIDZ-pool is made out of several /dev/mapper/dm-crypt devices that are not available in boot process (after booting is complete I run a script that first decrypts all physical HDDs and creates those mapped crypt-devices)

OS: Debian Jessy
Linux raid 3.16.0-4-amd64 #1 SMP Debian 3.16.7-2 (2014-11-06) x86_64 GNU/Linux

I think a workaround would be to put a command like "zfs export xxx" into a script that is being run every time the computer reboots. But maybe there's a better way?

**Comment by gmelikov** [comment]
Close as stale.

If it's actual - feel free to reopen.
