### ISSUE TITLE
Add "zdisk" command for disk-specific operations

### ISSUE THREAD

**Issue by kohlschuetter** [zfsonlinux/zfs#294]
Currently, zfs lacks a command-line tool that deals with disk-specific features, such as
- burn-in disk before adding it to a pool
- automatically determine real sector size (`ashift=12` etc.)
- display serial-no. / identify (= blinking lights etc.)
- manually/automatically spin-up/down drives
- run SMART tests

etc.

While there are many linux utilities around that perform the above steps, it would be great to have at least a zfs-specific interface to them. Thus, `zdisk` may well be a shell script and internally just call programs like `smartctl`, `hdparm`, etc. but at the same time is aware of any zfs-specifics.

The idea behind having a common tool is to lower the learning curve for new users and streamline the process of setting up/maintaining zfs pools.

It should be regarded good practice to first use `zdisk` before adding any device to a zpool. `zdisk` should notify the user if the device requires a particular zpool/zfs setting (e.g., `ashift=12`), for example.

`zdisk` could also help improving a "grey list" of known devices with strange behavior (e.g., reporting sector sizes of 512b whereas they use 4k internally). This greylist could be used to improve `zpool`'s default behavior (e.g., automatically use `ashift=12` instead of  `ashift=9` in these cases) -- see issue #289 for this particular aspect.

**Comment by kpande** [comment]
@kylef what became of this?

**Comment by kylef** [comment]
@kpande that was 4 years ago, I have no idea. I haven't used ZFS nor Linux since.

Please feel free to extend my commit: https://github.com/zfsonlinux/zfs/commit/79bf67acc891bb6868e3e1c7eb0624d107840ad0 and propose a PR if your interested on working on this feature.

**Comment by gmelikov** [comment]
@behlendorf looks like false closed?
