### ISSUE TITLE
"zpool: symbol lookup error: zpool: undefined symbol: highbit64" in /sbin/zpool

### ISSUE THREAD

**Issue by Amitie10g** [zfsonlinux/zfs#2942]
```
CPUs:				1 (4 cores)
Memory:				4GB
VM/Hypervisor:		No
ECC mem:			No
Distribution:		Debian GNU/Linux (Jessie/Sid)
Kernel version:		Linux davod.org 3.18.0-rc5-custom #1 SMP PREEMPT Sun Nov 23 15:07:51 CLST 2014 x86_64 GNU/Linux
SPL/ZFS source:		Packages got from ZFS for debian repositoriy
SPL/ZFS version:	# dmesg | grep -E 'SPL:|ZFS:'
[   12.783884] SPL: Loaded module v0.6.3-13~917fef~jessie
[   12.809507] ZFS: Loaded module v0.6.3-22~7b2d78~wheezy, ZFS pool version 5000, ZFS filesystem version 5
[   13.283655] SPL: using hostid 0x37333636
System services:	Workstation with Samba, Sane and Apache
```

I just updated my ZFS related packages from `0.6.3-1~jessie` and SPL `0.6.3-7~jessie` to the versions above. But, when running /sbin/zpool (in the zfsutils package) I get the following error:

`zpool: symbol lookup error: zpool: undefined symbol: highbit64`

And therefore, **the system is unable to import the pool** at boot time, and I get Kernel panic.

I already found some post in Google Groups, and the problem appears to be in the SPL. The older version have defined `highbit` instead of `highbit64`

I've used ZFS packages for Wheezy instead of Jessie because seems to be more up to date.

I resolved the problem by **copying the old zpool binary to /sbin/zpool** and then running ´update-initramfs´, and then works without problems for now (regardlress the version difference).

**Comment by Amitie10g** [comment]
Already resolved by updating.

**Comment by Rmrfy** [comment]
> ```
> CPUs:               1 (4 cores)
> Memory:             4GB
> VM/Hypervisor:      No
> ECC mem:            No
> Distribution:       Debian GNU/Linux (Jessie/Sid)
> Kernel version:     Linux davod.org 3.18.0-rc5-custom #1 SMP PREEMPT Sun Nov 23 15:07:51 CLST 2014 x86_64 GNU/Linux
> SPL/ZFS source:     Packages got from ZFS for debian repositoriy
> SPL/ZFS version:    # dmesg | grep -E 'SPL:|ZFS:'
> [   12.783884] SPL: Loaded module v0.6.3-13~917fef~jessie
> [   12.809507] ZFS: Loaded module v0.6.3-22~7b2d78~wheezy, ZFS pool version 5000, ZFS filesystem version 5
> [   13.283655] SPL: using hostid 0x37333636
> System services:    Workstation with Samba, Sane and Apache
> ```
> I just updated my ZFS related packages from `0.6.3-1~jessie` and SPL `0.6.3-7~jessie` to the versions above. But, when running /sbin/zpool (in the zfsutils package) I get the following error:
> 
> `zpool: symbol lookup error: zpool: undefined symbol: highbit64`
> 
> And therefore, **the system is unable to import the pool** at boot time, and I get Kernel panic.
> 
> I already found some post in Google Groups, and the problem appears to be in the SPL. The older version have defined `highbit` instead of `highbit64`
> 
> I've used ZFS packages for Wheezy instead of Jessie because seems to be more up to date.
> 
> I resolved the problem by **copying the old zpool binary to /sbin/zpool** and then running ´update-initramfs´, and then works without problems for now (regardlress the version difference).

Hi ：
  I want to install zfs-0.6.4 version under 7.4 system.But when the pool is created after the compilation and installation is completed, an error is reported.such as

`zpool: symbol lookup error: zpool: undefined symbol: zfs_dev_is_whole_disk`
