### ISSUE TITLE
NULL pointer dereference on importing pool using stale zpool.cache 0.6.3-22~7b2d78~wheezy

### ISSUE THREAD

**Issue by tom-joy** [zfsonlinux/zfs#2943]
Last week I changed some devices in a pool that's loaded in initramfs, and booted without updating the initramfs to contain a current zpool.cache file. On trying to import the pool with the old zpool.cache, the zfs module raised a kernel oops.

I admit it's not the most correct thing for me to have done in the first place, but nevertheless zfs shouldn't crash my computer.

I've attached some real, actual screenshots. I'll work on a more thorough reproduction but it may take some days before I'm in a position to do that.

![](http://i.imgur.com/JKBDsN8.jpg)

![](http://i.imgur.com/Wil4wM9.jpg)

![](http://i.imgur.com/YNFSEN9.jpg)

**Comment by gmelikov** [comment]
Closing as stale.
