### ISSUE TITLE
Ubuntu 14.04 - RAIDZ Pool Disappears on Reboot

### ISSUE THREAD

**Issue by asthepenguinflies** [zfsonlinux/zfs#2949]
So, I've been struggling with this issue ever since I wiped and did a clean install of 14.04 on my server. A bit of background info: I have five 3tb disks in my "zfs-media" pool, all added about a year ago by id, and connected to an IBM ServeRAID M1015 flashed to the LSI 9211-8i IT mode firmware. 

I first noticed the "disappearing pool" issue when I wiped my server and did a clean install of 14.04. In the past, I've used fstab to get around the fact automount wasn't working for me, but given that it was a fresh install I went for the default settings just to see.

So, I manually imported the pool, changed the mountpoint to /mnt/zfs-media from legacy (my normal mountpoint through fstab), and everything was great—all my files were present etc. I then proceeded to reboot my computer to test automount. Upon reboot, it didn't mount. In addition, "`sudo zpool status`" showed no pools available. I manually imported it again, and there it was. Just fine, everything great.

So, I switched back to legacy, and set up my fstab by adding the line below to my fstab as I had in the past:
`zfs-media	/mnt/zfs-media	zfs	defaults	0	2`

Unfortunately, it didn't work. Upon reboot, all I got was a message saying there was an error mounting zfs-media giving me the option to manually recover or skip. I skipped and found the same issue as last time (as was to be expected given the error). Once again, I manually imported the pool, ran "`mount -a`" and everything was back where it should be.

Following this I tried out the addition of "`zfs mount -a`" to my rc.local (in combination with the default mountpoint behavior), I updated my card's firmware, I tried adding a wait command to my mountall.conf, I tried upgrading to 14.10 and updated all the zfs packages, and I even did another wipe of the server back to 14.04 just to make sure something I had already done wasn't conflicting. Nothing.

I am currently still stuck manually importing the pool after boot, and it's getting super annoying because I have some applications that start with the machine and store settings on that pool, and they refuse to start without it present—which means I have to manually start them as well.

**Comment by asthepenguinflies** [comment]
I am still at the same spot with this. Are there additional logs that are necessary?

**Comment by dajhorn** [comment]
@asthepenguinflies, no, we need to get a debugging prompt and step through the mount steps.

**Comment by asthepenguinflies** [comment]
Any suggestions on how to get there?

From what I'm experiencing there's no way to get to the manual recovery prompt. If I hit "M" on boot the entire thing becomes unresponsive outside of being able to switch between the GUI and non-GUI boot screens (using `esc` or left and right arrow keys). Furthermore, hitting `ctrl + alt + t` simply switches to the non-GUI boot list, with a flashing underscore at the bottom left of the screen, and renders *everything* (including `esc` and the arrow keys) non-responsive. At that point, I have to physically reboot.

When I do reboot from that screen, if I choose advanced options, go into recovery mode, and drop to a prompt, I get the same results as I posted above. The disks are there, the pool is imported etc. For a giggle, the first thing I did at the recovery prompt this time around is I ran the `zfs list` command, and it returned that `zfs-media` was there and set to legacy. Running `mount -a` didn't mount it, but I believe that's an issue with being in recovery mode, is it not?

Regardless, it seems to me that whatever is going on is so completely screwing up boot that going into a debug prompt is not possible—it just hangs. I have had zero luck finding a solution to the "hang on 'M'" issue, so my guess is that it's pretty unique, and in this case likely caused by the zfs issue itself.

**Comment by dajhorn** [comment]
> Any suggestions on how to get there?

The `M` might not work if the system keyboard driver isn't ready at the rescue prompt.  While unlikely, this can happen if:

* The CSM and/or HID thingy for USB devices is disabled in the system BIOS, like when a UEFI computer is tuned for fast boot.  Look for a toggle that reads like *USB Compatibility Mode: Disabled || Keyboard Only || Enabled* and set it to anything except disabled.
* The motherboard has a PS/2 port and the firmware is wonky.  Try connecting a PS/2 keyboard if you have one.

> From what I'm experiencing there's no way to get to the manual recovery prompt. If I hit "M" on boot the entire thing becomes unresponsive outside of being able to switch between the GUI and non-GUI boot screens

This could also be a Plymouth problem.

Remove `splash` and `quiet` from the `/etc/default/grub` configuration, run `update-grub`, and try again.  Afterwards, the raw `dmesg` should appear as scrolling white-on-black text and eventually stop at the `M` prompt.

  Doing this prevents a video mode change before the `M` prompt that can mangle the console before everything is reset by the regular X11 desktop.

And for completeness, although you probably haven't done this, revert any `grub.cfg` or `CONSOLE` customizations that poke extended VESA modes.

**Comment by asthepenguinflies** [comment]
1. `sudo nano /etc/default/grub`
2. Removed `quiet splash` from the `GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"` line.
3. `sudo update-grub`
4. rebooted into UEFI Setup Utility
5. Saw Intel Rapid Start was enabled, but not set up. Disabled it just in case.
6. All USB options were already enabled, including legacy support.
7. Fast Boot was already disabled.
8. Saved and exited UEFI Setup Utility.
9. `DMESG` scrolled by.
10. Got to login prompt with no errors. `df -h` shows zfs-media mounted.
11. Rebooted to double check what I was seeing.
12. Once again got to login prompt with no errors. `df -h` shows zfs-media mounted.
13. Tested auto-mounting by turning off legacy `sudo zfs set mountpoint=/mnt/zfs-media zfs-media` and removed fstab line for `zfs-media`.
14. Rebooted.
15. Got to login prompt with no errors. `df -h shows zfs-media mounted.

Most recent dmesg is [here](https://gist.github.com/asthepenguinflies/0ed02e071d864d9dc3b3).

There appears to be some sort of black magic afoot. How can removing `quiet splash` possibly fix the issue? The only thing that changed other than that was the Intel Rapid Start setting, which was effectively disabled anyway since it wasn't set up with a partition.

**Comment by dasjoe** [comment]
Removing "quiet splash" makes the boot process somewhat slower, so it may
be that your disks get initialited and their device nodes appear before the
ZFS modules are loaded. I've seen similar behavior on some of my boxes, but
never got around to analyze it further, as I'm always removing those
parameters.

-- 
Regards,
Hajo Möller

**Comment by dajhorn** [comment]
> There appears to be some sort of black magic afoot. How can removing quiet splash possibly fix the issue?

An i915 video device is detected, but it glitches during initialization and could be causing some of the `SystemIO conflicts with Region` warnings.  It follows that Plymouth was somehow tripping over that video device.

I've seen this kind of problem resolved by firmware updates of the video card and/or motherboard.  Regardless, Plymouth is a general nuisance and disabling it is a good solution on affected computers.

Given the time stamps in the dmesg, this probably isn't a race condition that is kludged by having the system stall on slow early console output.

**Comment by rlaager** [comment]
You might try Ubuntu 16.04 and set the rootdelay option. When that option is set, the initrd script will try to repeatedly import the pool read-only until either it comes ONLINE or the timeout expires. Once either of those events happens, the pool will be imported read-write. So you set the delay to the *longest* you are willing to wait.
