### ISSUE TITLE
Ubuntu 14.04 on native ZFS root with MD RAID1 and UEFI

### ISSUE THREAD

**Issue by tommyhp2** [zfsonlinux/zfs#2956]
Hi folks,

I tried to install Ubuntu 14.04 on native ZFS root as described here:

https://github.com/zfsonlinux/pkg-zfs/wiki/HOWTO-install-Ubuntu-to-a-Native-ZFS-Root-Filesystem

However, my install is a bit more complicated.  I have 7 HDDs and are divided into 4 partitions each as follow:

part-1 - vfat (fat32) for EFI to be mounted as /boot/efi
part-2 - linux raid for MD RAID1 to be mounted as /boot
part-3 - OS install and swap volume
part-4 - data (zfs pool to be created)

I've modified the above HOWTO to install based on my desired configuration but it won't boot using ZFS as root.  To verify my steps, I've installed into the standard /dev/sd* partition instead of ZFS filesystem for root which works fine.  Further troubleshooting seems like it's trying to import a pool named 'rpool'.  So I had to export the pool 'sys' and reimported as 'zpool import sys rpool' for it to boot OK now.  Is it because I have zfs_force=1 in the kernel parameter? 

**************************************************************************************
root@host-t:~# df -h
Filesystem              Size  Used Avail Use% Mounted on
rpool/root/ubuntu        20G  1.5G   18G   8% /
udev                     16G   12K   16G   1% /dev
tmpfs                   3.2G  704K  3.2G   1% /run
none                    4.0K     0  4.0K   0% /sys/fs/cgroup
none                    5.0M     0  5.0M   0% /run/lock
none                     16G     0   16G   0% /run/shm
none                    100M     0  100M   0% /run/user
/dev/md0                488M  198M  261M  44% /boot
/dev/sda1               100M  9.7M   91M  10% /boot/efi
rpool/root/ubuntu/home   18G  256K   18G   1% /home
rpool/root/ubuntu/opt    18G  128K   18G   1% /opt
rpool/root/ubuntu/var    19G  453M   18G   3% /var
**************************************************************************************
root@host-t:~# zpool status
  pool: rpool
 state: ONLINE
  scan: none requested
config:

        NAME                                        STATE     READ WRITE CKSUM
        rpool                                       ONLINE       0     0     0
          raidz2-0                                  ONLINE       0     0     0
            sdc3                                    ONLINE       0     0     0
            ata-ST3000DM001-xxx_xxx-part3   ONLINE       0     0     0
            ata-ST3000DM001-xxx_xxx-part3   ONLINE       0     0     0
            ata-ST3000DM001-xxx_xxx-part3   ONLINE       0     0     0
            ata-TOSHIBA_DT01ACA300_xxx-part3  ONLINE       0     0     0

errors: No known data errors

  pool: sys
 state: UNAVAIL
status: One or more devices could not be used because the label is missing
        or invalid.  There are insufficient replicas for the pool to continue
        functioning.
action: Destroy and re-create the pool from
        a backup source.
   see: http://zfsonlinux.org/msg/ZFS-8000-5E
  scan: none requested
config:

        NAME        STATE     READ WRITE CKSUM
        sys         UNAVAIL      0     0     0  insufficient replicas
          raidz2-0  UNAVAIL      0     0     0  insufficient replicas
            sdc3    ONLINE       0     0     0
            sdf3    FAULTED      0     0     0  corrupted data
            sdd3    FAULTED      0     0     0  corrupted data
            sdg3    FAULTED      0     0     0  corrupted data
            sde3    FAULTED      0     0     0  corrupted data
**************************************************************************************
root@host-t:~# cat /proc/mdstat
Personalities : [linear] [multipath] [raid0] [raid1] [raid6] [raid5] [raid4] [raid10]
md0 : active raid1 sdd2[1] sde2[3] sdf2[2] sdg2[6] sdc2[0] sda2[4] sdb2[5]
      523968 blocks super 1.2 [7/7] [UUUUUUU]

unused devices: <none>
**************************************************************************************

Also, I've to do this ugly hack to get the initramfs created without throwing errors:

for F in `ls -1 /dev/disk/by-id/ata-*`; do ln -svf $F /dev; done;

**Comment by rlaager** [comment]
This stuff is better in newer versions of Ubuntu.
