### ISSUE TITLE
zpool(8) man page has incorrect indentation from `zpool upgrade` onwards

### ISSUE THREAD

**Issue by mkjorling** [zfsonlinux/zfs#2962]
It appears that the zpool man page source does not properly reset indentation after the block for `zpool status`, such that the blocks for `zpool upgrade` are indented to the same level as the parameters to `zpool status`. This makes them appear as potentially related, which is not the case and could be mildly confusing.

The indendation is reset at the `EXAMPLES` heading.

ZoL 0.6.3, man page as installed by 0.6.3-1~wheezy.

**Comment by rlaager** [comment]
This was (supposedly, I didn't check) fixed in #4184.
