### ISSUE TITLE
kernel lockup on zfs destroy snaphot with 3.16.5-gentoo

### ISSUE THREAD

**Issue by bencord0** [zfsonlinux/zfs#2967]
Stacktrace from "journalctl -fl" before I lost my ssh connections.
This appears to be a 100% reproducible lockup when I run 'zfs destroy "$snapshot"'.

    # zfs list -t snapshot | wc -l
    269

Stacktrace:
Dec 17 14:51:54 aniseed kernel: INFO: task zfs:1337 blocked for more than 30 seconds.
Dec 17 14:51:54 aniseed kernel:       Tainted: P        W  O  3.16.5-gentoo #2
Dec 17 14:51:54 aniseed kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Dec 17 14:51:54 aniseed kernel: zfs             D 0000000000000003 13736  1337   1328 0x00000080
Dec 17 14:51:54 aniseed kernel:  ffff8800be707c78 0000000000000002 ffff8800be707fd8 ffff88041643f5d0
Dec 17 14:51:54 aniseed kernel:  0000000000012d40 ffff88041b5c7390 ffff8804104b9aa8 ffff8804104b9a00
Dec 17 14:51:54 aniseed kernel:  ffff8804104b9ab0 ffff8804104b9ae4 0000000000000000 ffff8800be707c88
Dec 17 14:51:54 aniseed kernel: Call Trace:
Dec 17 14:51:54 aniseed kernel:  [<ffffffffbac2f5e8>] schedule+0x69/0x6b
Dec 17 14:51:54 aniseed kernel:  [<ffffffffc0190a7a>] __cv_init+0xf7/0x14c [spl]
Dec 17 14:51:54 aniseed kernel:  [<ffffffffba0a168b>] ? finish_wait+0x60/0x60
Dec 17 14:51:54 aniseed kernel:  [<ffffffffc0190adf>] __cv_wait+0x10/0x12 [spl]
Dec 17 14:51:54 aniseed kernel:  [<ffffffffc0260e2e>] txg_wait_synced+0xdf/0xf3 [zfs]
Dec 17 14:51:54 aniseed kernel:  [<ffffffffc02a4ede>] ? dsl_destroy_snapshot_check_impl+0x6f/0x15e [zfs]
Dec 17 14:51:54 aniseed kernel:  [<ffffffffc0245f4e>] dsl_sync_task+0x1ca/0x221 [zfs]
Dec 17 14:51:54 aniseed kernel:  [<ffffffffc02a444b>] ? dsl_destroy_snapshot_sync_impl+0x898/0x96c [zfs]
Dec 17 14:51:54 aniseed kernel:  [<ffffffffc02a4ede>] ? dsl_destroy_snapshot_check_impl+0x6f/0x15e [zfs]
Dec 17 14:51:54 aniseed kernel:  [<ffffffffc02a444b>] ? dsl_destroy_snapshot_sync_impl+0x898/0x96c [zfs]
Dec 17 14:51:54 aniseed kernel:  [<ffffffffc02a5080>] dsl_destroy_snapshots_nvl+0xb3/0xd1 [zfs]
Dec 17 14:51:54 aniseed kernel:  [<ffffffffc0281201>] zfs_unmount_snap+0x1f7/0x1ff [zfs]
Dec 17 14:51:54 aniseed kernel:  [<ffffffffc0281574>] pool_status_check+0x2b2/0x450 [zfs]
Dec 17 14:51:54 aniseed kernel:  [<ffffffffba138c15>] do_vfs_ioctl+0x351/0x415
Dec 17 14:51:54 aniseed kernel:  [<ffffffffba0b3a45>] ? current_kernel_time+0x9/0x2d
Dec 17 14:51:54 aniseed kernel:  [<ffffffffba0d6367>] ? __audit_syscall_entry+0xa1/0xc3
Dec 17 14:51:54 aniseed kernel:  [<ffffffffba138d11>] SyS_ioctl+0x38/0x5f

Versions:
sys-kernel/gentoo-sources-3.16.5 (current stable kernel)
sys-fs/zfs{,-kmod}-9999 (latest live ebuild and sources, as of Dec 17 14:27 UTC)

Is there a better way of getting version numbers from zfs live ebuilds other than timestamp?

---
I'm not sure if it matters, but I'm using sys-kernel/dracut-040-r2 (latest unstable)
Built with

    cd /usr/src/linux
    make modules
    dracut --no-compress /root/initramfs.cpio "$(make kernelversion)"
    make bzImage

bzImage is then PXE booted directly into a zfs-on-root + systemd. ZFS (2x2 mirrors) spans all disks without requiring any other bootloaders on this system.

    # cat /proc/cmdline 
    console=ttyS0,115200 console=tty1 root=ZFS=aniseed/gentoo/root rw init=/usr/lib/systemd/systemd BOOT_IMAGE=aniseed/vmlinuz

**Comment by behlendorf** [comment]
Closing, nothing like this has been reported in over a year.  If you're still able to reproduce the issue with a current version of ZFS we can open a new issue.
