### ISSUE TITLE
Can't mount zfs from read-only pool when mountpoint=none

### ISSUE THREAD

**Issue by Grumbel** [zfsonlinux/zfs#2968]
As far as I can tell, it is currently not possible to mount a zfs filesystem when the `mointpoint` is set to `none` and the pool is `readonly`. Importing the pool without `-o readonly=on` isn't an option as the pool is broken and impossible to import read/write, see #2947.

    $ sudo zpool import -o readonly=on backup

    $ sudo zfs get mountpoint backup/archive
    NAME            PROPERTY    VALUE       SOURCE
    backup/archive  mountpoint  none        inherited from backup

    $ sudo zfs mount backup/archive
    cannot mount 'backup/archive': no mountpoint set

    # doesn't work since mountpoint isn't part of the Temporary Mount Point Properties
    $ sudo zfs mount -o mountpoint=/mnt3 backup/archiveoptions
    cannot mount 'backup/archive': no mountpoint set

    $ sudo zfs set mountpoint=/mnt3 backup/archive
    cannot set property for 'backup/archive': dataset is read-only

    $ sudo mount -t zfs backup/archive /mnt3
    filesystem 'backup/archive' cannot be mounted using 'mount'.
    Use 'zfs set mountpoint=legacy' or 'zfs mount backup/archive'.
    See zfs(8) for more information.

    $ sudo zfs set mountpoint=legacy backup/archive
    cannot set property for 'backup/archive': dataset is read-only

Mounting the zfs seems to require write access to the pool no matter what.

PS: `backup/archive` is an empty directory, so it's not a real problem for me, still found it a little weird that it doesn't seem to be possible to access it.

**Comment by behlendorf** [comment]
Closing.  Temporary mount point properties are now supported in master.

**Comment by Dante4** [comment]
> Closing. Temporary mount point properties are now supported in master.

based on https://openzfs.github.io/openzfs-docs/man/master/7/zfsprops.7.html#Temporary_Mount_Point_Properties

8 years later it's still not supported
