### ISSUE TITLE
ZFS requires CONFIG_PAX_USERCOPY_SLABS to be disabled

### ISSUE THREAD

**Issue by 8573** [zfsonlinux/zfs#2977]
Gentoo Linux’s `sys-fs/zfs-kmod-0.6.3-r1` package (and possibly
earlier versions; I don’t know) requires that the grsecurity/PaX
kernel configuration setting `CONFIG_PAX_USERCOPY_SLABS` be disabled.

I’m filing this report to track this issue on the pattern of
zfsonlinux/spl#422.

**Comment by behlendorf** [comment]
Closing.  Support added with commit zfsonlinux/spl@2ebe396
