### ISSUE TITLE
Ubuntu 14.04 on native ZFS root with MD RAID1 and UEFI and multiple pools

### ISSUE THREAD

**Issue by tommyhp2** [zfsonlinux/zfs#2982]
Hi folks,

After overcoming certain hurdles in setting up Ubuntu 14.04 LTS [1] using 6 HDDs with partitions as follow:

part-1 - vfat (fat32) for EFI to be mounted as /boot/efi
part-2 - linux raid for MD RAID1 to be mounted as /boot
part-3 - OS install and swap volume (RAID10)
part-4 - data (RAIDZ2)

I've encountered another problem with grub-probe and booting when having multiple ZFS pools:

root@host-t:~# zpool list
NAME   SIZE  ALLOC   FREE    CAP  DEDUP  HEALTH  ALTROOT
sys   55.1G  3.05G  52.1G     5%  1.00x  ONLINE  -
root@host-t:~# grub-probe /
zfs
root@host-t:~# zpool create -f -o ashift=12 -m /data data raidz2 `ls -1 /dev/disk/by-id/ata*part4`
root@host-t:~# zpool list
NAME   SIZE  ALLOC   FREE    CAP  DEDUP  HEALTH  ALTROOT
data  16.2T  6.34M  16.2T     0%  1.00x  ONLINE  -
sys   55.1G  3.13G  52.0G     5%  1.00x  ONLINE  -
root@host-t:~# grub-probe /
Segmentation fault
root@host-t:~# zpool destroy data
root@host-t:~# zpool list
NAME   SIZE  ALLOC   FREE    CAP  DEDUP  HEALTH  ALTROOT
sys   55.1G  3.19G  51.9G     5%  1.00x  ONLINE  -
root@host-t:~# grub-probe /
zfs
root@host-t:~# uname -a
Linux host-t 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Sometimes I get this for grub-probe:

root@host-t:~# zpool list
NAME   SIZE  ALLOC   FREE    CAP  DEDUP  HEALTH  ALTROOT
data  16.2T  5.11M  16.2T     0%  1.00x  ONLINE  -
sys   55.1G  3.96G  51.2G     7%  1.00x  ONLINE  -
root@host-t:~# grub-probe /
Floating point exception (core dumped)

and recent entry dmesg:

[  112.687551] traps: grub-probe[2531] trap divide error ip:42fd0c sp:7fff41ccb150 error:0 in grub-probe[400000+b8000]

I've verified this several times including using:

dd bs=100M if=/dev/zero of=/dev/disk/by-id/ata<each_hdd>

to remove any artifacts from partitioning, formatting of filesystem, and ZFS pool creation.  Does ZoL support multiple pools with mixed RAID type?  Or is this bug for Ubuntu 14.04 only?  Or because I have MD RAID too?  I haven't tried other Linux flavors or Ubuntu version.

Thanks,
Tommy

[1] https://github.com/zfsonlinux/zfs/issues/2956

**Comment by gmelikov** [comment]
Close as stale.

If it's actual - feel free to reopen.
