### ISSUE TITLE
Possible system throughput stall during arc reclaim

### ISSUE THREAD

**Issue by ryao** [zfsonlinux/zfs#2997]
My system has a ZFS rootfs, 32GB of RAM and no swap. It runs a custom branch that mostly contains the kmem-rework. I noticed a possible hiccup involving ARC memory reclaim when watching my system with htop during a firefox build when my system's memory was within 2GB of being completely full. For the most part, all cores were fully active and time spent in the kernel was about 10% or less on average. Then at some point in time, almost all activity ceased. The cores were mostly idle with a few percentage points of time spent in the kernel and memory usage dropped by something like 8GB. `ls -l $HOME` worked fine and nothing else appeared out of the ordinary. Then the system returned to normal as ARC reclaim appeared to cease.

The idea that memory reclaim can bring the firefox build process to a standstill until it finishes implies that there is some kind of lock contention in the kernel module between regular VFS operations and ARC reclamation that we need to address. This is probably the most vague issue description that I have yet to file, but this is all that I have go on right now. I am filing this anyway because the idea that lock contention under memory pressure needs more work is something that merits investigation.

That said, this stall is far better than what I have seen in the past and implies that we are making progress in this area.

**Comment by behlendorf** [comment]
Closing as stale.  We've had a lot of changes to the ARC in the last year which may improve this.  We can reopen this if your able to reproduce this kind of problem with master.
