### ISSUE TITLE
frequent failures on SSD Crucial M500

### ISSUE THREAD

**Issue by Bronek** [zfsonlinux/zfs#3007]
Hi, I have a 4 small SSDs Crucial M500 connected to HBA SAS 2308 (built into motherboard) , they are separated into partitions and the partitions are allocated to ZFS, as mirrors (each side from different physical disk). Frequently on computer startup ZFS fails to mount **both** sides of a mirror, e.g. like this:

```
status: An intent log record could not be read.
        Waiting for adminstrator intervention to fix the faulted pool.
action: Either restore the affected device(s) and run 'zpool online',
        or ignore the intent log records by running 'zpool clear'.
   see: http://zfsonlinux.org/msg/ZFS-8000-K4
  scan: scrub repaired 0 in 0h5m with 0 errors on Wed Jan  7 20:19:54 2015
config:

        NAME        STATE     READ WRITE CKSUM
        zdata       FAULTED      0     0     0  bad intent log
          mirror-0  ONLINE       0     0     0
            sdb     ONLINE       0     0     0
            sdc     ONLINE       0     0     0
          mirror-1  ONLINE       0     0     0
            sdd     ONLINE       0     0     0
            sde     ONLINE       0     0     0
        logs
          mirror-2  UNAVAIL      0     0     0  insufficient replicas
            sdh2    FAULTED      0     0     0  corrupted data
            sdi2    FAULTED      0     0     0  corrupted data
          mirror-3  ONLINE       0     0     0
            sdf2    ONLINE       0     0     0
            sdg2    ONLINE       0     0     0
```

This heals by itself if I restart computer sufficient number of times - or if I import the pool by hand. The pool you see above is a dataset which is not required for startup, but it is especially annoying when it happens to my root filesystem (which is ZFS mirrorred dataset). Self-healing is made possible by the fact that I placed a copy of /etc/zfs/zpool.cache inside my initramfs, but these failures are annoying nevertheless. The problem never happens to just one side of a mirror.

My software version is kernel 3.17.7 + small number of patches from ArchLinux, SPL vanilla 0.6.3-r1.2 and ZFS 0.6.3-r1.2 with small number of patches cleanly cherry-picked from master. I do not have problems with HDDs (WD red 4TB) only with SSDs, not sure because they are partitioned (different partition for different pool - e.g. only few gigs for SLOG of data pool and the rest for root dataset) or because there is something special about these SSDs.

**Comment by Bronek** [comment]
FWIW, this might be a duplicate of #2949 and/or #2927 although the distribution is different and I'm in total control of the packages (linux kernel, spl and zfs) installed. Installation steps were followed from instruction at https://wiki.archlinux.org/index.php/Installing_Arch_Linux_on_ZFS . I will try zeroing my hostid and followup later.

**Comment by dasjoe** [comment]
Maybe your devices get reordered during boot, `/dev/sdX` names are not guaranteed to be stable, so it's better to use `/dev/disk/by-id/`.

`zpool export poolname; zpool import -d /dev/disk/by-id/ poolname`, then regenerate your initrd to keep your zpool.cache current.

**Comment by Bronek** [comment]
Nope, that's not it. I've had this pool imported by /dev/disk/by-id and it still ocasionally fails to mount. Also, while displayed names refer to sdX, actual content of zpool.cache was with ids (I've had a peek)

**Comment by behlendorf** [comment]
From what you've described it sounds like there is a problem with the Crucial M500 drives or the controller they're attached too.  They've been faulted by ZFS because corrupted data has been detected while reading back the replay logs (i.e. bad checksums).

**Comment by Bronek** [comment]
Thank you! I will see if there is anything in dmesg next time this happens. Should I also look anywhere else?

**Comment by behlendorf** [comment]
dmesg is a good place to start.  I suspect there's a decent chance you'll see error reported by the device.

**Comment by Firedragon** [comment]
Could it be that fstrim or discard option is corrupting your data?
http://forum.crucial.com/t5/Crucial-SSDs/M500-on-Linux-with-fstrim-or-discard-under-heavy-load-could/td-p/151522

**Comment by Bronek** [comment]
Thanks for the link, but that's not it - I'm running kernel 3.17.7 and there is no trace of data corruption after I have unloaded zfs module and then loaded it back again. Also, the problem always affects both sides of a mirror at the same time.

**Comment by Bronek** [comment]
I think I fixed the problem, but no new binary was deployed. The problem was most likely between keyboard and chair.

I re-created cachefile while running the affected OS (as opposed to rescue Linux instance), ensuring (once again) that all disks inside cachefile are defined by /dev/disk/by-id and then "backed" this cachefile inside initramfs. This seem to have fixed the problem - after dozens of reboots I have not seen zpool status to report missing labels/disks or to replace disk identification with /dev/sdX

I would argue that there could possibly be problem (a bug) somewhere in zfs, when cachefile is created on separate system (rescue/live Linux) and then copied by hand to system actually running zfs (ie. target Linux), then this cachefile must to be replaced by hand in the target Linux on its first start, otherwise zfs cachefile will become corrupted - leading to errors reported in my first post.
