### ISSUE TITLE
Problem with iscsi target

### ISSUE THREAD

**Issue by hamsaeed** [zfsonlinux/zfs#3008]
hi,
I install zfs on linux , and create a zpool,
then install Iscsi target ,
can you help me for how i use zpool for iscsi target ,Please?

thanks,

**Comment by FransUrbo** [comment]
This is not a support forum. If you have a question on how to use ZFS, ZoL etc, please use the mailinglist. So would you be so kind to close this?

**Comment by hamsaeed** [comment]
I'm sorry,

**Comment by hamsaeed** [comment]
dear , where is mailinglist?
can you write their address?

**Comment by behlendorf** [comment]
@hamsaeed http://zfsonlinux.org/lists.html
