### ISSUE TITLE
zxg_sync blocked

### ISSUE THREAD

**Issue by theking2** [zfsonlinux/zfs#3026]
Just like thread https://github.com/zfsonlinux/zfs/issues/542 I witness frequent lock-ups on zxg_sync as well. This time during reboot and mount of a zfs. 
archlinux 3.18
system on SSD, 4 harddisks in a raidz2 setup, 2G  of RAM.

Just before the reboot I had copied a 5G amount of data. After that swap space was used up and I issued a reboot. As very little is running on this system I suspect zfs slowly using up swap space or in other words use up memory unchecked.

**Comment by dweeezil** [comment]
I suspect d695dbf might help with this.

**Comment by gmelikov** [comment]
Closing as stale.
