### ISSUE TITLE
raidz pool cannot be mount after one device failed

### ISSUE THREAD

**Issue by fantacinni** [zfsonlinux/zfs#3035]
My setup is a 5 disks raidz. (vault1, vault2, vault3, vault4, vault5)
One of the disk cannot be detected today, I powered off the computer, pull the failed disk out and replace a new disk in, boot into Linuxmint 17.1, the pool is not auto mounted.
This is the output of 'zpool import -f ':
>   pool: tank
>    id: 12080607584394764917
>  state: UNAVAIL
> status: One or more devices are missing from the system.
> action: The pool cannot be imported. Attach the missing
>	devices and try again.
>   see: http://zfsonlinux.org/msg/ZFS-8000-6X
> config:
>
>	tank         UNAVAIL  missing device
>	  vault1     ONLINE
>	  vault2     ONLINE
>	  vault3     ONLINE
>	  vault4     ONLINE
>
>	Additional devices are known to be part of this pool, though their
>	exact configuration cannot be determined.

**Comment by AndCycle** [comment]
your setup doesn't looks like raidz, are you sure about that?

here is example output
http://serverfault.com/questions/352287/zfs-raidz-import-failure-when-migrating

**Comment by fantacinni** [comment]
I'm pretty sure I've created it with raidz...
The ZFS total space is around 7.3TiB, and my disks are 2TiB, So it matches the raidz n-1 rule.
How do I check if it is raidz or not now?

**Comment by AndCycle** [comment]
take a look at that link,
https://forums.freebsd.org/threads/cannot-import-raidz-after-power-failure-metadata-corrupted.36865/
it should mention raidz1 in config, which doesn't exists in your output

**Comment by fantacinni** [comment]
Checked my bash history, I was using this options to create the pool...
> zpool create -O mountpoint=none -o ashift=12 -O compression=lz4 -O atime=off -O xattr=sa tank raidz /dev/mapper/vault1 /dev/mapper/vault2 /dev/mapper/vault3 /dev/mapper/vault4 /dev/mapper/vault5
I'll check the link you provied.

**Comment by fantacinni** [comment]
O my mistake, I created a JBOD pool before....
Thanks for the help!
