### ISSUE TITLE
gpg key 0xF14AB620

### ISSUE THREAD

**Issue by paep** [zfsonlinux/zfs#3039]
The Fedora packages are apparently signed with the gpg key 0xF14AB620. To calm the paranoid amongst us, perhaps it would be an idea to list that key as an official signing key on the zfsonlinux.org web site?

**Comment by behlendorf** [comment]
@peep Definitely a good idea, right now the key is just part of the zfs-release package.

**Comment by behlendorf** [comment]
The public key ID and fingerprint have been added to the Fedora and EPEL pages.

http://zfsonlinux.org/fedora.html
http://zfsonlinux.org/epel.html

**Comment by paep** [comment]
Many thanks! /Anders

On 02/06/2015 12:04 AM, Brian Behlendorf wrote:
> The public key ID and fingerprint have been added to the Fedora and EPEL
> pages.
> 
> http://zfsonlinux.org/fedora.html
> http://zfsonlinux.org/epel.html
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zfsonlinux/zfs/issues/3039#issuecomment-73149260>.
> 

-- 
GnuPG key id: 7EAE66A8
