### ISSUE TITLE
Pool imported as sdX instead of /dev/disk/by-id

### ISSUE THREAD

**Issue by azeemism** [zfsonlinux/zfs#3043]
Hi,

Exporting then importing a pool shows devices listed as sdX under zpool status.

Pool was created as
zpool create spool mirror /dev/disk/by-id/... /dev/disk/by-id/...

Unless the -d options is used each time the pool is imported.
zpool import -d /dev/disk/by-id spool

This is not the case with v0.6.3-766_gfde0d6d.

Not sure if this is somehow related to,
https://github.com/zfsonlinux/zfs/issues/2482

Using:
VirtualBox
(fresh install) Debian Jessie
(dailies) zfs v0.6.3-22~2d9d57~jessie

Thanks,

Azeem

**Comment by azeemism** [comment]
I can now report that after the dailies fix

https://github.com/zfsonlinux/pkg-zfs/issues/138

If a pool is export it is imported back automatically with /dev/disk/by-id after a reboot. This wasn't the case before the fix. 

However if the pool is imported manually, unless the "-d /dev/disk/by-id" option is used it gets imported as /dev/sdX.

It would be nice it manual import remembered the disk naming format from either

zpool create tank mirror /dev/disk/by-id /dev/disk/by-id
or
zpool import -d /dev/disk/by-id tank

But that is a minor concern.

**Comment by FransUrbo** [comment]
> However if the pool is imported manually, unless the "-d /dev/disk/by-id" option is used it gets imported as /dev/sdX.
> 
This is most likely due to the zpool.cache file. Try setting 'cachefile=none' on your pool(s) and, if it's still there, remove /etc/zfs/zpool.cache and recreate the initrd.

Also, make sure that USE_DISK_BY_ID='yes' in /etc/default/zfs (before recreating the initrd).=

**Comment by azeemism** [comment]
Okay will try this out right now.

I assume the command to recreate the initrd is,

mv initrd.img-3.16.0-4-amd64 initrd.img-3.16.0-4-amd64.old
update-initramfs -c -k all

**Comment by azeemism** [comment]
No change. An exported pool is always imported back as /dev/disk/by-id after reboot. "zpool import spool" is always imported as /dev/sdX

*** 
nano /etc/default/zfs
USE_DISK_BY_ID='yes'
Is the default setting which is good.

zpool set cachefile=none spool
Automatically deleted /etc/zfs/zpool.cache
At reboot zpool.cache file was recreated

update-initramfs -c -k all

**Comment by nicko88** [comment]
I think you are running into this:

http://www.reddit.com/r/zfs/comments/2ugerx/workaround_to_restore_bypath_behavior_for_sata/

**Comment by Bronek** [comment]
I was experiencing identical issue until I removed `zpool import -aN` from initramfs ZFS hook of my system. After removing this command, my pools (except for root filesystem) are imported using `zpool.cache` only. Since then the device names in my pools are no longer replaced with /dev/sdX .

I raised in ZFS package for my Linux distribution to remove `zpool import -aN` : https://github.com/archzfs/archzfs/issues/50 .

**Comment by alexanderhaensch** [comment]
I ran into this problem recently. 
Wouldn't it be best to default the command 
zpool import $pool
to
zpool import -d /dev/by-id $pool

The legacy /dev/sdX is getting more and more unreliable.

**Comment by behlendorf** [comment]
@alexanderhaensch you can change the default search order with the ZPOOL_IMPORT_PATH environment variable.  See `zpool.8`.

```
       ZPOOL_IMPORT_PATH
              The  search path for devices or files to use with the pool. This
              is a colon-separated list of directories in  which  zpool  looks
              for  device  nodes and files.  Similar to the -d option in zpool
              import.
```

That said, you may be right and it's time to change the default.  The primary reason it was left as `/dev/` for so long was many of the distributions hasn't yet standardized on the `/dev/disk/by-id/` convention.  However, times are a changing and I can't think of a disro offland that doesn't ship with those udev rules.

It would be great if you set ZPOOL_IMPORT_PATH on your systems to simulate a change in the default search paths.

**Comment by alexanderhaensch** [comment]
@behlendorf setting the environment variable works great. Now i can import my pool much easier without having the sdX which is changing every boot. :)

**Comment by behlendorf** [comment]
@alexanderhaensch what did you end up setting it to.  The default search order is as follows starting with `by-vdev`.

```
char *
zpool_default_import_path[DEFAULT_IMPORT_PATH_SIZE] = {
        "/dev/disk/by-vdev",    /* Custom rules, use first if they exist */
        "/dev/mapper",          /* Use multipath devices before components */
        "/dev/disk/by-uuid",    /* Single unique entry and persistent */
        "/dev/disk/by-id",      /* May be multiple entries and persistent */
        "/dev/disk/by-path",    /* Encodes physical location and persistent */
        "/dev/disk/by-label",   /* Custom persistent labels */
        "/dev"                  /* UNSAFE device names will change */
};
```

**Comment by alexanderhaensch** [comment]
For some reason, the function zfs_resolve_shortname does not use vdev to label. On my system always /dev is used.

**Comment by alexanderhaensch** [comment]
I tested a little bit: 
with ZPOOL_IMPORT_PATH="/dev/disk/by-id" :

```
config:

        NAME                                               STATE     READ WRITE CKSUM
        storage                                            ONLINE       0     0     0
          raidz1-0                                         ONLINE       0     0     0
            ata-ST3000VX000-1CU166_W1F4HC6Q                ONLINE       0     0     0
            ata-ST3000VX000-1CU166_W1F45XDY                ONLINE       0     0     0
            ata-ST3000VX000-1CU166_W1F45WV8                ONLINE       0     0     0

cache
          ata-Corsair_Force_GT_113882030000070000A4-part3  ONLINE       0     0     0 
```                                                                                                                                           

with ZPOOL_IMPORT_PATH="/dev/disk/by-vdev" :

```
config:                                                                             
        NAME                                               STATE     READ WRITE CKSUM
        storage                                            ONLINE       0     0     0
          raidz1-0                                         ONLINE       0     0     0
            disk3                                          ONLINE       0     0     0
            disk2                                          ONLINE       0     0     0
            disk1                                          ONLINE       0     0     0
        cache
          ata-Corsair_Force_GT_113882030000070000A4-part3  ONLINE       0     0     0
```                     

without any  ZPOOL_IMPORT_PATH :

```
config:
        NAME                                               STATE     READ WRITE CKSUM
        storage                                            ONLINE       0     0     0
          raidz1-0                                         ONLINE       0     0     0
            sdd                                            ONLINE       0     0     0
            sdf                                            ONLINE       0     0     0
            sda                                            ONLINE       0     0     0
        cache
          ata-Corsair_Force_GT_113882030000070000A4-part3  ONLINE       0     0     0
```

**Comment by rlaager** [comment]
This came up in the Ubuntu bug tracker as well: https://bugs.launchpad.net/ubuntu/+source/zfs-linux/+bug/1571241

**Comment by samvde** [comment]
Additional info (I logged the Ubuntu bug report): I was not able to get the ZPOOL_IMPORT_PATH working for the root filesystem on Ubuntu 16.04, i.e. adding it to /etc/default/zfs does not propagate this into the initrd.

**Comment by rlaager** [comment]
Is `zpool import` ignoring zpool_default_import_path because of libblkid?

https://github.com/zfsonlinux/zfs/blob/8fc5674c522e22f0b97e4714bf5410e24d481afa/lib/libzfs/libzfs_import.c#L1599

**Comment by behlendorf** [comment]
@rlaager spot on, I've added a patch to the existing #4523 pull request to address this.  At its core the patch adds any alternate paths to the device which are described by the vdev label.  This will preserve the original name if the device still is accessible by that path.

**Comment by rlaager** [comment]
@behlendorf I tested that patch. Applying only that patch fixes the issue observed in Ubuntu. That is, if I have a pool which was last imported using /dev/disk/by-id names, the patch causes zpool import to import it using /dev/disk/by-id names.
