### ISSUE TITLE
zfsutils error: unable to read zfs.target

### ISSUE THREAD

**Issue by azeemism** [zfsonlinux/zfs#3044]
Hi,

Regarding the dailies version of zfs:

When installing zfsutils (0.6.3-22~2d9d57~jessie) to a VirtualBox instance of Debian Jessie, I receive the following error (repeated twice):

/usr/bin/deb-systemd-helper: error: unable to read zfs.target

I am not sure if this is okay to ignore. Only related info I found was at these two links:

http://www.mattzone.com/zfsonlinux/zfsonlinux_20141015.html
https://groups.google.com/a/zfsonlinux.org/forum/#!topic/zfs-discuss/NdjlJBEqc10

init-system-helpers version installed is 1.22.

Thanks for all that you do,

Azeem

**Comment by FransUrbo** [comment]
> When installing zfsutils (0.6.3-22~2d9d57~jessie) to a VirtualBox instance of Debian Jessie, I receive the following error (repeated twice):
> 
> /usr/bin/deb-systemd-helper: error: unable to read zfs.target
> 
This belong to https://github.com/zfsonlinux/pkg-zfs, please move it there.
