### ISSUE TITLE
grub-probe error: unknown filesystem

### ISSUE THREAD

**Issue by azeemism** [zfsonlinux/zfs#3045]
Hi,

Regarding the dailies version of zfs: 0.6.3-22~2d9d57~jessie

Mounted zfs files systems are not detected by grub-probe with "error: unknown filesystem" being returned. No such issue found with with version v0.6.3-766_gfde0d6d. I am running Debian Jessie of VirtualBox.

All packages below are version: 2.02~beta2-19 amd64
grub-efi
grub-efi-amd64
grub-efi-amd64-bin
grub2-common

Thanks for all that you do,

Azeem

**Comment by FransUrbo** [comment]
> Mounted zfs files systems are not detected by grub-probe with "error: unknown filesystem" being returned. No such issue found with with version v0.6.3-766_gfde0d6d. I am running Debian Jessie of VirtualBox.
> 
This belong to https://github.com/zfsonlinux/grub, please move it there.=
