### ISSUE TITLE
grub-update does not identify pool correctly: root=ZFS=<missing>/ROOT/debian

### ISSUE THREAD

**Issue by azeemism** [zfsonlinux/zfs#3046]
Hi,

Regarding the dailies version of zfs: 0.6.3-22~2d9d57~jessie

I am running grub-update under chroot, during native-zfs-root-filesystem installation. The parameter root=ZFS= is missing the pool name. This may be related to #3045. No such issue was found with  version 0.6.3-766_gfde0d6d

The /boot/grub/grub.cfg file is updated with,
root=/ROOT/debian

Instead of,
root=ZFS=spool/ROOT/debian

This occurs with or without the following parameters set in /etc/default/grub
boot=zfs rpool=spool bootfs=spool/ROOT/debian

This issue can be duplicated as follows:

VirtualBox Installation of Debian Jessie (RAID 10)
sda1 - UEFI
sd[a-d]2 - unformatted for zfs
sd[a-d]3 - swap
sd[a-d]4 - /boot
sd[a-d]5 - /

Install zfs dailies, 
create pool 
zpool create -m none spool mirror /dev/disk/by-id /dev/disk/by-id mirror  /dev/disk/by-id /dev/disk/by-id
create datasets for spool/ROOT/debian
add /etc/udev/rules.d/70-zfs-grub-fix.rules
from: https://github.com/zfsonlinux/grub/issues/5
zpool export spool
zpool import -o altroot=/sysroot spool
zfs set mountpoint=/ spool/ROOT/debian
rsync -axv / /sysroot/
rsync -axv /dev/ /sysroot/dev/
chroot /sysroot /bin/bash
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount /boot
nano /etc/fstab
comment out line for /
can add or not add line for spool/ROOT/debian / zfs default,noatime 0 0
update-initramfs -c -k all
update-grub

Thanks for all that you do,

Azeem

**Comment by FransUrbo** [comment]
> I am running grub-update under chroot, during native-zfs-root-filesystem installation. The parameter root=ZFS= is missing the pool name. This may be related to #3045. No such issue was found with version 0.6.3-766_gfde0d6d
> 
This belong to https://github.com/zfsonlinux/grub, please move it there.
