### ISSUE TITLE
Error inserting zcommon

### ISSUE THREAD

**Issue by kiranfractal** [zfsonlinux/zfs#3051]
Hi,

Trying to install latest zfs from zfs-testing.

I am getting below error.
\# modprobe zfs
----------------------
WARNING: Error inserting zcommon (/lib/modules/2.6.32-504.1.3.el6.x86_64/extra/zcommon.ko): Unknown symbol in module, or unknown parameter (see dmesg)
FATAL: Error inserting zfs (/lib/modules/2.6.32-504.1.3.el6.x86_64/extra/zfs.ko): Unknown symbol in module, or unknown parameter (see dmesg)

dmesg output:
------------------
znvpair: Unknown symbol spl_debug_bug
znvpair: Unknown symbol spl_debug_bug
znvpair: Unknown symbol spl_debug_bug
znvpair: Unknown symbol spl_debug_bug
Adding 262140k swap on /dev/xvdb.  Priority:-1 extents:1 across:262140k SS
znvpair: Unknown symbol spl_debug_bug
NET: Registered protocol family 10
lo: Disabled Privacy Extensions
type=1305 audit(1422538182.293:3): audit_pid=27660 old=0 auid=4294967295 ses=4294967295 res=1
znvpair: Unknown symbol spl_debug_bug
znvpair: Unknown symbol spl_debug_bug
znvpair: Unknown symbol spl_kmem_free
znvpair: Unknown symbol spl_kmem_alloc
znvpair: Unknown symbol spl_kmem_free
znvpair: Unknown symbol spl_kmem_alloc
znvpair: Unknown symbol spl_kmem_free
znvpair: Unknown symbol spl_kmem_alloc
znvpair: Unknown symbol spl_kmem_free
znvpair: Unknown symbol spl_kmem_alloc
znvpair: Unknown symbol spl_kmem_free
znvpair: Unknown symbol spl_kmem_alloc

ZFS version:
----------------
filename:       /lib/modules/2.6.32-504.1.3.el6.x86_64/extra/zfs.ko
version:        0.6.3-189_g6466b61
license:        CDDL
author:         OpenZFS on Linux
description:    ZFS
srcversion:     F9A95F3D589BAF99B43618C
depends:        spl,znvpair,zcommon,zunicode,zavl
vermagic:       2.6.32-504.1.3.el6.x86_64 SMP mod_unload modversions 

Operating System:
----
\# cat /etc/issue
CentOS release 6.6 (Final)
Kernel \r on an \m

Thanks.

**Comment by behlendorf** [comment]
You need to update the SPL and ZFS source then rebuild.

**Comment by kiranfractal** [comment]
I removed the spl and zfs and its dependent packages and reinstalled zfs using "yum install zfs" it installed without any error.
