### ISSUE TITLE
zpl_evict_inode should call truncate_inode_pages_final() on Linux 3.15 or later

### ISSUE THREAD

**Issue by ryao** [zfsonlinux/zfs#3056]
According to torvalds/linux@91b0abe36a7b2b3b02d7500925a5f8455334f0e5, the proper way to evict an inode is to call `truncate_inode_pages_final()` and be certain that there is no async writeback running as of Linux 3.15 and later. We should look into making the ZPL do this.

**Comment by behlendorf** [comment]
Interesting.  I'm glad you noticed this.

**Comment by behlendorf** [comment]
Closing for now, this is something we'll want to examine more closely when integrating with the page cache.
