### ISSUE TITLE
Large kmem_alloc BUG

### ISSUE THREAD

**Issue by AeonJJohnson** [zfsonlinux/zfs#3057]
Getting these when loading spl/zfs kernel modules on linux-3.18.4. Using Brian Behlendorf's largeblock branch (0.6.3-183_gdd078c8).

SPL: Loaded module v0.6.3-68_g9099312
zunicode: module license 'CDDL' taints kernel.
Disabling lock debugging due to kernel taint
ZFS: Loaded module v0.6.3-183_gdd078c8, ZFS pool version 5000, ZFS filesystem version 5
SPL: using hostid 0x00000000
Large kmem_alloc(39864, 0x0), please file an issue at:
https://github.com/zfsonlinux/zfs/issues/new
CPU: 5 PID: 70837 Comm: zpool Tainted: P           OE  3.18.4 #1
Hardware name: Intel Corporation S2600CP/S2600CP, BIOS SE5C600.86B.02.04.0003.102320141138 10/23/2014
 0000000000000000 ffff880feb8dbcd8 ffffffff8159f058 0000000000000002
 00000000000042d0 ffff880feb8dbd08 ffffffffa04e2071 ffff880fadbfb9c0
 0000000000009bb8 ffff880feb8dbde0 ffff880feb8dbd80 ffff880feb8dbd18
Call Trace:
 [<ffffffff8159f058>] dump_stack+0x49/0x61
 [<ffffffffa04e2071>] spl_kmem_alloc+0x141/0x1d0 [spl]
 [<ffffffffa056387f>] nv_alloc_sleep_spl+0x1f/0x30 [znvpair]
 [<ffffffffa055e683>] nv_mem_zalloc+0x23/0x50 [znvpair]
 [<ffffffffa05602a9>] nvlist_xpack+0xb9/0x110 [znvpair]
 [<ffffffffa056031a>] nvlist_pack+0x1a/0x40 [znvpair]
 [<ffffffffa05636bb>] fnvlist_pack+0x3b/0x90 [znvpair]
 [<ffffffffa061a686>] put_nvlist+0x46/0xb0 [zfs]
 [<ffffffffa061e32a>] zfs_ioc_pool_tryimport+0x6a/0x90 [zfs]
 [<ffffffffa06205ce>] zfsdev_ioctl+0x44e/0x480 [zfs]
 [<ffffffff810882fb>] ? pick_next_task_fair+0x15b/0x210
 [<ffffffff811aa713>] do_vfs_ioctl+0x73/0x380
 [<ffffffff811aaac1>] SyS_ioctl+0xa1/0xb0
 [<ffffffff810e9cbc>] ? __audit_syscall_entry+0xac/0x110
 [<ffffffff815a3292>] system_call_fastpath+0x12/0x17
Large kmem_alloc(39964, 0x0), please file an issue at:
https://github.com/zfsonlinux/zfs/issues/new
CPU: 5 PID: 70837 Comm: zpool Tainted: P           OE  3.18.4 #1
Hardware name: Intel Corporation S2600CP/S2600CP, BIOS SE5C600.86B.02.04.0003.102320141138 10/23/2014
 0000000000000000 ffff880feb8dbdb8 ffffffff8159f058 0000000000000000
 00000000000042d0 ffff880feb8dbde8 ffffffffa04e2071 0000000000009c1c
 0000000000000060 0000000001a3d470 0000000000000000 ffff880feb8dbe48
Call Trace:
 [<ffffffff8159f058>] dump_stack+0x49/0x61
 [<ffffffffa04e2071>] spl_kmem_alloc+0x141/0x1d0 [spl]
 [<ffffffffa061a50e>] get_nvlist+0x6e/0xd0 [zfs]
 [<ffffffffa061dc49>] zfs_ioc_pool_import+0x39/0x120 [zfs]
 [<ffffffffa06205ce>] zfsdev_ioctl+0x44e/0x480 [zfs]
 [<ffffffff811aa713>] do_vfs_ioctl+0x73/0x380
 [<ffffffff811aaac1>] SyS_ioctl+0xa1/0xb0
 [<ffffffff810e9cbc>] ? __audit_syscall_entry+0xac/0x110
 [<ffffffff815a3292>] system_call_fastpath+0x12/0x17
Large kmem_alloc(40100, 0x0), please file an issue at:
https://github.com/zfsonlinux/zfs/issues/new
CPU: 2 PID: 70837 Comm: zpool Tainted: P           OE  3.18.4 #1
Hardware name: Intel Corporation S2600CP/S2600CP, BIOS SE5C600.86B.02.04.0003.102320141138 10/23/2014
 0000000000000000 ffff880feb8dbcd8 ffffffff8159f058 0000000000000002
 00000000000042d0 ffff880feb8dbd08 ffffffffa04e2071 ffff880fadbfb9c0
 0000000000009ca4 ffff880feb8dbde0 ffff880feb8dbd80 ffff880feb8dbd18
Call Trace:
 [<ffffffff8159f058>] dump_stack+0x49/0x61
 [<ffffffffa04e2071>] spl_kmem_alloc+0x141/0x1d0 [spl]
 [<ffffffffa056387f>] nv_alloc_sleep_spl+0x1f/0x30 [znvpair]
 [<ffffffffa055e683>] nv_mem_zalloc+0x23/0x50 [znvpair]
 [<ffffffffa05602a9>] nvlist_xpack+0xb9/0x110 [znvpair]
 [<ffffffffa056031a>] nvlist_pack+0x1a/0x40 [znvpair]
 [<ffffffffa05636bb>] fnvlist_pack+0x3b/0x90 [znvpair]
 [<ffffffffa061a686>] put_nvlist+0x46/0xb0 [zfs]
 [<ffffffffa061dd0c>] zfs_ioc_pool_import+0xfc/0x120 [zfs]
 [<ffffffffa06205ce>] zfsdev_ioctl+0x44e/0x480 [zfs]
 [<ffffffff811aa713>] do_vfs_ioctl+0x73/0x380
 [<ffffffff811aaac1>] SyS_ioctl+0xa1/0xb0
 [<ffffffff810e9cbc>] ? __audit_syscall_entry+0xac/0x110
 [<ffffffff815a3292>] system_call_fastpath+0x12/0x17
Large kmem_alloc(39828, 0x0), please file an issue at:
https://github.com/zfsonlinux/zfs/issues/new
CPU: 2 PID: 70837 Comm: zpool Tainted: P           OE  3.18.4 #1
Hardware name: Intel Corporation S2600CP/S2600CP, BIOS SE5C600.86B.02.04.0003.102320141138 10/23/2014
 0000000000000000 ffff880feb8dbcd8 ffffffff8159f058 0000000000000002
 00000000000042d0 ffff880feb8dbd08 ffffffffa04e2071 ffff880fac75fda0
 0000000000009b94 ffff880feb8dbde0 ffff880feb8dbd80 ffff880feb8dbd18
Call Trace:
 [<ffffffff8159f058>] dump_stack+0x49/0x61
 [<ffffffffa04e2071>] spl_kmem_alloc+0x141/0x1d0 [spl]
 [<ffffffffa056387f>] nv_alloc_sleep_spl+0x1f/0x30 [znvpair]
 [<ffffffffa055e683>] nv_mem_zalloc+0x23/0x50 [znvpair]
 [<ffffffffa05602a9>] nvlist_xpack+0xb9/0x110 [znvpair]
 [<ffffffffa056031a>] nvlist_pack+0x1a/0x40 [znvpair]
 [<ffffffffa05636bb>] fnvlist_pack+0x3b/0x90 [znvpair]
 [<ffffffffa061a67a>] ? put_nvlist+0x3a/0xb0 [zfs]
 [<ffffffffa061a686>] put_nvlist+0x46/0xb0 [zfs]
 [<ffffffffa061e04b>] zfs_ioc_pool_stats+0x4b/0x70 [zfs]
 [<ffffffffa06205ce>] zfsdev_ioctl+0x44e/0x480 [zfs]
 [<ffffffff811aa713>] do_vfs_ioctl+0x73/0x380
 [<ffffffff811aaac1>] SyS_ioctl+0xa1/0xb0
 [<ffffffff810e9cbc>] ? __audit_syscall_entry+0xac/0x110
 [<ffffffff815a3292>] system_call_fastpath+0x12/0x17
Large kmem_alloc(39828, 0x0), please file an issue at:
https://github.com/zfsonlinux/zfs/issues/new
CPU: 2 PID: 70837 Comm: zpool Tainted: P           OE  3.18.4 #1
Hardware name: Intel Corporation S2600CP/S2600CP, BIOS SE5C600.86B.02.04.0003.102320141138 10/23/2014
 0000000000000000 ffff880feb8dbcd8 ffffffff8159f058 0000000000000002
 00000000000042d0 ffff880feb8dbd08 ffffffffa04e2071 ffff880fac75fda0
 0000000000009b94 ffff880feb8dbde0 ffff880feb8dbd80 ffff880feb8dbd18
Call Trace:
 [<ffffffff8159f058>] dump_stack+0x49/0x61
 [<ffffffffa04e2071>] spl_kmem_alloc+0x141/0x1d0 [spl]
 [<ffffffffa056387f>] nv_alloc_sleep_spl+0x1f/0x30 [znvpair]
 [<ffffffffa055e683>] nv_mem_zalloc+0x23/0x50 [znvpair]
 [<ffffffffa05602a9>] nvlist_xpack+0xb9/0x110 [znvpair]
 [<ffffffffa056031a>] nvlist_pack+0x1a/0x40 [znvpair]
 [<ffffffffa05636bb>] fnvlist_pack+0x3b/0x90 [znvpair]
 [<ffffffffa061a686>] put_nvlist+0x46/0xb0 [zfs]
 [<ffffffffa061e04b>] zfs_ioc_pool_stats+0x4b/0x70 [zfs]
 [<ffffffffa06205ce>] zfsdev_ioctl+0x44e/0x480 [zfs]
 [<ffffffff811aa713>] do_vfs_ioctl+0x73/0x380
 [<ffffffff811aaac1>] SyS_ioctl+0xa1/0xb0
 [<ffffffff810e9cbc>] ? __audit_syscall_entry+0xac/0x110
 [<ffffffff815a3292>] system_call_fastpath+0x12/0x17

**Comment by behlendorf** [comment]
@AeonJJohnson these are harmless and just advisory, but we'll definitely get them fixed up quickly in master.  Thanks for reporting them.

**Comment by behlendorf** [comment]
A patch for this has been added in #3076.
