### ISSUE TITLE
spa_maxblocksize not exported

### ISSUE THREAD

**Issue by rpwagner** [zfsonlinux/zfs#3058]
As part of the Lustre effort to [support large blocks with ZFS| https://jira.hpdd.intel.com/browse/LU-6152], `spa_maxblocksize` is being access from the Lustre modules and needs to be exported. I dropped this change into my code and have successfully mounted ZFS-backed MDTs and OSTS. The exports are organized by topic, and I wasn't sure where this should go, or I would have submitted a pull request.

```
diff --git a/module/zfs/spa_misc.c b/module/zfs/spa_misc.c
index 48f6d70..2591e27 100644
--- a/module/zfs/spa_misc.c
+++ b/module/zfs/spa_misc.c
@@ -2024,6 +2024,7 @@ EXPORT_SYMBOL(spa_has_slogs);
 EXPORT_SYMBOL(spa_is_root);
 EXPORT_SYMBOL(spa_writeable);
 EXPORT_SYMBOL(spa_mode);
+EXPORT_SYMBOL(spa_maxblocksize);
 
 EXPORT_SYMBOL(spa_namespace_lock);
```

**Comment by behlendorf** [comment]
@rpwagner Thanks, I've made the same change to the updated large block branch I'm testing.  I just haven't pushed the update branch yet.  That should hopefully happen today.

**Comment by behlendorf** [comment]
Closing, this change was folded in to the updated largeblock patch.
