### ISSUE TITLE
configure: error at debian-zfs package installation on Debian 7

### ISSUE THREAD

**Issue by hostingnuggets** [zfsonlinux/zfs#3065]
I followed the exact instructions on http://zfsonlinux.org/debian.html in order to install ZFS on Debian 7 but nevertheless I get the following error message during the installation of the debian-zfs package:

```
...
Loading new zfs-0.6.3 DKMS files...
First Installation: checking all kernels...
Building only for 3.2.0-4-amd64
Building initial module for 3.2.0-4-amd64
configure: error: 
    *** Please make sure the kmod spl devel <kernel> package for your
    *** distribution is installed then try again.  If that fails you
    *** can specify the location of the spl objects with the
    *** '--with-spl-obj=PATH' option.
Error! Bad return status for module build on kernel: 3.2.0-4-amd64 (x86_64)
...
```

still it looks like ZFS is working but this error sounds quite bad... any ideas? or maybe a bug in the installer?

**Comment by FransUrbo** [comment]
>     *** Please make sure the kmod spl devel <kernel> package for your
>     *** distribution is installed then try again.  If that fails you
>     *** can specify the location of the spl objects with the
>     *** '--with-spl-obj=PATH' option.
This seem to happen every now and then. Don't know why and I have not been able to reproduce it…

But apparently, for some reason, the spl-dkms package isn't installed/configured first.

Try

	dpkg --purge --force-depends spl-dkms
	apt-get install spl-dkms

After that, if that look like it's worked, run

	dpkg --configure --pending

**Comment by hostingnuggets** [comment]
Thanks that trick worked but it would be really good if someone could take a closer look to this packaging issue on Debian 7.

**Comment by N7DR** [comment]
So does this error actually matter? 

I saw it when I did my last ZFS install (on a pristine debian 7 system), but since the installation proceeded quite happily from that point, I assumed that the error was trapped and resolved behind the scenes by the installation routines (not, I think an unreasonable expectation: several distros seem to perform updates and upgrades in that manner). The system has been running fine for weeks despite this error in the installation.

**Comment by hostingnuggets** [comment]
@N7DR I had exactly the same impression. Although you get this error message ZFS still seems to be fully functional. On the other hand someone should really fix this packaging issue on Debian as it is very misleading.

**Comment by behlendorf** [comment]
> But apparently, for some reason, the spl-dkms package isn't installed/configured first.

We had a similar issue for a long time on Fedora / EPEL until those distributions updated the version of DKMS they're shipping to include the following patch.  I'm not sure if the version of DKMS shipped by debian include this fix.

https://bugzilla.redhat.com/show_bug.cgi?id=1023598

**Comment by aizikil** [comment]
Here is a workaround http://louwrentius.com/installation-of-zfs-on-linux-hangs-on-debian-wheezy.html

**Comment by FransUrbo** [comment]
@aizikil The workaround is irrelevant for THIS issue (it's a good one for #3103).

**Comment by FransUrbo** [comment]
We might be on to something here. Don't quite know how to fix it simple though.

The Debian GNU/Linux version of dkms does NOT contain the relevant patches. However, I/we/ZoL have one that do, version <code>2.2.0.3-1.2+zfs6</code> made by Darik Horn made Mar 20, 2013. This gets 'sucked in' with an install, but apparently it's not installed and configured BEFORE it's needed for some people (I've tried several times, and I've never had this problem on any of my test installs - and I've done hundreds).

**Comment by ColinIanKing** [comment]
Just for reference, I'm seeing this on Ubuntu wily too.  If one installs gcc first and then zfs it works. I'm trying to debug this one further as it seems to bite a few users now.

**Comment by behlendorf** [comment]
@ColinIanKing thanks for looking in to this.  For what it's worth in epel dkms depends on gcc so it's brought in first that way when the dependencies are solved.

**Comment by ColinIanKing** [comment]
I believe that spl DKMS builds are failing because although we have gcc installed, the test for gcc building correctly depends on having libc-dev installed.  If one installs that first then all is good.  I've got a clean reproducer now working that fails 100% of the time, so I'm pretty close now to building and testing a possible workaround/fix.

**Comment by ColinIanKing** [comment]
OK, I believe this looks like a suitable fix, I've tested it out and it does the trick:

spl-linux:  debian/control, 

Package: spl-dkms
Depends: ${misc:Depends}, libc-dev, dkms (>= 2.2.0.2), file, lsb-release
Recommends: spl

The libc-dev is required to make the spl build OK with DKMS on a totally clean machine.  I suspect many people don't see this issue as they normally have this installed.  I'm going to hammer this to death with some repeated automated testing to see if it is 100% sane and works, and then send you a patch sometime tomorrow once I'm totally happy with it.

**Comment by ColinIanKing** [comment]
Yep, this seems solid. I've done a pull request for this on github

**Comment by mrvn** [comment]
Seems to still happen:

(Reading database ... 118844 files and directories currently installed.)
Preparing to unpack .../libc6-dev_2.24-5_amd64.deb ...
Unpacking libc6-dev:amd64 (2.24-5) over (2.24-2) ...
Preparing to unpack .../libc-dev-bin_2.24-5_amd64.deb ...
Unpacking libc-dev-bin (2.24-5) over (2.24-2) ...
Preparing to unpack .../linux-libc-dev_4.7.8-1_amd64.deb ...
Unpacking linux-libc-dev:amd64 (4.7.8-1) over (4.7.2-1) ...
Preparing to unpack .../libc6_2.24-5_amd64.deb ...
Unpacking libc6:amd64 (2.24-5) over (2.24-2) ...
Setting up libc6:amd64 (2.24-5) ...
Processing triggers for libc-bin (2.24-2) ...
Processing triggers for man-db (2.7.5-1) ...
Selecting previously unselected package spl-dkms.
(Reading database ... 118844 files and directories currently installed.)
Preparing to unpack .../spl-dkms_0.6.5.8-2_all.deb ...
Unpacking spl-dkms (0.6.5.8-2) ...
Setting up libc-dev-bin (2.24-5) ...
Setting up linux-libc-dev:amd64 (4.7.8-1) ...
Setting up libc6-dev:amd64 (2.24-5) ...
Setting up spl-dkms (0.6.5.8-2) ...
Loading new spl-0.6.5.8 DKMS files...
First Installation: checking all kernels...
Building for 4.4.0-1-amd64 and 4.7.0-1-amd64
Building initial module for 4.4.0-1-amd64
Done.

spl:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.4.0-1-amd64/updates/dkms/

splat.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.4.0-1-amd64/updates/dkms/

depmod....

DKMS: install completed.
Building initial module for 4.7.0-1-amd64
Done.

spl:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.7.0-1-amd64/updates/dkms/

splat.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.7.0-1-amd64/updates/dkms/

depmod...

DKMS: install completed.

(Reading database ... 119131 files and directories currently installed.)
Preparing to unpack .../zfs-dkms_0.6.5.8-1_all.deb ...

------------------------------
Deleting module version: 0.6.5.8
completely from the DKMS tree.
------------------------------
Done.
Unpacking zfs-dkms (0.6.5.8-1) over (0.6.5.8-1) ...
Setting up zfs-dkms (0.6.5.8-1) ...
Loading new zfs-0.6.5.8 DKMS files...
Building for 4.4.0-1-amd64 and 4.7.0-1-amd64
Building initial module for 4.4.0-1-amd64
configure: error: 
        *** Please make sure the kmod spl devel <kernel> package for your
        *** distribution is installed then try again.  If that fails you
        *** can specify the location of the spl objects with the
        *** '--with-spl-obj=PATH' option.
Error! Bad return status for module build on kernel: 4.4.0-1-amd64 (x86_64)
Consult /var/lib/dkms/zfs/0.6.5.8/build/make.log for more information.

**Comment by jawi** [comment]
Also stumbled upon this error persistently on Debian Jessie. The cause of the problem is that the `spl-dkms` package does *not* copy the required `spl_config.h` and `Modules.symvers` files. There's a `POST_BUILD` step defined in the `dkms.conf` that does attempt to copy these files, but I think it is invoked too soon as the destination directory does not yet exist. 

Locally, I've solved it slightly differently by creating a configuration override for the `spl-dkms`: create a file named `/etc/dkms/spl.conf` with the following contents:

    POST_INSTALL="scripts/dkms.postbuild -a ${arch} -k ${kernelver} -v ${PACKAGE_VERSION} -n ${PACKAGE_NAME} -t ${dkms_tree}"

Now, a `dpkg-reconfigure spl-dkms` does copy the right files, which in its turn, causes `dpkg-reconfigure zfs-dkms` to complete successfully.

@ColinIanKing / @FransUrbo / @behlendorf : is any of you able to confirm this behaviour?

**Comment by helix84** [comment]
@jawi Thank you, that helped! :+1: (`vim /etc/dkms/spl.conf; dpkg-reconfigure spl-dkms; dkms autoinstall; modprobe zfs`)

I'm on Jessie. Your analysis seems right, here's what I had after doing `apt-get install zfs-dkms zfs-initramfs`:

Present: /usr/src/spl-0.6.5.8/spl_config.h.in
Not present: /var/lib/dkms/spl/0.6.5.8/3.16.0-4-amd64/x86_64/spl_config.h

````$ sudo dkms status
spl, 0.6.5.8, 3.16.0-4-amd64, x86_64: installed
zfs, 0.6.5.8: added
````

`dkms install zfs` was failing with
````
...
checking kernel file name for module symbols... Module.symvers
checking spl source directory... /usr/src/spl-0.6.5.8
checking spl build directory...
/var/lib/dkms/spl/0.6.5.8/3.16.0-4-amd64/x86_64
configure: error:
        *** Please make sure the kmod spl devel <kernel> package for your
        *** distribution is installed then try again.  If that fails you
        *** can specify the location of the spl objects with the
        *** '--with-spl-obj=PATH' option.
````

I think when I originally did `apt-get install zfs-dkms` on this machine, it just worked. Then I wanted to make sure I have zfs in initramfs and I couldn't get it to work after reboot - not sure if it was just due to dpkg-initramfs or there was a kernel upgrade and dkms failed to rebuild both modules correctly.

**Comment by sforshee** [comment]
Thanks. I had already started on the code fixes, but I my time to work on it has been limited. Will try to post an update soon.

**Comment by Hultner** [comment]
I've run into the same problem and have tried everything I can think of without getting it to work. The solution @jawi and then @helix84 recommends does not work as the `spl_config.h` and `Modules.symvers` doesn't exist for me.

My `dkms status` list looks like this
```sh
aufs, 4.14+20171218, 4.14.0-3-amd64, x86_64: installed
spl, 0.7.5, 4.13.0-1-amd64, x86_64: installed
spl, 0.7.5, 4.14.0-3-amd64, x86_64: installed
zfs, 0.6.5.9: added
```

And reinstalling spl with the conf gives the following
```
spl:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.14.0-3-amd64/updates/dkms/

splat.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.14.0-3-amd64/updates/dkms/

Running the post_install script:
cp: cannot stat '/var/lib/dkms/spl/0.7.5/build/spl_config.h': No such file or directory
cp: cannot stat '/var/lib/dkms/spl/0.7.5/build/module/Module.symvers': No such file or directory

depmod...

DKMS: install completed.
```

This is really quite cumbersome :/

**Comment by Hultner** [comment]
I changed my sources to buster so I could use zfs 0.7.5, now it seems to work as it should.
