### ISSUE TITLE
Cannot compile and install zfs & spl 0.6.3-1.2 on Debian Jessie

### ISSUE THREAD

**Issue by azeemism** [zfsonlinux/zfs#3067]
Below are the steps I followed and errors I received while trying to compile and install the latest stable releases.

https://github.com/zfsonlinux/zfs/releases
https://github.com/zfsonlinux/spl/releases

Debian Jessie install on VirtualBox:

Remove the existing module:

dkms remove -m zfs -v 0.6.3 --all
dkms remove -m spl -v 0.6.3 --all

Download and extract the files:

cd /usr/src
wget https://github.com/zfsonlinux/zfs/archive/zfs-0.6.3-1.2.tar.gz
wget https://github.com/zfsonlinux/spl/archive/spl-0.6.3-1.2.tar.gz
tar -zxvf zfs-0.6.3-1.2.tar.gz
tar -zxvf spl-0.6.3-1.2.tar.gz

Rename the directories:

mv zfs-zfs-0.6.3-1.2 zfs-0.6.3-1.2
mv spl-spl-0.6.3-1.2 spl-0.6.3-1.2

Open the SPL directory:
cd /usr/src/spl-0.6.3-1.2

Create the configure script:
./autogen.sh

Error Image 1:

![compile-01](https://cloud.githubusercontent.com/assets/10731034/5995885/128f0c10-aa52-11e4-952c-2d356bcad197.png)

Run the configure script:
./configure --prefix=/usr

make

make install

Error Image 2:

![compile-02](https://cloud.githubusercontent.com/assets/10731034/5995891/293b676a-aa52-11e4-835f-eb75c0c3922e.png)

List of directory contents:

ls -l /lib/modules/3.16.0-4-amd64

![compile-03](https://cloud.githubusercontent.com/assets/10731034/5995893/3facfe64-aa52-11e4-8e02-c54cf498edfe.png)

Open the ZFS directory:
cd /usr/src/zfs-0.6.3-1.2

Create the configure script:
./autogen.sh

Error Image 3:

![compile-04](https://cloud.githubusercontent.com/assets/10731034/5995904/633cf820-aa52-11e4-88b7-1f2b040eabf8.png)

Run the configure script:
./configure /usr/src/spl-0.6.3-1.2 --prefix=/usr

Error Image 4:

![compile-05](https://cloud.githubusercontent.com/assets/10731034/5995908/817ace34-aa52-11e4-8371-0c56b95359f8.png)

Due to the previous command not completing, the following commands were not run:

make

make install

Start the newly compiled ZFS kernel module:

modprobe zfs

*** 

Since the above steps were not working, I later tried to copy over the previous versions dkms.conf files to the respective "-1.2"  directories and modified the versions line in both files, but was not successful when executing

dkms add -m spl -v 0.6.3-1.2
dkms add -m zfs -v 0.6.3-1.2

dkms build -m spl -v 0.6.3-1.2
dkms build -m zfs -v 0.6.3-1.2

dkms install -m spl -v 0.6.3-1.2
dkms install -m zfs -v 0.6.3-1.2

I cannot remember the specific error. I would have to test again. But since there was no dkms file to begin with, I expect the steps outlined in the previous section are what I should be following.

***

Sources:
http://www.graymatterboundaries.com/?p=496
http://zfsonlinux.org/generic-deb.html

Required packages (for the sources listed) were installed in advance.

Thanks in advance,

Azeem

**Comment by FransUrbo** [comment]
> Run the configure script:
> 
> ./configure /usr/src/spl-0.6.3-1.2 --prefix=/usr
> 
That would be

	./configure --with-spl=/usr/src/spl-0.6.3-1.2 --with-spl-obj=/usr/src/spl-0.6.3-1.2 --prefix

After that run

	make deb

and you'll get deb packages for all libraries and utilities. AND also the modules! No need for the dkms crap…

**Comment by azeemism** [comment]
@FransUrbo your suggestion helped move things forward, but they are still errors though the compile/install. Hopefully it is something that I am doing wrong. My last try at it went as follows:

***

Uninstall (0.6.3)

spool export spool

apt-get remove --purge debian-zfs

apt-get remove --purge libnvpair1 libuutil1 libzfs2 libzpool2 spl zfsutils dkms spl-dkms zfs-dkms zfs-initramfs zfsonlinux

Comment out all lines / remove  /etc/apt/sources.list.d/zfsonlinux.list

# I assume the above dependence are not required for the compile/install?

***

Install dependencies for the compile:

apt-get install git autoconf libtool
apt-get install build-essential gawk alien fakeroot linux-headers-$(uname -r)
apt-get install zlib1g-dev uuid-dev libblkid-dev libselinux1-dev parted lsscsi wget

***

Uncompress 0.6.3-1.2 to the respective directories

wget https://github.com/zfsonlinux/zfs/archive/zfs-0.6.3-1.2.tar.gz
wget https://github.com/zfsonlinux/spl/archive/spl-0.6.3-1.2.tar.gz

/root/zol/0.6.3-1.2/spl
/root/zol/0.6.3-1.2/zfs

***

Manually type in the following commit:
Illumos 4924 - LZ4 Compression for metadata #2807 
https://github.com/zfsonlinux/zfs/pull/2807
https://github.com/zfsonlinux/zfs/commit/62bdd5eb7a35288cc25c5ae968bcd0f08889f986

***

SPL Compile/Install:

cd /root/zol/0.6.3-1.2/spl
./autogen.sh

configure.ac:35 warning AM_INIT_AUTOMAKE: two- and three-arguments forms are depricated. For more inof, see:
configure.ac:35: http//....<see image in top post>

# Can the above warning be safely ignored?

***

./configure --with-linux=/usr/src/linux-headers-3.16.0-4-amd64 --prefix=/usr
make deb
dpkg -i -R *.deb

***

If 'make' is used in place of 'make deb' a number of errors appear, and I am not sure why they would appear, and whether the same errors will plague the .deb files?  ...especially since 'make' and 'make install' should also work.

# Can the 'make' errors be safely ignored?

![compile-v2-1](https://cloud.githubusercontent.com/assets/10731034/6015016/beb0db82-ab23-11e4-8da1-5a0625002b64.png)

***

ZFS Compile/Install:

cd /root/zol/0.6.3-1.2/zfs
./autogen.sh

...
lib/libzpool/Makefile.am:11: warning: source file '$(top-srcdir)/module/zfs/...' is in a subdirectory,\
lib/libzpool/Makefile.am:11: but option 'subdir-objects' is disabled
... 
(same as image in top post)

Adding "AUTOMAKE_OPTIONS = subdir-objects" to bottom of Makefile.am file did not fix this warning. 

# Can the ''subdir-objects' is disabled' warning be safely ignored?

***

./configure --with-spl=/root/zol/0.6.3-1.2/spl --with-spl-obj=/root/zol/0.6.3-1.2/spl --with-linux=/usr/src/linux-headers-3.16.0-4-amd64 --prefix=/usr

make deb

Image of 'make deb' errors:

![compile-v2-2](https://cloud.githubusercontent.com/assets/10731034/6015139/c6046942-ab25-11e4-9d84-bc86eab8a5fe.png)
age of 'make deb' errors

# No .deb files were created. Not sure how to proceed?

I had already used ' --with-linux=/usr/src/linux-headers-3.16.0-4-amd64'

Module.symvers was located in 
/usr/src/spl-0.6.3/3.16.0-4-amd64/
/usr/src/linux-headers-3.16.0-4-amd64/

***

When 'make' is used the following errors occur:

![compile-v2-3](https://cloud.githubusercontent.com/assets/10731034/6015577/f908cdf6-ab2a-11e4-8ccd-f1aff91e1147.png)

The patch that I manually typed in looks to be exactly as the commit:
https://github.com/zfsonlinux/zfs/commit/62bdd5eb7a35288cc25c5ae968bcd0f08889f986

dmu.c file I typed in:

![compile-v2-4](https://cloud.githubusercontent.com/assets/10731034/6015579/00c11076-ab2b-11e4-982d-ccc6d6231b1e.png)

![compile-v2-5](https://cloud.githubusercontent.com/assets/10731034/6015580/048ca33c-ab2b-11e4-94cb-d28019a33563.png)

# Are they typos in the commit, not sure what it should look like?

# Not sure why they are other error as well?

This is giving me heart burn. I don't understand why the steps I am following are not working.

**Comment by azeemism** [comment]
If I am running on a native zfs root filesystem, will it even be possible to compile and install/reinstall the files and modules when the next stable or 0.6.4 is released?

Would this be a possible item of concern as well, with the regular install, I assume through dkms?

**Comment by FransUrbo** [comment]
> apt-get remove --purge debian-zfs
> 
> apt-get remove --purge libnvpair1 libuutil1 libzfs2 libzpool2 spl zfsutils dkms spl-dkms zfs-dkms zfs-initramfs zfsonlinux
> 
> Comment out all lines / remove /etc/apt/sources.list.d/zfsonlinux.list
> 
> I assume the above dependence are not required for the compile/install?
> 
They are not. You're creating new debs later.
> Manually type in the following commit:
> Illumos 4924 - LZ4 Compression for metadata #2807 
> #2807
> 62bdd5e
> 
That's one way to do it. I would rather use the GIT version, that way you can apply patches (pull requests) easier:

	git clone https://github.com/zfsonlinux/zfs.git
	git clone https://github.com/zfsonlinux/zfs.git
	cd zfs
	[follow https://gist.github.com/piscisaureus/3342247]
	git fetch -a
	[get tags with "git tag -l"]
	git checkout -b zfs-0.6.3-1.2 zfs-0.6.3-1.2
	git merge origin/pr/2807
	[repeat for any other PR you want]
> configure.ac:35 warning AM_INIT_AUTOMAKE: two- and three-arguments forms are depricated. For more inof, see: configure.ac:35: http//....
> 
> Can the above warning be safely ignored?
> 
Yes.
> ./configure --with-linux=/usr/src/linux-headers-3.16.0-4-amd64 --prefix=/usr
> 
Safe command line, but if you only have one kernel/kernel source installed you don't need the '--with-linux' option… Otherwise, it will most likely also need '--with-linux-obj'.
> make deb
> 
For spl, you also need to run 'make' (without options). This so that the later build of zfs will find the object files (which it won't if only 'make deb' is create - nothing is built inside the spl source directory).
> Can the 'make' errors be safely ignored?
> 
No, because any error will make the make process halt. If you get this when only running 'make' but not when running 'make deb', you need to take very, very close note of what's happening during the configure stage. Something is missing/wrong…
> lib/libzpool/Makefile.am:11: warning: source file '$(top-srcdir)/module/zfs/...' is in a subdirectory,\
> lib/libzpool/Makefile.am:11: but option 'subdir-objects' is disabled
> ... 
> (same as image in top post)
> 
> Adding "AUTOMAKE_OPTIONS = subdir-objects" to bottom of Makefile.am file did not fix this warning.
> 
> Can the ''subdir-objects' is disabled' warning be safely ignored?
> 
They should be safe. Although I/we need to figure out what's causing them…
> ./configure --with-spl=/root/zol/0.6.3-1.2/spl --with-spl-obj=/root/zol/0.6.3-1.2/spl --with-linux=/usr/src/linux-headers-3.16.0-4-amd64 --prefix=/usr
> 
You're adding an extra level of directory here' Remove the last part (the '/spl' part). BUT you must have run simple 'make' in there first...
> I had already used ' --with-linux=/usr/src/linux-headers-3.16.0-4-amd64'
> 
> Module.symvers was located in 
> /usr/src/spl-0.6.3/3.16.0-4-amd64/
> /usr/src/linux-headers-3.16.0-4-amd64/
> 
As said above, if you only have one kernel, you don't need the '--with-linux' option. But it can also bee that you're missing the '--with-linux-obj' option. Which then should be

	--with-linux=/usr/src/linux-headers-3.16.0-4-common --with-linux-obj=/usr/src/linux-headers-3.16.0-4-amd64
> When 'make' is used the following errors occur:
> 
> 
> 
Looks like you're missing a PR dependency. It seems that it's not only needs #2807, but something else to… OR that when you applied it, you missed something or it wasn't applied clean.




I'm very happy that you want to do this yourself, but this is now outside the scope of this issue! I would like to ask you to take this to the mailing list instead, the issue tracker is NOT a support forum.

I would also like to ask you to close this issue, and continue it on the mailing list which is a better and more appropriate forum for this problem. IF (when?) we can actually see a problem/issue, you will be recommended to take it back to the issue tracker with a new issue.

Or a quicker way would be to use the IRC channel.=

**Comment by FransUrbo** [comment]
> If I am running on a native zfs root filesystem, will it even be possible to compile and install/reinstall the files and modules when the next stable or 0.6.4 is released?
> 
> Would this be a possible item of concern as well, with the regular install, I assume through dkms?
> 
Running a zfs root is/will always (?) be an issue. It's _very_ important to think before rebooting (understanding the full process helps).

But if you run from git, then you won't be using dkms. The 'make deb' will create a kmod-zfs-<kernel_version>_<zfs_version>_<arch>.deb for you (such as kmod-zfs-3.16.0-4_0.6.3_amd64.deb). You will also have to recreate your initrd manually (usually, dkms is doing this for you, but it have so many other problems, it's worth ditching).=

**Comment by azeemism** [comment]
@FransUrbo Thanks. I appreciate you sharing your incite. You are a very helpful person. Will do as you suggested.
