### ISSUE TITLE
Problem with ZFS after HDD controller crash

### ISSUE THREAD

**Issue by aloofness** [zfsonlinux/zfs#3068]
Hi everyone,

Two weeks ago the HDD controller on my server crashed. On the HDD I had a ZFS partition. 

Now I am trying to import the ZFS disk on the new server but ...

I tryed following:

root@backup:~# zpool import
   pool: disk1
     id: 2229110754804667287
  state: UNAVAIL
 status: The pool was last accessed by another system.
 action: The pool cannot be imported due to damaged devices or data.
   see: http://zfsonlinux.org/msg/ZFS-8000-EY
 config:
        disk1       UNAVAIL  unsupported feature(s)
          loop0p1   ONLINE

root@backup:~# zpool import disk1
cannot import 'disk1': pool may be in use from other system, it was last accessed by beertime (hostid: 0x175e85a8) on Sun Jan 18 04:09:36 2015
use '-f' to import anyway

root@backup:~# zpool import disk1 -f
This pool uses the following feature(s) not supported by this system:
        com.delphix:hole_birth
        com.delphix:embedded_data
cannot import 'disk1': unsupported version or feature

And this is ZFS I am using:
root@backup:~# dmesg | grep -E 'SPL:|ZFS:'
[   45.845503] SPL: Loaded module v0.6.3-295_ga9d5f15
[   45.940510] ZFS: Loaded module v0.6.3-763_ge883253, ZFS pool version 5000, ZFS filesystem version 5
[  464.600089] SPL: using hostid 0x007f0101

Does anybody knows, if it is a bug or a problem that can be easily resolved? Or I have a corupted ZFS volume?

Thanks for everything, by the way :-)

**Comment by nicko88** [comment]
Looks like you are trying to import the pool on an older build of ZoL which doesn't have those feature flags available.  You will need to upgrade your ZoL to a build that supports them.

**Comment by behlendorf** [comment]
Right, you'll need to either use the current ZoL master branch to import this pool or wait for the 0.6.4 release which is the first tag to support those features.
