### ISSUE TITLE
CENTOS 7 - ZFS send causes panic

### ISSUE THREAD

**Issue by greg-hydrogen** [zfsonlinux/zfs#3069]
Hello Everyone,

I am able to consittently reproduce the following crash in a VM when performing a zfs send.  This happens with the latest kernel and master as well as an older git master  (6 months)

I have the vmcore if there is useful information that can be pulled from that

Thanks,
Greg

[ 1442.700975] CPU: 0 PID: 115 Comm: spl_system_task Tainted: PF          O--------------   3.10.0-123.20.1.el7.x86_64 #1
[ 1442.701035] Hardware name: VMware, Inc. VMware Virtual Platform/440BX Desktop Reference Platform, BIOS 6.00 07/30/2013
[ 1442.701089] task: ffff8800369f8b60 ti: ffff8800369f4000 task.ti: ffff8800369f4000
[ 1442.701128] RIP: 0010:[<ffffffffa00b97f5>]  [<ffffffffa00b97f5>] arc_buf_remove_ref+0x15/0x110 [zfs]
[ 1442.701198] RSP: 0018:ffff8800369f56d8  EFLAGS: 00010246
[ 1442.701226] RAX: 0000000000000000 RBX: 0000000000000000 RCX: 0000000000000000
[ 1442.701262] RDX: 0000000000000034 RSI: ffff8800369f5810 RDI: 0000000000000000
[ 1442.701300] RBP: ffff8800369f56f8 R08: 0000000000000000 R09: 0000000000000000
[ 1442.701336] R10: 0000000000000004 R11: 0000000000000005 R12: 0000000000000000
[ 1442.701375] R13: 0000000000000000 R14: ffffffffa00b98f0 R15: 0000000000000000
[ 1442.701414] FS:  00007f749b7ba740(0000) GS:ffff88013fc00000(0000) knlGS:0000000000000000
[ 1442.701457] CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
[ 1442.701488] CR2: 0000000000000048 CR3: 00000000adaa0000 CR4: 00000000000407f0
[ 1442.701572] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[ 1442.701617] DR3: 0000000000000000 DR6: 00000000ffff0ff0 DR7: 0000000000000400
[ 1442.701657] Stack:
[ 1442.701672]  ffff8800369f5810 ffff880055373740 0000000000000000 ffffffffa00b98f0
[ 1442.701724]  ffff8800369f5710 ffffffffa00b9923 0000000000000034 ffff8800369f57c0
[ 1442.701767]  ffffffffa00b9bfd 0000000000000000 0000000000000000 000000003f86e893
[ 1442.701812] Call Trace:
[ 1442.701849]  [<ffffffffa00b98f0>] ? arc_buf_remove_ref+0x110/0x110 [zfs]
[ 1442.701904]  [<ffffffffa00b9923>] arc_getbuf_func+0x33/0x70 [zfs]
[ 1442.701953]  [<ffffffffa00b9bfd>] arc_read+0x29d/0xa60 [zfs]
[ 1442.701999]  [<ffffffffa00b98f0>] ? arc_buf_remove_ref+0x110/0x110 [zfs]
[ 1442.702053]  [<ffffffffa00d52f1>] traverse_visitbp+0x151/0x7f0 [zfs]
[ 1442.702108]  [<ffffffffa00d60fd>] traverse_dnode+0xbd/0xf0 [zfs]
[ 1442.702163]  [<ffffffffa00d57f3>] traverse_visitbp+0x653/0x7f0 [zfs]
[ 1442.702217]  [<ffffffffa00d53f5>] traverse_visitbp+0x255/0x7f0 [zfs]
[ 1442.702270]  [<ffffffffa00d53f5>] traverse_visitbp+0x255/0x7f0 [zfs]
[ 1442.702324]  [<ffffffffa00d53f5>] traverse_visitbp+0x255/0x7f0 [zfs]
[ 1442.702380]  [<ffffffffa00d53f5>] traverse_visitbp+0x255/0x7f0 [zfs]
[ 1442.702434]  [<ffffffffa00d53f5>] traverse_visitbp+0x255/0x7f0 [zfs]
[ 1442.702488]  [<ffffffffa00d53f5>] traverse_visitbp+0x255/0x7f0 [zfs]
[ 1442.702545]  [<ffffffffa00d60c5>] traverse_dnode+0x85/0xf0 [zfs]
[ 1442.702598]  [<ffffffffa00d58a6>] traverse_visitbp+0x706/0x7f0 [zfs]
[ 1442.702677]  [<ffffffff8101a679>] ? sched_clock+0x9/0x10
[ 1442.703977]  [<ffffffff8109a045>] ? sched_clock_cpu+0xb5/0x100
[ 1442.705237]  [<ffffffffa00d5fda>] traverse_prefetch_thread+0x9a/0x100 [zfs]
[ 1442.706535]  [<ffffffffa00d5070>] ? prefetch_needed.isra.2+0x40/0x40 [zfs]
[ 1442.707763]  [<ffffffffa000d73e>] taskq_thread+0x1be/0x360 [spl]
[ 1442.708975]  [<ffffffff810977e0>] ? wake_up_state+0x20/0x20
[ 1442.710210]  [<ffffffffa000d580>] ? taskq_cancel_id+0x140/0x140 [spl]
[ 1442.711389]  [<ffffffff81085aff>] kthread+0xcf/0xe0
[ 1442.712573]  [<ffffffff81085a30>] ? kthread_create_on_node+0x140/0x140
[ 1442.713774]  [<ffffffff815f316c>] ret_from_fork+0x7c/0xb0
[ 1442.714910]  [<ffffffff81085a30>] ? kthread_create_on_node+0x140/0x140
[ 1442.715955] Code: 31 f6 48 89 df e8 cc c2 ff ff e9 68 ff ff ff 0f 1f 80 00 00 00 00 66 66 66 66 90 55 48 89 e5 41 56 41 55 41 54 49 89 fc 53 31 db <48> 83 7f 48 00 48 8b 07 48 8b 3d a4 7a 16 00 0f 94 c3 48 39 b8 
[ 1442.718198] RIP  [<ffffffffa00b97f5>] arc_buf_remove_ref+0x15/0x110 [zfs]
[ 1442.719293]  RSP <ffff8800369f56d8>
[ 1442.720314] CR2: 0000000000000048

**Comment by behlendorf** [comment]
Can you include a simple test case or the command you're running so we can try and reproduce when someone has time to work on it.

**Comment by gmelikov** [comment]
Closing as stale.
