### ISSUE TITLE
0.6.4 Target date

### ISSUE THREAD

**Issue by tsykes** [zfsonlinux/zfs#3073]
Is there a target date for the next release? I'm having issues with zfs on CentOS 7. I tried the testing repository and it resolved my issues. I'm wondering if I should wait for the 0.6.4 release or back off CentOS 7 for now.

**Comment by behlendorf** [comment]
When the remaining milestones in https://github.com/zfsonlinux/zfs/milestones/0.6.4 are resolved.  In the interests of speeding up an 0.6.4 release I'm bumping the non-critical items to 0.6.5.
