### ISSUE TITLE
Add split documentation packages for zfs, zpool commands

### ISSUE THREAD

**Issue by wrouesnel** [zfsonlinux/zfs#3086]
Currently the only way to get documentation on the zfs, zpool "swiss-army knife" commands is from a single, very long man page. This makes quickly referring to command parameters in the console difficult since you have to scroll an unordered list to find them.

It would be good to, in addition to the "compendium" man pages for these commands, install a set of zfs-\* zpool-\* commands which contained only documentation for the specific subcommand being referred to. An example would be how the git man pages are structured.

**Comment by behlendorf** [comment]
That sounds like an excellent suggestion to me.  Personally, I really like the way the git man pages are laid out.  I also like how you can use the `--help` long option to pull up the correct man page.  For example, `git --help checkout`.  My only concern is that we should do this in addition to the existing man pages to make it fairly easy to pull in updates from other platforms.

**Comment by jas14** [comment]
@Ericson2314: you did this for illumos right? do you think the script would be applicable here?

**Comment by Ericson2314** [comment]
For zpool yes, with @lukenels

**Comment by jgottula** [comment]
I noticed that this is still an open issue, despite #9559 and #9564 having been merged.

Presumably this issue should be marked as done/accepted now?

**Comment by behlendorf** [comment]
@jgottula yes, thank you for pointing this out.  Closed.
