### ISSUE TITLE
no blkid output for cache device

### ISSUE THREAD

**Issue by dsockwell** [zfsonlinux/zfs#3092]
This issue is a follow-up to a question I asked on IRC. I have a cache device that isn't recognized by 'blkid' for some reason, and it's causing me some grief wrt encryption. I can imagine there are other consequences also. Should blkid be recognizing cache devices as zfs_member ? Can I fake it without modifying blkid or libblkid?

10:35:18    dsockwell | i have a root pool on top of LUKS with cache and slog devices. Debian's cryptroot
                      | uses 'blkid' to verify a good decryption, and my cache devices always fail to
                      | decrypt on startup. I tried getting some blkid output on a decrypted cache device
                      | and nothing came back. Is this a bug? Can I fake the blkid output for cryptroot?
                      | http://pastebin.com/0LNBLDKz

```
root@elrucio:/etc/zfs# zpool status -v
  pool: rpool
 state: ONLINE
  scan: scrub repaired 0 in 4h13m with 0 errors on Fri Jan 23 15:57:30 2015
config:

        NAME                                                                STATE     READ WRITE CKSUM
        rpool                                                               ONLINE       0     0     0
          mirror-0                                                          ONLINE       0     0     0
            dm-name-ata-HGST_HDN724030ALE640_PK2234P8JYTYNY_crypt           ONLINE       0     0     0
            dm-name-ata-ST3000DM001-1CH166_W1F3SNCL_crypt                   ONLINE       0     0     0
          mirror-1                                                          ONLINE       0     0     0
            dm-name-ata-HGST_HDN724030ALE640_PK2234P8JVBZMY_crypt           ONLINE       0     0     0
            dm-name-ata-ST3000DM001-1CH166_W1F3V9H7_crypt                   ONLINE       0     0     0
        logs
          mirror-2                                                          ONLINE       0     0     0
            dm-name-ata-INTEL_SSDSC2BW120A4_CVDA343401FZ1207GN-part2_crypt  ONLINE       0     0     0
            dm-name-ata-INTEL_SSDSC2BW120A4_CVDA343002UH1207GN-part2_crypt  ONLINE       0     0     0
        cache
          dm-name-ata-INTEL_SSDSC2BW120A4_CVDA343401FZ1207GN-part3_crypt    ONLINE       0     0     0
          dm-name-ata-INTEL_SSDSC2BW120A4_CVDA343002UH1207GN-part3_crypt    ONLINE       0     0     0

errors: No known data errors

root@elrucio:/etc/zfs# /sbin/blkid -s TYPE -o value /dev/disk/by-id/dm-uuid-CRYPT-LUKS1-3303da4e0dd74d8696efe53bc7612136-ata-ST3000DM001-1CH166_W1F3SNCL_crypt
zfs_member

root@elrucio:/etc/zfs# /sbin/blkid /dev/disk/by-id/dm-uuid-CRYPT-LUKS1-3303da4e0dd74d8696efe53bc7612136-ata-ST3000DM001-1CH166_W1F3SNCL_crypt
/dev/disk/by-id/dm-uuid-CRYPT-LUKS1-3303da4e0dd74d8696efe53bc7612136-ata-ST3000DM001-1CH166_W1F3SNCL_crypt: LABEL="rpool" UUID="9651825162987964560" UUID_SUB="17754604583346869478" TYPE="zfs_member"

root@elrucio:/etc/zfs# /sbin/blkid /dev/disk/by-id/dm-uuid-CRYPT-LUKS1-e07706434dab43c3b224a7de5f2e0bdf-ata-INTEL_SSDSC2BW120A4_CVDA343002UH1207GN-part3_crypt

# No output; device is a cache device though.

root@elrucio:/etc/zfs#
```

**Comment by dsockwell** [comment]
I think I found the code that is performing the detection here - https://github.com/karelzak/util-linux/blob/master/libblkid/src/superblocks/zfs.c

**Comment by behlendorf** [comment]
@dsockwell yes you're definitely looking the right area.  I think the key bit of information you need to know is that the ZFS label written to an L2ARC device isn't complete.  Specifically, it doesn't contain any uberblocks like the labels on the primary pool devices.  This almost certainly why blkid fails to detect the device, it looks for this uberblock signature.  I think it would be great if we could improve the ZFS signature detection code in blkid.

**Comment by dsockwell** [comment]
Yes, the uberblock test would fail first, but there is one uberblock tag per label on a cache vdev.

```
0020000: 0cb1 ba00 0000 0000 8813 0000 0000 0000  ................
```

yes, it kind of reads 'ooba b1oc'. there's also a 'da7a b1oc':

```
001ffd0: 0000 0000 0000 0000 117a 0cb1 7ada 1002  .........z..z...
```

blkid can then know the difference - a cache vdev's label has one uberblock with txg 0 and a real date for a timestamp. For confirmation, blkid can check one or more of the other three labels, whose uberblock should be identical (check guid_sum and timestamp). There are also some nvpair entries (version, state, guid).

I've done some hex dumps of a newly-zero'd device labeled as cache.

the first 256K (should be one label) http://sprunge.us/SHaE
the first 512K (should be two labels) http://sprunge.us/GKbd

I've also added some output from 'zdb -l -u <device>':

A cache vdev: http://sprunge.us/cNdZ 
A mirror vdev: http://sprunge.us/KfDg 

And here's a convenient link to the zfs on-disk specification, http://www.giis.co.in/Zfs_ondiskformat.pdf

**Comment by dsockwell** [comment]
Workaround - This may possibly be unsafe or unstable, I won't know for some days. This is to solve my immediate difficulty with booting. Yes, I'm probably crazy to do this. I'd be thrilled for someone to tell me why, though.

1. attach the cache device to the zpool
2. create a disk image and format it ext2
3. write the first 4096 bytes (this is half of the 8k buffer zone in the zfs label spec) to the cache device while it's attached to the zpool.
4. observe 'blkid' output. remember the -p switch. It looks a lot better than it did.
5. observe the cache device is still ONLINE in 'zpool status -v'. I sure hope that 4k wasn't important.

```
root@elrucio:~/stupid-sysadmin-tricks/blkid-bug# mkfs.ext2 ./ext2fs.img
mke2fs 1.42.5 (29-Jul-2012)
./ext2fs.img is not a block special device.
Proceed anyway? (y,n) y
Discarding device blocks: done
Filesystem label=
OS type: Linux
Block size=1024 (log=0)
Fragment size=1024 (log=0)
Stride=0 blocks, Stripe width=0 blocks
16384 inodes, 65536 blocks
3276 blocks (5.00%) reserved for the super user
First data block=1
Maximum filesystem blocks=67108864
8 block groups
8192 blocks per group, 8192 fragments per group
2048 inodes per group
Superblock backups stored on blocks:
        8193, 24577, 40961, 57345

Allocating group tables: done
Writing inode tables: done
Writing superblocks and filesystem accounting information: done
```

```
root@elrucio:~/stupid-sysadmin-tricks/blkid-bug# dd if=./ext2fs.img of=/dev/disk/by-id/dm-name-ata-INTEL_SSDSC2BW120A4_CVDA343401FZ1207GN-part3_crypt bs=4096 count=1
1+0 records in
1+0 records out
4096 bytes (4.1 kB) copied, 3.7071e-05 s, 110 MB/s
```

```
root@elrucio:~/stupid-sysadmin-tricks/blkid-bug# blkid -p /dev/disk/by-id/dm-name-ata-INTEL_SSDSC2BW120A4_CVDA343401FZ1207GN-part3_crypt
/dev/disk/by-id/dm-name-ata-INTEL_SSDSC2BW120A4_CVDA343401FZ1207GN-part3_crypt: UUID="85670ef8-57ee-4b9c-b8bd-4dbbf970f34e" VERSION="1.0" TYPE="ext2" USAGE="filesystem"
```

```
root@elrucio:~/stupid-sysadmin-tricks/blkid-bug# zpool status -v
  pool: rpool
 state: ONLINE
  scan: scrub repaired 0 in 4h13m with 0 errors on Fri Jan 23 15:57:30 2015
config:

        NAME                                                                STATE     READ WRITE CKSUM
        rpool                                                               ONLINE       0     0     0
          mirror-0                                                          ONLINE       0     0     0
            dm-name-ata-HGST_HDN724030ALE640_PK2234P8JYTYNY_crypt           ONLINE       0     0     0
            dm-name-ata-ST3000DM001-1CH166_W1F3SNCL_crypt                   ONLINE       0     0     0
          mirror-1                                                          ONLINE       0     0     0
            dm-name-ata-HGST_HDN724030ALE640_PK2234P8JVBZMY_crypt           ONLINE       0     0     0
            dm-name-ata-ST3000DM001-1CH166_W1F3V9H7_crypt                   ONLINE       0     0     0
        logs
          mirror-2                                                          ONLINE       0     0     0
            dm-name-ata-INTEL_SSDSC2BW120A4_CVDA343401FZ1207GN-part2_crypt  ONLINE       0     0     0
            dm-name-ata-INTEL_SSDSC2BW120A4_CVDA343002UH1207GN-part2_crypt  ONLINE       0     0     0
        cache
          dm-name-ata-INTEL_SSDSC2BW120A4_CVDA343002UH1207GN-part3_crypt    ONLINE       0     0     0
          dm-name-ata-INTEL_SSDSC2BW120A4_CVDA343401FZ1207GN-part3_crypt    ONLINE       0     0     0

errors: No known data errors
root@elrucio:~/stupid-sysadmin-tricks/blkid-bug#
```

**Comment by dsockwell** [comment]
It's been almost a week and the label hasn't been touched.

```
root@elrucio:~/stupid-sysadmin-tricks/blkid-bug# blkid -p /dev/disk/by-id/dm-name-ata-INTEL_SSDSC2BW120A4_CVDA343002UH1207GN-part3_crypt
/dev/disk/by-id/dm-name-ata-INTEL_SSDSC2BW120A4_CVDA343002UH1207GN-part3_crypt: UUID="85670ef8-57ee-4b9c-b8bd-4dbbf970f34e" VERSION="1.0" TYPE="ext2" USAGE="filesystem"
```

**Comment by mihu** [comment]
@behlendorf I've got similar situation. Reading the code of libblkid it seems that current implementation only inspects first two labels and tries to found four uberblocks. In my case this fails, because I have one uberblock per label (it's a newly added cache device). I've tried to fix it (at least for me). Here is the version of code, which works for me https://gist.github.com/mihu/c144687d718d7b6f6c0d. If think it's ok, I will try to push to util-linux upstream.

**Comment by behlendorf** [comment]
@mihu this looks pretty reasonable to me.  It assumes the smallest uberblock size and verifies it can locate at least 4 of them in the labels.  It would be great if you could push this upstream to util-linux.

**Comment by dsockwell** [comment]
@mihu I propose some expanded inline documentation, since util-linux might appreciate being walked through the on-disk format more explicitly. https://gist.github.com/dsockwell/cc067bd917bf86779d1a

Also, is zfs_extract_guid_name(blkid_probe pr, loff_t offset) allowed to fail or yield an ugly struct in this context? because it's looking for some name-value pairs (name and pool_guid) that don't exist in cache vdevs.

```
--------------------------------------------
LABEL 0
--------------------------------------------
    version: 5000
    state: 4
    guid: 16659112550915347596
Uberblock[0]
	magic = 0000000000bab10c
	version = 5000
	txg = 0
	guid_sum = 11278191410931990941
	timestamp = 1423588768 UTC = Tue Feb 10 10:19:28 2015
```

**Comment by mihu** [comment]
Seems that util-linux has official repository even here on github, so I've taken the shortcut:)
https://github.com/karelzak/util-linux/pull/155
