### ISSUE TITLE
zfs unmount very slow, txg_sync taking 90% CPU

### ISSUE THREAD

**Issue by lintonv** [zfsonlinux/zfs#3095]
Following setup:

Kernel : 2.6.32-279
Distro : CentOS-6.3
RAM: 32 GB

Test : Run IO on 50 ZFS filesystems. While running IO, bring down the system gracefully by first running "zfs unmount -a"

Observation : The unmount takes a long time to complete. From the 'top' output in CentOS, the entire time txg_sync appears to take most of the CPU. That could be a hint as to what is going on

**Comment by behlendorf** [comment]
@lintonv a few questions.

* What kind of IO?  Reads, writes, creates, unlinks?
* What version of ZFS?
* How slow?  The umounts are serialized by `zfs unmount -a` and each unmount must block waiting for it's dirty data to be written to disk.
* Try running `perf top` while txg_sync is taking most of the CPU to see what it's doing.

**Comment by lintonv** [comment]
@behlendorf 

1. IO was mostly random 8k (we have also seen similar delays, when the system crashes and zfs mount takes a long time. At the time of the crash, IO was going on)
2. Original version of ZFS 0.6.3 (July 2014) + patch for "mutex: force serialization on mutex_exit() to fix races"(https://github.com/zfsonlinux/spl/commit/a3c1eb7)
3. The time varies between 4 mins and 30 mins with the latter the case when performing 'zfs mount -a' after a crash
4. I will take a look at 'perf top'
