### ISSUE TITLE
undefined symbol get_system_hostid

### ISSUE THREAD

**Issue by odoucet** [zfsonlinux/zfs#3097]
Versions : 
SPL: Loaded module v0.6.3-71_g086476f
ZFS: Loaded module v0.6.3-207_gafe3732, ZFS pool version 5000, ZFS filesystem version 5
Kernel: 3.10.62-1.el6.elrepo.x86_64
CentOS 6.5

Command "zpool status" returned the following: 
zpool: symbol lookup error: /lib64/libzfs.so.2: undefined symbol: get_system_hostid

"zpool list" and "zfs list" are working correctly

**Comment by behlendorf** [comment]
@odoucet ensure you've updated libzpool library on your system.  This symbol was added.

**Comment by odoucet** [comment]
libzpool2 was not up to date, problem resolved. thank you
