### ISSUE TITLE
Feature: new dataset flag 'chroot' - don't mount sub-datasets automatically

### ISSUE THREAD

**Issue by prometheanfire** [zfsonlinux/zfs#3098]
This once flipped on a dataset it would not automount sub datasets.  This could be useful in at least two scenarios, containers and backups.

```
ZPOOL/containers/foo         mountpoint=/    chroot=true
ZPOOL/OS/rootfs              mountpoint=/    chroot=false
ZPOOL/remote-backups/foo     mountpoint=/    chroot=true
```

This would only mount `ZPOOL/OS/rootfs` on boot.

In addition it would help if we could (un)set this flag on sends/recvs so we could add/remove it on backup/restore.

**Comment by kpande** [comment]
does `canmount=noauto` not satisfy that request?

**Comment by prometheanfire** [comment]
Ya, that's what I'm using now (for sends).

`zfs recv -uvs -o canmount=off ZPOOL/remote-backups/${SNAPSHOT}"`

**Comment by kpande** [comment]
right, `recv -o` didn't exist back then. thanks.
