### ISSUE TITLE
zfs hangs with dedup

### ISSUE THREAD

**Issue by albionxyz** [zfsonlinux/zfs#3101]
Since I have enabled deduplication zfs hangs every few minutes. (During zpool import, or reproduceably during copying to zvol.)
I am booting xen 4.3.

Please let me know which logs you need.

**Comment by albionxyz** [comment]
It might be related to  #3091

**Comment by albionxyz** [comment]
The whole system hangs for 5sec-1min every few minutes too and suddenly recovers then too. I am not sure whether it is the same issue or another.

**Comment by albionxyz** [comment]
iotop shows 99.9% usage:

![z_rd_iss](https://cloud.githubusercontent.com/assets/3390179/6185600/b4c4a19e-b370-11e4-9ade-8469b7be95da.png)

**Comment by albionxyz** [comment]
With one pool it is particularly bad. Importing takes 5 minutes which used less than 10 seconds (95% of the time it is just hanging).

zfs send | zfs receive hangs also most of the time: With zfs list is see the size of the receiving dataset staying at 64k size for a couple of minutes, than sometimes it receives some 100Mb and hangs again for some minutes. (Trying zfs commands in other shell instances just hang then.)

**Comment by sempervictus** [comment]
Importing a pool with DDTs requires that they be loaded into memory, which would go through verification of each block read. How much data is in there, how bad are the DDT tables?

**Comment by gmelikov** [comment]
Close as stale, feel free to reopen if it's still actual.
