### ISSUE TITLE
zfs retroactive compress and dedup command

### ISSUE THREAD

**Issue by albionxyz** [zfsonlinux/zfs#3102]
As compression and and deduplication are not retroactive, wouldn't it make sense to have a command doing this?
So you could write something like
zfs retrocompress {on|off} {dataset}
and
zfs retrodedup {on|off} {dataset}

**Comment by albionxyz** [comment]
PS: how to write greater-than/less-than signs in github?

**Comment by rlaager** [comment]
This would be nice, but it's not really practical. You end up in "block-pointer rewrite" territory.

**Comment by rlaager** [comment]
Alternatively, see also #3013.
