### ISSUE TITLE
Broken debian package

### ISSUE THREAD

**Issue by aizikil** [zfsonlinux/zfs#3103]
Hello, today I'm trying to install on clean debian zfs.
It is not going well. (((

 sudo wget http://archive.zfsonlinux.org/debian/pool/main/z/zfsonlinux/zfsonlinux_4_all.deb
--2015-02-13 15:14:44--  http://archive.zfsonlinux.org/debian/pool/main/z/zfsonlinux/zfsonlinux_4_all.deb
Resolving archive.zfsonlinux.org (archive.zfsonlinux.org)... 54.231.10.49
Connecting to archive.zfsonlinux.org (archive.zfsonlinux.org)|54.231.10.49|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2040076 (1.9M) [application/x-debian-package]
Saving to: `zfsonlinux_4_all.deb'

100%[===================================================================================================================>] 2,040,076

2015-02-13 15:14:55 (186 KB/s) - `zfsonlinux_4_all.deb' saved [2040076/2040076]

aiz@serv5:~$ sudo dpkg -i zfsonlinux_4_all.deb
(Reading database ... 125097 files and directories currently installed.)
Preparing to replace zfsonlinux 2~wheezy (using zfsonlinux_4_all.deb) ...
Unpacking replacement zfsonlinux ...
Setting up zfsonlinux (4) ...
Installing new version of config file /etc/apt/trusted.gpg.d/zfsonlinux.gpg ...
aiz@serv5:~$ sudo apt-get update
Hit http://mirror.yandex.ru wheezy Release.gpg
Hit http://mirror.yandex.ru wheezy-updates Release.gpg
Hit http://security.debian.org wheezy/updates Release.gpg
Hit http://mirror.yandex.ru wheezy Release
Hit http://security.debian.org wheezy/updates Release
Hit http://mirror.yandex.ru wheezy-updates Release
Hit http://mirror.yandex.ru wheezy/main Sources
Hit http://security.debian.org wheezy/updates/main Sources
Hit http://mirror.yandex.ru wheezy/main amd64 Packages
Hit http://mirror.yandex.ru wheezy/main Translation-en
Hit http://mirror.yandex.ru wheezy-updates/main Sources
Hit http://security.debian.org wheezy/updates/main amd64 Packages
Hit http://mirror.yandex.ru wheezy-updates/main amd64 Packages/DiffIndex
Get:1 http://archive.zfsonlinux.org wheezy Release.gpg [836 B]
Hit http://mirror.yandex.ru wheezy-updates/main Translation-en/DiffIndex
Hit http://security.debian.org wheezy/updates/main Translation-en
Hit http://archive.zfsonlinux.org wheezy Release
Hit http://archive.zfsonlinux.org wheezy/main amd64 Packages
Ign http://archive.zfsonlinux.org wheezy/main Translation-en_US
Ign http://archive.zfsonlinux.org wheezy/main Translation-en
Fetched 836 B in 2s (338 B/s)
Reading package lists... Done
aiz@serv5:~$ sudo apt-get install debian-zfs
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  binutils build-essential cpp-4.6 dkms dpkg-dev fakeroot g++ g++-4.7 gcc gcc-4.6 gcc-4.6-base gcc-4.7 libalgorithm-diff-perl libalgor
  libalgorithm-merge-perl libc-dev-bin libc6-dev libdpkg-perl libfile-fcntllock-perl libitm1 libnvpair1 libstdc++6-4.7-dev libuutil1 l
  linux-headers-3.2.0-4-amd64 linux-headers-3.2.0-4-common linux-headers-amd64 linux-kbuild-3.2 linux-libc-dev make manpages-dev spl s
  zfsutils
Suggested packages:
  binutils-doc gcc-4.6-locales zfs-auto-snapshot debian-keyring g++-multilib g++-4.7-multilib gcc-4.7-doc libstdc++6-4.7-dbg gcc-multi
  automake1.9 libtool flex bison gdb gcc-doc gcc-4.6-multilib libmudflap0-4.6-dev gcc-4.6-doc libgcc1-dbg libgomp1-dbg libquadmath0-db
  binutils-gold gcc-4.7-multilib libmudflap0-4.7-dev gcc-4.7-locales libitm1-dbg libcloog-ppl0 libppl-c2 libppl7 glibc-doc libstdc++6-
  nfs-kernel-server samba-common-bin zfs-initramfs
Recommended packages:
  linux-headers
The following NEW packages will be installed:
  binutils build-essential cpp-4.6 debian-zfs dkms dpkg-dev fakeroot g++ g++-4.7 gcc gcc-4.6 gcc-4.6-base gcc-4.7 libalgorithm-diff-pe
  libalgorithm-diff-xs-perl libalgorithm-merge-perl libc-dev-bin libc6-dev libdpkg-perl libfile-fcntllock-perl libitm1 libnvpair1 libs
  libuutil1 libzfs2 libzpool2 linux-headers-3.2.0-4-amd64 linux-headers-3.2.0-4-common linux-headers-amd64 linux-kbuild-3.2 linux-libc
  manpages-dev spl spl-dkms zfs-dkms zfsutils
0 upgraded, 37 newly installed, 0 to remove and 4 not upgraded.
Need to get 51.2 MB of archives.
After this operation, 152 MB of additional disk space will be used.
Do you want to continue [Y/n]? n
Abort.
aiz@serv5:~$ uname -a
Linux serv5 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u1 x86_64 GNU/Linux
aiz@serv5:~$ uname -r
3.2.0-4-amd64
aiz@serv5:~$ sudo apt-get install debian-zfs
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  binutils build-essential cpp-4.6 dkms dpkg-dev fakeroot g++ g++-4.7 gcc gcc-4.6 gcc-4.6-base gcc-4.7 libalgorithm-diff-perl libalgor
  libalgorithm-merge-perl libc-dev-bin libc6-dev libdpkg-perl libfile-fcntllock-perl libitm1 libnvpair1 libstdc++6-4.7-dev libuutil1 l
  linux-headers-3.2.0-4-amd64 linux-headers-3.2.0-4-common linux-headers-amd64 linux-kbuild-3.2 linux-libc-dev make manpages-dev spl s
  zfsutils
Suggested packages:
  binutils-doc gcc-4.6-locales zfs-auto-snapshot debian-keyring g++-multilib g++-4.7-multilib gcc-4.7-doc libstdc++6-4.7-dbg gcc-multi
  automake1.9 libtool flex bison gdb gcc-doc gcc-4.6-multilib libmudflap0-4.6-dev gcc-4.6-doc libgcc1-dbg libgomp1-dbg libquadmath0-db
  binutils-gold gcc-4.7-multilib libmudflap0-4.7-dev gcc-4.7-locales libitm1-dbg libcloog-ppl0 libppl-c2 libppl7 glibc-doc libstdc++6-
  nfs-kernel-server samba-common-bin zfs-initramfs
Recommended packages:
  linux-headers
The following NEW packages will be installed:
  binutils build-essential cpp-4.6 debian-zfs dkms dpkg-dev fakeroot g++ g++-4.7 gcc gcc-4.6 gcc-4.6-base gcc-4.7 libalgorithm-diff-pe
  libalgorithm-diff-xs-perl libalgorithm-merge-perl libc-dev-bin libc6-dev libdpkg-perl libfile-fcntllock-perl libitm1 libnvpair1 libs
  libuutil1 libzfs2 libzpool2 linux-headers-3.2.0-4-amd64 linux-headers-3.2.0-4-common linux-headers-amd64 linux-kbuild-3.2 linux-libc
  manpages-dev spl spl-dkms zfs-dkms zfsutils
0 upgraded, 37 newly installed, 0 to remove and 4 not upgraded.
Need to get 51.2 MB of archives.
After this operation, 152 MB of additional disk space will be used.
Do you want to continue [Y/n]? y
Get:1 http://mirror.yandex.ru/debian/ wheezy/main libitm1 amd64 4.7.2-5 [36.6 kB]
Get:2 http://mirror.yandex.ru/debian/ wheezy/main gcc-4.7 amd64 4.7.2-5 [8,296 kB]
Get:3 http://security.debian.org/ wheezy/updates/main binutils amd64 2.22-8+deb7u2 [4,793 kB]
Get:4 http://archive.zfsonlinux.org/debian/ wheezy/main dkms all 2.2.0.3-1.2+zfs6 [78.8 kB]
Get:5 http://archive.zfsonlinux.org/debian/ wheezy/main spl-dkms all 0.6.3-7~wheezy [554 kB]
Get:6 http://archive.zfsonlinux.org/debian/ wheezy/main zfs-dkms all 0.6.3-1~wheezy [1,475 kB]
Get:7 http://security.debian.org/ wheezy/updates/main libc-dev-bin amd64 2.13-38+deb7u7 [225 kB]
Get:8 http://security.debian.org/ wheezy/updates/main linux-libc-dev amd64 3.2.65-1+deb7u1 [836 kB]
Get:9 http://archive.zfsonlinux.org/debian/ wheezy/main spl amd64 0.6.3-7~wheezy [15.8 kB]
Get:10 http://archive.zfsonlinux.org/debian/ wheezy/main libuutil1 amd64 0.6.3-1~wheezy [53.4 kB]
Get:11 http://archive.zfsonlinux.org/debian/ wheezy/main libnvpair1 amd64 0.6.3-1~wheezy [50.8 kB]
Get:12 http://security.debian.org/ wheezy/updates/main libc6-dev amd64 2.13-38+deb7u7 [2,666 kB]
Get:13 http://archive.zfsonlinux.org/debian/ wheezy/main libzpool2 amd64 0.6.3-1~wheezy [465 kB]
Get:14 http://archive.zfsonlinux.org/debian/ wheezy/main libzfs2 amd64 0.6.3-1~wheezy [144 kB]
Get:15 http://archive.zfsonlinux.org/debian/ wheezy/main zfsutils amd64 0.6.3-1~wheezy [401 kB]
Get:16 http://security.debian.org/ wheezy/updates/main linux-headers-3.2.0-4-common amd64 3.2.65-1+deb7u1 [3,586 kB]
Get:17 http://archive.zfsonlinux.org/debian/ wheezy/main debian-zfs amd64 7~wheezy [7,052 B]
Get:18 http://mirror.yandex.ru/debian/ wheezy/main gcc amd64 4:4.7.2-1 [5,064 B]
Get:19 http://mirror.yandex.ru/debian/ wheezy/main make amd64 3.81-8.2 [396 kB]
Get:20 http://mirror.yandex.ru/debian/ wheezy/main libstdc++6-4.7-dev amd64 4.7.2-5 [1,726 kB]
Get:21 http://mirror.yandex.ru/debian/ wheezy/main g++-4.7 amd64 4.7.2-5 [8,011 kB]
Get:22 http://security.debian.org/ wheezy/updates/main linux-headers-3.2.0-4-amd64 amd64 3.2.65-1+deb7u1 [625 kB]
Get:23 http://mirror.yandex.ru/debian/ wheezy/main g++ amd64 4:4.7.2-1 [1,374 B]
Get:24 http://mirror.yandex.ru/debian/ wheezy/main libdpkg-perl all 1.16.15 [958 kB]
Get:25 http://mirror.yandex.ru/debian/ wheezy/main dpkg-dev all 1.16.15 [1,356 kB]
Get:26 http://mirror.yandex.ru/debian/ wheezy/main build-essential amd64 11.5 [7,178 B]
Get:27 http://mirror.yandex.ru/debian/ wheezy/main gcc-4.6-base amd64 4.6.3-14 [142 kB]
Get:28 http://mirror.yandex.ru/debian/ wheezy/main cpp-4.6 amd64 4.6.3-14 [4,828 kB]
Get:29 http://mirror.yandex.ru/debian/ wheezy/main fakeroot amd64 1.18.4-2 [109 kB]
Get:30 http://mirror.yandex.ru/debian/ wheezy/main gcc-4.6 amd64 4.6.3-14 [7,325 kB]
Get:31 http://mirror.yandex.ru/debian/ wheezy/main libalgorithm-diff-perl all 1.19.02-2 [51.5 kB]
Get:32 http://mirror.yandex.ru/debian/ wheezy/main libalgorithm-diff-xs-perl amd64 0.04-2+b1 [12.9 kB]
Get:33 http://mirror.yandex.ru/debian/ wheezy/main libalgorithm-merge-perl all 0.08-2 [13.5 kB]
Get:34 http://mirror.yandex.ru/debian/ wheezy/main libfile-fcntllock-perl amd64 0.14-2 [17.2 kB]
Get:35 http://mirror.yandex.ru/debian/ wheezy/main linux-kbuild-3.2 amd64 3.2.17-1 [238 kB]
Get:36 http://mirror.yandex.ru/debian/ wheezy/main linux-headers-amd64 amd64 3.2+46 [4,450 B]
Get:37 http://mirror.yandex.ru/debian/ wheezy/main manpages-dev all 3.44-1 [1,737 kB]
Fetched 51.2 MB in 1min 17s (665 kB/s)
Extracting templates from packages: 100%
Preconfiguring packages ...
Selecting previously unselected package libitm1:amd64.
(Reading database ... 125098 files and directories currently installed.)
Unpacking libitm1:amd64 (from .../libitm1_4.7.2-5_amd64.deb) ...
Selecting previously unselected package binutils.
Unpacking binutils (from .../binutils_2.22-8+deb7u2_amd64.deb) ...
Selecting previously unselected package gcc-4.7.
Unpacking gcc-4.7 (from .../gcc-4.7_4.7.2-5_amd64.deb) ...
Selecting previously unselected package gcc.
Unpacking gcc (from .../gcc_4%3a4.7.2-1_amd64.deb) ...
Selecting previously unselected package make.
Unpacking make (from .../make_3.81-8.2_amd64.deb) ...
Selecting previously unselected package libc-dev-bin.
Unpacking libc-dev-bin (from .../libc-dev-bin_2.13-38+deb7u7_amd64.deb) ...
Selecting previously unselected package linux-libc-dev:amd64.
Unpacking linux-libc-dev:amd64 (from .../linux-libc-dev_3.2.65-1+deb7u1_amd64.deb) ...
Selecting previously unselected package libc6-dev:amd64.
Unpacking libc6-dev:amd64 (from .../libc6-dev_2.13-38+deb7u7_amd64.deb) ...
Selecting previously unselected package libstdc++6-4.7-dev.
Unpacking libstdc++6-4.7-dev (from .../libstdc++6-4.7-dev_4.7.2-5_amd64.deb) ...
Selecting previously unselected package g++-4.7.
Unpacking g++-4.7 (from .../g++-4.7_4.7.2-5_amd64.deb) ...
Selecting previously unselected package g++.
Unpacking g++ (from .../g++_4%3a4.7.2-1_amd64.deb) ...
Selecting previously unselected package libdpkg-perl.
Unpacking libdpkg-perl (from .../libdpkg-perl_1.16.15_all.deb) ...
Selecting previously unselected package dpkg-dev.
Unpacking dpkg-dev (from .../dpkg-dev_1.16.15_all.deb) ...
Selecting previously unselected package build-essential.
Unpacking build-essential (from .../build-essential_11.5_amd64.deb) ...
Selecting previously unselected package dkms.
Unpacking dkms (from .../dkms_2.2.0.3-1.2+zfs6_all.deb) ...
Selecting previously unselected package spl-dkms.
Unpacking spl-dkms (from .../spl-dkms_0.6.3-7~wheezy_all.deb) ...
Processing triggers for man-db ...
Setting up binutils (2.22-8+deb7u2) ...
Setting up libitm1:amd64 (4.7.2-5) ...
Setting up gcc-4.7 (4.7.2-5) ...
Setting up gcc (4:4.7.2-1) ...
Setting up make (3.81-8.2) ...
Setting up libc-dev-bin (2.13-38+deb7u7) ...
Setting up linux-libc-dev:amd64 (3.2.65-1+deb7u1) ...
Setting up libc6-dev:amd64 (2.13-38+deb7u7) ...
Setting up libdpkg-perl (1.16.15) ...
Setting up dpkg-dev (1.16.15) ...
Setting up dkms (2.2.0.3-1.2+zfs6) ...
Setting up spl-dkms (0.6.3-7~wheezy) ...
Loading new spl-0.6.3 DKMS files...
First Installation: checking all kernels...
Building only for 3.2.0-4-amd64
Module build for the currently running kernel was skipped since the
kernel source for this kernel does not seem to be installed.
Setting up g++-4.7 (4.7.2-5) ...
Setting up g++ (4:4.7.2-1) ...
update-alternatives: using /usr/bin/g++ to provide /usr/bin/c++ (c++) in auto mode
Setting up build-essential (11.5) ...
Setting up libstdc++6-4.7-dev (4.7.2-5) ...
Selecting previously unselected package zfs-dkms.
(Reading database ... 128088 files and directories currently installed.)
Unpacking zfs-dkms (from .../zfs-dkms_0.6.3-1~wheezy_all.deb) ...
Selecting previously unselected package gcc-4.6-base:amd64.
Unpacking gcc-4.6-base:amd64 (from .../gcc-4.6-base_4.6.3-14_amd64.deb) ...
Selecting previously unselected package cpp-4.6.
Unpacking cpp-4.6 (from .../cpp-4.6_4.6.3-14_amd64.deb) ...
Selecting previously unselected package spl.
Unpacking spl (from .../spl_0.6.3-7~wheezy_amd64.deb) ...
Selecting previously unselected package libuutil1.
Unpacking libuutil1 (from .../libuutil1_0.6.3-1~wheezy_amd64.deb) ...
Selecting previously unselected package libnvpair1.
Unpacking libnvpair1 (from .../libnvpair1_0.6.3-1~wheezy_amd64.deb) ...
Selecting previously unselected package libzpool2.
Unpacking libzpool2 (from .../libzpool2_0.6.3-1~wheezy_amd64.deb) ...
Selecting previously unselected package libzfs2.
Unpacking libzfs2 (from .../libzfs2_0.6.3-1~wheezy_amd64.deb) ...
Selecting previously unselected package zfsutils.
Unpacking zfsutils (from .../zfsutils_0.6.3-1~wheezy_amd64.deb) ...
Selecting previously unselected package debian-zfs.
Unpacking debian-zfs (from .../debian-zfs_7~wheezy_amd64.deb) ...
Selecting previously unselected package fakeroot.
Unpacking fakeroot (from .../fakeroot_1.18.4-2_amd64.deb) ...
Selecting previously unselected package gcc-4.6.
Unpacking gcc-4.6 (from .../gcc-4.6_4.6.3-14_amd64.deb) ...
Selecting previously unselected package libalgorithm-diff-perl.
Unpacking libalgorithm-diff-perl (from .../libalgorithm-diff-perl_1.19.02-2_all.deb) ...
Selecting previously unselected package libalgorithm-diff-xs-perl.
Unpacking libalgorithm-diff-xs-perl (from .../libalgorithm-diff-xs-perl_0.04-2+b1_amd64.deb) ...
Selecting previously unselected package libalgorithm-merge-perl.
Unpacking libalgorithm-merge-perl (from .../libalgorithm-merge-perl_0.08-2_all.deb) ...
Selecting previously unselected package libfile-fcntllock-perl.
Unpacking libfile-fcntllock-perl (from .../libfile-fcntllock-perl_0.14-2_amd64.deb) ...
Selecting previously unselected package linux-headers-3.2.0-4-common.
Unpacking linux-headers-3.2.0-4-common (from .../linux-headers-3.2.0-4-common_3.2.65-1+deb7u1_amd64.deb) ...
Selecting previously unselected package linux-kbuild-3.2.
Unpacking linux-kbuild-3.2 (from .../linux-kbuild-3.2_3.2.17-1_amd64.deb) ...
Selecting previously unselected package linux-headers-3.2.0-4-amd64.
Unpacking linux-headers-3.2.0-4-amd64 (from .../linux-headers-3.2.0-4-amd64_3.2.65-1+deb7u1_amd64.deb) ...
Selecting previously unselected package linux-headers-amd64.
Unpacking linux-headers-amd64 (from .../linux-headers-amd64_3.2+46_amd64.deb) ...
Selecting previously unselected package manpages-dev.
Unpacking manpages-dev (from .../manpages-dev_3.44-1_all.deb) ...
Processing triggers for initramfs-tools ...
update-initramfs: Generating /boot/initrd.img-3.2.0-4-amd64
Processing triggers for man-db ...
Setting up zfs-dkms (0.6.3-1~wheezy) ...
Loading new zfs-0.6.3 DKMS files...
First Installation: checking all kernels...
Building only for 3.2.0-4-amd64
Building initial module for 3.2.0-4-amd64
configure: error:
        *** Please make sure the kmod spl devel <kernel> package for your
        *** distribution is installed then try again.  If that fails you
        *** can specify the location of the spl objects with the
        *** '--with-spl-obj=PATH' option.
Error! Bad return status for module build on kernel: 3.2.0-4-amd64 (x86_64)
Consult /var/lib/dkms/zfs/0.6.3/build/make.log for more information.
Setting up gcc-4.6-base:amd64 (4.6.3-14) ...
Setting up cpp-4.6 (4.6.3-14) ...
Setting up spl (0.6.3-7~wheezy) ...
Setting up libuutil1 (0.6.3-1~wheezy) ...
Setting up libnvpair1 (0.6.3-1~wheezy) ...
Setting up libzpool2 (0.6.3-1~wheezy) ...
Setting up libzfs2 (0.6.3-1~wheezy) ...
Setting up zfsutils (0.6.3-1~wheezy) ...
Setting up fakeroot (1.18.4-2) ...
update-alternatives: using /usr/bin/fakeroot-sysv to provide /usr/bin/fakeroot (fakeroot) in auto mode
Setting up gcc-4.6 (4.6.3-14) ...
Setting up libalgorithm-diff-perl (1.19.02-2) ...
Setting up libalgorithm-diff-xs-perl (0.04-2+b1) ...
Setting up libalgorithm-merge-perl (0.08-2) ...
Setting up libfile-fcntllock-perl (0.14-2) ...
Setting up linux-headers-3.2.0-4-common (3.2.65-1+deb7u1) ...
Setting up linux-kbuild-3.2 (3.2.17-1) ...
Setting up linux-headers-3.2.0-4-amd64 (3.2.65-1+deb7u1) ...
Examining /etc/kernel/header_postinst.d.
run-parts: executing /etc/kernel/header_postinst.d/dkms 3.2.0-4-amd64
Setting up linux-headers-amd64 (3.2+46) ...
Setting up manpages-dev (3.44-1) ...
Processing triggers for initramfs-tools ...
update-initramfs: Generating /boot/initrd.img-3.2.0-4-amd64
Setting up debian-zfs (7~wheezy) ...

**Comment by aizikil** [comment]
Workaround is here ----- http://louwrentius.com/installation-of-zfs-on-linux-hangs-on-debian-wheezy.html

**Comment by tuxoko** [comment]
It seems that it tries spl-dkms before kernel header is installed.
Maybe the dependency isn't setup in the spl-dkms package?

**Comment by FransUrbo** [comment]
> It seems that it tries spl-dkms before kernel header is installed.
> Maybe the dependency isn't setup in the spl-dkms package?
> 
With some help on IRC, we found the issue is in the following dependency list:

	spl-dkms -> dkms -> recommends=linux-headers-amd64

The problem here is that recommends are not ordered before the actual package.


Thanx to xorAxAx on #zfsonlinux for helping me with this (I just haven't had the time to deal with it - it's always (!!) worked for me, even on fresh installs).

**Comment by TwizzyDizzy** [comment]
Hi folks,

I don't know if the dependency chain of the kernel headers is the only issue here.

In fact I just had some troubles installing the latest version of zfsonlinux on a fresh Debian Jessie.

The plain install of debian-zfs left me in a state where neither ZFS nor SPL kernel modules have been built.

The following did the trick though:

> dpkg-reconfigure spl-dkms
> modprobe spl
> dpkg-reconfigure zfs-dkms
> modprobe zfs

It seems as - pretty obviously - the SPL module had to be built/loaded before the build of the ZFS module went fine.

Hope this could contribute something to this discussion.

Cheers
Thomas

**Comment by rlaager** [comment]
ZFS is packaged in Debian now. If this is still an issue with the official Debian packages, it should probably be taken to the Debian bug tracker.
