### ISSUE TITLE
Slow creation of dataset

### ISSUE THREAD

**Issue by behlendorf** [zfsonlinux/zfs#3105]
Originally opened at zfsonlinux/spl#432 by @michalstab.

Time to create dataset is longer with every new dataset. Tested on:
package zfs-0.6.3-1.2.el6.x86_64 (CentOS release 6.6 2.6.32-504.8.1.el6.x86_64)

package zfs-0.6.3-1.2.el7.centos.x86_64 (CentOS release 7-0.1406 3.10.0-123.13.2.el7.x86_64)

With 7278 datasets

```
[root@localhost ~]# time zfs create pool1/home2/aaas2
real    0m23.651s
user    0m19.804s
sys 0m3.567s
With 7280 datasets

[root@localhost ~]# time zfs create pool1/home2/aaaps2
real    0m24.234s
user    0m20.013s
sys 0m4.005s
```

On FreeBSD works correctly.

**Comment by rmgoodberlet** [comment]
Any progress or updates on this issue?  Still happening in 0.6.5.3 on Oracle Linux 6.  Can provide additional information if helpful.  

[root@]# time zfs list | wc -l
19927

real    0m5.241s
user    0m1.025s
sys     0m4.207s
[root@]# time zfs create zfs_data/cifs/home/dilbert1

real    1m8.778s
user    1m2.145s
sys     0m6.370s
[root@]# time zfs create zfs_data/cifs/home/dilbert2

real    1m12.464s
user    1m5.265s
sys     0m6.608s


strace of the zfs create process shows over 20k open() calls, nearly all of which are open("/etc/mtab", O_RDONLY).  The total strace output is 3299707 lines long (which is impressive).  Running the trace on an identical server that has 2 datasets results in a 502 line trace with 9 mtab mentions.

mtab cache seems to be enabled:

[root@]# grep "libzfs_mnttab_cache" /usr/src/zfs-0.6.5.3/cmd/zfs/zfs_main.c
        libzfs_mnttab_cache(g_zfs, B_TRUE);

**Comment by behlendorf** [comment]
@rmgoodberlet I believe this was addressed in master by commit e3e670d0061ff121293dafb37d1f14a7069d49d5.  This should eliminate most of the `open("/etc/mtab", O_RDONLY)` calls and speed things up.  If would be great if you could apply and verify the fix independently for us.

**Comment by mailinglists35** [comment]
@behlendorf I am observing this behaviour on 0.6.5.6 - was that commit included in the release?

**Comment by mailinglists35** [comment]
@behlendorf downloading and unpacking the following file `c349d46d86b4f61cd53a0891acad916cfc3f0d6754127db7f60a0bd98185aeff  zfs-0.6.5.6.tar.gz` gives me `./zfs-0.6.5.6/lib/libzfs/libzfs_mount.c` that does not seem to contain the changes from that referenced commit.

root@homerouter:/usr/local/src/zfs/0.6.5.6# wget https://raw.githubusercontent.com/zfsonlinux/zfs/e3e670d0061ff121293dafb37d1f14a7069d49d5/lib/libzfs/libzfs_mount.c
--2016-04-25 18:20:24--  https://raw.githubusercontent.com/zfsonlinux/zfs/e3e670d0061ff121293dafb37d1f14a7069d49d5/lib/libzfs/libzfs_mount.c
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.31.19.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.31.19.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 32663 (32K) [text/plain]
Saving to: ‘libzfs_mount.c’

libzfs_mount.c      100%[=====================>]  31.90K  --.-KB/s   in 0s

2016-04-25 18:20:25 (81.7 MB/s) - ‘libzfs_mount.c’ saved [32663/32663]

root@homerouter:/usr/local/src/zfs/0.6.5.6# diff libzfs_mount.c ./zfs-0.6.5.6/lib/libzfs/libzfs_mount.c
23d22
    <  * Copyright 2015 Nexenta Systems, Inc.  All rights reserved.
    25d23
    <  * Copyright (c) 2014 by Delphix. All rights reserved.
    748a747,753
    >       if ((ret = zfs_init_libshare(hdl, SA_INIT_SHARE_API)) != SA_OK) {
    >               (void) zfs_error_fmt(hdl, EZFS_SHARENFSFAILED,
    >                   dgettext(TEXT_DOMAIN, "cannot share '%s': %s"),
    >                   zfs_get_name(zhp), sa_errorstr(ret));
    >               return (-1);
    >       }
    >
    759,766d763
    <               ret = zfs_init_libshare(hdl, SA_INIT_SHARE_API);
    <               if (ret != SA_OK) {
    <                       (void) zfs_error_fmt(hdl, EZFS_SHARENFSFAILED,
    <                           dgettext(TEXT_DOMAIN, "cannot share '%s': %s"),
    <                           zfs_get_name(zhp), sa_errorstr(ret));
    <                       return (-1);
    <               }
    <
    863c860
    <               return (zfs_error_fmt(hdl, EZFS_UNSHARENFSFAILED,
    ---
    >               return (zfs_error_fmt(hdl, EZFS_SHARENFSFAILED,

**Comment by mailinglists35** [comment]
the same for zfs-0.6.5.6/lib/libzfs/libzfs_dataset.c

**Comment by behlendorf** [comment]
@mailinglists35 it is not part of 0.6.5.6.  However, it is safe to cherry-pick if you need it for your systems.  Closing, this should be resolved by:

e3e670d Illumos 4953, 4954, 4955

**Comment by ANorwell** [comment]
Are there plans to add this to a release?

**Comment by behlendorf** [comment]
@ANorwell thanks for the comment.  @nedbass this is definitely something we should consider cherry picking for the 0.6.5.x release.
