### ISSUE TITLE
zfs corrupted file <0x0>

### ISSUE THREAD

**Issue by K1773R** [zfsonlinux/zfs#3108]
After a scrub, a weird file seems to be gotten corrupted. Its sill there after a rollback to a recent snapshot:

```
  pool: rpool
 state: ONLINE
status: One or more devices has experienced an error resulting in data
	corruption.  Applications may be affected.
action: Restore the file in question if possible.  Otherwise restore the
	entire pool from backup.
   see: http://zfsonlinux.org/msg/ZFS-8000-8A
  scan: scrub repaired 0 in 18h39m with 0 errors on Sun Feb 15 13:20:18 2015
config:

	NAME             STATE     READ WRITE CKSUM
	rpool            ONLINE       0     0     0
	  mirror-0       ONLINE       0     0     0
	    cryptrpool1  ONLINE       0     0     0
	    cryptrpool2  ONLINE       0     0     0

errors: Permanent errors have been detected in the following files:

        rpool/HOME/k1773r:<0x0>


NAME                USED  AVAIL  REFER  MOUNTPOINT
rpool/HOME/k1773r  1.00T   757G   826G  /home/k1773r
```
How can i remove said file and make my zpool "happy" again?

**Comment by sempervictus** [comment]
I'm seeing something very similar in #3094 and wondering how active your home dataset is. I'm seeing something like this on a random-io-heavy dataset (not a lot of writes, but heavy read and bursts of small random writes). Fun part is that the damaged "file" appears to be the dataset itself, or maybe even the pool. @behlendorf suggested i look @ zdb -m and zdb -M on the pool itself - and they show a spacemap mismatch in my case (one which seems to be randomly guessing at how many spacemaps it should have).

Which version of ZFS are you running? Does the snapshot which you restored show the error as well? In my case, scrub shows the damaged DS and a snapshot already containing the damage:
```
errors: Permanent errors have been detected in the following files:

        rpool/steam:<0x0>
        rpool/steam@20150210-1528:<0x0>
```

**Comment by K1773R** [comment]
im using v0.6.3. i dont have the metaslab problem as you.
yes, after a zfs rollback the error was still there.
it does not show it for the snapshot itself.

**Comment by lundman** [comment]
Are you running straight ZOL, or does your dataset names suggest zfs-crypto? If it is the latter, then the recent pull request dealt with 0x0 error
https://github.com/zfsrogue/zfs-crypto/commit/710c3f3c24edda71b408857f4a9eeb3ac56a7e78

If it is straight ZOL, I apologise for the noise.

**Comment by K1773R** [comment]
@lundman yes, straight ZOL with LUKS/dm. didnt knew that zfs-crypto exists.

**Comment by lundman** [comment]
My apologies for the noise, my comments will disappear :)

**Comment by K1773R** [comment]
a second scrub didnt help. also whats weird, it never showed an error for read/cksum, tough that might be due to another issue already submitted.
as its a production system, i'l have to restore from backups now. i will save the full output of zdb for later usage (if needed).

**Comment by K1773R** [comment]
after destorying the dataset and running scrub again, the error is gone.

**Comment by K1773R** [comment]
it seems the problem was caused by a bad HBA and not zfs, closing for now.

**Comment by Harvie** [comment]
Is there way to fix this without recreating the dataset?
