### ISSUE TITLE
zfs is not pointing to latest commit

### ISSUE THREAD

**Issue by kiranfractal** [zfsonlinux/zfs#3118]
I installed zfs by enabling zfs-testing in the zfs.repo file.

It is not pointing to the current master commit.

[root@li349-79 ~]# modinfo zfs
filename:       /lib/modules/2.6.32-504.1.3.el6.x86_64/extra/zfs.ko
version:        0.6.3-202_g33b4de5
license:        CDDL
author:         OpenZFS on Linux
description:    ZFS
srcversion:     C9D2FB9AD6E010CB2F6B3DE
depends:        spl,znvpair,zcommon,zunicode,zavl
vermagic:       2.6.32-504.1.3.el6.x86_64 SMP mod_unload modversions 
parm:           zvol_inhibit_dev:Do not create zvol device nodes (uint)
parm:           zvol_major:Major number for zvol device (uint)
parm:           zvol_threads:Number of threads for zvol device (uint)
parm:           zvol_max_discard_blocks:Max number of blocks to discard (ulong)

**Comment by behlendorf** [comment]
@kiranfractal thanks, we'll get the packages updated.

**Comment by behlendorf** [comment]
Closes the repositories have been updated.
