### ISSUE TITLE
Please include to-be-released jessie (Debian 8)  to buildbots farm

### ISSUE THREAD

**Issue by yarikoptic** [zfsonlinux/zfs#3121]
jessie is on the way to be released soon and not that many changes are pushed in usually.  It would be nice to be sure that ZFS is working reliably on it (I am trying to use it on jessie with some success)

BTW -- how do you link buildbot reports to PRs reports?  at some point a while back I was looking for a solution but didn't find.

**Comment by behlendorf** [comment]
Good idea, I'll get it installed when I get a chance.

Github provides a simple [status API](https://developer.github.com/v3/repos/statuses/) which can be used to post results.  We've just updated our builtbot infrastructure to post pass/fail along with a link to the detailed buildbot results.

**Comment by yarikoptic** [comment]
Thanks in advance for jessie!

buildbot infrastructure -- anything anywhere public to sneak up the recipe? then I would improve ours ;) -- https://github.com/nipy/nibotmi

**Comment by behlendorf** [comment]
Sorry not yet, but I agree it would be nice to make all of our buildbot glue available.

**Comment by yarikoptic** [comment]
would you be so kind to share at least bits of that recipe "manually"? ;)  e.g. to debian@onerussian.com

**Comment by yarikoptic** [comment]
@behlendorf  if you share with me your buildbot<->GitHub setup in some shape I can promise to "polish it up" for a re-consumable thing for others ;-)

**Comment by behlendorf** [comment]
Debian 8 builder was added some time ago.

http://build.zfsonlinux.org/builders/Debian%208%20x86_64%20%28BUILD%29

@yarikoptic sorry it took so long but we've published our buildbot<->github infrastructure.  If you're still game to polish it up we'd love the help.  There are a handful of things we'd love to have improve here in the issue  tracker:

https://github.com/zfsonlinux/zfs-buildbot/

https://github.com/zfsonlinux/zfs-buildbot/issues

**Comment by yarikoptic** [comment]
Thanks @behlendorf -- great to see it published!  Better later than never!
For my project I just adopted buildbot<->github integration setup from https://github.com/ethereum/ethereum-buildbot
