### ISSUE TITLE
ztest does not take kindly to being installed in /usr/local

### ISSUE THREAD

**Issue by nwf** [zfsonlinux/zfs#3126]
It segfaults at cmd/ztest/ztest.c:5396, trying to construct the correct invocation for "zdb".  Even symlinking it into /sbin isn't sufficient because it calls realpath() to see through such things.  Perhaps using an environment variable to indicate the path to zdb, overriding this attempted search, is the right answer?

**Comment by behlendorf** [comment]
Yeah, this chunk of code has always been pretty horrible.  I think it's completely reasonable that callers need to have the path to `zdb` in their PATH environment.  We could update the code to honor an environment variable to override the search as you suggested.
