### ISSUE TITLE
Support for richacls

### ISSUE THREAD

**Issue by Bronek** [zfsonlinux/zfs#3133]
Please treat this as proxy request for comments, rather than a bug report or even feature request.

Today (26th Feb 2015), Andreas Gruenbacher issued request on LKML for comments and code review of upcoming richacls for Linux filesystems feature. Assuming that, if (when?) this feature is eventually merged into the kernel, given the rationale for this new feature ("improve
interoperability between Linux and other systems, mainly across the NFSv4 and
CIFS/SMB protocols"), it will make perfect sense to later add support for this feature in ZoL. It would be thus highly desired if ZoL community itself provided early feedback on the design and implementation of richacls as to make this integration work less awkward (I'm not saying "easy").

**Comment by behlendorf** [comment]
The easier path here will probably be to the needed code to support NFSv4 ACLs as described in #4966.
