### ISSUE TITLE
zpool can't import pool on disk partition

### ISSUE THREAD

**Issue by kpande** [zfsonlinux/zfs#3145]
I've got a weird situation here. I can't seem to get a pool imported on a particular server without deleting the whole disk dev node.. 

I created a pool on two disks, using partition 4 of each. It was working fine for a long time, then behaved oddly - couldn't attach iSCSI targets to volumes even though the /dev/zvol node existed, ietadm didn't want to comply. I rebooted the server and the pool was not able to import.

I've copied a bunch of relevant output here: https://gist.github.com/kpande/74b1cdf3468e17e31250

I couldn't import using /dev/ or /dev/by-id/ even though the dev nodes and symlinks all pointed to separate objects.

zdb showed the device path as being the whole disk. when I removed the whole disk dev node, it displayed the dev path as partition4 like I expected to.

**Comment by aarcane** [comment]
Your partition is too close to the end of the disk. You should use a tool
like gparted to relocate the partition at least 10MiB from the end of the
disk. You may need to destroy and recreate

**Comment by kpande** [comment]
That's not the case. This server, and dozens like it, have been running for two years.

**Comment by aarcane** [comment]
Can you add the output of:
parted
unit s
p

To your gist?

**Comment by kpande** [comment]
(parted) unit s                                                           
(parted) p                                                                
Model: ATA ST3500320NS (scsi)
Disk /dev/sda: 976773168s
Sector size (logical/physical): 512B/512B
Partition Table: gpt

Number  Start      End         Size        File system  Name     Flags
 1      2048s      48828415s   48826368s                primary
 2      48828416s  80078847s   31250432s                primary
 3      80078848s  80273407s   194560s                  primary  bios_grub
 4      80273408s  976773119s  896499712s  zfs          primary

**Comment by kpande** [comment]
updated gist

**Comment by dasjoe** [comment]
I'm with @aarcane, your ZFS partition is too close to the end of those disks.

Ongoing transactions probably wrote data (i.e. uberblock array has grown) into the area where ZFS checks for the vdev labels when it's using partitionless disks.

What about swapping partitions 3 and 4, is there any reason why your `bios_grub` isn't partition 4?

**Comment by kpande** [comment]
doesn't make sense: "Ongoing transactions probably wrote data (i.e. uberblock array has grown) into the area where ZFS checks for the vdev labels when it's using partitionless disks."

If this were the case we'd be seeing an awful lot more disk corruption and un-importable pools. It'd also probably start failing scrub and other things due to something being written in the wrong partition.

**Comment by kpande** [comment]
Is there any way to mitigate this issue inside the zpool source - i.e. check whether a vdev label is inside the last partition and ignore the whole disk if it is?

**Comment by thegreatgazoo** [comment]
@dasjoe and @aarcane: Can you please elaborate why the partition can't be near the end of a disk?

My understanding is that uberblock array is fixed and does not grow, so I also found the "uberblock array has grown" claim hard to understand - maybe I missed something here.

**Comment by kpande** [comment]
so it looks like this isn't a case of zpool getting confused about the location of the label, it is something else.

I created a partition table on a drive in an attempt to convert a live system to ZFS root..

I created 4 partitions, the last containing ZFS, but it was 10*GB* away from the end of the disk.

Created the pool using 'zpool create -o ashift=12 tank /dev/sdb4'

Exported, imported the pool just fine using /dev/disk/by-id.

I booted a VM using the whole disk and it gets through Grub, loads Dracut which complains about the pool being unavailable. 

At the dracut shell, I can see that it is attempting to import the *whole disk* instead of part4.

When I rm the whole device, the pool is imported from the partition.

**Comment by kpande** [comment]
any chance at a fix for this @behlendorf ? this is causing grief on a lot of systems that were fine before (maybe recent changes ) switching to HEAD newer than -175

**Comment by kpande** [comment]
[~sys/disk/by-id]-[root@h]-[1]-[873]
[:(] # zpool import -d /dev/disk/by-id 
   pool: tank
     id: 5884798594334896503
  state: UNAVAIL
 status: One or more devices contains corrupted data.
 action: The pool cannot be imported due to damaged devices or data.
   see: http://zfsonlinux.org/msg/ZFS-8000-5E
 config:

	tank                                         UNAVAIL  insufficient replicas
	  mirror-0                                   UNAVAIL  insufficient replicas
	    1620547016084460107                      UNAVAIL
	    ata-HGST_HUS724030ALA640_PN2234P8KKY91Y  UNAVAIL
[~sys/disk/by-id]-[root@h]-[1]-[874]
[:(] # ls
ata-HGST_HUS724030ALA640_PN2234P8KKXLPY        ata-HGST_HUS724030ALA640_PN2234P8KKY91Y-part2  scsi-SATA_HGST_HUS724030A_PN2234P8KKXLPY        scsi-SATA_HGST_HUS724030A_PN2234P8KKY91Y-part2  
wwn-0x5000cca22cf26ec7-part1
ata-HGST_HUS724030ALA640_PN2234P8KKXLPY-part1  ata-HGST_HUS724030ALA640_PN2234P8KKY91Y-part3  scsi-SATA_HGST_HUS724030A_PN2234P8KKXLPY-part1  scsi-SATA_HGST_HUS724030A_PN2234P8KKY91Y-part3  
wwn-0x5000cca22cf26ec7-part2
ata-HGST_HUS724030ALA640_PN2234P8KKXLPY-part2  
ata-HGST_HUS724030ALA640_PN2234P8KKY91Y-part4  
scsi-SATA_HGST_HUS724030A_PN2234P8KKXLPY-part2  
scsi-SATA_HGST_HUS724030A_PN2234P8KKY91Y-part4
  wwn-0x5000cca22cf26ec7-part3
ata-HGST_HUS724030ALA640_PN2234P8KKXLPY-part3 
 md-name-debian64:0                             
scsi-SATA_HGST_HUS724030A_PN2234P8KKXLPY-part3  
wwn-0x5000cca22cf26c31-part1                    
wwn-0x5000cca22cf26ec7-part4
ata-HGST_HUS724030ALA640_PN2234P8KKXLPY-part4
  md-name-debian64:1                             
scsi-SATA_HGST_HUS724030A_PN2234P8KKXLPY-part4
  wwn-0x5000cca22cf26c31-part2
ata-HGST_HUS724030ALA640_PN2234P8KKY91Y
md-uuid-a92e40e5:eb09ab7d:4a2468ab:3b2ab0e1    scsi-SATA_HGST_HUS724030A_PN2234P8KKY91Y       
wwn-0x5000cca22cf26c31-part3
ata-HGST_HUS724030ALA640_PN2234P8KKY91Y-part1
md-uuid-c2239dd4:83f5ad17:cea93056:86cd0e54    scsi-SATA_HGST_HUS724030A_PN2234P8KKY91Y-part1 
wwn-0x5000cca22cf26c31-part4
[~sys/disk/by-id]-[root@h]-[0]-[875]
[:)] # rm ata* scsi*
[~sys/disk/by-id]-[root@h]-[0]-[876]
[:)] # zpool import -d /dev/disk/by-id 
   pool: tank
     id: 5884798594334896503
  state: ONLINE
 action: The pool can be imported using its name or numeric identifier.
 config:

	tank                              ONLINE
	  mirror-0                        ONLINE
	    wwn-0x5000cca22cf26c31-part4  ONLINE
	    wwn-0x5000cca22cf26ec7-part4  ONLINE
[~sys/disk/by-id]-[root@h]-[0]-[877]
[:)] # zpool import -d /dev/disk/by-id -a
[~sys/disk/by-id]-[root@h]-[0]-[878]
[:)] #

**Comment by kpande** [comment]
It may be useful to know, I had an issue setting up a Gentoo server with a GPT label disk - the pool would not import at boot unless I remove the whole disk devnode. On the other hand, I was able to use an MBR layout without issue.

**Comment by kpande** [comment]
After a reboot:

```
[~]-[root@host]-[0]-[321]
[:)] # zpool status           
no pools available
[~]-[root@host]-[0]-[322]
[:)] # zpool import
   pool: tank
     id: 1191463676227608509
  state: DEGRADED
 status: One or more devices contains corrupted data.
 action: The pool can be imported despite missing or damaged devices.  The
	fault tolerance of the pool may be compromised if imported.
   see: http://zfsonlinux.org/msg/ZFS-8000-4J
 config:

	tank                                     DEGRADED
	  mirror-0                               DEGRADED
	    6365044544702214197                  UNAVAIL
	    pci-0000:00:1f.2-scsi-0:0:0:0-part4  ONLINE
[~]-[root@host]-[0]-[323]
[:)] # zpool export ank
cannot open 'ank': no such pool
[~]-[root@host]-[1]-[324]
[:(] # zpool export tank
cannot open 'tank': no such pool
[~]-[root@host]-[1]-[325]
[:(] # zpool import -a -f
[~]-[root@host]-[0]-[326]
[:)] # zpool export tank 
[~]-[root@host]-[0]-[327]
[:)] # zpool import -a -d /dev
cannot import 'tank': one or more devices are already in use

[~]-[root@host]-[1]-[328]
[:(] # zpool import -d /dev   
   pool: tank
     id: 1191463676227608509
  state: UNAVAIL
 status: One or more devices contains corrupted data.
 action: The pool cannot be imported due to damaged devices or data.
   see: http://zfsonlinux.org/msg/ZFS-8000-5E
 config:

	tank                     UNAVAIL  insufficient replicas
	  mirror-0               UNAVAIL  insufficient replicas
	    6365044544702214197  UNAVAIL
	    sdb                  UNAVAIL
[~]-[root@host]-[0]-[329]
[:)] # zpool import -a -d /dev/disk/by-id
cannot import 'tank': one or more devices are already in use

[~]-[root@host]-[1]-[330]
[:(] # zpool import -d /dev/disk/by-id 
   pool: tank
     id: 1191463676227608509
  state: UNAVAIL
 status: One or more devices contains corrupted data.
 action: The pool cannot be imported due to damaged devices or data.
   see: http://zfsonlinux.org/msg/ZFS-8000-5E
 config:

	tank                                 UNAVAIL  insufficient replicas
	  mirror-0                           UNAVAIL  insufficient replicas
	    6365044544702214197              UNAVAIL
	    ata-ST2000DM001-9YN164_Z1E05X81  UNAVAIL
[~]-[root@host]-[0]-[331]
[:)] # zpool status
no pools available
[~]-[root@host]-[0]-[332]
[:)] # rm /dev/disk/by-id/ata*
[~]-[root@host]-[0]-[333]
[:)] # rm /dev/disk/by-id/scsi*
[~]-[root@host]-[0]-[334]
[:)] # rm /dev/disk/by-id/wwn-0x5000c5003f2823b6 
[~]-[root@host]-[0]-[335]
[:)] # rm /dev/disk/by-id/wwn-0x5000c5003f5a608c 
[~]-[root@host]-[0]-[336]
[:)] # zpool import -d /dev/disk/by-id          
   pool: tank
     id: 1191463676227608509
  state: ONLINE
 action: The pool can be imported using its name or numeric identifier.
 config:

	tank                              ONLINE
	  mirror-0                        ONLINE
	    wwn-0x5000c5003f2823b6-part4  ONLINE
	    wwn-0x5000c5003f5a608c-part4  ONLINE
[~]-[root@host]-[0]-[337]
[:)] # 
```

**Comment by behlendorf** [comment]
@kpande do we have a test case for how to create a pool with this problem?  (I may have missed it above).

**Comment by kpande** [comment]
@behlendorf I used our standard system installer with debian wheezy. We've been setting systems up using the following:
```
for i in /dev/md* ; do mdadm --stop $i  ; done
mdadm --zero-superblock /dev/${1}1
mdadm --zero-superblock /dev/${1}2
# the issue does not really occur with MBR configuration
parted /dev/$1 --script -- mklabel gpt
# 25GB mdadm root filesystem
parted /dev/$1 --script -- mkpart primary 1 25G
# 16GB reserved for swap
parted /dev/$1 --script -- mkpart primary 25G 41G
# overprovision storage for grub_bios
parted /dev/$1 --script -- mkpart primary 41G 41.1G 
parted /dev/$1 --script -- toggle 3 bios_grub
# partition the rest of the disk for ZFS
parted /dev/$1 --script -- mkpart primary 41.1G 100\%
# create mdraid, add children later
mdadm --create -f --auto=yes /dev/md0 --level=mirror --raid-devices=2 /dev/${DRIVE1}1 ${DRIVE2}1
mdadm --create -f --auto=yes /dev/md1 --level=mirror --raid-devices=2 /dev/${DRIVE1}2 ${DRIVE2}2
# format mdraid with ext4
mkfs.ext4 -F -F /dev/md0
# zpool create using /dev/sd* device nodes directly
zpool create -fo ashift=12 tank mirror /dev/${DRIVE1}4 /dev/${DRIVE2}4
```

When booting with USE_DISK_BY_ID=1 in /etc/default/grub it will not import the pool. If I import using -d /dev/disk/by-id I must rm the whole disk first - if it does not use by-id the pool imports. The downside is, once I've set a machine to import using by-id, this problem recurs on every reboot.

**Comment by behlendorf** [comment]
@kpande so it sounds like the problem is that ZFS is finding the specific vdevs by too many different names and is basically having a hard time sorting them out.  I'm guessing this is largely just a problem with gpt labels since they include additional information which causes more entries to be created in the same directory.

What do you think about this as a possible solution.  There already exists an environment variable called ZPOOL_IMPORT_PATH which can be set to specify the `zpool import` search paths.  It's analogous to specifying multiple `-d` options at import time and effectively just limits which devices are probed.  For example:

```
ZPOOL_IMPORT_PATH="/dev/disk/by-id" zpool import
```

We could add a ZPOOL_IMPORT_REGEX environment variable which could be used to provide further filtering.  For example, if you only wanted to match device names which started with `wwn` in the `/dev/disk/by-id` directory.

```
ZPOOL_IMPORT_PATH="/dev/disk/by-id" ZPOOL_IMPORT_REGEX="^wwn" zpool import
```

This could of course all be largely hidden by the init script but it would allow the end user more control over which devices were probed.  I'm guessing you don't have any issues if you just leave the wwn names in the `/dev/disk/by-id` directory and do the import.

**Comment by kpande** [comment]
that would be fine if all of my machines used similar hardware - I was hoping that zpool might learn to distinguish and not try to load the whole device if a partition on that device also contains a zpool. In theory, there shouldn't be a case of whole disk AND partition, the partition should win.

**Comment by behlendorf** [comment]
I don't follow, that should be the case today.  If we detect a vdev on a partition then there shouldn't be a valid label on the whole disk.  Although there may be pools on other partitions.  Isn't the issue you're hitting being cases by the fact that `wwn-X` and `scsi-X` end up referring to the same device?  Or have I misunderstood.

**Comment by kpande** [comment]
no - i think it handles that gracefully, it'll just end up using random device names. my issue specifically (according to dasjoe) is when a partition is created near the end of a disk (mine is < 10MiB away from the end) it's possible zpool could 'confuse' it as a whole disk label. I don't fully understand how that is possible, but it's enough to cause distress when attempting to use persistent labels.

**Comment by behlendorf** [comment]
Oh! Now I understand, yes that is a very different issue.  I can see how that could cause problems. Can you please try the #3206 patch I just proposed.  It adjusts the `zpool import` such that by default it requires that all 4 vdev labels exist.  This should weed out the bogus devices under a variety of circumstances.

**Comment by kpande** [comment]
Already building on an affected server :-) :+1:

**Comment by kpande** [comment]
now zpool properly ignores the bunk devices. thanks @behlendorf ! good job! this one was bothering quite a few people recently.

**Comment by kpande** [comment]
resolved by PR #3206

**Comment by behlendorf** [comment]
@kpande thanks for the quick verification.   There were a variety of issues which might be related to this we should make sure this patch addresses them too.  After pushing this patch I had two other thoughts which I'll probably explore to make this more robust.

* When checking all the labels in zpool_read_label() we should verify not only that they all exist but that they refer the to same guid.  Otherwise we may miss some bizarre but possible corner cases.

* It may make sense to automatically fall back to the `-l` behavior if no pools are detected.  The idea being ZFS should just do the right thing if possible.

**Comment by kpande** [comment]
i like that. i've had these machines in production for a couple years and it just now started working differently, the less modification to keep them running, the better

**Comment by sempervictus** [comment]
This should also help with SSDs which were once raw ZFS cache/slog devices, but were subsequently encrypted with dm-crypt and fed to the same/another pool. They still retain enough label to confuse the zpool command without that patch (havent tested yet, enthralled with KoT's ARC monstrosity @ present)...

Far as bizarre corner cases go, a lot of us create and destroy zpools for testing ZoL all the time - i'm sure we've made some fubar label conditions among the group, and the added consistency will only help to prevent false positive bug reports resulting from our own unsanitary lab conditions. :)

**Comment by FransUrbo** [comment]
Could this possibly be related to #3207?

**Comment by behlendorf** [comment]
@FransUrbo unrelated I suspect.
