### ISSUE TITLE
zpool destroy data -f does not work (permanently)

### ISSUE THREAD

**Issue by frankuit** [zfsonlinux/zfs#3150]
Hi Guys, 
i'm in the process of moving a pool (data) to a new piece of storage hardware and pool (backups).
i've done so with the zfs export and import functionality.
but now the old raid has crashed (disks broken) and i wanted to remove it.
when i remove it, no error is reported.
next, i reboot the server and there are no pools found.
so, i do: zpool import backups (as backups is the pool on the new hardware)
but then it also imports the old pool (data) again, output:

i've tried exporting it, and destroying it (even using -f) but it always comes back at next reboot, when i have to import it.
i also tried by deleting /etc/zfs/zpool.cache, but that didn't work either.
could this be a bug ?

Versions:
Debian wheezy amd64
ii  spl                                            0.6.3-1                            amd64        Commands to control the kernel modules
ii  zfs                                            0.6.3-9                            amd64        Commands to control the kernel modules and libraries

zpool status
  pool: backups
 state: ONLINE
  scan: none requested
config:

        NAME                                      STATE     READ WRITE CKSUM
        backups                                   ONLINE       0     0     0
          scsi-3600508b1001c77b1e985ba945cf1ddff  ONLINE       0     0     0
          scsi-3600508b1001c49cd37abb1470a1238e6  ONLINE       0     0     0
        cache
          sdb                                     ONLINE       0     0     0

errors: No known data errors

  pool: data
 state: UNAVAIL
status: One or more devices could not be used because the label is missing 
        or invalid.  There are insufficient replicas for the pool to continue
        functioning.
action: Destroy and re-create the pool from
        a backup source.
   see: http://zfsonlinux.org/msg/ZFS-8000-5E
  scan: none requested
config:

        NAME                                      STATE     READ WRITE CKSUM
        data                                      UNAVAIL      0     0     0  insufficient replicas
          scsi-3600508b1001cea2b7053a4acb29d1b5d  UNAVAIL      0     0     0
          scsi-3600508b1001c82122e091706bbc0f248  UNAVAIL      0     0     0
          scsi-3600508b1001cfd8ff229605deaa273c0  UNAVAIL      0     0     0
          scsi-3600508b1001c6bd805040b27df3b7ee9  UNAVAIL      0     0     0
          scsi-3600508b1001ce56089d3bd4da19d7ad7  UNAVAIL      0     0     0
          scsi-3600508b1001cdb8a7cc06b739000c78a  UNAVAIL      0     0     0
          scsi-3600508b1001c7d47003817d4cb01d9b0  UNAVAIL      0     0     0
          scsi-3600508b1001c7997fbd1be452d9a216a  UNAVAIL      0     0     0

**Comment by dasjoe** [comment]
Did you rebuild the initrd after destroying the pool?

If not, do so. Either export or destroy the pool data, then rebuild the initramfs:
```
zpool export data
update-initramfs -k all -u
```

**Comment by frankuit** [comment]
ok, trying this now, here's the output:

zpool status
  pool: backups
 state: ONLINE
  scan: none requested
config:

        NAME                                      STATE     READ WRITE CKSUM
        backups                                   ONLINE       0     0     0
          scsi-3600508b1001c77b1e985ba945cf1ddff  ONLINE       0     0     0
          scsi-3600508b1001c49cd37abb1470a1238e6  ONLINE       0     0     0
        cache
          sdb                                     ONLINE       0     0     0
          sdc1                                    ONLINE       0     0     0

errors: No known data errors

  pool: data
 state: UNAVAIL
status: One or more devices could not be used because the label is missing 
        or invalid.  There are insufficient replicas for the pool to continue
        functioning.
action: Destroy and re-create the pool from
        a backup source.
   see: http://zfsonlinux.org/msg/ZFS-8000-5E
  scan: none requested
config:

        NAME                                      STATE     READ WRITE CKSUM
        data                                      UNAVAIL      0     0     0  insufficient replicas
          scsi-3600508b1001cea2b7053a4acb29d1b5d  UNAVAIL      0     0     0
          scsi-3600508b1001c82122e091706bbc0f248  UNAVAIL      0     0     0
          scsi-3600508b1001cfd8ff229605deaa273c0  UNAVAIL      0     0     0
          scsi-3600508b1001c6bd805040b27df3b7ee9  UNAVAIL      0     0     0
          scsi-3600508b1001ce56089d3bd4da19d7ad7  UNAVAIL      0     0     0
          scsi-3600508b1001cdb8a7cc06b739000c78a  UNAVAIL      0     0     0
          scsi-3600508b1001c7d47003817d4cb01d9b0  UNAVAIL      0     0     0
          scsi-3600508b1001c7997fbd1be452d9a216a  UNAVAIL      0     0     0

:~# zpool destroy -f data
:~# update-initramfs -k all -u

ok, it seems gone now, so lets reboot and check again.
zpool list
NAME      SIZE  ALLOC   FREE    CAP  DEDUP  HEALTH  ALTROOT
backups  72.5T  49.9T  22.6T    68%  1.00x  ONLINE  -

Damn, it's back after a reboot:

zpool import backups
zpool status
  pool: backups
 state: ONLINE
  scan: none requested
config:

        NAME                                      STATE     READ WRITE CKSUM
        backups                                   ONLINE       0     0     0
          scsi-3600508b1001c77b1e985ba945cf1ddff  ONLINE       0     0     0
          scsi-3600508b1001c49cd37abb1470a1238e6  ONLINE       0     0     0
        cache
          sdb                                     ONLINE       0     0     0
          sdc1                                    ONLINE       0     0     0

errors: No known data errors

  pool: data
 state: UNAVAIL
status: One or more devices could not be used because the label is missing 
        or invalid.  There are insufficient replicas for the pool to continue
        functioning.
action: Destroy and re-create the pool from
        a backup source.
   see: http://zfsonlinux.org/msg/ZFS-8000-5E
  scan: none requested
config:

        NAME                                      STATE     READ WRITE CKSUM
        data                                      UNAVAIL      0     0     0  insufficient replicas
          scsi-3600508b1001cea2b7053a4acb29d1b5d  UNAVAIL      0     0     0
          scsi-3600508b1001c82122e091706bbc0f248  UNAVAIL      0     0     0
          scsi-3600508b1001cfd8ff229605deaa273c0  UNAVAIL      0     0     0
          scsi-3600508b1001c6bd805040b27df3b7ee9  UNAVAIL      0     0     0
          scsi-3600508b1001ce56089d3bd4da19d7ad7  UNAVAIL      0     0     0
          scsi-3600508b1001cdb8a7cc06b739000c78a  UNAVAIL      0     0     0
          scsi-3600508b1001c7d47003817d4cb01d9b0  UNAVAIL      0     0     0
          scsi-3600508b1001c7997fbd1be452d9a216a  UNAVAIL      0     0     0
root@jupiter:~# uptime
 17:03:40 up 1 min,  1 user,  load average: 0.72, 0.31, 0.12

I've tried the export and the destroy options.

**Comment by frankuit** [comment]
when i pass -v to the update-initramfs command, it tells me: nothing to do, exiting.

**Comment by dasjoe** [comment]
So the pool has some remnants on one of your drives, or it is stuck in your zpool.cache.
What does `zdb` (without parameters) output, when both pools are visible?

**Comment by frankuit** [comment]
zpool list -v
NAME   SIZE  ALLOC   FREE    CAP  DEDUP  HEALTH  ALTROOT
backups  72.5T  49.9T  22.6T    68%  1.00x  ONLINE  -
  scsi-3600508b1001c77b1e985ba945cf1ddff  36.2T  25.0T  11.3T         -
  scsi-3600508b1001c49cd37abb1470a1238e6  36.2T  25.0T  11.3T         -
cache      -      -      -      -      -      -
  sdb   149G  1.90M   149G         -
  sdc1  93.1G  2.17M  93.1G         -
data      -      -      -      -      -  FAULTED  -
  scsi-3600508b1001cea2b7053a4acb29d1b5d      -      -      -     16.0E
  scsi-3600508b1001c82122e091706bbc0f248      -      -      -     16.0E
  scsi-3600508b1001cfd8ff229605deaa273c0      -      -      -     16.0E
  scsi-3600508b1001c6bd805040b27df3b7ee9      -      -      -     16.0E
  scsi-3600508b1001ce56089d3bd4da19d7ad7      -      -      -     16.0E
  scsi-3600508b1001cdb8a7cc06b739000c78a      -      -      -     16.0E
  scsi-3600508b1001c7d47003817d4cb01d9b0      -      -      -     16.0E
  scsi-3600508b1001c7997fbd1be452d9a216a      -      -      -     16.0E


# zdb
backups:
    version: 5000
    name: 'backups'
    state: 0
    txg: 1064041
    pool_guid: 5297264370766593315
    errata: 0
    hostid: 279717526
    hostname: 'jupiter'
    vdev_children: 2
    vdev_tree:
        type: 'root'
        id: 0
        guid: 5297264370766593315
        children[0]:
            type: 'disk'
            id: 0
            guid: 250243637057757688
            path: '/dev/disk/by-id/scsi-3600508b1001c77b1e985ba945cf1ddff-part1'
            whole_disk: 1
            metaslab_array: 37
            metaslab_shift: 38
            ashift: 12
            asize: 40007519174656
            is_log: 0
            create_txg: 4
        children[1]:
            type: 'disk'
            id: 1
            guid: 16687454002057251955
            path: '/dev/disk/by-id/scsi-3600508b1001c49cd37abb1470a1238e6-part1'
            whole_disk: 1
            metaslab_array: 34
            metaslab_shift: 38
            ashift: 12
            asize: 40007519174656
            is_log: 0
            create_txg: 4
    features_for_read:

**Comment by frankuit** [comment]
i've moved the /etc/zfs/zpool.cache file as i stated earlier, so it should not come from there i think?

**Comment by GregorKopka** [comment]
Sounds like a stale /etc/zfs/zpool.cache in the **initrd**.

**Comment by frankuit** [comment]
any idea on how i can fix it ? as the normal initramfs update didn't work.

Regards,
Frank


2015-03-23 23:31 GMT+01:00 Gregor Kopka <notifications@github.com>:

> Sounds like a stale /etc/zfs/zpool.cache in the *initrd*.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zfsonlinux/zfs/issues/3150#issuecomment-85231990>.
>



-- 
Met vriendelijke groet,

Frank Uittenbosch

**Comment by frankuit** [comment]
I seem to have fixed this by re-creating the initramfs: # mkinitramfs -o /boot/initrd.img-3.2.0.4-amd64-new
copying that one over the old version and rebooting.
now i'm running the latest version of zfs again, and it's running fine now.

Thanks,
Frank
