### ISSUE TITLE
RHEL6: Pool not imported on boot

### ISSUE THREAD

**Issue by snajpa** [zfsonlinux/zfs#3153]
When rebooting a system, upon a new boot my zpool 'vz' is not imported. I suspect it's been doing so since the autoimport default was set to do not autoimport (which is a fairly recent change).

I've tried exporting the pool and importing it under different name, then exporting it again and importing back as 'vz', but that didn't help.

Manually running "zpool import vz" imports the pool with no issues, but I really have no clue why this doesn't happen automatically when zfs service starts.

I'm running SL6.6 and current git head of ZoL.

**Comment by behlendorf** [comment]
@snajpa thanks for noticing this, and I think you're right that's exactly when this broke.  Disabling the autoimport means that we're dependent on the systemd units or init scripts to import the pool.  It looks like the existing RHEL6 init script don't explicitly import the pool and relied on the autoimport behavior.  I'll try and post a fix for this shortly.

**Comment by behlendorf** [comment]
@snajpa could you please verify the proposed patch in #3154 resolves your issue.  Basically, I've replaced the RHEL init script with a slightly modified version of the LSB init script used on other platforms.  It works as expected in my initial minimal testing.  The only issue I noticed was that selinux denied the `zfs mount -a` for some reason on boot.  This may however probably has been a long standing issue.

**Comment by snajpa** [comment]
I'll deploy it today, since our machines are deadlocking and/or having serious memory issues on a daily basis I suspect I'll know rather soon (sigh :( ).

**Comment by behlendorf** [comment]
The updated init script has been merged.  In the process it was updated to automatically start the ZED.

**Comment by snajpa** [comment]
Excellent, I can now confirm it is working as expected. Thank you.
