### ISSUE TITLE
Ubuntu 14 LTS: Dataset not automatically mounting

### ISSUE THREAD

**Issue by telx85** [zfsonlinux/zfs#3170]
G'day guys,

I have an issue (bug) where ZFS is not mounting my dataset on boot up. Unfortunately it was working sweet and then I rebooted, thought I had lost everything, re-created my dataset and then found out I could have just done:

$ sudo zpool import -a

Anyway I didn't and so I lost it. But why doesn't the ZFS auto mount? 

OS = Ubuntu 14.04 LTS
HDD = 2x 3TB SE Western Digital SATA drives

user@test:/mnt$ dpkg -l \* | grep ubuntu-zfs
ii  ubuntu-zfs       8~trust        amd64        Native ZFS filesystem metapackage for Ubuntu.

Here is what I did to create my data set:

$ sudo zpool create -f backup1 mirror /dev/sdb /dev/sdc
$ sudo zfs create backup1/backup
$ sudo zfs create backup1/downloads
$ sudo zfs create backup1/vms
$ sudo zfs set mountpoint=/mnt/backup1 backup1

Everything looks sweet, but every time I reset I need to import the dataset again.

Any ideas guys?

regards,
Steve

**Comment by Bronek** [comment]
You forgot to set cachefile , I think it's not set by default.

**Comment by telx85** [comment]
Just tried and no go.

$ sudo zpool set cachefile=/etc/zfs/zpool.cache

It then creates an unreadable file (maybe by design although I wouldn't think so) - see attached

![zpool cache](https://cloud.githubusercontent.com/assets/2740134/6609889/e87387d0-c892-11e4-8ed4-3f59b7279c17.png)

**Comment by pmoroney** [comment]
I am having a problem that may be similar.
My initrd is calling the following command:
mount -t zfs -o zfsutil rootssd/ROOT/gentoo /mnt/root
And I am getting a "filesystem 'rootssd/ROOT/gentoo' cannot be mounted, unable to open the dataset" error
If I do a "zpool import rootssd -R /mnt/root" instead, it works perfectly.
I have verified that I have a good cache file.

**Comment by telx85** [comment]
Hmmm, I'm a bit of a noob so I don't even know how you find what your initrd is calling.

The work around that I currently have (probably completely wrong and bad and will kill my neighbours cats) is this in my crontab

@reboot sudo zpool import -a >> /dev/null

**Comment by behlendorf** [comment]
Closing, as a support issue.
