### ISSUE TITLE
systemd init scripts are not installed using the ubuntu zol ppa

### ISSUE THREAD

**Issue by samvde** [zfsonlinux/zfs#3173]
I am testdriving systemd on Ubuntu 15.04 with zfs as root filesystem. The system works great, however it seems the systemd initscripts are not installed on my system, leaving one zpool exported and a few filesystems unmounted at boot. This worked fine with upstart.

When looking at the dkms folders I can see the scripts were pulled correctly from git (at least I assume that's why the're there):
ll /var/lib/dkms/zfs/0.6.3.0/build/etc/systemd/system
total 58
drwxr-xr-x 2 root root 11 mrt 10 22:32 ./
drwxr-xr-x 3 root root  5 mrt 10 22:32 ../
-rw-r--r-- 1 root root  6 mrt 10 22:30 50-zfs.preset.in
-rw-r--r-- 1 root root  6 mrt 10 22:32 Makefile
-rw-r--r-- 1 root root  6 mrt 10 22:30 Makefile.in
-rw-r--r-- 1 root root  6 mrt 10 22:30 zed.service.in
-rw-r--r-- 1 root root  6 mrt 10 22:30 zfs-import-cache.service.in
-rw-r--r-- 1 root root  6 mrt 10 22:30 zfs-import-scan.service.in
-rw-r--r-- 1 root root  6 mrt 10 22:30 zfs-mount.service.in
-rw-r--r-- 1 root root  6 mrt 10 22:30 zfs-share.service.in
-rw-r--r-- 1 root root  6 mrt 10 22:30 zfs.target.in

I can test things to help out, however I have no developer skills (automake/make/autoconfigure/...). E.g. I have no idea if I could deploy those files manually to test.

edit: logged launchpad systemd: https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1431523

**Comment by FransUrbo** [comment]
This belong to the https://github.com/zfsonlinux/pkg-zfs repo, NOT this repo.

**Comment by samvde** [comment]
Yes you are of course right, I'll try to fix it.

**Comment by samvde** [comment]
Close: move to correct repo.
