### ISSUE TITLE
Potential data abort issue (memory access over @oend by @ref and @op) during lz4 decompress with corrupted or invalid compression data

### ISSUE THREAD

**Issue by kernelOfTruth** [zfsonlinux/zfs#3176]
JeHyeon (Tom) Yeon from windriver.com found out, if compression
data was corrupted or altered in any way to be invalid,
this could lead to memory accesses over @oend by @ref and @op

Below is his lkml message and link:

If the part of the compression data are corrupted, or the compression
data is totally fake, the memory access over the limit is possible.

This is the log from my system usning lz4 decompression.
   [6502]data abort, halting
   [6503]r0  0x00000000 r1  0x00000000 r2  0xdcea0ffc r3  0xdcea0ffc
   [6509]r4  0xb9ab0bfd r5  0xdcea0ffc r6  0xdcea0ff8 r7  0xdce80000
   [6515]r8  0x00000000 r9  0x00000000 r10 0x00000000 r11 0xb9a98000
   [6522]r12 0xdcea1000 usp 0x00000000 ulr 0x00000000 pc  0x820149bc
   [6528]spsr 0x400001f3
and the memory addresses of some variables at the moment are
    ref:0xdcea0ffc, op:0xdcea0ffc, oend:0xdcea1000
As you can see, COPYLENGH is 8bytes, so @ref and @op can access the momory
over @oend.

Signed-off-by: tom.yeon <tom.yeon@windriver.com>

https://lkml.org/lkml/2015/3/12/139

**Comment by kernelOfTruth** [comment]
Seemingly in connection with the patch in the pull request applied - data occured in some places of my local filesystem [data and metadata corruption]

which could be fixed by scrub/resilvering

I'm not sure if those were caused solely by that patch or some other was behind it

Anyway: there's a potential problem and there should be a way to fix it

**Comment by ryao** [comment]
Corruption should cause a checksum failure, which would prevent this from happening. Bit flips and hypothetical software bugs that cause the memory buffer to get clobbered would be able to race with the checksum calculation, which would allow this to happen. Specifically, before the checksum is calculated on writes and after the checksum is calculated on reads. I consider the risk here to be equivalent to being subject multiple lightning strikes, but we probably should patch this in the 0.6.5 release as a preventative measure.

**Comment by kernelOfTruth** [comment]
@ryao thanks for passing by ! - I agree, it's low priority given that there was no relating issue posted yet or no reports of such kind have been posted in the mailing list

what baffles me  is the following:

```
zpool status 
  pool: WD30EFRX
 state: ONLINE
status: One or more devices has experienced an error resulting in data
	corruption.  Applications may be affected.
action: Restore the file in question if possible.  Otherwise restore the
	entire pool from backup.
   see: http://zfsonlinux.org/msg/ZFS-8000-8A
  scan: scrub in progress since Fri Mar 13 13:37:38 2015
    601G scanned out of 1.93T at 67.2M/s, 5h48m to go
    0 repaired, 30.45% done
config:

	NAME              STATE     READ WRITE CKSUM
	WD30EFRX          ONLINE       0     0     0
	  mirror-0        ONLINE       0     0     0
	    wd30efrx      ONLINE       0     0     0
	    wd30efrx_002  ONLINE       0     0     0

errors: 128 data errors, use '-v' for a list
```

I'm not sure if there were no checksum errors at all and still corruption 
because I did several tests (and thus reboots) which lead to reset of the checksum error counter (but experience from the past tells me that it should be persistent)

or there's something deeper underneath all this

This PC does have ECC Ram, I'll take a look if other parts are playing tricks on me

```
edac-util -v -r
mc0: 0 Uncorrected Errors with no DIMM info
mc0: 0 Corrected Errors with no DIMM info
mc0: csrow0: 0 Uncorrected Errors
mc0: csrow0: mc#0csrow#0channel#0: 0 Corrected Errors
mc0: csrow0: mc#0csrow#0channel#1: 0 Corrected Errors
mc0: csrow1: 0 Uncorrected Errors
mc0: csrow1: mc#0csrow#1channel#0: 0 Corrected Errors
mc0: csrow1: mc#0csrow#1channel#1: 0 Corrected Errors
mc0: csrow2: 0 Uncorrected Errors
mc0: csrow2: mc#0csrow#2channel#0: 0 Corrected Errors
mc0: csrow2: mc#0csrow#2channel#1: 0 Corrected Errors
mc0: csrow3: 0 Uncorrected Errors
mc0: csrow3: mc#0csrow#3channel#0: 0 Corrected Errors
mc0: csrow3: mc#0csrow#3channel#1: 0 Corrected Errors
edac-util: No errors to report.
```

Thanks !

**Comment by tuxoko** [comment]
@kernelOfTruth 
See my comments in #3177

**Comment by behlendorf** [comment]
Closing.  Explained in #3177.
