### ISSUE TITLE
0.6.3-235_g7f3e466 

### ISSUE THREAD

**Issue by malexandvsc** [zfsonlinux/zfs#3184]
zfs bleeding, test new 649T nested raidz3 pool, approx. 100 concurrent rsync processes over nfs exports, local nfs imports; no ZIL/L2ARC disks, no compression 

symptoms: nfs exports stuck, running local rsync process stuck, new file create/delete ok
peculiarity: zpool in 178 lsi megaraid 0 disks (not jbod)

currently re-running with
vm.min_free_kbytes 512MB 
options zfs zfs_arc_max 128GB (half RAM)

[   13.495509] CPU: 9 PID: 4202 Comm: zpool Tainted: PF          O--------------   3.10.0-123.20.1.el7.x86_64 #1
[   13.495510] Hardware name: Supermicro X9DRX+-F/X9DRX+-F, BIOS 3.0a 12/06/2013
[   13.495511]  00000000000042d0 0000000079072274 ffff881fc440bc00 ffffffff815e2b0c
[   13.495514]  ffff881fc440bc38 ffffffffa00fdb21 ffff883fa9a92000 0000000000000000
[   13.495517]  ffff883fd0791dc0 0000000000000000 ffff883fc8833da0 ffff881fc440bcf0
[   13.495519] Call Trace:
[   13.495523]  [<ffffffff815e2b0c>] dump_stack+0x19/0x1b
[   13.495529]  [<ffffffffa00fdb21>] spl_kmem_alloc+0x131/0x1b0 [spl]
[   13.495551]  [<ffffffffa0524c45>] spa_config_sync+0x235/0x660 [zfs]
[   13.495575]  [<ffffffffa0104a8c>] ? cv_wait_common+0x10c/0x190 [spl]
[   13.495578]  [<ffffffff81086ac0>] ? wake_up_bit+0x30/0x30
[   13.495583]  [<ffffffffa0104b25>] ? __cv_wait+0x15/0x20 [spl]
[   13.495602]  [<ffffffffa0525184>] spa_config_update+0x114/0x120 [zfs]
[   13.495623]  [<ffffffffa052515a>] spa_config_update+0xea/0x120 [zfs]
[   13.495643]  [<ffffffffa0520f9e>] spa_import+0x61e/0x830 [zfs]
[   13.495665]  [<ffffffffa05557a4>] zfs_ioc_pool_import+0x104/0x150 [zfs]
[   13.495686]  [<ffffffffa0559026>] zfsdev_ioctl+0x476/0x4b0 [zfs]
[   13.495690]  [<ffffffff811c2c85>] do_vfs_ioctl+0x2e5/0x4c0
[   13.495693]  [<ffffffff811c2f01>] SyS_ioctl+0xa1/0xc0
[   13.495695]  [<ffffffff815f3219>] system_call_fastpath+0x16/0x1b
[   14.045017] Large kmem_alloc(57044, 0x0), please file an issue at:
https://github.com/zfsonlinux/zfs/issues/new
[   14.045022] CPU: 17 PID: 5856 Comm: spa_async Tainted: PF          O--------------   3.10.0-123.20.1.el7.x86_64 #1
[   14.045023] Hardware name: Supermicro X9DRX+-F/X9DRX+-F, BIOS 3.0a 12/06/2013
[   14.045024]  00000000000042d0 000000006de3d17f ffff883f8c59fd18 ffffffff815e2b0c
[   14.045028]  ffff883f8c59fd50 ffffffffa00fdb21 ffff883fa9a92000 0000000000000000
[   14.045031]  ffff883fd0791dc0 0000000000000000 ffff881fcc9fdfc0 ffff883f8c59fe08
[   14.045034] Call Trace:
[   14.045040]  [<ffffffff815e2b0c>] dump_stack+0x19/0x1b
[   14.045054]  [<ffffffffa00fdb21>] spl_kmem_alloc+0x131/0x1b0 [spl]
[   14.045086]  [<ffffffffa0524c45>] spa_config_sync+0x235/0x660 [zfs]
[   14.045092]  [<ffffffffa0104a8c>] ? cv_wait_common+0x10c/0x190 [spl]
[   14.045095]  [<ffffffff81086ac0>] ? wake_up_bit+0x30/0x30
[   14.045100]  [<ffffffffa0104b25>] ? __cv_wait+0x15/0x20 [spl]
[   14.045120]  [<ffffffffa0525184>] spa_config_update+0x114/0x120 [zfs]
[   14.045139]  [<ffffffffa05231b7>] spa_async_thread+0x2f7/0x430 [zfs]
[   14.045157]  [<ffffffffa0522ec0>] ? spa_vdev_resilver_done+0x140/0x140 [zfs]
[   14.045162]  [<ffffffffa00ffcaa>] thread_generic_wrapper+0x7a/0x90 [spl]
[   14.045167]  [<ffffffffa00ffc30>] ? __thread_exit+0x20/0x20 [spl]
[   14.045169]  [<ffffffff81085aff>] kthread+0xcf/0xe0
[   14.045171]  [<ffffffff81085a30>] ? kthread_create_on_node+0x140/0x140
[   14.045174]  [<ffffffff815f316c>] ret_from_fork+0x7c/0xb0
[   14.045176]  [<ffffffff81085a30>] ? kthread_create_on_node+0x140/0x140
[   14.056138] Large kmem_alloc(57044, 0x0), please file an issue at:
https://github.com/zfsonlinux/zfs/issues/new
[   14.056141] CPU: 2 PID: 5856 Comm: spa_async Tainted: PF          O--------------   3.10.0-123.20.1.el7.x86_64 #1
[   14.056142] Hardware name: Supermicro X9DRX+-F/X9DRX+-F, BIOS 3.0a 12/06/2013
[   14.056143]  00000000000042d0 000000006de3d17f ffff883f8c59fcd8 ffffffff815e2b0c
[   14.056147]  ffff883f8c59fd10 ffffffffa00fdb21 ffff883fa9a92000 0000000000000000
[   14.056149]  ffff883fd0791dc0 0000000000000000 ffff881fcde89340 ffff883f8c59fdc8
[   14.056152] Call Trace:
[   14.056155]  [<ffffffff815e2b0c>] dump_stack+0x19/0x1b
[   14.056162]  [<ffffffffa00fdb21>] spl_kmem_alloc+0x131/0x1b0 [spl]
[   14.056184]  [<ffffffffa0524c45>] spa_config_sync+0x235/0x660 [zfs]
[   14.056189]  [<ffffffffa0104a8c>] ? cv_wait_common+0x10c/0x190 [spl]
[   14.056192]  [<ffffffff81086ac0>] ? wake_up_bit+0x30/0x30
[   14.056196]  [<ffffffffa0104b25>] ? __cv_wait+0x15/0x20 [spl]
[   14.056216]  [<ffffffffa0525184>] spa_config_update+0x114/0x120 [zfs]
[   14.056234]  [<ffffffffa052515a>] spa_config_update+0xea/0x120 [zfs]
[   14.056252]  [<ffffffffa05231b7>] spa_async_thread+0x2f7/0x430 [zfs]
[   14.056270]  [<ffffffffa0522ec0>] ? spa_vdev_resilver_done+0x140/0x140 [zfs]
[   14.056274]  [<ffffffffa00ffcaa>] thread_generic_wrapper+0x7a/0x90 [spl]
[   14.056279]  [<ffffffffa00ffc30>] ? __thread_exit+0x20/0x20 [spl]
[   14.056281]  [<ffffffff81085aff>] kthread+0xcf/0xe0
[   14.056283]  [<ffffffff81085a30>] ? kthread_create_on_node+0x140/0x140
[   14.056285]  [<ffffffff815f316c>] ret_from_fork+0x7c/0xb0
[   14.056287]  [<ffffffff81085a30>] ? kthread_create_on_node+0x140/0x140

modinfo zfs
filename:       /lib/modules/3.10.0-123.20.1.el7.x86_64/extra/zfs.ko
version:        0.6.3-235_g7f3e466
license:        CDDL
author:         OpenZFS on Linux
description:    ZFS
srcversion:     58284D0B1ADCBBC01A26602
...

zfs get all
NAME                     PROPERTY              VALUE                     SOURCE
tank1ST                  type                  filesystem                -
tank1ST                  creation              Fri Mar 13 23:01 2015     -
tank1ST                  used                  34.6T                     -
tank1ST                  available             430T                      -
tank1ST                  referenced            291K                      -
tank1ST                  compressratio         1.00x                     -
tank1ST                  mounted               yes                       -
tank1ST                  quota                 none                      default
tank1ST                  reservation           none                      default
tank1ST                  recordsize            128K                      default
tank1ST                  mountpoint            /tank1ST                  default
tank1ST                  sharenfs              off                       default
tank1ST                  checksum              on                        default
tank1ST                  compression           off                       local
tank1ST                  atime                 off                       local
tank1ST                  devices               on                        default
tank1ST                  exec                  on                        default
tank1ST                  setuid                on                        default
tank1ST                  readonly              off                       default
tank1ST                  zoned                 off                       default
tank1ST                  snapdir               hidden                    default
tank1ST                  aclinherit            restricted                default
tank1ST                  canmount              on                        default
tank1ST                  xattr                 sa                        local
tank1ST                  copies                1                         default
tank1ST                  version               5                         -
tank1ST                  utf8only              off                       -
tank1ST                  normalization         none                      -
tank1ST                  casesensitivity       sensitive                 -
tank1ST                  vscan                 off                       default
tank1ST                  nbmand                off                       default
tank1ST                  sharesmb              off                       default
tank1ST                  refquota              none                      default
tank1ST                  refreservation        none                      default
tank1ST                  primarycache          all                       default
tank1ST                  secondarycache        all                       default
tank1ST                  usedbysnapshots       0                         -
tank1ST                  usedbydataset         291K                      -
tank1ST                  usedbychildren        34.6T                     -
tank1ST                  usedbyrefreservation  0                         -
tank1ST                  logbias               latency                   default
tank1ST                  dedup                 off                       local
tank1ST                  mlslabel              none                      default
tank1ST                  sync                  standard                  local
tank1ST                  refcompressratio      1.00x                     -
tank1ST                  written               291K                      -
tank1ST                  logicalused           34.4T                     -
tank1ST                  logicalreferenced     10.5K                     -
tank1ST                  snapdev               hidden                    default
tank1ST                  acltype               off                       default
tank1ST                  context               none                      default
tank1ST                  fscontext             none                      default
tank1ST                  defcontext            none                      default
tank1ST                  rootcontext           none                      default
tank1ST                  relatime              off                       default
tank1ST                  redundant_metadata    all                       default
tank1ST                  overlay               off                       default

systemctl -t service -a|grep zfs
zfs-import-cache.service                                                                  loaded active   exited  Import ZFS pools by cache file
zfs-import-scan.service                                                                   loaded inactive dead    Import ZFS pools by device scanning
zfs-mount.service                                                                         loaded active   exited  Mount ZFS filesystems
zfs-share.service                                                                         loaded active   exited  ZFS file system shares

**Comment by kpande** [comment]
May be some fixes coming in #3050 and #3183 

Does this occur with ZFS pre-kmem rework?

**Comment by malexandvsc** [comment]
assuming that it relates to deadlock stalled allocation requests - can a list of locks be dumped cyclically?

2nd run went longer (approx. 8 vs. 4 hours) until no more I/O from existing processes visible with zpool iostat. Not tested with pre-kmem. 

I/O seems to pause cyclically - similar to flushing pages behaviour. Both the period between 0 reported pool iostat and the duration of the phases seems to increase until staying at 0.  

Restarted without changes, if there is a patch to try that would be great.

**Comment by behlendorf** [comment]
@malexandvsc could you fully describe your workload.  You mention you're running many concurrent rsyncs over NFS.  I assume ZoL is running on the NFS server side, is rsync running on the client?  Are you rsyncing a large number of small or large files?  Is the rsync removing and creating files?  etc.  This sounds a lot like #3181 but any detail you could help provide would be useful.

**Comment by malexandvsc** [comment]
Well - for the last 4 days it was running rsync flawlessly in respect to zfs (_no change to the last failure run above) with about 95M files in 70TB ingested.  

rsync is currently creating/reading (directory traversal), no delete about 100 instances. A patched version of rsync is used that does posix_fadvise64 so not to use the Linux page-cache.  

rsync-vsc -avrH --sockopts=SO_SNDBUF=8388608,SO_RCVBUF=8388608--stats --progress --whole-file --no-owner --no-group <> <>

in addition another machine on 0.6.3-238_ge023409 is doing the same with so far 8TB small files with no issues.

**Comment by kernelOfTruth** [comment]
@malexandvsc could you point to that patch, please ?

or is it the one from http://insights.oetiker.ch/linux/fadvise/ ?

this might help folks that suffer from metadata in ARC exploding

**Comment by malexandvsc** [comment]
indeed the Oetiker fadvise patch

**Comment by malexandvsc** [comment]
well the issue seems to coincide with rsync file traversals (approx. 650 million files, which is certainly envelope). Once the diffs have been established, copy works fine without any stuck rsync processes. Yet, during the diff-ing the deadlock-type behavior described on top seems to occur. Re-tried with 0.6.3-245_gbc88866.

**Comment by malexandvsc** [comment]
1.6TB SSD for L2ARC, ZIL and native HBAs added for more runs

**Comment by malexandvsc** [comment]
so far no changes, even 20M directory traverses single processes seem to trigger it

**Comment by kernelOfTruth** [comment]
@malexandvsc thanks - I'll give that patched rsync a try

some of the locks are being tracked at #3183 

@dweeezil has mentioned a bunch of fixes in https://github.com/zfsonlinux/zfs/issues/3183#issuecomment-81352438 ( https://github.com/dweeezil/zfs/commit/f04f972 ) - perhaps those can help you

**Comment by malexandvsc** [comment]
I did not see the behavior again with another approx. 80TB written. Changes relative to the initial post: only a handful concurrent rsync processes, HBAs instead of raid controllers and large L2ARC/ZIL SDD albeit the latter 2 are unlikely to be related.

**Comment by behlendorf** [comment]
Closing this is believed to be resolved in the 0.6.5.x series.
