### ISSUE TITLE
fileset says mounted when it is not

### ISSUE THREAD

**Issue by kpande** [zfsonlinux/zfs#3186]
I just had an interesting issue where I couldn't mount or unmount a fileset. The fileset is /var/www and it had "overlay=on" when this issue showed up after a reboot. 

I noticed Nagios said '404' for my server, and that I couldn't mount/unmount/change the mount properties: https://gist.github.com/kpande/6692fe231e16e10b7dfd

It says the filesystem is mounted _and_ it is listed in mtab, but the filesystem _wasn't_ mounted. My /etc/mtab was originally a symlink to /proc/self/mounts and so to try to access my data I unlinked mtab and created it as a file without the /var/www line in it. I was then able to mount and access it.

**Comment by kpande** [comment]
I'll test sending this to a different pool using -p tomorrow and see if the issue transfers with the snapshot properties. Using send/recv without -p allowed me to 'repair' the dataset.

**Comment by behlendorf** [comment]
Do you happen to check `/proc/mounts` as well?  As you know `/etc/mtab` is just a cached copy of mounted filesystems and it is possible for it to be out of date.  If it is zfs may not mount on unmount properly.

**Comment by kpande** [comment]
/proc/mounts was also incorrect. that's why i had to unlink /etc/mtab so the zfs userland tools didn't think the fileset was mounted, otherwise I couldn't change "mountpoint" or "canmount" properties - the box was in a bit of a pickle. this issue has cropped up a couple times recently, all relating to overlay support.

**Comment by kpande** [comment]
the reason I filed this as a bug is precisely because /proc/self/mounts was incorrect and showed a filesystem as mounted, when it wasn't.. and it was rather difficult to actually access or repair the filesystem without doing send / recv.

I still have access to the affected filesets - when I did the send/recv, I left the originals in a ZPL called "borked" so they could be investigated later.

**Comment by kpande** [comment]
@nedbass have you looked into this?

**Comment by GregorKopka** [comment]
Having looked through the code, the only difference between overlay mount and normal one seems to be the check for an empty mountpoint at https://github.com/zfsonlinux/zfs/blob/2b54cb14517b8b3877716dbe02fe75f12a47eb5e/lib/libzfs/libzfs_mount.c#L471 

So my guess is the problem with the desynced mtab and /proc/mounts comes from https://github.com/zfsonlinux/zfs/blob/2b54cb14517b8b3877716dbe02fe75f12a47eb5e/lib/libzfs/libzfs_mount.c#L290 failing in a way that there is no error reported but the filesystem hasn't been really mounted, leading to https://github.com/zfsonlinux/zfs/blob/2b54cb14517b8b3877716dbe02fe75f12a47eb5e/lib/libzfs/libzfs_mount.c#L518 creating (or adding to) the confusion.

Is the problem still reproducible?

**Comment by gmelikov** [comment]
Closing as stale. Feel free to reopen it if it's reproducible on latest stable.
