### ISSUE TITLE
Manually creating /dev/zd* node for a zvol with zvol_inhibit_dev=1.

### ISSUE THREAD

**Issue by Pentium100MHz** [zfsonlinux/zfs#3198]
Hello, is there a way to manually create a node for a particular zvol when the zvol_inhibit_dev is set to 1?

The reason is twofold:
1. Since we use zvols as VM storage, we expect to have a lot of them, especially in the backup server. A lot of zvols slows down the server and in the backup server the /dev/zd\* nodes are only useful once in a while (when there is a need to recover some info).
2. When we are doing zfs send | zfs recv to copy a dataset with zvols to another hypervisor, the copying sometimes fails with an error "dataset is busy" - this may be because the kernel tries to read the zvol (for partitions etc) during the zfs recv operation.

Now, I have set zvol_inhibit_dev to 1, created a zvol, then set zvol_inhibit_dev to zero and created another zvol. The second zvol is visible in /dev/, is there a way to make the first zvol visible without rebooting the server or removing/inserting the zfs module?

**Comment by edillmann** [comment]
Hello Pentium100MHz,

You could clone it.

**Comment by Pentium100MHz** [comment]
Thanks, this solves the first problem.

**Comment by gmelikov** [comment]
Closing as stale.
