### ISSUE TITLE
zio_injection_enabled should not be a module option

### ISSUE THREAD

**Issue by thegreatgazoo** [zfsonlinux/zfs#3199]
The zio_inject.c seems to keep <code>zio_injection_enabled</code> as a counter of fault handlers. Maybe I missed something but it doesn't make much sense to give userspace control of its value. For example:
- If user sets <code>options zfs zio_injection_enabled=-1</code>, then adds a fault handler by calling <code>zinject</code>, then <code>zio_inject_fault()</code> would increase  <code>zio_injection_enabled</code> to 0, which essentially disables the fault handler.
- <code>options zfs zio_injection_enabled=0</code> may give the impression that fault injection is disabled, but it'd still work by running the zinject tool.

Also, the following symbols were exported from zio.c:
```
EXPORT_SYMBOL(zio_injection_enabled);
EXPORT_SYMBOL(zio_inject_fault);
EXPORT_SYMBOL(zio_inject_list_next);
EXPORT_SYMBOL(zio_clear_fault);
EXPORT_SYMBOL(zio_handle_fault_injection);
EXPORT_SYMBOL(zio_handle_device_injection);
EXPORT_SYMBOL(zio_handle_label_injection);
```
But they were actually defined in zio_inject.c. It seemed that zio_inject.c would be the right place to export them.

**Comment by behlendorf** [comment]
@thegreatgazoo you're right, I was clearly overzealous when I added this module option and exported these.  It would be great if you could propose a patch which.

* Removes the ` zio_injection_enabled` module option.
* Removes the `zio_injection_enabled` section from `man/man5/zfs-module-parameters.5`
* Moves the EXPORT_SYMBOLs to the correct place.

**Comment by thegreatgazoo** [comment]
Thanks for confirming. Patch to come shortly.
