### ISSUE TITLE
bad error : disappearing / reappearing file visibility 

### ISSUE THREAD

**Issue by tom71** [zfsonlinux/zfs#3224]
We have the problem, that files are shown as "No such file or directory", when we try to access them. After a few access tries, they are accessible again. This error is shown locally and via nfs. The error happens after about 10 hours of run time of our software. As we have lots of data, we cannot provide a reproducer script on its own. But we have created a test zfs pool now and try to shorten the time til the errror occurs to a range of minutes. We try to accomplish this by raising the work load by a factor of 10. We will also run zdb -ddddd on the test pool before and after the error. 
We can provide a login to our machines, so developpers can gather more information.

**Comment by behlendorf** [comment]
@tom71 if you could provide a reproducer of the issue that would be the most helpful.  It would also be helpful to know what version of ZFS you're able to reproduce this issue on.

**Comment by kpande** [comment]
From the mailing list:

http://list.zfsonlinux.org/pipermail/zfs-discuss/2015-March/000356.html

**Comment by tom71** [comment]
We are working hard on a reproducer. For our current software it takes 
about 10 hours for the error to occur. We multiplied the workload by 10 
in order to force the error earlier. But we have loads of data, we work 
on. It is difficult to construct a reproducer without the data. We are 
using ubuntu-zfs 8 trusty. Kernel is 3.13.0-39-generic. We made a 
special zfs test pool, where we put the data. We ran zdb -ddddd testpool 
before the run of the software and will run the same command after that. 
Are there other commands ,we should run with zdb ? We can provide a test 
account on our machines.

On 25.03.2015 19:40, Brian Behlendorf wrote:
>
> @tom71 <https://github.com/tom71> if you could provide a reproducer of 
> the issue that would be the most helpful. It would also be helpful to 
> know what version of ZFS you're able to reproduce this issue on.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/zfsonlinux/zfs/issues/3224#issuecomment-86163880>.
>

-- 
Dipl.-Ing. Thomas Grossmann
Chair for Clinical Bioinformatics
Saarland University, University Hospital
Building E2.1
66123 Saarbrücken, Germany
Ph. +49 681 302 68603

**Comment by tom71** [comment]
What we found out:

On our machines main2, main3 and main4.

If we create a file e.g. test.txt. We edit the file e.g. insert a line "echo 2222". Save the file. do a "ls" on the file. Works. Change the file e.g. add a line "echo 3333" save the file. Do a ls. Does not work. "No such file or directory. Before we had the file systems local and via nfs and the error occured. Now we have only nfs mounts and the error still occurs. 
The error does not always show up.

I can provide a login to our servers. Please mail to thomas.grossmann@ccb.uni-saarland.de for the login data. 

Thomas

**Comment by tom71** [comment]
It is hard to generate a reproducer, because the cause of the failure is mostly editing a file, saving it, then it is not there. Then it is there again. 
We have a new case: a python script is changed. Then it is saved and executed. The interpreter in that script is not found. The python interpreter is on an ext4 file system. Maybe this error gives you more ideas. We have not had any problems like that when being purely on ext4 on all file systems. This happened exactly  when we introduced zfs. Is there a problem with zfs <-> vfs operation ?
After executing the script a second time everything is fine. 
We will update to the 0.6.4 zfs release soon. Hopefully we get an improvement here.

**Comment by tom71** [comment]
This the file after editing it:

ls -la in the dir
 
-?????????  ? ?      ?        ?             ? xxxxx

try that again and it works.

**Comment by tom71** [comment]
editing file y:

test10@main2:~$ ls y
ls: cannot access y: File exists

again: works

test10@main2:~$ ls g
ls: cannot access g: No such file or directory

again: works

**Comment by kpande** [comment]
From the ML (oystr@cs.washington.edu): 
```
We have observed this behavior also.  The following patch (originally
posted in November 2014) resolved the situation for us:

--------------------------

Questionable behavior of ZFS with NFS

There seems to be a annoying problem using NFSv4 to access ZFS file systems
under certain circumstances.  It's easily reproduced by:

	nfs_client1:  mount server:/export /mnt
	nfs_client1:  cd /mnt
	nfs_client1:  echo foo >junk
	nfs_client1:  cat junk
	foo

Now on a different NFSv4 client:

	nfs_client2:  mount server:/export /mnt
	nfs_client2:  cd /mnt
	nfs_client2:  vi junk
	# Make some changes to /mnt/junk and save
	# This change the inode associated with /mnt/junk

Now back to the original client:

	nfs_client1:  cat junk
	cat: junk: No such file or directory

Admittedly NFSv4 is not advertised as a cluster file system that maintains
a completely coherent view of data across multiple nodes.  But it does
have some mechanisms built in that try to deal with situations like the
above.  Namely, it employs specialized file handle lookup routines that return
ESTALE when a file handle contains a nonexistant inode value.  The ESTALE
return triggers a return full file path lookup from the client to determine
if the file has actually gone away or if the cached file handle is no
longer valid.  ZFS behavior can be brought into line with other file
systems (e.g., ext4) by applying the following patch:

--- zfs-0.6.3/module/zfs/zpl_export.c_orig	2014-10-20 16:48:59.000000000 -0700
+++ zfs-0.6.3/module/zfs/zpl_export.c	2014-11-24 15:06:09.617436690 -0800
@@ -96,8 +96,22 @@
 
 	rc = zfs_vget(sb, &ip, fid);
 
-	if (rc != 0)
+	if (rc != 0) {
+		/*
+		 * If we see ENOENT it might mean that an NFSv4 client
+		 * is using a cached inode value in a file handle and
+		 * that the sought after file has had its inode changed
+		 * by a third party.  So change the error to ESTALE
+		 * which will trigger a full lookup by the client and
+		 * will find the new filename/inode pair if it still
+		 * exists.
+		 */
+		if ( rc == ENOENT ) {
+			printk(KERN_INFO "zpl_fh_to_dentry: changing ENOENT to ESTALE\n");
+			return (ERR_PTR(-ESTALE));
+		}
 		return (ERR_PTR(-rc));
+	}
 
 	ASSERT((ip != NULL) && !IS_ERR(ip));
 
Don't know if anybody cares about this or if such would be reading this
list, but I just thought I would point out the problem.
```

**Comment by tom71** [comment]
Thanks a lot for the patch. Our next maintenance is next week. I have already prepared the servers and looking forward to run the machines with it.

**Comment by jorg85** [comment]
patch works with Version 0.6.4.1, starting on line 105 in module/zfs/zpl_export.c

But on step "Now back to the original client:" within ca. 10 sec i will see:

nfs_client1:  cat junk
cat: junk: File exists

After about 10 sec the error is gone away and cat shows the content of junk.

**Comment by behlendorf** [comment]
@kpande thanks for posting this from the list.  I've opened pull request #3404 to get some review and feedback on this proposed fix.
