### ISSUE TITLE
Strange behaviour of *ratio attribute in zfs get all command

### ISSUE THREAD

**Issue by maxkorki** [zfsonlinux/zfs#3228]
Hi,
I was writing dd if=/dev/zero on dataset with compression. I noticed that compressratio doesn't change:

ls -alh
-rw-r--r-- 1 root root 4.0G Feb  3 14:20 plik1
-rw-r--r-- 1 root root 4.0G Feb  3 14:21 plik10
-rw-r--r-- 1 root root 4.0G Feb  3 14:21 plik11
-rw-r--r-- 1 root root 4.0G Feb  3 14:21 plik12
-rw-r--r-- 1 root root 4.0G Feb  3 14:21 plik13
-rw-r--r-- 1 root root 4.0G Feb  3 14:21 plik14
-rw-r--r-- 1 root root 4.0G Feb  3 14:21 plik15
-rw-r--r-- 1 root root 4.0G Feb  3 14:21 plik16
-rw-r--r-- 1 root root 4.0G Feb  3 14:21 plik17
-rw-r--r-- 1 root root 4.0G Feb  3 14:21 plik18
-rw-r--r-- 1 root root 4.0G Feb  3 14:21 plik19
-rw-r--r-- 1 root root 4.0G Feb  3 14:20 plik2
-rw-r--r-- 1 root root 4.0G Feb  3 14:21 plik20
-rw-r--r-- 1 root root 4.0G Feb  3 14:21 plik21
-rw-r--r-- 1 root root 4.0G Feb  3 14:21 plik22
-rw-r--r-- 1 root root 4.0G Feb  3 14:21 plik23
-rw-r--r-- 1 root root 4.0G Feb  3 14:21 plik24
-rw-r--r-- 1 root root 4.0G Feb  3 14:21 plik25
-rw-r--r-- 1 root root 4.0G Feb  3 14:21 plik26
-rw-r--r-- 1 root root 4.0G Feb  3 14:21 plik27
-rw-r--r-- 1 root root 4.0G Feb  3 14:21 plik28
-rw-r--r-- 1 root root 4.0G Feb  3 14:21 plik29
-rw-r--r-- 1 root root 4.0G Feb  3 14:20 plik3
-rw-r--r-- 1 root root 4.0G Feb  3 14:22 plik30
-rw-r--r-- 1 root root 4.0G Feb  3 14:22 plik31
-rw-r--r-- 1 root root 4.0G Feb  3 14:22 plik32
-rw-r--r-- 1 root root 4.0G Feb  3 14:22 plik33
-rw-r--r-- 1 root root 4.0G Feb  3 14:22 plik34
-rw-r--r-- 1 root root 4.0G Feb  3 14:22 plik35
-rw-r--r-- 1 root root 4.0G Feb  3 14:22 plik36
-rw-r--r-- 1 root root 4.0G Feb  3 14:22 plik37
-rw-r--r-- 1 root root 4.0G Feb  3 14:22 plik38
-rw-r--r-- 1 root root 4.0G Feb  3 14:22 plik39
-rw-r--r-- 1 root root 4.0G Feb  3 14:20 plik4
-rw-r--r-- 1 root root 4.0G Feb  3 14:22 plik40
-rw-r--r-- 1 root root 4.0G Feb  3 14:22 plik41
-rw-r--r-- 1 root root 4.0G Feb  3 14:22 plik42
-rw-r--r-- 1 root root 4.0G Feb  3 14:22 plik43
-rw-r--r-- 1 root root 4.0G Feb  3 14:22 plik44
-rw-r--r-- 1 root root 4.0G Feb  3 14:22 plik45
-rw-r--r-- 1 root root 4.0G Feb  3 14:22 plik46
-rw-r--r-- 1 root root 4.0G Feb  3 14:22 plik47
-rw-r--r-- 1 root root 4.0G Feb  3 14:22 plik48
-rw-r--r-- 1 root root 4.0G Feb  3 14:22 plik49
-rw-r--r-- 1 root root 4.0G Feb  3 14:20 plik5
-rw-r--r-- 1 root root 4.0G Feb  3 14:22 plik50
-rw-r--r-- 1 root root 4.0G Feb  3 14:23 plik51
-rw-r--r-- 1 root root 4.0G Feb  3 14:23 plik52
-rw-r--r-- 1 root root 4.0G Feb  3 14:23 plik53
-rw-r--r-- 1 root root 4.0G Feb  3 14:23 plik54
-rw-r--r-- 1 root root 4.0G Feb  3 14:23 plik55
-rw-r--r-- 1 root root 4.0G Feb  3 14:23 plik56
-rw-r--r-- 1 root root 4.0G Feb  3 14:23 plik57
-rw-r--r-- 1 root root 4.0G Feb  3 14:23 plik58
-rw-r--r-- 1 root root 4.0G Feb  3 14:23 plik59
-rw-r--r-- 1 root root 4.0G Feb  3 14:20 plik6
-rw-r--r-- 1 root root 4.0G Feb  3 14:23 plik60
-rw-r--r-- 1 root root 4.0G Feb  3 14:20 plik7
-rw-r--r-- 1 root root 4.0G Feb  3 14:21 plik8
-rw-r--r-- 1 root root 4.0G Feb  3 14:21 plik9

zfs get all | grep compress
Pool-0/share0        compressratio         1.00x                  -
Pool-0/share0        compression           lz4                    local
Pool-0/share0        refcompressratio      1.00x                  -
Pool-0               compressratio         1.00x                  -
Pool-0               compression           off                    local
Pool-0               refcompressratio      1.00x                  -

zpool get all
NAME    PROPERTY                    VALUE                       SOURCE
Pool-0  size                        238G                        -
Pool-0  capacity                    0%                          -
Pool-0  altroot                     -                           default
Pool-0  health                      ONLINE                      -
Pool-0  guid                        6512148600335952022         default
Pool-0  version                     -                           default
Pool-0  bootfs                      -                           default
Pool-0  delegation                  on                          default
Pool-0  autoreplace                 off                         default
Pool-0  cachefile                   -                           default
Pool-0  failmode                    wait                        default
Pool-0  listsnapshots               off                         default
Pool-0  autoexpand                  off                         default
Pool-0  dedupditto                  0                           default
Pool-0  dedupratio                  1.00x                       -
Pool-0  free                        238G                        -
Pool-0  allocated                   133M                        -
Pool-0  readonly                    off                         -
Pool-0  ashift                      12                          local
Pool-0  comment                     -                           default
Pool-0  expandsize                  -                           -
Pool-0  freeing                     0                           default
Pool-0  fragmentation               0%                          -
Pool-0  leaked                      0                           default
Pool-0  feature@async_destroy       enabled                     local
Pool-0  feature@empty_bpobj         active                      local
Pool-0  feature@lz4_compress        active                      local
Pool-0  feature@spacemap_histogram  active                      local
Pool-0  feature@enabled_txg         active                      local
Pool-0  feature@hole_birth          active                      local
Pool-0  feature@extensible_dataset  enabled                     local
Pool-0  feature@embedded_data       active                      local
Pool-0  feature@bookmarks           enabled                     local

ZoL v 0.6.3

If it is correct behaviour, please close this ticket.

**Comment by behlendorf** [comment]
This is correct behavior.
