### ISSUE TITLE
zvol I/O errors even though disks are fine, 0.6.3-1.2

### ISSUE THREAD

**Issue by pzwahlen** [zfsonlinux/zfs#3236]
First time posting,

We have a raidz1 pool with 2 zvols which are mostly unreadable (I/O errors). Disks have been tested with read-only and non-destructive read-write "badblocks" and reported 0 errors.

Details:

We're running 0.6.3-1.2 on CentOS 7 with 32G of ECC memory. We have a pool made of 4 disks in raidz1. Disks are Seagate SAS 600G/15K.

Pool contains 2 zvol, exported over scst/iscsi to ESXi and formatted with VMFS. We lost the VMs running on those 2 volumes.

Data has been restored but I need to understand what happened. I've removed those datastores from ESXi and stopped the iscsi export so I'm running everything locally.

When reading from /dev/zd0 or /dev/zd16, kernel generates tons of 

[330940.425700] end_request: I/O error, dev zd16, sector 935819264
[330940.429239] end_request: I/O error, dev zd16, sector 935819264
[330940.432777] end_request: I/O error, dev zd16, sector 935819264
[330940.436030] end_request: I/O error, dev zd16, sector 935819264
[330940.439356] end_request: I/O error, dev zd16, sector 935819264

2 things:
- When that happened, we had zfs_arc_max=28G. I have already been told this was a bad idea and that might be the reason for this corruption. Need input on that. Server was using max 15G of ARC with default settings and was showing 14G of free memory for weeks, so we increased arc_max.

- One disk is showing "Elements in grown defect list: 2047" in smartctl and we initially though it was the culprit. However, this disk is reporting zero badblocks when tested (several times).
```
[root@sanlab2 ~]# zpool status -v
  pool: p02
 state: ONLINE
status: One or more devices has experienced an error resulting in data
        corruption.  Applications may be affected.
action: Restore the file in question if possible.  Otherwise restore the
        entire pool from backup.
   see: http://zfsonlinux.org/msg/ZFS-8000-8A
  scan: scrub repaired 0 in 2h50m with 1008 errors on Thu Mar 26 14:10:34 2015
config:

        NAME                        STATE     READ WRITE CKSUM
        p02                         ONLINE       0     0   500
          raidz1-0                  ONLINE       0     0 1.94K
            wwn-0x5000c5006c5f04ab  ONLINE       0     0     0
            wwn-0x5000c5006c5f3b6f  ONLINE       0     0     0
            wwn-0x5000c5006c5f24bf  ONLINE       0     0     0
            wwn-0x5000c5006c5f36ab  ONLINE       0     0     0

errors: Permanent errors have been detected in the following files:

        p02/p02v01:<0x1>
        p02/p02v02:<0x1>
```
```
[root@sanlab2 ~]# zfs list
NAME         USED  AVAIL  REFER  MOUNTPOINT
p02         1.44T   118G   198K  /p02
p02/p02v01   736G   470G   384G  -
p02/p02v02   736G   603G   251G  -
```
Thanks for hints on how to troubleshoot this further.

**Comment by kernelOfTruth** [comment]
@pzwahlen I've had a seagate (ST3000DM001) fail a few months ago and it also showed no badblocks - but before shortly before that ZFS had detected some issues (if I recall correctly there *_might have been already_* some pending sectors)

then fast forward a few days (or 1-2 weeks) later: the disk was making head placement sounds, defect sectors, reallocated/pending sectors count was rising to the tens of thousands (still somewhat usable) - shortly after that only broken data could be written and/or retrieved and writing also took significantly longer

First I had thought ZFS of smartctl showed some errors or were wrong - but similar behavior could also be observed with Btrfs



could you please post the full output of 

```
smartctl -a
```

for the offending disk(s) ?

seems like ZFS detected hardware errors early enough

**Comment by pzwahlen** [comment]
@kernelOfTruth Thanks for looking into it.

Output of "smartctl -a" for the 4 SAS drives is here:
https://dl.dropboxusercontent.com/u/11595966/smartctl.txt

I don't think zfs detected anything early enough, because data is more or less gone.

I'm seeing the same I/O errors patterns on both volumes (zd0 and zd16). No LVM, no cryptsetup. My topology looks like this:

    4 drives(external jbod) -> HBA(lsi 9207-8e) -> zpool -> zvols -> scst(vdisk_blockio)

ESXi is connecting to SCST over 2x10G paths in round-robin mode.

**Comment by kernelOfTruth** [comment]
https://forums.freenas.org/index.php?threads/many-seagate-600gb-15k-sas-failures-st3600057ss.24921/

the first drive has a few suspicious entries, like you already mentioned:

```
Elements in grown defect list: 2047
```

```
Non-medium error count
```
http://sourceforge.net/p/smartmontools/mailman/smartmontools-support/thread/20120703132148.GX25845@mayfirst.org/




You could try re-assigning the defect blocks, like mentioned in:
http://www.masterzen.fr/2009/02/01/the-curse-of-bad-blocks-is-no-more/

I'd be interested if others with those kind of setups (I'm running a small server/workstation so don't have experience with raidz) can offer more insights


Perhaps zdb gives additional information ?

export the pool, then run

```
zdb -mc -M -e
```


Anyway: you'd probably get a faster response on the freenode zfs and zfsonlinux irc channel , if it's urgent

Sorry to be of no additional help

**Comment by pzwahlen** [comment]
After careful log investigation I think I understand what happened.

This pool is in a "shared" JBOD. Pacemaker/Corosync are managing the clustering/failover.

Sometime, I can see the load on the server going up to 32 (reported by uptime). It is mostly IOWAIT and txg_sync from what I can tell.

In one such peak, Corosync couldn't get scheduled properly and the other node forcefully took over, migrating the pool (and iSCSI and IP addresses). It appears the pool was then dual-mounted on both nodes for about 5 seconds (time it took for Corosync to settle down and fail back).

Can anyone confirm this would be enough for so many IO errors on ZVOLS ?

I'll close the issue once I get some more feedback.

Thanks everyone one!

**Comment by kpande** [comment]
Ouch. That definitely sounds like it would cause a problem for the pool!

**Comment by pzwahlen** [comment]
After further investigation, it clearly appears that this pool was dual-imported for 5 seconds. In this case, one node became so slow that Corosync couldn't be scheduled.

Anyway, issue closed!
