### ISSUE TITLE
isci firmware

### ISSUE THREAD

**Issue by AbhayMK** [zfsonlinux/zfs#3244]
I am working on debian 7 wheezy.
following error occurred during zfs installation.

Setting up zfs-dkms (0.6.3-1.3-2~wheezy) ...
Loading new zfs-0.6.3 DKMS files...
First Installation: checking all kernels...
Building only for 3.2.0-4-amd64
Building initial module for 3.2.0-4-amd64
configure: error:
        *** Please make sure the kmod spl devel <kernel> package for your
        *** distribution is installed then try again.  If that fails you
        *** can specify the location of the spl objects with the
        *** '--with-spl-obj=PATH' option.
Error! Bad return status for module build on kernel: 3.2.0-4-amd64 (x86_64)
Consult /var/lib/dkms/zfs/0.6.3/build/make.log for more information.

ALSO IN THE END:-

W: Possible missing firmware /lib/firmware/isci/isci_firmware.bin for module isci
Setting up debian-zfs (7~wheezy) ...

Can you suggest what is to be done.

**Comment by FransUrbo** [comment]
> *** Please make sure the kmod spl devel package for your
> *** distribution is installed then try again.
> 
This is the real culprit - dpkg is trying to configure zfs-dims before spl-dkms
(or spl-dkms failed and you didn't notice).

Try:

	dpkg --configure spl-dkms

and when that's complete:
	dpkg --configure zfs-dkms

and for completeness when that's finished:

	dpkg --configure --pending
> W: Possible missing firmware /lib/firmware/isci/isci_firmware.bin for module isci
> 
That is completely unrelated and only a (W)arming. Nothing to worry about
(unless, possibly, if you're booting from iSCSI).

**Comment by behlendorf** [comment]
Closing.  You'll want to update to the latest official packages from Debian.
