### ISSUE TITLE
CentOS 7.1 (7.1.1503 (Core)) do not install zfs 

### ISSUE THREAD

**Issue by x09** [zfsonlinux/zfs#3245]
zfs   0.6.3-1.3.el7.centos

yum install zfs

>....
>Loading new zfs-0.6.3 DKMS files...
>Building for 3.10.0-229.1.2.el7.x86_64
>Building initial module for 3.10.0-229.1.2.el7.x86_64
>configure: error:
>       *** Please make sure the kmod spl devel <kernel> package for your
>       *** distribution is installed then try again.  If that fails you
>       *** can specify the location of the spl objects with the
>       *** '--with-spl-obj=PATH' option.
>Error! Bad return status for module build on kernel: 3.10.0-229.1.2.el7.x86_64 (x86_64)
>Consult /var/lib/dkms/zfs/0.6.3/build/make.log for more information.
>warning: %post(zfs-dkms-0.6.3-1.3.el7.centos.noarch) scriptlet failed, exit status 10
>Non-fatal POSTIN scriptlet failure in rpm package zfs-dkms-0.6.3-1.3.el7.centos.noarch
>....

[root@pj5 ~]# cat /etc/redhat-release
CentOS Linux release 7.1.1503 (Core)

[root@pj5 ~]# uname -a
Linux prj5.geoseis 3.10.0-229.1.2.el7.x86_64 #1 SMP Fri Mar 27 03:04:26 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

[root@prj5 ~]# rpm -qa | grep zfs-release
zfs-release-1-2.el7.centos.noarch

**Comment by x09** [comment]
yum erase zfs zfs-dkms libzfs2
and try reinstall it

see full proccess log here - http://pastebin.com/eqAHrPyN

**Comment by shepherdlazy** [comment]
I am error
``` bash
[root@host ~]# yum install zfs 
--> Finished Dependency Resolution
Error: Package: zfs-dkms-0.6.3-1.3.el7.centos.noarch (zfs)
           Requires: dkms >= 2.2.0.3-20
Error: Package: spl-dkms-0.6.3-1.3.el7.centos.noarch (zfs)
           Requires: dkms >= 2.2.0.2
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
[root@host ~]# cat /etc/redhat-release
CentOS Linux release 7.1.1503 (Core)
[root@host ~]# uname -a
Linux host.net 3.10.0-229.1.2.el7.x86_64 #1 SMP Fri Mar 27 03:04:26 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by shepherdlazy** [comment]
I'm sorry I epel repo is not enabled.

**Comment by yesbox** [comment]
Confirmed, won't successfully install on Centos 7.1.

**Comment by behlendorf** [comment]
This looks like an issue with the weak modules support for older kernels.  This is almost certainly because the spl.ko module doesn't strictly adhere the kernel KABI whitelist.  We're moving in that direction but we still depend on some symbols not on the whitelist, and one of those symbols must have changed.

I just verified that if you boot in to the latest kernel and run the install everything behaves properly.

**Comment by x09** [comment]
>[root@pj5 ~]# rpm -qa | grep kernel
>kernel-tools-libs-devel-3.10.0-229.1.2.el7.x86_64
>kernel-devel-3.10.0-229.1.2.el7.x86_64
>kernel-3.10.0-229.1.2.el7.x86_64
>kernel-tools-3.10.0-229.1.2.el7.x86_64
>kernel-headers-3.10.0-229.1.2.el7.x86_64
>kernel-tools-libs-3.10.0-229.1.2.el7.x86_64

>[root@pj5 ~]# rpm -qa | grep zfs
>libzfs2-0.6.3-1.3.el7.centos.x86_64
>zfs-0.6.3-1.3.el7.centos.x86_64
>zfs-release-1-2.el7.centos.noarch
>zfs-dkms-0.6.3-1.3.el7.centos.noarch

[root@pj5 ~]# uname -a
>Linux pj5 3.10.0-229.1.2.el7.x86_64 #1 SMP Fri Mar 27 03:04:26 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

>[root@pj5 ~] find /lib/modules/$(uname -r)/ -name "splat.ko" -or -name "zcommon.ko" -or -name "zpios.ko" -or -name "spl.ko" -or -name "zavl.ko" -or -name "zfs.ko" -or -name "znvpair.ko" -or -name "zunicode.ko"

>/lib/modules/3.10.0-229.1.2.el7.x86_64/extra/zcommon.ko
>/lib/modules/3.10.0-229.1.2.el7.x86_64/extra/zunicode.ko
>/lib/modules/3.10.0-229.1.2.el7.x86_64/extra/zpios.ko
>/lib/modules/3.10.0-229.1.2.el7.x86_64/extra/znvpair.ko
>/lib/modules/3.10.0-229.1.2.el7.x86_64/extra/zavl.ko
>/lib/modules/3.10.0-229.1.2.el7.x86_64/extra/zfs.ko

>[root@pj5 ~]# zpool list
>Failed to load ZFS module stack.
>Load the module manually by running 'insmod <location>/zfs.ko' as root.

>[root@pj5 modules]# insmod /lib/modules/3.10.0-229.1.2.el7.x86_64/extra/zfs.ko
>insmod: ERROR: could not insert module /lib/modules/3.10.0-229.1.2.el7.x86_64/extra/zfs.ko: >Unknown symbol in module

not working. i am need forced downgrade to CentOS 7.0

**Comment by shepherdlazy** [comment]
I can run successfully, and have started to use

```
[root@host ~]# rpm -qa | grep kernel
kernel-devel-3.10.0-229.1.2.el7.x86_64
kernel-debug-devel-3.10.0-229.1.2.el7.x86_64
kernel-3.10.0-229.1.2.el7.x86_64
kernel-tools-3.10.0-229.1.2.el7.x86_64
kernel-headers-3.10.0-229.1.2.el7.x86_64
kernel-tools-libs-3.10.0-229.1.2.el7.x86_64
abrt-addon-kerneloops-2.1.11-19.el7.centos.0.3.x86_64
[root@host ~]# rpm -qa | grep zfs
zfs-release-1-2.el7.centos.noarch
zfs-0.6.3-1.3.el7.centos.x86_64
zfs-dkms-0.6.3-1.3.el7.centos.noarch
libzfs2-0.6.3-1.3.el7.centos.x86_64
[root@host ~]# uname -a
Linux host.net 3.10.0-229.1.2.el7.x86_64 #1 SMP Fri Mar 27 03:04:26 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[root@host ~]# find /lib/modules/$(uname -r)/ -name "splat.ko" -or -name "zcommo 
n.ko" -or -name "zpios.ko" -or -name "spl.ko" -or -name "zavl.ko" -or -name "zfs 
.ko" -or -name "znvpair.ko" -or -name "zunicode.ko"
/lib/modules/3.10.0-229.1.2.el7.x86_64/extra/spl.ko
/lib/modules/3.10.0-229.1.2.el7.x86_64/extra/splat.ko
/lib/modules/3.10.0-229.1.2.el7.x86_64/extra/zavl.ko
/lib/modules/3.10.0-229.1.2.el7.x86_64/extra/znvpair.ko
/lib/modules/3.10.0-229.1.2.el7.x86_64/extra/zunicode.ko
/lib/modules/3.10.0-229.1.2.el7.x86_64/extra/zcommon.ko
/lib/modules/3.10.0-229.1.2.el7.x86_64/extra/zfs.ko
/lib/modules/3.10.0-229.1.2.el7.x86_64/extra/zpios.ko
[root@host ~]# zpool list
NAME          SIZE  ALLOC   FREE    CAP  DEDUP  HEALTH  ALTROOT
mfspool      2.72T   143G  2.58T     5%  1.00x  ONLINE  -
mfspool-ext  2.72T   230G  2.49T     8%  1.00x  ONLINE  -
[root@host ~]# zfs list
NAME                     USED  AVAIL  REFER  MOUNTPOINT
mfspool                  143G  2.54T   200K  /mfspool
mfspool-ext              230G  2.45T  13.3G  /mfspool-ext
mfspool-ext/movie        217G  2.45T   217G  /mfspool-ext/movie
mfspool/archive          136K  2.54T   136K  /mfspool/archive
mfspool/backup          88.3G  2.54T  88.3G  /mfspool/backup
mfspool/doc              136K  2.54T   136K  /mfspool/doc
mfspool/media           54.5G  2.54T   168K  /mfspool/media
mfspool/media/gallery   39.5G  2.54T  39.5G  /mfspool/media/gallery
mfspool/media/music      944M  2.54T   944M  /mfspool/media/music
mfspool/media/recorder   136K  2.54T   136K  /mfspool/media/recorder
mfspool/media/videos    14.1G  2.54T  14.1G  /mfspool/media/videos
mfspool/scm              136K  2.54T   136K  /mfspool/scm
mfspool/src              136K  2.54T   136K  /mfspool/src
mfspool/tools            136K  2.54T   136K  /mfspool/tools
mfspool/www              136K  2.54T   136K  /mfspool/www
[root@host ~]# zpool status
  pool: mfspool
 state: ONLINE
  scan: none requested
config:

NAME        STATE     READ WRITE CKSUM
mfspool     ONLINE       0     0     0
  mirror-0  ONLINE       0     0     0
    sdc     ONLINE       0     0     0
    sdd     ONLINE       0     0     0

errors: No known data errors

  pool: mfspool-ext
 state: ONLINE
  scan: none requested
config:

NAME        STATE     READ WRITE CKSUM
mfspool-ext  ONLINE       0     0     0
  sde       ONLINE       0     0     0

errors: No known data errors
[root@host ~]# 
```

**Comment by shepherdlazy** [comment]
It took me a long time to install spl-dkms and zfs-dkms. You re install spl-dkms and zfs-dkms to try .

**Comment by x09** [comment]
Remove old kernel{headers,libs}
Reinstall spl-dkms, zfs-dkms
all work fine.
