### ISSUE TITLE
centos 7 strikes again

### ISSUE THREAD

**Issue by dmaziuk** [zfsonlinux/zfs#3250]
I'm gonna report this as an issue even though I'm not sure there's anything to be done. Short of pushing out a stable release that works on centos 7. It's somewhat related to #3248 -- rather, to what happens after.

What happens after is that dkms didn't rebuild the testing -159_gc944be5 on kernel update. And since I don't have zfs-testing repo enabled by default I didn't get -260_g74aa2ba until after reboot when I had no /tank again.

No biggie, update to -260_g74aa2ba fixed it, but still an annoyance. Expect more centos 7 users to get bit by it.

**Comment by deajan** [comment]
copying my solution from #3248 that the reporter just closed so people can easily find this fix.
Please leave this open for some time.

Clean reinstall with the following (latest zfs testing packages are stable to use)
```
dkms remove --all zfs/0.6.3
 dkms remove --all spl/0.6.3
find /lib/modules/$(uname -r)/extra -name "splat.ko" -or -name "zcommon.ko" -or -name "zpios.ko" -or -name "spl.ko" -or -name "zavl.ko" -or -name "zfs.ko" -or -name "znvpair.ko" -or -name "zunicode.ko" | xargs rm -f
find /lib/modules/$(uname -r)/weak-updates/ -name "splat.ko" -or -name "zcommon.ko" -or -name "zpios.ko" -or -name "spl.ko" -or -name "zavl.ko" -or -name "zfs.ko" -or -name "znvpair.ko" -or -name "zunicode.ko" | xargs rm -f
yum reinstall zfs-release
yum --enablerepo=zfs-testing reinstall $(rpm -qa | egrep "zfs|spl")
```

You will still get error messages but your kernel modules get built.
You can check them with
```
find /lib/modules/$(uname -r)/extra
```

**Comment by dmaziuk** [comment]
the point is, kernel updates don't seem to work with -testing zfs packages. I just did "yum --enablerepo=zfs-testing up" on another system and even though that pulled in the -260__g74aa2ba I still had no /tank after reboot and had to do a clean reinstall.

**Comment by dmaziuk** [comment]
PS. no /tank after reboot is of course the original centos-7 problem that -testing packages are supposed to fix. So how are we better off.

**Comment by deajan** [comment]
Well i have the above commands run on two CentOS 7.1 servers that fixed my no tank problem too.

**Comment by dmaziuk** [comment]
I believe the proper fix for centos 7 no tank problem is releasing a stable hostid-fixed version.
