### ISSUE TITLE
"Cannot find UTS_RELEASE definition" when build the latest dkms packages, Debian Jessie with custom compiled kernel 3.18.5

### ISSUE THREAD

**Issue by Amitie10g** [zfsonlinux/zfs#3263]
Well, I just updated to the newest packages:

* **zfs:** 0.6.3-44-40d06e
* **spl:** 0.6.3-27-ae26dd
* **GRUB:** ZOL9-7aa9f6

GRUB works perfectly, but when building zfs and spl with dkms the following error appears for the both zfs and spl:
```
Building initial module for 3.18.5-custom
configure: error: *** Cannot find UTS_RELEASE definition.
Error! Bad return status for module build on kernel: 3.18.5-custom (x86_64)
```
The logs were populed with the following short contents (for the both spl and zfs, too):
```
DKMS make.log for spl-0.6.3 for kernel 3.18.5-custom (x86_64)
Mon Apr  6 22:11:02 CLST 2015
make: *** No targets specified and no makefile found.  Stop.
```
I'm using Debian Jessie/Sid with a custom compiled kernel 3.18.5; previous zfs and spl versions were built against this kernel without issues.

I still able to boot with the backup initramfs.

**Comment by FransUrbo** [comment]
What does <code>/var/lib/dkms/zfs/0.*/$(uname -r)/$(arch)/log/make.log</code> say?

**Comment by Amitie10g** [comment]
The only logs are pressent in ```/var/lib/dkms/zfs/0.6.3/build/``` with the contents indicated above, and there has been created the directory "3.2.0-4-amd64".

The relevant parts of /var/lib/dkms/zfs/0.6.3/build/config.log for me are:
```
[output omitted]
hostname = davod-notebook
uname -m = x86_64
uname -r = 3.18.5-custom
uname -s = Linux
uname -v = #1 SMP PREEMPT Mon Feb 2 23:09:45 CLST 2015

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown
[output omitted]
```

<a href="http://pastebin.com/YQ0r8GjW">Full log is available in Pastebin</a>.

**Comment by FransUrbo** [comment]
```
configure:12837: checking kernel source directory
configure:12879: result: /lib/modules/3.18.5-custom/./source
configure:12890: checking kernel build directory
configure:12917: result: /lib/modules/3.18.5-custom/build
configure:12920: checking kernel source version
configure:12956: result: Not found
```

Do you have either of these links pointing to your custom kernel source/build directory?

**Comment by Amitie10g** [comment]
I haven't checked that yet, because I gone to sleep at that moment. I'll fix the symlinks and I'll try again.
