### ISSUE TITLE
Memory leak in make_root_vdev()

### ISSUE THREAD

**Issue by thegreatgazoo** [zfsonlinux/zfs#3264]
In make_root_vdev():
```c
        if ((newroot = construct_spec(props, argc, argv)) == NULL)
                return (NULL);

        if (zhp && ((poolconfig = zpool_get_config(zhp, NULL)) == NULL))
                return (NULL);
```

Before the 2nd _return (NULL)_, there should be a _nvlist_free(newroot);_. Otherwise memory for _newroot_ seemed leaked. Patch to come shortly.

**Comment by behlendorf** [comment]
Good catch, yes it definitely looks like we need a `nvlist_free(newroot);` there.
