### ISSUE TITLE
Document bookmarks properly

### ISSUE THREAD

**Issue by FransUrbo** [zfsonlinux/zfs#3268]
I know I added an example in the manpage a few months ago, but looking through the manpage again today, I noticed it's not really described anywhere…

Snapshots (together with Clones, Volumes and File systems etc) is described fairly early, but not bookmarks.

If I know exactly what a bookmark IS (but especially the difference between a bookmark and a snapshot), I could do it in a few minutes… Unless someone else jumps to it.

**Comment by DeHackEd** [comment]
A bookmark isn't a property. It's loosely a snapshot but without the hold on on-disk data. It can be used as the source of a send (but not the destination). 

The idea is users can keep bookmarks around for replication reasons and not worry about disk space being consumed by them.  The way I imagine it if your backup target went down and your snapshot retention policy destroyed your last snapshot replicated to the backup target then you'd need to start all over again. If you kept bookmarks for each snapshot on the source then you can just resume from that instead.

From a storage standpoint, a bookmark is little more than a recording of the 'createtxg' of a snapshot into a distinct object which survives if the snapshot itself is destroyed. That means there's little incentive to destroy them.
