### ISSUE TITLE
"zpool upgrade" advice considered dangerous

### ISSUE THREAD

**Issue by gordan-bobic** [zfsonlinux/zfs#3270]
In light of recent conversation on the mailing list regarding using ZFS for root/boot file systems, the following message from "zpool status" could be considered dangerous:

status: The pool is formatted using a legacy on-disk format.  The pool can
    still be used, but some features are unavailable.
action: Upgrade the pool using 'zpool upgrade'.  Once this is done, the
    pool will no longer be accessible on software that does not support
    feature flags.

Since grub package is not keeping up with ZFS patches required to support the latest ZFS features, following this advice could render a machine unbootable in a way that is very difficult to recover from (a new /boot disk would be required).

Consequently, I would like to propose that this advice is not given out as standard. At the very least it should be omitted unless -v is used.

**Comment by FransUrbo** [comment]
I agree with you, BUT (playing devils advocate), one COULD argue that <code> will no longer be accessible on software that does not support feature flags</code> is enough warning.

On the other hand, how many users read documentation and know that this would affect Grub and therefor their booting of the system?

I second your suggestion that it would only be shown if used with <code>-v</code>. WITH, possibly, one of those links for other problems which could describe the issue in more detail and the dangers of [upgrading] it.

**Comment by GregorKopka** [comment]
Maybe change the message a bit:
```
action: Upgrade the pool using 'zpool upgrade'. Once this is done, the
pool will no longer be accessible on software that does not support
feature flags. WARNING: This can result in root pools unable to boot.
```
?

**Comment by gordan-bobic** [comment]
How about something like this:
- Only show the message with -v.
- When the user calls "zpool upgrade", do a check to see if /boot is on ZFS. If it is, refuse to do it without -f.

**Comment by Bronek** [comment]
@gordan-bobic also check on a root i.e. / filesystem would be required (unless you actually meant it? using ZFS as /boot is rather fiddly, I heard)

As for proposed message, small problem (as a user) is that I do not see what features would be added before I upgrade, and I only learn about those if I need to downgrade and ZFS tells me that its unable to import a pool due to (finally listed) features. Perhaps its better not to give advice to upgrade in the first place, if we do not tell how that would be better.

Also, it would be great if there was an ability to learn before committing to downgrade that some pools will not import anymore (this is what #3234 was about)

**Comment by gordan-bobic** [comment]
I don't think checking for root on ZFS is necessary. If we can load the kernel and initramfs, we have are far enough along that it no longer matters. Checking where /boot is important.

The original point made was that the message to upgrade should not be shown by default.

The much bigger problem is that downgrading is not possible because the pool will have been tainted by options that grub doesn't understand. If you upgrade the pool and find it is unbootable, the only thing you can do is get another disk, put both the old and new disks in another machine, and zfs send the contents of the old pool to the new disk, and make sure the new disk was set up without enabling features incompatible with grub - in other words, it causes a huge complication, which is why I think upgrading the pool should not be encouraged or mentioned as advisory without an overwhelmingly good reason, and if there is any hint of ZFS being used for /boot, upgrade should require -f.
