### ISSUE TITLE
immutable bit can't be set/unset on files in pool root

### ISSUE THREAD

**Issue by bfleming** [zfsonlinux/zfs#3275]
I've run into the issue described in the title. This may be unique to my situation, or at least a rarity.
Pool named Storage was initially created with maczfs.
Files were copied onto Storage without creating any datasets, (just straight to /Storage).
The disks were moved to a new linux machine, (zfs-0.6.3), imported, filesystem updated to 5000, and Storage renamed to tank.

Datasets were created and in attempting to move some files to organize them into appropriate datasets, some files couldn't be moved due to the immutable bit being set on them. Note that I never set the immutable bits on these files in the first place, so I'm not sure why they are set.

chattr -i on the files in question returns: Invalid argument while setting flags.

After some testing, I see that I can chattr +i and chattr -i on files within a dataset, but if I copy a new file to /tank, chattr +i or chattr -i on the new file also returns: Invalid argument while setting flags.

**Comment by bfleming** [comment]
It's been a while with no comments. Is there more information that's needed to look into this issue? Is this expected behavior for a pool created with maczfs?

**Comment by kernelOfTruth** [comment]
support should be there:

https://github.com/zfsonlinux/zfs/issues/229

http://comments.gmane.org/gmane.linux.file-systems.zfs.user/5073

**Comment by ilovezfs** [comment]
You should move to 0.6.4, regardless.

Have you upgraded the pool and the datasets yet from versions 8 and 2 to versions 5000 and 5, respectively?

**Comment by bfleming** [comment]
Centos 6.6 64-bit with latest kernel 2.6.32-504.16.2.el6.x86_64.
Upgraded to 0.6.4 last week and ran zpool upgrade -a.

Preexisting file that can't be deleted:
[root@storage WINDOWS]# lsattr SET3.tmp
----i----------- SET3.tmp
[root@storage WINDOWS]# chattr -i SET3.tmp
chattr: Invalid argument while setting flags on SET3.tmp

strace output for chattr:
lstat("SET3.tmp", {st_mode=S_IFREG|0755, st_size=1042903, ...}) = 0
lstat("SET3.tmp", {st_mode=S_IFREG|0755, st_size=1042903, ...}) = 0
open("SET3.tmp", O_RDONLY|O_NONBLOCK)   = 3
ioctl(3, EXT2_IOC_GETFLAGS, 0x7fff0f07621c) = 0
close(3)                                = 0
lstat("SET3.tmp", {st_mode=S_IFREG|0755, st_size=1042903, ...}) = 0
open("SET3.tmp", O_RDONLY|O_NONBLOCK)   = 3
ioctl(3, EXT2_IOC_SETFLAGS, 0x7fff0f07621c) = -1 EINVAL (Invalid argument)
close(3)                                = 0

Create new file in same directory (reproducible anywhere under /tank outside of a dataset):
[root@storage WINDOWS]# touch test
[root@storage WINDOWS]# chattr +i test
chattr: Invalid argument while setting flags on test

strace output for chattr:
lstat("test", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
lstat("test", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
open("test", O_RDONLY|O_NONBLOCK)       = 3
ioctl(3, EXT2_IOC_GETFLAGS, 0x7fffe2e2a44c) = 0
close(3)                                = 0
lstat("test", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
open("test", O_RDONLY|O_NONBLOCK)       = 3
ioctl(3, EXT2_IOC_SETFLAGS, 0x7fffe2e2a44c) = -1 EINVAL (Invalid argument)
close(3)      

Create a new file in dataset /tank/backups:
[root@storage backups]# touch test
[root@storage backups]# lsattr test
---------------- test
[root@storage backups]# chattr +i test
[root@storage backups]# lsattr test
----i----------- test

strace output for chattr:
lstat("test", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
lstat("test", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
open("test", O_RDONLY|O_NONBLOCK)       = 3
ioctl(3, EXT2_IOC_GETFLAGS, 0x7fff7699126c) = 0
close(3)                                = 0
lstat("test", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
open("test", O_RDONLY|O_NONBLOCK)       = 3
ioctl(3, EXT2_IOC_SETFLAGS, 0x7fff7699126c) = 0
close(3)                                = 0


Looks like I'm hitting this section of code:
e2fsprogs-1.42.12/misc/chattr.c:
```
if (fsetflags(name, flags) == -1) {
        if (!silent) {
                com_err(program_name, errno,
                                _("while setting flags on %s"),
                                name);
        }
        return -1;
}
```
Then possibly here:
e2fsprogs-1.42.12/lib/e2p/fsetflags.c:
```
#else /* !HAVE_CHFLAGS || (APPLE_DARWIN && HAVE_EXT2_IOCTLS) */
#if HAVE_EXT2_IOCTLS
        int fd, r, f, save_errno = 0;
        struct stat buf;

        if (!lstat(name, &buf) &&
            !S_ISREG(buf.st_mode) && !S_ISDIR(buf.st_mode)) {
                goto notsupp;
        }
#if !APPLE_DARWIN
        fd = open (name, OPEN_FLAGS);
        if (fd == -1)
                return -1;
        f = (int) flags;
        r = ioctl (fd, EXT2_IOC_SETFLAGS, &f);
        if (r == -1)
                save_errno = errno;
        close (fd);
        if (save_errno)
                errno = save_errno;
#else /* APPLE_DARWIN */
        f = (int) flags;
        return syscall(SYS_fsctl, name, EXT2_IOC_SETFLAGS, &f, 0);
#endif /* !APPLE_DARWIN */
        return r;

notsupp:
#endif /* HAVE_EXT2_IOCTLS */
#endif
        errno = EOPNOTSUPP;
        return -1;
}
```

**Comment by bfleming** [comment]
Looks like tank was at version 2 and the new datasets were version 5.
Set tank to 5 and immutable bit can be changed now.
I thought a zpool upgrade would handle the versioning.
Thanks for the hint and apologies for the noise.
