### ISSUE TITLE
zpool upgrade fails

### ISSUE THREAD

**Issue by zinc69** [zfsonlinux/zfs#3276]
Maybe i missed something but i cant do a zpool upgrade on my pool after the latest update 0.6.4 (v5?)

Debian Wheezy

root@xxx:# zpool upgrade -a
This system supports ZFS pool feature flags.

cannot set property for 'poolname': invalid argument for this pool operation

root@xxx:# zpool upgrade -v
This system supports ZFS pool feature flags.

The following features are supported:

FEAT DESCRIPTION
-------------------------------------------------------------
async_destroy                         (read-only compatible)
     Destroy filesystems asynchronously.
empty_bpobj                           (read-only compatible)
     Snapshots use less space.
lz4_compress
     LZ4 compression algorithm support.
spacemap_histogram                    (read-only compatible)
     Spacemaps maintain space histograms.
enabled_txg                           (read-only compatible)
     Record txg at which a feature is enabled
hole_birth
     Retain hole birth txg for more precise zfs send
extensible_dataset
     Enhanced dataset functionality, used by other features.
embedded_data
     Blocks which compress very well use even less space.
bookmarks                             (read-only compatible)
     "zfs bookmark" command

The following legacy versions are also supported:

VER  DESCRIPTION
---  --------------------------------------------------------
 1   Initial ZFS version
 2   Ditto blocks (replicated metadata)
 3   Hot spares and double parity RAID-Z
 4   zpool history
 5   Compression using the gzip algorithm
 6   bootfs pool property
 7   Separate intent log devices
 8   Delegated administration
 9   refquota and refreservation properties
 10  Cache devices
 11  Improved scrub performance
 12  Snapshot properties
 13  snapused property
 14  passthrough-x aclinherit
 15  user/group space accounting
 16  stmf property support
 17  Triple-parity RAID-Z
 18  Snapshot user holds
 19  Log device removal
 20  Compression using zle (zero-length encoding)
 21  Deduplication
 22  Received properties
 23  Slim ZIL
 24  System attributes
 25  Improved scrub stats
 26  Improved snapshot deletion performance
 27  Improved snapshot creation performance
 28  Multiple vdev replacements

**Comment by FransUrbo** [comment]
> Maybe i missed something but i cant do a zpool upgrade on my pool after the latest update 0.6.4 (v5?)
> 
Did you reboot after the upgrade?

**Comment by zinc69** [comment]
no... do i really need to?

**Comment by FransUrbo** [comment]
> no... do i really need to?
> 

Of course! This is a filesystem that's resides in a kernel module. And you just made a MAJOR update!

**Comment by zinc69** [comment]
well that was an adventure, something happened to my grub2 and the server would not boot.  after that was fixed i was able to upgrade successfully
Thanks for the advice.
