### ISSUE TITLE
[reminder] zfs-0.6.4-stable branch creation for both zfs & spl

### ISSUE THREAD

**Issue by kernelOfTruth** [zfsonlinux/zfs#3277]
Hi,

@behlendorf if you've forgotten or still haven't had time to do so

here's the reminder/issue to create a branch for the 0.6.4 ZoL milestone

Thank you :+1:

**Comment by behlendorf** [comment]
@kernelOfTruth I haven't forgotten, but thanks for the reminder, I'll get it created once we have fixes where are needed there.

**Comment by behlendorf** [comment]
https://github.com/zfsonlinux/zfs/tree/zfs-0.6.4-release

I've created the zfs-0.6.4-release branch for point releases based on 0.6.4.  Currently it contains the following small, but important, fixes.  I'd like to turn around the first point release, 0.6.4.1, with at least these fixes and almost certainly one or two more.

e548a59 Mark additional functions as PF_FSTRANS
7af6322 Allocate zfs_znode_cache on the Linux slab
