### ISSUE TITLE
zfs receive datasets with foriegn set mountpoints

### ISSUE THREAD

**Issue by hcoin** [zfsonlinux/zfs#3278]
I sure lost many hours tracking down this 'system stops' issue:

Consider a "zfs send" dataset that mentions specific paths as mountpoints.  A dataset made by a system no longer able to recreate it.  The issue arises when the mountpoints specified in the dataset are locally critical:  /var  /root, etc.

The -u option appears to succeed in preventing the immediate mounting of the uppermost dataset, while allowing the mounting of child datasets.  And even the uppermost dataset gets mounted on a reboot.  This results in a system which dies mysteriously upon reboot forcing a rescue boot. At any rate: forcing the receive process to be human monitored each time.  Other 'workarounds' mentioned online have the effect of changing global behavior on the zpool.   

The devil of it is:  there is no way I know of to detect in advance whether there are specific problematic mount points in an incoming stream until after they've been loaded and potentially created a havoc.  

Consider either (my preference)  adding a switch to 'zfs recv' in the spirit of 'chroot': a switch that forces all mountpoints in an incoming dataset to be descendants of the path in the switch.  This one preserves all information in the incoming datasets (switch settings, etc.)

or:  A switch in ZFS receive that forces all switches relating to immediate mounting and mounting upon reboots of all datasets in the stream to "off".   I don't like this one because it loses information.

Then the admin can sort it out without the fear a reboot at the wrong time will not allow any log ins, or even 'rescue mode' boots.

**Comment by mailinglists35** [comment]
for me the -u option is ignored like in this freebsd thread https://forums.freebsd.org/threads/36844/
so I have to temporarily set canmount=noauto on source then restore canmount to on on the source after successful send

**Comment by loli10K** [comment]
With https://github.com/zfsonlinux/zfs/commit/a3eeab2de68670a4481eab3d086982aff23b6906 we can change the `mountpoint` (or `canmount`) property on the destination when receiving to avoid issues with foreign filesystems:

```
root@linux:~# df
Filesystem     1K-blocks     Used Available Use% Mounted on
udev               10240        0     10240   0% /dev
tmpfs            2048652     8568   2040084   1% /run
/dev/sda1       30363364 22280372   6517724  78% /
tmpfs            5121624        0   5121624   0% /dev/shm
tmpfs               5120        0      5120   0% /run/lock
tmpfs            5121624        0   5121624   0% /sys/fs/cgroup
tmpfs            5121624   262144   4859480   6% /var/tmp
src/fs             57088        0     57088   0% /mnt/foreign
src/fs/subfs1      57088        0     57088   0% /mnt/foreign/subfs1
src/fs/subfs2      57088        0     57088   0% /mnt/foreign/subfs2
root@linux:~# zfs send -R src/fs@snap1 | zfs recv -v dst/fs -o mountpoint=/srv
receiving full stream of src/fs@snap1 into dst/fs@snap1
received 48.6K stream in 1 seconds (48.6K/sec)
receiving full stream of src/fs/subfs2@snap1 into dst/fs/subfs2@snap1
received 44.8K stream in 1 seconds (44.8K/sec)
receiving full stream of src/fs/subfs1@snap1 into dst/fs/subfs1@snap1
received 44.8K stream in 1 seconds (44.8K/sec)
root@linux:~# df
Filesystem     1K-blocks     Used Available Use% Mounted on
udev               10240        0     10240   0% /dev
tmpfs            2048652     8568   2040084   1% /run
/dev/sda1       30363364 22280372   6517724  78% /
tmpfs            5121624        0   5121624   0% /dev/shm
tmpfs               5120        0      5120   0% /run/lock
tmpfs            5121624        0   5121624   0% /sys/fs/cgroup
tmpfs            5121624   262144   4859480   6% /var/tmp
src/fs             57088        0     57088   0% /mnt/foreign
src/fs/subfs1      57088        0     57088   0% /mnt/foreign/subfs1
src/fs/subfs2      57088        0     57088   0% /mnt/foreign/subfs2
dst/fs             57088        0     57088   0% /srv
dst/fs/subfs1      57088        0     57088   0% /srv/subfs1
dst/fs/subfs2      57088        0     57088   0% /srv/subfs2
```

Does this address your needs @hcoin? Can we close this?

**Comment by hcoin** [comment]
@loli10K  I'd say this patch goes all of the way to avoid crashes when the admin 'knows' the recv side has the character of a 'repository of data that only will be used elsewhere' and is defacto 'read only' no matter what the various flags enable and need only be visible in the zfs directory tree, then expresses that knowledge by maintaining -x and -o flags depending on the direction of the data flow.

Ideally, you'd want any dataset sent 'back' to where it 'came from' to 'just work' without having to remember that it was 'originally sent' using a 'special flag'.  These patches accomplish that only if the admin 'keeps track' of 'what which source wanted'.  

I think a 'whole answer' might be something like a tristate flag on the zpool called 'is_repository' with choices false, true and force,  and an optional flag in zfs recv 'override_repository' with choices true and false.

You can work out the logic, with the effect that if a dataset is landing in a pool with is_repository true or force or has the override_repository true then nothing in it will be mounted no matter what the flags in the data set might indicate.  In that way, when the dataset is 'sent back' it will 'do what it did' without forcing the admin to 'keep track' of 'where it came from'.
