### ISSUE TITLE
CentOS 6.6 , zfs 6.4.1 (zpool upgrade failed after zfs upgrade)

### ISSUE THREAD

**Issue by x09** [zfsonlinux/zfs#3284]
Hi,

upgrade zfs 6.3.x to 6.4.x

> [root@pd6 ~]# zpool status
>  pool: ZFS
> state: ONLINE
> status: Some supported features are not enabled on the pool. The pool can
>        still be used, but some features are unavailable.
>action: Enable all features using 'zpool upgrade'. Once this is done,
>        the pool may no longer be accessible by software that does not support
>       the features. See zpool-features(5) for details.
> ....

OK, let's try..

>[root@pd6 ~]# zpool upgrade
>This system supports ZFS pool feature flags.
>....
> POOL  FEATURE
> ---------------
>ZFS            
>      spacemap_histogram
>      enabled_txg       
>      hole_birth
>      extensible_dataset
>      embedded_data
>      bookmarks
>zpool: ../../lib/libzfs/libzfs_config.c:250: Assertion `nvlist_lookup_nvlist(config, ZPOOL_CONFIG_FEATURE_STATS, &features) == 0' failed.
>Aborted (core dumped)

zpool uprgade ZFS (zfs pool's name)
> [root@pd6 ~]# zpool upgrade ZFS
> This system supports ZFS pool feature flags.
> cannot set property for 'ZFS': invalid argument for this pool operation

/var/log/messages

>Apr 13 14:32:35 pd6 abrt[23946]: Saved core dump of pid 23717 (/sbin/zpool) to /var/spool/abrt/ccpp-2015-04-13-14:32:34-23717 (1560576 bytes)
>Apr 13 14:32:35 pd6 abrtd: Directory 'ccpp-2015-04-13-14:32:34-23717' creation detected
>Apr 13 14:32:35 pd6 abrtd: Package 'zfs' isn't signed with proper key
>Apr 13 14:32:35 pd6 abrtd: 'post-create' on '/var/spool/abrt/ccpp-2015-04-13-14:32:34-23717' exited with 1
>Apr 13 14:32:35 pd6 abrtd: Deleting problem directory '/var/spool/abrt/ccpp-2015-04-13-14:32:34-23717'

**Comment by okket** [comment]
Did you reboot after upgrading the zfs kernel module?

**Comment by x09** [comment]
Oh!! You right!!! All worked fine after reboot.
