### ISSUE TITLE
zpool events undocumented

### ISSUE THREAD

**Issue by beren12** [zfsonlinux/zfs#3286]
Looks like there's no events section in the man page.

**Comment by kpande** [comment]
zpool events -f: provides a running feed similar to "tail -f"

zpool events -H: remove the first printed header

zpool events -c: clear all events and print a string in the format "cleared n events"

So ideally if one were to run zpool events -cHf you'd clear the events before printing the running feed of next events as they appear, but it only clears the events.

**Comment by SenH** [comment]
verbose flag (-v) is also available

**Comment by behlendorf** [comment]
A zfs-events man page was added.
