### ISSUE TITLE
Duplicate ZPool Name causes mount to fail

### ISSUE THREAD

**Issue by ghost** [zfsonlinux/zfs#3291]
My zfs HDD's previously came from Solaris (compatible ZFS version).  Running on Ubuntu 14.04.2.  Everything has been fine up until 0.6.4.  I have always had to import my pool using the id, not the name, since I have 2 pools called "zfs".  The automounting has always worked. Post upgrade, this is no longer the case for mounting zfs on boot.   I had to run "zpool import 14761808417051116593 zfs-new"  Once the name change has occured for the pool, the automounts under /zfs-new work perfectly and it always appears upon reboot.

does the new cache file only try names to import? rather than ID's?

**Comment by GregorKopka** [comment]
It might be that unique pool names are now enforced a bit stricter.
Which is a good idea, since `zfs <something> <pool>/<dataset>` wouldn't be able to decide *which* <pool> to work on in case there could be anbiguous pool names.

**Comment by evilmattyj** [comment]
I forgot to mention that the ZFS from Solaris had totally failed and I had reused the drives, I wanted to keep things similar, hence i created a new pool with the same name.

**Comment by behlendorf** [comment]
Closing.  You'll want to give your pools different names or always import by guid.
