### ISSUE TITLE
nex-3165 segregate ddt in arc

### ISSUE THREAD

**Issue by kpande** [zfsonlinux/zfs#3301]
https://github.com/Nexenta/illumos-nexenta/commit/3f9dfd6487b1569e4f92233b4894dda2f402e85a

this change looks like a useful start to making dedup more tunable.

there are some follow-up commits which change dedup behaviour to use this segregated accounting and disable growth if it overruns DDT size limits. it is not upstream yet, but I feel it warrants inclusion in ZoL because it is relevant to our memory problems.

**Comment by behlendorf** [comment]
This is definitely something we should look in to.

**Comment by kpande** [comment]
This also, may be related to their DDT changes: https://github.com/Nexenta/illumos-nexenta/commit/339d76818f1f006c20d5d5a9809f37f0bc53eb1f

**Comment by kpande** [comment]
It was for this: https://github.com/Nexenta/illumos-nexenta/commit/6ab9242ef8b5eb92c3770f829884a9904f172bf4

**Comment by kpande** [comment]
@behlendorf is this still something we want in ZFS now that we've got #5182?

maybe @alek-p can point out if there were any changes to this since 2015.

**Comment by alek-p** [comment]
I'm happy to help and ID the right commits if someone wants to port these changes however I suspect there are better solutions for some of these dedup shortcomings. Highest impact work would probably be if someone talked to @ahrens and finished https://github.com/ahrens/illumos/tree/dedup

**Comment by alek-p** [comment]
for more context on the work in that branch see: https://www.youtube.com/watch?v=PYxFDBgxFS8
