### ISSUE TITLE
ZFS send receive between different versions of zfs results in more space used and slow volume

### ISSUE THREAD

**Issue by Pentium100MHz** [zfsonlinux/zfs#3306]
Hello,

We use zfs for virtualization and backups. Backups and migration is done using zfs send | zfs recv. I have noticed something strange happening when the versions of zfs are different.

Backups use Centos 6.4 and zfs 0.6.2, the pool is a couple of raidz2s
HV1 uses Debian 7 and zfs 0.6.3, the pool is a mirror
HV2 uses Ubuntu 14.04 LTS and zfs 0.6.4, the pool is raidz1

The datasets being copied are zvols, or rather, datasets containing multiple zvols.

The different versions happened because of various reasons, but for now here we are.

The problem, described with multiple situations where it occurs:
Situation 1:
1. If I copy a dataset from HV1 to HV2 using zfs send | zfs recv, it takes up more space (160GB for a 120GB zvol) and is very slow to access, causing high CPU usage (which is "pinned" on the VM accessing it, not a separate process). The slowness does not come immediately, but after some time. If I restart the virtual machine, then it works well for some time again before becoming slow.
2. If I then copy the data using dd (without recreating the zvol/dataset) then the zvol takes up even more space (180GB) and the problem still exists.

Situation 2:
If I copy a dataset from HV1 to Backups using send|recv, then it takes up even more space (240GB for the same 120GB zvol in addition to 80GB for snapshots).

Is this a known problem with different zfs versions? If so, why doesn't zfs recv warn about this?

**Comment by kpande** [comment]
are you using copies=2 or different compression algo on different servers?

**Comment by kpande** [comment]
Please use the mailing list (http://list.zfsonlinux.org) for these kinds of inquiries because the bug tracker is not a support forum. Only legitimate regressions and bugs should be posted here.

**Comment by Pentium100MHz** [comment]
Sorry. Please delete this.

**Comment by DeHackEd** [comment]
Press the 'Close issue' button at the bottom of this screen.

**Comment by kpande** [comment]
thanks @Pentium100MHz - no hard feelings :-)
