### ISSUE TITLE
'zpool upgrade' not discriminating datasets for version checks

### ISSUE THREAD

**Issue by DeHackEd** [zfsonlinux/zfs#3313]
<pre>
# zpool create test1 /tmp/scratchfile1 -o version=26
# zfs create -V 40M -s test1/zvol
# zpool list
NAME         SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
atmaweapon  2.73T  1.52T  1.20T         -      -    55%  1.00x  ONLINE  -
test1        250M   163K   250M         -      -     0%  1.00x  ONLINE  -
# zpool upgrade test1
This system supports ZFS pool feature flags.

atmaweapon/gentoo-kvm (v13385824) is not supported by this implementation of ZFS.
atmaweapon/c6-lxc (v13385824) is not supported by this implementation of ZFS.
atmaweapon/windows7 (v13385824) is not supported by this implementation of ZFS.
atmaweapon/centos6-template (v13385824) is not supported by this implementation of ZFS.
atmaweapon/centos7 (v13385824) is not supported by this implementation of ZFS.
atmaweapon/fedora20 (v13385824) is not supported by this implementation of ZFS.
...
atmaweapon/ubuntu-13.10 (v13385824) is not supported by this implementation of ZFS.
test1/vol (v13385824) is not supported by this implementation of ZFS.
Upgrade not performed due to 14 unsupported filesystems (max v5).
</pre>

Wat?

All of the above datasets are zvols... most of which are not even on the pool requested.

**Comment by dasjoe** [comment]
I'm running 0.6.4 via the PPA, and I see the same issue:
```
root@interzone ~/zfs # zpool create -f -o ashift=12 TEST mirror /root/zfs/1 /root/zfs/2 -o version=26
root@interzone ~/zfs # zfs create -V 40M TEST/zvol                                                   
root@interzone ~/zfs # zpool upgrade TEST
This system supports ZFS pool feature flags.
 
TEST/zvol (v26763360) is not supported by this implementation of ZFS.
rpool/SWAP (v26763360) is not supported by this implementation of ZFS.
Upgrade not performed due to 2 unsupported filesystems (max v5).
```

**Comment by dweeezil** [comment]
The ```zfs_prop_get_int()``` use throughout libzfs doesn't have any way to communicate any error status to the caller.  Of course it doesn't help that volumes don't even have a ```version``` property but arguably should (different topic altogether).

I'll post a fix for this specific problem shortly but it seems the users of the above-mentioned function ought to be audited.
