### ISSUE TITLE
zfs not mounting

### ISSUE THREAD

**Issue by mikedilger** [zfsonlinux/zfs#3315]
Like #3311, except that I can't mount from the command line either... thus the filesystems are currently inaccessible to me:

```
zig / # zfs mount -a
mount: mount(2) failed: No such file or directory
cannot mount 'z': No such device or address
mount: mount(2) failed: No such file or directory
cannot mount 'z/0.ADMIN': No such device or address
mount: mount(2) failed: No such file or directory
cannot mount 'z/0.BACKUP': No such device or address
mount: mount(2) failed: No such file or directory
cannot mount 'z/ca': No such device or address
mount: mount(2) failed: No such file or directory
```

...etc.

It did make the directories under /z/

`dmesg` shows nothing during this time.

I've been on 0.6.4 (or a commit shortly before that) for a few weeks.   Today I did a lot of operations, creating and deleting filesystems, zfs send and recv, snapshotting etc.   This includes creating filesystems underneath other filesystems.  After these, and after a reboot, the behavior began.

I've removed all zpool.cache files and init scripts and am doing everything by command line now.

Also seems weird that the first 2 lines of output were trying to mount a filesystem 'z' (the pool itself), not sure if that's right or not.

.... WAIT a second, the disk just did a bunch of grinding, and ...
... it mounts again!
Hmm.  That could be a hint...

**Comment by gmelikov** [comment]
Closing as stale. Feel free to reopen it if it's reproducible on latest stable.
