### ISSUE TITLE
casesensitivity=insensitive performance issues

### ISSUE THREAD

**Issue by kpande** [zfsonlinux/zfs#3318]
(documenting this part for Google's sake, as well because I couldn't find an issue I had opened before on the subject)
A couple years ago I was using samba for roaming profiles and file sharing with a handful of Windows 7 iSCSI machines using ZoL. At the time, it was in-between 0.6.2 and 0.6.3 and there were some xattr performance problems which were in the midst of being resolved by xattr=sa.

The production network I was working on had 30 workstations, all identical OS image. When they logged in using roaming profiles on case insensitive share, by the 3rd PC, the smbd processes were spinning with 120s timeouts and some kind of backtraces being printed to the console, but no one could really determine how come ZFS was causing this. Developers for ZoL didn't have much to base it on, but when I used case sensitive shares, things worked as expected - actually, the system became unresponsive again after the 20th PC was logged in, and this was due to xattr. I worked around that (at the time, November 2012) with an ext4 zvol for their samba profiles.

Fast-forward to today, I'm using 0.6.4 on a similar spec'd system. I recently enabled case insensitivity in order to test it out, but I don't have 30 workstations here at home so my full-scale testing is limited.

On that 0.6.2 system, we ran it in a lab for days with stress tests but we did not see the ZFS problems emerge until we put a real workload on the pool - 30 users each have two folders, a .home and a .V2; the .home contains a lot of Office documents, images, downloads - the .V2 contains their Windows user registry and a bunch of tiny/medium-size AppData folders. Talk about frustrating. Something that should have worked, was cripped when used in the real world.

All of this is made relevant by the results of a "test" I inadvertently performed last night running 100 bittorrents on a single Samba share which is on a very fast pool of two WD Blacks in a stripe (no mirroring, I know, I love life so much! I've got backups and this data isn't too important :-)

CPU load goes to 3.00 and stays there, the bittorrents with about 2000+ simultaneous connections are pegged at 3MB/s on a 35MB/s+ internet connection. My router can handle it.. 

When I moved the downloads from insensitive to sensitive filesystem, their rate spiked up to 12MB/s+ and the system load drops to 0.00

So it seems there are some inefficiencies in the way case sensitivity is handled and if used, even with a single user machine on a striped pool you can "easily" (how common is it to run 100 torrents?) drive the box into I/O stalls and miserable performance.

**Comment by ptx0** [comment]
@behlendorf i've been using ext4 zvol to workaround the lack of support

**Comment by sanjeevbagewadi** [comment]
From the description I am assuming that the workload involves substantial amount of lookup/create operations. Is that assumption correct ?

Because, the case-sensitivity matter only during lookup/create and should not affect an actual read/write.
