### ISSUE TITLE
ZoL 0.6.4 zpool status disk name regression on Ubuntu

### ISSUE THREAD

**Issue by d33psky** [zfsonlinux/zfs#3323]
Using 0.6.4-3~trusty packages on Ubuntu 14.04 the disk names with which a pool was made change into sda-like names after a reboot. This prevents identifying a disk by its type and serial number like what was possible on (at least) 0.6.2

For example I make a pool :

zpool create tank raidz2 ata-HGST_HUS724030ALA640_PN1234P8KJRZKX ata-HGST_HUS724030ALA640_PN1234P8KJJNZX ...

and before a reboot these get listed as expected :

zpool status
  pool: tank
 state: ONLINE
  scan: none requested
config:
        NAME                                         STATE     READ WRITE CKSUM
        tank                                         ONLINE       0     0     0
          raidz2-0                                   ONLINE       0     0     0
            ata-HGST_HUS724030ALA640_PN1A38P3G58S1B  ONLINE       0     0     0
            ata-HGST_HUS724030ALA640_PN1A38P3G2GJ2B  ONLINE       0     0     0
...

However after a reboot they show up as :

zpool status
  pool: tank
 state: ONLINE
  scan: none requested
config:
        NAME        STATE     READ WRITE CKSUM
        tank        ONLINE       0     0     0
          raidz2-0  ONLINE       0     0     0
            sdc     ONLINE       0     0     0
            sdd     ONLINE       0     0     0
...

I need these to show with the names the pool was created with.

Extra info from zfs-discuss : this issue does not show on CentOS 6 or EL7 but is confirmed on Ubuntu with this additional info : "Saw this happen on my ubuntu system too after upgrading to 0.6.4
Interesting detail was that it happened only to about half of the drives in the pool. Have 2 different controllers in there.  After a 'zpool export' followed by a 'zpool import -d /dev/disk/by-id'
things are back to normal, even through subsequent reboots."

**Comment by FransUrbo** [comment]
This either belongs to https://github.com/zfsonlinux/pkg-zfs OR on the mailinglist (it looks more like support question than an issue to me). In either case, please move and close it!

**Comment by d33psky** [comment]
Thanks. Will do.

**Comment by mailinglists35** [comment]
"In either case, please move"

no, please do not move this issue elsewhere - because i came straight here (and not pkg-zfs) to search for "by-id" when upgrading from 0.6.3 to 0.6.4 CHANGED my paths from id to sdX names and this could help others, too.

**Comment by kpande** [comment]
@mailinglists35 what does your /etc/default/zfs look like?

**Comment by mailinglists35** [comment]
# ZoL userland configuration.

# Run `zfs mount -a` during system start?
# This should be 'no' if zfs-mountall or a systemd generator
# is available.
ZFS_MOUNT='yes'

# Run `zfs unmount -a` during system stop?
# This should be 'no' on most systems.
ZFS_UNMOUNT='yes'

# Run `zfs share -a` during system start?
# nb: The shareiscsi, sharenfs, and sharesmb dataset properties.
ZFS_SHARE='yes'

# Run `zfs unshare -a` during system stop?
ZFS_UNSHARE='yes'

# Sould we use '-d /dev/disk/by-*' when importing pool.
# This is recomended, but the default 'no' uses the cache
# file.
# Variable is somewhat missleading. Previously the code
# tried _only_ '/dev/disk/by-id', but will now try any
# '/dev/disk/by-*' directory.
USE_DISK_BY_ID='yes'

# Should the datasets be mounted verbosly (a mount counter
# will be used when mounting if set to 'yes').
VERBOSE_MOUNT='no'

# Should we allow overlay mounts (this is standard in Linux,
# but not ZFS which comes from Solaris where this is not allowed).
DO_OVERLAY_MOUNTS='no'

# Any additional option to the 'zfs mount' command line.
# Include '-o' for each option wanted.
MOUNT_EXTRA_OPTIONS=""

# Build kernel modules with the --enable-debug switch?
ZFS_DKMS_ENABLE_DEBUG='no'

# Build kernel modules with the --enable-debug-dmu-tx switch?
ZFS_DKMS_ENABLE_DEBUG_DMU_TX='no'

# Keep debugging symbols in kernel modules?
ZFS_DKMS_DISABLE_STRIP='no'

# Wait for this many seconds in the initrd pre_mountroot?
# This delays startup and should be '0' on most systems.
ZFS_INITRD_PRE_MOUNTROOT_SLEEP='0'

# Wait for this many seconds in the initrd mountroot?
# This delays startup and should be '0' on most systems.
# This might help on systems which have their ZFS root on
# a USB disk that takes just a little longer to be available
ZFS_INITRD_POST_MODPROBE_SLEEP='0'

# List of additional datasets to mount after the root
# dataset is mounted.
#
# The init script will use the mountpoint specified in
# the 'mountpoint' property value in the dataset to
# determine where it should be mounted.
#
# This is a space separated list, and will be mounted
# in the order specified, so if one filesystem depends
# on a previous mountpoint, make sure to put them in
# the right order.
#ZFS_INITRD_ADDITIONAL_DATASETS="rpool/ROOT/usr rpool/ROOT/var"

# List of pools that should NOT be imported at boot
# This is a space separated list.
#ZFS_POOL_EXCEPTIONS="test2"

# Location of the lockfile.
LOCKDIR=/run/lock

**Comment by mailinglists35** [comment]
well it does not "look" exactly like above, can't find an easy way to paste plaintext with lines beginning with # sign on github

**Comment by behlendorf** [comment]
@mailinglists35 you can use triple back-ticks for this, \`\`\`.  Just place them before and after the plain text block, I've updated your comment to include them.

**Comment by kpande** [comment]
it's curious that USE_DISK_BY_ID is yes but your system didn't do that without explicitly exporting/importing -d /dev/disk/by-id
