### ISSUE TITLE
zpool upgrade: cannot set property (0.6.4)

### ISSUE THREAD

**Issue by mattgarber** [zfsonlinux/zfs#3326]
After upgrading to zfs packages 0.6.4-1 on EL6, I'm unable to run `zpool upgrade storage` (pool is named 'storage') or `zpool upgrade -a`, which both return the following error:

cannot set property for 'storage': invalid argument for this pool operation

Presumably this is because the loaded kernel module is 0.6.3-1.2, which can't support what the 0.6.4-1 userspace tools are trying to perform, although in that case I think the error message could be cleaned up to reflect that it can't be run until a reboot due to the current kernel module not supporting the operation (?).

**Comment by DeHackEd** [comment]
Currently mixing and matching of module versions is not supported. You may find some functions (such as importing) don't work at all. Avoid doing this.

In the future the kernel API will be updated for compatibility. Until then try to avoid mixing and matching.

**Comment by mattgarber** [comment]
It's not mixing and matching module versions, it's a mismatch of the userspace components and loaded module version; this happens when you perform an upgrade of the ZFS components on EL6 and can't yet reboot (this is a production hypervisor).

If you run `zpool status`, all of the pools will indicate that they're eligible to be upgraded for the new features, yet the `zpool upgrade` command fails, presumably because of the mismatch. Assuming that's the case though, I think the error generated by that attempt should just be a hair more useful for those who may not understand that they need to reboot for the updated module.

**Comment by mattgarber** [comment]
Actually, to be even more helpful, couldn't the userspace tools detect when there's a mismatch with the loaded module (package upgraded, not rebooted) and print a warning before most command output. Something like:

"WARNING: The ZFS user tools are not the same version as the loaded kernel module. Some functionality may be broken or perform unexpectedly; please reboot or unload/reload with the latest installed kernel modules."


I'd guess that it's actually a fairly common occurrence on servers or other systems that don't get rebooted very often -- or which contain filesystems that can't just have the module unloaded/reloaded on a whim.

**Comment by behlendorf** [comment]
There has been some work along this lines in #2557 but it hasn't been finalized yet.

**Comment by kyrias** [comment]
Just got bit by this after having to do some system updates that happened to include new zfs packages, and it seems that PR was closed with "in practice relying on the version from the packaging has been enough for users".

**Comment by gmelikov** [comment]
Close as stale.

If it's actual - feel free to reopen.

**Comment by pmwoodward3** [comment]
Bumping for visibility

**Comment by ajthemacboy** [comment]
@pmwoodward3 Very offtopic for this thread, but how did you upgrade to 0.7.0? I am trying to build from source and am getting a lot of errors.
