### ISSUE TITLE
zfs functions (mont -a, list, zpool status) extremely slow

### ISSUE THREAD

**Issue by Pentium100MHz** [zfsonlinux/zfs#3329]
Hi,

Our backup server crashed (kernel panic) and I rebooted it, it took three hours to come back online and that was because automounting of datasets took pretty much the entire time. During that time, the activity indicators on the hard drives indicated that the hard drives were idle, with some activity every few seconds.

In addition to that, all zfs functions take up long times.

'zfs list' takes 37 seconds and returns 550 entries
'zfs list -t snapshot' takes 2 minutes 47 seconds and returns 3391 entries
'zpool status' takes 18 seconds (increases if the hard drives are actually used)..

During that time, the hard drives are not fully utilized, according to iostat, the most utilization is around 10%.

OS is CentOS 6.4
ZFS version is 0.6.2  
This is because 0.6.3 has more issues as does newer CentOS 6.x in conjunction with zfs.

Is there a way to speed this up?

**Comment by kpande** [comment]
Please use the mailing list for support unless you're able to verify that this is a ZFS issue - try downgrading if possible to see if the issue goes away, and then incrementally update each revision of ZFS and test until you find an offending commit.

**Comment by Pentium100MHz** [comment]
OK, so I lost the ability to recognize things that do not belong here. Sorry.

**Comment by kpande** [comment]
well, I saw you're using 0.6.2 which is marvelously out of date. 0.6.4 resolves a major issue in RHEL-based older kernels that has to do with memory reclaim never occurring.. on top of that, it's just a very buggy version.

if you have problems with 0.6.4 on RHEL, then you can post it here. until then it's a mailing list thing because you're not using a development branch.

**Comment by Pentium100MHz** [comment]
After the problems with 0.6.3 (and newer CenOS) I'm kinda worried about updating it on this server. But yea, that makes sense. I have posted my question on the mailing list and will see if I can updae the server (and not make things worse).
