### ISSUE TITLE
arc erosion

### ISSUE THREAD

**Issue by antry** [zfsonlinux/zfs#3340]
there are ARC erosion in some workloads (large random write like
fio
bs=4k
sync=1
runtime=240
rw=randwrite
direct=1
iodepth=32
ioengine=libaio
)
MRU ~ arc size and MFU is too small to normal work whith other tasks.and we have to much reads from main pool  when we rewrites.especialy if zvol block size > block_io and we need to read  the whole block from the pool instead of metada.
need parametr like zfs_arc_p_max to left space for MFU.and change arc_adapt() function.

diff arc.c arc.c.orig 
184d183
< unsigned long zfs_arc_p_max = 0 ;
2645a2645

> 2664c2664
> ## < 
> 
> 2666,2667d2665
> < 
> <               arc_p = (zfs_arc_p_max == 0 ? arc_p : MIN(arc_p,zfs_arc_p_max)); 
> 5668,5670d5665
> < 
> < module_param(zfs_arc_p_max, ulong, 0644);
> < MODULE_PARM_DESC(zfs_arc_p_max, "limit arc_p grows");

**Comment by gmelikov** [comment]
Closing as stale. Feel free to reopen it if it's reproducible on latest master.
