### ISSUE TITLE
Missing /etc/zfs/zpool.cache

### ISSUE THREAD

**Issue by CMCDragonkai** [zfsonlinux/zfs#3353]
For some reason, my zpool.cache file no longer exists. This causes `zdb` to crash. I googled around and there's no way to regenerate the zpool.cache file?

This is strange, because it's a clean VM that was created. The ZFS is mounted in a legacy manner by systemd, perhaps this caused the problem?

Similar feature request here: https://www.illumos.org/issues/461 But I'm pretty sure I didn't delete my zpool.cache file.

**Comment by kpande** [comment]
Please use the mailing list as this is not a support forum.

**Comment by CMCDragonkai** [comment]
Sent.
