### ISSUE TITLE
zfs_vdev_scheduler takes newline character

### ISSUE THREAD

**Issue by voidzero** [zfsonlinux/zfs#3356]
This is zfs 0.6.4 on a standard Linux machine. For the rest, I'll let my commands speak for itself:

```
# pwd
/sys/module/zfs/parameters
# cat zfs_vdev_scheduler
noop
# echo cfq > zfs_vdev_scheduler
# cat zfs_vdev_scheduler
cfq

# echo -n cfq > zfs_vdev_scheduler
# cat zfs_vdev_scheduler
cfq
# exit
```

**Comment by gmelikov** [comment]
Close as stale.

If it's actual - feel free to reopen.

**Comment by voidzero** [comment]
Hello. This bug is still open. I don't know how much it matters that the newline isn't trimmed but I guess it's better to make sure that it is - that it gets valid input.

**Comment by voidzero** [comment]
By the way, I can't reopen this issue myself. @gmelikov @behlendorf maybe one of you can take a look?
