### ISSUE TITLE
Removing l2arc blocks IOs to zvol

### ISSUE THREAD

**Issue by pzwahlen** [zfsonlinux/zfs#3358]
I'm using 0.6.4.1 on CentOS 7, exporting zvols to ESXi via scst/vdisk_blockio/iscsi

I have a 4-disks/raidz1 pool (I know, not ideal) and an SSD. L2ARC definitely seems to help, until I have to remove it from the pool.

From what I see, removing the L2ARC cache device can take a very long time (up to 5 minutes measured) _and_ IOs to pool zvols are completely blocked during that time (as reported by scst).

I already reported this to the mailing list a few weeks ago on 0.6.3 but wanted to wait for 0.6.4 for some additional tests. It looks like it didn't change.

It might be a "by design" issue, but it makes ZFS almost impractical for a SAN cluster setup where you expect to switch pools from one node to another in just a few seconds (I would say under 30 seconds).

I can add that the time required for removing the cache device is proportional to how much the L2ARC is used (as reported by arcstat.sh).

**Comment by gmelikov** [comment]
Close as stale.

If it's actual - feel free to reopen.
