### ISSUE TITLE
ZFS-8000-5E after disk id changed

### ISSUE THREAD

**Issue by ospalax** [zfsonlinux/zfs#3359]
Hello,
everywhere is recommended to use /dev/disk/by-id disk path to avoid problem of disk renaming, but what can one do when linux kernel decide to change even these names??

zdb -l shows:
vdev_tree:
        type: 'disk'
        id: 0
        guid: 5448082579735766291
        path: '/dev/disk/by-id/scsi-SATA_C300-CTFDDAC25600000000110703034DDB-part3'

but now after update in debian wheezy I get in /dev/disk/by-id/:
ata-C300-CTFDDAC256MAG_00000000110703034DDB
ata-C300-CTFDDAC256MAG_00000000110703034DDB-part1
ata-C300-CTFDDAC256MAG_00000000110703034DDB-part2
ata-C300-CTFDDAC256MAG_00000000110703034DDB-part3

So this:
scsi-SATA_C300-CTFDDAC25600000000110703034DDB-part3
is now this:
ata-C300-CTFDDAC256MAG_00000000110703034DDB-part3

I had to create simple symlink to import pool again. BTW.: I want to sign under this issue too:
https://github.com/zfsonlinux/zfs/issues/2933

Because when I saw ZFS-8000-5E I almost thought that I really need to reinstall my system....only the hatred to do so force me to found out the cause of this. Very misleading message indeed.

Finally my question:
Can I change this one line permanently somehow?:
path: '/dev/disk/by-id/scsi-SATA_C300-CTFDDAC25600000000110703034DDB-part3'

So I don't have to create dummy symlink and also what naming scheme you suggest when by-id is also completely unsafe?

EDIT:
I found this:
http://www.computersolutions.cn/blog/2013/10/ubuntu-13-diskby-id-name-changes-zfs/

but in my case when I try to do import after export I have two results depending on existence of dummy symlink:
1. I leave the dummy symlink in place => pool is imported again via dummy symlink
2. I delete dummy symlink => I get:
cannot import 'tank': one or more devices are already in use

**Comment by mailinglists35** [comment]
if you have disks partitioned with gpt (or if you are willing to repartition as gpt, I think in theory on you can even do the conversion in-place) you can give names to partitions and they will show under /dev/disks/by-partlabel/
