### ISSUE TITLE
Very slow fsync on an idle filesystem, which shares a pool with a busy filesystem

### ISSUE THREAD

**Issue by haimhelman** [zfsonlinux/zfs#3365]
I have two datasets sharing the same zpool.
root@flash08:~# zfs list
NAME                                     USED  AVAIL  REFER  MOUNTPOINT
pool_vnode154_0                   20.0G  1.76T  12.2M  /pool_vnode154_0
pool_vnode154_0/instance     4.24G  15.8G  4.24G /pool_vnode154_0_instance

The first one is performing heavy write IO. The second one is performing light IO with frequent fsyncs.
I get fsync times of 40+ seconds!
When running that load on two pools (even if they are using the same backend drives) I get ~1 msec fsync times.
Any idea what is the cause and if this is avoidable without separating the pools?

My assumption was that an fsync on a file in one file system does not trigger any IO in the other filesystem and that there is some fairness mechanism in place to prevent one filesystem from starving another filesystem on the same zpool.

Was I wrong on either or both assumptions?

Thanks,
Haim

**Comment by DeHackEd** [comment]
This is probably better suited to the mailing list. This is an issue tracker for bugs, not discussion of how ZFS works.

The pool itself maintains its consistency across the whole pool, not just some datasets. fsync operations of sufficient size will trigger a full TXG flush which means all dirty data across the pool will be committed to disk. Your program will have to wait that out.

You may get better response time by tweaking ZIL parameters to allow the sync to just be written to the ZIL instead.

**Comment by haimhelman** [comment]
You are probably right, will continue this on the mailing list.
