### ISSUE TITLE
ZFS PANIC at pool import

### ISSUE THREAD

**Issue by palica** [zfsonlinux/zfs#3370]
I am runnning 0.6.4.1 and this is what I've got at import. I have upgraded the pool to use the new features. This is a 3-way mirror pool.

VERIFY3(0 == zap_lookup(ddt->ddt_os, ddt->ddt_spa->spa_ddt_stat_object, name, sizeof (uint64_t), sizeof (ddt_histogram_t) / sizeof (uint64_t), &ddt->ddt_histogram[type][class])) failed ( 0 == 6)
PANIC at ddt.c:124:ddt_object_load()

**Comment by behlendorf** [comment]
It appears there's some issue loading the de-duplication table which is preventing the import.  Has dedup ever been enabled on this pool?  Have you tried importing the pool either on FreeBSD or illumos by chance?

**Comment by palica** [comment]
no, dedup was never turned/enabled on this pool.

**Comment by palica** [comment]
I have imported the pool in single user mode and the pool works fine. I run a scrub on the entire pool without error. On next reboot and import I am getting another error now:

VERIFY3(range_tree_space(rt) == space) failed (8051959 == 32980824064)
PANIC at space_map.c:127:space_map_load()

**Comment by dringdahl** [comment]
I received the same error:

Aug  3 09:59:38 san2 kernel: VERIFY3(0 == zap_lookup(ddt->ddt_os, ddt->ddt_spa->spa_ddt_stat_object, name, sizeof (uint64_t), sizeof (ddt_histogram_t) / sizeof (uint64_t), &ddt->ddt_histogram[type][class])) failed (0 == 6)
Aug  3 09:59:38 san2 kernel: PANIC at ddt.c:124:ddt_object_load()

This was on a pool that did have dedup enabled. I found that this error only occurred if I tried to import using the cache. If I imported manually, it imported without issue. This also recreated the cache, which allowed it to import using the cache from that point forward. The cache should not have been corrupt as the system had been shut down cleanly prior to encountering the error. I am running zfs-0.6.4.2-1.el7.centos.x86_64. Please let me know if there is any other information I can provide.

**Comment by behlendorf** [comment]
There error code is ENXIO (6) which would suggest that a device was missing from the pool.  Is it possible the device names changed are were inconsistent with the cache file?  That could explain why removing and cache file and rescanning for all the devices fixed the issue.

Regardless, this shouldn't have been fatal.  We should have simply returned the error here so the user gets a sane error about a problem with the devices.  I'll propose a trivial patch.

**Comment by dringdahl** [comment]
No, no devices were missing. It is a single monolithic device for reasons I won't go into. I know that is sub-optimal for zfs. In any case, the device was available without any issues. Importing using the cache failed but importing manually succeeded.

**Comment by dringdahl** [comment]
I can also confirm that the device name was consistent.

**Comment by behlendorf** [comment]
@dringdahl then I'm not sure what happened here.  I've merged the fix to master which will at least make sure this case is no longer fatal.
