### ISSUE TITLE
Zpool import failure

### ISSUE THREAD

**Issue by roedie** [zfsonlinux/zfs#3390]
After rebooting my server I got:

[   62.011526] SPL: using hostid 0x007f0101
[   69.862719] VERIFY3(size <= rt->rt_space) failed (17632 <= 0)
[   69.862823] PANIC at range_tree.c:248:range_tree_remove()
[   69.862902] Showing stack for process 23300
[   69.862981] CPU: 12 PID: 23300 Comm: zpool Tainted: P           O  3.16.0-0.bpo.4-amd64 #1 Debian 3.16.7-ckt9-3~deb8u1~bpo70+1
[   69.863096] Hardware name: HP ProLiant DL380p Gen8, BIOS P70 09/08/2013
[   69.863207]  0000000000000000 ffffffffa2263060 ffffffff81544e1f ffffffffa2271f50
[   69.863541]  ffffffffa0578f62 ffff8817de438190 ffffffffa22720a8 ffff882d8be15040
[   69.863874]  ffffffff00000030 ffff882db286bad8 ffff882db286ba78 ffff882db4486600
[   69.864188] Call Trace:
[   69.864277]  [<ffffffff81544e1f>] ? dump_stack+0x41/0x51
[   69.864361]  [<ffffffffa0578f62>] ? spl_panic+0xc2/0x100 [spl]
[   69.864443]  [<ffffffff810b0f08>] ? __wake_up+0x48/0x70
[   69.864523]  [<ffffffff81549a3e>] ? mutex_lock+0xe/0x2a
[   69.864611]  [<ffffffffa219d2a2>] ? remove_reference.isra.11+0xd2/0x100 [zfs]
[   69.864694]  [<ffffffff81549a3e>] ? mutex_lock+0xe/0x2a
[   69.864777]  [<ffffffffa21a2df5>] ? arc_buf_eviction_needed+0x95/0xd0 [zfs]
[   69.864864]  [<ffffffffa21a89a0>] ? dbuf_rele_and_unlock+0x250/0x3d0 [zfs]
[   69.864954]  [<ffffffffa224bc3a>] ? zio_wait+0x14a/0x1e0 [zfs]
[   69.865040]  [<ffffffffa21b2e82>] ? dmu_buf_hold_array_by_dnode+0x252/0x570 [zfs]
[   69.865147]  [<ffffffffa21e7724>] ? range_tree_remove+0x1b4/0x330 [zfs]
[   69.865235]  [<ffffffffa21b3a41>] ? dmu_read+0x131/0x180 [zfs]
[   69.865325]  [<ffffffffa220010a>] ? space_map_load+0x22a/0x570 [zfs]
[   69.865415]  [<ffffffffa22054a8>] ? vdev_dtl_load+0xd8/0x110 [zfs]
[   69.865504]  [<ffffffffa2207928>] ? vdev_load+0x68/0xe0 [zfs]
[   69.865591]  [<ffffffffa22078f3>] ? vdev_load+0x33/0xe0 [zfs]
[   69.865679]  [<ffffffffa22078f3>] ? vdev_load+0x33/0xe0 [zfs]
[   69.865768]  [<ffffffffa21f497a>] ? spa_load+0xfba/0x1ba0 [zfs]
[   69.865857]  [<ffffffffa21ed605>] ? spa_activate+0x165/0x450 [zfs]
[   69.865947]  [<ffffffffa21f6888>] ? spa_tryimport+0x98/0x420 [zfs]
[   69.866035]  [<ffffffffa22270ba>] ? zfs_ioc_pool_tryimport+0x5a/0xa0 [zfs]
[   69.866124]  [<ffffffffa222c78f>] ? zfsdev_ioctl+0x4cf/0x510 [zfs]
[   69.866207]  [<ffffffff811cf7c6>] ? do_vfs_ioctl+0x86/0x4e0
[   69.866287]  [<ffffffff811cfcc1>] ? SyS_ioctl+0xa1/0xc0
[   69.866367]  [<ffffffff8154d428>] ? page_fault+0x28/0x30
[   69.866446]  [<ffffffff8154b40d>] ? system_call_fast_compare_end+0x10/0x15

Importing the pool does not seem to be possible. Not sure how to advance from here...

**Comment by ilovezfs** [comment]
If your main goal is to get access to the files, you can try a readonly import:

```
sudo zpool import -o readonly=on mypool
```

**Comment by roedie** [comment]
I will close this one. Seems like the zpool.cache got corrupted somehow.
