### ISSUE TITLE
[Illumos #5376] arc_kmem_reap_now() should not result in clearing arc_no_grow

### ISSUE THREAD

**Issue by kernelOfTruth** [zfsonlinux/zfs#3393]
Posting this here for tracking the port of this commit,

still is existent on recent illumos-gate, not available on ZoL yet,

not sure how easy it is to port but a similar approach certainly would help in low-memory conditions

"I observed a machine writing data at 200-500MB/s. 
mpstat showed that periodically one CPU would become 100% busy for a few
seconds, with heavy crosscall activity. Sometimes the other CPUs would become
idle during this time. I discovered that this was due primarily to
arc_kmem_reap_now()'s calls to kmem_cache_reap_now(), and resulting TLB
shootdowns to remove mappings for freed slabs. There are many opportunities to
improve the kmem/vmem/hat code. However, upon reproducing the issue, I found that ZFS's
ARC management can also be improved to reduce the frequency and duration of
these xcall storms. The primary observation is that we should not clear
arc_no_grow after calling arc_kmem_reap_now(). One way to prevent this would
be to have an idea of when we are getting low on memory before we actually have
to call arc_kmem_reap_now(), to not allow arc_no_grow to be cleared when we are
low on memory, and to ensure that arc_shrink() will keep us in the "low on
memory" region in the absence of other interactions. Implementing this fix
resulted in much less frequent calls to arc_kmem_reap_now() under a synthetic
workload."

https://www.illumos.org/issues/5376

https://github.com/illumos/illumos-gate/commit/2ec99e3e987d8aa273f1e9ba2b983557d058198c

**Comment by DeHackEd** [comment]
I had actually examined this patch yesterday. It's largely incompatible with ZoL right now due to ab26409db753bb087842ab6f1af943f3386c764f.

**Comment by kernelOfTruth** [comment]
@DeHackEd thanks for taking a look at this - okay, so perhaps ZFSonLinux' codebase isn't even affected by that problem

**Comment by DeHackEd** [comment]
I'm not entirely sure. I just saw that it would be more than just a few minutes' work, noted the reason, and marked the patch as such.

The various VFS integration issues have caused the pruning behaviour to be changed in ZoL a fair bit. It's something we'll have to look at in more detail but I leave that to those who know the code better than I.

**Comment by loli10K** [comment]
_9018 Replace kmem_cache_reap_now() with kmem_cache_reap_soon()_ has recently landed in illumos-gate (https://github.com/illumos/illumos-gate/commit/36a64e62848b51ac5a9a5216e894ec723cfef14e), `kmem_cache_reap_now()` is no more; we can probably close this in the next OpenZFS sync?

**Comment by behlendorf** [comment]
Closing.  This isn't as much of an issue on Linux since the kernel's memory reclaim mechanisms are very different than on Illumos.
