### ISSUE TITLE
Suboptimal performance with zvols over 10gb ethernet

### ISSUE THREAD

**Issue by dswartz** [zfsonlinux/zfs#3394]
So I have a vsphere host linked to a Linux server with 10gbe ethernet.  I created an 8-disk raid10 array with 1TB SAS nearline drives.  I then export a zvol to vsphere using SCST.  If I set sync=disabled, I can get 350MB/sec reads on the guest, running crystaldiskmark.  Writes are slightly slower (320MB/sec).  If I set up a mdraid raid-10 with the same exact disks, and export the block device using vdisk_fileio (to take advantage of linux page cache), I can get more than 500MB/sec on reads.  If I set the SCST cache to writeback, writes are about the same.  When I was using a 1gbe link, the same HW setup could saturate the 1gbe link.  I don't know why ZoL is underperforming this badly.  Some tuning needed?  Something fundamental in the current codebase?

**Comment by kpande** [comment]
FYI, blockio and fileio both use page cache with SCST. IET is the only linux target (that I know of) which avoids cache using blockio.

**Comment by pzwahlen** [comment]
Are you really sure about that ? All the SCST documentation available mentions that blockio completely bypasses the Linux cache. I tend to agree based on what I experienced when running SCST over drbd.

It's only when I migrated to ZFS/ZVOLs that I started to have the Linux cache being used somehow.

Cheers!

PS: I'm really interested in a solid iSCSI/SCST over ZVOL setup (for ESXi in my case). Based on what I have seen so far, I don't understand how commercial ZoL-based solutions can sell, as we're probably still a few releases away from something reliable enough.

**Comment by dswartz** [comment]
Agreed.

**Comment by dswartz** [comment]
Now that I'm not on my mobile device.  I think there is often confusion vis-a-vis vdisk_blockio and vdisk_fileio using a block device (with SCST of course.)  The former absolutely does not involve the linux page cache, and the latter does.  If SCST is using a ZVOL, this all changes, so there is no point to using vdisk_fileio that I can see.

**Comment by dswartz** [comment]
To amend my previous post: vdisk_fileio does makes sense with ZFS if you are not serving up block storage via zvols.  Due to the performance hit, and the fact that esos makes it so easy to serve up file-based LUNs, what I did was to create a ZFS dataset.  Then use 'dd' to create sparse LUN files, and export them via vdisk_fileio handler.  Works very nicely, and if I have to extend the LUN, it's trivial.  I did need to remember to set a reservation on the dataset for quasi 'thick' VMFS LUNs...

**Comment by kaazoo** [comment]
I didn't see this issue before and created another one at #4211, because I thought my results were more based on the fact that I also use ZFS on top of the iSCSI disk.

**Comment by pzwahlen** [comment]
Just wanted to add that on my quest to a stable iSCSI storage for ESXi I also moved from SCST vdisk_blockio to vdisk_fileio and the performance are days and nights compared to ZVOLs.

iowait went from 20-30% down to 1-2% with the exact same workload.

I would tend to agree that we have a problem when using ZVOLs with SCST, but it might not be a ZFS issue.

**Comment by dswartz** [comment]
On 2016-01-18 16:46, pzwahlen wrote:
> Just wanted to add that on my quest to a stable iSCSI storage for ESXi
> I also moved from SCST vdisk_blockio to vdisk_fileio and the
> performance are days and nights compared to ZVOLs.
> 
> iowait went from 20-30% down to 1-2% with the exact same workload.
> 
> I would tend to agree that we have a problem when using ZVOLs with
> SCST, but it might not be a ZFS issue.

Hard to say.  Before I built esos with zfs support, I was using it with 
mdraid+lvm, and I tried scst_fileio and scst_blockio.  I don't have hard 
numbers, but I don't remember the performance being very different...

**Comment by kpande** [comment]
@dswartz is this still happening with the modern zvol implementation? can you try a target other than SCST which has been shown to misbehave with ZFS? we're using LIO with success. please reopen the issue if it's still a concern.
