### ISSUE TITLE
How to apply multipath to ZFS system?

### ISSUE THREAD

**Issue by daringpig** [zfsonlinux/zfs#3399]
I have a machine with two controllers, in which there is 24 disks. And the zfs-0.6.4 is running on it.
Now I want to use the self-contained multipathd to the  machine. how should I use the multipath to the zfs device. For example, should I export the disk through multipath and iscsi, and create the zpool on the multipath device, or should I create the zpool with the local device and multipath it ?
thank you ~~

**Comment by DeHackEd** [comment]
This is an issue tracker, not a support forum. I suggest using the mailing list instead.

**Comment by TioNisla** [comment]
google "dm multipath"
