### ISSUE TITLE
can't open objset

### ISSUE THREAD

**Issue by edillmann** [zfsonlinux/zfs#3401]
Since upgrade on latest master, I get the following kernel message on zpool import

zpool import bfs
dmesg :
[ 2733.340548] WARNING: can't open objset for bfs/vms/vm4501
[ 2736.234109] WARNING: can't open objset for bfs/vms/vm4501, error 2 

error 2 is ENOENT

The dataset is not visible with zfs list, it cannot be destroyed nor recreated,

zdb -d bfs bfs/vms/vm4501 gives:

Dataset mos [META], ID 0, cr_txg 4, 1.58G, 4571 objects

    Object  lvl   iblk   dblk  dsize  lsize   %full  type
         0    3    16K    16K  9.06M  18.0M   12.39  DMU dnode

The message seem's to be generated into zil.c @ line 2286

Is my data lost ?

Regards,
Eric

**Comment by ilovezfs** [comment]
Just had the same problem. Reverting to kernel 3.19 and 0.6.4 allowed it to import fine.

**Comment by ilovezfs** [comment]
http://i.imgur.com/pwhdO4S.png

**Comment by edillmann** [comment]
Unfortunately I already did a zpool upgrade to give largeblocks a try :-(

FYI, Kernel is 4.0.0, the dataset is the only one where I "played" with bookmarks...

**Comment by ilovezfs** [comment]
For me it was 4.0.2, so that helps rules out any specific issue with the 4.0.1->4.0.2 upgrade I'd done.

**Comment by behlendorf** [comment]
@edillmann your data is most likely fine.  From what you've described I think you ran in to [illumos 5393](https://www.illumos.org/issues/5393).  This is an issue which would only impact dataset set which had used something like bookmarks but not largeblocks. There is a fix I had planned to merge as part of the large block patches but it slipped my mind.  Can you apply the patch in #3403 and verify it resolves your issue.

**Comment by edillmann** [comment]
@behlendorf thank's for that quick patch which resolv this issue

**Comment by behlendorf** [comment]
The fix for this has been merged to master.  @edillmann thanks for the quick verification of the fix.
