### ISSUE TITLE
compiling on debian gives syntax error

### ISSUE THREAD

**Issue by gregfr** [zfsonlinux/zfs#3406]
I've set up an completly new debian 7.8 box (kernel 2.6.32).

While compiling, I get the following:

    make -C /usr/src/linux-headers-.. SUBDIRS=`pwd`  CONFIG_ZFS=m modules
    expr: syntax error

then the file /lib/modules/../modules.order has disppeared, I have to re-install the kernel package to get it back.

later make check gives an error:

    Failed to load spl (/usr/local/src/spl-0.6.4.1/.../module/spl/spl.ko)
    zfs.sh: Failed to load modules

it seems something wrong in the makefile deletes files from /lib/modules/../modules...

**Comment by behlendorf** [comment]
Could you include the exact procedure you're using to build.  I'm able to build on Debian just fine.

**Comment by gregfr** [comment]
Really standard, like I've been doing for every zfs install in the past:

    wget http://archive.zfsonlinux.org/downloads/zfsonlinux/spl/spl-0.6.4.1.tar.gz
    tar xzf spl-0.6.4.1.tar.gz
    cd spl-0.6.4.1/
    ./configure
    make
    make install
    make check

The system is in French, not sure if it changes anything... do you want me to do a make clean and send you the whole output of a new make?

**Comment by gregfr** [comment]
Just did a make clean and the first lines are:

    Making clean in module
    make[1]: entrant dans le répertoire « /root/src/spl-0.6.4.1/module »
    make -C /usr/src/linux-headers-2.6.32-38-pve SUBDIRS=`pwd`  clean
    expr: erreur de syntaxe
    make[2]: entrant dans le répertoire « /usr/src/linux-headers-2.6.32-38-pve »
      CLEAN   /root/src/spl-0.6.4.1/module/.tmp_versions

"erreur de syntaxe" means "syntax error"

**Comment by gregfr** [comment]
I did:
    export LANG=C
    export LANGUAGE=C
    export LC_ALL=C

and a new make clean, the output is the same:

    Making clean in module
    make[1]: Entering directory `/root/src/spl-0.6.4.1/module'
    make -C /usr/src/linux-headers-2.6.32-38-pve SUBDIRS=`pwd`  clean
    expr: syntax error
    make[2]: Entering directory `/usr/src/linux-headers-2.6.32-38-pve'

**Comment by gregfr** [comment]
Note that at the end I still get the modules installed:

    $ modinfo zfs
    filename:       /lib/modules/2.6.32-38-pve/zfs/zfs.ko
    version:        0.6.4.1-1
    license:        CDDL
    author:         OpenZFS on Linux
    description:    ZFS
    srcversion:     8324F6AEA2A06B2B6F0A0F5
    depends:        spl,znvpair,zcommon,zunicode,zavl
    vermagic:       2.6.32-38-pve SMP mod_unload modversions

**Comment by behlendorf** [comment]
Closing. Official packages are now provided by Debian.
