### ISSUE TITLE
Iterative ZFS volume migration over network

### ISSUE THREAD

**Issue by pavel-odintsov** [zfsonlinux/zfs#3407]
Hello, folks!

I working with thousands of Linux containers and use live migration every day. Unfortunately, I should use OpenVZ's ploop disk layout on top of ext4 for implementing this case because ZFS lacks of require features for me.

For live migration we need implement following approach:
- We send whole ZFS volume blocks from source to target machine
- We send changed since last sync blocks to target machine
- We send changed since last sync blocks to target machine
  .....
- We found very small amount of changed blocks and call external command for stopping any disk activity for this volume. 

This approach implemented in ploop tool http://openvz.org/Man/ploop.8:

``` bash
This command enables the in-kernel write tracker for the specified ploop device, then
sends all the  data blocks from the top delta image to a pipe specified by the output_fd
argument (stdout, i.e. 1 by default), supposedly read by destination ploop copy, or a file.
After that, it iteratively gets the list of the modified data blocks from the kernel and sends
those blocks again. After a number of iterations (or when the list is empty), it executes the 
stop_command (this could be vzctl stop or vzctl chkpnt) and does the last iteration of
sending the modified data blocks. Finally, it checks that the data were not modified,
error is returned otherwise.
```

This feature could be implemented with some hacks but really zero downtime way to migrate one volume to another server will be very useful for all Community.

**Comment by kernelOfTruth** [comment]
referencing old issue: https://github.com/zfsonlinux/zfs/issues/2458

**Comment by kpande** [comment]
see the presentation from OVH on 'zMotion', a technique for migrating hosts via NFS.
