### ISSUE TITLE
GRUB (grub-mkconfig) unable to detect ZFS root

### ISSUE THREAD

**Issue by sempervictus** [zfsonlinux/zfs#3424]
Using ZFS HEAD on a new EFI host following the ZFS root manual, i'm finding that we have serious issues with ZFS and GRUB on Ubuntu:
1 - packages have not been updated since raring
2 - old packages depend on libzfs1, libzfs2 has the information needed to process large-block pools
3 - dependency hell is breaking out between grub-efi-amd64-signed and ZFS packages
4 - it appears to presently not be possible to install ZFS root systems on Ubuntu under EFI.
5 - update-grub (grub-mkconfig) fails to determine what / is, grub-probe -v -d /dev/root_crypt works though (shows ZFS). This configuration has ZFS atop dm-crypt with separate /boot and EFI partitions.

**Comment by mk01** [comment]
@sempervictus 

as a workaround call grub-install directly with params --boot-directory and --efi-directory .
it even doesn't need extra partitions, I use the gpt9 what zfs creates on each disk. it has 8MB size but grub is fine with 1mb efi loader

**Comment by kpande** [comment]
going to close this because of its age - if you can break it out into separate issues that are still ongoing, that would be best
