### ISSUE TITLE
A few zpool attach commands one after the other fail

### ISSUE THREAD

**Issue by arturpzol** [zfsonlinux/zfs#3442]
Hello,

We are using ZOL 0.6.4-1 version with Debian Jessie with kernel 3.10.36 and testing quickly attaching disk to zpool.

The pool has simple structure:

"
zpool status
  pool: Pool-0
 state: ONLINE
  scan: resilvered 132M in 0h0m with 0 errors on Tue May 26 10:01:59 2015
config:

```
    NAME                      STATE     READ WRITE CKSUM
    Pool-0                    ONLINE       0     0     0
      wwn-0x50000c0f01d54a34  ONLINE       0     0     0
```

errors: No known data errors
"

When we run below script:

"
while true; do 
   zpool attach Pool-0 wwn-0x50000c0f01d54a34 wwn-0x50000c0f01d40f38 -f
   zpool attach Pool-0 wwn-0x50000c0f01d54a34 wwn-0x50000c0f01d4f7a4 -f
   zpool attach Pool-0 wwn-0x50000c0f01d54a34 wwn-0x50000c0f01cac098 -f
   zpool detach Pool-0 wwn-0x50000c0f01d40f38
   zpool detach Pool-0 wwn-0x50000c0f01cac098
   zpool detach Pool-0 wwn-0x50000c0f01d4f7a4
done
"
from time to time get error "no such pool or dataset":

"
- true
- zpool attach Pool-0 wwn-0x50000c0f01d54a34 wwn-0x50000c0f01d40f38 -f
- zpool attach Pool-0 wwn-0x50000c0f01d54a34 wwn-0x50000c0f01d4f7a4 -f
  cannot attach wwn-0x50000c0f01d4f7a4 to wwn-0x50000c0f01d54a34: no such pool or dataset
- zpool attach Pool-0 wwn-0x50000c0f01d54a34 wwn-0x50000c0f01cac098 -f
- zpool detach Pool-0 wwn-0x50000c0f01d40f38
- zpool detach Pool-0 wwn-0x50000c0f01cac098
- zpool detach Pool-0 wwn-0x50000c0f01d4f7a4
  cannot detach wwn-0x50000c0f01d4f7a4: no such device in pool
- true
- zpool attach Pool-0 wwn-0x50000c0f01d54a34 wwn-0x50000c0f01d40f38 -f
- zpool attach Pool-0 wwn-0x50000c0f01d54a34 wwn-0x50000c0f01d4f7a4 -f
  cannot attach wwn-0x50000c0f01d4f7a4 to wwn-0x50000c0f01d54a34: no such pool or dataset
- zpool attach Pool-0 wwn-0x50000c0f01d54a34 wwn-0x50000c0f01cac098 -f
- zpool detach Pool-0 wwn-0x50000c0f01d40f38
- zpool detach Pool-0 wwn-0x50000c0f01cac098
- zpool detach Pool-0 wwn-0x50000c0f01d4f7a4
  cannot detach wwn-0x50000c0f01d4f7a4: no such device in pool
- true
- zpool attach Pool-0 wwn-0x50000c0f01d54a34 wwn-0x50000c0f01d40f38 -f
- zpool attach Pool-0 wwn-0x50000c0f01d54a34 wwn-0x50000c0f01d4f7a4 -f
- zpool attach Pool-0 wwn-0x50000c0f01d54a34 wwn-0x50000c0f01cac098 -f
- zpool detach Pool-0 wwn-0x50000c0f01d40f38
- zpool detach Pool-0 wwn-0x50000c0f01cac098
- zpool detach Pool-0 wwn-0x50000c0f01d4f7a4
- true
- zpool attach Pool-0 wwn-0x50000c0f01d54a34 wwn-0x50000c0f01d40f38 -f
- zpool attach Pool-0 wwn-0x50000c0f01d54a34 wwn-0x50000c0f01d4f7a4 -f
  cannot attach wwn-0x50000c0f01d4f7a4 to wwn-0x50000c0f01d54a34: no such pool or dataset
- zpool attach Pool-0 wwn-0x50000c0f01d54a34 wwn-0x50000c0f01cac098 -f
  cannot attach wwn-0x50000c0f01cac098 to wwn-0x50000c0f01d54a34: no such pool or dataset
- zpool detach Pool-0 wwn-0x50000c0f01d40f38
- zpool detach Pool-0 wwn-0x50000c0f01cac098
  cannot detach wwn-0x50000c0f01cac098: no such device in pool
- zpool detach Pool-0 wwn-0x50000c0f01d4f7a4
  cannot detach wwn-0x50000c0f01d4f7a4: no such device in pool
- true
- zpool attach Pool-0 wwn-0x50000c0f01d54a34 wwn-0x50000c0f01d40f38 -f
  cannot attach wwn-0x50000c0f01d40f38 to wwn-0x50000c0f01d54a34: no such pool or dataset
- zpool attach Pool-0 wwn-0x50000c0f01d54a34 wwn-0x50000c0f01d4f7a4 -f
  cannot attach wwn-0x50000c0f01d4f7a4 to wwn-0x50000c0f01d54a34: no such pool or dataset
- zpool attach Pool-0 wwn-0x50000c0f01d54a34 wwn-0x50000c0f01cac098 -f
  cannot attach wwn-0x50000c0f01cac098 to wwn-0x50000c0f01d54a34: no such pool or dataset
- zpool detach Pool-0 wwn-0x50000c0f01d40f38
  cannot detach wwn-0x50000c0f01d40f38: no such device in pool
- zpool detach Pool-0 wwn-0x50000c0f01cac098
  cannot detach wwn-0x50000c0f01cac098: no such device in pool
- zpool detach Pool-0 wwn-0x50000c0f01d4f7a4
  cannot detach wwn-0x50000c0f01d4f7a4: no such device in pool
- true
- zpool attach Pool-0 wwn-0x50000c0f01d54a34 wwn-0x50000c0f01d40f38 -f
  cannot attach wwn-0x50000c0f01d40f38 to wwn-0x50000c0f01d54a34: no such pool or dataset
- zpool attach Pool-0 wwn-0x50000c0f01d54a34 wwn-0x50000c0f01d4f7a4 -f
  cannot attach wwn-0x50000c0f01d4f7a4 to wwn-0x50000c0f01d54a34: no such pool or dataset
- zpool attach Pool-0 wwn-0x50000c0f01d54a34 wwn-0x50000c0f01cac098 -f
  cannot attach wwn-0x50000c0f01cac098 to wwn-0x50000c0f01d54a34: no such pool or dataset
- zpool detach Pool-0 wwn-0x50000c0f01d40f38
  cannot detach wwn-0x50000c0f01d40f38: no such device in pool
- zpool detach Pool-0 wwn-0x50000c0f01cac098
  cannot detach wwn-0x50000c0f01cac098: no such device in pool
- zpool detach Pool-0 wwn-0x50000c0f01d4f7a4
  cannot detach wwn-0x50000c0f01d4f7a4: no such device in pool
- true
  "

We suppose that for small resilvering time zpool attach action is not possible.

We tried to solve the problem using: 

udevadm settle
blockdev --rereadpt

but nothing helped.

I'd like to know is anyone has experienced a similar problem? Any idea?

**Comment by ilovezfs** [comment]
Try exporting the pool, and then reimporting it like this:

```
zpool import -d /dev Pool-whatever
```

Then retry a <code>zpool attach</code> using the sd* or hd* names in the output of <code>zpool status</code> and <code>lsblk</code>.

**Comment by arturpzol** [comment]
I forced importing pool using below command:

zpool import 14284847540706065840 Pool-0 -f -d /dev/disk/by-id/ -N

because it improve import time in environment with many disks. Whether it has an impact for zpool attach operation? 

Please note that attach action fails from time to time not always. When I execute the attach again, command ends successfully.

**Comment by arturpzol** [comment]
Small feedback from research:

When I removed below line from 60-persistent-storage.rules udev rule problem is temporary solved:

KERNEL!="sr*", OPTIONS+="watch"

I suppose that udev "watching" generates much more events (change and remove) than without it so zpool binary is a little bit confused.
