### ISSUE TITLE
BUG: unable to handle kernel paging request @ dmu_write (32-bit only?)

### ISSUE THREAD

**Issue by Dagger6497** [zfsonlinux/zfs#3447]
I'm trying to run ZOL on a 32-bit machine. It seems to mostly be working fine, but attempting to run certain programs on a ZFS filesystem causes the kernel oops shown below. The system stays up afterwards, but ZFS hangs and won't respond to anything.

In this case, I was running `apt-get install <package>` with /var/cache/apt/ on a ZFS filesystem. There is definitely other software that triggers this failure (e.g. if I use ZFS root and log into XFCE, the whole system hangs -- I can't get the bug output for that though, because the kernel doesn't write it to disk). However, `dd` to a file on the filesystem works fine, as does `git clone`ing the ZOL repository. I don't know what `apt-get` does differently. I also don't know for sure if this is 32-bit only, but it seems likely.

I'm using 65037d9b25c2bfa98d0aa5c9e34678127c03b345. I've also tried with 98b254188a730553361adfabca9f658421be2b82, which is the commit immediately before c9520ecc0f4693cf6fbc3f678555268dc2b91089; it made no difference. (In both cases I was using SPL commit zfsonlinux/spl@dc5e8b70416e5d511bc361309bd426c767177723.)

I'm not really sure where to go from here, or if there's even any interest in fixing it, but I couldn't find any recent bugs that look like they might cover this so I figured I should file one rather than just ignore it. Issue #379 and issue #757 look fairly similar, but were both closed for old age.

Kernel: 3.16.0-4-686-pae
Distro: Debian Jessie (stable).

May 26 22:04:10 laptop kernel: [10428.746740] BUG: unable to handle kernel paging request at ff7fd000
May 26 22:04:10 laptop kernel: [10428.746968] IP: [<c125aff4>] memcpy+0x14/0x30
May 26 22:04:10 laptop kernel: [10428.747118] *pdpt = 0000000001716001 *pde = 000000000179d067 *pte = 0000000000000000
May 26 22:04:10 laptop kernel: [10428.747389] Oops: 0000 [# 1] SMP
May 26 22:04:10 laptop kernel: [10428.747521] Modules linked in: zfs(PO) zunicode(PO) zcommon(PO) znvpair(PO) spl(O) zavl(PO) lib80211_crypt_ccmp cpufreq_conservative cpufreq_userspace cpufreq_powersave bnep cpufreq_stats i8k nfsd auth_rpcgss oid_registry nfs_acl nfs lockd fscache sunrpc joydev pcmcia iTCO_wdt iTCO_vendor_support dell_laptop dcdbas snd_intel8x0 snd_ac97_codec snd_pcm snd_timer psmouse evdev snd pcspkr serio_raw soundcore ac97_bus ipw2200 libipw cfg80211 ecb lpc_ich mfd_core rng_core lib80211 btusb bluetooth yenta_socket 6lowpan_iphc pcmcia_rsrc pcmcia_core radeon ttm drm_kms_helper drm i2c_algo_bit i2c_core rfkill button irda crc_ccitt tpm_tis tpm video battery ac shpchp phc_intel(O) processor fuse parport_pc ppdev lp parport autofs4 ext4 crc16 mbcache jbd2 sg sd_mod crc_t10dif crct10dif_generic crct10dif_common ata_generic ata_piix ahci libahci libata scsi_mod ehci_pci tg3 ptp pps_core libphy thermal thermal_sys uhci_hcd ehci_hcd usbcore usb_common [last unloaded: zavl]
May 26 22:04:10 laptop kernel: [10428.748005] CPU: 0 PID: 5949 Comm: apt-get Tainted: P           O  3.16.0-4-686-pae # 1 Debian 3.16.7-ckt9-3~deb8u1
May 26 22:04:10 laptop kernel: [10428.748005] Hardware name: Dell Inc. Latitude D610, BIOS A06 10/02/2005
May 26 22:04:10 laptop kernel: [10428.748005] task: c4e1a010 ti: c08fe000 task.ti: c08fe000
May 26 22:04:10 laptop kernel: [10428.748005] EIP: 0060:[<c125aff4>] EFLAGS: 00010206 CPU: 0
May 26 22:04:10 laptop kernel: [10428.748005] EIP is at memcpy+0x14/0x30
May 26 22:04:10 laptop kernel: [10428.748005] EAX: d449e000 EBX: 00020000 ECX: 00007c00 EDX: ff7fc000
May 26 22:04:10 laptop kernel: [10428.748005] ESI: ff7fd000 EDI: d449f000 EBP: c08ffce0 ESP: c08ffcd4
May 26 22:04:10 laptop kernel: [10428.748005]  DS: 007b ES: 007b FS: 00d8 GS: 00e0 SS: 0068
May 26 22:04:10 laptop kernel: [10428.748005] CR0: 80050033 CR2: ff7fd000 CR3: 0092c000 CR4: 000007f0
May 26 22:04:10 laptop kernel: [10428.748005] Stack:
May 26 22:04:10 laptop kernel: [10428.748005]  cb38b018 00020000 00000000 c08ffd30 d0a39e40 00000000 00000000 01800000
May 26 22:04:10 laptop kernel: [10428.748005]  00000000 00000000 d0aeaf97 c08ffd20 c08ffd1c 00000000 00000000 00000000
May 26 22:04:10 laptop kernel: [10428.748005]  cb38b018 00000000 c4fc0000 000000c0 cb07f700 c48376ec c4f6c000 c08ffdec
May 26 22:04:10 laptop kernel: [10428.748005] Call Trace:
May 26 22:04:10 laptop kernel: [10428.748005]  [<d0a39e40>] ? dmu_write.part.7+0x90/0x1e0 [zfs]
May 26 22:04:10 laptop kernel: [10428.748005]  [<d0aca6f9>] ? zfs_putpage+0x2c9/0x490 [zfs]
May 26 22:04:10 laptop kernel: [10428.748005]  [<c11476e2>] ? rmap_walk+0x122/0x2a0
May 26 22:04:10 laptop kernel: [10428.748005]  [<c11479bd>] ? page_mkclean+0x5d/0x80
May 26 22:04:10 laptop kernel: [10428.748005]  [<c1196510>] ? __set_page_dirty_buffers+0x20/0xa0
May 26 22:04:10 laptop kernel: [10428.748005]  [<d0addfaf>] ? zpl_putpage+0x2f/0x40 [zfs]
May 26 22:04:10 laptop kernel: [10428.748005]  [<d0addf80>] ? zpl_fh_to_dentry+0xb0/0xb0 [zfs]
May 26 22:04:10 laptop kernel: [10428.748005]  [<c111fe93>] ? write_cache_pages+0x1a3/0x3c0
May 26 22:04:10 laptop kernel: [10428.748005]  [<d0addf80>] ? zpl_fh_to_dentry+0xb0/0xb0 [zfs]
May 26 22:04:10 laptop kernel: [10428.748005]  [<c1479cd0>] ? mutex_lock+0x10/0x28
May 26 22:04:10 laptop kernel: [10428.748005]  [<d0a73b4c>] ? rrw_exit+0x4c/0x130 [zfs]
May 26 22:04:10 laptop kernel: [10428.748005]  [<c113bc31>] ? do_wp_page+0x3c1/0x840
May 26 22:04:10 laptop kernel: [10428.748005]  [<d0ade09e>] ? zpl_writepages+0x7e/0x140 [zfs]
May 26 22:04:10 laptop kernel: [10428.748005]  [<c11215ba>] ? do_writepages+0x1a/0x40
May 26 22:04:10 laptop kernel: [10428.748005]  [<c1118614>] ? __filemap_fdatawrite_range+0x54/0x60
May 26 22:04:10 laptop kernel: [10428.748005]  [<c1118759>] ? filemap_write_and_wait_range+0x39/0x80
May 26 22:04:10 laptop kernel: [10428.748005]  [<d0ade224>] ? zpl_fsync+0x44/0xa0 [zfs]
May 26 22:04:10 laptop kernel: [10428.748005]  [<d0ade1e0>] ? zpl_readpage+0x80/0x80 [zfs]
May 26 22:04:10 laptop kernel: [10428.748005]  [<c1194b4e>] ? vfs_fsync_range+0x2e/0x40
May 26 22:04:10 laptop kernel: [10428.748005]  [<c1145b0a>] ? SyS_msync+0x1fa/0x250
May 26 22:04:10 laptop kernel: [10428.748005]  [<c147bcdf>] ? sysenter_do_call+0x12/0x12
May 26 22:04:10 laptop kernel: [10428.748005] Code: 54 2b 43 50 88 43 4e 5b 5d c3 90 8d 74 26 00 e8 63 fc ff ff eb e8 90 55 89 e5 57 56 53 3e 8d 74 26 00 89 cb 89 c7 c1 e9 02 89 d6 <f3> a5 89 d9 83 e1 03 74 02 f3 a4 5b 5e 5f 5d c3 8d b6 00 00 00
May 26 22:04:10 laptop kernel: [10428.748005] EIP: [<c125aff4>] memcpy+0x14/0x30 SS:ESP 0068:c08ffcd4
May 26 22:04:10 laptop kernel: [10428.748005] CR2: 00000000ff7fd000
May 26 22:04:10 laptop kernel: [10428.748005] ---[ end trace 1db0c73b4d24ec2c ]---

**Comment by behlendorf** [comment]
Closing, resolved by #2505.
