### ISSUE TITLE
Default write throttle settings limit writes to <13 MB/s on systems with <640 MB of RAM

### ISSUE THREAD

**Issue by Dagger6497** [zfsonlinux/zfs#3453]
I just installed ZoL on my laptop. Reads are working perfectly fine, but writes are a tad slower than I'd hoped for:

```
# dd if=/test/256M of=/256M bs=1M; dd if=/256M of=/test/256M-2 bs=1M
256+0 records in
256+0 records out
268435456 bytes (268 MB) copied, 2.97928 s, 90.1 MB/s
256+0 records in
256+0 records out
268435456 bytes (268 MB) copied, 82.2776 s, 3.3 MB/s
```

`zpool iostat 1` looks like this:

```
test        6.68G  4.45G    445      0  55.5M      0
test        6.68G  4.45G    688      0  86.1M      0
test        6.68G  4.45G    675      0  84.3M      0
test        6.68G  4.45G    231      0  28.9M      0
test        6.68G  4.45G      0      0      0      0
test        6.69G  4.43G      0    197      0  14.7M
test        6.69G  4.43G      0      0      0      0
test        6.69G  4.43G      0      0      0      0
test        6.69G  4.43G      0      0      0      0
test        6.69G  4.43G      0      0      0      0
test        6.71G  4.42G      2    218  3.99K  14.7M
test        6.71G  4.42G      0      0      0      0
test        6.71G  4.42G      0      0      0      0
test        6.71G  4.42G      0      0      0      0
test        6.71G  4.42G      0      0      0      0
test        6.71G  4.42G      5    200  5.99K  14.9M
test        6.71G  4.42G      0      0      0      0
test        6.71G  4.42G      0      0      0      0
test        6.71G  4.42G      0      0      0      0
test        6.71G  4.42G      0      0      0      0
test        6.72G  4.40G      7    201  11.5K  14.9M
test        6.72G  4.40G      0      0      0      0
```

That looks weird. ZFS writes 15 MB every 5 seconds, and then just sits there doing nothing for the rest of the time. No CPU usage or disk activity either. What gives?

With some input from ryao, I managed to figure out what's going on. On this particular system, ZFS sets the following settings by default:

```
# grep . /sys/module/zfs/parameters/{zfs_dirty_*,zfs_txg_timeout}
zfs_dirty_data_max:15195668
zfs_dirty_data_max_max:15195668
zfs_dirty_data_max_max_percent:25
zfs_dirty_data_max_percent:10
zfs_dirty_data_sync:67108864
zfs_txg_timeout:5
```

15 MB sounds familiar. It turns out that ZFS triggers a transaction to write out dirty data whenever the amount of dirty data goes above `zfs_dirty_data_sync`. But on this system, that never happens, because the max amount of dirty data is capped at 15 MB, which is less than `zfs_dirty_data_sync`'s hardcoded default of 64 MB. ZFS then sits around doing nothing until `zfs_txg_timeout` expires, at which point the data is finally written to disk and it starts accepting more. The end result is that 15 MB of data is written out every 5 seconds, giving the 3 MB/s that I get from `dd`.

(Side note: I'm not sure why ZFS thinks I have 150 MB of RAM. I am using a 32-bit kernel, but I have 2 GB of RAM and vmalloc=640M. I can reproduce these 3 MB/s writes on an x86_64 kernel though, so it's not x86-specific.)

`zfs_dirty_data_max` needs to be at _least_ `zfs_dirty_data_sync` to prevent ZFS from sitting around waiting for the transaction timeout. With the current default settings, any system with less than 640 MB of RAM is being artificially limited to 64 MB every 5 seconds = 13 MB/s, or less. But if I'm thinking about this right, we actually want it to be twice `zfs_dirty_data_sync`: when a transaction completes, ideally you want at least `zfs_dirty_data_sync` bytes worth of dirty data immediately available so you can start writing out the next transaction straight away.

I think the most sensible way of fixing this is probably to set `zfs_dirty_data_sync` to half of `zfs_dirty_data_max` (but no more than 64 MB), if the user hasn't explicitly set a different value.

(This might actually be an upstream bug, but I'm reporting it here because a) I know we've made some local changes to the zfs_dirty_data\* stuff, and b) I'm using ZoL, not upstream.)

**Comment by gmelikov** [comment]
Closing as stale. Feel free to reopen it if it's reproducible on latest master.
