### ISSUE TITLE
zpool create -o feature@[...]=disabled isn't accepted

### ISSUE THREAD

**Issue by gordan-bobic** [zfsonlinux/zfs#3460]
It looks like explicitly setting a feature flag to disabled at pool creation time isn't accepted. Instead the -d flag has to be used and the subset of features explicitly enabled.

This is rather unintuitive. Please consider supporting the syntax of explicitly setting feature flags to disabled at pool creation time.

**Comment by DeHackEd** [comment]
This is explicitly listed as not supported in the man page. A feature flag can only be set to 'enabled'.

Besides, many of them immediately go `active` when enabled and are stuck that way. Using `-d` is the only reliably method to prevent flags from being enabled at all.

**Comment by gordan-bobic** [comment]
Where is it explicitly stated as not supported in the man page? It doesn't appear to be under the zpool create option, under either the -o or -d sub-sections, and it isn't obvious in zpool-features man page either.

Why would it be a bad idea to enable specifying features to be disabled using the -o feature@ option explicitly during zpool create? It would be massively more intuitive.

**Comment by DeHackEd** [comment]
It might be more intuitive to allow setting disabled, but the documentation for the feature@blah properties clearly states:
<code>
  feature@feature_name=enabled
      The value of this property is the current state of feature_name. 
       The only valid value when setting this property is enabled which
       moves feature_name to the enabled state. See zpool-features(5)
       for details on feature states.
</code>

Similarly the `zpool create -d` description states you can enable features you want. Also you can enable them at runtime one-by-one using `zpool set`.

**Comment by gordan-bobic** [comment]
Sure - but none of this gives a strong reason why this _shouldn't_ be implemented as I described.

**Comment by behlendorf** [comment]
I don't think this is an unreasonable request.  This isn't supported currently but being able to specify the features with `zpool create -o feature@[...]=disabled` would be handy and intuitive.  Doing so is largely just a matter of argument processing `zpool_do_create()`.

**Comment by FransUrbo** [comment]
If I understand the code correctly, IF a <code>feature=disable</code> is used in the command line, we need to 'fake' a <code>-d</code>, enable all features EXCEPT the one we've asked to disable… ?

**Comment by gordan-bobic** [comment]
That is a good question. When some features are specified as enabled, and some disabled, and some not specified at all, what should the default for the ones that haven't been mentioned be? Defaulting them to disabled may be safer since enabling them later is easy and disabling them later is impossible.

**Comment by FransUrbo** [comment]
Let's say we use the following command line:

```
zpool create -o feature@lz4_compress=disable rpool sdc
```

For me, that would indicate, for me, that all features, EXCEPT <code>lz4_compress</code> should be enabled. So the default here should be <code>enable</code>. Otherwise, we would have used:

```
zpool create -d rpool sdc
```

With this command line:

```
zpool create -o feature@lz4_compress=disable -o feature@large_blocks=enable rpool sec
```

it gets a little more tricky. Code wise, I need to disable ALL but <code>large_blocks</code>. So in that case, the default would/should (?) be <code>disable</code>.

**Comment by FransUrbo** [comment]
As long as we document the reverse in defaults in both these cases, I think this will work. It would be reasonably easy to code this, without to much change to the code.

**Comment by gordan-bobic** [comment]
Right, so:
1) if _only_ disable flags are specified, default=enabled
2) if any enable flags are specified, default=disabled
?

**Comment by FransUrbo** [comment]
That sounds reasonable. Sounds a little counter intuitive (that the default changes), but that would be the easiest.

Would you be happy with that?

**Comment by gordan-bobic** [comment]
I think it would be more intuitive than the current approach (-d to disable everything, then explicitly enable the individual flags).
If somebody would care to point me at the correct file and function, I'm willing to have a go at implementing this change. Please be gentle, though, I'm pretty new to ZFS code. :-)

**Comment by FransUrbo** [comment]
I've already started. The first part is already done. I just need to figure out where/how exactly to do the second part.

I should hopefully have a PR within a few hours.

**Comment by behlendorf** [comment]
Let me propose an alternative, here's how I'd expect these options to work if implemented.

* The `-d` flags controls the __default__ value for all features.  When not set all features are enabled.  When set all features are disabled.  This is identical to the existing well understood behavior.

* The `-o feature@[...]=enabled|disabled` syntax can be used to override the default value whatever it may be.  In my opinion this removes any ambiguity about what a command will do.

Examples:

```
# Create a pool with ONLY large blocks
zpool create -d -o feature@large_blocks=enable tank vda

# Create a pool with everything EXCEPT bookmarks and hole_birth
zpool create -o feature@bookmarks=disabled -o feature@hole_birth=disabled tank vda
```

NOTE: Disabling a feature which is disabled by default, or enabled a feature which is enabled by default, is harmless and should be treated as such.

**Comment by FransUrbo** [comment]
Fixed cstyle errors and removed the debugging output.

**Comment by FransUrbo** [comment]
With this last push, these four tests succeeds:

```
# All features=disabled                                                                                                                                       
./cmd/zpool/zpool create -f -d rpool sdc

# All features=disabled, except large_blocks                                                                                                                  
./cmd/zpool/zpool create -f -d -o feature@large_blocks=enabled rpool sdc

# All features=disabled, except hole_birth (and enabled_txg which it depends on)        - ???                                                                 
./cmd/zpool/zpool create -f    -o feature@hole_birth=enabled -o feature@lz4_compress=disable rpool sdc

# All features=enabled, except hole_birth, async_destroy and lz4_compress                                                                                     
./cmd/zpool/zpool create -f    -o feature@hole_birth=disabled -o feature@async_destroy=disable -o feature@lz4_compress=disable rpool sec
```

**Comment by FransUrbo** [comment]
It's not the pretties code I've ever written, but it seems to do the job :)
