### ISSUE TITLE
grub "root=ZFS=..." misses zpool

### ISSUE THREAD

**Issue by heilts** [zfsonlinux/zfs#3462]
Hello,

I use Debian "Jessie" with zfs 0.6.4-1.1-2 and root on zfs. The root pool is "tank0".

After upgrading to grub 2.02-beta2.9-ZOL1, the grub.cfg misses the pool part, i.e. it becomes e.g.
linux   /jessie-1/ROOT@/boot/vmlinuz-3.19.8 root=ZFS=jessie-1/ROOT ro boot=zfs $bootfs  quiet
This does not work, it should be e.g.
linux   /jessie-1/ROOT@/boot/vmlinuz-3.19.8 root=ZFS=tank0/jessie-1/ROOT ro boot=zfs $bootfs  quiet

Also, at running "update-grub", I got

root@tor:~# update-grub
Generating grub configuration file ...
Found background image: /usr/share/images/desktop-base/desktop-grub.png
Found linux image: /boot/vmlinuz-3.19.8
Found initrd image: /boot/initrd.img-3.19.8
/usr/sbin/grub-probe: error: unknown filesystem.
Found linux image: /boot/vmlinuz-3.19.3
Found initrd image: /boot/initrd.img-3.19.3
Found linux image: /boot/vmlinuz-3.16.0-4-amd64
Found initrd image: /boot/initrd.img-3.16.0-4-amd64
/usr/sbin/grub-probe: error: unknown filesystem.
Found memtest86+ image: /jessie-1/ROOT@/boot/memtest86+.bin
Found memtest86+ multiboot image: /jessie-1/ROOT@/boot/memtest86+_multiboot.bin
Found Debian GNU/Linux (8.0) on /dev/sdi1
done

However, grub-probe works:
root@tor:~# grub-probe /
zfs

The root filesystem is placed on GPT parted disks (raidz1) partitition 4. The other partititions are used for gtp grub and md1 (carrying an ext4 based rescue system and swap, this is why the update-grub creates so many entries).

I do not know how to track the probelm further.

Best regards
Hinrich

**Comment by FransUrbo** [comment]
This belongs to the Grub repo (https://github.com/zfsonlinux/grub). Please move it there and close this one.

Could you please (in the new ticket) verify the version of the grub packages?

```
dpkg -l \*grub\* | grep ^ii
```

But the fact that you're getting

```
/usr/sbin/grub-probe: error: unknown filesystem.
```

indicates that one of the (many!) <code>grub-probe</code> commands is failing. Maybe because you have a mixed system?
