### ISSUE TITLE
zpool export fails after manual pool import or creation on ARM

### ISSUE THREAD

**Issue by gordan-bobic** [zfsonlinux/zfs#3466]
RedSleeve 7 (el7 armv5tel), ChromeOS 3.4.0 kernel rebuilt from source, ZoL 0.6.4.1:

host# zpool import usb
cannot import 'usb': more than one matching pool
host# zpool import
   pool: usb
     id: 4015255860133671413
  state: ONLINE
 status: The pool is formatted using a legacy on-disk version.
 action: The pool can be imported using its name or numeric identifier, though
    some features will not be available without an explicit 'zpool upgrade'.
 config:

```
usb                                                           ONLINE
  usb-Kingston_DataTraveler_2.0_1C6F654E3FD9FD80B90F2D23-0:0  ONLINE
```

   pool: usb
     id: 11506627151742964876
  state: FAULTED
 status: One or more devices contains corrupted data.
 action: The pool cannot be imported due to damaged devices or data.
   see: http://zfsonlinux.org/msg/ZFS-8000-5E
 config:

```
usb                                                           FAULTED  corrupted data
  usb-Kingston_DataTraveler_2.0_1C6F654E3FD9FD80B90F2D23-0:0  UNAVAIL  corrupted data
```

   pool: chrs
     id: 11931174478503449987
  state: UNAVAIL
 status: One or more devices contains corrupted data.
 action: The pool cannot be imported due to damaged devices or data.
   see: http://zfsonlinux.org/msg/ZFS-8000-5E
 config:

```
chrs                          UNAVAIL  insufficient replicas
  mmc-SD16G_0xd3919918-part2  UNAVAIL
```

host# zpool import 4015255860133671413
host# zpool export usb
cannot export 'usb': pool is busy
host# zpool export -f usb
cannot export 'usb': pool is busy
host# zfs list
NAME          USED  AVAIL  REFER  MOUNTPOINT
usb          8.05G  48.6G  32.5K  /usb
usb/scratch  8.05G  48.6G  8.05G  /usb/scratch
host# lsof | grep /usb
host# zpool destroy usb
cannot destroy 'usb': pool is busy

It scrubbed OK (8GB used on a ~60GB USB stick).
The only way to export he pool was to reboot the machine.
It was re-imported at startup, but export then worked. Nothing in syslog.

This appears to be repeatable (tried it all twice, rebooted each time).
It is worth stressing that this is on 32-bit ARM (armv5tel), not x86-64, just in case it is related.

Edit: Actually, this seems to have nothing to do with the remnants of the old pool. I blew away the last 1GB of the device and that got rid of the old pool's header. But the problem persists, the behaviour is exactly the same:

host# zpool list
NAME   SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
usb   57.5G  8.05G  49.5G         -      -    13%  1.00x  ONLINE  -
host# zpool export usb
host# zpool import usb
host# zpool list
NAME   SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
usb   57.5G  8.05G  49.5G         -      -    13%  1.00x  ONLINE  -
host# zpool export usb
cannot export 'usb': pool is busy

I cannot reproduce this on x86-64 with ZoL 0.6.4.1 using the same removable media, so it seems to be something specific to either ARM or an odd interaction with the kernel.

After the automatic import at boot time, the pool can be exported. Import it again manually, and it becomes unexportable.

What else can I check to gain more clues as to why the pool would be deemed busy?

**Comment by loli10K** [comment]
A lot of fixes has landed to improve ARM compatibility since 0.6.4, closing as stale.
