### ISSUE TITLE
zpool events poorly documented

### ISSUE THREAD

**Issue by osti** [zfsonlinux/zfs#3467]
Dear ZOL community,
we are experiencing some checksum errors on 84T zpool and are trying to debug the sources (lots of hardware and virtualisation layers in between, we're talking about virtual SAN and stuff).

By lucky fortune we found out about the "zpool events" command, which provides some insight into the checksum errors: at least, we get the good and bad checksums; but there are a lot of other fields written out, like the zio_objset and zio_object. Poorly documented, sadly.

Are there plans to improve the man page on this? Could we contribute to the man page, given some hints on source code regions where the meaning of these values can be deduced from?

Greetings,
mo

**Comment by behlendorf** [comment]
@osti I completely agree.  What we'd like to see happen if for each event to be clearly documented in a man page.  Under what situations can an event occur, what do the various fields mean, etc.  Sadly so far no one has time to work on this.

If you could contribute a man page that would be very helpful.  I think the place to start would be with the various events listed in `include/sys/fm/fs/zfs.h`  See the `FM_EREPORT_*` section for a list of events.  The ` FM_EREPORT_PAYLOAD_` section of this same file contains the valid fields an event might contain.  Many of these are fairly self explanatory but I'm happy to answer questions when things aren't clear.

**Comment by FransUrbo** [comment]
Commit a60e668b added initial support for a <code>zfs-events(5)</code> (<code>man/man5/zfs-events.5</code>) manpage.

We/someone just needs to fill in what they actually do and/or mean.

**Comment by FransUrbo** [comment]
I've just created PR #3480 which takes it a couple of more steps towards completion, but it's still not the whole way, but it's as far as I can take it with my limited understanding of the code.

**Comment by behlendorf** [comment]
@FransUrbo thanks!  I took your pull request and filled in the remaining gaps with at least a short description.  I also added tables for the valid zio_stages and zio_flags to make it possible to interpret the value without having the source checked out.

@osti commit d050c62 adds the basic information for all existing events and their payloads.  If you're going to be working in this area and doing a careful investigation of the events.  It would be great if you could enhance the existing documentation with what you learn.

**Comment by osti** [comment]
@behlendorf sorry for being so quiet, but I had a lot coming up last months.
