### ISSUE TITLE
openSUSE 13.2 - pools don't import on boot - systemd issue

### ISSUE THREAD

**Issue by seijirou302** [zfsonlinux/zfs#3473]
I'm not a developer but I'll try to do my best to explain the problem and how I fixed it.

ZFS was installed by adding the repo and installing through software.opensuse.org/package/zfs

I inserted drives that contained a pool and I was able to discover the pool with zpool import, and I was able to manually import the pool find with zpool import -d /dev/dsk/by-id/ 

Upon reboot though the pool needed to be manually imported again.  After a few days of google searching on and off I located and mostly understood the existance of /usr/lib/systemd/system/zfs* files

I was able to determine with systemctl status zfs-import-cache.service this command was failing with the error "modprobe: invalid option -- 'N'"

The command in zfs-import-cache.service is "ExecStart=/sbin/modprobe zfs && /sbin/zpool import -c /etc/zfs/zpool.cache -aN"

After some head scratching I figured that the && wasn't being interpreted correctly and modprobe thought the entire line was parameters.  To fix this I changed the line to " ExecStart =/bin/sh -c '/sbin/modprobe zfs && /sbin/zpool import -c /etc/zfs/zpool.cache -AN' " and this worked for me.

**Comment by behlendorf** [comment]
@seijirou302 nice diagnosis, your spot on.  This was a brief regression which was fixed in master with 544f7184f8541bbfd7c739f7e01fc9b5b6e57c5e, I'm a bit surprised it found it way so quickly in to the openSUSE packages.

**Comment by seijirou302** [comment]
@behlendorf Thanks for following up!  I refreshed the openSUSE repos and saw that the zfs package has an update now which implements that fix. :)
