### ISSUE TITLE
Transaction group always hangs with ZIL

### ISSUE THREAD

**Issue by YFLOPS** [zfsonlinux/zfs#3474]
I've set up a few servers with ZPOOL's attached to multiple arrays.  To improve random write throughput I added SSD's for the ZIL, and it usually hangs after I run a benchmark for quite a few minutes, even with just 30s of I/O.  zpool iostat, and iotop both show now data being moved about:

This happens on all three servers.

root      80948  0.9  0.0      0     0 ?        D<   Jun05   8:24 [txg_sync]
root      99266  2.9  0.0 263888 42116 ?        Ds   11:15   0:04 fio --filename=/dev/zvol/bigtank/volume --direct=1 --rw=randwrite --refill_buffers --ioengine=libaio --bs=4k --iodepth=16 --numjobs=16 --runtime=30 --group_reporting --name

3.10.0-123.el7.x86_64
zfs-0.6.4.1-1.el7.centos.x86_64

I've tried both the raw device, and a partition.

]# zpool status |sed 's/SSU/Enclosure/g'
  pool: bigtank
 state: ONLINE
  scan: none requested
config:

```
NAME                                   STATE     READ WRITE CKSUM
bigtank                                ONLINE       0     0     0
  raidz2-0                             ONLINE       0     0     0
    Enclosure1_56                            ONLINE       0     0     0
    Enclosure1_57                            ONLINE       0     0     0
    Enclosure1_58                            ONLINE       0     0     0
    Enclosure1_59                            ONLINE       0     0     0
    Enclosure1_60                            ONLINE       0     0     0
    Enclosure1_61                            ONLINE       0     0     0
    Enclosure1_62                            ONLINE       0     0     0
  raidz2-1                             ONLINE       0     0     0
    Enclosure1_63                            ONLINE       0     0     0
    Enclosure1_64                            ONLINE       0     0     0
    Enclosure1_65                            ONLINE       0     0     0
    Enclosure1_66                            ONLINE       0     0     0
    Enclosure1_67                            ONLINE       0     0     0
    Enclosure1_68                            ONLINE       0     0     0
    Enclosure1_69                            ONLINE       0     0     0
  raidz2-2                             ONLINE       0     0     0
    Enclosure1_70                            ONLINE       0     0     0
    Enclosure1_71                            ONLINE       0     0     0
    Enclosure1_72                            ONLINE       0     0     0
    Enclosure1_73                            ONLINE       0     0     0
    Enclosure1_74                            ONLINE       0     0     0
    Enclosure1_75                            ONLINE       0     0     0
    Enclosure1_76                            ONLINE       0     0     0
  raidz2-3                             ONLINE       0     0     0
    Enclosure1_77                            ONLINE       0     0     0
    Enclosure1_78                            ONLINE       0     0     0
    Enclosure1_79                            ONLINE       0     0     0
    Enclosure1_80                            ONLINE       0     0     0
    Enclosure1_81                            ONLINE       0     0     0
    Enclosure1_82                            ONLINE       0     0     0
    Enclosure1_83                            ONLINE       0     0     0
  raidz2-4                             ONLINE       0     0     0
    Enclosure2_56                            ONLINE       0     0     0
    Enclosure2_57                            ONLINE       0     0     0
    Enclosure2_58                            ONLINE       0     0     0
    Enclosure2_59                            ONLINE       0     0     0
    Enclosure2_60                            ONLINE       0     0     0
    Enclosure2_61                            ONLINE       0     0     0
    Enclosure2_62                            ONLINE       0     0     0
  raidz2-5                             ONLINE       0     0     0
    Enclosure2_63                            ONLINE       0     0     0
    Enclosure2_64                            ONLINE       0     0     0
    Enclosure2_65                            ONLINE       0     0     0
    Enclosure2_66                            ONLINE       0     0     0
    Enclosure2_67                            ONLINE       0     0     0
    Enclosure2_68                            ONLINE       0     0     0
    Enclosure2_69                            ONLINE       0     0     0
  raidz2-6                             ONLINE       0     0     0
    Enclosure2_70                            ONLINE       0     0     0
    Enclosure2_71                            ONLINE       0     0     0
    Enclosure2_72                            ONLINE       0     0     0
    Enclosure2_73                            ONLINE       0     0     0
    Enclosure2_74                            ONLINE       0     0     0
    Enclosure2_75                            ONLINE       0     0     0
    Enclosure2_76                            ONLINE       0     0     0
  raidz2-7                             ONLINE       0     0     0
    Enclosure2_77                            ONLINE       0     0     0
    Enclosure2_78                            ONLINE       0     0     0
    Enclosure2_79                            ONLINE       0     0     0
    Enclosure2_80                            ONLINE       0     0     0
    Enclosure2_81                            ONLINE       0     0     0
    Enclosure2_82                            ONLINE       0     0     0
    Enclosure2_83                            ONLINE       0     0     0
logs
  pci-0000:02:00.0-scsi-0:0:3:0-part1  ONLINE       0     0     0
```

errors: No known data errors

=== START OF INFORMATION SECTION ===
Vendor:               TOSHIBA
Product:              PX02SSF020
Revision:             A4AC
User Capacity:        200,049,647,616 bytes [200 GB]
Logical block size:   512 bytes
Physical block size:  4096 bytes
Lowest aligned LBA:   0
LU is resource provisioned, LBPRZ=1
Rotation Rate:        Solid State Device
Form Factor:          2.5 inches
Logical Unit id:      0x500003962c890220
Serial number:        REDACTED
Device type:          disk
Transport protocol:   SAS
Local Time is:        Sat Jun  6 11:26:29 2015 CDT
SMART support is:     Available - device has SMART capability.
SMART support is:     Enabled
Temperature Warning:  Disabled or Not Supported

=== START OF READ SMART DATA SECTION ===
SMART Health Status: OK

SS Media used endurance indicator: 0%
Current Drive Temperature:     24 C
Drive Trip Temperature:        60 C

Manufactured in week 11 of year 2015
Elements in grown defect list: 0

Error counter log:
           Errors Corrected by           Total   Correction     Gigabytes    Total
               ECC          rereads/    errors   algorithm      processed    uncorrected
           fast | delayed   rewrites  corrected  invocations   [10^9 bytes]  errors
read:          0        0         0         0          0          0.016           0
write:         0        0         0         0          0         24.865           0

Non-medium error count:        9

NAME     PROPERTY                    VALUE                       SOURCE
bigtank  size                        202T                        -
bigtank  capacity                    0%                          -
bigtank  altroot                     -                           default
bigtank  health                      ONLINE                      -
bigtank  guid                        4932989410862557659         default
bigtank  version                     -                           default
bigtank  bootfs                      -                           default
bigtank  delegation                  on                          default
bigtank  autoreplace                 off                         default
bigtank  cachefile                   -                           default
bigtank  failmode                    wait                        default
bigtank  listsnapshots               off                         default
bigtank  autoexpand                  off                         default
bigtank  dedupditto                  0                           default
bigtank  dedupratio                  1.00x                       -
bigtank  free                        201T                        -
bigtank  allocated                   863G                        -
bigtank  readonly                    off                         -
bigtank  ashift                      12                          local
bigtank  comment                     -                           default
bigtank  expandsize                  -                           -
bigtank  freeing                     0                           default
bigtank  fragmentation               0%                          -
bigtank  leaked                      0                           default
bigtank  feature@async_destroy       enabled                     local
bigtank  feature@empty_bpobj         active                      local
bigtank  feature@lz4_compress        active                      local
bigtank  feature@spacemap_histogram  active                      local
bigtank  feature@enabled_txg         active                      local
bigtank  feature@hole_birth          active                      local
bigtank  feature@extensible_dataset  enabled                     local
bigtank  feature@embedded_data       active                      local
bigtank  feature@bookmarks           enabled                     local

**Comment by gmelikov** [comment]
Close as stale.

If it's actual - feel free to reopen.
