### ISSUE TITLE
Looking for help with permanent error <0xffffffffffffffff>:<0x0>

### ISSUE THREAD

**Issue by janlam7** [zfsonlinux/zfs#3476]
Hi,

on one of my machines zpool status -v gives the following message since today after a scrub:

errors: Permanent errors have been detected in the following files:
        <0xffffffffffffffff>:<0x0>

Shortly before I rolled back a snapshot, maybe that has something to do with it.

Running zdb -mc pool3 ends with:

Traversing all blocks to verify metadata checksums and verify nothing leaked ...

loading space map for vdev 0 of 1, metaslab 119 of 174 ...zdb: ../../module/zfs/range_tree.c:262: Assertion `rs->rs_end >= end (0xef7e0a4000 >= 0xef7e0b2000)' failed.
Aborted

The number of checksum errors is also increasing steadily.
Other than that, everything seems to be working.

What to do ?

**Comment by behlendorf** [comment]
It sounds like like of the drives is starting to fail.  If you pool has redundancy I'd replace it.

**Comment by janlam7** [comment]
Ok, if the error still occurs, I'll restore from a backup.
