### ISSUE TITLE
zfs receive of a replicated snapshot that includes a clone results in no error, but exit code 1

### ISSUE THREAD

**Issue by Pentium100MHz** [zfsonlinux/zfs#3479]
Hi, I have noticed a weird problem with zfs. I think this is a bug, therefore I am filing it here, and not in the mailing list.

Replicating the bug is a bit tricky, but it happened naturally on my backup server. ZFS version 0.6.4.1-1, OS: the host is Debian 8, backup can be Debian 8 or CentOS 6.6, the same happens. 

You need two servers with zfs to replicate this - a host and a backup server (there is no bug if all this is done on a single server).

On the host:

```
zfs create home/test
zfs create home/test/d0
zfs destroy home/test/d0
zfs create -V 10G home/test/d0
zfs snapshot home/test/d0@snap
zfs create home/test2
zfs clone home/test/d0@snap home/test2/d0
zfs create -V 1G home/test2/d1
```

The sizes are not important, I am using zvols, and do not know if the same happens with non-zvol datasets, anyway, here's what we have now:

```
home/test
home/test/d0
home/test2
home/test2/d0    <---- clone of home/test/d0@snap
home/test2/d1
```

Now I try to back home/test2 up. On the backup server:

```
zfs create nfs/bkp
rsh host-ip "/sbin/zfs send -v home/test2@snap1" | zfs recv -duv nfs/bkp
rsh host-ip "/sbin/zfs send -v home/test2/d0@snap1" | zfs recv -duv nfs/bkp
rsh host-ip "/sbin/zfs send -v home/test2/d1@snap1" | zfs recv -duv nfs/bkp
```

So far so good, full backup done. Now let's try to do an incremental one:
On the host:

```
zfs snapshot -r home/test2@snap2
```

On the backup server (this is where the bug appears):

```
~#rsh host-ip "/sbin/zfs send -v -R -i home/test2@snap1 home/test2@snap2" | zfs recv -duv nfs/bkp
send from @snap1 to home/test2@snap2 estimated size is 0
send from @snap1 to home/test2/d0@snap2 estimated size is 0
send from @snap1 to home/test2/d1@snap2 estimated size is 0
total estimated size is 0
TIME        SENT   SNAPSHOT
receiving incremental stream of home/test2@snap2 into nfs/bkp/test2@snap2
TIME        SENT   SNAPSHOT
TIME        SENT   SNAPSHOT
received 312B stream in 1 seconds (312B/sec)
receiving incremental stream of home/test2/d0@snap2 into nfs/bkp/test2/test2/d0@snap2
received 312B stream in 1 seconds (312B/sec)
receiving incremental stream of home/test2/d1@snap2 into nfs/bkp/test2/test2/d1@snap2
received 312B stream in 1 seconds (312B/sec)
~# echo $?
1
```

So, no error is reported, but exit code is 1 (which of course causes my backup script to report an error). The data seems to be copied (checked with a non-empty dataset).

**Comment by irnes** [comment]
I have encountered the same issue. Is this going to be fixed?

**Comment by valeech** [comment]
Same issue here as well. 

```
zfs create home/test
zfs create -V 10G home/test/d0
zfs snapshot home/test/d0@snap
zfs clone home/test/d0@snap home/test/d1
zfs snapshot home/test/d1@snap2
zfs clone home/test/d1@snap2 home/test/d2
zfs snapshot home/test/d2@snap3
zfs clone home/test/d2@snap3 home/test/d3

zfs snapshot -r home@initialsnap
zfs send -R home@initialsnap | zfs recv -Fu other/home

zfs snapshot home/test/d3@snap4
zfs clone home/test/d3@snap4 home/test/d4
zfs snapshot home/test/d4@snap5
zfs clone home/test/d4@snap5 home/test/d5
zfs snapshot home/test/d5@snap6
zfs clone home/test/d5@snap6 home/test/d6

zfs snapshot -r home@nextsnap
zfs send -RI home@initialsnap home@nextsnap | zfs recv -Fu other/home

zfs destroy -r home@initialsnap
zfs rename -r home@nextsnap home@initialsnap
zfs destroy -r other/home@initialsnap
zfs rename -r other/home@nextsnap otherhome@initialsnap

zfs rename home/test/d0@snap home@test/d0@snap_rename
zfs promote home/test/d1@snap
zfs destroy -r home/test/d0
zfs destroy home/test/d1@snap_rename
zfs rename home/test/d1@snap home@test/d1@snap_rename
zfs promote home/test/d2@snap
zfs destroy -r home/test/d1
zfs destroy home/test/d2@snap_rename
zfs rename home/test/d2@snap home@test/d2@snap_rename
zfs promote home/test/d3@snap
zfs destroy -r home/test/d2
zfs destroy home/test/d3@snap_rename

zfs snapshot home/test/d6@snap7
zfs clone home/test/d6@snap7 home/test/d7
zfs snapshot home/test/d7@snap8
zfs clone home/test/d7@snap8 home/test/d8
zfs snapshot home/test/d8@snap9
zfs clone home/test/d8@snap9 home/test/d9

zfs snapshot -r home@nextsnap
zfs send -RI home@initialsnap home@nextsnap | zfs recv -Fu other/home
```

I am essentially chaining clones off of each other and replicating them remotely. Then I promote some of the earlier clones to delete the even earlier origins. Once those origins are missing, zfs recv still sees them on the receiving side and tries to promote them but fails for some reason. 

If you do a `recv -F` it actually tries to remove the datasets on the remote side because they do not exist on the source side. This fails as well because the recv does not know how to handle clones and actually errors out and fails.

Without `recv -F` the recv can't promote but keeps going. The receive is successful in the sense that all of the data is transmitted and accessible on the remote side, but the command actually exits with exit code 1. This will jack up a script that is looking for actual errors on zfs recv.
