### ISSUE TITLE
Missing Fedora 22 repository

### ISSUE THREAD

**Issue by danielkza** [zfsonlinux/zfs#3485]
Fedora 22 has been officially out for about two weeks. It would be nice to have packages for it in the official repository.

I've been running with the F21 packages since the release and haven't had any problems. If there are no issues pertaining to the change to kernel 4.0, it should be a matter of just rebuilding the packages and setting up the new version.

It seems there are other people interested, like seen in issue #3456.

I can help with some testing if necessary.

**Comment by maci0** [comment]
+1

**Comment by behlendorf** [comment]
Thanks for the reminder, I'll see if I can't get them created tomorrow.

**Comment by maci0** [comment]
Keep in mind that F22 might upgrade to kernel 4.1 during its lifecycle.
I have seen some issues about incompatibility with 4.1 and ZoL 0.6.4.1.
I guess a 0.6.4.2 should be released with the linux 4.1 relevant patches backported.

**Comment by danielkza** [comment]
Kernels usually enter Fedora about a month after mainline release. That means there's probably between one and one-and-a-half months from now until 4.1 reaches F22. Is 0.6.5 unlikely to have been released at that point, integrating the patches? Or maybe a 0.6.4-3 release would be in order so all distros can pick up kernel 4.1 later?

**Comment by maci0** [comment]
Yeah, I have had issues with that in the past. When Fedora would update the kernel but the ZoL release in the distro was not compatible.
I think i'm not the only one who was having this problem...
That's why we should make sure the latest stable ZoL release in repositories is compatible with the latest mainline kernel.

**Comment by twagler** [comment]
+1

**Comment by behlendorf** [comment]
It might take a little longer to get an automated daily Fedora 22 repository going.  There appears to be an issue with signing rpms with a key that uses a pass phase.  A [fix](https://github.com/rpm-software-management/rpm/commit/0bce5fcf270711a2e077fba0fb7c5979ea007eb5) has been merged but an updated version of rpm hasn't been tagged yet so the fix isn't in Fedora 22.  

https://bugzilla.redhat.com/show_bug.cgi?id=1228234

**Comment by behlendorf** [comment]
Official release and testing repositories are now available for Fedora 22.  They've passed my basic functional testing and appear to work as expected with the new `dnf` package managed.  As always please report any problems!

**Comment by danielkza** [comment]
I hit the DKMS issue today. I created an issue, hopefully with a good amount of information (#3538).

**Comment by fardok** [comment]
pls   - how to install  ZFS on fedora22?  yum dont work,   dnf cant install

**Comment by behlendorf** [comment]
Supported packages are only provided for x86_64, custom packages can be built for other Fedora architectures as described here.

http://zfsonlinux.org/generic-rpm.html

**Comment by fardok** [comment]
One year later...  - is it possible to install zfs on Fedora with fucking dnf?

**Comment by behlendorf** [comment]
Yes, for x86_64 only.
