### ISSUE TITLE
zfs build against 4.1 kernel fails to build with DKMS

### ISSUE THREAD

**Issue by ColinIanKing** [zfsonlinux/zfs#3486]
Using DKMS and the ubuntu  https://launchpad.net/~zfs-native/+archive/ubuntu/stable PPA, with a 4.1-rc7 kernel I'm getting build failures due to changes in struct kiocb etc.. 

the DKMS build log reports:

  CC [M]  /var/lib/dkms/zfs/0.6.4.1/build/module/zfs/../../module/zfs/zpl_export.o
  CC [M]  /var/lib/dkms/zfs/0.6.4.1/build/module/zfs/../../module/zfs/zpl_file.o
/var/lib/dkms/zfs/0.6.4.1/build/module/zfs/../../module/zfs/zpl_file.c: In function ‘zpl_aio_fsync’:
/var/lib/dkms/zfs/0.6.4.1/build/module/zfs/../../module/zfs/zpl_file.c:200:27: error: ‘struct kiocb’ has no member named ‘ki_nbytes’
      kiocb->ki_pos + kiocb->ki_nbytes, datasync));
                           ^
/var/lib/dkms/zfs/0.6.4.1/build/module/zfs/../../module/zfs/zpl_file.c: In function ‘zpl_aio_read’:
/var/lib/dkms/zfs/0.6.4.1/build/module/zfs/../../module/zfs/zpl_file.c:269:22: error: ‘struct kiocb’ has no member named ‘ki_nbytes’
  size_t count = kiocb->ki_nbytes;
                      ^
/var/lib/dkms/zfs/0.6.4.1/build/module/zfs/../../module/zfs/zpl_file.c: In function ‘zpl_aio_write’:
/var/lib/dkms/zfs/0.6.4.1/build/module/zfs/../../module/zfs/zpl_file.c:352:22: error: ‘struct kiocb’ has no member named ‘ki_nbytes’
  size_t count = kiocb->ki_nbytes;
                      ^
/var/lib/dkms/zfs/0.6.4.1/build/module/zfs/../../module/zfs/zpl_file.c: At top level:
/var/lib/dkms/zfs/0.6.4.1/build/module/zfs/../../module/zfs/zpl_file.c:781:2: error: unknown field ‘aio_read’ specified in initializer
  .aio_read = zpl_aio_read,
  ^
/var/lib/dkms/zfs/0.6.4.1/build/module/zfs/../../module/zfs/zpl_file.c:781:2: warning: initialization from incompatible pointer type
/var/lib/dkms/zfs/0.6.4.1/build/module/zfs/../../module/zfs/zpl_file.c:781:2: warning: (near initialization for ‘zpl_file_operations.read_iter’)
/var/lib/dkms/zfs/0.6.4.1/build/module/zfs/../../module/zfs/zpl_file.c:782:2: error: unknown field ‘aio_write’ specified in initializer
  .aio_write = zpl_aio_write,
  ^
/var/lib/dkms/zfs/0.6.4.1/build/module/zfs/../../module/zfs/zpl_file.c:782:2: warning: initialization from incompatible pointer type
/var/lib/dkms/zfs/0.6.4.1/build/module/zfs/../../module/zfs/zpl_file.c:782:2: warning: (near initialization for ‘zpl_file_operations.write_iter’)
/var/lib/dkms/zfs/0.6.4.1/build/module/zfs/../../module/zfs/zpl_file.c: In function ‘zpl_aio_fsync’:
/var/lib/dkms/zfs/0.6.4.1/build/module/zfs/../../module/zfs/zpl_file.c:201:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
scripts/Makefile.build:258: recipe for target '/var/lib/dkms/zfs/0.6.4.1/build/module/zfs/../../module/zfs/zpl_file.o' failed
make[5]: **\* [/var/lib/dkms/zfs/0.6.4.1/build/module/zfs/../../module/zfs/zpl_file.o] Error 1
scripts/Makefile.build:403: recipe for target '/var/lib/dkms/zfs/0.6.4.1/build/module/zfs' failed
make[4]: **\* [/var/lib/dkms/zfs/0.6.4.1/build/module/zfs] Error 2
Makefile:1383: recipe for target '_module_/var/lib/dkms/zfs/0.6.4.1/build/module' failed
make[3]: **\* [_module_/var/lib/dkms/zfs/0.6.4.1/build/module] Error 2
make[3]: Leaving directory '/usr/src/linux-headers-4.1.0-rc7+'
Makefile:16: recipe for target 'modules' failed
make[2]: **\* [modules] Error 2
make[2]: Leaving directory '/var/lib/dkms/zfs/0.6.4.1/build/module'
Makefile:675: recipe for target 'all-recursive' failed
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory '/var/lib/dkms/zfs/0.6.4.1/build'
Makefile:545: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by kernelOfTruth** [comment]
https://github.com/zfsonlinux/zfs/pull/3421

needs to be merged soon-ish then

4.1-rc7* is working fine here with that patch

**Comment by behlendorf** [comment]
Yes, yes it does.  That one slipped off by radar let me see if we can't get that merged right away.

**Comment by DorianGray** [comment]
Any ETA on when the PPA will get a new release? I run a zfs root and am really looking forward to some features in kernel 4.1.

**Comment by behlendorf** [comment]
Expect a 0.6.4.2 tag this week with Linux 4.1 support.  After the tag it will take a little while to roll out to the distributions.

**Comment by gmelikov** [comment]
Close as stale.
