### ISSUE TITLE
May distributed parallel reading feature be enabled in ZFS?

### ISSUE THREAD

**Issue by windmoonfox** [zfsonlinux/zfs#3493]
When I imported a pool still active in another server in readonly mode, I found it appears a snapshot, kept unchanged by ignoring any update from the original host. I know ZFS is not a distributed file system, but I think this feature may help much in an enterprise enviroment. May ZFS on linux team consider to add this feature to next version?

**Comment by behlendorf** [comment]
@windmoonfox there shouldn't be anything preventing you from doing this today if you force import the pool read-only and then only access things like snapshots.
