### ISSUE TITLE
[RFC] High memory fragmentation after long usage, failing high order memory allocations ?

### ISSUE THREAD

**Issue by kernelOfTruth** [zfsonlinux/zfs#3494]
I've seen a continuously declining possibility of high order allocations in 

/proc/buddyinfo

which indicates a high memory fragmentation

I'm not entirely sure whether this is at part due to how ZFS uses memory.

As a potential mitigation in the long term there could be the possibility to add compaction functionality to SPL - similar as used in zram and a GPU driver used by Gioh Kim of LG

http://marc.info/?l=linux-virtualization&m=143323004318542&w=2
[RFC 0/4] enable migration of non-LRU pages

**Comment by behlendorf** [comment]
@kernelOfTruth with the current master code this is to be expected.  However, the ABD patches should significantly reduce/resolve this issue.  By change have you observed a pool with this patches applied?

**Comment by kernelOfTruth** [comment]
@behlendorf you mean the ABD patches ?

Yes, up to just recently I've almost exclusively used a branch with ABD patches and if I remember correctly - I've also observed this behavior with those

with the current zfs master it appears to be more extreme

Thus I'm looking forward (and waiting) for a refreshed ABD stack to merged or available - so I can test it

Thanks

**Comment by kernelOfTruth** [comment]
I'm not entirely sure yet if the observation is correct but

running with THP off

```
transparent_hugepage=never
```

memory compaction appears to have a higher success rate (less stalls, less fails)


Less fragmentation ?

Will have to take a deeper look into this issue ...

**Comment by behlendorf** [comment]
@kernelOfTruth can you please close this issue if the recently merged ABD patches resolved this problem.

**Comment by gmelikov** [comment]
Close as stale.

If it's actual - feel free to reopen.
