### ISSUE TITLE
Multiple snapshots across various pools

### ISSUE THREAD

**Issue by zielony360** [zfsonlinux/zfs#3504]
Hello,

I need to create many snapshots on different pools atomically, because the snapshots from both pools have to be from the same time (reason: I am merging zvols from different pools with mdadm - I know what I am doing).

When I try to take snapshots:

zfs snapshot pool1/zvol1@snap1 pool2/zvol1@snap1
cannot create snapshots : multiple snapshots of same fs not allowed
no snapshots were created

However filesystems are other.

I use 0.6.3 during this try.

Is there some way to freeze IOs (especially writes) to pools/zvols for a short time to take all snapshots?

**Comment by behlendorf** [comment]
@zielony360 you can take snapshots atomically across multiple filesystem if they are within the _same_ pool but not if they're in _different_ pools.  This isn't something ZFS can support internally because each pool is running it's own independent transaction object store.  You'll need to somehow control this from your application.

**Comment by zielony360** [comment]
@behlendorf Thank you for your answer.

So nowadays the only way to take snapshots across few pools from the same time is setting blkio throttle (hopefully nobody use 1 B block :D):
```
echo "MAJ:MIN  1" > /sys/fs/cgroup/blkio/blkio.throttle.write_bps_device
echo "MAJ:MIN  1" > /sys/fs/cgroup/blkio/blkio.throttle.write_iops_device
zfs snapshot pool1/zvol1@snap1 &
zfs snapshot pool2/zvol1@snap1 &
wait
echo "MAJ:MIN  0" > /sys/fs/cgroup/blkio/blkio.throttle.write_bps_device
echo "MAJ:MIN  0" > /sys/fs/cgroup/blkio/blkio.throttle.write_iops_device
```
However it can be used only with zvols. Maybe someone has a better idea?

**Comment by fling-** [comment]
@zielony360 try using zfs-auto-snapshot

**Comment by behlendorf** [comment]
Closing.  Coordinating snapshots across multiple pools needs to be handled outside ZFS.

**Comment by dechamps** [comment]
While it makes sense that one can't snapshot atomically across multiple pools, the error message is still very confusing. Filed #16457 about that.
