### ISSUE TITLE
Init Script: zfs_action log output is not useful

### ISSUE THREAD

**Issue by MrStaticVoid** [zfsonlinux/zfs#3514]
In `zfs-functions`, in `zfs_action()`, the error code is logged like:

```sh
        $CMD
        ret=$?
        if [ "$ret" -eq 0 ]; then
                zfs_log_end_msg $ret
        else
                zfs_log_failure_msg $ret
        fi
```

The return status for $CMD is passed to functions like:

```sh
        zfs_log_end_msg() { eend "$1"; }
        zfs_log_failure_msg() { eerror "$1"; }
```

which, in the case of a failure, simply outputs a number to the boot messages, like:

```
 * Mounting ZFS filesystem(s)  ...
cannot mount '/var': directory is not empty
 * 1       <--- this is not helpful
 * Mounting volumes and filesystems registered in fstab ...
 [ ok ]
```

**Comment by FransUrbo** [comment]
I misunderstood the usage of <code>eerror()</code> (which requires a error info message, which we don't have). We should use <code>eend()</code> for <code>zfs_log_failure_msg()</code> as well.

I have a fix, I figure I just try to fix your other issue while I'm at it. Expect a new push for #3510 "shortly" that fixes this and hopefully your other one as well.
