### ISSUE TITLE
How do I reduce memory consumption?

### ISSUE THREAD

**Issue by pneumatic** [zfsonlinux/zfs#3530]
Is it possible to reduce ARC memory consumption in-flight?  How do I determine which version that I have installed?  I have a zfsonlinux server that is starting to become very unreliable and the logs look like it is a memory issue (only 200 megabytes of 24GB free).  Google indicates that a lot of people have this problem but nobody seems to have found a solution for fixing the issue in-production.

**Comment by FransUrbo** [comment]
This is more of a support question than a bug/issue with the software. Please close this and take it to the mailing list.

**Comment by kernelOfTruth** [comment]
@pneumatic some keywords to look into

NUMA, zfs_arc_max, zfs_arc_min, zfs_arc_meta_limit, zfs_arc_meta_strategy (https://github.com/zfsonlinux/zfs/issues/3303#issuecomment-111755146), zfs_arc_overflow_shift (https://github.com/zfsonlinux/zfs/issues/3303#issuecomment-111772489), zfs_arc_meta_adjust_restarts

spl_kmem_cache_kmem_limit, spl_kmem_cache_slab_limit, spl_kmem_cache_expire, spl_kmem_cache_reclaim

ARC in relation to RAM size (close to or less than half)


Some of those settings require to run ZFS from at least June 17th 2015 (or latest zfs master + spl master)

Hope that helps
