### ISSUE TITLE
"zpool status" can't display real-time status

### ISSUE THREAD

**Issue by yuzx** [zfsonlinux/zfs#3539]
I create a pool with 5 disks and then pull off a disk."zpool status" display all online. Only when I do "zpool scrub", the disk display unavail. why zfs filesystem can't  real-time monitor？ what can I do?
Thank you very much！！！

**Comment by DeHackEd** [comment]
This is an issue tracker, not a support forum.

ZFS doesn't know a disk is failed until it gets some feedback from the OS, such as after attempting IO on a dead disk.

**Comment by yuzx** [comment]
ok,thank you!

**Comment by behlendorf** [comment]
Kernel side callbacks or a udev rule would allow us to be notified of physical device removal but it hasn't been a priority.  One I/O is issued the issue will be detected.  If someone wan't to investigate this I think it would be a nice improvement.
