### ISSUE TITLE
ZFS 1MB Block Size

### ISSUE THREAD

**Issue by behlendorf** [zfsonlinux/zfs#354]
This is a patch we are going to need to recreate to reduce the ZFS overhead and improve throughput.

--- From Andreas ---
At one time we were working with a ZFS patch that implemented a max 1MB blocksize, and this improved normal IO performance under certain workloads.  In particular, it reduced lock contention and indirect block allocation in the indirect block tree, which allowed a single server to have a much higher peak throughput.

The way the patch was implemented was to allow RAID-Z(2) blocks to be up to 1MB in size, but the individual blocks on each VDEV were still limited to 128kB.  That also avoided the overhead of fragmenting and repacking large writes into multiple small buffers for the VDEVs with standard 8+2 RAID-Z2 configurations.  The default maximum blocksize was left at 128kB, and a pool property had to be set to use the 1MB blocksize, to maintain compatibility with standard ZFS.

Unfortunately, that patch was never released by Oracle.  I never saw the code, so I don't know the underlying details of how it was implemented, but I don't think it was overly complex to implement.  There definitely IS a single constant which controls the maximum blocksize. but the patch was definitely more than just changing that one constant.

**Comment by behlendorf** [comment]
Finally merged!

f1512ee Illumos 5027 - zfs large block support

**Comment by sentania** [comment]
I recently patched to a level that included this fix.  I did *not* upgrade my pool, but was able to successfull create a zvol with a 1MB block size, which immediately triggered the following panic:

[ 2739.227921] VERIFY3(size <= spa_maxblocksize(spa)) failed (1048576 <= 131072)
[ 2739.228023] PANIC at arc.c:1547:arc_buf_alloc()
[ 2739.228073] Showing stack for process 3480
[ 2739.228078] CPU: 10 PID: 3480 Comm: zvol Tainted: P           O   3.18.16-gentoo #1
[ 2739.228080] Hardware name: Supermicro H8DM8-2/H8DM8-2, BIOS 080014  10/22/2009
[ 2739.228082]  000000000000060b ffff8807f42079e8 ffffffff814a2b18 00000000000000fb
[ 2739.228091]  ffffffffa1fcaf05 ffff8807f42079f8 ffffffffa063eeb4 ffff8807f4207b78
[ 2739.228094]  ffffffffa063ef5d ffff8807f4207a78 ffffffff00000030 ffff8807f4207b88
[ 2739.228097] Call Trace:
[ 2739.228108]  [<ffffffff814a2b18>] dump_stack+0x46/0x58
[ 2739.228118]  [<ffffffffa063eeb4>] spl_dumpstack+0x3d/0x3f [spl]
[ 2739.228124]  [<ffffffffa063ef5d>] spl_panic+0xa7/0xda [spl]
[ 2739.228129]  [<ffffffffa063c873>] ? spl_kmem_cache_alloc+0x649/0x668 [spl]
[ 2739.228135]  [<ffffffff814a6083>] ? mutex_unlock+0x9/0xb
[ 2739.228158]  [<ffffffffa1f2accf>] ? dbuf_rele_and_unlock+0x2bf/0x3bb [zfs]
[ 2739.228161]  [<ffffffff814a6083>] ? mutex_unlock+0x9/0xb
[ 2739.228173]  [<ffffffffa1f2c636>] ? dbuf_rm_spill+0x749/0x786 [zfs]
[ 2739.228185]  [<ffffffffa1f25769>] arc_buf_alloc+0x53/0x165 [zfs]
[ 2739.228198]  [<ffffffffa1f2b558>] dbuf_read+0x2cf/0x71a [zfs]
[ 2739.228214]  [<ffffffffa1f32f68>] dmu_buf_rele_array+0x242/0x415 [zfs]
[ 2739.228229]  [<ffffffffa1f33204>] dmu_buf_hold_array_by_bonus+0xc9/0xe8 [zfs]
[ 2739.228244]  [<ffffffffa1f341ae>] dmu_read_req+0x49/0xe9 [zfs]
[ 2739.228258]  [<ffffffffa1fbb15a>] zrl_is_locked+0x1267/0x1593 [zfs]
[ 2739.228266]  [<ffffffffa063ddac>] taskq_create+0x4e3/0x648 [spl]
[ 2739.228272]  [<ffffffff8104c746>] ? wake_up_process+0x34/0x34
[ 2739.228277]  [<ffffffffa063db3f>] ? taskq_create+0x276/0x648 [spl]
[ 2739.228282]  [<ffffffff810462b6>] kthread+0xcd/0xd5
[ 2739.228285]  [<ffffffff810461e9>] ? kthread_create_on_node+0x16c/0x16c
[ 2739.228289]  [<ffffffff814a7b08>] ret_from_fork+0x58/0x90
[ 2739.228292]  [<ffffffff810461e9>] ? kthread_create_on_node+0x16c/0x16c


I would imagine that if the pool isn't upgraded we don't want to allow the creation of larger than 128k blocksize.

**Comment by behlendorf** [comment]
@sentania we definitely don't.  I've filed this crash as #3591 so we can track it.  Is it possible you were running with a new version of the ZFS utilities and an old version of the kernel modules when this happened?
