### ISSUE TITLE
Strange ARC usage

### ISSUE THREAD

**Issue by roedie** [zfsonlinux/zfs#3556]
I've noticed my ARC size often exceeds the maximum size. When I reboot the ARC stays within normal bounds for about 2 weeks, and after that it starts allocating more than the max.

Also, at the same moment this starts, disk utilisation and disk IO-wait go up.

This happens with zfs 0.6.4.1, all data is server over NFS.

![zfs_stats_utilization-pinpoint 1434787274 1435912099](https://cloud.githubusercontent.com/assets/1014038/8495134/5d19221c-216b-11e5-9658-2f9d61909cf7.png)

**Comment by behlendorf** [comment]
@roedie the recently released 0.6.4.2 tag has some patches which should help with this.  Specifically one of the following depending on your kernel version.

* Improve metadata shrinker performance on pre-3.1 kernels zfsonlinux/zfs#3501, and
* Linux 3.12 compat: NUMA-aware per-superblock shrinker

https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.6.4.2

**Comment by roedie** [comment]
@behlendorf  Thanks for your answer. But now I'm a bit stuck between a rock and a hard place. Unless #3445 is also fixed by 0.6.4.2. Last time I upgraded to 0.6.4.1 or 544f71 I got system hangs within a couple of days.

**Comment by gmelikov** [comment]
Close as stale.

If it's actual - feel free to reopen.
