### ISSUE TITLE
dataset reorganisation on root pool caused boot process to hang (deadlock?)

### ISSUE THREAD

**Issue by RJVB** [zfsonlinux/zfs#3558]
Hi,

I just got myself out of an annoying issue, rather trivial in itself but not at all so to diagnose or in its effects.

I have an Ubuntu 14.04 system that I transferred to ZFS, using an ext3 boot partition; spl/zfs 0.6.4.1, zfs-initramfs 0.6.3-0.27~21b446~wheezy and grub 2.02-beta2.9-ZOL11-7aa9f6-wheezy .
I have a number of datasets configured in my root pool (called Patux), among which

Patux/devel/MacPorts (mounts on /opt/local ; Patux/devel's mountpoint is set to none)
Patux/ProjectNeon5 (mounts on /opt/project-neon5)

I decided to reorganise this, putting everything under /opt in Patux/opt but keeping MacPorts and Neon5 in their own dataset.

I did

> zfs rename -p Patux/ProjectNeon5 Patux/opt/ProjectNeon5

to take care of the Neon5 dataset and create Patux/opt in one step. I did not modify the MacPorts dataset, as it was already set to mount on /opt/local .

The next reboot hung, systematically on some step after launching the NSM status monitor, suggesting an internet related problem. Since I rebooted because the WiFi adapter didn't wake correctly from hibernation AND I'd installed several things (including a new kernel) AND I'd already seen this kind of hang when I still  used Ubuntu's own grub (or the zfs-grub for Ubuntu) I went on a a wild hunt that was unsuccessful and very annoying until I finally extracted the disk to hook it up to a faster machine and I finally managed to obtain an error message that led to the solution.

I have an /etc/fstab file that works on several rigs, and thus has swap device entries for each, only one of which is available during a given boot of course. There will be a warning for the 1st missing entry (with shortcuts to ignore or resolve manually) which I'd never acted on because it was never necessary before. Now, I used the "Skip" (ignore) shortcut, and finally got an error about Patux/devel/MacPorts not being available (yet), which I could _not_ skip.

So I rebooted once more from a different pool (with the Patux pool completely disconnected to avoid auto-mounting issues). In that context, the Patux pool imported just fine, with all dataset mounting as they should. I then renamed Patux/devel/MacPorts to Patux/opt/MacPorts (without changing its mountpoint), and that solved the boot issue.

Is this a known issue (or even a sanctioned behaviour) with ZFS, or rather grub or zfs-initramfs, caused by the attempt to mount a dataset on a directory that's in another dataset that comes later in the `zfs list` list? Even if so, why is there no error printed (systematically), and why is it impossible to skip this particular mount?

**Comment by gmelikov** [comment]
Close as stale.

If it's actual - feel free to reopen.
