### ISSUE TITLE
Error while upgrading debian testing "Unknown Debian GNU/Linux version!"

### ISSUE THREAD

**Issue by mroark1m** [zfsonlinux/zfs#3579]
I ran apt-get upgrade today on my debian testing system with zfs already installed, and I got this:

...
Setting up zfsonlinux (6) ...
Unknown Debian GNU/Linux version!
Can not create /etc/apt/sources.list.d/zfsonlinux.list.
See /usr/share/doc/zfsonlinux/zfsonlinux.list.
dpkg: error processing package zfsonlinux (--configure):
 subprocess installed post-installation script returned error exit status 1
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@huey:~# 

Is there any way I can rescue this installation?

**Comment by mroark1m** [comment]
Well I removed that package since it seemed like it only created apt related files and as far as I could tell everything else was succesful. But after a reboot I have 

root@huey:~# zpool list
no pools available

So I guess there was some other issue with the upgrade.

**Comment by mroark1m** [comment]
zpool import tank
zpool import tank2

has made the two pools available again. But now the disk ids are different. Before I was using /dev/disk/by-id names and now they are /dev/sdx names. I'd like to figure out how to get back to the /dev/disk/by-id names since I believe the /dev/sdx names can change.

**Comment by mroark1m** [comment]
I exported tank2 and then tried to import again using a copy of the old zpool.cache file:

root@huey:~# zpool import -c /tmp/zpool.cache 
   pool: tank2
     id: 10673489856820876384
  state: UNAVAIL
 status: One or more devices contains corrupted data.
 action: The pool cannot be imported due to damaged devices or data.
   see: http://zfsonlinux.org/msg/ZFS-8000-5E
 config:

	tank2                             UNAVAIL  insufficient replicas
	  mirror-0                        UNAVAIL  insufficient replicas
	    wwn-0x50014ee2b6508a37-part1  UNAVAIL
	    wwn-0x50014ee20b481221-part1  UNAVAIL

It looks like something else changed in the upgrade, because these partition names are no longer correct. Changing it to point to the /dev/disk/by-id/ directory, it uses the ata names instead:

root@huey:~# zpool import -d /dev/disk/by-id/
   pool: tank2
     id: 10673489856820876384
  state: ONLINE
 status: Some supported features are not enabled on the pool.
 action: The pool can be imported using its name or numeric identifier, though
	some features will not be available without an explicit 'zpool upgrade'.
 config:

	tank2                                               ONLINE
	  mirror-0                                          ONLINE
	    ata-WDC_WD40EFRX-68WT0N0_WD-WCC4E7KFC02Y-part1  ONLINE
	    ata-WDC_WD40EFRX-68WT0N0_WD-WCC4E3CP922J-part1  ONLINE

I guess I will be satisfied with that for now.

**Comment by FransUrbo** [comment]
This really belong to the https://github.com/zfsonlinux/pkg-zfs repository, so could you please close this one and open it in the pkg-zfs repo instead?

As to installing the Wheezy or Jessie packages on testing, you're more or less on your own. it's not supported, and probably never will. Testing is way to … "fluent" for that.

As for the import, that is expected behavior - if you use <code>zpool import</code> it WILL use <code>/dev</code> as source for the devices. Have a look at <code>/etc/default/zfs</code>, the <code>USE_DISK_BY_ID</code> option.

**Comment by mroark1m** [comment]
I'll check out the USE_DISK_BY_ID option. Thanks. Sorry for posting in wrong repository.
