### ISSUE TITLE
Errors and warnings when updating ZFS on CentOS 7

### ISSUE THREAD

**Issue by Zhro** [zfsonlinux/zfs#3580]
After performing a yum update which included kernel updates, ZFS was unable to load after a reboot. Failure to reinstall it seemed to stem modules building from the wrong kernel source.

I performed a `rpm -qa | grep kernel` and removed old kernel-devel and kernel-headers, then ran the following:

`yum remove libzfs2 dkms zfs-dkms zfs zfs-release spl spl-dkms`
`yum localinstall --nogpgcheck http://archive.zfsonlinux.org/epel/zfs-release.el7.noarch.rpm`
`yum install libzfs2 dkms zfs-dkms zfs zfs-release spl spl-dkms -y | tee zfs-log`

ZFS is now working again but the log reported many warnings and errors:

http://pastebin.com/raw.php?i=GL64JP7x

Should I be worried about this?

**Comment by behlendorf** [comment]
They warning indicate a problem creating the symlinks for weak modules.  This means if you boot to a different kernel you won't be able to load the ZFS modules without rebuilding them for it.  Beyond that they're not a reason for concern.
