### ISSUE TITLE
lib/libspl/zone.c error: ISO C90 forbids mixed declarations and code

### ISSUE THREAD

**Issue by kernelOfTruth** [zfsonlinux/zfs#3588]
Just got this upon attempting to compile ZFS

seems like the aggressive error flags work after all :+1: 

```
../../lib/libspl/zone.c: In function ‘getzonenamebyid’:
../../lib/libspl/zone.c:54:2: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
  ssize_t ret = strlen(GLOBAL_ZONEID_NAME) + 1;
  ^
cc1: all warnings being treated as errors
```

**Comment by kernelOfTruth** [comment]
There are several more in different files  - not sure if it can be even viewed as "error" ...

**Comment by kernelOfTruth** [comment]
https://github.com/kernelOfTruth/zfs/commit/7c9bfaf5f80ec598595d21d75d699a58e04f6d15

```
addressing
error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]

(incomplete)
```

**Comment by behlendorf** [comment]
@kernelOfTruth this is a little odd because we do build all of the user space utilities as libraries as C99 so this shouldn't be a warning.  Also why did you end up closing this issue?

**Comment by kernelOfTruth** [comment]
@behlendorf I thought of it as a false positive due to having messed things up with the toolchain (e.g. KDE and QT on my system turned out to do things in a very weird way in combination with GCC 5.1)

So I quickly closed it (it was pretty late back then - several hours after midnight if I remember correctly) and put the blame on the above mentioned issue and wanted to avoid confusion.

In the end it still could be something to look into

thus re-opening

**Comment by rlaager** [comment]
If we're building as C99, why is this a problem that needs fixing?

If this is not a problem, then I'd like to close this issue. If it is agreed that this is a problem, I can take a look at this. @kernelOfTruth has a start, and it really should be trivial to fix these.

**Comment by kernelOfTruth** [comment]
@rlaager feel free taking a look at it I'm currently occupied otherwise

I usually enable the following flags when porting patches or doing experiments on the code:

```
-Wformat-extra-args -Wall -Werror -Werror=format= -Werror=maybe-uninitialized -Wpedantic -Werror=pedantic -Werror=declaration-after-statement
```

I'm mostly using gcc 4.9.4 hardened right now since a few things do not build with gcc 5.3 or 6.2 yet (also I didn't have time to test out e.g. a full system rebuild with gcc 6.2)

Thanks

**Comment by behlendorf** [comment]
We should just close this.  But for the record in user space we can build C99 without issue.  However, any code which needs to run in kernel space must be C90.  We've explored relaxing this but overriding the kernel build system is problematic and brittle so it's best that we update the code as needed.
