### ISSUE TITLE
Linux 4.2 compatibility

### ISSUE THREAD

**Issue by behlendorf** [zfsonlinux/zfs#3596]
The ZoL code must be updated to compile against Linux 4.2 kernel.  Several minor issues prevent building, patches to follow shortly.

**Comment by colorprint** [comment]
It is not fixed completly yet?

**Comment by behlendorf** [comment]
@colorprint the patches in #3597 are complete, just not yet merged.  That should happen soon since they changes required we're complicated.

**Comment by kernelOfTruth** [comment]
Be careful when using 4.2 kernels there currently seems to be memory corruption last time I skimmed through the mailing list
