### ISSUE TITLE
ZFS pool not importable on zol 0.6.4 on alpine linux 3.2.2

### ISSUE THREAD

**Issue by tzelch** [zfsonlinux/zfs#3603]
Hi,

I have a strange issue with ZOL on Alpine Linux.
I can create a pool and use it without problems, but as soon as i reboot, or if i export the pool, i'm not able to import it anymore.
The zdb -l command won't be able to unpack the labels, but fdisk will see that the Device has a zfs_member signature

backup:~# uname -a
Linux backup 3.18.18-2-grsec #3-Alpine SMP Tue Jul 14 09:13:42 GMT 2015 x86_64 Linux
backup:~# cat /etc/alpine-release 
3.2.2

backup:~# apk info zfs-grsec
zfs-grsec-3.18.18-r2 description:
ZFS for Linux

zfs-grsec-3.18.18-r2 webpage:
http://zfsonlinux.org

zfs-grsec-3.18.18-r2 installed size:
2502656

backup:~# apk info zfs-utils
zfs-utils-3.18.18-r2 description:
Userland tools to manage zfs on linux

zfs-utils-3.18.18-r2 webpage:
http://zfsonlinux.org

zfs-utils-3.18.18-r2 installed size:
3334144

backup:~# zpool create test /dev/xvdc
backup:~# zfs create test/bla
backup:~# zpool list
NAME   SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
test  9.94G   708K  9.94G         -     0%     0%  1.00x  ONLINE  -
backup:~# zpool export test
backup:~# zpool import test
cannot import 'test': no such pool available
backup:~# zpool import -F -n
no pools available to import
## LABEL 3

failed to unpack label 3
backup:~# fdisk /dev/xvdc

Welcome to fdisk (util-linux 2.26.2).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.

/dev/xvdc: device contains a valid 'zfs_member' signature; it is strongly recommended to wipe the device with wipefs(8) if this is unexpected, in order to avoid possible collisions

Device does not contain a recognized partition table.
Created a new DOS disklabel with disk identifier 0x0c384414.

Command (m for help):

**Comment by stroobandt** [comment]
**Similar issue with zfsonlinux 0.6.5.4-1~trusty amd64 on Xubuntu LTS 14.04**

A detailed account can be read over at [Server Fault](http://serverfault.com/q/762308/175321).

**Comment by rodolfo-vargas** [comment]
On Alpine 3.3.1 using zfs-grsec-4.1.19-r0 the issue remains.

I tried to mount it using 
`$ zfs mount -a`
but no luck...


One clue. There is not /dev/disk/by-id/ directory. 

This is the content of `/etc/conf.d/zfs` 
```
# ZoL userland configuration.

# Run `zfs mount -a` during system start?
ZFS_MOUNT='yes'

# Run `zfs unmount -a` during system stop?
ZFS_UNMOUNT='yes'

# Run `zfs share -a` during system start?
# nb: The shareiscsi, sharenfs, and sharesmb dataset properties.
ZFS_SHARE='yes'

# Run `zfs unshare -a` during system stop?
ZFS_UNSHARE='yes'

# Specify specific path(s) to look for device nodes and/or links for the
# pool import(s). See zpool(8) for more information about this variable.
# It supersedes the old USE_DISK_BY_ID which indicated that it would only
# try '/dev/disk/by-id'.
# The old variable will still work in the code, but is deprecated.
#ZPOOL_IMPORT_PATH="/dev/disk/by-vdev:/dev/disk/by-id"

# Should the datasets be mounted verbosely?
# A mount counter will be used when mounting if set to 'yes'.
VERBOSE_MOUNT='no'

# Should we allow overlay mounts?
# This is standard in Linux, but not ZFS which comes from Solaris where this
# is not allowed).
DO_OVERLAY_MOUNTS='no'

# Any additional option to the 'zfs mount' command line?
# Include '-o' for each option wanted.
MOUNT_EXTRA_OPTIONS=""

# Build kernel modules with the --enable-debug switch?
# Only applicable for Debian GNU/Linux {dkms,initramfs}.
ZFS_DKMS_ENABLE_DEBUG='no'

# Build kernel modules with the --enable-debug-dmu-tx switch?
# Only applicable for Debian GNU/Linux {dkms,initramfs}.
ZFS_DKMS_ENABLE_DEBUG_DMU_TX='no'

# Keep debugging symbols in kernel modules?
# Only applicable for Debian GNU/Linux {dkms,initramfs}.
ZFS_DKMS_DISABLE_STRIP='no'

# Wait for this many seconds in the ignited pre_mountroot
# This delays startup and should be '0' on most systems.
# Only applicable for Debian GNU/Linux {dkms,initramfs}.
ZFS_INITRD_PRE_MOUNTROOT_SLEEP='0'

# Wait for this many seconds in the ignited mount root
# This delays startup and should be '0' on most systems. This might help on
# systems which have their ZFS root on a USB disk that takes just a little
# longer to be available
# Only applicable for Debian GNU/Linux {dkms,initramfs}.
ZFS_INITRD_POST_MODPROBE_SLEEP='0'

# List of additional datasets to mount after the root dataset is mounted?
#
# The init script will use the mountpoint specified in the 'mount point'
# property value in the dataset to determine where it should be mounted.
#
# This is a space separated list, and will be mounted in the order specified,
# so if one filesystem depends on a previous mountpoint, make sure to put
# them in the right order.
#
# It is not necessary to add filesystems below the root fs here. It is
# taken care of by the initrd script automatically. These are only for
# additional filesystems needed. Such as /opt, /usr/local which is not
# located under the root fs.
# Example: If root FS is 'rpool/ROOT/rootfs', this would make sense.
#ZFS_INITRD_ADDITIONAL_DATASETS="rpool/ROOT/usr rpool/ROOT/var"

# List of pools that should NOT be imported at boot?
# This is a space separated list.
#ZFS_POOL_EXCEPTIONS="test2"

# Optional arguments for the ZFS Event Daemon (ZED).
# See zed(8) for more information on available options.
#ZED_ARGS="-M"
```??

**Comment by Corey-J-Bukolt** [comment]
Also having the same issue on Alpine.  I can create a zpool but as soon as I export it and try to import it it can't be found.

**Comment by gmelikov** [comment]
Close as stale.

If it's actual - feel free to reopen.
