### ISSUE TITLE
Crash with 4.2 kernel

### ISSUE THREAD

**Issue by colorprint** [zfsonlinux/zfs#3606]
Compiles fine but crashes on boot with 4.2 kernel:
https://www.dropbox.com/s/k2iuf5uj44m8ujs/2015-07-17%2021.51.38.jpg?dl=0
With 4.1.2 kernel works fine.
Compiled from git master.

**Comment by behlendorf** [comment]
Thanks, I didn't see this in my testing (nor did the buildbot) but it's possible there's another more subtle API change which still needs to be addressed.

**Comment by tuxoko** [comment]
RDI is an odd number, also according to https://www.kernel.org/doc/Documentation/x86/x86_64/mm.txt,
it's in kernel text area. I wonder how it ended up like that...

**Comment by colorprint** [comment]
no any progress yet?

**Comment by tuxoko** [comment]
@colorprint Does this still occur with newer kernel rc?
Also the link you posted doesn't work anymore.

**Comment by colorprint** [comment]
Fixed the link in the first message.
Will check with 4.2rc4 kernel today

**Comment by colorprint** [comment]
Tested with 4.2-rc4 kernel - same problem.
zfs and spl compiled from git master.

**Comment by tuxoko** [comment]
@colorprint 
Did you recompile spl/zfs against the new kernel?
Are you using spl/zfs in initrd? If so, is the newly compiled spl/zfs in it?
Also please provide your kernel config.
Thanks.

**Comment by colorprint** [comment]
Yes, recompiled of course.
Kernel compiled from https://aur.archlinux.org/packages/linux-mainline/ (Arch linux), just changed the kernel realese in PKGBUIL to 4.2-rc4
Here is the config file shared: https://dl.dropboxusercontent.com/u/4080500/2015/config.x86_64

**Comment by tuxoko** [comment]
@colorprint 
I haven't found out anything suspicious yet.
Could you try bisecting it?

**Comment by colorprint** [comment]
I have finally get it working on 4.2-rc2
