### ISSUE TITLE
Datasets with mountpoint=none with children with mountpoint set up mounts anyway, 0.6.4-21-53b1d9-wheezy

### ISSUE THREAD

**Issue by Amitie10g** [zfsonlinux/zfs#3619]
I've done a fresh Debian stretch install (due to weired problems), and when the pool is imported and datasets are mounted, datasets with mountpoint=none with children datasets with mountpoint set up, the parent dataset is mounted **anyway** (instead of mounting just its childs), regardless the folder is non-empty and Overlay mounts are disabled. In particular, this make `/usr` completelly hidden, and then, the system hangs forever (or at least several hours) when trying to load services.

I'm testing with a rescue system with zfs `0.6.3-26` in chrooted env (my in-disk system has `0.6.4-21-53b1d9-wheezy`). This problem did not ocurred with previous versions of zfs related packages.

In the rescue system:

<pre>root@davod-notebook:/# zfs list -r davod.org/ROOT/debian-3
NAME                                  USED  AVAIL  REFER  MOUNTPOINT
davod.org/ROOT/debian-3               737M  67.5G   575M  /mnt
davod.org/ROOT/debian-3/opt            96K  67.5G    96K  /mnt/opt
davod.org/ROOT/debian-3/usr           162M  67.5G    96K  none
davod.org/ROOT/debian-3/usr/games     160K  67.5G    96K  /mnt/usr/games
davod.org/ROOT/debian-3/usr/share     133M  67.5G   133M  /mnt/usr/share
davod.org/ROOT/debian-3/usr/src      28.6M  67.5G  28.6M  /mnt/usr/src
davod.org/ROOT/debian-3/var           272K  67.5G   108K  none
davod.org/ROOT/debian-3/var/backups    96K  67.5G    96K  /mnt/var/backups</pre>

<pre>root@davod-notebook:/# mount | grep debian-3
davod.org/ROOT/debian-3 on / type zfs (rw,noatime,xattr,noacl)
davod.org/ROOT/debian-3/opt on /opt type zfs (rw,noatime,xattr,noacl)
davod.org/TMP/debian-3/tmp on /tmp type zfs (rw,noatime,xattr,noacl)
davod.org/ROOT/debian-3/usr/games on /usr/games type zfs (rw,noatime,xattr,noacl)
davod.org/ROOT/debian-3/usr/share on /usr/share type zfs (rw,noatime,xattr,noacl)
davod.org/ROOT/debian-3/usr/src on /usr/src type zfs (rw,noatime,xattr,noacl)
davod.org/ROOT/debian-3/var/backups on /var/backups type zfs (rw,noatime,xattr,noacl)
davod.org/LOG/debian-3/var/log on /var/log type zfs (rw,noatime,xattr,noacl)
davod.org/TMP/debian-3/var/tmp on /var/tmp type zfs (rw,noatime,xattr,noacl)</pre>

But in the real system (for `davod.org/ROOT/debian-3/usr` and also `davod.org/ROOT/debian-3/var`):

<pre>zfs list -r davod.org/ROOT/debian-3/usr
NAME                                  USED  AVAIL  REFER  MOUNTPOINT
davod.org/ROOT/debian-3/usr           162M  67.5G    96K  /usr
davod.org/ROOT/debian-3/usr/games     160K  67.5G    96K  /mnt/usr/games
davod.org/ROOT/debian-3/usr/share     133M  67.5G   133M  /mnt/usr/share</pre>

<pre>root@davod-notebook:/# mount | grep debian-3/usr
davod.org/ROOT/debian-3/usr on /usr type zfs (rw,noatime,xattr,noacl)
davod.org/ROOT/debian-3/usr/share on /usr/share type zfs (rw,noatime,xattr,noacl)
davod.org/ROOT/debian-3/usr/src on /usr/src type zfs (rw,noatime,xattr,noacl)
davod.org/ROOT/debian-3/usr/games on /usr/games type zfs (rw,noatime,xattr,noacl)</pre>

I'll tried a workarround, reanimng `davod.org/ROOT/debian-3/usr`'s childs to somewhat like `davod.org/ROOT/debian-3/usr-games`, leaving those datasets away from its parent dataset, and then, destroy `davod.org/ROOT/debian-3/usr`, and the system boots successfully. But the idea is use the parent and its childs, consideraing, again, that I didn't have problems before updating to `0.6.4-21-53b1d9-wheezy`

**Comment by FransUrbo** [comment]
> davod.org/ROOT/debian-3/usr           162M  67.5G    96K  /usr
Shouldn't that be "none"? As it is now, it's no wonder why it's mounted. It's expected behavior�

**Comment by fling-** [comment]
'none' is inherited too.
Try using `zfs inherit mountpoint` on a dataset.

**Comment by ryao** [comment]
This is a regression in 0.6.4.2 that i noticed with `zpool create -m none ...`.

**Comment by ryao** [comment]
This might be related to a regression in 0.6.4 that can be reproduced with `zpool create -m none ...`. The `-m none` is ignored.

**Comment by Amitie10g** [comment]
<blockquote>davod.org/ROOT/debian-3/usr           162M  67.5G    96K  /usr
<blockquote>Shouldn't that be "none"? As it is now, it's no wonder why it's mounted. It's expected behavior</blockquote></blockquote>

Yep, *should* be ``none``, but as I mentioned, that are the mount points of these datasets after booting, regardless its configuration, and therefore it should be not an expected behaviour.

Also, I created the zpool without `-m none` several months ago.

Anyway, I renamed the child datasets and problem resolved, but I still need to keep these datasets inside its parent one. If the porblem is fixed in next Debian packages update, please tell me to test.

**Comment by FransUrbo** [comment]
> davod.org/ROOT/debian-3/usr 162M 67.5G 96K /usr
> Shouldn't that be "none"? As it is now, it's no wonder why it's mounted. It's expected behavior
> Yep, should be none, but as I mentioned, that are the mount points of these datasets after booting, regardless its configuration, and therefore it should be not an expected behaviour.
> 
If you have set the mount point to "/usr" for this dataset, then it will be mounted on "/usr". Period.

Have you tried to run

	zpool set mountpoint=none davod.org/ROOT/debian-3/usr
> If the porblem is fixed in next Debian packages update, please tell me to test.
> 
There is nothing to fix. This is how it's supposed to work, and always have...

**Comment by behlendorf** [comment]
I'm not able to reproduce the issue described here with zfs-0.6.4-200-gc6a3a22.  Creating a pool with the __-m__ option properly sets __mountpoint=none__, this value is inherited by child datasets, and filesystem set as __none__ are not mounted.  Potentially there might be an issue if `/sbin/mount.zfs` isn't installed.

```
$zpool create -m none tank mirror vdb vdc
$ zfs create tank/fish
$ zfs create tank/fish/a
$ zfs create tank/fish/b
$ zfs set mountpoint=/tank/fish/a tank/fish/a

$ zfs get mountpoint 
NAME         PROPERTY    VALUE         SOURCE
tank         mountpoint  none          local
tank/fish    mountpoint  none          inherited from tank
tank/fish/a  mountpoint  /tank/fish/a  local
tank/fish/b  mountpoint  none          inherited from tank

$ zpool export tank
$ zpool import tank
$ df
Filesystem           1K-blocks     Used Available Use% Mounted on
/dev/mapper/VolGroup-lv_root
                      64597756 26405616  34904304  44% /
tmpfs                  4029428        0   4029428   0% /dev/shm
/dev/vda1               487652   166405    295647  37% /boot
tank/fish/a           32251648        0  32251648   0% /tank/fish/a
```

**Comment by gmelikov** [comment]
Close as stale.

If it's actual - feel free to reopen.
