### ISSUE TITLE
Enhancement: /dev/zfs permissions

### ISSUE THREAD

**Issue by malachid** [zfsonlinux/zfs#362]
The PPA installation created a /dev/zfs special file with root:root 600 permissions.  Changing this (chmod/chgrp) doesn't work so well since it gets recreated on boot.  Unfortunately, that makes it difficult to use things like zpool status and zfs list as anyone but root.

Perhaps a better solution would be to create a zfs group and specify 660 permissions.  That would allow the machine administration to easily specify who is allowed to use the zfs toolset.  Alternatively, the group name could be specified in the /etc/default/zfs configuration file.

**Comment by rtvd** [comment]
Is there a need for a special ZFS group and 660 permissions at all? Why not just set the permissions to 666, just like it is done in FreeBSD?

**Comment by behlendorf** [comment]
@rtvd that requires some additional infrastructure for Linux.  That work is underway in #4487 and I plan to post and updated version of that patch this week for review.
