### ISSUE TITLE
Centos 7 zfs-dkms yum install failure

### ISSUE THREAD

**Issue by tommybutler** [zfsonlinux/zfs#3623]
yum install spl # worked fine, but...
yum install zfs zfs-dkms
Running transaction
  Installing : zfs-dkms-0.6.4.2-1.el7.centos.noarch  
Loading new zfs-0.6.4.2 DKMS files...
Building for 3.10.0-229.7.2.el7.x86_64
Building initial module for 3.10.0-229.7.2.el7.x86_64
configure: error: 
    **\* Please make sure the kmod spl devel <kernel> package for your
    **\* distribution is installed then try again.  If that fails you
    **\* can specify the location of the spl objects with the
    **\* '--with-spl-obj=PATH' option.
Error! Bad return status for module build on kernel: 3.10.0-229.7.2.el7.x86_64 (x86_64)
Consult /var/lib/dkms/zfs/0.6.4.2/build/make.log for more information.
warning: %post(zfs-dkms-0.6.4.2-1.el7.centos.noarch) scriptlet failed, exit status 10
Non-fatal POSTIN scriptlet failure in rpm package zfs-dkms-0.6.4.2-1.el7.centos.noarch

cat /var/lib/dkms/zfs/0.6.4.2/build/make.log
DKMS make.log for zfs-0.6.4.2 for kernel 3.10.0-229.7.2.el7.x86_64 (x86_64)
Thu Jul 23 23:00:21 EDT 2015
make: **\* No targets specified and no makefile found.  Stop.

**Comment by behlendorf** [comment]
It looks like you may not have installed `spl-dkms`, make sure that's installed before `zfs-dkms`.

**Comment by gmelikov** [comment]
Close as stale.

If it's actual - feel free to reopen.
