### ISSUE TITLE
Custom SMTP server for zed.d

### ISSUE THREAD

**Issue by liquidox** [zfsonlinux/zfs#3631]
I believe zed.d does not support configuring a custom SMTP server, localhost only.

I would like to see this added in the future.

**Comment by dun** [comment]
Pull request #3648 would allow for an SMTP relay (or anything else) to be specified via the `ZED_EMAIL_OPTS` variable.  For example, the following line in `zed.rc` could be used with Heirloom mailx:
```
ZED_EMAIL_OPTS="-s '@SUBJECT@' -S smtp=my_smtp_relay_host @ADDRESS@"
```
