### ISSUE TITLE
single iostat command always returns same old values

### ISSUE THREAD

**Issue by kaazoo** [zfsonlinux/zfs#3633]
No matter how often I run the following iostat command, it always returns the same values:
```
$ zpool iostat backup
               capacity     operations    bandwidth
pool        alloc   free   read  write   read  write
----------  -----  -----  -----  -----  -----  -----
backup      34.1T  1.11T      0     18    510   266K
# zpool iostat backup
               capacity     operations    bandwidth
pool        alloc   free   read  write   read  write
----------  -----  -----  -----  -----  -----  -----
backup      34.1T  1.11T      0     18    510   266K
# zpool iostat backup
               capacity     operations    bandwidth
pool        alloc   free   read  write   read  write
----------  -----  -----  -----  -----  -----  -----
backup      34.1T  1.11T      0     18    510   266K
...
```

But when I run iostat with 3 iterations I get the real values:
```
$ zpool iostat backup 1 3
               capacity     operations    bandwidth
pool        alloc   free   read  write   read  write
----------  -----  -----  -----  -----  -----  -----
backup      34.1T  1.11T      0     18    510   266K
backup      34.1T  1.11T      0      0      0      0
backup      34.1T  1.11T      0      0      0      0
```

So iostat seems to take the first line from cached values.

As a workaround, I use 2 iterations and only take the second line of output:
```
$ zpool iostat backup 1 2 | tail -n 1
```

**Comment by kernelOfTruth** [comment]
how about

```
zpool iostat 1
```

that refreshes every second and each time has different values

**Comment by richardelling** [comment]
> On Jul 26, 2015, at 9:38 AM, kaazoo <notifications@github.com> wrote:
> 
> No matter how often I run the following iostat command, it always returns the same values:
> 
> $ zpool iostat backup
>                capacity     operations    bandwidth
> pool        alloc   free   read  write   read  write
> ----------  -----  -----  -----  -----  -----  -----
> backup      34.1T  1.11T      0     18    510   266K
> # zpool iostat backup
>                capacity     operations    bandwidth
> pool        alloc   free   read  write   read  write
> ----------  -----  -----  -----  -----  -----  -----
> backup      34.1T  1.11T      0     18    510   266K
> # zpool iostat backup
>                capacity     operations    bandwidth
> pool        alloc   free   read  write   read  write
> ----------  -----  -----  -----  -----  -----  -----
> backup      34.1T  1.11T      0     18    510   266K
> ...
> But when I run iostat with 3 iterations I get the real values:
> 
> $ zpool iostat backup 1 3
>                capacity     operations    bandwidth
> pool        alloc   free   read  write   read  write
> ----------  -----  -----  -----  -----  -----  -----
> backup      34.1T  1.11T      0     18    510   266K
> backup      34.1T  1.11T      0      0      0      0
> backup      34.1T  1.11T      0      0      0      0
> So iostat seems to take the first line from cached values.
> 
> 

Not cached values, but the delta-T is boot time. So you're seeing the report
of performance since boot.
 -- richard

**Comment by kaazoo** [comment]
@kernelOfTruth 
I use the output for performance monitoring by a NRPE check script. That's why I would like to just get the current values.

**Comment by DeHackEd** [comment]
You might be interested in #3439 (which got merged last month) which just omits the first line of output, essentially giving you what you want.

Personally I suggest a bigger number for your interval so you get a broader picture than a 1-second average.

**Comment by behlendorf** [comment]
As @DeHackEd mentioned in the next tag (or master) you'll be able to pass the `-y` option to iostat to get the behavior you want.  The default behavior remains unchanged.

**Comment by kaazoo** [comment]
OK, thanks :)
