### ISSUE TITLE
Failed to load ZFS module stack

### ISSUE THREAD

**Issue by srinivasa-r** [zfsonlinux/zfs#3635]
Dear Concerned, 

We have installed Scientific Linux release 6.1 (Carbon) recently for one of our project in our institute. We are trying to install the ZFS as per the standard instructions (using yum) and ZFS is installed without any problem, but when we are trying to use "zpool status", it showing the following error and we are unable to use the ZFS.

"Failed to load ZFS module stack.
Load the module manually by running 'insmod <location>/zfs.ko' as root."

I would really appreciate if you could help us to fix this issue.

Thanks in advance.

Cheers,
--

Srinivas R

**Comment by kernelOfTruth** [comment]
@srinivasa-r I bet if you asked on the IRC channel and posted some more in-depth information you'd have the solution in no time ;)

**Comment by behlendorf** [comment]
`modprobe zfs` will load the zfs modules, they should also be loaded automated by the init scripts.

**Comment by srinivasa-r** [comment]
Dear Behlendorf,

I have tried that command, but it is giving the following error:

modprobe zfs
FATAL: Module zfs not found.
You have new mail in /var/spool/mail/root

**Comment by behlendorf** [comment]
@srinivasa-r then the module weren't build for your running kernel.  Make sure your system is up to date and running the latest installed kernel.

**Comment by srinivasa-r** [comment]
Hi,

We are using Scientific Linux release 6.1, because our project works only on this. The kernal that we are using is "2.6.32-131.0.15.el6.x86_64". I would really appreciate if you could help us in fixing this issue.

**Comment by behlendorf** [comment]
@srinivasa-r if your running SL you should be able to pull the ZFS packages right from their addon repository.  I'd suggest doing the following.

* Make sure your system is up to date and reboot to make sure your running the latest kernel.
* Remove all existing spl, spl-dkms, zfs, and zfs-dkms packages.
* Install the kernel-devel packages.
* Install the ZFS packages from the addons repository:
  http://ftp.scientificlinux.org/linux/scientific/6rolling/x86_64/addons/zfs/
* Test ZFS with a `zpool status`.

If it still doesn't work make sure the zfs.ko modules was built and added to `/lib/module/<kernel>`.  If it was and just can't be loaded check `dmesg` for error messages.

**Comment by srinivasa-r** [comment]
Thank you very much. I was able to install the ZFS successfully.....:-)  Great help....

Thank you once again......!!!!!!!!!!!!!!!!
