### ISSUE TITLE
Proxying http://archive.zfsonlinux.org/ via Artifactory

### ISSUE THREAD

**Issue by NetAppBlueDevil** [zfsonlinux/zfs#3646]
I didn't see any other place to report an issue with the download site, hoping this is OK.

I'm trying to use Artifactory to proxy a number of internet APT repositories for my environment.  Although I can apt-get when configured directly to the zfs site, I get 404 errors when trying to use Artifactory as a proxy.

It seems that files that I can curl directly (like Release.gpg) are getting 404 when requested by artifactory.  Also, I get an XML key not found type error if I try to hit directly on the browser.

Is there something special required to be able to do this?  I'm trying to use artifactory to speed up my dependency accesses and reduce hits to the external sites.

**Comment by behlendorf** [comment]
Closing.  This sounds like an issue with Artifactory.  The packages are hosted at download.zfsonlinux.org which is an S3 bucket.  Also the official Debian packages are now hosted by Debian.
