### ISSUE TITLE
Freeze with latest git (night of July 30)

### ISSUE THREAD

**Issue by angstymeat** [zfsonlinux/zfs#3654]
I've had this freeze happen twice today. This time I was able to get some debugging info:
https://cloud.passcal.nmt.edu/index.php/s/OhwpdORdqsNcgw3

I'm not seeing anything strange happening, the system is running as usual, and then all ZFS access hangs like something is being blocked or deadlocked. The first time it happened, the system was running normally. The second time I had started an rsync backup (it's the client, sending files to the off-site server). That ran for about 20 minutes before the system froze.

In its "frozen" state, I can log into it, logging continues to work, etc., but any access to a zfs fs (ls, df, etc) causes the session to hang indefinitely.

I'm running the git head from July 30 with #3344 & #3643 installed.

The system is a VMWare virtual machine running Fedora 22 with the 4.0.8 kernel. It is running 6 virtual processors with 24GB of RAM.

The load is very write-heavy, with continuous writes to many files, sometimes consisting of only a few bytes each.

I have 3 other machines that are running this same code with the same patches listed above, and they are not exhibiting this behavior. Two of them do not have this level of load, and the off-site backup does heavy rsync operations once a day that last for about 2 hours.

Edit: I was wrong, my off-site backup is running the git head from the 27th with some patches. I'm updating it now to see if this happens on it, too.

**Comment by angstymeat** [comment]
Something I've noticed on my graphs... I run zswap (the kernel module that allows you to compress writes to your swap file, nothing to do with ZFS) and both times when this happened the system was writing to the swap partition, but the compression ration was insane.

The first time, I had written 1.9GB of data that was only taking up 850K. This time, I crashed after it had paged-out around 500GB, taking up only 135K of space.

That seems like it is writing a bunch of 0-filled pages or something.

Before this, the most I had written-out to swap was 100MB, and that was with the system running continuously for 9 months (Fedora 18 previously, just updated it to 22 on Tuesday).

The huge jumps in paging seem to correspond to rsync, but only appear to happen when the main memory is full. I'm doing some tests to see if this is related to #3643 in any way.

**Comment by angstymeat** [comment]
Also, did scrub behavior change recently? I'm noticing that arc_reclaim is running almost continuously when a scrub is running, and neither my system memory or my arc usage is anywhere near full.

**Comment by sempervictus** [comment]
The last two builds of ZFS we did resulted in very similar lockups, and damage to an ecryptfs mount atop ZFS which had to be rolled back three snaps just to keep the entire system from hard-locking on access to the affected ecryptfs structures. Which patches are you running?

**Comment by siebenmann** [comment]
arc_reclaim running almost continuously may be issue #3637, which was only fixed in a pair of commits pushed to the tree on July 30th (specifically 11f552fa9074a94dac3463300e369013ec2f1544). If you're running a recent git tip from before then, you may be running into this.

**Comment by angstymeat** [comment]
I installed after that commit, which is why I was surprised.

However, I spent the weekend trying to cause it to freeze up again, and failed. After the last time I recompiled ZFS and reinstalled it, so maybe I made a mistake the previous time.

Anyway, I'm keeping an eye on it and if I don't have an issue again by the end of the week, I'm going to close this ticket.

**Comment by angstymeat** [comment]
It's starting again, as far as I can tell.

zswap stats are showing over 1GB swapped out, taking up 166.9K of space. That's a compression factor of somewhere around 6036:1, so it seems like a lot of empty pages (or at least pages with all the same data) being written out or something.

Currently, arc_reclaim and arc_prune are popping-up, but not consuming large amounts of CPU time like they were earlier.

When this has happened before, I was anywhere from an hour to a day away from a crash, depending on how loaded the system was.

ZFS version is showing 0.6.4-184_g6bec435, so that should be the version with the fix for #3637.

The system is primarily a write-workload with lots of small writes to a lot of memory-mapped files.

I've done a debug dump and put it up at https://cloud.passcal.nmt.edu/index.php/s/2qeli2DK8tCmZc8, if that's helpful at all.

**Comment by angstymeat** [comment]
Looking at my graphs, both times the swap file surged was when it looks like the arc is dropping cached file data and storing more metadata.

**Comment by angstymeat** [comment]
I'm having this happen on another machine, now, my off-site backup server.

It hasn't frozen, but access time is slow right now while running a ```zfs send``` to backup a filesystem to another file on the same machine. ```zfs list``` is taking upwards of 10 seconds for just 29 filesystems. ```arc_reclaim``` is at ~107% (8 cpu system).

My arc is draining while at the same time the my paging file has grown from 0 to 1.2GB (again, with a 2048:1 compression ratio, so a lot of repeating data).

The system has been up for 4 days, running rsyncs with other systems a couple of times each day, and the swap file hasn't been touched (I haven't gone into swap in over two months on this system).

I've made another set of traces for this machine at https://cloud.passcal.nmt.edu/index.php/s/o2FnjSfCWf2FcFr.

It does appear that it takes at least several days to get to the point where this occurs, and it seems that scrubs and sends can push it over the edge.

**Comment by angstymeat** [comment]
It's about an hour after my send finished and my arc is still continuing to drain, although it is slowing. I now have 3.38GB written out to swap.

Here are the relevant graphs. (The bottom one says "pages" in the legend, but it is actually bytes).

![ARC Statistics](http://www.passcal.nmt.edu/~mlove/github/arc.png)
![ZSwap Statistics](http://www.passcal.nmt.edu/~mlove/github/swap.png)

**Comment by angstymeat** [comment]
Running a ```zfs send``` on the off-site machine so I can install some new drives next week and restore, but 245GB in, and the send has locked up with no data being read or written. I have one CPU that is 100% in IOWAIT.

I've also jumped up to 4.7GB written out to swap (2.3M after zswap compression).

Here's some ```vmstat``` output:
```
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 0  1   2412 333148  59656 31925168    0    0  3272    59    5    9  1  2 96  1  0
 0  1   2412 333128  59664 31925168    0    0     0     2  100  143  0  0 87 13  0
 0  1   2412 333376  59664 31925168    0    0     0    14   60   67  0  0 88 13  0
 0  1   2412 333420  59672 31925168    0    0     0     2   61   71  0  0 87 13  0
 0  1   2412 333544  59672 31925168    0    0     0     0   65   78  0  0 87 13  0
 0  1   2412 333544  59672 31925168    0    0     0     0   54   61  0  0 87 13  0
 0  1   2412 333544  59672 31925168    0    0     0     0   64   74  0  0 87 13  0
 0  1   2412 333544  59672 31925168    0    0     0     0   65   77  0  0 87 13  0
 0  1   2412 333668  59672 31925168    0    0     0     2   62   74  0  0 87 13  0
 0  1   2412 333668  59672 31925168    0    0     0     0   59   69  0  0 87 13  0
```

**Comment by angstymeat** [comment]
Ok, ignore that previous power about iowait. The network interface was being dropped so NFS was hanging.

**Comment by angstymeat** [comment]
I rebooted and I'm trying ZFS without #3643. My ZFS send has been running for about 90 minutes and I have 23.8GB written out to swap.

Is there a memory leak and the leaked data is being swapped out?

**Comment by angstymeat** [comment]
The system went down about an hour ago, with my arc ~1/3 full, and over 86GB written into swap. Well, mostly down. It's still technically running, but the shell hangs anytime you try to access a ZFS file system.

At 2am my nightly backups started running at the same time as my ```zfs send``` was running, so the system was about as stressed-out as possible.

Currently, I am running SPL 0.6.4-18_g8ac6ffe and ZFS 0.6.4-184_g6bec435, which are the latest versions available with only patch #3344.

Something __has__ to be wrong here.
![Memory](http://www.passcal.nmt.edu/~mlove/github/mem2.png)
![ARC](http://www.passcal.nmt.edu/~mlove/github/arc2.png)
![ZSwap](http://www.passcal.nmt.edu/~mlove/github/swap2.png)

**Comment by angstymeat** [comment]
Ok, I can replicate this within an hour or so now. This last time I got my swap file to 500GB! :)

Anyway, I'm going back through testing commits to see if I can figure out when this started.

**Comment by angstymeat** [comment]
First... my zswap compression ratio numbers are way off. Both values used to be pages that I calculated into bytes. Now, it appears that one has remained pages and the other is now reported as bytes. In reality, the numbers I'm seeing are are nowhere near this dramatic. My swap partition is filling, but it isn't with pages compressed 2000:1.

I've done some more working trying to isolate this today, but I'm going to open a new issue with proper numbers.

**Comment by kernelOfTruth** [comment]
@angstymeat talking about zswap: are you running with default compression algorithm (lzo) or with lz4 ?

```
zswap.compressor=lz4 
```

could help especially when there are lots of zero-filled pages

**Comment by angstymeat** [comment]
My boot cli has it set to lz4, but somewhere around Fedora 20 it stopped working and defaults to lzo with a ```lz4 compressor not available```. It worked in 18 & 19.

I preferred it, but I haven't gone back to tinker with it to get it to work again.

They changed the stats on me, so my swap usage graphs on newer systems were completely off-kilter.

I know that I've managed to crash two machines by just letting them running normally, but I'm going back and doing this over again without forcing it to be low on memory so I can get a better look.

**Comment by angstymeat** [comment]
@kernelOfTruth Your post got me up off my butt to re-enable zswap lz4 on my systems. Thanks.
