### ISSUE TITLE
cannot cancel scrubbing pool: currently resilvering

### ISSUE THREAD

**Issue by FransUrbo** [zfsonlinux/zfs#3657]
Is there an obvious reason why this shouldn't be possible?

```
  pool: pool
 state: ONLINE
status: One or more devices is currently being resilvered.  The pool will
        continue to function, possibly in a degraded state.
action: Wait for the resilver to complete.
  scan: resilver in progress since Wed Aug  5 07:44:56 2015
    7.33T scanned out of 27.3T at 5.15K/s, (scan is slow, no estimated time)
    44.6M resilvered, 26.89% done
```

**Comment by DeHackEd** [comment]
You want to stop a resilver? You can't start a resilver directly.

What are you trying to accomplish?

**Comment by FransUrbo** [comment]
> You want to stop a resilver?
> 
No, a scrub.
> What are you trying to accomplish?
> 
See #3658 for what brought this on.


I couldn't cancel the scrub, because it was resilvering. I don't want
to cancel the resilver, I want to cancel the scrub that was running
_at the same time_ (or paused while the resilver was running).
