### ISSUE TITLE
vdev_id script doesn't find the disks without a tweak

### ISSUE THREAD

**Issue by abuschmann** [zfsonlinux/zfs#3662]
I have set up zfs on a Supermicro 2027R-AR24NV running CentOS 7.1
It has three LSI SAS3008 to connect the 24 disks on the front side.
The default vdev_id script doesn't find any disk.

The problem is .../bay_identifier doesn't give any helpful value:
cat: .../bay_identifier: Invalid argument

I added the following:
<pre># diff -u /usr/lib/udev/vdev_id.dist /usr/lib/udev/vdev_id
--- /usr/lib/udev/vdev_id.dist  2015-06-26 18:24:49.000000000 +0200
+++ /usr/lib/udev/vdev_id       2015-08-05 12:36:48.262748981 +0200
@@ -32,6 +32,7 @@
 # multipath     no
 # topology      sas_direct
 # phys_per_port 4
+# slot         bay
 #
 # #       PCI_ID  HBA PORT  CHANNEL NAME
 # channel 85:00.0 1         A
@@ -93,6 +94,7 @@
 DEV=
 MULTIPATH=
 TOPOLOGY=
+BAY=
 
 usage() {
        cat << EOF
@@ -252,7 +254,25 @@
                i=$(($i + 1))
        done
 
-       SLOT=`cat $end_device_dir/bay_identifier 2>/dev/null`
+       SLOT=
+       case $BAY in
+           "bay") 
+               SLOT=`cat $end_device_dir/bay_identifier 2>/dev/null`
+               ;;
+           "phy") 
+               SLOT=`cat $end_device_dir/phy_identifier 2>/dev/null`
+               ;;
+           "id")
+               i=$(($i + 1))
+               d=$(eval echo \${$i})
+               SLOT=`echo $d | sed -e 's/^.*://'`
+               ;;
+           "lun")
+               i=$(($i + 2))
+               d=$(eval echo \${$i})
+               SLOT=`echo $d | sed -e 's/^.*://'`
+               ;;
+       esac
        if [ -z "$SLOT" ] ; then
                return
        fi
@@ -356,10 +376,15 @@
        TOPOLOGY=`awk "\\$1 == \"topology\" {print \\$2; exit}" $CONFIG`
 fi
 
+if [ -z "$BAY" ] ; then
+       BAY=`awk "\\$1 == \"slot\" {print \\$2; exit}" $CONFIG`
+fi
+
 # First check if an alias was defined for this device.
 ID_VDEV=`alias_handler`
 
 if [ -z "$ID_VDEV" ] ; then
+       BAY=${BAY:-bay}
        TOPOLOGY=${TOPOLOGY:-sas_direct}
        case $TOPOLOGY in
                sas_direct|sas_switch)
</pre>

Now I can use /etc/zfs/vdev_id.conf like:
<pre>
multipath     no
topology      sas_direct
phys_per_port 8
slot          phy

#       PCI_ID  HBA PORT  CHANNEL NAME
channel 03:00.0 0         d1
channel 04:00.0 0         d0
channel 81:00.0 0         d2
</pre>

The **slot** keyword selects where the slot number is taken from:
* **bay:**  .../bay_identifier
* **phy:** .../phy_identifier
* **id:**  the scsi id
* **lun:** the scsi lun

The *scsi id* didn't help me, the order is different than by the phy_identifier.
Anyway, I am not clear on on how anything "sas" maps to the "scsi id".

This gives me the disks connected to the SAS hostadapters.
I have only covered the disks on the backside connected to the SATA hostadapter on the mainboard by an udev script which was done by trial and error.

Do you need further information?

**Comment by behlendorf** [comment]
@abuschmann thanks for posting this.  Can you open a pull request against master with the proposed patch.  That way we won't loose track of it and can get it reviewed and merged.  This looks like a reasonable approach to me but let's run it by @nedbass and get his input.

**Comment by nedbass** [comment]
@abuschmann can you do some cable-pull or drive-pull testing with this?  Some device identifiers get incremented when a device disappears and comes back, so they aren't reliable for uniquely identifying the physical location of a drive.

**Comment by abuschmann** [comment]
@behlendorf 
I have created a pull request: #3693 

@nedbass 
I am not sure which output you need.
I have pulled disk01 and disk13:
<pre>
ls -l /dev/disk/by-vdev/ >/var/tmp/ls-vor-platte-ziehen
lsblk >> /var/tmp/ls-vor-platte-ziehen
cat /proc/scsi/scsi >>/var/tmp/ls-vor-platte-ziehen</pre>

pull disk01

<pre>
ls -l /dev/disk/by-vdev/ >/var/tmp/ls-platte-01-gezogen
lsblk >> /var/tmp/ls-platte-01-gezogen
cat /proc/scsi/scsi >>/var/tmp/ls-platte-01-gezogen</pre>

pull disk13

<pre>
ls -l /dev/disk/by-vdev/ >/var/tmp/ls-platte-13-gezogen
lsblk >> /var/tmp/ls-platte-13-gezogen
cat /proc/scsi/scsi >>/var/tmp/ls-platte-13-gezogen</pre>

The diffs (I have removed the date, as I called "udevadm trigger" inbetween):
<pre>diff /tmp/ls-vor-platte-ziehen /tmp/ls-platte-01-gezogen
3,5d2
< lrwxrwxrwx. 1 root root  9 _date_ d01 -> ../../sdk
< lrwxrwxrwx. 1 root root 10 _date_ d01-part1 -> ../../sdk1
< lrwxrwxrwx. 1 root root 10 _date_ d01-part9 -> ../../sdk9
90,92d86
< sdk                 8:160  0 931.5G  0 disk  
< ├─sdk1              8:161  0 931.5G  0 part  
< └─sdk9              8:169  0     8M  0 part  
160,162d153
<   Vendor: ATA      Model: ST91000640NS     Rev: SN03
<   Type:   Direct-Access                    ANSI  SCSI revision: 06
< Host: scsi8 Channel: 00 Id: 01 Lun: 00</pre>
<pre>diff /tmp/ls-platte-01-gezogen /tmp/ls-platte-13-gezogen
28,30d27
< lrwxrwxrwx. 1 root root  9 _date_ d13 -> ../../sdc
< lrwxrwxrwx. 1 root root 10 _date_ d13-part1 -> ../../sdc1
< lrwxrwxrwx. 1 root root 10 _date_ d13-part9 -> ../../sdc9
58,60d54
< sdc                 8:32   0 931.5G  0 disk  
< ├─sdc1              8:33   0 931.5G  0 part  
< └─sdc9              8:41   0     8M  0 part  
130,132d123
<   Vendor: ATA      Model: ST91000640NS     Rev: SN03
<   Type:   Direct-Access                    ANSI  SCSI revision: 06
< Host: scsi0 Channel: 00 Id: 02 Lun: 00
</pre>
<pre>diff /tmp/ls-vor-platte-ziehen /tmp/ls-platte-13-gezogen
3,5d2
< lrwxrwxrwx. 1 root root  9 _date_ d01 -> ../../sdk
< lrwxrwxrwx. 1 root root 10 _date_ d01-part1 -> ../../sdk1
< lrwxrwxrwx. 1 root root 10 _date_ d01-part9 -> ../../sdk9
31,33d27
< lrwxrwxrwx. 1 root root  9 _date_ d13 -> ../../sdc
< lrwxrwxrwx. 1 root root 10 _date_ d13-part1 -> ../../sdc1
< lrwxrwxrwx. 1 root root 10 _date_ d13-part9 -> ../../sdc9
61,63d54
< sdc                 8:32   0 931.5G  0 disk  
< ├─sdc1              8:33   0 931.5G  0 part  
< └─sdc9              8:41   0     8M  0 part  
90,92d80
< sdk                 8:160  0 931.5G  0 disk  
< ├─sdk1              8:161  0 931.5G  0 part  
< └─sdk9              8:169  0     8M  0 part  
138,140d125
< Host: scsi0 Channel: 00 Id: 02 Lun: 00
<   Vendor: ATA      Model: ST91000640NS     Rev: SN03
<   Type:   Direct-Access                    ANSI  SCSI revision: 06
160,162d144
<   Vendor: ATA      Model: ST91000640NS     Rev: SN03
<   Type:   Direct-Access                    ANSI  SCSI revision: 06
< Host: scsi8 Channel: 00 Id: 01 Lun: 00
</pre>

The excerpt from /var/log/messages:
<pre>Aug 19 15:11:22 sierra kernel: sd 8:0:1:0: device_blocked, handle(0x000a)
Aug 19 15:11:24 sierra kernel: port-8:1: remove: sas_addr(0x4433221101000000)
Aug 19 15:11:24 sierra kernel: port-8:1: remove: sas_addr(0x4433221101000000), phy(1)
Aug 19 15:11:24 sierra kernel: sd 8:0:1:0: [sdk] Synchronizing SCSI cache
Aug 19 15:11:24 sierra kernel: sd 8:0:1:0: [sdk]
Aug 19 15:11:24 sierra kernel: Result: hostbyte=DID_NO_CONNECT driverbyte=DRIVER_OK
Aug 19 15:11:24 sierra kernel: mpt3sas1: removing handle(0x000a), sas_addr(0x4433221101000000)</pre>
<pre>Aug 19 15:28:43 sierra kernel: sd 0:0:2:0: device_blocked, handle(0x000b)
Aug 19 15:28:45 sierra kernel: port-0:2: remove: sas_addr(0x4433221103000000)
Aug 19 15:28:45 sierra kernel: port-0:2: remove: sas_addr(0x4433221103000000), phy(3)
Aug 19 15:28:45 sierra kernel: sd 0:0:2:0: [sdc] Synchronizing SCSI cache
Aug 19 15:28:45 sierra kernel: sd 0:0:2:0: [sdc]
Aug 19 15:28:45 sierra kernel: Result: hostbyte=DID_NO_CONNECT driverbyte=DRIVER_OK
Aug 19 15:28:45 sierra kernel: mpt3sas0: removing handle(0x000b), sas_addr(0x4433221103000000)</pre>

**Comment by nedbass** [comment]
@abuschmann what I want to know is whether the drives come back with the expected names in `/dev/disk/by-vdev` after being removed and re-inserted.  Same for disconnecting and reconnecting the cable for the SAS expander.

**Comment by abuschmann** [comment]
@nedbass the drives came back with the expected names in `/dev/disk/by-vdev` after I reinserted them in the oder disk01, disk13.

I ran a `dd of=/dev/null if=dNN` on each disk to see that they light up in the right order. (from a physical point of view in front of the system.)

<pre>ls -l /dev/disk/by-vdev/ >/var/tmp/ls-nach-platte-stecken
lsblk >>/var/tmp/ls-nach-platte-stecken
cat /proc/scsi/scsi >>/var/tmp/ls-nach-platte-stecken</pre>
The diff gives:
<pre>diff /tmp/ls-vor-platte-ziehen /tmp/ls-nach-platte-stecken 
3,5c3,5
< lrwxrwxrwx. 1 root root  9 _date_ d01 -> ../../sdk
< lrwxrwxrwx. 1 root root 10 _date_ d01-part1 -> ../../sdk1
< lrwxrwxrwx. 1 root root 10 _date_ d01-part9 -> ../../sdk9
---
> lrwxrwxrwx. 1 root root  9 _date_ d01 -> ../../sdc
> lrwxrwxrwx. 1 root root 10 _date_ d01-part1 -> ../../sdc1
> lrwxrwxrwx. 1 root root 10 _date_ d01-part9 -> ../../sdc9
31,33c31,33
< lrwxrwxrwx. 1 root root  9 _date_ d13 -> ../../sdc
< lrwxrwxrwx. 1 root root 10 _date_ d13-part1 -> ../../sdc1
< lrwxrwxrwx. 1 root root 10 _date_ d13-part9 -> ../../sdc9
---
> lrwxrwxrwx. 1 root root  9 _date_ d13 -> ../../sdk
> lrwxrwxrwx. 1 root root 10 _date_ d13-part1 -> ../../sdk1
> lrwxrwxrwx. 1 root root 10 _date_ d13-part9 -> ../../sdk9
138,140d140
< Host: scsi0 Channel: 00 Id: 02 Lun: 00
<   Vendor: ATA      Model: ST91000640NS     Rev: SN03
<   Type:   Direct-Access                    ANSI  SCSI revision: 06
162,164d161
< Host: scsi8 Channel: 00 Id: 01 Lun: 00
<   Vendor: ATA      Model: ST91000640NS     Rev: SN03
<   Type:   Direct-Access                    ANSI  SCSI revision: 06
209a207,212
> Host: scsi8 Channel: 00 Id: 08 Lun: 00
>   Vendor: ATA      Model: ST91000640NS     Rev: SN03
>   Type:   Direct-Access                    ANSI  SCSI revision: 06
> Host: scsi0 Channel: 00 Id: 08 Lun: 00
>   Vendor: ATA      Model: ST91000640NS     Rev: SN03
>   Type:   Direct-Access                    ANSI  SCSI revision: 06
</pre>

The kernel names `/dev/sdc` and `/dev/sdk` get switched between the two disks.

The 'scsi id' of each replaced disk moved to 8, so the 'scsi id' part of my code is not suitable for my  platform.

**Comment by behlendorf** [comment]
@abuschmann thanks for the follow up.  Aside from a minor typo in the patch this looks good to me.

**Comment by abuschmann** [comment]
Thank you for integrating this.

**Comment by nedbass** [comment]
The modified script tested OK for me. The changes look good to me. It's not clear to me whether the "lun" or "id" identifiers will be useful to anyone. I don't have a strong opinion on it, but if there's no clear use case I'd lean toward removing them.

**Comment by abuschmann** [comment]
The background for the "lun" and "id" identifiers is to support the older passive SCSI disk arrays. They are only used in development any more, not in production.
(We still have some in production, but only on old multi role systems which are scheduled to be replaced, but where the new software is not yet done.)

**Comment by behlendorf** [comment]
@abuschmann thanks for iterating on this.  I've squashed the patches together and merged it as:

bba365c Add extra keyword 'slot' to vdev_id.conf
