### ISSUE TITLE
Apparent AIO related crash in CentOS6 doing ZFS send on SCST host

### ISSUE THREAD

**Issue by sempervictus** [zfsonlinux/zfs#3664]
A client system went down sometime between 0130 and 0300 this morning, hard crash, had to be forcibly rebooted from the IPMI console.
The system runs a known stable build of ZoL, with ABD being the only major change from master. However, this is a CentOS6 box on kernel 2.6.32-431.17.1.el6.x86_64, whereas the vast majority of our own and our client systems are Ubuntu LTS (storage hosts with a custom PF-based kernel and SCST patches). This one runs SCST without its TCP zero copy patches (using filleio mode for accessing ZVOLs) serving iSCSI to Xen and the only difference between it and two identical hosts adjacent to it performing the same activities is that it takes and sends snapshots every 15m across a site-to-site link. The crash seems to occur during a send operation only, the other hosts have been running for months with no issue.
We've stabilized the sucker for now, but this may be the 2nd such event in two weeks, and its a show stopper (production env, medical data, so ZFS atop dm-crypt). The last time we also saw SCST errors in dmesg, and also during a ZFS send. 

Has anyone seen anything of this nature? Any suggestions for how to prevent or easily reproduce this for hunting? I have a newer stable build i can push to the system, but i'd like to know if its ZoL or the elderly kernel revision fighting it out with SCST's use of AIO screwing us.

Just in case, ping @ryao since i remember you having worked on AIO a while back.
Thanks for any help folks can provide.

Image of crash dump:

<img width="837" alt="251e4084-36d4-467a-8097-4ff041161c08" src="https://cloud.githubusercontent.com/assets/1331084/9115520/a3253fa2-3c2d-11e5-97aa-a1a5da33e6dd.png">

**Comment by behlendorf** [comment]
@sempervictus I haven't seen anything like this before and there's nothing ZFS related in the posted stack to go on.
