### ISSUE TITLE
# sign for creating bookmarks is not working properly

### ISSUE THREAD

**Issue by fearedbliss** [zfsonlinux/zfs#3665]
Hello,

Taking a bookmark via the following is suppose to work but doesn't (possibly due to the shell?):

zfs bookmark tank/dataset@snapshot #snapshot

however, doing the above makes the zfs command believe that an argument is missing. Doing a # doesn't work and a full qualification of the name is needed (or single quotes):

zfs bookmark tank/dataset@snapshot tank/dataset#snapshot

---

octopus ~ # zfs list -t bookmark
no datasets available

octopus ~ # zfs bookmark tank/gentoo/root@2015-08-06-0000-01-DAILY #test
missing bookmark argument
usage:
        bookmark <snapshot> <bookmark>

For the property list, run: zfs set|get

For the delegated permission list, run: zfs allow|unallow
octopus ~ # zfs bookmark tank/gentoo/root@2015-08-06-0000-01-DAILY tank/gentoo/root#test
octopus ~ # zfs list -t bookmark
NAME                    USED  AVAIL  REFER  MOUNTPOINT
tank/gentoo/root#test      -      -      -  -
- Jonathan

**Comment by DeHackEd** [comment]
Yes the shell is causing a bit of trouble there. For reference, # is a shell metacharacter for "comment" so your first test actually never named a bookmark. From the tool's standpoint, the error of missing arguments is correct.

<pre># zfs bookmark atmaweapon/home@2015-08-18 \#2015-08-18
cannot create bookmark '#2015-08-18': invalid argument
</pre>
It would be nice if this syntax was supported though. `zfs rename pool/fsname@snap1 @newname` does work so it should be feasible.

**Comment by fearedbliss** [comment]
Renaming a snapshot defeats the purpose of the bookmark though since the
difference between. The bookmark and the snapshot is that the snapshot
actually holds data while the bookmark is just a reference in time that you
can use a point to do a send/recv.
