### ISSUE TITLE
Sending a bookmark on zfs doesn't allow the -vn flags to be used

### ISSUE THREAD

**Issue by fearedbliss** [zfsonlinux/zfs#3666]
Hello,

If one tries to send an incremental backup from one point to another and would like to see how much data would be sent (-vn), one would normally use a 'fromSnap' and 'toSnap' and this would work. However, if you try to do this from a #bookmark created at the same point as the 'fromSnap', this will not work. 

octopus ~ # zfs list -t bookmark
NAME USED AVAIL REFER MOUNTPOINT
tank/gentoo/root#test - - - -
octopus ~ # zfs send -vn -i tank/gentoo/root#test tank/gentoo/root@2015-08-06-1000-01-HOURLY
Error: Unsupported flag with filesystem or bookmark.
octopus ~ # zpool get feature@bookmarks tank
NAME  PROPERTY           VALUE              SOURCE
tank  feature@bookmarks  active             local

The above does work if I remove the -vn flags. However that would mean that I would lose information regarding how much data will be sent and has been sent.
- Jonathan

**Comment by DeHackEd** [comment]
I thought 5dc8b7365ff1932bfd969bc71cd49db9b3a6dc87 was supposed to fix this. Are you running the latest Git head?

**Comment by fearedbliss** [comment]
Nope. I only run the latest released version (0.4.2-r2)

**Comment by mailinglists35** [comment]
this issue is still present in latest git master

**Comment by yacoob** [comment]
Hit this just now with 
```
[    9.254770] ZFS: Loaded module v0.6.5.8-1, ZFS pool version 5000, ZFS filesystem version 5
```

Curiously enough, it bombs up for me with both `-vn` and `-R`, independently of each other:

```shell
root@archiso ~ # zfs send oldpool/sys/home > /dev/null
root@archiso ~ # zfs send -vn oldpool/sys/home > /dev/null
Error: Unsupported flag with filesystem or bookmark.
1 root@archiso ~ # zfs send -R oldpool/sys/home > /dev/null
Error: Unsupported flag with filesystem or bookmark.
```

I don't have any bookmarks on `oldpool`:
```
root@archiso ~ # zfs list -r -t bookmark oldpool
no datasets available
```
and the set of flags supported by my operating environment (custom archiso with zfs) and `oldpool` seems to be the same:

```
root@archiso ~ # zpool upgrade
This system supports ZFS pool feature flags.

All pools are formatted using feature flags.

Every feature flags pool has all supported features enabled.
```

**Comment by ptx0** [comment]
it also breaks using `-I` to send bookmarks.

```
# sudo zfs send -I tank/vdisks/576dc668c3bef#1491143762 tank/vdisks/576dc668c3bef@1492309999 > /dev/null
Error: Unsupported flag with filesystem or bookmark.

```

**Comment by rugubara** [comment]
from zfs man:
`  zfs send [-DnPpRveLc] [-[iI] snapshot|bookmark] snapshot`
Apparently -I should accept a bookmark, but it doesn't. I run latest master.
