### ISSUE TITLE
cannot mount zfs in rw mode. endless rcu_sched warnings

### ISSUE THREAD

**Issue by n-other** [zfsonlinux/zfs#3670]
Hello,

I am running zfs 0.6.4.2 on debian jessie with 3.16 kernel and currently having few issues:

1) I cannot mount zfs in rw mode. it hangs forever while kernel throws out rcu_sched warnings:
INFO: rcu_sched detected stalls on CPU/tasks...
Also the system becomes unresponsive and can be recovered only by hard reset.
It appeared after filesystem was 100% full and recovered by adding additional disks to the pool
The only solution to access pool at the moment is to set set pool to readonly, mount it and set back to readwrite. As a matter of experiment I've tried to boot from freebsd and mount this pool, however it crashed around zfs_unlinked_drain(). 

2) space is not reclaimed back from files being deleted. output from zdb -dddd msapool/brick01 3|head -n 30:
Dataset msapool/brick01 [ZPL], ID 43, cr_txg 204, 63.8T, 2014740 objects, rootbp DVA[0]=<6:3783ddfe400:400> DVA[1]=<7:a161eb3400:400> [L0 DMU objset] fletcher4 lz4 LE contiguous unique double size=800L/200P birth=9531323L/9531323P fill=2014740 cksum=136db4ed17:68e1e3ddaef:131ed9bb79a6f:27af41cfd42bba

```
Object  lvl   iblk   dblk  dsize  lsize   %full  type
     3    2    16K    16K  1.74M  3.66M  100.00  ZFS delete queue
    dnode flags: USED_BYTES USERUSED_ACCOUNTED 
    dnode maxblkid: 233
    Fat ZAP stats:
            Pointer table:
                    1024 elements
                    zt_blk: 0
                    zt_numblks: 0
                    zt_shift: 10
                    zt_blks_copied: 0
                    zt_nextblk: 0
            ZAP entries: 729
            Leaf blocks: 233
            Total blocks: 234
            zap_block_type: 0x8000000000000001
            zap_magic: 0x2f52ab2ab
            zap_salt: 0x4967fd47
            Leafs with 2^n pointers:
                      1:      2 *
                      2:    207 ****************************************
                      3:     24 *****
            Blocks with n*5 entries:
                      0:    181 ****************************************
                      1:     49 ***********
                      2:      3 *
            Blocks n/10 full:
                      1:    233 ****************************************
```

I guess this one is a consequence of previous problem. i've checked through the code and it looks like zfs_unlinked_drain() is not run for read-only mounted pools.

3) zpool status -v shows

errors: Permanent errors have been detected in the following files:

```
    msapool/brick01:<0x31f311>
```

and I was never been able to recover this error file with scrub.

**Comment by n-other** [comment]
I also found really strange object while making zdb -dddd through the whole pool.
here is the object output:

Dataset msapool/brick01 [ZPL], ID 43, cr_txg 204, 63.8T, 2014775 objects, rootbp DVA[0]=<1:572d3a5a400:400> DVA[1]=<2:726e90c400:400> [L0 DMU objset] fletcher4 lz4 LE contiguous unique double size=800L/200P birth=9538649L/9538649P fill=2014775 cksum=1081091e5a:5d6409628bf:11a0fcb401122:257f27de50d193

    Object  lvl   iblk   dblk  dsize  lsize   %full  type
    246298    1    16K    512      0    512    0.00  ZFS directory
                                        168   bonus  System attributes
        dnode flags: USED_BYTES USERUSED_ACCOUNTED 
        dnode maxblkid: 0
        path    ???<object#246298>
        uid     1001
        gid     1001
        atime   Thu Jun 11 19:23:03 2015
        mtime   Sun Jun 21 08:53:30 2015
        ctime   Sun Jun 21 08:53:30 2015
        crtime  Thu Jun 11 19:23:03 2015
        gen     8616709
        mode    41777
        size    2
        parent  246297
        links   0
        pflags  40800000145
        Fat ZAP stats:
                Pointer table:
                        1 elements
                        zt_blk: 0
                        zt_numblks: 0
                        zt_shift: 0
                        zt_blks_copied: 0
                        zt_nextblk: 0
                ZAP entries: 0
                Leaf blocks: 0
                Total blocks: 0
                zap_block_type: 0x0
                zap_magic: 0x0
                zap_salt: 0x0
                Leafs with 2^n pointers:
                Blocks with n*5 entries:
                Blocks n/10 full:
                Entries with n chunks:
                Buckets with n entries:

following by endless calls like: 
futex(0x7fdbfc5f9f38, FUTEX_WAKE_PRIVATE, 2) = 0
at this time CPU is getting 100% used by zdb.

I also couldn't find parent object 246297 for this object. Could it be the reason for zdb not able to process it? How do I fix it?

**Comment by dweeezil** [comment]
@n-other It might be interesting to dump that specific dnode with my patched zdb from https://github.com/dweeezil/zfs/tree/zdb.  It adds a bunch of verbose stuff designed to troubleshoot corrupted SAs but it might also help in this case (use ```-ddddddd```).

**Comment by n-other** [comment]
@dweeezil here it is. doesn't look much different :(

# /usr/src/dweeezil.zfs/cmd/zdb/.libs/zdb -ddddddd msapool/brick01 246298
Dataset msapool/brick01 [ZPL], ID 43, cr_txg 204, 63.8T, 2014812 objects, rootbp DVA[0]=<6:5f3875f5000:400> DVA[1]=<7:a36280ec00:400> [L0 DMU objset] fletcher4 lz4 LE contiguous unique double size=800L/200P birth=9551486L/9551486P fill=2014812 cksum=1468f935eb:6fc8b86821e:144400da81f15:29473827fce34e

    Object  lvl   iblk   dblk  dsize  lsize   %full  type
    246298    1    16K    512      0    512    0.00  ZFS directory (K=inherit) (Z=inherit)
                                        168   bonus  System attributes
        dnode flags: USED_BYTES USERUSED_ACCOUNTED 
        dnode maxblkid: 0
        path    ???<object#246298>
        uid     1001
        gid     1001
        atime   Thu Jun 11 19:23:03 2015
        mtime   Sun Jun 21 08:53:30 2015
        ctime   Sun Jun 21 08:53:30 2015
        crtime  Thu Jun 11 19:23:03 2015
        gen     8616709
        mode    41777
        size    2
        parent  246297
        links   0
        pflags  40800000145
        Fat ZAP stats:
                Pointer table:
                        1 elements
                        zt_blk: 0
                        zt_numblks: 0
                        zt_shift: 0
                        zt_blks_copied: 0
                        zt_nextblk: 0
                ZAP entries: 0
                Leaf blocks: 0
                Total blocks: 0
                zap_block_type: 0x0
                zap_magic: 0x0
                zap_salt: 0x0
                Leafs with 2^n pointers:
                Blocks with n*5 entries:
                Blocks n/10 full:
                Entries with n chunks:
                Buckets with n entries:

**Comment by dweeezil** [comment]
@n-other That's not my hacked zdb.  It will _always_ at least print the "SA hdrsize" and "SA layout" lines prior to the "path".  Once you get the hacked zdb running properly, I'd also like to see the output of ```zdb -dddd  msapool/brick01 5 6```.

My guess is that you may have tried to transplant my patches atop whatever sources you are using but didn't get all the commits.  The ```zdb``` branch I referenced contains __8__ patches atop a current master.

**Comment by n-other** [comment]
Hi @dweeezil,

here they are:


    Object  lvl   iblk   dblk  dsize  lsize   %full  type
         5    1    16K  1.50K  6.50K  1.50K  100.00  SA attr registration (K=inherit) (Z=inherit)
        dnode flags: USED_BYTES USERUSED_ACCOUNTED 
        dnode maxblkid: 0
        microzap: 1536 bytes, 21 entries

                ZPL_DACL_ACES =  40013 : [0:4:19]
                ZPL_DXATTR =  30014 : [0:3:20]
                ZPL_UID =  800000c : [8:0:12]
                ZPL_RDEV =  800000a : [8:0:10]
                ZPL_SYMLINK =  30011 : [0:3:17]
                ZPL_CRTIME =  10000003 : [16:0:3]
                ZPL_LINKS =  8000008 : [8:0:8]
                ZPL_ATIME =  10000000 : [16:0:0]
                ZPL_GEN =  8000004 : [8:0:4]
                ZPL_PARENT =  8000007 : [8:0:7]
                ZPL_GID =  800000d : [8:0:13]
                ZPL_XATTR =  8000009 : [8:0:9]
                ZPL_MODE =  8000005 : [8:0:5]
                ZPL_SCANSTAMP =  20030012 : [32:3:18]
                ZPL_SIZE =  8000006 : [8:0:6]
                ZPL_DACL_COUNT =  8000010 : [8:0:16]
                ZPL_FLAGS =  800000b : [8:0:11]
                ZPL_ZNODE_ACL =  5803000f : [88:3:15]
                ZPL_MTIME =  10000001 : [16:0:1]
                ZPL_CTIME =  10000002 : [16:0:2]
                ZPL_PAD =  2000000e : [32:0:14]
Indirect blocks:
               0 L0 0:178000:2000 1:b000:400 600L/200P F=1 B=204/204

                segment [0000000000000000, 0000000000000600) size 1.50K

    Object  lvl   iblk   dblk  dsize  lsize   %full  type
         6    1    16K    16K    16K    32K  100.00  SA attr layouts (K=inherit) (Z=inherit)
        dnode flags: USED_BYTES USERUSED_ACCOUNTED 
        dnode maxblkid: 1
        Fat ZAP stats:
                Pointer table:
                        1024 elements
                        zt_blk: 0
                        zt_numblks: 0
                        zt_shift: 10
                        zt_blks_copied: 0
                        zt_nextblk: 0
                ZAP entries: 5
                Leaf blocks: 1
                Total blocks: 2
                zap_block_type: 0x8000000000000001
                zap_magic: 0x2f52ab2ab
                zap_salt: 0x497c8a4d
                Leafs with 2^n pointers:
                          9:      1 *
                Blocks with n*5 entries:
                          1:      1 *
                Blocks n/10 full:
                          1:      1 *
                Entries with n chunks:
                          3:      1 *
                          4:      4 ****
                Buckets with n entries:
                          0:    507 ****************************************
                          1:      5 *

                5 = [ 17 ]
                2 = [ 5  6  4  12  13  7  11  0  1  2  3  8  16  19 ]
                6 = [ 5  6  4  12  13  7  11  0  1  2  3  8  16  19  17  9 ]
                3 = [ 5  6  4  12  13  7  11  0  1  2  3  8  16  19  9 ]
                4 = [ 5  6  4  12  13  7  11  0  1  2  3  8  16  19  17 ]
Indirect blocks:
               0 L0 1:4c976a9f800:800 0:4a43a5ec000:2000 4000L/400P F=1 B=47458/47458
            4000 L0 1:4c976a9e400:1000 0:4a43a5ea000:2000 4000L/a00P F=1 B=47458/47458

                segment [0000000000000000, 0000000000008000) size   32K


    Object  lvl   iblk   dblk  dsize  lsize   %full  type
    246298    1    16K    512      0    512    0.00  ZFS directory (K=inherit) (Z=inherit)
                                        168   bonus  System attributes
        dnode flags: USED_BYTES USERUSED_ACCOUNTED 
        dnode maxblkid: 0
        SA hdrsize 8
        SA layout 2
        path    ???<object#246298>
        uid     1001
        gid     1001
        atime   Thu Jun 11 19:23:03 2015
        mtime   Sun Jun 21 08:53:30 2015
        ctime   Sun Jun 21 08:53:30 2015
        crtime  Thu Jun 11 19:23:03 2015
        gen     8616709
        mode    41777
        size    2
        parent  246297
        links   0
        pflags  40800000145
        ndacl   3
        Misc SA sizes:
                DACL_ACES = 24
                ZNODE_ACL = N/A
        dump_znode_sa_xattr: sa_xattr_size=0 sa_size error=2
        Fat ZAP stats:
                Pointer table:
                        1 elements
                        zt_blk: 0
                        zt_numblks: 0
                        zt_shift: 0
                        zt_blks_copied: 0
                        zt_nextblk: 0
                ZAP entries: 0
                Leaf blocks: 0
                Total blocks: 0
                zap_block_type: 0x0
                zap_magic: 0x0 
                zap_salt: 0x0
                Leafs with 2^n pointers:
                Blocks with n*5 entries:
                Blocks n/10 full:
                Entries with n chunks:
                Buckets with n entries:

**Comment by n-other** [comment]
also, the one from my first mail:

msapool/brick01:<0x31f311>

do I understand it right and 0x31f311 represents hex number of inode? if this is true, here is the dump for this node also:

    Object  lvl   iblk   dblk  dsize  lsize   %full  type
   3273489    3    16K   128K   245M   245M  100.00  ZFS plain file (K=inherit) (Z=inherit)
                                        176   bonus  System attributes
        dnode flags: USED_BYTES USERUSED_ACCOUNTED 
        dnode maxblkid: 1960
        SA hdrsize 8
        SA layout 3
        path    ???<object#3273489>
        uid     33
        gid     33
        atime   Thu May  7 01:55:25 2015
        mtime   Thu May  7 09:58:43 2015
        ctime   Mon May 18 20:27:31 2015
        crtime  Thu May  7 01:55:03 2015
        gen     7980384
        mode    100644
        size    256947652
        parent  3278516
        links   1
        pflags  40800000004
        ndacl   3
        xattr   3278538
        Misc SA sizes:
                DACL_ACES = 24
                ZNODE_ACL = N/A
        dump_znode_sa_xattr: sa_xattr_size=0 sa_size error=2
Indirect blocks:
               0 L2   3:3811d808c00:800 4:a1db2df400:800 4000L/600P F=1961 B=7980388/7980388
               0  L1  1:3e1754e4800:2000 2:24000334400:2000 4000L/1600P F=128 B=7980384/7980384
               0   L0 2:240c0c2b000:2ac00 20000L/20000P F=1 B=7980384/7980384
           20000   L0 3:22695ce8c00:2ac00 20000L/20000P F=1 B=7980384/7980384
.
.
.
lot's of similar lines
.
.
.
         f4a0000   L0 3:38b4ab61c00:2ac00 20000L/20000P F=1 B=7980388/7980388
         f4c0000   L0 3:38b4ab8c800:2ac00 20000L/20000P F=1 B=7980388/7980388
         f4e0000   L0 3:38b4abb7400:2ac00 20000L/20000P F=1 B=7980388/7980388
         f500000   L0 3:38b4abe2000:2ac00 20000L/20000P F=1 B=7980388/7980388

                segment [0000000000000000, 000000000f520000) size  245M

**Comment by dweeezil** [comment]
@n-other  The dnode is fine.  It's an incompletely-removed directory and shouldn't exist anymore.  This is a case of filesystem corruption which shouldn't be able to happen.  Does your system have ECC memory?

**Comment by n-other** [comment]
@dweeezil According to dmidecode the system supports Single-bit ECC. If this dnode is fine, why does it make zdb to hang and consume all possible CPU? Missing parent?

I don't have possibility to make backup and restore for this fs due to it's size. Can you recommend good recovery approach?

**Comment by n-other** [comment]
Hi, after few tests I can state that the problem with file deletion is somewhere around xattr processing:

i've created few additional datasets on the the pool, here is current xattrs:

NAME                 PROPERTY  VALUE  SOURCE
msapool              xattr     on     local
msapool/brick01      xattr     on     local
msapool/brick02      xattr     sa     local
msapool/testbrick01  xattr     on     local
msapool/testbrick02  xattr     sa     local

and tried to copy and delete files to both testbrick01 and testbrick02

after deletion of all copied files on both testbrick01 and testbrick02 df shows:

msapool/testbrick02       111700992         128 111700864   1% /export/testbrick02
msapool/testbrick01       114736768     3035904 111700864   3% /export/testbrick01

and testbrick01 again has a delete queue containing few  items:
Dataset msapool/testbrick01 [ZPL], ID 4602, cr_txg 9549134, 2.90G, 174 objects, rootbp DVA[0]=<6:43d1e82400:400> DVA[1]=<7:e61409d000:400> [L0 DMU objset] fletcher4 lz4 LE contiguous unique double size=800L/200P birth=9611442L/9611442P fill=174 cksum=12bdf92882:68e67f1d98c:137eaed887b51:28b15ac83f26ab

    Object  lvl   iblk   dblk  dsize  lsize   %full  type
         3    1    16K  2.50K  1.50K  2.50K  100.00  ZFS delete queue
        dnode flags: USED_BYTES USERUSED_ACCOUNTED 
        dnode maxblkid: 0
        microzap: 2560 bytes, 32 entries

                a3 = 163 
                33 = 51 
                8a = 138 
                6e = 110 
                3c = 60 
                81 = 129 
                65 = 101 
                7a = 122 
                68 = 104 
                62 = 98 
                49 = 73 
                6b = 107 
                71 = 113 
                91 = 145 
                9a = 154 
                7e = 126 
                7b = 123 
                48 = 72 
                42 = 66 
                87 = 135 
                3b = 59 
                5f = 95 
                a2 = 162 
                58 = 88 
                52 = 82 
                84 = 132 
                3f = 63 
                3a = 58 
                55 = 85 
                74 = 116 
                a1 = 161 
                5e = 94 
Indirect blocks:
               0 L0 1:53c6fe14000:400 a00L/200P F=1 B=9611334/9611334

                segment [0000000000000000, 0000000000000a00) size 2.50K

while testbrick02 does not:

Dataset msapool/testbrick02 [ZPL], ID 4608, cr_txg 9549136, 63.6K, 28 objects, rootbp DVA[0]=<10:51105b12400:400> DVA[1]=<11:1df9c09b000:400> [L0 DMU objset] fletcher4 lz4 LE contiguous unique double size=800L/200P birth=9611448L/9611448P fill=28 cksum=117298d0ee:5ea286428a2:1139f3d3b418f:23925bba9b981a

    Object  lvl   iblk   dblk  dsize  lsize   %full  type
         3    1    16K    512  1.50K    512  100.00  ZFS delete queue
        dnode flags: USED_BYTES USERUSED_ACCOUNTED 
        dnode maxblkid: 0
        microzap: 512 bytes, 0 entries

Indirect blocks:
               0 L0 9:68012feb000:400 200L/200P F=1 B=9611329/9611329

                segment [0000000000000000, 0000000000000200) size   512
