### ISSUE TITLE
Extremely slow zvol nodes creation when pool is resilvering (or repairing)

### ISSUE THREAD

**Issue by ab-oe** [zfsonlinux/zfs#3682]
Hello,
I've noticed problem with importing pool when one mirror device was previously replaced or when the scrub operation was running. Creation of zvol nodes is extremely slow and udev gets timeout. For example the execution of **/lib/udev/zvol_id /dev/zd0** takes several minutes. I tried to modify following parameters with different combinations but I didn't noticed any impact on zvol nodes creation (only scrub/resilver speed was affected):
- zfs_scrub_delay
- zfs_vdev_scrub_max_active
- zfs_vdev_scrub_min_active
- zfs_resilver_delay
- zfs_resilver_min_time_ms
- zfs_scan_idle
- zfs_scan_min_time_ms
- zfs_top_maxinflight

The only thing that resolved this issue was setting **zfs_no_scrub_io** to **1** but I don't wan't to disable I/O on resilver process.

Zpool structure looks as follows:

```
zpool status
  pool: Pool-0
 state: ONLINE
status: One or more devices has experienced an unrecoverable error.  An
    attempt was made to correct the error.  Applications are unaffected.
action: Determine if the device needs to be replaced, and clear the errors
    using 'zpool clear' or replace the device with 'zpool replace'.
   see: http://zfsonlinux.org/msg/ZFS-8000-9P
  scan: scrub in progress since Wed Aug 12 14:09:28 2015
    123G scanned out of 1.01T at 13.6M/s, 19h8m to go
    24.1G repaired, 11.84% done
config:

    NAME                                        STATE     READ WRITE CKSUM
    Pool-0                                      ONLINE       0     0     0
      mirror-0                                  ONLINE       0     0     0
        scsi-3500003948830326c                  ONLINE       0     0     0
        scsi-35000039488303270                  ONLINE       0     0     0
      mirror-1                                  ONLINE       0     0     0
        scsi-3500003949800bc04                  ONLINE       0     0     0
        scsi-3500003949800aea0                  ONLINE       0     0     0
      mirror-2                                  ONLINE       0     0     0
        scsi-SWD_WD9001BKHG-02D22_WX31EA1EC340  ONLINE       0     0   764  (repairing)
        scsi-3500003949800aea4                  ONLINE       0     0     0
      mirror-3                                  ONLINE       0     0     0
        scsi-3500003949800baec                  ONLINE       0     0     0
        scsi-STOSHIBA_AL13SEB900_2320A034FTR6   ONLINE       0     0     0
      mirror-4                                  ONLINE       0     0     0
        scsi-3500003949800baf8                  ONLINE       0     0     0
        scsi-3500003949800bae4                  ONLINE       0     0     0
    logs
      scsi-3500117310023e10c                    ONLINE       0     0     0

zfs list
NAME            USED  AVAIL  REFER  MOUNTPOINT
Pool-0         1.48T  2.52T   616K  /Pools/Pool-0
Pool-0/system    4.13G  2.52T   132M  -
Pool-0/share1   200G  2.52T   200G  /Pools/Pool-0/share1
Pool-0/share2   128K  2.52T   128K  /Pools/Pool-0/share2
Pool-0/store1   301G  2.57T   250G  -
Pool-0/store2   301G  2.57T   250G  -
Pool-0/store3   301G  2.58T   244G  -
Pool-0/store4   301G  2.81T   944K  -
Pool-0/win1     100G  2.54T  84.4G  -
Pool-0/win2    7.46G  2.52T  7.46G  -
```

Creation of zvol nodes in /dev takes about 100s

```
[10002.358799]  zd0: p1
[10023.445628]  zd16: p1
[10044.547048]  zd32: unknown partition table
[10065.831818]  zd48: p1
[10087.211811]  zd64: p1
[10087.271218]  zd80: p1
[10108.491638]  zd96: p1
```

Test environment:
CPU: 2 x Intel Xeon CPU E5-2643
RAM: 128GB
Kernel: 3.10
ZFS version: 0.6.4.2 release

I think it is related to #3659

**Comment by behlendorf** [comment]
@ab-oe does the proposed fix in #3659 resolve the issue?

**Comment by ab-oe** [comment]
@behlendorf unfortunately no. Zvol creation is still very slow. I can't see any difference with or without the patch.

**Comment by ab-oe** [comment]
I created work-around for that issue that won't corrupt data like setting zfs_no_scrub_io. 

The following patch adds new parameter to zfo module named "zfs_block_scan". When set it block scanning until it is unset. Blocking resilver for the time of import eliminates the issue with slow zvol nodes creation. The resilver restarts at the same place where it was blocked so the data integrity isn't affected.

```
Index: module/zfs/dsl_scan.c
===================================================================
--- module/zfs/dsl_scan.c	(revision 41200)
+++ module/zfs/dsl_scan.c	(working copy)
@@ -61,6 +61,7 @@
 int zfs_resilver_delay = 2;		/* number of ticks to delay resilver */
 int zfs_scrub_delay = 4;		/* number of ticks to delay scrub */
 int zfs_scan_idle = 50;			/* idle window in clock ticks */
+int zfs_block_scan = 0;			/* block scanning */
 
 int zfs_scan_min_time_ms = 1000; /* min millisecs to scrub per txg */
 int zfs_free_min_time_ms = 1000; /* min millisecs to free per txg */
@@ -1469,6 +1470,11 @@
 		dsl_scan_setup_sync(&func, tx);
 	}
 
+	/* scanning is currently blocked, try again later */
+	if (zfs_block_scan) {
+	    return;
+	}
+
 	/*
 	 * If the scan is inactive due to a stalled async destroy, try again.
 	 */
@@ -1884,6 +1890,9 @@
 module_param(zfs_scrub_delay, int, 0644);
 MODULE_PARM_DESC(zfs_scrub_delay, "Number of ticks to delay scrub");
 
+module_param(zfs_block_scan, int, 0644);
+MODULE_PARM_DESC(zfs_block_scan, "Block scrub/resilver");
+
 module_param(zfs_scan_idle, int, 0644);
 MODULE_PARM_DESC(zfs_scan_idle, "Idle window in clock ticks");
```

**Comment by richardelling** [comment]
Philosophically, this workaround is painful. We try to make ZFS as auto-tuning as possible, requiring as little manual intervention as possible. Adding this sort of "magic tunable" is difficult to document in a meaningful way and sustain over time. Surely there is a better, more permanent, no-manual-intervention-required solution?

**Comment by ab-oe** [comment]
I understand but I haven't found any other solution for that. The time of "bringing up" one zvol can be greater than one minute. I know I can increase udev event timeout but so slow import is unacceptable in cluster environment.

**Comment by behlendorf** [comment]
@ab-oe additional improvements have been made which will appear in 0.7.0-rc2 which are expected to improve the situation.  They include.

* 7ac557c - zpool_create_minors parallel prefetch
* 899662e - zvol_remove_minors do parallel zvol_free
* d45e010 - zvol: reduce linear list search
