### ISSUE TITLE
CentOS 7.1: importing pool with special zil device fails

### ISSUE THREAD

**Issue by abuschmann** [zfsonlinux/zfs#3689]
I have set up zfs on a Supermicro 2027R-AR24NV running CentOS 7.1

I am trying to use zfs with the zil device on NVDIMM, which uses a special block driver.
(The device is effectively a non volatile ramdisk.)
`zfs import` fails with a corrupt log device.

I have not problems when running the zil on a normal disk.

<pre># uname -a
Linux sierra.sasys-int.de 3.10.0-229.7.2.el7.x86_64 #1 SMP Tue Jun 23 22:06:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
# dkms status 
spl, 0.6.4.2, 3.10.0-229.7.2.el7.x86_64, x86_64: installed
zfs, 0.6.4.2, 3.10.0-229.7.2.el7.x86_64, x86_64: installed
spl, 0.6.4.2, 3.10.0-123.el7.x86_64, x86_64: installed-weak from 3.10.0-229.7.2.el7.x86_64
zfs, 0.6.4.2, 3.10.0-123.el7.x86_64, x86_64: installed-weak from 3.10.0-229.7.2.el7.x86_64
spl, 0.6.4.2, 3.10.0-229.1.2.el7.x86_64, x86_64: installed-weak from 3.10.0-229.7.2.el7.x86_64
zfs, 0.6.4.2, 3.10.0-229.1.2.el7.x86_64, x86_64: installed-weak from 3.10.0-229.7.2.el7.x86_64</pre>

To reproduce:
<pre>zpool create -f tank raidz2 d01 d02 d03 d04 d05 d06 d07 \
        d11 d12 d13 d14 d15 d16 d17 log arxcis_b0
[1127407.378630] arxcis_b: debug: arx_ioctl: unsupported ioctl 0x2285: return -ENOTTY

zpool export tank
zpool import
   pool: tank
     id: 14173017687901805883
  state: DEGRADED
 status: One or more devices contains corrupted data.
 action: The pool can be imported despite missing or damaged devices.  The
        fault tolerance of the pool may be compromised if imported.
   see: http://zfsonlinux.org/msg/ZFS-8000-4J
 config:

        tank         DEGRADED
          raidz2-0   ONLINE
            d01      ONLINE
            d02      ONLINE
            d03      ONLINE
            d04      ONLINE
            d05      ONLINE
            d06      ONLINE
            d07      ONLINE
            d11      ONLINE
            d12      ONLINE
            d13      ONLINE
            d14      ONLINE
            d15      ONLINE
            d16      ONLINE
            d17      ONLINE
        logs
          arxcis_b0  UNAVAIL  corrupted data
ls -l /dev/arxcis_b0
brw-rw----. 1 root disk 252, 0 Aug 18 14:06 /dev/arxcis_b0</pre>

How do I debug this?
Do I need full udev bindings before I can use a block device for zfs?

I have notices that the disk devices used for zfs have a gpt partition table like this:
<pre>parted /dev/disk/by-vdev/d01 print
Model: ATA ST91000640NS (scsi)
Disk /dev/sdk: 1000GB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags: 

Number  Start   End     Size    File system  Name  Flags
 1      1049kB  1000GB  1000GB               zfs
 9      1000GB  1000GB  8389kB</pre>

The special block device doesn't have this partitioning.

**Comment by behlendorf** [comment]
@abuschmann if the arxcis device doesn't support partitions that could cause a problem like your seeing.  As you noticed by default ZFS wants to create an EFI partition table on the device.  You could try manually partitioning the device and creating a DOS-type partition table and then using that for the log device.

**Comment by abuschmann** [comment]
I can and have put GPT partitions on the arxcis device. It didn't help.
Currently I am fighting `udevadm` to create symlinks to the partitions in `/dev/disk/by-id/`.
`/dev/arxcis_b0p1` and `/dev/arxcis_b0p9` are there.
...
I got a config file for udevadm which gives me `/dev/disk/by-id/arxcis_b0-part1` and `/dev/disk/by-id/arxcis_b0-part9` . It doesn't help.
...
I tried to use a partition: `arxcis_b0p1` instead of the whole disk. It doesn't help.
...
I tried to use a DOS-type partition table on `arxcis_b0` and used `arxcis_b0p1` from that. It doesn't help.

Is there a debug or info switch to the zfs subsystem?

**Comment by abuschmann** [comment]
The arxcis block device can be used as a tape with tar, but it does not work as a block device for ext3.
I wrote a bug report to arxcis in August 2015, but did not yet get an answer.

Unsolved but the problem is with the arxcis driver.
Do you want to close this issue?

**Comment by behlendorf** [comment]
@abuschmann thanks for following up with us.  Yes, if this was determined to be an issue with the driver there's not really much we can do.  I've closed the issue.
