### ISSUE TITLE
[Linux Kernel, GPL-only] mm: Change global memory state symbols to GPL-only

### ISSUE THREAD

**Issue by kernelOfTruth** [zfsonlinux/zfs#3692]
Could the following change be of concern (in case spl or some part of zfs rely on it) ?

http://marc.info/?l=linux-kernel&m=143968216905052&w=2

```
Proprietary modules should not be able to touch vm_stat or participate
in shrinking.
```

**Comment by behlendorf** [comment]
Thanks for pointing me to this thread.  Yes this potentially of major concern to us.  We've been trying to shift away from the shrinker anyway but this may speed that up.

**Comment by sempervictus** [comment]
Seems an unnecessary spoke in the wheel of anyone writing kernel code/drivers. Wonder what the motivation for this is.

@behlendorf: How _do_ you implement a separate memory reclamation scheme anyway?

**Comment by behlendorf** [comment]
@sempervictus for a filesystem the right way has always been to rely on notifications through the page cache.

**Comment by ryao** [comment]
Thanks for telling us about this. We should complain on the list now to prevent this from making it in the next release.

**Comment by behlendorf** [comment]
Closing.  It turns out this wasn't an issue.
