### ISSUE TITLE
After disk change old disk stayed in zpool and replacing-0

### ISSUE THREAD

**Issue by mrqwer88** [zfsonlinux/zfs#3698]
Hello!

On storage Centos 6 and zfs-0.6.4.2-1.el6.x86_64
```
uname -r
2.6.32-504.16.2.el6.x86_64
```
```
zfs get version data
NAME  PROPERTY  VALUE    SOURCE
data  version   5        -
```

After disk change we start replase as usual - 
```
zploop replace data old_disk new_disk
```

But after resilvered it degraded yet - 
```
zpool status
  pool: data
 state: DEGRADED
status: One or more devices has experienced an error resulting in data
	corruption.  Applications may be affected.
action: Restore the file in question if possible.  Otherwise restore the
	entire pool from backup.
   see: http://zfsonlinux.org/msg/ZFS-8000-8A
  scan: resilvered 1,19T in 12h36m with 63 errors on Sun Aug 16 18:45:29 2015
config:

	NAME                                          STATE     READ WRITE CKSUM

...
	  mirror-9                                    DEGRADED     0     0   132
	    replacing-0                               DEGRADED   132     0     0
	      scsi-3600605b009beb5d01c8f52ab129bbd43  OFFLINE      0     0     0
	      scsi-3600605b009beb5d01d5af438564a3ce8  ONLINE       0     0   132
	    scsi-3600605b009beb5d01c8f52ad12b4aed2    ONLINE       0     0   132

```
(old disk scsi-3600605b009beb5d01c8f52ab129bbd43 was unavail at first - in offline I set it manual, when try delete it after resivered ended).

I try scrub it, clean and export/import pool, but without any good effect.

Have you any ideas how I can fix this pool?
thanks in advance

**Comment by dasjoe** [comment]
The replaced disks can get stuck sometimes, yes.
`zpool detach data scsi-3600605b009beb5d01c8f52ab129bbd43` should work.

**Comment by mrqwer88** [comment]
Yes - zpool detach work.
Now it look good - 
```
  pool: data
 state: ONLINE
...
	  mirror-9                                  ONLINE       0     0   132
	    scsi-3600605b009beb5d01d5af438564a3ce8  ONLINE       0     0   132
	    scsi-3600605b009beb5d01c8f52ad12b4aed2  ONLINE       0     0   132
``

We had two disks with manufacturing defects on this storage.
Both after work about few days - month suddenly go down and after few hours they go up with clean smart - like it work only 8 hours.
When it go down block device and logical r0 with this disk in raid controller exist and try work.
And it have some write errors, befor it marked like broken.
In dmesg it looks like
```
sd 1:2:19:0: [sdt]  Result: hostbyte=DID_BAD_TARGET driverbyte=DRIVER_OK
sd 1:2:19:0: [sdt] CDB: Read(16): 88 00 00 00 00 01 27 23 af b0 00 00 01 00 00 00
__ratelimit: 53 callbacks suppressed
end_request: I/O error, dev sdt, sector 4951617456
sd 1:2:19:0: [sdt]  Result: hostbyte=DID_BAD_TARGET driverbyte=DRIVER_OK
sd 1:2:19:0: [sdt] CDB: Read(16): 88 00 00 00 00 01 27 23 b0 b0 00 00 01 00 00 00
end_request: I/O error, dev sdt, sector 4951617712
sd 1:2:19:0: [sdt]  Result: hostbyte=DID_BAD_TARGET driverbyte=DRIVER_OK
sd 1:2:19:0: [sdt] CDB: Read(16): 88 00 00 00 00 01 27 23 b1 b0 00 00 01 00 00 00
end_request: I/O error, dev sdt, sector 4951617968
sd 1:2:19:0: [sdt]  Result: hostbyte=DID_BAD_TARGET driverbyte=DRIVER_OK
sd 1:2:19:0: [sdt] CDB: Read(16): 88 00 00 00 00 01 24 31 cb f8 00 00 00 10 00 00
end_request: I/O error, dev sdt, sector 4902210552
sd 1:2:19:0: [sdt]  Result: hostbyte=DID_BAD_TARGET driverbyte=DRIVER_OK
sd 1:2:19:0: [sdt] CDB: Write(16): 8a 00 00 00 00 01 10 a4 95 b8 00 00 01 00 00 00
end_request: I/O error, dev sdt, sector 4574188984
sd 1:2:19:0: [sdt]  Result: hostbyte=DID_BAD_TARGET driverbyte=DRIVER_OK
sd 1:2:19:0: [sdt] CDB: Read(16): 88 00 00 00 00 01 27 23 e0 b0 00 00 01 00 00 00
end_request: I/O error, dev sdt, sector 4951630000
sd 1:2:19:0: [sdt]  Result: hostbyte=DID_BAD_TARGET driverbyte=DRIVER_OK
sd 1:2:19:0: [sdt] CDB: Read(10): 28 00 00 00 0a 10 00 00 10 00
end_request: I/O error, dev sdt, sector 2576
sd 1:2:19:0: [sdt]  Result: hostbyte=DID_BAD_TARGET driverbyte=DRIVER_OK
sd 1:2:19:0: [sdt] CDB: Read(16): 88 00 00 00 00 02 ba 8f b4 10 00 00 00 10 00 00
end_request: I/O error, dev sdt, sector 11719914512
sd 1:2:19:0: [sdt]  Result: hostbyte=DID_BAD_TARGET driverbyte=DRIVER_OK
sd 1:2:19:0: [sdt] CDB: Read(16): 88 00 00 00 00 02 ba 8f b6 10 00 00 00 10 00 00
end_request: I/O error, dev sdt, sector 11719915024
sd 1:2:19:0: [sdt]  Result: hostbyte=DID_BAD_TARGET driverbyte=DRIVER_OK
sd 1:2:19:0: [sdt] CDB: Write(16): 8a 00 00 00 00 01 10 a4 96 b8 00 00 01 00 00 00
end_request: I/O error, dev sdt, sector 4574189240

```

At first we readded then, because it have clean smarts.
Now both replaced to new disks, but it stay in degraded after second disk replacment and I wrote this issue.

Thanks for help!

**Comment by behlendorf** [comment]
Closing.  This looks like a matter of just documenting the behavior.  Glad you managed to sort it out!
