### ISSUE TITLE
Mountall Fails to unlock zfs cache device

### ISSUE THREAD

**Issue by rjonasz** [zfsonlinux/zfs#3706]
During boot mountall can unlock zfs drives except for cache drives.  This was detected using Ubuntu 14.04 with 3 SAS drives forming root pool in raidz, 2 log SSD drives in mirror, and one SSD cache drive.  They are all encrypted with luks using cryptsetup.  5 of the 6 drives unlock.  The cache can be unlocked after boot and added to the pool.

**Comment by gmelikov** [comment]
Close as stale.

If it's actual - feel free to reopen.
