### ISSUE TITLE
bulid 0.6.4.2  in debian 7.8  arch :i386,  when system reboot  I lose the data set and pool

### ISSUE THREAD

**Issue by lihui2090** [zfsonlinux/zfs#3711]
I  use  the zfs-0.6.4.2  and spl-0.6.4.2 to bulid in debian 7.8.
the kernel is  :Linux debian 3.2.0-4-686-pae #1 SMP Debian 3.2.68-1+deb7u3 i686 GNU/Linux
use kmod way to bulid 
I create pool and dataset, but when i reboot the system ,the pool and dataset is losed.
Am i lose init config step or?
thanks very much .

another quesion is :
when i create pool,
zpool create newpool  raidz /dev/sdb /dev/sdc
invalid vdev specification
use '-f' to override the following errors:
I  need  -f to create .

root@debian:/newpool/zdev1# mount
newpool on /newpool type zfs (rw,relatime,xattr,noacl)
newpool/zdev1 on /newpool/zdev1 type zfs (rw,relatime,xattr,noacl)

after reboot 
root@debian:/home/miniadmin# lsmod |grep spl
spl                    47986  3 znvpair,zcommon,zfs
zlib_deflate           21318  1 spl
root@debian:/home/miniadmin# lsmod |grep zfs
zfs                  1606493  0 
zunicode              324248  1 zfs
zavl                   12870  1 zfs
zcommon                31236  1 zfs
znvpair                40533  2 zcommon,zfs
spl                    47986  3 znvpair,zcommon,zfs

root@debian:/home/miniadmin# zfs list
no datasets available

**Comment by fling-** [comment]
What does `zpool import` say?

**Comment by lihui2090** [comment]
I have get it ,thank you vevry much!
root@debian:/home/miniadmin# zpool import
   pool: newpool
     id: 9731241069697300937
  state: ONLINE
 action: The pool can be imported using its name or numeric identifier.
 config:

        newpool     ONLINE
          raidz1-0  ONLINE
            sdb     ONLINE
            sdc     ONLINE


root@debian:/home/miniadmin# zpool import newpool
root@debian:/home/miniadmin# zfs list
NAME           USED  AVAIL  REFER  MOUNTPOINT
newpool        677M  18.9G    19K  /newpool
newpool/zdev   677M  18.9G   677M  /newpool/zdev

**Comment by fling-** [comment]
Don't use raidz1 with two disks. Add more disks or use mirror instead.

**Comment by DeHackEd** [comment]
Also note that 32 bit ZFS on Linux is not very well supported. You WILL see problems relating to memory management. Please upgrade your system to 64 bits if possible.

**Comment by lihui2090** [comment]
I will test the mirror way ths very much .


I have use zfs in 64 bit system, but the company have a product is 32bit.  
IFthe 32 bit zfs can run stabel long time?
ths very much.

**Comment by fling-** [comment]
You could use multilib and/or 32 bit lxc container.

**Comment by lihui2090** [comment]
ths ,first
the  zoopl should auto import the pools,but i system can't,
can fling give me a advice,ths.

**Comment by lihui2090** [comment]
In /etc/init.d/  have zfs 
service zfs start 
the pool will imported and mounted 
ths fling .

**Comment by ronnyegner** [comment]
64 bit Linux supports 32 bit applications. That said you can run yozr 64bit linux with ZFS and your 32bit application at the same time.

**Comment by kernelOfTruth** [comment]
@lihui2090 try the chroot approach if the compatibility libs aren't sufficient

https://wiki.debian.org/DebianAMD64Faq
http://swinky-linuxblog.blogspot.co.at/2008/12/using-32-bit-applications-in-64-bit.html
https://web.archive.org/web/20100918121337/http://alioth.debian.org/docman/view.php/30192/21/debian-amd64-howto.html

https://wiki.ubuntu.com/DebootstrapChroot

with a 64bit kernel you should run into less issues with ZFS

**Comment by FransUrbo** [comment]
> with a 64bit kernel you should run into less issues with ZFS
> 
Do note that running a mixed system (64bit kernel, 32bit userland) can give very, very strange results and errors, not easily found or detected.

I ran like that for almost a year, and I had a lot of trouble that I couldn't quite pinpoint.

I even lost my whole pool once. Still don't know the exact cause, I was running the crypto patch as well. But running a mixed system probably had at least SOMETHING to do with it...

**Comment by ronnyegner** [comment]
@FransUrbo you could put the 32 bit into a VM running a 32 bit Linux....

**Comment by FransUrbo** [comment]
> @FransUrbo you could put the 32 bit into a VM running a 32 bit Linux….
> 
What good would that do?! The whole point is that you need a 64bit kernel!

With that comes that you really need to run 64bit userland as well, because a mixed environment isn't really working properly.

Hence, if we continue that line of thought, you need a fully enabled 64bit environment, through and through… Which have been the whole point of this "exercise".


ANY part of the environment being 32bit isn't really supported. It can work, some people have gotten it to work, but it's a mess and from what it seems a "toss up".

If you really need ZFS and you're _forced_ to run 32bit, go with zfs-fuse. It's old, it doesn't have much regarding functionality and it's not maintained any more. But it's stable (albeit slow as f**k!) and works correctly on 32bit.

**Comment by ronnyegner** [comment]
@FransUrbo I understood that the poster needed a 32 bit for his application but for ZFS 64bit is a must-have. So my advise above was to run a 64bit Linux system with ZFS and then run a virtual machine with a 32bit os on the 64bit system. That way he gets the best of both worlds: ZFS on the host and is still able to run his 32bit app in a complete 32 bit environment.

**Comment by lihui2090** [comment]
Tks every body!
I will test the zfs  32, for know zfs details status in 32 systems  .

**Comment by lihui2090** [comment]
i find the zfs-fuse not supporte acl .

**Comment by ronnyegner** [comment]
@lihui2090  Yes, that´s because the ZFS-FUSE port is no longer maintained (to my knowledge). Why don´t you try the approach i mentioned? You install a 64bit operating system, configure your ZFS pool and then install Virtualbox (or VMWARE) and run a virtual machine with 32 bit linux. In the virtual machine you can then run your application in a pure 32bit environment while you profit from the benefits of having ZFS on the host.

**Comment by lihui2090** [comment]
because the hard ware is 32bit and  the performance is not very high  .

**Comment by lihui2090** [comment]
@ronnyegner 
Because the hard ware is 32bit and the performance is not very high .

**Comment by ronnyegner** [comment]
@lihui2090  then maybe ZFS is not the right choice for the platform?

**Comment by lihui2090** [comment]
@ronnyegner if i use the zfs in 32bit ,the system will to run err or not?

**Comment by ronnyegner** [comment]
@lihui2090 Try it. Nobody can say this for sure. But there are issues with 32 bit systems due to the memory architecture and the limits inheritent to the 32 bit architecture. But maybe it will work for you....

**Comment by lihui2090** [comment]
ok,i wiil try .

**Comment by lihui2090** [comment]
I find a  question in test .
when i  transfer many files to server ,the spl_kmem_cache hold the cpu .
![zfstest](https://cloud.githubusercontent.com/assets/13795209/9923469/e51adfe6-5d27-11e5-8a53-cdc6d8df8d63.png)

**Comment by lihui2090** [comment]
@behlendorf 
when i test i find a  questiion    spl_kmem_cache hold the cpu,reboot not resolved.
 1193 root      39  19     0    0    0 S  53.8  0.0   3:49.91 spl_kmem_cache/                                                                                                                                                                                                 
 1191 root      39  19     0    0    0 S  51.8  0.0   3:54.29 spl_kmem_cache/                                                                                                                                                                                                 
 1190 root      39  19     0    0    0 S  50.2  0.0   3:52.29 spl_kmem_cache/                                                                                                                                                                                                 
 1192 root      39  19     0    0    0 S  49.9  0.0   3:52.45 spl_kmem_cache/                                                                                                                                                                                                 
 4658 root      20   0     0    0    0 Z  31.8  0.0   7:11.74 python                                                                                                                                                                                                          
 3155 root      39  19     0    0    0 D  24.6  0.0   1:53.41 z_wr_int/14                                                                                                                                                                                                     
 3141 root      39  19     0    0    0 D  24.0  0.0   1:53.58 z_wr_int/0                                                                                                                                                                                                      
 8878 root      20   0  5172 1444  976 R   1.0  0.1   0:01.70 top                                                                                                                                                                                                             
 1406 root      20   0     0    0    0 S   0.3  0.0   0:00.02 flush-179:0                                                                                                                                                                                                     
    1 root      20   0  3188  912  772 S   0.0  0.1   0:02.62 init                                                                                                                                                                                                            
    2 root      20   0     0    0    0 S   0.0  0.0   0:00.00 kthreadd                                                                                                                                                                                                        
    3 root      20   0     0    0    0 S   0.0  0.0   0:00.00 ksoftirqd/0                                                                                                                                                                                                     
    4 root      20   0     0    0    0 S   0.0  0.0   0:00.16 kworker/0:0                                                                                                                                                                                                     
    6 root      rt   0     0    0    0 S   0.0  0.0   0:00.00 migration/0                                                                                                                                                                                                     
    7 root      rt   0     0    0    0 S   0.0  0.0   0:00.00 migration/1                                                                                                                                                                                                     
    8 root      20   0     0    0    0 S   0.0  0.0   0:00.00 kworker/1:0                                                                                                                                                                                                     
    9 root      20   0     0    0    0 S   0.0  0.0   0:00.00 ksoftirqd/1                                                                                                                                                                                                     
   10 root      20   0     0    0    0 S   0.0  0.0   0:00.00 kworker/0:1                                                                                                                                                                                                     
   11 root      rt   0     0    0    0 S   0.0  0.0   0:00.00 migration/2                                                                                                                                                                                                     
   12 root      20   0     0    0    0 S   0.0  0.0   0:00.00 kworker/2:0                                                                                                                                                                                                     
   13 root      20   0     0    0    0 S   0.0  0.0   0:00.00 ksoftirqd/2                                                                                                                                                                                                     
   14 root      rt   0     0    0    0 S   0.0  0.0   0:00.00 migration/3                                                                                                                                                                                                     
   15 root      20   0     0    0    0 S   0.0  0.0   0:00.00 kworker/3:0                                                                                                                                                                                                     
   16 root      20   0     0    0    0 S   0.0  0.0   0:00.00 ksoftirqd/3                                                                                                                                                                                                     
   17 root       0 -20     0    0    0 S   0.0  0.0   0:00.00 cpuset                                                                                                                                                                                                          
   18 root       0 -20     0    0    0 S   0.0  0.0   0:00.00 khelper                                                                                                                                                                                                         
   19 root      20   0     0    0    0 S   0.0  0.0   0:00.00 kworker/u:1                                                                                                                                                                                                     
  201 root      20   0     0    0    0 S   0.0  0.0   0:00.00 sync_supers                                                                                                                                                                                                     
  203 root      20   0     0    0    0 S   0.0  0.0   0:00.00 bdi-default                                                                                                                                                                                                     
  204 root       0 -20     0    0    0 S   0.0  0.0   0:00.00 kintegrityd                                                                                                                                                                                                     
  206 root       0 -20     0    0    0 S   0.0  0.0   0:00.00 kblockd                                                                                                                                                                                                         
  318 root       0 -20     0    0    0 S   0.0  0.0   0:00.00 ata_sff                                                                                                                                                                                                         
  329 root      20   0     0    0    0 S   0.0  0.0   0:00.00 khubd                                                                                                                                                                                                           
  337 root       0 -20     0    0    0 S   0.0  0.0   0:00.00 md                                                                                                                                                                                                              
  434 root       0 -20     0    0    0 S   0.0  0.0   0:00.00 rpciod                                                                                                                                                                                                          
  477 root      20   0     0    0    0 S   0.0  0.0   0:00.00 kswapd0                                                                                                                                                                                                         
  538 root      20   0     0    0    0 S   0.0  0.0   0:00.00 fsnotify_mark                                                                                                                                                                                                   
  558 root       0 -20     0    0    0 S   0.0  0.0   0:00.00 nfsiod                                                                                                                                                                                                          
  567 root       0 -20     0    0    0 S   0.0  0.0   0:00.00 crypto                                                                                                                                                                                                          
  581 root       0 -20     0    0    0 S   0.0  0.0   0:00.00 kthrotld                                                                                                                                                                                                        
  667 root      20   0     0    0    0 S   0.0  0.0   0:00.06 scsi_eh_0

**Comment by lihui2090** [comment]
when i test i find a questiion spl_kmem_cache hold the cpu,reboot not resolved.

Tasks: 242 total, 1 running, 240 sleeping, 0 stopped, 1 zombie
%Cpu(s): 0.1 us, 68.1 sy, 0.0 ni, 15.4 id, 16.4 wa, 0.0 hi, 0.0 si, 0.0 st
KiB Mem: 1812048 total, 321688 used, 1490360 free, 29220 buffers
KiB Swap: 0 total, 0 used, 0 free, 113604 cached

1193 root 39 19 0 0 0 S 53.8 0.0 3:49.91 spl_kmem_cache/
1191 root 39 19 0 0 0 S 51.8 0.0 3:54.29 spl_kmem_cache/
1190 root 39 19 0 0 0 S 50.2 0.0 3:52.29 spl_kmem_cache/
1192 root 39 19 0 0 0 S 49.9 0.0 3:52.45 spl_kmem_cache/

**Comment by lihui2090** [comment]
vmalloc =512M reslove the  spl_kmem_cache hold
but the 32 linux can't use disk biger than 2t,so have become the system to 64 ,ths every body

**Comment by loli10K** [comment]
> so have become the system to 64 ,ths every body

Closing as stale and (supposedly) resolved.
