### ISSUE TITLE
no space left for all zfs filesystems

### ISSUE THREAD

**Issue by bjin** [zfsonlinux/zfs#3724]
I probably did something wrong, or missed something. But today when I was trying to compile and run zfs from git master, it succeed to import but is totally unusable. Available space become zero for all zfs filesystems and I can't even create or rename a file. The whole filesystem is kind of fronzen so I didn't get any other useful information from log files. Is this expected or a known issue? 

My pool was created with 0.6.4 so there are two features flag not enabled. And it's compiled from `278bee9` for zfs and `801b560` for spl. If it's only a few steps, I think I can try to do a bisect tomorrow, if that's helpful.

FWIW, it's the first time I try to compile and run zfs since the release of `0.6.4`.

**Comment by DeHackEd** [comment]
The reserved space was increased during a recent patch. If you were very close to full before (97 or 98+%) it'll read as 100% now.

I would suggest either reverting for now or destroying some snapshots to free up space. Your target is about 3% of the whole pool size.

**Comment by bjin** [comment]
I suppose it's unlikely the cause. The usage is less than 30% for the pool. However, I did do daily snapshots so it's like hundreds of them.

**Comment by bjin** [comment]
Ooops, I realized that I made a mistake here. My pool is indeed near full now, and deleting snapshots did help. Thanks.

**Comment by bjin** [comment]
Just for reference purpose, what's the commit that increased the reserved space? Is there anyone to disable that?

**Comment by bjin** [comment]
Reopen this issue, since there might cases that it's not possible to delete any files or snapshots to free up spaces.

**Comment by bjin** [comment]
@DeHackEd @behlendorf Could you tell which commit caused this? What will be very helpful.

**Comment by bjin** [comment]
Okay, I figured it out, it's https://github.com/zfsonlinux/zfs/commit/3d45fdd6c0d5b4c8e42b6a2cda00bf6f22c9f2bf .

Is there any reason that reserved space changed from 1/64 to 1/32? It actually brought breakage.

**Comment by behlendorf** [comment]
@bjin yes we absolutely can.  Thanks for reminding me about this, I meant to post a patch which exposes this as a module option.  See pull request #3727.
