### ISSUE TITLE
Can't set Kerberos options with sharenfs

### ISSUE THREAD

**Issue by ikogan** [zfsonlinux/zfs#3738]
I can't seem to set Kerberos options either the Solaris or the Linux way when exporting via `zfs set sharenfs`.

So far I've tried:

`zfs set sharenfs=rw=@10.1.42.0/24,no_subtree_check,insecure,root_squash,nohide,sec=krb5:krb5i:krb5p Data/Shared`

`zfs set sharenfs=sec=krb5p:krb5i:krb5,rw=@10.1.42.0/24,no_subtree_check,insecure,root_squash.nohide`

No matter what, the output of `exportfs -v` looks like:

```
root@ezra:~# exportfs -v
/data/Shared    10.1.42.0/24(ro,wdelay,root_squash,no_subtree_check)
```

I do notice that `/etc/dfs/sharetab` looks reasonable:

```
/data/Shared    -   nfs rw=@10.1.42.0/24,no_subtree_check,insecure,root_squash,nohide,sec=krb5:krb5p:krb5i
```

Here's some system info:

```
root@ezra:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.8 (wheezy)
Release:        7.8
Codename:       wheezy
root@ezra:~# lsb_release -a && uname -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.8 (wheezy)
Release:        7.8
Codename:       wheezy
Linux ezra 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u3 x86_64 GNU/Linux
root@ezra:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.8 (wheezy)
Release:        7.8
Codename:       wheezy
root@ezra:~# uname -a
Linux ezra 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u3 x86_64 GNU/Linux
root@ezra:~# zfs list
NAME                USED  AVAIL  REFER  MOUNTPOINT
Data               3.82T  1.46T  43.8G  /data
Data/Backups       13.0G  1.46T  13.0G  /data/Backups
Data/Homes          948G  1.46T   270K  /data/Homes
Data/Homes/user1    234M  1.46T   234M  /data/Homes/user1
Data/Homes/user2   7.87G  1.46T  7.87G  /data/Homes/user2
Data/Stuff          749G  1.46T   749G  /data/Stuff
Data/Shared        2.10T  1.46T  2.10T  /data/Shared
Data/Websites       170K  1.46T   170K  /data/Websites
root@ezra:~# apt-show-versions zfsutils
zfsutils/wheezy uptodate 0.6.4-1.2-1-wheezy
root@ezra:~# apt-show-versions nfs-kernel-server
nfs-kernel-server/wheezy uptodate 1:1.2.6-4
```

Kerberos does work correctly when using exports, here's what my `/etc/exports` file looks like:

```
# /etc/exports: the access control list for filesystems which may be exported
#               to NFS clients.  See exports.
/export/Shared 10.1.42.0/24(rw,no_subtree_check,insecure,nohide,fsid=227b43b3-6fcb-46f3-a7e1-9edb7b739aab,sec=krb5:krb5p:krb5i)
/export/Homes 10.1.42.0/24(rw,no_subtree_check,insecure,nohide,fsid=14cde529-7a7f-4da9-aac0-4a45cf5c6107,sec=krb5:krb5p:krb5i)

# NFSv4 - pseudo filesystem root
/export 10.1.42.0/24(ro,fsid=0,root_squash,no_subtree_check,hide,sec=krb5:krb5p:krb5i)
```

When I strace with `strace -s 1024 -f  -v zfs share -a` I get some interesting output:

```
...
[pid 27841] execve("/usr/sbin/exportfs", ["/usr/sbin/exportfs", "-i", "-o", "rw,no_subtree_check,insecure,root_squash,nohide,sec", "*:/data/Shared"]
...
```

So it looks like that additional equals sign is throwing off the options parsing a bit. I'll attempt to dig into this a bit more once I figure out why this isn't building but was wondering if there's a workaround.

Also, when I try to setup the share the Solaris way, I get the following in strace:

```
...
[pid  3000] execve("/usr/sbin/exportfs", ["/usr/sbin/exportfs", "-i", "-o", "rw,no_subtree_check,insecure,root_squash,nohide", "10.1.42.0/24:/data/Shared"]
...
```

**Comment by ikogan** [comment]
So, interestingly, if I build from https://github.com/zfsonlinux/zfs/commit/7065e2dac61ceef58df62280185162c0a00e2d30, then this works fine.

**Comment by FransUrbo** [comment]
> I can't seem to set Kerberos options either the Solaris or the Linux way when exporting via zfs set sharenfs.
> 

From the strace, I gather that you're running with the sharenfs that comes in ZFS released and/or GIT?

That one is extremely limiting and I rewrote it shortly after it was accepted to use registry shares instead of user shares (which only have four, five options possible). With registry shares, you can give ANY option that's available in smb.conf.

However, @behlendorf prefers to wait "a couple of years" to have ZED do all sharing instead of looking at or accepting any commits that have to do with the share* options.

I've rewritten both the sharenfs and sharesmb (which I was the original author of) almost completely, as well as a shareiscsi. None is of any interest...

**Comment by ikogan** [comment]
I am indeed, my issue, though, is that I'm trying to give each user their own file system so that they have control over snapshots and what not.

When I use the `/etc/exports` file above, the contents of the individual directories are hidden as they're each on a different file system. I had assume that, since filesystems inherit flags, using sharenfs on `/data/Homes` would cause zfs to export all of the child filesystems as well and, with `nohide`, this would realize the behavior I'm looking for without having to manually add each user's home directory to `/etc/exports`. Is there a better way to do this?

**Comment by ikogan** [comment]
After setting everything up it does work as I expect with the version I've built from source. My next question is, will 0.6.4.2 be available in the Wheezy repo for ZoL? It doesn't seem to be at the moment.

**Comment by FransUrbo** [comment]
It is, it's just called <code>0.6.4-1.2-1-wheezy</code>.

**Comment by ikogan** [comment]
Ah, that seems to be the version I have. I just built 44b5ec8fd19d0ff3f258ee000ac404f01cd97835 from source, which I imagine is what that version was built from and it also works fine. Why then does the one installed by the package not work fine?

**Comment by FransUrbo** [comment]
Oh, right! I've added that extra NFS patch to my packages. Totally forgot.

I'll have a look as to why it didn't work. I've accidentally read it as you had a problem with shareSMB not, shareNFS.

**Comment by FransUrbo** [comment]
Ok, I've pushed a new version of the pull request. @ikogan, I'd appreciate immensely if you could build a version with this and test it to make sure.

**Comment by ikogan** [comment]
```  CC [M]  /home/kogan/Documents/Code/zfs-sharenfs-fix/module/zfs/arc.o
/home/kogan/Documents/Code/zfs-sharenfs-fix/module/zfs/arc.c: In function ‘arc_change_state’:
/home/kogan/Documents/Code/zfs-sharenfs-fix/module/zfs/arc.c:1631:4: error: implicit declaration of function ‘IMPLY’ [-Werror=implicit-function-declaration]
/home/kogan/Documents/Code/zfs-sharenfs-fix/module/zfs/arc.c: In function ‘arc_prune’:
/home/kogan/Documents/Code/zfs-sharenfs-fix/module/zfs/arc.c:2752:2: error: implicit declaration of function ‘taskq_wait_outstanding’ [-Werror=implicit-function-declaration]
/home/kogan/Documents/Code/zfs-sharenfs-fix/module/zfs/arc.c: In function ‘arc_kmem_reap_now’:
/home/kogan/Documents/Code/zfs-sharenfs-fix/module/zfs/arc.c:3411:3: error: implicit declaration of function ‘vmem_qcache_reap’ [-Werror=implicit-function-declaration]
/home/kogan/Documents/Code/zfs-sharenfs-fix/module/zfs/arc.c: In function ‘arc_reclaim_thread’:
/home/kogan/Documents/Code/zfs-sharenfs-fix/module/zfs/arc.c:3511:4: error: implicit declaration of function ‘cv_timedwait_sig’ [-Werror=implicit-function-declaration]
/home/kogan/Documents/Code/zfs-sharenfs-fix/module/zfs/arc.c: In function ‘arc_init’:
/home/kogan/Documents/Code/zfs-sharenfs-fix/module/zfs/arc.c:5381:36: error: ‘boot_ncpus’ undeclared (first use in this function)
/home/kogan/Documents/Code/zfs-sharenfs-fix/module/zfs/arc.c:5381:36: note: each undeclared identifier is reported only once for each function it appears in
/home/kogan/Documents/Code/zfs-sharenfs-fix/module/zfs/arc.c:5462:57: error: ‘defclsyspri’ undeclared (first use in this function)
/home/kogan/Documents/Code/zfs-sharenfs-fix/module/zfs/arc.c: In function ‘l2arc_start’:
/home/kogan/Documents/Code/zfs-sharenfs-fix/module/zfs/arc.c:6984:9: error: ‘defclsyspri’ undeclared (first use in this function)
cc1: some warnings being treated as errors
make[7]: *** [/home/kogan/Documents/Code/zfs-sharenfs-fix/module/zfs/arc.o] Error 1
make[6]: *** [/home/kogan/Documents/Code/zfs-sharenfs-fix/module/zfs] Error 2
make[5]: *** [_module_/home/kogan/Documents/Code/zfs-sharenfs-fix/module] Error 2
make[4]: *** [sub-make] Error 2
make[3]: *** [all] Error 2
make[3]: Leaving directory `/usr/src/linux-headers-3.2.0-4-amd64'
make[2]: *** [modules] Error 2
make[2]: Leaving directory `/data/Homes/kogan/Documents/Code/zfs-sharenfs-fix/module'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/data/Homes/kogan/Documents/Code/zfs-sharenfs-fix'
```

Perhaps my Kernel headers aren't sufficient? https://github.com/zfsonlinux/zfs/commit/44b5ec8fd19d0ff3f258ee000ac404f01cd97835 and https://github.com/zfsonlinux/zfs/commit/7065e2dac61ceef58df62280185162c0a00e2d30 seem to work fine.

**Comment by FransUrbo** [comment]
Right! You where using the released version… The PR is including the latest master, which also needs a new SPL…

If you cherry-pick the commits in the PR, it might work better.

```
git clone https://github.com/zfsonlinux/zfs.git zfs-sharenfs-fix
cd zfs-sharenfs-fix
git checkout -b zfs-0.6.4.2 zfs-0.6.4.2
git remote add turbo https://github.com/FransUrbo/zfs.git
git fetch turbo
git cherry-pick bcdd954b21e1fbd3a1b30e1be5d36fa756048d3b
git cherry-pick 08f8958d650f9ee25e7ca4b8cb9d5565d8922e77
./autogen.sh
[etc]
```

**Comment by ikogan** [comment]
That worked, and it looks like it now works, but only with the Linux syntax. The following does not work:

```
root@ezra:/home/kogan/Documents/Code# zfs set sharenfs=sec=krb5:krb5i:krb5p,rw=@10.1.42.0/24,root_squash,no_subtree_check Data/Shared
```

The following does work:

```
 zfs set sharenfs=rw=@10.1.42.0/24,root_squash,no_subtree_check,sec=krb5:krb5p:krb5i Data/Shared
```

**Comment by FransUrbo** [comment]
> That worked, and it looks like it now works, but only with the Linux syntax. The following does not work:
> 
> root@ezra:/home/kogan/Documents/Code# zfs set sharenfs=sec=krb5:krb5i:krb5p,rw=@10.1.42.0/24,root_squash,no_subtree_check Data/Shared
Ah, yes :(.

Since @behlendorf have no real interest in the pull request, that he thinks that the Solaris syntax should be removed (which I don't really object to technically - I don't have a need for it) I had to "cut some corners" to get it to work.

THAT MEANS that unfortunately one now _HAVE_ to start with a "rw[=@xxx]" _OR_ a "ro[=@xxx]" to make sure that anything after that _and up to the next rw/ro statement (if any)_ is for ONE/THAT host/network setting…

I might be able to tweak it, but I don't see the point at the moment… 


Does it matter a lot to you?

**Comment by ikogan** [comment]
It doesn't matter to me at all, so long as one of the two works. I was just pointing it out to be thorough. I think it makes sense for the Linux usage to work on Linux though I understand the usefulness of being able to move a filesystem to Solaris or BSD and have properties that continue to work.

On the other hand, it seems a little scary that my filesystem will automatically start sharing itself on the network again after I've done something as extreme as moving it to a different box. Anyway, this works great. Thanks very much for looking at it and fixing things!

**Comment by FransUrbo** [comment]
@ikogan Ok, since we can consider this fixed and that it isn't really a problem with "zfs" (this repo - it should have been moved to https://github.com/zfsonlinux/pkg-zfs but I forgot), can you please close this issue?

**Comment by FransUrbo** [comment]
@ikogan _IF_ @behlendorf decide to act on the PR, I'm sure we can work something out on your notes on it (I have marked them as TODO in the source). But we'll do that in the PR, not here...

**Comment by ikogan** [comment]
For the moment I've decided to handle this by augmenting OpenMediaVault's ZFS support (https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-zfs/pull/1) so I don't yet have to rely on `sharenfs`. When there's a clearer direction on this, I'll update the plugin to do whatever the best practice ends up being.

Thanks again for all of your help!
