### ISSUE TITLE
Illumos #3190, zfs incremental: cannot receive incremental stream:destination ... has been modified since most recent snapshot - subdirectories suddenly (?) containing data on backup device

### ISSUE THREAD

**Issue by kernelOfTruth** [zfsonlinux/zfs#3742]
Just hit the referenced BUG:

https://www.illumos.org/issues/3190

I've had 3 snapshots on the backup

31.08
01.09
02.09

when trying to send a newer snapshot to the backup device (03.09 and 04.09)

zfs send bailed out with

```
cannot receive incremental stream: destination ... has been modified
since most recent snapshot
warning: cannot send ... : Broken pipe
```

well, yes - but there has been ZERO changes on the master

I've no idea where the changes on the backup appeared from :-1: 

tried rolling back recursively but the changes are STILL there

**Comment by kernelOfTruth** [comment]
well, I rolled back that single mentioned directory manually and it continued

but now suddenly lots of other subdirectories from /home (on the destination) contain additional data :confused: 

@behlendorf  @ahrens related to snapshot handling: is there any progress on support for resuming interrupted zfs sends ?

the pre-requisite is there (Illumos 5746)

**Comment by kernelOfTruth** [comment]
_could_ be user error or false assumption on how send and receive work

investigating ...

**Comment by siebenmann** [comment]
If the destination filesystem is mounted, there is at least one ZFS feature that can cause immediate divergence between snapshots and the mounted filesystem: ZFS delete queues, which are used to handle the case of when a currently open file has been deleted. The snapshot captures the current state of the filesystem's delete queue, the send | receive transfers it, and then on the destination ZFS sees a non-empty delete queue with nothing actually using those files any more and deletes them, causing the mounted filesystem to diverge from the snapshot.

It is possible to inspect a snapshot's ZFS delete queue and thereby determine if this might be what's happening to your filesystems. A how-to for Illumos is [here](https://utcc.utoronto.ca/~cks/space/blog/solaris/ZFSDeleteQueue) and I believe it should apply to ZoL's version of zdb as well.

As far as I know the only workaround for this is to never mount the destination filesystem.

**Comment by kernelOfTruth** [comment]
@siebenmann thanks for the pointers,

it was a combination of auto-mounting of the snapshots/backup medium and user error,

closing
