### ISSUE TITLE
running "mount -o loop" system hang

### ISSUE THREAD

**Issue by dlan17** [zfsonlinux/zfs#3751]
it's a Gentoo Linux system, using kernel 4.1.6 (sys-kernel/gentoo-sources-4.1.6), zfs-0.6.4.2, zfs-kmod-0.6.4.2, spl-0.6.4.2.

while running: mount -o loop portage-20150827.squashfs /mnt/test, will trigger kernel panic

[   87.743950] general protection fault: 0000 [#1] SMP 
[   87.751424] Modules linked in: nfsd pl2303 usbserial ppdev x86_pkg_temp_thermal dcdbas usb_skeleton coretemp kvm_intel kvm parport_pc pata_acpi xts aes_x86_64 
sha256_genx
[   87.860617] CPU: 1 PID: 2139 Comm: spl_kmem_cache/ Tainted: P           O    4.1.6-gentoo #1
[   87.871921] Hardware name: Dell Inc. OptiPlex 390/0M5DCD, BIOS A11 10/14/2013
[   87.881926] task: ffff880063bfc3d0 ti: ffff880063518000 task.ti: ffff880063518000
[   87.892317] RIP: 0010:[<ffffffff81112557>]  [<ffffffff81112557>] list_del+0xb/0x2f
[   87.902801] RSP: 0018:ffff88006351ba78  EFLAGS: 00010087
[   87.910999] RAX: ffffffff82371d00 RBX: ffffea00018073a0 RCX: ffffffff82371d00
[   87.920996] RDX: 6a5c4d26169234f4 RSI: 0000000000000000 RDI: ffffea00018073a0
[   87.930988] RBP: ffff88006351ba78 R08: 0000000000000000 R09: 0000000000000000
[   87.940983] R10: 000000000000068e R11: 0000000000000002 R12: ffffea0001807380
[   87.950992] R13: 0000000000000000 R14: 0000000000000000 R15: ffffffff82371c40
[   87.960967] FS:  0000000000000000(0000) GS:ffff880079e40000(0000) knlGS:0000000000000000
[   87.971929] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   87.980550] CR2: 00007fffea7d2e28 CR3: 000000000220b000 CR4: 00000000000406e0
[   87.990525] Stack:
[   87.995331]  ffff88006351bac8 ffffffff81112e72 0000000000000000 0000000000000000
[   88.005603]  ffffffff82371d00 ffffffff82371c40 0000000000000000 ffff880079e5b140
[   88.015863]  ffffffff82371c40 0000000000000141 ffff88006351bb48 ffffffff81114e80
[   88.026117] Call Trace:
[   88.031367]  [<ffffffff81112e72>] __rmqueue_smallest+0x6d/0xb4
[   88.040000]  [<ffffffff81114e80>] __rmqueue+0x2d/0x1fd
[   88.047895]  [<ffffffff8111580d>] ? __alloc_pages_nodemask+0x16b/0x6c0
[   88.057164]  [<ffffffff8111522f>] get_page_from_freelist+0x1df/0x57b
[   88.066266]  [<ffffffff8111580d>] __alloc_pages_nodemask+0x16b/0x6c0
[   88.075370]  [<ffffffff81b473fa>] ? _raw_spin_unlock+0xe/0x10
[   88.083835]  [<ffffffff8114c9c0>] ? slab_post_alloc_hook.isra.32+0x11/0x20
[   88.093425]  [<ffffffff8113de31>] __vmalloc_node_range+0x13e/0x1bb
[   88.102317]  [<ffffffff8113dedd>] __vmalloc_node+0x2f/0x31
[   88.110500]  [<ffffffffa03fb666>] ? spl_vmalloc+0x35/0x58 [spl]
[   88.119103]  [<ffffffff8113deff>] __vmalloc+0x20/0x22
[   88.126828]  [<ffffffffa03fb666>] spl_vmalloc+0x35/0x58 [spl]
[   88.135224]  [<ffffffffa03f9d56>] spl_kmem_cache_set_move+0x2d5/0x826 [spl]
[   88.144826]  [<ffffffffa03f9db0>] spl_kmem_cache_set_move+0x32f/0x826 [spl]
[   88.154386]  [<ffffffff810ec76f>] ? trace_hardirqs_off+0x9/0x20
[   88.162923]  [<ffffffffa03fc14f>] taskq_cancel_id+0x2d7/0x4a0 [spl]
[   88.171789]  [<ffffffff810789dc>] ? wake_up_state+0x12/0x12
[   88.179919]  [<ffffffffa03fbf65>] ? taskq_cancel_id+0xed/0x4a0 [spl]
[   88.188840]  [<ffffffff8106eec8>] kthread+0xa5/0xad
[   88.196289]  [<ffffffff81070000>] ? put_cred_rcu+0x59/0xbc
[   88.204331]  [<ffffffff8106ee23>] ? __kthread_parkme+0x61/0x61
[   88.212713]  [<ffffffff81b47d02>] ret_from_fork+0x42/0x70
[   88.220664]  [<ffffffff8106ee23>] ? __kthread_parkme+0x61/0x61
[   88.229043] Code: 65 ff 0d 9d 93 ef 7e 83 f8 01 4c 89 a3 18 c0 ff ff 5b 48 19 c0 41 5c 48 f7 d0 5d 48 83 e0 f2 c3 48 8b 47 08 55 48 8b 17 48 89 e5 <48> 89 42 08 
48 89 10 
[   88.254124] RIP  [<ffffffff81112557>] list_del+0xb/0x2f
[   88.262035]  RSP <ffff88006351ba78>
[   88.268176] ---[ end trace d6ba8b4288207052 ]---
[   94.877265] general protection fault: 0000 [#2] SMP 
[   94.884897] Modules linked in: nfsd pl2303 usbserial ppdev x86_pkg_temp_thermal dcdbas usb_skeleton coretemp kvm_intel kvm parport_pc pata_acpi xts aes_x86_64 
sha256_genx
[   94.995063] CPU: 1 PID: 4026 Comm: irqbalance Tainted: P      D    O    4.1.6-gentoo #1
[   95.006069] Hardware name: Dell Inc. OptiPlex 390/0M5DCD, BIOS A11 10/14/2013
[   95.016228] task: ffff880066f27440 ti: ffff8800763ac000 task.ti: ffff8800763ac000
[   95.026701] RIP: 0010:[<ffffffff8114f623>]  [<ffffffff8114f623>] __slab_free+0x52/0x2b3
[   95.037673] RSP: 0018:ffff8800763afbd8  EFLAGS: 00010246
[   95.045874] RAX: 5a92828b05611adb RBX: ffff8800601cf320 RCX: ffffffff8113a27e
[   95.055860] RDX: ffff8800601cf320 RSI: 5a92828b05611adb RDI: ffff880100106000
[   95.065798] RBP: ffff8800763afc78 R08: 0000000000000000 R09: 5a92828b05611adb
[   95.075691] R10: 20656c62616b7361 R11: 0000000000000206 R12: 5a92828b05611adb
[   95.085515] R13: 0000000000000000 R14: ffff880100106000 R15: ffff880062d65810
[   95.095335] FS:  00007f3213d82740(0000) GS:ffff880079e40000(0000) knlGS:0000000000000000
[   95.106104] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   95.114526] CR2: 00007f3213dbd000 CR3: 0000000076425000 CR4: 00000000000406e0
[   95.124337] Stack:
[   95.129005]  ffffffff8201abe5 ffffffff8201abe6 ffff8800763afc90 ffff88006287c000
[   95.139115]  ffff8800763afc58 ffffffff815134cf ffffffff8201abe5 ffff88006287b47d
[   95.149218]  ffff8800763afcd0 ffff000aff0a0000 0000000000000fbb ffff8800763afc60
[   95.159324] Call Trace:
[   95.164433]  [<ffffffff815134cf>] ? vsnprintf+0x8a/0x3b1
[   95.172417]  [<ffffffff811303fe>] ? sync_mm_rss+0x42/0x74
[   95.180462]  [<ffffffff8113a27e>] ? anon_vma_free+0x3c/0x40
[   95.188675]  [<ffffffff8114f96f>] kmem_cache_free+0xeb/0x140
[   95.196952]  [<ffffffff8113a27e>] anon_vma_free+0x3c/0x40
[   95.204937]  [<ffffffff8113af7d>] __put_anon_vma+0x17/0x36
[   95.213004]  [<ffffffff8113afba>] put_anon_vma+0x1e/0x22
[   95.220880]  [<ffffffff8113b1da>] unlink_anon_vmas+0xf4/0x144
[   95.229188]  [<ffffffff811309bb>] free_pgtables+0x3e/0xcc
[   95.237134]  [<ffffffff81135758>] unmap_region+0xc8/0xec
[   95.244983]  [<ffffffff8113537a>] ? vma_gap_callbacks_propagate+0x1b/0x33
[   95.254314]  [<ffffffff81135bbc>] ? vma_rb_erase+0x171/0x197
[   95.262521]  [<ffffffff81137012>] do_munmap+0x275/0x2ea
[   95.270283]  [<ffffffff811370cc>] vm_munmap+0x45/0x5e
[   95.277859]  [<ffffffff8113710b>] SyS_munmap+0x26/0x2f
[   95.285515]  [<ffffffff81b478ee>] system_call_fastpath+0x12/0x71
[   95.294029] Code: 0d 21 00 74 15 4c 8d 45 88 e8 01 fe ff ff 48 85 c0 49 89 c5 0f 84 63 02 00 00 4d 85 ed 74 0c 48 8b 75 88 4c 89 ef e8 1b 7e 9f 00 <49> 8b 44 24 
18 4d 8b 
[   95.319068] RIP  [<ffffffff8114f623>] __slab_free+0x52/0x2b3
[   95.327427]  RSP <ffff8800763afbd8>
[   95.333626] ---[ end trace d6ba8b4288207053 ]---

**Comment by kernelOfTruth** [comment]
https://github.com/zfsonlinux/zfs/pull/3651 Fix Linux 4.1 compat regarding loop device on ZFS

**Comment by drescherjm** [comment]
Use the 9999 git ebuilds or wait for 0.6.5.

**Comment by behlendorf** [comment]
Right, thanks for filing this but as mentioned it was addressed by #3651 so I'm closing this as a duplicate.  Either of the proposed solutions will resolve the issue.
