### ISSUE TITLE
zfs consumes all 64GB memory (dedup, compression, and luks)

### ISSUE THREAD

**Issue by ilikenwf** [zfsonlinux/zfs#3755]
Machine:
64GB ECC
Perc5I (I know, I know) with 5x 1TB 7200 RPM each as RAID0
luks with zpool on top, dedup and compression enabled
Debian Jessie/Proxmox

I realize my hardware and software setup isn't ideal but I believe what is happening shouldn't be.

Even after limiting the ARC cache to 16GB, I find that on large writes - like copying backed up files over (numbering in the thousands), or restoring a VM (Proxmox) to a zvol (really just a big dd operation), that after a while all 64GB of my RAM is consumed. If I 

    echo 3 > /proc/sys/vm/drop_caches

The console hangs, but I then get most of the memory back, along with most system functionality. I find that aside from this, the system seems a little less responsive than it should be anyway.

I have tried different kernels, the stable, and the snapshot versions of zfs, but this problem leads to the dreaded "blocked for more than 120 seconds" if I'm not around to drop the caches.

Is this something I can fix if I rebuild my pool and disable dedup, or should I just run back to using hardware RAID, LUKS, and ext4?

**Comment by ilikenwf** [comment]
I've moved back to lvm.

**Comment by kernelOfTruth** [comment]
@ilikenwf on IRC or ZFS related forums, the mailing list you might have gotten a (faster) response

well, now it's too late probably anyway ...
