### ISSUE TITLE
Illumos #6214, concurrency race in manipulating ARC buffer flags during L2ARC writeout can cause pool corruption

### ISSUE THREAD

**Issue by siebenmann** [zfsonlinux/zfs#3757]
This is a just-filed Illumos bug where a concurrency race in manipulating hdr->b_flags between L2ARC writeout and ARC eviction can cause corrupt metadata to get written to the primary pool, [Illumos #6214 - zpools going south](https://www.illumos.org/issues/6214). I don't know if this applies to ZoL given the different kernel environments, but ZoL does have the base commit that introduced the problem in Illumos in b9541d6b7d765883f8a5fe7c1bde74df5c256ff6.

**Comment by behlendorf** [comment]
We'll definitely want to pull the upstream fix when it's available right away for this issue.  The same kind of race should be possible in ZoL but may be very unlikely in practice.

**Comment by ryao** [comment]
@behlendorf It requires that the system use L2ARC, which does not get test converage on the buildbot. Consequently, we have no idea how likely/unlikely it is. I think we should revert b9541d6b7d765883f8a5fe7c1bde74df5c256ff6 as a precaution while it is still not in a tagged release.

**Comment by kernelOfTruth** [comment]
Quickly skimming the discussion on https://www.reddit.com/r/sysadmin/comments/1hmvel/zfs_your_worst_experiences/

are there any pointers to the reports ?

What platform this is appear on (mainly Illumos ? *BSD ? ZOL ?) ?

What patchstack ? There were at least 2 subsequent fixes following that referenced commit, which fixed calculation and other problems with the l2arc - but I doubt they change anything in relation to zpool metadata corruption/issue

**Comment by behlendorf** [comment]
@siebenmann thanks for bringing this to our attention.  I think that even though this issue is exceptionally unlikely we need treat this as a blocker for 0.6.5 and delay the release.  @ryao unfortunately we can't easily revert b9541d6 so we'll need to fix the root cause.  Luckily it's my understanding that there's already fix in the works from the illumos guys.

**Comment by siebenmann** [comment]
I believe that the current illumos-devel thread discussing the proposed fix for this starts [here](http://comments.gmane.org/gmane.os.illumos.devel/23301), if people want a head start before the fix lands in the illumos-gate repo. [This initial illumos-devel message](http://article.gmane.org/gmane.os.illumos.devel/23221/) describes where to find the original thread with the problem report and discussion in the ZFS and OmniOS mailing lists. I don't know more than this, @kernelOfTruth, because I haven't been paying particular attention to the discussion of it on either list before now.

(What prompted my report here is [this strong warning about L2ARCs on omnios-discuss](http://permalink.gmane.org/gmane.os.omnios.general/5113) from one of the OmniOS developers.)
