### ISSUE TITLE
Compression not work with zfs blocksize=4K and zpool ashift=12

### ISSUE THREAD

**Issue by redtex** [zfsonlinux/zfs#3758]
I have two pools: main and backup.
Main pool with ashift=9 hosts VM's and has zvol blocksize=4k compression=lz4.
Backup pool with ashift=12 used to store backup increment copies of VM's

After upgrading my pools to 0.6.4 from 0.6.3 I've noticed, that when I create new backup with zfs send -R | zfs recv, backed up volumes has contrary properties, original zvol:

zfs get used,compressratio,logicalused sas-15k/vm-102-disk-1
NAME                   PROPERTY       VALUE  SOURCE
sas-15k/vm-102-disk-1  used           7.06G  -
sas-15k/vm-102-disk-1  compressratio  1.97x  -
sas-15k/vm-102-disk-1  logicalused    13.7G  -

Backup zvol:

zfs get used,compressratio,logicalused backup/vm-102-disk-1
NAME        PROPERTY       VALUE  SOURCE
tpool/test  used           13.3G  -
tpool/test  compressratio  2.00x  -
tpool/test  logicalused    13.7G  -

But when I've created test pool with ashift=9 and sent zvol on it, things become normal:

zfs get used,compressratio,logicalused tpool/vm-102-disk-1
NAME        PROPERTY       VALUE  SOURCE
tpool/test  used           6.96G  -
tpool/test  compressratio  2.00x  -
tpool/test  logicalused    13.7G  -

And on old zvols, which was created on backup with zfs v.0.6.3 things are normal too.
So, it seems to be a huge bug of 0.6.4

**Comment by dasjoe** [comment]
> Main pool with ashift=9 hosts VM's and has zvol blocksize=4k compression=lz4.
> Backup pool with ashift=12 used to store backup increment copies of VM's

So your backup pool uses ashift=12, which makes its minimal block size 4k.
You obviously can't gain anything from compression, other than skip writing whole blocks due to the obligatory ZLE pass when any kind of compression is enabled.

**Comment by fling-** [comment]
@redtex compression works just fine but you are getting a lot of overhead by padding with such small volblocksize set.

**Comment by redtex** [comment]
Understood, thank you.
