### ISSUE TITLE
ZVOLs appearing as drives in Ubuntu's Unity

### ISSUE THREAD

**Issue by sempervictus** [zfsonlinux/zfs#3759]
Recent changes to ZVOLs seem to have them enumerated via partprobe or similar component such that their partition tables show up in lsblk and the disks now appear in the unity task tray (which in my case added about a dozen disks to the thing and forces a scroll on it). On this particular system, LVMs are not being enumerated due to a filter setting, but it may also cause VG namespace collisions if multiple ZVOLs use the same VG names (or you have clones).
@ryao had me check for removable state on the devices, and __sudo find /sys -name removable | grep zd | xargs cat__ produces all zeroes for every zd device it finds.

**Comment by behlendorf** [comment]
@sempervictus that's surprising, I didn't expect any change in behavior.  Do you know exactly which patch caused this?

**Comment by sempervictus** [comment]
I'm pretty sure this came out of the recent changes in either ZVOL semantics (@ryao's elimination of an IO layer) or the accounting code. Dont have a specific commit as i only noticed it this morning on the 3rd stack containing ZVOL accounting fixup.

**Comment by behlendorf** [comment]
@sempervictus the odd thing is none of those changes should have changed how zvols are presented to the system.  Is it possible there was some change in unity that was made just recently which caused this?

**Comment by behlendorf** [comment]
@sempervictus I'm not sure this should be considered a ZoL bug.  ZVOLs are block devices and it's up to Unity and lsblk if they should be presented to users.  Any objection to closing this?
