### ISSUE TITLE
Log/Cache on separate drives are not set to noop.

### ISSUE THREAD

**Issue by dracwyrm** [zfsonlinux/zfs#3761]
On a default install of spl/zfs, the drives that contain the storage part of a pool have their schedulers set to noop. However, if you have the log and/or the cache on a separate drive, those drives are not set to noop. For example, my layout is as follows:

```
    NAME        STATE     READ WRITE CKSUM
    tank        ONLINE       0     0     0
      raidz1-0  ONLINE       0     0     0
        sdb     ONLINE       0     0     0
        sdc     ONLINE       0     0     0
        sdd     ONLINE       0     0     0
    logs
      mirror-1  ONLINE       0     0     0
        sde1    ONLINE       0     0     0
        sdf1    ONLINE       0     0     0
    cache
      sde2      ONLINE       0     0     0
      sdf2      ONLINE       0     0     0
```

The defaults that are set are as follows:

```
cat /sys/block/sd{a,b,c,d,e,f}/queue/scheduler
(sda) noop deadline cfq [bfq] 
(sdb) [noop] deadline cfq bfq 
(sdc) [noop] deadline cfq bfq 
(sdd) [noop] deadline cfq bfq 
(sde) noop deadline cfq [bfq] 
(sdf) noop deadline cfq [bfq]
```

I added the drive for easier reading. I need to manually set sde/sdf to noop.

This happens for all versions in the master branch up to 09/09/2015 and in the stable release of v0.6.4.2.

I think it seems to be faster with sde/sdf set to noop, so some more testing will need to be done with this. Well, also for consistency, having the mechinism that makes my sdb, sdc, and sdd set to noop should set the log/cache drives to noop.

I was told to make this a bug report. There have been tests done by other users that prove noop is the faster scheduler to use for zfs.

Hope this helps.

**Comment by fling-** [comment]
@dracwyrm could you try using whole drives for logs and/or cache?

**Comment by dracwyrm** [comment]
@fling- At first I thought it was because I used /dev/sdx notation for the raid and /dev/disk/by-id for the log and cache when creating the ztank. However, I have been recompiling my whole system the past few days using the new 5.2 version of GCC (hence I haven't been on here much), so I started fresh with a fresh ztank to try out the patch for the other bug that I had.

Anyways, I was able to create the entire ztank using /dev/disk/by-id notation (which is wanted to do from the beginning but ran into yet another bug reported by a different user about not being able to do that). After checking the out:

````
cat /sys/block/sd{a,b,c,d,e,f}/queue/scheduler 
noop deadline [cfq] bfq 
[noop] deadline cfq bfq 
[noop] deadline cfq bfq 
[noop] deadline cfq bfq 
noop deadline [cfq] bfq 
noop deadline [cfq] bfq 
````

Even with IDs it was able to make the drives as noop.

As per your question, I have my Gentoo repository on the first partitions of those two drives to keep them separate due to file fragmentation and because that is one thing I would use every now and then, so it won't affect drive performance. I would have had to wipe that out. However, Regardless of other partitions, it should be set to noop, right? If one has two partitions, log and cache, would it work then? At the moment, I don't know if I want to wipe out the two drives to check that.

Kind regards,
Jon

**Comment by behlendorf** [comment]
@dracwyrm because disk I/O scheduler can only be set on a per-device basis (i.e. sd{a,b,c}) changing it will effect all partitions on the device.  Since ZFS was only given a single partition for the cache device it's unaware what else may be using the block device and therefore doesn't know if it's safe to automatically change the scheduler.  You're going to want to either manually set this on your system, or give ZFS the entire device.
