### ISSUE TITLE
zfs(8) incorrect description of zfs unmount -a

### ISSUE THREAD

**Issue by ilovezfs** [zfsonlinux/zfs#3762]
The error is here:
https://github.com/zfsonlinux/zfs/blob/058ac9ba7811baea78a47ba1ead8acd7512684b6/man/man8/zfs.8#L2034-L2038
(Unmount is part of shutdown not boot.)

illumos has recently corrected the error here: https://github.com/illumos/illumos-gate/commit/b3cff10cdd26674d8dc66e0b349fd185df709fad

**Comment by behlendorf** [comment]
Yup, thanks.
