### ISSUE TITLE
l2arc fully aggressive settings?

### ISSUE THREAD

**Issue by inkdot7** [zfsonlinux/zfs#3774]
I am trying to use ZFS as a replacement for a low-latency file system
built with MD mirror raid of SSD and (a few) HDDs for resiliency.  By
using the MD option write-mostly, all reads are served by the SSD with
low latency and high bandwidth.  (As long as the SSD is alive :) )

I have not been able to find an option to tell a ZFS mirrored pool to
serve all reads by some specific disks (the SSDs).  Is there one?
(Such an option would be very nice.)

I thought that by setting the SSD up as L2ARC, and being larger than
the pool, it would serve all reads (after the first time), and thus give
the read latency and bandwidth performance of the SSDs.

It seems that the default options of the zfs module do not handle this
situation well however.  I have therefore done the following:

l2arc_noprefetch=0           # To do also streaming reads
l2arc_headroom=1000          # To scan all ARC to end up in L2ARC
l2arc_write_max=15000000     # This combined with the smaller
l2arc_write_boost=15000000
l2arc_feed_min_ms=50         # value here seems to feed better,
                             # in total 300 MB/s, which is faster
                             # then the HDDs I have in now can read.

It almost does the trick, but not fully:

I have created a number of test file, one of them is 8 GB, the other
22 GB.  When reading either of them once, I can see that all reads on
a subsequent read is from the cache devices.  Good.  When reading them
after each other, and then again after each other, some reads go from the
HDDs.  I am confused why data apparently is evicted from the L2ARC, as
there still is (lots of) free space in the L2ARC...

This also happens after a fresh boot of the machine, i.e. cleared (L2ARC).
Reading one of the large file apparently clears out data from the other.

(The machine has 32 GiB, which is the limit, and I'd like to be able to
use memory also for other tasks than ZFS.  That's why the large SSDs
(expensive, but way cheaper than memory. :-) ))

If it is of help, below is a current dump from arc_summary.pl.  The
machine is running Debian, with zfsonlinux, 0.6.4-1.2-1.

------------------------------------------------------------------------
ZFS Subsystem Report				Mon Sep 14 16:06:37 2015
ARC Summary: (HEALTHY)
	Memory Throttle Count:			0

ARC Misc:
	Deleted:				3.03m
	Recycle Misses:				221.96k
	Mutex Misses:				197
	Evict Skips:				197

ARC Size:				99.99%	13.04	GiB
	Target Size: (Adaptive)		100.00%	13.04	GiB
	Min Size (Hard Limit):		28.57%	3.73	GiB
	Max Size (High Water):		3:1	13.04	GiB

ARC Size Breakdown:
	Recently Used Cache Size:	54.20%	7.07	GiB
	Frequently Used Cache Size:	45.80%	5.97	GiB

ARC Hash Breakdown:
	Elements Max:				2.53m
	Elements Current:		100.00%	2.53m
	Collisions:				716.46k
	Chain Max:				7
	Chains:					513.88k

ARC Total accesses:					5.39m
	Cache Hit Ratio:		52.66%	2.84m
	Cache Miss Ratio:		47.34%	2.55m
	Actual Hit Ratio:		52.44%	2.83m

	Data Demand Efficiency:		100.00%	1.46m
	Data Prefetch Efficiency:	0.02%	1.40m

	CACHE HITS BY CACHE LIST:
	  Most Recently Used:		37.58%	1.07m
	  Most Frequently Used:		62.02%	1.76m
	  Most Recently Used Ghost:	3.04%	86.32k
	  Most Frequently Used Ghost:	10.53%	298.83k

	CACHE HITS BY DATA TYPE:
	  Demand Data:			51.28%	1.46m
	  Prefetch Data:		0.01%	287
	  Demand Metadata:		48.31%	1.37m
	  Prefetch Metadata:		0.40%	11.37k

	CACHE MISSES BY DATA TYPE:
	  Demand Data:			0.00%	24
	  Prefetch Data:		54.78%	1.40m
	  Demand Metadata:		45.11%	1.15m
	  Prefetch Metadata:		0.10%	2.65k

L2 ARC Summary: (HEALTHY)
	Low Memory Aborts:			0
	Free on Write:				7.40k
	R/W Clashes:				0
	Bad Checksums:				0
	IO Errors:				0

L2 ARC Size: (Adaptive)				231.12	GiB
	Compressed:			99.54%	230.05	GiB
	Header Size:			0.31%	745.48	MiB

L2 ARC Evicts:
	Lock Retries:				0
	Upon Reading:				0

L2 ARC Breakdown:				2.55m
	Hit Ratio:			38.37%	979.46k
	Miss Ratio:			61.63%	1.57m
	Feeds:					39.44k

L2 ARC Writes:
	Writes Sent:			100.00%	20.30k

File-Level Prefetch: (HEALTHY)
DMU Efficiency:					29.18m
	Hit Ratio:			99.65%	29.08m
	Miss Ratio:			0.35%	101.06k

	Colinear:				101.06k
	  Hit Ratio:			0.01%	8
	  Miss Ratio:			99.99%	101.05k

	Stride:					27.46m
	  Hit Ratio:			100.00%	27.46m
	  Miss Ratio:			0.00%	636

DMU Misc: 
	Reclaim:				101.05k
	  Successes:			0.18%	185
	  Failures:			99.82%	100.86k

	Streams:				1.62m
	  +Resets:			0.00%	10
	  -Resets:			100.00%	1.62m
	  Bogus:				0

ZFS Tunable:
	metaslab_debug_load                               0
	zfs_arc_min_prefetch_lifespan                     250
	zfetch_max_streams                                8
	zfs_nopwrite_enabled                              1
	zfetch_min_sec_reap                               2
	zfs_dirty_data_max_max_percent                    25
	zfs_arc_p_aggressive_disable                      1
	spa_load_verify_data                              1
	zfs_zevent_cols                                   80
	zfs_dirty_data_max_percent                        10
	zfs_sync_pass_dont_compress                       5
	l2arc_write_max                                   15000000
	zfs_vdev_scrub_max_active                         2
	zfs_vdev_sync_write_min_active                    10
	zfs_no_scrub_prefetch                             0
	zfs_arc_shrink_shift                              5
	zfetch_block_cap                                  256
	zfs_txg_history                                   0
	zfs_delay_scale                                   500000
	zfs_vdev_async_write_active_min_dirty_percent     30
	metaslab_debug_unload                             0
	zfs_read_history                                  0
	zvol_max_discard_blocks                           16384
	zfs_recover                                       0
	l2arc_headroom                                    1000
	zfs_deadman_synctime_ms                           1000000
	zfs_scan_idle                                     50
	zfs_free_min_time_ms                              1000
	zfs_dirty_data_max                                3377293721
	zfs_vdev_async_read_min_active                    1
	zfs_mg_noalloc_threshold                          0
	zfs_dedup_prefetch                                0
	zfs_vdev_max_active                               1000
	l2arc_write_boost                                 15000000
	zfs_resilver_min_time_ms                          3000
	zfs_vdev_async_write_max_active                   10
	zil_slog_limit                                    1048576
	zfs_prefetch_disable                              0
	zfs_resilver_delay                                2
	metaslab_lba_weighting_enabled                    1
	zfs_mg_fragmentation_threshold                    85
	l2arc_feed_again                                  1
	zfs_zevent_console                                0
	zfs_immediate_write_sz                            32768
	zfs_free_leak_on_eio                              0
	zfs_deadman_enabled                               1
	metaslab_bias_enabled                             1
	zfs_arc_p_dampener_disable                        1
	zfs_metaslab_fragmentation_threshold              70
	zfs_no_scrub_io                                   0
	metaslabs_per_vdev                                200
	zfs_dbuf_state_index                              0
	zfs_vdev_sync_read_min_active                     10
	metaslab_fragmentation_factor_enabled             1
	zvol_inhibit_dev                                  0
	zfs_vdev_async_write_active_max_dirty_percent     60
	zfs_vdev_cache_size                               0
	zfs_vdev_mirror_switch_us                         10000
	zfs_dirty_data_sync                               67108864
	spa_config_path                                   /etc/zfs/zpool.cache
	zfs_dirty_data_max_max                            8443234304
	zfs_zevent_len_max                                128
	zfs_scan_min_time_ms                              1000
	zfs_vdev_cache_bshift                             16
	zfs_arc_meta_adjust_restarts                      4096
	zfs_arc_memory_throttle_disable                   1
	zfs_vdev_scrub_min_active                         1
	zfs_vdev_read_gap_limit                           32768
	zfs_arc_meta_limit                                0
	zfs_vdev_sync_write_max_active                    10
	l2arc_norw                                        0
	zfs_arc_meta_prune                                10000
	metaslab_preload_enabled                          1
	l2arc_nocompress                                  0
	zvol_major                                        230
	zfs_vdev_aggregation_limit                        131072
	zfs_flags                                         0
	spa_asize_inflation                               24
	l2arc_feed_secs                                   1
	zfs_sync_pass_deferred_free                       2
	zfs_disable_dup_eviction                          0
	zvol_threads                                      32
	zfs_arc_grow_retry                                5
	zfs_read_history_hits                             0
	zfs_vdev_async_write_min_active                   1
	zfs_vdev_async_read_max_active                    3
	zfs_scrub_delay                                   4
	zfs_delay_min_dirty_percent                       60
	zfs_free_max_blocks                               100000
	zfs_vdev_cache_max                                16384
	zio_delay_max                                     30000
	zfs_top_maxinflight                               32
	zfs_vdev_write_gap_limit                          4096
	spa_load_verify_metadata                          1
	spa_load_verify_maxinflight                       10000
	l2arc_noprefetch                                  0
	zfs_vdev_scheduler                                noop
	zfs_expire_snapshot                               300
	zfs_sync_pass_rewrite                             2
	zil_replay_disable                                0
	zfs_nocacheflush                                  0
	zfs_arc_max                                       14000000000
	zfs_arc_min                                       4000000000
	zfs_read_chunk_size                               1048576
	zfs_txg_timeout                                   5
	zfs_pd_bytes_max                                  52428800
	l2arc_headroom_boost                              200
	zfs_send_corrupt_data                             0
	l2arc_feed_min_ms                                 50
	zfs_arc_average_blocksize                         8192
	zfetch_array_rd_sz                                1048576
	zfs_autoimport_disable                            1
	zio_requeue_io_start_cut_in_line                  1
	zfs_vdev_sync_read_max_active                     10
	zfs_mdcomp_disable                                0

**Comment by ptx0** [comment]
Please close this and use the mailing list for general discussion -> http://list.zfsonlinux.org

**Comment by inkdot7** [comment]
Ok, I will.  But one could see it as a bug also: why does L2ARC drop entries when it has free space?

**Comment by inkdot7** [comment]
sent to zfs-discuss
