### ISSUE TITLE
Snapshots mounted over NFS do not unmount

### ISSUE THREAD

**Issue by angstymeat** [zfsonlinux/zfs#3776]
I installed 0.6.5 on one of our file servers today, and tried out the new ability to look at a snapshot over NFS. That worked fine.

The server mounted the snapshots locally and the ycould be read from the remote client, however the server is never unmounting the snapshots. I have autofs set for a 300 second timeout, and this last time I've waited for 45 minutes. The user that mounted the snapshots on the client has been logged out for most of that time. Trying to delete the snapshot failed, too.

When I try to force an unmount I with ```umount -f``` I get a message that the target is busy. Neither ```lsof``` or ```fuser``` show any of these mounts in use.

Update: ```zfs-auto-snapshot``` just completed its hourly run, and the wayward snapshots have been unmounted and renamed. It's looking like destroying them with ```-r``` works, at least if you want to delete a snapshot.

The file server is running the 3.11.10-100.fc18.x86_64 kernel with spl & zfs version 0.6.5-1.

**Comment by angstymeat** [comment]
And now, for some reason, everything is unmounting correctly now. It didn't start working until after ```zfs-auto-snapshot``` ran, though.

**Comment by behlendorf** [comment]
@angstymeat the unmount may not be immediately possible if there are open NFS file handles cached on the server.  Once those handles timeout the filesystem can be unmounted but as of today a manual unmount on the server doesn't force that.  That's might be a nice addition if we can find a clean way to do it.  In the meanwhile this shouldn't cost you anything on the server handles will be dropped in memory is needed and eventually the snapshots will automatically unmount.

**Comment by angstymeat** [comment]
I was concerned that I would have issues renaming or deleting a snapshot if it was showing up as mounted, but it doesn't appear to be an issue.

I'm going to close this.
