### ISSUE TITLE
Snapshot automount fails under chroot

### ISSUE THREAD

**Issue by lazy404** [zfsonlinux/zfs#3778]
Sep 14 18:31:36 www kernel: WARNING: Unable to automount /.zfs/snapshot/test/wwwpool/lazydev_zfstest@test: 512

wwwpool is mounted under /home/www, the process is chrooted at /home/www/lazydev_zfstest

full_path should be /home/www/lazydev_zfstest/.zfs/snapshot/test but is /.zfs/snapshot/test
https://github.com/zfsonlinux/zfs/blob/master/module/zfs/zfs_ctldir.c#L691
called by
https://github.com/zfsonlinux/zfs/blob/master/module/zfs/zfs_ctldir.c#L1069

using d_absolute_path() fixed the issue but it isn't normally exported

**Comment by behlendorf** [comment]
@lazy404 as of 0.6.5 we have another way to tackle this.  We could use `zfsctl_snapshot_path_objset()` to construct the full path when the path generated by `zfsctl_snapshot_path()` fails.  This function was added to handle the NFS auto-mount case which is similar to the chroot case.  That way we don't need to depend on `d_absolute_path()` which as you point out isn't always available.

**Comment by behlendorf** [comment]
@lazy404 are you still observing this with recent 0.6.5.x releases?

**Comment by lazy404** [comment]
It failed with some earlier 0.6.5.x releases but it was gracefull,
i will check with the last one

**Comment by behlendorf** [comment]
This issue was resolved in the 0.7 series.
