### ISSUE TITLE
Fedora 23 Repository

### ISSUE THREAD

**Issue by maci0** [zfsonlinux/zfs#3781]
Fedora 23 already has pre-releases. The zfsonlinux repo should be updated as well.
I still think ZoL should try to provide the new repo as soon as Fedora branches rawhide into the next release tree, maybe even provide ZoL for rawhide as well. That way early adopters/testers have an easier way to upgrade and maybe discover bugs with new toolchains or kernels in combination with ZoL way before stuff gets officially released. Maybe also have the automated tests running on those pre-releases and rawhide.

**Comment by behlendorf** [comment]
We'll see what can be done about adding a Fedora 23 repository soon.

**Comment by stewartadam** [comment]
Any update on this? Fedora 23 is now released.

**Comment by x09** [comment]
Fedora 23 repo very need!

**Comment by grizzlyfred** [comment]
I would love to get to know what to do except follow the "build from git" route. My 22 => 23 upgrade in the vm was bumpy (had do to an additional dnf with a lot of different options and hints along with rebuilding rpm-db) in the almost only updated but never really used vm, so I am scared to upgrade my datastore real metal server/nas/w'ever

**Comment by kernelOfTruth** [comment]
@grizzlyfred there's an upstream patch, commit for it - but no one has ported it yet ...

**Comment by bziller** [comment]
BTW: I'm currently just using zfs's Fedora 22 packages with Fedora 23. Modules compile just fine.YMMV

**Comment by behlendorf** [comment]
The Fedora 22 DKMS packages will work fine with Fedora 23 until a new repository can be added.

**Comment by bbabich** [comment]
Maybe, but not out of the box. 

[root@seal ~]# zpool status
The ZFS modules are not loaded.
[root@seal ~]# /sbin/modprobe zfs
modprobe: FATAL: Module zfs not found in directory /lib/modules/4.2.6-300.fc23.x86_64
[root@seal ~]#

**Comment by tpagden** [comment]
Same as bbabich with me. However I may have some operator error here.

Modules zfs not found in directory /lib/modules/4.2.6xxxx

**Comment by storrgie** [comment]
It's certainly holding me up from using ZFS on a couple systems. Is there some big changeovers in the packaging/building of the ZoL project that is holding this up?

**Comment by Trisooma** [comment]
I would also like to see an official Fedora 23 repo, any news yet?

**Comment by behlendorf** [comment]
Packages are now available for Fedora 23.  Sorry about the delay, but I ran in to some issues with `mock`, `dnf`, and packaging signing in the latest release.  

```
$ sudo yum install --nogpgcheck http://archive.zfsonlinux.org/fedora/zfs-release$(rpm -E %dist).noarch.rpm
$ sudo yum install kernel-devel zfs 
```

**Comment by tpagden** [comment]
Thank you!

**Comment by JamesRHarris** [comment]
Make sure you run "dkms install" for spl and zfs for each kernel you might
boot. After the new packages came in I was missing modules. More in my note
on the zfs-discuss list.

On Tue, Dec 8, 2015 at 5:59 PM, tpagden <notifications@github.com> wrote:

> Thank you!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zfsonlinux/zfs/issues/3781#issuecomment-163082006>.
>



-- 
James Harris
Software Engineer
james.r.harris@gmail.com

**Comment by fardok** [comment]
cant  install zfs:
 sudo yum install kernel-devel zfs 
 -Cannot download  repomd.xml: Cannot download repodata/repomd.xml: all mirrors were tried ... errror 
yum  try  to install from  http://archive.zfsonlinux.org/fedora/22/i386/    BUT   my linux is i686!      how can i change to i686?

**Comment by error10** [comment]
@fardok, This issue is not related to yours. Fedora packages are built for 64-bit systems, and trying to use ZFS on a 32-bit system isn't recommended anyway.

**Comment by fardok** [comment]
processor is AMD Athlon 2 x2  - he is  x64

**Comment by kernelOfTruth** [comment]
@fardok so why don't you make use of the 64bit support and install a 64bit Linux distribution ?

That way the kernel modules exist

you can *_try_* to use ZFSonLinux with a 32bit distribution but it's not recommended (and not really supported) and

in that case it would be best to compile the kernel modules on your own.

If you need further support please go to the IRC channel: 
​#zfsonlinux freenode

or use the zfs-discuss mailing list

or perhaps one of the bigger Fedora forums

**Comment by tirrorex** [comment]
Are those packages supposed to work right of the box on fedora 23? Not working here
