### ISSUE TITLE
zfs 0.6.5 not in Debian (jessie) repository

### ISSUE THREAD

**Issue by Pentium100MHz** [zfsonlinux/zfs#3784]
Hi, 
For some reason the new version is not in Debian repository.

```
apt-get update
apt-cache madison zfs-dkms
  zfs-dkms | 0.6.4-1.2-1 | http://archive.zfsonlinux.org/debian/ jessie/main amd64 Packages
apt-cache madison debian-zfs
debian-zfs |   7~jessie | http://archive.zfsonlinux.org/debian/ jessie/main amd64 Packages
```
Do I need to add a new repository or is the new version going to be in the same repository as 0.6.4?

**Comment by agijsberts** [comment]
The right place to discuss this would probably be the packaging repository in https://github.com/zfsonlinux/pkg-zfs. Checking the releases thus far on https://github.com/zfsonlinux/pkg-zfs/releases it seems that 0.6.5 has been made available for Ubuntu but not yet for Debian.

**Comment by Pentium100MHz** [comment]
Sorry, I didn't know the packages were a separate thing.

**Comment by FransUrbo** [comment]
Done. <code>0.6.5-1</code> is now available for both Wheezy and Jessie. Both Released and Dailes.

Please close this.
