### ISSUE TITLE
ZFS uses directory-based xattrs despite xattr=sa

### ISSUE THREAD

**Issue by nedbass** [zfsonlinux/zfs#3787]
ZFS uess a directory-based extended attribute even when the `xattr=sa` dataset property is in effect. This is a regression in 0.6.5 introduced by commit 0282c4137e7409e6d85289f4955adf07fac834f5. The example commands below demonstrate the issue.

```
truncate -s 1g /tmp/vdev
zpool create tank /tmp/vdev
zfs create -o xattr=sa tank/fish
touch /tank/fish/x
setfattr  -n user.foo -v foo /tank/fish/x
inode=`ls -li /tank/fish/x | awk '{print $1}'`
zdb -vvvv tank/fish $inode
# observe that SA xattr is missing and a separate xattr object ID is allocated
```

**Comment by nedbass** [comment]
Updated patch to use `saxattr` and `dirxattr` mount options instead of `xattr=sa` and `xattr=dir`. This mirrors the valid dataset property values and adheres to mount option naming conventions. Also eliminates ugly string handling from the option parsing code.

**Comment by behlendorf** [comment]
LGTM
