### ISSUE TITLE
ZFS Panics with PAX Patch/Grsec (Related to SLAB_USERCOPY)

### ISSUE THREAD

**Issue by wuffleton** [zfsonlinux/zfs#3796]
Hello. I'm finding myself getting kernel panics as soon as I try loading zfs under a hardened kernel (linux-grsec on Arch Linux). I've asked over at the Grsecurity forums since the panic was a security feature being tripped, and the PAX team says that it's because the slab cache is not marked with SLAB_USERCOPY.

In my searching, issue #2977 may be relevant to this problem.

Grsecurity Thread: https://forums.grsecurity.net/viewtopic.php?f=3&t=4266
Output of Panic: 
![panicatthezfs](https://cloud.githubusercontent.com/assets/4283099/9952429/51aa31e0-5d8a-11e5-8175-bd8db5c12e31.png)

**Comment by behlendorf** [comment]
@wuffleton thanks for the link.  I'm not setup to test PAX could you verify  that applying the following patch to the spl code solves the problem.  It ensures all slabs are created with the  SLAB_USERCOPY on a PAX system.

```diff
diff --git a/module/spl/spl-kmem-cache.c b/module/spl/spl-kmem-cache.c
index a83c9f3..1e49bd0 100644
--- a/module/spl/spl-kmem-cache.c
+++ b/module/spl/spl-kmem-cache.c
@@ -986,13 +986,18 @@ spl_kmem_cache_create(char *name, size_t size, size_t alig
                if (rc)
                        goto out;
        } else {
+               unsigned long slabflags = 0;
+
                if (size > (SPL_MAX_KMEM_ORDER_NR_PAGES * PAGE_SIZE)) {
                        rc = EINVAL;
                        goto out;
                }
 
+#if defined(SLAB_USERCOPY)
+               slabflags |= SLAB_USERCOPY;
+#endif
                skc->skc_linux_cache = kmem_cache_create(
-                   skc->skc_name, size, align, 0, NULL);
+                   skc->skc_name, size, align, slabflags, NULL);
                if (skc->skc_linux_cache == NULL) {
                        rc = ENOMEM;
                        goto out;
```

**Comment by wuffleton** [comment]
@behlendorf I can confirm that this patch corrects the issue with the current zfs/spl versions under linux-grsec 4.1.7.201509201149-1-grsec on Arch Linux! I used the same commits as our current AUR packages for both modules in order to test this, which are 2b5a45f for SPL and 159270e for ZFS.

Sorry for the slightly delayed reply on this, work's been pretty busy this week and I just had a chance to build a minimal VM for testing.  

Both SPL and ZFS can be probed without issues, and common ZFS operations appear to be working as expected with no complaints in dmesg or panics from PAX/GRSEC.

**Comment by behlendorf** [comment]
Fix merged as:

zfsonlinux/spl@2ebe396 Fix PAX Patch/Grsec SLAB_USERCOPY panic
