### ISSUE TITLE
Mounting iso-file from ZFS hangs system

### ISSUE THREAD

**Issue by Markismus** [zfsonlinux/zfs#3802]
Mounting an iso-file from a ZFS (zfs-git 0.6.4.2_r0_g44b5ec8_4.1.6_1-1 (archzfs-git)) zpool completely freezes my system (4.1.6-1-ARCH).

When mounting a iso-file from a mounted ZFS pool the system hangs indefinitely (at least 10 minutes).
When mounting the same iso-file from a mounted ext4 partition, it's mounted immediately.

The ZFS pool is a raidz1 with 4 devices.
The ext4 partition is a logical volume made with LVM on mdraid 5 with 5 devices.

For testing purposes I have created a raidz1 zpool alongside my other partitions. This is the first, rather impressive problem I have run into.

The only additional info I was able to generate is with the command " sudo mount filename.iso /media/iso -t udf -o loop ". It first generated a line stating that the loop device was mounted read-only, before freezing.

Does someone know where I could look for information to tackle this problem?

**Comment by DeHackEd** [comment]
#3651
This was fixed in the 0.6.5 tag. Please upgrade, but do be mindful of a known ZVOL corruption bug and check with your package maintainer to see if they have the fix applied.

**Comment by kernelOfTruth** [comment]
@DeHackEd , @Markismus that should be addressed as well,

https://github.com/zfsonlinux/zfs/commits/zfs-0.6.5-release

now only that state needs to land in AUR or as an Arch package

**Comment by Markismus** [comment]
Great! 

[0.6.5.1 has landed in AUR.](https://aur.archlinux.org/packages/zfs-git/)

**Comment by GabrieleV** [comment]
I confirm the issue, using native ZFS 0.6.4.x as shipped in Ubuntu 15.10.
Using the latest 0.6.5.5.1 version  from https://launchpad.net/~zfs-native/+archive/ubuntu/stable , I can mount loop devices on image files residing on zfs filesystem without hangs.
