### ISSUE TITLE
Debian Jessie : DKMS issue

### ISSUE THREAD

**Issue by jpapadopoulos** [zfsonlinux/zfs#3807]
When running dkms build zfs/0.6.5.1 it is looking for the spl source in /usr/src/spl-0.6.5.1 but the source is actually in /usr/src/spl-0.6.5 since spl is still at version 0.6.5

**Comment by whatarcane** [comment]
Can confirm, I had to revert to Debian Wheezy after upgrading to Jessie.  zfs-dkms is uninstallable.

**Comment by whatarcane** [comment]
This is the error message seen when installing zfs-dkms:
Building initial module for 3.16.0-4-amd64
configure: error: 
	*** Please make sure the kmod spl devel <kernel> package for your
	*** distribution is installed then try again.  If that fails you
	*** can specify the location of the spl objects with the
	*** '--with-spl-obj=PATH' option.
Error! Bad return status for module build on kernel: 3.16.0-4-amd64 (x86_64)
Consult /var/lib/dkms/zfs/0.6.5.1/build/make.log for more information.

/var/lib/dkms/zfs/0.6.5.1/build/make.log contains:
make: *** No targets specified and no makefile found.  Stop.

Creating a symlink from /usr/src/spl-0.6.5.1 to /usr/src/spl-0.6.5 doesn't help.

**Comment by whatarcane** [comment]
The same happened on Debian Wheezy.

**Comment by tremzz** [comment]
Confirmed on Debian Jessie/8.  Exact same issues as above.  I also attempted to copy the src contents from /usr/src/spl-0.6.5 into /usr/src/spl-0.6.5.1.  

The install simply hangs here at this point.
..
....
Unpacking debian-zfs (7~jessie) ...
Processing triggers for initramfs-tools (0.120) ...
update-initramfs: Generating /boot/initrd.img-3.16.0-4-amd64
Processing triggers for man-db (2.7.0.2-5) ...
Processing triggers for systemd (215-17+deb8u2) ...
Setting up zfs-dkms (0.6.5.1-1) ...
Loading new zfs-0.6.5.1 DKMS files...
First Installation: checking all kernels...
Building only for 3.16.0-4-amd64
Building initial module for 3.16.0-4-amd64

My issue started while doing an apt-get update and apt-get upgrade today.  Previously it has been working flawlessly.

**Comment by cmiscloni** [comment]
Same problem for me on Wheezy 3.16.0-0.bpo.4-amd64

checking spl source directory... Not found
configure: error: 
	*** Please make sure the kmod spl devel package for your distribution
	*** is installed then try again.  If that fails you can specify the
	*** location of the spl source with the '--with-spl=PATH' option.

**Comment by niekbergboer** [comment]
Confirmed, on Debian Jessie (though running a custom 4.1.2 kernel).

**Comment by christoph-h** [comment]
Confirmed on Wheezy, running 2.6.32-33-pve:
Loading new zfs-0.6.5.1 DKMS files...
Building only for 2.6.32-33-pve
Building initial module for 2.6.32-33-pve
configure: error: 
        *** Please make sure the kmod spl devel package for your distribution
        *** is installed then try again.  If that fails you can specify the
        *** location of the spl source with the '--with-spl=PATH' option.
Error! Bad return status for module build on kernel: 2.6.32-33-pve (x86_64)
Consult /var/lib/dkms/zfs/0.6.5.1/build/make.log for more information.

**Comment by tremzz** [comment]
@niekbergboer 
Your extra symlink solved the problem for me.  However, instead of installing just reinstalling zfs-dkms (as I had already uninstalled it during my efforts to solve the issue), I did an 'apt-get install debian-zfs" and here was the result:

(Truncated for brevity)
apt-get install debian-zfs
....
DKMS: install completed.
Setting up libzfs2 (0.6.5.1-1) ...
Setting up zfsutils (0.6.5.1-1) ...
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
update-rc.d: warning: start runlevel arguments (S) do not match zfs-zed Default-Start values (2 3 4 5)
insserv: Service zfs-mount has to be enabled to start service zfs-zed
insserv: exiting now!
update-rc.d: error: insserv rejected the script header
dpkg: error processing package zfsutils (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of debian-zfs:
 debian-zfs depends on zfsutils; however:
  Package zfsutils is not configured yet.

dpkg: error processing package debian-zfs (--configure):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.19-18+deb8u1) ...
Processing triggers for initramfs-tools (0.120) ...
update-initramfs: Generating /boot/initrd.img-3.16.0-4-amd64
E: Sub-process /usr/bin/dpkg returned an error code (1)

However, after modprobing for zfs, I can see my pools and access them.   Will be looking into the zfsutils issue.

**Comment by FransUrbo** [comment]
Please see the second section of the "Where to report problems" in the FAQ: http://zfsonlinux.org/faq.html#WhereDoIReportProblems

This belong to https://github.com/zfsonlinux/pkg-zfs. Please close and move.

PS. I'm currently testing a fix, should be available within the hour (just woke up).

**Comment by jpapadopoulos** [comment]
My bad, i will pay more attention next time. Do i actually have the necessary permissions to move it?

**Comment by FransUrbo** [comment]
It's not possible to practically _move_ an issue. You'll have to open a new and close the other.

**Comment by FransUrbo** [comment]
But give it a couple of minutes. The fix is good and a new package should be available within the hour (depending on Amazon S3 and their sync time).

**Comment by cmiscloni** [comment]
Fix should be available in "http://archive.zfsonlinux.org/debian wheezy main" too ?
Thanks

**Comment by FransUrbo** [comment]
Yes. Both Wheezy and Jessie, Released and Dailies.

**Comment by jpapadopoulos** [comment]
ZFS is building now for me, however the zfsutils issue mentioned by tremzz still persists. I'm thinking that one deserves it's own ticket though

**Comment by tremzz** [comment]
@jpapadopoulos are you going to submit a new ticket for the zfsutils issue?  If not, I suppose I could do it.

**Comment by schlomie** [comment]
@jpapadopoulos 
@tremzz 

Although already closed, and the ticket is not directly related to the zfsutils problem stated above, but I just wanted to post a work-around that has worked for me.  I have not yet dug down to find the root of the issue, but I think it has something to do (at least with the Debian packaging) with the systemd hooks.

After installing/building zfs-dkms, apt complains about zfsutils being broken.  I've worked around this with the following:

```
systemctl enable zfs-import
systemctl enable zfs-mount
apt-get -f install
```
After enabling the systemd hooks for zfs-import and zfs-mount, the installation of zfsutils completes successfully.

**Comment by tremzz** [comment]
@schlomie

Thanks for the reply - nice work.  Your solution worked for me as well.

root@hostname: ~# systemctl enable zfs-import
Synchronizing state for zfs-import.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d zfs-import defaults
Executing /usr/sbin/update-rc.d zfs-import enable
root@hostname: ~# systemctl enable zfs-mount
Synchronizing state for zfs-mount.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d zfs-mount defaults
Executing /usr/sbin/update-rc.d zfs-mount enable
The unit files have no [Install] section. They are not meant to be enabled
using systemctl.
Possible reasons for having this kind of units are:
1) A unit may be statically enabled by being symlinked from another unit's
   .wants/ or .requires/ directory.
2) A unit's purpose may be to act as a helper for some other unit which has
   a requirement dependency on it.
3) A unit may be started when needed via activation (socket, path, timer,
   D-Bus, udev, scripted systemctl call, ...).
root@hostname: ~# apt-get -f install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
2 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up zfsutils (0.6.5.1-1) ...
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
update-rc.d: warning: start runlevel arguments (S) do not match zfs-zed Default-Start values (2 3 4 5)
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
Processing triggers for initramfs-tools (0.120) ...
update-initramfs: Generating /boot/initrd.img-3.16.0-4-amd64
Setting up debian-zfs (7~jessie) ...
