### ISSUE TITLE
data loss after cloning

### ISSUE THREAD

**Issue by roman-stratoscale** [zfsonlinux/zfs#3809]
suppose poolA is a valid pool that already exists

The following scenario  fails:
1.  zfs create -p poolA/a - the command fails 
   ...
   ...
   after sometime we try again
2.  zfs create -p poolA/a - the command success
3. create some file in /poolA/a
4. zfs snapshot poolA/a@snap1 -  the command success
5. verify that the file exists is in snap1 - its NOT

the root cause in code is here.
at stage 0:
1. zfs_create_ancestors() is called with " poolA/a"
2. zfs_create_ancestors calls  check_parents() with "poolA/a"
3. check_parents() returns that poolA is the longest prefix of path that is an existing dataset
4. zfs_create_ancestors() calls create_parents( "poolA/a", len( " poolA")  ) //the first argument is the path and the second is the length of the longest prefix  of the path which is already a data set (as returned from check_parents() )
5.  create_parents() does this:
    a. .zfs_create("poolA/a") //creates the data set "poolA/a" (*)
    b. zfs_mount("poolA/a")
6.zfs_mount() does the following:
....
....
    a.creates PATH for mounting the dataset "poolA/a"  on it 
    b.mount the dataset "poolA/a" on PATH
    boom the mount fails for some reason.
an ERROR is returned to the user.

at stage 1:
1. zfs_create_ancestors() is called with "poolA/a"
2. now check_parents() will return "poolA/a" as the longest prefix of path that is an existing dataset because of (*) (from 5.a)
3. nothing more will be done and a success will be returned to the user although poolA/a is not mounted on PATH.

Therefore although zfs returned success on zfs_create at stage 1, all the data that is written to PATH will not be taken into snap1, because there is no connection between the PATH and the dataset.

**Comment by behlendorf** [comment]
@roman-stratoscale thanks for filing this issue.  I'm not able to reproduce this problem, everything seems to work as expected for me.  What version of ZFS are you using?

**Comment by roman-stratoscale** [comment]
0.6.4

in order to reproduce it you need to somehow make the "zfs create -p poolA/a " command from stage 1 to fail because of a failure in mount.(lib/libzfs/libzfs_mount.c:472)

In our system we create a very large amount of datasets, so occasionally the mount actually fails.

**Comment by behlendorf** [comment]
Closing as stale.
