### ISSUE TITLE
Hang on USB disconnect

### ISSUE THREAD

**Issue by vozhyk-** [zfsonlinux/zfs#3817]
A single USB pendrive pool. When the pendrive is disconnected, ZFS doesn't notice it (shows it as `ONLINE` despite the device not existing in `/dev`), and when something tries to access it, the system hangs.
Backtraces and dmesg after triggering a panic with SysRq (the pendrive is `F0394B5D`):
https://bpaste.net/show/47a9268adc7b (3) - the drive was deliberately pulled out, and the hang happened when MPD tried to access the next song (a bit different than the others, probably because I used `sysrq-u` immediately before `sysrq-c`)
https://bpaste.net/show/504b0e6caf37 (2)
https://bpaste.net/show/0ea0fabc4a3b (1)
In (1) and (2) a disconnect and reconnect is visible some time before the hang.
In all 3 instances the ZFS processes hang when trying to access the pool.

Funtoo, linux 4.0.9-aufs with BFS, BFQ, UKSM and TuxOnIce patches.

**Comment by vozhyk-** [comment]
ZFS/SPL versions are close to 0.6.5 -- ZFS 0.6.5 - 1 commit .. 0.6.5.1

**Comment by kernelOfTruth** [comment]
Related to https://github.com/zfsonlinux/zfs/issues/3785 system freezes when zfs is waiting for disks to spin up

**Comment by behlendorf** [comment]
Resolved by 5592404 which will be cherry-picked in to 0.6.5.2 release.

**Comment by pcjc2** [comment]
This symptom (hang on USB removal) appears to be back in 0.7.1. Again, zpool showed the device as ONLINE.
