### ISSUE TITLE
systemd rocks

### ISSUE THREAD

**Issue by acrixl** [zfsonlinux/zfs#3818]
debian 8

this:
https://github.com/zfsonlinux/zfs/issues/2498

update-rc.d zfs-import remove
update-rc.d zfs-mount remove
update-rc.d zfs-share remove
update-rc.d zfs-zed remove

rm /etc/init.d/zfs-*

reboot

now all work as expected since systemd init stuff here

**Comment by FransUrbo** [comment]
This is not a support forum, so please close this.

**Comment by ggzengel** [comment]
On boot I see ZFS pool import twice. One LSB and one Systemd. They run both on same time.
I think this was not a question, it was an answer for an issue and it makes sense, until next update.
So please fix this.

With systemd there is a lot to do:
# cat zfs-import-scan.service | grep ExecStart=
ExecStart=/sbin/zpool import -d /dev/disk/by-id -aN

I think this won't work with the code above:
#ZPOOL_IMPORT_PATH="/dev/disk/by-vdev:/dev/disk/by-id"

**Comment by FransUrbo** [comment]
This still isn't a support forum. I don't see a question or an issue here. And an answer to a completely different issue is still a support thing and this isn't a support forum!

Please close this and then go read http://zfsonlinux.org/faq.html#WhereDoIReportProblems and http://zfsonlinux.org/faq.html#HowDoIReportProblems.

Then, if needed, come back and report another. The correct way.

**Comment by behlendorf** [comment]
@acrixl I'm glad to hear the systemd units work well for you.  By all means use them if that's what you prefer.  Let's chalk this up to documentation and leave it for future reference.
