### ISSUE TITLE
systemd and LSB scripts run parallel

### ISSUE THREAD

**Issue by ggzengel** [zfsonlinux/zfs#3819]
```
# uname -a
Linux xenserver1 4.1.0-0.bpo.2-amd64 #1 SMP Debian 4.1.6-1~bpo8+1 (2015-09-09) x86_64 GNU/Linux

# cat /etc/apt/sources.list.d/zfsonlinux.list 
deb http://archive.zfsonlinux.org/debian jessie main
```

On boot I see ZFS pool import twice. One LSB and one Systemd. They run both on same time.

With systemd there is a lot to do. It always import pool by ID:
#cat zfs-import-scan.service | grep ExecStart=
ExecStart=/sbin/zpool import -d /dev/disk/by-id -aN

I think this won't work with the code above:
ZPOOL_IMPORT_PATH="/dev/disk/by-vdev:/dev/disk/by-id"

Perhaps these are changes from Turbo?
The idea behind this is OK, because I like to import pools by partlabel.

**Comment by FransUrbo** [comment]
Thanx, that makes more sense. However, this then indicates that it belongs to https://github.com/zfsonlinux/pkg-zfs.

Please close this and open another at the pkg-zfs repo.

PS. I have no idea why and how that could have happened….

**Comment by ggzengel** [comment]
Moved ...
