### ISSUE TITLE
ZFS repo breaks yum provide

### ISSUE THREAD

**Issue by Zhro** [zfsonlinux/zfs#3820]
$yum provides "*/libcrypto.so*"
    Loaded plugins: auto-update-debuginfo, fastestmirror
    Loading mirror speeds from cached hostfile
     * base: mirrors.advancedhosters.com
     * epel: ftp.osuosl.org
     * epel-debuginfo: ftp.osuosl.org
     * extras: mirror.pac-12.org
     * updates: mirror.hmc.edu
    base-debuginfo/x86_64/filelists_db                                                                                                                                                         |  14 MB  00:00:12
    epel/x86_64/filelists_db                                                                                                                                                                   | 5.8 MB  00:00:01
    epel-debuginfo/x86_64/filelists_db                                                                                                                                                         | 2.6 MB  00:00:00
    extras/7/x86_64/filelists_db                                                                                                                                                               | 322 kB  00:00:00
    updates/7/x86_64/filelists_db                                                                                                                                                              | 2.7 MB  00:00:00
    http://archive.zfsonlinux.org/epel/7/x86_64/repodata/8b600e3f3eafaa15d062c878010ee810db5e114586326e0cae667aef05c497ab-filelists.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
    Trying other mirror.

     One of the configured repositories failed (ZFS on Linux for EL7),
     and yum doesn't have enough cached data to continue. At this point the only
     safe thing yum can do is fail. There are a few ways to work "fix" this:

         1. Contact the upstream for the repository and get them to fix the problem.

         2. Reconfigure the baseurl/etc. for the repository, to point to a working
            upstream. This is most often useful if you are using a newer
            distribution release than is supported by the repository (and the
            packages for the previous distribution release still work).

         3. Disable the repository, so yum won't use it by default. Yum will then
            just ignore the repository until you permanently enable it again or use
            --enablerepo for temporary usage:

                yum-config-manager --disable zfs

         4. Configure the failing repository to be skipped, if it is unavailable.
            Note that yum will try to contact the repo. when it runs most commands,
            so will have to try and fail each time (and thus. yum will be be much
            slower). If it is a very temporary problem though, this is often a nice
            compromise:

                yum-config-manager --save --setopt=zfs.skip_if_unavailable=true

    failure: repodata/8b600e3f3eafaa15d062c878010ee810db5e114586326e0cae667aef05c497ab-filelists.sqlite.bz2 from zfs: [Errno 256] No more mirrors to try.
    http://archive.zfsonlinux.org/epel/7/x86_64/repodata/8b600e3f3eafaa15d062c878010ee810db5e114586326e0cae667aef05c497ab-filelists.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found

Attempted to update repo:

    $sudo yum localinstall --nogpgcheck https://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
    Loaded plugins: auto-update-debuginfo, fastestmirror
    epel-release-7-5.noarch.rpm                                                                                                                                                                |  14 kB  00:00:00
    Examining /var/tmp/yum-root-DlBwGM/epel-release-7-5.noarch.rpm: epel-release-7-5.noarch
    /var/tmp/yum-root-DlBwGM/epel-release-7-5.noarch.rpm: does not update installed package.
    Nothing to do

    $sudo yum localinstall --nogpgcheck http://archive.zfsonlinux.org/epel/zfs-release.el7.noarch.rpm
    Loaded plugins: auto-update-debuginfo, fastestmirror
    zfs-release.el7.noarch.rpm                                                                                                                                                                 | 4.3 kB  00:00:00
    Examining /var/tmp/yum-root-DlBwGM/zfs-release.el7.noarch.rpm: zfs-release-1-2.el7.centos.noarch
    /var/tmp/yum-root-DlBwGM/zfs-release.el7.noarch.rpm: does not update installed package.
    Nothing to do

Had to disable ZFS repo to complete yum provides.

**Comment by behlendorf** [comment]
@Zhro I'm not able to reproduce this on a CentOS 7 VM.  Have you tried clearing the yum cache and trying again.  `yum clean all && yum update`.

**Comment by Zhro** [comment]
It seems to be working now. I haven't changed anything.
