### ISSUE TITLE
Host freezes under 0.6.5.1, ubuntu vivid

### ISSUE THREAD

**Issue by adrienkohlbecker** [zfsonlinux/zfs#3832]
Hello,

I've updated my server last week, switching from Ubuntu 14.10 to 15.04, and from a custom 3.16 kernel to mainstream 3.19. My zfs version was subsequently updated to 0.6.5 from 0.6.3. This was an online upgrade, no reinstallation from scratch.

Since then, I'm getting intermittent lockups that completely freeze the system. It does not (until now) happen when the server is lightly used : only when I have a VM running and/or a docker container running.
In this case, I get around 30min to a couple hours of uptime before the host freezes and I have to force reset it.

I have updated to 0.6.5.1 yesterday, but it did not improve the problem.
I managed to take the following screenshots from the remote KVM, but that's all I have, since the display is usually sleeping when it happens, and there is nothing in syslog

<img width="714" alt="screenshot 2015-09-23 10 38 41" src="https://cloud.githubusercontent.com/assets/70469/10084964/65b0b480-6306-11e5-83f6-45f2d6b66585.png">
<img width="726" alt="screenshot 2015-09-23 10 38 50" src="https://cloud.githubusercontent.com/assets/70469/10084968/6b45d06a-6306-11e5-89b8-56fa278565a9.png">

This is a bit above my competencies but I'm willing to help with debug if needed. 
Otherwise, is there a way for me to install 0.6.4 or 0.6.3 while this gets sorted out ? The packages have been removed from the ppa

Best,

**Comment by behlendorf** [comment]
@adrienkohlbecker this is a duplicate on #3652 and on the short list of things to be fixed in the next point release.  As a short term workaround you can try setting `echo 0 > /sys/module/spl/parameters/spl_taskq_thread_dynamic` which has been reported to help.  I'm not sure about the easier way to roll back packages on Ubuntu.

**Comment by adrienkohlbecker** [comment]
Ah, good to know. I skimmed the list of issues and didn't think this was related to removing disks. I'll try the workaround, thanks!

**Comment by behlendorf** [comment]
Resolved by 5592404 which will be cherry-picked in to 0.6.5.2 release.
