### ISSUE TITLE
systemd: add Conflicts=zfs-import.service

### ISSUE THREAD

**Issue by ggzengel** [zfsonlinux/zfs#3837]
For systems with systemd in sysv init compatibility mode you have to prevent that services in /etc/init.d will be executed if there is a equivalent in systemd.
There is zfs-import without a corresponding systemd service. You have to add 'Conflicts=zfs-import.service' to zfs-import-cache.service and zfs-import-scan.service.

 ```
[Unit]
Description=Import ZFS pools by cache file
DefaultDependencies=no
Requires=systemd-udev-settle.service
After=systemd-udev-settle.service
After=cryptsetup.target
ConditionPathExists=/etc/zfs/zpool.cache
Conflicts=zfs-import.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStartPre=/sbin/modprobe zfs
ExecStart=/sbin/zpool import -c /etc/zfs/zpool.cache -aN
ExecStop=/sbin/zpool export -a
```

**Comment by behlendorf** [comment]
@ggzengel could you please open a pull request with the proposed fix.  It makes is easier for me to merge, get it reviewed, and properly credit the author.

**Comment by ggzengel** [comment]
First time I made this with github. Now we have #3838.

**Comment by FransUrbo** [comment]
I'm slowly starting to understand what you're been on about for the last couple of days :).

So you're saying that that <code>zfs-import.service</code> is auto generated from the <code>/etc/init.d/zfs-import</code> file. And when you install both the SYSV scripts **and** the systemd services files on the same system **and** <code>systemd</code> is in charge of starting services (not <code>init</code>), this auto generated service file conflicts with the two existing ones, the <code>zfs-import-cache.service</code> and <code>zfs-import-scan.service</code>??

**Comment by ggzengel** [comment]
@FransUrbo Exactly. You got it. That's the way systemd will make smooth migration.

I googled about jessie and systemd: Jessie will always use systemd on normal install and will use systemd on upgrade from Wheezy to Jessie.

**Comment by ggzengel** [comment]
I hope I don't spam too much.
Is this now useful?

**Comment by FransUrbo** [comment]
Very much so, thanx!

**Comment by ggzengel** [comment]
better solution in #3839
