### ISSUE TITLE
0.6.4->0.6.5.1: df shows disk full, 0 space available

### ISSUE THREAD

**Issue by limelime** [zfsonlinux/zfs#3841]
After I rebuilt my live debian 8.2 system to use 0.6.5.1, running `df -k` show 100% full, **Available** space is 0. Some pools have GB of space left but the **Available** column shows 0. Whereas in v0.6.4, everything is fine. I'm running my system from USB key. I installed zfsonlinux as described from http://zfsonlinux.org/debian.html.

**Comment by behlendorf** [comment]
From the [release notes](https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.6.5):

```
Default reserved space was increased from 1.6% to 3.3% of total pool capacity.
This default percentage can be controlled through the new spa_slop_shift module
option, setting it to 6 will restore the previous percentage.
```

**Comment by limelime** [comment]
Just to let you know, there is discrepancy in the percentage number:
* Release note: 3.3%
* In source code comment 3.2%
* The formula: 1/(2^5)*100 = 3.125%

https://github.com/zfsonlinux/zfs/search?utf8=%E2%9C%93&q=3.2%25

**Comment by behlendorf** [comment]
@limelime thanks for pointing that out, I've updated the release notes accordingly.
