### ISSUE TITLE
Debian: How to install specific version of zfs?

### ISSUE THREAD

**Issue by limelime** [zfsonlinux/zfs#3843]
Debian: How to install specific version of zfs?
I don't want to always get the latest version from the repository.

**Comment by Amitie10g** [comment]
I agree, I already ask for this packaging issue. In seevral cases is important to keep previous version to avoid broken installations (as happened sometimes).

**Comment by FransUrbo** [comment]
This belongs to https://github.com/zfsonlinux/pkg-zfs. Please close and reopen a new issue in that repo.

I started to remove ancient and old versions from the repository because it became to cluttered.

If you need/must have an older version, currently you'll have to build from source.
