### ISSUE TITLE
System hangs during boot if root zfs volume has children with zfs 0.6.5

### ISSUE THREAD

**Issue by dclaisse** [zfsonlinux/zfs#3845]
Context: Debian Jessie, upgraded from zfs 0.6.4 to 0.6.5.1.
System is comprised of a root pool (rpool) on an 128GB SSD + 12TB data pool (backup)

Root volume is rpool/os, and it has a child rpool/os/tmp, which is mounted on /tmp

With zfs 0.6.5.1, system hangs during boot, log showing the following:

Begin: Using rpool/os as root.    ... done.
Begin: Mounting filesystem rpool/os
rpool/os/tmp    ...
[hangs]

It seems that there is an IFS issue in a for loop in /etc/zfs/zfs-functions (function recursive_mount_filesystems), items are not separated correctly.

I patched wildly /etc/zfs/zfs-functions to add a modified IFS around line 420, adding the export IFS line:

```
        export IFS="
"
        # Go through the complete list (recursivly) of all filesystems
        # below the first (root) dataset.
        filesystems=$("${ZFS}" list -oname -tfilesystem -H -r "${fs}")
        for f in ${filesystems} ${ZFS_INITRD_ADDITIONAL_DATASETS}
```

Ran update-initramfs -u -k all, and since then my system boots fine.

Feel free to ask me any corrective test.

Damien

**Comment by woffs** [comment]
Same problem here, system continues to boot by pressing Ctrl-D

**Comment by dclaisse** [comment]
Issue doesn't occur anymore since latest 0.6.5.2 initramfs fixes.
