### ISSUE TITLE
zfs-zed.service: Starting ZFS Event Daemon failed

### ISSUE THREAD

**Issue by limelime** [zfsonlinux/zfs#3847]
After installing v0.6.5.1, on  boot time, I noticed that zfs-zed.service is failing. On v0.6.4, I didn't see this error. I don't know what zfs-zed.service is nor did I configure it. I'm running Debian 8.2.

**Comment by FransUrbo** [comment]
It is highly likely that this is fixed by #3824.

**Comment by behlendorf** [comment]
Closing as out of date.
