### ISSUE TITLE
zed: no subject in email when using exim

### ISSUE THREAD

**Issue by Finkregh** [zfsonlinux/zfs#3848]
I use exim as MTA which can not send e-mail from the commandline while specifying the subject as argument.

See `-bm` at http://www.exim.org/exim-html-current/doc/html/spec_html/ch-the_exim_command_line.html
> This option runs an Exim receiving process that accepts an incoming, locally-generated message on the standard input. The recipients are given as the command arguments (except when -t is also present – see below). Each argument can be a comma-separated list of RFC 2822 addresses. This is the default option for selecting the overall action of an Exim call; it is assumed if no other conflicting option is present.

It would be nice if i could turn on a switch that puts the mails' subject into the data coming from stdin. (see https://github.com/zfsonlinux/zfs/blob/master/cmd/zed/zed.d/zed-functions.sh#L263 )

**Comment by Finkregh** [comment]
oh well, or i could install 'mailutils' ... :facepalm:

close this if you want :)

**Comment by behlendorf** [comment]
Let's go with the 'mailutils' solution for now.  But this kind of behavior is something we should be aware of!
