### ISSUE TITLE
Feature Request: Add Brotli as new compression algorithm.

### ISSUE THREAD

**Issue by dreh23** [zfsonlinux/zfs#3849]
Googles Suisse departement invented a new compression algorithm. See
http://google-opensource.blogspot.pt/2015/09/introducing-brotli-new-compression.html

**Comment by DeHackEd** [comment]
Duplicate of #3844 

Note that Brotli has a narrow scope. It might do good for compressing logs or a web storage space directory, but doesn't do nearly as well as a generic algorithm for arbitrary inputs. There are scenarios where it loses to LZMA/XZ.

**Comment by behlendorf** [comment]
Closing as duplicate of #3844.
