### ISSUE TITLE
0.6.5.1 - I/O timeout during disk spin up

### ISSUE THREAD

**Issue by speedst3r** [zfsonlinux/zfs#3856]
I have an 8-disk raidz2 vdev where the component disks are put in standby after being idle for 15 minutes. With 0.6.5.1 it appears that something has changed that causes I/O requests to timeout while waiting for the drives to spin up, with the following in the syslog:

> Sep 30 11:45:41 sook kernel: [ 1604.793964] sd 0:0:4:0: [sdf] FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_OK
> Sep 30 11:45:41 sook kernel: [ 1604.793969] sd 0:0:4:0: [sdf] CDB:
> Sep 30 11:45:41 sook kernel: [ 1604.793972] Read(16): 88 00 00 00 00 00 9c 0e 65 c8 00 00 00 08 00 00
> Sep 30 11:45:41 sook kernel: [ 1604.793984] blk_update_request: I/O error, dev sdf, sector 2618189256

For each recurrence the component device differs as does the sector (i.e. it's not a faulty drive), and sometimes errors for two different devices are logged in the same request. Once the error occurs the system is inaccessible (ping replies, but other services open a connection with zero data) and needs to be reset. Individual drives can be woken up with dd but when attempting to access the filesystems on the pool the I/O error occurs.

Downgraded to 0.6.4.2 and this issues does not occur.

Steps to reproduce:
1. Put disks in vdev in standby (e.g. hdparm -y /dev/sd[b-i])
2. Attempt to access a filesystem in that pool
3. Observe errors

System is running Ubuntu 14.04, kernel 3.13.0-61 (tried -62, -63, -65 and the vivid enablement kernel with no difference).

**Comment by mountassir** [comment]
I think this is similar to #3785, a fix will be in the 0.6.5.2 release.

**Comment by kernelOfTruth** [comment]
yes, which should be today or tomorrow according to @behlendorf

**Comment by behlendorf** [comment]
Yes, this should be addressed in 0.6.5.2 which is available now.  It'll take a little while to work it's way in to the distributions but you can always download it directly.  Definitely let us know if it does or doesn't resolve the issue.

https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.6.5.2

**Comment by speedst3r** [comment]
Thanks all, I only checked the open issues - not closed!

**Comment by drozdu** [comment]
I am still experiencing this error in ZFS version 0.6.5.3, linux arch, kernel 4.2.5. 
Using IBM ServeRAID M1015 in IT mode (SAS2008).
<blockquote><p>
gru 25 01:27:49 nas kernel: sd 6:0:0:0: [sdf] UNKNOWN(0x2003) Result: hostbyte=0x00 driverbyte=0x00<br>
gru 25 01:27:49 nas kernel: sd 6:0:0:0: [sdf] CDB: opcode=0x2a 2a 00 65 23 23 28 00 00 08 00<br>
gru 25 01:27:49 nas kernel: blk_update_request: I/O error, dev sdf, sector 1696801576<br>
gru 25 01:27:49 nas kernel: sd 6:0:2:0: [sdh] UNKNOWN(0x2003) Result: hostbyte=0x00 driverbyte=0x00<br>
gru 25 01:27:49 nas kernel: sd 6:0:2:0: [sdh] CDB: opcode=0x2a 2a 00 65 23 23 28 00 00 08 00<br>
gru 25 01:27:49 nas kernel: blk_update_request: I/O error, dev sdh, sector 1696801576<br>
gru 25 01:27:49 nas kernel: sd 6:0:3:0: [sdi] UNKNOWN(0x2003) Result: hostbyte=0x00 driverbyte=0x00<br>
gru 25 01:27:49 nas kernel: sd 6:0:3:0: [sdi] CDB: opcode=0x2a 2a 00 65 23 23 30 00 00 08 00<br>
gru 25 01:27:49 nas kernel: blk_update_request: I/O error, dev sdi, sector 1696801584<br>
gru 25 01:28:02 nas kernel: sd 6:0:1:0: [sdg] UNKNOWN(0x2003) Result: hostbyte=0x00 driverbyte=0x00<br>
gru 25 01:28:02 nas kernel: sd 6:0:1:0: [sdg] CDB: opcode=0x2a 2a 00 88 1a 2c b8 00 00 08 00<br>
gru 25 01:28:02 nas kernel: blk_update_request: I/O error, dev sdg, sector 2283416760<br>
gru 25 01:28:02 nas zed[21198]: eid=426 class=delay pool=dysk1<br>
gru 25 01:28:02 nas zed[21200]: eid=427 class=io pool=dysk1<br>
gru 25 01:28:02 nas zed[21223]: eid=428 class=delay pool=dysk1<br>
gru 25 01:28:02 nas zed[21225]: eid=429 class=io pool=dysk1<br>
gru 25 01:28:02 nas zed[21248]: eid=430 class=delay pool=dysk1<br>
gru 25 01:28:02 nas zed[21250]: eid=431 class=io pool=dysk1<br>
gru 25 01:28:02 nas zed[21273]: eid=432 class=io pool=dysk1<br>
gru 25 01:28:02 nas zed[21296]: eid=433 class=delay pool=dysk1<br>
gru 25 01:28:02 nas zed[21298]: eid=434 class=io pool=dysk1<br>
</p></blockquote>

**Comment by flo82** [comment]
i'm still experiencing this bug with 0.6.5.6 on Ubuntu 16.04. with same chipset (SAS2008).

This is what i did:
created a zpool on the device and sent it to sleep (hdparm -y). Then started writing a file to it. Result was:
[59526.359997] sd 0:0:1:0: [sda] FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_OK
[59526.360003] sd 0:0:1:0: [sda] CDB:
[59526.360006] Read(16): 88 00 00 00 00 00 31 28 fd 58 00 00 00 08 00 00
[59526.360022] blk_update_request: I/O error, dev sdc, sector 824769380

i created a ext3 filesystem on the device and sent it to sleep. Then started the fily copy again. Result: No messages in dmesg. 

I also checked the original file with the copied one - they are identical. So this bug has to do with ZFS and is not closed.Any Ideas? Need further Information?
