### ISSUE TITLE
Cannot use partition aliases in vdev_id.conf

### ISSUE THREAD

**Issue by sparksh** [zfsonlinux/zfs#3859]
When pools are assembled from partitions, vdev_id.conf  aliases do not work. The directory /dev/disk/by-vdev is not created because the associated udev rule for parsing vdev_id.conf is never called.

Adding one line to this rule will fix the problem:

69-vdev.rules

It is located in the source tree at:

udev/rules.d/

The line that invokes the vdev_id script matches a DEVTYPE of "disk"
A simple fix is to match "disk" and "partition":
...
ENV{DEVTYPE}=="disk", IMPORT{program}="/usr/lib/udev/vdev_id -d %k"
ENV{DEVTYPE}=="partition", IMPORT{program}="/usr/lib/udev/vdev_id -d %k"
...

**Comment by behlendorf** [comment]
@sparksh good point, could you open a pull request with the proposed fix so we can merge your fix.

**Comment by behlendorf** [comment]
@sparksh I've opened PR #5266 with your proposed fix for review.
