### ISSUE TITLE
Null pointer crash in kernel after enabling recordsize=1M

### ISSUE THREAD

**Issue by unya** [zfsonlinux/zfs#3861]
kernel 4.1.5 gentoo aufs
on amd64 machine
disk - samsung 850 Pro 512G
Steps to reproduce: run big emerge job, like removing gcc or world update

dump of logs from pstore: https://dl.dropboxusercontent.com/u/9540080/crashlog-1.tar

**Comment by behlendorf** [comment]
This doesn't look related to the record size.  If your still seeing this please try setting the module option `spl_taskq_thread_dynamic=0` and see if that resolves the issue.

**Comment by behlendorf** [comment]
Set `spl_taskq_thread_dynamic=0` to default in 0.6.5.3 until root cause is explained.
