### ISSUE TITLE
0.6.5 Regression: Exporting the pool on shutdown in dracut dirties vdev labels and pollutes zpool history.

### ISSUE THREAD

**Issue by ryao** [zfsonlinux/zfs#3875]
The new dracut code that does pool export on shutdown in dracut dirties the vdev labels, which breaks `zpool import -T` and `zpool import -F` because the kernel cannot distinguish between a vdev configuration change and the export. It also pollutes the `zpool history` with commands that the user never actually ran on the pool.

I did not pay too much attention to what was happening in the dracut module because people on Gentoo use genkernel and people at work do not worry about / on ZFS, but I am starting to pay attention because the incorrect behavior could make catastrophic failures that could be recovered with some minor assistance from the ZoL project irrecoverable without major assistance.

I tried export on shutdown in 2012 in Gentoo and abandoned it after discovering the problems it caused:

https://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/sys-fs/zfs/files/zfs-shutdown?view=log&pathrev=MAIN

The export on shutdown behavior in the dracut zfs module should be removed.

**Comment by behlendorf** [comment]
@ryao I don't believe this is quite so clear cut.  Cleanly exporting the pool resolves a whole raft of other issues which will be reintroduced if we revert this.  See commit 07a3312f170ac56cb480b0df9fdf4c83f116b59b.

And while it's true that  cleanly exporting the pool complicates using `zpool import -T` and `zpool import -F` I'd argue that's an issue with those utilities.  We should fix them.

**Comment by ryao** [comment]
@behlendorf All of those issues would be correctedly addressed by the the behavior suggested in #3876 without requiring any divergence from Illumos.

**Comment by ryao** [comment]
@behlendorf I am rewriting the dracut ZFS module to fix this issue, #3876 and the unreported issue of pools faulting on import when a vdev is added. The WIP code is in my git repository's dracut branch:

https://github.com/ryao/zfs/tree/dracut

I will open a pull request after it has been properly tested.

**Comment by ryao** [comment]
Pull request #3879 is opened with a tentative fix.

**Comment by FransUrbo** [comment]
This isn't a regression. It's been doing this "for years" and as far as I can tell, no one have ever complained about this - "if it ain't broken, don't fix it".

**Comment by ryao** [comment]
This is a regression. I tried this technique in 2012 and abandoned it because it caused problems such as this. ZFS scripts should never execute an export operation.

**Comment by ryao** [comment]
@behlendorf As I said in #3800, #3889 appears to have occurred where two nodes had access to the same pools over SAS and they both tried importing the pools at the same time, causing pool corruption. This happened on CentOS, but on distributions where the "import all pools" behavior is used in conjunction with either export at shutdown, pool corruption will occur, even if the default spl_hostid is changed from 0 to prevent it.

**Comment by FransUrbo** [comment]
The export isn't the problem obviously! it's the import.

**Comment by ryao** [comment]
@FransUrbo Being at risk for things going south by default is something I would expect from btrfs. We should not be doing it.

**Comment by behlendorf** [comment]
Proposed fix in #5238

**Comment by behlendorf** [comment]
Closing.  Commit 7e8a2d0b755ea67291d3f576069706e43abc5e31 prevent dracut from dirtying label on export.
