### ISSUE TITLE
dracut should verbatim import from cachefile

### ISSUE THREAD

**Issue by ryao** [zfsonlinux/zfs#3876]
Doing an import at boot dirties the vdev labels, which breaks zpool import -T and zpool import -F because the kernel cannot distinguish between a vdev configuration change and the export. It also pollutes the zpool history with commands that the user never actually ran on the pool.

Dracut's boot behavior should be changed to mimic genkernel's zfs branch:

https://gitweb.gentoo.org/proj/genkernel.git/tree/defaults/linuxrc?h=zfs#n111
https://gitweb.gentoo.org/proj/genkernel.git/tree/defaults/linuxrc?h=zfs#n307
https://gitweb.gentoo.org/proj/genkernel.git/tree/defaults/initrd.scripts?h=zfs#n1027
https://gitweb.gentoo.org/proj/genkernel.git/tree/defaults/linuxrc?h=zfs#n525

That has not been merged into genkernel because I have so far only implemented partial support for /dev/disk/by-id/\* symlinks in mdev and the other /dev/disk/by-\* symlinks are yet to be implemented. Given that dracut uses udev, this should not be an issue for dracut in adopting the new genkernel behavior.

Note that how the boot process works will need further changes in the future when a syntax for passing the pool GUID and vdevs by-path from the kernel to the bootloader from the kernel commandline is developed, but until then, this is the way forward. I plan to retain the behavior implemented in the current zfs branch as a legacy option when the boot process changes are ready in Gentoo to minimize pain when dealing with existing installations.

**Comment by ryao** [comment]
Pull request #3879 is opened with a tentative fix.

**Comment by Rudd-O** [comment]
I believe this is the specific behavior you refer to, w.r.t. dirtying up the pool labels:

https://gitweb.gentoo.org/proj/genkernel.git/tree/defaults/initrd.scripts?h=zfs#n1053

**Comment by Rudd-O** [comment]
zpool import does not have flag -a — from that file:

```
/sbin/zpool import -c /etc/zfs/zpool.cache -aN
```

**Comment by Rudd-O** [comment]
What about that process prevents dirtying up the pool labels?
