### ISSUE TITLE
Fedora repository doesn't pull in enough deps to build the kernel modules

### ISSUE THREAD

**Issue by peachpine** [zfsonlinux/zfs#3881]
Hello,
I normally compile from source but I tried using the Fedora repository on a fresh install and found that  "dnf install zfs" doesn't pull in enough dependencies to build dkms-kernel or dkms-spl.

The only way to get it to work is to manually include all the dependencies like so:
dnf install zlib-devel libuuid-devel libblkid-devel libselinux-devel parted lsscsi autoconf automake libtool zfs

**Comment by FransUrbo** [comment]
@peachpine Could you test my two PRs and see if they solve the problem?

**Comment by FransUrbo** [comment]
The spl PR should be enough, so I've closed the zfs one...

**Comment by behlendorf** [comment]
@peachpine which version of Feodra?  I assume Feodra 22 or newer since that's when they cut over from yum to dnf.  It does sound like there's a problem but the critical dependencies should already be listed.
