### ISSUE TITLE
Missing free space after upgrade to 0.6.5.1

### ISSUE THREAD

**Issue by ldonzis** [zfsonlinux/zfs#3885]
I don't know if this is directly related, but I just upgraded a system from 0.6.4 to 0.6.5.1 and the upgraded the pools.  I did this on two other systems and everything was fine, although the space usage appears to be somewhat different now.

Anyway, on the system, in question the filesystems are completely out of space:

root@ss3:~# zfs list backups
NAME      USED  AVAIL  REFER  MOUNTPOINT
backups  12.6T      0  14.5G  /backups

So I deleted some files and a few snapshots but that did not change the available space, it's still at zero and nothing can be created.  However, as I deleted the files and snapshots, the pool would show free space:

root@ss3:~# zpool list
NAME      SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
backups  16.2T  15.8T   483G         -    34%    97%  1.00x  ONLINE  -

But for some reason the free space is not reflected back into the filesystems.

I've tried a few random things, such as unmounting/mounting, exporting/importing, but none of that helped.

Thanks very much,
lew

**Comment by woffs** [comment]
See #3841

**Comment by ldonzis** [comment]
Thanks very much.  That’s so obvious, I apologize for the silly question.

lew
