### ISSUE TITLE
Build/ dkms issue Fedora 22

### ISSUE THREAD

**Issue by dvwiz** [zfsonlinux/zfs#3886]
Getting the following errors on dnf install zfs. Any advice? 

Dependencies resolved.
===================================== Package
     Arch   Version        Repository                                Size
=====================================Installing:
 libnvpair1
     x86_64 0.6.5.2-1.fc22 zfs  33 k
 libuutil1
     x86_64 0.6.5.2-1.fc22 zfs  37 k
 libzfs2
     x86_64 0.6.5.2-1.fc22 zfs 119 k
 libzpool2
     x86_64 0.6.5.2-1.fc22 zfs 413 k
 spl x86_64 0.6.5.2-1.fc22 zfs  30 k
 spl-dkms
     noarch 0.6.5.2-1.fc22 zfs 432 k
 zfs x86_64 0.6.5.2-1.fc22 zfs 333 k
 zfs-dkms
     noarch 0.6.5.2-1.fc22 zfs 1.8 M

Transaction Summary
=====================================Install  8 Packages

Total download size: 3.2 M
Installed size: 16 M
Is this ok [y/N]: y
Downloading Packages:
(1/8  32 kB/s |  37 kB     00:01
(2/8): libnvpair1-0.6.5.2-1.f  18 kB/s |  33 kB     00:01
(3/8): zfs-0.6.5.2-1.fc22.x86 172 kB/s | 333 kB     00:01
(4/8): spl-0.6.5.2-1.fc22.x86  44 kB/s |  30 kB     00:00
(5/8): libzpool2-0.6.5.2-1.fc 231 kB/s | 413 kB     00:01
(6/8): libzfs2-0.6.5.2-1.fc22  35 kB/s | 119 kB     00:03
(7/8): zfs-dkms-0.6.5.2-1.fc2 353 kB/s | 1.8 MB     00:05
(8/8): spl-dkms-0.6.5.2-1.fc2  78 kB/s | 432 kB     00:05
--------------------------------------------------------------Total                         358 kB/s | 3.2 MB     00:09     Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Installing  : libuutil1-0.6.5.2-1.fc22.x86_64           1/8   Installing  : libnvpair1-0.6.5.2-1.fc22.x86_64          2/8   Installing  : libzpool2-0.6.5.2-1.fc22.x86_64           3/8   Installing  : spl-dkms-0.6.5.2-1.fc22.noarch            4/8 Loading new spl-0.6.5.2 DKMS files...
Building for 4.1.8-200.fc22.x86_64
Building initial module for 4.1.8-200.fc22.x86_64
configure: error: in `/var/lib/dkms/spl/0.6.5.2/build':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
Error! Bad return status for module build on kernel: 4.1.8-200.fc22.x86_64 (x86_64)
Consult /var/lib/dkms/spl/0.6.5.2/build/make.log for more information.
warning: %post(spl-dkms-0.6.5.2-1.fc22.noarch) scriptlet failed, exit status 10
Non-fatal POSTIN scriptlet failure in rpm package spl-dkms
Non-fatal POSTIN scriptlet failure in rpm package spl-dkms
  Installing  : spl-0.6.5.2-1.fc22.x86_64                 5/8   Installing  : zfs-dkms-0.6.5.2-1.fc22.noarch            6/8 Loading new zfs-0.6.5.2 DKMS files...
Building for 4.1.8-200.fc22.x86_64
Building initial module for 4.1.8-200.fc22.x86_64
configure: error: in `/var/lib/dkms/zfs/0.6.5.2/build':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
Error! Bad return status for module build on kernel: 4.1.8-200.fc22.x86_64 (x86_64)
Consult /var/lib/dkms/zfs/0.6.5.2/build/make.log for more information.
warning: %post(zfs-dkms-0.6.5.2-1.fc22.noarch) scriptlet failed, exit status 10
Non-fatal POSTIN scriptlet failure in rpm package zfs-dkms
Non-fatal POSTIN scriptlet failure in rpm package zfs-dkms
  Installing  : libzfs2-0.6.5.2-1.fc22.x86_64             7/8   Installing  : zfs-0.6.5.2-1.fc22.x86_64                 8/8   Verifying   : zfs-0.6.5.2-1.fc22.x86_64                 1/8   Verifying   : libnvpair1-0.6.5.2-1.fc22.x86_64          2/8   Verifying   : libuutil1-0.6.5.2-1.fc22.x86_64           3/8   Verifying   : libzfs2-0.6.5.2-1.fc22.x86_64             4/8   Verifying   : libzpool2-0.6.5.2-1.fc22.x86_64           5/8   Verifying   : spl-0.6.5.2-1.fc22.x86_64                 6/8   Verifying   : zfs-dkms-0.6.5.2-1.fc22.noarch            7/8   Verifying   : spl-dkms-0.6.5.2-1.fc22.noarch            8/8 
Installed:
  libnvpair1.x86_64 0.6.5.2-1.fc22                              libuutil1.x86_64 0.6.5.2-1.fc22                               libzfs2.x86_64 0.6.5.2-1.fc22                                 libzpool2.x86_64 0.6.5.2-1.fc22                               spl.x86_64 0.6.5.2-1.fc22                                     spl-dkms.noarch 0.6.5.2-1.fc22                                zfs.x86_64 0.6.5.2-1.fc22                                     zfs-dkms.noarch 0.6.5.2-1.fc22                              
Complete!

**Comment by behlendorf** [comment]
I haven't played with `dnf` much yet but it sure looks like its dependency solver for some reason isn't installing the gcc and make packages.  Can you check if they're already installed on your system?  The zfs-dkms package has a dependency on them.

```
Requires:       gcc, make, perl

```

**Comment by dvwiz** [comment]
Those 3 things are definitely installed. ZFS was working previously on this system. I think this happened after a kernel upgrade.

**Comment by dvwiz** [comment]
Sorry, I'm kind of new to bug reporting. I tried installing 0.6.5.1 and there was no issue. So this issue, as reported above, is a Fedora 22 + zfs 0.6.5.2 problem as far as I know. Am I in the right place, or could this be an issue for Fedora?

**Comment by behlendorf** [comment]
@dvwiz you're definitely in the right place.  But commit a61b38c is the only packaging change between 0.6.5.1 and 0.6.5.2 and it doesn't touch any of the dependencies.  This may be an issue with the repository itself we'll refresh it shortly and see if that resolves the issue.

**Comment by dvwiz** [comment]
0.6.5.2 builds with no issues now. Thanks!

**Comment by behlendorf** [comment]
@dvwiz great thanks for following up.
