### ISSUE TITLE
High Load Average and IO hangs on file operation (copy)

### ISSUE THREAD

**Issue by alxdlv** [zfsonlinux/zfs#3897]
Host: 
CPU 2 x Xeon X5660 2.8GHz (2 sockets, 6 cores), Hyper-Threading enabled (total 24 CPUs), Debian Wheezy, 2.6.32-41 kernel (Proxmox), ~10 KVM machines (almost idle) stored as .img on dataset running with cache=writeback (some RAW, some qcow2)

Disks used (1x SSD for cache/logs, 2x2 3.5" HDD 7200rpm, 128MB Buffer, SAS2.0, 3GBit)

`# free -m`
`total       used       free     shared    buffers     cached`
`Mem:         88556      72314      16242          0        202        249`
`-/+ buffers/cache:      71863      16693`
`Swap:        29695          0      29695`
meminfo: http://pastebin.com/6BJLP0DZ
lsiutil dump state: http://pastebin.com/n07jr7sB
dmesg - NO errors/stack traces
**ZFS related details (slabtop, arcstats, zfs get all, /proc/buddyinfo, iostat)**: http://pastebin.com/skCzGzJ2

For example, before copy:
`load average: 1.94, 2.59, 2.99`
While copying:
`load average: 15.10, 7.73, 6.09`

`02:00.0 SCSI storage controller: LSI Logic / Symbios Logic SAS1064ET PCI-Express Fusion-MPT SAS (rev 08)`
NO Hardware RAID, Write Cache: enabled

perf top:
![perf top](http://i.imgur.com/zSUUJsF.png)

**Comment by travkin** [comment]
Specifically transferred ZIL (logs) to SSD in the hope of solving problems with the load average, but no result.

Yes, ashift is 9 on a single pool, but it but despite that there should be such a difference or problem.

**Comment by ryao** [comment]
ashift=9 would not account for the high load averages. Your configuration has plenty of overhead. I would suggest switching to cache=none (let ZFS worry about caching writes), putting the VMs on either a zvol with volblocksize=4K or a dataset with recordsize=4K (setting this on the dataset will not convert existing files) and updating to 0.6.5.2.

**Comment by xalxd** [comment]
ZFS is already updated to 0.6.5.2.
recordsize=4K can make a big difference in this case?
I can't use cache=none as KVM machine won't start. Only cache=writeback.
And the problem appears on host copy (not guest)
Also, I have almost same behaviour even if I copy files in other empty dataset that isn't "KVM powered".

**Comment by xalxd** [comment]
Setting recordsize=4K instead of 128K for dataset and cp/mv shows significant decrease in performance on write (from ~50 MB/s to ~2-3 MB/s, yeah). Problem somewhere deeper.

**Comment by paulkramme** [comment]
I experience the same issue.
