### ISSUE TITLE
update from zfs 0.6.4.2 to zfs 0.6.5.1,random I/O performance not improved

### ISSUE THREAD

**Issue by dsw0350** [zfsonlinux/zfs#3898]
hello
When i use fio to test the performance of zfs 0.6.4.2 and zfs 0.6.5.1, i find sequential I/O performance is improved, but random I/O performance is not.
An example fio command i used as follows:
     fio -filename=/dev/zvol/pool/volume -direct=1 -iodepth=1 -thread -rw=randread -ioengine=psync -bs=4k -size=200G -numjobs=15 -runtime=60 -group_reporting -name=randread_4k
The results as follow:
                                      mbps                                                    iops
bs          rw                 6.4.2               6.5.1                              6.4.2                6.5.1
4k        randread       2667.7KB/s      1688.3KB/s                        666                   642
4k        randwrite      1245.5KB/s       1141.7KB/s                        311                  285
16k      randread       5085.9KB/s       4856.5KB/s                       317                  303
16k      randwrite       22222KB/s        27667KB/s                        388                  1729
64k      randread       13377KB/s         16548KB/s                       209                   258
64k      randwrite       81783KB/s         45120KB/s                      1277                  704

linux kernal version:3.14.50-v64

Best regards

**Comment by ryao** [comment]
What drives are you using and what is the pool configuration?

The random read performance should improve when the zfetch improvements from Illumos are merged. The random write performance should improve when someone writes code to avoid synchronous read-modify-write on uncached buffers.

**Comment by dsw0350** [comment]
zpool: one raidz vdev with 4 disks, ashift=12, almost the default settings.
volume: log bias=throughput dedup=off compression=off copy=1 sync=standard

drivers? Do you mean the mpt2sas driver?

Thanks.

**Comment by wangdbang** [comment]
Hi ryao, 

    Would you like to give some presdu codes about the random write performance? Or give more suggestion about this, i'd like to try about this in some days later.

Best Regards,
Daobang Wang.
