### ISSUE TITLE
Failed to start ZFS file system shares.

### ISSUE THREAD

**Issue by fxception** [zfsonlinux/zfs#3919]
This also shows up sometimes upon booting

![ss 2015-10-13 at 02 19 57](https://cloud.githubusercontent.com/assets/9167635/10455237/094abc32-716f-11e5-8b66-1f92a48408ae.jpg)

This shows up when typing the command "systemctl status zfs-share.service"
![ss 2015-10-13 at 02 21 07](https://cloud.githubusercontent.com/assets/9167635/10455253/11122c7a-716f-11e5-8e8b-7425bd6f0182.png)

root@fxception:~# lsb_release -da
No LSB modules are available.
Distributor ID: Debian
Description: Debian GNU/Linux 8.2 (jessie)
Release: 8.2
Codename: jessie
root@fxception:~# hostnamectl
Static hostname: fxception
Icon name: computer-desktop
Chassis: desktop
Operating System: Debian GNU/Linux 8 (jessie)
Kernel: Linux 3.16.0-4-amd64
Architecture: x86-64
root@fxception:~#

**Comment by FransUrbo** [comment]
Please see https://github.com/zfsonlinux/zfs/issues/3918#issuecomment-147868182 for possible reason to this.
