### ISSUE TITLE
failed to load ZFS stack

### ISSUE THREAD

**Issue by beninhos** [zfsonlinux/zfs#3922]
ubuntu 14.04 64 bit ZFS on linux.

After a reboot and kernel update;

beninho@Jaguar:~$ sudo zpool status
The ZFS modules are not loaded.
Try running '/sbin/modprobe zfs' as root to load them.
beninho@Jaguar:~$ sudo su
root@Jaguar:/home/beninho# /sbin/modprobe zfs
modprobe: FATAL: Module zfs not found.
root@Jaguar:/home/beninho# dmesg | grep ZFS
root@Jaguar:/home/beninho# apt-get install ubuntu-zfs
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ubuntu-zfs is already the newest version.

dkms status:

spl, 0.6.5.2, 3.13.0-63-generic, x86_64: installed
spl, 0.6.5.2, 3.13.0-65-generic, x86_64: installed
zfs, 0.6.5.2: added

Solved with:

sudo dkms remove -m zfs -v 0.6.5.2 --all
sudo dkms add -m zfs -v 0.6.5.2
sudo dkms install -m zfs -v 0.6.5.2

zpool import

It seems like kernal update does not trigger zfs dkms to rebuild. ?

**Comment by behlendorf** [comment]
@beninhos it does look that way.  Or perhaps it built against the wrong version of the spl somehow, it looks like you may have somehow had two installed?  If this happens again there may be additional useful debugging in `dmesg`.

**Comment by beninhos** [comment]
How do I find out? This installetion is allmost two years up and running, this is the first time the error occurred. How to use dmesg - i'am not an expert, trief it with dmesg | grep ZFS, but that did not give an ouput.

**Comment by behlendorf** [comment]
Closing as out of date.

**Comment by codecowboy** [comment]
I'm seeing this issue as well but I am not able to resolve using the above method.

dkms status shows:
```

nvidia-304, 304.135, 3.13.0-112-generic, x86_64: installed
nvidia-304, 304.135, 3.13.0-117-generic, x86_64: installed
spl, 0.6.5.9, 3.13.0-112-generic, x86_64: installed
spl, 0.6.5.9, 3.13.0-117-generic, x86_64: installedError! Could not locate dkms.conf file.
File:  does not exist.

spl, 0.6.5.9, 3.13.0-74-generic, x86_64: installed
```

but zfs not listed? This happened after an apt-get update on 14.0.4

**Comment by codecowboy** [comment]
@behlendorf same here. did you resolve this?

**Comment by yamboy1** [comment]
@codecowboy what version of the linux kernel are you using?

**Comment by codecowboy** [comment]
4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64
x86_64 GNU/Linux
