### ISSUE TITLE
zfs used wrong device as cache / pool lost

### ISSUE THREAD

**Issue by hjjg** [zfsonlinux/zfs#3923]
Hi,

I've added a SSD (/dev/sdd) L2ARC to my zpool (tank, /dev/sda). There was another pool (tank2, /dev/sdc) without a cache. After a reboot, tank2 cannot be found and the device names changed. 

The SSD is /dev/sdb now (formally the system disk), tank is /dev/sda and tank2 is /dev/sdd. 

zpool status says, that it's using /dev/sdd as a cache device for /dev/sda. tank2 cannot be found.

zpool import -D /dev/sdd tank2 is not working.

Is the data lost?

**Comment by hjjg** [comment]
I've used tank with mysqld_multi to replicate database servers. mysqld_multi has not been started after the reboot, so only ZFS should have touched /dev/sdd for adding it as a cache device.

We have issued this command now:

zfs export tank

**Comment by hjjg** [comment]
zpool import -c /tmp/zpool.cache -f
   pool: tank2
     id: 1789664647323734951
  state: FAULTED
 status: One or more devices contains corrupted data.
 action: The pool cannot be imported due to damaged devices or data.
	The pool may be active on another system, but can be imported using
	the '-f' flag.
   see: http://zfsonlinux.org/msg/ZFS-8000-5E
 config:

	tank2       FAULTED  corrupted data
	  sdc       FAULTED  corrupted data


The pool is lost.

Even if this is not the fault of zfs-on-linux, this is a major thing. As far as I know, zfs looks for signatures all the time expept for cache-devices...

**Comment by behlendorf** [comment]
@hjjg ZFS is careful about not overwriting a device without warning.  What does a simple `zpool import` without extra arguments show for available pools?  This will case it to inspect all the devices under /dev/ looking for pools.

**Comment by hjjg** [comment]
Hi @behlendorf, thank you for your help. Unfortunately the data is lost. I managed to get /etc/zfs/zpool.cache back (thank you etckeeper!). According to my investigation an some guys from freenode #zfs, I'm pretty sure the data is lost.

We already started to rebuild what is lost.

**Comment by hjjg** [comment]
zfs import did not find anything. Even after removing /dev/sdd from tank as a cache device, removing the SSD from the system and rebooting everything it was not possible for zpool to find anything on the device.

**Comment by tuxoko** [comment]
Are cache device and data disk labelled differently? If so, we should probably add checks so we don't accidentally import data disk as cache device.

**Comment by richardelling** [comment]
You can observe the labels using:
  zdb -l /dev/sdd

Cache devices are labeled like spare devices, unlike pool and log devices. Spares (and at one time caches) were expected to be used by multiple pools, so there is no pool guid or top-level vdev configuration in the label. This means that you can't easily tell what pool the cache belonged to. The heuristic uses the aux device's guid and can be fragile -- sometimes leading to false claims of pool destruction. You can look at the labels, offline the aux devices, then search again for the pools.

**Comment by hjjg** [comment]
I removed the cache device completely for now. Is there a safe way to switch to another device naming to e.g. /dev/disk/by-id/wwn-*? 

I'm pretty sure that I have tried to add the cache disk with this naming scheme at first, but it did not work. 
Don't ask me about it - it was late at night.
