### ISSUE TITLE
Available Space Change After Latest Upgrade

### ISSUE THREAD

**Issue by erocm123** [zfsonlinux/zfs#3924]
So I upgrade zfs on my CentOS 7 box by using yum and now it is reporting available space differently. Has the accounting changed? Sorry, I don't know which version I was on before, but now I am on 6.5.2.

Before Upgrade:
NAME                       USED  AVAIL  REFER  MOUNTPOINT
volume1                   3.39T   186G   740M  /volume1

After Upgrade:
NAME                       USED  AVAIL  REFER  MOUNTPOINT
volume1                   3.39T   128G   740M  /volume1

As you can see there was about 60G that "disappeared".

Also, I know I am running my pool way below the recommended free space for ZFS, but this is just file storage at my home. :)

**Comment by greg-hydrogen** [comment]
@erocm123 - yes there has been a change of behavior for reserved space in the 0.6.5 release 
https://github.com/zfsonlinux/zfs/releases

"Default reserved space was increased from 1.6% to 3.2% of total pool capacity. This default percentage can be controlled through the new spa_slop_shift module option, setting it to 6 will restore the previous percentage."

**Comment by erocm123** [comment]
That did the trick. Thanks.
