### ISSUE TITLE
Decreasing zfs_arc_max with l2arc prevents arc_reclaim to finish

### ISSUE THREAD

**Issue by tuomari** [zfsonlinux/zfs#3926]
ZFS: 0.6.5.2 with ABD 
L2arc 2x 128G (both filled to ~95G )

```
    NAME                                                        STATE     READ WRITE CKSUM
    tank                                                        ONLINE       0     0     0
      mirror-0                                                  ONLINE       0     0     0
        ata-ST3000DM001-9YN166_Z1F16W89                         ONLINE       0     0     0
        ata-ST3000DM001-9YN166_Z1F160XK                         ONLINE       0     0     0
      mirror-1                                                  ONLINE       0     0     0
        ata-ST3000DM001-1CH166_W1F3P4FA                         ONLINE       0     0     0
        ata-ST3000DM001-9YN166_Z1F160T3                         ONLINE       0     0     0
      mirror-2                                                  ONLINE       0     0     0
        ata-ST3000DM001-9YN166_Z1F16XH9                         ONLINE       0     0     0
        ata-ST3000DM001-1CH166_Z1F27SL1                         ONLINE       0     0     0
      mirror-4                                                  ONLINE       0     0     0
        ata-WDC_WD30EFRX-68EUZN0_WD-WCC4N5ECAKDR                ONLINE       0     0     0
        ata-ST3000DM001-1CH166_Z1F27SXT                         ONLINE       0     0     0
      mirror-5                                                  ONLINE       0     0     0
        ata-ST3000DM001-1CH166_Z1F4DJQZ                         ONLINE       0     0     0
        ata-ST3000DM001-1CH166_Z1F27VCK                         ONLINE       0     0     0
    logs
      ata-OWC_Mercury_Enterprise_Pro_6G_SSD_MEP6G05012E26L6601  ONLINE       0     0     0
    cache
      ata-OCZ-VERTEX4_OCZ-1T3R37NK3HLFQ531                      ONLINE       0     0     0
      ata-OCZ-VERTEX4_OCZ-OD888216KNU08A16                      ONLINE       0     0     0
```

I tried to increase zfs_arc_max from 40G to 50G and typo'd 50G to 5G, which I corrected right away.
After a day or so arcstat showed arcsz to still be at 5G and arc_reclaim was using ~30% CPU.
After removing one of the cache devices arcsz dropped to 2.9G after which arcsz started to climb steadily to the target 50G.

It seems that 
- arc_reclaim is unable to release memory required for l2arc headers.
- arc_reclaim is not notified if zfs_arc_max is changed

**Comment by behlendorf** [comment]
> arc_reclaim is unable to release memory required for l2arc headers.

This is definitely true.  Every block added to the L2ARC requires a small amount of memory to track and even under memory pressure the existing implementation will not abandon the references to those blocks to free up memory.  Size your L2ARC accordingly.

> arc_reclaim is not notified if zfs_arc_max is changed

This shouldn't be the case (although perhaps there as bug), as of 0.6.5.x the `arc_tuning_update()` function is called periodically in arc_reclaim to pick up changes to the module parameters.

**Comment by hostingnuggets** [comment]
@behlendorf could you comment and give more details about your sentence "Size your L2ARC accordingly" ?

I had severe performance degradation where arc_reclaim would use 100% of a CPU core as described in issue #4738. My server (hypervisor) has 8 GB RAM, 4 GB RAM is for ARC and then I have a NVMe module of 240 GB for the L2ARC. Should I have a smaller L2ARC ? or what do you recommend?
