### ISSUE TITLE
User with no files has exceeded quota

### ISSUE THREAD

**Issue by griznog** [zfsonlinux/zfs#3927]
Hi,

We have a CentOS 6.6 server running 0.6.5-1 which is showing a user as over quota, even though the user has no files in the filesystem (I went through and removed everything they owned to be certain and checked to make sure no processes are holding deleted files open):

[root@storage-hp07-10 /]# zfs get userused@lafif mds600-r/home
NAME           PROPERTY        VALUE           SOURCE
mds600-r/home  userused@lafif  16.0E           local

I've tried exporting and importing the pool, but that doesn't have any effect. As a workaround I can set the users quota to none but that is not a solution I can use in bulk if this starts affecting other users.

Also I'm happy to provide additional debugging information, I just didn't know where to start since there are no errors, just an incorrect userused value.
Thanks,

jbh

**Comment by DeHackEd** [comment]
This looks like a duplicate of #3789. We're already looking at it.

It might be fixable as ZFS does support upgrading between pool versions with and without this feature. See the above issue for details.

**Comment by griznog** [comment]
Thanks for the pointer.
