### ISSUE TITLE
memory leak in the slab?

### ISSUE THREAD

**Issue by chjohnst** [zfsonlinux/zfs#3929]
I am running into an issue on 0.6.4-1 where I completely run out of memory in the lower zone which eventually brings my zpools to a complete stall and I am usually forced to reboot.  I have done all of the usual of limiting my arc down to 16GB (boxes have 512GB) but that has not helped.  I have increased min_free_kbytes to almost 2GB from the default but has not helped very much.   Usually about 1-2 hrs before the hangs happen I see a page allocation failure and low_memory_zone is at all 0s basically where one of my memory zones are completely starved. 

2015-10-15T15:49:10.306925-04:00 XXXX kernel: [251598.394743] lowmem_reserve[]: 0 0 0 0

**Comment by DeHackEd** [comment]
Unlikely there is a leak, but the nature of the slabs - especially when large blocks are in use and block sizes are highly variable - are that large allocations are made for the full slabs while ZFS thinks it's only using a small amount of memory.

Pull request #3441 addresses this issue significantly but is based on an out of date version of ZFS now. Some people have trees that are more up to date. (shameless plug: I'm one of those  people) It's a 3rd party patch but has seen extensive use by many people so far.

**Comment by behlendorf** [comment]
There are no known leaks, but it is possible that an imbalance could happen between zones.  The ABD patches may help with this, alternately you could move forward to 0.6.5.3 which added a new `zfs_arc_sys_free` module option.  It will attempt to keep enough free memory on your system

```
       zfs_arc_sys_free (ulong)
                   The  target  number  of  bytes the ARC should leave as free
                   memory on the system.  Defaults to the larger  of  1/64  of
                   physical memory or 512K.  Setting this option to a non-zero
                   value will override the default.

                   Default value: 0.
```

**Comment by chjohnst** [comment]
Ok that makes sense as I do see one memory zone lopsided.  I could try this
but was also thinking about disabling NUMA on my storage nodes and just
interleave memory.

My users don't want to constantly upgrade so might be worth waiting for the
ABD patchset to make it into zfs proper.

Can you explain how this new feature could help, the new option you mention?

There are no known leaks, but it is possible that an imbalance could happen
between zones. The ABD patches may help with this, alternately you could
move forward to 0.6.5.3 which added a new zfs_arc_sys_free module option.
It will attempt to keep enough free memory on your system

       zfs_arc_sys_free (ulong)
                   The  target  number  of  bytes the ARC should leave as free
                   memory on the system.  Defaults to the larger  of  1/64  of
                   physical memory or 512K.  Setting this option to a non-zero
                   value will override the default.

                   Default value: 0.

—
Reply to this email directly or view it on GitHub
<https://github.com/zfsonlinux/zfs/issues/3929#issuecomment-149031608>.

**Comment by chjohnst** [comment]
Are the ABD patches expected anytime soon in a new release?

**Comment by behlendorf** [comment]
In the next release yes.   But that won't be for a few months.

**Comment by tuxoko** [comment]
@behlendorf 
Do you have any plan on merging the ABD. Are there any specific things that should be done before merging it?

**Comment by behlendorf** [comment]
Closing.  ABD has been merged!
