### ISSUE TITLE
0.6.5.2-2-wheezy Debian init scripts have a loop between zfs-mount and zfs-import if stopped

### ISSUE THREAD

**Issue by mkjorling** [zfsonlinux/zfs#3932]
Something about installing 0.6.5.2-2-wheezy as an upgrade from 0.6.4-1.2-1-wheezy on Debian Wheezy causes the init scripts to have "a loop between service zfs-mount and zfs-import if stopped", which prevents the installation from succeeding.

Partial output from running `apt-get upgrade`:

    *** zed.rc (Y/I/N/O/D/Z) [default=N] ? y
    Installing new version of config file /etc/zfs/zed.d/zed.rc ...
    insserv: There is a loop between service zfs-mount and zfs-import if stopped
    insserv:  loop involving service zfs-import at depth 3
    insserv:  loop involving service zfs-mount at depth 2
    insserv:  loop involving service pulseaudio at depth 1
    insserv:  loop involving service networking at depth 2
    insserv:  loop involving service umountfs at depth 12
    insserv: exiting now without changing boot order!
    update-rc.d: error: insserv rejected the script header
    dpkg: error processing zfsutils (--configure):
     subprocess installed post-installation script returned error exit status 1
    dpkg: dependency problems prevent configuration of zfs-initramfs:
     zfs-initramfs depends on zfsutils; however:
      Package zfsutils is not configured yet.
    
    dpkg: error processing zfs-initramfs (--configure):
     dependency problems - leaving unconfigured
    Setting up zfs-dkms (0.6.5.2-2-wheezy) ...
    Loading new zfs-0.6.5.2 DKMS files...
    Building only for 3.2.0-4-amd64
    
    Errors were encountered while processing:
     zfsutils
     zfs-initramfs
    E: Sub-process /usr/bin/dpkg returned an error code (1)

I have tried to perform both a straight upgrade as well as deleting the /etc/init.d/zfs* scripts first and retrying the installation, but get the same result each time.

`dpkg-reconfigure` after the `apt-get upgrade` finishes as above simply states that both named packages are broken.

Manually running `update-rc.d` gives the same error output.

I can restore normal functionality by downgrading back to the 0.6.4-1.2-1-wheezy packages and restoring all relevant configuration files, with only trivial warnings from insserv:

    Setting up zfsutils (0.6.4-1.2-1-wheezy) ...
    insserv: warning: current start runlevel(s) (S) of script `zfs-mount' overrides LSB defaults (2 3 4 5).
    insserv: warning: current stop runlevel(s) (0 6) of script `zfs-mount' overrides LSB defaults (0 1 6).
    insserv: warning: current start runlevel(s) (S) of script `zfs-mount' overrides LSB defaults (2 3 4 5).
    insserv: warning: current stop runlevel(s) (0 6) of script `zfs-mount' overrides LSB defaults (0 1 6).
    insserv: warning: current start runlevel(s) (S) of script `zfs-mount' overrides LSB defaults (2 3 4 5).
    insserv: warning: current stop runlevel(s) (0 6) of script `zfs-mount' overrides LSB defaults (0 1 6).
    Processing triggers for initramfs-tools ...

**Comment by FransUrbo** [comment]
This belong to https://github.com/zfsonlinux/pkg-zfs. Please open a new issue there and close this one.

**Comment by mkjorling** [comment]
https://github.com/zfsonlinux/pkg-zfs/issues/179
