### ISSUE TITLE
Kernel panic under high I/O (e.g. scrub)

### ISSUE THREAD

**Issue by stevecs** [zfsonlinux/zfs#3933]
I have been running zfsonlinux for a long while now (2+ years) under ubuntu 14.04 LTS in a with no real issues in a vmware ESXi box with drives sent to the guest.   Just recently upgraded to v0.6.5.2-1~trusty (from 0.6.4.2-1~trusty).   System is running 3.13.0-65 kernel and have 32GB set to arc max (160GB total guest memory).

I can get in and export/import the pool and it show up as online/can access it with normal I/O.   However when I started the monthly scrub (112 drives/406T) it goes for about an hour and then I get a kernel panic. 

The system has 7 trays of drives across 5 controllers, which normally (in previous scrubs) produced about 4GB/s of I/O.     After the first crash I tried both reducing ARC (down to 32G above; it was at 64G) as well as removing any other optimizations/overrides to the zfs module except the following with no effect:

options zfs zfs_arc_max=3435973836
options zfs zfs_txg_timeout="120"
options zfs zfs_scrub_delay=0
options zfs zfs_resilver_delay=0
options zfs zfs_resilver_min_time_ms=10000

(snippet below)
Oct 17 12:05:24 loki kernel: general protection fault: 0000 [#1] SMP
Oct 17 12:05:24 loki kernel: Modules linked in: dm_crypt vmw_balloon coretemp crct10dif_pclmul crc32_pclmul ghash_clmulni_intel aesni_intel aes_x86_64 lrw gf128mul glue_helper ablk_helper cryptd serio_raw joydev ppdev dm_service_time hwmon_vid adm1021 dm_multipath scsi_dh parport_pc vmw_vmci shpchp i2c_piix4 mac_hid i2c_i801 firewire_sbp2 firewire_core crc_itu_t lp parport zfs(POX) zunicode(POX) zcommon(POX) znvpair(POX) spl(OX) zavl(POX) raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx xor raid6_pq raid1 raid0 multipath linear osst st ses enclosure hid_generic usbhid hid vmwgfx psmouse ttm mpt2sas mptspi mptscsih drm raid_class mptbase e1000 scsi_transport_sas pata_acpi
Oct 17 12:05:24 loki kernel: CPU: 15 PID: 14878 Comm: z_rd_iss Tainted: P           OX 3.13.0-65-generic #106-Ubuntu
Oct 17 12:05:24 loki kernel: Hardware name: VMware, Inc. VMware Virtual Platform/440BX Desktop Reference Platform, BIOS 6.00 04/14/2014
Oct 17 12:05:24 loki kernel: task: ffff88279eb61800 ti: ffff88277c1f2000 task.ti: ffff88277c1f2000
Oct 17 12:05:24 loki kernel: RIP: 0010:[<ffffffff811a32db>]  [<ffffffff811a32db>] __kmalloc_node+0x18b/0x2a0
Oct 17 12:05:24 loki kernel: RSP: 0018:ffff88277c1f3a98  EFLAGS: 00010246
Oct 17 12:05:24 loki kernel: RAX: 0000000000000000 RBX: 0000000000000000 RCX: 00000000011b6da3
Oct 17 12:05:24 loki kernel: RDX: 00000000011b6da2 RSI: 0000000000000000 RDI: 0000000000015f80
Oct 17 12:05:24 loki kernel: RBP: ffff88277c1f3ad8 R08: ffff88283fc75f80 R09: ffff8813ef803800
Oct 17 12:05:24 loki kernel: R10: ffff8813ef803800 R11: ffffffffa0197b20 R12: 000000000000c210
Oct 17 12:05:24 loki kernel: R13: 00000000000000c0 R14: 00ffff88279717d6 R15: 00000000ffffffff
Oct 17 12:05:24 loki kernel: FS:  0000000000000000(0000) GS:ffff88283fc60000(0000) knlGS:0000000000000000
Oct 17 12:05:24 loki kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
Oct 17 12:05:24 loki kernel: CR2: 00007f68d5250270 CR3: 0000000001c0e000 CR4: 00000000000007e0
Oct 17 12:05:24 loki kernel: Stack:
Oct 17 12:05:24 loki kernel:  ffff88277c1f3ac0 ffffffffa0197b20 ffff8813ef803800 0000000000000000
Oct 17 12:05:24 loki kernel:  000000000000c210 00000000000000c0 0000000000000000 0000000000000000
Oct 17 12:05:24 loki kernel:  ffff88277c1f3b10 ffffffffa0197b20 ffff88251058b480 ffff8827a4e92000
Oct 17 12:05:24 loki kernel: Call Trace:
Oct 17 12:05:24 loki kernel:  [<ffffffffa0197b20>] ? spl_kmem_zalloc+0xc0/0x170 [spl]
Oct 17 12:05:24 loki kernel:  [<ffffffffa0197b20>] spl_kmem_zalloc+0xc0/0x170 [spl]
Oct 17 12:05:24 loki kernel:  [<ffffffffa038ab74>] __vdev_disk_physio+0x64/0x440 [zfs]
Oct 17 12:05:24 loki kernel:  [<ffffffffa038b432>] vdev_disk_io_start+0xa2/0x200 [zfs]
Oct 17 12:05:24 loki kernel:  [<ffffffffa03c8ecf>] zio_vdev_io_start+0x9f/0x2e0 [zfs]
Oct 17 12:05:24 loki kernel:  [<ffffffffa03cc546>] zio_nowait+0xc6/0x1b0 [zfs]
Oct 17 12:05:24 loki kernel:  [<ffffffffa03920f4>] vdev_raidz_io_start+0x174/0x2f0 [zfs]
Oct 17 12:05:24 loki kernel:  [<ffffffffa038fb40>] ? vdev_raidz_asize+0x60/0x60 [zfs]
Oct 17 12:05:24 loki kernel:  [<ffffffffa03c8ecf>] zio_vdev_io_start+0x9f/0x2e0 [zfs]
Oct 17 12:05:24 loki kernel:  [<ffffffffa03cc546>] zio_nowait+0xc6/0x1b0 [zfs]
Oct 17 12:05:24 loki kernel:  [<ffffffffa038e763>] vdev_mirror_io_start+0x163/0x190 [zfs]
Oct 17 12:05:24 loki kernel:  [<ffffffffa038dcf0>] ? vdev_mirror_worst_error+0x80/0x80 [zfs]
Oct 17 12:05:24 loki kernel:  [<ffffffffa03c900d>] zio_vdev_io_start+0x1dd/0x2e0 [zfs]
Oct 17 12:05:24 loki kernel:  [<ffffffffa03ca058>] zio_execute+0xc8/0x180 [zfs]
Oct 17 12:05:24 loki kernel:  [<ffffffffa019b08d>] taskq_thread+0x20d/0x410 [spl]
Oct 17 12:05:24 loki kernel:  [<ffffffff8109ac90>] ? wake_up_state+0x20/0x20
Oct 17 12:05:24 loki kernel:  [<ffffffffa019ae80>] ? taskq_cancel_id+0x120/0x120 [spl]
Oct 17 12:05:24 loki kernel:  [<ffffffff8108b7d2>] kthread+0xd2/0xf0
Oct 17 12:05:24 loki kernel:  [<ffffffff8108b700>] ? kthread_create_on_node+0x1c0/0x1c0
Oct 17 12:05:24 loki kernel:  [<ffffffff81734aa8>] ret_from_fork+0x58/0x90
Oct 17 12:05:24 loki kernel:  [<ffffffff8108b700>] ? kthread_create_on_node+0x1c0/0x1c0
Oct 17 12:05:24 loki kernel: Code: 5d c8 4c 89 4d d0 e8 d5 cb 00 00 4c 8b 4d d0 49 89 c2 4c 8b 5d c8 e9 f1 fe ff ff 0f 1f 44 00 00 49 63 42 20 48 8d 4a 01 49 8b 3a <49> 8b 1c 06 4c 89 f0 65 48 0f c7 0f 0f 94 c0 84 c0 0f 84 ca fe
Oct 17 12:05:24 loki kernel:  RSP <ffff88277c1f3a98>
Oct 17 12:05:24 loki kernel: ---[ end trace b149697392badca9 ]---
Oct 17 12:05:24 loki kernel: general protection fault: 0000 [#2] SMP
Oct 17 12:05:24 loki kernel: Modules linked in: dm_crypt vmw_balloon coretemp crct10dif_pclmul crc32_pclmul ghash_clmulni_intel aesni_intel aes_x86_64 lrw gf128mul glue_helper ablk_helper cryptd serio_raw joydev ppdev dm_service_time hwmon_vid adm1021 dm_multipath scsi_dh parport_pc vmw_vmci shpchp i2c_piix4 mac_hid i2c_i801 firewire_sbp2 firewire_core crc_itu_t lp parport zfs(POX) zunicode(POX) zcommon(POX) znvpair(POX) spl(OX) zavl(POX) raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx xor raid6_pq raid1 raid0 multipath linear osst st ses enclosure hid_generic usbhid hid vmwgfx psmouse ttm mpt2sas mptspi mptscsih drm raid_class mptbase e1000 scsi_transport_sas pata_acpi
Oct 17 12:05:24 loki kernel: CPU: 15 PID: 2 Comm: kthreadd Tainted: P      D    OX 3.13.0-65-generic #106-Ubuntu
Oct 17 12:05:24 loki kernel: Hardware name: VMware, Inc. VMware Virtual Platform/440BX Desktop Reference Platform, BIOS 6.00 04/14/2014
Oct 17 12:05:24 loki kernel: task: ffff8813cf1c1800 ti: ffff8813cf16c000 task.ti: ffff8813cf16c000
Oct 17 12:05:24 loki kernel: RIP: 0010:[<ffffffff811a3465>]
Oct 17 12:05:24 loki kernel:  [<ffffffff811a3465>] kmem_cache_alloc+0x75/0x1e0
Oct 17 12:05:24 loki kernel: RSP: 0018:ffff8813cf16dd88  EFLAGS: 00010286
Oct 17 12:05:24 loki kernel: RAX: 0000000000000000 RBX: 0000000000000000 RCX: 00000000011b6da3
Oct 17 12:05:24 loki kernel: RDX: 00000000011b6da2 RSI: ffff8813cf1c1800 RDI: ffff8813cf1c1800
Oct 17 12:05:24 loki kernel: RBP: ffff8813cf16ddb8 R08: 0000000000015f80 R09: ffffffff81090b66
Oct 17 12:05:24 loki kernel: R10: 0000000000000000 R11: ffffea004f2c5640 R12: 00ffff88279717d6
Oct 17 12:05:24 loki kernel: R13: 00000000000000d0 R14: ffff8813ef803800 R15: ffff8813ef803800
Oct 17 12:05:24 loki kernel: FS:  0000000000000000(0000) GS:ffff88283fc60000(0000) knlGS:0000000000000000
Oct 17 12:05:24 loki kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
Oct 17 12:05:24 loki kernel: CR2: 00007f68d5250270 CR3: 0000000001c0e000 CR4: 00000000000007e0
Oct 17 12:05:24 loki kernel: Stack:
Oct 17 12:05:24 loki kernel:  ffffffff81090b66
Oct 17 12:05:24 loki kernel:  0000000000000000
Oct 17 12:05:24 loki kernel:  ffff8813cf1c1800
Oct 17 12:05:24 loki kernel:  0000000000800711
Oct 17 12:05:24 loki kernel:
Oct 17 12:05:24 loki kernel:  ffff8827a0474800
Oct 17 12:05:24 loki kernel:  ffff88259ec42000
Oct 17 12:05:24 loki kernel:  ffff8813cf16ddd8
Oct 17 12:05:24 loki kernel:  ffffffff81090b66
Oct 17 12:05:24 loki kernel:
Oct 17 12:05:24 loki kernel:  0000000000000000
Oct 17 12:05:24 loki kernel:  ffff8827a0474800
Oct 17 12:05:24 loki kernel:  ffff8813cf16de08
Oct 17 12:05:24 loki kernel:  ffffffff8109123f
Oct 17 12:05:24 loki kernel:
Oct 17 12:05:24 loki kernel: Call Trace:
Oct 17 12:05:24 loki kernel:
Oct 17 12:05:24 loki kernel:  [<ffffffff81090b66>] ? prepare_creds+0x26/0x1c0
Oct 17 12:05:24 loki kernel:
Oct 17 12:05:24 loki kernel:  [<ffffffff81090b66>] prepare_creds+0x26/0x1c0
Oct 17 12:05:24 loki kernel:
Oct 17 12:05:24 loki kernel:  [<ffffffff8109123f>] copy_creds+0x2f/0x150
Oct 17 12:05:24 loki kernel:
Oct 17 12:05:24 loki kernel:  [<ffffffff81065540>] copy_process.part.26+0x340/0x16b0
Oct 17 12:05:24 loki kernel:
Oct 17 12:05:24 loki kernel:  [<ffffffff8108b700>] ? kthread_create_on_node+0x1c0/0x1c0
Oct 17 12:05:24 loki kernel:
Oct 17 12:05:24 loki kernel:  [<ffffffff81066a85>] do_fork+0xd5/0x340
Oct 17 12:05:24 loki kernel:
Oct 17 12:05:24 loki kernel:  [<ffffffff81066d16>] kernel_thread+0x26/0x30
Oct 17 12:05:24 loki kernel:
Oct 17 12:05:24 loki kernel:  [<ffffffff8108c14a>] kthreadd+0x15a/0x1c0
Oct 17 12:05:24 loki kernel:
Oct 17 12:05:24 loki kernel:  [<ffffffff8108bff0>] ? kthread_create_on_cpu+0x60/0x60
Oct 17 12:05:24 loki kernel:
Oct 17 12:05:24 loki kernel:  [<ffffffff81734aa8>] ret_from_fork+0x58/0x90
Oct 17 12:05:24 loki kernel:
Oct 17 12:05:24 loki kernel:  [<ffffffff8108bff0>] ? kthread_create_on_cpu+0x60/0x60
Oct 17 12:05:24 loki kernel: Code:
Oct 17 12:05:24 loki kernel: cd
Oct 17 12:05:24 loki kernel: 00
Oct 17 12:05:24 loki kernel: 00
Oct 17 12:05:24 loki kernel: 49
Oct 17 12:05:24 loki kernel: 8b
Oct 17 12:05:24 loki kernel: 50
Oct 17 12:05:24 loki kernel: 08
Oct 17 12:05:24 loki kernel: 4d
Oct 17 12:05:24 loki kernel: 8b
Oct 17 12:05:24 loki kernel: 20
Oct 17 12:05:24 loki kernel: 49
Oct 17 12:05:24 loki kernel: 8b
Oct 17 12:05:24 loki kernel: 40
Oct 17 12:05:24 loki kernel: 10
Oct 17 12:05:24 loki kernel: 4d
Oct 17 12:05:24 loki kernel: 85
Oct 17 12:05:24 loki kernel: e4
Oct 17 12:05:24 loki kernel: 0f
Oct 17 12:05:24 loki kernel: 84
Oct 17 12:05:24 loki kernel: 17
Oct 17 12:05:24 loki kernel: 01
Oct 17 12:05:24 loki kernel: 00
Oct 17 12:05:24 loki kernel: 00
Oct 17 12:05:24 loki kernel: 48
Oct 17 12:05:24 loki kernel: 85
Oct 17 12:05:24 loki kernel: c0
Oct 17 12:05:24 loki kernel: 0f
Oct 17 12:05:24 loki kernel: 84
Oct 17 12:05:24 loki kernel: 0e
Oct 17 12:05:24 loki kernel: 01
Oct 17 12:05:24 loki kernel: 00
Oct 17 12:05:24 loki kernel: 00
Oct 17 12:05:24 loki kernel: 49
Oct 17 12:05:24 loki kernel: 63
Oct 17 12:05:24 loki kernel: 46
Oct 17 12:05:24 loki kernel: 20
Oct 17 12:05:24 loki kernel: 48
Oct 17 12:05:24 loki kernel: 8d
Oct 17 12:05:24 loki kernel: 4a
Oct 17 12:05:24 loki kernel: 01
Oct 17 12:05:24 loki kernel: 4d
Oct 17 12:05:24 loki kernel: 8b
Oct 17 12:05:24 loki kernel: 06
Oct 17 12:05:24 loki kernel: <49>
Oct 17 12:05:24 loki kernel: 8b
Oct 17 12:05:24 loki kernel: 1c
Oct 17 12:05:24 loki kernel: 04
Oct 17 12:05:24 loki kernel: 4c
Oct 17 12:05:24 loki kernel: 89
Oct 17 12:05:24 loki kernel: e0
Oct 17 12:05:24 loki kernel: 65
Oct 17 12:05:24 loki kernel: 49
Oct 17 12:05:24 loki kernel: 0f
Oct 17 12:05:24 loki kernel: c7
Oct 17 12:05:24 loki kernel: 08
Oct 17 12:05:24 loki kernel: 0f
Oct 17 12:05:24 loki kernel: 94
Oct 17 12:05:24 loki kernel: c0
Oct 17 12:05:24 loki kernel: 84
Oct 17 12:05:24 loki kernel: c0
Oct 17 12:05:24 loki kernel: 74
Oct 17 12:05:24 loki kernel: b9
Oct 17 12:05:24 loki kernel: 49
Oct 17 12:05:24 loki kernel: 63
Oct 17 12:05:24 loki kernel:
Oct 17 12:05:24 loki kernel:  [<ffffffff811a3465>] kmem_cache_alloc+0x75/0x1e0
Oct 17 12:05:24 loki kernel:  RSP <ffff8813cf16dd88>
Oct 17 12:05:24 loki kernel: ---[ end trace b149697392badcaa ]---
Oct 17 12:05:24 loki kernel: general protection fault: 0000 [#3]
Oct 17 12:05:24 loki kernel: SMP
Oct 17 12:05:24 loki kernel:
Oct 17 12:05:24 loki kernel: Modules linked in:
Oct 17 12:05:24 loki kernel:  dm_crypt
Oct 17 12:05:24 loki kernel:  vmw_balloon
Oct 17 12:05:24 loki kernel:  coretemp
Oct 17 12:05:24 loki kernel:  crct10dif_pclmul
Oct 17 12:05:24 loki kernel:  crc32_pclmul
Oct 17 12:05:24 loki kernel:  ghash_clmulni_intel
Oct 17 12:05:24 loki kernel:  aesni_intel
Oct 17 12:05:24 loki kernel:  aes_x86_64
Oct 17 12:05:24 loki kernel:  lrw
Oct 17 12:05:24 loki kernel:  gf128mul
Oct 17 12:05:24 loki kernel:  glue_helper
Oct 17 12:05:24 loki kernel:  ablk_helper
Oct 17 12:05:24 loki kernel:  cryptd
Oct 17 12:05:24 loki kernel:  serio_raw
Oct 17 12:05:24 loki kernel:  joydev
Oct 17 12:05:24 loki kernel:  ppdev
Oct 17 12:05:24 loki kernel:  dm_service_time
Oct 17 12:05:24 loki kernel:  hwmon_vid
Oct 17 12:05:24 loki kernel:  adm1021
Oct 17 12:05:24 loki kernel:  dm_multipath
Oct 17 12:05:24 loki kernel:  scsi_dh
Oct 17 12:05:24 loki kernel:  parport_pc
Oct 17 12:05:24 loki kernel:  vmw_vmci
Oct 17 12:05:24 loki kernel:  shpchp
Oct 17 12:05:24 loki kernel:  i2c_piix4
Oct 17 12:05:24 loki kernel:  mac_hid
Oct 17 12:05:24 loki kernel:  i2c_i801
Oct 17 12:05:24 loki kernel:  firewire_sbp2
Oct 17 12:05:24 loki kernel:  firewire_core
Oct 17 12:05:24 loki kernel:  crc_itu_t
Oct 17 12:05:24 loki kernel:  lp
Oct 17 12:05:24 loki kernel:  parport
Oct 17 12:05:24 loki kernel:  zfs(POX)
Oct 17 12:05:24 loki kernel:  zunicode(POX)
Oct 17 12:05:24 loki kernel:  zcommon(POX)
Oct 17 12:05:24 loki kernel:  znvpair(POX)
Oct 17 12:05:24 loki kernel:  spl(OX)
Oct 17 12:05:24 loki kernel:  zavl(POX)
Oct 17 12:05:24 loki kernel:  raid10
Oct 17 12:05:24 loki kernel:  raid456
Oct 17 12:05:24 loki kernel:  async_raid6_recov
Oct 17 12:05:24 loki kernel:  async_memcpy
Oct 17 12:05:24 loki kernel:  async_pq
Oct 17 12:05:24 loki kernel:  async_xor
Oct 17 12:05:24 loki kernel:  async_tx
Oct 17 12:05:24 loki kernel:  xor
Oct 17 12:05:24 loki kernel:  raid6_pq
Oct 17 12:05:24 loki kernel:  raid1
Oct 17 12:05:24 loki kernel:  raid0
Oct 17 12:05:24 loki kernel:  multipath
Oct 17 12:05:24 loki kernel:  linear
Oct 17 12:05:24 loki kernel:  osst
Oct 17 12:05:24 loki kernel:  st
Oct 17 12:05:24 loki kernel:  ses
Oct 17 12:05:24 loki kernel:  enclosure
Oct 17 12:05:24 loki kernel:  hid_generic
Oct 17 12:05:24 loki kernel:  usbhid
Oct 17 12:05:24 loki kernel:  hid
Oct 17 12:05:24 loki kernel:  vmwgfx
Oct 17 12:05:24 loki kernel:  psmouse
Oct 17 12:05:24 loki kernel:  ttm
Oct 17 12:05:24 loki kernel:  mpt2sas
Oct 17 12:05:24 loki kernel:  mptspi
Oct 17 12:05:24 loki kernel:  mptscsih
Oct 17 12:05:24 loki kernel:  drm
Oct 17 12:05:24 loki kernel:  raid_class
Oct 17 12:05:24 loki kernel:  mptbase
Oct 17 12:05:24 loki kernel:  e1000
Oct 17 12:05:24 loki kernel:  scsi_transport_sas
Oct 17 12:05:24 loki kernel:  pata_acpi

(will post full data)

I did not see this already mentioned (if this is a duplicate let me know).

**Comment by stevecs** [comment]
full panic is here:   http://pastebin.com/fNwsL6ai

**Comment by behlendorf** [comment]
@stevecs sorry you've been bitten by this issue.  The good news is that we believe this will be fixed by commit cd887ab869bb506c88a66ba8c225ca42680b89d0 in the [0.6.5.3 tag](https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.6.5.3).  Definitely let us know if this doesn't address the issue once this release appears for Trusty.

**Comment by stevecs** [comment]
Thanks.   will check it out w/ 0.6.5.3.  We have current backups and this only seems to (so far) to raise it's head with heavy load so think we can roll the dice for a little bit.

**Comment by stevecs** [comment]
Just to update here.   I just had a chance to install and run a scan against the array with v0.6.5.3-1~trusty.    The above problem did not recur so it looks like this commit was successful.    I'll close the ticket out and re-open if I see anything untoward.     Thanks!
