### ISSUE TITLE
etc/init.d/README.md points at incorrect issue tracker for issue reporting

### ISSUE THREAD

**Issue by mkjorling** [zfsonlinux/zfs#3934]
https://github.com/zfsonlinux/zfs/blob/master/etc/init.d/README.md states that, referring to the init scripts:

> If you find that they don't work for your platform, please report this at the ZFS On Linux issue tracker at https://github.com/zfsonlinux/zfs/issues.

https://github.com/zfsonlinux/zfs/issues/3932#issuecomment-149000285 states that the issue involving the init scripts should be reported at https://github.com/zfsonlinux/pkg-zfs instead.

I feel the link needs to be corrected to correctly reflect where issues with the init scripts should be reported, or the section expanded on to explain which issues should be reported where.

**Comment by FransUrbo** [comment]
Both these are correct unfortunately.

Issues regarding the init scripts in ZoL (<code>etc/init.d</code> directory) belong to the zfs bug tracker. BUT, anyone having issues with the Debian GNU/Linux init scripts need to report this to the pkg-zfs tracker.

The reason for this is that I apply extra patches/PRs to the Debian GNU/Linux packages that have yet to be applied/accepted into ZoL.

**Comment by FransUrbo** [comment]
@mkjorling Please close this - I consider this a "non-issue". The README.md IS correct, in regards to the zfs repo. And putting in information about other repos is out of its scope I think.

The correct information is also displayed in the FAQ (http://zfsonlinux.org/faq.html#WhereDoIReportProblems).
