### ISSUE TITLE
nfsd bash  z_unmount  blocked for more than 120 seconds

### ISSUE THREAD

**Issue by wonder** [zfsonlinux/zfs#3941]
Hello,

  zfs-dkms                            0.6.5.2-1~trusty   

I'm trying to access a snapshot over nfs and sometimes it hangs, now i didn't even had any write operations via nfs.

After nfsd hanged, I wanted to copy some files from the snapshot directory directly from this server and entering in the diretory hanged as well.

Right now this box is very unstable with 0.6.5.2-1.

6480.144035] INFO: task nfsd:1794 blocked for more than 120 seconds.
[ 6480.144162]       Tainted: P           OE 3.16.0-51-generic #69~14.04.1-Ubuntu
[ 6480.144266] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 6480.144374] nfsd            D ffff88045fc930c0     0  1794      2 0x00000000
[ 6480.144380]  ffff88043e86ba20 0000000000000046 ffff88043dcef010 ffff88043e86bfd8
[ 6480.144383]  00000000000130c0 00000000000130c0 ffff880449659e90 ffffffffc0624560
[ 6480.144387]  ffffffffc0624564 ffff88043dcef010 00000000ffffffff ffffffffc0624568
[ 6480.144390] Call Trace:
[ 6480.144412]  [<ffffffff8176b829>] schedule_preempt_disabled+0x29/0x70
[ 6480.144415]  [<ffffffff8176d675>] __mutex_lock_slowpath+0xd5/0x1d0
[ 6480.144419]  [<ffffffff8176d78f>] mutex_lock+0x1f/0x2f
[ 6480.144487]  [<ffffffffc04c52f6>] zfsctl_snapshot_unmount_delay+0x26/0xa0 [zfs]
[ 6480.144528]  [<ffffffffc04c6786>] zfsctl_lookup_objset+0x246/0x3a0 [zfs]
[ 6480.144532]  [<ffffffff8176d782>] ? mutex_lock+0x12/0x2f
[ 6480.144569]  [<ffffffffc048de78>] ? rrw_exit+0x68/0x170 [zfs]
[ 6480.144612]  [<ffffffffc04d97b6>] zfs_vget+0x176/0x3e0 [zfs]
[ 6480.144655]  [<ffffffffc04f7a02>] zpl_fh_to_dentry+0x72/0xb0 [zfs]
[ 6480.144668]  [<ffffffffc07c9930>] ? nfsd_proc_getattr+0xa0/0xa0 [nfsd]
[ 6480.144673]  [<ffffffff812c0932>] exportfs_decode_fh+0x72/0x2e0
[ 6480.144697]  [<ffffffffc06feae6>] ? cache_check+0x106/0x3d0 [sunrpc]
[ 6480.144705]  [<ffffffffc07cf68c>] ? exp_find+0xfc/0x1b0 [nfsd]
[ 6480.144710]  [<ffffffff811b7d16>] ? kmem_cache_alloc_trace+0x1c6/0x1f0
[ 6480.144714]  [<ffffffff81322537>] ? aa_alloc_task_context+0x27/0x40
[ 6480.144723]  [<ffffffffc07ca656>] fh_verify+0x2f6/0x5e0 [nfsd]
[ 6480.144727]  [<ffffffff811b67cb>] ? kfree+0xab/0x140
[ 6480.144736]  [<ffffffffc07d84c9>] nfsd4_putfh+0x49/0x50 [nfsd]
[ 6480.144746]  [<ffffffffc07da66f>] nfsd4_proc_compound+0x4ff/0x820 [nfsd]
[ 6480.144754]  [<ffffffffc07c6dab>] nfsd_dispatch+0xbb/0x200 [nfsd]
[ 6480.144768]  [<ffffffffc06f45b0>] svc_process_common+0x440/0x6d0 [sunrpc]
[ 6480.144777]  [<ffffffffc07c6670>] ? nfsd_destroy+0x80/0x80 [nfsd]
[ 6480.144790]  [<ffffffffc06f4947>] svc_process+0x107/0x170 [sunrpc]
[ 6480.144798]  [<ffffffffc07c6670>] ? nfsd_destroy+0x80/0x80 [nfsd]
[ 6480.144805]  [<ffffffffc07c6737>] nfsd+0xc7/0x130 [nfsd]
[ 6480.144811]  [<ffffffff810915a2>] kthread+0xd2/0xf0
[ 6480.144814]  [<ffffffff810914d0>] ? kthread_create_on_node+0x1c0/0x1c0
[ 6480.144818]  [<ffffffff8176f2d8>] ret_from_fork+0x58/0x90
[ 6480.144821]  [<ffffffff810914d0>] ? kthread_create_on_node+0x1c0/0x1c0
[ 6480.144824] INFO: task nfsd:1797 blocked for more than 120 seconds.
[ 6480.144923]       Tainted: P           OE 3.16.0-51-generic #69~14.04.1-Ubuntu
[ 6480.145026] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 6480.145133] nfsd            D ffff88045fc130c0     0  1797      2 0x00000000
[ 6480.145137]  ffff88043e687a50 0000000000000046 ffff880440118a30 ffff88043e687fd8
[ 6480.145141]  00000000000130c0 00000000000130c0 ffff8804495c4750 ffffffffc0624560
[ 6480.145144]  ffffffffc0624564 ffff880440118a30 00000000ffffffff ffffffffc0624568
[ 6480.145148] Call Trace:
[ 6480.145152]  [<ffffffff8176b829>] schedule_preempt_disabled+0x29/0x70
[ 6480.145155]  [<ffffffff8176d675>] __mutex_lock_slowpath+0xd5/0x1d0
[ 6480.145159]  [<ffffffff8176d78f>] mutex_lock+0x1f/0x2f
[ 6480.145199]  [<ffffffffc04c6574>] zfsctl_lookup_objset+0x34/0x3a0 [zfs]
[ 6480.145202]  [<ffffffff8176d782>] ? mutex_lock+0x12/0x2f
[ 6480.145239]  [<ffffffffc048de78>] ? rrw_exit+0x68/0x170 [zfs]
[ 6480.145281]  [<ffffffffc04d97b6>] zfs_vget+0x176/0x3e0 [zfs]
[ 6480.145285]  [<ffffffff8109ece5>] ? check_preempt_curr+0x85/0xa0
[ 6480.145288]  [<ffffffff8109ed19>] ? ttwu_do_wakeup+0x19/0xc0
[ 6480.145329]  [<ffffffffc04f7a02>] zpl_fh_to_dentry+0x72/0xb0 [zfs]
[ 6480.145337]  [<ffffffffc07c9930>] ? nfsd_proc_getattr+0xa0/0xa0 [nfsd]
[ 6480.145340]  [<ffffffff812c0932>] exportfs_decode_fh+0x72/0x2e0
[ 6480.145344]  [<ffffffff810a1b72>] ? default_wake_function+0x12/0x20
[ 6480.145349]  [<ffffffff810b50f2>] ? autoremove_wake_function+0x12/0x40
[ 6480.145352]  [<ffffffff810b49f8>] ? __wake_up_common+0x58/0x90
[ 6480.145355]  [<ffffffff810b4c84>] ? __wake_up+0x44/0x50
[ 6480.145359]  [<ffffffff810d4188>] ? __call_rcu_nocb_enqueue+0xc8/0xd0
[ 6480.145367]  [<ffffffffc07ca656>] fh_verify+0x2f6/0x5e0 [nfsd]
[ 6480.145370]  [<ffffffff811b67cb>] ? kfree+0xab/0x140
[ 6480.145379]  [<ffffffffc07d84c9>] nfsd4_putfh+0x49/0x50 [nfsd]
[ 6480.145388]  [<ffffffffc07da66f>] nfsd4_proc_compound+0x4ff/0x820 [nfsd]
[ 6480.145396]  [<ffffffffc07c6dab>] nfsd_dispatch+0xbb/0x200 [nfsd]
[ 6480.145410]  [<ffffffffc06f45b0>] svc_process_common+0x440/0x6d0 [sunrpc]
[ 6480.145418]  [<ffffffffc07c6670>] ? nfsd_destroy+0x80/0x80 [nfsd]
[ 6480.145432]  [<ffffffffc06f4947>] svc_process+0x107/0x170 [sunrpc]
[ 6480.145439]  [<ffffffffc07c6670>] ? nfsd_destroy+0x80/0x80 [nfsd]
[ 6480.145447]  [<ffffffffc07c6737>] nfsd+0xc7/0x130 [nfsd]
[ 6480.145450]  [<ffffffff810915a2>] kthread+0xd2/0xf0
[ 6480.145454]  [<ffffffff810914d0>] ? kthread_create_on_node+0x1c0/0x1c0
[ 6480.145457]  [<ffffffff8176f2d8>] ret_from_fork+0x58/0x90
[ 6480.145460]  [<ffffffff810914d0>] ? kthread_create_on_node+0x1c0/0x1c0
[ 6600.144028] INFO: task z_unmount:315 blocked for more than 120 seconds.
[ 6600.144133]       Tainted: P           OE 3.16.0-51-generic #69~14.04.1-Ubuntu
[ 6600.144236] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 6600.144344] z_unmount       D ffff88045fcd30c0     0   315      2 0x00000000
[ 6600.144350]  ffff8804464d7d40 0000000000000046 ffff88009e8fa8c0 ffff8804464d7fd8
[ 6600.144354]  00000000000130c0 00000000000130c0 ffff88044965a8c0 ffffffffc0624560
[ 6600.144357]  ffffffffc0624564 ffff88009e8fa8c0 00000000ffffffff ffffffffc0624568
[ 6600.144361] Call Trace:
[ 6600.144382]  [<ffffffff8176b829>] schedule_preempt_disabled+0x29/0x70
[ 6600.144385]  [<ffffffff8176d675>] __mutex_lock_slowpath+0xd5/0x1d0
[ 6600.144389]  [<ffffffff8176d78f>] mutex_lock+0x1f/0x2f
[ 6600.144457]  [<ffffffffc04c5d7a>] zfsctl_snapshot_unmount+0x4a/0x170 [zfs]
[ 6600.144499]  [<ffffffffc04c5ec8>] snapentry_expire+0x28/0xb0 [zfs]
[ 6600.144511]  [<ffffffffc03c208d>] taskq_thread+0x20d/0x410 [spl]
[ 6600.144517]  [<ffffffff810a1b60>] ? wake_up_state+0x20/0x20
[ 6600.144525]  [<ffffffffc03c1e80>] ? taskq_cancel_id+0x120/0x120 [spl]
[ 6600.144530]  [<ffffffff810915a2>] kthread+0xd2/0xf0
[ 6600.144533]  [<ffffffff810914d0>] ? kthread_create_on_node+0x1c0/0x1c0
[ 6600.144536]  [<ffffffff8176f2d8>] ret_from_fork+0x58/0x90
[ 6600.144539]  [<ffffffff810914d0>] ? kthread_create_on_node+0x1c0/0x1c0
[ 6600.144559] INFO: task nfsd:1794 blocked for more than 120 seconds.
[ 6600.144659]       Tainted: P           OE 3.16.0-51-generic #69~14.04.1-Ubuntu
[ 6600.144764] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 6600.144871] nfsd            D ffff88045fc930c0     0  1794      2 0x00000004
[ 6600.144875]  ffff88043e86ba20 0000000000000046 ffff88043dcef010 ffff88043e86bfd8
[ 6600.144878]  00000000000130c0 00000000000130c0 ffff880449659e90 ffffffffc0624560
[ 6600.144881]  ffffffffc0624564 ffff88043dcef010 00000000ffffffff ffffffffc0624568
[ 6600.144885] Call Trace:
[ 6600.144890]  [<ffffffff8176b829>] schedule_preempt_disabled+0x29/0x70
[ 6600.144893]  [<ffffffff8176d675>] __mutex_lock_slowpath+0xd5/0x1d0
[ 6600.144897]  [<ffffffff8176d78f>] mutex_lock+0x1f/0x2f
[ 6600.144937]  [<ffffffffc04c52f6>] zfsctl_snapshot_unmount_delay+0x26/0xa0 [zfs]
[ 6600.144978]  [<ffffffffc04c6786>] zfsctl_lookup_objset+0x246/0x3a0 [zfs]
[ 6600.144982]  [<ffffffff8176d782>] ? mutex_lock+0x12/0x2f
[ 6600.145019]  [<ffffffffc048de78>] ? rrw_exit+0x68/0x170 [zfs]
[ 6600.145062]  [<ffffffffc04d97b6>] zfs_vget+0x176/0x3e0 [zfs]
[ 6600.145105]  [<ffffffffc04f7a02>] zpl_fh_to_dentry+0x72/0xb0 [zfs]
[ 6600.145118]  [<ffffffffc07c9930>] ? nfsd_proc_getattr+0xa0/0xa0 [nfsd]
[ 6600.145123]  [<ffffffff812c0932>] exportfs_decode_fh+0x72/0x2e0
[ 6600.145147]  [<ffffffffc06feae6>] ? cache_check+0x106/0x3d0 [sunrpc]
[ 6600.145156]  [<ffffffffc07cf68c>] ? exp_find+0xfc/0x1b0 [nfsd]
[ 6600.145160]  [<ffffffff811b7d16>] ? kmem_cache_alloc_trace+0x1c6/0x1f0
[ 6600.145164]  [<ffffffff81322537>] ? aa_alloc_task_context+0x27/0x40
[ 6600.145173]  [<ffffffffc07ca656>] fh_verify+0x2f6/0x5e0 [nfsd]
[ 6600.145177]  [<ffffffff811b67cb>] ? kfree+0xab/0x140
[ 6600.145187]  [<ffffffffc07d84c9>] nfsd4_putfh+0x49/0x50 [nfsd]
[ 6600.145196]  [<ffffffffc07da66f>] nfsd4_proc_compound+0x4ff/0x820 [nfsd]
[ 6600.145204]  [<ffffffffc07c6dab>] nfsd_dispatch+0xbb/0x200 [nfsd]
[ 6600.145219]  [<ffffffffc06f45b0>] svc_process_common+0x440/0x6d0 [sunrpc]
[ 6600.145227]  [<ffffffffc07c6670>] ? nfsd_destroy+0x80/0x80 [nfsd]
[ 6600.145240]  [<ffffffffc06f4947>] svc_process+0x107/0x170 [sunrpc]
[ 6600.145248]  [<ffffffffc07c6670>] ? nfsd_destroy+0x80/0x80 [nfsd]
[ 6600.145255]  [<ffffffffc07c6737>] nfsd+0xc7/0x130 [nfsd]
[ 6600.145259]  [<ffffffff810915a2>] kthread+0xd2/0xf0
[ 6600.145262]  [<ffffffff810914d0>] ? kthread_create_on_node+0x1c0/0x1c0
[ 6600.145265]  [<ffffffff8176f2d8>] ret_from_fork+0x58/0x90
[ 6600.145269]  [<ffffffff810914d0>] ? kthread_create_on_node+0x1c0/0x1c0
[ 6600.145271] INFO: task nfsd:1797 blocked for more than 120 seconds.
[ 6600.145370]       Tainted: P           OE 3.16.0-51-generic #69~14.04.1-Ubuntu
[ 6600.145474] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 6600.145581] nfsd            D ffff88045fc130c0     0  1797      2 0x00000004
[ 6600.145585]  ffff88043e687a50 0000000000000046 ffff880440118a30 ffff88043e687fd8
[ 6600.145588]  00000000000130c0 00000000000130c0 ffff8804495c4750 ffffffffc0624560
[ 6600.145592]  ffffffffc0624564 ffff880440118a30 00000000ffffffff ffffffffc0624568
[ 6600.145595] Call Trace:
[ 6600.145600]  [<ffffffff8176b829>] schedule_preempt_disabled+0x29/0x70
[ 6600.145603]  [<ffffffff8176d675>] __mutex_lock_slowpath+0xd5/0x1d0
[ 6600.145606]  [<ffffffff8176d78f>] mutex_lock+0x1f/0x2f
[ 6600.145647]  [<ffffffffc04c6574>] zfsctl_lookup_objset+0x34/0x3a0 [zfs]
[ 6600.145650]  [<ffffffff8176d782>] ? mutex_lock+0x12/0x2f
[ 6600.145686]  [<ffffffffc048de78>] ? rrw_exit+0x68/0x170 [zfs]
[ 6600.145728]  [<ffffffffc04d97b6>] zfs_vget+0x176/0x3e0 [zfs]
[ 6600.145731]  [<ffffffff8109ece5>] ? check_preempt_curr+0x85/0xa0
[ 6600.145734]  [<ffffffff8109ed19>] ? ttwu_do_wakeup+0x19/0xc0
[ 6600.145776]  [<ffffffffc04f7a02>] zpl_fh_to_dentry+0x72/0xb0 [zfs]
[ 6600.145784]  [<ffffffffc07c9930>] ? nfsd_proc_getattr+0xa0/0xa0 [nfsd]
[ 6600.145787]  [<ffffffff812c0932>] exportfs_decode_fh+0x72/0x2e0
[ 6600.145790]  [<ffffffff810a1b72>] ? default_wake_function+0x12/0x20
[ 6600.145795]  [<ffffffff810b50f2>] ? autoremove_wake_function+0x12/0x40
[ 6600.145798]  [<ffffffff810b49f8>] ? __wake_up_common+0x58/0x90
[ 6600.145801]  [<ffffffff810b4c84>] ? __wake_up+0x44/0x50
[ 6600.145804]  [<ffffffff810d4188>] ? __call_rcu_nocb_enqueue+0xc8/0xd0
[ 6600.145813]  [<ffffffffc07ca656>] fh_verify+0x2f6/0x5e0 [nfsd]
[ 6600.145816]  [<ffffffff811b67cb>] ? kfree+0xab/0x140
[ 6600.145825]  [<ffffffffc07d84c9>] nfsd4_putfh+0x49/0x50 [nfsd]
[ 6600.145834]  [<ffffffffc07da66f>] nfsd4_proc_compound+0x4ff/0x820 [nfsd]
[ 6600.145842]  [<ffffffffc07c6dab>] nfsd_dispatch+0xbb/0x200 [nfsd]
[ 6600.145856]  [<ffffffffc06f45b0>] svc_process_common+0x440/0x6d0 [sunrpc]
[ 6600.145864]  [<ffffffffc07c6670>] ? nfsd_destroy+0x80/0x80 [nfsd]
[ 6600.145878]  [<ffffffffc06f4947>] svc_process+0x107/0x170 [sunrpc]
[ 6600.145885]  [<ffffffffc07c6670>] ? nfsd_destroy+0x80/0x80 [nfsd]
[ 6600.145893]  [<ffffffffc07c6737>] nfsd+0xc7/0x130 [nfsd]
[ 6600.145896]  [<ffffffff810915a2>] kthread+0xd2/0xf0
[ 6600.145899]  [<ffffffff810914d0>] ? kthread_create_on_node+0x1c0/0x1c0
[ 6600.145903]  [<ffffffff8176f2d8>] ret_from_fork+0x58/0x90
[ 6600.145906]  [<ffffffff810914d0>] ? kthread_create_on_node+0x1c0/0x1c0
[ 6720.144029] INFO: task z_unmount:315 blocked for more than 120 seconds.
[ 6720.144135]       Tainted: P           OE 3.16.0-51-generic #69~14.04.1-Ubuntu
[ 6720.144239] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 6720.144347] z_unmount       D ffff88045fcd30c0     0   315      2 0x00000000
[ 6720.144353]  ffff8804464d7d40 0000000000000046 ffff88009e8fa8c0 ffff8804464d7fd8
[ 6720.144357]  00000000000130c0 00000000000130c0 ffff88044965a8c0 ffffffffc0624560
[ 6720.144360]  ffffffffc0624564 ffff88009e8fa8c0 00000000ffffffff ffffffffc0624568
[ 6720.144364] Call Trace:
[ 6720.144386]  [<ffffffff8176b829>] schedule_preempt_disabled+0x29/0x70
[ 6720.144389]  [<ffffffff8176d675>] __mutex_lock_slowpath+0xd5/0x1d0
[ 6720.144393]  [<ffffffff8176d78f>] mutex_lock+0x1f/0x2f
[ 6720.144461]  [<ffffffffc04c5d7a>] zfsctl_snapshot_unmount+0x4a/0x170 [zfs]
[ 6720.144503]  [<ffffffffc04c5ec8>] snapentry_expire+0x28/0xb0 [zfs]
[ 6720.144516]  [<ffffffffc03c208d>] taskq_thread+0x20d/0x410 [spl]
[ 6720.144521]  [<ffffffff810a1b60>] ? wake_up_state+0x20/0x20
[ 6720.144529]  [<ffffffffc03c1e80>] ? taskq_cancel_id+0x120/0x120 [spl]
[ 6720.144534]  [<ffffffff810915a2>] kthread+0xd2/0xf0
[ 6720.144538]  [<ffffffff810914d0>] ? kthread_create_on_node+0x1c0/0x1c0
[ 6720.144541]  [<ffffffff8176f2d8>] ret_from_fork+0x58/0x90
[ 6720.144544]  [<ffffffff810914d0>] ? kthread_create_on_node+0x1c0/0x1c0
[ 6720.144566] INFO: task nfsd:1794 blocked for more than 120 seconds.
[ 6720.144666]       Tainted: P           OE 3.16.0-51-generic #69~14.04.1-Ubuntu
[ 6720.144769] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 6720.144876] nfsd            D ffff88045fc930c0     0  1794      2 0x00000004
[ 6720.144880]  ffff88043e86ba20 0000000000000046 ffff88043dcef010 ffff88043e86bfd8
[ 6720.144883]  00000000000130c0 00000000000130c0 ffff880449659e90 ffffffffc0624560
[ 6720.144887]  ffffffffc0624564 ffff88043dcef010 00000000ffffffff ffffffffc0624568
[ 6720.144890] Call Trace:
[ 6720.144895]  [<ffffffff8176b829>] schedule_preempt_disabled+0x29/0x70
[ 6720.144898]  [<ffffffff8176d675>] __mutex_lock_slowpath+0xd5/0x1d0
[ 6720.144902]  [<ffffffff8176d78f>] mutex_lock+0x1f/0x2f
[ 6720.144943]  [<ffffffffc04c52f6>] zfsctl_snapshot_unmount_delay+0x26/0xa0 [zfs]
[ 6720.144984]  [<ffffffffc04c6786>] zfsctl_lookup_objset+0x246/0x3a0 [zfs]
[ 6720.144987]  [<ffffffff8176d782>] ? mutex_lock+0x12/0x2f
[ 6720.145024]  [<ffffffffc048de78>] ? rrw_exit+0x68/0x170 [zfs]
[ 6720.145067]  [<ffffffffc04d97b6>] zfs_vget+0x176/0x3e0 [zfs]
[ 6720.145111]  [<ffffffffc04f7a02>] zpl_fh_to_dentry+0x72/0xb0 [zfs]
[ 6720.145123]  [<ffffffffc07c9930>] ? nfsd_proc_getattr+0xa0/0xa0 [nfsd]
[ 6720.145129]  [<ffffffff812c0932>] exportfs_decode_fh+0x72/0x2e0
[ 6720.145152]  [<ffffffffc06feae6>] ? cache_check+0x106/0x3d0 [sunrpc]
[ 6720.145161]  [<ffffffffc07cf68c>] ? exp_find+0xfc/0x1b0 [nfsd]
[ 6720.145165]  [<ffffffff811b7d16>] ? kmem_cache_alloc_trace+0x1c6/0x1f0
[ 6720.145169]  [<ffffffff81322537>] ? aa_alloc_task_context+0x27/0x40
[ 6720.145178]  [<ffffffffc07ca656>] fh_verify+0x2f6/0x5e0 [nfsd]
[ 6720.145183]  [<ffffffff811b67cb>] ? kfree+0xab/0x140
[ 6720.145192]  [<ffffffffc07d84c9>] nfsd4_putfh+0x49/0x50 [nfsd]
[ 6720.145201]  [<ffffffffc07da66f>] nfsd4_proc_compound+0x4ff/0x820 [nfsd]
[ 6720.145210]  [<ffffffffc07c6dab>] nfsd_dispatch+0xbb/0x200 [nfsd]
[ 6720.145224]  [<ffffffffc06f45b0>] svc_process_common+0x440/0x6d0 [sunrpc]
[ 6720.145232]  [<ffffffffc07c6670>] ? nfsd_destroy+0x80/0x80 [nfsd]
[ 6720.145246]  [<ffffffffc06f4947>] svc_process+0x107/0x170 [sunrpc]
[ 6720.145253]  [<ffffffffc07c6670>] ? nfsd_destroy+0x80/0x80 [nfsd]
[ 6720.145261]  [<ffffffffc07c6737>] nfsd+0xc7/0x130 [nfsd]
[ 6720.145264]  [<ffffffff810915a2>] kthread+0xd2/0xf0
[ 6720.145267]  [<ffffffff810914d0>] ? kthread_create_on_node+0x1c0/0x1c0
[ 6720.145271]  [<ffffffff8176f2d8>] ret_from_fork+0x58/0x90
[ 6720.145274]  [<ffffffff810914d0>] ? kthread_create_on_node+0x1c0/0x1c0
[ 6720.145276] INFO: task nfsd:1797 blocked for more than 120 seconds.
[ 6720.145376]       Tainted: P           OE 3.16.0-51-generic #69~14.04.1-Ubuntu
[ 6720.145478] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 6720.145585] nfsd            D ffff88045fc130c0     0  1797      2 0x00000004
[ 6720.145589]  ffff88043e687a50 0000000000000046 ffff880440118a30 ffff88043e687fd8
[ 6720.145592]  00000000000130c0 00000000000130c0 ffff8804495c4750 ffffffffc0624560
[ 6720.145596]  ffffffffc0624564 ffff880440118a30 00000000ffffffff ffffffffc0624568
[ 6720.145599] Call Trace:
[ 6720.145604]  [<ffffffff8176b829>] schedule_preempt_disabled+0x29/0x70
[ 6720.145607]  [<ffffffff8176d675>] __mutex_lock_slowpath+0xd5/0x1d0
[ 6720.145610]  [<ffffffff8176d78f>] mutex_lock+0x1f/0x2f
[ 6720.145651]  [<ffffffffc04c6574>] zfsctl_lookup_objset+0x34/0x3a0 [zfs]
[ 6720.145654]  [<ffffffff8176d782>] ? mutex_lock+0x12/0x2f
[ 6720.145690]  [<ffffffffc048de78>] ? rrw_exit+0x68/0x170 [zfs]
[ 6720.145732]  [<ffffffffc04d97b6>] zfs_vget+0x176/0x3e0 [zfs]
[ 6720.145735]  [<ffffffff8109ece5>] ? check_preempt_curr+0x85/0xa0
[ 6720.145738]  [<ffffffff8109ed19>] ? ttwu_do_wakeup+0x19/0xc0
[ 6720.145780]  [<ffffffffc04f7a02>] zpl_fh_to_dentry+0x72/0xb0 [zfs]
[ 6720.145788]  [<ffffffffc07c9930>] ? nfsd_proc_getattr+0xa0/0xa0 [nfsd]
[ 6720.145791]  [<ffffffff812c0932>] exportfs_decode_fh+0x72/0x2e0
[ 6720.145794]  [<ffffffff810a1b72>] ? default_wake_function+0x12/0x20
[ 6720.145799]  [<ffffffff810b50f2>] ? autoremove_wake_function+0x12/0x40
[ 6720.145802]  [<ffffffff810b49f8>] ? __wake_up_common+0x58/0x90
[ 6720.145805]  [<ffffffff810b4c84>] ? __wake_up+0x44/0x50
[ 6720.145808]  [<ffffffff810d4188>] ? __call_rcu_nocb_enqueue+0xc8/0xd0
[ 6720.145817]  [<ffffffffc07ca656>] fh_verify+0x2f6/0x5e0 [nfsd]
[ 6720.145820]  [<ffffffff811b67cb>] ? kfree+0xab/0x140
[ 6720.145829]  [<ffffffffc07d84c9>] nfsd4_putfh+0x49/0x50 [nfsd]
[ 6720.145838]  [<ffffffffc07da66f>] nfsd4_proc_compound+0x4ff/0x820 [nfsd]
[ 6720.145846]  [<ffffffffc07c6dab>] nfsd_dispatch+0xbb/0x200 [nfsd]
[ 6720.145860]  [<ffffffffc06f45b0>] svc_process_common+0x440/0x6d0 [sunrpc]
[ 6720.145868]  [<ffffffffc07c6670>] ? nfsd_destroy+0x80/0x80 [nfsd]
[ 6720.145882]  [<ffffffffc06f4947>] svc_process+0x107/0x170 [sunrpc]
[ 6720.145889]  [<ffffffffc07c6670>] ? nfsd_destroy+0x80/0x80 [nfsd]
[ 6720.145897]  [<ffffffffc07c6737>] nfsd+0xc7/0x130 [nfsd]
[ 6720.145900]  [<ffffffff810915a2>] kthread+0xd2/0xf0
[ 6720.145904]  [<ffffffff810914d0>] ? kthread_create_on_node+0x1c0/0x1c0
[ 6720.145907]  [<ffffffff8176f2d8>] ret_from_fork+0x58/0x90
[ 6720.145910]  [<ffffffff810914d0>] ? kthread_create_on_node+0x1c0/0x1c0
[ 6720.145924] INFO: task bash:4802 blocked for more than 120 seconds.
[ 6720.146023]       Tainted: P           OE 3.16.0-51-generic #69~14.04.1-Ubuntu
[ 6720.146126] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 6720.146233] bash            D ffff88045fcd30c0     0  4802   3466 0x00000000
[ 6720.146237]  ffff880062b67b40 0000000000000086 ffff88043b478000 ffff880062b67fd8
[ 6720.146240]  00000000000130c0 00000000000130c0 ffff88044965a8c0 ffffffffc0624560
[ 6720.146243]  ffffffffc0624564 ffff88043b478000 00000000ffffffff ffffffffc0624568
[ 6720.146247] Call Trace:
[ 6720.146251]  [<ffffffff8176b829>] schedule_preempt_disabled+0x29/0x70
[ 6720.146255]  [<ffffffff8176d675>] __mutex_lock_slowpath+0xd5/0x1d0
[ 6720.146258]  [<ffffffff8176d78f>] mutex_lock+0x1f/0x2f
[ 6720.146299]  [<ffffffffc04c62e1>] zfsctl_snapshot_mount+0x1e1/0x440 [zfs]
[ 6720.146341]  [<ffffffffc04f6a80>] zpl_snapdir_automount+0x10/0x30 [zfs]
[ 6720.146346]  [<ffffffff811de32a>] follow_managed+0x13a/0x300
[ 6720.146350]  [<ffffffff811ed420>] ? __d_lookup+0x120/0x160
[ 6720.146353]  [<ffffffff811deebb>] lookup_fast+0x18b/0x2c0
[ 6720.146357]  [<ffffffff812ebfec>] ? security_inode_permission+0x1c/0x30
[ 6720.146361]  [<ffffffff811deae2>] ? __inode_permission+0x52/0xc0
[ 6720.146364]  [<ffffffff811e01d7>] do_last+0xa7/0x1210
[ 6720.146368]  [<ffffffff8132cd2b>] ? apparmor_file_alloc_security+0x5b/0x180
[ 6720.146371]  [<ffffffff812ecbc6>] ? security_file_alloc+0x16/0x20
[ 6720.146374]  [<ffffffff811e32fb>] path_openat+0xbb/0x640
[ 6720.146377]  [<ffffffff811e4279>] ? putname+0x29/0x40
[ 6720.146380]  [<ffffffff811e4eef>] ? user_path_at_empty+0x5f/0x90
[ 6720.146382]  [<ffffffff811e4fda>] do_filp_open+0x3a/0x90
[ 6720.146386]  [<ffffffff811f1b47>] ? __alloc_fd+0xa7/0x130
[ 6720.146391]  [<ffffffff811d3909>] do_sys_open+0x129/0x280
[ 6720.146394]  [<ffffffff811d3a94>] SyS_openat+0x14/0x20
[ 6720.146397]  [<ffffffff8176f38d>] system_call_fastpath+0x1a/0x1f
[ 6840.144027] INFO: task z_unmount:315 blocked for more than 120 seconds.
[ 6840.144132]       Tainted: P           OE 3.16.0-51-generic #69~14.04.1-Ubuntu
[ 6840.144237] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 6840.144345] z_unmount       D ffff88045fcd30c0     0   315      2 0x00000000
[ 6840.144350]  ffff8804464d7d40 0000000000000046 ffff88009e8fa8c0 ffff8804464d7fd8
[ 6840.144354]  00000000000130c0 00000000000130c0 ffff88044965a8c0 ffffffffc0624560
[ 6840.144358]  ffffffffc0624564 ffff88009e8fa8c0 00000000ffffffff ffffffffc0624568
[ 6840.144361] Call Trace:
[ 6840.144381]  [<ffffffff8176b829>] schedule_preempt_disabled+0x29/0x70
[ 6840.144384]  [<ffffffff8176d675>] __mutex_lock_slowpath+0xd5/0x1d0
[ 6840.144388]  [<ffffffff8176d78f>] mutex_lock+0x1f/0x2f
[ 6840.144453]  [<ffffffffc04c5d7a>] zfsctl_snapshot_unmount+0x4a/0x170 [zfs]
[ 6840.144496]  [<ffffffffc04c5ec8>] snapentry_expire+0x28/0xb0 [zfs]
[ 6840.144507]  [<ffffffffc03c208d>] taskq_thread+0x20d/0x410 [spl]
[ 6840.144513]  [<ffffffff810a1b60>] ? wake_up_state+0x20/0x20
[ 6840.144521]  [<ffffffffc03c1e80>] ? taskq_cancel_id+0x120/0x120 [spl]
[ 6840.144526]  [<ffffffff810915a2>] kthread+0xd2/0xf0
[ 6840.144529]  [<ffffffff810914d0>] ? kthread_create_on_node+0x1c0/0x1c0
[ 6840.144533]  [<ffffffff8176f2d8>] ret_from_fork+0x58/0x90
[ 6840.144536]  [<ffffffff810914d0>] ? kthread_create_on_node+0x1c0/0x1c0

**Comment by behlendorf** [comment]
This is fixed in master by commit f22f900f15c28ebd8b8b764ee6229a7069c74a13.  It can be safely cherry-picked back to your version if needed to resolve the issue.  Sorry about that.
