### ISSUE TITLE
ZVOL /dev/disk/by-uuid and /dev/disk/by-label symlinks not created on Ubuntu Wily

### ISSUE THREAD

**Issue by samvde** [zfsonlinux/zfs#3951]
I previously had my swap area (on a zvol) configured by label in fstab. 

After upgrading to Ubuntu Wily and zfs 0.6.5.3-1, it appears the symlinks are no longer created. I have tried recreating the swap space, and importing by device scan as well as the cache file (using newly created initrd images), but so far I have not been able to trigger the creation of the symlinks.

Work around is trivial by using full device paths in fstab.

This issue did not exist on Vivid, and occurs on all upgraded machines. I'm not sure the issue is Ubuntu specific though. It might be systemd related.

I can test possible workarounds on my machine(s).

**Comment by runderwo** [comment]
This appears to still be happening with 0.7.x

**Comment by kpande** [comment]
yes, integration with fstab is a "best effort". maybe you can create a custom udev rule. otherwise full paths should work "forever".
