### ISSUE TITLE
Sudden death of kernel on access to snapshots via nfs 

### ISSUE THREAD

**Issue by IngoReimann** [zfsonlinux/zfs#3960]
Hi, 

I got a severe issue while reading a large file in an zfs/nfs-share:

Situation:
Server: Ubuntu 15.10, Kernel 4.2.0-16-lowlatency,
zfs 0.6.5.3 from http://ppa.launchpad.net/zfs-native/stable/ubuntu wily 
zfs share via nfs, zfs-auto-snapshot from 15.04

Client:  Ubuntu 15.04 - mounts the share

client wrote 12G file to the share, waits for snapshot to happen.
Afterwards access to .zfs/snapshot/zfs-auto-snap_SOME-TIMESTAMP

When trying to build md5sum on the file, the client process locks up after some minutes. No further snapshot activity happened during that time. Kernel on server throws "task nfsd:1925 blocked for more than 120 seconds."

On server, the next snapshot processes lock up. Reboot only is possible via sysreq.
Afterwards it starts up, but immediately freezes completely after some seconds. No keypress on console, no ICMP-ECHO. This happens again and again until i reboot the client!

For me it resembles like the old Ping of Death.

Is this a known behaviour? With my systems i may reproduce it.

regards,

ingo

**Comment by IngoReimann** [comment]
Just to add - we created the share with "exportfs" not via "zfs sharenfs". After we switched to "zfs sharenfs" everything seems to be stable.

**Comment by behlendorf** [comment]
@IngoReimann if it happens again could you please try and gather any debugging you can from the console.  I'm glad you've found a solution, but it's not clear why manually using exportfs to share the filesystems would have fixed the issue.

**Comment by behlendorf** [comment]
Several issues regarding accessing snapshots over nfs have been resolved since this issue was last updated.
