### ISSUE TITLE
"sharesmb=on" and "zfs" share do not work

### ISSUE THREAD

**Issue by SiliCAT** [zfsonlinux/zfs#3964]
I have tried many times in my vmware Debian box:

```
apt-get install debian-zfs samba
zpool create tank sdb
zfs create -o casesensitivity=mixed tank/srv
zfs set sharesmb=on tank/srv

zfs share tank/srv
cannot share 'tank/srv': filesystem already shared
```

But,
There is NOTHING shared by samba at localhost

I found there is no trace the "net" command being invoked: there is nothing under the path /var/lib/samba/usershares/

I  am using Debian 8.0 Jessie amd64, Did I do something wrong or it is a bug?

**Comment by FransUrbo** [comment]
> I found there is no trace the "net" command being invoked: there is nothing under the path /var/lib/samba/usershares/
> 
> I am using Debian 8.0 Jessie amd64, Did I do something wrong or it is a bug?
> 

If you're using the packages I provide at ZoL, then you're using the newer version of the sharesmb code (#1476) which uses REGISTRY shares instead.

Try

	net conf listshares

A problem is that if zfs-share isn't run (to unshare everything) at shutdown, they will remain and seen by samba when it starts up again after a reboot.

**Comment by sofakng** [comment]
I'm also having a problem...  what is the correct configuration for samba, zol, and the sharesmb setting?

I can get my share to work, but after a reboot ZFS complains that the share already exists and the zfs-share.service won't start.

**Comment by loli10K** [comment]
Closing as stale: feel free to comment providing basic info about your setup (https://github.com/zfsonlinux/zfs/blob/master/.github/ISSUE_TEMPLATE.md) if this can still be reproduced.
