### ISSUE TITLE
centos 7 modprobe fail

### ISSUE THREAD

**Issue by dmaziuk** [zfsonlinux/zfs#3986]
This is ugly because I've just updated 4 centos 7 machines to `3.10.0-229.20.1.el7.x86_64` kernel and _only on one_ of them I get

```
[root@batfish modules]# modprobe -v zfs
insmod /lib/modules/3.10.0-229.20.1.el7.x86_64/weak-updates/zfs.ko zfs_arc_max=2147483648 
modprobe: ERROR: could not insert 'zfs': Invalid argument
[root@batfish modules]# ls /lib/modules/3.10.0-229.20.1.el7.x86_64/weak-updates/
forcedeth  spl  splat.ko  spl.ko  zavl.ko  zcommon.ko  zfs  zfs.ko  znvpair.ko  zpios.ko  zunicode.ko
[root@batfish modules]# insmod /lib/modules/3.10.0-229.20.1.el7.x86_64/weak-updates/zfs.ko
insmod: ERROR: could not insert module /lib/modules/3.10.0-229.20.1.el7.x86_64/weak-updates/zfs.ko: Invalid parameters
```

They're all AMD SuperMicros, the one that's failing is the oldest -- something like 2008 vintage -- but is working just fine with the the previous build: `3.10.0-229.14.1.el7.x86_64`.

Weird.

**Comment by behlendorf** [comment]
@dmaziuk that is strange.  Could you include the `dmesg` output.  I suspect completely removing and reinstalling the packages would solve the issue.

**Comment by dmaziuk** [comment]
I think dmesg.old is the one you want, dmesg is with previous (working) kernel attached just for reference.
 
[dmesg.old.txt](https://github.com/zfsonlinux/zfs/files/33275/dmesg.old.txt)
[dmesg.txt](https://github.com/zfsonlinux/zfs/files/33276/dmesg.txt)

**Comment by chuckleb** [comment]
I also got this while updating my CentOS 7 machine. A clean remove/reinstall of zfs and spl fixed it. I followed the instructions here:
http://www.yuna.se/2015/11/23/zfs-on-centos-rebuild-after-yum-upgrade-fucks-up/

Simply, the instructions are:
yum erase zfs zfs-dkms libzfs2 spl spl-dkms 
yum install zfs

**Comment by rhagu** [comment]
Hi, I just encountered the same problem. I updated today after a long time of not logging into the machine. It is a supermicro board with Intel CPU: http://pastebin.com/SiqgX728

This is the error message I get with yum update: http://pastebin.com/tJAkYLPX

I am running CentOS Linux release 7.2.1511 (Core) at the moment.

**Comment by fishdust** [comment]
Same issue for me. I did what chuckleb mentioend:
`yum erase zfs zfs-dkms libzfs2 spl spl-dkms`
reboot
`yum install zfs`
reboot

**Comment by chuckleb** [comment]
I just ran updates last night and ran into same problem. Rebooted and no zfs. Did the yum erase, yum install, reboot and everything works. @fishdust, shouldn't need a reboot between erase and install.

**Comment by behlendorf** [comment]
Closing as stale.
