### ISSUE TITLE
kernel: PANIC: inode 1561 has invalid mode: 0x11

### ISSUE THREAD

**Issue by kevin0431** [zfsonlinux/zfs#3989]
Got another kernel panic after update zfs to 0.6.5.2, following instruction from issues#3921

Nov  2 19:14:43 kernel: SPL: Loaded module v0.6.5.2-1
Nov  2 19:14:43 kernel: ZFS: Loaded module v0.6.5.2-1, ZFS pool version 5000, ZFS filesystem version 5

Nov  2 19:00:07 kernel: PANIC: inode 1561 has invalid mode: 0x11
Nov  2 19:00:07 kernel:
Nov  2 19:00:07 kernel: Showing stack for process 18424
Nov  2 19:00:07 kernel: Pid: 18424, comm: glusterfsd Tainted: P           ---------------    2.6.32-504.23.4.el6.x86_64 #1
Nov  2 19:00:07 kernel: Call Trace:
Nov  2 19:00:07 kernel: [<ffffffffa027803d>] ? spl_dumpstack+0x3d/0x40 [spl]
Nov  2 19:00:07 kernel: [<ffffffffa02780cd>] ? vcmn_err+0x8d/0xf0 [spl]
Nov  2 19:00:07 kernel: [<ffffffffa03202a3>] ? sa_lookup_impl+0x13/0x20 [zfs]
Nov  2 19:00:07 kernel: [<ffffffffa03203e9>] ? sa_lookup+0x89/0xb0 [zfs]
Nov  2 19:00:07 kernel: [<ffffffffa02e2509>] ? dmu_object_size_from_db+0x69/0xa0 [zfs]
Nov  2 19:00:07 kernel: [<ffffffffa0332d72>] ? zfs_panic_recover+0x52/0x60 [zfs]
Nov  2 19:00:07 kernel: [<ffffffffa0378e95>] ? zfs_znode_alloc+0x315/0x510 [zfs]
Nov  2 19:00:07 kernel: [<ffffffffa0379319>] ? zfs_zget+0x289/0x310 [zfs]
Nov  2 19:00:07 kernel: [<ffffffffa034fa43>] ? zap_lookup_norm+0xc3/0x190 [zfs]
Nov  2 19:00:07 kernel: [<ffffffffa0359b6e>] ? zfs_dirent_lock+0x4be/0x580 [zfs]
Nov  2 19:00:07 kernel: [<ffffffffa0359e3b>] ? zfs_dirlook+0x8b/0x270 [zfs]
Nov  2 19:00:07 kernel: [<ffffffffa0352fc0>] ? zfs_zaccess+0xa0/0x2d0 [zfs]
Nov  2 19:00:07 kernel: [<ffffffffa031d242>] ? rrw_enter_read_impl+0xd2/0x180 [zfs]
Nov  2 19:00:07 kernel: [<ffffffffa037311f>] ? zfs_lookup+0x2ef/0x340 [zfs]
Nov  2 19:00:07 kernel: [<ffffffffa038ac1b>] ? zpl_lookup+0x9b/0x120 [zfs]
Nov  2 19:00:07 kernel: [<ffffffff8119de75>] ? do_lookup+0x1a5/0x230
Nov  2 19:00:07 kernel: [<ffffffff8119eb04>] ? __link_path_walk+0x7a4/0x1000
Nov  2 19:00:07 kernel: [<ffffffff8119f61a>] ? path_walk+0x6a/0xe0
Nov  2 19:00:07 kernel: [<ffffffff8119f82b>] ? filename_lookup+0x6b/0xc0
Nov  2 19:00:07 kernel: [<ffffffff811a0957>] ? user_path_at+0x57/0xa0
Nov  2 19:00:07 kernel: [<ffffffff811b650c>] ? getxattr+0x9c/0x170
Nov  2 19:00:07 kernel: [<ffffffff8119bd86>] ? final_putname+0x26/0x50
Nov  2 19:00:07 kernel: [<ffffffff8119c38b>] ? putname+0x2b/0x40
Nov  2 19:00:07 kernel: [<ffffffff81193d30>] ? vfs_fstatat+0x50/0xa0
Nov  2 19:00:07 kernel: [<ffffffff81193dee>] ? vfs_lstat+0x1e/0x20
Nov  2 19:00:07 kernel: [<ffffffff81193e14>] ? sys_newlstat+0x24/0x50
Nov  2 19:00:07 kernel: [<ffffffff8119c941>] ? path_put+0x31/0x40
Nov  2 19:00:07 kernel: [<ffffffff811b6641>] ? sys_lgetxattr+0x61/0x80
Nov  2 19:00:07 kernel: [<ffffffff8100b0f2>] ? system_call_fastpath+0x16/0x1b

**Comment by Retrodynen** [comment]
wtf?

**Comment by Biyoni** [comment]
lol cope

**Comment by Biyoni** [comment]
> 
> 
> wtf?

cope
