### ISSUE TITLE
Cannot reference bookmarks in `zfs get`, etc

### ISSUE THREAD

**Issue by DeHackEd** [zfsonlinux/zfs#3995]
<pre># zfs bookmark pool/dataset@replicace3 pool/dataset#replicate3

# zfs list -t bookmark
NAME                      USED  AVAIL  REFER  MOUNTPOINT
pool/dataset#replicate3      -      -      -  -

# zfs get all pool/dataset#replicate3
cannot open 'pool/dataset#replicate3': invalid dataset name

# zfs list -t bookmark -o name,creation,createtxg,guid
NAME                     CREATION               CREATETXG   GUID
pool/dataset#replicate3  Fri Oct 30 15:54 2015      8.70K  13502112369419254620
</pre>

Boomarks have properties which are potentially of interest to users, but you cannot get the information for a specific bookmark. The only way I know of to get information out of bookmarks is to use a broad `zfs list -t bookmark` command.

(For the curious, the properties above are from the snapshot and not representative of the time the bookmark was taken.)

**Comment by mailinglists35** [comment]
I am also interested in getting properties for bookmarks

**Comment by mailinglists35** [comment]
additionally -o createtxg is not even documented. are there any undocumented properties other that createtxg?

**Comment by loli10K** [comment]
@mailinglists35 this shoud be fixed by _OpenZFS 7386 - zfs get does not work properly with bookmarks_ (https://github.com/openzfs/openzfs/commit/edb901a) once that gets integrated.

> are there any undocumented properties other that createtxg?

https://github.com/zfsonlinux/zfs/blob/zfs-0.7.0-rc3/module/zcommon/zfs_prop.c#L467

**Comment by gmelikov** [comment]
I ported it in #5666,  reviewers are welcome.

**Comment by DeHackEd** [comment]
Presumed fixed by #5666 merge
