### ISSUE TITLE
Issue with ecryptfs and ZFS snapshot directory (.zfs) - unable to access, permission denied

### ISSUE THREAD

**Issue by abraunegg** [zfsonlinux/zfs#4000]
When using ecryptfs and mounting the decrypted data, any attempt to access the snapshot directory results in a permission denied error, with the following kernel messages:

```
Nov  5 20:57:57 testserver kernel: Error opening lower file for lower_dentry [0xffff88003e1cc0c0] and lower_mnt [0xffff88003aa0d2a0]; rc = [-13]
Nov  5 20:57:57 testserver kernel: ecryptfs_open: Error attempting to initialize the lower file for the dentry with name [.zfs]; rc = [-13]
```

From the strace log, the problem is listed as:

```
> open(".", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 EACCES (Permission denied)
```

Attached is the strace log of the issue, along with a trace-cmd data file:

https://github.com/abraunegg/zfs-debug/blob/master/strace.txt
https://github.com/abraunegg/zfs-debug/blob/master/trace.dat

**Comment by rlaager** [comment]
I looked into this quite a while ago. The details are fuzzy, but I think it there's some automount flag or callback or something that's set on .zfs or .zfs/snapshots.

**Comment by rlaager** [comment]
I think this is one of those CANTFIX or WONTFIX bugs. Hopefully ZFS encryption in #4329 lands soon.
