### ISSUE TITLE
degraded zpool can't be destroy or export

### ISSUE THREAD

**Issue by dsw0350** [zfsonlinux/zfs#4003]
I use the following commands:
1) zpool create -f test raidz sdb sdc sdd
2) zfs create test/fold00
3) dd if=/dev/zero of=/test/fold00/a.txt bs=4k
Then I pull out two disks:sdb,sdc.
The zpool test is degraded and i want to destroy it,but the command "zpool destroy test" doesn't work,with or with "-f" option. "zpool export test" doesn't work either.
Do i have another option except to restart the computer?

system:CentOS-6.5-x86_64

best regard,thanks

**Comment by ilovezfs** [comment]
Destroy doesn't make sense if the devices are not present, but export may be possible.

You can try offlining the sdb and sdc first, and then exporting.
```
zpool offline test sdb
zpool offline test sdc
zpool export test 
```

Does that succeed or fail as well?

**Comment by dsw0350** [comment]
#zpool offline test sdb
can't offline sdb: pool I/O is currently suspended
#zpool offline test sdc
can't offline sdb: pool I/O is currently suspended
#zpool export test
umount: /test/fold00: device is busy.
        (in some cases useful info about processs that use the device is found by lsof(8) or fuser(1))
cannot unmount "/test/fold00":umount failed

All of the command are failed.
I don't want to restart the computer, but i don't know how to deal with it.

**Comment by ilovezfs** [comment]
You will likely need to reboot.

Is this possible?

```
umount -l /test/fold000
```

**Comment by dsw0350** [comment]
"umount -l /test/fold00" doesn't report any errors, but "zpool export test" hangs.

**Comment by ilovezfs** [comment]
And control+C is also probably not possible now on the export?

Sounds like it's reboot time to me.

**Comment by dsw0350** [comment]
control +c works,command "zpool export test" exit.
But the test pool is still there.
I try zpool export test again,and it reports error:cannot export "test": pool I/O is currently suspended.
I cannot kill "dd if=/dev/zero of=/test/fold00/a.txt bs=4k" process.

**Comment by ilovezfs** [comment]
What's the output of

```
# ps aux | grep zpool
# ps aux | grep zfs
```

And are the original sdb, sdc devices available to be plugged back in?

**Comment by dsw0350** [comment]
#ps -ef | grep zfs 
/bin/umount -t zfs /test
[zfs_iput_taskq/]
/bin/sh /etc/zfs/zed.d/io-spare.sh

there is no any process about zpool.

plugge back in the original disks makes no difference.

**Comment by ilovezfs** [comment]
Once you plug them back in, can you determine their new names from lsblk, or similar?

**Comment by dsw0350** [comment]
I use scsi_id to create zpool and plug disks back in doesn't work either.
By scsi_id,i mean /dev/disk/by-id/scsi-xxxxxxx

**Comment by ilovezfs** [comment]
Correct. You would need to create symlinks named /dev/sdb, /dev/sdb1, /dev/sdc, /dev/sdc1 to the current device names and issue zpool clear for it to have even a chance at working.

**Comment by dsw0350** [comment]
when i create zpool with -f option, symlinks name /dev/disk/by-id/scsi-xxxx1, /dev/disk/by-id/scsi-xxxx9 are created.
destroy or export are still failed.
I have no idea to make it work.

**Comment by ilovezfs** [comment]
Yes, the additional /dev/disk/by-* links are created automatically by udev when zfs partitions disks. However, you created the pool using the names sdb and sdc, so zfs knows them by those names, not by any of the names in /dev/disk/by-*, and you would need to "trick" zfs into finding them by those names again.

What are the current /dev/sd* device names now that you plugged them back in?

```
ls -lt /dev/ | grep sd
ls -lt /dev/disk/by-id/ | grep sd
```

**Comment by dsw0350** [comment]
@ilovezfs Thank you very much. I have tried to use /dev/disk/by-id/scsi-xxx to create zpool. Do the same steps, and  get the same result as before. Using /dev/disk/by-id/scsi-xxx cannot solve the problem.
