### ISSUE TITLE
vdev_id broken in Centos 6.7

### ISSUE THREAD

**Issue by dbdavids** [zfsonlinux/zfs#4007]
In Centos 6.6 vdev_id works as expected becaues it can look in the following locations for a slot number for the drive.

/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/host0/port-0:0/expander-0:0/port-0:0:1/end_device-0:0:1/sas_device/end_device-0:0:1/bay_identifier or port_identifer.

in 6.7, these do not exist for some reason.  You can similarly get a number by pulling from the following command in 6.7

ls /sys`udevadm info -q path -p /sys/block/sdg`/device|grep enclosure_device|tr -dc '0-9'

Its quickly getting beyond my abilities, and I am not sure my suggestion is the best way to go about it, but until there is a fix, I cannot use ZFS based off the slot numbering, only the drive letter or other identifiers.

**Comment by dbdavids** [comment]
udevadm .../sdg is supposed to have backticks around it.

**Comment by behlendorf** [comment]
Is this still an issue?  I wasn't able to reproduce the problem with the latest CentOS.

**Comment by behlendorf** [comment]
Closing as out of date.
