### ISSUE TITLE
How do I destroy a hidden and damaged zvol?

### ISSUE THREAD

**Issue by rgronlund** [zfsonlinux/zfs#4010]
I am sorry if this is not the right place for this question, but I am in a bit of a quandary. 
A scrub of the zfs pool highlighted a damaged file, in this case its a zvol which we used for an iscsi target, and zfs list can no longer see it? As the zvol is no longer used I want to get rid of it but I want to keep the rest of the data in the pool intact. 
How is the best way to remove it?
Can I export/import the zpool in its current state to another host?

**Comment by rgronlund** [comment]
Any chance someone can answer this as I would like to move the pool to a server with a newer version of ZFS as we are experiencing problems with zfs_iput-taskq problem?

**Comment by behlendorf** [comment]
If you know the name of the zvol try destroying it with `zfs destroy`.  If it doesn't appear in `zfs list` you may be able to find the name by running `zdb -d <pool-name>`.  Regardless of if you manage to destroy the zvol you can safely export and import the pool on a new host.

**Comment by rgronlund** [comment]
Thanks for that. The output i get is

[root@fs2 pipelines]# zdb -d melbfs
WARNING: can't open objset for melbfs/iscsitest
zdb: can't open 'melbfs': Input/output error
[root@fs2 pipelines]#

where iscsitest is the item marked as corrupt when doing a zpool status -v

Good to know i can export and import still.

Cheers

Rowan

**Comment by behlendorf** [comment]
And `zfs destroy melbfs/iscsitest` can't remove it?

**Comment by rgronlund** [comment]
Am a bit paranoid about running something like that as there is a lot of data at stake. Is there any chance that running it will impact other data in the pool?

**Comment by behlendorf** [comment]
If the pool was 100% healthy I'd say there was zero risk.  Still, I like to be extra cautious too.  I'd suggest you just send/recv all the datasets you want in the melbfs pool to a new pool on the new host.  Then there's no risk.

**Comment by rgronlund** [comment]
Ok, that will take some time, but i will do that.

Thanks for your help

**Comment by rgronlund** [comment]
So the server with the zpool crashed and so we did a zpool import into the other server which went fine except for the expected reporting of the previous fault
[root@fs1 ~]# zpool import -f melbfs
cannot iterate filesystems: I/O error

The pool reported fine, but didn't automatically mount so ran
[root@fs1 ~]# zfs mount -a
cannot iterate filesystems: I/O error

Which mount everything except one zfs section and has sat there for over 9 hours

[root@fs1 biodata]# zfs list
cannot iterate filesystems: I/O error
NAME               USED  AVAIL  REFER  MOUNTPOINT
melbfs             217T  31.2T  76.4K  none
melbfs/GTArchive  9.57T  31.2T  9.50T  -
melbfs/LinuxHome   364G  31.2T   364G  /LinuxHome
melbfs/Runs        150G  31.2T   150G  /Runs
melbfs/agrf        677G  31.2T   677G  /agrf
melbfs/archive    46.4T  31.2T  46.4T  /archive
melbfs/biodata     149T  31.2T   149T  /biodata
melbfs/data        664G  31.2T   664G  /data
melbfs/data0      15.3G  31.2T  15.3G  /data0
melbfs/home       1.64T  31.2T  1.64T  /home
melbfs/iscsi      6.04T  33.2T  4.06T  -
melbfs/melbsan01  2.99T  31.2T  2.99T  /melbsan01
tank              11.3T  5.40T  1.24T  /tank
tank/appl          116G  5.40T   116G  /tank/appl
tank/home         10.9G  5.40T  10.9G  /tank/home
tank/scratch      8.79T  5.40T  8.79T  /tank/scratch
tank/test         1.15T  5.40T  1.03T  /tank/test

The melbfs/biodata is the one still outstanding and when i attempt to mount it individually it comes back with

[root@fs1 ~]# zfs mount melbfs/biodata
filesystem 'melbfs/biodata' is already mounted
cannot mount 'melbfs/biodata': mountpoint or dataset is busy

zpool status -v

shows the pool is fine but it looks like its going through finding the CRC errors from the damaged iscsitest vdev

Is there any way to see what its up to?

**Comment by behlendorf** [comment]
@rgronlund if the original `zfs mount -a` appears to be hanging I'd first verify that there are no ASSERT/VERIFY/BUG errors in the `dmesg` output.  Assuming the log is clean and the mount command is still hanging I'd grab a stack trace from the `zfs mount` process.  You can do this with `cat /proc/<mount pid>/stack`, that should give us some idea as to why it's blocked if you post it in to the issue.

However, my best guess is that it's replaying a very large ZIL.  Depending on how long the filesystem was mounted, how many creates/unlinks happened, and what version it was running it may take a while to replay the log.  The best thing to do is wait it out if it's clearly making progress.
