### ISSUE TITLE
Failed for build latest ZoL's master branch update as buitin on the zen-kernel 4.3/master & same error with vanilla kernel linux-4.3

### ISSUE THREAD

**Issue by sergiall** [zfsonlinux/zfs#4013]
LD [M]  drivers/staging/lustre/lustre/ptlrpc/ptlrpc.o
  Building modules, stage 2.
  MODPOST 3987 modules
ERROR: "spl_kmem_alloc" [fs/zfs/zpios/zpios.ko] undefined!
ERROR: "spl_panic" [fs/zfs/zpios/zpios.ko] undefined!
ERROR: "spl_vmem_zalloc" [fs/zfs/zpios/zpios.ko] undefined!
ERROR: "spl_vmem_alloc" [fs/zfs/zpios/zpios.ko] undefined!
ERROR: "spl_kmem_free" [fs/zfs/zpios/zpios.ko] undefined!
ERROR: "spl_vmem_free" [fs/zfs/zpios/zpios.ko] undefined!
ERROR: "spl_kmem_zalloc" [fs/zfs/zpios/zpios.ko] undefined!
ERROR: "spl_kmem_zalloc" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "kmem_asprintf" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "taskq_member" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "spl_kmem_cache_destroy" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "__kstat_set_raw_ops" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "kstat_waitq_exit" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "crgetfsuid" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "spl_kmem_cache_alloc" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "taskq_cancel_id" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "z_compress_level" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "spl_kmem_cache_free" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "z_uncompress" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "vn_openat" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "taskq_wait_outstanding" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "crgetfsgid" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "tsd_create" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "__thread_exit" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "system_taskq" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "__cv_broadcast" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "__kstat_create" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "kstat_runq_exit" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "__udivdi3" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "taskq_destroy" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "crgetgid" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "vn_releasef" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "vcmn_err" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "kmem_vasprintf" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "spl_vmem_zalloc" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "crgetuid" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "__cv_wait_io" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "spl_panic" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "tsd_destroy" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "ddi_strtoull" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "vn_rdwr" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "__cv_signal" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "vn_remove" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "cmn_err" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "tsd_get" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "spl_kmem_free" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "__kstat_install" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "taskq_init_ent" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "kmem_debugging" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "taskq_dispatch" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "ddi_copyout" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "__cv_wait_sig" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "tsd_set" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "strfree" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "zone_get_hostid" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "spl_vmem_alloc" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "vn_getattr" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "kstat_waitq_enter" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "__cv_wait" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "vn_fsync" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "kstat_runq_enter" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "kobj_get_filesize" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "vn_getf" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "groupmember" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "kobj_open_file" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "vn_open" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "crgetngroups" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "heap_arena" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "crgetruid" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "crgetgroups" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "taskq_create" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "__kstat_delete" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "vn_set_pwd" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "crfree" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "p0" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "strdup" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "kobj_read_file" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "kobj_close_file" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "rootdir" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "vmem_size" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "__umoddi3" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "spl_kmem_cache_create" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "taskq_wait" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "vn_mode_to_vtype" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "__cv_timedwait_sig" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "spl_kmem_alloc" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "__cv_destroy" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "vn_seek" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "taskq_dispatch_ent" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "cv_timedwait_hires" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "ddi_copyin" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "__thread_create" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "taskq_wait_id" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "spl_kmem_cache_set_move" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "crhold" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "spl_kmem_cache_reap_now" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "vn_close" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "zio_arena" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "__cv_init" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "spl_vmem_free" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "__divdi3" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "taskq_dispatch_delay" [fs/zfs/zfs/zfs.ko] undefined!
ERROR: "spl_kmem_alloc" [fs/zfs/zcommon/zcommon.ko] undefined!
ERROR: "__umoddi3" [fs/zfs/zcommon/zcommon.ko] undefined!
ERROR: "cmn_err" [fs/zfs/zcommon/zcommon.ko] undefined!
ERROR: "spl_kmem_free" [fs/zfs/zcommon/zcommon.ko] undefined!
ERROR: "spl_kmem_alloc" [fs/zfs/nvpair/znvpair.ko] undefined!
ERROR: "spl_panic" [fs/zfs/nvpair/znvpair.ko] undefined!
ERROR: "spl_vmem_alloc" [fs/zfs/nvpair/znvpair.ko] undefined!
ERROR: "ddi_strtol" [fs/zfs/nvpair/znvpair.ko] undefined!
ERROR: "xdrmem_create" [fs/zfs/nvpair/znvpair.ko] undefined!
ERROR: "spl_kmem_free" [fs/zfs/nvpair/znvpair.ko] undefined!
WARNING: modpost: Found 5 section mismatch(es).
To see full details build your kernel with:
'make CONFIG_DEBUG_SECTION_MISMATCH=y'
scripts/Makefile.modpost:90: recipe for target '__modpost' failed
make[2]: **\* [__modpost] Error 1
Makefile:1095: error make recipe for target «modules»
make[1]: **\* [modules] Error 2
make[1]: exit dir «/media/BUILD/zen++»
debian/ruleset/targets/common.mk:295: error for make target «debian/stamp/build/kernel»
make: **\* [debian/stamp/build/kernel] Error 2

spl & zfs master branches was cloning and configured with:
./autogen.sh
./configure --enable-linux-builtin --with-linux=../../zen++ (my local build kernel dir)
./copy-builtin ../../zen++
for eatch.
The spl was change as builtin [*] by menuconfig and zfs was sort as module [M]
Stage 1 and 2 of kernel build process leave without errors, but this is trap! 
Any solutions?Ideas?Sorry for my bad english...

**Comment by gedia** [comment]
Sounds a lot like spl bug #498, which I submitted last week. Haven't been able to find a workaround so far...

**Comment by gmelikov** [comment]
Close as stale.

If it's actual - feel free to reopen.
