### ISSUE TITLE
Linux 4.4 compat: make_request_fn return type changed && const changes

### ISSUE THREAD

**Issue by DeHackEd** [zfsonlinux/zfs#4021]
See torvalds/linux@dece16353ef47d8d33f5302bc158072a9d65e26f for the `make_request_fn` change

Another change comes from torvalds/linux@e409de992e3ea3674393465f07cc71c948edd87a where "const" was added to a number of xattr function parameters. This produces compiler warnings but still builds.

**Comment by behlendorf** [comment]
Thanks for the heads up.

**Comment by behlendorf** [comment]
Fixed in master:

61d482f Linux 4.4 compat: xattr operations takes xattr_handler
1a09371 Linux 4.4 compat: make_request_fn returns blk_qc_t

**Comment by philmmanjaro** [comment]
Well, using dkms this ends in:
```
checking whether fops->read/write_iter() are available... yes
checking whether kmap_atomic wants 1 args... yes
checking whether follow_down_one() is available... yes
checking whether make_request_fn() returns int... no
checking whether make_request_fn() returns void... configure: error: no - Please file a bug report at
			    https://github.com/zfsonlinux/zfs/issues/new
```
Tested with zfs 0.6.5.2 and Linux 4.4-rc3.

**Comment by philmmanjaro** [comment]
Forget my comment. It works. I just had to [patch it properly](https://github.com/manjaro/packages-extra/blob/master/zfs-dkms/PKGBUILD):
```
checking whether make_request_fn() returns int... no
checking whether make_request_fn() returns void... no
checking whether make_request_fn() returns blk_qc_t... yes
```
