### ISSUE TITLE
0.6.4 -> 0.6.5.1/0.6.5.2/0.6.5.3 upgrade created an error in my dataset

### ISSUE THREAD

**Issue by mailinglists35** [zfsonlinux/zfs#4022]
I was running 0.6.4 and I ran an apt-get update/upgrade.
On my amd64 debian wheezy, packages were upgraded to:

zfs-dkms: 0.6.5.2-2-wheezy
spl-dkms: 0.6.5-1-wheezy

(why are they not using the same version numbers?!)

after the upgrade, zfs-dkms failed to compile, I've got frustrated by this unexpected failed upgrade so I can't remember what exact error I was given, I purged all zfs/spl packages and manually generated the debs from the 0.6.5.3 tarballs following build instructions from the main zol webpage.

after importing the pool using0.6.5.3, I've got this error:

    errors: Permanent errors have been detected in the following files:
            mypool:<0x19a712>

I ran the scrub, but that didn't make a difference.

`zdb -dddd mypool 0x19a712` shows this

    Dataset mos [META], ID 0, cr_txg 4, 155M, 5625 objects, rootbp DVA[0]=<0:a808117000:1000> DVA[1]=<0:2a1c7a7000:1000> DVA[2]=<0:7090cdd000:1000> [L0 DMU objset] fletcher4 uncompressed LE contiguous unique triple size=800L/800P birth=4888577L/4888577P fill=5625 cksum=a690907cd:120174188a2e:fac9605203a71:927d077437be3a5
    
        Object  lvl   iblk   dblk  dsize  lsize   %full  type
    zdb: dmu_bonus_hold(1681170) failed, errno 2

not sure if this is the correct way to fuel zdb with an object id (prefixed or not with `0x`), I ran it again without the `0x `prefix

    Dataset mos [META], ID 0, cr_txg 4, 155M, 5625 objects, rootbp DVA[0]=<0:a808117000:1000> DVA[1]=<0:2a1c7a7000:1000> DVA[2]=<0:7090cdd000:1000> [L0 DMU objset] fletcher4 uncompressed LE contiguous unique triple size=800L/800P birth=4888577L/4888577P fill=5625 cksum=a690907cd:120174188a2e:fac9605203a71:927d077437be3a5

        Object  lvl   iblk   dblk  dsize  lsize   %full  type
            19    1    16K    512  12.0K    512  100.00  DSL deadlist map (K=inherit) (Z=inherit)
                                            320   bonus  DSL deadlist map hdr
            dnode flags: USED_BYTES
            dnode maxblkid: 0
            microzap: 512 bytes, 1 entries
    
                    0 = 20
    Indirect blocks:
                   0 L0 0:1d000:1000 0:2c0001d000:1000 0:580000b000:1000 200L/200P F=1 B=4/4
    
                    segment [0000000000000000, 0000000000000200) size   512

What is this and how do I get rid of it without destroying the pool/dataset?

**Comment by mailinglists35** [comment]
root@bkp1:~# zpool status -v
      pool: mypool
     state: ONLINE
    status: One or more devices has experienced an error resulting in data
            corruption.  Applications may be affected.
    action: Restore the file in question if possible.  Otherwise restore the
            entire pool from backup.
       see: http://zfsonlinux.org/msg/ZFS-8000-8A
      scan: scrub repaired 0 in 2h43m with 0 errors on Tue Nov 17 06:46:30 2015
    config:
    
            NAME        STATE     READ WRITE CKSUM
                mypool     ONLINE       0     0     0
              mirror-0  ONLINE       0     0     0
                sdb3    ONLINE       0     0     0
                sda3    ONLINE       0     0     0
    
    errors: Permanent errors have been detected in the following files:
    
            mypool:<0x19a712>

**Comment by mailinglists35** [comment]
root@bkp1:~# zdb -c mypool
    
    Traversing all blocks to verify metadata checksums and verify nothing leaked ...
    
    loading space map for vdev 0 of 1, metaslab 104 of 115 ...
     572G completed ( 209MB/s) estimated time remaining: 0hr 00min 00sec
            No leaks (block sum matches space maps exactly)
    
            bp count:         7271287
            ganged count:           0
            bp logical:    831131446784      avg: 114303
            bp physical:   605273475072      avg:  83241     compression:   1.37
            bp allocated:  614562676736      avg:  84519     compression:   1.35
            bp deduped:             0    ref>1:      0   deduplication:   1.00
            SPA allocated: 614562676736     used: 62.21%
    
            additional, non-pointer bps of type 0:      13406
            Dittoed blocks on same vdev: 392524

**Comment by FransUrbo** [comment]
Please read http://zfsonlinux.org/faq.html#WhereDoIReportProblems

This belong to https://github.com/zfsonlinux/pkg-zfs - please close this and open a new in the correct issue tracker.

**Comment by behlendorf** [comment]
@mailinglists35 your pool looks very much intact and the permanent error appears to be for an object which was already removed.  How that could have happened isn't clear, unfortunately there's not a real easy way to clear the error log without using send/recv.

**Comment by mailinglists35** [comment]
I don't remember where I've read that someone fixed a similar issue by running the scrub *twice*
So I ran the scrub again, and the error is gone.
