### ISSUE TITLE
Attempting to reproduce Illumos #4986 wedges the threads

### ISSUE THREAD

**Issue by rincebrain** [zfsonlinux/zfs#4028]
<pre>zfs create monolith/foo
zfs set refquota=150M monolith/foo
zfs set compression=off monolith/foo
dd if=/dev/zero of=/monolith/foo/y bs=1M count=200
zfs snapshot monolith/foo@1
zfs snapshot monolith/foo@2
zfs send -R monolith/foo@2 | zfs recv monolith/bar</pre>
The above sequence will wedge a pool named monolith.

<pre># modinfo spl | grep ^version:
version:        0.6.5.3-1
# modinfo zfs | grep ^version:
version:        0.6.5.2-2</pre>

dmesg output:
[zfs wedge.txt](https://github.com/zfsonlinux/zfs/files/40281/zfs.wedge.txt)

Both send and recv are stuck in state D and unkillable.

edit to be more precise: the pool appears to be servicing requests other than the send and recv normally, for now, so this is not a wedge of the entire pool, just those taskqs.

**Comment by rincebrain** [comment]
Ah, apparently this is just a really nice way (? I haven't tried rebooting and confirming reproduction) to reproduce the dynamic_taskq deadlock, since I discovered my spl module version that's _running_ is 0.6.5.2, and dynamic_taskq is set to 1. (0.6.5.3 was built but not rebooted into yet.)

**Comment by rincebrain** [comment]
Yeah, it appears to reproduce the dynamic_taskq deadlock every time on a couple of reboots, with spl_thread_taskq_dynamic forced to 1 on 0.6.5.3. Nice.

**Comment by tuxoko** [comment]
This is fixed in master https://github.com/zfsonlinux/spl/commit/f5f2b87df0362242b13b8183a2a8d88be63b0e73

**Comment by rincebrain** [comment]
Neat. Any idea when that'll make it into a release, or should I just live dangerously and run git HEAD?

**Comment by behlendorf** [comment]
@rincebrain it's fixed in 0.6.5.3 too, just in a slightly different way.  And git HEAD isn't that dangerous if you want to give it a try!
