### ISSUE TITLE
Insufficient privileges to view errors in zpool status

### ISSUE THREAD

**Issue by sempervictus** [zfsonlinux/zfs#4031]
This looks to be a fun one - a single-disk pool seems to be having some sort of disagreement with the controller its on and intermittently turning itself off and on. Whats fun is that zpool status -v wont show the 9 data errors, just says:

```
zpool status -v
  pool: 1diskpool
 state: ONLINE
status: One or more devices are faulted in response to IO failures.
action: Make sure the affected devices are connected, then run 'zpool clear'.
   see: http://zfsonlinux.org/msg/ZFS-8000-HC
  scan: none requested
config:

    NAME                             STATE     READ WRITE CKSUM
    1diskpool                   ONLINE       1     8     0
      dm-name-crypt_WD-SERIAL  ONLINE       1     0     0

errors: List of errors unavailable (insufficient privileges)
```

**Comment by oddcoder** [comment]
I have the same bug ... for some reason the list of errors are unavailable 
if sudo is not privileged enough ... who is ?!

**Comment by oddcoder** [comment]
got the same problem and solved it with
`sudo zpool clear 1diskpool`

**Comment by Blackclaws** [comment]
Its rather easy to create this error using files as block devices and mucking about in them using dd. 

However you get CKSUM errors then which makes zpool clear unusable (depending on where you muck about you will destroy the metadata). It would still be nice to be able to see what was actually lost or what errors happened.
