### ISSUE TITLE
Implement/add search by commit functionality (mirror)

### ISSUE THREAD

**Issue by kernelOfTruth** [zfsonlinux/zfs#4035]
Since github doesn't allow searching by commit message or commit content

I remembered that bitbucket offers that functionality:

https://blog.bitbucket.org/2010/12/03/repository-search-filtering/

Adding that as a mirror to github would make doing quick searches for code changes way more comfortable, especially in the absence of access to git itself (e.g. when on the move)

Perhaps git.kernel.org would work as well ? Its servers are very fast and the search functionality not but, not sure though how their opinion about ZFS is

**Comment by behlendorf** [comment]
Closing.  Anyone can mirror the project wherever they like.
