### ISSUE TITLE
Zfs send high cpu utilization

### ISSUE THREAD

**Issue by Lukapo-logcheck** [zfsonlinux/zfs#4036]
Hello,
when I am trying to send larger snapshots like 5GB+, then zfs uses whole one core and is sending data in about 1Mbit/s, but sometimes it goes high as 800Mbit/s.
I tried to lower cpu utilization by settings cipher blowfish/rc4, but it didn't help.
Also I tried to work with mbuffer, but it was even worse (maybe I used it badly).
I am testing it on server for testing purposes and it is old C2Q, but I think it should be okay for streaming zfs snapshots.
If snapshot is smaller than 5Gb, then it streams all the time at about 800Mbit/s.

**Comment by Lukapo-logcheck** [comment]
Now I tried it on one production server and speeds are even lower...
When I send it into /dev/null, then everything is running fast...

**Comment by behlendorf** [comment]
@Lukapo-logcheck what version of ZFS.  Also be aware ZFS will only send data as fast as it can be received, which may be way sending it to /dev/null is fast.

**Comment by RubenKelevra** [comment]
I had the same issue, it is already fixed on centos-repo since this bug-report has been opend. @Lukapo-logcheck do you confim?
