### ISSUE TITLE
Cache device changes ashift after reboot

### ISSUE THREAD

**Issue by tjikkun** [zfsonlinux/zfs#4037]
Because of reasons mentioned in http://list.zfsonlinux.org/pipermail/zfs-discuss/2015-November/023820.html we need to set ashift=9 on our L2ARC devices. However after a reboot the revert back to the default value for the specific device. (Well actually that is a guess, because I don't know how to read the currect ashift for a cache device, it is not listed in zdb. The problem reappears after a boot, and disappears again after re-adding with ashift=9)

ZFS version:
0.6.4.2

**Comment by dasjoe** [comment]
This looks like https://www.illumos.org/issues/5219

**Comment by tjikkun** [comment]
Cache device is OCZ-SABER1000
Sector Sizes:     512 bytes logical, 4096 bytes physical

**Comment by dasjoe** [comment]
The original issue causing you to manually switch to ashift=9 has been fixed in https://github.com/zfsonlinux/zfs/commit/ef56b0780c80ebb0b1e637b8b8c79530a8ab3201 which is in the currently supported release 0.6.5.3.

I didn't realise you were still on 0.6.4.2, please upgrade to the current release and see whether both this and your original issue persist.

**Comment by tjikkun** [comment]
Yeah unfortunately 0.6.5* has not been stable for us so we can't upgrade at the moment.

**Comment by dasjoe** [comment]
As said on IRC, 0.6.4 will no longer receive fixes. The issues you had with 0.6.5.2 should be fixed in 0.6.5.3.

**Comment by chjohnst** [comment]
Are there 0.6.5.3 debs yet?

**Comment by dasjoe** [comment]
On 11/30/2015 03:41 PM, Christopher Johnston wrote:
> Are there 0.6.5.3 debs yet?

Yes, as always generic debs are available:
http://zfsonlinux.org/generic-deb.html

@dajhorn's PPA for Ubuntu is on 0.6.5.3, too.

ZoL's Debian maintainer (@FransUrbo) has not replied to my mails about
0.6.5.3 yet, if I remember correctly he plans to discontinue the
packages once ZFS becomes available from the official Debian repositories.

-- 
Regards,
Hajo Möller

**Comment by loli10K** [comment]
Supposedly fixed in https://github.com/zfsonlinux/zfs/commit/ef56b0780c80ebb0b1e637b8b8c79530a8ab3201 which is in the stable 0.6.5 branch.
