### ISSUE TITLE
Starting strace on zfs receive terms the process

### ISSUE THREAD

**Issue by tomassrnka** [zfsonlinux/zfs#4046]
We found a strange behaviour on 0.6.5.3+, starting strace -p <pid> on zfs receive process causes the process to terminate.

**Comment by DeHackEd** [comment]
Related to #810, the SIGSTOP involved in tracing the process nukes the job.

Send and Receive are (almost) entirely in-kernel operations invoked by a single system call. It can't be interrupted. Forcing the issue makes the job abort.

**Comment by loli10K** [comment]
Duplicate of #810
