### ISSUE TITLE
Unexplained data corruption as a result of routine disk replacement

### ISSUE THREAD

**Issue by yacoob** [zfsonlinux/zfs#4047]
I'm not sure whether this will be a useful bug report, but here it goes.

tl;dr: I've replaced a disk in my zfs pool and found a number of corrupted files after a reboot. 

Here's a postmortem for this event
https://goo.gl/GlL6WN
If you read through it, you'll most likely find that it does look like a bug in ZFS - and not a hardware problem. The main problem with this event is that I can't really provide much evidence that would be useful to even recreating this failure. I'm just hoping that perhaps a person more experienced with ZFS will be able to spot something that would allow for pinpointing the root cause better than "well, a ZFS bug".

**Comment by kernelOfTruth** [comment]
@yacoob please provide more details on the hardware

beside mcelog there's also edac-utils (when running ECC RAM)

sample output e.g. from my box:

```
edac-util -v -r
mc0: 0 Uncorrected Errors with no DIMM info
mc0: 0 Corrected Errors with no DIMM info
mc0: csrow0: 0 Uncorrected Errors
mc0: csrow0: mc#0csrow#0channel#0: 0 Corrected Errors
mc0: csrow0: mc#0csrow#0channel#1: 0 Corrected Errors
mc0: csrow1: 0 Uncorrected Errors
mc0: csrow1: mc#0csrow#1channel#0: 0 Corrected Errors
mc0: csrow1: mc#0csrow#1channel#1: 0 Corrected Errors
mc0: csrow2: 0 Uncorrected Errors
mc0: csrow2: mc#0csrow#2channel#0: 0 Corrected Errors
mc0: csrow2: mc#0csrow#2channel#1: 0 Corrected Errors
mc0: csrow3: 0 Uncorrected Errors
mc0: csrow3: mc#0csrow#3channel#0: 0 Corrected Errors
mc0: csrow3: mc#0csrow#3channel#1: 0 Corrected Errors
edac-util: No errors to report.
```

**Comment by yacoob** [comment]
Take a look at the attachments. On the software side:

```
Linux boxoob 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64 GNU/Linux
```
```
ii  debian-zfs                           7~wheezy                         amd64        Native ZFS filesystem metapackage for Debian.
ii  libzfs2                              0.6.5.2-2                        amd64        Native ZFS filesystem library for Linux
ii  libzpool2                            0.6.5.2-2                        amd64        Native ZFS pool library for Linux
ii  zfs-dkms                             0.6.5.2-2                        all          Native ZFS filesystem kernel modules for Linux
ii  zfs-initramfs                        0.6.5.2-2                        amd64        Native ZFS root filesystem capabilities for Linux
ii  zfsonlinux                           6                                all          archive.zfsonlinux.org trust package
ii  zfsutils                             0.6.5.2-2                        amd64        command-line tools to manage ZFS filesystems
```
I couldn't get `edac-utils` to work, but mcelog stays clear since I've installed it yesterday.


[cpuinfo.txt](https://github.com/zfsonlinux/zfs/files/45154/cpuinfo.txt)
[dmidecode.txt](https://github.com/zfsonlinux/zfs/files/45153/dmidecode.txt)
[smartctl.txt](https://github.com/zfsonlinux/zfs/files/45155/smartctl.txt)

**Comment by yacoob** [comment]
So... any insight what might have gone wrong here?
