### ISSUE TITLE
ZFS breaks on filesystem mount

### ISSUE THREAD

**Issue by joruffin** [zfsonlinux/zfs#4052]
Summary:
ZFS dies while trying to mount a particular filesystem with the following errors:
[zfs-panic.txt](https://github.com/zfsonlinux/zfs/files/46144/zfs-panic.txt)
Ubuntu 14.04.3 x64

Background:
I was moving large amounts of data into new child filesystems. Odd behaviour during file moves was noticed, wherein the deleted files would not release their space for a time proportional to the size of the data. Not releasing the space means that it was not allocated in used space or snapshot space and the  total space in use according to zpool list did not decrease (or rather stay the same as they were moving.) This always eventually corrected itself by moving the space into a (much) later snapshot. I was done moving files for the night and a kernel upgrade was pending, so I restarted the server. On next boot ZFS started to die in this way.

Things that work:
Anything other than mounting this particular filesystem in read/write. The FS mounts fine if I import with readonly on.

Things I've tried:
I've run 'zdb -bcsvL' against the pool with zfs_recover=1, no change.
Tried mounting in OmniOS and SmartOS, can't mount there either but I'm not nearly as good at solaris systems so I'm reporting against linux.

I'll be happy to try things or get more info for you.
Thanks for your time.

**Comment by tuxoko** [comment]
same as https://github.com/zfsonlinux/zfs/issues/4006

**Comment by tuxoko** [comment]
@joruffin 
Can you try to boot with ```slub_debug``` and try rw mount?

**Comment by neingeist** [comment]
I have the same issue and will help to debug in the new year.

**Comment by fikridal** [comment]
I've the same problem; A volume does not mount/unmount after hard reboot. 

http://pastebin.com/gq87hFGx
http://pastebin.com/6tSuEVvZ

Thanks.

**Comment by behlendorf** [comment]
@fikridal @neingeist can you apply the patches in #4123, they are safe and should resolve the problem.  Definitely let us know if that doesn't fix things.

**Comment by neingeist** [comment]
I will after January 4th, as I'm out of town currently.

On December 23, 2015 8:30:58 PM GMT+01:00, Brian Behlendorf <notifications@github.com> wrote:
>@fikridal @neingeist can you apply the patches in #4123, they are safe
>and should resolve the problem.  Definitely let us know if that doesn't
>fix things.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/zfsonlinux/zfs/issues/4052#issuecomment-166976182

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by fikridal** [comment]
@behlendorf  my steps are true for patching?

cd /usr/src/zfs-0.6.5.3/module/zfs/
mv zap.c zapc_bck
wget https://raw.githubusercontent.com/zfsonlinux/zfs/16f7d95ffc686c769d8b030b918b0b674125855a/module/zfs/zap.c
mv zfs_dir.c zfs_dir.c_bck
wget https://raw.githubusercontent.com/tuxoko/zfs/da8264a80ad1463d0a27ab2a34cefe721fbd5e77/module/zfs/zfs_dir.c

dkms remove -m zfs -v 0.6.5.3 --all
dkms add -m zfs -v 0.6.5.3
dkms install -m zfs -v 0.6.5.3

if answer is yes, They didn't work. it still same 
http://pastebin.com/6tSuEVvZ

Thanks.

**Comment by fikridal** [comment]
Hello again,
Theese fixs are ok, my problem solved after 12 hours.. 
Thanks.. :)

**Comment by joruffin** [comment]
This patch also immediately fixed my problem.

**Comment by neingeist** [comment]
For the record: The fixes also worked for me.

**Comment by fikridal** [comment]
@behlendorf hi, new version of the zol has that patch?

**Comment by kernelOfTruth** [comment]
@fikridal https://github.com/zfsonlinux/zfs/commits/zfs-0.6.5-release
https://github.com/zfsonlinux/zfs/pull/4123

so yes :+1:

**Comment by fikridal** [comment]
thanks :)
