### ISSUE TITLE
Broken metadata

### ISSUE THREAD

**Issue by D4rk4** [zfsonlinux/zfs#4057]
root@damned:/export/pub/mirror/ftp.debian.org/debian-ports/pool-m68k/main/o/openais-legacy# ls -lsah
ls: cannot access libopenais-legacy-dev_0.80.5+sv: No such file or directory
ls: cannot access openais-legacy_0.80.5+sv: No such file or directory
ls: cannot access libopenais-legacy-2_0.80.5+sv: No such file or directory
total 108K
97K drwxr-xr-x   2 dark dark   5 Dec  1 11:17 .
12K drwxr-xr-x 348 dark dark 348 Jun 16 21:03 ..
  ? -?????????   ? ?    ?      ?            ? libopenais-legacy-2_0.80.5+sv
  ? -?????????   ? ?    ?      ?            ? libopenais-legacy-dev_0.80.5+sv
  ? -?????????   ? ?    ?      ?            ? openais-legacy_0.80.5+sv
root@damned:/export/pub/mirror/ftp.debian.org/debian-ports/pool-m68k/main/o/openais-legacy# rm libopenais-legacy-2_0.80.5+sv
rm: cannot remove 'libopenais-legacy-2_0.80.5+sv': No such file or directory
root@damned:/export/pub/mirror/ftp.debian.org/debian-ports/pool-m68k/main/o/openais-legacy# zpool status -v
  pool: export
 state: ONLINE
  scan: scrub repaired 0 in 52h20m with 0 errors on Sat Nov 28 06:16:44 2015
config:

```
    NAME                                           STATE     READ WRITE CKSUM
    export                                         ONLINE       0     0     0
      raidz1-0                                     ONLINE       0     0     0
        sdb                                        ONLINE       0     0     0
        sdc                                        ONLINE       0     0     0
        sdd                                        ONLINE       0     0     0
        sde                                        ONLINE       0     0     0
        sdf                                        ONLINE       0     0     0
      raidz1-2                                     ONLINE       0     0     0
        sdh                                        ONLINE       0     0     0
        sdj                                        ONLINE       0     0     0
        sdk                                        ONLINE       0     0     0
        sdg                                        ONLINE       0     0     0
        sdi                                        ONLINE       0     0     0
    cache
      ata-INTEL_SSDSA2M160G2GC_CVPO006300BR160AGN  ONLINE       0     0     0
```

errors: No known data errors
root@damned:/export/pub/mirror/ftp.debian.org/debian-ports/pool-m68k/main/o/openais-legacy# cd
root@damned:~# dpkg -l | grep ii | awk '{print $2" "$3}' | grep -Ei '(zfs|spl)'
debian-zfs 7~jessie
libzfs2 0.6.5.2-2
sgmlspl 1.03ii-33
spl 0.6.5-1
spl-dkms 0.6.5-1
zfs-dkms 0.6.5.2-2
zfs-initramfs 0.6.5.2-2
zfsonlinux 6
zfsutils 0.6.5.2-2

**Comment by AndCycle** [comment]
there is always this question first,

do you use ECC memory?

as I followed similar discussion on mailing list few days ago,
the conclusion is ZFS blindly trust anything with correct checksum,

which means those metadata is messed up before they been written to disk,
so scrub won't help in this case,

if you are not using ECC, it can be faulty hardware, 

if you use ECC,
there could be nasty issue in ZFS itself and probably no way to help on this,
unless you have the procedure to recreate this bug then someone can fix it.

**Comment by D4rk4** [comment]
Yes it's Dual Xeon E5440 home server with FB-DIMM ECC Memory. Can I continue to safely use this pool?

**Comment by AndCycle** [comment]
here is the thread,
http://list.zfsonlinux.org/pipermail/zfs-discuss/2015-November/023949.html

there is no conclusion, so I guess you have make the decision by yourself.

**Comment by voidzero** [comment]
Scary. Is this only on 0.6.5? Maybe I should keep running 0.6.4 for now. My pool looks almost the same although not raidz1, and my pool is smaller. Corruption is a big no no though :) Thanks @AndCycle :+1:

**Comment by nedbass** [comment]
@D4rk4 bug #3195, which affected ZFS on Linux releases prior to 0.6.4, could corrupt directories in that way. Is it possible that the directory was modified while the pool was imported under 0.6.3 or earlier? I believe it was most likely to affect affect datasets with `xattr=sa` set.

**Comment by D4rk4** [comment]
I don't use xattr=sa on this pool... And i don't import pool on other kernel/zfs/spl version.

**Comment by nedbass** [comment]
> I don't use xattr=sa on this pool... And i don't import pool on other kernel/zfs/spl version.

@D4rk4 just to be perfectly clear, does that statement apply to the entire history of your pool?

**Comment by voidzero** [comment]
Is there any follow up on this bug? I'm still reluctant to update zfs because of it.

**Comment by D4rk4** [comment]
It's still actual, but pool still work without any NEW metadata corruptions.
