### ISSUE TITLE
"zpool remove" on a log device being silently ignored

### ISSUE THREAD

**Issue by durval-menezes** [zfsonlinux/zfs#4067]
Hello,

This seems to have happened (however irreproducibly) to at least one other person here: https://github.com/zfsonlinux/zfs/issues/2099#issuecomment-162313742

For full details, please see the zfs-discuss mailing list thread starting with this message: http://list.zfsonlinux.org/pipermail/zfs-discuss/2015-December/024006.html

As it seems to be hard to reproduce, I'm keeping my pool in this semi-broken state with the hope that it can be used to debug and solve the problem. Please let me know if I can be of help.

Cheers, 
Durval.

**Comment by behlendorf** [comment]
Closing as stale.
