### ISSUE TITLE
Snapshot not being removed properly

### ISSUE THREAD

**Issue by wipash** [zfsonlinux/zfs#4068]
As of this weekend, my syslog is being spammed with messages such as the following:

```
Dec  7 11:23:12 whg-sto-102 kernel: WARNING: Unable to automount /wlg_live_2/wlg_hfs/.zfs/snapshot/hourly-2015-11-30-2201/wlg_live_2/wlg_hfs@hourly-2015-11-30-2201: 256
Dec  7 11:23:13 whg-sto-102 kernel: WARNING: Unable to automount /wlg_live_2/wlg_hfs/.zfs/snapshot/hourly-2015-12-01-0201/wlg_live_2/wlg_hfs@hourly-2015-12-01-0201: 256
Dec  7 11:23:14 whg-sto-102 kernel: WARNING: Unable to automount /wlg_live_2/wlg_hfs/.zfs/snapshot/hourly-2015-12-01-0401/wlg_live_2/wlg_hfs@hourly-2015-12-01-0401: 256
Dec  7 11:23:15 whg-sto-102 kernel: WARNING: Unable to automount /wlg_live_2/wlg_hfs/.zfs/snapshot/hourly-2015-12-01-0301/wlg_live_2/wlg_hfs@hourly-2015-12-01-0301: 256
Dec  7 11:23:16 whg-sto-102 kernel: WARNING: Unable to automount /wlg_live_2/wlg_hfs/.zfs/snapshot/hourly-2015-12-01-1001/wlg_live_2/wlg_hfs@hourly-2015-12-01-1001: 256
Dec  7 11:23:18 whg-sto-102 kernel: WARNING: Unable to automount /wlg_live_2/wlg_hfs/.zfs/snapshot/hourly-2015-11-29-0801/wlg_live_2/wlg_hfs@hourly-2015-11-29-0801: 256
Dec  7 11:23:19 whg-sto-102 kernel: WARNING: Unable to automount /wlg_live_2/wlg_hfs/.zfs/snapshot/hourly-2015-11-30-1401/wlg_live_2/wlg_hfs@hourly-2015-11-30-1401: 256
Dec  7 11:23:20 whg-sto-102 kernel: WARNING: Unable to automount /wlg_live_2/wlg_hfs/.zfs/snapshot/hourly-2015-12-01-0501/wlg_live_2/wlg_hfs@hourly-2015-12-01-0501: 256
Dec  7 11:23:21 whg-sto-102 kernel: WARNING: Unable to automount /wlg_live_2/wlg_hfs/.zfs/snapshot/hourly-2015-11-30-2201/wlg_live_2/wlg_hfs@hourly-2015-11-30-2201: 256
Dec  7 11:23:22 whg-sto-102 kernel: WARNING: Unable to automount /wlg_live_2/wlg_hfs/.zfs/snapshot/hourly-2015-12-01-0201/wlg_live_2/wlg_hfs@hourly-2015-12-01-0201: 256
Dec  7 11:23:23 whg-sto-102 kernel: WARNING: Unable to automount /wlg_live_2/wlg_hfs/.zfs/snapshot/hourly-2015-12-01-0401/wlg_live_2/wlg_hfs@hourly-2015-12-01-0401: 256
Dec  7 11:23:24 whg-sto-102 kernel: WARNING: Unable to automount /wlg_live_2/wlg_hfs/.zfs/snapshot/hourly-2015-12-01-0301/wlg_live_2/wlg_hfs@hourly-2015-12-01-0301: 256
Dec  7 11:23:25 whg-sto-102 kernel: WARNING: Unable to automount /wlg_live_2/wlg_hfs/.zfs/snapshot/hourly-2015-12-01-1001/wlg_live_2/wlg_hfs@hourly-2015-12-01-1001: 256111
```

The snapshots don't exist:
```
[root@whg-sto-102 snapshot]# zfs list -t snapshot -r wlg_live_2/wlg_hfs | grep hourly-2015-12-01-0201
[root@whg-sto-102 snapshot]# zfs list -t snapshot -r wlg_live_2/wlg_hfs | grep hourly-2015-12-01-0301
```

The snapshot folders don't show up with `ls`:
```
[root@whg-sto-102 snapshot]# ls /wlg_live_2/wlg_hfs/.zfs/snapshot | grep hourly-2015-12-01-0201
[root@whg-sto-102 snapshot]# ls /wlg_live_2/wlg_hfs/.zfs/snapshot | grep hourly-2015-12-01-0301
```

But stat shows them:
```
[root@whg-sto-102 snapshot]# stat /wlg_live_2/wlg_hfs/.zfs/snapshot/hourly-2015-12-01-0201
  File: ‘/wlg_live_2/wlg_hfs/.zfs/snapshot/hourly-2015-12-01-0201’
  Size: 0               Blocks: 0          IO Block: 512    directory
Device: 25h/37d Inode: 281474976673040  Links: 1
Access: (0555/dr-xr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2015-12-07 10:45:19.945231287 +1300
Modify: 2015-12-02 09:22:39.599681380 +1300
Change: 2015-12-02 09:22:39.599681380 +1300
 Birth: -
[root@whg-sto-102 snapshot]# stat /wlg_live_2/wlg_hfs/.zfs/snapshot/hourly-2015-12-01-0301
  File: ‘/wlg_live_2/wlg_hfs/.zfs/snapshot/hourly-2015-12-01-0301’
  Size: 0               Blocks: 0          IO Block: 512    directory
Device: 25h/37d Inode: 281474976672676  Links: 1
Access: (0555/dr-xr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2015-12-02 09:22:39.710677884 +1300
Modify: 2015-12-02 09:22:39.710677884 +1300
Change: 2015-12-02 09:22:39.710677884 +1300
 Birth: -
```

`lsof` doesn't show any processes using these folders.

I'm unable to remove these folders manually, and the problem doesn't go away after a reboot.
I've also tried recreating these snapshots, which populates the snapshot folder and stops the automount failure message, but when I remove the snapshots the problem returns.

Snapshots are being created and removed hourly with zfs-auto-snapshot (https://github.com/zfsonlinux/zfs-auto-snapshot) with the following arguments:
```
exec /usr/local/sbin/zfs-auto-snapshot --quiet --syslog --label=hourly --keep=120 --prefix="" wlg_live_2/wlg_hfs
```

Not all snapshots that have been autoremoved are showing this issue. I've tried manually creating and destroying a few snapshots on this filesystem this morning, but haven't been able to recreate the issue yet.

#### System version info:
```
# cat /etc/centos-release
CentOS Linux release 7.1.1503 (Core)

# modinfo zfs
filename:       /lib/modules/3.10.0-229.20.1.el7.x86_64/weak-updates/zfs.ko
version:        0.6.5-32_g256fa98

# modinfo spl
filename:       /lib/modules/3.10.0-229.20.1.el7.x86_64/weak-updates/spl.ko
version:        0.6.5-11_ge7b75d9

# uname -sr
Linux 3.10.0-229.20.1.el7.x86_64
```

**Comment by behlendorf** [comment]
@wipash there were two automount snapshot fixes applied to master since you last updated.  Could you either cherry-pick these patches up update to the latest master source.

d287880 Fix snapshot automount behavior when concurrent or fail
24ef51f Use spa as key besides objsetid for snapentry

**Comment by behlendorf** [comment]
@wipash can you verify the the latest 0.6.5.x releases resolved this problem.  The snapshot fixes mentioned above were included and should have addressed this.

**Comment by wipash** [comment]
Will update several of our boxes tonight and let you know

**Comment by wipash** [comment]
Issue hasn't reappeared after update.

**Comment by behlendorf** [comment]
@wipash thanks for the update and confirmation this has been fixed.  Closing.

**Comment by teramundisupport** [comment]
Hi,

We are facing this very same issue on recently freshly installed CentOS 7 with zfs-kmod:

[root@backup01 ~]# cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core)

[root@backup01 ~]# uname -sr
Linux 3.10.0-957.12.2.el7.x86_64

[root@backup01 ~]# modinfo zfs | grep version:
version:        0.7.13-1
rhelversion:    7.6
srcversion:     CD1489EAB5842683DC3584F

[root@backup01 ~]# modinfo spl | grep version:
version:        0.7.13-1
rhelversion:    7.6
srcversion:     D3DA80EEA70C9ED650FA39A

[root@backup01 ~]# rpm -qa | grep zfs
zfs-release-1-6.el7.noarch
libzfs2-0.7.13-1.el7_6.x86_64
kmod-zfs-0.7.13-1.el7_6.x86_64
zfs-0.7.13-1.el7_6.x86_64



In our logs, we can see "zfs destroy" executed successfully:

[Jun 12 16:02:02] [PID 178739] Removing exceeding daily snapshot.
[Jun 12 16:02:02] [PID 178739] Running: /usr/sbin/zfs destroy backups02/sever481@daily_2019-06-05_1425
[Jun 12 16:02:10] [PID 178739] Return Code: 0.



After that, dmesg shows the warning:

[673470.723451] WARNING: Unable to automount /backups02/sever481/.zfs/snapshot/daily_2019-06-05_1425/backups02/sever481@daily_2019-06-05_1425: 256
[673470.727498] WARNING: Unable to automount /backups02/sever481/.zfs/snapshot/daily_2019-06-05_1425/backups02/sever481@daily_2019-06-05_1425: 256



If we look at the list of snapshots, it's not there anymore:

[root@backup01 ~]# zfs list -r -t all backups02/sever481 | grep 2019-06-05_1425
[root@backup01 ~]# zfs list backups02/sever481@daily_2019-06-05_1425
cannot open 'backups02/sever481@daily_2019-06-05_1425': dataset does not exist



If we look at the directories inside .zfs/snapshot it also seems to be gone:

[root@backup01 ~]# ls -la /backups02/sever481/.zfs/snapshot/ | grep 2019-06-05_1425
[root@backup01 ~]#



However, we can see it with stat:

[root@backup01 ~]# stat /backups02/sever481/.zfs/snapshot/daily_2019-06-05_1425
  File: /backups02/sever481/.zfs/snapshot/daily_2019-06-05_1425
  Size: 0         	Blocks: 0          IO Block: 512    directory
Device: 30009bh/3145883d	Inode: 281474976710183  Links: 1
Access: (0777/drwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-06-12 16:40:15.815808416 -0300
Modify: 2019-06-12 07:29:19.679656113 -0300
Change: 2019-06-12 07:29:19.679656113 -0300
 Birth: -




And "ls" shows errors but also manages to list the directory:

[root@backup01 ~]# ls -la /backups02/sever481/.zfs/snapshot/daily_2019-06-05_1425
ls: cannot access /backups02/sever481/.zfs/snapshot/daily_2019-06-05_1425/.: Object is remote
ls: cannot access /backups02/sever481/.zfs/snapshot/daily_2019-06-05_1425/..: Object is remote
total 0
d????????? ? ? ? ?            ? .
d????????? ? ? ? ?            ? ..



rmdir allows us to delete the empty directory:

[root@backup01 ~]# rmdir /backups02/sever481/.zfs/snapshot/daily_2019-06-05_1425
[root@backup01 ~]#


After which we can not longer see it:

[root@backup01 ~]# stat /backups02/sever481/.zfs/snapshot/daily_2019-06-05_1425
stat: cannot stat /backups02/sever481/.zfs/snapshot/daily_2019-06-05_1425: No such file or directory
[root@backup01 ~]# ls -la /backups02/sever481/.zfs/snapshot/daily_2019-06-05_1425
ls: cannot access /backups02/sever481/.zfs/snapshot/daily_2019-06-05_1425: No such file or directory



Apparently, after that the warnings stop -- we are continuing to observe to see if they show up again, but so far it didn't happen again after "rmdir".

We didn't try to reboot the server to see what happens and also didn't run a "zfs scrub" -- would that help?

**Comment by arstercz** [comment]
`kernel: WARNING: Unable to automount` also occurs in `0.7.13` version after I destroy a snapshot:
```
os: Centos7 
kernel： 3.10.0-862.14.4.el7.x86_64
zfs-0.7.13-1.el7_6.x86_64
zfs-dkms-0.7.13-1.el7_6.noarch
libzfs2-0.7.13-1.el7_6.x86_64
zfs-release-1-6.el7.noarch
```
It seems that `mount.zfs` want mount the snapshot
```
Mar 07 09:23:57 cz snoopy[26557]: [uid:0 sid:0 tty:ERROR(ttyname_r->EBADF) cwd:/ filename:/sbin/mount.zfs]: /sbin/mount.zfs datapool/db@db_20191025 /data/
Mar 07 09:23:57 cz kernel: WARNING: Unable to automount /data/db/.zfs/snapshot/db_20191025/datapool/db@db_20191025: 256
Mar 07 09:23:58 cz snoopy[26561]: [uid:0 sid:0 tty:ERROR(ttyname_r->EBADF) cwd:/ filename:/sbin/mount.zfs]: /sbin/mount.zfs datapool/db@db_20191025 /data/
Mar 07 09:23:58 cz kernel: WARNING: Unable to automount /data/db/.zfs/snapshot/db_20191025/datapool/db@db_20191025: 256
```
