### ISSUE TITLE
Replace Error

### ISSUE THREAD

**Issue by OverLocker** [zfsonlinux/zfs#4070]
Hello,
I have two disks in pool (old - online and new - offline) after attempt to replace. What should i do?

pool status
  pool: ZFS01
 state: DEGRADED
  scan: resilvered 136K in 0h0m with 0 errors on Mon Dec  7 06:23:52 2015
config:
 
        NAME                                            STATE     READ WRITE CKSUM
        ZFS01                                           DEGRADED     0     0     0
          raidz2-0                                      DEGRADED     0     0     0
            ata-WDC_WD30EFRX-68AX9N0_WD-WCC1T1103105    ONLINE       0     0     0
            ata-WDC_WD30EFRX-68AX9N0_WD-WCC1T1172243    ONLINE       0     0     0
            ata-WDC_WD30EZRX-00SPEB0_WD-WCC4E0315648    ONLINE       0     0     0
            ata-WDC_WD30EZRX-00DC0B0_WD-WMC1T2084454    ONLINE       0     0     0
            ata-WDC_WD30EZRX-00D8PB0_WD-WCC4N0103047    ONLINE       0     0     0
            ata-WDC_WD30EZRX-00DC0B0_WD-WMC1T0438502    ONLINE       0     0     0
            replacing-6                                 DEGRADED     0     0     0
              ata-WDC_WD30EZRX-00MMMB0_WD-WCAWZ0412403  ONLINE       0     0     0
              127286639182292558                        UNAVAIL      0     0     0  was /dev/disk/by-id/ata-WDC_WD30EZRX-00DC0B0_WD-WMC1T0419233-part1
            ata-WDC_WD30EZRX-00MMMB0_WD-WMAWZ0327093    ONLINE       0     0     0
            ata-WDC_WD30EFRX-68EUZN0_WD-WCC4N0962266    ONLINE       0     0     0
 
errors: No known data errors

But:
zpool status -x
all pools are healthy

**Comment by dasjoe** [comment]
You can safely detach the UNAVAIL disk: `zpool detach ZFS01 127286639182292558`
