### ISSUE TITLE
when i use samba with zfs in debian 64 the kernel panic

### ISSUE THREAD

**Issue by lihui2090** [zfsonlinux/zfs#4073]
I have a server is debian-7.9 64.
cpu is 
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
kernel is Linux 2.6.39.001 #1 SMP PREEMPT Sun Dec 6 02:31:31 EST 2015 x86_64 GNU/Linux
I  can login the share dir , but 
when i create a  file or dir in samba share  dir the kernle panic . 
root@winsuntech:~# zdb 
winsun:
    version: 5000
    name: 'test'
    state: 0
    txg: 1592
    pool_guid: 1936287794203984767
    errata: 0
    hostname: 'hhhh'
    vdev_children: 1
    vdev_tree:
        type: 'root'
        id: 0
        guid: 1936287794203984767
        create_txg: 4
        children[0]:
            type: 'mirror'
            id: 0
            guid: 3421012742799825909
            metaslab_array: 34
            metaslab_shift: 35
            ashift: 12
            asize: 4000771997696
            is_log: 0
            create_txg: 4
            children[0]:
                type: 'disk'
                id: 0
                guid: 18192064795699640212
                path: '/dev/sda1'
                whole_disk: 1
                create_txg: 4
            children[1]:
                type: 'disk'
                id: 1
                guid: 9930839888330376040
                path: '/dev/sdb1'
                whole_disk: 1
                create_txg: 4
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data

root@winsuntech:~# zpool status
  pool: test
 state: ONLINE
  scan: none requested
config:

```
    NAME        STATE     READ WRITE CKSUM
    winsun      ONLINE       0     0     0
      mirror-0  ONLINE       0     0     0
        sda     ONLINE       0     0     0
        sdb     ONLINE       0     0     0
```

errors: No known data errors

**Comment by behlendorf** [comment]
Please post in the panic you can find it in the output of the `dmesg` command.  Or if that's impossible a photo of the backtrace on the console would work.  Without that we have nothing to go on.

**Comment by lihui2090** [comment]
in dmesg no find log about the  panic niformation, in the console has the informations,
BUG: scheduling while atomic: smbd/4305/0x00000002
Modules linked in: zfs(P) zunicode(P) zavl(P) zcommon(P) znvpair(P) spl spidev ce5xx_spi_slv
Pid: 4305, comm: smbd Tainted: P            2.6.39.001 #1
Call Trace:
 [<ffffffff815e2e6f>] ? schedule+0x6af/0x8b0
 [<ffffffffa035a555>] ? zpl_read_common+0x85/0xd0 [zfs]
 [<ffffffff81046524>] ? lock_timer_base.isra.30+0x34/0x70
 [<ffffffff81046a62>] ? try_to_del_timer_sync+0x62/0x90
 [<ffffffff815e3582>] ? schedule_timeout+0x132/0x1e0
 [<ffffffff81046200>] ? usleep_range+0x40/0x40
 [<ffffffffa00117f5>] ? task_alloc+0x65/0x140 [spl]
 [<ffffffffa035bca0>] ? zpl_prune_sb+0x30/0x30 [zfs]
 [<ffffffffa0011bd4>] ? taskq_dispatch_delay+0x84/0x110 [spl]
 [<ffffffffa035d5eb>] ? zpl_check_acl+0x9b/0xb0 [zfs]
 [<ffffffff810d5e0e>] ? acl_permission_check+0x8e/0xb0
 [<ffffffff810d7f53>] ? link_path_walk+0x313/0x900
 [<ffffffff810d7a97>] ? do_lookup+0x137/0x2e0
 [<ffffffff810d7473>] ? path_init+0x193/0x3e0
 [<ffffffff810e1b90>] ? dput+0x20/0x190
 [<ffffffff810d86a2>] ? path_lookupat+0x52/0x840
 [<ffffffff810da01c>] ? do_path_lookup+0x2c/0xa0
 [<ffffffff810da49e>] ? user_path_at+0x5e/0xc0
 [<ffffffff810d0305>] ? cp_new_stat+0xf5/0x110
 [<ffffffff810d018b>] ? vfs_fstatat+0x3b/0x80
 [<ffffffff810d0573>] ? sys_newstat+0x13/0x30
 [<ffffffff815e5bbb>] ? system_call_fastpath+0x16/0x1b

**Comment by lihui2090** [comment]
may be is   
    zfs set sharesmb=on test  
    zfs set  aclinherit=restricted  test 
    the  test permison is  
    drwxr-xr-x 2 root root 4096 Dec  9 06:29 test
    
   in samba  when i create the dir ,i no authority ,then cheduling while atomic: smbd/4305/0x00000002

   and the device  has  a watchdog  , so  the kernel  reboot and no log

**Comment by behlendorf** [comment]
Closing.  This is believed to be fixed in the current release.
