### ISSUE TITLE
Can't use the whole disk 

### ISSUE THREAD

**Issue by LeeRock** [zfsonlinux/zfs#4074]
According to the official document,create the pool with the whole disk is good in performance.I try to use:
zpool create mypool  /dev/sdl
but zfs is hang on the command  ,i can use the CTRL+C to stop it.My system is redhat 7.0.Kernel is 3.10.0-123.e17.x86_64.
I use the libuuid 1.0.3 and zlib 1.2.8.

**Comment by LeeRock** [comment]
My zfs spl is 0.6.5.3.But I can't use the whole disk since 0.6.4

**Comment by LeeRock** [comment]
It's my first to communicate in the opensource community.Is anything I did wrong that no one want to help me solve the problem?

**Comment by AndCycle** [comment]
if nobody hit this except you, you have to dig the problem about why by your own,

you need more general support, 
try mailing list, http://zfsonlinux.org/lists.html
