### ISSUE TITLE
arc_summary.py isn't python3 compatible

### ISSUE THREAD

**Issue by dlan17** [zfsonlinux/zfs#4084]
~ # python --version
Python 3.4.3

~ # head -1 $(which  arc_summary.py)
#!/usr/bin/python

~ # arc_summary.py 
  File "/bin/arc_summary.py", line 1135
    except IndexError , e:
                      ^
SyntaxError: invalid syntax

**Comment by behlendorf** [comment]
Thanks for pointing this out.  This would be a great issue for someone familiar familiar with the latest python to tackle.

**Comment by behlendorf** [comment]
Fixed with:

7cf2ffa Make arc_summary.py and dbufstat.py compatible with python3
