### ISSUE TITLE
Security issue: /dev/zfs has mode 0666 when 60-fprint-autosuspend.rules is installed

### ISSUE THREAD

**Issue by ilovezfs** [zfsonlinux/zfs#4100]
The udev rule 60-fprint-autosuspend.rules causes /dev/zfs, among other devices, to have the mode 0666 instead of whatever mode they would otherwise have, which in /dev/zfs's case is 0600:
https://gist.github.com/ilovezfs/2854a6d59ee6b2ae7e6b#file-dev-with-and-without-fprint-txt

This causes security issues such as the ability for unprivileged users to create zfs datasets. 

Is there some change that can be made to ZoL to prevent it from getting ensnared by this bug, rather than waiting for a libfprint upstream fix?

https://gist.github.com/ilovezfs/f232703e70b610aa6ae7#file-60-fprint-autosuspend-rules
http://cgit.freedesktop.org/libfprint/libfprint/tree/libfprint
http://cgit.freedesktop.org/libfprint/libfprint/tree/libfprint/fprint-list-udev-rules.c

**Comment by dasjoe** [comment]
Your distribution seems to modify `fprint-list-udev-rules.c` to include `, MODE="0666"`, which should get appended to the first line instead of getting printed on its own.

**Comment by ilovezfs** [comment]
@dasjoe Yup, making that change resolves the problem. So the question is whether it's upstream Gentoo or just Sabayon and which version(s) are affected.

The file specifically came from

```
openzfs ~ # e-file /lib/udev/rules.d/60-fprint-autosuspend.rules 
[I] sys-auth/libfprint
	Available Versions:	0.6.0-r1 0.6.0 0.5.0-r1 0.5.1-r1 
	Last Installed Ver:	0.6.0-r1(Sun 27 Sep 2015 07:20:30 PM JST)
	Homepage:		http://cgit.freedesktop.org/libfprint/libfprint/
	Description:		library to add support for consumer fingerprint readers
	Matched Files:		/lib/udev/rules.d/60-fprint-autosuspend.rules; 
```

**Comment by dasjoe** [comment]
Upstream bug: https://bugs.gentoo.org/show_bug.cgi?id=562218

-- 
Regards,
Hajo Möller

**Comment by behlendorf** [comment]
This is really something they'll need to handle upstream, there's only so much we can do if they're changing the permissions on the device.

**Comment by ryao** [comment]
@behlendorf We can enforce UMASK on /dev/zfs in the kernel module itself through a credentials check. The UMASK could be set via a module parameter that defaults to restricting /dev/zfs access to root and can only be set at boot. I intend to implement this idea soon.

**Comment by behlendorf** [comment]
@ryao we could, although keep in mind many people currently rely on explicitly re-permissioning the /dev/zfs device as a partial substitute for delegations.  For example, they'll make sure a certain group has access to it and put certain trusted users in that group.

**Comment by ryao** [comment]
@behlendorf That is why it would be customizable as a module parameter.

**Comment by behlendorf** [comment]
@ryao as long as the default behavior doesn't change.  If this is implemented it's a workaround for a distribution specific issue and should be set solely for that distribution.
