### ISSUE TITLE
Mount option mode

### ISSUE THREAD

**Issue by CMCDragonkai** [zfsonlinux/zfs#4101]
When creating a dataset for /tmp in ZFS, I expected that there would be a `mode` option to set like `mode=1777`. Currently ZFS doesn't have this option under `zfs mount`, but neither does normal mount command:

```
# this doesn't work
mount -t zfs -o mode=1777 rpool/tmp /mnt/tmp
```

Any reasons why there's no mode option for ZFS?

**Comment by dasjoe** [comment]
A dataset's permissions are preserved, you can set them manually once and they'll be restored at the next mount:
```
# zfs create sbooblehat-rpool/test
# ls -al /
[…]
drwxr-xr-x   2 root root        2 Dec 14 14:35 test
[…]
# chmod 1777 /test
# ls -al /
[…]
drwxrwxrwt   2 root root        2 Dec 14 14:35 test
[…]
# zfs umount /test
# rm -r /test
# zfs mount sbooblehat-rpool/test 
# ls -al /
[…]
drwxrwxrwt   2 root root        2 Dec 14 14:35 test
[…]
```

**Comment by CMCDragonkai** [comment]
Oh that's handy.

**Comment by behlendorf** [comment]
@CMCDragonkai they're stored in the root inode for the dataset.
