### ISSUE TITLE
./configure fail on Zorin 10 kernel 3.19

### ISSUE THREAD

**Issue by v12venator** [zfsonlinux/zfs#4103]
Configure: error:
    uuid/uuid.h missing, libuuid-devel package required
see config.log for more details.

**Comment by v12venator** [comment]
Unable to find libuuid-devel in repositories. Any direction?

**Comment by tuxoko** [comment]
uuid-dev

**Comment by behlendorf** [comment]
@v12venator it depends entirely on your distribution, but `uuid-dev` and `libuuid-devel` are common names for the package.

**Comment by v12venator** [comment]
@behlendorf I manually updated the uuid-dev package. Now I run into the error of making deb-utils and deb-kmod on both the spl and zfs when building .debs.

Makefile1172: recipe for target 'deb-local' failed
make *** [deb-local] Error 1

Any ideas what that might entail?

**Comment by v12venator** [comment]
@tuxoko @behlendorf 
I apologize for wasting your time. I gave up on building my own and installed the package from the launchpad website. I figured I would be able to build a generic .deb on my own, being a newbie-ish linux user.
