### ISSUE TITLE
Kernel panic - not syncing: avl_find() succeeded inside avl_add()

### ISSUE THREAD

**Issue by storepeter** [zfsonlinux/zfs#4122]
I get a kernel panic every day on Ubuntu 14.04.3 / ZFS 0.6.5.3.
Please advice if you need further details.
I have included a blurred photo of the screen after the crash

Best Regards
Peter

![img_0001](https://cloud.githubusercontent.com/assets/4480669/11900323/3a47d3dc-a573-11e5-998c-55b3c603e299.JPG)

excerpt from dmesg:
[    0.000000] Linux version 3.19.0-41-generic (buildd@lgw01-12) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #46~14.04
.2-Ubuntu SMP Tue Dec 8 17:46:10 UTC 2015 (Ubuntu 3.19.0-41.46~14.04.2-generic 3.19.8-ckt10)
[    0.000000] Command line: BOOT_IMAGE=/vmlinuz-3.19.0-41-generic boot=zfs rpool=y bootfs=y/ROOT/ubuntu-14.04-y
...
[    7.368128] zavl: module license 'CDDL' taints kernel.
[    7.369392] Disabling lock debugging due to kernel taint
[    7.370653] zavl: module verification failed: signature and/or  required key missing - tainting kernel
[    7.373345] SPL: Loaded module v0.6.5.3-1~trusty
[    7.383352] ZFS: Loaded module v0.6.5.3-1~trusty, ZFS pool version 5000, ZFS filesystem version 5
[    9.150664] SPL: using hostid 0x007f0101

----
zpool status
  pool: av
 state: ONLINE
status: Some supported features are not enabled on the pool. The pool can
	still be used, but some features are unavailable.
action: Enable all features using 'zpool upgrade'. Once this is done,
	the pool may no longer be accessible by software that does not support
	the features. See zpool-features(5) for details.
  scan: none requested
config:

	NAME                                       STATE     READ WRITE CKSUM
	av                                         ONLINE       0     0     0
	  mirror-0                                 ONLINE       0     0     0
	    ata-ST2000DL003-9VT166_5YDA1MXK-part5  ONLINE       0     0     0
	    ata-ST32000542AS_5XW1WX63-part5        ONLINE       0     0     0

errors: No known data errors

  pool: y
 state: ONLINE
status: Some supported features are not enabled on the pool. The pool can
	still be used, but some features are unavailable.
action: Enable all features using 'zpool upgrade'. Once this is done,
	the pool may no longer be accessible by software that does not support
	the features. See zpool-features(5) for details.
  scan: resilvered 1.13G in 0h2m with 0 errors on Sun Dec 13 12:32:14 2015
config:

	NAME                                       STATE     READ WRITE CKSUM
	y                                          ONLINE       0     0     0
	  mirror-0                                 ONLINE       0     0     0
	    ata-ST2000DL003-9VT166_5YDA1SW7-part5  ONLINE       0     0     0
	    ata-ST32000542AS_5XW1WB4G-part5        ONLINE       0     0     0

errors: No known data errors

 -----
zpool history
History for 'av':
2013-12-11.17:46:43 zpool create -o ashift=12 -f av mirror ata-ST2000DL003-9VT166_5YDA1MXK-part5 ata-ST32000542AS_5XW1WX63-part5
2013-12-11.17:46:43 zpool set feature@lz4_compress=enabled av
2013-12-11.17:46:44 zfs set compression=lz4 av
2013-12-11.17:46:45 zfs set atime=off av
2013-12-11.17:46:45 zfs set sharenfs=on av
2013-12-11.17:46:46 zfs set snapdir=visible av
....
History for 'y':
2013-12-11.10:44:21 zpool create -o ashift=12 -f y mirror ata-ST2000DL003-9VT166_5YDA1SW7-part5 ata-ST32000542AS_5XW1WB4G-part5
2013-12-11.10:44:21 zpool set feature@lz4_compress=enabled y
2013-12-11.10:44:21 zfs set compression=lz4 y
2013-12-11.10:44:22 zfs set atime=off y
2013-12-11.10:44:22 zfs set sharenfs=on y
2013-12-11.10:44:23 zfs set snapdir=visible y

**Comment by behlendorf** [comment]
@storepeter the fix for this is in the master branch and will be in the next point release.  If you need a fix now you can safely cherry pix these two patches.

d287880 Fix snapshot automount behavior when concurrent or fail
24ef51f Use spa as key besides objsetid for snapentry

**Comment by storepeter** [comment]
I installed the fixes above, and the system has now been running for more than a day, without any problems.

Thank you for your support, and for making zfsonlinux happen. I have been a happy user for more than two years, with very few problems.

**Comment by behlendorf** [comment]
@storepeter glad to hear that resolved the issue.  Sorry we let this one slip through we'll get it in the next release.
