### ISSUE TITLE
zfs and sharesmb -- are my shares being created twice?

### ISSUE THREAD

**Issue by sofakng** [zfsonlinux/zfs#4125]
I'm using ProxMox v4.1 which is Debian 8 64-bit running ZoL v0.6.5 and Samba v4.1.17.

When I try to use ZFS to enable an smb share (i.e. zfs set sharesmb=on tank/files), it works but after a reboot I receive errors such as "cannot share tank/files: smb add share failed" and "ERROR: share tank_files already exists."

The first change to get anything working was to enable "registry shares = yes" in my /etc/samba/smb.conf.

However, I noticed that I have a service called "zfs-share.service" which executes "zfs share -a", but there is also a file "/etc/default/zfs.conf" with settings for "ZFS_SHARE = yes".

It sounds like the service and the defaults file are causing 'zfs share -a' to be executed twice during startup?

**Comment by FransUrbo** [comment]
> cannot share tank/files: smb add share failed" and "ERROR: share tank_files already exists
> 
This is a problem I never got around fixing. It was supposed to have been done once the review of the patch started, but "the powers that be" choose to ignore and not accept the patch, so I never bothered to fix that part.

It's perfectly fine, just a bit annoying.


What happens is that when ZoL tells samba to do the sharing it records this as a share. When the machine then stops, ZoL isn't telling samba to STOP sharing, so when samba comes back up again after the reboot, it still have that share enabled. And then ZoL comes along and wants to share it again… At which time samba complains and say it's already shared…

**Comment by sofakng** [comment]
Thanks very much for the information!  I spent a couple of hours looking through the ZoL code and then realized that ProxMox used a different version of ZoL that included your patch.  I agree that it's not causing any problems but I do get errors in my log from the zfs-share service.

If I did want to implement a quick fix, all I need is a script that uses "net conf delshares" on shutdown, right?

**Comment by FransUrbo** [comment]
The _correct_ way should be to make sure that <code>zfs unshare -a</code> is run before Samba is shut down. Or, if you want to make things easy for you, run <code>net conf delshares</code> just before Samba shutdown (as you say). With <code>systemd</code> scripts, I think there's some kind of "post-execute" option you can use for that.

**Comment by sofakng** [comment]
Thanks again.

It's too bad your commits won't be merged into master for a while.  Also, it's strange but if you run 'zfs share -a' you get the error that the share already exists but if you run it a second time it doesn't show any errors.  (I'm not sure if it's failing silently, or the second attempt realizes that the share was already created)

**Comment by FransUrbo** [comment]
There is SOME code bug in there as well, but _usually_ it works by running <code>zfs unshare -a</code> first. But it's not been on my TODO to figure out exactly what the problem is and how to fix it. it works...
