### ISSUE TITLE
feature flags missing from pool

### ISSUE THREAD

**Issue by kfreedman** [zfsonlinux/zfs#4126]
I have two systems whose zfs features differ.. both are the same kernel and zfs version, so this is perplexing:

[root@host1] >> modinfo zfs | grep version
version:        0.6.5.3-1
srcversion:     CEB8F91B3D53F4A2844D531
vermagic:       2.6.32-573.8.1.el6.x86_64 SMP mod_unload modversions 

[root@host2]# modinfo zfs | grep version
version:        0.6.5.3-1
srcversion:     CEB8F91B3D53F4A2844D531
vermagic:       2.6.32-573.8.1.el6.x86_64 SMP mod_unload modversions 

[root@host1] ~ >> uname -a
Linux host12.6.32-573.12.1.el6.x86_64 #1 SMP Tue Dec 15 21:19:08 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
# this one was just upgraded from 537.8.1 to 537.12.1 but same issues before and afer

[root@host2 ~]# uname -a
Linux host2.2.6.32-573.8.1.el6.x86_64 #1 SMP Tue Nov 10 18:01:38 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

root@host1] ~ >> zpool upgrade -a
This system supports ZFS pool feature flags.

All pools are already formatted using feature flags.

Every feature flags pool already has all supported features enabled.

[root@wphost2 ~]# zpool upgrade -a
This system supports ZFS pool feature flags.

All pools are already formatted using feature flags.

Every feature flags pool already has all supported features enabled.

[root@host1] ~ >> zpool get all |grep @
data  feature@async_destroy  enabled                local
data  feature@empty_bpobj    active                 local
data  feature@lz4_compress   active                 local

[root@host2 ~]# zpool get all |grep @
data  feature@async_destroy       enabled                     local
data  feature@empty_bpobj         active                      local
data  feature@lz4_compress        active                      local
data  feature@spacemap_histogram  active                      local
data  feature@enabled_txg         active                      local
data  feature@hole_birth          active                      local
data  feature@extensible_dataset  enabled                     local
data  feature@embedded_data       active                      local
data  feature@bookmarks           enabled                     local
data  feature@filesystem_limits   enabled                     local
data  feature@large_blocks        enabled                     local

root@host1] ~ >> zpool set feature@large_blocks data
missing value in property=value argument
usage:
	set <property=value> <pool>

**Comment by ilovezfs** [comment]
Is this gentoo?

**Comment by kernelOfTruth** [comment]
rhel 6 or cent os 6 I suppose

**Comment by kfreedman** [comment]
Centos 6, sorry for the late reply.  I didn't see your comments until now for some reason.
Just upgraded to 0.6.5.4  and no change:

[root] ~ >> cat /etc/redhat-release 
CentOS release 6.7 (Final)
[root] ~ >> uname -a
Linux webhost1.2.6.32-573.12.1.el6.x86_64 #1 SMP Tue Dec 15 21:19:08 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[root] ~ >> modinfo zfs | grep version
version:        0.6.5.4-1
srcversion:     5FC0B558D497732F17F4202
vermagic:       2.6.32-573.12.1.el6.x86_64 SMP mod_unload modversions

**Comment by DeHackEd** [comment]
Sounds like either your user tools may be out of sync or the loaded kernel module is out of date despite an updated installed kernel module. `rpm -q zfs libzfs2` on each system will check the user tools versions and `cat /sys/module/zfsversion` will check the loaded module version.

**Comment by kfreedman** [comment]
They're both the same
[root@host1] ~ >> cat /sys/module/zfs/version
0.6.5.4-1
[root@host1] ~ >> rpm -q zfs libzfs2
zfs-0.6.5.4-1.el6.x86_64
libzfs2-0.6.5.4-1.el6.x86_64

[root@host2 ~]# cat /sys/module/zfs/version
0.6.5.4-1
[root@host2 ~]# rpm -q zfs libzfs2
zfs-0.6.5.4-1.el6.x86_64
libzfs2-0.6.5.4-1.el6.x86_64

**Comment by kfreedman** [comment]
Any thoughts here? 
upgrading kernel didn't help:
2.6.32-573.18.1.el6.x86_64

**Comment by ilovezfs** [comment]
what are the outputs of
```
# which -a zfs
# which -a zpool
# which -a zfs | xargs -tn1 ldd
# which -a zpool | xargs -tn1
```

**Comment by kfreedman** [comment]
oh.. well now I feel dumb.   
there was an old version of zpool and zfs left over from when I switched to manual builds to repos 
 :( 

sorry for the confusion and thanks a bunch for the help.
