### ISSUE TITLE
[OpenZFS] Illumos 6434 - sa_find_sizes() may compute wrong SA header size

### ISSUE THREAD

**Issue by kernelOfTruth** [zfsonlinux/zfs#4141]
This issue might need attention and a decision (update with upstream or leaving as-is):

https://www.illumos.org/issues/6434 sa_find_sizes() may compute wrong SA header size

https://github.com/illumos/illumos-gate/commit/3502ed6e7cb3f3d2e781960ab8fe465fdc884834

(see: https://github.com/zfsonlinux/zfs/issues/1890 ; https://github.com/zfsonlinux/zfs/commit/472e7c60853af099fbdf9d52162fd39818884f4f sa_find_sizes() may compute wrong SA header size)

CC:
@behlendorf  @dweeezil @nedbass

**Comment by behlendorf** [comment]
This change is large based on a patch from ZoL and FreeBSD which we pushed upstream after a little more cleanup.  We definitely want to update ZoL to bring us back in sync with upstream.
