### ISSUE TITLE
SELinux: security_context_to_sid(off) failed for (dev zfs, type zfs) errno=-22 with one version but not others

### ISSUE THREAD

**Issue by RichardSharpe** [zfsonlinux/zfs#4151]
I am not sure if this is an issue or my problem with building.

When I first built ZFS I must have built it from master, because the versions in use are:

SPL:  v0.6.4-12_g77ab5dd
ZFS: v0.6.4-139_g1cd7773

If I upgrade to the current master or to 0.6.5-release, everything is fine, but if I build 0.6.4-release with one change and install it on my system with an existing ZPool, I get the above error.

That is:

SPL: v0.6.4.1-1
ZFS: v0.6.4.2-1_gae168d1

What have I done wrong to cause the SELinux error?

**Comment by RichardSharpe** [comment]
OK, I think this was a problem with my build environment.

After I fixed that up things work.

**Comment by tomalakgeretkal** [comment]
What problem with your build environment? Please share with the class!
