### ISSUE TITLE
PANIC at arc.c:3194:arc_shrink()

### ISSUE THREAD

**Issue by virtual81** [zfsonlinux/zfs#4161]
I am using ZFS 0.6.5.3-r1 as provided by Gentoo on kernel 4.1.15. During tests, the following ASSERTs appeared. The corresponding code in arc_shrink looks ok, so I suspect a locking problem.

[Sun Jan  3 11:45:10 2016] VERIFY((arc_stats.arcstat_c.value.ui64) >= (arc_stats.arcstat_c_min.value.ui64)) failed
[Sun Jan  3 11:45:10 2016] VERIFY((arc_stats.arcstat_c.value.ui64) >= (arc_stats.arcstat_c_min.value.ui64)) failed
[Sun Jan  3 11:45:10 2016] PANIC at arc.c:3194:arc_shrink()
[Sun Jan  3 11:45:10 2016] Showing stack for process 58926
[Sun Jan  3 11:45:10 2016] CPU: 0 PID: 58926 Comm: arc_reclaim Tainted: P        W  O    4.1.15+ #16
[Sun Jan  3 11:45:10 2016] Hardware name: Supermicro H8QG6/H8QG6, BIOS 3.00       09/04/2012
[Sun Jan  3 11:45:10 2016]  0000000000000c7a ffff8828049bfc78 ffffffff814050d4 00000000c537c537
[Sun Jan  3 11:45:10 2016]  ffffffffa127e792 ffff8828049bfc88 ffffffffa017e887 ffff8828049bfe08
[Sun Jan  3 11:45:10 2016]  ffffffffa017e930 ffff8828049bfca8 ffffffff00000028 ffff8828049bfe18
[Sun Jan  3 11:45:10 2016] Call Trace:
[Sun Jan  3 11:45:10 2016]  [<ffffffff814050d4>] dump_stack+0x45/0x57
[Sun Jan  3 11:45:10 2016]  [<ffffffffa017e887>] spl_dumpstack+0x3d/0x3f [spl]
[Sun Jan  3 11:45:10 2016]  [<ffffffffa017e930>] spl_panic+0xa7/0xda [spl]
[Sun Jan  3 11:45:10 2016]  [<ffffffff814095da>] ? _raw_spin_lock+0x9/0xb
[Sun Jan  3 11:45:10 2016]  [<ffffffffa017a35e>] ? spl_slab_reclaim+0x38/0x2ee [spl]
[Sun Jan  3 11:45:10 2016]  [<ffffffffa0180763>] ? __cv_signal+0x97/0x9c [spl]
[Sun Jan  3 11:45:10 2016]  [<ffffffffa11983e1>] ? hdr_recl+0x3a/0x3c [zfs]
[Sun Jan  3 11:45:10 2016]  [<ffffffffa017add3>] ? spl_kmem_cache_reap_now+0x15b/0x167 [spl]
[Sun Jan  3 11:45:10 2016]  [<ffffffffa119ff6a>] arc_shrink+0xcf/0x118 [zfs]
[Sun Jan  3 11:45:10 2016]  [<ffffffffa11a00e2>] arc_reclaim_thread+0x12f/0x31e [zfs]
[Sun Jan  3 11:45:10 2016]  [<ffffffffa119ffb3>] ? arc_shrink+0x118/0x118 [zfs]
[Sun Jan  3 11:45:10 2016]  [<ffffffffa017b21c>] thread_generic_wrapper+0x9d/0xaa [spl]
[Sun Jan  3 11:45:10 2016]  [<ffffffffa017b17f>] ? __thread_exit+0x12/0x12 [spl]
[Sun Jan  3 11:45:10 2016]  [<ffffffff81052dda>] kthread+0xa0/0xa8
[Sun Jan  3 11:45:10 2016]  [<ffffffff81052d3a>] ? __kthread_parkme+0x5c/0x5c
[Sun Jan  3 11:45:10 2016]  [<ffffffff81409cd2>] ret_from_fork+0x42/0x70
[Sun Jan  3 11:45:10 2016]  [<ffffffff81052d3a>] ? __kthread_parkme+0x5c/0x5c
[Sun Jan  3 11:45:10 2016] PANIC at arc.c:3194:arc_shrink()
[Sun Jan  3 11:45:10 2016] Showing stack for process 19892
[Sun Jan  3 11:45:10 2016] CPU: 10 PID: 19892 Comm: ceph-osd Tainted: P        W  O    4.1.15+ #16
[Sun Jan  3 11:45:10 2016] Hardware name: Supermicro H8QG6/H8QG6, BIOS 3.00       09/04/2012
[Sun Jan  3 11:45:10 2016]  0000000000000c7a ffff880de0eaf4b8 ffffffff814050d4 00000000c55fc55f
[Sun Jan  3 11:45:10 2016]  ffffffffa127e792 ffff880de0eaf4c8 ffffffffa017e887 ffff880de0eaf648
[Sun Jan  3 11:45:10 2016]  ffffffffa017e930 0000000000000020 0000000000000028 ffff880de0eaf658
[Sun Jan  3 11:45:10 2016] Call Trace:
[Sun Jan  3 11:45:10 2016]  [<ffffffff814050d4>] dump_stack+0x45/0x57
[Sun Jan  3 11:45:10 2016]  [<ffffffffa017e887>] spl_dumpstack+0x3d/0x3f [spl]
[Sun Jan  3 11:45:10 2016]  [<ffffffffa017e930>] spl_panic+0xa7/0xda [spl]
[Sun Jan  3 11:45:10 2016]  [<ffffffff8105a8fc>] ? default_wake_function+0xd/0xf
[Sun Jan  3 11:45:10 2016]  [<ffffffff810676f9>] ? autoremove_wake_function+0xf/0x32
[Sun Jan  3 11:45:10 2016]  [<ffffffff8106721b>] ? __wake_up_common+0x50/0x7e
[Sun Jan  3 11:45:10 2016]  [<ffffffff81067288>] ? __wake_up+0x3f/0x46
[Sun Jan  3 11:45:10 2016]  [<ffffffffa119ff6a>] arc_shrink+0xcf/0x118 [zfs]
[Sun Jan  3 11:45:10 2016]  [<ffffffffa11a037a>] arc_shrinker_func_scan_objects+0xa9/0x123 [zfs]
[Sun Jan  3 11:45:10 2016]  [<ffffffff810c616b>] shrink_slab+0x1b2/0x227
[Sun Jan  3 11:45:10 2016]  [<ffffffff810c8976>] shrink_zone+0x165/0x256
[Sun Jan  3 11:45:10 2016]  [<ffffffff810c8c0b>] do_try_to_free_pages+0x1a4/0x337
[Sun Jan  3 11:45:10 2016]  [<ffffffff810c8e27>] try_to_free_pages+0x89/0x90
[Sun Jan  3 11:45:10 2016]  [<ffffffff810c0ed0>] __alloc_pages_nodemask+0x486/0x6d3
[Sun Jan  3 11:45:10 2016]  [<ffffffff810eb24c>] alloc_pages_current+0xb4/0xd5
[Sun Jan  3 11:45:10 2016]  [<ffffffff810cf597>] ? zone_statistics+0x6a/0x6d
[Sun Jan  3 11:45:10 2016]  [<ffffffff810f015d>] alloc_slab_page+0x42/0xdb
[Sun Jan  3 11:45:10 2016]  [<ffffffff810f147e>] new_slab+0x6a/0x221
[Sun Jan  3 11:45:10 2016]  [<ffffffff810f2a13>] __slab_alloc+0x335/0x3c0
[Sun Jan  3 11:45:10 2016]  [<ffffffff813586c1>] ? __alloc_skb+0x79/0x1a9
[Sun Jan  3 11:45:10 2016]  [<ffffffff8135868f>] ? __alloc_skb+0x47/0x1a9
[Sun Jan  3 11:45:10 2016]  [<ffffffff810f4eac>] __kmalloc_node_track_caller+0x8b/0xf5
[Sun Jan  3 11:45:10 2016]  [<ffffffff813586c1>] ? __alloc_skb+0x79/0x1a9
[Sun Jan  3 11:45:10 2016]  [<ffffffff813558fb>] __kmalloc_reserve.isra.21+0x2c/0x7a
[Sun Jan  3 11:45:10 2016]  [<ffffffff8135868f>] ? __alloc_skb+0x47/0x1a9
[Sun Jan  3 11:45:10 2016]  [<ffffffff813586c1>] __alloc_skb+0x79/0x1a9
[Sun Jan  3 11:45:10 2016]  [<ffffffff811d0d73>] ? copy_from_iter+0x1a9/0x256
[Sun Jan  3 11:45:10 2016]  [<ffffffff8139af13>] sk_stream_alloc_skb+0x33/0xe0
[Sun Jan  3 11:45:10 2016]  [<ffffffff8139b6b9>] tcp_sendmsg+0x2b3/0x79c
[Sun Jan  3 11:45:10 2016]  [<ffffffff813bb755>] inet_sendmsg+0x33/0x5b
[Sun Jan  3 11:45:10 2016]  [<ffffffff8134f4d0>] sock_sendmsg_nosec+0x12/0x1d
[Sun Jan  3 11:45:10 2016]  [<ffffffff81350400>] ___sys_sendmsg+0x195/0x20a
[Sun Jan  3 11:45:10 2016]  [<ffffffff8108e01d>] ? futex_wake+0xdb/0xec
[Sun Jan  3 11:45:10 2016]  [<ffffffff8108f922>] ? do_futex+0xd2/0x777
[Sun Jan  3 11:45:10 2016]  [<ffffffff810ad084>] ? acct_account_cputime+0x17/0x19
[Sun Jan  3 11:45:10 2016]  [<ffffffff81119a47>] ? __fget+0x1f/0x55
[Sun Jan  3 11:45:10 2016]  [<ffffffff81119ad5>] ? __fget_light+0x3b/0x46
[Sun Jan  3 11:45:10 2016]  [<ffffffff81350713>] __sys_sendmsg+0x3d/0x5b
[Sun Jan  3 11:45:10 2016]  [<ffffffff810b9939>] ? context_tracking_user_enter+0xe/0x10
[Sun Jan  3 11:45:10 2016]  [<ffffffff8135073e>] SyS_sendmsg+0xd/0x17
[Sun Jan  3 11:45:10 2016]  [<ffffffff81409917>] system_call_fastpath+0x12/0x6a

Current values as provided by arcstats:
p                               4    528444288
c                               4    8451921920
c_min                           4    8452446208
c_max                           4    135239139328
size                            4    25676652440

**Comment by dweeezil** [comment]
See https://github.com/zfsonlinux/zfs/issues/3904#issuecomment-148055169.  Unfortunately, we don't have a full fix for this problem yet.
