### ISSUE TITLE
filesystem refquota not enforced over cifs

### ISSUE THREAD

**Issue by luozhengzheng** [zfsonlinux/zfs#4164]
Dear All,

testing ZFS on Linux I ran into a problem with filesystem refquotas on ZFS . that is, the refquotas can't enforece the filesystem correctly.  In the following example,a empty zfs filesystem (vd1/16390)is created and the quota is set to 50M. but 50.0015M data can write to the filesystem, which is a little over the requota, who can explain why? thanks.

by the way, no related snapshot or clones with the filesystem.

# zfs_do_list()
NAME          USED        AVAIL  REFER
vd1/16390     50.0015M    0      50.0015M

**Comment by behlendorf** [comment]
@luozhengzheng this isn't intuitive but it is by design.  The most efficient way to enforce quotas is at part of the transaction engine.  This means you can slightly overshoot your quota by get enough updates in to a single transaction group.
