### ISSUE TITLE
ZIO pipeline can not done and no chance to reexecute

### ISSUE THREAD

**Issue by liaoyuxiangqin** [zfsonlinux/zfs#4167]
Dear All,

testing ZFS on Linux I ran into a problem with ZIO pipeline execute exception. when accessing the ZFS filesystem via NFS(v3/v4),  when disconnect and connect the disk at the same time zio is possible to can not done and no chance to reexecute. Furthermore the spa sync thread will suspend due to wait orphans zio done.

I thank that the problem has a relationship with the following code, and detail description as follows:
    /*
     \* Godfather I/Os should never suspend.
     */
    if ((zio->io_flags & ZIO_FLAG_GODFATHER) &&
        (zio->io_reexecute & ZIO_REEXECUTE_SUSPEND))
        zio->io_reexecute = 0;
In this code, when godfather zio's io_reexecute member contain ZIO_REEXECUTE_SUSPEND bit, its io_reexecute member will reset, and then execute done and destroy.
In my test, the godfather zio only indicate spa_suspend_zio_root, when i testing the godfather zio have two or more children and then resume it via zpool clear, so the zio_reexecute function will recursive reexecute all previously suspended i/o.

After resume the godfather zio , if some child zio's io_reexecute member assigned ZIO_REEXECUTE_NOW bit, but others assigned ZIO_REEXECUTE_SUSPEND bit,  
so the godfather zio's io_reexecute member will inherit both ZIO_REEXECUTE_NOW and ZIO_REEXECUTE_SUSPEND bit.

However these child zio which io_reexecute member  assigned ZIO_REEXECUTE_SUSPEND will remove from current godfater zio's child list and add to new spa_suspend_zio_root's  child list, but others zio which  io_reexecute member  assigned ZIO_REEXECUTE_NOW only notify godfater zio to execute and inherit io_reexecute member  value to godfater zio. 

At last, the godfater zio execute above code in zio_done function, and then godfather zio execute done and destroy, so that these child zio which  io_reexecute member assigned ZIO_REEXECUTE_NOW will lose parent  zio and have no chance to reexecute.

**Comment by loli10K** [comment]
This should be fixed by https://github.com/zfsonlinux/zfs/commit/a32494d22ac25c35c5d26eb0b2607ea68adb93cd, @liaoyuxiangqin can we close this?

**Comment by liaoyuxiangqin** [comment]
@loli10K  okay, I'm very glad to this problem was solved.
