### ISSUE TITLE
[dependencies, misc] Illumos 2605 want to resume interrupted zfs send

### ISSUE THREAD

**Issue by kernelOfTruth** [zfsonlinux/zfs#4172]
[dependencies]

Lots of files are in a state requiring several of the pending pull-requests already merged or requiring even newer ones

posting here - otherwise this functionality and commit is hard to track successfully and merge properly

<del> 5745 https://github.com/zfsonlinux/zfs/commit/23de906c72946da56a54f75238693e186d44d6e2 Illumos 5745 - zfs set allows only one dataset property to be set at a time </del>
--------------------------------------------------------------------------------------------------
<del> 5746 https://github.com/zfsonlinux/zfs/commit/37f8a8835a88da6122e2526d6aaeeef75556a7bd Illumos 5746 - more checksumming in zfs send </del>
--------------------------------------------------------------------------------------------------

5960, 5925 https://github.com/zfsonlinux/zfs/pull/4142 Illumos 5960 zfs recv should prefetch indirect blocks, Illumos 5925 zfs receive -o origin= 

--------------------------------------------------------------------------------------------------

5987 https://github.com/zfsonlinux/zfs/pull/4145 Illumos 5987 zfs prefetch code needs work

--------------------------------------------------------------------------------------------------

4929 https://github.com/zfsonlinux/zfs/pull/4159 Illumos 4929 want prevsnap property

--------------------------------------------------------------------------------------------------

6171 https://github.com/zfsonlinux/zfs/pull/3988 Illumos 6171 dsl_prop_unregister() slows down dataset eviction.

**Comment by kernelOfTruth** [comment]
[regression tests]

https://github.com/zfsonlinux/zfs/commit/0cee24064a79f9c01fc4521543c37acea538405f Speed up 'zfs list -t snapshot -o name -s name'

```zfs list -t snapshot -o name -s name```

still needs to work fairly quick

------------------------------------------------------------------------------------------------------------------------

[new tests]

usr/src/test/zfs-tests/include/commands.cfg

usr/src/test/zfs-tests/runfiles/delphix.run

usr/src/test/zfs-tests/runfiles/omnios.run

usr/src/test/zfs-tests/runfiles/openindiana.run

usr/src/test/zfs-tests/tests/functional/rsend/Makefile

usr/src/test/zfs-tests/tests/functional/rsend/rsend.kshlib

usr/src/test/zfs-tests/tests/functional/rsend/rsend_019_pos.ksh

usr/src/test/zfs-tests/tests/functional/rsend/rsend_020_pos.ksh

usr/src/test/zfs-tests/tests/functional/rsend/rsend_021_pos.ksh

usr/src/test/zfs-tests/tests/functional/rsend/rsend_022_pos.ksh

usr/src/test/zfs-tests/tests/functional/rsend/rsend_024_pos.ksh

**Comment by kernelOfTruth** [comment]
```
diff --git a/lib/libzfs/Makefile.am b/lib/libzfs/Makefile.am
index e7d33f3..c9632da 100644
--- a/lib/libzfs/Makefile.am
+++ b/lib/libzfs/Makefile.am
@@ -20,7 +20,7 @@
 #
 #
 # Copyright (c) 2005, 2010, Oracle and/or its affiliates. All rights reserved.
-# Copyright (c) 2012 by Delphix. All rights reserved.
+# Copyright (c) 2011, 2014 by Delphix. All rights reserved.
 #
 
 LIBRARY= libzfs.a
@@ -72,6 +72,9 @@ LDLIBS +=	-lc -lm -ldevid -lgen -lnvpair -luutil -lavl -lefi \
 	-ladm -lidmap -ltsol -lmd -lumem -lzfs_core
 CPPFLAGS +=	$(INCS) -D_LARGEFILE64_SOURCE=1 -D_REENTRANT
 
+# There's no lint library for zlib, so only include this when building
+$(DYNLIB) := LDLIBS +=	-lz
+
 CERRWARN +=	-_gcc=-Wno-switch
 CERRWARN +=	-_gcc=-Wno-parentheses
 CERRWARN +=	-_gcc=-Wno-uninitialized
```

**Comment by kernelOfTruth** [comment]
```
diff --git a/lib/libzfs/libzfs_sendrecv.c b/lib/libzfs/libzfs_sendrecv.c
index b155fc8..b9b0f68 100644
--- a/lib/libzfs/libzfs_sendrecv.c
+++ b/lib/libzfs/libzfs_sendrecv.c
@@ -21,7 +21,7 @@
 
 /*
  * Copyright (c) 2005, 2010, Oracle and/or its affiliates. All rights reserved.
- * Copyright (c) 2011, 2014 by Delphix. All rights reserved.
+ * Copyright (c) 2011, 2015 by Delphix. All rights reserved.
  * Copyright (c) 2012, Joyent, Inc. All rights reserved.
  * Copyright (c) 2013 Steven Hartland. All rights reserved.
  */
@@ -48,6 +48,7 @@
 #include "zfs_prop.h"
 #include "zfs_fletcher.h"
 #include "libzfs_impl.h"
+#include <zlib.h>
 #include <sha2.h>
 #include <sys/zio_checksum.h>
 #include <sys/ddt.h>
```

hm, so ZFS also needs zlib / gzip support ?

**Comment by kernelOfTruth** [comment]
alright so where does the sha2.h file come from - and where do we need it ?

https://gist.github.com/kernelOfTruth/ca85a32db3f2db554cda zfs illumos-gate sha2.h commits, libzfs_sendrecv.c

**Comment by behlendorf** [comment]
@kernelOfTruth what's going on in this issue?  Is it something you'd like to leave open now that the bulk of the dependencies have been merged?

**Comment by kernelOfTruth** [comment]
@behlendorf yes, this issue can be closed 

the two things currently concerning me is 

https://github.com/zfsonlinux/zfs/commit/0cee24064a79f9c01fc4521543c37acea538405f Speed up 'zfs list -t snapshot -o name -s name'

this one is noted here,

and the tests included by this commit:

can these be also tested via the buildbots or is this Illumos, Solaris, etc. specific ?

anyway - closing

Thanks !

**Comment by behlendorf** [comment]
There's been an on-again off-again effort to pull those tests over for the buildbot to run but it's been something of a slog and not yet ready.

**Comment by kernelOfTruth** [comment]
Understood, these tests appear quite complex (and useful !) - so I'm sure there's also significant porting work to be done to get them to work with Linux
