### ISSUE TITLE
zfs/kernel crash when mounting dataset, stacktrace provided

### ISSUE THREAD

**Issue by rsyring** [zfsonlinux/zfs#4183]
## The Problem

Whenever I try to mount my `rpool/ROOT` dataset I get a zfs/kernel (?) stack trace.  See below for images of the problem (no root filesystem so no way to get the text representation that I am aware of).
## System Info
- Macbook Pro (11,1) w/ 1 TB SSD drive
  - At most, 150GB of data
- Recently installed ZFS on root on ubuntu 14.04.
- Using the latest stable ZFS as released by the ZFS on Linux ppa team.
- Running a 4.2.x kernel, but I also couldn't boot into my 3.13.x backup kernel.
- Installed on a luks container following these instructions:
  https://help.ubuntu.com/community/encryptedZfs
- The above was all working fine for at least the past couple of days
- Recently ran memtest86 overnight (4 passes) and had no detectable
  memory errors
## Changes made that caused (?) problem
- Wanted to use a bit different of a snapshot scheme for data files vs
  system files
- Moved /home /etc /tmp from normal directories on rpool/ROOT to instead
  be zfs datasets mounted in those locations
  - rpool/data/home, rpool/data/etc, etc.
- Booted into single-user mode in order to complete the setup of the new
  zfs datasets and their mount points
- When I moved the home directory, it was about 60GB of data
- When I moved the /etc directory, I had some problems getting ZFS to
  work.  In hindsight, I probably shouldn't have tried to put /etc on a
  separate dataset.  The last thing I did was setup the zfs dataset to mount
  at /etc, moved /etc to /etc.bak, and rebooted.
- The system wouldn't reboot with shutdown -r now, so I ended up just
  holding the power button until the computer shutdown.
## Troubleshooting

With help given on this mailing list thread (http://list.zfsonlinux.org/pipermail/zfs-discuss/2016-January/024261.html) I have been able to do the following:
- was able to log into the initramfs console (busybox)
- import rpool using -N, 
- zpool status shows no errors
- perform a scrub (no errors)
- remove rpool/data/etc
- mount rpool/data/home and browse the files.  
- send snapshots of rpool/ROOT to a different pool on a backup hard drive
- mount a snapshot of rpool/ROOT that was taken a couple hours before I started the modifications noted in "Recent Changes" above.
## Stack Trace

![2016-01-08 09 11 17](https://cloud.githubusercontent.com/assets/109467/12202993/a42c1690-b5fa-11e5-8808-f075dee762a5.jpg)
![2016-01-08 11 03 09-1](https://cloud.githubusercontent.com/assets/109467/12202992/a428aa1e-b5fa-11e5-8a2b-66099dd5367d.jpg)

**Comment by dweeezil** [comment]
For some reason there seems to be a rash of these lately.  See 29572cc and f5f087e for fixes.I suspect the former will cherry-pick cleanly into just about any version and allow you to mount.

**Comment by rsyring** [comment]
@dweeezil I really appreciate the quick response.  I was able to patch the source to match 29572cc and then I could boot back into that dataset.

**Comment by behlendorf** [comment]
@rsyring great to hear.  These two patches will be in the point release, if your curious was other fixes will be you can follow the release branch https://github.com/zfsonlinux/zfs/commits/zfs-0.6.5-release.

**Comment by dajhorn** [comment]
@rsyring, those patches are in the Ubuntu dailies.

**Comment by behlendorf** [comment]
Closing as resolved.
