### ISSUE TITLE
zpl_inode.c:zpl_lookup fails to set flags required to return the CI name of zfs snapshot dirs

### ISSUE THREAD

**Issue by RichardSharpe** [zfsonlinux/zfs#4185]
Hi,

After we fixed the case-insensitive rename issue, we ran into a snapshot issue.

zfs_dirlook is failing to fill in the pathname if it is a fake .zfs snapshot dir.

The fix seems to be:
```
diff --git a/module/zfs/zfs_dir.c b/module/zfs/zfs_dir.c
index 712cb46..ced8ee6 100644
--- a/module/zfs/zfs_dir.c
+++ b/module/zfs/zfs_dir.c
@@ -436,6 +436,8 @@ zfs_dirlook(znode_t *dzp, char *name, struct inode
**ipp, int flags,
                rw_exit(&dzp->z_parent_lock);
        } else if (zfs_has_ctldir(dzp) && strcmp(name, ZFS_CTLDIR_NAME) == 0) {
                *ipp = zfsctl_root(dzp);
+                if (rpnp)
+                        (void) strlcpy(rpnp->pn_buf, ZFS_CTLDIR_NAME, rpnp->pn_bufsize);
        } else {
                int zf;
```

**Comment by RichardSharpe** [comment]
I will prepare another change ...

**Comment by behlendorf** [comment]
Better yet have `zpl_lookup()` set FIGNORECASE in `flags` when case insensitive.  That way it's get set properly at the end of `zfs_dirlook()`.

**Comment by RichardSharpe** [comment]
OK, so that is our bug. Thanks.

We will test with that and another update will be forthcoming.

**Comment by behlendorf** [comment]
@RichardSharpe please open a new pull request with this fix.  As it turns out I merged your latest version to master just moments before I saw you open this issue.

**Comment by RichardSharpe** [comment]
Shall do.

**Comment by tuxoko** [comment]
@RichardSharpe 
The original patch doesn't seem complete.
https://github.com/zfsonlinux/zfs/blob/c5d0287011679d76288c2617c409252245172a32/module/zfs/zpl_inode.c#L80

Under case insensitive, if we do d_splice_alias, which hash the negative dentry, we would end up with all sorts of mixed-case negative dentries in the hash. If we create a file later with one of the names, we cannot lookup with other names.

**Comment by behlendorf** [comment]
Good point, I hadn't considered that case.  That could lead to some strange behavior until the mixed case negative dentries were naturally dropped from the cache.

**Comment by RichardSharpe** [comment]
Edited title to indicate the real problem.

**Comment by RichardSharpe** [comment]
tuxoko: OK, I see what you mean. 

OK, so what we should do in the ENOENT error path is add the negative entry in a CI manner.

**Comment by behlendorf** [comment]
Yes, that should address it.  That way we're always using the CI name for cache lookups.

**Comment by RichardSharpe** [comment]
So, at least in 3.10 there seems to be no way to indicate that a negative entry is case insensitive. Let me check if there is one in later kernels.

**Comment by RichardSharpe** [comment]
Thinking about this some more, there will only be multiple, case-different negative entries in the dcache if someone does some fairly pathological stuff, I imagine.

For example, say we are looking up somefile.txt, if the application did a stat on each case version, we would end up with ~2048 negative entries. Eg, somefile.txt, Somefile.txt, sOmefile.txt ... However, typically, the application will present the name, in one case, say somefile.txt, get ENOENT (which will install somefile.txt as a negative entry) and then go and try to create with that same case. The create will then succeed, so the negative entry will be converted to a positive entry with the correct name.

After that, any other case that it presents will match the name as created and will not generate a negative entry.

**Comment by tuxoko** [comment]
The easy fix should be just return NULL, so negative dentry would always be dropped.

**Comment by RichardSharpe** [comment]
Yes, you are correct. I realized this in the car on the way home.

This means that we do without the negative entries on a CI file system.

Anything else would require support from Linux. I could imagine each dentry having a pointer to a canonicalize function or table, but that probably would not fly and we already get plenty of benefit from the current approach.

**Comment by RichardSharpe** [comment]
Also, I think I will have to look at the rename and delete path because if we convert those dentries to negative entries then I will have to delete them on a case-insensitive FS.

**Comment by RichardSharpe** [comment]
After reading through a bunch of code, it seems that rename does not create negative entries but unlink does.

To properly handle this we would have to implement our own dentry operations, I think.

However, the first thing to do is to stop creating negative entries.

**Comment by behlendorf** [comment]
Just so you're aware we already do register `zpl_revalidate()` to handle invalidating dentries for other circumstances such as `zfs rollback`.

**Comment by RichardSharpe** [comment]
Thanks for that info.

Looks like I need two dentry_operations_t structures, one with just zpl_revalidate and one with both that an a new function, zpl_dentry_iput.

The second dentry_operations_t structure would be used when we are a case-insensitive files system.

The new function would call d_drop on the dentry and iput on the inode.

Seems pretty straightforward.

I am working on cleaning up the last few issues (not creating negative entries when we are case insensitive and passing FIGNORECASE to zfs_lookup when we are case insensitive.)

**Comment by RichardSharpe** [comment]
It turns out that it is not simply a case of returning NULL in all cases if we are a CI file system.

You have to pay attention to the flags passed into zpl_lookup and if you don't things like touch start failing.

**Comment by RichardSharpe** [comment]
In particular, it seems that something like this is neeed:
```
        if (error) {
                /*
                 * If CI, don't create negative entries but only
                 * if there was no intent.
                 */
                if (ppn && !(flags & 0x7f00)) {
                        if (error == -ENOENT)
                                printk(KERN_WARNING "%s:name not found: %s, flags: %0X\n",
                                        __func__, dname(dentry), flags);
                        kmem_free(pn.pn_buf, ZFS_MAXNAMELEN);
                        return (ERR_PTR(error));
                }

                if (error == -ENOENT) {
                        printk(KERN_WARNING "returning megative entry for %s\n",
                                dname(dentry));
                }
                else {
                        printk(KERN_WARNING "returning error %d for %s\n", error,
                                dname(dentry));
                }
                if (error == -ENOENT)
                        return (d_splice_alias(NULL, dentry));
                else
                        return (ERR_PTR(error));
        }
```

The printks can go.

However, to have this build for kernels where nameidata is passed in rather than flags, it will need to have some ifdefs.

Also, flags & 0x7f00 is pretty ugly. Need to define a symbol with all the appropriate bits.

With that and the new dentry ops for CI file systems, things seem to be more correct.

Tests involve doing things like:

1. create some-file.txt
2. delete some-file.txt
3. create Some-file.txt
4. Try to lookup some-file.txt and check if it gets all the way to zpl_lookup.

**Comment by tuxoko** [comment]
No, return NULL is the correct way http://lxr.free-electrons.com/source/fs/xfs/xfs_iops.c#L261

**Comment by RichardSharpe** [comment]
I have tested both the only returning NULL approach and the approach above.

The test I use is:

1. ls some-file.txt # This should return ENOENT when it does not exist.
2. touch Some-file.txt # Create a file with a name differing only by the case of the first char
3. ls some-file.txt

If the first step created a negative entry in the dcache, step 3 will fail with ENOENT when it should not.

Returning NULL seems to cause ENOENT in step 3, while doing as above seems to work.

I will post the full patch I am now using.

**Comment by RichardSharpe** [comment]
Here is the change:
```
iff --git a/module/zfs/zpl_inode.c b/module/zfs/zpl_inode.c
index 33a780c..9530ec9 100644
--- a/module/zfs/zpl_inode.c
+++ b/module/zfs/zpl_inode.c
@@ -31,7 +31,10 @@
 #include <sys/dmu_objset.h>
 #include <sys/vfs.h>
 #include <sys/zpl.h>
+#include <sys/file.h>

+dentry_operations_t zpl_dentry_operations;
+dentry_operations_t zpl_ci_dentry_operations;

 static struct dentry *
 #ifdef HAVE_LOOKUP_NAMEIDATA
@@ -46,11 +49,12 @@ zpl_lookup(struct inode *dir, struct dentry *dentry, unsigned int flags)
        fstrans_cookie_t cookie;
        pathname_t *ppn = NULL;
        pathname_t pn;
+       int zfs_flags = 0;
        zfs_sb_t *zsb = dentry->d_sb->s_fs_info;

-       /* What about mixed case? */
        /* If we are a case insensitive fs, we need the real name */
        if (zsb->z_case == ZFS_CASE_INSENSITIVE) {
+               zfs_flags = FIGNORECASE;
                pn.pn_bufsize = MAXNAMELEN; /* Should this be PATH_MAX? */
                pn.pn_buf = kmem_zalloc(MAXNAMELEN, KM_SLEEP);
                ppn = &pn;
@@ -61,19 +65,40 @@ zpl_lookup(struct inode *dir, struct dentry *dentry, unsigned int flags)

        crhold(cr);
        cookie = spl_fstrans_mark();
-       error = -zfs_lookup(dir, dname(dentry), &ip, 0, cr, NULL, ppn);
+       error = -zfs_lookup(dir, dname(dentry), &ip, zfs_flags, cr, NULL, ppn);
        spl_fstrans_unmark(cookie);
        ASSERT3S(error, <=, 0);
        crfree(cr);

        spin_lock(&dentry->d_lock);
        dentry->d_time = jiffies;
-#ifndef HAVE_S_D_OP
-       d_set_d_op(dentry, &zpl_dentry_operations);
-#endif /* HAVE_S_D_OP */
+       /* If case insensitive, add correct dentry ops */
+       printk(KERN_WARNING "%s: Adding dentry ops (ci == %d) for %s!\n",
+               __func__, (ppn != NULL), dname(dentry));
+       if (ppn)
+               d_set_d_op(dentry, &zpl_ci_dentry_operations);
+       else
+               d_set_d_op(dentry, &zpl_dentry_operations);
        spin_unlock(&dentry->d_lock);

        if (error) {
+               /*
+                * If CI, don't create negative entries but only
+                * if there was no intent.
+                */
+               if (ppn && !(flags & 0x7f00)) {
+                       kmem_free(pn.pn_buf, ZFS_MAXNAMELEN);
+
+                       if (error == -ENOENT) {
+                               printk(KERN_WARNING "%s:name not found: %s, flags: %0X\n",
+                                       __func__, dname(dentry), flags);
+                       } else {
+                               printk(KERN_WARNING "%s: error %d for %s\n", __func__,
+                                       error, dname(dentry));
+                       }
+                       return (ERR_PTR(error));
+               }
+
                if (error == -ENOENT)
                        return (d_splice_alias(NULL, dentry));
                else
@@ -88,17 +113,8 @@ zpl_lookup(struct inode *dir, struct dentry *dentry, unsigned int flags)
                struct dentry *new_dentry;
                struct qstr real_name;

-#if 0
-               /* Were names different? */
-               if (bcmp(pn.pn_buf, dname(dentry), dlen(dentry))) {
-                       printk(KERN_WARNING "Name in lookup (%s) differs from fs (%s)",
-                               dname(dentry), pn.pn_buf);
-               }
-#endif
-
                real_name.name = pn.pn_buf;
                real_name.len = strlen(pn.pn_buf);
-               real_name.hash = full_name_hash(real_name.name, real_name.len);
                new_dentry = d_add_ci(dentry, ip, &real_name);
                kmem_free(pn.pn_buf, MAXNAMELEN);
                return (new_dentry);
@@ -513,6 +529,20 @@ zpl_fallocate(struct inode *ip, int mode, loff_t offset, loff_t len)
 }
 #endif /* HAVE_INODE_FALLOCATE */

+/*
+ * Case insensitive dentry iput function. We want to get rid of
+ * the dentry, not make it negative because we do want case sensitive
+ * negative entries hanging around if
+ */
+static void
+zpl_ci_iput(struct dentry *dentry, struct inode *inode)
+{
+       printk(KERN_WARNING "dropping dentry %p (%s) for inode %lu\n",
+               dentry, dname(dentry), inode->i_ino);
+       d_drop(dentry);
+       iput(inode);
+}
+
 static int
 #ifdef HAVE_D_REVALIDATE_NAMEIDATA
 zpl_revalidate(struct dentry *dentry, struct nameidata *nd)
@@ -657,3 +687,8 @@ const struct inode_operations zpl_special_inode_operations = {
 dentry_operations_t zpl_dentry_operations = {
        .d_revalidate   = zpl_revalidate,
 };
+
+dentry_operations_t zpl_ci_dentry_operations = {
+       .d_revalidate   = zpl_revalidate,
+       .d_iput         = zpl_ci_iput,
+};
```

However, it still needs cleaning up and further testing.
