### ISSUE TITLE
pool full giving loads of problems

### ISSUE THREAD

**Issue by stormeporm** [zfsonlinux/zfs#4206]
Edit 
This has already been fixed in 0.65 its probably because the spa_slop_shift is still 6 in 0.64 it has been changed to 5 in 0.65
Maybe it can be backported to 0.64 with a big warning that before installing you should check that you pool is less than 97% full
https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.6.5
## https://github.com/zfsonlinux/zfs/issues/3724

First the setup.
6 raidz pools with 6x4tb disks. 
64gb ram 
ubuntu 15.10
zfs v0.6.4.2-0ubuntu1.1, ZFS pool version 5000, ZFS filesystem version 5

zpool list
NAME    SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
tank0  21.8T  21.4T   348G         -    59%    98%  1.00x  ONLINE  -
tank1  21.8T  21.4T   348G         -    61%    98%  1.00x  ONLINE  -
tank2  21.8T  21.4T   348G         -    62%    98%  1.00x  ONLINE  -
tank3  21.8T  21.4T   348G         -    61%    98%  1.00x  ONLINE  -
tank4  21.8T  21.4T   348G         -    61%    98%  1.00x  ONLINE  -
tank5  21.8T  21.4T   348G         -    62%    98%  1.00x  ONLINE  -

Output of df -h
tank0            18T   18T     0 100% /tank0
tank3            18T   18T  512K 100% /tank3
tank1            18T   18T  101M 100% /mnt/disk1
tank2            18T   18T  101M 100% /mnt/disk2
tank4            18T   18T  101M 100% /mnt/disk4
tank5            18T   18T  101M 100% /mnt/disk5

For some test I have completely filled the pools. four out six of  are doing fine but two of them are acting strangely. 
tank0 and tank3 as you can see they have 0K left and 512K.Yes they also have different mount points but that is because I cant change the mount point like the other ones.
When I try to change the mountpoint I get an error that I cant do it because its full.
Sorry I cant reproduce the exact error because I've started a scrub on the two mountpoints. Just to see if it will help.
And I cant stop the scrub because I'm out of space. error: "cannot cancel scrubbing tank0: out of space"

So I'm out of space lets delete something problem solved right?

On tank 3 it did not work at first because the pool was empty when I did an ls on it. 
After rebooting the machine and manually mounting the pool I could delete a file and my problems are solved. 

On tank0 I had the same error of not seeing any file with an ls, rebooting and remounting fixed that. But I can still not delete a file,  error: "rm: cannot remove ‘testb.00253455’: No space left on device"

So my current situation is 5 tanks work and tank0 is giving me problems when I want to change anything of try to fix the problem.

The data on the pools is totally irrelevant accept that it takes a day to create it. But I want to know if the is a fix for this and learn some doing it.

I'm leaving the pools in this state so I can do some trouble shooting on it maybe we can find a solution. 
My question is how to trouble shoot it and will you help me with it.

More observations
"df"  says its full and "zfs list" says there is 348G free.
But when I look at the meta slabs I cant find the 348G free.
I see 128G at the last slab and like 2GB in total free on the other 173.
Maybe this is correct but can someone explain it to me.

Meta slabs tank 0
zdb -m -e tank0
Metaslabs:
    vdev          0
    metaslabs   174   offset                spacemap          free  
    ---------------   -------------------   ---------------   -------------
    metaslab      0   offset            0   spacemap     38   free    3.08M
    metaslab      1   offset   2000000000   spacemap     39   free    2.02M
    metaslab      2   offset   4000000000   spacemap     46   free    2.34M
    metaslab      3   offset   6000000000   spacemap     47   free    2.36M
    metaslab      4   offset   8000000000   spacemap     48   free    6.56M
    metaslab      5   offset   a000000000   spacemap     49   free    13.0M
    metaslab      6   offset   c000000000   spacemap     50   free    5.96M
    metaslab      7   offset   e000000000   spacemap     51   free    5.02M
    metaslab      8   offset  10000000000   spacemap     52   free    5.92M
    metaslab      9   offset  12000000000   spacemap     53   free    17.8M
    metaslab     10   offset  14000000000   spacemap     56   free    7.03M
    metaslab     11   offset  16000000000   spacemap     57   free    6.39M
    metaslab     12   offset  18000000000   spacemap     58   free    15.3M
    metaslab     13   offset  1a000000000   spacemap     59   free    13.8M
    metaslab     14   offset  1c000000000   spacemap     60   free    17.2M
    metaslab     15   offset  1e000000000   spacemap     62   free    2.36M
    metaslab     16   offset  20000000000   spacemap     63   free    6.57M
    metaslab     17   offset  22000000000   spacemap     76   free    5.95M
    metaslab     18   offset  24000000000   spacemap     77   free    6.73M
    metaslab     19   offset  26000000000   spacemap     78   free    6.84M
    metaslab     20   offset  28000000000   spacemap     79   free    6.25M
    metaslab     21   offset  2a000000000   spacemap     80   free    5.91M
    metaslab     22   offset  2c000000000   spacemap     83   free    4.93M
    metaslab     23   offset  2e000000000   spacemap     84   free    8.52M
    metaslab     24   offset  30000000000   spacemap     85   free     9.7M
    metaslab     25   offset  32000000000   spacemap     86   free    10.1M
    metaslab     26   offset  34000000000   spacemap     87   free    7.48M
    metaslab     27   offset  36000000000   spacemap     88   free    20.6M
    metaslab     28   offset  38000000000   spacemap     90   free    13.5M
    metaslab     29   offset  3a000000000   spacemap     91   free    12.4M
    metaslab     30   offset  3c000000000   spacemap     94   free    13.2M
    metaslab     31   offset  3e000000000   spacemap     95   free    17.2M
    metaslab     32   offset  40000000000   spacemap     97   free    14.5M
    metaslab     33   offset  42000000000   spacemap     37   free    16.4M
    metaslab     34   offset  44000000000   spacemap     67   free    16.0M
    metaslab     35   offset  46000000000   spacemap     69   free    9.05M
    metaslab     36   offset  48000000000   spacemap     98   free    8.28M
    metaslab     37   offset  4a000000000   spacemap     74   free    14.9M
    metaslab     38   offset  4c000000000   spacemap     99   free    14.3M
    metaslab     39   offset  4e000000000   spacemap    100   free    8.39M
    metaslab     40   offset  50000000000   spacemap    101   free    20.4M
    metaslab     41   offset  52000000000   spacemap    102   free    14.8M
    metaslab     42   offset  54000000000   spacemap    103   free    18.1M
    metaslab     43   offset  56000000000   spacemap     55   free    19.6M
    metaslab     44   offset  58000000000   spacemap    105   free    15.1M
    metaslab     45   offset  5a000000000   spacemap    106   free    14.9M
    metaslab     46   offset  5c000000000   spacemap    107   free    7.35M
    metaslab     47   offset  5e000000000   spacemap    108   free    20.8M
    metaslab     48   offset  60000000000   spacemap    109   free    13.9M
    metaslab     49   offset  62000000000   spacemap    110   free    14.1M
    metaslab     50   offset  64000000000   spacemap    111   free    6.88M
    metaslab     51   offset  66000000000   spacemap    112   free    7.75M
    metaslab     52   offset  68000000000   spacemap    113   free    32.6M
    metaslab     53   offset  6a000000000   spacemap    115   free    10.5M
    metaslab     54   offset  6c000000000   spacemap    118   free    14.9M
    metaslab     55   offset  6e000000000   spacemap     82   free    14.9M
    metaslab     56   offset  70000000000   spacemap    119   free    12.2M
    metaslab     57   offset  72000000000   spacemap    120   free    13.7M
    metaslab     58   offset  74000000000   spacemap    121   free    15.5M
    metaslab     59   offset  76000000000   spacemap    122   free    7.77M
    metaslab     60   offset  78000000000   spacemap    123   free    19.5M
    metaslab     61   offset  7a000000000   spacemap    124   free    16.4M
    metaslab     62   offset  7c000000000   spacemap    125   free    14.7M
    metaslab     63   offset  7e000000000   spacemap     93   free    16.9M
    metaslab     64   offset  80000000000   spacemap    126   free    9.23M
    metaslab     65   offset  82000000000   spacemap     96   free    33.9M
    metaslab     66   offset  84000000000   spacemap     36   free    18.5M
    metaslab     67   offset  86000000000   spacemap     68   free    28.1M
    metaslab     68   offset  88000000000   spacemap    129   free    13.8M
    metaslab     69   offset  8a000000000   spacemap    132   free    20.3M
    metaslab     70   offset  8c000000000   spacemap     75   free    14.5M
    metaslab     71   offset  8e000000000   spacemap    133   free    15.1M
    metaslab     72   offset  90000000000   spacemap    135   free    8.44M
    metaslab     73   offset  92000000000   spacemap    136   free    14.5M
    metaslab     74   offset  94000000000   spacemap    139   free    8.50M
    metaslab     75   offset  96000000000   spacemap    140   free    10.8M
    metaslab     76   offset  98000000000   spacemap     61   free    95.9M
    metaslab     77   offset  9a000000000   spacemap    141   free    15.1M
    metaslab     78   offset  9c000000000   spacemap    142   free    21.0M
    metaslab     79   offset  9e000000000   spacemap    143   free    14.6M
    metaslab     80   offset  a0000000000   spacemap    145   free    15.2M
    metaslab     81   offset  a2000000000   spacemap    147   free    13.8M
    metaslab     82   offset  a4000000000   spacemap    148   free    15.0M
    metaslab     83   offset  a6000000000   spacemap    149   free    6.28M
    metaslab     84   offset  a8000000000   spacemap    150   free    9.44M
    metaslab     85   offset  aa000000000   spacemap    151   free    18.4M
    metaslab     86   offset  ac000000000   spacemap    117   free    44.6M
    metaslab     87   offset  ae000000000   spacemap    152   free    12.2M
    metaslab     88   offset  b0000000000   spacemap     81   free    15.6M
    metaslab     89   offset  b2000000000   spacemap     89   free     137M
    metaslab     90   offset  b4000000000   spacemap    154   free    15.5M
    metaslab     91   offset  b6000000000   spacemap    155   free    17.7M
    metaslab     92   offset  b8000000000   spacemap    156   free    31.8M
    metaslab     93   offset  ba000000000   spacemap    159   free    15.0M
    metaslab     94   offset  bc000000000   spacemap    160   free    15.3M
    metaslab     95   offset  be000000000   spacemap    161   free    15.2M
    metaslab     96   offset  c0000000000   spacemap    163   free    28.5M
    metaslab     97   offset  c2000000000   spacemap    165   free    16.9M
    metaslab     98   offset  c4000000000   spacemap    166   free    16.7M
    metaslab     99   offset  c6000000000   spacemap     54   free    18.9M
    metaslab    100   offset  c8000000000   spacemap    167   free    16.1M
    metaslab    101   offset  ca000000000   spacemap    128   free    10.9M
    metaslab    102   offset  cc000000000   spacemap    131   free    15.9M
    metaslab    103   offset  ce000000000   spacemap    169   free    11.9M
    metaslab    104   offset  d0000000000   spacemap    171   free    27.7M
    metaslab    105   offset  d2000000000   spacemap    172   free    15.9M
    metaslab    106   offset  d4000000000   spacemap    173   free    17.8M
    metaslab    107   offset  d6000000000   spacemap    138   free    28.4M
    metaslab    108   offset  d8000000000   spacemap    174   free    16.5M
    metaslab    109   offset  da000000000   spacemap    104   free    31.3M
    metaslab    110   offset  dc000000000   spacemap    175   free    29.1M
    metaslab    111   offset  de000000000   spacemap    177   free    26.3M
    metaslab    112   offset  e0000000000   spacemap    179   free    15.1M
    metaslab    113   offset  e2000000000   spacemap    144   free    49.6M
    metaslab    114   offset  e4000000000   spacemap    146   free     109G
    metaslab    115   offset  e6000000000   spacemap    181   free    29.9M
    metaslab    116   offset  e8000000000   spacemap    182   free    17.7M
    metaslab    117   offset  ea000000000   spacemap    183   free    31.4M
    metaslab    118   offset  ec000000000   spacemap    184   free    33.8M
    metaslab    119   offset  ee000000000   spacemap    116   free    18.6G
    metaslab    120   offset  f0000000000   spacemap    185   free    15.0M
    metaslab    121   offset  f2000000000   spacemap    186   free    7.04M
    metaslab    122   offset  f4000000000   spacemap     92   free    11.2M
    metaslab    123   offset  f6000000000   spacemap    187   free    6.42M
    metaslab    124   offset  f8000000000   spacemap    188   free    7.49M
    metaslab    125   offset  fa000000000   spacemap    157   free    43.4M
    metaslab    126   offset  fc000000000   spacemap    189   free    7.82M
    metaslab    127   offset  fe000000000   spacemap    191   free    6.26M
    metaslab    128   offset 100000000000   spacemap    192   free    10.2M
    metaslab    129   offset 102000000000   spacemap    162   free    2.90M
    metaslab    130   offset 104000000000   spacemap    193   free    12.7M
    metaslab    131   offset 106000000000   spacemap    194   free    11.0M
    metaslab    132   offset 108000000000   spacemap    195   free    10.2M
    metaslab    133   offset 10a000000000   spacemap    196   free    13.1M
    metaslab    134   offset 10c000000000   spacemap    127   free    13.5M
    metaslab    135   offset 10e000000000   spacemap    134   free    26.9M
    metaslab    136   offset 110000000000   spacemap    197   free    12.2M
    metaslab    137   offset 112000000000   spacemap    170   free    16.5M
    metaslab    138   offset 114000000000   spacemap    198   free    11.3M
    metaslab    139   offset 116000000000   spacemap    200   free     9.8M
    metaslab    140   offset 118000000000   spacemap    201   free    10.3M
    metaslab    141   offset 11a000000000   spacemap    202   free    11.5M
    metaslab    142   offset 11c000000000   spacemap    114   free    16.6M
    metaslab    143   offset 11e000000000   spacemap    203   free    10.8M
    metaslab    144   offset 120000000000   spacemap    204   free    11.6M
    metaslab    145   offset 122000000000   spacemap    178   free    22.6M
    metaslab    146   offset 124000000000   spacemap    205   free    10.8M
    metaslab    147   offset 126000000000   spacemap    206   free    11.3M
    metaslab    148   offset 128000000000   spacemap    180   free    52.9M
    metaslab    149   offset 12a000000000   spacemap    207   free    11.9M
    metaslab    150   offset 12c000000000   spacemap    208   free    13.1M
    metaslab    151   offset 12e000000000   spacemap    209   free    10.9M
    metaslab    152   offset 130000000000   spacemap    210   free    11.2M
    metaslab    153   offset 132000000000   spacemap    211   free    11.3M
    metaslab    154   offset 134000000000   spacemap    212   free    10.5M
    metaslab    155   offset 136000000000   spacemap    153   free    24.7M
    metaslab    156   offset 138000000000   spacemap    213   free    11.4M
    metaslab    157   offset 13a000000000   spacemap    214   free    11.9M
    metaslab    158   offset 13c000000000   spacemap    158   free    20.7M
    metaslab    159   offset 13e000000000   spacemap    215   free    10.9M
    metaslab    160   offset 140000000000   spacemap    190   free    43.2M
    metaslab    161   offset 142000000000   spacemap    216   free    12.0M
    metaslab    162   offset 144000000000   spacemap    164   free    24.2M
    metaslab    163   offset 146000000000   spacemap    168   free    23.7M
    metaslab    164   offset 148000000000   spacemap    217   free    12.8M
    metaslab    165   offset 14a000000000   spacemap    218   free    12.0M
    metaslab    166   offset 14c000000000   spacemap    219   free    12.4M
    metaslab    167   offset 14e000000000   spacemap    130   free    11.9M
    metaslab    168   offset 150000000000   spacemap    137   free    11.8M
    metaslab    169   offset 152000000000   spacemap    220   free    12.9M
    metaslab    170   offset 154000000000   spacemap    176   free    24.2M
    metaslab    171   offset 156000000000   spacemap    221   free    90.1G
    metaslab    172   offset 158000000000   spacemap    199   free    46.1M
    metaslab    173   offset 15a000000000   spacemap     64   free     128G

zpool status 

  pool: tank0
 state: ONLINE
  scan: scrub in progress since Mon Jan 11 11:42:15 2016
    4.78T scanned out of 21.4T at 691M/s, 7h0m to go
    0 repaired, 22.34% done
config:

```
NAME        STATE     READ WRITE CKSUM
tank0       ONLINE       0     0     0
  raidz1-0  ONLINE       0     0     0
    F0      ONLINE       0     0     0
    F3      ONLINE       0     0     0
    F2      ONLINE       0     0     0
    F1      ONLINE       0     0     0
    F7      ONLINE       0     0     0
    F6      ONLINE       0     0     0
```

errors: No known data errors

  pool: tank1
 state: ONLINE
  scan: scrub repaired 0 in 9h54m with 0 errors on Wed Jan  6 10:54:24 2016
config:

```
NAME        STATE     READ WRITE CKSUM
tank1       ONLINE       0     0     0
  raidz1-0  ONLINE       0     0     0
    F5      ONLINE       0     0     0
    F4      ONLINE       0     0     0
    F11     ONLINE       0     0     0
    F10     ONLINE       0     0     0
    F9      ONLINE       0     0     0
    F8      ONLINE       0     0     0
```

errors: No known data errors

  pool: tank2
 state: ONLINE
  scan: scrub repaired 0 in 9h49m with 0 errors on Thu Jan  7 10:49:31 2016
config:

```
NAME        STATE     READ WRITE CKSUM
tank2       ONLINE       0     0     0
  raidz1-0  ONLINE       0     0     0
    F15     ONLINE       0     0     0
    F14     ONLINE       0     0     0
    F13     ONLINE       0     0     0
    F12     ONLINE       0     0     0
    F19     ONLINE       0     0     0
    F18     ONLINE       0     0     0
```

errors: No known data errors

  pool: tank3
 state: ONLINE
  scan: scrub in progress since Mon Jan 11 11:42:23 2016
    2.23T scanned out of 21.4T at 516M/s, 10h49m to go
    0 repaired, 10.41% done
config:

```
NAME        STATE     READ WRITE CKSUM
tank3       ONLINE       0     0     0
  raidz1-0  ONLINE       0     0     0
    F17     ONLINE       0     0     0
    F16     ONLINE       0     0     0
    F23     ONLINE       0     0     0
    F22     ONLINE       0     0     0
    F21     ONLINE       0     0     0
    F20     ONLINE       0     0     0
```

errors: No known data errors

  pool: tank4
 state: ONLINE
  scan: scrub repaired 0 in 13h30m with 0 errors on Sat Jan  9 14:30:38 2016
config:

```
NAME        STATE     READ WRITE CKSUM
tank4       ONLINE       0     0     0
  raidz1-0  ONLINE       0     0     0
    B11     ONLINE       0     0     0
    B10     ONLINE       0     0     0
    B9      ONLINE       0     0     0
    B8      ONLINE       0     0     0
    B3      ONLINE       0     0     0
    B2      ONLINE       0     0     0
```

errors: No known data errors

  pool: tank5
 state: ONLINE
  scan: scrub repaired 0 in 13h19m with 0 errors on Sun Jan 10 14:19:24 2016
config:

```
NAME        STATE     READ WRITE CKSUM
tank5       ONLINE       0     0     0
  raidz1-0  ONLINE       0     0     0
    B1      ONLINE       0     0     0
    B0      ONLINE       0     0     0
    B7      ONLINE       0     0     0
    B6      ONLINE       0     0     0
    B5      ONLINE       0     0     0
    B4      ONLINE       0     0     0
```

errors: No known data errors

**Comment by kernelOfTruth** [comment]
referencing https://github.com/zfsonlinux/zfs/pull/4207 Illumos #4950 files sometimes can't be removed from a full filesystem

**Comment by behlendorf** [comment]
Closing, this issue was resolved in the release.
