### ISSUE TITLE
Illumos #6370 ZFS send fails to transmit some holes

### ISSUE THREAD

**Issue by kernelOfTruth** [zfsonlinux/zfs#4230]
Description

In certain circumstances, "zfs send -i" (incremental send) can produce a stream which will result in incorrect sparse file contents on the target.

The problem manifests as regions of the received file that should be sparse (and read a zero-filled) actually contain data from a file that was deleted (and which happened to share this file's object ID).

Note: this can happen only with filesystems (not zvols, because they do not free (or reuse) object IDs).

Note: This can happen only if, since the incremental source (FromSnap), a file was deleted and then another file was created, and the new file is sparse (i.e. has areas that were never written to and should be implicitly zero-filled).

We suspect that this was introduced by 4370 (applies only if hole_birth feature is enabled), and made worse by 5243 (applies if hole_birth feature is disabled, and we never send any holes).

The bug is caused by the hole birth feature. When an object is deleted and replaced, all the holes in the object have birth time zero. However, zfs send cannot tell that the holes are new since the file was replaced, so it doesn't send them in an incremental. As a result, you can end up with invalid data when you receive incremental send streams. As a short-term fix, we can always send holes with birth time 0 (unless it's a zvol or a dataset where we can guarantee that no objects have been reused).

https://www.illumos.org/issues/6370

https://github.com/openzfsonosx/zfs/commit/dbdf5102a7d1745ab991e36709d0392a83bd9b81

references: 

https://www.illumos.org/issues/4370 avoid transmitting holes during zfs send
https://www.illumos.org/issues/5243 zdb -b could be much faster

**Comment by eborisch** [comment]
Duplicate issue #4050.

**Comment by kernelOfTruth** [comment]
@eborisch thanks !

this was thought as a reminder

Closing.
