### ISSUE TITLE
NixOS kernel 4.4 - zfs build fialed

### ISSUE THREAD

**Issue by otwieracz** [zfsonlinux/zfs#4240]
Attaching ``$ nixos-rebuild switch`` log. Shouldn't be Nix-related. Everything worked fine with 4.3 kernel.

``
boot.kernelPackages = pkgs.linuxPackages_4_4;
``

[$ nixos-rebuild switch output](https://github.com/zfsonlinux/zfs/files/94900/log.txt)

**Comment by clefru** [comment]
I'm not familiar with the error, but I just happened to notice that zfs-0.6.5.4 brings compat fixes for 4.4. See https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.6.5.4

**Comment by behlendorf** [comment]
Specifically this was addressed by commit 1a093716788a08b5d038c49ab99a6e9363c97a64 was is part of 0.6.5.4.  The kernel moves fast and we do out best to keep up.
