### ISSUE TITLE
zpl_lookup creates dnode ops based on HAVE_S_D_OP but that seems not to be good enough for some releases of Linux

### ISSUE THREAD

**Issue by RichardSharpe** [zfsonlinux/zfs#4242]
Hi,

In zpl_lookup we have:
```
#ifndef HAVE_S_D_OP
        d_set_d_op(dentry, &zpl_dentry_operations);
#endif /* HAVE_S_D_OP */
```

And I have modified it to:
```
#ifndef HAVE_S_D_OP
        /* If case insensitive, add correct dentry ops */
        printk(KERN_WARNING "%s: Adding dentry ops (ci == %d)!\n",
                __func__, (ppn != NULL));
        if (ppn)
                d_set_d_op(dentry, &zpl_ci_dentry_operations);
        else
                d_set_d_op(dentry, &zpl_dentry_operations);
#endif /* HAVE_S_D_OP */
```

However on Linux 3.10.0-229-xyz (as shipped with Centos 7.x ...) this simply does not work, since I do not get the printk.

Looks like we need a different test. HAVE_S_D_OP relates to superblock ops, not dentry ops, it seems, at least in the version I mentioned.

**Comment by tuxoko** [comment]
We don't need a new set of d_op.
The only different is in lookup, unlink, and rmdir. And they are all trivial.

**Comment by RichardSharpe** [comment]
@tuxoko 

Well, I have to yield to your superior knowledge, I guess.

However, fs/namei.c:vfs_unlink calls dir->i_ops->unlink(dir, dentry) and then calls d_delete(dentry) and d_delete is going to create a negative entry unless we implement a d_iput entry that does different things.

Regards,
Richard Sharpe
(何以解憂？唯有杜康。--曹操)

**Comment by RichardSharpe** [comment]
Hmmm,

shouldn't:
```
#ifndef HAVE_S_D_OP
```

be:

```
#ifdef HAV_D_SET_D_OP
```

**Comment by behlendorf** [comment]
@RichardSharpe perhaps a comment should have been added there, but you can find the rational in the commit history ee93035378ff1f0769bb4216dc35057a2f14f9b9.

```
    Use sb->s_d_op default dentry operations
    
    As of Linux 2.6.37 the right way to register custom dentry
    operations is to use the super block's ->s_d_op field.
    For older kernels they should be registered as part of the
    lookup operation.
```

**Comment by RichardSharpe** [comment]
Ahhh, I should have looked more closely.

**Comment by RichardSharpe** [comment]
OK, I see what to do.

**Comment by RichardSharpe** [comment]
I think I can close this now.
