### ISSUE TITLE
raidz2 writes more than expected to disk

### ISSUE THREAD

**Issue by hhhappe** [zfsonlinux/zfs#4253]
I discovered that a lot more is written to disks compared to what is written to the fs. Obviously, the parity overhead has to be there, but this is even more.

This simple dd procedure can trigger it on a new fs:

dd of=/test/t1 if=/dev/zero bs=1M count=10000 conv=fsync

The first one writes the expected 10k MB and a bit extra for metadata to disks (parity excluded).

Now, deleting the file and writing it again, will write 14k MB.

This was tested on 0.6.5.3 with 4TB SAS rust drives. A quick test has shown that it also happens on 0.6.5.4 and 0.6.4.1.

OS: CentOS 6.7

**Comment by richardelling** [comment]
For space efficiency, the recordsize relative to the drive's physical block size and raidz2 layout is critically important. Rather than explaining here, see http://blog.delphix.com/matt/2014/06/06/zfs-stripe-width/

If you are interested in digging into the details, there are ways to observe the details behind Matt's post (note to self: blog these techniques)

**Comment by hhhappe** [comment]
This does not have to do with layout, which BTW is 10 disks with recordsize=128k.

It is the actual bytes written to the disks measured with iostat. The first write of the file is doing it within reason, but the second is writing 40% more. Perhaps it is a cleanup thing, but that seems excessive. I have also considered if it could be other be other SCSI command which iostat registers as writes. Maybe UNMAPs?

**Comment by hhhappe** [comment]
Doing a bit of blktracing i cannot find anything other than normal writes.

I'm not sure if I'm missing something, but a 4GB write overhead (excluding parity) when writing a 10GB file, kind of makes ZFS useless for write bound stuff.
