### ISSUE TITLE
Zpool folders empty

### ISSUE THREAD

**Issue by kbrdaemon** [zfsonlinux/zfs#4273]
After i upgraded to zfs 0.6.5.3-r3 I got the problem that one of my pools only showed the top level of the folder tree and they were all empty.

The pool imports without any errors. 
Running zfs on Gentoo with Kernel 4.3.4 

If you need any further information please let me know.

**Comment by janlam7** [comment]
Does the newer gentoo release fix this problem for you ?

**Comment by loli10K** [comment]
Closing as stale.
