### ISSUE TITLE
zfs send -i transferres too much data!?

### ISSUE THREAD

**Issue by 1stone** [zfsonlinux/zfs#4274]
I'm replicating a ZFS volume (here tank/backuppc) do a remote server.
To do this, daily snapshots are created and send incrementally (e.g. `zfs send -i tank/backuppc@zrep_000025 tank/backuppc@zrep_000026`)

~~~
root@backup:~# zfs list -t all
NAME                               USED  AVAIL  REFER  MOUNTPOINT
tank                              6.09T  13.9T   205K  /tank
tank/backuppc                     4.25T  13.9T  4.09T  /tank/backuppc
tank/backuppc@zrep_000021          105M      -  3.96T  -
tank/backuppc@zrep_000022         64.4M      -  3.96T  -
tank/backuppc@zrep_000023             0      -  3.94T  -
tank/backuppc@zrep_000024             0      -  3.94T  -
tank/backuppc@zrep_000025             0      -  3.94T  -
tank/backuppc@zrep_000026             0      -  4.09T  -
~~~

While this is working ok - basically - I was puzzled by the amount of data that is transferred with each run.
For the above example, this was roughly 200G (and it's more-or-less the same each day), while the *USED* column in the volume list doesn't show any significant usages between the snapshots that would justify that amount of data.
This looks like a bug - or I'm missing something there...

~~~
# zfs send -v -i tank/backuppc@zrep_000025 tank/backuppc@zrep_000026 | dd of=/dev/null bs=1M |tee /tmp/log
send from @zrep_000025 to tank/backuppc@zrep_000026 estimated size is 195G
total estimated size is 195G
TIME        SENT   SNAPSHOT
09:54:09   26.5M   tank/backuppc@zrep_000026
09:54:10   44.6M   tank/backuppc@zrep_000026
09:54:11    259M   tank/backuppc@zrep_000026
...
10:05:14    198G   tank/backuppc@zrep_000026
10:05:15    198G   tank/backuppc@zrep_000026
0+19439932 records in
0+19439932 records out
212726045376 bytes (213 GB) copied, 668.191 s, 318 MB/s
~~~

**Comment by 1stone** [comment]
That is with `zfs 0.6.5.2-2` on `Linux backup 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt17-1 (2015-09-26) x86_64 GNU/Linux`.

**Comment by richardelling** [comment]
Is compression enabled? The send stream is decompressed.

**Comment by 1stone** [comment]
Well, yes. Compression is enabled and I'm aware of the fact that the stream is (unfortunately) uncompressed. Currently *compressratio* is 1.31x.

However, considering the list above, I don't understand how the snapshot difference going from `zrep_0025` to `zrep_0026` does account for 200GB when the USED column shows `0`.

**Comment by ColdCanuck** [comment]
The Used column from zrep_0025 to zrep_0025 says nothing was deleted;  but the refer column says some 150GB were added (4.09T - 3.94T), so sending 200 GB isn't that far off the mark.

**Comment by richardelling** [comment]
Used for snapshots is the space that is unique to the snapshot. It is expected to change as you delete data in the future.

**Comment by richardelling** [comment]
Also, zstreamdump shows what is in the stream, if you want to look at the details.

**Comment by 1stone** [comment]
Hmm... so this is then more a misunderstanding of the USED column on my side...!?
From what the manual says, I would have expected that this value shows the amount of data the snapshot differs in total (so including added and deleted data).

    used

        ...
        When snapshots (see the "Snapshots" section) are created, their space is initially shared between the snapshot and the file system, and possibly with  previ‐
        ous  snapshots.  As the file system changes, space that was previously shared becomes unique to the snapshot, and counted in the snapshot's space used. Addi‐
        tionally, deleting snapshots can increase the amount of space unique to (and used by) other snapshots.
        ...

Regardless of this definition and possible display, I would love to find out, what actually changed between the snapshots.
The hint with using `zstreamdump` was interesting and helpful. Unfortunately, it's very low-level and far from a list of files - but that may be quite difficult on the block (?) level of the zfs stream...!?

**Comment by ColdCanuck** [comment]
consider a simple filesystem:
day one:  Snap S1 contains files A,B, C Used shows 0 because the files are still in the current fs and snapshot (i.e. nothing is unique to S1)

day two: file D is added. Snap S2 Used shows 0 because A,B,C are in S1 and S2;  D is inhe current fs and S2

day three:  B is deleted. Snap S3 Used shows 0 because A, C, and D are in two Snaps plus the file system; B is in Snap S1 and S2



I believe zfs diff will help

      zfs diff [-FHt] snapshot snapshot|filesystem

           Display the difference between a snapshot of a given filesystem and another snapshot of that filesystem from a later time or the current contents of the filesystem.   The
           first  column  is  a  character indicating the type of change, the other columns indicate pathname, new pathname (in case of rename), change in link count, and optionally
           file type and/or change time.

**Comment by 1stone** [comment]
Thanks for the hints and insights.
