### ISSUE TITLE
Implement a receive / send buffer on zfs send | zfs receive

### ISSUE THREAD

**Issue by RubenKelevra** [zfsonlinux/zfs#4281]
I found this article, which shows an issue on zfs send | zfs receive.

http://everycity.co.uk/alasdair/2010/07/using-mbuffer-to-speed-up-slow-zfs-send-zfs-receive/

This is especially an issue when receiving over a slow network, like dsl. First at all, when the disks are able to receive they got to less data and when they stall no data is transferred at all.

Secondly I use a tcp session to transfer the data over ssh, so I think the issue is increased because the tcp is constantly running it's slow start to avoid congestion, with bursty data transfers the bandwidth ist further wasted.

With mbuffer with 1 GB size on both sending systems and 2x 1 GB on receiving side I reduced my backup-time massively because my dsl is now constantly filled up with data.

So it would be nice if it's possible to implement a similar function in zfs send | zfs receive. A progress graph would be also nice, as optional feature.

**Comment by kernelOfTruth** [comment]
referencing: https://github.com/zfsonlinux/zfs/issues/1161 Implement zfs recv buffer

**Comment by ryao** [comment]
@RubenKelevra As @kernelOfTruth, this has already been implemented. It just is not configurable via the commandline tool and instead opts to use the value of `/proc/sys/fs/pipe-max-size`.

https://github.com/zfsonlinux/zfs/commit/5c3f61eb498e8124858b1369096bf64b86a938e7

**Comment by RubenKelevra** [comment]
I'm still importing from one machine while importing several hundert snapshots as diff (via send -I a@1 a@800 ). On the second import the import just stall several dozend seconds, than he imports the full buffer and stall again after some seconds ... 

The 6 disks are only avg 6% busy... the z_wr_iss processes seem to block here ... what are the purpose of these processes?

**Comment by ryao** [comment]
They issue write IOs to disk.

**Comment by RubenKelevra** [comment]
I use dedup and gzip-9 compression, but sometimes the receive stalls completely and use 3 of 4 cores completely without issuing much IOs to disk. How may I debug this for you?

**Comment by RubenKelevra** [comment]
My issue seem to be the same at this:

https://serverfault.com/questions/507587/zfs-send-i-receive-stalling

**Comment by CMCDragonkai** [comment]
So is mbuffer still needed at all with all the latest changes to send and receive?

**Comment by DeHackEd** [comment]
`mbuffer` can still help dramatically as the default buffer size on Linux is still on the order of kilobytes and the receive process can read intermittently and in bursts as it flushes data and reads needed metadata while it runs.

The question is, is this feature worthwhile enough to make it part of send/recv directly? I gave my opinion in the other issues.

**Comment by CMCDragonkai** [comment]
In that case, does it help only on the receive side or on both send and receive?

**Comment by DeHackEd** [comment]
While it helps either side, if you could only have one side implement the buffer or have the larger buffer then the right choice is the receiver.

**Comment by tuxoko** [comment]
If you use current master. It does use `bqueue` as send/recv buffer. Though the size seems to be hardcoded, so you need to recompile if you want to adjust it.

**Comment by mailinglists35** [comment]
> I use dedup and gzip-9 compression

switch to lz4. I had an old dataset using gz9 and I wend crazy trying to find out why is my cpu burning on receive. switched to lz4 and transfer went back to expected speed.

**Comment by dioni21** [comment]
Old open issue.  Let me leave my opinion:

I think zfs send/recv should have a minimum buffer.  Enough for most critical operations, but not more than that.  Maybe something like **block size (128k?) times number of simultaneous physical I/O** permitted on the pool in question.  Maybe, also, this same sized buffer on **both sides**, send and recv.

Obviously more buffer may mean more performance, but Unix Philosophy is to create small programs to do small things, and pipe them through.  So, IFF the user wants, let the user add mbuffer or whatever to his pipe.
