### ISSUE TITLE
Best way to monitor actual pool usage (in terms of bandwidth -- i.e. mb/s) at a set interval?

### ISSUE THREAD

**Issue by DeviantEng** [zfsonlinux/zfs#4284]
Hi all.  

I'm running ZoL on a Debian box with 10 5TB drives in a RAID10 setup.  I'm looking for a way to pull bandwidth usage at a set time, and send that data to Splunk.  Basically, I want to run a script every 30 seconds(maybe more, maybe less) that shows the mbps of reads and writes, from the pool.  I don't particularly care about how much reads come from arc vs direct from disk, but overall disk performance (so I can graph over time).  

I've been playing with `zpool iostat`, and as I understand it shows an average  of performance over a time period.  For example, just running `zpool iostat` shows the average since system boot, where as `zpool iostat 30` will show values every 30 seconds, averaging the stats for the previous 30 seconds.  Do I understand this correctly?  Example values I'm seeing are like `26.1M` which I assume is `26.1 Megabytes per second`, yes?

Also, I have come across `/proc/spl/kstat/zfs/<pool_name>/io`, which shows several numbers, in what I assume are bytes.  Fields listed are `nread, nwritten, reads, writes, wtime, wlentime, wupdate, rtime, rlentime, rupdate, wcnt, rcnt`.  Can someone elaborate on what these are for, and how to read them?  How is this data written to this file and at what interval?  Is it current time, or averaged numbers?

So between these two options, which would be better to use?  Is there something else I could use instead that would be better (included with ZFSonLinux, or could be installed and used via script(s) )?

If you are unclear of my overall goal, please let me know and I will try to clarify further.

Thanks!

**Comment by DeviantEng** [comment]
Anyone?

**Comment by kernelOfTruth** [comment]
``` zpool iostat -v 1 ```

and

https://www.reddit.com/r/zfs/comments/436axr/monitoring_zfs_performance_long_term/

**Comment by colttt** [comment]
21month later and there is still no documentation about  `nread, nwritten, reads, writes, wtime, wlentime, wupdate, rtime, rlentime, rupdate, wcnt, rcnt` and the difference (eg nwritten and written). Also the reddit comments are not very helpfull. can someone explain the fields?

**Comment by richardelling** [comment]
This issue is closed. However, for posterity...

UTSL, https://github.com/zfsonlinux/zfs/blob/master/lib/libspl/include/sys/kstat.h#L580
If you search further with keyword "solaris" you'll find quite a bit of info on how kstat_io types work.

Specificially for ZFSonLinux, the kstat_io is at the interface of the pool:devices. It represents neither the VFS nor zvol interface. For the VFS layer, Linux does not seem to have builtin metrics. For the zvol interface, metrics are available as per other block devices, eg iostat, /proc/diskstats

If you notice rlentime == wlentime, then apply SPL commit e8474f9ad3b3d23c3277535c4f53f8fd1e6cbd74

**Comment by behlendorf** [comment]
For the VFS layer Linux doesn't provide aggregate counters but there are standard tracepoints for this purpose.  https://www.kernel.org/doc/Documentation/trace/tracepoint-analysis.txt

**Comment by tonyhutter** [comment]
@DeviantEng we've also been logging zpool iostat values to splunk.  Consider using the `-y` (don't show initial summary screen), `-p` (raw values), and `-H` (no headings) flags to make it easier to parse into a syslog line:

```zpool iostat -vlqpHy 10 1 | awk '{print "vdev="$1" allocated="$2" free="$3" reads="$4" ... ```

I'd recommend a 10sec sample time for accurate values.

**Comment by DeviantEng** [comment]
@tonyhutter I assume you're not running under ZoL because `-H`, `-p`, and `-q` aren't valid options for iostat on my ZOL build.  

I'm currently running build `0.6.5.9-pve15-bpo80`, which comes with Proxmox `4.4-96`.

**Comment by gmelikov** [comment]
@DeviantEng they are valid in ZoL 0.7+ version.

**Comment by DeviantEng** [comment]
@gmelikov Looks like I'll be upgrading today.  :)

Thanks!

**Comment by richardelling** [comment]
FWIW, telegraf plugin for linux optionally collects the pool's io stats (/proc/spl/kstat/zfs/POOLNAME/io) and can push them out to a wide variety of metrics collectors. Good stuff.

https://github.com/influxdata/telegraf
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/zfs

**Comment by Sudhar287** [comment]
Can anyone please provide some explanation/links to understand the workings of `/proc/spl/kstat/zfs/ZPOOL NAME/objset-*` such as `writes, nwritten, reads, nread`? :)
I wrote/read some files in the ZFS pool that I created and there was no change in the numbers in the objset-*. Why is that?
