### ISSUE TITLE
zfs recv parameter x not working

### ISSUE THREAD

**Issue by chani** [zfsonlinux/zfs#4285]
The oracle page states 

> If you have a local file system property value in a snapshot stream and you want to disable the property when it is received, use the zfs receive -x command. For example, the following command sends a recursive snapshot stream of home directory file systems with all file system properties reserved to a backup pool, but without the quota property values:
[Source](http://docs.oracle.com/cd/E23823_01/html/819-5461/gbchx.html)

Actually it seems that -x is not working as expected / just ignored. If I do:

destination system:
`zfs set com.sun:auto-snapshot=false pool/backups`

source system:
```
zfs snapshot -r pool@backup
zfs send -R pool@backup | ssh destination-system 'zfs recv -x com.sun:auto-snapshot -o readonly=on pool/backups/foobar'
```

then I can see on the destination system using zfs get that the property readonly has been set to "on" (that means -o is working) but the property com.sun:auto-snapshot is still set to "true" which means that -x did not unset it as it should (which then should have lead to foobar inheriting the property from the parent where it is set to false)

Am I misinterpreting -x or has -x not been implemented as of now?

Then a question someone might possibly answer and I've been unable to find anything about using my favorite search engine.. Is it possible to see if a dataset has been received vs locally created? Some flag which is set and could be checked?

**Comment by kernelOfTruth** [comment]
referencing:

https://github.com/zfsonlinux/zfs/issues/1050 Request for '-x' option to 'zfs receive'.
https://github.com/zfsonlinux/zfs/issues/1350 zfs receive does neither support -o property=value nor -x property

**Comment by chani** [comment]
Ah. Sorry. I haven't seen #1050. This one can be closed then, I guess.
