### ISSUE TITLE
Sudden write() + fsync() performance drop

### ISSUE THREAD

**Issue by michaelxwang** [zfsonlinux/zfs#4305]
Sudden write() + fsync() performance drop

I am experiencing a "sudden" drop in fsync() performance. Here "sudden" is 
defined as a big change in the performance in one day or two without any
hardware and software change, but just through the usage. Here is an example:

Yesterday, I performed a test as shown below which repetitively writes 4K blocks
followed a fsync():

```
sysbench --test=fileio            \
         --file-num=1             \
         --file-total-size=50G    \
         --file-fsync-all=on      \
         --file-test-mode=seqrewr \
         --max-time=100           \
         --file-block-size=4096   \
         --max-requests=0         \
         run
```

and got a result:

```
Operations performed:  0 reads, 189250 writes, 189250 Other = 378500 Total
Read 0b  Written 739.26Mb  Total transferred 739.26Mb  (7.3925Mb/sec)
 1892.47 Requests/sec executed
```

through the "normal" use overnight, the server is so slow in write() that it
is not usable. The same test today gives a result:

```
Operations performed:  0 reads, 52629 writes, 52629 Other = 105258 Total
Read 0b  Written 205.58Mb  Total transferred 205.58Mb  (2.0241Mb/sec)
  518.17 Requests/sec executed
```

It becomes 3.6x worse.

This server is a MySQL replica, which applies the changes from the primary.
The only thing that is "usual" is we had a large number of deletes from a table.

Empirically we discovered that if we rebuild the zpool, and restore the
files, then the same test will perform best. We have an identical server
which serves the same purpose except with the zpool rebuilt and files
restored via rsync/cp. The same fsync() test shows:

```
Operations performed:  0 reads, 373516 writes, 373516 Other = 747032 Total
Read 0b  Written 1.4249Gb  Total transferred 1.4249Gb  (14.518Mb/sec)
 3716.55 Requests/sec executed
```

From the worst to the best, the difference is 7.1x.

This tells us there is something wrong with the pool. But exactly what and how
can I get the performance to normal easier than going through the time consuming
process of the creating pool and restoring process?

List below is the zfs/zpool properties of the "good" and "bad" servers.

The good:

```
root@mdb-01-p-05:~# zpool list

NAME     SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
local0  5.81T  5.23T   592G         -    86%    90%  1.00x  ONLINE  -

root@mdb-01-p-05:~# zfs list

NAME                         USED  AVAIL  REFER  MOUNTPOINT
local0                      5.23T   406G    96K  /local0
local0/mysqlbin              288K   406G    96K  /srv/mysqlbin
local0/mysqlbin/binlog        96K   406G    96K  /srv/mysqlbin/binlog
local0/mysqlbin/relaylog      96K   406G    96K  /srv/mysqlbin/relaylog
local0/mysqldata            5.23T   406G    96K  /srv/mysqldata
local0/mysqldata/binlog      108G   406G   108G  /srv/mysqldata/binlog
local0/mysqldata/data       5.11T   406G  5.11T  /srv/mysqldata/data
local0/mysqldata/innodblog  16.0G   406G  16.0G  /srv/mysqldata/innodblog
local0/mysqldata/relaylog   62.8M   406G  62.8M  /srv/mysqldata/relaylog
local0/mysqllog              540M   406G    96K  /srv/mysqllog
local0/mysqllog/log          540M   406G   540M  /srv/mysqllog/log
local0/mysqltemp             992K   406G    96K  /srv/mysqltemp
local0/mysqltemp/tmp         896K   406G   896K  /srv/mysqltemp/tmp

root@mdb-01-p-05:~# zfs get all | grep -E '^local0/mysqldata/data.*(sync|recordsize|compress)'

local0/mysqldata/data       compressratio         1.81x                     -
local0/mysqldata/data       recordsize            128K                      local
local0/mysqldata/data       compression           lz4                       local
local0/mysqldata/data       sync                  standard                  default
local0/mysqldata/data       refcompressratio      1.81x                     -

root@mdb-01-p-05:~# zpool iostat 3 30

               capacity     operations    bandwidth
pool        alloc   free   read  write   read  write
----------  -----  -----  -----  -----  -----  -----
local0      5.23T   592G  1.40K  3.70K  21.6M  47.3M
local0      5.23T   592G    334  6.25K  4.73M  61.0M
local0      5.23T   592G    394  4.46K  7.28M  43.3M
local0      5.23T   592G    805  5.19K  10.7M  50.5M
local0      5.23T   592G  1.72K  5.89K  22.8M  52.5M
local0      5.23T   592G    616  5.31K  9.11M  50.1M
local0      5.23T   592G    397  5.72K  6.92M  50.3M
local0      5.23T   592G    565  5.58K  9.44M  50.0M
local0      5.23T   592G    616  7.91K  12.5M  70.4M
local0      5.23T   592G    519  8.56K  7.77M  74.1M
local0      5.23T   592G    344  3.05K  5.15M  25.0M
local0      5.23T   592G    296  2.67K  5.14M  25.1M
local0      5.23T   592G    673  6.04K  8.00M  52.3M
local0      5.23T   592G    333  3.26K  5.10M  30.5M
local0      5.23T   592G    644  5.99K  7.11M  52.4M
local0      5.23T   592G    233  5.86K  5.08M  52.2M
local0      5.23T   592G    329  5.29K  6.14M  48.5M
local0      5.23T   592G    567  5.05K  12.4M  47.7M
local0      5.23T   592G    557  6.10K  8.05M  56.5M
local0      5.23T   592G    694  11.4K  8.69M   101M
local0      5.23T   592G    318  2.92K  4.58M  25.0M
local0      5.23T   592G   1010  2.50K  13.5M  24.9M
local0      5.23T   592G    390  6.06K  6.23M  53.5M
local0      5.23T   592G    373  3.51K  6.82M  34.1M
local0      5.23T   592G    297  8.23K  4.74M  71.4M
local0      5.23T   592G  1.18K  2.83K  15.2M  27.2M
local0      5.23T   592G    277  3.12K  4.87M  27.6M
local0      5.23T   592G    572  8.69K  11.4M  75.7M
local0      5.23T   592G    277  2.78K  4.33M  26.9M
local0      5.23T   592G    532  5.93K  7.39M  53.5M
```

The bad:

```
[root@mdb-01-p-07:/root] # zpool list

NAME     SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
local0  5.81T  4.68T  1.14T         -    86%    80%  1.00x  ONLINE  -

[root@mdb-01-p-07:/root] # zfs list

NAME                         USED  AVAIL  REFER  MOUNTPOINT
local0                      4.68T   977G    19K  /local0
local0/mysqlbin               58K   977G    19K  /srv/mysqlbin
local0/mysqlbin/binlog        20K   977G    20K  /srv/mysqlbin/binlog
local0/mysqlbin/relaylog      19K   977G    19K  /srv/mysqlbin/relaylog
local0/mysqldata            4.67T   977G    19K  /srv/mysqldata
local0/mysqldata/binlog      275G   977G   275G  /srv/mysqldata/binlog
local0/mysqldata/data       4.39T   977G  4.39T  /srv/mysqldata/data
local0/mysqldata/innodblog  16.4G   977G  16.4G  /srv/mysqldata/innodblog
local0/mysqldata/relaylog   2.40G   977G  2.40G  /srv/mysqldata/relaylog
local0/mysqllog              542M   977G    19K  /srv/mysqllog
local0/mysqllog/log          542M   977G   542M  /srv/mysqllog/log
local0/mysqltemp              45K   977G    19K  /srv/mysqltemp
local0/mysqltemp/tmp          26K   977G    26K  /srv/mysqltemp/tmp

[root@mdb-01-p-07:/root] # zfs get all | grep -E '^local0/mysqldata/data.*(sync|recordsize|compress)'

local0/mysqldata/data       compressratio         2.25x                     -
local0/mysqldata/data       recordsize            16K                       local
local0/mysqldata/data       compression           lz4                       local
local0/mysqldata/data       sync                  standard                  default
local0/mysqldata/data       refcompressratio      2.25x                     -

[root@mdb-01-p-07:/root] # zpool iostat 3 30
               capacity     operations    bandwidth
pool        alloc   free   read  write   read  write
----------  -----  -----  -----  -----  -----  -----
local0      4.68T  1.14T     98  2.98K  1.37M  18.2M
local0      4.68T  1.14T    326  5.17K  5.02M  29.8M
local0      4.68T  1.14T    327  3.90K  6.65M  20.1M
local0      4.68T  1.14T    310  4.32K  4.80M  23.7M
local0      4.68T  1.14T    219  2.92K  4.20M  21.0M
local0      4.68T  1.14T    143  3.41K  3.00M  15.4M
local0      4.68T  1.14T    193  4.99K  3.66M  29.3M
local0      4.68T  1.14T    257  5.51K  7.39M  33.1M
local0      4.68T  1.14T    217  6.57K  4.69M  42.1M
local0      4.68T  1.14T    339  4.96K  6.21M  26.6M
local0      4.68T  1.14T    190  4.73K  3.39M  24.7M
local0      4.68T  1.14T    551  7.39K  11.5M  43.2M
local0      4.68T  1.14T     12  3.48K   537K  14.5M
local0      4.68T  1.14T    266  5.00K  4.18M  26.7M
local0      4.68T  1.14T    425  5.88K  8.40M  35.2M
local0      4.68T  1.14T     39  6.74K   777K  40.2M
local0      4.68T  1.14T    314  1.38K  5.88M  11.2M
local0      4.68T  1.14T    127  3.07K  2.21M  14.8M
local0      4.68T  1.14T    389  4.36K  7.23M  23.5M
local0      4.68T  1.14T    167  4.68K  2.96M  24.2M
local0      4.68T  1.14T    358  6.03K  5.79M  33.8M
local0      4.68T  1.14T    256  5.78K  3.61M  34.1M
local0      4.68T  1.14T    409  4.51K  6.66M  24.5M
local0      4.68T  1.14T    110    231  2.42M  1.99M *
local0      4.68T  1.14T    144  5.34K  3.02M  26.0M
local0      4.68T  1.14T    337  5.18K  7.55M  29.1M
local0      4.68T  1.14T    218  7.04K  3.67M  38.0M
local0      4.68T  1.14T     46  5.99K   841K  34.7M
local0      4.68T  1.14T     91    828  1.79M  4.66M *
local0      4.68T  1.14T    238  3.76K  5.23M  20.1M
```

NB: The "bad" server used to have 128K recordsize that is why it has better
compression ratio and more free space. The "good" server had 16K recordsize
on the volume from start when we rebuilt the server. 

The zpool iostat on the "bad" server not only has low write output, but
always has dips as I indicated by the "*".

Thank you for reading this far. If you need more information, please let
me know and I will be happy to provide.

**Comment by ryao** [comment]
Files created when recordsize=128K was set are still using that recordsize. That might explain this.

**Comment by michaelxwang** [comment]
Clarification: The "bad" servers were built and used with 128K record size for most of its life, and dynamically changed to 16K because 16K matches the average size of mysql writes, and had been "good" for a few months before it became "bad". The "good" server was built and restored with 16K record size, and after running for a few days changed to 128K for space conservation and it remains "good". That is why the good server was shown 128K in the output provided above.

I have also "good" server built and used for its entire life with 128K record size, and it is performing well. 

This shows there is no direct relationship between fsync() result and record size.

The only thing that matters that I can tell is the process of recreation of the pool after warming up the disks [writing /dev/zero to all the drives]:

http://hatim.eu/2014/05/24/leveraging-ssd-ephemeral-disks-in-ec2-part-1/

and the restore the database. However, I am not sure what changed in the process. I would like to believe it is the defragmentation, but as you can tell from my posting above, the "good" and "bad" servers have the same FRAG metric which is 86%. Either defragmentation is not the reason, or the FRAG number is not a good measure of fragmentation. 

ALSO, the fsync() result can change. After one day, the fsync() may becomes bad or return to normal, and the fsync() result is directly related to the mysql performance as it makes frequent fsync() calls. Disable sync on the pool helps the application performance.

All I am writing seems to be a fiction, but the observation is REAL. I just do not know where the phantom is, and how to catch it. All I know is after recreating the pool and restoring the data [with OS cp or rsync command], the phantom goes away. Cc: @ryao .

**Comment by kernelOfTruth** [comment]
@michaelxwang the fragmentation provided in

``` zpool list ``` 

is only the provided **average** of all the metaslabs,

via 

``` zdb -m -v pool ```

you can look up the fragmentation of the individual metaslabs, that should surely differ between those servers and could partly explain a performance drop if in a certain area the fragmentation is very high where data has to be written

**Comment by michaelxwang** [comment]
@kernelOfTruth Thank you for providing the `zdb -m -v pool` command. I know where the filesystem that the application is writing to, but not the metaslabs. Is there a translation the metaslabs a certain filesystem belong? Thanks.

**Comment by kernelOfTruth** [comment]
@michaelxwang 

>Is there a translation the metaslabs a certain filesystem belong?

You mean the position on the harddrive of the metaslab, which is currently being written to ?
You could look at the stats before and after the write to see if things changed to see which metaslab is affected.

Quickly posting a few links:
http://blog.delphix.com/uday/2013/02/19/78/
http://myverylittletricks.net/code/?page_id=318
https://utcc.utoronto.ca/~cks/space/blog/solaris/ZFSZpoolFragmentationDetails
https://blogs.oracle.com/bonwick/en/entry/zfs_block_allocation
