### ISSUE TITLE
Unbalanced disk use and disk free space

### ISSUE THREAD

**Issue by michaelxwang** [zfsonlinux/zfs#4310]
I have seen from "zpool iostat -v" out unbalanced disk usage:

```
               capacity     operations    bandwidth
pool        alloc   free   read  write   read  write
----------  -----  -----  -----  -----  -----  -----
  xvdf       661G  83.2G    323    438  3.26M  5.91M   First entry
  xvdg       737G  7.43G *  335    590  3.39M  7.62M * of output
  xvdh       659G  85.0G    321    425  3.24M  5.78M   abbreviated
```

where disk xvdg has been used more heavily and has less space
left on it. However on next day, I see:

```
               capacity     operations    bandwidth
pool        alloc   free   read  write   read  write
----------  -----  -----  -----  -----  -----  -----
  xvdf       669G  75.4G    311    417  3.21M  5.41M   First entry
  xvdg       706G  37.8G *  344    560  3.74M  6.89M * of output
  xvdh       667G  77.1G    309    406  3.19M  5.31M   abbreviated
```

i.e. the usage on disk xvdg has been reduced towards a more
balanced disk use, and free space has grown 30+ GB! It is not
that I have removed files on disk xvdg, but the free space on
all other disks are reduced. This means the zfs system has moved
data from disk xvdg to other disks.

I would like to get a confirmation that the zfs indeed reblance
the disk space and disk use due to previous unbalanced disk use
which is nice, but the unbalanced disk usage seem to be bug and
that why here I report it. The more detailed output is copied
below.

PS: I created the pool local0 with all these 8 new disks
of equal sizes which are Amazon EC2 local ephemeral SSD disks,
I did not later add or remove disks from the pool.

2016-02-04T16:30:07 [on system P-once]:

```
# zpool iostat -v 3 300
               capacity     operations    bandwidth
pool        alloc   free   read  write   read  write
----------  -----  -----  -----  -----  -----  -----
local0      5.23T   592G  2.54K  3.52K  26.3M  48.7M * First entry
  xvdb       660G  83.7G    321    414  3.24M  5.82M   of output
  xvdc       660G  84.0G    322    423  3.25M  5.82M
  xvdd       662G  81.9G    328    451  3.31M  6.05M
  xvde       661G  83.3G    325    436  3.29M  5.89M
  xvdf       661G  83.2G    323    438  3.26M  5.91M
  xvdg       737G  7.43G *  335    590  3.39M  7.62M *
  xvdh       659G  85.0G    321    425  3.24M  5.78M
  xvdi       661G  83.2G    323    424  3.26M  5.87M
----------  -----  -----  -----  -----  -----  -----

               capacity     operations    bandwidth
pool        alloc   free   read  write   read  write
----------  -----  -----  -----  -----  -----  -----
local0      5.23T   592G  1.89K  3.72K  20.3M  25.9M *
  xvdb       660G  83.7G    201    385  2.14M  2.49M
  xvdc       660G  84.0G    212    397  2.25M  2.61M
  xvdd       662G  81.9G    208    400  2.20M  2.67M
  xvde       661G  83.3G    224    396  2.36M  2.55M
  xvdf       661G  83.2G    200    334  2.09M  2.46M
  xvdg       736G  7.62G *  497  1.10K  5.24M  8.23M *
  xvdh       659G  85.0G    189    384  1.93M  2.46M
  xvdi       661G  83.2G    206    384  2.11M  2.39M
----------  -----  -----  -----  -----  -----  -----

               capacity     operations    bandwidth
pool        alloc   free   read  write   read  write
----------  -----  -----  -----  -----  -----  -----
local0      5.23T   592G  1.73K  2.24K  18.6M  20.8M *
  xvdb       660G  83.7G    171      1  1.77M  5.33K
  xvdc       660G  84.0G    198      0  2.09M      0
  xvdd       662G  81.9G    179      0  1.84M      0
  xvde       661G  83.3G    177      0  1.81M      0
  xvdf       661G  83.2G    190      0  2.01M      0
  xvdg       736G  7.60G *  499  2.24K  5.35M  20.8M *
  xvdh       659G  85.0G    167      1  1.73M  5.33K
  xvdi       661G  83.2G    188      1  1.94M  5.33K
----------  -----  -----  -----  -----  -----  -----

               capacity     operations    bandwidth
pool        alloc   free   read  write   read  write
----------  -----  -----  -----  -----  -----  -----
local0      5.23T   592G  1.58K  5.92K  16.4M  51.5M *
  xvdb       660G  83.7G    178      2  1.80M  10.7K
  xvdc       660G  84.0G    171      2  1.76M  10.7K
  xvdd       662G  81.9G    185      1  1.86M  5.33K
  xvde       661G  83.3G    166      0  1.68M      0
  xvdf       661G  83.2G    164      0  1.65M      0
  xvdg       736G  7.59G *  439  5.91K  4.50M  51.5M *
  xvdh       659G  85.0G    169      0  1.72M      0
  xvdi       661G  83.2G    145      1  1.46M  5.33K
----------  -----  -----  -----  -----  -----  -----

               capacity     operations    bandwidth
pool        alloc   free   read  write   read  write
----------  -----  -----  -----  -----  -----  -----
local0      5.23T   592G  2.25K  5.95K  23.0M  44.4M *
  xvdb       660G  83.7G    251      1  2.44M  5.33K
  xvdc       660G  84.0G    238      1  2.42M  5.33K
  xvdd       662G  81.9G    229      1  2.34M  5.33K
  xvde       661G  83.3G    255      0  2.55M      0
  xvdf       661G  83.2G    260      1  2.56M  5.33K
  xvdg       737G  7.45G *  558  5.95K  5.72M  44.4M *
  xvdh       659G  85.0G    249      1  2.49M  5.33K
  xvdi       661G  83.2G    255      0  2.47M      0
----------  -----  -----  -----  -----  -----  -----
```

2016-02-05T11:03:59 [on system P-once]:

```
# zpool iostat -v 3 30
               capacity     operations    bandwidth
pool        alloc   free   read  write   read  write
----------  -----  -----  -----  -----  -----  -----
local0      5.26T   567G  2.46K  3.35K  26.2M  44.6M * First entry
  xvdb       668G  75.9G    309    395  3.20M  5.34M   of output
  xvdc       668G  76.2G    309    404  3.20M  5.34M
  xvdd       670G  74.2G    315    428  3.26M  5.53M
  xvde       668G  75.6G    313    415  3.23M  5.39M
  xvdf       669G  75.4G    311    417  3.21M  5.41M
  xvdg       706G  37.8G *  344    560  3.74M  6.89M *
  xvdh       667G  77.1G    309    406  3.19M  5.31M
  xvdi       669G  75.3G    311    403  3.22M  5.39M
----------  -----  -----  -----  -----  -----  -----

               capacity     operations    bandwidth
pool        alloc   free   read  write   read  write
----------  -----  -----  -----  -----  -----  -----
local0      5.26T   567G  1.40K    628  14.7M  5.43M *
  xvdb       668G  75.9G    166     77  1.69M   661K
  xvdc       668G  76.2G    158     74  1.58M   620K
  xvdd       670G  74.2G    168     81  1.74M   687K
  xvde       668G  75.6G    158     71  1.63M   891K
  xvdf       669G  75.4G    169     82  1.74M   729K
  xvdg       706G  37.8G *  269     81  2.81M   685K *
  xvdh       667G  77.1G    157     79  1.62M   626K
  xvdi       669G  75.3G    183     78  1.93M   667K
----------  -----  -----  -----  -----  -----  -----

               capacity     operations    bandwidth
pool        alloc   free   read  write   read  write
----------  -----  -----  -----  -----  -----  -----
local0      5.26T   567G  1.58K  1.31K  16.3M  10.5M
  xvdb       668G  75.9G    166    168  1.72M  1.28M
  xvdc       668G  76.2G    180    180  1.79M  1.39M
  xvdd       670G  74.2G    181    165  1.80M  1.29M
  xvde       668G  75.6G    183    112  1.75M  1.31M
  xvdf       669G  75.4G    199    167  1.99M  1.29M
  xvdg       706G  37.8G *  329    190  3.57M  1.29M *
  xvdh       667G  77.1G    191    185  1.90M  1.32M
  xvdi       669G  75.2G    185    173  1.79M  1.34M
----------  -----  -----  -----  -----  -----  -----

               capacity     operations    bandwidth
pool        alloc   free   read  write   read  write
----------  -----  -----  -----  -----  -----  -----
local0      5.26T   567G  1.48K  1.05K  15.8M  8.06M
  xvdb       668G  75.9G    181    138  1.90M  1.03M
  xvdc       668G  76.2G    138    132  1.43M  1.01M
  xvdd       670G  74.2G    175    129  1.81M  1007K
  xvde       668G  75.6G    158    122  1.64M  1.03M
  xvdf       669G  75.4G    175    128  1.82M   973K
  xvdg       706G  37.8G *  339    165  3.64M  1.01M *
  xvdh       667G  77.1G    176    124  1.79M  1.03M
  xvdi       669G  75.2G    166    128  1.72M  1.02M
----------  -----  -----  -----  -----  -----  -----

               capacity     operations    bandwidth
pool        alloc   free   read  write   read  write
----------  -----  -----  -----  -----  -----  -----
local0      5.26T   567G  1.44K  6.25K  15.2M  59.1M
  xvdb       668G  75.9G    151    753  1.57M  7.35M
  xvdc       668G  76.2G    163    761  1.70M  7.28M
  xvdd       670G  74.2G    154    784  1.62M  7.36M
  xvde       668G  75.6G    176    708  1.77M  7.37M
  xvdf       669G  75.4G    183    785  1.85M  7.34M
  xvdg       706G  37.8G *  285    984  3.01M  7.53M *
  xvdh       667G  77.1G    172    844  1.76M  7.40M
  xvdi       669G  75.2G    182    779  1.91M  7.49M
----------  -----  -----  -----  -----  -----  -----
```

**Comment by jfoboss** [comment]
We've experiencing similar behaviour. In our environment we've got extreme disbalance in I/O.
![zraid disbalance](https://cloud.githubusercontent.com/assets/17083746/12847286/46e37d0e-cc23-11e5-99bf-dc40fe6e60ee.png)

`root@storage-d9-10614:/tank/pool_test/brick# zpool status
  pool: tank
 state: ONLINE
  scan: scrub canceled on Fri Feb  5 12:31:39 2016
config:

        NAME                                        STATE     READ WRITE CKSUM
        tank                                        ONLINE       0     0     0
          raidz2-0                                  ONLINE       0     0     0
            scsi-3600605b009077a501e0d17ec92dd8cc1  ONLINE       0     0     0
            scsi-3600605b009077a501e0d1800941575e0  ONLINE       0     0     0
            scsi-3600605b009077a501e0d181595564716  ONLINE       0     0     0
            scsi-3600605b009077a501e0d182b9696def8  ONLINE       0     0     0
            scsi-3600605b009077a501e0d184097d82029  ONLINE       0     0     0
            scsi-3600605b009077a501e0d185599187909  ONLINE       0     0     0
          raidz2-1                                  ONLINE       0     0     0
            scsi-3600605b009077a501e0d186a9a592040  ONLINE       0     0     0
            scsi-3600605b009077a501e0d187f9b9a918b  ONLINE       0     0     0
            scsi-3600605b009077a501e0d18949cda952b  ONLINE       0     0     0
            scsi-3600605b009077a501e0d18a99e1b14e7  ONLINE       0     0     0
            scsi-3600605b009077a501e0d18be9f5b7999  ONLINE       0     0     0
            scsi-3600605b009077a501e0d18d3a09be122  ONLINE       0     0     0

errors: No known data errors


----------------------------------

zpool iostat -v
                                               capacity     operations    bandwidth
pool                                        alloc   free   read  write   read  write
------------------------------------------  -----  -----  -----  -----  -----  -----
tank                                        7.10T  14.6T     77    530  5.28M  14.1M
  raidz2                                    3.55T  7.32T     38    264  2.64M  7.01M
    scsi-3600605b009077a501e0d17ec92dd8cc1      -      -     16     61   576K  1.78M
    scsi-3600605b009077a501e0d1800941575e0      -      -     16     61   587K  1.78M
    scsi-3600605b009077a501e0d181595564716      -      -     16     61   590K  1.78M
    scsi-3600605b009077a501e0d182b9696def8      -      -     16     61   575K  1.78M
    scsi-3600605b009077a501e0d184097d82029      -      -     16     61   587K  1.78M
    scsi-3600605b009077a501e0d185599187909      -      -     16     61   591K  1.78M
  raidz2                                    3.55T  7.32T     38    266  2.64M  7.04M
    scsi-3600605b009077a501e0d186a9a592040      -      -     16     68   580K  1.79M
    scsi-3600605b009077a501e0d187f9b9a918b      -      -     16     68   583K  1.79M
    scsi-3600605b009077a501e0d18949cda952b      -      -     16     68   590K  1.79M
    scsi-3600605b009077a501e0d18a99e1b14e7      -      -     16     68   578K  1.79M
    scsi-3600605b009077a501e0d18be9f5b7999      -      -     16     68   583K  1.79M
    scsi-3600605b009077a501e0d18d3a09be122      -      -     16     68   592K  1.79M
------------------------------------------  -----  -----  -----  -----  -----  -----



----------------------------------


root@storage-d9-10614:/tank/pool_test/brick# zfs get all tank
NAME  PROPERTY              VALUE                  SOURCE
tank  type                  filesystem             -
tank  creation              Thu Dec 24 17:20 2015  -
tank  used                  4.73T                  -
tank  available             9.30T                  -
tank  referenced            32.0K                  -
tank  compressratio         1.68x                  -
tank  mounted               yes                    -
tank  quota                 none                   default
tank  reservation           none                   default
tank  recordsize            128K                   default
tank  mountpoint            /tank                  default
tank  sharenfs              off                    default
tank  checksum              on                     default
tank  compression           lz4                    local
tank  atime                 off                    local
tank  devices               on                     default
tank  exec                  on                     default
tank  setuid                on                     default
tank  readonly              off                    default
tank  zoned                 off                    default
tank  snapdir               hidden                 default
tank  aclinherit            restricted             default
tank  canmount              on                     default
tank  xattr                 on                     default
tank  copies                1                      default
tank  version               5                      -
tank  utf8only              off                    -
tank  normalization         none                   -
tank  casesensitivity       sensitive              -
tank  vscan                 off                    default
tank  nbmand                off                    default
tank  sharesmb              off                    default
tank  refquota              none                   default
tank  refreservation        none                   default
tank  primarycache          all                    default
tank  secondarycache        all                    default
tank  usedbysnapshots       0                      -
tank  usedbydataset         32.0K                  -
tank  usedbychildren        4.73T                  -
tank  usedbyrefreservation  0                      -
tank  logbias               latency                default
tank  dedup                 off                    default
tank  mlslabel              none                   default
tank  sync                  disabled               local
tank  refcompressratio      1.00x                  -
tank  written               32.0K                  -
tank  logicalused           7.93T                  -
tank  logicalreferenced     9.50K                  -
tank  filesystem_limit      none                   default
tank  snapshot_limit        none                   default
tank  filesystem_count      none                   default
tank  snapshot_count        none                   default
tank  snapdev               hidden                 default
tank  acltype               posixacl               local
tank  context               none                   default
tank  fscontext             none                   default
tank  defcontext            none                   default
tank  rootcontext           none                   default
tank  relatime              off                    default
tank  redundant_metadata    all                    default
tank  overlay               off                    default
`
