### ISSUE TITLE
Temporary freeze copying lots of small files

### ISSUE THREAD

**Issue by farnoy** [zfsonlinux/zfs#4320]
I did `$ cp -R a b`,  `a` contains `42978` files at a total size of 4.1G (2.2G on-disk, compressed). The system froze for ~10 seconds, then the copy continued and I could see the system load for the past 5 minutes went up to 22. By removing `b` and trying the copy again I was not able to reproduce the freeze (ARC related?).

```
NAME   PROPERTY              VALUE                  SOURCE
zroot  type                  filesystem             -
zroot  creation              Thu Jan 28 18:05 2016  -
zroot  used                  38.3G                  -
zroot  available             48.4G                  -
zroot  referenced            33.8G                  -
zroot  compressratio         1.61x                  -
zroot  mounted               yes                    -
zroot  mountpoint            /                      local
zroot  compression           on                     local
zroot  atime                 on                     local
zroot  version               5                      -
zroot  utf8only              off                    -
zroot  normalization         none                   -
zroot  casesensitivity       sensitive              -
zroot  usedbysnapshots       0                      -
zroot  usedbydataset         33.8G                  -
zroot  usedbychildren        4.44G                  -
zroot  usedbyrefreservation  0                      -
zroot  refcompressratio      1.64x                  -
zroot  written               33.8G                  -
zroot  logicalused           58.9G                  -
zroot  logicalreferenced     52.5G                  -
zroot  relatime              on                     local
```

Other properties are default.s

**Comment by tuxoko** [comment]
What version are you using?
Do you see anything in dmesg?

Try `echo 3 > /proc/sys/vm/drop_caches` and see if you can reproduce it.

**Comment by farnoy** [comment]
I am using `0.6.5.4-g1ffc4c1` with a `4.4.1` kernel.

I was unable to reproduce it again with or without dropping caches :cry:

**Comment by ryao** [comment]
@farnoy What indication made you think that things had frozen?

There probably is no way to know what happened for certain, but one idea is that maybe you hit the dirty data limit, an underlying device paused in error correction during dirty data writeout and everything running blocked on that. That could give the appearance of everything freezing for a few seconds if it blocked on writes, although reads (with the exception of SEEK_HOLE/SEEK_DATA in lseek on files with dirty data) would keep working. That said, what happens is rarely the first thing that I imagine, but there isn't much to go on here.

**Comment by farnoy** [comment]
The whole desktop froze - couldn't move my mouse or do anything. I have this system load indicator on my desktop toolbar and I immediately noticed how much it went up when it unfroze.

Too bad I can't give you any more information about it. Should I start gathering debug logs from ZFS and possibly other software? Maybe it will happen again

**Comment by gmelikov** [comment]
Hello, i have such freezes on compressed zvol, compress algoritm is default, atime disabled.

I can reproduce it (for example, recheck Deluge downloaded torrents), have more than 5 second freezes (time differs for huge files - 15gb file check freezes my PC for 2 minutes).

`echo 3 > /proc/sys/vm/drop_caches` helps for a time until zfs cache exceeds my ram, i think, after that i have freezes.

It's process independent, i get freezes on io load to compressed zvol (such as games).

Debian Jessie, 
Linux kernel 4.5 4.5.0-0.bpo.1-amd64 SMP Debian 4.5.1-1~bpo8+1 (2016-04-20) x86_64 GNU/Linux
zfs 0.6.5.6. 



16gb RAM, intel i5 6600k.

`zfs get all fs2/main`
> NAME      PROPERTY              VALUE                      SOURCE
> fs2/main  type                  filesystem                 -
> fs2/main  creation              Сб окт 31 16:37 2015  -
> fs2/main  used                  265G                       -
> fs2/main  available             303G                       -
> fs2/main  referenced            265G                       -
> fs2/main  compressratio         1.11x                      -
> fs2/main  mounted               yes                        -
> fs2/main  quota                 none                       default
> fs2/main  reservation           none                       default
> fs2/main  recordsize            128K                       default
> fs2/main  mountpoint            /data/fs1                  local
> fs2/main  sharenfs              off                        default
> fs2/main  checksum              on                         default
> fs2/main  compression           on                         local
> fs2/main  atime                 off                        inherited from fs2
> fs2/main  devices               on                         default
> fs2/main  exec                  on                         default
> fs2/main  setuid                on                         default
> fs2/main  readonly              off                        default
> fs2/main  zoned                 off                        default
> fs2/main  snapdir               hidden                     default
> fs2/main  aclinherit            restricted                 default
> fs2/main  canmount              on                         default
> fs2/main  xattr                 on                         default
> fs2/main  copies                1                          default
> fs2/main  version               5                          -
> fs2/main  utf8only              off                        -
> fs2/main  normalization         none                       -
> fs2/main  casesensitivity       sensitive                  -
> fs2/main  vscan                 off                        default
> fs2/main  nbmand                off                        default
> fs2/main  sharesmb              off                        default
> fs2/main  refquota              none                       default
> fs2/main  refreservation        none                       default
> fs2/main  primarycache          all                        default
> fs2/main  secondarycache        all                        default
> fs2/main  usedbysnapshots       0                          -
> fs2/main  usedbydataset         265G                       -
> fs2/main  usedbychildren        0                          -
> fs2/main  usedbyrefreservation  0                          -
> fs2/main  logbias               latency                    default
> fs2/main  dedup                 off                        default
> fs2/main  mlslabel              none                       default
> fs2/main  sync                  standard                   default
> fs2/main  refcompressratio      1.11x                      -
> fs2/main  written               265G                       -
> fs2/main  logicalused           295G                       -
> fs2/main  logicalreferenced     295G                       -
> fs2/main  filesystem_limit      none                       default
> fs2/main  snapshot_limit        none                       default
> fs2/main  filesystem_count      none                       default
> fs2/main  snapshot_count        none                       default
> fs2/main  snapdev               hidden                     default
> fs2/main  acltype               off                        default
> fs2/main  context               none                       default
> fs2/main  fscontext             none                       default
> fs2/main  defcontext            none                       default
> fs2/main  rootcontext           none                       default
> fs2/main  relatime              off                        default
> fs2/main  redundant_metadata    all                        default
> fs2/main  overlay               off                        default

[dmesg.txt](https://github.com/zfsonlinux/zfs/files/250653/dmesg.txt) after `echo 3 > /proc/sys/vm/drop_caches` and more than 2 minute freezes.

What additional info can i give? Thanks!
