### ISSUE TITLE
[Feature Request] Add l2arc_max_block_size tunable

### ISSUE THREAD

**Issue by Sachiru** [zfsonlinux/zfs#4323]
As per the blog post from Oracle here:

https://blogs.oracle.com/storageops/entry/when_should_i_buy_readzilla

"This optimization for small-block I/O may not be available in non-Oracle ZFS implementations, but can be viewed with "echo l2arc_max_block_size/D | mdb -k" on Solaris."

Can we add a ZFS tunable that allows users to set the l2arc max block size (currently 32kb) for ZoL?

**Comment by behlendorf** [comment]
That's not a bad idea, particularly if your pool contains large blocks (up to 16M).  I'm a little surprised something like this doesn't already exist.  I've opened #4326 with an initial implementation of this feature for review and testing.  It works as expected in my initiation testing.
