### ISSUE TITLE
zfs-import-scan.service should be removed

### ISSUE THREAD

**Issue by ryao** [zfsonlinux/zfs#4325]
@behlendorf zfs-import-scan.service should be removed for the same reasons 33df62d052bad11a1ebb220810672fcfba2a8d86 was done.

The only difference between this and what was done prior to 33df62d052bad11a1ebb220810672fcfba2a8d86 is that the presence of the cachefile reverts to the behavior that 33df62d052bad11a1ebb220810672fcfba2a8d86. Not every system with the ZoL userland installed is necessarily actually using it. In that cases, we could have the behavior that 33df62d052bad11a1ebb220810672fcfba2a8d86 disabled occur on every boot.

**Comment by behlendorf** [comment]
The cache file is one way to configure the system, it's not definitively the right way or the only way.  The current systemd behavior is to prefer the cache file if it exists otherwise fall back to scanning.

**Comment by ilovezfs** [comment]
I think it's hard to justify a naked, automated `zpool import -a` under any scenario even with `-d /dev/disk/by-id`. Maybe if it forced the mountpoint property to be entirely ignored, it would be something other than scary.

**Comment by ryao** [comment]
@behlendorf I ha been intentionally vague in describing my concern because I wanted to ensure the issue was tracked, but I did not want people outside of the core ZoL developers to understand what I was saying.

Unfortunately, it seems that I had been too vague. Anyway, I sent you a PGP encrypted email describing my concerns. Its content should be similar to that of the last PGP encrypted email that I sent you, which described a similar issue.

**Comment by behlendorf** [comment]
Disabled by default in #4699.
