### ISSUE TITLE
EL7 kmod repo metadata not updated

### ISSUE THREAD

**Issue by herver** [zfsonlinux/zfs#4327]
Hello there, 

I'm using the kmod repo that @behlendorf mentioned [here](https://github.com/zfsonlinux/zfs/issues/3801#issuecomment-142444518) but it seems like although zfs-0.6.5.4 RPMs are [there](http://archive.zfsonlinux.org/?marker=epel/7/kmod/x86_64/zfs-0.6.5.4) the metadata of the repo are stuck with the previous 0.6.5.3.

Would you mind refreshing these ?

**Comment by behlendorf** [comment]
Looks like the machinery had a hiccup, I've refreshed it and it's providing 0.6.54 now.  Thank you for reporting this.

**Comment by herver** [comment]
Hi, 

We mirror the kmod repo but it doesn't seem to contain the last 0.6.5.5 release of today.
Is the machinerey to publish `kmod-{zfs,spl} `to the kmod repo automatic ? 

Or is it just me being impatient to get my hands on the the fresh RPMs ?

Thank you for your help.

**Comment by behlendorf** [comment]
@herver it looks like the repodata didn't get updated, I manually refreshed it and everything looks good now.

**Comment by herver** [comment]
Thanks :+1: 
Could you do the same for the el6 repo ?

**Comment by behlendorf** [comment]
@herver refreshed the 3l6 kmod repo.

**Comment by herver** [comment]
Hi there, 

The metadata for the kmod repo for el6/7 are still lagging behind, the RPMs are there for 0.6.5.7 but the repodata didn't get updated (which causes mirror creation to skip these).

- http://archive.zfsonlinux.org/epel/6/kmod/x86_64/
- http://archive.zfsonlinux.org/epel/7/kmod/x86_64/

Could you please have a look ? (and possibly automated it as for the normal repo ?)

**Comment by herver** [comment]
I noticed that this time the kmod RPMs haven't been built for 0.6.5.8.

They don't show up here: http://archive.zfsonlinux.org/?prefix=epel/7/kmod/x86_64/zfs-0.6.5 nor in the metadata.

If you need a hand to get this working (or builders), please let me know !

**Comment by behlendorf** [comment]
@herver a month or so back the EPEL and Fedora repositories were migrated from http://archive.zfsonlinux.org to http://download.zfsonlinux.org.  An updated zfs-release package was published in the archive repo but it wouldn't have overwritten your `/etc/yum.repos.d/zfs.conf` file if you had made local modifications.  Look for a new `/etc/yum.repos.d/zfs.conf.rpmnew` file to use.

As of today the main zfs repository contains packages for 0.6.5.8 and the zfs-testing repository contains the 0.7.0-rc2 release candidate.
