### ISSUE TITLE
zdb: Assertion `pthread_setspecific(kthread_key, kt) == 0 (0x16 == 0x0)' failed.

### ISSUE THREAD

**Issue by tuxoko** [zfsonlinux/zfs#4331]
On latest master, running zdb will get ```zdb: kernel.c:130: Assertion `pthread_setspecific(kthread_key, kt) == 0 (0x16 == 0x0)' failed.```

The problem seems to be that zdb will call into `zpool_find_import_impl`, which does `thread_init` and `thread_fini`, causing `kthread_key` to be invalid.

**Comment by behlendorf** [comment]
This was accidentally introduced by 519129ff4e717f3026ae70b58d2db59d937aef06 which I recently brought over from Illumos.  It was overkill to bring over the entire illumos thread pool interface so I hijacked the user space taskqs which provide basically the same interface.  I wanted to avoid initializing everything with kernel_init().
