### ISSUE TITLE
libzfs_impl.h -> struct zpool_handle: zpool_hdl should be zfs_hdl

### ISSUE THREAD

**Issue by ggzengel** [zfsonlinux/zfs#4336]
struct zpool_handle {
    libzfs_handle_t *zpool_hdl;

zpool_dhl points to a libzfs handle so it should be named zfs_hdl like in

struct zfs_handle {
    libzfs_handle_t *zfs_hdl;

**Comment by ggzengel** [comment]
More better is to name zfs_hdl to libzfs_hdl, because there is zfs_handle and libzfs_handle.

So it should be:
struct zpool_handle {
libzfs_handle_t *libzfs_hdl;

struct zfs_handle {
libzfs_handle_t *libzfs_hdl;

**Comment by ggzengel** [comment]
After looking here (http://fossies.org/dox/zfs-0.6.5.4/structzfs__handle.html) I understand this naming scheme. They normally use the struct name as prefix. But they didn't in zfs_handle.

So it would be more clearly to use:
```
struct zfs_handle {
  libzfs_handle_t *zfs_libzfs_hdl; // old: zfs_hdl
  zpool_handle_t *zfs_zpool_hdl; //old: zpool_hdl

struct zpool_handle {
  libzfs_handle_t *zpool_libzfs_hdl; // old: zpool_hdl
  zpool_handle_t *zpool_next;
```

**Comment by behlendorf** [comment]
Could you propose a pull request for this cleanup.
