### ISSUE TITLE
INFO: task txg_sync:4116 blocked for more than 120 seconds

### ISSUE THREAD

**Issue by kevin0431** [zfsonlinux/zfs#4339]
We are running 0.6.3-1 and kernel is 2.6.32-358.6.1.el6.x86_64, should I set  spl_taskq_thread_dynamic =0 for below kernel error?

<3>INFO: task txg_sync:4116 blocked for more than 120 seconds.
<3>"echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
<6>txg_sync      D 0000000000000008     0  4116      2 0x00000000
<4> ffff88106960db70 0000000000000046 0000000000000001 ffff88107158a570
<4> 0000000000000000 0000000000000000 ffff88106960daf0 ffffffff81063322
<4> ffff8810704c7058 ffff88106960dfd8 000000000000fb88 ffff8810704c7058
<4>Call Trace:
<4> [<ffffffff81063322>] ? default_wake_function+0x12/0x20
<4> [<ffffffff810a1aa9>] ? ktime_get_ts+0xa9/0xe0
<4> [<ffffffff8150de73>] io_schedule+0x73/0xc0
<4> [<ffffffffa021bccc>] cv_wait_common+0xac/0x1c0 [spl]
<4> [<ffffffffa038de70>] ? zio_execute+0x0/0x140 [zfs]
<4> [<ffffffff81096c80>] ? autoremove_wake_function+0x0/0x40
<4> [<ffffffffa021bdf8>] __cv_wait_io+0x18/0x20 [spl]
<4> [<ffffffffa038e0ab>] zio_wait+0xfb/0x1b0 [zfs]
<4> [<ffffffffa031c083>] dsl_pool_sync+0xb3/0x430 [zfs]
<4> [<ffffffffa0331be3>] spa_sync+0x433/0xac0 [zfs]
<4> [<ffffffffa03465b4>] txg_sync_thread+0x3b4/0x640 [zfs]
<4> [<ffffffff81056089>] ? set_user_nice+0xc9/0x130
<4> [<ffffffffa0346200>] ? txg_sync_thread+0x0/0x640 [zfs]
<4> [<ffffffffa0213978>] thread_generic_wrapper+0x68/0x80 [spl]
<4> [<ffffffffa0213910>] ? thread_generic_wrapper+0x0/0x80 [spl]
<4> [<ffffffff81096916>] kthread+0x96/0xa0
<4> [<ffffffff8100c0ca>] child_rip+0xa/0x20
<4> [<ffffffff81096880>] ? kthread+0x0/0xa0
<4> [<ffffffff8100c0c0>] ? child_rip+0x0/0x20
<0>Kernel panic - not syncing: hung_task: blocked tasks
<4>Pid: 257, comm: khungtaskd Tainted: P           ---------------    2.6.32-358.el6.x86_64 #1
<4>Call Trace:
<4> [<ffffffff8150cfc8>] ? panic+0xa7/0x16f
<4> [<ffffffff810e0ab7>] ? watchdog+0x217/0x220
<4> [<ffffffff810e08a0>] ? watchdog+0x0/0x220
<4> [<ffffffff81096916>] ? kthread+0x96/0xa0
<4> [<ffffffff8100c0ca>] ? child_rip+0xa/0x20
<4> [<ffffffff81096880>] ? kthread+0x0/0xa0
<4> [<ffffffff8100c0c0>] ? child_rip+0x0/0x20

**Comment by behlendorf** [comment]
The warning here is just advisory.  I'd also suggest updated to 0.6.5.4.
