### ISSUE TITLE
I/O errors since dataset change to sync=always

### ISSUE THREAD

**Issue by giezi** [zfsonlinux/zfs#4340]
Dear ZFS on Linux Team

We have changed the sync setting on all datasets on several systems from sync=standard to sync=always yesterday. Since the change, we see on all systems a mass amount of "blk_update_request: I/O error" messages on different disks:

16-02-2016  04:50:13    Result: hostbyte=DID_TIME_OUT driverbyte=DRIVER_OK
16-02-2016  04:50:13    CDB:
16-02-2016  04:50:13    Write(10): 2a 00 56 6c 60 60 00 00 50 00
16-02-2016  04:50:13    blk_update_request: I/O error, dev sdg, sector 1449943136
16-02-2016  04:50:14    blk_update_request: I/O error, dev sdg, sector 0
16-02-2016  08:01:52    sd 0:0:18:0: attempting task abort! scmd(ffff88017e4e8600)
16-02-2016  08:01:52    CDB:
16-02-2016  08:01:52    Write(10): 2a 00 03 87 e3 70 00 01 00 00
16-02-2016  08:01:52    scsi target0:0:18: handle(0x001c), sas_address(0x5003048001b259a2),phy(34)
16-02-2016  08:01:52    scsi target0:0:18: enclosure_logical_id(0x5003048001b259bf), slot(18)
16-02-2016  08:01:52  
16-02-2016  08:01:52    Result: hostbyte=DID_SOFT_ERROR driverbyte=DRIVER_OK
16-02-2016  08:01:52    CDB:
16-02-2016  08:01:52    Write(10): 2a 00 03 f6 36 40 00 00 10 00
16-02-2016  08:01:52    blk_update_request: I/O error, dev sds, sector 66467392

ZoL Version: 0.6.5.4
Kernel: 3.18.26-76
Pool ashift: 13

Disks types:
Samsung 850 PRO 2TB
Samsung 840 EVO 1TB

Thank you in advance for any kind of help.

Best regards
Reto

**Comment by niekbergboer** [comment]
FWIW: I've had various kinds of trouble with the 850 Pro series, including checksum errors.

**Comment by giezi** [comment]
Thank you for your hint!  What do you think, is it maybe related to the ashift:13 value? Because some people tend to use ashift:12 in combination with Samsung SSDs. Any experience?

**Comment by AndCycle** [comment]
850 Pro is known to have a buggy firmware, 
so there is probably not much thing can be done here,

https://groups.google.com/a/zfsonlinux.org/d/topic/zfs-discuss/q_eMWwyVooc/discussion
