### ISSUE TITLE
"zpool status" doesn't give reliable device names

### ISSUE THREAD

**Issue by chadmiller** [zfsonlinux/zfs#4341]
In truncating everything before the last '/' in vdev names, we lose information that users and utilities would like to be able to use to work on the device outside of zpool.

I'm thinking of "grub" now, in that it wants a list of devices that make up a pool. "zpool status" gives some name that could be found in /dev/ or in /dev/disk/by-id/ or /dev/mapper/ ....

By discarding the path before printing, we make utilities and users guess, and that's a bad thing.

**Comment by chadmiller** [comment]
A new parameter will work, but enforces a dependency on a particular version. This is what I hope to use in Ubuntu.

``` C
--- zfs-linux-0.6.5.4.orig/lib/libzfs/libzfs_pool.c
+++ zfs-linux-0.6.5.4/lib/libzfs/libzfs_pool.c
@@ -3484,8 +3484,11 @@ zpool_vdev_name(libzfs_handle_t *hdl, zp
         */
        verify(nvlist_lookup_string(nv, ZPOOL_CONFIG_TYPE, &type) == 0);
        if (strcmp(type, VDEV_TYPE_DISK) == 0) {
+         char *full_paths = getenv("WITH_FULL_PATHS");
+         if ((full_paths == NULL) || (strcmp(full_paths, "") == 0) || (strcmp(full_paths, "0") == 0)) {
            path = strrchr(path, '/');
            path++;
+         }
        }

        /*
```

**Comment by behlendorf** [comment]
At least in spirit this is related to #2012 which adds an option to print the guid instead of the short name.  It would be nice to refactor that previous work so it could be used to optionally print either the guid, short name, or full name of a vdev.

**Comment by ilovezfs** [comment]
@behlendorf We've had this on OS X for a while:
https://github.com/openzfsonosx/zfs/commit/87943e68370d9e29cfadb24b1ca8936267aee48b
https://github.com/openzfsonosx/zfs/commit/13905023ed3605b352c5facf1207da7b52bd57fe

**Comment by behlendorf** [comment]
@ilovezfs nice!  I wasn't aware you'd built on Richard's work.

**Comment by arvidjaar** [comment]
Would you still consider out-of-band way to enable full paths, like environment variable, suggested originally? Using options is compatibility problem - how can we reliably detect whether zpool supports new options or not before calling it? Environment variable allows us to ask "please give us full names if possible" and will be ignored if zpool version in use does not support it.

**Comment by behlendorf** [comment]
@arvidjaar I'd think you'd want to test the command (or check the version) to determine if the option was supported.  However, I do think adding the environment variables would be a nice way to customize the default behavior.  I've added the following environment variables to control this.

 ZPOOL_VDEV_NAME_GUID
 ZPOOL_VDEV_NAME_FOLLOW_LINKS
 ZPOOL_VDEV_NAME_PATH

For those who need this feature it would be helpful if you could test the patch in #4343 and verify it meets your needs.

**Comment by rlaager** [comment]
@arvidjaar, @chadmiller Is it particularly problematic to just call `zpool status -p` and if the exit status is non-zero, try again with `zpool status`?

**Comment by arvidjaar** [comment]
@rlaager We run it on multiple platforms (Linux, *BSD, OS X, may be others I have not even heard of). There is no guarantee that each platform gives the same meaning to `zpool status -p` as each develops zfs independently.

Anyway, variables are already there, it is more work to remove the code now :)
