### ISSUE TITLE
RPM packaging - zfs 0.6.5.4 

### ISSUE THREAD

**Issue by alphacc** [zfsonlinux/zfs#4348]
Dear All,

Trying to rebuild packages on el6 and el7 we have a different behavior than in the past ;
kmod(s) are being rebuilt without the kernel Version-Release in the Name. [1]

I tried to rebuild on CentOS 6.7 and 7.2.

Is it a known bug / wanted behavior ? I couldn't pinpoint what commit did change this behavior. It affect both kmod zfs and spl.
## 

Thomas.

[1]:
How to reproduce from .tar.gz :
cd zfs (or spl)
./configure --with-spec=redhat
make srpm
make rpm

RESULT ->  kmod-zfs-0.6.5.4-1.el6.x86_64.rpm
WANTED ->  kmod-zfs-2.6.32-573.8.1.el6.x86_64-0.6.5.4-1.el6.x86_64.rpm

**Comment by behlendorf** [comment]
@alphacc passing `--with-spec=redhat` to configure will result in kmod packages with weak modules support.  These modules are not tied to a specific kernel and thus don't include a specific kernel version.  They allow you to upgrade your kernel without rebuilding zfs.  This is only possible on enterprise distributions like RHEL/CENTOS/SLES when a stable kabi is provided.

If you'd rather build module for a specific kernel then don't use the --with-spec option.
