### ISSUE TITLE
zfsonlinux.com should use TLS

### ISSUE THREAD

**Issue by Aeyoun** [zfsonlinux/zfs#4353]
Please enable HTTPS on `zfsonlinux.org`. The website is used to verify signing keys (Fedora and other repositories) and the pages it serves should be made harder to intercept and modify.

Grab free certificates from [Let’s Encrypt](http://letsencrypt.org/).

**Comment by DeHackEd** [comment]
The site is hosted by github. It's not that easy.

Also Let's Encrypt is still beta so don't push it too hard on people.

**Comment by kpande** [comment]
I'd rather the project use a real CA even if it means paying a bit extra, lots of companies benefit from ZoL, maybe it's something for OpenZFS stakeholders to be involved with. I'm not sure.

**Comment by sketch242** [comment]
@kpande  Let's not spread FUD.  Let's Encrypt is a real CA, they just operate a bit differently than most.  They don't offer EV certs, but it's unlikely ZOL would go that route anyway (or even be able to).

**Comment by kpande** [comment]
@sketch242 We can certainly do EV for zfsonlinux.com, @behlendorf can, anyway.

**Comment by Aeyoun** [comment]
Any TLS is better than no TLS.

**Comment by kpande** [comment]
You can't encrypt sites hosted by Github pages on custom domains: https://konklone.com/post/github-pages-now-sorta-supports-https-so-use-it

**Comment by behlendorf** [comment]
An alternative I've been considering is migrating everything from the website (github page) to the ZFS projects wiki.  Then just point the custom domain at the wiki.  This would resolve TLS issue and from my point of view get rid of one more bit of infrastructure which someone needs to maintain.  Thoughts?

**Comment by rlaager** [comment]
@behlendorf It seems you've been working in that direction. Any interest in (me, time permitting) moving the msg stuff to the wiki? If so, would we then modify the URLs in the ZFS source code, or keep the zfsonlinux.org/msg URLs as stable URLs indefinitely? (My first instinct is to keep the URLs.)

For reference, I'm talking about the pages like this:
http://zfsonlinux.org/msg/ZFS-8000-EY/

**Comment by behlendorf** [comment]
@rlaager that's definitely the plan, and I'd love the help.  As for the msg stuff I think moving a copy of it to the wiki is a good idea.  My feeling is we'll want to leave the existing URLs intact pretty much indefinitely, with the possibility of redirecting them to the wiki versions at some point in the future.  Then for perhaps the 0.7 release we could update the URLs printed by the utilities.

This issue can also now be closed out.  All of the critical information which was hosted at zfsonlinux.org has now been migrated to the github wiki which is TLS secured.
