### ISSUE TITLE
Tweak Release file for better integration with stock Debian

### ISSUE THREAD

**Issue by fallenguru** [zfsonlinux/zfs#4354]
Currently the ZoL repo for Debian is set up so that the ZoL version of any package will be installed/upgraded over the stock one as long as its version number is higher. This means that, for instance, grub will be overwritten by the ZoL version even if you do not boot from ZFS. I for one like to stick as close to stock as possible (security updates, clean upgrade path, general distro support ...).

I realise there've been some experiments with pinning in the past but how about setting
NotAutomatic: yes
ButAutomaticUpgrades: yes
in the Releases file?

Packages that exist only in the ZoL repo should still work normally; packages with an official and a ZoL version would need either an admin decision to select the ZoL version or a dependency somewhere that effectively requires it; packages that already are the ZoL version would continue to track it. (This is how backports works.)

Packages that aren't required to be installed for ZoL to work but must be the ZoL version if they are, could just Break / Conflict earlier or even any other versions.

**Comment by caymanbumster** [comment]
I concur.

I presently have conflicts caused from installing **grub-xen-host** (v 2.02~beta2-22+deb8) from the Debian jessie repository and ZFSonLinux 0.6.5.2-2.

The conflict appears to arise at grub-common.

I am not booting a ZFS filesystem.

What's particularly attention getting is seeing "wheezy" version labels that what to get installed on a "jessie" system.

**Comment by behlendorf** [comment]
Sadly at the moment we're without a active maintainer for the Debian packages.  If you can suggest someone familiar with Debian packaging who wants the job that would be helpful.  At least until Debian officially starts including the packages.

**Comment by tomposmiko** [comment]
Where is @FransUrbo ?

**Comment by behlendorf** [comment]
Closing.  Packaging is now handled directly by the Debian project.
