### ISSUE TITLE
the manual of zpool is incorrected regarding hot spare

### ISSUE THREAD

**Issue by AceSlash** [zfsonlinux/zfs#4358]
I was surprised to see that a spare wasn't used when a drive was in error:

```
    # zpool status
      pool: tank
     state: DEGRADED
    status: One or more devices are faulted in response to persistent errors.
            Sufficient replicas exist for the pool to continue functioning in a
            degraded state.
    action: Replace the faulted device, or use 'zpool clear' to mark the device
            repaired.
      scan: none requested
    config:

            NAME                                        STATE     READ WRITE CKSUM
            tank                                        DEGRADED     0     0     0
              mirror-0                                  ONLINE       0     0     0
                scsi-360026b9062e37e001d9c3eab0f198e0a  ONLINE       0     0     0
                scsi-360026b9062e37e001d9c3eac0f2a7b74  ONLINE       0     0     0
              mirror-1                                  ONLINE       0     0     0
                scsi-360026b9062e37e001d9c3ead0f3bbccc  ONLINE       0     0     0
                scsi-360026b9062e37e001d9c3eae0f4cef55  ONLINE       0     0     0
              mirror-2                                  DEGRADED     0     0     0
                scsi-360026b9062e37e001d9c3eaf0f5f3e2f  ONLINE       0     0     0
                scsi-360026b9062e37e001d9c3eb10f71fcf6  FAULTED      0    98     0  too many errors
              mirror-3                                  ONLINE       0     0     0
                scsi-360026b9062e37e001d9c3eb20f853418  ONLINE       0     0     0
                scsi-360026b9062e37e001d9c3eb30f98b53d  ONLINE       0     0     0
            spares
              scsi-360026b9062e37e001d9c3eb50facaa09    AVAIL   

    errors: No known data errors
```

I removed the drive from the server and even rebooted just in case and the output of zpool status is now:

```
# zpool status
  pool: tank
 state: DEGRADED
status: One or more devices could not be used because the label is missing or
        invalid.  Sufficient replicas exist for the pool to continue
        functioning in a degraded state.
action: Replace the device using 'zpool replace'.
   see: http://zfsonlinux.org/msg/ZFS-8000-4J
  scan: none requested
config:

        NAME                                        STATE     READ WRITE CKSUM
        tank                                        DEGRADED     0     0     0
          mirror-0                                  ONLINE       0     0     0
            scsi-360026b9062e37e001d9c3eab0f198e0a  ONLINE       0     0     0
            scsi-360026b9062e37e001d9c3eac0f2a7b74  ONLINE       0     0     0
          mirror-1                                  ONLINE       0     0     0
            scsi-360026b9062e37e001d9c3ead0f3bbccc  ONLINE       0     0     0
            scsi-360026b9062e37e001d9c3eae0f4cef55  ONLINE       0     0     0
          mirror-2                                  DEGRADED     0     0     0
            scsi-360026b9062e37e001d9c3eaf0f5f3e2f  ONLINE       0     0     0
            11816597691826856982                    UNAVAIL      0     0     0  was /dev/disk/by-id/scsi-360026b9062e37e001d9c3eb10f71fcf6-part1
          mirror-3                                  ONLINE       0     0     0
            scsi-360026b9062e37e001d9c3eb20f853418  ONLINE       0     0     0
            scsi-360026b9062e37e001d9c3eb30f98b53d  ONLINE       0     0     0
        spares
          scsi-360026b9062e37e001d9c3eb50facaa09    AVAIL   

errors: No known data errors
```

I tried to change the settings of zed in "/etc/zfs/zed.d/zed.rc", in-commenting the following lines:

```
ZED_SPARE_ON_CHECKSUM_ERRORS=10
ZED_SPARE_ON_IO_ERRORS=1
```

But still the zpool doesn't use its spare... Should I have changed the zed settings before? Is this intended behavior? Is it possible to force the use of a spare at this point?

It seems like a bug that the spare is not used or the documentation is incredibly misleading:

```
   Hot Spares
       ZFS allows devices to be associated with pools as "hot spares". These devices are not actively used in the pool, but when an active device fails, it is automatically replaced by a hot spare.
```

**Comment by dasjoe** [comment]
As the failed disk is already marked as `UNAVAIL` it will not trigger zed on its own, just use `zpool replace` manually:
`zpool replace tank 11816597691826856982 scsi-360026b9062e37e001d9c3eb50facaa09`

The changes to zed.rc will show effects once your pool shows new checksum or IO errors.

**Comment by dasjoe** [comment]
`man zpool` states that hot spares are used automatically, which is not the case (as of now).
Please rename this issue or open a new one about `man zpool` requiring a fix so it correctly mentions zed and maybe even hints at how to configure zed.

**Comment by AceSlash** [comment]
Thank you it works, maybe add to the man page of zpool that to trigger a spare the "/etc/zfs/zed.d/zed.rc" must be changed? or just change it on the next release?

**Comment by Ralithune** [comment]
Did this issue get resolved?

We have a customer who wants to know if spares will be automatically used in the case of degradation.

**Comment by behlendorf** [comment]
@Ralithune they will be added in the zed is configured to do so.  There is still ongoing work to improve the default behavior.

**Comment by Ralithune** [comment]
I hate to keep banging on this issue, but I'm not sure where to go.

I've got both of the parameters uncommented (and the system has been rebooted through numerous testing sequences) but ZFS still doesn't appear to be doing anything after I remove a drive.  http://pastebin.com/FScL4sP5

Do I need to do something other than uncomment those lines? @AceSlash

**Comment by AceSlash** [comment]
@Ralithune sorry I can't help you: since then I don't have any pool with a hot spare where a disk failed.

**Comment by Tristan2252** [comment]
Hi, I am experiencing the same issue where i have both flags set to
```
ZED_SPARE_ON_CHECKSUM_ERRORS=10
ZED_SPARE_ON_IO_ERRORS=1
```
as well as `autoreplace=on`. When i remove a drive the status of the pool goes to `DEGRADED` but the spare remains as status `AVAIL` and does not replace the removed drive. Is there any solution to this without just doing it manually?

**Comment by Ralithune** [comment]
@AceSlash If you pull a drive, does your system begin the failover process right away?

My experience is that it sits and does not recognize it, but does complain of degraded state.

You can put it back to normal operation by re-seating the drive and typing 
`zpool hottub clear`

**Comment by kernelOfTruth** [comment]
referencing https://github.com/zfsonlinux/zfs/issues/2808 , http://list.zfsonlinux.org/pipermail/zfs-discuss/2014-October/019321.html , https://github.com/zfsonlinux/zfs/issues/2449

**Comment by gmelikov** [comment]
There were ZED related changes last year which affect this issue. Closed.

**Comment by Keeper-of-the-Keys** [comment]
I don't think this issue should have been closed.

I just created a test system on CentOS 7.5 with ZFS 0.7.9 set up a pool in raidz2 with a spare pulled the plug on one disk and the spare was not taken into use, man zpool does not mention anywhere that I need to do anything in zed.rc to make this process act like a hot spare as the name suggests.

I will modify may zed.rc and try again but regardless of the result of that test if I indeed need to modify any setting from what ships to make "hot spare" work as "man zpool" suggests that should be stated in "man zpool".

**Comment by Keeper-of-the-Keys** [comment]
After modifying zed.rc as suggested above and rebooting the hot-spare still did not take over, I had one disk UNAVAIL and a spare AVAIL while the pool was degraded and suggested that I take a manual action.

**Comment by abqcheeks** [comment]
I'm having the same issue. This system is a new Debian stretch installed last week.  I've also enabled the appropriate items in the rc file.  I've done a little troubleshooting and noticed that /etc/zfs/zed.d/io-spare.sh contains this logic:
```
    # Device is already FAULTED or DEGRADED
    if [ "${vdev_status}" = "FAULTED" ] \
            || [ "${vdev_status}" = "DEGRADED" ]; then
        rv=3
    else
        rv=1
        # 1) FAULT or DEGRADE the device.
        ...
        # 2) Set the SES fault beacon. (not actually implemented)
        ...
        # 3) Replace the device with a hot spare.

```
It looks to me like if an io error occurred and zed was notified before the drive got marked DEGRADED, it would then mark it DEGRADED and activate a spare.  But if I just pull a drive, I think ZFS marks the drive DEGRADED before zed is invoked.  It sees that it is already degraded and exits without doing anything.

My first inclination is to rearrange that logic so that it is willing to activate a spare for a degraded drive.  But I have not traced all the implications of that.  (Like, will that lead to trying to activate a spare again if some other event fires?  And doesn't the failed disk need to be detached to keep it from showing up as degraded?)

Any input welcome.  Am I on the right track?

**Comment by abqcheeks** [comment]
A little more troubleshooting.  When I physically remove a disk from the array, it's marked as UNAVAIL, not DEGRADED or FAULTED.  The io-spares.sh script gets called 3 times in about 0.05 seconds.  Each time, ZEVENT_SUBCLASS is set to "io", but ZEVENT_VDEV_READ_ERRORS and ZEVENT_VDEV_WRITE_ERRORS are both 0, so no action is taken.

The email zed sends also reports there was an io error, but all the error counts are 0.

**Comment by behlendorf** [comment]
> Any input welcome. Am I on the right track?

@abqcheeks you're on the right track, but it sounds like you're running an 0.6.x based release.  For the 0.7.x releases a lot of work was done in this area to resolve the kinds of issues you're seeing, including retiring the `io-spare.sh` script.  This behavior is now controlled by the ZED itself, for full details see commit 976246fadde25790cec3de50c01c689d98d84e0c.  If possible, I'd suggest updating to the 0.7.x releases.

**Comment by abqcheeks** [comment]
You are correct, zfs-0.6.5.9-5.  I'll see about installing 0.7.x.  Thanks.

**Comment by abqcheeks** [comment]
Is 0.7.x available in debian stretch-backports?

**Comment by gmelikov** [comment]
@abqcheeks yes https://packages.debian.org/stretch-backports/zfs-dkms

**Comment by abqcheeks** [comment]
@gmelikov thank you ... turns out I was missing "contrib non-free" on my repo line in apt/sources.list

**Comment by abqcheeks** [comment]
Just to report back, with 0.7.9 it did the right thing for me.  I pulled a disk on a raidz3, and after the next i/o it activated one of the 2 spares and resilvered.  The only oddity was after resilvering the raidz3 was still marked DEGRADED until I detached the failed disk.  Thanks for the help guys.

**Comment by Keeper-of-the-Keys** [comment]
@abqcheeks Did it work out of the box for you or you did need to change configuration somewhere?

**Comment by Keeper-of-the-Keys** [comment]
@abqcheeks hmmm I'll retest, I'm having a slight suspicion that maybe the fact that I at first installed 0.6.x (CentOS 7.0 repo) instead of 0.7.9 (CentOS 7.5 repo) may be messing things up.

**Comment by abqcheeks** [comment]
@Keeper-of-the-Keys that's exactly what I did (except Debian instead of CentOS).  You can confirm zed is the right version with "zed -V".  

Here is what zed logged for me.  Does it log anything for you?

```Jun 12 15:45:53 sassyaii zed: eid=12 class=io pool_guid=0x4A4D6D21CE35D88D vdev_path=/dev/disk/by-id/wwn-0x5000c500420310b7-part1
Jun 12 15:45:53 sassyaii zed: eid=13 class=io pool_guid=0x4A4D6D21CE35D88D vdev_path=/dev/disk/by-id/wwn-0x5000c500420310b7-part1
Jun 12 15:45:53 sassyaii zed: eid=14 class=io pool_guid=0x4A4D6D21CE35D88D vdev_path=/dev/disk/by-id/wwn-0x5000c500420310b7-part1
Jun 12 15:45:53 sassyaii zed: eid=15 class=probe_failure pool_guid=0x4A4D6D21CE35D88D vdev_path=/dev/disk/by-id/wwn-0x5000c500420310b7-part1
Jun 12 15:45:55 sassyaii zed: eid=16 class=vdev.too_small pool_guid=0x4A4D6D21CE35D88D vdev_path=/dev/disk/by-id/wwn-0x5000c500420310b7-part1
Jun 12 15:45:55 sassyaii zed: eid=17 class=statechange pool_guid=0x4A4D6D21CE35D88D vdev_path=/dev/disk/by-id/wwn-0x5000c500420310b7-part1 vdev_state=UNAVAIL
Jun 12 15:45:55 sassyaii zed: eid=18 class=vdev_spare pool_guid=0x4A4D6D21CE35D88D vdev_path=/dev/disk/by-id/wwn-0x5000c5004203245b-part1 vdev_state=ONLINE
Jun 12 15:45:55 sassyaii zed: eid=19 class=vdev_attach pool_guid=0x4A4D6D21CE35D88D vdev_path=/dev/disk/by-id/wwn-0x5000c5004203245b-part1 vdev_state=ONLINE
Jun 12 15:45:57 sassyaii zed: eid=20 class=resilver_start pool_guid=0x4A4D6D21CE35D88D
Jun 12 15:45:57 sassyaii zed: eid=21 class=history_event pool_guid=0x4A4D6D21CE35D88D
Jun 12 15:46:00 sassyaii zed: eid=22 class=config_sync pool_guid=0x4A4D6D21CE35D88D
Jun 12 15:46:06 sassyaii zed: eid=23 class=history_event pool_guid=0x4A4D6D21CE35D88D
Jun 12 15:48:30 sassyaii zed: eid=24 class=history_event pool_guid=0x4A4D6D21CE35D88D
Jun 12 15:48:30 sassyaii zed: eid=25 class=resilver_finish pool_guid=0x4A4D6D21CE35D88D
Jun 12 15:50:28 sassyaii zed: eid=26 class=vdev.unknown pool_guid=0x4A4D6D21CE35D88D vdev_path=/dev/disk/by-id/wwn-0x5000c500420310b7-part1
Jun 12 15:50:29 sassyaii zed: eid=27 class=vdev_clear pool_guid=0x4A4D6D21CE35D88D vdev_path=/dev/disk/by-id/wwn-0x5000c500420310b7-part1 vdev_state=UNAVAIL
Jun 12 15:50:29 sassyaii zed: eid=28 class=config_sync pool_guid=0x4A4D6D21CE35D88D
Jun 12 15:51:12 sassyaii zed: eid=29 class=vdev_remove_aux pool_guid=0x4A4D6D21CE35D88D vdev_path=/dev/disk/by-id/wwn-0x5000c5004203245b-part1 vdev_state=ONLINE
Jun 12 15:51:12 sassyaii zed: eid=30 class=vdev_remove pool_guid=0x4A4D6D21CE35D88D vdev_path=/dev/disk/by-id/wwn-0x5000c500420310b7-part1 vdev_state=UNAVAIL
Jun 12 15:51:12 sassyaii zed: eid=31 class=config_sync pool_guid=0x4A4D6D21CE35D88D
Jun 12 15:51:17 sassyaii zed: eid=32 class=history_event pool_guid=0x4A4D6D21CE35D88D
Jun 12 15:52:26 sassyaii zed: eid=33 class=config_sync pool_guid=0x4A4D6D21CE35D88D
Jun 12 15:52:26 sassyaii zed: eid=34 class=vdev_add pool_guid=0x4A4D6D21CE35D88D
```

**Comment by Keeper-of-the-Keys** [comment]
I just had some time to rebuild my test system and indeed a clean and correct install did work out of the box!

**Comment by ycs0220** [comment]
> 

Do raidz1 and mirror work as well？
