### ISSUE TITLE
Prefer reading from SSDs in asymmetric (SSD+HDD) mirrors

### ISSUE THREAD

**Issue by inkdot7** [zfsonlinux/zfs#4363]
Inspired by some earlier discussions here I have implemented a suggestion for a minimalistic change of the mirror vdev read scheduler vdev_mirror_child_select() such that it if possible reads from nonrotating storage, when the mirror has a mix of rotating and non-rotating storage.  It is also protected by a module parameter, such that this behaviour is not active by default.

Performance tests with fio and varying blocksizes (to mimic varying filesizes although fio as far as I managed uses very large files, and thus trigger ZFS checking of entire records even for small reads) are attached [prefer_nonrot_measurements.txt](https://github.com/zfsonlinux/zfs/files/143508/prefer_nonrot_measurements.txt).  They show ~50 % random read iops improvement, and ~20 % for random writes.  Also the streaming read and write performance improved, especially the reads (up to 80 % in my case); I suppose as they no longer stall for long-ago issued HDD reads.

I would of course be interested in this kind of functionality being included in ZFS on Linux.  But am no expert on the internals or other workings of ZFS, or how to perform deeper testing.  Please tell if there is something to fix with the patches to better adhere to coding standards, etc. 

Technical comment: the idea with making two rounds in the selection loop of vdev_mirror_child_select() is that it is a very rare case that two turns will actually be made.  Usually it will just take the first hit.  The alternative would be to duplicate the loop, which looked more hairy.

Patches 4 and 5 add a column to 'zpool iostat', showing which vdevs are non-rotating, and also which ones have mixed underlying storage.

The patches (5): [prefer_nonrot.tar.gz](https://github.com/zfsonlinux/zfs/files/143513/prefer_nonrot.tar.gz)

// Håkan

**Comment by DeHackEd** [comment]
Any reason against submitting this as a pull request instead? It's easier to read and comment on.

**Comment by behlendorf** [comment]
@inkdot7 please add the patches to a pull request so it's easier to comment/review.  You might also be interested in #4334 which incorporated some additional improvements from FreeBSD.  If you're in a position to help benchmark those changes and yours that would be helpful.

**Comment by inkdot7** [comment]
Ok, hope that worked as a review request.  It seems I have worked relative to 7a27ad0 (tag: zfs-0.6.5), ok?  The measurements are based on that in any case.  FreeBSD r256956 applied cleanly - running some tests now.

**Comment by inkdot7** [comment]
Have now also tested with fb1e93e: 
[more_nonrot_measurements.txt](https://github.com/zfsonlinux/zfs/files/144449/more_nonrot_measurements.txt)

The results are the very much the same, almost too similar :)  In the 2-way SSD parallel read case the fb1e93e commit does improve things a bit, where my solution does nothing.

Perhaps as a useful leftover: I found it nice when 'zpool iostat' told which drives are nonrotating/SSD.

**Comment by ryao** [comment]
@inkdot7 You could write a patch on top of the FreeBSD code to expose that information in `zpool iostat`.

It would have been nice if these changes were in an actual pull request, although I am leaning toward us adopting FreeBSD's code for the sake of reducing divergence and because their tunables make more sense. Getting the same results as the FreeBSD code with some minor changes to the existing algorithm is definitely interesting though.

**Comment by inkdot7** [comment]
Actually, I was unaware of the FreeBSD code until now.  As that seems to also deal better with the case of slight performance differences between units within a storage class, #4334 would be preferable to me too.

(I think I managed to put my suggestion in a pull request though?  See #4364 above.)

I close this issue, and that pull request, and return with a zpool iostat information pull request later.

**Comment by ingresso-pete** [comment]
So, I've arrived at this several years too late - but did this kind of change go into ZFS in the end at all ? ( am on FreeBSD, but thats now using OpenZFS anyway ). Use case for me would be to mirror a drive on a cloud machine to local instance SSD in order to speed up reads. If something like this went in and works then that would be great ;)

**Comment by behlendorf** [comment]
This functionality was added in commit 9f500936c82137ef3a57c53013894f622dcec14e back in 2016.   If you're using an OpenZFS on FreeBSD you'll have this functionality.  Some additional tuning are available if you want to modify the default behavior.

```
     zfs_vdev_mirror_rotating_inc=0 (int)
             A number by which the balancing algorithm increments the load
             calculation for the purpose of selecting the least busy mirror
             member when an I/O operation immediately follows its predecessor
             on rotational vdevs for the purpose of making decisions based on
             load.

     zfs_vdev_mirror_rotating_seek_inc=5 (int)
             A number by which the balancing algorithm increments the load
             calculation for the purpose of selecting the least busy mirror
             member when an I/O operation lacks locality as defined by
             zfs_vdev_mirror_rotating_seek_offset.  Operations within this
             that are not immediately following the previous operation are
             incremented by half.

     zfs_vdev_mirror_rotating_seek_offset=1048576B (1MB) (int)
             The maximum distance for the last queued I/O operation in which
             the balancing algorithm considers an operation to have locality.
             See ZFS I/O SCHEDULER.

     zfs_vdev_mirror_non_rotating_inc=0 (int)
             A number by which the balancing algorithm increments the load
             calculation for the purpose of selecting the least busy mirror
             member on non-rotational vdevs when I/O operations do not immedi‐
             ately follow one another.

     zfs_vdev_mirror_non_rotating_seek_inc=1 (int)
             A number by which the balancing algorithm increments the load
             calculation for the purpose of selecting the least busy mirror
             member when an I/O operation lacks locality as defined by the
             zfs_vdev_mirror_rotating_seek_offset.  Operations within this
             that are not immediately following the previous operation are
             incremented by half.
```

**Comment by ingresso-pete** [comment]
Thankyou, thats excellent, and just what I needed to know!

**Comment by spacerunner5** [comment]
Hi,

I hope this simple question may catch someones attention - I do not want to reopen the issue. Came here googling for "zfs_vdev_mirror_non_rotating_inc".

Unfortunately, I have a hard time understanding the parameters mentioned above.

Example Setup: Mirror vdev, 2 non-rotating disks (SSD) attached, one of them way slower (latency) than the other.

Goal: Read preferably only from the faster SSD. What settings should I apply where?

I would greatly appreciate any help with a small example. Basically a similar concept compared to the question of @ingresso-pete - I just don't know how to implement it. 

Thank a thousand times for OpenZFS :)

**Comment by ingresso-pete** [comment]
Hi! So, they are in sysctls...

$ sysctl -a vfs.zfs.vdev | grep rotating
vfs.zfs.vdev.aggregation_limit_non_rotating: 131072
vfs.zfs.vdev.mirror.non_rotating_seek_inc: 1
vfs.zfs.vdev.mirror.non_rotating_inc: 0
vfs.zfs.vdev.mirror.rotating_seek_offset: 1048576
vfs.zfs.vdev.mirror.rotating_seek_inc: 5
vfs.zfs.vdev.mirror.rotating_inc: 0

thats the defaults on my 15-STABLE machine. I havent played about with this in a while. Googling those, with dots instead of underscores,m will give you more info. But as I understand it, the values above means it will prefer the non rotating to the rotating for a seek, as it has a lower increment. Am not are why the non ;'seek' are both zero though  I would ahve thought you would also want to tune those much the same.

**Comment by spacerunner5** [comment]
Those settings seem systemwide and for distinguishing between rotating and non-rotating disks. But that is not the case / use case here as well as on previous question from @ingresso-pete I mentioned before: 

> to mirror a drive on a cloud machine to local instance SSD in order to speed up reads.

which leads to my question:

2 mirror disks, one fast (ssd, local) and one slow (ssd, remote)

can I somehow tell zfs to prefer the fast disk for reads?

**Comment by ingresso-pete** [comment]
Ah, apologies, yes, I misread!

I dont know of a way to do this in ZFS. I am wondering if there is a way you could stack a geom module on top of the remote one which would make it appear as if it was not an ssd, and then rely on the rotating vs non-rotating behaviour ? I cant think of one though. Maybe you could do it by sharing the drive as iscsi, using ctld, (which lets you set rotation speed) and then mounting it on localhost using iscsid... but that seems horribly over-engineered.

gmirror lets you select drive priorities, and I used to use that, but then you lose all the nice zfs features.

Am sorry, I dont have any other ideas I am afraid ;(
