### ISSUE TITLE
RFE: change new 'zpool list' -p flag to some other letter

### ISSUE THREAD

**Issue by siebenmann** [zfsonlinux/zfs#4368]
As of the just landed commit d2f3e292dccab23e47ade3c67677a10f353b9e85, 'zpool list' supports a -p flag to show vdev paths. Unfortunately this is an option clash with upstream ZFS, where -p is used with zpool and zfs commands to mean 'report precise integer values for disk space, not rounded numbers'. It would be nice if this option clash could be fixed, ideally by moving -p to another option letter.

(Implementing the upstream -p behavior is presumably another RFE.)

**Comment by behlendorf** [comment]
@siebenmann thanks for pointing this out right away.  I missed this conflict because we haven't ported those patches yet.  Yes I agree we'll want to change the option letter right away to remove the clash.  How do you feel about `-P`, or do you have a better suggestion.

**Comment by siebenmann** [comment]
-P sounds fine for me, especially since -L is already upper-cased. It might be useful to switch -g to -G as well, so all three options have uniform case.

**Comment by ilovezfs** [comment]
And they shall always appear in the order "GPL" :)

**Comment by dracwyrm** [comment]
@ilovezfs But it's activated with a '-' so it would -GPL...
Though that does go along with ZFS since it's not GPL. :(

**Comment by behlendorf** [comment]
Let's leave -g as it is.  I have the impression the original guid patch was fairly widely used so I'd like to avoid breaking anything which was already using it.
