### ISSUE TITLE
Difficulty building on Debian Sid with Grsecurity Kernel

### ISSUE THREAD

**Issue by ajhaydock** [zfsonlinux/zfs#4373]
Hopefully this is just something simple, but I am having difficulty building SPL/ZFS from source on Debian Sid with a 4.4.2 Grsec kernel, using the official guide [from the ZFS on Linux site](http://zfsonlinux.org/generic-deb.html).

I have followed the guide exactly, using the latest `0.6.5.4` packages from the ZFS on Linux site, and with the source from Git (both produce the same error).

Commands are being run as a standard (non-root) user.

All commands are successful, prior to the `make deb-utils deb-kmod` command, which appears to fail at a number of points attempting to build rpm packages. (I have attached a log of this command being run to compile SPL as [spl-log.txt](https://github.com/zfsonlinux/zfs/files/149073/spl-log.txt)). I have also attached [config.log](https://github.com/zfsonlinux/zfs/files/149077/config.log.txt) in case that is helpful too.

After this build attempt on a clean source directory, I am left with the following files which appear to have been compiled:
- spl_0.6.5.4-1_amd64.deb
- spl-0.6.5.4-1.src.rpm
- spl-kmod-0.6.5.4-1.src.rpm

I understand that it is attempting to build these packages as .rpm and then convert them to .deb files using alien, but cannot work out what file or package I am missing, or what part of the build process is failing.

I do not believe the issue is related to grsecurity itself, as no grsec errors are turning up in the syslog during the build process. I can also confirm that the directories that the build process is searching for my kernel sources within all appear to be present as expected.

Hopefully this is a simple issue of a missing package or something similar. (For what it's worth, Debian's `build-essential` package doesn't include `autoreconf`, so it might be helpful to add `dh-autoreconf` to the prerequisites installed at the start of the guide on the ZoL site, as I found myself needing to install that also).

I can attempt further testing or provide more logs/info if necessary. Thanks for any help you can provide.

**Update:** I'm now pretty certain this is an issue caused by the Grsec patchset, as I am getting the exact same error under the newly released Linux 4.4.3, and under Ubuntu 14.04 / 15.10.

I am going to try building under a Grsec kernel on a distro that is actually RPM based such as Fedora and report back with results.

**Comment by voidzero** [comment]
You can also try Gentoo-Hardened, or the derivative I use, Funtoo-Hardened. I've been running zfs on grsec-enabled kernels for a pretty long time without any issues. You can't enable certain options - that's when compilation will fail - but simply adding the patchset should not be reason for build failures to occur. I'd have to look up which of those options should be kept disabled (hopefully this will change one day), so please request if you want me to do so.

**Comment by rlaager** [comment]
This issue, as written, doesn't seem particularly actionable. Compiling an RPM on Debian and then converting to a .deb is non-standard. Debian has ZFS packaged now, so my first advice would be to try again with that. If that fails, then I'd suggest trying again with master.
