### ISSUE TITLE
grsec: cannot enter .zfs/snapshot/X

### ISSUE THREAD

**Issue by alexanderhaensch** [zfsonlinux/zfs#4377]
when trying to enter .zfs/snaphot/X i get:
`too many levels of symbolic links`

in dmesg there are alot of:

`grsec: denied exec of usermode helper binary /bin/sh located outside of permitted system paths
`
manual mount of the snapshots works

**Comment by GICodeWarrior** [comment]
What versions of ZFS, SPL, and Grsec?

**Comment by alexanderhaensch** [comment]
This happens with newer versions of ZFS/SPL from 0.6.5.3 and 0.6.5.4 and any Grsec from september to the newest.

**Comment by lazy404** [comment]
grsecurity bans using /bin/sh as an usermode helper which is called by snapshot mounter

You could use this to disable thiese checks
https://gist.github.com/lazy404/5888c3fa6747a605375e

**Comment by stiell** [comment]
Looks like grsec would allow using /sbin/mount.zfs directly and zfs is only using /bin/sh to redirect standard streams to /dev/null. Is this redirection necessary? Could it be done without /bin/sh?

**Comment by behlendorf** [comment]
@stiell good question.  It's my recollection that everything was redirected to /dev/null because it was the most cautious thing to do.  I don't believe it's required.  It would be interesting to try removing the /bin/sh requirement and open a PR with that change.  You'll want to get SET_UNMOUNT_CMD and SET_MOUNT_CMD.

**Comment by stiell** [comment]
This issue is what PR #1919 was trying to fix. It fixes mounting by calling `/sbin/mount.zfs` directly, but it has no fix for unmounting (`umount` is in `/bin`, which is not permitted by grsec).
