### ISSUE TITLE
zdb -e broken by 519129f

### ISSUE THREAD

**Issue by dweeezil** [zfsonlinux/zfs#4382]
Discovered by running ```zdb -e -p ...``` with current master code.  I've not looked into this too far but it seems the problem may be that both ```thread_init()``` is effectively called twice in ```main()``` in zdb.c.  Both the ```kernel_init()``` call it (directly) and ```find_zpool()``` (via ```zpool_search_import()```->```zpool_find_import_impl()```).

The failures show up as error returns from ```pthread_setspecific()```.

The culprit seems to be 519129f.

**Comment by tuxoko** [comment]
https://github.com/zfsonlinux/zfs/issues/4331

**Comment by dweeezil** [comment]
Oops, guess I didn't look closely enough.
