### ISSUE TITLE
bash completion triggering sudo prompt?

### ISSUE THREAD

**Issue by fallenguru** [zfsonlinux/zfs#4394]
Using Debian 8.3 jessie and
zfsonlinux   6
debian-zfs   7~jessie
zfsutils, libzfs2, zfs-dkms   0.6.5.2-2   
spl, spl-dkms   0.6.5-1
with sudo enabled.

Whenever I use bash's command completion for zfs or zpool and my sudo auth is not already cached, the completion itself will trigger a sudo prompt, e.g "sudo zfs get all cr[TAB]" will ask for a password right after the [TAB], which I find confusing.

I can see that listing pools/datasets might require root privileges but I'd much rather bash completion just fail silently if it can't get the info. Or maybe do the thing it does when the completion is ambiguous and output "# lacking privileges for getting ..." and "sorry" as "alternatives".

**Comment by behlendorf** [comment]
Thanks for the bug report.  I hope this is something we'll be able to address fairly soon by allowing non-root users to run `zpool list`, `zfs list`, and `zpool iostat`.  These don't need to be privileged commands.
