### ISSUE TITLE
very slow zfs receive (zfs process consumes too much cpu) with hundreds of recursive datasets and dozens of snapshots for each dataset

### ISSUE THREAD

**Issue by mailinglists35** [zfsonlinux/zfs#4395]
nmon, atop, zfs receive, perf top, cpuinfo - outputs included in the attached gif screencast.

![2016-03-08_19-51-12](https://cloud.githubusercontent.com/assets/2054302/13612129/ed9c99de-e576-11e5-8991-b14ce776a9a3.gif)

**Comment by kernelOfTruth** [comment]
Distro, kernel, hardware and other 

pool size, pool configuration, etc.

please


mutex_lock
raw_spin_unlock_irqrestore

are shown taking some share (~ 10% each)


glibc 2.19


HP Proliant dl320s gl
Xeon 3060 (?)

**Comment by mailinglists35** [comment]
debian jessie amd64
pool = 1 vdev = raidz3 8 x 500Gb + 4 hotspares x 500Gb
about 600 datasets

`zfs get all` and `zpool get all` coming up at next boot (the machine stays pretty much offline)

let me know exactly what else you need to know.
