### ISSUE TITLE
kmalloc-96 and kmalloc-512 slabs grow seemingly without bound

### ISSUE THREAD

**Issue by RichardSharpe** [zfsonlinux/zfs#4399]
Hi folks,

We are seeing the following issue when running long running tests.

These tests involve creating millions of files. Because we use Samba and have SeLinux enabled (boo, hiss) each file has one SeLinux XATTR (less than 96 bytes in length) and one NTFS ACLs XATTR that is less than 512-bytes in length. We are using xattr=SA.

After creating around 3.7 million files we see that the SLABs are now consuming around 5GB of memory, and the kmalloc-512 slab has some 1.3GB in it alone, and the kmalloc-96 slab is also large and growing.

The machine (a VM) becomes unusable not long after that because we only have 12GB of memory on those nodes.

It looks like these objects are being cached but never expired or evicted from the cache.

The kernel is 3.10.0-229 from CentOS 7.1.

Has anyone seen this? 

Is it likely in the ZPL layer or in the ZFS layer or deeper in?

**Comment by RichardSharpe** [comment]
In module/zfs/zpl_super.c:zpl_evict_inode:
```
static void
zpl_evict_inode(struct inode *ip)
{
        fstrans_cookie_t cookie;

        cookie = spl_fstrans_mark();
        truncate_setsize(ip, 0);
        clear_inode(ip);
        zfs_inactive(ip);
        spl_fstrans_unmark(cookie);
}
```

Should we be calling zfs_inode_destroy to cleanup and release resources tied to the ZNode?

**Comment by RichardSharpe** [comment]
Having looked at this some more and after looking at this comment:

https://github.com/zfsonlinux/spl/pull/213

and noticing that zfs_inode_alloc allocates memory for the znode from kmem_cache_alloc, and noticing that there is a call to zfs_inode_alloc from zpl_inode_alloc,

Also, I note this comment in zpl_super.c:
```
 * This elaborate mechanism was replaced by ->evict_inode() which
 * does the job of both ->delete_inode() and ->clear_inode().  It
 * will be called exactly once, and when it returns the inode must
 * be in a state where it can simply be freed.i
```

Which suggests that we should be _should_ be calling zfs_inode_destroy in zpl_evict_inode.

**Comment by RichardSharpe** [comment]
OK, after looking at fs/inode.c in the kernel we are using, I see that there is an explicit call to destroy_inode which should call zpl_inode_destroy which should cleanup the things hanging off of the znode.

I will look elsewhere to see what is going on.

**Comment by RichardSharpe** [comment]
We currently think we are seeing a deadlock during eviction. Checking stacks.

**Comment by RichardSharpe** [comment]
We are playing with deduping XATTRs and switched on verification. When we switched that off, this problem went away,

Closing for now.

**Comment by behlendorf** [comment]
@RichardSharpe sorry about the sluggish reply.  Without carefully investigating the code I'm not sure why switching off verification would resolve this but I'm glad you were able to somewhat explain this.  It would be nice to fully explain this at some point.

Regarding your xattr heavy workload with millions of files, I'd suggest trying the large dnode patch in #3542 which is getting close to finalized.  It was designed to improve performance and reduce pool fragmentation for exactly your workload.  As the name suggests it done this by increasing the dnode size which in conjunction with xattr=sa allows large xattrs to be co-located on disk with the dnode.

If you have a have test system for benchmarking myself and @nedbass would definitely be very interested if your results.  You'll want to enable the feature, set the dnode size to 1k, enabled xattr=sa, and then run your tests.
