### ISSUE TITLE
Website didn't tell the truth

### ISSUE THREAD

**Issue by ggzengel** [zfsonlinux/zfs#4402]
http://zfsonlinux.org/debian.html

> These packages track the latest official upstream tag and are refreshed as new releases are made available

**Comment by ptx0** [comment]
Is it considered poor form to publish debs compiled using `make deb`?

**Comment by behlendorf** [comment]
@ggzengel I've updated the website accordingly.  Unfortunately we've lost of package maintainer so these packages won't be getting frequent updates.  The good news is that the Debian project is working to provide them directly.

http://zfsonlinux.org/debian.html

@ptx0 `make deb` is going to produce slightly different packages.  This functionality is useful for testing and one-off installs but it doesn't conform to the normal Debian packaging guidelines.
