### ISSUE TITLE
Kernel panic on Shutdown/Reboot 

### ISSUE THREAD

**Issue by pludi** [zfsonlinux/zfs#4403]
Platform: VirtualBox 5.0.14 on Fedora 23 x86_64
OS: Debian 8 on x86_64
Kernel: 3.16.0-4-amd64
SPL: 0.6.5-1
ZFS: 0.6.5-1
Output: [Image](http://imagebin.ca/v/2ZsMfvuXnFAq)

System installed on ZFS root based on [this](https://github.com/zfsonlinux/pkg-zfs/wiki/HOWTO-install-Debian-GNU-Linux-to-a-Native-ZFS-Root-Filesystem) how-to, with adaptions for Jessie and /var dataset. On shutdown and reboot, the kernel panics. The only non-ZFS filesystem is a small partition for /boot.

**Comment by behlendorf** [comment]
@pludi this appears to be an ext4 issue.  The stack trace shows `ext4_commit_super()` as the suspect call path and include no mention of ZFS.

**Comment by pludi** [comment]
And I don't have an ext4 FS on that system. Just a small ext3 as /boot, unless that's handled by ext4-code too. But ultimately it's an ZoL issue, since that same bug doesn't appear on a regular Debian 8 without ZoL installed & set up. So the ZFS or SPL code is probably doing something that upsets the ext4 code.

One thing I haven't tried yet, for lack of time, is installing the current code base manually, as the packages apparently aren't updated anymore (#4408, zfsonlinux/pkg-zfs#181), and I need it working on Debian 8.

**Comment by behlendorf** [comment]
OK, well we can leave this issue open for reference but there is nothing really actionable here.  If you're able to come up with a canned reproducer or additional debugging directly implicating ZFS then we may be able to investigate further.  Sorry.

**Comment by pludi** [comment]
Finally had some time to dig into this issue.

Apparently, ext3 filesystems are handled by ext4 code in the kernel. For some reason, having that small boot partition causes the kernel panic, but only while it's active. When I unmount it prior to halting no panic happens. Also, no panic on reboot.

Filing a bug against Debian if it also happens with other non-ext roots, and will update this bug in case.
