### ISSUE TITLE
zfs allowing operations for all users

### ISSUE THREAD

**Issue by montanaviking** [zfsonlinux/zfs#4410]
Hi, I'm running zfs on linux and the command
zfs get version poolname
gives version 5
I'm running Ubuntu 14.04 64 bit
My problem is that it is possible to now run my zfs command set on ANY user that I log in as including the guest user. I don't need to log in as root or use sudo (as I think I had to in the past) to run any and all zfs and zpool commands and all these commands are now possible to all users on my system.
Of course this is a major security hole!
The command:
sudo zfs allow poolname
(where poolname is the name of my data pool)
gives a blank output.
How do I close this security hole and why is it like this?
Thanks,
Phil

**Comment by kpande** [comment]
```
% zfs list
Permission denied the ZFS utilities must be run as root.
```

Can you show output of `ls -al /dev/zfs` ?

**Comment by montanaviking** [comment]
$ ls -al /dev/zfs
crw-rw-rw- 1 root root 10, 57 Mar 12 21:03 /dev/zfs

Thanks!

**Comment by montanaviking** [comment]
and 
$ zfs list 
on my system produces a zfs listing (same result as $ sudo zfs list
Thanks,
Phil

**Comment by montanaviking** [comment]
Hi kpande, the content of
/etc/sudoers.d/zfs is:
## Allow read-only ZoL commands to be called through sudo
## without a password. Remove the first '#' column to enable.
##
## CAUTION: Any syntax error introduced here will break sudo.
##
## Cmnd alias specification
#Cmnd_Alias C_ZFS = \
#  /sbin/zfs "", /sbin/zfs help *, \
#  /sbin/zfs get, /sbin/zfs get *, \
#  /sbin/zfs list, /sbin/zfs list *, \
#  /sbin/zpool "", /sbin/zpool help *, \
#  /sbin/zpool iostat, /sbin/zpool iostat *, \
#  /sbin/zpool list, /sbin/zpool list *, \
#  /sbin/zpool status, /sbin/zpool status *, \
#  /sbin/zpool upgrade, /sbin/zpool upgrade -v
#
#Runas_Alias R_ROOT = root
#
## User privilege specification
#root    ALL=(ALL) ALL
#
## Members of the admin group may gain root privileges
#%adm ALL=(ALL) ALL  # linux
#%admin ALL=(ALL) ALL  # linux
#%staff ALL=(ALL) ALL  # solaris
#
## allow any user to use basic read-only ZFS commands
#ALL ALL = (R_ROOT) NOPASSWD: C_ZFS

Thanks,
Phil

**Comment by montanaviking** [comment]
No uncommented lines in the last posting thanks

**Comment by montanaviking** [comment]
Hi kpande again,
Thank you so much. I changed the permissions on /dev/zfs to 660 (it's owned by root:root) and now zfs commands can be executed only by root - which is exactly what I want!
I'm still wondering how this got set wrongly however.
And a lot of other files under /dev have the rw rw rw permissions still.
Thanks and best
Phil

**Comment by ilovezfs** [comment]
@montanaviking it could be a bad udev rule. https://github.com/zfsonlinux/zfs/issues/4100

**Comment by montanaviking** [comment]
Hi llovezfs,
I'm ignorant about udev rules for zfs. Any idea how to modify them so that my permissions changes are correct and permanent for zfs?
Thanks so much,
Phil

**Comment by behlendorf** [comment]
@montanaviking it's going to depend on your distribution.  But by default ZoL doesn't ship with any udev rules which would change the permissions on `/dev/zfs`, it relies on those provided by the distro which we don't have any control over.
