### ISSUE TITLE
PANIC at fnvpair.c:68:fnvlist_size()  when having 3 disks in a mirror, 1x1tb and 2x2tb, goes away when 1tb drive is removed AND 2x2tb expanded

### ISSUE THREAD

**Issue by ghost** [zfsonlinux/zfs#4411]
Hello,

the last week I had a failed drive in my mirror of 2x1tb.

As a consequence I "replaced" (zfs replace) the failed drive with a 2tb drive. Since I didn't boot the original system right then, I can't tell if this would have created the same panic seen below.

Afterwards, still acting from a sysresccd, I furthermore attached a second 2tb drive, making this a three-way mirror. After the resilvering successfully completed a second time I managed to boot into my system after downgrading to 0.6.5.3 (otherwise I got another error with newer versions when trying grub2-install, one of them Segmentation Fault).
## 

Info about my system:

Gentoo Linux, kernel 4.3.3-gentoo, zfs-kmod, zfs and spl all version 0.6.5.3.

While running my previous setup of 2x1tb mirror, i had the most recent version of 0.6.5.4-r1 running just fine.
## 

After the bootup was complete, roughly a few seconds afterwards, I got part of the following message displayed in my boot console.

Investigating /var/log/messages yielded this:

[1392.358658] VERIFY3(0 == nvlist_size(nvl, &size, 0)) failed (0 == 22)
[ 1392.358754] PANIC at fnvpair.c:68:fnvlist_size()
[ 1392.358841] Showing stack for process 11374
[ 1392.358844] CPU: 0 PID: 11374 Comm: zfs Tainted: P           O    4.3.3-gentoo #1
[ 1392.358845] Hardware name: System manufacturer System Product Name/P8H67-M PRO, BIOS 3904 04/27/2013
[ 1392.358847]  0000000000000000 ffff880545627bd8 ffffffff813887e3 ffffffffa002b9be
[ 1392.358850]  ffff880545627be8 ffffffffa00119e3 ffff880545627d78 ffffffffa0011a9c
[ 1392.358852]  ffff880545627d88 ffff880545627c50 ffff880500000030 ffff880545627d88
[ 1392.358854] Call Trace:
[ 1392.358860]  [<ffffffff813887e3>] dump_stack+0x44/0x55
[ 1392.358867]  [<ffffffffa00119e3>] spl_dumpstack+0x3d/0x3f [spl]
[ 1392.358870]  [<ffffffffa0011a9c>] spl_panic+0xb7/0xea [spl]
[ 1392.358874]  [<ffffffffa000d945>] ? spl_kmem_free+0x2c/0x2e [spl]
[ 1392.358879]  [<ffffffffa0013d92>] ? tsd_get+0xa6/0x113 [spl]
[ 1392.358883]  [<ffffffffa0013f6f>] ? tsd_set+0x170/0x3ab [spl]
[ 1392.358890]  [<ffffffffa0027b0a>] fnvlist_size+0x4d/0x55 [znvpair]
[ 1392.358915]  [<ffffffffa010bf0c>] zfs_secpolicy_smb_acl+0x621/0x4ffb [zfs]
[ 1392.358938]  [<ffffffffa01108ce>] zfs_secpolicy_smb_acl+0x4fe3/0x4ffb [zfs]
[ 1392.358959]  [<ffffffffa01132ad>] pool_status_check+0x6f9/0x7d4 [zfs]
[ 1392.358962]  [<ffffffff811354b6>] do_vfs_ioctl+0x36b/0x419
[ 1392.358965]  [<ffffffff81030263>] ? __do_page_fault+0x2be/0x338
[ 1392.358966]  [<ffffffff811355a2>] SyS_ioctl+0x3e/0x5c
[ 1392.358969]  [<ffffffff81653b17>] entry_SYSCALL_64_fastpath+0x12/0x6a

In order to try and fix this, I thought about what fnvlist_size() could be related to and went ahead to remove the 1tb drive from the three-way mirror, leaving it with unexpanded 2x2tb in a mirror.

The panic reappeared after reboot.

I set autoexpand to on and rebooted, same panic.

I expanded each disk manually, rebooted and the panic was gone.

I hope this helps and can be replicated, since obviously I can't provide further information - i guess.

Edit:
Forgot to mention, that the new 2tb drives have the following partition table:

Number  Start (sector)    End (sector)  Size       Code  Name
   1            2048         1026047   500.0 MiB   BE00  Solaris boot
   2         1026048         1091583   32.0 MiB    EF02  BIOS boot partition
   3         1091584      3907029134   1.8 TiB     BF00  Solaris root

Meaning 1first partition of both drives were in a zpool mirror. Thus problems installing grub2 on said mirror with newer versions than 0.6.5.3 (-r1, -r2, ... not tested, only -r5 and 0.6.5.4-r*).
So /boot is on the boot pool. data partitions of all three drives are encrypted using cryptsetup, once opened build the system pool housing / and /home.

**Comment by behlendorf** [comment]
Thanks for the detailed bug report so we can track this.
