### ISSUE TITLE
computer froze after scrub started & pool now always 100% full

### ISSUE THREAD

**Issue by shdw** [zfsonlinux/zfs#4412]
I have started a scrub yesterday night, this morning my computer was completely frozen.
I haven't found anything about zfs (nor anything else) that could have caused the freezing, so unable to be sure if the scrub froze the computer, but now my pool is always 100% full. I've deleted a few unimportant (but many GB-large) files and still marked as 100%, even after an unmount/re-mount and a reboot.

The scrub was still going on after a successful reboot & automatic pool re-importing, so I just stopped it to avoid any further write operations to the pool until this is resolved.

I'm running zfs & spl live ebuilds on gentoo. Let me know what else I can provide so that this bug filing helps you help me & find out if this is a bug or an unappropriately confgured zfs setup / zfs pool.

Thanks & Regards

**mediatheque shdw # zpool status brute**
  pool: brute
 state: ONLINE
  scan: scrub canceled on Sun Mar 13 12:57:52 2016
config:

        NAME        STATE     READ WRITE CKSUM
        brute       ONLINE       0     0     0
          raidz1-0  ONLINE       0     0     0
            sdb     ONLINE       0     0     0
            sdd     ONLINE       0     0     0
            sde     ONLINE       0     0     0
            sdf     ONLINE       0     0     0

errors: No known data errors

SMART short tests PASSED on all pool's drives, waiting for long test results (not expecting issues, but will update if any are coming up)

**Comment by shdw** [comment]
I have restarted scrubbing, as there were no error whatsoever in logs nor from SMART monitoring, and also because there is free space reported now by zpool list but it still says there's 0% available when using df.

**mediatheque shdw # df -h /brute/shdw**
Sys. de fichiers Taille Utilisé **Dispo** Uti% Monté sur
brute/prive/shdw   1,1T    1,1T     **0** 100% /brute/shdw

**"Dispo" means "Available"**


**mediatheque shdw # zpool list     **                                                                                   
NAME    SIZE  ALLOC   **FREE**  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
brute  7,25T  7,08T   **170G**         -    36%    97%  1.00x  ONLINE  -


**mediatheque shdw # zpool status brute **
  pool: brute
 state: ONLINE
  scan: scrub in progress since Sun Mar 13 15:34:36 2016
        1,43T scanned out of 7,08T at 221M/s, 7h26m to go
        0 repaired, 20,23% done
config:

        NAME        STATE     READ WRITE CKSUM
        brute       ONLINE       0     0     0
          raidz1-0  ONLINE       0     0     0
            sdb     ONLINE       0     0     0
            sdd     ONLINE       0     0     0
            sde     ONLINE       0     0     0
            sdf     ONLINE       0     0     0

errors: No known data errors

**Comment by shdw** [comment]
I assume that this quote, source [HERE](https://docs.oracle.com/cd/E23824_01/html/821-1448/gbchp.html), could potentially explain what is going on in my case:

> Out of Space Behavior
> 
> File system snapshots are inexpensive and easy to create in ZFS. Snapshots are common in most ZFS environments. For information about ZFS snapshots, see Chapter 7, Working With Oracle Solaris ZFS Snapshots and Clones.
> 
> The presence of snapshots can cause some unexpected behavior when you attempt to free disk space. Typically, given appropriate permissions, you can remove a file from a full file system, and this action results in more disk space becoming available in the file system. However, if the file to be removed exists in a snapshot of the file system, then no disk space is gained from the file deletion. The blocks used by the file continue to be referenced from the snapshot.
> 
> As a result, the file deletion can consume more disk space because a new version of the directory needs to be created to reflect the new state of the namespace. This behavior means that you can receive an unexpected ENOSPC or EDQUOT error when attempting to remove a file.

**Comment by richardelling** [comment]
"zpool list" shows the space used/available for the pool
"zfs list" shows the space used/available for file systems
There is a reserve space in the pool for intent logs, housekeeping, and allocation efficiency. This is a common feature of file systems. The amount reserved has varied over the years, but you can generally expect 2-4%.

**Comment by shdw** [comment]
I have yet to find out how to fix my available space issue. The scrubbing took nearly 15 hours to complete (which is normal for a 8TB pool on this machine), there were no errors encountered, but I still cannot write any data in my pool (except being able to delete files).

**mediatheque mnt # zpool status brute**
 ```
 pool: brute
 state: ONLINE
  scan: scrub repaired 0 in 14h47m with 0 errors on Mon Mar 14 06:21:48 2016
config:

        NAME        STATE     READ WRITE CKSUM
        brute       ONLINE       0     0     0
          raidz1-0  ONLINE       0     0     0
            sdb     ONLINE       0     0     0
            sdd     ONLINE       0     0     0
            sde     ONLINE       0     0     0
            sdf     ONLINE       0     0     0

errors: No known data errors
```
**mediatheque mnt # zpool list**
```
NAME    SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
brute  7,25T  7,08T   170G         -    36%    97%  1.00x  ONLINE  -
```

Any suggestions about how I could gain back the ability to write to my pool?

**Comment by behlendorf** [comment]
The only way to resolve your available space issue is to free up space in the pool.  One of the easiest ways to do this is to delete old snapshots you no longer need.  If you don't have any old snapshot then you'll need to free up space by removing files.

As a short term work around you can decrease the amount of reserved space held by the pool.  Although this isn't generally a good idea because this space is used for a variety of housekeeping purposes.  To do this set the `spa_slop_shift` module option to 6, this will reserve 1.6% of the total pool capacity.

**Comment by shdw** [comment]
Thanks @behlendorf 

I will play on the safe side and just continue sorting/deleting stuff until I get enough space to gain back the ability to write on it.

**Comment by behlendorf** [comment]
@shdw sounds good.  Let's chalk this one up to improved documentation and close it out.
