### ISSUE TITLE
0.6.5.6 release inclusion list [suggestions please]

### ISSUE THREAD

**Issue by kernelOfTruth** [zfsonlinux/zfs#4414]
Well, that's at least what I'd include ;)

-------------------------------------------

**optional**

https://github.com/zfsonlinux/zfs/commit/a0bd735adb1b1eb81fef10b4db102ee051c4d4ff Add support for asynchronous zvol minor operations

-------------------------------------------

https://github.com/zfsonlinux/zfs/issues/4404 zfs hanged when multiple operations on dataset
https://github.com/zfsonlinux/zfs/issues/3681 lock order inversion between zvol_open() and dsl_pool_sync()...zvol_rename_minors()

??

https://github.com/zfsonlinux/zfs/commit/1ee159f423b5eb3c4646b0ba2dd0fb359503ba90 Fix lock order inversion with zvol_open()

https://github.com/zfsonlinux/zfs/commit/5428dc51fb55145fbac1c142402dafc11d1e7d28 Make zvol minor functionality more robust

-------------------------------------------

https://github.com/zfsonlinux/zfs/commit/c352ec27d5c5ecea8f6af066258dfd106085eaac Illumos 6370 - ZFS send fails to transmit some holes

-------------------------------------------

https://github.com/zfsonlinux/zfs/commit/513168abd267f84ebcb688b4e1d42a2abd4fedce Make zvol update volsize operation synchronous.

-------------------------------------------

zpool, command changes:

https://github.com/zfsonlinux/zfs/commit/a77f29f93c8d016f17d9b77f39662e311774aaae Change full path subcommand flag from -p to -P

https://github.com/zfsonlinux/zfs/commit/d2f3e292dccab23e47ade3c67677a10f353b9e85 Add -gLp to zpool subcommands for alt vdev names

-------------------------------------------

https://github.com/zfsonlinux/zfs/commit/eea9309423d577d62cf62d1f98444e22e264ef15 Prevent zpool_find_vdev() from truncating vdev path

-------------------------------------------

https://github.com/zfsonlinux/zfs/commit/007595564ea8e28ca2e91e523f744821d021c465 Illumos 4448 - zfs diff misprints unicode characters

-------------------------------------------

https://github.com/zfsonlinux/zfs/commit/e989f19cba2beffb03351842c2da1409f68e4466 Correctly parse -R flag arguments

-------------------------------------------

https://github.com/zfsonlinux/zfs/commit/9d36cdb65089954baf649a8963f2129654c0b0b2 Handling negative dentries in a CI file system.

-------------------------------------------

https://github.com/zfsonlinux/zfs/commit/8a09d5fd463120ee5d527b4d40d029b37a0b8d6e Add l2arc_max_block_size tunable

-------------------------------------------

and some more ...

to-be-added

**Comment by odoucet** [comment]
Even if I was really expecting "async zvol minor operations", I consider this a major change, so not to be included in a bugfix release. I would prefer releasing a 0.6.6 version with such patches (and not wait for 0.7, because if I see the issues tracker, this version is not close to be released ...).

**Comment by Sachiru** [comment]
Perhaps this additional feature?

https://github.com/zfsonlinux/zfs/issues/4323

**Comment by behlendorf** [comment]
Thanks for starting this list so we can track possible patches to apply to the next point release.  I think some of these changes would be nice to have like async minors but are out of scope for a boring low risk point release.

Hopefully we can instead focus and getting an 0.7 release done.  Some of the items flag for that release may just need to be bumped to the next tag so we can get it released.

**Comment by Fabian-Gruenbichler** [comment]
Since #4404/#3681 seems to only be fixed with the "async zvol minor operations" cherry-picked as well, I would like to see it included in a release soon (if not 6.5.6, maybe 6.6 soon after?). This gets triggered pretty easily and has fatal consequences (all operations on the affected zpool hang, requiring a full reboot to fix).

**Comment by nedbass** [comment]
We released [0.6.5.6](https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.6.5.6) today.

Most of the above was included with the exception of these **[reasons in bold]**

8a09d5f Add l2arc_max_block_size tunable **[new feature]**
513168a Make zvol update volsize operation synchronous. **[rare bug and not enough time on master]**
0075955 Illumos 4448 - zfs diff misprints unicode characters **[cosmetic change, ZoL already has a fix]**

**Comment by kernelOfTruth** [comment]
@nedbass thanks for the explanation !

**Comment by Sachiru** [comment]
Thanks for the explanation. Please correct me if I'm wrong, but the
l2arc_max_block_size tunable should be okay, right? You're just waiting for
a feature release like 0.6.6 or 0.7, right?

Also, that code should be okay with the ABD work right?

**Comment by behlendorf** [comment]
@Sachiru right.  There's nothing wrong with the patch if you want to cherry pick it.  Just as a matter of policy new features aren't added to the stable release, this feature will appear in 0.7.
