### ISSUE TITLE
ZFS on linux and nvme SSDs

### ISSUE THREAD

**Issue by montanaviking** [zfsonlinux/zfs#4415]
Hi, Perhaps someone can tell me what I'm missing? 
I'm attempting to use a Samsung 950 EVO nvme SSD with ZFS on Linux and I could partition and see this drive with GParted.
However, the SSD produces only /dev/nvmexxxx listings and no listings anywhere under /dev/disk
When I try to perform:
$ (sudo) zpool create -n tank log nvme0n1p3
invalid vdev specification: at least one toplevel vdev must be specified
It appears that ZFS expects to find an entry under /dev/disk/xxx where xxx is by-id etc...?
Could someone kindly direct me as to how to get ZFS to find my SSD's partitions?
I've looked for quite some time on Google in vain.
Thanks so much,
Phil

**Comment by Sachiru** [comment]
You're creating a tank that contains no data drives, only log devices?

**Comment by montanaviking** [comment]
Please forgive me! I made a stupid mistake "create" should have been "add"
Thanks,
Phil

**Comment by kpande** [comment]
Hi Phil, I may suggest sending email to the [mailing list](http://list.zfsonlinux.org) next time :-)
