### ISSUE TITLE
ZFS show multiple process of spl_system_task, z_rd_iss, z_rd_int_0, z_wr_int_1 etc

### ISSUE THREAD

**Issue by cbovy** [zfsonlinux/zfs#4418]
ps aux show multiple processes of kernel tasks of ZFS. 
Is that behavior as expected?

Example of [z_wr_int_0]:
root      1573  0.0  0.0      0     0 ?        S<   Mar14   0:00 [z_wr_int_0]
root      1574  0.0  0.0      0     0 ?        S<   Mar14   0:00 [z_wr_int_0]
root      1575  0.0  0.0      0     0 ?        S<   Mar14   0:00 [z_wr_int_0]
root      1576  0.0  0.0      0     0 ?        S<   Mar14   0:00 [z_wr_int_0]
root      1577  0.0  0.0      0     0 ?        S<   Mar14   0:00 [z_wr_int_0]
root      1578  0.0  0.0      0     0 ?        S<   Mar14   0:00 [z_wr_int_0]
root      1579  0.0  0.0      0     0 ?        S<   Mar14   0:00 [z_wr_int_0]
root      1580  0.0  0.0      0     0 ?        S<   Mar14   0:00 [z_wr_int_0]
root      1581  0.0  0.0      0     0 ?        S<   Mar14   0:00 [z_wr_int_0]
root      1582  0.0  0.0      0     0 ?        S<   Mar14   0:00 [z_wr_int_0]
root      1583  0.0  0.0      0     0 ?        S<   Mar14   0:00 [z_wr_int_0]

Installed versions from Ubuntu PPA (http://ppa.launchpad.net/zfs-native/stable/ubuntu):
ii  libnvpair1                           0.6.5.5-1~wily                                     amd64        Solaris name-value library for Linux
ii  libuutil1                            0.6.5.5-1~wily                                     amd64        Solaris userland utility library for Linux
ii  libzfs2                              0.6.5.5-1~wily                                     amd64        Native OpenZFS filesystem library for Linux
ii  libzpool2                            0.6.5.5-1~wily                                     amd64        Native OpenZFS pool library for Linux
ii  spl                                  0.6.5.5-1~wily                                     amd64        Solaris Porting Layer utilities for Linux
ii  spl-dkms                             0.6.5.5-1~wily                                     all          Solaris Porting Layer kernel modules for Linux
ii  zfs-dkms                             0.6.5.5-1~wily                                     amd64        Native OpenZFS filesystem kernel modules for Linux
ii  zfs-doc                              0.6.5.5-1~wily                                     amd64        Native OpenZFS filesystem documentation and examples.
ii  zfsutils                             0.6.5.5-1~wily                                     amd64        Native OpenZFS management utilities for Linux

zpool status:
  pool: naspool
 state: ONLINE
  scan: none requested
config:

        NAME                                          STATE     READ WRITE CKSUM
        naspool                                       ONLINE       0     0     0
          raidz1-0                                    ONLINE       0     0     0
            ata-WDC_WD20EFRX-68EUZN0_WD-WCC4M6XKT7RK  ONLINE       0     0     0
            ata-WDC_WD20EFRX-68EUZN0_WD-WCC4M5DLN5X8  ONLINE       0     0     0
            ata-WDC_WD20EFRX-68EUZN0_WD-WCC4M3SKLKYH  ONLINE       0     0     0

errors: No known data errors

**Comment by behlendorf** [comment]
@cbovy yes, this is the expected behavior.  You can set the `spl_taskq_thread_dynamic=1` module option to reduce the number of idle threads, they will be created as needed.

```
       spl_taskq_thread_dynamic (int)
                   Allow  dynamic  taskqs.   When enabled taskqs which set the
                   TASKQ_DYNAMIC flag will by default  create  only  a  single
                   thread.  New threads will be created on demand up to a max‐
                   imum allowed number to facilitate the  completion  of  out‐
                   standing tasks.  Threads which are no longer needed will be
                   promptly destroyed.  By default this  behavior  is  enabled
                   but it can be disabled to aid performance analysis or trou‐
                   bleshooting.

                   Default value: 1
```
