### ISSUE TITLE
ZFS recursive snapshotting not working for zvols

### ISSUE THREAD

**Issue by davidbruzos** [zfsonlinux/zfs#4419]
After upgrading to ZFS 0.6.5.4 on Gentoo Linux with kernel 4.1.12-gentoo, the recursive snapshotting feature appears broken for zvols.  The destroy -r
+functionality appears to also be broken.  Here is an example scenario:

* Creating the sample structure:
```
    # zfs create tank/topdir
    # zfs create tank/topdir/subdir1
    # zfs create tank/topdir/subdir2
    # zfs create -V 10g -b 4k -s tank/topdir/subdir1/zvol1
    # zfs create -V 10g -b 4k -s tank/topdir/subdir2/zvol2
    # zfs snapshot -r tank/topdir@snap1
```

* Listing snapshots:
```
    # zfs list -r -t snap tank/topdir
    NAME                                USED  AVAIL  REFER  MOUNTPOINT
    tank/topdir@snap1              0      -    96K  -
    tank/topdir/subdir1@snap1      0      -    96K  -
    tank/topdir/subdir2@snap1      0      -    96K  -
```

* Trying to destroy structure:
```
    # zfs destroy -r tank/topdir
    cannot destroy 'tank/topdir/subdir1': dataset already exists
    cannot iterate filesystems: dataset already exists
```

* Comments:
    1. Notice that no snapshots were created for the zvols.
    2. The "zfs destroy -r" command fails with a confusing error.
 
I have not tried 0.6.5.5, but reading the release notes, it does not look like this issue was corrected.  The "snapshot -r" functionality is working fine in 0.6.5.3.  I install ZFS directly from portage, I have not tried downloading it directly from github.

If there is something I can test to help, let me know.

**Comment by ryao** [comment]
This is likely a regression in the stable API code. You can install sys-fs/zfs-0.6.5.4-r0 as a workaround until a new ebuild revision is fixed.

**Comment by davidbruzos** [comment]
Hello Richard, thank you for your suggestion.  I will give that a try and report back.

David

**Comment by davidbruzos** [comment]
Hello, sorry I took a while to get back.  I tested 0.6.5.4-r0 and it is working great, so it looks like Richard is right.  Thank you for your efforts!

David

**Comment by behlendorf** [comment]
@davidbruzos thanks for following up.  I'm closing this one out.
