### ISSUE TITLE
“inode with xattr in both SA and dir” warnings

### ISSUE THREAD

**Issue by SenH** [zfsonlinux/zfs#4428]
Since updating so 0.6.5.4 I'm receiving following warnings in kernel log:
```
WARNING: ZFS: inode ffff8800b918a840 has xattr "user.org.netatalk.Metadata" in both SA and dir
WARNING: ZFS: inode ffff8801e44741c0 has xattr "user.org.netatalk.Metadata" in both SA and dir
WARNING: ZFS: inode ffff8800c6558ec0 has xattr "user.org.netatalk.Metadata" in both SA and dir
WARNING: ZFS: inode ffff8801e4474a40 has xattr "user.org.netatalk.Metadata" in both SA and dir
WARNING: ZFS: inode ffff8801e4472840 has xattr "user.org.netatalk.Metadata" in both SA and dir
WARNING: ZFS: inode ffff8801ce995b40 has xattr "user.com.dropbox.attributes" in both SA and dir
WARNING: ZFS: inode ffff8801ce574a40 has xattr "user.com.dropbox.attributes" in both SA and dir
```
Is this something to be worried about?
How can I retrieve the ZFS dataset where the inode address points to?

**Comment by rlaager** [comment]
Did you set or unset xattr=sa some time after the dataset was initially created?

**Comment by SenH** [comment]
The root dataset was originally created before xattr=sa existed. When I upgraded the pool from RAIDZ1 to RAIDZ2. I initialized the RAIDZ2 root dataset with xattr=sa and transferred the data with `zfs send`.

I just looked up the pool creation date with `zfs history ` and it's 2014-10-03.

**Comment by rlaager** [comment]
I'm not 100% positive, but the warning suggests to me that you have files which had xattrs set pre-SA, then you changed the setting, and then the same files had xattrs set again after.

**Comment by SenH** [comment]
That could be the case indeed.

I want to know which file the warnings are referring to but you need the ZFS dataset and the inode number in order the retrieve the filename with `zdb -dddd [dataset] [object]`. The ZFS dataset is missing from the warning.

The code which generates the warning was added end of 2015 and it should automatically fix the issue (but only warning is displayed)
https://github.com/zfsonlinux/zfs/commit/a08add3067e5ebecbae6a7da5bd967c5dbbf2ef2
