### ISSUE TITLE
dbuf_read_impl(): return (SET_ERROR(err)) when err can be 0

### ISSUE THREAD

**Issue by thegreatgazoo** [zfsonlinux/zfs#4430]
Introduced by commit https://github.com/zfsonlinux/zfs/commit/5f6d0b6f5aa9af2ee5be74ac415a574b732c2c0f

Which adds lots of noise in tracing, e.g.:
```
<...>-122063 [055] .... 81868.335600: zfs_set__error: dbuf.c:728:dbuf_read_impl(): error 0x0
```

**Comment by behlendorf** [comment]
@thegreatgazoo let's just convert this to a `return (err);` to avoid the noise.

**Comment by behlendorf** [comment]
@thegreatgazoo if you have a minute can you open a new PR for this.
