### ISSUE TITLE
zpool add doesn't check ashift validity.

### ISSUE THREAD

**Issue by whiskerface** [zfsonlinux/zfs#4434]
Debian 8/Jessie
ZFS|SPL module version: 0.6.5.4-1

Trying to create a pool with an ashift value larger than 13 will yield an error.

> cannot create 'testing': property 'ashift' number 14 is invalid.

However if you later add a vdev to this pool it doesn't check the validity of the ashift value.

```
History for 'testing':
zpool create -o ashift=12 testing mirror /mnt/file0 /mnt/file1
zpool add -o ashift=15 testing mirror /mnt/file2 /mnt/file3
zpool add -o ashift=20 testing mirror /mnt/file4 /mnt/file5
```

Discovered after i made a typo when doing `zpool add` where the ashift value was `1e` instead of `13`.
Causing the pool to lock up and become un-importable. `zdb|grep ashift` returned `ashift: 1152921504606846976` for the devices in that vdev.

**Comment by voidzero** [comment]
This is actually a pretty important bug imo

**Comment by voidzero** [comment]
Great, thanks! :+1:
