### ISSUE TITLE
Test case: reservation_013_pos

### ISSUE THREAD

**Issue by avg-I** [zfsonlinux/zfs#4444]
Test case reservation_013_pos ksh integer variables may overflow.

I am running the test suite with `DISKS` variable pointing to a bunch of 40GB disks.
I am getting the following failure:

```
Test: /usr/share/zfs/zfs-tests/tests/functional/reservation/reservation_013_pos (run as root) [00:01] [FAIL]
...
Reservation property for testpool.16466/testvol16072 incorrect. Expected  -320274432 but got 8530165760.
```

It seems that ksh integer variables (declared with `typeset -i`) have maximum value of 2^31 - 1 (even on an amd64 system).  So, calculations done with ksh's `((...))` mechanism may overflow.

**Comment by behlendorf** [comment]
Nice analysis, if you come up with a good fix for this please open a PR!

**Comment by bunder2015** [comment]
Just looking through old ZTS issues, is this still the case for ksh `((...))` ?  Maybe we could switch to `typeset -il`

```
chris@bloomfield ~ $ cat test.sh
#!/bin/ksh

((int0 = 2**31))
typeset -i int1=2**31
typeset -il int2=2**31

echo $int0
echo $int1
echo $int2

chris@bloomfield ~ $ ./test.sh
2147483648
-2147483648
2147483648
```

**Comment by behlendorf** [comment]
That looks like an entirely reasonable way to fix this as long as the versions of `ksh` we're using to test with support it. It would be great if you could update the test case and verify the fix.
