### ISSUE TITLE
zfs test suite: partition names are incorrect for real disks

### ISSUE THREAD

**Issue by avg-I** [zfsonlinux/zfs#4447]
Currently there is an assumption that partitions are named like _disk_**p**_i_, but that seems to be true only if _disk_ ends with a digit like `loop1` and then a partition name could be `loop1p1`.
But for real disks like `sdb` the partition name would actually be, for example, `sdb1`.
The code should be smarter about that. Probably it should inspect `DISKS` value.

**Comment by behlendorf** [comment]
Yes, this is code I was intending to add but I ran out of steam.  I think a helper function added to `tests/zfs-tests/include/libtest.shlib` which generates the right suffix given a patch is the way to go.  The `zfs_append_partition()` function in lib/libzfs/libzfs_util.c already contains an implementation of this logic in C.  It just needs to be translated to ksh and then all the hard coded locations its needed have to be updated.
