### ISSUE TITLE
zfs 0.6.5.6 build failure on aarch64, 4.4.0 Linux kernel, Ubuntu Xenial.

### ISSUE THREAD

**Issue by ColinIanKing** [zfsonlinux/zfs#4448]
Building zfs 0.6.5.6 on aarch64 4.4.0 snapdragon, I'm getting the following build failure:

make[5]: Entering directory '/home/ubuntu/0.6.5.6/zfs-linux-0.6.5.6/lib/libspl/asm-generic'
gcc -DHAVE_CONFIG_H -include ../../../zfs_config.h -I../../../lib/libspl/include  -D_GNU_SOURCE -D__EXTENSIONS__ -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DTEXT_DOMAIN=\"zfs-linux-user\" -DLIBEXECDIR=\"/usr/lib/zfs-linux\" -DRUNSTATEDIR=\"/var/run\" -DSBINDIR=\"/sbin\" -DSYSCONFDIR=\"/etc\"  -DNDEBUG -Wall -Wstrict-prototypes -Wno-unused-but-set-variable -Wno-bool-compare -fno-strict-aliasing -g -O2 -fPIC -c -S atomic.c -o atomic.S
In file included from /usr/include/aarch64-linux-gnu/sys/procfs.h:32:0,
                 from /usr/include/aarch64-linux-gnu/sys/ucontext.h:26,
                 from /usr/include/signal.h:326,
                 from /usr/include/aarch64-linux-gnu/sys/param.h:28,
                 from ../../../lib/libspl/include/sys/param.h:30,
                 from ../../../lib/libspl/include/sys/types.h:33,
                 from ../../../lib/libspl/include/atomic.h:30,
                 from atomic.c:27:
../../../lib/libspl/include/sys/time.h:61:8: error: unknown type name ‘hrtime_t’
 extern hrtime_t gethrtime(void);
        ^
../../../lib/libspl/include/sys/time.h:62:25: error: unknown type name ‘timestruc_t’
 extern void gethrestime(timestruc_t *);
                         ^
I don't get the issue on other architectures.  Not sure why this is happening on just this arch.

**Comment by behlendorf** [comment]
@ColinIanKing we have a tiny fix for this in master, you'll want to cherry pick d76d9c696a79b07a4d874f20855d8828d84f03f6. I'll make a note to get this one in the next tag.

**Comment by ColinIanKing** [comment]
Thanks, that does the trick!

**Comment by behlendorf** [comment]
Excellent.  I've cherry picked it on to the release branch so it's certain to make the next point release when enough small fixes like this have accumulated.
