### ISSUE TITLE
Mounting fuse file systems makes ZFS file systems dissapear

### ISSUE THREAD

**Issue by jonwedell** [zfsonlinux/zfs#4469]
I've just updated to the v0.6.5.6 release and am having an issue where mounting anything with fuse makes some of my ZFS file systems disappear:

```bash
jon@server:~$ sudo zfs list
NAME                     USED  AVAIL  REFER  MOUNTPOINT
zdrive                  3.76T  4.05T   213K  /zdrive
zdrive/NAS              3.37T  4.05T  2.97T  /zdrive/NAS
zdrive/server           13.7G  4.05T  7.50G  /zdrive/server
...
zdrive/encrypted_homes  16.3G  4.05T  5.13G  /home

jon@server:~$ ls /zdrive/NAS/
ebooks  music  photo  video
jon@server:~$ cd /tmp/
jon@server:/tmp$ mkdir tmp
jon@server:/tmp$ sshfs jon@localhost:/var tmp
jon@server:/tmp$ ls tmp/
backups  cache	crash  lib  local  lock  log  mail  metrics  opt  run  spool  subsonic	tmp
jon@server:/tmp$ ls /zdrive/NAS/
jon@server:/tmp$ sudo zfs mount -a
jon@server:/tmp$ ls /zdrive/NAS/
jon@server:/tmp$ fusermount -u tmp
jon@server:/tmp$ ls /zdrive/NAS/
```

And now there is nothing in /zdrive/NAS or any of my other ZFS file systems that are mounted under /zdrive. One file system is still accessible - the one that is mounted at /home.

Furthermore, after I trigger this issue I cannot export the pool:

```bash
jon@server:/tmp$ sudo zpool export zdrive
umount: /zdrive/server: not mounted
cannot unmount '/zdrive/server': umount failed
jon@server:/tmp$ sudo zfs mount -a
filesystem 'zdrive/server' is already mounted
cannot mount 'zdrive/server': mountpoint or dataset is busy
jon@server:/tmp$ sudo zpool export zdrive
umount: /zdrive/private: not mounted
cannot unmount '/zdrive/private': umount failed
```
I have to reboot to fix the issue.

I can easily reproduce the issue if there is anything else you need to me to do to see where the problem is.

This is on Ubuntu 14.04.4 LTS.

**Comment by kernelOfTruth** [comment]
What fuse filesystems are we talking about here ?

what FUSE version ?

I used jmtpfs (MTP, FUSE) and didn't observe these kind of issues,

more details please

**Comment by jonwedell** [comment]
I noticed the issue originally with a python FUSE file system that I wrote that uses [fuse.py](https://github.com/terencehonles/fusepy) then was able to verify that the issue also happens with sshfs.

Here are the versions of the relevant packages:

```bash
jon@server:~$ sshfs --version
SSHFS version 2.5
FUSE library version: 2.9.2
fusermount version: 2.9.2
using FUSE kernel interface version 7.19
```

**Comment by jonwedell** [comment]
I was finally able to get the pool to export and import. After doing so I can no longer reproduce the issue.
