### ISSUE TITLE
Temporary relatime=on acts like relatime=off

### ISSUE THREAD

**Issue by tspivey** [zfsonlinux/zfs#4470]
Contrary to what I read from man zfs on a freshly installed Ubuntu 16.04 snapshot, relatime doesn't work like I think it should if its source is temporary.

```
[    7.111075] ZFS: Loaded module v0.6.5.4-0ubuntu2, ZFS pool version 5000, ZFS filesystem version 5
root@storage:~# zfs get atime,relatime test
NAME  PROPERTY  VALUE     SOURCE
test  atime     on        default
test  relatime  on        temporary
root@storage:~# mount | grep /test
test on /test type zfs (rw,relatime,xattr,noacl)
root@storage:/test# touch file;stat -c%x file
2016-03-28 12:01:57.520703028 -0700
root@storage:/test# cat file;stat -c%x file
2016-03-28 12:02:12.280575497 -0700
```

Every time I run the last command line, my atime updates.
I expect the atime to stay the same since relatime is on, and I get this behaviour if I turn relatime on with zfs set relatime=on test.
However, my understanding is that if relatime is on and temporary, it should act like it's on until changed.

**Comment by loli10K** [comment]
This seems to be already fixed by https://github.com/zfsonlinux/zfs/commit/0df9673f01e8c52d882502d62789fa66efc327e2.
