### ISSUE TITLE
Assertion `pthread_create ...` failed when using zdb -i

### ISSUE THREAD

**Issue by ioquatix** [zfsonlinux/zfs#4472]
I was deleting a lot of files on my server. Something strange happened and I had to reboot. Then, on booting, I waited over 1.5 hours to mount but it didn't. Finally, I reboot ins ignore user mode. Most of the ZFS pools have mounted, but the tank/backup pool is stuck. It appears the disk is still processing. Occasionally the free space changes (increases) which makes sense since I was deleting a lot of old backups.

What I didn't expect was that running `zdb -i` to fail. See the attached image.

![img_6864](https://cloud.githubusercontent.com/assets/30030/14101646/3c4d3580-f5f2-11e5-9956-195a8be8a9d4.jpg)

Perhaps this is a bug?

**Comment by behlendorf** [comment]
@ioquatix this slipped in to master briefly but was resolved by commit 505d9655c9e759a145b4812c654c51c34dbe3425.  It should never have appeared in 0.6.5.x so you must be running additional patches there.

**Comment by ioquatix** [comment]
I'm just using the versions shown on the screen. They are from git however, so yes, not totally stable.

**Comment by behlendorf** [comment]
@ioquatix then if you don't mind I'd like to close out this issue as fixed.  The issue was addressed in master and you should pick up a fix the next time those packages get updated.
