### ISSUE TITLE
zfs mount/unmount very flaky

### ISSUE THREAD

**Issue by jimsalterjrs** [zfsonlinux/zfs#4473]
This seems to crop up most often in relation to replication - I zfs umount datasets prior to replication, then zfs mount them afterward, and it pretty frequently fails oddly.  The replication itself works fine, but zfs is confused as hell about whether or not the dataset is actually mounted.  Observe:

```
root@hs0:/# zfs mount | grep apps
data/images/appserver  /data/images/appserver
```

OK, zfs claims data/images/appserver is mounted. But do we see any data in it?

```
root@hs0:/# ls /data/images/appserver
root@hs0:/#
```

Nope.  So it's _not_ really mounted.  So let's mount it:

```
root@wings-ny-hs0:/# zfs mount data/images/appserver
cannot mount 'data/images/appserver': filesystem already mounted
```

Whaddaya mean, already mounted? It clearly isn't!  Fine then, let's unmount it:

```
root@hs0:/# zfs umount data/images/appserver
umount: /data/images/appserver: not mounted
cannot unmount '/data/images/appserver': umount failed
```

now you're just fscking with me. >=[ 

But now that we've unmounted the filesystem said it was mounted, and gotten an error because it also apparently also wasn't mounted, we can actually mount it and see the data:

```
root@hs0:/# zfs mount data/images/appserver
root@hs0:/# ls /data/images/appserver
win2012R2-GOLD.qcow2
```

This is on Ubuntu Trusty 14.04 LTS, running libzfs2 0.6.5.6-1~trusty.  This bug has been biting me in the ass for quite some time now, it's just been a small enough nibble that I haven't reported it until now.  (sorry about the delay, I really should have filed it close to a year ago.)

**Comment by jimsalterjrs** [comment]
This bug is getting to be more and more of a problem.  I turned strict error checking on with `or die` pragma in `syncoid`, which is now causing replication to fail due to this bug.  Example:

````
root@banshee:/tmp# /usr/local/bin/syncoid -r banshee/images root@192.168.100.10:data/backup/jrs/banshee/imagesSending incremental banshee/images@syncoid_banshee_2016-05-25:04:18:02 ... syncoid_banshee_2016-05-25:16:48:29 (~ 4 KB):
8.84kB 0:00:00 [ 122kB/s] [=================================================================] 220%            
filesystem 'data/backup/jrs/banshee/images/freebsd' can not be mounted due to error 22
cannot mount 'data/backup/jrs/banshee/images/freebsd': Invalid argument
property may be set but unable to remount filesystem
CRITICAL ERROR: /usr/bin/ssh -c arcfour -S /tmp/syncoid-root-root@archivist-1464209307 root@archivist  /sbin/zfs set readonly=on data/backup/jrs/banshee/images/freebsd died: 256 at /usr/local/bin/syncoid line 498.
````

You can see the bug in action directly with individual commands.

````
root@banshee:/tmp# ssh root@archivist zfs set readonly=on data/backup/jrs/banshee/images/freebsd
filesystem 'data/backup/jrs/banshee/images/freebsd' can not be mounted due to error 22
cannot mount 'data/backup/jrs/banshee/images/freebsd': Invalid argument
property may be set but unable to remount filesystem
root@banshee:/tmp# ssh root@archivist zfs set readonly=off data/backup/jrs/banshee/images/freebsd
filesystem 'data/backup/jrs/banshee/images/freebsd' can not be mounted due to error 22
cannot mount 'data/backup/jrs/banshee/images/freebsd': Invalid argument
property may be set but unable to remount filesystem
````

I'm unable to set readonly either on or off on the filesystem due to this bug.  The very temporary workaround is to unmount the filesystem, which itself is buggy and errors out:

````
root@banshee:/tmp# ssh root@archivist zfs umount data/backup/jrs/banshee/images/freebsd
umount: /data/backup/jrs/banshee/images/freebsd: not mounted
cannot unmount '/data/backup/jrs/banshee/images/freebsd': umount failed
````

Then you can remount it, and changing the value of `readonly` will succeed:

````
root@banshee:/tmp# ssh root@archivist zfs mount data/backup/jrs/banshee/images/freebsd
root@banshee:/tmp# ssh root@archivist zfs set readonly=on data/backup/jrs/banshee/images/freebsd
````

This is *extremely* obnoxious, and basically means I have to ignore errors if I want to successfully replicate unattended.  Please consider upgrading the label on this bug.

**Comment by jefft** [comment]
Similar symptoms (ZFS confused over mount status) with ZoL 0.6.5.6 on Ubuntu 16.04:
```
root@jturner-desktop:~# zfs mount tank/dotfiles
filesystem 'tank/dotfiles' is already mounted
cannot mount 'tank/dotfiles': mountpoint or dataset is busy
root@jturner-desktop:~# 
root@jturner-desktop:~# ls /dotfiles
root@jturner-desktop:~# 
root@jturner-desktop:~# zfs list -o name,mountpoint,mounted tank/dotfiles
NAME           MOUNTPOINT  MOUNTED
tank/dotfiles  /dotfiles        no
```
In my case I think it was triggered by my use of ZFS-enabled LXC containers. I had previously run the command:
```
lxc config device add "$containername" shared-dotfiles disk source=/dotfiles path=/root/lib/dotfiles
```
Then after some container stopping/starting, the NFS mount of `tank/dotfiles` hung, and when I investigated I found this situation.

**Comment by jimsalterjrs** [comment]
I'm still having occasional issues with mountpoint flakiness on various pools. In a couple of extreme cases I've had to destroy datasets entirely and recreate them because they'd report themselves mounted twice in the same place - you could `zfs umount` it once, and it would complete with no error... but it would still be mounted, this time with only *one* entry showing in the output of `zfs mount`, and now it would error on any issue of `zfs mount` *or* `zfs umount`.

The last time this happened, even exporting and importing the pool didn't clear the bugged dataset; I had to destroy it and recreate it.  Happily it was an otherwise-empty "parent" dataset so I could just rename a bunch of things around, but it was still annoying in the extreme.

**Comment by yaniv-aknin** [comment]
I think this just happened to me too; 4.10.0-28-generic, Ubuntu 17.04. Let me know if there's any other diagnostics I can provide.

**Comment by loli10K** [comment]
This might not even be a ZFS bug after all:

```
root@linux:~# POOLNAME='testpool'
root@linux:~# TMPDIR='/var/tmp'
root@linux:~# mountpoint -q $TMPDIR || mount -t tmpfs tmpfs $TMPDIR
root@linux:~# fallocate -l 64m $TMPDIR/zpool.dat
root@linux:~# zpool create -f -O mountpoint=none $POOLNAME $TMPDIR/zpool.dat
root@linux:~# zfs create -o mountpoint=$TMPDIR/ne/st/ed $POOLNAME/nested
root@linux:~# # mask the mount point
root@linux:~# mount -t tmpfs tmpfs $TMPDIR/ne
root@linux:~# # cannot umount
root@linux:~# zfs umount $POOLNAME/nested
umount: /var/tmp/ne/st/ed: mountpoint not found
cannot unmount '/var/tmp/ne/st/ed': umount failed
root@linux:~# # cannot mount
root@linux:~# zfs mount $POOLNAME/nested
cannot mount 'testpool/nested': filesystem already mounted
root@linux:~# 
root@linux:~# df -t zfs
df: no file systems processed
root@linux:~# df -t zfs -a
Filesystem      1K-blocks  Used Available Use% Mounted on
testpool/nested         -     -         -    - /var/tmp/ne/st/ed
```

The underlying issue is the umount syscall returning ENOENT:

```
root@linux:~# strace -qf -e trace=execve,umount zfs umount $POOLNAME/nested
execve("/usr/sbin/zfs", ["zfs", "umount", "testpool/nested"], [/* 14 vars */]) = 0
[pid  6899] execve("/bin/umount", ["/bin/umount", "-t", "zfs", "/var/tmp/ne/st/ed"], [/* 14 vars */]) = 0
[pid  6899] umount("/var/tmp/ne/st/ed", 0) = -1 ENOENT (No such file or directory)
umount: /var/tmp/ne/st/ed: mountpoint not found
[pid  6899] +++ exited with 32 +++
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=6899, si_uid=0, si_status=32, si_utime=0, si_stime=0} ---
cannot unmount '/var/tmp/ne/st/ed': umount failed
+++ exited with 1 +++
root@linux:~# 
```

This also happens with ext, so i don't think it's a ZFS bug:

```
root@linux:~# uname -r
4.6.4
root@linux:~# fallocate -l 64m $TMPDIR/ext_1.dat
root@linux:~# fallocate -l 64m $TMPDIR/ext_2.dat
root@linux:~# yes | mkfs $TMPDIR/ext_1.dat &> /dev/null
root@linux:~# yes | mkfs $TMPDIR/ext_2.dat &> /dev/null
root@linux:~# mkdir -p /mnt/ne/sted
root@linux:~# mount $TMPDIR/ext_1.dat /mnt/ne/sted
root@linux:~# mkdir -p /mnt/ne/
root@linux:~# mount $TMPDIR/ext_2.dat /mnt/ne/
root@linux:~# # try to umount
root@linux:~# umount /mnt/ne/sted
umount: /mnt/ne/sted: mountpoint not found
root@linux:~# # try to mount
root@linux:~# mount $TMPDIR/ext_1.dat /mnt/ne/sted
mount: /var/tmp/ext_1.dat is already mounted
root@linux:~# 
```

**Comment by jimsalterjrs** [comment]
Wow. Um, who should it be reported to upstream, then?  I get that it's not a ZFS bug, but it sure as hell is an annoying bug; seems we ought to do the right thing and report it where it counts.

**Comment by Redsandro** [comment]
I'm running into this. Did anyone of you figure out a way to 'clean' this up without rebooting the server?

```
$ sudo zfs mount pool/backups
filesystem 'pool/backups' is already mounted
cannot mount 'pool/backups': mountpoint or dataset is busy
$ sudo zfs unmount pool/backups
cannot unmount 'pool/backups': not currently mounted
```

**Comment by Redsandro** [comment]
Figured it out.

```
$ grep backups /proc/*/mounts
/proc/1052/mounts:pool/backups /backups zfs rw,xattr,noacl 0 0
/proc/32352/mounts:pool/backups /backups zfs rw,xattr,noacl 0 0
/proc/8378/mounts:pool/backups /backups zfs rw,xattr,noacl 0 0
```

Not sure why `zfs list` shows this as `mounted=no`

**Comment by StefanAbl** [comment]
Hi, I seem to have the same issue. It always happens when trying to restart Containers/VMs in Proxmox.
```
umount: /Volume1/subvol-126-disk-0: mountpoint not found
TASK ERROR: zfs error: cannot unmount '/Volume1/subvol-126-disk-0': umount failed
```
This is the error from the Proxmox GUI. After some further testing this hints at a similiar problem like the one described in this thread. 

```
root@proxmox:~# zfs unmount Volume1/subvol-126-disk-0
umount: /Volume1/subvol-126-disk-0: not mounted
cannot unmount '/Volume1/subvol-126-disk-0': umount failed
root@proxmox:~# zfs mount Volume1/subvol-126-disk-0
cannot mount 'Volume1/subvol-126-disk-0': filesystem already mounted
root@proxmox:~# zfs list Volume1/subvol-126-disk-0
NAME                        USED  AVAIL  REFER  MOUNTPOINT
Volume1/subvol-126-disk-0   721M  7.30G   721M  /Volume1/subvol-126-disk-0
root@proxmox:~# ls /Volume1/subvol-126-disk-0/ #empty 
```
Also doing
`grep subvol-126-disk-0 /proc/*/mounts`
Lists what seems like every process on the system. 

Sorry for commenting on this closed issue, but I don't know where else this would fit.

**Comment by woffs** [comment]
Yeah, still there with 0.8.1 here

**Comment by woffs** [comment]
false alarm. it turns out that the zfs datasets, e.g. /var/www, were mounted before /var (a non-zfs volume) was mounted. No ZFS problem, just a unix/systemd/adminstration problem.
