### ISSUE TITLE
 FS_IOC_GETFLAGS fails on big endian powerpc64

### ISSUE THREAD

**Issue by ColinIanKing** [zfsonlinux/zfs#4475]
On 64 bit big endian powerpc64 I am getting ENOTTY (Inappropriate ioctl for device) when performing the FS_IOC_GETFLAGS ioctl on a file on ZFS.  This ioctl works fine on other 64 bit platforms, so I suspect there is an issue with the way big endian ints/longs are being passed to ZFS via the ioctl().

I've got a very simple reproducer that creates a file "test" and performs the ioctl() on the file; on the powerpc64 I'm getting -ENOTTY.  Looking at zpl_ioctl() I suspect the int cmd is not being handle correctly for this cmd hence getting the ENOTTY default case.

```
static long
zpl_ioctl(struct file *filp, unsigned int cmd, unsigned long arg)
{
        switch (cmd) {
        case FS_IOC_GETFLAGS:
                return (zpl_ioctl_getflags(filp, (void *)arg));
        case FS_IOC_SETFLAGS:
                return (zpl_ioctl_setflags(filp, (void *)arg));
        default:
                return (-ENOTTY);
        }
}
```

Reproducer below:

```
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/ioctl.h>
#include <fcntl.h>
#include <errno.h>
#include <string.h>

#define FS_IOC_GETFLAGS                 _IOR('f', 1, long)

int main(int argc, char **argv)
{
	int fd;
	int flags;

	fd = open("test", O_CREAT | O_RDWR, 0755);
	if (fd < 0) {
		fprintf(stderr, "open: errno=%d (%s)\n", errno, strerror(errno));
		exit(1);
	}
	if (ioctl(fd, FS_IOC_GETFLAGS, &flags) < 0) {
		fprintf(stderr, "ioctl: errno=%d (%s)\n", errno, strerror(errno));
		exit(1);
	}
	
	close(fd);

	exit(0);
}```

**Comment by ColinIanKing** [comment]
Just to add, this is zfs 0.6.5.6, with a 4.4 kernel

**Comment by behlendorf** [comment]
@ColinIanKing sounds like a good guess.  Let's dump the exact values of `cmd`, `FS_IOC_GETFLAGS`, FS_IOC_SETFLAGS from the kernel side and have a look.  Could you add the following debug to the kernel module.

```diff
diff --git a/module/zfs/zpl_file.c b/module/zfs/zpl_file.c
index a23bc7d..0231771 100644
--- a/module/zfs/zpl_file.c
+++ b/module/zfs/zpl_file.c
@@ -784,6 +784,9 @@ zpl_ioctl_setflags(struct file *filp, void __user *arg)
 static long
 zpl_ioctl(struct file *filp, unsigned int cmd, unsigned long arg)
 {
+       dprintf("zpl_ioctl() cmd=%u FS_IOC_GETFLAGS=%u FS_IOC_SETFLAGS=%u\n",
+           cmd, (unsigned)FS_IOC_GETFLAGS, (unsigned)FS_IOC_SETFLAGS);
+
        switch (cmd) {
        case FS_IOC_GETFLAGS:
                return (zpl_ioctl_getflags(filp, (void *)arg));
```

Then enable the internal ZFS debug message log, run your reproducer, and dump the log.

```
echo 1 >/sys/module/zfs/parameters/zfs_dbgmsg_enable
./reproducer
cat /proc/spl/kstat/zfs/dbgmsg
```

**Comment by ColinIanKing** [comment]
zpl_ioctl() cmd=1074030081 FS_IOC_GETFLAGS=1074292225 FS_IOC_SETFLAGS=2148034050

**Comment by ColinIanKing** [comment]
include/uapi/linux/fs.h:#define FS_IOC_GETFLAGS                 _IOR('f', 1, long)

which is 1074030081 or 0x40046601

**Comment by ColinIanKing** [comment]
1074292225 = 0x40086601

**Comment by ColinIanKing** [comment]
I suspect there is a difference between the user space view of _IOC_SIZEBITS and the kernel, I need dig a bit more on this

**Comment by ColinIanKing** [comment]
..mind you, this ioctl works OK on ext4, so it may be the zfs side that is picking up the wrong size at build time.

**Comment by ColinIanKing** [comment]
#define FS_IOC_GETFLAGS _IOR('f', 1, long long)
works on ZFS but fails on ext4 - it produces the same ioctl cmd as in the zfs driver

#define FS_IOC_GETFLAGS _IOR('f', 1, long)
fails on ZFS, but does work on ext4

**Comment by ColinIanKing** [comment]
The following fix seems to work on my big endian powerpc64 test box. I used the same kind of 32/64 compat ioctl twiddles as found on other file systems, and it seems to work for me now.  I had to bodge this by adding the linux/compat.h at the start of module/zfs/zpl_file.c, I don't know how that should be abstracted.  I've not tested this for little endian 64 bit systems yet.

'''
#include <linux/compat.h>
'''

'''
zpl_compat_ioctl(struct file *filp, unsigned int cmd, unsigned long arg)
{
        printk(KERN_CRIT "zpl_compat_ioctl called, cmd=%u\n", cmd);
        switch (cmd) {
        case FS_IOC32_GETFLAGS:
                cmd = FS_IOC_GETFLAGS;
                break;
        case FS_IOC32_SETFLAGS:
                cmd = FS_IOC_SETFLAGS;
                break;
        default:
                return (-ENOIOCTLCMD);
        }
        return (zpl_ioctl(filp, cmd, (unsigned long) compat_ptr(arg)));
}
'''

**Comment by behlendorf** [comment]
Seems reasonable, I didn't realize you were testing with a 32-bit user space.  Adding `linux/compat.h` to the top of the `zpl_file.c` is fine, the `zpl_*` source files are all already Linux specific so that's the right layer in the abstraction.

**Comment by ColinIanKing** [comment]
Fixed, see bug 4477: https://github.com/zfsonlinux/zfs/pull/4477
