### ISSUE TITLE
Kernel panic

### ISSUE THREAD

**Issue by da-tex** [zfsonlinux/zfs#4480]
We see a reproducible kernel panic, most likely related to zfs, when we run our backup script. I will add a blurry picture taken from my mobile in the evening.

> EDIT: 
> The last part of the script, building an index of changed files and creating several symlinks, triggers the panic.
> 
> ZFS related commands are here:
> zfs list -H -t snapshot
> zfs diff -H -F "..." "...."
>
> I try to figure out the exact circumstances in the next days.

Taking the snapshot seems to work. (See zpool history below)

I found similar issues here on github. Can you check if this is a know issue? If yes does a patch exist? Thanks in advance!

System information:

**modinfo zfs|head**
filename:       /lib /modules/3.16.0-4-amd64/updates/dkms/zfs.ko
version:        0.6.5.2-2
license:        CDDL
author:         OpenZFS on Linux
description:    ZFS
srcversion:     B6DF70C0F3350F9F3D1A7C4
depends:        spl,znvpair,zunicode,zcommon,zavl
vermagic:       3.16.0-4-amd64 SMP mod_unload modversions 
parm:           zvol_inhibit_dev:Do not create zvol device nodes (uint)
parm:           zvol_major:Major number for zvol device (uint)

**uname -a**
Linux .... 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u2 (2016-01-02) x86_64 GNU/Linux

**zpool history**
....
2016-03-31.06:30:28 zfs snapshot -r tank/fs@2016-03-31
2016-03-31.06:56:14 zpool import -N tank

**Comment by tuxoko** [comment]
There some snapshot related issues that were fixed in 0.6.5.4. You should probably upgrade to newer stable. The current one is 0.6.5.6

**Comment by da-tex** [comment]
After running
`apt-get update && apt-get upgrade && apt-get dist-upgrade`
the current installed version still is 0.6.5.2

The daily variants in the sources.d directory are uncommented.

Do I have to update manually? Or are there problems within my debian installation?

**Comment by azeemism** [comment]
@da-tex, see https://github.com/zfsonlinux/pkg-zfs/issues/181

**Comment by azeemism** [comment]
@da-tex, use the default.
`nano /etc/apt/sources.list.d/zfsonlinux.list`
```
## This file is installed by the zfsonlinux package.

deb [arch=amd64] http://archive.zfsonlinux.org/debian jessie main
#deb-src http://archive.zfsonlinux.org/debian jessie main

# !! Enable these ONLY if you want/need the dailies - latest ZoL code !!
#deb [arch=amd64] http://archive.zfsonlinux.org/debian jessie-daily main
#deb-src http://archive.zfsonlinux.org/debian jessie-daily main
```
Then,
`apt-get update`
`apt-get upgrade`

**Comment by da-tex** [comment]
Thank you, guys! The update didn't work in the first place, because it wasn't in the dailies...
Now it worked and our backup script is running again!

Just one little problem: Now the pool isn't imported on system startup. Manual import works.
`zpool list 
no pools available

zpool list 
no pools available

zpool list 
no pools available`

How can I fix this?
