### ISSUE TITLE
zfs-mount fails with 0.6.5.4-r2 on gentoo

### ISSUE THREAD

**Issue by lkastner** [zfsonlinux/zfs#4494]
I upgraded from zfs-0.6.4.2 to zfs-0.6.5.4-r2 recently. The zfs-import service works fine, but zfs-mount fails with the following output in dmesg:

[   71.451369] SPL: using hostid 0x00000000
[   92.240904] BUG: unable to handle kernel paging request at 0000004fa0036c7c
[   92.241055] IP: [<ffffffffa003133e>] zfs_prop_get_type+0xe/0x20 [zcommon]
[   92.241163] PGD 0 
[   92.241256] Oops: 0000 [#1] SMP 
[   92.241394] Modules linked in: zfs(PO) zunicode(PO) zcommon(PO) znvpair(PO) spl(O) zavl(PO)
[   92.241771] CPU: 1 PID: 3742 Comm: dump_list_strat Tainted: P           O    4.1.15-gentoo-r1 #3
[   92.241829] Hardware name: To Be Filled By O.E.M. To Be Filled By O.E.M./Q1900-ITX, BIOS P1.00 03/28/2014
[   92.241889] task: ffff88015645f7d0 ti: ffff880083d04000 task.ti: ffff880083d04000
[   92.241944] RIP: 0010:[<ffffffffa003133e>]  [<ffffffffa003133e>] zfs_prop_get_type+0xe/0x20 [zcommon]
[   92.242052] RSP: 0018:ffff880083d07588  EFLAGS: 00010202
[   92.242104] RAX: 0000004fffffffb0 RBX: ffff880083d07728 RCX: 0000000000000000
[   92.242159] RDX: 0000000000000018 RSI: 0000000000000000 RDI: 00000000ffffffff
[   92.242214] RBP: ffff880083d07588 R08: 000000000000006f R09: ffff880084559b80
[   92.242269] R10: 0000000000000000 R11: ffff88015af17500 R12: 0000000000000010
[   92.242324] R13: ffff880083d07868 R14: 00000000ffffffff R15: 0000000000000000
[   92.242380] FS:  0000000000000000(0000) GS:ffff88015fc80000(0000) knlGS:0000000000000000
[   92.242436] CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
[   92.242489] CR2: 0000004fa0036c7c CR3: 0000000001ce3000 CR4: 00000000001006e0
[   92.242554] Stack:
[   92.242611]  ffff880083d07858 ffffffffa00cefe0 ffff880083d075a8 ffffffff81963449
[   92.242857]  0000000000000035 ffff880156fd6800 ffff880083d07868 ffff880084559f00
[   92.243102]  ffff880084559b80 0000000000000246 ffff880156fd6800 ffff8800892a8a00
[   92.243347] Call Trace:
[   92.243430]  [<ffffffffa00cefe0>] dsl_prop_inherit+0x6c0/0xa40 [zfs]
[   92.243499]  [<ffffffff81963449>] ? mutex_unlock+0x9/0x10
[   92.243566]  [<ffffffffa00058a5>] ? spl_kmem_alloc+0xa5/0x1a0 [spl]
[   92.243633]  [<ffffffffa0032ad0>] ? zprop_string_to_index+0xc0/0x190 [zcommon]
[   92.243701]  [<ffffffffa0005b55>] ? spl_kmem_free+0x25/0x40 [spl]
[   92.243767]  [<ffffffffa0032901>] ? zprop_iter_common+0xd1/0x130 [zcommon]
[   92.243835]  [<ffffffffa0032997>] ? zprop_name_to_prop+0x37/0xb0 [zcommon]
[   92.243903]  [<ffffffffa00057f9>] ? strfree+0x9/0x10 [spl]
[   92.243968]  [<ffffffff81963449>] ? mutex_unlock+0x9/0x10
[   92.244050]  [<ffffffffa00cf2a5>] dsl_prop_inherit+0x985/0xa40 [zfs]
[   92.244126]  [<ffffffffa014cd83>] ? zrl_init+0x43/0x50 [zfs]
[   92.244207]  [<ffffffffa00bf52d>] ? dsl_dataset_fast_stat+0xad/0x170 [zfs]
[   92.244291]  [<ffffffffa00d0510>] ? dsl_prop_unset_hasrecvd+0x60/0x60 [zfs]
[   92.244375]  [<ffffffffa00d0521>] dsl_prop_get_all_new+0x11/0x2790 [zfs]
[   92.244456]  [<ffffffffa011b86d>] zfs_secpolicy_smb_acl+0xdd/0x5ea0 [zfs]
[   92.244537]  [<ffffffffa0121a2f>] dataset_name_hidden+0x1ff/0x370 [zfs]
[   92.244604]  [<ffffffff81963449>] ? mutex_unlock+0x9/0x10
[   92.244687]  [<ffffffffa00f9cca>] ? unique_insert+0x11a/0x140 [zfs]
[   92.244768]  [<ffffffffa00be6a3>] ? dsl_dataset_hold_obj+0x583/0xbf0 [zfs]
[   92.244848]  [<ffffffffa00aba0c>] dmu_objset_stats+0x16c/0xbd0 [zfs]
[   92.244915]  [<ffffffffa00058a5>] ? spl_kmem_alloc+0xa5/0x1a0 [spl]
[   92.244994]  [<ffffffffa00abb79>] dmu_objset_stats+0x2d9/0xbd0 [zfs]
[   92.245073]  [<ffffffffa00aded0>] dmu_objset_find_dp+0x150/0x1d0 [zfs]
[   92.245154]  [<ffffffffa0121880>] ? dataset_name_hidden+0x50/0x370 [zfs]
[   92.245234]  [<ffffffffa0123a8f>] dump_list_strategy_one+0x5f/0xd0 [zfs]
[   92.245315]  [<ffffffffa0123bac>] dump_list_strategy_impl+0xac/0x340 [zfs]
[   92.245382]  [<ffffffff810b9e24>] ? put_prev_task_fair+0x24/0x40
[   92.245462]  [<ffffffffa0123e40>] ? dump_list_strategy_impl+0x340/0x340 [zfs]
[   92.245542]  [<ffffffffa0123e59>] dump_list_strategy+0x19/0xa0 [zfs]
[   92.245610]  [<ffffffffa0007e0c>] __thread_exit+0x8c/0xa0 [spl]
[   92.245677]  [<ffffffffa0007da0>] ? __thread_exit+0x20/0xa0 [spl]
[   92.245743]  [<ffffffff810ab744>] kthread+0xc4/0xe0
[   92.245807]  [<ffffffff810ab680>] ? kthread_create_on_node+0x170/0x170
[   92.245873]  [<ffffffff81965752>] ret_from_fork+0x42/0x70
[   92.245937]  [<ffffffff810ab680>] ? kthread_create_on_node+0x170/0x170
[   92.246000] Code: 04 83 b8 e0 6c 03 a0 01 0f 95 c0 0f b6 c0 c3 66 0f 1f 44 00 00 31 c0 5d c3 0f 1f 40 00 89 ff 55 48 8d 04 bf 48 89 e5 48 c1 e0 04 <8b> 80 cc 6c 03 a0 5d c3 66 2e 0f 1f 84 00 00 00 00 00 89 ff 55 
[   92.249026] RIP  [<ffffffffa003133e>] zfs_prop_get_type+0xe/0x20 [zcommon]
[   92.249139]  RSP <ffff880083d07588>
[   92.250263] CR2: 0000004fa0036c7c
[   92.250324] ---[ end trace 99ad4540909a6ff6 ]---

Afterwards it is locked up. Is this the same issue as [#4318](https://github.com/zfsonlinux/zfs/issues/4318)? Since it worked fine with 0.6.4.2, is there some kernel flag that needs to be included now?

**Comment by behlendorf** [comment]
Can you check if this is reproducible with a manual build of the ZoL 0.6.5.6 tarballs, not the gentoo version.  Adding @ryao to this issue.

**Comment by drescherjm** [comment]
If you install the zfs-9999, spl-9999, zfs-kmod-9999 you should get the current master without the new stable API patches that are in some of the other ebuilds.

**Comment by lkastner** [comment]
Thanks. It works perfectly with the 0.6.5.6 tarballs, meaning I cannot reproduce. I will try the 9999 version on the weekend. Is this due to the higher version or the non-ebuild version? I have another machine which works just fine with the 0.6.5.4-r2 ebuilds.

**Comment by lkastner** [comment]
I will close the issue now, as it works for me. If I manage to reproduce, I can reopen. Thank you for your help.

**Comment by drescherjm** [comment]
9999 usually means live (what is in the source control - master, trunk ...) ebuild of a repository. In this case I believe you get what is in the github master branch at the time you emerge.
