### ISSUE TITLE
zfs pool corruption on power loss

### ISSUE THREAD

**Issue by zrait** [zfsonlinux/zfs#4501]
My recently created zpool's metadata was corrupted due to a brief loss of power. I have ECC ram, and the pool was made up of 2 vdevs consisting of 6 disks in raidz2. The pool didn't come up when the system rebooted, and I received email notifications that checksum errors had occurred (I believe during the attempt to mount the pool at boot). I tried `zpool import -F` which told me that the pool metadata was corrupted and did not suggest any potential recovery options. I'm already in the process of restoring the pool from backup, but I'm a bit surprised this happened (I've never lost an entire filesystem to a power hiccup) and curious whether I should expect that a power loss will regularly corrupt an entire pool or if this was just a perfect storm of some sort.

I'm also happy to provide any zfs event history or anything of the sort if that's helpful.

**Comment by drescherjm** [comment]
I would say this is unusual.

**Comment by behlendorf** [comment]
This is very unusual and shouldn't be possible.  `zpool import -F` should always be able to rollback unless your disk was lying to you, or potentially there was a pool configuration change (add/remove disk) right before the power outage.
