### ISSUE TITLE
debian apt archive versioning broken, causes warnings during dist-upgrade

### ISSUE THREAD

**Issue by jh3141** [zfsonlinux/zfs#4502]
Attempting to upgrade a wheezy machine to jessie (by changing the apt-sources list for both debian and zfsonlinux.org repositories to point to jessie rather than wheezy, running `apt-get update` and `apt-get dist-upgrade`) gives the following warning:

> The following packages will be DOWNGRADED:
>   debian-zfs

The reason for this is that the version number of the zfs package for jessie ("7~jessie") is lower than the version number for wheezy ("7~wheezy") due to the fact that alphabetic sections of the version are compared lexically. The version number should increase in order to make everything work appropriately.

**Comment by Fabian-Gruenbichler** [comment]
it's rather pointless to use `upstream-pkgrel~distro` when distro is not using a naming scheme like ubuntu's ABC. The correct way for Debian (based) distros (especially for packages like zfs, where nearly identical releases happen for multiple distros, and the chances for the `upstream-pkgrel` part to be identical within a dist-upgrade path are therefore high) would probably be something like `upstream-pkgrel~Xdistro`, where X is the distro's major release number (i.e. 7 for wheezy, 8 for jessie, 9 for stretch), or more similar to Debian's naming scheme for backports: `upstream-pkgrel~zfsX` or `upstream-pkgrel~zolX`.

This should probably go to pkg-zfs though ;)

**Comment by behlendorf** [comment]
Closing.  This is a packaging issue handled by the distribution.
