### ISSUE TITLE
utf8only, normalization settings being ignored on non root pool creation

### ISSUE THREAD

**Issue by cwharlow** [zfsonlinux/zfs#4504]
command "zpool create -f -o ashift=12 -O normalization=formD -m none scratchpool ata-TOSHIBA_HDWD110_Y5EB69RRS"

results in "~ # zfs get normalization scratchpool
NAME         PROPERTY       VALUE          SOURCE
scratchpool  normalization  none           default "

also tried with /dev/sdX  rather than device ID and also other normalization forms, no luck

gentoo, kernel 4.1.15-r1. zfs-0.6.5.4-r2, zfs-kmod-0.6.5.4-r1, spl-0.6.5.4-r1

**Comment by cwharlow** [comment]
not working to create root pools either. 2 machines I did installs on this week show normalization as none. machine in initial comment was installed around Oct 2014 (so older zfs version), root pool on it says:
"~ # zfs get normalization zroot
NAME   PROPERTY       VALUE          SOURCE
zroot  normalization  formD          -
"

**Comment by stiell** [comment]
Same problem with Gentoo, kernel 4.4.8-hardened-r1, zfs-0.6.5.3-r5.

zfs-0.6.5.2-r1 (with spl-0.6.5.3-r1 and zfs-kmod-0.6.5.3-r4) does not have the issue.

**Comment by stiell** [comment]
I just tried with sys-fs/zfs-0.6.5.4 (i.e. no Gentoo-specific patches) and setting e.g. `normalization=formD` on pool pool creation works fine. It seems that this bug is in one of @ryao's patches to the sys-fs/zfs package.

**Comment by rlaager** [comment]
I agree with @stiell. This works for me. It sounds like this is a Gentoo problem and should be reported there.

**Comment by cwharlow** [comment]
sure no problem, thanks for the help. I will report it there
