### ISSUE TITLE
zpool_vdev_remove() includes misleading error message that top-level  devices can be removed

### ISSUE THREAD

**Issue by ColinIanKing** [zfsonlinux/zfs#4506]
lib/libzfs/libzfs_pool.c, zpool_vdev_remove(), the function has a comment stating: "Remove the given device.  Currently, this is supported only for hot spares and level 2 cache devices".  However, there is an error message that states "only inactive hot spares, cache, top-level, or log devices can be removed".

Which statement is correct, and does the error message need fixing because it is misleading?

        /*
         * XXX - this should just go away.
         */
        if (!avail_spare && !l2cache && !islog) {
                zfs_error_aux(hdl, dgettext(TEXT_DOMAIN,
                    "only inactive hot spares, cache, top-level, "
                    "or log devices can be removed"));
                return (zfs_error(hdl, EZFS_NODEVICE, msg));
        }

**Comment by behlendorf** [comment]
This block of code predates my involvement and goes all the way back to 2009.  But after looking over the code and [commit history](https://github.com/openzfs/openzfs/commit/88ecc943b4eb72f7c4fbbd8435997b85ef171fc3) the conditional check here is correct.

The function comment just wasn't updated when support for log devices was being worked on.  Oddly this same commit added top-level devices to the error message but ZFS never has allowed users to remove a top-level vdev.  Internally it's possible under certain circumstances but it misleading to tell users they can do this in an error message.

We should update the function comment and error message accordingly.
