### ISSUE TITLE
elevator "none" check is reverses, regression from commit d1d7e2689db9e ("cstyle: Resolve C style issues")

### ISSUE THREAD

**Issue by ColinIanKing** [zfsonlinux/zfs#4507]
Commit commit d1d7e2689db9e ("cstyle: Resolve C style issues") while cleaning up style warnings broke the none elevator comparison in module/zfs/vdev_disk.c, vdev_elevator_switch():

-       if (!strncmp(elevator, "none", 4) && (strlen(elevator) == 4))
+       if (strncmp(elevator, "none", 4) && (strlen(elevator) == 4) == 0)

The code no longer returns 0 when elevator == "none".

**Comment by behlendorf** [comment]
Indeed it did.  Please open a PR to revert this change in a fashion `make cstyle` is happy with so we can resolve this.

**Comment by ColinIanKing** [comment]
I'm unfamiliar with the process here, not sure what you mean by "open a PR".

**Comment by drescherjm** [comment]
Pull Request.

**Comment by behlendorf** [comment]
Github shorthand for a pull request.  If you can create a new one with a tiny fix for this it'll be easy to get it reviewed, merged, and attributed properly.
