### ISSUE TITLE
zfs_fuid_node_add() modifies zfs_fuid_info_t list without obvious locking

### ISSUE THREAD

**Issue by ColinIanKing** [zfsonlinux/zfs#4508]
module/zfs/zfs_fuid.c, zfs_fuid_node_add(): 

There don't seem to be any direct (or obvious) locks around the list modifications on zfs_fuid_info_t **fuidpp, so this looks like a potential race condition on this list.

**Comment by behlendorf** [comment]
This functionality, along with everything else wrapped with HAVE_KSID, is dormant under Linux.  Additional work is still required needed to map this illumos functionality to its Linux counterpart.

**Comment by behlendorf** [comment]
Closing.  This code is disabled on Linux.
