### ISSUE TITLE
Ability to test ZED proper functioning

### ISSUE THREAD

**Issue by Darakko** [zfsonlinux/zfs#4511]
When configuring ZED, admins need to be sure it will really trigger the desired alarm when a problem will occur months or years later.

There should be a way to trigger an fake event in order to check if the logs are written and/or if the email is received. This allow to validate the full chain from the event to the final tools used to monitor the health of ZFS.

**Comment by alexanderhaensch** [comment]
This is something i would like to see as well. Maybe something like
`zpool events -m "Test Message"`

Another possibility is to force a failure by for example removing a drive in a raidz setup.

**Comment by behlendorf** [comment]
We definitely want this ability so we can add additional test coverage which verifies the ZED.  @don-brady may have some additional thoughts on this, but my current inclination is to extend `zinject` which is already used for error injection.

**Comment by don-brady** [comment]
Confirming that more testing is required for the ZED/zevent stack.  We will be adding functional test as part of our ZED related work. Operations like auto-spare, auto-online, auto-replace should be validated start-to-finish during testing.

Looks like there is an ask here for tools to help administrators in validating custom zedlet behavior.

**Comment by behlendorf** [comment]
Closing.  Test coverage for auto-spare, auto-online, auto-replace have all been added to the ZTS.  We'll continue to extend the test coverage as needed.  As for testing the ZED users can use `zinject` to simulate failure, this is the same utility which is used by the test suite.

**Comment by flaviut** [comment]
> As for testing the ZED users can use zinject to simulate failure, this is the same utility which is used by the test suite.

I looked over the help page for zinject, but unfortunately all this stuff is quite a bit beyond me. Do you have an example command that I can use to test zed that won't break/panic my system?

**Comment by cvoltz** [comment]
Try `zinject -d DEVICE -e io -T all -f 100 POOL`. That will fail all I/O to the specified `DEVICE` in the specified `POOL` 100% of the time until you clear it with a `zinject -c all`. You'll want to run `zpool clear POOL DEVICE` afterwards to clear the fault. For example:
```
# inject fault
zinject -d /dev/sdb -e io -T all -f 100 tank

# verify LED

# clear fault
zinject -c all
zpool clear tank /dev/sdb
```
