### ISSUE TITLE
Data Corruption During ZFS send/receieve

### ISSUE THREAD

**Issue by jonwedell** [zfsonlinux/zfs#4530]
During ZFS send and receive at least one file is becoming corrupted - and neither sending nor receiving pool reports any errors during the send or with zpool status.

A demonstration:

On the sending computer (manta):

```shell
[root@manta ~]# zpool status -x
all pools are healthy
[root@manta ~]# zfs get mountpoint tank/extras/html
NAME              PROPERTY    VALUE                  SOURCE
tank/extras/html  mountpoint  /websites/extras/html  inherited from tank/extras
[root@manta html]# cd /websites/extras/html/molprobity_visualization/
[root@manta molprobity_visualization]# md5sum data.js 
b61bdb07117a3f293f683c123064cd3d  data.js
[root@manta molprobity_visualization]# /usr/sbin/zfs snapshot tank/extras/html@`date +\%F`
[root@manta molprobity_visualization]# /usr/sbin/zfs send -R -i tank/extras/html@`date --date yesterday +\%F` tank/extras/html@`date +\%F` | ssh batfish "/usr/sbin/zfs receive -Fduv tank"
receiving incremental stream of tank/extras/html@2016-04-15 into tank/extras/html@2016-04-15
received 50.7KB stream in 1 seconds (50.7KB/sec)
[root@manta molprobity_visualization]# wc -c data.js 
2980484 data.js

```

on the receiving computer (batfish) after the zfs send/receive:

```shell
[root@batfish ~]# zpool status -x
all pools are healthy
[root@batfish ~]# zfs get mountpoint tank/extras/html
NAME              PROPERTY    VALUE                  SOURCE
tank/extras/html  mountpoint  /websites/extras/html  inherited from tank/extras
[root@batfish ~]# cd /websites/extras/html/molprobity_visualization/
[root@batfish molprobity_visualization]# md5sum data.js 
f07f1adcf274ef300848af7009c7c7df  data.js
[root@batfish molprobity_visualization]# wc -c data.js 
2980484 data.js
```

Every night when this runs the file on batfish is replaced with a corrupted version of the one on manta. As you can see the file size is identical; it is just that part of the end of the file has about 8 kilobytes of garbage data and some invalid data that is probably from an older version of the file. Nevertheless the files are identical in size, just not content.

I haven't modified the file on manta because I suspect it may fix the issue and I wanted to help provide information to identify this bug before I lost the ability to reproduce it. I'm happy to provide more information to debug this if you can guide me in what you need to see to identify the problem.

We do not have deduplication enabled, and both file systems are using lzjb compression.

If it helps, you can see the [original file](http://extras.bmrb.wisc.edu/molprobity_visualization/data.js) and what the [same file looks like](http://extras.bmrb.wisc.edu/molprobity_visualization/corrupted.js) after it has been copied. If you search for the string "5.3000,5.6500,],},},},};" in the corrupted file you will see where the corruption appears to begin.

**Comment by jonwedell** [comment]
I should probably add:

Both machines are on Centos 7.2.1511.

Both machines have this version of ZFS:

zfs.x86_64     0.6.5.6-1.el7.centos       @zfs-kmod

**Comment by fling-** [comment]
@jonwedell could you also cmp the data in the snapshots? There is a possibility you have the corruption in an older snapshot or in all of them.

**Comment by jonwedell** [comment]
@fling- No data corruption appears at all on the sending side:

```shell
web@manta:/websites/extras/html/.zfs/snapshot$ ls
2016-04-14  2016-04-15  2016-04-16  2016-04-17
web@manta:/websites/extras/html/.zfs/snapshot$ md5sum */molprobity_visualization 
b61bdb07117a3f293f683c123064cd3d  2016-04-14/molprobity_visualization/data.js
b61bdb07117a3f293f683c123064cd3d  2016-04-15/molprobity_visualization/data.js
b61bdb07117a3f293f683c123064cd3d  2016-04-16/molprobity_visualization/data.js
b61bdb07117a3f293f683c123064cd3d  2016-04-17/molprobity_visualization/data.js
```

That is the md5sum of the original and correct file.

**Comment by fling-** [comment]
@jonwedell I'm talking about comparing the snapshots on the sending side to the snapshots on the receiving side.

**Comment by jonwedell** [comment]
Ah, sorry. The snapshots on the receiving side also have the uncorrupted file on all the snapshots - including the most up to date one.

**Comment by fling-** [comment]
@jonwedell good news. It is easy to workaround with a single rollback. Atleast we don't have a corruption in the snapshots. Looks like I could stop doing any more cmp on my side trying to reproduce your behavior.

**Comment by kernelOfTruth** [comment]
Referencing https://github.com/zfsonlinux/zfs/commit/c352ec27d5c5ecea8f6af066258dfd106085eaac Illumos 6370 - ZFS send fails to transmit some holes

(which is already included in 0.6.5.6)

afaik there's also other hole related changes at openzfs waiting to be integrated:
https://github.com/openzfs/openzfs/pull/82
https://github.com/openzfs/openzfs/pull/46

But this shouldn't cause any corruption ...

@jonwedell 

Please post some information on how the 2 machines are connected, the hardware they're running and other specifics you might deem useful to troubleshoot this case

Thanks

**Comment by jonwedell** [comment]
@fling- Yeah, triggering a rollback on the receiving machine would work; I can also regenerate that specific file on the receiving side. I've just stopped the nightly zfs send for now because nothing on that dataset is changing at this point in time anyways.

@kernelOfTruth - Hmm, that first commit seems to refer only to sparse files, which this particular file is not. I saw #4050 today which sounds like the same symptoms I'm experiencing, though we have hole_birth enabled.

Unfortunately I've lost the ability to reproduce this after doing some tests to see what triggers the problem. One (or some combination) of the following actions appears to have stopped this problem from happening:

destroying the most recent snapshot of the problematic dataset on the receiving machine
sending the full dataset to a new machine to see if the problem occurs
creating a new snapshot on the sending machine and sending that incrementally to the new test machine

I was unable to reproduce the issue on the new machine; and like I said I can no longer reproduce on the original machine; the file is now unmodified during incremental sends. (Which was the expected behavior all along since this particular file has not been modified in over a year and certainly not between the snapshots that were being sent incrementally.)

I'm not sure if it is worth keeping this open if I can no longer reproduce the problem.

**Comment by dmaziuk** [comment]
@kernelOfTruth : both are AMD supermicros, I don't have the mobo models handy. Receiving end's an older box w/ dual opteron 2350 & 4GB RAM, sender's a dual 6212 w/ 64GB RAM. They're in adjacent racks but there's cisco firewall in between, it's installed in the main switch stack a couple of blocks away, so the traffic goes all the way there and back to our server room.

There's nothing about either that stands out. Except the receiving machine being a bit old.

**Comment by dmaziuk** [comment]
On 2nd thought, I lied: the receiving machine is running kernel 3.10.0-229.14.1.el7 because every newer kernel build so far (current is 327.13.1) has failed to boot. That does stand out, actually.

**Comment by rincebrain** [comment]
@kernelOfTruth 6513 is _not_ in an 0.6.5.X release yet, so if this pool has hole_birth, that's a possible reason.

If it is 6513 or a hole_birth-related bug, sending a non-differential stream will result in the receiver having an intact copy of the file.

**Comment by behlendorf** [comment]
Fixes for multiple hole birth related bug were applied to 0.6.5.8 tag and the module option `ignore_hole_birth` was added an enabled by default.  This disables the hole birth functionality by default with the intention of leaving it disabled until all hole birth bugs have been resolved and relevant test cases added.  See #5061 for the last known remaining issue.
