### ISSUE TITLE
DKMS builds on Ubuntu Failing

### ISSUE THREAD

**Issue by sempervictus** [zfsonlinux/zfs#4532]
This is a repost of https://github.com/zfsonlinux/pkg-zfs/issues/198, which has been up for three weeks, but i figure that Ubuntu folks like @ColinIanKing are more likely to see the issue here (sorry if this is bad GH etiquette).

Since the import of the new test suite, the Ubuntu packaging has been broken for DKMS builds, which makes for some "unpleasantness" in automated testing across kernels.

**Comment by rlaager** [comment]
If you're trying to use zfs-dkms from pkg-zfs or the PPA on 16.04 or newer, you're doing it wrong.

If Ubuntu's zfs-dkms is broken in 16.04 (or yakkety development), you should take that bug report to Launchpad. I honestly haven't tested it recently, since I'm using the pre-built binaries.
