### ISSUE TITLE
zfsonlinux.github.com: outdated public key

### ISSUE THREAD

**Issue by dasjoe** [zfsonlinux/zfs#4533]
The website still lists @behlendorf's public key, 0xC6AF658B, whereas current releases' sha256 files are signed by @nedbass 0xC77B9667.

**Comment by FransUrbo** [comment]
@behlendorf Could you enable issues on https://github.com/zfsonlinux/zfsonlinux.github.com ?

**Comment by behlendorf** [comment]
@dasjoe thanks for pointing this out.  To be clear @nedbass is now signing the stable releases and I'm signing major releases, but the website clearly doesn't show that so we'll get it updated.

@FransUrbo done.  What I'd like to do is start migrating some/all of the content from the website to the zfs wiki.  This is the simplest way I can see to address the legitimate concerns in #4541 about the website not being TLS secured.  It should also make it easier for project members to help maintain it.

**Comment by behlendorf** [comment]
The public [signing keys](https://github.com/zfsonlinux/zfs/wiki/Signing-Keys) for releases are now posted on the wiki.
