### ISSUE TITLE
Cannot destroy a dataset, reports 'dataset is busy'

### ISSUE THREAD

**Issue by zenny** [zfsonlinux/zfs#4535]
Hi,

Similar instances has been reported in the past, and was reportedly **solved**, but it seems to have recurred in my case (Ubuntu 14.04 with zfs v0.6.5.6-1~trusty).

The dataset is mounted

```
# df -h | grep CONTAINER
tank/CONTAINER        209G  1.7G  207G   1% /mnt/tank/CONTAINER
```

Tried to destroy with -f argument output dataset is busy

```
# zfs destroy -f tank/CONTAINER
cannot destroy 'tank/CONTAINER': dataset is busy
```

Checked if it held by some snapshots: none.

```
# zfs holds tank/CONTAINER
'tank/CONTAINER' is not a snapshot
NAME  TAG  TIMESTAMP
no datasets available

```

Checked whether the volume is mounted: No results.
`# df -h | grep CONTAINER`

Checked whether the dataset is there:

```
# zfs list | grep CONTAINER
tank/CONTAINER        1.64G   207G  1.64G  /mnt/tank/CONTAINER
```

Tried to destroy again in futility.

```
# zfs destroy tank/CONTAINER
cannot destroy 'tank/CONTAINER': dataset is busy
```

Did I miss anything? Inputs appreciated!

**Comment by tomposmiko** [comment]
```
fuser -vm /mnt/tank/CONTAINER
```

Most probably you will find some processes there. Basically your container is still running.

**Comment by zenny** [comment]
I have stopped all processes that drives it, and also rebooted the machines several time to upgrade kernel. Means the service that drives the containers have been stopped. 

Also,lazy-unmounted all aufs instances with:
`umount -l $(grep 'aufs' /proc/mounts | awk '{print$2}' | sort -r)`

```
# fuser -vm /mnt/storage/hyper
                     USER        PID ACCESS COMMAND
/mnt/tank/CONTAINER:  root     kernel mount /mnt/tank/CONTAINER
```

**Comment by behlendorf** [comment]
Closing.  Working as expected, busy datasets cannot be unmounted.
