### ISSUE TITLE
CentOS7 rpm has broken URL

### ISSUE THREAD

**Issue by victoredwardocallaghan** [zfsonlinux/zfs#4540]
On the following page [epel](http://zfsonlinux.org/epel.html) there is a bad URL:

```
 - $ sudo yum localinstall --nogpgcheck https://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
```
should be:
```
 + $ sudo yum localinstall --nogpgcheck https://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-6.noarch.rpm
```

Kind Regards,
Edward.

**Comment by behlendorf** [comment]
@victoredwardocallaghan thanks for noticing this.  I've updated the page to recommend installing the `epel-release` package which is now provided from the  official CentOS/RHEL repos.
