### ISSUE TITLE
zpool label command

### ISSUE THREAD

**Issue by FransUrbo** [zfsonlinux/zfs#4551]
When replacing an old device with a brand new, it requires the <code>-f</code> option. That is scary, because if I pasted/wrote the wrong (new) device, I might mess up everything.

I'd rather have the possibility to first do <code>zpool label newdev</code>.

**Comment by behlendorf** [comment]
@FransUrbo so actually the `-f` should no longer be required in master.  Commit a9977b37ca7bd27ff28de435f8666e253ff6330e changes this for exactly the reasons you mentioned.

**Comment by FransUrbo** [comment]
Ah, nice!
