### ISSUE TITLE
How to resolve this dracut shell problem.

### ISSUE THREAD

**Issue by dilshath** [zfsonlinux/zfs#4556]
I am using centos 7 in physical machine. While creating and saving new partition followed by using "fdisk" command for save and partprobe in Centos 7 (It is installed in KVM), I got this error (at least 3 or 4 times). I appreciate if you guide me how to fix this problem. 

Warning: /dev/centos/root does not exist
Warning: /dev/centos/swap does not exist
Warning: /dev/mapper/centos-root does not exist

Starting Dracut Emergency Shell...
Warning: /dev/centos/root does not exist
Warning: /dev/centos/swap does not exist
Warning: /dev/mapper/centos-root does not exist

Generating "/run/initramfs/rdsosreport.txt"
Entering emergency mode, Exit the shell to continue.

dracut:/#

**Comment by kostyaberger** [comment]
What is your ZFS setup? Because this place is related to "ZFS on Linux" solution, not just ANY linux-related problem one may encounter in various configurations.

[Here](https://www.centos.org/forums/viewtopic.php?t=52140) is a post similar to yours. Maybe you ask there.

**Comment by FransUrbo** [comment]
He also asked the exact same thing in https://github.com/zfsonlinux/zfs/pull/4478#issuecomment-214247337.

**Comment by kostyaberger** [comment]
Well, hope he'll understand this time.

Sent from Yahoo Mail on Android 
 
  On Fri, Apr 29, 2016 at 18:49, Turbo Fredriksson<notifications@github.com> wrote:   
He also asked the exact same thing in #4478 (comment).

**Comment by behlendorf** [comment]
Closing as unrelated to ZoL, at least until additional details are provided.
