### ISSUE TITLE
Build error with new mainline kernel 4.5.2 "blk_queue_flush" [fs/zfs/zfs/zfs.ko] undefined!

### ISSUE THREAD

**Issue by sergiall** [zfsonlinux/zfs#4563]
Hello,I try to build zfs as linux-builtin module with latest stable mainline kernel and unfortunaly get this error:
CC [M]  fs/zfs/zfs/zvol.o
  LD [M]  fs/zfs/zfs/zfs.o
  Building modules, stage 2.
  MODPOST 4130 modules
ERROR: "blk_queue_flush" [fs/zfs/zfs/zfs.ko] undefined!
WARNING: modpost: Found 1 section mismatch(es).
To see full details build your kernel with:
'make CONFIG_DEBUG_SECTION_MISMATCH=y'
scripts/Makefile.modpost:91: recipe for target '__modpost' failed
make[2]: **\* [__modpost] Error 1

My spl/zfs config.log
[config.log.txt](https://github.com/zfsonlinux/zfs/files/237064/config.log.txt)
[config.log.txt](https://github.com/zfsonlinux/zfs/files/237065/config.log.txt)

Please,help me resolve this issue!

**Comment by sergiall** [comment]
As I investigate,new kernels's edition of file include/linux/blkdev.h dont't have the 
"extern void blk_queue_flush(struct request_queue *q, unsigned int flush);" string,but have the
"extern void blk_queue_flush_queueable(struct request_queue *q, bool queueable);" string,so I edit the
file contained "blk_queue_flush" reference - fs/zfs/zfs/zvol.c" and simple change this line:
blk_queue_flush(zv->zv_queue, VDEV_REQ_FLUSH | VDEV_REQ_FUA);
to 
blk_queue_flush_queueable(zv->zv_queue, VDEV_REQ_FLUSH | VDEV_REQ_FUA);
and error disappeared and kernel continued to build,but I fill,what tests in runtime has needed.
If you prompt more elegant solution,please write here about.
Thank you for attention.

**Comment by tsjk** [comment]
Yes, I do wonder about this as well.
