### ISSUE TITLE
spl_hostid= kernel parameter overriden by spl

### ISSUE THREAD

**Issue by kostyaberger** [zfsonlinux/zfs#4572]
Kernel command line parameter spl_hostid seems to be used by zfs, as per dracut boot message "ZFS: using hostid ($spl_hostid here)". But it is overriden by spl, as per another message "SPL: using hostid (then goes another hostid, identical to the one output by /bin/hostid in initramfs).

Actually, is there a mechanism to override the one used by spl? Both spl_hostid= kernel parameter and /etc/hostid are ignored. As I have 2 OSes in the same ZFS pool, making them both use the same hostid is better than using "-f" parameter to forcefully import the pool.

**Comment by rlaager** [comment]
For the benefit of anyone stumbling across this in the future, this was resubmitted here:
https://github.com/zfsonlinux/spl/issues/544
