### ISSUE TITLE
dracut fails when pool members are /dev/sd*

### ISSUE THREAD

**Issue by bjencks** [zfsonlinux/zfs#4577]
In `/contrib/dracut/02zfsexpandknowledge/module-setup.sh.in`, `get_pool_devices` behaves incorrectly when pool members are sd* (e.g. sde,sdf,sda2), since it only looks for members in /dev/disk/*.

The `zpool list | awk` pipeline is also very fragile, since it includes 'mirror' and blank lines (and presumably other types such as raidz). The blank line in particular is breaking the script for me, because it decides that the device is /dev/disk/by-id/ by evaluating $prefix/$pooldev with an empty pooldev.

I haven't confirmed it, but I believe this is causing a hang in dracut's initramfs generation.

**Comment by bjencks** [comment]
Related: #3605 and a5a370227eb0a3daf8992a38920d54eb3b7b3c25

**Comment by behlendorf** [comment]
@Rudd-O can you take a look at this.  Also FYI I just added a new 'Dracut' label to the issue tracker and tagged most of the outstanding [dracut issues](https://github.com/zfsonlinux/zfs/labels/Dracut) I'm aware of.

**Comment by Rudd-O** [comment]
Yes.     Looking at it now.

**Comment by Rudd-O** [comment]
I have fixed this issue in the pull request:

"The zpool list | awk pipeline is also very fragile, since it includes 'mirror' and blank lines (and presumably other types such as raidz). The blank line in particular is breaking the script for me, because it decides that the device is /dev/disk/by-id/ by evaluating $prefix/$pooldev with an empty pooldev."

**Comment by Rudd-O** [comment]
I believe I have fixed the issue where pools are composed of devices that are direct children of /dev.  But I might be wrong, so make sure to test them.

The real solution is to have zpool print out the actual device path.  I can't do C without inflicting segfaults on folks, so this will have to do.  But I will integrate any sort of patches that do exactly the printout of the actual device path, no questions asked.  Okay, some questions asked.

**Comment by Rudd-O** [comment]
(I added stuff to the Fix boot in other cases pull request https://github.com/zfsonlinux/zfs/pull/4558#discussion_r61047066 )

**Comment by Rudd-O** [comment]
On 04/29/2016 04:45 PM, Brian Behlendorf wrote:
>
> @Rudd-O <https://github.com/Rudd-O> can you take a look at this. Also
> FYI I just added a new 'Dracut' label to the issue tracker and tagged
> most of the outstanding dracut issues
> <https://github.com/zfsonlinux/zfs/labels/Dracut> I'm aware of.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/zfsonlinux/zfs/issues/4577#issuecomment-215802079>
>

Sorry for the delay.  I was oncall at Google.  And it was an interesting
week.

-- 
    Rudd-O
    http://rudd-o.com/

**Comment by b333z** [comment]
@Rudd-O in case of use, I believe https://github.com/zfsonlinux/zfs/commit/d2f3e292dccab23e47ade3c67677a10f353b9e85 made it into the zfs-0.6.5.6 tag which gives us full path from zpool:

```
# zpool list -v
NAME   SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
tank   127G   109G  17.8G         -    60%    85%  1.00x  ONLINE  -
  sda4   127G   109G  17.8G         -    60%    85%
# ZPOOL_VDEV_NAME_PATH=1 zpool list -v                                                                                                                                                                                      
NAME   SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
tank   127G   109G  17.8G         -    60%    85%  1.00x  ONLINE  -
  /dev/sda4   127G   109G  17.8G         -    60%    85%
```

I'd probably go for the environment variable as the argument as -p changes to -P in a later commit: https://github.com/zfsonlinux/zfs/commit/a77f29f93c8d016f17d9b77f39662e311774aaae

**Comment by Rudd-O** [comment]
Can I ask you to modify the relevant file in https://github.com/zfsonlinux/zfs/pull/4558 to absorb this change in semantics?  Happy to incorporate it with the suggestions you may come up with, as I think this will seriously increase robustness.

**Comment by behlendorf** [comment]
You can rely on the `-P` option.  The use of `-p` only lasted for a few commits in master and that syntax never appeared in a tagged release.

**Comment by b333z** [comment]
@Rudd-O just put a PR to your branch with the -P change: https://github.com/Rudd-O/zfs/pull/13

**Comment by Rudd-O** [comment]
I have a different change in mind which fixes this problem.  Let's merge that one and we'll revisit the -P use later, as I am going away for a few days and I won't be available to contact or solve issues that a larger change may cause.

**Comment by Rudd-O** [comment]
Great news: I have added @b333z work to my pull request, which solves this issue.

**Comment by bjencks** [comment]
I successfully booted with a0a9742844054b741ab8b29d887cbc870d6beb5a from your topic-fixboot tree, with root=zfs:path/to/root, on Fedora 23.

**Comment by behlendorf** [comment]
Closing, this issue has been addressed by:

d402c18 A collection of dracut fixes
