### ISSUE TITLE
Security Permission Folder Share Cannot Edit in ZFS Share

### ISSUE THREAD

**Issue by n4ldi** [zfsonlinux/zfs#4581]
The problem about security permission folder (Access Denied).
ZFS, Shadow Copy, Samba and join to Active Directory success install without error. I can use share folder with domain admins write or read access. But I get the problem when I use Properties Security Permission folder share windows, apply (Access Denied).

My smb.conf :
[share]
path = /fileserver/share
read only = No
comment = ZFS dataset with Previous Versions enabled
vfs objects = shadow_copy2
shadow: snapdir = .zfs/snapshot
shadow: sort = desc
shadow: format = zfs-auto-snap_hourly-%F-%H%M

I used this permission ;
chmod g=rwx fileserver/share
chgrp "Domain Admins" fileserver/share

any people can help about this problem ? :(

**Comment by FransUrbo** [comment]
I've rewritten the <code>sharesmb</code> to use **REGISTRY** shares instead of the current **USER** shares. You're very unlikely to get that working with the current code.

Have a look at https://github.com/zfsonlinux/zfs/pull/1476 if you're interested in the new behaviour.

**Comment by dominikh** [comment]
@FransUrbo Would you mind explaining what exactly the state of #1476 is? The PR is closed, but I don't see the changes anywhere in master and you speak of "waiting a year or two". 0.6.5.6 is still using user shares and I cannot find any other mentions regarding ZoL switching to registry shares.

**Comment by FransUrbo** [comment]
@dominikh As far as I know, it's dead. You'll have to ask/bug @behlendorf for more information.

But FYI, I've been running that PR in production for a couple of years now and there's nothing wrong with it. I just got fed up of waiting for a review of it, that wasn't going to happen.

Brian preferred, and I technically agree, that it would be better if ZED (ZFS Event Daemon) did the sharing. I just think it's better to have a _working_ solution, even if it's not perfect, until we DO get the "perfect" solution.

**Comment by behlendorf** [comment]
@dominikh I'd suggest applying @FransUrbo registry shares changes locally if you need to use that approach.  @FransUrbo is right I didn't want to switch the upstream ZoL source to user register shares and then again to ZED based approach.

**Comment by n4ldi** [comment]
Im not understand what have you said all. I have solved this issue with this : 

> zfs set acltype=posixacl

Thank you so much for your help :)

**Comment by dominikh** [comment]
@FransUrbo @behlendorf Okay, thanks for the explanation. Is there any rough timeline for the ZED based approach?

**Comment by behlendorf** [comment]
@dominikh it's unlikely to be soon, however I do expect that we'll all all the required event infrastructure for it in place this year.
