### ISSUE TITLE
Need import zpool after reboot machine

### ISSUE THREAD

**Issue by PeterQiao** [zfsonlinux/zfs#4590]
Hi,

I'm not sure whether someone reported this issue before.
I'm using virtualbox to use zfs and I find every time after I reboot VM, I have to re-import zpool.

Server:
 centos-7 with kernel 3.10

[root@localhost ~]# zpool list
no pools available
[root@localhost ~]# zpool import tank
[root@localhost ~]# zpool list
NAME   SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
tank  9.94G   391M  9.56G         -     6%     3%  1.00x  ONLINE  -
[root@localhost ~]# uname -a
Linux localhost.localdomain 3.10.0-327.13.1.el7.x86_64 #1 SMP Thu Mar 31 16:04:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost ~]#

Is there any other configuration I have to add?

Thank you for your time.

**Comment by b333z** [comment]
@PeterQiao have you enabled the zfs services with ```systemctl enable zfs.target``` ?

**Comment by PeterQiao** [comment]
Hi b333z,

Thank you, after enable service, this issue has been solved.

**Comment by b333z** [comment]
Good to hear @PeterQiao
