### ISSUE TITLE
Seq read is very slow

### ISSUE THREAD

**Issue by PeterQiao** [zfsonlinux/zfs#4592]
Hi,

I just did a simple test on my vm by using dd, here is my result:
Sys: centos 7 kernel: 3.10.0-327.13.1.el7.x86_64, I'm using a 512GB SSD sandisk X210
[root@localhost ~]# zpool status
  pool: tank
 state: ONLINE
  scan: none requested
config:

        NAME                                     STATE     READ WRITE CKSUM
        tank                                     ONLINE       0     0     0
          ata-VBOX_HARDDISK_VB65339056-d06a1ca9  ONLINE       0     0     0
          ata-VBOX_HARDDISK_VB64edb4f5-4dade716  ONLINE       0     0     0

errors: No known data errors

[root@localhost ~]# zfs list
NAME      USED  AVAIL  REFER  MOUNTPOINT
tank     98.1M  9.53G  19.5K  /tank
tank/p1  97.8M  9.53G  97.8M  /tank/p1

[root@localhost p1]# ls -l
total 100112
-rw-r--r--. 1 root root 102400000 May  3 02:59 a
[root@localhost p1]# dd if=./a of=/dev/null bs=1k
^C2071+0 records in
2070+0 records out
2119680 bytes (2.1 MB) copied, 4.55032 s, **# 466 kB/s**

I don't know why the speed is only 466 kB/s, can I improve performance by some configuration?

Thank you for your time.

**Comment by dasjoe** [comment]
Multiple issues here, you are doing "benchmarks" using `dd` with a block size of 1k, in a VM, on SSDs.

This is not an issue in ZFS, please take it to the mailing list [zfs-discuss](http://list.zfsonlinux.org/mailman/listinfo/zfs-discuss) or IRC (#zfsonlinux on freenode).

**Comment by PeterQiao** [comment]
Ok
