### ISSUE TITLE
CentOS 6.7 trouble: zfs module not found

### ISSUE THREAD

**Issue by cousins** [zfsonlinux/zfs#4596]
[yum-zfs-install.txt](https://github.com/zfsonlinux/zfs/files/248144/yum-zfs-install.txt)

I had ZFS running fine and then did a kernel update.  Then rebooted and updated spl and zfs. In the past this has worked. The new kernel is 2.6.32-573.22.1.el6.x86_64. 

I tried completely removing zfs, spl, zfs-dkms, spl-dkms and verified with "dkms status" that there was nothing there. Then I did "yum install zfs" and it installed them all again. However, when got done it still says it can't find zfs.ko when I run "modprobe zfs". 

dkms status shows:

> [root@nfs4 ~]# dkms status
> Error! Could not locate dkms.conf file.
> File:  does not exist.
> spl, 0.6.5.6, 2.6.32-504.23.4.el6.x86_64, x86_64: installed-weak from 2.6.32-573.22.1.el6.x86_64
> zfs, 0.6.5.6, 2.6.32-504.23.4.el6.x86_64, x86_64: installed-weak from 2.6.32-573.22.1.el6.x86_64
> spl, 0.6.5.6, 2.6.32-504.el6.x86_64, x86_64: installed-weak from 2.6.32-573.22.1.el6.x86_64
> zfs, 0.6.5.6, 2.6.32-504.el6.x86_64, x86_64: installed-weak from 2.6.32-573.22.1.el6.x86_64
> spl, 0.6.5.6, 2.6.32-573.18.1.el6.x86_64, x86_64: installed-weak from 2.6.32-573.22.1.el6.x86_64
> zfs, 0.6.5.6, 2.6.32-573.18.1.el6.x86_64, x86_64: installed-weak from 2.6.32-573.22.1.el6.x86_64

So, indeed, there is no zfs/spl for the current kernel for some reason. I will attach the output of the yum install command. I tried booting into the previous kernel and it didn't find zfs.ko either. possibly because of what it says at the end: installed-weak from 2.6.32-573.22.1.el6-x86_64?

If I try to do "dkms install spl" it says:

> Module zfs/0.6.5.6 already installed on kernel 2.6.32-573.22.1.el6.x86_64/x86_64

I'll try going to the previous kernel, uninstalling it all and then installing it again.

**Comment by cousins** [comment]
I don't understand. I just booted into the previous kernel, wiped out zfs, spl and the dkms packages. Then ran yum install zfs again. Still can't find zfs:

> [root@nfs4 ~]# dkms status
Error! Could not locate dkms.conf file.
File:  does not exist.
spl, 0.6.5.6, 2.6.32-504.23.4.el6.x86_64, x86_64: installed-weak from 2.6.32-573.18.1.el6.x86_64
zfs, 0.6.5.6, 2.6.32-504.23.4.el6.x86_64, x86_64: installed-weak from 2.6.32-573.18.1.el6.x86_64
spl, 0.6.5.6, 2.6.32-504.el6.x86_64, x86_64: installed-weak from 2.6.32-573.18.1.el6.x86_64
zfs, 0.6.5.6, 2.6.32-504.el6.x86_64, x86_64: installed-weak from 2.6.32-573.18.1.el6.x86_64
spl, 0.6.5.6, 2.6.32-573.22.1.el6.x86_64, x86_64: installed-weak from 2.6.32-573.18.1.el6.x86_64
zfs, 0.6.5.6, 2.6.32-573.22.1.el6.x86_64, x86_64: installed-weak from 2.6.32-573.18.1.el6.x86_64

It shows it for each of the others installed.

What to do? I'm glad this is a backup system rather than one of our primaries. I guess I'll need to get the source and do it the old fashioned way?

**Comment by cousins** [comment]
More information:

The weak-updates directory looks like:

> [root@nfs4 weak-updates]# ls -al
total 8
drwxr-xr-x 2 root root 4096 May  4 00:34 .
drwxr-xr-x 6 root root 4096 May  4 00:57 ..
lrwxrwxrwx 1 root root   54 May  3 18:15 splat.ko -> /lib/modules/2.6.32-504.23.4.el6.x86_64/extra/splat.ko
lrwxrwxrwx 1 root root   52 May  4 00:28 spl.ko -> /lib/modules/2.6.32-573.18.1.el6.x86_64/extra/spl.ko
lrwxrwxrwx 1 root root   53 May  4 00:34 zavl.ko -> /lib/modules/2.6.32-573.18.1.el6.x86_64/extra/zavl.ko
lrwxrwxrwx 1 root root   56 May  3 18:10 zcommon.ko -> /lib/modules/2.6.32-504.23.4.el6.x86_64/extra/zcommon.ko
lrwxrwxrwx 1 root root   52 May  3 18:10 zfs.ko -> /lib/modules/2.6.32-504.23.4.el6.x86_64/extra/zfs.ko
lrwxrwxrwx 1 root root   56 May  3 16:42 znvpair.ko -> /lib/modules/2.6.32-504.23.4.el6.x86_64/extra/znvpair.ko
lrwxrwxrwx 1 root root   54 May  3 18:10 zpios.ko -> /lib/modules/2.6.32-504.23.4.el6.x86_64/extra/zpios.ko
lrwxrwxrwx 1 root root   57 May  3 16:42 zunicode.ko -> /lib/modules/2.6.32-504.23.4.el6.x86_64/extra/zunicode.ko

So for some reason they are symbolic linking to modules from older kernels. That seems like a bug. All of the links are broken except for spl.ko and zavl.ko. One thing I noticed is that the current kernel (2.6.32-573.22.1.el6.x86_64) does not have an "extra" directory. Not sure if that matters but it might mean something. 

I just removed the to 2.6.32-504 kernels and devel packages and removed spl/zfs with the dkms packages too. The weak-updates directory then looked the same as before so I deleted the links. Then I ran "yum install zfs" and it created the "extra" directory and put the zfs modules in there.

"modprobe zfs" now works and "zpool import -a" brought the pools in. 

So, I think the problem was that the weak-updates directory had those links in there and it was screwing things up with dkms. Is this a known issue? Something that can be fixed?

Thanks,

Steve

**Comment by dasjoe** [comment]
It's a known issue with RHEL and derivatives that weak-installed DKMS modules get in the way.
You can either remove everything ZFS-related and reinstall or switch to KMOD packages instead of DKMS, as described in https://github.com/zfsonlinux/zfs/issues/3801#issuecomment-142444518.

**Comment by deajan** [comment]
For a quickfix see https://github.com/zfsonlinux/zfs/issues/2400#issuecomment-46118193

**Comment by cousins** [comment]
Can the zfs-dkms and spl-dkms packages do this checking and fixing when they are updated?

**Comment by behlendorf** [comment]
Improved [kmod/dkms documentation is available for RHEL/CentOS](https://github.com/zfsonlinux/zfs/wiki/RHEL-%26-CentOS) on the wiki.

It's definitely possible to improve the dkms packages but I'd recommend switching to the kmods.  If someone wants to propose a fix for the dkms patches that would be great.

**Comment by cousins** [comment]
I just freed up a system to test this (kmod on CentOS) on and it worked fine. Much improved from the dkms route. Thanks very much!

**Comment by deajan** [comment]
I moved from dkms to kmod today on my personnal server.
Removing and reinstalling zfs isn't enough, because earlier compiled kernel modules from dkms still load.
```
[    5.380540] spl: module verification failed: signature and/or required key missing - tainting kernel
[    5.425831] systemd-journald[399]: Received request to flush runtime journal from PID 1
[    5.447698] SPL: Loaded module v0.6.5.5-1
[    5.468523] znvpair: module license 'CDDL' taints kernel.
[    5.470475] Disabling lock debugging due to kernel taint
[    5.499588] zfs: disagrees about version of symbol spl_kmem_cache_reap_now
[    5.499592] zfs: Unknown symbol spl_kmem_cache_reap_now (err -22)
[    5.499874] zfs: disagrees about version of symbol spl_kmem_cache_set_move
[    5.499876] zfs: Unknown symbol spl_kmem_cache_set_move (err -22)
[    5.500063] zfs: disagrees about version of symbol spl_kmem_cache_alloc
[    5.500064] zfs: Unknown symbol spl_kmem_cache_alloc (err -22)
[    5.500193] zfs: disagrees about version of symbol spl_kmem_cache_create
[    5.500194] zfs: Unknown symbol spl_kmem_cache_create (err -22)
[    5.500783] zfs: disagrees about version of symbol spl_kmem_cache_destroy
[    5.500784] zfs: Unknown symbol spl_kmem_cache_destroy (err -22)
[    5.500871] zfs: disagrees about version of symbol spl_kmem_cache_free
[    5.500872] zfs: Unknown symbol spl_kmem_cache_free (err -22)
```

So here are the steps to make a clean zfs (dkms or kmod) install.
```
yum remove $(rpm -qa | egrep "zfs|spl" | grep -v "zfs-release")
find /lib/modules/ -name "splat.ko" -or -name "zcommon.ko" -or -name "zpios.ko" -or -name "spl.ko" -or -name "zavl.ko" -or -name "zfs.ko" -or -name "znvpair.ko" -or -name "zunicode.ko"
```
Optionnal but recommended step to enable kmod instead of dkms installation unless a non standard kernel is used
```
sed -i's#baseurl=http://archive.zfsonlinux.org/epel/7/$basearch/#baseurl=http://archive.zfsonlinux.org/epel/7/kmod/$basearch/#' /etc/yum.repos.d/zfs.repo
sed -i 's#baseurl=http://archive.zfsonlinux.org/epel-testing/7/$basearch/#baseurl=http://archive.zfsonlinux.org/epel-testing/7/kmod/$basearch/#' /etc/yum.repos.d/zfs.repo
```
Final step to reinstall zfs
```
yum install zfs
```

@behlendorf I know this has been discussed multiple times, but as there are alot of issues regarding this, maybe this could be added to the installation doc ?

**Comment by behlendorf** [comment]
@deajan good thought, I've [updated the wiki](https://github.com/zfsonlinux/zfs/wiki/RHEL-&-CentOS#switching-from-dkms-to-kabi-tracking-kmod) accordingly.  Feel free to recommend further improvements to the documentation.

**Comment by maltefiala** [comment]
Same problem here, clean install of latest centos and a `yum update` afterwards.
Current kernel: `3.10.0-514.6.1.el7.x86_64`

## Steps
```bash
yum update
# Import zfs.repo
yum install zfs
reboot
zfs list
> The ZFS modules are not loaded.
> Try running '/sbin/modprobe zfs' as root to load them.
/sbin/modprobe zfs
> modprobe: FATAL: Module zfs not found.
```

Not fixable with solution above. May be related to #5191

DKMS install works fine. However, `yum install epel-release` is missing from [howto](https://github.com/zfsonlinux/zfs/wiki/RHEL-%26-CentOS#dkms)

**Comment by deajan** [comment]
For CentOS 7.3 you need a separate repo, see the wiki.
