### ISSUE TITLE
zdb can't see zpools which have been imported readonly - It should be able to

### ISSUE THREAD

**Issue by JuliaVixen** [zfsonlinux/zfs#4598]
Every now and then, I need to do some low-level zfs recovery (for example because I "replaced" some drives, and then later needed to recover the data from the original "destroyed" drives, but that's another story. This feature, #4187, would be so incredibly useful.) , or at least just look at a device/pool without writing to it. Anyway, "zdb" only works on zpools which are:
1. importable
2. imported writeable

The times when you really _really_ would want to use "zdb", is when you're investigating why you can't import some devices, or you want to investigate a zpool's metadata without it getting messed up by a bunch of new metadata writes.

So, I'm really talking about two things here, which should probably be two different issues, but it would be very very useful if 'zdb' could be used on single or multiple block devices, which can't be imported, or even seen by "zpool import". And also, using 'zdb' on healthy zpools which have been imported 'readonly'.

Right now only "zdb -lu /dev/whatever" is the only thing you can do with a block device.

And "zdb -anything" doesn't work when you import pools like this:

```
localhost ~ # zpool import -o readonly=on example
localhost ~ # zpool list
NAME          SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
example      21.8T  20.9T   825G         -     0%    96%  1.00x  ONLINE  -
writeable    36.2T  24.3T  11.9T         -    37%    67%  1.00x  ONLINE  -

localhost ~ # hexdump -C /etc/zfs/zpool.cache 
[There's just the 'writeable' pool in there]

localhost ~ # zdb -C  
writable:
    version: 5000
    name: 'writable'
    state: 0
[etc etc, just this one pool]

localhost ~ # zdb -d example
zdb: can't open 'example': No such file or directory

-- 

[But, re-import read-write...]

localhost ~ # zpool export example
localhost ~ # zpool import example
localhost ~ # zdb -C
example:
    version: 5000
    name: 'example'
    state: 0
    txg: 5195339
[etc. etc.]
writable:
    version: 5000
    name: 'writable'
    state: 0
[etc. etc.]

localhost ~ # zdb -d example
Dataset mos [META], ID 0, cr_txg 4, 354M, 680 objects
Dataset example/stuff@2015_Jul_8 [ZPL], ID 330, cr_txg 1261118, 10.1T, 1910968 objects
[etc. etc.]
```

**Comment by behlendorf** [comment]
@JuliaVixen The good news if you can do this today by requesting `zdb` treat the pool as if it is exported by passing the -e option.  For example: `zdb -e -d example`.

Although I agree you shouldn't need to use this option on a pool imported readonly and that should be investigated.

```
       -e [-p path]...

           Operate on an exported pool, not present  in  /etc/zfs/zpool.cache.
           The  -p  flag  specifies  the  path  under  which devices are to be
           searched.
```

**Comment by richardelling** [comment]
In upstream, zdb is expected to be run without root privilege. So it doesn't require a kernel or private and privileged interface. In other words, use -e and -d when you want to explicitly look at files/devices and not rely on being able to read kernel state or /etc/zfs/zpool.cache.

**Comment by sskras** [comment]
@behlendorf wrote:

> The good news if you can do this today by requesting `zdb` treat the pool as if it is exported by passing the -e option. For example: `zdb -e -d example`.
> 
> Although I agree you shouldn't need to use this option on a pool imported readonly and that should be investigated.

I just got his on CentOS 7.9 + OpenZFS-0.8.6, I imported rpool from OmniOS as read-only:
```
$ sudo zpool import -o readonly=on -R /mnt rpool -f
$ zpool list -v
NAME        SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
rpool       232G  2.14G   230G        -         -     0%     0%  1.00x    ONLINE  /mnt
  sda       232G  2.14G   230G        -         -     0%  0.92%      -  ONLINE  

$ zfs list
NAME                        USED  AVAIL     REFER  MOUNTPOINT
rpool                      3.21G   222G     25.5K  /mnt/rpool
rpool/ROOT                 1.14G   222G       24K  legacy
rpool/ROOT/omnios-r151032  1.14G   222G     1.14G  /mnt
rpool/dump                 1.00G   222G     1.00G  -
rpool/swap                 1.06G   223G       12K  -
```
It's still the same:
```
$ zdb
cannot open '/etc/zfs/zpool.cache': No such file or directory
```
Should this be reopened? Or maybe reported as a new bug?
