### ISSUE TITLE
/sbin/lsmod: No such file or directory

### ISSUE THREAD

**Issue by prakashsurya** [zfsonlinux/zfs#460]
On my archlinux install, the lsmod program is installed in '/bin/lsmod'. As a result, when running 'make check' I receive many '/sbin/lsmod: No such file or directory' errors. It would be nice to clean this up. Setting the $LSMOD environment variable to the correct location appears to allow the tests to run just fine.

**Comment by behlendorf** [comment]
@ryao is this still a Gentoo issue and if so what did you do to address it?  Can it be taken upstream or shall we just close this out and a downstream issue.

**Comment by behlendorf** [comment]
Closing as a distribution specific issue.
