### ISSUE TITLE
task zfs or txg_sync blocked for more than seconds during snapshot creation and deletion

### ISSUE THREAD

**Issue by mailinglists35** [zfsonlinux/zfs#4604]
This is happening every day when zfs-auto-snapshot cron kicks in, basically since ever with all kernels (3.x, 4.x), ocasionally at first but now it's stressing enough to file this issue.

root@homerouter:~# cat /etc/cron.daily/zfs-auto-snapshot
# !/bin/sh

exec zfs-auto-snapshot --quiet --syslog --label=daily --keep=31 //

[stack.txt](https://github.com/zfsonlinux/zfs/files/252734/stack.txt)
[zpool-status.txt](https://github.com/zfsonlinux/zfs/files/252739/zpool-status.txt)
[zpool-get-all.txt](https://github.com/zfsonlinux/zfs/files/252751/zpool-get-all.txt)
[zfs-get-all.txt](https://github.com/zfsonlinux/zfs/files/252752/zfs-get-all.txt)
[spl-parameters.txt](https://github.com/zfsonlinux/zfs/files/252805/spl-parameters.txt)
[zfs-parameters.txt](https://github.com/zfsonlinux/zfs/files/252806/zfs-parameters.txt)
[kstats.txt](https://github.com/zfsonlinux/zfs/files/252807/kstats.txt)
(to directly view the text files instead of having to save first, this firefox addon overrides content-disposition httpheader and makes the browser display the file https://addons.mozilla.org/en-us/firefox/addon/bypass-forced-download/)
hw: Core(TM)2 Duo CPU     E8200  @ 2.66GHz, 4Gb RAM, 2x1Tb sata hdd

zfs list -t all | wc -l
53635

**Comment by mailinglists35** [comment]
hello?

**Comment by behlendorf** [comment]
@mailinglists35 15 seconds is a pretty aggressive timeout for `hung_task_timeout_secs`.  What the watchdog message here signifies in we're performing too much work in the txg sync task and it's taken longer than 15 to handle this transaction group.  This shouldn't cause any problems and would go entirely unnoticed with the default `hung_task_timeout_secs`.

What might be causing this is requesting too many snapshots be created/destroyed in a single TXG.

**Comment by mailinglists35** [comment]
@behlendorf I have set this to 15 sec because i wanted to catch earlier the stacks. but even if I leave it at default i still receive the message
