### ISSUE TITLE
Temporary IO freezes on compressed volumes

### ISSUE THREAD

**Issue by gmelikov** [zfsonlinux/zfs#4609]
Hello, i have whole system freezes on compressed zvol, compress algoritm is default, atime disabled. Maybe this is similar to #4320.

I can reproduce it (for example, recheck Deluge downloaded torrents), have more than 5 second freezes (time differs for huge files - 15gb file check freezes my PC for 2 minutes).

`echo 3 > /proc/sys/vm/drop_caches` helps for a time until zfs cache exceeds my ram, i think, after that i have freezes.

It's process independent, i get freezes on io load to compressed zvol.

Debian Jessie, 
Linux kernel 4.5 4.5.0-0.bpo.1-amd64 SMP Debian 4.5.1-1~bpo8+1 (2016-04-20) x86_64 GNU/Linux (i had freezes on 4.4 too)
zfs 0.6.5.6. 

16gb RAM, intel i5 6600k.

`zfs get all fs2/main`
> NAME      PROPERTY              VALUE                      SOURCE
> fs2/main  type                  filesystem                 -
> fs2/main  creation              Сб окт 31 16:37 2015  -
> fs2/main  used                  265G                       -
> fs2/main  available             303G                       -
> fs2/main  referenced            265G                       -
> fs2/main  compressratio         1.11x                      -
> fs2/main  mounted               yes                        -
> fs2/main  quota                 none                       default
> fs2/main  reservation           none                       default
> fs2/main  recordsize            128K                       default
> fs2/main  mountpoint            /data/fs1                  local
> fs2/main  sharenfs              off                        default
> fs2/main  checksum              on                         default
> fs2/main  compression           on                         local
> fs2/main  atime                 off                        inherited from fs2
> fs2/main  devices               on                         default
> fs2/main  exec                  on                         default
> fs2/main  setuid                on                         default
> fs2/main  readonly              off                        default
> fs2/main  zoned                 off                        default
> fs2/main  snapdir               hidden                     default
> fs2/main  aclinherit            restricted                 default
> fs2/main  canmount              on                         default
> fs2/main  xattr                 on                         default
> fs2/main  copies                1                          default
> fs2/main  version               5                          -
> fs2/main  utf8only              off                        -
> fs2/main  normalization         none                       -
> fs2/main  casesensitivity       sensitive                  -
> fs2/main  vscan                 off                        default
> fs2/main  nbmand                off                        default
> fs2/main  sharesmb              off                        default
> fs2/main  refquota              none                       default
> fs2/main  refreservation        none                       default
> fs2/main  primarycache          all                        default
> fs2/main  secondarycache        all                        default
> fs2/main  usedbysnapshots       0                          -
> fs2/main  usedbydataset         265G                       -
> fs2/main  usedbychildren        0                          -
> fs2/main  usedbyrefreservation  0                          -
> fs2/main  logbias               latency                    default
> fs2/main  dedup                 off                        default
> fs2/main  mlslabel              none                       default
> fs2/main  sync                  standard                   default
> fs2/main  refcompressratio      1.11x                      -
> fs2/main  written               265G                       -
> fs2/main  logicalused           295G                       -
> fs2/main  logicalreferenced     295G                       -
> fs2/main  filesystem_limit      none                       default
> fs2/main  snapshot_limit        none                       default
> fs2/main  filesystem_count      none                       default
> fs2/main  snapshot_count        none                       default
> fs2/main  snapdev               hidden                     default
> fs2/main  acltype               off                        default
> fs2/main  context               none                       default
> fs2/main  fscontext             none                       default
> fs2/main  defcontext            none                       default
> fs2/main  rootcontext           none                       default
> fs2/main  relatime              off                        default
> fs2/main  redundant_metadata    all                        default
> fs2/main  overlay               off                        default

[dmesg.txt](https://github.com/zfsonlinux/zfs/files/250653/dmesg.txt) after `echo 3 > /proc/sys/vm/drop_caches` and more than 2 minute freezes.

What additional info can i give? Thanks!

**Comment by kpande** [comment]
is your system hitting severe memory pressure?

**Comment by gmelikov** [comment]
If you mean free ram for zfs cache - i usually have max 8gb of 16 used by processes. When i've got this problem i had ~6gb  of used ram. In the worst case i have 3gb of free/cached memory.

**Comment by kpande** [comment]
do you have the ability to test with latest git master?

**Comment by gmelikov** [comment]
I've recently updated to 0.6.5.7 and enabled xattr sa, trying to reproduce problem now.

Can this problem be in default xattr? If yes then i'll test it on new zvol with it.

It's a workstation, i'm afraid i can't test latest git master for now.

**Comment by gmelikov** [comment]
I didn't have such long freezes after i set xattr=sa, i think this issue should be closed then. thanks for help.
