### ISSUE TITLE
SPL version different for compilation under Ubuntu?

### ISSUE THREAD

**Issue by Ralithune** [zfsonlinux/zfs#4625]
I don't know if this is the appropriate place for this - I apologize in advance if it is not.

When trying to set up ZoL from a git clone on Ubuntu 14.04.1, "configure" throws the following error:
```
configure: error:
        *** Please make sure the kmod spl devel package for your distribution
        *** is installed then try again.  If that fails you can specify the
        *** location of the spl source with the '--with-spl=PATH' option.
        *** The spl version must match the version of ZFS you are building,
        *** 0.6.5.  Failed to find spl.release.in in the following:

                /var/lib/dkms/spl/0.6.5/build
                /usr/local/src/spl-0.6.5/3.19.0-25-generic
                /usr/local/src/spl-0.6.5
                /usr/src/spl-0.6.5/3.19.0-25-generic
                /usr/src/spl-0.6.5
                ../spl/
                /usr/src/linux-headers-3.19.0-25-generic,
```
I have SPL installed (apt-get -y install zpl-dev), but it's showing up as version 0.6.5.6:

```
root@ubuntu:~/zfs# ls /var/lib/dkms/spl/
0.6.5.6/                         kernel-3.19.0-25-generic-x86_64/
```

Am I doing something wrong, or is this an issue?

**Comment by drescherjm** [comment]
The zfs-discuss mailing list is for these type of requests.

https://github.com/zfsonlinux/zfs/wiki/Mailing-Lists

**Comment by Ralithune** [comment]
For anyone finding this, git cloning the SPL git and compiling / installing it from source solved the issue.
