### ISSUE TITLE
ztest: ztest_ddt_repair() ASSERT

### ISSUE THREAD

**Issue by crawfxrd** [zfsonlinux/zfs#4626]
There appears to be [an assert](https://github.com/zfsonlinux/zfs/blob/master/cmd/ztest/ztest.c#L5268-5269) in `ztest_ddt_repair` that is not always valid. Occasionally during testing a dataset's `ds_fsid_guid` would change. This value is used to calculate a pattern for testing the DDT layer. If the GUID changed since the last time that the pattern was set, the assert would fail and `ztest` would crash as a result.

This is the command that was run in a loop and eventually caused `ztest` to crash:

```
ztest -t 1 -VVVVV -m 2 -r 0 -R 1 -v 2 -a 9 -T 86 -P 19 -s 128m -f /mnt
```

Tested against f00828e on master.

**Comment by behlendorf** [comment]
Resolved by 546d32ca102675caed534075f9e7517890707d7b
