### ISSUE TITLE
zpool list -vp should print statistics for vdevs also parsable.

### ISSUE THREAD

**Issue by chrekh** [zfsonlinux/zfs#4646]
zpool list -vp prints the total statistics for the pool parsable. It
would be nice if it did that for the individual vdevs also.

**Comment by behlendorf** [comment]
It definitely should, this sounds like bug.  @tonyhutter has been working in this area of the code and might have some thoughts about this.

**Comment by chrekh** [comment]
While at it, the manpages uses 'parsable' in some places, and 'parseable' in other.
It should be easy to grep for one of them and replace it with the other.

**Comment by tonyhutter** [comment]
193a37c updated `zpool iostat` to let you pass in pool names, vdevs in a specific pool, or vdevs in any pools.  If you want to implement this for `zpool list` as well, I'd recommend taking a look at `zpool_main.c:zpool_do_iostat()`.

**Comment by chrekh** [comment]
I kind of hoped you would fix it! ;) C isn't my strongest language.

But, now you got me motivated, so I made a kind of least effort change
in function print_one_column with #4656

**Comment by chrekh** [comment]
I tried to fix style-issues by deleting the branch and push a new. Obviously that isn't the right way to do it since that closed the pull-request ;)
(What is the correct way to change a commit in a pull-request?)

Anyway, I made a new pull-request instead. #4657

**Comment by behlendorf** [comment]
@chrekh you can force update the branch to refresh the PR.  Thanks for tackling this.

**Comment by chrekh** [comment]
This is now fixed with bc2d809
