### ISSUE TITLE
ZFS incompatible with grsecurity RAP feature

### ISSUE THREAD

**Issue by pospim19** [zfsonlinux/zfs#4649]
Hi, I tried build ZFS module under 4.5.4 kernel with fresh grsecurity patchset, which got new feature - Return Address Protection. It built fine, but when I tried include built module into kernel following message appeared:
```
May 15 10:16:39 grsec-compiler kernel: zavl: module is not compatible with the KERNEXEC 'or' method and RAP
```
Seems ZFS doesn't support RAP right now.

**Comment by mrobbetts** [comment]
FWIW, I'm also seeing this same problem with 4.6.5 + grsecurity.

**Comment by xea** [comment]
Same here with Gentoo 4.6.4-hardened-r3.

**Comment by behlendorf** [comment]
Closing, won't fix.  RAP and *binary* out-of-tree modules are not compatible, but since full source is available for ZFS this is something which the distribution might  be able to handle.
