### ISSUE TITLE
zpool locked up, zfs processes in D state

### ISSUE THREAD

**Issue by osd1000** [zfsonlinux/zfs#4650]
I have a zpool composed of 36 disks as 4*RAIDZ2 which locked up over the weekend such that all zfs commands got stuck in D state and and files were not available remotely over NFS or SMB.  (To my shame, I didn't check whether files were accessible locally - sorry!)

I have cronjobs which run various combinations of zfs snapshot, zfs send, and zfs destroy frequently (every five minutes or so) to maintain snapshots and send them to a replica host.  Additionally, a scrub was in progress at the time of the hang.

The kernel log at around the time things got wedged is attached.

This is Ubuntu 14.04 with the following zfs packages installed:

```
root@marrow:~# dpkg -la | grep zfs
ii  dkms                                2.2.0.3-1.1ubuntu5.14.04.1+zfs10~trusty all          Dynamic Kernel Module Support Framework
ii  libzfs2                             0.6.5.3-1~trusty                        amd64        Native OpenZFS filesystem library for Linux
ii  mountall                            2.53-zfs1                               amd64        filesystem mounting tool
ii  zfs-auto-snapshot                   1.1.0-0ubuntu1~trusty                   all          ZFS Automatic Snapshot Service
ii  zfs-dkms                            0.6.5.3-1~trusty                        amd64        Native OpenZFS filesystem kernel modules for Linux
ii  zfs-doc                             0.6.5.3-1~trusty                        amd64        Native OpenZFS filesystem documentation and examples.
ii  zfs-zed                             0.6.5.3-1~trusty                        amd64        OpenZFS Event Daemon (zed)
ii  zfsutils                            0.6.5.3-1~trusty                        amd64        Native OpenZFS management utilities for Linux
root@marrow:~#
```

[marrow-incident-160516-kern.txt](https://github.com/zfsonlinux/zfs/files/265910/marrow-incident-160516-kern.txt)

**Comment by behlendorf** [comment]
@osd1000 thanks for opening the issue so we can track this.

**Comment by dweeezil** [comment]
@osd1000 Is this easily reproducible?  If so, it would be worth trying 0.6.5.7 which, among other things, has zfsonlinux/spl@89a2234 which might be relevant.

**Comment by osd1000** [comment]
On Monday, 16 May 2016, Tim Chase wrote:

> @osd1000 Is this easily reproducible?

Not really.  The server in question has been in service since the
start of the year and this is the first time this has happened.

> If so, it would be worth trying 0.6.5.7 which, among other things,
> has zfsonlinux/spl@89a2234 which might be relevant.

That looks plausible, doesn't it?  I'll try that release on my
development server and on the live one if/when we get another hangup.

Owen
-- 
`Touch can bring blossom to things that decay.'

**Comment by osd1000** [comment]
Just a quick update to say I applied 0.6.5.7 and have not seen the lockup since...

**Comment by kpande** [comment]
I'm going to close this, please re-open if the deadlock reoccurs.
