### ISSUE TITLE
logicalused doesn't include blocks of zeros when compress=on

### ISSUE THREAD

**Issue by tuxoko** [zfsonlinux/zfs#4660]
Hi, I noticed an interesting behaviour regarding logicalused and logicalreferenced when compress=on.

If I write blocks of zeros, lused and lrefer will not increase.

```
# dd if=/dev/zero of=/dev/zd0 bs=1M count=16 oflag=direct
# zfs get lused,lrefer pp/vol0
NAME     PROPERTY           VALUE   SOURCE
pp/vol0  logicalused        4K      -
pp/vol0  logicalreferenced  4K      -
```

If I write blocks of ones, lused and lrefer do increase.

```
# dd if=/dev/zero bs=1M count=16 | tr '\000' '\377' | dd of=/dev/zd0 oflag=direct
# zfs get lused,lrefer pp/vol0
NAME     PROPERTY           VALUE   SOURCE
pp/vol0  logicalused        16.0M   -
pp/vol0  logicalreferenced  16.0M   -
```

I'm not sure if this is intented or not, but I kind of get it that we don't write anything for blocks of zeros, so we don't have a good way to track whether those are blocks of zero or hole. However, according to the `man zfs(8)` lused and lrefer ignores compression, so it's kind of confusing.

Any idea if this behaviour can be "fixed", or should we just add notes in the document?

**Comment by DeHackEd** [comment]
Compression specifically detects all-zero blocks and turns them into true sparse holes. Nothing is written, compressed or otherwise.

So, yes. It's both.

https://github.com/zfsonlinux/zfs/blob/master/module/zfs/zio_compress.c#L99

**Comment by tuxoko** [comment]
Both?
My question that the document says logicalused ignores compression effect, but in reality compression does have effect on zero blocks.

I figure we probably can't "fix" this behaviour unless we don't compress zero blocks to hole. So we should probably add that to the document.

**Comment by DeHackEd** [comment]
"whether those are blocks of zero or hole". Enabling compression means these are equivalent.

While the fact that this happens is fairly well known, it it indeed not documented in the man page nor do I know of official documentation that mentions it.
