### ISSUE TITLE
Snapshots are showing unreachable inside snapdir

### ISSUE THREAD

**Issue by shilpi230** [zfsonlinux/zfs#4661]
It is like this when I cd into some folder. 

`Linux 3.19.0-58-generic`

`shilpi@minions-gcp:(unreachable)/folder`

**Comment by rlaager** [comment]
I can reproduce this as well.

**Comment by behlendorf** [comment]
Can you post a reproducer and a zfs version you're able to reproduce this with.  This is the first report of this I've heard.

**Comment by rlaager** [comment]
Well, perhaps I spoke too soon. I saw it happen yesterday, but I can't reproduce it at will today. I'm on 0.6.5.6-0ubuntu8 on 16.04 (Xenial) with Linux 4.4.0-22-generic.

**Comment by shilpi230** [comment]
This is exactly happening when I give rollback to any snapshot folder, every other folder including itself becomes unreachable.

**Comment by tuxoko** [comment]
@shilpi230 Thanks for the reproducer
```
//go into snapdir
# cd /pp/.zfs/snapshot/003
# mount | grep 003
pp@003 on /pp/.zfs/snapshot/003 type zfs (ro,relatime,xattr,noacl)

//rollback and mount is gone
# zfs rollback pp@003
# mount | grep 003

//try going into a directory
# cd dd
# pwd
(unreachable)/dd

//while the above process stays inside, another process does
# cd /pp/.zfs/snapshot/003
bash: cd: /pp/.zfs/snapshot/003: Too many levels of symbolic links
```

The unreachable will happen for anything inside a detached mount point (umount -l).
So basically what happens is that a rollback will cause all snapdir to detach.
The problem seems to caused by doing rezget on snapdir.

**Comment by tuxoko** [comment]
This also happen whenever you do recv.
https://github.com/zfsonlinux/zfs/issues/4514

**Comment by shilpi230** [comment]
Thank you @behlendorf :) will use this commit and let u know if this works. 👍

**Comment by behlendorf** [comment]
@shilpi230 definitely let us know if this doesn't resolve the issue, and thank @tuxoko for the fix!
