### ISSUE TITLE
Linux 4.7 Parallel Filesystem Directory Handling Compatibility

### ISSUE THREAD

**Issue by dracwyrm** [zfsonlinux/zfs#4664]
There was a new commit that finally makes readdir parallel instead of serial. To use this, filesystems need to switch to "iterate_shared()" which only takes a read lock. More info in patch here:
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=7f427d3a6029331304f91ef4d7cf646f054216d2

Is this something ZFS can make use of?

Cheers.

**Comment by behlendorf** [comment]
@dracwyrm this is definitely something we're going to have to look at.  These changes break the build for 4.7 kernels by making small changes to several interfaces we depend on.  @tuxoko if you have the time it would be great if you could look at this.

**Comment by tuxoko** [comment]
I haven't looked very closely yet. But the main change is making inode_lock
an rwsem, which is handled in vfs. So we should be able to support this
without much change.

**Comment by behlendorf** [comment]
@tuxoko I've only briefly looked a this myself but I did notice they also made a trivial change to the get xattr interface (again).  I suspect you're right resolving this should be pretty straight forward, it'll just require a little bit of compatibility code.

**Comment by dracwyrm** [comment]
Good to hear. Also of note, this doesn't necessarily speed up access as there is already caching done, so only special use cases will speed up. Like the Samba incident 10 years ago. Makes me wonder if it will speed up VM access.
