### ISSUE TITLE
ZED does not send mails

### ISSUE THREAD

**Issue by hcw70** [zfsonlinux/zfs#4667]
When testing ZED under Ubuntu 12.04, zed starts normally but does not report mails for scrub errors.

From Syslog: 

> May 19 12:04:37 mediasrv zed[30840]: ZFS Event Daemon 0.6.5.4-1~precise (PID 30840)
> May 19 12:04:37 mediasrv zed[30840]: Processing events since eid=401
> 

Tested a fail event by running dd over a LVM zfs volume and then doing a scrub.
The event is reported in zpool events:

> May 19 2016 11:57:19.371572313 ereport.fs.zfs.checksum
> May 19 2016 11:57:19.439573188 ereport.fs.zfs.checksum
> May 19 2016 11:57:19.439573188 ereport.fs.zfs.checksum
> May 19 2016 11:57:25.227647610 ereport.fs.zfs.scrub.finish
> May 19 2016 12:05:03.389531829 ereport.fs.zfs.io
> 

but no mail is sent and no output from zed.
 
My zed conf (comments removed):

> ZED_DEBUG_LOG="/tmp/zed.debug.log"
> ZED_EMAIL_ADDR="root"
> ZED_EMAIL_PROG="mail"
> ZED_EMAIL_OPTS="-s '@SUBJECT@' @ADDRESS@"
> ZED_LOCKDIR="/var/lock"
> ZED_NOTIFY_INTERVAL_SECS=3600
> ZED_NOTIFY_VERBOSE=1
> ZED_RUNDIR="/var/run"
> ZED_SYSLOG_PRIORITY="daemon.notice"
> ZED_SYSLOG_TAG="zed"
>

**Comment by rlaager** [comment]
Symlink everything from /usr/lib/zfs-linux/zfs/zed.d (except all-debug.sh and generic-notify.sh) into /etc/zfs/zed.d.

**Comment by hcw70** [comment]
Thanks for the hint. However, still not sending mails. In syslog now i see some messages:

> May 24 09:05:15 mediasrv zed[23528]: ZFS Event Daemon 0.6.5.4-1~precise (PID 23528)
> May 24 09:05:15 mediasrv zed[23528]: Processing events since eid=591
> May 24 09:05:56 mediasrv zed[23528]: Invoking "all-syslog.sh" eid=592 pid=23604
> May 24 09:05:56 mediasrv zed[23528]: Finished "all-syslog.sh" eid=592 pid=23604 exit=2
> May 24 09:05:56 mediasrv zed[23528]: Invoking "all-syslog.sh" eid=593 pid=23605
> May 24 09:05:56 mediasrv zed[23528]: Finished "all-syslog.sh" eid=593 pid=23605 exit=2
> May 24 09:05:56 mediasrv zed[23528]: Invoking "checksum-notify.sh" eid=593 pid=23606
> May 24 09:05:56 mediasrv zed[23528]: Finished "checksum-notify.sh" eid=593 pid=23606 exit=2
> May 24 09:05:56 mediasrv zed[23528]: Invoking "checksum-spare.sh" eid=593 pid=23607
> May 24 09:05:56 mediasrv zed[23528]: Finished "checksum-spare.sh" eid=593 pid=23607 exit=2
>

**Comment by hcw70** [comment]
BTW, is the symlink issue fixed with later debian packages?
Regards
Hauke

**Comment by hcw70** [comment]
Please note that the file "zed-functions.sh" is not present in the zfs-zed debian package. This is referenced in the script files which i did symlink above.

**Comment by rlaager** [comment]
The missing zed-functions.sh is probably an issue.

**Comment by rlaager** [comment]
This is definitely fixed in Ubuntu 16.04.

**Comment by behlendorf** [comment]
@FransUrbo can you comment on `zed-functions.sh` being missing in the Debian packaging?

**Comment by hcw70** [comment]
> $ dpkg -L zfs-zed 
> /.
> /usr
> /usr/share
> /usr/share/doc
> /usr/share/man
> /usr/share/man/man8
> /usr/share/man/man8/zed.8.gz
> /usr/lib
> /usr/lib/zfs-linux
> /usr/lib/zfs-linux/zfs
> /usr/lib/zfs-linux/zfs/zed.d
> /usr/lib/zfs-linux/zfs/zed.d/scrub.finish-notify.sh
> /usr/lib/zfs-linux/zfs/zed.d/resilver.finish-notify.sh
> /usr/lib/zfs-linux/zfs/zed.d/checksum-spare.sh
> /usr/lib/zfs-linux/zfs/zed.d/io-spare.sh
> /usr/lib/zfs-linux/zfs/zed.d/data-notify.sh
> /usr/lib/zfs-linux/zfs/zed.d/all-syslog.sh
> /usr/lib/zfs-linux/zfs/zed.d/checksum-notify.sh
> /usr/lib/zfs-linux/zfs/zed.d/all-debug.sh
> /usr/lib/zfs-linux/zfs/zed.d/generic-notify.sh
> /usr/lib/zfs-linux/zfs/zed.d/io-notify.sh
> /usr/sbin
> /usr/sbin/zed
> /etc
> /etc/zfs
> /etc/zfs/zed.d
> /etc/zfs/zed.d/zed.rc
> /etc/init.d
> /etc/init
> /etc/init/zed.conf
> /usr/share/doc/zfs-zed
> /etc/init.d/zed
> $ dpkg -l zfs-zed 
> Gewünscht=Unbekannt/Installieren/R=Entfernen/P=Vollständig Löschen/Halten
> | Status=Nicht/Installiert/Config/U=Entpackt/halb konFiguriert/
>          Halb installiert/Trigger erWartet/Trigger anhängig
> |/ Fehler?=(kein)/R=Neuinstallation notwendig (Status, Fehler: GROSS=schlecht)
> ||/ Name           Version        Beschreibung
> +++-==============-==============-============================================
> ii  zfs-zed        0.6.5.4-1~prec OpenZFS Event Daemon (zed)
>

**Comment by FransUrbo** [comment]
Well, I'm not building a separate zfs-zed package! I never saw the point - it's needed everywhere where <code>zpool</code> is. So I package it in the **zfsutils** package..

So wherever that  package and file is coming from (or not coming from in this case :), it's not from me/us.

**Comment by hcw70** [comment]
Its from http://ppa.launchpad.net/zfs-native/stable/ubuntu precise main

> $ apt-cache show zfs-zed
> Package: zfs-zed
> Source: zfs-linux
> Priority: extra
> Section: admin
> Installed-Size: 148
> Maintainer: Darik Horn <dajhorn@vanadac.com>
> Architecture: amd64
> Version: 0.6.5.4-1~precise
> Recommends: mail-transport-agent
> Replaces: zfsutils
> Depends: upstart-job, zfs-doc, libc6 (>= 2.14), libnvpair1, libzfs2, zfsutils
> Filename: pool/main/z/zfs-linux/zfs-zed_0.6.5.4-1~precise_amd64.deb
> Size: 30836
> MD5sum: 815ebf8d145623b62b96e858d65b7513
> SHA1: 98b087792c528b537aae7949798631c71ea489ac
> SHA256: b31c5f34392cc043c8e22f3a2d70ef1d5f6bfc9e82892091baa982d4495d5961
> Description-en: OpenZFS Event Daemon (zed)
>  A monitor that automatically runs scripts for OpenZFS kernel events,
>  like disk failures.
> Description-md5: 9bcf67f0c1851d4e5d328bb062f48199
>

**Comment by FransUrbo** [comment]
Ah, I didn't read the whole thing. You said **debian package**..

**Comment by hcw70** [comment]
Is there a solution to my problem? Should i rebuild my debian package or extract the missing files from somewhere?

Kind regards

Hauke

**Comment by FransUrbo** [comment]
> Is there a solution to my problem? Should i rebuild my debian package or extract the missing files from somewhere?
> 

Simples would just to take it from https://raw.githubusercontent.com/zfsonlinux/zfs/master/cmd/zed/zed.d/zed-functions.sh.

**Comment by hcw70** [comment]
Ok, with the "zed-functions.sh" in place and also symlinked, zed works!

Kind regards

Hauke
