### ISSUE TITLE
Created pool with by-id but on reboot it uses sdX

### ISSUE THREAD

**Issue by hippie131** [zfsonlinux/zfs#4669]
I'm on Ubuntu 14.04 with the latest zfs installed for the PPA. Here is the history:
zpool history
History for 'mypool':
2016-05-17.21:20:56 zpool create -m none -o ashift=12 mypool raidz2 /dev/disk/by-id/ata-WDC_WD6002FFWX-68TZ4N0_K1G0YB8B /dev/disk/by-id/ata-WDC_WD6001FFWX-68Z39N0_WD-WXB1HB4MYU7M /dev/disk/by-id/ata-WDC_WD6001FFWX-68Z39N0_WD-WX11DB5140D1 /dev/disk/by-id/ata-WDC_WD6001FFWX-68Z39N0_WD-WX11DB51457V /dev/disk/by-id/ata-WDC_WD6001FFWX-68Z39N0_WD-WX11DB514Y1L /dev/disk/by-id/ata-WDC_WD6001FFWX-68Z39N0_WD-WXB1HB4TDJL4
2016-05-18.07:40:43 zpool import -N mypool
2016-05-18.11:45:12 zpool import -N mypool

The last 2 entries were created from system reboots causing the pool to be imported like this:
zpool status
  pool: mypool
 state: ONLINE
  scan: none requested
config:

        NAME        STATE     READ WRITE CKSUM
        mypool      ONLINE       0     0     0
          raidz2-0  ONLINE       0     0     0
            sdc     ONLINE       0     0     0
            sdb     ONLINE       0     0     0
            sdd     ONLINE       0     0     0
            sdi     ONLINE       0     0     0
            sdk     ONLINE       0     0     0
            sdj     ONLINE       0     0     0

errors: No known data errors

I tried to use the deprecated ZPOOL_IMPORT_PATH="/dev/disk/by-id" in /etc/default/zfs but it had no effect. The zpool.cache file has references in it for the by-id drives. What can I do to ensure on reboot it imports with the by-id paths? Is it possible to manually set the import command issued automatically on reboot to import by the by-id paths?

**Comment by behlendorf** [comment]
This was fixed in the zfs-0.6.5.7 release which was tagged last week.  It looks like the ppa has been updated to include these packages, can you verify the exact zfs version number.

**Comment by hippie131** [comment]
dpkg -l | grep zfs
ii  dkms                                2.2.0.3-1.1ubuntu5.14.04.1+zfs10~trusty all          Dynamic Kernel Module Support Framework
ii  libzfs2                             0.6.5.7-1~trusty                        amd64        Native OpenZFS filesystem library for Linux
ii  mountall                            2.53-zfs1                               amd64        filesystem mounting tool
ii  ubuntu-zfs                          8~trusty                                amd64        Native ZFS filesystem metapackage for Ubuntu.
ii  zfs-dkms                            0.6.5.7-1~trusty                        amd64        Native OpenZFS filesystem kernel modules for Linux
ii  zfs-doc                             0.6.5.7-1~trusty                        amd64        Native OpenZFS filesystem documentation and examples.
ii  zfs-initramfs                       0.6.5.7-1~trusty                        amd64        Native OpenZFS root filesystem capabilities for Linux
ii  zfsutils                            0.6.5.7-1~trusty                        amd64        Native OpenZFS management utilities for Linux

**Comment by behlendorf** [comment]
@hippie131 can please try the following:

```
$ zpool export mypool
$ zpool import -d /dev/disk/by-id mypool

# Verify by-id names are used.
$ zpool status
$ reboot

# Verify by-id names are used.
$ zpool status
```

**Comment by hippie131** [comment]
same thing happens:
# zpool export mypool
# zpool import -d /dev/disk/by-id mypool
# zpool status
  pool: mypool
 state: ONLINE
  scan: none requested
config:

        NAME                                            STATE     READ WRITE CKSUM
        mypool                                          ONLINE       0     0     0
          raidz2-0                                      ONLINE       0     0     0
            ata-WDC_WD6002FFWX-68TZ4N0_K1G0YB8B         ONLINE       0     0     0
            ata-WDC_WD6001FFWX-68Z39N0_WD-WXB1HB4MYU7M  ONLINE       0     0     0
            ata-WDC_WD6001FFWX-68Z39N0_WD-WX11DB5140D1  ONLINE       0     0     0
            ata-WDC_WD6001FFWX-68Z39N0_WD-WX11DB51457V  ONLINE       0     0     0
            ata-WDC_WD6001FFWX-68Z39N0_WD-WX11DB514Y1L  ONLINE       0     0     0
            ata-WDC_WD6001FFWX-68Z39N0_WD-WXB1HB4TDJL4  ONLINE       0     0     0

errors: No known data errors

# reboot
# zpool status
  pool: mypool
 state: ONLINE
  scan: none requested
config:

        NAME        STATE     READ WRITE CKSUM
        mypool      ONLINE       0     0     0
          raidz2-0  ONLINE       0     0     0
            sdc     ONLINE       0     0     0
            sdb     ONLINE       0     0     0
            sdd     ONLINE       0     0     0
            sdi     ONLINE       0     0     0
            sdk     ONLINE       0     0     0
            sdj     ONLINE       0     0     0

errors: No known data errors

**Comment by hippie131** [comment]
Is there a way to alter the command used at boot time? if there is I can just change it from "zpool import -N mypool" to "zpool import -d /dev/disk/by-id mypool"

**Comment by kingneutron** [comment]
--I was having this exact same issue on Ubuntu 14.04-64-LTS; thank you for fixing it :)

/ currently using kernels 4.2.0-30-generic #36~14.04.1-Ubuntu SMP and
// 4.2.0-36-generic #42~14.04.1-Ubuntu SMP

(main PC, kernel 4.2.0-30)
$ dpkg -l|grep zfs
ii  dkms                                        2.2.0.3-1.1ubuntu5.14.04.1+zfs10~trusty all          Dynamic Kernel Module Support Framework
ii  libzfs2                                     0.6.5.7-1~trusty                        amd64        Native OpenZFS filesystem library for Linux
ii  mountall                                    2.53-zfs1                               amd64        filesystem mounting tool
ii  ubuntu-zfs                                  8~trusty                                amd64        Native ZFS filesystem metapackage for Ubuntu.
ii  zfs-dkms                                    0.6.5.7-1~trusty                        amd64        Native OpenZFS filesystem kernel modules for Linux
ii  zfs-doc                                     0.6.5.7-1~trusty                        amd64        Native OpenZFS filesystem documentation and examples.
ii  zfsutils                                    0.6.5.7-1~trusty                        amd64        Native OpenZFS management utilities for Linux

( 2nd server, kernel 4.2.0-36 )
$ dpkg -l|grep zfs
ii  dkms                                        2.2.0.3-1.1ubuntu5.14.04.1+zfs10~trusty all          Dynamic Kernel Module Support Framework
ii  libzfs2                                     0.6.5.7-1~trusty                        amd64        Native OpenZFS filesystem library for Linux
ii  mountall                                    2.53-zfs1                               amd64        filesystem mounting tool
ii  ubuntu-zfs                                  8~trusty                                amd64        Native ZFS filesystem metapackage for Ubuntu.
ii  zfs-dkms                                    0.6.5.7-1~trusty                        amd64        Native OpenZFS filesystem kernel modules for Linux
ii  zfs-doc                                     0.6.5.7-1~trusty                        amd64        Native OpenZFS filesystem documentation and examples.
ii  zfsutils                                    0.6.5.7-1~trusty                        amd64        Native OpenZFS management utilities for Linux

**Comment by kingneutron** [comment]
@hippie131 , what kernel version are you using, maybe try upgrading to 4.2.0-30 or -36?

**Comment by hippie131** [comment]
Im at the highest i can be without going to the next LTS which isnt recommended until the first point release comes out

-------- Original message --------

**Comment by hippie131** [comment]
# uname -a
Linux Media 4.2.0-36-generic #42~14.04.1-Ubuntu SMP Fri May 13 17:27:22 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by hippie131** [comment]
updated to the new hardware stack and now it seems to be mounting properly with the disk IDs. Here is the kernel version I'm on now:
uname -a
Linux Media 4.4.0-34-generic #53~14.04.1-Ubuntu SMP Wed Jul 27 16:56:40 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by behlendorf** [comment]
For the sake of completeness this was address in the release branch by c9ca152fd1de1b0fd959e772b9a25d14a891952b
