### ISSUE TITLE
Unable to rename zfs filesystem: missing dataset name

### ISSUE THREAD

**Issue by tbennett6421** [zfsonlinux/zfs#4681]
I was originally wanting to rename a zfs filesystem and change it's mountpoint.

When I ran `zfs rename vmroot vmds` I would get the message 
`cannot create 'vmds': missing dataset name`

I then changed the mountpoint using the following
`zfs set mountpoint=/mnt/nfs/vmds vmroot`
which was succesful

Trying once again to rename gives me the same error message as before.

Things I have tried
- running sudo vs root
- changing mountpoint to legacy and renaming zfs filesystem
- rebooting

`uname -a`
Linux nas 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

`lsb_release -a`
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty

**Comment by b333z** [comment]
The topmost dataset is special in that it shares it's name with the pool, so you need to rename the pool to rename that dataset, ```man zpool``` and read the ```zfs import``` section for details. So don't think this is a bug (although the error message could be better)

**Comment by tbennett6421** [comment]
You're awesome,

I spent hours trying to figure this out. The error message made not sense to me, and I was looking at the zfs code. Once you pointed me in the right direction I was able to change the name of that file system.
