### ISSUE TITLE
Failed to import zpool 

### ISSUE THREAD

**Issue by clandmeter** [zfsonlinux/zfs#4686]
After fixing most of #4385 we are trying cleanup things in Alpine Linux to include ZFS in our upcoming 3.4 release. I have applied most of the needed patches to the latest stable version, but when I reboot the zpool does not come online. Also a manual zpool import will result in a:
```cannot import 'tank': no such pool available```

When I try to import specifying the cache file with -c I get:
```invalid or corrupt cache file contents: invalid or missing cache file```

A strace when importing fails can be found here: http://tpaste.us/3Mjv

I also tried to compiled zfs tools from current master, and this does seem to allow importing again, so this seems only affected to latest stable.

**Comment by behlendorf** [comment]
@clandmeter that's strange since the release branch receives by far the most testing and I haven't heard any similar reports.  Have you tried using your patched version of the release branch on a non-Alpine Linux distribution to see if you can reproduce the issue?

**Comment by clandmeter** [comment]
@behlendorf seems after rebasing the patches to current stable version zpool import is working properly.
Thanks again for your help on getting this to work on musl/alpine.
