### ISSUE TITLE
memory leaks until kmalloc-512 slab is full

### ISSUE THREAD

**Issue by ptx0** [zfsonlinux/zfs#4698]
* Linux 4.4.11
* Memory: 32GB
* ARC max: defaults (~15GB)
* Root filesystem: ext4+mdraid
* Pool layout: mirrored pair, 2x2TB HGST (partitions)
* Features: Compression (lz4), no deduplication
* Workload: 7 x Linux KVM on ZVOL direct and via iSCSI (512MB RAM each)

I had this box running for 200+ days with its current workload on zfs+spl `0.6.5.4` with Linux `3.16`.
* SLUB allocator
* ARC usually stays at 15GB
* VMs can balloon and shrink as needed
* drop_caches frees ARC

I recently updated the kernel to `4.4.11` and simultaneously updated zfs+spl to `0.6.5.7`
* SLAB / SLUB allocators tested
* Memory is consumed until it is all used, and then starts swapping
* Applications are not using memory
* ARC was stuck at 100MB
* `ps auxw --sort -rss` numbers do not add up to the total used memory
* `/proc/slabinfo` lists `kmalloc-512` as 30GB
* `drop_caches` does nothing

The system does not hang, unlike other reclaim issue reports I have seen. Stopping virtual machines didn't free up any memory, either.

I have Linux sysctl for overcommit set to defaults.

**Comment by behlendorf** [comment]
@ptx0 can you try either reverting to 0.6.5.4 with the new kernel, or reverting to the old kernel with 0.6.5.7.  This way we can narrow down where this issue was introduced.

**Comment by ptx0** [comment]
I meant to detail that in the issue report above.

I did downgrade to `0.6.5.4` + `4.4.11` with SLUB and ARC reclaim works again.

**Comment by behlendorf** [comment]
@ptx0 OK, then it's between 0.6.5.4 - 0.6.5.7 which is a pretty small delta.  Skimming through the list of changes there are a couple possible candidates which might have introduced a small leak.  My first guess would be the asynchronous zvol commit where I see a possible, but very unlikely leak, if a taskq_dispatch() were to fail.

I know it's a lot to ask, but if you have a non-production system where you could test the 0.6.5.5 and 0.6.5.6 tags that would really help narrow it down.  It may take some time to reproduce this locally, and thus far I haven't heard any other reports of this so it may be something particular to your workload (lots of zvol creates/destroys perhaps?).

**Comment by ptx0** [comment]
I hadn't done any create / destroy, just statistics collection every 15-30 seconds:
* zpool iostat
* zfs get all
* zpool get all

A couple VMs use ZVOL directly and a few connect via iSCSI.

I don't have any non-production systems, unfortunately.. Severe lack of resources.

**Comment by ptx0** [comment]
ugh, sorry. I may have fudged up my `0.6.5.7` by building HEAD instead - so I can't guarantee it is indeed in `0.6.5.7`. the issue clearly exists in HEAD.

**Comment by dweeezil** [comment]
@ptx0 Are your zvols using the standard 8K blocksize?  Do you have the full output from ```/proc/spl/kstat/zfs/arcstats``` available?

**Comment by dweeezil** [comment]
@ptx0 And to clarify the versions, are you saying that you never did actually try 0.6.5.7?  Also, to clarify the workload, is the ZFS use 100% zvol?  And are the zvols strictly being accessed by qemu/kvm?  And the iSCSI, is the system an initiator, target or both?

**Comment by dracwyrm** [comment]
Is this the same issue that I'm having now?

I upgraded to the latest head (as of 20160518) with kernel 4.5.5 Gentoo Sources. I have cache separated out on two SSDs in a stripe so roughly 100GB of cache total. My Windows 10 is on a ZVol. On the Linux side, I would use zpool iostat -v and watch my cache fill up. It would never empty out. Then when it becomes full, Windows would be very stuttery and slow. Again, the cache does not empty out even then.

Also, since upgrading to the new version of ZFS, Windows is just genuinely slow to load apps, even Windows Explorer. I think this might have something to do with caching, but not sure.

Is this the same thing?

**Comment by ptx0** [comment]
Yes, Tim. I tested HEAD - forgot to `git reset --hard zfs-0.6.5.7`

ZFS slabs:
http://sprunge.us/VfIb
Slab info:
http://sprunge.us/WWhU
```
     time    read  miss  miss%     dmis  dm%  pmis  pm%  mmis  mm%  arcsz     c  
 10:00:37     0     0        0     0       0    0   0    0     0    51M    55M  
```

**Comment by ptx0** [comment]
@dracwyrm My system doesn't have any knowledge of where the memory is going. It's possible they are the same. Do you have large amounts of used memory that doesn't show up in ZFS slabs?

**Comment by behlendorf** [comment]
@tuxoko identified the following leaks in master which would explain this. #4706 #4707

**Comment by ptx0** [comment]
seems to be resolved, also with ABD patches

**Comment by D4rk4** [comment]
@kpande  need deb build with this patches...

**Comment by kpande** [comment]
maybe @FransUrbo can build a new daily from HEAD which will give you pre-release access to the fix?
