### ISSUE TITLE
zfs mount errors are obtuse

### ISSUE THREAD

**Issue by jimsalterjrs** [zfsonlinux/zfs#4700]
I have frequently seen "unable to mount [dataset] due to error 22", but have never been able to find out what "error 22" is supposed to represent.

Today I was attempting to assist a user troubleshoot a pool that mounted with no errors but wouldn't mount the root dataset in the pool, and in that user's case, it was "unable to mount [dataset] due to error 1".

Where can I find a list of what "error 1" and "error 22" (and presumably, at a minimum, errors 2-21) are, and what they mean?

**Comment by behlendorf** [comment]
These are [standard errno ](http://www-numi.fnal.gov/offline_software/srt_public_context/WebDocs/Errors/unix_system_errors.html) exit codes.  These are usually translated by the tools in to more human readable strings but obviously that isn't happening in all cases.  So in your case:

#define EPERM            1      /* Operation not permitted */
#define EINVAL          22      /* Invalid argument */

**Comment by jimsalterjrs** [comment]
Thank you. Odd - I saw an strace of the failed mount operation that threw 
the error 1, and there was no EPERM.


----------------

(Sent from my tablet - please blame any weird errors on autocorrect)
