### ISSUE TITLE
non-deterministic find on ZFS snapshot

### ISSUE THREAD

**Issue by lnxbil** [zfsonlinux/zfs#4704]
Hi,

I don't know if this is a bug or a feature, but `find` does not work as it should be. I'm using ZFS `v0.6.5.6-1` on the machine in question and encounter a very strange problem with `find` and ZFS snapshots.

I have a ZFS filesystem which stores a rsynced backup of some server. This filesystem gets filled and snapshotted once a day, so I have snapshots with the date of the sync. I just wanted to `find` some files and the file was only found once:

```
root@backup /rpool/machines/some-domain.com/.zfs/snapshot > find . -name "*1461235789.27*"
./2016-04-27/rootFS/home/ABC/XYZ/Maildir/cur/1461235789.27564_0.some-domain.com:2,S
```

whereas the file exists in any snapshot since then:

```
root@backup /rpool/machines/some-domain.com/.zfs/snapshot > ls -l ./2016-04-28/rootFS/home/ABC/XYZ/Maildir/cur/1461235789.27564_0.some-domain.com:2,S
-rw------- 1 2079 2018 16453 Apr 21 12:49 ./2016-04-28/rootFS/home/ABC/XYZ/Maildir/cur/1461235789.27564_0.some-domain.com:2,S
root@backup /rpool/machines/some-domain.com/.zfs/snapshot > ls -l ./2016-04-29/rootFS/home/ABC/XYZ/Maildir/cur/1461235789.27564_0.some-domain.com:2,S
-rw------- 1 2079 2018 16453 Apr 21 12:49 ./2016-04-29/rootFS/home/ABC/XYZ/Maildir/cur/1461235789.27564_0.some-domain.com:2,S
```

If I run on the top-most level of the filesystem, the file is only found in snapshots:

```
root@backup /rpool/machines/some-domain.com > find . -name "*1461235789.27*"
./.zfs/snapshot/2016-04-27/rootFS/home/ABC/XYZ/Maildir/cur/1461235789.27564_0.some-domain.com:2,S
root@backup /rpool/machines/some-domain.com > find . -name "*1461235789.27*"
./.zfs/snapshot/2016-04-27/rootFS/home/ABC/XYZ/Maildir/cur/1461235789.27564_0.some-domain.com:2,S
./.zfs/snapshot/2016-05-06/rootFS/home/ABC/XYZ/Maildir/cur/1461235789.27564_0.some-domain.com:2,S
root@backup /rpool/machines/some-domain.com > find . -name "*1461235789.27*"
./.zfs/snapshot/2016-04-27/rootFS/home/ABC/XYZ/Maildir/cur/1461235789.27564_0.some-domain.com:2,S
./.zfs/snapshot/2016-05-06/rootFS/home/ABC/XYZ/Maildir/cur/1461235789.27564_0.some-domain.com:2,S
root@backup /rpool/machines/some-domain.com > ls -l rootFS/home/ABC/XYZ/Maildir/cur/1461235789.27564_0.some-domain.com:2,S
-rw------- 1 2079 2018 16453 Apr 21 12:49 rootFS/home/ABC/XYZ/Maildir/cur/1461235789.27564_0.some-domain.com:2,S
root@backup /rpool/machines/some-domain.com > find . -name "*1461235789.27*"
./.zfs/snapshot/2016-04-27/rootFS/home/ABC/XYZ/Maildir/cur/1461235789.27564_0.some-domain.com:2,S
./.zfs/snapshot/2016-05-06/rootFS/home/ABC/XYZ/Maildir/cur/1461235789.27564_0.some-domain.com:2,S
```

Yet if I search on each snapshot directory, the file is always found. I think this is some kind of weird filesystem boundary crossing bug. I noticed, that each snapshot is mounted on access.

This is not the first time I encountered this problem, but the first it is so strange that I wanted to file a bug report. I can help myself for now by using find explicitly inside snapshot directories (e.g. `./.zfs/snapshot/2016-04-26`) but it would be great if this could be fixed upstream.

Deactivating `snapdir` also results in correct behavior to find the "real" (current) file:

```
root@backup /rpool/machines/some-domain.com > find  -name "*1461235789.27*"
root@backup /rpool/machines/some-domain.com > zfs set snapdir=hidden rpool/machines/some-domain.com
root@backup /rpool/machines/some-domain.com > find  -name "*1461235789.27*"
./rootFS/home/ABC/XYZ/Maildir/cur/1461235789.27564_0.some-domain.com:2,S
```

**Comment by rincebrain** [comment]
I _think_ the problem you're encountering is that running find on FOO/.zfs/snapshot doesn't trigger mounts of all of them , so to speak.

For example:
`$ find /workspace/juke_dump/.zfs/snapshot/ | wc -l
16
$ find /workspace/juke_dump/.zfs/snapshot/ | wc -l
887
$ find /workspace/juke_dump/.zfs/snapshot/ | wc -l
1758
$ find /workspace/juke_dump/.zfs/snapshot/ | wc -l
2629
$ find /workspace/juke_dump/.zfs/snapshot/ | wc -l
3500
[...]
$ find /workspace/juke_dump/.zfs/snapshot/ | wc -l
50519
`
(It looks like what's happening is that find stats the snapshot dir and does not attempt to descend into the entries with apparent size 0, but something find is doing is triggering the first non-mounted snapshot to be mounted.

It's slightly odd, though, because _sometimes_, it seems the mount triggers and completes on the first not-mounted snapshot before find "decides" which children to descend into.)

If you try executing an ls FOO/.zfs/snapshot/* before your find, it will mount all of them, and then you can run your find as desired.

In contrast, ls -R always triggers all of the mounts.

This is (almost certainly) a bug, but that might give you a useful workaround or two.

**Comment by lnxbil** [comment]
Thank you for your comment. Your suggested solution is actually what I do right now and what I meant by 

> Yet if I search on each snapshot directory, the file is always found

**Comment by tuxoko** [comment]
Does `rsync -anv` works?

**Comment by lnxbil** [comment]
I just tried to figure out what @tuxoko meant I think it works:

```
root@backup /rpool/machines/some-domain.com > rsync -anv --include='*1461235789.27*' --include='*/' --exclude='*' --prune-empty-dirs . /tmp
```

all files were found (in the snapshots and in the filesystem itself), yet it took ages to build the file list.

**Comment by tuxoko** [comment]
So rsync works but find doesn't. So I think the problem might be older find version doesn't know how to deal with automount. On my system both rsync and find works fine.

**Comment by lnxbil** [comment]
What ```find``` version do you use?

I use:

```
root@backup ~ > find --version
find (GNU findutils) 4.4.2
Copyright (C) 2007 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Eric B. Decker, James Youngman, and Kevin Dalley.
Erzeugt mit der GNU gnulib Version e5573b1bad88bfabcda181b9e0125fb0c52b7d3b
Aktivierte Eigenschaften:D_TYPE O_NOFOLLOW(enabled) LEAF_OPTIMISATION FTS() CBO(level=0)
```

**Comment by tuxoko** [comment]
I'm on ubuntu 16.04
```
find (GNU findutils) 4.7.0-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Eric B. Decker, James Youngman, and Kevin Dalley.
Features enabled: D_TYPE O_NOFOLLOW(enabled) LEAF_OPTIMISATION FTS(FTS_CWDFD) CBO(level=2) 
```
This could also be caused by how zfs shows unmounted snapdir as zero sized. So when find(1) does stat(2), it would think it's empty and not trying to open it.

**Comment by lnxbil** [comment]
Will try a newer version next week.

**Comment by loli10K** [comment]
> Will try a newer version next week.

@lnxbil is this still an issue?

**Comment by behlendorf** [comment]
Closing as stale.  We can reopen if it's still an issue.
