### ISSUE TITLE
ZFS issue after enlarging image

### ISSUE THREAD

**Issue by ntenisOT** [zfsonlinux/zfs#4718]
I created a new img using the following command:

    truncate -s 250G disk.img

and I replace the existing image that I used for zpool with that one using (lxd.img was 2G):

    zpool replace lxd lxd.img disk.img
I set the autoexpand to on

    sudo zpool set autoexpand=on lxd
But the size is still 2GB and I have an EXPANDSZ property that states the size of the new image.

    NAME   SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
    lxd   1.98G  1.82G   170M      248G    69%    91%  1.00x  ONLINE  -

How can I fix this?

**Comment by FransUrbo** [comment]
> zpool replace lxd lxd.img disk.img
You need to put disk.img online as well.

**Comment by ntenisOT** [comment]
But I think it is online.

    sudo zpool status
    pool: lxd
    state: ONLINE
          scan: resilvered 1.82G in 0h0m with 0 errors on Wed Jun  1 14:38:48 2016
        config:

	NAME                     STATE     READ WRITE CKSUM
	lxd                      ONLINE       0     0     0
	  /var/lib/lxd/disk.img  ONLINE       0     0     0

    errors: No known data errors

**Comment by ntenisOT** [comment]
Oh thanks. I did:

    sudo zpool online -e lxd /var/lib/lxd/disk.img

and now I have: 

    NAME   SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
    lxd    250G  1.82G   248G         -     0%     0%  1.00x  ONLINE  -

**Comment by FransUrbo** [comment]
> But I think it is online
> 
Yes, but not the added space..

**Comment by ntenisOT** [comment]
Thanks a lot 👍
