### ISSUE TITLE
zpool scrub hangs on non-redundant data failure

### ISSUE THREAD

**Issue by hcw70** [zfsonlinux/zfs#4721]
When doing 

> dd if=/dev/zero of=/dev/media2/zfs-disk-2 bs=1024k count=1024

on a (by accident) non redundant disk file, and then doing a 

> zfs scrub zfs-test

the data corruption is reported correcly and visible via zpool status, but the scrub process does not terminate. The process is not killable with -KILL.

> INFO: task zpool:7746 blocked for more than 120 seconds.
> [12361.836272] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
> [12361.836274] zpool           D ffffffff81806200     0  7746   4694 0x00000000
> [12361.836279]  ffff88010a683c18 0000000000000086 0000000000000001 ffff880133cada88
> [12361.836284]  ffff88010a683fd8 ffff88010a683fd8 ffff88010a683fd8 0000000000012800
> [12361.836287]  ffff880134ba1700 ffff880019b01700 ffff88010a683c28 ffff880133cadac0
> [12361.836291] Call Trace:
> [12361.836300]  [<ffffffff8166cb8f>] schedule+0x3f/0x60
> [12361.836325]  [<ffffffffa0188f75>] cv_wait_common+0x115/0x130 [spl]
> [12361.836329]  [<ffffffff8108dc00>] ? add_wait_queue+0x60/0x60
> [12361.836337]  [<ffffffffa0188fe5>] __cv_wait+0x15/0x20 [spl]
> [12361.836389]  [<ffffffffa02470af>] txg_wait_synced+0xef/0x140 [zfs]
> [12361.836392]  [<ffffffff8166eb1e>] ? _raw_spin_lock+0xe/0x20
> [12361.836418]  [<ffffffffa021e4e0>] ? dsl_prop_unset_hasrecvd+0x60/0x60 [zfs]
> [12361.836444]  [<ffffffffa0222a5a>] dsl_sync_task+0x18a/0x280 [zfs]
> [12361.836470]  [<ffffffffa021f250>] ? dsl_scan_sync_state+0xb0/0xb0 [zfs]
> [12361.836495]  [<ffffffffa021e4e0>] ? dsl_prop_unset_hasrecvd+0x60/0x60 [zfs]
> [12361.836521]  [<ffffffffa021f250>] ? dsl_scan_sync_state+0xb0/0xb0 [zfs]
> [12361.836547]  [<ffffffffa02228af>] dsl_scan+0x6f/0x80 [zfs]
> [12361.836553]  [<ffffffffa0181789>] ? strdup+0x49/0x70 [spl]
> [12361.836581]  [<ffffffffa023443c>] spa_scan+0x4c/0x90 [zfs]
> [12361.836611]  [<ffffffffa026df8a>] zfs_ioc_pool_scan+0x3a/0x70 [zfs]
> [12361.836618]  [<ffffffffa018179f>] ? strdup+0x5f/0x70 [spl]
> [12361.836646]  [<ffffffffa0272d5a>] zfsdev_ioctl+0x4da/0x520 [zfs]
> [12361.836651]  [<ffffffff8119078a>] do_vfs_ioctl+0x8a/0x340
> [12361.836654]  [<ffffffff811897e5>] ? putname+0x35/0x50
> [12361.836657]  [<ffffffff8117d50c>] ? do_sys_open+0x17c/0x250
> [12361.836660]  [<ffffffff81190ad1>] sys_ioctl+0x91/0xa0
> [12361.836663]  [<ffffffff81677262>] system_call_fastpath+0x16/0x1b
> 

 

> dpkg -l zfsutils
> Gewünscht=Unbekannt/Installieren/R=Entfernen/P=Vollständig Löschen/Halten
> | Status=Nicht/Installiert/Config/U=Entpackt/halb konFiguriert/
>          Halb installiert/Trigger erWartet/Trigger anhängig
> |/ Fehler?=(kein)/R=Neuinstallation notwendig (Status, Fehler: GROSS=schlecht)
> ||/ Name           Version        Beschreibung
> +++-==============-==============-============================================
> ii  zfsutils       0.6.5.4-1~prec Native OpenZFS management utilities for Linu
>

**Comment by hcw70** [comment]
Btw: status after scrubbing is:

> zpool status zfs-test 
>   pool: zfs-test
>  state: UNAVAIL
> status: One or more devices are faulted in response to IO failures.
> action: Make sure the affected devices are connected, then run 'zpool clear'.
>    see: http://zfsonlinux.org/msg/ZFS-8000-HC
>   scan: scrub in progress since Thu Jun  2 14:00:27 2016
>     388K scanned out of 2.34M at 148/s, 3h51m to go
>     0 repaired, 16.20% done
> config:
> 
> 	NAME                   STATE     READ WRITE CKSUM
> 	zfs-test               UNAVAIL      0     0     0  insufficient replicas
> 	  media2-zfs--disk--2  UNAVAIL      0     0     0  corrupted data
> 	  media2-zfs--disk--1  ONLINE       0     0     0
> 
> errors: 26 data errors, use '-v' for a list
>

**Comment by behlendorf** [comment]
@hcw70 was the pool suspended?  This should be logged on the console.

**Comment by hcw70** [comment]
> Jun  2 14:00:31 mediasrv kernel: [12242.973510] WARNING: Pool 'zfs-test' has encountered an uncorrectable I/O failure and has been suspended.

**Comment by behlendorf** [comment]
@hcw70 OK so this is expected behavior.  When a non-redundant pool suffers enough damage that it no longer can continue it will suspend the pool and all I/O.  This includes the scrub, which is what you're seeing.  This behavior is configurable with the **failmode** pool property, by default the property is set to **wait**.

```
       failmode=wait | continue | panic

           Controls  the  system  behavior  in  the event of catastrophic pool
           failure. This condition is typically a result of a loss of  connec‐
           tivity  to  the  underlying  storage  device(s) or a failure of all
           devices within the pool. The behavior of such an  event  is  deter‐
           mined as follows:

           wait        Blocks  all I/O access until the device connectivity is
                       recovered and the  errors  are  cleared.  This  is  the
                       default behavior.

           continue    Returns  EIO  to  any new write I/O requests but allows
                       reads to any of  the  remaining  healthy  devices.  Any
                       write  requests  that  have yet to be committed to disk
                       would be blocked.

           panic       Prints out a message to the  console  and  generates  a
                       system crash dump.
```
