### ISSUE TITLE
Can't build ZFS module via DKMS on Debian 8

### ISSUE THREAD

**Issue by D4rk4** [zfsonlinux/zfs#4725]
/var/lib/dkms/zfs/0.6.5.991/build/module/zfs/zpl_file.c: In function ‘zpl_llseek’:
/var/lib/dkms/zfs/0.6.5.991/build/module/zfs/zpl_file.c:424:3: error: implicit declaration of function ‘spl_inode_lock_shared’ [-Werror=implicit-function-declaration]
   spl_inode_lock_shared(ip);
   ^
/var/lib/dkms/zfs/0.6.5.991/build/module/zfs/zpl_file.c:430:3: error: implicit declaration of function ‘spl_inode_unlock_shared’ [-Werror=implicit-function-declaration]
   spl_inode_unlock_shared(ip);
   ^
cc1: some warnings being treated as errors
-----------------
ii  libnvpair1                               0.6.5.991-295-gb7faa7a-jessie-daily         amd64        Solaris name-value library for Linux
ii  libuutil1                                0.6.5.991-295-gb7faa7a-jessie-daily         amd64        Solaris userland utility library for Linux
ii  libzfs-dev                               0.6.5.991-295-gb7faa7a-jessie-daily         amd64        Native ZFS filesystem development files for Linux
ii  libzfs2                                  0.6.5.991-295-gb7faa7a-jessie-daily         amd64        Native ZFS filesystem library for Linux
ii  libzpool2                                0.6.5.991-295-gb7faa7a-jessie-daily         amd64        Native ZFS pool library for Linux
ii  zfs-dkms                                 0.6.5.991-295-gb7faa7a-jessie-daily         all          Native ZFS filesystem kernel modules for Linux
ii  zfs-initramfs                            0.6.5.991-295-gb7faa7a-jessie-daily         amd64        Native ZFS root filesystem capabilities for Linux
ii  zfsutils                                 0.6.5.991-295-gb7faa7a-jessie-daily         amd64        command-line tools to manage ZFS filesystems

**Comment by FransUrbo** [comment]
https://github.com/zfsonlinux/pkg-zfs/issues/211
