### ISSUE TITLE
`zfs create` takes unreasonably long time, exponential to existing number of datasets

### ISSUE THREAD

**Issue by mailinglists35** [zfsonlinux/zfs#4727]
When there are lots of existing datasets in an imported pool, creating new datasets take very long time.
steps to reproduce:

```
root@linux:~# mount -t tmpfs -o size=2662400k tmpfs /mnt/test/
root@linux:~# truncate -s 2GiB /mnt/test/deleteme
root@linux:~# zpool create deleteme /mnt/test/deleteme
root@linux:~# for i in `seq 1 2000`; do (time zfs create deleteme/$i); done
```

in the graph below, at around 1500 datasets created in the ram-file-backed test pool I have imported a real pool containing 1600 datasets - see how creation time jumped after that.

system specs and zfs/zpool config mentioned [here](https://github.com/zfsonlinux/zfs/issues/4604#issue-153513904) except now it's kernel 4.5 instead of 4.4 and zfs updated to 0.6.5.7.

attached [perf.data.zip](https://github.com/zfsonlinux/zfs/files/298821/perf.data.zip) output file from running `perf record -a zfs create deleteme/test` and [perf_trace.txt](https://github.com/zfsonlinux/zfs/files/298819/perf_trace.txt) from `perf trace zfs create deleteme/test`  as well as [strace.txt](https://github.com/zfsonlinux/zfs/files/298828/strace.txt) output on zfs process

Other observations:
lots of these `0x5a14` ioctls in the strace and perf trace:
`75.032 ( 2.132 ms): zfs/17863 ioctl(fd: 7</dev/zfs>, cmd: 0x5a14, arg: 0x7ffe6bbea1d0               ) = -1 ESRCH No such process`
occasional 'cannot allocate memory' even though the system has free memory available
`ioctl(7, 0x5a14, 0x7ffd6d1ad9a0)        = -1 ENOMEM (Cannot allocate memory)`

![zfs](https://cloud.githubusercontent.com/assets/2054302/15799338/f8d8e944-2a61-11e6-982f-d893a2d764fd.png)

**Comment by dweeezil** [comment]
@mailinglists35 What happens if you don't mount them (use ```zpool create -O mountpoint=none deleteme /mnt/test/deleteme```)?

**Comment by mailinglists35** [comment]
@dweeezil I'll re-run and post updates. meanwhile, with NO datasets mounted (the pool with 1600 datasets only imported but not mounted), I get 12 seconds on `zpool create deleteme /mnt/test/deleteme`

    root@linux:~# time perf record -a zpool create deleteme /mnt/test/deleteme
    [ perf record: Woken up 19 times to write data ]
    [ perf record: Captured and wrote 4.862 MB perf.data (99048 samples) ]
    
    real    0m12.914s
    user    0m0.232s
    sys     0m12.492s

(one second faster if ran without perf recording)

**Comment by mailinglists35** [comment]
with `-o mountpoint=none` or with `-o canmount=noauto` (I prefer the later, since I will want the real dataset mounted eventually) I get about 0,015s for 1 dataset creation, no matter how many datasets I create

**Comment by kpande** [comment]
when i'm running this test on a VM with 4 vCPU and 4GB RAM there is spinning in arc_prune when it reaches 2000 datasets, all operations take excessively long time and I had to eventually destroy the pool.

**Comment by behlendorf** [comment]
@kpande thanks for the additional information.  We should be able to get a better idea exactly why arc_prune is using so much cpu by dumping arcstats.  My guess would be it's bumping up against one of the meta data limits.

**Comment by kpande** [comment]
my test was with 0.6.5 and I have not redone the test with 0.7.0-rcn or HEAD
