### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by meagon** [zfsonlinux/zfs#4731]
/dev/shm/master/module/zfs/arc.c: In function ‘arc_reclaim_thread’:
/dev/shm/master/module/zfs/arc.c:3452:29: error: implicit declaration of function ‘SEC2NSEC’ [-Werror=implicit-function-declaration]
    growtime = gethrtime() + SEC2NSEC(arc_grow_retry);
                             ^
/dev/shm/master/module/zfs/arc.c:3504:11: error: implicit declaration of function ‘cv_timedwait_sig_hires’ [-Werror=implicit-function-declaration]
    (void) cv_timedwait_sig_hires(&arc_reclaim_thread_cv,
           ^
/dev/shm/master/module/zfs/zpl_file.c: In function ‘zpl_llseek’:
/dev/shm/master/module/zfs/zpl_file.c:424:3: error: implicit declaration of function ‘spl_inode_lock_shared’ [-Werror=implicit-function-declaration]
   spl_inode_lock_shared(ip);
   ^
/dev/shm/master/module/zfs/zpl_file.c:430:3: error: implicit declaration of function ‘spl_inode_unlock_shared’ [-Werror=implicit-function-declaration]
   spl_inode_unlock_shared(ip);

**Comment by DeHackEd** [comment]
What version of ZFS, what kernel are you compiling it against, and what did you give to `./configure` ?

**Comment by meagon** [comment]
./configure --with-spl=/usr/local/src/spl-0.6.5.7

**Comment by meagon** [comment]
get from the master

**Comment by behlendorf** [comment]
@meagon you need to pull the latest version of the SPL master branch.
