### ISSUE TITLE
zfs recv over ssh without root

### ISSUE THREAD

**Issue by urza** [zfsonlinux/zfs#4734]
Hello, sorry if this is the wrong place to ask, but I have problem I dont know how to solve.

I would like to send and receive incremental snapshot from zfs on one machine to zfs on other machine.
On sending machine I command this:

send -R -i @snap0 mypool/urza@snap1 | ssh urza@my.remote.xx sudo zfs recv -Fv mypool/urza

However problem is that I cant enter the password for sudo.
Is there a way around this? Can I make user urza on receiving machine able to run zfs command without sudo? I dont want to enable root over ssh.

Thank you very much

**Comment by D4rk4** [comment]
Enable root. Disable password auth...

**Comment by urza** [comment]
I successfully solved the issue by following this solution: https://askubuntu.com/questions/159007/how-do-i-run-specific-sudo-commands-without-a-password

Thank you

**Comment by behlendorf** [comment]
Once #4487 is merged you'll be able to use delegations to address this issue as well.
