### ISSUE TITLE
arc_reclaim slows down system

### ISSUE THREAD

**Issue by hostingnuggets** [zfsonlinux/zfs#4738]
I am running Debian 8 with ZoL 0.6.5.6 and have 4 960GB SSD disks in a RAIDZ1 pool as well as 2 additional 240 GB SSDs for the logs in a mirror and finally a NVMe module for the cache. This server is a Xen hypervisor in order to run virtual machines and has 8 GB of RAM assigned to it (total of 128 GB of RAM) and 4 cores. Furthermore I have zfs_arc_max set to 4294967296 (4GB). The ZFS pool is used only for zvols, one per virtual machine. 

This evening I noticed that suddently the virtual machines where not very responsive, for example it would take 10 seconds to log into a VM and running a command on it would also be very slow. So I checked the hypervisor with top and saw that most of the time the arc_reclaim process would be using 100% CPU for a few seconds then disappearing and the coming up back again, and so on. Eventually after 30 minutes the system went back to normal by itself.

There where no special load as far as I know on any VMs and there are only 5 VMs on this hypervisor  as it is a brand new server. So I was wondering is this somehow an issue related to arc_reclaim itself as there are a few issues opened still concerning arc_reclaim? or is it maybe some bad configuration from my side? or do I maybe need to tune some ZFS kernel module parameters?

**Comment by dweeezil** [comment]
Please post the arcstats while the problem is happening.  What kernel version are you running?

**Comment by hostingnuggets** [comment]
lucky you but unlucky me it's happening right now again, here the output of arcstat.py with 2 seconds interval:

```
/usr/sbin/arcstat.py 2 
    time  read  miss  miss%  dmis  dm%  pmis  pm%  mmis  mm%  arcsz     c  
21:16:06     0     0      0     0    0     0    0     0    0   4.1G  4.0G  
21:16:08   519    42      8    42    8     0    0    42    8   4.0G  4.0G  
21:16:10     4     1     25     1   25     0    0     1   25   4.0G  4.0G  
21:16:12    63    15     24    15   24     0    0    15   24   4.0G  4.0G  
21:16:14    14     8     58     8   58     0    0     8   58   4.0G  4.0G  
21:16:16    28    11     40     8   32     3  100     5   31   4.0G  4.0G  
21:16:18   151    36     24    34   23     2  100    30   21   4.0G  4.0G  
21:16:20    62     5      8     5    8     0    0     5    8   4.0G  4.0G  
21:16:22    13    11     85     4   66     7  100     3   85   4.0G  4.0G  
21:16:24   116    64     55    31   40    33   84    30   41   4.0G  4.0G  
21:16:26   121    66     54    25   31    41  100    23   31   4.0G  4.0G  
21:16:28   114    42     37    15   17    27  100    15   17   4.0G  4.0G  
21:16:30    84    35     42    35   42     0    0    35   42   4.0G  4.0G  
21:16:32     8     2     23     2   23     0    0     2   23   4.0G  4.0G  
21:16:34    16     7     45     7   45     0    0     7   45   4.0G  4.0G  
21:16:36    33    10     31    10   31     0    0    10   31   4.0G  4.0G  
21:16:38    97    26     26    26   26     0    0    26   26   4.0G  4.0G  
21:16:40    12     8     70     8   70     0    0     8   70   4.0G  4.0G  
21:16:42    12     3     29     3   29     0    0     3   29   4.0G  4.0G  
21:16:44    16     9     56     9   56     0    0     9   56   4.0G  4.0G  
21:16:46    49    35     71     7   33    28  100     6   34   4.0G  4.0G  
21:16:48    62    40     65    11   34    29  100    10   35   4.0G  4.0G  
21:16:50    40    36     90     3   42    33  100     2   57   4.0G  4.0G  
21:16:52    40    36     90     2   38    34  100     0   20   4.0G  4.0G  
21:16:54    95    48     50    19   40    29   60    17   44   4.0G  4.0G  
21:16:56    91    41     45     7   12    34  100     7   12   4.0G  4.0G  
21:16:58    80    36     45    11   21    25   90    10   21   4.0G  4.0G  
21:17:01    70    35     49     3    9    31   96     3    9   4.0G  4.0G  
21:17:03    88    55     63    21   39    34  100    20   40   4.0G  4.0G  
21:17:05   102    55     53    30   38    25  100    29   39   4.0G  4.0G  
21:17:07    79    45     56    14   29    30  100    13   30   4.0G  4.0G  
21:17:09    77    34     44    11   21    23  100    10   20   4.0G  4.0G  
21:17:11    89    48     53    22   35    25  100    17   31   4.0G  4.0G  
21:17:13    72    48     67    11   33    37   94     7   29   4.0G  4.0G  
21:17:15    65    38     58    17   38    20  100    15   38   4.0G  4.0G  
21:17:17    96    43     44     6   10    36  100     5    9   4.0G  4.0G  
21:17:19    68    24     35    16   27     7  100    15   25   4.0G  4.0G  
21:17:21    90    33     37    33   37     0    0    13   18   4.0G  4.0G  
21:17:23    85    65     77    60   75     5  100     9   35   4.0G  4.0G  
21:17:25    50    37     73     3   18    34  100     1   11   4.0G  4.0G  
21:17:27    95    51     53    17   27    34  100    17   29   4.0G  4.0G  
21:17:29   241    64     26    36   17    28  100    34   16   4.0G  4.0G  
21:17:31    45    16     36    10   26     6  100    10   35   4.0G  4.0G  
21:17:33  1.3K    55      4    55    4     0    0    55    4   4.1G  4.0G  
21:17:35   254    19      7    19    7     0    0    19    7   4.1G  4.0G  
21:17:37    24    16     66    16   66     0    0    16   66   4.0G  4.0G  
21:17:39    54    24     45    24   45     0    0    24   45   4.0G  4.0G  
21:17:41    53    44     82    14   63    29   96    13   77   4.0G  4.0G  
21:17:43    68    55     81    14   53    41  100    13   57   4.0G  4.0G  
21:17:45   132    90     67    47   53    42   95    44   54   4.0G  4.0G  
21:17:47    62    30     48    27   45     3  100    20   38   4.0G  4.0G  
21:17:49   168    83     49    37   30    46  100    35   30   4.0G  4.0G  
21:17:51   100    51     51     4    8    47  100     4    8   4.0G  4.0G  
21:17:53   143    87     60    23   29    63  100    20   27   4.0G  4.0G  
```

The kernel is the following:

3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-1 (2016-03-06) x86_64 GNU/Linux

**Comment by hostingnuggets** [comment]
the contents of /proc/spl/kstat/zfs/arcstats might also be useful for you:
```
6 1 0x01 91 4368 8514024590 1936536633267777
name                            type data
hits                            4    98577966
misses                          4    39203785
demand_data_hits                4    42948884
demand_data_misses              4    19466485
demand_metadata_hits            4    51981138
demand_metadata_misses          4    13358848
prefetch_data_hits              4    3618814
prefetch_data_misses            4    6282007
prefetch_metadata_hits          4    29130
prefetch_metadata_misses        4    96445
mru_hits                        4    52120243
mru_ghost_hits                  4    816766
mfu_hits                        4    45940812
mfu_ghost_hits                  4    96979
deleted                         4    208486162
mutex_miss                      4    3235031
evict_skip                      4    33641613117
evict_not_enough                4    1688362305
evict_l2_cached                 4    276209274368
evict_l2_eligible               4    702180655616
evict_l2_ineligible             4    2764802048
evict_l2_skip                   4    4207179
hash_elements                   4    41460022
hash_elements_max               4    41472033
hash_collisions                 4    313418701
hash_chains                     4    1048576
hash_chain_max                  4    71
p                               4    3966005248
c                               4    4294967296
c_min                           4    33554432
c_max                           4    4294967296
size                            4    4314752192
hdr_size                        4    83992
data_size                       4    278528
metadata_size                   4    1861632
other_size                      4    704680
anon_size                       4    61440
anon_evictable_data             4    0
anon_evictable_metadata         4    0
mru_size                        4    1812480
mru_evictable_data              4    0
mru_evictable_metadata          4    0
mru_ghost_size                  4    0
mru_ghost_evictable_data        4    0
mru_ghost_evictable_metadata    4    0
mfu_size                        4    266240
mfu_evictable_data              4    110592
mfu_evictable_metadata          4    0
mfu_ghost_size                  4    0
mfu_ghost_evictable_data        4    0
mfu_ghost_evictable_metadata    4    0
l2_hits                         4    13474090
l2_misses                       4    25729644
l2_feeds                        4    1944495
l2_rw_clash                     4    23
l2_read_bytes                   4    23610330624
l2_write_bytes                  4    147426293760
l2_writes_sent                  4    696760
l2_writes_done                  4    696760
l2_writes_error                 4    0
l2_writes_lock_retry            4    1556
l2_evict_lock_retry             4    0
l2_evict_reading                4    0
l2_evict_l1cached               4    0
l2_free_on_write                4    1366555
l2_cdata_free_on_write          4    638
l2_abort_lowmem                 4    17
l2_cksum_bad                    4    0
l2_io_error                     4    0
l2_size                         4    171941231616
l2_asize                        4    104546883584
l2_hdr_size                     4    4311823360
l2_compress_successes           4    36319801
l2_compress_zeros               4    0
l2_compress_failures            4    20154816
memory_throttle_count           4    0
duplicate_buffers               4    0
duplicate_buffers_size          4    0
duplicate_reads                 4    0
memory_direct_count             4    351
memory_indirect_count           4    75354
arc_no_grow                     4    0
arc_tempreserve                 4    294912
arc_loaned_bytes                4    0
arc_prune                       4    0
arc_meta_used                   4    4314473664
arc_meta_limit                  4    3133510656
arc_meta_max                    4    4328318064
arc_meta_min                    4    16777216
arc_need_free                   4    0
arc_sys_free                    4    130560000
```

**Comment by ptx0** [comment]
does this issue occur on HEAD?

**Comment by hostingnuggets** [comment]
@ptx this is a production server running 0.6.5.6, I can't upgrade to HEAD on this server.

After having read #3926 I suspect the problem could be related to the size of my L2ARC (240 GB) which might be big to be handled by my ARC of 4 GB and hence the constant arc_reclaim. Is this probable? and if yes what would be an optimal size of the ARC or L2ARC in order to avoid such a situation in the future.

**Comment by behlendorf** [comment]
@hostingnuggets yes, that's exactly what's going on.  You can tell by checking the `l2_hdr_size`. According to the arcstats above it has grown to 4.3G or effectively all of your ARC.  Since you're pool is all ssd I'd recommend removing the L2ARC device entirely.

**Comment by hostingnuggets** [comment]
@behlendorf thanks for your analysis. So if I understand you correctly if one has an all SSD ZFS pool there is no need for a L2ARC? even if my L2ARC is a very fast NVMe SSD PCI module which has amazing IOPS as well as something like 2 GB/s r/w transfer speed?

**Comment by ptx0** [comment]
you'll need more ARC if you want the L2ARC - or find a way to optimize the in-memory L2ARC lists.

**Comment by behlendorf** [comment]
@hostingnuggets it's really all about trade offs and striking a good balance on the system for your workload.  In most cases I've seen adding a L2ARC device to an SSD based pool usually isn't worth it unless 1) the L2ARC device is much faster than the SSD based pool, and 2) you have enough available memory to efficiently manage the L2ARC device.  In this case it sounds like you have 1 but not enough of  2 to manage the entire device.

A good compromise might be to create an L2ARC device of say 32GB which will requires a much smaller fraction of the ARC.  The idea here is it should be sized so it's large enough to handle your normal working set (which is presumably larger than memory).  If that working set is smaller than memory you might be better off without an L2ARC and devoting all your memory to the ARC, DRAM is still way faster than a NVMe device!

**Comment by hostingnuggets** [comment]
@behlendorf so it now all makes sense to me, I guess I will go for reducing my L2ARC down to 32 GB as you suggest. Now I have two questions: 

1) is it a safe procedure to remove the L2ARC cache of my pool in production and then add it back?
2) what exactly do you mean with "working set"? I am not familiar with this term and don't know its meaning in the context of ZFS.

**Comment by lnicola** [comment]
@hostingnuggets 

1. Yes, it should be safe to remove the L2ARC while online. But if you repartition the drive you might need to reboot the machine.
2. The working set is usually the data you're using the most (or most of the time). The idea is that you can go without L2ARC if your data fits in ARC.

**Comment by hostingnuggets** [comment]
@behlendorf how do you find out approxmiately how big your working set is? I assume here that the system also needs to be warm and not freshly rebooted.

**Comment by BioSehnsucht** [comment]
If you repartition and the new partitions are not seen right away, try using 'partprobe'. I assume this is available for debian, I have it on CentOS.

**Comment by bknl** [comment]
@hostingnuggets "how do you find out how big your working set is ?"

Have a look at the fill grade of the l2arc (while it's still there) after the machine has "warmed" up for a while (on my pools it took about a day or 2) and simultaneously note down the l2 hit and miss counters. 

Once the filling stops (no matter whether that's at 100% of the L2ARC device or less), you have the upper
bound of the working set. To find the true size, note the L2 miss ratios and then reduce the size of the
L2ARC (binary search worked for me, i.e. half it at first to whatever constituted "full") and then let it refill and note the L2 hit/miss ratio.  When the hit/miss ratio  goes way up compared to whatever the ratio was at the full size, increase somewhat (quarter step, etc.) again, if it's modest, try reducing further.

Sort of poor mans adaptive page fault frequency algorithm.


PS: On my pools I eventually removed l2arc entirely and just got a little more DRAM.

**Comment by hostingnuggets** [comment]
@bknl thanks for your tips regarding L2ARC size optimisation. Right now the server has been up and running for nearly 3 days and I have the following L2ARC stats:

```
L2 ARC Summary: (HEALTHY)
	Low Memory Aborts:			0
	Free on Write:				165
	R/W Clashes:				0
	Bad Checksums:				0
	IO Errors:				0

L2 ARC Size: (Adaptive)				30.89	GiB
	Compressed:			51.84%	16.01	GiB
	Header Size:			2.03%	642.45	MiB

L2 ARC Evicts:
	Lock Retries:				0
	Upon Reading:				0

L2 ARC Breakdown:				59.65m
	Hit Ratio:			0.25%	146.29k
	Miss Ratio:			99.75%	59.50m
	Feeds:					242.36k

L2 ARC Writes:
	Writes Sent:			100.00%	188.77k
```

As you can see the miss ratio looks really bad, meaning my L2ARC is useless. So does this mean now that I should downsize my L2ARC by half? or does it need longer to warm up?

**Comment by richardelling** [comment]
@bknl looking at L2 fill rates is pretty much useless. The better approach is to look at the eviction dispositions: evict_l2_eligible counts bytes evicted that could be written to L2. If you see a high rate, then adding L2 can help. By contrast, if you see a high rate of evict_l2_ineligible, then adding L2 doesn't help. If you have an L2, then evict_l2_cached says ARC is too small, but L2 is useful.

**Comment by hostingnuggets** [comment]
@richardelling to complement your last comment here would be the detailed l2 stats take from /proc/spl/kstat/zfs/arcstats:

```
evict_l2_cached                 4    32972751360
evict_l2_eligible               4    242131968
evict_l2_ineligible             4    5193728
evict_l2_skip                   4    0
l2_hits                         4    149795
l2_misses                       4    59534631
l2_feeds                        4    251551
l2_rw_clash                     4    0
l2_read_bytes                   4    485360640
l2_write_bytes                  4    112347495936
l2_writes_sent                  4    195969
l2_writes_done                  4    195969
l2_writes_error                 4    0
l2_writes_lock_retry            4    256
l2_evict_lock_retry             4    0
l2_evict_reading                4    0
l2_evict_l1cached               4    0
l2_free_on_write                4    165
l2_cdata_free_on_write          4    327
l2_abort_lowmem                 4    0
l2_cksum_bad                    4    0
l2_io_error                     4    0
l2_size                         4    36355565056
l2_asize                        4    18706790912
l2_hdr_size                     4    754587080
l2_compress_successes           4    55019760
l2_compress_zeros               4    0
l2_compress_failures            4    8052208
```

**Comment by bknl** [comment]
Re: @hostingnuggets 

Your miss ratio is already really bad, so downsizing is not going to be the right approach. Whether there ever is a  L2 size at which the hit  ratio climbs remains to be seen (and you didn't seem to have enough RAM to map the entire size).

Re: @richardelling 

I've looked over the comments in module/arc.c describing the meaning of  evict_l2_XXX and now I'm unclear about the meaning of evict_l2_cached.  My method of determining working set size did not
suggest to use L2 fill rate, so I'm a little confused by your comment.

As I understand it, the "eligible/uneligible" just throws out stuff that cannot be cached in L2 due to structural reasons:
   /*
         * A buffer is *not* eligible for the L2ARC if it:
         * 1. belongs to a different spa.
         * 2. is already cached on the L2ARC.
         * 3. has an I/O in progress (it may be an incomplete read).
         * 4. is flagged not eligible (zfs property).
         */

As far as I can make out the meaning of evict_l2_cached, that is only ever incremented when L2 grabs something, but I fail to see how that number tells me whether it ever is *useful* in L2.

My method assumed that there would be *some* hit ratio in a given L2 size and if one wanted to find out
how small L2 could be made without impacting a given hit ratio too much, that method would work (if slowly and painfully).

With the numbers from @hostingnuggets, even at the full size of of his (her ?) current L2, there are essentially neglible hits (over 100 Gbyte written to L2 for a measly 0.5 Gbyte in avoided base device
reads, if I interpret the numbers correctly).

**Comment by hostingnuggets** [comment]
@bknl after the issues I had I raised the ARC RAM from 4 GB to 6 GB and the hypervisor has now in total 16 GB of RAM. I am respecting the ZFS FAQ question which mentions that if you are running ZFS with Xen hypervisor your should now use more than 30-40% of RAM for the ARC.

So my next question would now be what do you recommend me to do? 

Just as a reminder I am using zvols. Two zvols per Xen instance (VM).

**Comment by richardelling** [comment]
Unlike other multi-level caches you might be familiar with, there is not an eviction path from L1 to L2. There is only eviction from L1. Each eviction is classified as I described. Thus by observing the eviction disposition you can determine if L2 is useful or not for the given configuration and workload.

**Comment by hostingnuggets** [comment]
For your information, I can confirm that my issue (arc_reclaim using 100% CPU and slowing down whole system) happens exactly when the L2 header size equals the ARC size.

Does maybe ZFS have any safeguard for this kind of situtation? Or one just have to make sure that the L2ARC is not too big but then again there are no rules defining the maximum size of an L2ARC. I think this should at least be documented somewhere or maybe an FAQ entry.
