### ISSUE TITLE
xattr not seen if they are stored in a Fat ZAP

### ISSUE THREAD

**Issue by mattpepin** [zfsonlinux/zfs#4748]
I'm trying to import a FreeNAS 9.3 pool into Ubuntu 16.04 LTS. Everything works fine except extended attributes. New ones work just fine, but I cannot see the ones that were there before in FreeNAS. I poked around with zdb and here's the difference:

Working (created in Ubuntu):
```
    Object  lvl   iblk   dblk  dsize  lsize   %full  type
      8202    1    16K    512     8K    512  100.00  ZFS directory
                                        168   bonus  System attributes
	dnode flags: USED_BYTES USERUSED_ACCOUNTED 
	dnode maxblkid: 0
	path	/test5/<xattrdir>
	uid     1000
	gid     1000
	atime	Thu Jun  9 15:44:26 2016
	mtime	Thu Jun  9 15:44:26 2016
	ctime	Thu Jun  9 15:44:26 2016
	crtime	Thu Jun  9 15:44:26 2016
	gen	155121
	mode	41777
	size	4
	parent	8201
	links	2
	pflags	40800000145
	microzap: 512 bytes, 2 entries

		user.org.netatalk.Metadata = 8203 (type: Regular File)
		user.com.apple.metadata_kMDItemUserTags:$DATA = 8204 (type: Regular File)
```

Not working (Created in FreeNAS):
```
    Object  lvl   iblk   dblk  dsize  lsize   %full  type
       257    2    16K    16K  24.0K    32K  100.00  ZFS directory
                                        168   bonus  System attributes
	dnode flags: USED_BYTES USERUSED_ACCOUNTED 
	dnode maxblkid: 1
	path	/testfreenas/<xattrdir>
	uid     1001
	gid     1001
	atime	Thu Jun  9 13:08:30 2016
	mtime	Wed Mar  2 21:46:07 2016
	ctime	Wed Mar  2 21:46:07 2016
	crtime	Tue Mar  1 00:18:16 2016
	gen	6635
	mode	41777
	size	5
	parent	12
	links	2
	pflags	40800000145
	Fat ZAP stats:
		Pointer table:
			1024 elements
			zt_blk: 0
			zt_numblks: 0
			zt_shift: 10
			zt_blks_copied: 0
			zt_nextblk: 0
		ZAP entries: 3
		Leaf blocks: 1
		Total blocks: 2
		zap_block_type: 0x8000000000000001
		zap_magic: 0x2f52ab2ab
		zap_salt: 0x65002c3
		Leafs with 2^n pointers:
			  9:      1 *
		Blocks with n*5 entries:
			  0:      1 *
		Blocks n/10 full:
			  1:      1 *
		Entries with n chunks:
			  3:      1 *
			  4:      1 *
			  5:      1 *
		Buckets with n entries:
			  0:    509 ****************************************
			  1:      3 *

		netatalk.Metadata = 258 (type: Regular File)
		org.netatalk.Metadata = 7563 (type: Regular File)
		DosStream.com.apple.metadata_kMDItemUserTags:$DATA = 7564 (type: Regular File)
```

I'm no expert with ZFS, but from what I can tell, one xattr is stored in a microzap, the other in a FAT zap. It looks like ZFS on Linux can't recognize the latter.

**Comment by mattpepin** [comment]
What I mean by not working is that they are not shown when I run "xattr filename" or "getfattr filename". Samba does not see them either.

**Comment by mattpepin** [comment]
OK, I was blind. This has nothing to do with Fat or microzap. The prefixes are different. I'm missing a "user." prefix on all old attributes. Is there a way to fix it on my side?

**Comment by dweeezil** [comment]
ZoL currently enforces a specific set of prefixes.  It looks like FreeBSD may allow arbitrary prefixes.

**Comment by mattpepin** [comment]
Right. It seems that in FreeBSD, unknown prefix = user. It also seems that it's not stored at all if you add an xattr with a user prefix. However, you still have to specify user to list xattr:

```
lsextattr user test
test	org.netatalk.Metadata
```

Looks like a not so easy to fix problem without recopying all files from FreeBSD to another server running ZoL... Am I missing something?

**Comment by mattpepin** [comment]
I came up with a solution. It's working fine for me and all FreeNAS xattrs are now functional. It adds the missing user. prefix to unknown prefixes. It's conditionally compiled with a NO_USER_PREFIX define. It's in my no-user-prefix branch if it's of any use to someone.

https://github.com/mattpepin/zfs/tree/no-user-prefix

**Comment by behlendorf** [comment]
@mattpepin I'm glad you were able to work up a solution, and thanks for posting the patch.
