### ISSUE TITLE
zpool lost after reboot

### ISSUE THREAD

**Issue by jamesbeedy** [zfsonlinux/zfs#4755]
Ubuntu release -> Xenial

My zpool is lost after reboot, and I must re-import it every time :-(

**Comment by kpande** [comment]
this is an issue tracker, not for distribution support. please use the mailing list or file a bug on Launchpad for their ZFS packages.

**Comment by jamesbeedy** [comment]
@kpande can you supply a link? Everything I find on lp points back to here....

**Comment by kpande** [comment]
Sure;

ML: http://list.zfsonlinux.org

Launchpad: https://launchpad.net/ubuntu/xenial/+source/zfs-linux
