### ISSUE TITLE
Boot errors, how to reboot correctly?

### ISSUE THREAD

**Issue by urza** [zfsonlinux/zfs#4757]
Hi, I have debian jessie and zfs on linux (package versions bellow).

I created zpool consisting of two 4TB HDDs in zfs mirror:

 pool1  ONLINE
 -- mirror-0  ONLINE
 -- -- bay1    ONLINE
 -- -- bay2    ONLINE

The disks are ecnrypted BELOW zfs with dmcrypt.
So everytime I boot, I need to dercypt disks and do:
cryptsetup open /dev/sdb bay1
cryptsetup open /dev/sdc bay2
zpool import pool1

Then I can use my pool. That is fine.

Problem is that twice already, my system didn't boot correctly (one was after typing "reboot" command, second time was when power went out unexpectedly). Both times, it ended hanging in emergency mode after some zfs error during boot.
I am attaching screenshot of the boot error and screen showing that my debian booted into emergency environment, which is problem because it is not reachable over ssh and I am not often at the physical location of my server.

Is there anything I can do to prevent this? Is there some correct reboot procedure? What do I need to do? Unmount all zfs? Export my pool? Close the encrypted containers?

What if there will be power failure again? Can I somehow tell debian to boot "no matter what", ignore the errors, so that I can ssh into it and try to clear it?

Thanks for any advises.

![boot_error1](https://cloud.githubusercontent.com/assets/189804/16070876/804e1826-32d8-11e6-9944-0deef16eedce.jpg)
![boot_error2](https://cloud.githubusercontent.com/assets/189804/16070877/805292fc-32d8-11e6-84cf-77f7dc426a1e.jpg)

My debian version:
 Debian GNU/Linux 8.5 (jessie)
 Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08)

ZOL version:
Package: debian-zfs
Version: 7~jessie
Architecture: amd64
Maintainer: Darik Horn <dajhorn@vanadac.com>
Installed-Size: 41
Depends: spl, spl-dkms, zfs-dkms, zfsutils
Recommends: build-essential, linux-headers, zfsonlinux
Suggests: zfs-auto-snapshot
Priority: optional
Section: metapackages
Filename: pool/main/d/debian-zfs/debian-zfs_7~jessie_amd64.deb
Size: 6806
SHA256: 163d21f0c34220463ba5b56c14f3f3ede1b9b5b0f62eee3a738abb8994f108b6
SHA1: f99079b572e74c7cbf203b93292acea4c60c3b02
MD5sum: 6f5846820d147b913f2d114a038d2e7e
Description: Native ZFS filesystem metapackage for Debian.
Description-md5: 4ccc328604d7c59f2850205a963c306f

Package: zfsonlinux
Version: 8
Architecture: all
Maintainer: Turbo Fredriksson <turbo@bayour.com>
Installed-Size: 2054
Pre-Depends: lsb-release
Recommends: debian-zfs
Homepage: http://zfsonlinux.org/
Priority: extra
Section: utils
Filename: pool/main/z/zfsonlinux/zfsonlinux_8_all.deb
Size: 2040474
SHA256: 543c1cd88a16d63cad9ce6bf76dc603adeed3cd785e46078c13b5c953f55dafb
SHA1: f234a8a18919d8d4214e2982f5d538d9b14c0dca
MD5sum: 4d85ab0d7e9f3e2e2bf9d200799d0f7e
Description: archive.zfsonlinux.org trust package
 This package installs the GPG keys and APT sources for the
 archive.zfsonlinux.org package repository.
Description-md5: 992d833f23f9e5879059e6edd4919d11

**Comment by kpande** [comment]
these packages are made by @FransUrbo

**Comment by FransUrbo** [comment]
Using zfs on luks partition haven't been properly tested. I recommend taking this to the mailing list, it's more of a support question than a real bug.
