### ISSUE TITLE
User access to NFS share broken sometime after 0.6.5.x

### ISSUE THREAD

**Issue by iamjamestl** [zfsonlinux/zfs#4758]
On 0.6.5.7 and earlier, I can share a dataset over NFS and operate on it with my regular user.  For example, on a clean system running Linux 4.5.6:

As root:
```
> zfs create -o mountpoint=/share -o sharenfs=on test/share
> mount localhost:/share /mnt   # demonstrate over localhost to eliminate any UID-mismatch/idmap nonsense
> chown james /mnt
```

As james:
```
> cd /mnt
> touch test
> ls -al test
-rw-r--r-- 1 james users 0 Jun 15 16:37 test
```

Good. Then, changing nothing but `zfs`, `zfs-kmod`, and `spl` to use the current git HEAD, f74b821a6696fef9e9953aae05941e99bf83800e:

As root:
```
> zfs destroy test/share
> zfs create -o mountpoint=/share -o sharenfs=on test/share
> mount localhost:/share /mnt   # demonstrate over localhost to eliminate any UID-mismatch/idmap nonsense
> chown james /mnt
```

As james:
```
> cd /mnt
> touch test
touch: cannot touch ‘test’: Permission denied
> ls -al test
-rw-r--r-- 1 root root 0 Jun 15 16:55 test
```

For some reason, the file gets created with root ownership.  This goes for any newly-created files.  I can change the ownership as root and then have write access to it as my regular user:

```
> sudo chown james /share/test
> ls -al /mnt/test
-rw-r--r-- 1 james root 4 Jun 15 16:57 /mnt/test
> echo blah > /mnt/test
> cat /mnt/test
blah
```

Extra info:
```
> uname -a
Linux test 4.5.6-gentoo #1 SMP Wed Jun 15 13:45:57 EDT 2016 x86_64 Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz GenuineIntel GNU/Linux
> mount | grep share
test/share on /share type zfs (rw,xattr,posixacl)
localhost:/share on /mnt type nfs4 (rw,relatime,vers=4.2,rsize=524288,wsize=524288,namlen=255,hard,proto=tcp6,port=0,timeo=600,retrans=2,sec=sys,clientaddr=::1,local_lock=none,addr=::1)
> cat /proc/fs/nfs/exports 
# Version 1.1
# Path Client(Flags) # IPs
/       *(ro,no_root_squash,sync,no_wdelay,no_subtree_check,v4root,fsid=0,uuid=500caa80:002833da:00000000:00000000,sec=390003:390004:390005:1)
/share  *(rw,no_root_squash,sync,wdelay,no_subtree_check,uuid=1ceb312a:00b489e4:00000000:00000000,sec=1)
```

**Comment by AB17** [comment]
Confirmed.
We are having this issue as well.

**Comment by AB17** [comment]
The June 1st master is OK.
The latest one is not.
This happened with one of the commits from June 2 onwards.
I've tested using kernel 4.4.12 and 4.4.13.

**Comment by behlendorf** [comment]
Thanks for the bug report.  My guess is this was accidentally introduced when support for `zfs allow` was merged on June 7th, see commit f74b821a6696fef9e9953aae05941e99bf83800e.  This only impacts access via NFS correct?  It would be great if you could try reverting the `zfs allow` commit and verify that resolves the issue.

**Comment by AB17** [comment]
Will build again on Monday and revert that commit.
Will confirm.

**Comment by tuxoko** [comment]
@behlendorf 
This is definitely introduced by https://github.com/zfsonlinux/zfs/commit/f74b821a6696fef9e9953aae05941e99bf83800e

That patch "enables" `zfs_acl_ids_create` and `zfs_fuid_create_cred` which is used in filesystem operations. But it uses euid and egid, rather than fsuid and fsgid. These two functions are only used in filesystem operations, so I think these two function should be revert.

**Comment by behlendorf** [comment]
@tuxoko indeed.  Could you propose a patch which reverts the `zfs_acl_ids_create` and `zfs_fuid_create_cred` change by wrapping them with `#if defined(__sun__)`.

**Comment by tuxoko** [comment]
@behlendorf 
It might not be just those two functions. There are several secpolicy_*() in filesystem operations that were disabled before this patch.

**Comment by behlendorf** [comment]
The delegation patch enabled ~70 or so new test cases which were used to verify all of this was functioning correctly.  Of course, all of those test cases covered testing local filesystems and not access via NFS.  I haven't dug too deeply in to this but what must be happening is the CRED being passed by the NFS server when performing the create is the kcred.  We'll need to add code to handle this in a similar fashion as before for NFS.

**Comment by tuxoko** [comment]
Yes, fsuid and fsgid normally would be the same as euid and guid. But on linux, NFS server only changed fsuid and fsgid according to the credential provided by client, so we have this problem. Linux actually has setfsuid(2) and setfsgid(2) syscalls that can let user program does things like NFS server. We can leverage them in test cases without really setting up NFS.

**Comment by AB17** [comment]
@behlendorf 
Latest master is now fine with this commit reverted.
Confirmed NFS file permission issue is down to https://github.com/zfsonlinux/zfs/commit/f74b821a6696fef9e9953aae05941e99bf83800e

**Comment by behlendorf** [comment]
Verified the fix and merged to master as:

100a91a Fix NFS credential
