### ISSUE TITLE
Question: remove disk from pool

### ISSUE THREAD

**Issue by galindro** [zfsonlinux/zfs#4762]
Is it possible to remove a disk from a pool that was added by mistake to save storage space? If no, why?

I can do it with LVM2: http://superuser.com/questions/820488/remove-a-physical-volume-from-vg-with-no-free-pe.

**Comment by kpande** [comment]
please use the mailing list (http://list.zfsonlinux.org) for support questions.

**Comment by galindro** [comment]
Sorry...
