### ISSUE TITLE
Wiki : libvirt/uefi issue on Ubuntu 16.04 Root on ZFS

### ISSUE THREAD

**Issue by eviweb** [zfsonlinux/zfs#4764]
Hi,
I spent a lot of time making a *qemu/kvm* virtual machine to succeed in booting in *UEFI* mode.
In fact the prerequisites are:
* `ovmf`: a version that provides the split CODE/VARS binaries, (ie. [Gerd Hoffman's daily build](https://www.kraxel.org/repos/jenkins/edk2/))    
Both CODE and VARS files should be installed under: `/usr/share/OVMF`
* `libvirt`: version >= 1.2.8, with the `nvram` setting enabled in `/etc/libvirt/qemu.conf`    
```
nvram = [
    "/usr/share/OVMF/OVMF_CODE.fd:/usr/share/OVMF/OVMF_VARS.fd"
]
```
The reason is that without this, the boot manager configuration does not persist after reboot.
May you update the *Troubleshooting > QEMU/KVM/XEN* section of this [page](https://github.com/zfsonlinux/zfs/wiki/Ubuntu%2016.04%20Root%20on%20ZFS), please ?

Thanks

Eric

**Comment by behlendorf** [comment]
Tagging @rlaager to look at this.

**Comment by rlaager** [comment]
@eviweb Does the version of ovmf in 16.04 have the appropriate split?

In other words, are these steps sufficient?
1) Install stock 16.04 host.
2) Install libvirt-bin and ovmf.

Do we also need this step?
3) Uncomment the nvram line in /etc/libvirt/qemu.conf.

**Comment by eviweb** [comment]
Hi @rlaager,
yes, indeed, the ovmf package provided by Ubuntu 16.04 contains the appropriate split.
All of the three mentioned steps are required.
For info, I was previously under Ubuntu 14.04 and after upgrading to 16.04, I was able to persist the boot manager configuration.
Hope that's help.
Eric

**Comment by rlaager** [comment]
Thanks. I updated the wiki.
