### ISSUE TITLE
Ubuntu 16.04 failure to import on boot

### ISSUE THREAD

**Issue by markjohnson** [zfsonlinux/zfs#4770]
Ubuntu 16.04 LTS host wouldn't come back up after maintenance reboot. Hung when trying to bring up ZFS.

Last message on the console was:

Starting import ZFS pools by cache file...
VERIFY(rs == NULL) failed
PANIC at range_tree.c:186:range_tree_add()

One drive had dropped out of the array prior to the reboot and hadn't been replaced.  On a hunch I backed up and removed /etc/zfs/zpool.cache and the system booted and the pool came up normally.  Can provide the old pool.cache upon request.

**Comment by loli10K** [comment]
A similar (duplicate?) issue was just reported (#7157), i'm going to close this one since it has not seen activity in more than a year and the other one may have some fresh data to troubleshoot the problem.
