### ISSUE TITLE
[zfs-auto-snapshot] Feature request - configuration dialog

### ISSUE THREAD

**Issue by kingneutron** [zfsonlinux/zfs#4775]
--The default settings for zfs-auto-snapshot are a bit crazy. Who needs snapshots every 15 minutes by default? That was keeping my disks from spinning down.

--Since it is being supplied in a package, can we get a dialog box that lists existing zfs datasets and has at least checkboxes for "enable at pool level and inherit downward" and for monthly, weekly, daily, and what hour(s) to schedule snapshots for?

Note - I am happy to attempt a shot at coding this, at least for Ubuntu 14.04-64-LTS if someone can provide a few links in the right direction. Would also make sense to have something like this in webmin... I am proficient at bash, but more of an admin than a general coder.

**Comment by kpande** [comment]
this is a legacy script that is mostly unmaintained, feel free to send a PR, but it's unlikely this will happen. if you'd like further discussion, I suggest the zfs-discuss (or openzfs) mailing list: http://list.zfsonlinux.org

you may find timeslider useful: https://github.com/Lalufu/time-slider

**Comment by mailinglists35** [comment]
you might want to report this issue to this repo, I think: https://github.com/zfsonlinux/zfs-auto-snapshot
zfsonlinux/zfs is just for the zfs module and utilities (zfs-auto-snapshot is NOT coded here)

**Comment by kingneutron** [comment]
Thanks for the info, all :-)
