### ISSUE TITLE
issue report template

### ISSUE THREAD

**Issue by kpande** [zfsonlinux/zfs#4776]
We need a standard format to report bugs, and github allows the use of a special markdown file in the .github directory to provide a pre-filled issue or pull request template, though I think issues are the more pressing matter.

A script could be bundled with the source to retrieve system information:
- SPL, ZFS, Kernel, distribution name + versions
- ARC / Memory statistics
- Process list?
- Stack traces?
- dmesg output?

Open to input.

**Comment by FransUrbo** [comment]
Have a look at https://github.com/zfsonlinux/zfs/pull/2727
