### ISSUE TITLE
Block layer statistics in /sys/block/zdX/stat in ZOL 0.6.5 are empty

### ISSUE THREAD

**Issue by arturpzol** [zfsonlinux/zfs#4777]
Hello,

In ZOL 0.6.5.6 and in trunk sources block layer statistics for zvols in /sys/block/zdX/stat files are empty e.g.:

```
cat /sys/block/zd16/stat 
       0        0        0        0        0        0        0        0        0        0        0
```

Of course I wrote and read some data to that zvol before read stat file.
In 0.6.4 that statistics were filled out. 

Does it intentional changes?

**Comment by behlendorf** [comment]
@arturpzol what kernel version are you using?  These value are reported properly for me with 0.6.5.7 on Ubuntu 16.04, kernel 4.4.0-22-generic.

**Comment by arturpzol** [comment]
Thanks for feedback.
I am using native kernel version 3.10.92.
I will test with newer kernel version and let you know.

**Comment by kpande** [comment]
You will need kernel newer than 3.19
