### ISSUE TITLE
Fedora 24 Package

### ISSUE THREAD

**Issue by rabin-io** [zfsonlinux/zfs#4782]
Can you please add it ?

**Comment by behlendorf** [comment]
Thanks for letting us know this was released.  We'll get it added, in the meanwhile the Fedora 23 DKMS package should continue to work fine.

**Comment by rabin-io** [comment]
Thanks, It's working.

**Comment by rabin-io** [comment]
Thank you.

**Comment by 0mkara** [comment]
Fedora 23 DKMS package gives me repo sync error on Fedora 24.

**Comment by error10** [comment]
This has taken an extraordinarily long time to resolve, for what should be a very simple process. It is starting to become a bit of a problem, as while you can work around it, this isn't very convenient for new OS installations, where ZFS is inexplicably not available at all. What can we do about this?

**Comment by behlendorf** [comment]
Packages have been added for Fedora 24.

**Comment by IainDouglas** [comment]
I installed this earlier over a working Fedora 23 package and it failed with this error 

> configure: error:
        *** Please make sure the kmod spl devel <kernel> package for your
        *** distribution is installed then try again.  If that fails you
        *** can specify the location of the spl objects with the
        *** '--with-spl-obj=PATH' option.

So far as I could tell everything that should be there was. I ended up removing the ZFS packages and their dependencies followed by a reinstall which solved the problem.

I know someone else who had the same problem and solved it with

```
dkms install spl/0.6.5.7
dkms install zfs/0.6.5.7
```

**Comment by fearedbliss** [comment]
I just had the same issue with a new Fedora 24 server installation and removing/reinstalling or dkms install didn't work.

  Installing  : spl-dkms-0.6.5.7-1.fc24.noarch                                                                                            15/22
Loading new spl-0.6.5.7 DKMS files...
Building for 4.7.2-201.fc24.x86_64
Building initial module for 4.7.2-201.fc24.x86_64
Error! Bad return status for module build on kernel: 4.7.2-201.fc24.x86_64 (x86_64)
Consult /var/lib/dkms/spl/0.6.5.7/build/make.log for more information.
warning: %post(spl-dkms-0.6.5.7-1.fc24.noarch) scriptlet failed, exit status 10
Non-fatal POSTIN scriptlet failure in rpm package spl-dkms
Non-fatal POSTIN scriptlet failure in rpm package spl-dkms
  Installing  : spl-0.6.5.7-1.fc24.x86_64                                                                                                 16/22
  Installing  : python-libs-2.7.12-2.fc24.x86_64                                                                                          17/22
  Installing  : python-pip-8.0.2-1.fc24.noarch                                                                                            18/22
  Installing  : python2-setuptools-20.1.1-1.fc24.noarch                                                                                   19/22
  Installing  : python-2.7.12-2.fc24.x86_64                                                                                               20/22
  Installing  : zfs-dkms-0.6.5.7-1.fc24.noarch                                                                                            21/22
Loading new zfs-0.6.5.7 DKMS files...
Building for 4.7.2-201.fc24.x86_64
Building initial module for 4.7.2-201.fc24.x86_64
configure: error:
        *** Please make sure the kmod spl devel <kernel> package for your
        *** distribution is installed then try again.  If that fails you
        *** can specify the location of the spl objects with the
        *** '--with-spl-obj=PATH' option.
Error! Bad return status for module build on kernel: 4.7.2-201.fc24.x86_64 (x86_64)
Consult /var/lib/dkms/zfs/0.6.5.7/build/make.log for more information.
warning: %post(zfs-dkms-0.6.5.7-1.fc24.noarch) scriptlet failed, exit status 10
Non-fatal POSTIN scriptlet failure in rpm package zfs-dkms
Non-fatal POSTIN scriptlet failure in rpm package zfs-dkms
  Installing  : zfs-0.6.5.7-1.fc24.x86_64                                                                                                 22/22
  Verifying   : zfs-0.6.5.7-1.fc24.x86_64                                                                                                  1/22
  Verifying   : libnvpair1-0.6.5.7-1.fc24.x86_64                                                                                           2/22
  Verifying   : libuutil1-0.6.5.7-1.fc24.x86_64                                                                                            3/22
  Verifying   : libzfs2-0.6.5.7-1.fc24.x86_64                                                                                              4/22
  Verifying   : libzpool2-0.6.5.7-1.fc24.x86_64                                                                                            5/22
  Verifying   : spl-0.6.5.7-1.fc24.x86_64                                                                                                  6/22
  Verifying   : zfs-dkms-0.6.5.7-1.fc24.noarch                                                                                             7/22
  Verifying   : spl-dkms-0.6.5.7-1.fc24.noarch                                                                                             8/22
  Verifying   : dkms-2.2.0.3-34.git.9e0394d.fc24.noarch                                                                                    9/22
  Verifying   : gcc-6.1.1-3.fc24.x86_64                                                                                                   10/22
  Verifying   : libmpc-1.0.2-5.fc24.x86_64                                                                                                11/22
  Verifying   : mpfr-3.1.4-1.fc24.x86_64                                                                                                  12/22
  Verifying   : cpp-6.1.1-3.fc24.x86_64                                                                                                   13/22
  Verifying   : python-2.7.12-2.fc24.x86_64                                                                                               14/22
  Verifying   : python-pip-8.0.2-1.fc24.noarch                                                                                            15/22
  Verifying   : python2-setuptools-20.1.1-1.fc24.noarch                                                                                   16/22
  Verifying   : python-libs-2.7.12-2.fc24.x86_64                                                                                          17/22
  Verifying   : binutils-2.26.1-1.fc24.x86_64                                                                                             18/22
  Verifying   : glibc-devel-2.23.1-10.fc24.x86_64                                                                                         19/22
  Verifying   : isl-0.14-5.fc24.x86_64                                                                                                    20/22
  Verifying   : glibc-headers-2.23.1-10.fc24.x86_64                                                                                       21/22
  Verifying   : kernel-headers-4.7.2-201.fc24.x86_64     

[root@bethany ~]# zpool status
The ZFS modules are not loaded.
Try running '/sbin/modprobe zfs' as root to load them.
[root@bethany ~]# modprobe zfs
modprobe: FATAL: Module zfs not found in directory /lib/modules/4.7.2-201.fc24.x86_64

**Comment by error10** [comment]
@fearedbliss That has nothing to do with this issue. You want issue #5064.

**Comment by fearedbliss** [comment]
@error10 ah! ok, thanks!
