### ISSUE TITLE
SSE not available in New RAIDZ implementation

### ISSUE THREAD

**Issue by angstymeat** [zfsonlinux/zfs#4783]
I've just compiled and installed installed version 0.6.5-310_gd0de2e8 onto a system and it does not appear to have the SSE implementation available  (#4328).

When I run "`cat /sys/module/zfs/parameters/zfs_vdev_raidz_impl`" I get "`[fastest] original scalar`", even though my system has SSE available:

`
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr **sse** **sse2** ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm **sse4a** misalignsse 3dnowprefetch osvw ibs skinit wdt nodeid_msr hw_pstate npt lbrv svm_lock nrip_save pausefilter vmmcall
`

I appear to have passed the configure checks for SSE, too.

I'm running Fedora 23 with kernel 4.4.8-300.fc23.x86_64 on a Dell R515.

**Comment by ironMann** [comment]
It seem that your CPU does not support SSSE3, needed for reconstruction path...

Can you post your CPU model number?
Also, for now, SIMD code works only in x86_64 mode.

If this is a common situation, an alternative reconstruction method could be implemented.

**Comment by angstymeat** [comment]
I hadn't looked closely enough to realize that SIMD was an Intel technology.

My CPUs are AMD Opterons. On this particular machine I'm using the AMD Opteron 4130. I have other servers running 6328 processors.

**Comment by ironMann** [comment]
AMD started supporting SSSE3 starting with Bulldozer based Opterons, about 5years after Intel Xeons [wiki source](https://en.wikipedia.org/wiki/List_of_AMD_Opteron_microprocessors)
So this should work on 6328.

I'll start thinking about solution to close that gap, but I doubt it will be as efficient as with SSSE3.
sidenote: 'scalar' handles RAIDZ3 much faster than original.

**Comment by angstymeat** [comment]
Thanks!

I see ssse3 support in the cpuinfo for our 6328-based systems. The 4130-based one is an older one I use for network monitoring and 2nd-tier backups, so I tested it there first.

I think I'm seeing a difference even with the scalar implementation on RAIDZ1 & 2, but I'm having a heck of a time with consistency in my sysbench benchmarks.

**Comment by ironMann** [comment]
@angstymeat New SSE2 implementation is in #4815 
Could you give it a try on your 4130-based test system? It would be good to know if everything is working as expected.

**Comment by angstymeat** [comment]
Thanks! My system is currently performing backups, but I'll install it and try it tomorrow when it is quiescent.

Also, I have a couple of newer processors on the way for it, anyway, but I have a few other systems that I can't justify upgrading that this could help with.
