### ISSUE TITLE
Defragmentation like on btrfs

### ISSUE THREAD

**Issue by RubenKelevra** [zfsonlinux/zfs#4785]
It would be nice to implement an defragmentation support and a possible to display the file-fragmentation on a disk.

Currently it's only possible to view the fragmentation of the free space (how is this calculated??).

**Comment by Sachiru** [comment]
As is repeated multiple times, this requires block pointer rewrite, and as
such, is very far from being done.

There are 10 kinds of people in the world; those who can read binary and
those who can't.

**Comment by kpande** [comment]
duplicate of #264

**Comment by ryao** [comment]
You can see block pointers with zdb, which lets you see to what extent is a file is fragmented. Run `zdb -ddddd $dataset $objectID` The object id is the inode number reported by the VFS. You can find it out via the `stat` command.

Fragmentation is a normal aspect of filesystems. It is required for a CoW filesystem to function and is a requirement for filesystems in general. Fragmentation is a non-issue when the average IO size times the IOPS constrains the sequential throughput. The 128KB default record size should limit the extent to which fragmentation can affect performance, at the trade-off of read-modify-write IO amplification when your IOs are routinely smaller than it such as under a database workload (where you will want a smaller recordsize).

The ill effects attributed to file fragmentation in ZFS are often ZFS' own anti-fragmentation measures taking effect when metaslabs reach 96% full to prevent a bad situation from becoming worse. At that point, the codebase switches from first fit allocation behavior to best fit allocation behavior. That is extremely CPU intensive and can limit IOPS. There is also the effect of bandwidth on rotational disks being roughly twice as high at the outermost tracks than at the innermost tracks. ZFS has a feature called LBA weighting that will prefer metaslabs at the outermost tracks (at low LBAs). This increases bandwidth while the pool is relatively empty, but causes metaslabs to enter the best-fit allocator earlier and has the effect of making the decrease in performance when the pool is relatively full more apparent from having mostly only the inner most platters to use.

LBA weighting can be disabled globally via the `metaslab_lba_weighting_enabled` kernel module parameter. It was automatically disabled on non-rotational was disabled by a commit last year:

https://github.com/zfsonlinux/zfs/commit/fb40095f5f0853946f8150481ca22602d1334dfe

If you are willing to sacrifice some performance when a pool is empty for better performance when a pool is full, you could disable lba weighting via `echo 0 > /sys/module/zfs/parameters/metaslab_lba_weighting_enabled` at runtime. This affects all pools on a system. If you are not using an initramfs, you can likely have the kernel module loaded with the option by doing `echo options zfs metaslab_lba_weighting_enabled=0 >> /etc/modprobe.d/zfs.conf`. If you use an initramfs (or even if you don't), it might be possible to do the same by booting with the kernel commandline parameter `zfs.metaslab_lba_weighting_enabled=0`.

**Comment by RubenKelevra** [comment]
Thanks for your very informative response @ryao, I've using zfs as storage for raw files for vservers. I added a cronjob which do snapshots every two ours. The server exports the diff via send | receive to a backup storage.

Rolling back can be easily done if the snapshot is still on the main machines but I have to copy the entirely data back if it's deleted on the main machines.

So the issue of fragmentation in this case is very very strong, the disks are doing the triple times of IO than one year earlier, but the load is about the same. 

So I think my usecase is pretty bad on the current approach because the plain raw files are going to be fragmented more and more, because the original chunks remain as snapshot-data for fast recovery.

It would be nice if it would be possible to just rewrite the actual last data to a new location at once and let the snapshot-data laying fragmented on disk - nobody cares here.

**Comment by ryao** [comment]
@RubenKelevra You are probably seeing read-modify-write IO amplification on the VM disk images. You will want to set recordsize=4K and do a send/recv to ensure that the VMs are stored with recordsize=4K. Changing it on the dataset will only affect new files, so either copying them or doing a send/recv is necessary to change the record size. Doing a full send/recv before shutting down a VM and then doing an incremental send/recv should make the transition easier.

**Comment by ryao** [comment]
@RubenKelevra I suggest reading this:

http://open-zfs.org/wiki/Performance_tuning

**Comment by RubenKelevra** [comment]
Actually I use only one DB-Server per Hypervisor, and `/var` got it's own hdd which has 8k recordsize :)
