### ISSUE TITLE
ZFS + CentOS 6 - very low performance of pool and not working SSD write cache

### ISSUE THREAD

**Issue by vutfastcit** [zfsonlinux/zfs#4786]
Hello,

I need advice on where might be wrong? 

**Description of the problem:**
Configuration below, I have a very low performance (xx MB/s) of the entire pool. SSD for writing not work. Write operations do not make use SSD (logs). Pool is connected to a Windows Server 2012 R2 via iSCSI initiator (192.168.1.0/24, 10 GbE, MTU 9000).

**Production configuration:**
OS:

> centos-release-6-7.el6.centos.12.3.x86_64

Kernel:

> 2.6.32-573.18.1.el6.x86_64

ZFS:

> zfs-release-1-4.el6.noarch
> zfs-0.6.5.4-1.el6.x86_64
> libzfs2-0.6.5.4-1.el6.x86_64
> zfs-dkms-0.6.5.4-1.el6.noarch

ZPOOL LIST:

> NAME         SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
> storage701  25,4T  9,28T  16,1T         -    22%    36%  1.00x  ONLINE  -

ZPOOL STATUS:

> ```
>     NAME                                             STATE     READ WRITE CKSUM
>     storage701                                       ONLINE       0     0     0
>       mirror-0                                       ONLINE       0     0     0
>         scsi-350014ee5aaabb6f4                       ONLINE       0     0     0
>         scsi-350014ee555565aac                       ONLINE       0     0     0
>       mirror-1                                       ONLINE       0     0     0
>         scsi-350000c0f01dd1694                       ONLINE       0     0     0
>         scsi-350000c0f028c1efc                       ONLINE       0     0     0
>       mirror-2                                       ONLINE       0     0     0
>         scsi-350000c0f028b9040                       ONLINE       0     0     0
>         scsi-350000c0f02f00d40                       ONLINE       0     0     0
>       mirror-3                                       ONLINE       0     0     0
>         scsi-350000c0f01f553c8                       ONLINE       0     0     0
>         scsi-350000c0f0299d5c8                       ONLINE       0     0     0
>       mirror-4                                       ONLINE       0     0     0
>         scsi-350000c0f023d1924                       ONLINE       0     0     0
>         scsi-350000c0f02f01344                       ONLINE       0     0     0
>       mirror-5                                       ONLINE       0     0     0
>         scsi-350000c0f01352c04                       ONLINE       0     0     0
>         scsi-350000c0f01ef51ac                       ONLINE       0     0     0
>       mirror-6                                       ONLINE       0     0     0
>         scsi-350000c0f01f337b0                       ONLINE       0     0     0
>         scsi-350000c0f01f30084                       ONLINE       0     0     0
>     logs
>       mirror-7                                       ONLINE       0     0     0
>         scsi-SATA_INTEL_SSDSC2BA1BTTV335105J2100FGN  ONLINE       0     0     0
>         scsi-SATA_INTEL_SSDSC2BA1BTTV3352055K100FGN  ONLINE       0     0     0
>     cache
>       scsi-SATA_KINGSTON_SH103S50026B722A0185F4      ONLINE       0     0     0
>       scsi-SATA_KINGSTON_SH100S50026B7227012EE9      ONLINE       0     0     0
>       scsi-SATA_KINGSTON_SH103S50026B722A0187CD      ONLINE       0     0     0
> ```
> 
> errors: No known data errors

ZPOOL IOSTAT (Idle state):
![logs-ssd](https://cloud.githubusercontent.com/assets/20104690/16295475/674b0ff0-3927-11e6-8112-590e0db9cdf8.jpg)

MK

**Comment by kpande** [comment]
support requests are better off done via [IRC or the zfs-discuss mailing list](http://list.zfsonlinux.org)
