### ISSUE TITLE
Enhancement: Port AVX2 Fletcher-4 algorithm to SSSE3

### ISSUE THREAD

**Issue by tj90241** [zfsonlinux/zfs#4789]
Hi all and thanks for such a great FS!

I saw 1eeb4562a72ab29345572609e1e4315ecd26c5a1 the other day and was intrigued. Unfortunately, my NAS only supports SSSE3, so I backported the algorithm. The module's microbenchmark selected the SSSE3 implementation over the scalar one, so there is a benefit to vectorization even when doing two additions per cycle instead of four... but I'm not sure by how much without profiling.

Is there any interest in accepting this? If so, i will gladly work to get this into a mergeable state.

One thing I will note is that I couldn't figure out how to make the math in the [paper](https://software.intel.com/en-us/articles/fast-computation-of-fletcher-checksums) work for two lanes (as opposed to four). As a result, I had to use 10 XMM registers and thus the code only works for x86_64 and not IA-32. If someone is willing to give me the final checksum correction for two lanes, I can modify the patch to work on IA-32 as well.

Another small note is that this commit could be made ever so marginally faster with SSE4, but I figured it was better to stick with SSSE3 for the sake of compatibility.

**Comment by behlendorf** [comment]
@tj90241 adding a SSSE3 implementation of fletcher4 would definitely be worth while and appreciated by many!  Please open a pull request with the proposed implementation and hopefully @jxiong and @ironMann can take a look.  They've both been heavily involved in the recent vectorization work.

**Comment by ironMann** [comment]
@tj90241 Great, please share so we can take a look. 
About the math you mentioned, I ran the numbers for two lanes quickly, weights should be as follows: 
a = a0 + a1; 
b = 2b0 + 2b1 - a1; 
c = 4c0 - b0 + 4c1 -3b1; 
d = 8d0 - 4c0 + 8d1 - 8c1 + b1; 
Also, it might be worthwhile making this SSE2 only, to get better coverage. Do you use SSSE3 for byteswap variant only?

**Comment by tj90241** [comment]
@ironMann Thanks so much for the weights! I'll revise my commit and make a pull request shortly.

Yes, SSSE3 is only used for the byteswap variant (as it requires pshufb). I could also create two fletcher_ops_t structs; one for SSE2 and one for SSSE3 -- they would share all member functions other than the byteswap routine.

**Comment by ironMann** [comment]
@tj90241 this looks great, do you have any performance numbers?

Before doing SSE2, I wonder how much would a 'superscalar' version benefit from this decomposition. CPUs can perform at least 2 independent ADDs simultaneously, which we can provide by splitting the algorithm in two lanes. Without having to do `kfpu_begin()/end()` it might very well be as fast as SSE variant.

**Comment by tj90241** [comment]
No performance numbers, yet - I'll work on getting some this weekend.

The SSE2 is likely to benefit over a superscalar variant because everything is twice is wide. Although not shown here, we can unroll the loop once and use a 128-bit load instead of doing a 64-bit load each iteration. This should artificially inflate the window size, etc. etc. I'll get some numbers for these cases too.

**Comment by ironMann** [comment]
@tj90241 This is coming along nicely! However, I find the benchmark to be somewhat misrepresenting.
AVX2 fletcher was pushed forward as a part of effort to enable large streaming writes for Lustre [slideset](http://wiki.lustre.org/images/2/21/LUG2016D1_Large-Streaming-IO-for-Lustre-on-ZFS_Jinshan-Xiong_Revised_v2.pdf)
For block as large as 16MB, `fini()` method should not make much difference, but for 'normal' ZFS use cases it might, as they noted in the article.

@behlendorf I propose the selection benchmark includes all stages needed to get full fletcher4 checksum, including `init()/compute()/fini()`in every iteration.
Also, they should be run on a block size representative of typical block size used.
If someone has different criteria for implementation selection, some kind of `fletcher4_factory()` can be implemented to take those into account.

**Comment by behlendorf** [comment]
@tj90241 the updated patch LGTM and works as expected in my local testing.

@ironMann I'm all for changing the benchmark as you've described to make it more realistic.  This was mentioned in the original review but with only avx2 and a scalar implementation it didn't really matter.  The relative performance difference between the two implementations was huge. However, I agree that as we add additional implementations having a more realistic benchmark workload is important.

@tj90241 @ironMann I'm happy to merge a patch which reworks these benchmarks if you can propose one in a PR.

**Comment by tj90241** [comment]
@ironMann @behlendorf I agree that init/fini should be measured. The current benchmark uses a blocksize of 4096. That being said, is it sufficient to benchmark init/compute/byteswap/fini on a 4096 and assume larger block sizes have a speedup that is >= that achieved for a 4096 blocksize? Is blocksize < 4096 used anywhere?

If this is not a safe assumption, what blocksize(s) should be used to benchmark?

**Comment by ironMann** [comment]
@tj90241 I propose 512KiB. It's between typical record sizes (128K and 1M), and should fit into caches of most CPUs.

**Comment by behlendorf** [comment]
How about 128K, SPA_OLD_MAXBLOCKSIZE, instead to try and minimize our memory footprint at module load time.  This is still by far the most common block size in use even though 1M (and larger) blocks are supported.  It would be interested to run the benchmark with both sizes and see if there's any significant difference in performance.

**Comment by tj90241** [comment]
@ironMann @behlendorf Thanks for your input. I will experiment with those blocksizes (4k, 128k,512k,1M) on different machines and report back.

**Comment by ironMann** [comment]
I got my hands on `Intel(R) Xeon Phi(TM) CPU 7210` and I implemented fletcher4 on avx512f. Here are results for full checksum calculation (native) for different block sizes:
```
fletcher4	4KB		16KB	64KB	128KB	256KB	1MB		16MB
--------------------------------------------------------------------
[scalar]	1213	1228	1231	1231	1225	1200	1160
[sse2]		2374	2442	2459	2456	2462	2250	2220
[avx2]		4288	4753	4871	4893	4900	4050	3882
[avx512f]	5975	8445	9196	9221	9262	6307	5620
```

**Comment by behlendorf** [comment]
@ironMann nice!  It looks like any of these block sizes would work fine for the purposes of a benchmark.  I'd suggest 128K for the reasons mentioned above.  If you can review the sse2 implementation and sign-off on it too I'll see about getting it merged.  Then it would be great if you could open a PR with your avx512f optimized versions which shows an awesome improvement!

**Comment by ironMann** [comment]
@behlendorf will do. Just a note on this benchmark: These xeon phis actually use Atom class cores clocked ~1.3GHz, 64 of them on a die, with 4-way HT, and dedicated powerful vector unit. For this reason difference between scalar and simd might be larger than on more conventional CPUs. But it's nice to have it for when AVX512 becomes more mainstream.
