### ISSUE TITLE
Poor throughput to vdevs with well conditioned IO

### ISSUE THREAD

**Issue by KungFuJesus** [zfsonlinux/zfs#4792]
I'll try to include all the details I know off the top of my head.

This is a broadwell based chipset, with a SuperMicro board.  It's utilizing two Xeon E5-2660 v4's, with 128GB of memory.  X2APIC is enabled (though I've experimented with disabling it as well).  VT-d is disabled.  I'm running Ubuntu Server 16.04.  I'm using 4x Seagate constellation drives (ST91000640NS).  These drives are natively 512 byte sectors, though I've tried forcing ashift to be 12 as well when creating the pool.

When I run dd if=/dev/zero of=testfile bs=4m count=8000, I get full disk throughput to each of the 4 devices (whether configured in a pair of mirrors or a single raidz1) for a little bit.  Then I seem to hit a performance cliff, my disks claim to be 100% busy but the svctime in iostat goes from ~.5-1.5ms to 9ms, and txg_sync starts to hang.  I can start another dd or other ideal sequential write workload at the same time, and performance for that IO will have the same effect (initially high throughput while the subsequent one is still in progress, and slowly flushing).  Then after a while that IO will screech to the whopping 13MB/sec / disk just as the former did.  

I boot with the same exact hardware and the same exact pool in FreeBSD (mfsbsd 10.3) and I don't see any of these issues.  I don't think it's a thermal throttling issue, as I can issue more IO while the slow IO is in progress and get great throughput for a certain duration.  Smartctl says the disks are perfectly healthy.  Sometimes the dd will return really quickly when it manages to fit into Linux's page cache, but the underlying IO will still flush slowly to the disks for the tail end of it (where the tail is somewhat substantial).  

Please let me know if you need me to include more details.

**Comment by KungFuJesus** [comment]
Also same controller but different disk (Intel SSD) doesn't suffer from this issue with ext4, so that may help at least partially eliminate the hardware + drivers as a suspect.

**Comment by KungFuJesus** [comment]
So after chatting in #openzfs, a bandaid appears to be doing this:
echo 2 > /sys/module/zfs/parameters/zfs_vdev_async_write_min_active

This appears to keep the disk fed with enough IO to actually saturate the throughput.  For whatever reason ZoL is dropping to the minimum outstanding writes.

**Comment by DeHackEd** [comment]
So the issue is that rotation media write performance tends to tank when the number of outstanding IO requests is reduced to 1 when doing sequential operations. By the time the drive gets the "next" request from ZFS it has already rotated past the point where it can fulfill the new write and must wait for the sector to come around before trying again. Effectively you get 1 block written per rotation. Forcing a minimum of 2 writes queued keeps the drive busy.

**Comment by chrisrd** [comment]
FYI, for more info on the queuing strategy and tuneables, see [ZFS I/O Scheduler](https://github.com/zfsonlinux/zfs/blob/master/module/zfs/vdev_queue.c#L41) and in particular, the stuff starting at [Async Writes](https://github.com/zfsonlinux/zfs/blob/master/module/zfs/vdev_queue.c#L87)

**Comment by KungFuJesus** [comment]
I'm starting to wonder if this ZFS On Linux specific change has anything to do with my poor throughput issue...
https://github.com/zfsonlinux/zfs/commit/a58df6f53687ac6d1dee21f60de41b2552a43201

**Comment by behlendorf** [comment]
@KungFuJesus it shouldn't, but if you suspect it's causing a problem you can safely revert it for the purposes of testing.

**Comment by KungFuJesus** [comment]
The problem is it's a production machine at this point I can't really do it
on. I may look for more hardware to reproduce this.

**Comment by kpande** [comment]
@KungFuJesus i'm going to close this due to age, support requests are better off done via [IRC or the zfs-discuss mailing list](http://list.zfsonlinux.org)
