### ISSUE TITLE
config of a hot spare not currently in use or l2cache device will memory leak in add_config

### ISSUE THREAD

**Issue by liaoyuxiangqin** [zfsonlinux/zfs#4797]
Dear All,

when i reading ZFS on Linux code, I ran into a memory leak problem with add_config function. 
At the start of this function, when deal with a config which belongs to a hot spare not currently in use or level 2 cache device, we only add device to the list of names to translate, but we don't free the config whether process successful or not.

I think the memory of config will leak, and the related code in add_config as follows:

	/*
	 * If this is a hot spare not currently in use or level 2 cache
	 * device, add it to the list of names to translate, but don't do
	 * anything else.
	 */
	if (nvlist_lookup_uint64(config, ZPOOL_CONFIG_POOL_STATE,
	    &state) == 0 &&
	    (state == POOL_STATE_SPARE || state == POOL_STATE_L2CACHE) &&
	    nvlist_lookup_uint64(config, ZPOOL_CONFIG_GUID, &vdev_guid) == 0) {
		if ((ne = zfs_alloc(hdl, sizeof (name_entry_t))) == NULL)
			return (-1);

		if ((ne->ne_name = zfs_strdup(hdl, path)) == NULL) {
			free(ne);
			return (-1);
		}
		ne->ne_guid = vdev_guid;
		ne->ne_order = order;
		ne->ne_num_labels = num_labels;
		ne->ne_next = pl->names;
		pl->names = ne;
		return (0);
	}

In the above code, we don't have to free the config memory no matter process success or failure, and will lead to memory leak.

**Comment by heary-cao** [comment]
hello, liaoyuxiangqin

**Comment by behlendorf** [comment]
Addressed by:

e24e62a Fix memory leak in function add_config()
