### ISSUE TITLE
Large stack frame when compiled with -O0

### ISSUE THREAD

**Issue by DeHackEd** [zfsonlinux/zfs#4799]
<pre>cc1: warnings being treated as errors
../../module/zfs/vdev_raidz_math_scalar.c: In function ‘scalar_rec_pqr’:
../../module/zfs/vdev_raidz_math_scalar.c:215: error: the frame size of 1104 bytes is larger than 1024 bytes
</pre>

CentOS 6
Configured with: `CFLAGS='-O0 -g' ./configure --with-config=user --enable-debug`

Moving to `-O1` enables compiling.

Kinda a small concern. Do we care? I use `-O0` for debugging because optimizations make gdb difficult to use.

**Comment by ironMann** [comment]
@DeHackEd Could you try compiling with `-fcombine-stack-adjustments` added to CFLAGS

Problem here is that GCC does not report sane stack size for inlined methods in O0

**Comment by DeHackEd** [comment]
No such option under gcc 4.4.7 (centos 6)

**Comment by behlendorf** [comment]
Although option here would be to disable the warning for this function with a [diagnostic pragma](https://gcc.gnu.org/onlinedocs/gcc/Diagnostic-Pragmas.html).  Try this:

```
#pragma GCC diagnostic ignored "-Wframe-larger-than="
```

**Comment by ironMann** [comment]
Would it make sense to add new libtool convenient library for raidz implementations, always built with `-O2` or without stack frame check.

**Comment by behlendorf** [comment]
What would we gain by adding a convenience library?

**Comment by ironMann** [comment]
@behlendorf For one, we could remove `-Wframe-larger-than` selectively. Other thing is that SIMD code, both raidz and fletcher4, is not guarantied to work if user sets high opt level in `CFLAGS`, e.g. `-O3 -ftree-vectorize`. Too bad automake protects CFLAGS...

That said, everything can also be solved with pragma statements. For gcc, anyway

**Comment by behlendorf** [comment]
The only two compilers I'm aware of which can build the Linux kernel are gcc and clang.  Both appear to support diagnostic pragmas so for simplicity this would be my preference.

https://gcc.gnu.org/onlinedocs/gcc/Diagnostic-Pragmas.html
http://clang.llvm.org/docs/UsersManual.html#controlling-diagnostics-via-pragmas
