### ISSUE TITLE
use aggsum for arc stats

### ISSUE THREAD

**Issue by ahrens** [zfsonlinux/zfs#4808]
With a fix in place for https://github.com/zfsonlinux/zfs/issues/4807, I observed that although the wall clock time was dramatically improved, the CPU used increased by 30-200%.  Most of the CPU time was spent in `arc_space_return()`, updating the ARC statistics, specifically `arc_size`, `arcstat_*_size`, and `arcstat_meta_used`.  These are globals that are updated by `atomic_add_64()`, and the slowness is most likely due to cache line contention.

![image](https://cloud.githubusercontent.com/assets/799124/16363758/9b5648c8-3b89-11e6-84ec-42629988759d.png)

A fix for this would be to use an "aggregate sum" data structure for these statistics.  This data structure has one delta value per CPU, stored on separate cache lines.  Incrementing or decrementing the statistic only involves updating the running CPU's delta, thus avoiding cache line contention.  Reading the statistic require summing up each CPU's delta, but this is done rarely.  In terms of cost/reward, once the other bottlenecks are addressed, fixing this bug will provide a low-medium performance gain and require a low-medium amount of effort to implement.

Analysis sponsored by Intel Corp.

**Comment by behlendorf** [comment]
Resolved by OpenZFS 8484, 37fb3e4318.
