### ISSUE TITLE
Is primarycache=all suitable for read performance of database and consistent?

### ISSUE THREAD

**Issue by neoqguo** [zfsonlinux/zfs#4812]
We build PostgreSQL(PG) on zfs and disc is Fusion-io(high speed io card). Essenial args are set as follows, more in P.S.
ashift=12
recordsize=8k
primarycache=metadata
secondarycache=none
logbias=throughput

In testing, we catch the read performance bottleneck of database, espeically PG scans pages in sequence, only 4kB is fetched one time(= read bandwide/read count), and high utility in iostat, detail as follows:
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.13    0.00    1.21    3.13    0.00   95.53
Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00    12.00    0.00    5.00     0.00    68.00    27.20     0.00    0.00    0.00    0.00   0.00   0.00
fioa              0.00     0.00 8098.00    0.00 36204.00     0.00     8.94     0.83    0.10    0.10    0.00   0.10  82.80

We get the results as follows:
1. There is no data cached in primarycache, so every read action must fetch block from disc. PG page is 8k, and ashift 12 means 4k, so one 8k in PG would lead twice fetching from disc.
2. Maybe ashift=13 would slove this issue, while, we find that if ashift(8k) is the same as recordsize 8k, compression seems useless, and we need compression to save disc volume.
3. As ZIL is disabled(logbias=throughput), we believe write would fsync to disc, espeically xlog(WAL in PG).

Then, we try to adjust args as follows, after adjustment, one read could get more bytes and utility lower down
primarycache=all
secondarycache=all

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          17.38    0.00   23.30    0.04    0.00   59.28
Device:         rrqm/s   wrqm/s     r/s     w/s   rsec/s   wsec/s avgrq-sz avgqu-sz   await  svctm  %util
sda               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00   0.00   0.00
fioa             60.00     0.00 3447.00    0.00 502792.00     0.00   145.86     1.41    0.41   0.15  51.60

There are some confused points coming to us:
1. Primarycache caches data, and logbias(throughput) tells no zil, data in arc is one-copy on disc? they are consistent with each other?
2. If zfs could still keep in consistent when system is down unexpected?

Looking forward to your advice, thx~

neoqguo

[z_conf.txt](https://github.com/zfsonlinux/zfs/files/336937/z_conf.txt)

**Comment by DeHackEd** [comment]
This is an issue tracker, please use the mailing list for questions like this.
