### ISSUE TITLE
system freezes running off ZFS; kernel 4.5.7, Celeron N3150 and Seagate SSHD

### ISSUE THREAD

**Issue by RJVB** [zfsonlinux/zfs#4823]
I am getting too regular system lock-ups when running off my ZFS root (/boot is on ext4), about once every other day. I don't get any useful information in my system logs, possibly because it can no longer be written.

This seems to happen during relatively intensive I/O, like compilation but the other day it happened when I was doing a zfs send/receive to a pool on an external USB disk. I've yet to see this kind of freeze happen when I boot off an almost identical install on a btrfs root connected over USB3. It's just not identical enough in terms of settings that I can exclude that some setting is responsible for my issue, and I haven't yet found a reproducible way to trigger the freeze.

I know the i915 support for my hardware is still evolving but while the freezes do seem to happen more easily when running a command that does verbose terminal I/O they also happen when there's no video activity at all (as in nothing changes on the screen). More importantly, all GPU/IGP issues I've had left the machine responsive over SSH at least.

Some details:
- Linux kernel 4.5.7 with the ConKolivas patches (but I also get the freezes without them)
- ZFS 0.6.5.7-1~trusty
- Intel Celeron N3150 ("braswell") with "Cherryview" graphics
- Seagate Laptop SSHD (ST500LM000-1EJ162), a hybrid HDD with a couple of Gb of SSD cache
- 8Gb RAM
- overcommit off (/proc/sys/vm/overcommit_ratio=80, overcommit_memory=2) (freezes occur with the default settings too).

Whatever causes these lock-ups it appears that it's never yet happened during a crucial ZFS transaction/operation; the pool remains error-free. (I scrubbed it yesterday evening, booted off the btrfs external just to be sure)

I've seen comparable lock-ups during very intensive compiles (Qt5...) on much slower and MUCH more stable hardware when I had sync off on the dataset that held the build directory. I think those were due to some sort of memory contention issue; since then I basically only have sync=off on the dataset that holds /tmp .

Any thoughts would be appreciated. I'm of course not sure if ZFS is at cause, I just have a hunch it is.

**Comment by RJVB** [comment]
Re: absent info in the logs. Supposing that's indeed because of a race condition, what should I expect with the following approach:

- boot off the btrfs external
- mount the internal root pool to a sub prefix
- chroot into that prefix the way one would to run updates, redo the grub config etc.:
```
> mount -bind /dev /mnt/dev
> mount -bind /proc /mnt/proc
> # etc
> chroot /mnt mount -av
> chroot /mnt $SHELL -l
> exec su - myself
> startx | xinit startkde
```

That should give me my regular login session/environment, but I'd hope that all system messages still go to the logs on the real root, right?

**Comment by RJVB** [comment]
FWIW: 
```
> cat /sys/block/sda2/queue/scheduler
noop deadline [cfq]
```

is that reasonable, knowing that the pool sits in a (GPT) partition?

**Comment by kpande** [comment]
use **noop** scheduler; closing due to age

**Comment by RJVB** [comment]
Sorry, completely forgot about this. If memory serves me well the freeze I used to have on this system were in fact due to the thermald. Once I kicked that off it's mostly been a happy little slowbook :)

**Comment by kpande** [comment]
haha, thanks for the closure!
