### ISSUE TITLE
`zpool export` does not delete the mountpoint on pools with local mountpoint property

### ISSUE THREAD

**Issue by mailinglists35** [zfsonlinux/zfs#4824]
````
root@linux:~# stat /deleteme
stat: cannot stat ‘/deleteme’: No such file or directory
root@linux:~# zpool create  deleteme /dev/loop0
root@linux:~# stat /deleteme
  File: ‘/deleteme’
  Size: 2               Blocks: 1          IO Block: 512    directory
Device: 23h/35d Inode: 4           Links: 2
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-06-30 18:55:28.283454235 +0300
Modify: 2016-06-30 18:55:28.283454235 +0300
Change: 2016-06-30 18:55:28.283454235 +0300
 Birth: -
root@linux:~# zpool export deleteme
root@linux:~# stat /deleteme
stat: cannot stat ‘/deleteme’: No such file or directory

root@linux:~# stat /srv/deleteme
stat: cannot stat ‘/srv/deleteme’: No such file or directory
root@linux:~# zpool create -m /srv/deleteme deleteme /dev/loop0
root@linux:~# zpool export deleteme
root@linux:~# stat /srv/deleteme
  File: ‘/srv/deleteme’
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: 803h/2051d      Inode: 1351725     Links: 2
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-06-30 18:50:03.439797844 +0300
Modify: 2016-06-30 18:50:03.439797844 +0300
Change: 2016-06-30 18:50:03.439797844 +0300
 Birth: -
root@linux:~#
````

expectation: delete the mountpoint after export, like the case for pools without defined mountpoints

**Comment by loli10K** [comment]
> expectation: delete the mountpoint after export, like the case for pools without defined mountpoints

But why?

I don't think there's a bug here, seems to be working as intended:

```c
  1074  /*
  1075   * Remove the mountpoint associated with the current dataset, if necessary.
  1076   * We only remove the underlying directory if:
  1077   *
  1078   *      - The mountpoint is not 'none' or 'legacy'
  1079   *      - The mountpoint is non-empty
  1080   *      - The mountpoint is the default or inherited
  1081   *      - The 'zoned' property is set, or we're in a local zone
  1082   *
  1083   * Any other directories we leave alone.
  1084   */
  1085  void
  1086  remove_mountpoint(zfs_handle_t *zhp)
```

**Comment by mailinglists35** [comment]
working as intended != working as expected

**Comment by loli10K** [comment]
> working as intended != working as expected

It's working as the original developers intended, so it's not a bug. Is this a feature request?

> expectation: delete the mountpoint after export, like the case for pools without defined mountpoints


You still haven't answered my question, i'll ask again: why do you expect zfs to delete the mountpoint after export? I'm not thrilled by the idea of zfs trying to `rmdir` "/var/log".

**Comment by mailinglists35** [comment]
> It's working as the original developers intended, so it's not a bug. Is this a feature request?

it's neither a bug nor a feature request. it's a design rethinking request. IMO the original developers designed this behaviour wrong.

> why do you expect zfs to delete the mountpoint after export?

I expect **consistent behaviour**: you either CREATE and DELETE the mountpoint ALL THE TIME - or exclusively - you DO NOT TOUCH THE MOUNTPOINT AT ANY TIME.
the current behaviour is inconsistent, it's picky when to create+delete and when not. 
I DON'T WANT TO MEMORIZE in what case it's doing it by itself and in what cases it's the admin responsibility to create and delete, because it's logicless to sometimes do and sometimes don't.

> I'm not thrilled by the idea of zfs trying to rmdir "/var/log"

Agree but only as long as `/var/log` was NOT created by `zpool import` or `zfs mount`.
If `/var/log` did not exist before `zpool import/zfs mount`, I expect one of these:
- fail
- create it then delete it at `zpool export` or `zfs umount` time.

currently `zpool export` creates mountpoints but does not delete them. this is definitely something I do not want nor do I expect.

**Comment by mailinglists35** [comment]
why is this closed? the design still exhibits inconsistent behaviour:

with defaults:
it creates directory on create/import
it deletes directory on export

with import -R /path for default-created pool
it creates directory on create/import
it deletes directory on export

with create -m /path
it creates directory on import/create
it does **not** delete directory on export
(actually if you have a tree of nested datasets, after export the **entire tree** remains not deleted, not just the top level dataset)

other than "because it was written this way by the original zfs authors", can someone show an actual valid argument for why is it the way it is, and why the way it is is the right way?

**Comment by GregorKopka** [comment]
At least we have an error in the code comments,
I'm quite sure that we don't want to remove a **non-empty** mountpoint.

https://github.com/zfsonlinux/zfs/blob/900d09b285107e13fa0bdb8378274dff89347181/lib/libzfs/libzfs_mount.c#L1123-L1126

**Comment by mailinglists35** [comment]
but in the case I described (reproductible, try for yourself) the directory **is** empty, yet remains not deleted!

**Comment by RJVB** [comment]
That's just how it works, just like I presume most of us don't delete temporary mountpoints we created once.

Changing this behaviour as a new default zpool is bound to break scripts that rely on the fact that ZFS mountpoints are NOT deleted on export.

Check zed, if it doesn't already provide an event for pool export (or rather, zfs unmount) a feature request to add such an event will stand a better chance, I think.

**Comment by mailinglists35** [comment]
>That's just how it works
No I won't accept that as an argument. If that's how it works, it works **wrong**.

If the local property of the top level dataset "mountpoint" does not exist at import time, it has to either:
A. refuse import (just like mount calls for regular filesystems bail out on unexistent mount point)
B. create the mountpoint at import and delete the mountpoint at export.

>break scripts that rely on the fact that ZFS mountpoints are NOT deleted on export.
I don't buy this either. What is the practical use of a leftover that remains on a non-default setting? Remember that on default setup, the directory created at import is deleted at export.

**Comment by RJVB** [comment]
> I don't buy this either.

You don't have to, but whether or not you do is perfectly irrelevant I fear. ZFS has been designed and used by people who know pretty damn well what they're doing - and the chance that there are NOT more of them who'd need to adapt their habits to the consistency gripes of a single user (apparently a newcomer at that) is not just small.

>Remember that on default setup, the directory created at import is deleted at export. 

What 's "default setup" here? When no alternate mountpoint is used? Let's take the example of one of my scratch pools, imported with `zpool import ni64` so using its configured defaults

```
> zfs list | fgrep nif64
nif64                                         4.20G  52.0G  3.94G  /Volumes/nif64
nif64/MacPorts                                 255M  52.0G    88K  none
nif64/MacPorts/MacFork-git                     254M  52.0G   254M  /opt/local/var/macports/sources/macfork-ports
nif64/bla bla                                  100K  52.0G   100K  /Volumes/nif64/bla bla
```

This is on Linux, despite the use of /Volumes.

```
> zpool export nif64
> ll -d /Volumes/nif64/ /opt/local/var/macports/sources/macfork-ports
 592751 1 drwxr-xr-x 2 root root 2 Jan  9 14:42 /opt/local/var/macports/sources/macfork-ports/
1278894 1 drwxr-xr-x 2 root root 2 Jan  9 14:42 /Volumes/nif64//
> sudo rm -rf /Volumes/nif64/ /opt/local/var/macports/sources/macfork-ports
> zpool import nif64
>ll -d /Volumes/nif64/ /opt/local/var/macports/sources/macfork-ports /Volumes/nif64/bla\ bla
 4 9 drwxr-xr-x 57 bertin   80 64 Jan  7 16:32 /opt/local/var/macports/sources/macfork-ports/
 4 9 drwxr-xr-x  7 bertin root  8 Dec 30 14:51 /Volumes/nif64//
34 1 drwxr-xr-x  2 bertin root  3 Dec 26 22:27 /Volumes/nif64/bla bla/
> zpool export nif64
ll -d /Volumes/nif64/ /opt/local/var/macports/sources/macfork-ports /Volumes/nif64/bla\ bla
ls: cannot access /Volumes/nif64/bla bla: No such file or directory
 591978 1 drwxr-xr-x 2 root root 2 Jan  9 14:47 /opt/local/var/macports/sources/macfork-ports/
1279025 1 drwxr-xr-x 2 root root 2 Jan  9 14:47 /Volumes/nif64//
```

So, the only directory which was deleted in "/Volumes/nif64/bla bla" but that's logical: it exists on the dataset that was mounted on /Volumes/nif64, not on the filesystem that holds the nif64 mountpoint.

If those are the directories you claim are deleted on export with the "default setup", then it's your reasoning which is wrong, not the design.

If by default setup you mean that the mountpoint property is left to its default value (not the case in my example pool) then your reasoning is probably still flawed. IIRC, the default mountpoint for a pool's first dataset  is '/' ... and it doesn't even make sense to delete that on export (probably the reason too why the boot pool isn't exported on restart or shutdown).

I'm not going to do down this rabbithole any further, as I said I agree with the others that the current behaviour is not exactly wrong and doesn't require changing beyond possibly an option that provides some kind of cleanup without introducing incompatibilities with other ZFS versions and implementations.

If you can't buy that either, I guess there's always BetterFS O:-)

**Comment by GregorKopka** [comment]
mountpoint gets created **and** removed when using default mountpoint:
```
office test $ ls -al | grep mount
office test $ zfs create test/mount
office test $ ls -al | grep mount
drwxr-xr-x  2 root   root               2 Jan  9 15:19 mount
office test $ zfs destroy test/mount
office test $ ls -al | grep mount
```
mountpoint gets created **but not** removed when using an explicit (local) mountpoint:
```
office test $ ls -al | grep mount
office test $ zfs create test/mount -o mountpoint=/test/mount
office test $ ls -al | grep mount
drwxr-xr-x  2 root   root               2 Jan  9 15:20 mount
office test $ zfs destroy test/mount
office test $ ls -al | grep mount
drwxr-xr-x  2 root   root               2 Jan  9 15:20 mount
```

I find this _at least_ surprising, while at the same time lacking a good reason for that behaviour.
IMHO this inconsistency dosn't make much sense, but who am I to know... 
Maybe @ahrens could shed a little light on this?

**Comment by RJVB** [comment]
> mountpoint gets created **and** removed when using default mountpoint:
> mountpoint gets created **but not** removed when using an explicit (local) mountpoint:

The "bla bla" dataset in my example is a default mountpoint, though inherited from a local property (but that shouldn't make a difference?!)

What happens when you revert the mountpoint property to 'inherited' (I think that's possible)?


> I find this _at least_ surprising

I can agree more with that since here we're talking about dataset destruction.
