### ISSUE TITLE
Change a fix amount of disks which scrubs/replaces to a percentage IO-value

### ISSUE THREAD

**Issue by RubenKelevra** [zfsonlinux/zfs#4826]
The default values of `zfs_vdev_scrub_min_active` and `zfs_vdev_scrub_max_active` slows down an zfs replace more than necessary on larger arrays. 

A change from a "how many disks should scrub / replace at once" to "how many percentage IO should be minimal / maximal given to this work" is much more consistently on different poolsizes.

**Comment by behlendorf** [comment]
@RubenKelevra can you share any performance data for your various pool configurations.

**Comment by behlendorf** [comment]
Closing.  There's nothing actionable here.  If someone has the time to develop a reasonable heuristic to automatically tune this we can look in to adopting it.
