### ISSUE TITLE
Please add link to "Getting Started" wiki page for zol on voidlinux

### ISSUE THREAD

**Issue by gotwf** [zfsonlinux/zfs#4841]
Voidlinux is an up and coming distro based on runit that supports both glibc and musl.  I've written a zol on Voidlinux installation guide here:

http://www.teamcool.net/posts/zol-voidlinux.html

that would be nice to add to the "Getting Started" wiki 

https://github.com/zfsonlinux/zfs/wiki/Getting-Started

Would someone with "Collaborator" rights please add a link to it?

Thanks bunches.

**Comment by rlaager** [comment]
I'm not "in charge" here, so take this with a grain of salt... I'd rather see this reformatted as a wiki page than a blog post. I think that would be more maintainable over the long term.

As a separate issue, I'd personally prefer a neutral and professional tone. At a minimum, certain language should be removed.

**Comment by behlendorf** [comment]
I tend to agree.  I'm happy to add documentation for Voidlinux but lets keep it professional.  I see there are already some rough notes on the Voidlinux wiki.  It would be ideal if those could be updated then we can link to it. 

https://wiki.voidlinux.eu/Manual_install_with_ZFS_root
