### ISSUE TITLE
l2arc_feed kernel thread keeps waking up the cpu on idle system

### ISSUE THREAD

**Issue by mailinglists35** [zfsonlinux/zfs#4844]
pool is idle, no scrub no silver no reads no writes no scsi/samba/nfs shares

root@linux:~# perf record -g -a -p $(pidof l2arc_feed) -e cycles sleep 30
Warning:
PID/TID switch overriding SYSTEM[ perf record: Woken up 1 times to write data ]
[ perf record: Captured and wrote 0.021 MB perf.data (65 samples) ]

```
Samples: 65  of event 'cycles', Event count (approx.): 42897125
  Children      Self  Command     Shared Object      Symbol
+   33.63%    33.63%  l2arc_feed  [kernel.kallsyms]  [k] _raw_spin_lock
+   22.33%    22.33%  l2arc_feed  [kernel.kallsyms]  [k] l2arc_feed_thread
+   17.69%    17.69%  l2arc_feed  [kernel.kallsyms]  [k] mutex_trylock
+   17.44%    17.44%  l2arc_feed  [kernel.kallsyms]  [k] multilist_sublist_next
+    8.77%     8.77%  l2arc_feed  [kernel.kallsyms]  [k] mutex_unlock
     0.09%     0.09%  l2arc_feed  [kernel.kallsyms]  [k] native_write_msr_safe
     0.05%     0.05%  l2arc_feed  [kernel.kallsyms]  [k] irq_work_interrupt

  pool: homebackup
 state: ONLINE
  scan: scrub repaired 0 in 15h1m with 0 errors on Fri Jul  1 16:01:12 2016
config:

    NAME                                                  STATE     READ WRITE CKSUM
    homebackup                                            ONLINE       0     0     0
      mirror-0                                            ONLINE       0     0     0
        sdc                                               ONLINE       0     0     0
        sdb                                               ONLINE       0     0     0
    logs
      ata-Corsair_CSSD-F60GB2_1042843425062945863-part5  ONLINE       0     0     0
    cache
      ata-Corsair_CSSD-F60GB2_1042843425062945863-part6  ONLINE       0     0     0

errors: No known data errors

root@linux:~# zpool iostat 30
               capacity     operations    bandwidth
pool        alloc   free   read  write   read  write
----------  -----  -----  -----  -----  -----  -----
homebackup   871G  57.4G      1      0  3.07K    737 #this one read only happens at zpool iostat launch
homebackup   871G  57.4G      0      0      0      0
homebackup   871G  57.4G      0      0      0      0
homebackup   871G  57.4G      0      0      0      0
```

**Comment by ironMann** [comment]
So, the thread used 43Mill CPU cycles over 30sec. It doesn't look too problematic, but frequent interrupts can prevent CPU from entering low power states. 
Can you share result of `powertop --csv` ?

**Comment by mailinglists35** [comment]
root@homerouter:~# powertop --csv
Loaded 0 prior measurements
Cannot load from file /var/cache/powertop/saved_parameters.powertop
File will be loaded after taking minimum number of measurement(s) with battery only
RAPL device for cpu 0
RAPL device for cpu 0
RAPL device for cpu 0
Devfreq not enabled
Cannot load from file /var/cache/powertop/saved_parameters.powertop
File will be loaded after taking minimum number of measurement(s) with battery only
Preparing to take measurements
  unknown op '{'
Taking 1 measurement(s) for a duration of 20 second(s) each.
PowerTOP outputing using base filename powertop.csv

[powertop.csv.txt](https://github.com/zfsonlinux/zfs/files/360150/powertop.csv.txt)

**Comment by ironMann** [comment]
So these results fit well with the `perf` ones:
```
Usage;Wakeups/s;GPU ops/s;Disk IO/s;GFX Wakeups/s;Category;Description
0.7 ms/s; 0.15;;;;Process;[l2arc_feed]
```
While it does show a bit longer processing in this thread, 700us/s, the wakeup frequency isn't high enough to keep CPUs awake. Typically, you want watch for things with more than 4 Wakeups/s. Report also shows that CPU spends ~98% percent of time in lowest power state C2.
