### ISSUE TITLE
Kernel panic

### ISSUE THREAD

**Issue by standula** [zfsonlinux/zfs#4857]
[kern.txt](https://github.com/zfsonlinux/zfs/files/367719/kern.txt)
Hi, i have kernel panic on server debian jessie repetly in few days.
I send kernel log

**Comment by kernelOfTruth** [comment]
@standula for ease of overview

please post Hardware configuration (ECC ?, board, processor, etc.)

and ZFS setup information (harddrive array, etc.)


Also what were you doing, or are you (your server) doing while this is happening ?

Thanks

**Comment by standula** [comment]
Thanks for answer: 
Server: https://www.asus.com/Commercial-Servers-Workstations/RS162E4RX4/

HW Con H/W path        Device      Class      Description
==================================================
                            system     Computer
/0                          bus        Motherboard
/0/1                        memory     5984MiB System memory
/0/3                        processor  Intel(R) Xeon(R) CPU           E5450  @ 3.00GHz
/0/0                        bridge     6702PXH PCI Express-to-PCI Bridge A
/0/0/3          scsi6       storage    SAS1068 PCI-X Fusion-MPT SAS
/0/0/3/0.0.0                disk       SCSI Disk
/0/0/3/0.1.0                disk       SCSI Disk
/0/0/3/0.2.0    /dev/sda    disk       2TB ST2000VX000-1ES1
/0/0/3/0.2.0/1  /dev/sda1   volume     1863GiB OS X ZFS partition or Solaris /usr partition
/0/0/3/0.2.0/9  /dev/sda9   volume     8191KiB reserved partition
/0/0/3/0.3.0    /dev/sdb    disk       2TB ST2000VX000-1ES1
/0/0/3/0.3.0/1  /dev/sdb1   volume     1863GiB OS X ZFS partition or Solaris /usr partition
/0/0/3/0.3.0/9  /dev/sdb9   volume     8191KiB reserved partition
/0/0/3/1.0.0    /dev/sdc    disk       145GB Logical Volume
/0/0/3/1.0.0/1  /dev/sdc1   volume     46GiB Linux filesystem partition
/0/0/3/1.0.0/2  /dev/sdc2   volume     4766MiB Linux filesystem partition
/0/0/3/1.0.0/3  /dev/sdc3   volume     32GiB Linux filesystem partition
/0/0.1                      generic    6700/6702PXH I/OxAPIC Interrupt Controller A
/0/2                        display    ES1000
/0/100                      bridge     5000P Chipset Memory Controller Hub
/0/100/2                    bridge     5000 Series Chipset PCI Express x4 Port 2
/0/100/2/0                  bridge     6311ESB/6321ESB PCI Express Upstream Port
/0/100/2/0/0                bridge     6311ESB/6321ESB PCI Express Downstream Port E1
/0/100/2/0/1                bridge     6311ESB/6321ESB PCI Express Downstream Port E2
/0/100/2/0/2                bridge     6311ESB/6321ESB PCI Express Downstream Port E3
/0/100/2/0.3                bridge     6311ESB/6321ESB PCI Express to PCI-X Bridge
/0/100/3                    bridge     5000 Series Chipset PCI Express x4 Port 3
/0/100/3/0      eth0        network    80003ES2LAN Gigabit Ethernet Controller (Copper)
/0/100/3/0.1    eth1        network    80003ES2LAN Gigabit Ethernet Controller (Copper)
/0/100/4                    bridge     5000 Series Chipset PCI Express x8 Port 4-5
/0/100/5                    bridge     5000 Series Chipset PCI Express x4 Port 5
/0/100/6                    bridge     5000 Series Chipset PCI Express x8 Port 6-7
/0/100/7                    bridge     5000 Series Chipset PCI Express x4 Port 7
/0/100/8                    generic    5000 Series Chipset DMA Engine
/0/100/1c                   bridge     631xESB/632xESB/3100 Chipset PCI Express Root Port 1
/0/100/1d                   bus        631xESB/632xESB/3100 Chipset UHCI USB Controller #1
/0/100/1d.1                 bus        631xESB/632xESB/3100 Chipset UHCI USB Controller #2
/0/100/1d.2                 bus        631xESB/632xESB/3100 Chipset UHCI USB Controller #3
/0/100/1d.3                 bus        631xESB/632xESB/3100 Chipset UHCI USB Controller #4
/0/100/1d.7                 bus        631xESB/632xESB/3100 Chipset EHCI USB2 Controller
/0/100/1e                   bridge     82801 PCI Bridge
/0/100/1f                   bridge     631xESB/632xESB/3100 Chipset LPC Interface Controller
/0/100/1f.2                 storage    631xESB/632xESB SATA RAID Controller
/0/100/1f.3                 bus        631xESB/632xESB/3100 Chipset SMBus Controller
/0/101                      bridge     5000 Series Chipset FSB Registers
/0/102                      bridge     5000 Series Chipset FSB Registers
/0/103                      bridge     5000 Series Chipset FSB Registers
/0/104                      bridge     5000 Series Chipset Reserved Registers
/0/105                      bridge     5000 Series Chipset Reserved Registers
/0/106                      bridge     5000 Series Chipset FBD Registers
/0/107                      bridge     5000 Series Chipset FBD Registers
/1              vethEAWXXH  network    Ethernet interface
/2              veth3WNCW2  network    Ethernet interface
/3              vethYBUQLC  network    Ethernet interface
/4              veth47K67T  network    Ethernet interface
/5              vethK4F6PL  network    Ethernet interface


zpool config : 
  pool: data_pool
 state: ONLINE
  scan: scrub repaired 0 in 0h59m with 0 errors on Tue Apr 19 07:13:42 2016
config:

        NAME                                            STATE     READ WRITE CKSUM
        data_pool                                       ONLINE       0     0     0
          mirror-0                                      ONLINE       0     0     0
            sda                                         ONLINE       0     0     0
            sdb                                         ONLINE       0     0     0
        logs
          sdc2                                          ONLINE       0     0     0
        cache
          wwn-0x600508e000000000e2b157132445de0b-part3  ONLINE       0     0     0

sdc is hardware raid 
sda, sdb are sata disks in zfs mirror
It occurs in common work process.

**Comment by kernelOfTruth** [comment]
data heavy ? metadata heavy ?

**Comment by standula** [comment]
Can you please explain what do you mean exactly?

**Comment by kernelOfTruth** [comment]
you wrote

>It occurs in common work process.

could you clarify how it is used ?

e.g. if there are VMs,

databases; webserver, dataserver, 

https://en.wikipedia.org/wiki/Server_(computing)#Purpose

the goal is either to reproduce that panic or to understand how it can happen

Thanks

**Comment by standula** [comment]
Yes of course, 

i attach zfs list. 
I have some lxc containers with ZFS backend, BIND, Apache, PosgreSQL, MySQL, Proftpd, Postfix, Dovecot.
I guess it is planned task which makes kernel panic. In 99% server lost response on Sunday at 6 30  - 8 00
data_pool                                  271G  1,49T    19K  /data_pool
data_pool/backups                         77,2G  1,49T  77,2G  /data_pool/backups
data_pool/home                             785M  1,49T   785M  /home
data_pool/lxc                             2,02G  1,49T    19K  /data_pool/lxc
data_pool/lxc/containers                  2,02G  1,49T  49,5K  /data_pool/lxc/containers
data_pool/lxc/containers/grafana           391M  1,49T   391M  /data_pool/lxc/containers/grafana/rootfs
data_pool/lxc/containers/monitoring        305M  1,49T   305M  /data_pool/lxc/containers/monitoring/rootfs
data_pool/servers                          189G  1,49T    20K  /srv
data_pool/servers/ftp                     79,6G  1,49T  79,6G  /srv/ftp
data_pool/servers/mail                    64,3G  1,49T  64,3G  /srv/mail
data_pool/servers/mysql                   3,08G  1,49T  3,08G  /srv/mysql
data_pool/servers/postgresql               174M  1,49T   174M  /srv/postgresql
data_pool/servers/www                     41,4G  1,49T  41,4G  /srv/www
data_pool/swap                            2,06G  1,49T  1,59G  -
data_pool/tests                             19K  1,49T    19K  /data_pool/tests

Thanks

**Comment by akkyoh** [comment]
Hello. 

Please make sure there is no problem if at the time of check mdadm (softwre raid)? cat /proc/mdstat
I have such errors, they also appear on the weekends when there is a check disk array.

**Comment by standula** [comment]
Hi, 
i don`t use mdadm. I have hw raid on system ( 2 disk in raid 1 with reiserfs) + data on zfs .
