### ISSUE TITLE
aarch64 or noarch repo for yum/Fedora package

### ISSUE THREAD

**Issue by richardhenwood** [zfsonlinux/zfs#4871]
Hi,

I'm running Fedora 24 on a RPI3, in AArch64 execution state. I used the Fedora 23 noarch repo rpm from [1]. This rpm installed the zfs.repo file. This file has a baseurl like:
http://archive.zfsonlinux.org/fedora-testing/$releasever/$basearch/

It seems there isn't a link for $basearch=AArch64. After substituiting x86_64 for $basearch, spl- and zfs-dkms packages are available. I've built and installed from the spl and zfs dkms packages and now have a zfs filesystem mounted and apprently happy.

For AArch64 users I think there could a be a small change made to the repos to enhance the experience:
 + An 'aarch64' link could be created so $basearch resolves.
 + The repo could have the dkms broken out in a separate no arch repo.

Or, I guess there could be a noarch repo, and $basearch could be omitted completely from the baseurl?

Or, there is an even better way?

1. https://github.com/zfsonlinux/zfs/wiki/Fedora

**Comment by behlendorf** [comment]
To properly support aarch64 we'd need to do a little more work.  You're absolutely right that the dkms packages from noarch will build properly for aarch64 and work.  However, that only covers the kernel side of things.  The x86_64 directory of the repository contains the user space binaries built for x86_64.  For this to work we'd need to build aarch64 binaries as well and right now we haven't automated that process.

**Comment by richardhenwood** [comment]
Ah - I see!
Thanks for taking the time to explain - and let me know if I can be of any assistance.

**Comment by behlendorf** [comment]
Closing.  Binary packages won't be provided for non-x86_64 platforms for Fedora or EPEL.  If someone from the Fedora community would like to volenteer to maintain the ZFS packages for additional architectures please let me know.
