### ISSUE TITLE
zpool has mirror numbers with a gap?

### ISSUE THREAD

**Issue by dswartz** [zfsonlinux/zfs#4875]
8 drives in a 4x2 raid10.  'zpool status' shows mirror-0 through mirror-3.  Added two more drives, and vdev showed as mirror-4 (as expected).  Added two more drives, and that shows as mirror-6?  As below:

        NAME                            STATE     READ WRITE CKSUM
        tank                            ONLINE       0     0     0
          mirror-0                      ONLINE       0     0     0
            wwn-0x5000c5005621857b      ONLINE       0     0     0
            wwn-0x5000c500412ef8b3      ONLINE       0     0     0
          mirror-1                      ONLINE       0     0     0
            wwn-0x5000c50041ab0c47      ONLINE       0     0     0
            wwn-0x5000c500412ee41f      ONLINE       0     0     0
          mirror-2                      ONLINE       0     0     0
            wwn-0x5000c500575e15b7      ONLINE       0     0     0
            wwn-0x5000c500426c6f73      ONLINE       0     0     0
          mirror-3                      ONLINE       0     0     0
            wwn-0x5000c500575759fb      ONLINE       0     0     0
            wwn-0x5000c50056ed546f      ONLINE       0     0     0
          mirror-4                      ONLINE       0     0     0
            wwn-0x5000c50041bd3e87      ONLINE       0     0     0
            wwn-0x5000c50057575fe3      ONLINE       0     0     0
          mirror-6                      ONLINE       0     0     0
            wwn-0x5000c50055e99cdf      ONLINE       0     0     0
            wwn-0x5000c50055e9a7a3      ONLINE       0     0     0
        logs
          wwn-0x5000a7203007d0e1-part1  ONLINE       0     0     0

**Comment by richardelling** [comment]
The instance number is meaningless. You can ignore it. In fact, if you expect it to be consistent, then you may be disappointed.

**Comment by dswartz** [comment]
Good to know, thanks.  I will close this.  I've literally never seen a newly added vdev skip a number this way...
