### ISSUE TITLE
Write (through/back) cache

### ISSUE THREAD

**Issue by antst** [zfsonlinux/zfs#4879]
As far as I know, there is some work has been done in nexenta on write-caching on special vdev (read SSD). To make it clear, it is not about ZIL, which is not write cache.

I briefly looked into nexenta sources, there is something about write caching (feature@wrcache and option wrc_mode).

They also had a talk about this feature last summer.

Does someone know what is the current status of the story and when can we expect this feature available in ZOL?

For me it looks like critical component,mad ZIL + L2ARC doesn't implement real tired storage, while addition of WRC does.

Currently, if you need to write 20GB, zil and l2arc will not help you, while (for example) having 1TB fast PCIe SSD in front of 40TB HDD storage, can make your life way better in many cases.

Anton.

**Comment by rlaager** [comment]
I haven't heard anything, and I'm not sure there's any reason to keep this issue open in ZoL.
