### ISSUE TITLE
Implicit declaration of function 'highbit'

### ISSUE THREAD

**Issue by OrdinaryMagician** [zfsonlinux/zfs#4881]
On `module/icp/os/modhash.c`, line 315. Just got the error moments ago trying to build from latest git master.

I'm on a 4.6.4 kernel, if it's of any relevance to the problem.

**Comment by kernelOfTruth** [comment]
please also post the exact gcc version

```
gcc -v
```

Thanks !

**Comment by OrdinaryMagician** [comment]
All of the output?
`Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc-multilib/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release
Thread model: posix
gcc version 6.1.1 20160707 (GCC)`

**Comment by tonyhutter** [comment]
Is your SPL up to date?

```
commit d2f97b2a2651d8e1a6e9e1dcb07cfe8570efcfff
Author: Tom Caputi <tcaputi@datto.com>
Date:   Thu Jul 14 15:51:24 2016 -0400

    Added highbit() and lowbit() macros
    
    Signed-off-by: Tom Caputi <tcaputi@datto.com>
    Signed-off-by: Tony Hutter <hutter2@llnl.gov>
    Signed-off-by: Brian Behlendorf <behlendorf1@llnl.gov>
    Closes #562
```

**Comment by OrdinaryMagician** [comment]
Oh, it's probably that. I updated them in the wrong order.

**Comment by vozhyk-** [comment]
Updating `spl` fixed this for me.

@OrdinaryMagician did it for you? In that case, can you close the issue?

**Comment by OrdinaryMagician** [comment]
Oh, I have to close it myself? oops.
