### ISSUE TITLE
dereference on null pointer when fclosing hdl->libzfs_mnttab

### ISSUE THREAD

**Issue by ColinIanKing** [zfsonlinux/zfs#4902]
libzfs_util.c, libzfs_init()

Currently there is no file open failure check when opening
/etc/dfs/sharetab.  The NULL hdl->libzfs_sharelib file pointer
will lead to a null pointer deference when this is closed, for
example, in the case where libzfs_core_init() fails and the
subsequent cleanup closes hdl->libzfs_sharelib.

I'll send a patch to fix this issue shortly.

**Comment by behlendorf** [comment]
It's probably better to remove this entirely from libzfs_init() / libzfs_close(). It's only used in It's only ever used in is_shared() and it would be better to just handle the open/close there.

**Comment by behlendorf** [comment]
Resolved by 2bac68145f94012d6e41dffb9f4a7faf80a8e107.
