### ISSUE TITLE
corrupted zvol data after zfs incremental send

### ISSUE THREAD

**Issue by davidbruzos** [zfsonlinux/zfs#4904]
I'm moving a 1TB zvol from one data center to another using ZFS incremental streams to minimize application down time during the switch-over.  Basically, I send an initial stream and then, I send an incremental once the VM in the origin location is powered off.  Then, I start the VM in the remote data center.  The zvol was created using "zfs create -b 4k -s -V 1t tank/vms/disk" and it is the backing device for a DRBD resource.

During a test run, I noticed that a sha256 checksum of the files in the NTFS volume fail on the target/remote site.  The checksums of the initial stream check-out fine, but once the incremental was applied, multiple files on the target did not checksum correctly.  I use this functionality from time to time and it is very useful, but I'm not sure that I can risk silent data corruption.  A pool scrub on the target system does not find anything and no errors are reported anywhere (dmesg, zfs, etc).

I've used this functionality in the past and I never noticed an issue.  That was with versions <=0.6.5.3 though.

I removed the original zvol and tried again (using the same exact commands) and all checksums check-out correctly for a while, but as more increments are sent, problems begin to show up again.

I've seen some open bugs regarding streams and corruption, but I did not see anything specific to zvols.  I guess it may not matter, since the data is stored in the zpool anyway, but I'm not sure about that.

Both servers are Xen hypervisors and have ECC RAM and work great (as far as I can tell).  The host OS is Gentoo Linux with Xen 4.6 and kernel 4.4.6 with ZFS 0.6.5.7.

The zvols are used as DRBD backing storage and the virtual machine guest is running Windows Server 2012R2 and Exchange 2013.  I've seen the corruption show-up on multiple of the Exchange mailbox databases and in the transaction logs as well.

**Comment by kernelOfTruth** [comment]
referencing: https://github.com/zfsonlinux/zfs/issues/4809 Silently corrupted file in snapshots after send/receive

https://github.com/zfsonlinux/zfs/issues/4530 Data Corruption During ZFS send/receieve
