### ISSUE TITLE
Centos 7 - Unable to Switching from DKMS to kABI-tracking kmod, FATAL: Module zfs not found

### ISSUE THREAD

**Issue by ungrown** [zfsonlinux/zfs#4911]
I followed that [wiki](https://github.com/zfsonlinux/zfs/wiki/RHEL-%26-CentOS). Installation is smooth, `sudo zfs` shows usage instruction, but any further command is unfunctional, giving `The ZFS modules are not loaded` followd by `FATAL: Module zfs not found`. In `/lib/modules/`, some files related to `zfs` and `spl` including `*.ko` files are found in `/extra` directory which is in the directory named after an **old kernel which I have removed earlier**. Since the wiki gives particular instructions which I checked repeatedly by Googling, there should be nothing I missed.

Then I reversed `zfs.repo` back to default (dkms version) and installed zfs(dkms). During installation it sayed `kernel headers for this kernel does not seem to be installed`, but actually I have installed `kernel-devel` and the exact `kernel-header` is reported installed by `yum`. After that zfs(dkms) is still unfuctional, giving `The ZFS modules are not loaded` followd by `FATAL: Module zfs not found`. However this time there is NO files in the old-version-kernel-named directory under `/lib/modules/`.

This is my kernel. Old version kernel has been removed.
```shell
$ uname -a
Linux homeserver 3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 23 17:05:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Need help, cofused and anxious. And sorry for my rigid english.

**Comment by behlendorf** [comment]
@ungrown I'd suggest reinstalled the kABI-tracking kmod packages.  After the packages are installed symlinks should be created from your running `/lib/modules` directory to the `*.ko` file installed by the package.  Running `modprobe zfs` should then load those modules.  If they can't be loaded it's usually because the symlinks are either missing or the modules aren't compatible with your kernel.  The latter shouldn't be the case if you're running a stock el7 kernel.  You can also run `dmesg` to get an idea why a kernel module won't load.

**Comment by ungrown** [comment]
@behlendorf 
Seems like another failure for me.
Firstly I linked them to **/lib/modules/`uname -r`/**:
```shell
$ ll
total 2704
lrwxrwxrwx.  1 root root     44 Jul 30 14:10 build -> /usr/src/kernels/3.10.0-327.22.2.el7.x86_64/
drwxr-xr-x. 11 root root   4096 Jul  2 18:08 kernel
-rw-r--r--.  1 root root 706371 Aug  3 23:15 modules.alias
-rw-r--r--.  1 root root 682782 Aug  3 23:15 modules.alias.bin
-rw-r--r--.  1 root root   1288 Jun 24 01:17 modules.block
-rw-r--r--.  1 root root   5995 Jun 24 01:14 modules.builtin
-rw-r--r--.  1 root root   7744 Aug  3 23:15 modules.builtin.bin
-rw-r--r--.  1 root root 218218 Aug  3 23:15 modules.dep
-rw-r--r--.  1 root root 316220 Aug  3 23:15 modules.dep.bin
-rw-r--r--.  1 root root    339 Aug  3 23:15 modules.devname
-rw-r--r--.  1 root root    108 Jun 24 01:17 modules.drm
-rw-r--r--.  1 root root    100 Jun 24 01:17 modules.modesetting
-rw-r--r--.  1 root root   1522 Jun 24 01:17 modules.networking
-rw-r--r--.  1 root root  84666 Jun 24 01:14 modules.order
-rw-r--r--.  1 root root     89 Aug  3 23:15 modules.softdep
-rw-r--r--.  1 root root 311931 Aug  3 23:15 modules.symbols
-rw-r--r--.  1 root root 387108 Aug  3 23:15 modules.symbols.bin
lrwxrwxrwx.  1 root root      6 Jul 30 14:10 source -> build/
lrwxrwxrwx.  1 root root     64 Aug  3 23:25 splat.ko -> /lib/modules/3.10.0-327.18.2.el7.x86_64/extra/spl/splat/splat.ko
lrwxrwxrwx.  1 root root     60 Aug  3 23:25 spl.ko -> /lib/modules/3.10.0-327.18.2.el7.x86_64/extra/spl/spl/spl.ko
drwxr-xr-x.  2 root root      6 Jun 24 01:17 updates
drwxr-xr-x.  2 root root     91 Jul  2 18:08 vdso
drwxr-xr-x.  2 root root      6 Jun 24 01:17 weak-updates
lrwxrwxrwx.  1 root root     61 Aug  3 23:25 zavl.ko -> /lib/modules/3.10.0-327.18.2.el7.x86_64/extra/zfs/avl/zavl.ko
lrwxrwxrwx.  1 root root     68 Aug  3 23:25 zcommon.ko -> /lib/modules/3.10.0-327.18.2.el7.x86_64/extra/zfs/zcommon/zcommon.ko
lrwxrwxrwx.  1 root root     60 Aug  3 23:25 zfs.ko -> /lib/modules/3.10.0-327.18.2.el7.x86_64/extra/zfs/zfs/zfs.ko
lrwxrwxrwx.  1 root root     67 Aug  3 23:25 znvpair.ko -> /lib/modules/3.10.0-327.18.2.el7.x86_64/extra/zfs/nvpair/znvpair.ko
lrwxrwxrwx.  1 root root     64 Aug  3 23:25 zpios.ko -> /lib/modules/3.10.0-327.18.2.el7.x86_64/extra/zfs/zpios/zpios.ko
lrwxrwxrwx.  1 root root     69 Aug  3 23:25 zunicode.ko -> /lib/modules/3.10.0-327.18.2.el7.x86_64/extra/zfs/unicode/zunicode.ko
```
Then time for `modprobe`:
```shell
sudo modprobe zfs
modprobe: FATAL: Module zfs not found.
```

Hmmm, lets try **/lib/modules/**:
```shell
$ ll
total 4
drwxr-xr-x. 3 root root   18 Aug  3 23:16 3.10.0-327.18.2.el7.x86_64
drwxr-xr-x. 6 root root 4096 Aug  3 23:25 3.10.0-327.22.2.el7.x86_64
lrwxrwxrwx. 1 root root   48 Aug  3 23:28 splat.ko -> /lib/modules/3.10.0-327.22.2.el7.x86_64/splat.ko
lrwxrwxrwx. 1 root root   46 Aug  3 23:28 spl.ko -> /lib/modules/3.10.0-327.22.2.el7.x86_64/spl.ko
lrwxrwxrwx. 1 root root   47 Aug  3 23:28 zavl.ko -> /lib/modules/3.10.0-327.22.2.el7.x86_64/zavl.ko
lrwxrwxrwx. 1 root root   50 Aug  3 23:28 zcommon.ko -> /lib/modules/3.10.0-327.22.2.el7.x86_64/zcommon.ko
lrwxrwxrwx. 1 root root   46 Aug  3 23:28 zfs.ko -> /lib/modules/3.10.0-327.22.2.el7.x86_64/zfs.ko
lrwxrwxrwx. 1 root root   50 Aug  3 23:28 znvpair.ko -> /lib/modules/3.10.0-327.22.2.el7.x86_64/znvpair.ko
lrwxrwxrwx. 1 root root   48 Aug  3 23:28 zpios.ko -> /lib/modules/3.10.0-327.22.2.el7.x86_64/zpios.ko
lrwxrwxrwx. 1 root root   51 Aug  3 23:28 zunicode.ko -> /lib/modules/3.10.0-327.22.2.el7.x86_64/zunicode.ko
```
Then `modprobe`:
```shell
$ sudo modprobe zfs
modprobe: FATAL: Module zfs not found.
```

:(

**Comment by kpande** [comment]
please use the mailing list for questions like this - you will have better chances at finding a solution.

**Comment by otraupe** [comment]
mohan, I have the same problem atm. did you ever solve this?
