### ISSUE TITLE
zfs mount of one particular fs sits forever in D state

### ISSUE THREAD

**Issue by osd1000** [zfsonlinux/zfs#4920]
Ubuntu 14.04.4 LTS, kernel 3.13.0-92-generic
ZFS version 0.6.5.7-1~trusty

I have a pool of ~2600 zfses which seems to be working mostly well, but attempting to mount one zfs causes zfs mount to sit around forever in D state.

I've set it to canmount=noauto so I can boot and reboot the machine.

root@rooster:/local# zfs set canmount=noauto local/scratch
root@rooster:/local# zfs mount local/scratch

In another terminal window:

root@rooster:/home/osd1000# ps -eo pid,comm,args,state,wchan | grep mount.zfs
 17460 mount.zfs       /sbin/mount.zfs local/scrat D cv_wait_common

How can I debug this further?

Owen

**Comment by behlendorf** [comment]
This issue may be resolved by commit e3e670d which is in master and should be in the next point release.  You could try cherry picking that patch and see if it resolves/improves the issue.

**Comment by behlendorf** [comment]
@osd1000 the issue resolved by the commit was that `zfs_init_libshare` was run regardless of how the properties were set.
