### ISSUE TITLE
altroot with chroot breaks zfs list

### ISSUE THREAD

**Issue by dasJ** [zfsonlinux/zfs#4931]
I'm using systemd (on Arch Linux) in my initrd. As there is no official way of using a ZFS root with systemd-initrd (at least I couldn't find anything), I built it myself.

When systemd starts in the initrd, I import all pools and when systemd is trying to mount ZFS on `/sysroot`, I take care of that. I accomplish that by setting `altroot` to `/sysroot` when importing the pools.

When systemd switches the root, everything works great, but when I look at the output of `zfs list`, my root dataset appears to be mounted to `/sysroot`. Of course, this was the case before switching roots, but now it's files are at `/`.

 This isn't just a visual issue, I also get problems when I want to create subdatasets. Using `zfs create tank/root/mydataset` will mount the dataset at `/sysroot/tank/root/mydataset` instead of `/tank/root/mydataset`.

In my opinion, ZFS should handle the root switch and substitute the altroot paths accordingly.

**Comment by kpande** [comment]
use `mount -t zfs -o zfsutil pool/fs /sysroot` in initrd.
