### ISSUE TITLE
ubuntu 16.04 documentation: /var has trouble mounting

### ISSUE THREAD

**Issue by g--** [zfsonlinux/zfs#4938]
Hi!  I'm posting here because I couldn't find a more appropriate place to post feedback for the wiki documentation.

I just finished following

 https://github.com/zfsonlinux/zfs/wiki/Ubuntu%2016.04%20Root%20on%20ZFS

and successfully got a system up with a ZFS root.  One challenge I had was /var.  It doesn't get mounted before systemd starts writing to it.  I worked around this by setting the zfs flag for pool/var to ignore a non-empty mount point, but it seems less than ideal.

Thanks for the guide!

Geoff

**Comment by dasjoe** [comment]
The wiki makes no mention of `/var` being on its own mountable dataset.
It actually ensures `rpool/var` is not mountable:

```
# zfs create -o canmount=off -o setuid=off  -o exec=off rpool/var
# zfs create -o com.sun:auto-snapshot=false             rpool/var/cache
# zfs create                                            rpool/var/log
# zfs create                                            rpool/var/spool
# zfs create -o com.sun:auto-snapshot=false -o exec=on  rpool/var/tmp
```
