### ISSUE TITLE
Zpool resize + iSCSI

### ISSUE THREAD

**Issue by Gabrym** [zfsonlinux/zfs#4942]
Hello Team,

I have issue when i want increase zpool size.
  pool: epool
 state: ONLINE
  scan: none requested
config:

        NAME                                                                                        STATE     READ WRITE CKSUM
        epool                                                                                 ONLINE       0     0     0
          mirror-0                                                                                  ONLINE       0     0     0
            ip-X.X.X.X:3260-iscsi-iqn.2003-01.org.linux-iscsi.XXX.x8664:sn.4131b20eecae-lun-1  ONLINE       0     0     0
            ip-X.X.X.Y:3260-iscsi-iqn.2003-01.org.linux-iscsi.YYY.x8664:sn.c11a6ff468d4-lun-1  ONLINE       0     0     0

I tried:
1. Autoexpend = off
a) zpool set autoexpend=off epool
b) zpool online -e epool ip-X.X.X.X:3260-iscsi-iqn.2003-01.org.linux-iscsi.XXX.x8664:sn.4131b20eecae-lun-1
c) zpool online -e epool ip-X.X.X.Y:3260-iscsi-iqn.2003-01.org.linux-iscsi.XXY.x8664:sn.4131b20eecae-lun-1
2. Autoexpend = on
a)  zpool set autoexpend=on epool

When i check epool ip-X.X.X.X:3260-iscsi-iqn.2003-01.org.linux-iscsi.XXX.x8664:sn.4131b20eecae-lun-1 by gdisk i see new free space like 3 TB but pool has only 1 TB space.

modinfo zfs
filename:       /lib/modules/4.5.4-1-ARCH/extra/zfs/zfs.ko.gz
version:        0.6.5-253_ga9bb2b6
license:        CDDL
author:         OpenZFS on Linux
description:    ZFS
srcversion:     CB04DCABF280B5751A780A2

**Comment by Gabrym** [comment]
ip-X.X.X.X:3260-iscsi-iqn.2003-01.org.linux-iscsi.XXX.x8664:sn.4131b20eecae-lun-1 it's link to /dev/sde

Output from gdisk:
 gdisk -l /dev/sde
GPT fdisk (gdisk) version 1.0.1

Partition table scan:
  MBR: protective
  BSD: not present
  APM: not present
  GPT: present

Found valid GPT with protective MBR; using GPT.
Disk /dev/sde: 6442450944 sectors, 3.0 TiB
Logical sector size: 512 bytes
Disk identifier (GUID): A2642A74-26C9-9248-B24E-4C829724D5B0
Partition table holds up to 128 entries
First usable sector is 34, last usable sector is 6442450910
Partitions will be aligned on 2048-sector boundaries
Total free space is 4029 sectors (2.0 MiB)

Number  Start (sector)    End (sector)  Size       Code  Name
   1            2048      6442432511   3.0 TiB     BF01  zfs-9bbab718f5dd7870
   9      6442432512      6442448895   8.0 MiB     BF07

**Comment by FransUrbo** [comment]
Did you rescan the partition table? Fdisk can usually see the (new) size, but you also need to tell the kernel. Try ``partprobe /dev/...``

**Comment by Gabrym** [comment]
It helped. Thank you very much.

**Comment by kpande** [comment]
please use the mailing list for questions like this in the future
