### ISSUE TITLE
zfs list showing 30GB less free space after upgrade to Ubuntu 16.04

### ISSUE THREAD

**Issue by omegab** [zfsonlinux/zfs#4945]
I upgraded to Ubuntu 16.04 (new install) from Ubuntu 14.04 and now zfs list shows ~28-30GB less free space on each of my 3 zpools. 

*2 disk mirror
*zfs list is about 30GB less free space (e.g. 302GB vs 330GB). Same as df -h.
*zpool list shows the exact same free space on both systems (e.g 359GB)
Ubuntu 16.04 is running zfsutils-linux 0.6.5.6-0ubuntu10
Ubuntu 14.04 is running ubuntu-zfs ~8-trusty

Any ideas?

**Comment by kernelOfTruth** [comment]
https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.6.5

```
Changes in Behavior

Default reserved space was increased from 1.6% to 3.2% of total pool capacity. This default percentage can be controlled through the new spa_slop_shift module option, setting it to 6 will restore the previous percentage.
```

set

```
options zfs spa_slop_shift=6
```

in 


/etc/modprobe.d/zfs.conf

**Comment by omegab** [comment]
Perfect, works exactly as you said.
