### ISSUE TITLE
External Fragmentation leading to Out of memory Condition

### ISSUE THREAD

**Issue by gaurkuma** [zfsonlinux/zfs#4953]
Hi,

We have been facing this issue with ZFS where we see huge fragmentation after the system is up and running workload for few hours. 

Setup:

Running with 12GB RAM with ZFS having 50% as arc_max and arc_min set to 30%. Test being run creates 128GB of data in Phase 1 with 500k files each of 256k size and in Phase 2 does, random R/W/U on the existing files. 

The system starts with having most of the pages in 4MB list 

cat /proc/buddyinfo
Node 0, zone      DMA      0      1      1      0      2      1      1      0      1      1      3 
Node 0, zone    DMA32     42   1492    574    155     46     61     38     26      8      3    619 
Node 0, zone   Normal     66   8473    517    119     62    247    154     31      8      5   1965 

After the test is started and running for couple of hours the memory is highly fragmented 

Node 0, zone      DMA      0      0      1      0      2      1      1      0      1      1      3 
Node 0, zone    DMA32   3749   2061   9264    715      7      3      2      3      1      0      0 
Node 0, zone   Normal  77836  36734    123     35      2      1      0      0      0      0      0 

Things Tried to reduce fragmentation
1. Use MOVABLE zone for user space allocation to limit the fragmentation to  a particular zone. 
2. Use kmalloc instead of vmalloc for zio_buf\* slab allocations. Although larger allocations are not recommended to use kmalloc but since we know in our case, ZFS is mostly the consumer of memory, so we forced it to use kmalloc by tweaking the spl_kmem_cache_kmem_limit parameter to 128KB. Wanted to see if it helps us with fragmentation but doesnt look like. 
3. Reduce arc_max to 40% and arc_min to 20% but didnt help either. 

Wherein I understand fragmentation is bound to happen but in our case it looks to be extreme as  no. of 4KB and 8KB pages is huge. Any ideas as to how we can reduce the amount of fragmentation.

**Comment by kernelOfTruth** [comment]
This is also an observation that I made.

```slub_nomerge```

on bootup

and memory compaction might help for newer kernels (where the compaction algorithm got significantly improved)

a new feature is also the compaction of unevictable pages:

```
echo 1 > /proc/sys/vm/compact_unevictable
```

<-- to enable it

```
echo 1 > /proc/sys/vm/compact_memory
```

<-- for compaction,

every several hours or so, keep in mind that while compaction is running this can lead to latency spikes


Additional suggestions or approaches on how to mitigate this is welcome

**Comment by gaurkuma** [comment]
@kernelOfTruth I will try with slub_nomerge. 

/proc/sys/vm/compact_unevictable is already set to 1 in our environment. 

I am not sure if regularly writing to /proc/sys/vm/compact_memory will make a difference since i see the compaction code path is anyways hit several times because of memory pressure.

**Comment by kernelOfTruth** [comment]
okay, scratch that with slub_nomerge, apologies, so quite the opposite is the case

https://utcc.utoronto.ca/~cks/space/blog/linux/SlabinfoSlabMerging
http://lwn.net/Articles/229096/

no idea how I got to remember that slub_nomerging was to reduce fragmentation.

It's the job of slab-merging to reduce fragmentation and superfluous caches

**Comment by dweeezil** [comment]
@gaurkuma There's a chance ABD (#3441) could help with this or could at least be forced to help reduce external fragmentation.  However, if you're main issue is with the smaller 4KiB and 8KiB allocations, I'm not sure it would make any difference.

Theoretically, we could implement a consolidator of some sort, even if a very rudimentary one, in the SPL slab implementation similar to that of illumos.  That would, of course, require moving back to the SPL slab for the smaller allocations.  As a note, it's very likely that some of the original rationale for moving these smaller allocations to the Linux slab are no longer valid due to the many other memory management improvements that have been made in the mean time.

**Comment by behlendorf** [comment]
Closing, this is believed to have been resolved by ABD.

**Comment by poige** [comment]
Not sure if it was exactly this issue but I've just seen such lack of RAM on a host with ZFS that in despite of `free` reported bunch of free memory (arc limited to 16 GB and host has 128 GB), the system couldn't allocate pretty smaller amount to run a program. Dropping caches solved it.
