### ISSUE TITLE
Snapshot and TAR incremental problem

### ISSUE THREAD

**Issue by svirusxxx** [zfsonlinux/zfs#4968]
Hello, I use amanda backup system for remote backups.
It's support zfs-snapshot for making backups.
Few days ago I installed first time ZFS on my linux server (gentoo).
And I find problem with amanda.
Exectly the problem is amanda making always first incremental level of the same size as level 0 (full).
When I try to find where is a problem, i found there is a problem when "tar" calculating incremental backup.
Amanda use command similar to this:
`tar -cvvf /dev/null --restrict --no-acls --no-xattrs --listed-incremental /tmp/amanda_level_0 --no-check-device --ignore-failed-read --totals --no-acls --no-xattrs --no-selinux .`
And ... when amanda do this second time , on brend new snapshot (with no files changed), tar show information that the "." (dot) directory has renamed.
`tar: .: Directory has been renamed`
So "tar" think that everything is changed.
here is my example: http://pastebin.com/AgmkjNPY

On other my servers I use LVM-Snapshots with amanda, and tar never show this information.
So I think the problem is in zfs implementation.

**Comment by svirusxxx** [comment]
I make hot fix to this.
https://forums.zmanda.com/showthread.php?6199-Amanda-3-3-9-ZFS-on-Linux-incremental-backup-problem&p=18765

**Comment by behlendorf** [comment]
@svirusxxx thanks for digging in to this and filing an issue.  Based on the debugging you've posted the issue appears to be that `tar` detects that the root inode number of mounted snapshot has changed.  This was done intentionally by ZFS and that root inode number is used to encode exactly what snapshot needs to be auto-mounted there.  If `tar` can be updated to ignore just that inode number for ZFS that may be the best solution.

**Comment by svirusxxx** [comment]
@behlendorf Thanks for replay.
OK,  I will report this to gnu-tar software and make a better patch.
