### ISSUE TITLE
current HEAD unbootable, libgcc_s.so.1 must be installed for pthread_cancel to work

### ISSUE THREAD

**Issue by bunder2015** [zfsonlinux/zfs#4976]
Tried to upgrade from a git version from a month or so ago, to one from today.  When I rebooted, importing my root pool failed with the message "libgcc_s.so.1 must be installed for pthread_cancel to work".

Booted in with a livecd and did a "revdep-rebuild -L libgcc_s.so.1", re-emerged the zfs packages, rebuilt the initrd and rebooted, unfortunately I got the same error.

**Comment by drescherjm** [comment]
I have the same issue in gentoo as well. Are you using genkernel or genkernel-next?

**Comment by bunder2015** [comment]
I'm currently using 4.3.4, built by hand, but the initrd was built by genkernel.

**Comment by behlendorf** [comment]
Looks like a duplicate of #4749.
