### ISSUE TITLE
Unable to disable zpool import during boot without manual editing zfs-import-scan.service

### ISSUE THREAD

**Issue by redtex** [zfsonlinux/zfs#4980]
I have a High-available SAN storage - CentOS 7 + ZoL + SCST + pacemaker. In such setup pools imported after system boot by pacemaker. But zfs module is loaded either by zfs-import-cache.service, which start condition failed because pools imported without cachefile or by zfs-import-scan.service which must be masked, because pools, as I mentioned before, must be loaded by pacemaker.
To resolve this problem I have to create my own zfs-module.service:
```
[Unit]
Description=Loads ZFS module
DefaultDependencies=no
Requires=systemd-udev-settle.service
After=systemd-udev-settle.service
After=cryptsetup.target
Before=local-fs.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/sbin/modprobe zfs

[Install]
WantedBy=multi-user.target

```
mask zfs-import-cache.service and zfs-import-scan.service

**Comment by rlaager** [comment]
See 92547bc45ca9a2114662d9343ae53e5098acb627 and #4658. If this is something different, please re-open. If you can't reopen a closed bug, message me and I'll do it.

**Comment by redtex** [comment]
Not exactly, but in general you are correct.
