### ISSUE TITLE
zdb rate estimator underflows

### ISSUE THREAD

**Issue by nwf** [zfsonlinux/zfs#4982]
I am not sure quite what I did to provode zdb's ire, but while running `zdb -ecm`, 

```
4.09T completed ( 598MB/s) estimated time remaining: 4294775575hr 4294967279min 4294967241sec        
```

is a particularly impolite way of saying "I have no idea".  Operations are continuing against the disks and things look like they're going to work out, but it'd be nice to have.... slightly more realistic progress information. :)

**Comment by ironMann** [comment]
This might be fixed by f0c26069bdf4ec675c840f0932fcfe7d4036d06f

@nwf Can you retest with `zdb` from master?
