### ISSUE TITLE
Test case: zfs_mount_006_pos

### ISSUE THREAD

**Issue by BearBabyLiu** [zfsonlinux/zfs#4990]
I being debugged the zfs-test scripts about zfs_mount,,I found that the scipts as zfs_mount_pos_005,zfs_mount_pos_006,zfs_mount_007_pos,zfs_mount_009_neg,zfs_mount_010_neg.ksh execute failure, through see the file-linux.run, found these scripts needs investigation, I try to debuged zfs_mount_pos_005,zfs_mount_pos_006,zfs_mount_010_neg.ksh, on  my machine(linux 2.6.33)

through debug, I found that The cause of zfs_mount_pos_005 failure is same to the zfs_mount_010_neg.ksh
The two scipts verify "If the filesystem 's mountpoint is currently in use, will mount failed"
but in my machine, I execute the operation of these scipts, The results are as follows:

```
- [root@A22832414_00 /]# zpool list
- NAME    SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
- raid0   192M   384K   192M         -     1%     0%  1.00x  ONLINE  -
- [root@A22832414_00 /]# zfs create raid0/fs1
- [root@A22832414_00 /]# zfs set mountpoint=/home/liuliu/ raid0/fs1
- [root@A22832414_00 /]# zfs umount -f raid0/fs1
- [root@A22832414_00 /]# cd /home/liuliu/  /* Building  mountpoint is currently in use scenarios */
- [root@A22832414_00 liuliu]# zfs mount raid0/fs1 /* mount success is different to scipts verify */
- [root@A22832414_00 liuliu]#
```

From the above known, in linux, Even if the mountpoint is currently in use, can also be mounted, so
the scipts as zfs_mount_pos_005 and zfs_mount_010_neg excute failed.

the zfs_mount_pos_006 verify "If filesystem 's mountpoint be the identical of existing filesystem,it will mount failed"

but in my machine, I execute the operation of the scipt, The results are as follows:

```
[root@A22832414_00 liuliu]# zfs list
NAME                   USED  AVAIL  REFER  MOUNTPOINT
raid0                  110K   160M    19K  /raid0
zpool11                907M   400M  24.0K  /zpool11
zpool11/testvol28070   155M   555M  9.33K  -
zpool11/testvol28071   188M   588M     8K  -
zpool11/testvol28072   188M   588M     8K  -
zpool11/testvol28073   188M   588M  9.33K  -
zpool11/testvol28074   188M   588M  9.33K  -
[root@A22832414_00 liuliu]# zfs create raid0/fs1
[root@A22832414_00 liuliu]# zfs set mountpoint=/home/liuliu/ raid0/fs1
[root@A22832414_00 liuliu]# zfs create raid0/fs2
[root@A22832414_00 liuliu]# zfs umount raid0/fs2
[root@A22832414_00 liuliu]# zfs set mountpoint=/home/liuliu/ raid0/fs2
[root@A22832414_00 liuliu]# zfs mount
raid0                           /raid0
zpool11                         /zpool11
raid0/fs1                       /home/liuliu
[root@A22832414_00 liuliu]# zfs mount raid0/fs2
[root@A22832414_00 liuliu]# zfs mount
raid0                           /raid0
zpool11                         /zpool11
raid0/fs1                       /home/liuliu
raid0/fs2                       /home/liuliu
[root@A22832414_00 liuliu]# 
```

From the above known, in linux, Even if the  mountpoint be the identical of existing filesystem, can also be mounted, so the scipts as zfs_mount_pos_006 excute failed.
Analysis:
Overlay mount is default in Linux, zfs's code only limits the mountpoint is not empty,The following

```
    /*
     * Determine if the mountpoint is empty.  If so, refuse to perform the
     * mount.  We don't perform this check if 'remount' is
     * specified or if overlay option(-O) is given
     */
    if ((flags & MS_OVERLAY) == 0 && !remount &&
        !dir_is_empty(mountpoint)) {
        zfs_error_aux(hdl, dgettext(TEXT_DOMAIN,
            "directory is not empty"));
        return (zfs_error_fmt(hdl, EZFS_MOUNTFAILED,
            dgettext(TEXT_DOMAIN, "cannot mount '%s'"), mountpoint));
    }
```

so ,if the mountpoint  is empty,  Even if the  mountpoint be the identical of existing filesystem, can also be mounted, and after mount will  overlay  before mount, see all the scipts about zfs_mount, find that not verfiy "if mountpoint is not empty,will mount filesystem failed",so I add one scipt about it,code is the follow:

```
#!/IDE0/ztest/zfs-tests/bin/bash -p
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2007 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

. $STF_SUITE/include/libtest.shlib
. $STF_SUITE/tests/functional/cli_root/zfs_mount/zfs_mount.kshlib

#
# DESCRIPTION:
# Invoke "zfs mount <filesystem>" with a filesystem
# but its mountpoint is not empty,
# it will fail with a return code of 1
# and issue an error message.
#
# STRATEGY:
#1. Make sure that the ZFS filesystem is unmounted.
#2. Apply 'zfs set mountpoint=path <filesystem>'.
#3. Create a file in the given mountpoint.
#3. Invoke 'zfs mount <filesystem>'.
#4. Verify that mount failed with return code of 1.
#

verify_runnable "both"

function cleanup
{
    log_must $ZFS set mountpoint=$TESTDIR $TESTPOOL/$TESTFS
    log_must force_unmount $TESTPOOL/$TESTFS
    return 0
}

typeset -i ret=0

log_assert "Verify that '$ZFS $mountcmd' with a filesystem " \
    "whose mountpoint is currently not empty will fail with return code 1."

log_onexit cleanup

unmounted $TESTPOOL/$TESTFS || \
    log_must cleanup

[[ -d $TESTDIR ]] || \
    log_must $MKDIR -p $TESTDIR

log_must $TOUCH $TESTDIR/$TESTFILE0

$ZFS $mountcmd $TESTPOOL/$TESTFS
ret=$?
(( ret == 1 )) || \
    log_fail "'$ZFS $mountcmd $TESTPOOL/$TESTFS' " \
        "unexpected return code of $ret."

log_note "Make sure the filesystem $TESTPOOL/$TESTFS is unmounted"
unmounted $TESTPOOL/$TESTFS || \
    log_fail Filesystem $TESTPOOL/$TESTFS is mounted

log_pass "'$ZFS $mountcmd' with a filesystem " \
    "whose mountpoint is currently not empty failed with return code 1."
```

Thank you!

**Comment by behlendorf** [comment]
@BearBabyLiu thanks for looking in to this.  So the intention here is to optionally emulate the mount overlay behavior as it exists on illumos.  For this purpose an `overlay` property was added, from `zfs(8)`.

```
       overlay=on | off

           Allow mounting on a busy directory or a directory which already contains
           files/directories. This is the default mount behavior for Linux filesys‐
           tems.  However, for consistency with  ZFS  on  other  platforms  overlay
           mounts  are  disabled  by  default.   Set  overlay=on  to enable overlay
           mounts.
```

Now it may be for that behavior to work the zfs.mount helpers needs to be installed.

I'd love to see these scripts updated for Linux so they verify this propery is behavior correctly.  If you have a proposed patch for this it would be great if you could open a new pull request.

**Comment by BearBabyLiu** [comment]
@behlendorf  Thank you for your guidance, I would be glad to do it,But I have a question,I'm directly modifying existing scripts or add new script? Modify the script directly may be will affect the execution of other platforms such as illumos or These scripts are only executed on Linux, modify directly is ok ? I'm going to do the thing in the next two days

**Comment by behlendorf** [comment]
You can modify the existing test cases.  However, since we don't want to break them for other platforms we've added some helper functions.  You can use the `is_linux` function to wrap Linux-only sections of the test like this:

```
if is_linux; then
..
else
...
fi
```

**Comment by tcaputi** [comment]
@behlendorf What do you think we want to do here? It seems that zfs is behaving reasonably well right now, given that the Linux kernel is ok with multiple filesystems sharing a mountpoint. This sees like an easy test to fix once we make a decision about how we want to handle it.

**Comment by behlendorf** [comment]
@tcaputi we should get the test cases updated and test the expected `overlay` behavior.
