### ISSUE TITLE
Open the scripts (zfs_create_003_pos.ksh,zfs_create_006_pos.ksh) in zfs_create

### ISSUE THREAD

**Issue by ChaoyuZhang** [zfsonlinux/zfs#4991]
The scripts (zfs_create_003_pos.ksh,zfs_create_006_pos.ksh) was shielded in linux.run, but I found these two scripts can run successfully on my linux, my linux version is 2.6.33.20  (gcc version 4.4.5 20110214 (Red Hat 4.4.5-6) (GCC) ).
      Is there any other reasons to do so? If not, I think we can open them to increase test scene.

**Comment by behlendorf** [comment]
@ChaoyuZhang they may have either been overlooked or failed on other Linux distributions.  If you open a new pull request which adds them to the `linux.run` file we'll be able to determine if they pass the buildbot and can be enabled.

**Comment by ChaoyuZhang** [comment]
OK, thanks for your answer.

**Comment by behlendorf** [comment]
Resolved by 43cb1c1212be430f1a94307ac8be1737ca564e58
