### ISSUE TITLE
Mount Fails, Unable to Open the Dataset

### ISSUE THREAD

**Issue by necouchman** [zfsonlinux/zfs#4994]
I've been happily churning along create ZPOOLs and ZFS volumes for most of the day today, but, toward the end of my adventures, have run into the following error when trying to create a new ZFS:

```
# zfs create local/blah
filesystem '/local/blah' cannot be mounted, unable to open the dataset
cannot mount 'local/blah': Invalid argument
filesystem successfully created, but not mounted
```

I can then destroy and retry, and the error is consistent.  Additionally, if I try to unmount and then remount an existing data set, I get the same error:

```
# zfs unmount local/testing
# zfs mount local/testing
filesystem '/local/testing' cannot be mounted, unable to open the dataset
cannot mount 'local/testing': Invalid argument
```

I don't see any obvious errors in dmesg output or /var/log/messages, so not sure what's going on.  I have several systems with many more mounted filesystems than this one has, so I don't think I've hit any sort of limitation on number of mounted filesystems - and that also would not explain why I cannot unmount and remount.  I'm running CentOS 6 (kernel version 2.6.32-573.18.1.el6.x86_64), and spl/zfs version 0.6.5.5-1.  Any hints would be appreciated.

**Comment by necouchman** [comment]
Going to guess this is long since resolved - at least, no an issue for me anyway.

**Comment by thorsummoner** [comment]
btw I had this issue when my current working directory had a file/directory who's name shadowed the zfs dataset name

```
# say I had these two filesystem names:

/tank/foo/bar
/root/scratch/tank/foo/bar

# (cd /root/scratch/; zfs mount tank/foo/bar)
filesystem '/root/scratch/tank/foo/bar' cannot be mounted, unable to open the dataset

# (cd /; zfs mount tank/foo/bar)
((success))

```

looks like the zfs mount command does a fielsystem lookup for the dataset name, and if that happens to match a real file name, it adjusts the zfs mount call to use the full name of the relative path result, which in my case scared me but was otherwise harmless.
