### ISSUE TITLE
a theory on cpu usage and freeze with zfs in general.

### ISSUE THREAD

**Issue by dorvan** [zfsonlinux/zfs#5006]
Hi all.
I'm using zfs since first openindiana release, and as possible, I've started to use in in linux, on servers, clusters, my clients pc, notebooks...
I'm a gentoo user firslty.

At today, what I am available to see, also reproducing some scenario posted in open and past issues, most of performance problems (a part compression and dedup) it's related to filesystem hierarchy.

I intend "**hierarchy**" (or nesting) in 3 contexts.
**1- Dataset Hierarchy
2- Mounpoint Hierarchy
3- Snapsnot quantity**

To evaluate more deeply I want to ask to all users who have posted an issues to print-out here (also changing names) their pool/and mountpoint layout.

I had some of problems highlighted in issues in past, and also in near past.
performance issues and wrong sizes calculation on different zpool and datasets.

But.... since December 2015 I've changed the default file system layout in my works, to have single-level Dataset hierarchy, a snapshot cleanup procedure and clean as possible mountpoint structure. 

Other my bestpractice it's to leave empty and out from used mountpoint structure, the zpool volume (I mount it to /(..)pool/*VolRoot*, the other Dataset can start in /(...)pool/Data/*DatasetsMountpoints*
This have solved most of performance problems, on both SSD and mechanical disks; on all kind of systems, phisical and virtual with any kind of available RAM.

So...
**Can hierarchy, _really_, affect performances?**

I'm interested in all kind of costructive answers. 
Thanks.
Ivan

**Comment by dorvan** [comment]
@behlendorf This is not only performance related, 
but impact also on snapshot creation and deletion, in a nested zfs structure (dataset AND/OR mountpoint) it's more frequent the presence of freeze and locks directly related on worker forking and memory usage, if they causing a deadlock, after the reboot the pool report a non-coherent sizes situation, usually fixed with a scrub.

**Comment by dweeezil** [comment]
@dorvan Lots of datasets and snapshots can increase the need to cache metadata for the DMU dnode objects which are effectively giant sparse arrays.  There's also the issue that they only use a 16K blocksize which doesn't help much when they're very large.  If memory pressure causes this metadata to be evicted, you'll see poor performance when manipulating the dataset hierarchy.

Regardless, you shouldn't be seeing deadlocks.  Have you got a test case which can reproduce the problem?

**Comment by dorvan** [comment]
@dweeezil not for deadlocks, for locks yes, simply using a zfs as samba server backend for windows clients home directories. After an intense usage (especially with chrome browser directory structure in AppData can produce a smb/zfs disalignment of objects, (10 users concurrent rw/access, with a single dataset disalignment, a single home it's enough) can reduce performance and cause small zfs freezes manipulating snapshots, not deadlocks

**Comment by kpande** [comment]
please use [the zfs-discuss mailing list](http://list.zfsonlinux.org) for general questions unless you can rewrite the issue so it is more well defined..
