### ISSUE TITLE
can not create pool: invalid feature (null)

### ISSUE THREAD

**Issue by li1ju** [zfsonlinux/zfs#5032]
hi,

I just installed zfs on a machine running debian jessie 8.5
I set the arcsize in /etc/modprobe.d/zfs.conf :

> options zfs zfs_arc_max=9663676416

then modprobe zfs, and create a pool
`zpool create tank mirror sdb sdc`

i get the following error :

> cannot create 'tank': invalid feature '(null)'

i tried changing the pool name, with or without options (ashift), with different disks, with the name from /dev/disk/by-id, or /dev/sdb, but i still get the same error

my zfs version is the latest (0.6.5.7-8-jessie)

thanks

**Comment by li1ju** [comment]
one thing i can see after the creation failed: the zfs partitions on the disks are created.
before creating the pool, my disks are clean
```
wipefs -a /dev/sdb
dd if=/dev/zero of=/dev/sdb bs=100M count=1
```
and i set the partition table with GPT
`parted /dev/sdb mklabel gpt`

once the creation has failed ($? gives 1 in return), i look at the disk :
`fdisk -l /dev/sdb`
and the partitions are here :
> Disque /dev/sdb : 3,7 TiB, 4000787030016 octets, 7814037168 secteurs
> Unités : secteur de 1 × 512 = 512 octets
> Taille de secteur (logique / physique) : 512 octets / 4096 octets
> taille d'E/S (minimale / optimale) : 4096 octets / 4096 octets
> Type d'étiquette de disque : gpt
> Identifiant de disque : 1C428F34-F203-6F43-AEF1-280047B884E2
> 
> Device          Start        End    Sectors  Size Type
> /dev/sdb1        2048 7814019071 7814017024  3,7T Solaris /usr & Apple ZFS
> /dev/sdb9  7814019072 7814035455      16384    8M Solaris reserved 1

**Comment by li1ju** [comment]
after reading a alot, it seems the problems come from a feature of this version.
i can create a pool with the -d flag
example:
`zpool create -d tank mirror sdb sdc`
now, features are disabled :
`zpool status`

> pool: tank
>  state: ONLINE
> status: Some supported features are not enabled on the pool. The pool can
> 	still be used, but some features are unavailable.
> action: Enable all features using 'zpool upgrade'. Once this is done,
> 	the pool may no longer be accessible by software that does not support
> 	the features. See zpool-features(5) for details.
>   scan: none requested
> config:
> 
> 	NAME                                  STATE     READ WRITE CKSUM
> 	tank                               ONLINE       0     0     0
> 	  mirror-0                            ONLINE       0     0     0
> 	    ata-ST6000VN0021-1Z811C_ZA10ALAJ  ONLINE       0     0     0
> 	    ata-ST6000VN0021-1Z811C_ZA10AL3X  ONLINE       0     0     0
> 	  mirror-1                            ONLINE       0     0     0
> 	    ata-ST4000VN000-1H4168_Z300YT07   ONLINE       0     0     0
> 	    ata-ST4000VN000-1H4168_Z300YSTL   ONLINE       0     0     0
> 
> errors: No known data errors

i i look at the feature by doing `zpool upgrade` :
> This system supports ZFS pool feature flags.
> 
> All pools are formatted using feature flags.
> 
> 
> Some supported features are not enabled on the following pools. Once a
> feature is enabled the pool may become incompatible with software
> that does not support the feature. See zpool-features(5) for details.
> 
> POOL  FEATURE
> ---------------
> helPool
>       async_destroy
>       empty_bpobj
>       lz4_compress
>       spacemap_histogram
>       enabled_txg
>       hole_birth
>       extensible_dataset
>       embedded_data
>       bookmarks
>       (null)
>       (null)

the 2 last are named 'null', maybe this is the problem ;-)

**Comment by li1ju** [comment]
after upgrading the pool
`zpool upgrade tank`

> This system supports ZFS pool feature flags.
> 
> Enabled the following features on 'tank':
>   async_destroy
>   empty_bpobj
>   lz4_compress
>   spacemap_histogram
>   enabled_txg
>   hole_birth
>   extensible_dataset
>   embedded_data
>   bookmarks
> cannot set property for 'tank': invalid feature '(null)'

zpool status

> pool: tank
>  state: ONLINE
> status: Some supported features are not enabled on the pool. The pool can
> 	still be used, but some features are unavailable.
> action: Enable all features using 'zpool upgrade'. Once this is done,
> 	the pool may no longer be accessible by software that does not support
> 	the features. See zpool-features(5) for details.
>   scan: none requested
> config:
> 
> 	NAME                                  STATE     READ WRITE CKSUM
> 	tank                               ONLINE       0     0     0
> 	  mirror-0                            ONLINE       0     0     0
> 	    ata-ST6000VN0021-1Z811C_ZA10ALAJ  ONLINE       0     0     0
> 	    ata-ST6000VN0021-1Z811C_ZA10AL3X  ONLINE       0     0     0
> 	  mirror-1                            ONLINE       0     0     0
> 	    ata-ST4000VN000-1H4168_Z300YT07   ONLINE       0     0     0
> 	    ata-ST4000VN000-1H4168_Z300YSTL   ONLINE       0     0     0
> 
> errors: No known data errors

`zpool upgrade`

> This system supports ZFS pool feature flags.
> 
> All pools are formatted using feature flags.
> 
> 
> Some supported features are not enabled on the following pools. Once a
> feature is enabled the pool may become incompatible with software
> that does not support the feature. See zpool-features(5) for details.
> 
> POOL  FEATURE
> ---------------
> tank
>       (null)
>       (null)

**Comment by rincebrain** [comment]
That's...really strange.

Can you do me a favor and share the values from
cat /sys/module/{spl,zfs}/version
zpool upgrade -v
dpkg -V spl zfs

The only thing I can conceive of that could cause this would be if you had been running a newer version of ZFS at some point, with feature flags that aren't in 0.6.5-release...but even then, only one feature flag has been added in git versus 0.6.5-release (large_dnode), so I don't quite understand the two (null) values.

**Comment by li1ju** [comment]
to be sure,
i just did:
`apt-get update && apt-get upgrade`
3 new updates showed up:
> libnvpair1
> libzpool2
> libuutil1

After the upgrade, i did a `zpool upgrade` and the "null" features were gone.
The 2 left were filesystem_limits and large_blocks
After a `zpool upgrade tank` no problem anymore.
i could also destroy the pool and recreate it, without problem :)
So that's strange, for sure !
i guess the upgrade fixed it.

**Comment by JuliaVixen** [comment]
Oh hey! I can reproduce this problem. Even after updating and upgrading SPL and ZFS.

```
zpool create \
-O atime=off \
-O exec=off \
-O devices=off \
-O setuid=off \
-O checksum=sha256 \
-O compression=lz4 \
-O recordsize=1M \
-o ashift=12 \
-o autoexpand=off \
-o autoreplace=off \
-o comment="Main Photo Archive" \
-f \
    photos raidz1 \
/dev/disk/by-id/ata-ST10000DM0004_ZA20B89L \
/dev/disk/by-id/ata-ST10000DM0004_ZA20B8CJ \
/dev/disk/by-id/ata-ST10000DM0004_ZA20B97Q


cannot create 'photos': invalid feature '(null)'
```

This is with using the master version from github, as of, about half an hour ago...

```
localhost ~ # modinfo spl | head
filename:       /lib/modules/4.6.7B/extra/spl/spl.ko
version:        0.7.0-rc2
license:        GPL
author:         OpenZFS on Linux
description:    Solaris Porting Layer
srcversion:     BF45F2B8E8A961F56A146A9
depends:        zlib_deflate
vermagic:       4.6.7B SMP mod_unload modversions 

localhost ~ # modinfo zfs | head
filename:       /lib/modules/4.6.7B/extra/zfs/zfs.ko
version:        0.7.0-rc2
license:        CDDL
author:         OpenZFS on Linux
description:    ZFS
srcversion:     7B072A9EA7DD461E46A3786
depends:        spl,znvpair,icp,zunicode,zcommon,zavl
vermagic:       4.6.7B SMP mod_unload modversions 


localhost ~ # ls -l `which zpool`
-rwxr-xr-x 1 root root 528176 Dec 16 23:07 /usr/local/sbin/zpool

localhost ~ # ls -l /usr/local/lib/libnvpair.*
-rw-r--r-- 1 root root 602918 Dec 16 23:03 /usr/local/lib/libnvpair.a
-rwxr-xr-x 1 root root    998 Dec 16 23:03 /usr/local/lib/libnvpair.la
lrwxrwxrwx 1 root root     18 Dec 16 23:03 /usr/local/lib/libnvpair.so -> libnvpair.so.1.0.1
lrwxrwxrwx 1 root root     18 Dec 16 23:03 /usr/local/lib/libnvpair.so.1 -> libnvpair.so.1.0.1
-rwxr-xr-x 1 root root 355376 Dec 16 23:03 /usr/local/lib/libnvpair.so.1.0.1

localhost ~ # ls -l /usr/local/lib/libzpool.*
-rw-r--r-- 1 root root 15503702 Dec 16 23:06 /usr/local/lib/libzpool.a
-rwxr-xr-x 1 root root     1019 Dec 16 23:06 /usr/local/lib/libzpool.la
lrwxrwxrwx 1 root root       17 Dec 16 23:06 /usr/local/lib/libzpool.so -> libzpool.so.2.0.0
lrwxrwxrwx 1 root root       17 Dec 16 23:06 /usr/local/lib/libzpool.so.2 -> libzpool.so.2.0.0
-rwxr-xr-x 1 root root  7846216 Dec 16 23:06 /usr/local/lib/libzpool.so.2.0.0
```

This was also happening with a 0.7.0-rc1 release from October, which I was using until about an hour ago... because of this exact bug... which is still in the current version.

I've been creating pools with `-o version=28`, until today, when I though I'd see if the current version was, perhaps, not going to randomly corrupt the pool for some unknown reason.

**Comment by JuliaVixen** [comment]
OK, I think I figured it out...

I ran this through `strace`, and saw a bunch of this stuff:

```
open("/lib64/libnvpair.so.1", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libuutil.so.1", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libzpool.so.2", O_RDONLY|O_CLOEXEC) = 3
```

Those are all the old versions..

```
localhost ~ # ls -l /lib64/libzpool.so.2*
lrwxrwxrwx 1 root root      17 Jul  8 21:27 /lib64/libzpool.so.2 -> libzpool.so.2.0.0
-rwxr-xr-x 1 root root 5829136 Jul  8 21:27 /lib64/libzpool.so.2.0.0

localhost ~ # ls -l /lib64/libnvpair.so.1*
lrwxrwxrwx 1 root root     18 Jul  8 21:27 /lib64/libnvpair.so.1 -> libnvpair.so.1.0.1
-rwxr-xr-x 1 root root 354720 Jul  8 21:27 /lib64/libnvpair.so.1.0.1
```

It's not using `/usr/local/lib/` for some reason...

**Comment by JuliaVixen** [comment]
(I replaced the libraries in `/lib64/` and `zpool` works without error now.)
