### ISSUE TITLE
compile warnings in the module/icp/ modules

### ISSUE THREAD

**Issue by kernelOfTruth** [zfsonlinux/zfs#5041]
This might be meaningless right now since the other encryption parts are to be merged in the near future,

but I thought I'd nevertheless let you know:

```
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/icp/asm-x86_64/aes/aes_amd64.o: warning: objtool: aes_encrypt_amd64(): can't find starting instruction
  AS [M]  /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/icp/asm-x86_64/aes/aes_intel.o
  AS [M]  /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/icp/asm-x86_64/modes/gcm_intel.o
  AS [M]  /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/icp/asm-x86_64/sha1/sha1-x86_64.o
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/icp/asm-x86_64/aes/aes_intel.o: warning: objtool: rijndael_key_setup_enc_intel()+0x14e: call without frame pointer save/setup
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/icp/asm-x86_64/aes/aes_intel.o: warning: objtool: rijndael_key_setup_dec_intel()+0x0: call without frame pointer save/setup
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/icp/asm-x86_64/aes/aes_intel.o: warning: objtool: .text+0x20: return instruction outside of a callable function
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/icp/asm-x86_64/aes/aes_intel.o: warning: objtool: .text+0x77: return instruction outside of a callable function
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/icp/asm-x86_64/aes/aes_intel.o: warning: objtool: .text+0xb5: return instruction outside of a callable function
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/icp/asm-x86_64/aes/aes_intel.o: warning: objtool: .text+0xe0: return instruction outside of a callable function
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/icp/asm-x86_64/modes/gcm_intel.o: warning: objtool: gcm_mul_pclmulqdq(): can't find starting instruction
  AS [M]  /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/icp/asm-x86_64/sha2/sha256_impl.o
  CC [M]  /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/dsl_dir.o
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/icp/asm-x86_64/sha1/sha1-x86_64.o: warning: objtool: .text+0x10b3: can't decode instruction
  CC [M]  /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/dsl_pool.o
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/icp/asm-x86_64/sha2/sha256_impl.o: warning: objtool: .text+0x1307: can't find jump dest instruction at .text+0x12d8
```

additional compiler flags used

```
-Wformat-extra-args -Wall -Werror -Werror=format= -Werror=maybe-uninitialized
```

**Comment by tuxoko** [comment]
Need to add macro that does `push rbp; mov rsp rbp` when CONFIG_FRAME_POINTER

**Comment by behlendorf** [comment]
@tcaputi can you look in to these objtool warnings which were introduced by the icp.

**Comment by tcaputi** [comment]
Ill look at this tomorrow. Admittedly, assembly is not really something I'm great at. I was very thankful it just worked when I ported it over. I will try what @tuxoko has suggested.

**Comment by tcaputi** [comment]
I'm sorry, I've been a bit busy this past week and I will be this next week as well. I don't currently have a machine setup with `CONFIG_FRAME_POINTER` enabled either. @tuxoko if you think that you can quickly make the change, I would appreciate it a lot. Otherwise, I'll try to get to it when I can.

**Comment by behlendorf** [comment]
FRAME_BEGIN and FRAME_END exist for this purpose on x86.  But it appears it may take a little restructuring to use them correctly.  @ironMann may have some thoughts on this.

**Comment by ironMann** [comment]
@behlendorf I've cleared the warnings in PR #5872 
I also added linux specific SIMD code handling. I'm not sure how the current code does not break userspace when running AES-GCM, because ` _KERNEL` was not defined when invoking assembler in the icp module. 
I don't know how to get good testing coverage for this.

**Comment by tcaputi** [comment]
@ironMann 

> I'm not sure how the current code does not break userspace when running AES-GCM, because _KERNEL was not defined when invoking assembler in the icp module.

What are you referring to specifically? I don't believe any of the assembly code particularly cares if `_KERNEL` is defined or not (IIRC).

**Comment by ironMann** [comment]
@tcaputi It appers to me that [reg saving macros](https://github.com/zfsonlinux/zfs/blob/master/module/icp/asm-x86_64/aes/aes_intel.S#L185-L282) were not used, and the code was only protected by `kpreempt_disable()/kpreempt_enable() ` and not with `kernel_fpu_begin()/kernel_fpu_end()`.
So that thread could overwrite userspace XMM state.
