### ISSUE TITLE
(website) Please provide links to linux+ZFS rescue CDs

### ISSUE THREAD

**Issue by denizzzka** [zfsonlinux/zfs#5045]
It is very hard to find actual working ZFS rescue CD for newbies, expecially with Linux kernel

**Comment by denizzzka** [comment]
https://wiki.gentoo.org/wiki/User:Fearedbliss - Gentoo-based System Rescue CD

**Comment by behlendorf** [comment]
The Ubuntu 16.04 [live image](http://releases.ubuntu.com/16.04/) provides ZFS support.

**Comment by denizzzka** [comment]
Please don't close because website still doesn't have these links

**Comment by denizzzka** [comment]
> The Ubuntu 16.04 live image provides ZFS support.
Are you sure? Tried it (version 16.04.1) hour ago and it isn't find zfs kernel modules.

**Comment by behlendorf** [comment]
Reasonably sure, from Ubuntu 16.04.

```
$ uname -a
Linux host 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ dpkg -S /lib/modules/4.4.0-34-generic/kernel/zfs/zfs/zfs.ko 
linux-image-4.4.0-34-generic: /lib/modules/4.4.0-34-generic/kernel/zfs/zfs/zfs.ko
```

I've reopened the issue, perhaps someone could propose some text to add this to the FAQ.

**Comment by likewhoa** [comment]
The Gentoo Livedvd maintain by me supports latest ZFS and if you need a more recent version because the livedvd is outdated, you can simply emerge zfs on the livedvd to have it updated for you. http://get.gentoo.org

**Comment by kernelOfTruth** [comment]
@likewhoa in that case it's probably also good to document how to update it on the livedvd successfully,

so that as many people who might be dependent on it, can update it 

Thanks :)

**Comment by likewhoa** [comment]
@kernelOfTruth I didn't think that would be necessary as you expect a ZOL user would know the basics of using Gentoo Linux and updating modules in the kernel, but I would be happy to write a short explanation (in the ZOL wiki perhaps?) on how to update the ZFS kernel modules on the Gentoo Livedvd.

**Comment by kernelOfTruth** [comment]
@likewhoa yes, it's better to have the steps outlined, I don't doubt that the basics are there, but there could be also users who hadn't used Gentoo before (e.g. users of Fedora, Debian, Ubuntu, etc.).

In additiono to the Gentoo liveDVD and @fearedbliss ' SysRescCD there's also the Sabayon liveDVD which (to my knowledge) also should contain zfs modules (according to Sabayon_Linux_16.07_amd64_KDE.iso.pkglist that's currently 0.6.5.6)

**Comment by drescherjm** [comment]
I did not know you could modify / replace the kernel of the livedvd easily. I have messed with SysRescCD and the srm updating then recreating the iso.

**Comment by dasjoe** [comment]
@denizzzka @behlendorf Ubuntu 16.04 comes with ZFS kernel modules by default, although you need to install `zfsutils-linux` to get, well, the `zfs` and `zpool` utilities:

```
$ dpkg -L zfsutils-linux 
/.
/sbin
/sbin/zinject
/sbin/zhack
/sbin/mount.zfs
/sbin/fsck.zfs
/sbin/zpool
/sbin/zdb
/sbin/zstreamdump
/sbin/ztest
/sbin/zpios
/sbin/zfs
/etc
/etc/init.d
/etc/init.d/zfs-share
/etc/sudoers.d
/etc/sudoers.d/zfs
/etc/cron.d
/etc/cron.d/zfsutils-linux
/etc/default
/etc/default/zfs
/etc/zfs
/lib
/lib/systemd
/lib/systemd/system
/lib/systemd/system/zfs-mount.service
/lib/systemd/system/zfs-import-scan.service
/lib/systemd/system/zfs.target
/lib/systemd/system/zfs-import-cache.service
/lib/udev
/lib/udev/zvol_id
/lib/udev/vdev_id
/lib/udev/rules.d
/lib/udev/rules.d/69-vdev.rules
/lib/udev/rules.d/60-zvol.rules
/usr
/usr/sbin
/usr/sbin/arcstat.py
/usr/sbin/arc_summary.py
/usr/sbin/dbufstat.py
/usr/lib
/usr/lib/zfs-linux
/usr/lib/zfs-linux/scrub
/usr/lib/os-probes
/usr/lib/os-probes/10zvol-test
/usr/share
/usr/share/initramfs-tools
/usr/share/initramfs-tools/hooks
/usr/share/initramfs-tools/hooks/zdev
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/zfsutils-linux
/usr/share/bash-completion
/usr/share/bash-completion/completions
/usr/share/bash-completion/completions/zfs
/usr/share/doc
/usr/share/man
/usr/share/man/man8
/usr/share/man/man8/mount.zfs.8.gz
/usr/share/man/man8/zpool.8.gz
/usr/share/man/man8/zfs.8.gz
/usr/share/man/man8/zdb.8.gz
/usr/share/man/man8/vdev_id.8.gz
/usr/share/man/man8/fsck.zfs.8.gz
/usr/share/man/man8/zstreamdump.8.gz
/usr/share/man/man8/zinject.8.gz
/usr/share/man/man1
/usr/share/man/man1/zhack.1.gz
/usr/share/man/man1/ztest.1.gz
/usr/share/man/man1/zpios.1.gz
/usr/share/man/man5
/usr/share/man/man5/zpool-features.5.gz
/usr/share/man/man5/zfs-events.5.gz
/usr/share/man/man5/zfs-module-parameters.5.gz
/usr/share/man/man5/vdev_id.conf.5.gz
/usr/share/doc/zfsutils-linux
```

**Comment by kingneutron** [comment]
What I ended up doing is installing Ubuntu 14.04-64-LTS to a bootable 16GB USB3 thumbdrive for ZFS recovery environment; that way you can have scripts, editors, up-to-date (or custom) kernel, latest packages, and everything you need.  Just keep it updated every so often.  16.04 should work as well.

This is the page I have bookmarked for a ZFS-enabled live CD (System rescue CD), which is what I used before the USB3 solution:
http://ftp.osuosl.org/pub/funtoo/distfiles/sysresccd/

**Comment by rlaager** [comment]
For Ubuntu, I added some documentation to the root-on-ZFS HOWTO: https://github.com/zfsonlinux/zfs/wiki/Ubuntu-16.04-Root-on-ZFS#rescuing-using-a-live-cd

**Comment by DurvalMenezes** [comment]
Looks like the until-now-excellent Fearedbliss ISO has been abandomned: the files listed at the above URLs are stuck at ZFS 0.7.9 and were last updated more than 6 months ago :-/

What is the recommended ready-to-use Linux+ZFS recovery ISO?

**Comment by drescherjm** [comment]
I recently used the script of his to produce a 0.8.0-rc1 ISO but it did take a few steps to get a recent kernel since the aufs-sources ebuilds were old. Looking a few minutes ago I see these are now current.

**Comment by fearedbliss** [comment]
@drescherjm when updating the cd (And this only applies if you want to upgrade the kernel.. you dont have to upgrade the kernel, if you dont upgrade it, then you can just leave the existing kernel that you made in place (like the sources that I still have in my overlay), and then just recompile the modules). If you do upgrade the kernel (or if you are going to go with a new sysresccd, then make sure to get the patches that upstream is using):

https://sourceforge.net/p/systemrescuecd/code/ci/master/tree/portage-overlay/sys-kernel/std-sources/files/

in order for you to get the kernel config that the upstream kernel is using (before using that config as a basis for your own kernel that will eventually replace the one in the cd), you will need to boot the cd in a vm and then copy the .config file that's in the /root dir. I've searched the entire cd for the config and it doesnt exist, it dynamically generated after many many changes that the cd makes as it boots up.

**Comment by DurvalMenezes** [comment]
@drescherjm have you built an iso with an updated ZoL? could you please post a link to it?TIA

**Comment by drescherjm** [comment]
This probably should be discussed on the mailing list. Although at the moment I don't have time.
