### ISSUE TITLE
CentOS 6: zfs-release rpm not signed

### ISSUE THREAD

**Issue by markus-ermes** [zfsonlinux/zfs#5057]
I am trying to update zrfs using yum on a CentOS 6 system;

yum update responds with:

<SNIP>
Package zfs-release-1-5.el6.noarch.rpm is not signed

Doing a quick check with 
rpm -qpi zfs-release-1-5.el6.noarch.rpm | grep Signature
Signature   : (none)

Thank you for your help!

**Comment by behlendorf** [comment]
Fixed.  I've signed and updated the release package for el6.
