### ISSUE TITLE
Buffer I/O error on [zvol], lost async page writen (dmesg spam)

### ISSUE THREAD

**Issue by Celmor** [zfsonlinux/zfs#5065]
[Dmesg: https://pastebin.com/raw/FAncn8da](https://pastebin.com/raw/FAncn8da)

What I did shortly before and during which these errors started :
zfs mount /dev/zvol/VM/Games-part1 /media/game && cp /dev/zero > /media/game/zero; rm /media/game/zero/
zfs set compression=off VM/Games (2016-09-03.19:20:44)
cp /dev/zero > /media/game/zero; rm /media/game/zero
umount /media/game/zero
zfs rollback VM/Games@4 (2016-09-03.21:26:02)
mount /dev/zvol/VM/Games-part1 /mnt/zvol-Games
mount /dev/zvol/Data/Backup/tempSyncDisabled-part1 /mnt/temp1/ && cp something /mnt/temp1 &
zfs create -s Data/temp -V 10G (2016-09-03.22:58:11)
run a VM for a few minutes with VM/Win10Qemu and VM/Games zvols as its storage (qemu-system-x86_64 -drive file=/dev/zvol/VM/Win10Qemu,format=raw -drive file=/dev/zvol/VM/Games,if=virtio,format=raw ...)
sudo mkfs.ntfs /dev/zd48 & # "Initializing device with zeroes:" taking very long
killall -s KILL mkfs.ntfs
sudo fdisk -l /dev/zd48 # hanging

I've brought this up in the #zfsonlinux IRC chat on freenode and they suggested I file a bug report.
"Separate from it going unbearably slow, I'd argue that flooding dmesg with dropping writes is probably a problem, even if it's just indicating something needs suppression"

uname:
`Kernel: Linux Celmor-PC 4.4.13-1-MANJARO #1 SMP PREEMPT Wed Jun 8 09:21:59 UTC 2016 x86_64 GNU/Linux`

ZFS related Packages:

```
local/linux44-zfs 0.6.5.7-7 (linux44-extramodules)
    Kernel modules for the Zettabyte File System.
local/spl-utils 0.6.5.7-1 (manjarozfs)
    Solaris Porting Layer User-Mode utils
local/zfs-utils 0.6.5.7-1 (manjarozfs)
    User-Mode utils for the Zettabyte File System
```

zpool status:

```
  pool: Data
 state: ONLINE
  scan: resilvered 3.17T in 10h24m with 0 errors on Wed Aug 31 09:37:22 2016
config:

    NAME        STATE     READ WRITE CKSUM
    Data        ONLINE       0     0     0
      mirror-0  ONLINE       0     0     0
        Data2   ONLINE       0     0     0
        Data1   ONLINE       0     0     0

errors: No known data errors

  pool: VM
 state: ONLINE
status: Some supported features are not enabled on the pool. The pool can
    still be used, but some features are unavailable.
action: Enable all features using 'zpool upgrade'. Once this is done,
    the pool may no longer be accessible by software that does not support
    the features. See zpool-features(5) for details.
  scan: none requested
config:

    NAME                                       STATE     READ WRITE CKSUM
    VM                                         ONLINE       0     0     0
      ata-Crucial_CT512MX100SSD1_AAAAAAAAAAAA  ONLINE       0     0     0

errors: No known data errors

```

zfs list -t volume:

```
NAME                           USED  AVAIL  REFER  MOUNTPOINT
Data/Backup/tempSyncDisabled  63.8G   126G  63.8G  -
Data/temp                     1.32G   126G  1.32G  -
VM/Games                       211G   224G   210G  -
VM/Win10Qemu                  26.8G   224G  20.6G  -
```

symlinks for zvols:

```
/dev/zvol/VM/Games: symbolic link to ../../zd32
/dev/zvol/VM/Win10Qemu: symbolic link to ../../zd16
/dev/zvol/Data/temp: symbolic link to ../../zd48
/dev/zvol/Data/Backup/tempSyncDisabled: symbolic link to ../../../zd0
```

[ZPool properties](https://puu.sh/qYWHT/11e7a4e96a.txt)
[ZFS volumes properties](https://puu.sh/qYWRj/1b5c101df3.txt)
[PC Specs](https://pastebin.com/raw/LrpDurnD)

**Comment by mkovero** [comment]
Sounds awful lot like of #5118
