### ISSUE TITLE
Documentation for debian does not work: no debian-zfs package to install

### ISSUE THREAD

**Issue by schafdog** [zfsonlinux/zfs#5067]
I believe there is some error on this page. 

I am trying on testing but with sid repo (yes, not supported). 

After the update, I try: 

root@us3:/etc# apt-get install debian-zfs
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package debian-zfs is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'debian-zfs' has no installation candidate

Am I overlooking something?

**Comment by schafdog** [comment]
Ok the package was in jessie, which start the dkms build and fails. I thought there would be binaries for amd64?

**Comment by kpande** [comment]
please use [the zfs-discuss mailing list](http://list.zfsonlinux.org) for questions
