### ISSUE TITLE
Grsec build on Arch produces broken zavl module

### ISSUE THREAD

**Issue by sempervictus** [zfsonlinux/zfs#5069]
Just built a linux-grsec-4.7.2 Arch kernel (need to rebuild to have objtool in it), and the zfs-dkms-git packages.

Everything builds now, but the resulting zavl module can't be loaded with the grsec kernel:
```
[Wed Sep  7 03:25:43 2016] zavl: module is not compatible with the KERNEXEC 'or' method and RAP
```
Will look at Alpine's build to see how they deal with this, but if anyone has a solution, i'd love to know how to properly fix the sources for grsecurity builds.

**Comment by sempervictus** [comment]
Apparently this is a known issue - https://github.com/zfsonlinux/zfs/issues/4649.
How are the Archers and Gentooers out there handling this today?

**Comment by ironMann** [comment]
`zavl` is very straightforward module (compared to the rest of zfsonlinux). Real issue is that RAP and out-of-tree modules are not compatible.  You'll probably need to disable RAP feature of grsec to run zfs. See [here](https://bugs.gentoo.org/show_bug.cgi?id=581726#c2)

**Comment by behlendorf** [comment]
Closing, won't fix.  RAP and *binary* out-of-tree modules are not compatible, but since full source is available for ZFS this is something which the distribution might  be able to handle.
