### ISSUE TITLE
/usr/libexec/zfs/zfault.sh -c -v -t 5 fail (33)

### ISSUE THREAD

**Issue by plentystars** [zfsonlinux/zfs#507]
<pre>
destroying /dev/md0
/dev/md1
/dev/md2
/dev/md3

/dev/md:
Creating /dev/loop0 using /tmp/zpool-lo.XsSo0Znu
Creating /dev/md0 using /dev/loop0
Destroying /dev/md0
Destroying /dev/loop0
                                        raid0	raid10	raidz	raidz2	raidz3
1    soft write error                   Skip
2    hard write error                   Skip
3    all write errors                   Skip
4    soft read error                    Skip
5    hard read error                    Fail (33)
</pre>
uname -a 
<pre>
Linux fc16.ntel.local 3.1.6-1.fc16.x86_64 #1 SMP Wed Dec 21 22:41:17 UTC 2011 x86_64 x86_64 x86_64 GNU/Linux
</pre>
spl and compile from git clone

**Comment by behlendorf** [comment]
Closing.  The `zfault.sh` test script has been removed and replaced by the far more extensive ZFS Test Suite.

6bb24f4 Add the ZFS Test Suite
