### ISSUE TITLE
what is the really recommended zfs_arc_max and zfs_arc_min?

### ISSUE THREAD

**Issue by CDLuminate** [zfsonlinux/zfs#5077]
I found the following links:

https://github.com/zfsonlinux/zfs/issues/3677  
https://github.com/zfsonlinux/zfs/wiki/FAQ  

However still confused on how to choose values for `zfs_arc_max` and `zfs_arc_min`.
ZFS consumes nearly half of my laptop memory with the default `zfs_arc_max = 0`.

**Comment by gmelikov** [comment]
please use [the mailing list](http://list.zfsonlinux.org) for support requests, this is not a bug. thank you!
