### ISSUE TITLE
Ubuntu: mounting ZFS volumes will abort the boot process only *sometimes*, despite the error condition being present always

### ISSUE THREAD

**Issue by luca-ing** [zfsonlinux/zfs#5079]
### Observed on:
Ubuntu 16.04 machine with ZFS root, set up as described at https://github.com/zfsonlinux/zfs/wiki/Ubuntu-16.04-Root-on-ZFS (well, as of a few months ago).

### Observation:
Booting sometimes (about 50% of cases) aborts and drops to a root login. The rest of the time it boots up apparently without a hitch, but on inspection none of the volumes which make up the /var hierarchy are mounted.

There seems to always be a problem that my non-root ZFS volumes can't be mounted since their mountpoints are non-empty.

I had problems with booting which seemed related to ZFS a while ago and mucked about with mount options - I can't tell whether this mucking about was the cause of my problems,  or one of its effects.

### Expectation:
The system behaviour is always consistent. Either this problem is grave enough to interrupt booting, or it isn't.

### steps to reproduce:
unclear.

### additional info:

```
✘ ⚡ root@notebook  ~  zfs get mounted -r   
NAME                                   PROPERTY  VALUE    SOURCE
notebook                               mounted   no       -
notebook/ROOT                          mounted   no       -
notebook/ROOT/ubuntu-1                 mounted   no       -
notebook/ROOT/ubuntu-1@install         mounted   -        -
notebook/ROOT/ubuntu-1@ansible-ran     mounted   -        -
notebook/ROOT/ubuntu-1@x11-starts      mounted   -        -
notebook/ROOT/ubuntu-1@GUI-starts      mounted   -        -
notebook/ROOT/ubuntu-2                 mounted   yes      -
notebook/ROOT/ubuntu-2@initial         mounted   -        -
notebook/ROOT/ubuntu-2@GUI-runs-again  mounted   -        -
notebook/home                          mounted   yes      -
notebook/home/root                     mounted   no       -
notebook/var                           mounted   no       -
notebook/var/cache                     mounted   no       -
notebook/var/log                       mounted   no       -
notebook/var/nfs                       mounted   yes      -
notebook/var/spool                     mounted   no       -
notebook/var/tmp                       mounted   no       -
```

```
✘ ⚡ root@notebook  ~  zfs get mountpoint -r
NAME                                   PROPERTY    VALUE         SOURCE
notebook                               mountpoint  /             local
notebook/ROOT                          mountpoint  none          local
notebook/ROOT/ubuntu-1                 mountpoint  /             local
notebook/ROOT/ubuntu-1@install         mountpoint  -             -
notebook/ROOT/ubuntu-1@ansible-ran     mountpoint  -             -
notebook/ROOT/ubuntu-1@x11-starts      mountpoint  -             -
notebook/ROOT/ubuntu-1@GUI-starts      mountpoint  -             -
notebook/ROOT/ubuntu-2                 mountpoint  /             local
notebook/ROOT/ubuntu-2@initial         mountpoint  -             -
notebook/ROOT/ubuntu-2@GUI-runs-again  mountpoint  -             -
notebook/home                          mountpoint  /home         inherited from notebook
notebook/home/root                     mountpoint  /root         local
notebook/var                           mountpoint  /var          inherited from notebook
notebook/var/cache                     mountpoint  /var/cache    inherited from notebook
notebook/var/log                       mountpoint  /var/log      local
notebook/var/nfs                       mountpoint  /var/lib/nfs  local
notebook/var/spool                     mountpoint  /var/spool    inherited from notebook
notebook/var/tmp                       mountpoint  /var/tmp      inherited from notebook
```

```
✘ ⚡ root@notebook  ~  zfs get canmount -r                 
NAME                                   PROPERTY  VALUE     SOURCE
notebook                               canmount  on        local
notebook/ROOT                          canmount  off       local
notebook/ROOT/ubuntu-1                 canmount  off       local
notebook/ROOT/ubuntu-1@install         canmount  -         -
notebook/ROOT/ubuntu-1@ansible-ran     canmount  -         -
notebook/ROOT/ubuntu-1@x11-starts      canmount  -         -
notebook/ROOT/ubuntu-1@GUI-starts      canmount  -         -
notebook/ROOT/ubuntu-2                 canmount  on        local
notebook/ROOT/ubuntu-2@initial         canmount  -         -
notebook/ROOT/ubuntu-2@GUI-runs-again  canmount  -         -
notebook/home                          canmount  on        default
notebook/home/root                     canmount  on        default
notebook/var                           canmount  off       local
notebook/var/cache                     canmount  on        default
notebook/var/log                       canmount  on        default
notebook/var/nfs                       canmount  on        default
notebook/var/spool                     canmount  on        default
notebook/var/tmp                       canmount  on        default
```

**journalctl -xb:**
```
-- The start-up result is done.
Sep 08 06:31:20 notebook systemd[1]: Starting Import ZFS pools by device scanning...
-- Subject: Unit zfs-import-scan.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit zfs-import-scan.service has begun starting up.
Sep 08 06:31:20 notebook zpool[3586]: no pools available to import
Sep 08 06:31:20 notebook systemd[1]: Started Import ZFS pools by device scanning.
-- Subject: Unit zfs-import-scan.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit zfs-import-scan.service has finished starting up.
-- 
-- The start-up result is done.
Sep 08 06:31:20 notebook systemd[1]: Starting Mount ZFS filesystems...
-- Subject: Unit zfs-mount.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit zfs-mount.service has begun starting up.
Sep 08 06:31:20 notebook zfs[3589]: cannot mount '/': directory is not empty
Sep 08 06:31:20 notebook zfs[3589]: cannot mount '/root': directory is not empty
Sep 08 06:31:20 notebook zfs[3589]: cannot mount '/var/cache': directory is not empty
Sep 08 06:31:20 notebook zfs[3589]: cannot mount '/var/log': directory is not empty
Sep 08 06:31:20 notebook zfs[3589]: cannot mount '/var/spool': directory is not empty
Sep 08 06:31:20 notebook zfs[3589]: cannot mount '/var/tmp': directory is not empty
Sep 08 06:31:20 notebook systemd[1]: zfs-mount.service: Main process exited, code=exited, status=1/FAILURE
Sep 08 06:31:20 notebook systemd[1]: Failed to start Mount ZFS filesystems.
-- Subject: Unit zfs-mount.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit zfs-mount.service has failed.
-- 
-- The result is failed.
Sep 08 06:31:20 notebook systemd[1]: Dependency failed for ZFS startup target.
-- Subject: Unit zfs.target has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit zfs.target has failed.
-- 
-- The result is dependency.
Sep 08 06:31:20 notebook systemd[1]: zfs.target: Job zfs.target/start failed with result 'dependency'.
Sep 08 06:31:20 notebook systemd[1]: zfs-mount.service: Unit entered failed state.
Sep 08 06:31:20 notebook systemd[1]: zfs-mount.service: Failed with result 'exit-code'.
Sep 08 06:31:20 notebook systemd[1]: Reached target Local File Systems.
-- Subject: Unit local-fs.target has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit local-fs.target has finished starting up.
-- 
-- The start-up result is done.
Sep 08 06:31:20 notebook systemd[1]: Starting Create Volatile Files and Directories...
```

**Comment by loli10K** [comment]
It's almost certainly a race condition. You have both datasets `notebook` and `notebook/ROOT/ubuntu-2` with `canmount=on` and `mountpoint=/`, i don't think this is intentional.

**Comment by luca-ing** [comment]
Thanks for the lightening-quick help.

I suppose you're right. I thought I copy&pasted all commands from the wiki page when setting up the machine, but apparently not.
For that reason I was actually aware of this situation, but somehow convinced myself it was correct. Oh well.

BTW, might it be better to set the mountpoint for the root volume (`notebook`, in my case) to `none`? I remember finding this confusing when I read the instructions, and it's probably what made me not question this conflict.

I'll be leaving this issue open for now in case anyone wants to comment, and will close it after I resolve my issue if it's not already closed by then.

**Comment by loli10K** [comment]
@luca-ing i think the root dataset should have `canmount=off` as per `zpool create` command specified in section 2.3 of https://github.com/zfsonlinux/zfs/wiki/Ubuntu-16.04-Root-on-ZFS

```
# zpool create -o ashift=12 \
      -O atime=off -O canmount=off -O compression=lz4 -O normalization=formD \
      -O mountpoint=/ -R /mnt \
      rpool /dev/disk/by-id/scsi-SATA_disk1-part1
```

**Comment by deajan** [comment]
@luca-ing Did @loli10K remark solve your issue ?
If yes, please close the issue.

**Comment by deajan** [comment]
Indeed recent versions of ubuntu have switched to systemd and there are problems, especially between if you upgraded from a previous version. Did you have time to test ?

**Comment by luca-ing** [comment]
I re-installed my system from scratch, and have done about 10 reboots since, without the problem reoccurring.

Interestingly, I've reused my zpool, and only created a new root FS for my new installation; so my problem doesn't seem to be connected to the way ZFS is configured.

For the record: the previous installation had also been from scratch, and was used pretty conventionally. As far as I can tell, the issue appeared "out of thin air".
I've kept the old FS around in case someone would like to investigate.

I'm closing this issue.

**Comment by loli10K** [comment]
@luca-ing i'd like to understand the root cause of the problem, if you're willing to share the fs/pool. Now that ubuntu is officially shipping ZoL more users will eventually face this problem, if we can update the wiki before that it'd be great.

**Comment by behlendorf** [comment]
@rlaager can you comment on this.

**Comment by rlaager** [comment]
zfs set mountpoint=/mnt notebook/ROOT/your-old-fs
zfs mount notebook/ROOT/your-old-fs
cd /mnt
ls root var/cache var/log var/spool var/tmp

I suspect you have data in those directories. Once you redid the root filesystem, they are properly empty.

How you got into this state, I'm not sure. It could be related to the duplicate mountpoint at / messing something up. But I'm not at all sure about that.

**Comment by luca-ing** [comment]
I wrote an email to @loli10K offering access to the pool.

@rlaager your suspicion is correct.

The thing is, though, I removed these files and made sure that `zfs mount -a` worked as expected. They were recreated on the next reboot.

And yes, my mount hierarchy was initially incorrect (I probably didn't pay enough attention tho the wiki). But for one thing, it must have been incorrect for months before the failing boots happened, and for another, once the situation was corrected manually, it un-corrected itself on reboot.

**Comment by rlaager** [comment]
I can somewhat understand the stuff in /var. Perhaps if some service started too early and was writing there. But /root has me baffled.

What sort of contents did you find in those directories? Was it clearly related to some particular service?

**Comment by luca-ing** [comment]
I'm sorry, I was imprecise in my description; I eventually cleaned up /root and it stayed clean. Similarly /var/spool might have stayed clean once I cleaned it.

Remember I ran the system for an unknown length of time with /var improperly mounted. Only when booting started to fail did I notice something was amiss.

(This is really the second baffling thing: why did the boot process appear to throw an error only "sometimes". Perhaps there's a race inside the Ubuntu startup scripts somewhere).

The /var hierarchy was re-polluted on subsequent reboots however.

See here:
<pre>
root@notebook:/mnt# ls -l root var/cache var/log var/spool var/tmp
root:
total 0

var/cache:
total 1
drwxr-sr-x 2 man root 2 Sep 29 05:44 man

var/log:
total 5
-rw------- 1 root utmp    0 Sep 29 05:44 btmp
-rw-rw-r-- 1 root utmp 1536 Oct  1 07:34 wtmp

var/spool:
total 0

var/tmp:
total 0
</pre>

I appear to have cleaned /var/tmp already during my last, aborted rescue attempt, but I remember it contained a directory called `systemd-\<long random-seeming string\>`

Also:
<pre>
root@notebook:/mnt# cat var/log/wtmp 
~~~reboot4.4.0-38-generic���W�
                               ~~~reboot4.4.0-38-genericS��W�,
root@notebook:/mnt# eneric�^�WI�~~~reboot4.4.0-38-generic�J�WL~
</pre>

**Comment by rlaager** [comment]
Does this show anything interesting?

`sudo apt install acct`
`sudo dump-utmp /mnt/var/log/wtmp`

**Comment by luca-ing** [comment]
@rlaager thanks for looking into it. I'll run the commands you asked tomorrow morning before work and get back to you.

Also, you're welcome to inspect my pool if you like. I'm already in communication with @loli10K as to the best approach.

**Comment by luca-ing** [comment]
@rlaager As per your request:
<pre>
root@notebook:/mnt#  sudo dump-utmp /mnt/var/log/wtmp
reboot                          |~                               |2|~~  |    0|4.4.0-38-generic                                                                                                                                                                                                                                                |Thu Sep 29 05:43:59 2016
reboot                          |~                               |2|~~  |    0|4.4.0-38-generic                                                                                                                                                                                                                                                |Fri Sep 30 06:17:23 2016
reboot                          |~                               |2|~~  |    0|4.4.0-38-generic                                                                                                                                                                                                                                                |Sat Oct  1 08:59:08 2016
reboot                          |~                               |2|~~  |    0|4.4.0-38-generic                                                                                                                                                                                                                                                |Sat Oct  1 07:34:20 2016
</pre>

Unfortunately, doesn't seem interesting to me.

**Comment by rlaager** [comment]
This makes me wonder if systemd (or something) is logging an event at reboot, after /var etc. are unmounted, but with / still mounted.
