### ISSUE TITLE
dsl_prop_register() leaks a copy of the propname

### ISSUE THREAD

**Issue by tcaputi** [zfsonlinux/zfs#5082]
I found a memory leak when running zfs with the spl memory debugging enabled. `dsl_prop_register()` calls `dsl_prop_record_create()` which does a `spa_strdup()` of the propname. At module unload time, it seems that this is leaked. I have not yet found why this is the case. It looks like there is a corresponding `strfree()` in `dsl_prop_fini()`. It is also strange that the `dsl_prop_record_t` itself isnt reported as leaked.

Here is my debugging output from dmesg. It was basically produced by adding a dump_stack() to `spa_strdup()` where the memory leak was reported: [spa_strdup.txt](https://github.com/zfsonlinux/zfs/files/465173/spa_strdup.txt)

**Comment by dweeezil** [comment]
Thanks for tracking this down.  I had come across this leak, too, the last time I ran with memory debugging enabled.  The problem is that they're not freed correctly.  I'll post a PR shortly.
