### ISSUE TITLE
/sys/module/zfs/parameters how to change settings ? 

### ISSUE THREAD

**Issue by MasterCATZ** [zfsonlinux/zfs#5088]
root@aio:/sys/module/zfs/parameters# echo 25 > /sys/module/zfs/parameters/zio_taskq_batch_pct
bash: /sys/module/zfs/parameters/zio_taskq_batch_pct: Permission denied

any idea why as root user I can not change settings ? 

root@aio:/sys/module/zfs/parameters# modprobe zfs zio_taskq_batch_pct=25
root@aio:/sys/module/zfs/parameters# cat /sys/module/zfs/parameters/zio_taskq_batch_pct
75

Ubuntu 16 LTS 4.4.0-36-generic
how am I meant to change zfs parameters, I can barely use pc while its re-silvering 
ideally I wish their was a setting for zfs to only use 1x CPU core

**Comment by behlendorf** [comment]
By default this option is read-only, it may only be set at module load time.  It was set this way because it is only read during pool import.  Making a change after the pool is imported will have no effect.

```
$  ls -l /sys/module/zfs/parameters/zio_taskq_batch_pct
-r--r--r-- 1 root root 4096 Sep 12 10:05 /sys/module/zfs/parameters/zio_taskq_batch_pct
```

The following patch will make it writable but you must set it after module load and before pool import.

```diff
diff --git a/module/zfs/spa.c b/module/zfs/spa.c
index c7cfe6e..d76e011 100644
--- a/module/zfs/spa.c
+++ b/module/zfs/spa.c
@@ -6907,7 +6907,7 @@ module_param(spa_load_verify_data, int, 0644);
 MODULE_PARM_DESC(spa_load_verify_data,
        "Set to traverse data on pool import");
 
-module_param(zio_taskq_batch_pct, uint, 0444);
+module_param(zio_taskq_batch_pct, uint, 0644);
 MODULE_PARM_DESC(zio_taskq_batch_pct,
        "Percentage of CPUs to run an IO worker thread");
 
```

**Comment by MasterCATZ** [comment]
ok thanks , 

wherein ubuntu can I set my custom parameters ? 
ie) freebsd was /boot/loader.conf

**Comment by behlendorf** [comment]
Create an `/etc/modprobe.d/zfs.conf` file.

**Comment by A2116** [comment]
> 
> 
> By default this option is read-only, it may only be set at module load time. It was set this way because it is only read during pool import. Making a change after the pool is imported will have no effect.
> 
> ```
> $  ls -l /sys/module/zfs/parameters/zio_taskq_batch_pct
> -r--r--r-- 1 root root 4096 Sep 12 10:05 /sys/module/zfs/parameters/zio_taskq_batch_pct
> ```
> 
> The following patch will make it writable but you must set it after module load and before pool import.
> 
> ```diff
> diff --git a/module/zfs/spa.c b/module/zfs/spa.c
> index c7cfe6e..d76e011 100644
> --- a/module/zfs/spa.c
> +++ b/module/zfs/spa.c
> @@ -6907,7 +6907,7 @@ module_param(spa_load_verify_data, int, 0644);
>  MODULE_PARM_DESC(spa_load_verify_data,
>         "Set to traverse data on pool import");
> 
> -module_param(zio_taskq_batch_pct, uint, 0444);
> +module_param(zio_taskq_batch_pct, uint, 0644);
>  MODULE_PARM_DESC(zio_taskq_batch_pct,
>         "Percentage of CPUs to run an IO worker thread");
> ```

how we can apply this patch?
