### ISSUE TITLE
ZFS dracut module broken on fedora due to libgcc_s.so.1

### ISSUE THREAD

**Issue by bjencks** [zfsonlinux/zfs#5089]
Commit 61c73494394fc9de9283b3fd4f00bcdf4bd300a7 breaks dracut on my fedora 24 system, because gcc-config doesn't exist, and `/usr/lib/gcc/*/*/libgcc_s.so.1` doesn't exist. The symlink in `/usr/lib/gcc/*/*/` is called `libgcc_s.so`, and points to `/lib64/libgcc_s.so.1`.

**Comment by behlendorf** [comment]
@Calrama can you propose a patch to resolve this or I'm going to need to revert your 61c7349 from master.

**Comment by ryao** [comment]
@Calrama @behlendorf There are enough ways of detecting the existence of an executable that look correct, but are not, that it is easy to pick the wrong one. The fix is to replace `type` with `command -v`. That should make everything work as it is supposed to work.

**Comment by ryao** [comment]
@behlendorf #5092 fixes this.

**Comment by Calrama** [comment]
@behlendorf My apologies, I'll need to look more carefully in the future.
@ryao Thank you for fixing my mistake.

**Comment by bziller** [comment]
This still leaves the problem of the non existent `/usr/lib/gcc/*/*/libgcc_s.so.1` on fedora.
I can confirm this on fedora 23 where only `/usr/lib/gcc/x86_64-redhat-linux/5.3.1/libgcc_s.so` exists and no `libgcc_s.so.1` symlink.
Maybe just using `dracut_install /usr/lib/gcc/*/*/libgcc_s.so*` might be a solution?

**Comment by Calrama** [comment]
@bziller I have added that to @ryao's regression fix at https://github.com/Calrama/zfs/commit/776891d873b37831af0fa42d159b7571aa10f148, but I don't have a fedora system ready to test
@bjencks Could you test if https://github.com/Calrama/zfs/commit/776891d873b37831af0fa42d159b7571aa10f148 works on fedora?

**Comment by bjencks** [comment]
I just tested with the entire clause commented out, i.e. no `dracut-install anything/libgcc_s.so`, and my initramfs still included `/lib64/libgcc_s.so.1` and booted correctly. I don't know whether that's something ZFS can depend on, or due to some other non-guaranteed dependency I have.

@Calrama, that means your patch will work, in that it won't cause errors, but I won't be able to tell if it's actually doing what's necessary.

**Comment by Calrama** [comment]
@bjencks That is weird, could you run dracut with `--debug` to see where `/lib64/libgcc_s.so.1` gets included for you without the clause? Because I know it won't be for me on Funtoo (and I'd pose also Gentoo), I need that as otherwise `lsinitrd ... | grep libgcc_s` will be empty (so it's necessary at least on those systems).

**Comment by bjencks** [comment]
@Calrama Sorry for the delay. A number of binaries explicitly link to `libgcc_s.so.1` (`ldd` shows it), so dracut can trace those dependencies and include it.
```
/usr/lib/udev/scsi_id
/usr/lib/udev/ata_id
/usr/lib/udev/zvol_id # This is provided by ZFS, why doesn't this happen on Gentoo?
/usr/lib/systemd/systemd-udevd
/usr/lib/systemd/systemd # And a bunch more systemd binaries
/usr/sbin/mount.zfs
/usr/sbin/zpool
/usr/sbin/dhclient
/usr/sbin/zfs
/usr/bin/findmnt
/usr/bin/kmod
```
And a bunch more.

**Comment by Calrama** [comment]
@bjencks Thanks, could you try out https://github.com/Calrama/zfs/commit/e4cb5bc462c68bbc0b666b69d06d1e2f4dcb1f19? This *should* detect if `zpool` gets directly linked to `libgcc_s.so.1` and only apply the fix if it is not.

**Comment by behlendorf** [comment]
Could you open a PR with this fix once it has been tested.

**Comment by bjencks** [comment]
Tested, looks good. Commented on the commit.

**Comment by Calrama** [comment]
@bjencks Thank you for testing.
@behlendorf Can do, one question though: My current master includes @ryao's commit from https://github.com/zfsonlinux/zfs/issues/5089#issuecomment-246437077 cherry-picked and several "dirty" commits (trying to get it right) and would most likely conflict with whatever is currently being done over at https://github.com/zfsonlinux/zfs/pull/5092 (or the new PR mentioned there) by him. Should I still open a PR as is?

**Comment by behlendorf** [comment]
@Calrama you're going to want to create a new branch off master.  Then apply the needed fixes to that branch and squash things in to a single commit to make it easier to review.  I don't think there's any need to preserve @ryao's change as a separate commit since it's so tiny.  Use that new branch to open a PR and we'll ask @ryao for a review to make sure it's OK for Gentoo.

**Comment by Calrama** [comment]
@behlendorf Thank you for the pointers, done and opened https://github.com/zfsonlinux/zfs/pull/5138
@ryao Could you review my proposed fix (which is based on your initial one): https://github.com/zfsonlinux/zfs/pull/5138
