### ISSUE TITLE
el6 + kmod-zfs + elrepo kernel

### ISSUE THREAD

**Issue by dmaziuk** [zfsonlinux/zfs#5090]
I've a centos 6 box running elrepo kernel 3.10. After swithcing from dkms to kmod-zfs:

[root@exocet modules]# rpm -q -l kmod-zfs
/lib/modules/2.6.32-573.26.1.el6.x86_64
/lib/modules/2.6.32-573.26.1.el6.x86_64/extra
/lib/modules/2.6.32-573.26.1.el6.x86_64/extra/zfs
/lib/modules/2.6.32-573.26.1.el6.x86_64/extra/zfs/avl
/lib/modules/2.6.32-573.26.1.el6.x86_64/extra/zfs/avl/zavl.ko
/lib/modules/2.6.32-573.26.1.el6.x86_64/extra/zfs/nvpair
/lib/modules/2.6.32-573.26.1.el6.x86_64/extra/zfs/nvpair/znvpair.ko
/lib/modules/2.6.32-573.26.1.el6.x86_64/extra/zfs/unicode
/lib/modules/2.6.32-573.26.1.el6.x86_64/extra/zfs/unicode/zunicode.ko
/lib/modules/2.6.32-573.26.1.el6.x86_64/extra/zfs/zcommon
/lib/modules/2.6.32-573.26.1.el6.x86_64/extra/zfs/zcommon/zcommon.ko
/lib/modules/2.6.32-573.26.1.el6.x86_64/extra/zfs/zfs
/lib/modules/2.6.32-573.26.1.el6.x86_64/extra/zfs/zfs/zfs.ko
/lib/modules/2.6.32-573.26.1.el6.x86_64/extra/zfs/zpios
/lib/modules/2.6.32-573.26.1.el6.x86_64/extra/zfs/zpios/zpios.ko

Not sure what you could do, maybe the rpm could check `uname` pre-install and abort?

**Comment by behlendorf** [comment]
Make sure you follow the proceedure described in the [Switching from DKMS to kABI-tracking kmod](
https://github.com/zfsonlinux/zfs/wiki/RHEL-%26-CentOS#switching-from-dkms-to-kabi-tracking-kmod) section of the wiki.

**Comment by dmaziuk** [comment]
My running kernel is `3.10.103-1.el6.elrepo.x86_64`

**Comment by behlendorf** [comment]
@dmaziuk I see.  Then that's just not something we support with the kmod packages.  You can try the el7 repository which provides kmod packages for 3.10.0 el7 kernels.  However, if they're not using the exact same kernel the kABI may be different and you may have unresolved symbols.

You can always locally build kmod packages for your kernel with the `--with-spec=redhat` configure option.  Just make sure you apply it to both the SPL and ZFS packages.

```
./configure --with-spec=redhat
make rpms

**Comment by dmaziuk** [comment]
Yeah, I know, that's why I said "not sure what you could do". This is an FYI, more than anything -- perhaps add a warning to "switching from dkms to kabi"?
