### ISSUE TITLE
CentOS6 kmod-spl-0.6.5.7-1.el6.x86_64 requires spl, which requires spl-kmod

### ISSUE THREAD

**Issue by jesschang** [zfsonlinux/zfs#5100]
Trying to install el6 kmod based spl and zfs rpms but ran into a chicken-and-egg issue:
1. Installing kmod-spl-0.6.5.7-1.el6.x86_64.rpm failed:  
   Processing Dependency: spl = 0.6.5.7 for package: kmod-spl-0.6.5.7-1.el6.x86_64
2. Installing spl-0.6.5.7-1.el6.x86_64.rpm failed:
   Processing Dependency: spl-kmod = 0.6.5.7 for package: spl-0.6.5.7-1.el6.x86_64
3. Checking "rpm -qp --provides kmod-spl-0.6.5.7-1.el6.x86_64.rpm":
   kernel-modules >= 2.6.32-573.26.1.el6.x86_64
   spl-kmod = 0.6.5.7-1.el6
   kmod-spl = 0.6.5.7-1.el6
   kmod-spl(x86-64) = 0.6.5.7-1.el6

Is kmod-spl supposed to replace spl-kmod?  And, anyone else has seen this issue before?

**Comment by gmelikov** [comment]
0.6.5.8 released, try it and open issue if needed.
