### ISSUE TITLE
DKMS build issues on Linux 4.7.x on Fedora 24

### ISSUE THREAD

**Issue by seriu** [zfsonlinux/zfs#5104]
Gotten the following build errors out of DKMS on Fedora 24 with the latest 2 kernel updates. Seems it's looking for a mutex that doesn't exist, is this some quirk that came in with 4.7.x or is something terribly wrong with my system? (both equally possible)

[zfs-build-error-4.7.2-201.fc24.x86_64.txt](https://github.com/zfsonlinux/zfs/files/472059/zfs-build-error-4.7.2-201.fc24.x86_64.txt)
[zfs-build-error-4.7.3-200.fc24.x86_64.txt](https://github.com/zfsonlinux/zfs/files/472060/zfs-build-error-4.7.3-200.fc24.x86_64.txt)

**Comment by deajan** [comment]
AFAIK, kernes 4.7 & 4.8 are fully supported by 0.6.5.8 and later only.
0.6.5.8 was released a couple of days ago and rpm packages should come out shortly.

**Comment by seriu** [comment]
Well, that certainly helps address that problem, glad to know it was just on my end :)
