### ISSUE TITLE
RPMs built from the current git tree no longer include git revision information in their RPM release number

### ISSUE THREAD

**Issue by siebenmann** [zfsonlinux/zfs#5105]
Normally RPMs built from the development git repository get RPM versions like '-0.6.5-440_ge1f80bf'; this is the ZFS version 0.6.5, plus a git revision derived RPM release number, here '440_ge1f80bf'. This is useful but more importantly it insures that RPM tools see that successive git commits are different RPM versions and so you can easily upgrade from one to another.

Right now this doesn't work. If you build ZFS from the repository currently, RPMs get versions of '0.7.0-rc1' (version 0.7.0 plus release rc1); there is no git revision information included any more. The direct cause of this is that `configure` runs `git describe` in a way that can't find the starting tag (the `--match` argument). At the moment, the full command run is  `git describe --match=zfs-0.7.0`; the --match argument is `${ZFS_META_NAME}-${ZFS_META_VERSION}`. Unfortunately the actual tag in the git repo is `zfs-0.7.0-rc1` so `git describe` fails with 'fatal: No names found, cannot describe anything'.

It's not clear to me how best to fix this. The `META` file has `rc1` as the Release: value so you could pull it from there. But previous versions (eg for 0.6.5) have the Release as `1` while the git tag is just `zfs-0.6.5`, so blindly appending `${ZFS_META_RELEASE}` in the `git describe` command is clearly not correct all the time. Maybe the correct answer is to ignore ZFS_META_RELEASE if it's '1' and use it otherwise? But that feels like a hack (and potentially fragile).

**Comment by behlendorf** [comment]
I recently noticed this myself.  For the reasons you mentioned what I think want is for it to ignore the most recent rc tags.  This way when 0.7.0-1 is tagged it'll be newer than all existing 0.6.5-x and 0.7.0-rcX tags.  It would be great if you could propose a fix.

**Comment by siebenmann** [comment]
If I'm understanding this right, I don't think it's possible to do this with the current design of META and I don't think it's necessary in general as RPM will see '0.7.0-1' as more recent than '0.7.0-rc1'. As far as I can see, the search for the starting git tag for `git describe` has to be based on the `Version` and `Release` from META unless you want to add extra information; I can't see a sensible way to derive any other tag name.

Given that the base tag to search for has to be derived from `Version`, the only thing I can think of is to include the `Release` information in the tag name in `config/zfs-meta.m4` if and only if it's not equal to `1`. Always including `Release` in the tag name to search for would require changing (future) tag names from eg `zfs-0.7.0` to `zfs-0.7.0-1`, which seems less than ideal.

**Comment by behlendorf** [comment]
> I don't think it's necessary in general as RPM will see '0.7.0-1' as more recent than '0.7.0-rc1'

In general I agree, this is the most important case to get right.  And this shouldn't have any impact on most end users since I'm planning to only generate RPMs for tagged releases.  But it still would be nice for developers to not to break the existing automatic versioning behavior on a branch.

What do you think of the following trivial change.  It updates the logic to look for either a $META_VERSION or $META_VERSION-$META_RELEASE tag to use as the match point.  The result is the additional `git describe` information will still get appended to the release field.  Depending on how smart rpm is at interpreting the release field this may work as before.  But I haven't manually verified this.

```
spl-0.7.0-rc1_3_gcb81c0c.src.rpm
```


```diff
diff --git a/config/spl-meta.m4 b/config/spl-meta.m4
index 0561fbb..fbfaec4 100644
--- a/config/spl-meta.m4
+++ b/config/spl-meta.m4
@@ -63,6 +63,14 @@ AC_DEFUN([SPL_AC_META], [
                        if test -n "${_release}"; then
                                SPL_META_RELEASE=${_release}
                                _spl_ac_meta_type="git describe"
+                       else
+                               _match="${SPL_META_NAME}-${SPL_META_VERSION}-${S
+                               _alias=$(git describe --match=${_match} 2>/dev/n
+                               _release=$(echo ${_alias}|cut -f3- -d'-'|sed 's/
+                               if test -n "${_release}"; then
+                                       SPL_META_RELEASE=${_release}
+                                       _spl_ac_meta_type="git describe"
+                               fi
                        fi
                fi
 
```

**Comment by siebenmann** [comment]
I think that this works, and as far as I know RPM handles the version to version upgrades fine.

(I build ZFS and SPL RPMs this way for a succession of git commits and I've never had a problem upgrading from one version to another. If you're curious, the `rpmdev-vercmp` program (from `rpmdevtools`) can be used to check out what RPM will think of various version comparisons. It uses the actual underlying code in the RPM shared library, via the Python bindings.)

**Comment by behlendorf** [comment]
Thanks for the `rpmdev-vercmp` tip, thanks a lot easier than actually building real packages to do the testing.  I've opened zfsonlinux/spl#572 and #5140 with the above proposed fix for this.  @siebenmann if you could review and test this that would be great.

**Comment by siebenmann** [comment]
Belatedly: this works for me for both SPL and ZFS, and it appears to generate exactly the `git describe` output I expect (at least for SPL, which is easy to see by hand because it had only one commit between now and my most recent build).

**Comment by behlendorf** [comment]
@siebenmann thanks for the additional confirmation.  Using `rpmdev-vercmp` I was able to convince myself this worked like we wanted it too and I wanted to get this fixed in the master branch.  Definitely let me know if you run in to problems again.
