### ISSUE TITLE
kmod-zfs conflicts with zfs-dkms

### ISSUE THREAD

**Issue by dmaziuk** [zfsonlinux/zfs#5106]
I'm posting this in case others come looking.

It's a minor annoyance, due to `zfs-release-1-3` RPM from two weeks ago shipping with `zfs` repo enabled and `zfs-kmod` one disabled. I believe shipping with both enabled will get rid of the error: on all centos 7 hosts w/ `kmod-zfs` I get
```
Failed to check for updates with the following error message: 
Failed to build transaction: kmod-zfs-0.6.5.7-1.el7.centos.x86_64 requires zfs = 0.6.5.7
kmod-zfs conflicts with zfs-dkms-0.6.5.8-1.el7.centos.noarch
kmod-spl-0.6.5.7-1.el7.centos.x86_64 requires spl = 0.6.5.7
kmod-spl conflicts with spl-dkms-0.6.5.8-1.el7.centos.noarch
```

**Comment by behlendorf** [comment]
This is by design, these packages do conflict.  If you're using the kind packages you should enable just the kind repo and disable the dkms repo.

**Comment by dmaziuk** [comment]
Yes, but if both repos are enabled, yum is picking the `kmod-` packages and ignoring `-dkms` ones. No errors.

**Comment by behlendorf** [comment]
That may resolve the warning, but I wouldn't suggest depending on that behavior.  You might run in to the problems if one repository gets updated but not the other.  I'd expect yum/dnf to install the newest package from either repository which could lead to problems.

The recommended solution is to just enable either the dkms or kmod packages.  But thanks for filing this issue so others are aware of this.

**Comment by brian-lamb-software-engineer** [comment]
yes thank you, and i firmly believe i had already disabled the dkms, so cant understand why the error.  thanks for the lead, ill try to find what packages are enabled.

**Comment by MynaITLabs** [comment]
FYI, (for future reference)
`depmod: ERROR: fstatat(4, zavl.ko): No such file or directory`
Might be a sign of link references pointing to files that no longer exist. Check subdirectories under
`/usr/lib/modules` .
