### ISSUE TITLE
Illumos/OpenZFS commit tracker (in-depth look)

### ISSUE THREAD

**Issue by kernelOfTruth** [zfsonlinux/zfs#5111]
I'm listing a few commits here which need a more deeper look into the ZFS changes from Illumos/OpenZFS to get it right and are not yet merged to ZoL source:
- https://github.com/illumos/illumos-gate/commit/1fdcbd00c9cbac286b5f92e08877e8cb3c448420 6874 rollback and receive need to reset ZPL state to what's on disk

this one's really important since it can break clone, rollback, receive handling - leading to ENOSPC, quota and other issues

_When we do a clone swap (caused by "zfs rollback" or "zfs receive"), the ZPL doesn't completely reload the state from the DMU; some values remain cached in the zfsvfs_t._
(https://www.illumos.org/issues/6874)

(which e.g. diverges due to 3558fd73b5d863304102f6745c26e0b592aca60a "Prototype/structure update for Linux" from February 2011)
- https://github.com/illumos/illumos-gate/commit/0f7643c7376dd69a08acbfc9d1d7d548b10c846a 7090 zfs should improve allocation order and throttle allocations

has quite several rejects/mismatches and also needs some deeper look than for the usual small changes

**Comment by gmelikov** [comment]
I think it's obsolete, now we have a [tracker](http://build.zfsonlinux.org/openzfs-tracking.html) for it.
