### ISSUE TITLE
zvol slow on overwrites

### ISSUE THREAD

**Issue by mheubach** [zfsonlinux/zfs#5114]
Hello,

I think I either hit a bug or a basic misunderstanding. In a testing environment I get good write performance when writing to a zvol for the first time. All subsequent writes are becoming terribly slow.
A closer look reveals that there are a lot of read operations going on when overwriting a zvol.

My pool is a striped mirror of 6 sas drives. I have a 10GB file of arbitrary data which I copy with ddrescue to the zvol. ZFS is 0.6.5.6 on Ubuntu 16.04.

`zfs create -V 100G -o volblocksize=64k testpool/testvol
ddrescue /root/ddfile /dev/zvol/testpool/testvol -f`

zpool iostat -v 5 in a second session shows mainly something like this:

`                               capacity     operations    bandwidth
pool                        alloc   free   read  write   read  write

---

testpool                    6.49G  1.35T      0  4.90K      0   293M
  mirror                    2.16G   462G      0  1.68K      0   100M
    scsi-35000c500100c3a73      -      -      0    842      0  99.8M
    scsi-35000c5002639c333      -      -      0    846      0   100M
  mirror                    2.16G   462G      0  1.60K      0  95.4M
    scsi-35000c500100c418f      -      -      0    822      0  97.7M
    scsi-35000c50010358383      -      -      0    802      0  95.4M
  mirror                    2.17G   462G      0  1.62K      0  97.3M
    scsi-35000c500103584f3      -      -      0    829      0  98.2M
    scsi-35000c50026395057      -      -      0    821      0  97.3M

---

`

If I run ddrescue for a second time the zvol slows down and I can see read activity on the zvol:

`                               capacity     operations    bandwidth
pool                        alloc   free   read  write   read  write

---

testpool                    9.13G  1.35T    420    419  23.5M  19.5M
  mirror                    3.04G   461G    106    135  5.94M  6.24M
    scsi-35000c500100c3a73      -      -     52     63  2.96M  6.24M
    scsi-35000c5002639c333      -      -     53     63  2.98M  6.24M
  mirror                    3.04G   461G    166    140  9.18M  6.77M
    scsi-35000c500100c418f      -      -     99     67  5.40M  6.77M
    scsi-35000c50010358383      -      -     66     66  3.78M  6.77M
  mirror                    3.04G   461G    147    142  8.40M  6.44M
    scsi-35000c500103584f3      -      -     97     61  5.54M  6.45M
    scsi-35000c50026395057      -      -     49     62  2.87M  6.45M

---

`

This is reproducible. First writes are fast second writes to the same blocks are slow. I can delete the zvol and recreate it - always the same. If I use snapshots and create a snapshot immediately after creating the zvol I can just rollback the zvol and have the same story. First writes are fast second writes to same blocks are slow.
If I rerun ddrescue with e.g. opos=20G on a zvol which already became slow I have a fast write again. However if I overwrite the data on the same position it is slow again.
What really amazes me is that there is so much reading going on which is the reason for the slow writes. But I don't now why that is and how to stop it.

This only happens when writing directly into the zvol. If I create an ext4 filesystem on the zvol and mount it, I can copy and overwrite my 10GB file as many times as I like it is always fast and there is nearly no reading going on.

I also tested this with Ubuntu 14.04 and ZFS 0.6.5.3 and PVE (Proxmox) ZFS 0.6.5.7 - it's all the same although there are differences in overall performance.

So what is happening here? Does anyone have an idea?

Best regards
Manfred

**Comment by loli10K** [comment]
@mheubach i think you may be hitting this issue: https://github.com/zfsonlinux/zfs/issues/361

Could you try running ddrescue forcing its blocksize to be the same as the target ZVOL (`--sector-size=64k`)?

**Comment by mheubach** [comment]
If I do this the writing is initially faster and the reading starts later. But anyway it starts reading and therefore slowing down writing after a while.

**Comment by behlendorf** [comment]
This is absolutely because ZFS is a CoW filesystem and the problem is described in #361.  The effect is mitigated somewhat when there's a filesystem mounted on the volume because it will be batching it's IO in to larger chunks.

I'd be interested to hear what kind of results you get when testing with the [0.7.0-rc1 ](
https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.7.0-rc1) release candidate.  Commit 755065f3dce1123eac03e2b25c81647026b8e49b significantly improved the prefetch logic which may help your ddrescue workload.

**Comment by mheubach** [comment]
ok - I have 0.7.0-rc1 now.
My newly created zpool is again a stripe of 6 mirrored sas drives (3x 2)
The zvol has a blocksize of 128k
ddrescue is run with the default sector size of 512

overwriting the vol with new (different) data is now much faster (was about 15 - 30M with 0.6.5):

```
              capacity     operations     bandwidth 
pool        alloc   free   read  write   read  write
----------  -----  -----  -----  -----  -----  -----
pool1       9.67G  1.35T    617  1.21K  76.6M   132M
  mirror    3.22G   461G    206    405  25.7M  43.5M
    sdb         -      -     98    201  12.2M  21.7M
    sdd         -      -    108    203  13.4M  21.8M
  mirror    3.22G   461G    205    412  25.4M  44.0M
    sde         -      -    110    204  13.8M  22.0M
    sdf         -      -     94    207  11.6M  22.0M
  mirror    3.22G   461G    204    416  25.5M  44.3M
    sdg         -      -     69    208  8.68M  22.2M
    sdh         -      -    134    208  16.8M  22.2M
----------  -----  -----  -----  -----  -----  -----
```

writing to a newly created zvol looks like this:

```
----------  -----  -----  -----  -----  -----  -----
              capacity     operations     bandwidth 
pool        alloc   free   read  write   read  write
----------  -----  -----  -----  -----  -----  -----
pool1       10.7G  1.35T      0  4.53K      0   570M
  mirror    3.57G   460G      0  1.43K      0   180M
    sdb         -      -      0    734      0  90.2M
    sdd         -      -      0    734      0  90.1M
  mirror    3.56G   460G      0  1.55K      0   196M
    sde         -      -      0    798      0  98.3M
    sdf         -      -      0    793      0  97.8M
  mirror    3.57G   460G      0  1.54K      0   194M
    sdg         -      -      0    782      0  96.4M
    sdh         -      -      0    791      0  97.5M
----------  -----  -----  -----  -----  -----  -----
```

So there is definitely a big improvement in performance for these workloads
