### ISSUE TITLE
Improve RHEL updating to zfs 0.6.5.8 instructions

### ISSUE THREAD

**Issue by deajan** [zfsonlinux/zfs#5115]
Shortly before 0.5.6.8 release, zfs-release package has been updated to v1-3.el7.
When updating this package, the old /etc/yum.repos.d/zfs.repo is kept and the new one is written to /etc/yum.repos.d/zfs.repo.rpmnew

Old repo file contains old archive.zfsonlinux.org urls instead of download.zfsonlinux.org.
As a result, yum update won't update zfs to version 0.6.5.8.

It might be valuable to add a word about zfs.repo.rpmnew file for RHEL / CentOS / Fedora on the wiki.

**Comment by ahmgithubahm** [comment]
Me too!  :-)  Was about to open a new issue to say that 0.6.5.8 still hadn't appeared in the EL6 repo when I found this one.  Can archive not be made a CNAME for download, to fix this at the repo end?

thanks
