### ISSUE TITLE
Systemd doesn't activate the pool after upgrade to 0.6.5.8

### ISSUE THREAD

**Issue by henryx** [zfsonlinux/zfs#5123]
On Fedora 23, after upgrade from 0.6.5.7 to 0.6.5.8 the pool doesn't activate. Problem is located in two causes:
- Unit files are disabled.
- Existence of /etc/zfs/zpool.cache file.

In particular, the second problem emerges after enabling the zfs-import-scan.service unit file. A `systemctl status zfs-import-scan.service` report this:

```
Condition: start condition failed at Sat 2016-09-17 14:21:12 CEST; 6s ago
           ConditionPathExists=!/etc/zfs/zpool.cache was not met

Sep 17 14:17:06 alice.wonderland.home systemd[1]: Started Import ZFS pools by device scanning.
Sep 17 14:21:12 alice.wonderland.home systemd[1]: Started Import ZFS pools by device scanning.
```

**Comment by behlendorf** [comment]
You'll want to reset the presets as described in the release notes:

https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.6.5.8

**Comment by stapler117** [comment]
I had the same issue as @henryx and resetting the presets like @behlendorf said fixed my problem.

**Comment by henryx** [comment]
Currently I've solved "by hand". What leaves me perplexed, however, it he message of `systemctl status zfs-import-scan.service`. Can reset of presets solve it?

**Comment by deajan** [comment]
Reset of presets won't solve this.
As far as i understand, zfs-import-scan supposes that zfs-import-cache doesn't have any cache info.
You should run either import scan or import cache service.
Please correct me if I'm wrong :)

**Comment by behlendorf** [comment]
@deajan yes you're right.  One of these methods needs to be enabled, resetting the presets will enable the zfs-import-cache service which does presume your cache file contains a pool.  If that's not going to be the case for your configuration enable the scan service instead and disable the cache service.
