### ISSUE TITLE
Non-bootable system after removing cache disk

### ISSUE THREAD

**Issue by nickcrabtree** [zfsonlinux/zfs#5125]
I have a physical server running Ubuntu 16.04 with a zfs root file system, installed following the instructions at https://github.com/zfsonlinux/zfs/wiki/Ubuntu-16.04-Root-on-ZFS

I installed the bootloader as per instructions:

5.5b For UEFI booting, install GRUB:
grub-install --target=x86_64-efi --efi-directory=/boot/efi \
      --bootloader-id=ubuntu --recheck --no-floppy
The system has been running fine for three months, with several reboots (mainly caused by power cuts).

The root pool is a three way mirror:

NAME                                                                STATE     READ WRITE CKSUM
rpool                                                               ONLINE       0     0     0
  mirror-0                                                          ONLINE       0     0     0
    ata-SAMSUNG_HM500JI_S1WFJ90S818624-part1                        ONLINE       0     0     0
    ata-ST3250820AS_5QE5BVW5-part1                                  ONLINE       0     0     0
    ata-GB0250C8045_9SF0R2RD-part1                                  ONLINE       0     0     0
Originally I also had a hot-spare included in the pool. This morning, I needed the hot spare for use in another server which had a failed device, so I used zpool remove to remove the hot spare from the system, powered down, and physically removed the spare.

Now the server won't boot.

I've tried selecting all the three remaining physical disks to boot from but no joy.

At present, I have rebooted using a live CD. Following the early steps in the installation instructions above, I can see all the zfs pools, so the data is all there. I think the next step might be to chroot into this zpool but am not sure how to do so given the different ROOT file systems etc.

In a Solaris system, the boot information is applied to all disks in a root pool, so that boot integrity is assured even if one of the disks dies. Is this not the case with ZFS on Linux?

**Comment by rincebrain** [comment]
We'd need to see what the error output is - is it not finding a bootloader on any disk, or are you booting only to get an error about mounting the root filesystem, or ...?

Those instructions don't seem to specify an explicit disk when you install for EFI mode, so I would guess that, unless you have explicit EFI partitions on all the disks in the mirror, it only installed to whichever disk had an EFI partition mounted at /boot/efi, which would seem to have been your "hot spare".

I would suspect that one or more things might need updates to understand the notion of keeping multiple EFI partitions in sync to boot from any of them, but to be fair, if my hypothesis is right, what happened above would have bitten you for any RAID system on EFI, not just ZFS.

Apparently the "correct way" (ugh) of doing this is to, indeed, create distinct FAT32 /boot/efi partitions on every disk, make sure they're identical, and add distinct UEFI boot entries for each of them, which those instructions almost certainly wouldn't have any hooks to do.

**Comment by nickcrabtree** [comment]
Following the motherboard manufacturer's logo, there was just a small white blinking horizontal line at the top left of the screen - I don't think it could find a bootloader anywhere.

I have solved the problem by re-running the grub installation to each of the disks as @rincebrain mentions. Extracting the relevant parts of the installation instructions and correctly mounting the root file system in a chroot environment turned out to be non-trivial; details are here http://askubuntu.com/questions/826209/re-initialise-grub-for-non-bootable-uefi-zfs-16-04-installation/826613#826613 

I think at minimum in the installation instructions should cover the process of creating a /boot/efi partition on each disk and installing the bootloader to it.

**Comment by rlaager** [comment]
"Later, install GRUB to all the disks. This is trivial for MBR booting; the UEFI equivalent is currently left as an exercise for the reader."

The best approach here (thanks Mason Loring Bliss!) is to create the UEFI partition as a metadata=0.90 format mirror. With the superblock at the end, the UEFI firmware will think of it as a FAT filesystem, but the Linux install will see it as a RAID device, keeping everything in sync.

**Comment by rlaager** [comment]
Closing. There's a reasonable chance I'll be updating the HOWTO soon to use the metadata=0.90 approach, but regardless, there's no need to keep this open.
