### ISSUE TITLE
Poor cache performance

### ISSUE THREAD

**Issue by severach** [zfsonlinux/zfs#5128]
Arch Linux
Installed with scripts at (https://github.com/severach/ArchLinuxScripts)

0.7.0 has poor performance. Performance is fine for disk reads but it acts as if all the ARC caches are non functional. I run a test program once to get the cache loaded up and repeat to reuse the cache. Here are the second run performances where all data should be pulled from the cache:

0.7.0: 800 records per second.
0.6.5.8: 40000 records per second.

0.7.0 is the same speed on both runs. On the first run 0.6.5.8 starts at 800 records per second and speeds up as more of the file is cached. The second run runs the whole file at max speed.

Data file size: 100MB
free and arcstat.py are run after the second run.

```
% uname -srm
Linux 4.7.4-1-ARCH x86_64
% pacman -Qs zfs-linux
local/spl-linux-git 0.7.0_rc1_r3_gcb81c0c_4.7.4_1-1 (archzfs-linux-git)
local/spl-utils-linux-git 0.7.0_rc1_r3_gcb81c0c_4.7.4_1-1 (archzfs-linux-git)
local/zfs-linux-git 0.7.0_rc1_r21_g9ea9e0b_4.7.4_1-1 (archzfs-linux-git)
local/zfs-utils-linux-git 0.7.0_rc1_r21_g9ea9e0b_4.7.4_1-1 (archzfs-linux-git)
# arcstat.py                        :(
    time  read  miss  miss%  dmis  dm%  pmis  pm%  mmis  mm%  arcsz     c
20:25:59     0     0      0     0    0     0    0     0    0    94M   15G
# free -h
              total        used        free      shared  buff/cache   available
Mem:            31G        500M         30G        1.6M        681M         30G
Swap:            0B          0B          0B
```
```
% uname -srm
Linux 4.7.4-1-ARCH x86_64
% pacman -Qs zfs-linux
local/spl-linux 0.6.5.8_4.7.4_1-1 (archzfs-linux)
local/spl-utils-linux 0.6.5.8_4.7.4_1-1 (archzfs-linux)
local/zfs-linux 0.6.5.8_4.7.4_1-1 (archzfs-linux)
local/zfs-utils-linux 0.6.5.8_4.7.4_1-1 (archzfs-linux)
# arcstat.py
    time  read  miss  miss%  dmis  dm%  pmis  pm%  mmis  mm%  arcsz     c
20:39:03     0     0      0     0    0     0    0     0    0   864M   15G
# free -h
              total        used        free      shared  buff/cache   available
Mem:            31G        1.2G         29G        1.6M        619M         29G
Swap:            0B          0B          0B
```
```
 # zpool status
  pool: zfsdata
 state: ONLINE
  scan: resilvered 1.12M in 0h0m with 0 errors on Thu Apr 30 01:16:09 2015
config:

        NAME          STATE     READ WRITE CKSUM
        zfsdata       ONLINE       0     0     0
          mirror-0    ONLINE       0     0     0
            zfsdata1  ONLINE       0     0     0
            zfsdata2  ONLINE       0     0     0
        cache
          zfsl2arc    ONLINE       0     0     0

errors: No known data errors
```

**Comment by dweeezil** [comment]
I think the compressed ARC broke the ARC under ZoL.  I suspect a porting problem given how much the ZoL ARC code has wandered from the upstream.  Trivial tests before-and-after the compressed ARC show that it appears to be the problem.

**Comment by dweeezil** [comment]
For the time being, ```modprobe zfs zfs_arc_meta_strategy=0``` will work around the problem.  Some of the new code isn't playing well with the ZoL-specific balanced metadata eviction.

**Comment by severach** [comment]
It works.

**Comment by kernelOfTruth** [comment]
@dweeezil so that's the explanation why the ARC size would grow that conservatively ?

even during heavy usage it would never grow beyond approx. 6 GB in size with a set limit of e.g. 10 GB
