### ISSUE TITLE
Hang on access to zfs filesystem since 0.6.5.5

### ISSUE THREAD

**Issue by claunia** [zfsonlinux/zfs#5147]
Hi,

Since updating to 0.6.5.5 one of my ZFS filesystems has become inaccesible.

ls /mountpoint hangs indefinitely, without any kind of error message or dmesg.

Failure still happens on 0.7.0-rc1.

Downgrading to 0.6.5.4 allows access to the filesystem.
Issue is not pool related, zpool and zfs commands work perfectly.
Sending the filesystem to another pool reproduces the fail.
Creating other filesystem on the same pool does not exhibit the fail.
It is the only filesystem on several pools I have with this failure.
zpool history only shows imports, scrubs and exports.
Scrub detects not a single failure.

> claunia@zeus ~ $ sudo zfs get all osrepo
> NAME    PROPERTY              VALUE                   SOURCE
> osrepo  type                  filesystem              -
> osrepo  creation              sáb abr 19  3:50 2014  -
> osrepo  used                  1,48T                   -
> osrepo  available             336G                    -
> osrepo  referenced            1,48T                   -
> osrepo  compressratio         1.20x                   -
> osrepo  mounted               no                      -
> osrepo  quota                 none                    default
> osrepo  reservation           none                    default
> osrepo  recordsize            128K                    default
> osrepo  mountpoint            /Volumes/osrepo         local
> osrepo  sharenfs              off                     default
> osrepo  checksum              on                      default
> osrepo  compression           gzip-9                  local
> osrepo  atime                 on                      default
> osrepo  devices               on                      default
> osrepo  exec                  on                      default
> osrepo  setuid                on                      default
> osrepo  readonly              off                     default
> osrepo  zoned                 off                     default
> osrepo  snapdir               hidden                  default
> osrepo  aclinherit            restricted              default
> osrepo  canmount              on                      default
> osrepo  xattr                 on                      default
> osrepo  copies                1                       default
> osrepo  version               5                       -
> osrepo  utf8only              on                      -
> osrepo  normalization         formD                   -
> osrepo  casesensitivity       insensitive             -
> osrepo  vscan                 off                     default
> osrepo  nbmand                off                     default
> osrepo  sharesmb              off                     default
> osrepo  refquota              none                    default
> osrepo  refreservation        none                    default
> osrepo  primarycache          all                     default
> osrepo  secondarycache        all                     default
> osrepo  usedbysnapshots       0                       -
> osrepo  usedbydataset         1,48T                   -
> osrepo  usedbychildren        295M                    -
> osrepo  usedbyrefreservation  0                       -
> osrepo  logbias               latency                 default
> osrepo  dedup                 off                     local
> osrepo  mlslabel              none                    default
> osrepo  sync                  standard                default
> osrepo  refcompressratio      1.20x                   -
> osrepo  written               0                       -
> osrepo  logicalused           1,77T                   -
> osrepo  logicalreferenced     1,77T                   -
> osrepo  filesystem_limit      none                    default
> osrepo  snapshot_limit        none                    default
> osrepo  filesystem_count      none                    default
> osrepo  snapshot_count        none                    default
> osrepo  snapdev               hidden                  default
> osrepo  acltype               off                     default
> osrepo  context               none                    default
> osrepo  fscontext             none                    default
> osrepo  defcontext            none                    default
> osrepo  rootcontext           none                    default
> osrepo  relatime              off                     default
> osrepo  redundant_metadata    all                     default
> osrepo  overlay               off                     default

**Comment by tuxoko** [comment]
> casesensitivity insensitive

Are you using Linux 4.7+?
If so this is same as #5124

**Comment by claunia** [comment]
Mmm most probably yes I updated zfs at the same time as going to 4.7.0 and error is still happening on 4.7.4. I'll follow the other thread, sorry for duplicate didn't relate to kernel version.
