### ISSUE TITLE
ZFSonLinux doesn't work/build anymore since Jessie 8.6 upgrade

### ISSUE THREAD

**Issue by thorsten-gehrig** [zfsonlinux/zfs#5149]
Hi
i updated my jessie (dist-upgrade) and now my ZFS didn't work anymore.
If i try to build 
apt-get install spl-dkms
spl:
Running module version sanity check.
Error! Module version 0.6.5.7-5-jessie for spl.ko
is not newer than what is already found in kernel 3.2.0-4-amd64 (0.6.5-62_g16fc1ec).
You may override by specifying --force.

splat.ko:
Running module version sanity check.
Error! Module version 0.6.5.7-5-jessie for splat.ko
is not newer than what is already found in kernel 3.2.0-4-amd64 (0.6.5-62_g16fc1ec).
You may override by specifying --force.

Loading the ZFS
server:~# modprobe -v zfs
insmod /lib/modules/3.2.0-4-amd64/updates/dkms/zfs.ko 
modprobe: ERROR: could not insert 'zfs': Invalid argument

Is there any hint how to build the correct SPL and ZFS with the latest Debian 8.6??

Kind regards
Thorsten

**Comment by rincebrain** [comment]
It seems like what's happening for you is that you're running a git build of ZoL (as evidenced by the module version 0.6.5-##_g[commit]), and trying to install a stable release on top of it.

You should probably remove that version before trying to install a stable release on top of it - I'd expect apt to have complained if the modules were installed using a Debian package, so I'd guess you built+installed them by hand.

**Comment by ffrediani** [comment]
There you go:

apt clean
apt update
apt purge zfs*
apt remove spl dkms spl-dkms
apt autoremove
add-apt-repository --remove ppa:zfs-native/stable

apt install zfsutils-linux
apt install spl-dkms

reboot -n
