### ISSUE TITLE
Memory leaks reported in ZFS with SPL Kmem Debugging On

### ISSUE THREAD

**Issue by tcaputi** [zfsonlinux/zfs#5151]
While running some tests for the ZFS Encryption patch with spl kmem debugging on, I found a few memory leaks that exist in the current upstream/master (commit 160987b5). These can be reproduced with the following commands:
- `multilist_create()`

```
modprobe zfs
modprobe -r zfs
```

Result from spl kmem debugging:

```
[12426.656717] address          size  data             func:line
[12426.656720] ffff8803f8309a00 512   01000000083003ff multilist_create:82
[12426.656723] ffff8803c44e7c00 512   01000000084e03ff multilist_create:82
```
- `sa_add_layout_entry()` and `receive_read_record()`

```
zfs create pool/std
echo "The quick brown fox jumps over the lazy dog." > /pool/std/file1
sync
zfs snapshot pool/std@snap1
zfs send pool/std@snap1 | zfs recv pool/recv
```

Result from spl kmem debugging:

```
[12426.656717] address          size  data             func:line
[12426.656724] 0000000000000010 0                      sa_add_layout_entry:410
[12426.656725] 0000000000000010 0                      sa_add_layout_entry:410
[12426.656727] 0000000000000010 0                      receive_read_record:2650
[12426.656728] 0000000000000010 0                      receive_read_record:2650
[12426.656729] 0000000000000010 0                      receive_read_record:2650
```

**Comment by behlendorf** [comment]
I've proposed a fix for the multilist leak which is straight forward, but I haven't looked in the others closely.  

Once these are resolved what you do think about enabling kmem debugging by default and adding a check after the ZFS Test Suite run verifying that nothing was leaked.

**Comment by tcaputi** [comment]
That would probably be a good idea. My only concern is that the buildbot tests currently take ~ 3 or 4 hours to run as is (with a lot of the zfs-tests still being disabled). Maybe if we had one machine that ran the tests with kmem debugging while the others ran normally that would be better since we could check for big failures faster and worry about leaks afterwards.

**Comment by tuxoko** [comment]
Can we add kmemleak and kasan to buildbot?

**Comment by behlendorf** [comment]
Since it requires a custom kernel we wouldn't be able to add to every TEST builder since they use the distribution provided kernels.  But we absolutely could add a new TEST builder with a custom kernel with this functionality.  How would you want it to work?  Just clear the log at the beginning of each build step and dump the log at the end?

**Comment by tuxoko** [comment]
Yes, that should do it. Also we should probably built from latest stable kernel, otherwise we always claim to support the latest version but then find out something's not right.

**Comment by behlendorf** [comment]
The kernekl.org builders do always build against the latest kernel but you're right they don't actually test it.  That would be a nice addition.

**Comment by behlendorf** [comment]
These leaks have been resolved and a kmemleak enabled builder added to help catch any future memleaks on the kernel side at review time.
