### ISSUE TITLE
Standard Userspace Executables Throw General Protection Faults During Tests

### ISSUE THREAD

**Issue by tcaputi** [zfsonlinux/zfs#5156]
There are now 2 open pull requests against the current upstream/master that have exhibited some strange behavior on the Amazon SIMD build slave. While running the buildbot tests, standard userspace applications begin segfaulting. In my experience, this usually means that some memory in the kernel module is being double freed after it is already allocated to a new proccess or the kernel module is overwriting memory it does not own.

Here are the 2 pull requests that are exhibiting the issue (one of which makes very minimal changes). In the first one, sudo starts throwing general protection faults in ld.so. The second throws general protection faults in wget:

http://build.zfsonlinux.org/builders/Amazon%202015.09%20x86_64%20SIMD%20%28TEST%29/builds/1817
http://build.zfsonlinux.org/builders/Amazon%202015.09%20x86_64%20SIMD%20%28TEST%29/builds/1796

**Comment by behlendorf** [comment]
The first one you've listed is particularly interesting because we've barely just loaded the spl and splat kernel modules when it occurs.  And none of the zfs kernel modules will have ever been installed on this new VM.  If this was caused by a kernel double free it was caused by something in either the spl or splat modules which happened at module load time.

**Comment by tcaputi** [comment]
I was unable to reproduce the issue by doing `modprobe splat; modprobe -r splat` in a tight loop. Still trying to figure out a reliable way to reproduce the issue. It also happened a little while ago (September 19th) on one of my test machines, but I was doing a lot of debugging at the time and thought it was a failure in my new code.

**Comment by ironMann** [comment]
one [more](http://build.zfsonlinux.org/builders/Amazon%202015.09%20x86_64%20SIMD%20%28TEST%29/builds/1866)

I never load splat, and I've never seen this in local testing on native, kvm, or vbox setups.

**Comment by behlendorf** [comment]
For the purposes of automated testing I've disabled the splat tests in the buildbot.  There's really no point is running these tests repeatedly anyway if there aren't SPL changes or new kernels.  That should eliminate these annoying testing failures.  Adding the following line to the commit comment will enable the splat test for the PR.

```
TEST_SPLAT_SKIP="no"
```

**Comment by behlendorf** [comment]
This appears to have been largely resolved by zfsonlinux/spl@0d267566650d89bde8bd5ec4665749810d5bafc7.  I'll keep an eye on the buildbot and reopen this issue if it's in fact not resolved.
