### ISSUE TITLE
zfs-dracut seems broken on fedora 24

### ISSUE THREAD

**Issue by wphilips** [zfsonlinux/zfs#5157]
I have a configuration with the root filesystem on a zfs filesystem.
/boot is also in a zfs filesystem and I boot using a recent grub. 
Up til a few days ago this was all working with fedora22. 
While upgrading first to fedora 23 and then to fedora24 In  encountered
all kinds of problems with dracut (mainly while using dkms installs).
So I finally decided to to compile the latest zfsonlinux master, building 
rpms and using those. However, this also has problems.

The problem is that booting fails with mount-zfs complaining about 
the special device "ZFS=zfs/ROOT/fedora" not being found.

In the end I devised a workaround (only for my confuration) which allowed
me to boot by adding the lines 
ZFS_DATASET="zfs/ROOT/fedora"
ZFS_POOL="zfs"
in mount-zfs.sh

This workaround allows booting. I mention it because it  helps to delimit the problem.
Specifying 
 root=ZFS=zfs/ROOT/fedora 
is typically what is advised in howto's and seems to be what people use on fedora and centos.
It also worked for me in the past.

Howeverm according to what I see in zfs-mount.sh, I think it is impossible that this
would still work:
ZFS_DATASET is cleared at the start of the script and remains unset  for the rest
of the script. As a result ZFS_POOL is never set. The main pool is never imported
and all that remains is a big fight between the annoyed user and systemd+dracut
to see who gives up first.

I assume that this is a bug?
Is it possible to make specifying a kernel command line parameter possible again?
Specifically it would help fedora+dkms.

One of the alternative solutions I tried was to set a bootfs parameter on a zpool?
However, this seems to be impossible (at least on my pool):
zpool set bootfs=zfs/ROOT/fedora zfs
cannot set property for 'zfs': operation not supported on this type of pool

Suggestions on the preferred way to configure dracut are welcome.

Versions:
 zfs HEAD detached at 70cc394
spl  master            8acfb2b 
name -a
Linux daria.mynet 4.7.4-200.fc24.x86_64 #1 SMP Thu Sep 15 18:42:09 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

cat /proc/cmdline
BOOT_IMAGE=/boot/@/vmlinuz-4.7.4-200.fc24.x86_64 ro boot=zfs root=ZFS=zfs/ROOT/fedora rd.shell

**Comment by zfs-fan** [comment]
> Up til a few days ago this was all working with fedora22.
> While upgrading first to fedora 23 and then to fedora24 In encountered

Aha! So it's not just me and my setup. Exact same story here; several hosts, no problem since late 2013 with incremental upgrades from Fedora18 up to 22, but fails to mount root when upgrading snap/clone of 22 to 23 or 24:

![dsc_0037](https://cloud.githubusercontent.com/assets/996337/18826902/139f57be-83d0-11e6-8fe0-6576a017a7a4.jpg)

> root=ZFS=zfs/ROOT/fedora
I notice from the dracut script that this may have changed to root=ZFS:zfs/ROOT/fedora
(colon, not eq, after the ZFS keyword)
-- but I may be wrong, as any way it does not work; it just fails in a different and maybe even worse way, with a halt that needs a hard reset:

![dsc_0035](https://cloud.githubusercontent.com/assets/996337/18826949/64d51a56-83d0-11e6-8732-7379a4cbcf19.jpg)

But notice i imports and mounts just fine if I execute or source the script
 set -x ; . /usr/lib/dracut/hooks/mount/98-mount-zfs.sh
manually from the initrd emergency prompt:

![dsc_0043](https://cloud.githubusercontent.com/assets/996337/18827044/e280dc56-83d0-11e6-8114-8b021d4b28c8.jpg)

**Comment by sparksh** [comment]
Same symptoms on Fedora 24 with zfs-dkms. This method worked for me:

1) Set the bootfs property in the pool:

    zpool set bootfs=zfs/ROOT/fedora

2) Eliminate the "root=ZFS=zfs/ROOT/fedora ro" clause entirely in /etc/grub2.cfg

Hopefully these workarounds will be temporary...

**Comment by behlendorf** [comment]
@Rudd-O could you look at this Fedora / Dracut issue.

**Comment by Rudd-O** [comment]
I will take a peek.

**Comment by Rudd-O** [comment]
I could not reproduce it on my touchstone build system with Fedora 24.  Dracut does the right thing here:

```
dracut: //lib/dracut-lib.sh@64(info): echo '<30>dracut: ZFS: Set zfs:seed_staging_24_RPMs/ROOT/os as bootfs.'
```

In my platform it says this:

```
[   57.051831] dracut: ZFS: sysroot.mount absent, mounting root with mount-zfs.sh
```

HOWEVER, there WAS a change that broke a thing:

```
systemctl --system --show -p LoadState sysroot.mount
[   57.038362] systemctl[534]: Unknown operation sysroot.mount.
```

That makes no sense.  I will fix it and report back.

**Comment by Rudd-O** [comment]
Haha, I'm an idiot, I put that bug there myself.  See  https://github.com/zfsonlinux/zfs/commit/d402c18dd60124525b253b27c5018f54a030928d for the first time that `--show` was introduced.  `--show` obviously does not work.

I will send a PR soon.

**Comment by Rudd-O** [comment]
Testing again with PR https://github.com/zfsonlinux/zfs/pull/5204 .  In the meantime, do not yet merge it as it may cause other bugs to shake up.

**Comment by Rudd-O** [comment]
Yep, I found another issue.  That issue is systemctl not being able to check that the `sysroot.mount` file exists.  I have devised a different mechanism to check for what we want — whether the generator was created and will do its job.

**Comment by Rudd-O** [comment]
(Right now I hate my life a bit.  But at least my Jenkins instance speaks to me when it blows up!)

**Comment by Rudd-O** [comment]
I'm still working on this.  I needed to make some automation improvements to zfs-fedora-installer in order to have a reliable testing bench, but other than that, it looks like I may have the solution to the issue.

**Comment by Rudd-O** [comment]
I have the reliable testing bench now (it's an EC2 instance).  I'm testing both the hostonly and the nohostonly initrds and, so far, the hostonly initrd boots fine.  Will keep everyone posted.

**Comment by Rudd-O** [comment]
OK, on Fedora 24, I cannot reproduce the boot issue, with or without the hostonly initrd.

Here is the command line used to create the test case:

```
sudo /opt/zfs-fedora-installer/staging/install-fedora-on-zfs \
  --use-prebuilt-rpms=rpms/RELEASE=24/  \
  --no-cleanup --use-branch=staging  \
  --releasever=24  \
  --yum-cachedir=/mnt/jenkins/yumcache/24  \
  --host-name=seed.dragonfear  \
  --pool-name=seed_staging_24_RPMs  \
  --vol-size=6144  \
  --swap-size=256  \
  --root-password=seed  \
  --luks-password=seed  \
  '--luks-options=-c aes-xts-plain64:sha256 -h sha256 -s 512 --use-random --align-payload 4096'  \
  root.img
```

**Comment by behlendorf** [comment]
@Rudd-O when you're happy with the proposed fix can you refresh the patches in #5204 with the final version rebased on master.

**Comment by Rudd-O** [comment]
I am getting some VERY ODD errors while testing this.  If I run eight of these builds at the same time, GUARANTEED that several of them will fail during yum install, with extraneous "cpio unpacking of archive failed" error messages, leaving broken systems behind.  I do not see any CKSUM or other I/O errors on the zpool outputs.  I am going to do the mechanic thing and begin taking away things one by one, to try and triangulate what could be causing that issue.

Of course, I fear it may be ZFS itself.  That could always be the case.

**Comment by Rudd-O** [comment]
I think it's not the storage, it's the yum / dnf cache.  Checking now...

**Comment by Rudd-O** [comment]
I've crossed the hurdles I needed to cross and I have discovered that, with the patches outlined above, Fedora 20, 22, 23 and 24 boot fine with both the hostonly initrd and the nonhostonly initrd.  I cannot reproduce the problem anymore.

I will rebase now.

**Comment by Rudd-O** [comment]
Patch rebased.

**Comment by Rudd-O** [comment]
Now's a good time as any time to discuss running `install-fedora-on-zfs` on your build bots — soon in its master branch it will incorporate the ability to check fully automatically whether a particular install (a pair of spl and zfs branches) will successfully boot from ZFS atop LUKS.  The only problem is that running it within Amazon EC2 can be dog slow, around 10 minutes per run, because it needs to use QEMU to actually boot the images, twice (once for the test with no-hostonly initrd, and once for the test with hostonly initrd).

**Comment by Rudd-O** [comment]
@wphilips ZFS_DATASET is set here: https://github.com/Rudd-O/zfs/blob/cd57b11c3de8a07f120bb75dc1204c05f8231721/contrib/dracut/90zfs/mount-zfs.sh.in#L43 .  The preparation to parse the variable is done here: https://github.com/Rudd-O/zfs/blob/cd57b11c3de8a07f120bb75dc1204c05f8231721/contrib/dracut/90zfs/parse-zfs.sh.in#L35

**Comment by Rudd-O** [comment]
@wphilips the fix may be in.

See: https://github.com/zfsonlinux/zfs/pull/5204

To test: clone my repo of zfs, checkout the branch in question on that pull request, build RPMs of everything, install them (including the zfs-dracut RPM), and then:

```
dracut --regenerate-all -fv
```

Then reboot.  Tell me if you experience problems.

Alternatively, to test-drive the changes in a VM without potentially hosing your running system:

* Clone https://github.com/Rudd-O/zfs-fedora-installer to a local folder.
* In that folder, run `sudo ./install-fedora-on-zfs --use-branch=staging --root-password=password --chown=$USER --chgrp=$USER root.img`.
* Boot the `root.img` image using QEMU now; you can find information on how to do that online.  You want to use `qemu-system-x86_64` in `accel=kvm` mode or else it will be horribly slow.

In any case, if you need to collect debugging information:

* https://fedoraproject.org/wiki/How_to_debug_Systemd_problems
* https://freedesktop.org/wiki/Software/systemd/Debugging/
