### ISSUE TITLE
[RFC] ZFS 0.6.5.9 proposed patch stack

### ISSUE THREAD

**Issue by kernelOfTruth** [zfsonlinux/zfs#5163]
https://github.com/zfsonlinux/zfs/commit/db707ad094431a8869123cb2389a4b768d5583a0 OpenZFS 6940 - Cannot unlink directories when over quota

posting at least that patch here since for quota users it could be pretty important

**Comment by claunia** [comment]
d5b897a6a1da2f031a708fd267b4de2cc9b7a6e2 deadlock on case insensitive filesystems seems quite important also

**Comment by tuxoko** [comment]
@claunia 
Use this version to prevent conflict.
https://gist.github.com/tuxoko/aca3da99949a603a393818f8945a5010

**Comment by kernelOfTruth** [comment]
https://github.com/zfsonlinux/zfs/commit/b58986eebf3c47c946393da4b968ee33edaea99e Use large stacks when available

(https://github.com/zfsonlinux/zfs/issues/4880#issuecomment-251714980 Reduced performance for 0.6.5 in virtualized environment and others )

**Comment by behlendorf** [comment]
Tagged 0.6.5.9.
