### ISSUE TITLE
Ubuntu 16.04.1 Install zfsutils-linux Panic Error, endless loop

### ISSUE THREAD

**Issue by Magnum26** [zfsonlinux/zfs#5173]
Fresh install of Ubuntu 16.04.1, installed all updates / upgrades for system before installing zfsutils-linux. The install processes all the way to Reached target Swap then has a PANIC error and loops endlessly.

There is a zpool there already (was) with 3TB of data on it. This only happened after the system upgrade, so I reinstalled the boot drive / OS to see if it was just a issue with that, clearly it's an issue with the zfsutils-linux package for 16.04.1

Package version installed zfsutils-linux 0.6.5.6-0ubuntu12

![q12cdzk](https://cloud.githubusercontent.com/assets/3380011/18868459/2df47be6-84a0-11e6-9416-1dcff4b84cd1.jpg)

**Comment by rlaager** [comment]
See also: https://bugs.launchpad.net/ubuntu/+source/zfs-linux/+bug/1628553

**Comment by tlvenn** [comment]
I have a very similar issue and I am totally stuck without being able to access my data ... :(

The only difference I have is the PANIC error is slightly different:
> PANIC: blkptr at ffff88021a214000 has invalid CHECKSUM 10

My data zpool is not used to boot the system so it's easy to just reboot to try something else.

Is there any chance that my slightly different panic error has been seen before and can be resolved easily ?

**Comment by bunder2015** [comment]
was your pool created on illumos or bsd? #5216

**Comment by tlvenn** [comment]
The pool was originally created on illumos but I was able to import it on Ubuntu 16.04 just fine and it worked fine for quite sometimes. Then I added a cache device to the raid-z and shortly after I got the PANIC.

**Comment by tlvenn** [comment]
I was kinda hoping it was just related to that cache disk, so I unplugged that SSD and tried to import the pool with the -m option, same thing is happening sadly.

**Comment by behlendorf** [comment]
@tlvenn the PANIC indicates that a small bit of metadata used to store one of the blocks in your pool was somehow damaged but stored with a valid checksum.  You can instruct ZFS to try and continue in spite of the unrecoverable damage by setting the module option `zfs_recover=1` prior to importing the pool.  I'd suggest first importing the pool read-only, `zpool import -o readonly <pool>`, and making a copy of the data.  From there you can try importing the pool read-write.

**Comment by tlvenn** [comment]
Hi @behlendorf, thanks a lot for your reply, I was able to recover my pool.

**Comment by gmelikov** [comment]
Looks like resolved, feel free to reopen the issue if it's not.
