### ISSUE TITLE
zfs Build breaks on ppc64le arch

### ISSUE THREAD

**Issue by harsha544** [zfsonlinux/zfs#5174]
Initiated a local build of zfs (Branch zfs-0.6.3-stable) on POWER8 Server with **ppc64le** architecture which fails

**Comment by harsha544** [comment]
I'm Currently working on the above issue. will update on the same.

**Comment by rlaager** [comment]
I'm not sure what our practice is on assigning bugs, but hey, I seem to be able to do it. :)

**Comment by behlendorf** [comment]
Closing.  Works for me building zfs-0.7.1 on POWER9 ppc64le.
