### ISSUE TITLE
mindless resilvering time being shown in zpool status -v 

### ISSUE THREAD

**Issue by devZer0** [zfsonlinux/zfs#5186]
centos 7
zfsonlinux  0.6.5.7
virtual machine on xenserver 7
# zpool status -v

  pool: zfspool
 state: ONLINE
  scan: resilvered 5,18G in 307445734561825858h42m with 0 errors on Fri Sep 23 18:31:37 2016
config:

```
    NAME        STATE     READ WRITE CKSUM
    zfspool     ONLINE       0     0     0
      raidz1-0  ONLINE       0     0     0
        xvdb1   ONLINE       0     0     0
        xvdc1   ONLINE       0     0     0
        xvdd1   ONLINE       0     0     0
        xvde1   ONLINE       0     0     0
```

errors: No known data errors
# zpool list

NAME      SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
zfspool  6,22T  1,83T  4,39T         -    18%    29%  1.00x  ONLINE  -

resilver finished quite fast, i think reporting 307445734561825858h 42m  is a little bit over the top....

i updated to 0.6.5.8 and did not try forcing another resilvering, this system is semi-production and in 0.6.5.8 i don`t see any appropriate change which should have adressed this, so i`d first like to hear what may have gone wrong here or if it`s a known issue...

**Comment by loli10K** [comment]
Probably related to https://github.com/zfsonlinux/zfs/issues/1490. Did you manually trigger the resilver?

My (educated) guess: this was caused by some time synchronization functionality between your Xen hypervisor and the VM.

**Comment by devZer0** [comment]
good point, didn`t mind that.

the resilver was automatically started after boot, so chances are high that there was a backward jump in time.  

will check for that

**Comment by loli10K** [comment]
> will check for that

Closing as stale, feel free to comment if this is still an issue. Also `zpool history -i` would be the place to start looking in case this happens again.
