### ISSUE TITLE
"zpool status -v" shows file error

### ISSUE THREAD

**Issue by James-Dao** [zfsonlinux/zfs#5193]
Hi,

I use zfs in production environment, i run into a question, but i do not know how to handle this question, also want to the root cause.  can you help me ? zfs version is 0.6.5.4-1
This is the error detail:

root@ubuntu:~# zpool status -v
  pool: volumes
 state: ONLINE
status: One or more devices has experienced an error resulting in data
	corruption.  Applications may be affected.
action: Restore the file in question if possible.  Otherwise restore the
	entire pool from backup.
   see: http://zfsonlinux.org/msg/ZFS-8000-8A
  scan: scrub repaired 0 in 3h49m with 1937 errors on Thu Sep 22 12:29:51 2016
config:

	NAME        STATE     READ WRITE CKSUM
	volumes     ONLINE       0     0 2.04K
	  mirror-0  ONLINE       0     0     0
	    vdb     ONLINE       0     0     0
	    vdf     ONLINE       0     0     0
	  mirror-1  ONLINE       0     0 4.09K
	    vdd     ONLINE       0     0 4.09K
	    vde     ONLINE       0     0 4.09K

errors: Permanent errors have been detected in the following files:

        volumes/free/1/be9509b4-cca7-45bc-6b36-46e01a2c755b:<0x1659>     
        /volumes1/data/free/1/5f9cf209-69d8-4289-56a6-ebc96231bc50/avatar/avatar_20160919042303.jpg
.....

when i use cat to read file, it shows "Input/output error":
cat /volumes1/data/free/1/aa307c38-4b94-49f4-6993-6cea4441ae0f/1.txt
cat: /volumes1/data/free/1/aa307c38-4b94-49f4-6993-6cea4441ae0f/1.txt:     Input/output error

**Comment by drescherjm** [comment]
I believe this is a question for the mailing list.

**Comment by James-Dao** [comment]
you mean i need to post a email to "zfs-discuss@list.zfsonlinux.org" to discuss this question?
