### ISSUE TITLE
hybrid/dynamic case-(in)sensitivity?

### ISSUE THREAD

**Issue by RJVB** [zfsonlinux/zfs#5200]
This isn't an actual issue I'm having, just a though that came up discussing the new ApFS and the fact that it apparently doesn't have a case-insensitive mode (a first for Apple).

This got me wondering: it's probably possible to mimic case-insensitive at a high, UI level, but can it not be done at the FS level too? What if you add what's essentially a fallback through a mode that can be activated or deactivated at any time? If a file/path doesn't exist with the given exact spelling, fall back to a check that disregards case, and if that succeeds, return that instance. Evidently you'd probably not want to do that for creation (unless you want to make the FS case-insensitive in all aspects) and the implementation might be a bit delicate for things like directory listing.

Wouldn't that give the kind of filesystem behaviour typical Mac and PC users expect, while offering real, hard case preservation underneath?

I'm not exactly an experienced FS developer, but others on here surely must be. What do you think, am I overlooking a few things that would make this a truly bad idea bound for failure?

**Comment by rlaager** [comment]
What you have described is case-preserving storage with case-insensitive lookups. (Well, you described something slightly different, which is to lookup case-sensitively first and then fall back, which wouldn't work well in practice because that implies you can have duplicated names.)

Isn't this already how ZFS's casesensitivity=insensitive property works?

In any event, the issue tracker isn't the place for this sort of discussion.

**Comment by RJVB** [comment]
On Friday September 30 2016 16:50:49 Richard Laager wrote:

> What you have described is case-preserving storage with case-insensitive lookups. (Well, you described something slightly different, which is to lookup case-sensitively first and then fall back, which wouldn't work well in practice because that implies you can have duplicated names.)

How can you have duplicate names? The underlying structure still considers differences in case differences in name. Are you concerned that files in potentially many different locations (complex paths) can be considered the same file? That's indeed a problem ...

> Isn't this already how ZFS's casesensitivity=insensitive property works?

I doubt it because if so there shouldn't be any need for it to be read-only. Whether or not you do the lookup with or without taking case into consideration is something you can change on the fly.

> In any event, the issue tracker isn't the place for this sort of discussion.

Did I overlook a forum or something of the sort?

R.

**Comment by ptx0** [comment]
try IRC or the mailing list.
