### ISSUE TITLE
soft lockup with stable 0.6.3-1.3

### ISSUE THREAD

**Issue by samuelxhu** [zfsonlinux/zfs#5211]
A production ZFS server running stable 0.6.3-1.3, with SCST as FC target, encountering the following soft lockup

Sep 23 09:40:29 panda1 kernel: INFO: task txg_sync:19410 blocked for more than 120 seconds.
Sep 23 09:40:29 panda1 kernel:      Tainted: P           ---------------    2.6.32-504.3.3.el6.x86_64 #1
Sep 23 09:40:29 panda1 kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Sep 23 09:40:29 panda1 kernel: txg_sync      D 0000000000000000     0 19410      2 0x00000080
Sep 23 09:40:29 panda1 kernel: ffff880a113a5b70 0000000000000046 0000000000000000 ffff88105dbef218
Sep 23 09:40:29 panda1 kernel: 0000000000000001 ffff88105dbef230 0000000000000000 0000000000000000
Sep 23 09:40:29 panda1 kernel: ffff880a113a5af0 ffffffff81064ba2 ffff881047d4d098 ffff880a113a5fd8
Sep 23 09:40:29 panda1 kernel: Call Trace:
Sep 23 09:40:29 panda1 kernel: [<ffffffff81064ba2>] ? default_wake_function+0x12/0x20
Sep 23 09:40:29 panda1 kernel: [<ffffffff810aaa21>] ? ktime_get_ts+0xb1/0xf0
Sep 23 09:40:29 panda1 kernel: [<ffffffff8152a173>] io_schedule+0x73/0xc0
Sep 23 09:40:29 panda1 kernel: [<ffffffffa0321231>] cv_wait_common+0xc1/0x1d0 [spl]
Sep 23 09:40:29 panda1 kernel: [<ffffffffa0491e00>] ? zio_execute+0x0/0x140 [zfs]
Sep 23 09:40:29 panda1 kernel: [<ffffffff8109eb00>] ? autoremove_wake_function+0x0/0x40
Sep 23 09:40:29 panda1 kernel: [<ffffffffa0321358>] __cv_wait_io+0x18/0x20 [spl]
Sep 23 09:40:29 panda1 kernel: [<ffffffffa049203b>] zio_wait+0xfb/0x1c0 [zfs]
Sep 23 09:40:29 panda1 kernel: [<ffffffffa0420693>] dsl_pool_sync+0xb3/0x440 [zfs]
Sep 23 09:40:29 panda1 kernel: [<ffffffffa0434e4f>] spa_sync+0x40f/0xaf0 [zfs]
Sep 23 09:40:29 panda1 kernel: [<ffffffffa0449f1b>] txg_sync_thread+0x3ab/0x5f0 [zfs]
Sep 23 09:40:29 panda1 kernel: [<ffffffff8105c2f9>] ? set_user_nice+0xc9/0x130
Sep 23 09:40:29 panda1 kernel: [<ffffffffa0449b70>] ? txg_sync_thread+0x0/0x5f0 [zfs]
Sep 23 09:40:29 panda1 kernel: [<ffffffffa0318e68>] thread_generic_wrapper+0x68/0x80 [spl]
Sep 23 09:40:29 panda1 kernel: [<ffffffffa0318e00>] ? thread_generic_wrapper+0x0/0x80 [spl]
Sep 23 09:40:29 panda1 kernel: [<ffffffff8109e66e>] kthread+0x9e/0xc0
Sep 23 09:40:29 panda1 kernel: [<ffffffff8100c20a>] child_rip+0xa/0x20
Sep 23 09:40:29 panda1 kernel: [<ffffffff8109e5d0>] ? kthread+0x0/0xc0
Sep 23 09:40:29 panda1 kernel: [<ffffffff8100c200>] ? child_rip+0x0/0x20

Is there already a patch to fix it? if possible, I would like to stay with 0.6.3-1.3 for the moment

**Comment by rincebrain** [comment]
I mean, presuming it is indeed a soft lockup, that's just going to be an artifact of how long it takes to do those ZIOs.

I believe a number of changes have been made to improve performance since 0.6.3-1.3 was cut, ~18 months ago, but no single change stands out that would be a good option for cherry-picking to me.

Is there a particular reason you want to avoid upgrading? IIRC there's a number of known hard lockups prior to 0.6.5.

**Comment by kpande** [comment]
please reproduce on a current release.
