### ISSUE TITLE
nbmand=on causes import mount error

### ISSUE THREAD

**Issue by risto3** [zfsonlinux/zfs#5217]
another issue encountered migrating from illumos had to do with a couple of CIFS mounts
where 'sharesmb' was 'on' as well as 'nbmand'. 
I had already set both 'sharesmb' and 'sharenfs' to 'off' but ignored changing 'nbmand', which gives the following upon import:

```
[root@sarchx64 richard]# LANG=C zpool import -d /dev/disk/by-uuid/ 1631288782183825328
filesystem 'dpool/export/home/anneke' can not be mounted due to error 1
cannot mount 'dpool/export/home/anneke': Invalid argument
filesystem 'dpool/export/home/krista' can not be mounted due to error 1
cannot mount 'dpool/export/home/krista': Invalid argument
```

although this property is not used on Linux, it should probably be simply ignored or at most a warning issued, not an error.

**Comment by loli10K** [comment]
I believe this is fixed in the 0.6.5 stable branch https://github.com/zfsonlinux/zfs/commit/590509b75e899a769a47744cba2ab41fda5f85ce, closing.
