### ISSUE TITLE
Error while running zfs utilities from crontab

### ISSUE THREAD

**Issue by vfrans** [zfsonlinux/zfs#5221]
Hello,

I'm trying to run the zfs utilities from crontab as user root with bash shell.

Here is the config of my /etc/crontab:

```
SHELL=/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin
MAILTO=<my_mail>
HOME=/root

03 7 * * * root $HOME/backup.sh
```

Here is the content of $HOME/backup.sh:

```
#!/bin/bash
source $HOME/.bash_profile
whoami
zfs snapshot synczfs/data@mysnap
mount -t zfs synczfs/data@mysnap /snapzfs/
<backing up some stuffs from the snapshot folder /snapzfs>
umount /snapzfs
zfs destroy synczfs/data@mysnap
```

The result that i get in my mails is the following:

> root
> Permission denied the ZFS utilities must be run as root.

Is there something i'm missing? Because it really feels like i am running the zfs utils as root.

**Comment by rlaager** [comment]
Obvious question: The same script works fine outside of cron?

`ls -la /dev/zfs`

Try throwing a `strace` in front of ZFS. Let's see where it's failing.

**Comment by rlaager** [comment]
Also, `ls -la /etc/mtab`

**Comment by vfrans** [comment]
Ovious question, but still a valid one! Yes the script does work when run by the root user logged in (using ssh, never tested local and i'm not able to).

`[root@hostname ~]# ls -la /dev/zfs
crw-rw----. 1 root root 10, 57 Sep 20 09:00 /dev/zfs
[root@hostname ~]# ls -la /etc/mtab
-rw-r--r--. 1 root root 656 Oct  5 07:03 /etc/mtab`

Script launched by crontab:
`#!/bin/bash
source $HOME/.bash_profile
strace zfs snapshot synczfs/data@mysnap
exit`

Result:
`execve("/sbin/zfs", ["zfs", "snapshot", "synczfs/data@mysnap"], [/* 12 vars */]) = 0
brk(0)                                  = 0x1094000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbca4540000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY)      = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=22877, ...}) = 0
mmap(NULL, 22877, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fbca453a000
close(3)                                = 0
open("/lib64/libnvpair.so.1", O_RDONLY) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\260K\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=82184, ...}) = 0
mmap(NULL, 2177352, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fbca410e000
mprotect(0x7fbca4121000, 2097152, PROT_NONE) = 0
mmap(0x7fbca4321000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x13000) = 0x7fbca4321000
close(3)                                = 0
open("/lib64/libuutil.so.1", O_RDONLY)  = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0U\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=78352, ...}) = 0
mmap(NULL, 2173848, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fbca3efb000
mprotect(0x7fbca3f0c000, 2097152, PROT_NONE) = 0
mmap(0x7fbca410c000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x11000) = 0x7fbca410c000
close(3)                                = 0
open("/lib64/libzpool.so.2", O_RDONLY)  = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\200|\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1287584, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbca4539000
mmap(NULL, 4845272, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fbca3a5c000
mprotect(0x7fbca3b8f000, 2097152, PROT_NONE) = 0
mmap(0x7fbca3d8f000, 28672, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x133000) = 0x7fbca3d8f000
mmap(0x7fbca3d96000, 1461976, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fbca3d96000
close(3)                                = 0
open("/lib64/libzfs.so.2", O_RDONLY)    = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\300\244\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=305536, ...}) = 0
mmap(NULL, 2400840, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fbca3811000
mprotect(0x7fbca385a000, 2097152, PROT_NONE) = 0
mmap(0x7fbca3a5a000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x49000) = 0x7fbca3a5a000
close(3)                                = 0
open("/lib64/libzfs_core.so.1", O_RDONLY) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\340\20\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=16712, ...}) = 0
mmap(NULL, 2112016, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fbca360d000
mprotect(0x7fbca3611000, 2093056, PROT_NONE) = 0
mmap(0x7fbca3810000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3000) = 0x7fbca3810000
close(3)                                = 0
open("/lib64/libm.so.6", O_RDONLY)      = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0p>\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=596360, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbca4538000
mmap(NULL, 2633912, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fbca3389000
mprotect(0x7fbca340c000, 2093056, PROT_NONE) = 0
mmap(0x7fbca360b000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x82000) = 0x7fbca360b000
close(3)                                = 0
open("/lib64/libdl.so.2", O_RDONLY)     = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\340\r\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=19536, ...}) = 0
mmap(NULL, 2109696, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fbca3185000
mprotect(0x7fbca3187000, 2097152, PROT_NONE) = 0
mmap(0x7fbca3387000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7fbca3387000
close(3)                                = 0
open("/lib64/librt.so.1", O_RDONLY)     = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\240!\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=43944, ...}) = 0
mmap(NULL, 2128816, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fbca2f7d000
mprotect(0x7fbca2f84000, 2093056, PROT_NONE) = 0
mmap(0x7fbca3183000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x6000) = 0x7fbca3183000
close(3)                                = 0
open("/lib64/libuuid.so.1", O_RDONLY)   = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\240\25\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=16304, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbca4537000
mmap(NULL, 2111272, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fbca2d79000
mprotect(0x7fbca2d7d000, 2093056, PROT_NONE) = 0
mmap(0x7fbca2f7c000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3000) = 0x7fbca2f7c000
close(3)                                = 0
open("/lib64/libz.so.1", O_RDONLY)      = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0 !\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=88600, ...}) = 0
mmap(NULL, 2183696, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fbca2b63000
mprotect(0x7fbca2b78000, 2093056, PROT_NONE) = 0
mmap(0x7fbca2d77000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x14000) = 0x7fbca2d77000
close(3)                                = 0
open("/lib64/libpthread.so.0", O_RDONLY) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0000^\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=142688, ...}) = 0
mmap(NULL, 2212848, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fbca2946000
mprotect(0x7fbca295d000, 2097152, PROT_NONE) = 0
mmap(0x7fbca2b5d000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x17000) = 0x7fbca2b5d000
mmap(0x7fbca2b5f000, 13296, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fbca2b5f000
close(3)                                = 0
open("/lib64/libc.so.6", O_RDONLY)      = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0000\356\1\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1923352, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbca4536000
mmap(NULL, 3750184, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fbca25b2000
mprotect(0x7fbca273c000, 2097152, PROT_NONE) = 0
mmap(0x7fbca293c000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x18a000) = 0x7fbca293c000
mmap(0x7fbca2942000, 14632, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fbca2942000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbca4535000
mmap(NULL, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbca4532000
arch_prctl(ARCH_SET_FS, 0x7fbca4533740) = 0
mprotect(0x7fbca293c000, 16384, PROT_READ) = 0
mprotect(0x7fbca2b5d000, 4096, PROT_READ) = 0
mprotect(0x7fbca2d77000, 4096, PROT_READ) = 0
mprotect(0x7fbca3183000, 4096, PROT_READ) = 0
mprotect(0x7fbca3387000, 4096, PROT_READ) = 0
mprotect(0x7fbca360b000, 4096, PROT_READ) = 0
mprotect(0x7fbca4541000, 4096, PROT_READ) = 0
munmap(0x7fbca453a000, 22877)           = 0
set_tid_address(0x7fbca4533a10)         = 2882
set_robust_list(0x7fbca4533a20, 24)     = 0
futex(0x7ffc5f8850ac, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7ffc5f8850ac, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 1, NULL, 7fbca4533740) = -1 EAGAIN (Resource temporarily unavailable)
rt_sigaction(SIGRTMIN, {0x7fbca294bcb0, [], SA_RESTORER|SA_SIGINFO, 0x7fbca29557e0}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {0x7fbca294bd40, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7fbca29557e0}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
getrlimit(RLIMIT_STACK, {rlim_cur=10240*1024, rlim_max=RLIM64_INFINITY}) = 0
brk(0)                                  = 0x1094000
brk(0x10b5000)                          = 0x10b5000
open("/usr/lib/locale/locale-archive", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=99164480, ...}) = 0
mmap(NULL, 99164480, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fbc9c71f000
close(3)                                = 0
access("/sys/module/zfs", F_OK)         = 0
access("/sys/module/zfs", F_OK)         = 0
clock_gettime(CLOCK_MONOTONIC, {1309236, 446262225}) = 0
open("/dev/zfs", O_RDWR)                = 3
close(3)                                = 0
open("/dev/zfs", O_RDWR)                = 3
open("/etc/mtab", O_RDONLY)             = 4
open("/etc/dfs/sharetab", O_RDONLY)     = 5
open("/dev/zfs", O_RDWR)                = 6
open("/usr/share/locale/locale.alias", O_RDONLY) = 7
fstat(7, {st_mode=S_IFREG|0644, st_size=2512, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbca453f000
read(7, "# Locale name alias data base.\n#"..., 4096) = 2512
read(7, "", 4096)                       = 0
close(7)                                = 0
munmap(0x7fbca453f000, 4096)            = 0
open("/usr/share/locale/en_US.UTF-8/LC_MESSAGES/zfs-linux-user.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US.utf8/LC_MESSAGES/zfs-linux-user.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US/LC_MESSAGES/zfs-linux-user.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.UTF-8/LC_MESSAGES/zfs-linux-user.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.utf8/LC_MESSAGES/zfs-linux-user.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en/LC_MESSAGES/zfs-linux-user.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
ioctl(3, 0x5a12, 0x7ffc5f8815c0)        = 0
ioctl(3, 0x5a05, 0x7ffc5f87df70)        = 0
mmap(NULL, 135168, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbca4511000
ioctl(6, 0x5a23, 0x7ffc5f881460)        = 0
munmap(0x7fbca4511000, 135168)          = 0
ioctl(3, 0x5a3f, 0x7ffc5f881a50)        = 0
close(3)                                = 0
close(4)                                = 0
close(5)                                = 0
close(6)                                = 0
exit_group(0)                           = ?
+++ exited with 0 +++`

**Comment by rlaager** [comment]
I've got a lot of nothing, so the following is "grasping at straws" and general "X doesn't work under cron" troubleshooting ideas.

Are you on a distro with SELinux? Can you think of anything else that might differ between the cron environment and the normal root environment?

Another test idea would be to run screen from cron (e.g. set it to run a minute in the future). Once it starts up, run `sudo screen -x` to connect to it. See if zfs fails in that environment. If it does, it'll be a lot easier to work out what is different. Definitely look at environment variables (e.g. run `env` in the cron environment vs. a normal one).

**Comment by vfrans** [comment]
@rlaager, thanks a lot! SELinux indeed was the thing getting in my way!
After adding a custom module to allow allow mount_t device_t:chr_file open, it worked flawlessly!
