### ISSUE TITLE
Migrated pool to new drive with new pool name wont import

### ISSUE THREAD

**Issue by VERTlG0** [zfsonlinux/zfs#5222]
I'm using Gentoo, and zfs-0.6.5.8 with kernel gentoo-sources-4.7.4. I migrated my old pool, "rpool" to a new drive.  I created a new pool on that new drive called "rpool2". After successful migration, I installed grub to /boot, ran 'make install' to install kernel, rebuilt modules, ran 'genkernel --zfs initramfs', 'grub-mkconfig -o /boot/grub/grub.cfg', made sure new grub showed "root=ZFS=rpool2/ROOT/gentoo"  and scandelay=3 was added because I always added it for my old pool which was on a usb drive and needed the delay. (I kept it because seems like everything is loading very fast in the initramfs now that Im on a SSD, and thought it couldnt hurt to keep. NOTE: I removed it in attempts to see if it would boot without it.... )Rebooted. Grub loads fine. Hit 'e' to double check grub.cfg, verified it's indeed rpool2, but when the initramfs starts initializing.. it tries to import rpool/ROOT/gentoo, and not rpool2/ROOT/gentoo.. It's still trying to import old pool.

![](http://i.imgur.com/aNSDYOy.jpg)

So I removed /etc/zfs/zpool.cache, re-did the steps again, and still wont import rpool2. I then went into sysrescd, did 'zpool import -N rpool rpool2' to rename my new pool from rpool2 to rpool.. re-did the steps, and now it boots. However, thats not fixing the problem. 

So I named my new pool back to rpool2 to try to find out why the initramfs is still trying to boot the old pool name. I also created a new /etc/zfs/zpool.cache while using rpool2. 

UPDATE: I found a solution to the problem. I don't know what this means in the long run and why it fixed it.. but instead of root=ZFS=rpool2/ROOT/gentoo as I always used and is what is in most zfs install guides. I then as a last resort tried real_root=ZFS=rpool2/ROOT/gentoo which worked perfectly.  Maybe someone can explain why that work and what the issue was? Also, removed scandelay for any of those who are wondering :)

Any input is greatly appreciated. 
Thanks.

**Comment by drescherjm** [comment]
There was an update to genkernel needed for recent zfs to boot.

**Comment by VERTlG0** [comment]
What version is that new update? Why is my old pool able to boot with genkernel and not new pool.. New pool is just a copy of old pool so same zfs version, same genkernel, same grub.

**Comment by drescherjm** [comment]
I took my comment back because I see your problem is a different issue.

**Comment by VERTlG0** [comment]
@drescherjm it's ok. Thanks for trying to help. I found a remedy to the problem.I hope its a remedy and not a temporary fix.  See above UPDATE:

**Comment by drescherjm** [comment]
I always use real_root. Here is what I have on one server here at work:

``
datastore2 zfs # grep ZFS /etc/default/grub
GRUB_CMDLINE_LINUX_DEFAULT="dozfs=force domdadm vga=791 scandelay=5 real_root=ZFS=zfs/os/gentoo"
``

**Comment by VERTlG0** [comment]
I dont know what the differences are between the two.. but the you would think since this new pool is just a copy of the old pool which booted with root=ZFS=rpool/ROOT/gentoo would also boot with that same line.. once I confirmed real_root= worked.. i tried root= again and it wouldnt boot.. I then renamed my pool back to the original name rpool which i know would boot with root=, so i tried booting it with real_root= as well which it did.. I then edited grub back to root=rpool/ROOT/gentoo. So to summarize- copied old pool to new drive with new pool name.. old pool booted with root= new pool name wont boot with root= but will with real_root=. Using old pool name does allow booting with both real_root= and root= . So if someone tries to copy their pool and of course theyll have to name the new pool.. theres a good chance their new pool wont import till they rename it back to the old pool.. or edit their grub and use real_root= with the new pool name.

**Comment by rlaager** [comment]
At least some init scripts (not sure about Gentoo) fall back on "rpool". So it's possible that it was working before, but not because of the root=, but only because your pool was named "rpool". As for the obvious question of how it found the dataset... did your old pool have the bootfs property set?

Also, @ryao would be the one to talk to.
