### ISSUE TITLE
zfs modules won't load after upgrade of RHEL-7 kernel

### ISSUE THREAD

**Issue by howff** [zfsonlinux/zfs#5225]
After upgrading the kernel from 3.10.0-327.18.2.el7.x86_64 to 3.10.0-327.36.1.el7.x86_64 the zfs modules no longer load.
I've tried both repos [zfs] and [zfs-kmod] with the same results:
[ 2967.850186] zfs: disagrees about version of symbol vn_openat
[ 2967.850190] zfs: Unknown symbol vn_openat (err -22)
etc.

I've tried erasing (and making sure there's no modules left in /lib/modules) and reinstalling numerous times to no avail.

**Comment by bziller** [comment]
Do you have kABI-tracking kmod or DKMS style packages installed, i.e. kmod-zfs or zfs-dkms?

**Comment by howff** [comment]
Following the docs https://github.com/zfsonlinux/zfs/wiki/RHEL-%26-CentOS
I originally had the default dkms then edited the repo to try kABI-tracking kmod then put it back to default again -- all three attempts failed.

**Comment by bziller** [comment]
Have you tried running ```depmod -a```?

**Comment by howff** [comment]
Thanks for the suggestion - just tried 'depmod -a' followed by 'modprobe zfs' -- I get the same errors

**Comment by loli10K** [comment]
@howff `vn_openat` is exported by the SPL kernel module, check if that is correctly installed (you should probably have the same version for both ZFS and SPL packages) and loaded into the kernel.

**Comment by howff** [comment]
I just tried "modprobe spl" then "modprobe zfs" - same error (actually vn_openat is just the first, there are many others). The packages are the same version:
spl-dkms-0.6.5.8-1.el7.centos.noarch
spl-0.6.5.8-1.el7.centos.x86_64
zfs-release-1-3.el7.centos.noarch
libzfs2-0.6.5.8-1.el7.centos.x86_64
zfs-dkms-0.6.5.8-1.el7.centos.noarch
zfs-0.6.5.8-1.el7.centos.x86_64

**Comment by bziller** [comment]
What's the output of ```cat /sys/module/spl/version``` and/or ```modinfo spl zfs | grep ^version```?

**Comment by howff** [comment]
Rather oddly they are different from each other:
# modinfo spl zfs | grep -i vers
version:        0.6.5.8-1
rhelversion:    7.2
# cat /sys/module/spl/version
0.6.5.6-1
I'm guessing this means that when you remove a package completely it may still leave itself loaded in memory - which seems a bit unintuitive. In the absence of a fix to RHEL maybe it's worth mentioning in the wiki that we need to rmmod <list of modules> when upgrading or switching to kABI-tracking kmod. Thanks folks :-)
