### ISSUE TITLE
Virtual machine write cache lost on shutdown (zvol)

### ISSUE THREAD

**Issue by RubenKelevra** [zfsonlinux/zfs#5227]
Hey guys,

I try to find a bug in kvm/libvirt/qemu/zfsonlinux, I use zvol on ArchLinux and kvm as hypervisor on this machine.

My virtual machine, running arch linux, had installed some updates and I had to reboot it. After the reboot all updates packages are broken and the download-cache of pacman is also broken.

All files are actually zero bytes large and the kernel and other packages are only partly written.

The guest filesystem is ext4, while the hypervisor uses zvol on a mirrored device.

Usually I use a zpool with mirroring and raw files for the VMs on that, two years no issues with that with some dozens machines.

The "buffermode" and "IO-Mode" on the hypervisor wasn't touched, I guess the default is "writethrough" and "threads".

Is the zvol-function not suitable for this use case or there anything I might test out?

Best regards

Ruben

**Comment by Rudd-O** [comment]
I doubt the zvol is the issue.  For you to have consistent writes, the OS needs to send write barriers (say, sync on poweroff, or fsync() on an ongoing basis) to the virtual block device, and the barriers need to make it out of the hypervisor and down onto the ZFS zvol, and then you will have consistent writes.  If syncing in the guest OS does not cause the hypervisor to sync, then that is a bug in the hypervisor.  Linux does sync when powering off.

Seems you should talk to the fellows in charge of the hypervisor you used, to get more debugging information.

**Comment by RubenKelevra** [comment]
I guess your right, I used to have an LVM based setup with virtual devices and encountered a similar issue, so we might be able to track it down to a libvirt-bug or if there's a virtual device code in Linux, there might be an issue as well. But I'm not sure how to test it at all. :/

As far as I understand, the virtual os should send some write commands to the virtual machine, which then picks them up and send it to the virtual device.

When I shutdown the OS, it should sync all open write requests to the virtual devices. If they were all accepted, the OS shut down the machine.

When this happens, the virtual device (ZVOL) on the hypervisor stays there but the virtual machine disappears. As far as I understand, the virtual machine accepts write requests, but accept them that fast, that the OS is able to shut the virtual machine down before it is able to commit them to the ZVOL.

The question is, why does this only happens to the ZVOL machine, not to the both other setups with raw files.

**Comment by Rudd-O** [comment]
* https://www.redhat.com/archives/virt-tools-list/2013-June/msg00081.html
* https://lists.nongnu.org/archive/html/qemu-devel/2006-08/msg00013.html

**Comment by RubenKelevra** [comment]
Here is my libvirt bugreport:

https://bugzilla.redhat.com/show_bug.cgi?id=1382139
