### ISSUE TITLE
Clarify whether zpool export is needed on poweroff

### ISSUE THREAD

**Issue by Rudd-O** [zfsonlinux/zfs#5228]
It remains unclear whether it is bad or good to zpool export on poweroff, but it appears that, to clear underlying devices (DM, LUKS, MD), the pool should be exported prior to systemd / dracut doing the clearing of those underlying devices.

What do we know about the proper way to shut down a ZFS pool during system poweroff?

**Comment by Rudd-O** [comment]
Label Dracut please.

**Comment by behlendorf** [comment]
Historically on Illumos the pool does not get exported for a few reasons.  Off the top of my head:

* Exporting the pool removes it from the cache file.  Other platforms depend on the cache file to know which pools to import.
* Exporting the pool causes the vdev labels to be updated.  This limits ZFS's ability to automatically rollback the pool to the previous TXG is needed.

Now whether those reasons really apply to Linux which boots very differently now with systemd are debatable.

**Comment by Rudd-O** [comment]
OK.  Then we shall not try to export the pool.  I am happy to make the changes in the initramfs that will cause that to stop happening.

Having said that, this raises another question:

How do we ensure that the root pool has committed everything to disk before poweroff?

**Comment by behlendorf** [comment]
> How do we ensure that the root pool has committed everything to disk before poweroff?

Well if you can unmount but not export the pool that would do it.  Also there's an argument to be made cleanly exporting the pool shouldn't limit your rollback ability and that's just a bug.

> Is there a way to readonly / yank a pool's devices out of the way of whatever underlying storage there is, such that the underlying storage can then be cleaned up, but without dirtying up the pool labels? 

You should be able to use the `-F` hardforce option to `zpool export` to have to export the pool without dirtying the labels.

**Comment by Rudd-O** [comment]
I don't think that's correct.  I just did a `zpool export -F` on a pool I just created for the purposes of testing, and the pool history clearly shows the command, so something is in fact being written to the pool when you export something.

Any ideas?

**Comment by behlendorf** [comment]
The `-F` option doesn't disable all writes to the pool, it just disables the label updates which are the problem.  Although I'd definitely verify this with `zdb`.  See
https://github.com/zfsonlinux/zfs/blob/master/module/zfs/spa.c#L4296.

Probably the right thing to do here during a normal shutdown is to always use  `-F`.
