### ISSUE TITLE
comment field being lost after kernel panic

### ISSUE THREAD

**Issue by nhardt** [zfsonlinux/zfs#5231]
I'm doing some testing on zfs. With repeated kernel panics, a pool sometimes will lose the comment field. I've been using zfs for less than a day so there could definitely be user error, but it is repeatable. It doesn't always happen though, so it doesn't seem like it's stored in memory. The times when the label is lost, the pool also does not mount on boot. When I run the import manually, it becomes available, but the label is gone.

```
[root@xxx ~ 19:58:01 ]# zpool history slot3data
History for 'slot3data':
2016-10-05.08:33:49 zpool create -f -m /mnt/slot3data slot3data /dev/mapped/slot3data
2016-10-05.08:33:50 zpool set comment=279a9669_11 slot3data
2016-10-05.08:33:51 zfs set compression=lz4 slot3data
2016-10-05.08:39:58 zpool import -c /etc/zfs/zpool.cache -aN
2016-10-05.08:54:10 zpool import -c /etc/zfs/zpool.cache -aN
2016-10-05.09:10:07 zpool import slot3data
2016-10-05.09:19:52 zpool set comment=279a9669_11 slot3data
```

each of the `zpool import -c /etc/zfs/zpool.cache -aN` commands is when auto mount worked after the kp. `zpool import slot3data` is a manual mount when the auto mount failed. Setting the comment field after it is lost works. No changes to the pools are occurring near the time of the kp, but there is load.

Please let me know if I should be running additional commands or if there is additional data I can provide. Thanks!

**Comment by DeHackEd** [comment]
The comment is kept in the disk labels. It should be visible in `zdb -l /dev/mapped/slot3data/`unless something's gone horribly wrong.

**Comment by nhardt** [comment]
looks like i failed to mention that i'm using `zpool get comment slot3data` to get the comment. should that be any different? are there any logs or anything that would be useful to get if this happens? so far has been reproducible.

**Comment by kpande** [comment]
@nhardt is this still a concern?

**Comment by nhardt** [comment]
I have not tested anything recent. The issue is no longer a concern for me personally.

**Comment by loli10K** [comment]
> I have not tested anything recent. The issue is no longer a concern for me personally.

This doesn't seem to be an issue anymore, closing.
