### ISSUE TITLE
fcntl_setlk very slow

### ISSUE THREAD

**Issue by akorn** [zfsonlinux/zfs#524]
Hi,

after migrating a samba server to zfsonlinux, I noticed that almost all smbd processes were waiting in fcntl(), trying to:

```
fcntl(23, F_SETLKW, {type=F_WRLCK, whence=SEEK_SET, start=8, len=1}) = 0
```

on /var/run/samba/gencache_notrans.tdb. These calls were all taking so long that they were causing client timeouts.

On a hunch, I put /var/run/samba on a tmpfs and voilá, it works as before; the long waits are gone.

**Comment by behlendorf** [comment]
Closing as stale.
