### ISSUE TITLE
Non members aren't allowed to ask questions on the zfs-discuss mailing list?

### ISSUE THREAD

**Issue by midjji** [zfsonlinux/zfs#5249]
Despite having subscribed to the mailing list I receive a "Non-members are not allowed to post." mail if I send any mail to zfs-discuss, this means this is the only way I can find to ask if particular behaviours are bugs or intended behaviour. Is this truly the intended behaviour of the mailing list? Why is the discuss list closed to new members? or where is the member option hidden? Is there some kind of minimum answering ratio required to post?`what ?

Despite searching for some time I cannot find any way to become a member of the mailing list, perhaps I am just being stupid, but please help.

**Comment by kpande** [comment]
this happens when you subscribe to the list and receive via one email, but then send with another.

**Comment by kpande** [comment]
you must use the email you are sub'd with to send emails to the list, otherwise there is no filtration taking place (save for spam)

**Comment by midjji** [comment]
I am,
Still does not work

**Comment by kpande** [comment]
are you authoring emails to `zfs-discuss@list.zfsonlinux.org` ?

**Comment by midjji** [comment]
Sending to yes, might be that i registered with a mail+ somethign adress
