### ISSUE TITLE
about metaslabs_per_vdev value  questions

### ISSUE THREAD

**Issue by steven-wugang** [zfsonlinux/zfs#5261]
question 1：Whether this metaslabs_per_vdev value（default 200） can be increased， What will be the impact of the increase?
question 2：If a single metaslab is too large, when the fragmentation is serious, Space seg consumes a lot of memory，so the system is out of memory。Whether there is a solution to this problem？

**Comment by DeHackEd** [comment]
Inappropriate question for a bug tracker

**Comment by kpande** [comment]
please use [the zfs-discuss mailing list](http://list.zfsonlinux.org)

**Comment by steven-wugang** [comment]
Thank you for reminding me
