### ISSUE TITLE
Error! Bad return status for module build on kernel: 3.16.0-4-amd64 (x86_64)

### ISSUE THREAD

**Issue by fxception** [zfsonlinux/zfs#5270]
On a fresh install of debian jessie 8.6 used jessie backports to apt-get install zfsutils-linux and I get an error. here is the whole process of the apt-get http://pastebin.com/sDkEAcNK . After it completed it did detect my pool and import it for me, but I'm not sure if this is normal on a fresh install or something i'm missing.

Thanks in advance.

**Comment by interduo** [comment]
Maybe You should issue this bug to Debian buglist? Please show us make.log from /var/lib/dkms/zfs/0.6.5.8/build/.

**Comment by behlendorf** [comment]
Closing as a Debian issue.
