### ISSUE TITLE
zfs incompatibility problem with solaris v28 fs ver 5

### ISSUE THREAD

**Issue by mike-sk** [zfsonlinux/zfs#5290]
this is describing it best.

send (oracle solaris v28) ---> recv (openzfs) fails with error
cannot receive: stream has unsupported feature, feature flags = 24

https://github.com/openzfsonosx/zfs/issues/48
I guess oracle updated zfs send

At least documentation that zpool v28 AND zfs ver 4 is needed to  get zfs send to work,
Sorry if this is wrong place to post it

rpm -qa | grep -e zfs -e spl
spl-0.6.5.7-1.el6.x86_64
spl-dkms-0.6.5.7-1.el6.noarch
zfs-dkms-0.6.5.7-1.el6.noarch
libzfs2-0.6.5.7-1.el6.x86_64
zfs-release-1-5.el6.noarch
zfs-0.6.5.7-1.el6.x86_64

**Comment by ryao** [comment]
Oracle broke send/recv compatibility. It is a known problem. It is also unlikely to be fixed because the change is not well understood.

**Comment by mike-sk** [comment]
the problem is realy documentation, cause if you follow   whats writeln everywhere (just zpool ver28)  you end up with solaris xTB volume ver zpool ver 28, zfs ver 5 and expecting to do zfs send and then you find out you have to copy all that again with rsync.  If you lucky, like me you test just before. It took me a bit of googling to figure what went wrong.

**Comment by kpande** [comment]
@mike-sk i'm not quite sure what you want us to change or where this should be documented.

**Comment by mike-sk** [comment]
This is a bit too old thread but.
At the time I was checking compatibility there was information you need 
zpool v28
but no information that you need zfs fs version4 in solaris   if you 
chcange to zfs fs version5  then you can't use zfs send/rcv properly.
after update to zfs fs ver5 I got into problems and hat to migrate few 
TB back to ver4
So this should be documented (may be allready done)

zfs get version

**Comment by rincebrain** [comment]
@mike-sk Even better than that, it's not a FS version 4 versus 5 problem, or pool version 28 problem, ZoL understands those. Oracle broke their on-disk and send stream compatibility with non-Oracle implementations for the same version numbers.

**Comment by behlendorf** [comment]
Would it be possible for someone with access to a Solaris system to generate and post a small example of both a full and incremental send stream with the incompatibility.  The stream may need it contain a file with multiple ACLs to ensure a spill block is used.  Thanks!

**Comment by behlendorf** [comment]
The core spill block issue was resolved by #8668.  As for the stream incompatibility with Solaris, since we don't have access to the details of the change they made we've decided it's best to not to guess and leave this incompatibility.  Closing issue.
