### ISSUE TITLE
Zpool import error on Fedora 24 server

### ISSUE THREAD

**Issue by Matty9191** [zfsonlinux/zfs#5318]
I'm getting some odd output while attempting to import a pool that was created on a X64 Solaris host:

  pool: bits
     id: 11221294326241036435
  state: UNAVAIL
 status: The pool was last accessed by another system.
 action: The pool cannot be imported due to damaged devices or data.
   see: http://zfsonlinux.org/msg/ZFS-8000-EY
 config:

```
bits                                             UNAVAIL  insufficient replicas
  raidz1-0                                       UNAVAIL  insufficient replicas
    c0t5d0s0                                     UNAVAIL
    c0t4d0s0                                     UNAVAIL
    md-uuid-dc867613:8e75d8e8:046b61bf:26ec6fc5  ONLINE
    11221294326241036435                         ONLINE
```

The four devices that make up this pool are definitely there and I can import the pool on a SmartOS system. Is this mode not supported? I wasn't able to find an answer in the official documentation..

**Comment by behlendorf** [comment]
OK, then the second thing to check would be that you can read the ZFS vdev labels with `zdb -l`.  You should get the same output on SmartOS and Linux.

```
zdb -l /dev/sdb
```

**Comment by Matty9191** [comment]
After a bit of digging I think I figured this out. The md driver was attempting to form a RAID array from the devices in my ZFS pool:

$ cat /proc/mdstat 
Personalities : [raid6] [raid5] [raid4] 
md127 : active (auto-read-only) raid5 sde[0] sdc[2] sdb[1]
      1465148928 blocks level 5, 64k chunk, algorithm 2 [3/3] [UUU]

This appears to have caused several devices to show up as UNAVAIL:

$ zpool import
   pool: bits
     id: 10295490771409337839
  state: UNAVAIL
 status: One or more devices contains corrupted data.
 action: The pool cannot be imported due to damaged devices or data.
   see: http://zfsonlinux.org/msg/ZFS-8000-5E
 config:

	bits                                           UNAVAIL  insufficient replicas
	  raidz1-0                                     UNAVAIL  insufficient replicas
	    ata-WDC_WD7500AACS-00D6B1_WD-WCAU47102921  UNAVAIL
	    ata-WDC_WD7500AACS-00D6B1_WD-WCAU47306478  UNAVAIL
	    ata-WDC_WD7500AACS-00D6B1_WD-WCAU47459778  ONLINE
	    ata-WDC_WD7500AACS-00D6B1_WD-WCAU47304342  UNAVAIL

Excluding the devices above in /etc/mdadm.conf allowed me to import the pool without issue. Is this normal behavior? What is the recommended way to fix this? Exclude pool devices? Blacklist kernel modules? Something else?

**Comment by Matty9191** [comment]
These have never been part of an md array. They were original in an X64 Solaris 10 server which was rebuilt with Fedora Linux. Any idea where md checks for the raid header? Curious what is at that location that is confusing md.

**Comment by behlendorf** [comment]
I'd start with `mdadm -E /dev/sdX` to dump the contents of the header.  That should at least tell you what it's detecting.  As for the details of the on-disk format your best bet is probably the blkid source.  It's responsible for detecting the signature of a disk when it's added to the system.

https://git.kernel.org/cgit/utils/util-linux/util-linux.git/

**Comment by rageagainstthebugs** [comment]
This not be zfs issue, but configuration problem with MD, me think this can be close.

**Comment by bunder2015** [comment]
while i appreciate your enthusiasm, brian is perfectly capable to closing stale bugs

**Comment by rageagainstthebugs** [comment]
thank you chris, i only find old ticket to closed.

**Comment by behlendorf** [comment]
Capable, but busy.  I certainly don't mind the help keeping on top of the tracker.  And since this was determined not to be a ZFS issue, but a `mdadm` issue, I agree we should close it out.
