### ISSUE TITLE
Feature request: add AVAIL (from zfs list) to zpool list

### ISSUE THREAD

**Issue by GregorKopka** [zfsonlinux/zfs#5334]
Simple request to add the available (AVAIL) property returned by the zfs list command to the output of zpool list.

There might be plenty of space 'free' in the pool (when viewed from zpool list) with none (or only little) of it effectively available (blocked by spa_slop_shift, as one possible culprit) at all.

So it would be good to show the effectively available space (as reported by zfs list) in the output of zpool list.

**Comment by richardelling** [comment]
IMHO, it is not a good idea to mix zpool and zfs usage data, the two can be radically different. To wit, zfs avail is a per-dataset metric and how would one understand the zpool output if there are hundreds of datasets, each with different avail?

Perhaps we can solve this with documentation?

**Comment by GregorKopka** [comment]
Example: The tank base dataset is all-default (except atime and xattr, to inherit into children), so it should have full access to all FREE space in the tank pool. But only 51% of that make it to being AVAIL.
```
host ~ $ zpool list tank
NAME      SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
tank     9,06T  8,27T   809G     16,0E      -    91%  1.00x  ONLINE  -
host ~ $ zfs list tank
NAME      USED  AVAIL  REFER  MOUNTPOINT
tank     6,61T   414G   345K  /tank
```
Looking at the output of zpool the user is lead into thinking that adding 500GB of data into a (new or existing) dataset would work - while ZFS *already knows in advance* (as shown by zfs list) that this will fail.

Thus solving this through documentation only isn't good enough, IMHO. Instead:
```
host ~ $ zpool list tank
NAME      SIZE  ALLOC   FREE   AVAIL  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
tank     9,06T  8,27T   809G   414G      16,0E      -    91%  1.00x  ONLINE  -
host ~ $ zfs list tank
NAME      USED  AVAIL  REFER  MOUNTPOINT
tank     6,61T   414G   345K  /tank
```
with AVAIL in zpool list being documented like 'space useable by datasets (estimated), taking ZFS overhead (metadata, copies, redundancy) into account' would give the user the needed information.

**Comment by richardelling** [comment]
For datasets (zfs properties) avail is adjusted as needed by quotas and reservations. This is why each dataset can have a different value for avail.

**Comment by GregorKopka** [comment]
Being able to limit (or guarantee) space for datasets and the resulting differences in *available* of them is beside the point.

The issue is that the FREE property of the pool is misleading to useless: it dosn't reflect the effective amount of data you are able to add to the pool at all, in the example I posted it is off by nearly 50% (on the short side).

On the other hand we have the output of AVAIL for an *unrestricted* dataset in the pool that accounts for redundancy overhead, spa_slop wastage, (etc.) and reports a somewhat realistic number of now much additional data the pool is willing to take. 

Hence my request to add that figure to the output of zpool list to give the user a number that isn't completely irrelevant but actually useful.

**Comment by richardelling** [comment]
With reservations, there is no such thing as "unrestricted dataset"
I think you should close this RFE and learn more about the concept of pooled storage models.

**Comment by GregorKopka** [comment]
With *unrestricted* dataset I'm refering to one without quota/reservation/whatever *in itself* stopping it from consuming all the available (=not already allocated to other datasets) net space in the pool. The *available* that is reported on such dataset is what ZFS thinks to be effectively available for operations (writing additional data into it, creating/receiving datasets as a children to it, and the like) before denying any further addition to this dataset (and all other in the pool that do not have a reservation) because of 'disk full' (ENOSPC).

That I why I would like to list exactly this *available* (as defined in the prior paragraph) through zpool list: to get direct access to a fair approximation on how much additional new data can effectively be added to the pool (without touching any existing datasets by removing reservations, destroying them or their snapshots). FREE of zpool list isn't helpful since it shows gross free space, not net available.

**Comment by richardelling** [comment]
Your definition of unrestricted dataset is not practical. The reason is because a  reservation on a dataset reduces the space available to other datasets.

If it helps, in my training materials on slide 149 (Dataset Space Accounting) at http://www.slideshare.net/relling/zfs-tutorial-lisa-2011 we usually spend 10+ minutes discussing the values in the the `zfs list -o space` output. For this case, note that the "avail" is not the same for all datasets.

**Comment by GregorKopka** [comment]
Any comments about existing datasets and if or what quota or reservation they might have might be interesting, but are offtopic since I'm refering to the _rest_ of the space: 
the unused, unreserved, __available space in the *pool*__.

I'll try to word it another way for you to get my point:

Currently there is no way to always display correctly the available logical space (or an estimation close enough to reality) in the pool. The nearest possibility is to query the root dataset of the pool through _zfs get available poolname_ - but this result _can_ be distorted by setting a quota or reservation on the root dataset (I so far have not seen a good reason for this to make sense, but YMMV).

As I (as an admin+user) don't really care about how much space is physically free in the pool, but how much is logically available for me to use for tasks I have in mind or on my list... I want a way to query the available pool space in a way that cannot be distorted.

The data is already there (and held current), it is used as the base of the calculation for the display of _available_ for a dataset (zfs get available, but when used for this it'll get adjusted for any quota or reservation made for the individual dataset).

I want to query information about the pool (not about an individual dataset):
A pool level, read-only property of _available_ seems the reasonable thing. Preferably added to the default output of _zpool list_ - since it is, like the health status, an essential top-level information about a pool.  IMHO.

**Comment by richardelling** [comment]
This is my last comment on this issue. I suggest further discussion on the appropriate discussion list.

@GregorKopka writes, "Currently there is no way to always display correctly the available logical space (or an estimation close enough to reality) in the pool." 

This is because there is no logical space in the pool. All logical space is shown by the zfs command. Since the space available to apps and users is all logical space, zfs is the correct command. Trying to add "zfs" notions into the "zpool" command will only confuse people.

**Comment by GregorKopka** [comment]
Reporting FREE space via zpool that actually isn't (and won't ever be) available for use through zfs confuses way worse.

ZFS useage is increasing for smaller installations (and even single-user machines like desktops, thanks to the benefits it provides over classical solutions like LVM or physical partitions) on which it is more practical to not restrict datasets but let them grow freely - as there is only one user and all the space is his anyway. You might be used to only big installations where this might be different, but the world is growing bigger than that: The end users are coming.

I suggested to add a meaningfull number (how much space in the pool currently is making AVAILable for additional zfs operations) to zpool list to offset the useless and confusing FREE one. 

To reduce the confusion with the current output that people have, among other places, expressed in:
https://github.com/zfsonlinux/zfs/issues/4206
https://github.com/zfsonlinux/zfs/issues/3014
https://github.com/zfsonlinux/zfs/issues/1942
https://github.com/zfsonlinux/zfs/issues/1089
https://github.com/zfsonlinux/zfs/issues/4117

About the 'appropriate' discussion list: It would have been more helpful to state *which* instead.

**Comment by richardelling** [comment]
zfs-discuss@list.zfsonlinux.org
