### ISSUE TITLE
wiki edit and mailing lists problem

### ISSUE THREAD

**Issue by gmelikov** [zfsonlinux/zfs#5348]
How can i contribute to git wiki?

There are some missing packages for building on Debian (libtool, autoconf).

Sorry to writing here, i tried to open Mailing Lists, but they are not working from https://github.com/zfsonlinux/zfs/wiki/Mailing-Lists (unable to connect).

**Comment by kpande** [comment]
wiki is currently only for members to contribute to, you may open an issue report with specific changes or ask @behlendorf for edit permissions.

mail list server was down for maintenance this AM, should be back up soon.
