### ISSUE TITLE
Cant mount sub-datasets at boot

### ISSUE THREAD

**Issue by johnramsden** [zfsonlinux/zfs#5351]
I've been trying to set up a pool with multiple data sets and I feel like I've tried every different combination of legacy data sets and ZFS managed datasets. Running Arch Linux with mirrored ssd's.

Is there a way to boot from a pool using many subdatasets? 

This is the set-up I am trying to boot from: 

```
vault/ROOT/default              /
vault/home                      /home
vault/tmp                       /tmp
vault/var                       /var
vault/run                       /run
vault/usr                       /usr
vault/usr/local                 /usr/local
vault/usr/lib                   /usr/lib
vault/usr/share                 /usr/share
vault/var/lib                   /var/lib 
```

I can get `/usr` and the root dataset to mount, but beyond that I haven't been able to get this setup to boot. 

I've had no problem in the past booting from a set up looking like this: 

```
vault/ROOT/default              /
vault/home                      /home
vault/tmp                       /tmp
vault/var                       /var
vault/usr                       /usr
```

But it seems like when I add the sub-data sets it causes an issue. 

The error message I have continuously gotten is 

Error: Root device mounted successfully, but /sbin/init does not exist. 

Among other errors when I try different combinations of Legacy data sets and zfs managed. 

The way I usually mount them that has worked in the past is: 

```
zfs list
NAME                 USED  AVAIL  REFER  MOUNTPOINT
vault                199G  30.0G    96K  none
vault/ROOT          8.15G  30.0G    96K  none
vault/ROOT/default  8.15G  30.0G  7.82G  /
vault/home           180G  30.0G  75.2G  legacy
vault/tmp            504K  30.0G   376K  /tmp
vault/usr           3.18G  30.0G  1.71G  legacy
vault/var           4.59G  30.0G  1.56G  legacy 
```

I have had this setup currently working on the same computer.

**Comment by johnramsden** [comment]
Yea, seems to be /usr, I destroyed vault/usr/local, vault/usr/lib and vault/usr/share and it worked. Is there a way to make this work?

**Comment by tuxoko** [comment]
Not possible, you need all the binary and library and stuff to mount filesystem.
