### ISSUE TITLE
ZFS 0.6.5.7~1 on Ubuntu 14.04.5 with NFSv4 has broken ACL support

### ISSUE THREAD

**Issue by gdevenyi** [zfsonlinux/zfs#5371]
I host a "quarantine" on an ZFS storage server which consists a bunch of installed software shared across a number of desktop machines. I recently went to install some python3 based tools in the quarantine and ran into the following:

From an strace of running a python3 setuptools script on the quarantine drive, mounted on a client via NFSv4:
```sh
chmod("/opt/quarantine/pydpiper/2.0/build/lib/python3.4/site-packages/pydpiper-2.0-py3.4.egg", 0644) = 0
listxattr("dist/pydpiper-2.0-py3.4.egg", "system.nfs4_acl\0", 256) = 16
getxattr("dist/pydpiper-2.0-py3.4.egg", "system.nfs4_acl", "\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x16\x01\x87\x00\x00\x00\x06OWNER@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x12\x00\x81\x00\x00\x00\x06GROUP@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x12\x00\x81\x00\x00\x00\x09EVERYONE@\x00\x00", 128) = 80
setxattr("/opt/quarantine/pydpiper/2.0/build/lib/python3.4/site-packages/pydpiper-2.0-py3.4.egg", "system.nfs4_acl", "\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x16\x01\x87\x00\x00\x00\x06OWNER@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x12\x00\x81\x00\x00\x00\x06GROUP@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x12\x00\x81\x00\x00\x00\x09EVERYONE@\x00\x00", 80, 0) = -1 EIO (Input/output error)
```

It appears that the setxattr call is failing against fails on the ZFS volume mounted over ZFS

**Comment by behlendorf** [comment]
Related to #4966.  It's not clear why this is failing if it's being [translated to a Posix ACL](http://lxr.free-electrons.com/source/fs/nfsd/nfs4acl.c?v=4.7#L102) by the NFS kernel server as @maxximino pointed out.  ZFS should be non the wiser.  We're going to need to dig deeper in to exactly where the NFS server is failing.

**Comment by tuxoko** [comment]
@behlendorf 
We need to implement inode->set_acl

**Comment by maxximino** [comment]
It's indeed a real zfs bug - nfs4_setfacl -a A:999:rwx  /mnt/ext4_over_nfs_with_acl/somefile works
nfs4_setfacl -a A:999:rwx  /mnt/zfs_over_nfs_with_acl/somefile fails with -EIO

nfs4_getfacl reports correctly translated posix acl (set on the server with setfacl as posix acl)

**Comment by tuxoko** [comment]
@gdevenyi 
Please try https://github.com/zfsonlinux/zfs/pull/5375
