### ISSUE TITLE
Expanding a Single Disk zpool

### ISSUE THREAD

**Issue by necouchman** [zfsonlinux/zfs#5372]
Running SPL + ZFS 0.6.5.8 on RHEL6 on VMware, kernel has been upgraded to 4.8.6, and running into an issue where the expand is not working.  Here's what I'm doing:
- Create a zpool with an initial size of 100GB.
- Expand the VMware disk to 500GB
- Rescan device in Linux such that kernel sees new size (fdisk -l shows correct size)
- Run "zpool online -e tank1 sdb"

At this point the zpool does not expand, but if I look at the GPT on the disk, it appears that the underlying partition has been expanded.  I can export/import the pool, run the online command, again, reboot the system, but the pool never expands.

**Comment by drescherjm** [comment]
https://www.dan.me.uk/blog/2012/11/14/increase-capacity-of-freebsd-zfs-array-by-replacing-disks/

**Comment by necouchman** [comment]
Yeah, saw that...but I found other indications elsewhere that simple expanding the underlying disk and then re-running the online command should online resize the device and the pool.

**Comment by drescherjm** [comment]
I think this is more of a mailing list question. Anyways the only time I have done this I used "set autoexpand=on" not sure if this has changed since then.

**Comment by kpande** [comment]
please use [the zfs-discuss mailing list](http://list.zfsonlinux.org) for support questions since this is potentially distribution specific.
