### ISSUE TITLE
compressratio showing 1.00x or 1.01x no matter what

### ISSUE THREAD

**Issue by jimsalterjrs** [zfsonlinux/zfs#5373]
I'm running a just-installed-today copy of 16.04.1, installed from an ISO also just downloaded today from releases.ubuntu.com.

~~~~
root@xenial:~# lsb_release -rd
Description:	Ubuntu 16.04.1 LTS
Release:	16.04

root@xenial:~# apt-cache policy zfsutils-linux
zfsutils-linux:
  Installed: 0.6.5.6-0ubuntu14
  Candidate: 0.6.5.6-0ubuntu14
  Version table:
 *** 0.6.5.6-0ubuntu14 500
        500 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     0.6.5.6-0ubuntu8 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
~~~~

I noticed that zfs get compressratio was not returning good results, and tested to ensure it was the compressratio reporting that was broken, not the actual compression.  Demonstration:

~~~~
root@xenial:~# zfs get compress data/test
NAME       PROPERTY     VALUE     SOURCE
data/test  compression  gzip      local
root@xenial:~# zfs list data/test
NAME        USED  AVAIL  REFER  MOUNTPOINT
data/test  2.64G   855G  2.64G  /data/test
~~~~

Note that data/test has inline gzip compression on, and shows 2.64G of data USED.

~~~~
root@xenial:~# du -hs --apparent-size /data/test
9.2G	/data/test
root@xenial:~# du -hs /data/test
2.7G	/data/test
~~~~

Now note that du correctly shows us that we have 9.2G of data stored in data/test (about 7G of which is actually a dump from /bin/zero for max compressibility, the other bit being an Ubuntu VM image file).

We should be seeing a compressratio of about 3.41x.

~~~~
root@xenial:~# zfs get compressratio data/test
NAME       PROPERTY       VALUE  SOURCE
data/test  compressratio  1.01x  -
~~~~

But we're seeing 1.01x.  Obviously very much not correct.  Halp?

I also reported this on Ubuntu's launchpad, but I figured I'd go ahead and jump the gun a bit and see what you fine folks might know about this.  If this is a closed bug here, it would be A-MAZ-ING if I could get a pointer to the issue to share with the folks monitoring zfsutils-linux over there in Canonical-land.

Thank you!

**Comment by DeHackEd** [comment]
This is a bug tracker, not a support forum.

The most likely answer to your question is, sparse holes are not considered "compressed". They are holes. You get the same thing on ext4 and it doesn't support compression at all. ZFS will turn all-null pages into sparse holes when compression is enabled.

**Comment by jimsalterjrs** [comment]
I'm well aware what "this" is, thank you very much.  Are you having a particularly bad day?

I was _not_ aware that piping from /dev/zero into a filehandle would create a sparse file; I've verified that you're correct by piping a bunch of ASCII into a file instead and seeing the compressratio come back correctly.

~~~~
root@locutus:/data/zerotest# perl test.pl | pv > compressible.txt
^C92GB 0:00:08 [ 624MB/s] [                   <=>                                                                                                         ]

root@locutus:/data/zerotest# zfs get compressratio data/zerotest
NAME           PROPERTY       VALUE  SOURCE
data/zerotest  compressratio  31.74x  -
~~~~

Feel free to tag this "invalid" if it makes you feel better; closing.

**Comment by kpande** [comment]
well, it's true that this is not a support forum and the noise generated by non-issues is distracting from actual work to be done.
