### ISSUE TITLE
zed: build error with "-O1", undefined reference to `libzfs_fru_compare'

### ISSUE THREAD

**Issue by ironMann** [zfsonlinux/zfs#5402]
```
# git co zol/master; ./autogen.sh; CFLAGS="-O1" ./configure --enable-debug; make
....
agents/zfs_retire.o: In function `find_vdev':
/home/neskovic/zfs/cmd/zed/agents/zfs_retire.c:109: undefined reference to `libzfs_fru_compare'
collect2: error: ld returned 1 exit status
Makefile:834: recipe for target 'zed' failed
```
```
# gcc -v
gcc version 6.2.1 20160916 (Red Hat 6.2.1-2) (GCC)
```

I suspect this has to do something with `HAVE_LIBTOPO` not being set anywhere. Also, the error is gone when compiled with `-O2`, which could be due to more aggressive dead code elimination.

**Comment by behlendorf** [comment]
I suspect you're right.  `libtopo` is a library from illumos and I'm not aware of any Linux equivalent for the functionality it provides.  This code was wrapped in HAVE_LIBTOPO in the early days of the port simply to disable it but clearly it doesn't cover everything.  We should probably stop kicking the can down the road on this and remove the libtopo code.  It could always be resurrected if needed.   @don-brady should probably comment on this.
