### ISSUE TITLE
grub installation not working

### ISSUE THREAD

**Issue by bobk48** [zfsonlinux/zfs#5414]
System Requirements should say the hard drive you intend to use should be unallocated, unpartitioned but with a partition table on it.
I've correctly gone through all steps up to  5.1, and don't see zfs for output of the grub-probe / command.
Furthermore, steps 5.4 and 5.5 don't work, my system complains that the alias name for what you designate as  /dev/disk/by-id/scsi_SATA_disk1 is bad. Although the gdisk commands from step 2.2 work perfectly, and those aliases are correct when partitioning the disk.
Thus I cannot get past step 5.5a. System won't boot with no boot device designated. I rebooted anyway, and tried trouble shooting, install GRUB, no luck.
Conclusion: not ready for prime time. If only Linus would just put ZFS in the kernel. PCBSD/TrueOS and Solaris have it right!

**Comment by gmelikov** [comment]
At least you must give your disto name. 

Grub must be compiled with zfs support.

For now it's better to use additional nonzfs partition for some distros.

Sorry, but you have to use [mailing list or irc](https://github.com/zfsonlinux/zfs/wiki/Mailing-Lists) for support questions.
