### ISSUE TITLE
HOWTO Ubuntu 16.10 Root on ZFS error

### ISSUE THREAD

**Issue by OOPMan** [zfsonlinux/zfs#5416]
@rlaager Step 4.3 is missing details on copying `/etc/resolv.conf` from the host environment to the chroot environment.

As I side note, I was successfully able to use this HOWTO to install Kubuntu to ZFS root without using the whole disk :-)

**Comment by rlaager** [comment]
Aren't you ending up with resolvconf installed? Are you using a static IP but not setting `dns-nameservers` in `/etc/network/interfaces`?

I'm going to close this, but don't read too much into that. We can trivially reopen it if needed.
