### ISSUE TITLE
Ubuntu 16.04/Mint 18 zfs cannot create zpool on the boot disk!

### ISSUE THREAD

**Issue by bobk48** [zfsonlinux/zfs#5420]
This is a comment about creating zpools on a vdev that is the Ubuntu 16.04 or Mint 18 system, or boot, disk. If you try to do that on your system disk /dev/sda, or its first slice, with-

$ sudo zpool create test /dev/sda
invalid vdev specification
use '-f' to override the following errors:
/dev/sda does not contain an EFI label but it may contain partition information in the MBR.
$ sudo zpool create test /dev/sda1
invalid vdev specification
use '-f' to override the following errors:
/dev/sda1 contains a filesystem of type 'ext4'
$

Force the override, kiss your system disk goodbye, it won't boot.
So zfsutils-linux on Ubuntu 16.04 or Mint 18 only allows you to create zpools and datasets on media that is not your boot disk, like other internally-mounted hard disks, externally-mounted hard drives, USB thumb drives, etc.. I've done it on all of the previous very successfully. I never create zpools on partitions or create zvols, bad practice deprecated by Solaris. 

As of 11/21/2016

**Comment by kpande** [comment]
please use [the mailing list](http://list.zfsonlinux.org) for discussion, this is a bug tracker
