### ISSUE TITLE
 configure for zfs fails if following dkms only custom-package guide

### ISSUE THREAD

**Issue by tebruno99** [zfsonlinux/zfs#5424]
I was following the custom-package guide to produce Fedora 25 packages.

$ cd spl
$ ./configure
$ make pkg-utils rpm-dkms
$ sudo yum localinstall *.<arch>.rpm

The zfs step is actually not possible because ./configure in zfs reports that spl-kmod can't be found (which of course it can't, it didn't get built in the dkms only spl build)

$ cd ../zfs
$ ./configure
$ make pkg-utils rpm-dkms

**Comment by behlendorf** [comment]
@tebruno99 the `make rpm-dkms` target should work because it doesn't actually build anything.  It just packages the ZFS source so it can be built latter after the spl-dkms package in installed and compiled.

**Comment by gmelikov** [comment]
Close as stale.

If it's actual - feel free to reopen.
