### ISSUE TITLE
Add Fedora 25 repo

### ISSUE THREAD

**Issue by rabin-io** [zfsonlinux/zfs#5430]
Hello, 

Can you please add F25 repo ?

Thanks,

**Comment by behlendorf** [comment]
Yes, thanks for the reminder.

**Comment by x09** [comment]
i need f25 repo too

**Comment by error10** [comment]
Do you need any assistance with getting these repos put together? I recall that there was a lengthy delay getting the Fedora 24 repo as well (#4782) and I would like to avoid these delays going forward. I might not be the only one.

**Comment by behlendorf** [comment]
The Fedora 25 repository is now available.  The [zfs] repository contains zfs-0.6.5.8 and the [zfs-testing] repository contains zfs-0.7.0-rc2.

> Do you need any assistance with getting these repos put together?

Yes.  I'd like to be able to hand off responsibility for the Fedora repository to a new maintainer more closely affiliated with the Fedora project.  I think it's also worth investigating moving the official packages to one of the existing third party repositories.  If someone with experience packaging for Fedora is willing to volenteer please let me know.

https://fedoraproject.org/wiki/Third_party_repositories

**Comment by error10** [comment]
> Yes. I'd like to be able to hand off responsibility for the Fedora repository to a new maintainer more closely affiliated with the Fedora project.

I'd be happy to help with this. I'm already a Fedora packager and heavy Fedora user, and I'm already familiar with the overall process of maintaining repos through some third party and copr repos I've maintained for a few years now.

> I think it's also worth investigating moving the official packages to one of the existing third party repositories. If someone with experience packaging for Fedora is willing to volenteer please let me know.

And if one of the existing third party repos wants to take over this, I'm happy with that as well.

**Comment by behlendorf** [comment]
@error10 thanks for offering to help.  If you could email me directly at behlendorf1@llnl.gov we can work out the details.
