### ISSUE TITLE
Fake 100% Disk Usage?

### ISSUE THREAD

**Issue by masiqbal** [zfsonlinux/zfs#5434]
Hi,

I have weird disk usage on my ZFS installation. I can not write any files on the pool because of 100% usage. But, its usage is actually very low.

#df -h
Filesystem                                Size  Used Avail Use% Mounted on
devtmpfs                                   32G     0   32G   0% /dev
tmpfs                                      32G     0   32G   0% /dev/shm
tmpfs                                      32G  1.5M   32G   1% /run
tmpfs                                      32G     0   32G   0% /sys/fs/cgroup
/dev/mapper/fedora_root   50G   14G   37G  28% /
tmpfs                                      32G  4.0K   32G   1% /tmp
/dev/md126p1                              477M  130M  318M  29% /boot
/dev/mapper/fedora-home  617G  230G  387G  38% /home
**rpool/home-hdd                             11T   11T   72G 100% /home-hdd**

#du -sh /home-hdd
464G	/home-hdd

#zfs list
NAME             USED  AVAIL  REFER  MOUNTPOINT
rpool           10.1T  71.8G   198K  /rpool
rpool/home-hdd  10.1T  71.8G  10.1T  /home-hdd

My setup is in:
Fedora 24 64bit
2 x Intel(R) Xeon(R) CPU L5638
64GB RAM
2x 750 HDD RAID 1 for OS
4 x 4TB HDD for ZFS (RAIDZ)

**Comment by kernelOfTruth** [comment]
what is set for

```
cat /sys/module/zfs/parameters/spa_slop_shift
```

?

**Comment by masiqbal** [comment]
cat /sys/module/zfs/parameters/spa_slop_shift
5

**Comment by ronnyegner** [comment]
Can you please post the output of:

zfs list -o space
zfs list -t snapshot


Thanks

**Comment by masiqbal** [comment]
Hi,
I unmounted-mounted the pool, reboot the server, and it seemed normal again.
But I still wonder, how to prevent that situation come again.

Here is my last ZFS status:

zpool list
NAME    SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
rpool  14.5T  3.77T  10.7T         -    11%    26%  1.00x  ONLINE  -

zpool status
  pool: rpool
 state: ONLINE
  scan: none requested
config:

	NAME                                  STATE     READ WRITE CKSUM
	rpool                                 ONLINE       0     0     0
	  raidz1-0                            ONLINE       0     0     0
	    ata-ST4000NM0033-9ZM170_Z1Z55T71  ONLINE       0     0     0
	    ata-ST4000NM0033-9ZM170_S1Z0TN41  ONLINE       0     0     0
	    ata-ST4000NM0033-9ZM170_Z1Z5Q9S9  ONLINE       0     0     0
	    ata-ST4000NM0033-9ZM170_Z1Z1GCKD  ONLINE       0     0     0

errors: No known data errors


zfs list -o space
NAME            AVAIL   USED  USEDSNAP  USEDDS  USEDREFRESERV  USEDCHILD
rpool           7.47T  2.74T         0    174K              0      2.74T
rpool/home-hdd  7.47T  2.74T         0   2.74T              0          0

zfs list -t snapshot
no datasets available

**Comment by ronnyegner** [comment]
Sometimes these things are not related to ZFS and happen when you create a large file (that fills your disk), delete the file while a programm still accesses it. The actual file is deleted but since the file handle is stil open the file is not removed. Once the last handle is closed the file is removed and the space freed. You can do the same thing by rebooting and export/import of course.

**Comment by thewacokid** [comment]
The next time this happens (if it does), you can use lsof to see what files are potentially hanging on to the mount:

lsof -a +L1 [mountpoint]

That'll give you the PID of the offending processes as well.
