### ISSUE TITLE
test zfault.sh  5 & 6 :raid0 fails

### ISSUE THREAD

**Issue by martinhelmer** [zfsonlinux/zfs#545]
I know the guide says not to run these test' but i'm reporting them anyway :)

Running with 
*zfsonlinux-zfs-e29be02
*/zfsonlinux-spl-3c6ed54
(master head @ 29 jan)

System: debian wheezy (testing)
kernel: 3.1.0-1-amd64

here's my output:

root@carmencita:/proc/sys/kernel# /usr/libexec/zfs/zfault.sh -c
                                        raid0	raid10	raidz	raidz2	raidz3
1    soft write error                   Pass	Pass	Pass	Pass	Pass	
2    hard write error                   Pass	Pass	Pass	Pass	Pass	
3    all write errors                   Pass	Pass	Pass	Pass	Pass	
4    soft read error                    Pass	Pass	Pass	Pass	Pass	
5    hard read error                    Fail (33)
6   fixable read error                 Fail (33)
7    silent data corruption             Pass	Pass	Pass	Pass	Pass
8 not tested
9 not tested

**Comment by behlendorf** [comment]
Closing.  The `zfault.sh` test script has been removed and replaced by the far more extensive ZFS Test Suite.

6bb24f4 Add the ZFS Test Suite
