### ISSUE TITLE
[bug][CentOS7] - pools not available on reboot

### ISSUE THREAD

**Issue by ckozler** [zfsonlinux/zfs#5450]
After rebooting my pools are not available. The only reliable way to fix this  was to do the following:
  
# systemctl enable zfs-import-cache
# systemctl enable zfs-import-scan

I would imagine these should be done at install time? I couldnt find any documentation that stated you had to do this if you wanted your pools available on reboot. Then again, I could just be blind as hell :-)

Thanks for creating and maintaining an awesome set of software !

**Comment by ckozler** [comment]
Actually I had to do all of these after install to get volumes be automatically present on boot

    systemctl enable zfs.target
    systemctl enable zfs-import-cache
    systemctl enable zfs-import-scan
    systemctl status zfs-import-cache
    systemctl enable zfs-mount.service
    systemctl enable zfs-share

**Comment by behlendorf** [comment]
I've [updated the wiki](https://github.com/zfsonlinux/zfs/wiki/RHEL-%26-CentOS#important-notices) to make it clear that you'll need to do this when updating to 0.6.5.8.  There's the fix in the master branch already which will appear in 0.6.5.9 which will take care of this automatically, b3c159fee4ab92832e6a735431b8b5f930665fab.
