### ISSUE TITLE
Make error on 3.16.39 kernel with message: implicit declaration of function ‘inode_change_ok’

### ISSUE THREAD

**Issue by wf-cs** [zfsonlinux/zfs#5454]
The kernel 3.16.39 seems to have removed inode_change_ok. So building on that platform failed with the following messages:
/zfs-0.6.5.8/module/zfs/zpl_inode.c: In function ‘zpl_setattr’:
/zfs-0.6.5.8/module/zfs/zpl_inode.c:324: error: implicit declaration of function ‘inode_change_ok’

**Comment by Fabian-Gruenbichler** [comment]
this should be fixed in master (with https://github.com/zfsonlinux/zfs/commit/3b0ba3ba99b8a3af0fb532bf264629436b1abd84 )
