### ISSUE TITLE
Any guide for migrating archive.zfsonlinux.org repo to debian-backports?

### ISSUE THREAD

**Issue by caizixian** [zfsonlinux/zfs#5458]
According to https://github.com/zfsonlinux/zfs/wiki/Debian , APT repos on archive.zfsonlinux.org will not be updated and are not recommended for new installations.

But I noticed that there are some changes regarding package names. So simply removing old `/etc/apt/sources.list.d/zfsonlinux.list` and `echo "deb http://ftp.debian.org/debian jessie-backports main contrib" >> /etc/apt/sources.list.d/backports.list` will introduce some problems.

For example, packages `libnvpair1linux libuutil1linux libzfs2linux libzpool2linux` cannot replace `libnvpair1 libuutil1 libzfs2 libzpool2` directly, because they will overwrite files provided by latter group of packages, and therefore `dpkg` will fail. And packages `libnvpair1 libuutil1 libzfs2 libzpool2` cannot be removed either, because `grub-common` reports dependence on them.

Is there any recommended procedures for migrating archive.zfsonlinux.org repo to debian-backports?

**Comment by kpande** [comment]
Please use [the mailing list](http://list.zfsonlinux.org) for this kind of distribution specific support request

**Comment by beren12** [comment]
One last tip, you can also do

```
cd /var/cache/apt/archives

sudo dpkg -i --force-overwrite libuutil1linux_* libnvpair1linux_* libzpool2linux_* libzfs2linux_* zfsutils-linux_* zfs-zed_*
```

because debian changed package names

**Comment by caizixian** [comment]
@beren12 Thanks.

**Comment by meteozond** [comment]
As for me mailing list is quite complicated difficult to browse legacy tool, so here is our migration workaround, if someone needed.

Completely remove old version
```
aptitude purge -y \
libzfs2 \
libzfs2linux \
zfs-dkms   \
zfs-zed   \
zfsonlinux \
zfsutils \
zfsutils-linux \
libzpool2linux \
libuutil1linux \
libnvpair1linux \
zfsonlinux \
debian-zfs 
```

Add backports repo
```
echo "deb http://ftp.debian.org/debian jessie-backports main contrib" >> /etc/apt/sources.list.d/backports.list && \
apt update && \
apt install linux-headers-$(uname -r) && \
apt-get install -t jessie-backports zfs-dkms
```

Re-install
```
aptitude install -y -t jessie-backports zfs-dkms
```

Re-install grub if removed for some wired reason
```
aptitude install -y \
grub-common \
grub-pc \
grub-pc-bin \
grub2-common
```
