### ISSUE TITLE
What *should* txg be on new pool?

### ISSUE THREAD

**Issue by toddcurry** [zfsonlinux/zfs#5460]
I have two pools and txg values that are 640,000x different.

'sudo zdb' on two 6 x 4TB RaidZ2 pools:
- Old pool, 85% full, created with Ubuntu 16.04 and latest ZFS (at that time):  txg of 2,558,812
- New pool, 0% full, created with ubuntu 16.04.1 with latest ZFS, txg of 4.   
[update:  just did zdb and txg on old pool is now 2,655,127, which is 4% increase in 4 days]

Are these txg values established at instantiation?  Should they grow over time?  Are they timeout values, in which case 2.5M seconds is a very long timeout.   Thoughts, please?

    `tank1:  
    version: 5000
    name: 'tank1'
    state: 0
    txg: 2655127
    pool_guid: 17254055283463926692
    errata: 0
    hostname: 'veronica'
    vdev_children: 1
    vdev_tree:
        type: 'root'
        id: 0
        guid: 17254055283463926692
        children[0]:
            type: 'raidz'
            id: 0
            guid: 11220465842454891957
            nparity: 2
            metaslab_array: 34
            metaslab_shift: 37
            ashift: 9
            asize: 24004631986176
            is_log: 0
            create_txg: 4
            children[0]:
                type: 'disk'
                id: 0
                guid: 18435459050442703723
                path: '/dev/disk/by-id/scsi-35000c***f7-part1'
                whole_disk: 1
                DTL: 468
                create_txg: 4
[all other children identical]`

and new tank:

    `ptank22:
	version: 5000
	name: 'ptank22'
	state: 0
	txg: 4
	pool_guid: 13581898166879535613
	errata: 0
	hostname: 'foo'
	vdev_children: 1
	vdev_tree:
		type: 'root'
		id: 0
		guid: 13581898166879535613
		create_txg: 4

		children[0]:
			type: 'raidz'
			id: 0
			guid: 10036536211960924462
			nparity: 2
			metaslab_array: 35
			metaslab_shift: 37
			ashift: 9
			asize: 24004680744960
			is_log: 0
			create_txg: 4

			children[0]:
				type: 'disk'
				id: 0
				guid: 2719522612282591943
				path: '/dev/mapper/scsi-85e216ff-enc'
				whole_disk: 0
				create_txg: 4

[all other children identical]`

**Comment by aikudinov** [comment]
Yes, txg increases over time with writes to the pool.
https://www.delphix.com/blog/delphix-engineering/zfs-fundamentals-transaction-groups

Also, this is a bug tracker, not a forum - please use mailing lists for questions.

**Comment by toddcurry** [comment]
Thanks aikudinov, could you point to an article that actually describes the mechanism by which ZFS increases txg over time -- why, on what basis, with what intent.  Your link to a generic 101 article on transaction groups is insulting, considering the time I spent googling and actually reading the code here before I reported the issue.  

Also, the 1990s called:  AOL would like to send you a CD with 1000 free hours to go with your "mailing list" for questions. </snark>

**Comment by kpande** [comment]
http://dtrace.org/blogs/ahl/2012/12/13/zfs-fundamentals-transaction-groups/

it's a shame that I found this within 5 seconds of typing "zfs txg 4" into google, when you couldn't do the same.

please watch your tone, we're all volunteers here and it's easy enough to ban you to avoid white noise.

**Comment by toddcurry** [comment]
Absolutely nothing in that article, Kpande, describes a monotonic increase in txg over time (please note that if you had actually googled those terms with quotes, you would have gotten no results, which is something I tried several days ago, before digging into Illumos, FreeNAS and code here).  

Txg of 2.6M on a pool may be a bug -- it may indicate that there is some runaway process that does, for no good reason, increase a timing stat monotonically.  Could be a problem.   Hence, it probably deserves a little bit of dissection.   Will it really hold a write for 2.6 million seconds?  Probably not, but what over-rides it?  Why wouldn't a proper scrub reset it?  What code might be in play?  Hey, I'm happy to take a look -- let's discuss that part, please! 

Appreciate the comment on tone, but having snarky door minders like the first guy isn't going to make the party any better.
