### ISSUE TITLE
problem download and packages upgrade - debian

### ISSUE THREAD

**Issue by oklimemilko** [zfsonlinux/zfs#5462]
```
sudo -i
# wget http://archive.zfsonlinux.org/debian/pool/main/z/zfsonlinux/zfsonlinux_6_all.deb
# dpkg -i zfsonlinux_6_all.deb
```
.....
I did upgrade my debian 8.1 amd64 linux and system was crashed. I did apt-get update && apt-get upgrade my debian 8.1 linux and system was crashed after reboot. Module was not found inside ramdisk

**Comment by kpande** [comment]
this is a support request, the archive referenced above is not supported. please use [the mailing list](http://list.zfsonlinux.org) or IRC for further discussion.
