### ISSUE TITLE
Zpool import -t is actually alterting pool names on master

### ISSUE THREAD

**Issue by sempervictus** [zfsonlinux/zfs#5466]
Running master from a week ago, i realized today that pools i've been working on have been altered - their names were changed during _zpool import -t poolTempName poolName_.

Not sure where or when the regression happened, but this should probably be fixed, kind of a breaking "change" when VMs suddenly dont boot for being unable to find their rpool...

**Comment by behlendorf** [comment]
We absolutely need to fix this before the release.  @ryao can you look in to this regression and propose a fix with a test case for this feature.

**Comment by sempervictus** [comment]
@ryao: i imagine you're currently eyeball-deep in the end of Q4 like the rest of us :). I took a quick look at the changes you made to allow the temporary names to be used inside module/zfs/spa_config.c as well as the delta since then (2013? really? i remember asking for that like it was yesterday :) )... there's been too much churn for me to quickly trace what happens to the spa config as relating to the ZFS_IMPORT_TEMP_NAME flag.
Far as i know, this worked in the spring. Since then, we've only seen 3 changes in module/zfs/spa_config.c - fb390aafc8, ccc92611b1bd, and 02730c333c4, and nothing in those commits looks like it should be breaking this functionality.
Are there any environment, kernel, or build variables which could cause the -t flag to be ignored on import? Thanks

**Comment by loli10K** [comment]
I had some spare cpu cycles during lunch, so i used those to learn automated git bisecting and find the commit that broke this functionality: https://github.com/zfsonlinux/zfs/commit/e0ab3ab553e36595344d9cbdc240d380ad203b60 (_OpenZFS 6736 - ZFS per-vdev ZAPs_).

Illumos is not affected because they don't have temporary pool names (!?)
