### ISSUE TITLE
kernel panic during boot near import (4.8.11 + grsec)

### ISSUE THREAD

**Issue by bunder2015** [zfsonlinux/zfs#5468]
upgrading from 4.3.4 to 4.8.11 as well as from 0.6.5.6 to git head, using hardened.  system panics during boot either during or immediately after import.

sorry for the horrible quality...  http://i.imgur.com/GJza8rL.jpg

kernel configs for reference...
4.3.4 - https://paste.pound-python.org/show/0msGOEagGFI5M4YXa7WK/
4.8.11 - https://paste.pound-python.org/show/O0a4F1RN2CJwl6gZCYPQ/
diff for reference - https://www.diffchecker.com/IT899b1l

i'm not sure if this config related, it could be that i'm using an option that isn't supported.  i've checked to make sure that RAP is turned off.  sadly the panic message scrolls past the screen ultra fast, so i'm not sure what actually caused the panic...  hopefully the stack dump and configs will help.

i'm also not sure if this is a bug or not, but PMT told me to post it so we can get some eyes on it.

thanks

**Comment by loli10K** [comment]
Possibly related to https://github.com/torvalds/linux/commit/f5509cc18daa7f82bcc553be70df2117c8eedc16 (_mm: Hardened usercopy_)?

`__check_object_size` (from your backtrace) was introduced in that commit and is controlled by `CONFIG_HARDENED_USERCOPY` which you have set to `y` in the new config.

**Comment by bunder2015** [comment]
Good catch.  Must have been enabled by default when I upgraded.  I will check this tomorrow and check back.  Thanks

**Comment by bunder2015** [comment]
I'm going to close this as I was also having problems upgrading to hardened 4.7 and 4.4, and I've since been able to boot into hardened 4.4.  It might be possible I was doing something wrong.

**Comment by loli10K** [comment]
@bunder2015 https://github.com/torvalds/linux/commit/f5509cc18daa7f82bcc553be70df2117c8eedc16 landed in v4.8, so it's still possible this is a problem with HARDENED_USERCOPY=y and v4.8+, it could be useful to keep it open until we confirm this is not the case.

**Comment by bunder2015** [comment]
As you wish.  As luck would have it, I also received a reply from the PAX team after I closed my gentoo bug.  I can't keep rebooting that machine for testing, so hopefully someone else can pick up where I left off.

https://bugs.gentoo.org/show_bug.cgi?id=603188#c7

> what we would need is dmesg as your screenshot is just missing the lines where USERCOPY reported the slab cache name that was caught during a usercopy operation. my guess is that one/some of zfs's own slabs should be created via kmem_cache_create_usercopy/KMEM_CACHE_USERCOPY instead of kmem_cache_create/KMEM_CACHE.

**Comment by loli10K** [comment]
> my guess is that one/some of zfs's own slabs should be created via kmem_cache_create_usercopy/KMEM_CACHE_USERCOPY instead of kmem_cache_create/KMEM_CACHE.

This may be related to https://github.com/zfsonlinux/spl/pull/595 (_Add support for recent kmem_cache_create_usercopy_)

**Comment by behlendorf** [comment]
@loli10K is correct, yhis should be address by zfsonlinux/spl#595 which has been merged to master.  You'll need to make sure to update the SPL to pull in the fix.  Closing, but definitely let us know if for some reason that doesn't address your issue.
