### ISSUE TITLE
chattr immutable broken on zfs (master)

### ISSUE THREAD

**Issue by edillmann** [zfsonlinux/zfs#5469]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | ubuntu
Distribution Version    | 16.04
Linux Kernel                 | 4.4.0-51-lowlatency
Architecture                 |  x86_64
ZFS Version                  | 0.7.0-rc2
SPL Version                  | 0.7.0-rc2

### Describe the problem you're observing
chattr is not working properly on zfs

### Simple reproducer

```
touch testfile
chattr -i testfile
touch testfile
touch: cannot touch 'testfile': Permission denied

lsattr testfile
---------------- testfile
```

**Comment by loli10K** [comment]
Probably introduced in https://github.com/zfsonlinux/zfs/commit/64c688d7161daac0a799b11b40cb791f6fd264db (_Refactor updating of immutable/appendonly flags_), i can't reproduce with its parent commit.

Fortunately this doesn't seem to persist on disk, a possible workaround is to remount the filesystem.

**Comment by dweeezil** [comment]
See #5470 for a fix.

**Comment by edillmann** [comment]
That was a quick fix, it work's for me, thanks
