### ISSUE TITLE
arcstats l2_size accounting error

### ISSUE THREAD

**Issue by AndCycle** [zfsonlinux/zfs#5474]
gentoo 
Linux kernel ver. 4.4.26-gentoo
spl ver. 0.6.5.8-r0-gentoo
zfs ver. 0.6.5.8-r0-gentoo

I just removed all L2ARC from my system because they doesn't seems to help much in my case,
but I found there is a weird mismatch on arcstats,
as arcstats shows l2_size is not zero after I remove all L2ARC,

```
l2_hits                         4    29668114
l2_misses                       4    2442141926
l2_feeds                        4    2168607
l2_rw_clash                     4    18
l2_read_bytes                   4    1824548642816
l2_write_bytes                  4    2347059627008
l2_writes_sent                  4    1791623
l2_writes_done                  4    1791623
l2_writes_error                 4    0
l2_writes_lock_retry            4    92
l2_evict_lock_retry             4    27
l2_evict_reading                4    107
l2_evict_l1cached               4    1501905
l2_free_on_write                4    139788
l2_cdata_free_on_write          4    1098
l2_abort_lowmem                 4    0
l2_cksum_bad                    4    0
l2_io_error                     4    0
l2_size                         4    13586432
l2_asize                        4    0
l2_hdr_size                     4    0
l2_compress_successes           4    18637071
l2_compress_zeros               4    0
l2_compress_failures            4    16106066

```

**Comment by behlendorf** [comment]
I believe this issue was addressed post 0.6.5.x.  If possible could you verify on a test system that the issue doesn't appear in 0.7.0-rc2 or newer?

**Comment by AndCycle** [comment]
as I don't have another system for testing, I will wait for 0.7.0 release.

**Comment by loli10K** [comment]
> I will wait for 0.7.0 release.

@AndCycle is this still an issue with 0.7.0? Can we close this?

**Comment by AndCycle** [comment]
@loli10K I am not able to run 0.7.1 without panic, 
so this will gonna live for a while longer or if anyone else can do test it out,

this stats mismatch should be easy to reproduce on 0.6.5.11 by 

attach an L2ARC, 
running some metadata bench to produce workload for a while, 
then removing L2ARC,

on my system this can be easily reproduce in one day.

**Comment by behlendorf** [comment]
@AndCycle which issue is preventing you from running 0.7.1 again?

**Comment by AndCycle** [comment]
@behlendorf this one, https://github.com/zfsonlinux/zfs/issues/6522
I have no issue with v0.6.5.11
