### ISSUE TITLE
Want wiki article about hole_birth

### ISSUE THREAD

**Issue by rincebrain** [zfsonlinux/zfs#5483]
Wrote wiki article for hole_birth bug, but there's no equivalent for PRs for the wiki.

http://pastebin.com/cVCxBzqu was the thing I wrote. I'd tag this Documentation, but I don't think I have the ability to tag my own things either.

**Comment by rlaager** [comment]
Can you checkout the wiki like this:
git clone https://github.com/zfsonlinux/zfs.wiki.git

Then make your changes, commit them, run `git format-patch`, and submit that?

I assume we'll want to link this from the existing FAQ page. Or maybe put this inline in the FAQ?

**Comment by rincebrain** [comment]
Sure.

http://pastebin.com/Xen3APcy

**Comment by rlaager** [comment]
Added. Thanks!

**Comment by behlendorf** [comment]
Thanks!  Here the [link](https://github.com/zfsonlinux/zfs/wiki/hole_birth-FAQ) to the added wiki page.
