### ISSUE TITLE
Intermittent ZFS build configuration errors

### ISSUE THREAD

**Issue by pstch** [zfsonlinux/zfs#5485]
### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Debian
Distribution Version    |  Jessie 8.6
Linux Kernel                 |  Linux gramsci 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux
Architecture                 |  amd64
ZFS Version                  |  Not installed
SPL Version                  |  0.7.0-rc2_4_gf200b83

### Describe the problem you're observing

Intermittently, one of the checks in the `./configure` scripts fails, with a message linking to this page (new issue):

```
checking whether current->bio_tail exists... no
checking whether current->bio_list exists... configure: error: no - Please file a bug report at
			    https://github.com/zfsonlinux/zfs/issues/new
```

([Full log](https://gist.github.com/pstch/d1f4f4e63a014193c101a4d63343e649))
### Describe how to reproduce the problem

It happened a few times, and now I'm having trouble reproducing it. Nothing change on the machine, it's an official Debian live build that has only installed build dependencies, compiled SPL and attempted to configure ZFS.

I'm not really sure that this is a serious issue, as it's intermittent and I didn't find a way to reproduce it in a deterministic way, but the error message asked me to file a bug report.

**Comment by behlendorf** [comment]
@pstch if you observe this again please grab the `config.log` from the top level build directory.  That should show exactly why this check failed.  The "Full log" link you posted above also appears to link to the new issue page.

**Comment by pstch** [comment]
Oops, I fixed the link, although it's not very useful as it's just the output of `./configure`. I will make sure to grab the `config.log` if this happens again.
