### ISSUE TITLE
arc_summary.py require review to proper reflect actual value for ZoL

### ISSUE THREAD

**Issue by AndCycle** [zfsonlinux/zfs#5526]
this is just a note about this script, 

as I am working with a munin plugin to proper present ZoL stats,
I found that arc_sumary.py is original written for FreeBSD, 
and some of the arcstats it use to summarize the result is not actual value on ZoL.

for example,
`p` is stand for target size of MRU
so it use `p` as `MRU size` ,
`size-p` as `MFU size`,

on ZoL we do have independent `mru_size` and `mfu_size` value,
on my system `MRU size` is far off `p` which result in wrong conclusion for `ARC Size Breakdown`,

so I think this script require some review.

**Comment by richardelling** [comment]
p is the MRU target size, not the actual size

I suggest if you are writing an agent to go directly to the arc.c source for details and get the values directly from the /proc/spl/kstat/zfs/* rather than an intermediary script such as arc_summary

**Comment by AndCycle** [comment]
that's what I am doing right now,

as arc_summary.py is included in current ZoL,
I just get some reference from it in order to find out what's matter,
