### ISSUE TITLE
Can't add log (mirror) to existing zpool

### ISSUE THREAD

**Issue by seanmahrt** [zfsonlinux/zfs#5539]
I'm trying to add a mirror of two partitions on my SSD as a ZIL.  I think I have the command correctly...

sean@myth:~$ sudo zpool add bigpool log mirror /dev/disk/by-id/ata-Patriot_Pyro_PT1206A00061293-part2 /dev/disk/by-id/ata-Patriot_Pyro_PT1210A00076434-part2
cannot add to 'bigpool': one or more devices is currently unavailable

I also tried not adding it as a mirror, and I get the same error.  I've rebooted a couple times to no avail.  I haven't exported/imported the pool, but it's a fresh pool created about a month ago.

Any suggestions are appreciated!

------

Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-57-generic x86_64)
ZFS version:        0.6.5.6-0ubuntu15
SPL version:        0.6.5.6-0ubuntu4

Zpool information:

  pool: bigpool
 state: ONLINE
  scan: scrub repaired 0 in 2h36m with 0 errors on Sun Dec 25 10:55:32 2016
config:

	NAME                                      STATE     READ WRITE CKSUM
	bigpool                                   ONLINE       0     0     0
	  raidz2-0                                ONLINE       0     0     0
	    ata-ST32000644NS_9WM58D5S             ONLINE       0     0     0
	    ata-ST32000644NS_9WM5JW4T             ONLINE       0     0     0
	    ata-ST32000644NS_9WM5FXZ7             ONLINE       0     0     0
	    ata-ST2000VN000-1HJ164_W5224E89       ONLINE       0     0     0
	    ata-Hitachi_HUA723020ALA641_YFHJ6RRA  ONLINE       0     0     0
	    ata-ST32000644NS_9WM5EY7D             ONLINE       0     0     0
	cache
	  ata-Patriot_Pyro_PT1206A00061293-part3  ONLINE       0     0     0
	  ata-Patriot_Pyro_PT1210A00076434-part3  ONLINE       0     0     0
------

**Comment by kpande** [comment]
please use [the mailing list](http://list.zfsonlinux.org) for support requests, this is not a bug. thank you!
