### ISSUE TITLE
ZFS build fails on 4.9 kernel: testing repo needs latest

### ISSUE THREAD

**Issue by h1z1** [zfsonlinux/zfs#5541]
### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | CentOS
Distribution Version    | 6.8
Linux Kernel                 | kernel-ml 4.9.0-1.el6.elrepo
Architecture                 | x86_64
ZFS Version                  | 0.7.0-rc2
SPL Version                  | 0.7.0-rc2

### Describe the problem you're observing

RPM install of zfs module fails to build

### Describe how to reproduce the problem

i) Install zfs repo as per wiki https://github.com/zfsonlinux/zfs/wiki/RHEL-%26-CentOS

ii) Module will fail to build as per Issue #5393

### Include any warning/errors/backtraces from the system logs
```
  CC [M]  /var/lib/dkms/zfs/0.7.0/build/module/zfs/zpl_inode.o
/var/lib/dkms/zfs/0.7.0/build/module/zfs/zpl_file.c:841: error: unknown field ‘aio_fsync’ specified in initializer
/var/lib/dkms/zfs/0.7.0/build/module/zfs/zpl_file.c:841: warning: initialization from incompatible pointer type
make[5]: *** [/var/lib/dkms/zfs/0.7.0/build/module/zfs/zpl_file.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [/var/lib/dkms/zfs/0.7.0/build/module/zfs] Error 2
make[3]: *** [_module_/var/lib/dkms/zfs/0.7.0/build/module] Error 2
make[3]: Leaving directory `/usr/src/kernels/4.9.0-1.el6.elrepo.x86_64'

```

Possibly related(?) latest _release_ depends on a Fedora release dkms-2.2.0-20+, that is only available on CentOS from _epel-testing_ (dkms-2.3-1.20161202gitde1dca9.el6.noarch).  dkms-2.2.0.3-14 is the latest.

**Comment by loli10K** [comment]
@h1z1 Fixed in master https://github.com/zfsonlinux/zfs/pull/5398

@gmelikov can we add "search for closed PRs before opening a new issue" on the Wiki?

**Comment by gmelikov** [comment]
@loli10K it's already in CONTRIBUTING.md, but it's a good idea to add this info to ISSUE_TEMPLATE.md, i'll do it.

**Comment by h1z1** [comment]
Understood, should that be in the testing repo yet?

[~]# grep -R HAVE_FILE_AIO_FSYNC /usr/src/zfs-0.7.0/*
[~]#

**Comment by loli10K** [comment]
@h1z1 i don't use RHEL/CentOS packages but since https://github.com/zfsonlinux/zfs/commit/7ca25051b6470e8471b4ed454d8c66ff21338de3 has not landed in any tagged (pre-)release yet i don't think it is.

If you *really* need the latest bits and you know exactly what you're doing you should compile from source.

**Comment by h1z1** [comment]
I'll try.  It will be an issue for anyone updating though.

**Comment by h1z1** [comment]
Finally got back to this - Rebuilding with latest from git compiles fine.  Anyone building on newer kernels will need to do it manually until the rpm is updated.
