### ISSUE TITLE
zinject contains spelling mistake of hexadecimal

### ISSUE THREAD

**Issue by ColinIanKing** [zfsonlinux/zfs#5546]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  n/a
Distribution Version    |  n/a
Linux Kernel                 | n/a
Architecture                 |  n/a
ZFS Version                  |  zfs-0.7.0-rc2
SPL Version                  | n/a

### Describe the problem you're observing

Spelling mistake of hexadecimal in zinject source and man page, currently spelled as "hexidecimal", should be "hexadecimal"

**Comment by bunder2015** [comment]
Looks like two of these are already covered in #5543.

**Comment by behlendorf** [comment]
Resolved by #5543.
