### ISSUE TITLE
zfs mount -a should give higher priority to root pool

### ISSUE THREAD

**Issue by AndrewJDR** [zfsonlinux/zfs#5562]
Currently, if the same mountpoint exists on two or more pools, the mount behavior for ```zfs mount -a``` appears to be non-deterministic. For example, if both rpool and xpool contain an effective mountpoint ```/var/tmp```, either ```rpool/var/tmp``` or ```xpool/var/tmp``` could be mounted.

It would be very nice if ```zfs mount -a``` gave higher priority to any mounpoints on the same pool as ```/``` is mounted from. An easy way to achieve this might be to work through the potential mounts in the order that the pools were imported. Since the root pool will always be imported first, this would likely be sufficient to achieve the goal of giving priority to mountpoints on the root pool.

As for the reason this would be nice:
If you're doing zfs send / zfs recv stuff for the purposes of backup (say between rpool -> xpool in my example), the mounpoints get sent as well, and on the next bootup some of the child datasets on xpool will get mounted instead of from rpool -- that is typically not desired. If zfs mount -a simply prioritized mountpoints on the root pool, this wouldn't really be an issue.
(I think i can set canmount=off on the receiving datasets, but that is particularly elegant, and complicates the process of using xpool to boot from in failover situations)

**Comment by kpande** [comment]
in my experience, the root pool (and all of its filesystems) are explicitly mounted by the initrd (dracut, genkernel, initramfs-tools) and if yours is not doing this, it is a bug with the implementation.
