### ISSUE TITLE
ZFS not creating correct extended attributes (xattr) via samba

### ISSUE THREAD

**Issue by waltersteinlein** [zfsonlinux/zfs#5568]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  CentOS
Distribution Version    |  7.2
Linux Kernel                 |  3.10.0
Architecture                 |  x86_64
ZFS Version                  |  0.7.0-rc2
SPL Version                  |  0.7.0-rc2

### Describe the problem you're observing
I've shared two identical file systems on the same pool via samba. Creating a file (through samba) on both of them result in different extended file attributes:

```
# getfattr test/testfile.txt 
# file: test/testfile.txt
user.DOSATTRIB
user.SAMBA_PAI
```

```
# getfattr data/testfile.txt 
# file: data/testfile.txt
user.SAMBA_PAI
```

(Note: The two filesystems are data and test)

```
# zfs get -r xattr tank
NAME                         PROPERTY  VALUE  SOURCE
tank                         xattr     sa     local
tank/data                    xattr     sa     inherited from tank
tank/test                    xattr     sa     inherited from tank
```

ACLs for both files and parent directory are identical (as show by getfacl). Filesystems are mounted (by zfs) with xattr support 

```
# mount | grep tank
tank on /tank type zfs (rw,noatime,mand,xattr,posixacl)
tank/test on /tank/test type zfs (rw,noatime,mand,xattr,posixacl)
tank/data on /tank/data type zfs (rw,noatime,mand,xattr,posixacl)
```

Samba configuration for both shares are identical;

```
[data]
   path = /tank/data
   guest ok = no
   read only = no
   browsable = yes
   inherit permissions = yes

[test]
   path = /tank/test
   guest ok = no
   read only = no
   browsable = yes
   inherit permissions = yes
```

As a result, I cannot change the DOS flags (such as read-only or archive) on the data share (while I can on the tank share). I can however change the extended attributes manually

```
# setfattr -n user.DOSATTRIB data/testfile.txt 
# getfattr data/testfile.txt 
# file: data/testfile.txt
user.DOSATTRIB
user.SAMBA_PAI
```

but afterward, the DOS flags are still not changeable through samba. ZFS seems to ignore this setting.

This could very well be a samba bug, but since it works just fine on an ext4 fs I suspect there's something on the zfs side of things going wrong.

### Include any warning/errors/backtraces from the system logs
No entires in syslog. Not sure what I could include to help track this down.

**Comment by waltersteinlein** [comment]
Unfortunately I cannot reproduce the problem on a different machine. There's just this one filesystem that's bugged out and every new filesystem I create on the same pool (such as 'test') above works just fine. I could work around this by re-creating the original filesystem and copying the file over, but I'd like to avoid this since it contains about 50TiB of data.
Also, I'd like to help track this down since it could happen again.

**Comment by waltersteinlein** [comment]
Ok, I found out how to find the inode infomation for a particular file:

```
# zdb -vvvv tank/data 155207758
Dataset tank/data [ZPL], ID 46, cr_txg 97, 41.1T, 41066553 objects, rootbp DVA[0]=<3:9b052869c00:600> DVA[1]=<0:1424ff484800:600> [L0 DMU objset] fletcher4 lz4 LE contiguous unique double size=800L/200P birth=2895887L/2895887P fill=41066553 cksum=154abe7f32:6d9c1966300:1411549ac3557:2a731bf9e53fbe

    Object  lvl   iblk   dblk  dsize  dnsize  lsize   %full  type
 155207758    1    16K  17.5K  3.50K     512  17.5K  100.00  ZFS plain file
                                               240   bonus  System attributes
        dnode flags: USED_BYTES USERUSED_ACCOUNTED 
        dnode maxblkid: 0
        path    /shelf.mel
        uid     101265
        gid     104188
        atime   Thu Dec 22 18:03:25 2016
        mtime   Thu Dec 22 18:03:25 2016
        ctime   Fri Jan  6 22:58:44 2017
        crtime  Thu Dec 22 18:03:25 2016
        gen     2607116
        mode    100775
        size    17750
        parent  390353
        links   1
        pflags  40800000004
        xattr   155207759
        SA xattrs: 56 bytes, 1 entries

                user.DOSATTRIB = 
Indirect blocks:
               0 L0 2:150008e2f000:1200 4600L/a00P F=1 B=2607116/2607116

                segment [0000000000000000, 0000000000004600) size 17.5K
```
so the DOSATTRIB is empty while is is valid on the 'test' filesystem mentioned above.

**Comment by waltersteinlein** [comment]
Ok, even when setting the correct user.DOSATTRIB user.SAMBA_PAI and security.NTACL values, it doesn't work. Could it somehow be that there's still xattr data in the direcotry that zfs uses if xattr=on and that somehow interferes with the xattr data in the inodes?

**Comment by waltersteinlein** [comment]
Hmm, the part that reads

```
               0 L0 EMBEDDED et=0 200L/53P B=2896860

                segment [0000000000000000, 0000000000000200) size   512
```

is not present on the files of the 'working' filesystem.

**Comment by waltersteinlein** [comment]
And I'm getting a ton of

`WARNING: ZFS: inode ffff881ca3c39e38 has xattr "user.DOSATTRIB" in both SA and dir`

in the kernel log on lots of different inodes :(

**Comment by beren12** [comment]
Have you seen https://wiki.samba.org/index.php/Setting_up_a_Share_Using_Windows_ACLs?

**Comment by waltersteinlein** [comment]
Thanks for the input. Could you be a bit more verbose?
The tl;dr version of my problem is: Got a file, can't set the DOS attributes on one filesystem, works fine when copying the file to another file system. ACLs work fine, it's just the DOS attributes. I suspect that's because those are stored in SA as well as dir.

**Comment by tuxoko** [comment]
> WARNING: ZFS: inode ffff881ca3c39e38 has xattr "user.DOSATTRIB" in both SA and dir

This is likely because of bug in xattr in old zfs. You can clear them by setting the xattr again in new version.

**Comment by waltersteinlein** [comment]
You mean despite

```
NAME                         PROPERTY  VALUE  SOURCE
tank                         xattr     sa     local
tank/data                    xattr     sa     inherited from tank
```

just do `zfs set xattr=sa tank` again?

**Comment by tuxoko** [comment]
No, I mean setfattr on the file.
Though, I should have print inode number in the warning message. The pointer value doesn't help figure out which file at all...

**Comment by tuxoko** [comment]
Use this to get the inode number if you don't know which files are affected

```diff
diff --git a/module/zfs/zpl_xattr.c b/module/zfs/zpl_xattr.c
index 7186e47..22ea670 100644
--- a/module/zfs/zpl_xattr.c
+++ b/module/zfs/zpl_xattr.c
@@ -398,8 +398,8 @@ __zpl_xattr_where(struct inode *ip, const char *name, int *where, cred_t *cr)
 		return (error);
 
 	if (*where == (XATTR_IN_SA|XATTR_IN_DIR))
-		cmn_err(CE_WARN, "ZFS: inode %p has xattr \"%s\""
-		    " in both SA and dir", ip, name);
+		cmn_err(CE_WARN, "ZFS: inode %lu has xattr \"%s\""
+		    " in both SA and dir", ip->i_ino, name);
 	if (*where == XATTR_NOENT)
 		error = -ENODATA;
 	else
```

**Comment by waltersteinlein** [comment]
Thanks. Been there done that. The kernel warning might have gone away for the inodes I've touched but I still can change the DOSATTRIB through samba (or even read it after setting it on the inode directly). I'm pretty sure this is a zfs bug since copying the file to another fs fixes the issue (same host, same samba config/version). I'd love to avoid copying 60TiB around though.

**Comment by tuxoko** [comment]
I don't understand what those xattr are for, and I don't understand what do you want to do with the DOSATTRIB and why is it important. If you want to remove then just setfattr -x.

All I can say is that the known bugs for xattr are fixed in ZFS, and while you still have the relics from the old bug (the above warning), it is fixable when you do setfattr.

**Comment by waltersteinlein** [comment]
Well the DOSATTRIBS are used for storing the SYSTEM, HIDDEN, ARCHIVE or READ-ONLY attributes.
I can remove them with `setfattr -x` and also set them so zdb is showing me the values I'm expecting. Samba however is completely ignoring everything I set through `setfattr`. This is however limited to one particular zfs file system. Works fine on another one, works fine when I copy the file to another one. If nobody cares, it's good enough for me since I can work around it by copying my files away. But I think this issue will pop up somewhere else again.
I also don't know what I could do to track this down further. I'd gladly provide any information that might help solve this but currently I just don't know how to debug this issue.
