### ISSUE TITLE
High i/o load when doing scrub but the strange thing is that I have to reboot an NFS client in order to fix it ?

### ISSUE THREAD

**Issue by SanderM2** [zfsonlinux/zfs#5570]
I have two boxes. One box is running ZoL as a raid mirror over 6x6Tb disks. The storage is exported over NFS to the second box. The second box is running a webserver.

When I do "zpool scrub data" on the ZoL box the disk i/o load starts to go up and stay at 100%. The 5-min load on the webserver box goes up to 150 and higher. If I do "zpool scrub -s data" in order to stop the scrub process, nothing changes at the load. So the load stays tooo high.

If I kill the webserver, the loads goes down to 0. Pretty normal offcourse.. But if I restart the webserver the load goes up again, disk i/o goes back to 100% too... Very strange! Disk load is usally <= 2%. It's not a highly loaded system...

If I reboot the webserver everything goes back to normal and loads is at the normal values again.
But if I do "zpool scrub data" again, it all behaves the same as explain above. I can repeat the process over and over again with the same results.

I have no idea what the issue could be. It seems like there's an issue with NFS + Scrubbing at the same time but then again. I have no idea why rebooting the client would help.

Any thoughts?

**Comment by SanderM2** [comment]
I just installed 4 disks from an old zfs pool in this ZoL box and imported that ZFS pool too.
So these 4 disks are not even used by the webserver. I then started a scrub on those disks and instantly saw my disk load going up on ALL disks, in cluding the 6x6Tb ones. Webserver load went up again etc... same as before when doing the scrub on the original disks.

I'm puzzled.. this must be some bug, right?

**Comment by SanderM2** [comment]
Some more info about my ZoL system:

It's a Dell R510 with a H200 controller. 2x L5630 CPU's running ubuntu linux

# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial


# modinfo zfs | grep -iw version
version:        0.6.5.6-0ubuntu15

# modinfo spl | grep -iw version 
version:        0.6.5.6-0ubuntu4

# free -g
              total        used        free      shared  buff/cache   available
Mem:             94           1          40           0          52          43
Swap:            11           0          11

**Comment by SanderM2** [comment]
Maybe kernel version is important to know too? 

# uname -a
Linux st01 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by kpande** [comment]
please use [the mailing list](http://list.zfsonlinux.org) or IRC for support request, this is not a bug, rather, a configuration issue.
