### ISSUE TITLE
ZFS cannot import : I/O error

### ISSUE THREAD

**Issue by Maddin5** [zfsonlinux/zfs#5571]
Hi,

I experienced an error in my ZFS machine. My ZFS Pool is no longer willing to import. I always get the error: 

```cannot import 'Gewuerzglas': I/O error
        Destroy and re-create the pool from
        a backup source.
```
It seems that the data might be still there but some check sums gone bad? 
I already tried several things. Non seemed to work. Any suggestens how to rescue this pool?

What I have tried so far

```
root@openmediavault:~# zpool import
   pool: Gewuerzglas
     id: 15011586312885837941
  state: ONLINE
 action: The pool can be imported using its name or numeric identifier.
 config:
        Gewuerzglas  ONLINE
          raidz1-0  ONLINE
            sda     ONLINE
            sde     ONLINE
            sdj     ONLINE
            sdc     ONLINE
            sdg     ONLINE
            sdf     ONLINE
            sdi     ONLINE
            sdh     ONLINE
            sdd     ONLINE
```

```root@openmediavault:~# zpool import Gewuerzglas
cannot import 'Gewuerzglas': I/O error
        Destroy and re-create the pool from
        a backup source.
```
```root@openmediavault:~# zpool import -f Gewuerzglas
cannot import 'Gewuerzglas': I/O error
        Destroy and re-create the pool from
        a backup source.
```
```
root@openmediavault:~# zpool import -f -F Gewuerzglas
cannot import 'Gewuerzglas': I/O error
        Destroy and re-create the pool from
        a backup source.
```
```
root@openmediavault:~# zpool import -m -f -o readonly=on Gewuerzglas
cannot import 'Gewuerzglas': I/O error
        Destroy and re-create the pool from
        a backup source.
```
```
root@openmediavault:~# zpool import -f -F -n Gewuerzglas
```

Does not show anything

Anyone knows how to repair or rescue data? 

### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Openmdiavault
Distribution Version    | 3.0.59
Linux Kernel                 | Linux 3.16.0-4-amd64
Architecture                 | Debian
ZFS Version                  | version:        0.6.5.8-2~bpo8+1
SPL Version                  | version:        0.6.5.8-2~bpo8+2

**Comment by kpande** [comment]
please use [the mailing list](http://list.zfsonlinux.org) or IRC for support request, this does not appear to be a bug. if you do discover a bug that led to this state, feel free to re-open the issue.
