### ISSUE TITLE
splat: spl_kmem_alloc_warn leading to NULL dereference

### ISSUE THREAD

**Issue by jsalinasintel** [zfsonlinux/zfs#5574]
splat test should not use spl_kmem_alloc_warn leading to BUG: unable to handle kernel NULL pointer dereference at (null) #5574

Version Information 
=================================================================
Distribution Name       Centos 7.2  
Distribution Version     7.2 
Linux Kernel                3.10.0-327.36.3.el7.x86_64 
Architecture                 x86_64
ZFS Version                master  Dec 20th RPM/modinfo say: 0.7.0-rc2
SPL Version                master  Dec 20th RPM/modinfo say: 0.7.0-rc2  
Git Build Data              Revision: a3823f428deb8f15dd383dc6210b2e16926f4217
refs/remotes/origin/master
Built Branches              refs/remotes/origin/master: Build #186 of Revision a3823f428deb8f15dd383dc6210b2e16926f4217  (refs/remotes/origin/master)

Problem 
=================================================================
Splat is influenced by what is set in /sys/module/spl/parameters/spl_kmem_alloc_warn
if set too high this crash can be seen: BUG: unable to handle kernel NULL pointer dereference at           (null)

Reproduce
=================================================================  
cat /sys/module/spl/parameters/spl_kmem_alloc_warn
65536
echo "16777216" > /sys/module/spl/parameters/spl_kmem_alloc_warn
run splat 

Log detail 
=================================================================
BUG: unable to handle kernel NULL pointer dereference at           (null)

**Comment by behlendorf** [comment]
Closing.  Splat retired.
