### ISSUE TITLE
zpool iostat shows implausible numbers for cache drives

### ISSUE THREAD

**Issue by waltersteinlein** [zfsonlinux/zfs#5583]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  CentOS
Distribution Version    |  7.2.1511
Linux Kernel                 |  3.10.0
Architecture                 |  x86_64
ZFS Version                  |  0.7.0-rc2
SPL Version                  |  0.7.0-rc2

### Describe the problem you're observing
`zpool iostat <pool> -v` shows highly implausible numbers for cache drives on zfs 0.7.0-rc2 compared to v0.6.5.8.

```
> [...]
> cache                         -      -      -      -      -      -
>   wwn-0x55cd2e404c2814d7  4,24T  16,0E      9    126  80,8K  9,82M
>   wwn-0x55cd2e404c28141a  4,26T  16,0E     10    126  86,0K  9,81M
```

Those disks have a capacity of 200GB each (which is reflected in the v0.6.5.8 output) yet `zpool iostat` shows 4+TiB alloc and 16EiB free for those drives.

Note that the alloc value is growing continuously as well, which was not the case in v0.6.5.8.

**Comment by behlendorf** [comment]
This issue should have been resolved by commit 423e7b62613d0a359e488cf2599a44174d073805
