### ISSUE TITLE
 Linux ZFS port doesn't respect RLIMIT_FSIZE

### ISSUE THREAD

**Issue by ColinIanKing** [zfsonlinux/zfs#5587]
BugLink: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1656259

### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Ubuntu
Distribution Version    |  16.10, 17.04
Linux Kernel                 | 4.8.0-22-generic
Architecture                 | x86_64
ZFS Version                  | 0.6.5.8-0ubuntu1
SPL Version                  | 0.6.5.8-0ubuntu1

### Describe the problem you're observing

bash -c 'ulimit -f 1024; yes | head -n2097152' > /path/on/filesystem/under/test

On ext4, this test case prints something along the lines of:

 bash: line 1: 11274 Broken pipe yes
       11275 File size limit exceeded(core dumped) | head -n2097152

On ZFS, this test case incorrectly exits zero with no output, demonstrating that ZFS does not respect RLIMIT_FSIZE.

I asked a friend to run this on Solaris 5.10 and FreeBSD 10.0-CURRENT, and on those systems this test case correctly generates SIGXFSZ; so it seems that this is a bug in the Linux port of ZFS.

(This was discovered while tracking down Launchpad test suite failures under LXD on ZFS. Launchpad uses RLIMIT_FSIZE in one place to guard against bugs that cause debdiff to generate arbitrarily large amounts of output and fill the disk.)

### Describe how to reproduce the problem

bash -c 'ulimit -f 1024; yes | head -n2097152' > /path/on/filesystem/under/test

### Include any warning/errors/backtraces from the system logs

None.

**Comment by DeHackEd** [comment]
Looks like we need to call `inode_newsize_ok(const struct inode *inode, loff_t offset)` to determine if we have hit the limit. Function was added in 2.6.32 (torvalds/linux@25d9e2d15286281ec8) which makes it safe to use for us.

**Comment by tuxoko** [comment]
We need to add `generic_write_checks` as well.

**Comment by behlendorf** [comment]
@tuxoko can you please review #5588 as a potential fix for this issue.  It's been lightly tested with CentOS 7 and works as expected, I've open the PRs for the bots to test and to get feedback on the approach.
