### ISSUE TITLE
"zfs list -d <depth> -o name" output depth is wrong when -H is given 

### ISSUE THREAD

**Issue by mailinglists35** [zfsonlinux/zfs#5594]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | debian
Distribution Version    | stretch
Linux Kernel                 | 4.8.15-2
Architecture                 | amd64
ZFS Version                  | 0.7.0-rc2_104_g42b64e50c
SPL Version                  | 0.7.0-rc2_8_g8e99d66

### Describe the problem you're observing
```
root@linux:~# zfs list -t filesystem -d1 -H -o name pool/iphone
pool/iphone

root@linux:~# zfs list -t filesystem -d1 -o name pool/iphone
NAME
pool/iphone
pool/iphone/private
```

the output without -H seems to be the correct one, conform to the manual page which says

           -d depth

               Recursively  display  any children of the dataset, limiting the recursion to depth. A depth of 1 will dis‐
               play only the dataset and its direct children.

### Describe how to reproduce the problem
create recursive datasets, then list them with / without -H

**Comment by mailinglists35** [comment]
the same manual says nothing about -H altering the -d parameter

           -H

               Used for scripting mode. Do not print headers and separate fields by a single  tab  instead  of  arbitrary
               white space.

**Comment by mailinglists35** [comment]
so effectively when `-H` is used, `-d N` acts as `-d N-1`

**Comment by mailinglists35** [comment]
possibly related issue https://github.com/zfsonlinux/zfs/issues/4287

**Comment by kpande** [comment]
#4287 only affects Gentoo users on an old ebuild (not ending with -r0)

**Comment by kpande** [comment]
I think this is because your userland and kernel modules are mismatched, same as in the other issue you opened. I cannot reproduce this on either 0.7.0 (git HEAD) or 0.6.5 (stable branch)

**Comment by mailinglists35** [comment]
they are both from git master

**Comment by mailinglists35** [comment]
uhm, I was not running latest master at the time of reporting, but the other issue is indeed running latest master. updating to master makes this go away. closing.
