### ISSUE TITLE
Fedora 25 Update from Kernel 4.8 to 4.9 broke SPL

### ISSUE THREAD

**Issue by grizzlyfred** [zfsonlinux/zfs#5602]
I think something similar was in manjaro a while ago, when kernel 4.9 was fresh.
I am sorry that cc thinks it must speak german... But I think the lines and problems are obvious.
The userland get installed, but no kernel module and thus no pools

/var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-cred.c: In Funktion »splat_cred_test3«:
/var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-cred.c:191:20: Fehler: »NGROUPS_SMALL« nicht deklariert (erste Benutzung in dieser Funktion)
  gi = groups_alloc(NGROUPS_SMALL);
                    ^~~~~~~~~~~~~
/var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-cred.c:191:20: Anmerkung: jeder nicht deklarierte Bezeichner wird nur einmal für jede Funktion, in der er vorkommt, gemeldet
/var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-cred.c:203:3: Fehler: Implizite Deklaration der Funktion »GROUP_AT« [-Werror=implicit-function-declaration]
   GROUP_AT(gi, i) = make_kgid(current_user_ns(), tmp_gid);
   ^~~~~~~~

/var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-cred.c:203:19: Fehler: Als linker Operand einer Zuweisung wird L-Wert erfordert
   GROUP_AT(gi, i) = make_kgid(current_user_ns(), tmp_gid);

**Comment by mskarbek** [comment]
Kernel 4.9 is not supported by 0.6.5.8, we will have to wait for 0.6.5.9 or 0.7.0.

**Comment by dkscully** [comment]
I would note that 0.7.0 rc2 is also broken with the 4.9.3 kernel from F25.

  CC [M]  /var/lib/dkms/zfs/0.7.0/build/module/zfs/zpl_xattr.o
/var/lib/dkms/zfs/0.7.0/build/module/zfs/zpl_file.c:841:2: error: unknown field ‘aio_fsync’ specified in initializer
  .aio_fsync = zpl_aio_fsync,
  ^
/var/lib/dkms/zfs/0.7.0/build/module/zfs/zpl_file.c:841:15: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .aio_fsync = zpl_aio_fsync,
               ^~~~~~~~~~~~~
/var/lib/dkms/zfs/0.7.0/build/module/zfs/zpl_file.c:841:15: note: (near initialization for ‘zpl_file_operations.fasync’)
cc1: some warnings being treated as errors
scripts/Makefile.build:293: recipe for target '/var/lib/dkms/zfs/0.7.0/build/module/zfs/zpl_file.o' failed
make[5]: *** [/var/lib/dkms/zfs/0.7.0/build/module/zfs/zpl_file.o] Error 1

**Comment by mskarbek** [comment]
@dkscully this is already fixed in #5398.

**Comment by gmelikov** [comment]
@dkscully please read and fill in issue template next time.

**Comment by grizzlyfred** [comment]
I am trying to build from source now the 0.7.0-rc2 + approx. 10 commits now on this fedora box (just updated), but on first attempt I fail to something noted here: 
[https://github.com/zfsonlinux/zfs/issues/5485](url)
I just did second ./configre pass pass on both zfs and spl and it went through.
Now I have a lovely bunch of rpms:
> libnvpair1-0.7.0-rc2_125_ga0aacd3.fc25.x86_64.rpm
> zfs-0.7.0-rc2_125_ga0aacd3.fc25.x86_64.rpm
> libuutil1-0.7.0-rc2_125_ga0aacd3.fc25.x86_64.rpm
> zfs-debuginfo-0.7.0-rc2_125_ga0aacd3.fc25.x86_64.rpm
> libzfs2-0.7.0-rc2_125_ga0aacd3.fc25.x86_64.rpm
> zfs-dkms-0.7.0-rc2_125_ga0aacd3.fc25.noarch.rpm
> libzfs2-devel-0.7.0-rc2_125_ga0aacd3.fc25.x86_64.rpm
> zfs-dkms-0.7.0-rc2_125_ga0aacd3.fc25.src.rpm
> libzpool2-0.7.0-rc2_125_ga0aacd3.fc25.x86_64.rpm
> zfs-dracut-0.7.0-rc2_125_ga0aacd3.fc25.x86_64.rpm
> zfs-0.7.0-rc2_125_ga0aacd3.fc25.src.rpm
> zfs-test-0.7.0-rc2_125_ga0aacd3.fc25.x86_64.rpm
and also
spl-0.7.0-rc2_10_g0194e4a.fc25.src.rpm
spl-debuginfo-0.7.0-rc2_10_g0194e4a.fc25.x86_64.rpm
spl-dkms-0.7.0-rc2_10_g0194e4a.fc25.src.rpm
spl-0.7.0-rc2_10_g0194e4a.fc25.x86_64.rpm
spl-dkms-0.7.0-rc2_10_g0194e4a.fc25.noarch.rpm
... now if that would install, we would now that it is a mere packaging / distro issue, that shouldn't be thre once 0.7.0 is released...
