### ISSUE TITLE
[brainfarting] hybrid (or per-file) compression?

### ISSUE THREAD

**Issue by RJVB** [zfsonlinux/zfs#5605]
This is a bit of a wishlist/wishful thinking ticket, hope that's OK on here (if not I'll move it).

ZFS currently supports various compression types and levels, with various trade-offs between space and throughput efficiency.

In another universe I use HFS+, which supports transparent decompression and requires dedicated tools to apply compression, based on ZIP. I've never really compared zip (8 or 9) with gzip (8 or 9) but with zip-8 I see compression levels I rarely see with lz4, and I can make use of accelerated ZIP implementations like the one by Cloudflare.

Of course zip compresses more slowly, but that's not so much an issue when the files being compressed are of the write once/rarely, read often class. (And my compression tool is smart enough to know not to waste time of files which won't compress.) In short: I can unpack tarballs with HFS compression when that makes sense, and run a compression step on say big build directories when done with them (e.g. QtWebEngine's build dir compresses from 21Gb to under 5Gb without increasing the overall build time significantly).

In ZFS you could unpack things with high compression by switching the target dataset compression type, but I don't know of a convenient way to rewriting existing files with a better form of compression. Unless `mv` has an option to copy-and-then-delete even when NOT crossing a filesystem/dataset boundary?

And that's something that would be nice to have:
- compression type and level are already stored at the file level since files remain readable when you change the dataset property. A userland library might thus change that setting on a per-file basis, without requiring special privileges as long as the user has write permission for the file.
- this would allow rewriting files with better compression more easily, without having to change the overall dataset property. Ideally this would happen transparently when changing the file property, but simply creating a new file would be OK too.
- and it would allow any operation (archive unpack, installing distribution updates, etc) to be done with scoped compression settings by [f]open etc. wrappers through library injection.

Is there anything that sounds doable and worth the effort in the ramblings above?

**Comment by DeHackEd** [comment]
This is a bug tracker, not a support forum. Please use the mailing list for questions like this.

**Comment by RJVB** [comment]
On Monday January 16 2017 03:23:58 DeHackEd wrote:
> This is a bug tracker, not a support forum. Please use the mailing list for questions like this.

This isn't a support question either but indeed a forum would be more appropriate than a mailing list.

**Comment by MyPod** [comment]
@RJVB as far as I know compression is applied at the block level, as the last operation before being written on disk, and not at the file level. You would have to copy things and delete the original to change the compression format, or copy to a different dataset. Moreover, more could be involved, so you might end up wasting space by keeping two copies on-disk, even if only one is available in the latest state of the dataset and the other is exclusively required for a snapshot.
The compression setting affects the whole dataset, too, so unless you have a rather specific usecase in which i.e. you have a dataset for a given source tree, there's the risk of interfering with other program and potentially require a lot of CPU to compress with a more intensive algorithm.

**Comment by RJVB** [comment]
So that means that you can end up with a file compressed by 2 different methods if you change the dataset property while a write is in progress?

Indeed, one could end up with multiple copies of files concerned by snapshots. That's an expected consequence, but I have a hunch that datasets on which you'd use this kind of compression tweak are not the type of datasets for which you'd keep persistent snapshot(s) .

Yes, changing the dataset property temporarily will affect all writes to it until the change has been reverted. Not necessarily a big issue if you're aware of the implication and take it into account.
But what I had in mind was very specifically a compression setting that applies to a file descriptor when it's being opened, initialised from the dataset property. This must already be what the driver does: select the compression algorithm for writable files based on the dataset's property. Overriding that choice through a parameter is probably among the easier implementation details of this idea, and doesn't affect other operations.
