### ISSUE TITLE
Linux 4.9 compability release

### ISSUE THREAD

**Issue by RubenKelevra** [zfsonlinux/zfs#5630]
Hey guys,

Linux 4.9 is now some weeks out and I wanted to update to find out that ZFSoL still misses the Linux 4.9 compatibility. Is there still an issue or is it just a lack of time / testing which prevents the small fixing release for the 4.9 compatibility?

Thanks in advance!

Ruben

**Comment by behlendorf** [comment]
We've been focused on getting the next -rc3 release out and tested.  Now that that's done we'll get an 0.6.5.9 release of the production branch put together with build fixes and any other critical fixes.  There's a branch with just build fixes available here if you want something right away.

https://github.com/behlendorf/spl/commits/spl-0.6.5.8-fedora-25
https://github.com/behlendorf/zfs/commits/zfs-0.6.5.8-fedora-25

**Comment by gordan-bobic** [comment]
This appears to break as early as autogen on EL7/arm32 (regular 0.6.5.8 works):

[root@dreamplug /mnt/tmp/spl-spl-0.6.5.8-fedora-25]# ./autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I config
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
configure.ac:44: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by loli10K** [comment]
@gordan-bobic this is strange, that specific line has been the same for a long time https://github.com/behlendorf/spl/blame/spl-0.6.5.8-fedora-25/configure.ac#L44. Do you have `libtool` installed?

**Comment by gordan-bobic** [comment]
Ah, hang on - this _could_ be related to the bug I'm trying to hunt down at the minute (mentioned it on the mailing list yesterday).

**Comment by behlendorf** [comment]
Closing.  We when 0.6.5.9 is related it will contain support for the latest kernels.  We don't need to keep this issue open to track that.

**Comment by eljenso** [comment]
Debian Stretch will be released soon (full freeze will be on 2017-02-05, see https://wiki.debian.org/DebianStretch).
It ships with Kernel 4.9 but the repo serves ZFS v0.6.5.8, so Debian Stretch comes without working ZFS.

Please release v0.6.5.9 soon.
