### ISSUE TITLE
Failure to compile on 4.4.44 gcc 5.4.0-r2 (gentoo)

### ISSUE THREAD

**Issue by prometheanfire** [zfsonlinux/zfs#5631]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Gentoo
Distribution Version    | null
Linux Kernel                 | 4.4.44
Architecture                 | x86_64
ZFS Version                  |  https://github.com/zfsonlinux/zfs/commit/4ea3f86426f76e59244ec6f66504da688d90193c
SPL Version                  |  https://github.com/zfsonlinux/spl/commit/f5c5286daa5f76532d7a8a7988d6a42cfd58038c

### Describe the problem you're observing

Failure to compile as builtin, worked with the same kernel patchset as used in 4.4.43

### Include any warning/errors/backtraces from the system logs

From make

https://gist.github.com/prometheanfire/dda69b3c7952091a7ef2c47f779f6f06

and here's my kconfig

https://paste.pound-python.org/show/PXkgbtK6xroIz3X2EkK1/

**Comment by prometheanfire** [comment]
Failed on kernel 4.9.5 as well with gcc 5.4.0-r2  I think this is caused by gcc

**Comment by Kajanos87** [comment]
Also fail compilation on kernel 4.9.5 - zfs 0.7.0-rc3_4_g4ea3f86

`*checking whether lookup_bdev() wants 1 arg... yes
*checking whether invalidate_bdev() wants 1 arg... yes
*checking whether bdev_logical_block_size() is available... yes
*checking whether bdev_physical_block_size() is available... yes
*checking whether bio has bi_iter... yes
*checking whether BIO_RW_FAILFAST_* are defined... no
*checking whether REQ_FAILFAST_MASK is defined... yes
*--
*In file included from /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/include/sys/trace.h:38:0,
*                 from /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/include/sys/sdt.h:43,
*                 from /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/include/sys/zfs_context.h:64,
*                 from /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/include/sys/crypto/common.h:39,
*                 from /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/module/icp/illumos-crypto.c:35:
*/var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/include/sys/trace_dbgmsg.h:115:91: error: conflicting types for 'trace_name'
*--
*In file included from /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/include/sys/trace.h:38:0,
*                 from /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/include/sys/sdt.h:43,
*                 from /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/include/sys/zfs_context.h:64,
*                 from /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/include/sys/crypto/common.h:39,
*                 from /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/module/icp/illumos-crypto.c:35:
*/var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/include/sys/trace_dbgmsg.h:115:263: error: conflicting types for 'trace_name_rcuidle'
*--
*In file included from /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/include/sys/trace.h:38:0,
*                 from /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/include/sys/sdt.h:43,
*                 from /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/include/sys/zfs_context.h:64,
*                 from /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/include/sys/crypto/common.h:39,
*                 from /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/module/icp/illumos-crypto.c:35:
*/var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/include/sys/trace_dbgmsg.h:115:442: error: conflicting types for 'register_trace_name'
*--
*In file included from /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/include/sys/trace.h:38:0,
*                 from /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/include/sys/sdt.h:43,
*                 from /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/include/sys/zfs_context.h:64,
*                 from /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/include/sys/crypto/common.h:39,
*                 from /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/module/icp/illumos-crypto.c:35:
*/var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/include/sys/trace_dbgmsg.h:115:675: error: conflicting types for 'unregister_trace_name'
*--
*In file included from /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/include/sys/trace.h:38:0,
*                 from /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/include/sys/sdt.h:43,
*                 from /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/include/sys/zfs_context.h:64,
*                 from /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/include/sys/crypto/common.h:39,
*                 from /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/module/icp/illumos-crypto.c:35:
*/var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/include/sys/trace_dbgmsg.h:115:911: error: conflicting types for 'check_trace_callback_type_name'
*--
*In file included from /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/include/sys/trace.h:38:0,
*                 from /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/include/sys/sdt.h:43,
*                 from /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/include/sys/zfs_context.h:64,
*                 from /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/include/sys/crypto/common.h:39,
*                 from /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/module/icp/illumos-crypto.c:35:
*/var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/include/sys/trace_dbgmsg.h:115:1129: error: redefinition of 'trace_name_enabled'
*--
*                 from /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/include/sys/crypto/common.h:39,
*                 from /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/module/icp/illumos-crypto.c:35:
*/var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/include/sys/trace_dbgmsg.h:73:1129: note: previous definition of 'trace_name_enabled' was here
* DEFINE_EVENT(zfs_dprintf_class, name, \
*                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^
*/usr/src/linux-4.9.5-gentoo/scripts/Makefile.build:293: recipe for target '/var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/module/icp/illumos-crypto.o' failed
*make[6]: *** [/var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/module/icp/illumos-crypto.o] Error 1
*/usr/src/linux-4.9.5-gentoo/scripts/Makefile.build:544: recipe for target '/var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/module/icp' failed
*make[5]: *** [/var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/module/icp] Error 2
*--
*  CC [M]  /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/module/nvpair/fnvpair.o
*  CC [M]  /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/module/nvpair/nvpair_alloc_spl.o
*  CC [M]  /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/module/nvpair/nvpair_alloc_fixed.o
*  LD [M]  /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/module/unicode/zunicode.o
*  LD [M]  /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/module/nvpair/znvpair.o
*/usr/src/linux-4.9.5-gentoo/Makefile:1490: recipe for target '_module_/var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/module' failed
*make[4]: *** [_module_/var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/module] Error 2
*make[4]: Leaving directory '/usr/src/linux-4.9.5-gentoo'
*Makefile:150: recipe for target 'sub-make' failed
*make[3]: *** [sub-make] Error 2
*make[3]: Leaving directory '/usr/src/linux-4.9.5-gentoo'
*Makefile:19: recipe for target 'modules' failed
*make[2]: *** [modules] Error 2
*make[2]: Leaving directory '/var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/module'
*Makefile:836: recipe for target 'all-recursive' failed
*make[1]: *** [all-recursive] Error 1
*make[1]: Leaving directory '/var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999'
*Makefile:705: recipe for target 'all' failed
*make: *** [all] Error 2
* * ERROR: sys-fs/zfs-kmod-9999::gentoo failed (compile phase):
* *   emake failed
*--
* * The complete build log is located at '/var/tmp/portage/sys-fs/zfs-kmod-9999/temp/build.log'.
* * The ebuild environment file is located at '/var/tmp/portage/sys-fs/zfs-kmod-9999/temp/environment'.
* * Working directory: '/var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999'
* * S: '/var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999'
* * Messages for package sys-fs/zfs-kmod-9999:
* * ERROR: sys-fs/zfs-kmod-9999::gentoo failed (compile phase):
* *   emake failed
`

**Comment by prometheanfire** [comment]
@Kajanos87 what version of gcc you running?

**Comment by Kajanos87** [comment]
gcc version 4.9.4 (Gentoo 4.9.4 p1.0, pie-0.6.4)

**Comment by skalteis** [comment]
Can confirm on Debian stretch, master/commit 3d43125fd465d869c813eb30a0233c0b6aae1209
gcc (Debian 6.2.1-5) 6.2.1 20161124

**Comment by skalteis** [comment]
Seems #5643 is tracking this.

**Comment by prometheanfire** [comment]
fixed in master
