### ISSUE TITLE
unexpected results of chmod() + mkdir() leading to permissions error

### ISSUE THREAD

**Issue by RJVB** [zfsonlinux/zfs#5633]
I have Tcl-based build scripts that invoke the `xinstall` function from a Tcl extension library "pextlib" (source: `install()` in https://github.com/macports/macports-base/blob/master/src/pextlib1.0/xinstall.c)

One of those scripts contains an expression `xinstall -m 775 -d ${destroot}${qt_cmake_module_dir}/${d}` which is called inside a loop over `d`. It evaluates to 2 subsequent `mkdir()` calls with their associated `chmod()` calls in xinstall.c :

```
xinstall: mkdir /opt/local/var/lnxports/build/_opt_local_site-ports_aqua_qt5-kde-angel/qt5-kde-angel/work/destroot/opt/local/lib/cmake
xinstall: mkdir /opt/local/var/lnxports/build/_opt_local_site-ports_aqua_qt5-kde-angel/qt5-kde-angel/work/destroot/opt/local/lib/cmake/Qt5Svg
```

but when the script then tries to do `file rename ${f} ${destroot}${qt_cmake_module_dir}/${d}/` I get the error

```
error renaming "/opt/local/var/lnxports/build/_opt_local_site-ports_aqua_qt5-kde-angel/qt5-kde-angel/work/destroot/opt/local/libexec/qt5/lib/cmake/Qt5Svg/Qt5Svg_QSvgIconPlugin.cmake" to "/opt/local/var/lnxports/build/_opt_local_site-ports_aqua_qt5-kde-angel/qt5-kde-angel/work/destroot/opt/local/lib/cmake/Qt5Svg/Qt5Svg_QSvgIconPlugin.cmake": permission denied
```

because the 2nd directory (Qt5Svg) didn't get the proper permissions:

```
> sudo ll -R /opt/local/var/lnxports/build/_opt_local_site-ports_aqua_qt5-kde-angel/qt5-kde-angel/work/destroot/opt/local/lib/cmake/
/opt/local/var/lnxports/build/_opt_local_site-ports_aqua_qt5-kde-angel/qt5-kde-angel/work/destroot/opt/local/lib/cmake/:
total 2
1134062 drwxr-xr-x 4 bertin bertin 4 Jan 23 11:10 ../
1133522 drwxr-xr-x 3 bertin bertin 3 Jan 23 11:10 ./
1133523 d-w--w-r-x 2 bertin bertin 2 Jan 23 11:10 Qt5Svg/

/opt/local/var/lnxports/build/_opt_local_site-ports_aqua_qt5-kde-angel/qt5-kde-angel/work/destroot/opt/local/lib/cmake/Qt5Svg:
total 1
1133522 drwxr-xr-x 3 bertin bertin 3 Jan 23 11:10 ../
1133523 d-w--w-r-x 2 bertin bertin 2 Jan 23 11:10 ./
```

This doesn't always happen, but in the few attempts I just made the error occurred systematically but for different directories under the lib/cmake directory. I finally changed the script to call `xinstall -m 775 -d ${destroot}${qt_cmake_module_dir}` outside the loop and that allowed it to complete this time.

It has never happened to me on other filesystems, and I don't see anything wrong in xinstall.c, so I think this is a subtle bug in ZFS. It reminds me of the fact that `du` doesn't immediately report the correct on-disk file/directory size, but this issue is of course different in that the permissions do not correct themselves over time.

NB: yes, this is from MacPorts but we *are* talking about running on Linux and ZoL; I haven't seen anything Mac-specific in pextlib that is relevant here, just standard Unix/POSIX code.

**Comment by behlendorf** [comment]
For reference can you add what version of ZFS are you're seeing this issue with.

**Comment by RJVB** [comment]
On Monday January 23 2017 14:27:04 Brian Behlendorf wrote:
> For reference can you add what version of ZFS are you're seeing this issue with.

I have been seeing this with the Darik Horn's 0.6.5.7 package for Ubuntu 14.04 with kernel 4.5.7, and am now seeing it with 0.6.5.8 , with kernel 4.8.15 .

R.

**Comment by tuxoko** [comment]
What's your umask?
Can you use strace on both successful and failed run?

**Comment by RJVB** [comment]
On Monday January 23 2017 15:50:51 Chunwei Chen wrote:

>What's your umask?

Sorry, 755, standard mask for a "system" directory. Didn't mention it because it's implicit from the correctly created lib/cmake directory ;)

>Can you use strace on both successful and failed run?

What I didn't mention is that this happens when I "install" Qt5 for packaging (= to a "destroot"), which means *lots* of I/O. That may actually be a factor, but it also means strace will give a sh*tload of output to sift through. So I tried filtering with -P, and evidently the issue promptly jumped to a different instruction with a different path :-/ A path created before the actual destroot run, using the fmtree command.

I did get to see a chmod() of the target directory with a weird umask, 0225 in a subsequent run with `-e trace=file`. I'm currently trying to match the error location to a command in my build script but have some difficulty reproducing the error now that I'm really looking hard at reproducing it :((

I do not have a 225 mask in my scripts, and I hope you agree that it cannot be the result of a non-initialised value in the install() function either.

R

**Comment by RJVB** [comment]
>Can you use strace on both successful and failed run?

Currently, keeping everything else equal except the exact invocation, this fails:

> strace -e trace=file -o strace1.log $INSTALLcmd

and this succeeds:

> strace -e trace=file $INSTALLcmd >& strace2.log

Any brilliant ideas? I've been getting a bit too many of these Heisenbugs recently :(

R.

**Comment by RJVB** [comment]
WTH?

I tweaked xinstall.c a bit, in InstallCmd() (the actual function called from Tcl):

```
		case 'm': {
			if (!objc) {
				Tcl_WrongNumArgs(interp, 1, objv, "-m");
				return TCL_ERROR;
			}
			const char *modeString = Tcl_GetString(*(++objv));
			if (!(set = setmode(modeString))) {
				char errmsg[255];

				snprintf(errmsg, sizeof errmsg, "%s: Invalid file mode: %s",
					 funcname, modeString);
				Tcl_SetResult(interp, errmsg, TCL_VOLATILE);
				return TCL_ERROR;
			}
			mode = getmode(set, 0);
            if (verbose) {
                ui_debug(interp, "%s: mode=%s umask=0%o", funcname, modeString, mode);
            }
			free(set);
			objv++, objc -= 2;
			break;
        }
```

and by a stroke of luck I got a hit at once:

```
:debug:destroot xinstall: mode=775 umask=0225
:error:destroot Failed to destroot qt5-kde-angel: error renaming "/opt/local/var/lnxports/build/_opt_local_site-ports_aqua_qt5-kde-angel/qt5-kde-angel/work/destroot/opt/local/libexec/qt5/lib/pkgconfig/Qt5X11Extras.pc" to "/opt/local/var/lnxports/build/_opt_local_site-ports_aqua_qt5-kde-angel/qt5-kde-angel/work/destroot/opt/local/lib/pkgconfig/Qt5X11Extras.pc": permission denied
```

A bug in setmode (2)? Or possibly indeed a side-effect of running on ZFS because `setmode` can do a transient umask change and that is a (known) operation which may take time on ZFS?

**Comment by tuxoko** [comment]
ZFS doesn't do anything with umask. You get the 0225 value from setmode and getmode, I don't see how ZFS has anything to do with this.

**Comment by RJVB** [comment]
Calling umask() doesn't do anything on disk? If so, ZFS is indeed unlikely to be involved directly.

For reference, this is what setmode() does with umask:

```
     /*
      * Get a copy of the mask for the permissions that are mask relative.
      * Flip the bits, we want what's not set.  Since it's possible that
      * the caller is opening files inside a signal handler, protect them
      * as best we can.
      */
     sigfillset(&signset);
     (void)sigprocmask(SIG_BLOCK, &signset, &sigoset);
     (void)umask(mask = umask(0));
     mask = ~mask;
     (void)sigprocmask(SIG_SETMASK, &sigoset, NULL);
```

**Comment by RJVB** [comment]
Mea culpa (I think).
Turns out that the pextlib library that provides the Tcl xinstall function has its own setmode implementation, so old that it still used K&R function declarations. I haven't tried to follow exactly what goes wrong in that code, but after tweaking the build process to use the current libbsd version I have no longer been able to reproduce the issue.

For now.

Either way, I think it's safe to say that ZFS is indeed not involved. Whew!
