### ISSUE TITLE
Soft Lockup in multipathd

### ISSUE THREAD

**Issue by dpquigl** [zfsonlinux/zfs#5656]
### System information

Type                                | Version/Name
Bug                               |    https://github.com/dpquigl/zfs/tree/abd-linear-reduction
Distribution Name       |  Centos
Distribution Version    | 7.2
Linux Kernel                 | 3.10.0-327
Architecture                 | x86_64
ZFS Version                  | https://github.com/dpquigl/zfs/tree/abd-linear-reduction
SPL Version                  | pre-rc3 master A8F46DA51476B9227DB47B0

### Describe the problem you're observing
During test runs a soft lock is triggered initial in mutlipathd when trying to free a dnode

### Describe how to reproduce the problem
Run the test suite with this branch.

[linear.txt](https://github.com/zfsonlinux/zfs/files/728283/linear.txt)

**Comment by dpquigl** [comment]
@tuxoko Brian told me to tag you in this issue since it seems to be a zvol related bug.

**Comment by tuxoko** [comment]
@dpquigl 
Did you do rollback or recv on the zvol?
If so it's very likely #4866 which is fixed in master.

**Comment by dpquigl** [comment]
This branch has your patch for #4866 in it. We're rerunning against an rc3 master at the moment but it does have you're fix.

**Comment by tuxoko** [comment]
OK, it's blocked on an rwsem, but the log doesn't show who's holding the lock. Any chance you have a crash dump to extract such info?

**Comment by dpquigl** [comment]
@tuxoko Unfortunately that log got rolled off with subsequent runs. We are rerunning it now and once we get the failure again I'll post the new trace with the process up there. I have a vmcore but I don't know if you can get it out of that.

**Comment by ironMann** [comment]
@dpquigl I would look into this patch rather than looking into previous issues. At the time, I stopped working/testing on this due to large abd PR activity. Not sure if it's correct
