### ISSUE TITLE
Assembler code for atomic_sub_64 seems wrong (i386)

### ISSUE THREAD

**Issue by Ringdingcoder** [zfsonlinux/zfs#5671]
While poring over the atomic code I noticed that `atomic_sub_64` in `lib/libspl/asm-i386/atomic.S` looks wrong. Shouldn't it be subl followed by sbbl instead of adcl?

**Comment by behlendorf** [comment]
Yes, that does look wrong.  @ironMann could you comment on the this.

The good news is that is the user space implementation of these atomics.  They're mainly used for statistics tracking when testing ZFS in user space with ztest.

```
        ENTRY(atomic_sub_64)
        ALTENTRY(atomic_sub_64_nv)
        pushl   %edi
        pushl   %ebx
        movl    12(%esp), %edi
        movl    (%edi), %eax
        movl    4(%edi), %edx
1:
        movl    16(%esp), %ebx
        movl    20(%esp), %ecx
        subl    %eax, %ebx
>>>        adcl    %edx, %ecx
        lock
        cmpxchg8b (%edi)
        jne     1b
        movl    %ebx, %eax
        movl    %ecx, %edx
        popl    %ebx
        popl    %edi
        ret
        SET_SIZE(atomic_sub_64_nv)
        SET_SIZE(atomic_sub_64)
```

**Comment by ironMann** [comment]
Agree, that should be `sbbl` instead of `adcl`.
