### ISSUE TITLE
ZFS upgrade caused pool to lose available space

### ISSUE THREAD

**Issue by chrisbrown1903** [zfsonlinux/zfs#5685]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  CentOS
Distribution Version    | 7.3.1611
Linux Kernel                 | 3.10.0-514.6.1.el7.x86_64
Architecture                 | x86_64
ZFS Version                  | zfs-dkms-0.6.5.8-1.el7.centos.noarch
SPL Version                  | spl-dkms-0.6.5.8-1.el7.centos.noarch

### Describe the problem you're observing
I've noticed I lose about 1.5% of my available pool after upgrading from 6.3.1.2 to 6.5.8-1. 

I noticed the decrease in available space in both "zfs list"  and "df" commands. 

### Describe how to reproduce the problem
Upgrade from 6.3.1-2 > 6.5.8-1

**Comment by behlendorf** [comment]
This was done intentionally and is described in the [Changes in Behavior](https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.6.5) section of the 0.6.5 release notes.

* Default reserved space was increased from 1.6% to 3.2% of total pool capacity. This default percentage can be controlled through the new spa_slop_shift module option, setting it to 6 will restore the previous percentage.

**Comment by chrisbrown1903** [comment]
You're awesome! Thanks!
