### ISSUE TITLE
zvol_id failing on gentoo (probably other distributions who build with stack protection)

### ISSUE THREAD

**Issue by Peitolm** [zfsonlinux/zfs#569]
# /lib/udev/zvol_id /dev/zd0
*** stack smashing detected ***: zvol_id - terminated
zvol_id: stack smashing attack in function <unknown> - terminated
Report to http://bugs.gentoo.org/
Killed

added -fno-stack-protector to the compile line for zvol_id and it compiles and works,

 # /lib/udev/zvol_id /dev/zd0
tank/volume

**Comment by ryao** [comment]
@behlendorf #775 did fix this.

**Comment by behlendorf** [comment]
@ryao thanks.  It looks like there is still some room for improvement here but the basic issue has been resolved.  Closing.
