### ISSUE TITLE
Proper handling of Sparse File support

### ISSUE THREAD

**Issue by bew-dev** [zfsonlinux/zfs#5696]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  rhel
Distribution Version    | 7.3
Linux Kernel                 | 
Architecture                 | x64
ZFS Version                  | 7.3 linked on main
SPL Version                  | to match

### Describe the problem you're observing
A windows smb pushing of sparse files to the array has errors.  it wouldnt attempt this if it wasnt interpreting them as being accepted(or not) by the zfs filesystem.  What flag is missing, or can be added to proper stop attempt of sparse writes?
 
[zfs get all pastey](http://pastey.org/view/8013f7b9) 
i notice `fscontext` is set to none, is that related?

here is my smb config
```
[global]
    workgroup = MEGROUP
    #security = user
    #passdb backend = tdbsam
    printing = bsd
    printcap name = /dev/null
    load printers = no
    #spoolss
    disable spoolss = yes
    #aim to fix windows freefilesync copy symlinks not working
    follow symlinks = yes
    wide links = yes
	
[san]
    comment = ZFS 'san' pool Backup File Server
    path = /san/vault
    #ironically doesnt make it readonly, however, worked in favor of writeabe, valid users, and browseable yes, on arch
    read only = yes
    #writeable = yes
    #browseable = yes
    #valid users = me @admins
    write list = me, backupusers, root, @admins
```

here is the folder perms	

```
$ /san$ ls -la
total 21
drwxr-xr-x.  3 root root      3 Jan  3 23:08 .
dr-xr-xr-x. 18 root root   4096 Jan 28 04:30 ..
drwxrwxr-x.  8 root backupusers    8 Jan 28 00:00 vault
```

### Describe how to reproduce the problem
create raidz2 array across 6x2tb drives, on rhel64-7.3 or arch64 latest to date, enable samba share writeable, then push from freefilesync on a windows installation somewhere across the network, using windows network path , e.g. `\\machine\sharename`

### Include any warning/errors/backtraces from the system logs

`3:08:15 AM	Error	Cannot write file attributes of "\\MERLIN\san\redtail\data\dpub\Downloads\photoshop lightroom plugins\Lightroom Presets 03\Colorful HDR Effect 1 - LightroomLibrary.lrtemplate.ffs_tmp".
Error Code 1: Incorrect function. (DeviceIoControl, FSCTL_SET_SPARSE)`

[bug report here](https://aur.archlinux.org/packages/zfs-linux-git/)
[author corroboration](http://www.freefilesync.org/forum/viewtopic.php?f=2&t=1650&p=13710#p13710)

For the implementer
[More sparse File info](https://blogs.oracle.com/bonwick/entry/seek_hole_and_seek_data)
[control code docs](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364596)

Also Where is the proper upstream on this, if its not here?  Solaris? 

Thinking on this, I have read articles that in some cases the system needs fully and strictly "Administrator" privileges, so that's one other possible outcome on the source of this issue.  How to achieve perfect Administrator privs thats to be discussed.  I believe this has to do with certain versions of NTLM, as well as possibly even an ACTUAL user named Administrator in the linux box, so that smbpasswd can issue the user to the connection.  Hope its not that far fetched, that puts the work onto my end, lol.    (Edit: added smb configs)

Any ideas?

**Comment by tuxoko** [comment]
This is not a zfs issue, please check your windows or samba config.

**Comment by brian-lamb-software-engineer** [comment]
hmm, i wish you could tell me more, because i thought the author of freefilesync, who runs the opcodes to control the drivers directly on sparse writes, mentioned its a zfs driver issue.
