### ISSUE TITLE
Failed Trying to Install Ubuntu 16.10 with ZFS

### ISSUE THREAD

**Issue by thor998** [zfsonlinux/zfs#5697]
Hello all,

I have been trying to install Ubuntu 16.10 in a ZFS partition, and I have
following this guide:
https://github.com/zfsonlinux/zfs/wiki/Ubuntu-16.10-Root-on-ZFS

The system is being installed in a virtual machine, and I have tried 
dozens of times (I tried all the recommendation on the guide above,
and even tried recommendations on other guides I found on Google), 
but I fail to pass step 5. 

When I restart the Ubuntu LiveCD, and remove the ISO to boot on the 
virtual drive, it simple dont boot at all on the ZFS partition, and dont give 
any message of error, the virtual machine simple cant find the partition.

I tried changing flags of the partition (with Gparted) to sign that there 
is a Grub boot, or that the partition is a system, and nothing have 
happened. Then I opened another partition tool available on Ubuntu 
LiveCD, and it shows the information that there is a Grub for UEFI installed 
on the ZFS partition, but, this virtual machine+ubuntu installation was 
configured following the instructions for normal BIOS with MBR, and 
when I followed that guide above, I choose to install Grub for BIOS with 
MBR, not for UEFI. 

Then, I guessed that for some reason, Grub installed a boot for UEFI 
automatically, (is it possible to happen?). Then I tried to boot the virtual 
drive in a virtual machine configured to work with UEFI, and, nothing 
happened, it cant find the partition and simple dont boot.

Then, I thought, well, if the problem is with UEFI or BIOS, then I can start
all from scratch following the UEFI steps and it will work, so, I did it, 
including creating a virtual machine exclusively for UEFI, and guess what, 
I cant pass step 5 again! In both situations where I tried BIOS+MBR, or 
UEFI, I cant boot the system at all, in both situations the partitions are not
recognized.

Worth mentioning, when I did the Grub steps for MBR, Grub failed to install
(this command specifically # grub-install /dev/disk/by-id/scsi-SATA_disk1)
directly on the whole disk, in the MBR, it only install on the first partition 
that is where Ubuntu was installed. On the Grub steps for UEFI,
(this command specifically # mkdosfs -F 32 -n EFI /dev/disk/by-id/scsi-SATA_disk1-part3)
It says a warning that the partition dont have enough sectors for a FAT32 
partition.

I already tried everything that came up to my mind and I ran out of options, 
I am not specialist on this subject of partition and boot systems, then, 
I really have no idea about where I am failing, and, if anyone could help me,
I would be glad. It is really important to me to have an Ubuntu system together 
ZFS to keep my data safe from silent data corruption.

**Comment by ghfields** [comment]
I'm sorry to hear you are having issues.  The wiki that you have referenced allows you to make a highly tuned root pool.  I have also written a HOW-TO that I believe is a bit easier to implement.  The drawback to mine, however, is that is only works with BIOS boot.  If this is not an issue for you, feel free to try [HOWTO install Ubuntu 16.10 to a Whole Disk Native ZFS Root Filesystem using Ubiquity GUI installer](https://github.com/zfsonlinux/pkg-zfs/wiki/HOWTO-install-Ubuntu-16.10-to-a-Whole-Disk-Native-ZFS-Root-Filesystem-using-Ubiquity-GUI-installer) which can be found in the pkg-zfs wiki.

**Comment by kpande** [comment]
this is an inappropriate use of the issue tracker, please use [the zfs-discuss mailing list](http://list.zfsonlinux.org) for distribution / support requests.

**Comment by thor998** [comment]
@kpande 

This is a quote of that specific article where it asks to use this place to report when something wrong happen when following that article... it is not my mistake right.

> Reporting Bugs
> If  you have bugs or feature requests related to this HOWTO, please [file a new issue](https://github.com/zfsonlinux/zfs/issues/new) and mention @rlaager.

@ghfields 
Thanks, I will look at your article carefully.

**Comment by gmelikov** [comment]
@thor998  if you don't see grub on boot - you just didn't install it (grub begin to work with ZFS after it's loaded). Load from ZFS begins after grub loaded from MBR. @kpande closed the issue because it doesn't seem like a problem in instruction, so you need a support.

**Comment by thor998** [comment]
Thanks everyone, 

I actually found where the problem was (I researched in deep and I did the steps all over again), and it is partially my mistake, I admit, but it can be much possible a minor issue on the article too.

So, here it is my considerations:
1- On step 2.2, it dont says that I should follow that order strictly, them, probably I did first the
"Run these in all cases:", and then selected BIOS or UEFI variation in the attempts I did, the problem is, doing "sgdisk -a1 -n2:34:2047  -t2:EF02 /dev/disk/by-id/scsi-SATA_disk1" won't work if you do the others first (I checked with gparted and the partition is not created), and when I did it first and the other later it says a warning saying that it is relocating sectors to align. It dont looks right, then, I guess the problem is something to do with this "-n2:34:2047" overlaping the sectors with the other 2 commands.

2- On step 4.6a, the command "apt install --yes grub-pc", after installing grub, it opens an interface and ask where to put grub, and I was wrongly selecting the whole disk, not the partition. Since there is not a single note on this step, I was confusing it with step 5.5a. Maybe a little note pointing out what to do on step 4.6a would help people that is not aware of how it works.

**Comment by rlaager** [comment]
The BIOS partition is in the free space left over from normal partition alignment, so it shouldn't matter what order you run it in. That said, of course you should follow the instructions as written.

On 4.6a, the correct place to install GRUB is to the whole disk, as with a normal install. So that was not a mistake. I've added a note.
