### ISSUE TITLE
Incorrect file size in ZFS fs

### ISSUE THREAD

**Issue by yarus23** [zfsonlinux/zfs#5700]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Ubuntu server
Distribution Version    | 16.10
Linux Kernel                 | 4.8.0-34
Architecture                 | x86_64
ZFS Version                  | 0.6.5.8-0ubuntu4.1
SPL Version                  | 0.6.5.8-2

### Describe the problem you're observing

I use a single file for KVM raw hdd image. It expected to be 50Gig file. But ls -lh gives 900 terabytes file. So I need now to move this file to another pool but cannot, it just cannot copy 900 terabytes.

### Describe how to reproduce the problem

I have made a miracle pool, put here a single file created with qemu-img and install Windows into it.

### Include any warning/errors/backtraces from the system logs

[zpool status](https://github.com/zfsonlinux/zfs/files/739280/1.txt)
[zdb output](https://github.com/zfsonlinux/zfs/files/739281/2.txt)
[zfs get all](https://github.com/zfsonlinux/zfs/files/739283/3.txt)
[ls output](https://github.com/zfsonlinux/zfs/files/739282/4.txt)

**Comment by DeHackEd** [comment]
That's not a "how to reproduce" description.

Besides, sparse files are supported in all kinds of filesystems. Without more details this looks more like a user mistake than a bug.

**Comment by behlendorf** [comment]
It sounds as if you've created a sparse file which is working as intended.  The `du` utility can be used to report the real size used on disk.
