### ISSUE TITLE
0.7.0-rc3 deadlocks constantly at zpool export

### ISSUE THREAD

**Issue by bzzz77** [zfsonlinux/zfs#5713]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | 
Distribution Version    | 
Linux Kernel                 | 3.10.0-327.36.3.el7
Architecture                 | x86-64
ZFS Version                  | 0.7.0-rc3
SPL Version                  | 0.7.0-rc2

### Describe the problem you're observing
zpool export got stuck:

[  481.733056] z_zvol          D 0000000000000000     0  3965      2 0x00000080
[  481.733064]  ffff880fb8e0bd18 0000000000000046 ffff880fb942c500 ffff880fb8e0bfd8
[  481.733070]  ffff880fb8e0bfd8 ffff880fb8e0bfd8 ffff880fb942c500 ffff880fe0192400
[  481.733076]  0000000000000012 0000000000000013 ffff880fe01924d8 0000000000000000
[  481.733082] Call Trace:
[  481.733098]  [<ffffffff8163bd69>] schedule+0x29/0x70
[  481.733116]  [<ffffffffa0814595>] taskq_wait_outstanding+0x95/0xf0 [spl]
[  481.733124]  [<ffffffff810a6b80>] ? wake_up_atomic_t+0x30/0x30
[  481.733207]  [<ffffffffa09d3629>] zvol_task_cb+0x2c9/0x450 [zfs]
[  481.733213]  [<ffffffff8163b718>] ? __schedule+0x2d8/0x900
[  481.733223]  [<ffffffffa0813e36>] taskq_thread+0x246/0x470 [spl]
[  481.733234]  [<ffffffff810b8940>] ? wake_up_state+0x20/0x20
[  481.733242]  [<ffffffffa0813bf0>] ? taskq_thread_spawn+0x60/0x60 [spl]
[  481.733251]  [<ffffffff810a5b8f>] kthread+0xcf/0xe0
[  481.733257]  [<ffffffff810a5ac0>] ? kthread_create_on_node+0x140/0x140
[  481.733265]  [<ffffffff81646c98>] ret_from_fork+0x58/0x90
[  481.733271]  [<ffffffff810a5ac0>] ? kthread_create_on_node+0x140/0x140

### Describe how to reproduce the problem
# zpool create -f test  /dev/sdb1 /dev/sdc1 /dev/sdd1
# zfs create test/test
# zpool destroy test

**Comment by loli10K** [comment]
Duplicated/related to https://github.com/zfsonlinux/zfs/issues/5195?

**Comment by kernelOfTruth** [comment]
@bzzz77

is it just a typo or are you **really** running different versions of SPL and ZFS ?

**Comment by bzzz77** [comment]
yes, I did, for quite long time :) closing as can't reproduce with refreshed SPL. thanks.
