### ISSUE TITLE
Cannot write files to filesystem, commit 933ec99 (commit 986dd8a works)

### ISSUE THREAD

**Issue by inkdot7** [zfsonlinux/zfs#5720]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Debian
Distribution Version    | Jessie
Linux Kernel                 | 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30)
Architecture                 | x86_64
ZFS Version                  | v0.7.0-rc3_35_g933ec99
SPL Version                  | v0.7.0-rc3_2_g9704820

### Describe the problem you're observing
Writes fail with commit 933ec99, reporting that the filesystem is full.  With commit 986dd8a it works.

### Describe how to reproduce the problem
```
scripts/zfs.sh
cmd/zpool/zpool create -f lcl sdd3
cmd/zfs/zfs create lcl/t1
touch /lcl/t1/qqq
dd if=/dev/zero of=/lcl/t1/zeros1
```
the last command reports failure:
```
dd: skrivning till ”/lcl/t1/zeros1”: Enheten är full
1+0 poster in
0+0 poster ut
0 byte (0 B) kopierade, 0,000255897 s, 0,0 kB/s
```

Commit 933ec99 is for PR #5673 .  Is the problem some kind of kernel configuration with my (old?) kernel?

I did redo
```
./autogen.sh
./configure --with-spl=/home/htj/z/sep11/spl --enable-debug
make clean
make -j 5
```
after checkout of 933ec99.  (And same with 986dd8a that works.)

**Comment by tuxoko** [comment]
Please post the config.log for zfs.
Also, run dd again with strace.
And try again with this patch https://gist.github.com/tuxoko/9fb1f59717770de9d43d6d6f7c7a29c8

**Comment by inkdot7** [comment]
[config.log_986dd8a.txt](https://github.com/zfsonlinux/zfs/files/746046/config.log_986dd8a.txt)
[config.log_933ec99.txt](https://github.com/zfsonlinux/zfs/files/746047/config.log_933ec99.txt)
[dd_strace_986dd8a.txt](https://github.com/zfsonlinux/zfs/files/746048/dd_strace_986dd8a.txt)
[dd_strace_933ec99.txt](https://github.com/zfsonlinux/zfs/files/746049/dd_strace_933ec99.txt)
[dd_strace_933ec99_iter_write.patch.txt](https://github.com/zfsonlinux/zfs/files/746050/dd_strace_933ec99_iter_write.patch.txt)

Works with patch.

**Comment by tuxoko** [comment]
OK I found the bug. It would affect kernel version 3.16-4.0
I wonder why the test suite didn't catch it.

**Comment by tuxoko** [comment]
Try this https://github.com/zfsonlinux/zfs/pull/5726

**Comment by behlendorf** [comment]
The Debian builder should have caught this, it's running a 3.16.0-4-amd64 kernel.  Also related to these changes see comment   https://github.com/zfsonlinux/zfs/commit/933ec999511f3d29de005bfa8966ae007b161c0f#commitcomment-20703820

**Comment by behlendorf** [comment]
We're only doing build tests on Debian we don't run the full test suite.  There must not be any other kernels in that range running the full suite.

**Comment by grizzlyfred** [comment]
@tuxoko As requested, here the config on my fedora backup box 4.9.6-200.fc25.x86_64 now running 986dd8a ("OpenZFS 5561 - support root pools on EFI/GPT partitioned disks", 2017-01-27)
Because https://github.com/zfsonlinux/zfs/commit/933ec999511f3d29de005bfa8966ae007b161c0f fails to build for me.
[config.log.txt](https://github.com/zfsonlinux/zfs/files/746339/config.log.txt)

There is not much done on that box, it runs 2x2TB HDDs, and an old SSD for a xfs-over-bcache-over-zvol (thanks to yet non-persistent l2arc). So in a way it is good that the federa zfs packages and/or my dkms failed working, I come to contribute to zfs ;-) Although I had a different mind tonight... on my manjaro the tortoishg is broke thanks to qscintilla bindings for python not updated. So the missing zpool (again) on the backup box is rather 2nd prio,..

**Comment by tuxoko** [comment]
@grizzlyfred 
You need to upload the one where build fails.

**Comment by grizzlyfred** [comment]
I thought it was that. I built the 986dd8a ("OpenZFS 5561 - support root pools on EFI/GPT partitioned disks", 2017-01-27) into kmod rpms and installed them, then I git pulled and then I used gitk to hardreset
to  933ec99 configure/make/make pgk... again and then uploaded the file.
Unfortunately, albeit I have I have btrfs as root, I have no automatic snapshotting (think diy snapper or the zfs-auto-snapshot) as on the main workstation, so I cannot check whether it differs from the one which just did build. Sorry. If you really think it is the wrong file, I can ./configure again. But I think my workflow was correct.

**Comment by inkdot7** [comment]
@grizzlyfred you may want to look at #4365.  (Especially if you have some test box.  I have a test backup machine up running with a version of it since a month.)  It ought to be more potent than persistent l2arc.

**Comment by tuxoko** [comment]
@grizzlyfred 
Then you'll need to ./configure again.

**Comment by tuxoko** [comment]
@grizzlyfred 
Ok, never mind, you didn't run ./autogen.sh, and thath's the problem.

**Comment by grizzlyfred** [comment]
Now that you say.. I overlooked that on https://github.com/zfsonlinux/zfs/wiki/Custom-Packages
> Be aware that when building directly from a git repository you must first run the autogen.sh script to create the configure script." 
I never read that text on top, just the commands down. My bad. Now I feel stupid. Yeah autogen.... How could I forget...

**Comment by tuxoko** [comment]
Yeah, you need to rerun ./autogen.sh when you switch version, otherwise new conftest won't get run.

**Comment by grizzlyfred** [comment]
Yep. Current head 0f676dc228862ce0b4f9e27d06d394e9cbaa32e3 successfully built.
