### ISSUE TITLE
Systemd: Problems booting a new system

### ISSUE THREAD

**Issue by Freeaqingme** [zfsonlinux/zfs#5732]
### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Debian
Distribution Version    | Jessie (8)
Linux Kernel                 |  4.4.38
Architecture                 | amd64
ZFS Version                  | 0.6.5.8-1
SPL Version                  | 0.6.5.8-1

### Describe the problem you're observing
On a clean install, at boot I need to press ctrl+D for the system to continue booting. Not just once, but so far every boot. I don't have this problem on other machines. We used to install the ZFS userland utilities from achrives.zfsonlinux.org (package zfsutils), but since it has gone offline we've switched to zfsutils-linux from Debian backports as suggested by the ZoL documentation (and because archives.zfsonlinux.org has been down - #5536 .

The problem was also observed on Linux 4.9.6.

### Describe how to reproduce the problem
Don't know. But I'm hoping the logs will tell you more. To me it's just a clean Debian install. Although the logs do suggest my ext2 partition requires repairing, and that probably breaks things.
 
### Include any warning/errors/backtraces from the system logs
```
# journalctl -xb
[...]
Feb 02 11:36:38 web208 systemd-fsck[338]: /dev/vda1 was not cleanly unmounted, check forced.
Feb 02 11:36:38 web208 mount[350]: The ZFS modules are not loaded.
Feb 02 11:36:38 web208 mount[350]: Try running '/sbin/modprobe zfs' as root to load them.
Feb 02 11:36:38 web208 systemd[1]: srv.mount mount process exited, code=exited status=2
Feb 02 11:36:38 web208 systemd[1]: Failed to mount /srv.
[...]
Feb 02 11:36:38 web208 systemd[1]: Triggering OnFailure= dependencies of local-fs.target.
Feb 02 11:36:38 web208 systemd[1]: Dependency failed for /srv/http.
[...]

# cat /etc/fstab
/dev/mapper/web208-root	/	xfs	defaults	0	1
# /boot was on /dev/vda1 during installation
UUID=120c0757-1588-46ef-ab63-6bb4287e49fe	/boot	ext2	defaults	0	2
/dev/mapper/web208-swap_1	none	swap	sw	0	0
/var/ns	/var/ns	none	rw,bind,rprivate	0	0
cust	/srv	zfs	noexec	0	0
cust/http	/srv/http	zfs	noexec	0	0
/srv/http	/sites	none	rw,bind	0	0
[...]
```

**Comment by skalteis** [comment]
As far as I know it's not recommended to mount zfs datasets from fstab. Remove the last three lines from your fstab and your system should at least boot into a proper runlevel again. Then you can start sorting out whether your zfs modules are loaded properly and troubleshoot your mounts (i.e. set proper zfs properties for your datasets).

**Comment by kpande** [comment]
this is an inappropriate use of the issue tracker, please use [the zfs-discuss mailing list](http://list.zfsonlinux.org) for distribution / support requests.
