### ISSUE TITLE
How to solve with CONFIG_DEBUG_LOCK_ALLOC

### ISSUE THREAD

**Issue by SchrodingerZhu** [zfsonlinux/zfs#5746]
Fedora Rawhide Kernel is automatically built with the option CONFIG_DEBUG_LOCK_ALLOC=y, so I find it unable to built and use ZFS on my system. How can I solve it? If I just use it for personal bussiness, whether I can pass the ./confugure without the CDDL or GNU licence check?

In addition, I hope this project can give support to the Rawhide branch, not just for the versions less equal than fc25.

**Comment by behlendorf** [comment]
@SchrodingerZhu locally you can modify `License:` section the top level META file to real GPL instead of CDDL.  Then re-run `autogen.sh` and `configure`.

Regarding supporting the Rawhide branch could you point me at some documentation describing the how to run a version of Fedora which tracks rawhide?

**Comment by SchrodingerZhu** [comment]
I am not a professional fedora user, but in my opinion, you can follow the rawhide easily by add Rawhide repo to `/etc/yum.repos.d/`.
The rawhide repo should be like this:
```
[fedora]
name=Fedora $releasever - $basearch - ustc
failovermethod=priority
baseurl=https://mirrors.ustc.edu.cn/fedora/development/rawhide/Everything/$basearch/os/
#mirrorlist=https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=$basearch
enabled=1
metadata_expire=7d
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$basearch

[fedora-debuginfo]
name=Fedora $releasever - $basearch - Debug - ustc
failovermethod=priority
baseurl=https://mirrors.ustc.edu.cn/fedora/development/rawhide/Everything/$basearch/debug/
#mirrorlist=https://mirrors.fedoraproject.org/metalink?repo=fedora-debug-$releasever&arch=$basearch
enabled=0
metadata_expire=7d
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$basearch

[fedora-source]
name=Fedora $releasever - Source - ustc
failovermethod=priority
baseurl=https://mirrors.ustc.edu.cn/fedora/development/rawhide/Everything/source/SRPMS/
#mirrorlist=https://mirrors.fedoraproject.org/metalink?repo=fedora-source-$releasever&arch=$basearch
enabled=0
metadata_expire=7d
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$basearch
```
By the way, editing the META file does work, I have successfully built the rpms for my system. Thanks very mush!
