### ISSUE TITLE
dracut boot options insufficient

### ISSUE THREAD

**Issue by Vaelatern** [zfsonlinux/zfs#5753]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Void Linux
Distribution Version    |  Rolling
Linux Kernel                 | 4.9.7
Architecture                 | amd64
ZFS Version                  | 0.6.5.9
SPL Version                  |  0.6.5.9

### Describe the problem you're observing

On a dracut based initramfs, `/etc/default/zfs` describes such options as pool layouts like:
```
void
void/fsroot
void/fsroot/etc
void/fsroot/usr
void/fsroot/var
```
explaining that the mounts under the primary would all be imported automatically. This is incorrect. The option also does nothing even if I do list such (not so hypothetical) datasets.

The text that suggests this is in 
https://github.com/zfsonlinux/zfs/blob/master/etc/init.d/zfs.in#L123-L128

### Describe how to reproduce the problem

Install a Linux with dracut ramdisks and try to use such a layout. Then reboot and watch as the system mounts the primary dataset, dracut realizes it's okay to continue, and watch the kernel panic because the chroot is definitely inadequate.

```
# zpool create void
# zfs create void/fsroot
# zfs create void/fsroot/usr
# zfs create void/fsroot/var
# zfs create void/fsroot/etc
# zfs create void/homes
# zfs set -o mountpoint=/ void/fsroot
# zfs set -o mountpoint=/usr void/fsroot/usr
# zfs set -o mountpoint=/var void/fsroot/var
# zfs set -o mountpoint=/etc void/fsroot/etc
# zfs set -o mountpoint=/home void/homes
# zpool export void
# zpool import -R /mnt void
```

And then I installed void under /mnt, including a hacky symlink so `grub-probe` can identify my root (I'm doing this on top of LUKS)

**Comment by prometheanfire** [comment]
I think the problem is because you have a separate /usr and the fstab generator does not know or do anything about that.  Do you have any log?

**Comment by Vaelatern** [comment]
I'd forgotten about this issue! I do not have logs from this time period, but would love to see this use case working. I do not know anything about the fstab generator. I think the problem relates to the deliberate import commands chosen by the zfs modules at the time, I'd not expect fstab to be relevant.

**Comment by kpande** [comment]
this will work if you use `overlay=on`, unfortunately it's not trivial to "properly" fix this in dracut.
