### ISSUE TITLE
UTF-8 filenames length limit

### ISSUE THREAD

**Issue by TioNisla** [zfsonlinux/zfs#5760]
When used national character set with utf-8 locale, file name length limit of 256 chars effectively divided by two or more. Result: can not store files with more than 127 chars in filename/dirname and more than 2047 in whole path. (libc built with NAME_MAX 511 & PATH_MAX 4096)
```
# name='' ; for i in `seq 0 127` ; do name=$name'z' ; done ; echo $name | wc -c
129
# name='' ; for i in `seq 0 127` ; do name=$name'я' ; done ; echo $name | wc -c
257
```

**Comment by rlaager** [comment]
I tested this. A `touch $name` fails with the second one. But this is not ZFS-specific. It also fails on a tmpfs.
