### ISSUE TITLE
SMB is not unsharing exported pool

### ISSUE THREAD

**Issue by bachmarc** [zfsonlinux/zfs#5761]
Hi,
I am running ZFS on debian.

#>dmesg | grep ZFS
[   20.309104] ZFS: Loaded module **v0.6.5.8-2~bpo8+1**, ZFS pool version 5000, ZFS filesystem version 5

I imported a backup-pool recently, copied some snapshots to it and exported the pool again.
The backup pool inherets all proberties of the productive pool, so the share option by chance.

During import I was told that this and that folder is already shared... it was never my intension to share the backup...

Now after the export I realized the server still exposes all backup folders.

#>smbclient -L 192.168.1.100
Enter root's password:
Domain=[WORKGROUP] OS=[Windows 6.1] Server=[**Samba 4.2.14-Debian]**

        Sharename       Type      Comment
        ---------       ----      -------
        IPC$            IPC       IPC Service (Samba 4.2.14-Debian)
        backup01_audio  Disk      Dataset name: backup01/audio
        backup01_books  Disk      Dataset name: backup01/books
        backup01_cassian Disk      Dataset name: backup01/cassian
 [...]

I tried  zfs unshare -a, I tried restarting smbd&nmbd... still all clients see the backup folders which have currently no running disk to point to...

Of course I could reboot but this is not the solution i would prefer.

1) Why is that pool not gotten unshared during export?
2) How do I clean up now?

Kind regards Marc

**Comment by loli10K** [comment]
> Why is that pool not gotten unshared during export?

It's probably a bug in zfs "unshare" smb code, and should be fixed in https://github.com/zfsonlinux/zfs/commit/2f71caf2d926249920d1b9162550c56715cc6461 (which has not landed in 0.6.5.8).

> How do I clean up now?

Check if they're present in `/var/lib/samba/usershares` (or use `net usershare *` command to list/delete them)

**Comment by bachmarc** [comment]
I think to remember zfs is not using usershares anymore... that's why net usershare list won't display something

**Comment by loli10K** [comment]
> I think to remember zfs is not using usershares anymore...

Very strange, it does for me (zfs-0.7.0-rc3):

```
root@debian-8-zfs:~# POOLNAME='testpool'
root@debian-8-zfs:~# TMPDIR='/var/tmp'
root@debian-8-zfs:~# fallocate -l 128m $TMPDIR/zpool.dat
root@debian-8-zfs:~# zpool create $POOLNAME $TMPDIR/zpool.dat
root@debian-8-zfs:~# zfs create $POOLNAME/fssmb
root@debian-8-zfs:~# strace -qqf -e trace=execve zfs set sharesmb=on $POOLNAME/fssmb
execve("/usr/sbin/zfs", ["zfs", "set", "sharesmb=on", "testpool/fssmb"], [/* 14 vars */]) = 0
sa_enable_share: share->sharepath=/testpool/fssmb, protocol=smb
[pid  4982] execve("/usr/bin/net", ["/usr/bin/net", "-S", "127.0.0.1", "usershare", "add", "testpool_fssmb", "/testpool/fssmb", "Comment: /testpool/fssmb", "Everyone:F"], [/* 14 vars */]) = 0
[pid  4982] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=4984, si_uid=0, si_status=0, si_utime=0, si_stime=0} ---
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=4982, si_uid=0, si_status=0, si_utime=4, si_stime=0} ---
root@debian-8-zfs:~# net usershare list
testpool_fssmb
root@debian-8-zfs:~# ls -l /var/lib/samba/usershares/
total 4
-rw-r--r-- 1 root root 125 Feb  8 16:01 testpool_fssmb
root@debian-8-zfs:~# smbclient -U% -L //localhost
Domain=[WORKGROUP] OS=[Windows 6.1] Server=[Samba 4.2.14-Debian]

	Sharename       Type      Comment
	---------       ----      -------
	print$          Disk      Printer Drivers
	IPC$            IPC       IPC Service (Samba 4.2.14-Debian)
	testpool_fssmb  Disk      Comment: /testpool/fssmb
```

**Comment by loli10K** [comment]
> the bug remains and deleting tons of shares by hand is boring....

Not a bug in ZFSonLinux: even Debian packages use samba "usershares": https://anonscm.debian.org/cgit/pkg-zfsonlinux/zfs.git/tree/lib/libshare/smb.c?h=debian/0.6.5.8-2#n201.

What is probably happening here is that you're still using Turbo's custom branch which contains, among other things, a big libshare/smb rewrite to use registry shares. You can see that from the share comment: mine starts with "_Comment:_" while yours starts with "_Dataset name:_": that is specific of Turbo's branch: https://github.com/FransUrbo/zfs/blob/FAVORITES/lib/libshare/smb.c#L366.

**Comment by bachmarc** [comment]
This sounds to be most likely the reason for having registry shares... I installed ZFS before it became part of debian repository
What I think is a bug ist the failed unshare after export... that maybe  2f71caf

Coming back to turbo's code: I thought i migrated to debian's repository and upgrade runs frequently... why the old code survived in my system and where i failes to migrate 100%?
At the end I do not want to run a mixutre that waits to fail one day...

Marc

**Comment by bachmarc** [comment]
OK, I removed all the old zfs debs and played the manual dependecy solving game in dpkg....

now, i seem to have a clean consistent zfs installation from one source without turbo's branch

I'll see if the export/unshare bug is still there next backup cyvle

Marc
