### ISSUE TITLE
Fedora 25: Failed to synchronize cache for repo 'zfs-testing'

### ISSUE THREAD

**Issue by okket** [zfsonlinux/zfs#5772]
Since a few days I get ```Failed to synchronize cache for repo 'zfs-testing'``` when I update my repos. DNF does not complain about other repos (incl. zfs stable). Wiping all caches, reinstalling the ```zfs-release``` package do not help.

This is just a heads up for a minor infrastructure issue / inconvenience, no complaint. Thanks for the great work.

**Comment by behlendorf** [comment]
@okket thanks letting us know.  The issue should be fixed.

**Comment by okket** [comment]
Yes. No more error. Thank you for the quick response.
