### ISSUE TITLE
Centos 7 rpm update disables ZED

### ISSUE THREAD

**Issue by lschweiss** [zfsonlinux/zfs#5791]
After running an update with yum using the repo at http://download.zfsonlinux.org/epel/zfs-release.el7_3.noarch.rpm zed.rc was replaced and the configured version was moved to zed.rc.rpmsave.

It should not have been replaced with an RPM update.

**Comment by behlendorf** [comment]
I agree.  The strange thing is that everything installed under `/etc/zfs/` is marked noreplace.

-- zfs.spec
```
%config(noreplace) %{_sysconfdir}/%{name}
```

And the right bits in the rpm have been set for noreplace (0x10).  In this case 17 (0x11) are set.

```
$ rpm -qp --qf '[%{filenames}: %{fileflags}\n]' ./zfs-0.6.5.9-1.el7_3.centos.x86_64.rpm | grep zed.rc
/etc/zfs/zed.d/zed.rc: 17
```

**Comment by kpande** [comment]
doesn't occur in 0.7.x
