### ISSUE TITLE
ZFS EL6 repo broken dependency for zfs-dkms

### ISSUE THREAD

**Issue by awnz** [zfsonlinux/zfs#5811]
I *think* this is a repo problem?

Unsatisfied dependency for dkms when trying to install zfs-dkms when both are on offer from the zfs yum repository.

### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | CentOS
Distribution Version    | 6.8
Linux Kernel                 | 2.6.32-642.13.1.el6.x86_64
Architecture                 | x86_64
ZFS Version                  | unable to install!
SPL Version                  | 

### Describe the problem you're observing

When doing:

yum install zfs

I get (truncated):

Error: Package: zfs-dkms-0.6.5.8-1.el6.noarch (zfs)
           Requires: dkms >= 2.2.0.3-20
           Available: dkms-2.2.0.3-2.zfs1.el6.noarch (zfs)
               dkms = 2.2.0.3-2.zfs1.el6
           Installing: dkms-2.2.0.3-14.zfs1.el6.noarch (zfs)
               dkms = 2.2.0.3-14.zfs1.el6
Error: Package: zfs-dkms-0.6.5.8-1.el6.noarch (zfs)
           Requires: dkms >= 2.2.0.3-20
           Available: dkms-2.2.0.3-2.zfs1.el6.noarch (zfs)
               dkms = 2.2.0.3-2.zfs1.el6
           Available: dkms-2.2.0.3-14.zfs1.el6.noarch (zfs)
               dkms = 2.2.0.3-14.zfs1.el6

### Describe how to reproduce the problem

On CentOS 6.8 that hasn't yet had zfsonlinux installed:

yum install http://download.zfsonlinux.org/epel/zfs-release.el6.noarch.rpm
yum install zfs-dkms

### Include any warning/errors/backtraces from the system logs

n/a

**Comment by behlendorf** [comment]
The dkms package is provided by the [epel repository](https://fedoraproject.org/wiki/EPEL).  You'll need to enable it as well as the zfs repository.

**Comment by awnz** [comment]
Thanks, I didn't realise I had failed to get EPEL going on this particular server.

However, it appears a (wrong) dkms package is indeed offered by the ZFS repo. Should this be cleaned up to make the failure more obvious?

Extract from the XML from http://download.zfsonlinux.org/

```
<Contents>
<Key>epel/6/SRPMS/dkms-2.2.0.3-14.zfs1.el6.src.rpm</Key>
<LastModified>2016-08-19T22:45:27.000Z</LastModified>
<ETag>"7d33137a02ac8aefdf58239473f9514d"</ETag>
<Size>103921</Size>
<StorageClass>STANDARD</StorageClass>
</Contents>
<Contents>
<Key>epel/6/SRPMS/dkms-2.2.0.3-2.zfs1.el6.src.rpm</Key>
<LastModified>2016-08-19T22:45:27.000Z</LastModified>
<ETag>"c9a1a1198f706a244820fd8416be731b"</ETag>
<Size>140412</Size>
<StorageClass>STANDARD</StorageClass>
</Contents>
```

**Comment by behlendorf** [comment]
So it is, good catch.  I'll remove it, this is an older version of dkms which was provided prior to some dkms fixes being incorporated upstream.
