### ISSUE TITLE
userquota@ shouldn't be settable higher than quota/refquota

### ISSUE THREAD

**Issue by bunder2015** [zfsonlinux/zfs#5829]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Gentoo
Distribution Version    |  
Linux Kernel                 |  4.4.8-hardened-r1
Architecture                 |  amd64
ZFS Version                  |  0.7.0-rc2_111_g3864055
SPL Version                  |  0.7.0-rc2_8_g8e99d66

### Describe the problem you're observing
It is possible to set userquota@ higher than refquota.  Userquota@ would never be reached because refquota would be reached first.  This might also be possible with regular quota, but I did not check.
### Describe how to reproduce the problem
zfs create mypool/ds
zfs set refquota=10G mypool/ds
zfs set userquota@myuser=20G mypool/ds
zfs get refquota,userquota@myuser mypool/ds

**Comment by bunder2015** [comment]
I was asked on IRC if we should also be allowed to set refquota higher than quota, I personally don't believe so, but I'll leave that up to you folks to decide.  Just a head's up that there may be other instances where we can overallocate quotas.

**Comment by gmelikov** [comment]
Don't know if it's a bug or feature, but this behavior looks good to me, because we can set userquota once and grow our dataset later.

**Comment by kpande** [comment]
actually i don't see an issue with having userquota higher than quota, since the smaller of the two will be enforced anyway.

**Comment by ahrens** [comment]
Quotas of all sorts set limits of space usage.  If there is something else preventing you from filling up a quota all the way, that is not relevant to the quota.  If you want to ensure you can fill your quota all the way, then you must set a reservation to the same size as the quota (although there is no `userreservation` property, so you're out of luck for user quotas).
