### ISSUE TITLE
rpm packages for 0.6.5.9 doesn't exists

### ISSUE THREAD

**Issue by phuture** [zfsonlinux/zfs#5839]
### System information
Type                                | Version/Name
  ---                                  |     0.6.5.9
Distribution Name       | CentOS

### Describe the problem you're observing
There are no rpm packages for latest version of ZoL.

### Describe how to reproduce the problem
http://download.zfsonlinux.org/

**Comment by behlendorf** [comment]
Packages for CentOS 6 were not added to the repository until #5739 has been resolved.  Packages are available for CentOS 7.

**Comment by behlendorf** [comment]
The CentOS 6 kmod and dkms repositories have been updated with spl/zfs-0.6.5.9 built against the 2.6.32-696 kernel. Sorry about the delay.
