### ISSUE TITLE
zpool import allows mount from multiple hosts without -f

### ISSUE THREAD

**Issue by quentinleburel** [zfsonlinux/zfs#5840]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | CentOS
Distribution Version    |  7.3.1611
Linux Kernel                 | 3.10.0-514.6.1.el7.x86_64
Architecture                 | x86_64
ZFS Version                  | 0.6.5.9-1
SPL Version                  | 0.6.5.9-1

### Describe the problem you're observing
zpool import doesn't check if the pool is already mounted 

### Describe how to reproduce the problem
/dev/sdb is visible both by asus05 and asus06 in the config below:
```
[root@asus05 ~]# zpool list
no pools available
[root@asus05 ~]# zpool create tank sdb
[root@asus05 ~]# zpool list
NAME   SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
tank  1.81T    50K  1.81T         -     0%     0%  1.00x  ONLINE  -
[root@asus05 ~]# ssh asus06 zpool list
no pools available
[root@asus05 ~]# ssh asus06 zpool import
   pool: tank
     id: 877838307015933496
  state: ONLINE
 action: The pool can be imported using its name or numeric identifier.
 config:

        tank        ONLINE
          sdb       ONLINE
[root@asus05 ~]# ssh asus06 zpool import tank
[root@asus05 ~]# ssh asus06 zpool list
NAME   SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
tank  1.81T  89.5K  1.81T         -     0%     0%  1.00x  ONLINE  -
```
=> asus06 shouldn't import tank without -f, because it's already mounted on asus05

**Comment by kpande** [comment]
you should probably be using fence_scsi.. but for this level of prevention in zpool import, the idea is to ensure /etc/hostid is unique on each host. I do not think this is a bug. in the future, please use [the zfs-discuss mailing list](http://list.zfsonlinux.org) before opening an issue.

**Comment by quentinleburel** [comment]
my bad, was sure it was a bug, indeed it's not. Works fine when the hostids are properly defined:

```
[root@asus06 ~]# cat /sys/module/spl/parameters/spl_hostid
2874055220
[root@asus05 ~]# cat /sys/module/spl/parameters/spl_hostid
747262265
[root@asus05 ~]# zpool list
no pools available
[root@asus05 ~]# ssh asus06 zpool list
Warning: Permanently added 'asus06' (ECDSA) to the list of known hosts.
no pools available
[root@asus05 ~]# zpool create -f tank sdb
[root@asus05 ~]# zpool list
NAME   SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
tank  1.81T    65K  1.81T         -     0%     0%  1.00x  ONLINE  -
[root@asus05 ~]# ssh asus06 zpool import
   pool: tank
     id: 8304137114772438386
  state: ONLINE
 status: The pool was last accessed by another system.
 action: The pool can be imported using its name or numeric identifier and
        the '-f' flag.
   see: http://zfsonlinux.org/msg/ZFS-8000-EY
 config:

        tank        ONLINE
          sdb       ONLINE
[root@asus05 ~]# ssh asus06 zpool import tank
cannot import 'tank': pool may be in use from other system, it was last accessed by asus05.cluster (hostid: 0x2c8a5139) on Mon Feb 27 18:00:38 2017
use '-f' to import anyway
```

**Comment by kpande** [comment]
thank you. fence_scsi is quite neat and provides better fencing capabilities, potentially even rebooting the node until the PR is free.
