### ISSUE TITLE
Cannot list boomarks of a zvol

### ISSUE THREAD

**Issue by tobia** [zfsonlinux/zfs#5847]
### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Debian (with Proxmox PVE sources.list)
Distribution Version    | 8.6
Linux Kernel                 | 4.4.40-1-pve
Architecture                 | x86_64
ZFS Version                  | 0.6.5.9-1
SPL Version                  | 0.6.5.9-1

### Describe the problem you're observing

Trying to list the bookmarks of a zvol with `zfs list -tbookmark -d1 $ZVOL` gives an error message:

    cannot open '$ZVOL': operation not applicable to datasets of this type

### Describe how to reproduce the problem

Make a filesystem with snapshots and bookmarks, as well as a zvol with snapshots and bookmarks.

You can get all 4 lists of items except for the latter:

```
# zfs list -tsnapshot -d1 $ZFS
NAME  USED  AVAIL  REFER  MOUNTPOINT
...
# zfs list -tbookmark -d1 $ZFS
NAME  USED  AVAIL  REFER  MOUNTPOINT
...
# zfs list -tsnapshot -d1 $ZVOL
NAME  USED  AVAIL  REFER  MOUNTPOINT
...
# zfs list -tbookmark -d1 $ZVOL
cannot open '$ZVOL': operation not applicable to datasets of this type
```

**Comment by behlendorf** [comment]
@tobia commit e33da554c5daf0103b093f44ab5b90ad6c064c3f should have addressed this in master.  We'll see about cherry picking it back for the next point release.

**Comment by kpande** [comment]
@behlendorf we should have a "Backport to Stable" label of some sort

**Comment by behlendorf** [comment]
@kpande we've been using the projects section for this, https://github.com/zfsonlinux/zfs/projects/6.

**Comment by behlendorf** [comment]
Closing, the fix is part of https://github.com/zfsonlinux/zfs/pull/6142
