### ISSUE TITLE
cache coherence problem after zfs rename abortion

### ISSUE THREAD

**Issue by timohaas** [zfsonlinux/zfs#5870]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Debian
Distribution Version    | Stretch
Linux Kernel                 | 4.9.0-1
Architecture                 | amd64
ZFS Version                  | 0.6.5.9-2
SPL Version                  | 0.6.5.9-1

### Describe the problem you're observing
open thunar and navigate to folder /tank
zfs create tank/video/test
zfs rename tank/video/test tank/video/test:test
CTRL-C abort rename (i did a large transfer during the rename)
ls /tank/video => returns test instead of test:test
zfs list shows the correct dataset name

after 
zpool export
zpool import
the problem is solved and
ls /tank shows test:test

### Describe how to reproduce the problem
could not reproduce
### Include any warning/errors/backtraces from the system logs

```
I think there might be a cache coherence problem.
```

**Comment by kpande** [comment]
if you aborted rename, chances are it didn't remount, so your dataset was mounted with the previous path. when exporting and importing, it remounted. this however, is not a bug and it's better that you use [the mailing list](http://list.zfsonlinux.org) for support requests.
