### ISSUE TITLE
ZVOL ioctl(BLKFLSBUF) doesn't flush device buffers

### ISSUE THREAD

**Issue by adilger** [zfsonlinux/zfs#5871]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | 
Distribution Version    | 
Linux Kernel                 | 
Architecture                 | 
ZFS Version                  | github master
SPL Version                  | 

### Describe the problem you're observing
I was reviewing the ZoL code related to whether ```zpool import``` was using ```ioctl(BLKFLSBUF)``` to flush the underlying block device (will file a separate issue on that).  I noticed the only place this value appears is in the EFI partitioning code and for the ZVOL code:

```
 zvol_ioctl(struct block_device *bdev, fmode_t mode,
    unsigned int cmd, unsigned long arg)
{
        :
        case BLKFLSBUF:
                zil_commit(zv->zv_zilog, ZVOL_OBJ);
                break;
        } 
```

In the above code, it is only committing the current TXG, but not actually making any effort to flush the pages for that ZVOL from the page cache as required. 

```
 static int blkdev_flushbuf(struct block_device *bdev, fmode_t mode,
                unsigned cmd, unsigned long arg)
 {
        int ret;

        if (!capable(CAP_SYS_ADMIN))
                return -EACCES;

        ret = __blkdev_driver_ioctl(bdev, mode, cmd, arg);
        if (!is_unrecognized_ioctl(ret))
                return ret;

        fsync_bdev(bdev);
        invalidate_bdev(bdev);
        return 0;
  }
```

**Comment by behlendorf** [comment]
> not actually making any effort to flush the pages for that ZVOL from the page cache as required.

It's true the page cache won't be flushed in `zvol_ioctl()`, and in fact the `zil commit()` is a little redundant and perhaps should be dropped since it could hurt performance.

But the page cache will be flushed slightly latter in  `fsync_bdev() -> sync_blockdev() -> __sync_blockdev() -> filemap_write_and_wait()`.  What I'm not positive about is if we'll get a REQ_OP_FLUSH bio after writing all the async pages to force a `zil_commit()`.  But it seems like we must and setting the right ops would be the responsibility of the upper layers forming the bios.  In the zvol we just need to honor what we're given.

**Comment by behlendorf** [comment]
Let's see if we can get @tuxoko's thoughts on this too.

**Comment by tuxoko** [comment]
There's almost no explicit BLKFLSBUF in the kernel, so I think we should do nothing and return -ENOTTY and let `fsync_bdev` do the work.

@behlendorf 
The `fsync_bdev` won't be called if you don't return -ENOTTY.

**Comment by behlendorf** [comment]
Ahh, I misread that conditional.  Then yes, we should definitely remove the BLKFLSBUF case so -ENOTTY is returned here and `fsync_bdev()` can do the heavy lifting.

**Comment by adilger** [comment]
```BLKFSLBUF``` isn't about writing out dirty buffers as the comments imply, but rather about dropping pages from the cache completely.  This is used, for example, before re-reading a modified partition table from disk, or if a block device is used in an HA environment and the disk may be modified by a different node behind the back of the local node's cache.

It is possible that this is still being handled indirectly by ```blkdev_ioctl()``` somewhere in the call stack for the ZVOL, but I couldn't find it.

The reason I was looking into the use of BLKFLSBUF by ZFS was to see if the ```zpool --import``` code was flushing the block device buffers before accessing the pool from disk, in case there are stale pages cached in RAM on the local node that were modified by another node on disk (i.e. an active/passive HA environment).  It is possible to do this in userspace via ```blockdev --flushbufs``` for each disk in the pool, but it would be much more convenient if ```zpool --import --flushbufs``` was added as an option since zpool already knows which disks to import.  This is important in the case of non-fatal HA failover/failback operations, where STONITH is not involved, since it would be bad to e.g. base operations after import on an old version of the überblock contents.

**Comment by tuxoko** [comment]
> BLKFSLBUF isn't about writing out dirty buffers as the comments imply, but rather about dropping pages from the cache completely

It does both write and drop.
```
fsync_bdev(bdev);
invalidate_bdev(bdev);
```

**Comment by behlendorf** [comment]
> to see if the zpool --import code was flushing the block device buffers before accessing the pool from disk

The code doesn't use BLKFLSBUF to drop the pages from the cache, although that's probably a good idea.  It does use O_DIRECT to bypass the cache to avoid getting stale data in a fail-over situation.  The devices are also opened O_EXCL to ensure there's always only one local consumer.

**Comment by adilger** [comment]
On Mar 7, 2017, at 16:45, Brian Behlendorf <notifications@github.com> wrote:
> The code doesn't use BLKFLSBUF to drop the pages from the cache, although that's probably a good idea. It does use O_DIRECT to bypass the cache to avoid getting stale data in a fail-over situation. The devices are also opened O_EXCL to ensure there's always only one local consumer.
> 

I didn't think about the use of O_DIRECT, which would also avoid the use of cached pages on a backup server during the import. Is O_DIRECT used only for reading the überblock, or is all ZFS block device IO done with O_DIRECT because it has its own ARC to cache the data?

**Comment by behlendorf** [comment]
O_DIRECT is used to verify the labels and uberblocks on the devices we were given by blkid.  From the label information the pool configuration is built up and passed to the kernel for use when importing.  Things are much better in this regard in 0.7.0-rc3 and newer.  We ran down a bunch of subtle issues which can occur with shared disks or even just with multi-path configurations.

c30d8ded0c8c64a9a144cf478502bb4e512ab9fa Fix 'zpool import' detection issue
83bf769d500a231eac023c9f9f88719ad205694e Fix 'zpool import' detection issues

**Comment by behlendorf** [comment]
Going back to the original issue I've opened #5879 with a proposed fix.  It pulls `fsync_bdev(bdev)` down in to `zvol_ioctl()` to make sure the page cache gets flushed and waits for a txg sync.  The page cache is invalidated and all ARC buffers backing the ZVOL are evicted.
