### ISSUE TITLE
Did zfs works well with virtio? 

### ISSUE THREAD

**Issue by sunzhaoyang** [zfsonlinux/zfs#5884]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Redhat
Distribution Version    | 7.2
Linux Kernel                 | 3.10.0-327.el7.x86_64 
Architecture                 | 
ZFS Version                  | 0.6.5.9
SPL Version                  | 0.6.5.9

```
$lsmod |grep zfs | awk '{print $1}' | xargs -i modinfo {} | grep -E '^version:'
version:        0.6.5.9-1
version:        0.6.5.9-1
version:        0.6.5.9-1
version:        0.6.5.9-1
version:        0.6.5.9-1
version:        0.6.5.9-1
```
### Describe the problem you're observing
I Got the same issue here:https://github.com/zfsonlinux/zfs/issues/4065

zfs (0.6.5.x) dosn't work well with virtio, and I can't use AHCI for some reason.

I had test 0.6.4.x ,and everting seemed ok.

Two Question:
1. Is there a plan to fix this problem or I had to use 0.6.4.2 forever?
2. Is it ok if I downgrade zfs from 0.6.5.7 to 0.6.4.2 ?Would it case data corrupt?

Thank you!

### Describe how to reproduce the problem

Attach two vol into kvm both with virtio, one from lvm ,another from zpool.

Start fio on the zvol only, in vm.

You will see this:

![qq20170311-123412](https://cloud.githubusercontent.com/assets/2182116/23820598/1613b918-0657-11e7-9dd0-b08b76009818.png)

**Comment by sunzhaoyang** [comment]
Why this issue got closed?

**Comment by kernelOfTruth** [comment]
@sunzhaoyang you opened a duplicate issue (one is enough),

you stated questions - those are best answered in the mailing list(s) or IRC,

this isn't a support forum

**Comment by sunzhaoyang** [comment]
Got it! Thanks~
