### ISSUE TITLE
ZFS broken after dist-upgrade

### ISSUE THREAD

**Issue by s-geissler** [zfsonlinux/zfs#5886]
### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Linux Mint 18 Sarah
Distribution Version    |  18
Linux Kernel                 |  4.4.0-64-generic
Architecture                 |  amd64
ZFS Version                  | v0.6.5.9-1~trusty
SPL Version                  | v0.6.5.9-1~trusty

I just recently upgraded from Linux Mint 17 to Linux Mint 18 using mintupgrade. This is essentially an upgrade from Ubuntu 14.04 to 16.04. Since the upgrade, my pools are not being imported automatically on reboot. Instead i have to import them manually using `zpool import $poolname`. Further, I had to add `zfs`to `/etc/modules`, which was not required before the upgrade.

I have checked to recreate the `/etc/zfs/zpool.cache` file as well as `/etc/hostid` file. Both did not resolve my issue.

Since the upgrade removed all PPAs from the system, it seems I ended up with a set of broken ZFS packages. Essentially I assume the problem originates from a lot of the ZFS services being gone. At least the only registered ZFS service is `zfs-share`.

Output of `apt install zfs`:

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'zfsutils-linux' instead of 'zfs'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 zfsutils-linux : Depends: zfs-doc (= 0.6.5.6-0ubuntu15) but 0.6.5.9-1~trusty is to be installed
                  Depends: libnvpair1linux but it is not going to be installed
                  Depends: libuutil1linux but it is not going to be installed
                  Depends: libzfs2linux but it is not going to be installed
                  Depends: libzpool2linux but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

And the output of `apt search zfs`:

```
p   golang-go-zfs-dev
p   libguestfs-zfs
p   libguestfs-zfs:i386
i A libzfs2
p   libzfs2linux
p   libzfs2linux:i386
p   libzfs2linux-dbg
p   libzfs2linux-dbg:i386
p   libzfslinux-dev
p   libzfslinux-dev:i386
v   lzfs
v   lzfs:i386
v   lzfs-dkms
v   lzfs-dkms:i386
i   ubuntu-zfs
v   zfs
v   zfs:i386
i   zfs-dkms
p   zfs-dkms:i386
i A zfs-doc
p   zfs-fuse
p   zfs-fuse:i386
p   zfs-initramfs
p   zfs-zed
p   zfs-zed:i386
p   zfs-zed-dbg
p   zfs-zed-dbg:i386
p   zfsnap
i   zfsutils
p   zfsutils-linux
p   zfsutils-linux:i386
p   zfsutils-linux-dbg
p   zfsutils-linux-dbg:i386
```

Question is, how to resolve the issues without losing the data on my pool. If further information is required, I will gladly provide it.

**Comment by aikudinov** [comment]
You won't loose data just by playing with packages, but you might have a problem booting if you have zfs root and mess something badly. 
If I remember correctly, I had similar issues dist-upgrading from previous ubuntu release with ppa packages to ubuntu packages, which happens because zfs ppa is conflicting with ubuntu zfs. Normally you should remove all PPAs before upgrading (annoying) or deal with the mess yourself. The obvious thing to try is "apt-get install -f", probably removing some old ppa packages and installing new ones.

**Comment by s-geissler** [comment]
Already tried all that. I also (by now) tried to uninstall all remaining PPA packages and installing ZFS freshly via `apt install zfs`. Some packages are being installed but (e.g.) the kernel module is missing afterwards, so it just doesn't work at all right now. Seems the apt provided module is not working with my kernel version.

**Comment by aikudinov** [comment]
Are you sure you don't have any apt pinning in action?
Also 16.04 should be xenial and yours says 0.6.5.9-1~trusty to be installed, are you sure you don't have ppa in sources.list* somewhere? Not sure what should be the right one for mint...
What does "apt policy zfsutils-linux" says?

**Comment by s-geissler** [comment]
```
zfsutils-linux:
  Installed: (none)
  Candidate: 0.6.5.6-0ubuntu15
  Version table:
     0.6.5.6-0ubuntu15 500
        500 http://ftp.tu-ilmenau.de/mirror/ubuntu xenial-updates/main amd64 Packages
     0.6.5.6-0ubuntu8 500
        500 http://ftp.tu-ilmenau.de/mirror/ubuntu xenial/universe amd64 Packages
```

According to https://www.mail-archive.com/kernel-packages@lists.launchpad.net/msg216862.html there is a bug that affects more recent kernels. However, building 0.6.5.9 from source does not work either. I build and installed the deb packages created from source and it still doesn't work. Guess i will just downgrade the kernel until the repos provide the fixed version.

**Comment by s-geissler** [comment]
I just downgraded to Kernel 4.4.0-21 and everything went back to working after a simple `apt install spl spl-dkms` followed by `apt install zfs`. So it was just the issue with the kernel changes from the link above.

\closed

**Comment by gmelikov** [comment]
@s-geissler please, next time write to your distributive tracker or our mailing lists first, we don't provide packages for Debian-like repositories now. Glad that you found your problem, closed.
