### ISSUE TITLE
zpool status

### ISSUE THREAD

**Issue by gigeCDN** [zfsonlinux/zfs#5889]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Centos
Distribution Version    |  6
Linux Kernel                 |  2.6.32-042stab106.4 #1 SMP Fri Mar 27 15:19:28 MSK 2015 x86_64 x86_64 x86_64 GNU/Linux

Architecture                 | x86_64
ZFS Version                  |  version:        0.6.4-1
SPL Version                  |  version:        0.6.4-1

Commands to find ZFS/SPL versions:
modinfo zfs | grep -iw version
version:        0.6.4-1
modinfo spl | grep -iw version 
version:        0.6.4-1

### Describe the problem you're observing
on mirror vdev deatch zpool status is borked
### Describe how to reproduce the problem

```
before:
        NAME                                               STATE     READ WRITE CKSUM
        zfsmirrordata0                                     ONLINE       0     0     0
          mirror-0                                         ONLINE       0     0     0
            pci-0000:03:00.0-sas-0x4433221101000000-lun-0  ONLINE       0     0     0
            pci-0000:03:00.0-sas-0x4433221103000000-lun-0  ONLINE       0     0     0
          mirror-2                                         ONLINE       0     0     0
            pci-0000:03:00.0-sas-0x4433221102000000-lun-0  ONLINE       0     0     0
            pci-0000:03:00.0-sas-0x4433221100000000-lun-0  ONLINE       0     0     0
          mirror-3                                         ONLINE       0     0     0
            pci-0000:03:00.0-sas-0x4433221105000000-lun-0  ONLINE       0     0     0
            pci-0000:03:00.0-sas-0x4433221104000000-lun-0  ONLINE       0     0     0
```

run:
zpool detach zfsmirrordata0 /dev/disk/by-path/pci-0000:03:00.0-sas-0x4433221104000000-lun-0

```
after:
        NAME                                                   STATE     READ WRITE CKSUM
        zfsmirrordata0                                         ONLINE       0     0     0
          mirror-0                                             ONLINE       0     0     0
            pci-0000:03:00.0-sas-0x4433221101000000-lun-0      ONLINE       0     0     0
            pci-0000:03:00.0-sas-0x4433221103000000-lun-0      ONLINE       0     0     0
          mirror-2                                             ONLINE       0     0     0
            pci-0000:03:00.0-sas-0x4433221102000000-lun-0      ONLINE       0     0     0
            pci-0000:03:00.0-sas-0x4433221100000000-lun-0      ONLINE       0     0     0
          pci-0000:03:00.0-sas-0x4433221105000000-lun-0        ONLINE       0     0     0 <--- check me
```

did not saved  zdb but looked ok

after:
zpool attach zfsmirrordata0 -f /dev/disk/by-path/pci-0000\:03\:00.0-sas-0x4433221105000000-lun-0 /dev/disk/by-path/pci-0000:03:00.0-sas-0x4433221104000000-lun-0

zpool status look back ok

**Comment by devonblzx** [comment]
It's hard to tell without indentation, is the problem that the vdev is showing in mirror-2 or is it that the vdev isn't showing in a mirror at all?

**Comment by gigeCDN** [comment]
Issue is that is it that vdev isn't showing in a mirror at all, however u can see it not align against the others, it starts before.
I have upgraded it since, but is in production so wont be able to replicate on that server.

**Comment by kpande** [comment]
if you detach, the vdev is no longer a mirror.
