### ISSUE TITLE
Debian Jessie Root on ZFS - grub-install error

### ISSUE THREAD

**Issue by 4wk-** [zfsonlinux/zfs#5891]
Hi guys.

I'm pretty new to Github so please feel free to correct me. @gmelikov  @rlaager 

For the third time, I'm trying to setting up my brand new company server (DELL PowerEdge R330 - 6HDD) following the Debian Jessie Root on ZFS. Indeed, I tried twice in the late 2016, unsuccessfully. But several changes had occured in this HOW TO, so I decided last week to give it another shot.

I'm not a sysadmin, but I got solid notions about Unix ; I am really convinced by the zfs architecture du to this article https://blogs.oracle.com/partnertech/entry/a_hands_on_introduction_to2 : It seems to me really powerfull in term of keeping data even with burnt HDD (our old server runs RAID hardware).

Here is the thing: I followed all the HOW TO, planning to create a mirror pool on my 6 HDD. I choose to go with UEFI booting instead of legacy (random choice). And I get tricked at the very last of the HOW TO, part 5, instruction 5.5b:

I get this output: 
```
Installing for x86_64-efi platform.
EFI variables are not supported on this system.
EFI variables are not supported on this system.
grub-install: error: efibootmgr failed to registrer the boot entry: No such file or directory.
```

I'm pretty sure I followed the right way, I did grub instructions every time on the 6 HDD, as asked.
Naively, I thought I would still be able to boot ; so I tried, ejecting the live CD and it failed with the output:

```
Booting from DVD-ROM
Bootind from Hard drive C:
Booting from BRCM MBA Slot

PXE-E53: No boot filename received
PXE-MOF: Exiting Broadcom PXE ROM.

No boot device abailable or Operating System detected.
Current boot mode is set to BIOS.
Please ensure a compatible bootable media is available.
```

My questions are:
a) - Are you guys any idea of what I missed?
b) - Am I able to fix this boot without reformating HDD and give it another try to this huge HOW TO with the legacy boot?

Thanks a lot.

**Comment by gmelikov** [comment]
About your problem - I googled and found `If the machine was booted from MBR then grub-install (or efibootmgr) will fail to create the efi boot entry with the following error: EFI variables are not supported on this system`. You should try to search before ask.

Please, next time use our mailing lists or irc, this is not a support forum. Closed.

**Comment by 4wk-** [comment]
Hello @gmelikov 

Thank you for your reply. Unfortunaly, I googled a lot before posting, including stackoverflow and so on. But installing ZFS Root is very specific and nothing of what I found help me with my problem. That's why I posted here, as asked in the HOW TO.

> If you have bugs or feature requests related to this HOWTO, please file a new issue and mention @gmelikov and @rlaager.

Even if I booted on the live CD from MBR, that doesn't help me with my question b).

If I still need help on this, should I go on IRL or use the mailing list?
Sorry for the inconvenience, have a good day.

Regards,

**Comment by gmelikov** [comment]
If you have a problem with ZFS - Grub usually give you some message about file system.

> Even if I booted on the live CD from MBR,
You will have exactly this message if you boot from MBR and try to install grub as EFI.

Did you check that grub can install EFI on another FS on this server? Maybe you have some misconfiguration in bios?

**Comment by 4wk-** [comment]
Ok, I understand. I'm not super familiar with the EFI boot either way. I didn't change a thing in the BIOS, as it's a brand new server.

So let's say I mount in chroot ; I think I will be stuck anyway: in the step 2.2, HDD were partionned for an UEFI boot, so if I can't change boot method easily, I'm stuck.

Thanks anyway, I'm gonna reset HDD and table partionning and try the legacy one!

**Comment by gmelikov** [comment]
> it's a brand new server
Brand new servers doesn't always have settings which you need to work. Good luck!

**Comment by 4wk-** [comment]
Hey @gmelikov that's it, I just succedded in booting, following the HOW TO with the legacy boot instead of UEFI. Yay!

I'm however stuck with a behaviour I don't understand. I've post the question on StackOverFlow, but so far no answer. If you wishe to [take a look](http://stackoverflow.com/questions/42817256/zfs-hotspare-replace-detach-ressource-is-busy), I would really appreciated it.

I guess I missunderstood some concept with ZFS :/

**Comment by 4wk-** [comment]
I forgot one thing: on the HOW TO, several lines (13) contains `apt install `; you should rename these in `apt-get install` ;

Thanks @gmelikov @rlaager

**Comment by jwittlincohen** [comment]
@4wk- 

apt install performs the same function as apt-get install.  It just offers some nice new features like color coding and a progress bar.  Apt is meant to be easier to use than apt-get, and is a drop-in replacement for most tasks.  Why do you want to change the howto?

**Comment by 4wk-** [comment]
Oh, my bad, I didn't know at all. I though it was a typo from the original ubuntu HOW TO. I tried to set up a server with this HOW TO 4 times, and 4 times I typed `apt-get install` ;)
