### ISSUE TITLE
cannot import 'zroot': unsupported version or feature

### ISSUE THREAD

**Issue by jfburdet** [zfsonlinux/zfs#5892]
Hi,

I'm using ZOL, on Arch, by adding the following lines to /etc/pacman.conf

```
[archzfs]
Server = http://archzfs.com/$repo/x86_64
```

I rebooted my server today, but it's unable to boot :

```
This pool uses the following feature(s) not supported by this system:
        org.zfsonlinux:userobj_accounting (User/Group object accounting.)
All unsupported features are only required for writing to the pool.
The pool can be imported using '-o readonly=on'.
cannot import 'zroot': unsupported version or feature
```

I made a rescue USB key, but I'm facing same issue. 

The module version is as following :

```
root@archiso / # modinfo zfs
filename:       /lib/modules/4.10.1-1-ARCH/extra/zfs/zfs.ko.gz
version:        0.6.5.9-1
license:        CDDL
author:         OpenZFS on Linux
description:    ZFS
srcversion:     42C4AB70887EA26A9970936
depends:        spl,znvpair,zcommon,zunicode,zavl
vermagic:       4.10.1-1-ARCH SMP preempt mod_unload modversions
```

Any hint to make thinks work again is welcome.

**Comment by jfburdet** [comment]
I still don't get how this feature has been added to my pool ... it seems from a future version that is still in beta.

Anyway, I will attach another disk, and do some zfs send/receive to recreate a moutable copy of my pool

**Comment by jfburdet** [comment]
(Closing because i'm not respecting reporting guidelines)

**Comment by skjeggape** [comment]
i'll comment here even if this is closed.
I am facing identical issue after latest updates on arch. there where som problems with spl not building but after that evryting looked fine until reboot as i now face the same issue.

any fix for this?
