### ISSUE TITLE
After reboot CentOS7  can‘t import pool with ramdisk

### ISSUE THREAD

**Issue by serennity** [zfsonlinux/zfs#5897]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | CentOS7
Distribution Version    | 7.2
Linux Kernel                 | 3.10.0-327
Architecture                 | 64bit
ZFS Version                  | 0.7.0-rc3
SPL Version                  | 0.7.0-rc3

### Describe the problem you're observing
ramdisk  zil log device will unavail after reboot 
### Describe how to reproduce the problem
step1: modprobe brd rd_nr=2 rd_size=10485760  max_part=0
step2: zpool create rpool /dev/sda /dev/sdb  zpool add rpool log /dev/ram0  
step3: reboot 
step4: zpool import -a  

### Include any warning/errors/backtraces from the system logs

```
# zpool import -m
   pool: rpool
     id: 16534096154258433495
  state: UNAVAIL
 status: One or more devices are missing from the system.
 action: The pool cannot be imported. Attach the missing
	devices and try again.
   see: http://zfsonlinux.org/msg/ZFS-8000-6X
 config:

	  pool      UNAVAIL  missing device
	  sda        ONLINE
	  sdb        ONLINE

	Additional devices are known to be part of this pool, though their
	exact configuration cannot be determined.

```

```
#zpool import -fm rpool
  pool: rpool
 state: DEGRADED
status: One or more devices could not be used because the label is missing or
	invalid.  Sufficient replicas exist for the pool to continue
	functioning in a degraded state.
action: Replace the device using 'zpool replace'.
   see: http://zfsonlinux.org/msg/ZFS-8000-4J
  scan: none requested
config:

	NAME                    STATE     READ WRITE CKSUM
	rpool                 DEGRADED     0     0     0
	  sda                   ONLINE       0     0     0
	  sdb                   ONLINE       0     0     0
	logs
	  15942034284181244096  UNAVAIL      0     0     0  was /dev/ram0

errors: No known data errors
```

it seems that the guid of ram0 has changed .

**Comment by bunder2015** [comment]
Using a ramdisk for your SLOG/ZIL defeats the point of having one to begin with.  Use a SSD or another disk.

**Comment by gmelikov** [comment]
If I understand it right - your /dev/ram0 is empty after reboot. Maybe that's the problem?

**Comment by bunder2015** [comment]
It would also get erased should the system experience any other form of power loss (shutdown, UPS/mains failure), it needs to be located on actual physical storage instead of a virtual memory device.

**Comment by tuomari** [comment]
You can achieve the same result with setting `zfs set sync=off rpool` without having to recreate the ramdisk every time. Both practices (having sync=off and ramdisk as LOG) are higly unadviced practices and should not be used, unless you understand the ramifications!
