### ISSUE TITLE
"zpool online -e" does not work with IP/FC SAN or luns attached to virtual machine when expanding zpool

### ISSUE THREAD

**Issue by jinqzhen** [zfsonlinux/zfs#5899]
"zpool online -e" does work with lvm luns, but when it comes with IP/FC SAN or luns attached to virtual machine, the pool will never expand.
1.    Create a zpool with an initial size of 100GB.
2.    Expand the IP/FC SAN disk to 500GB
3.    Rescan device in Linux such that kernel sees new size (fdisk -l shows correct size)
4.    Run "zpool online -e tank1 sdb", this update partition table on disk successfully, but rescan partition table failed(accomplished in module function "vdev_disk_rrpart").

As I know, this is caused by rescan partition table fails, which accomplished by "BLKRRPART" ioctl in vdev_disk_rrpart. "BLKRRPART" will delete all partitions and rebuild the partition table, this can not be done because partition 1 is used by the zpool. The following steps can do partition table rescan successfully if you add it after rdwr_efi.c->efi_use_whole_disk(int fd)->efi_write:
1.BLKPG_DEL_PARTITION -> delete partition 9
2.BLKPG_RESIZE_PARTITION -> resize partition 1
3.BLKPG_ADD_PARTITION -> add partition 9
But "BLKPG_RESIZE_PARTITION" was since linux kernel 3.6, so how to fix this?

test with:
zfs version: 0.6.5.* and master
OS:ubuntu 16.04 or centos 7
kernel version: 3.10, 4.4 and 4.8
iSCSI Target: LIO
virtual machine: qmeu-kvm
virtual disk: virtIO SCSI and virtIO blk

**Comment by behlendorf** [comment]
> this can not be done because partition 1 is used by the zpool.

@jinqzhen thanks for filing this issue, could you explain this comment further.  I ask because this shouldn't be an issue `vdev_disk_rrpart()` is called before opening the block device.  Exactly what is the failure and errno you're seeing.

**Comment by jinqzhen** [comment]
@behlendorf  Sorry about that, I do not really see what error happened with "vdev_disk_rrpart()". I just know "vdev_disk_rrpart()" is used to rescan the partition table but the partition table rescan failed. Maybe other errors happened while reopening the vdev. I should see what really happened while reopening the vdev.

**Comment by kpande** [comment]
we've not seen this one in a while. does it still occur for you?
