### ISSUE TITLE
no zfs-0.6.5.9 rpm in download.zfsonlinux.org/epel repository

### ISSUE THREAD

**Issue by miesi** [zfsonlinux/zfs#5900]
I can't find zfs 0.6.5.9 rpms for RHEL6 x86_64 on http://download.zfsonlinux.org/epel/6/x86_64.

Has support for zfs on RHEL 6 ended?

**Comment by behlendorf** [comment]
@miesi the RHEL6 repo wasn't updated with 0.6.5.9 due to issue #5739 which was observed after it was tagged.  The warning only appears with older RHEL kernels and is harmless but we held off updating the repo until it's resolved in 0.6.5.10.
