### ISSUE TITLE
zpool import hangs forever after replacing disk and reboot

### ISSUE THREAD

**Issue by godspeed-you** [zfsonlinux/zfs#5924]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Debian Jessie
Distribution Version    |  8
Linux Kernel                 |  3.16.39-1+deb8u2
Architecture                 |  x86_64
ZFS Version                  |  0.6.5.9-2~bpo8+1
SPL Version                  |  0.6.5.9-1~bpo8+1

### Problem:
zpool cannot be imported anymore. 

### Pre error:
- Zpool is a raidz1 containing three hard disks and several zfs volumes
- One disk had two offline sectores and showed signs of a nearby breakdown
- I replaced this device with a new one
- I do not remember completely - I think I was rebooting the system after the rebuilding and it was still working - maybe this is a misleading/wrong information 
- Last time the pool was active and zfs volumes accessable one volume was probably failing 
- After a reboot the pool could not be imported again. Respectively the system hung forever at booting (while trying to import the zpool)
- Any further attemps have been made with disconnect disks on boot and attaching them in running system (I am desperate)

### What I tried:
- list the importable pools: ```import zpool``` was successful and showed the missing pool
- importing this pool leading into an endless import. I had to hard reset the system. This happend on almost all later attemps
- import with the serveral options zpool import is shipped with: no success
- removing the new hard disk and trying to import with only the old two devices: no success
- zdb -l on the any disk returns 4 labels containing reasonable information about the pool
- Importing the pool on an Ubuntu live cd, or ZFSGuru: no success 
- I tried several combinations of importing with only two devices: no success
- clone of the old two disks to new disks and trying to import with -T option: no success but different behaviour. After a couple of hours the command return something like "cannot import: one or more devices is currently unavailable"

### Some more information:
- with all the old devices the pool shows up as degraded with the replaced devices as unavailbale. This device has not been unavailable when it was replaced. The system was up for 7 months until the first reboot for replacing the disk.
- I can deliver almost all data if needed or if I forgot something

### Questions:
- Any suggestions to this case at all? I have at the moment 6 drives: 2 drives are clones of each other, one drive has been rebuild by zfs, so I am able to try even risky things
- How are my chances to get my data from these drives at all? I would destroy the pool and rebuild if I can get these data back. 
- Is it possible to create a new pool containg the zfs volumes if I use the existing disks?

**Comment by behlendorf** [comment]
@godspeed-you could you please post the pool configuration (output of `zpool status`).  How much redundancy was the pool configured with?

I'd also suggest trying to import the pool read-only.  This minimizes the amount of information which needs to be read from the pool so if there's a particular non-critical block which is causing the import to fail this may prevent the issue.  `zpool import -o readonly=on`.

**Comment by godspeed-you** [comment]
Hi,
thanks for the response! I followed your suggestion and was successful for importing the pool and mounting most of my volumes. Except one volume is missing. 
As I mentioned, I have a raidz1 configuration containing three disks. Below the output of ```zpool status```:

```
  pool: wg
 state: ONLINE
status: One or more devices has experienced an error resulting in data
        corruption.  Applications may be affected.
action: Restore the file in question if possible.  Otherwise restore the
        entire pool from backup.
   see: http://zfsonlinux.org/msg/ZFS-8000-8A
  scan: scrub repaired 8K in 4h54m with 2 errors on Thu Mar  2 18:17:23 2017
config:

        NAME        STATE     READ WRITE CKSUM
        wg          ONLINE       0     0     1
          raidz1-0  ONLINE       0     0     4
            hgst1   ONLINE       0     0     0
            wg2     ONLINE       0     0     0
            wg3     ONLINE       0     0     0
```

**Comment by godspeed-you** [comment]
Here the output of the import:
```
root@myserver:~# zpool import -o readonly=on wg
unable to fetch ZFS version for filesystem 'wg/lager'
cannot mount 'wg/lager': Die Ressource ist zur Zeit nicht verfügbar
```
Translation: "The ressource is not available at the moment"

**Comment by godspeed-you** [comment]
Additionally the output of ```zfs  get version wg/lager```:
```
root@myserver:~# zfs get version wg/lager
NAME      PROPERTY  VALUE    SOURCE
wg/lager  version   -        -
```

**Comment by godspeed-you** [comment]
In my opinion zfs should be able to mount a dataset even if the version can not retrieved. In worst case by specifying the version manually. 

(Sorry for not coming back earlier - I just waited for a reaction to my last comments)
