### ISSUE TITLE
CentOS 2.6.32-696.el6 symbol change posix_acl_equiv_mode

### ISSUE THREAD

**Issue by dmaziuk** [zfsonlinux/zfs#5930]
### System information
Distribution Name       |  centos
Distribution Version    |  6
Linux Kernel                 |  2.6.32-696.el6.x86_64
Architecture                 | AMD x64
ZFS Version                  | kmod-zfs-0.6.5.8-1.el6.x86_64
SPL Version                  | kmod-spl-0.6.5.8-1.el6.x86_64

### Describe the problem you're observing

No zpool after kernel upgrade.

```
# modprobe zfs
FATAL: Module zfs not found.
```

### Include any warning/errors/backtraces from the system logs
```
  Installing : kmod-zfs-0.6.5.8-1.el6.x86_64                                                                                                             1/1 
WARNING: /lib/modules/2.6.32-696.el6.x86_64/weak-updates/zfs/zpios/zpios.ko needs unknown symbol dmu_tx_hold_write
WARNING: /lib/modules/2.6.32-696.el6.x86_64/weak-updates/zfs/zpios/zpios.ko needs unknown symbol dmu_read
WARNING: /lib/modules/2.6.32-696.el6.x86_64/weak-updates/zfs/zpios/zpios.ko needs unknown symbol dmu_tx_assign
WARNING: /lib/modules/2.6.32-696.el6.x86_64/weak-updates/zfs/zpios/zpios.ko needs unknown symbol dmu_tx_create
WARNING: /lib/modules/2.6.32-696.el6.x86_64/weak-updates/zfs/zpios/zpios.ko needs unknown symbol dmu_object_alloc
WARNING: /lib/modules/2.6.32-696.el6.x86_64/weak-updates/zfs/zpios/zpios.ko needs unknown symbol dmu_object_free
WARNING: /lib/modules/2.6.32-696.el6.x86_64/weak-updates/zfs/zpios/zpios.ko needs unknown symbol dmu_objset_own
WARNING: /lib/modules/2.6.32-696.el6.x86_64/weak-updates/zfs/zpios/zpios.ko needs unknown symbol dsl_destroy_head
WARNING: /lib/modules/2.6.32-696.el6.x86_64/weak-updates/zfs/zpios/zpios.ko needs unknown symbol dmu_write
WARNING: /lib/modules/2.6.32-696.el6.x86_64/weak-updates/zfs/zpios/zpios.ko needs unknown symbol dmu_objset_disown
WARNING: /lib/modules/2.6.32-696.el6.x86_64/weak-updates/zfs/zpios/zpios.ko needs unknown symbol dmu_tx_commit
WARNING: /lib/modules/2.6.32-696.el6.x86_64/weak-updates/zfs/zpios/zpios.ko needs unknown symbol dmu_tx_wait
WARNING: /lib/modules/2.6.32-696.el6.x86_64/weak-updates/zfs/zpios/zpios.ko needs unknown symbol dmu_tx_abort
WARNING: /lib/modules/2.6.32-696.el6.x86_64/weak-updates/zfs/zpios/zpios.ko needs unknown symbol dmu_object_set_blocksize
WARNING: /lib/modules/2.6.32-696.el6.x86_64/weak-updates/zfs/zpios/zpios.ko needs unknown symbol dmu_objset_create
WARNING: /lib/modules/2.6.32-696.el6.x86_64/weak-updates/zfs/zpios/zpios.ko needs unknown symbol dmu_tx_hold_free
```

**Comment by behlendorf** [comment]
Can you include the output from `dmesg` which should show why the zfs module could not be loaded.

**Comment by dmaziuk** [comment]
Yes but I don't see anything in there. In the current ```dmesg```:
```
microcode: CPU47: patch_level=0x6000822
Microcode Update Driver: v2.00 <tigran@aivazian.fsnet.co.uk>, Peter Oruba
zunicode: module license 'CDDL' taints kernel.
Disabling lock debugging due to kernel taint
SPL: Loaded module v0.6.5.8-1
ZFS: Loaded module v0.6.5.8-1, ZFS pool version 5000, ZFS filesystem version 5
Adding 65535996k swap on /dev/sdc1.  Priority:-1 extents:1 across:65535996k
<EOF>
```

In ```dmesg.old``` :
```microcode: CPU47: patch_level=0x6000822
Microcode Update Driver: v2.00 <tigran@aivazian.fsnet.co.uk>, Peter Oruba
Adding 65535996k swap on /dev/sdc1.  Priority:-1 extents:1 across:65535996k
<EOF>
```

That's the only occurrence of zfs, and ```/var/log/messages``` is similarly useless. The warnings above are the only relevant stuff I have.

**Comment by dmaziuk** [comment]
PS, note that ```2.6.32-696``` that's missing symbols is the new kernel

**Comment by behlendorf** [comment]
This doesn't look like issue with the Redhat kernel since those are all symbols provided by zfs.ko and they're only impacting zpios.ko which is only used for testing purposes.  Plus zfs.ko was loaded for your running kernel so you should be good to go.  If possible I'd suggest removing all the spl/zfs packages, then any lingering modules which didn't get removed, and reinstalling.  Directions are available on the [wiki](https://github.com/zfsonlinux/zfs/wiki/RHEL-%26-CentOS#switching-from-dkms-to-kabi-tracking-kmod).

**Comment by dmaziuk** [comment]
Nope. 

1. Do a 6.9 update
2. Remove ZFS incl. ```find /lib/modules ...```
3. Reboot
4. Install ZFS
5. Reboot
Still no ZFS:
```
# modprobe zfs
FATAL: Module zfs not found.
```

**Comment by truatpasteurdotfr** [comment]
- 2.6.32-696.el6.x86_64 is from 6.8/cr (pre 6.9 release).
- confirmed here too (6.8 + latest kernel from 6.8/updates) + kmod-zfs : ok (fresh kickstart with minimal installation)
- yum install http://download.zfsonlinux.org/epel/zfs-release.el6.noarch.rpm
- yum install  kmod-zfs-2.6.32-642.15.1.el6.x86_64
- insmod zfs && zpool list
Then
- yum -y install centos-release-cr
- yum -y --enablerepo=cr update 
- reboot under the newly installed kernel
-> no more zfs (weak-update silently fails)
```
 /sbin/weak-modules --verbose --add-kernel 2.6.32-696.el6.x86_64 
Module zfs.ko from kernel 2.6.32-642.15.1.el6.x86_64 is not compatible   with kernel 2.6.32-696.el6.x86_64 in symbols: posix_acl_equiv_mode
```

**Comment by truatpasteurdotfr** [comment]
rebuilding the kmod-zfs|zpl with kernel-devel-2.6.32-696.el6.x86_64 yields a working zfs setup.

**Comment by behlendorf** [comment]
@truatpasteurdotfr thanks for the additional debugging to identify the system which was changed.  We'll look in to what can be done.

**Comment by dmaziuk** [comment]
Just FYI: centos release 6.9 is official so users who aren't tracking "continuous release" repo will be installing the new kernel now.

**Comment by sbonds** [comment]
Yeah, like me! A workaround for people who came here because their ZFS using kmod on CentOS 6.9 stock kernels stopped working is to change /boot/grub/grub.conf with "default=1" instead of "default=0" to boot to the prior kernel until this gets fixed for real.

**Comment by cousins** [comment]
Should this be resolved now? @dmaziuk mentioned that 6.9 is official now. So should the kmod-zfs be updated? Currently it looks like kmod-zfs kmod-spl are still on the 642 kernel:

```
[root@nfs2 ~]# repoquery -ql kmod-zfs
/lib/modules/2.6.32-642.4.2.el6.x86_64
/lib/modules/2.6.32-642.4.2.el6.x86_64/extra
/lib/modules/2.6.32-642.4.2.el6.x86_64/extra/zfs
/lib/modules/2.6.32-642.4.2.el6.x86_64/extra/zfs/avl
/lib/modules/2.6.32-642.4.2.el6.x86_64/extra/zfs/avl/zavl.ko
/lib/modules/2.6.32-642.4.2.el6.x86_64/extra/zfs/nvpair
/lib/modules/2.6.32-642.4.2.el6.x86_64/extra/zfs/nvpair/znvpair.ko
/lib/modules/2.6.32-642.4.2.el6.x86_64/extra/zfs/unicode
/lib/modules/2.6.32-642.4.2.el6.x86_64/extra/zfs/unicode/zunicode.ko
/lib/modules/2.6.32-642.4.2.el6.x86_64/extra/zfs/zcommon
/lib/modules/2.6.32-642.4.2.el6.x86_64/extra/zfs/zcommon/zcommon.ko
/lib/modules/2.6.32-642.4.2.el6.x86_64/extra/zfs/zfs
/lib/modules/2.6.32-642.4.2.el6.x86_64/extra/zfs/zfs/zfs.ko
/lib/modules/2.6.32-642.4.2.el6.x86_64/extra/zfs/zpios
/lib/modules/2.6.32-642.4.2.el6.x86_64/extra/zfs/zpios/zpios.ko

[root@nfs2 ~]# repoquery -ql kmod-spl
/lib/modules/2.6.32-642.4.2.el6.x86_64
/lib/modules/2.6.32-642.4.2.el6.x86_64/extra
/lib/modules/2.6.32-642.4.2.el6.x86_64/extra/spl
/lib/modules/2.6.32-642.4.2.el6.x86_64/extra/spl/spl
/lib/modules/2.6.32-642.4.2.el6.x86_64/extra/spl/spl/spl.ko
/lib/modules/2.6.32-642.4.2.el6.x86_64/extra/spl/splat
/lib/modules/2.6.32-642.4.2.el6.x86_64/extra/spl/splat/splat.ko
```
Should I be checking with someone else? 

Thanks,

Steve

**Comment by truatpasteurdotfr** [comment]
I can just re-state that rebuilding from the provided sources on CentOS-6.9 new kernels yields working kernel modules.

just do something like:
```
(tar xzvf spl-0.6.5.9.tar.gz && cd spl-0.6.5.9 && ./configure  --with-linux=/lib/modules/${KERNEL}/source --with-linux-obj=/lib/modules/${KERNEL}/build && make rpm rpm-kmod rpm-utils )
install the kmod-spl-devel-${KERNEL}  kmod-spl-${KERNEL} rpms
(tar xzvf zfs-0.6.5.9.tar.gz && cd zfs-0.6.5.9 && ./configure  --with-linux=/lib/modules/${KERNEL}/source --with-linux-obj=/lib/modules/${KERNEL}/build/ --with-selinux  && make rpm rpm-kmod rpm-utils)
install the kmod-zfs-${KERNEL} rpm
```

with KERNEL=2.6.32-696.el6.x86_64 or 2.6.32-696.1.1.el6.x86_64

**Comment by cousins** [comment]
@truatpasteurdotfr : I see. So I guess this thread **is** different than the other one I started. I was specifically looking for a fix to the CentOS 6 kmod-spl and kmod-zfs packages in the ZFS yum repository. Thanks for helping clarify that (at least for me). 

BTW, in this case, the DKMS module worked fine to get me through until kmod in the zfs-repo catches up.

**Comment by behlendorf** [comment]
The CentOS 6 kmod and dkms repositories have been updated with spl/zfs-0.6.5.9 built against the `2.6.32-696` kernel.  Sorry about the delay.

**Comment by cousins** [comment]
Thanks @behlendorf !
