### ISSUE TITLE
Compile issue with the latest branch to add TRIM support

### ISSUE THREAD

**Issue by fcrg** [zfsonlinux/zfs#5937]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | gentoo
Distribution Version    | 
Linux Kernel                 | 4.7.10
Architecture                 | x86_64
ZFS Version                  |  PR 5925 ; dweeezil:ntrim2
SPL Version                  | spl-0.7.0-rc3

### Describe the problem you're observing
Compile issue with the latest branch to add TRIM support

### Describe how to reproduce the problem
compile with -Werror=implicit-function-declaration

### Include any warning/errors/backtraces from the system logs
fs/zfs/zfs/metaslab.c: In function 'metaslab_auto_trim':
fs/zfs/zfs/metaslab.c:3835:6: error: implicit declaration of function 'trace_zfs_preserve__spilled' [-Werror=implicit-function-declaration]
      DTRACE_PROBE1(preserve__spilled,
      ^
fs/zfs/zfs/metaslab.c:3842:6: error: implicit declaration of function 'trace_zfs_drop__spilled' [-Werror=implicit-function-declaration]
      DTRACE_PROBE1(drop__spilled
      
fs/zfs/zfs/vdev.c: In function 'vdev_auto_trim':
fs/zfs/zfs/vdev.c:3830:2: error: implicit declaration of function 'trace_zfs_autotrim__mem__lim' [-Werror=implicit-function-declaration]
  DTRACE_PROBE3(autotrim__mem__lim, vdev_t *, vd, uint64_t, mused,

**Comment by behlendorf** [comment]
This issue is related to the work going on in #5925 and should be reported there.  @dweeezil I'm closing this issue and referencing #5925 so it can be resolved in that patch stack.
