### ISSUE TITLE
ZFS On Linux wiki content: no license specified

### ISSUE THREAD

**Issue by sampablokuper** [zfsonlinux/zfs#5958]
The ZFS on Linux codebase is maintained at https://github.com/zfsonlinux/zfs.git . That repository's contents [provide](https://github.com/zfsonlinux/zfs/blob/master/COPYRIGHT) [clarity](https://github.com/zfsonlinux/zfs/blob/master/OPENSOLARIS.LICENSE) about the licensing of the files in that repository. So far, so good!

However, the [ZFS on Linux wiki](https://github.com/zfsonlinux/zfs/wiki) is maintained in a separate repository: https://github.com/zfsonlinux/zfs.wiki.git . None of the files in this repository specify how they are licensed.

Please can ZFS on Linux clarify the licensing status of the files in the ZFS on Linux wiki repository, to enable them to be collaboratively edited by people who do not already hold copyright in them? (Ideally, they would be licensed as [CC BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/), to ensure compatibility with prominent wikis/websites such as Wikipedia and the Stack Exchange network.)

**Comment by ryao** [comment]
The CC BY-SA 3.0 is the same license that both the Gentoo wiki and the OpenZFS wiki use. We just need all contributors to sign off on it.

@behlendorf @nedbass @tonyhutter @dweeezil @FransUrbo @rincebrain @ofaaland @kernelOfTruth @jgoldschrafe @thegreatgazoo @dinatale2 @gmelikov @don-brady @davromaniak @dpquigl 

Would all of you guys sign off on placing the entire wiki under the same license as the OpenZFS wiki?

https://creativecommons.org/licenses/by-sa/3.0/

**Comment by gmelikov** [comment]
I think we can resolve it here. @gmelikov, @rlaager, @dajhorn, @kpande and @kernelOfTruth have already agreed with licensing in #5960.

**Comment by sampablokuper** [comment]
@gmelikov wrote:
> I think we can resolve it here. @gmelikov, @rlaager, @dajhorn, @kpande and @kernelOfTruth have already agreed with licensing in #5960.

#5960 was only about the [Debian Jessie Root on ZFS](https://github.com/zfsonlinux/zfs/wiki/Debian-Jessie-Root-on-ZFS) page, not about any other content in the wiki.

**Comment by kernelOfTruth** [comment]
oh well, @gmelikov , @sampablokuper  agreed - my okay was referring to any wiki related contribution

**Comment by rlaager** [comment]
It sounds like the following are left?
@nedbass
@tonyhutter
@dweeezil
@FransUrbo
@rincebrain
@ofaaland
@jgoldschrafe
@thegreatgazoo
@dinatale2
@don-brady
@davromaniak
@dpquigl

**Comment by tonyhutter** [comment]
It''s ok with me.  I don't even remember editing the wiki :-)

**Comment by dweeezil** [comment]
Ok with me too.

**Comment by jgoldschrafe** [comment]
I stuck my +1 on yesterday.

**Comment by rincebrain** [comment]
Go for it.

**Comment by davromaniak** [comment]
Hi.

No issue for me, you can go for it.

Thanks.

**Comment by behlendorf** [comment]
Yup, sounds good.

**Comment by dinatale2** [comment]
Ok with me.

**Comment by nedbass** [comment]
I agree.

**Comment by dpquigl** [comment]
I agree with the change.

**Comment by don-brady** [comment]
Fine by me

**Comment by gmelikov** [comment]
I agree too.

**Comment by thegreatgazoo** [comment]
Agree

**Comment by ofaaland** [comment]
OK with me

**Comment by sampablokuper** [comment]
@FransUrbo , is this OK with you?

**Comment by FransUrbo** [comment]
Yes, I'm all good with this.

**Comment by gmelikov** [comment]
Thanks, looks like everyone agrees.

**Comment by behlendorf** [comment]
Thanks everybody.  I've added a [License page](https://github.com/zfsonlinux/zfs/wiki/License) to the wiki git repository and referenced it from the footer.
