### ISSUE TITLE
Permission to extend wiki documentation

### ISSUE THREAD

**Issue by sampablokuper** [zfsonlinux/zfs#5960]
The [Debian Jessie Root on ZFS](https://github.com/zfsonlinux/zfs/wiki/Debian-Jessie-Root-on-ZFS) page says:

> If you have bugs or feature requests related to this HOWTO, please file a new issue and mention @gmelikov and @rlaager.

So, @gmelikov and @rlaager , as the authors of that HOWTO, please can you give me permission to adapt it for Debian Stretch, and to publish that adaptation? (Ideally, please license it under CC BY-SA 3.0, as per #5958 .)

Thanks!

**Comment by gmelikov** [comment]
You can send a patch here. IIRC Stretch install is identical,  you just don't need to install grub from testing repositories. We will update it just after Stretch stable release.

**Comment by sampablokuper** [comment]
@gmelikov, thanks for your permission to publish a patch :) @rlaager, are you also OK with me doing that?

My aim is both to update it for Stretch, and also to make the HOWTO a bit more comprehensible for novices/intermediates. Working on a draft. Will follow up if I get it to the point where it is workable. I would post it already, except for needing permission from you both due to #5958.

**Comment by rlaager** [comment]
I'm fine with a CC-BY-SA 3.0 license, though I'd probably prefer something even more permissive, or at least "CC-BY-SA 4.0 with Creative Commons as a license proxy". But I'm not the only copyright holder. You'd definitely need to check with @dajhorn too, and possibly others.

Maybe @behlendorf could weigh in on the issue of licensing for the wiki in general?

**Comment by behlendorf** [comment]
I'd like to opt for something permissive too.  The CC-BY-SA 4.0 license seems like a reasonable choice but we'll need to get the approval of everyone who's contributed.  That list is still fairly short.

```
git shortlog -e -s
   220  Brian Behlendorf <behlendorf1@llnl.gov>
     2  David Quigley <dpquigl@users.noreply.github.com>
     1  Don Brady <don.brady@intel.com>
    34  George Melikov <mail@gmelikov.ru>
     9  Giuseppe Di Natale <dinatale2@users.noreply.github.com>
    12  Isaac Huang <he.huang@intel.com>
     2  Olaf Faaland <faaland1@llnl.gov>
     1  Rich Ercolani <rincebrain@gmail.com>
    51  Richard Laager <rlaager@wiktel.com>
     1  Tim Chase <tim@chase2k.com>
     1  Tony Hutter <hutter2@llnl.gov>
    19  Turbo Fredriksson <turbo@bayour.com>
    51  behlendorf <behlendorf1@llnl.gov>
     3  davromaniak <cyril.lavier@gmail.com>
     1  jgoldschrafe <jeff@holyhandgrenade.org>
    36  kernelOfTruth aka. kOT, Gentoo user <kerneloftruth@gmail.com>
```

**Comment by dajhorn** [comment]
@rlaager, @behlendorf ,

Any of my ZoL contributions may be relicensed.

HTH.

**Comment by kpande** [comment]
do whatever you want with my contributions

**Comment by gmelikov** [comment]
Do whatever you want with my contributions too.

**Comment by kernelOfTruth** [comment]
Works for me, just do what you want with the contributions :)

**Comment by sampablokuper** [comment]
@rlaager [wrote](https://github.com/zfsonlinux/zfs/issues/5960#issuecomment-291249575):
> I'm fine with a CC-BY-SA 3.0 license, though I'd probably prefer something even more permissive, or at least "CC-BY-SA 4.0 with Creative Commons as a license proxy".

Thanks :) Sorry for my delay in replying.

> But I'm not the only copyright holder. You'd definitely need to check with @dajhorn too, and possibly others.

As far as I can tell, only you and @gmelikov contributed to the [Debian Jessie Root on ZFS](https://github.com/zfsonlinux/zfs/wiki/Debian-Jessie-Root-on-ZFS) HOWTO and to the Ubuntu 16.04 Root on ZFS HOWTO from which it was forked:

```
$ git shortlog -s Debian-Jessie-Root-on-ZFS.md
     2  George Melikov
     3  Richard Laager
$ git shortlog -s Ubuntu-16.04-Root-on-ZFS.md
    33  Richard Laager
```

If I am mistaken and there were other contributors to [Debian Jessie Root on ZFS](https://github.com/zfsonlinux/zfs/wiki/Debian-Jessie-Root-on-ZFS), please point me to the relevant Git commits so that I can be sure I would not be using anyone's work in breach of copyright.

> Maybe @behlendorf could weigh in on the issue of licensing for the wiki in general?

That discussion would be welcome. It is *out of scope for **this** bug report*, which was [specifically](https://github.com/zfsonlinux/zfs/issues/5960#issue-218939684) opened to request permission to extend the [Debian Jessie Root on ZFS](https://github.com/zfsonlinux/zfs/wiki/Debian-Jessie-Root-on-ZFS) HOWTO, but it is *in scope for #5958*, so please let's handle it at the latter.

**Comment by sampablokuper** [comment]
@gmelikov [wrote](https://github.com/zfsonlinux/zfs/issues/5960#issuecomment-291416602):
> Do whatever you want with my contributions too.

Great. Thanks!

**Comment by sampablokuper** [comment]
@behlendorf [wrote]():
> I'd like to opt for something permissive too. The CC-BY-SA 4.0 license seems like a reasonable choice but we'll need to get the approval of everyone who's contributed. That list is still fairly short.
>
> ```
>    git shortlog -e -s
>    220  Brian Behlendorf <behlendorf1@llnl.gov>
>    2  David Quigley <dpquigl@users.noreply.github.com>
>    1  Don Brady <don.brady@intel.com>
>    34  George Melikov <mail@gmelikov.ru>
>    9  Giuseppe Di Natale <dinatale2@users.noreply.github.com>
>    12  Isaac Huang <he.huang@intel.com>
>    2  Olaf Faaland <faaland1@llnl.gov>
>    1  Rich Ercolani <rincebrain@gmail.com>
>    51  Richard Laager <rlaager@wiktel.com>
>    1  Tim Chase <tim@chase2k.com>
>    1  Tony Hutter <hutter2@llnl.gov>
>    19  Turbo Fredriksson <turbo@bayour.com>
>    51  behlendorf <behlendorf1@llnl.gov>
>    3  davromaniak <cyril.lavier@gmail.com>
>    1  jgoldschrafe <jeff@holyhandgrenade.org>
>    36  kernelOfTruth aka. kOT, Gentoo user <kerneloftruth@gmail.com>
> ```

I think you are referring to the **ZFS on Linux** wiki as a whole, which is [beyond the scope](https://github.com/zfsonlinux/zfs/issues/5960#issuecomment-295769090) of this bug report. Please see #5958 instead. Thanks!

**Comment by sampablokuper** [comment]
@dajhorn wrote:
> `@rlaager`, `@behlendorf `,
> Any of my ZoL contributions may be relicensed.

@kpande wrote:
> do whatever you want with my contributions

@kernelOfTruth wrote:
> Works for me, just do what you want with the contributions :)

Thanks, but do any of you three contributors hold copyright in the [Debian Jessie Root on ZFS](https://github.com/zfsonlinux/zfs/wiki/Debian-Jessie-Root-on-ZFS) HOWTO?

If not, and your comments are referring to other contributions to the ZFS on Linux wiki, then this is the wrong bug report. Please post at #5958 instead. Thanks!
