### ISSUE TITLE
Debian Installation on Wiki Mountpoint Error

### ISSUE THREAD

**Issue by rschulman** [zfsonlinux/zfs#5969]
In following the wiki instructions for installing zfs on Debian Jessie, I reached section 3.2 and ran `zfs mount rpool/ROOT/debian` and am told that it cannot mount `/` because the directory isn't empty. I believe I've followed instructions correctly, and indeed the prior instruction, `zfs create -o canmount=noauto -o mountpoint=/ rpool/ROOT/debian` specifies that mount point.

Am I being dense or something? Thanks.

cc @gmelikov @rlaager

**Comment by gmelikov** [comment]
In section 2.3 you created pool with `-R /mnt`, so `zfs mount rpool/ROOT/debian` should mount to `/mnt`. If you made any other changes (export/import pool, etc), then you will have such an error.

Please use mailing lists next time.

**Comment by rlaager** [comment]
@gmelikov I changed the HOWTOs to mention the mailing list and IRC for support.
