### ISSUE TITLE
ZFS kernel driver can start an unwanted resilver that will never complete 

### ISSUE THREAD

**Issue by jsalinasintel** [zfsonlinux/zfs#5970]
Version Information 
=================================================================
Distribution Name       Centos 7.2  
Distribution Version     7.2 
Linux Kernel                3.10.0-327.36.3.el7.x86_64
Architecture                 x86_64
ZFS Version                0.7.0-rc3
SPL Version                0.7.0-rc3  

Problem 
=================================================================
Testing dRAID we noticed that sometimes before a rebuild would start a scrub or resilver would start first.  We stopped zed and these still happen.  This same behavior happens on raidz as well.  Sometimes it will be a scrub, sometimes a resilver.  

Reproduce
=================================================================  
zinject -d $DISK -e io -T write||ALL tank 
write to pool tank 

Log detail 
=================================================================
Inject IO error and after the error count is high enough 

On IO error, ZFS tries to probe the vdev to see if it's still in good shape: zio_vdev_io_done() -> vdev_probe()
The probe will call into vdev_open(), which will start a resilver since the vdev's DTL_MISSING is not empty
The resilver will cause more IO errors on the vdev, then it'd essentially go back to step 1 and repeat forever
On 9-drive raidz1 pool (only 423M used) has been repeated resilvering over 10 hours now:
scan: resilver in progress since Mon Apr  3 21:20:19 2017
scan: resilver in progress since Mon Apr  3 21:31:28 2017
scan: resilver in progress since Mon Apr  3 21:33:17 2017 

It does not appear this will ever complete, but will constantly be restarting from the beginning.   

In other cases it is possible to see a scrub and then resilver: 
02:39:20.049995627 resource.fs.zfs.statechange: sdg became FAULTED
02:39:20.242995864 sysevent.fs.zfs.scrub_start: scrub started
02:39:21.141996971 sysevent.fs.zfs.scrub_finish: scrub completed
02:39:21.788997768 sysevent.fs.zfs.vdev_spare: spare was used to replace FAULTED drive, then:
02:39:22.524998673 sysevent.fs.zfs.resilver_start
02:39:23.825000272 sysevent.fs.zfs.resilver_finish
 
Another question from this is should this functionality all be handled by zed now?

**Comment by behlendorf** [comment]
@jsalinasintel proposed fix in #5971 for review.  With the fix applied ZFS will correctly fault the device as a result of the simulated IO errors.

> Another question from this is should this functionality all be handled by zed now?

Yes and no.  ZFS should internally be responsible for faulting the device under certain circumstances such as when the device is completely inaccessible.

**Comment by kpande** [comment]
this should have been resolved with #5971
