### ISSUE TITLE
Kernel 4.10 compat?

### ISSUE THREAD

**Issue by MarkGavalda** [zfsonlinux/zfs#5972]
v0.6.5.9 release contains https://github.com/zfsonlinux/zfs/commit/a5e046eaacad20487188c9eef231554e1401d8c9 ( Linux 4.10 compat ) yet it's not listed under supported kernels:
```
Supported Kernels
Compatible with 2.6.32 - 4.9 Linux kernels.
```
Was that not updated by accident or isn't v0.6.5.9 compatible with kernels 4.10+ ?

**Comment by behlendorf** [comment]
An oversight, I've updated the documentation.  Thanks.
