### ISSUE TITLE
SATA trim for vdev members

### ISSUE THREAD

**Issue by GregorKopka** [zfsonlinux/zfs#598]
ZoL should issue SATA TRIM commands to the underlying block devices when blocks are freed.

For CACHE devices (unless persistend L2ARC may be implemented at some point in the future): on cache device activation (and deactivation, like zpool remove <cachedevice>) a TRIM command should free the whole space (minus needed persistent superblocks) available on such devices .

Only then SSDs will be hinted of unused blocks so their wear-leveling algorithms can function as intended.

**Comment by dweeezil** [comment]
I figure I'm far enough along to mention I'm working on porting Nextenta's TRIM support.  It uses a rather different approach than the the one described earlier in this issue.  My plan is to try to get disk and file vdevs working first and then deal with zvols.  It's a good ways off yet but so far is looking good.  I'll post more information to this particular issue as it becomes available.

**Comment by dechamps** [comment]
What do you mean by "deal with zvols"? Discards are already implemented for zvols and have been working for years now - see #334, #384, #1010. Discard on zvol is a frontend feature, which is very different from discard on vdevs, which is a backend feature.

**Comment by richardelling** [comment]
> On Jul 24, 2015, at 1:46 PM, Tim Chase <notifications@github.com> wrote:
> 
> I figure I'm far enough along to mention I'm working on porting Nextenta's TRIM support. It uses a rather different approach than the the one described earlier in this issue. My plan is to try to get disk and file vdevs working first and then deal with zvols.
> 

This makes no sense. Surely you mean initiating TRIM/UNMAP for vdevs?  
That is totally different than zvols, as that work is already done.
 -- richard

**Comment by dweeezil** [comment]
Let me clarify the part regarding zvols: I want to evaluate whether to try replacing the existing zvol discard code with that from Nexenta. The particular use case for which I was asked to do this work is for file vdevs so I figured on porting the code and testing with file and disk vdevs first and then look at the zvol situation later.

**Comment by dweeezil** [comment]
This appears to be coming together rather nicely and, so far, vdev file trimming (via hole-punching) appears to be working properly and, as expected, the existing zvol code works just fine (tested with a "discard"-mounted ext4 atop a zvol).  I've not dealt with vdev disks yet but am instead running a bunch of stress tests with vdev file-based pools to make sure nothing has broken.

I'll also be porting Nexenta's on-demand trim feature.

The WIP spl code is in https://github.com/dweeezil/spl/tree/ntrim and the WIP zfs code is in https://github.com/dweeezil/zfs/tree/ntrim.

**Comment by richardelling** [comment]
> On Jul 26, 2015, at 8:23 AM, Tim Chase <notifications@github.com> wrote:
> 
> This appears to be coming together rather nicely and, so far, vdev file trimming (via hole-punching) appears to be working properly and, as expected, the existing zvol code works just fine (tested with a "discard"-mounted ext4 atop a zvol). I've not dealt with vdev disks yet but am instead running a bunch of stress tests with vdev file-based pools to make sure nothing has broken.
> 
> 

sigh, so many ZFS ports, so little time :-)
I had not realized that the ZoL code is so far behind illumos in this regard.
Yes, absolutely agree with what you are proposing.

FWIW, Solaris 11 has had vdev-level UNMAP/TRIM for years. By default it is disabled.
Given the large variance in drive and array performance during UNMAP/TRIM, it is
clear that default=enabled is not a good idea. Perhaps some day the drive vendors will
get it right... 
 -- richard

**Comment by tomposmiko** [comment]
Out of curiosity will be there available an fstrim like (offline) solution?

**Comment by dweeezil** [comment]
The patch set seems to be working at this point.  Please see #3656.

@tomposmiko With the on-demand trim feature, ```zpool trim <pool>``` does the same thing, however, I'm going to look into adding support for the Linux standard FITRIM ioctl which would allow ```fstrim``` to work properly.

**Comment by dweeezil** [comment]
@tomposmiko I had forgotten how weird FITRIM is.  Among other things, it targets a single filesystem which in ZFS really isn't possible since space allocation is a pool attribute.  I think ```zpool trim``` ought to suffice.

**Comment by Bronek** [comment]
@dweeezil theoretically you could perform reverse lookup from filesystem to pool(s) and the perform "zpool trim" on a result ...

**Comment by CMCDragonkai** [comment]
Would this work on ZFS over LUKs? We would need to enable the discard for the LUKs of course, but what else would be needed?

**Comment by dasJ** [comment]
@CMCDragonkai I currently run ZFS on LUKS and I just had to open the volume with `--allow-discards`. I set `autotrim=on` on the pool for automatic trimming.

**Comment by UralZima** [comment]
Hi. Can anyone provide some instructions, how to run TRIM version of ZFS in Gentoo? I urgently need it, my SSD is failing. Is it possible to add patches to portage or modify ebuild file? 
@dasJ, how you running it? Maybe @dweeezil, you can help? 
Thank you very much.
P.S. I already posted a question on another thread (nexenta), not sure if someone will answer soon

**Comment by drescherjm** [comment]
> I urgently need it, my SSD is failing. 

I don't believe TRIM will help fix a failing SSD.

**Comment by awnz** [comment]
If your SSD is failing, as @drescherjm said, TRIM won't help. What you want to do, and urgently is:
1) Stop writing anything to that SSD.
2) Copy everything off it immediately to safer storage. Start with the most important data first.
3) Replace the SSD with a new one.

Hopefully you are using RAID and backups.

Since this Github issue is for the ZFS TRIM feature and not for support, if you need any volunteer assistance with this, talk to me on Twitter at @aw_nz (https://twitter.com/aw_nz)

**Comment by UralZima** [comment]
Thanks for answers. I understood you, but anyway, I have heavy DB running on it, I don't want to trash newly bought SSD again. Of course I have backups/snaphots. I just want to enable/test TRIM on ZFS
@awnz, Thanks for your offer to help. I don't have a twitter, let's talk in this web chat room: 
https://tlk.io/trimzfs  anyone who interested, please join. 

I think these instructions will help another testers/devs to test trim feature, so it can be on-topic here. 
Is it enought to git clone ntrim branch of spl, ./configure && make && make install and do the same for zfs with ntrim-next branch? it will generate .ko files, and I need to move them to initramfs? or some cleaner way exists for gentoo? 

Thank you very much.

**Comment by cwedgwood** [comment]
@behlendorf, @dweeezil; close (duplicate) because it's been superseded by #5925 ?

**Comment by mailinglists35** [comment]
Is pull request #8419 the final one that will actually fix this issue? (I don't understand why was closed last year)

**Comment by behlendorf** [comment]
@mailinglists35 yes,  #8419 is the final version.  This is was closed as a duplicate of a previous version of TRIM.
