### ISSUE TITLE
Hidden memory

### ISSUE THREAD

**Issue by Lisio** [zfsonlinux/zfs#6005]
### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Ubuntu
Distribution Version    | 16.04
Linux Kernel                 | 4.4.52
Architecture                 | amd64
ZFS Version                  | 0.6.5.6
SPL Version                  | 0.6.5.6

```
$ apt --installed list | grep zfs

libzfs2linux/xenial-updates,now 0.6.5.6-0ubuntu16 amd64 [installed,automatic]
zfs-dkms/xenial-updates,now 0.6.5.6-0ubuntu16 amd64 [installed,automatic]
zfs-doc/xenial-updates,xenial-updates,now 0.6.5.6-0ubuntu16 all [installed,automatic]
zfs-zed/xenial-updates,now 0.6.5.6-0ubuntu16 amd64 [installed,automatic]
zfsutils-linux/xenial-updates,now 0.6.5.6-0ubuntu16 amd64 [installed]
```

### Describe the problem you're observing
When I don't do anything with files on server the memory usage looks like this:
```
$ free -h
              total        used        free      shared  buff/cache   available
Mem:            31G         12G         18G        123M        476M         18G
Swap:          9.0G        398M        8.6G
```
If I start using filesystem actively (read big file, e.t.c.) in a couple of minutes the memory disappears:
```
$ free -h
              total        used        free      shared  buff/cache   available
Mem:            31G         27G        2.7G        123M        957M        3.1G
Swap:          9.0G        398M        8.6G
```
```
$ vmstat -s
     32914100 K total memory
     29147896 K used memory
     11605052 K active memory
       785336 K inactive memory
      2756436 K free memory
         7180 K buffer memory
      1002588 K swap cache
      9435124 K total swap
       408444 K used swap
      9026680 K free swap
```

15G of RAM simply disappeared. There are no processes that use it, and it is not used for buffers or cache.
```
$ ps aux | awk '{print $6}' | tail -n +2 | paste -sd+ | bc
13350252
```

I suppose this memory is used by zfs kernel module as a filesystem cache, but I don't understand why it becomes invisible to the system. The side effect of such behavior is that OS can't free it when needed. For example, mongodb instance in lxc container (I use LXD 2.12 with ZFS as backing store) receives constant checksum errors while reading data and crashes. Several hours ago I even couldn't start db because of this checksum errors and the only thing that helped me is this simple line:
```
sync && echo 3 > /proc/sys/vm/drop_caches
```

**Comment by kpande** [comment]
you are using a very old version of ZFS, and this type of request is better suited to [the mailing list](http://list.zfsonlinux.org)

**Comment by jwittlincohen** [comment]
@Lisio By default ZFS can use up to 50% of main memory for the ARC cache.  To see ARC stats including the amount of memory used use "sudo arc_summary".  You can also monitor ARC hits with "sudo arcstat."  arcstat reports. 

Excerpted arc_summary output:

`ARC Size:                               67.60%  16.22   GiB
        Target Size: (Adaptive)         67.62%  16.23   GiB
        Min Size (Hard Limit):          0.13%   32.00   MiB
        Max Size (High Water):          768:1   24.00   GiB
`
Arcstat output:

`    time  read  miss  miss%  dmis  dm%  pmis  pm%  mmis  mm%  arcsz     c
23:13:00     0     0      0     0    0     0    0     0    0    16G   16G
`

**Comment by Lisio** [comment]
@kpande Sadly, this is the newest version in repos for the latest LTS release of Ubuntu.
@jwittlincohen Thank you for the clarification. Now I have to understand why it causes troubles with lxc containers. They definitely crash when trying to get memory which arc cache doesn't want to free.

**Comment by jwittlincohen** [comment]
@Lisio. The method used in 0.6.5.x and earlier for ARC can be slow to release memory, resulting in kernel panics.  That is why the max ARC size is limited to 50%.  You can also manually set this by doing the following:

echo X > /sys/module/zfs/parameters/zfs_arc_max

X would be the maximum ARC size in bytes.

**Comment by jwittlincohen** [comment]
Your other option is to use the 0.7.0, which is currently in testing (RC) status.  0.7.0 has improved memory management due to ABD, and may resolve your issues.
