### ISSUE TITLE
attempting to remove mirrored slog device(s) results in misleading error message

### ISSUE THREAD

**Issue by kpande** [zfsonlinux/zfs#6008]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | CentOS
Distribution Version    | 6.x
Linux Kernel                 | 4.4.60
Architecture                 | x86_64
ZFS Version                  | 0.6.5-stable
SPL Version                  | 0.6.5-stable

### Describe the problem you're observing

When I want to detach mirrored SLOG devices, the error is inappropriate:

```
# zpool remove tank scsi-360022480c662b662c4c6fd14fe99a6d0
cannot remove scsi-360022480c662b662c4c6fd14fe99a6d0: operation not supported on this type of pool
```

The pool is a stripe-only geometry with two disks in mirrored log vdev. However, the error is actually because of the *slog vdev type* though it says it's about the *pool type*.

### Workaround

```
# zpool detach tank <disk> # < detach one of the SLOG devices
# zpool remove tank <disk2> # < remove the other SLOG device
```
Other sources tell me to use "zpool remove tank mirror-2" where *mirror-2* is the SLOG vdev.

**Comment by DeHackEd** [comment]
That is technically correct. You can't remove a disk from a mirror. You either detach it from the mirror or remove the whole log vdev (which is `mirror-X`) as you said.

**Comment by kpande** [comment]
but the pool is a stripe, and the error could be more informative to tell me what is _actually_ going on without making me guess and try a bunch of other commands.

**Comment by kpande** [comment]
the operation is not supported message makes it seem like I can't remove log vdev from this pool.

**Comment by GregorKopka** [comment]
Given that detach is only good to _remove_ a disk of a mirror I wonder if it wouldn't be better (in terms of less confusion for users) to enable remove to also do the job of detach and stop mentioning detach in the man page (or state there that it's unneeded as remove does this too).

Or is that a cruft that has to, similar to zfs rollback -r, be kept till the heath death of the universe as someone _might_ rely on design errors made years ago?

**Comment by DeHackEd** [comment]
More like to enforce certain behaviours. You `detach` mirrors because if you want to make a mirror wider you use `attach`. Using `zpool remove` to break apart a mirror might accidentally make users think that using `zpool add` does the opposite and OH SHI-

**Comment by kpande** [comment]
fwiw, this still occurs on 0.8. I can at least open a PR to fix the man page so that this is documented,

**Comment by DanielSmedegaardBuus** [comment]
I get the same error with an SLOG device that is *not* a mirror. 

0.8.0 (RC4) on Ubuntu Server 19.04. 

Have a pool exported from another system, where a log device was used. I cannot remove the now non-existent log device from the pool:

```
daniel@titanic ~ sudo zpool remove titanic 3470644392946588961
cannot remove 3470644392946588961: Mount encrypted datasets to replay logs.
```

This is with everything mounted. Tried replacing the log device in an attempt to then be able to remove it. This triggers a resilver for some reason. Trying to remove the replaced device,

```
daniel@titanic ~ sudo zpool remove titanic /dev/disk/by-partlabel/slog
cannot remove /dev/disk/by-partlabel/slog: operation not supported on this type of pool
```

Detach?

```
daniel@titanic ~ sudo zpool detach titanic /dev/disk/by-partlabel/slog
cannot detach /dev/disk/by-partlabel/slog: no valid replicas
```

Each part very confusing. What to do? :D
