### ISSUE TITLE
Configure failed when cross build in user mode

### ISSUE THREAD

**Issue by wangdbang** [zfsonlinux/zfs#6010]
Trunk code Configure failed with cross build in user mode, reported "*** zlib.h missing, zlib-devel package required".

**Comment by wangdbang** [comment]
0.7.0 rc3 has the same issue.

**Comment by loli10K** [comment]
This issue is missing a lot of the required information (https://github.com/zfsonlinux/zfs/blob/master/.github/ISSUE_TEMPLATE.md), closing.
