### ISSUE TITLE
Stripe-only pool says ONLINE when faulted

### ISSUE THREAD

**Issue by kpande** [zfsonlinux/zfs#6012]
I've searched the issue reports for similar problems but haven't found any. I am aware of an issue with single-disk vdev pools going down hard instead of gracefully, and @dweeezil was looking into that.

### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | CentOS
Distribution Version    | 6.x
Linux Kernel                 | 4.4.60
Architecture                 | x86_64
ZFS Version                  | 0.6.5-stable
SPL Version                  | 0.6.5-stable

### Describe the problem you're observing
I have a pool made up of 10 vdevs that are each a single FUSE device. If I create a stripe-only pool with these vdevs, and then purposely kill one of the FUSE processes, I expect the pool to go to OFFLINE / DEGRADED (for RAID-1 pool) but neither occurs.

`zpool status` does know that the status is not good.

```
# zpool status
  pool: t1
 state: ONLINE
status: One or more devices are faulted in response to IO failures.
action: Make sure the affected devices are connected, then run 'zpool clear'.
   see: http://zfsonlinux.org/msg/ZFS-8000-HC
  scan: none requested
  trim: none requested
config:

	NAME         STATE     READ WRITE CKSUM
	t1           ONLINE       0     1     0
	  3  ONLINE       0     0     0
	  4  ONLINE       0     0     0
	  5  ONLINE       0     0     0
	  6  ONLINE       0     0     0
	  7  ONLINE       0     0     0
	  8  ONLINE       0     0     0
	  9  ONLINE       3     2     0 # <= killed this device FUSE process, still ONLINE

```

Nothing except a reboot recovers the system at this point. This prevents our auto replace scripts from working.

**Comment by behlendorf** [comment]
What happens when you run out of redundancy is the pool gets SUSPENDED not DEGRADED.  You can control the behavior of a suspended pool using the __failmode__ property.  The pool can be resumed by bringing the failed device back online and running `zpool clear`.  Although I agree we could make the `zpool status` output more informative.

```
       failmode=wait | continue | panic

           Controls  the  system  behavior  in  the event of catastrophic pool
           failure. This condition is typically a result of a loss of  connec‐
           tivity  to  the  underlying  storage  device(s) or a failure of all
           devices within the pool. The behavior of such an  event  is  deter‐
           mined as follows:

           wait        Blocks  all I/O access until the device connectivity is
                       recovered and the  errors  are  cleared.  This  is  the
                       default behavior.

           continue    Returns  EIO  to  any new write I/O requests but allows
                       reads to any of  the  remaining  healthy  devices.  Any
                       write  requests  that  have yet to be committed to disk
                       would be blocked.

           panic       Prints out a message to the  console  and  generates  a
                       system crash dump.
```

**Comment by kpande** [comment]
@behlendorf even with 'continue' instead of 'wait' it does not go into SUSPENDED, still shows ONLINE

**Comment by behlendorf** [comment]
Check the output of `dmesg` it should show a message showing the pool was suspended.

Oddly `zpool status` doesn't show when the pool is suspended, and this is what I think could be improved.  Currently the only valid values for "state: XXX" are found in `zpool_state_to_name()`.  (OFFLINE, REMOVED, FAULTED, SPLIT, UNAVAIL, DEGRADED, ONLINE, UNKNOWN).

**Comment by kpande** [comment]
hm, i'd think that it should appear as FAULTED then
