### ISSUE TITLE
lustre 2.9 and zfs 0.7-rc3

### ISSUE THREAD

**Issue by jn0** [zfsonlinux/zfs#6018]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Linux       |  CentOS
Distribution Version    |  7.3
Linux Kernel                 |  3.10.0-514.el7_lustre
Architecture                 |  x86_64
ZFS Version                  |  0.7.0-rc3
SPL Version                  |  0.7.0-rc3_8_g481762f

### Describe the problem you're observing

mount.lustre fails for unresolved "zrl_add" symbol at osd_zfs insertion

### Describe how to reproduce the problem

build/install lustre from src rpm, build/install zfs/spl from github, try to mount a zfs volume

### Include any warning/errors/backtraces from the system logs

At rpm install time:
```
depmod: WARNING: /lib/modules/3.10.0-514.el7_lustre.x86_64/extra/lustre-osd-zfs/fs/osd_zfs.ko needs unknown symbol zrl_add
```

I'm trying to "fix" `zfs/module/zfs/zrlock.c` with

```c
#ifdef zrl_add
#undef zrl_add
#endif

void zrl_add(zrlock_t *zrl, const char *zc)
{
        return zrl_add_impl(zrl, zc);
}
EXPORT_SYMBOL(zrl_add);
```
at the very end of the code (just before the last `#endif`)

Still testing/experimenting...

**Comment by ryao** [comment]
Try building luster after installing ZFS.

**Comment by rlaager** [comment]
I'm closing, as this is old. If this is still relevant, please let me know.
