### ISSUE TITLE
ZFS send/receive failed after 96.3TB (87%)

### ISSUE THREAD

**Issue by OmenWild** [zfsonlinux/zfs#6036]
### System information, sending system

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Ubuntu 
Distribution Version    | 12.04.5 LTS
Linux Kernel                 | 3.13.0-116-generic
Architecture                 | x86_64
ZFS Version                  | 0.6.5.4-1~precise
SPL Version                  | 0.6.5.4-1~precise

### System information, receiving system

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Ubuntu
Distribution Version    | 16.04.2 LTS
Linux Kernel                 | 4.4.0-72-generic
Architecture                 | x86_64
ZFS Version                  | 0.6.5.6-0ubuntu15
SPL Version                  | 0.6.5.6-0ubuntu4

### Describe the problem you're observing
A ZFS send/receive between two hosts connected over InfiniBand stopped 87% of the way through. It moved 96.3TB of data over 4.5 days, then 2 days ago, the zfs process on the receive side exited, possibly due to `cannot share 'aqua-test': share(1M) failed` (see below).

The receive host is a very bare instance of Ubuntu 16.04 without the NFS packages installed.

Oddly enough, on the receive side, both mbuffer and netcat are still running, but ps shows no sign of zfs, so I am guessing it exited after it printed that error.

It seems to me that a soft error, that could be resolved at a later time, should not cause an operation that takes days to finish, to fail.

### Describe how to reproduce the problem
Sender:
```
zfs send -R -e z0@1 | mbuffer -m 1G | nc.traditional 172.16.3.28 8023
```

Receiver:
```
netcat -w 1200 -l -p 8023 | mbuffer -m 5G | zfs receive -d -F aqua-test
```

### Include any warning/errors/backtraces from the system logs
No kernel warnings or backtraces on either end, but the receiver noted:
```
in @  400 MiB/s, out @  0.0 KiB/s, 97.1 TiB total, buffer   6% full cannot share 'aqua-test': share(1M) failed
in @  0.0 KiB/s, out @  0.0 KiB/s, 97.1 TiB total, buffer 100% full
```

**Comment by kpande** [comment]
have you tried using `recv -u` to not mount the receiving end? doing recv in this way won't die until the netcat pipe to it breaks.
