### ISSUE TITLE
Can't mount any volumes

### ISSUE THREAD

**Issue by stefanfritsch** [zfsonlinux/zfs#6045]
Hi,

this problem might very well originate from user error, I'm an amateur when it comes to zfs. But it's in my opinion at least a minor issue as if I issue a command and that command fails I expect an error. But the only error I've been able to get is with `mount -t zfs` (as opposed to `zfs mount`).

If I did nothing wrong then it is a major issue because it means the pool is unmountable.

So I'd be very thankful for any suggestions, especially if they show that I'm just an idiot. :)

Thanks,
Stefan

### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  RancherOS
Distribution Version    |  1.0.0
Linux Kernel                 |  4.9.21-rancher
Architecture                 |  x86_64
ZFS Version                  |  0.6.5.9-1
SPL Version                  |  0.6.5.9-1

### Describe the problem you're observing

I upgraded my OS. Before the upgrade I exported the pool. After the upgrade zpool status looks fine but I can no longer mount any of the volumes of the pool.

```
root@se-helmet:/# zpool status
  pool: helmet-pool
 state: ONLINE
  scan: resilvered 36K in 0h0m with 0 errors on Wed Apr 19 15:54:59 2017
config: ...
errors: No known data errors

root@se-helmet:/# zfs list -o name,mountpoint,mounted

NAME                              MOUNTPOINT                         MOUNTED
helmet-pool                       /helmet-pool                            no
helmet-pool/Databases             /helmet-pool/Databases                  no
...

root@se-helmet:/# zfs mount -va
root@se-helmet:/# zfs mount -v helmet-pool
root@se-helmet:/# zfs mount -v helmet-pool/Databases
root@se-helmet:/# zfs list -o name,mountpoint,mounted

NAME                              MOUNTPOINT                         MOUNTED
helmet-pool                       /helmet-pool                            no
helmet-pool/Databases             /helmet-pool/Databases                  no
```

### Include any warning/errors/backtraces from the system logs

No warnings, errors or messages in the system logs. The only error I've been able to get is if I try to use  mount:

```
root@se-helmet:/# mount -t zfs helmet-pool/Databases /test

filesystem 'helmet-pool/Databases' cannot be mounted at '/test' due to canonicalization error 2.
```

**Comment by loli10K** [comment]
> root@se-helmet:/# mount -t zfs helmet-pool/Databases /test
> filesystem 'helmet-pool/Databases' cannot be mounted at '/test' due to canonicalization error 2.

@stefanfritsch does this still happen if you run the `mount` command from another working directory?

**Comment by stefanfritsch** [comment]
yep, same error.

But I have found the reason.

RancherOS uses an overlay filesystem and zfs and the user live on incompatible "planes". 

I found that from the canonicalization error (as another issue mentioned it gets thrown if the destination dir does not exist) and from problems with zdb:

```
root@se-helmet:/# zdb
cannot open '/etc/zfs/zpool.cache': No such file or directory
root@se-helmet:/# ls -l /etc/zfs
total 8
drwxr-xr-x 2 root root 4096 Nov 29 10:27 zed.d
-rw-r--r-- 1 root root 1576 Apr  5 08:06 zpool.cache
```

Moving the pool hierarchy to `/mnt/helmet-pool` solved the issue. I assume they did some changes in RancherOS between versions and so it worked with the old one but no longer with the new one.

It would be nice if zfs could provide an informative error if it can't mount due to issues with the destination directories.

Thanks a lot for your reply. It's worth a lot to get confirmation that what you're doing is basically sound and that you have to look for the problem elsewhere.

Many thanks,
Stefan

**Comment by loli10K** [comment]
> Moving the pool hierarchy to /mnt/helmet-pool solved the issue.

@stefanfritsch i'm glad you got this sorted out 👍

**Comment by nornagon** [comment]
Since this is the first result on Google for this error, what fixed it for me was recreating the zpool with no `mountpoint` option set. Apparently ZFS can have its own ideas of where it wants things to be mounted, and if you set it up that way then it will complain loudly if you try to mount things in a different configuration. (for me, I had set `mountpoint=/` on the pool and was attempting to mount it at `/mnt`.)

**Comment by cschoenebeck** [comment]
That's indeed no user friendly error message. Apparently it is printing the POSIX error code (ENOENT=2="No such file or directoy") at the end of the error message, so printing at least the auto translated error string would make sense.

As it is a common error though to forget creating the target directory for new filesystems, it would IMO make sense to add a dedicated error message stating that the mount point does not exist, and the actual resolved path of the mount point.
