### ISSUE TITLE
mountpoint remains in use afte restore snapshot 

### ISSUE THREAD

**Issue by sayto** [zfsonlinux/zfs#6070]
### System information

Distribution Name    |  Ubuntu
Distribution Version  | 16.04
Linux Kernel             | 4.4.0-72-generic
Architecture              | x86_64
ZFS Version             | 0.6.5.6-0ubuntu15
SPL Version             | 0.6.5.6-0ubuntu4
zfsutils-linux Version| 0.6.5.6-0ubuntu16

Problem:
I use lxd
after restore container from shapshot cannot add new snapshot or restore again
until restart container

Step to reproduce the problem:

launch container:
 lxc launch debian/jessie

```
Creating popular-kitten
Starting popular-kitten
```
and create snapshot:
 lxc snapshot popular-kitten

let`s see configs and stats:

 lxc info popular-kitten
```
Name: popular-kitten
Remote: unix:/var/lib/lxd/unix.socket
....
Profiles: default
```
 lxc profile show default
```
...
pool: main-pool
```
 zfs get mounted main-pool/containers/popular-kitten
```
NAME PROPERTY VALUE SOURCE
main-pool/containers/popular-kitten mounted yes -
```
 zfs get mounted main-pool/snapshots/popular-kitten
```
NAME PROPERTY VALUE SOURCE
main-pool/snapshots/popular-kitten mounted yes -
```
now restore container from snapshot:
 lxc restore popular-kitten snap0
and see, what changes

 zfs get mounted main-pool/snapshots/popular-kitten
```
NAME PROPERTY VALUE SOURCE
main-pool/snapshots/popular-kitten mounted yes -
```
 zfs get mounted main-pool/containers/popular-kitten
```
NAME PROPERTY VALUE SOURCE
main-pool/containers/popular-kitten mounted no -
```
if try to make new snapshot or restore again:

 lxc snapshot popular-kitten
```
error: Failed to mount ZFS filesystem: filesystem 'main-pool/containers/popular-kitten' is already mounted
cannot mount 'main-pool/containers/popular-kitten': mountpoint or dataset is busy
```
 lxc restore popular-kitten snap0
```
error: Failed to mount ZFS filesystem: filesystem 'main-pool/containers/popular-kitten' is already mounted
cannot mount 'main-pool/containers/popular-kitten': mountpoint or dataset is busy
```
but container still work:

 lxc info popular-kitten
```
Name: popular-kitten
Remote: unix:/var/lib/lxd/unix.socket
Architecture: x86_64
Created: 2017/04/25 07:17 UTC
Status: Running
```

 lxc exec popular-kitten bash
```
root@popular-kitten:~# uptime
 07:34:06 up 8 min, 0 users, load average: 0.00, 0.02, 0.03
```
after restart container:

 lxc restart popular-kitten
 zfs get mounted main-pool/containers/popular-kitten
```
NAME PROPERTY VALUE SOURCE
main-pool/containers/popular-kitten mounted yes -
```
on another server this problem missmatch:

Distribution Name    |  Ubuntu
Distribution Version  | 16.10
Linux Kernel             | 4.8.0-46-generic
Architecture              | x86_64
ZFS Version             | 0.6.5.8-0ubuntu4.1
SPL Version             | 0.6.5.8-2
zfsutils-linux Version| 0.6.5.8-0ubuntu4.1

this bug on ubuntu bug tracker:
https://bugs.launchpad.net/ubuntu/+source/lxc/+bug/1686036

**Comment by brauner** [comment]
Sorry, this is the wrong repo to report this agains. I wasn meaning that you open it on https://github.com/lxc/lxd. :)

**Comment by sayto** [comment]
Did not understand you
created another one issue))

**Comment by brauner** [comment]
@sayto, np at all. Sorry for the noise @zfsonlinux/zfs guys. :)
