### ISSUE TITLE
zfs_dirty_data_max_max grows without bound as memory is installed

### ISSUE THREAD

**Issue by evujumenuk** [zfsonlinux/zfs#6072]
As of https://github.com/zfsonlinux/zfs/pull/1696#issuecomment-29843941, `zfs_dirty_data_max_max` is dynamically set to a fraction of `physmem * PAGESIZE` where it used to be statically set to 4 GiB. As the comment notes, this change was intended to prevent overflow of `zfs_dirty_data_max` and `zfs_dirty_data_max_max` on 32-bit systems.

It's clear that these values need to shrink on 32-bit systems.

It's not clear that these values would need to grow on large 64-bit systems.

Ideally, `zfs_dirty_data_max_max` would be capped to 4 GB (as it was before).

**Comment by behlendorf** [comment]
@evujumenuk thanks for reminding us about this.  Yes, this was an oversight and we should reinstate it which I've done in PR #6081.  @tuxoko I believe you ran in to trouble with this when testing on a large memory machine, if you could review this that'd be great.
