### ISSUE TITLE
Intel Optane Memory log device compatibility 

### ISSUE THREAD

**Issue by RubenKelevra** [zfsonlinux/zfs#6080]
Phoronix wrote over the general compatibility of Linux with the new Optane Memory from Intel.

I was wondering if somebody did some testing of Log-Device compatibility, does it honor the write barrier and hold all data or does a power loss result in data loss on those devices?

The very high 4k write performance should be very interesting for log-devices for hypervisors as well as database servers with 8k record sizes. 

Is zfs currently optimized to quickly write 4k/8k to the log devices and concat it to larger chuncks for slower harddrives/ssds? Or is there no performance benefit, because it just buffers peaks while the disks still have to write small chunks?

**Comment by kpande** [comment]
please use [the mailing list](http://list.zfsonlinux.org) for discussion since this is the issue tracker for development. thank you!

**Comment by problame** [comment]
@RubenKelevra you might be interested in https://github.com/openzfs/zfs/pull/12731
