### ISSUE TITLE
Couple of small improvements to the HOWTO (Ubuntu 16.04 ZFS on Root)

### ISSUE THREAD

**Issue by mahmoud** [zfsonlinux/zfs#6090]
Not really system-specific, but notes on [the HOWTO](https://github.com/zfsonlinux/zfs/wiki/Ubuntu-16.04-Root-on-ZFS):

1. Maybe add a note about `sgdisk --zap` on already-partitioned disks. I ran into `Error encountered; not saving changes` a couple times before I realized I needed to destroy existing partitions.
2. `vi` and `nano` are not available after the `chroot` step, but `echo` / `cat` works fine to add lines.

Overall an excellent guide, thank you very much!

**Comment by rlaager** [comment]
Are you saying that `vi` is not available for the start of step 4.4 (for editing /etc/apt/sources.list)? It is absolutely available after that step, as ubuntu-minimal depends on vim-tiny.

**Comment by mahmoud** [comment]
What can I say, perhaps it was a PATH issue? Definitely got `command not found`.

**Comment by rlaager** [comment]
For the first item, see the updated step 2.1.

For the second item, I just tested; `nano` is definitely unavailable, but `vi` definitely is. I re-ordered the creation of the sources list to before the `chroot` such that it is possible to use `nano` all the time. I also added a note about installing `nano` in the chroot environment. See the updated steps 4.3 & 4.5.

**Comment by mahmoud** [comment]
Excellent! Thank you very much :)
