### ISSUE TITLE
Want ZIL Pipelining

### ISSUE THREAD

**Issue by ryao** [zfsonlinux/zfs#6097]
Right now, concurrent synchronous operations block on ZIL. While we do batching, the blocking adds latency. If we could pipeline ZIL so that we can begin preparing new lwbs while ZIO is writing out the current commit, concurrent synchronous IO performance should improve, especially in terms of latencies.

By the way, I have written a preliminary patch at work. There is 1 space leak bug that I need to fix. After fixing it, the plan is to put it into a pull request. I am just filing this a little early to let people know that the patch is imminent. :)

**Comment by behlendorf** [comment]
@ryao when you open the PR please include your benchmark test results.

**Comment by ryao** [comment]
@behlendorf Unfortunately, I am not at liberty to publish all of my benchmark test results because some of the benchmark configurations are subject to confidentiality requirements. I will make time to produce numbers that I can publish via various configurations of fio.

That being said, I have found that ztest is insufficient to catch bugs in the ZIL changes. GPFs are happening in code that passes ztest when in the kernel and subject to extreme parallel synchronous loads. I'll have something to publish after that issue is solved.

**Comment by ryao** [comment]
@behlendorf Unfortunately, the benchmark configuration being used to evaluate progress by work is subject to confidentiality requirements. I will make time to produce numbers that I can publish via various configurations of fio though. Fio is my first choice anyway.

That being said, the leak issue is fixed, but I have found that ztest is insufficient to catch bugs in the ZIL changes. GPFs are happening in code that passes ztest when in the kernel and subject to extreme parallel synchronous loads. I expect to have something to publish after that issue is solved.

**Comment by ryao** [comment]
@behlendorf Unfortunately, the benchmark configuration being used to evaluate progress by work is subject to confidentiality requirements. I will make time to produce numbers that I can publish via various configurations of fio though. Fio is my first choice anyway.

That being said, the leak issue is fixed, but I have found that ztest is insufficient to catch bugs in the ZIL changes. GPFs are happening in code that passes ztest when both in the kernel and subject to extreme parallel synchronous loads. I expect to have something to publish after that issue is solved.

**Comment by ryao** [comment]
The patch is ready for review at #6133. I have a deadline to improve performance at work later this week, so I am leaving the fio work for after that.

**Comment by scineram** [comment]
I think this can be closed after #6566.

**Comment by behlendorf** [comment]
@scineram yes indeed.  Closing.
