### ISSUE TITLE
"make deb" produces dependencies with incompatible package names

### ISSUE THREAD

**Issue by aerusso** [zfsonlinux/zfs#6106]
This has affected the packaging for a quite a while, and still affect 0.7.0-rc4. When installing the produced `.deb`'s:

```
Selecting previously unselected package kmod-spl-4.9.0-3-amd64.
(Reading database ... 251177 files and directories currently installed.)
Preparing to unpack kmod-spl-4.9.0-3-amd64_0.7.0-0_amd64.deb ...
Unpacking kmod-spl-4.9.0-3-amd64 (0.7.0-0) ...
Selecting previously unselected package kmod-zfs-4.9.0-3-amd64.
Preparing to unpack kmod-zfs-4.9.0-3-amd64_0.7.0-0_amd64.deb ...
Unpacking kmod-zfs-4.9.0-3-amd64 (0.7.0-0) ...
Selecting previously unselected package libnvpair1.
Preparing to unpack libnvpair1_0.7.0-0_amd64.deb ...
Unpacking libnvpair1 (0.7.0-0) ...
Selecting previously unselected package libuutil1.
Preparing to unpack libuutil1_0.7.0-0_amd64.deb ...
Unpacking libuutil1 (0.7.0-0) ...
Selecting previously unselected package libzfs2.
Preparing to unpack libzfs2_0.7.0-0_amd64.deb ...
Unpacking libzfs2 (0.7.0-0) ...
Selecting previously unselected package libzpool2.
Preparing to unpack libzpool2_0.7.0-0_amd64.deb ...
Unpacking libzpool2 (0.7.0-0) ...
Selecting previously unselected package spl.
Preparing to unpack spl_0.7.0-0_amd64.deb ...
Unpacking spl (0.7.0-0) ...
Selecting previously unselected package zfs-initramfs.
Preparing to unpack zfs-initramfs_0.7.0-0_amd64.deb ...
Unpacking zfs-initramfs (0.7.0-0) ...
Selecting previously unselected package zfs.
Preparing to unpack zfs_0.7.0-0_amd64.deb ...
Unpacking zfs (0.7.0-0) ...
Setting up kmod-spl-4.9.0-3-amd64 (0.7.0-0) ...
Setting up kmod-zfs-4.9.0-3-amd64 (0.7.0-0) ...
dpkg: dependency problems prevent configuration of libnvpair1:
 libnvpair1 depends on libuutil1linux; however:
  Package libuutil1linux is not installed.

dpkg: error processing package libnvpair1 (--install):
 dependency problems - leaving unconfigured
Setting up libuutil1 (0.7.0-0) ...
dpkg: dependency problems prevent configuration of libzfs2:
 libzfs2 depends on libnvpair1linux; however:
  Package libnvpair1linux is not installed.
 libzfs2 depends on libzpool2linux; however:
  Package libzpool2linux is not installed.

dpkg: error processing package libzfs2 (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libzpool2:
 libzpool2 depends on libnvpair1linux; however:
  Package libnvpair1linux is not installed.
 libzpool2 depends on libuutil1linux; however:
  Package libuutil1linux is not installed.

dpkg: error processing package libzpool2 (--install):
 dependency problems - leaving unconfigured
Setting up spl (0.7.0-0) ...
Setting up zfs-initramfs (0.7.0-0) ...
dpkg: dependency problems prevent configuration of zfs:
 zfs depends on libnvpair1linux; however:
  Package libnvpair1linux is not installed.
 zfs depends on libuutil1linux; however:
  Package libuutil1linux is not installed.
 zfs depends on libzfs2linux; however:
  Package libzfs2linux is not installed.
 zfs depends on libzpool2linux; however:
  Package libzpool2linux is not installed.

dpkg: error processing package zfs (--install):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.24-10) ...
Processing triggers for man-db (2.7.6.1-2) ...
Processing triggers for systemd (232-22) ...
Errors were encountered while processing:
 libnvpair1
 libzfs2
 libzpool2
 zfs
```

Just putting `--force-depends` seems to make everything work fine. The `alien` rpm -> deb process looks complicated, so I stopped my search there.

**Comment by MyPod** [comment]
I recall having a similar result when I didn't properly clean up the packages that come from the distribution repository before building spl and zfs. Make sure to remove them from the system and try building again

**Comment by loli10K** [comment]
To confirm what MyPod said i built 0.7.0-rc4 and the resulting `libnvpair1` package does not depend on `libuutil1linux`:

```
root@debian-8-zfs:/usr/src/zfs# dpkg -I libnvpair1_0.7.0-0_amd64.deb 
 new debian package, version 2.0.
 size 72328 bytes: control archive=843 bytes.
     608 bytes,    15 lines      control              
     207 bytes,     3 lines      md5sums              
      23 bytes,     1 lines      shlibs               
      60 bytes,     2 lines      triggers             
 Package: libnvpair1
 Version: 0.7.0-0
 Architecture: amd64
 Maintainer: root <root@debian-8-zfs>
 Installed-Size: 328
 Depends: libc6 (>= 2.3.4), libudev1 (>= 183), libuuid1 (>= 2.16), libuutil1, zlib1g (>= 1:1.1.4)
 Section: alien
 Priority: extra
 Description: Solaris name-value library for Linux
  This package contains routines for packing and unpacking name-value
  pairs.  This functionality is used to portably transport data across
  process boundaries, between kernel and user space, and can be used
  to write self describing data structures on disk.
  .
  (Converted from a rpm package by alien version 8.92.)
```

@aerusso it doesn't seem that "make deb produces dependencies with incompatible package names", it's more likely you're mixing packages compiled from source with packages from ... debian stretch i guess? There should be an "template" that helps you post useful information (os name/version, steps to reproduce the problem) when opening a new issue.

**Comment by aerusso** [comment]
@loli10K It is true that I have Debian packages installed, but I am using `--with-spl` and `--with-spl-obj` referring to the (already compiled) spl-0.7.0-rc4. I still do not understand why the zfs build process should produce packages depending on the Debianized packages.

The scenario I am in in is that I am running ZFS on root (almost)---and would like to compile rc4). I am currently using the Debian packages. I cannot uninstall any zfs packages, because that would render the machine un-bootable. Is there to be no migration path from Debian back to source installation?

The build process for this project is complicated, so I'm working on getting another stretch machine (without any installed zfs packages) up for testing.

**Comment by MyPod** [comment]
I haven't been checking, but I suspect the issue is in the packaging, not in the building itself. Your specifying of `--with-spl` and `--with-spl-obj` has little to do with the parsing of ldd that creating a package does to check what other packages the package-in-the-making is depending on.
As someone who has switched from the repository ones to custom-built ones, I recommend you use a chroot environment to build the spl and zfs packages.

**Comment by aerusso** [comment]
@MyPod Thank you! Your comment is exactly correct. and something like it should be included in the documentation. Probably on `https://github.com/zfsonlinux/zfs/wiki/Building-ZFS` near where `make deb` is mentioned.

As @MyPod accurately described, during the packaging phase dependencies are automatically generated---in particular during the `alien` conversion rpm->deb phase, `dh_shlibdeps` is called (which in turn calls `dpkg-shlibdeps`). If `dh_shlibdeps` is replaced by a dummy executable simply returning an empty line, the generated `deb` files have no mention of the Debianized packages. 

The spartan `alien` documentation doesn't suggest there's any simple way to turn this behavior off. And the source code seems to confirm that. The simplest solution is probably going to be to bypass `alien` entirely---and not attempt to dynamically generate dependencies. I'm not going to be able to produce a patch that does that for a while.

**Comment by aerusso** [comment]
The above two pull requests produce `deb` files without the automatically generated `dh_shlibdeps` dependencies by hacking a softlink to /bin/true in place of `dh_shlibdeps` into the PATH.
