### ISSUE TITLE
Trace points Build Failure

### ISSUE THREAD

**Issue by behlendorf** [zfsonlinux/zfs#6120]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | CentOS
Distribution Version    | 7.3.1611
Linux Kernel                 | 3.10.0-514.16.1.el7.x86_64
Architecture                 | x86_64
ZFS Version                  | zfs-0.7.0-rc4
SPL Version                  | spl-0.7.0-rc4

### Describe the problem you're observing

Changing the license in from CDDL to GPL in the top level META file results in a build failure when compiling support for trace points.  Building [ZFS directly in to a more recent kernel](http://build.zfsonlinux.org/builders/Kernel.org%20Built-in%20x86_64%20%28BUILD%29/builds/12931) does not appear to cause this build issue.  
### Describe how to reproduce the problem

```
> sed -i -- 's/CDDL/GPL/g' META
> sh autogen.sh
> ./configure
> make
```

### Include any warning/errors/backtraces from the system logs

```
In file included from ./arch/x86/include/asm/spinlock.h:4:0,
                 from include/linux/spinlock.h:87,
                 from include/linux/seqlock.h:35,
                 from include/linux/time.h:5,
                 from include/linux/stat.h:18,
                 from include/linux/module.h:10,
                 from /home/behlendo/src/git/spl/include/sys/sysmacros.h:28,
                 from /home/behlendo/src/git/spl/include/sys/types.h:29,
                 from /home/behlendo/src/git/zfs/include/sys/zfs_context.h:34,
                 from /home/behlendo/src/git/zfs/include/sys/multilist.h:22,
                 from /home/behlendo/src/git/zfs/module/zfs/trace.c:26:
include/linux/jump_label.h:120:40: error: initializer element is not constant
 #define STATIC_KEY_INIT_FALSE ((struct static_key) \
                                        ^
include/linux/tracepoint.h:210:24: note: in expansion of macro ‘STATIC_KEY_INIT_FALSE’
   { __tpstrtab_##name, STATIC_KEY_INIT_FALSE, reg, unreg, NULL };\
                        ^
include/linux/tracepoint.h:216:2: note: in expansion of macro ‘DEFINE_TRACE_FN’
  DEFINE_TRACE_FN(name, NULL, NULL);
  ^
include/trace/define_trace.h:45:2: note: in expansion of macro ‘DEFINE_TRACE’
  DEFINE_TRACE(name)
  ^
/home/behlendo/src/git/zfs/include/sys/trace_dbgmsg.h:73:1: note: in expansion of macro ‘DEFINE_EVENT’
 DEFINE_EVENT(zfs_dprintf_class, name, \
 ^
/home/behlendo/src/git/zfs/include/sys/trace_dbgmsg.h:78:1: note: in expansion of macro ‘DEFINE_DPRINTF_EVENT’
 DEFINE_DPRINTF_EVENT(zfs_zfs__dprintf);
 ^
```

**Comment by tuxoko** [comment]
@behlendorf 
IIRC, this is sort of a bug in older gcc when using std=gnu99

**Comment by behlendorf** [comment]
Closing.  Won't fix, this isn't an issue with newer versions of gcc.
