### ISSUE TITLE
Feature request: SipHash to replace fletcher4

### ISSUE THREAD

**Issue by RubenKelevra** [zfsonlinux/zfs#6129]
Currently the default Hash algorithm to secure data-integrity is fletcher4, which is designed from a data integrity than from a cryptographic standpoint, like crc32 is too.

Linux 4.11 supports a new extremely fast 64-bit hash algorithm called SipHash which is designed also from a cryptographic standpoint.

Since it's much more modern and very fast, we might want to consider using it as new default hash-algorithm and discard fletcher4 because of it's age.

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=2c956a60778cbb6a27e0c7a8a52a91378c90e1d1

**Comment by DeHackEd** [comment]
Here are some arguments against:

* As a keyed hash, a key needs to be standardized on.
* ZFS wants a 256 bit hash. You could use this as the foundation for one, but not as-is.
* "discarding fletcher4" is unlikely to happen for backwards compatibility for a long time.
* Keep in mind you're defending against a drive, controller, or cable that has developed a bad case of the crazies... not from an external attacker with malicious intent and compute power.
* Is there a benchmark? fletcher4 is actually a very simple algorithm and even implemented with SIMD now.

**Comment by kernelOfTruth** [comment]
further against:

- it's 64-bit only
- in its previous incarnation it was supposedly pretty slow (need current benchmarks)

**Comment by kpande** [comment]
I'd welcome a patch that adds this capability but wouldn't argue for changing the default considering how [important](http://web.archive.org/web/20100111013302/http://mail.opensolaris.org/pipermail/zfs-discuss/2009-November/034106.html) they are for safety (and Linux 4.11 won't be widely available in all distributions for some time)

**Comment by RubenKelevra** [comment]
Thanks for your feedback!
