### ISSUE TITLE
Strange zfs list behavior 

### ISSUE THREAD

**Issue by RubenKelevra** [zfsonlinux/zfs#6130]
This is a minor bug report about the behavior of `zfs list`

This works as expected:
`# zfs list data/vms/mars`
`NAME.                 USED  AVAIL  REFER  MOUNTPOINT`
`data/vms/mars   866G  1,42T  72,8G  -`

This doesn't work as expected:

`# zfs list -t snapshot data/vms/mars`
`cannot open 'data/vms/mars': operation not applicable to datasets of this type`

So we need to do a workaround like this to get a result:

`# zfs list -t snapshot | grep data/vms/mars`

Am I holding it wrong? Or is this limitation intentionally?

**Comment by DeHackEd** [comment]
This is behaving as intended and not a bug. You asked for a particular dataset, and a mismatched type filter. Perhaps you want to add `-d 1 -r` to your command-line?
