### ISSUE TITLE
Complete hang when using zfs recv and dev/pool went offline [version 0.6.5.9-1]

### ISSUE THREAD

**Issue by ioquatix** [zfsonlinux/zfs#6138]
### Describe the problem you're observing

I was doing a zfs send | zfs recv and the receiving zdev failed.

The zfs recv command has completely hung and even kill -9 won't kill it.

I tried to do a backtrace using gdb but it hung too.

**Comment by kpande** [comment]
you didn't provide any backtraces or debugging information, please see [here](https://github.com/zfsonlinux/zfs/wiki/FAQ#reporting-a-problem).

**Comment by ioquatix** [comment]
I tried to but when using gdb to collect a backtrace, it also hung.
