### ISSUE TITLE
SPL configure error on Centos 7.3 3.10.0-514.16.1.el7.x86_64

### ISSUE THREAD

**Issue by samuelxhu** [zfsonlinux/zfs#6152]
[root@spl]# uname -r
3.10.0-514.16.1.el7.x86_64

[root@spl]# cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core)

[root@spl]# gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

On master branch running ./configure yields the following error
checking whether old 2-argument shrinker exists... no
checking whether old 3-argument shrinker exists... no
checking whether new 2-argument shrinker exists... no
checking whether ->count_objects callback exists... configure: error: error

The same thing happens on almost all previous ZoL versions, including 0.6.5, 0.6.4, 0.6.3 etc

how to fix it?

**Comment by samuelxhu** [comment]
@tonyhutter Surprising enough. I have just checked again, i still got the configure error, though i have the same kernel version and centos version as yours.
checking whether old 2-argument shrinker exists... no
checking whether old 3-argument shrinker exists... no
checking whether new 2-argument shrinker exists... no
checking whether ->count_objects callback exists... configure: error: error

May i ask what is your gcc version?

**Comment by samuelxhu** [comment]
My own mistake.

**Comment by SpiffyB** [comment]
@smuething can you explain what you did wrong? I'm getting the same error at the moment
