### ISSUE TITLE
Support .zfs/snapshot access via NFS

### ISSUE THREAD

**Issue by behlendorf** [zfsonlinux/zfs#616]
While the .zfs/snapshot directory is supported in the latest source, it is not yet accessible via NFS.  There are a few integrations issues with the Linux NFS kernel servers which still need to be worked out.  This issue is to track that work.

**Comment by micw** [comment]
This also might affect bind mounts (e.g. when trying to access a snapshot from within a linux container or a docker box): http://comments.gmane.org/gmane.linux.file-systems.zfs.user/20179

@behlendorf , what's the reason to have the milestone set to 0.8.0? It seems that there are working patches since more than a year. Solving this would allow much new use cases for zfs on linux.

**Comment by micw** [comment]
For bind mounts (e.g. in lxc containers) the issue can be workarounded by calling
```
mount --make-shared /path/to/mounted/volume
```
before creating the bind mount.

**Comment by behlendorf** [comment]
@micw Yes it's definitely not that far off, #2797 actually contains the latest version of the patches and they're something I hope to merge shortly after the next tag.  It would be great if you could give the latest patches with a recent kernel and verify they work properly.

**Comment by segdy** [comment]
@micw Can you elaborate on the workaround with "--make-shared"? I was pretty excited when I saw it but unfortunately it does not work for me:

On the "root machine" (hardware node):

    hwnode: # zfs create pool/test
    hwnode: # zfs set snapdir=visible pool/test
    hwnode: # mount --make-shared /pool/test
    hwnode: # mount -n --bind /pool/test /var/lib/vz/root/200/mnt/test
    hwnode: # zfs snapshot pool/test@first
    hwnode: # zfs snapshot pool/test@second
    hwnode: # touch /pool/test/testfile

Then, entering the OpenVZ container (conceptually should be the same as LXC):

    container: # cd /mnt/test
    container: # ls -a
    .  ..  .zfs  testfile
    container: # cd .zfs/snapshot
    container: # ls -a
    .  ..  first  second
    container: # cd first
    -bash: cd: first: Too many levels of symbolic links

... exactly the same result as without "--make-shared" :-(
