### ISSUE TITLE
Setting snapshot_limit at the zpool level makes grub fail for all datasets on the pool.

### ISSUE THREAD

**Issue by samvde** [zfsonlinux/zfs#6169]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Ubuntu 
Distribution Version    | 16.04.2
Linux Kernel                 | 4.8.0-53-generic
Architecture                 | amd64
ZFS Version                  | 0.6.5.8-0ubuntu4.2
SPL Version                  | 0.6.5.8-2

### Describe the problem you're observing
When setting snapshot_limit on a given rpool (top level dataset), the rpool nor any dataset on it will be bootable by grub.

At boot, grub drops into a rescue prompt reporting the error "compression algorithm inherit not supported". The same error is reported by grub-probe and subsequently grub-install, making repair impossible. 

At worst this is a corruption issue in zfs, at best it is a grub bug.

I haven't found a way to undo this except re-creating the pool (zfs send/recv comes to mind). Unsetting snapshot_limit (to none) does not solve the issue. Move /boot from zfs to a separate partition was required to make the system bootable again (using the second partition). I might try renaming the pool or re-creating the disk partition (online, using a new temporary mirror during the migration), but it would help if someone who understands what happens here could point me in the right direction wrt. what could work.

Scrub detects no errors.
Send/Recv datasets from an impacted rpool to another one makes them detectable by grub again (on the second pool).
 
### Describe how to reproduce the problem
zpool create -o mountpoint=/rpool rpool /dev/sdax
zfs create rpool/dataset

Scenario 1:
zfs set snapshot_limit=16 rpool/dataset
grub-probe /rpool              -> zfs
grub-probe /rpool/dataset -> zfs

Scenario 2:
zfs set snapshot_limit=16 rpool
grub-probe /rpool              -> "compression algorithm inherit not supported"
grub-probe /rpool/dataset -> "compression algorithm inherit not supported"
You can now no longer use this rpool to boot a system natively.

**Comment by BtbN** [comment]
grub does not support all features from modern ZFS. Some options make it impossible for grub to read a pool.
Guess you found one of them.

**Comment by samvde** [comment]
That doesn't explain why unsetting it does not solve the issue.

**Comment by BtbN** [comment]
I'd assume because it sets a feature flag or something, and the fs is then permanently in need of a feature that grub does not have. But I'm not an expert on how ZFS works internally, just seems unlikely to me for this to be a bug on either side, just an unsupported feature by grub.

**Comment by samvde** [comment]
Well, you set this at the zfs level. I have not seen differences between features of an impacted pool and a working one.

**Comment by bunder2015** [comment]
This does sound like a grub problem, however I believe grub should already support feature@filesystem_limits.  Which version do you have installed?  This may be better suited for IRC or the mailing lists.

**Comment by samvde** [comment]
When looking at scenario 1 & 2 the zpool features are indistinguishable, with feature@filesystem_limits active on both occasions. I'm not sure why grub would handle those cases differently.

The installed package is 2.02~beta2-36ubuntu3.9 but I believe Canonical pulled in some patches to regular grub.

**Comment by bunder2015** [comment]
I think that should be recent enough, out of curiosity, can you try also setting it on the dataset that you're booting from as well?

**Comment by samvde** [comment]
That actually was the case.

As far as I was able to pin it down, things work well until you set a value for snapshot_limit at the pool itself, so at the top-level zfs dataset.

**Comment by loli10K** [comment]
> At worst this is a corruption issue in zfs, at best it is a grub bug.

Good news, this seems to be a GRUB bug.

Setting "filesystem_limit" on the dataset cause the dir object to be "zapified" (`dsl_dir_init_fs_ss_count()` -> `dsl_dir_zapify()` -> `dmu_object_zapify()`). Notice how the type changes from `DSL directory` (DMU_OT_DSL_DIR) to `zap` (DMU_OTN_ZAP_METADATA):

```
root@debian:/usr/src/grub# POOLNAME='testpool'
root@debian:/usr/src/grub# TMPDIR='/var/tmp'
root@debian:/usr/src/grub# zpool destroy -f $POOLNAME
root@debian:/usr/src/grub# rm -f $TMPDIR/zpool.dat
root@debian:/usr/src/grub# fallocate -l 128m $TMPDIR/zpool.dat
root@debian:/usr/src/grub# zpool create -O mountpoint=/srv/$POOLNAME $POOLNAME $TMPDIR/zpool.dat
root@debian:/usr/src/grub# #
root@debian:/usr/src/grub# zdb -dd $POOLNAME 2
Dataset mos [META], ID 0, cr_txg 4, 48.0K, 35 objects

    Object  lvl   iblk   dblk  dsize  lsize   %full  type
         2    1    16K    512      0    512    0.00  DSL directory

root@debian:/usr/src/grub# ./grub-probe /srv/$POOLNAME
zfs
root@debian:/usr/src/grub# #
root@debian:/usr/src/grub# zfs set filesystem_limit=1234 $POOLNAME
root@debian:/usr/src/grub# #
root@debian:/usr/src/grub# zdb -dd $POOLNAME 2
Dataset mos [META], ID 0, cr_txg 4, 51.0K, 35 objects

    Object  lvl   iblk   dblk  dsize  lsize   %full  type
         2    1    16K    512      0    512  100.00  zap

root@debian:/usr/src/grub# ./grub-probe /srv/$POOLNAME
./grub-probe: error: compression algorithm inherit not supported
.
root@debian:/usr/src/grub# 
```

From the debugger we see `grub-probe` trying to read information with an invalid (zero-filled) bp in `zio_read()`:

```
root@debian:/usr/src/grub# gdb -q ./grub-probe -ex 'b grub-core/fs/zfs/zfs.c:1888' -ex "run /srv/$POOLNAME"
Reading symbols from ./grub-probe...done.
Breakpoint 1 at 0x442af4: file grub-core/fs/zfs/zfs.c, line 1888.
Starting program: /usr/src/grub/grub-probe /srv/testpool
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, zio_read (bp=0x7ffffffde570, endian=1, buf=0x7ffffffde1a8, size=0x7ffffffde1a0, data=0x714710) at grub-core/fs/zfs/zfs.c:1888
1888	    return grub_error (GRUB_ERR_NOT_IMPLEMENTED_YET,
(gdb) list
1883	  if (comp >= ZIO_COMPRESS_FUNCTIONS)
1884	    return grub_error (GRUB_ERR_NOT_IMPLEMENTED_YET,
1885			       "compression algorithm %u not supported\n", (unsigned int) comp);
1886	
1887	  if (comp != ZIO_COMPRESS_OFF && decomp_table[comp].decomp_func == NULL)
1888	    return grub_error (GRUB_ERR_NOT_IMPLEMENTED_YET,
1889			       "compression algorithm %s not supported\n", decomp_table[comp].name);
1890	
1891	  if (comp != ZIO_COMPRESS_OFF)
1892	    /* It's not really necessary to align to 16, just for safety.  */
(gdb) p *bp
$1 = {
  blk_dva = {{
      dva_word = {0, 0}
    }, {
      dva_word = {0, 0}
    }, {
      dva_word = {0, 0}
    }}, 
  blk_prop = 0, 
  blk_pad = {0, 0}, 
  blk_phys_birth = 0, 
  blk_birth = 0, 
  blk_fill = 0, 
  blk_cksum = {
    {
      zc_word = {0, 0, 0, 0}, 
      {
        zc_cut_cksum = {0, 0, 0, 0, 0}, 
        zc_mac = {0, 0, 0}
      }
    }
  }
}
(gdb) p/d ZIO_COMPRESS_INHERIT
$2 = 0
(gdb) p/d comp
$3 = 0
```

The real issue is in `fill_fs_info()`: because our objset is not a DMU_OT_DSL_DIR anymore we don't lookup the `dd_head_dataset_obj` from the metadnode bonus field (grub-core/fs/zfs/zfs.c:3971->3975)

```
(gdb) bt
#0  zio_read (bp=0x7ffffffde570, endian=1, buf=0x7ffffffde1a8, size=0x7ffffffde1a0, data=0x714710) at grub-core/fs/zfs/zfs.c:1888
#1  0x0000000000445d9b in make_mdn (mdn=0x7ffffffde430, data=0x714710) at grub-core/fs/zfs/zfs.c:3141
#2  0x0000000000447c58 in fill_fs_info (info=0x7ffffffde870, mdn=..., data=0x714710) at grub-core/fs/zfs/zfs.c:3982
#3  0x00000000004485fa in grub_zfs_dir (device=0x713540, path=0x4ddbc2 "/", hook=0x49eda8 <probe_dummy_iter>, hook_data=0x0) at grub-core/fs/zfs/zfs.c:4199
#4  0x000000000049ee83 in grub_fs_probe (device=0x713540) at grub-core/kern/fs.c:73
#5  0x00000000004035fc in probe (path=0x70f3a0 "/srv/testpool", device_names=0x713670, delim=10 '\n') at util/grub-probe.c:381
#6  0x000000000040486f in main (argc=2, argv=0x7fffffffec18) at util/grub-probe.c:863
(gdb) up
#1  0x0000000000445d9b in make_mdn (mdn=0x7ffffffde430, data=0x714710) at grub-core/fs/zfs/zfs.c:3141
3141	  err = zio_read (bp, mdn->endian, &osp, &ospsize, data);
(gdb) up
#2  0x0000000000447c58 in fill_fs_info (info=0x7ffffffde870, mdn=..., data=0x714710) at grub-core/fs/zfs/zfs.c:3982
3982	  err = make_mdn (&mdn, data);
(gdb) list fill_fs_info
3956	}
3957	
3958	static grub_err_t
3959	fill_fs_info (struct grub_dirhook_info *info,
3960		      dnode_end_t mdn, struct grub_zfs_data *data)
3961	{
3962	  grub_err_t err;
3963	  dnode_end_t dn;
3964	  grub_uint64_t objnum;
3965	  grub_uint64_t headobj;
(gdb) 
3966	  
3967	  grub_memset (info, 0, sizeof (*info));
3968	    
3969	  info->dir = 1;
3970	  
3971	  if (mdn.dn.dn_type == DMU_OT_DSL_DIR)
3972	    {
3973	      headobj = grub_zfs_to_cpu64 (((dsl_dir_phys_t *) DN_BONUS (&mdn.dn))->dd_head_dataset_obj, mdn.endian);
3974	
3975	      err = dnode_get (&(data->mos), headobj, 0, &mdn, data);
(gdb) p mdn.dn.dn_type
$4 = 196 '\304'
(gdb) p *((dsl_dir_phys_t *)mdn->dn->dn_bonus)
$5 = {
  dd_creation_time = 1496068974, 
  dd_head_dataset_obj = 21, 
  dd_parent_obj = 0, 
  dd_clone_parent_obj = 18, 
  dd_child_dir_zapobj = 4, 
  dd_used_bytes = 71680, 
  dd_compressed_bytes = 27136, 
  dd_uncompressed_bytes = 27136, 
  dd_quota = 0, 
  dd_reserved = 0, 
  dd_props_zapobj = 3, 
  dd_deleg_zapobj = 0, 
  unused = {1, 19456, 0, 52224, 0, 0, 0}, 
  keychain = 0, 
  unused2 = {0 <repeats 12 times>}
}
```

The same mdn is later used in `make_mdn()`, but now its bonus field is treated as a `dsl_dataset_phys_t`: its values are obviously wrong (ds_dir_obj = 1496068974 on a newly created pool?) `ds_bp` included, which is why `zio_read(ds_bp)` detects an invalid compression.

```
(gdb) list
3976	      if (err)
3977		{
3978		  grub_dprintf ("zfs", "failed here\n");
3979		  return err;
3980		}
3981	    }
3982	  err = make_mdn (&mdn, data);
3983	  if (err)
3984	    return err;
3985	  err = dnode_get (&mdn, MASTER_NODE_OBJ, DMU_OT_MASTER_NODE, 
(gdb) list make_mdn
3127	  return GRUB_ERR_NONE;
3128	}
3129	
3130	static grub_err_t
3131	make_mdn (dnode_end_t * mdn, struct grub_zfs_data *data)
3132	{
3133	  void *osp;
3134	  blkptr_t *bp;
3135	  grub_size_t ospsize = 0;
3136	  grub_err_t err;
(gdb) 
3137	
3138	  grub_dprintf ("zfs", "endian = %d\n", mdn->endian);
3139	
3140	  bp = &(((dsl_dataset_phys_t *) DN_BONUS (&mdn->dn))->ds_bp);
3141	  err = zio_read (bp, mdn->endian, &osp, &ospsize, data);
3142	  if (err)
3143	    return err;
3144	  if (ospsize < OBJSET_PHYS_SIZE_V14)
3145	    {
3146	      grub_free (osp);
(gdb) p *((dsl_dataset_phys_t *)mdn->dn->dn_bonus)
$6 = {
  ds_dir_obj = 1496068974, 
  ds_prev_snap_obj = 21, 
  ds_prev_snap_txg = 0, 
  ds_next_snap_obj = 18, 
  ds_snapnames_zapobj = 4, 
  ds_num_children = 71680, 
  ds_creation_time = 27136, 
  ds_creation_txg = 27136, 
  ds_deadlist_obj = 0, 
  ds_used_bytes = 0, 
  ds_compressed_bytes = 3, 
  ds_uncompressed_bytes = 0, 
  ds_unique_bytes = 1, 
  ds_fsid_guid = 19456, 
  ds_guid = 0, 
  ds_flags = 52224, 
  ds_bp = {
    blk_dva = {{
        dva_word = {0, 0}
      }, {
        dva_word = {0, 0}
      }, {
        dva_word = {0, 0}
      }}, 
    blk_prop = 0, 
    blk_pad = {0, 0}, 
    blk_phys_birth = 0, 
    blk_birth = 0, 
    blk_fill = 0, 
    blk_cksum = {
      {
        zc_word = {0, 0, 0, 0}, 
        {
          zc_cut_cksum = {0, 0, 0, 0, 0}, 
          zc_mac = {0, 0, 0}
        }
      }
    }
  }, 
  ds_pad = {0, 0, 0, 0, 0, 0, 0, 0}
}
(gdb) 
```

The following "_patch_" seems to "_fix_" the issue:

```
root@debian:/usr/src/grub# ./grub-probe /srv/$POOLNAME
./grub-probe: error: compression algorithm inherit not supported
.
root@debian:/usr/src/grub# cat issue-6169.patch 
diff --git a/grub-core/fs/zfs/zfs.c b/grub-core/fs/zfs/zfs.c
index 6e1fff9..5735015 100644
--- a/grub-core/fs/zfs/zfs.c
+++ b/grub-core/fs/zfs/zfs.c
@@ -3968,7 +3968,7 @@ fill_fs_info (struct grub_dirhook_info *info,
     
   info->dir = 1;
   
-  if (mdn.dn.dn_type == DMU_OT_DSL_DIR)
+  if (mdn.dn.dn_type == DMU_OT_DSL_DIR || mdn.dn.dn_type == DMU_OTN_ZAP_METADATA) /* zapified */
     {
       headobj = grub_zfs_to_cpu64 (((dsl_dir_phys_t *) DN_BONUS (&mdn.dn))->dd_head_dataset_obj, mdn.endian);
 
root@debian:/usr/src/grub# patch -p1 < issue-6169.patch 
patching file grub-core/fs/zfs/zfs.c
root@debian:/usr/src/grub# make -j`nproc` &> /dev/null
root@debian:/usr/src/grub# ./grub-probe /srv/$POOLNAME
zfs
root@debian:/usr/src/grub# 
```

**Comment by samvde** [comment]
I wish I could do what you do or at least understand it :-) Many thanks for explaining this. I'll see if I can get this fixed with the grub team.
