### ISSUE TITLE
RPI 64bit ZFS IOT Tweaks...

### ISSUE THREAD

**Issue by necrose99** [zfsonlinux/zfs#6201]
some IOT ,or  nas like Optimizations or scripts might be of use.. 
with the low ram on the rpi3 , worried about slowing the zfs down ie wait till device is idle for 45 mins or so..   then do de-dupe etc... fs tasks that use considerable ram..... 
zfs can have some ram pork-age.. which could crash things... 

my rootfs isnt on zfs on this device currently ,  however mainly for disk access and prep. 
 I have in mind to acquire a arm64 server..  and use zfs for root on that..  some disk forensics also might be fun.

**Comment by necrose99** [comment]
I'd be happy with a few low RAM /conf file tweaks to keep zfs fast but slow/schedule  some of the back end maintenance tasks till device is more idle/idle for 30+ mins....

**Comment by kpande** [comment]
the [zfs-discuss mailing list](http://list.zfsonlinux.org) is the more appropriate venue for this discussion
