### ISSUE TITLE
spl-dkms fail upon install (Fedora 25, zfs 0.6.5.9-1)

### ISSUE THREAD

**Issue by bitsandbooks** [zfsonlinux/zfs#6206]
While installing ZFS on a fresh, updated Fedora 25 machine, I get a failure during install of `spl-dkms` and `zfs-dkms`. (N.B.: `dkms` already successfully installed.)

Here's the results of `dnf install zfs`:

    Last metadata expiration check: 0:02:39 ago on Thu Jun  8 17:46:17 2017.
    Dependencies resolved.
    ===================================================================================================================================================================================================================
    Package                                            Arch                                             Version                                                   Repository                                     Size
    ===================================================================================================================================================================================================================
    Installing:
    spl                                                x86_64                                           0.6.5.9-1.fc25                                            zfs                                            33 k
    spl-dkms                                           noarch                                           0.6.5.9-1.fc25                                            zfs                                           447 k
    zfs                                                x86_64                                           0.6.5.9-1.fc25                                            zfs                                           348 k
    zfs-dkms                                           noarch                                           0.6.5.9-1.fc25                                            zfs                                           1.9 M
    
    Transaction Summary
    ===================================================================================================================================================================================================================
    Install  4 Packages
    
    Total download size: 2.7 M
    Installed size: 15 M
    Is this ok [y/N]: y
    Downloading Packages:
    (1/4): spl-0.6.5.9-1.fc25.x86_64.rpm                                                                                                                                                92 kB/s |  33 kB     00:00    
    (2/4): zfs-0.6.5.9-1.fc25.x86_64.rpm                                                                                                                                               373 kB/s | 348 kB     00:00    
    (3/4): spl-dkms-0.6.5.9-1.fc25.noarch.rpm                                                                                                                                          527 kB/s | 447 kB     00:00    
    (4/4): zfs-dkms-0.6.5.9-1.fc25.noarch.rpm                                                                                                                                          1.0 MB/s | 1.9 MB     00:01    
    -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    Total                                                                                                                                                                              1.5 MB/s | 2.7 MB     00:01     
    Running transaction check
    Transaction check succeeded.
    Running transaction test
    Transaction test succeeded.
    Running transaction
    Installing  : spl-dkms-0.6.5.9-1.fc25.noarch                                                                                                                                                                 1/4 
    Loading new spl-0.6.5.9 DKMS files...
    Building for 4.11.3-202.fc25.x86_64
    Building initial module for 4.11.3-202.fc25.x86_64
    configure: error: unknown
    Error! Bad return status for module build on kernel: 4.11.3-202.fc25.x86_64 (x86_64)
    Consult /var/lib/dkms/spl/0.6.5.9/build/make.log for more information.
    warning: %post(spl-dkms-0.6.5.9-1.fc25.noarch) scriptlet failed, exit status 10
    Non-fatal POSTIN scriptlet failure in rpm package spl-dkms
    Non-fatal POSTIN scriptlet failure in rpm package spl-dkms
    Installing  : spl-0.6.5.9-1.fc25.x86_64                                                                                                                                                                      2/4 
    Installing  : zfs-dkms-0.6.5.9-1.fc25.noarch                                                                                                                                                                 3/4 
    Loading new zfs-0.6.5.9 DKMS files...
    Building for 4.11.3-202.fc25.x86_64
    Building initial module for 4.11.3-202.fc25.x86_64
    configure: error: 
        *** Please make sure the kmod spl devel <kernel> package for your
        *** distribution is installed then try again.  If that fails you
        *** can specify the location of the spl objects with the
        *** '--with-spl-obj=PATH' option.
    Error! Bad return status for module build on kernel: 4.11.3-202.fc25.x86_64 (x86_64)
    Consult /var/lib/dkms/zfs/0.6.5.9/build/make.log for more information.
    warning: %post(zfs-dkms-0.6.5.9-1.fc25.noarch) scriptlet failed, exit status 10
    Non-fatal POSTIN scriptlet failure in rpm package zfs-dkms
    Non-fatal POSTIN scriptlet failure in rpm package zfs-dkms
    Installing  : zfs-0.6.5.9-1.fc25.x86_64                                                                                                                                                                      4/4 
    Verifying   : zfs-0.6.5.9-1.fc25.x86_64                                                                                                                                                                      1/4 
    Verifying   : spl-0.6.5.9-1.fc25.x86_64                                                                                                                                                                      2/4 
    Verifying   : zfs-dkms-0.6.5.9-1.fc25.noarch                                                                                                                                                                 3/4 
    Verifying   : spl-dkms-0.6.5.9-1.fc25.noarch                                                                                                                                                                 4/4 
    
    Installed:
    spl.x86_64 0.6.5.9-1.fc25                         spl-dkms.noarch 0.6.5.9-1.fc25                         zfs.x86_64 0.6.5.9-1.fc25                         zfs-dkms.noarch 0.6.5.9-1.fc25                        
    
    Complete!

And here's the contents of `/var/lib/dkms/spl/0.6.5.9/build/make.log`:

    DKMS make.log for spl-0.6.5.9 for kernel 4.11.3-202.fc25.x86_64 (x86_64)
    Thu Jun  8 17:49:56 CDT 2017
    make: *** No targets specified and no makefile found.  Stop.

Calling `modprobe zfs` fails because the modules were not successfully built.

**Comment by hesdago** [comment]
As far as I can tell, kernel 4.11 support is only available on pre-release branch: v0.7.0-rc4 for now. 
You can either update to zfs-testing (dnf update --enablerepo=zfs-testing), or stay on kernel version 4.10.17 until the 0.7 zfs release is published as stable.

**Comment by gmelikov** [comment]
4.11 kernel is not supported in 0.6.5.9, you have to wait for 0.6.5.10 or use 0.7.0 (testing). Next time please read package description.
