### ISSUE TITLE
Update github wiki to tell users to provide complete path to "with-spl" configuration option

### ISSUE THREAD

**Issue by ddwo** [zfsonlinux/zfs#6215]
A tip under the "configure and build" section on [this page](https://github.com/zfsonlinux/zfs/wiki/Building-ZFS) tells users to provide the path to a spl directory, but it doesn't mention the requirement of an absolute path ([see here](http://list.zfsonlinux.org/pipermail/zfs-discuss/2013-September/011088.html))

I ran into this issue and fixed it by doing what the mailing list post said to do.

Can someone with privileges update the wiki to reflect this?

**Comment by dinatale2** [comment]
@ddwo, I just updated it. Can you confirm that it's ok now?

**Comment by ddwo** [comment]
Thanks, it looks good now
