### ISSUE TITLE
DKMS modules fail to build on Fedora 25

### ISSUE THREAD

**Issue by revident** [zfsonlinux/zfs#6225]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Fedora
Distribution Version    | 25
Linux Kernel                 | 4.11.3-202.fc25.x86_64
Architecture                 | x86_64
ZFS Version                  | 0.6.5.9-1 / 0.6.5.8-2
SPL Version                  | 0.6.5.9-1 / 0.6.5.8-2

### Describe the problem you're observing

Build of dkms modules fails during rpm install.
This problem showed in somewhere in the last few weeks. I note there was a package update for DKMS in the end of may. Possible upstream bug?

### Describe how to reproduce the problem

On system with Fedora, updated to latest updates.

### Include any warning/errors/backtraces from the system logs

[spl-make.log.txt](https://github.com/zfsonlinux/zfs/files/1072095/spl-make.log.txt)
[zfs-install-terminal.log.txt](https://github.com/zfsonlinux/zfs/files/1072098/zfs-install-terminal.log.txt)
[zfs-make.log.txt](https://github.com/zfsonlinux/zfs/files/1072097/zfs-make.log.txt)

**Comment by kpande** [comment]
this is a distribution issue, 0.6.5.9 doesn't support >4.10, please check the releases page and use [the zfs-discuss mailing list](http://list.zfsonlinux.org) next time.

**Comment by revident** [comment]
That is rude.

1) If it's an upstream issue, then please mark this ticket as upstream, but leave it open so others can search for it and find it when reporting issues. I did in fact search for 'is:issue is:open fedora' before submitting this ticket.

2)  Mailman archives are terrible thing to inflict on a user. It contains no search functionality of it's own, so as a user, unless I was habitually reading, I wouldn't know how to where to look.
Using a Google search is also not helpful 'fedora site:http://list.zfsonlinux.org/pipermail/zfs-discuss/'. Returning only old entries from Fedora 23

3) Be kind and link to the specific thread, considering you already know about it, and mailman archives lack search features.

4) Your ticket template does not list the mailing list as a place to search for know issues. If indeed you feel closing tickets in the manner is appropriate (which frankly it should not have been).

**Comment by kpande** [comment]
i'm sorry you felt it was rude. of course, searching for only open issues for fedora 25 would not return the other numerous reported issues of this exact problem: #6214

**Comment by revident** [comment]
Indeed, all the more reason to leave it open, and add an 'upsteam' label. That would allow you to mark as duplicate, or in my case, I wouldn't have opened the issue in the first place, instead subscribing to the existing #6214.

Closing tickets like this is only creating more work for yourself, closing duplicates.

**Comment by kpande** [comment]
but the issue is resolved. why leave a fixed issue open? use 0.6.5.10. open a bug report with fedora if they don't have it. right?

**Comment by revident** [comment]
I see the dilemma here, In code, yes the issue is fixed, and committed to a version. But as the zfsforlinux project is also responsible for packaging, then from a user perspective, the issue isn't resolved, because that version isn't released as a package yet.

If you weren't also responsible for packaging, then what you say would be reasonable, open a ticket with the Distro to have them update the package to the new version. Tracked separately.

I can say I learned something here, to not limit my searches to only open issues.
But also, there is an opportunity here, to preform better closes, but explicitly linking to the previous issues and/or discussions threads, to explain why it's being closed.

**Comment by kpande** [comment]
ZoL is not responsible for distribution packaging, that is the issue.. thanks for understanding.

**Comment by revident** [comment]
I think you misunderstand. I'm talking the ZFS packages, 0.6.5.10, is not in the main zfs repo yet, those you are responsible for. So when there is a gap between a code release, and packages showing up in download.zfsonlinux.org, where would such an issue be tracked?

**Comment by gmelikov** [comment]
@revident next time please read [the contributing guidelines](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#reporting-bugs ) too, information about mailing lists and searching all issues (not just opened) is here.

I agree with @kpande, the issue is already tracked, and it's searchable.

**Comment by kpande** [comment]
since 0.6.5.10 is still in rc status it is not built for the zfsonlinux.org repo which only handles stable packages. the issue is that Fedora does not block you from updating your kernel with an outdated filesystem version, and we can't fix that.
