### ISSUE TITLE
option -u to zfs receive does not work

### ISSUE THREAD

**Issue by Rudd-O** [zfsonlinux/zfs#624]
When I send a replication stream from a source to a destination, and I specify -u in zfs receive, zfs receive insists on mounting the replicated stream.  Unfortunately, this causes the receive to fail right at its end because it attempts to mount the received dataset atop another dataset that was already mounted.

Latest git tip.

**Comment by mailinglists35** [comment]
I can't test on latest release but on debian jessie version 0.6.4-1b -u is ignored on zfs receive

**Comment by Rudd-O** [comment]
This probably should be reopened in that case.

**Comment by behlendorf** [comment]
Reopening until we can verify it's really fixed.

**Comment by kpande** [comment]
it's working here.
