### ISSUE TITLE
Custom compile on proxmox

### ISSUE THREAD

**Issue by gregfr** [zfsonlinux/zfs#6243]
Greetings

I'm trying to update zfs on an old proxmox server. 
I can compile from source (downloaded today 0.6.5.10),  as I used to do in the past, but a proxmox-provided version of zfs is already installed, and it seems it always take precedence over my custom compile.

Is there a way to disable proxmox version and use the latest custom?

Thanks in advance

greg

### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  proxmox
Distribution Version    |  3.4
Linux Kernel                 |  2.6.32-48-pve
Architecture                 |  x86_64
ZFS Version                  |  0.6.5.7-8_gf1b07c5 -> 0.6.5.10
SPL Version                  |  0.6.5.7-3_g8455153 -> 0.6.5.10

**Comment by bunder2015** [comment]
You'll probably want to have a chat with the proxmox folks.  This is more of a distro issue than a zfs (as a whole) one.

**Comment by gregfr** [comment]
I'm afraid they will tell me my version is out-dated, and they cannot provide an updated version anyway :(

**Comment by mailinglists35** [comment]
>  but a proxmox-provided version of zfs is already installed, and it seems it always take precedence over my custom compile

rmmod the distro-provided modules, insmod your own modules.
put your custom binaries in /usr/local/bin and adjust PATH to look there first.

**Comment by kpande** [comment]
you might have better luck on [the zfs-discuss mailing list](http://list.zfsonlinux.org) for proxmox issues.
