### ISSUE TITLE
ZED does not send mail

### ISSUE THREAD

**Issue by lindhe** [zfsonlinux/zfs#6246]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Ubuntu
Distribution Version    | 16.10 yakkety
Linux Kernel                 | 4.8.0-54-generic
Architecture                 | x86_64
ZFS Version                  | 0.6.5.8-0ubuntu4.2
SPL Version                  | 0.6.5.8-2

#### I can not get ZED to send me mail.
I have installed `s-nail`, `msmtp` and `msmtp-mta` and configured `.msmtprc` properly (both in `/home/andreas`, `/etc/` and `/root/`, just in case). I can send mail manually, for example by `echo 'Message body' | mail -s 'A subject' me@example.com`, both as user `andreas` and as `root`.

#### This is my `/etc/zfs/zed.d/zed.rc`, minus comments:
```
ZED_EMAIL_ADDR="me@example.com"
ZED_EMAIL_PROG="mail"
ZED_EMAIL_OPTS="-s @SUBJECT@ @ADDRESS@"
ZED_NOTIFY_VERBOSE=1
ZED_SYSLOG_TAG="zed"
```

I have restarted the service as well as the machine.

It is possible that this is a packaging issue, so just in case: I _think_ I installed ZFS via the `zfsutils-linux/yakkety-updates` packet (group?).

### Describe how to reproduce the problem
If I run a scrub, nothing happens. I should get an email, right?

### Include any warning/errors/backtraces from the system logs
In my endeavours to try and debug, I've started to look into the related ZED scripts in `/usr/lib/zfs-linux/zfs/zed.d`. I don't know if it's supposed to be possible to run the scripts right from the command line, but it sure does not work.

If I run `/usr/lib/zfs-linux/zfs/zed.d/scrub.finish-notify.sh`, it says:
```
./scrub.finish-notify.sh: 17: .: Can't open /zed-functions.sh
```

And no wonders. That file is not executable. If I `chmod +x zed-functions.sh` and try again, I get squat.

#### Listing of `/usr/lib/zfs-linux/zfs/zed.d`:
```
-rwxr-xr-x 1 root root  532 May 22 18:13 all-debug.sh*
-rwxr-xr-x 1 root root  260 May 22 18:13 all-syslog.sh*
-rwxr-xr-x 1 root root 2.1K May 22 18:13 checksum-notify.sh*
-rwxr-xr-x 1 root root 6.8K May 22 18:13 checksum-spare.sh*
-rwxr-xr-x 1 root root 2.1K May 22 18:13 data-notify.sh*
-rwxr-xr-x 1 root root 2.0K May 22 18:13 generic-notify.sh*
-rwxr-xr-x 1 root root 2.1K May 22 18:13 io-notify.sh*
-rwxr-xr-x 1 root root 6.8K May 22 18:13 io-spare.sh*
-rwxr-xr-x 1 root root 1.7K May 22 18:13 resilver.finish-notify.sh*
-rwxr-xr-x 1 root root 1.7K May 22 18:13 scrub.finish-notify.sh*
-rw-r--r-- 1 root root  11K May 22 18:13 zed-functions.sh
```
_Is it not odd that `zed-functions.sh` is not executable?_

#### Listing of `/etc/zfs/zed.d`:
```
lrwxrwxrwx 1 root root   42 Jan 16 19:45 all-syslog.sh -> /usr/lib/zfs-linux/zfs/zed.d/all-syslog.sh*
lrwxrwxrwx 1 root root   47 Jan 16 19:45 checksum-notify.sh -> /usr/lib/zfs-linux/zfs/zed.d/checksum-notify.sh*
lrwxrwxrwx 1 root root   46 Jan 16 19:45 checksum-spare.sh -> /usr/lib/zfs-linux/zfs/zed.d/checksum-spare.sh*
lrwxrwxrwx 1 root root   43 Jan 16 19:45 data-notify.sh -> /usr/lib/zfs-linux/zfs/zed.d/data-notify.sh*
lrwxrwxrwx 1 root root   41 Jan 16 19:45 io-notify.sh -> /usr/lib/zfs-linux/zfs/zed.d/io-notify.sh*
lrwxrwxrwx 1 root root   40 Jan 16 19:45 io-spare.sh -> /usr/lib/zfs-linux/zfs/zed.d/io-spare.sh*
lrwxrwxrwx 1 root root   54 Jan 16 19:45 resilver.finish-notify.sh -> /usr/lib/zfs-linux/zfs/zed.d/resilver.finish-notify.sh*
lrwxrwxrwx 1 root root   51 Jan 16 19:45 scrub.finish-notify.sh -> /usr/lib/zfs-linux/zfs/zed.d/scrub.finish-notify.sh*
-rw-r--r-- 1 root root 2.6K Jun 18 20:14 zed.rc
lrwxrwxrwx 1 root root   45 May 22 18:13 zed-functions.sh -> /usr/lib/zfs-linux/zfs/zed.d/zed-functions.sh
```

#### Output of `systemctl status zed`:
```
● zed.service - ZFS Event Daemon (zed)
   Loaded: loaded (/lib/systemd/system/zed.service; static; vendor preset: enabled)
   Active: active (running) since Sun 2017-06-18 20:14:28 CEST; 55min ago
     Docs: man:zed(8)
 Main PID: 13771 (zed)
    Tasks: 1 (limit: 4915)
   Memory: 3.7M
      CPU: 171ms
   CGroup: /system.slice/zed.service
           └─13771 /usr/sbin/zed -F

Jun 18 20:14:28 server systemd[1]: Started ZFS Event Daemon (zed).
Jun 18 20:14:28 server zed[13771]: ZFS Event Daemon 0.6.5.8-0ubuntu4.3 (PID 13771)
Jun 18 20:14:28 server zed[13771]: Processing events since eid=19
Jun 18 20:14:37 server zed[13809]: eid=20 class=scrub.start pool=tmppool
```

**Comment by lindhe** [comment]
It appears that even though `msmtp-mta` is installed (creating mappings to make `msmtp` compatible with `mail` syntax), and even though that works in cli, it does not work when zed tries to do it. If I remove `-s @SUBJECT@` from the arguments, it works. But then I get no subject line.

Can I add the subject line to `stdin` instead?

**Comment by gdevenyi** [comment]
Looks like ZED was written assuming "mailx" compatibility, "mail" is quite old, hence missing the subject line option.

https://unix.stackexchange.com/questions/89530/difference-between-mail-and-mailx

**Comment by lindhe** [comment]
You nudged me in just the right direction!

The additions of `msmtp-mta` and `s-nail` (the former providing compatibility mappings and the latter providing `mailx`) do provide the correct interface. The problem was the argument. I just needed to add quotes around the `@SUBJECT@` variable like so:

```
ZED_EMAIL_OPTS="-s '@SUBJECT@' @ADDRESS@"
```

I don't see how this works for anyone else. Surely this must be some kind of type error?
