### ISSUE TITLE
sending a readonly volume

### ISSUE THREAD

**Issue by gregfr** [zfsonlinux/zfs#6252]
Greetings
I have this pool that I can only mount read only. I'm trying to copy it elsewhere, but it seems I can't use "zfs send" because I can't create a snapshot...
How can I send a read-only volume to a remote location?

I found this page: https://www.illumos.org/issues/4368
but I can't see how I can do that.

Thanks in advance

**Comment by kpande** [comment]
hi @gregfr this is unfortunately not the correct place for support requests, you may try IRC (#zfsonlinux @ Freenode) or [the zfs-discuss mailing list](http://list.zfsonlinux.org).
