### ISSUE TITLE
zfs-mount.service Failure Seemingly Due to Line in Step 4.7

### ISSUE THREAD

**Issue by ScottHaney** [zfsonlinux/zfs#6258]
### System information
Type                                | Version/Name
---|---
Distribution Name            | Xenial
Distribution Version         | 16.04
Linux Kernel                    | 4.4.0-81
Architecture                     | x86_64
ZFS Version                    | 0.6.5.6-0ubuntu16
SPL Version                    | 0.6.5.6-0ubuntu4

### Description of Problem and its Solution

After running into some weird issues with the 16.04 root zfs install I found that if I replaced the following line from step 4.7

```
# ln -s mapper/luks1 /dev/luks1
```

with 

```
# ln -s /dev/mapper/luks1 /dev/luks1
```

all seemed to be right with the world again.

One of the issues that I ran into with the original instructions was systemctl was showing that zfs-mount.service had failed. The status for zfs-mount.service was saying something about how it was unable to mount /var/cache because the directory wasn't empty. Another issue was updating grub where it mentioned that /dev/luks1 was an unknown device, which is what led me to the change that I have above.

Since making this change I haven't run into any problems using zfs so far. To me it seems like this might be worth updating in the instructions and I was wondering if anyone else agrees or if there is something else that I should have done.

**Comment by megajocke** [comment]
I followed these instructions roughly when installing my Xenial-on-ZFS box.
https://github.com/zfsonlinux/zfs/wiki/Ubuntu-16.04-Root-on-ZFS

It seems that this step assumes $PWD is /dev (running `cd /dev` before would also work).
I think I probably used the same command as you.

It would be a good idea to change the instruction to use the absolute path as you suggest.

**Comment by behlendorf** [comment]
@rlaager could you look at this.

**Comment by rlaager** [comment]
@megajocke This has nothing to do with $PWD. A relative symlink is relative to its own directory, not the process's CWD. For example:
```
# date > /dev/mapper/foo
# ln -s mapper/foo /dev/foo
# cat /dev/foo
Wed Aug  9 01:09:14 CDT 2017
```

@ScottHaney I'm not entirely sure if this is necessary, but I don't see how the absolute path is any worse. So I made the change.
