### ISSUE TITLE
Typo in dsl_dataset.h

### ISSUE THREAD

**Issue by robert0206liu** [zfsonlinux/zfs#6273]
The parameters `dsl_dataset_t *os` in function prototype `void dsl_dataset_stats(dsl_dataset_t *os, nvlist_t *nv);` in dsl_dataset.h seems to be a typo. `*os` should be changed to `*ds`?
https://github.com/zfsonlinux/zfs/blob/master/include/sys/dsl_dataset.h#L293

BTW, the definition of `dsl_dataset_stats` in dsl_dataset.c is using `*ds`.
https://github.com/zfsonlinux/zfs/blob/master/module/zfs/dsl_dataset.c#L1852

**Comment by behlendorf** [comment]
The `dsl_dataset_sync`, `dsl_dataset_sync_done` and I'm sure other function prototypes have similar harmless typos.  Potentially these could be all be fixed if someone wants to do the cleanup the headers.
