### ISSUE TITLE
zfs receive soft deadlock

### ISSUE THREAD

**Issue by spacelama** [zfsonlinux/zfs#6317]
### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Debian 
Distribution Version    | Debian GNU/Linux 9 (stretch/stable)
Linux Kernel                 | 4.9.0-3-amd64 (4.9.30-1 (2017-06-04))
Architecture                 | amd64
ZFS Version                  | 0.6.5.9-5
SPL Version                  | 0.6.5.9-1

### Describe the problem you're observing

"zfs receive tank8TBext/backuppc@$snapname < $new"
from an ~90GB incremental generated on another system hangs up frequently on the first transfer of the day, straight after an import of tank8TBext, with read IOPs on $new and write IOPs on tank8TBext dropping to zero.

If I run a `zfs list`, zfs disk churns for a bit, finishes the listing, and IOPs briefly goes back into the hundreds then back to 0.  Repeat the zfs list, and disk churns a bit more, IOPs increases then back to 0.  Typically, the third zfs list then allows reading to proceed at 50-80MB/s and IOPs back into a reasonable range.  30 minutes later, I notice zfs receive has locked up again, and IOPs back to 0.  Repeat process until entire zfs receive finishes.

I had the zfs receive in a loop for all the daily incrementals shipped on the disk from remote location, and all subsequent incrementals (smaller in size) read correctly in one go.  At end of process, zfs pool exported again.

This is not an isolated incident - this happened to me last week as well.  That time, same pattern - first incremental after a zfs import kept halting (no progress overnight), `zfs list` revived it, second and subsequent incrementals after zfs import read fine, even though some of those incrementals were larger than the initial failing one.

Incrementals on remote system were generated with zfs=spl=0.6.5.9-1, but with a Debian 4.9.25-1~bpo8+1 (2017-05-19) kernel.

**Comment by spacelama** [comment]
root@weinberg:/home/tconnors# uname -a
Linux weinberg 4.9.0-3-amd64 #1 SMP Debian 4.9.30-1 (2017-06-04) x86_64 GNU/Linux
root@weinberg:/home/tconnors# ps auxww | grep zfs
root     22126  0.0  0.0  63544  2408 pts/10   S+   Aug04   0:00 sudo env PUSER=tconnors bash --login -c  zfs receive tank8TBext/backuppc@20170729
root     22127 13.3  0.0  35248  2216 pts/10   D+   Aug04 539:53 zfs receive tank8TBext/backuppc@20170729
root     27086  0.0  0.0   8060   728 pts/91   S+   11:38   0:00 grep zfs
root@weinberg:/home/tconnors# modinfo zfs
filename:       /lib/modules/4.9.0-3-amd64/updates/dkms/zfs.ko
version:        0.6.5.9-5
license:        CDDL
author:         OpenZFS on Linux
description:    ZFS
srcversion:     42C4AB70887EA26A9970936
depends:        spl,znvpair,zcommon,zunicode,zavl
vermagic:       4.9.0-3-amd64 SMP mod_unload modversions 
...
root@weinberg:/home/tconnors# modinfo spl
filename:       /lib/modules/4.9.0-3-amd64/updates/dkms/spl.ko
version:        0.6.5.9-1
license:        GPL
author:         OpenZFS on Linux
description:    Solaris Porting Layer
srcversion:     48193C257A77A8D29B07FC6
depends:        
vermagic:       4.9.0-3-amd64 SMP mod_unload modversions 
...
root@weinberg:/home/tconnors# echo w > /proc/sysrq-trigger
root@weinberg:/home/tconnors# echo t > /proc/sysrq-trigger
# attached
[syslog-sysrq-trigger-t.txt](https://github.com/zfsonlinux/zfs/files/1203664/syslog-sysrq-trigger-t.txt)

**Comment by bennabiy** [comment]
This is similar to what I experience, but I have not managed to get mine unstuck. It just freezes.

**Comment by gmelikov** [comment]
Probably fixed by https://github.com/zfsonlinux/zfs/commit/9b8407638da71ea9f4afb21375f991869f19811f , feel free to reopen the issue if it's not.
