### ISSUE TITLE
space allocated on cache device underflows

### ISSUE THREAD

**Issue by waltersteinlein** [zfsonlinux/zfs#6320]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  CentOS
Distribution Version    |  7.3.1611
Linux Kernel                 |  3.10.0
Architecture                 | x86_64
ZFS Version                  | 0.7.0-rc4
SPL Version                  | 0.7.0-rc4

The issue described in https://github.com/zfsonlinux/zfs/issues/5583 seems still present in 0.7.0-rc4. <code>zpool iostat <pool> -v</code> still shows 16EiB when a cache drive is full:

```
cache                         -      -      -      -      -      -
  wwn-0x55cd2e404c2814d7   187G  16,0E      0      8  19,3K   434K
```
The reported available space seems to be correct as long as the cache drive is not filled up.
<code>zpool list -v</code> also report an <code>ALLOC</code> value that's bigger than the size of the drive (which seems odd):

```
cache      -      -      -         -      -      -
  wwn-0x55cd2e404c2814d7   186G   187G  16,0E         -     0%   100%
```

**Comment by ahrens** [comment]
I'm pretty sure this was fixed recently.
