### ISSUE TITLE
Fedora 26 / 0.6.5.9 -> 0.6.5.10/11

### ISSUE THREAD

**Issue by virtuallynathan** [zfsonlinux/zfs#6336]
Hi there,

Fedora 26 is out today, I was wondering if/when 0.6.5.10/11 might make it into a Fedora 26 repo?

Thanks,
Nathan

**Comment by virtuallynathan** [comment]
Looks like 0.6.5.9 is in the f26 repo, but 0.6.5.10/11 are not.

**Comment by behlendorf** [comment]
We expect to update the repository today with 0.6.5.11.

**Comment by virtuallynathan** [comment]
Awesome, thanks for the info!
