### ISSUE TITLE
Package new(er) version for Fedora 26

### ISSUE THREAD

**Issue by Trisooma** [zfsonlinux/zfs#6338]
Fedora 26 is released, with a 4.11.8 kernel.
The repository contains version 0.6.5.9 that only supports kernels up to 4.10.

please release the latest stable (0.6.5.11?) version so Fedora users can upgrade to the latest version.

**Comment by behlendorf** [comment]
Closing, see #6336.

**Comment by Trisooma** [comment]
Sorry my bad, is was searching in open issues only :-)
