### ISSUE TITLE
zpool iostat/status -c can call arbitrary scripts

### ISSUE THREAD

**Issue by inkdot7** [zfsonlinux/zfs#6353]
Scripts in arbitrary directories can be called by the `zpool iostat/status -c` option.  Reported in #6121 , this issue just to keep track.

A simple solution might be to disallow any slash in the argument to `-c` ?

Example:
```
root@xcz:/home/htj/zfs# ZPOOL_SCRIPTS_PATH=cmd/zpool/zpool.d/ ZPOOL_SCRIPTS_AS_ROOT=1 cmd/zpool/zpool status -c ../../../../../../../../bin/mktemp
  pool: lcl
 state: ONLINE
  scan: none requested
config:

	NAME         STATE     READ WRITE CKSUM
	lcl          ONLINE       0     0     0
	  sdd4       ONLINE       0     0     0  /tmp/tmp.pkwRZC11bG
	  nvme0n1p4  ONLINE       0     0     0  /tmp/tmp.j9TsCi1yRq

errors: No known data errors
```

**Comment by dinatale2** [comment]
I'm thinking the solution can be to disallow `~`, `/`, and `.` from each command string. The command shouldn't have an extension, should have slashes for a path, and shouldn't be attempting to use the home directory at all.

**Comment by tonyhutter** [comment]
You can call `basename()` on the string to strip out the path.  That would remove the need to strip out any chars.

**Comment by dinatale2** [comment]
@tonyhutter If we use `basename()`, we could potentially give "positive" feedback to those who may incorrectly attempt to override our base scripts (i.e. `~/media` vs `media`). If we look for the right set of characters, we can ignore a command because it may have a path, instead of accidentally running one of our provided scripts.

**Comment by tonyhutter** [comment]
That's true.  Maybe just refuse to run a script if `dirname(script)` returns anything?

**Comment by dinatale2** [comment]
Oh, I like that. I'll try that one. Thanks!

**Comment by kpande** [comment]
so running a script from the cwd is alright? what if the user enters /tmp and creates a script, or in some other writeable dir? can we have a check that the script is owned by root?

**Comment by dinatale2** [comment]
@kpande Long story cut short, by default, a script from the cwd is not alright to execute. There are exceptions, details are below.

A script can only be run when it's in one of the directories in `ZPOOL_SCRIPTS_PATH` (which by default is taken to be `~/.zpool.d:/etc/zfs/zpool.d` if `ZPOOL_SCRIPTS_PATH` is not defined). Default scripts provided by ZFS should already be owned by root. If a user provides a custom `ZPOOL_SCRIPTS_PATH`, it is assumed they have sufficient privilege to run those scripts.

@tonyhutter `dirname()` won't work after all. It can possibly modify the path that is passed to it and there is some special casing which we'd have to account for. I'm falling back to checking for a handful of characters in the cmd string.
