### ISSUE TITLE
4.13 compat: bio->bi_error removed, replaced with bi_status

### ISSUE THREAD

**Issue by DeHackEd** [zfsonlinux/zfs#6355]
Pleaseholder issue for <a href="https://github.com/torvalds/linux/commit/4e4cbee93d5">this commit</a> which changed <a href="https://github.com/torvalds/linux/commit/4e4cbee93d5#diff-bd4811706a8d71334f8f07cc135455eb"><tT>/usr/src/linux/include/linux/blk_types.h</tt></a> and ZFS doesn't build.

Someone in IRC reports their distro packs a "4.12" kernel which includes at least this patch, albeit a less popular distro.

**Comment by behlendorf** [comment]
Proposed patches for review in #6351.

**Comment by DeHackEd** [comment]
This is what I get for checking issues but not pull requests.

Closing as superfluous.
