### ISSUE TITLE
Error messages refer to genhostid utility not available on SUSE

### ISSUE THREAD

**Issue by ofaaland** [zfsonlinux/zfs#6358]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | SUSE
Distribution Version    | 
Linux Kernel                 | 
Architecture                 | 
ZFS Version                  | 0.7.0-rc5
SPL Version                  | 

### Describe the problem you're observing
The `multihost` property in 0.7.0-rc5 requires that the hostid is set to a nonzero value, as ZFS depends on that hostid to prevent a pool from being imported on two systems at the same time.

The `zpool(8)` man page and the error messages instruct the user to create an /etc/hostid file with the `genhostid(1)` utility.

Unfortunately, @adilger reports this utility is not available on SUSE linux.

### Describe how to reproduce the problem
Run `genhostid` on a system with SUSE linux installed.

**Comment by ofaaland** [comment]
Seems like ZFS should provide a script for SUSE users.  It should probably support 3 modes:
* Generate a random hostid
* Use 32 bits from the first attached NIC
* Allow the user to specify the desired value

**Comment by adilger** [comment]
On Jul 17, 2017, at 2:08 PM, Olaf Faaland <notifications@github.com> wrote:
> 
> Seems like ZFS should provide a script for SUSE users. It should probably support 3 modes:
> 
> 	• Generate a random hostid
> 	• Use 32 bits from the first attached NIC
> 	• Allow the user to specify the desired value

I think it makes sense to keep the same functionality as the RHEL version:

GENHOSTID(1)                                                      GENHOSTID(1)

NAME
       genhostid - generate and set a hostid for the current host

SYNOPSIS
       genhostid

DESCRIPTION
       genhostid  generates a random hostid and stores it in /etc/hostid,
       if /etc/hostid does not already exist.

SEE ALSO
       hostid(1), gethostid(2), sethostid(2)

                                                                  GENHOSTID(1)

Cheers, Andreas

**Comment by ofaaland** [comment]
Interestingly, it appears that genhostid on RHEL 6.8 and RHEL 7.3 does not behave as described in the manpage.  It over-writes an existing /etc/hostid file.

I wrote the script to follow the semantics described in the manpage, except that I added the option to specify the desired hostid value.

**Comment by adilger** [comment]
Yes, I observed the same inconsistency with the man page, and the man page behavior to be safer and more correct. There is a bug in the genhostid sanity checking, which makes it appear that they will not overwrite existing /etc/hostid files, but in fact it will always be overwritten. I filed a bug with the upstream package maintainers about this. 

Cheers, Andreas

**Comment by bunder2015** [comment]
I believe this will also be needed for gentoo users, as we don't appear to have `genhostid` either.  I'm wondering if this is a RH/EL/CentOS program only...
