### ISSUE TITLE
mount points and shares differ

### ISSUE THREAD

**Issue by Averelll** [zfsonlinux/zfs#6361]
Hi,

I imported a pool from my old server, all went well, even the same mount points were resolved automatically, but somehow zfs tries to share different directories:

mount shows:
lake on /lake type zfs (rw,xattr,noacl)
lake/data on /zfs_data type zfs (rw,xattr,noacl)
lake/important on /zfs_important type zfs (rw,xattr,noacl)

zfs get sharesmb: 
NAME            PROPERTY  VALUE     SOURCE
lake            sharesmb  off       local
lake/data       sharesmb  off       local
lake/important  sharesmb  off       local

so zfs tries to share the pool names, and not the mount points, leading to:

[FAILED] Failed to start ZFS file system shares.

systemctl status zfs-share.service
? zfs-share.service - ZFS file system shares
   Loaded: loaded (/lib/systemd/system/zfs-share.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2017-07-17 23:56:36 CEST; 8h ago
  Process: 1488 ExecStart=/sbin/zfs share -a (code=exited, status=1/FAILURE)
  Process: 1462 ExecStartPre=/usr/bin/rm -f /etc/dfs/sharetab (code=exited, status=203/EXEC)
 Main PID: 1488 (code=exited, status=1/FAILURE)

Jul 17 23:56:36 homerus systemd[1]: Starting ZFS file system shares...
Jul 17 23:56:36 homerus zfs[1488]: cannot share 'lake/data': share(1M) failed
Jul 17 23:56:36 homerus zfs[1488]: cannot share 'lake/important': share(1M) failed
Jul 17 23:56:36 homerus systemd[1]: zfs-share.service: Main process exited, code=exited, status=1/FAILURE
Jul 17 23:56:36 homerus systemd[1]: Failed to start ZFS file system shares.
Jul 17 23:56:36 homerus systemd[1]: zfs-share.service: Unit entered failed state.
Jul 17 23:56:36 homerus systemd[1]: zfs-share.service: Failed with result 'exit-code'.

Running on Debian Stretch, with the official repositories:
modinfo zfs | grep -iw version
version:        0.6.5.9-5
modinfo spl | grep -iw version 
version:        0.6.5.9-1

**Comment by loli10K** [comment]
> so zfs tries to share the pool names, and not the mount points, leading to:

This doesn't seem right: the error message you posted is from NFS sharing, not SMB sharing. It's likely you have set `sharenfs=on`on those datasets.

To be honest i don't think this is a ZFS bug.
