### ISSUE TITLE
zfs recv -x and -o fail when property is invalid (missing)

### ISSUE THREAD

**Issue by prometheanfire** [zfsonlinux/zfs#6371]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | gentoo
Distribution Version    | updated
Linux Kernel                 | 4.9
Architecture                 | x86_86
ZFS Version                  |  probably around 0.7.0rc2
SPL Version                  |  same time period

### Describe the problem you're observing

    # zfs send -Lecp storage-pool/remote-backups/vm01-vms/usr@local-backup-201707091859 | zfs recv -duvF -o mountpoint=none backup04-zp00/backups
    receiving full stream of storage-pool/remote-backups/vm01-vms/usr@local-backup-201707091859 into backup04-zp00/backups/remote-backups/vm01-vms/usr@local-backup-201707091859
    cannot receive new filesystem stream: property 'mountpoint' does not apply to datasets of this type

I'd like to be able to use a simple script to sync backup to an external drive (offsite) and just exclude mountpoint in either the send or recv if the property exists or not

### Describe how to reproduce the problem
use `recv -x mountpoint` on a volume

**Comment by loli10K** [comment]
> use recv -x mountpoint on a volume

I've seen the word "volume" misused sometimes to describe filesystems (or datasets), i'm asking just to be sure: is this a ZVOL you're trying to receive?

**Comment by prometheanfire** [comment]
Yes, a zvol, the actual script, simply masks the mountpoint attribute on ALL recvs, including zvols.

**Comment by loli10K** [comment]
This is to be expected, "mountpoint" is **not** a valid ZVOL property:

```
root@linux:~# zfs get type testpool/zvol 
NAME           PROPERTY  VALUE   SOURCE
testpool/zvol  type      volume  -
root@linux:~# zfs set mountpoint=none testpool/zvol 
cannot set property for 'testpool/zvol': 'mountpoint' does not apply to datasets of this type
```

To send/recv volumes you probably want "volmode" instead, which recently landed in 0.7.0-rc5 (https://github.com/zfsonlinux/zfs/commit/cf8738d85374f51298a0872bcd58257bbb4fda6d): 

```
The volmode property may be set to control the visibility of ZVOL
block devices.

This allow switching ZVOL between three modes:
   full - existing fully functional behaviour (default)
   dev  - hide partitions on ZVOL block devices
   none - not exposing volumes outside ZFS

Additionally the new zvol_volmode module parameter can be used to
control the default behaviour.

This functionality can be used, for instance, on "backup" pools to
avoid cluttering /dev with unneeded zd* devices.
```

**Comment by prometheanfire** [comment]
ya, I'm aware that mountpoint is an invalid property for zvols, didn't know about the new zvol_volmode thing, which is nice as well (and I'll start using it whenever I update).

What I was looking for is for zfs recv to ignore the unsetting of properties that don't exist, instead of erroring as it does now.

**Comment by loli10K** [comment]
>What I was looking for is for zfs recv to ignore the unsetting of properties that don't exist, instead of erroring as it does now.

Use `zfs send -R`: it doesn't really make much sense to ignore invalid `-x|-o` options specifically set from the command line for a single dataset.

**Comment by prometheanfire** [comment]
I was using `zfs send -p` (because -R doesn't work if you've removed a couple of datasets snapshots, it assumes all child datasets have that snapshot).  I was basically looking to send everything, but ignore one or two properties.

**Comment by loli10K** [comment]
> I was basically looking to send everything, but ignore one or two properties.

With `zfs send -R` we're going to ignore invalid properties because we could have different dataset types (filesystems and volumes) in the same send stream, but for a single dataset you're expected to know the destination type: why can't you omit the invalid properties from the command line? Just "ignoring" an option you specifically asked to be applied doesn't look good.

**Comment by prometheanfire** [comment]
can you send a replication stream of a single dataset?  I can't do it for the whole pool because the whole pool isn't snapshotted, some datasets have had their snapshots removed (cache, replaceable data, etc) and a send -R on a pool like that doesn't work.  see https://github.com/zfsonlinux/zfs/issues/5196 for more info on that.

edit:

I can confirm that a replication stream does work for a single dataset, so I'll use `--replicate` instead of `--props`.

tested with both the following with success.

    zfs send -LecR storage-pool/remote-backups/vm01-vms/usr@local-backup-201707091859 | zfs recv -duvF -o mountpoint=none backup04-zp00/backups-test

and

    zfs send -LecR storage-pool/remote-backups/vm01-vms/usr@local-backup-201707091859 | zfs recv -duvF -x mountpoint backup04-zp00/backups-test

where `storage-pool/remote-backups/vm01-vms/usr` is a volume

the problem then becomes `--replicate` sends all child snapshots (older snapshots of the same dataset) when I only want the one, I will move on to doing incrementals but the initial sync is a bit ineffecient.

**Comment by loli10K** [comment]
> send -R on a pool like that doesn't work. see #5196 for more info on that.

I know, if you remember we tried to fix that but didn't succeed. You can still cherry-pick my old PR in your local overlay if you need it.

> I can confirm that a replication stream does work for a single dataset, so I'll use --replicate instead of --props.

You could also avoid using `-x|-o mountpoint` when receiving a ZVOL. Anyway, glad it worked out for you in the end.
