### ISSUE TITLE
Improper thread usage in ztest

### ISSUE THREAD

**Issue by tcaputi** [zfsonlinux/zfs#6377]
### Describe the problem you're observing

For as long as I can remember working on ZFS, I've noticed that buildbot occasionally hits an assertion in ztest where a thread seems to run without returning `TS_MAGIC` when we attempt to join it. After getting one such core dump on my VM i took a bit of time to look into it and discovered that it seems to be causes by a race condition in our use of the thread control functions.

Currently, ztest calls `zk_thread_create()` for each of the worker threads. This function returns a `kthread_t *`, which we dereference to get the thread id.  However, `zk_thread_exit()` will automatically free this struct when the thread completes. Therefore, if the thread completes very quickly, it is possible for the `kthread_t` to be freed before we can dereference the thread id. This usually results in us storing a bad thead id which fails to be joined later.

This seems to be the primary cause of the problem, but I've noticed a few other things as well (some are fairly trivial). To summarize everything in one place, these are the problems that seem to exist with the userspace usage of the thread code:

1. ztest.c should not attempt to dereference the `kthread_t` pointer returned by `zk_thread_create()` if it might be freed before we can get to it. In the kernel, we get around this by holding a lock when creating the thread, and requiring the thread to hold the same lock before it completes. In Illumos, they use the `thr_create()` function here which returns a thread id (similar to pthreads) instead of a struct to dereference. Either method might be appropriate here.
2. ztest.c should probably use the `thread_create()` instead of `zk_thread_create()` for code consistency.
3. For abstraction purposes, it probably isn't great that the `zk_thread_create()` takes pthread-specific flags (in this case `PTHREAD_CREATE_JOINABLE`).

### Describe how to reproduce the problem

The problem occurs fairly rarely on buildbot runs.

### Include any warning/errors/backtraces from the system logs

From `ztest.out`
```starting main threads...
ret == (void *)0x72f158ab4261e538ull (0x1  0x7fd3b8c1e498)
ASSERT at kernel.c:222:zk_thread_join()/media/sf_projects/zfs_crypto/zfs-datto/cmd/ztest/.libs/lt-ztest[0x4091db]
```

I will paste a backtrace if I notice one come up on buidlbot.

**Comment by tuxoko** [comment]
Interesting. I did a quick glance, but I don't see why we need to return the structure at all.
Perhaps we should make it a pseudo structure and return tid as pointer value.

**Comment by tcaputi** [comment]
I think it was done just to match the Illumos kernel's thread creation logic. That seems kind of silly here though, since even Illumos doesn't use their own thread framework here.

**Comment by behlendorf** [comment]
> I think it was done just to match the Illumos kernel's thread creation logic.

Right.  This was done at the time to minimize any differences but it was always an ugly, but expedient, solution for user space.

I'm in favor of all your suggestions above and would love to see this improved.  The approach talked about at the last OpenZFS Developer Day was to introduce a compatibility layer which was flexible enough to work correctly across all OpenZFS platforms.  The new proposed thread interfaces were as follows.  There was a proposed initial patch for DelphixOS which needed to be updated for Linux to verify this interface will work for us.

```c
typedef uint64_t zthread_id_t;
typedef enum thrtype {
       THR_CURPROC,
       THR_GLOBAL
} zk_thrtype_t;

zthread_id_t zk_thread_create(void (*)(), void *, zk_thrtype_t);
zthread_id_t zk_thread_create_v(void (*)(), void *, zk_thrtype_t, uint64_t,
    pri_t);
void zk_thread_join(zthread_id_t);
void zk_thread_exit();
zthread_id_t zk_curthread();
```
