### ISSUE TITLE
Test case: mmp_active_import

### ISSUE THREAD

**Issue by dinatale2** [zfsonlinux/zfs#6406]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | All
Distribution Version    | All
Linux Kernel                 | All
Architecture                 | All
ZFS Version                  | 0.7.0-rc5
SPL Version                  | 0.7.0-rc5

### Describe the problem you're observing
mmp_active_import occasionally fails on buildbot builders. `pgrep` exits with a return code of 1 indicating that `ztest` stopped running.

### Describe how to reproduce the problem
Reproducible by buildbot.

### Include any warning/errors/backtraces from the system logs

http://build.zfsonlinux.org/builders/Ubuntu%2014.04%20i686%20%28TEST%29/builds/3095/steps/shell_8/logs/log

```
Test: /usr/share/zfs/zfs-tests/tests/functional/mmp/mmp_active_import (run as root) [00:19] [FAIL]
18:47:28.32 ASSERTION: multihost=on|off active pool activity checks
18:47:28.35 SUCCESS: mkdir -p /var/tmp/mmp
18:47:28.36 SUCCESS: truncate -s 268435456 /var/tmp/mmp/vdev1 /var/tmp/mmp/vdev2
18:47:28.37 SUCCESS: mmp_clear_hostid
18:47:28.39 SUCCESS: mmp_set_hostid 01234567
18:47:28.56 SUCCESS: zpool create -f mmppool mirror /var/tmp/mmp/vdev1 /var/tmp/mmp/vdev2
18:47:28.63 SUCCESS: zpool set multihost=on mmppool
18:47:28.71 SUCCESS: zpool export mmppool
18:47:28.73 SUCCESS: mmp_clear_hostid
18:47:28.75 SUCCESS: mmp_set_hostid 89abcdef
18:47:28.75 NOTE: Starting ztest in the background as hostid 01234567
18:47:28.76 SUCCESS: eval ZFS_HOSTID=01234567 ztest -T120 -M -k0 -f /var/tmp/mmp -E -p mmppool >/dev/null 2>&1 &
18:47:28.91 14636
18:47:28.91 14640
18:47:28.92 SUCCESS: pgrep ztest
18:47:33.61 SUCCESS: sleep 5
18:47:47.12 ERROR: pgrep ztest exited 1
```

**Comment by behlendorf** [comment]
@adilger yup this was fixed.  Thanks, closing!

**Comment by nabakishore** [comment]
I see the issue even after excluding ztest_reguid() from mmp test running in loop.
I get following error in ztest

`test: No pools found err=2

/usr/sbin/ztest[0x409b2a]
/lib64/libpthread.so.0(+0xf5f0)[0x7f30c4f6b5f0]
/lib64/libc.so.6(gsignal+0x37)[0x7f30c4bc4337]
/lib64/libc.so.6(abort+0x148)[0x7f30c4bc5a28]
/usr/sbin/ztest[0x409611]
/usr/sbin/ztest[0x40899a]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f30c4bb0505]
/usr/sbin/ztest[0x40937d]
child died with signal 6
`
