### ISSUE TITLE
0.7.0 release tarball missing some man pages

### ISSUE THREAD

**Issue by bunder2015** [zfsonlinux/zfs#6409]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | all
Distribution Version    | na
Linux Kernel                 | na
Architecture                 | na
ZFS Version                  | 0.7.0
SPL Version                  | 0.7.0

### Describe the problem you're observing
It appears the 0.7.0 release tarball is missing files, eg the man pages for ~zfs~zstreamdump, zpool and zinject
### Describe how to reproduce the problem
Download [tarball](https://github.com/zfsonlinux/zfs/releases/download/zfs-0.7.0/zfs-0.7.0.tar.gz) and unpack

**Comment by fearedbliss** [comment]
zfs exists. zpool, zinject, and zstreamdump appear to be missing. At least from the list of man pages that I've been monitoring. A more comprehensive search should probably be done to make sure there isn't anything else we are missing.

**Comment by bunder2015** [comment]
Found out why...  https://github.com/zfsonlinux/zfs/blob/master/man/man8/Makefile.am#L7

**Comment by demizer** [comment]
Is a new stable release going to be made to include the fix? I am seeing this issue when building for Arch Linux.

**Comment by behlendorf** [comment]
@demizer yes.  You'll want to cherry pick that commit for the moment if you're building from git.  The posted tarballs have been updated to include the tiny fix.

**Comment by siebenmann** [comment]
For the record, this also affects RPMs built from the current git tree.

**Comment by charlesmilette** [comment]
Also affects users installing from zfs-dkms-git with the Arch Linux AUR

**Comment by devZer0** [comment]
i reinstalled via yum on centos today, but the issue remains - maybe the build in the yum repo has not been updated!?

[root@rx300-1 var]# rpm -q -i zfs
Name        : zfs
Version     : 0.7.0
Release     : 1.el7_3
Architecture: x86_64
Install Date: Fr 04 Aug 2017 12:33:28 CEST
Group       : System Environment/Kernel
Size        : 1029322
License     : CDDL
Signature   : RSA/SHA256, Mi 26 Jul 2017 20:02:17 CEST, Key ID a9d5a1c0f14ab620
Source RPM  : zfs-0.7.0-1.el7_3.src.rpm
Build Date  : Mi 26 Jul 2017 19:55:28 CEST
Build Host  : fedora-24-repo
Relocations : (not relocatable)
URL         : http://zfsonlinux.org/
Summary     : Commands to control the kernel modules and libraries
Description :
This package contains the ZFS command line utilities.

[root@rx300-1 var]# man zpool
Kein Handbucheintrag für zpool vorhanden

**Comment by behlendorf** [comment]
The CentOS package should get an update early next week with this fix and a few others.
