### ISSUE TITLE
Error when building zfs 0.7.0: implicit declaration of function ‘__spl_pf_fstrans_check’

### ISSUE THREAD

**Issue by SenH** [zfsonlinux/zfs#6412]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Ubuntu
Distribution Version    | 12.04.5 LTS
Linux Kernel                 | 3.13.0-110-generic
Architecture                 | x86_64
ZFS Version                  | zfs-0.7.0-1
SPL Version                  | zfs-0.7.0-1

### Describe the problem you're observing

Following error message is returning after executing make and build fails.
zfs 0.7.0-rc3 was still building fine on this system.

Maybe related to these changes? 
#6113 
zfsonlinux/spl#614

### Describe how to reproduce the problem
```
./autogen.sh
./configure
make
```
### Make error output
```
Making all in module
  CC [M]  /home/sen/development/zol-master/zfs/module/zfs/vdev_file.o
/home/sen/development/zol-master/zfs/module/zfs/vdev_file.c: In function ‘vdev_file_io_start’:
/home/sen/development/zol-master/zfs/module/zfs/vdev_file.c:216:4: error: implicit declaration of function ‘__spl_pf_fstrans_check’ [-Werror=implicit-function-declaration]
cc1: some warnings being treated as errors
make: *** [all] Error 2
```

**Comment by SenH** [comment]
Setting spl dir manually with `./configure --with-spl=../spl/` fixed the make error.  Otherwise the spl include dir would have been `/usr/src/spl-0.7.0` which didn't include the zfsonlinux/spl#614 changes.

Is it good practice to manually specify the spl dir when recompiling a new version?

**Comment by behlendorf** [comment]
Generally it's a good idea to explicitly set `--with-spl` when building.  We're going to address this in the next release by pulling the spl in to the zfs repository to avoid this kind of problem entirely.
