### ISSUE TITLE
"zfs: Unknown symbol __udivmoddi4" with gcc-7 and 32bit

### ISSUE THREAD

**Issue by woffs** [zfsonlinux/zfs#6417]
### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | archlinux
Distribution Version    | 
Linux Kernel                 | 4.9.11
Architecture                 | i386
ZFS Version                  | 0.7.0
SPL Version                  | 0.7.0

### Describe the problem you're observing
modprobe zfs
causes
``zfs: Unknown symbol __udivmoddi4 (err 0)``
in dmesg

### Describe how to reproduce the problem
compile and install zfs-dkms-git from archlinux-aur on a 32bit system

This is apparently related to gcc-7 on 32bit only.

**Comment by loli10K** [comment]
Illumos is having a similar issue: https://www.illumos.org/issues/8500 (loader: need __divmoddi4 and __udivmoddi4).

We could ship `__divmoddi4`/`__udivmoddi4` with the SPL like it was done for `__udivdi3`.

**Comment by behlendorf** [comment]
> We could ship __divmoddi4/__udivmoddi4 with the SPL like it was done for __udivdi3.

Yes, that's going to be the cleanest fix.  The alternative will be invasive changes to the core ZFS code.
