### ISSUE TITLE
zfs-0.7.0: multiple definition of blk_set_runtime_active

### ISSUE THREAD

**Issue by osti** [zfsonlinux/zfs#6420]
Currently I am deploying zfs-0.7.0 on some Gentoo machines; on two I was successful, whil on the third I cannot compile (or better, link) the kernel module.

### System information
Distribution Name       | Gentoo
Distribution Version    | N/A
Linux Kernel                 | 4.8.17-hardened-r2
Architecture                 | amd64
ZFS Version                  | 0.7.0 (upgrading from 0.6.5.11-r0-gentoo)
SPL Version                  | 0.7.0-r0-gentoo (upgrade successful)
GCC version | 5.4.0-r3

### Describe the problem you're observing
```
LD [M]  /var/tmp/portage/sys-fs/zfs-kmod-0.7.0/work/zfs-0.7.0/module/unicode/zunicode.o
/var/tmp/portage/sys-fs/zfs-kmod-0.7.0/work/zfs-0.7.0/module/unicode/uconv.o: In function `blk_set_runtime_active':
(.text+0xde0): multiple definition of `blk_set_runtime_active'
/var/tmp/portage/sys-fs/zfs-kmod-0.7.0/work/zfs-0.7.0/module/unicode/u8_textprep.o:(.text+0x2700): first defined here
make[6]: *** [/usr/src/linux-4.8.17-hardened-r2/scripts/Makefile.build:427: /var/tmp/portage/sys-fs/zfs-kmod-0.7.0/work/zfs-0.7.0/module/unicode/zunicode.o] Error 1
make[5]: *** [/usr/src/linux-4.8.17-hardened-r2/scripts/Makefile.build:440: /var/tmp/portage/sys-fs/zfs-kmod-0.7.0/work/zfs-0.7.0/module/unicode] Error 2
make[5]: *** Waiting for unfinished jobs....
```
and then the same error (multi defi of blk_set_runtime_active) for more LD steps...

### Describe how to reproduce the problem
emerge =sys-fs/zfs-kmod-0.7.0

**Comment by bunder2015** [comment]
can you try 9999?  they should be identical (for the time being), but i'm curious to see if this is a packaging issue with the tarball used for specific releases.

**Comment by osti** [comment]
Sorry, but it looks quite the same.
Yet I could re-compile it on a different system.

**Comment by behlendorf** [comment]
This is pretty strange since ZFS doesn't use `blk_set_runtime_active()`.  Perhaps we're picking up two different kernel headers somewhere which define this function?

**Comment by osti** [comment]
update: vanilla from git repo seems to work; I will further investigate this evening (UTC+2).

**Comment by osti** [comment]
Sorry for all that noise: after changing nothing (yes, really...) it ... works. No idea, why.
