### ISSUE TITLE
Missing /dev/zvol after upgrade to ZFS 0.7.0 in Fedora 26

### ISSUE THREAD

**Issue by danielkza** [zfsonlinux/zfs#6428]
### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Fedora
Distribution Version    |  26
Linux Kernel                 | 4.11.11-300.fc26
Architecture                 | x86_64
ZFS Version                  | zfs-0.7.0-1.fc26.x86_64
SPL Version                  | spl-0.7.0-1.fc26.x86_64

### Describe the problem you're observing

/dev/zvol is completely missing after a ZFS upgrade.

### Describe how to reproduce the problem

Upgrade to ZFS 0.7.0 caused immediate disappearance of the directory. Unfortunately I already ran a zpool upgrade before noticing the issue, hence cannot downgrade to easily verify if anything changes.

### Include any warning/errors/backtraces from the system logs

Unfortunately there seem to be no interesting messages in the system logs, other than ones from `libvirt` complaining about the missing zvol dir:

```
jul 29 17:10:20 daniel-pc libvirtd[16054]: 2017-07-29 20:10:20.861+0000: 16360: error : virDirOpenInternal:2810 : cannot open directory '/dev/zvol/daniel-pc-media/vm': No such file or directory
jul 29 17:10:20 daniel-pc libvirtd[16054]: 2017-07-29 20:10:20.861+0000: 16360: error : storageDriverAutostart:227 : internal error: Failed to autostart storage pool 'zvols': cannot open directory '/dev/zvol/daniel-pc-media/vm': No such file or directory
```

**Comment by danielkza** [comment]
It seems there was an issue when generating the initramfs after the upgrade that caused the ZFS modules contained there to differ from the ZFS utilities versions. After a manual re-generation everything seems to be working correctly.

Any idea of what could cause such discrepancies?

**Comment by bunder2015** [comment]
I was starting to think this was a udev problem, but I'm glad you were able to get it sorted.  FWIW, I didn't have any problems with zvols when I upgraded on gentoo.
