### ISSUE TITLE
zfs-mount.service WorkingDirectory ignored (Not an absolute path)

### ISSUE THREAD

**Issue by LnxGnome** [zfsonlinux/zfs#6429]
### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  CentOS
Distribution Version    |  7.3
Linux Kernel                 |  3.10.0-514.26.2
Architecture                 | x86_64
ZFS Version                  | 0.7.0-1
SPL Version                  | 0.7.0-1

### Describe the problem you're observing
Seen in journalctl output:
systemd[1]: [/usr/lib/systemd/system/zfs-mount.service:14] Not an absolute path, ignoring: -/sbin/

### Describe how to reproduce the problem
Install ZFS on CentOS 7.3 (this system was upgraded from 0.6.5)

### other info
man systemd.exec
WorkingDirectory=
    Takes an absolute directory path. Sets the working directory for executed processes. If not set, defaults to the root directory when systemd is running as a system instance and the respective user's home directory if run as user.

**Comment by loli10K** [comment]
https://www.freedesktop.org/software/systemd/man/systemd.exec.html#WorkingDirectory=

> WorkingDirectory=

> Takes a directory path relative to the service's root directory specified by RootDirectory=, or the special value "~ ". Sets the working directory for executed processes. If set to "~", the home directory of the user specified in User= is used. If not set, defaults to the root directory when systemd is running as a system instance and the respective user's home directory if run as user. **If the setting is prefixed with the "-" character, a missing working directory is not considered fatal**. If RootDirectory=/RootImage= is not set, then WorkingDirectory= is relative to the root of the system running the service manager. Note that setting this parameter might result in additional dependencies to be added to the unit (see above).

**Comment by loli10K** [comment]
This _may be_ a systemd bug introduced in https://github.com/systemd/systemd/commit/7b07e99320586fa3baf3e6cbb374f06c6ddc47d8.

@LnxGnome which systemd version is your system running?

**Comment by LnxGnome** [comment]
systemd-219-30.el7_3.9.x86_64

**Comment by loli10K** [comment]
Reproduced on CentOS7, cannot reproduce on Debian8 (systemd-215-17) or Sid (sytemd-234-2).

Also the "~" character doesn't seem to be accepted too:

```
centos systemd[1]: [/usr/lib/systemd/system/zfs-mount.service:15] Not an absolute path, ignoring: ~
```

Sorry but this doesn't seem a ZFS bug, maybe it's better to report this to your distro maintainer?

**Comment by LnxGnome** [comment]
Looks like that functionality was introduced into systemd @ https://github.com/systemd/systemd/commit/5f5d8eab1f2f5f5e088bc301533b3e4636de96c7 (Sep 23, 2015), which would make it part of the v227 release of systemd (Oct 7, 2015).  CentOS is on v219, so it would not be present.

**Comment by loli10K** [comment]
@LnxGnome you're right, i had erroneously assumed CentOS had this functionality backported. Debian Jessie comes with systemd v215 but seems to support both "-" and "~".

**Comment by behlendorf** [comment]
Is there a simple proposed for the older versions of systemd.

**Comment by LnxGnome** [comment]
Don't set it.  "If not set, defaults to the root directory when systemd is running as a system instance..."  
Since ExecStart is an absolute path, is there a reason to set it to /sbin?

**Comment by behlendorf** [comment]
@LnxGnome this was done originally to work around some undesirable behavior in `mount(8)`, commit d32d25c5c26c8d1e254bc0fcb8a8ae059e95cebc.  We need to make sure the cwd is not root, in fact an empty directory would be best, to avoid a specific  type of mount failure.

**Comment by LnxGnome** [comment]
Dropping the "-" is the next most straightforward solution.  /sbin should be there.
@sbindir@ might be an alternative, which from the rpm.spec is /sbin.
If you leave it as-is, then (has error, defaults to back /) doesn't that reintroduce the chance of undesirable behavior that https://github.com/zfsonlinux/zfs/commit/d32d25c5c26c8d1e254bc0fcb8a8ae059e95cebc is supposed to avoid?
