### ISSUE TITLE
Add systemd setup to "Ubuntu ZFS mountall FAQ and troubleshooting" wiki page

### ISSUE THREAD

**Issue by krichter722** [zfsonlinux/zfs#6431]
### Describe the problem you're observing
The [Ubuntu ZFS mountall FAQ and troubleshooting](https://github.com/zfsonlinux/zfs/wiki/Ubuntu-ZFS-mountall-FAQ-and-troubleshooting) wiki page mentions the configuration involving the deprecated Ubuntu PPA and `upstart` which is no longer the default the init manager in 17.04 (maybe earlier). It'd be appreciated if that'd be differentiated in the wiki. I'd be appreciated as well if information for a source installation (discouraged for beginners, but still interesting) would be provided or linked.

I'm looking for information

  * how to deal with the built-in kernel modules (after installing from source, I'm deleting `/lib/modules/[version]/kernel/zfs` and running `depmod -a`, but that might be wrong and only work by accident).
  * how to make `systemd` units depend on mountpoints (`xy.mount` only seems available after the mount happened with `zfs mount`; maybe there's a better dependency).

If information for `systemd` can be found for other OS they should be separated or be linked without too much redundancy.

Please note that this is not a support request - I'd like to see this fixed for anybody instead of just me because I think it concerns a large audience and up-to-date information make a good impression on users.

**Comment by rlaager** [comment]
This page no longer exists.
