### ISSUE TITLE
dracut module does not install all dependencies of vdev_id

### ISSUE THREAD

**Issue by kkretschmer** [zfsonlinux/zfs#6443]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Gentoo
Distribution Version    | 2017-08-01
Linux Kernel                 | 4.9.34-gentoo
Architecture                 | x86_64
ZFS Version                  | v0.7.0-r0-gentoo
SPL Version                  | v0.7.0-r0-gentoo

### Describe the problem you're observing
The ZFS dracut module does not ensure the installation of all commands required by the [`vdev_id` ](/zfsonlinux/zfs/blob/master/cmd/vdev_id/vdev_id)script.  In particular, `awk`, `grep`, and `head` are required, but [`contrib/dracut/90zfs/module-setup.sh.in`](/zfsonlinux/zfs/blob/master/contrib/dracut/90zfs/module-setup.sh.in) only installs `grep` explicitly.  On my system, no other dracut module installs them, at least in host-only mode.  As a result, the links in /dev/disk/by-vdev are missing in the initrd environment.

As a workaround, I added `/etc/dracut.conf.d/zfs.conf` with the content
```
install_items+="awk grep head"
```
This is sufficient for correct operation of `vdev_id`.  I suggest that `contrib/dracut/90zfs/module-setup.sh.in` should also do `dracut_install awk` and `dracut_install head`.

### Describe how to reproduce the problem
lsinitrd /boot/initramfs-x86_64-4.9.34-gentoo.img | grep -E 'awk|grep|head'

**Comment by behlendorf** [comment]
Thanks for the detailed issue, it would be great to get a PR opened with a proposed fix for review.  Let's get @Rudd-O thoughts on this as well.

**Comment by Rudd-O** [comment]
LGTM.
