### ISSUE TITLE
Unable to run zfs command lines under zfs revision 0.7

### ISSUE THREAD

**Issue by aasraoui** [zfsonlinux/zfs#6456]
we have installed zfs 0.7 via DKMS and don't seem to have the cli in this version:
installed software release:
dkms status
lustre, 2.10.0, 3.10.0-514.21.1.el7_lustre.x86_64, x86_64: installed
spl, 0.7.0, 3.10.0-514.21.1.el7_lustre.x86_64, x86_64: installed
zfs, 0.7.0, 3.10.0-514.21.1.el7_lustre.x86_64, x86_64: installed

e.g missing clis:

 zpool list
-bash: zpool: command not found

thanks,
AA

**Comment by kpande** [comment]
this is a configuration issue and as such is better suited for [the zfs-discuss mailing list](http://list.zfsonlinux.org)
