### ISSUE TITLE
zfs send size estimation apparently inaccurate

### ISSUE THREAD

**Issue by devZer0** [zfsonlinux/zfs#6462]
see https://github.com/jimsalterjrs/sanoid/issues/122#issuecomment-320231908 , is that problem solvable zfs upstream ?

it`s very dissatisfying to have a zfs sync tool report "i`m at 53%" and then be suddenly finish or it is trespassing 100% and then needs for another >200% to finish.

know that from windows progress bars....and it sucks....

**Comment by kpande** [comment]
did you read `CONTRIBUTING.md` or even the template you seemingly completely ignored before submitting the issue? this is a question better asked on [the zfs-discuss mailing list](http://list.zfsonlinux.org).
