### ISSUE TITLE
zdb fails to locate datasets within exporting zfs pool with '-e -p' options

### ISSUE THREAD

**Issue by jxiong** [zfsonlinux/zfs#6464]
zdb prior to zfs 0.7.0 is able to get information of a dataset in zfs pool by '-e -p' as following:

```zdb -e -p /tmp -u lustre-ost1/ost1```

where 'ost1' is a dataset within zfs pool 'lustre-ost1'.

The information of zfs pool is as follows:
```
[root@centos7 tests]# zpool list lustre-ost1 -v
NAME   SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
lustre-ost1   384M  1.92M   382M         -     1%     0%  1.00x  ONLINE  -
  /tmp/lustre-ost1   384M  1.92M   382M         -     1%     0%
```

it doesn't work any more in zfs 0.7.0:
```
[root@centos7 tests]# zdb -e -p /tmp -u lustre-ost1/ost1
failed to own dataset 'lustre-ost1/ost1': No such file or directory
zdb: can't open 'lustre-ost1/ost1': No such file or directory
```
However, it works to check zfs pool directly:
```
[root@centos7 tests]# zdb -e -p /tmp -u lustre-ost1

Uberblock:
	magic = 0000000000bab10c
	version = 5000
	txg = 126
	guid_sum = 8587760490132740705
	timestamp = 1501874937 UTC = Fri Aug  4 12:28:57 2017
	mmp_magic = 00000000a11cea11
	mmp_delay = 0
```
The workaround solution seems to add the zfs pool into cache file, as follows:
```
[root@centos7 tests]# zpool set cachefile=/tmp/zpool.cache lustre-ost1
[root@centos7 tests]# zdb -U /tmp/zpool.cache -u lustre-ost1/ost1
Dataset lustre-ost1/ost1 [ZPL], ID 74, cr_txg 6, 1.79M, 224 objects
```

Since this is a not designed change, I would suppose this would be a bug.

### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Centos
Distribution Version    | 7.3
Linux Kernel                 | 3.10.0-514.16.1.el7_lustre.x86_64
Architecture                 | x86_64
ZFS Version                  | zfs-0.7.0-13-g1e1c398
SPL Version                  | spl-0.7.0-6-g6ecfd2b

**Comment by jxiong** [comment]
Update: the workaround solution of setting cachefile doesn't work on a physical device:

```
[root@onyx-82 ~]# zpool list -v  lustre-ost1
NAME   SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
lustre-ost1  49.8G  1.95M  49.7G         -     0%     0%  1.00x  ONLINE  -
  sdd1  49.8G  1.95M  49.7G         -     0%     0%
[root@onyx-82 ~]# zdb -U /tmp/zpool.cache -u lustre-ost1/ost1
failed to own dataset 'lustre-ost1/ost1': Remote I/O error
zdb: can't open 'lustre-ost1/ost1': Remote I/O error
```

@nedbass @ofaaland probably the new feature MMP stopped it from accessing the dataset.

**Comment by ofaaland** [comment]
Yep, this is not intentional.  I'll take a look; thank you.

**Comment by KnightKu** [comment]
Hi @ofaaland , is the issue Jinshan reported on comments fixed?
I just saw patch (https://github.com/zfsonlinux/zfs/commit/478754a8f5ff0f3b9f6dfe4ce272efc1681d243e) which fixed  the first "No such file or directory" issue, but not for the "Remote I/O error" issue, which seems to be related to MMP.

**Comment by ofaaland** [comment]
Hi @KnightKu , sorry I overlooked this.  It looks like it's not fixed.  I'll create a new issue for it and mention you.

**Comment by KnightKu** [comment]
Thanks, @ofaaland .

**Comment by KnightKu** [comment]
Hi @ofaaland,
zdb works with following change (just always ignore the MMP check for zdb):
```
diff --git a/cmd/zdb/zdb.c b/cmd/zdb/zdb.c
index 142968d..97adab1 100644
--- a/cmd/zdb/zdb.c
+++ b/cmd/zdb/zdb.c
@@ -5801,6 +5801,15 @@ main(int argc, char **argv)
                                }
                        }
                } else {
+                       /*
+                        * Disable the activity check to allow examination of
+                        * active pools.
+                        */
+                       mutex_enter(&spa_namespace_lock);
+                       if ((spa = spa_lookup(target)) != NULL) {
+                               spa->spa_import_flags |= ZFS_IMPORT_SKIP_MMP;
+                       }
+                       mutex_exit(&spa_namespace_lock);
                        error = open_objset(target, DMU_OST_ANY, FTAG, &os);
                        if (error == 0)
                                spa = dmu_objset_spa(os);
```
Is this one the right way to fix the problem?
