### ISSUE TITLE
panic on boot to root pool

### ISSUE THREAD

**Issue by RNCTX** [zfsonlinux/zfs#6466]
Hey guys, I'm not sure if this is remotely possible but I gave it a shot...

I have a ZFS pool from another machine (BSD, filesystem v5000) that seemingly imports and works normally from a Ubuntu live disk, so I tried following the guide on here to boot from it (after installing 16.04 in a chroot per the guide). I wiped out the BSD-specific datasets and created new ones for Ubuntu per the guide.  All of the data I'm trying to keep in the array are in the user home folders, so I retained the dataset pointing to /home, by changing the mountpoint from /usr/home to /home.

Everything appears to go smoothly, right up until the boot...

http://imgur.com/a/IV5rE

The only errors I saw during the migration were grub complaining about not being able to identify the file system type of the on-disk partitions.  However, grub does install/update normally to the MBR of all of the disks in question, and grub-probe of the root mount returns 'zfs'.

These are 2TB disks on a non-UEFI motherboard (a Supermicro ATOM board, as you can see).

I am booting with...

boot=zfs
rpool defined (name of the pool)
bootfs defined to the / dataset
A swap made on the array, defined in fstab.

**Comment by gmelikov** [comment]
It doesn't look like panic, maybe misconfiguration?

Support questions should be asked at our mailing lists.

And next time don't just ignore and delete issue template, thanks, closed.
