### ISSUE TITLE
It takes ~36 seconds to import zfs root filesystem during boot.

### ISSUE THREAD

**Issue by crocket** [zfsonlinux/zfs#6475]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Gentoo
Linux Kernel                 | 4.9.34-gentoo
Architecture                 | x86_64
ZFS Version                  | 0.7.0-r0-gentoo
SPL Version                  | 0.7.0-r0-gentoo

### Describe the problem you're observing

It takes ~36 seconds to boot gentoo linux on `os` ZFS pool.
I used a timer to measure the number of seconds.

Sometimes, initramfs fails to import `os` and shows me initramfs shell.
In the shell, the amount of time that it takes to execute `time /sbin/zpool import` is roughly 36~42 seconds.

**Comment by bunder2015** [comment]
It might be useful to know your pool geometry, but ultimately I believe that this is a genkernel bug, not a zfs one.  It is my understanding that dracut doesn't have this problem.

**Comment by crocket** [comment]
```
$ sudo zpool status
Password:
  pool: os
 state: ONLINE
status: Some supported features are not enabled on the pool. The pool can
        still be used, but some features are unavailable.
action: Enable all features using 'zpool upgrade'. Once this is done,
        the pool may no longer be accessible by software that does not support
        the features. See zpool-features(5) for details.
  scan: scrub repaired 0B in 0h2m with 0 errors on Tue Aug  8 20:22:18 2017
config:

        NAME        STATE     READ WRITE CKSUM
        os          ONLINE       0     0     0
          mirror-0  ONLINE       0     0     0
            sda3    ONLINE       0     0     0
            sdd3    ONLINE       0     0     0

errors: No known data errors

  pool: user-data
 state: ONLINE
status: Some supported features are not enabled on the pool. The pool can
        still be used, but some features are unavailable.
action: Enable all features using 'zpool upgrade'. Once this is done,
        the pool may no longer be accessible by software that does not support
        the features. See zpool-features(5) for details.
  scan: scrub repaired 0B in 3h29m with 0 errors on Sat Jul 22 20:59:15 2017
config:

        NAME                                         STATE     READ WRITE CKSUM
        user-data                                    ONLINE       0     0     0
          mirror-0                                   ONLINE       0     0     0
            ata-HGST_HDN724030ALE640_PK2234P8JHJJ2R  ONLINE       0     0     0
            ata-HGST_HDN724030ALE640_PK1234P9GTG9WX  ONLINE       0     0     0
```

**Comment by kpande** [comment]
please re-open this when the gentoo bug is resolved, assuming that there is a zol bug then.

**Comment by kpande** [comment]
as another note, the [zfs-discuss mailing list](http://list.zfsonlinux.org) is a great place to discuss the issue with other users to see if someone has the same problem, or a workaround.
