### ISSUE TITLE
zfs not importing zvol from illumos based zfs

### ISSUE THREAD

**Issue by bennabiy** [zfsonlinux/zfs#6480]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Ubuntu-Mate
Distribution Version    | 16.04.3
Linux Kernel                 | 4.6.4-040604-generic
Architecture                 | amd64
ZFS Version                  | 0.6.5.7-1
SPL Version                  | 0.6.5.7-1

### Describe the problem you're observing
When I do a zfs send pool/dataset > file.zfs from an illumos created zvol made in SmartOS, and then try to zfs recv -vdF poolname , I get it importing almost all of the data, and then hanging. Say I have a dataset which on the original is 1.97 GB, it receives 1.81 and then hangs. This happens on any zvol's I try to copy to my backup machine which is ZoL based.

### Describe how to reproduce the problem
Generate a zvol on a non ZoL based zfs system, and zfs send /recv to a ZoL based system (whether through ssh, or file copy then import)

### Include any warning/errors/backtraces from the system logs
no warnings in the logs...

**Comment by gmelikov** [comment]
First we need information about SmartOS version.

The main advise is to try with latest version - 0.6.5.11 or 0.7. 0.6.5.7 may have problems with recv from newer openZFS versions.

**Comment by bennabiy** [comment]
SmartOS PI 
`joyent_20170706T001501Z`
output from 
````
modinfo | grep zfs
119 fffffffff7d65000 12b098   8   1  zfs (ZFS filesystem version 5000)
119 fffffffff7d65000 12b098  90   1  zfs (ZFS storage pool)
````

**Comment by gmelikov** [comment]
Looks like #5699 duplicate, install latest zfs vertsion and try, feel free to reopen this issue if it won't help. Closed.
