### ISSUE TITLE
Plans for packaging 0.7.x for Ubuntu?

### ISSUE THREAD

**Issue by gdevenyi** [zfsonlinux/zfs#6482]
Will there be another ppa or updates to the existing one for the 0.7.x series?

**Comment by DeHackEd** [comment]
You'll have to ask Ubuntu. They package that stuff.

**Comment by gdevenyi** [comment]
They don't package the existing ppa, that's zfs on linux

**Comment by gmelikov** [comment]
Please ask such questions on Ubuntu PPA page https://launchpad.net/~zfs-native , this is not a support forum, next time please read contribution guidelines https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md and don't just remove issue template.
