### ISSUE TITLE
zfs root on debian jessie outdated?

### ISSUE THREAD

**Issue by faxm0dem** [zfsonlinux/zfs#6485]
Hi,

The debian [tutorial](/zfsonlinux/zfs/wiki/Debian-Jessie-Root-on-ZFS) seems active, but it refers to jessie. Is that a mistake, or does it only work on jessie?

**Comment by gmelikov** [comment]
It works on stretch too, just don't use backports, packages are already in stretch repos.

**Comment by gmelikov** [comment]
I've updated wiki to Stretch https://github.com/zfsonlinux/zfs/wiki/Debian-Stretch-Root-on-ZFS , feel free to reopen this issue if you get any problems.
