### ISSUE TITLE
zfs pool creation  fails in version 0.7.0

### ISSUE THREAD

**Issue by aasraoui** [zfsonlinux/zfs#6488]
Under zfs 0.7 zpool create fails with this response, anything has changed in version 0.7 ?

 zpool create -f -o ashift=12 ost raidz2 35000c5008355e2c3 35000c5008355cedb 35000c500837ece67 35000c5008355ddcf 35000c500837f23cf 35000c500837f2b93 35000c5008355bb67 35000c5008355bbdf 35000c5008355da8b 35000c500837f249f 35000c5008355c33b

cannot create 'ost': invalid argument for this pool operation
 rpm -qa "*zpool*"
libzpool2-0.7.0-1.el7_3.x86_64

spl, 0.7.0, 3.10.0-514.21.el7
zfs, 0.7.0, 3.10.0-514.21.1.el7

**Comment by behlendorf** [comment]
Nothing has changed in regarding the pool creating syntax, what you've posted should work.  I'd suggest making sure you've removed any old version of ZFS from the system then reinstalling 0.7.1 cleanly to see if you're able to still reproduce the issue.

**Comment by kpande** [comment]
this is a userland issue with mismatched kernel version.

**Comment by fermulator** [comment]
This is a super annoying bug eh ;/

It is easy to hit even in interim upgrade states.

Consider:
 1. user has functional system, CentOS + zfsonlinux
 2. dnf upgrade, kernel updates and/or zfs updates
 3. now userland is mismatch w/ kernel ;/
