### ISSUE TITLE
debian stretch zfs root howto grub uefi fails

### ISSUE THREAD

**Issue by faxm0dem** [zfsonlinux/zfs#6493]
I tested the [stretch zfs root debian howto](/zfsonlinux/zfs/wiki/Debian-Stretch-Root-on-ZFS) and thanks so much for updating it from jessie. However, I'm failing to complete the [grub installation step](/zfsonlinux/zfs/wiki/Debian-Stretch-Root-on-ZFS#step-5-grub-installation).

The UEFI method fails with the following message:

```
$ update-grub
update-initramfs: Generating /boot/initrd.img-4.9.0-3-amd64
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-4.9.0-3-amd64
Found initrd image: /boot/initrd.img-4.9.0-3-amd64
done
$ grub-install --target=x86_64-efi --efi-directory=/boot/efi \
    --bootloader-id=debian --recheck --no-floppy
Installing for x86_64-efi platform.
EFI variables are not supported on this system.
EFI variables are not supported on this system.
grub-install: error: efibootmgr failed to register the boot entry: No such file or directory.
```

**Comment by bunder2015** [comment]
`EFI variables are not supported on this system.`

best guess, the kernel you booted doesn't have efi support, or you didn't mount /sys in your chroot.

**Comment by faxm0dem** [comment]
sysfs is mounted and kernel is 4.9.0-3-amd64.
I tried to load the efivars and efivarfs and both report `could not insert No such device`

**Comment by faxm0dem** [comment]
I think I might be booting wrong, as the efi firmware directory is absent in sysfs

**Comment by gmelikov** [comment]
UEFI part of instruction was copied from Ubuntu one. It's not ZFS related problem, I think.

**Comment by faxm0dem** [comment]
you're absolutely right. I was booting in legacy mode :-/ sorry for the noise.

That being said I found a small typo: one of the first commands should be `echo`, not `cat` in paragraph *1.4 Add contrib archive area*

**Comment by gmelikov** [comment]
That's great!

Thanks, fixed. Closed.
