### ISSUE TITLE
'edonr' and 'skein' zpool features are not supported for root pools even though UEFI is a thing

### ISSUE THREAD

**Issue by evujumenuk** [zfsonlinux/zfs#6501]
Exhibit A:

https://github.com/zfsonlinux/zfs/blob/376994828fd3753aba75d492859727ca76f6a293/module/zfs/zfs_ioctl.c#L3991-L4004

Exhibit B:

https://github.com/zfsonlinux/zfs/blob/376994828fd3753aba75d492859727ca76f6a293/lib/libzfs/libzfs_dataset.c#L1593-L1598

(376994828fd3753aba75d492859727ca76f6a293 is the current `master`.)

As for the rationale, @skiselkov stated the following in https://www.listbox.com/member/archive/post_content.html?post_id=20131007080502:B04DC60C-2F48-11E3-9198-9C9438B0F59B&address=000:

> No, this is to cover the ERANGE return from zfs_ioctl.c:3784 where we
check to make sure nobody enables any salted checksums on a root pool,
since GRUB doesn't have support for that feature. Bootloader support on
FreeBSD might differ, though.

On UEFI systems, GRUB is not even used. Prohibiting the setting and use of specific flags is, in this configuration, rather unnecessary.

https://github.com/zfsonlinux/zfs/issues/6202 notes the same: disallowing zpool features is not warranted when GRUB is not used, which is a configuration that has worked for several years now.

**Comment by bunder2015** [comment]
While EFI stub booting is a thing, most people who use EFI still use it to boot grub, which doesn't support several feature flags.  illumos (to the best of my knowledge) doesn't support EFI either.  I don't know the complete status of the grub they use.  It might be possible their grub can't boot all-flag pools as well.

**Comment by charlesmilette** [comment]
What about users of systemd-boot, which on UEFI systems just boots the EFI stub?

**Comment by bunder2015** [comment]
Unfortunately the linux ecosystem is so diverse, I don't think we would find a solution that suits everybody's needs.

**Comment by charlesmilette** [comment]
What about the possibility to enable those features (and others) on `bootfs` pools with a clear warning about the possibility to break some bootloaders?

**Comment by bunder2015** [comment]
Its probably doable, but I think a better idea would be to add it behind a `-f` option to `zfs set` so people don't arbitrarily change it by mistake.  I'm not a dev and it would probably need to get approval across all the platforms before implementing.  Sounds like something worthy of the mailing lists.
