### ISSUE TITLE
zfs 0.7.1 building problem on OEL 7.4

### ISSUE THREAD

**Issue by Yevgeny1** [zfsonlinux/zfs#6502]
distr :   OEL 7.4
arch :    x86-64
kernel : UEK4 R4
Linux oel7_1 4.1.12-94.5.7.el7uek.x86_64 #2 SMP Thu Jul 20 18:44:17 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux

ZFS Version   :               0.7.1
modinfo zfs | grep -iw version :                0.7.1-1
modinfo spl | grep -iw version :                0.7.1-1

## problem

rebuild after upgrade (OEL 7.3 --> 7.4),  DKMS  build incorrect modules, for non-active kernels
(installed both kernel trees,  RHEL kernel 3.10.xxx  and UEK kernel 4.1.xxx, active is 4.1.xxx,  but build script build module for fresh-installed and non-active kernel 3.10.xxx, not for currently used  4.1.xxx kernel).

solution : reboot, remove all zfs* spl* rpm's, install & rebuild.

**Comment by devZer0** [comment]
this looks stale/outdated. 

close?

**Comment by Yevgeny1** [comment]
"this looks stale/outdated.
close?"

Yes.
