### ISSUE TITLE
/dev/zfs is missing!

### ISSUE THREAD

**Issue by Synergyst** [zfsonlinux/zfs#6514]
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name  |  Debian Jessie
Distribution Version  | 8 update 2
Linux Kernel  | Linux pentium 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64 GNU/Linux
Architecture  | amd64
ZFS  |        0.6.5.9-2~bpo8+1
SPL  |        0.6.5.9-1~bpo8+1 

### Describe the problem you're observing
When running any ZFS commands I get the error:
/dev/zfs and /proc/self/mounts are required.
Try running 'udevadm trigger' and 'mount -t proc proc /proc' as root.

### Describe how to reproduce the problem
`zfs get all`
`/dev/zfs and /proc/self/mounts are required.
Try running 'udevadm trigger' and 'mount -t proc proc /proc' as root.`

### More details ###
/proc/self/mounts exists and contains the contents of /etc/mtab from the looks.
/dev/zfs does NOT exist.. 'udevadm trigger' does nothing to resolve this.

**Comment by BtbN** [comment]
modprobe zfs?

**Comment by Synergyst** [comment]
I have tried this. Nothing happens..

**Comment by richardelling** [comment]
There are kernel configurations which prevent the zfs module from loading. Check the output of dmesg for zfs-related error messages.

**Comment by Synergyst** [comment]
I rebooted the server and that seems to have resolved the issue.

Is ZFS not supposed to load automatically without a reboot after following the official wiki instructions for Debian?

Feel free to mark this as closed if there is no further input on the issue.

**Comment by kpande** [comment]
please, in the future, use [the zfs-discuss mailing list](http://list.zfsonlinux.org) or #zfsonlinux on Freenode IRC first before opening an issue

**Comment by MarcS1975** [comment]
> There are kernel configurations which prevent the zfs module from loading. Check the output of dmesg for zfs-related error messages.

Thank you Richard for the comment!! I had the same problem as Synergyst above and could not find a solution. Almost lost my whole ZFS pool of data. Your comment made me reboot with an old Kernel which made ZFS work. All data was saved.
