### ISSUE TITLE
module ZFS not found

### ISSUE THREAD

**Issue by 1Liol** [zfsonlinux/zfs#6517]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | CentOS 
Distribution Version    | 7.3.1611
Linux Kernel                 | 4.12.7-1.el7.elrepo.x86_64
Architecture                 | x86_64
ZFS Version                  | 0.7.1-1.el7_3
SPL Version                  | 0.7.1-1.el7_3

### Describe the problem you're observing
After ZFS installation from RPM on a clean system with kernel version 4.12 I got the following error:
~:zfs create
The ZFS modules are not loaded
Tried running '/sbin/modprobe zfs' as root to load them.
~:modprobe zfs
FATAL: Module zfs not found

### Include any warning/errors/backtraces from the system logs
I've installed by following guide 
https://github.com/zfsonlinux/zfs/wiki/RHEL-%26-CentOS

**Comment by kpande** [comment]
please, use [the zfs-discuss mailing list](http://list.zfsonlinux.org) or #zfsonlinux on Freenode IRC to help diagnose before reopening your issue
