### ISSUE TITLE
ZFS 0.7.1-1 overreads with larger than 1 MB record size (up to 16x read amplification)

### ISSUE THREAD

**Issue by thewacokid** [zfsonlinux/zfs#6518]
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | TOSS (RHEL 6.7 derivative)
Distribution Version    | 2.4-9 
Linux Kernel                 | 2.6.32-573.26.1.1chaos.ch5.4.x86_64 #1 SMP Wed May 4 15:27:57 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
Architecture                 | x86_64
ZFS Version                  | 0.7.1-1
SPL Version                  | 0.7.1-1

### Describe the problem you're observing
It appears that setting a large recordsize causes read amplification based on [new block size / 1 MB].  This is a large pool with ~60 TB of space free out of 145 TB total (17+3 array of 8 TB drives).  Fresh ZFS filesystem, however the pool is 17% fragmented.  I'm going to recreate on a totally fresh pool to ensure it's not fragmentation related, though this still feels like a bug even if it is.  Write speeds are not affected, which is why I would expect fragmentation doesn't come into play here.

### Describe how to reproduce the problem
zfs set recordsize=1M
dd if=/dev/zero of=testfile1 bs=1M count=10000
zfs set recordsize=4M
dd if=/dev/zero of=testfile4 bs=1M count=10000
zfs set recordsize=16M
dd if=/dev/zero of=testfile16 bs=1M count=10000

Confirm record size:
```
[root@stb-dsu-sn002 test_large_blocks]# stat testfile1 | grep Blocks
  Size: 10485760000	Blocks: 19428575   IO Block: 1048576 regular file
[root@stb-dsu-sn002 test_large_blocks]# stat testfile4 | grep Blocks
  Size: 10485760000	Blocks: 19299995   IO Block: 4194304 regular file
[root@stb-dsu-sn002 test_large_blocks]# stat testfile16 | grep Blocks
  Size: 10485760000	Blocks: 19251861   IO Block: 16777216 regular file
```

Read them back with 1 MB blocks:
```
[root@stb-dsu-sn002 test_large_blocks]# dd if=testfile1 of=/dev/null bs=1M
10000+0 records in
10000+0 records out
10485760000 bytes (10 GB) copied, 16.9706 s, 618 MB/s
[root@stb-dsu-sn002 test_large_blocks]# dd if=testfile4 of=/dev/null bs=1M
10000+0 records in
10000+0 records out
10485760000 bytes (10 GB) copied, 58.9244 s, 178 MB/s
[root@stb-dsu-sn002 test_large_blocks]# dd if=testfile16 of=/dev/null bs=1M
10000+0 records in
10000+0 records out
10485760000 bytes (10 GB) copied, 286.38 s, 36.6 MB/s
```

Check to see if larger read blocks make a difference:
dd if=testfile4 of=/dev/null bs=4M 
dd if=testfile16 of=/dev/null bs=16M
(very similar results here, read block size doesn't improve things)

Watching the disk statistics shows that they are indeed serving data at the same rate, they're just being hammered for far more data than is being passed back to the application.  Perhaps a bug in the sequential read logic that keeps such data out of the ARC?

### Include any warning/errors/backtraces from the system logs
None noted.

zfs.conf:
```
options zfs zfs_dirty_data_sync=4294967296
options zfs zfs_arc_min=4294967296
options zfs zfs_txg_timeout=120
options zfs zfs_top_maxinflight=128
options zfs zfs_vdev_aggregation_limit=16777216
options zfs zfs_max_recordsize=16777216
```

**Comment by behlendorf** [comment]
This does look like a performance issue with larger block sizes.

> dd if=/dev/zero of=testfile1 bs=1M count=10000

Based on your performance results I'm assuming you set `compression=off` on the filesystem?  Otherwise, I'd expect that your test files which were created with `/dev/zero` would be converted entirely to holes and you'd see great read performance.  You may want to use `/dev/urandom` when creating the files for a more realistic read workload.

> Perhaps a bug in the sequential read logic that keeps such data out of the ARC?

That's a good guess.  It definitely sounds like the buffer is getting dropped from the ARC and re-read from disk repeatedly.  You should be able to get a good idea if this is the case by watching `arcstat.py 1` and seeing what the miss% is.

Collecting the `/proc/spl/kstat/zfs/arcstats` and `/proc/spl/kstat/zfs/zfetchstats` from before and after the test should also help narrow down where the problem is.

**Comment by thewacokid** [comment]
Indeed, compression is disabled on these pools (they're for benchmarking / dev, so we wanted to avoid having to generate consistently compressible datasets).

arcstat.py 1 (while reading a 16 MB recordsize file)
`[root@stb-dsu-sn002 parameters]# arcstat.py 1
    time  read  miss  miss%  dmis  dm%  pmis  pm%  mmis  mm%  arcsz     c  
08:35:36     0     0      0     0    0     0    0     0    0   2.2G   31G  
08:35:37     0     0      0     0    0     0    0     0    0   2.2G   31G  
08:35:38     0     0      0     0    0     0    0     0    0   2.2G   31G  
08:35:39     1     1    100     1  100     0    0     0    0   2.2G   31G  
08:35:40    33    33    100    33  100     0    0     0    0   2.2G   31G  
08:35:41    41    41    100    41  100     0    0     0    0   2.2G   31G  
08:35:42    50    50    100    50  100     0    0     0    0   2.2G   31G  
08:35:43    42    42    100    42  100     0    0     0    0   2.2G   31G  
08:35:44    37    37    100    37  100     0    0     0    0   2.2G   31G  
08:35:45    37    37    100    37  100     0    0     0    0   2.2G   31G  
08:35:46    37    37    100    37  100     0    0     0    0   2.2G   31G  
08:35:48    12    12    100    12  100     0    0     0    0   2.2G   31G  
08:35:49     0     0      0     0    0     0    0     0    0   2.2G   31G  
08:35:50     0     0      0     0    0     0    0     0    0   2.2G   31G  `

...and while gathering these results, I realized just now that someone swapped the primarycache setting to metadata on the base pool, and my test filesystem inherited it. :(


Here's a read of the same file with primarycache=all after filling the cache with other data (to ensure that this data wasn't in the ARC), and performance is closer to what I would have expected, but still slower than the smaller block sizes with correspondingly lower hit rates.

16 MB recordsize file:
`[root@stb-dsu-sn002 ~]# arcstat.py 1
    time  read  miss  miss%  dmis  dm%  pmis  pm%  mmis  mm%  arcsz     c  
08:55:47     0     0      0     0    0     0    0     0    0    31G   31G  
08:55:48    25    23     92    23   92     0    0     1   50    31G   31G  
08:55:49    30    29     96    29   96     0    0     0    0    31G   31G  
08:55:50    38    32     84    32   84     0    0     0    0    31G   31G  
08:55:51    30    29     96    29   96     0    0     0    0    31G   31G  
08:55:52    33    30     90    30   90     0    0     0    0    31G   31G  
08:55:53    36    33     91    33   91     0    0     0    0    31G   31G  
08:55:54    34    32     94    32   94     0    0     0    0    31G   31G  
08:55:55    30    27     90    27   90     0    0     0    0    31G   31G  
08:55:56    32    31     96    31   96     0    0     0    0    31G   31G  
08:55:57    32    29     90    29   90     0    0     0    0    31G   31G  
08:55:58    33    30     90    30   90     0    0     0    0    29G   29G  
08:55:59    38    37     97    37   97     0    0     0    0    29G   29G  
08:56:00    38    34     89    34   89     0    0     0    0    29G   29G  
08:56:01    30    29     96    29   96     0    0     0    0    29G   29G  
08:56:02    34    30     88    30   88     0    0     0    0    29G   29G  
08:56:03    30    25     83    25   83     0    0     0    0    29G   29G  
08:56:04    30    27     90    27   90     0    0     0    0    30G   30G  
08:56:05    30    27     90    27   90     0    0     0    0    30G   30G  
08:56:06    29    25     86    25   86     0    0     0    0    30G   30G  
08:56:07    27    26     96    26   96     0    0     0    0    26G   26G  
08:56:08    35    30     85    30   85     0    0     0    0    26G   26G  
08:56:09    13    11     84    11   84     0    0     0    0    26G   26G  
08:56:10     0     0      0     0    0     0    0     0    0    26G   26G  

`

4 MB recordsize file:
`[root@stb-dsu-sn002 ~]# arcstat.py 1
    time  read  miss  miss%  dmis  dm%  pmis  pm%  mmis  mm%  arcsz     c
08:55:02     4     3     75     3   75     0    0     2   66    31G   31G  
08:55:03   383   195     50     4    2   191   91     2  100    31G   31G  
08:55:04   489   244     49     0    0   244   98     0    0    31G   31G  
08:55:05   575   288     50     0    0   288   99     0    0    31G   31G  
08:55:06   488   244     50     0    0   244  100     0    0    31G   31G  
08:55:07   475   231     48     0    0   231   87     1   33    31G   31G  
08:55:08   491   245     49     0    0   245   98     0    0    31G   31G  
08:55:09   610   304     49     0    0   304   99     0    0    31G   31G  
08:55:10   577   289     50     0    0   289  100     1  100    31G   31G  
08:55:11   457   226     49     0    0   226   88     0    0    31G   31G  
08:55:12   480   237     49     0    0   237   98     0    0    31G   31G  
08:55:13     0     0      0     0    0     0    0     0    0    31G   31G  
`

1 MB recordsize file:
`[root@stb-dsu-sn002 ~]# arcstat.py 1
    time  read  miss  miss%  dmis  dm%  pmis  pm%  mmis  mm%  arcsz     c
08:54:44     0     0      0     0    0     0    0     0    0    28G   28G  
08:54:45   883   449     50     6    1   443  100     3  100    28G   28G  
08:54:46  2.1K  1.1K     50     0    0  1.1K  100     1   33    29G   29G  
08:54:47  2.0K  1.0K     50     0    0  1.0K  100     1   33    30G   30G  
08:54:48  1.7K   826     49     0    0   826  100     1   33    31G   31G  
08:54:49  1.8K   924     50     0    0   924  100     1   33    31G   31G  
08:54:50  1.8K   920     50     0    0   920  100     1   33    31G   31G  
08:54:51  1.9K   927     50     0    0   927  100     1  100    31G   31G  
08:54:52  1.9K   925     49     0    0   925  100     0    0    31G   31G  
08:54:53  1.9K   927     49     0    0   927  100     1   33    31G   31G  
08:54:54  1.8K   875     50     0    0   875  100     1   33    31G   31G  
08:54:55  2.0K   986     49     0    0   986  100     1   33    31G   31G  
08:54:56   352   172     48     0    0   172  100     0    0    31G   31G  
08:54:57     0     0      0     0    0     0    0     0    0    31G   31G  
`


So is this still a bug, or is it an expected behavior?  I wouldn't expect large block sizes to hurt this badly, but perhaps there's a size limitation on a single IO call that just exacerbates the lack of caching?  I have tested in the past and I don't recall seeing such huge read inflations for larger block sizes even with primarycache=metadata set.  4 MB recordsize actually seems to perform a bit better than 1 MB in this case, with good hit ratios - only 16 MB seems to be terrible in comparison.

arcstats / zfetchstats before:
`[root@stb-dsu-sn002 ~]# cat /proc/spl/kstat/zfs/arcstats
12 1 0x01 92 4416 1174672978786 159176384481308
name                            type data
hits                            4    119435
misses                          4    392306
demand_data_hits                4    39225
demand_data_misses              4    169065
demand_metadata_hits            4    54018
demand_metadata_misses          4    178742
prefetch_data_hits              4    18665
prefetch_data_misses            4    25392
prefetch_metadata_hits          4    7527
prefetch_metadata_misses        4    19107
mru_hits                        4    85038
mru_ghost_hits                  4    18172
mfu_hits                        4    10827
mfu_ghost_hits                  4    3016
deleted                         4    87899
mutex_miss                      4    5
evict_skip                      4    35
evict_not_enough                4    2
evict_l2_cached                 4    0
evict_l2_eligible               4    128306566144
evict_l2_ineligible             4    1432928256
evict_l2_skip                   4    0
hash_elements                   4    64873
hash_elements_max               4    94218
hash_collisions                 4    29299
hash_chains                     4    222
hash_chain_max                  4    2
p                               4    16076810418
c                               4    33822255104
c_min                           4    4294967296
c_max                           4    33822255104
size                            4    33913128008
compressed_size                 4    27174418944
uncompressed_size               4    27217824256
overhead_size                   4    6590906368
hdr_size                        4    22169112
data_size                       4    33696024576
metadata_size                   4    69300736
dbuf_size                       4    28496048
dnode_size                      4    70227456
bonus_size                      4    26910080
anon_size                       4    376352256
anon_evictable_data             4    0
anon_evictable_metadata         4    0
mru_size                        4    15791526400
mru_evictable_data              4    3076522496
mru_evictable_metadata          4    0
mru_ghost_size                  4    18027516416
mru_ghost_evictable_data        4    16022242304
mru_ghost_evictable_metadata    4    2005274112
mfu_size                        4    17597446656
mfu_evictable_data              4    17547919360
mfu_evictable_metadata          4    205312
mfu_ghost_size                  4    4294799360
mfu_ghost_evictable_data        4    4093640704
mfu_ghost_evictable_metadata    4    201158656
l2_hits                         4    0
l2_misses                       4    0
l2_feeds                        4    0
l2_rw_clash                     4    0
l2_read_bytes                   4    0
l2_write_bytes                  4    0
l2_writes_sent                  4    0
l2_writes_done                  4    0
l2_writes_error                 4    0
l2_writes_lock_retry            4    0
l2_evict_lock_retry             4    0
l2_evict_reading                4    0
l2_evict_l1cached               4    0
l2_free_on_write                4    0
l2_abort_lowmem                 4    0
l2_cksum_bad                    4    0
l2_io_error                     4    0
l2_size                         4    0
l2_asize                        4    0
l2_hdr_size                     4    0
memory_throttle_count           4    0
memory_direct_count             4    0
memory_indirect_count           4    1239
arc_no_grow                     4    0
arc_tempreserve                 4    0
arc_loaned_bytes                4    0
arc_prune                       4    0
arc_meta_used                   4    217103432
arc_meta_limit                  4    25366691328
arc_dnode_limit                 4    2536669132
arc_meta_max                    4    528233920
arc_meta_min                    4    16777216
sync_wait_for_async             4    542
demand_hit_predictive_prefetch  4    20069
arc_need_free                   4    0
arc_sys_free                    4    1056945472`

`[root@stb-dsu-sn002 ~]# cat /proc/spl/kstat/zfs/zfetchstats 
10 1 0x01 3 144 1174639379489 159187618919348
name                            type data
hits                            4    6818265
misses                          4    30419605
max_streams                     4    30073557`

...and after reading a few 16 MB recordsize files (dd if=testfile of=/dev/null bs=1M):
`[root@stb-dsu-sn002 ~]# cat /proc/spl/kstat/zfs/arcstats
12 1 0x01 92 4416 1174672978786 159351003332340
name                            type data
hits                            4    120656
misses                          4    396009
demand_data_hits                4    40089
demand_data_misses              4    170315
demand_metadata_hits            4    54375
demand_metadata_misses          4    181195
prefetch_data_hits              4    18665
prefetch_data_misses            4    25392
prefetch_metadata_hits          4    7527
prefetch_metadata_misses        4    19107
mru_hits                        4    86021
mru_ghost_hits                  4    18933
mfu_hits                        4    11065
mfu_ghost_hits                  4    3091
deleted                         4    121047
mutex_miss                      4    7
evict_skip                      4    36
evict_not_enough                4    3
evict_l2_cached                 4    0
evict_l2_eligible               4    196006691840
evict_l2_ineligible             4    1483259904
evict_l2_skip                   4    0
hash_elements                   4    72409
hash_elements_max               4    94218
hash_collisions                 4    29598
hash_chains                     4    240
hash_chain_max                  4    2
p                               4    30375029938
c                               4    33822255104
c_min                           4    4294967296
c_max                           4    33822255104
size                            4    33862350848
compressed_size                 4    20991436288
uncompressed_size               4    21042927104
overhead_size                   4    12717025280
hdr_size                        4    25286304
data_size                       4    33634201088
metadata_size                   4    74260480
dbuf_size                       4    30561120
dnode_size                      4    70880576
bonus_size                      4    27161280
anon_size                       4    1081450496
anon_evictable_data             4    0
anon_evictable_metadata         4    0
mru_size                        4    29333472768
mru_evictable_data              4    5030036992
mru_evictable_metadata          4    999424
mru_ghost_size                  4    4486542336
mru_ghost_evictable_data        4    2441086464
mru_ghost_evictable_metadata    4    2045455872
mfu_size                        4    3293538304
mfu_evictable_data              4    3287285760
mfu_evictable_metadata          4    24576
mfu_ghost_size                  4    19362116096
mfu_ghost_evictable_data        4    19158532096
mfu_ghost_evictable_metadata    4    203584000
l2_hits                         4    0
l2_misses                       4    0
l2_feeds                        4    0
l2_rw_clash                     4    0
l2_read_bytes                   4    0
l2_write_bytes                  4    0
l2_writes_sent                  4    0
l2_writes_done                  4    0
l2_writes_error                 4    0
l2_writes_lock_retry            4    0
l2_evict_lock_retry             4    0
l2_evict_reading                4    0
l2_evict_l1cached               4    0
l2_free_on_write                4    0
l2_abort_lowmem                 4    0
l2_cksum_bad                    4    0
l2_io_error                     4    0
l2_size                         4    0
l2_asize                        4    0
l2_hdr_size                     4    0
memory_throttle_count           4    0
memory_direct_count             4    0
memory_indirect_count           4    1239
arc_no_grow                     4    0
arc_tempreserve                 4    0
arc_loaned_bytes                4    0
arc_prune                       4    0
arc_meta_used                   4    228149760
arc_meta_limit                  4    25366691328
arc_dnode_limit                 4    2536669132
arc_meta_max                    4    528233920
arc_meta_min                    4    16777216
sync_wait_for_async             4    542
demand_hit_predictive_prefetch  4    20069
arc_need_free                   4    0
arc_sys_free                    4    1056945472`

`[root@stb-dsu-sn002 ~]# cat /proc/spl/kstat/zfs/zfetchstats 
10 1 0x01 3 144 1174639379489 159354191698140
name                            type data
hits                            4    6894150
misses                          4    30739595
max_streams                     4    30389954`

**Comment by ironMann** [comment]
@thewacokid Have you tried increasing the `zfetch_max_distance` module parameter above `16MiB`? The value can be adjusted in runtime.

**Comment by thewacokid** [comment]
@ironMann I have tried that, and it appears to not change the behavior meaningfully.  16 MB recordsizes work well for writing, but reading is still generating a lot of ARC misses and overreads.  4 MB recordsize appears to work well after tuning a few things, but I know I'm out on the edge in terms of wanting to use massive recordsizes. :)

The underlying issue appears to be a limitation in the singular IOs issued to the leaf vdev - this issue is extremely easy to trigger with primarycache=metadata.  Perhaps that's not much of an issue for most, but it only appears to be partially mitigated by allowing the ARC to cache the data for subsequent reads.  In memory-constrained cases, I imagine it'll degrade back to the initial 4x to 16x read amplification scenario.

**Comment by Thoro** [comment]
I just ran into the same issue with the primarycache=metadata - but it's a recommended setting for PostgreSQL somehow.

https://serverfault.com/questions/875557/zfs-read-behaviour-on-single-disk

Additionally I do have the issue that if primarycache=all is set, that the read speeds are limited to 1.3 GB/s - which seems to be a CPU limitation because no offloading is happening (?) - shouldn't reading from the cache be efficient?

And regarding the issue, the same happens with small recordsizes (see in my link) - and I'm wondering if it's not possible to just issue smaller read requests instead of the full recordsize??

BTW. I'm using current ZFS master@b33d668ddb005b1072c26d36e1abff53aa39ca98
Kernel: Linux at-storage-01 4.12.5 #1 SMP Fri Aug 11 09:55:48 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by richardelling** [comment]
> Additionally I do have the issue that if primarycache=all is set, that the read speeds are limited to 1.3 GB/s - which seems to be a CPU limitation because no offloading is happening (?) - shouldn't reading from the cache be efficient?

A block is processed as a whole. For example, compression/decompression/checksum is done by a single thread on each block.

> And regarding the issue, the same happens with small recordsizes (see in my link) - and I'm wondering if it's not possible to just issue smaller read requests instead of the full recordsize??

The block size, as limited by recordsize, is the unit of work. For example, when reading a block, the whole block must be read in order to verify the checksum. Similarly, if a single bit in the block is updated, the whole new block must be written. For this reason, the engineering trade-off of large vs small recordsize is often unclear.

**Comment by Thoro** [comment]
According to #3022 the data is uncompressed in the ARC - what other operations are happening at that time - I still think 1.3 GB/s seems too slow. Compression and recordsize 128K allows 2.7GB/s reads directly from disk.

Not sure if that's now the correct location to discuss the issue I posted on serverstack - why would the IOPS be limited with ZFS? I can get ~85000 IOPS with XFS, but on ZFS it maxes out at 20k for 16k read and 16k record size - also CPU practically idles.

**Comment by behlendorf** [comment]
> According to #3022 the data is uncompressed in the ARC

At the time that issue was opened this was true.  As of the 0.7 release data is kept compressed in the ARC and uncompressed on demand.  This is possible because for a modern processors lz4 decompression is effectively as fast as a memory copy.  You can disable this for testing by setting the module option `zfs_compressed_arc_enabled=0`, but since you have available CPU that's probably not the issue.

Those numbers do sound low, but it's hard to say where exactly the bottleneck is for your system without  carefully profiling it.

**Comment by Thoro** [comment]
I will try the compress/uncompressed option and see. Since it's single thread performance and the CPU is just a 2.2 Ghz and the dd process is running at 100% I do believe this may be the issue.

Can you give me a few hints were to start with the profiling regarding the non cached read specialities? Or is that just how zfs works? (single workload type per dataset?)

Atm I'm testing with dd / fio , read, randread, write, randwrite with various block sizes. And the whole behaviour is - in my opinion - just weird.

**Comment by fling-** [comment]
Similar issue here with 0.7.1
zfs reads from a vdev at 200MBps (from zpool iostat)
rsync only getting 3MBps reads

**Comment by Thoro** [comment]
@fling- this can actually either be that primarycache=all is off, you have a record size mismatch between rsync and zfs, or a permissions issue that you don't have xattr=sa set - maybe there are other reasons, but check those first

**Comment by ahrens** [comment]
> primarycache setting to metadata

I don't think there's a bug here.  If you ask for the data to not be cached, then you should expect every read from the application to turn into a read from disk.  If you are doing sub-block reads (e.g. reading 1MB at a time from recordsize=16M), then ZFS has to read the whole block to get the small part you requested.

**Comment by thewacokid** [comment]
That would be true if doing bs=recordsize reads "fixed" the issue, but it does not as I stated in my first issue report.  I could retest and report again if needed, but I don't believe the underlying cause was found here.

**Comment by dbavatar** [comment]
@thewacokid I agree. This is still broken. I switched over the 4MB thinking this issue was fixed based on the above comment, but reading from files written with 4MB blocks is painfully slow, even when using 4MB read size. I don't believe it's caching effects either, as I don't see read amplification on the block devices. Maybe you can confirm the same on your setup with /usr/bin/iostat?

**Comment by thewacokid** [comment]
I don't have the same testbed available at the moment.  I haven't retested this on the newest "stable" .7 release, my plan is to reconfirm this behavior when we go to validate the newer releases for production use.
