### ISSUE TITLE
Periodic hangs ZFS/iSCSI(LIO), Reconnecting Windows iSCSI Initiator

### ISSUE THREAD

**Issue by Voothi** [zfsonlinux/zfs#6523]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Ubuntu Server
Distribution Version    |  16.04.2
Linux Kernel                 |  4.4.0-87-generic #110-Ubuntu SMP GNU/Linux
Architecture                 |  x86_64
ZFS Version                  |  0.6.5.6-0ubuntu16
SPL Version                  |  0.6.5.6-0ubuntu4

### Describe the problem you're observing
Periodic hangs ZFS/iSCSI(LIO), Reconnecting Windows iSCSI Initiator
### Describe how to reproduce the problem
Hight workload on zvol over one iSCSI from Windows 2012R2. (Backup_Initial-Replication VMs Hyper-V)
Ubuntu as VM with connecting VHDX (Dynamic) on Hyper-V SCSI Controller. 

Pool - 2xTB_VHDX place on NTFS(Cluster-Size_64K) / StorageSpaceTiering / VD LSI Mirror 2x3TB_HDD-SATA-HGST-3.5inch. 

Log / SLOG (ZIL) - 1x30GB_VHDX place on NTFS(Cluster-Size_64K) / StorageSpaceTiering / VD LSI Mirror 2x223GB_SSD-SATA.

Cache / L2ARC - 1x30GB_VHDX place on NTFS(Cluster-Size_64K) / StorageSpaceTiering / VD LSI Mirror 2x223GB_SSD-SATA.

RAM / Dynamic RAM Hyper-V 2048-16384 200% buffer.

**Comment by kpande** [comment]
please use [the zfs-discuss mailing list](http://list.zfsonlinux.org) to have people help you diagnose and gather information to then reopen this issue if need be.
