### ISSUE TITLE
ZFS Debian stretch obsolete step 4.5

### ISSUE THREAD

**Issue by faxm0dem** [zfsonlinux/zfs#6525]
Hi and thanks again for this excellent [tutorial](/zfsonlinux/zfs/wiki/Debian-Stretch-Root-on-ZFS) @gmelikov @rlaager . It seems the step involving the creation of `/usr/share/initramfs-tools/conf.d/zfs` in ¶ *"4.5 Install ZFS in the chroot environment for the new system"* is not necessary anymore in stretch as the file already exists and identical (provided by package `zfs-initramfs`)

**Comment by gmelikov** [comment]
Thanks, I've removed it.
