### ISSUE TITLE
Random checksum failures and corrupt data in zvols when running QEMU

### ISSUE THREAD

**Issue by Tobi29** [zfsonlinux/zfs#6532]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Arch Linux
Distribution Version    | 
Linux Kernel                 | 4.12.8 (Vanilla as well as Zen)
Architecture                 | x86_64
ZFS Version                  | zfsonlinux/zfs@08de8c16f5d322fb594742ea78958385d8ee5b50 (using customized dkms packages, self compiled)
SPL Version                  | zfsonlinux/spl@9df9692637aeee416f509c7f39655beb2d35b549 (using customized dkms packages, self compiled)

This is running on consumer grade hardware (No ECC memory, plain motherboard with SATA hdds and ssds).

However the issue seems to only affect zvols, but 2 to 3 drives at once, so I am confident this
is no hardware fault.

### Describe the problem you're observing
Running QEMU with zvols causes corruptions when guest filesystem writes to it.

Specifically `zpool status` reports checksum errors in the zvol and the guest filesystem
starts to report I/O errors all over the place.

Normal files (including running QEMU with a disk stored in a file) are not affected, with no
errors being reported nor any visible corruptions.

It appears to occur all the way back on ZFS 0.7.0 rc5 and Linux 4.11.x, however kernel version
does not appear to be culprit (Although I cannot rule it out). I was unable to try ZFS 0.7.0 rc4
on this system due to feature flags, if it is of use I can try bisect it down, however that
may take a day or two.

### Describe how to reproduce the problem
Ideally if available, running Windows (with NTFS) in a VM seems to cause this very commonly.

Alternatively installing some distro using QEMU on a drive backed by a zvol with any filesystem
(ext4, btrfs and xfs all cause this and most distro installers provide at least one of them
for easy testing).

It may take 2-3 attempts but once it gets going it spams errors in `zpool status` and the installer
often also gets stuck.

Specifically in my tests I used a blocksize of 64K, a striped pool on 2 hdds (although the same
issue occured on an ssd in the same machine), no compression (it also happens with lz4, probably
others as well), primarycache off, no secondary cache, QEMU performance modes on cache none and
io native (also occurs on other configurations).

I was so far unable to reproduce the issue by mounting a filesystem on it (without a VM) or
running plain `dd`.

### Include any warning/errors/backtraces from the system logs
Nothing in dmesg on the host side most of the time. I have noticed some ZFS panics locking
up the affected pool occasionally when testing, however this is quite rare and I do not have
the backtrace available, if I notice that happening again, I can post it on here (It contained
a function call to something like `arc_write` if memory serves).

`zpool status -v` shows CKSUM errors affecting the zvols. (No actual files are listed
by the -v option, other than mentioned zvols)

Running e.g. `dd` to recover data from broken zvols just prints generic I/O errors,
whenever a broken block is read.

If useful I can try provide more debug info, just not sure what the best options for
getting them is as I am not exactly familiar with the internals of Linux or ZFS.

**Comment by behlendorf** [comment]
@Tobi29 this sounds a lot like issue #6238 which was just fixed in master by commit f763c3d1df569a8d6b60bcb5e95cf07aa7a189e6.  It would be great if you could pull the latest source and see if you're still able to reproduce this issue.

**Comment by Tobi29** [comment]
Good to know that running a debug build to catch errors is possible, seems like this in fact fixed the issue for me as well. Thanks for the help either way!
