### ISSUE TITLE
centos 7.4 is (almost) out, please build kmod-*.el7_4

### ISSUE THREAD

**Issue by dmaziuk** [zfsonlinux/zfs#6565]
As usual, `kmod-[zfs|spl]` does not load into the new kernel: `3.10.0-693.1.1.el7`. It's in "continuous release" now, 7.4 is not "officially" out yet.

**Comment by loli10K** [comment]
This is already being tracked in https://github.com/zfsonlinux/zfs/issues/6541, please use the search functionality next time, thanks.
