### ISSUE TITLE
Problems installing zfs on Fedora 26

### ISSUE THREAD

**Issue by poettler-ric** [zfsonlinux/zfs#6585]
### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Fedora
Distribution Version    | 26
Linux Kernel                 | 4.12.8
Architecture                 | x86_64
ZFS Version                  | -
SPL Version                  | -

### Describe the problem you're observing

I can't install the zfs package using dnf:
```
[richi@localhost ~]$ sudo dnf install zfs
[sudo] password for richi: 
Last metadata expiration check: 0:31:02 ago on Mit 30 Aug 2017 18:46:19 CEST.
Error: 
 Problem: problem with installed package zfs-fuse-0.7.2.2-4.fc26.x86_64
  - package zfs-0.6.5.9-1.fc26.x86_64 conflicts with zfs-fuse provided by zfs-fuse-0.7.2.2-4.fc26.x86_64
  - package zfs-0.6.5.9-1.fc26.x86_64 conflicts with zfs-fuse provided by zfs-fuse-0.7.2.2-2.fc26.x86_64
  - conflicting requests
  - package zfs-0.6.5.11-1.fc26.x86_64 conflicts with zfs-fuse provided by zfs-fuse-0.7.2.2-4.fc26.x86_64
  - package zfs-0.6.5.11-1.fc26.x86_64 conflicts with zfs-fuse provided by zfs-fuse-0.7.2.2-2.fc26.x86_64
  - package zfs-0.7.0-1.fc26.x86_64 conflicts with zfs-fuse provided by zfs-fuse-0.7.2.2-4.fc26.x86_64
  - package zfs-0.7.0-1.fc26.x86_64 conflicts with zfs-fuse provided by zfs-fuse-0.7.2.2-2.fc26.x86_64
  - package zfs-0.7.1-1.fc26.x86_64 conflicts with zfs-fuse provided by zfs-fuse-0.7.2.2-4.fc26.x86_64
  - package zfs-0.7.1-1.fc26.x86_64 conflicts with zfs-fuse provided by zfs-fuse-0.7.2.2-2.fc26.x86_64
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstalable packages)
```
I assume this comes from this commit:
https://src.fedoraproject.org/rpms/zfs-fuse/c/d92f7fc67d3faeafcffe15a5e71a5be3e9684714?branch=master

Tbh I got no idea who should change their package, if at all.

### Describe how to reproduce the problem

Execute: ```dnf install zfs```

**Comment by poettler-ric** [comment]
Somehow they managed to make zfs-fuse a dependency for libvirt/kvm.

**Comment by behlendorf** [comment]
Thanks for letting us know, but I don't think there's anything we can do about this.  These packages _do_ intentionally conflict with the zfs-fuse.  Let's get @Conan-Kudo's thoughts on how best to resolve this in Fedora.

**Comment by Conan-Kudo** [comment]
You can do `dnf swap zfs-fuse zfs` to swap implementations.

**Comment by poettler-ric** [comment]
Thanks @Conan-Kudo , I didn't trust that switch at first. Now I have to figure out how to get that into my ansible playbook. Tbh I don't know why they rely on zfs-fuse, since it doesn't even have a commit since Nov 2015.
Thanks for the fast replies.

**Comment by Conan-Kudo** [comment]
@poettler-ric Well, the reason for it is because Fedora does not allow *any* third-party kernel modules in the distribution. It's either in the kernel or it operates through FUSE. Kernel module packages have been banned (and moved to RPM Fusion) since Fedora 8.
