### ISSUE TITLE
Using refquota, rm: cannot remove ... Disk quota exceeded

### ISSUE THREAD

**Issue by petermaloney** [zfsonlinux/zfs#6587]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Ubuntu
Distribution Version    | 16,94
Linux Kernel                 | 4.4.0-92-generic
Architecture                 | amd64 / x86_64
ZFS Version                  | 0.6.5.6-0ubuntu16
SPL Version                  | 0.6.5.6-0ubuntu4

### Describe the problem you're observing
Using refquota and a filled up dataset without any snapshots, you cannot remove files without raising the quota first. So that means only the administrator can delete files to solve the problem.

If you simply fill it with a single large file, it removes fine. Also my code below without the 2nd "touch" loop won't produce it either (which is proven already by the first rm). But if you make lots of small ones, it's easy to reproduce. And in our real life data, it happens frequently, even though it's mostly large files.

### Describe how to reproduce the problem
```
# zfs destroy -r tank/junk/quotatest
# zfs create tank/junk/quotatest
# zfs set compression=off tank/junk/quotatest
# zfs set refquota=1G tank/junk/quotatest
# cd /tank/junk/quotatest/
# while true; do dd if=/dev/zero of=$(printf "%05d" $RANDOM) bs=1M count=1 >/dev/null 2>&1 || break; done
# rm $(ls -1 | head -n1)
# while touch $(printf "n%05d" $RANDOM) >/dev/null 2>&1; do true; done

# rm $(ls -1 | head -n1)
rm: cannot remove '00071': Disk quota exceeded
```

**Comment by loli10K** [comment]
Fixed in 0.7.0-rc1? https://github.com/zfsonlinux/zfs/commit/1a04bab34808694f3bf1cef3dc208c9499d103aa
