### ISSUE TITLE
ZFS does not package systemd unit files in Debian even with --enable-systemd

### ISSUE THREAD

**Issue by jwittlincohen** [zfsonlinux/zfs#6591]
### System information

Type | Version/Name
  ---  |     --- 
Distribution Name | Debian
Distribution Version | Stretch (9.1)
Linux Kernel | 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64
Architecture | AMD64
ZFS Version | 0.7.0-1
SPL Version | 0.7.0-1

### Describe the problem you're observing

Regardless of my ./configure settings, the [instructions](https://github.com/zfsonlinux/zfs/wiki/Custom-Packages) to build custom kmod packages fails to package systemd unit files. Instead, sysvinit scripts are packaged.  In order to force the use of systemd, I compiled with:

`./configure --enable-systemd --with-systemdunitdir=/lib/systemd/system --with-systemdpresetdir=/lib/systemd/system-preset --with-systemdmodulesloaddir=/lib/modules-load.d
`

Nonetheless, the sysvinit scripts are packaged:

```
root@debian-vm:~# dpkg-query -L zfs
/.
/etc
/etc/default
/etc/default/zfs
/etc/init.d
/etc/init.d/zfs-import
/etc/init.d/zfs-mount
/etc/init.d/zfs-share
 #/etc/init.d/zfs-zed
```

No systemd unit files are packed, and as expected, there are no ZFS unit files in `/lib/systemd/system`

```
root@debian-vm:~# ls -la /lib/systemd/system | grep zfs
root@debian-vm:~# 
```

However, if I run ` #make install DESTDIR=/tmp/zfs`, the systemd unit files are installed to '/lib/systemd/system'

```
root@debian-vm:/tmp/zfs/lib/systemd/system# ls -la /tmp/zfs/lib/systemd/system
total 32
drwxr-xr-x 2 root root 4096 Sep  1 00:17 .
drwxr-xr-x 4 root root 4096 Sep  1 00:17 ..
-rw-r--r-- 1 root root  491 Sep  1 00:17 zfs-import-cache.service
-rw-r--r-- 1 root root  448 Sep  1 00:17 zfs-import-scan.service
-rw-r--r-- 1 root root  381 Sep  1 00:17 zfs-mount.service
-rw-r--r-- 1 root root  363 Sep  1 00:17 zfs-share.service
-rw-r--r-- 1 root root   76 Sep  1 00:17 zfs.target
```
Thus, this appears to be a packaging issue.

**Comment by WyseNynja** [comment]
Just ran into this on Ubuntu 16.04 :(
