### ISSUE TITLE
Extension to vdev_id script

### ISSUE THREAD

**Issue by tesujimath** [zfsonlinux/zfs#6592]
I have a server which presents scsi disks rather than sas ones.  It is therefore incompatible with the vdev_id script.

I have made some local modifications to this script to support what I am calling "scsi" topology.  It works for me, but I am very aware that testing this sort of thing thoroughly requires access to a variety of hardware which I don't have.

Are you interested in a pull request with this extension?

**Comment by behlendorf** [comment]
@tesujimath that sounds like a useful addition and something we'd consider including.  If you open a PR with the proposed changes we'll be able to provide more concrete feedback.
