### ISSUE TITLE
Can older userspace tools be used with newer ZFS/SPL Kmod's? 

### ISSUE THREAD

**Issue by matjohn2** [zfsonlinux/zfs#6593]
Quick yes/no question 👍 

Would it be stable and acceptable to run kernel modules version 0.7.1 with userspace tools 0.6.5.9?

Looking to automate kernel module builds for Moby/Linuxkit and it's potentially easier to just build the kernel modules and use the existing alpine APK's for the userspace tools (currently at 0.6.5.9).

Matt

**Comment by gmelikov** [comment]
No, you will have problems with it.

Next time please use mailing lists for support. Closed.
