### ISSUE TITLE
make `-fno-inline` compile option more accessible

### ISSUE THREAD

**Issue by prakashsurya** [zfsonlinux/zfs#6604]
Sometimes it can be beneficial to disable function inlining; e.g. to make the system easier to trace, measure, debug, etc.. Thus, it'd be nice to have an easy way to add the `-fno-inline` option to the kernel module's compilation options.

I've tested the following patch, and it appears to work as I intended:
```
diff --git a/module/Makefile.in b/module/Makefile.in
index 60973ec7d5..3e8ccf5765 100644
--- a/module/Makefile.in
+++ b/module/Makefile.in
@@ -10,6 +10,7 @@ INSTALL_MOD_DIR ?= extra
 ZFS_MODULE_CFLAGS += -include @SPL_OBJ@/spl_config.h
 ZFS_MODULE_CFLAGS += -include @abs_top_builddir@/zfs_config.h
 ZFS_MODULE_CFLAGS += -I@abs_top_srcdir@/include -I@SPL@/include -I@SPL@
+ZFS_MODULE_CFLAGS += -fno-inline
 @CONFIG_QAT_TRUE@ZFS_MODULE_CFLAGS += -I@QAT_SRC@/include
 @CONFIG_QAT_TRUE@KBUILD_EXTRA_SYMBOLS += @QAT_SYMBOLS@
 export ZFS_MODULE_CFLAGS
```

With that patch applied, I can use `crash` to dump the stack for a process that crashed within ZFS:
```
crash> bt 1283
PID: 1283   TASK: ffff887d386b6200  CPU: 14  COMMAND: "fio"
 #0 [ffff887d382a7820] __schedule at ffffffff8183e9ee
 #1 [ffff887d382a7870] schedule at ffffffff8183f0d5
 #2 [ffff887d382a7888] spl_panic at ffffffffc01fb0ca [spl]
 #3 [ffff887d382a7a10] zil_lwb_commit at ffffffffc079a379 [zfs]
 #4 [ffff887d382a7a68] zil_process_commit_list at ffffffffc079a5f8 [zfs]
 #5 [ffff887d382a7af8] zil_commit_writer at ffffffffc079a98c [zfs]
 #6 [ffff887d382a7b30] zil_commit at ffffffffc079aaf0 [zfs]
 #7 [ffff887d382a7b50] zfs_write at ffffffffc078717a [zfs]
 #8 [ffff887d382a7d18] zpl_write_common_iovec at ffffffffc07b36cf [zfs]
 #9 [ffff887d382a7da0] zpl_iter_write_common at ffffffffc07b37c0 [zfs]
#10 [ffff887d382a7e08] zpl_iter_write at ffffffffc07b3824 [zfs]
#11 [ffff887d382a7e30] new_sync_write at ffffffff8120ec0b
#12 [ffff887d382a7eb8] __vfs_write at ffffffff8120ec76
#13 [ffff887d382a7ec8] vfs_write at ffffffff8120f5f9
#14 [ffff887d382a7f08] sys_pwrite64 at ffffffff81210465
#15 [ffff887d382a7f50] entry_SYSCALL_64_fastpath at ffffffff818431f2
    RIP: 00007f0d9dbcfda3  RSP: 00007fffbbf0d970  RFLAGS: 00000293
    RAX: ffffffffffffffda  RBX: 00007f0d89358600  RCX: 00007f0d9dbcfda3
    RDX: 0000000000002000  RSI: 0000000000cfe660  RDI: 0000000000000004
    RBP: 00007f0d89358600   R8: 0000000000000000   R9: 0000000000000001
    R10: 00000000009ac000  R11: 0000000000000293  R12: 0000000009920804
    R13: 0000000000000001  R14: 0000000000002000  R15: 00000000009aa000
    ORIG_RAX: 0000000000000012  CS: 0033  SS: 002b
```

Now, without my patch applied, the same process would have a stack like the following:
```
crash> bt 28365
PID: 28365  TASK: ffff887b7b978e00  CPU: 5   COMMAND: "fio"
 #0 [ffff887cd2167870] __schedule at ffffffff8183e9ee
 #1 [ffff887cd21678c0] schedule at ffffffff8183f0d5
 #2 [ffff887cd21678d8] spl_panic at ffffffffc02d70ca [spl]
 #3 [ffff887cd2167a60] zil_commit at ffffffffc1271daa [zfs]
 #4 [ffff887cd2167b50] zfs_write at ffffffffc1260d6d [zfs]
 #5 [ffff887cd2167d48] zpl_write_common_iovec at ffffffffc128b391 [zfs]
 #6 [ffff887cd2167dc0] zpl_iter_write at ffffffffc128b4e1 [zfs]
 #7 [ffff887cd2167e30] new_sync_write at ffffffff8120ec0b
 #8 [ffff887cd2167eb8] __vfs_write at ffffffff8120ec76
 #9 [ffff887cd2167ec8] vfs_write at ffffffff8120f5f9
#10 [ffff887cd2167f08] sys_pwrite64 at ffffffff81210465
#11 [ffff887cd2167f50] entry_SYSCALL_64_fastpath at ffffffff818431f2
    RIP: 00007f08274fbda3  RSP: 00007ffc1eae8a70  RFLAGS: 00000293
    RAX: ffffffffffffffda  RBX: 00007f080f6d8240  RCX: 00007f08274fbda3
    RDX: 0000000000002000  RSI: 0000000000f9b660  RDI: 0000000000000004
    RBP: 00007f080f6d8240   R8: 0000000000000000   R9: 0000000000000001
    R10: 0000000000374000  R11: 0000000000000293  R12: 000000000009bea3
    R13: 0000000000000001  R14: 0000000000002000  R15: 0000000000372000
    ORIG_RAX: 0000000000000012  CS: 0033  SS: 002b
```

Without my patch, it appears as though the panic was triggered from within `zil_commit`, when it actually occurred within `zil_lwb_commit`.

Having this extra information about which functions are being called is even more valuable when using a tracing tool like ftrace, since the additional function calls (that would have otherwise been inlined) can help remove any ambiguity about which code path(s) is being taken by the system, and without needing the addition of any extra static tracepoints.

It would be great if this build-time configuration could be enabled via an option to the `./configure` script, much like the `--enable-debug` option that currently exists.

**Comment by loli10K** [comment]
> It would be great if this build-time configuration could be enabled via an option to the ./configure script, much like the --enable-debug option that currently exists.

Doesn't 
```
export ZFS_MODULE_CFLAGS='-fno-inline'
./autogen.sh && ./configure && make
```
already achieve this?

**Comment by prakashsurya** [comment]
That might work. I hadn't really dug into the build files prior to making this issue, but now having briefly looked at them, what you're suggesting seems reasonable.

With that said, I think it'd also be reasonable to enable that compile option whenever `--enable-debug` is specified (like my patch attempts to do); the potential performance implications shouldn't be a concern when that flag is enabled, right?

I might even go so far as to argue that function inlining should be disabled by default even for non-debug builds, but it'd be irresponsible to make that statement without doing some detailed performance analysis (which I haven't done). The additional observability gained is tangible (for me, at least), and perhaps even on production system as dynamic tracing on Linux becomes more widespread, whereas the performance gains of aggressive function inlining isn't as obvious.

If using the `ZFS_MODULE_CFLAGS` environment variable is the right way to do this, I'm OK with that (now that I know how to use it).

**Comment by loli10K** [comment]
To be honest i've never used this before today, so i don't know about possible implications: maybe it can increase stack usage? I understand the observability concerns but enabling `-fno-inline` whenever `--enable-debug` is specified doesn't sound too good, it seems much more flexible to be able to specify custom options conditionally via CFLAGS/ZFS_MODULE_CFLAGS.

Also, i'm not sure about the additional observability gained: while it may be true dynamic tracing on Linux is becoming more widespread according to the issue tracker most of the userbase doesn't even use binaries with debugging enabled, which i think defeat the purpose of all this.

**Comment by prakashsurya** [comment]
> most of the userbase doesn't even use binaries with debugging enabled, which i think defeat the purpose of all this.

What I was getting at, is I think the `-fno-inline` option could be useful even for non-debug builds (i.e. for production systems), since it can make these dynamic tracing tools more useful for debugging and information gathering on production systems. My proposed change doesn't do this, but I think there could be a valid argument for it, assuming a reasonable performance impact of using it by default.

After working on illumos for a few years, and having dtrace and mdb available to effectively root cause problems the first time they appear in production environments, this sort of thing has become more important to me. Using environment variables is nice, but since it's an opt-in action, I'm skeptical that most users will enable this, which means these tracing tools will not be very effective when used on production systems.

> maybe it can increase stack usage?

Yeah, that's a good point. I think it definitely would increase stack usage. I forgot how delicate that situation is on Linux, so it's definitely something to consider. Further, I'd argue that's a good reason for _not_ setting `-fno-inline` via the environment variable; since most folks will not test with it set, enabling it "downstream" could be risky since that configuration wouldn't have been tested.

> I understand the observability concerns but enabling `-fno-inline` whenever `--enable-debug` is specified doesn't sound too good

Can you expand on your concerns? I'd like to better understand your stance, since I could be overlooking something. Using the environment variables seems like a viable approach, but I'm hesitant since it'd encourage folks to run using an otherwise untested configuration.

**Comment by loli10K** [comment]
Unless `-fno-inline` has no tangible performance impact (in which case i'm all for using it) the option to enable it could be more explicit than simply `--enable-debug`: i was hoping for something like `--enable-debug-dmu-tx` (now gone) or `--enable-debuginfo`.

**Comment by prakashsurya** [comment]
That makes sense. I was assuming that the performance impact would be acceptable when using the `--enable-debug` flag, but if that's not the case, I'm OK using a different flag to do this. Brian also suggested `--enable-debuginfo`, so that might be the way to go. Is the `--enable-debuginfo` enabled on any of the automated tests?

I'm still OK using an environment variable too; so long as we have some testing to ensure its usage doesn't cause problems.

**Comment by loli10K** [comment]
Reading the commit message here https://github.com/zfsonlinux/zfs/commit/7098243dba55704fafc406dbf9f304fa54db4d17 it would seem more appropriate to use `--enable-debuginfo`:

> The consequence is that issue reports from distributions such as Ubuntu
and its derivatives build kernel modules without debuginfo contain
nonsensical backtraces. It is therefore desireable to force generation
of debuginfo, so we implement --enable-debuginfo.

> Is the --enable-debuginfo enabled on any of the automated tests?

It doesn't seem to be, and is disabled by default:

```
root@linux:/usr/src/zfs# git describe
zfs-0.7.0-63-g4c5b89f59
root@linux:/usr/src/zfs# ./configure --help | grep debuginfo
  --enable-debuginfo      Force generation of debuginfo [default=no]
```

**Comment by behlendorf** [comment]
Regarding the performance impact of `-fno-inline` I'd be surprised if it was significant, so I'm not too concerned about that.

The limited stack situation on Linux is is a bigger problem and it's going to prevent us from adding `-fno-inline` to the production builds.  At least on the kernel side.  There are already several places in the code where we need to explicitly force functions to be inlined to keep the stack usage to a minimum.  Hopefully, these sites will remain inlined even when build with `fno-inline`.

I think it makes the most sense to add this to the existing `--enable-debuginfo` option. Anyone enabling this option almost certainly wants all the debugging information which can be provided.  This isn't enabled by default for the automated testing but it could be.  In fact, you can verify this doesn't cause any problems by enabling it in the PR which adds this functionality.  Custom configure options can be specified in the commit message.

```
Configure-zfs: --enable-debug --enable-debuginfo
```

**Comment by prakashsurya** [comment]
OK, I've updated the patch in the PR to use the `--enable-debuginfo` flag instead of `--enable-debug`.

**Comment by loli10K** [comment]
https://github.com/zfsonlinux/zfs/commit/6384cf4132a39dd0ada7991d551554b718041da9 was merged, i think we can close this.
