### ISSUE TITLE
Can not restore refreservation to its original value

### ISSUE THREAD

**Issue by shodanshok** [zfsonlinux/zfs#6608]
### System information

Type                                | Linux
  ---                                  |     --- 
Distribution Name       | CentOS Linux
Distribution Version    | 7.3
Linux Kernel                 | 3.10.0-514.26.2.el7.x86_64
Architecture                 | x86_64
ZFS Version                  | 0.7.1-1
SPL Version                  | 0.7.1-1

### Describe the problem you're observing
After setting `refreservation=none` on a zvol, it is not possible to restore its original value

### Describe how to reproduce the problem
1. create a zvol on whichever size
2. give a look at its `refreservation`
3. set `refreservation=none`
4. trying to restore its `refreservation` to original value give an unexpected error saying `cannot set property for 'tank/vol1': 'refreservation' is greater than current volume size`

Example:

```
[root@slave7 ~]# zfs list
NAME   USED  AVAIL  REFER  MOUNTPOINT
tank   816K   879M    24K  /tank
[root@slave7 ~]# zfs create -V 200M tank/vol1
[root@slave7 ~]# zfs get all tank/vol1 | grep refreservation
tank/vol1  refreservation        208M                   local
tank/vol1  usedbyrefreservation  208M                   -
[root@slave7 ~]# zfs set refreservation=none tank/vol1
[root@slave7 ~]# zfs get all tank/vol1 | grep refreservation
tank/vol1  refreservation        none                   local
tank/vol1  usedbyrefreservation  0B                     -
[root@slave7 ~]# zfs set refreservation=208M tank/vol1
cannot set property for 'tank/vol1': 'refreservation' is greater than current volume size

```

**Comment by loli10K** [comment]
Duplicate? https://github.com/zfsonlinux/zfs/issues/2468

**Comment by shodanshok** [comment]
Uhm yes, it seems a duplicate. Should I close this bug? Can we merge that on the original bug report?

More important: any news on the bug?
Thanks.

**Comment by loli10K** [comment]
> More important: any news on the bug?

Not that i know of, sorry.

If the information contained in the bug report is still true today this is enforced in userland, you can probably bypass this issue using `gdb`.
