### ISSUE TITLE
GCC 7.2.0 error in zpl_export

### ISSUE THREAD

**Issue by sempervictus** [zfsonlinux/zfs#6625]
### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Arch Linux
Distribution Version    | current
Linux Kernel                 | 4.9.48
Architecture                 | x86_64
ZFS Version                  | master
SPL Version                  | master

Building from master on Arch Linux (current as of today), i'm seeing ZFS module build failures in DKMS under the newly pushed GCC 7.2 packages:
```
done
make[3]: Entering directory '/var/lib/dkms/zfs/0.7.0/build/module/icp'
mkdir -p api core spi io os algs algs/aes algs/edonr algs/modes algs/sha1 algs/sha2 algs/skein asm-x86_64 asm-x86_64/aes asm-x86_64/modes asm-x86_64/sha1 asm-x86_64/sha2 asm-i386 asm-generic
make[3]: Leaving directory '/var/lib/dkms/zfs/0.7.0/build/module/icp'
make -C /usr/lib/modules/4.9.48-1-sv/build SUBDIRS=`pwd`  CONFIG_ZFS=m modules
make[3]: Entering directory '/usr/lib/modules/4.9.48-1-sv/build'
  CC [M]  /var/lib/dkms/zfs/0.7.0/build/module/zfs/zpl_export.o
/var/lib/dkms/zfs/0.7.0/build/module/zfs/zpl_export.c:171:16: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .encode_fh  = zpl_encode_fh,
                ^~~~~~~~~~~~~
/var/lib/dkms/zfs/0.7.0/build/module/zfs/zpl_export.c:171:16: note: (near initialization for ‘zpl_export_operations.encode_fh’)
```
Not quite sure why this is happening, the static initializer doesn't look like its been changed in a few years, so i'm betting the new GCC packages are the problem.

**Comment by tuxoko** [comment]
@sempervictus Check config.log for this part: `checking whether eops->encode_fh() wants inode`

**Comment by ssergiienko** [comment]
Just now upgraded to new GCC 7.2 and everything is ok with ZFS `0.7.0_r16_g6a8ee4f71-1` (it's ~= 0.7.1 tag). So problem could be only later in master.
Info:
```
local/linux 4.12.12-1 (base)
    The Linux kernel and modules
local/linux-lts 4.9.49-2
    The Linux-lts kernel and modules
```
During installation of 4.12.12:
```
checking whether eops->encode_fh() wants inode... yes
```

**Comment by sempervictus** [comment]
Rebuilt on 4.9.48, seems alright, probably an environmental effect.
Thanks for looking into it.


-------- Original Message --------

**Comment by loli10K** [comment]
> seems alright, probably an environmental effect.

Good, closing.
