### ISSUE TITLE
Some tests fail to cleanup when existing zpools are imported

### ISSUE THREAD

**Issue by stewartadam** [zfsonlinux/zfs#6627]
### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Fedora
Distribution Version    | 26
Linux Kernel                 | 4.12.9-300.fc26.x86_64
Architecture                 | x86_64
ZFS Version                  | 0.7.1-1 (with encryption patches)
SPL Version                  | 0.7.1-1

I've installed SPL from the upstream f26 repo and compiled 0.7.1 from source, patching in:
* Add libtpool (thread pools) (46364cb)
* Send / Recv Fixes following b52563 (9b84076)
* Native Encryption for ZFS on Linux (b525630)

While running the test suite to troubleshoot #6621 I observed several failures that were not present using the same RPM packages I compiled in a VM when no other pools were available. e.g. `functional/acl/posix/cleanup` failed to cleanup due to a `grep: Unmatched ( or \(` which appeared to impact subsequent tests:
```
SUCCESS: userdel staff1
SUCCESS: groupdel zfsgrp
grep: Unmatched ( or \(
grep: write error: Broken pipe
rm: cannot remove '/var/tmp/testdir': Device or resource busy
ERROR: rm -rf /var/tmp/testdir exited 1
NOTE: Performing test-fail callback (/usr/share/zfs/zfs-tests/callbacks/zfs_dbgmsg.ksh)
```

This is the snippet from `/usr/share/zfs/zfs-tests/include/libtest.shlib` that appears to cause the issue:
```
exclude=`eval echo \"'(${KEEP})'\"`
		ALL_POOLS=$(zpool list -H -o name 
		    | grep -v "$NO_POOLS" | egrep -v "$exclude")
```
In my case I had 3 pools, so `KEEP=data data-raidz ssd-scratch`.

**Comment by stewartadam** [comment]
As well `functional/bootfs/bootfs_004_neg` also appears to fail because of the test directory is not prefixed in its cleanup step:
```
13:27:11.67 Invalid pool names are rejected by zpool set bootfs
13:27:11.67 NOTE: Performing local cleanup via log_onexit (cleanup)
13:27:11.67 rm: cannot remove '/bootfs_004.4047.dat': No such file or directory
Test: /usr/share/zfs/zfs-tests/tests/functional/bootfs/bootfs_005_neg (run as root) [00:31] [FAIL]
```

Code:
```
function cleanup {
	if poolexists $POOL; then
		log_must zpool destroy $POOL
	fi
	rm /bootfs_004.$$.dat
}
```
That should read `rm $TESTDIR/bootfs_004.$$.dat` to match the earlier `mkfile` invokation.

**Comment by behlendorf** [comment]
@stewartadam I'd definitely believe there are still some lingering issues like this in the test suite.  The ZTS was adapted from Illumos and might have slightly different assumptions about the environment and of course bugs.  It would be great if you could open PRs for any problems you uncover so we can get those issues addressed.
