### ISSUE TITLE
Unable to install from EL7_3 - 404 not found

### ISSUE THREAD

**Issue by acastaner** [zfsonlinux/zfs#6638]
I'm running CentOS 7.3, fresh install and fully patch. I installed the repo from this link http://download.zfsonlinux.org/epel/zfs-release.el7_3.noarch.rpm

Now when I do a `yum install kernel-devel zfs` I get this: 

```
Downloading packages:
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
libnvpair1-0.7.1-1.el7_4.x86_6 FAILED
http://download.zfsonlinux.org/epel/7.3/x86_64/libnvpair1-0.7.1-1.el7_4.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found                                                    ]  0.0 B/s |    0 B  --:--:-- ETA
Trying other mirror.
To address this issue please refer to the below knowledge base article

https://access.redhat.com/articles/1320623

If above article doesn't help to resolve this issue please create a bug on https://bugs.centos.org/

libuutil1-0.7.1-1.el7_4.x86_64 FAILED
http://download.zfsonlinux.org/epel/7.3/x86_64/libuutil1-0.7.1-1.el7_4.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found                                                     ]  0.0 B/s |    0 B  --:--:-- ETA
Trying other mirror.
libzfs2-0.7.1-1.el7_4.x86_64.r FAILED
http://download.zfsonlinux.org/epel/7.3/x86_64/libzfs2-0.7.1-1.el7_4.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found                                                       ]  0.0 B/s |    0 B  --:--:-- ETA
Trying other mirror.
libzpool2-0.7.1-1.el7_4.x86_64 FAILED
http://download.zfsonlinux.org/epel/7.3/x86_64/libzpool2-0.7.1-1.el7_4.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found                                                     ]  0.0 B/s |    0 B  --:--:-- ETA
Trying other mirror.
spl-0.7.1-1.el7_4.x86_64.rpm   FAILED
http://download.zfsonlinux.org/epel/7.3/x86_64/spl-0.7.1-1.el7_4.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found                                                           ]  0.0 B/s |    0 B  --:--:-- ETA
Trying other mirror.
spl-dkms-0.7.1-1.el7_4.noarch. FAILED
http://download.zfsonlinux.org/epel/7.3/x86_64/spl-dkms-0.7.1-1.el7_4.noarch.rpm: [Errno 14] HTTP Error 404 - Not Found                                                      ]  0.0 B/s |    0 B  --:--:-- ETA
Trying other mirror.
zfs-0.7.1-1.el7_4.x86_64.rpm   FAILED
http://download.zfsonlinux.org/epel/7.3/x86_64/zfs-0.7.1-1.el7_4.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found                                                           ]  0.0 B/s |    0 B  --:--:-- ETA
Trying other mirror.
zfs-dkms-0.7.1-1.el7_4.noarch. FAILED
http://download.zfsonlinux.org/epel/7.3/x86_64/zfs-dkms-0.7.1-1.el7_4.noarch.rpm: [Errno 14] HTTP Error 404 - Not Found                                                      ]  0.0 B/s |    0 B  --:--:-- ETA
Trying other mirror.


Error downloading packages:
  zfs-0.7.1-1.el7_4.x86_64: [Errno 256] No more mirrors to try.
  libuutil1-0.7.1-1.el7_4.x86_64: [Errno 256] No more mirrors to try.
  libnvpair1-0.7.1-1.el7_4.x86_64: [Errno 256] No more mirrors to try.
  libzpool2-0.7.1-1.el7_4.x86_64: [Errno 256] No more mirrors to try.
  libzfs2-0.7.1-1.el7_4.x86_64: [Errno 256] No more mirrors to try.
  spl-0.7.1-1.el7_4.x86_64: [Errno 256] No more mirrors to try.
  spl-dkms-0.7.1-1.el7_4.noarch: [Errno 256] No more mirrors to try.
  zfs-dkms-0.7.1-1.el7_4.noarch: [Errno 256] No more mirrors to try.
```

Using EL7_4 I don't get 404's anymore, but I reckon this repo is for RHEL 7.4 not CentOS 7.3?

**Comment by fmikker** [comment]
Have you tried doing a 'yum clean all && yum update' ?
The EL* repositories works fine both for RHEL and CentOS 7.{3,4}

**Comment by changchichung** [comment]
I have the same problem .
yum clean all works fine , but yum update will cause some error like this
http://archive.zfsonlinux.org/epel/7.4/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below knowledge base article

https://access.redhat.com/articles/1320623

If above article doesn't help to resolve this issue please create a bug on https://bugs.centos.org/

 One of the configured repositories failed (ZFS on Linux for EL7 - dkms),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=zfs ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable zfs
        or
            subscription-manager repos --disable=zfs

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=zfs.skip_if_unavailable=true

failure: repodata/repomd.xml from zfs: [Errno 256] No more mirrors to try.
http://archive.zfsonlinux.org/epel/7.4/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found

**Comment by fmikker** [comment]
Add the following file to see if there is any inconstancies in the repo file:
`/etc/yum.repos.d/zfs.repo`
