### ISSUE TITLE
zfs send wildly varying read speed, stops sending for long periods of time

### ISSUE THREAD

**Issue by Kramerican** [zfsonlinux/zfs#6652]
Ubuntu 16.04
ZFS v... Not sure, couldn't figure out how to find which version I'm on.

I'm seeing wildly fluctuating speeds with `zfs send ` seemingly at random. I'm piping output from a ~7.8GB dataset to a file on another HDD with something like 

`time zfs send lxd/containers/mycontainer@testnew | mbuffer -m 1G > /backup/testnew` 

I  see in the output from mbuffer that it will happily chug along for the first 5-6 GB with 50-135Mb/s and then slow down to a crawl. Sometimes it starts out slowly, just a few hundred K, maybe spiking up to a few Mb/s, then picks up speed up to full throttle for a little while, then slows down again. In essence seemingly random and wild fluctuations in speed.

When slowed down to a halt, the CPU use for the process will be 0% and iotop does not reveal any relevant (or otherwise heavy) disk activity. It seems to me something is clogging up the works, but I am unsure of how to diagnose this. What could result in zfs send crawling to a halt like this?

Please note I am a complete zfs newbie, but otherwise well versed in Linux.

**Comment by gmelikov** [comment]
It's not the best way to just remove the entire issue template and ignore our contributing guidelines, please don't do it next time.

The issue tracker is for bugs and feature requests only, please use our mailing lists, closed.

**Comment by Kramerican** [comment]
@gmelikov my sincerest apologies. I did not intend to step on your toes here, and granted this was all hastily typed up.

As I am not seeing anything detectably wrong with my setup other than zfs stalling, I am suspecting this might either be a bug, or something in my environment which isn't configured correctly. Thus I do not think this is _completely_ out of scope for the issue tracker, however.

Anyway, I'll try my luck on the mailing list, and might then return here and follow your template of course.

Thank you for your time and attention regardless.
