### ISSUE TITLE
zfs receive does not respect ownership of files

### ISSUE THREAD

**Issue by flixman** [zfsonlinux/zfs#6657]
### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | CentOS Linux
Distribution Version    | 7.3.1611
Linux Kernel                 | 3.10.0-514.26.2.el7.x86_64
Architecture                 | x86_64
ZFS Version                  | 0.7.1-1
SPL Version                  | 0.7.1-1

### Describe the problem you're observing
When sending | receiving a ZFS FS, the filesystem I get has both the owner and group set to nxautomation for all files, snapshots, and files within snapshots. The original sent ZFS FS files' owner is root, and the receiving effective id is also root so... I do not understand why the new ownership is nxautomation.

### Describe how to reproduce the problem
Running 'ssh <remote machine> "zfs send -R \<ZFS@snapshot\>" |  sudo zfs receive -F \<ZFS\>'

**Comment by AndCycle** [comment]
have you tried ` ls -n` to take a look about the actual UID of the file owner?
the same UID is not necessary the same user you know.
and there is more extra things you need to consider depend on your environment.

**Comment by AndCycle** [comment]
and by the way, if you wanna know what actually store inside ZFS, 
use `zdb` to verify your observation

**Comment by flixman** [comment]
My fault: You are absolutely right. Sorry for making you loose time :-/.
