### ISSUE TITLE
zfs-0.7.2/module/icp/io/skein_mod.c:339]: (style) Array index 'vec_idx' is used before limits check.

### ISSUE THREAD

**Issue by dcb314** [zfsonlinux/zfs#6683]
Source code is

    for (vec_idx = 0; offset >= uio->uio_iov[vec_idx].iov_len &&
        vec_idx < uio->uio_iovcnt;
        offset -= uio->uio_iov[vec_idx++].iov_len)

**Comment by tcharding** [comment]
How about?
```
/*
 * Jump to the first iovec containing ptr to the digest to be returned.
 */
 vec_idx = 0;
 while (vec_idx < uio->uio_iovcnt && offset >= uio->uio_iov[vec_idx].iov_len) {
        offset -= uio->uio_iov[vec_idx].iov_len;
	vec_idx++;
}
```

**Comment by dcb314** [comment]
Sanity check is before use, so looks good.

**Comment by behlendorf** [comment]
The automated analysis here looks wrong, I don't see how `vec_idx` could be used before it's initialized.  That said, the fix looks good and is nicer than the existing code so let's do it.  My only suggestion would be to initialize ` vec_idx` a few lines up where it's declared instead of above the loop.

**Comment by dcb314** [comment]
>The automated analysis here looks wrong, I don't see how vec_idx could be used before it's >initialized. 

I think the automated analysis is trying to detect reading one element off the end of an array.

In more detail, any sanity check for an array index *must* happen before use.
Sanity check after allows to read past the end of an array.

**Comment by tcharding** [comment]
I agree with what @dcb314 said. What automated analysis tool are you using? I don't see this issue in the Coverity scan.

**Comment by dcb314** [comment]
>What automated analysis tool are you using?

cppcheck, available from sourceforge. 

I find it very useful for C and C++ code.

**Comment by tcharding** [comment]
thanks @dcb314. I love your bitesized issues, they present easy low hanging fruit for new developers. Is there some particular reason you were raising issues instead of PR's (I only ask because if you are doing it to help new devs I'll leave some for others?)

**Comment by tcharding** [comment]
> My only suggestion would be to initialize vec_idx a few lines up where it's declared instead of above the loop

Initializing `vec_idx` at declaration time leaves the code vulnerable to bugs when a later developer adds code in between the declaration and the while loop. IMO it is safer/cleaner to initialize the variable close to where it is used. This also reduces cognitive load on the reader since the initial value of `vec_idx` is apparent while viewing the loop. Granted it would look _nicer_ without the initialization directly above the while loop. I'll give you time to respond @behlendorf before creating the PR. thanks

**Comment by dcb314** [comment]
>thanks @dcb314. I love your bitesized issues, they present easy low hanging fruit for new developers. 

Thanks. You'd get even more fruit if you ran cppcheck yourselves. I ran it and
merely picked out the reports that I thought were important, which might not
be the same as the ones you think are important.

Good to know you have Coverity as well.

>Is there some particular reason you were raising issues instead of PR's

No. I found a way to send bug reports that works. Different teams have different ways
of doing things and it isn't always easy to send a bug report into some projects, which
rather defeats the point of open source.

**Comment by behlendorf** [comment]
Ahh yes, that would make more sense.  @tcharding I understand what you're saying, in this case the use is close enough to the declaration and the function is small enough that I think it makes the most sense to do it in the declaration.  This is the kind of thing we're flexible about depending on the circumstances.

@dcb314 out of curiosity what version of cppcheck are you using and what options are you passing.  We do automatically run cppcheck against every PR with the default options and report the results, see the top-level `cppcheck` Makefile target.  We'd love to enable more of the checks provided by `cppcheck` but of course we would need to fix what it finds first.

**Comment by dcb314** [comment]
>what version of cppcheck are you using and what options are you passing.

Bleeding edge development version. There are sometime false positives
as new warnings are worked on and not everything it reports is IMHO worth fixing.

I use flags --enable=all and sometimes --language=c++
and I've tweeked the source code of cppcheck as well.
