### ISSUE TITLE
zfs-0.7.2/module/zfs/zfs_vnops.c:4565]: (style) Suspicious condition

### ISSUE THREAD

**Issue by dcb314** [zfsonlinux/zfs#6685]
zfs-0.7.2/module/zfs/zfs_vnops.c:4565]: (style) Suspicious condition (assignment + comparison); Clarify expression with parentheses.

Source code is

       if ((error = zfs_getattr(ip, &vap, 0, CRED()) != 0))

maybe better code

       if ((error = zfs_getattr(ip, &vap, 0, CRED())) != 0)

**Comment by tcharding** [comment]
Correct me if I am wrong but the original code clobbers the return value from zfs_getattr(). Is this intended? I'm brand new round here so I can't say but it seems unlikely. At least we should have a comment if that **is** intended.

How about (inline with other code in this file)
```
if ((error = zfs_getattr(ip, &vap, 0, CRED()))
        return (error);
``` 

I'm guessing you guys don't like (I better re-read the coding conventions ;)

```
error =  zfs_getattr(ip, &vap, 0, CRED());
if (error)
	return (error);
```

**Comment by behlendorf** [comment]
This is definitely a bug.  The intent here is to return `error` when it's non-zero.  @tcharding let's go with the inline fix.  Both styles are allowed by the coding conventions and are used on a case by case basis depending on which is clear for for the specific code block.  It would be great if you could open a new PR with the fix.

**Comment by tcharding** [comment]
Cool. I'll do the PR shortly. thanks @behlendorf

**Comment by tcharding** [comment]
This is my first PR to ZFS project. Please feel free to yell at me if I missed something in the procedure.
