### ISSUE TITLE
ZFS Linux boot issues

### ISSUE THREAD

**Issue by alaraun** [zfsonlinux/zfs#6700]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Debian
Distribution Version    | unstable
Linux Kernel                 | 4.12.13
Architecture                 | x86_64
ZFS Version                  | 0.7.2
SPL Version                  |  0.7.0-12_g9df9692

### Describe the problem you're observing
- Can'tt get snapshot selection list as '-r' is missing when listing snapshots.
- quiet boot displays "lvm is not available"

### Describe how to reproduce the problem
- Boot from snapshot without giving snapshot name ie rpool/ROOT/debian@

### Fixes
```
diff --git a/contrib/initramfs/scripts/zfs b/contrib/initramfs/scripts/zfs
index 68373d2f2..4650c9646 100644
--- a/contrib/initramfs/scripts/zfs
+++ b/contrib/initramfs/scripts/zfs
@@ -579,10 +579,10 @@ ask_user_snap()
            eval `echo SNAP_$i=$snap`
            i=$((i + 1))
        done <<EOT
-$("${ZFS}" list -H -oname -tsnapshot "${fs}")
+$("${ZFS}" list -H -oname -tsnapshot -r "${fs}")
 EOT
 
-       echo -n "  Snap nr [0-$((i-1))]? " > /dev/stderr
+       echo -n "  Snap nr [1-$((i-1))]? " > /dev/stderr
        read snapnr
 
        # Re-enable debugging.
```
```
diff --git a/contrib/initramfs/scripts/local-top/zfs b/contrib/initramfs/scripts/local-top/zfs
index f09b2c81b..e8e5cd264 100755
--- a/contrib/initramfs/scripts/local-top/zfs
+++ b/contrib/initramfs/scripts/local-top/zfs
@@ -44,7 +44,7 @@ activate_vg()
 {
         # Sanity checks
         if [ ! -x /sbin/lvm ]; then
-                message "lvm is not available"
+                [ "$quiet" != "y" ] && message "lvm is not available"
                 return 1
         fi

````

**Comment by behlendorf** [comment]
Thanks, can you open a PR with the proposed fix.

**Comment by alaraun** [comment]
PR https://github.com/zfsonlinux/zfs/pull/6747
