### ISSUE TITLE
Ubuntu 16.04 Root on ZFS howto is broken because of util-linux package

### ISSUE THREAD

**Issue by BerserkerTroll** [zfsonlinux/zfs#6702]
`debootstrap` fails because of the bug in the util-linux package https://bugs.debian.org/823665

I've tried to workaround this by downloading and unpacking [ubuntu-base-16.04-core-amd64.tar.gz](http://cdimage.ubuntu.com/ubuntu-base/releases/16.04/release/ubuntu-base-16.04-core-amd64.tar.gz) into the `/mnt`, instead of using debootstrap. It seem to work fine until I try to generate initramfs and grub menu. I run the following script inside chroot:
```
locale-gen en_US.UTF-8 # ok
ln -s /proc/self/mounts /etc/mtab # ok
apt update
apt install --yes --no-install-recommends linux-image-generic
apt install --yes zfs-initramfs ubuntu-minimal grub-pc parallel
sed -e 's/quiet//' -e 's/splash//' -e 's/#GRUB_TERMINAL/GRUB_TERMINAL/' -i /etc/default/grub
grub-probe / # prints "zfs"
# "update-initramfs -c -k all" doesn't generate initramfs, I have to specify the version
update-initramfs -c -k 4.4.0-96-generic
update-grub # says that the /boot/grub/grub.cfg.new has errors. The file is almost empty, except for a few comment lines saying it is auto-generated
parallel -j1 --no-notice -a /root/disks.list "grub-install {}" # install grub to multiple disks, tells that there are no errors
ls /boot/grub/*/zfs.mod # shows the file
```

So  debootstrap, update-initramfs and update-grub are not working as expected.

Cast @rlaager

**Comment by rlaager** [comment]
debootstrap definitely worked on 16.04. I've run the HOWTO dozens of times. Are you saying it breaks in certain scenarios, or that it has recently broken (e.g. due a new util-linux being shipped as an update for 16.04)?

**Comment by BerserkerTroll** [comment]
Hmm. It is strange. `debootstrap xenial ...` run successfully on my local machine (Ubuntu 16.10), but it fails when I run it from Ubuntu 16.04 Live CD on a remote machine, where I do actual ZFS on root installation.

**Comment by BerserkerTroll** [comment]
`deboostrap` problem is solvable in multiple ways. I've decided to install Ubuntu server on a VM and copy files from it. Now `update-initramfs` is working, but `update-grub` is not:
```
+ grub-probe /
zfs
+ update-initramfs -c -k all
update-initramfs: Generating /boot/initrd.img-4.4.0-87-generic
W: Possible missing firmware /lib/firmware/ast_dp501_fw.bin for module ast
W: mdadm: /etc/mdadm/mdadm.conf defines no arrays.
+ update-grub
Generating grub configuration file ...
Script `/boot/grub/grub.cfg.new' contains no commands and will do nothing
Syntax errors are detected in generated GRUB config file.
Ensure that there are no errors in /etc/default/grub
and /etc/grub.d/* files or please file a bug report with
/boot/grub/grub.cfg.new file attached.
done
```
Could it be because I have multiple disks in a pool? Like here https://bugs.launchpad.net/ubuntu/+source/grub2/+bug/1582811
```
grub-probe --target=device /
/dev/sdg1
/dev/sdd1
/dev/sdc1
/dev/sdh1
/dev/sdb1
/dev/sdf1
/dev/sde1
```

**Comment by BerserkerTroll** [comment]
The issue with debootstrap is solved. It was completely my fault. I've added separate dataset for `/etc` with option `-o exec=off`:
```
zfs create -o setuid=off  -o exec=off rpool/etc
```
which no doubt was a wrong decision, at least because `/etc` contains `init.d` directory with scripts.

I didn't test it yet, but I think this will also solve the GRUB issue.
