### ISSUE TITLE
Unprivileged user can remove a file owned by root when the file parent dir is owned by that user

### ISSUE THREAD

**Issue by sriccio** [zfsonlinux/zfs#6704]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Centos
Distribution Version    | 6.9
Linux Kernel                 | 2.6.32-696.10.3.el6.x86_64
Architecture                 | x86_64
ZFS Version                  | 0.7.2-1
SPL Version                  | 0.7.2-1

### Describe the problem you're observing
An unprivilieged user can remove a file or dir owned by root if the parent dir is owned by this unprivilegied user.

### Describe how to reproduce the problem
as root:
mkdir testdir
chown testuser.testuser testdir
cd testdir
touch testfile
sudo -u testuser rm testfile

And the file is gone.

**Comment by sylveon** [comment]
Isn't that correct behavior for Unix permissions?

**Comment by sriccio** [comment]
Oh my ... I think you're right. I don't know why, but I was sure a file owned by root could only be removed by root in every cases.

Please pardon my mistake.

**Comment by nsc-zino** [comment]
Yea, that is as it should be.
