### ISSUE TITLE
vdev_copy_uberblocks() should use abd_alloc_linear()

### ISSUE THREAD

**Issue by thegreatgazoo** [zfsonlinux/zfs#6713]
The _vdev_copy_uberblocks()_ function uses _abd_to_buf(ub_abd))_ but allocates it with _abd_alloc(VDEV_UBERBLOCK_SIZE(vd), B_TRUE)_:
https://github.com/zfsonlinux/zfs/blob/39f56627ae988d09b4e3803c01c22b2026b2310e/module/zfs/vdev_label.c#L1167
https://github.com/zfsonlinux/zfs/blob/39f56627ae988d09b4e3803c01c22b2026b2310e/module/zfs/vdev_label.c#L1179

When the vd's ashift is high, _VDEV_UBERBLOCK_SIZE(vd)_ can be larger than _PAGESIZE_, which causes _abd_alloc()_ to return a scattered ABD, which will panic _abd_to_buf(ub_abd))_.

**Comment by behlendorf** [comment]
Good catch!  We do have a test case which exercises 8k uberblocks, `create-o_ashift.ksh`, but we never use them as part of an expansion test would would run this code.  It would be great if you could open a PR with the fix.
