### ISSUE TITLE
zfs_write() while loop is candidate for refactoring

### ISSUE THREAD

**Issue by tcharding** [zfsonlinux/zfs#6724]
### System information

Current development tip:
`39f56627ae98 ("receive_freeobjects() skips freeing some objects")`

### Describe the problem you're observing

Function `module/zfs_vnops:zfs_write()` contains a while loop that is almost 200 lines long. Coverity emits two warnings for code within this while loop. On top of that the function is over 350 lines long and has over 20 local variables. This function is a candidate for refactoring. It feels racy to attend to the Coverity issues within such a long while loop [for a new comer].

**Comment by tcharding** [comment]
Is this sort of refactoring something the ZFS project is open to?

**Comment by behlendorf** [comment]
I don't think it's a good idea to refactor this without good cause.  The `zfs_write()` function is at the core of the write path and while it has gotten somewhat large and unwieldy it's well tested.

**Comment by tcharding** [comment]
Understood, thanks.
