### ISSUE TITLE
HOWTOS: mount with --make-rslave

### ISSUE THREAD

**Issue by ghost** [zfsonlinux/zfs#6730]
@rlaager 

I suggest to add the `--make-rslave` to bind-mounts, i.e. write
```
# mount --rbind --make-rslave /dev  /mnt/dev
# mount --rbind --make-rslave /proc /mnt/proc
# mount --rbind --make-rslave /sys  /mnt/sys
```

This makes possible unmounting of `/mnt/{dev,proc,sys}` using `umount -R`, in case one fucked something up and wishes to destroy and recreate the pool.

**Comment by saveriomiroddi** [comment]
> @rlaager
> 
> I suggest to add the `--make-rslave` to bind-mounts, i.e. write
> 
> ```
> # mount --rbind --make-rslave /dev  /mnt/dev
> # mount --rbind --make-rslave /proc /mnt/proc
> # mount --rbind --make-rslave /sys  /mnt/sys
> ```
> 
> This makes possible unmounting of `/mnt/{dev,proc,sys}` using `umount -R`, in case one fucked something up and wishes to destroy and recreate the pool.

There is a procedure in place, for proposing edits: https://github.com/zfsonlinux/zfs/wiki/Ubuntu-18.04-Root-on-ZFS#contributing

Regarding the modification, I've done extensive testing, and, at least on my system, using the `rslave` propagation, while making the unmount work without force/lazy, it causes `zpool export -a` to irrevocably return a `pool busy` error (on the other hand, not using `rslave` forces me to perform a hard reset after the export...). Therefore, I think should be tested on several system before being added to the wiki.

**Comment by rlaager** [comment]
Sorry, somehow I either never saw this issue or lost track of it until the recent comment. This is pretty old, so it may very well predate the contributing instructions, and even if it didn't, an issue is okay too. Given the apparent trade-offs here, I'm inclined to just leave this as is.

I'm going to close this, but I don't feel strongly about that, so let me know if you disagree and I can re-open. You should be able to comment on a closed issue, but if not, you can email me directly at rlaager@wiktel.com.
