### ISSUE TITLE
zfs on sparc needs const static int sha1_consts[] = { ... } inside SHA1Transform() to compile

### ISSUE THREAD

**Issue by KireinaHoro** [zfsonlinux/zfs#6738]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Gentoo Linux
Distribution Version    |  Live
Linux Kernel                 |  4.9.49
Architecture                 |  UltraSPARC T2
ZFS Version                  |  [all]
SPL Version                  |  [all]

### Describe the problem you're observing

https://github.com/bahamas10/openzfs/blob/d4732e670edab07052ad1ccbcb4497c9bf6df199/usr/src/common/crypto/sha1/sha1.c#L502-L538

We need that as well, as `SHA1_CONST` macro has defined the behavior is to use this array on sparc, yet which was not implemented in the sources, which would result in the linker not finding the corresponding symbol `sha1_consts`.

https://github.com/zfsonlinux/zfs/blob/87f9371aefca857e7091dfdee3ec2d36b0de54c4/module/icp/include/sha1/sha1_consts.h#L46-L49

### Describe how to reproduce the problem

[inapplicable]

### Include any warning/errors/backtraces from the system logs

[inapplicable]

**Comment by KireinaHoro** [comment]
Adding this fixed the undefined reference issue mentioned in #6733 . The port to SPARC works now and passed `ztest` successfully.

**Comment by behlendorf** [comment]
@KireinaHoro thanks for digging in to this.  It would be great if you could open a PR with the needed fixes so we can get it reviewed and merged.
