### ISSUE TITLE
Corruption with sync=disabled on recent (>=0.7) zfs versions

### ISSUE THREAD

**Issue by gedia** [zfsonlinux/zfs#6768]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Gentoo
Distribution Version    | n/a
Linux Kernel                 | 4.13.5-gentoo
Architecture                 | amd64
ZFS Version                  | 0.7.2-r0-gentoo
SPL Version                  | 0.7.2-r0-gentoo

### How the issue manifests
I first noticed this because it affects executables. ldconfig would complain for various libraries that the .so file "is not an ELF file - it has the wrong magic bytes at the start"

Please read the "how to reproduce" section if this description doesn't make sense to you

### Describe how to reproduce the problem
I have always used sync=disabled for a zfs dataset used for building packages on gentoo. I never had any issues with it on the 0.6.x series. Starting with git master since about May 2017 (or maybe earlier, but I hadn't tested the 0.7 branch before that date), I have been able to reproduce this on two different computers with the following steps:

1) Use the following mountpoints for ZFS on gentoo:
```
NAME                    MOUNTPOINT
gtank                   none
gtank/gentoo            none
gtank/gentoo/boot       /boot
gtank/gentoo/build      /var/tmp/portage
gtank/gentoo/sysroot    /
gtank/gentoo/tmp        /tmp
gtank/gentoo/var        legacy
gtank/swap              -
```
2) Set the following attributes for the gtank/gentoo/build dataset:
```
compression=lz4
atime=off
sync=disabled
```
3) Boot a recent (>4.11) kernel with zfs modules from the 0.7.x branch
4) "emerge" several packages, using "/var/tmp/portage" as Portage's PORTAGE_TMPDIR directory, which is in turn a mountpoint for the gtank/gentoo/build dataset
5) Watch patiently as ldconfig starts complaining about .so files not being ELF files after a while.

This never manifested with the 0.6.x series and it seems to go away if I set sync=standard for the 0.7.x series as well...

I assume this is not something that should happen, since disabling sync didn't exhibit this behaviour with 0.6, so I'm opening this issue. Please note that during testing for this issue I never noticed anything that could have led to corruption of ASYNC writes (e.g. power loss).

### Other things I noticed

I copied one such "non ELF" .so file to my home folder, and then rebuilt the package with sync=standard, a process which produced a valid file. I noticed that:

a) The files have identical size:
```
pc ~ # ls -l /root/libgwenviewlib.so.4.97.0 
-rwxr-xr-x 1 root root 1383992 Oct 13 16:56 /root/libgwenviewlib.so.4.97.0
pc ~ # ls -l /usr/lib/libgwenviewlib.so.4.97.0 
-rwxr-xr-x 1 root root 1383992 Oct 16 17:56 /usr/lib/libgwenviewlib.so.4.97.0
```
b) Only the file built with sync=standard is valid ELF:
```
pc ~ # file /root/libgwenviewlib.so.4.97.0 
/root/libgwenviewlib.so.4.97.0: data
pc ~ # file /usr/lib/libgwenviewlib.so.4.97.0 
/usr/lib/libgwenviewlib.so.4.97.0: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, stripped
```

Also, note that this is not reproducible EVERY time. If I build for example a package 10 times with the build directory being a mountpoint of a dataset with sync=disabled, I'd say the problem manifests between 1 in 3 and 1 in 2 times.

**Comment by tuxoko** [comment]
https://github.com/zfsonlinux/zfs/issues/3125

**Comment by behlendorf** [comment]
Closing as duplicate.
