### ISSUE TITLE
Dependency missing in wiki

### ISSUE THREAD

**Issue by Redsandro** [zfsonlinux/zfs#6769]
I cannot edit your wiki and/or send a PR, correct?

Anyway, in https://github.com/zfsonlinux/zfs/wiki/Custom-Packages where it sais:

> For Debian and Ubuntu:
> 
> ```
> $ sudo apt-get install build-essential autoconf libtool gawk alien fakeroot gdebi linux-headers-$(uname -r)
> $ sudo apt-get install zlib1g-dev uuid-dev libattr1-dev libblkid-dev libselinux-dev libudev-dev parted lsscsi wget ksh gdebi
> ```

There should also be this dependency: `libssl-dev`.

**Comment by behlendorf** [comment]
Yes there should.  Wiki updated.

**Comment by Redsandro** [comment]
Great! :+1:
