### ISSUE TITLE
Cannot compile 0.7.3 on Antix 16-64 bit, kernel 4.8 (0.7.0 compiles OK)

### ISSUE THREAD

**Issue by kingneutron** [zfsonlinux/zfs#6778]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Antix 16 64-bit 
Distribution Version    | Debian Stable/Jessie
Linux Kernel                 | 4.8 (from distro repo)
Architecture                 | AMD64
ZFS Version                  |  modinfo zfs  0.7.0-139_gf8cd871
SPL Version                  |  modinfo spl   0.7.3-1

### Describe the problem you're observing
Cannot compile ZFS from git 0.7.3 on Antix 16-64 bit, kernel 4.8 (0.7.0 compiles and runs OK)

--Script attached, logfile with errors attached

  CC       zap_micro.lo
  CC       zfeature.lo
Makefile:539: recipe for target 'all-recursive' failed
Makefile:712: recipe for target 'all-recursive' failed
Makefile:580: recipe for target 'all' failed

### Describe how to reproduce the problem
Run attached script twice - 1st run compiles 0.7.0 fine, then will get a compile error for 0.7.3 (please note I am not proficient at git, apologies in advance)
[zfs-compile-error.tar.gz](https://github.com/zfsonlinux/zfs/files/1408721/zfs-compile-error.tar.gz)

**Comment by behlendorf** [comment]
@kingneutron were you building from the provided tarballs or git?  If this is an updated git tree make sure you run `autoreconf --force` before `configure`.

**Comment by kingneutron** [comment]
I am using git (non-proficiently, admittedly, pls bear with me) and am trying your recommendation; will report back. Thanks!

**Comment by kingneutron** [comment]
After adding 'autoreconf --force' to my script before configure, I am getting the same errors:

  CC       vdev_root.lo                                                                                                     
  CC       zap.lo                                                                                                           
  CC       zap_leaf.lo                                                                                                      
  CC       zap_micro.lo                                                                                                     
  CC       zfeature.lo                                                                                                      
Makefile:539: recipe for target 'all-recursive' failed                                                                      
Makefile:712: recipe for target 'all-recursive' failed                                                                      
Makefile:580: recipe for target 'all' failed                         

--Updated attachments (please note that Antix 16 Debian has no systemd)
[zfs-compile-results-with-autoreconf-force-20171025.tar.gz](https://github.com/zfsonlinux/zfs/files/1416034/zfs-compile-results-with-autoreconf-force-20171025.tar.gz)

Thanks...

**Comment by pzakha** [comment]
Ran into that issue recently when changing branches.
I've tried the recommendations above as well as a bunch of different options to cleanup the repository, but nothing worked.
I had to re-cloning the repository did the job though.
I suspect some make state / configuration files were kept that weren't being cleaned up.

**Comment by kingneutron** [comment]
Update - this can be closed, I switched to MX Linux 17 and they have ZFS 0.7.6-1 working with the 4.9 and 4.15 kernel series. Thanks

**Comment by mailinglists35** [comment]
Still occurring on Odroid C2 (aarch64, kernel 3.14.79-97 - I know, I will update to latest supported 3.16 when I will have physical access...)

git clone 
./autogen.sh
./configure
make -j $(nproc)

[full log](https://pastebin.com/9Txsxy35)

worked ok with 0.7.0
````
make[3]: Entering directory '/tmp/zfs/git/zfs/lib/libzpool'
  CC       kernel.lo
make[3]: *** No rule to make target '../../module/zfs/zfeature_common.c', needed by 'zfeature_common.lo'.  Stop.
make[3]: *** Waiting for unfinished jobs....
  CC       taskq.lo
  CC       util.lo
make[3]: Leaving directory '/tmp/zfs/git/zfs/lib/libzpool'
Makefile:618: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/tmp/zfs/git/zfs/lib'
Makefile:802: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/zfs/git/zfs'
Makefile:671: recipe for target 'all' failed
make: *** [all] Error 2
````

**Comment by rincebrain** [comment]
#7090 's resolution suggests you may only need a clean git tree for this to work properly.
