### ISSUE TITLE
Import Illumos #742: Resurrect the ZFS "aclmode" property

### ISSUE THREAD

**Issue by ryao** [zfsonlinux/zfs#679]
We might want to import illumos/illumos-gate@a3c49ce110f325a563c245bedc4d533adddb7211. It reintroduces an old feature.

https://www.illumos.org/issues/742

**Comment by kernelOfTruth** [comment]
Just saw it from the change in https://github.com/zfsonlinux/zfs/pull/4159 that

the snippet

```
 	/*
  	 * Property to be removed once libbe is integrated
 	 */
 	zprop_register_hidden(ZFS_PROP_PRIVATE, "priv_prop",
 	    PROP_TYPE_NUMBER, PROP_READONLY, ZFS_TYPE_FILESYSTEM,
 	    "PRIV_PROP");
```

to be removed by this change in module/zcommon/zfs_prop.c

is still there and found this issue entry

**Comment by kernelOfTruth** [comment]
referencing: https://github.com/zfsonlinux/zfs/issues/340 Suggestion for patch import from the Illumos project

**Comment by behlendorf** [comment]
@kernelOfTruth the way ACLs needed to be implemented for Linux that feature doesn't really apply.  I've marked it as such on the wiki.  I'll close this issue out since it not something anyone is planning to do.
