### ISSUE TITLE
Feature: zpool status to output full path to VDevs

### ISSUE THREAD

**Issue by lukebigum** [zfsonlinux/zfs#6792]
Distribution Name       | CentOS
Distribution Version    | 6
Linux Kernel                 | 2.6.32
Architecture                 | x86_64
ZFS Version                  | 0.7.1-1
SPL Version                  | 0.7.1-1

### Describe the problem you're observing

This is more feature request than bug.  The problem I have is the zpool command doesn't have a way to output the full path to it's VDevs. Under normal use you'd never need this, however it would be very useful if you are trying to do zpool management from any sort of automation or configuration management tool.

### Describe how to reproduce the problem

Consider the creation of a zpool like so with any arbitrary device as a vdev, then checking the status:

```
$ zpool create zpool1 /dev/vg_os/lv_zfs
$ zpool status zpool1
...
	NAME        STATE     READ WRITE CKSUM
	zpool1      ONLINE       0     0     0
	  lv_zfs    ONLINE       0     0     0
```

The output of "zpool status" shows the vdev name as "lv_zfs". A human being can figure out that this is actually /dev/vg_os/lv_zfs, no problem there, and I acknowledge that with ZFS metadata there generally shouldn't be a need to display the full path. However, configuration management tools like Puppet struggle with relative paths. If Puppet is told to go create 'zpool1' with a single vdev called '/dev/vg_os/lv_zfs', it will think it has failed (or has more work to do) because "lv_zfs" != "/dev/vg_os/lv_zfs".

You can work around the problem by making the tools and scripts smarter by searching through paths in /dev and looking for 'lv_zfs'. However that doesn't solve the actual problem because I could legitimately have  device nodes called _/dev/sda_, _/dev/vg_os/sda_, and _/dev/foo/sda_, and then the problem becomes a lot harder to solve.

It's an edge case, but if there was some option to 'zpool status' that translates the VDev to a full device path, this would make it a lot easier to integrate into scripts and tools that reference full device paths.

**Comment by loli10K** [comment]
> he problem I have is the zpool command doesn't have a way to output the full path to it's VDevs.

Doesn't `zpool status -P` already do this?

```
[root@zfsonlinux ~]# lvcreate centos -n zol1 -L1G
  Logical volume "zol1" created.
[root@zfsonlinux ~]# zpool create testpool /dev/mapper/centos-zol1
[root@zfsonlinux ~]# zpool status
  pool: testpool
 state: ONLINE
  scan: none requested
config:

	NAME           STATE     READ WRITE CKSUM
	testpool       ONLINE       0     0     0
	  centos-zol1  ONLINE       0     0     0

errors: No known data errors
[root@zfsonlinux ~]# zpool status -P
  pool: testpool
 state: ONLINE
  scan: none requested
config:

	NAME                       STATE     READ WRITE CKSUM
	testpool                   ONLINE       0     0     0
	  /dev/mapper/centos-zol1  ONLINE       0     0     0

errors: No known data errors
[root@zfsonlinux ~]# 
```

**Comment by lukebigum** [comment]
It does, thank you. I'm a bit embarrassed that that option escaped our notice!

**Comment by behlendorf** [comment]
@lukebigum it looks like it escaped your notice because the full description was accidentally dropped from the `zpool status` section of the man page.  We'll need to fix that.
