### ISSUE TITLE
Updated repository for Fedora 27

### ISSUE THREAD

**Issue by brmather** [zfsonlinux/zfs#6814]
Hello,

I foolishly upgraded Fedora last night, thinking there should be no compatability issue with the current Linux kernel version, but a Fedora 27 repository isn't available. Do you know what sort of timeline we're looking at for this to show up?

This is totally my fault for being brazen with the upgrade.

**Comment by tonyhutter** [comment]
I see that FC27 is scheduled to be released next week (https://fedoraproject.org/wiki/Releases/27/Schedule). I'll include packages for it in the upcoming 0.7.4 release.  We don't have a fixed release schedule, but I'd estimate something coming in the mid/late December or early January timeframe.  In the meantime, you can try building form source.

**Comment by brmather** [comment]
Thanks for your reply. I've built spl and zfs from source, but I can't open my zpool because "the pool has been upgraded to a newer, incompatible on-disk version." Do you know any way around this?

**Comment by kkretschmer** [comment]
Please check if dnf switched to zfs-fuse due to dependency issues w.r.t. `/bin/ksh` (#6467). This happened to me when upgrading to Fedora 27. For now I worked around the issue by building my own rpms from source and installing them with `rpm --nodeps`.

**Comment by brmather** [comment]
Thanks for the update. Can you clarify how you got it working? I built the rpms from source and installed them - dkms status now lists spl and zfs version 0.7.3 - but any zfs or zpool command requires zfs-fuse which is still at 0.7.2.2.

**Comment by kkretschmer** [comment]
I force-deinstalled zfs-fuse (`rpm -e --nodeps zfs-fuse`), which was pulled in as a dependency of libvirt-daemon-driver-storage-zfs. The I installed the newly-built rpms via `rpm -i --nodeps`, checked DKMS status, updated intramfs (I use a ZFS root file system). Possibly you still have zfs-fuse installed. zfs-fuse 0.7.2 only supports pool version 28.

**Comment by aalba6675** [comment]
Another change required: in F27 the ksh package provides /usr/bin/ksh, not /bin/ksh

Installing zfs-dkms-0.7.3 from Fedora 26 on Fedora 27
```
$ sudo dnf install ./zfs-dkms-0.7.3-1.fc26.noarch.rpm 
Last metadata expiration check: 0:03:12 ago on Sun 05 Nov 2017 10:27:09 PM +08.
Error: 
 Problem: conflicting requests
  - nothing provides /bin/ksh needed by zfs-dkms-0.7.3-1.fc26.noarch
```
```
$ dnf provides /bin/ksh
Last metadata expiration check: 1:03:59 ago on Sun 05 Nov 2017 09:23:00 PM +08.
Error: No Matches found
```

```
$ dnf provides /usr/bin/ksh
Last metadata expiration check: 1:04:31 ago on Sun 05 Nov 2017 09:23:00 PM +08.
ksh-20120801-41.fc27.x86_64 : The Original ATT Korn Shell
Repo        : @System
Matched from:
Filename    : /usr/bin/ksh

ksh-20120801-41.fc27.x86_64 : The Original ATT Korn Shell
Repo        : fedora
Matched from:
Filename    : /usr/bin/ksh
```

**Comment by brmather** [comment]
Thanks! Removing `zfs-fuse` and installing the rpms compiled from source did the trick.

**Comment by seitzbg** [comment]
Indeed I am having this issue going from F26 to F27:

`[root@torserv seitz]# sudo dnf system-upgrade download --refresh --releasever=27
Before you continue ensure that your system is fully upgraded by running "dnf --refresh upgrade". Do you want to continue [y/N]: yes
Fedora 27 - x86_64 - Updates                                                                                                                                         3.4 kB/s | 373  B     00:00
Fedora 27 - x86_64                                                                                                                                                    28 MB/s |  58 MB     00:02
RPM Fusion for Fedora 27 - Free - Updates                                                                                                                             51 kB/s | 1.7 kB     00:00
RPM Fusion for Fedora 27 - Free                                                                                                                                      491 kB/s | 706 kB     00:01
Failed to synchronize cache for repo 'zfs', disabling.
Last metadata expiration check: 0:00:00 ago on Tue 07 Nov 2017 07:04:36 PM EST.
Error:
 Problem: package zfs-dkms-0.7.3-1.fc26.noarch requires /bin/ksh, but none of the providers can be installed
  - ksh-20120801-35.fc26.x86_64 does not belong to a distupgrade repository
  - problem with installed package zfs-dkms-0.7.3-1.fc26.noarch
`

**Comment by behlendorf** [comment]
The fix for this, https://github.com/zfsonlinux/zfs/pull/6835, was applied to master and will be applied to the next point release.

**Comment by avsej** [comment]
Fedora has been released recently. Any plans to deploy F27 repository of zfs and http://download.zfsonlinux.org/fedora/zfs-release.fc27.noarch.rpm?

**Comment by aruiz** [comment]
With regards to the zfs-fuse problem, it looks like there's an opportunity here to move the userland tools upstream and have zfs-fuse and the kernel drivers being different packages. Have you considered reaching out to the zfs-fuse maintainer to talk about this?

**Comment by turkstra** [comment]
I noticed above that the implied timeline on a new repo for F27 is "mid/late December or early January timeframe." Is there any chance you might consider doing it earlier? That's quite a while to wait before being able to upgrade to F27. Usually in the past you guys have been pretty good about providing an updated repo when a new version of Fedora is released. I know I'm not the only one that would appreciate this :-) Regardless, thank you for everything you all do. I love being able to use ZFS on Linux!

**Comment by tonyhutter** [comment]
@turkstra thanks for your patience, we haven't forgotten F27 users!  Ideally we would have supported F27 with 0.7.3 in October, but the patches weren't available.  I'm actively working on putting together a 0.7.4 release that will support F27 and the 4.14 kernel.  I wouldn't expect anything until the first week of December at the earliest though (due to Thanksgiving break).  Note that the zfs master branch will build under F27.

**Comment by edgan** [comment]
I just upgraded my Fedora 26 system to Fedora 27. I had zfs-0.7.3 installed, and the upgrade just worked. The ksh pakage wasn't an issue. I downloanded, https://www.rpmfind.net/linux/fedora/linux/updates/27/x86_64/Packages/k/ksh-20120801-42.fc27.x86_64.rpm , and installed it before running dnf system-upgrade.

**Comment by sm6rpz** [comment]
Note that the ksh package (is about to be) updated, see https://bugzilla.redhat.com/show_bug.cgi?id=1513096 I.e. the new Fedora ksh package will now provide /bin/ksh just as expected.

**Comment by kaspergrubbe** [comment]
@edgan That is some good information, thanks for sharing it.

I think I will hold back a bit until an official release have been made, then I can test it out.

**Comment by behlendorf** [comment]
Closing, zfs-0.7.4 tagged, Fedora 27 repository created, upstream ksh package from Fedora updated to provide /bin/ksh.
