### ISSUE TITLE
ZFS kmod not available for kernel 4.13 (Centos 7.4)

### ISSUE THREAD

**Issue by kvaps** [zfsonlinux/zfs#6831]
Hi, Centos switch kernel from `3.10` to `4.13` and now kmod is not accessible.

Now it goes by default from `7.4` version:
```
# cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core) 
```
```
# uname -a
Linux localhost.localdomain 4.13.11-1.el7.elrepo.x86_64 #1 SMP Thu Nov 2 11:29:36 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
```
Please update kmod binaries for `4.13` kernel.

**Comment by behlendorf** [comment]
@kvaps the [default CentOS 7.4 kernel](http://mirror.centos.org/centos/7/os/x86_64/Packages/)  is still 3.10 based.  Packages aren't provided for kernels from the ml or cr repositories which change more quickly, but you can easily [roll your own](https://github.com/zfsonlinux/zfs/wiki/Custom-Packages).
