### ISSUE TITLE
export -f : pool busy

### ISSUE THREAD

**Issue by dmaziuk** [zfsonlinux/zfs#6855]
```
zpool export -f tank
cannot export 'tank': pool is busy
```
This is in high-availability context: two head nodes connected to dual-ported SAS shelves, ZFS on multipathed disks, `ucarp` managing the "cluster ip" and running `zpool import -f -o cachefile=none "tank"`/`zpool export -f "tank"` on startup/shutdown.

As best I can tell, `nfsd` is keeping the pool busy and not letting it get exported (see also #6000). 

I have the same behaviour in drbd/pacemaker clusters, it's not zfs-specific. I have a feeling it may have existed on centos 6, too, but there with `heartbeat` I used custom nfs shutdown scritps that `killall -9`'ed runing `nfsd`'s. Now with improved nfs and `systemd` running the show in centos 7 it got much worse.

Can we still make usable systems out of this somehow? Is it possible to have `zpool export --kill` along the lines of `umount -f`/`fuser -k` perhaps?

**Comment by behlendorf** [comment]
This behavior isn't specific to ZFS and I'm told people do find Linux a usable system.

Bottom line the Linux kernel won't let you unmount a filesystem if there is a process with open file handles (nfsd is a similar story).  This is different than on other platforms but it's implemented in the VFS and applies to all Linux filesystems.

Something like `zpool export --kill` could be added to force kill processes using the filesystem.  But it's not clear this logic belongs in ZFS at all.  It wouldn't be able to do anything more advanced than what could be added more easily and flexibly to a wrapper script.

**Comment by dmaziuk** [comment]
OK so right now I just run 
```
zpool export -f tank
```
and it works sometimes. Do you think I'll have better luck with explicit
```
zfs unshare -a
zfs umount -a -f
zpool export -f tank
```
Or would that make no difference and I should try going after the offending `nfsd`s instead?

**Comment by behlendorf** [comment]
It shouldn't make a difference, internally `zpool export` will call `unshare` and `umount` if needed.  I'd suggest using the nfs service provided by pacemaker instead of `zfs share`.  In the most recent version there's also a zfs service provided.

**Comment by dmaziuk** [comment]
Thanks. My pacemaker setups (w/ DRBD) have the same problem, actually, that's why I went with `ucarp` on this one. (And `pacemaker` being at best an overkill for 2-node active/passive setups.) Linux-HA folks blame `systemd` for not killing `nfsd` threads properly on "stop".

I guess I'll see if I can find time and hardware to play with "nosystemd" ubuntu LTS... between changing kernel ABI on every point release and this I'm certainly not deploying any more centos 7 servers if I can help it.
