### ISSUE TITLE
Rpm dependency problem with zfs-dkms on Fedora 27

### ISSUE THREAD

**Issue by sm6rpz** [zfsonlinux/zfs#6878]
As mentioned in Fedora bug 1513096 https://bugzilla.redhat.com/show_bug.cgi?id=1513096 the Fedora ksh package has changed its provides so that the zfs-dkms rpm- package no longer recognise that the ksh shell is installed.

Zfs-dkms has a dependency for /bin/ksh, that the Fedora 27 ksh rpm-package does not have a provide for.

One solution is to change the dependency from /bin/zsh to the package zsh (see comment 9 in Fedora bug mentioned above).

**Comment by behlendorf** [comment]
This was addressed in master, 12954494a1bfe4c115332049cca1704d865f72d0, 13589da974e4e808b16d7dd280744277bb8d079b, by disabling automatic dependency generation for those packages.  The alternative was the change a few hundred scripts with `#!/bin/ksh` which would have broken dependencies on other distributions.  These changes will be applied to 0.7.4 at which point we'll create a Fedora 27 repository.
