### ISSUE TITLE
Weird scrub statistics

### ISSUE THREAD

**Issue by lnicola** [zfsonlinux/zfs#6887]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Arch Linux
Distribution Version    | N/A
Linux Kernel                 | 4.13.12-1-ARCH
Architecture                 | x86-64
ZFS Version                  | 0.7.0-186_g99834d195
SPL Version                  | 0.7.0-20_g35a44fc

### Describe the problem you're observing

The scrub statistics make no sense:

```text
  scan: scrub in progress since Mon Nov 20 08:05:32 2017
	67.8G scanned at 48B/s, 85.6T issued at 0B/s, 855G total
	0B repaired, 10257.36% done, no estimated completion time
```

If it sounds like a version mismatch, I just re-created my `initramfs` and rebooted.

The `total` value is correct, and `scanned` might be, too. Scrub takes about 3.5 h, which is the same as before. Pool is a 2x2 TB mirror.

### Describe how to reproduce the problem

```bash
zpool scrub tank
zpool status
```

**Comment by tcaputi** [comment]
This looks to me like you may have updated your zfs binaries but not the kernel module. d4a72f23863382bdf6d0ae33196f5b5decbc48fd should provide a noticeable improvement in scrub performance and I could definitely see how an out-of-sync kernel module might report weird statistics to userspace.

You should be able to check the kernel module version with `cat /sys/module/zfs/version`. If it is out of date you might just need to export your pool, run `modprobe -r zfs; modprobe zfs` and reimport your pool.

**Comment by lnicola** [comment]
@tcaputi As I mentioned in the report, I rebooted because it looked exactly like a version mismatch. But I should have checked the version numbers, as `0.7.0-186_g99834d195` is before https://github.com/zfsonlinux/zfs/commit/d4a72f23863382bdf6d0ae33196f5b5decbc48fd. So my `zfs` package has the wrong version of the kernel modules.

**Comment by lnicola** [comment]
Fixed by https://github.com/zfsonlinux/zfs/pull/6909. As an aside, scrub times have improved from 3.5 h to 2.5 h.
