### ISSUE TITLE
ZFS block diff

### ISSUE THREAD

**Issue by opnoack** [zfsonlinux/zfs#6893]
Hi folks,

I am curious if there is any way to get a list of changed blocks between two snapshots, e.g. like rbd diff here:

`rbd diff --from-snap snap1 pool/image@snap2 --format plain`

There is only zfs send and receive, but that doesn't really help me as I only need the metadata. Can you assist me with this?

Kind regards,
Oliver

**Comment by kpande** [comment]
this is a question better suited for [the zfs-discuss mailing list](http://list.zfsonlinux.org) since it's a support thing and not a bug. thanks oliver!
