### ISSUE TITLE
Support for Docker in unprivileged LXD

### ISSUE THREAD

**Issue by tomposmiko** [zfsonlinux/zfs#6896]
This is basically a feature request. I hope this is the right place for that.
My goal is running any kind of Docker in LXD containers. The very best example is mysql.
According to LXD devs it's a ZFS issue.
Could someone confirm it? Does is really require changes to the ZFS codebase ? What kind of? How much work does it mean?

For history please see the following issue:

https://github.com/lxc/lxc/issues/1001

Especially the following comment from Christian Brauner.

Fwiw, Docker does currently not support running the overlay graphdriver on most cow systems, effectively they just suggest you use overlay with ext4. However, with kernel 4.7 it will be possible to use it at least on btrfs. I'm not super familiar with zfs but e.g. the incompatibility between overlay and btrfs stemmed from the fact that btrfs until this commit did not implement RENAME_{EXCHANGE,WHITEOUT} which overlay requires. A similar problem might apply to zfs.

I would be happy with both aufs and overlayfs.

**Comment by kpande** [comment]
that sounds theoretical. others (myself) are using overlayfs without issue and docker itself has a zfs driver.

**Comment by kpande** [comment]
if you wouldn't mind first discussing this on [the zfs-discuss mailing list](http://list.zfsonlinux.org) first to determine if there's a better solution before opening up a feature request
