### ISSUE TITLE
Missing instructions in wiki Debian Stretch Root on ZFS

### ISSUE THREAD

**Issue by BluGen** [zfsonlinux/zfs#6899]
In the section Troubleshooting -> Rescuing using a Live CD the command `apt install --yes zfs-dkms` will fail, because the package zfs-dkms is in the contrib repository. By default this is not activated in the latest debian live images. It has to be added like in install step 1.4 already shown.

Also after installing the zfs-dkms package, the zfs module has to be loaded with `modprobe zfs`. This instruction is missing in the install steps too.

@gmelikov @rlaager

**Comment by gmelikov** [comment]
Thanks, added redirection to needed step.
