### ISSUE TITLE
draidcfg utility

### ISSUE THREAD

**Issue by qwertyx64** [zfsonlinux/zfs#6915]
Hi, where Can I find draidcfg utility? I would like to try dRAID, but I cant find draidcfg. Thank you.

**Comment by gmelikov** [comment]
It's in #5841 pull request, please use mailing lists for support questions next time, closed.

**Comment by behlendorf** [comment]
This feature is still under development but feedback and testing are welcome.  You can find the latest version in the PR and some additionial documentation on the wiki https://github.com/zfsonlinux/zfs/wiki/dRAID-HOWTO.

**Comment by mjm455** [comment]
Sorry to dig up an old thread but has draid feature been put into the official 0.8.x release?  I don't seem to be able to find those features anymore but would like to try them.

**Comment by behlendorf** [comment]
@mjm455 since development is still in progress the feature was not included in 0.8.
