### ISSUE TITLE
Support for Linux 4.14 in ZOL 0.7.4 ?

### ISSUE THREAD

**Issue by Bronek** [zfsonlinux/zfs#6929]
It appears that release 0.7.3 does not support Linux kernel 4.14 - at least not explicitly. Should we (users) expect release 0.7.4 with this support explicitly listed? Thank you for all your good work :)

**Comment by tonyhutter** [comment]
@Bronek correct, 4.14 will be supported on zfs-0.7.4.

**Comment by farwayer** [comment]
@tonyhutter any ETA for 0.7.4? It is already fixed in `spl` and patch is not too large. So maybe it's better to release fix as 0.7.3.1?

**Comment by tonyhutter** [comment]
@farwayer 0.7.4 should be out next week.  The patches currently in the `zfs-0.7-release` branch are the ones I'm going to use.   It's just a matter of going though all the motions to generate a release.

**Comment by tonyhutter** [comment]
released: https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.7.4

**Comment by chrisrd** [comment]
The last line of the https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.7.4 release notes is
```
Linux 4.15 compat: timer updates #670 #671
```

I don't know if it's too late to change, but these should specify they're SPL issues, and hopefully link across there...

There was a question on zfs-discuss about this:

http://list.zfsonlinux.org/pipermail/zfs-discuss/2018-February/030483.html

**Comment by chrisrd** [comment]
...oops, sorry, that was meant to go into #7051. Reposting over there...
