### ISSUE TITLE
Pool imported on both nodes despite using multihost property

### ISSUE THREAD

**Issue by gusioo** [zfsonlinux/zfs#6933]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Debian
Distribution Version    | Jessie
Linux Kernel                 | 4.4.45
Architecture                 | x64
ZFS Version                  | 0.7.2-1
SPL Version                  | 0.7.2-1

### Describe the problem you're observing
I have shared pool with enabled multihost in following configuration:

Node-A:

```
root@192.168.251.77:~$ zpool status
   pool: Pool-0
  state: ONLINE
   scan: none requested
config:

         NAME                                            STATE READ 
WRITE CKSUM
         Pool-0 ONLINE       0     0     0
           mirror-0 ONLINE       0     0     0
             scsi-0QEMU_QEMU_HARDDISK_drive-scsi0-0-0-6 ONLINE       0     0     0
             scsi-0QEMU_QEMU_HARDDISK_drive-scsi1-0-0 ONLINE       0     0     0

errors: No known data errors
```
Node-B:

```
root@192.168.251.76:~$ zpool import
    pool: Pool-0
      id: 12868391378107479450
   state: UNAVAIL
  status: The pool is currently imported by another system.
  action: The pool must be exported from node-c137b00b (hostid=c137b00b)
         before it can be safely imported.
    see: http://zfsonlinux.org/msg/ZFS-8000-EY
  config:

         Pool-0                                          UNAVAIL 
currently in use
           mirror-0                                      ONLINE
             scsi-0QEMU_QEMU_HARDDISK_drive-scsi0-0-0-6  ONLINE
             scsi-0QEMU_QEMU_HARDDISK_drive-scsi1-0-0    ONLINE
```

When I try to import Pool-0 on Node-B I got following errors (these are expected):

```
root@192.168.251.76:~$ zpool import Pool-0
cannot import 'Pool-0': pool is imported on node-c137b00b (hostid: 0xc137b00b)
Export the pool on the other system, then run 'zpool import'.
```

```
root@192.168.251.76:~$ zpool import Pool-0 -f
cannot import 'Pool-0': pool is imported on host 'node-c137b00b' (hostid=c137b00b).
Export the pool on the other system, then run 'zpool import'.
```

However, when I use separate cache file and force parameter for zpool import command then it's possible to import pool (even though it is imported by another system).

```
root@192.168.251.76:~$ zpool import 12868391378107479450 Pool-0 -c /tmp/Pool-0.cache
cannot import 'Pool-0': pool is imported on node-c137b00b (hostid: 0xc137b00b)
Export the pool on the other system, then run 'zpool import'.
```

```
root@192.168.251.76:~$ zpool import 12868391378107479450 Pool-0 -c /tmp/Pool-0.cache -f
```

Pool-0 was imported on Node-B without errors and was active on both nodes.

Is this expected or a bug?

**Comment by behlendorf** [comment]
@gusioo thanks for reporting this.  That is not expected, even with the cache file the pool should not be importable.  Let me pull in @ofaaland and we'll see about reproducing this and determining the root cause.

**Comment by DaFresh** [comment]
I wonder if disabling the cache file (zpool set cachefile=none pool0) could be a temporary work around ?

**Comment by DaFresh** [comment]
I wonder if disabling the cache file (-o cachefile=none) at the pool creation and import could be a temporary workaround ?

**Comment by behlendorf** [comment]
Yes, disabling the cachefile would avoid any potential issue.

**Comment by behlendorf** [comment]
@gusioo PR #6971 opened with a fix, we'll see about getting it in the next 0.7 release.

**Comment by devZer0** [comment]
i have the same problem - i have multihost=on, and a day later after starting both nodes freshly - i wonder why the pool is imported/mounted on both nodes!!

on the second node (which was booted later on),  i see this warning

[  296.360648] WARNING: MMP writes to pool 'hostmirrorpool' have not succeeded in over 5s; suspending pool 
[  296.360654] WARNING: Pool 'hostmirrorpool' has encountered an uncorrectable I/O failure and has been suspended.

why does that pool get imported and mounted at all, when i even cannot do that manually ? have there been changes between 0.7.12 and 0.8rc?  i'm sure, after exporting on node1 i needed "-f" before i could import it on node2, so i'm curious why (with 0.8rc) it now gets imported automatically

**Comment by gmelikov** [comment]
@devZer0 please describe your installation - is it 1 JBOD with 2 servers connected via HBA cards? `multihost=on` is sensitive for RW delays.

**Comment by kpande** [comment]
we determined their issue on IRC. there is a weakness in MMP implementation when one pool is SUSPENDED but the `failmode` is not `=panic`, the original host stays up until the admin runs 'zpool clear' and then both systems have the pool imported.

**Comment by devZer0** [comment]
i'm not sure if there is another "chance" for accidental parallel import - but i had run concurrent export/import in a loop on two different nodes accessing a shared zpool and i had seen at least 2 occurences that the pool was active on both even without being suspended intermittedly. i managed to competely corrupt it that way. i guess there is chance for "race condition".

**Comment by ofaaland** [comment]
@devZer0 I just created a PR to prevent pool from being resumed when multihost is enabled, and to update the manpage to inform users that is disallowed beccause it would be unsafe.  #8460
