### ISSUE TITLE
Documentation error: conflicting information on the zpool manpage regarding removing log devices

### ISSUE THREAD

**Issue by DurvalMenezes** [zfsonlinux/zfs#6938]
### System information

Type                                | Version/Name
  ---                                  |     --- 
ZFS Version                  | 0.7.3-1

### Problem description 
"man zpool" shows conflicting information; please compare: 

       zpool remove pool device ...
           Removes  the  specified  device  from the pool. This command currently only supports
           removing hot spares, cache, **and log devices.** 

And 

       Intent Log
        (...)
        Log  devices can be **added, replaced, attached, detached, and imported** and exported as part
        of the larger pool. Mirrored log devices can be removed by specifying the top-level mirror for the log.

Please note that the first paragraph states that log devices can be removed (with the `zpool remove` command) while the 2nd part (specific to the log devices) doesn't say it can, except if the log is mirrored (and in that case, I believe the right command would be `zpool detach`, not `zpool remove`, and therefore it should not be called "removing"). 

### Steps to reproduce

Just install ZoL and issue a `man zpool`, and search for the above paragraphs. 

NOTE: this issue has been discussed in the zfs-discuss mailing list and there was consensus that it indeed is a bug to be reported, please see here: http://list.zfsonlinux.org/pipermail/zfs-discuss/2017-December/030031.html

**Comment by ahrens** [comment]
The existing phrasing is correct about removing mirrors, but you're right that we should explicitly mention that that log devices can be removed in the `Intent Log` section.  We might also break out the import/export into another sentence like, `Log devices are part of their containing pool and "zpool import/export" treats them the same as other devices in the pool.`
