### ISSUE TITLE
ZFS stopped working on Debian after update to Strech. Reinstall problems.

### ISSUE THREAD

**Issue by urza** [zfsonlinux/zfs#6942]
Hi, I was using ZFS on Linux for few years on Debian Jessie. Recently I upgraded to Debian Stretch and after Reboot ZFS stopped working:
```

The ZFS modules are not loaded.
Try running '/sbin/modprobe zfs' as root to load them.
```

I found people with [same problem but on Ubuntu ](https://askubuntu.com/questions/936023/zfs-modules-are-not-loaded)recommending to uninstall and install zfs again.  So I undinstalled ZFS:

`sudo apt remove debian-zfs libzfs2 zfs-dkms zfsonlinux zfsutils`

and then installed it again following [install instruction on this repository for debian](https://github.com/zfsonlinux/zfs/wiki/Debian). However on command:

`apt-get install zfs-dkms zfsutils-linux`

I have this error:

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package zfs-dkms is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'zfs-dkms' has no installation candidate
E: Unable to locate package zfsutils-linux
```

What can I do?

**Comment by gmelikov** [comment]
This package is in contrib repository https://packages.debian.org/source/stretch/zfs-linux . Please enable it.

Please next time use our mailing lists for support.
