### ISSUE TITLE
zfs receive stall in D state 

### ISSUE THREAD

**Issue by bud4** [zfsonlinux/zfs#6946]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Ubuntu
Distribution Version    |16.04.3 LTS
Linux Kernel                 | 4.4.0-101-generic
Architecture                 | x86_64
ZFS Version                  | 0.6.5.6-0ubuntu16
SPL Version                  | 0.6.5.6-0ubuntu4
### Describe the problem you're observing
zfs receive stall in d state and it does not proceed. more than an hour without writing anything. 
### Describe how to reproduce the problem
big load many asynchronous readings in progress.
### Include a warning/errors/backtraces from the system logs
look at the mbuffer log . no message in kernel.log
[mbuffer_rcv512987816.log](https://github.com/zfsonlinux/zfs/files/1547505/mbuffer_rcv512987816.log)
'''
ps alx output:
4     0 135944 135886  20   0  54080 24092 cv_wai D    ?          0:26 /sbin/zfs receive -v -F pool_z2_samba

cat  /proc/135944/syscall 16 0x3 0x5a1b 0x7ffc94eb6e30 0x25 0x7f896dc69780 0x7f896eda9780 0x7ffc94eb6ad8 0x7f896d99ff07
'''

**Comment by Fabian-Gruenbichler** [comment]
which version is in use on the system generating the zfs send stream? potentially you are affected by the issue fixed in https://github.com/zfsonlinux/zfs/pull/6616

**Comment by bud4** [comment]
All two system are 6.5. May be my case?

Il 11 dic 2017 1:37 PM, "Fabian-Gruenbichler" <notifications@github.com> ha
scritto:

which version is in use on the system generating the zfs send stream?
potentially you are affected by the issue fixed in #6616
<https://github.com/zfsonlinux/zfs/pull/6616>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/zfsonlinux/zfs/issues/6946#issuecomment-350712447>, or mute
the thread

**Comment by kpande** [comment]
please use [the zfs-discuss mailing list](http://list.zfsonlinux.org) for support requests, you might want to try 0.7.4 which has a lot of improvements over the 0.6.5 series.
