### ISSUE TITLE
New feature: drop DDT entries

### ISSUE THREAD

**Issue by ggzengel** [zfsonlinux/zfs#6947]
In #5904 I have a very big DDT even when I disable dedup on all file systems.
I want to get rid of the DDT entries.

I think it's best to have an import option which resets the DDT.

**Comment by AndCycle** [comment]
no, there is no easy way to do this, even if you disable the dedup, the file previous exist on the file system are still using it, there is no magic way to do the job,

the only way to complete get ride of it is moving out all your data then recreate the pool.

**Comment by ggzengel** [comment]
> the only way to complete get ride of it is moving out all your data then recreate the pool.

That's why I think it's a good idea to have a option to drop DDT.

I don't have the possibility to drop the pool:

```
zpool list -v
NAME   SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
zpool1  96.8T  85.7T  11.0T         -    52%    88%  1.13x  ONLINE  -
  raidz3  53.5T  50.9T  2.61T         -    58%    95%
    ZFS_VOL01      -      -      -         -      -      -
    ZFS_VOL02      -      -      -         -      -      -
    ZFS_VOL03      -      -      -         -      -      -
    ZFS_VOL04      -      -      -         -      -      -
    ZFS_VOL05      -      -      -         -      -      -
    ZFS_VOL06      -      -      -         -      -      -
    ZFS_VOL07      -      -      -         -      -      -
    ZFS_VOL08      -      -      -         -      -      -
    ZFS_VOL09      -      -      -         -      -      -
    ZFS_VOL10      -      -      -         -      -      -
    ZFS_VOL11      -      -      -         -      -      -
    ZFS_VOL12      -      -      -         -      -      -
    ZFS_VOL13      -      -      -         -      -      -
    ZFS_VOL14      -      -      -         -      -      -
    ZFS_VOL15      -      -      -         -      -      -
  raidz3  43.2T  34.9T  8.39T         -    46%    80%
    ZFS_VOL17      -      -      -         -      -      -
    ZFS_VOL18      -      -      -         -      -      -
    ZFS_VOL19      -      -      -         -      -      -
    ZFS_VOL20      -      -      -         -      -      -
    ZFS_VOL21      -      -      -         -      -      -
    ZFS_VOL22      -      -      -         -      -      -
    ZFS_VOL23      -      -      -         -      -      -
    ZFS_VOL24      -      -      -         -      -      -
log      -      -      -         -      -      -
  mirror  48.2G  1.41M  48.2G         -    24%     0%
    ZFS_ZIL1      -      -      -         -      -      -
    ZFS_ZIL2      -      -      -         -      -      -
cache      -      -      -         -      -      -
  ZFS_CACHE1   324G   314G  9.80G         -     0%    96%
  ZFS_CACHE2   324G   314G  9.80G         -     0%    96%
spare      -      -      -         -      -      -
  ZFS_VOL16      -      -      -         -      -      -
```

**Comment by lundman** [comment]
I think Ahrens mentioned an idea about dropping overflow DDT entries in the talk https://www.youtube.com/watch?v=PYxFDBgxFS8
Perhaps that idea could be abused by decreasing the ddt size until its 0

**Comment by rincebrain** [comment]
@lundman that trick only works for items where you have n=1 entries by special casing n=1, I don't think you can induct on it readily.

@ggzengel The problem is that the DDT is required to know where the data on disk is for any given item, and the kind of rewrite mechanism that would be required to drop the DDT would have severe performance penalties as well, at best. These are the reasons that the man page for zfs says
 ```
Deduplicating data is a very resource-intensive operation. It is generally recommended that you have at least 1.25 GiB of RAM per 1 TiB of storage when you enable deduplication. Calculating the exact requirement depends heavily on the type of data stored in the pool.
```
and a lot of recommended practices guides for ZFS say "don't do this, no, really, we promise".

Depending on the size of the individual datasets, you could zfs send|recv them onto the same pool, in a path that has dedup=off, and once received, the received copy will not have dedup enabled; then you could destroy the deduplicated copy, and repeat.

The _other_ problem I see is that, with a dedupratio of 1.13 to 1, you'd more than fill your pool if you did this for all the data currently on there, unless I'm terrible at math.

**Comment by ggzengel** [comment]
But they didn't write that the DDT never shrinks even if it's empty. That's my problem.

**Comment by DeHackEd** [comment]
That's actually a known problem (see #5916, #4933). A ZAP never shrinks once its grown.

**Comment by ggzengel** [comment]
So it's necessary to have a option to drop it completely.

**Comment by DeHackEd** [comment]
ZFS in general needs to opportunistically or on-demand support a ZAP rebuild, possibly demoting to a microzap. An optimization that a ZAP gets turned into an empty microcap if it's ever cleaned out makes a lot of sense.

**Comment by ggzengel** [comment]
I think to drop DDT is easier to implement than optimizing the whole file system at runtime.

**Comment by DeHackEd** [comment]
This is where I'm confused. There's a bit in the block pointer indicating the block is in the DDT at all. Even if the DDT is empty but enormous, it won't be consulted for deletes/overwrites since it's empty, and if `dedup=off` nothing will get put into it either. So who cares? It takes some space on disk, but it stays out of your RAM.

As for simply dropping one full of data, you can't. Off the top of my head, if you simply drop the DDT, you must make sure that

1. No block stored in the DDT has a reference count higher than 1
2. Dedup is off forever
2a. Alternative: replace the DDT with a simple block counter that decrements whenever a dedup'd block is deleted and dedup mode is unlocked when this counter eventually reaches 0.

Or alternatively, your pool is read-only forever but at that point who cares about the DDT?

**Comment by AndCycle** [comment]
@ggzengel no, your DDT is not empty at all, dedup raton 1.13 clear means there are things still using is, any file operation during your dedup=on period has use the table, don't make false sense about the off, off only means any future file operation won't use it, what have happened stays there.

**Comment by ggzengel** [comment]
I know a lot about dedup and I know that this system still has shared blocks.
I have a lot of systems at my customers and some waste memory it could use for caching.

> dedup: DDT entries 5248804, size 38.2K on disk, 4.24K in core
This system wastes 30GB RAM.

Even with send and receive the DDT won't shrink.

Is somebody here who exactly knows about the internal structure of ZFS?
Where is the block usage counter? Is it only in the DDT?
If yes, than it is to difficult, because each block has to be cloned and the reference has to be searched and patched.
If not, the reference to the DDT has to be cleared and the DDT could be dropped.

If it's really not easy, than optimize the DDT on import.

**Comment by ggzengel** [comment]
Dedup would be a very effective mechanism if you have block usage counter outside DDT and could drop the DDT.

In the early days you are always activating dedup while migrating to the new system. So you will save space on the file system.
Later (in production) if the DDT grows above a limit or the system slows down you are deactivating dedup and dropping the DDT.
If you need dedup on rare file systems you can activate dedup and resend them.

**Comment by ggzengel** [comment]
Isn't there anybody who can write code to drop the DDT?
To drop it on zpool import is more than enough.

**Comment by ggzengel** [comment]
I really need dropping the DDT.
Is anybody here which can write some code for ignoring the DDT while opening a zpool?

**Comment by kpande** [comment]
nope

**Comment by ggzengel** [comment]
@kpande What does nope mean? Can't deduplicated blocks not exist without DDT?

**Comment by bunder2015** [comment]
No, you need a DDT or else you have no idea whether you need to write new blocks or not.

**Comment by ggzengel** [comment]
@bunder2015 I don't understand. Is ZFS inconsistent if you disable dedup and drop the DDT?

**Comment by DeHackEd** [comment]
You can't do it. Any more than you can write to a snapshot. The design depends on it.

**Comment by ggzengel** [comment]
Would it ever be possible to drop the DDT in future or is it so too much too change on internal structure?
What would you prefer?
1. Optimize DDT
2. Make drop of DDT possible

**Comment by kpande** [comment]
no but you may be interested in #8420 should work ever begin on that.

**Comment by Harvie** [comment]
I have destroyed ZFS dataset containing deduped data, recreated it with dedup=off, but the DDT seems to remain:

`dedup: DDT entries 25572574, size 512B on disk, 165B in core`

Do i really need to recreate whole pool? I was kinda expecting that it will be enough to remove the dataset. Annoying...

**Comment by Harvie** [comment]
Ok. nevermind. After removing the ~2TB dataset it took two days of some background job to clean up the DDT, but it eventualy disappeared. Now it shows:

`dedup: no DDT entries`

Also it took the same amount of time to reclaim the free space. I would say that 1TB reclaimed per day is rather slow. given it's just two drives in mirror on reasonably recent server hw. Not really a problem in my use case, but i guess there's plenty of room for improvement.
