### ISSUE TITLE
Remap a ZFS record to a new physical sector

### ISSUE THREAD

**Issue by sjuxax** [zfsonlinux/zfs#6978]
I have a ZFS disk from a striped, non-redundant pool (experimental for non-critical data) that has developed a relatively small number of bad blocks. These reads are affecting several large files and cause checksum and read errors on the pool when scrubbed.

Using ddrescue, I have been able to get a successful read in and around and most of the bad sectors on the failing disk, but I skipped the sectors that haven't presented problems to a) avoid worsening the disks's condition and b) save time by not reading extra data from a dying disk. That means that I can't just mount this image or treat it as an otherwise functional filesystem, so I can't copy the corrupted/missing parts of the file over logically (probably wouldn't be able to do this anyway since the data was striped).

I'm looking for a way to manually recover by copying the correct values into known-good sectors on the disk and then updating the ZFS records to know that they should look for the data at the new physical sector instead of the old one. I understand that this is probably exactly what ZFS would've done if the affected zpool were redundant.

Is there a way to do this from userspace with a non-ZFS device, like my disk image of the damaged blocks only? I was hoping that I could get the explicit list of corrupted records and probe in a new value for it through `zdb` or similar. Short of this, I will probably just have to bite the bullet and hope that I can get eventually get a 100% complete image from the dying disk before it plops all the way out.

**Comment by DeHackEd** [comment]
"Update ZFS records" requires block pointer rewrite which is explicitly not supported at this time.

**Comment by kpande** [comment]
please use [the zfs-discuss mailing list](http://list.zfsonlinux.org) for support requests.
