### ISSUE TITLE
Increasing zfs_vdev_aggregation_limit with zvols

### ISSUE THREAD

**Issue by zielony360** [zfsonlinux/zfs#6979]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Debian
Distribution Version    | 7
Linux Kernel                 | 4.0.4
Architecture                 |x86_64 
ZFS Version                  | 0.6.5.7
SPL Version                  | 0.6.5.7

### Describe the problem you're observing
Hello,

we have pool consisting 5 x 10-disk raidz2 group and using zvols with volblocksize=128k, shared through LIO FC target. Due to the fact that zfs_vdev_aggregation_limit is limited to 128k too, writes on singular disk are very small, like 13 kB average, what causes performance issues. Unfortunately, there is no large blocks for zvols to prevent it.

My questions are:
1. Can I somehow safely increase zfs_vdev_aggregation_limit to 512 kB with existing configuration?
2. If not, how can I migrate to large blocks datasets using the same pool? I mean I would like to create datasets, set recordsize=512k on them, but also raise zfs_vdev_aggregation_limit to make it sensible. For some time zvols will coexist with datasets during such migration.

### Describe how to reproduce the problem
Create a pool with wide raidz2 vdevs and use zvols.

**Comment by zielony360** [comment]
I think #4512 may be also related to the case, as we have no merges on physical block devices (HDDs). Maybe if there are some merges on HDDs, then I won't have to cope with higher aggregating on vdevs.

**Comment by gmelikov** [comment]
`zfs_vdev_aggregation_limit` size was changed in master branch (last comment with changes https://github.com/zfsonlinux/zfs/commit/d4a72f23863382bdf6d0ae33196f5b5decbc48fd), 
and you can change it manually in 0.7.* release too (for ex. `echo '1048576' > /sys/module/zfs/parameters/zfs_vdev_aggregation_limit`)

feel free to reopen the issue if it didn't help.

**Comment by zielony360** [comment]
@gmelikov Does this commit apply to zvols too?

**Comment by gmelikov** [comment]
@zielony360 IIRC zfs_vdev* parameters are for vdevs, not zvol/dataset specific.

**Comment by behlendorf** [comment]
@zielony360 yes it applies to any IO issued by ZFS to the underlying devices.
