### ISSUE TITLE
ZFS volumes fail to import pools across reboots with the zfs 0.7.4

### ISSUE THREAD

**Issue by tukanos** [zfsonlinux/zfs#6980]
I tried honestly to search the bug tracker [https://github.com/zfsonlinux/zfs/issues ](url) if somebody suffers the same issue.  It seems not.  There were some similar issues with dkms/reboots, but these do not seem the same to me.

### System information

Distribution Name       |  CentOS
Distribution Version    | centos-release-7-4.1708.el7.centos.x86_64
Linux Kernel                 | Linux 4.4.102-1.el7.elrepo.x86_64
Architecture                 | x86_64
ZFS Version                  | 0.7.4-1
SPL Version                  | 0.7.4-1

### Describe the problem you're observing
The hard part of this issue is that sometimes it works and sometimes it does not work.   When I reboot/boot the server sometimes falls into a busybox with the virtpool always present (see my configuration below) and the others sometimes yes and sometimes not.  (it even works sometimes on reboot and sometimes it falls into busybox) and you have to manually force import the pools and manually export them in order for the the server to boot.

I have the following setup (all zpools are healthy):
devpool (a mirror pool with two hdds),  tempfilepool (one hdd), virtpool (ssd with swap on it).  The two pools tempfilepol and virtpool are in the cache file /etc/zfs/zpool.cache.  The root is placed on devpool.  There is a separate /boot partition is on SD card with ext2.

Note: zfs 0.7.3 worked fine.

### Describe how to reproduce the problem
Reboot or start a server/system.

### Include any warning/errors/backtraces from the system logs

If the `devpool` which is the `/` is incorrectly exported than the computer falls into a busybox with message:
```
can not import `devpool` pool was was previously in use from another system.
Last accessed by <unknown> (hostid=0) at at Mon Dec 18 11:31:14 2017
```
I have to manually force import and export the `devpool` in order to boot. 

If the `devpool` is importable the serve rmounts but sometimes it fails to `import/mount` the tempfilepool
the `zfs-import-scan.service` service fails:

```
● zfs-import-scan.service - Import ZFS pools by device scanning
   Loaded: loaded (/usr/lib/systemd/system/zfs-import-scan.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2017-12-18 12:36:22 CET; 4min 52s ago
 Main PID: 433 (code=exited, status=1/FAILURE)

Dec 18 12:36:16 cvalik.localdomain systemd[1]: Starting Import ZFS pools by device scanning...
Dec 18 12:36:22 cvalik.localdomain zpool[433]: cannot import 'tempfilepool': pool was previously in use from another system.
Dec 18 12:36:22 cvalik.localdomain zpool[433]: Last accessed by <unknown> (hostid=0) at Mon Dec 18 11:31:14 2017
Dec 18 12:36:22 cvalik.localdomain zpool[433]: The pool can be imported, use 'zpool import -f' to import the pool.
Dec 18 12:36:22 cvalik.localdomain systemd[1]: zfs-import-scan.service: main process exited, code=exited, status=1/FAILURE
Dec 18 12:36:22 cvalik.localdomain systemd[1]: Failed to start Import ZFS pools by device scanning.
Dec 18 12:36:22 cvalik.localdomain systemd[1]: Unit zfs-import-scan.service entered failed state.
Dec 18 12:36:22 cvalik.localdomain systemd[1]: zfs-import-scan.service failed.
```
If the computer is correctly started everything seems fine (all services started):
` systemctl status "zfs*" "zpool*" `

```
 ● zfs-zed.service - ZFS Event Daemon (zed)
  2    Loaded: loaded (/usr/lib/systemd/system/zfs-zed.service; enabled; vendor     preset: enabled)
  3    Active: active (running) since Mon 2017-12-18 11:58:26 CET; 29min ago
  4      Docs: man:zed(8)
  5  Main PID: 5248 (zed)
  6    CGroup: /system.slice/zfs-zed.service
  7            └─5248 /sbin/zed -F
  8
  9 Dec 18 11:58:28 cvalik.localdomain zed[5248]: ZFS Event Daemon 0.7.4-1 (PID     5248)
 10 Dec 18 11:58:28 cvalik.localdomain zed[5248]: Processing events since eid=0
 11 Dec 18 11:58:26 cvalik.localdomain systemd[1]: Started ZFS Event Daemon (zed    ).
 12 Dec 18 11:58:26 cvalik.localdomain systemd[1]: Starting ZFS Event Daemon (ze    d)...
 13
 14 ● zfs-import-cache.service - Import ZFS pools by cache file
 15    Loaded: loaded (/usr/lib/systemd/system/zfs-import-cache.service; enabled    ; vendor preset: enabled)
 16    Active: active (exited) since Mon 2017-12-18 11:57:54 CET; 30min ago
 17   Process: 3298 ExecStart=/sbin/zpool import -c /etc/zfs/zpool.cache -aN (co    de=exited, status=0/SUCCESS)
 18   Process: 3296 ExecStartPre=/sbin/modprobe zfs (code=exited, status=0/SUCCE    SS)
 19  Main PID: 3298 (code=exited, status=0/SUCCESS)
 20    CGroup: /system.slice/zfs-import-cache.service
 21
 22 Dec 18 11:58:25 cvalik.localdomain zpool[3298]: no pools available to import
 23
 24 ● zfs-mount.service - Mount ZFS filesystems
 25    Loaded: loaded (/usr/lib/systemd/system/zfs-mount.service; enabled; vendo    r preset: enabled)
 26    Active: active (exited) since Mon 2017-12-18 11:57:56 CET; 30min ago
 27   Process: 3317 ExecStart=/sbin/zfs mount -a (code=exited, status=0/SUCCESS)
 28  Main PID: 3317 (code=exited, status=0/SUCCESS)
 29    CGroup: /system.slice/zfs-mount.service
 30
 31 ● zfs-share.service - ZFS file system shares
 32    Loaded: loaded (/usr/lib/systemd/system/zfs-share.service; enabled; vendo    r preset: enabled)
 33    Active: active (exited) since Mon 2017-12-18 11:58:54 CET; 29min ago
 34   Process: 8279 ExecStart=/sbin/zfs share -a (code=exited, status=0/SUCCESS)
 35   Process: 8274 ExecStartPre=/bin/rm -f /etc/dfs/sharetab (code=exited, stat    us=0/SUCCESS)
 36  Main PID: 8279 (code=exited, status=0/SUCCESS)
 37    CGroup: /system.slice/zfs-share.service
 38
 39 Dec 18 11:58:54 cvalik.localdomain systemd[1]: Starting ZFS file system shar    es...
 40 Dec 18 11:58:54 cvalik.localdomain systemd[1]: Started ZFS file system share    s.
```

**Comment by rincebrain** [comment]
zfs-import-scan.service runs /sbin/zpool import -aN -o cachefile=none, so the cachefile contents probably shouldn't matter.

If you just wanted to work around this forcibly for now, you could add -f to the line and regenerate the initramfs.

I'd still be curious to know why it thinks hostid doesn't match. What do "hostid" and "zdb -CC [poolname] | grep hostid | head" output?

**Comment by tonyhutter** [comment]
@tukanos I only glanced at this issue, but I wonder if you're hitting #6971.  Can you try installing 0.7.5 and tell us if that fixes it?

**Comment by tukanos** [comment]
@rincebrain : I have tried multitude of things to achieve a stable state.  
One of the things I tried was to play around with /etc/hostid.  I tried to randomize it: `dd if=/dev/urandom of=/etc/hostid bs=4 count=1`.  Next I tried to get rid of /etc/hostid completely, which I forgot to return back before posting.  

For the sake of completeness (when the file is back):
```
[root@cvalik hostid]# hexdump /etc/hostid
0000000 0100 007f
0000004
```
```
[root@cvalik hostid]# zdb -CC devpool | grep hostid | head
        hostid: 8323328
        hostid: 8323328
```

@tonyhutter : I'm now installing ` zfs CentOS 0.7.4-2` update.  If that will not help I'll try to compile the 0.7.5 from source.

**Comment by tukanos** [comment]
@rincebrain checked this morning (around 10 a.m. CET) and it was `0.7.4-2` with no `0.7.5-1`.   When I checked now at 12:43 CET it had `0.7.5-1`, oh well I will update again and then return.  

From my tests it appears that `0.7.4-2` had this fixed too.  Maybe it was just a wrong tag.

**Comment by tukanos** [comment]
@rincebrain - with `0.7.5-1` seems issue seems to be resolved.

@tonyhutter - it appears that I was indeed hitting #6971.

Thank you both for help me out.  I'm closing this issue.
