### ISSUE TITLE
zpool property 'freeing' partially stuck

### ISSUE THREAD

**Issue by samis** [zfsonlinux/zfs#6984]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Gentoo
Distribution Version    | Profile 17.0
Linux Kernel                 | 4.14.5-gentoo
Architecture                 | X86_64
ZFS Version                  | 0.7.0-211_g4e9b1569
SPL Version                  | 0.7.0-21_ged19bcc

### Describe the problem you're observing
I recently decided to clean up and delete two unused sparse zvols. After this, the freeing property increased as expected and did initially decrease. However, it's almost 24 hours (and two reboots) later and the property is still reporting the exact same value. 

As a test, I filled a zvol with 1G of /dev/urandom and then destroyed it. The property increased from it's original value of 14353956864 to 14605664256 but shortly afterwards the data was freed and the value was back to 14353956864. This is similar to #5808 but both the scenario and the behaviour appear to be different, as neither zvol was ever used for NFS purposes.
### Describe how to reproduce the problem
I have not yet reproduced this beyond the above test. I can't be certain that the freeing value was correct before, but the timing seems right for this issue.
### Include any warning/errors/backtraces from the system logs
So far there have been no warnings, errors or backtraces created as a result of this problem.

**Comment by samis** [comment]
To see if I could obtain additional information, I ran 'zdb -bb'. While the pool was imported, is it worth nothing that the leaked space matches the freeing property exactly? https://gist.github.com/anonymous/e93feb0a375cc88baff64b41fe2fc792#file-zdb-out-L10884

**Comment by kpande** [comment]
what version was this pool created with?

**Comment by samis** [comment]
It was creating on the 0.6.x branch, but I'm away from the machine and pool so exact details will have to wait for the weekend.

**Comment by samis** [comment]
Using the installation logs, the ZoL version at pool creation time was 0.6.5.8.
