### ISSUE TITLE
Optimize the write bandwidth for zpool

### ISSUE THREAD

**Issue by redzhang1990** [zfsonlinux/zfs#6991]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |    Redhat
Distribution Version    |     7.4
Linux Kernel                 |    4.11.0
Architecture                 |    ARM
ZFS Version                  |    0.7.1
SPL Version                  |    0.7.1

### Describe the problem you're observing
I am testing the write bandwidth of zpool which created as raidz2 (10+2) .
When we set the zfs_vdev_async_write_max_active from 10 to 32, the write bandwidth of 1*zpool , 2*zpool and 3*zpool can be improved about 1GB/s, but the 4*zpool write bandwidth can't be improved.

I set the  zfs_vdev_async_write_max_active to 48,60, but it didn't work in the 4*zpool test. How to explain this ?

**Comment by redzhang1990** [comment]
I have found that the key point is raidz2. When create the zpool without raidz2, the write bandwidth of 1 to 4 zpools is linear growth. When using the raidz2, the 4 zpools write bandwidth be limited under 4.5GB/s. Please if some one can know how to slove this issue, thx very much !

**Comment by kpande** [comment]
this is not a bug, which this issue tracker is for. use the zfs-discuss mailing list for support requests.
