### ISSUE TITLE
centos 7 failover w/ ucarp

### ISSUE THREAD

**Issue by dmaziuk** [zfsonlinux/zfs#6993]
This is a follow-up to #6855 -- I'm still having problems getting export/import to work. I seem to have gotten the "down" script to work but right now I have the "up'' script that does
```
/sbin/ip address add "$2"/32 dev "$1"
systemctl restart nfs-server          # b/c we kill it in the down-script to let go of zfs shares

if zpool import -f -o cachefile=none "tank" ; then
#    systemctl start zfs-mount
    systemctl start zfs-share
    ${LOGGER} ${NOTE} "vip $2 is up"
else
    ${LOGGER} ${CRIT} "zpool import tank failed!"
    echo "zpool import tank failed!" | mail -s "nmrfam_data is down!" root@nmrfam.wisc.edu
fi
```
and after this runs I have:
```
# zpool status
  pool: tank
 state: ONLINE
...

# exportfs
/tank/downloads 	144.92.4.0/24
/nmrfam_data  	144.92.4.0/24

# df
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/sdy2      181076660 2636988 169218400   2% /
devtmpfs        16341536       0  16341536   0% /dev
tmpfs           16381460      12  16381448   1% /dev/shm
tmpfs           16381460    8876  16372584   1% /run
tmpfs           16381460       0  16381460   0% /sys/fs/cgroup
tmpfs            3276292       0   3276292   0% /run/user/0
```
and the error e-mail. 

I.e. zfs mount fails. If I uncomment explicit `systemctl start zfs-mount` in the script, it fails with "already mounted". With that commented out it fails, some of the time, with:
```
+ LOGGER='/usr/bin/logger -t ucarp'
+ CRIT='-p daemon.crit'
+ NOTE='-p daemon.notice'
+ '[' 'enp2s0 144.92.4.213' == '' ']'
+ /sbin/ip address add 144.92.4.213/32 dev enp2s0
+ systemctl restart nfs-server
+ zpool import -f -o cachefile=none tank
cannot mount '/tank': directory is not empty
+ /usr/bin/logger -t ucarp -p daemon.crit 'zpool import tank failed!'
+ echo 'zpool import tank failed!'
+ mail -s 'nmrfam_data is down!' root@nmrfam.wisc.edu
```
but not all the time.

That's from command line, when I enable it under `ucarp` it fails most of the time.

Any ideas how to make this work?

**Comment by kpande** [comment]
please use [the zfs-discuss mailing list](http://list.zfsonlinux.org) for support requests. this is an issue tracker for bug reports, and not a support forum.

**Comment by dmaziuk** [comment]
To me this behaviour looks buggy: `zpool import` mounts filesystems (why? what happened to doing one thing only?), `zfs mount` fails with "already mounted" or "mountpoint busy" (why? there's nothing mounted), the whole thing is very wobbly.

As I said before it's hard to say how much of instability lays with `zfs` and how much: with the rest of it, but the bottom line is ZoL right now is buggy and unstable in fail-over NFS server setup on centos 7. It's an issue.

**Comment by dmaziuk** [comment]
PS which part of 
```
+ zpool import -f -o cachefile=none tank
cannot mount '/tank': directory is not empty
```
looks like "not an issue" to you?

**Comment by kpande** [comment]
that may be so, but this is not the place to diagnose the issues. try the mailing list, or IRC (#zfsonlinux on freenode)
