### ISSUE TITLE
Datasets Not Mounted Correctly After Updating to 0.7.4-1

### ISSUE THREAD

**Issue by SenileAnimal** [zfsonlinux/zfs#7000]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Antergos (Arch Linux)
Distribution Version    |  Unknown
Linux Kernel                 |  4.14.8-1 (Latest)
Architecture                 |  x64 (64 bit)
ZFS Version                  |  0.7.4-1 (Latest)
SPL Version                  |  0.7.4-1 (Latest)

### Describe the problem you're observing
After updating the system (including zfs-dkms, zfs-utils, spl, spl-utils, updated via Pamac), I received a pop-up message: 
"directory permissions differ on /root/
filesystem: 755 package 750
directory permissions differ on /etc/sudoers.d/
filesystem:: 750 package: 755"

On reboot my zpools contain all datasets, except 1, but all datasets are listed as empty folders with no contents. The 1 missing dataset had redundant naming, in this case the zpool was Emulation and the dataset was also named Emulation. I tried renaming the dataset with redundant naming, and after several reboots, it finally shows up, though the dataset is like the others and only listed as an empty folder. 

Mounting the zpools fixes the problem, but it throws an error for each zpool:
sudo zpool import Media
cannot mount '/Media': directory is not empty 

I can confirm that mount points are listed for all datasets (by running "zfs-list"), but they're not actually mounted (by running "zfs get all zpoolname/datasetname") until I import them or run zfs mount -a, which must be done on each reboot of the system in order to view the contents of the datasets.

Perhaps the zfs-mount service is not behaving correctly? 

This issue seems similar to https://github.com/zfsonlinux/pkg-zfs/issues/43

I hope this is the right place to report this issue, and that it's not a foolish error on my behalf. This is I think the first time I've updated zfs-dkms. Thank you for any assistance you can provide.

### Describe how to reproduce the problem
Did not try to reproduce, sorry.

I've checked journalctl and dmesg and see no ZFS errors. I have deleted the ZFS cache, enabled all zfs related services and ensured they are running/completed successfully, and even reinstalled zfs yet the issue persists. Basically, I see no errors anywhere, yet the datasets are not mounted on reboot. Note that everything worked well until I updated to the latest zfs version.

**Comment by SenileAnimal** [comment]
My apologies, it just occurred to me to navigate to the datasets and check the contents in command line. The contents do appear in command line/terminal. I'm not sure what's going on here.

**Comment by AndCycle** [comment]
do Antergos use systemd? 

if it's so, please read
https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.7.4

**Comment by kpande** [comment]
please read the release notes!
