### ISSUE TITLE
ZED does not emit dataset destroy when destroying cooresponding pool

### ISSUE THREAD

**Issue by jgrund** [zfsonlinux/zfs#7009]
when issuing a `zpool destroy tank`, I don't see a ZED event for the destruction of any datasets in that pool, even though they appear to have been destroyed.

If they are destroyed, it seems like ZED should emit the same event it does on a `zfs destroy tank/ds`

**Comment by DeHackEd** [comment]
You don't want to do `zfs destroy` when destroying a pool. If you did:
1) Destroying the pool would take a long longer
2) Recovering a destroyed pool would not be possible, or at least not worth trying.

**Comment by jgrund** [comment]
@DeHackEd What is the state of any corresponding datasets when a `zpool destroy` is executed on a pool that contains datasets?

**Comment by DeHackEd** [comment]
A `zpool destroy` is functionally equivalent to a `zpool export` with the drive labels marked as "destroyed" rather than "exported".

This is leaving the realm of a bug tracker.

**Comment by loli10K** [comment]
@jgrund there doesn't seem to be a bug here, should we close this?
