### ISSUE TITLE
find and atime on RHEL 7.

### ISSUE THREAD

**Issue by rwyse** [zfsonlinux/zfs#7010]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | RHEL
Distribution Version    | 7.4
Linux Kernel                 | 3.10.0-693.2.2.el7.x86_64
Architecture                 | x86_64
ZFS Version                  | 0.7.2-1
SPL Version                  | 0.7.2-1

### Describe the problem you're observing
Find is reporting some strange and false results.

### Describe how to reproduce the problem
On a system I cd into an archive directory and I will get something like the following to occur.
```
find ./ -type f -print -atime +365
./resp_time_mean.wsp
./resp_time_95_pct.wsp
./resp_time_99_pct.wsp
./resp_time_max.wsp
./count_per_sec.wsp

stat resp_time_mean.wsp
  File: ‘resp_time_mean.wsp’
  Size: 1434292   	Blocks: 7          IO Block: 131072 regular file
Device: 26h/38d	Inode: 7015277     Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2017-10-31 15:54:19.319639606 -0500
Modify: 2017-10-31 15:54:19.321639542 -0500
Change: 2017-11-07 22:24:15.438101891 -0600
 Birth: -
```
I have 3 servers running various versions of ZFS 0.7.x that are doing the same thing.  On all 3 systems atime is set to on in the ZFS settings.  This isn't an error and it reports no issues that I can find, but find is clearly reporting an incorrect result from the filesystem.  My question is what is it that is happening that would throw off find like that on ZFS?  Am I missing something in the process here?  The goal is to sort archive directories and find then delete files that are over a certain age.

Any help or guidance on this would be appreciated as I am stumped and I know enough about managing ZFS to be dangerous, but not the fine details of what happens at the file level.  Is it something off in the inode or is this intended and I should be using something else to achieve my goals?

Apologies as I don't have logs that can show the system behavior in this manner.  Thanks in advance for any information on this one.

**Comment by loli10K** [comment]
Output of `strace -v find ./ -type f -print -atime +365` would be greatly appreciated: if it's too verbose consider using https://gist.github.com/.

**Comment by rwyse** [comment]
Well that isn't as verbose I expected it to be.  Sorry for the delay in getting back to you as that was the end of my day.  Find the requested output below, although I am even more curious now seeing as the st_atime= is within the specified time range:

strace -v find ./ -type f -print -atime +365
execve("/bin/find", ["find", "./", "-type", "f", "-print", "-atime", "+365"], ["XDG_SESSION_ID=348393", "HOSTNAME=ip-10-1-10-125.localdom"..., "SHELL=/bin/bash", "TERM=xterm-256color", "HISTSIZE=1000", "QTDIR=/usr/lib64/qt-3.3", "OLDPWD=/root", "QTINC=/usr/lib64/qt-3.3/include", "QT_GRAPHICSSYSTEM_CHECKED=1", "USER=root", "LS_COLORS=rs=0:di=38;5;27:ln=38;"..., "MAIL=/var/spool/mail/root", "PATH=/usr/lib64/qt-3.3/bin:/usr/"..., "PWD=/mnt/graphite_archive/archiv"..., "LANG=en_US.UTF-8", "QT_GRAPHICSSYSTEM=native", "HISTCONTROL=ignoredups", "SHLVL=1", "HOME=/root", "LOGNAME=root", "QTLIB=/usr/lib64/qt-3.3/lib", "LESSOPEN=||/usr/bin/lesspipe.sh "..., "_=/bin/strace"]) = 0
brk(0)                                  = 0x1b2d000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1de7935000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_dev=makedev(202, 2), st_ino=63888, st_mode=S_IFREG|0644, st_nlink=1, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=72, st_size=33011, st_atime=2018/01/03-21:15:57, st_mtime=2017/10/31-22:15:50, st_ctime=2017/10/31-22:15:50}) = 0
mmap(NULL, 33011, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f1de792c000
close(3)                                = 0
open("/lib64/libselinux.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\300j\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_dev=makedev(202, 2), st_ino=19350301, st_mode=S_IFREG|0755, st_nlink=1, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=312, st_size=155736, st_atime=2018/01/03-15:53:30, st_mtime=2016/08/26-02:39:14, st_ctime=2016/12/29-15:47:20}) = 0
mmap(NULL, 2255216, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f1de74f0000
mprotect(0x7f1de7514000, 2093056, PROT_NONE) = 0
mmap(0x7f1de7713000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x23000) = 0x7f1de7713000
mmap(0x7f1de7715000, 6512, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f1de7715000
close(3)                                = 0
open("/lib64/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0`T\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_dev=makedev(202, 2), st_ino=16821226, st_mode=S_IFREG|0755, st_nlink=1, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=2232, st_size=1141928, st_atime=2018/01/03-15:48:01, st_mtime=2016/10/27-23:26:01, st_ctime=2016/12/29-15:47:19}) = 0
mmap(NULL, 3150152, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f1de71ee000
mprotect(0x7f1de72ee000, 2097152, PROT_NONE) = 0
mmap(0x7f1de74ee000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x100000) = 0x7f1de74ee000
close(3)                                = 0
open("/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0@\34\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_dev=makedev(202, 2), st_ino=16821217, st_mode=S_IFREG|0755, st_nlink=1, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=4144, st_size=2118128, st_atime=2018/01/03-15:50:27, st_mtime=2016/10/27-23:26:02, st_ctime=2016/12/29-15:47:19}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1de792b000
mmap(NULL, 3932672, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f1de6e2d000
mprotect(0x7f1de6fe3000, 2097152, PROT_NONE) = 0
mmap(0x7f1de71e3000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1b6000) = 0x7f1de71e3000
mmap(0x7f1de71e9000, 16896, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f1de71e9000
close(3)                                = 0
open("/lib64/libpcre.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\360\25\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_dev=makedev(202, 2), st_ino=16821234, st_mode=S_IFREG|0755, st_nlink=1, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=784, st_size=398264, st_atime=2018/01/03-17:12:30, st_mtime=2016/05/03-05:53:28, st_ctime=2016/09/14-16:04:03}) = 0
mmap(NULL, 2490888, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f1de6bcc000
mprotect(0x7f1de6c2c000, 2093056, PROT_NONE) = 0
mmap(0x7f1de6e2b000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x5f000) = 0x7f1de6e2b000
close(3)                                = 0
open("/lib64/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0`\16\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_dev=makedev(202, 2), st_ino=16821224, st_mode=S_IFREG|0755, st_nlink=1, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=40, st_size=19776, st_atime=2018/01/03-15:50:27, st_mtime=2016/10/27-23:26:01, st_ctime=2016/12/29-15:47:19}) = 0
mmap(NULL, 2109744, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f1de69c8000
mprotect(0x7f1de69ca000, 2097152, PROT_NONE) = 0
mmap(0x7f1de6bca000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f1de6bca000
close(3)                                = 0
open("/lib64/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\240l\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_dev=makedev(202, 2), st_ino=16896462, st_mode=S_IFREG|0755, st_nlink=1, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=288, st_size=143944, st_atime=2018/01/03-15:50:27, st_mtime=2016/10/27-23:26:02, st_ctime=2016/12/29-15:47:19}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1de792a000
mmap(NULL, 2208864, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f1de67ac000
mprotect(0x7f1de67c3000, 2093056, PROT_NONE) = 0
mmap(0x7f1de69c2000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x16000) = 0x7f1de69c2000
mmap(0x7f1de69c4000, 13408, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f1de69c4000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1de7929000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1de7927000
arch_prctl(ARCH_SET_FS, 0x7f1de7927800) = 0
mprotect(0x7f1de71e3000, 16384, PROT_READ) = 0
mprotect(0x7f1de69c2000, 4096, PROT_READ) = 0
mprotect(0x7f1de6bca000, 4096, PROT_READ) = 0
mprotect(0x7f1de6e2b000, 4096, PROT_READ) = 0
mprotect(0x7f1de74ee000, 4096, PROT_READ) = 0
mprotect(0x7f1de7713000, 4096, PROT_READ) = 0
mprotect(0x62d000, 4096, PROT_READ)     = 0
mprotect(0x7f1de7936000, 4096, PROT_READ) = 0
munmap(0x7f1de792c000, 33011)           = 0
set_tid_address(0x7f1de7927ad0)         = 107315
set_robust_list(0x7f1de7927ae0, 24)     = 0
rt_sigaction(SIGRTMIN, {0x7f1de67b2780, [], SA_RESTORER|SA_SIGINFO, 0x7f1de67bb370}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {0x7f1de67b2810, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7f1de67bb370}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
statfs("/sys/fs/selinux", 0x7ffe81be0320) = -1 ENOENT (No such file or directory)
statfs("/selinux", 0x7ffe81be0320)      = -1 ENOENT (No such file or directory)
brk(0)                                  = 0x1b2d000
brk(0x1b4e000)                          = 0x1b4e000
open("/proc/filesystems", O_RDONLY)     = 3
fstat(3, {st_dev=makedev(0, 3), st_ino=4026533180, st_mode=S_IFREG|0444, st_nlink=1, st_uid=0, st_gid=0, st_blksize=1024, st_blocks=0, st_size=0, st_atime=2018/01/04-09:25:14, st_mtime=2018/01/04-09:25:14, st_ctime=2018/01/04-09:25:14}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1de7934000
read(3, "nodev\tsysfs\nnodev\trootfs\nnodev\tr"..., 1024) = 313
stat("/etc/sysconfig/64bit_strstr_via_64bit_strstr_sse2_unaligned", 0x7ffe81be0200) = -1 ENOENT (No such file or directory)
read(3, "", 1024)                       = 0
close(3)                                = 0
munmap(0x7f1de7934000, 4096)            = 0
access("/etc/selinux/config", F_OK)     = 0
open(".", O_RDONLY)                     = 3
fcntl(3, F_GETFD)                       = 0
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
uname({sysname="Linux", nodename="ip-10-1-10-125.localdomain", release="3.10.0-693.2.2.el7.x86_64", version="#1 SMP Sat Sep 9 03:55:24 EDT 2017", machine="x86_64", domainname="(none)"}) = 0
ioctl(0, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {c_iflags=0x2d00, c_oflags=0x5, c_cflags=0xbf, c_lflags=0xca3b, c_line=0, c_cc="\x03\x1c\x7f\x15\x04\x00\x01\x00\x11\x13\x1a\xff\x12\x0f\x17\x16\xff\x00\x00"}) = 0
gettimeofday({1515079514, 524722}, NULL) = 0
open("/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 4
fstat(4, {st_dev=makedev(202, 2), st_ino=31137, st_mode=S_IFREG|0644, st_nlink=1, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=207112, st_size=106070960, st_atime=2018/01/03-15:50:27, st_mtime=2016/12/29-15:47:19, st_ctime=2016/12/29-15:47:19}) = 0
mmap(NULL, 106070960, PROT_READ, MAP_PRIVATE, 4, 0) = 0x7f1de0283000
close(4)                                = 0
open("/usr/share/locale/locale.alias", O_RDONLY|O_CLOEXEC) = 4
fstat(4, {st_dev=makedev(202, 2), st_ino=31129, st_mode=S_IFREG|0644, st_nlink=1, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=8, st_size=2502, st_atime=2018/01/03-15:53:57, st_mtime=2016/10/27-23:04:07, st_ctime=2016/12/29-15:47:17}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1de7934000
read(4, "# Locale name alias data base.\n#"..., 4096) = 2502
read(4, "", 4096)                       = 0
close(4)                                = 0
munmap(0x7f1de7934000, 4096)            = 0
open("/usr/share/locale/en_US.UTF-8/LC_MESSAGES/findutils.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US.utf8/LC_MESSAGES/findutils.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US/LC_MESSAGES/findutils.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.UTF-8/LC_MESSAGES/findutils.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.utf8/LC_MESSAGES/findutils.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en/LC_MESSAGES/findutils.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
ioctl(1, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {c_iflags=0x2d00, c_oflags=0x5, c_cflags=0xbf, c_lflags=0xca3b, c_line=0, c_cc="\x03\x1c\x7f\x15\x04\x00\x01\x00\x11\x13\x1a\xff\x12\x0f\x17\x16\xff\x00\x00"}) = 0
newfstatat(AT_FDCWD, "./", {st_dev=makedev(0, 38), st_ino=7015272, st_mode=S_IFDIR|0755, st_nlink=2, st_uid=0, st_gid=0, st_blksize=512, st_blocks=3, st_size=7, st_atime=2018/01/04-09:20:34, st_mtime=2017/11/07-22:24:15, st_ctime=2017/11/07-22:24:15}, AT_SYMLINK_NOFOLLOW) = 0
openat(AT_FDCWD, "./", O_RDONLY|O_NOCTTY|O_NONBLOCK|O_DIRECTORY|O_NOFOLLOW) = 4
fcntl(4, F_GETFD)                       = 0
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
fstat(4, {st_dev=makedev(0, 38), st_ino=7015272, st_mode=S_IFDIR|0755, st_nlink=2, st_uid=0, st_gid=0, st_blksize=512, st_blocks=3, st_size=7, st_atime=2018/01/04-09:20:34, st_mtime=2017/11/07-22:24:15, st_ctime=2017/11/07-22:24:15}) = 0
fcntl(4, F_GETFL)                       = 0x38800 (flags O_RDONLY|O_NONBLOCK|O_LARGEFILE|O_DIRECTORY|O_NOFOLLOW)
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
newfstatat(AT_FDCWD, "./", {st_dev=makedev(0, 38), st_ino=7015272, st_mode=S_IFDIR|0755, st_nlink=2, st_uid=0, st_gid=0, st_blksize=512, st_blocks=3, st_size=7, st_atime=2018/01/04-09:20:34, st_mtime=2017/11/07-22:24:15, st_ctime=2017/11/07-22:24:15}, AT_SYMLINK_NOFOLLOW) = 0
fcntl(4, F_DUPFD, 3)                    = 5
fcntl(5, F_GETFD)                       = 0
fcntl(5, F_SETFD, FD_CLOEXEC)           = 0
getdents(4, {{d_ino=7015272, d_off=1, d_reclen=24, d_name=".", d_type=DT_DIR} {d_ino=6372341, d_off=2, d_reclen=24, d_name="..", d_type=DT_DIR} {d_ino=7015277, d_off=317694856, d_reclen=40, d_name="resp_time_mean.wsp", d_type=DT_REG} {d_ino=7015274, d_off=320988467, d_reclen=40, d_name="resp_time_95_pct.wsp", d_type=DT_REG} {d_ino=7015275, d_off=326768092, d_reclen=40, d_name="resp_time_99_pct.wsp", d_type=DT_REG} {d_ino=7015276, d_off=408243947, d_reclen=40, d_name="resp_time_max.wsp", d_type=DT_REG} {d_ino=7015273, d_off=531602389, d_reclen=40, d_name="count_per_sec.wsp", d_type=DT_REG}}, 32768) = 248
getdents(4, {}, 32768)                  = 0
close(4)                                = 0
fcntl(5, F_DUPFD_CLOEXEC, 0)            = 4
fstat(1, {st_dev=makedev(0, 11), st_ino=3, st_mode=S_IFCHR|0620, st_nlink=1, st_uid=1034, st_gid=5, st_blksize=1024, st_blocks=0, st_rdev=makedev(136, 0), st_atime=2018/01/04-09:25:12, st_mtime=2018/01/04-09:25:12, st_ctime=2018/01/04-09:02:41}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1de7934000
write(1, "./resp_time_mean.wsp\n", 21./resp_time_mean.wsp
)  = 21
newfstatat(5, "resp_time_mean.wsp", {st_dev=makedev(0, 38), st_ino=7015277, st_mode=S_IFREG|0644, st_nlink=1, st_uid=0, st_gid=0, st_blksize=131072, st_blocks=7, st_size=1434292, st_atime=2017/10/31-15:54:19, st_mtime=2017/10/31-15:54:19, st_ctime=2017/11/07-22:24:15}, AT_SYMLINK_NOFOLLOW) = 0
write(1, "./resp_time_95_pct.wsp\n", 23./resp_time_95_pct.wsp
) = 23
newfstatat(5, "resp_time_95_pct.wsp", {st_dev=makedev(0, 38), st_ino=7015274, st_mode=S_IFREG|0644, st_nlink=1, st_uid=0, st_gid=0, st_blksize=131072, st_blocks=7, st_size=1434292, st_atime=2017/10/31-15:56:08, st_mtime=2017/10/31-15:56:08, st_ctime=2017/11/07-22:24:15}, AT_SYMLINK_NOFOLLOW) = 0
write(1, "./resp_time_99_pct.wsp\n", 23./resp_time_99_pct.wsp
) = 23
newfstatat(5, "resp_time_99_pct.wsp", {st_dev=makedev(0, 38), st_ino=7015275, st_mode=S_IFREG|0644, st_nlink=1, st_uid=0, st_gid=0, st_blksize=131072, st_blocks=7, st_size=1434292, st_atime=2017/10/31-15:55:01, st_mtime=2017/10/31-15:55:01, st_ctime=2017/11/07-22:24:15}, AT_SYMLINK_NOFOLLOW) = 0
write(1, "./resp_time_max.wsp\n", 20./resp_time_max.wsp
)   = 20
newfstatat(5, "resp_time_max.wsp", {st_dev=makedev(0, 38), st_ino=7015276, st_mode=S_IFREG|0644, st_nlink=1, st_uid=0, st_gid=0, st_blksize=131072, st_blocks=7, st_size=1434292, st_atime=2017/10/31-15:55:49, st_mtime=2017/10/31-15:55:49, st_ctime=2017/11/07-22:24:15}, AT_SYMLINK_NOFOLLOW) = 0
write(1, "./count_per_sec.wsp\n", 20./count_per_sec.wsp
)   = 20
newfstatat(5, "count_per_sec.wsp", {st_dev=makedev(0, 38), st_ino=7015273, st_mode=S_IFREG|0644, st_nlink=1, st_uid=0, st_gid=0, st_blksize=131072, st_blocks=7, st_size=1434292, st_atime=2017/10/31-15:54:03, st_mtime=2017/10/31-15:54:03, st_ctime=2017/11/07-22:24:15}, AT_SYMLINK_NOFOLLOW) = 0
close(5)                                = 0
close(4)                                = 0
fchdir(3)                               = 0
close(3)                                = 0
close(1)                                = 0
munmap(0x7f1de7934000, 4096)            = 0
close(2)                                = 0
exit_group(0)                           = ?
+++ exited with 0 +++

Thanks again for the assistance and guidance on this one.

-Ryan

**Comment by loli10K** [comment]
@rwyse I took the liberty of editing your comments adding code tags (```) for easier readability.

> although I am even more curious now seeing as the st_atime= is within the specified time range

Both `find` and `stat` seem to read the same atime for "resp_time_mean.wsp", so maybe ZFS is not at fault here. Actually, if you look closely at the order used by `find` to print the ouput result (`write(stdout, <filename>)`) and read the atime to compare against the "-atime" param (`newfstatat(fd, <filename>)`) the real issue may become more clear.

**Comment by rwyse** [comment]
So that has to be one of the nicest ways in which to say you're a jerk for not formatting that nasty strace output....thanks lol and sorry for that oversight.  

I apologize though, I have been staring at this one too long and I am pretty sure that I am missing something pretty stupid/obvious at this point.  All that I can really see in the ordering is that you have a new line before the ) = 21 in the write results while the newfstatat results is on a single line yet it is reporting at = 0.   

I didn't think ZFS was going to be the culprit as I would think I would have stumbled across something about it in my digging over the past couple of days, but I figured someone here would maybe be better equipped in assisting me find the culprit considering the knowledge pool available.  That being said, what is it that I am missing here?

Thanks :)

**Comment by loli10K** [comment]
`find` is writing the result output (filename) **before** even reading the atime from the file; does running `find ./ -type f -atime +365 -print` ("-print" **after** the "-atime") produce the expected output?

**Comment by rwyse** [comment]
Really, operand order?  Wow alright that one is an obvious.  Thanks for the assistance on this and I will close the issue.  I do appreciate the help.

-Ryan
