### ISSUE TITLE
Dracut: Export Priority Fix

### ISSUE THREAD

**Issue by dcrdev** [zfsonlinux/zfs#7012]
When utilising the zfs dracut module with a dm-crypt setup, the crypt dracut module fails to close the encrypted container on shutdown. 

This is due to:
- The crypt module checks for mounted filesystems, at this point there are none.
- If none are found, several attempts are made to close the container.
- Ofcourse just because there are no mounted filesystems, does not mean that the zpool isn't still active and tying up of those disk.
- The encryption container is never closed, a retry limit is imposed and cryptsetup ultimately fails.
- This *can under certain circumstances cause sync issues, there's some kind of weird race going.

This can be fixed here:
https://github.com/zfsonlinux/zfs/blob/master/contrib/dracut/90zfs/module-setup.sh.in#L68

You'll note that priority of 20 - well the script within crypt that is responsible for closing containers has a higher priority of 30:
https://github.com/dracutdevs/dracut/blob/master/modules.d/90crypt/module-setup.sh#L66

The ideal solution here would be if crypt could check for the presence of an active zpool, but that's never going to happen. So a not very elegant solution by any means, but increasing the priority does appear to fix this problem.

Whether that causes any issues with other modules, I couldn't say I'm no dracut expert (I hate it) - but I certainly haven't noticed any adverse affects in my brief testing.

**Comment by behlendorf** [comment]
@dcrdev did you close this issue because you found another solution for this issue?

**Comment by dcrdev** [comment]
@behlendorf

The dracut command line hook priorities are a mess - transpired that the priority this was originally set to was pretty much the best value; albeit incompatible with the encrypt module. Changing the value here resulted in some other modules not always cleaning up.

I closed the pull request because I can't see a way forward without making encrypt zfs aware - which can't be done here.

**Comment by behlendorf** [comment]
@dcrdev makes sense, thanks for the explanation.
