### ISSUE TITLE
Impact of Intel bug (tm) on ZFS

### ISSUE THREAD

**Issue by h1z1** [zfsonlinux/zfs#7015]
Maybe the wrong avenue for this but no doubt like others watching the events of the last few days unfold, I've been asked to comment on the impact to ZFS in our environment.   I'm in a rather odd position as I don't really have the hardware to duplicate an entire production silo, running 4.15.x kernel.   I do however know at least 4.14 will bite us as per #6929.  

Has anyone tested or confirmed what the impact of this will be going forward?  Would rather not duplicate effort if it's already being addressed.

Thanks

**Comment by ryao** [comment]
The impact is the same as it is to any other storage driver in the Linux kernel. Anything that can execute locally is likely able to read information from kernel memory that it should not be able to access. If you are using ZFS to serve iSCSI, SMB and NFS, the server is no more vulnerable than it was previously on the surface. The question would be whether the client machines are trying to do access control on things there for locally executed code. If you have a shared system, then it is open season on the kernel's data structures regardless of what filesystem you are using and ZFS' data structures would be within the scope of things that can be read.

If a super confidential document is in ARC and a less privileged user that shouldn't be able to read it wants it, there is a possibility of reading the kernel data structures to find it and obtain it. The same is true for other filesystems that have data in the page cache. A script that uses this attack to get data out of the page cache is not applicable to ZFS outside memory mapped data, so an attack on ZFS' ARC would need to be done separately.

If you are using ZFS crypto, I suppose that there would also be the risk of a local attacker grabbing the encryption keys used to protect datasets, although I am not the best one to comment on that.

Anyway, I suspect that it would be better to use this to get root privileges. For example, a local user could do a login (or fail to login) to get the password database into memory, read it through this attack, crack it and then login as root.

**Comment by h1z1** [comment]
If anything these "bugs" certainly highlight another elephant in the room and that is cloud security overall.  There is none for basically the same reason.  If you have access to the host, you can read anything from memory, or worse - passively snapshot.   It's less of an issue when you're not crossing authority domains (SAAS for example), but entirely wipes any security from public clouds.   It is what baffles me about the encryption in zfs or really the lack thereof. 

There is however the other side of this which is the impact of the proposed patches and zfs being compatible with current mainline kernel.  Performance for example.

It could certainly be argued (and will from me, for the time being), that the attack vector is minimized in at least storage server deployments since the bugs require local access.

**Comment by philippeg-ligo** [comment]
I just ran  performance comparison on one of our data repository: 
2.45 TB zpool running on a 12 core Xeon hardware on scientific linux 7.4. 
The load is a big hierarchy of docx, ppt, pdf, psd etc...
We're running zfs in kmod. 

I measured a 20 % performance drop at zpool scrub between before and after applying the SL kernel / microcode updates to fix the vulnerability. 
kernel 3.10.0.693.11.1 before 3.10.0.693.11.6 now
microcode_ctl 2.1-22 before 2.1.-22.2 now 
zfs 0.7.5 

cat /proc/cpuinfo | head  -n 26
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz
stepping	: 1
microcode	: 0xb000025
cpu MHz		: 1199.953
cache size	: 15360 KB
physical id	: 0
siblings	: 12
core id		: 0
cpu cores	: 6
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 20
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 invpcid_single intel_pt spec_ctrl ibpb_support tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm arat pln pts
bogomips	: 7199.49
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

**Comment by h1z1** [comment]
> model name	: Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz
> cpu MHz	: 1199.953

3.6GHz running @ 1.1??  Quite a bit of underclocking there.

**Comment by drescherjm** [comment]
> 3.6GHz running @ 1.1?? Quite a bit of underclocking there.

That is normal. The CPU clocks down when under low load.

**Comment by kernelOfTruth** [comment]
added **Performance** label

It's not really related to performance issues **from** ZFS but in connection **with** ZFS,

nevertheless helpful to immediately spot what the topic is about
