### ISSUE TITLE
codecov bot gone nuts

### ISSUE THREAD

**Issue by bunder2015** [zfsonlinux/zfs#7022]
### Describe the problem you're observing
codecov bot has gone nuts, 13 emails in ~20 minutes from the same pull (7018)

**Comment by sylveon** [comment]
I think you can block it to avoid receiving its emails

**Comment by bunder2015** [comment]
Clicking the bot's "user name" takes me here: https://github.com/apps/codecov

Unfortunately I don't see an option to block it like I would if it were a regular user.

**Comment by DeHackEd** [comment]
I've taken this up with github support. Because the bot is a github app and not really a user, blocking the user doesn't do it. At this time it is not blockable at the github level.

**Comment by prometheanfire** [comment]
I auto sort my email, even still I get too many emails

**Comment by gmelikov** [comment]
Agree, it's a little bit noisy, I auto sort them in email client too, now there are 783 letters from September (and I think many of them were deleted by me in the midnight rage).

**Comment by bunder2015** [comment]
Checking my morning email...  From the author's last comment in the PR 7018, I've gotten 31 emails from the bot.

**Comment by sylveon** [comment]
![image](https://user-images.githubusercontent.com/6440374/34727798-f55fa952-f525-11e7-9c57-48636e62a581.png)

**Comment by ptx0** [comment]
@behlendorf can we please shut the bot down? its signal to noise ratio is too damn low.

**Comment by behlendorf** [comment]
Why don't we first try and reduce the noise, I've opened #7025 which should limit it to one comment per PR.  That should be manageable, if that fails we can disable posting to PRs entirely.  Sorry about the spam.

**Comment by bunder2015** [comment]
Thanks! Closing for now.
