### ISSUE TITLE
Consider adding mitigations for speculative execution related concerns

### ISSUE THREAD

**Issue by sempervictus** [zfsonlinux/zfs#7035]
GCC should get retpoline support soon, and Intel seems to be proposing kernel code with barriers to speculative execution - https://patchwork.ozlabs.org/cover/856316/. ZFS is already pretty unhappy from KPTI, but since there's a good deal of user controlled data going into it, this might be worth investigating.

**Comment by behlendorf** [comment]
Thanks for the link to the discussion, we'll want to keep an eye on this.

**Comment by error10** [comment]
Fedora is already shipping retpoline enabled kernels, and it is not possible to load ZFS DKMS modules anymore. Attempting to do so gives the following error:

```
spl: version magic '4.14.15-300.fc27.x86_64 SMP mod_unload ' should be '4.14.15-300.fc27.x86_64 SMP mod_unload retpoline '
modprobe: ERROR: could not insert 'zfs': Exec format error
```

At the moment I'm stuck on 4.14.14-300.fc27.x86_64.

**Comment by sylveon** [comment]
IDK what the ArchZFS project did exactly, but it works for me on the retpoline-compiled linux-zen kernel.

**Comment by Fabian-Gruenbichler** [comment]
On Sat, Jan 27, 2018 at 09:18:59PM -0800, Michael Hampton wrote:
> Fedora is already shipping retpoline enabled kernels, and it is not possible to load ZFS DKMS modules anymore. Attempting to do so gives the following error:
> 
> ```
> spl: version magic '4.14.15-300.fc27.x86_64 SMP mod_unload ' should be '4.14.15-300.fc27.x86_64 SMP mod_unload retpoline '
> modprobe: ERROR: could not insert 'zfs': Exec format error
> ```
> 
> At the moment I'm stuck on 4.14.14-300.fc27.x86_64.
> 

that one will be downgraded to a warning with a future kernel update
(the revert is already queued for the next 4.14 stable update upstream)

**Comment by kpande** [comment]
since it's been a year, we can probably close this @behlendorf ?

**Comment by sempervictus** [comment]
I believe Respectre does find and make changes, but no idea if it would be some TOS violation to post the output. The 4.4 patch was recently gpleaked, thereby leaking the plugin... might be worth a compile pass just to see what it skylines.

**Comment by behlendorf** [comment]
Unless we have a volenteer who want to further investigation I agree we should close this out.  Support for retpoline has been in gcc for a long time now along with the kernel mitigation.  We can always open new issues (or better yet PRs) to address any specific concerns identified by Respectre.
