### ISSUE TITLE
pool from file, file deleted, but pool status is OK

### ISSUE THREAD

**Issue by eztEgyed** [zfsonlinux/zfs#7047]
Type                                | Version/Name
Distribution Name       |  Ubuntu
Distribution Version    |  16.04.3 LTS
Linux Kernel                 | 4.4.0-109-generic
Architecture                 | x86_64
ZFS Version                  | 0.6.5.6-0ubuntu16
SPL Version                  | 0.6.5.6-0ubuntu14

### Describe the problem you're observing

If I make a pool from file, then delete the file (or write in tothe file directly) and after check (with status and scrub) the pool, but pool status is OK.

**Comment by rincebrain** [comment]
@eztEgyed I would guess that, if you ran "zpool reopen", it would go south rapidly, as I would guess what's happening is that the filesystem isn't actually marking the file as "deleted" until all references to the file are closed, including ZFS's use of it, and I would not imagine zpool reopen can manage to reopen the file when it's been rm'd.

Also, this kind of thing seems more like a question for the zfs-discuss mailing list or the ZoL IRC channel.

**Comment by gmelikov** [comment]
Yes, file is not actually deleted because ZFS holds it. Closed as support question, please use mailing lists.

**Comment by eztEgyed** [comment]
Thx
