### ISSUE TITLE
Simple HTTPS auth keyfile location for Encrypted volume key location

### ISSUE THREAD

**Issue by ACiDGRiM** [zfsonlinux/zfs#7064]
Why not provide support for a key on an https://user:password@keyserver.local:8080/zfs_keyfile
certificatebased auth could also be considered, but the above uri would be useful for an initial release

When kept on a secure network this would allow multiple systems to access the keyfile. storing the password for such a system in plaintext shouldn't be an issue as a malicious actor would have identical access if the keyfile was stored as a local partition or file.

The webserver serving the keyfile could then itself encrypt a zfs volume with the 32bit keyfile using a password or other source, and only decrypt to be available for hosts in the case of needing key recovery. Further protecting from unauthorized access

**Comment by sempervictus** [comment]
There was discussion of this in one of the PRs, but the basic premise is:
There's no reason to _not_ do it per se, if you have the time and effort to implement, that'd be awesome.
The difficulty comes from the GPL-only export of cryptographic interfaces which the CDDL module can't/shouldn't use. As a result, the illumos crypto subsystem is largely in ZoL. TLS implementations aren't light or simple, and also have licensing constraints, but there should be a couple of viable options. Lastly, you have the HTTP library requirement. Oh, and all of this has to be done without exposing the key (although thats a laughable concept these days with meltdown and spectre/casper/marley around every corner).
That said, its a great function to have, and if you've the time to implement it, i'm sure it would see heavy use.

**Comment by DeHackEd** [comment]
Considering that today ZFS requires the user app to do most of the heavy lifting, it implies a working userspace and you can implement something using, say, `curl` and scripting.

**Comment by ACiDGRiM** [comment]
I guess i'll just make the on boot ZFS initialization script pull the key file from the web server using curl to a tmpfs mount before mounting the data and then destroy the tmpfs.

Thanks, I didn't think of using curl, It just seemed like the keylocation=file:///path/to/key indicated support for uri's other than local fs
