### ISSUE TITLE
"fg: no job control" error on installing zfs .deb

### ISSUE THREAD

**Issue by darrenfreeman** [zfsonlinux/zfs#7074]
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Debian
Distribution Version    | 9.3
Linux Kernel                 | 4.9.65-3+deb9u2
Architecture                 | x86-64
ZFS Version                  | latest git
SPL Version                  | latest git

I've only recently switched to a .deb based system, so I'm sorry if I'm overlooking the obvious!

I'm currently getting errors on running apt-get install:

```
root@box:~# apt-get install edac-util
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: The package zfs needs to be reinstalled, but I can't find an archive for it.
```

I do remember ignoring some errors, so let's try this again:

```
root@box:~# dpkg -i /opt/zfs/pkgs/zfs/zfs_0.7.0-255_amd64.deb 
(Reading database ... 192027 files and directories currently installed.)
Preparing to unpack .../zfs/zfs_0.7.0-255_amd64.deb ...
Unpacking zfs (0.7.0-255) over (0.7.0-255) ...
/var/lib/dpkg/info/zfs.postrm: line 2: fg: no job control
dpkg: warning: subprocess old post-removal script returned error exit status 1
dpkg: trying script from the new package instead ...
/var/lib/dpkg/tmp.ci/postrm: line 2: fg: no job control
dpkg: error processing archive /opt/zfs/pkgs/zfs/zfs_0.7.0-255_amd64.deb (--install):
 subprocess new post-removal script returned error exit status 1
/var/lib/dpkg/tmp.ci/postrm: line 2: fg: no job control
dpkg: error while cleaning up:
 subprocess new post-removal script returned error exit status 1
Processing triggers for man-db (2.7.6.1-2) ...
Errors were encountered while processing:
 /opt/zfs/pkgs/zfs/zfs_0.7.0-255_amd64.deb
```

And it's dead again. apt-get install fails again. What should I try next?

**Comment by phreaker0** [comment]
I'm hitting this too, to workaround it (so I can install updated versions and make apt happy again) i just let the postrm script return and exit code of 0, before running the command which fails.
Just insert "exit 0" on line 1in /var/lib/dpkg/info/zfs.postrm until the issue is resolved.
