### ISSUE TITLE
zfs iostat: zfs send does not seem to affect bandwidth rates

### ISSUE THREAD

**Issue by voidzero** [zfsonlinux/zfs#7076]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Funtoo Linux (Gentoo derivative)
Linux Kernel                 | 4.14.13
Architecture                 | x86_64
ZFS Version                  | 0.7-release
SPL Version                  | 0.7-release
GCC version                  | 7.1.0

I am running a `zfs send | zfs receive` command, from and to local disks. In the output of `zpool iostat -v -Td`, the write speed on the receiving disk shows 102M. But the sending disk shows a read of 2.58MB total.

The receiving vdev is a single disk. The sending vdev is a raidz1 with four disks. Each disk shows approx. 666K, so the total read speed is 2.58MB give or take.

**Comment by DeHackEd** [comment]
Not a bug. `zfs send` can make use of compressed data (the stream itself is not compressed) and the data already cached in the ARC which can easily explain these events.

Also there is no 0.9-release version of ZFS.

**Comment by voidzero** [comment]
> Not a bug. zfs send can make use of compressed data (the stream itself is not compressed) and the data already cached in the ARC which can easily explain these events.

I don't think the data is cached. The max arc cache is 16G, I have a 10G cache device on the pool, and the sent data is already 285G. The speed seems to be slowly increasing btw, right now it's at 3.7MB/s. Most of the data on the pool has not been accessed during this session.

> Also there is no 0.9-release version of ZFS.
LOL, oops, typo. Fixed. :laughing:

**Comment by gmelikov** [comment]
@voidzero please check if actual disk read differs with `zpool iostat` (for ex. by `iostat -x 1`). It is normal that `zfs send` read speed differs from `zfs recv` write speed.
