### ISSUE TITLE
libdir configure seems not beeing respected

### ISSUE THREAD

**Issue by albundy83** [zfsonlinux/zfs#7083]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Ubuntu
Distribution Version    |  14.04
Linux Kernel                 | 3.13.0-137-generic
Architecture                 | amd64
ZFS Version                  | 0.7.5
SPL Version                  | 0.7.5

### Describe the problem you're observing
When compiling with the following configure command:
```bash
./configure LDFLAGS="-L/lib" --prefix=/usr --bindir=/bin --sbindir=/sbin --libdir=/lib --with-udevdir=/lib/udev --with-linux=/lib/modules/3.13.0-137-generic/build --with-linux-obj=/lib/modules/3.13.0-137-generic/build
````
Important information is `--libdir=/lib`
During make
```bash
make -s pkg-utils pkg-kmod
````
There is another ./configure which is triggered and it does not respect libdir parameter
```bash
Installing zfs-0.7.5-1.src.rpm
Executing(%prep): /bin/sh -e /tmp/zfs-build-gbellon-n0v6AuzH/TMP/rpm-tmp.UivgVY
+ umask 022
+ cd /tmp/zfs-build-gbellon-n0v6AuzH/BUILD
+ cd /tmp/zfs-build-gbellon-n0v6AuzH/BUILD
+ rm -rf zfs-0.7.5
+ /bin/tar -xf -
+ /bin/gzip -dc /tmp/zfs-build-gbellon-n0v6AuzH/SOURCES/zfs-0.7.5.tar.gz
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd zfs-0.7.5
+ /bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
Executing(%build): /bin/sh -e /tmp/zfs-build-gbellon-n0v6AuzH/TMP/rpm-tmp.xLqoW7
+ umask 022
+ cd /tmp/zfs-build-gbellon-n0v6AuzH/BUILD
+ cd zfs-0.7.5
+ CFLAGS='-O2 -g'
+ export CFLAGS
+ CXXFLAGS='-O2 -g'
+ export CXXFLAGS
+ FFLAGS='-O2 -g'
+ export FFLAGS
+ ./configure --host=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/lib64 --libexecdir=/usr/lib/x86_64-linux-gnu --localstatedir=/var --sharedstatedir=/usr/com --mandir=/usr/share/man --infodir=/usr/share/info --with-config=user --with-udevdir=/lib/udev --with-udevruledir=/lib/udev/rules.d --with-dracutdir=/usr/lib/dracut --disable-static --disable-debug --enable-sysvinit --disable-systemd
````
Important information is `--libdir=/lib64`
The deb files created for example libzpool2_0.7.5-1_amd64.deb etc ... are installed in /lib64

### Describe how to reproduce the problem
Just run ./configure and make specified

**Comment by albundy83** [comment]
According to my first seach, it seems an issue with https://github.com/zfsonlinux/zfs/blob/master/rpm/generic/zfs.spec.in and https://github.com/zfsonlinux/zfs/blob/master/rpm/generic/zfs-dkms.spec.in that does not use --libdir in ./configure:
```bash
%build
%configure \
    --with-config=user \
    --with-udevdir=%{_udevdir} \
    --with-udevruledir=%{_udevruledir} \
    --with-dracutdir=%{_dracutdir} \
    --disable-static \
    %{debug} \
    %{debuginfo} \
    %{asan} \
    %{systemd}
make %{?_smp_mflags}
```

**Comment by behlendorf** [comment]
@albundy83 the `%configure` macro when expanded will add `_libdir`.  That's currently defined as `_lib` which is the right default directory for rpm based systems.  What you're going to want to do is update `RPM_DEFINE_UTIL` in `config/zfs-build.m4` to pass the requested  `--libdir` to `rpmbuild`, then update the spec file to conditionally overdire the default when it's defined.  Patches welcome.

**Comment by albundy83** [comment]
The latest pull request seems good to me, I will close this issue.
https://github.com/zfsonlinux/zfs/pull/7101
