### ISSUE TITLE
zfs-import-cache.service fails after 7da8f8d81bf1fadc2d9dff10f0435fe601e919fa

### ISSUE THREAD

**Issue by WoefulDerelict** [zfsonlinux/zfs#7085]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Arch Linux
Distribution Version    | Rolling
Linux Kernel                 | 4.14.15
Architecture                 | x86-64
ZFS Version                  | cd0a89ded96d9cedbf20c70b533b616770ca4831
SPL Version                  | 23602fdb39e1254c669707ec9d2d0e6bcdbf1771

### Describe the problem you're observing

The zfs-import-cache.service fails after the introduction of `ExecStartPost=/bin/bash -c "/usr/bin/systemctl set-environment BOOTFS=$(@sbindir@/zpool list -H -o bootfs)"` in [7da8f8d81bf1fadc2d9dff10f0435fe601e919fa](https://github.com/zfsonlinux/zfs/commit/7da8f8d81bf1fadc2d9dff10f0435fe601e919fa)

The local output of `/usr/bin/zpool list -H -o bootfs` is
```
-
rpool/ROOT/default
```
The failure can be mitigated via `ExecStartPost=/bin/bash -c "/usr/bin/systemctl set-environment BOOTFS=$(@sbindir@/zpool list -H -o bootfs)" | grep -ve '^\-$'`

I don't have a reference for the output of  `/usr/bin/zpool list -H -o bootfs` from earlier versions of the Linux kernel and thus am unsure if this output is expected or a result of [7082](https://github.com/zfsonlinux/zfs/issues/7082)
### Describe how to reproduce the problem
1. Install ZFS from any point after [7da8f8d81bf1fadc2d9dff10f0435fe601e919fa](https://github.com/zfsonlinux/zfs/commit/7da8f8d81bf1fadc2d9dff10f0435fe601e919fa)
2. Boot the machine.
### Include any warning/errors/backtraces from the system logs

```
systemd[1]: Starting Import ZFS pools by cache file...
systemd[1]: Starting Mount ZFS filesystems...
zpool[2517]: no pools available to import
bash[2524]: Failed to set environment: Invalid environment assignments
systemd[1]: zfs-import-cache.service: Control process exited, code=exited status=1
systemd[1]: zfs-import-cache.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Import ZFS pools by cache file.
```

**Comment by behlendorf** [comment]
@prometheanfire can you look in to this.
