### ISSUE TITLE
ZFS performance significantly less than Raw disk + LUKS defaults

### ISSUE THREAD

**Issue by ACiDGRiM** [zfsonlinux/zfs#7091]
[ZFS blocksize.xlsx](https://github.com/zfsonlinux/zfs/files/1670827/ZFS.blocksize.xlsx)

ZFS 128-gcm bit encryption is faster that 128 cbc, but is much slower than Luks on a raw disk.
What information can I provide to help debug and improve this

See attached spreadsheet using 8MB fileblocks

modinfo zfs
filename:       /lib/modules/3.10.0-693.11.6.el7.x86_64/weak-updates/zfs/zfs/zfs.ko
version:        0.7.0-225_g823d48b
license:        CDDL
author:         OpenZFS on Linux
description:    ZFS
rhelversion:    7.4
srcversion:     CEA5E5BC518E82C69F42377
depends:        spl,znvpair,icp,zunicode,zcommon,zavl
vermagic:       3.10.0-693.2.2.el7.x86_64 SMP mod_unload modversions

**Comment by kpande** [comment]
use the mailing list for this please
