### ISSUE TITLE
Data stored in cache reads from L2ARC as well as from pool itself

### ISSUE THREAD

**Issue by matveevandrey** [zfsonlinux/zfs#7104]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Proxmox 5.1 (Debian with Ubuntu kernel)
Distribution Version    | 
Linux Kernel                 | Linux pve 4.13.13-5-pve #1 SMP PVE 4.13.13-38 
Architecture                 | x64
ZFS Version                  | 0.7.5
SPL Version                  |0.7.5

### Describe the problem you're observing
Every time I'm moving my VM disks from local ZFS (no matter stored in zvol or files) to external storage (NFS for example) "zpool iostat -v 1" shows that data is reading from both pool and cache with the same speed (eq to 1Gbs network limitation ~110Mbs)

I've performed some tests (warmed up the cache with VM disk data - to be sure that full disk image is in L2ARC cache) and than moved this disk to NFS storage. Exactly the same behavior - data was reading from both pool and L2ARC cache (with the speed ~110Mbs from both).

Is it done by design?

**Comment by kpande** [comment]
please use [the zfs-discuss mailing list](http://list.zfsonlinux.org) for support requests, and re-open a bug using the required information once it is determined that there is one (if so)

thanks!

**Comment by gmelikov** [comment]
Looks like you need to get https://github.com/zfsonlinux/zfs/commit/0873bb6337452e3e028e40f5dad945b30deab185 , it will be included in 0.7.6 release.

**Comment by gmelikov** [comment]
Did you compile ZFS by yourself? Proxmox distributes 0.7.4 with https://github.com/zfsonlinux/zfs/commit/0873bb6337452e3e028e40f5dad945b30deab185 cherry-pick http://download.proxmox.com/debian/pve/dists/stretch/pvetest/binary-amd64/zfsutils-linux_0.7.4-pve2~bpo9.changelog .

**Comment by matveevandrey** [comment]
cherry-pick - means that  0873bb6 has been included
and I'm talking about L2ARC! not ARC

**Comment by gmelikov** [comment]
If ARC hit rate is bad (which https://github.com/zfsonlinux/zfs/commit/0873bb6337452e3e028e40f5dad945b30deab185 fixes), then L2ARC hit rate is bad too.

>cherry-pick - means that 0873bb6 has been included

I don't understand what you mean by it. 

If you have more questions - feel free to use mailing lists.

**Comment by matveevandrey** [comment]
I mean than "cherry-pick" (in Proxmox update) means that patch 0873bb6 has been ported to Proxmox 0.7.4 and it fixes problem with ARC (I tested it for proxmox dev team) but L2ARC (with this patch) behaves in the way I described above

**Comment by gmelikov** [comment]
You are welcome in mailing lists with this question, be ready to write a reproducer.

**Comment by trisk** [comment]
Is the sysctl `vfs.zfs.l2arc_noprefetch` set? This will prevent the L2ARC from caching streaming workloads which would mean your disk image isn't populated into the L2ARC.
