### ISSUE TITLE
kernel.org builders need flex + bison

### ISSUE THREAD

**Issue by bunder2015** [zfsonlinux/zfs#7116]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | kernel.org buildbots
Distribution Version    | 
Linux Kernel                 | 4.16+
Architecture                 | 
ZFS Version                  | 
SPL Version                  | 

### Describe the problem you're observing
kernel.org builders need flex + bison

http://lkml.iu.edu/hypermail/linux/kernel/1802.0/00459.html
### Describe how to reproduce the problem
run tests

### Include any warning/errors/backtraces from the system logs
http://build.zfsonlinux.org/builders/Kernel.org%20Default%20x86_64%20%28BUILD%29/builds/18205/steps/shell_1/logs/configure

**Comment by dinatale2** [comment]
@bunder2015 I just opened zfsonlinux/zfs-buildbot#130. Do you mind making sure I got the package names right?

**Comment by bunder2015** [comment]
I don't know much about amazon, but if [this](https://aws.amazon.com/amazon-linux-ami/2017.09-packages/) is correct then your fix sounds right.

**Comment by dinatale2** [comment]
@bunder2015 thanks! PR was just merged.
