### ISSUE TITLE
Compilation Issue on Master

### ISSUE THREAD

**Issue by ronnyegner** [zfsonlinux/zfs#7121]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Ubuntu 
Distribution Version    | 17.04
Linux Kernel                 |  4.10.0-24-generic
Architecture                 | x64
ZFS Version                  | 0.7.0-128_gc616dcf8b
SPL Version                  | 0.7.0-16_g0cefc9d

### Describe the problem you're observing

Clone Master

```
./autogen
./configure
make

/usr/src/zfs/module/zfs/zio.c: In function ‘zio_wait’:
/usr/src/zfs/module/zfs/zio.c:1968:11: error: implicit declaration of function ‘cv_timedwait_io’ [-Werror=implicit-function-declaration]
   error = cv_timedwait_io(&zio->io_cv, &zio->io_lock,
           ^~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
scripts/Makefile.build:294: recipe for target '/usr/src/zfs/module/zfs/zio.o' failed
make[5]: *** [/usr/src/zfs/module/zfs/zio.o] Error 1
scripts/Makefile.build:567: recipe for target '/usr/src/zfs/module/zfs' failed
make[4]: *** [/usr/src/zfs/module/zfs] Error 2
Makefile:1524: recipe for target '_module_/usr/src/zfs/module' failed
make[3]: *** [_module_/usr/src/zfs/module] Error 2
make[3]: Leaving directory '/usr/src/linux-headers-4.10.0-24-generic'
Makefile:27: recipe for target 'modules' failed
make[2]: *** [modules] Error 2
make[2]: Leaving directory '/usr/src/zfs/module'
Makefile:732: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/usr/src/zfs'
Makefile:605: recipe for target 'all' failed
make: *** [all] Error 2
```

GCC version is:

`gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2) `

**Comment by DeHackEd** [comment]
Your described versions are wrong. You said zfs version c616dcf8b which was made on October 14th 2017, but the commit that causes this error is 8fb1ede which was made on December 18th.

Update your SPL version as well and rebuild/install it first before trying ZFS.

**Comment by ronnyegner** [comment]
I am trying to compile the current ZFS master. I have SPL (from current master) compiled but not yet installed. The error i get is when trying to compile the current ZFS master.

**Comment by ronnyegner** [comment]
OK. So it is NOT enough to compile only. You have to "make install" SPL before you can compile ZFS. Problem solved. Thanks @DeHackEd.
