### ISSUE TITLE
A 0.7.5.1 version?

### ISSUE THREAD

**Issue by hetzbh** [zfsonlinux/zfs#7124]
Hi,
I've seen [this commit](https://github.com/zfsonlinux/zfs/commit/0873bb6337452e3e028e40f5dad945b30deab185) which fixed ARC hit rate.

If I'm not mistaken, it's not in 0.7.5, so my question is: How about releasing a 0.7.5.1 version with this fix since it's pretty important?

**Comment by kpande** [comment]
this is not how bug reports work, please, see the project section for upcoming release information.

**Comment by tonyhutter** [comment]
Released: https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.7.6
