### ISSUE TITLE
incremental recv to filesystem with token says "dataset is busy"

### ISSUE THREAD

**Issue by kpande** [zfsonlinux/zfs#7129]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Gentoo
Distribution Version    | 17.0
Linux Kernel                 | 4.14.15
Architecture                 | amd64
ZFS Version                  | 0.7-release
SPL Version                  | 0.7-release

### Describe the problem you're observing
A recv failed when using `recv -s` due to network timeout.

My script attempted to send an incremental stream instead of resume, since it had matching snapshots.

The remote side says "dataset is busy", which is a somewhat useless message, considering the actual issue was the existence of a remote receive_resume_token.

Using the token to resume or aborting it resolves the condition.

**Comment by loli10K** [comment]
@kpande would something like this be acceptable?

```
root@linux:/usr/src/zfs# zfs send -i $POOLNAME/sendfs@snap1 $POOLNAME/sendfs@snap2 | zfs recv $POOLNAME/recvfs
cannot receive incremental stream: destination testpool/recvfs contains partially-complete state from "zfs receive -s".
```
