### ISSUE TITLE
receive_spill() should check byteswap for non-raw receives

### ISSUE THREAD

**Issue by tcaputi** [zfsonlinux/zfs#7130]
The `receive_spill()` code currently has a minor bug where it does not check for byteswap before assigning the arc buffer to the dbuf for non-raw sends. It is very unlikely that this effects anyone since causing the issue requires the following:

1. You are sending from a big endian host to a little endian one (or visa versa).
2. Your metadata is large enough to use spill blocks and you aren't using multi-slot dnodes
3. You are not doing a raw send of an encrypted dataset.

Nevertheless, this issue should be fixed at some point.

**Comment by loli10K** [comment]
Does https://github.com/zfsonlinux/zfs/commit/1a2342784aeb15049a3d4926615adf3b85f0bce4 fix this issue? Can we close this?

**Comment by tcaputi** [comment]
Yes. Thanks.
