### ISSUE TITLE
dracut running zfs-load-key.sh on non-systemd system

### ISSUE THREAD

**Issue by bunder2015** [zfsonlinux/zfs#7136]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | gentoo
Distribution Version    | n/a
Linux Kernel                 | 4.9.75
Architecture                 | amd64
ZFS Version                  | git master
SPL Version                  | git master

### Describe the problem you're observing
attempted to upgrade the kernel on my router and enlarge my ESP, on reboot dracut can't find systemctl on a non-systemd system, trying to load a key for a pool without encryption

could be related to #7134 , filing for completeness
### Describe how to reproduce the problem
update to git head and reboot
### Include any warning/errors/backtraces from the system logs

https://i.imgur.com/TQMjyPD.jpg

**Comment by kpande** [comment]
yep, same thing here. pretty nasty to kill booting systems. @tcaputi please fix.

**Comment by prometheanfire** [comment]
This was my addition :|

Can you try adding the following to the start of the file?

    [[ -e /bin/systemctl ]] || exit 0

**Comment by prometheanfire** [comment]
also, was that with this commit? https://github.com/zfsonlinux/zfs/commit/6d82b79699a40c9b8934286fabdcba5a68ee5bd6

**Comment by tcaputi** [comment]
Sorry, I'm not really familiar with dracut systems.... Let me know if there is anything I can do to help.

**Comment by prometheanfire** [comment]
@tcaputi this was my change, but I think https://github.com/zfsonlinux/zfs/commit/6d82b79699a40c9b8934286fabdcba5a68ee5bd6 should fix it, I just don't have a non systemd system to test with on hand.

**Comment by bunder2015** [comment]
6d82b79 doesn't seem to help, will try the other suggestion

**Comment by bunder2015** [comment]
the one-liner also doesn't work

https://i.imgur.com/74H3kdd.jpg

**Comment by prometheanfire** [comment]
Talked in irc, but here's what I need for more debugging

First, test on https://github.com/zfsonlinux/zfs/commit/6d82b79699a40c9b8934286fabdcba5a68ee5bd6 or later.

1. The output of rdsoreport.txt
2. manually running /lib/dracut/hooks/pre-mount/90-zfs-load-key.sh
3. lsinitrd on the initram

preferably all the above with the `[[-e /bin/systemctl]] || exit 0` as the first line after `#!/bin/bash` in the pre-mount hook file.
