### ISSUE TITLE
list.zfsonlinux.org dosn't send maily anymore

### ISSUE THREAD

**Issue by GregorKopka** [zfsonlinux/zfs#7146]
It may be the wrong place, but I have no clue where else to report it, so here I go.

list.zfsonlinux.org [198.50.226.105] seems to have problems, what I know is:
- it dosn't send me any mails anymore, even tried to get a reminder for my registered address but no mail received
- last mail received was 2018-02-07 02:41:11 [Re: [zfs-discuss] Relation between L2ARC and RAM size]
- it had accepted posts from me to the list after that one, these arrived in the archive but I didn't get a copy of them
- the only contacts my SMTP server had with 198.50.226.105 (according to the logs) since the mail mentioned above were the mails I sent to the list
- none of my customers (that use the same MX) complain about missing mail, I receive everything else I expect, everything seems to work nicely on my side

Could someone with access to the mailing list server please take a look?

**Comment by GregorKopka** [comment]
Update:
One mail I sent to the list on 07.02.2018 10:47 just arrived, as did the zfs-discuss@list.zfsonlinux.org mailing list reminder requested 20:07 (= ~40 minutes ago).

**Comment by ptx0** [comment]
should be fixed now, thanks for the report, overzealous spam protections were enacted for self explanatory reasons

**Comment by GregorKopka** [comment]
Mails are coming in, slowly but they do. Thanks for fixing.
