### ISSUE TITLE
key for encrypted dataset can't be loaded with latest master

### ISSUE THREAD

**Issue by phreaker0** [zfsonlinux/zfs#7152]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Ubuntu
Distribution Version    | 18.04 dev
Linux Kernel                 | 4.15.0-pf2+ (4.15.2)
Architecture                 | x86_64
ZFS Version                  | v0.7.0-298_g35e0202
SPL Version                  | v0.7.0-26_g48ef8ba

### Describe the problem you're observing

With the current master an encrypted dataset key can't be loaded. Using and older version (zfs: v0.7.0-277_g0d23f5e, spl: v0.7.0-24_g23602fd) on another workstation works fine:

```
# zfs load-key ext/e
Enter passphrase for 'ext/e': 
Key load error: Invalid parameters provided for ext/e.
```

The dataset/pool is affected by "Errata 3". But another (new) pool with encrypted datasets (with the new on disk format) is affected as well.

### Describe how to reproduce the problem

Load key for an encrypted dataset, following are the encryption properties used by my datasets:

```
ext/e  encryption            aes-256-gcm            -
ext/e  keylocation           prompt                 local
ext/e  keyformat             passphrase             -
ext/e  pbkdf2iters           342K                   -
ext/e  encryptionroot        ext/e                  -
ext/e  keystatus             unavailable            -
```

### Include any warning/errors/backtraces from the system logs

nothing in the system logs

**Comment by phreaker0** [comment]
seems to be an error on my side, compiled the latest master on the other workstation and it works fine there.

**Comment by prometheanfire** [comment]
-march=native is probably the enemy here (or something like that), maybe you compiled against the wrong sources as well?

**Comment by PSSGCSim** [comment]
I compiled today from the master and I am facing the same issue. What did you do differently to fix it? @phreaker0

**Comment by phreaker0** [comment]
for me it only works on workstations where i still have a patch around intended for another issue (#6539), i don't know where I got this snipped actually. The following patch does the trick for me:

```
diff --git a/configure.ac b/configure.ac
index 6dd6834a3..6068aaacc 100644
--- a/configure.ac
+++ b/configure.ac
@@ -44,6 +44,8 @@ AC_CONFIG_HEADERS([zfs_config.h], [
        (mv zfs_config.h zfs_config.h.tmp &&
        awk -f ${ac_srcdir}/config/config.awk zfs_config.h.tmp >zfs_config.h &&
        rm zfs_config.h.tmp) || exit 1])
+AC_CACHE_VAL([lt_cv_sys_lib_dlsearch_path_spec],[
+       lt_cv_sys_lib_dlsearch_path_spec="\$libdir `rpm --eval '/%{_lib}'`"])
 
 AC_PROG_INSTALL
 AC_PROG_CC
```

For me this is reproducible, if i compile without the patch, i can't load the keys. If i include it again it works again. So it seems that without the patch I'm linking to older/wrong libs or something?

@PSSGCSim maybe you can try the patch too and see if it also works for you?
@prometheanfire I don't set this flag explicitly, i use the following script to compile/install zfs:

```
#!/bin/bash
set -e

export LANG=C
export LANGUAGE=C
export LC_ALL=C

ZFS_VERSION="0.7.0"
KERNEL_SUFFIX="4.15.0-pf2+"

cd spl/
ls *.deb && mv *.deb ../spl_archive/
git clean -x -d -f
./autogen.sh
./configure --with-linux=/usr/src/linux-headers-${KERNEL_SUFFIX}/ \
            --with-linux-obj=/usr/src/linux-headers-${KERNEL_SUFFIX}/
make pkg-utils deb-dkms
for file in *.deb; do sudo gdebi -q --non-interactive $file; done

cd ../zfs
ls -l *.deb && mv *.deb ../zfs_archive/
./autogen.sh
./configure --with-linux=/usr/src/linux-headers-${KERNEL_SUFFIX}/ \
            --with-linux-obj=/usr/src/linux-headers-${KERNEL_SUFFIX}/ \
            --with-systemdunitdir=/usr/lib/systemd/system \
            --with-systemdpresetdir=/usr/lib/systemd/system-preset \
            --with-systemdmodulesloaddir=/usr/lib/modules-load.d \
            --enable-systemd
make pkg-utils deb-dkms
for file in *.deb; do sudo gdebi -q --non-interactive $file; done
cd ..
```
