### ISSUE TITLE
Support DOS partitioning

### ISSUE THREAD

**Issue by ryao** [zfsonlinux/zfs#719]
it seems that some EFI implementations refuse to start the MBR bootloader when they see a GPT partition signature:

http://forums.lenovo.com/t5/Linux-Discussion-Knowledge-Base/Configuring-SSD-to-run-with-Linux-Thinkpad-X220/ta-p/584583

This poses a problem for using ZFS as the root filesystem. As such, it would be useful to have an option for DOS partitioning at pool creation.

**Comment by rlaager** [comment]
What's the problem here? Partition the disk with an msdos label and put ZFS on the partition.
