### ISSUE TITLE
volumes missing from /dev/zvol

### ISSUE THREAD

**Issue by prometheanfire** [zfsonlinux/zfs#7213]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Gentoo
Distribution Version    | latest
Linux Kernel                 | 4.14.20
Architecture                 | x86_64
ZFS Version                  | 09302a4ca86df2a758c5b883e28b0952cfa31ff7
SPL Version                  | 378c6ed549e7d68eebb4b0bd37a09e66f70c647b

### Describe the problem you're observing
device nodes are missing
/dev/zd* and /dev/zvol/* are missing

### Describe how to reproduce the problem
have a zvol and reboot into the above zfs/spl versions

New volumes have device nodes created. toggling volmode to none, dev, default, full doesn't help.  Not sure what else to do...

### Include any warning/errors/backtraces from the system logs
nothing

**Comment by prometheanfire** [comment]
@tcaputi can't test the encryption if my iscsi devs can't get accessed :P

**Comment by tcaputi** [comment]
I'm assuming the zvols are encrypted? This patch should fix that issue: https://github.com/zfsonlinux/zfs/pull/7210

**Comment by tcaputi** [comment]
The patch was merged. You should be able to try again with the current master code.

**Comment by prometheanfire** [comment]
yep, they showed up again
