### ISSUE TITLE
zpools not visible after reboot after upgrade to 0.7.6 (Debian)

### ISSUE THREAD

**Issue by zeigerpuppy** [zfsonlinux/zfs#7232]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Debian Stretch (without systemd)
Distribution Version    | 4.9.65-3+deb9u1
Linux Kernel                 | 4.9.0-4-amd64
Architecture                 | amd64
ZFS Version                  | 0.7.6-1 (from release files)
SPL Version                  | 0.7.6-1

### Describe the problem you're observing

After upgrading to 0.7.6 (from 0.7.5), my two zpools are not visible on boot and require manual import.  Previously they were visible and the zfs filesystems mounted on reboot.

They can be manually imported 

```
zpool import zpool1
zpool import zpool2
```

There are no import errors.

I have tried rebuilding the zpool caches and initramfs

``` 
zpool set cachefile=/etc/zfs/zpool.cache zpool1
zpool set cachefile=/etc/zfs/zpool.cache zpool2
update-initramfs -u
```

I have also tried setting the variable in `/etc/default/zfs` to import all pools (although I'd prefer not to!)

```
ZPOOL_IMPORT_ALL_VISIBLE='yes'
```

This Debian system is running without `systemd`, perhaps that may have something to do with the issue.

There are no relevant boot errors that I can see and the pools function correctly once imported.

**Comment by kpande** [comment]
please use [the mailing list](http://list.zfsonlinux.org) for distribution support on ubuntu or debian systems since we don't provide packages for these

**Comment by zeigerpuppy** [comment]
For anyone that stumbles across this, the fix was simply to enable the init scripts for zfs, I guess this is not automatically done by the installer any more.

```
update-rc.d zfs-import defaults
update-rc.d zfs-mount defaults
update-rc.d zfs-share defaults
update-rc.d zfs-zed defaults
```
