### ISSUE TITLE
cannot import encrypted pool created with zfs-0.7-rc4

### ISSUE THREAD

**Issue by andi8086** [zfsonlinux/zfs#7240]
### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Arch-Linux
Distribution Version    |  -
Linux Kernel                 | 4.9.37
Architecture                 |  x64
ZFS Version                  |  0.7.2 / 0.7.6
SPL Version                  |  0.7.2 / 0.7.6

### Describe the problem you're observing

I initially enabled the features with:
```
zpool set feature@encryption=enabled cortex
zpool set feature@multi_vdev_crash_dump=enabled cortex
zpool set feature@large_dnode=enabled cortex
zpool set feature@sha512=enabled cortex
zpool set feature@skein=enabled cortex
zpool set feature@edonr=enabled cortex
zpool set feature@userobj_accounting=enabled cortex
zpool import cortex
zpool scrub cortex
```
**using spl-0.7.0-rc5 and zfs-0.7.0-rc4**.

Then I created encrypted filesystems like:

zfs create -o encryption=aes-256-gcm -o keyformat=raw -o     keylocation=file:///tmp/keys/cortex-photography.key cortex/photography

and now I wanted to upgrade to a newer ZOL version. However, I cannot reimport
and always get

```
This pool uses the following feature(s) not supported by this system:
	com.datto:encryption (Support for dataset level encryption)
cannot import 'cortex': unsupported version or feature
```
I tried 0.7.2 and 0.7.6 without success (from the git repo).

**Comment by andi8086** [comment]
Okay, forget it... I did not understand that the support for encryption is only in master on top of 0.7.0-something.... strange branching... a pitty.

**Comment by gmelikov** [comment]
master branch will be changed to 0.8 later.
