### ISSUE TITLE
bookmark should be usable for incremental stream

### ISSUE THREAD

**Issue by kpande** [zfsonlinux/zfs#7263]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Gentoo
Distribution Version    | 17.0
Linux Kernel                 | 4.14.20
Architecture                 | amd64
ZFS Version                  | master
SPL Version                  | master

### Describe the problem you're observing
`zfs send -I` is not supported with bookmark as incremental source. I do recall seeing recent work upstream for this.. can't find any PRs.

### Describe how to reproduce the problem

```
# /sbin/zfs send -Lvw -I rpool/ocean/GENTOO#1520046001 rpool/ocean/GENTOO@1520080201 > /dev/null 
Error: Unsupported flag with filesystem or bookmark.
# /sbin/zfs send -Lvw -i rpool/ocean/GENTOO#1520046001 rpool/ocean/GENTOO@1520080201 > /dev/null
send from rpool/ocean/GENTOO#1520046001 to rpool/ocean/GENTOO@1520080201
```

### Include any warning/errors/backtraces from the system logs
(omitted)

**Comment by kpande** [comment]
the same exists with `send -p`.

**Comment by denizzzka** [comment]
@kpande 
> the same exists with send -p.

How to use it?
