### ISSUE TITLE
Repository for Fedora 28

### ISSUE THREAD

**Issue by SolidTux** [zfsonlinux/zfs#7280]
I'm thinking of upgrading Fedora to [Branched](https://fedoraproject.org/wiki/Releases/Branched?rd=Branched) (version 28), but there is no repository yet.

Would it be possible to provide a repository for Fedora 28? What would be needed for that?

**Comment by avsej** [comment]
The beta release is going to happen soon (https://fedoraproject.org/wiki/Releases/28/Schedule), so having Fedora 28 repository would be great to test and report issues earlier.

**Comment by tonyhutter** [comment]
We've been testing to see if we can have a F28 repo up for the 0.7.7 release, but we're hitting some packaging problems.  If we can get those sorted out quickly and without much impact, then we'll include a F28 0.7.7 repo.  If not, then you'll have to wait for 0.7.8.

**Comment by avsej** [comment]
@tonyhutter, there was 0.7.7 release yesterday, and still no fc28 repository, does it mean that there were some issues, which will be resolved only once Fedora 28 will be released?

**Comment by tonyhutter** [comment]
@avsej unfortunately we couldn't come up with a quick fix for the fc28 packaging problems, so we'll have to wait for the next release.  We're using the rawhide builds for testing, and plan to have a new zfs out before fc28 though.

**Comment by maci0** [comment]
any update on this issue? I installed the fc27 rpms in fc28 and it worked fine.

**Comment by tonyhutter** [comment]
We're planning to support F28 in 0.7.9.  In fact, I'm putting together a patchset for it right now in  https://github.com/zfsonlinux/zfs/pull/7447.  I'd target first week of May for a release, since I'm out of the office this week and next week.

**Comment by gordonthree** [comment]
me too on this one, looking forward to 0.7.9 👍

**Comment by tonyhutter** [comment]
I merged in some last minute RHEL 7.5/F28 build fixes that popped up this week (#7463 and #7495).  If those test ok, then we should 0.7.9 out next week.

**Comment by awaybreaktoday** [comment]
Leaving notice to get notified of 0.7.9 release

**Comment by tonyhutter** [comment]
0.7.9 is out: https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.7.9
