### ISSUE TITLE
ZFS Freeze 

### ISSUE THREAD

**Issue by beloncfy** [zfsonlinux/zfs#7283]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  CentOS 7.X 
Distribution Version    |  7.4
Linux Kernel                 | 3.10.0-693.17.1.el7.x86_64
Architecture                 | 
ZFS Version                  |  0.7.6-1
SPL Version                  |  0.7.6-1

### Describe the problem you're observing
Zpool freeze again, can't even zfs list or navigate to the folder and run ls command. 

System load average > 900 currently , however there is no 100% on iowait .

Smartctl showing disks are healty, no error was found. And dd with >150MB/s reading speed when the pool was not accessible.
### Describe how to reproduce the problem
No idea why it happens. However this pool is mainly to receive data from other zfs host with zfs receive. 

The server has 2 pools however only this backup pool is freeze.

Happen twice within these 4 months. Possible send/receive too aggressive?
### Include any warning/errors/backtraces from the system logs

Can't find any relevant error log ,even on the console.

**Comment by kpande** [comment]
use [ the zfs-discuss mailing list](http://list.zfsonlinux.org) for support requests, this is not a bug.
