### ISSUE TITLE
ERROR: could not insert 'zfs': Unknown symbol in module, or unknown parameter (see dmesg) [...same issue as #6483]

### ISSUE THREAD

**Issue by msl86131** [zfsonlinux/zfs#7288]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Debian Jessie
Distribution Version    | 8.3
Linux Kernel                 | 3.16.0-4
Architecture                 | amd64
ZFS Version                  | 0.6.5.9-5~bpo8+1
SPL Version                  | 0.6.5.9-1~bpo8+1

### Describe the problem you're observing
I have a hardware limitation that forces me to use Debian Jessie 8.3, which comes w/ the 3.16.0-4 kernel. After a fresh OS install, I install zfs-dkms, but modprobe zfs returns error in the title. Everything I've seen points to version issues. Not sure if the spl module being 0.6.5.9-1  & zfs module being 0.6.5.9-5 is at issue here, but I'm not sure how to specify older packages for either.

### Describe how to reproduce the problem
-Fresh Debian 8.3 install.
-Follow instructions from Debian wiki page
-modprobe zfs throws error
-dmesg shows the following:
```
zfs: Unknown symbol setattr_prepare (err 0)
```

**Comment by kpande** [comment]
this is not a bug, use [the zfs-discuss mailing list](http://list.zfsonlinux.org) for support.
