### ISSUE TITLE
Need help installing 0.7.6-1 using dkms on RHEL kernel 2.6.32-573.26.1.el6.x86_64

### ISSUE THREAD

**Issue by sumo491bn** [zfsonlinux/zfs#7292]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  RHEL 
Distribution Version    |  6.9
Linux Kernel                 |  2.6.32-573.26.1
Architecture                 | X86_64
ZFS Version                  |  0.7.6
SPL Version                  | 0.7.6

### Describe the problem you're observing
When doing yum install zfs I get the following messages:
WARNING: Can't read module /lib/modules/2.6.32-573.26.1.el6.x86_64/weak-updates/icp.ko: No such file or directory
WARNING: Can't read module /lib/modules/2.6.32-573.26.1.el6.x86_64/weak-updates/zfs.ko: No such file or directory
WARNING: /lib/modules/2.6.32-573.26.1.el6.x86_64/weak-updates/zpios.ko needs unknown symbol dmu_tx_hold_write
WARNING: /lib/modules/2.6.32-573.26.1.el6.x86_64/weak-updates/zpios.ko needs unknown symbol dmu_read
WARNING: /lib/modules/2.6.32-573.26.1.el6.x86_64/weak-updates/zpios.ko needs unknown symbol dmu_tx_assign
WARNING: /lib/modules/2.6.32-573.26.1.el6.x86_64/weak-updates/zpios.ko needs unknown symbol dmu_tx_create
WARNING: /lib/modules/2.6.32-573.26.1.el6.x86_64/weak-updates/zpios.ko needs unknown symbol dmu_object_alloc
WARNING: /lib/modules/2.6.32-573.26.1.el6.x86_64/weak-updates/zpios.ko needs unknown symbol dmu_object_free
WARNING: /lib/modules/2.6.32-573.26.1.el6.x86_64/weak-updates/zpios.ko needs unknown symbol dmu_objset_own
WARNING: /lib/modules/2.6.32-573.26.1.el6.x86_64/weak-updates/zpios.ko needs unknown symbol dsl_destroy_head
WARNING: /lib/modules/2.6.32-573.26.1.el6.x86_64/weak-updates/zpios.ko needs unknown symbol dmu_write
WARNING: /lib/modules/2.6.32-573.26.1.el6.x86_64/weak-updates/zpios.ko needs unknown symbol dmu_objset_disown
WARNING: /lib/modules/2.6.32-573.26.1.el6.x86_64/weak-updates/zpios.ko needs unknown symbol dmu_objset_spa
WARNING: /lib/modules/2.6.32-573.26.1.el6.x86_64/weak-updates/zpios.ko needs unknown symbol spa_maxblocksize
WARNING: /lib/modules/2.6.32-573.26.1.el6.x86_64/weak-updates/zpios.ko needs unknown symbol dmu_tx_commit
WARNING: /lib/modules/2.6.32-573.26.1.el6.x86_64/weak-updates/zpios.ko needs unknown symbol dmu_tx_wait
WARNING: /lib/modules/2.6.32-573.26.1.el6.x86_64/weak-updates/zpios.ko needs unknown symbol dmu_tx_abort
WARNING: /lib/modules/2.6.32-573.26.1.el6.x86_64/weak-updates/zpios.ko needs unknown symbol dmu_object_set_blocksize
WARNING: /lib/modules/2.6.32-573.26.1.el6.x86_64/weak-updates/zpios.ko needs unknown symbol dmu_objset_create
WARNING: /lib/modules/2.6.32-573.26.1.el6.x86_64/weak-updates/zpios.ko needs unknown symbol dmu_tx_hold_free

### Describe how to reproduce the problem
yum install zfs

It appears to succeed, but with the messages above. The module is not loaded, so when doing /sbin/modprobe zfs, I get FATAL: Module zfs not found.

I verified that we are using kernel version 2.6.32-573.26.1, even though we upgraded almost everything else to 6.9. kernel-headers and kernel-devel are version 2.6.32-573.26.1. Should I try an older ZFS version?

**Comment by DeHackEd** [comment]
This is a bug tracker, not a support forum. Please use the mailing list.
