### ISSUE TITLE
ZVOL does not honor all sync write requests

### ISSUE THREAD

**Issue by jimsalterjrs** [zfsonlinux/zfs#7297]
### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Ubuntu
Distribution Version    |  16.04.4 LTS
Linux Kernel                 |  4.4.0-116-generic #140-Ubuntu SMP 
Architecture                 |  x86_64
ZFS Version                  |  0.6.5.6-0ubuntu16
SPL Version                  |  0.6.5.6-0ubuntu4

### Describe the problem you're observing
When benchmarking zvol performance today, I noticed that KVM guests with zvol-backed storage do not honor synchronous writes from `fio`, although guests with .qcow2-on-dataset-backed storage do.

The effect is more pronounced within a guest, but it's observable directly on the host as well. In the following run, despite `--ioengine=sync` being specified, please note that the job *begins* at 50.0%, and continues running for 12 seconds after supposedly finishing (due to my also having set `end_fsync=1`). If the synchronous writes were being honored during the run, there would be no zero-transfer updates after the run nominally finished as you see here (and in fact, there are none when using a dataset rather than a zvol).

There's obviously no way to capture it in a console log, but I can also physically observe the activity LEDs on my storage array still rapidly flashing for another two seconds or so after the final output (ie, after `--end_fsync=1` finishes).

~~~~
root@bench:/mnt/zvol# fio --name=random-write --ioengine=sync --iodepth=4 --rw=randwrite --bs=4k --direct=0 --size=512m --numjobs=16 --end_fsync=1random-write: (g=0): rw=randwrite, bs=4K-4K/4K-4K/4K-4K, ioengine=sync, iodepth=4
...
fio-2.2.10
Starting 16 processes
Jobs: 16 (f=16): [w(16)] [50.0% done] [0KB/869.2MB/0KB /s] [0/223K/0 iops] [eta 
Jobs: 16 (f=16): [w(16)] [50.0% done] [0KB/691.7MB/0KB /s] [0/177K/0 iops] [eta 
Jobs: 16 (f=16): [w(16)] [50.0% done] [0KB/506.7MB/0KB /s] [0/130K/0 iops] [eta 
Jobs: 16 (f=16): [w(16)] [55.6% done] [0KB/585.3MB/0KB /s] [0/150K/0 iops] [eta 
Jobs: 16 (f=16): [w(16)] [60.0% done] [0KB/584.9MB/0KB /s] [0/150K/0 iops] [eta 
Jobs: 16 (f=16): [w(16)] [63.6% done] [0KB/442.6MB/0KB /s] [0/113K/0 iops] [eta 
Jobs: 16 (f=16): [w(16)] [72.7% done] [0KB/275.6MB/0KB /s] [0/70.6K/0 iops] [eta
Jobs: 16 (f=16): [w(5),F(1),w(6),F(1),w(3)] [75.0% done] [0KB/200.5MB/0KB /s] [0
Jobs: 16 (f=16): [w(5),F(1),w(6),F(1),w(3)] [76.9% done] [0KB/156.2MB/0KB /s] [0
Jobs: 16 (f=16): [w(5),F(1),w(6),F(1),w(3)] [75.0% done] [0KB/92619KB/0KB /s] [0
Jobs: 16 (f=16): [w(5),F(1),w(6),F(1),w(3)] [76.5% done] [0KB/102.1MB/0KB /s] [0
Jobs: 16 (f=16): [w(5),F(1),w(6),F(1),w(3)] [77.8% done] [0KB/178.5MB/0KB /s] [0
Jobs: 16 (f=16): [w(2),F(1),w(2),F(1),w(6),F(1),w(3)] [83.3% done] [0KB/180.8MB/
Jobs: 16 (f=16): [w(2),F(2),w(1),F(1),w(6),F(1),w(3)] [84.2% done] [0KB/159.4MB/
Jobs: 16 (f=16): [w(2),F(2),w(1),F(2),w(3),F(1),w(1),F(2),w(1),F(1)] [85.0% done
Jobs: 16 (f=16): [w(2),F(2),w(1),F(2),w(3),F(1),w(1),F(2),w(1),F(1)] [90.0% done
Jobs: 16 (f=16): [w(2),F(2),w(1),F(2),w(3),F(1),w(1),F(2),w(1),F(1)] [86.4% done
Jobs: 16 (f=16): [w(2),F(2),w(1),F(2),w(3),F(1),w(1),F(2),w(1),F(1)] [87.0% done
Jobs: 16 (f=16): [F(16)] [100.0% done] [0KB/212.4MB/0KB /s] [0/54.4K/0 iops] [et
Jobs: 16 (f=16): [F(16)] [100.0% done] [0KB/0KB/0KB /s] [0/0/0 iops] [eta 00m:00
Jobs: 16 (f=16): [F(16)] [100.0% done] [0KB/0KB/0KB /s] [0/0/0 iops] [eta 00m:00
Jobs: 16 (f=16): [F(16)] [100.0% done] [0KB/0KB/0KB /s] [0/0/0 iops] [eta 00m:00
Jobs: 16 (f=16): [F(16)] [100.0% done] [0KB/0KB/0KB /s] [0/0/0 iops] [eta 00m:00
Jobs: 16 (f=16): [F(16)] [100.0% done] [0KB/0KB/0KB /s] [0/0/0 iops] [eta 00m:00
Jobs: 16 (f=16): [F(16)] [100.0% done] [0KB/0KB/0KB /s] [0/0/0 iops] [eta 00m:00
Jobs: 16 (f=16): [F(16)] [100.0% done] [0KB/0KB/0KB /s] [0/0/0 iops] [eta 00m:00
Jobs: 16 (f=16): [F(16)] [100.0% done] [0KB/0KB/0KB /s] [0/0/0 iops] [eta 00m:00
Jobs: 16 (f=16): [F(16)] [100.0% done] [0KB/0KB/0KB /s] [0/0/0 iops] [eta 00m:00
Jobs: 16 (f=16): [F(16)] [100.0% done] [0KB/0KB/0KB /s] [0/0/0 iops] [eta 00m:00
Jobs: 16 (f=16): [F(16)] [100.0% done] [0KB/0KB/0KB /s] [0/0/0 iops] [eta 00m:00
Jobs: 8 (f=8): [F(2),_(2),F(1),_(2),F(3),_(1),F(1),_(2),F(1),_(1)] [100.0% done] [0KB/0KB/0KB /s] [0/0/0 iops] [eta 00m:00s]
random-write: (groupid=0, jobs=1): err= 0: pid=8473: Tue Mar 13 16:49:55 2018
~~~~

### Describe how to reproduce the problem

~~~~
root@box:~# apt install fio
root@box:~# zfs create pool/zvol -V 20G
root@box:~# mkfs.ext4 /dev/zvol/pool/zvol
root@box:~# mkdir /mnt/zvol ; mount /dev/zvol/pool/zvol /mnt/zvol
root@box:~# cd /mnt/zvol
root@box:/mnt/zvol# fio --name=random-write --ioengine=sync --iodepth=4 --rw=randwrite --bs=4k --direct=0 --size=512m --numjobs=16 --end_fsync=1random-write: (g=0): rw=randwrite, bs=4K-4K/4K-4K/4K-4K, ioengine=sync, iodepth=4
~~~~

Look for the `fio` job to begin at a high percentage rather than at 0% or close; also look for the `fio` job to run for several seconds after reporting 100.0% complete and 00m:00s ETA, if possible look at drive activity LEDs (or a tool like `iotop` monitoring the physical disks in the vdev(s)) for continued writes after the `fio` run nominally finishes as well.

**Comment by richardelling** [comment]
In fio, sync calls read(2) and write(2). It doesn't necessarily call fsync. You can trace the actual system calls to see for sure. In any case, perhaps `--fsync=1` is what you want?

**Comment by loli10K** [comment]
I did trace the syscalls like suggested, `--ioengine=sync` does not seem to issue synchronous I/O. If fact, `fio(1)` does not even suggest `--ioengine=sync` would result in using synchronous I/O:

```
       ioengine=str
              Defines how the job issues I/O.  The following types are defined:

                     sync   Basic read(2) or write(2) I/O.  fseek(2) is used to position the I/O location.
```

Using `--fsync=1` (or `--sync=1`, which results in opening output files with `O_SYNC`) seem like a more correct approach to run this "synchronous benchmark"; this doesn't seem to be a ZFS issue though.

@jimsalterjrs were you able to verify what @richardelling suggested? Can we close this?

**Comment by kpande** [comment]
closing issue as resolved
