### ISSUE TITLE
zfs diff no result despite changes to fs being made

### ISSUE THREAD

**Issue by devZer0** [zfsonlinux/zfs#7303]
Distribution Name       | CentOS
Distribution Version    |  7.4.1708
Linux Kernel                 |  3.10.0-693.17.1.el7.x86_64
Architecture                 | x86_64
ZFS Version                  |  0.7.6-1
SPL Version                  |  0.7.6-1

### Describe the problem you're observing
i'm seeing that there are changes made to the filesystem (as you can see in snapshot "written") statistics, but i can't see which changes being made to that dataset.  as far as i know, nothing is writing to that dataset between the two snapshots.

for my curiousity, the number "196416" is occuring several times on several other datasets, too - where i would have expected "0" , as you can see from the snapshots before 11:01hrs

could one explain why i don't see a diff ?
can files change in a way that diff won't show it ? 
can zfs datasets change on blocklevel without files/dirs being changed/written to?

### Describe how to reproduce the problem

zfs list -t all -p -o name,written -r timemachinepool/tm8
NAME                                                           WRITTEN
timemachinepool/tm8                                                  0
timemachinepool/tm8@zfs-auto-snap_daily-2018-03-13-0250   131069501640
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-13-1601             0
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-13-1701             0
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-13-1801             0
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-13-1901        212784
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-13-2001             0
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-13-2101        212784
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-13-2201        196416
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-13-2301        196416
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-14-0001             0
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-14-0101             0
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-14-0201             0
timemachinepool/tm8@zfs-auto-snap_daily-2018-03-14-0225              0
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-14-0301             0
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-14-0401             0
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-14-0501             0
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-14-0601             0
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-14-0701    1288169784
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-14-0801    1937324664
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-14-0901     450602856
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-14-1001     216565008
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-14-1101     197741808
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-14-1201     190016112
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-14-1301     201686496
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-14-1401     208070016
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-14-1501     201473712
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-14-1601             0
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-14-1701             0
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-14-1801        196416
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-14-1901             0
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-14-2001             0
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-14-2101             0
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-14-2201             0
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-14-2301             0
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-15-0001             0
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-15-0101             0
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-15-0201             0
timemachinepool/tm8@zfs-auto-snap_daily-2018-03-15-0215              0
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-15-0301             0
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-15-0401             0
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-15-0501             0
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-15-0601             0
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-15-0701             0
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-15-0801             0
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-15-0901             0
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-15-1001             0
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-15-1101        196416
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-15-1201        196416
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-15-1301        196416
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-15-1401        196416
timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-15-1501        196416

zfs diff -FHt timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-15-1001 timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-15-1101

zfs diff -FHt timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-15-1101 timemachinepool/tm8@zfs-auto-snap_hourly-2018-03-15-1201

zfs list -t all -p -o name,written -r timemachinepool|grep 196416|wc -l
35

**Comment by loli10K** [comment]
> could one explain why i don't see a diff ?
> can files change in a way that diff won't show it ?
> can zfs datasets change on blocklevel without files/dirs being changed/written to?

Most probably you have "atime=on" on your dataset:

```
root@linux:/usr/src/zfs# POOLNAME='testpool'
root@linux:/usr/src/zfs# TMPDIR='/var/tmp'
root@linux:/usr/src/zfs# mountpoint -q $TMPDIR || mount -t tmpfs tmpfs $TMPDIR
root@linux:/usr/src/zfs# zpool destroy -f $POOLNAME
root@linux:/usr/src/zfs# rm -f $TMPDIR/zpool.dat
root@linux:/usr/src/zfs# fallocate -l 128m $TMPDIR/zpool.dat
root@linux:/usr/src/zfs# zpool create -f $POOLNAME $TMPDIR/zpool.dat
root@linux:/usr/src/zfs# zfs create -o atime=on $POOLNAME/fs1
root@linux:/usr/src/zfs# mktree -b /$POOLNAME/fs1 -d 3 -f 3
root@linux:/usr/src/zfs# zfs snap $POOLNAME/fs1@snap1
root@linux:/usr/src/zfs# zfs snap $POOLNAME/fs1@snap2
root@linux:/usr/src/zfs# zfs snap $POOLNAME/fs1@snap3
root@linux:/usr/src/zfs# find /$POOLNAME/fs1 > /dev/null
root@linux:/usr/src/zfs# zfs snap $POOLNAME/fs1@snap4
root@linux:/usr/src/zfs# zfs snap $POOLNAME/fs1@snap5
root@linux:/usr/src/zfs# zfs snap $POOLNAME/fs1@snap6
root@linux:/usr/src/zfs# zfs list -t all -p -o name,written -r $POOLNAME/fs1
NAME                WRITTEN
testpool/fs1              0
testpool/fs1@snap1   120832
testpool/fs1@snap2        0
testpool/fs1@snap3        0
testpool/fs1@snap4    24576
testpool/fs1@snap5        0
testpool/fs1@snap6        0
root@linux:/usr/src/zfs# for i in {2..6}; do
>    zfs diff $POOLNAME/fs1@snap$((i-1)) $POOLNAME/fs1@snap$i
> done
root@linux:/usr/src/zfs# 
```

With "atime=off":

```
root@linux:/usr/src/zfs# POOLNAME='testpool'
root@linux:/usr/src/zfs# TMPDIR='/var/tmp'
root@linux:/usr/src/zfs# mountpoint -q $TMPDIR || mount -t tmpfs tmpfs $TMPDIR
root@linux:/usr/src/zfs# zpool destroy -f $POOLNAME
root@linux:/usr/src/zfs# rm -f $TMPDIR/zpool.dat
root@linux:/usr/src/zfs# fallocate -l 128m $TMPDIR/zpool.dat
root@linux:/usr/src/zfs# zpool create -f $POOLNAME $TMPDIR/zpool.dat
root@linux:/usr/src/zfs# zfs create -o atime=off $POOLNAME/fs1
root@linux:/usr/src/zfs# mktree -b /$POOLNAME/fs1 -d 3 -f 3
root@linux:/usr/src/zfs# zfs snap $POOLNAME/fs1@snap1
root@linux:/usr/src/zfs# zfs snap $POOLNAME/fs1@snap2
root@linux:/usr/src/zfs# zfs snap $POOLNAME/fs1@snap3
root@linux:/usr/src/zfs# find /$POOLNAME/fs1 > /dev/null
root@linux:/usr/src/zfs# zfs snap $POOLNAME/fs1@snap4
root@linux:/usr/src/zfs# zfs snap $POOLNAME/fs1@snap5
root@linux:/usr/src/zfs# zfs snap $POOLNAME/fs1@snap6
root@linux:/usr/src/zfs# zfs list -t all -p -o name,written -r $POOLNAME/fs1
NAME                WRITTEN
testpool/fs1              0
testpool/fs1@snap1   120832
testpool/fs1@snap2        0
testpool/fs1@snap3        0
testpool/fs1@snap4        0
testpool/fs1@snap5        0
testpool/fs1@snap6        0
root@linux:/usr/src/zfs# for i in {2..6}; do
>    zfs diff $POOLNAME/fs1@snap$((i-1)) $POOLNAME/fs1@snap$i
> done
root@linux:/usr/src/zfs# 
```

**Comment by loli10K** [comment]
> could one explain why i don't see a diff ?
> can files change in a way that diff won't show it ?
> can zfs datasets change on blocklevel without files/dirs being changed/written to?

I believe this is explained by my comment above; with no feedback in months i think we can close this.
