### ISSUE TITLE
Bad disk takes proxmox down

### ISSUE THREAD

**Issue by donhwy** [zfsonlinux/zfs#7306]
I am not sure if this is zol or proxmox issue. I will report it here on advice of others.
I have a proxmox server with zfs pools on hbas. The os is on a hw raid. It has a failed drive. I did an upgrade yesterday that included a kernel. After rebooting zfs failed making the vm's unusable. zfs and zpool commands would just hang. To get it running I had to physically remove all the disks in the pool with the bad disk. Rebooted and it runs fine.

Don't know if the pastebin will be useful. https://pastebin.com/JjEbJdZ0

Thanks

**Comment by kpande** [comment]
sorry, this is indeed the wrong place. please use [the zfs-discuss mailing list](http://list.zfsonlinux.org)
