### ISSUE TITLE
iso URL for Ubuntu-18.04-Root-on-ZFS is broken

### ISSUE THREAD

**Issue by wheelcomplex** [zfsonlinux/zfs#7311]
https://github.com/zfsonlinux/zfs/wiki/Ubuntu-18.04-Root-on-ZFS

has a link to no exist URL: http://releases.ubuntu.com/18.04/ubuntu-18.04-desktop-amd64.iso

It should be http://cdimage.ubuntu.com/daily-live/current/bionic-desktop-amd64.iso

maybe should update to release URL a few days later.

**Comment by bunder2015** [comment]
FWIW, 18.04 hasn't been released yet.  It should be out on 2018-04-26.
