### ISSUE TITLE
Can not create ZVOL over full free space

### ISSUE THREAD

**Issue by c0d3z3r0** [zfsonlinux/zfs#7312]
### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Debian
Distribution Version    | 9
Linux Kernel                 | 4.9.0-4-amd64
Architecture                 | amd64
ZFS Version                  | 0.7.6-1
SPL Version                  | 0.7.6-1

### Describe the problem you're observing
Can not create ZVOL over full free space.

### Describe how to reproduce the problem

~~~
$ zpool create -f -o ashift=12 -o feature@edonr=enabled -m none root mirror /dev/disk/by-id/<disk1> /dev/disk/by-id/<disk2>
$ zpool list -p
NAME   SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
root  63887638528  602112  63887036416         -      0      0   1.00  DEGRADED  -
$ zfs list -p
NAME    USED        AVAIL  REFER  MOUNTPOINT
root  405504  61890744320  98304  none
$ zfs create -V $((61890744320/8192*8192)) -o checksum=edonr root/root
cannot create 'root/root': out of space
~~~

`$((61890744320/8192*8192))` is used to match blocksize

**Comment by c0d3z3r0** [comment]
I found the solution here: https://groups.google.com/a/zfsonlinux.org/forum/#!topic/zfs-discuss/EF34_jr6S6A

I knew that one should not fill ZFS to 100% with data but I didn't realize that even a ZVOL should be max. 70-90% of the pool.

I'll leave this open for some more comments from you but feel free to close the issue.

**Comment by kpande** [comment]
use `zfs create -s` but trying to write to a zvol that is larger than the pool will end up corrupting the zvol contents when the device is full.

**Comment by c0d3z3r0** [comment]
@kpande thanks for that tip but I assume that would be a really, really bad idea... I'll just create a ZVOL with 70-90%. I first need to test which size is the maximum size without performance issues.
