### ISSUE TITLE
Unable to take snapshot : "out of space error"  seems like because of wrong size calculations.

### ISSUE THREAD

**Issue by melihhsarica** [zfsonlinux/zfs#7321]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  CentOS Linux
Distribution Version    |  7.4.1708 (Core)
Linux Kernel                 |  3.10.0-693.17.1.el7.x86_64
Architecture                 | x86_64
ZFS Version                  | 0.7.6-1
SPL Version                  | 0.7.6-1

### Describe the problem you're observing
I have got a pool with 2TB disk attached. Deduplication is enabled
```
# zpool status
  pool: pf79827d87155
 state: ONLINE
  scan: none requested
config:

        NAME           STATE     READ WRITE CKSUM
        pf79827d87155  ONLINE       0     0     0
          sdc1         ONLINE       0     0     0
```
```
# zpool list
NAME            SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
pf79827d87155  1.98T   611G  1.39T         -     5%    30%  1.00x  ONLINE  -
```
with blockdevice datasets created in it. they are all shared as Volume Devices to the hosts
```
# zfs list -o name,used,refer,volsize,volblocksize,written,compression
NAME                          USED  REFER  VOLSIZE  VOLBLOCK  WRITTEN  COMPRESS
pf79827d87155                1.92T    96K        -         -      96K       off
pf79827d87155/f035d45915c9c  33.0G  6.11G      32G        8K    6.11G    gzip-8
pf79827d87155/f1dc30f87b140  32.0G   828M      32G        1M     828M       off
pf79827d87155/f3089f8f4aa56  1.49G   110G     512G        8K    1.49G       off
pf79827d87155/f4e4dd6f1b898  33.0G  2.88G      32G        8K    2.88G       off
pf79827d87155/f56f210ab12f9   760G   110G     512G        8K    2.61M    gzip-8
pf79827d87155/fa3be722f095e  33.1G   120M      32G        8K     188K    gzip-8
pf79827d87155/faabf49a085fe  24.6G   112G     512G        1M    24.6G       off
pf79827d87155/fcea0ae83751d   128G    56K     128G        1M      56K    gzip-8
pf79827d87155/fd2dead72d25c   855G  97.6G     512G        1M    1.18M       lz4
pf79827d87155/ffec264a82020  64.0G    56K      64G        1M      56K    gzip-8
```
The problem is used values are much higher than the dataset initial sizes. 
everytime i copy the newer files ( like a backup operation) to dataset and take a snapshot it used size grows by the size of the whole data.
for example . 
dataset pf79827d87155/fd2dead72d25c is 512GB initial size. 
used size of this dataset is 176GB when u check from the mount point with du -sh
it has snapshots
```
# zfs list -t snapshot | grep pf79827d87155/fd2dead72d25c
pf79827d87155/fd2dead72d25c@20180314233406  51.3G      -  92.7G  -
pf79827d87155/fd2dead72d25c@20180319010002     0B      -  93.2G  -
pf79827d87155/fd2dead72d25c@20180319010016     0B      -  93.2G  -
pf79827d87155/fd2dead72d25c@20180319030252  41.6G      -  97.1G  -
pf79827d87155/fd2dead72d25c@20180319045308  48.0G      -  97.8G  -
pf79827d87155/fd2dead72d25c@20180319065558  47.5G      -  97.3G  -
pf79827d87155/fd2dead72d25c@20180319085325  1.18M      -  97.6G  -
```
its seems like in the used value of the dataset is the sum of the all  refer value of snapshots + refer value of the dataset itself.

and also for dataset pf79827d87155/f035d45915c9c it just created and 6 GB of data copied in it.
when i try to create a snapshot it says
```
# zfs snapshot pf79827d87155/f035d45915c9c@dd
cannot create snapshot 'pf79827d87155/f035d45915c9c@dd': out of space
```

### Describe how to reproduce the problem
create a pool 
enable deduplication
create dataset as a blockDevice with compression
create a VolumeGroup using dataset
format it as ext4 file system 
Mount Volume Group 

Copy a huge data in it.
take a snapshot on the zfs side
u ll see that used value is higher than the total dataset capacity
copy same data with a lil changes 
take snapshot again 
used size grows everytime u copy data in it and take snapshot.

when all used size reaches the total pool capacity u cant take snapshot again because "out of space" error.

**Comment by rincebrain** [comment]
@melihhsarica So, IRC or the zfs-discuss mailing list would be a better place to ask this, but in general, zvols require enough space available to overwrite all the data in the live version of the zvol, because most of the things you'd use a zvol for don't like it if they run out of space when trying to overwrite a block.

So you need (space for all the referenced data from all snapshots and the live version of the zvol)+(enough space to overwrite the whole thing once).

**Comment by melihhsarica** [comment]
Why did you close this question?

As U can see i ve got more than 1 TB free space on my pool .

I can create new datasets and copy data in it but when it comes to snapshot it gives outof space error.

**Comment by rincebrain** [comment]
@melihhsarica zpool list is telling you how much space on the pool is not currently being used by anything, zfs list is telling you that nearly all the space on the pool is reserved between the snapshots on the various zvols and the reservations to overwrite them all.

What does zfs list -o space think of pf79827d87155? That will give you more insight into why this is failing.

**Comment by kpande** [comment]
question != bug

please use [the zfs-discuss mailing list](http://list.zfsonlinux.org) for support, or IRC (#zfsonlinux on Freenode).

**Comment by melihhsarica** [comment]
What does zfs list -o space think of pf79827d87155? gives 3GB according to this its abvious to have this error. 
But 
zfs list -o space gives used space of the datasets pf79827d87155/fd2dead72d25c 855GB.
in this dataset. 176 GB uncompressed data that u can see from du -sh
listed as  96 GB of phsical data on dataset and 188GB of snapshot used(in 7 snapshts)  and value of totally used space must be 294 GB  but its says 855 GB used space. this is the problem i guess

```
# zfs list -o space
NAME                         AVAIL   USED  USEDSNAP  USEDDS  USEDREFRESERV  USEDCHILD
pf79827d87155                3.62G  1.92T        0B     96K             0B      1.92T
pf79827d87155/f035d45915c9c  30.5G  33.0G        0B   6.11G          26.9G         0B
pf79827d87155/f1dc30f87b140  34.8G  32.0G        0B    828M          31.2G         0B
pf79827d87155/f3089f8f4aa56  3.62G  1.49G        0B   1.49G             0B         0B
pf79827d87155/f4e4dd6f1b898  33.7G  33.0G        0B   2.88G          30.1G         0B
pf79827d87155/f56f210ab12f9   532G   760G      122G    110G           528G         0B
pf79827d87155/fa3be722f095e  36.6G  33.1G      188K    120M          33.0G         0B
pf79827d87155/faabf49a085fe  3.62G  24.6G        0B   24.6G             0B         0B
pf79827d87155/fcea0ae83751d   132G   128G        0B     56K           128G         0B
pf79827d87155/fd2dead72d25c   516G   855G      245G   97.6G           512G         0B
pf79827d87155/ffec264a82020  67.6G  64.0G        0B     56K          64.0G         0B
```
```
# zfs list -t snapshot -o space
NAME                                        AVAIL   USED  USEDSNAP  USEDDS  USEDREFRESERV  USEDCHILD
pf79827d87155/fd2dead72d25c@20180314233406      -  51.3G         -       -              -          -
pf79827d87155/fd2dead72d25c@20180319010002      -     0B         -       -              -          -
pf79827d87155/fd2dead72d25c@20180319010016      -     0B         -       -              -          -
pf79827d87155/fd2dead72d25c@20180319030252      -  41.6G         -       -              -          -
pf79827d87155/fd2dead72d25c@20180319045308      -  48.0G         -       -              -          -
pf79827d87155/fd2dead72d25c@20180319065558      -  47.5G         -       -              -          -
pf79827d87155/fd2dead72d25c@20180319085325      -  1.18M         -       -              -          -
```

**Comment by melihhsarica** [comment]
@kpande I ve create a message on zfs-discuss. 

thanks for directing.
