### ISSUE TITLE
wiki issue: 16.04 root on ZFS, multiple disks

### ISSUE THREAD

**Issue by Mrten** [zfsonlinux/zfs#7332]
re. 4.8b: if you're using raidz for the pool, shouldn't all the -n3 partitions on the different disks get a msdos partition? otherwise, if the first disk fails, there is no bootloader.

**Comment by rlaager** [comment]
The UEFI partitions are duplicated later, after the first boot. This is step 6.8b in the current 18.04 HOWTO.

You might also be interested in this comment: https://github.com/zfsonlinux/zfs/issues/6798#issuecomment-565766257
