### ISSUE TITLE
All deprecated <attr/xattr.h> headers should be switched to <sys/xattr.h> instead.

### ISSUE THREAD

**Issue by fearedbliss** [zfsonlinux/zfs#7344]
Hello,

Gentoo has removed/placed in temp QA our "sys-apps/attr-2.4.48" package. With this change, a number of applications that are still relying on the deprecated attr header have since started to fail to compile. ZFS is one of these applications, and means that all of the zfs versions on Gentoo are now failing if they rely on this deprecated library. We will probably patch the sources to use the new headers but I'm not sure if this will lead to any types of regressions.

The folks upstream for attr have recommended for people to switch their headers to the new sys/xattr.h since all attr/xattr.h functionality has been in glibc for a long time.

http://git.savannah.nongnu.org/cgit/attr.git/commit/?id=7921157890d07858d092f4003ca4c6bae9fd2c38

- Jonathan

**Comment by ryao** [comment]
I wonder how long ago was ages ago. We could try changing things and see if the buildbot is happy with it. Otherwise, we get to have another autotools check.

**Comment by DeHackEd** [comment]
`tests/zfs-tests/cmd/mktree/mktree.c` and `tests/zfs-tests/cmd/xattrtest/xattrtest.c` seem to be the only files that need xattr.h...

CentOS 6 seems to be okay with a simple:
```
sed -i s%attr/xattr.h%sys/xattr.h%g tests/zfs-tests/cmd/mktree/mktree.c tests/zfs-tests/cmd/xattrtest/xattrtest.c
```
And it compiles with `/usr/include/attr/xattr.h` unusable. CentOS 6 is our oldest supported distro, so I guess that means this is okay.
