### ISSUE TITLE
etc/init.d/zfs-mount tries to mount swap zvol

### ISSUE THREAD

**Issue by gyakovlev** [zfsonlinux/zfs#7346]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Gentoo
Distribution Version    | current
Linux Kernel                 | 0.7.7-r0-gentoo
Architecture                 | x86_64
ZFS Version                  | 0.7.7-r0-gentoo
SPL Version                  | 0.7.7-r0-gentoo

### Describe the problem you're observing
gentoo bug https://bugs.gentoo.org/647248

zfs-mount initscript  looks for 2 patterns while trying to mount zvols

```read_fstab "^/dev/(zd|zvol)"```

so anything that matches /dev/zd* or /dev/zvol/* in fstab will be attempted to be mounted by zfs-mount.
this does not account for possible _swap_ with mountpoint field set to _none_

and [this wiki page](https://github.com/zfsonlinux/pkg-zfs/wiki/HOWTO-use-a-zvol-as-a-swap-device) describes this as supported use-case

I think initscript should ignore zvols with empty mount point.

### Describe how to reproduce the problem
User has the following line in /etc/fstab
```fstab
/dev/zvol/zroot/swap	none	swap	sw	0 0
```

so zfs-mount will attempt to run
```sh
fsck "$dev" && mount "$mntpt"
```

where ```$mntpt``` is _none_

result is
```sh
 * Mounting ZFS filesystem(s)  ...
 [ ok ]
fsck from util-linux 2.30.2
mount: none: mount point does not exist.
```

I'd like to submit a pr for this one but I'm not sure what is the preferred solution.

adding 
```sh
echo "$mntpnt" | egrep -qE '^none' && continue
```
to read_fstab function right after similar check seems to filter it out and works for my use case.

if I's acceptable I'll submit a pr.

### Include any warning/errors/backtraces from the system logs

```sh
read_fstab "^/dev/(zd|zvol)"
+ read_fstab '^/dev/(zd|zvol)'
+ local 'match=^/dev/(zd|zvol)'
+ local i var TMPFILE
++ env
++ grep --colour=auto '^FSTAB_'
++ sed 's,=.*,,'
+ unset FSTAB_3 FSTAB_2 FSTAB_1 FSTAB_0 FSTAB_dev_3 FSTAB_dev_2 FSTAB_dev_1 FSTAB_dev_0
+ i=0
+ read -r fs mntpnt fstype opts
+ egrep --colour=auto -qE '^#|^$'
+ echo '#PARTUUID=b8ea456c-1f3a-6f41-b1ab-b51061f30d43'
+ continue
+ read -r fs mntpnt fstype opts
+ echo PARTUUID=a1ab0c25-ad16-1148-8691-7b1941db7fb7
+ egrep --colour=auto -qE '^#|^$'
+ grep --colour=auto -qE '^/dev/(zd|zvol)'
+ echo 'PARTUUID=a1ab0c25-ad16-1148-8691-7b1941db7fb7 /boot vfat noatime 0 0'
+ read -r fs mntpnt fstype opts
+ egrep --colour=auto -qE '^#|^$'
+ echo UUID=b9bd7f04-3b7e-4eea-ae24-2a3bedf2afb0
+ grep --colour=auto -qE '^/dev/(zd|zvol)'
+ echo 'UUID=b9bd7f04-3b7e-4eea-ae24-2a3bedf2afb0 none swap sw,pri=0,discard 0 0'
+ read -r fs mntpnt fstype opts
+ egrep --colour=auto -qE '^#|^$'
+ echo UUID=4e5754d0-1783-4630-ad71-b7f10b6b4df5
+ grep --colour=auto -qE '^/dev/(zd|zvol)'
+ echo 'UUID=4e5754d0-1783-4630-ad71-b7f10b6b4df5 none swap sw,pri=0,discard 0 0'
+ read -r fs mntpnt fstype opts
+ egrep --colour=auto -qE '^#|^$'
+ echo zhome/home
+ grep --colour=auto -qE '^/dev/(zd|zvol)'
+ echo 'zhome/home /home zfs defaults 0 0'
+ read -r fs mntpnt fstype opts
+ egrep --colour=auto -qE '^#|^$'
+ echo '#proc'
+ continue
+ read -r fs mntpnt fstype opts
+ egrep --colour=auto -qE '^#|^$'
+ echo '#tmpfs'
+ continue
+ read -r fs mntpnt fstype opts
+ echo '#tmpfs'
+ egrep --colour=auto -qE '^#|^$'
+ continue
+ read -r fs mntpnt fstype opts
+ egrep --colour=auto -qE '^#|^$'
+ echo /dev/zvol/zroot/swap
+ grep --colour=auto -qE '^/dev/(zd|zvol)'
+ echo '/dev/zvol/zroot/swap none swap sw,pri=0	0 0'
+ eval export FSTAB_dev_0=/dev/zvol/zroot/swap
++ export FSTAB_dev_0=/dev/zvol/zroot/swap
++ FSTAB_dev_0=/dev/zvol/zroot/swap
++ printf '%b\n' /dev/zvol/zroot/swap
++ sed s,/,_,g
+ fs=_dev_zvol_zroot_swap
+ eval export FSTAB_0=none
++ export FSTAB_0=none
++ FSTAB_0=none
+ i=1
+ read -r fs mntpnt fstype opts
```

extracted for readability:
```sh
FSTAB_0=none
FSTAB_dev_0=/dev/zvol/zroot/swap
```

**Comment by kpande** [comment]
please open a PR for review, thanks for bringing this up!
