### ISSUE TITLE
DKMS build failure on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by darrenfreeman** [zfsonlinux/zfs#7348]
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | openSUSE
Distribution Version    | Tumbleweed
Linux Kernel                 | 4.15.9-1-default #1 SMP PREEMPT
Architecture                 | x86-64
ZFS Version                  | git, latest
SPL Version                  | git, latest

I'm trying to install zfs on a machine that's never had it before. I did a zypper dup to upgrade the whole system to the latest packages, before proceeding.

I performed: `./autogen.sh && ./configure && make pkg`

I'm not entirely sure which of the RPMs I should be installing. I think the install guide could really use an explanation of what all the different packages are for, and which are optional or mutually exclusive.

Starting from no installed packages, I performed:

`rpm -i spl-0.7.0-31_g43983eb.x86_64.rpm spl-dkms-0.7.0-31_g43983eb.noarch.rpm`

```
Loading new spl-0.7.0 DKMS files...
Building for 4.15.9-1-default
Building initial module for 4.15.9-1-default
Error! Bad return status for module build on kernel: 4.15.9-1-default (x86_64)
Consult /var/lib/dkms/spl/0.7.0/build/make.log for more information.
warning: %post(spl-dkms-0.7.0-31_g43983eb.noarch) scriptlet failed, exit status 10
```

From that log:

```
  Building modules, stage 2.
  MODPOST 2 modules
  CC      /var/lib/dkms/spl/0.7.0/build/module/spl/spl.mod.o
  CC      /var/lib/dkms/spl/0.7.0/build/module/splat/splat.mod.o
  LD [M]  /var/lib/dkms/spl/0.7.0/build/module/spl/spl.ko
  LD [M]  /var/lib/dkms/spl/0.7.0/build/module/splat/splat.ko
make[3]: Leaving directory '/usr/src/linux-4.15.9-1-obj/x86_64/default'
make[2]: Leaving directory '/var/lib/dkms/spl/0.7.0/build/module'
make[2]: Entering directory '/var/lib/dkms/spl/0.7.0/build'
make[2]: *** No rule to make target 'module/NONE', needed by 'all-am'.  Stop.
make[2]: Leaving directory '/var/lib/dkms/spl/0.7.0/build'
make[1]: *** [Makefile:609: all-recursive] Error 1
make[1]: Leaving directory '/var/lib/dkms/spl/0.7.0/build'
make: *** [Makefile:490: all] Error 2
```

**Comment by darrenfreeman** [comment]
I'm using the latest git, it always calls itself 0.7.0. But it's newer than 0.7.7.

**Comment by darrenfreeman** [comment]
```
commit 43983eb2024ec6b3280e6e06a6fb621ee3bb2a41 (HEAD -> master, origin/master, origin/HEAD)
Author: LOLi <loli10K@users.noreply.github.com>
Date:   Fri Mar 9 22:51:31 2018 +0100
```

**Comment by fcicq** [comment]
spl repo is here https://github.com/zfsonlinux/spl

**Comment by darrenfreeman** [comment]
Sorry about that.. you want me to open a new issue?

**Comment by darrenfreeman** [comment]
Issue opened on the spl repo.

**Comment by behlendorf** [comment]
@darrenfreeman this was caused by upstream kernel bug https://bugzilla.redhat.com/show_bug.cgi?id=1550152#c6 which effectively breaks all external kernel module builds starting with the 4.15.9-1 kernel.

You're going to want to rollback to an earlier kernel until they sort this out.  The fedora developers are [rolling back this change](https://src.fedoraproject.org/rpms/kernel/c/0ff2afdbe0501525ee2d5b53fdc20a320b29bc8c?branch=master) but it'll be up to each distribution how to handle this in the short term.
