### ISSUE TITLE
Debian Stretch: zfs dkms module build fails with `NR_FILE_PAGES in either node_stat_item or zone_stat_item: NOT FOUND`

### ISSUE THREAD

**Issue by creshal** [zfsonlinux/zfs#7358]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Debian
Distribution Version    | 9.4
Linux Kernel                 | 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3
Architecture                 | amd64
ZFS Version                  | 0.7.7
SPL Version                  | 0.7.7

### Describe the problem you're observing

`dkms build zfs/0.7.7` fails with: 

```[…]
checking whether asm/fpu/api.h exists... yes                                               
checking whether i_(uid|gid)_(read|write) exist... yes                               
checking whether module_param_call() is hardened... no                          
checking whether iops->rename() wants flags... yes
checking whether generic_setxattr() exists... no  
checking whether current_time() exists... yes     
checking whether global_node_page_state() exists... yes                                            
checking whether global_zone_page_state() exists... no                                                   
checking whether enum node_stat_item contains NR_FILE_PAGES... no                          
checking whether enum node_stat_item contains NR_INACTIVE_ANON... no                 
checking whether enum node_stat_item contains NR_INACTIVE_FILE... no            
checking whether enum node_stat_item contains NR_SLAB_RECLAIMABLE... no
checking whether enum zone_stat_item contains NR_FILE_PAGES... no
checking whether enum zone_stat_item contains NR_INACTIVE_ANON... no                   
checking whether enum zone_stat_item contains NR_INACTIVE_FILE... no                  
checking whether enum zone_stat_item contains NR_SLAB_RECLAIMABLE... no                   
checking global_page_state enums are sane... no                                     
NR_FILE_PAGES in either node_stat_item or zone_stat_item: NOT FOUND
configure needs updating, see: config/kernel-global_page_state.m4
configure: error: in `/var/lib/dkms/zfs/0.7.7/build':
configure: error: SHUT 'ER DOWN CLANCY, SHE'S PUMPIN' MUD!
```
[(Full log)](https://up.tao.at/-28b2237770bca193b2c1599e144b89c7/dkms)

### Describe how to reproduce the problem

1. Build spl and zfs each with default settings (`autogen.sh && configure`), build utils and dkms packages (`make deb-utils deb-dkms`)
2. Install the generated spl and spl-dkms packages, notice dkms build works.
3. Install the generated packages for libraries (uutil, nvpair, zfs2, zfs2-devel, zpool2), zfs and zfs-dkms.
4. Notice dkms build fails without any error message, manually re-run `dkms build zfs/0.7.7` to get to aforementioned error message.

`make deb-kmod` doesn't trigger any error fwiw and *seems* to build fine, but modprobe fails with
```
[  220.500838] zcommon: disagrees about version of symbol __kstat_delete
[  220.500841] zcommon: Unknown symbol __kstat_delete (err -22)
[  220.500864] zcommon: disagrees about version of symbol __kstat_create
[  220.500866] zcommon: Unknown symbol __kstat_create (err -22)
[  220.500885] zcommon: disagrees about version of symbol __kstat_set_raw_ops
[  220.500886] zcommon: Unknown symbol __kstat_set_raw_ops (err -22)
[  220.500915] zcommon: disagrees about version of symbol __kstat_install
[  220.500917] zcommon: Unknown symbol __kstat_install (err -22)
```

Is this related, or a different issue?

**Comment by creshal** [comment]
FWIW, I'm trying to upgrade from 0.7.3, where zfs-dkms built the same way worked fine.

**Comment by dioni21** [comment]
This is also criplling instalation on RHEL latest kernel-3.10.0-693.21.1.el7.x86_64

It works perfectly at kernel-3.10.0-693.5.2.el7.x86_64

**Comment by dioni21** [comment]
> This is also criplling instalation on RHEL latest **kernel-3.10.0-693.21.1.el7.x86_64**
> 
> It works perfectly at kernel-3.10.0-693.5.2.el7.x86_64

Indeed, I could make it work!  Still not sure about what the problem is, but what does not work is upgrading!

I removed every instance of old kernel and kernel-devel from the new machine.  Also, removed every .ko file from **/lib/modules/3.10.0-693.21.1.el7.x86_64/weak-updates/**

After this, **yum reinstall spl-dkms && yum reinstall zfs-dkms**, (or something like that, it was not straightforward) and now everything works...

**Comment by turrini** [comment]
The same problem happens too with Debian Buster (Linux 4.15.0-2 [4.15.11])

**Comment by turrini** [comment]
The same problem happens too with Debian Buster (Linux 4.15.0-2 [4.15.11])

**Comment by creshal** [comment]
For Debian Stretch the files are in `/usr/src/`, not `/usr/include/`, but I can confirm the workaround works. Now how can it be fixed permanently?

**Comment by turrini** [comment]
@creshal Sorry and thanks for fixing it :-)

**Comment by jaredj** [comment]
I experienced the issue @akorn encountered and found that at least for me it was an issue with the debian packaging: the `override_dh_auto_install` target in `debian/rules` goes to some trouble to install a minimal set of files in `/usr/src/zfs-${version}`, excluding all plain files within `scripts/` from installation.  FTR I was using a modifed version of a PPA package of 0.7.1 so YMMV.  I worked around the issue by modifying `debian/rules` to install all files in `scripts/` although I'm sure it would be possible to special-case only that specific file.

It sounds like the issue @akorn and I encountered was separate from the one worked around by @turrini

**Comment by akorn** [comment]
I agree, it was a separate issue. I also build my own packages based on the pkg-zfs repository.

**Comment by jaredj** [comment]
@akorn in case it's useful my modification to `debian/rules` can be seen [here](https://github.com/ReplibitLLC/trusty-backport/blob/master/Dockerfile#L144-L147)

**Comment by aerusso** [comment]
@creshal Could you confirm that PR #7554 fixes this problem for you?

**Comment by creshal** [comment]
I no longer get any useful error messages, but it still doesn't build.

[dkms output shows no error messages apart from "failed":](https://up.tao.at/-6a28ba4ee83cc839bfb6a1da6b088fd6/dkms-output)
```
[…]
config.status: executing libtool commands

Building module:
cleaning build area...
make -j8 KERNELRELEASE=4.9.0-6-amd64...........
Error!  Build of zlua.ko failed for: 4.9.0-6-amd64 (x86_64)
Consult the make.log in the build directory
/var/lib/dkms/zfs/0.7.8/build/ for more information.```

[make.log isn't helpful either.](https://up.tao.at/-d60e56a9036e3ee8eddd0828bf20ff99/build.log)

**Comment by behlendorf** [comment]
> Error!  Build of zlua.ko failed for: 4.9.0-6-amd64 (x86_64)

The `zlua.ko` module doesn't exist in the 0.7.8 release.  I'd suggest trying a clean install after making sure everything spl and zfs related has been removed from under `/var/lib/dkms/`.

**Comment by creshal** [comment]
Okay, patched dkms.mkconf the wrong way, properly patched it works.
