### ISSUE TITLE
"zpool scrub" hangs due to IO error

### ISSUE THREAD

**Issue by michaelletzgus** [zfsonlinux/zfs#736]
Hi!

Again debian wheezy, kernel 3.3.5.

> zpool create tank raidz /dev/loop1 /dev/loop2 /dev/loop3 

Then I "damaged"  one device:
> dd if=/dev/zero of=disk2 bs=1 count=1

Scrubbed it:
> zpool scrub tank
> zpool status
  pool: tank
 state: ONLINE
status: One or more devices could not be used because the label is missing or
        invalid.  Sufficient replicas exist for the pool to continue
        functioning in a degraded state.
action: Replace the device using 'zpool replace'.
   see: http://zfsonlinux.org/msg/ZFS-8000-4J
 scan: scrub repaired 0 in 0h0m with 0 errors on Thu May 10 21:04:09 2012
config:

        NAME        STATE     READ WRITE CKSUM
        tank        ONLINE       0     0     0
          raidz1-0  ONLINE       0     0     0
            loop1   ONLINE       0     0     0
            loop2   UNAVAIL      0     0     0  corrupted data
            loop3   ONLINE       0     0     0

Replaced the faulty device:

> zpool replace tank /dev/loop2 /dev/loop4
> zpool status
  pool: tank
 state: ONLINE
 scan: resilvered 55.5K in 0h0m with 0 errors on Thu May 10 21:05:17 2012
config:

        NAME        STATE     READ WRITE CKSUM
        tank        ONLINE       0     0     0
          raidz1-0  ONLINE       0     0     0
            loop1   ONLINE       0     0     0
            loop4   ONLINE       0     0     0
            loop3   ONLINE       0     0     0

Then I killed 2 devices:

> dd if=/dev/zero of=disk3 bs=1 count=1
> dd if=/dev/zero of=disk4 bs=1 count=1

But then:

> zpool scrub tank

...never returns.

Second terminal gives:

> zpool status
  pool: tank
 state: UNAVAIL
status: One or more devices are faulted in response to IO failures.
action: Make sure the affected devices are connected, then run 'zpool clear'.
   see: http://zfsonlinux.org/msg/ZFS-8000-HC
 scan: scrub in progress since Thu May 10 21:07:43 2012
    1 scanned out of 190K at 1/s, 54h2m to go
    0 repaired, 0.00% done
config:

        NAME        STATE     READ WRITE CKSUM
        tank        UNAVAIL      0     0     0  insufficient replicas
          raidz1-0  UNAVAIL      0     0     0  insufficient replicas
            loop1   ONLINE       0     0     0
            loop4   UNAVAIL      0     0     0  corrupted data
            loop3   UNAVAIL      0     0     0  corrupted data

It's now impossible to get rid of the pool:
> zpool destroy -f tank
cannot open 'tank': pool I/O is currently suspended

Neither replacing nor setting offline/online this faulty drives works.

**Comment by behlendorf** [comment]
Closing.
