### ISSUE TITLE
zfs 0.7 hangs receiving 16M block (reproducible)

### ISSUE THREAD

**Issue by fling-** [zfsonlinux/zfs#7365]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | gentoo
Distribution Version    | 17.1
Linux Kernel                 | 4.15.3
Architecture                 | amd64
ZFS Version                  | 0.7.6-1
SPL Version                  | 0.7.6-1

### Describe the problem you're observing
zfs hangs receiving 16M blocks when I'm trying to migrate data between pools
Looks like I'm stuck in the middle of migration as I can't send without `-L` because of #6224

### Describe how to reproduce the problem
Using https://gist.github.com/fling-/c66bf1e4a082b5cf9cd4d1106fe6e2bc

### Include any warning/errors/backtraces from the system logs
```
# zfs send -LRe studio/gentoo@old-pool | mbuffer -L -m 512M | zfs recv -u new-root/gentoo
in @  0.0 KiB/s, out @  0.0 KiB/s, 2248 MiB total, buffer 100% full^C
```

`recv` hangs in D state:
```
952 pts/11   D+     0:03 zfs recv -u new-root/gentoo
```

**Comment by zrav** [comment]
If it is acceptable to re-send all the data using <=128k blocks, as a workaround you could restart sending from scratch without -L. #6224 only occurs when you incrementally send small blocks with large blocks already present on the target.

**Comment by behlendorf** [comment]
@fling- thank you for the excellent reproducer, that definitely helped in reproducing the issue and identify the root cause.  I've opened #7404 with a proposed fix.
