### ISSUE TITLE
Minimum requirement for the Test Suite

### ISSUE THREAD

**Issue by RinCat** [zfsonlinux/zfs#7370]
Hi,

What is the minimum requirement for the Test Suite?
I had run zfs-tests.sh on a small VM with 2G RAM and 4 x 5GB DISKS, and got some FAIL and SKIP.
And durning the test, it broken my VM root ext4 filesystem by an unknown reason.

Syetem: Archlinux with linux 4.15.13 and zfs 0.7.7.

Last log before I/O error and system crash.

```
Test: /usr/share/zfs/zfs-tests/tests/functional/refreserv/cleanup (run as root) [00:00] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/rename_dirs/setup (run as root) [00:00] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/rename_dirs/rename_dirs_001_pos (run as root) [00:10] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/rename_dirs/cleanup (run as root) [00:00] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/replacement/setup (run as root) [00:01] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/replacement/replacement_001_pos (run as root) [02:26] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/replacement/replacement_002_pos (run as root) [00:53] [PASS]
```

Setted DISKS="sdb sdc sdd", but sda2 broken.

```
NAME   MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
sda      8:0    0   5G  0 disk 
├─sda1   8:1    0   1M  0 part 
└─sda2   8:2    0   5G  0 part /
sdb      8:16   0   5G  0 disk 
sdc      8:32   0   5G  0 disk 
sdd      8:48   0   5G  0 disk 
```

**Comment by behlendorf** [comment]
@RinCat 2G that should be more than enough.  At a minimum, 1G ofmemory and three 4G disks.  Here's what a test run of 0.7.7 should look like for your kernel:

http://build.zfsonlinux.org/builders/Fedora%20Rawhide%20x86_64%20%28TEST%29/builds/490/steps/shell_8/logs/tests

You might try instead running it with lookback devices.  By default the will be backed by sparce files in `/var/tmp` but you can use the `-d` option to put them somewhere else if needed.

**Comment by bunder2015** [comment]
I use a 30gb disk on my VM.  It's enough for the base OS (~4gb), the 3 disk files and the logs for a few full test runs.  I find the test run better with 4gb of memory rather than trying to go as minimal as possible, however throwing more cores at it didn't seem to help me much past 2 cores/threads.  It could be possible that my VM is bottlenecked by disk IO though.
