### ISSUE TITLE
selecting a slow ZFS compression throw too much CPU load to a HT system

### ISSUE THREAD

**Issue by RubenKelevra** [zfsonlinux/zfs#7376]
Hey guys,

you might already read on a different ticket, that I'm running ZFS with gzip-9 on a notebook. It's an older i3-2330M with HT. So there are just 2 physical cores but 4 virtual ones.

### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | ArchLinux
Distribution Version    | latest
Linux Kernel                 | 4.15.13-1-ARCH
Architecture                 | x64 (Intel)
ZFS Version                  | 0.7.7-1
SPL Version                  | 0.7.7-1

### Describe the problem you're observing
I observed a huge laggyness / jittering in the system performance while writing files to a zfs storage which is configured to gzip-9 compression. I don't want to complain here about slow performance - of course, it's slow to write on it. The issue is, it's utilizing 3 virtual cores to the maximum, leaving the system nearly no free time to actually respond to user inputs.

I wonder if we should switch to a more conservative physical core -1 metric instead of a virtual cores -1 for the amount of compression thread, leaving much more room for other tasks being performed on the system while writing data.

The load on my system rises from way below 1 to 9 just by moving stuff from one disk to a ZFS one with gzip-9 compression.

### Describe how to reproduce the problem
Use an old slow CPU with HT and write on a ZFS pool with gzip-9 compression. Try to use e.g. Chrome to browse the web or VLC to display a video while writing.

**Comment by kpande** [comment]
the solution is not to use slow compression algorithms on CPUs that cannot reasonably support it, not to gimp everyone else's system.

**Comment by DeHackEd** [comment]
Gimp your own system. Module parameter `zio_taskq_batch_pct`at the obvious risk of reduced capacity for the compression algorithm.

**Comment by RubenKelevra** [comment]
@kpande well, you don't get my the point here - it's not reasonable to overload a system, which clearly happens here. Three processes on two actually processors just don't work. Please reopen this bug report. :)
