### ISSUE TITLE
Cannot install grub bootloader on ubuntu

### ISSUE THREAD

**Issue by schmurfy** [zfsonlinux/zfs#7384]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Ubuntu
Distribution Version    | 16.04
Linux Kernel                 | 4.4.0-116-generic
Architecture                 | x86-64
ZFS Version                  | 0.6.5.6-0ubuntu16
SPL Version                  | 0.6.5.6-0ubuntu4

### Describe the problem you're observing
When following the zfs install guide for ubuntu 16.04 I cannot get past the bootloader install, when running `grub-install /dev/disk/by-id/scsi-<DISKID>` I get:

```
Installing for i386-pc platform.
grub-install: warning: this GPT partition label contains no BIOS Boot Partition; embedding won't be possible.
grub-install: error: filesystem `zfs' doesn't support blocklists.
```

I am not sure why I get the embedding warning since I am trying to install the bootloader on the whole disk and I have no idea why the second error means.
I already have an ubuntu-16.04 installed but I am trying to prepare a second empty disk for zfs so I followed this guide https://github.com/zfsonlinux/zfs/wiki/Ubuntu-16.04-Root-on-ZFS from step 2.

Here is my disk layout:
```
lsblk
NAME                    MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda                       8:0    1 931.5G  0 disk
├─sda1                    8:1    1   243M  0 part
├─sda2                    8:2    1     1K  0 part
└─sda5                    8:5    1 931.3G  0 part
  ├─VMHost17--vg-root   252:0    0 899.6G  0 lvm
  └─VMHost17--vg-swap_1 252:1    0  31.7G  0 lvm  [SWAP]
sdb                       8:16   1 931.5G  0 disk
├─sdb1                    8:17   1 931.5G  0 part
└─sdb9                    8:25   1     8M  0 part
sr0                      11:0    1  1024M  0 rom
``` 

I am not sure that's a bug but since I followed the guide here on a fresh ubuntu-16.04 opening an issue seems reasonnable.

This is really driving me crazy, getting a working linux install on zfs should be easier than that :/

Ps: I am trying to install with zfs on sdb

**Comment by kpande** [comment]
this is the zfs bug tracker, for bugs in zfs. you should use [the zfs-discuss mailing list](http://list.zfsonlinux.org) for support requests.

**Comment by ryao** [comment]
For those who have this problem, just do `sgdisk --new=2:48:2047 --typecode=2:EF02 --change-name=2:"BIOS boot partition" ${BLOCK_DEV}` to make a BIOS Boot Partition. It will make GRUB2 happy.

**Comment by pjgoodall** [comment]
> For those who have this problem, just do `sgdisk --new=2:48:2047 --typecode=2:EF02 --change-name=2:"BIOS boot partition" ${BLOCK_DEV}` to make a BIOS Boot Partition. It will make GRUB2 happy.

I had this problem when working with `Ubuntu 18.04.1 LTS`  in section **5.5a For legacy (MBR) booting, install GRUB to the MBR**. WHy not include in the documents?

**Comment by rlaager** [comment]
@pjgoodall Adding a BIOS boot partition has been in the instructions since basically forever.
