### ISSUE TITLE
Request: json output format

### ISSUE THREAD

**Issue by airtonix** [zfsonlinux/zfs#740]
at the moment all status outputs are formatted with the intention that it'll be read by a human.

Any chance of getting some machine consumable output data? 

This would ease the creation of user web or gui interfaces mashups by others.

just a thought.

**Comment by etopian** [comment]
+1

**Comment by behlendorf** [comment]
@etopian there's some active work to support this in #3483.  If you could provide feedback on the changes I'm sure it would be welcome.

**Comment by dreamcat4** [comment]
Hi. It seems the work moved over to PR #3938 ... seems like most of the works already been done it just needs someone else to come along and finish it off. The last leg, as it were.

**Comment by behlendorf** [comment]
Closing.  Support for JSON output for `zfs` commands was added using channel programs, see 7281.

**Comment by jersobh** [comment]
https://github.com/jersobh/zfs-resty
