### ISSUE TITLE
A kluge to make systemd unlock a LUKS device required by a non-root zpool

### ISSUE THREAD

**Issue by darrenfreeman** [zfsonlinux/zfs#7400]
I'm migrating a system over to zfs. At this stage I don't have root on zfs, but just about everything else is. And I believe it's a well known problem that there is no proper systemd generator for zfs, so if you are using zfs on LUKS, it's tricky to get systemd to unlock the device needed by zfs.

After much screwing around, I've come up with a line in `/etc/fstab` that will get the job done and have systemd unlock the needed device, so that zfs can import the pool containing `/home`, before the desktop environment auto-login which obviously would need that mounted. The pool is using only one vdev, called `crypt-rpool0`, properly described in `/etc/crypttab`. Although the pool is called `rpool`, it's not currently providing the root filesystem.

```
none    /rpool  zfs     defaults,nofail,x-systemd.requires=systemd-cryptsetup@crypt\x2drpool0.service   0       2
```

(I believe the `\x2d` above, is an escape sequence for the hyphen, in `crypt-rpool0`)

Well, this line is failing, so I'd appreciate some hints on what I'm doing wrong. But.. the kluge is at least working for me, because the pool is not using `mountpoint=legacy`. Here's the relevant stuff from `journalctl`:

```
Apr 07 04:16:33 host systemd[1]: Found device ST2000LM003_HN-M201RAD rpool0.
Apr 07 04:16:33 host systemd[1]: Starting Cryptography Setup for crypt-rpool0...
Apr 07 04:16:34 host systemd[1]: Started Cryptography Setup for crypt-rpool0.
Apr 07 04:16:34 host systemd[1]: systemd-cryptsetup@crypt\x2drpool0.service: Unit is bound to inactive unit dev-mapper-crypt\x2drpool0.device. Stopping, too.
Apr 07 04:16:34 host systemd[1]: systemd-cryptsetup@crypt\x2drpool0.service: Failed to enqueue stop job, ignoring: Transaction is destructive.
Apr 07 04:16:34 host systemd[1]: Mounting /rpool...
Apr 07 04:16:36 host systemd[1]: rpool.mount: Mount process exited, code=exited status=1
Apr 07 04:16:36 host systemd[1]: Failed to mount /rpool.
Apr 07 04:16:36 host systemd[1]: rpool.mount: Unit entered failed state.
```

I'm really happy that the system boots and there are basically no symptoms to the above failure. But putting this issue here because others will be searching for this solution, and maybe it can be improved.

**Comment by kpande** [comment]
please use [the zfs-discuss mailing list](http://list.zfsonlinux.org) for this issue since it's not a bug with ZFS. you can link your ML thread here to redirect users to its discussion. thanks darren!
