### ISSUE TITLE
Feature Request: MIME-type aware compression decision for whole files

### ISSUE THREAD

**Issue by RubenKelevra** [zfsonlinux/zfs#7403]
Currently, LZ4-compression uses a fast bail-out when it detects that a recordsize-block isn't compressible. GZIP invest a huge amount of CPU power, to do the same (when it's even bailing out early - not sure if this is implemented).

Adding the ability to detect if a block is worth compression is usually not necessary, we all do this consideration naturally if we want to send an email. Nobody would really consider investing an hour of CPU time compressing JPGs or a Video file with LZMA2 - because it's never worth it.

Why don't we just rely on the MIME type of a file, to judge, if ZFS should try to compress a file in the first place? This information should be nearly always available (except on sparse files not containing the head of the file), and it's a very fast decision:

file -i random_filename.mp4 gives me _video/mp4_ in 47ms real and 4ms user and 4ms sys for a spinning disk, running ZFS while currently compiling a Linux kernel on this volume. While the recordsize is up to 1M on this pool.

We can easily provide a standard-blacklist of MIME-types (for archive formats, audio and video files and similar) and give the users the ability to just add additionally MIME-types if they have custom needs.

This feature request is a successor of https://github.com/zfsonlinux/zfs/issues/7373

**Comment by kpande** [comment]
this is a terrible idea, see #5928 for a better solution

**Comment by RubenKelevra** [comment]
@kpande might you explain your opinion?

**Comment by DeHackEd** [comment]
Kernel drivers cannot make a decision at the "MIME type" level. Running the user application "file" on every thing being written is absurd.

**Comment by behlendorf** [comment]
@RubenKelevra on the surface I can see why this sounds like an appealing idea.  It makes good sense from the perspective of a user space application.  Unfortunately, the problem looks a little different from a kernel space driver which is expected to as efficiently as possible handle arbitrary blobs of data.

Saso Kiselkov gave a talk a few years ago at an OpenZFS development summit discussing this issue I'm sure you'd find it interesting.  His proposed solution isn't too different that yours, but instead of checking the MIME type to determine if something incompressible we track some per-file compression statistics.  This has the advantage of being completely generic and would let us decide beforehand if we're likely to benefit from compression.  Now we just need to implement it, or something like it!

http://open-zfs.org/w/images/4/4d/Compression-Saso_Kiselkov.pdf
http://www.youtube.com/watch?v=TZF92taa_us

**Comment by kpande** [comment]
no, looking at the MIME type is a patently bad idea, auto compression referenced above is a much nicer solution.

**Comment by RubenKelevra** [comment]
@kpande

well, you already wrote your opinion. Then you closed this ticket, refused to respond to my question why you think that way and blocked all further discussion of this topic. 

I don't like your attitude, I don't think an open discussion of ideas hurt this project and if you do, you might be wrong. Censorship of opinions you don't like should have no place in an open source project. Get your frustrations somewhere else sorted out, not here.

That said, I understand, you dislike the idea to call an external program to decide if a block should be compressed or not, but that's not what I wanted to suggest here.

So some facts:
-We know that File-Magic works, we use it every day on OS X and Unix to decide how to open a file.
-We know that most files I've listed are incompressible.
-We know that File-Magic is a very good indicator what type of file we just be locking at.
-In other high performance/low latency scenario when a fast decision about the compressibility is needed, the application use File-Magic to decide with a low latency if those CPU-cycles trying to compress the file would be wasted or not.

Furthermore, I like the auto compression idea, but it's a solution for not-overloading a system with efforts of compression.

Applying just auto compression to a something like a /home folder with mixed content might lead to not compressed compressible files while other files might not be compressible but they've been selected to try to compress them.

So adding the ability to predict if an compression is worth trying increase the chance of selecting actually compressible blocks which would enhance the compression ratio while keeping the CPU usage at the same level.

**Comment by kpande** [comment]
it's not just calling a user program, the entire concept of deciding how to compress a whole file that might not even be written in the way you're imagining. what if the magic is written at the end? what if the file type changes? what if the magic is wrong? what if it's overwritten in place? working on the block level is a much smarter way to get things accomplished, as it's then more generally implemented and would even work for ZVOL.
