### ISSUE TITLE
a6cc97566c54255c98612c801f2c9d9be2d0e8f8 may have broken in-kernel compilation

### ISSUE THREAD

**Issue by akorn** [zfsonlinux/zfs#7407]
After `copy-builtin` and enabling zfs support in the kernel config, building the kernel fails with:

```
  CC [M]  fs/zfs/zfs/zfs_ioctl.o
fs/zfs/zfs/zfs_ioctl.c:6950:12: error: ‘ZFS_MINOR’ undeclared here (not in a function); did you mean ‘ZFS_OWNER’?
  .minor  = ZFS_MINOR,
            ^~~~~~~~~
            ZFS_OWNER
scripts/Makefile.build:293: recipe for target 'fs/zfs/zfs/zfs_ioctl.o' failed
make[3]: *** [fs/zfs/zfs/zfs_ioctl.o] Error 1
scripts/Makefile.build:544: recipe for target 'fs/zfs/zfs' failed
make[2]: *** [fs/zfs/zfs] Error 2
scripts/Makefile.build:544: recipe for target 'fs/zfs' failed
make[1]: *** [fs/zfs] Error 2
Makefile:1006: recipe for target 'fs' failed
make: *** [fs] Error 2
```

This is with 4.9.92, but I don't suppose it matters.

I suspect this is fallout from a6cc97566c54255c98612c801f2c9d9be2d0e8f8.

**Comment by bunder2015** [comment]
Please do not delete the issue template when filing new issues, we need that information.  We have no idea which distro you are using for example.

**Comment by akorn** [comment]
I'm using Devuan ceres, but I can't imagine it to be relevant for this build issue. Had I been in any doubt, I would have left the template info in, but in this case I think it would just have been useless clutter.

Nonetheless, I will leave it in next time.

**Comment by loli10K** [comment]
FWIW i'm not seeing this issue on my system building the current master (6c9af9e8f4a2901c9a5f205876b67dcc3216cbd8):

```
root@linux:~# grep zfs /proc/modules 
root@linux:~# cat /sys/module/zfs/version 
0.7.0-411_g6c9af9e
root@linux:~# ls -l /dev/zfs
crw------- 1 root root 10, 249 Apr  1 08:44 /dev/zfs
root@linux:~# uname -r
4.12.0-rc2+
root@linux:~# cat /etc/debian_version 
8.0
root@linux:~# 
```

Even the Kernel Built-in builder seems to be happy with 5c27ec10889d3d8f12d59fb7e5068ed2d8697c85

http://build.zfsonlinux.org/builders/Kernel.org%20Built-in%20x86_64%20(BUILD)/builds/19094/

**Comment by akorn** [comment]
Hm. Can't reproduce it anymore either.

Sorry about the noise.
