### ISSUE TITLE
web links to fixed  spl issues are broken in zfs release notes

### ISSUE THREAD

**Issue by ak100** [zfsonlinux/zfs#7419]
Web links for individual SPL issues are broken on zfs release log webpage starting with release 0.7.x . In older release notes the full url was used to refer spl issue.  Apparently github assumes the issue linked by its ID is in the same (current) repository.

Example:
```
zfs-0.7.7
SPL
 Fix spl-kmod builds when using rpm >= 4.14 #691
```

The issue # 691 links to the issue #691 in zfs repository where it shall link to the issue [#691](https://github.com/zfsonlinux/spl/pull/691) in spl repository:
```
current:
   https://github.com/zfsonlinux/zfs/pull/691
correct:
   https://github.com/zfsonlinux/spl/pull/691
```

Ways to fix: use url in form: 
zfsonlinux/spl#691 or [#691](zfsonlinux/spl#691) or [spl #691](zfsonlinux/spl#691)
```
zfsonlinux/spl#691
[#691](zfsonlinux/spl#691)
[spl #691](zfsonlinux/spl#691)
```

**Comment by ak100** [comment]
I stand corrected :
Ways to fix - use full url in form:
> zfsonlinux/spl#691

Two other looked OK in preview but got rewritten to different URL when the issue was posted.

**Comment by kpande** [comment]
it's generating them from `git log --oneline` and he would have to edit them all manually or do it correctly in the commit message, which isn't overly important. the information is still there.

**Comment by behlendorf** [comment]
Manually fixed for the last few releases.
