### ISSUE TITLE
Multi mount support

### ISSUE THREAD

**Issue by behlendorf** [zfsonlinux/zfs#745]
Multi mount protection needs to be implemented for ZFS to allow safe pool failover.  The idea is that regardless of the hostid you should be able to safely determine if the pool is in use on another node.  If it is then importing the pool should be prohibited, if it's not then you are allowed to import the pool regardless of the host id.  

Lustre's ldiskfs filesystem has implemented something similar to this for a while now.  We should be able to do something like this  for zfs by checking the on-disk txg number.  It will be incremented every few seconds when the pool is being written too.  The tricky part is  that when the pool is idle we can't count on this being updated.  We may need to add a mmp property to the pool to force a periodic update when the zpool is deployed in a failover environment.

http://wiki.lustre.org/manual/LustreManual20_HTML/ManagingFailover.html

**Comment by adilger** [comment]
One thing I just noticed is missing in Ricardo's design document at http://permalink.gmane.org/gmane.os.illumos.zfs/302 is an **mmp_time** field in mmp_struct.  This is in the "nice to have" fields and would not affect the protocol, but it has been useful in ldiskfs to be able to print to the console "MMP failure info: last update time: %llu, last update node: %s, last update device: %s\n".

**Comment by ofaaland** [comment]
PR https://github.com/zfsonlinux/zfs/pull/5821 contains the most recent revision of the design document and some additional supporting docs.
