### ISSUE TITLE
zfs-kmod-repo for el 7.5 (soon av. centos 7.5.1804)

### ISSUE THREAD

**Issue by hoonetorg** [zfsonlinux/zfs#7472]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | el
Distribution Version    | 7.5
Linux Kernel                 | 3.10.0-862
Architecture                 | x86_64
ZFS Version                  | 0.7.8-1
SPL Version                  | 0.7.8-1

### Describe the problem you're observing
There is no zfs-kmod repo for el7.5-kmod packages.
AFAIU repomd.xml for it would be there: http://download.zfsonlinux.org/epel/7.5/kmod/x86_64/repodata/repomd.xml
(analog repomd.xml for 7.4 http://download.zfsonlinux.org/epel/7.4/kmod/x86_64/repodata/repomd.xml exists)

**Comment by behlendorf** [comment]
Closing.  We'll provide packages for 7.5 when 0.7.9 is tagged.  There were some compatibility issues 9464b9591ea5cd61a4d6ef8e29c4597b48d16a77 which needed to be addressed first.

**Comment by hoonetorg** [comment]
@behlendorf thx for this info.
