### ISSUE TITLE
Recoverable checksum errors on a single drive pool?

### ISSUE THREAD

**Issue by markdesouza** [zfsonlinux/zfs#7488]
### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Debian
Distribution Version    |  Stretch (v9.4)
Linux Kernel                 |  4.9.0-5
Architecture                 |  amd64
ZFS Version                  |  0.7.6-1~bpo9+1
SPL Version                  |  0.7.6-1~bpo9+1

### Describe the problem you're observing
I have a non-replicated zpool I use for testing. Hardware is reasonably new and fault free (as per smart report), using ecc mem, hosted in a datacenter (ie no power failures) etc. I received the error below and believe it is incorrect or at the very least poorly worded.

1) Given I believe the hardware to be good, I am suspicious of the validity of the error reported
2) If there was an error, the message is confusing. 
- It states there was an unrecoverable error, but applications were unaffected. I assume this means that ZFS recovered the data and self-healed. But how? Given this is not a replicated array, any error should be unrecoverable. (also the dataset has copies=1)
3) Conversely if there was actual hard errors that were not able to be healed, then the affected files should be listed
4) The link http://zfsonlinux.org/msg/ZFS-8000-9P states "A device has experienced uncorrectable errors in a replicated configuration", but this is not a replicated configuration

### Describe how to reproduce the problem
N/A

### Include any warning/errors/backtraces from the system logs
  pool: chen-rpool
 state: ONLINE
status: One or more devices has experienced an unrecoverable error.  An
	attempt was made to correct the error.  Applications are unaffected.
action: Determine if the device needs to be replaced, and clear the errors
	using 'zpool clear' or replace the device with 'zpool replace'.
   see: http://zfsonlinux.org/msg/ZFS-8000-9P
  scan: scrub repaired 3K in 0h0m with 0 errors on Tue May  1 02:30:14 2018
config:

	NAME                                            STATE     READ WRITE CKSUM
	chen-rpool                                      ONLINE       0     0     0
	  scsi-36000c29d1eb136652fc9462492d9ab0b-part2  ONLINE       0     0     1

errors: No known data errors

**Comment by phreaker0** [comment]
I guess a metadata block was affected which by default is saved two times, therefore the error could be repaired even on a single disk pool. The relevant property is "redundant_metadata" with a standard value of "all".

**Comment by markdesouza** [comment]
ok so I can confirm redundant_metadata is set to all, however just to be sure is there a way to see from scrub directly what blocks (and their use ie filename) were affected

**Comment by phreaker0** [comment]
As far as I know, affected files are only listed in the zpool status -v output if there were unrecoverable checksum errors.

**Comment by gmelikov** [comment]
Please use mailing lists for support questions, closed.
