### ISSUE TITLE
DOWN'I

### ISSUE THREAD

**Issue by flerko** [zfsonlinux/zfs#7497]
Вы чо долбаебы, ебанулись? мускл нихуя не робит, фиксите (фиксики) нахуй

**Comment by mschilli87** [comment]
@flerko: I'm not sure if [google translate changes the tone of your issue](https://translate.google.com/#auto/en/%D0%92%D1%8B%20%D1%87%D0%BE%20%D0%B4%D0%BE%D0%BB%D0%B1%D0%B0%D0%B5%D0%B1%D1%8B%2C%20%D0%B5%D0%B1%D0%B0%D0%BD%D1%83%D0%BB%D0%B8%D1%81%D1%8C%3F%20%D0%BC%D1%83%D1%81%D0%BA%D0%BB%20%D0%BD%D0%B8%D1%85%D1%83%D1%8F%20%D0%BD%D0%B5%20%D1%80%D0%BE%D0%B1%D0%B8%D1%82%2C%20%D1%84%D0%B8%D0%BA%D1%81%D0%B8%D1%82%D0%B5%20(%D1%84%D0%B8%D0%BA%D1%81%D0%B8%D0%BA%D0%B8)%20%D0%BD%D0%B0%D1%85%D1%83%D0%B9) but like this it will probably be hard to help you. [[переведите]](https://translate.google.com/#en/ru/I'm%20not%20sure%20if%20google%20translate%20changes%20the%20tone%20of%20your%20issue%20but%20like%20this%20it%20will%20probably%20be%20hard%20to%20help%20you.)

[Не могли бы вы попытаться перефразировать свой вопрос на английском языке (вы могли бы попробовать онлайн-переводчика)?](https://translate.google.com/#en/ru/Could%20you%20please%20try%20to%20rephrase%20your%20question%20in%20English%20(you%20could%20try%20an%20online%20translator)%3F)

**Comment by gmelikov** [comment]
@flerko your issue style is unacceptable, and you must use english. Closed as non constructive. Next time we have to ban you.

@flerko стиль вашего issue недопустим, к тому же русский не является предпочтительным языком для общения в данном баг трекере. Issue закрыт как не конструктивный. В следующий раз нам придётся вас забанить.
