### ISSUE TITLE
Use scatter-gather lists for ARC buffers

### ISSUE THREAD

**Issue by behlendorf** [zfsonlinux/zfs#75]
This is a big change but we really need to consider updating the ZFS code to use scatter-gather lists for the ARC buffers instead of vmalloc'ed memory.  Using a vmalloc'ed buffer is the way it's done on OpenSolaris but it's less problematic there because they have a more full featured virtual memory management system in the kernel.  By design the Linux kernel's VM is primitive for performance reasons.  The only reason things are working reasonable well today is that I've implemented a fairly decent virtual slab in the SPL.  This is good but it goes against the grain of what should be done and it does cause some problems, such as:

1) Deadlocks.  Because of the way the zio pipeline in designed in ZFS we must be careful to avoid triggering the synchronous memory reclaim path.  If one of the zio threads does enter reclaim then it may deadlock on itself by trying to flush dirty pages from say a zvol.  This is avoided in most instances by clearing GFP_FS but we can't clear this flag for vmalloc() calls.  Unfortunately, we may be forced to vmalloc() a new slab in the zio pipeline for certain workloads such as compression and this we risk deadlocking.  Moving to scatter-gather lists would allow us to eliminate this __vmalloc() and potential deadlock.

2) Avoid serializing on the single Linux VM lock.  Because the Linux VM is designed to be lightly used all changes to the virtual address space are serialized through a single lock.  The SPL slab does go through some effort to minimizing this impact by allocating slabs of objects but clearly there are scaling concerns here.

3) VM overhead.  In addition to the lock contention there is overhead involved in locating suitable virtual addresses and setting up the mapping from virtual to physical pages.  For a CPU hungry filesystem and overhead we can eliminate is worthwhile.

4) 32-bit arch support.  This biggest issue with supporting 32-bit arches is they have a very small virtual address range, usually only 100's of MB.  By moving all ARC data buffers to scatter gather lists we avoid having to use this limited address range.  Instead all data pages can simply reside is the standard address range just like with all other Linux filesystems.

**Comment by kernelOfTruth** [comment]
and #3441

**Comment by behlendorf** [comment]
Merged as:

7657def Introduce ARC Buffer Data (ABD)
