### ISSUE TITLE
Test suite: some tests are hardcoded to use /tmp 

### ISSUE THREAD

**Issue by bunder2015** [zfsonlinux/zfs#7507]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | n/a
Distribution Version    | n/a
Linux Kernel                 | n/a
Architecture                 | n/a
ZFS Version                  | master
SPL Version                  | master

### Describe the problem you're observing
I meant to post this a couple weeks ago but got sidetracked.  Several test cases appear to be hardcoded to use /tmp for storage, the files left behind aren't huge in size and get cleaned up on reboot with most distros, but these should be consolidated to $TEST_BASE_DIR.  I will try to work on these as time permits in the coming weeks unless someone gets to it before I manage to.  Feel free to assign to me.

~~snapshot_002_pos~~ #7508 
~~enospc_002_pos~~ #7515
~~history~~ #7600 
xattr_003/004/007/008
~~delegate~~ #7778 
several cli_user and cli_root tests
~~privilege~~ #7803
nopwrite_recsize
~~events~~ #7805 
~~acl~~ #7777 
~~largest_pool~~ #7804
~~libtest~~ #7614
mv_files (probably can't be fixed without rewriting the test)
~~inuse_004~~ #7775
~~projectquota_002~~ #7774 
~~zvol_swap~~ #7839 
~~zpool_checkpoint~~ #7840

**Comment by ahrens** [comment]
@jwk404 FYI

**Comment by bunder2015** [comment]
I'm hoping to get back to these this weekend or next week, been caught up with work and some other things, I'm just doing a quick test run post-spl-merge and if all goes well I can be back to working on these.

**Comment by bunder2015** [comment]
Closing for now, thanks for finishing these off.  When I get my vm working again I'll see if we have any more stray files laying around after tests.
