### ISSUE TITLE
'zfs allow -c' doesn't add a create time permission as documentation claims it should.

### ISSUE THREAD

**Issue by jmonsted** [zfsonlinux/zfs#7519]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Raspbian
Distribution Version    | Stretch 2018-04-18
Linux Kernel                 | 4.14.34+
Architecture                 | armv6l
ZFS Version                  | 0.7.8
SPL Version                  | 0.7.8

The same issue has been spotted on FreeBSD 11.1.

### Describe the problem you're observing
I'm trying to allow "create time permissions", but the 'zfs allow -c' syntax isn't working. Instead, i get an empty permission set. I suspect the -s and -c options are getting confused somehow.

### Describe how to reproduce the problem
```
root@:~# zfs allow tank
root@:~# zfs allow -c destroy tank
root@:~# zfs allow tank
---- Permissions on tank----------------------------------------
Permission sets:
        destroy
root@:~# 
```

I expected to see:
```
---- Permissions on tank----------------------------------------
Create time permissions:
        destroy
```

### Include any warning/errors/backtraces from the system logs
No logs.

**Comment by ahrens** [comment]
Looks the same on illumos:
```
$ sudo zfs allow -c destroy rpool
$ zfs allow rpool
---- Permissions on rpool --------------------------------------------
Permission sets:
        destroy
```

**Comment by jmonsted** [comment]
Is there a workaround to let a user destroy its own snapshots, but nothing else?
