### ISSUE TITLE
RHEL 404 Errors Installing 7.5 kmod Version

### ISSUE THREAD

**Issue by mickwilli** [zfsonlinux/zfs#7535]
When attempting to install the RHEL 7.5 kmod tracking version of zfs, the following errors are received:

`zfs-0.7.9-1.el7_3.x86_64.rpm   FAILED
http://download.zfsonlinux.org/epel/7.5/kmod/x86_64/zfs-0.7.9-1.el7_3.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found                                                                                     ]  0.0 B/s |    0 B  --:--:-- ETA

kmod-zfs-0.7.9-1.el7_3.x86_64. FAILED
http://download.zfsonlinux.org/epel/7.5/kmod/x86_64/kmod-zfs-0.7.9-1.el7_3.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found                                                                                ]  0.0 B/s |    0 B  --:--:-- ETA
Trying other mirror.
`

It appears that yum is hitting a 404 error downloading the rpm packages required to install.

**Comment by juxi500** [comment]
Same here

**Comment by juxi500** [comment]
I found out what is the problem. yum is looking for these packages on wrong links.

Here are correct links, maybe someone will find it useful:

http://download.zfsonlinux.org/epel/7.5/kmod/x86_64/kmod-zfs-0.7.9-1.el7_5.x86_64.rpm
http://download.zfsonlinux.org/epel/7.5/kmod/x86_64/kmod-spl-0.7.9-1.el7_5.x86_64.rpm
http://download.zfsonlinux.org/epel/7.5/kmod/x86_64/libnvpair1-0.7.9-1.el7_5.x86_64.rpm
http://download.zfsonlinux.org/epel/7.5/kmod/x86_64/libuutil1-0.7.9-1.el7_5.x86_64.rpm
http://download.zfsonlinux.org/epel/7.5/kmod/x86_64/libzfs2-0.7.9-1.el7_5.x86_64.rpm
http://download.zfsonlinux.org/epel/7.5/kmod/x86_64/libzpool2-0.7.9-1.el7_5.x86_64.rpm
http://download.zfsonlinux.org/epel/7.5/kmod/x86_64/spl-0.7.9-1.el7_5.x86_64.rpm
http://download.zfsonlinux.org/epel/7.5/kmod/x86_64/zfs-0.7.9-1.el7_5.x86_64.rpm

**Comment by juxi500** [comment]
Side note: you can use this links straight in yum.

For example:

yum install http://download.zfsonlinux.org/epel/7.5/kmod/x86_64/kmod-zfs-0.7.9-1.el7_5.x86_64.rpm

**Comment by mickwilli** [comment]
Thanks @juxi500, that info is really helpful and I've now found the issue.

It turns out that Yum was still working on a cached copy of the yum repository, so it was trying to install the 7.3 version (since that's what it had last) rather than re-downloading the metadata and getting the new 7.5 packages and their associated file names. A "sudo yum clean metadata" should dispatch with that problem, although knowing what I know now, I'd recommend following the full procedure on the RHEL/CentOS page under the heading "RHEL/CentOS 7.x kmod package upgrade" as that way you can be sure to remove the old versions of everything and install the correct version (just be sure to change the installation url for the zfs-release yum repo to the one you need).

**Comment by tonyhutter** [comment]
Make sure you have the [zfs-release.el7_5.noarch.rpm](http://download.zfsonlinux.org/epel/zfs-release.el7_5.noarch.rpm) package installed if you're using RHEL 7.5.

**Comment by juxi500** [comment]
Thank you very much, it works now, I think we can close this issue :)
