### ISSUE TITLE
LMDB random COW writes, very badly affecting latency of writes from all processes and datasets

### ISSUE THREAD

**Issue by baryluk** [zfsonlinux/zfs#7543]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Debian GNU/Linux
Distribution Version	| sid/unstable
Linux Kernel	| 4.16.5-1 (`linux-image-4.16.0-1-amd64` version 4.16.5-1)
Architecture	| amd64
ZFS Version	| 0.7.0-459_gbc8a6a60e
SPL Version	| 0.7.0-34_g73d08ac

### Describe the problem you're observing

Setup:

* amd64 arch, i7-3930K @ 4.2GHz (Sandy Bridge, 6 cores, 12 hyperthreads).
* 32GB RAM, but mostly consumed by user space program.
* No ZFS dedup or encryption.
* 2 pools, the pool in question has one top level vdev with a mirror on top of two high performance Samsung SM961/PM961 1TB NVMe drive (PCIe 3.0) behind LUKS-based encryption:

`blkid | grep nvme`:
```text
/dev/nvme1n1p1: UUID="93b5cd4f-e7bf-4839-9b71-54b66fa6552f" TYPE="crypto_LUKS" PARTLABEL="wctank4-disk2-crypt" PARTUUID="32da2466-ccc9-4e92-bb73-2fce782542b4"
/dev/nvme0n1p1: UUID="81d4d022-7f58-408b-898e-5b8c7e8c5d8c" TYPE="crypto_LUKS" PARTLABEL="wctank4-disk1-crypt" PARTUUID="19a59399-38bc-420c-8819-161f431d4c0e"
/dev/nvme1n1: PTUUID="24bcd851-05c3-47da-a532-87181e40cd1d" PTTYPE="gpt"
/dev/nvme0n1: PTUUID="fb269785-9bfe-4e5e-91b7-ff509c3802eb" PTTYPE="gpt"
```

From `/etc/crypttab`:
```text
wctank4_disk1 UUID=81d4d022-7f58-408b-898e-5b8c7e8c5d8c /root/wctank1-keyfile luks,discard
wctank4_disk2 UUID=93b5cd4f-e7bf-4839-9b71-54b66fa6552f /root/wctank1-keyfile luks,discard
```

`LC_ALL=C free -h`:
```text
              total        used        free      shared  buff/cache   available
Mem:           31Gi        20Gi       6.8Gi       615Mi       4.5Gi        10Gi
Swap:         7.4Gi       746Mi       6.7Gi
#
```

`zpool status wctank4`:
```text
  pool: wctank4
 state: ONLINE
  scan: scrub repaired 0B in 0 days 00:32:01 with 0 errors on Wed Nov 29 16:10:42 2017
config:

	NAME               STATE     READ WRITE CKSUM
	wctank4            ONLINE       0     0     0
	  mirror-0         ONLINE       0     0     0
	    wctank4_disk1  ONLINE       0     0     0
	    wctank4_disk2  ONLINE       0     0     0

errors: No known data errors
```

`zpool get all wctank4`:
```text
NAME     PROPERTY                       VALUE                          SOURCE
wctank4  size                           952G                           -
wctank4  capacity                       92%                            -
wctank4  altroot                        -                              default
wctank4  health                         ONLINE                         -
wctank4  guid                           13946432891582609021           -
wctank4  version                        -                              default
wctank4  bootfs                         -                              default
wctank4  delegation                     on                             default
wctank4  autoreplace                    off                            default
wctank4  cachefile                      -                              default
wctank4  failmode                       wait                           default
wctank4  listsnapshots                  off                            default
wctank4  autoexpand                     off                            default
wctank4  dedupditto                     0                              default
wctank4  dedupratio                     1.00x                          -
wctank4  free                           66,7G                          -
wctank4  allocated                      885G                           -
wctank4  readonly                       off                            -
wctank4  ashift                         0                              default
wctank4  comment                        -                              default
wctank4  expandsize                     -                              -
wctank4  freeing                        0                              -
wctank4  fragmentation                  69%                            -
wctank4  leaked                         0                              -
wctank4  multihost                      off                            default
wctank4  feature@async_destroy          enabled                        local
wctank4  feature@empty_bpobj            active                         local
wctank4  feature@lz4_compress           active                         local
wctank4  feature@multi_vdev_crash_dump  enabled                        local
wctank4  feature@spacemap_histogram     active                         local
wctank4  feature@enabled_txg            active                         local
wctank4  feature@hole_birth             active                         local
wctank4  feature@extensible_dataset     active                         local
wctank4  feature@embedded_data          active                         local
wctank4  feature@bookmarks              enabled                        local
wctank4  feature@filesystem_limits      enabled                        local
wctank4  feature@large_blocks           enabled                        local
wctank4  feature@large_dnode            enabled                        local
wctank4  feature@sha512                 enabled                        local
wctank4  feature@skein                  enabled                        local
wctank4  feature@edonr                  enabled                        local
wctank4  feature@userobj_accounting     active                         local
wctank4  feature@encryption             enabled                        local
wctank4  feature@project_quota          active                         local
wctank4  feature@device_removal         enabled                        local
wctank4  feature@obsolete_counts        enabled                        local
```

(another pool wctank1 have similar setup, with 2 different SATA device, and is not used for anything during the same time).

Relevant properties of data set in question: (compression=off, sha256, everything else standard, atime=off, relatime=on).

```text
# zfs get recordsize,checksum,compression,copies,primarycache,secondarycache,logbias,dedup,sync,dnodesize,atime,relatime wctank4/home/baryluk/.bitmonero
NAME                             PROPERTY        VALUE           SOURCE
wctank4/home/baryluk/.bitmonero  recordsize      128K            default
wctank4/home/baryluk/.bitmonero  checksum        sha256          inherited from wctank4
wctank4/home/baryluk/.bitmonero  compression     off             local
wctank4/home/baryluk/.bitmonero  copies          1               default
wctank4/home/baryluk/.bitmonero  primarycache    all             default
wctank4/home/baryluk/.bitmonero  secondarycache  all             default
wctank4/home/baryluk/.bitmonero  logbias         latency         default
wctank4/home/baryluk/.bitmonero  dedup           off             default
wctank4/home/baryluk/.bitmonero  sync            standard        default
wctank4/home/baryluk/.bitmonero  dnodesize       legacy          default
wctank4/home/baryluk/.bitmonero  atime           off             inherited from wctank4
wctank4/home/baryluk/.bitmonero  relatime        on              inherited from wctank4
```

When running `monero-gui-linux-x64-v0.12.0.0.tar.bz2` ( https://github.com/monero-project/monero-gui/releases/tag/v0.12.0.0 ) and monerod binary (C++ application AFAIK) synchronizing Monero blockchain at high rate (good CPU, and 1Gbps Internet connectivity), that is stored in LMDB based database, entire system experiences periodic (about every 30 seconds) temporary (3 to 8 seconds) stalls in all write disk IO on this pool, including web browser caches, that affects almost all activity in the browser (even scrolling, text input from keyboard, focus changes, network IO, etc), and sometimes even my window manager window switching ability. Only write IO is stalled. I.e. I can run ` find -type f  -exec 'md5sum' {} +` and it sees full speed progress even during the stall.

Example of synthetic write stall (granted with some additional open/append/close calls) from another process in different dataset on the same pool (stall do not happen if I write/append to a file on different pool or different filesystem completely). From time to time this method will not detect stall in my webrbrowser or will not happen even when `strace` is showing very big `pwrite64` time.

```
$ i=0; while `LC_ALL=C sleep 0.1`; do i=$((i+1)); echo $i $(date '+%s.%N'); echo bzium >> ~/x.tmp.testing; done
1 1526423253.584753263
2 1526423255.165533865
3 1526423255.271711197
4 1526423255.384903835
...
111 1526423266.491869801
112 1526423266.595338495
113 1526423266.699487939
114 1526423266.803443127  # <---- 5 seconds wait
115 1526423271.202686021
116 1526423271.309274630
...
131 1526423272.872521702
132 1526423272.977262514
^C
```

10 second average io (from `iostat`) is about 800 tps to each device, 5MB/s read, 100MB/s write, with peaks up to 1200 tps and 120MB/s. During stalls the nvme drives will still see writes coming in, but with smaller bandwidth and iops, and tendency to oscillate heavily (between 10MB and 150MB/s).

`iostat 1`:
```text
Device             tps    kB_read/s    kB_wrtn/s    kB_read    kB_wrtn
nvme1n1         797,00     13568,00     95616,00      13568      95616
nvme0n1         475,00      1024,00     95616,00       1024      95616
```

`vmstat 1`:
```text
 0  4 755992 8597040 483252 4499728    0    0 15744 134816 6245 63076  3  9 69 19  0
 4  4 755992 8574968 483252 4499820    0    0 16912 170926 6241 60874  3  9 67 20  0
 0  1 755992 8566256 483252 4501260    0    0 15365 180641 8613 76867  5 12 68 16  0
 7  2 755992 8592516 483260 4501156    0    0 21012 162756 6270 48849  4 14 67 14  0
 0  4 755992 8572508 483260 4501240    0    0 16768 127579 5600 48806  6 10 72 12  0
 0  4 755992 8526084 483260 4501300    0    0 14341 218122 6365 58207  4 11 64 21  0
 2  3 755992 8524592 483260 4501340    0    0 11413 222546 6902 60677  5 14 62 19  0
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 1  1 755992 8452112 483264 4504308    4    0  8708 196951 6855 59834  5 10 63 22  0
 2  0 755992 8435624 483272 4500772    0    0 22912 125381 5067 37526  4 10 74 12  0
 3  3 755992 8471900 483272 4500784    0    0 20368 184189 5569 40892  3 15 67 15  0
 1  3 755992 8437124 483272 4500572    0    0 15877 200454 5771 46143  3 10 68 19  0
11  1 755992 8441184 483272 4500740    0    0  6405 185959 6188 76622  3 20 62 15  0
 0  4 755992 8298876 483272 4501356    0    0 10624 237824 5668 48503  3  8 67 22  0

```

`zpool iostat 1 -v`:
```text
...
                     capacity     operations     bandwidth 
pool               alloc   free   read  write   read  write
-----------------  -----  -----  -----  -----  -----  -----
wctank1             362G  46,3G      0      0      0      0
  mirror            362G  46,3G      0      0      0      0
    sda4_crypt         -      -      0      0      0      0
    sdb4_crypt         -      -      0      0      0      0
-----------------  -----  -----  -----  -----  -----  -----
wctank4             880G  72,3G     44    980  5,60M   206M
  mirror            880G  72,3G     44    980  5,60M   206M
    wctank4_disk1      -      -     33    605  4,23M   105M
    wctank4_disk2      -      -     10    375  1,37M   101M
-----------------  -----  -----  -----  -----  -----  -----
^C
```

Running `strace -tt -T -f -e trace=write,sync,fsync,fdatasync,pwrite64 -p $(pidof monerod)`, shows large number of `pwrite64` calls (each using 4096 bytes buffers), from single thread to single specific file descriptor. Offsets are kind of growing, but are not exactly spaced by 4096 or exactly sequential (if ever), but they do tend to grow (which might indicate a huge amount of holes crated in the process). Usually these `pwrite64` calls will finish in about 50 microseconds. Rarely more than one millisecond. Ever few tens thousands of calls however it will stall, and syscall will require at least 3 seconds to finish:

```text
[pid 14957] 23:58:58.141820 pwrite64(24, "\220\233\4\0\0\0\0\0\0\0\1\0^\0x\6\370\17\270\6\270\17x\0178\17\370\16\270\16x\16"..., 4096, 1236860928) = 4096 <6.383944>

...

[pid 14957] 00:00:42.788611 pwrite64(24, "\216#\30\0\0\0\0\0 \0\1\0,\0P\f\370\17\260\17h\17 \17\330\16\220\16H\16\0\16"..., 4096, 6479732736) = 4096 <0.000051>
[pid 14957] 00:00:42.788679 pwrite64(24, "\273#\30\0\0\0\0\0(\0\1\0v\0\350\1\370\17\260\17h\17 \17\330\16\220\16H\16\0\16"..., 4096, 6479917056) = 4096 <0.000013>
[pid 14957] 00:00:42.788708 pwrite64(24, "\307$\30\0\0\0\0\0@\0\"\0J\0\372\10C\274\0\0\0\0\0\0\276\373\21\1\0\0\0\0"..., 4096, 6481014784) = 4096 <0.000013>
[pid 14957] 00:00:42.788737 pwrite64(24, "T%\30\0\0\0\0\0(\0\"\0\322\0\232\1\273I;\25*RZ\347\223\306\355\367=D\203\304"..., 4096, 6481592320) = 4096 <0.000034>
[pid 14957] 00:00:42.788787 pwrite64(24, "\272%\30\0\0\0\0\0\0\0\1\0l\0\270\4\370\17\270\17\370\4x\17x\0058\17\370\16\270\16"..., 4096, 6482010112^[[6~) = 4096 <8.040208>   # <----
[pid 14957] 00:00:50.829067 pwrite64(24, "3&\30\0\0\0\0\0008\0\"\0\200\0000\4\3336\210\354\232A\261I|\4\234z\314\217\271\240"..., 4096, 6482505728) = 4096 <0.000116>
[pid 14957] 00:00:50.829267 pwrite64(24, "\\&\30\0\0\0\0\0@\0\1\0\200\0\250\5\370\17\310\17\230\17h\0178\17\10\17\330\5\330\16"..., 4096, 6482673664) = 4096 <0.000077>
[pid 14957] 00:00:50.829383 pwrite64(24, "2'\30\0\0\0\0\0(\0\"\0\274\0<\3\337\246\311\363\277\275\f\301\230v\25)\241\4\27j"..., 4096, 6483550208) = 4096 <0.000064>

```

I believe during the same time there will be a concurrent `fdatasync` running from another thread (started often many seconds before the stall) on the same file, while `pwrite64` are still going on concurrently too from the main thread.

```text
$ ls -lh /proc/$(pidof monerod)/fd | grep home
lrwx------ 1 baryluk baryluk 64 maj 16 01:04 23 -> /home/baryluk/.bitmonero/lmdb/lock.mdb
lrwx------ 1 baryluk baryluk 64 maj 16 01:04 24 -> /home/baryluk/.bitmonero/lmdb/data.mdb
lrwx------ 1 baryluk baryluk 64 maj 16 01:04 25 -> /home/baryluk/.bitmonero/lmdb/data.mdb
lrwx------ 1 baryluk baryluk 64 maj 16 01:04 26 -> /home/baryluk/.shared-ringdb/data.mdb
lrwx------ 1 baryluk baryluk 64 maj 16 01:04 27 -> /home/baryluk/.shared-ringdb/data.mdb
l-wx------ 1 baryluk baryluk 64 maj 16 01:04 3 -> /home/baryluk/Linux/monero-gui-v0.12.0.0/monero-gui-v0.12.0.0/monero-wallet-gui.log
l-wx------ 1 baryluk baryluk 64 maj 16 01:04 4 -> /home/baryluk/.bitmonero/bitmonero.log
```

### Describe how to reproduce the problem

See above.

I hope to retry with data stored on ext4 or tmpfs, and more zfs monitoring. Suggestions welcome. 

### Include any warning/errors/backtraces from the system logs

None

**Comment by baryluk** [comment]
Disabling sync dataset wise, `zfs set sync=disabled wctank4/home/baryluk/.bitmonero` , doesn't change anything for better. If anything it feels worse (stalls every 10 seconds or so).

**Comment by baryluk** [comment]
Changing `recordsize=4096` and `redundant_metadata=most` , stopping monerod, removing all snapshots and disabling periodic snapshots (ever 15 minutes), moving database file out of pool and the back (to defragment file and make new recordsize effective), basically fixed the problem.

Performance improved significantly too, `iostat` shows 3x incress in tps, with peaks up to 8000 iops. With almost zero KB_read/s. And sporadic periods of no writes at all (but that is due to sync=disabled probably). (It was previously doing only about 1000iops in peaks, and 800 iops on average). Write bandwidth is similar, if not smaller on average.

I attribute this to the fact that LMDB itself is copy-on-write database, and it has relatively random pattern of writes.

So I understand why the performance is better, and that with big record size ZFS performs poorly. But the bad impact on other datasets and write latency of other processes using the pool should not happen even if the recordsize is suboptimal. I guess the default of 128KB, with a lot of records with only small changes spread in them, creates a lot of suboptimal writes (and reads) when flushing data back to storage, and potentially blocks IO queues for long time. Not sure.

**Comment by kpande** [comment]
NVMe tend to thermal throttle like there's no tomorrow. have you checked this?

**Comment by baryluk** [comment]
I just said, that changing recordsize=4096 helped. Additionally, even if NVMe throttles and stops accepting writes, it should not affect writes to file system cache that do not hit NVMe at all from other application on same VFS / ZFS dataset. Thermal throttling also do not explain why during write being stalled, I can still read from the device at 2GB/s without issues or any latency hickups.

It is clearly a kernel or ZFS issue. Some form of lock contention or just lock during flusshing somewhere, or lack of write throttling of some sort.

I will try to reconfirm the that this is not thermal throttling experimentally, by 1) resyncing monerod from scratch and observing temperatures using `nvme smart-log /dev/nvme0n1`, 2) by creating new ZFS pool (unmirrored and unencrypted) with backing device in tmpfs via loopback.

**Comment by baryluk** [comment]
OK. I am taking that back. It might thermal throttling! I not 100% convinced, but who knows.

Peek observed temperature after just about 10 minutes of work with `recordsize=4096`:

```text
Every 2.0s: nvme smart-log /dev/nvme1n1 | grep -i temp            wielkiczarny: Wed May 16 20:59:56 2018

temperature                         : 50 C
Warning Temperature Time            : 0
Critical Composite Temperature Time : 0
Temperature Sensor 1                : 50 C
Temperature Sensor 2                : 90 C
```

(It climbed to ~80 deg C on Sensor 2, and 45 on Sensor 1, in just two minutes).

Even with `recordsize=4096` (which I previously claimed "solved" the write stalls from other apps), it still stalls, so it actually did not solve anything. (it just helped substantially previously somehow). I am still getting 5-10 seconds write stalls from other test program even 10 to 30 seconds, when resyncing monerod from scratch (~200 blocks per second, which translates to about 1000 iops per second in LMDB and file).

**Comment by baryluk** [comment]
Looking at thermal throttling counters from the drive, it is unlikely actually:

Focusing on Sensor 2.

Idle temp is 37 deg C.

After starting `monerod` it climbs to 60 deg in 15 seconds.

After 2 minutes, it oscillates around 75. Few more minutes later is above 80 deg C. Few more minutes and it does hit 90 deg C.

I experience write stalls even when the temperature was around 68 deg C already.

Also thermal transition counters shows zero all the time:

```text
Every 2.0s: nvme smart-log /dev/nvme0n1 | egrep -i "temp|ther"                                                                                        wielkiczarny: Wed May 16 19:41:04 2018

temperature                         : 45 C
Warning Temperature Time            : 0
Critical Composite Temperature Time : 0
Temperature Sensor 1                : 45 C
Temperature Sensor 2                : 82 C
Thermal Management T1 Trans Count   : 0
Thermal Management T2 Trans Count   : 0
Thermal Management T1 Total Time    : 0
Thermal Management T2 Total Time    : 0
```

So I am not convinced, but it could be just broken monitoring.


```text
# lspci | grep Samsung
08:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller SM961/PM961
09:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller SM961/PM961
```

```text
# nvme list
Node             SN                   Model                                    Namespace Usage                      Format           FW Rev  
---------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
/dev/nvme0n1     S318NAxxx       SAMSUNG MZVKW1T0HMLH-00000               1           1,02  TB /   1,02  TB    512   B +  0 B   CXA7300Q
/dev/nvme1n1     S318NAxxx       SAMSUNG MZVKW1T0HMLH-00000               1           1,02  TB /   1,02  TB    512   B +  0 B   CXA7300Q
```

These are two Samsung SM961. SSD M.2 (2280) 1TB. http://www.samsung.com/semiconductor/ssd/client-ssd/MZVKW1T0HMLH/

They are PCIe Gen 3, but I think I am actually using PCIe Gen 2 in my system, as Sandy Bridge doesn't support Gen 3. ( https://ark.intel.com/products/63697/Intel-Core-i7-3930K-Processor-12M-Cache-up-to-3_80-GHz )

I am using breakout PCIe card that hosts both of the M.2 drive on single side of one card. No passive or active cooling as such, other than the case air flow.

**Comment by richardelling** [comment]
This is not a bug and the conversation should be moved to the email list.

**Comment by kpande** [comment]
68C is very hot, my system sees max of 48C. and @richardelling is correct, mailing list or IRC are more appropriate locations.

**Comment by baryluk** [comment]
I still think this is in fact a ZFS bug, or kernel bug, and all my claims still stand. Even if the SSD is hot and is throttling, system should not block non-sync writes to a file system cache for sometimes 10 seconds, when at the same time, I still have 10GB of free memory in the system.

**Comment by gmelikov** [comment]
@baryluk lmdb works great for me on 2 hdd mirror, zfs 0.7.6. Please use mailing lists for future discussions about this topic.
