### ISSUE TITLE
zpool: symbol lookup error: zpool: undefined symbol: thread_init

### ISSUE THREAD

**Issue by kaN5300** [zfsonlinux/zfs#7544]
### System information

 
Distribution Name	| Xubuntu
Distribution Version	| 17.10/Artful
Linux Kernel	|  4.13.0-41-generic #46-Ubuntu SMP
Architecture	| amd64
ZFS Version	| 0.6.5.11-1ubuntu3.3
SPL Version	| 0.6.5.11-1ubuntu1

### Describe the problem you're observing
$ zpool
zpool: symbol lookup error: zpool: undefined symbol: thread_init
$ zfs
zfs: symbol lookup error: zfs: undefined symbol: zfs_send_resume

### Describe how to reproduce the problem

sudo apt install zfsutils-linux 

$ dpkg -l | grep zfs
ii  libzfs2linux                            0.6.5.11-1ubuntu3.4
ii  zfs-zed                                 0.6.5.11-1ubuntu3.4
ii  zfsutils-linux                          0.6.5.11-1ubuntu3.4

### Include any warning/errors/backtraces from the system logs

dmesg:
```
[   94.870206] ZFS: Loaded module v0.6.5.11-1ubuntu3.3, ZFS pool version 5000, ZFS filesystem version 5
[   94.835492] SPL: Loaded module v0.6.5.11-1ubuntu1
```

**Comment by gmelikov** [comment]
0.6.5.11 doesn't support  4.13 kernel.

And it looks like different userspace apps and kernel module version.

Please use compatible ZFS and kernel versions.

If you still have questions, you can write to out [mailing lists](https://github.com/zfsonlinux/zfs/wiki/Mailing-Lists), closed.

**Comment by Rmrfy** [comment]
> 0.6.5.11 doesn't support 4.13 kernel.
> 
> And it looks like different userspace apps and kernel module version.
> 
> Please use compatible ZFS and kernel versions.
> 
> If you still have questions, you can write to out [mailing lists](https://github.com/zfsonlinux/zfs/wiki/Mailing-Lists), closed.

Hi ：
  I want to install zfs-0.6.4 version under 7.4 system.But when the pool is created after the compilation and installation is completed, an error is reported.such as

`zpool: symbol lookup error: zpool: undefined symbol: zfs_dev_is_whole_disk`
