### ISSUE TITLE
Installation doc for centos/rhel command update

### ISSUE THREAD

**Issue by rahvee** [zfsonlinux/zfs#7548]
### Describe the problem you're observing

When following the installation instructions from
https://github.com/zfsonlinux/zfs/wiki/RHEL-and-CentOS
The zfs module fails to build or load.

### Describe how to reproduce the problem

The problem is caused by installing `kernel-devel` which is a later version than the running kernel. The problem can be solved by using the following command:

`$ sudo yum install "kernel-devel-uname-r == $(uname -r)" zfs`
instead of the command currently in the documentation:
`$ sudo yum install kernel-devel zfs`

**Comment by rlaager** [comment]
Fix applied. (I don't use CentOS, so I didn't test it. But I see what you're going for here.)
