### ISSUE TITLE
zfs inherit took several minutes

### ISSUE THREAD

**Issue by gusioo** [zfsonlinux/zfs#7558]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Linux
Distribution Version	| 
Linux Kernel	| 4.4.45
Architecture	| x86_64
ZFS Version	| 0.7.2-1
SPL Version	| 0.7.2-1

### Describe the problem you're observing

I want to use zvol with the custom property and a few thousands of snapshots. Each time a new snapshot is created the custom property is inherited from parent zvol. When I delete property zfs inherit takes a long time (a dozen minutes).

Is there a possibility to speed up this process or disable inheritance of custom properties so the process could take just a moment?

### Describe how to reproduce the problem

Zvol with custom property and few thousands of snapshots. Deleting custom property takes a long time.

**Comment by kpande** [comment]
this is better discussed on [the zfs-discuss mailing list](http://list.zfsonlinux.org) as it is a support request and not a bug.
