### ISSUE TITLE
zpool list and zfs list disagree on available space

### ISSUE THREAD

**Issue by RubenKelevra** [zfsonlinux/zfs#7565]
I got one pool, called data (1 way mirrored, one device taken manually offline). ZFS and zpool cannot agree on how much space is available on this pool.

There are no snapshots/reservations/quotas involved here, but I created recently 100-200 subvolumes and additionally 100-200 zvols and destroyed them again, I guess there's some unexpected overhead in such operations or some leaked space from them. How can we debug this? 

```
# zpool get all data
[...]
data  free                           29,6G
[...]
# zfs list
NAME         USED  AVAIL  REFER  MOUNTPOINT
data         566G  11,0G   566G  /data
```

### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Arch Linux
Linux Kernel	| 4.16.8-1-ARCH
Architecture	| x86-64
ZFS Version	| https://github.com/zfsonlinux/zfs/commit/64c1dcefe38a62d304177475a2ef77111cec612a
SPL Version	| https://github.com/zfsonlinux/spl/commit/84a80d5f2d14fdfd16d440eef2e3d6e756a1165c

**Comment by kpande** [comment]
please use the [zfs-discuss mailing list](http://list.zfsonlinux.org) for support requests.

**Comment by ahrens** [comment]
What's your pool configuration?  i.e. `zpool list -v`  What's `zpool get freeing` show?

**Comment by RubenKelevra** [comment]
Hey @ahrens,

so I think that there's some issue with the presentation in the UI and the documentation in the manpage, which lead to my interpretation that the number for _free_ in `zpool` and the number for _avail_ in `zfs` means the same thing.

The man page currently states, _free_ by `zpool` means:

```
The amount of free space available in the pool.
```

The man page states, for _available_ by `zfs`:
```
The amount of space available to the dataset and all its
children, assuming that there is no other activity in the pool.
Because space is shared within a pool, availability can be limited by
any number of factors, including physical pool size, quotas,
reservations, or other datasets within the pool.
```

There's nothing which points to a major difference here, to the user.

> What's `zpool get freeing` show?

```
NAME  PROPERTY  VALUE    SOURCE
data  freeing   0        -
```

> What's your pool configuration? i.e. `zpool list -v`

```
# zpool list -v
NAME   SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
data   596G   566G  30.3G         -    16%    94%  1.00x  DEGRADED  -
  mirror   596G   566G  30.3G         -    16%    94%
    sdc2      -      -      -         -      -      -
    sdb      -      -      -         -      -      -
# zfs list
NAME                  USED  AVAIL  REFER  MOUNTPOINT
data                  566G  11.7G   566G  /data

```

So 596 - 566 gives 30 G, what's displayed here. `zfs` on the other hand do some other calculations to get 11.7 G _avail_.

We might want to consider to change how the free value is calculated, substracting any additionally overhead and internal reservations, which is obviously done for `zfs list`, and show the same value which is displayed by `zfs list`. Additionally, we can add one or more new rows on `zpool get all <pool>`, showing exactly what's substracted for which purpose.

**OR**

We can change the documentation to something like 

```
free - The amount of physical space for blocks on the pool, which are currently
       unused. Because there are some internal reservations on storage pools,
       not all of this space is available to the dataset of this pool.
```

**OR**

We change the documentation as proposed, leave the free value as it was before and add the additional rows on `zpool get all <pool>` which shows exactly what's substracted for which purpose from the free value.

**Comment by RubenKelevra** [comment]
Thanks, this behavior is documented in the zfs-module-parameters man page. As stated before, I feel this information should be added to the zpool man page as well.

**Comment by richardelling** [comment]
My last posting here, this discussion belongs on the mail list.

There is not a simple answer for correlating pool space to logically available space. For example, with mixed vdev types or raidz, the numbers are much less obvious. The only simple thing to say is that you should manage the zfs space and ignore the zpool space.

For background, I have a single slide in my ZFS training materials that shows the output of `zfs list -o space` In learning about ZFS space accounting, we can spend 30 minutes discussing this one slide. Adding zpool space accounting could double that time, but doesn't help with the management of policies on space allocation, which is entirely done using the `zfs` command.

**Comment by ahrens** [comment]
@RubenKelevra Sure, feel free to open a PR to improve the manpages' description of the difference between the the allocated/free space listed in `zpool list`, and the used/available space listed in `zfs list`.  As @richardelling mentioned, this is complicated, but a common source of confusion.  If folks are reading the manpages and not getting the message that they should not be looking at `zpool list` to understand how much space is available, then we can definitely fix that.  (Though I suspect most folks who are confused by this are also not reading the manpages.)
