### ISSUE TITLE
rpm-utils fails to build on CentOS 7 using --with-config=srpm

### ISSUE THREAD

**Issue by DeHackEd** [zfsonlinux/zfs#7567]
### System information
Type | Version/Name
 --- | --- 
Distribution Name	| CentOS
Distribution Version	| 7.4
Linux Kernel	| 3.10.0-693.5.2.el7.x86_64
Architecture	| x86_64
ZFS Version	| zfs-0.7.0-493-g0dc2f70
SPL Version	| spl-0.7.0-36-g1149b62

### Describe the problem you're observing
```
# make distclean
# sh configure --with-config=srpm
# make rpm-utils
...
symlinked /usr/lib/debug/lib64/libuutil.so.1.0.1.debug to /usr/lib/debug/lib64/libuutil.so.debug
symlinked /usr/lib/debug/lib64/libzfs.so.2.0.0.debug to /usr/lib/debug/lib64/libzfs.so.2.debug
symlinked /usr/lib/debug/lib64/libnvpair.so.1.0.1.debug to /usr/lib/debug/lib64/libnvpair.so.1.debug
symlinked /usr/lib/debug/lib64/libzfs.so.2.0.0.debug to /usr/lib/debug/lib64/libzfs.so.debug
20088 blocks
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/redhat/brp-compress
+ /usr/lib/rpm/redhat/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1
+ /usr/lib/rpm/redhat/brp-python-hardlink
+ /usr/lib/rpm/redhat/brp-java-repack-jars
Processing files: zfs-0.7.0-493_g0dc2f70.el7.centos.x86_64
error: File must begin with "/": %{_generatordir}/*


RPM build errors:
    File must begin with "/": %{_generatordir}/*
make[1]: *** [rpm-common] Error 1
make[1]: Leaving directory `/usr/src/zfs'
make: *** [rpm-utils] Error 2
```
vs
```
# sh configure --with-config=user
# make rpm-utils
...
(successful build)
```
### Describe how to reproduce the problem
Basically described above

### Include any warning/errors/backtraces from the system logs
n/a

**Comment by aerusso** [comment]
I'm sorry---I'm have some trouble finding git revision g0dc2f70? Could you point to the specific revision? I also cannot seem to reproduce this on master.

**Comment by DeHackEd** [comment]
Drop the 'g' to get a git commit id. This is what `git describe` shows. So g 0dc2f70

**Comment by aerusso** [comment]
Thanks. Does this also happen in a clean check-out? Like `git archive 0dc2f70 | tar -x -C /tmp/build-dir/`?

I'm not able to reproduce it here on Debian testing with that commit either.

**Comment by DeHackEd** [comment]
I did as you suggested. It still failed. The highlight of the diff of the two outputs appears to be this:
```
@@ -1510,29 +1512,29 @@
 if test -d "zfs-0.7.0"; then find "zfs-0.7.0" -type d ! -perm -200 -exec chmod u+w {} ';' && rm -rf "zfs-0.7.0" || { sleep 5 && rm -rf "zfs-0.7.0"; }; else :; fi
 make[2]: Entering directory `/tmp/build-dir'
 make[2]: Leaving directory `/tmp/build-dir'
-Wrote: /tmp/zfs-build-root-tfcHWfVc/SRPMS/zfs-0.7.0-1.el7.centos.src.rpm
+Wrote: /tmp/zfs-build-root-hTaiGGrJ/SRPMS/zfs-0.7.0-1.el7.centos.src.rpm
 make[1]: Leaving directory `/tmp/build-dir'
 make  pkg="zfs" \
-       def='--define "_without_debug 1" --define "_without_debuginfo 1" --define "_without_asan 1" --define "_initconfdir /etc/sysconfig"   ' rpm-common
+       def='--define "_without_debug 1" --define "_without_debuginfo 1" --define "_without_asan 1" --define "_initconfdir /etc/sysconfig"  --with systemd --define "_unitdir /usr/lib/systemd/system" --define "_presetdir /usr/lib/systemd/system-preset" --define "_generatordir /usr/lib/systemd/system-generators" ' rpm-common
 make[1]: Entering directory `/tmp/build-dir'
 make[2]: Entering directory `/tmp/build-dir'
 make[2]: Leaving directory `/tmp/build-dir'
 Installing zfs-0.7.0-1.el7.centos.src.rpm
```
Build log files:
http://64.39.160.227/build-failure-srpm.txt
http://64.39.160.227/build-success-user.txt
Not shown: `make distclean` between runs.

**Comment by aerusso** [comment]
Could you see if 6955801 fixes this? This looks like a loose end I may have missed.

**Comment by DeHackEd** [comment]
That didn't seem to affect anything.

**Comment by aerusso** [comment]
It seems like `_generatordir` is not getting set. I don't understand how that should be possible, so someone who understand the RPM build process is going to have to help out.

**Comment by stewartadam** [comment]
Any objections to using `%{_systemdgeneratordir}` instead of passing one through a `--define` from the CLI?
