### ISSUE TITLE
Compilation error GPL-only symbol 'trace_handle_return'

### ISSUE THREAD

**Issue by gtrafimenkov** [zfsonlinux/zfs#7572]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| 
Distribution Version	| 
Linux Kernel	| 4.16.12
Architecture	| amd64
ZFS Version	| 0.7.9
SPL Version	| 0.7.9

### Describe the problem you're observing

I am trying to compile zfs 0.7.9 as built in for kernel 4.16.12.  Compilation fails with the following error:

```
FATAL: modpost: GPL-incompatible module zfs.ko uses GPL-only symbol 'trace_handle_return'
scripts/Makefile.modpost:92: recipe for target '__modpost' failed
```

### Describe how to reproduce the problem

- download, extract linux kernel sources linux-4.16.12.tar.xz, configure
- download and extract spl 0.7.9
- `./autogen.sh && ./configure --enable-linux-builtin --with-linux=PATH_TO_KERNEL_SOURCES && ./copy-builtin PATH_TO_KERNEL_SOURCES`
- download and extract zfs 0.7.9
- `./autogen.sh && ./configure --enable-linux-builtin --with-linux=PATH_TO_KERNEL_SOURCES && ./copy-builtin PATH_TO_KERNEL_SOURCES`
- `cd PATH_TO_KERNEL_SOURCES`
- `make menuconfig`, select compilation of Solaris Porting Layer and ZFS Filesystem support as modules
- `make -j $(nproc) bindeb-pkg`

### Include any warning/errors/backtraces from the system logs

Compiation fails with the error:

```
FATAL: modpost: GPL-incompatible module zfs.ko uses GPL-only symbol 'trace_handle_return'
scripts/Makefile.modpost:92: recipe for target '__modpost' failed
make[3]: *** [__modpost] Error 1
Makefile:1267: recipe for target 'modules' failed
make[2]: *** [modules] Error 2
make[2]: *** Waiting for unfinished jobs....
```

**Comment by gtrafimenkov** [comment]
I have found the problem.  I configured building spl and zfs as modules:

```
CONFIG_SPL=m
CONFIG_ZFS=m
```

When configuring like this:

```
CONFIG_SPL=y
CONFIG_ZFS=y
```

everything works fine.

I configured spl ans zfs as modules because I wanted to build kernel deb packages with spl and zfs modules included.

**Comment by behlendorf** [comment]
Commit cb709642216b5ac9be10039471c3c4bc27cb7cf2 further improves the tracing situation and will be in the next major release.
