### ISSUE TITLE
[*el6] Setting up zfs-dracut for zfs / with ext4 /boot

### ISSUE THREAD

**Issue by steakknife** [zfsonlinux/zfs#758]
Suggestions, feedback welcome because IHNFI about dracut.

##### Steps:

0. Build and setup as usual.
1. Edit /etc/dracut.conf, add zfs to dracutmodules and add_dracutmodules
2. Run `dracut --force`

##### Error:

`/sbin/dracut: line 246: /usr/share/dracut/modules.d/90zfs/install: No such file or directory`

##### Expected Behavior:

dracut to build an image capable of booting a zfs root volume from an ext4 /boot.

##### Environment:
SL 6.2 x86_64
```
kernel-2.6.32-220.17.1.el6.x86_64
dracut-004-256.el6.noarch
dracut-kernel-004-256.el6.noarch
grub-0.97-75.el6.x86_64
spl + zfs 0.6.0 rc8 built from source
```

**Comment by Rudd-O** [comment]
In my fork, I've merged most of the upstream dracut stuff, but there are still important bits in my fork without which Fedora 20 and 21 systems just won't boot from root ZFS.

My script zfs-fedora-installer also has a workaround for GRUB that eliminates the need to recompile GRUB with ZFS support for booting from a ZFS root pool.

Enjoy!

**Comment by Rudd-O** [comment]
This is the relevant integration bit that allows root on ZFS on LUKS to work:

https://github.com/Rudd-O/zfs/tree/master/dracut/02zfsexpandknowledge

This is the relevant integration bit that allows GRUB to work with ZFS roots:

https://github.com/Rudd-O/zfs-fedora-installer/tree/master/grub-zfs-fixer

Enjoy!

**Comment by Rudd-O** [comment]
This bug should no longer be a problem anymore.

**Comment by behlendorf** [comment]
@Rudd-O thanks for following up.  Since this should no longer be an issue in master I'm closing this.
