### ISSUE TITLE
"zpool online -e" doesn't work without running export + partprobe +import in the VM

### ISSUE THREAD

**Issue by gordan-bobic** [zfsonlinux/zfs#7582]
Latest CentOS (7.5) kernel and ZoL 0.7.9, KVM hypervisor

To reproduce:
Create a VM with 50GB disk2/vdb, start the vm and create pool on it.

On hypervisor:
```
# lvresize -L 100G /dev/vms/testvm-disk2 
  Size of logical volume vms/testvm-disk2 changed from 50.00 GiB (12800 extents) to 100.00 GiB (25600 extents).
  Logical volume vms/testvm-disk2 successfully resized.
# virsh blockresize --path /dev/vms/testvm-disk2 --size 100G testvm
Block device '/dev/vms/testvm-disk2' is resized
```
On guest:
```
# dmesg | tail -2
[3368803.667305] virtio_blk virtio3: new size: 209715200 512-byte logical blocks (107 GB/100 GiB)
[3368803.667316] vdb: detected capacity change from 53687091200 to 107374182400
# zpool set autoexpand=on data
# zpool online -e data /dev/vdb
# zpool list
NAME   SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
data  49.9G  47.4G  2.4G         -      -    95%  1.00x  ONLINE  -
```
Exporting the pool, running partprobe, then re-importing the pool, then doing zpool online -e data /dev/vdb does work, but having to introduce downtime to extend the disk is far from ideal.

**Comment by DeHackEd** [comment]
Sounds like a Linux kernel behaviour where a live partition can't be resized by re-reading the partition table while said partition is in use. Hence the export.

**Comment by gordan-bobic** [comment]
Perhaps, but it works for LVM volumes without unmounting and partprobing, so it should also be achievable with ZFS.

**Comment by shartse** [comment]
`autoexpand` currently doesn't work at all. However, you should be able to manually expand the vdev without exporting the pool. 

I'm currently working on a fix that has `zpool reopen` detect the new expandsize. Then zfs will know about the new space and you can run `zpool online -e` to use it: https://github.com/zfsonlinux/zfs/pull/7546.

As for the way things work now, here's a hacky workaround: Run `partprobe`  on your device (it should give the warning about new space). Then  `zpool online -e <pool> <dev>` followed by `partprobe` again allows zfs to detect the new expandsz available for the the vdev (visible through zpool list -v). To add the space to the vdev run `zpool online -e`
