### ISSUE TITLE
Centos 7.5 can't run zfs (source, kabi, dkms)

### ISSUE THREAD

**Issue by svennd** [zfsonlinux/zfs#7590]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Centos
Distribution Version	|  7.5.1804 (Core)
Linux Kernel	|  3.10.0-862.3.2.el7
Architecture	| 86_64
ZFS Version	|  0.7.9-1
SPL Version	|  0.7.9-1

### Describe the problem you're observing
Cannot load zfs module due to errors. after building from source (also had issue with the normal dkms/kabi)

```
modprobe zfs
modprobe: ERROR: could not insert 'zfs': Unknown symbol in module, or unknown parameter (see dmesg)

dmesg 
[  122.614476] zfs: Unknown parameter `zil_slog_limit'
```

zfs errors observed during make -s -j$(nproc) : 
```
/opt/zfs/zfs_0.7.9/zfs-0.7.9/module/zcommon/zfs_fletcher_avx512.o: warning: objtool: fletcher_4_avx512f_byteswap()+0x4e: can't find jump dest instruction at .text+0x171
/opt/zfs/zfs_0.7.9/zfs-0.7.9/module/zfs/vdev_raidz_math_avx512bw.o: warning: objtool: raidz_zero_abd_cb()+0x33: can't find jump dest instruction at .text+0x3d
/opt/zfs/zfs_0.7.9/zfs-0.7.9/module/zfs/vdev_raidz_math_avx512f.o: warning: objtool: mul_x2_2()+0x24: can't find jump dest instruction at .text+0x39
```
I removed older kernels, and retry but to no avail, also using kabi or dkms failed to get a working zfs module :( 

### Describe how to reproduce the problem

Centos 7.5, attempt to install latest zfs.

if this is already reported, I apoligise I haven't found it.

**Comment by behlendorf** [comment]
> zfs: Unknown parameter `zil_slog_limit'

This is a configuration issue.  You must have an `/etc/modprobe.d/zfs.conf` file, or similar, on your system when is trying to set the `zil_slog_limit` module parameter.  This parameter no longer exists which is causing the module load to fail.  Remove this tuning and you'll be able to load the modules.

**Comment by svennd** [comment]
Ow this is painful, yes, spot on, thanks !

**Comment by AeonJJohnson** [comment]
This same error occurs during dkms compilation of **_zfs 0.7.9_** on **_CentOS 7.5.1804_** running **_3.10.0-862.9.1.el7.x86_64_**

    ...
    Making all in 90zfs
    Making all in initramfs
    Making all in module
    /home/aeon/devel/zfs/module/zcommon/zfs_fletcher_avx512.o: warning: objtool: fletcher_4_avx512f_byteswap()+0x4e: can't find jump dest instruction at .text+0x171
    /home/aeon/devel/zfs/module/zfs/vdev_raidz_math_avx512bw.o: warning: objtool: raidz_zero_abd_cb()+0x33: can't find jump dest instruction at .text+0x3d
    /home/aeon/devel/zfs/module/zfs/vdev_raidz_math_avx512f.o: warning: objtool: mul_x2_2()+0x24: can't find jump dest instruction at .text+0x39

**Comment by behlendorf** [comment]
These warnings are the result of the kernel being configured with `CONFIG_STACK_VALIDATION` and are harmless.  The version of `objtool` provided by the kernel is confused.
