### ISSUE TITLE
Wiki for 18.04 root install has small error

### ISSUE THREAD

**Issue by olmari** [zfsonlinux/zfs#7605]
At wiki https://github.com/zfsonlinux/zfs/wiki/Ubuntu-18.04-Root-on-ZFS there is typo in one of the notes in Step 3:

"If you want ACL support on everything, you can set it on the whole pool: zfs set -o acltype=posixacl rpool"

That "-o" in there is extra and will result in error. When setting parameters with zfs set you don't use "-o" there, while you do use it in for example "zfs create" to set parameter for dataset/zvol.

**Comment by gmelikov** [comment]
Thank you, fixed.
