### ISSUE TITLE
[dracut] missing systemd binaries in initramfs generated by dracut when sysroot uses native zfs encryption

### ISSUE THREAD

**Issue by gedia** [zfsonlinux/zfs#7607]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Gentoo
Distribution Version	| rolling
Linux Kernel	| 4.17
Architecture	| AMD64
ZFS Version	| 0.7.0-1417_g2d9142c9
SPL Version	| 0.7.0-1417_g2d9142c9

### Describe the problem you're observing
Dracut-generated initramfs does not include the following two binaries necessary when sysroot is on zfs with native encryption:
* /bin/systemd-ask-password
* /bin/systemd-tty-ask-password-agent
### Describe how to reproduce the problem
Install your distro on a ZFS dataset with native ZFS encryption. Use ZFS-provided dracut scripts to generate an initramfs, then try booting. You will be prompted for a passphrase to decrypt your ZFS datasets but your input won't be registered.

Using a recent dracut from git master doesn't seem to help either.
### Workaround
Manually extract the generated initramfs, copy these two binaries over, and repackage into a cpio.

### P.S.
I am not sure whether this is an issue with zfs-provided dracut scripts, or with dracut itself. It's been a while since I looked into this, but I believe these tools are flagged for inclusion into the generated initramfs via dracut scripts intended for cryptsetup. Merely installing cryptsetup (so dracut will detect its presence) doesn't seem to be enough. However, I don't think this should depend on cryptsetup in any way as zfs native encryption by itself should prompt dracut to include these binaries in the initramfs.

**Comment by behlendorf** [comment]
@gedia it sounds like you've already identified the root cause here and the `contrib/dracut/90zfs/module-setup.sh.in` needs to be updated to install the binaries in the image.  The `install` function is where this happens, and it should be an easy addition.  If you can make the change locally, verify it works, and open a PR we can get it reviewed and integrated.

**Comment by gedia** [comment]
I made an attempt at a patch. Resulting Pull Request is #7719
