### ISSUE TITLE
The role of /etc/default/zfs is inconsistent and poorly documented

### ISSUE THREAD

**Issue by aerusso** [zfsonlinux/zfs#7635]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| none/any (but especially Debian)
Distribution Version	| unstable
Linux Kernel	| irrelevant
Architecture	| irrelevant
ZFS Version	| git master
SPL Version	| git master

### Describe the problem you're observing
Downstream [Debian bug 901436](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=901436) has come up where a user tried, quite reasonably, to disable boot-time `zfs mount -a` by settings `ZFS_MOUNT=no` in `/etc/default/zfs`.

### Discussion
However, that variable is used only by the sysv init scripts---and the documentation should reflect that. There are a couple other questions this brings up though:

1. The initramfs system also uses parameters in this file so it cannot be treated as merely a part of the sysv init system (and therefore should probably be moved in the source hierarchy, so downstream maintainers are not fooled into thinking it is only used by the sysv scripts)

2. There are other options in this file that maybe should be supported by systemd init scripts---basically everything after `VERBOSE_MOUNT=` in that file (and maybe also that as well?)

If we can come to a consensus on how this should be handled, I can write up a PR to fix this.

**Comment by colttt** [comment]
looks like my bug-report ;)
#7627

**Comment by aerusso** [comment]
Whoops. I searched, but my eyes did not see.
