### ISSUE TITLE
Sharenfs with ACL - how must the option set?

### ISSUE THREAD

**Issue by boospy** [zfsonlinux/zfs#7640]
I use here proxmox with ZFSversion 0.7.9. 

I would like to use unix acl's with nfsshare on ZFS too. With normal NFS-Export this is working fine. If i create an share with the acl-option, i get an error that this is an unknown option. 

`zfs create testpool/testnfs -o sharenfs="rw=@hostname1.local,rw=@192.168.1.3,no_root_squash,no_subtree_check,async,acl"`

Thanks for help and Best Regards

**Comment by drescherjm** [comment]
I think this is a question for the mailing list.

**Comment by boospy** [comment]
You mean that?
http://list.zfsonlinux.org/mailman/listinfo/zfs-discuss
