### ISSUE TITLE
"Install Root on ZFS" wikis are a usability nightmare

### ISSUE THREAD

**Issue by taoeffect** [zfsonlinux/zfs#7670]
### Describe the problem you're observing

I've reviewed the "root on ZFS" instructions for several wikis, including [Ubuntu](https://github.com/zfsonlinux/zfs/wiki/Ubuntu-18.04-Root-on-ZFS), [Debian](https://github.com/zfsonlinux/zfs/wiki/Debian-Stretch-Root-on-ZFS), and third-party instructions for [Fedora](https://www.csparks.com/BootFedoraZFS/index.md), and they are all shockingly complicated.

ZFS is an incredible filesystem! It is lightyears ahead of everything else out there! It's been 13 years since its introduction! By now it should be *default* on all Linux distributions as the only root filesystem.

And yet it's 2018 and these wikis are *nightmare inducing!*

What is going on? Why is it still so mind-bogglingly difficult to install ZFS?

**Comment by ryu0** [comment]
Because, most distributions don't ship with ZFS support out of the box. Those instructions are for people that want to use ZFS as their root filesystem in spite of that. They are basically instructions for the manual installation process, which allows you to bypass the limitations of the automated installers, but at the cost of increased difficulty.

**Comment by taoeffect** [comment]
So I got that there is some obscure drama regarding licensing. This is a serious issue. I really want to use ZFS as root on all my linux systems, but can't because of this! I'm definitely not the only person in this boat!

How long can this status quo continue? Will it ever be addressed?

**Comment by gmelikov** [comment]
Please don't just remove issue template next time. Bug tracker is not a support forum, use our mailing lists. It would be great if you may be more specific there.

Closed, not a bug.

**Comment by taoeffect** [comment]
> Closed, not a bug.

Many projects consider serious usability problems that completely prevent the software from being installed or used to be bugs — usability bugs.

**Comment by gmelikov** [comment]
@taoeffect, if you're interested in this question, you can search our issues, some of them
 https://github.com/zfsonlinux/zfs/issues/6804 https://github.com/zfsonlinux/zfs/issues/6056

Yes, it would be great to have zfs integrated in distros installers. But for now zfs on root is still preferred for experienced users only (license is not the only concern). So we write comprehensive instructions, where one of our targets is to familiarize user with zfs. If you have any specific suggestions - they are always welcome!

Let's discuss this topic in mailing lists, if you want.
