### ISSUE TITLE
Test suite: enospc_002_pos failure affects enospc_003_pos

### ISSUE THREAD

**Issue by PaulZ-98** [zfsonlinux/zfs#7671]
### System information

Distribution Name	|  Ubuntu
Distribution Version	|  16.04
Linux Kernel	|  
Architecture	| 
ZFS Version	| 0.7.0-1453_g6983060
SPL Version	|  0.7.0-1453_g6983060

### Describe the problem you're observing
enospc_002_pos has expected failure modes but does not clean up.  This affects the next test enospc_003_pos because a mount point directory is not empty.
### Describe how to reproduce the problem
./scripts/zfs-tests.sh -T no_space
### Include any warning/errors/backtraces from the system logs
```
Test: /root/send5/zfs/tests/zfs-tests/tests/functional/no_space/enospc_003_pos (run as root) [00:01] [FAIL]
10:43:54.59 ASSERTION: ENOSPC is returned on pools with large physical block size
10:43:55.69 SUCCESS: mkfile 512m /var/tmp/filedisk0_create
10:43:56.04 SUCCESS: zpool create testpool1 -o ashift=13 /var/tmp/filedisk0_create
10:43:56.14 ERROR: zfs set mountpoint=/var/tmp/testdir testpool1 exited 1
10:43:56.14 cannot mount '/var/tmp/testdir': directory is not empty property may be set but unable to remount filesystem
```

**Comment by PaulZ-98** [comment]
I'll create PR soon but this seemed to fix things.
```
diff --git a/tests/zfs-tests/tests/functional/no_space/enospc_002_pos.ksh b/tests/zfs-tests/tests/functional/no_space/enospc_002_pos.ksh
index ab74734..4d8c83e 100755
--- a/tests/zfs-tests/tests/functional/no_space/enospc_002_pos.ksh
+++ b/tests/zfs-tests/tests/functional/no_space/enospc_002_pos.ksh
@@ -28,6 +28,13 @@
 
 verify_runnable "both"
 
+function cleanup
+{
+        log_must rm -f $TESTDIR/*
+}
+
+log_onexit cleanup
+
 log_assert "ENOSPC is returned when file system is full."
 sync
 log_must zfs set compression=off $TESTPOOL/$TESTFS

**Comment by PaulZ-98** [comment]
Here's the line in enospc_003_pos that fails (set mountpoint)
```
log_must zpool create $TESTPOOL1 -o ashift=13 $disk
log_must zfs set mountpoint=$TESTDIR $TESTPOOL1    <-- fails

**Comment by PaulZ-98** [comment]
Also FWIW enospc_002_pos fails because sometimes zfs snapshot and zfs bookmark will succeed despite full pool.  Should we just eliminate the 002_pos test?

**Comment by behlendorf** [comment]
@PaulZ-98 there was a commit to made on Friday to address this e03a41a6049d463fe746038c81dec394783db98e.  Additional improvements welcome.

**Comment by PaulZ-98** [comment]
Hi @behlendorf that works for me!  Closing.
