### ISSUE TITLE
openssh-server not installed by default in live 9.3

### ISSUE THREAD

**Issue by jasonblewis** [zfsonlinux/zfs#7679]
@gmelikov @rlaager

on the wiki page Debian Stretch Root on ZFS

openssh-server not installed in the live 9.3 cd by default (didn't have a chance to test 9.4 yet)

suggest you include the line `apt install openssh-server` somewhere

### System information

Type | Version/Name
 --- | --- 
Distribution Name	| 
Distribution Version	| 
Linux Kernel	| 
Architecture	| 
ZFS Version	| 
SPL Version	|

**Comment by gmelikov** [comment]
@jasonblewis thank you, done.
