### ISSUE TITLE
suggested updates to the Debian Stretch Root on ZFS wiki page

### ISSUE THREAD

**Issue by jasonblewis** [zfsonlinux/zfs#7685]
@gmelikov and @rlaager

 - after installing zfs in step 1.5, `modprobe zfs`
   alternatively before running zpool create in 2.3

 - section 2.3 
  this gives an error if you aren't using v7 of zfs. you have a note about that further down the page, but it would be better to note not to use "-o feature@large_dnode=disabled" option unless using v7, above the command, before the user might try and do it.
```
   root@debian:~# zpool create -o ashift=12       -o feature@large_dnode=disabled       -O atime=off -O canmount=off -O compression=lz4 -O normalization=formD       -O xattr=sa -O mountpoint=/ -R /mnt rpool /dev/vda1 
   cannot create 'rpool': invalid feature 'large_dnode'
``` 

- section 1.5 and 4.5
`the apt install  --yes zfs-dkms` commands give an error (when installing with backports at any rate)
`/var/lib/dkms/zfs/0.7.9/build/configure: line 13069: dpkg-architecture: command not found`
suggest `apt install dpkg-dev`  before installing zfs-dkms

**Comment by gmelikov** [comment]
> after installing zfs in step 1.5, modprobe zfs
alternatively before running zpool create in 2.3

IIRC it's not necessary, module will load with zpool creation. Or did you have any errors?

> section 2.3
this gives an error if you aren't using v7 of zfs. you have a note about that further down the page, but it would be better to note not to use "-o feature@large_dnode=disabled" option unless using v7, above the command, before the user might try and do it.

Moved it to precaution before command.

> section 1.5 and 4.5
the apt install --yes zfs-dkms commands give an error (when installing with backports at any rate)
/var/lib/dkms/zfs/0.7.9/build/configure: line 13069: dpkg-architecture: command not found
suggest apt install dpkg-dev before installing zfs-dkms

Thank you, added.

**Comment by gmelikov** [comment]
@jasonblewis added `modprobe zfs`.

If you'll find something more - feel free to write me here.
