### ISSUE TITLE
Performance degradation (related to gnome-keyring)?

### ISSUE THREAD

**Issue by SohumB** [zfsonlinux/zfs#7686]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Debian
Distribution Version	| buster/sid
Linux Kernel	| 4.16.0-2
Architecture	| amd64
ZFS Version	| 0.7.9-3
SPL Version	| 0.7.9-3

### Describe the problem you're observing

Hey! Let me know if this isn't the appropriate forum for this, but I think I've managed to build a testcase for _some_ form of performance degradation on zfs. Booting an equivalent system from an root ext4 partition is about a minute faster than booting from a root zfs volume. Same underlying drive (an msata SSD), and a simple iozone test on the zfs and ext4 partitions have zfs being naturally faster or comparable.

### Describe how to reproduce the problem

I have an ext4 root partition, which I copied over to a zfs volume following the suggestions in https://github.com/zfsonlinux/zfs/wiki/Debian-Stretch-Root-on-ZFS. That's as far as I understand the reproduction—but they _are_ the same data in both filesystems. I'm happy to work with yall in making this testcase smaller, since I've reached the limit of what I understand here.

### Include any warning/errors/backtraces from the system logs

I did run some bootcharts: 

[bootchart-20180705-2024-zfsroot.svg.gz](https://github.com/zfsonlinux/zfs/files/2169012/bootchart-20180705-2024-zfsroot.svg.gz)
[bootchart-20180705-2049-ext4root.svg.gz](https://github.com/zfsonlinux/zfs/files/2169013/bootchart-20180705-2049-ext4root.svg.gz)

So clearly the CPU usage is nigh-identical. What strikes me is how there's a couple of places on the zfs log where something looks like it's blocking access to... something? presumably the filesystem? The gnome-keyring and systemd cases towards the bottom.

**Comment by kpande** [comment]
please use [the zfs-discuss mailing list](http://list.zfsonlinux.org), thank you!
