### ISSUE TITLE
permanent errors detected in files - but only hexcodes, no filenames

### ISSUE THREAD

**Issue by devZer0** [zfsonlinux/zfs#7687]
### System information
Distribution Name	|  CentOS Linux 
Distribution Version	|  release 7.4.1708 (Core)
Linux Kernel	|   3.10.0-693.17.1.el7.x86_64
Architecture	|  x86_64
ZFS Version	|   0.7.6-1
SPL Version	|   0.7.6-1

### Describe the problem you're observing

while resilvering (upgrading from 2tb to 6tb drives, ata-WDC_WD60EFRX-68MYMN1_WD-WX51D6416058 is the 1st of 6 6tb drives) i got  

[root@tmbackup02 ~]# zpool status -v
  pool: timemachinepool
 state: DEGRADED
status: One or more devices has experienced an error resulting in data
	corruption.  Applications may be affected.
action: Restore the file in question if possible.  Otherwise restore the
	entire pool from backup.
   see: http://zfsonlinux.org/msg/ZFS-8000-8A
  scan: resilvered 1,73T in 18h26m with 1 errors on Fri Jul  6 06:20:41 2018
config:

	NAME                                           STATE     READ WRITE CKSUM
	timemachinepool                                DEGRADED     0     0     1
	  raidz2-0                                     DEGRADED     0     0     3
	    ata-WDC_WD2003FYYS-02W0B0_WD-WMAY00390617  ONLINE       0     0     0
	    ata-WDC_WD2003FYYS-02W0B0_WD-WMAUR0553783  FAULTED      8     0     0  too many errors
	    ata-WDC_WD2003FYYS-02W0B0_WD-WMAUR0599953  ONLINE       8     0     0
	    ata-WDC_WD20EFRX-68EUZN0_WD-WCC4M7VPE2A6   ONLINE       0     0     0
	    ata-WDC_WD20EFRX-68EUZN0_WD-WCC4M7VPENJ5   ONLINE       0     0     0
	    ata-WDC_WD60EFRX-68MYMN1_WD-WX51D6416058   ONLINE       0     0     0

errors: Permanent errors have been detected in the following files:

        <0x2e5>:<0x83a1>

so - which files are affected ?

### Describe how to reproduce the problem
the problem happend while replacing a dead disk and while resilvering, another disk died

**Comment by devZer0** [comment]
i just found this is a dupe of https://github.com/zfsonlinux/zfs/issues/7669

**Comment by ahrens** [comment]
Yes, this is a dup of #7669
