### ISSUE TITLE
zfs 0.7.9 panic for RHEL 6 kernel 2.6.32-754.2.1.el6.x86_64

### ISSUE THREAD

**Issue by stuartthebruce** [zfsonlinux/zfs#7704]
### System information
Type | Version/Name
 --- | --- 
Distribution Name	|  Scientific Linux
Distribution Version	|  6
Linux Kernel	|  2.6.32-754.2.1.el6.x86_64
Architecture	|  x86_64
ZFS Version	|  0.7.9
SPL Version	|  0.7.9

Loading the the 0.7.9 zfs kernel module crashes the latest RHEL 6 kernel (2.6.32-754.2.1.el6.x86_64).

This can be reproduced be booting to the latest kernel, yum install zfs (from zfs-kmod), and modprobe zfs.

I have rebooted to a previous kernel, removed the new kernel and zfs, rebooted, re-installed the updated kernel, successfully rebooted to the new kernel, and then after yum install zfs appears to succeed the system will crash when I attempt to load the zfs kernel module or if I simply reboot with zfs installed.

**Comment by ak100** [comment]
Did you install rpms from kmod-zfs area or DKMS?

It looks like zfs-0.7.9 rpm  (KMOD) was built against the older kernel:
$ rpm -qlp kmod-zfs-0.7.9-1.el6.x86_64.rpm 
...
/lib/modules/2.6.32-696.23.1.el6.x86_64/extra/zfs
...

RHEL modules supposed to be compatible (kABI-tracking) but sometimes they are not and you can't load zfs kernel module built for the other kernel. 

You may want try to rebuild zfs/spl rpms for your new kernel.

**Comment by stuartthebruce** [comment]
I used kmod-zfs. I was hoping that if there was an incompatibility that would have been caught before a kernel panic.

**Comment by stuartthebruce** [comment]
What is the best way to tell when the zfs-kmod repo for RHEL 6 has been updated to the latest upstream kernel release?

**Comment by stuartthebruce** [comment]
Is there a better place to report that kmod-zfs-0.7.9-1.el6.x86_64.rpm built against kernel 2.6.32-696.23.1.el6.x86_64 panics when loaded on kernel 2.6.32-754.2.1.el6 ?

**Comment by dmytroleonenko** [comment]
Hit the same issue. Still no fix in the repo? sad

**Comment by stuartthebruce** [comment]
Is there another forum to contact the RHEL6 kmod-zfs repo maintainer?

**Comment by brissonpat** [comment]
Same problem with the latest kernel 2.6.32-754.3.5.el6.x86_64.

**Comment by behlendorf** [comment]
Sorry about the delay.  New zfs-0.7.9-2 packages have been added to the repository which were built against the 2.6.32-754.2.1.el6.x86_64 kernel.

**Comment by rob-c** [comment]
Just experienced the same problem upgrading to 2.6.32-754.3.5.el6.x86_64 (from 2.6.32-696.18.7).
My system hung and refused to boot.

The solution was to drop back to the old kernel then manually remove all extra and weak_updates modules to force dkms to rebuild correctly for the latest -754 version. After rebooting everything came back without issue.
