### ISSUE TITLE
master vs. newest tag 

### ISSUE THREAD

**Issue by c3ph3us** [zfsonlinux/zfs#7707]
i have some questrion regardless this project as its wiki is poor: 

I.

could someone from dev explain me how is get a master branch (META 0.7.0) in which some changes are made (Latest commit 2dca37d on 7 Aug 2017) to tag 0.7.9 (Latest commit d1ed1be on 8 May)?  how master is diiferent from 0.7.9 tag (yes i can diff myself)  because normally i would consider a tag  0.7.9 as an ANCESTOR  of master but im confused from master  (META 0.7.0) ???  shoul it not have same version 0.7.9 or next one 0.7.9+ or 0.7.10? 

 II. 

are ou consider to do anything regardless the native ZFS encryption feature 
or this is a **BEARLY ZFS on linux   -> in short BZOL :)**??? 

best 
ceph3us

**Comment by rincebrain** [comment]
@c3ph3us As the wiki says, "Please contact us via the mailing list if you aren't certain that you are experiencing a bug."

"Not understanding how git is being used" is not a bug. Ask on IRC or the mailing list if you have questions.

"Issue template and contributing guidelines also break" is, without more information, not a useful bug.

"No one read" is just outright false.

**Comment by mschilli87** [comment]
@rincebrain 
> "Issue template and contributing guidelines also break" is, without more information, not a useful bug.
> 
> "No one read" is just outright false.

I'd interpret this as sarcasm. :wink:

**Comment by rageagainstthebugs** [comment]
@rincebrain Yes, very thanks PMT.

**Comment by gmelikov** [comment]
Closed, please use mailing lists for support questions.

And next time please don'j just remove our issue template.
