### ISSUE TITLE
Getting "Permission denied" error when trying to delete a snapshot by the same user who created it (and the permissions are ok)

### ISSUE THREAD

**Issue by flixman** [zfsonlinux/zfs#7716]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Debian
Distribution Version	| Testing
Linux Kernel	| 4.16.3
Architecture	| x86_64
ZFS Version	| 0.7.9
SPL Version	| 0.7.9

### Describe the problem you're observing
I have given the following permissions to a non admin user:

     ---- Permissions on zfsdata ------------------------------------------
     Local+Descendent permissions:
         user nonadmin destroy,hold,send,snapshot,userprop

With that user, I can create snapshots, but when destroying them I get
cannot destroy snapshots: permission denied

I assume I am doing something wrong but I do not manage to see why :/

### Describe how to reproduce the problem
1. Set up the permissions for a restricted user

    \# zfs allow nonadmin destroy,hold,send,snapshot,userprop zfsdata
2. Logged in as that user, create a snapshot and try to remove it:

     % zfs snapshot zfsdata/srv@kk
     % zfs list -t snapshot | grep kk
         zfsdata/srv@kk                                0B      -  1.42G  -
     % zfs destroy zfsdata/srv@kk
         cannot destroy snapshots: permission denied

**Comment by bunder2015** [comment]
Could give this a try

```
       destroy          subcommand     Must also have the 'mount' ability
```

However this might still not work because the mount ability doesn't quite work on linux.

**Comment by flixman** [comment]
Yes! it worked! Thank you :-)
