### ISSUE TITLE
Cannot enumerate files or directories 

### ISSUE THREAD

**Issue by chrisdelrey** [zfsonlinux/zfs#7721]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| CentOS
Distribution Version	| 7.5
Linux Kernel	| 3.10.0-862
Architecture	| x86_64
ZFS Version	| 0.6.5.7-1
SPL Version	| 0.6.5.7-1

### Include any warning/errors/backtraces from the system logs
after rebooting or remounting, df was now reflecting what looks to reflect space saved from the mass file deletion though now ls cannot enumerate or read any zpools. the only error i get is ls: reading directory /tank: Not a directory

**Comment by rincebrain** [comment]
That version is quite old, I'd suggest trying again on an 0.7.X version.

What does stat say on /tank, hopefully after trying a newer version?

**Comment by rageagainstthebugs** [comment]
This not be zfs bug, ls is not correct tool for enumerate zpools

**Comment by behlendorf** [comment]
This enumeration issue is the result of a RHEL 7.5 kABI change which was resolved in the 0.7.x series.  The pool is fine, but you'll want to either update to the latest packages from the repo, rollback the RHEL 7.4 kernel, or cherry pick the fix from https://github.com/zfsonlinux/zfs/pull/7833.

**Comment by chrisdelrey** [comment]
I should have updated the case, after updating the packages to .7 all is
good now.

Thanks for the reply!
Chris
