### ISSUE TITLE
ZFS zvol does not unallocate discarded blocks

### ISSUE THREAD

**Issue by c0d3z3r0** [zfsonlinux/zfs#7722]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Debian
Distribution Version	| 9
Linux Kernel	| 4.9.0-6-amd64
Architecture	| amd64
ZFS Version	| 0.7.9-3
SPL Version	| 0.7.9-3

### Describe the problem you're observing

Setup: ext4 (discard enabled)-> luks (discard enabled) -> zvol -> raidz1
(I do not want to use native encryption now!)

ZFS zvol does not unallocate discarded blocks.

### Describe how to reproduce the problem

- Set up disks: ext4 (discard enabled)-> luks (discard enabled) -> zvol -> raidz1
- Create some large files with `dd if=/dev/random`, then delete them
- optional / does not make a difference: run fstrim on ext4 volume
- sync;sync
- Check allocated size by `zfs list`

### Include any warning/errors/backtraces from the system logs

```
root@debian:~# zpool status zpool_data
  pool: zpool_data
 state: ONLINE
  scan: scrub repaired 0B in 0h8m with 0 errors on Tue Jul 17 12:01:40 2018
config:

	NAME                                                    STATE     READ WRITE CKSUM
	zpool_data                                              ONLINE       0     0     0
	  raidz1-0                                              ONLINE       0     0     0
	    ata-HGST_HTS721010A9E630_JR1000BN0S8TTE             ONLINE       0     0     0
	    ata-HGST_HTS721010A9E630_JR1000BN0T69VE             ONLINE       0     0     0
	    ata-HGST_HTS721010A9E630_JR1000BN0T69WE             ONLINE       0     0     0
	    ata-HGST_HTS721010A9E630_JR1000BN0TEJBE             ONLINE       0     0     0
	logs
	  ata-Samsung_SSD_840_PRO_Series_S1ANNSAF522891V-part3  ONLINE       0     0     0

errors: No known data errors
root@debian:~# zpool list zpool_data
NAME         SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
zpool_data  3.62T  76.8G  3.55T         -     0%     2%  1.00x  ONLINE  -
```

**Comment by ahrens** [comment]
You should check the allocated size in `zfs list` after running `zpool sync` to ensure that all ZFS changes have been written to disk and ZFS's space accounting has been updated.

Do I understand correctly that you are storing files in an ext4 filesystem, which is on top of LUKS, which is on top of a ZVOL, which is in a storage pool which uses RAIDZ2 on top of physical disks?

FYI, we'd normally draw the arrows in the opposite direction, from a component to the component that it depends on (e.g. ext4 -> luks -> zvol -> raidz2).

Also FYI, your output shows a RAIDZ1 pool but you mentioned RAIDZ2.  I'll assume that's just a typo but wanted to make sure you got the output from the right system.

I'm not that familiar with the zvol code on ZoL, but it does appear to have support for discard.  I'm not sure where the discard would be getting dropped.
```
zvol_request(struct request_queue *q, struct bio *bio)
...
	if (rw == WRITE) {
...
		if (bio_is_discard(bio) || bio_is_secure_erase(bio)) {
			if (zvol_request_sync || need_sync ||
			    taskq_dispatch(zvol_taskq, zvol_discard, zvr,
			    TQ_SLEEP) == TASKQID_INVALID)
				zvol_discard(zvr);
```

**Comment by c0d3z3r0** [comment]
> Do I understand correctly that you are storing files in an ext4 filesystem, which is on top of LUKS, which is on top of a ZVOL, which is in a storage pool which uses RAIDZ2 on top of physical disks?

Exactly

> FYI, we'd normally draw the arrows in the opposite direction, from a component to the component that it depends on (e.g. ext4 -> luks -> zvol -> raidz2).

Fixed in first post

> Also FYI, your output shows a RAIDZ1 pool but you mentioned RAIDZ2. I'll assume that's just a typo but wanted to make sure you got the output from the right system.

Typo fixed in first post. It's raidz1 indeed.

> I'm not that familiar with the zvol code on ZoL, but it does appear to have support for discard. I'm not sure where the discard would be getting dropped.

>You should check the allocated size in zfs list after running zpool sync to ensure that all ZFS changes have been written to disk and ZFS's space accounting has been updated.

No difference after `zpool sync`. Allocated space in `zfs list` and `zpool list` is more or less about the same.

**Comment by c0d3z3r0** [comment]
I did some more tests without luks which seemed to work correctly... there must be a problem with luks.
I'm sorry for all that noise. Closing this for now.

**Comment by c0d3z3r0** [comment]
@gmelikov sure. I'll give an update after some more testing

**Comment by beren12** [comment]
Are you sure you enabled discard in LUKS?

You can enable discard by editing the /etc/crypttab file and rebuilding your initramfs, or pass a kernel boot argument rd.luks.options=discard if you use systemd. You'll need to see how to format crypttab in the man page, could be

luks-blah-blah-blah UUID=blah-blah-blah none allow-discards
or
luks-blah-blah-blah UUID=blah-blah-blah none luks,discard  <-likely debian way

**Comment by c0d3z3r0** [comment]
@beren12 Yes but I didn't use crypttab but cryptsetup itself for testing with `--allow-discards`

I could not reproduce the issue again... I have absolutely no clue what went wron during my first tests but everything is fine now.
