### ISSUE TITLE
Dracut package must install awk

### ISSUE THREAD

**Issue by Rudd-O** [zfsonlinux/zfs#7729]
```
[yes_no_RPMs_27]    DEBUG:    VM.console:                 run@ 304	[   16.575509] dracut-pre-mount[219]: //lib/dracut/hooks/pre-mount/90-zfs-load-key.sh: line 36: awk: command not found
```

This is not good.  The Dracut module must install `awk` in the initial RAM disk, and the `-dracut` RPM package must specify a dependency on `awk`.

**Comment by behlendorf** [comment]
Opened #7747 with a proposed fix.

**Comment by behlendorf** [comment]
@Rudd-O the final code has been integrated with master to resolve this.

**Comment by Rudd-O** [comment]
You are awesome.  Thanks.
