### ISSUE TITLE
Kernel 4.17 compatibility?

### ISSUE THREAD

**Issue by Bronek** [zfsonlinux/zfs#7730]
I plan to upgrade to kernel 4.17, since 4.16 is now EOL. However ZOL version 0.7.9 is not supported under the new kernel version - should I go ahead and upgrade nevertheless, or would it be better to wait for the next release of ZOL?

Thank you for all your hard work!

**Comment by nilsmeyer** [comment]
0.7.9 works fine for me on 4.17. If for some reason it doesn't work just keep your old kernel around.

**Comment by brando56894** [comment]
Currently using ZoL on **4.17.6-200.fc28.x86_64** with no issues.

**Comment by behlendorf** [comment]
I've updated the release notes for 0.7.9 to indicated the 4.17 kernel is supported.  The kernel was released after 0.7.9 was tagged so it wasn't a sure thing when it was published.
