### ISSUE TITLE
Wiki: Debian Root on ZFS example never mounts /var/*

### ISSUE THREAD

**Issue by johnkeates** [zfsonlinux/zfs#7770]
In the example/instruction on https://github.com/zfsonlinux/zfs/wiki/Debian-Stretch-Root-on-ZFS, the canmount=off  setting on var causes none of the var mount points to exist or be used.

Manually specifying the mountpounts or overriding canmount works but doesn't seem to be right.

Specific part:
```
# zfs create -o canmount=off -o setuid=off  -o exec=off rpool/var
# zfs create -o com.sun:auto-snapshot=false             rpool/var/cache
# zfs create                                            rpool/var/log
# zfs create                                            rpool/var/spool
# zfs create -o com.sun:auto-snapshot=false -o exec=on  rpool/var/tmp
```

**Comment by gmelikov** [comment]
@johnkeates thank you for help, but `canmount` won't be inherited in this case, tested on 0.7.9.

Closed.

**Comment by gmelikov** [comment]
@johnkeates there was a problem with mount priority though, which may be a problem in this case.
