### ISSUE TITLE
Linux 4.18 support should be backported to 0.7.y

### ISSUE THREAD

**Issue by ryao** [zfsonlinux/zfs#7785]
I have done the work to backport it for Gentoo, so it just needs to be cherry-picked and put into a release:

https://github.com/ryao/spl/tree/spl-0.7.9-gentoo
https://github.com/ryao/zfs/tree/zfs-0.7.9-gentoo

https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=02cc5b66b7067ab32903ee3eabfeb3a9f65ec917

**Comment by mskarbek** [comment]
Please do even as a small sub-release like 0.7.9.1 without any other changes.

**Comment by arda2012** [comment]
+1 for the 0.7.9.1 sub-release. The reason I decided to use zfsonlinux was the fact that new kernels have always been supported upon release. Congratulations to tonyhutter for the baby. I understand well that you have other things to do now then working on zfsonlinux. Therefor I think a quick sub-release containing only the 4.18 support would be the way to go.

**Comment by tonyhutter** [comment]
Thanks @ryao, I'll pull these in.

**Comment by tonyhutter** [comment]
I'm putting together some 0.7.10 patchsets here:
ZFS: https://github.com/zfsonlinux/zfs/pull/7792
SPL: https://github.com/zfsonlinux/spl/pull/707

**Comment by loli10K** [comment]
Linux 4.18 is supported in zfs-0.7-release branch.
