### ISSUE TITLE
pyzfs missing support for recent libzfs_core functions

### ISSUE THREAD

**Issue by don-brady** [zfsonlinux/zfs#7793]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Ubuntu
Distribution Version	| 18.04
Linux Kernel	| 4.15
Architecture	| x86_64
ZFS Version	| master
SPL Version	| 

### Describe the problem you're observing
Recently added `libzfs_core` functions are missing from pyzfs
```
lzc_remap
lzc_pool_checkpoint
lzc_pool_checkpoint_discard
```

### Describe how to reproduce the problem
examine `./contrib/pyzfs/libzfs_core/__init__.py`

**Comment by loli10K** [comment]
I can probably take a stab at this in the upcoming weekend if no one else is already working on it.
