### ISSUE TITLE
[RFE] udev rule to add zvol partitions to /dev/disk/by-partuuid

### ISSUE THREAD

**Issue by mskarbek** [zfsonlinux/zfs#7811]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Fedora
Distribution Version	| 28
Linux Kernel	| 4.16.16-300.fc28
Architecture	| x86_64
ZFS Version	| 0.7.9-1
SPL Version	| 0.7.9-1

### Describe the problem you're observing
Currently `60-zvol.rules` creates symlinks only in `/dev/zvol` directory. It would be nice to also have links at least in `/dev/disk/by-partuuid` and maybe `/dev/disk/by-uuid` for partitions created on `zvol`.

**Comment by behlendorf** [comment]
@mskarbek I'd be happy to review any additional udev rules you want to propose which add the missing zvol partition links.

**Comment by mskarbek** [comment]
I have proposed a change to the `60-persistent-storage.rules` in systemd-udev (https://github.com/systemd/systemd/pull/9945). It will be a much cleaner approach. ;) If systemd will not accept then I'll just copy-and-paste relevant parts of that rule to `60-zvol.rules`.

**Comment by mskarbek** [comment]
Closing. Fixed in https://github.com/systemd/systemd/pull/9945.
