### ISSUE TITLE
"make deb" fails due to "error: bad date in %changelog

### ISSUE THREAD

**Issue by krichter722** [zfsonlinux/zfs#7825]
### System information
Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu
Distribution Version	| 18.04
Linux Kernel	| 4.15.0-33-generic
Architecture	| amd64
ZFS Version	| zfs-0.7.0-1695-g55972a672
SPL Version	| ./.

### Describe the problem you're observing
`./autogen.sh && ./configure && make && make pkg-dkms` fails due to

```
error: bad date in %changelog: Fr Aug 24 2018 Brian Behlendorf <behlendorf1@llnl.gov> 0.7.0-1527_g55972a672
Makefile:1255: recipe for target 'srpm-common' failed
make[1]: *** [srpm-common] Error 1
make[1]: Verzeichnis „/var/tmp/zfs“ wird verlassen
Makefile:1211: recipe for target 'srpm-dkms' failed
make: *** [srpm-dkms] Error 2
```

This is very similar to https://github.com/zfsonlinux/spl/issues/663 whose workaround to specify `LC_TIME=C` doesn't work (the workaround worked for older versions of spl, but no longer worked in for later versions before spl was integrated into the zfs repository).

### Describe how to reproduce the problem
Build with the above command on Ubuntu 18.04.

### Include any warning/errors/backtraces from the system logs
You can find the complete build log attached.
[build.log](https://github.com/zfsonlinux/zfs/files/2318014/build.log)

experienced with zfs-0.7.0-1695-g55972a672

**Comment by h1z1** [comment]
Probably won't matter much but throwing a vote in to keep changelog as the bulk of systems I deal with are rpm based.  It's helpful to know what version a spec file was used for and more importantly when it was last updated.  Is this not more a problem with debian?

**Comment by mskarbek** [comment]
@h1z1 `%changelog` in current form doesn't matter, it was "broken" anyway. In a proper changelog, you have to keep all the previous entries - currently, the changelog has only one autogenerated at the time of build.
