### ISSUE TITLE
zfs-auto-snapshot

### ISSUE THREAD

**Issue by ziyaul121** [zfsonlinux/zfs#7845]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Centos 7
Distribution Version	| CentOS Linux release 7.4.1708 (Core)
Linux Kernel	| 3.10.0-693.21.1.el7.x86_64
Architecture	| x86_64
ZFS Version	|  version:        0.7.9-1
SPL Version	|  version:        0.7.9-1

### Describe the problem you're observing

Recently I have configured ZFS in centos 7 and everything configured fine but whenever I try to configure auto snapshot than zfs-auto-snapshot command not available.
]# whereis zfs-auto-snapshot
zfs-auto-snapshot:

**Comment by ziyaul121** [comment]
This is new for me. Please help me to configure.

**Comment by ziyaul121** [comment]
Thanks

**Comment by gmelikov** [comment]
@ziyaul121 zfs-auto-snapshot must be installed separately, it's not included in zfs packages https://github.com/zfsonlinux/zfs-auto-snapshot

**Comment by ziyaul121** [comment]
Thanks a lot @gmelikov . got it.
