### ISSUE TITLE
Trying to build the 'zhack' disable feature commit from a few years ago

### ISSUE THREAD

**Issue by RNCTX** [zfsonlinux/zfs#7861]
Hello, as referenced by others like this issue [here](https://github.com/zfsonlinux/zfs/issues/6001), I have a pool that was mistakenly upgraded under Linux that needs to go back to FreeBSD.  Unfortunately userobj_accounting is enabled, which means that FreeBSD won't take the pool due to an unsupported feature.

I saw mention of [this commit](https://github.com/zfsonlinux/zfs/commit/83025286175d1ee1c29b842531070f3250a172ba) enabling feature disable functionality.  I grabbed a Ubuntu 14.04 boot disk and installed ZoL (and an SPL from about that time) from that pull request, but am still getting reference to userobj_accounting being an "unsupported feature" when I try to import the pool.

I'm not sure if the pool should be mounted or not?

With the pool exported, trying zhack returns:

```
root@ubuntu:~/zfs# zhack feature disable media org.zfsonlinux:userobj_accounting
zhack: feature 'org.zfsonlinux:userobj_accounting' is active, can not disable
```

**Comment by loli10K** [comment]
Why are you ignoring both rules and requests (https://github.com/zfsonlinux/zfs/issues/6466#issuecomment-320420368)? Please use the issue template if you found a bug, otherwise ask the mailing lists (https://github.com/zfsonlinux/zfs/wiki/Mailing-Lists).

Thank you for your cooperation.

**Comment by RNCTX** [comment]
The question I asked was in regard to the lead developer of this project making a patch for himself to use on a catch22 in feature flags, and therefore not addressed to you.  Nor is it addressed to anyone else that is using a current version of this software, since the relevant patch is over three years old (and now deprecated).

> Thank you for your cooperation.

What makes you think I'm agreeing with anything you typed?  Don't thank me, I'm not.

Thank *you*, for nothing.
