### ISSUE TITLE
kernel:[ 1097.965828] PANIC at zio.c:246:zio_data_buf_alloc()

### ISSUE THREAD

**Issue by Teutates3000** [zfsonlinux/zfs#7862]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  OpenMediaVault (Debian 8.11)
Distribution Version	|  3.0.94
Linux Kernel	|  4.9.0-0.bpo.6-amd64
Architecture	|  x86_64
ZFS Version	|  0.6.5.9-5~bpo8+1
SPL Version	|  0.6.5.9-1~bpo8+1

### Describe the problem you're observing
I have a raidz6 with 8 discs of 3TB and I had to change one of the discs that was defective. The manufacturer sent me a 4TB disc in exchange for my 3TB dead under warranty, I changed it as I have already done several except that I hung the wrong key and I executed the following command:
zpool replace -f -o ashift=6 MediaRaidZ6 /dev/disk/by-id/ata-ST3000VN007-2E4166_Z6A0D9NL-part1 /dev/disk/by-id/ata-ST4000VN008-2DR166_ZDH45MX7
While my ashift should be at 9 and I got the following error :
```
Message from syslogd@NAS at Aug 23 15:30:58 ...
 kernel:[ 1097.965714] VERIFY3(c < (1ULL << 24) >> 9) failed (65535 < 32768)

Message from syslogd@NAS at Aug 23 15:30:58 ...
 kernel:[ 1097.965828] PANIC at zio.c:246:zio_data_buf_alloc()
```
And since then I can no longer import :
```
root@NAS:~# zpool import MediaRaidZ6

Message from syslogd@NAS at Sep  4 17:19:44 ...
 kernel:[ 6203.976821] PANIC: blkptr at ffff9cd356a9ba40 has invalid PSIZE 33554432
```

### Describe how to reproduce the problem
Not replicable

**Comment by loli10K** [comment]
This was fixed more than a year ago (with https://github.com/zfsonlinux/zfs/commit/ff61d1a4959065aa99d52489438f6737765987c6). Fix is already included in the latest stable release.

**Comment by Teutates3000** [comment]
The problem is that I can't reproduce the problem on a more recent version (Debian 9) because I can't import my volume anymore.
I now have the following error all the time :
```
kernel:[ 6203.976821] PANIC: blkptr at ffff9cd356a9ba40 has invalid PSIZE 33554432
```
I found the information that I could use the script here : https://gist.github.com/jshoward/5685757
but I don't understand how it works.

**Comment by loli10K** [comment]
The initially reported issue has been fixed for a long time, i am going to close this.

Any new and different issue should probably merit its own bug report so we can debug it properly.
