### ISSUE TITLE
zfs stuck sometimes

### ISSUE THREAD

**Issue by woquflux** [zfsonlinux/zfs#7874]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Redhat 
Distribution Version	| 7.2
Linux Kernel	| 3.10.0-327
Architecture	| 
ZFS Version	| 0.6.4.2
SPL Version	| 0.6.4.2

### Describe the problem you're observing

In the case of high-pressure continuous writes, the io of zfs sometimes becomes extremely low, and the application will also be suspended and cannot continue to be written.
### Describe how to reproduce the problem

High pressure continuous write
### Include any warning/errors/backtraces from the system logs

![_93d37aca-8bda-48fe-abb8-a1979e9f96fc](https://user-images.githubusercontent.com/30719174/45208545-65b93600-b2bd-11e8-94cc-fe0c57084095.png)
![_82d711b4-9943-4c26-bf64-45b9e40d52d3](https://user-images.githubusercontent.com/30719174/45208548-6b168080-b2bd-11e8-9d9d-050d39377c18.png)
![_70ca62de-9bf9-431c-b8f9-0875b3e946cc](https://user-images.githubusercontent.com/30719174/45208553-6e117100-b2bd-11e8-84d2-cf4c2f8d8097.png)
![_549c5666-3454-4c0b-a9e7-f5a799fc7e9b](https://user-images.githubusercontent.com/30719174/45208570-77024280-b2bd-11e8-965d-0a3a0a6f1cfa.png)

```
options zfs zfs_arc_shrink_shift=14
options zfs zfs_prefetch_disable=1
options zfs zfs_nocacheflush=1
options zfs zfs_dirty_data_max=2147483648
options zfs zfs_dirty_data_max_max=4294967296
options zfs zfs_vdev_async_write_max_active=15
options zfs zfs_vdev_async_write_min_active=5
options zfs zfs_vdev_scheduler=deadline
options zfs zfs_vdev_async_write_active_min_dirty_percent=20
options zfs zfs_arc_meta_limit=21474836480
```

**Comment by drescherjm** [comment]
If you can upgrade your version 0.6.4.2 is pretty old.

**Comment by rincebrain** [comment]
Yeah, 0.6.4.2 is about 3.5 years old, there have been so many things changed since then I can't even count them all.

**Comment by woquflux** [comment]
OK，I had upgraded version
