### ISSUE TITLE
txg_sync writing huge amount of io

### ISSUE THREAD

**Issue by Alkeryn** [zfsonlinux/zfs#7879]
so i just learned how to use zfs and installed it on root today
an issue that i have is that txg_sync is writting most of the time
at like 100mB /s on my brand new ssd (samsung 960 pro nvme)
it have been less than a day and already a whole terabyte have been written to the disk
so how can i stop that, if i don't have a solution i will have no other choice than reinstalling on another fs
also for some reason when i start my qemu vm (in which the vm.qcow partition) is on another disk
the nvme write speak start to peak again

**Comment by kpande** [comment]
please don't ignore the template that tells you the required information for issue reports.

but this is not an issue report, it is a support request, which is more suited for IRC or [the zfs-discuss mailing list](http://list.zfsonlinux.org).
