### ISSUE TITLE
Man page - zpool Special Allocation Class, not removable?

### ISSUE THREAD

**Issue by Lady-Galadriel** [zfsonlinux/zfs#7880]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Gentoo
Distribution Version	| Rolling
Linux Kernel	| 4.14.65-gentoo
Architecture	| AMD64
ZFS Version	| 0.8.0-rc1
SPL Version	| 0.8.0-rc1

### Describe the problem you're observing
While reading about and testing new ZFS features, (checkpoints & metadata special vDevs), I found that the zpool man page entry for `Special Allocation Class` was missing a comment that it's not removable. (If it / they are removable, then the `zpool remove` section should be updated to include that information.)

The fix is pretty straight forward.

### Describe how to reproduce the problem
`man zpool`

### Include any warning/errors/backtraces from the system logs

ZFS source was sync'ed Sept. 8, 2018 about 4pm US/Central.

**Comment by behlendorf** [comment]
Devices added to the special allocation classes can be removed as long as they're configured as a mirror or individual disk.  This is mentioned in the man page, but I can see how this could be confusing since it's not made clear that they're consider to be part of the primary pool storage.


```
     zpool remove [-np] pool device...
             Removes the specified device from the pool.  This command cur‐
             rently only supports removing hot spares, cache, log devices and
             ___mirrored top-level vdevs (mirror of leaf devices); but not raidz___.
```

**Comment by kpande** [comment]
@behlendorf in general that distinction wasn't very obvious to me until @don-brady said that in his OpenZFS talk yesterday, i think it would be nice to make that more clear.

**Comment by behlendorf** [comment]
Proposed man page update in #7893 to clarify the restrictions.

```
     zpool remove [-np] pool device...
             Removes the specified device from the pool.  This command cur‐
             rently only supports removing hot spares, cache, log devices and
             mirrored top-level vdevs (mirror of leaf devices), including
             dedup and special vdevs.  When the primary pool storage includes
             a top-level raidz vdev only hot space, cache, and log devices may
             be removed.
```

**Comment by Lady-Galadriel** [comment]
Perfect. Thanks.
