### ISSUE TITLE
Add libaio-devel to Custom Package Wiki

### ISSUE THREAD

**Issue by olw2005** [zfsonlinux/zfs#7892]
Both of the current zfs releases (0.7.10 and 0.8.0-rc1) require libaio-devel.  The build process does provide a meaningful error (e.g. install libaio-devel).  But it's missing from the "yum install" instructions for RHEL derivatives and also the corresponding "apt-get" for Debian / Ubuntu.

**Comment by behlendorf** [comment]
Thanks for noticing, wiki updated.
