### ISSUE TITLE
nested bpobj causes leak of subobj

### ISSUE THREAD

**Issue by ahrens** [zfsonlinux/zfs#7908]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| illumos
Distribution Version	| 
Linux Kernel	| 
Architecture	| 
ZFS Version	| 
SPL Version	| 

### Describe the problem you're observing

After a `zfs destroy`, an object of type `bpobj subobj` remains allocated but not referenced.  This is reported by yet-to-be-upstreamed enhancements to zdb.

### Describe how to reproduce the problem

(updated 10/2/2018)
```
#!/bin/bash

zfs create -o compress=zle -o redundant_metadata=most -o recordsize=512 test/fs

# note, each 16K snapshots results in one layer of recursive bpobj subobj's
n=17000

echo creating file
dd if=/dev/urandom of=/test/fs/file conv=notrunc bs=$((512*100)) count=$((n/100))
zfs snapshot test/fs@first


for (( i=0; i<n; i=i+1 )); do
        echo $i
        dd if=/dev/zero of=/test/fs/file conv=notrunc bs=512 seek=$i count=1 >&/dev/null
        zfs snapshot test/fs@$i
        zfs destroy test/fs@$((i-1))
done

set -x

zdb -ddd test | grep subobj
zfs destroy test/fs@first
zdb -ddd test | grep subobj
```

output:
```
    $ zdb -ddd test | grep subobj
            83    1   128K   128K      0   128K    0.00  bpobj subobj
         26162    1   128K   128K   196K   256K  100.00  bpobj subobj
         30460    1   128K   128K     9K   128K  100.00  bpobj subobj
        Pool snapshot frees: object 11, 0 local blkptrs, 0 subobjs in object 83, 0 (0/0 comp)

    $ zfs destroy test/fs@first

    $ zdb -ddd test | grep subobj
            83    1   128K   128K      0   128K    0.00  bpobj subobj
         26162    1   128K   128K      0   128K    0.00  bpobj subobj
        Pool snapshot frees: object 11, 0 local blkptrs, 0 subobjs in object 83, 0 (0/0 comp)
    MOS object 26162 (bpobj subobj) leaked
```

Proposed fix (updated 9/17/2018):
```
diff --git a/usr/src/uts/common/fs/zfs/bpobj.c b/usr/src/uts/common/fs/zfs/bpobj.c
index a47bcd37dfe..fcb2989846d 100644
--- a/usr/src/uts/common/fs/zfs/bpobj.c
+++ b/usr/src/uts/common/fs/zfs/bpobj.c
@@ -352,6 +352,16 @@ bpobj_iterate_impl(bpobj_t *bpo, bpobj_itor_t func, void *arg, int64_t start,
                        bpo->bpo_phys->bpo_comp -= comp_before - comp_after;
                        bpo->bpo_phys->bpo_uncomp -=
                            uncomp_before - uncomp_after;
+
+                       if (err == 0 && sublist.bpo_havesubobj &&
+                           sublist.bpo_phys->bpo_subobjs != 0) {
+                               err = dmu_object_free(bpo->bpo_os,
+                                   sublist.bpo_phys->bpo_subobjs, tx);
+                               if (err != 0)
+                                       break;
+                               dmu_buf_will_dirty(sublist.bpo_dbuf, tx);
+                               sublist.bpo_phys->bpo_subobjs = 0;
+                       }
                }

                bpobj_close(&sublist);
```

See also https://github.com/zfsonlinux/zfs/pull/7675 and https://github.com/zfsonlinux/zfs/issues/7674

**Comment by PaulZ-98** [comment]
I'm unable to reproduce this with the script above.  It seems that during bpobj_enqueue, the (subobj == dp_empty_subobj) test is met, and the nested subobj arrangement is not created.

Running a different script, which creates 6000 snapshots and then destroys 1000..5400 does create a single "leg" of deeply nested bpobj, off of dp_free_bpboj (and blows out the stack).

Still would like to have a subobj somewhere in the hierarchy off dp_free_bpobj, that also has subobjs of its own.  Any thoughts on how to arrange that?

Also, if possible, I'd like to apply the zdb changes that print subobj and look for leaks.

**Comment by ahrens** [comment]
@PaulZ-98 I've updated the above script to work with gnu dd.  It reproduces for me on Ubuntu 18/04. 
 If you're still having trouble, try changing the `dd` line to not redirect to `/dev/null`, and see if it is giving you errors.

**Comment by PaulZ-98** [comment]
Confirmed with stock bits.  Got similar zdb output.  Now trying with non-recursive version.
