### ISSUE TITLE
Wiki: Git and GitHub for beginners

### ISSUE THREAD

**Issue by bunder2015** [zfsonlinux/zfs#7915]
### System information
Type | Version/Name
 --- | --- 
Distribution Name	| n/a
Distribution Version	| n/a
Linux Kernel	| n/a
Architecture	| n/a
ZFS Version	| n/a
SPL Version	| n/a

### Describe the problem you're observing
Occasionally we get pull requests from users who haven't used Git or GitHub before.  GitHub sometimes isn't the greatest platform for beginners, and could use better documentation, so I wrote a wiki article.  Posting for review and inclusion into the ZoL wiki.  https://github.com/bunder2015/zfs-wiki/blob/master/Git-and-GitHub-for-beginners.md

### Describe how to reproduce the problem
n/a

### Include any warning/errors/backtraces from the system logs
n/a

**Comment by GregorKopka** [comment]
I volunteer for beta-testing.

**Comment by bunder2015** [comment]
Thanks for giving it a go.  I didn't want to feel like I was singling you out as I made the same mistakes when I first started contributing, and in IRC conversations, it would appear to be a common problem for first-timers.  I hope it works for you, let me know if it gives you any problems so I can make adjustments.

**Comment by GregorKopka** [comment]
We've all been unfamiliar with basically everything at some point in time, it's only bad in case one dosn't _want_ to learn out of that state.

The manual seems to work, please take a look as [the result](https://github.com/zfsonlinux/zfs/pull/7916) - should it be what you wanted to archive with the manual: good work, please make sure it gets linked where new users will find if.

**Comment by bunder2015** [comment]
Looks good, thanks for testing, and thanks for the patch!

**Comment by behlendorf** [comment]
@bunder2015 thanks for putting this together, it's definitely a step in the right direction.  Why don't we updated the `CONTRIBUTING.md` to reference this new page and add it to the `Developer Resources` section of the wiki.

**Comment by gmelikov** [comment]
@bunder2015 thank you! I agree with @behlendorf , we may add it to wiki and create a reference in the `CONTRIBUTING.md`.

**Comment by GregorKopka** [comment]
@bunder2015 Could you please add a section about what to do in case a pull request needs to be updated (eg. because Buildbot complains) ?

**Comment by bunder2015** [comment]
Are you still having problems with your PR?  I added a couple blurbs about running checkstyle and re-pushing in case a PR needs to be corrected.

**Comment by GregorKopka** [comment]
Thanks. Had pieced that together eventually (hope Brian isn't that annoyed, as I messed up the branch in my fork in the process and found no way back, so I had to make new one). Other thing that could be helpful would be what to do when you forgot the --amend on an update (and possibly what to do when you forgot it bad enough so that you pushed that to your fork on github).

**Comment by GregorKopka** [comment]
@bunder2015 One thing regarding: https://github.com/zfsonlinux/zfs/wiki/Git-and-GitHub-for-beginners#maintaining-your-repository

wouldn't
```
git checkout master
git fetch upstream
git rebase upstream/master
git push origin master
```
not be better, as `git merge upstream/master` as 3rd step would add another commit (that then seems to get added to any branches created afterwards => ends up in pull requests) ?

**Comment by bunder2015** [comment]
Afraid not, you would get stuck carrying around an empty "merge x into master" commit which clogs up the git log.

**Comment by GregorKopka** [comment]
> Afraid not, you would get stuck carrying around an empty "merge x into master" commit which clogs up the git log.

That's exactly the problem I have when using `git merge upstream/master` as 3rd step 'for maintaining your repository' (as it's currently on the wiki) - only when I use `rebase` instead I don't end up with an extra `merge x into master` commit.

**Comment by bunder2015** [comment]
I'm afraid I don't see that here.  I just updated my local copy and this was the output using that exact script:
```
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Total 15 (delta 12), reused 12 (delta 12), pack-reused 3
Unpacking objects: 100% (15/15), done.
From https://github.com/zfsonlinux/zfs
   145c88fb7..dda550085  master     -> upstream/master
Updating 145c88fb7..dda550085
Fast-forward
 man/man8/zpool.8       |  2 +-
 module/zfs/spa_misc.c  | 23 ++++++++++++++++++++++-
 module/zfs/vdev_disk.c |  7 +++----
 3 files changed, 26 insertions(+), 6 deletions(-)
Username for 'https://github.com': bunder2015
Password for 'https://bunder2015@github.com':
Counting objects: 15, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (15/15), done.
Writing objects: 100% (15/15), 2.33 KiB | 2.33 MiB/s, done.
Total 15 (delta 13), reused 0 (delta 0)
remote: Resolving deltas: 100% (13/13), completed with 8 local objects.
To https://github.com/bunder2015/zfs.git
   145c88fb7..dda550085  master -> master
```
My GitHub copy at https://github.com/bunder2015/zfs looks fine as well.  Wish I could be of more help.

**Comment by behlendorf** [comment]
This may depend on the exact version of git.  Personally, my workflow largely matches what you suggested, though both should work as long as you're able to get a clean fast-forward.  Since I'm always working on a branch I tend to `git pull` the latest chances in to my local copy of master.  

Updating your repositories master branch, you'll never need to use `--force` for this.

```sh

git checkout master
git pull upstream master
git push origin master
```

Rebasing an existing local branch to updated a PR looks like.  Here you will need to use `--force` if you've done the rebase.

```sh
git checkout branch-name
git rebase -i master
git push --force origin branch-name
```

**Comment by GregorKopka** [comment]
@behlendorf 
@bunder2015 
```
git checkout master
git pull upstream master
git push origin master
```
works fine and dosn't create an empty commit (git version 2.13.6).

Remove the `git merge upstream/master` from https://github.com/zfsonlinux/zfs/wiki/Git-and-GitHub-for-beginners#maintaining-your-repository to avoid creating confusion (through empty commits)?

**Comment by kpande** [comment]
`git pull -r` will also pull while rebasing.

**Comment by bunder2015** [comment]
That seems to work on git 2.16.4, I updated the wiki with the new maintaining commands.  I can add a section on rebasing if we really need to, but I was hoping to not write an entire novel on using git.

**Comment by kpande** [comment]
i'm sure if you did, a few of us (but probably not all) would leave somewhat favourable reviews of your book on Amazon.
