### ISSUE TITLE
flake 8 style warnings

### ISSUE THREAD

**Issue by behlendorf** [zfsonlinux/zfs#7925]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| any
Distribution Version	| any
Linux Kernel	| any
Architecture	| any
ZFS Version	| zfs-0.8.0-rc1
SPL Version	| 

### Describe the problem you're observing

Current versions of flake8 report new new probably in the python scripts.  These need to be fixed for the `make checkstyle` target to pass cleanly.

```
$ flake8 --version
3.5.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 3.6.5 on Linux
```

### Describe how to reproduce the problem

On Ubuntu 18.08 with flake8 installed.

```
$ make checkstyle
./tests/test-runner/bin/zts-report.py:281:11: E999 SyntaxError: invalid syntax
./tests/test-runner/bin/test-runner.py:207:22: E999 SyntaxError: invalid syntax
./contrib/pyzfs/libzfs_core/test/test_libzfs_core.py:47:17: E999 SyntaxError: invalid syntax
Makefile:1566: recipe for target 'flake8' failed
make: *** [flake8] Error 1
```

### Include any warning/errors/backtraces from the system logs

N/A

**Comment by behlendorf** [comment]
Converting `zts-report.py` and `test-runner.py` to python 3 shouldn't be a huge issue, but there's a larger discussion to be had about `pyzfs`, see #7828.  Does anyone know if there's something we can do to allow flake8 to properly recognize those scripts as python2?

**Comment by bunder2015** [comment]
I didn't happen to see one in their documentation, however we can possibly `--ignore=E999` or `--exclude` the files in the interim.  Unfortunately I'm not very versed in python, I tried fixing some of them up by hand but I'm not sure if the scripts would still work as intended if I were to make a PR for it.  I think I'll leave this one for someone who knows more about python.
