### ISSUE TITLE
reported version is inaccurate

### ISSUE THREAD

**Issue by ahrens** [zfsonlinux/zfs#7931]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu
Distribution Version	| 
Linux Kernel	| 
Architecture	| 
ZFS Version	| ??
SPL Version	| 

### Describe the problem you're observing

The kernel reports the running module version in accurately, e.g. via `modinfo zfs`, `dmesg`, and `/sys/module/zfs/version`.  The reported version is determined when `configure` is run, rather than when the module is built.  Therefore incremental builds always report an inaccurate version, and thus it's impossible to know what bits you're really running.

### Describe how to reproduce the problem

`git commit...; make; make install; reboot; cat /sys/module/zfs/version`

### Recommended solution

Add a new .c file which is generated at compile time and contains a global variable with the git hash.  Replace uses of ZFS_META_ALIAS/RELEASE with this new variable.  (Note that we don't want to change `zfs_config.h` on every build, because it's included everywhere and thus incremental builds would recompile everything.)

**Comment by bunder2015** [comment]
Just curious, does this affect all distros or just debian/ubuntu?  Because they don't run the official packages, but rather they maintain their own source where they pick and choose what goes into it.

**Comment by drescherjm** [comment]
I believe this is just when you build using git to pull in the source code. configure long ago and update the git. and compile. If you don't run configure again in your build process it keeps the old version. On gentoo I don't see this because I am using the ebuild that clones the git each time.

**Comment by bunder2015** [comment]
Ah okay, I think I get it now.  Thanks for clarifying.

**Comment by ahrens** [comment]
https://github.com/zfsonlinux/zfs/pull/7965 provides a workaround for this: use /proc/sys/kernel/spl/gitrev and ignore the git hash in /sys/module/zfs/version and friends.  Given that, we may be able to change the recommended solution to instead remove the git hash from the versions reported here.  That way we fully separate the "release version" (which has requirements based on packaging, kernel module infrastructure, etc) from the git hash (which is primarily for developer use).
