### ISSUE TITLE
zpool iostat -l returns unrealistically low latency values

### ISSUE THREAD

**Issue by shodanshok** [zfsonlinux/zfs#7935]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| CentOS
Distribution Version	| 7.5.1804
Linux Kernel	| 3.10.0-862.11.6.el7.x86_64
Architecture	| x86_64
ZFS Version	| 0.7.11-1
SPL Version	| 0.7.11-1

### Describe the problem you're observing
`zpool iostat -l` reports unrealistically low latency values

### Describe how to reproduce the problem
```
[root@localhost ~]# zpool iostat -l
              capacity     operations     bandwidth    total_wait     disk_wait    syncq_wait    asyncq_wait  scrub
pool        alloc   free   read  write   read  write   read  write   read  write   read  write   read  write   wait
----------  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----
tank         983G  2.67T      4     91   267K  3.24M  881ns   56ns  553ns   16ns   42ns      -    1us   50ns  175ns

```
As you can see, all latency number are expressed in `ns` - but this is a SATA based machine, with 4x 7200 RPM HDDs and 2x Samsung 850 Evo SSDs as L2ARC/SLOG. In other words, we have absolutely zero chances to really have these low latencies.

Rather, what `zpool iostat -l` seems to do is to include inactive/dead time into accounting - ie: if having a 15ms instantaneous latency value followed by 5s of inactivity, the latency number is the averate between 1x 15ms and ~5000x 0ms. You can rightfully argue that this *is* the very meaning of average. However, I feel that excluding inactive time is key to get meaningful latency numbers.

**Comment by GregorKopka** [comment]
Possibly similar cause as in https://github.com/zfsonlinux/zfs/issues/7694.

**Comment by shodanshok** [comment]
You are right. I'll continue on the original thread, closing this issue as duplicate.
