### ISSUE TITLE
kmod-spl-0.7.11-1.el7_4.x86_64 kABI-tracking RPM in EL7.4 repo depends on EL7.5 kernel

### ISSUE THREAD

**Issue by nathans** [zfsonlinux/zfs#7956]
Since the 0.7.11 RPMs were released, the RPMs in the EL7.4 kABI-tracking repository (e.g. http://download.zfsonlinux.org/epel/7.4/kmod/) appear to be built for Centos 7.5 kernels.

This is on:
Centos 7.4.1708
Linux: 3.10.0-693.21.1.el7.x86_64

Here is the relevant error text from yum when attempting an install:
```
--> Processing Dependency: kernel(sme_me_mask) = 0x17fbce60 for package: kmod-spl-0.7.11-1.el7_4.x86_64
--> Finished Dependency Resolution
Error: Package: kmod-spl-0.7.11-1.el7_4.x86_64 (zfs)
           Requires: kernel(sme_me_mask) = 0x17fbce60
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

And this is reflected in the yum info for the new package:
```
Available Packages
Name        : kmod-spl
Arch        : x86_64
Version     : 0.7.11
Release     : 1.el7_4
Size        : 114 k
Repo        : zfs
Summary     : spl kernel module(s)
URL         : http://zfsonlinux.org/
License     : GPLv2+
Description : This package provides the spl kernel modules built for
            : the Linux kernel 3.10.0-862.11.6.el7.x86_64 for the x86_64
            : family of processors.
```
**3.10.0-862** is the kernel version for Centos 7.5, while **3.10.0-693** is the version for 7.4.

This changed since last week, when I successfully installed 0.7.9 packages from the 7.4 kmod repo onto 7.4 systems.

Is it possible for the 0.7.11 packages in the 7.4 repo to correctly target the 7.4 kernel? Otherwise it would be best to have the 0.7.9 packages back, or nothing at all.

Steps to reproduce:

1. Install a Centos-7.4 system (use 7.4 vault repo instead of live Centos mirrors to avoid upgrade to 7.5)
2. Install the [ZFS release for EL7.4](http://download.zfsonlinux.org/epel/zfs-release.el7_4.noarch.rpm)
3. Disable the [zfs] repo and enable the [zfs-kmod] repo
4. Attempt to install zfs

**Comment by tonyhutter** [comment]
Thanks for reporting this.  Our centos 7.4 mock config was pointing to the 7.5 centos repo.   I've rebuilt the packages - try it again.

**Comment by tonyhutter** [comment]
>  So it's not clear to me that using the Centos 7.5 kernel for 7.4 is wrong.

If you have Centos 7.4, then do a `yum update`, you will get Centos 7.5.  That includes the kernel, userspace, everything.  So in that sense people don't really run "Centos 7.4 with the 7.5 kernel", they simply run Centos 7.5.  You would have to have a non-standard config to have Centos 7.4 running the Centos 7.5 kernel.

In this particular case, @nathans is purposely not using the normal mirrors so he can keep running Centos 7.4 (including the 7.4 kernel).

**Comment by DrDaveD** [comment]
> If you have Centos 7.4, then do a yum update, you will get Centos 7.5

Not necessarily, it depends on how you set up the .repo files, whether or not you explicitly ask for 7.4 or the latest 7.

> You would have to have a non-standard config to have Centos 7.4 running the Centos 7.5 kernel.

I don't think that's true.  The standard configuration includes getting security updates, and the only way to do that for the kernel is to get the latest kernel which is the same one as 7.5.  If you don't update you Centos 7.4 machine to the 7.5 kernel, you will be vulnerable to public security threats.

**Comment by tonyhutter** [comment]
Yea, unfortunately the new package is there, but @behlendorf noticed today that it's still built for the Centos 7.5 kernel:
```
$ rpm -qpi http://download.zfsonlinux.org/epel/7.4/kmod/x86_64/kmod-zfs-0.7.11-1.el7_4.x86_64.rpm
warning: http://download.zfsonlinux.org/epel/7.4/kmod/x86_64/kmod-zfs-0.7.11-1.el7_4.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID f14ab620: NOKEY
Name        : kmod-zfs
Version     : 0.7.11
Release     : 1.el7_4
Architecture: x86_64
Install Date: (not installed)
Group       : System Environment/Kernel
Size        : 4191016
License     : CDDL
Signature   : RSA/SHA256, Wed 26 Sep 2018 11:10:24 AM PDT, Key ID a9d5a1c0f14ab620
Source RPM  : zfs-kmod-0.7.11-1.el7_4.src.rpm
Build Date  : Wed 26 Sep 2018 10:57:57 AM PDT
Build Host  : e364e0e7852b4fc9a48e2cfaa303fc73
Relocations : (not relocatable)
URL         : http://zfsonlinux.org/
Summary     : zfs kernel module(s)
Description :
This package provides the zfs kernel modules built for
the Linux kernel 3.10.0-862.11.6.el7.x86_64 for the x86_64
family of processors.
```
I'm going to double check why mock is still building against the wrong kernel...

**Comment by tonyhutter** [comment]
@nathans it turns out I updated the 7.4 mock config to point to the correct repos, but I didn't rebuild my mock environment.  Once I rebuilt the environment, it pulled in the correct 3.10.0-693 kernel headers.  I'll rebuild the RPMs in the next day or two after our internal build server comes back online.

**Comment by nathans** [comment]
Works great. Thanks!
