### ISSUE TITLE
Cannot set SMB share name (eg. sharesmb=name=incoming)

### ISSUE THREAD

**Issue by 3guesses** [zfsonlinux/zfs#7983]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| antiX
Distribution Version	| 17.1
Linux Kernel	| 
Architecture	| Intel x64
ZFS Version	| 0.6.5.9-5
SPL Version	| 0.6.5.9-1

I am new to ZFS and fairly new to Linux in general.  I am trying to set up an antiX 17.1 box to act as a file server (using ZFS) on a Windows network, but when I try to use the "set sharesmb=name=" option (to share out my ZFS dataset as "incoming" rather than the default "tank_incoming"), it complains that it's an invalid option:

`$ sudo zfs set sharesmb=name=incoming tank/incoming`
`cannot set property for 'tank/incoming': 'sharesmb' cannot be set to invalid options`

**Comment by roboyoshi** [comment]
Already mentioned in https://github.com/zfsonlinux/zfs/issues/1182.
Looks like it's still in development, but you can still overwrite it:

`net usershare add sharename path [comment] [acl] [guest_ok=[y|n]]`
in your case: `net usershare add incoming /mnt/tank/incoming "a comment.." guest_ok=n`
( taken from here: https://github.com/zfsonlinux/zfs/issues/1182#issuecomment-31513512 )
