### ISSUE TITLE
Backing zpools with LVM LVs can have strange results

### ISSUE THREAD

**Issue by rincebrain** [zfsonlinux/zfs#7992]
### System information
Type | Version/Name
 --- | --- 
Distribution Name	| Debian stretch
Distribution Version	| 9.5
Linux Kernel	| 4.9.0-8-amd64
Architecture	| x86_64
ZFS Version	| 0.7.11-1~bpo9+1
SPL Version	| 0.7.11-1~bpo9+1

### Describe the problem you're observing
(Yes, I know this is a terrible idea, I was just trying to reproduce a user's problem when they were testing ZFS and already using LVM.)

If you back a zpool with LVM LVs, write data to fill the pool, and then overwrite parts/all of the LVs, dd/xxd/cat/etc on the LV files will report the correct overwritten data, but ZFS won't notice without an export/import or scrub.

If you back a zpool with files on a filesystem directly, write data to fill the pool, overwrite parts/all of the backing files,, and then read the data on the pool, it will immediately throw checksum errors.

I don't know whether this is misbehavior on LVM, ZFS, or something else, but I found it rather surprising, and so did the person reporting it.

### Describe how to reproduce the problem
```
for i in `seq 0 3`;do truncate -s 128M lvtest$i && losetup -f lvtest$i; done;
# change the loops if losetup didn't grab 0-3, but inlining something to scrape that seemed unnecessary.
vgcreate -n lvmtest /dev/loop{0,1,2,3}; 
for i in `seq 1 4`;do lvcreate -L 128M lvmtest -n lvm${i};done;
zpool create -f testpool raidz2 /dev/lvmtest/lvm{1,2,3,4};
dd if=/dev/urandom of=/testpool/testfile bs=1M;
dd if=/dev/zero of=/dev/lvmtest/lvm3 bs=1M;
dd if=/dev/zero of=/dev/lvmtest/lvm4 bs=1M;
sync;
dd if=/testpool/testfile of=/dev/null bs=1M;
zpool status testpool;  # reports no errors
zpool scrub testpool;
zpool status testpool; # immediately reports the entire disks lvm3 and lvm4 as corrupt data UNAVAIL.
```

### Include any warning/errors/backtraces from the system logs
None.

**Comment by rincebrain** [comment]
@fling- I wasn't weighing in on whether this was a documentation bug or an implementation bug, but it was an unexpected result with no obvious documentation.

Particularly because reading the LVs (or flat files) produced the same contents without dropping caches, and different behavior when ZFS was layered on it.

I was not asking how to make it behave differently. I was remarking that it was either something that should probably be noted somewhere for others who run into the unexpected behavior, or root-caused and corrected to behave as expected.

**Comment by loli10K** [comment]
> If you back a zpool with files on a filesystem directly, write data to fill the pool, overwrite parts/all of the backing files,, and then read the data on the pool, it will immediately throw checksum errors.

On my system (Debian8) this does not happen without flushing the ARC, i get the same behaviour you reported with lvm:

```
root@linux:~# modinfo -F version zfs
0.7.10-1
root@linux:~# for i in `seq 1 4`;do truncate -s 128M /var/tmp/lvtest$i; done;
root@linux:~# zpool create -f testpool raidz2 /var/tmp/lvtest{1,2,3,4};
root@linux:~# dd if=/dev/urandom of=/testpool/testfile bs=1M;
dd: error writing ‘/testpool/testfile’: No space left on device
120+0 records in
119+0 records out
125173760 bytes (125 MB) copied, 19.7578 s, 6.3 MB/s
root@linux:~# dd if=/dev/zero of=/var/tmp/lvtest3 bs=1M  count=128;
128+0 records in
128+0 records out
134217728 bytes (134 MB) copied, 0.0824044 s, 1.6 GB/s
root@linux:~# dd if=/dev/zero of=/var/tmp/lvtest4 bs=1M count=128;
128+0 records in
128+0 records out
134217728 bytes (134 MB) copied, 0.0813998 s, 1.6 GB/s
root@linux:~# sync;
root@linux:~# dd if=/testpool/testfile of=/dev/null bs=1M;
119+1 records in
119+1 records out
125173760 bytes (125 MB) copied, 0.0821693 s, 1.5 GB/s
root@linux:~# zpool status testpool;  # reports no errors
  pool: testpool
 state: ONLINE
  scan: none requested
config:

	NAME                  STATE     READ WRITE CKSUM
	testpool              ONLINE       0     0     0
	  raidz2-0            ONLINE       0     0     0
	    /var/tmp/lvtest1  ONLINE       0     0     0
	    /var/tmp/lvtest2  ONLINE       0     0     0
	    /var/tmp/lvtest3  ONLINE       0     0     0
	    /var/tmp/lvtest4  ONLINE       0     0     0

errors: No known data errors
root@linux:~# zinject -a
root@linux:~# dd if=/testpool/testfile of=/dev/null bs=1M;
119+1 records in
119+1 records out
125173760 bytes (125 MB) copied, 0.85604 s, 146 MB/s
root@linux:~# zpool status testpool
  pool: testpool
 state: ONLINE
status: One or more devices has experienced an unrecoverable error.  An
	attempt was made to correct the error.  Applications are unaffected.
action: Determine if the device needs to be replaced, and clear the errors
	using 'zpool clear' or replace the device with 'zpool replace'.
   see: http://zfsonlinux.org/msg/ZFS-8000-9P
  scan: none requested
config:

	NAME                  STATE     READ WRITE CKSUM
	testpool              ONLINE       0     0     0
	  raidz2-0            ONLINE       0     0     0
	    /var/tmp/lvtest1  ONLINE       0     0     0
	    /var/tmp/lvtest2  ONLINE       0     0     0
	    /var/tmp/lvtest3  ONLINE       0     0    18
	    /var/tmp/lvtest4  ONLINE       0     0    18

errors: No known data errors
root@linux:~# 
```

**Comment by rincebrain** [comment]
@loli10K Huh, that's odd. I figured it was interesting enough when I could only repro this with LVM in the mix after the user reported it that it warranted further conversation.

Wonder if this was just a race I happened to win with whatever causes #7820 . I'll go try forcing arc_min=arc_max and see if I can repro it then.

**Comment by rincebrain** [comment]
@loli10K it was surprising to me, not that the behavior required flushing caches or not, but because the two cases appeared to differ consistently between the two configurations for the person asking about it and mine.

If it had been obvious it was the result of the data happening to expire from the ARC MRU in one case and not the other, or the behavior had been inconsistent between their system and mine, it would have been interesting, but in a different way.

(I also didn't think of anything dropping the ARC between the two because my system, at least, is not under any memory pressure, and I had set arc_min=arc_max on module load to work around #7820...except I apparently didn't regenerate the initrd after editing the modprobe.d config, so it didn't get applied. Womp womp.)

**Comment by gmelikov** [comment]
I don't see any bug or misbehavior here - just purge the cache before read and ZFS will read data from disk, that's all, no?

**Comment by rincebrain** [comment]
As you wish.

**Comment by gleventhal** [comment]
Where can I read about the official stance for ZOL with regards to running a zpool on top of LVM?

**Comment by eduncan911** [comment]
> Where can I read about the official stance for ZOL with regards to running a zpool on top of LVM?

I'd like to know this as well.  With LUKS and hibernation, running a completely separate disk partition for crypt swap with a passphrase of course prompts twice.  You can't use a "keyfile" for swap in this scenario because of the race to open the LUKS container to read hibernation data in initramfs.

Therefore, a very simple and clean way is to:

    LUKS
      -LVM
        -pvZFS_ROOT
        -pvSWAP

Given, this LVM is a workaround for the ZVOL bug of not able to use SWAP on ZVOL.
