### ISSUE TITLE
Missing step in wiki entry for Ubuntu 18.04 Root on ZFS

### ISSUE THREAD

**Issue by w0067814** [zfsonlinux/zfs#7993]
@rlaager
Richard,

Re: https://github.com/zfsonlinux/zfs/wiki/Ubuntu-18.04-Root-on-ZFS

Thanks for taking the time to make this wiki page. It's proven to be very useful. However I believe there is a step missing. I have found in section 4.5 that it is necessary to perform the command "chmod 1777 /tmp" before I can successfully use "apt update", otherwise I get errors reported by apt that it cannot write temporary files to /tmp for passing config to apt-key.

In my case I have created a separate /tmp dataset as per section 3.3

Thanks,
-Tim

**Comment by rlaager** [comment]
Thanks. Fixed in ee6f81906dfaf79deae2dd3495c459f8bec77ac5.
