### ISSUE TITLE
Unable to build working initramfs.img with dracut on ubuntu

### ISSUE THREAD

**Issue by chthonik** [zfsonlinux/zfs#8008]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu
Distribution Version	| 18.04 bionic
Linux Kernel	| 4.15.0-36-generic
Architecture	| AMD64
ZFS Version	| 0.8.0-rc1_34_g95542372e
SPL Version	| 0.8.0-rc1_34_g95542372e

### Describe the problem you're observing
I am attempting to be bleeding edge here and install a natively encrypted root on 18.04.  Dracut-mount is unable to mount the rootfs at boot.  I am using a keyfile loaded on a usb to decrypt the rootfs and the datasets are loaded properly.  I passed the root=ZFS:AUTO command to dracut for the vmlinuz image and also tried bootfs=rpool/ROOT/neon.  I tried rebuilding with only initramfs-tools installed but that got me nowhere--just a hex dump, which I wasn't about to solve.  

I'm thinking there may be some compatibility issue with dracut and ubuntu  or maybe I am just missing come configs when using dracut.

I just showed the beginning configs at boot and then the end of the trace where the error occurs
### Include any warning/errors/backtraces from the system logs
'''
+ cat /lib/dracut/dracut-
dracut-
+ cat /proc/cmdline
\\EFI\ubuntu\vmlinuz zfs:AUTO initrd=EFI\ubuntu\initramfs.img
+ '[' -f /etc/cmdline ']'
+ for _i in /etc/cmdline.d/*.conf
+ '[' -f '/etc/cmdline.d/*.conf' ']'
*BREAK*
[    3.645681] localhost systemd[1]: Found device Flash_Disk KEY.
[    3.646891] localhost systemd[1]: Mounting /media/max/KEY...
[    3.652384] localhost systemd[1]: Mounted /media/max/KEY.
[    3.653207] localhost systemd[1]: Reached target Local File Systems.
[    3.654266] localhost systemd[1]: Starting Create Volatile Files and Directories...
[    3.651346] localhost kernel: EXT4-fs (sdc1): mounted filesystem with ordered data mode. Opts: (null)
[    3.656634] localhost systemd[1]: Started Create Volatile Files and Directories.
[    3.775650] localhost kernel: ata5: SATA link down (SStatus 0 SControl 330)
[    4.090986] localhost kernel: ata6: SATA link down (SStatus 0 SControl 330)
[    5.132474] localhost kernel: ata7: failed to resume link (SControl 0)
[    5.133095] localhost kernel: ata7: SATA link down (SStatus 0 SControl 0)
[    5.445449] localhost kernel: ata8: SATA link down (SStatus 0 SControl 330)
[    5.568351] localhost systemd[1]: Started udev Wait for Complete Device Initialization.
[    5.569073] localhost systemd[1]: Reached target System Initialization.
[    5.569679] localhost systemd[1]: Reached target Basic System.
[    5.570674] localhost systemd[1]: Starting Import ZFS pools by device scanning...
[    5.835978] localhost bash[1269]: /bin/bash: /bin/awk: No such file or directory
[    5.839957] localhost systemd[1]: Started Import ZFS pools by device scanning.
[    5.840820] localhost systemd[1]: Reached target ZFS pool import target.
[    5.848501] localhost systemd[1]: Started Dispatch Password Requests to Console.
[   11.997984] localhost kernel: random: crng init done
[   11.998527] localhost kernel: random: 7 urandom warning(s) missed due to ratelimiting
[   16.185279] localhost systemd[1]: Started dracut pre-mount hook.
[   16.185976] localhost systemd[1]: Reached target Initrd Root File System.
[   16.186925] localhost systemd[1]: Starting Reload Configuration from the Real Root...
[   16.189332] localhost systemd[1]: Reloading.
[   16.203443] localhost zfs-generator: starting
[   16.204073] localhost zfs-generator: loading Dracut library from /lib/dracut-lib.sh
[   16.233202] localhost systemd[1]: Started Reload Configuration from the Real Root.
[   16.233852] localhost systemd[1]: Reached target Initrd File Systems.
[   16.234417] localhost systemd[1]: Reached target Initrd Default Target.
[   16.235315] localhost systemd[1]: Starting dracut mount hook...
[   16.318057] localhost dracut-mount[1438]: Warning: Can't mount root filesystem
[   16.322723] localhost systemd[1]: Starting Dracut Emergency Shell...

'''

**Comment by kpande** [comment]
don't use AUTO (it is deprecated), it's `rootfs=` not `bootfs=` (for cmdline argument) and this is ultimately better suited for the [zfs-discuss mailing list](http://list.zfsonlinux.org)

**Comment by kpande** [comment]
try `rootfs=ZFS=pool/foo/bar`

**Comment by chthonik** [comment]
Changed the param to root=ZFS=rpool/ROOT/neon, "rootfs" didn't seem to load the encryption key properly.  Yet, I am still unable to mount the rootfs.  Running dracut-mount fails because it is unable to read the dataset.

**Comment by chthonik** [comment]
Changed the param to root=ZFS=rpool/ROOT/neon, "rootfs" didn't seem to load the encryption key properly.  Yet, I am still unable to mount the rootfs.  Running dracut-mount fails because it is unable to read the dataset.  I don't think the dataset "rpool/ROOT/neon" is loading correctly.  After it drops to emergency shell, when I run "zfs mount rpool/ROOT/neon" the new rootfs is loaded and completely empty.  In other words, I chroot to the new '/' with absolutely nothing inside.
