### ISSUE TITLE
zfs-0.6.4.2 under redhat-7.4

### ISSUE THREAD

**Issue by Rmrfy** [zfsonlinux/zfs#8017]
Hi ：
I want to install zfs-0.6.4 version under 7.4 system.But when the pool is created after the compilation and installation is completed, an error is reported.such as

`zpool: symbol lookup error: zpool: undefined symbol: zfs_dev_is_whole_disk`

**Comment by kpande** [comment]
this is not a support forum, use [the zfs-discuss mailing list](http://list.zfsonlinux.org)
