### ISSUE TITLE
Make a dedicated reclaim thread

### ISSUE THREAD

**Issue by ryao** [zfsonlinux/zfs#802]
Currently, the kernel calls arc_shrinker_func() whenever it needs to free memory. Unfortunately, concurrent threads operating during memory pressure can invoke this function simultaneously, which causes locking contention and causes ARC to free excessive quantities of memory.

For example, it is possible for 5 threads block on direct reclaim, run through their reclaim paths and each come to the conclusion that ZFS will need to free 100MB of RAM. Then, ZFS will be invoked and the threads thread will be serialized, with each thread unblocking after 100MB of RAM has been freed. The total amount of memory freed will be 500MB of RAM and an excessive amount of time will have been spent waiting.

My basic idea to resolve this is as follows. I propose that we rework ARC to maintain a dedicated shrinker thread that will sleep until signaled to free memory. When the kernel invokes the arc_shrinker_func() callback, the thread that invokes it will signal the shrinker thread, which will wake up and proceed to free memory. If additional threads signal it during this time, their requests will be aggregated, with all of them being notified when the maximum of their free memory requests has been freed. After they are notified, the shrinker thread will go back to sleep.

In the above scenario, only 100MB will be freed, all 5 threads will only have to wait the time that the first thread would have had to wait and locking contention would decrease. My plan is to produce a patch for this when my time permits it, but I am posting this here so that it can be discussed in parallel to that.

**Comment by behlendorf** [comment]
Things are significantly improved after the multilist ARC support was merged.  Closing.
