### ISSUE TITLE
zfs builtin with linux 4.18.x (>= 4.5) doesn't compile anymore

### ISSUE THREAD

**Issue by michael-brade** [zfsonlinux/zfs#8023]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Debian
Distribution Version	|  unstable
Linux Kernel	|  4.18.14
Architecture	|  amd64
ZFS Version	|  git master (0aa5916a3)
SPL Version	|  -

### Describe the problem you're observing

After configuring kernel and zfs, doing `./copy-builtin` and then trying to compile the kernel results in:
```
 CC      fs/zfs/zfs/dbuf_stats.o
In file included from ./include/zfs/sys/zpl.h:36,
                 from fs/zfs/zfs/arc.c:297:
./include/zfs/linux/vfs_compat.h: In function ‘zpl_is_32bit_api’:
./include/zfs/linux/vfs_compat.h:635:10: error: implicit declaration of function ‘is_compat_task’; did you mean ‘is_idle_task’? [-Werror=implicit-function-declaration]
  return (is_compat_task());
          ^~~~~~~~~~~~~~
```
The reason is that `ZFS_AC_KERNEL_IN_COMPAT_SYSCALL` only runs in the ZFS tree, not in the kernel tree. And `HAVE_IN_COMPAT_SYSCALL` is not written to `zfs_config.h`, so in a linux tree with builtin ZFS, `HAVE_IN_COMPAT_SYSCALL` will never be defined.

The commit that introduced this is: https://github.com/zfsonlinux/zfs/commit/e897a23eb13bafcf9c38d2fc37ae57a7729d9a02

**Comment by behlendorf** [comment]
@michael-brade have you tried re-running autogen.sh.  `HAVE_IN_COMPAT_SYSCALL` is added, as expected, to `zfs_config.h` on our test systems.

```
/* in_compat_syscall() is available */
#define HAVE_IN_COMPAT_SYSCALL 1
```

And the automated kernel build-in builds appear to be passing (4.19.0-rc7).

http://build.zfsonlinux.org/builders/Kernel.org%20Built-in%20x86_64%20%28BUILD%29/builds/22531

**Comment by michael-brade** [comment]
@behlendorf whoops! you are right, that did it! Thank you :smile:
