### ISSUE TITLE
The newest zfs-0.8.0-rc1 is not work for Debain (rock64 board)

### ISSUE THREAD

**Issue by Rain516** [zfsonlinux/zfs#8026]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Armbian (Debain)
Distribution Version	| 4.4.161
Linux Kernel	| 4.4.161-rockchip64
Architecture	| aarch64
ZFS Version	| zfs-0.8.0-rc1
SPL Version	| spl-0.8.0-rc1

### Describe the problem you're observing
zfs-0.8.0-rc1 is not work for Debain (rock64 board), detail as below:

### Describe how to reproduce the problem

***
uname -a
Linux rock64 4.4.161-rockchip64 #2 SMP Sun Oct 14 23:22:24 CDT 2018 aarch64 GNU/Linux

*** zfs-0.8.0-rc1 building steps:
sudo git clone https://github.com/zfsonlinux/zfs
sudo mv zfs zfs-master
cd zfs-master
sudo ./autogen.sh
sudo ./configure
sudo make -s -j$(nproc)
sudo make deb-utils deb-dkms
for file in lib*.deb; do sudo gdebi -q --non-interactive $file; done
for file in zfs*.deb; do sudo gdebi -q --non-interactive $file; done

*** check ZFS:
ls -la /usr/lib/systemd/system/
total 40
drwxr-xr-x  2 root root 4096 Oct 16 05:06 .
drwxr-xr-x 10 root root 4096 Oct 16 05:06 ..
-rw-r--r--  1 root root  572 Oct 16 04:57 zfs-import-cache.service
-rw-r--r--  1 root root  539 Oct 16 04:57 zfs-import-scan.service
-rw-r--r--  1 root root  101 Oct 16 04:57 zfs-import.target
-rw-r--r--  1 root root  307 Oct 16 04:57 zfs-mount.service
-rw-r--r--  1 root root  378 Oct 16 04:57 zfs-share.service
-rw-r--r--  1 root root   76 Oct 16 04:57 zfs.target
-rw-r--r--  1 root root   76 Oct 15 21:08 zfs-target.service
-rw-r--r--  1 root root  167 Oct 16 04:57 zfs-zed.service

cat /sys/module/zfs/version
0.8.0-rc1_50_g0aa5916a3

sudo modprobe zfs
modprobe: ERROR: ../libkmod/libkmod-module.c:192 kmod_module_parse_depline() ctx=0x55739f7010 path=/lib/modules/4.4.161-rockchip64/extra/zfs/unicode/zunicode.ko error=No such file or directory

ls -la /etc/systemd/system
total 36
drwxr-xr-x 9 root root 4096 Oct 16 03:35 .
drwxr-xr-x 5 root root 4096 Oct 15 04:29 ..
drwxr-xr-x 2 root root 4096 Oct 15 04:39 basic.target.wants
lrwxrwxrwx 1 root root   53 Oct 15 04:39 dbus-org.freedesktop.nm-dispatcher.service -> /lib/systemd/system/NetworkManager-dispatcher.service
drwxr-xr-x 2 root root 4096 Oct 15 04:38 default.target.wants
drwxr-xr-x 2 root root 4096 Oct 15 04:41 getty.target.wants
drwxr-xr-x 2 root root 4096 Oct 16 02:27 multi-user.target.wants
drwxr-xr-x 2 root root 4096 Oct 15 04:39 network-online.target.wants
lrwxrwxrwx 1 root root   31 Oct 15 04:39 sshd.service -> /lib/systemd/system/ssh.service
drwxr-xr-x 2 root root 4096 Oct 15 04:41 sysinit.target.wants
lrwxrwxrwx 1 root root   35 Oct 15 04:32 syslog.service -> /lib/systemd/system/rsyslog.service
drwxr-xr-x 2 root root 4096 Oct 15 04:32 timers.target.wants
lrwxrwxrwx 1 root root    9 Oct 16 03:35 zfs-import-cache.service -> /dev/null
lrwxrwxrwx 1 root root    9 Oct 16 03:35 zfs-import-scan.service -> /dev/null
lrwxrwxrwx 1 root root    9 Oct 16 03:35 zfs-mount.service -> /dev/null
lrwxrwxrwx 1 root root    9 Oct 16 03:35 zfs-share.service -> /dev/null
lrwxrwxrwx 1 root root   42 Oct 15 20:56 zfs-target -> /usr/lib/systemd/system/zfs-target.service
lrwxrwxrwx 1 root root    9 Oct 16 03:35 zfs.target -> /dev/null
lrwxrwxrwx 1 root root    9 Oct 16 03:35 zfs-zed.service -> /dev/null

*** I tried to fix the above " -> /dev/null" issues as below:
sudo ln -sf /usr/lib/systemd/system/zfs-import-cache.service /etc/systemd/system/zfs-import-cache.service
sudo ln -sf /usr/lib/systemd/system/zfs-import-scan.service /etc/systemd/system/zfs-import-scan.service
sudo ln -sf /usr/lib/systemd/system/zfs-mount.service /etc/systemd/system/zfs-mount.service
sudo ln -sf /usr/lib/systemd/system/zfs-share.service /etc/systemd/system/zfs-share.service
sudo ln -sf /usr/lib/systemd/system/zfs.target /etc/systemd/system/zfs.target
sudo ln -sf /usr/lib/systemd/system/zfs-zed.service /etc/systemd/system/zfs-zed.service

sudo systemctl enable zfs-import-cache
sudo systemctl enable zfs-import-scan
sudo systemctl enable zfs-import.target
sudo systemctl enable zfs-mount
sudo systemctl enable zfs-share
sudo systemctl enable zfs-zed
sudo systemctl enable zfs.target

*** so far, I can create a ZFS pool and put file into the pool:
sudo zpool create -R /mnt myZFSpool /dev/sda
sudo touch /mnt/MyZFSpool/test.dat

*** after reboot, ZFS work abnormal:
A message during startup:
[FAILED] Failed to start ZFS file system shares.

sudo systemctl status zfs-share.service
● zfs-share.service - ZFS file system shares
   Loaded: loaded (/usr/lib/systemd/system/zfs-share.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2018-10-16 05:27:31 UTC; 50min ago
     Docs: man:zfs(8)
  Process: 847 ExecStart=/sbin/zfs share -a (code=exited, status=1/FAILURE)
  Process: 814 ExecStartPre=/bin/rm -f /etc/dfs/sharetab (code=exited, status=0/SUCCESS)
 Main PID: 847 (code=exited, status=1/FAILURE)

Oct 16 05:27:31 rock64 systemd[1]: Starting ZFS file system shares...
Oct 16 05:27:31 rock64 zfs[847]: Failed to initialize the libzfs library.
Oct 16 05:27:31 rock64 systemd[1]: zfs-share.service: Main process exited, code=exited, status=1/FAILURE
Oct 16 05:27:31 rock64 systemd[1]: Failed to start ZFS file system shares.
Oct 16 05:27:31 rock64 systemd[1]: zfs-share.service: Unit entered failed state.
Oct 16 05:27:31 rock64 systemd[1]: zfs-share.service: Failed with result 'exit-code'.

sudo zfs list
Failed to initialize the libzfs library.

cat /sys/module/zfs/version
cat: /sys/module/zfs/version: No such file or directory

Could someone help to fix the issue?

**Comment by gmelikov** [comment]
@Rain516 i don't see any `make deb-deb` in code, please try to build with `make deb`.

**Comment by Rain516** [comment]
> @Rain516 i don't see any `make deb-deb` in code, please try to build with `make deb`.

sorry, it typo, should be make deb-dkms

**Comment by Rain516** [comment]
> @Rain516 i don't see any `make deb-deb` in code, please try to build with `make deb`.



> @Rain516 i don't see any `make deb-deb` in code, please try to build with `make deb`.

sorry, it's typo, should be make deb-dkms. 
I have updated the description.

**Comment by rincebrain** [comment]
Among other things, /sys/module/zfs/version is the version of the module already loaded in your kernel.

It looks, though it's hard to tell without you escaping the console output or uploading it as a logfile, like zuincode.ko is causing errors on trying to load? What does dkms status say?

Also, you're not trying to run 0.8.0-rc1, you're running git master, which is an even more exciting thing for someone to try.

**Comment by kpande** [comment]
please use [the zfs-discuss mailing list](http://list.zfsonlinux.org) for support requests, this is not a  bug.
