### ISSUE TITLE
Logical devices names can get jumbled on Ubuntu.

### ISSUE THREAD

**Issue by ericbets** [zfsonlinux/zfs#8040]
### System information
Distribution Name	| Ubuntu
Distribution Version	| 18.04.01 LTS
Linux Kernel	| 4.15.0-36-generic #39-Ubuntu SMP
Architecture	| amd64
ZFS Version	| 0.7.5-1ubuntu16.3
SPL Version	| 0.7.5-1ubuntu1

### Describe the problem you're observing
OS boots from a USB-3 stick, and all the caddies are filled with zfs data drives.
Sometimes the /dev/sdX entries get jumbled w/no hardware changes and zfs looks for a zfs vdev where the OS is now sitting and the corresponding vdev in that pool cannot be found and thus goes offline. The rest of the pool is fine. For example, on the last boot   OS= /dev/sdb1, a vdev=/dev/sdc1, but on this boot their device names have been logically swapped. It would be good if zfs could do the right thing here and automatically search for the vdev that corresponds to the one that was originally inserted in it's catalog (via it's id), or introduce a way of human naming vdevs.

**Comment by kpande** [comment]
please use [the zfs-discuss mailing list](http://list.zfsonlinux.org) for support requests, this is not a bug

**Comment by bunder2015** [comment]
FWIW, zfs can already use /dev/disk/by-id

**Comment by behlendorf** [comment]
https://github.com/zfsonlinux/zfs/wiki/FAQ#selecting-dev-names-when-creating-a-pool
