### ISSUE TITLE
Rebuilding root pool to new disk makes system unbootable: cannot import root pool

### ISSUE THREAD

**Issue by drook** [zfsonlinux/zfs#8059]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Centos
Distribution Version	|  7.5
Linux Kernel	|  3.10.0-862.14.4
Architecture	|  amd64
ZFS Version	|  0.7.11-1
SPL Version	|  0.7.11-1

### Describe the problem you're observing
Adding new disk into the root pool mirror makes the system unable to boot. The system starts to complain about inability to import the root pool, used by <unknown> hostid = 0.

The workaround is still to `zpool import -fR / zroot` from the dracut shell and exit, but this operation (i.e. rebuilding on the newly added disk) is flawless on Solaris/FreeBSD.

### Describe how to reproduce the problem
`zpool detach zroot sde3`
`zpool attach zroot sdd3 sde3`
(wait for resilver to complete, reboot)

Reproducible 100%.

**Comment by drook** [comment]
![import-error](https://user-images.githubusercontent.com/2329493/47492866-6d31a000-d867-11e8-83f5-034048ad149f.jpg)

**Comment by djkazic** [comment]
I think this is inherent to the "different system" condition forcing you to import the pool with the `-f` argument. If this is divergent behavior from FreeBSD due to different code, there isn't much to do.

**Comment by kpande** [comment]
use `zfs_force=1` cmdline parameter. this is not a bug.

**Comment by drook** [comment]
Why "this is not a bug" ? I'm using zfs root pool on the same system that created it, same installation/host exactly. I'm not importing a pool from another host, or, god forbid, OS. Did you see a hardware or software raid that require intervention after disk replacement on next boot and did not count this a a bug ? Does that mean that whose who use zfs on Linux should suffer ?

**Comment by djkazic** [comment]
You probably forgot to update your initramfs when adding the disk. Here's some good reading to do: https://github.com/zfsonlinux/zfs/issues/2927

**Comment by drook** [comment]
Why should I update initramfs after removing and reinserting **_the same_** disk into **_the same_** pool ?
Nothing should change after the mirrored pool is rebuilt. If it has, it's a bug too from my knowledge. The most troublesome root pool implementation was in Solaris 10, but even there you didn't have to do anything other that recreating vtoc label on the disk after rebuilding. If something is different in Linux implementation, zpool should advise doing additional steps, like FreeBSD zpool is (which acts differently comparing to the reference zfs implementation, which is the Solaris one), for example by saying about calling 'gpart bootcode' after reinserting the disk/upgrading the root pool.

P.S. And the author of the ticket you're mentioning as 'good reading' is saying that initramfs updating isn't helping/fixing anything either.

**Comment by djkazic** [comment]
I pointed you there because I've run into this myself, and the `update-initramfs` approach worked. Not sure what else to tell you -- did you check the `hostid` like that ticket mentioned?
