### ISSUE TITLE
Cannot build on older gcc

### ISSUE THREAD

**Issue by xiaclo** [zfsonlinux/zfs#806]
I am trying to build for a Synology device (x64_64 atom), but it uses an older toolchain.

gcc (GCC) 4.2.0
GNU ld version 2.17
Linux 2.6.32.12
glibc 2.10.1

Let me know if any other versions would be helpful.

I have "fixed" a few errors already, but am running into more.  These are the changes I have made so far, hopefully they are helpful.

Full configure log: http://pastebin.com/hu7Cvx5g

error: 'LLONG_MAX' undeclared (first use in this function)
Complete error: http://pastebin.com/RMY1L3Du
Fixed by adding the "-std=c99" flag to the build of lib/libzfs/libzfs_pool.c and cmd/zpool/zpool_vdev.c

error: previous declaration of 'dmu_read_req' was here / error: previous declaration of 'dmu_write_req' was here
Complete error: http://pastebin.com/gjFwJWeD
Fixed by adding "struct request;" to the end of the list (line 67 on my version) to include/sys/dmu.h

I am now getting errors related to modules/zfs/vdev_disk.c, probably related to the changes I made earlier, forcing it to c99.
Complete error: http://pastebin.com/Sj7Urxa9

I'm not very competent with C or the like, is there another way around these errors?

**Comment by behlendorf** [comment]
Closing, since we haven't heard back and it's a very old version of gcc we'll assume this is no longer an issue.
