### ISSUE TITLE
Snapshots do not contain posixacls?

### ISSUE THREAD

**Issue by presleyd** [zfsonlinux/zfs#8062]
Type | Version/Name
 --- | --- 
Distribution Name	| CentOS
Distribution Version	| 7.5
Linux Kernel	| 3.10.0-862
Architecture	| Intel
ZFS Version	| 0.7.9-1
SPL Version	| 0.7.9-1

### Describe the problem you're observing
Posix ACL changes don't seem to be captured in snapshots. When you rollback a snapshot, the ACLs are not rolled back to previous state. Changing ACLs on a source ZFS filesystem which is replicated with zfs send/recv commands does not replicate ACL changes to the target ZFS filesystem.

### Describe how to reproduce the problem
I have a RAIDZ2 zpool who's overlaying ZFS filesystem has the following overridden attributes:
```
data  compression           lz4                    local
data  atime                 off                    local
data  xattr                 sa                     local
data  acltype               posixacl               local
```
SAMBA is used to export this fs to Windows. We currently have SMB working with the following smb.conf
```
[global]
        workgroup = IBBR
        security = ads
        realm = AD.IBBR.UMD.EDU
        log level = 3

        server string = IBBR Storage

        idmap config * : backend = tdb
        idmap config * : range = 300000-400000

        idmap config IBBR : backend = rid
        idmap config IBBR : range = 10000-20000

        passdb backend = tdbsam
        load printers = no

        winbind use default domain = true
        get quota command = /usr/local/bin/get_quota.sh %U

[data]
        path = /data
        read only = no
        hide unreadable = yes
   
        vfs objects = shadow_copy2, acl_xattr
        map acl inherit = yes
        store dos attributes = yes

        shadow: snapdir = /data/.zfs/snapshot
        shadow: format = zfs-auto-snap_%S-%Y-%m-%d-%H%M
```
Snapshots are usable from Windows Explorer as 'Previous Versions' and we can set ACLS from Windows Explorer and also via commands like setfacl. However, when an ACL is altered it does not replicate to our backup servers. If we use 'zfs rollback ...' or Windows Previous Versions to restore an old file it retains the latest ACLs and does not revert to previous ones. 

If we delete a folder or file, create a new copy with the same name and give it the new ACLs, however, the changes will be replicated. It's like ACLs are written to the snapshots only when the file/folder is new and never again?

Is this something I'm doing wrong?

**Comment by loli10K** [comment]
I suspect after an online receive/rollback userland is getting stale ACLs.

**Comment by presleyd** [comment]
When I change the ACL on the source server, getfacl instantly shows the change. When I push the snapshot to a destination server or rollback on either, getfacl also shows the stale ACLs. So I think that means that it's not happening in just userland.

**Comment by loli10K** [comment]
What i meant is the kernel is feeding stale ACL data to userland. Try unmounting the filesystem after a receive/rollback, mount it again and check ACLs.

**Comment by presleyd** [comment]
Your absolutely right. I'm not sure if there is anything I can do about that besides unmounting it but at least my ACLs are actually being preserved.

**Comment by loli10K** [comment]
I'm not sure if anything can be done to invalidate stale ACLs and how online rollbacks/receives behave on other platforms; i'm going to test this on my Illumos development box if/when i have some spare time.

**Comment by maxximino** [comment]
Does this help:
$ echo 2 > /proc/sys/vm/drop_caches
instead of unmounting? (files that are open would still have stale ACLs)

On the code side:
I think that calling evict_inodes (https://elixir.bootlin.com/linux/v4.18/source/fs/inode.c#L607) after receiving a snapshot/rollback would be a good idea anyway and should solve the problem for files that are not open.
For open files, would need to manually call forget_cached_acl on each one :(
Problem: evict_inodes is a GPL-only symbol :(

**Comment by presleyd** [comment]
That does not fix the problem in my case. I still see the stale ACLs.
