### ISSUE TITLE
zfs building issues

### ISSUE THREAD

**Issue by protonesso** [zfsonlinux/zfs#8068]
Hi everyone! I have troubles to build ZFS on Linux. I used zfs and spl version 0.7.11 on Linux kernel 4.19.0. I wanted to build that on my own LFS system.
Here's spl configuration for build
```
./configure \
	--prefix=/usr \
	--libdir=/usr/lib \
	--sbindir=/usr/bin \
        --with-linux=/usr/src/linux \
        --with-linux-obj=/usr/src/linux \
        --with-config=kernel \
        --build=x86_64-generic-linux
```
and zfs configuration:
```
./autogen.sh
./configure \
	--prefix=/usr \
	--libdir=/usr/lib \
	--libexecdir=/usr/lib/zfs \
	--sbindir=/usr/bin \
	--datadir=/usr/share \
	--sysconfdir=/etc \
        --with-linux=/usr/src/linux \
        --with-linux-obj=/usr/src/linux \
        --with-config=kernel \
	--with-mounthelperdir=/usr/bin \
	--with-udevdir=/usr/lib/udev \
	--with-udevruledir=/usr/lib/udev/rules.d \
	--with-dracutdir=/usr/lib/dracut \
	--with-tirpc \
	--build=x86_64-linux-generic
```
And build log: https://pastebin.com/UqyLHDxd
My toolchain: GCC 8.2.1 20180831, binutils 2.31.1, glibc 2.27

**Comment by rincebrain** [comment]
You completely deleted the template for reporting bugs and posted a support request instead.

0.7.11 doesn't claim to support anything above 4.18.

#7932 will most likely be in 0.7.12, and fix your problem.

**Comment by protonesso** [comment]
Thanks, I will wait

**Comment by protonesso** [comment]
Okay
