### ISSUE TITLE
RHEL 7.6 packages

### ISSUE THREAD

**Issue by muff1nman** [zfsonlinux/zfs#8090]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| RHEL
Distribution Version	| 7.6
Linux Kernel	| 3.10.0-957
Architecture	| x86_64
ZFS Version	| 0.7.11
SPL Version	| 0.7.11

### Describe the problem you're observing
There doesn't seem to be a repo available yet for 7.6.

**Comment by bunder2015** [comment]
RHEL 7.6 was released 5 days ago.  I'm sure packages will be arriving soon, thanks for letting us know and keep your eyes peeled. :smile:

**Comment by tonyhutter** [comment]
Yea, it's on my TODO list.  I need to put together the Fedora 29 packages as well.  They will definitely be included with 0.7.12 (https://github.com/zfsonlinux/zfs/pull/8078).

**Comment by tonyhutter** [comment]
... sorry I mistakenly read this this as Centos 7.6 (before my morning coffee...)  We don't provide RHEL packages, but do provide Centos 6 & 7 packages, so we'll support Centos 7.6 when it comes out.

**Comment by johnpeeb** [comment]
Is there a technical reason why the RPM KMOD packages don't use the Requires / Provides RPM directives to enable seamless updates for all Centos 7.x minor versions from a single repository? Specifically, couldn't you have a separate package for each supported kernel version, eg. zfs-kmod-kernelver, each of which Requires that kernel version and Provides the capability "zfs". Then, running "yum install zfs" should automatically pull in the version corresponding to your kernel and upgrades should work via yum upgrade seamlessly without having to run any extra commands, and will block updating the kernel until a compatible zfs package is available. Or am I missing something?

**Comment by tonyhutter** [comment]
@johnpeeb this doesn't answer your question, but I wanted to mention that the kmods are not versioned to the kernel, but rather to the kernel functions they call.  As long as those functions stay the same, then it should work.  For example,  zfs-kmod-0.7.12 works on both Centos 7 w/3.10.0-862.14.4 and 3.10.0-862.11.6.

**Comment by hoonetorg** [comment]
Probably it's time to build el 7.6 kmod packages and zfs-release.el7_6.noarch.rpm soon, because CentOS 7 with incompatible Kernel already there via CR repo

still on CentOS 7.5.1804
```
[root@lp-hfischer-centos ~]# cat /etc/centos-release
CentOS Linux release 7.5.1804 (Core) 
```
but already continous release kernel of upcoming Centos 7.6.1810 install via CR repo:
```
# fc -l 1 |grep "yum --enablerepo cr update" 
713	 yum --enablerepo cr update
# uname -a
Linux laptop 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
ZFS is not loadable anymore:
```
# zpool status
The ZFS modules are not loaded.
Try running '/sbin/modprobe zfs' as root to load them.
# modprobe zfs
modprobe: FATAL: Module zfs not found.
# rpm -qa |grep release |grep zfs
zfs-release-1-5.el7.centos.noarch
```
zfs-release.el7_6.noarch.rpm not available yet:
```
# yum install http://download.zfsonlinux.org/epel/zfs-release.el7_5.noarch.rpm
Loaded plugins: fastestmirror, langpacks, priorities
zfs-release.el7_5.noarch.rpm | 5.3 kB  00:00:00     
Examining /var/tmp/yum-root-zlmrfq/zfs-release.el7_5.noarch.rpm: zfs-release-1-5.el7.centos.noarch
/var/tmp/yum-root-zlmrfq/zfs-release.el7_5.noarch.rpm: does not update installed package.
Error: Nothing to do

# yum install http://download.zfsonlinux.org/epel/zfs-release.el7_6.noarch.rpm
Loaded plugins: fastestmirror, langpacks, priorities
Cannot open: http://download.zfsonlinux.org/epel/zfs-release.el7_6.noarch.rpm. Skipping.
Error: Nothing to do
```

**Comment by hoonetorg** [comment]
CentOS 7.6.1810 released now (https://lists.centos.org/pipermail/centos-announce/2018-December/023082.html)
Now it's definitely time to create the new kmod repo/packages/release(rpm) according to https://github.com/zfsonlinux/zfs/issues/8090#issuecomment-435949869

**Comment by tonyhutter** [comment]
@hoonetorg thanks, I'll put together the RPMs.

**Comment by fmikker** [comment]
I wish I had checked if the 7.6 package was available before I did the upgrade, oh well, no biggie to revert.

**Comment by tonyhutter** [comment]
Ok packages should be up now.  

https://github.com/zfsonlinux/zfs/wiki/RHEL-and-CentOS has been updated with the new 7.6 zfs-release rpm: http://download.zfsonlinux.org/epel/zfs-release.el7_6.noarch.rpm

Please post if you run into any issues

**Comment by GeoffreyMills** [comment]
FYI Cannot install the 7.5 or 7.6 releases on Centos 7. Can download and install the zfs-release rpm OK but the subsequent 'yum install zfs' fails, cannot download files. Seems like at least half of the 'spl', etc files are not found. The 7.4 release works OK

**Comment by tonyhutter** [comment]
@GeoffreyMills do a `yum clean all` and try again.

**Comment by GeoffreyMills** [comment]
Done, working now - thanks

**Comment by omfdzg** [comment]
Hi, have problem when trying to import module
>  /sbin/modprobe zfs
> modprobe: FATAL: Module zfs not found.

I see module is in place (possibly modprobe works with different path ?)

> locate zfs.ko 
> /usr/lib/modules/3.10.0-957.1.3.el7.x86_64/extra/zfs/zfs/zfs.ko

**Comment by omfdzg** [comment]
works fine after yum update
