### ISSUE TITLE
Ubuntu 18.04 requires correct use of netplan

### ISSUE THREAD

**Issue by pjgoodall** [zfsonlinux/zfs#8098]
### System information

Ubuntu | 18.04 LTS
Distribution Name	| Ubuntu
Distribution Version	|  18.04 LTS
Linux Kernel	| 4.15.0-38-generic
Architecture	| x86-64
ZFS Version	|  v0.7.5-1ubuntu16.4
SPL Version	| 0.7.5-1ubuntu1

### Describe the problem you're observing

No NetworkManager after following instructions in section 8.2b

### Describe how to reproduce the problem

After installing full gui version of Ubuntu, as in section **8.2b Install a full GUI environment** , and I `delete the /etc/netplan/NAME.yaml` as described, on reboot NetworkManager does not work, and I have no DNS.

If I follow the instructions in the second answer in AskUbuntu question - [Network Manager not working when installing ubuntu-desktop on a Ubuntu 18.04 Server installation](https://askubuntu.com/questions/1031956/network-manager-not-working-when-installing-ubuntu-desktop-on-a-ubuntu-18-04-ser)
then the issue is fixed.

My new `/etc/netplan/NAME.yaml` has contents. 

```
network:
  version: 2
  renderer: NetworkManager
```
I do not believe it is correct to delete  `/etc/netplan/NAME.yaml`  in Ubuntu 18.04.x, thiugh I am not expert.

I suspect any modification to files in /etc/netplan should be followed by 
```
netplan generate
netplan apply
```

Including perhaps those in step **4.2 Configure the network interface**

### Include any warning/errors/backtraces from the system logs
No logs seem relevant

**Comment by rlaager** [comment]
Good catch. I've updated the instructions. I skipped the "netplan generate" and "netplan apply" steps, because this is followed very shortly by a reboot.
