### ISSUE TITLE
ZFS root boot hangs at kernel loading

### ISSUE THREAD

**Issue by rejsmont** [zfsonlinux/zfs#8100]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu
Distribution Version	| 18.04
Linux Kernel	| 4.15.0-38-generic
Architecture	| x86_64
ZFS Version	| 0.7.5-1ubuntu15
SPL Version	| 0.7.5-1ubuntu1

### Describe the problem you're observing
After recently upgrading ubuntu and rebooting gandi VPS instance the boot hangs.

### Describe how to reproduce the problem
Unknown - the problem suddenly appeared after upgrade. I do not know what the previous versions were. The system is running under XEN hypervisor.

### Include any warning/errors/backtraces from the system logs
From kernel log:
```
[    0.045394] cpu 0 spinlock event irq 53
[    0.075787] acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.
[    0.979793] Grant table initialized
[    1.195686] mce: Unable to init MCE device (rc: -5)
[    1.929728] piix4_smbus 0000:00:01.3: SMBus Host Controller not enabled!
[    2.136706] spl: loading out-of-tree module taints kernel.
[    2.151423] znvpair: module license 'CDDL' taints kernel.
[    2.159127] Disabling lock debugging due to kernel taint
[  242.656151] INFO: task zpool:1083 blocked for more than 120 seconds.
[  242.665642]       Tainted: P           O     4.15.0-38-generic #41-Ubuntu
[  242.674866] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  242.685825] INFO: task txg_sync:2168 blocked for more than 120 seconds.
[  242.694072]       Tainted: P           O     4.15.0-38-generic #41-Ubuntu
[  242.701569] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
```

**Comment by rejsmont** [comment]
Hi!

I did a bit more digging into the matter (as I also wanted to save my data) and found that I may be after an actual bug in 0.7. Please see the edited bug report.

**Comment by rincebrain** [comment]
Related to #7659 maybe?

You could also try import with the l2arc device not connected, and since persistent L2ARC hasn't landed, nothing of value will be lost. If that works, and you can reproduce it by re-adding the l2arc device, that'd be exciting. If you don't have one, I suppose that'd be even more exciting.

**Comment by rejsmont** [comment]
@rincebrain Hi! Thanks for the suggestion. Unfortunately, it's a single disk pool, so no separate l2arc device (it was originally running under vm as lxd storage backend, so made no sense to spread it over multiple volumes). I will zfs send/receive to a fresh pool using 0.6.5.6 and see if it helps.

Thanks!
