### ISSUE TITLE
Cannot mount received raw encrypted filesystem

### ISSUE THREAD

**Issue by herrernst** [zfsonlinux/zfs#8103]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Fedora / Ubuntu
Distribution Version	| Fedora 29 / Ubuntu 18.04.1 LTS
Linux Kernel	| 4.18.16 / 4.15.0
Architecture	| x86_64
ZFS Version	| 0.8.0-rc1
SPL Version	| 0.8.0-rc1

### Describe the problem you're observing
On system 1 (Ubuntu), there's an encrypted filesystem with some snapshots. Some of these snapshots are sent to system 2 (Fedora) with flag `-w` (i.e. raw). After receiving, the filesystem cannot be mounted.

### Describe how to reproduce the problem
On system 2 (Fedora):
```bash
# receive oldest/initial snapshot
ssh ubuntu zfs send -w tank/encrypted@snap001 | zfs receive storage/encrypted
# receive some more snapshot
ssh ubuntu zfs send -w -I @snap001 tank/encrypted@snap010 | zfs receive storage/encrypted

sudo zfs mount -l storage/encrypted
Enter passphrase for 'storage/encrypted': 
filesystem 'storage/encrypted' can not be mounted: Input/output error
cannot mount 'storage/encrypted': Invalid argument
```

### Include any warning/errors/backtraces from the system logs
I don't see nothing unusual, is there anything specific you'd want?

**Comment by herrernst** [comment]
Any ideas? Is it a bug, or I am using it wrong?
The initial snapshot can still be mounted via `mount -t zfs storage/encrypted@snap001 /mnt`, but all incremental ones cannot:
```
mount -t zfs storage/encrypted@snap005 /mnt
filesystem 'storage/encrypted@snap005' can not be mounted: Input/output error
```

After rollback to the first snapshot, the filesystem also can be mounted again. After that, I've tried to receive snapshots again, but now a zfs process is already hanging for minutes on 100% cpu (without I/O), last message in `dbgmsg`is:
```
1542058215   spa_history.c:313:spa_history_log_sync(): txg 1612 finish receiving storage/encrypted/%recv (id 271) snap=snap002
1542058215   spa_history.c:313:spa_history_log_sync(): txg 1612 clone swap storage/encrypted/%recv (id 271) parent=encrypted
1542058215   spa_history.c:313:spa_history_log_sync(): txg 1612 snapshot storage/encrypted@snap002 (id 274) 
1542058215   spa_history.c:313:spa_history_log_sync(): txg 1612 destroy storage/encrypted/%recv (id 271) 
1542058215   bptree.c:232:bptree_iterate(): bptree index 0: traversing from min_txg=1092 bookmark 0/0/0/0

```

**Comment by tcaputi** [comment]
@herrernst By any chance did you upgrade from a previous unstable version of zfs with encryption? We haven't seen cases like this in a few months (other than problems from unstable versions).

**Comment by herrernst** [comment]
No, i've never used ZOL with native encryption before.

**Comment by tcaputi** [comment]
Hmmm... Do you have any steps to reproduce the issue? What kind of workload are you running on this dataset (how many files, how big are they, what kind of files are they)? 

Another good thing to do would be to run `echo 4294966270 > /sys/module/zfs/parameters/zfs_flags` and then try the test again. That will cause all errors that are returned from zfs to be logged (with a line number for me) in dbgmsg, which would help figure out where the problem is coming from.

**Comment by herrernst** [comment]
Thanks for your help. Here is the outpout of dbgmsg: https://pastebin.com/xaFi0m74
Pool was imported on boot, some time later, key was loaded, and then I tried to mount the filesystem.
One thing probably worth mentioning is that the filesystem and its snapshots are quite old and were created on Solaris (or OpenSolaris) and encrypted when received with ZOL. I've tried to reproduce the issue with a new filesystem, but the problem didn't happen again.

**Comment by tcaputi** [comment]
That is interesting. Can you do `zfs get version <dataset>` for me? I wonder if that has something to do with it

**Comment by herrernst** [comment]
dataset version is 5. Thanks for checking!

**Comment by herrernst** [comment]
Here's another (long) log from the source (Ubuntu) host: https://gist.githubusercontent.com/herrernst/b6205657c57669c894ebaf450ec311f1/raw/5909161fefbbff9843eabcd94885f6e22f9d4755/dbgmsg

Commands executed:
````
zfs send -w tank/encrypted@snap001 | zfs receive tank/encrypted_DUP_TEST
zfs send -w -i snap001 tank/encrypted@snap002 | zfs receive tank/encrypted_DUP_TEST
zfs load-key tank/encrypted_DUP_TEST
zfs mount tank/encrypted_DUP_TEST
````

**Comment by tcaputi** [comment]
That's very interesting.... I will probably need to look at this on Monday. What kind of workload are you running on this dataset (how many files, how big are they, what kind of files are they, are you using extended attributes)? Can you also provide the output of `zpool get all <pool>`?

**Comment by tcaputi** [comment]
@herrernst any updates to my last questions?

**Comment by herrernst** [comment]
Workload is small files (source code, documents, photos), around 30000 files. Some seem to have extended attributes (there are added `<xattrdir>`s in `zfs diff`), but they aren't listed with `getfattr`. 

Also, the bug doesn't seem to have something to do with incremental sending, if I send only one of the affected snapshots (like `snap002` from above), I also get this error. 

Do you see some apparent problem in the logs I posted?

Output of `zpool get all <pool>` is:
````
NAME                  PROPERTY                       VALUE                          SOURCE
storage               size                           1.81T                          -
storage               capacity                       5%                             -
storage               altroot                        -                              default
storage               health                         ONLINE                         -
storage               guid                           7176536494574276261            -
storage               version                        -                              default
storage               bootfs                         -                              default
storage               delegation                     on                             default
storage               autoreplace                    off                            default
storage               cachefile                      -                              default
storage               failmode                       wait                           default
storage               listsnapshots                  off                            default
storage               autoexpand                     off                            default
storage               dedupditto                     0                              default
storage               dedupratio                     1.00x                          -
storage               free                           1.71T                          -
storage               allocated                      105G                           -
storage               readonly                       off                            -
storage               ashift                         0                              default
storage               comment                        -                              default
storage               expandsize                     16.0E                          -
storage               freeing                        0                              -
storage               fragmentation                  0%                             -
storage               leaked                         0                              -
storage               multihost                      off                            default
storage               checkpoint                     -                              -
storage               load_guid                      7858410741726219422            -
storage               feature@async_destroy          enabled                        local
storage               feature@empty_bpobj            active                         local
storage               feature@lz4_compress           active                         local
storage               feature@multi_vdev_crash_dump  enabled                        local
storage               feature@spacemap_histogram     active                         local
storage               feature@enabled_txg            active                         local
storage               feature@hole_birth             active                         local
storage               feature@extensible_dataset     active                         local
storage               feature@embedded_data          active                         local
storage               feature@bookmarks              enabled                        local
storage               feature@filesystem_limits      enabled                        local
storage               feature@large_blocks           enabled                        local
storage               feature@large_dnode            enabled                        local
storage               feature@sha512                 enabled                        local
storage               feature@skein                  enabled                        local
storage               feature@edonr                  enabled                        local
storage               feature@userobj_accounting     disabled                       local
storage               feature@encryption             active                         local
storage               feature@project_quota          active                         local
storage               feature@device_removal         enabled                        local
storage               feature@obsolete_counts        enabled                        local
storage               feature@zpool_checkpoint       enabled                        local
storage               feature@spacemap_v2            active                         local
storage               feature@allocation_classes     enabled                        local
storage               feature@resilver_defer         enabled                        local
````

**Comment by tcaputi** [comment]
Hmmm so just to confirm you can reproduce the bug without `zfs send -i` or `zfs send -I`? That's interesting. Almost all of my working theories are only applicable to incremental receives.

Am I correct in my understanding that the first snapshot works correctly? How much data changed between the first and second snapshot?

**Comment by tcaputi** [comment]
Can you provide the output of `cat <send file for broken snapshot> | zstreamdump -v`? And if its not too much trouble, can you try receiving the snapshot into a different dataset (like `tank/encrypted2` or something)? That should tell us if there is a problem with the send / receive process itself or if there is something wrong with the dataset you are receiving it into.

**Comment by herrernst** [comment]
Here's the output of zstreamdump, but without `-v` (with `-v`, it would be 40 MB):
````
BEGIN record
	hdrtype = 1
	features = 1420004
	magic = 2f5bacbac
	creation_time = 4e6a6a92
	type = 2
	flags = 0x4
	toguid = 8700812bc1fa990a
	fromguid = 0
	toname = tank/encrypted@snap002
nvlist version: 0
	crypt_keydata = (embedded nvlist)
	nvlist version: 0
		DSL_CRYPTO_SUITE = 0x5
		DSL_CRYPTO_GUID = 0x49259de8cc99ee81
		DSL_CRYPTO_VERSION = 0x1
		DSL_CRYPTO_MASTER_KEY_1 = 0x7f 0x21 0x84 ....
		DSL_CRYPTO_HMAC_KEY_1 = 0xb1 0x74 0xb9 ...
		DSL_CRYPTO_IV = 0x2d 0x3f 0xdb ...
		DSL_CRYPTO_MAC = 0xa4 0x2 0xc2  ...
		portable_mac = 0x5e 0xa0 0xda ...
		keyformat = 0x3
		pbkdf2iters = 0x55730
		pbkdf2salt = 0x6d4102...
		mdn_checksum = 0x0
		mdn_compress = 0x0
		mdn_nlevels = 0x6
		mdn_blksz = 0x4000
		mdn_indblkshift = 0x11
		mdn_nblkptr = 0x3
		mdn_maxblkid = 0x597
	(end crypt_keydata)

END checksum = 4974f79c2244d7fe/d377e44c4fe64695/4a3e17f93704937f/191c5563cca11885
SUMMARY:
	Total DRR_BEGIN records = 1
	Total DRR_END records = 1
	Total DRR_OBJECT records = 31567
	Total DRR_FREEOBJECTS records = 522
	Total DRR_WRITE records = 100275
	Total DRR_WRITE_BYREF records = 0
	Total DRR_WRITE_EMBEDDED records = 0
	Total DRR_FREE records = 36825
	Total DRR_SPILL records = 31560
	Total records = 201818
	Total write size = 9827251200 (0x249bff400)
	Total stream length = 9906378468 (0x24e7756e4)
````
(I've truncated some keys.)
By receiving into a different dataset, do you mean into the same pool? I think I [already have done that](#issuecomment-440805855).

**Comment by tcaputi** [comment]
> Another thing maybe worth mentioning is that the dataset was once encrypted with the closed source Solaris ZFS encryption.

Ok. I honestly don't know if that could have caused any issues, although its very possible it did. When implementing encryption for OpenZFS I was very careful not to look at the Solaris implementation that was leaked so that we didn't get into any intellectual property trouble. I'm also curious if there were any other features active from Solaris that may be incompatible with encryption.

Debugging this might be a bit complicated. At this point what I've normally had to do in the past is go figure out which object is causing errors. If we're lucky it will be reported in `zpool status -v` as a "permanent data error" after attempting to mount the filesystem. The error will probably look something like this:

```
...
errors: Permanent errors have been detected in the following files:

        <part 1>:<part 2>
```

* `part 1` should be the dataset name, but it may not be printed if the problem is in the MOS which is unlikely. This will almost definitely be the name of your encrypted dataset.
* `part 2` is usually the file's path when the dataset is mounted, but it should be a hexadecimal identifier of the broken object since your dataset can not be mounted.

If the error isn't listed there it should show up in `zpool events -v` as an `authentication` error or as an IO error, depending on how the error is propagated. I don't remember the exact format of how the errors are reported, but if you provide the output here I should be able to tell you what it is.

If neither of these work I will probably have to provide a custom patch to figure out which object it is complaining about. Lets hope it doesn't come to that. :)

Once we have the object number (and since you said most files in the system are relatively small) I would need the output of `zdb -ddddddddddd <dataset name> <object number in decimal>`, which should give us a good idea of what object is broken along with some info about its structure. From there maybe we can figure out what happened.

**Comment by tcaputi** [comment]
That makes a lot of sense. Go ahead and email it to tcaputi@datto.com

**Comment by behlendorf** [comment]
> One thing probably worth mentioning is that the filesystem and its snapshots are quite old and were created on Solaris (or OpenSolaris) and encrypted when received with ZOL. I've tried to reproduce the issue with a new filesystem, but the problem didn't happen again.

This fits well with what @tcaputi discovered when examining the pool.  It certainly sounds as if somehow while running on (Open)Solaris the root directory had its bonus length set to 0.  That wouldn't have caused any real issues and could have happened a very long time ago.  How exactly that could have happened I can't really say for sure.

**Comment by herrernst** [comment]
Thanks for investigation! I booted up my old Solaris installation and looked at the original snapshots. Like you would guess, the problematic snapshot indeed has bonus length = 0.
````
Dataset nas/encrypted@snap002 [ZPL], ID 163, cr_txg 309, 9.22G, 31567 objects, rootbp DVA[0]=<0:5d3980c00:800:RZM:3> [L0 DMU objset] sha256 lzjb LE contiguous unique unencrypted 3-copy size=800L/200P birth=305L/305P fill=31567 cksum=33411d11326ee90:7ef0fef1c4535f63:4e97a18865a1e63f:99f7e28c8b39b06d

    Object  lvl   iblk   dblk  dsize  lsize   %full  type
         4    1    16K    512  2.50K    512  100.00  ZFS directory (K=inherit) (Z=inherit)
                                          0   bonus  System attributes
        dnode flags: USED_BYTES USERUSED_ACCOUNTED SPILL_BLKPTR
        dnode maxblkid: 0

Indirect blocks:
               0 L0 0:549819400:800 200L/200P F=1 B=265/265

                segment [0000000000000000, 0000000000000200) size   512
````
But, quite weird, the snapshot before has a non-zero bonus size:
````
Dataset nas/encrypted@snap001 [ZPL], ID 147, cr_txg 261, 11.7G, 44763 objects, rootbp DVA[0]=<0:556b89800:800:RZM:3> [L0 DMU objset] sha256 lzjb LE contiguous unique unencrypted 3-copy size=800L/200P birth=258L/258P fill=44763 cksum=2aab3605411459d1:57b963b3492559a5:20d846d0dcd13335:d7a4eef2f4caf6fc

    Object  lvl   iblk   dblk  dsize  lsize   %full  type
         4    1    16K    512  1.50K    512  100.00  ZFS directory (K=inherit) (Z=inherit)
                                        168   bonus  System attributes
        dnode flags: USED_BYTES USERUSED_ACCOUNTED 
        dnode maxblkid: 0

Indirect blocks:
               0 L0 0:630b3800:800 200L/200P F=1 B=183/183

                segment [0000000000000000, 0000000000000200) size   512

````

This is apparently quite an exotic issue. Could there be an easy way to fix my filesystem and/or create a new snapshot that would work? Otherwise I can also live with migrating the data with rsync.

**Comment by tcaputi** [comment]
That's unfortunate. This must be a bug on the Oracle Solaris version of ZFS then. Unfortunately I don't know what would work while guaranteeing that your data isn't corrupted. You could try changing the attributes (such as the rwx permissions) on the root directory and seeing what happens. I don't know if other files you have are effected though (assuming you want to back up something more than the empty snapshot you sent me). Theoretically though, you should always be able to rollback to your previous snapshots.

I think the most reliable thing you can do at this point is to mount each snapshot, rsync it over to a new dataset, snapshot the dataset, and repeat for all snapshots you want to back up. That will make sure none of this weirdness makes its way over to the new dataset. Hope that helps.

**Comment by herrernst** [comment]
Thanks for the hint about attributes. I changed the permissions on the root directory, and almost anything works then. There some more folders that have a problem, if I could also fix them I would prefer this "solution" to rsyncing. But unfortunately these other folders/files keep bonus length = 0 even after chmodding them. Any ideas?

**Comment by tcaputi** [comment]
I don't, but @behlendorf might. Sorry, the permissions idea was more of a guess than anything.

**Comment by herrernst** [comment]
@behlendorf Any idea to reset the bonus buffer size? Thanks.

**Comment by behlendorf** [comment]
@herrernst one thing which might work is setting the `xattr=sa` property on the dataset, then adding and removing a small extended attribute on the file.  This should cause the bonus size to be written correctly since that's where it's going to store the xattr.  Or... you might get an error due to the zero bonus length!  But it's worth a try.  You can always set `xattr=on|off` after removing any test xattrs to keep the pool portable.

**Comment by behlendorf** [comment]
@herrernst where you able to reset the bonus buffer size and resolve your issue?

**Comment by herrernst** [comment]
Yes, thanks. If I remember correctly I just did two `chmod` twice.

**Comment by tcaputi** [comment]
@slavanap I'm sorry to hear that. I might be able to try to help later this week, but I haven't actively done zfs development in several years now. Perhaps you could try to replicate what was done in this comment? https://github.com/openzfs/zfs/issues/8103#issuecomment-443446186
