### ISSUE TITLE
zpool device name mixup (wwn-....  / scsi-....)

### ISSUE THREAD

**Issue by devZer0** [zfsonlinux/zfs#8108]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  CentOS
Distribution Version	|  7.5.1804
Linux Kernel	|  3.10.0-862.11.6.el7.x86_64
Architecture	| x64
ZFS Version	| 0.7.11-1
SPL Version	| 0.7.11-1

### Describe the problem you're observing
I have labeld my hdd trays with WWN id for proper identification and tried to make zpool status output consistent to reflect naming scheme by wwn - but for my curiousity one of the disk reproducably shows up with scsi-.... name instead of wwn-.... name for no apparent reason.

backupvm1 is a virtual machine with 6 disks attached to a jbod raid controller with VMDirectPath IO passtrough to the vm - 4 disks are raidz1/zfspool, 2 disks are md-raid.  

but imho it should make no difference to physical setup - as you can see the symlinks in /dev/by-id point to the same sdX disk name. 

looks like a zfs/scanning issue to me

```
[root@backupvm1 ~]# zpool status -v
  pool: zfspool
 state: ONLINE
  scan: scrub repaired 0B in 22h11m with 0 errors on Sat Sep 22 15:53:37 2018
config:

	NAME                              STATE     READ WRITE CKSUM
	zfspool                           ONLINE       0     0     0
	  raidz1-0                        ONLINE       0     0     0
	    wwn-0x5000cca260e2f247-part1  ONLINE       0     0     0
	    wwn-0x5000cca260f190fb-part1  ONLINE       0     0     0
	    wwn-0x5000cca260f18f69-part1  ONLINE       0     0     0
	    scsi-35000cca260f18ff7-part1  ONLINE       0     0     0

errors: No known data errors


[root@backupvm1 ~]# ls -la /dev/disk/by-id/
insgesamt 0
drwxr-xr-x 2 root root 680  8. Nov 2018  .
drwxr-xr-x 8 root root 160  8. Nov 2018  ..
lrwxrwxrwx 1 root root   9  8. Nov 2018  ata-VMware_Virtual_SATA_CDRW_Drive_00000000000000000001 -> ../../sr0
lrwxrwxrwx 1 root root  10  8. Nov 2018  dm-name-cl-root -> ../../dm-0
lrwxrwxrwx 1 root root  10  8. Nov 2018  dm-name-cl-swap -> ../../dm-1
lrwxrwxrwx 1 root root  10  8. Nov 2018  dm-uuid-LVM-joL02krkDVA7sxa4q9H11ZxQpEfOKyTDF1I0OFcr4xlr1Zpu5AaEh9JI4ishBfwm -> ../../dm-0
lrwxrwxrwx 1 root root  10  8. Nov 2018  dm-uuid-LVM-joL02krkDVA7sxa4q9H11ZxQpEfOKyTDNIKE6qpMHRmBYlx2TYe0NegSvk75WIpo -> ../../dm-1
lrwxrwxrwx 1 root root  10  8. Nov 2018  lvm-pv-uuid-h9wdKV-a1rf-fnm5-wsOB-Y3SD-nyVR-Q2TY9W -> ../../sda2
lrwxrwxrwx 1 root root  11  8. Nov 2018  md-name-xo-backup-raid1 -> ../../md127
lrwxrwxrwx 1 root root  11  8. Nov 2018  md-uuid-2784a755:54492a1f:e4a3abb3:a707b54b -> ../../md127
lrwxrwxrwx 1 root root   9  8. Nov 2018  scsi-35000cca260e2f247 -> ../../sdc
lrwxrwxrwx 1 root root  10  8. Nov 2018  scsi-35000cca260e2f247-part1 -> ../../sdc1
lrwxrwxrwx 1 root root   9  8. Nov 2018  scsi-35000cca260f18f69 -> ../../sdf
lrwxrwxrwx 1 root root  10  8. Nov 2018  scsi-35000cca260f18f69-part1 -> ../../sdf1
lrwxrwxrwx 1 root root   9  8. Nov 2018  scsi-35000cca260f18ff7 -> ../../sde
lrwxrwxrwx 1 root root  10  8. Nov 2018  scsi-35000cca260f18ff7-part1 -> ../../sde1
lrwxrwxrwx 1 root root   9  8. Nov 2018  scsi-35000cca260f190fb -> ../../sdb
lrwxrwxrwx 1 root root  10  8. Nov 2018  scsi-35000cca260f190fb-part1 -> ../../sdb1
lrwxrwxrwx 1 root root   9  8. Nov 2018  scsi-35000cca261c58b31 -> ../../sdg
lrwxrwxrwx 1 root root  10  8. Nov 2018  scsi-35000cca261c58b31-part1 -> ../../sdg1
lrwxrwxrwx 1 root root   9  8. Nov 2018  scsi-35000cca261c59c9f -> ../../sdd
lrwxrwxrwx 1 root root  10  8. Nov 2018  scsi-35000cca261c59c9f-part1 -> ../../sdd1
lrwxrwxrwx 1 root root   9  8. Nov 2018  wwn-0x5000cca260e2f247 -> ../../sdc
lrwxrwxrwx 1 root root  10  8. Nov 2018  wwn-0x5000cca260e2f247-part1 -> ../../sdc1
lrwxrwxrwx 1 root root   9  8. Nov 2018  wwn-0x5000cca260f18f69 -> ../../sdf
lrwxrwxrwx 1 root root  10  8. Nov 2018  wwn-0x5000cca260f18f69-part1 -> ../../sdf1
lrwxrwxrwx 1 root root   9  8. Nov 2018  wwn-0x5000cca260f18ff7 -> ../../sde
lrwxrwxrwx 1 root root  10  8. Nov 2018  wwn-0x5000cca260f18ff7-part1 -> ../../sde1
lrwxrwxrwx 1 root root   9  8. Nov 2018  wwn-0x5000cca260f190fb -> ../../sdb
lrwxrwxrwx 1 root root  10  8. Nov 2018  wwn-0x5000cca260f190fb-part1 -> ../../sdb1
lrwxrwxrwx 1 root root   9  8. Nov 2018  wwn-0x5000cca261c58b31 -> ../../sdg
lrwxrwxrwx 1 root root  10  8. Nov 2018  wwn-0x5000cca261c58b31-part1 -> ../../sdg1
lrwxrwxrwx 1 root root   9  8. Nov 2018  wwn-0x5000cca261c59c9f -> ../../sdd
lrwxrwxrwx 1 root root  10  8. Nov 2018  wwn-0x5000cca261c59c9f-part1 -> ../../sdd1

[root@backupvm1 ~]# cat /proc/mdstat
Personalities : [raid1]
md127 : active raid1 sdg1[1] sdd1[0]
      7813894464 blocks super 1.2 [2/2] [UU]
      bitmap: 0/59 pages [0KB], 65536KB chunk

unused devices: <none>
```

### Describe how to reproduce the problem
zpool export zfspool
zpool import -d /dev/disk/by-id zfspool

**Comment by behlendorf** [comment]
Is it possible the `wwn-` symlink is missing at import time.  This would result in it falling back and trying other paths.

**Comment by devZer0** [comment]
yes - why should it be missing when the system is up and running? 
i do export and import when the system is up and running...and the problem persists.
can give it another try tomorrow to be really sure...

**Comment by behlendorf** [comment]
`udev` can create and destroy the links, I just wanted to rule it out as a cause.  It looks like this could also be caused by the parallel scanning of the `/dev/disk/by-id` entries.  Certain `/dev/disk/` directories are preferred over others (when not specified) but not device name within directories.

**Comment by behlendorf** [comment]
Can you try this, right now the tree of devices is preferentially sorted by guid instead of full path name. Which would explain the traversal order you're seeing. 

```diff
diff --git a/lib/libzutil/zutil_import.c b/lib/libzutil/zutil_import.c
index 4284efa757..1a4c866ef4 100644
--- a/lib/libzutil/zutil_import.c
+++ b/lib/libzutil/zutil_import.c
@@ -1475,11 +1475,11 @@ slice_cache_compare(const void *arg1, const void *arg2)
        uint64_t guid2 = ((rdsk_node_t *)arg2)->rn_vdev_guid;
        int rv;
 
-       rv = AVL_CMP(guid1, guid2);
+       rv = AVL_ISIGN(strcmp(nm1, nm2));
        if (rv)
                return (rv);
 
-       return (AVL_ISIGN(strcmp(nm1, nm2)));
+       return (AVL_CMP(guid1, guid2));
 }
 
 static boolean_t
```

**Comment by devZer0** [comment]
mhh, how can i compile/install/test zpool with libzutil without breaking/risking my current installation? that is a production system with 0.7.11 (which does have different filenames, apparently)

**Comment by devZer0** [comment]
huh?  After a scrub and re-export/import -  the problem is gone !?!!?!

[root@backupvm1 /]# zpool list -v
NAME   SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
zfspool    29T  13,0T  16,0T         -     6%    44%  1.00x  ONLINE  -
  raidz1    29T  13,0T  16,0T         -     6%    44%
    wwn-0x5000cca260e2f247-part1      -      -      -         -      -      -
    wwn-0x5000cca260f190fb-part1      -      -      -         -      -      -
    wwn-0x5000cca260f18f69-part1      -      -      -         -      -      -
    wwn-0x5000cca260f18ff7-part1      -      -      -         -      -      -
