### ISSUE TITLE
zfs create pool/. and pool/.. are allowed

### ISSUE THREAD

**Issue by kpande** [zfsonlinux/zfs#8115]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Gentoo
Distribution Version	| 
Linux Kernel	| 4.19.1
Architecture	| amd64
ZFS Version	| master
SPL Version	| master

### Describe the problem you're observing
Though it's unlikely to cause a problem unless you're seemingly out to do so, the following:

```
# zfs create rpool/..
# zfs list
NAME                                             USED  AVAIL  REFER  MOUNTPOINT
rpool                                            302G  33.2G    24K  none
rpool/..                                         24K  33.2G    24K  none
```

if you were to set `overlay=on` for `rpool/..` it will happily mount into `..` and it's not clear what is happening...

In addition, `.`

**Comment by akorn** [comment]
Actual live example where the fs got mounted:

```
# mount
...
gehenna/tmp/test on /tmp/test type zfs (rw,nosuid,nodev,xattr,posixacl)
gehenna/tmp/test/test2 on /tmp/test/test2 type zfs (rw,nosuid,nodev,xattr,posixacl)
gehenna/tmp/test/test2/.. on /tmp/test type zfs (rw,nosuid,nodev,xattr,posixacl)
```

**Comment by pcd1193182** [comment]
I tried to take this to the logical extreme on a disposable VM, and bad times ensued...
```
$ mount

...
rpool/ROOT/delphix.w7YlrYI on / type zfs (rw,relatime,xattr,noacl)
...
test on /test type zfs (rw,xattr,noacl)
test/.. on / type zfs (rw,xattr,noacl)
$ sudo touch /foo
sudo: unable to resolve host pd-uhoh
$ sudo zpool destroy test
sudo: unable to resolve host pd-uhoh
```

**Comment by kpande** [comment]
I was wondering about `zpool/../..` but not adventurous enough to test it out

**Comment by pcd1193182** [comment]
If you do that, you actually *create* a /.. directory, with distinct contents from / (which I'm pretty sure violates POSIX or something):
```
$ sudo zfs create -o overlay=on test/../..
$ mount | grep test
test on /test type zfs (rw,xattr,noacl)
test/.. on / type zfs (rw,xattr,noacl)
test/../.. on / type zfs (rw,xattr,noacl)
$ sudo dd if=/dev/urandom of=/../a bs=128k count=512
512+0 records in
512+0 records out
67108864 bytes (67 MB, 64 MiB) copied, 0.462258 s, 145 MB/s
$ zfs list -r test
NAME         USED  AVAIL  REFER  MOUNTPOINT
test        64.2M  21.7G    24K  /test
test/..     64.1M  21.7G    24K  /test/..
test/../..  64.1M  21.7G  64.1M  /test/../..
$ ls /..
a
```

**Comment by jpaetzel** [comment]
It's actually easy to do if you hit enter too soon in a zfs create command.  There's an illumos bug open for this that I've been meaning to fix for ages.

**Comment by akorn** [comment]
What happens if you `zpool import -R /foo` such a pool? I expect it's a way for a rogue pool to "break out" of `/foo`.

**Comment by bunder2015** [comment]
In IRC the other day we were also talking about other pool names that probably shouldn't be allowed, like "cache", "dedup", "special", "mapper", sd* hd* (linux), ada* (freebsd), pool/datasets containing spaces, among others.  It would be really nice if we could keep people from using "silly" names for pools/datasets.

**Comment by rincebrain** [comment]
.zfs is also accepted and mounted. Not anything more than inconvenient unless someone is looking to stash rootkits somewhere that ls -al doesn't enumerate even when something else is mounted in it, but figured I'd mention it here.

**Comment by kpande** [comment]
maybe @behlendorf and @ahrens did not see this, but would like their input on the issue.

**Comment by behlendorf** [comment]
As a first step I think we should prevent new pools and datasets from being created with these kinds of troublesome names.  I'd also suggest printing a warning at import/mount time for any existing names which don't conform.  It should indicating that a future version of the software may not suppose those names and they should be changed, with a link to the naming restrictions.  Then at some point in the future we can starting enforce this.

**Comment by beren12** [comment]
some of these names it might be nice to let an admin override the restrictions, like if you have a dataset per user, you may have users named 'cache' and I'm sure there are lots of valid words starting with the letters sd or hd

**Comment by pcd1193182** [comment]
I think we should pick a small enough set of restricted names that we're comfortable not allowing them to be overriden.

**Comment by kpande** [comment]
one problem is that we create zvol entries as `/dev/pool/dataset` as well as `/dev/zvol/pool/dataset` so we should probably reject names that already exist there?

**Comment by jpaetzel** [comment]
I don't see an actual issue with a pool named log, or a dataset named log for that matter.  It doesn't really hurt anything.  

Datasets named . or .. and mounted in the default location actually do cause problems.  I think a dataset named .zfs mounted in the default location would be inconvenient and somewhat non-intuitive.  (You could conceivably mount it somewhere that wouldn't cause an issue I suppose, but this seems of limited value to me)

I'd propose to make '.', '..', and '.zfs' illegal dataset names.  The concerns about other pool names or dataset names aren't worth changing the naming policy over since naming a pool or a data 'cache' for example doesn't actually break anything.

https://www.illumos.org/issues/8254

**Comment by pcd1193182** [comment]
I would be comfortable preventing a pool from being named the same as anything in `/dev`, partly for the reason @kpande said and also because I have more than once when doing testing done `zpool create sdb sdc sdd` and just... forgotten to put in a pool name.

As for dataset names, I'd be fine with 'no leading non-alphanumeric characters'

**Comment by GregorKopka** [comment]
I disagree with further limitations on dataset names as I think the existing ones are already crippling:

Non-english users use natural (to them) characters in directory names, with the current implementation it isn't easily possible to move such into zfs filesystems - only by forcing the desired directory (mountpoint) name through setting `mountpoint` (which happily accepts UTF8 and works but has some display problems with `zfs list`) or using `mountpoint=legacy` and fstab, but both methods basically boil down to maintaining a PROGRA~1 style workaround (which is completely unfun).

Datasets names are stored as `\0` terminated strings and should be treated as such, ZFS should allow everything except `/` and `\0` as valid characters for dataset names and just disallow `.`, `..`, and `.zfs`.

In case there are concerns about people painting themselves into a corner through using unprintable characters or whatnot: these could be addressed without big problems by adding an option to `zfs rename` that allows specifying the dataset by `guid` to 'unpaint' it.

**Comment by beren12** [comment]
That sounds reasonable

**Comment by Lady-Galadriel** [comment]
We should also clear up these particular error messages;
`root # zfs create amypond/@`
`cannot create 'amypond/@': empty component in name`

`root # zfs create amypond/@test`
`cannot create 'amypond/@test': empty component in name`

`root # zfs create amypond/#`
`cannot create 'amypond/#': empty component in name`

`root # zfs create amypond/#test`
`cannot create 'amypond/#test': empty component in name`

<br>The normal error message would be more appropriate;
`root # zfs create amypond/test@test`
`cannot create 'amypond/test@test': snapshot delimiter '@' is not expected here`

`root # zfs create amypond/test#test`
`cannot create 'amypond/test#test': bookmark delimiter '#' is not expected here`

**Comment by kpande** [comment]
those do not appear to be problematic.

**Comment by Lady-Galadriel** [comment]
@kpande, correct, they are not a problematic per say, as they won't allow the ZFS create to continue.

However a better error message would be helpful for those that attempting to use `@` or `#` as the first, (or only), character in a dataset or zvol name. This would help people who are new to ZFS. Or accidentally copy an existing snapshot or bookmark's name and forget to edit it.

If desired, I can open a separate issue for this error message improvement.

**Comment by pcd1193182** [comment]
I'd file a separate issue for those; I agree they're bad error messages, but it don't fall under the same category as this issue.

**Comment by jpaetzel** [comment]
I'm curious as to why this was closed.  Is there a commit that fixed it?

**Comment by kpande** [comment]
nope, there is no genuine interest in fixing it.

**Comment by jpaetzel** [comment]
It's a real problem, I haven't gotten around to fixing it in openzfs yet, but when I do I hope ZoL will take the change.
