### ISSUE TITLE
SPL compilation on Debian produces error

### ISSUE THREAD

**Issue by Akito13** [zfsonlinux/zfs#8128]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Raspbian and Debian
Distribution Version	| 9 (Stretch)
Linux Kernel	| any aarch64 kernel
Architecture	| armhf and arm64
ZFS Version	| -
SPL Version	| any kernel-supported version

### Describe the problem you're observing
```
configure: error: *** Unable to build an empty module.
Error! Bad return status for module build on kernel: <any-kernel> (aarch64)

```
output of make.log:
`make: *** No targets specified and no makefile found. Stop.`

### Describe how to reproduce the problem

Try to install spl-dkms or compile spl from source against any aarch64 kernel.

**Comment by kpande** [comment]
please give some actual details of version numbers in a way that this is reproducible by others, or use [zfs-discuss](http://list.zfsonlinux.org) if you need help figuring out how.

**Comment by Akito13** [comment]
> 
> 
> please give some actual details of version numbers in a way that this is reproducible by others, or use [zfs-discuss](http://list.zfsonlinux.org) if you need help figuring out how.

I did. Try any version from 7.0 to 7.11.

**Comment by bunder2015** [comment]
`configure: error: *** Unable to build an empty module.`

This indicates a distro issue, you're missing something necessary to make kernel modules.

https://github.com/zfsonlinux/zfs/wiki/Building-ZFS

**Comment by Akito13** [comment]
> 
> 
> `configure: error: *** Unable to build an empty module.`
> 
> This indicates a distro issue, you're missing something necessary to make kernel modules.
> 
> https://github.com/zfsonlinux/zfs/wiki/Building-ZFS

I have installed 0.7.11 on this distribution with a different kernel. Nothing is missing.

**Comment by kpande** [comment]
well there are no other users here with that problem so you should query zfs-discuss as mentioned earlier, getting upset about your issue being closed here won't do any good.
