### ISSUE TITLE
Possible data loss with an rsync copy

### ISSUE THREAD

**Issue by kroy-the-rabbit** [zfsonlinux/zfs#8145]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Debian
Distribution Version	|  Stretch + backports
Linux Kernel	| 4.9.0-8
Architecture	| amd64
ZFS Version	| 0.7.11-1~bpo9+1
SPL Version	| 0.7.11-1~bpo9+1

### Describe the problem you're observing

Rsync fails to quit transferring data to a full pool.  Currently transferred 14TB onto an 8TB pool. 

I create a new pool out of two disks (10TB each).  Created a dataset, set a reserve on it of 25GB.

Proceeded to attempt to copy 40TB of data onto it.  It's still going, stuck at 512M available.

```
burnnnn                8.8T  8.8T  512M 100% /burnnnn
burnnnn/reserve         26G  128K   26G   1% /burnnnn/reserve
```

The files are going somewhere though, as the transfers are continuing at "disk speed"

```
  2,402,053,383 100%   99.01MB/s    0:00:23 (xfr#34970, ir-chk=1017/40683)
path/directory/another_directory/file.tmp
```

I've repeated a few times and watched it.  Watching it, the space available counts down to zero, rsync slows down to turtle speeds like you'd expect, the space available hits 0 then immediately bounces back up to 512M, and rsync resumes full speed. 

Hitting CNTL-C on the rsync gives a message like:

```
rsync: write failed on "path/to/file": No space left on device (28)
```
The failed rsync transfer it states is actually the file where it should have run out of space, despite being a few THOUSAND transfers after the failed file transfer.

### Describe how to reproduce the problem

I've reproduced this on a VM.  Steps:

* 3x50GB disks in RAIDz1 (just wanted to make sure it didn't have something to do with the large files being transferred
* Create a dataset with a 10GB reserve
* Resync more than the size of the pool from somewhere to the pool.  I used an NFS mount.
* Watch as the pool approaches zero, then continues to copy files.  Note that I was using multiple files to create this scenario (versus a single large file bigger than the pool).

**Comment by kpande** [comment]
please don't get rid of the issue template. can you fill it out and put it back?

**Comment by kpande** [comment]
this is not a bug in ZFS. it is a bug in rsync.

```
# rsync -a /file.block /test/1 || echo "Failure"
rsync: mkstemp "/test/.1.O9zg04" failed: No space left on device (28)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1039) [sender=3.0.6]
Failure
```

```
# cp /file.block /test/1
cp: cannot create regular file `/test/1': No space left on device
```

```
# for i in `seq 1 1000` ; do rsync -a /file.block /$i || echo Failure ; done
```

(no output here)

**Comment by kpande** [comment]
in my last comment my ext4 system wasn't completely full, after reattempting I was able to match zfs results:

```# for i in `seq 1 1000` ; do rsync -a /file.block /$i || echo Failure ; done
rsync: writefd_unbuffered failed to write 4 bytes to socket [sender]: Broken pipe (32)
rsync: write failed on "/1": No space left on device (28)
rsync error: error in file IO (code 11) at receiver.c(301) [receiver=3.0.6]
rsync: connection unexpectedly closed (28 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(600) [sender=3.0.6]
Failure
rsync: writefd_unbuffered failed to write 4 bytes to socket [sender]: Broken pipe (32)
rsync: write failed on "/2": No space left on device (28)
rsync error: error in file IO (code 11) at receiver.c(301) [receiver=3.0.6]
rsync: connection unexpectedly closed (28 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(600) [sender=3.0.6]
Failure
rsync: writefd_unbuffered failed to write 4 bytes to socket [sender]: Broken pipe (32)
rsync: write failed on "/3": No space left on device (28)
rsync error: error in file IO (code 11) at receiver.c(301) [receiver=3.0.6]
rsync: connection unexpectedly closed (28 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(600) [sender=3.0.6]
Failure
rsync: writefd_unbuffered failed to write 4 bytes to socket [sender]: Broken pipe (32)
rsync: write failed on "/4": No space left on device (28)
rsync error: error in file IO (code 11) at receiver.c(301) [receiver=3.0.6]
rsync: connection unexpectedly closed (28 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(600) [sender=3.0.6]
Failure
```

**Comment by kpande** [comment]
you didn't give your rsync arguments so it's possible you're using an option that behaves in unexpected ways. any further discussion for this should go to [zfs-discuss or IRC](http://list.zfsonlinux.org).
