### ISSUE TITLE
Wrong doc link on multihost-SUSPENDED pool

### ISSUE THREAD

**Issue by gmelikov** [zfsonlinux/zfs#8148]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Centos 
Distribution Version	| 7.5
Linux Kernel	| 3.10.0-862.14.4.el7.x86_64
Architecture	| x64
ZFS Version	| 0.8.0-rc2_1_ga10d50f

### Describe the problem you're observing

Wrong doc link on multihost-SUSPENDED pool

http://zfsonlinux.org/msg/ZFS-8000-K4 doesn't say anything about multihost.

### Describe how to reproduce the problem

```[root@XX ~]# zpool status
  pool: vol1
 state: SUSPENDED
status: The pool is suspended because multihost writes failed or were delayed;
	another system could import the pool undetected.
action: Make sure the pool's devices are connected, then reboot your system and
	import the pool.
   see: http://zfsonlinux.org/msg/ZFS-8000-K4
  scan: none requested
config:
```

**Comment by bunder2015** [comment]
I wonder if lib/libzfs/libzfs_status.c and include/libzfs.h are out of sync.  Also over on the issue tracker for the website, there is an open issue for a missing error page (A5).  https://github.com/zfsonlinux/zfsonlinux.github.com/issues/41

**Comment by bunder2015** [comment]
Looking around a little more, I'm not sure we have an error code defined for ZPOOL_STATUS_IO_FAILURE_MMP, which was in K4's place before MMP was added.
