### ISSUE TITLE
zfs create - error message for @ or # in name improvement

### ISSUE THREAD

**Issue by Lady-Galadriel** [zfsonlinux/zfs#8155]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Gentoo
Distribution Version	| Rolling
Linux Kernel	| 4.14.83-gentoo
Architecture	| AMD64
ZFS Version	| 0.7.9-r0-gentoo
SPL Version	| 0.7.9-r0-gentoo

### Describe the problem you're observing
When a snapshot symbol, `@`, or bookmark symbol, `#`, is used for the first character of a dataset name, (and probably zvol), the error message is not as clear as it could be.

### Describe how to reproduce the problem
`root # zfs create amypond/@`
`cannot create 'amypond/@': empty component in name`

`root # zfs create amypond/@test`
`cannot create 'amypond/@test': empty component in name`

`root # zfs create amypond/#`
`cannot create 'amypond/#': empty component in name`

`root # zfs create amypond/#test`
`cannot create 'amypond/#test': empty component in name`

### Include any warning/errors/backtraces from the system logs
Not relevant.

### Proposed fix:
Please note that the normal error message when one of the symbols is used part way through the name is perfect;

`root # zfs create amypond/test@test`
`cannot create 'amypond/test@test': snapshot delimiter '@' is not expected here`

`root # zfs create amypond/test#test`
`cannot create 'amypond/test#test': bookmark delimiter '#' is not expected here`

**Comment by Lady-Galadriel** [comment]
This new issue was brought about by discussions in #8115

**Comment by kpande** [comment]
doesn't seem to be unclear in any way. a component in the name was not given..

**Comment by rincebrain** [comment]
@kpande you attempt to create a dataset, foo/@meow, and get back "empty component in name", which means absolutely nothing to people who don't know that @ and # are special delimiters - from their perspective, both the path (foo/) and the dataset name (@meow) are non-empty, so they will assume this is a bug, or decide they don't want to look into it further and go use something else that doesn't print error messages you need experience with the system to understand.

**Comment by Lady-Galadriel** [comment]
@rincebrain, thank you for more clearly describing the issue, (better than I did).

@kpande, it's not that we need OpenZFS to be idiot proof, (idiots can be quite inventive :-). But I think we want to be neutral or friendly if possible. Not obscure in the error messages that lead to confusion.

**Comment by madwizard** [comment]
Would it be sufficient to just expand on the error message to say "empty component or illegal character in name" ?

**Comment by Rain** [comment]
Taking a quick glance at this, is there any reason why [lines 171-206](https://github.com/zfsonlinux/zfs/blob/466f55334ac9b353948d4309bbcd44573e9a3024/lib/libzfs/libzfs_dataset.c#L171-L206) can't be moved above [line 111](https://github.com/zfsonlinux/zfs/blob/466f55334ac9b353948d4309bbcd44573e9a3024/lib/libzfs/libzfs_dataset.c#L111) in [libzfs_dataset.c](https://github.com/zfsonlinux/zfs/blob/466f55334ac9b353948d4309bbcd44573e9a3024/lib/libzfs/libzfs_dataset.c)?

I don't think any error messages actually need to be changed but the informative errors specific to snapshots & bookmarks should be checked for and reported first.
