### ISSUE TITLE
Native Encryption for ZfsOnLinux?

### ISSUE THREAD

**Issue by dererk** [zfsonlinux/zfs#8159]
Hi. As for v0.7.12 (latest as for today), release lacks support of native encryption.

Native encryption was merged master some months now, and I was wondering if there's an intention to merge it into a next release of ZoL soon.

Thanks!

**Comment by kpande** [comment]
this is not a bug.

**Comment by drescherjm** [comment]
I believe it will be in v0.8 which is in rc2 now.
