### ISSUE TITLE
raw encrypted incremental receive has checksum and I/O errors

### ISSUE THREAD

**Issue by kpande** [zfsonlinux/zfs#8168]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Gentoo
Distribution Version	| ~amd64
Linux Kernel	| 4.19.5-gentoo
Architecture	| amd64
ZFS Version	| 0.8.0-rc2_11_gc40a1124
SPL Version	| 0.8.0-rc2_11_gc40a1124

### Describe the problem you're observing
I have an encrypted root pool using two SATA SSDs, and a HDD pool with special vdev on NVMe.

Wanting to migrate my root filesystem to the larger/faster special pool, I ran:

`zfs send -Rwv rpool/ocean@to_newjack | zfs recv -Fv newjack/ocean`

Copied about 200 snapshots, about 1 per week or month from sometime in May til December 2018, definitely not new data. It's a root filesystem for Gentoo, with /usr/src containing several compiled kernels, a portage tree, and so on.

the oldest was from Mon, 07 May 2018:
```
2018-12-02.07:17:42 zfs destroy rpool/vm@1525664701
2018-12-02.07:17:42 zfs destroy rpool/vm@1525751101
2018-12-02.07:17:42 zfs destroy rpool/vm@1526270401
2018-12-02.07:17:42 zfs destroy rpool/vm@1526303701
2018-12-02.07:17:42 zfs destroy rpool/vm@1527032701
2018-12-02.07:17:42 zfs destroy rpool/vm@1527050701
2018-12-02.07:17:42 zfs destroy rpool/vm@1527205501
2018-12-02.07:17:43 zfs destroy rpool/vm@1527221701
2018-12-02.07:17:43 zfs destroy rpool/vm@1527291901
2018-12-02.07:17:43 zfs destroy rpool/vm@1527309901
2018-12-02.07:17:43 zfs destroy rpool/vm@1527378301
2018-12-02.07:17:43 zfs destroy rpool/vm@1527399901
2018-12-02.07:17:43 zfs destroy rpool/vm@1527551101
2018-12-02.07:17:43 zfs destroy rpool/vm@1527570901
2018-12-02.07:17:44 zfs destroy rpool/vm@1527613201
2018-12-02.07:17:44 zfs destroy rpool/vm@1527629401
2018-12-02.07:17:44 zfs destroy rpool/vm@1527660001
2018-12-02.07:17:44 zfs destroy rpool/vm@1527723901
2018-12-02.07:17:44 zfs destroy rpool/vm@1527746401
2018-12-02.07:17:44 zfs destroy rpool/vm@1527782401
2018-12-02.07:17:44 zfs destroy rpool/vm@1527798601
2018-12-02.07:17:44 zfs destroy rpool/vm@1527911101
2018-12-02.07:17:45 zfs destroy rpool/vm@1527997501
2018-12-02.07:17:45 zfs destroy rpool/vm@1528083901
2018-12-02.07:17:45 zfs destroy rpool/vm@1528155901
2018-12-02.07:17:45 zfs destroy rpool/vm@1528170301
2018-12-02.07:17:45 zfs destroy rpool/vm@1528171201
2018-12-02.07:17:45 zfs destroy rpool/vm@1528256701
2018-12-02.07:17:45 zfs destroy rpool/vm@1528343101
2018-12-02.07:17:45 zfs destroy rpool/vm@1528344001
2018-12-02.07:17:45 zfs destroy rpool/vm@1528583401
2018-12-02.07:17:45 zfs destroy rpool/vm@1528602301
2018-12-02.07:17:46 zfs destroy rpool/vm@1528688701
2018-12-02.07:17:46 zfs destroy rpool/vm@1528775101
2018-12-02.07:17:46 zfs destroy rpool/vm@1528861501
2018-12-02.07:17:46 zfs destroy rpool/vm@1528947901
2018-12-02.07:17:46 zfs destroy rpool/vm@1528948801
2018-12-02.07:17:46 zfs destroy rpool/vm@1529023501
2018-12-02.07:17:46 zfs destroy rpool/vm@1543680901
2018-12-02.07:17:47 zfs destroy rpool/vm@1543681003
2018-12-02.07:17:47 zfs destroy rpool/vm@1543681036
2018-12-02.07:17:47 zfs destroy rpool/vm@1543681801
2018-12-02.07:17:47 zfs destroy rpool/vm@1543682701
```

Upon booting into the new root filesystem copy, I saw I/O errors when writing to /var/log and when accessing kernel modules from /lib/modules. The system did boot fully and would allow me to login, but was fairly useless due to I/O errors.

Thinking that it's an interaction between encryption and special vdev, I used a fresh test pool with just a single disk vdev and re-executed the same send|recv. Booting from this also failed, because of the same permanent errors.

Recreated the test pool and attempted to avoid incremental send/recv but there's problems:

* `zfs send -R` is the only way to preserve parent/child heirarchy and keep a single `encryptionroot` when sending a whole pool
* `zfs send -R` forces me to send every single snapshot for all datasets, making it an incremental send by default, with no way to disrupt that behaviour other than destroying snapshots or sending an incomplete set

I ended up destroying all of the (working) source snapshots to do a full non-incremental send to a fresh test pool, which booted successfully without I/O / checksum errors.

### Describe how to reproduce the problem

After I booted successfully into the full non-incremental received dataset, I created a 2nd snapshot and sent an incremental to attempt to reproduce the original issue, but it unfortunately did not.

So it sounds like some older snapshot made `zfs recv` unhappy, and not necessarily the incremental mechanism itself. I wish I'd tried attempting a full non-incremental send with one of the ancient snapshots before I'd destroyed them, because the snapshot errors were not occurring on the original rpool. They only occurred wherever the filesystems were received to.

I had a long term backup copy in my local workstation, and hadn't tried loading the key or mounting it in quite some time. Once I did, the permanent errors appeared here, too. Funny enough, I can mount `newjack/backup/rpool/ocean/HOME` without any errors but when I mounted  `newjack/backup/rpool/ocean/HOME/kash`, permanent errors show up.

I scrub once a week, which some consider excessive, but it never reports any data issues.

The machine is a Threadripper 1900X with ECC memory (X399A PRIME).

### Include any warning/errors/backtraces from the system logs

```
  pool: newjack
 state: ONLINE
status: One or more devices is currently being resilvered.  The pool will
        continue to function, possibly in a degraded state.
action: Wait for the resilver to complete.
  scan: resilver in progress since Sun Dec  2 08:02:23 2018
        2.01T scanned at 1.13G/s, 414G issued at 232M/s, 2.17T total
        265G resilvered, 18.61% done, 0 days 02:13:21 to go
config:

        NAME                        STATE     READ WRITE CKSUM
        newjack                     ONLINE       0     0     0
          mirror-0                  ONLINE       0     0     0
            wwn-0x5000cca25cce59c1  ONLINE       0     0     0
            wwn-0x5000cca25ccde9bc  ONLINE       0     0     0  (resilvering)
        special 
          mirror-1                  ONLINE       0     0     0
            nvme1n1p2               ONLINE       0     0     0
            nvme0n1p2               ONLINE       0     0     0
        logs
          mirror-2                  ONLINE       0     0     0
            nvme0n1p1               ONLINE       0     0     0
            nvme1n1p1               ONLINE       0     0     0

errors: Permanent errors have been detected in the following files:

        <0x2f20>:<0x0> < destroyed
        newjack/backup/rpool/ocean/GENTOO/NEWROOT:<0x0>
        <0x3b69>:<0x0> < destroyed
        <0x1488>:<0x0> < destroyed
        newjack/backup/rpool/ocean/HOME/kash:<0x0>
        <0x35f7>:<0x0> < destroyed

```

**Comment by kpande** [comment]
zfs get all rpool/ocean: https://pastebin.com/Mp49pWnx
zfs get all newjack/backup/rpool/ocean: https://pastebin.com/1pxzAWtx
zpool get all: https://pastebin.com/m2KNQrFk

**Comment by kpande** [comment]
```
# zdb newjack/backup/rpool/ocean/GENTOO/NEWROOT 0x0
Dataset newjack/backup/rpool/ocean/GENTOO/NEWROOT [ZPL], ID 131638, cr_txg 337314, 32.4G, 1419748 objects

    Object  lvl   iblk   dblk  dsize  dnsize  lsize   %full  type
         0    6   128K    16K  1.98G     512  1.50G   45.13  DMU dnode


ZFS_DBGMSG(zdb) START:
spa.c:4435:spa_open_common(): spa_open_common: opening newjack/backup/rpool/ocean/GENTOO/NEWROOT
spa_misc.c:406:spa_load_note(): spa_load(newjack, config trusted): LOADING
vdev.c:115:vdev_dbgmsg(): disk vdev '/dev/disk/by-id/wwn-0x5000cca25cce59c1-part1': best uberblock found for spa newjack. txg 471399
spa_misc.c:406:spa_load_note(): spa_load(newjack, config untrusted): using uberblock with txg=471399
spa_misc.c:406:spa_load_note(): spa_load(newjack, config trusted): LOADED
ZFS_DBGMSG(zdb) END

```

**Comment by kpande** [comment]
@tcaputi let me know what more you need from this.

**Comment by kpande** [comment]
interestingly I can load keys, clone, mount any of the problematic filesystems on my separate backup server which runs 4.14.78, so I'll switch to a known good kernel on this system, too.

**Comment by kpande** [comment]
4.18.20 kernel on the previously affected system allowed me to boot the backup copy of my rootfs from my encrypted special pool.

**Comment by kpande** [comment]
spoke too soon; while 4.18.20 did boot up without I/O errors far enough to start XFCE4, KDE wouldn't start because ~/.config/startupconfigkeys gave I/O errors upon access. I'm not really sure what to do now.. the I/O error occurred on a freshly received copy of the rpool without ancient snapshots.

**Comment by tcaputi** [comment]
I'm busy all today so I'll have to take a look on Monday. What would be most helpful would be to figure out which block in the metadnode is broken. You can do this by running `zpool events -v` and looking for `authentication` errors. This should list the objset number, object number (should be 0), the level (should be 0) and the blkid. Once you have that, you can run `zdb -dddd <pool> | less`. Unfortunately, at this point you need to convert that objset number into a dataset name using zdb which is more of an art than a science. At some point I should try to write a script for that, but if not I can help with it on Monday.

Once you have the dataset name, you can run `zdb -dddddddd <dataset name> <objset number from zpool events>` (as you provided above). Multiply the blkid from `zpool events` by the record size and convert it to hex. You should be looking for the `L0` block that starts at this offset (listed in the left column).

Finally, once you have that, grab the first DVA (it should look like `1:11db356c00:4000`). The last thing you need to do is run `zdb -R <DVA> <pool>` to dump the block.

I need this info on for both the source and destination version of the block. I have to go in a few minutes, so I had to type this quickly. I apologize if I missed a step. If you can wait until Monday, I will script all of this out so you can just run it and it will dump out the blocks I need.

**Comment by tcaputi** [comment]
@kpande Here is a script which should do the things I was talking about above. It doesn't really have a ton of error handling and it might not work with your pool, but it works for the reproducer given to me in issue #8103. Let me know if you have any difficulty with it.

Run the script with the pool name as the only argument. It will look at your `zpool events` to find what block is broken, so this requires that the authentication error is still present in your events. If it is not, simply export the pool, reimport it, and read whatever files are causing trouble, triggering the IO error. Then run the script again. The script also requires that your pool has a cachefile set up (`zpool set cachefile=/etc/zfs/zpool.cache`) so that the zdb commands can run.

When the script runs the first time, it will dump the first destination block that is causing the problem. It will also print (most of) a second command for you to run before the dump. Running that command will dump the source block from the send side so that I can compare the 2. Hopefully this makes more sense than the instructions I wrote in a hurry this morning.

```
#!/bin/bash

# Only works if broken block is at level 0
# Requires pool to have cache file and be imported

POOL=$1 # name of the pool containing the block to be dumped

if [ -z $2 ]; then
	if ! zpool events -v $POOL | grep -qA 18 -m 2 'ereport.fs.zfs.authentication' ; then
		echo "No authentication errors found. Please re-import the pool, re-trigger the error, and try again."
		exit 1
	fi

	EVENT=$(zpool events -v $POOL | grep -A 18 -m 2 'ereport.fs.zfs.authentication')
	OBJSET=$(echo "$EVENT" | grep 'zio_objset' | awk '{ print $3 }')
	OBJECT=$(echo "$EVENT" | grep 'zio_object' | awk '{ print $3 }')
	LEVEL=$(echo "$EVENT" | grep 'zio_level' | awk '{ print $3 }')
	BLKID=$(echo "$EVENT" | grep 'zio_blkid' | awk '{ print $3 }')
	DATASET=$(zdb -d $POOL | grep 'Dataset' | grep "ID $(printf "%d\n" $OBJSET)" | awk '{ print $2 }')

	printf "Broken block found in dataset '%s' at bookmark %x:%x:%x:%x\n" $DATASET $OBJSET $OBJECT $LEVEL $BLKID
	if [[ $LEVEL -ne 0 ]]; then
		echo "Script currently only works on level 0 blocks"
		exit 1
	fi

	echo "Once this script completes run the following command to dump source block:"
	echo "    $0 <source dataset> $OBJECT $BLKID"
	echo

else
	DATASET=$2
	OBJECT=$3
	BLKID=$4
fi

RECORDSIZE=$(zfs get -pH -o value recordsize $DATASET)
BYTEOFF=$(printf "%x\n" $(($(($BLKID)) * $RECORDSIZE)))
DVA=$(zdb -dddddddd $DATASET $OBJECT | grep '      L0' | grep "$BYTEOFF      " | head -n 1 | awk '{ print $3 }')
zdb -R $POOL $DVA
```

**Comment by kpande** [comment]
it cannot find the DVA.

```
# zdb -dddddddd newjack/ocean/HOME/kash 0x0 | grep '      L0' | grep '889e0000      ' | head -n1 | awk '{ print $3 }'
# zdb -dddddddd newjack/ocean/HOME/kash 0x0 | grep '      L0' | grep '889e0000      '                                
# zdb -dddddddd newjack/ocean/HOME/kash 0x0 | grep '      L0' | grep '889e0000'      
# zdb -dddddddd newjack/ocean/HOME/kash 0x0 | grep 'L0' | grep '889e0000'      
# 

```

**Comment by kpande** [comment]
```
+ POOL=newjack
+ '[' -z newjack/ocean/HOME/kash ']'
+ DATASET=newjack/ocean/HOME/kash
+ OBJECT=0x0
+ BLKID=0x444f
++ zfs get -pH -o value recordsize newjack/ocean/HOME/kash
+ RECORDSIZE=131072
++ printf '%x\n' 2292056064
+ BYTEOFF=889e0000
++ zdb -dddddddd newjack/ocean/HOME/kash 0x0
++ grep '      L0'
++ grep '889e0000      '
++ head -n 1
++ awk '{ print $3 }'
+ DVA=
+ zdb -R newjack

```

**Comment by kpande** [comment]
oh, right - you needed both sides. that is the corrupted (receiving) data.

here is the source pool information:

https://pastebin.com/KmfTYr2F

**Comment by tcaputi** [comment]
Can you provide the output of `zdb -dddddddd newjack/ocean/HOME/kash 0x0`?

**Comment by kpande** [comment]
I can confirm that this bug only affects incremental raw receive for encrypted datasets.

I can decrypt the problematic dataset by omitting `-Rw` from send and recv'ing into an unencrypted destination. Incrementals work fine.

If I use `-Rw` and send just the initial snapshot, then I can access contents. If I then subsequently use `-I`, I get I/O errors.

**Comment by kpande** [comment]
I created a new encryptionroot and received some non-raw (`zfs send -v ... | zfs recv`) filesystems to it, and was able to do incremental recv without issue for encrypted dataset.

so it really seems limited to something about `-Rw`, and I can't isolate which because they rely on each other.

**Comment by kpande** [comment]
happened with the repaired dataset as incr source now

```
errors: Permanent errors have been detected in the following files:

        <0xe9b5>:<0x0>

```

**Comment by tcaputi** [comment]
Unfortunately, what I really need is a way to reproduce this issue. Without that I really don't know what I can do. I can try t think about this some more this week, but its tricky to debug a problem without knowing what is wrong.

**Comment by kpande** [comment]
I've tried to come up with instructions to reproduce but it simply seems to occur while using Gentoo with ZFS root. do you run any root pools with encryption?

**Comment by kpande** [comment]
the other issue is that I can't seem to get you a copy of the source dataset, even if I manage to make a small broken set in my pool, if I use `zfs send` to get the data to you, it will be mangled already. there is no way to compare the known 'good' data to the 'bad' received data.

I would need to create a small root disk and run from that for some time until the system exhibits the issue and then dd it to a file for you to inspect.

which is why I asked if you personally are running any rootfs systems and if we can compare kernel or filesystem options? I don't think my replication procedure has anything to do with it since we were reproducing the checksum errors with a simple `zfs send -wR` or `-wI`. I was unable to see any checksum errors without an incremental recv occurring (zfs send -wR with just one snapshot works fine, but this is of limited utility).

**Comment by tcaputi** [comment]
Can you reproduce the issue by doing:
1. Do a non-raw, incremental send / receive of the dataset
2. Do a raw, incremental send / receive of the new dataset created in (1)

If so, and if you're willing to share the data with me, then that should work well enough.

**Comment by tcaputi** [comment]
@kpande It seems your email has broken. I have received the file from you and should begin looking into this more on Monday

**Comment by kpande** [comment]
@behlendorf was able to reproduce the issue today using the `ssdpool.img` sparse file mirror of the 'good' source pool (i say 'good' because scrub finds no issues, loading key and reading files works, but sending this data causes recv side corruption).

**Comment by kpande** [comment]
we (the universal we, aka @behlendorf and @tcaputi) came up with a preliminary fix, which i've verified definitely solves the issue here with the `ssdpool` and have now verified the live backups i've re-sent from `rpool` are also error-free. there will be a PR opened soon, once there is a test case available.
