### ISSUE TITLE
Importing zpool takes a long time on boot

### ISSUE THREAD

**Issue by notthebee** [zfsonlinux/zfs#8177]
### System information
Type | Version/Name
 --- | --- 
Distribution Name	|  Gentoo
Distribution Version	|  Stable with OpenRC
Linux Kernel	|  4.18.16-ck
Architecture	|  AMD64
ZFS Version	|  0.7.11
SPL Version	|  0.7.11

### Describe the problem you're observing
I recently moved my Gentoo root to ZFS, and so far everything works great, except for one thing: importing zpool takes a long time (one-two minutes) on boot.

Also, `zpool status` shows "sda" instead of disk/by-id entry, not sure if that's relevant.

### Include any warning/errors/backtraces from the system logs
zpool status:
```
  pool: gentoo
 state: ONLINE
  scan: none requested
config:

	NAME        STATE     READ WRITE CKSUM
	gentoo      ONLINE       0     0     0
	  sda       ONLINE       0     0     0

errors: No known data errors
```

zfs list:
```~ zfs list    
NAME                      USED  AVAIL  REFER  MOUNTPOINT
gentoo                   83.0G   390G    96K  none
gentoo/ROOT              83.0G   390G    96K  none
gentoo/ROOT/boot         29.6M   390G  29.6M  /boot
gentoo/ROOT/gentoo       5.11G   390G  5.11G  /
gentoo/ROOT/home         65.3G   390G  65.3G  /home
gentoo/ROOT/tmp           128K   390G   128K  /tmp
gentoo/ROOT/usr          6.21G   390G  6.21G  /usr
gentoo/ROOT/usr_local    7.26M   390G  7.26M  /usr/local
gentoo/ROOT/usr_portage  4.50G   390G  4.50G  /usr/portage
gentoo/ROOT/var          1.76G   390G  1.76G  /var
```

**Comment by kpande** [comment]
this is not a bug in ZFS, but a distribution issue. please use [the zfs-discuss mailing list](http://list.zfsonlinux.org) or IRC (details on this link too).
