### ISSUE TITLE
Indestructible recv-10191-2  temp dataset after failed zfs recv of zvols

### ISSUE THREAD

**Issue by homerlinux** [zfsonlinux/zfs#8184]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Ubuntu
Distribution Version	| 18.04.1 LTS
Linux Kernel	| 4.15.0-42-generic
Architecture	| x86_64
ZFS Version	| 0.7.5-1ubuntu16.4
SPL Version	| 0.7.5-1ubuntu1

### Describe the problem you're observing
Several days ago,  a "zfs send | ssh zfs receive" command aborted with error "destination dataset is busy" while recursively sending and incremental snapshot of *volumes*. From that moment on, it seems impossible to me to delete a received temporal dataset on destination machine.

On the SOURCE host:
```
# zfs list
zfs/VMs/yoda             2,07T  4,26T    19K  none
zfs/VMs/yoda/moodledata  1,84T  5,47T   571G  -
zfs/VMs/yoda/root         229G  4,32T  64,6G  -
zfs/VMs/yoda/swap        4,08G  4,26T  2,02G  -
```
On the DESTINATION host:
```
# zfs list
NAME                             USED  AVAIL  REFER  MOUNTPOINT
zfs-10TB                        5,40T  3,38T    19K  /zfs-10TB
zfs-10TB/VMs                    1,27T  3,38T    19K  /zfs-10TB/VMs
zfs-10TB/VMs/yoda               1,21T  3,38T    19K  none
zfs-10TB/VMs/yoda/recv-10191-2  1,21T  4,05T   551G  -
```
As you can see, a strange "recv-10191-2" Volume appears. Can't destroy neither the volume, parent volume nor pool. Always says "dataset is busy". And it is not.

Provided they are volumes, not file systems, no open files are involved, and no virtual machine is running on the destination host making use of /dev/zvol/... (I checked that fact with lsof and fuser. No opened resources, as expected).

This very same error happened before upgrading both systems from Ubuntu 14.04 LTS and ZFS 0.6.1 so, to me this is not new.

After rebooting destination, same problem, "dataset" is busy when you try to destroy, so the problem is persistent across rebootings.

The only way for me to get rid of this is:  shutdown destination host, remove disks, and clean them via wipefs.

### Describe how to reproduce the problem
using zfs send | ssh zfs receive recursively with large zfs volumes *sometimes* produces this issue.

**Comment by kpande** [comment]
this is better suited for [the zfs-discuss mailing list or IRC](http://list.zfsonlinux.org) as it is most likely not a bug. you probably have a zfs hold on the 'snapshot'.

**Comment by homerlinux** [comment]
No, I haven't any holds. Take it for granted.
