### ISSUE TITLE
`zfs list` doesn't work with 0.8.0-rc2

### ISSUE THREAD

**Issue by LGro** [zfsonlinux/zfs#8196]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu
Distribution Version	| 18.04
Linux Kernel	| Linux server 4.15.0-42-generic
Architecture	| x86_64
ZFS Version	| 0.7.5-1ubuntu16.4
SPL Version	| 0.7.5-1ubuntu1

### Observed problem
The `zpool list` command is not listing pools.

### Reproduction instructions
1. Fresh UBuntu Server 18.04 setup
1. Download https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.8.0-rc2
1. Follow https://github.com/zfsonlinux/zfs/wiki/Custom-Packages#debian-and-ubuntu without the spl setup instructions (since I assumed it is included with zfs)
1. Run `zpool list`

### Resulting error
```
bad property list: invalid property 'name'
usage:
	list [-gHLpPv] [-o property[,...]] [-T d|u] [pool] ... 
	    [interval [count]]

the following properties are supported:

	PROPERTY             EDIT   VALUES

	feature@...           YES   disabled | enabled | active

The feature@ properties must be appended with a feature name.
See zpool-features(5).
```

**Comment by kpande** [comment]
this is suited for [the zfs-discuss mailing list](http://list.zfsonlinux.org) because it is a configuration/distribution issue and not a bug in ZFS. can you please close this out, and attempt to dissect it on the list or IRC first?

**Comment by LGro** [comment]
Sure, thanks for the quick reaction.
