### ISSUE TITLE
zpool set feature@ does nothing

### ISSUE THREAD

**Issue by eu41** [zfsonlinux/zfs#8217]
### System information

Type | Version/Name
 --- | 0.7.12
Distribution Name	| Gentoo
Distribution Version	| latest
Linux Kernel	| 4.19.7
Architecture	| x86_64
ZFS Version	| 0.7.12
SPL Version	| 0.7.12

### Describe the problem you're observing
zpool set feature@ has no effect on the feature I want to change

### Describe how to reproduce the problem
zpool set feature@edonr=disabled mypool
zpool get feature@edonr mypool, still shows it as enabled

same for userobj_accounting

**Comment by loli10K** [comment]
https://github.com/zfsonlinux/zfs/blob/00f198de6b6ac663926bff2666d956a61cea85db/man/man5/zpool-features.5#L91-L92

**Comment by eu41** [comment]
Then what is the point of "zpool set feature@=disabled?

I just created mypool, it is empty and I want to disable those two features before starting to use it.
I should be allowed to do it!
