### ISSUE TITLE
No zpool.cache file created and zpools are not loading when the system reboots

### ISSUE THREAD

**Issue by caraghavendravarma** [zfsonlinux/zfs#8252]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Debian Stretch
Distribution Version	| Debian 9.1
Linux Kernel	| 4.9.0-3
Architecture	| amd64
ZFS Version	| 0.8.0-rc2_42_g06f3fc2a4
SPL Version	| 0.8.0-rc2_42_g06f3fc2a4

### Describe the problem you're observing

Zpools not importing automatically when the system boots.
After booting the system, manual importing using the command (zpool import pool-name) works fine.

Please help in importing the zpool automatically when the system reboots else should i write any startup script for importing the pools at the time of booting the system, if so please let me know the procedure for having a startup script in debian 9.

### Describe how to reproduce the problem

Installed debian 9.1 OS on a Virtual machine and installed zfs(compiled and installed) using the git source link (https://github.com/zfsonlinux/zfs.git).
created a zpool using below command
command: zpool create pool-name raidz1 disk1 disk2

**Comment by kpande** [comment]
this is a support / configuration issue which belongs on [zfs-discuss or IRC](http://list.zfsonlinux.org)
