### ISSUE TITLE
Linux 5.0: 'SUBDIRS' will be removed after Linux 5.3

### ISSUE THREAD

**Issue by bunder2015** [zfsonlinux/zfs#8257]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| fedora rawhide
Distribution Version	| fc30
Linux Kernel	| 5.0.0-0.rc1.git0.1.fc30.x86_64
Architecture	| x86_64
ZFS Version	| master
SPL Version	| master

### Describe the problem you're observing
http://build.zfsonlinux.org/builders/Fedora%20Rawhide%20x86_64%20%28TEST%29/builds/1682/steps/shell_1/logs/make

```
make[4]: Entering directory '/tmp/spl-build-buildbot-Cu6g0KeK/BUILD/spl-kmod-0.7.12/_kmod_build_5.0.0-0.rc1.git0.1.fc30.x86_64/module'
make -C /usr/src/kernels/5.0.0-0.rc1.git0.1.fc30.x86_64 SUBDIRS=`pwd`  CONFIG_SPL=m modules
make[5]: Entering directory '/usr/src/kernels/5.0.0-0.rc1.git0.1.fc30.x86_64'
Makefile:189: ================= WARNING ================
Makefile:190: 'SUBDIRS' will be removed after Linux 5.3
Makefile:191: Please use 'M=' or 'KBUILD_EXTMOD' instead
Makefile:192: ==========================================
```

### Describe how to reproduce the problem
run the bots

### Include any warning/errors/backtraces from the system logs
see above

**Comment by tonyhutter** [comment]
I can reproduce this on a rawhide VM.  Assigning to myself.
