### ISSUE TITLE
Cannot export an upgraded pool after mounting it readonly

### ISSUE THREAD

**Issue by infobrand** [zfsonlinux/zfs#8276]
### System information

Type | 0.7.12
Distribution Name	| Ubuntu
Distribution Version	| 18.04
Linux Kernel	| 4.15.0-43
Architecture	| X64
ZFS Version	| 0.7.12-0york0~18.04
SPL Version	| 0.7.12-0york0~18.04

### Describe the problem you're observing
1. Mount a pool RW;
2. Upgrade the pool to the latest ZFS version
3. Export the pool directly after issuing upgrade command
4. Mount the pool Read Only
5. Exporting the pool, the export command hangs with no error message and no disk activity, forever.
6. Even shutting down the system hangs.

How to resolve this issue:

1. Poweroff the computer completely
2. Poweron
3. Mount the pool RW
4. Let ZFS background service upgrading the rest of the pool silently (do not re-issue the upgrade command once again)
5. When there is no disk activity anymore, export the pool
6. Now you can mount the pool readonly and export it again

Somehow, after upgrading a pool, ZFS tries to silently do its job on the pool, even if it's mounted readonly, which shouldn't occur.

Example:
```
this is an example how log text should be marked (wrap it with ```)
```
-->

**Comment by loli10K** [comment]
This was fixed in https://github.com/zfsonlinux/zfs/commit/bb1be77a35d3cf5389a36f1d13935811962278c3, closing.
