### ISSUE TITLE
Linux 5.0: bio_associate_blkg() now GPL'd

### ISSUE THREAD

**Issue by tonyhutter** [zfsonlinux/zfs#8287]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Fedora
Distribution Version	| 30 (rawhide)
Linux Kernel	| 5.0.0-0.rc1.git0.1.fc30.x86_64
Architecture	| x86-64
ZFS Version	| master
SPL Version	| master

### Describe the problem you're observing
`bio_associate_blkg()` is now GPL'd:

https://lore.kernel.org/lkml/20181205171039.73066-7-dennis@kernel.org/
### Describe how to reproduce the problem
Build master in rawhide.

### Include any warning/errors/backtraces from the system logs
`FATAL: modpost: GPL-incompatible module zfs.ko uses GPL-only symbol 'bio_associate_blkg'`

**Comment by tonyhutter** [comment]
We call the function via `bio_set_dev()`.

**Comment by johnreitan** [comment]
> We call the function via `bio_set_dev()`.

bio_set_dev() is just a define for a do {} while 0; loop which included a call to bio_associate_blkg, so doesn't help.
