### ISSUE TITLE
Certain desktop applications cannot work on ZFS

### ISSUE THREAD

**Issue by tomposmiko** [zfsonlinux/zfs#8295]
### System information
Type | Version/Name
 --- | --- 
Distribution Name | Ubuntu Disco 
Distribution Version	| 19.04
Linux Kernel	| 4.20.0-042000rc7-generic
Architecture	| AMD64
ZFS Version	| 0.8.0-rc3 
SPL Version	| 0.8.0-rc3 

### Describe the problem you're observing

Certain desktop application cannot work properly on ZFS.
- Thunderbird cannot load extensions.
- Slack cannot start (at least if it is installed by snap).

### Describe how to reproduce the problem
- Thunderbird
If TB is installed on another filesystem (eg. btrfs) with addons and copied to ZFS, TB starts, but addons are not loaded.

- Slack
$ sudo snap install slack
$ slack

Output is `permission denied`.

**Comment by kpande** [comment]
this is not an issue with the 4.20.0 and git master on gentoo with thunderbird. I do not use slack. this seems to be a configuration issue. please close this and use [zfs-discuss](http://list.zfsonlinux.org) for support.

**Comment by grahamc** [comment]
Slack works fine on ZFS, this bug might lay in Snap.

**Comment by tomposmiko** [comment]
Ehh, title fixed finally:)

Let me test it with standard Ubuntu kernel and Slack without snap.
Thanks.

**Comment by tomposmiko** [comment]
Ehh, title fixed finally:)

Let me test it with standard Ubuntu kernel and Slack without snap.
Interestingly, TB just started working. Hi Murphy, how are you?

And indeed, it's rather not a slack, but snap issue, I will open a new issue.
Sorry for the noise.
