### ISSUE TITLE
Ubuntu snap cannot work on ZFS

### ISSUE THREAD

**Issue by tomposmiko** [zfsonlinux/zfs#8296]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu Disco 
Distribution Version	| 19.04
Linux Kernel	| 4.20.0-042000rc7-generic
Architecture	| amd64
ZFS Version	| 0.8.0-rc3
SPL Version	| 0.8.0-rc3

### Describe the problem you're observing
Snap cannot work at all if it's on ZFS:

$ vlc
cannot create user data directory: /tank/tompos/snap/vlc/770: Read-only file system

$ slack
cannot create user data directory: /tank/tompos/snap/slack/10: Permission denied

$ xonotic
cannot create user data directory: /tank/tompos/snap/xonotic/34: Read-only file system

$ lxc
cannot create user data directory: /tank/tompos/snap/lxd/9886: Read-only file system

### Describe how to reproduce the problem
$ snap install <application>

ps.: Thanks to the snap product devs for the naming.

**Comment by kpande** [comment]
how is this a ZFS issue?

**Comment by ghfields** [comment]
Check the zfs mailing list (Subject: ffmpeg on ZFS).  Turned out ffmpeg snap app didn't work while apt version did.  Seemed to be filesystem sandboxing imposed by snap.

http://list.zfsonlinux.org/pipermail/zfs-discuss/2018-December/033025.html
