### ISSUE TITLE
initrd script is broken if /bin/plymouth exists on system

### ISSUE THREAD

**Issue by runderwo** [zfsonlinux/zfs#8306]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Debian
Distribution Version	| stretch-backports
Linux Kernel	| 4.19.0-0.bpo.1-amd64
Architecture	| amd64
ZFS Version	| 0.8.0~rc2-0-0
SPL Version	| 0.8.0~rc2-0-0

### Describe the problem you're observing

I apologize for not having a screenshot of this, but if /bin/plymouth exists and the initramfs script uses it to get the password from the console to decrypt an encrypted dataset containing the root filesystem, the zfs load-key command then fails because of the single quotes surrounding the encrypted dataset in the zfs command that is fed to plymouth.

### Describe how to reproduce the problem

Install plymouth, create a initramfs, and try to decrypt an encrypted dataset containing the root filesystem at boot.

**Comment by ghfields** [comment]
Background:
Single quotes were added midway through pull request because of review comments (those comments seem decimated by github):
https://github.com/zfsonlinux/zfs/pull/8093#issuecomment-437152642

It was also mirrored in dracut: https://github.com/zfsonlinux/zfs/pull/8114

As that pull states... it was intended not break pools with spaces in their names.

**Comment by kpande** [comment]
that is not an issue here..

**Comment by runderwo** [comment]
To be clear, I am not at all recommending that the quotes be removed, but rather if plymouth support is important, that the command string be passed through to plymouth ask-for-password in a way that has correct semantics.  Plymouth support is actually not important to me; I removed it from the system once I realized what was going wrong in the initrd.

**Comment by kpande** [comment]
maybe you have an old version of plymouth. which were you running?

**Comment by runderwo** [comment]
https://packages.debian.org/stretch/plymouth - up to date system

**Comment by rlaager** [comment]
See PR #9202

**Comment by rlaager** [comment]
This should be fixed by #9202.
