### ISSUE TITLE
Unexpected metadata misses

### ISSUE THREAD

**Issue by shodanshok** [zfsonlinux/zfs#8311]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| CentOS
Distribution Version	| 7.6
Linux Kernel	| 3.10.0-957.1.3.el7.x86_64
Architecture	| x86-64
ZFS Version	| 0.7.12
SPL Version	| 0.7.12

### Describe the problem you're observing
Unexpected, frequent metadata misses reported by `arcstat.py`, even after repeated directory list/walk and no ARC pressure. Even `primarycache=metadata` was attempted, without success. No real disk I/O seems to hit the physical disks.
### Describe how to reproduce the problem
Basically, I am issuing `du -hs` against a unpacked linux kernel 
directory tree (~66000 files).

The directory is under tank/test, which has the following local properties:
```
[root at singularity 0]# zfs get all tank/test | grep local
tank/test  compression           lz4                    local
tank/test  atime                 on                     local
tank/test  primarycache          metadata               local
tank/test  secondarycache        none                   local
tank/test  relatime              on                     local
```
Running "time du -hs" give the following output:
```
[root at singularity 0]# sync; echo 3 > /proc/sys/vm/drop_caches; while 
true; do time du -hs linux-4.20.1/; done
500M    linux-4.20.1/

real    0m1.226s
user    0m0.087s
sys     0m1.138s
500M    linux-4.20.1/

real    0m0.300s
user    0m0.063s
sys     0m0.237s
500M    linux-4.20.1/

real    0m0.298s
user    0m0.071s
sys     0m0.227s
500M    linux-4.20.1/

real    0m0.297s
user    0m0.064s
sys     0m0.233s
500M    linux-4.20.1/
...
```
On another terminal, I am running `arcstat.py 1`:
```
[root at singularity ~]# arcstat.py 1
     time  read  miss  miss%  dmis  dm%  pmis  pm%  mmis  mm%  arcsz    c
11:19:19     0     0      0     0    0     0    0     0    0   175M 249M
11:19:25  208K  4.9K      2  4.9K    2     0    0  4.9K    2   164M 249M
11:19:26   92K  8.7K      9  8.7K    9     0    0  8.7K    9   175M 249M
11:19:27   55K  9.5K     17  9.5K   17     0    0  9.5K   17   175M 249M
11:19:28   44K  7.7K     17  7.7K   17     0    0  7.7K   17   175M 249M
11:27:32   56K  9.6K     16  9.6K   16     0    0  9.6K   16   175M 249M
11:27:33   57K  9.8K     17  9.8K   17     0    0  9.8K   17   175M 249M
11:27:34   58K   10K     17   10K   17     0    0   10K   17   175M 249M
11:27:35   57K  9.7K     17  9.7K   17     0    0  9.7K   17   175M 249M
11:27:36   57K   10K     17   10K   17     0    0   10K   17   175M 249M
11:27:37   56K  9.4K     16  9.4K   16     0    0  9.4K   16   175M 249M
```
As you can see, the first run (the one with empty cache) commands much more reads, and I can see the corresponding reads via `zpool iostat -v 1`.

What I do not understand are the following runs, where a) total reads are much lower, b) total misses remain the same and, consequently, c) miss% goes up.

Having a warm cache, I really expected *all* metadata to be cached in the ARC. At the same time, this seems confirmed by `zpool iostat -v 1` (or `iostat -x -k 1`), which does show *no* reads are issued to the underlying disks.

What am I missing?
Thanks.

For reference: http://list.zfsonlinux.org/pipermail/zfs-discuss/2019-January/033124.html

**Comment by shodanshok** [comment]
I have no problem closing the issue and continuing on the mailing list (were I alredy submitted my findings), but I opened a issue here because higher than expected metadata misses can significanly lower IO performance. Regarding pool properties, all other non-local one are at default values. Thanks.

**Comment by loli10K** [comment]
Duplicate of #6589

**Comment by shodanshok** [comment]
@loli10K it does not seems a duplicate of https://github.com/zfsonlinux/zfs/issues/6589 to me... I do not see reversed hit/miss stats, rather *unexpected* misses when *all* metadata should already be in ARC.

**Comment by kpande** [comment]
removed duplicate mark. though both could be resolved by the same issue, considering page cache is only used by mmap() on ZFS.

**Comment by loli10K** [comment]
I believe this is a duplicate, i reproduced this and can confirm it is embedded BPs causing the issue. This can't be reproduced on encrypted datasets or pools with `feature@embedded_data=disabled`.

**Comment by dweeezil** [comment]
@loli10K Yes, I think you're correct.  See #8319 for a proposed fix.  The reason this is do prevalent on a "du -sh" type of operation on a Linux kernel tree is the 6000-7000 small directories it contains, most of which are represented by a single embedded data blkptr.

**Comment by kpande** [comment]
yes, it is aesthetic only unless some internal logic uses this statistic to make any meaningful decision.

**Comment by shodanshok** [comment]
Ok, I'm closing now. Thanks to all involved.
