### ISSUE TITLE
Zol on rtos

### ISSUE THREAD

**Issue by CirrusThink** [zfsonlinux/zfs#8336]
Are there any tested cases of installing / using Zol in a RTOS linux distro that does not interfere with the CPU running real time operations ? We have a requirement to be able to limit the FS to run on a specif/s number of CPU's in order to prioritize the kernel usage. The distro in particular is https://www.concurrent-rt.com/solutions/linux/ RedHawk Linux

**Comment by bunder2015** [comment]
Please use the [mailing list](https://github.com/zfsonlinux/zfs/wiki/Mailing-Lists) for non-bug questions and support, thanks.
