### ISSUE TITLE
Request: Code of Conduct

### ISSUE THREAD

**Issue by community35** [zfsonlinux/zfs#8344]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  -
Distribution Version	|  -
Linux Kernel	|   -
Architecture	|   -
ZFS Version	|   -
SPL Version	|   -

### Describe the problem you're observing
This project needs a Code of Conduct.

### Describe how to reproduce the problem
https://github.com/zfsonlinux/zfs/issues/7960#issuecomment-457890088

**Comment by kpande** [comment]
the comment you linked seems to be my comment talking about how hostility is not welcome in the project.

a CoC is unnecessary, the only thing it seems to do is bring about more "exciting" events that unfold emotionally.

you'd hope the rules are common sense and go without saying: don't call others names, don't abuse those who are trying to help you.

**Comment by community35** [comment]
I ask you to reconsider, and please stop closing issues or deleting comments you don't like.

**Comment by kpande** [comment]
ok, let's reconsider it then.

I don't delete comments because I don't like them. the only time comments are ever **deleted** is when they contain some hostility that is unwelcome. calling someone a primadonna and using womens' menstruation as pejorative is unacceptable - where would **that** fit in on your Code of Conduct?

I minimise comments when they are off-topic, but this doesn't prevent someone from seeing what was said, it only de-clutters the ticket interface.

I lock issues that have too many commenters not adding to the conversation, so, if you want to keep issues open, don't contribute needless commentary.

**Comment by community35** [comment]
Are you going to add a Code of Conduct?

**Comment by gmelikov** [comment]
@community35 it's not the best way to ignore existing rules of issue creation when you want to propose some more rules. I agree with @kpande opinion, CoC is unnecessary here. It is a bug tracker. You have a bug - you write here. For support and other things we have other methods of communicaton - for ex. mailing lists.

**Comment by kpande** [comment]
it's also notable that @community35 is a [sock puppet account](https://en.wikipedia.org/wiki/Sockpuppet_(Internet)) created just for the purpose of this troll-like issue.

**Comment by K1773R** [comment]
@community35 from your profile: "Joined 9 hours ago".
You comment here with a new account about something you didn't like in the past?
I don't see any good which a CoC would do for ZoL, please take your SJW things elsewhere...

**Comment by community35** [comment]
> You are here to defend people that insult others.

Well, i am not in fact here for that reason @K1773R.

@gmelikov i meant banned from irc, not mailing list. There are logs of zfsonlinux oper being toxic and banning users. Some members of the zfsonlinux github team idle in the irc channel and they should know and have already reported this: we *need* a Code of Conduct.

**Comment by kpande** [comment]
no one has been banned from the mailing list with the exception of FransUrbo, but even his ban was rescinded after 3 months. no one else has been callous or upsetting enough to warrant any removal.

I don't even recall anyone being banned from the Github issue tracker? and there have been a couple who really got close..

on IRC, you were warned that you were skating on thin ice, and you kept going.

let me know when you want this issue closed/locked. until then, it's open for community comment on Code of Conduct.

**Comment by community35** [comment]
> I don't even recall anyone being banned from the Github issue tracker?

Oh, but we do. At least some of us, and we had to create new accounts.

> on IRC, you were warned that you were skating on thin ice, and you kept going.

Can you post the logs here so we can all agree it was a mistake?

**Comment by kpande** [comment]
> Oh, but we do. At least some of us, and we had to create new accounts.

dishonesty will get you nowhere. Brian is the only one with power to ban an account. if you have been banned, then he had **good reason**.

**Comment by beren12** [comment]
I assume you are "cluelessuser" on irc? even if not, if you keep not listening to advice and/or doing boneheaded things yes, you will get banned for a bit. If you don't like the level of support you receive, please contact billing and request a partial refund of your support contract.

**Comment by community35** [comment]
@beren12 your assumption is wrong.

```
< xedniv> whats the situation with 8.0 in terms of stable release?
< DeHackEd> 0.8.0 ?
< xedniv> yes typo
< DeHackEd> official statement: https://github.com/zfsonlinux/zfs/milestone/12
< DeHackEd> (is it loading the issue list for anyone? it won't load for me)
< xedniv> i had issues this week with github and the issue list
< xedniv> across different projects
< DeHackEd> oh good. it's not just my broken DSL connection..
< xedniv> it literally did not show the Issues tab in one case
< xedniv> im rebuilding rc3 with the few patches i had mostly for issues with hardened configs... will reboot soon. dat feel @ building and using experimental trees on a system that actually has valuable data.
< xedniv> (backed up, but still)
< bunder> DeHackEd: that links works for me, as does https://github.com/zfsonlinux/zfs/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.8.0
< bunder> but github is a weird infrastructure
< DeHackEd> that works...
< xedniv> not bad
< xedniv> 27 issues arent that many after a quick look, most seem relatively benign
< xedniv> except for the attr NULL deref
< xedniv> seems it hit someone else
< bunder> i mailed them last week, turns out if you try to accept an invite to a private repo, but you're not logged in, you get a 404 instead of a login page
< DeHackEd> hahaha
< DeHackEd> microsoft finally showing their ownership of github
<@zfs> [zfsonlinux/zfs] bcache & zfs results in minor corruptions (#8340) created by clefru <https://github.com/zfsonlinux/zfs/issues/8340>
< xedniv> ill be more concerned about MS's stance on copyright and other things... while theres some plagiarism and crap that goes on, there is also a ton of useful reverse engineering and "questionable" content on github that rubs wrong some people
< xedniv> we will see if we have another 'code of conduct' fiasco that is a thinly veiled effort to curb stuff like reverse eng, or research on all things that are politically incorrect
<@zfs> [zfsonlinux/zfs] bcache & zfs results in minor corruptions (#8340) comment by Rich Ercolani <https://github.com/zfsonlinux/zfs/issues/8340#issuecomment-457847591>
<@zfs> [zfsonlinux/zfs] System lockup when rsync'ing files between zpools (#7867) comment by Cory Coager <https://github.com/zfsonlinux/zfs/issues/7867#issuecomment-457855821>
<@zfs> [zfsonlinux/zfs] System lockup when rsync'ing files between zpools (#7867) comment by Cory Coager <https://github.com/zfsonlinux/zfs/issues/7867#issuecomment-457855821>
<@zfs> [zfsonlinux/zfs] System lockup when rsync'ing files between zpools (#7867) closed by Cory Coager <https://github.com/zfsonlinux/zfs/issues/7867#event-2098973219>
< PMT> I love waking up to my server's root SSD having shit the bed.
<@ptx0> xedniv: "mostly benign" #8186
<@zfs> [zfs] #8186 - OpenZFS 9963 - Separate tunable for disabling ZIL vdev flush by behlendorf  <https://github.com/zfsonlinux/zfs/issues/8186>
<@ptx0> oops
<@ptx0> #8168
<@zfs> [zfs] #8168 - raw encrypted incremental receive has checksum and I/O errors  <https://github.com/zfsonlinux/zfs/issues/8168>
< xedniv> ptx0, "mostly" is the keyword
<@ptx0> and yet you run it on a system with valuable data despite corruption bugs
<@ptx0> interesting
< xedniv> i dont use that feature.
< xedniv> https://www.merriam-webster.com/dictionary/mostly < too
<@ptx0> no one even knows what the root cause of the corruption is. do you have some insight no one else does to know whether it's limited to that feature?
< xedniv> i dont think you are on my payroll for risk assessment, though. thanks for the pro bono advice...
-!- mode/#zfsonlinux [+b *!*xedniv@unaffiliated/moldenauer] by ptx0
-!- xedniv was kicked from #zfsonlinux by ptx0 [bye felicia]
<@ptx0> come in here ask for help and then insult people who do it
<@ptx0> not welcome here
<@ptx0> in case anyone thinks this is just a hair-trigger reaction, look through your logs to see how much BS that user causes when people are trying to help them in the past
```

**Comment by kpande** [comment]
```
< xedniv> we will see if we have another 'code of conduct' fiasco that is a thinly veiled effort to curb stuff like reverse eng, or research on all things that are politically incorrect
```

isn't that ironic? your own cherry picked section of logs shows how your request is a thinly veiled effort to... well..

if, as you said, you have been banned from github before and created an account to bypass said ban, ths issue should be closed and you should respect the repo owners' policy.

**Comment by community35** [comment]
@kpande can you explain how that user insulted you and why it deserved to be kicked from the channel?

**Comment by kpande** [comment]
```
< xedniv> i dont think you are on my payroll for risk assessment, though. thanks for the pro bono advice...

```

it was repeated behaviour like this insulting the people who are helping you that got you forcibly ejected from the IRC channel and then you came on here to involve others who just want to keep working on the project.

**Comment by ahrens** [comment]
The discussion in this thread has not been productive. In the future, please speak respectfully to fellow contributors. @behlendorf and I are working on putting a process in place for handling inappropriate behavior. In the meantime, please feel free to contact either Brian or I privately if you have concerns about the behavior of ZFSonLinux community members.
