### ISSUE TITLE
Upgrading LUKS+ZFS root pool on Ubuntu 18.04 to 18.10 can lead to a system unable to boot.

### ISSUE THREAD

**Issue by stevenj** [zfsonlinux/zfs#8357]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Ubuntu
Distribution Version	|  18.10
Linux Kernel	|  Any
Architecture	|  Any
ZFS Version	|  Any
SPL Version	|  Any

### Describe the problem you're observing

Upgrading from Ubuntu 18.04 to 18.10 when using LUKS encrypted root volumes can lead to a system that is unable to boot.

### Describe how to reproduce the problem

Have a LUKS+ZFS setup with the root volume encrypted working in 18.04 and upgrade to 18.10.
When the initramfs is generated, the following warning may be emitted.  Which means that its more than likely the next reboot will not work because the initramfs will not be able to map the encrypted volumes.

### Include any warning/errors/backtraces from the system logs
```
cryptsetup: WARNING: The initramfs image may not contain cryptsetup binaries
    nor crypto modules. If that's on purpose, you may want to uninstall the
    'cryptsetup-initramfs' package in order to disable the cryptsetup initramfs
    integration and avoid this warning.
```

The problem is that in 18.04 and prior, if the cryptsetup did not know how to deal with the filesystem, it would emit a warning, but include the necessary stuff to map the encrypted volumes.  In 18.10 if cryptsetup can not identify the filesystem, then no encrypted volume support is included in the initramfs.

There is a fix.

Add the option initramfs to /etc/crypttab.  like so:
```
zfs-mirror-1 /dev/disk/by-id/ata-TS256GMSA370_B961490027-part2	none		luks,discard,initramfs
zfs-mirror-2 /dev/disk/by-id/ata-TS256GMSA370_B961490030-part2	none		luks,discard,initramfs
```

This forces the initramfs to map these even if cryptsetup doesn't understand the underlying file system.  This seems to only be required for the root pool.

This is not a problem with ZFSonLinux per se.  But a note about it would be useful in the wiki so that anyone else bitten by it knows how to fix it.

**Comment by stevenj** [comment]
Sorry I don't know how to push wiki changes, but the following is a suggested patch to document the issue:
```
diff --git a/Ubuntu-18.04-Root-on-ZFS.md b/Ubuntu-18.04-Root-on-ZFS.md
index 965635c..cc30c85 100644
--- a/Ubuntu-18.04-Root-on-ZFS.md
+++ b/Ubuntu-18.04-Root-on-ZFS.md
@@ -589,3 +589,27 @@ To be able to use UEFI in guests (instead of only BIOS booting), run this on the
        "/usr/share/AAVMF/AAVMF_CODE.fd:/usr/share/AAVMF/AAVMF_VARS.fd"
     ]
     $ sudo service libvirt-bin restart
+
+### Failed boot after upgrading from 18.04 to 18.10
+A change in cryptsetup between 18.04 and 18.10 may prevent an encrypted zfs root volume from being mapped at boot time. Which leads to a unbootable system.
+
+mkinitramfs will emit the following warning when this occurs:
+```
+cryptsetup: WARNING: The initramfs image may not contain cryptsetup binaries
+    nor crypto modules. If that's on purpose, you may want to uninstall the
+    'cryptsetup-initramfs' package in order to disable the cryptsetup initramfs
+    integration and avoid this warning.
+
+```
+
+The way to correct is to add the "initramfs" option to /etc/crypttab, eg:
+```
+zfs-mirror-1 /dev/disk/by-id/ata-TS256GMSA370_B961490027-part2 none            luks,discard,initramfs
+zfs-mirror-2 /dev/disk/by-id/ata-TS256GMSA370_B961490030-part2 none            luks,discard,initramfs
+```
+
+Then rerun mkinitramfs.
+
+If the warning disappears then you have probably averted the problem.
+
+If you are trying to recover a broken system, use a live image on a USB drive to boot, mount everything and then chroot into your filesystem to regenerate the initramfs.
```

**Comment by dcarosone** [comment]
Thankyou! I hit this problem trying to do the upgrade shortly after 18.10 was released. I've waited until now to find this solution.

**Comment by dcarosone** [comment]
I just added this option and verified that it doesn't break `update-initramfs` on 18.04, so I suggest the wording recommends doing this as a pre-upgrade step rather than as late recovery.

**Comment by stevenj** [comment]
Yes I would agree with that.  I didn't test on 18.04 but your test matches my expectation.  It can and should be done pre-emptively if possible.

**Comment by dcarosone** [comment]
And further, the fix actually works.. now running 18.10

**Comment by rlaager** [comment]
The 18.04 instructions have had initramfs since they were created.
