### ISSUE TITLE
On-disk raw send errata

### ISSUE THREAD

**Issue by tcaputi** [zfsonlinux/zfs#8375]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| All
Distribution Version	| All
Linux Kernel	| All
Architecture	| All
ZFS Version	| 0.8.0-rc3

This issue is being created to track an errata relate to raw sends. Currently, it is possible to create an unreadable dataset in zfs by doing a combination of incremental raw and non-raw sends of an encrypted dataset. This sequence of commands should not be allowed to take place, but the check for this requires that we add a new value into the `dsl_dataset_t` ZAP object and any bookmarks created from encrypted datasets. More info and steps to reproduce the issue can be found in the pull request for the fix (https://github.com/zfsonlinux/zfs/pull/8308).

**Comment by rlaager** [comment]
Since #8308 has been fixed, this is done, right?
