### ISSUE TITLE
nfs client can't see ownership or mode of zfs dataset root dir

### ISSUE THREAD

**Issue by srcc-chekh** [zfsonlinux/zfs#8376]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Proxmox VE 5.3.x / Debian 9.7
Distribution Version	|  Proxmox VE 5.3.x / Debian 9.7
Linux Kernel	|  4.15.18-10-pve
Architecture	|  x86_64
ZFS Version	|  0.7.12-pve1~bpo1
SPL Version	|  0.7.12-1

### Describe the problem you're observing

The NFS client seems to always show ownership root:root and mode 0755 for a directory which is actually a zfs filesystem on the NFS server.

### Describe how to reproduce the problem

If you do something like
zfs create tank/dataset
zfs create tank/dataset/one
zfs create tank/dataset/two

Then you put /tank/dataset into your /etc/exports and 'systemctl start nfs-kernel-server'

Then you mount that NFS share on an NFS client; the directories "one" and "two" always show root:root and mode 755 no matter what you change them to on the server side.

I tried NFS v3 and NFS v4 and I tried CentOS and Ubuntu NFS clients.

The workaround is to export individual directories like
tank/dataset/one
tank/dataset/two

I'm not sure if this is expected. I guess it's something about the NFS server traversing ZFS filesystems.

**Comment by gdevenyi** [comment]
Probably need to share your /etc/exports and /var/lib/nfs/etab

**Comment by srcc-chekh** [comment]
OK, yes, I think this is just a misunderstanding on my part about filesystem boundaries.
