### ISSUE TITLE
Remove zfs-zed hard dep from zfs-share init script

### ISSUE THREAD

**Issue by beren12** [zfsonlinux/zfs#8386]
The zfs-share init script has a requires: dependency on zfs-zed. It doesn't seem to be needed to start, it's already in the "should start/stop" list, and it can break downstream packaging where zed is split from the main package: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=915831

the systemd scripts do not have this dependency listed either.

```
--- zfs-share.orig	2019-01-04 11:26:09.076322596 -0500
+++ zfs-share	2019-01-04 11:26:32.643426954 -0500
@@ -9,8 +9,8 @@
 #
 ### BEGIN INIT INFO
 # Provides:          zfs-share
-# Required-Start:    $local_fs $network $remote_fs zfs-mount zfs-zed
-# Required-Stop:     $local_fs $network $remote_fs zfs-mount zfs-zed
+# Required-Start:    $local_fs $network $remote_fs zfs-mount
+# Required-Stop:     $local_fs $network $remote_fs zfs-mount
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Should-Start:      iscsi iscsitarget istgt scst nfs-kernel-server samba samba4 zfs-mount zfs-zed

```

**Comment by beren12** [comment]
Oh, looks like it was already suggested as a workaround: https://github.com/zfsonlinux/zfs/issues/8127#issuecomment-444020786

**Comment by behlendorf** [comment]
@beren12 that fix looks entirely reasonable to me, would you mind opening a PR for it?  You're right the `zfs-share` init script doesn't need this dependency.

**Comment by beren12** [comment]
made a PR here: https://github.com/zfsonlinux/zfs/pull/8447

**Comment by beren12** [comment]
PR accepted
