### ISSUE TITLE
ZFS install fails on Fedora 29 - unsupported kernel

### ISSUE THREAD

**Issue by pauldeg** [zfsonlinux/zfs#8394]
### System information

Type | Version/Name
 --- | Fedora 29
Distribution Name	| Fedora
Distribution Version	| 29
Linux Kernel	| 4.20.6-200.fc29.x86_64
Architecture	| x64
ZFS Version	| 0.7.12
SPL Version	| 0.7.12

### Describe the problem you're observing
ZFS 0.7.12 does not support kernels 4.20.x, yet ZFS RPM is provided for Fedora 29
### Describe how to reproduce the problem
Install fails , ZFS modules not built

**Comment by loli10K** [comment]
Duplicate of #8388

**Comment by edgan** [comment]
@pauldeg I suggest you look at my comment in #8318 . It is what I used to get it working.

**Comment by bunder2015** [comment]
Closing as duplicate
