### ISSUE TITLE
zpool create: invalid argument for this pool operation

### ISSUE THREAD

**Issue by omfdzg** [zfsonlinux/zfs#8406]
Hi just cloned 0.8.0 RC3 for a first time. 
build to .deb package abd replaced 7.5 version. 
Now seems zpool create has a bug. 

### System information
Type	Version/Name
Distribution Name	Ubuntu
Distribution Version  18.04.2
Linux Kernel	4.15.0-45-generic
Architecture	x86_64
ZFS Version	0.8.0-0
SPL Version	0.8.0-0
### Describe the problem you're observing
cannot create 'pool_name': invalid argument for this pool operation

### Describe how to reproduce the problem
 zpool create -f  -O encryption=on -O keyformat=passphrase backup1  /dev/sdq /dev/sdp
Enter passphrase:
Re-enter passphrase:
cannot create 'backup1': invalid argument for this pool operation
root@x:~/zfs# zpool create -f  backup1  /dev/sdq /dev/sdp
cannot create 'backup1': invalid argument for this pool operation
root@x:~/zfs# zpool create   backup1  /dev/sdq /dev/sdp
cannot create 'backup1': invalid argument for this pool operation
root@x:~/zfs# zpool create backup1 /dev/sdq /dev/sdp
cannot create 'backup1': invalid argument for this pool operation
root@x:~/zfs# zpool create backup1 sdq sdp
cannot create 'backup1': invalid argument for this pool operation
root@x:~/zfs# zpool create -n backup1 sdq sdp
would create 'backup1' with the following layout:
	backup1
	  sdq
	  sdp
root@x:~/zfs# zpool create -f  backup1 sdq sdp
cannot create 'backup1': invalid argument for this pool operation
root@x:~/zfs# zpool create  backup1 mirror  sdq sdp
cannot create 'backup1': invalid argument for this pool operation
root@x:~/zfs# zpool create  backup1 mirror  /dev/sdq /dev/sdp
cannot create 'backup1': invalid argument for this pool operation 

### Include any warning/errors/backtraces from the system logs
none logged

**Comment by omfdzg** [comment]
root@x:~# apt list --installed | grep zfs

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

kmod-zfs-4.15.0-45-generic/now 0.8.0-0 amd64 [installed,local]
kmod-zfs-devel/now 0.8.0-0 amd64 [installed,local]
kmod-zfs-devel-4.15.0-45-generic/now 0.8.0-0 amd64 [installed,local]
libzfs2/now 0.8.0-0 amd64 [installed,local]
libzfs2-devel/now 0.8.0-0 amd64 [installed,local]
python3-pyzfs/now 0.8.0-0 amd64 [installed,local]
zfs/now 0.8.0-0 amd64 [installed,local]
zfs-dracut/now 0.8.0-0 amd64 [installed,local]
zfs-initramfs/now 0.8.0-0 amd64 [installed,local]
zfs-test/now 0.8.0-0 amd64 [installed,local]

**Comment by omfdzg** [comment]
managed to create pool with below command anyway bug is there 

zpool create -fd tank   /dev/sdp /dev/sdq

**Comment by kpande** [comment]
unlikely to be a bug, more likely a system configuration issue. please use [IRC or zfs-discuss](http://list.zfsonlinux.org) for support.

**Comment by omfdzg** [comment]
you are right, got old kernel module installed from 0.7.5

**Comment by Hypocritus** [comment]
Thanks to both of you I had an old kernel module that needed to be refreshed with a new **zfs-dkms**, then a reinstall of the newer packages.
