### ISSUE TITLE
CentOS7 download.zfsonlinux.org missing files for 7.6

### ISSUE THREAD

**Issue by softwrx** [zfsonlinux/zfs#8412]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| CentOS
Distribution Version	| 7.6
Linux Kernel	| 3.10.0-957.5.1.el7
Architecture	| x86_64
ZFS Version	| 0.7.12
SPL Version	| 0.7.12

### Describe the problem you're observing
Kmod files for zfs on CentOS 7.6 seem to be missing from download.zfsonlinux.org RPM repo. Yum command gets 404 errors for all files when attempting to install zfs.

### Describe how to reproduce the problem
yum install http://download.zfsonlinux.org/epel/zfs-release.el7_6.noarch.rpm

edit /etc/yum.repos.d/zfs.conf and disable [zfs] and enable [zfs-kmod]

yum install zfs

returns error downloading packages.

### Include any warning/errors/backtraces from the system logs

```
kmod-zfs-0.7.12-1.el7_4.x86_64 FAILED                                          
http://download.zfsonlinux.org/epel/7.6/kmod/x86_64/kmod-zfs-0.7.12-1.el7_4.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
libnvpair1-0.7.12-1.el7_4.x86_ FAILED                                          
http://download.zfsonlinux.org/epel/7.6/kmod/x86_64/libnvpair1-0.7.12-1.el7_4.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
libuutil1-0.7.12-1.el7_4.x86_6 FAILED                                          
http://download.zfsonlinux.org/epel/7.6/kmod/x86_64/libuutil1-0.7.12-1.el7_4.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
libzfs2-0.7.12-1.el7_4.x86_64. FAILED                                          
http://download.zfsonlinux.org/epel/7.6/kmod/x86_64/libzfs2-0.7.12-1.el7_4.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
libzpool2-0.7.12-1.el7_4.x86_6 FAILED                                          
http://download.zfsonlinux.org/epel/7.6/kmod/x86_64/libzpool2-0.7.12-1.el7_4.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
spl-0.7.12-1.el7_4.x86_64.rpm  FAILED                                          
http://download.zfsonlinux.org/epel/7.6/kmod/x86_64/spl-0.7.12-1.el7_4.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
(1/10): lm_sensors-libs-3.4.0-6.20160601gitf9185e5.el7.x86 |  42 kB   00:00     
zfs-0.7.12-1.el7_4.x86_64.rpm  FAILED                                          
http://download.zfsonlinux.org/epel/7.6/kmod/x86_64/zfs-0.7.12-1.el7_4.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
(2/10): sysstat-10.1.5-17.el7.x86_64.rpm                   | 315 kB   00:00     


Error downloading packages:
  zfs-0.7.12-1.el7_4.x86_64: [Errno 256] No more mirrors to try.
  kmod-zfs-0.7.12-1.el7_4.x86_64: [Errno 256] No more mirrors to try.
  libzfs2-0.7.12-1.el7_4.x86_64: [Errno 256] No more mirrors to try.
  libnvpair1-0.7.12-1.el7_4.x86_64: [Errno 256] No more mirrors to try.
  libuutil1-0.7.12-1.el7_4.x86_64: [Errno 256] No more mirrors to try.
  spl-0.7.12-1.el7_4.x86_64: [Errno 256] No more mirrors to try.
  kmod-spl-0.7.12-1.el7_4.x86_64: [Errno 256] No more mirrors to try.
  libzpool2-0.7.12-1.el7_4.x86_64: [Errno 256] No more mirrors to try.
```

**Comment by softwrx** [comment]
Files also appear to be missing for 7.5. However files are present in the 7.4 repo (the files do not seem to work with the current 3.10.0-957 kernel, though they do work with 3.10.0-862).

**Comment by alatteri** [comment]
I just installed ZFS on CentOS 7.6 from repos without issue.

**Comment by softwrx** [comment]
Maybe it's a bad mirror that I'm being sent to, the files still aren't there for me today.

The URL below came from the errors during the yum install process.

```
$ wget http://download.zfsonlinux.org/epel/7.6/kmod/x86_64/zfs-0.7.12-1.el7_4.x86_64.rpm
--2019-02-15 21:29:50--  http://download.zfsonlinux.org/epel/7.6/kmod/x86_64/zfs-0.7.12-1.el7_4.x86_64.rpm
Resolving download.zfsonlinux.org... 52.218.249.32, 2600:1fa0:40cc:448:34da:d011::
Connecting to download.zfsonlinux.org|52.218.249.32|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-02-15 21:29:50 ERROR 404: Not Found.
```

**Comment by softwrx** [comment]
Interesting. i just noticed something... 

The filenames had el7_4 in them, even though the path had /7.6/.

I manually change the filename to use el7_6 and the file was there. So something about the repo data downloaded was bad. I'm going to try again.

**Comment by softwrx** [comment]
Digging a little deeper it seems something got hung on my system. Even though it was using the updated path for 7.6 in the download URLs, the filenames were still using the el7_4 entries. And of course 7.4 files were not in the 7.6 path. So this seems to be something that unique to my system.

Documenting what I did to correct the issue in case this bites someone else (or me again) in the future. And closing this since there's not really an issue here.

This is the procedure that finally cleaned things enough to properly install the 7.6 updates:
```
# rpm -e bfs-release
# yum install http://download.zfsonlinux.org/epel/zfs-release.el7_6.noarch.rpm
# vi /etc/yum.repos.d/zfs.conf 
```
Edit the [zfs] and [zfs-kmod]  blocks. Disable [zfs] and enable [zfs-kmod].
```
# yum clean metadata
# yum clean all
#  yum update
# reboot
```

Sadly, while this cleaned up the issue I was having with the yum update to the current release for 7.6 and kernel 3.10.0-957 it sadly does not actually work. The modules don't load or can't be found. So I still have to revert to 3.10.0-862. But at least this issue is finished.
