### ISSUE TITLE
Question: About ECC RAM

### ISSUE THREAD

**Issue by KeineK** [zfsonlinux/zfs#8441]
## Question
I am a freshman about zfs.There are some questions about if i have to use ecc ram for zfs?
- Which feature of zfs depend on ecc ram?
- if wihthout ecc, what problems will occurs or which feature cann't not work well?

**Comment by alek-p** [comment]
GitHub issues are used to track enhancements, bugs etc. so this not an appropriate place for asking questions, please use the mailing list for that.
Also read: https://jrs-s.net/2015/02/03/will-zfs-and-non-ecc-ram-kill-your-data/
