### ISSUE TITLE
zfs dracut module cannot import root zpool after kernel upgrade.

### ISSUE THREAD

**Issue by crocket** [zfsonlinux/zfs#8456]
### System information

Distribution Name	| Gentoo
Linux Kernel	| 4.19.23 and 4.14.101
Architecture	| x86_64 or amd64
ZFS Version	| 0.7.12
SPL Version	| 0.7.12

### Describe the problem you're observing

After kernel upgrade, dracut initial ramdisk cannot import root zpool which hosts my root filesystem.

Thus, I resorted to the latest git commit from [genkernel](https://github.com/robbat2/genkernel).
By setting `GRUB_CMDLINE_LINUX` to `dozfs=cache` in `/etc/default/grub` and executing `grub-mkconfig -o /boot/grub/grub.cfg`, `dozfs=cache` is passed to [genkernel/defaults/linuxrc](https://github.com/robbat2/genkernel/blob/0fdb8feba2d4e3c49ed541c6c9ebf6f2ca6f7457/defaults/linuxrc#L111-L128) which then passes the option, `-c /etc/zfs/zpool.cache` to `zpool import`.

With `GRUB_CMDLINE_LINUX` set to `dozfs=cache` in `/etc/default/grub`, genkernel's initial ramdisk imports zpool quickly.

After genkernel initial ramdisk imports zpool for the new kernel, dracut initial ramdisk can import the zpool quickly, too.

**Comment by bunder2015** [comment]
were you running 4.14.83 when you made the initrd for 4.14.101?  you need to specify --kver=4.14.101

**Comment by crocket** [comment]
I specified `--kver=4.14.101` and `--kver=4.19.23` for 4.14.101 and 4.19.23 respectively.

**Comment by ptx0** [comment]
no logs or debug info from dracut makes it impossible to fix.

**Comment by crocket** [comment]
How do I get logs or debug info? Shall I record a video of the boot process with simple framebuffer enabled?

**Comment by kpande** [comment]
use the `rd.debug` commandline option, though you might be better served on [IRC or the zfs-discuss mailing list](http://list.zfsonlinux.org) as this seems to be a configuration issue and not a bug. I cannot reproduce it.

**Comment by crocket** [comment]
This time, I couldn't get logs because simple framebuffer was not enabled.

After fixing the issue with genkernel, I cannot reproduce the issue with dracut.

I'm going to close it and report the issue again when it happens again.
