### ISSUE TITLE
Can't create pool

### ISSUE THREAD

**Issue by 53845714nF** [zfsonlinux/zfs#8468]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Debian
Distribution Version	|  stretch backports
Linux Kernel	|  4.19.0-0.bpo.2-amd64
Architecture	| amd64
ZFS Version	| 0.7.12-1~bpo9+1
SPL Version	| 0.7.12-1~bpo9+1

### Describe the problem you're observing
If I tried to create a pool with:
```
zpool create testpool /dev/sdb -f
```
I get this Message:
```
cannot create 'testpool': invalid argument for this pool operation
```
### Describe how to reproduce the problem
I tried to build zfs for Linux Kernel 4.20, that has not work. Than I install the Linux Kernel 4.19 and reboot my system, afterwards I reinstall zfs-dkms and zfsutils-linux from the backports.
### Include any warning/errors/backtraces from the system logs
[strace_zpool-create.log](https://github.com/zfsonlinux/zfs/files/2919687/strace_zpool-create.log)

**Comment by bunder2015** [comment]
Order of arguments is important, if you really need to use `-f` it should go after the verb `create` and before the pool name.

**Comment by DeHackEd** [comment]
You probably still have old versions of ZFS tools or kernel modules loaded and mixed up with newer versions of the packages. ZFS does not support mixing and match versions yet (in released versions anyway)

Not a bug. Fix your system. If compiling from source happened in the past, be sure to check `/usr/local/*` is also clean

**Comment by 53845714nF** [comment]
Thanks to you both for the quick help.
Your  were right, to clean my system was the solution.  
Sorry for my mistake, it is not a software bug in zfs.
