### ISSUE TITLE
recent kernel-fpu.m4 fails to detect __kernel_fpu_begin at capable kernels (4.2 - 4.20)

### ISSUE THREAD

**Issue by BrainSlayer** [zfsonlinux/zfs#8473]
just to make it short. i just tested 4.20 and 4.15.
with current git tree the configure script fails to detect __kernel_fpu_begin / __kernel_fpu_end on these kernels. it just fails after testing kernel_fpu_begin but does not try the alternate variant for these kernels. so effectivly all fpu based optimizations are now disabled for kernels from 4.2 to 4.20
i havent found the typo yet. but there surelly is any 

### System information

Type | Version/Name
 --- | --- 
Distribution Name	| 
Distribution Version	| 
Linux Kernel	| 
Architecture	| 
ZFS Version	| 
SPL Version	|

**Comment by tonyhutter** [comment]
Does https://github.com/zfsonlinux/zfs/pull/8363 help?

**Comment by tonyhutter** [comment]
I just tried 0.7.13 on Fedora 29 (4.20.13-200.fc29.x86_64 kernel) and it correctly detects `__kernel_fpu_*`
```
checking which kernel_fpu function to use... __kernel_fpu_*
```
```
zfs_config.h:593:#define KERNEL_EXPORTS_X86_FPU 1
```

**Comment by BrainSlayer** [comment]
after rechecking i found out its something like developer blindness and maybe too much work today. there wasnt such a issue. i will close this :-)
