### ISSUE TITLE
Silent data corruption with NFS

### ISSUE THREAD

**Issue by mazouffre** [zfsonlinux/zfs#8474]
### System information

Type | Version/Name
  --- | ---
Distribution Name	| OpenSUSE
Distribution Version	| 42.3
Linux Kernel	| 4.14.98
Architecture	| x86_64
ZFS Version	| 0.8.0-rc3_43_g0902c4577
SPL Version	| 0.8.0-rc3_43_g0902c4577

### Describe the problem you're observing
Silent data corruption after a hard reboot of a NFS server.

### Describe how to reproduce the problem
Configure a NFS export (any version) and while writing data from a NFS client do a hard reboot of the server, then check the written data when the NFS server is back online. For this test, diskchecker.pl (https://gist.github.com/bradfitz/3172656) can be used.

The output of diskchecker.pl with ZoL :
  _Total errors: 55
  Histogram of seconds before end:
     628   55_

The data corruption occurs because Linux 4.7+  introduced IOCB_DSYNC and IOCB_SYNC flags for sync writes and they are used for nfsd writes and ignored by ZFS On Linux.

For now, we use internally the following patch when we build ZoL to fix the issue on ou file servers: [ZoL_nfsd.txt](https://github.com/zfsonlinux/zfs/files/2930309/ZoL_nfsd.txt).

**Comment by grwilson** [comment]
We started testing a fix for this yesterday that was specific to our kernel. I reviewed your proposed patch and seems reasonable. Let me know if you plan to submit this patch or if you want me to.

**Comment by grwilson** [comment]
My patch is slightly different so I'm happy to provide feedback on your patch.

**Comment by ryao** [comment]
This patch appears weird when I view it as I am seeing Â in place of tabs, but otherwise, it looks sane to me.

**Comment by shodanshok** [comment]
Can I ask for more information about this problem? From my understanding, NFS exports uses the `sync` option by default, which means that the underlying file is opened with `O_SYNC` and/or that `sync` is called at each write.

Did more recent nfs version change that? What is the benefit of using per-IO (rather than per-write) sync flag (ie: `IOCB_SYNC`)?

**Comment by grwilson** [comment]
I'm extending the patch to include fixes for both read and write. I will also be addressing https://github.com/zfsonlinux/zfs/issues/8452 as well.

**Comment by mazouffre** [comment]
> We started testing a fix for this yesterday that was specific to our kernel. I reviewed your proposed patch and seems reasonable. Let me know if you plan to submit this patch or if you want me to.

I do not plan to submit my patch, it is only a quick fix for our servers. My knowledge of Linux and ZoL is somewhat limited, I prefer to let you do it.
