### ISSUE TITLE
remake_initrd needs to be yes

### ISSUE THREAD

**Issue by Rudd-O** [zfsonlinux/zfs#849]
In the DKMS branch, the code in dkms.conf that says

REMAKE_INITRD="no"

needs to be yes.  The reason it needs to be yes is because ZFS support needs to be included into the initial RAM disk after compilation.  Otherwise, ZFS fails to load upon boot, rendering ZFS-on-root setups unbootable.

Same goes for spl's dkms.conf.

Thanks in advance :-)

**Comment by behlendorf** [comment]
Closing.  This is an issue for the distribution packaging.

**Comment by Rudd-O** [comment]
What about the same thing in the case of ZFS DKMS on Fedora and Red Hat?  In these cases, clearly this repo is the source of the packaging.  Over here, whenever I upgrade the ZFS DKMS packages, I end up having to remake the initrd right after the RPM install, because the initrds will contain either no ZFS or the prior ZFS version.
