### ISSUE TITLE
Errata #4 on pool that never had encryption 

### ISSUE THREAD

**Issue by angstymeat** [zfsonlinux/zfs#8503]
### System information
Type | Version/Name
 --- | --- 
Distribution Name	|  Fedora
Distribution Version	|  24
Linux Kernel	|  4.11.12-100.fc24.x86_64
Architecture	|  x86_64
ZFS Version	| 0.8.0-rc3_103_g1af240f
SPL Version	| N/A

### Describe the problem you're observing
I had a disk failure (bad sectors) yesterday and ran two scrubs to correct the issue temporarily so I can replace the disk later this week. While the 2nd scrub was running, memory usage spiked and caused an out-of-memory problem. The server eventually rebooted on its own, and appeared to be running ok.

I decided to install the latest git master copy, and after reboot I see:

```
status: Errata #4 detected.
	Existing encrypted datasets contain an on-disk incompatibility
	which needs to be corrected.
action: To correct the issue enable the bookmark_v2 feature and backup
	existing encrypted datasets to new encrypted datasets and
	destroy the old ones.
```

The system is working fine, but I'm hesitant to follow the instructions since this zpool has never had encryption enabled.

I was going to migrate to a new set of disks in the coming weeks, anyway, but this has gotten me a little concerned.

### Describe how to reproduce the problem
Not sure.

**Comment by tcaputi** [comment]
@angstymeat can you provide the output of `zpool get all`?

**Comment by angstymeat** [comment]
Sure:
```
NAME  PROPERTY                       VALUE                          SOURCE
data  size                           7.25T                          -
data  capacity                       69%                            -
data  altroot                        -                              default
data  health                         ONLINE                         -
data  guid                           4266056777176761587            -
data  version                        -                              default
data  bootfs                         -                              default
data  delegation                     on                             default
data  autoreplace                    off                            default
data  cachefile                      none                           local
data  failmode                       wait                           default
data  listsnapshots                  on                             local
data  autoexpand                     off                            default
data  dedupditto                     0                              default
data  dedupratio                     1.00x                          -
data  free                           2.20T                          -
data  allocated                      5.05T                          -
data  readonly                       off                            -
data  ashift                         12                             local
data  comment                        -                              default
data  expandsize                     -                              -
data  freeing                        0                              -
data  fragmentation                  29%                            -
data  leaked                         0                              -
data  multihost                      off                            default
data  checkpoint                     -                              -
data  load_guid                      6008579275925553777            -
data  feature@async_destroy          enabled                        local
data  feature@empty_bpobj            active                         local
data  feature@lz4_compress           active                         local
data  feature@multi_vdev_crash_dump  enabled                        local
data  feature@spacemap_histogram     active                         local
data  feature@enabled_txg            active                         local
data  feature@hole_birth             active                         local
data  feature@extensible_dataset     active                         local
data  feature@embedded_data          active                         local
data  feature@bookmarks              enabled                        local
data  feature@filesystem_limits      enabled                        local
data  feature@large_blocks           enabled                        local
data  feature@large_dnode            active                         local
data  feature@sha512                 enabled                        local
data  feature@skein                  enabled                        local
data  feature@edonr                  enabled                        local
data  feature@userobj_accounting     active                         local
data  feature@encryption             enabled                        local
data  feature@project_quota          active                         local
data  feature@device_removal         enabled                        local
data  feature@obsolete_counts        enabled                        local
data  feature@zpool_checkpoint       enabled                        local
data  feature@spacemap_v2            active                         local
data  feature@allocation_classes     enabled                        local
data  feature@resilver_defer         enabled                        local
data  feature@bookmark_v2            disabled                       local
```

**Comment by tcaputi** [comment]
Yeah. So the code is setup to trigger the errata if it detects that you have `encryption` enabled and not `bookmark_v2`. The steps are correct (you just dont need to actually do anything with encrypted datasets because you don't have any). Just enable the bookmark_v2 feature and you should be fine.

We should make this more intuitive to users who have never used encryption before. I'll see what I can come up with.

**Comment by angstymeat** [comment]
Oh, I see what it means now. The encryption _feature_ is enabled. I thought it meant that it thought I had encrypted datasets.

**Comment by angstymeat** [comment]
Just enabled bookmark_v2 and the message is still there. I tried a `zpool clear` but it didn't go away. Does it only clear on import?

**Comment by tcaputi** [comment]
yeah it clears on import

**Comment by angstymeat** [comment]
I think the message could be a little clearer, because anything like that showing up when I run a `zpool status` causes me to immediately panic. :)

However, this is a user-comprehension issue, so you can go ahead and close it.

**Comment by tcaputi** [comment]
its fine, well leave it open while we come up with better messaging.

**Comment by rlaager** [comment]
If you're willing to break backwards compatibility somewhat, could you make enabling the encryption feature also enable bookmark_v2, possibly by making encryption depend on bookmark_v2?

**Comment by tcaputi** [comment]
We already made bookmark_v2 a dependency if encryption. Unfortunately we did not want to do anything without the user's permission so we decided not to have it automatically enable the bookmark_v2 feature

**Comment by jwittlincohen** [comment]
The errata message links to [](http://zfsonlinux.org/msg/ZFS-8000-ER) but this link is for the completely unrelated Errata #1. 

In addition, the current errata message doesn't indicate how one would go about an impacted encrypted dataset.  Even after enabling the bookmarkv2 feature, attempting a raw send results in a `cannot receive incremental stream: IV set guid missing. See errata 4` message.  Since it does not appear to be possible to receive with `-o encryption=on`, it appears that one must create a new encrypted dataset and then increment through each dataset as there is no way to do a non-raw replication send.  Is there a better way?

**Comment by tcaputi** [comment]
> The errata message links to Errata #1, but this link is completely unrelated to Errata #4.

Scroll down and you'll see all of the other erratas.

> Even after enabling the bookmarkv2 feature, attempting a raw replication send results in a cannot receive incremental stream: IV set guid missing. See errata 4 message

Is this quote from the errata page unclear?
```
If there are existing encrypted datasets, administrators will then need to back these datasets up. This can be done in several ways. Non-raw zfs send and zfs receive can be used as per usual, as can traditional backup tools. The above-mentioned steps are needed because ZFS is not able to check that a receive of (or into) an old dataset will result in a valid new snapshot. This restriction can be disabled, however, which will allow ZFS to receive a stream that results in a snapshot that can not be accessed due to authentication errors. To disable this restriction, set the zfs_disable_ivset_guid_check module parameter to 1. Streams received this way (as well as any received before the upgrade) will need to be manually checked to ensure they are not corrupted.
```
I guess maybe it should say 'The above-mentioned steps are needed _**for raw sends**_.....' and 'This restriction can be disabled, however, which will allow ZFS to receive a _**raw**_ stream....'

**Comment by jwittlincohen** [comment]
@tcaputi My mistake.  The instructions are clear.  I just didn't scroll down and thus didn't see the instructions :/

**Comment by tcaputi** [comment]
Thats fine. No worries. i'm going to close this issue since the documentation was merged last week. I'll see if theres an easy way to link to the actual errata itself.

**Comment by jwittlincohen** [comment]
@tcaputi kpande states that the corruption associated with this errata can be detected by running a scrub, so long as the encryption keys for the impacted dataset are loaded.  This may be what you meant when you stated
> Streams received this way will need to be manually checked to verify they are not corrupted. 

However, it would be nice if the errata message clarified this point.

**Comment by tcaputi** [comment]
Scrubs will not find this kind of corruption. Scrubs only check the bit-rot checksums, not the security MACs. This allows zfs to do scrubs and resilvers even when your keys aren't loaded. Unfortunately, the only way to confirm your received data is ok is to do a non-raw send of it or otherwise read it.

**Comment by tcaputi** [comment]
@jwittlincohen how is this for updated documentation in the errata page? IS there anything else that could be made clearer?

```
First, system administrators with affected pools will need to enable the
<b>bookmark_v2</b> feature on their pools. Enabling this feature will
prevent this pool from being imported by previous versions of the ZFS
software (including read-only imports). If the pool contains no encrypted
datasets, this is the only step required.

If there are existing encrypted datasets, administrators will then need
to back these datasets up. This can be done in several ways. Non-raw
<b>zfs send</b> and <b>zfs receive</b> can be used as per usual, as can
traditional backup tools.

Raw receives of existing encrypted datasets and raw receives into
existing encrypted datasets are currently disabled because ZFS is not
able to guarantee that the stream and the existing dataset came from a
consistent source. This check can be disabled which will allow ZFS to
receive these streams anyway. Note that this can result in datasets
with data that cannot be accessed due to authentication errors if raw
and non-raw receives are mixed over the course of several incremental
backups. To disable this restriction, set the
<b>zfs_disable_ivset_guid_check</b> module parameter to 1. Streams
received this way (as well as any received before the upgrade) will
need to be manually checked by reading the data to ensure they are not
corrupted. For more information on this issue, please refer to the zfs
man page section on <b>zfs receive</b> which describes the restrictions
on raw sends.
```

**Comment by jwittlincohen** [comment]
@tcaputi 

I think the Errata explanation is clear.  However, I think the man page section relating to `zfs send `and `zfs receive` would benefit from additional clarification.  These issues are only related in that the Errata states: 

> please refer to the zfs man page section on <b>zfs receive</b> which describes the restrictions
> on raw sends.

**1) In order to do a replication (`-R`) send of an encrypted dataset, `-w` must be used.  This does not appear to be documented.** 

The sections explaining `-R` and `-w` for `zfs send` do not mention this limitation:

```
       -R, --replicate
           Generate a replication stream package, which will replicate the specified file system, and all descendent file systems, up to the named snapshot.
           When received, all properties, snapshots, descendent file systems, and clones are preserved.

           If the -i or -I flags are used in conjunction with the -R flag, an incremental replication stream is generated.  The current values of proper‐
           ties, and current snapshot and file system names are set when the stream is received.  If the -F flag is specified when this stream is received,
           snapshots and file systems that do not exist on the sending side are destroyed.

 -w, --raw
           For encrypted datasets, send data exactly as it exists on disk. This allows backups to be taken even if encryption keys are not currently loaded.
           The backup may then be received on an untrusted machine since that machine will not have the encryption keys to read the protected data or alter
           it without being detected. Upon being received, the dataset will have the same encryption keys as it did on the send side, although the
           keylocation property will be defaulted to prompt if not otherwise provided. For unencrypted datasets, this flag will be equivalent to -Lec.  Note
           that if you do not use this flag for sending encrypted datasets, data will be sent unencrypted and may be re-encrypted with a different encryp‐
           tion key on the receiving system, which will disable the ability to do a raw send to that system for incrementals.
```


**2) Specifying encryption parameters with the `-o` option during a `zfs receive` fails when used with `-o keyformat=passphrase` because it requires a prompt.  However, this is not mentioned as a limitation in the man page.**

The man page states:  

> Unencrypted streams can be received as encrypted datasets, either through inheritance or by specifying encryption parameters with  the -o options.

While this would presumably work with `-o keyformat=file://</absolute/file/path`, the send fails with `-o keyformat=passphrase` because it expects a prompt for the password.

```
jason@backup-server:~$ sudo zfs send -Lcev bigbackup/rpool-server-raw-received/home@test2 | zfs receive bigbackup/ignore -o encryption=on -o keyformat=passphrase
full send of bigbackup/rpool-server-raw-received/home@test2 estimated size is 9.46G
total estimated size is 9.46G
TIME        SENT   SNAPSHOT
cannot receive new filesystem stream: Cannot use 'prompt' keylocation because stdin is in use.
```

**Comment by nixomose** [comment]
```Oh, I see what it means now. The encryption feature is enabled. I thought it meant that it thought I had encrypted datasets.```

I was under the same mistaken impression. just fyi
