### ISSUE TITLE
IO Starvation and IO Scheduling

### ISSUE THREAD

**Issue by CMCDragonkai** [zfsonlinux/zfs#8506]
I've read that ZFS on Linux suggests using deadline scheduler.

I find that some tasks occupy a lot of IO, and this IO ends up starving the interactive response of other programs. In fact I run Emacs, and when I'm doing `aws s3 sync`, it ends up completely freezing emacs and other programs.

Is there some sort of recommendation for tuning ZFS or the IO scheduler in order to maintain fairness across the IO of different programs so interactivity is maintained?

**Comment by kpande** [comment]
well, you removed the template and I don't know what kernel you use, but in any case, this is a question better for the [zfs-discuss mailing list](http://list.zfsonlinux.org). no one suggested to use  deadline, it has always been noop. with the new 5.0 kernel, you want `none` or `mq-deadline`. if you have issues with those, open a report with the needed information.
