### ISSUE TITLE
Updated kernal to v4.20.16 - that broke zfs

### ISSUE THREAD

**Issue by macmattias** [zfsonlinux/zfs#8511]
I recently installed a new Ubuntnu Server 18.04.2, in it I got an SATA III pci-e card that requires a kernal of v4.20.x.
Using ukuu to upadte to that, after this zfs module isnt loaded.
When I ask the system where it is, the module is in the v4.15.x kernel.

How do I get zfs working again?
ATM I'm running sudo dpkg-reconfigure zfs-dkms

**Comment by gmelikov** [comment]
1. Please don't remove issue template.
2. Check ZFS version, 4.20+ kernel needs 0.7.13. If you don;t have it in repos - you need to build/install it manually.
