### ISSUE TITLE
Import a pool with missing top-level vdevs

### ISSUE THREAD

**Issue by dechamps** [zfsonlinux/zfs#852]
Currently, when trying to import a pool with missing vdevs, I got this:

```
  pool: disasterpool
    id: 10403888125469171240
 state: UNAVAIL
status: One or more devices are missing from the system.
action: The pool cannot be imported. Attach the missing
    devices and try again.
   see: http://zfsonlinux.org/msg/ZFS-8000-6X
config:

    disasterpool                      UNAVAIL  missing device
      /root/disaster/zpool/active/d1  ONLINE
      /root/disaster/zpool/active/d2  ONLINE

    Additional devices are known to be part of this pool, though their
    exact configuration cannot be determined.
```

That's a shame considering ZFS is technically capable of mouting a pool with missing top-level vdevs. In fact, I managed to make this pool import again (albeit in read-only mode) by adding empty disks and then forging a ZFS label for them with nothing more than an hexadecimal editor (ah... good times) and some printk debugging to match the GUIDs in the forged labels with the contents of the MOS.

Of course there is data loss, but data from the remaining devices is still salvageable and thanks to the metadata ditto blocks, the dataset/filesystem structure is still intact. The pool mostly works in this state, except for some glitches like being unable to umount some datasets.

What I'm wondering is: ZFS seems perfectly capable of salvaging a pool with missing top-level vdevs, yet it doesn't allow me to and I have to resort to some cumbersome fiddling with labels to make ZFS believe the disks are still there. Why isn't there a feature to do this automatically? Like, for example, `zpool import -M` which would mean "I know I have missing top-level vdevs, but just do what you can and try to salvage the data I have left"?

**Comment by mailinglists35** [comment]
> @behlendorf commented on Jul 27, 2012
> [...]
> Anyway, I hear what your saying and longer term we certainly may work on improving the disaster recovery code so you can at least get something back from the pool without heroic efforts

1. is https://github.com/zfsonlinux/zfs/issues/4168 depending on this?
2. what long-term means now? since this statement was made 4 years ago (wow, that seems quite long ago, thanks for all hard development!), how long could a newbie expect that "long term" means from now on?

**Comment by rlaager** [comment]
Pavel Zakharov is working this as part of his "SPA import and pool recovery" project. The slides are not available anywhere that I'm aware of. If they become available, I'd assume they'd be linked from here:
http://open-zfs.org/wiki/OpenZFS_Developer_Summit_2016

**Comment by behlendorf** [comment]
Pavel's work was integrated for 0.8 in commit 6cb8e5306d9696d155ae7a808f56c4e46d69b64c which adds this feature.  Note that since importing a pool with a missing top-level vdev almost certainly implies data loss, the pool must be imported read-only.
