### ISSUE TITLE
Error in "Ubuntu 18.04 Root on ZFS" wiki entry?

### ISSUE THREAD

**Issue by mdPlusPlus** [zfsonlinux/zfs#8524]
>2.3 Create the boot pool:

    # zpool create -o ashift=12 -d \
          -o feature@async_destroy=enabled \
          -o feature@bookmarks=enabled \
          -o feature@embedded_data=enabled \
          -o feature@empty_bpobj=enabled \
          -o feature@enabled_txg=enabled \
          -o feature@extensible_dataset=enabled \
          -o feature@filesystem_limits=enabled \
          -o feature@hole_birth=enabled \
          -o feature@large_blocks=enabled \
          -o feature@lz4_compress=enabled \
          -o feature@spacemap_histogram=enabled \
          -o feature@userobj_accounting=enabled \
          -O acltype=posixacl -O canmount=off -O compression=lz4 -O devices=off \
          -O normalization=formD -O relatime=on -O xattr=sa \
          -O mountpoint=/ -R /mnt \
          bpool /dev/disk/by-id/scsi-SATA_disk1-part3

Maybe I'm misunderstanding something here, but shouldn't the mountpoint be `/boot` instead of `/`?

**Comment by kpande** [comment]
it should probably also use a sub-dataset and not the top-level `bpool` filesystem: #1548

**Comment by mdPlusPlus** [comment]
It's getting the following datasets:

    # zfs create -o canmount=off -o mountpoint=none bpool/BOOT
    # zfs create -o canmount=noauto -o mountpoint=/boot bpool/BOOT/ubuntu

**Comment by kpande** [comment]
`canmount=off` makes the `bpool` a container for any filesystem that will be mounted as a subdirectory of `/`. I didn't look at the wiki when I made my previous comment, I've looked it over now. but this is correct behaviour.

**Comment by rlaager** [comment]
The `bpool` hierarchy directly mirrors the `rpool` one. The expectation is that some future `beadm`-style tool would create/delete/activate `bpool/BOOT/ubuntu-$counter` (or `bpool/BOOT/ubuntu-$timestamp`) and `rpool/ROOT/ubuntu-$counter` (or `rpool/ROOT/ubuntu-$timestamp`) at the same time. This keeps the kernels and initrds in `/boot` in sync with the kernel modules installed in `/`, as well as the package manager state for the same.

**Comment by mdPlusPlus** [comment]
> `canmount=off` makes the `bpool` a container for any filesystem that will be mounted as a subdirectory of `/`. I didn't look at the wiki when I made my previous comment, I've looked it over now. but this is correct behaviour.

I take it the mountpoint is irrelevant then and setting it up with `/boot` doesn't change anything?

Oh and btw, I suppose adding instructions for an encrypted `/boot` setup would be helpful.

**Comment by rlaager** [comment]
Setting the mountpoint is completely irrelevant, as it is later changed to legacy anyway. Once the systemd mount generator is available, the legacy mountpoint step will go away, and then the mountpoint will be relevant. If there isn’t explicit brand-style support added by that time, we will need to drop the canmount=noauto so it actually mounts.

Encrypted /boot is possible. You would need to put /boot on LUKS and have GRUB prompt for a password to unlock it. To avoid double password prompting, you can use a key file in /boot to unlock the main LUKS for rpool. I’m trying to follow stock Ubuntu, though, where /boot is unencrypted and the initrd prompts for the password.
