### ISSUE TITLE
Newly created zvols processed slowly by z_zvol taskq

### ISSUE THREAD

**Issue by jgallag88** [zfsonlinux/zfs#8526]
### System information
Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu
Distribution Version	| 18.04
Linux Kernel	| 4.15.0
Architecture	| x86_64
ZFS Version	| https://github.com/delphix/zfs/commit/0245a6ea491074705df60eebf785dc3d21972710
SPL Version	| https://github.com/delphix/zfs/commit/0245a6ea491074705df60eebf785dc3d21972710

### Describe the problem you're observing
After a zvol is created, some work to make the zvol usable, such as creating device minor numbers and making the rest of the system aware of the volume, is done asynchronously. This asynchronous work is a bottleneck when creating a large number of zvols in a short period of time. There are two factors which together make this processing slow:

- The taskq which handles this processing, the `z_zvol` taskq, is limited to a single thread. The reason it is single threaded is because it is a simple way to prevent problematic re-orderings of operations, such as a zvol deletion being processed before the corresponding creation.
- Processing each zvol takes a relatively long time, primarily because it involves waiting for multiple txgs to sync in `zvol_shutdown_zv`, which is called via

        zvol_shutdown_zv+1
        zvol_release+235
        __blkdev_put+476
        blkdev_put+76
        device_add_disk+1038
        add_disk+14
        zvol_create_minor_impl+1115
        zvol_create_minors_impl+301
        zvol_task_cb+109
        taskq_thread+528
        kthread+289
        ret_from_fork+53
  `zvol_shutdown_zv` calls `txg_wait_synced` once directly and once via `zil_close`.

### Describe how to reproduce the problem

Create a large number of zvols in a short period of time, and then wait for them all to become usable:
```
for i in `seq 1 250`; do sudo zfs create -V 8M rpool/zvol$i & done; time while [[ $(find /dev/zvol/rpool | wc -l) -lt 250 ]]; do sleep .05; done
```
If the pool is otherwise basically idle, this isn't too bad
```
real	0m40.523s
user	0m3.675s
sys	0m2.442s
```
However, if I add even a moderate amount of write activity to the pool, it takes much longer, because txgs are taking much longer to sync:
```
real	87m16.629s
user	4m47.812s
sys	1m54.610s
```

**Comment by jgallag88** [comment]
One way to improve performance of zvol creation would be to allow the taskq to use additional threads. If we were to do this, we would need some alternative mechanism to prevent problematic orderings of operations. This mechanism would have to prevent not just re-ordering of operations on the same zvol, but also reordering of operations on a zvol with operations on children or parents of that zvol. For instance, if a zvol were renamed and then its child removed, `zvol_rename_minors_impl` for the parent would have to run before `zvol_remove_minors_impl` for the child, otherwise `zvol_remove_minors_impl` would look for the child using the wrong name and thus fail to do any work.

Another way to improve performance might be to avoid waiting for the txgs to sync altogether. In the call to `add_disk`, the kernel opens the zvol read-only:
```
        err = blkdev_get(bdev, FMODE_READ, NULL);
        if (err < 0)
                goto exit;
        blkdev_put(bdev, FMODE_READ);
```
Presumably both of the `txg_wait_synced` calls in `zvol_shutdown_zv` exist for the sake of ensuring that writes have made it to disk. In this case we know there were no writes. Maybe we could find a way to skip these steps if all of the opens for the zvol were read-only?

**Comment by behlendorf** [comment]
Thanks for digging in to this and providing such a clear analysis of the underlying performance problem.

> Another way to improve performance might be to avoid waiting for the txgs to sync altogether. 

This is a great idea, and I'd expect it to result in the biggest overall performance improvement.  There are a bunch of ways to go about this, but the easiest way which comes to mind would be to set a flag in the `zvol_state_t` if the device has ever been opened read/write.  If which case the `txg_wait_synced()` only needs to be done when it's set.  This would be easy to prototype and you may find that in practice it's sufficient to address most of the issue.

**Comment by jgallag88** [comment]
Thanks @behlendorf. I prototyped this approach and it looks good (the time spent in `zvol_create_minors_impl` is negligible compared to what it was before). I'll work on putting together a PR.
