### ISSUE TITLE
recv_fix_encryption_heirarchy issues

### ISSUE THREAD

**Issue by ryao** [zfsonlinux/zfs#8527]
At a glance, it appears to me that the pool would be placed in an inconsistent state if the system went down due to a power outage just as `recv_fix_encryption_heirarchy()` started to execute. I would need to dig into this more, but here is a quick question, does anyone offhand see a way to change the code update the hierachy as datasets are received such that `recv_fix_encryption_heirarchy()` could be eliminated?

Also, `recv_fix_encryption_heirarchy()` really ought to be `recv_fix_encryption_hierarchy()`.

**Comment by ryao** [comment]
The comment above the function also has "heriarchy". It should be "hierarchy".

**Comment by tcaputi** [comment]
@ryao all of the multiple-snapshot / multiple dataset receive code is by its nature non-atomic. `recv_fix_encryption_heirarchy()`. There are many places in the zfs_receive_package() code that would leave the pool in strange states in the event of a crash. The code here is also very much "best effort" (see the `progress` and `needagain` variables in `recv_incremental_replication()`)

I don't really have a good way to resolve this.

**Comment by ahrens** [comment]
I think it depends on what is meant by "inconsistent".  The pool should be usable regardless of when power is lost.  However, as @tcaputi mentioned, all multi-snapshot receives (encrypted or not) are non-atomic.  Strange (though self-consistent) states are visible while the receive is in progress, and will persist if the receive is interrupted (by either the process exiting, or the machine rebooting).

**Comment by ahrens** [comment]
Sounds like we need a search-and-replace to fix they misspelling `heriarchy`.

Does the other explanations make sense to you @ryao?  If so we'll close this issue or narrow its scope to the misspelling.

**Comment by ryao** [comment]
@ahrens It does make sense, but I still need to do some tests here to review the behavior. I will reopen this if I find anything notable.
