### ISSUE TITLE
Ztest not shown in zpool list nor zfs list

### ISSUE THREAD

**Issue by Harvie** [zfsonlinux/zfs#8542]
When i run ztest i can't see any pools or datasets using `zfs list` or `zpool list`...
Other than that te test seems to run fine. But i am not sure if something is actualy tested, because i would expect some new temporary test pool to appear in these listings...

Is ztest meant for testing actual ZFS module loaded in the kernel or just userspace tools? I don't understand how you can have test pool loaded in kernel without being able to see it.

Is this normal behaviour?

**Comment by ahrens** [comment]
ztest does not test (or interact with) the loaded kernel module.  It uses libzpool, which is a userland compilation of (most of) the same code that's compiled into the zfs kernel module.

Therefore you should not expect to see the ztest pool in `zfs/zpool list`.  This is normal.

**Comment by Harvie** [comment]
> It uses libzpool, which is a userland compilation of (most of) the same code that's compiled into the zfs kernel module.

Ah. I've used ztest from debian and zfs module i've built from git. That means i didn't tested the module at all. What should i use to stress test running ZFS to confirm it was properly deployed and configured?

**Comment by Harvie** [comment]
Also i think there should be BIG WARNING about this in ztest manpage.
I think it does not really make sense for ztest to be provided as binary package in Debian/Ubuntu.
What is the point of having precompiled ztest distributed to end users?
