### ISSUE TITLE
ZFS kernel tree integration should be more modular

### ISSUE THREAD

**Issue by ryao** [zfsonlinux/zfs#855]
ZFS should be more modular when it is integrated into the kernel source tree. In particular, I believe the following should be done:
- SPLAT and ZPIOS should be optional.
- avl, nvpair, unicode and zcommon should be invisible options like ZLIB_DEFLATE and ZLIB_INFLATE that are selected by visible options. That would allow their use by other parts of the kernel, even if ZFS itself is not selected.

**Comment by behlendorf** [comment]
Closing.  SPLAT and ZPIOS have been removed.  All of the modules are required so it may make sense to merge then, but I don't think it makes sense to create invisible build options.
