### ISSUE TITLE
[question] Get unix timestamp of latest snapshot of given dataset

### ISSUE THREAD

**Issue by Harvie** [zfsonlinux/zfs#8562]
I want to write nagios check for ZFS replication. But i can't get `zfs list` to show unix timestamp of snapshot creation date/time. I know i can probably parse formated datetime, but i think having unix timestamp would be less error prone.

**Idealy i want to get timestamps of newest (and maybe oldest) snapshot for all datasets.**
Do you think, you can add such feature to `zfs list`?

I have replication scheduled to run every 15 minutes, so i think it would be reasonable to check there is no dataset that has latest snapshot older than 1 hour...

**Comment by gmelikov** [comment]
Please read issue template next time, not just delete it. You should use mailing lists/IRC for support questions.

Offtopic - just add `-H` (scripting mode).

**Comment by Harvie** [comment]
> -H  Used for scripting mode.  Do not print headers and separate fields by a single tab instead of arbitrary white space.

Well that's useful, but it does not provide unix timestamps...

**Comment by richardelling** [comment]
`zfs get -p creation dataset@snapshot`

**Comment by drescherjm** [comment]
> zfs get -p creation dataset@snapshot
Why us the value a number like 1533115801?

I see that zfs list -p -o name,creation -t snapshot 

gets the same data but I don't know how to decode this number.

datastore4 user_public_mirror # zfs list -p -o name,creation -t snapshot
NAME                                                                      CREATION
zfs_data_0@zfs-auto-snap_monthly-2018-08-01-0930                          1533115801
zfs_data_0@zfs-auto-snap_monthly-2018-09-01-0930                          1535794207
zfs_data_0@zfs-auto-snap_monthly-2018-10-01-0930                          1538386201
zfs_data_0@zfs-auto-snap_monthly-2018-11-01-0930                          1541064601
zfs_data_0@zfs-auto-snap_monthly-2018-11-06-1724                          1541525056
zfs_data_0@zfs-auto-snap_monthly-2018-11-06-1812                          1541527974
zfs_data_0@zfs-auto-snap_monthly-2018-11-06-1833                          1541529235
zfs_data_0@zfs-auto-snap_monthly-2018-12-05-2340                          1544053203

**Comment by drescherjm** [comment]
I figured out my question so deleted. This should help
zfs list -p -o name,creation -t snapshot

**Comment by Harvie** [comment]
@drescherjm PERFECT! That is what i was looking for... Thank you very much.

**Comment by Harvie** [comment]
Any ideas how to list only snapshots for given dataset?

**Comment by ptx0** [comment]
read the man page?

**Comment by jwittlincohen** [comment]
@Harvie “zfs list -t snapshot -r pool/dataset”

**Comment by Harvie** [comment]
@ptx0 maybe i am dumb, but i was not able to find it.
@jwittlincohen I've tried this already, but this as well lists snapshots for all child datasets. eg. pool/dataset/foo/bar@something... i want only pool/dataset@something...

**Comment by Harvie** [comment]
Anyway... Thanks for the help. I've created following script that can be used by nagios to check that backups are working... So i wanted to share it in case someone finds it useful:

```bash
#!/bin/sh
#
# (c) Tomas 'Harvie' Mudrunka 2019
#
# This script goes through all ZFS datasets and checks
# if all of them have at least one snapshot newer than $time_limit seconds

time_limit=3600
#time_limit=20
debug=false
dataset_list="$(zfs list -H -p -o name -t filesystem,volume)"
snapshot_list="$(zfs list -H -p -o name,creation -t snapshot)"
current_time="$(date +%s)"

get_snapshots_by_dataset() {
	echo "$1@null	0"
	echo "$snapshot_list" | grep ^"$1"@
}

get_newest_snapshot_timestamp() {
	get_snapshots_by_dataset "$1" | cut -f 2 | grep '[0-9]' | sort -n | tail -n 1
}

status=true
echo "$dataset_list" | while read dataset; do
	current_snapshot="$(get_newest_snapshot_timestamp "$dataset")"
	time_diff="$(($current_time - $current_snapshot))"
	[ $time_diff -gt $time_limit ] && status=false
	[ "$status" = 'false' -o "$debug" = 'true'  ] &&
		echo "Latest snapshot of $dataset is $time_diff seconds old (limit is $time_limit s)"
	$status
done; exit $?
```

**Comment by ptx0** [comment]
it is the depth option.

**Comment by jwittlincohen** [comment]
> @ptx0 maybe i am dumb, but i was not able to find it.
> @jwittlincohen I've tried this already, but this as well lists snapshots for all child datasets. eg. pool/dataset/foo/bar@something... i want only pool/dataset@something...

As ptx0 said, you need the depth option.

`zfs list -t snapshot -r pool/dataset -d1` will only show snapshots for the dataset specified, with no snapshots from child datasets.
