### ISSUE TITLE
dataset name validation

### ISSUE THREAD

**Issue by behlendorf** [zfsonlinux/zfs#8564]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Any
Distribution Version	| Any
Linux Kernel	| Any
Architecture	| Any
ZFS Version	| Any
SPL Version	| Any

### Describe the problem you're observing

Dataset names are incorrectly allowed to be "." or "..", this should be detected and prevented when validating the dataset name.  Additional discussion of this issue can be found in #8115.

Duplicate of https://www.illumos.org/issues/8254
Duplicate of #8115 

### Describe how to reproduce the problem

```
# zfs create tank/.
cannot mount '/tank/.': directory is not empty
filesystem successfully created, but not mounted

# zfs create tank/..
cannot mount '/tank/..': directory is not empty
filesystem successfully created, but not mounted

# zfs list 
NAME      USED  AVAIL     REFER  MOUNTPOINT
tank      784K   831M     24.5K  /tank
tank/.     24K   831M       24K  /tank/.
tank/..    24K   831M       24K  /tank/..
```

### Include any warning/errors/backtraces from the system logs

A warning is issued that the filesystem cannot be mounted, but it will still be created.  The desired behavior is for the `zfs create` command to fail with a meaningful error.

**Comment by foxyeyes48** [comment]
Now I don't understand all of this could you please help me out I Am new
