### ISSUE TITLE
New 0.8 RC

### ISSUE THREAD

**Issue by lovesegfault** [zfsonlinux/zfs#8572]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Gentoo
Distribution Version	|  Rolling
Linux Kernel	|  5.0.5
Architecture	|  X86_64
ZFS Version	|  0.8 RC3
SPL Version	|  N/A

### Describe the problem you're observing
RC3 is a bit old and I'd like to test newly merged features (e.g. TRIM) without using `master`. It'd be nice if a new RC could be released for testing, specially for distros (like NixOS IIRC) who package the RC as a beta.

### Describe how to reproduce the problem
N/A

### Include any warning/errors/backtraces from the system logs
N/A

**Comment by behlendorf** [comment]
@bemeurer you should be able to expect an 0.8.0-rc4 tagged from master by early next week.

**Comment by whalehub** [comment]
@behlendorf Any update on this?

**Comment by drescherjm** [comment]
I think you are a little early to ask for that depending on who does the tagging.

**Comment by behlendorf** [comment]
This is being actively worked but it  has been slightly delayed so we can include a couple important bug fixes.

**Comment by mailinglists35** [comment]
Brian, sorry for the impatience - are you guys thinking about rc4 to be the base for the 0.8.0 release, as in release rc4, let it long enough to surface a few new bugs if any, then release 0.8 from it?

Or is 0.8 strictly be ready only when all [0.8 milestone bugs](https://github.com/zfsonlinux/zfs/milestone/12) are solved?

**Comment by behlendorf** [comment]
> are you guys thinking about rc4 to be the base for the 0.8.0 release, as in release rc4, let it long enough to surface a few new bugs if any, then release 0.8 from it?

Yes, that's the plan.  The remaining blockers are related to raw send/recv, and we're working on that now.

**Comment by fire** [comment]
The latest version of Fedora, version 29, has not had a release and has been broken for several months already. 

Hope this will provide an updated package.

**Comment by mskarbek** [comment]
> The latest version of Fedora, version 29, has not had a release and has been broken for several months already.
What do you mean by that? 0.7.13 works perfectly well on Fedora 29, I'm using it as a root file system. The only thing that you need to keep in check is ZoL and kernel compatibility. If you expect that you will always get the newest kernel right after its release in Fedora repository then you may get disappointed.

**Comment by behlendorf** [comment]
The [zfs-0.8.0-rc4 release](https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.8.0-rc4) has been tagged and is available for download.  Sorry about the delay.

This release is feature complete and only important bug fixes and minor changes will be applied before the final zfs-0.8.0 tag.

**Comment by fire** [comment]
zfs rc4 works and I don't see any obvious bugs. Thanks for the release.
