### ISSUE TITLE
Mailinglists down?

### ISSUE THREAD

**Issue by colttt** [zfsonlinux/zfs#8573]
It looks like that all mailing lists are down?

Sorry for spamming but I don't know how to contact the zfs-team otherwise.

**Comment by ahrens** [comment]
That's correct.  We're working on it and expect to have it back up by the end of the week.

**Comment by colttt** [comment]
Wow, ok, whats happen?

**Comment by behlendorf** [comment]
No problem.  We needed to migrate the lists to a new provider.  Sorry about the disruption.

**Comment by rlaager** [comment]
The mailing lists are back up:
https://zfsonlinux.topicbox.com/groups/zfs-discuss/Tea96bad3ca91993b/mailing-lists
