### ISSUE TITLE
Unable to create pool without -d

### ISSUE THREAD

**Issue by bonze82** [zfsonlinux/zfs#8581]
Distribution Name	| Debian Stretch
Distribution Version	| 9.8 
Linux Kernel	| 4.19.0
Architecture	| Amd64
ZFS Version	| 7.12.1
SPL Version	| 7.12.1

zpool create fails with : invalid argument for this pool operation

must force pool creation with -d
This worked fine in 6.5.9
Nothing indicated in syslogs

**Comment by behlendorf** [comment]
Can you post the exact command line usage which is failing.  i.e. `zpool create tank sda`.

**Comment by bonze82** [comment]
zpool create test /test.img

Test is a 4gb image using command
dd if=/dev/zero of=/test.img bs=1M count=4096

________________________________

**Comment by behlendorf** [comment]
I'm unable to reproduce the failure your seeing with 0.7.13.

```
$ truncate -s 4G /test.img
$ zpool create test /test.img
$ zpool status test
  pool: test
 state: ONLINE
  scan: none requested
config:

	NAME         STATE     READ WRITE CKSUM
	test         ONLINE       0     0     0
	  /test.img  ONLINE       0     0     0

errors: No known data errors
```
