### ISSUE TITLE
Provide updated link for ZFS rescue CDs

### ISSUE THREAD

**Issue by acidrop** [zfsonlinux/zfs#8582]
[available here](http://list.zfsonlinux.org/zfs-iso/) thanks to @bunder2015

_Originally posted by @kpande in https://github.com/zfsonlinux/zfs/issues/5045#issuecomment-441178537_

Can you please provide an updated link for this, now that the mailing-lists were migrated to the new servers?

G.

**Comment by ptx0** [comment]
there is no maintainer anymore. the iso are no longer being created. good luck.

**Comment by acidrop** [comment]
Ok

**Comment by beren12** [comment]
This is the latest I found: https://www.hamiltonshells.ca/zfs-iso/

**Comment by drescherjm** [comment]
All of these links are now dead. Are there alternatives?
