### ISSUE TITLE
Does cache/log device contain decrupted data from encrypted datasets?

### ISSUE THREAD

**Issue by qinq-net** [zfsonlinux/zfs#8586]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Gentoo GNU/Linux
Distribution Version	|  17.1 (20190404)
Linux Kernel	|  4.14.83-gentoo
Architecture	|  amd64
ZFS Version	|  0.8.0_rc3
SPL Version	|  N/A

### Describe the problem you're observing
I have a pool running on a low-speed HDD, and I wish to use a SDD as cache or log device. However, there are some encrypted datasets holding sensitive data. Should I use something like dm-crypt to encrypt the cache device?
### Describe how to reproduce the problem
Have a pool with encrypted datasets and unencrypted cache devices, wandering whether there are risks of data leaking.
### Include any warning/errors/backtraces from the system logs

N/A

**Comment by beren12** [comment]
You're best bet is likely to use a spacial allocation vdev for metadata and small blocks for your pool once 0.8 is released. it will have the same encryption as the rest of your pool. It won't be a cache it will be part of your pool so it's a very good idea to make it a ssd mirror vdev. Remember, there are still bugs in encryption, right now I believe with raw sends so be careful and keep backups.

**Comment by rlaager** [comment]
This is more of a question than a bug report, but I too am curious about this.

**Comment by tcaputi** [comment]
All data kept in the ZIL (in a SLOG or not) is encrypted. You don't need to do anything else.
