### ISSUE TITLE
snaptshots not showing up in zfs list -t snap

### ISSUE THREAD

**Issue by prometheanfire** [zfsonlinux/zfs#8621]
### System information
Type | Version/Name
 --- | --- 
Distribution Name	| Gentoo
Distribution Version	| Master
Linux Kernel	| 5.0.7
Architecture	| x86_64
ZFS Version	| Master as of Thu Apr 11 02:20:48 CDT 2019

### Describe the problem you're observing

    zfs snap -r slaanesh-zp00@backup-201904122320
    zfs list -t snap
      NAME                                USED  AVAIL     REFER  MOUNTPOINT
      slaanesh-zp00@backup-201904122320     0B      -      184K  -
    zfs get type slaanesh-zp00/GENTOO@backup-201904122320
      NAME                                      PROPERTY  VALUE     SOURCE
      slaanesh-zp00/GENTOO@backup-201904122320  type      snapshot  -

### Describe how to reproduce the problem
As noted above
### Include any warning/errors/backtraces from the system logs
N/A

**Comment by drescherjm** [comment]
I think the bugfix for that is in master.

**Comment by prometheanfire** [comment]
it is, just remerged the client code and get the listing
