### ISSUE TITLE
static dtrace probes unavailable on non-GPL modules

### ISSUE THREAD

**Issue by brad-lewis** [zfsonlinux/zfs#8659]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Ubuntu
Distribution Version	|  18.04
Linux Kernel	|  4.15.0-46-generic
Architecture	|  x86_64
ZFS Version	|  0.8.0-rc3
SPL Version	| 0.8.0-rc3

### Describe the problem you're observing
ZFS tracing efforts are hampered by the inability to access zfs static probes(probes using DTRACE_PROBE macros).  The probes are available via tracepoints for GPL modules  only.  This limitation has been an issue as been brought up in various discussions before like this one: 
https://github.com/zfsonlinux/zfs/pull/2406

The build could be modified to generate a functions for each unique DTRACE_PROBE invocation.  These could be then accessed via kprobes.

**Comment by richardelling** [comment]
DTRACE_PROBE is now capable of being automatically converted to USDT probes for bpf. This could be useful for ztest. Reference: https://www.joyfulbikeshedding.com/blog/2019-01-31-full-system-dynamic-tracing-on-linux-using-ebpf-and-bpftrace.html
