### ISSUE TITLE
offensive strings in dnode.h

### ISSUE THREAD

**Issue by fixyourcodeplease** [zfsonlinux/zfs#8698]
```
/*
 * There should be a ## between the string literal and fmt, to make it
 * clear that we're joining two strings together, but that piece of shit
 * gcc doesn't support that preprocessor token.
 */
```

as a contributor to GCC, this is highly offensive. we should look into some consequences for this, thanks to the new CoC.

**Comment by ahrens** [comment]
I agree, let's adjust the language here.

If you'd like to report a code of conduct violation, please email conduct@open-zfs.org. Here are the reporting guidelines: http://www.open-zfs.org/wiki/Reporting_Guide

**Comment by fixyourcodeplease** [comment]
consider this the report, I do not wish to email my name, address and contact number to anyone.

**Comment by ahrens** [comment]
FYI, you do not need to provide that information, you may report anonymously.  From the Reporting Guide:

> You may report incidents anonymously if you are uncomfortable providing your contact information.

**Comment by fixyourcodeplease** [comment]
okay, how does one send an anonymous email?

**Comment by ahrens** [comment]
I'm not an expert in that, but here are the first 4 google results for "anonymous email":

https://www.pcmag.com/article/331733/how-to-create-an-anonymous-email-account
https://www.hongkiat.com/blog/anonymous-email-providers/
https://thebestvpn.com/anonymous-email/
https://protonmail.com/

**Comment by fixyourcodeplease** [comment]
ok, thank you! the privacy of those seem dubious but I will take their word for it.

I feel empowered to contribute to your project thanks to the CoC. I have been looking through commit messages and source code and I see many changes to make over the next few months. thank you for being understanding.

**Comment by ahrens** [comment]
FYI, the (now removed) comment in question was part of the original ZFS commit to OpenSolaris in 2005.  So we can't determine who wrote it originally.
