### ISSUE TITLE
Errata #4 warning has a very long line due to a missing newline

### ISSUE THREAD

**Issue by siebenmann** [zfsonlinux/zfs#8712]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Fedora
Distribution Version	| 29
Linux Kernel	| 5.0.10-200.fc29.x86_64
Architecture	| x86_64
ZFS Version	| 0.8.0-rc4_35_gde3e0b914
SPL Version	| 0.8.0-rc4_35_gde3e0b914

### Describe the problem you're observing

After commit b3b60984ee191bdbb00b91842053c83581854db7, the warning message about Errata #4 has a very long line due to a missing newline at the end of the first part of the message in ``status_callback()''.

### Describe how to reproduce the problem
````
$ zpool status
  pool: ssddata
 state: ONLINE
status: Errata #4 detected.
Existing encrypted snapshots and bookmarks contain an on-disk incompatibility.
        This may cause on-disk corruption if they are used with 'zfs recv'. action:  To correct the issue, enable the bookmark_v2 feature. No additional
        action is needed if there are no encrypted snapshots or bookmarks. If preserving
        the encrypted snapshots and bookmarks is required, use a non-raw send to backup
        and restore them. Alternately, they may be removed to resolve the
        incompatibility.
   see: http://zfsonlinux.org/msg/ZFS-8000-ER
````

In addition a few other lines in the action: portion of the message are longer than 80 characters when printed out.

**Comment by rlaager** [comment]
@JMoVS Any chance you could whip up a quick PR to fix this?

**Comment by rlaager** [comment]
Based on that output, is the first line also missing a tab?

**Comment by JMoVS** [comment]
Apparently it is. I can whip up a PR and probably have it ready in ~ 16 hours, first have to sleep. May get there sooner. Sry for the trouble, I‘ll check
