### ISSUE TITLE
Kernels with builtin ZFS support lack a way to mount a ZFS dataset as a rootfs without an initramfs

### ISSUE THREAD

**Issue by ryao** [zfsonlinux/zfs#872]
Currently, the only way to do this is with an initramfs. It would be nice to support mounting the rootfs from a ZFS dataset without an initramfs when ZFS is built into the kernel binary.

**Comment by ryao** [comment]
@FransUrbo It is an issue because the module makes upcalls to userspace.

**Comment by bunder2015** [comment]
I am also interested in this feature as well.

**Comment by kernelOfTruth** [comment]
+1

**Comment by jwezel** [comment]
It's 2017 and we absolutely need this.

**Comment by rlaager** [comment]
I'm closing this in favor of #4300, which has more notes.
