### ISSUE TITLE
0.8.0 Does not install on RHEL 8 (depmod change)

### ISSUE THREAD

**Issue by jadams** [zfsonlinux/zfs#8724]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Red Hat Enterprise Linux
Distribution Version	|  8.0.0
Linux Kernel	|  4.18.0-80.el8
Architecture	|  x86_64
ZFS Version	|  0.8.0-rc4
SPL Version	|  0.8.0-rc4

### Describe the problem you're observing
depmod in RHEL8 has moved from `/sbin/depmod` to `/usr/sbin/depmod`

Fixed by changing `/sbin/depmod` to `/usr/sbin/depmod` in `zfs/scripts/kmodtool`

### Describe how to reproduce the problem
Follow [Custom Package](https://github.com/zfsonlinux/zfs/wiki/Custom-Packages) instructions, fails at rpm install `nothing provides /sbin/depmod needed by zfs` 

### Include any warning/errors/backtraces from the system logs

```
Error:
 Problem 1: conflicting requests
  - nothing provides /sbin/depmod needed by kmod-zfs-4.18.0-80.el8.x86_64-0.8.0-rc4.el8.x86_64
 Problem 2: package zfs-0.8.0-rc4.el8.x86_64 requires zfs-kmod = 0.8.0, but none of the providers can be installed
  - conflicting requests
  - nothing provides /sbin/depmod needed by kmod-zfs-4.18.0-80.el8.x86_64-0.8.0-rc4.el8.x86_64
 Problem 3: package zfs-dracut-0.8.0-rc4.el8.x86_64 requires zfs(x86-64) = 0.8.0-rc4.el8, but none of the providers can be installed
  - package zfs-0.8.0-rc4.el8.x86_64 requires zfs-kmod = 0.8.0, but none of the providers can be installed
  - conflicting requests
  - nothing provides /sbin/depmod needed by kmod-zfs-4.18.0-80.el8.x86_64-0.8.0-rc4.el8.x86_64
 Problem 4: package zfs-test-0.8.0-rc4.el8.x86_64 requires zfs(x86-64) = 0.8.0-rc4.el8, but none of the providers can be installed
  - package zfs-0.8.0-rc4.el8.x86_64 requires zfs-kmod = 0.8.0, but none of the providers can be installed
  - conflicting requests
  - nothing provides /sbin/depmod needed by kmod-zfs-4.18.0-80.el8.x86_64-0.8.0-rc4.el8.x86_64
```

**Comment by Conan-Kudo** [comment]
@behlendorf With 0.8.0, we should stop shipping our own kmodtool fork, and use the one provided by either `redhat-rpm-config` (RHEL) or `kmodtool` (Fedora/EPEL).

That should resolve the issues, I think.

**Comment by mskarbek** [comment]
In addition to that in `0.7.13` there is a problem with missing `/usr/bin/python` which is nonexistent in RHEL 8 so `rpmbuild`  complains about Python scripts during build of `spl` packages and fails.
I didn't want to spam with a new issue about that.

**Comment by behlendorf** [comment]
@Conan-Kudo right, shipping our own versions shouldn't be necessary any more.  It'd be great to get a PR open for this.

**Comment by Conan-Kudo** [comment]
@behlendorf in retrospect, we probably need it for deb/ubu builds, but we can resync with the fedora version.

I don't know if I can get to this, but I think we should do this before cutting 0.8.0.

**Comment by behlendorf** [comment]
@Conan-Kudo re-syncing with Fedora version makes good sense.  This shouldn't be too tricky but it's also not going to be a trival drop in replacement.  Our version still contains at least one needed feature which hasn't been accepted upstream (kmod-devel packages).  There may be a few other little tweaks we need too.

While I think we should get this updated soon I don't think it needs to block 0.8.0.  But it would be nice to see it in 0.8.1.

**Comment by Conan-Kudo** [comment]
@behlendorf We shouldn't need the devel packages for 0.8.0 anymore, since SPL and ZFS are in one set of module packages.

**Comment by behlendorf** [comment]
That's true, but the kmod devel package is still required to build Lustre against ZFS.

**Comment by ofaaland** [comment]
Note that this occurs only when when using the "kmod" type build which results in zfs packages which require a specific kernel.

If the "kABI-tracking kmod" type build is used, the issue does not occur as the redhat-provided kmodtool is used.
https://github.com/zfsonlinux/zfs/wiki/Custom-Packages#kabi-tracking-kmod
