### ISSUE TITLE
Root Xattrs and ACLs disappear on large datasets copied with zfs send/receive

### ISSUE THREAD

**Issue by grantma** [zfsonlinux/zfs#8740]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| 
Distribution Version	| 
Linux Kernel	| 
Architecture	| 
ZFS Version	| 
SPL Version	|

**Comment by fling-** [comment]
Duplicate of #8741.
@grantma close this one.

**Comment by behlendorf** [comment]
Closing as duplicate of #8741
