### ISSUE TITLE
Root Xattrs and ACLs disappear on large datasets copied with zfs send/receive

### ISSUE THREAD

**Issue by grantma** [zfsonlinux/zfs#8741]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu
Distribution Version	| Bionic
Linux Kernel	| 4.19.x
Architecture	| amd64
ZFS Version	| 0.7.13
SPL Version	| 0.7.13

### Describe the problem you're observing
The Xattrs and ACLs tend to disappear in the root of any large dataset that we copy with zfs send/receive.  They are written to disk on arrival, but don't show up on the initial read with getfattr or getfacl.  It takes a cd command in the shell, followed by getfattr or getfacl for them to show up.

Looks like the attributes on the inodes that arrive with send/receive are not getting entirely read into memory, and then with atime being set, the empty ACLs in the cahced inodesare getting flushed to disk and overwriting the correct ones.

Dataset is about 3.5 TB in size.

**Comment by grantma** [comment]
Updated kernel (from Ubuntu 4.14.x to 4.19 LTS), and ZFS (from 0.7.5 to 0.7.13) based on changelog saying there was a fix for incorrectly transferred dnodes, which involves xattrs and ACLs.

File system is backing a large Samba data store with xattrs and ACLs enabled for full fidelity with Windows, so getting this fixed would be really nice.  On a lot of setups involoving health or legal data this could be a major privacy issue.

**Comment by fling-** [comment]
@grantma Are not you running getfacl on '.' directory? You need to `cd .` for the '.' directory to start pointing to the directory on the newly mounted filesystem. Alternatively you could avoid using '.' in your commands.

notice how `touch file` fails until you `cd .` :
```
$ mkdir /tmp/test
$ cd /tmp/test
$ rmdir ../test/
$ touch file
touch: cannot touch 'file': No such file or directory
$ cd .
cd: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
$ mkdir ../test
$ touch file
touch: cannot touch 'file': No such file or directory
$ ls
$ cd .
$ touch file
$ ls
file
```

**Comment by grantma** [comment]
Problem also happens with getfacl on /mnt/mntpnt per se.  Been using Linux since 1992, was cded into the mount point before doing getfacl -d .



> @grantma Are not you running getfacl on '.' directory? You need to `cd .` for the '.' directory to start pointing to the directory on the newly mounted filesystem. Alternatively you could avoid using '.' in your commands.
> 
> notice how `touch file` fails until you `cd .` :
> 
> ```
> $ mkdir /tmp/test
> $ cd /tmp/test
> $ rmdir ../test/
> $ touch file
> touch: cannot touch 'file': No such file or directory
> $ cd .
> cd: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
> $ mkdir ../test
> $ touch file
> touch: cannot touch 'file': No such file or directory
> $ ls
> $ cd .
> $ touch file
> $ ls
> file
> ```

**Comment by behlendorf** [comment]
@grantma do I understand correctly that you're only able to reproduce this issue for xattrs stored on the root directory inode?  Or stated differently, this isn't an issue for files or directories stored under the root inode.

**Comment by grantma** [comment]
This issue happens also happens sometimes on subdirs of root inode.  

Looks like standard Unix properties read in when traversing to lower directories, and then inode updated with xattrs and ACLs missing from memory on backup machine.

**Comment by grantma** [comment]
Believe there is a serious bug here.  Hope there has been enough screening questions.  Is there anyone assigned to this issue?  Would love to help you set up some tests so you can track it down.

**Comment by ptx0** [comment]
i'm sure if you provide a reproducer that works on a fresh system, someone will get to it in a few months.

**Comment by grantma** [comment]
Let me just say this, there is a definite problem here that would be a bug on an enterprise implementation.  Why does there appear to be no motivation to try and replicate this issue, as it is fundamental to proper zfs send/receive support of xattr=sa and ACLs?

All it takes is a pile of terrabytes of data, and a find shell script to apply ACLs/xattrs  via setfacl and setfattr....

**Comment by grantma** [comment]
Also, should the receive side of of the send receive not be mounted at all to prevent what obviously looks like some sort of VFS cache corruption via stale cached dir entries?

**Comment by behlendorf** [comment]
@grantma thank you for the reminder.  I agree this is a serious issue which needs to be investigated and resolved.  To track it I've added it to the 0.8-release project.

**Comment by rlaager** [comment]
On the mailing list, these were mentioned as potentially being the same issue:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=236993
https://www.illumos.org/issues/9952

**Comment by rlaager** [comment]
Further on the mailing list, it sounds like this was fixed by: https://github.com/zfsonlinux/zfs/pull/8668

**Comment by behlendorf** [comment]
@rlaager yes, you're exactly right.  Thanks for pointing out this still open issue, closing.
