### ISSUE TITLE
4.14.120 drops export of __kernel_fpu_begin/end

### ISSUE THREAD

**Issue by sempervictus** [zfsonlinux/zfs#8754]
Just a note for anyone else running into this joyful mess - a725c5201f0807a9f843db525f5f98f6c7a4c25b in 4.14.120 is called "x86/fpu: Don't export __kernel_fpu_{begin,end}()" resulting in "simd_x86.h:94:2: error: implicit declaration of function ‘__kernel_fpu_end’; did you mean ‘kernel_fpu_end’? " and such.

**Comment by shastah** [comment]
FWIW: `d4ff57d0320bf441ad5a3084b3adbba4da1d79f8` in 4.19.38

**Comment by ptx0** [comment]
revert the commit for the kernel and build unmodified ZFS source.

alternatively, change the declared license in META file to `GPL\0+CDDL` and then suddenly the problem goes away.

**Comment by sempervictus** [comment]
I just reverted the kernel commit since this is built-in from an in-tree copy. Still idiocy.
