### ISSUE TITLE
Use of Linux Api functions not found in 2.6.32.

### ISSUE THREAD

**Issue by lancethepants** [zfsonlinux/zfs#8760]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Tomato Firmware
Distribution Version	| R7000
Linux Kernel	| 2.6.36.4
Architecture	| Armv7
ZFS Version	| 0.8.0-rc5
SPL Version	| 0.8.0-rc5

### Describe the problem you're observing
Zol seems to use a couple linux api functions not found all the way back to 2.6.32. 

kstrtoul
7522a260773038ff58c213da3e722d1752655237
I replaced kstrtoul with strict_strtoul, but I'm guessing you'll want to check for kstrtoul availability.

ida_simple_get
ida_simple_remove
d45e010dceffc3bf86600787f4d116f891b8bf23
2d82116e80ba88fb8efbc3e573ee8a924323b32a
I simply commented out lines with ida_simple_* to get things to compile. zfs all works except /dev/zvol isn't created for my zvols, I'm sure from my commenting things out.

**Comment by kusumi** [comment]
Looks like RHEL6 backported these, and the reason build CI failed to catch these on old kernel versions including 2.6.32.

**Comment by kusumi** [comment]
Actually, this isn't finished yet, since

```
ida_simple_get
ida_simple_remove
d45e010
2d82116
I simply commented out lines with ida_simple_* to get things to compile. zfs all works except /dev/zvol isn't created for my zvols, I'm sure from my commenting things out.
```

still exists. There seems to be a few ways to address this.

1. Bring in ida_simple_* from upstream under GPL.
2. Bring in ida_simple_* from RHEL6 under GPL.
3. Revert ZoL change which brought in ida_simple_* and just use linked list.

and

1. is technically not easy, as it also brings in other dependencies used by ida_simple_*.
2. is essentially same as 1, but is guaranteed to work on RHEL6 which is a flavor of 2.6.32.
3. unless we have a performance reason not to use a linked list, this is easiest and most safe solution.

**Comment by ptx0** [comment]
well, RHEL6 is EOL in 2020 and it's probably best to move on now.

**Comment by lancethepants** [comment]
ida_simple_* was added in this commit, which released somewhere in early linux-3.x.
https://github.com/torvalds/linux/commit/88eca0207cf1574328c3ce8c3be537a9317261bb#diff-0576f2ea3b780283ee7ce1bc32e9aeeb

It does seem appealing to be able to say zfs works all the way back to 2.6.32.  On the other hand, ida_simple_*  code has been in zfs for a long time.  Too be honest, it's probably more work to fix it in zfs then to do that actual backporting of those functions.

I just attempted a backport applying just the commit listed above, and it seems to kind of work. I don't get a kernel panic when creating multiple zvols, and I kind of get a block device.  When I create with `zvol creat -V 1G backup/block`, I get a /dev/zd0 device that seems to work. If I add more I get
/dev/zd0
/dev/zd16
/dev/zd32
/dev/zd48
/dev/zd64
I'm not sure why that is happening instead of getting /dev/zvol/backup/block.  Is this something that happens with older kernels?

**Comment by ptx0** [comment]
you can try debugging udev since that's generally what is responsible for handling symlink creation.

**Comment by lancethepants** [comment]
Yes, it was a udev thing. Thanks.

Well everything seems to be working for me once I backported the ida_simple_* bits for my kernel. Seems the options are 1,2,3 from above, or 4. `Set new linux kernel minimum version.`  It is very close to being able to claim 2.6.32 compatibility, or otherwise linux 3.something is the next step up.

**Comment by kusumi** [comment]
> or 4. Set new linux kernel minimum version. It is very close to being able to claim 2.6.32 compatibility, or otherwise linux 3.something is the next step up.

`2.6.32` isn't a randomly selected number.
It was LTS, and adopted by some major distros most notably RHEL6.

**Comment by kpande** [comment]
RHEL6 is EOL and 2.6.32 is no longer LTS, the lowest kernel supported by kernel.org should probably be the next: 3.16

**Comment by behlendorf** [comment]
That's right, 2.6.32 was selected since it's what RHEL / CentOS 6 is based on and it will go EOL on November 30, 2020.  After which RHEL /CentOS 7 will be the oldest LTS supported and it is based on a 3.10 kernel.

https://endoflife.software/operating-systems/linux/red-hat-enterprise-linux-rhel

**Comment by lancethepants** [comment]
Well then it sounds as if this issue should be re-opened if you're all really meaning to support 2.6.32 fully until it is EOL.

**Comment by kusumi** [comment]
@behlendorf 
Do you want me to revert ida and just use the original linked list version written by you until 2.6.32 support is dropped ?
From the code, I don't see (performance)reason for this to be hash based.

If not we should probably just say ZoL supports RHEL6, but not vanilla 2.6.32.

**Comment by kusumi** [comment]
Probably not. There's also 58404a73db in addition to the commits op has mentioned. It's way too complex to cleanly revert these commits, just to support ancient kernels that don't compile ZoL.

**Comment by behlendorf** [comment]
Right, I don't think we want to revert these changes since that will reintroduce some other compatibility issues.  We should probably simply be clearer that when we say 2.6.32 we really mean the RHEL 2.6.32 based kernel.
