### ISSUE TITLE
5.2(-rc1) build issues

### ISSUE THREAD

**Issue by nivedita76** [zfsonlinux/zfs#8770]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| gentoo
Distribution Version	| 
Linux Kernel	| 5.2-rc1
Architecture	| amd64
ZFS Version	| git head
SPL Version	| 

### Describe the problem you're observing
In 5.2-rc1 some of the RWSEM defines seem to have been hidden, I guess because no users in the kernel tree (RWSEM_ACTIVE_READ_BIAS and RWSEM_ACTIVE_WRITE_BIAS). spl-rwlock.c no longer compiles, I had to comment out the logic in __rwsem_tryupgrade to get it to build.

**Comment by kusumi** [comment]
Haven't looked into details, but it looks ok to define them in `include/spl/sys/rwlock.h`, e.g.

```
     39 #else
     40 /* Linux 5.2 moved RWSEM_* macros to kernel/locking/rwsem.h. */
     41 #if !defined(RWSEM_ACTIVE_MASK)
     42 #ifdef CONFIG_64BIT
     43 #define RWSEM_ACTIVE_MASK               0xffffffffL
     44 #else
     45 #define RWSEM_ACTIVE_MASK               0x0000ffffL
     46 #endif
     47 #endif
     48 #if !defined(RWSEM_ACTIVE_BIAS)
     49 #define RWSEM_ACTIVE_BIAS               0x00000001L
     50 #endif
     51 #if !defined(RWSEM_WAITING_BIAS)
     52 #define RWSEM_WAITING_BIAS              (-RWSEM_ACTIVE_MASK-1)
     53 #endif
     54 #if !defined(RWSEM_ACTIVE_READ_BIAS)
     55 #define RWSEM_ACTIVE_READ_BIAS          RWSEM_ACTIVE_BIAS
     56 #endif
     57 #if !defined(RWSEM_ACTIVE_WRITE_BIAS)
     58 #define RWSEM_ACTIVE_WRITE_BIAS         (RWSEM_WAITING_BIAS + RWSEM_ACTIVE_BIAS)
     59 #endif
     60 #define SPL_RWSEM_SINGLE_READER_VALUE   (RWSEM_ACTIVE_READ_BIAS)
     61 #define SPL_RWSEM_SINGLE_WRITER_VALUE   (RWSEM_ACTIVE_WRITE_BIAS)
     62 #endif
```

**Comment by kusumi** [comment]
Btw, this should be addressed once https://github.com/zfsonlinux/zfs/pull/8730 is merged. It's been there for a few weeks in pr queue.

**Comment by nivedita76** [comment]
Ok thanks

**Comment by behlendorf** [comment]
I'll get the build issue PRs merged soon.
