### ISSUE TITLE
mailing list posts being moderated

### ISSUE THREAD

**Issue by ptx0** [zfsonlinux/zfs#8780]
hi, i've been posting advice to threads on the mailing list for some time now and just noticed they are not making it through to the list.

of course, i was told I wasn't "kicked out" of the community, and we all were told that the new "rules" would be applied transparently, the person involved would receive notice, an ability to appeal, none of which seem to apply here.

please unblock my posts to the mailing list, and explain yourself.

**Comment by ahrens** [comment]
Kash,

The mailing list holds messages for moderation if they are sent from email addresses that are not subscribed to the list.  I see a message currently held for moderation from kash@tripleback.net, which is not subscribed.  kashpande@gmail.com is subscribed.  I'll approve the held message now.

Feel free to also contact Brian and/or I offline if you run into technical difficulties in the future.

**Comment by ptx0** [comment]
```
from mail.tripleback.net by mail.tripleback.net with LMTP id SNmLDetc41zhSAAAnZk5uA (envelope-from <bounce.mM939aaec0b9e3f4df617648b0.r54bca796-6b73-11e9-b2fe-4eca242d11b0@zfsonlinux.bounce.topicbox.com>) for <kash@tripleback.net>; Mon, 20 May 2019 22:05:31 -0400
```

interestingly, i am and have been subscribed, so that makes no sense either.

**Comment by ahrens** [comment]
Not sure why kash@tripleback.net is not subscribed.  I don't see a log of when folks subscribe/unsubscribe.  FYI, fuckstains@tripleback.net is subscribed.
