### ISSUE TITLE
0.7 and 0.8 changelog lack SIMD details

### ISSUE THREAD

**Issue by ptx0** [zfsonlinux/zfs#8805]
well, the previous issue (#8804) was closed because it didn't mention 0.7 as well, which also lacks SIMD and neither changelog mention this known regression.

**Comment by tonyhutter** [comment]
@ptx0 it's listed in the zfs-0.7.13 changelog (https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.7.13)
Linux 5.0 compat: Disable vector instructions on 5.0+ kernels #8259

**Comment by ptx0** [comment]
ok, so then it is missing from 0.8 changelog after all.
