### ISSUE TITLE
0.8.0 compiling error - No rule to make target 'import_cachefile_device_replaced.ksh',

### ISSUE THREAD

**Issue by dguskovv** [zfsonlinux/zfs#8806]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Debian
Distribution Version	| 9.9
Linux Kernel	| 4.19.0-0.bpo.4-amd64
Architecture	| amd64
ZFS Version	| 0.8.0
SPL Version	| 

### Describe the problem you're observing

Cannot compile 0.8.0 release

### Describe how to reproduce the problem

Just run ./configure $$ make

I see error

make[8]: *** No rule to make target 'import_cachefile_device_replaced.ksh', needed by 'all-am'.  Stop.

As I can see, the archive https://github.com/zfsonlinux/zfs/releases/download/zfs-0.8.0/zfs-0.8.0.tar.gz have truncated file names:

import_cachefile_device_replaced.ks
import_cachefile_mirror_attached.ks
import_cachefile_mirror_detached.ks

in the directory zfs-0.8.0/tests/zfs-tests/tests/functional/cli_root/zpool_import

**Comment by behlendorf** [comment]
I wasn't able to reproduce this issue.  When extracting the related tarball the file names were not truncated.  What version of `tar` are you using?  I tested with `tar (GNU tar) 1.26`.

```
$ find . | grep import_cachefile
./tests/zfs-tests/tests/functional/cli_root/zpool_import/import_cachefile_shared_device.ksh
./tests/zfs-tests/tests/functional/cli_root/zpool_import/import_cachefile_device_replaced.ksh
./tests/zfs-tests/tests/functional/cli_root/zpool_import/import_cachefile_device_added.ksh
./tests/zfs-tests/tests/functional/cli_root/zpool_import/import_cachefile_mirror_detached.ksh
./tests/zfs-tests/tests/functional/cli_root/zpool_import/import_cachefile_mirror_attached.ksh
./tests/zfs-tests/tests/functional/cli_root/zpool_import/import_cachefile_device_removed.ksh
```

**Comment by dguskovv** [comment]
Sorry. The problem is on my side.
