### ISSUE TITLE
zfs-mount not working after upgrading to 0.8.0 (fedora 30)

### ISSUE THREAD

**Issue by hareve** [zfsonlinux/zfs#8808]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Fedora
Distribution Version	| 30
Linux Kernel	| 5.0.17-300.fc30.x86_64
Architecture	| x86_64
ZFS Version	| 0.8.0-1
SPL Version	| 0.8.0-1

### Describe the problem you're observing
ZFS not mounting after reboot (but zpool import <pool> works).

### Describe how to reproduce the problem
Reboot the system.

### Include any warning/errors/backtraces from the system logs
...
root@server ~]# systemctl status zfs-mount
● zfs-mount.service - Mount ZFS filesystems
   Loaded: loaded (/usr/lib/systemd/system/zfs-mount.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2019-05-24 09:59:27 CEST; 27min ago
     Docs: man:zfs(8)
  Process: 8175 ExecStart=/sbin/zfs mount -a (code=exited, status=127)
 Main PID: 8175 (code=exited, status=127)

May 24 09:59:27 server.evensen.lan systemd[1]: Starting Mount ZFS filesystems...
May 24 09:59:27 server.evensen.lan zfs[8175]: /sbin/zfs: symbol lookup error: /sbin/zfs: undefined symbol: zfs_crypto_rewrap
May 24 09:59:27 server.evensen.lan systemd[1]: zfs-mount.service: Main process exited, code=exited, status=127/n/a
May 24 09:59:27 server.evensen.lan systemd[1]: zfs-mount.service: Failed with result 'exit-code'.
May 24 09:59:27 server.evensen.lan systemd[1]: Failed to start Mount ZFS filesystems.
...

**Comment by allanjude** [comment]
Try reinstalling the zfs package. It seems as if somehow your zfs binary and libraries are not in sync.
