### ISSUE TITLE
./configure shebanged to /bin/sh when not posix compatible

### ISSUE THREAD

**Issue by bepvte** [zfsonlinux/zfs#8809]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Arch Linux
Distribution Version	|  Rolling
Linux Kernel	|  5.1.4
Architecture	|  x86_64
ZFS Version	|  0.8.0
SPL Version	|  N/A

### Describe the problem you're observing
I cannot run ./configure when /bin/sh is linked to the dash shell
### Describe how to reproduce the problem
dash (or other posix only shell) zfs-0.8.0/configure
### Include any warning/errors/backtraces from the system logs
./configure: 16358: ./configure: Bad substitution

Either the script should not be shebanged to /bin/sh, or the subsitition should be changed

**Comment by rlaager** [comment]
Can you try the fix in PR #8813, please?

**Comment by redg3ar** [comment]
It doesnt seem to fix it, these two lines might be the problem: https://github.com/zfsonlinux/zfs/blob/43977948aa156be2771f3df2b9a71f741d49515a/config/always-python.m4#L71-L72

**Comment by rlaager** [comment]
Thanks. I made that fix really quickly and obviously hadn't looked closely enough. I pushed another version of that PR which changes those lines too. Does that work? (You also need to run `autogen.sh` to rebuild `configure`.)

**Comment by redg3ar** [comment]
It looks like the pyzfs macro has a similar problem  too.

**Comment by rlaager** [comment]
I pushed a new version again to fix that too.

**Comment by redg3ar** [comment]
It worked!!!

**Comment by redg3ar** [comment]
It worked!!!

**Comment by rlaager** [comment]
When I created #8813, I didn't realize that #8731 existed. Any chance you could test #8731? That solution seems more comprehensive. If that works, I'll close #8813.

**Comment by redg3ar** [comment]
It looks like that works fairly well.
