### ISSUE TITLE
copy-builtin kernel location suggestion

### ISSUE THREAD

**Issue by foobarz** [zfsonlinux/zfs#881]
I have tested builtin, and I found that spl is placed in the main "core" linux source directory linux/spl, and zfs is placed under "fs" linux/fs/zfs. While this may seem like good locations, in practice I think they might not be.

The problem is builtin modules initialization order. This order is the same order the modules are linked into the kernel.  With the current copy-builtin placement, SPL and ZFS are init early in the boot process even before SCSI and IDE controllers, so I think that they are not able to see any devices when they init, for example using a /etc/zfs/zpool.cache stored in rootfs (initramfs-source).

The location of spl in "core" might not be a problem, but maybe it is too because maybe it internally inits zfs along with it. I'm not sure on that, but I notice that ZFS always follows right after SPL init as if SPL is init ZFS.

Anyhow, I have tested placing the modules at linux/drivers/zfsonlinux:
make menuconfig
   Device Drivers ->
    <*> ZFSonLinux support ->
      <*> Solaris Porting Layer (SPL)
      <*>     ZFS

With ZFSonLinux placed as a driver, and the _last_ driver in the Makefile(s), then all SCSI and IDE devices are init before ZFS and it can automatically import a pool on hard drives using a reable /etc/zfs/zpool.cache in rootfs.

Maybe consider changing copy-builtin to make this placement inside the kernel, after all other drivers have init. The way ZFS has mostly been tested is as a loadable module and it has always been loaded after all builtin and after all loadable hard drive controllers etc, so if it is builtin, it should be placed in the builtin link/init order  as last initialized driver.

ZFSonLinux is more like a software raid device driver, an alignment in the kernel more like MD raid (which is in drivers too, I believe), so maybe bettter. To give the ZFS cache import the best chance to see all available devices, place it as last linked driver.

Okay, to see more about my test setup, where I booted a system root on zfs pool/filesystem using only a kernel image with embedded initramfs/rootfs containing a minimal c init script to mount a zfs pool as / and exec it's /sbin/init, then see:
http://slackwiki.com/ZFS_root_%28builtin%29

Now, I had to make my own small c program for rootfs/init because I could not find a way to use kernel command line parameters (yet) to get the pool to mount automaically... I may try again by placing only a blank /etc/mtab and a good /etc/zfs/zpool.cache and try booting with kernel parameters:

spl.spl_hostid=0x007f0100 zfs.spa_config_path=/etc/zfs/zpool.cache root=zfs-root ro rootfstype=zfs rootwait devtmpfs.mount=1

But, I don't think that parameter devtmpfs.mount=1 will work if a /init is found in initramfs. I also think that devtmpfs must be mounted for zfs to mount a pool... so, what I am wanting is maybe a new kernel parameter that tells the ZFS module to do some things like:

zfs.bootfs-zpoolcache="mybootpoolordataset"

and, what this parameter would do is it would expect you to place a /etc/zfs/zpool.cache into your initramfs-source that is in your initial rootfs, and then it would do a procedure like this inside the tmpfs rootfs:
  mount devtmpfs /dev
  mkdir /mnt
  mount "mybootpoolordataset" /mnt
  mount --move /dev /mnt/dev
  cd /mnt
  mount --move . /
  chroot .
  cd /
  exec /sbin/init $@

Another issue is to maybe place a /etc/hostid file inside initramfs for SPL, but this has been tricky and I have not been able to get SPL to like a /etc/hostid file, and have had to using only hostname/IP based hostid and/or give the spl.spl_hostid parameter.

Okay, another proposed parameter for ZFS:

zfs.bootfs-import="mypooldataset"

This would depend on a good hostid being given to SPL or in /etc/hostid for it. Then ZFS would import a pool with it's internal zfs import code and do this stuff inside rootfs:

  mount devtmpfs /dev
  mkdir /mnt
  <internally zfs import mypooldataset  using hostid check OR NOT with may another parameter to override>
  mount "mybootpooldataset" /mnt
  mount --move /dev /mnt/dev
  cd /mnt
  mount --move . /
  chroot .
  cd /
  exec /sbin/init $@

So, the SPL and ZFS modules, when builtin should have the ability to work with the kernel's internal rootfs and the initramfs-source option of the kernel configuration, so with proper files placed into rootfs, and proper spl.* and/or zfs.* kernel parameters, it uses zpool.cache, or does an import with hostid checking and uses the rootfs to mount devtmpfs and do a switch root procedure to boot onto a root system installed on a ZFS dataset|pool.

Again, see this:
http://slackwiki.com/ZFS_root_%28builtin%29
for ideas how this stuff works. I hope a developer will gets good ideas on this, I'm not sure what I can develop on these ideas yet.

**Comment by behlendorf** [comment]
Closing as stale.
