### ISSUE TITLE
Grub Unknown File System

### ISSUE THREAD

**Issue by ellisonpatterson** [zfsonlinux/zfs#8810]
### System information
Distribution Name	| Gentoo
Distribution Version	| RR
Linux Kernel	| 5.1.4
Architecture	| amd64
ZFS Version	| 0.8.0-r0-gentoo
SPL Version	| 0.8.0-r0-gentoo

### Describe the problem you're observing
So if I create a volume and enable encryption, regardless of where I nest it in, it causes grub to think it doesn't know the filesystem and if I try to reboot with that encrypted volume still available (not destroyed) it won't boot and goes to grub-rescue, complaining that it doesn't know the file system type. Once I delete it, it's fixed.

### Describe how to reproduce the problem
```
op2 ~ # zfs create -o encryption=aes-256-gcm -o keyformat=passphrase -o keylocation=prompt -o mountpoint=/opt/test rpool/ROOT/test
Enter passphrase:
Re-enter passphrase:
op2 ~ # grub-probe /
grub-probe: error: unknown filesystem.
op2 ~ # zfs destroy rpool/ROOT/test
op2 ~ # grub-probe /
zfs
op2 ~ # echo "wut"
```

**Comment by gmelikov** [comment]
Grub doesn't support many of new 0.7 and 0.8 features, you can find useful information for ex. here http://git.savannah.gnu.org/cgit/grub.git/tree/grub-core/fs/zfs/zfs.c#n276 . If you want to use native ZFS encryption - please use other boot method, for ex. UEFI kernel boot.

**Comment by misterhsp** [comment]
Is there any hope that Grub can do that in the near future? efi-stub doesn't work on my Acer notebook. Entry created with efibootmgr but I don't see anything in the boot menu.

thanks...

**Comment by gmelikov** [comment]
@misterhsp unfortunately no. If you have problems with other boot methods - just use additional boot pool with minimal features flags activated.
