### ISSUE TITLE
Errata #4 detected.

### ISSUE THREAD

**Issue by MLWALK3R** [zfsonlinux/zfs#8814]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| ubuntu
Distribution Version	| 18.04
Linux Kernel	| 5.1.4
Architecture	| 64bit
ZFS Version	| 8.0 I think, modinfo doesnt work
SPL Version	| 8.0 I think, modinfo doesnt work

### Describe the problem you're observing
status: Errata #4 detected.
Cannot get rid of this error because I cannot enable bookmark_v2

cannot set property for 'zpool': invalid feature 'bookmark_v2'

### Describe how to reproduce the problem
IDK

**Comment by behlendorf** [comment]
I'd suggest first double checking that your kernel modules and user space utilities are up to date.  If you're running 0.8.0 you can run `zpool version` to get the version information.  Assuming everything is up to date, you should then be able to run `zpool set feature@bookmark_v2=enabled tank` to enable the feature.

**Comment by MLWALK3R** [comment]
> 
> 
> I'd suggest first double checking that your kernel modules and user space utilities are up to date. If you're running 0.8.0 you can run `zpool version` to get the version information. Assuming everything is up to date, you should then be able to run `zpool set feature@bookmark_v2=enabled tank` to enable the feature.


```
 zpool version not a command for me
 
 root@prime:~# zpool set feature@bookmark_v2=enabled zpool
 cannot set property for 'zpool': invalid feature 'bookmark_v2'
 root@prime:~#
 
 root@prime:~# zpool get version zpool
 NAME   PROPERTY  VALUE    SOURCE
 zpool  version   -        default
```




`

**Comment by behlendorf** [comment]
Then it sounds like your user space utilities haven't been updated the 0.8.0 for some reason and you should reinstall.

**Comment by MLWALK3R** [comment]
> 
> 
> Then it sounds like your user space utilities haven't been updated the 0.8.0 for some reason and you should reinstall.

Are you talking about zfsutils-linux? 

and reinstall as the server or the utilities; if utilities  how would I go about that ( Sorry for the dumb questions) ?

**Comment by behlendorf** [comment]
I'm a bit confused myself.  My understanding is Ubuntu 18.04 only provides packages for the zfs 0.7,x release which does not support encryption, nor the `bookmark_v2`.  So this isn't an error you should be seeing.  Did you somehow install a newer version of ZFS from an alternate source?

**Comment by MLWALK3R** [comment]
Compiled lastest kernel with lasted zfs build. I never had issues in the past up until 8.0

Used this guide

https://forum.level1techs.com/t/building-custom-kernel-with-zfs-built-in-updated-0-8-or-higher/142000

**Comment by behlendorf** [comment]
Well, it sounds as if you user space utilities haven't been updated.  Try running through the 'Configure, Build, and Install ZFS' steps again from the guide.  Perhaps you accidentally didn't run `make install`?  You could also try running the utilities directly form the source tree being installing them, (i.e. ./cmd/zpool/zpool version).

**Comment by MLWALK3R** [comment]
Tried to get it to install but it isn't working, it would use the old version that was installed I have now removed it totally and still can't get it to install via make. 

I've used ./zpool in the cmd folder to get boommark enabled. 

Do you have spersifc inscrtions for installing the utilities?

**Comment by MLWALK3R** [comment]
I've reinstalled ubuntu, too many issues going on; build ZFS from the 8.0 build rebooted and everythink is working as it should. Thank you for the support
