### ISSUE TITLE
0.8.0 does not mount datasets on boot (missing systemd zfs-mount.service)

### ISSUE THREAD

**Issue by grandiego** [zfsonlinux/zfs#8823]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu
Distribution Version	| 19.04
Linux Kernel	| 5.0.0-16-generic
Architecture	| x86-64
ZFS Version	| 0.8.0-22_g841a7a98f
SPL Version	| 0.8.0-22_g841a7a98f

### Describe the problem you're observing
I was running 0.7.12 from Ubuntu repos just fine. I've downloaded 0.8.0 from git and built .deb packages using make debs. I uninstalled 0.7.12 packages (had to because some of new ones have different names than previous, so dpkg tried to keep both at the same time), installed the new ones, update-initramfs, update-grub and reboot. zfsutils-linux is not being built anymore.

I'm running zfs on root filesystem. It's working fine just for the fact that every other dataset is not being mounted on boot.
I have to manually run zfs mount rpool/home and zfs mount rpool/home/2994622 every boot, as /etc/systemd/system/zfs-mount.service (which was provided by zfsutils-linux-0.7.12) now is missing.

```
# zfs list -t filesystem,volume
NAME                         USED  AVAIL     REFER  MOUNTPOINT
rpool                        145G   144G       96K  /rpool
rpool/ROOT                  20,4G   144G       96K  none
rpool/ROOT/2994622-2-94571  20,4G   144G     7,28G  /
rpool/home                   120G   144G      144K  /home
rpool/home/2994622           120G   144G      105G  /home/2994622
rpool/swap                  4,25G   145G     3,61G  -

# zfs get mounted,mountpoint,canmount -t filesystem,volume
NAME                        PROPERTY    VALUE          SOURCE
rpool                       mounted     no             -
rpool                       mountpoint  /rpool         default
rpool                       canmount    off            local
rpool/ROOT                  mounted     no             -
rpool/ROOT                  mountpoint  none           local
rpool/ROOT                  canmount    off            local
rpool/ROOT/2994622-2-94571  mounted     yes            -
rpool/ROOT/2994622-2-94571  mountpoint  /              local
rpool/ROOT/2994622-2-94571  canmount    noauto         local
rpool/home                  mounted     yes            -
rpool/home                  mountpoint  /home          local
rpool/home                  canmount    on             default
rpool/home/2994622          mounted     yes            -
rpool/home/2994622          mountpoint  /home/2994622  inherited from rpool/home
rpool/home/2994622          canmount    on             default
rpool/swap                  mounted     -              -
rpool/swap                  mountpoint  -              -
rpool/swap                  canmount    -              -


```

### Describe how to reproduce the problem

Git clone 0.8.0.
Make debs
Remove 0.7.12 zfs related packages from Ubuntu repos.
Install the 0.8.0 packages you've just build. (zfsutils-linux is missing)
update-initramfs and update-grub (just in case)
reboot

System boots fine, but rpool/home and rpool/home/2994622 are not mounted. I have to switch to tty1, log in and zfs mount both of them.

**Comment by behlendorf** [comment]
The Ubuntu provided packages for ZFS differ somewhat from packaging provided from the git repository so you may encounter some minor integration issues.  That said, all of the required systemd configuration files should be compatible between versions.  However, you many need to manually copy them in to place until the Ubuntu packages are updated to provide 0.8.

**Comment by ideologysec** [comment]
Is there a plan to have 0.8 in the LTS repos at any point, or will they forever be on the 0.7x branch until 20.04 ?
