### ISSUE TITLE
invalid or corrupt cache file contents with zfs 0.8

### ISSUE THREAD

**Issue by mabod** [zfsonlinux/zfs#8831]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Manjaro
Distribution Version	|  Testing
Linux Kernel	|  4.19.46
Architecture	|  x86
ZFS Version	|  0.8
SPL Version	|  0.8

### Describe the problem you're observing
Todays update on Manjaro Testing brings zfs 0.8 (was 0.7.13 before)
zfs now fails to import my pool during boot because zfs-import-cache.service can not handle the cache file. The underlying import command give the following error:

```
2# zpool import -c /etc/zfs/zpool.cache -aN
invalid or corrupt cache file contents: invalid or missing cache file
```
Manual import via "`zpool import zstore`" is working.

If I move the existing cache file out of the way, the manual import creates a new cache file but it is showing the same error during boot: cache file corrupt or invalid.

I have  to say that I did not do a feature upgrade yet to the pool if that matters:
```
7# zpool status                               
pool: zstore
state: ONLINE
status: Some supported features are not enabled on the pool. The pool can
	still be used, but some features are unavailable.
action: Enable all features using 'zpool upgrade'. Once this is done,
	the pool may no longer be accessible by software that does not support
	the features. See zpool-features(5) for details.
```

**Comment by mabod** [comment]
Update:
zfs import during boot still fails:


```
3# systemctl status zfs-import-cache.service
● zfs-import-cache.service - Import ZFS pools by cache file
   Loaded: loaded (/usr/lib/systemd/system/zfs-import-cache.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2019-05-29 16:36:30 CEST; 1min 12s ago
     Docs: man:zpool(8)
 Main PID: 324 (code=exited, status=1/FAILURE)

Mai 29 16:36:30 rakete zpool[324]: cannot import 'zstore': no such pool or dataset
Mai 29 16:36:30 rakete zpool[324]:         Destroy and re-create the pool from
Mai 29 16:36:30 rakete zpool[324]:         a backup source

```
But the manual import via cachefile works:

```
4# /usr/bin/zpool import -c /etc/zfs/zpool.cache -aN
5# zpool status
  pool: zstore
 state: ONLINE
status: Some supported features are not enabled on the pool. The pool can
	still be used, but some features are unavailable.
action: Enable all features using 'zpool upgrade'. Once this is done,
	the pool may no longer be accessible by software that does not support
	the features. See zpool-features(5) for details.
  scan: scrub repaired 0B in 0 days 16:57:34 with 0 errors on Mon Apr  1 23:52:01 2019
config:

	NAME                     STATE     READ WRITE CKSUM
	zstore                   ONLINE       0     0     0
	  mirror-0               ONLINE       0     0     0
	    sdb-WD-WCC4E5HF3P4S  ONLINE       0     0     0
	    sdc-WD-WCC4E1SSP28F  ONLINE       0     0     0
	  mirror-1               ONLINE       0     0     0
	    sdd-WD-WCC4E1SSP6NC  ONLINE       0     0     0
	    sda-WD-WCC7K7EK9VC4  ONLINE       0     0     0

errors: No known data errors
```

And this import command is the same that zfs-import-cache.service is using:

```
6# systemctl cat zfs-import-cache.service
# /usr/lib/systemd/system/zfs-import-cache.service
[Unit]
Description=Import ZFS pools by cache file
Documentation=man:zpool(8)
DefaultDependencies=no
Requires=systemd-udev-settle.service
After=systemd-udev-settle.service
After=cryptsetup.target
After=systemd-remount-fs.service
Before=zfs-import.target
ConditionPathExists=/etc/zfs/zpool.cache

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/bin/zpool import -c /etc/zfs/zpool.cache -aN

[Install]
WantedBy=zfs-import.target
```
So why is that not working at boot? I did create a new initramfs. And the kernel update did this anyways.

**Comment by mabod** [comment]
Update:
I edited zfs-import-cache.service to import the pool directly without cache file:
```
...
[Service]
Type=oneshot
RemainAfterExit=yes
#ExecStart=/usr/bin/zpool import -c /etc/zfs/zpool.cache -aN
ExecStart=/usr/bin/zpool import zstore
...
```
That works fine. This is so weird.

**Comment by mabod** [comment]
Update:

It seems to be a timing issue with the services. When I add a 5 sec delay to zfs-import-cache.service` it works fine:

```
[Service]
Type=oneshot
RemainAfterExit=yes
ExecStartPre=/bin/sleep 5
ExecStart=/usr/bin/zpool import -c /etc/zfs/zpool.cache -aN
```

ZFS 0.7 did not have that issue. How can I debug this any further?

**Comment by mabod** [comment]
Solved:
I had to remove and readd the cachefile option to the filesystem:

```
zpool set cachefile=none zstore
zpool set cachefile=/etc/zfs/zpool.cache zstore
```

Now zfs-import-cache.service works out of the box.

**Comment by dimitarvp** [comment]
@mabod FYI your last comment worked for me for a bit of time but then after a few small kernel upgrades (I am on Manjaro so it's usually a fairly recent kernel, and ZFS version is always current) it stopped working. I reissued the command and rebooted, and did both several times in a row, still no joy. I have a cache device in my ZFS pool (not sure if `cachefile` is at all related though).

Currently on kernel 6.2.16-1 and ZFS 2.1.11.

**Comment by dimitarvp** [comment]
What _did_ work however was this:

```sh
sudo truncate -s 0 /etc/zfs/zpool.cache
```

Because I was getting a complaint inside the boot log invoked via `journalctl -b` that the file is not empty and hence ZFS import is failing. I don't claim to have a clue why a non-empty file is even needed for ZFS import to work but I just went for the seemingly obvious and lo and behold, it worked. Hopefully that solution lasts.
