### ISSUE TITLE
pool not imported after update

### ISSUE THREAD

**Issue by Redsandro** [zfsonlinux/zfs#8838]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Linux Mint 19 Cinnamon
Distribution Version	| Cinnamon 3.8.9
Linux Kernel	| 4.15.0-50-generic
Architecture	| x64
ZFS Version	| 0.8.0-1
SPL Version	| 0.8.0-1

### Describe the problem you're observing

I have upgraded from 0.8.0-rc2 (I believe) to 0.8.0 final. Now my pool is not imported on startup anymore. When I import it manually and I reboot, the pool is gone again.

### Describe how to reproduce the problem

```bash
apt install build-essential autoconf libtool gawk alien fakeroot zlib1g-dev uuid-dev libattr1-dev libblkid-dev libselinux-dev libudev-dev parted lsscsi ksh libssl-dev libelf-dev linux-headers-$(uname -r)
apt install python3-distutils python3-dev python3-setuptools python3-cffi
wget https://github.com/zfsonlinux/zfs/releases/download/zfs-0.8.0/zfs-0.8.0.tar.gz
tar -xzf zfs-0.8.0.tar.gz
cd zfs-0.8.0
./configure && \
    make -s -j$(nproc) && \
    make deb-utils deb-dkms && \
    spd-say "Packages are ready."
for DEB in *.deb; do gdebi --non-interactive $DEB; done
```

I'm sure I missed something really simple.

**Comment by mabod** [comment]
How are you importing during boot? With zfs-import-cache.service?

**Comment by Redsandro** [comment]
@mabod your question made me try all the services again and now it works!

```bash
systemctl enable zfs-import-cache
systemctl enable zfs-import-scan
systemctl enable zfs-import.target
systemctl enable zfs-mount
systemctl enable zfs-share
systemctl enable zfs-zed
systemctl enable zfs.target
```

My issue is now resolved. I do wonder though; shouldn't the packages (re-)enable these services automatically for the user? Is not doing that an active choice?

**Comment by behlendorf** [comment]
> shouldn't the packages (re-)enable these services automatically for the user?

Yes they should.  My guess is that this might be an issue resulting from not having native packaging for Debian / Ubuntu.
