### ISSUE TITLE
Zpool destroy on ZoL 0.8

### ISSUE THREAD

**Issue by itman20** [zfsonlinux/zfs#8849]
### System information

Type | Version/Name
 --- 0.8| --- 
Distribution Name	Centos| 
Distribution Version	7| 
Linux Kernel	4.x| 
Architecture	x64| 
ZFS Version	0.8| 
SPL Version	0.8| 

### Describe the problem you're observing
Hi All,
I install zfs-0.8.0, when i have many dataset and volume , also they have many snapshot and they are working,
if i use : 
zpool destroy pool1,

it destroy pool without prompt for that pool has children and dataset has snapshots,
and it destroy whole pool immediately, 

do it is right ?

Thanks,

**Comment by Low-power** [comment]
I think this is working as expected.

**Comment by gmelikov** [comment]
Yes, as expected. If it was real pool - you can import deleted pool via `zpool import -D` flag, if you didn't change disks data after destroy.

**Comment by ahrens** [comment]
FYI, you will get a warning if you do `zfs destroy ...` and the argument has snapshots or children.  This is different from `zpool destroy`.
