### ISSUE TITLE
should "an zio" be "a zio"?

### ISSUE THREAD

**Issue by bnjf** [zfsonlinux/zfs#8875]
I was reading through the file and this caught my eye.  Unless the z is silent, "a zio" reads less jarringly.

https://github.com/zfsonlinux/zfs/blob/893a6d62c1895f3e3eeb660b048236571995a564/module/zfs/vdev_raidz_math.c#L475

**Comment by behlendorf** [comment]
@bnjf yes, it should be "a zio".  If you have a moment to open a PR it would be welcome, otherwise if you prefer I can open one with change.
