### ISSUE TITLE
`zfs promote` of encrypted clone outside its encryption root gives bad error message

### ISSUE THREAD

**Issue by DeHackEd** [zfsonlinux/zfs#8905]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| CentOS
Distribution Version	| 7.x
Linux Kernel	| 3.10.0-957.12.2.el7.x86_64
Architecture	| x86_64
ZFS Version	| 0.8.0-17_g2409be0 (c3e5907f + #8766 cherry-picked)
SPL Version	| (included)

### Describe the problem you're observing
```
# zfs create -o keyformat=passphrase -o encryption=on tank/encroottest
Enter passphrase: 
Re-enter passphrase: 
# zfs create tank/encroottest/testchild
# zfs snapshot tank/encroottest/testchild@snap1
# zfs clone tank/encroottest/testchild@snap1 tank/testclone
# zfs promote tank/testclone
cannot promote 'tank/testclone': dataset does not exist
```
Wait, what?

But if I move it to be a child of its encrypted root:
```
# zfs rename tank/testclone tank/encroottest/testchild2
# zfs promote tank/encroottest/testchild2
```
Success

I could not find anything obvious in the man page saying this wasn't allowed or that encrypted datasets need to be children of their encryption root or strictly clones of such a thing.

### Describe how to reproduce the problem
See above

### Include any warning/errors/backtraces from the system logs
Nothing applicable

**Comment by kpande** [comment]
that even seems like a simple test case for the suite, and one wonders why it's not there already :+1:

**Comment by tcaputi** [comment]
The test case is in there, but it does not check the error message. This should be an easy fix.
