### ISSUE TITLE
zfs-dracut regression

### ISSUE THREAD

**Issue by gordan-bobic** [zfsonlinux/zfs#8913]
### System information
Type | Version/Name
 --- | --- 
Distribution Name	| CentOS
Distribution Version	| 7.x continuous release
Linux Kernel	| 4,9.181
Architecture	| aarch64 but almost certainly affects x86-64 as well.
ZFS Version	| 0.8.1
SPL Version	| 0.8.1

### Describe the problem you're observing
zfs-dracut in 0.8.1 doesn't result in the rootfs being mounted, either via bootfs option or via any root= kernel boot options.

### Describe how to reproduce the problem
Mininal rootfs on ZFS
Build initramfs using dracut (add zfs module via dracut.conf)
Boot will drop to a dracut shell after failing to mount the rootfs.
Replace zfs-dracut-0.8.1 with zfs-dracut-0.7.13, rebuild initramfs, and everything will boot fine.

**Comment by kpande** [comment]
probably systemd specific because openrc is unaffected, at least on x86-64.

**Comment by kpande** [comment]
use `rd.debug` and gather logs please

**Comment by gordan-bobic** [comment]
Here is the relevant part of the output:

```
[   15.289254] dracut-mount[2146]: ///lib/dracut-zfs-lib.sh@27(): ZPOOL_IMPORT_OPTS=
[   15.289630] dracut-mount[2146]: ///lib/dracut-zfs-lib.sh@28(): getargbool 0 zfs_force -y zfs.force -y zfsforce
[   15.290017] dracut-mount[2146]: ///lib/dracut-zfs-lib.sh@238(getargbool): local _b
[   15.290394] dracut-mount[2146]: ///lib/dracut-zfs-lib.sh@239(getargbool): unset _b
[   15.290765] dracut-mount[2146]: ///lib/dracut-zfs-lib.sh@240(getargbool): local _default
[   15.291182] dracut-mount[2146]: ///lib/dracut-zfs-lib.sh@241(getargbool): _default=0
[   15.291562] dracut-mount[2146]: ///lib/dracut-zfs-lib.sh@241(getargbool): shift
[   15.291959] dracut-pre-mount[834]: ///lib/dracut/hooks/pre-mount/90-zfs-load-key.sh@21(source): zpool list -H
[   15.292155] dracut-mount[2146]: ////lib/dracut-zfs-lib.sh@242(getargbool): getarg zfs_force -y zfs.force -y zfsforce
[   15.292536] dracut-mount[2146]: ////lib/dracut-lib.sh@187(getarg): debug_off
[   15.292917] dracut-mount[2146]: ////lib/dracut-lib.sh@20(debug_off): set +x
[   15.293318] dracut-mount[2146]: ////lib/dracut-lib.sh@227(getarg): return 1
[   15.293710] dracut-pre-mount[834]: ///lib/dracut/hooks/pre-mount/90-zfs-load-key.sh@21(source): grep -q -v '^$'
[   15.293915] dracut-mount[2146]: ///lib/dracut-zfs-lib.sh@242(getargbool): _b=
[   15.294313] dracut-mount[2146]: ///lib/dracut-zfs-lib.sh@243(getargbool): '[' 1 -ne 0 -a -z '' ']'
[   15.294691] dracut-mount[2146]: ///lib/dracut-zfs-lib.sh@243(getargbool): _b=0
[   15.295084] dracut-mount[2146]: ///lib/dracut-zfs-lib.sh@244(getargbool): '[' -n 0 ']'
[   15.295467] dracut-mount[2146]: ///lib/dracut-zfs-lib.sh@245(getargbool): '[' 0 = 0 ']'
[   15.295846] dracut-mount[2146]: ///lib/dracut-zfs-lib.sh@245(getargbool): return 1
[   15.296261] dracut-mount[2146]: //lib/dracut/hooks/mount/98-mount-zfs.sh@5(): ZFS_DATASET=
[   15.296641] dracut-mount[2146]: //lib/dracut/hooks/mount/98-mount-zfs.sh@6(): ZFS_POOL=
[   15.297072] dracut-mount[2146]: //lib/dracut/hooks/mount/98-mount-zfs.sh@8(): case "${root}" in
[   15.297455] dracut-mount[2146]: //lib/dracut/hooks/mount/98-mount-zfs.sh@10(): return
[   15.297830] dracut-mount[2146]: /bin/dracut-mount@25(): ismounted /sysroot
[   15.298233] dracut-mount[2146]: /lib/dracut-lib.sh@551(ismounted): findmnt /sysroot
[   15.298611] dracut-mount[2146]: /bin/dracut-mount@33(): i=11
[   15.298983] dracut-mount[2146]: /bin/dracut-mount@34(): '[' 11 -gt 20 ']'
[   15.299377] dracut-mount[2146]: /bin/dracut-mount@18(): :
[   15.299751] dracut-mount[2146]: /bin/dracut-mount@19(): ismounted /sysroot
[   15.300171] dracut-mount[2146]: /lib/dracut-lib.sh@551(ismounted): findmnt /sysroot
[   15.300551] dracut-mount[2146]: /bin/dracut-mount@23(): for f in '$hookdir/mount/*.sh'
[   15.300925] dracut-mount[2146]: /bin/dracut-mount@24(): '[' -f /lib/dracut/hooks/mount/98-mount-zfs.sh ']'
[   15.301362] dracut-mount[2146]: /bin/dracut-mount@24(): . /lib/dracut/hooks/mount/98-mount-zfs.sh
[   15.301739] dracut-mount[2146]: //lib/dracut/hooks/mount/98-mount-zfs.sh@3(): . /lib/dracut-zfs-lib.sh
[   15.302131] dracut-mount[2146]: ///lib/dracut-zfs-lib.sh@3(): command -v getarg
[   15.302512] dracut-mount[2146]: ///lib/dracut-zfs-lib.sh@4(): command -v getargbool
[   15.302884] dracut-mount[2146]: ///lib/dracut-zfs-lib.sh@23(): OLDIFS='
[   15.303281] dracut-mount[2146]: '
[   15.303656] dracut-mount[2146]: ///lib/dracut-zfs-lib.sh@25(): NEWLINE='
[   15.304048] dracut-mount[2146]: '
```

It ends up looping over and over until:

```
[   18.431435] dracut-mount[2146]: /bin/dracut-mount@33(): i=21
[   18.431809] dracut-mount[2146]: /bin/dracut-mount@34(): '[' 21 -gt 20 ']'
[   18.432232] dracut-mount[2146]: /bin/dracut-mount@34(): action_on_fail 'Can'\''t mount root filesystem'
[   18.432621] dracut-mount[2146]: /lib/dracut-lib.sh@1134(action_on_fail): '[' -f /lib/dracut/no-emergency-shell ']'
[   18.432993] dracut-mount[2146]: /lib/dracut-lib.sh@1142(action_on_fail): emergency_shell 'Can'\''t' mount root filesystem
[   18.433390] dracut-mount[2146]: /lib/dracut-lib.sh@1087(emergency_shell): local _ctty
[   18.433767] dracut-mount[2146]: /lib/dracut-lib.sh@1088(emergency_shell): set +e
[   18.434167] dracut-mount[2146]: /lib/dracut-lib.sh@1089(emergency_shell): local _rdshell_name=dracut action=Boot hook=emergency
[   18.434547] dracut-mount[2146]: /lib/dracut-lib.sh@1090(emergency_shell): local _emergency_action
[   18.434926] dracut-mount[2146]: /lib/dracut-lib.sh@1092(emergency_shell): '[' 'Can'\''t' = -n ']'
[   18.435335] dracut-mount[2146]: /lib/dracut-lib.sh@1095(emergency_shell): '[' 'Can'\''t' = --shutdown ']'
[   18.435722] dracut-mount[2146]: /lib/dracut-lib.sh@1105(emergency_shell): echo
[   18.436120] dracut-mount[2146]: /lib/dracut-lib.sh@1105(emergency_shell): echo
[   18.436498] dracut-mount[2146]: /lib/dracut-lib.sh@1106(emergency_shell): warn 'Can'\''t mount root filesystem'
[   18.436874] dracut-mount[2146]: /lib/dracut-lib.sh@67(warn): echo 'Warning: Can'\''t mount root filesystem'
[   18.437287] dracut-mount[2146]: Warning: Can't mount root filesystem
[   18.437669] dracut-mount[2146]: /lib/dracut-lib.sh@1107(emergency_shell): source_hook emergency
[   18.769571] dracut-mount[2146]: /lib/dracut-lib.sh@425(source_hook): local _dir
[   18.769950] dracut-mount[2146]: /lib/dracut-lib.sh@426(source_hook): _dir=emergency
[   18.770364] dracut-mount[2146]: /lib/dracut-lib.sh@426(source_hook): shift
[   18.770752] dracut-mount[2146]: /lib/dracut-lib.sh@427(source_hook): source_all /lib/dracut/hooks/emergency
[   18.771156] dracut-mount[2146]: /lib/dracut-lib.sh@414(source_all): local f
[   18.771531] dracut-mount[2146]: /lib/dracut-lib.sh@415(source_all): local _dir
[   18.771982] dracut-mount[2146]: /lib/dracut-lib.sh@416(source_all): _dir=/lib/dracut/hooks/emergency
[   18.772389] dracut-mount[2146]: /lib/dracut-lib.sh@416(source_all): shift
[   18.772767] dracut-mount[2146]: /lib/dracut-lib.sh@417(source_all): '[' /lib/dracut/hooks/emergency ']'
[   18.773175] dracut-mount[2146]: /lib/dracut-lib.sh@417(source_all): '[' -d //lib/dracut/hooks/emergency ']'
[   18.773561] dracut-mount[2146]: /lib/dracut-lib.sh@418(source_all): for f in '"/$_dir"/*.sh'
[   18.773937] dracut-mount[2146]: /lib/dracut-lib.sh@418(source_all): '[' -e '//lib/dracut/hooks/emergency/*.sh' ']'
[   18.774351] dracut-mount[2146]: /lib/dracut-lib.sh@1108(emergency_shell): echo
[   18.774753] dracut-mount[2146]: //lib/dracut-lib.sh@1110(emergency_shell): getarg rd.emergency
[   18.775162] dracut-mount[2146]: //lib/dracut-lib.sh@187(getarg): debug_off
[   18.775541] dracut-mount[2146]: //lib/dracut-lib.sh@20(debug_off): set +x
[   18.775910] dracut-mount[2146]: //lib/dracut-lib.sh@227(getarg): return 1
[   18.776335] dracut-mount[2146]: /lib/dracut-lib.sh@1110(emergency_shell): _emergency_action=
[   18.776719] dracut-mount[2146]: /lib/dracut-lib.sh@1111(emergency_shell): '[' -z '' ']'
[   18.777115] dracut-mount[2146]: /lib/dracut-lib.sh@1112(emergency_shell): '[' -e /run/initramfs/.die ']'
[   18.777497] dracut-mount[2146]: /lib/dracut-lib.sh@1115(emergency_shell): getargbool 1 rd.shell -d -y rdshell
[   18.777881] dracut-mount[2146]: /lib/dracut-zfs-lib.sh@238(getargbool): local _b
[   18.778294] dracut-mount[2146]: /lib/dracut-zfs-lib.sh@239(getargbool): unset _b
[   18.778673] dracut-mount[2146]: /lib/dracut-zfs-lib.sh@240(getargbool): local _default
[   18.779076] dracut-mount[2146]: /lib/dracut-zfs-lib.sh@241(getargbool): _default=1
[   18.779455] dracut-mount[2146]: /lib/dracut-zfs-lib.sh@241(getargbool): shift
[   18.779850] dracut-mount[2146]: //lib/dracut-zfs-lib.sh@242(getargbool): getarg rd.shell -d -y rdshell
[   18.780269] dracut-mount[2146]: //lib/dracut-lib.sh@187(getarg): debug_off
[   18.780648] dracut-mount[2146]: //lib/dracut-lib.sh@20(debug_off): set +x
[   18.781044] dracut-mount[2146]: //lib/dracut-lib.sh@227(getarg): return 1
[   18.781452] dracut-mount[2146]: /lib/dracut-zfs-lib.sh@242(getargbool): _b=
[   18.781834] dracut-mount[2146]: /lib/dracut-zfs-lib.sh@243(getargbool): '[' 1 -ne 0 -a -z '' ']'
[   18.782236] dracut-mount[2146]: /lib/dracut-zfs-lib.sh@243(getargbool): _b=1
[   18.782617] dracut-mount[2146]: /lib/dracut-zfs-lib.sh@244(getargbool): '[' -n 1 ']'
[   18.782994] dracut-mount[2146]: /lib/dracut-zfs-lib.sh@245(getargbool): '[' 1 = 0 ']'
[   18.783399] dracut-mount[2146]: /lib/dracut-zfs-lib.sh@246(getargbool): '[' 1 = no ']'
[   18.783778] dracut-mount[2146]: /lib/dracut-zfs-lib.sh@247(getargbool): '[' 1 = off ']'
[   18.784263] dracut-mount[2146]: /lib/dracut-zfs-lib.sh@249(getargbool): return 0
[   18.784654] dracut-mount[2146]: /lib/dracut-lib.sh@1116(emergency_shell): _emergency_shell dracut
[   18.785046] dracut-mount[2146]: /lib/dracut-lib.sh@1046(_emergency_shell): local _name=dracut
[   18.785429] dracut-mount[2146]: /lib/dracut-lib.sh@1047(_emergency_shell): '[' -n 1 ']'
[   18.785810] dracut-mount[2146]: /lib/dracut-lib.sh@1049(_emergency_shell): echo 'PS1="dracut:\${PWD}# "'
[   18.786212] dracut-mount[2146]: /lib/dracut-lib.sh@1050(_emergency_shell): systemctl start dracut-emergency.service
dracut:/#
```

**Comment by kpande** [comment]
are you using plymouth?

**Comment by gordan-bobic** [comment]
No, I exclude all unnecessary dracut modules that bloat the initramfs:
In dracut.conf:
omit_dracutmodules+="nss-softokn i18n plymouth"
add_dracutmodules+="zfs"

**Comment by ghfields** [comment]
With everything working as expected in 0.7.13, I did a the diff between 0.7.13 and 0.8.1 files and searched for changes in the "contrib/dracut".  (https://github.com/zfsonlinux/zfs/compare/zfs-0.8.1...zfs-0.7.13#files_bucket)

By my quick eye, using @mounthelperdir@ instead of @sbindir@ seems to be the big change.  I have not looked at anything past this observation.

**Comment by gordan-bobic** [comment]
This patch that Bernd posted on zfs-discuss seems to fix the issue:

```
*** /usr/share/dracut/modules.d/90zfs/mount-zfs.sh.orig 2019-06-14 08:36:18.818038254 +0200
--- /usr/share/dracut/modules.d/90zfs/mount-zfs.sh      2019-06-14 08:37:22.065510759 +0200
***************
*** 5,15 ****
  ZFS_DATASET=""
  ZFS_POOL=""

- case "${root}" in
-       zfs:*) ;;
-       *) return ;;
- esac
-
  GENERATOR_FILE=/run/systemd/generator/sysroot.mount
  GENERATOR_EXTENSION=/run/systemd/generator/sysroot.mount.d/zfs-enhancement.conf

--- 5,10 ----
```

**Comment by ghfields** [comment]
I did see that come through the list and should have included that info.  Thanks. 

That code snip is 4 years old (https://github.com/zfsonlinux/zfs/commit/eda3d4e1de94cd3a9247bb90a64413a89e736847), so I was looking for the other changes that would make this section of code start to fail.

**Comment by rugubara** [comment]
I don't observe this behaviour on my hosts:

anton@PF16W6Y2 ~ $ uname -a
Linux PF16W6Y2 5.1.14-gentoo #1 SMP PREEMPT Mon Jun 24 14:42:18 MSK 2019 x86_64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz GenuineIntel GNU/Linux
anton@PF16W6Y2 ~ $ zfs --version
zfs-0.8.1-r0-gentoo
zfs-kmod-0.8.1-r0-gentoo

Booted from the zfs root ok.

**Comment by gordan-bobic** [comment]
Do you use zfs-dracut, or something else in your initramfs?
What is your root= kernel parameter?
Do you have bootfs property on the pool set?

I have reproduced the errant behaviour on _all_ of my CentOS 7 machines with ZFS root, three x86-64, one aarch64. It's consistent.

**Comment by rugubara** [comment]
Since I use mostly gentoo, I have trouble figuring out which flavour of dracut I use. 
The main dracut package is version 049-r1.
My package manager tells me that /usr/lib/dracut/modules.d/90zfs/mount-zfs.sh  was installed by sys-fs/zfs-0.8.1 package.
```
PF16W6Y2 ~ # equery b  /usr/lib/dracut/modules.d/90zfs/mount-zfs.sh 
 * Searching for /usr/lib/dracut/modules.d/90zfs/mount-zfs.sh ... 
sys-fs/zfs-0.8.1 (/usr/lib/dracut/modules.d/90zfs/mount-zfs.sh)
```
zfs is built with the following config options:
```
                --bindir="${EPREFIX}/bin"
                --enable-systemd
                --enable-sysvinit
                --localstatedir="${EPREFIX}/var"
                --sbindir="${EPREFIX}/sbin"
                --with-config=user
                --with-dracutdir="${EPREFIX}/usr/lib/dracut"
                --with-linux="${KV_DIR}"
                --with-linux-obj="${KV_OUT_DIR}"
                --with-udevdir="$(get_udevdir)"
                --with-systemdunitdir="$(systemd_get_systemunitdir)"
                --with-systemdpresetdir="${EPREFIX}/lib/systemd/system-preset"
```
I have bootfs property set to the root dataset.
Here is my kernel cmdline: root=ZFS=fast/system

**Comment by gordan-bobic** [comment]
Strange. I was only able to make it work with the patch above, and I wasn't the first one to have come up with the patch - Bernd hit the same issue before me and sent me the patch as a workaround, as discussed on the mailing list.

**Comment by rugubara** [comment]
I've reviewed the patches that zfs package applies. It only does PATCHES=( "${FILESDIR}/bash-completion-sudo.patch" ).

**Comment by gordan-bobic** [comment]
The diff shows far more than that:
$ diff -ruN zfs-0.7.13/contrib/dracut/90zfs zfs-0.8.1/contrib/dracut/90zfs

[zfs-dracut-0.7.13-0.8.1.txt](https://github.com/zfsonlinux/zfs/files/3324561/zfs-dracut-0.7.13-0.8.1.txt)

**Comment by rugubara** [comment]
> The diff shows far more than that:
> $ diff -ruN zfs-0.7.13/contrib/dracut/90zfs zfs-0.8.1/contrib/dracut/90zfs
> 
> [zfs-dracut-0.7.13-0.8.1.txt](https://github.com/zfsonlinux/zfs/files/3324561/zfs-dracut-0.7.13-0.8.1.txt)

I mean that sometimes packages in gentoo incorporate patches ahead of the upstream release schedule to fix critical bugs quickly w/o rolling back package version. 
I checked what patches were applied on top of 0.8.1 and found nothing except bash completion related.

**Comment by covici** [comment]
I am using gentoo, kernel 4.19.56 with the gentoo patches and gentoo is updated as of maybe a week ago and get this error.  I wonder if the patch would help me, maybe I can try it, will have to look into it.

**Comment by covici** [comment]
The patch would not apply, it said reversed  (or previously applied patch) detected.  Not sure why as those lines are in zfs-mount.sh and the purpose was to delete them, I will do by hand and regenerate the initrd.

**Comment by covici** [comment]
So, I deleted the lines in the zfs-mount.sh and rebooted using root=zfs:rpool/root and the mount did not work.  Here is what I get in the logs
Jul 09 05:34:02 ccs systemd[1]: Starting dracut pre-mount hook...
Jul 09 05:34:02 ccs systemd[1]: Started dracut pre-mount hook.
Jul 09 05:34:02 ccs systemd[1]: Mounting /sysroot...
Jul 09 05:34:02 ccs mount[1581]: filesystem 'rpool/root' cannot be mounted using 'zfs mount'.
Jul 09 05:34:02 ccs mount[1581]: Use 'zfs set mountpoint=/sysroot' or 'mount -t zfs rpool/root /sysroot'.
Jul 09 05:34:02 ccs mount[1581]: See zfs(8) for more information.
Jul 09 05:34:02 ccs systemd[1]: sysroot.mount: Mount process exited, code=exited, status=1/FAILURE

So, I added root= on the command line and it mounted the file system by itself -- this was the previous behavior in 0.7.13.  Not sure what exactly is going on, but at least I have something that will boot by itself.

**Comment by gordan-bobic** [comment]
Apologies if this is a stupid question, but - you DID rebuild the initrd after deleting those lines, right?

**Comment by covici** [comment]
Sure and the behavior did change.  Before deleting the lines saying
root= no longer would find the correct dataset, after deleting the
lines and regenerating the initrd root= did work again.

On Tue, 09 Jul 2019 06:16:29 -0400,
gordan-bobic wrote:
> 
> [1  <text/plain; UTF-8 (7bit)>]
> [2  <text/html; UTF-8 (7bit)>]
> Apologies if this is a stupid question, but - you DID rebuild the initrd after deleting those lines, right?
> 
> ―
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici wb2una
         covici@ccs.covici.com

**Comment by gordan-bobic** [comment]
This bug still manifests in 0.8.2. Same change to mount-zfs.sh mentioned here fixed it: https://github.com/zfsonlinux/zfs/issues/8913#issuecomment-502688138

**Comment by tsandmann** [comment]
I ran into exactly the same issue on CentOS 7.7 x86_64 after upgrading from ZFS 0.7.x to 0.8.2.

With some debugging I found out that the problem is caused by `zfs-load-key.sh` line 31 and 32:
https://github.com/zfsonlinux/zfs/blob/7bb0c294688ed121477536d7b4a7031c78a5706a/contrib/dracut/90zfs/zfs-load-key.sh.in#L31 https://github.com/zfsonlinux/zfs/blob/7bb0c294688ed121477536d7b4a7031c78a5706a/contrib/dracut/90zfs/zfs-load-key.sh.in#L32
because there the "zfs"-prefix is removed from `${root}`, but which is required for the the test if we are on ZFS-root in https://github.com/zfsonlinux/zfs/blob/7bb0c294688ed121477536d7b4a7031c78a5706a/contrib/dracut/90zfs/mount-zfs.sh.in#L8
```
case "${root}" in
	zfs:*) ;;
	*) return ;;
esac
```
Therefore mount-zfs.sh just exits and doesn't mount the root-fs properly.
So I think `${root}` must not be changed by `zfs-load-key.sh` before it is evaluated by `mount-zfs.sh` (at least as long as `mount-zfs.sh` relies on the the "zfs"-prefix in `${root}`).
