### ISSUE TITLE
zfs load-key stuck in a loop with encrypted pool at boot time with dracut built initramfs

### ISSUE THREAD

**Issue by dacianstremtan** [zfsonlinux/zfs#8920]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  CentOS
Distribution Version	| 7.6.1810 (Core)
Linux Kernel	| 3.10.0-957.21.2.el7.x86_64
Architecture	| x86_64
ZFS Version	| 0.8.1-1
SPL Version	| 0.8.1-1

### Describe the problem you're observing
I'm using encrypted pool for my root file system.  During boot I should be prompted to put the password for decryption.  The plymouth spinner keeps going without a prompt.  Escaping to shell I see the following prompts on the screen:
....
[....] dracut-mount[1867]: filesystem 'rpool/ROOT/centos7' can not be mounted: Permission denied
[....] dracut-mount[1867]: Encrypted ZFS password for rpool: [1/5]: Key load error: encryption failure
[....] dracut-mount[1867]: Encrypted ZFS password for rpool: [2/5]: Key load error: encryption failure
[....] dracut-mount[1867]: Encrypted ZFS password for rpool: [3/5]: Key load error: encryption failure
[....] dracut-mount[1867]: Encrypted ZFS password for rpool: [4/5]: Key load error: encryption failure
[....] dracut-mount[1867]: Encrypted ZFS password for rpool: [5/5]: Key load error: encryption failure
[....] dracut-mount[1867]: Wrong password
[....] dracut-mount[1867]: filesystem 'rpool/ROOT/centos7' can not be mounted: Permission denied
...

### Describe how to reproduce the problem
I built zfs 0.8.1 release from source using:

./autogen.sh
./configure
make rpm
sudo yum install kmod-zfs-3.10.0-957.12.2.el7.x86_64-0.8.1-1.el7.x86_64.rpm libnvpair1-0.8.1-1.el7.x86_64.rpm libuutil1-0.8.1-1.el7.x86_64.rpm libzfs2-0.8.1-1.el7.x86_64.rpm libzpool2-0.8.1-1.el7.x86_64.rpm python2-pyzfs-0.8.1-1.el7.noarch.rpm zfs-0.8.1-1.el7.x86_64.rpm zfs-dracut-0.8.1-1.el7.x86_64.rpm 
sudo dracut /boot/initramfs-3.10.0-957.21.2.el7.x86_64.img 3.10.0-957.21.2.el7.x86_64 --force --verbose
reboot the system in the kernel image with the new initramfs built by dracut

**Comment by dacianstremtan** [comment]
The way I fix it was to modify line 147 in /usr/lib/dracut/modules.d/90zfs/zfs-lib.sh 
instead of:
 - `if whereis plymouth >/dev/null 2>&1 && plymouth --ping 2>/dev/null; then`

use:

 - `if type plymouth >/dev/null 2>&1 && plymouth --ping 2>/dev/null; then`

The CentOS dracut does not include `whereis` and `which` commands in the initramfs.  The dracut plymouth module also uses type command instead of whereis.

**Comment by behlendorf** [comment]
@dacianstremtan thanks for running this down.  I agree switching this to `type` is the right way to handle it and is consistent with the other dracut provided modules (`crypt-lib.sh`, `dracut-emergency.sh`, etc)  Would you mind opening a PR with this small change.

**Comment by dacianstremtan** [comment]
@behlendorf submitted a new PR for this issue: #8938.  Still new on github, sorry for the pr #8937.

**Comment by behlendorf** [comment]
@dacianstremtan no problem, thanks!
