### ISSUE TITLE
0.8.1 encrypted filesystem does not allow console login with SELinux

### ISSUE THREAD

**Issue by elirov** [zfsonlinux/zfs#8927]
### System information

ZFS | 0.8.1
 --- | --- 
Distribution Name	| Fedora
Distribution Version	| 30 
Kernel | 5.1.8-300.fc30.x86_64
architecture	| 64 bit
ZFS Version	| 0.8.1-1
SPL Version	| 0.8.1-1

### Describe the problem you're observing
Trying to log in from the console under the following conditions give me the following error: change directory failed - permission denied

Also, trying to start an X session just loops back to the login screen (maybe due to the above error in the console.)

Conditions:
1. SE Linux Enforcing
2. ZFS 0.8.1 volume used for /home/test (user test)

If I turn off SE Linux (setenforce 0) or if I set the home directory to a non-ZFS volume, the error message on the console goes away and I am able to successfully log into an X session.

### Describe how to reproduce the problem
set up a test user with a home directory inside an encrypted ZFS volume under 0.8.1.  make sure SELinux is enforcing.  Try to log into the console or start an X session under that user.

### Include any warning/errors/backtraces from the system logs
SELinux troubleshooter shows an error trying to access /root/tmp/tmpkcux_92o file when trying to log into the console under the test user.  The /root/tmp directory exists.  Source process shows load_policy.  

Also, SELinux shows a warning for source process: login attempting search on the root directory, and also separately attempting search on the test directory.

**Comment by elirov** [comment]
updating the SELinux policy to allow search for the test login eliminates the console login error.
ausearch -c 'login' --raw | audit2allow -M test
semodule -i test.pp

**Comment by behlendorf** [comment]
@elirov is this only an issue with encrypted datasets?  As you describe it it sounds like an issue with the Fedora SELinux policy.  Is there anything we can do on the ZFS side?

**Comment by elirov** [comment]
I haven't tried with a normal dataset.  I'm wondering if it's somehow
trying to access the key stored in my root filesystem and setting off
selinux because of that.

**Comment by elirov** [comment]
the SELinux update definitely fixed the problem for me.  is this something that can be put into the dnf install process to make it easier to do the install?  just curious.

**Comment by behlendorf** [comment]
Could you post exactly what was denied?  I'm not sure why you would get an error accessing the `/root/tmp/tmpkcux_92o` file which presumably isn't stored in ZFS.

**Comment by elirov** [comment]
I'd have to redo the entire setup to try to reproduce this error.  Maybe close this for now and revisit if anyone else runs into it?  I'd hate to waste time on this if it's just a weird one-off or something.

**Comment by behlendorf** [comment]
@elirov sounds good.  Then I'm going to close this since this is the only report of this we've had.
