### ISSUE TITLE
"zfs diff" fails with "Unable to determine path or stats for object ...: File exists" on encrypted filesystems

### ISSUE THREAD

**Issue by chungy** [zfsonlinux/zfs#8931]
### System information
Type | Version/Name
 --- | --- 
Distribution Name	| Arch
Distribution Version	| N/A
Linux Kernel	| 5.1.11-arch1-1-ARCH
Architecture	| x86_64
ZFS Version	| 0.8.1
SPL Version	| 0.8.1

### Describe the problem you're observing

When running against an encrypted dataset, the `zfs diff` command fails to complete its task, outputting a message at the end such as:
`Unable to determine path or stats for object $objid in $dataset: File exists`

### Describe how to reproduce the problem
Have an encrypted dataset, key loaded and mounted, with a snapshot and with data changed after the snapshot, run the `zfs diff` command against the snapshot.

Example:
```
# zfs create -o mountpoint=/mnt rpool/temp
# cd /mnt/
# echo hello > alice
# zfs snapshot rpool/temp@alice
# echo new > bob
# zfs diff rpool/temp@alice
M	/mnt/
+	/mnt/bob
# zfs create -o encryption=on -o keyformat=passphrase rpool/temp/encr 
Enter passphrase: 
Re-enter passphrase: 
# cd encr/
# echo hello > alice
# zfs snap rpool/temp/encr@alice
# echo new > bob
# zfs diff rpool/temp/encr@alice
Unable to determine path or stats for object 3 in rpool/temp/encr@alice: File exists
```

**Comment by behlendorf** [comment]
@chungy I wasn't able to reproduce this issue using 0.8.1 on Fedora 30 using the reproducer you provided.  Are you able to reproduce this consistently on Arch?

```sh
$ zfs diff tank/temp/encr@alice
M	/tank/temp/encr/
+	/tank/temp/encr/bob
+	/tank/temp/encr/bob/<xattrdir>
+	/tank/temp/encr/bob/<xattrdir>/security.selinux
```

**Comment by chungy** [comment]
Yes, it happens consistently on Arch.

**Comment by youzhongyang** [comment]
While playing with zfs on Clear Linux, I tried the reproduction steps. Not reproduced.
```
root@clearlinux-dev/mnt/encr # zfs diff tank/temp/encr@alice
+       /mnt/encr/bob
M       /mnt/encr/
root@clearlinux-dev/mnt/encr # zfs version
zfs-0.8.1-1
zfs-kmod-0.8.1-1
root@clearlinux-dev/mnt/encr # uname -a
Linux clearlinux-dev 5.1.12-785.native #1 SMP Wed Jun 19 07:09:10 UTC 2019 x86_64 GNU/Linux
```

**Comment by sempervictus** [comment]
Any chance this is another side effect of the slow path use without SIMD? 5.1.1 has the GPL_ONLY FPU export thing going...
There have also been a bunch of changes in Arch userspace recently, and we are now on GCC 9.1, so might be worth rebuilding the userspace side of things. (We use an in-house fork of Arch for servers and workstations, and have successful builds of our 0.7.13 zfs-integrated kernels on GCC 9.1 in testing now. 0.7 because reading the issue tracker makes 0.8 seem untenably dangerous for prod use).

**Comment by HankB** [comment]
I believe I have been able to reproduce this on Debian with 0.8.1 installed from the Github repo. It seems to be related to the number of files in a snapshot. I discovered this after installing `gnome-core` on a relatively bare system and could not view a diff of the files changed (~65K lines in the output on an unencrypted install.) I can recreate using the following commands

```bash
root@mlbry03:/home/hbarta# zfs create rpool/home/hbarta/test
root@mlbry03:/home/hbarta# chown hbarta.hbarta test
root@mlbry03:/home/hbarta# zfs snap rpool/home/hbarta/test@create
```

````bash
hbarta@mlbry03:~/test$ for i in {1..100}; do for j in {1..100}; do echo $i $j > ${i}.${j}.txt; done; done
hbarta@mlbry03:~/test$ find .|wc -l
10001
hbarta@mlbry03:~/test$ 
````

````bash
root@mlbry03:/home/hbarta# zfs diff rpool/home/hbarta/test@create|wc -l
1
Unable to determine path or stats for object 3 in rpool/home/hbarta/test@zfs-diff-14831-00000001000ed5dd: File exists
root@mlbry03:/home/hbarta# 
````

This is on a Lenovo Y50 (I7 processor, 16GB RAM and 120GB cheap SATA SSD.) Install is per instructions at https://github.com/zfsonlinux/zfs/wiki/Debian-Buster-Encrypted-Root-on-ZFS, scripted using https://github.com/HankB/Linux_ZFS_Root/blob/master/Debian/install_Debian_to_ZFS_root.sh

**Comment by bew-dev** [comment]
This is happening to me still
```
$ zfs diff nas/live/rsnapshot@merged-san-2021-0930 nas/live/rsnapshot@rsnap-weekly-2021-1001 
M       /nas/live/rsnapshot/
Unable to determine path or stats for object 65926 in nas/live/rsnapshot@merged-san-2021-0930: No such file or directory
```
