### ISSUE TITLE
Wiki (custom packages) outdated

### ISSUE THREAD

**Issue by dewi-ny-je** [zfsonlinux/zfs#8932]
The wiki in the "[Custom packages](https://github.com/zfsonlinux/zfs/wiki/Custom-Packages)" page still lists compilation steps for spl, no more required with 0.8.x releases.

I wasn't able to edit the wiki, so I open this ticket.

**Comment by behlendorf** [comment]
Thanks for the reminder, I've updated the wiki pages.
