### ISSUE TITLE
Import FreeBSD pool into Linux

### ISSUE THREAD

**Issue by eiselekd** [zfsonlinux/zfs#8972]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu 
Distribution Version	| 18.10
Linux Kernel	| 4.18
Architecture	| x86_64
ZFS Version	| v0.7.9-3ubuntu6

I have a FreeBSD pool that I want to import in Linux and wonder weather the 2 versions are compatible.
Currently I can only mount it readonly:

```
sudo zpool import poolmirrorr2r3r0
This pool uses the following feature(s) not supported by this system:
        com.delphix:spacemap_v2 (Space maps representing large segments are more efficient.)
        org.zfsonlinux:project_quota (space/object accounting based on project ID.)
All unsupported features are only required for writing to the pool.
The pool can be imported using '-o readonly=on'.
cannot import 'poolmirrorr2r3r0': unsupported version or feature
```

Is there a possibility to import it read-write or do I need to recreate the pool and copy over the files?

**Comment by AndCycle** [comment]
no, if you wanna write you need that feature support, it's currently live in master branch https://github.com/zfsonlinux/zfs/commit/4d044c4c1d68ed518fe37eea61a4cc77048940fb

**Comment by AndCycle** [comment]
you need ZoL 0.8
EDIT: delete incorrect comment

**Comment by behlendorf** [comment]
@eiselekd the required features to mount it read-write were included in ZoL 0.8.  Since several other features were included in this release that are not yet available on FreeBSD you'll want to be careful about enabling any additional features.  Here's the current [compatibility matrix](http://build.zfsonlinux.org/zfs-features.html).

**Comment by kusumi** [comment]
`DragonFlyBSD` `zfsport` should be removed from http://build.zfsonlinux.org/zfs-features.html.

Afaik there is no such thing, and DragonFlyBSD also isn't kabi compatible with FreeBSD kernel modules (basically never was in the past too).

**Comment by eiselekd** [comment]
Recompiled to 0.8.0 and I'm able to import the FreeBSD pools r/w. Thanks.

**Comment by xiruizhao** [comment]
| Distro | Ubuntu 18.04.3 LTS (Linux 5.0.0-27-generic) x86_64 |
| --- | --- |
| ZFS | zfs-0.8.1-1, zfs-kmod-0.7.12-1ubuntu5 |

I still failed to import a zfs pool (created on macOS) into linux because of spacemap_v2. What should I do?

```
This pool uses the following feature(s) not supported by this system:
	com.delphix:spacemap_v2 (Space maps representing large segments are more efficient.)
All unsupported features are only required for writing to the pool.
The pool can be imported using '-o readonly=on'.
cannot import 'raid0': unsupported version or feature
```

**Comment by AndCycle** [comment]
> ZFS 	zfs-0.8.1-1, zfs-kmod-0.7.12-1ubuntu5

you only update half of your system, 
`zfs-kmod-0.7.12-1ubuntu5`

**Comment by xiruizhao** [comment]
I don't know much about linux. So what am I supposed to do now? @AndCycle Thanks.

**Comment by AndCycle** [comment]
@xiruizhao I don't use ubuntu at all, you need to find relative forum for that discussion. 
or go to the https://zfsonlinux.topicbox.com/groups/zfs-announce and seek for help
