### ISSUE TITLE
systemd zfs-mount service should call zfs mount -a -l instead of zfs mount -a?

### ISSUE THREAD

**Issue by elirov** [zfsonlinux/zfs#8983]
ZFS | 0.8.1
-- | --
Distribution Name | Fedora
Distribution Version | 30
Kernel | 5.1.8-300.fc30.x86_64
architecture | 64 bit
ZFS Version | 0.8.1-1
SPL Version | 0.8.1-1

### Describe the problem you're observing
starting up Fedora, the encrypted volume is not automatically mounting

### Describe how to reproduce the problem
create an encrypted volume and put a passphrase in /zfs-passphrase
verify that zfs mount -a -l works
restart Fedora
encrypted volume does not automatically mount
run zfs mount -a -l
volume is mounted

**Comment by loli10K** [comment]
Duplicate of #8750

**Comment by elirov** [comment]
Oops..  Sorry.
