### ISSUE TITLE
Cache suddenly accessed as /dev/sd* instead of /dev/disk/by-id/*

### ISSUE THREAD

**Issue by s-m-e** [zfsonlinux/zfs#8996]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| openSUSE
Distribution Version	|  Leap 15.1
Linux Kernel	| 4.12.14-lp151.28.7-default
Architecture	| x86_64
ZFS Version	| 0.8.1-1 (0.8.1-lp151.4.3.x86_64)
SPL Version	| 0.8.1-1

### Describe the problem you're observing

I am suddenly seeing the L2ARC / cache device not being accessed based on `/dev/disk/by-id/*` as originally configured by instead based on `/dev/sd*`, see below example:

```
# zpool status
  pool: data
 state: ONLINE
  scan: scrub in progress [...]
config:

        NAME                                                   STATE     READ WRITE CKSUM
        data                                                   ONLINE       0     0     0
          raidz1-0                                             ONLINE       0     0     0
            ata-ST-X_123                   ONLINE       0     0     0
            ata-ST-Y_456                   ONLINE       0     0     0
            ata-ST-Z_789                   ONLINE       0     0     0
        logs
          ata-SSD_ABC-part3  ONLINE       0     0     0
        cache
          sda4                                                 ONLINE       0     0     0

errors: No known data errors
```

`sda4` should actually read `ata-SSD_ABC-part4`.

### Describe how to reproduce the problem

Immediately before this happened, I had opened the server for maintenance. I suspect that I swapped the cables for ata-ST-Y_456 and ata-ST-Z_789. After I booted the system, the pool was not automatically discovered / mounted. I had to import it manually with `zpool import data`. Once this was done, I discovered the above issue.

### Include any warning/errors/backtraces from the system logs

(I could not track down any.)

**Comment by kpande** [comment]
use `-d /dev/disk/by-id`, and make sure you have a zpool cachefile configured if you want this to persist. you have to embed it in the initrd for root installations.

**Comment by s-m-e** [comment]
@kpande Thanks. The operating system is not installed on ZFS. In terms of making this permanent, if I understand you correctly, I would need to export and (re-) import my pool? I.e.

```
zpool export data
zpool import -d /dev/disk/by-id data
```

**Comment by kpande** [comment]
yes and then `zpool set cachefile=/etc/zfs/zpool.cache [pool]` or similar.

**Comment by s-m-e** [comment]
@kpande Ok, the export-import-strategy solved my issue. 

Setting the cachefile on the other hand did not change anything:

```
# zpool get cachefile
NAME  PROPERTY   VALUE      SOURCE
data  cachefile  -          default
# zpool set cachefile=/etc/zfs/zpool.cache data
# zpool get cachefile
NAME  PROPERTY   VALUE      SOURCE
data  cachefile  -          default
```

Nevertheless, I'd close this one for now. Thanks a lot.
