### ISSUE TITLE
Are users allowed non-modifying operations by default?

### ISSUE THREAD

**Issue by s-m-e** [zfsonlinux/zfs#9006]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| openSUSE
Distribution Version	|  Leap 15.1
Linux Kernel	| 4.12.14-lp151.28.7-default
Architecture	| x86_64
ZFS Version	| 0.8.1-1 (0.8.1-lp151.4.3.x86_64)
SPL Version	| 0.8.1-1

### Describe the problem you're observing

I just came across this: "ZFS allows anyone to use non modifying commands", see [this discussion](https://github.com/mafm/zfs-snapshot-disk-usage-matrix/issues/1). It is especially interesting since this is supposed to work without any modifications to `sudoers`.

As far as openSUSE is concerned, the `zfs` and `zpool` commands reside in `/usr/sbin` and can therefore not be run by non-root users. `/usr/sbin` also appears to be the default location for those commands when building ZoL from source.

Seeking clarification: What is a regular user by default supposed to be allowed? What is the canonical way to allow users "non-modifying" commands?

### Describe how to reproduce the problem

Clean openSUSE Leap 15.1 system. ZoL packages from [here](https://software.opensuse.org/package/zfs).

### Include any warning/errors/backtraces from the system logs

n/a

**Comment by ahrens** [comment]
Not sure about SUSE but it does work by default on Ubuntu (unprivileged users can run "zfs list", etc).

**Comment by DeHackEd** [comment]
`/sbin/` (and by extension `/usr/sbin`) isn't meant as a "normal users not allowed here" directory. sendmail historically lives in /usr/sbin, for example. Maybe suse is different here?

And yes, non-modification commands are allowed for all by default on ZFS as of the 0.7.0 release. If this is a concern I recommend modifying the udev rules to restrict permissions to `/dev/zfs`.

**Comment by richardelling** [comment]
Historically, /sbin held the system binaries required to boot to single-user mode. This never had anything to do with security. Consider a situation where /usr and / are on separate file systems and /usr is remotely mounted via NFS (eg how Sun ran diskless nodes for a few decades). Also, many diskless nodes shared a single, readonly NFS mount point for /usr while each had their own, unshared /. If for some reason you couldn't mount /usr, then you'd still like to be able to troubleshoot and fix.

**Comment by s-m-e** [comment]
Closing this as it appears to be a SUSE-related issue. Binaries in `/usr/sbin` can in fact not be run as a regular user in SUSE systems. I symlinked `zfs` and `zpool` to `/usr/bin` and non-modifying operations are working as expected for all users (and modifying operations are still prohibited of cause).

**Comment by aaronpuchert** [comment]
> As far as openSUSE is concerned, the `zfs` and `zpool` commands reside in `/usr/sbin` and can therefore not be run by non-root users.

That's not really true, `/usr/sbin` is world-readable and executables in there have mode 0755 by default. So you can run the executables. The directory isn't part of a non-root user's `PATH` though, so you either have to type out the full path or amend the `PATH` variable.

The [FHS specifies](http://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s10.html) that “[/usr/sbin] contains any non-essential binaries used exclusively by the system administrator.” One could argue that this is no longer satisfied if there are legitimate non-root uses, but there are other binaries in /usr/sbin/ that are mostly for administrative work yet allow unprivileged uses. A good example is `getcap`, which puts itself in /usr/sbin by virtue of having a [section 8 man page](http://www.man7.org/linux/man-pages/man8/getcap.8.html) despite requiring no privileges (as far as I can tell).
