### ISSUE TITLE
Linux 5.2 status?

### ISSUE THREAD

**Issue by zviratko** [zfsonlinux/zfs#9014]
I'd like to ask about the state of Linux-5.2.x support. I was able to compile HEAD against it but I have no idea whether it's supposed to be at least somewhat safe to run and test or whether it will eat my data due to some known issues.

Things like https://github.com/zfsonlinux/zfs/issues/8867 sound scary

Thanks

**Comment by behlendorf** [comment]
@zviratko good question.  Both 0.8.1 and master have had the full ZFS test suite run with the released Linux 5.2 kernel and they both passed without issue.  The issue reported in #8867 was only ever observed in 5.2-rc1 and not subsequent rcs.
