### ISSUE TITLE
Why does inode ops dynamically allocate vattr_t (or why others don't)

### ISSUE THREAD

**Issue by kusumi** [zfsonlinux/zfs#9017]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| 
Distribution Version	| 
Linux Kernel	| 
Architecture	| 
ZFS Version	| master
SPL Version	| 

### Describe the problem you're observing

There is a case where it choose to do dynamically due to recursiveness (e.g. `dbuf_hold_impl()`), but `vattr_t` in iops isn't the case.

`vattr_t` takes >100 bytes in kernel stack, so I presume that's the reason.

But then what makes difference for other ones that aren't dynamic (below) ? It seems most of them should also be dynamic if contexts allow sleep.

e.g. `zfs_get_xattrdir()` is used within `.lookup`, so it's a part of iops.

```
# grep vattr_t module/ -rIn | grep -v "\*" | grep -v kmem
module/spl/spl-kobj.c:75:       vattr_t vap;
module/zfs/vdev_file.c:63:      vattr_t vattr;
module/zfs/zfs_dir.c:1119:      vattr_t         va;
module/zfs/zfs_vnops.c:2842:    vattr_t         oldva;
module/zfs/zfs_vnops.c:4878:    vattr_t vap;
module/zfs/zfs_znode.c:1812:    vattr_t         vattr;
module/zfs/zfs_replay.c:286:    xvattr_t xva;
module/zfs/zfs_replay.c:435:    xvattr_t xva;
module/zfs/zfs_replay.c:813:    xvattr_t xva;
module/zfs/zpl_file.c:917:      xvattr_t xva;
module/zfs/zpl_file.c:957:      xvattr_t xva;
```

**Comment by behlendorf** [comment]
This inconsistency is largely the result of trying to minimize differences between the code on different platforms.  The new Linux specific code added in `module/zfs/zpl_*` tended to allocate it dynamically to minimize stack usage, while the original Sun code in `module/zfs/zfs_*` placed it on the stack.  In practice, there hasn't been a need to move them all of the stack so it wasn't changed.

**Comment by kusumi** [comment]
ok, thanks for explanation.
