### ISSUE TITLE
Undefined symbol gethrtime

### ISSUE THREAD

**Issue by geertijewski** [zfsonlinux/zfs#9018]
### System information
Type | Version/Name
 --- | --- 
Distribution Name	|  debian
Distribution Version	|  buster
Linux Kernel	|  4.9.0-8-amd64
Architecture	|  AMD64
ZFS Version	|  0.6.5.9-5
SPL Version	|  0.6.5.9-1

### Describe the problem you're observing
ZFS flat out does not load.

### Describe how to reproduce the problem
```
$ modprobe zfs
# empty
$ zpool
zpool: symbol lookup error: /lib/libzpool.so.2: undefined symbol: gethrtime
```

### Include any warning/errors/backtraces from the system logs
```
$ ldd /lib/libzpool.so.2
	linux-vdso.so.1 (0x00007fffa5f1c000)
	libuutil.so.1 => /lib/libuutil.so.1 (0x00007f15aa44a000)
	libnvpair.so.1 => /lib/libnvpair.so.1 (0x00007f15aa434000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f15a9baa000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f15a998c000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f15a976f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f15a93d0000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f15a91c8000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f15aa24a000)
```

**Comment by johnnyjacq16** [comment]
You are on Debian Stretch still, as the zfs version that is in Debian Buster is 0.7.12-2+deb10u1 and the kernel version should 4.19. 
Please ensure that the zfs-dkms package is installed with command `apt list zfs-dkms` it will tell you if the package is installed and was built by dkms with the `dkms status `command.

**Comment by geertijewski** [comment]
You are right, updating `zfs-dkms` and rebooting worked. I guess I did an incomplete update (because `lsb_release -a` did show buster but in my `/etc/apt/sources.list` it had the stretch mirrors)

Thank you very much
