### ISSUE TITLE
zvol always flagged non-rotational

### ISSUE THREAD

**Issue by stephan2012** [zfsonlinux/zfs#9033]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Debian GNU/Linux
Distribution Version	| 9.9
Linux Kernel	| `Linux n0041 4.19.0-0.bpo.5-amd64 #1 SMP Debian 4.19.37-4~bpo9+1 (2019-06-19) x86_64 GNU/Linux`
Architecture	| x86_64
ZFS Version	| `0.7.12-1~bpo9+1`
SPL Version	| `0.7.12-1~bpo9+1`

### Describe the problem you're observing
zvols are always flagged non-rotational despite of the pool's vdevs:

```
# zpool status bulkpool
  pool: bulkpool
 state: ONLINE
  scan: scrub repaired 0B in 12h34m with 0 errors on Sun Jun  9 12:58:47 2019
config:

        NAME        STATE     READ WRITE CKSUM
        bulkpool    ONLINE       0     0     0
          raidz1-0  ONLINE       0     0     0
            sdc     ONLINE       0     0     0
            sdd     ONLINE       0     0     0
            sde     ONLINE       0     0     0
            sdf     ONLINE       0     0     0
            sdg     ONLINE       0     0     0

# cat /sys/block/sdc/queue/rotational 
1
# cat /sys/block/sdd/queue/rotational  
1
# cat /sys/block/sde/queue/rotational  
1
# cat /sys/block/sdf/queue/rotational  
1
# cat /sys/block/sdg/queue/rotational  
1

# zfs create -b 128K -V 10G bulkpool/testvol
# ll /dev/zvol/bulkpool/testvol 
lrwxrwxrwx 1 root root 11 Jul 13 15:19 /dev/zvol/bulkpool/testvol -> ../../zd416
# cat /sys/block/zd416/queue/rotational 
0
```

This behavior confuses applications that try to adjust their I/O strategy to the underlying device type. E.g., current Rook/Ceph refuses to automatically create a WAL on a SSD zvol becauses it seems to have the same storage characteristics as the zvol homed in a rotational disk zpool.

Suggestion: Either dervice the rotational indicator from vdevs or make it configurable.

### Describe how to reproduce the problem
Create zpool, create zvol, check `/sys/block/<blockdevice>/queue/rotational`.

**Comment by richardelling** [comment]
ceph is mistaken that rotation means performance. However, there is nothing to do here because the rotation is already mutable:
```
root@elvis:/sys/block/zd0/queue# cat rotational
0
root@elvis:/sys/block/zd0/queue# echo 1 > rotational
root@elvis:/sys/block/zd0/queue# cat rotational
1
```

It would be trivial to add a udev rule to make that change. However, in general, I see no other benefit for such a silly, misguided application.

**Comment by stephan2012** [comment]
Yes, you are right. I was testing changing `queue/rotational` already but must have mixed-up things. I'll close this issue. Sorry for the noise.

**Comment by richardelling** [comment]
If you do create a udev rule, please post it back here for future searches. Thanks!
