### ISSUE TITLE
pjdfstest/tests/chmod/12.t failure

### ISSUE THREAD

**Issue by kusumi** [zfsonlinux/zfs#9035]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| 
Distribution Version	| 
Linux Kernel	| 
Architecture	| 
ZFS Version	|  master
SPL Version	| 

### Describe the problem you're observing
https://github.com/pjd/pjdfstest/blob/master/tests/chmod/12.t
fails on ZFS. This was successful with ext2, ext4, XFS.

```
1..14
ok 1
ok 2
not ok 3 - tried '-u 65534 -g 65534 open pjdfstest_71683b1760c307c43fdaa3b45b80884e 
O_WRONLY : write 0 x : fstat 0 mode', expected 0777, got 04777
not ok 4 - tried 'stat pjdfstest_71683b1760c307c43fdaa3b45b80884e mode', 
expected 0777, got 04777
ok 5
ok 6
not ok 7 - tried '-u 65534 -g 65534 open pjdfstest_71683b1760c307c43fdaa3b45b80884e 
O_RDWR : write 0 x : fstat 0 mode', expected 0777, got 02777
not ok 8 - tried 'stat pjdfstest_71683b1760c307c43fdaa3b45b80884e mode', 
expected 0777, got 02777
ok 9
ok 10
not ok 11 - tried '-u 65534 -g 65534 open pjdfstest_71683b1760c307c43fdaa3b45b80884e 
O_RDWR : write 0 x : fstat 0 mode', expected 0777, got 06777
not ok 12 - tried 'stat pjdfstest_71683b1760c307c43fdaa3b45b80884e mode', 
expected 0777, got 06777
ok 13
ok 14
Failed 6/14 subtests
```

### Describe how to reproduce the problem

This is due to a conditional to drop suid/sgid in `zfs_write()`.
ZoL does this as it doesn't use a generic file write for fops.

In below, `secpolicy_vnode_setid_retain(...) != 0` is always false, because it just returns 0, and as a result the test fails.
Isn't this supposed to be testing `secpolicy_vnode_setid_retain(...) == 0` ?
Why test for if suid/sgid are to be retained when it wants to drop them, assuming non-zero return value means to retain.

If this is a bug, I'll create a PR.

```
 897                 if ((zp->z_mode & (S_IXUSR | (S_IXUSR >> 3) |
 898                     (S_IXUSR >> 6))) != 0 &&
 899                     (zp->z_mode & (S_ISUID | S_ISGID)) != 0 &&
 900                     secpolicy_vnode_setid_retain(cr,
 901                     ((zp->z_mode & S_ISUID) != 0 && uid == 0)) != 0) {
 902                         uint64_t newmode;
 903                         zp->z_mode &= ~(S_ISUID | S_ISGID);
 904                         ip->i_mode = newmode = zp->z_mode;
 905                         (void) sa_update(zp->z_sa_hdl, SA_ZPL_MODE(zfsvfs),
 906                             (void *)&newmode, sizeof (uint64_t), tx);
 907                 }
```

**Comment by behlendorf** [comment]
It's a bug, but I don't believe the conditional you referenced in `zfs_write()` wrong.  Instead the `secpolicy_vnode_setid_retain()` function needs to be performing the same check as the kernel to determine if the suid/guid can be retained.  We'd relied on the VFS for this previously as mentioned in the comment.

**Comment by kusumi** [comment]
> It's a bug, but I don't believe the conditional you referenced in zfs_write() wrong. Instead the secpolicy_vnode_setid_retain() function needs to be performing

ok, looking at `secpolicy_vnode_setid_retain()` in FreeBSD, it looks like return value of 0 means to retain, rather than non-zero for retain.

**Comment by behlendorf** [comment]
> it looks like all it needs here is to test priv_policy_user(cr, CAP_FSETID, B_FALSE, EPERM) ?

Yes, I believe so.
