### ISSUE TITLE
Wiki: inconsistent build dependencies for Debian/Ubuntu packages

### ISSUE THREAD

**Issue by riyad** [zfsonlinux/zfs#9036]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu
Distribution Version	| 19.04 (disco)
Linux Kernel	| 5.0.0-20-generic
Architecture	| amd64
ZFS Version	| 0.8.1
SPL Version	| -

### Describe the problem you're observing

I was trying to build the newest (0.8.1) release on Ubuntu 19.04 (disco).
I started using the guide on the [Debian Buster Encrypted Root on ZFS](https://github.com/zfsonlinux/zfs/wiki/Debian-Buster-Encrypted-Root-on-ZFS#step-1-prepare-the-install-environment) wiki page (but replacing the [Debian package source](https://salsa.debian.org/zfsonlinux-team/zfs/tree/experimental/debian) with [Ubuntu's](https://git.launchpad.net/ubuntu/+source/zfs-linux/log/?h=applied/ubuntu/eoan)).

After adding some missing dependencies (see below) building works fine, but when comparing it to the [Building ZFS](https://github.com/zfsonlinux/zfs/wiki/Building-ZFS) wiki page you begin to wonder.

[Debian Buster Encrypted Root on ZFS](https://github.com/zfsonlinux/zfs/wiki/Debian-Buster-Encrypted-Root-on-ZFS#step-1-prepare-the-install-environment) list `libattr1-dev libblkid-dev libselinux1-dev libssl-dev python3-cffi python3-setuptools python3-sphinx python3-all-dev uuid-dev zlib1g-dev` as build dependencies (probably extracted from the [`debian/control`](https://git.launchpad.net/ubuntu/+source/zfs-linux/tree/debian/control?h=applied/ubuntu/eoan#n10) file).
But if you look at [Building ZFS](https://github.com/zfsonlinux/zfs/wiki/Building-ZFS) it **additionally** lists `libacl1-dev libudev-dev libaio-dev libdevmapper-dev libelf-dev`.

Observations:
* [Debian Buster Encrypted Root on ZFS](https://github.com/zfsonlinux/zfs/wiki/Debian-Buster-Encrypted-Root-on-ZFS#step-1-prepare-the-install-environment) needs to add `dkms` and `debhelper-compat` as dependencies
* although `libudev-dev` was listed as a **required** dependency in [an older version of the "Building ZFS" wiki page](https://github.com/zfsonlinux/zfs/wiki/Building-ZFS/_compare/ba11d850a4a5c5e057dd65202432c52781162854#diff-9d6ffababce8598910e666b4422931b2L13) the packages build without it. o.O
* installing `libudev-dev` and `libaio-dev` definitely alter the packages, but they are not listed  dependencies (not even as "optional")
* installing `libacl1-dev libdevmapper-dev libelf-dev` make no difference at all, but they're still listed as dependencies (`libdevmapper-dev` transitively depends on `libudev-dev`, but installing `libudev-dev` without `libdevmapper-dev` produces no change to the packages)

Questions:
* Am I missing something with regard to the Debian/Ubuntu packages? 
* Does [Building ZFS](https://github.com/zfsonlinux/zfs/wiki/Building-ZFS) list outdated dependencies? ... should they be weeded? ... or marked "optional"?
* Are Debian/Ubuntu missing "vital" (they don't seem to be "required" AFAIK)
 dependencies?

Note 1: I compared all the build artifacts of different builds/build configurations with [diffoscope](https://diffoscope.org/). Which in turn suggest that ZFS packages build reproducibly. :grinning: 
Note 2: I've not installed and run the built packages. All the above is conjecture based on *building*  the packages. :sweat_smile:

**Comment by Veriln** [comment]
Additionally in [Debian Buster Encrypted Root on ZFS](https://github.com/zfsonlinux/zfs/wiki/Debian-Buster-Encrypted-Root-on-ZFS#step-4-system-configuration), the list of packages to be installed within the chroot in section 4.6 is insufficient(?)

```
make[1]: Entering directory '/root/zfs'
dh_installinit -R --name zfs-import
dh_installinit: --name=zfs-import option specified, but init script not found
make[1]: *** [debian/rules:170: override_dh_installinit] Error 255
make[1]: Leaving directory '/root/zfs'
make: *** [debian/rules:34: binary] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -i -I failed
gbp:error: 'debuild -i -I -uc -us' failed: it exited with 29
```

Have you reproduced this @riyad ?

**Comment by riyad** [comment]
Interesting ... I didn't realize there're virtually the same instructions in section 1.5 and 4.6.

Observations:
* Section 4.6 has `dkms` in the list of dependencies while section 1.5 has not.
* Section 1.5 wants `linux-headers-$(uname -r)` specifically while section 4.6 is happy with the more generic `linux-headers-amd64` (= `linux-headers-generic` in Ubuntu)).

@Veriln I'm not seeing your error. Neither on Ubuntu nor on Debian (buster).

**Comment by riyad** [comment]
Another observation:
* `libaio-dev` seems to be only relevant for `zfs-test`

**Comment by behlendorf** [comment]
> Does Building ZFS list outdated dependencies? ... should they be weeded? ... or marked "optional"?

Thanks for taking a close look at this.  Let me see if I can shed some light on these dependencies.  The following pertains to the 0.8.1.  We should make sure to update our documentation accordingly.

* __libblkid-dev__ - Required by `zpool import` to consult the blkid to local ZFS member devices.
* __libuuid-dev__ - Required by internal `libefi` convenience library and the `zed` daemon.
* __libudev-dev__ - Required by the `zed` to detect when a device has been removed.
*  __libssl-dev__ - Required for the encryption feature.
* __zlib1g-dev__ - Required for gzip compression feature.
* __libelf-dev__ - Required by kernel as of linux-4.14, see the discussion [here](https://patchwork.kernel.org/patch/10059179/).  It should be pulled in by the kernel dev packages.
* __libaio-dev__ - Required by the test suite to test libaio support.

The following library are optional but will result in some supporting being disabled:

* __python3-cffi python3-setuptools python3-sphinx python3-all-dev__ - Required to build `pyzfs` support

The following should no longer be needed and can be pruned.

* __libattr1-dev__ - Used to be required by xattr test cases,
* __libselinux1-dev__ - Used to be required to manage selinux contexts
*  __libdevmapper-dev__ - Used to be required by `zpool` command.
*  __libacl1-dev__ - This appears to have never been needed.

**Comment by riyad** [comment]
Thanks @behlendorf for the detailed explanation. :grinning:

Regarding `libelf-dev` I tried a few things, but I still can't find what it's being used for. 
* Packages build and install without it being present (and kernel dev packages don't seem depend on it either).
  * it doesn't contain much: https://packages.debian.org/buster/amd64/libelf-dev/filelist
* `ldd * | grep elf` on (hopefully) all binaries and `*.so`s turns up empty.

Although `libattr1-dev` is not required any more:
* it's listed as a build dependency for the [Debian](https://salsa.debian.org/zfsonlinux-team/zfs/blob/master/debian/control#L12) and [Ubuntu](https://git.launchpad.net/ubuntu/+source/zfs-linux/tree/debian/control?h=ubuntu/eoan#n13) packages

**Comment by riyad** [comment]
FYI: I've also opened an issue for the [Ubuntu zfs-linux source package](https://bugs.launchpad.net/ubuntu/+source/zfs-linux/+bug/1837544).

**Comment by cdluminate** [comment]
@riyad Ubuntu pulls package from Debian and do increamental update upon it. If you report a bug to Debian, the problem will be fixed in two distributions instead of one. I've fixed it in git: https://salsa.debian.org/zfsonlinux-team/zfs/commit/9f1838e79b72e151b9c90751c384e8c3708db870

**Comment by riyad** [comment]
@cdluminate Thank you. I'll try to keep that in mind for the future.

**Comment by typoworx-de** [comment]
Can confirm this issue as trying to build recent zfs dkms/spl modules for ubuntu 16 / xenial linux dist having the issue.
```
configure: error: in `/root/packages/zfs':
configure: error: 
	*** uuid/uuid.h missing, libuuid-devel package required
```

-->  apt-get install uid-dev

**Comment by rlaager** [comment]
There are quite a few things going on here. Let me see if I can untangle them.

The Encrypted HOWTO is gone at this point. At the time, it was having the user build a backport themselves. That's why it was necessary to install a bunch of dependencies. But now the Buster HOWTO uses buster-backports, so that moots a fair bit of this.

`debhelper-compat` is not a real package; it's a virtual package. So you don't install it.

> installing libudev-dev and libaio-dev definitely alter the packages, but they are not listed dependencies (not even as "optional")
> installing libacl1-dev libdevmapper-dev libelf-dev make no difference at all, but they're still listed as dependencies (libdevmapper-dev transitively depends on libudev-dev, but installing libudev-dev without libdevmapper-dev produces no change to the packages)

I can't speak to these, but it seems those have been addressed in Debian and Ubuntu already by @cdluminate.

I've broken out the Building-ZFS update into #9722 to decouple it from this Debian HOWTO stuff.
