### ISSUE TITLE
zed crashes when devid not present

### ISSUE THREAD

**Issue by ahrens** [zfsonlinux/zfs#9054]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu
Distribution Version	| 18.04
Linux Kernel	| 4.15
Architecture	| x86_64
ZFS Version	| master

### Describe the problem you're observing

`zed` core dumps due to a NULL pointer in `zfs_agent_iter_vdev()`.  The `gs_devid` is NULL, but the `nvl` has a `"devid"` entry.

It looks like the problem is that `zfs_agent_post_event()` checks that `ZFS_EV_VDEV_GUID` or `DEV_IDENTIFIER` is present in `nvl`, but then later it / `zfs_agent_iter_vdev()` assumes that `DEV_IDENTIFIER` is present.

### Describe how to reproduce the problem

Typically this is not a problem because usually either all vdevs have devid's, or none of them do.  Since `zfs_agent_iter_vdev()` first checks if the vdev has devid before dereferencing `gs_devid`, the problem isn't typically encountered.  However, if some vdevs have devid's and some do not, then the problem is easily reproduced.

The fix might be for `zfs_agent_iter_vdev()` to only try to match the devid's if both `nvl` and `gsp` have devid's present.  At least, that will make the crash go away, but I'm not familiar enough with the `zed` code if there are more problems with this situation.

### Include any warning/errors/backtraces from the system logs

```
Core was generated by `/usr/sbin/zed -F'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __strcmp_ssse3 () at ../sysdeps/x86_64/multiarch/../strcmp.S:173
173	../sysdeps/x86_64/multiarch/../strcmp.S: No such file or directory.
---Type <return> to continue, or q <return> to quit---
[Current thread is 1 (Thread 0x7f423285e700 (LWP 3170))]
(gdb) bt
#0  __strcmp_ssse3 () at ../sysdeps/x86_64/multiarch/../strcmp.S:173
#1  0x0000560533180047 in zfs_agent_iter_vdev (zhp=zhp@entry=0x7f422c020a60, nvl=0x7f422c00cf90,
    arg=arg@entry=0x7f423285bd70) at agents/zfs_agents.c:120
#2  0x000056053317ff76 in zfs_agent_iter_vdev (zhp=zhp@entry=0x7f422c020a60, nvl=0x7f422c00d968,
    arg=arg@entry=0x7f423285bd70) at agents/zfs_agents.c:89
#3  0x000056053318018f in zfs_agent_iter_pool (zhp=0x7f422c020a60, arg=0x7f423285bd70) at agents/zfs_agents.c:143
#4  0x00007f423558d5fd in zpool_iter (hdl=0x560533cbf470, func=func@entry=0x5605331800f0 <zfs_agent_iter_pool>,
    data=data@entry=0x7f423285bd70) at libzfs_config.c:419
#5  0x00005605331806a4 in zfs_agent_post_event (class=0x5605331874d7 "resource.fs.zfs.removed",
    class@entry=0x5605331869f6 "EC_dev_remove", subclass=0x560533186e74 "", subclass@entry=0x560533187adf "disk",
    nvl=nvl@entry=0x7f422c007180) at agents/zfs_agents.c:213
#6  0x000056053317c524 in zed_udev_event (class=class@entry=0x5605331869f6 "EC_dev_remove",
    subclass=subclass@entry=0x560533187adf "disk", nvl=nvl@entry=0x7f422c007180) at zed_disk_event.c:84
#7  0x000056053317c8b5 in zed_udev_monitor (arg=0x560533cc36d0) at zed_disk_event.c:342
#8  0x00007f4234d366db in start_thread (arg=0x7f423285e700) at pthread_create.c:463
#9  0x00007f4234a5f88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by ahrens** [comment]
cc: @loli10K it looks like some of this code may have been changed by d48091de81e5eab2aa32d7a52db4f147bd813523, although I'm not sure that it actually changed the behavior in question.  In any case if you have ideas on the proper fix I would appreciate it!

**Comment by loli10K** [comment]
This analysis looks correct but i am not sure how to reproduce and test this (plug/remove disk without devid) to verify the proposed fix.

**Comment by ahrens** [comment]
I can test it and open a PR, thanks for the confirmation @loli10K .
