### ISSUE TITLE
Wiki: ZFS root on Debian Buster

### ISSUE THREAD

**Issue by HankB** [zfsonlinux/zfs#9063]
Attn @rlaager

WRT: https://github.com/zfsonlinux/zfs/wiki/Debian-Buster-Root-on-ZFS

### System information

Debian | Buster
 --- | --- 
Debian	| 
Buster	| 
4.19	| 
AMD64	| 
7.12	| 
7.12	| 

### Describe the problem you're observing

1st documentation issue
Instructions point to https://cdimage.debian.org/cdimage/weekly-live-builds/amd64/iso-hybrid/ for the live image. Should this be https://cdimage.debian.org/mirror/cdimage/release/current-live/amd64/iso-hybrid/ instead?

2nd issue
Instructions call to install an older version of gcc
```
apt install --yes gcc=4:7.1.0-2 
```
This seems to not be available. I find
```
root@debian:/home/user# apt-cache policy gcc-7
gcc-7:
  Installed: 7.4.0-6
  Candidate: 7.4.0-6
  Version table:
 *** 7.4.0-6 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
root@debian:/home/user# exit
```
I've tried replacing the install with 
```
apt install --yes gcc-7 debootstrap gdisk dpkg-dev linux-headers-$(uname -r)
```
to see if that works. Unfortunately I have had unrelated problems testing this (in a VM) with frequent problems fetching files from the Internet. I did one time make it as far as typing in the root password (and misstyped it. :( ) but at that point the install is substantially complete. At least the ZFS modules have loaded in the host and built in the chroot.

Is there a better solution to the gcc install version?

**Comment by rlaager** [comment]
Thanks for the feedback and the updated URL for the released buster images. I haven't had a chance to test everything fully, but I made changes that should fix this. The GCC thing was a temporary issue related to a pre-release transition in buster.
