### ISSUE TITLE
Build error with kernel 5.1

### ISSUE THREAD

**Issue by Rudd-O** [zfsonlinux/zfs#9071]
I'm attaching the build log here.  Latest master.
[make.log](https://github.com/zfsonlinux/zfs/files/3414877/make.log)

**Comment by kusumi** [comment]
Your kernel's `include/linux/random.h` (not `/usr/include/linux/random.h`) is missing torvalds/linux@7e756f423af808b6571fed3144747db2ef7fa1c5.

**Comment by Rudd-O** [comment]
OH!  I see.  Will talk to my distributor.

**Comment by Rudd-O** [comment]
https://github.com/QubesOS/qubes-issues/issues/5185
