### ISSUE TITLE
zed.d Slack notifier

### ISSUE THREAD

**Issue by dan1elhughes** [zfsonlinux/zfs#9076]
👋 Hey, I'm loving ZFS and would like to contribute if appropriate.

I can see there's a Pushbullet notification function already set up in `zfs/cmd/zed/zed.d/`, alongside the email one. I would like to use Slack instead, and I expect other users may too. I intend to essentially imitate the Pushbullet functionality for Slack, with the following rough steps:

- Duplicate the `ZED_PUSHBULLET_{ACCESS_TOKEN/CHANNEL_TAG}` config items in `zed.rc`
- Duplicate the [zed_notify_pushbullet function](https://github.com/zfsonlinux/zfs/blob/master/cmd/zed/zed.d/zed-functions.sh#L304-L359) and tweak it for Slack
- Add the Slack notifier to the [generic notify function](https://github.com/zfsonlinux/zfs/blob/master/cmd/zed/zed.d/zed-functions.sh#L190-L208)

Is this the right approach? Any pointers would be very appreciated.

Cheers! 👍 

---

Edit: Just to be clear, I'm offering to build this and not asking for this to be built. Just want to know if it's worth putting effort into first.😸

**Comment by behlendorf** [comment]
Thanks!  I'm sure others would also find Slack integration useful, and contributions are welcome.  I'm not familiar with Slack APIs but if possible I think modeling this functionality after what was done for pushbullet would be the right way to handle this.

**Comment by dan1elhughes** [comment]
OK great, I'll have a go at it and see how I get on. Ta!

**Comment by markwkjr** [comment]
Updated `zed_notify_slack_webhook()` in `zed-functions.sh` to use a code block for the body so that the messages comes in fixed width font to increase readability and better mirror console.

```
<     msg_json="$(printf '{"text": "*%s*\\n```\\n%s\\n```"}' "${subject}" "${msg_body}" )"
---
>     msg_json="$(printf '{"text": "*%s*\\n%s"}' "${subject}" "${msg_body}" )"
```
