### ISSUE TITLE
Debian Buster Encrypted Root on ZFS page missing psmisc

### ISSUE THREAD

**Issue by nipsy** [zfsonlinux/zfs#9077]
Thanks for the wonderful documentation at [Debian Buster Encrypted Root on ZFS](https://github.com/zfsonlinux/zfs/wiki/Debian-Buster-Encrypted-Root-on-ZFS).  I noticed that later in the documentation a killall command is used, but at no point previously do any of the apt invocations include the psmisc package.  I thought someone could add it to avoid confusion for some folks.

As requested, I'm mentioning @rlaager to possibly expedite this.

**Comment by rlaager** [comment]
Thanks for the suggestion.

I don't recall manually installing `psmisc`. But I made a change to eliminate the use of `killall` anyway:

```
     Stop zed:
-    # killall zed
+    # fg
+    Press Ctrl-C.
```
