### ISSUE TITLE
Operation not permitted when enabling zfs_qat_compress_disable parameter on zfs 0.8-release

### ISSUE THREAD

**Issue by Jingpei-Yang** [zfsonlinux/zfs#9106]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Ubuntu
Distribution Version	|  16.04.5
Linux Kernel	|  4.13.0-36-generic
Architecture	|  Intel(R) Xeon(R) Gold 6152 CPU
ZFS Version	|   0.8.1-1
SPL Version	|   0.8.1-1

### Describe the problem you're observing
Trying to enable qat related parameters on zfs, and got permission error. I'm on root access, and have no problem changing other non-qat related parameters.

====
 echo 0 > /sys/module/zfs/parameters/zfs_qat_compress_disable
-bash: echo: write error: Operation not permitted

echo 0 > /sys/module/zfs/parameters/zfs_qat_checksum_disable
-bash: echo: write error: Operation not permitted

echo 0 > /sys/module/zfs/parameters/zfs_qat_encrypt_disable
-bash: echo: write error: Operation not permitted

I do not have problem with changing other parameters: 

$ cat /sys/module/zfs/parameters/zfs_flags
0
$  echo 1 >  /sys/module/zfs/parameters/zfs_flags
$  cat /sys/module/zfs/parameters/zfs_flags
1
Please help on this issue. 
### Describe how to reproduce the problem

echo 0 > /sys/module/zfs/parameters/zfs_qat_encrypt_disable

**Comment by ahrens** [comment]
These module parameters are created mode 0644.  I strongly suspect that the parameters do not exist on your machine, because your zfs kernel module was compiled without QAT support.  You can check if these files exist.  If they don't, you're effectively doing the same thing as
```
root@localhost:~# echo 0 > /sys/module/zfs/parameters/asdfasdf
bash: /sys/module/zfs/parameters/asdfasdf: Permission denied
````

**Comment by Jingpei-Yang** [comment]
Hi @ahrens  I do have these files on my system. 

$ ll /sys/module/zfs/parameters/zfs_qat_*
-rw-r--r-- 1 root root 4096 Jul 31 11:00 /sys/module/zfs/parameters/zfs_qat_checksum_disable
-rw-r--r-- 1 root root 4096 Jul 31 10:53 /sys/module/zfs/parameters/zfs_qat_compress_disable
-rw-r--r-- 1 root root 4096 Jul 31 11:00 /sys/module/zfs/parameters/zfs_qat_encrypt_disable

I compiled zfs with QAT support:
$ ./configure --with-qat=<my_QAT_driver_path>

**Comment by ahrens** [comment]
Ah, I see.  These module parameters are special cases.  It looks like you can get this if `qat_dc_init()` fails.  Maybe someone more familiar with QAT can diagnose why that's happening.

```
static int
param_set_qat_compress(const char *val, struct kernel_param *kp)
{
	int ret;
	int *pvalue = kp->arg;
	ret = param_set_int(val, kp);
	if (ret)
		return (ret);
	/*
	 * zfs_qat_compress_disable = 0: enable qat compress
	 * try to initialize qat instance if it has not been done
	 */
	if (*pvalue == 0 && !qat_dc_init_done) {
		ret = qat_dc_init(); // <======== this has failed
		if (ret != 0) {
			zfs_qat_compress_disable = 1;
			return (ret);
		}
	}
	return (ret);
}

module_param_call(zfs_qat_compress_disable, param_set_qat_compress,
    param_get_int, &zfs_qat_compress_disable, 0644);
```

**Comment by Jingpei-Yang** [comment]
Does zfs-0.8 support the latest QAT C62x Chipset? Or it only works on the older 8950 adpater?

**Comment by behlendorf** [comment]
Yes, it should.  @wli5 added support for the C62x Chipset by commit 1cfdb0e6e401087778712fa893777b064a8afb6b.  Perhaps he can help diagnosis this.

**Comment by cfzhu** [comment]
@Jingpei-Yang  Hi Jingpei, could you provide  more information?  For example, the QAT configuration.

**Comment by Jingpei-Yang** [comment]
Recompiled QAT with kernel space enabled, now it works. Thank you!
