### ISSUE TITLE
Recursive deleting of snapshots hangs kernel 

### ISSUE THREAD

**Issue by vincentkersten** [zfsonlinux/zfs#9114]
Dear ZFS maintainers,
Thans you for your great work on bringing ZFS to linux!
For a while i have puzzling on the following (admittedly edge-case) bug:

### System information

Distribution Name	|  Debian |
Distribution Version	|  Stretch |
Linux Kernel	|  4.9.168-1+deb9u4 (2019-07-19) |
Architecture	|  64 bit |
ZFS Version	|  ZFS: Loaded module v0.7.12-2+deb10u1~bpo9+1, ZFS pool version 5000, ZFS filesystem version 5 |
SPL Version	|  0.7.12-2~bpo9+1 |

### Describe the problem you're observing
Recursive deleting snapshots results in kernel panic (spinlock), when the starting point of the recursive snapshot does not exist, on the second day. 

### Describe how to reproduce the problem
I do a daily snapshot (recursive) with cron of all volumes, but I skip two days:
zfs snapshot -r tank@$(date -I)

Also I daily do a recursive deletion of old snapshots older then 9 days. 
zfs destroy -r "tank@%$( date --date "9 days ago" -I )"

So, every seven days I hit a 'gap' of two days. The first days all is well. But, the second 'gap' day (that is, the second day without the dated snaphot), I run into a kernel panic. 

Example: 
Snapshots in .zfs/snapshots:

2019-01-01
2019-01-02 
2019-01-03 
2019-01-04 
... 'gap' days ...
2019-01-07 
2019-01-08 
2019-01-09
2019-01-10 

Now i start to delete recursive on 2019-01-05; Process yields no errors, but older snapshots (> 9 days) are not deleted. 

Then, when i start recursive deleting the next day, on 2019-01-06, I get a kernel panic. 

### solution
The solution is to create a snaphot every day, then the error does not occur. 

Makes me think there is some edge-case error in the recursive deleting when missing the snapshot with the date?

### Include any warning/errors/backtraces from the system logs
![Screenshot 2019-06-20 at 08 27 51](https://user-images.githubusercontent.com/5429401/62365391-44d87f80-b524-11e9-88e2-66993ba3bed9.png)

**Comment by dweeezil** [comment]
@vincentkersten This lock-up is the result of the "ps" command opening a file in a "procfs" (i.e. "/proc") file system.  A bit of looking around the internet shows a few other similar problem reports on Debian kernels but no actual resolution.  This issue does not seem to be directly related to ZFS, but it certainly may be exacerbated by all the task creating/destroying operations that ZoL is likely to do.

This issue _may_ have been fixed in 4.19 via torvalds/linux@41089b6d3e44a895076cc8ce56b08e463cb4f796.

**Comment by vincentkersten** [comment]
@dweeezil : Thank you for looking into this. I am interested in what type of issues with ps/procps and Debian kernels you actually found. It does however, not really explain why it
- hangs on the second 'gap' day (and not the first)
- it works when there is no 'gap'

However, since it could well be an edge-case i mostly wrote this for others to run into though :) and to see if you might encounter something in the recursive deletion code. Thanks again, Vincent

**Comment by vincentkersten** [comment]
ok, i again had this issue... unfortunately. So what happens is that i do a scrub once a week, and a few hours later, reversely delete snapshots (daily). Every second time the scrub finishes, and the reverse deleting starts, i get the above kernel hang. 
@dweeezil I would love to get more info on the issue you pointed at. 
Also I wonder if it makes sense to drop all caches  (/usr/bin/echo 3 > /proc/sys/vm/drop_caches) after i did a scrub.

**Comment by vincentkersten** [comment]
After some more analysis this seems to be related to nfs kernel server , sharing zfs vols. Need to use kernel server because of #6851 . Snapshots get deleted while users are still in the snapshot paths on clients.
