### ISSUE TITLE
Wiki: ZFS root on Debian Buster

### ISSUE THREAD

**Issue by HankB** [zfsonlinux/zfs#9117]
Problem with instructions, seemingly due to renaming of `shim` package.
Instructions at https://github.com/zfsonlinux/zfs/wiki/Debian-Buster-Root-on-ZFS
Attn: @rlaager

### System information
Type | Version/Name
 --- | --- 
Distribution Name	| Debian
Distribution Version	| Buster
Linux Kernel	| 4.19.0-5-amd64
Architecture	| x86_64
ZFS Version	| 0.7.12-2+deb10u1
SPL Version	| 0.7.12-2

### Describe the problem you're observing
Section 4.8b Install GRUB for UEFI booting
Command
```
apt install --yes grub-efi-amd64 shim
```
reports
```
Package shim is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  shim-helpers-amd64-signed shim-unsigned

E: Package 'shim' has no installation candidate
``` 
### Describe how to reproduce the problem
Follow instructions in the wiiki (and as scripted at 
https://github.com/HankB/Linux_ZFS_Root/blob/master/Debian/install_Debian_to_ZFS_root.sh )

Replacing `shim` with the suggested `shim-helpers-amd64-signed shim-unsigned`
works and the installation completes successfully.

### Include any warning/errors/backtraces from the system logs
unknown. Warning to terminal listed above.

**Comment by rlaager** [comment]
Thanks for letting me know.

I think we want `shim-signed` here. That's the version signed by the Microsoft CA so it is trusted by common stock UEFI firmwares. That depends on the helper package for the appropriate architecture.

I've made that change.
