### ISSUE TITLE
Kernel API autotools checks are slow

### ISSUE THREAD

**Issue by ryao** [zfsonlinux/zfs#9132]
Our Kernel API autotools checks invoke the kernel’s build system to build a kernel module as part of each check. I noticed that the Nvidia kernel driver also uses autotools and has a similar number of checks, but is much faster. It appears that Nvidia is invoking the compiler directly to speed up the process and that works for them. I imagine that might not work quite so well for testing for GPL symbol exports, but that technique likely could be adapted for the majority of our autotools checks to make things faster.

Speeding up the build system has always been a low priority for me, but I was recently troubleshooting what I thought to be a kernel bug that turned out to be the result of failing hardware causing miscompilation. While trying to figure it out, I had to sit through around a dozen full kernel and initramfs rebuilds for an entire day. At least an hour of that time seems to have been spent on autotools and after that experience, the build system performance suddenly feels like a higher priority to me. It is not high enough for me to do something right away, but it is high enough to have my attention. I am posting it here in case anyone wants to try to tackle this before I do. I am also self assigning it as a note to myself.

**Comment by perfinion** [comment]
another thing that would help i think is re-ordering some of the checks. a lot of the checks appear to be oldest kernel first with newest kernels at the end. which means the list gets longer and longer over time and it spends a lot of time "testing foo() with 2 params ... no", "testing foo with 3 params ... no", "with 4 params .. no", "with 5 ... yes". if we started with 5 then for most people things would probably be a lot faster just because there would be a lot less checks.

**Comment by c0d3z3r0** [comment]
#8547

**Comment by c0d3z3r0** [comment]
The time doubles by redundant calls of `./configure` as described in #9135

**Comment by DeHackEd** [comment]
It would be a pretty major redesign, but if several files could be built at once it could be sped up significantly. Calling into the Kbuild system is expensive, and calling it once (or more!) for each test is what's killing it.

Being able to just make a single Makefile with all (most?) tests with a single `make -k` and collect the resulting mess after the fact could make it incredibly fast, but a management nightmare.

**Comment by behlendorf** [comment]
> It appears that Nvidia is invoking the compiler directly to speed up the process and that works for them.

I think this is worth investigating since if it can be made it work we can hopefully avoid the need to make extensive (highly error prone) changes to the existing checks.
