### ISSUE TITLE
dsl_livelist_should_disable() has no prototype

### ISSUE THREAD

**Issue by allanjude** [zfsonlinux/zfs#9152]
# System information

Type | Version/Name
 --- | --- 
Distribution Name	| FreeBSD
Distribution Version	| 13.0
Linux Kernel	| N/A
Architecture	| amd64
ZFS Version	| master
SPL Version	| master

### Describe the problem you're observing
ZFS fails to compile with clang 8.0.1

### Describe how to reproduce the problem
Compile ZFS with warnings-as-errors (default) using clang

### Include any warning/errors/backtraces from the system logs
Compiler warning:
```error: no previous prototype for function 'dsl_livelist_should_disable' [-Werror,-Wmissing-prototypes]```

My question is, should I open a PR to:
A) Mark the function as static
B) Add a prototype for the function

**Comment by sdimitro** [comment]
From what I can tell the function is not used anywhere else, so I'd suggest to make it `static`.
@shartse can advise better on this

**Comment by shartse** [comment]
Yeah, if you could open a PR to mark it static that'd be great.
