### ISSUE TITLE
90 seconds delay during boot

### ISSUE THREAD

**Issue by kroeckx** [zfsonlinux/zfs#9160]
### System information
Type | Version/Name
 --- | --- 
Distribution Name	| Debian
Distribution Version	| buster / 10.0
Linux Kernel	| 4.19.37-5
Architecture	| amd64
ZFS Version	| 0.7.12-2+deb10u1
SPL Version	| 0.7.12-2

I did a install on putting ZFS on the root FS following https://github.com/zfsonlinux/zfs/wiki/Debian-Buster-Root-on-ZFS

### Describe the problem you're observing

During boot it hangs for 90 seconds, and the continues normally.

### Include any warning/errors/backtraces from the system logs

dmesg shows this during boot:
```
[    3.305653]  sdc: sdc2 sdc3 sdc4
[    3.306631] sd 3:0:0:0: [sdc] Attached SCSI removable disk
[    3.307413]  sdb: sdb2 sdb3 sdb4
[    3.308191] sd 2:0:0:0: [sdb] Attached SCSI removable disk
[    3.309591]  sda: sda2 sda3 sda4
[    3.310341]  sdd: sdd2 sdd3 sdd4
[    3.310389] sd 1:0:0:0: [sda] Attached SCSI disk
[    3.310943] sd 4:0:0:0: [sdd] Attached SCSI removable disk
[   93.335257] spl: loading out-of-tree module taints kernel.
[   93.335472] spl: module verification failed: signature and/or required key missing - tainting kernel
[   93.342168] SPL: Loaded module v0.7.12-2
[   93.342754] znvpair: module license 'CDDL' taints kernel.
[   93.342772] Disabling lock debugging due to kernel taint
[   95.149981] ZFS: Loaded module v0.7.12-2+deb10u1, ZFS pool version 5000, ZFS filesystem version 5
[   98.837345] systemd[1]: Inserted module 'autofs4'
```

**Comment by mskarbek** [comment]
Try to analyze systemd boot log, those 90 seconds look suspiciously like a unit timeout. It may be that the ZFS target/service unit is blocked by something and waits.

**Comment by kroeckx** [comment]
What I found in the mean time in the logs was this:
```
systemd[1]: dev-disk-by\x2dpartuuid-54556355\x2d1930\x2d440d\x2dbe47\x2dbff335d8d80f.device: Job dev-disk-by\x2dpartuuid-54556355\x2d1930\x2d440d\x2dbe47\x2dbff3
systemd[1]: Timed out waiting for device /dev/disk/by-partuuid/54556355-1930-440d-be47-bff335d8d80f.
```

fstab contains:
```
PARTUUID=54556355-1930-440d-be47-bff335d8d80f  /boot/efi vfat nofail,x-systemd.device-timeout=1 0 1
```

And boot/efi does end up mounted.

**Comment by kroeckx** [comment]
Commenting that out didn't have any effect.

**Comment by johnnyjacq16** [comment]
run the following command to find out which service is taking the most time to start on bootup.
`systemd-analyze blame`

**Comment by kroeckx** [comment]
That produces:
```
          5.466s networking.service
          2.029s zfs-import-bpool.service
          2.026s ifupdown-pre.service
          2.021s systemd-udev-settle.service
          1.344s exim4.service
           526ms user@1000.service
           481ms apparmor.service
           444ms zfs-mount.service
           422ms systemd-udevd.service
           401ms var-spool.mount
           400ms var-log.mount
[...]
```

**Comment by kroeckx** [comment]
`systemd-analyze time` returns:
```
Startup finished in 27.863s (firmware) + 5.740s (loader) + 1min 38.517s (kernel) + 12.384s (userspace) = 2min 24.506s 
graphical.target reached after 12.342s in userspace
```

**Comment by devZer0** [comment]
any chance to replace the corresponding disk to see if that makes a difference (to make sure it's not related to the disk itself?)

i have seen plugging in a single disk making all other disks disappear from the same sas hba - so you never know.... ;)

**Comment by rlaager** [comment]
This is really bizarre. The delay is before the ZFS module is loaded, so it's not any sort of pool importing or filesystem mounting delay. Since this is a root-on-ZFS install, the module has to be loaded while you're still in the initramfs environment. As far as I know, that's before systemd starts. So I think you need to look at this from that point of view.

I forget the details of debug mode in initramfs. The Ubuntu wiki says, "you may want to also try booting with the debug boot option. It should write a log to /tmp/initramfs.debug. You could also specify some arbitrary argument (for example debug=vc) to have the output written to the console." -- https://wiki.ubuntu.com/DebuggingKernelBoot

**Comment by kroeckx** [comment]
So the boot today had this in it:
[    3.249856] sd 1:0:0:0: [sda] Attached SCSI disk
[   63.258688] systemd-udevd[101]: eth1: Worker [128] processing SEQNUM=1438 is taking a long time
[   93.193528] systemd-udevd[128]: eth1: Failed to rename network interface 3 from 'eth1' to 'eno1': File exists
[   93.205214] systemd-udevd[127]: Using default interface naming scheme 'v240'.
[   93.296175] spl: loading out-of-tree module taints kernel.

I assume it's not a zfs problem.

**Comment by gmelikov** [comment]
@kroeckx thank you for information, I'll close this issue.
