### ISSUE TITLE
Mounting ZVOL snapshot returns "unable to fetch ZFS version for filesystem"

### ISSUE THREAD

**Issue by thehaven** [zfsonlinux/zfs#9184]
# System information

Type | Version/Name
 --- | --- 
Distribution Name	| Gentoo
Distribution Version	|  17.1
Linux Kernel	| 5.2.0-pf3
Architecture	| x86_64
ZFS Version	| master
SPL Version	| master

### Describe the problem you're observing
I am attempting to mount an ext4 zvol snapshot but receiving an error due to no ZFS version being set on the filesystem.

I can see that none of the zvol's on my systems have versions, I have created new ones to validate that they also are not created with versions applied.

### Describe how to reproduce the problem
Attempting to mount a zvol snapshot (ext4 file system internally) gives the error:
```bash
saratoga /storage # mount -t zfs tank3/virtuals/webhost@autosnap_2019-08-20_02:00:02_hourly /mnt/temp
unable to fetch ZFS version for filesystem 'tank3/virtuals/webhost@autosnap_2019-08-20_02:00:02_hourly'
```
I can see that all ZVOL's have no version:
```bash
saratoga ~ # zfs get -r version tank3/virtuals/webhost | head -n 5
NAME                                                         PROPERTY  VALUE    SOURCE
tank3/virtuals/webhost                                       version   -        -
tank3/virtuals/webhost@migrate                               version   -        -
tank3/virtuals/webhost@autosnap_2019-06-16_16:02:32_monthly  version   -        -
tank3/virtuals/webhost@autosnap_2019-07-01_00:00:01_monthly  version   -        -
```

Attempting to set a version does not work:
```bash
saratoga ~ # zfs set version=5 tank3/virtuals/webhost
cannot set property for 'tank3/virtuals/webhost': 'version' does not apply to datasets of this type
```
Any help appreciated.

**Comment by AndCycle** [comment]
well, you can't direct mount the ZVOL snapshot

https://superuser.com/questions/1289848/how-to-access-a-zfs-zvol-snapshot-block-device

**Comment by thehaven** [comment]
Thanks, that works for me:

```bash
saratoga /storage # zfs clone tank3/virtuals/webhost@autosnap_2019-08-19_23:59:01_daily tank3/virtuals/webhost-temp
saratoga /storage # mount /dev/zvol/tank3/virtuals/webhost-temp /mnt/temp
saratoga /storage # df -hT /mnt/temp
Filesystem     Type  Size  Used Avail Use% Mounted on
/dev/zd176     ext4   79G   67G  7.9G  90% /mnt/temp
```

I'm happy to close this off as I have a working solution. One final thought is that the error message given is a bit misleading in this situation. Its possibly worth a zvol check and appropriate message when someone attempts to mount a zvol rather than:
```
unable to fetch ZFS version for filesystem
```
?

Many thanks for the help.

**Comment by AndCycle** [comment]
no, you have to get the idea, ZVOL is a block device, 

so your `mount -t zfs` command will lead mount command to mount it as ZFS, but you have ext4 inside it.

**Comment by thehaven** [comment]
Understood. Thanks for the clarification.
