### ISSUE TITLE
Speed up dkms build (configure step)

### ISSUE THREAD

**Issue by PotcFdk** [zfsonlinux/zfs#9213]
When building `zfs-dkms` [from the AUR](https://aur.archlinux.org/packages/zfs-dkms/), the `configure` step takes much longer than the actual compile phase.
I end up having to wait more than three times the compilation time for the configure part alone! This is pretty insane - and a waste of resources.
Is this a known issue, and do plans exist to revamp the build system accordingly (or is there any way to speed this up somehow)?

**Comment by edacval** [comment]
https://github.com/zfsonlinux/zfs/issues/8547 ?

**Comment by PotcFdk** [comment]
@edacval thanks, I had trouble finding that issue. I'll subscribe to that one instead.
