### ISSUE TITLE
allow for persistent l2arc

### ISSUE THREAD

**Issue by cwedgwood** [zfsonlinux/zfs#925]
https://groups.google.com/a/zfsonlinux.org/forum/?fromgroups=#!topic/zfs-discuss/eSYYLdx73r4

References request and a suggestion on how it might be done.

**Comment by grahamperrin** [comment]
From irc://chat.freenode.net/#illumos today: 

>  nexenta might have some kind of implementation for it, i think.

**Comment by kernelOfTruth** [comment]
https://github.com/Nexenta/illumos-nexenta/commit/f0a9ee9eeed31410aecb7bc0172cec615698aecd

https://github.com/Nexenta/illumos-nexenta/commit/887263262dff3397c305be7129b6fb394189de8e

https://github.com/Nexenta/illumos-nexenta/commit/9498bb1539167ca88ff9237851a2ac9047859a5a

**Comment by kerberizer** [comment]
illumos 3525 is now in [code review](https://reviews.csiden.org/r/267/).

**Comment by cwedgwood** [comment]
Updated progress at https://reviews.csiden.org/r/267/

**Comment by mailinglists35** [comment]
@behlendorf what does closing of this mean? it has been integrated/ported already? it will never be?

**Comment by behlendorf** [comment]
The intention was to pick up this work once it was finalized and merged for illumos.

**Comment by mailinglists35** [comment]
@behlendorf  could you mark it a duplicate of #3744, even if this is chronologicallty the oldest?
I had to read the other one to understand what's going on, as your reply was not really clearly explaining why it was closed.

**Comment by mailinglists35** [comment]
@behlendorf is this going to 0.8 series, or is it planned only for openzfs v2?

**Comment by behlendorf** [comment]
It's planned for OpenZFS 2.0.
