### ISSUE TITLE
Key load error: Failed to get encryption root for dataset

### ISSUE THREAD

**Issue by gusev-vitaliy** [zfsonlinux/zfs#9267]
### System information
Type | Version/Name
-- | --
Distribution Name | Fedora
Distribution Version | 30
Linux Kernel | 5.2.9-200.fc30
Architecture | x86_64
ZFS Version | 0.8.0-233_gc95396004
SPL Version | 0.8.0-233_gc95396004

### Describe the problem you're observing

After fixing zfsonlinux#6703 and #8976 dataset cannot be accessed due to lost encryptionroot. So that encrypted data also is lost. Output of run commands:

```
NAME       PROPERTY        VALUE        SOURCE
data/A2/B  encryption      aes-256-ccm  -
data/A2/B  encryptionroot  data/A       -

NAME       PROPERTY        VALUE        SOURCE
data/A2/B  encryption      aes-256-ccm  -
data/A2/B  encryptionroot  -            -

Key load error: Failed to get encryption root for 'data/A2/B'.
```

### Describe how to reproduce the problem
```bash
dd if=/dev/zero of=/var/tmp/disk0 bs=1M count=64

zpool create data /var/tmp/disk0
echo 'C74AE2525459' | zfs create -o encryption=on -o keyformat=passphrase data/A

zfs snapshot data/A@1
zfs clone data/A@1 data/A2
zfs create data/A2/B

zfs promote data/A2
zfs get -t all -r encryption,encryptionroot data/A2/B # encryptionroot should be 'data/A2', but is 'data/A'

zfs destroy data/A
zfs get -t all -r encryption,encryptionroot data/A2/B # no encryptionroot anymore

zpool export data
zpool import -d /var/tmp/ data

zfs load-key data/A2/B
```
### Include any warning/errors/backtraces from the system logs

**Comment by tcaputi** [comment]
@gusev-vitaliy Please confirm that #9294 fixes your issue when you get a chance.
