### ISSUE TITLE
zfs encrypted raw send with encryptionroot higher up fails to mount on receive pool

### ISSUE THREAD

**Issue by sandyxb** [zfsonlinux/zfs#9273]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  none
Distribution Version	|  none
Linux Kernel	|  4.19.39
Architecture	|  x86_64
ZFS Version	|  0.8.1-1 git 20190720
SPL Version       | 0.8.1-1 git 20190720

### Describe the problem you're observing
A dataset with an encryptionroot not the same as the dataset, when sent raw to another pool, cannot be mounted. 

### Describe how to reproduce the problem

A dataset pool1/a is created with encryption enabled.
```
host1# zfs create -o canmount=off -o encryption=aes-256-gcm -o keyformat=passphrase pool1/a
Enter passphrase: 
Re-enter passphrase:
```

A sub-dataset pool1/a/b is created below it, inheriting encryption.
pool1/a will become the ecnryptionroot for pool1/a/b .
```
host1# zfs create -o canmount=noauto pool1/a/b
```

The sub-dataset pool1/a/b is sent raw to a destination host (same zfs version), with the same dataset structure, ie pool2/a is the encryption root.
```
host2# zfs create -o canmount=off -o encryption=aes-256-gcm -o keyformat=passphrase pool2/a
Enter passphrase: 
Re-enter passphrase:
```

After sending (lots of data), the sending side fails with a mount error.
strace reveals the mount syscall fails with EACCESS. 
```
host1# zfs list -t all | grep 'pool1/a'
pool1/a                                           730K  23.1T      365K  /pool1/a
pool1/a/b                                         365K  23.1T      365K  /pool1/a/b
host1# zfs get encryption | grep 'pool1/a'
pool1/a                                          encryption  aes-256-gcm  -
pool1/a/b                                        encryption  aes-256-gcm  -
host1# zfs mount pool1/a/b
host1# touch /pool1/a/b/x
host1# zfs snapshot pool1/a/b@snap
host1# zfs send -RLw pool1/a/b@snap | ssh host2 zfs receive -Fd pool2
root@host2's password: 
filesystem 'pool2/a/b' can not be mounted: Permission denied
cannot mount 'pool2/a/b': Invalid argument
```

The send succeeded in replicating the snapshot to the destination host.
But there, it is also not mountable.
```
host2# zfs list -t all | grep 'pool2/a'
pool2/a                                           675K  39.4T      365K  /pool2/a
pool2/a/b                                         310K  39.4T      310K  /pool2/a/b
pool2/a/b@snap                                      0B      -      310K  -
host2# zfs get encryptionroot | grep 's1pool/a'
pool2/a                                 encryptionroot  pool2/a               -
pool2/a/b                                  encryptionroot  pool2/a               -
pool2/a/b@snap                            encryptionroot  pool2/a               -
host2# zfs mount pool2/a/b
filesystem 'pool2/a/b' can not be mounted: Permission denied
cannot mount 'pool2/a/b': Invalid argument
```

I can understand that this is not supported, as the key setup may differ, maybe even an IV problem. But shouldn't the receiving side complain earlier, not after gobs of data has been moved? 

Even if this is considered a valid replication method, there is the danger that if the pool2/a/b dataset is ever moved back to pool1, that the key setup has changed there too, and it would effectively become useless.

**Comment by tcaputi** [comment]
The issue here seems to be confusion about the meaning of the `destsnap` parameter passed into `recv_fix_encryption_hierarchy()`. This parameter is interpreted in this function as "the name of the snapshot that was created at the top level of the `zfs receive`". In reality, it is just directly what the user provided on the command line. In this case you used `zfs receive -d`, so the expected value was `pool2/a/b@snap` and the actual value passed in was just `pool2`. I should be able to figure out a fix for this on Monday

**Comment by tcaputi** [comment]
@sandyxb can you confirm if #9309 solves your issue?

**Comment by tcaputi** [comment]
A simple test case has been pushed.
