### ISSUE TITLE
Wiki: Encrypted ZFS Root on Debian Buster - Plymouth breaks grub

### ISSUE THREAD

**Issue by fidomuh** [zfsonlinux/zfs#9283]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Debian
Distribution Version	|  Buster
Linux Kernel	|  4.9.0.16
Architecture	| AMD64
ZFS Version	| 0.8.1-4
SPL Version	| 0.8.1-4

### Describe the problem you're observing

https://github.com/zfsonlinux/zfs/wiki/Debian-Buster-Encrypted-Root-on-ZFS

Followed your guide to encrypted root on Debian Buster, with native encryption.
Works like a charm, until the last steps where you advice to install the base system.
When install a displaymanager, lightdm for instance, it also installs plymouth.

This breaks grub so on boot you need to load the key manually, do the mounts manually and then exit initramfs.

### Describe how to reproduce the problem

apt-get install plymouth

### Include any warning/errors/backtraces from the system logs
```
Error cannot open ''rpool'' invalid character '''
```

**Comment by fidomuh** [comment]
Quick note: After install lightdm, gdm or whichever display manager is wanted, simply remove plymouth to fix the issue.
```
apt-get remove plymouth
```

**Comment by belperite** [comment]
Hi,

Please see #9202 .

**Comment by ghfields** [comment]
Since this is being reported regularly, I would like to see #9202 (and hopefully #9042) to added to the 0.8.2 proposed patchset.
