### ISSUE TITLE
Conflict zfs-0.8.0/include/sys/abd.h in two packages

### ISSUE THREAD

**Issue by IslandLife** [zfsonlinux/zfs#9292]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Ubuntu
Distribution Version	| Ubuntu 19.04 disco
Linux Kernel	| 5.0.0-25-generic
Architecture	| x86_64
ZFS Version	| 0.8.0-258_g870e7a52c
SPL Version	| -

### Describe how to reproduce the problem

```
# dpkg -i ./zfs/kmod-zfs-devel_0.8.0-258_amd64.deb
(Reading database ... 347895 files and directories currently installed.)
Preparing to unpack .../kmod-zfs-devel_0.8.0-258_amd64.deb ...
Unpacking kmod-zfs-devel (0.8.0-258) ...
dpkg: error processing archive ./zfs/kmod-zfs-devel_0.8.0-258_amd64.deb (--install):
 trying to overwrite '/usr/src/zfs-0.8.0/include/sys/abd.h', which is also in package zfs-dkms 0.8.0-258
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 ./zfs/kmod-zfs-devel_0.8.0-258_amd64.deb
```

**Comment by behlendorf** [comment]
@IslandLife this is as expected, the `kmod-zfs-devel` and `kmod-dkms` package will conflict with each other.  Only one should be installed at a time depending on if you prefer kmod or dkms sytle packages.  This is a specified in the RPM packaging, but the "Conflicts" line appears to be lost in the conversion using `alien`.
