### ISSUE TITLE
ZFS master @ 4bbf0477a7f8936627c37ab89c704e763aa63b37 fails to be built in

### ISSUE THREAD

**Issue by tsjk** [zfsonlinux/zfs#9297]
### System information
Distribution Name	| Gentoo
Distribution Version	| N/A
Linux Kernel	| 4.19.71
Architecture	| AMD64
ZFS Version	| master
SPL Version	| -

### Describe the problem you're observing

Can't seem to build zfs as built in. I think that makefile change might be a cause, but I haven't made a detailed analysis. However,
95f0144675dd0e18617355443be0fbc7171af76b works
4bbf0477a7f8936627c37ab89c704e763aa63b37 does not

```
make[3]: *** No rule to make target 'fs/zfs/spl/spl.o', needed by 'fs/zfs/spl/built-in.a'.  Stop.
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [scripts/Makefile.build:544: fs/zfs/spl] Error 2
make[1]: *** [scripts/Makefile.build:544: fs/zfs] Error 2
make: *** [Makefile:1046: fs] Error 2
make: *** Waiting for unfinished jobs....
```

**Comment by behlendorf** [comment]
Some refactoriing was done to the source tree.  Can you verify this is reproducible after re-running `sh autogen` in the source tree for commit 4bbf047.

**Comment by prometheanfire** [comment]
hmm, null pointer deref? https://photos.app.goo.gl/eAaV8fXuXXfcUqDE7

not sure if it's related, I'm building from master as well, but against 5.2.13

**Comment by tsjk** [comment]
Well, the Gentoo ebuild does an eautoreconf when preparing the source, which should prepare it. I exchanged that call for an ./autogen.sh, but that made no difference.

The procedure in Gentoo to build in is to prepare the source, run configure, and then run ./copy-builtin (https://wiki.gentoo.org/wiki/ZFS#Installing_into_the_kernel_directory_.28for_static_installs.29, https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-fs/zfs-kmod/zfs-kmod-9999.ebuild). I have used the same procedure for years I think.

**Comment by prometheanfire** [comment]
I've done the same procedure for years as well, here's what I do.

```bash
# after update + depclean
PREV_KVER=$(eselect kernel show | tail -n1 | cut -d'-' -f2)
eselect kernel set 1
KVER=$(eselect kernel show | tail -n1 | cut -d'-' -f2)
cd /usr/src/linux
zcat /proc/config.gz > .config

# zfs part starts here
make modules_prepare
env EXTRA_ECONF='--enable-linux-builtin' ebuild /usr/portage/sys-fs/zfs-kmod/zfs-kmod-9999.ebuild clean configure
(cd /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999 && ./copy-builtin /usr/src/linux)
yes | make oldconfig  # enables spl and zfs as builtin
env EXTRA_ECONF='--with-spl=/usr/src/linux --enable-linux-builtin' ebuild /usr/portage/sys-fs/zfs/zfs-9999.ebuild clean merge
# zfs part ends here

make -j$(nproc)
make modules_install
emerge --usepkg=n --ask n -v @module-rebuild
find /lib/modules/"${KVER}"-gentoo/ -iname *ko.xz -exec /usr/src/linux/scripts/sign-file sha512 /usr/src/linux/certs/signing_key.pem /usr/src/linux/certs/signing_key.x509 {} \;
find /lib/modules/"${KVER}"-gentoo/ -iname *ko -exec /usr/src/linux/scripts/sign-file sha512 /usr/src/linux/certs/signing_key.pem /usr/src/linux/certs/signing_key.x509 {} \;
mount /boot
cp arch/x86/boot/bzImage /boot/kernel-"${KVER}"-gentoo
sbsign --key /etc/efikeys/db.key --cert /etc/efikeys/db.crt /boot/kernel-"${KVER}"-gentoo
mv /boot/kernel-"${KVER}"-gentoo.signed /boot/kernel-"${KVER}"-gentoo
sbsign --key /etc/efikeys/db.key --cert /etc/efikeys/db.crt /usr/libexec/fwupd/efi/fwupdx64.efi  # might as well make sure we have a updated shim for fwupd
dracut --kver "${KVER}"-gentoo
cp /boot/loader/entries/gentoo-"${PREV_KVER}".conf /boot/loader/entries/gentoo-"${KVER}".conf
sed -i "s/${PREV_KVER}/${KVER}/g" /boot/loader/entries/gentoo-"${KVER}".conf
umount /boot
```

**Comment by behlendorf** [comment]
Fix proposed for the crash on boot in #9208.  I'm not setup to build ZFS in to the kernel, if you are able to compile the source and could help apply and test the proposed fix that would be most appreciated.  Sorry about the regression.

**Comment by tsjk** [comment]
@prometheanfire : I do like you do - except for that I don't merge sys-fs/zfs before kernel compilation (I do that later, just before initrd creation is initiated). So, I think that if it works for you, then the current issue only affects earlier kernel versions.

**Comment by prometheanfire** [comment]
this is fixed btw, can be closed

**Comment by tsjk** [comment]
@prometheanfire I still have this problem, though.

**Comment by prometheanfire** [comment]
have you tried with a more recent commit?  The script I linked above has worked for me (on 5.2.16 which has master as of `Thu Sep 19 21:11:20 CDT 2019`)

**Comment by tsjk** [comment]
I tried the most recent commit earlier today and that failed with the same error as above. Was compiling 4.19.75. Reverted to 95f0144675dd0e18617355443be0fbc7171af76b, which compiled.

**Comment by tsjk** [comment]
I had to adjust my compilation script a bit to make this work. In case someone googles here:
I had prepare instead of modules_prepare. In addition, I did a mrproper after zfs integration and before compilation. In the past this has worked. :)
