### ISSUE TITLE
Unnecessary immediate write leading to lower throughput than expected

### ISSUE THREAD

**Issue by shodanshok** [zfsonlinux/zfs#9320]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| CentOS 7
Distribution Version	| 7.5
Linux Kernel	| 3.10.0-862.14.4.el7.x86_64
Architecture	| x86-64
ZFS Version	| 0.7.12-1
SPL Version	| 0.7.12-1

### Describe the problem you're observing
**In short:** it seems that the decision to use immediate vs indirect writes is done *before* write coalescing.

`zfs_immediate_write_sz` is a zfs knob used to select when issuing an immediate write to the ZIL (with successive double-write into main pool) rather than to main pool (counter-intuitive called an "indirect write"). The idea is to privilege low latency for small sync writes (up to 32K by default), without impacting throughput for large writes.

ZIL is normally involved for sync writes only, as async writes always go to the main pool at txg commit. However, when synching previously-written contiguous small-block async data, `zfs_immediate_write_sz` flushes *all* blocks via ZIL even if, by the virtue of being continuous, they are coalesced into big block writes (bigger than `zfs_immediate_write_sz`).

### Describe how to reproduce the problem
Simply issue something as:
`dd if=/dev/urandom of=/tank/test.img bs=16K count=1024 conv=fsync`
or an even simpler
`dd if=/dev/urandom of=/tank/test.img bs=16K count=1024; sync`
Meanfile, use `dstat` and `zpool iostat -r 1` to monitor what happens at the disk level.
Using the above example, let see `dstat` (note: zfs disk is `sdf`):
```
--dsk/sda-----dsk/sdb-----dsk/sdc-----dsk/sdd-----dsk/sde-----dsk/sdf-----dsk/zd0--
 read  writ: read  writ: read  writ: read  writ: read  writ: read  writ: read  writ
   0     0 :   0     0 :   0     0 :   0     0 :   0     0 :   0     0 :   0     0
   0     0 :   0     0 :   0     0 :   0     0 :   0     0 :   0     0 :   0     0
   0     0 :   0     0 :   0     0 :   0     0 :   0     0 :   0     0 :   0     0
   0     0 :   0     0 :   0     0 :   0     0 :   0     0 :   0     0 :   0     0
   0     0 :   0     0 :   0     0 :   0     0 :   0     0 :   0     0 :   0     0
   0     0 :   0     0 :   0     0 :   0     0 :   0     0 :   0    17M:   0     0
   0     0 :   0     0 :   0     0 :   0     0 :   0     0 :   0     0 :   0     0
   0     0 :   0     0 :   0     0 :   0     0 :   0     0 :   0     0 :   0     0
   0     0 :   0     0 :   0     0 :   0     0 :   0     0 :   0     0 :   0     0
   0     0 :   0     0 :   0     0 :   0     0 :   0     0 :   0    16M:   0     0
```
Please notice how the 16MB total data were written *2* times (first on ZIL, then on the main pool). At the same time, `zpool iostat -r 1` shows that blocks *were* coalesced into big (64K) chunks:
```
tank          sync_read    sync_write    async_read    async_write      scrub
req_size      ind    agg    ind    agg    ind    agg    ind    agg    ind    agg
----------  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----
512             0      0      0      0      0      0      0      0      0      0
1K              0      0      0      0      0      0      0      0      0      0
2K              0      0      0      0      0      0      0      0      0      0
4K              0      0      0      0      0      0      0      0      0      0
8K              0      0      0      0      0      0      0      0      0      0
16K             0      0      0      0      0      0      0      0      0      0
32K             0      0      0      0      0      0      0      0      0      0
64K             0      0    145      0      0      0      0      0      0      0
128K            0      0      0      0      0      0      0      0      0      0
256K            0      0      0      0      0      0      0      0      0      0
512K            0      0      0      0      0      0      0      0      0      0
1M              0      0      0      0      0      0      0      0      0      0
2M              0      0      0      0      0      0      0      0      0      0
4M              0      0      0      0      0      0      0      0      0      0
8M              0      0      0      0      0      0      0      0      0      0
16M             0      0      0      0      0      0      0      0      0      0
--------------------------------------------------------------------------------
```

Being 64K bigger than `zfs_immediate_write_sz`, I expected all data to be written directly to main pool. As stated above, it seems that the decision to use immediate vs indirect writes is done *before* write coalescing.

**Comment by shodanshok** [comment]
@richardelling thank for these information. My test pool is extremely simple: a single vdev, with a single dataset, in a pristine virtualized environment. No SLOG is at play here. This is why I think `dstat` and `zpool iostat` reasonably depict what I described in the first post.

**Comment by richardelling** [comment]
I agree that your use case only applies to single disk, no slog pools. It is not a generic solution.

**Comment by shodanshok** [comment]
@richardelling thank for your informations. If the choice of immediate/indirect write is intrinsically done *before* write coalescing, I will close the issue, unless you feel it should be left open.

**Comment by richardelling** [comment]
lets close it. there are some other things that can help what you’re observing, but I don’t think this proposal is generically applicable

**Comment by shodanshok** [comment]
Ok, I'm closing. Thanks.
