### ISSUE TITLE
Wiki gdebi to gdebi-core 

### ISSUE THREAD

**Issue by Dmole** [zfsonlinux/zfs#9366]
https://github.com/zfsonlinux/zfs/wiki/Custom-Packages#debian-and-ubuntu

gdebi-core "contains the libraries and command-line utility."
gdebi  "contains the graphical user interface", uses mono and adds 89.5 MB of bloat. 

(quotes from `apt show` on Ubuntu 18.04)

**Comment by gmelikov** [comment]
Thanks, fixed.
