### ISSUE TITLE
ZFS 0.8.2 rpm package repo for Centos 7.7 does not include zfs-dracut

### ISSUE THREAD

**Issue by dacianstremtan** [zfsonlinux/zfs#9368]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| CentOS
Distribution Version	| 7.7
Linux Kernel	| 3.10.0-1062.1.1.el7.x86_64
Architecture	| x86_64
ZFS Version	| 0.8.2
SPL Version	| 0.8.2

### Describe the problem you're observing
The rpm packages for CentOS 7.7 does not include zfs-dracut on the 7.7 repo
### Describe how to reproduce the problem

run `yum update` to update zfs from 0.7.13 to 0.8.2 and the following error occurs:

> --> Processing Dependency: zfs(x86-64) = 0.7.13-1.el7_6 for package: zfs-dracut-0.7.13-1.el7_6.x86_64
> &nbsp;&nbsp;&nbsp;---> Package zfs.x86_64 0:0.8.2-1.el7 will be obsoleting
> --> Finished Dependency Resolution
> Error: Package: zfs-dracut-0.7.13-1.el7_6.x86_64 (@zfs-kmod)
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Requires: zfs(x86-64) = 0.7.13-1.el7_6
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Removing: zfs-0.7.13-1.el7_6.x86_64 (@zfs-kmod)
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;zfs(x86-64) = 0.7.13-1.el7_6
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Updated By: zfs-0.8.2-1.el7.x86_64 (zfs-kmod)
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;zfs(x86-64) = 0.8.2-1.el7

if force the upgrade then when running dracut to build the new initramfs the following error occurs:
`dracut module 'zfs' cannot be found or installed.`

**Comment by dacianstremtan** [comment]
I noticed that the 7_6 repo does include the dracut-zfs package, but not the 7_7 repo.
I'm using the zfs-kmod repository:
> [zfs-kmod]
> name=ZFS on Linux for EL7 - kmod
> **baseurl=http://download.zfsonlinux.org/epel/7.6/kmod/$basearch/**
> enabled=1
> metadata_expire=7d
> gpgcheck=1
> gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-zfsonlinux

versus

> [zfs-kmod]
>name=ZFS on Linux for EL7 - kmod
> **baseurl=http://download.zfsonlinux.org/epel/7.7/kmod/$basearch/**
> enabled=0
> metadata_expire=7d
> gpgcheck=1
> gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-zfsonlinux

Using the 7_6 repository when I run yum update --skip-broken (skip over kmod-spl-0.7.13) I get the following output

Package | Arch | Version | Repository | Size
------------|--------|------------|----------------|-------
 kmod-zfs |  x86_64  |  0.8.2-1.el7    |  zfs-kmod    | 1.2 M
 libnvpair1 | x86_64     |   0.8.2-1.el7 | zfs-kmod    |  32 k
 libuutil1 | x86_64|0.8.2-1.el7|zfs-kmod|26 k
 libzfs2|x86_64|0.8.2-1.el7|zfs-kmod|201 k
 libzfs2-devel|x86_64|0.8.2-1.el7|zfs-kmod|356 k
 libzpool2|x86_64|0.8.2-1.el7|zfs-kmod|841 k
 zfs|x86_64|0.8.2-1.el7|zfs-kmod|471 k
 zfs-dracut|noarch|0.8.2-1.el7|zfs-kmod|15 k

**Comment by dacianstremtan** [comment]
Looks like the 7.6 repo is a ghost town for 0.8.2 packages.  
> http://download.zfsonlinux.org/epel/7.6/kmod/x86_64/kmod-zfs-0.8.2-1.el7.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found    
Trying other mirror.
libuutil1-0.8.2-1.el7.x86_64.r FAILED                                          
http://download.zfsonlinux.org/epel/7.6/kmod/x86_64/libuutil1-0.8.2-1.el7.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found  
etc.

**Comment by behlendorf** [comment]
> Centos 7.7 does not include zfs-dracut 

Fixed.

> Looks like the 7.6 repo is a ghost town for 0.8.2 packages.

Fixed #9369.
