### ISSUE TITLE
0.8.2 breaks in-tree build

### ISSUE THREAD

**Issue by sempervictus** [zfsonlinux/zfs#9373]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Arch
Distribution Version	|  Current
Linux + Grsecurity Kernel	|  4.14.146
Architecture	|  x86_64
ZFS Version	|  0.8.2
SPL Version	|  This line should probably be removed

I've brought this up in different comments prior to the 0.8.2 release, but apparently  in-tree users are few and far between, so there's no build-bot for it. The directory restructuring shellgames have broken in-tree built-in (not module) builds:
```
 1413 |  unsigned coeff[MUL_CNT];
      |           ^~~~~
  AR      fs/zfs/zfs/zfs.o
  AR      fs/zfs/zfs/built-in.o
  AR      fs/zfs/built-in.o
ar: fs/zfs/os/built-in.o: No such file or directory
make[2]: *** [scripts/Makefile.build:480: fs/zfs/built-in.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [scripts/Makefile.build:585: fs/zfs] Error 2
make: *** [Makefile:1046: fs] Error 2
```
ping @behlendorf - this appears to be a major regression in a stable tag. While it makes sense to structure the code to be more respectful of the multiple OS' which need to build/run it, it doesn't make sense to do that at the cost of existing/expected functionality, and then release it in a stable tag without testing. I'll take a bit of time to dig into this if nobody knows offhand where the fix is (i didn't follow the code shuffling all too closely, no time nowadays to watch the commit logs), but i think this is more an issue of "not testing a major implementation method in builds or runs"

**Comment by sempervictus** [comment]
This is what exists in the kernel tree at the time of the error:
```
fs/zfs/spl/built-in.o
fs/zfs/nvpair/built-in.o
fs/zfs/unicode/built-in.o
fs/zfs/zcommon/built-in.o
fs/zfs/lua/built-in.o
fs/zfs/zfs/built-in.o
fs/zfs/avl/built-in.o
fs/zfs/icp/built-in.o
```
The autotools intricacies require a bit more time than i have right now, i can't even find the exact commit where all this madness happened because i cant figure out what to git blame. Does anyone know which commit(s) rewired the pathnames (and didn't account for how they have to change when in-tree)?

**Comment by ptx0** [comment]
that would be Matthew Macy @mattmacy who marked all his tickets as non breaking changes, Ryan Moeller @freqlabs, and brian @behlendorf who supposedly reviewed this code and merged into stable release.

**Comment by freqlabs** [comment]
> apparently in-tree users are few and far between, so there's no build-bot for it

There _is_ a bot that tests the in-tree build though, and it passed for the restructuring PRs:
http://build.zfsonlinux.org/builders/Kernel.org%20Built-in%20x86_64%20%28BUILD%29
http://build.zfsonlinux.org/builders/Kernel.org%20Built-in%20x86_64%20%28BUILD%29/builds/31831
http://build.zfsonlinux.org/builders/Kernel.org%20Built-in%20x86_64%20%28BUILD%29/builds/31862

**Comment by freqlabs** [comment]
In fact, 0.8.2 doesn't even include the restructuring commits.

**Comment by freqlabs** [comment]
@sempervictus perhaps you have previously done an in-tree build of master and reused the unclean kernel tree? I don't see anything in 0.8.2 that would cause the build to look for `fs/zfs/os/built-in.o`.

**Comment by behlendorf** [comment]
@sempervictus due to exactly your concern we excluded all of the OpenZFS restructuring changes from the release branch.  None of this work is planned to ever appear in an 0.8.x release.  Try running `git clean -dxf` in the repository before building to ensure you're starting with an entirely clean tree.  Note this will remove every file and directory in the repository which isn't tracked by git, so a little care is warranted.

**Comment by sempervictus** [comment]
Confirmed that `-dxf` was the fix. One of the PRs atop the 0.8.1 branch was probably the culprit, some artifact left over from git-unrelated-builds.
