### ISSUE TITLE
Spurious re-silver to same device immediately after previous re-silver completed

### ISSUE THREAD

**Issue by HastyMarly** [zfsonlinux/zfs#9378]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Archlinux
Distribution Version	| Rolling
Linux Kernel	| 5.3.1-arch1-1-ARCH
Architecture	| x86_64
ZFS Version	| 0.8.0-284_g73d7820bb
SPL Version	| 0.8.0-284_g73d7820bb

### Describe the problem you're observing

Spurious resilver to same device immediately after previous resilver completed.

### Describe how to reproduce the problem

All I did was run

    zpool replace  tank 272646635384699889 /dev/mapper/sdb1crypt

Once the initial resilver completed, it apparently started over from scratch without exiting.

### Include any warning/errors/backtraces from the system logs

% zpool status -v
  pool: tank
 state: DEGRADED
status: One or more devices is currently being resilvered.  The pool will
        continue to function, possibly in a degraded state.
action: Wait for the resilver to complete.
  scan: resilver in progress since Sun Sep 29 18:58:47 2019
        1.61T scanned at 254M/s, 784G issued at 121M/s, 2.88T total
        784G resilvered, 26.60% done, 0 days 05:05:31 to go
config:

        NAME                      STATE     READ WRITE CKSUM
        tank                      DEGRADED     0     0     0
          mirror-0                DEGRADED     0     0     0
            replacing-0           DEGRADED     0     0     0
              272646635384699889  UNAVAIL      0     0     0  was /dev/mapper/sdb1crypt/old
              sdb1crypt           ONLINE       0     0     0  (resilvering)
            sda1crypt             ONLINE       0     0     0

errors: No known data errors

**Comment by jgallag88** [comment]
This sounds like it could be the same issue as #9155.
