### ISSUE TITLE
ZFS NFS sharenfs=on does NOT map root user to nobody by default

### ISSUE THREAD

**Issue by gkeen** [zfsonlinux/zfs#9397]
I have setup two different systems running Centos 7.7 with zfs 0.7.13-1 and created a filesystem inside a pool then shared it out with set sharenfs=on <pool/filesystem> . When I mount that NFS share on a system( another linux system ) on the same network as root. The root user can create files and directories as root and is not mapped to user nobody.

### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Centos
Distribution Version	| 7
Linux Kernel	| 3.10.0-1062.1.1.el7.x86_64
Architecture	| x86
ZFS Version	| v0.7.13-1
SPL Version	| v0.7.13-1

### Describe the problem you're observing
Using zfs set sharenfs=on to a zfs filesystem by default does not map root user to user nobody

### Describe how to reproduce the problem
Install Centos 7 on any white box. Install zfs version 0.7.13-1. Create a pool of available drives and turn NFS on with no other options using zfs set sharenfs=on <pool/filesystem>. Move to another system that has a NFS client on it. As root user ,mount the newly shared zfs directory. Create a file or directory or both as root. Do a long listing in the directory to discover the owner/group permissions remain root.

**Comment by gkeen** [comment]
Well, I did find this, https://zfsonlinux.org/manpages/0.7.13/man8/zfs.8.html  This behavior is by default. Aside from all the other implementations of NFS. ZoL is wide open. Seems like a bold move and as history has proven may not be the best.

**Comment by behlendorf** [comment]
@gkeen thank's for calling our attention to this. I've opened PR #9425 which modifies the default behavior to something a little more conventional.

**Comment by gkeen** [comment]
Brian, thank you for the reply. I’m guessing I should  leave the ticket I opened, open for right now.

**Comment by behlendorf** [comment]
@gkeen yes, please leave it open.  We'll close it out once the proposed changed in reviewed and merged.
