### ISSUE TITLE
Doc: Debian-Buster-Root-on-ZFS.md update for ZFS 0.8.2

### ISSUE THREAD

**Issue by HankB** [zfsonlinux/zfs#9398]
Attention @rlaager 

### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Debian
Distribution Version	| Buster
Linux Kernel	| N/A
Architecture	| AMD_64
ZFS Version	| 0.8.2
SPL Version	| unknown

### Describe the problem you're observing

Patch to apply workaround for zfs-initramfs's Plymouth fix is no longer needed.

### Describe how to reproduce the problem

Follow instructions, `patch` reports previously applied.

### Include any warning/errors/backtraces from the system logs

[my-changes.zip](https://github.com/zfsonlinux/zfs/files/3682093/my-changes.zip)

Tested by removing the lines 308,309 in https://github.com/HankB/Linux_ZFS_Root/blob/master/Debian/install_Debian_to_ZFS_root.sh and installing (whole disk, LUKS encryption and followup by installing `gnome-core`.)

**Comment by rlaager** [comment]
Thanks for the report. I saw that 0.8.2 hit buster-backports yesterday. I've removed those steps now.
