### ISSUE TITLE
Can't install ZFS 0.8.2 on Centos 7.8 

### ISSUE THREAD

**Issue by HishnGA** [zfsonlinux/zfs#9407]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Centos
Distribution Version	| 7.8
Linux Kernel	| 5.3
Architecture	| X86_64
ZFS Version	| 0.8.2
SPL Version	| 

### Describe the problem you're observing
I am trying to install ZFS onto a new Centos 7.8 system.  I have gotten all the prerequisites installed but when I do a "yum install zfs" I am getting the following error:
"http://download.zfsonlinux.org/epel-testing/7.7/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror."

When I try putting that URL into a Chrome I get:
"<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>epel-testing/7.7/x86_64/repodata/repomd.xml</Key>
<RequestId>2EB5D28D144B2F03</RequestId>
<HostId>
IhekFUFK03cXxff6mbh2E3mAttx9f7K/hWHDry3UUyFM8SRRQ/1AOJgQ/sVNbsBtV/NucpcOTI4=
</HostId>
</Error>"

I am wondering if something is broken on the upstream of my machine.

**Comment by tonyhutter** [comment]
Sorry, we only support Centos 7.7 at this time.   We'll support Centos 7.8 when it is released.  In the meantime, I'd recommend building from source.

**Comment by tobgen** [comment]
7.8 is released ;)

**Comment by npelov** [comment]
How much time after centos release  is ZFS compiled. I forgot to check first and I updated the OS, but there is no zfs release for 7.8? I Booted to the old kernel and then re-installed zfs and now it works, but I have servers that do not have KVM and it's pain in the ass to switch kernel with grub2. I need some kind of reminder not to update until zfs release is confirmed.

**Comment by tau-labs** [comment]
Same problem here since yesterday :-(

**Comment by ewwhite** [comment]
Just got hit by this. I didn't realize there wasn't support for 7.8 yet.

**Comment by dswartz** [comment]
Same here.  Ended up going to dkms.
