### ISSUE TITLE
Idiomatic 'cp -a' in buster install.

### ISSUE THREAD

**Issue by colmbuckley** [zfsonlinux/zfs#9420]
Idiomatic way to copy a full directory (eg: /etc/skel) including dotfiles to another, without an awkward glob, is 'cp -a src/. dest'. Patch for the Buster root wiki page attached.

@rlaager PTAL?

[idiom-cp.zip](https://github.com/zfsonlinux/zfs/files/3694909/idiom-cp.zip)

**Comment by rlaager** [comment]
Hey, that's a really neat trick! Merged. Thanks!
