### ISSUE TITLE
zpool: symbol lookup error: zpool: undefined symbol: is_mpath_whole_disk

### ISSUE THREAD

**Issue by rkrten** [zfsonlinux/zfs#9456]
### System information

Type | Version/Name
------|---------------
Linux | Ubuntu 16.04.1
Distribution Name	| Ubuntu
Distribution Version	| 16.04.1
Linux Kernel	| 4.15.0-65-generic #74\~16.04.1-Ubuntu
Architecture	| x86_64
ZFS Version	| 0.8.2-2\~16.04.york0
SPL Version	| 0.8.2-2\~16.04.york0

### Describe the problem you're observing
Issue "zpool" command and get the error message in the title.

### Describe how to reproduce the problem
As above.

### Include any warning/errors/backtraces from the system logs

None.

Please advise on how to diagnose.

**Comment by behlendorf** [comment]
It sounds as if you are somehow using a newer `zpool` binary with an older version of the `libzfs` library which lacks the needed symbol.  If possible, I'd suggest uninstalling and then reinstalling the zfs user space packages and see if that resolves it.

**Comment by rkrten** [comment]
Hi Brian,

yeah, I tried that. I did an "apt purge zfsutils-linux" followed by an "apt install zfsutils-linux" with an intervening reboot after each. No change. What's the correct procedure to absolutely positively start from "scratch" (short of re-installing ubuntu, LOL)? Is there any more info I can provide? Happy to do so!

That said, I booted ubuntu 19.10 off of a USB stick and it was able to mount the encrypted ZFS pool just fine, so that's a good sign...

**Comment by rkrten** [comment]
Ok, so the problem appears to be that `apt purge zfsutils-linux` doesn't purge enough stuff.
I hunted down and removed the following:

```
# find /usr/local/lib -name "*zfs*" | xargs rm
# rm -rf /var/lib/dkms/zfs
```

And then reinstalled `zfsutils-linux`; everything works now :-)
