### ISSUE TITLE
efibootmgr command error in Ubuntu 18.04 Root on ZFS

### ISSUE THREAD

**Issue by cyfdecyf** [zfsonlinux/zfs#9490]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Ubuntu
Distribution Version	|  18.04
Linux Kernel	|  5.0.0-31
Architecture	|  x86_64
ZFS Version	|  0.7.5-1ubuntu16.6
SPL Version	| 

[Ubuntu 18.04 Root on ZFS](https://github.com/zfsonlinux/zfs/wiki/Ubuntu-18.04-Root-on-ZFS) section 6.8b, current version says:

```
# umount /boot/efi

For the second and subsequent disks (increment ubuntu-2 to -3, etc.):
# dd if=/dev/disk/by-id/scsi-SATA_disk1-part2 \
     of=/dev/disk/by-id/scsi-SATA_disk2-part2
# efibootmgr -c -g -d /dev/disk/by-id/scsi-SATA_disk2 \
      -p 3 -L "ubuntu-2" -l '\EFI\ubuntu\grubx64.efi'

# mount /boot/efi
``` 

**The `efibootmgr` command should use `-p 2` as argument** instead of `-p 3`.

`grub-install` creates an UEFI boot entry like following:

```
Boot0000* ubuntu      HD(2,GPT,d127be86-cb17-4a72-b755-3cc231ccb122,0x800,0x32000)/File(\EFI\ubuntu\shimx64.efi)
```

The part uuid is correct in this case and I can use this entry to boot up system.

When I followed the document and use `-p 3` command to create UEFI boot entry, I got entry like following:

```
Boot0006* ubuntu-2    HD(3,GPT,482b73dc-af44-4c1e-9b02-ada240806e48,0x32800,0xc8000)/File(\EFI\ubuntu\shimx64.efi)
```

The part uuid in this entry refers to part3 which is for boot pool instead of EFI partition, thus can't boot up system.

**Comment by rlaager** [comment]
Thanks! I failed to update that when changing the partition layout. It's fixed now in be7eda21e31a451d10eff0e98571ea92ddfc98f2 on the wiki.
