### ISSUE TITLE
install to standard debian buster fails

### ISSUE THREAD

**Issue by nomisma-qt** [zfsonlinux/zfs#9547]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Debian Buster
Distribution Version	| 10.1
Linux Kernel	| 4.19.0-6-amd64
Architecture	| 
ZFS Version	| 0.8.2-3
SPL Version	| 0.8.2-3

### Include any warning/errors/backtraces from the system logs

I am not an expert, and unable to decode this. But i install a standard Debian Buster on XFS filesystem, and then i go to the ZFS Wiki, and read Getting started - Debian, and follow the instructions, and it does NOT work.

```
DKMS: install completed.
Setting up libzpool2linux (0.8.2-2~bpo10+1) ...
Setting up zfsutils-linux (0.8.2-2~bpo10+1) ...
Created symlink /etc/systemd/system/zfs-import.target.wants/zfs-import-cache.service → /lib/systemd/system/zfs-import-cache.service.
Created symlink /etc/systemd/system/zfs.target.wants/zfs-import.target → /lib/systemd/system/zfs-import.target.
Created symlink /etc/systemd/system/zfs.target.wants/zfs-mount.service → /lib/systemd/system/zfs-mount.service.
Created symlink /etc/systemd/system/zfs.target.wants/zfs-share.service → /lib/systemd/system/zfs-share.service.
Created symlink /etc/systemd/system/zfs-volumes.target.wants/zfs-volume-wait.service → /lib/systemd/system/zfs-volume-wait.service.
Created symlink /etc/systemd/system/zfs.target.wants/zfs-volumes.target → /lib/systemd/system/zfs-volumes.target.
Created symlink /etc/systemd/system/multi-user.target.wants/zfs.target → /lib/systemd/system/zfs.target.
zfs-import-scan.service is a disabled or a static unit, not starting it.
Job for zfs-mount.service failed because the control process exited with error code.
See "systemctl status zfs-mount.service" and "journalctl -xe" for details.
invoke-rc.d: initscript zfs-mount, action "start" failed.
● zfs-mount.service - Mount ZFS filesystems
   Loaded: loaded (/lib/systemd/system/zfs-mount.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2019-11-02 06:45:07 EET; 5ms ago
     Docs: man:zfs(8)
  Process: 2635 ExecStart=/sbin/zfs mount -a (code=exited, status=1/FAILURE)
 Main PID: 2635 (code=exited, status=1/FAILURE)

Nov 02 06:45:07 buster-xfs systemd[1]: Starting Mount ZFS filesystems...
Nov 02 06:45:07 buster-xfs zfs[2635]: The ZFS modules are not loaded.
Nov 02 06:45:07 buster-xfs zfs[2635]: Try running '/sbin/modprobe zfs' as root to load them.
Nov 02 06:45:07 buster-xfs systemd[1]: zfs-mount.service: Main process exited, code=exited, status=1/FAILURE
Nov 02 06:45:07 buster-xfs systemd[1]: zfs-mount.service: Failed with result 'exit-code'.
Nov 02 06:45:07 buster-xfs systemd[1]: Failed to start Mount ZFS filesystems.
dpkg: error processing package zfsutils-linux (--configure):
 installed zfsutils-linux package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of zfs-zed:
 zfs-zed depends on zfsutils-linux (>= 0.8.2-2~bpo10+1); however:
  Package zfsutils-linux is not configured yet.

dpkg: error processing package zfs-zed (--configure):
 dependency problems - leaving unconfigured
Processing triggers for systemd (241-7~deb10u1) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for libc-bin (2.28-10) ...
Errors were encountered while processing:
 zfsutils-linux
 zfs-zed
E: Sub-process /usr/bin/dpkg returned an error code (1)

```

After that the zfs modules do NOT load at boot. update-initramfs -u does not help. I don't know how to get the modules to load.

Question: can having the backports in repos affect the system when installing other packages? If so, it's a terrible idea, as i'd like to keep my system as close to standard as possible

If i install Proxmox there is no problems, ZFS runs fine with AES-NI support. Why does it has to be this difficult? The install procedure should be:

apt install zfs --yes

I would suggest you hold on developing further until you are able to come up with a working installer for Debian yes? Everytime i update my systems i'm scared that ZFS in particular will screw up my system. because months and years go by and there's always some problem, issue or error, and to be frank i'm very disappointed with how you have handled all this, I'm not a linux expert, and ZFS on Linux has been a constant nightmare for years.

**Comment by BlauerHunger** [comment]
What does the syslog say about the failed service zfs-mount? Does `modprobe -v zfs` load the modules?

**Comment by nomisma-qt** [comment]
> What does the syslog say about the failed service zfs-mount? Does `modprobe -v zfs` load the modules?

syslog says reason is that zfs module is not loaded, and i can load the module, then manually start the services, so the only issue is the install fails because the modules are not loaded.. And then loading the modules at boot never occurs.. it should be easy to reproduce by installing to a debian system with no previous zfs installation.. I tried compiling from source and creating .deb installers for all the services and the same thing occurs

**Comment by rlaager** [comment]
The issue here is that the zfs modules are loaded by a `modprobe zfs` that is an `ExecStartPre` on `zfs-import-scan.service` and `zfs-import-cache.service`. The cache unit only fires when a cache file is present, which won't exist if you've never used ZFS before on that system. So you want the `zfs-import-scan.service`, but that service does not get started by default. It was disabled by default in #4699.

I'm not sure what the best solution is here. One option would be to separate out the `modprobe zfs` into a different unit that `zfs-mount.service` also requires.

**Comment by nomisma-qt** [comment]
As i understand, ubuntu has zfs modules in kernel because they choose to ignore the licence issues, or am i wrong? It's a really annoying situation in that sense. 

Maybe it would be a good idea to look closer how Proxmox deals with ZFS, i've worked alot with PVE and their debian based ZFS implementation just works, right now they are running kernel 5.x with full SIMD support, and have a working ZFS installer as well.

I'll go ahead and close this if there are no more comments in awhile, thx
