### ISSUE TITLE
Deceptive error when creating a zpool with options, without root permissions

### ISSUE THREAD

**Issue by JustinLovinger** [zfsonlinux/zfs#9550]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  NixOS
Distribution Version	|  19.09
Linux Kernel	| 4.19.78
Architecture	| x86_64
ZFS Version	| 0.8.2-1
SPL Version	| 0.8.2-1

### Describe the problem you're observing

While trying to create a pool with `autotrim`, I get the error:
`cannot create 'pool': property 'autotrim'(31) not defined`.
`man zpool` show that `autotrim` is a valid property.
I can use `zpool set autotrim=on pool`.

### Describe how to reproduce the problem
1. `$ dd if=/dev/zero of=/tmp/poolfile bs=100MB count=1`
2. `$ zpool create -o autotrim=on temp /tmp/poolfile`

### Update

A little more testing shows that the error only occurs when trying to run `zpool create ...` without root permissions, and is similar for other options. It looks like the real issue is that the error message is deceptive.

**Comment by kpande** [comment]
easiest solution is; don't use autotrim with s3backer, it has terrible queueing strategy. it does not properly throttle DELETE vs GET/PUT, and overall, s3backer is not the way to go for object support. my company is currently in development of native http vdev support for zfs.

**Comment by JustinLovinger** [comment]
The error here isn't related to s3backer. See the Update for more information.

**Comment by kpande** [comment]
surely you can tell a bit of helpful guidance when you see it though; I have done much work on s3backer.

**Comment by GregorKopka** [comment]
> the error only occurs when trying to run `zpool create ...` without root permissions, and is similar for other options. It looks like the real issue is that the error message is deceptive.

Please rename the issue accordingly.
