### ISSUE TITLE
fiemap rebase fails fiemap_free test

### ISSUE THREAD

**Issue by rohan-puri** [zfsonlinux/zfs#9552]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu
Distribution Version	| 19.10
Linux Kernel	| 5.3.0-19-generic
Architecture	| x86_64
ZFS Version	| latest master (0.8.1-1ubuntu12)
SPL Version	| latest master (0.8.1-1ubuntu12)

### Describe the problem you're observing
Pull request #7545 , has a zfs-tests for fiemap implementation, which I have rebased to new master, while running the test, "fiemap_free" test failed.
### Describe how to reproduce the problem
Running filemap_free tests which are part of pull request #7545 
### Include any warning/errors/backtraces from the system logs

fiemap_free test run failed.
```
/home/rohan/zol-ws/zfs/tests/test-runner/bin/test-runner.py  -c "tests/runfiles/fiemap.run" -T "functional" -i "/home/rohan/zol-ws/zfs/tests/zfs-tests" -I "1"
Test: /home/rohan/zol-ws/zfs/tests/zfs-tests/tests/functional/fiemap/setup (run as root) [00:01] [PASS]
Test: /home/rohan/zol-ws/zfs/tests/zfs-tests/tests/functional/fiemap/fiemap_free (run as root) [00:01] [FAIL]
Test: /home/rohan/zol-ws/zfs/tests/zfs-tests/tests/functional/fiemap/cleanup (run as root) [00:00] [PASS]
```
From the test log I see,
```
Hole verify failed, additional extents found
Hole verify failed, 1 extent(s) missing

    obj=3 dataset=testpool/testfs path=/fiemap-file type=19 bonustype=44

    Object  lvl   iblk   dblk  dsize  dnsize  lsize   %full  type
         3    2   128K     4K    34K     512    32K  100.00  ZFS plain file (K=inherit) (Z=inherit)
                                               176   bonus  System attributes
        dnode flags: USED_BYTES USERUSED_ACCOUNTED USEROBJUSED_ACCOUNTED
        dnode maxblkid: 7
        uid     0
        gid     0
        atime   Wed Nov  6 01:01:51 2019
        mtime   Wed Nov  6 01:01:51 2019
        ctime   Wed Nov  6 01:01:51 2019
        crtime  Wed Nov  6 01:01:51 2019
        gen     38
        mode    100644
        size    32768
        parent  34
        links   1
        pflags  840800000004
Indirect blocks:
               0 L1  2:3000e000:400 20000L/400P F=8 B=38/38
               0  L0 2:20000800:1000 1000L/1000P F=1 B=38/38
            1000  L0 2:20001800:1000 1000L/1000P F=1 B=38/38
            2000  L0 2:20003a00:1000 1000L/1000P F=1 B=38/38
            3000  L0 2:20005c00:1000 1000L/1000P F=1 B=38/38
            4000  L0 2:20007400:1000 1000L/1000P F=1 B=38/38
            5000  L0 2:20008c00:1000 1000L/1000P F=1 B=38/38
            6000  L0 2:20009c00:1000 1000L/1000P F=1 B=38/38
            7000  L0 2:2000b400:1000 1000L/1000P F=1 B=38/38

                segment [0000000000000000, 0000000000008000) size   32K
----- Missing Hole Tree Extents -----
ID   Logical (Start-End Length)
0    0x000000000008-0x000000008000     32760
Hole verify failed, additional extents found
Hole verify failed, 1 extent(s) missing
Extents: 6
ID   Logical (Start-End Length)              Physical (Start-End Length)             Dev Flags
0    0x000000000008-0x000000001fff      8184 0x000000000000-0x000000000000         0 2   merged
1    0x000000002000-0x000000002fff      4096 0x000020003a00-0x0000200049ff      4096 2
2    0x000000003000-0x000000003fff      4096 0x000020005c00-0x000020006bff      4096 2
3    0x000000004000-0x000000004fff      4096 0x000020007400-0x0000200083ff      4096 2
4    0x000000005000-0x000000006fff      8192 0x000020008c00-0x00002000abff      8192 2   merged
5    0x000000007000-0x000000007fff      4096 0x00002000b400-0x00002000c3ff      4096 2   last
ERROR: fiemap -v -H 0:32768:1 -F delalloc,unwritten:0 /var/tmp/testdir/fiemap-file exited 8
```
On further analysis, I found this to be related to commit id "ca5777793ee10b9f7bb57aef00a6c8d57969625e".

On enabling "ZFS_DEBUG_DPRINTF" zfs_flags, I was able to see for the object id 3 in question above,
```
1572982312   dprintf: dnode.c:2230:dnode_free_range(): ds=testpool/testfs obj=3 blkid=0 nblks=8 txg=50
1572982312   dprintf: dnode.c:2230:dnode_free_range(): ds=testpool/testfs obj=3 blkid=0 nblks=8 txg=50

```

This where I saw 8, which is showing start of the first extent, after 0 to 7 bytes are freed.

The issue is dnode_free_range() calls, range_tree_add() with blkid & nblks(no of blocks), but the new range tree implementation here is initialized with "0"  shift and hence so expects offset&len and it treats freeing of 8 blocks from blockid 0 as freeing 8 bytes from offset 0, which is incorrect.

**Comment by ahrens** [comment]
> The issue is dnode_free_range() calls, range_tree_add() with blkid & nblks(no of blocks), but the new range tree implementation here is initialized with "0" shift and hence so expects offset&len and it treats freeing of 8 blocks from blockid 0 as freeing 8 bytes from offset 0, which is incorrect.

As mentioned in #9553, I don't think this analysis is correct.  The new range tree implementation does not care whether we are storing bytes or blocks.  The calling code all treats `dn_free_ranges` as storing blocks.

**Comment by ahrens** [comment]
> This where I saw 8, which is showing start of the first extent, after 0 to 7 bytes are freed.

This is showing that block ID's 0 through 7 (inclusive) are freed.  ZFS has no mechanism for tracking frees with sub-block granularity.  Sub-block frees are converted to writes of zero's, which AFAIK is the same as any other filesystem.

**Comment by rohan-puri** [comment]
@ahrens : Good point :)

Did the conversion in fiemap patch, updated fiemap pull request, closing this bug, since the bug is not in master, it was in rebased fiemap patch.
