### ISSUE TITLE
How to zfs send recursively and disable compression?

### ISSUE THREAD

**Issue by erpadmin** [zfsonlinux/zfs#9567]
zfsol zfs send does not appear to support the '-r' switch.  on solaris this would just recursively send, no extra.   while using -R (replicate) on a large set of fs's, the compression value is propagated to the destination.

can i use the replicate switch but override the compression?  i've made the assumption the data remains compressed in the stream.

**Comment by kpande** [comment]
use the mailing list if your question is support related.
