### ISSUE TITLE
Cannot remove top level dev. Error: out of space

### ISSUE THREAD

**Issue by xgiovio** [zfsonlinux/zfs#9579]
```
NAME                             SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
 
xpool2                          4.08T  3.43T   661G        -         -    28%    84%  1.00x    ONLINE  -
  wwn-0x50014ee258468906         464G   438G  26.2G        -         -    55%  94.3%      -  ONLINE  
  wwn-0x50014ee25e68bf96        3.62T  3.01T   635G        -         -    25%  82.9%      -  ONLINE  


sudo zpool remove xpool2  /dev/disk/by-id/wwn-0x50014ee258468906
cannot remove /dev/disk/by-id/wwn-0x50014ee258468906: out of space
```
I cannot remove a disk from striped pool also if there is a lot of space available

**Comment by ahrens** [comment]
There is not a lot of space available.  After removal you would have at most 635G-464G = 171G which is 4.6% of the pool.  There needs to be double the slop space, or about 6%.

**Comment by xgiovio** [comment]
thank you @ahrens . My question is: is there any method or command to understan exactly how many bytes i need to remove? You said, the slop space should be 6% but it is a fixed value? and approximation? Something should I know? Thank you

**Comment by ahrens** [comment]
The general rule is "a lot of space needs to be left free after the removal".  But yeah typically it would be between 6-7%.  It would be nice if the error message could tell you exactly how much more free space is required, though.

**Comment by xgiovio** [comment]
Thank you
