### ISSUE TITLE
commit 6c68594675ed3fdc1 ("Implement secpolicy_vnode_setid_retain()") causes a regression in the fstests chown 00 test 

### ISSUE THREAD

**Issue by ColinIanKing** [zfsonlinux/zfs#9585]
I've found a regression between ZFS 0.8.1 and 0.8.2 caused by commit 6c68594675ed3fdc1d663da47eaeb27c3db97f29 ("Implement secpolicy_vnode_setid_retain()").  When I revert this commit in 0.8.2 the regression is fixed.

### System information

Type | Version/Name
 --- | --- 
Ubuntu	|  20.04
Linux Kernel	|  5.3 and 5.4-rc6
Architecture	| amd64 (probably all)
ZFS Version	| 0.8.2 (0.8.2-3ubuntu1)
SPL Version	| 0.8.2

### Describe the problem you're observing

Running the fstests with ZFS 0.8.2 on 5.3 or 5.4-rc6 kernels I hit a failure on fstests chown 00 test.  To reproduce this failure on Ubuntu 20.04:

```
git clone git://kernel.ubuntu.com/ubuntu/autotest
git clone git://kernel.ubuntu.com/ubuntu/autotest-client-tests
git reset --hard 243b28ed9e9db2dec1cd59d0d957fc48a5bb4bda
cd autotest/client
rmdir tests
ln -s ../../autotest-client-tests tests
cd ..
cd ..
sudo apt-get install python gdb zfsutils-linux zfs-dkms
sudo autotest/client/autotest-local autotest/client/tests/ubuntu_zfs_fstest/control -v

This will fail:

12:08:48 DEBUG| [stdout] /home/cking/autotest/client/tmp/ubuntu_zfs_fstest/src/tests/chmod/11.t ..... ok
12:09:05 DEBUG| [stdout] /home/cking/autotest/client/tmp/ubuntu_zfs_fstest/src/tests/chown/00.t ..... 
12:09:05 DEBUG| [stdout] Failed 2/171 subtests 

...
  Test Summary Report
  -------------------
  /home/cking/autotest/client/tmp/ubuntu_zfs_fstest/src/tests/chown/00.t   (Wstat: 0 Tests: 171 Failed: 2)
    Failed tests:  84, 88
  Files=184, Tests=1957, 62 wallclock secs ( 0.62 usr  0.15 sys +  8.89 cusr  2.73 csys = 12.39 CPU)
  Result: FAIL
```

Reverting 6c68594675ed3fdc1d663da47eaeb27c3db97f29 in ZFS 0.8.2 fixes this issue.

**Comment by behlendorf** [comment]
This _is_ a change in behavior but it was done intentionally to resolve an issue @kusumi identified when running a [newer version](https://github.com/pjd/pjdfstest) of fstests.  Issue #9035 has the full analysis.  We should verify that the original test case really is functionally correct.  This test has apparently been updated upstream to accomodate some different linux behavior which may explain this, https://github.com/pjd/pjdfstest/commit/d9cc02.  The https://github.com/zfsonlinux/fstest.git does not include those changes.

**Comment by kusumi** [comment]
Interesting. Will take a look at it when I have time. The original commit was really just 1 loc `return (priv_policy_user(cr, CAP_FSETID, B_FALSE, EPERM));` which was unimplemented till then.

**Comment by ColinIanKing** [comment]
Just to confirm that when I updated to the latest fstests in our test infrastructure and all the tests pass so it is a change in the fstests. But we kind of knew that, but I wanted to add in that datapoint.

**Comment by ColinIanKing** [comment]
From my perspective it's OK to close this issue. Apologies for wasting your time.
