### ISSUE TITLE
libzfs always tries to load zfs modules stack, even when builtin

### ISSUE THREAD

**Issue by foobarz** [zfsonlinux/zfs#960]
spl and zfs can be configured with --enable-linux-builtin=yes and use the copy-builtin scripts to install spl and zfs source code into the linux kernel source code tree to have the option to have builtin modules in your private kernel.

When the modules are builtin to the kernel, libzfs (and the zfs and zpool tools using it) do not need to try to load the zfs modules stack, but libzfs always tries to load them and prints a message out telling you:

Failed to load ZFS module stack.
Load the module manually by running 'insmod <location>/zfs.ko' as root.

This seems to happen on the first usage of any program linked to libzfs, and happens at program init, (and I think) even before the program calls libzfs_init().

This is a very minor issue because it causes no problem really. But, it is just that libzfs is unaware that modules could be builtin. I am not sure the exact way that software determine if functionality is builtin to the kernel already, but would be nice if libzfs would have this check and if builtin already, keep silent and continue.

In addition, while I compile and static link to libzfs, I get some warnings but the compile and link still completes ok:

/lib/../lib64/libzfs.a(libzfs_dataset.o): In function `userquota_propname_decode':
/root/src/zfs-0.6.0-rc10/lib/libzfs/../../lib/libzfs/libzfs_dataset.c:2478: warning: Using 'getgrnam' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/root/src/zfs-0.6.0-rc10/lib/libzfs/../../lib/libzfs/libzfs_dataset.c:2474: warning: Using 'getpwnam' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking

I would like to be able to static link to libzfs without any warnings. I have not run into any problem that these warnings are about because I have only used the zpool_import() function of libzfs to make a small initramfs tool to import and boot a root zfs pool. Static linking to libzfs is useful to make special customized tools for initramfs that do not depend on the full spl and zfs packages to be installed in the initramfs. I understand the usecase for this is small because most users will just install the full spl and zfs packages into the initramfs or initrd image.

Lastly, I have read that libzfs is a "private" library of the zfs package for it's own tools, not intended for user programs. I realize this, but have found libzfs nice to experiment with for my own zfs tool.

If you would like more information on my weird usage case, you can see this: http://slackwiki.com/ZFS_root_%28builtin%29

**Comment by behlendorf** [comment]
Closing.  The ZFS modules are no longer automatically loaded.
