### ISSUE TITLE
Debian Buster Root on ZFS

### ISSUE THREAD

**Issue by ellisonj** [zfsonlinux/zfs#9617]
Seems I had troubles with rpool/tmp refusing to mount correctly on boot. After reviewing the Stretch version I noticed the tmpfs part being mutually exclusive to the rpool/tmp option. After copying the data off rpool/tmp I destroyed the dataset. Copied everything back in /tmp ala tmpfs after the next boot. Reboots with no mounting issues. 

It seems tmpfs is default in Buster. So this part should be rewritten with this in mind.

**Comment by Ornias1993** [comment]
It would be extra helpfull if you could copy-pasta the part of the guide thats wrong, rewrite it a bit and add that to your issue.

That way it could be changed by a maintainer extra swiftly :)

**Comment by rlaager** [comment]
I just tested in one of my test VMs. I switched from `tmp.mount` (which mounts a tmpfs at `/tmp`) to `rpool/tmp`. It works fine. The Buster version of the guide does explain that there are three options and you have to pick one.

If you have further information on how it was breaking for you or suggestions on what I can change, let me know.
