### ISSUE TITLE
zpool add -n special does not print special, or check feature allocation_classes

### ISSUE THREAD

**Issue by inkdot7** [zfsonlinux/zfs#9627]
### System information
Type | Version/Name
 --- | --- 
Distribution Name	| Debian
Distribution Version	| 9.11
Linux Kernel	| 4.9.0-11-amd64
Architecture	| amd64
ZFS Version	| 0.8.0-408_g0c4681380  (compiled from source)
SPL Version	| 0.8.0-408_g0c4681380

### Describe the problem you're observing
When adding a special device in dry-run mode (`zpool add -n`), it does not print the special marker in the list of the would-be configuration.
```
# zpool add -n znimbus1 special /dev/vde1 
would update 'znimbus1' to the following configuration:
        znimbus1
          vdb
          vdc
          vdd
          vde1
```
Expected result (which is like what `zpool status` prints, after actual adding):
```
# zpool add -n znimbus1 special /dev/vde1 
would update 'znimbus1' to the following configuration:
        znimbus1
          vdb
          vdc
          vdd
        special
          vde1
```
Also, the `zpool add -n` command did not warn that the pool is missing the allocation classes feature, as the actual command (without `-n`) does:
```
# zpool add znimbus1 special /dev/vde1 
cannot add to 'znimbus1': pool must be upgraded to add these vdevs
```

### Describe how to reproduce the problem
`zpool add -n pool special vdev`

**Comment by Ornias1993** [comment]
Mostly a duplicate of #9390

**Comment by inkdot7** [comment]
@Ornias1993 thanks!  Sorry, did not find that when searching.

**Comment by Ornias1993** [comment]
NP happens to the best of us :)
