### ISSUE TITLE
Wiki: ZFS root on Ubuntu 18.04 should disable gnome-initial-setup

### ISSUE THREAD

**Issue by omsai** [zfsonlinux/zfs#9628]
Wiki page: https://github.com/zfsonlinux/zfs/wiki/Ubuntu-18.04-Root-on-ZFS#step-8-full-software-installation

After completing the optional step 8.2b, rebooting the machine confusingly tries to walk you through the new user setup process even though local users have been created.  The workaround for this on Ask Ubuntu https://askubuntu.com/a/1039368 is to modify `/etc/gdm3/custom.conf` with:

```
[daemon]
InitialSetupEnable=false
```

Then one is presented with the typical login screen instead of always being asked to create a new user.

It would be great if this need to patch `custom.conf` can be added maybe to section 8.2b itself between installing `ubuntu-desktop` and before the suggestion for installing `NetworkManager`.

**Comment by behlendorf** [comment]
@rlaager would you mind commenting on this.

**Comment by rlaager** [comment]
It's been a while since I have done a full GUI install from scratch. When I test, I tend to test just a CLI install to verify the ZFS steps. I'll take you at your word. :) I've merged this change in 72066a939e1e4bf5e9b88d1cf72f1f9492295c10.
