### ISSUE TITLE
initramfs scripts/zfs tries to mount root subdataset with canmount=noauto

### ISSUE THREAD

**Issue by deliank** [zfsonlinux/zfs#9637]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Debian
Distribution Version	|  Buster (10.0
Linux Kernel	|  4.19.0-6-amd64
Architecture	|  amd-64
ZFS Version	|  0.8.2-2~bpo10+1
SPL Version	| 0.8.2-2~bpo10+1

### Describe the problem you're observing

If this is my unencrypted root dataset:

`rpool/hm/root`

and I create an encrypted subdataset:

`rpool/hm/root/home/user1`

which has enabled encryption, `keylocation=prompt`, `keyformat=passphrase`, HOWEVER it has `canmount=noauto`, then the initramfs script :

`scripts/zfs`

blocks the boot process and tries to decrypt and mount this dataset.

The problem is that the script checks for `canmount=no` but ignores `canmount=noauto`

The idea is to have UNencrypted root dataset and child datasets which have sensitive data to be encrypted. 

I know that as a workaround I can move the encrypted datasets otside of the root. I prefer not to as I'd like to have easy rollback and easy backups for everything under `rpool/hm/root`

**Comment by GregorKopka** [comment]
> The problem is that the script checks for `canmount=no` but ignores `canmount=noauto`

To be able to boot multiple things from one pool the behaviour to mount the `canmount=noauto` children of the root dataset is a _good_ thing, it'll mount the related datasets of the system that is being booted while skipping the ones from all the other systems. This allows to recursively clone a system and boot it without having to modify it.

So I disagree with this issue: current behavior is IMHO exactly as it needs to be, /home shouldn't be stored as a child dataset of the OS in a zfs root setup.

**Comment by deliank** [comment]
> This allows to recursively clone a system and boot it without having to modify it.

What does cloning have to do with mounting ?!

**Comment by GregorKopka** [comment]
I was stating a use case of mine (directly boot, without having to modify eg. fstab beforehand, a cloned OS install dataset hirarchy) that would go defunct in case the current, IMHO perfectly fine, behavior would change.

**Comment by rlaager** [comment]
This is not a supported configuration. If you're interested in making this a supportable scenario, the initramfs code would need modifications to check for encryption roots under the rootfs and prompt for their keys.
