### ISSUE TITLE
l2arc_noprefetch weird behaviour, documentation wrong?

### ISSUE THREAD

**Issue by zviratko** [zfsonlinux/zfs#9642]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu
Distribution Version	| 19.04
Linux Kernel	| 5.0.0-36-generic
Architecture	| x86_64
ZFS Version	| 0.8.2-1
SPL Version	| 0.8.2-1

I am seeing weird behaviour with this setting.
I was testing my pool speed with regular dd over big (30G+, much bigger than ARC) files and noticed that setting l2arc_noprefetch=1 results in no lookups in l2arc even when blocks are already in there and yet I am still seeing writes to l2arc with this setting applied (the pool is otherwise mostly idle).

I am testing this with "dd if=$file of=/dev/null bs=4M". This should(?) result in prefetch being used and not missing, right? (No idea, maybe it's not prefetch, but then why doesn't it even _read_ from there with this setting applied?)

In any case, the docs say:

Disables writing prefetched, but unused, buffers to cache devices.

but it looks like it should at least say:

Disables looking up prefetched blocks in cache devices or caching them therein.

**Comment by richardelling** [comment]
nit, your benchmark will prefetch, but then the blocks are used, so l2arc_noprefetch doesn't apply.

**Comment by zviratko** [comment]
So why does setting l2arc_noprefetch=1 immediately stop hitting my cache devices and start hitting the data drives?

**Comment by richardelling** [comment]
I'm not sure, 1 (true) is the default, so if what you say is true then no l2arc would ever work.

Think of it this way, if the block is prefetched, but not used, then it won't be eligible to write to l2arc.  

For reads, if l2arc_noprefetch == 1 and the block is prefetched, then it won't be read from l2arc. This could result in the prefetcher reading from the pool. Typically this is not a problem because the ZIO scheduler sets prefetch reads at low priority, so real demand reads will push out the prefetch reads.

**Comment by zviratko** [comment]
My system is mostly idle (it's a home NAS), and my cache devices were not utilized at all, so I run with 0 by default.

Yes, it seems very strange to me but your explanation makes sense and is probably what I am seeing. (Although wouldn't it be beneficial to always read the blocks from l2arc if present?)
Sorry about the confusion, I'm going to close this non-issue...

**Comment by richardelling** [comment]
This is old code and likely not exposed to very much experimentation. However, now we should be able to see the behaviour using `zpool iostat -wv`

**Comment by kpande** [comment]
and as a note, for extremely slow data vdevs it is useful to have the l2arc store and use prefetched blocks if the penalty of re-retrieving these blocks when later needed (in terms of seconds or minutes, not hours) is substantial. this can mean the difference between Veeam synthetic backups taking seconds vs hours.

**Comment by richardelling** [comment]
@kpande good point, I've updated https://github.com/zfsonlinux/zfs/wiki/ZFS-on-Linux-Module-Parameters#l2arc_noprefetch
