### ISSUE TITLE
I tried to be a good guy and fix a typo in the wiki but I can't.

### ISSUE THREAD

**Issue by nixomose** [zfsonlinux/zfs#9651]
I found a typo in the zfs wiki page 
https://github.com/zfsonlinux/zfs/wiki/Custom-Packages

specifically under the
"Debian and Ubuntu"
section where it says 
"DKMS

Building rpm-based DKMS and user packages can be done as follows:"

that should probably say deb-based and not rpm-based.

I tried and tried to offer a pull request to update the wiki but github makes that impossible, and the amount of effort it would take one of you guys to make it possible would be more than just updating the typo yourself, so I offer it up an as issue.

but really. I tried to update the wiki, but forking the zfs repo, doesn't fork the wiki, cloning the zfs wiki  is possible but there's nowhere to push the branch of the fork to, to open an pr, and according to this:

http://roman-ivanov.blogspot.com/2013/11/how-to-merge-github-wiki-changes-from.html

you have to manually apply the change anyway. So it would be easier for you to just fix the typo at the source.

I apologize for wasting your time reading all this, but as far as I can tell, there's nothing I can do.
I blame github.

Happy black friday.

**Comment by gmelikov** [comment]
Thank you, fixed!
