### ISSUE TITLE
Wiki - libvirt - Update for Debian 10 (buster)

### ISSUE THREAD

**Issue by AlbanVidal** [zfsonlinux/zfs#9676]
### System information
Type | Version/Name
 --- | --- 
Distribution Name	| Debian
Distribution Version	| 10 (Buster)
Linux Kernel	| 4.19.0-6-amd64
Architecture	| x86_64
ZFS Version	| 0.8.2-2~bpo10+1
SPL Version	| 0.8.2-2~bpo10+1

### Describe the problem you're observing

Dear ZoL developpers,

The [Debian-Buster-Root-on-ZFS](https://github.com/zfsonlinux/zfs/wiki/Debian-Buster-Root-on-ZFS) page is out of date on **QEMU/KVM/XEN** section.

Indeed in Debian 10 (Buster) the libvirt daemon service name is **libvirtd** instead of **libvirt-bin**

Moreover, the `/etc/libvirt/qemu.conf` has changed and two new lines are added on section **nvram**.

Please find bellow a git patch to update the documentation.

```
From 23b066d6d749edba819128428a86242ae8112f78 Mon Sep 17 00:00:00 2001
From: Alban VIDAL <zordhak@debian.org>
Date: Wed, 4 Dec 2019 20:44:08 +0100
Subject: [PATCH] libvirt - Update for Debian 10 (buster)

---
 Debian-Buster-Root-on-ZFS.md | 6 ++++--
 1 file changed, 4 insertions(+), 2 deletions(-)

diff --git a/Debian-Buster-Root-on-ZFS.md b/Debian-Buster-Root-on-ZFS.md
index d9eea21..315ab7f 100644
--- a/Debian-Buster-Root-on-ZFS.md
+++ b/Debian-Buster-Root-on-ZFS.md
@@ -731,7 +731,9 @@ To be able to use UEFI in guests (instead of only BIOS booting), run this on the
     Uncomment these lines:
     nvram = [
        "/usr/share/OVMF/OVMF_CODE.fd:/usr/share/OVMF/OVMF_VARS.fd",
-       "/usr/share/AAVMF/AAVMF_CODE.fd:/usr/share/AAVMF/AAVMF_VARS.fd"
+       "/usr/share/OVMF/OVMF_CODE.secboot.fd:/usr/share/OVMF/OVMF_VARS.fd",
+       "/usr/share/AAVMF/AAVMF_CODE.fd:/usr/share/AAVMF/AAVMF_VARS.fd",
+       "/usr/share/AAVMF/AAVMF32_CODE.fd:/usr/share/AAVMF/AAVMF32_VARS.fd"
     ]
 
-    sudo service libvirt-bin restart
+    sudo systemctl restart libvirtd.service
-- 
2.20.1
```

As is asked in **Contributing** section I mention @rlaager for this patch.

Best regards,
Alban

**Comment by rlaager** [comment]
Thanks! Merged as aecfb58c7cf4071c0a46a043c382cbfd2c39a6f9.
