### ISSUE TITLE
resilver_restart_001 intermittently fails

### ISSUE THREAD

**Issue by jwk404** [zfsonlinux/zfs#9677]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu
Distribution Version	| 18.04
Linux Kernel	| 4.15
Architecture	| x86
ZFS Version	| 5a089773
SPL Version	| 

### Describe the problem you're observing
resilver_restart_001 fails sometimes, possibly a race in verify_restarts()

### Describe how to reproduce the problem
The test fails intermittently.

### Include any warning/errors/backtraces from the system logs
```
04:11:20.87 NOTE: expected 1 resilver start(s) after offline/online, found 1
04:11:22.08 Added handler 59 with the following properties:
04:11:22.08   pool: testpool
04:11:22.08   vdev: 8f34acbcad36f507
04:11:22.08 SUCCESS: zinject -a -d /var/tmp/file-3 -e io -T read -f 0.25 testpool
04:11:23.46 removed all registered handlers
04:11:23.46 SUCCESS: zinject -c all
04:11:23.48 NOTE: expected 1 resilver start(s) after zinject, found 1
04:11:27.93 SUCCESS: zpool sync testpool
04:11:27.94 NOTE: expected 2 resilver start(s) after resilver, found 1
04:11:27.94 expected 2 resilver start(s) after resilver, found 1
04:11:27.95 NOTE: Performing test-fail callback (/usr/share/zfs/zfs-tests/callbacks/zfs_dbgmsg.ksh)
```

**Comment by behlendorf** [comment]
I've recently noticed this as well.  @jwpoduska would you mind looking in to this, #9588 added this test case.  Here are two example failures hit by the CI.  It's failing in about 2% of CI test runs.

http://build.zfsonlinux.org/builders/Amazon%202%20x86_64%20Release%20%28TEST%29/builds/7645
http://build.zfsonlinux.org/builders/CentOS%207%20x86_64%20%28TEST%29/builds/9098

**Comment by jwpoduska** [comment]
I'm looking at it, but nothing to report yet

**Comment by Ornias1993** [comment]
@jwpoduska I opened a PR for your fix, just so it's clear to everyone there is something that might do something about this :)
