### ISSUE TITLE
cannot replace broken disk, scary kernel messages logged

### ISSUE THREAD

**Issue by willymilkytron** [zfsonlinux/zfs#9702]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu
Distribution Version	| 17
Linux Kernel	| 4.13.0-21-generic
Architecture	| 
ZFS Version	| 0.6.5.11-1ubuntu3
SPL Version	| 0.6.5.11-1ubuntu1

### Describe the problem you're observing

broken disk cant be replace, zpool replace hungs

all zpool commands after hungs too

### Describe how to reproduce the problem

have broken disk, try zpool replace with healty disk

### Include any warning/errors/backtraces from the system logs

 INFO: task txg_sync:2162 blocked for more than 120 seconds.
       Tainted: P           O    4.13.0-21-generic #24-Ubuntu
 "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
 txg_sync        D    0  2162      2 0x00000000
 Call Trace:
  __schedule+0x28b/0x890
  schedule+0x36/0x80
  io_schedule+0x16/0x40
  cv_wait_common+0xb2/0x140 [spl]
  ? wait_woken+0x80/0x80
  __cv_wait_io+0x18/0x20 [spl]
  zio_wait+0xb2/0x150 [zfs]
  dsl_pool_sync+0x30a/0x480 [zfs]
  spa_sync+0x36e/0xb20 [zfs]
  ? kvm_clock_get_cycles+0x1e/0x20
  txg_sync_thread+0x3b6/0x620 [zfs]
  ? __switch_to+0x211/0x520
  ? txg_quiesce_thread+0x3e0/0x3e0 [zfs]
  thread_generic_wrapper+0x72/0x80 [spl]
  kthread+0x125/0x140
  ? __thread_exit+0x20/0x20 [spl]
  ? kthread_create_on_node+0x70/0x70
  ? kthread_create_on_node+0x70/0x70
  ret_from_fork+0x25/0x30
 INFO: task zpool:2776 blocked for more than 120 seconds.
       Tainted: P           O    4.13.0-21-generic #24-Ubuntu
 "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
 zpool           D    0  2776   2735 0x00000000
 Call Trace:
  __schedule+0x28b/0x890
  schedule+0x36/0x80
  cv_wait_common+0x11e/0x140 [spl]
  ? wait_woken+0x80/0x80
  __cv_wait+0x15/0x20 [spl]
  txg_wait_synced+0xdd/0x130 [zfs]
  spa_vdev_config_exit+0xa6/0x1b0 [zfs]
  spa_vdev_exit+0x20/0x90 [zfs]
  spa_vdev_attach+0x30f/0x540 [zfs]
  zfs_ioc_vdev_attach+0xa5/0xc0 [zfs]
  zfsdev_ioctl+0x1ff/0x4c0 [zfs]
  do_vfs_ioctl+0xa5/0x610
  ? __do_page_fault+0x27b/0x4d0
  SyS_ioctl+0x79/0x90
  entry_SYSCALL_64_fastpath+0x1e/0xa9
 RIP: 0033:0x7f8eeb4c9ea7
 RSP: 002b:00007ffd5b95ccc8 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
 RAX: ffffffffffffffda RBX: 00007f8eeb79ac20 RCX: 00007f8eeb4c9ea7
 RDX: 00007ffd5b960300 RSI: 0000000000005a0e RDI: 0000000000000003
 RBP: 000055666ed05c00 R08: 0000000000000003 R09: 000055666ecf140c
 R10: ffffffffffffef40 R11: 0000000000000246 R12: 0000000000040000
 R13: 000000000004a410 R14: 000055666ed05bf0 R15: 0000000000000000
 INFO: task txg_sync:2162 blocked for more than 120 seconds.
       Tainted: P           O    4.13.0-21-generic #24-Ubuntu
 "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
 txg_sync        D    0  2162      2 0x00000000
 Call Trace:
  __schedule+0x28b/0x890
  schedule+0x36/0x80
  io_schedule+0x16/0x40
  cv_wait_common+0xb2/0x140 [spl]
  ? wait_woken+0x80/0x80
  __cv_wait_io+0x18/0x20 [spl]
  zio_wait+0xb2/0x150 [zfs]
  dsl_pool_sync+0x30a/0x480 [zfs]
  spa_sync+0x36e/0xb20 [zfs]
  ? kvm_clock_get_cycles+0x1e/0x20
  txg_sync_thread+0x3b6/0x620 [zfs]
  ? __switch_to+0x211/0x520
  ? txg_quiesce_thread+0x3e0/0x3e0 [zfs]
  thread_generic_wrapper+0x72/0x80 [spl]
  kthread+0x125/0x140
  ? __thread_exit+0x20/0x20 [spl]
  ? kthread_create_on_node+0x70/0x70
  ? kthread_create_on_node+0x70/0x70
  ret_from_fork+0x25/0x30
 INFO: task zpool:2776 blocked for more than 120 seconds.
       Tainted: P           O    4.13.0-21-generic #24-Ubuntu
 "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
 zpool           D    0  2776   2735 0x00000000
 Call Trace:
  __schedule+0x28b/0x890
  schedule+0x36/0x80
  cv_wait_common+0x11e/0x140 [spl]
  ? wait_woken+0x80/0x80
  __cv_wait+0x15/0x20 [spl]
  txg_wait_synced+0xdd/0x130 [zfs]
  spa_vdev_config_exit+0xa6/0x1b0 [zfs]
  spa_vdev_exit+0x20/0x90 [zfs]
  spa_vdev_attach+0x30f/0x540 [zfs]
  zfs_ioc_vdev_attach+0xa5/0xc0 [zfs]
  zfsdev_ioctl+0x1ff/0x4c0 [zfs]
  do_vfs_ioctl+0xa5/0x610
  ? __do_page_fault+0x27b/0x4d0
  SyS_ioctl+0x79/0x90
  entry_SYSCALL_64_fastpath+0x1e/0xa9
 RIP: 0033:0x7f8eeb4c9ea7
 RSP: 002b:00007ffd5b95ccc8 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
 RAX: ffffffffffffffda RBX: 00007f8eeb79ac20 RCX: 00007f8eeb4c9ea7
 RDX: 00007ffd5b960300 RSI: 0000000000005a0e RDI: 0000000000000003
 RBP: 000055666ed05c00 R08: 0000000000000003 R09: 000055666ecf140c
 R10: ffffffffffffef40 R11: 0000000000000246 R12: 0000000000040000
 R13: 000000000004a410 R14: 000055666ed05bf0 R15: 0000000000000000
 INFO: task zpool:30642 blocked for more than 120 seconds.
       Tainted: P           O    4.13.0-21-generic #24-Ubuntu
 "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
 zpool           D    0 30642   2735 0x00000000
 Call Trace:
  __schedule+0x28b/0x890
  ? get_page_from_freelist+0x9ce/0xb20
  schedule+0x36/0x80
  schedule_preempt_disabled+0xe/0x10
  __mutex_lock.isra.2+0x190/0x4e0
  ? spl_vmem_alloc+0x19/0x20 [spl]
  __mutex_lock_slowpath+0x13/0x20
  ? __mutex_lock_slowpath+0x13/0x20
  mutex_lock+0x2f/0x40
  spa_all_configs+0x5e/0x1b0 [zfs]
  zfs_ioc_pool_configs+0x23/0x50 [zfs]
  zfsdev_ioctl+0x1ff/0x4c0 [zfs]
  do_vfs_ioctl+0xa5/0x610
  ? __do_page_fault+0x27b/0x4d0
  SyS_ioctl+0x79/0x90
  entry_SYSCALL_64_fastpath+0x1e/0xa9
 RIP: 0033:0x7fb983623ea7
 RSP: 002b:00007fff050c5f88 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
 RAX: ffffffffffffffda RBX: 00007fb9838f4c20 RCX: 00007fb983623ea7
 RDX: 00007fff050c5fb0 RSI: 0000000000005a04 RDI: 0000000000000003
 RBP: 0000000000040010 R08: ffffffffffffffff R09: 00007fb984c31010
 R10: 0000000000000022 R11: 0000000000000246 R12: 0000000000041000
 R13: 0000000000040000 R14: 0000000000001000 R15: 0000000000000000
 INFO: task txg_sync:2162 blocked for more than 120 seconds.
       Tainted: P           O    4.13.0-21-generic #24-Ubuntu
 "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
 txg_sync        D    0  2162      2 0x00000000
 Call Trace:
  __schedule+0x28b/0x890
  schedule+0x36/0x80
  io_schedule+0x16/0x40
  cv_wait_common+0xb2/0x140 [spl]
  ? wait_woken+0x80/0x80
  __cv_wait_io+0x18/0x20 [spl]
  zio_wait+0xb2/0x150 [zfs]
  dsl_pool_sync+0x30a/0x480 [zfs]
  spa_sync+0x36e/0xb20 [zfs]
  ? kvm_clock_get_cycles+0x1e/0x20
  txg_sync_thread+0x3b6/0x620 [zfs]
  ? __switch_to+0x211/0x520
  ? txg_quiesce_thread+0x3e0/0x3e0 [zfs]
  thread_generic_wrapper+0x72/0x80 [spl]
  kthread+0x125/0x140
  ? __thread_exit+0x20/0x20 [spl]
  ? kthread_create_on_node+0x70/0x70
  ? kthread_create_on_node+0x70/0x70
  ret_from_fork+0x25/0x30
 INFO: task zpool:2776 blocked for more than 120 seconds.
       Tainted: P           O    4.13.0-21-generic #24-Ubuntu
 "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
 zpool           D    0  2776   2735 0x00000000
 Call Trace:
  __schedule+0x28b/0x890
  schedule+0x36/0x80
  cv_wait_common+0x11e/0x140 [spl]
  ? wait_woken+0x80/0x80
  __cv_wait+0x15/0x20 [spl]
  txg_wait_synced+0xdd/0x130 [zfs]
  spa_vdev_config_exit+0xa6/0x1b0 [zfs]
  spa_vdev_exit+0x20/0x90 [zfs]
  spa_vdev_attach+0x30f/0x540 [zfs]
  zfs_ioc_vdev_attach+0xa5/0xc0 [zfs]
  zfsdev_ioctl+0x1ff/0x4c0 [zfs]
  do_vfs_ioctl+0xa5/0x610
  ? __do_page_fault+0x27b/0x4d0
  SyS_ioctl+0x79/0x90
  entry_SYSCALL_64_fastpath+0x1e/0xa9
 RIP: 0033:0x7f8eeb4c9ea7
 RSP: 002b:00007ffd5b95ccc8 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
 RAX: ffffffffffffffda RBX: 00007f8eeb79ac20 RCX: 00007f8eeb4c9ea7
 RDX: 00007ffd5b960300 RSI: 0000000000005a0e RDI: 0000000000000003
 RBP: 000055666ed05c00 R08: 0000000000000003 R09: 000055666ecf140c
 R10: ffffffffffffef40 R11: 0000000000000246 R12: 0000000000040000
 R13: 000000000004a410 R14: 000055666ed05bf0 R15: 0000000000000000
 INFO: task zpool:30642 blocked for more than 120 seconds.
       Tainted: P           O    4.13.0-21-generic #24-Ubuntu
 "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
 zpool           D    0 30642   2735 0x00000000
 Call Trace:
  __schedule+0x28b/0x890
  ? get_page_from_freelist+0x9ce/0xb20
  schedule+0x36/0x80
  schedule_preempt_disabled+0xe/0x10
  __mutex_lock.isra.2+0x190/0x4e0
  ? spl_vmem_alloc+0x19/0x20 [spl]
  __mutex_lock_slowpath+0x13/0x20
  ? __mutex_lock_slowpath+0x13/0x20
  mutex_lock+0x2f/0x40
  spa_all_configs+0x5e/0x1b0 [zfs]
  zfs_ioc_pool_configs+0x23/0x50 [zfs]
  zfsdev_ioctl+0x1ff/0x4c0 [zfs]
  do_vfs_ioctl+0xa5/0x610
  ? __do_page_fault+0x27b/0x4d0
  SyS_ioctl+0x79/0x90
  entry_SYSCALL_64_fastpath+0x1e/0xa9
 RIP: 0033:0x7fb983623ea7
 RSP: 002b:00007fff050c5f88 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
 RAX: ffffffffffffffda RBX: 00007fb9838f4c20 RCX: 00007fb983623ea7
 RDX: 00007fff050c5fb0 RSI: 0000000000005a04 RDI: 0000000000000003
 RBP: 0000000000040010 R08: ffffffffffffffff R09: 00007fb984c31010
 R10: 0000000000000022 R11: 0000000000000246 R12: 0000000000041000
 R13: 0000000000040000 R14: 0000000000001000 R15: 0000000000000000
 INFO: task txg_sync:2162 blocked for more than 120 seconds.
       Tainted: P           O    4.13.0-21-generic #24-Ubuntu
 "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
 txg_sync        D    0  2162      2 0x00000000
 Call Trace:
  __schedule+0x28b/0x890
  schedule+0x36/0x80
  io_schedule+0x16/0x40
  cv_wait_common+0xb2/0x140 [spl]
  ? wait_woken+0x80/0x80
  __cv_wait_io+0x18/0x20 [spl]
  zio_wait+0xb2/0x150 [zfs]
  dsl_pool_sync+0x30a/0x480 [zfs]
  spa_sync+0x36e/0xb20 [zfs]
  ? kvm_clock_get_cycles+0x1e/0x20
  txg_sync_thread+0x3b6/0x620 [zfs]
  ? __switch_to+0x211/0x520
  ? txg_quiesce_thread+0x3e0/0x3e0 [zfs]
  thread_generic_wrapper+0x72/0x80 [spl]
  kthread+0x125/0x140
  ? __thread_exit+0x20/0x20 [spl]
  ? kthread_create_on_node+0x70/0x70
  ? kthread_create_on_node+0x70/0x70
  ret_from_fork+0x25/0x30
 INFO: task zpool:2776 blocked for more than 120 seconds.
       Tainted: P           O    4.13.0-21-generic #24-Ubuntu
 "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
 zpool           D    0  2776   2735 0x00000000
 Call Trace:
  __schedule+0x28b/0x890
  schedule+0x36/0x80
  cv_wait_common+0x11e/0x140 [spl]
  ? wait_woken+0x80/0x80
  __cv_wait+0x15/0x20 [spl]
  txg_wait_synced+0xdd/0x130 [zfs]
  spa_vdev_config_exit+0xa6/0x1b0 [zfs]
  spa_vdev_exit+0x20/0x90 [zfs]
  spa_vdev_attach+0x30f/0x540 [zfs]
  zfs_ioc_vdev_attach+0xa5/0xc0 [zfs]
  zfsdev_ioctl+0x1ff/0x4c0 [zfs]
  do_vfs_ioctl+0xa5/0x610
  ? __do_page_fault+0x27b/0x4d0
  SyS_ioctl+0x79/0x90
  entry_SYSCALL_64_fastpath+0x1e/0xa9
 RIP: 0033:0x7f8eeb4c9ea7
 RSP: 002b:00007ffd5b95ccc8 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
 RAX: ffffffffffffffda RBX: 00007f8eeb79ac20 RCX: 00007f8eeb4c9ea7
 RDX: 00007ffd5b960300 RSI: 0000000000005a0e RDI: 0000000000000003
 RBP: 000055666ed05c00 R08: 0000000000000003 R09: 000055666ecf140c
 R10: ffffffffffffef40 R11: 0000000000000246 R12: 0000000000040000
 R13: 000000000004a410 R14: 000055666ed05bf0 R15: 0000000000000000
root@milkyyy:~# dmesg | colrm 1 15
INFO: task txg_sync:2162 blocked for more than 120 seconds.
      Tainted: P           O    4.13.0-21-generic #24-Ubuntu
"echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
txg_sync        D    0  2162      2 0x00000000
Call Trace:
 __schedule+0x28b/0x890
 schedule+0x36/0x80
 io_schedule+0x16/0x40
 cv_wait_common+0xb2/0x140 [spl]
 ? wait_woken+0x80/0x80
 __cv_wait_io+0x18/0x20 [spl]
 zio_wait+0xb2/0x150 [zfs]
 dsl_pool_sync+0x30a/0x480 [zfs]
 spa_sync+0x36e/0xb20 [zfs]
 ? kvm_clock_get_cycles+0x1e/0x20
 txg_sync_thread+0x3b6/0x620 [zfs]
 ? __switch_to+0x211/0x520
 ? txg_quiesce_thread+0x3e0/0x3e0 [zfs]
 thread_generic_wrapper+0x72/0x80 [spl]
 kthread+0x125/0x140
 ? __thread_exit+0x20/0x20 [spl]
 ? kthread_create_on_node+0x70/0x70
 ? kthread_create_on_node+0x70/0x70
 ret_from_fork+0x25/0x30
INFO: task zpool:2776 blocked for more than 120 seconds.
      Tainted: P           O    4.13.0-21-generic #24-Ubuntu
"echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
zpool           D    0  2776   2735 0x00000000
Call Trace:
 __schedule+0x28b/0x890
 schedule+0x36/0x80
 cv_wait_common+0x11e/0x140 [spl]
 ? wait_woken+0x80/0x80
 __cv_wait+0x15/0x20 [spl]
 txg_wait_synced+0xdd/0x130 [zfs]
 spa_vdev_config_exit+0xa6/0x1b0 [zfs]
 spa_vdev_exit+0x20/0x90 [zfs]
 spa_vdev_attach+0x30f/0x540 [zfs]
 zfs_ioc_vdev_attach+0xa5/0xc0 [zfs]
 zfsdev_ioctl+0x1ff/0x4c0 [zfs]
 do_vfs_ioctl+0xa5/0x610
 ? __do_page_fault+0x27b/0x4d0
 SyS_ioctl+0x79/0x90
 entry_SYSCALL_64_fastpath+0x1e/0xa9
RIP: 0033:0x7f8eeb4c9ea7
RSP: 002b:00007ffd5b95ccc8 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
RAX: ffffffffffffffda RBX: 00007f8eeb79ac20 RCX: 00007f8eeb4c9ea7
RDX: 00007ffd5b960300 RSI: 0000000000005a0e RDI: 0000000000000003
RBP: 000055666ed05c00 R08: 0000000000000003 R09: 000055666ecf140c
R10: ffffffffffffef40 R11: 0000000000000246 R12: 0000000000040000
R13: 000000000004a410 R14: 000055666ed05bf0 R15: 0000000000000000
INFO: task txg_sync:2162 blocked for more than 120 seconds.
      Tainted: P           O    4.13.0-21-generic #24-Ubuntu
"echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
txg_sync        D    0  2162      2 0x00000000
Call Trace:
 __schedule+0x28b/0x890
 schedule+0x36/0x80
 io_schedule+0x16/0x40
 cv_wait_common+0xb2/0x140 [spl]
 ? wait_woken+0x80/0x80
 __cv_wait_io+0x18/0x20 [spl]
 zio_wait+0xb2/0x150 [zfs]
 dsl_pool_sync+0x30a/0x480 [zfs]
 spa_sync+0x36e/0xb20 [zfs]
 ? kvm_clock_get_cycles+0x1e/0x20
 txg_sync_thread+0x3b6/0x620 [zfs]
 ? __switch_to+0x211/0x520
 ? txg_quiesce_thread+0x3e0/0x3e0 [zfs]
 thread_generic_wrapper+0x72/0x80 [spl]
 kthread+0x125/0x140
 ? __thread_exit+0x20/0x20 [spl]
 ? kthread_create_on_node+0x70/0x70
 ? kthread_create_on_node+0x70/0x70
 ret_from_fork+0x25/0x30
INFO: task zpool:2776 blocked for more than 120 seconds.
      Tainted: P           O    4.13.0-21-generic #24-Ubuntu
"echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
zpool           D    0  2776   2735 0x00000000
Call Trace:
 __schedule+0x28b/0x890
 schedule+0x36/0x80
 cv_wait_common+0x11e/0x140 [spl]
 ? wait_woken+0x80/0x80
 __cv_wait+0x15/0x20 [spl]
 txg_wait_synced+0xdd/0x130 [zfs]
 spa_vdev_config_exit+0xa6/0x1b0 [zfs]
 spa_vdev_exit+0x20/0x90 [zfs]
 spa_vdev_attach+0x30f/0x540 [zfs]
 zfs_ioc_vdev_attach+0xa5/0xc0 [zfs]
 zfsdev_ioctl+0x1ff/0x4c0 [zfs]
 do_vfs_ioctl+0xa5/0x610
 ? __do_page_fault+0x27b/0x4d0
 SyS_ioctl+0x79/0x90
 entry_SYSCALL_64_fastpath+0x1e/0xa9
RIP: 0033:0x7f8eeb4c9ea7
RSP: 002b:00007ffd5b95ccc8 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
RAX: ffffffffffffffda RBX: 00007f8eeb79ac20 RCX: 00007f8eeb4c9ea7
RDX: 00007ffd5b960300 RSI: 0000000000005a0e RDI: 0000000000000003
RBP: 000055666ed05c00 R08: 0000000000000003 R09: 000055666ecf140c
R10: ffffffffffffef40 R11: 0000000000000246 R12: 0000000000040000
R13: 000000000004a410 R14: 000055666ed05bf0 R15: 0000000000000000
INFO: task zpool:30642 blocked for more than 120 seconds.
      Tainted: P           O    4.13.0-21-generic #24-Ubuntu
"echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
zpool           D    0 30642   2735 0x00000000
Call Trace:
 __schedule+0x28b/0x890
 ? get_page_from_freelist+0x9ce/0xb20
 schedule+0x36/0x80
 schedule_preempt_disabled+0xe/0x10
 __mutex_lock.isra.2+0x190/0x4e0
 ? spl_vmem_alloc+0x19/0x20 [spl]
 __mutex_lock_slowpath+0x13/0x20
 ? __mutex_lock_slowpath+0x13/0x20
 mutex_lock+0x2f/0x40
 spa_all_configs+0x5e/0x1b0 [zfs]
 zfs_ioc_pool_configs+0x23/0x50 [zfs]
 zfsdev_ioctl+0x1ff/0x4c0 [zfs]
 do_vfs_ioctl+0xa5/0x610
 ? __do_page_fault+0x27b/0x4d0
 SyS_ioctl+0x79/0x90
 entry_SYSCALL_64_fastpath+0x1e/0xa9
RIP: 0033:0x7fb983623ea7
RSP: 002b:00007fff050c5f88 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
RAX: ffffffffffffffda RBX: 00007fb9838f4c20 RCX: 00007fb983623ea7
RDX: 00007fff050c5fb0 RSI: 0000000000005a04 RDI: 0000000000000003
RBP: 0000000000040010 R08: ffffffffffffffff R09: 00007fb984c31010
R10: 0000000000000022 R11: 0000000000000246 R12: 0000000000041000
R13: 0000000000040000 R14: 0000000000001000 R15: 0000000000000000
INFO: task txg_sync:2162 blocked for more than 120 seconds.
      Tainted: P           O    4.13.0-21-generic #24-Ubuntu
"echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
txg_sync        D    0  2162      2 0x00000000
Call Trace:
 __schedule+0x28b/0x890
 schedule+0x36/0x80
 io_schedule+0x16/0x40
 cv_wait_common+0xb2/0x140 [spl]
 ? wait_woken+0x80/0x80
 __cv_wait_io+0x18/0x20 [spl]
 zio_wait+0xb2/0x150 [zfs]
 dsl_pool_sync+0x30a/0x480 [zfs]
 spa_sync+0x36e/0xb20 [zfs]
 ? kvm_clock_get_cycles+0x1e/0x20
 txg_sync_thread+0x3b6/0x620 [zfs]
 ? __switch_to+0x211/0x520
 ? txg_quiesce_thread+0x3e0/0x3e0 [zfs]
 thread_generic_wrapper+0x72/0x80 [spl]
 kthread+0x125/0x140
 ? __thread_exit+0x20/0x20 [spl]
 ? kthread_create_on_node+0x70/0x70
 ? kthread_create_on_node+0x70/0x70
 ret_from_fork+0x25/0x30
INFO: task zpool:2776 blocked for more than 120 seconds.
      Tainted: P           O    4.13.0-21-generic #24-Ubuntu
"echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
zpool           D    0  2776   2735 0x00000000
Call Trace:
 __schedule+0x28b/0x890
 schedule+0x36/0x80
 cv_wait_common+0x11e/0x140 [spl]
 ? wait_woken+0x80/0x80
 __cv_wait+0x15/0x20 [spl]
 txg_wait_synced+0xdd/0x130 [zfs]
 spa_vdev_config_exit+0xa6/0x1b0 [zfs]
 spa_vdev_exit+0x20/0x90 [zfs]
 spa_vdev_attach+0x30f/0x540 [zfs]
 zfs_ioc_vdev_attach+0xa5/0xc0 [zfs]
 zfsdev_ioctl+0x1ff/0x4c0 [zfs]
 do_vfs_ioctl+0xa5/0x610
 ? __do_page_fault+0x27b/0x4d0
 SyS_ioctl+0x79/0x90
 entry_SYSCALL_64_fastpath+0x1e/0xa9
RIP: 0033:0x7f8eeb4c9ea7
RSP: 002b:00007ffd5b95ccc8 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
RAX: ffffffffffffffda RBX: 00007f8eeb79ac20 RCX: 00007f8eeb4c9ea7
RDX: 00007ffd5b960300 RSI: 0000000000005a0e RDI: 0000000000000003
RBP: 000055666ed05c00 R08: 0000000000000003 R09: 000055666ecf140c
R10: ffffffffffffef40 R11: 0000000000000246 R12: 0000000000040000
R13: 000000000004a410 R14: 000055666ed05bf0 R15: 0000000000000000
INFO: task zpool:30642 blocked for more than 120 seconds.
      Tainted: P           O    4.13.0-21-generic #24-Ubuntu
"echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
zpool           D    0 30642   2735 0x00000000
Call Trace:
 __schedule+0x28b/0x890
 ? get_page_from_freelist+0x9ce/0xb20
 schedule+0x36/0x80
 schedule_preempt_disabled+0xe/0x10
 __mutex_lock.isra.2+0x190/0x4e0
 ? spl_vmem_alloc+0x19/0x20 [spl]
 __mutex_lock_slowpath+0x13/0x20
 ? __mutex_lock_slowpath+0x13/0x20
 mutex_lock+0x2f/0x40
 spa_all_configs+0x5e/0x1b0 [zfs]
 zfs_ioc_pool_configs+0x23/0x50 [zfs]
 zfsdev_ioctl+0x1ff/0x4c0 [zfs]
 do_vfs_ioctl+0xa5/0x610
 ? __do_page_fault+0x27b/0x4d0
 SyS_ioctl+0x79/0x90
 entry_SYSCALL_64_fastpath+0x1e/0xa9
RIP: 0033:0x7fb983623ea7
RSP: 002b:00007fff050c5f88 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
RAX: ffffffffffffffda RBX: 00007fb9838f4c20 RCX: 00007fb983623ea7
RDX: 00007fff050c5fb0 RSI: 0000000000005a04 RDI: 0000000000000003
RBP: 0000000000040010 R08: ffffffffffffffff R09: 00007fb984c31010
R10: 0000000000000022 R11: 0000000000000246 R12: 0000000000041000
R13: 0000000000040000 R14: 0000000000001000 R15: 0000000000000000
INFO: task txg_sync:2162 blocked for more than 120 seconds.
      Tainted: P           O    4.13.0-21-generic #24-Ubuntu
"echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
txg_sync        D    0  2162      2 0x00000000
Call Trace:
 __schedule+0x28b/0x890
 schedule+0x36/0x80
 io_schedule+0x16/0x40
 cv_wait_common+0xb2/0x140 [spl]
 ? wait_woken+0x80/0x80
 __cv_wait_io+0x18/0x20 [spl]
 zio_wait+0xb2/0x150 [zfs]
 dsl_pool_sync+0x30a/0x480 [zfs]
 spa_sync+0x36e/0xb20 [zfs]
 ? kvm_clock_get_cycles+0x1e/0x20
 txg_sync_thread+0x3b6/0x620 [zfs]
 ? __switch_to+0x211/0x520
 ? txg_quiesce_thread+0x3e0/0x3e0 [zfs]
 thread_generic_wrapper+0x72/0x80 [spl]
 kthread+0x125/0x140
 ? __thread_exit+0x20/0x20 [spl]
 ? kthread_create_on_node+0x70/0x70
 ? kthread_create_on_node+0x70/0x70
 ret_from_fork+0x25/0x30
INFO: task zpool:2776 blocked for more than 120 seconds.
      Tainted: P           O    4.13.0-21-generic #24-Ubuntu
"echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
zpool           D    0  2776   2735 0x00000000
Call Trace:
 __schedule+0x28b/0x890
 schedule+0x36/0x80
 cv_wait_common+0x11e/0x140 [spl]
 ? wait_woken+0x80/0x80
 __cv_wait+0x15/0x20 [spl]
 txg_wait_synced+0xdd/0x130 [zfs]
 spa_vdev_config_exit+0xa6/0x1b0 [zfs]
 spa_vdev_exit+0x20/0x90 [zfs]
 spa_vdev_attach+0x30f/0x540 [zfs]
 zfs_ioc_vdev_attach+0xa5/0xc0 [zfs]
 zfsdev_ioctl+0x1ff/0x4c0 [zfs]
 do_vfs_ioctl+0xa5/0x610
 ? __do_page_fault+0x27b/0x4d0
 SyS_ioctl+0x79/0x90
 entry_SYSCALL_64_fastpath+0x1e/0xa9
RIP: 0033:0x7f8eeb4c9ea7
RSP: 002b:00007ffd5b95ccc8 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
RAX: ffffffffffffffda RBX: 00007f8eeb79ac20 RCX: 00007f8eeb4c9ea7
RDX: 00007ffd5b960300 RSI: 0000000000005a0e RDI: 0000000000000003
RBP: 000055666ed05c00 R08: 0000000000000003 R09: 000055666ecf140c
R10: ffffffffffffef40 R11: 0000000000000246 R12: 0000000000040000
R13: 000000000004a410 R14: 000055666ed05bf0 R15: 0000000000000000

**Comment by Ornias1993** [comment]
Thats a nasty bug you got there!
But... 0.6.5.11 is about 2,5 years old now... 

This could just as well already have been patched and if there is a patch I HIGHLY doubt it's going to get backported all the way to 0.6.5....

**Comment by behlendorf** [comment]
@willymilkytron if possible I'd suggest updating to Ubuntu 18.04 which contains a newer version of ZFS.

Aside from building a custom ZFS version for the Ubuntu release you're running there's not much we can do upstream.  We've definitely addressed an issue similar to one you're encountered in updated versions.  Sorry you ran in to this!
