### ISSUE TITLE
Allow creating a snapshot from an existing snapshot

### ISSUE THREAD

**Issue by deviantintegral** [zfsonlinux/zfs#9721]
### Describe the problem you're observing

I have zfs-auto-snapshot running, creating periodical snapshots of datasets. It would be useful to be able to create additional snapshots using a snapshot as the source. For example, perhaps an admin is asked to recover files which are only in one of the `-frequent` snapshots. Today, their options are:

* Clone the snapshot to a dataset, and make a snapshot of the clone
* Rename the snapshot and hold it (however, you may lose the context of how the snapshot was generated, and other admins looking for it may be surprised to see it "missing").

It would be a better user experience if you could just create snapshots from snapshots, as if they were created at exactly the same time.

**Comment by kpande** [comment]
er, no, you can use the `.zfs/snapshots` hidden pseudo-directory if `snapdir` is `visible`.

**Comment by rlaager** [comment]
It's not possible to go back and create snapshots retroactively. A snapshot is defined by its TXG number, and we will have moved on from that TXG.

**Comment by deviantintegral** [comment]
Thanks for the explanation!
