### ISSUE TITLE
Update Building-ZFS dependencies

### ISSUE THREAD

**Issue by rlaager** [zfsonlinux/zfs#9722]
This is referencing: https://github.com/zfsonlinux/zfs/wiki/Building-ZFS

The following was originally posted by @behlendorf in https://github.com/zfsonlinux/zfs/issues/9036#issuecomment-512900782

> Does Building ZFS list outdated dependencies? ... should they be weeded? ... or marked "optional"?

Thanks for taking a close look at this.  Let me see if I can shed some light on these dependencies.  The following pertains to the 0.8.1.  We should make sure to update our documentation accordingly.

* __libblkid-dev__ - Required by `zpool import` to consult the blkid to local ZFS member devices.
* __libuuid-dev__ - Required by internal `libefi` convenience library and the `zed` daemon.
* __libudev-dev__ - Required by the `zed` to detect when a device has been removed.
*  __libssl-dev__ - Required for the encryption feature.
* __zlib1g-dev__ - Required for gzip compression feature.
* __libelf-dev__ - Required by kernel as of linux-4.14, see the discussion [here](https://patchwork.kernel.org/patch/10059179/).  It should be pulled in by the kernel dev packages.
* __libaio-dev__ - Required by the test suite to test libaio support.

The following library are optional but will result in some supporting being disabled:

* __python3-cffi python3-setuptools python3-sphinx python3-all-dev__ - Required to build `pyzfs` support

The following should no longer be needed and can be pruned.

* __libattr1-dev__ - Used to be required by xattr test cases,
* __libselinux1-dev__ - Used to be required to manage selinux contexts
*  __libdevmapper-dev__ - Used to be required by `zpool` command.
*  __libacl1-dev__ - This appears to have never been needed.

**Comment by behlendorf** [comment]
@rlaager thanks for reminding me about this.  I've gone ahead and updated the [Build ZFS](https://github.com/zfsonlinux/zfs/wiki/Building-ZFS) and [Custom Packages](https://github.com/zfsonlinux/zfs/wiki/Custom-Packages) wiki pages.  I made the following high level changes:

* The dependencies are now consistent between the pages.
* Updated documentation to make it clear they the dependencies are for the 0.8.x releases. 
* Collapsed all the build requirements down on to a single line which is easy to cut and paste.
* Moved ZTS requirements down in to the testing section.
* Manually verified the listed requirements are correct for CentOS 7, Fedora 31, and Ubuntu 18.04.  They should be correct for other releases of these distributions.
