### ISSUE TITLE
version of master branch is older than 0.8.2

### ISSUE THREAD

**Issue by 12101111** [zfsonlinux/zfs#9754]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Gentoo Linux
Distribution Version	|  
Linux Kernel	| linux-5.4.5-gentoo
Architecture	| amd64
ZFS Version	| 
SPL Version	| 

### Describe the problem you're observing

https://github.com/zfsonlinux/zfs/blob/master/META  : 
`Linux-Maximum: 5.1`
`Version:       0.8.0`

This prevent me building master branch against Linux 5.4.

**Comment by behlendorf** [comment]
This information is advisory and should not prevent the build.  It sounds as is there a new kabi change in the 5.4 kernels which needs to be investigated.  But we certainly can bump the Linux-Maximum to 5.3 in master until the 5.4 issue is understood and fixed.

**Comment by MasterCATZ** [comment]
why is the master listed as Version: 0.8.0 when it should be higher than 0.8.2 from last year ?

**Comment by behlendorf** [comment]
The `git describe` version number is authoritative here, the version in the META file is used for tagged releases.
