### ISSUE TITLE
can't review, comment, or see any activity by Ornias1993 on the tracker

### ISSUE THREAD

**Issue by ptx0** [zfsonlinux/zfs#9757]
This guy submitted a PR to change the Pull Request Template guidelines and then seemingly locked it from review, or, github just having some troubles, but a couple things:

I never get any emails from Github when they submit a PR or any other activity

There are typos in the pull request that can not be reviewed

Can you look into this and maybe NOT disallow review comments on pull requests? Thanks!

**Comment by behlendorf** [comment]
If you're experiencing problems it must be on the Github side.  As a project we have not locked any of the PRs to prevent review.  You should be able to add comments, the PR you referenced does already have one reviewer, and I verified I'm able to add comments as well.  You may want to give it another try.

As for notifications again this isn't something which the project itself has much control over.  I can only point you at the relevant Github documentation.

https://help.github.com/en/github/receiving-notifications-about-activity-on-github/managing-your-notifications

**Comment by ptx0** [comment]
okay, I reached out to Github support who says @Ornias1993 has something wrong with their account and they must contact Github.

**Comment by ptx0** [comment]
[screenshot](https://imgur.com/iydLrr6.png)

**Comment by ptx0** [comment]
@behlendorf can you reopen this until i'm able to leave review comments on their PR

**Comment by behlendorf** [comment]
I've reopened this PR for now.

**Comment by Ornias1993** [comment]
@behlendorf
Github prevents blocked users to comment. I blocked this duplicate account of @kpande due to previous repeated behavior against me and others which I personally classify as abusive.

There is nothing "wrong" with my account, I just blocked them.

I find it VERY bad form to handle this publically on an issuetracker. This should've been forwarded to the CoD workgroup.

**Comment by kpande** [comment]
well blocking other contributors from commenting on your contributions is poor form, i don't know what exactly your problem is here, but it's too bad you are such a dick.

**Comment by mschilli87** [comment]
@kpande 
> ... you are such a dick.

Point in case.
Personnally, @kpande's behaviour on this issue tracker is a reason for me to mostly silently follow this repo without commenting.
And the complete lack of any official response/sanction shows the true (non-)worth of the so much debated CoC. :disappointed: 
On most communities, sock-puppet acocunts per se are enough to ban a user (all accounts).
And no matter how valuable the contributions of a single user may be, toxic bahaviour can stop many more from joining the communty (or make them leave).

@Ornias1993 
> **I'm not going to add any more comment on the issue**

Me neither (and likely not on others as well).

**Comment by kpande** [comment]
> Personnally, @kpande's behaviour on this issue tracker is a reason for me to mostly silently follow this repo without commenting.

i didn't realise i have such a profound impact on this community despite mostly ceasing involvement back in May, what the fuck are you talking about?

**Comment by kpande** [comment]
mostly i find the response from @mschilli87 to be a dramatic cry for attention from the developers, it has nothing to do with my desire to review some typos in the PR.

**Comment by newtothis698** [comment]
@mschilli87 this wasn't a debate about whether you find my presence unappealing, it's about being able to review a PR, which I had to create a new account to do. I will create new accounts as many times as I need to review the code..
