### ISSUE TITLE
moderated posts to mailing list

### ISSUE THREAD

**Issue by ptx0** [zfsonlinux/zfs#9758]
Since the beginning of the year when the mailing lists were migrated, the powers that be put me into shadow banned mode so that everything I submit to the list is put into a submission queue that someone eventually takes forever to review and submit to the list. So, yeah, If you could so kindly remove me from the shitlist so that my posts make it to the list in time to help users, that would be greaaaaat. Thaaaaaanks.

**Comment by behlendorf** [comment]
As we've stated before, the mailing list holds messages for moderation if they are sent from email address which are not subscribed to the list.  All of your messages which have been held were sent from an unsubscribed email address.  I've gone ahead and added the kash@tripleback.net as a secondary address for the address which is registered.  Perhaps that will help.

**Comment by ptx0** [comment]
I have re-subscribed three times now, thank you.

**Comment by drescherjm** [comment]
Should the email address be removed from the above comment?

**Comment by ptx0** [comment]
of course i'm going to get spam because of this, it's not like anyone else cares.

**Comment by behlendorf** [comment]
I've removed the address.

**Comment by mschilli87** [comment]
@behlendorf: Maybe you also want to delete the inital version from the edit history of your comment (see https://help.github.com/en/github/building-a-strong-community/tracking-changes-in-a-comment#deleting-sensitive-information-from-a-comments-history)?
