### ISSUE TITLE
[Feature] Compression: Make QAT offload algorithm independent

### ISSUE THREAD

**Issue by Ornias1993** [zfsonlinux/zfs#9760]
## Describe the problem you're observing
In the current version of ZFS QAT offload is only possible with GZIP and will offload to Software/CPU GZIP when failed.

However, considering CEPH already does this, It should be possible to make it offload with multiple algorithms or even make it algorith independent. For example CEPH already enables offload for LZ4.

Byond combining it with current algorithms future use of such a feature might be:
- ZSTD + QAT offload
- Adaptive Compression including QAT offload
- removal of software/cpu GZIP

## References
https://docs.ceph.com/docs/master/radosgw/qat-accel/

**Comment by behlendorf** [comment]
Perhaps @wli5 can comment on the feasibility of this.  But it's my understanding that the current generation of QAT hardware does not support LZ4 offload.  The limitations of the user space [QATzip](https://github.com/intel/QATzip#introduction) library used by Ceph may be different.

**Comment by Ornias1993** [comment]
@behlendorf 
After checking in-code it seems that CEPH is doing it differently.
Currently if QAT fails, it falls back to CPU GZIP on zfs.

How they support QAT with LZ4 is just falling back to $insert-other-algorithm

I doesn't support LZ4, it just falls back to lz4...

**Comment by wli5** [comment]
Currently in ZFS, QAT is under GZIP compression method, to support your request we need to create a new "qat" compression method, e.g., "zfs set compression=qat tank", with this new compression method, everything (offloading, fallback, etc.) will be handled by qat API. In theory we can do it, but for now I'd prefer to keep current design, it is clean, simple and compatible with SW.

**Comment by Ornias1993** [comment]
@wli5 Okey, understandable, could you explain how common fallback to cpu/software actually is in practice?

**Comment by wli5** [comment]
@Ornias1993 it is not common, the fallback happens when the QAT hardware has failure when compress a block of data.

**Comment by Ornias1993** [comment]
@wli5 Thanks for the info. So other fallback has close to zero priority :)
Closing..
