### ISSUE TITLE
segfault caused by recent commit (missing nullcheck)

### ISSUE THREAD

**Issue by BrainSlayer** [zfsonlinux/zfs#9770]
to make it short. https://github.com/zfsonlinux/zfs/commit/9fb2771aa5f53a14f8c30dca6b9f609d192e50f6 causes a segfault in all current tests. i added a inline comment. the return of getenv("TERM") might be NULL, but this is not checked, so the code will crash if TERM is not specified

**Comment by behlendorf** [comment]
This NULL return is handled [here](https://github.com/zfsonlinux/zfs/commit/9fb2771aa5f53a14f8c30dca6b9f609d192e50f6#diff-a032bbeb60ca2bebce124ecb6e876989R1928), or are you referring to somewhere else in the code?

**Comment by BrainSlayer** [comment]
@behlendorf no. there is a reason that i closed it immediatly after opening. on second review i found out that i have overseen it. but there must be still something bad with the code since libzpool segfaults in test since this commit
