### ISSUE TITLE
Setting zfs_vdev_scheduler to none doesn't change scheduler on CentOS8

### ISSUE THREAD

**Issue by serg-ku** [zfsonlinux/zfs#9778]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| CentOS
Distribution Version	| 8
Linux Kernel	| 4.18.0-80.11.2.el8_0.x86_64
Architecture	| x86_64
ZFS Version	| 0.8.2-1
SPL Version	| 0.8.2-1

### Describe the problem you're observing
In CentOS 8 noop scheduler was renamed to none, so zfs needs "none" scheduler to be set on devices, default zfs_vdev_scheduler is noop, so I've tried to set in modprobe config:
options zfs zfs_vdev_scheduler=none
After reboot arc_summary shows correct zfs_vdev_scheduler, but all disks still using mq-deadline.
Of course zfs is using whole devices in this case.

### Describe how to reproduce the problem
set options zfs zfs_vdev_scheduler=none in /etc/modprobe.d/zfs.conf
reboot
check arc_summary or cat /sys/module/zfs/parameters/zfs_vdev_scheduler it will show "none"
finally check scheduler for zfs disks:
cat /sys/block/_DEVICE_/queue/scheduler 
it'll show "mq-deadline", but should be "none"

I've temporary made workaround via udev rule:
ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/scheduler}="none"

**Comment by behlendorf** [comment]
For exactly this reason the `zfs_vdev_scheduler` property is being retired, 9e17e6f2541c69a7a5e0ed814a7f5e71cbf8b90a.  It's recommended that users switch to a udev rule to set the scheduler as you've done.  See issue #9609 for additional details.

**Comment by serg-ku** [comment]
Thank you for pointing this out, while searching I haven't identified this issue as relevant for, sorry.
Also I've seen a some issues where mq-deadline was suspected to be the cause and decided to switch to none, as it was many years before, in #9609 you mentioned, that none and mq-deadline performs well, so mq-deadline can be considered safe now? Would you recommend not touching default scheduler?
Thanks!

**Comment by behlendorf** [comment]
> Would you recommend not touching default scheduler?

That's right, these days the default scheduler works well for most common configurations and hardware.  Unless you're encountering a specific problem, or have clearly measured a performance improvement for your workload, my recommendation would be to leave the default scheduler.

There were suspicions that implicated mq-deadline when the kernel first introduced multiqueue support.  However, the upstream kernel appears to have sorted this out and it's no longer and issue with modern kernels.

**Comment by RubenKelevra** [comment]
@serg-ku wrote:

> ### Describe the problem you're observing
> In CentOS 8 noop scheduler was renamed to none, so zfs needs "none" scheduler to be set on devices, default zfs_vdev_scheduler is noop, so I've tried to set in modprobe config:
> options zfs zfs_vdev_scheduler=none
> After reboot arc_summary shows correct zfs_vdev_scheduler, but all disks still using mq-deadline.
> Of course zfs is using whole devices in this case.

Just to correct the misconception here:

`noop` and `none` are __not__ the same thing, so it's not a rename. Both are available next to each other until Linux 6.0 and they work completly different. The only thing they have in common is, that it's just a FIFO-Queue - nothing inside the queue will be reordered.

The difference is, that `none` works on the modern multi-thread framework for IO and `noop` works like `CFQ` or `multiqueue` as single thread.

So it's fine to use each of them - if only one is available.. If both are available `none` is the better option.
