### ISSUE TITLE
wiki: shimx64 vs. grubx64 EFI variance in documentation procedure

### ISSUE THREAD

**Issue by fermulator** [zfsonlinux/zfs#9785]
@rlaager 

### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu 
Distribution Version	| 18.04.3 LTS
Linux Kernel	| 4.15.0-70-generic
Architecture	| x64
ZFS Version	| 0.7.5
SPL Version	| 0.7.5

### Describe the problem you're observing

After completing https://github.com/zfsonlinux/zfs/wiki/Ubuntu-18.04-Root-on-ZFS, on an EFI based system (IBM x3550 M3), with ZFS mirror boot disks, the procedure leveraging `grub-install` (early steps) and subsequetnly the `efibootmgr` (later steps) to deal with >1 disk in the mirror boot pool results in two different targets for EFI boot to grub.

```
# efibootmgr -v | grep ubuntu
Boot0011* ubuntu	HD(2,GPT,5b7cfaa4-dad4-4b4e-9cf4-3fd7a7a7a918,0x800,0x100000)/File(\EFI\ubuntu\shimx64.efi)
Boot0012* ubuntu-2	HD(2,GPT,26e9def0-9629-4210-9c2a-a23d638dbaff,0x800,0x100000)/File(\EFI\ubuntu\grubx64.efi)
```

As per https://askubuntu.com/questions/342365/what-is-the-difference-between-grubx64-and-shimx64, I learned that the `shimx64` is for secure boot (and is likely the default by `grub-install`, whereas `grubx64` is the binary itself for GRUB (and is how our `efibootmgr` command is crafted.

So the goal of this is to consider attaining consistency in the instructions.  On secure-boot systems, presumably we MUST use `shimx64` (which by default `grub-install` will achieve for us), however on normal EFI (non-secure-boot) systems, the default `grubx64` is fine... (did not propose any patch here as I think it requires some consideration/thought).

In my case, I am only running zfsonlinux as root boot for Ubuntu, ... no secure-boot setup on the system, so the instructions worked, though resulted in an inconsistent target for my two disks.

In another case, they MAY require secure boot, in which case only the first disk will work (and if it fails, the system would suddenly be unable to boot).

Is there any harm in defaulting to the `shimx64` always?

### Describe how to reproduce the problem

Follow the above-mentioned procedure for:
* EFI boot
* x64
* zfs mirror

And consider the scenarios
1. EFI
2. UEFI
3. UEFI + secure-boot

FOCUS:
* `grub-install --target= ...` https://github.com/zfsonlinux/zfs/wiki/Ubuntu-18.04-Root-on-ZFS#step-5-grub-installation
vs.
* `efibootmgr ...` https://github.com/zfsonlinux/zfs/wiki/Ubuntu-18.04-Root-on-ZFS#step-6-first-boot

### Include any warning/errors/backtraces from the system logs
N/A

**Comment by rlaager** [comment]
My 18.04 system is using grubx64.efi (and does not have shim installed), but systems I have installed recently (even without Root-on-ZFS) are using shimx64.efi. So I've changed this to use shimx64.efi unconditionally. Thanks!
