### ISSUE TITLE
ZFS 0.8.2 starts scrub and looses drives

### ISSUE THREAD

**Issue by OverLocker** [zfsonlinux/zfs#9816]
Hello,
After update to 0.8.2 from 0.7.13 i get issue when zfs automaticaly starts scrub and looses different drives from pool. When i stop scrub, reload zfs-import and start scrub manually, nothing bad happends. It happends with two other pool (RAIDZ2 on 4 disks and mirror with 2 Disks)
Please check. I can send any needed information to help to find issue quickly.
Thanks.

> modinfo zfs | grep -iw version
version:        0.8.2-r2-gentoo

> modinfo spl | grep -iw version
version:        0.8.2-r2-gentoo

> lsb_release -a
LSB Version:    n/a
Distributor ID: Gentoo
Description:    Calculate Scratch Server 20
Release:        n/a
Codename:       n/a

> uname -a
Linux NAS02 4.19.86-gentoo #2 SMP Sun Jan 5 18:23:19 MSK 2020 x86_64 Intel(R) Core(TM) i3-3210 CPU @ 3.20GHz GenuineIntel GNU/Linux

**Comment by AndCycle** [comment]
@OverLocker 
I suggest you take the problem to mailing list first
https://zfsonlinux.topicbox.com/groups/zfs-discuss

people there can help you identify some basic issue.

**Comment by Ornias1993** [comment]
To add a little explaination to the great advice by @AndCycle :
The issue tracker is mostly meant for problems that are somewhat confirmed to be a code-related (documentation =/= code in this case).

If an issue might be more layer 8 (user) related, it's heavily adviced to ask in the mailing list first.

Also:
If you file an issue, it would be awesome if you kept the issue form in tact and fill it out accordingly. While I understand copying and pasting those readouts gives us the same info, it's helpfull if everyone keeps to the same format (and included form) so we can see at one glance what the specs of a specific issue are.

**Comment by Ornias1993** [comment]
@behlendorf You might want to close it, it's clearly a mailinglist issue and OP hasn't added additional info to the contrary.

**Comment by behlendorf** [comment]
@OverLocker my hunch would be that the newer version of ZFS is pushing your disks harder than the previous version when scrubbing.  This usually indicates that your hardware may not be up to the task of driving all the disks simultaneously.  One thing you might try is setting the `zfs_scan_legacy` module option to 1.  This will revert to using the old scrub code which may help you avoid the issue.
