### ISSUE TITLE
zfs_arc_min default, documentation, and compilation mode

### ISSUE THREAD

**Issue by cyounkins** [zfsonlinux/zfs#9838]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Arch
Distribution Version	| Rolling
Linux Kernel	| 4.20.13
Architecture	| x64
ZFS Version	| 0.7.13-1
SPL Version	| 0.7.13-1

### Describe the problem you're observing
I see on the wiki page https://github.com/zfsonlinux/zfs/wiki/ZFS-on-Linux-Module-Parameters#zfs_arc_min that `zfs_arc_min` has a default of "greater of 33,554,432 (32 MiB) and `c_max` / 2" and can be verified with "/proc/spl/kstat/zfs/arcstats entry `c_min`"

```
craig@pluto ~> cat /sys/module/zfs/parameters/zfs_arc_min
0
craig@pluto ~> cat /sys/module/zfs/parameters/zfs_arc_max
0
craig@pluto ~> cat /proc/spl/kstat/zfs/arcstats | grep '^c_'
c_min                           4    1053180544
c_max                           4    16850888704
```

My system has 32GB of RAM, so `c_max` matches the default "RAM size in bytes / 2", but `c_min` does not match its default. It does however, match the default in Oracle's documentation (https://docs.oracle.com/cd/E19253-01/817-0404/gjheb/index.html) of "1/32nd of physical memory or 64 Mbytes, whichever value is larger".

This looks to be where the default is established: https://github.com/zfsonlinux/zfs/blob/2a8ba608d3eace43010174aa4f67c8b8af4aacf3/module/zfs/arc.c#L7127

```
#ifdef	_KERNEL
	/* Set min cache to 1/32 of all memory, or 32MB, whichever is more */
	arc_c_min = MAX(allmem / 32, 2ULL << SPA_MAXBLOCKSHIFT);
#else
	/*
	 * In userland, there's only the memory pressure that we artificially
	 * create (see arc_available_memory()).  Don't let arc_c get too
	 * small, because it can cause transactions to be larger than
	 * arc_c, causing arc_tempreserve_space() to fail.
	 */
	arc_c_min = MAX(arc_c_max / 2, 2ULL << SPA_MAXBLOCKSHIFT);
#endif
```

It looks like it depends on whether it was compiled with the 'kernel' config or 'userland' config. I am using DKMS and so I think `--with-config=kernel` is passed to `configure` for my build.

1. Is my understanding correct that my default `c_min` does not match the wiki page because my module was compiled `--with-config=kernel` whereas the wiki page refers to the `--with-config=user` configuration?
2. What is the purpose of the different compilation modes?

**Comment by richardelling** [comment]
fixed, please verify

**Comment by cyounkins** [comment]
Verified
