### ISSUE TITLE
CentOS 8.1 kmod packages missing

### ISSUE THREAD

**Issue by rgessner** [zfsonlinux/zfs#9856]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  CentOS
Distribution Version	| 8.1.1911
Linux Kernel	| 4.18.0
Architecture	| x86_6
ZFS Version	| 0.8.2
SPL Version	| 

### Describe the problem you're observing

Installing zfs-kmod package fails on CentOS 8.1.1911.
Furthermore working Centos8 zfs systems fail to work after update to 8.1.

### Describe how to reproduce the problem

- Install fresh Centos 8.1
- install zfs repo
- switch to zfs-kmod repo
- run "dnf install zfs"

or

- Update working CentOS 8 system with zfs (dnf update)
- reboot

### Include any warning/errors/backtraces from the system logs

Fresh install:

```
# dnf install zfs
Last metadata expiration check: 11:13:19 ago on Fri 17 Jan 2020 01:58:40 PM CET.
Error: 
 Problem: package zfs-0.8.2-1.el8.x86_64 requires zfs-kmod = 0.8.2, but none of the providers can be installed
  - conflicting requests
  - nothing provides kernel(__remove_inode_hash) = 0x8b7a4ec8 needed by kmod-zfs-0.8.2-1.el8.x86_64
  - nothing provides kernel(clear_inode) = 0x05ef95a0 needed by kmod-zfs-0.8.2-1.el8.x86_64
  - nothing provides kernel(clear_nlink) = 0x51b31641 needed by kmod-zfs-0.8.2-1.el8.x86_64
  - nothing provides kernel(current_time) = 0x79e296fb needed by kmod-zfs-0.8.2-1.el8.x86_64
  - nothing provides kernel(d_add_ci) = 0xee0c1e0d needed by kmod-zfs-0.8.2-1.el8.x86_64
  - nothing provides kernel(d_instantiate) = 0xa5b7f5db needed by kmod-zfs-0.8.2-1.el8.x86_64
  - nothing provides kernel(d_invalidate) = 0x84984326 needed by kmod-zfs-0.8.2-1.el8.x86_64
  - nothing provides kernel(d_make_root) = 0x0297e905 needed by kmod-zfs-0.8.2-1.el8.x86_64
  - nothing provides kernel(d_obtain_alias) = 0xa56bdac4 needed by kmod-zfs-0.8.2-1.el8.x86_64
  - nothing provides kernel(d_prune_aliases) = 0x91edc70b needed by kmod-zfs-0.8.2-1.el8.x86_64
  - nothing provides kernel(d_set_d_op) = 0xd41942ad needed by kmod-zfs-0.8.2-1.el8.x86_64

[...]
```  

Update from CentOS8:

```
# /sbin/modprobe zfs
modprobe: FATAL: Module zfs not found in directory /lib/modules/4.18.0-147.3.1.el8_1.x86_64

```

**Comment by StephenDart** [comment]
I can also confirm this is not working, tried on a fresh Centos8.1
The el8_1 rpm is showing on the downloads but it doesnt have any metadata for the repo so doesnt work yet, so i am guessing the packages for 8.1 arent fully built yet. 
Will watch and see if its released soon.

**Comment by markusdd** [comment]
nooooooo ... just found that. Just ran the 8.1 update because teh release package is there....
Now I cannot mount my tank...

**Comment by rgessner** [comment]
> nooooooo ... just found that. Just ran the 8.1 update because teh release package is there....
> Now I cannot mount my tank...

Just boot the last working kernel via the grub boot menu.

**Comment by theinfinityproject** [comment]
Any eta on this?
Furthermore what is to do for those who already have upgraded to Centos 8.1 if package finally arrives?

**Comment by tvtue** [comment]
+1 from here.

**Comment by theinfinityproject** [comment]
> > > nooooooo ... just found that. Just ran the 8.1 update because teh release package is there....
> > > Now I cannot mount my tank...
> > 
> > 
> > Just boot the last working kernel via the grub boot menu.
> 
> That is not guaranteed to work depending on what else you have installed. Actually my general observation with RHEL/CentOS is that older kernels do not work anymore after a major step like 8.0 to 8.1.

I can confirm it works (booting old kernel on a standard centos installation)

**Comment by behlendorf** [comment]
We expect to release packages for 8.1 in the next week or so.  Thanks for your patience.

**Comment by theinfinityproject** [comment]
> We expect to release packages for 8.1 in the next week or so. Thanks for your patience.

Thanks for the update. A question @behlendorf : For those who are already on 8.1; a simple update will do or smth like a purge and reinstall will have to take place?

**Comment by markusdd** [comment]
Thanks for the ETA. Anyway you should take down the release package so other people do not step into the same trap :D

**Comment by behlendorf** [comment]
A new release package will be posted for 8.1 once the repository is ready.  After switching to the new release package an upgrade should work, as will a purge and clean install.

**Comment by StephenDart** [comment]
Just noticed that the zfs-release.el8_1.noarch.rpm was now listed on the wiki. 
I have just installed it and all looks good. Zfs installed with no broken dependancies and i can create a pool and datasets. Zfs version is 0.8.3.1
Thanks to the devs for creating and building this.  


Type | Version/Name
-- | --
Distribution Name | CentOS
Distribution Version | 8.1.1911
Linux Kernel | 4.18.0-147.3.1.el8_1
Architecture | x86_64
ZFS Version | 0.8.3.1

**Comment by tvtue** [comment]
I did a yum update on a centos 7.7 and it worked.
I also did a rpm -Uvh on the rpm file of the repo on a centos 8.1 system. And afterwards a yum update. That also worked. 

Thank for very much providing an updated version.
