### ISSUE TITLE
addition of zfsutils-linux scrub every 2nd sunday

### ISSUE THREAD

**Issue by fermulator** [zfsonlinux/zfs#9858]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu 
Distribution Version	| 18.04.3 LTS
Linux Kernel	| 4.15.0-73-generic
Architecture	| x86_64
ZFS Version	| 0.7.5-1ubuntu16.6
SPL Version	| 0.7.5-1ubuntu2

### Describe the problem you're observing

When did this file get added into zfsonlinux ecosystem?
```
# cat /etc/cron.d/zfsutils-linux
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# Scrub the second Sunday of every month.
24 0 8-14 * * root [ $(date +\%w) -eq 0 ] && [ -x /usr/lib/zfs-linux/scrub ] && /usr/lib/zfs-linux/scrub
```

I've been a ZoL user for many years now, and have had my own cron setup tailored to distribute pool scrubs once per month, spread across the month to avoid system I/O overload on any one day of the month, like this:
```
# zfsmain scrub: 2:30AM 7th of every month
30 02 7 * * /sbin/zpool scrub zfsmain

# zstorage scrub: 2:30AM 5th of every month
30 02 5 * * /sbin/zpool scrub zstorage

# zmedia scrub: 1:00AM 14th of every month
00 01 14 * * /sbin/zpool scrub zmedia

# zstorage scrub: 2:30AM 21st of every month
30 02 21 * * /sbin/zpool scrub ztank
```

However suddenly I noticed in an adhoc check of `zpool status` that ALL my pools were scrubbed on Sunday January 12th 2020!
```
# zpool status | grep -i "scrub"
  scan: scrub repaired 0B in 0h13m with 0 errors on Sun Jan 12 00:37:31 2020
  scan: scrub repaired 0B in 11h24m with 0 errors on Tue Jan 14 12:24:33 2020  <-- (one of my own since the Jan12 mega scrub)
  scan: scrub repaired 0B in 0h45m with 0 errors on Sun Jan 12 01:09:40 2020
  scan: scrub repaired 0B in 7h10m with 0 errors on Sun Jan 12 07:34:11 2020
```

this is NOT what I had configured, so I went digging and found that zfsutil cron file :(

```
# cat /usr/lib/zfs-linux/scrub
#!/bin/sh -eu

# Scrub all healthy pools.
zpool list -H -o health,name 2>&1 | \
	awk 'BEGIN {FS="\t"} {if ($1 ~ /^ONLINE/) print $2}' | \
while read pool
do
	zpool scrub "$pool"
done
```
```
# cat /etc/cron.d/zfsutils-linux
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# Scrub the second Sunday of every month.
24 0 8-14 * * root [ $(date +\%w) -eq 0 ] && [ -x /usr/lib/zfs-linux/scrub ] && /usr/lib/zfs-linux/scrub
```

This MAY be a desirable default for some system admins, but having it suddenly appear IMO is at the same time undesirable for many.

### Describe how to reproduce the problem

1. Having been a ZoL user sys admin for many years.
2. Be a decent sys admin and know the basics, you've configured your own cron/schedule for pool scrubbing per guidelines and individual needs.
2. Follow stable upgrade channels. (for me this is Ubuntu LTS 16.04, then 18.04)
3. Suddenly after some upgrade version XX(?) your pools start scrubbing on the 2nd Sunday of every month without your having configured it or asked for that.

### Include any warning/errors/backtraces from the system logs
N/A

### Expectations

Hoping we can:
1. Confirm when and why this was rolled out to all systems by default (does the explanation make sense? is it _really_ OK to do this? how was it communicated?)
2. Ensure "how to disable" is documented and supported (i.e. if I just delete that cron file, will some future upgrade replace and re-enable it?)

**Comment by misterbigstuff** [comment]
it's in the changelog, it's better for nonexperienced users to have it scrub rather than never, and for experienced admins like yourself it is no problem to follow the changelog and remove the cron file?

**Comment by loli10K** [comment]
AFAIK `/etc/cron.d/zfsutils-linux` is part of Ubuntu's packaging and has nothing to do with upstream (#1006): this seems to have landed in the wrong bug tracker.

**Comment by fermulator** [comment]
Didn't see it anywhere in https://github.com/zfsonlinux/zfs/releases (search keyword `scrub`).

Thanks @loli10K for the ref there, definitely shows other users have a similar opinion/feeling per the sudden double-scrub. The conclusion of #1006 was clearly not to implement it in core, and rather as part of a cron configuration. (makes sense)

If `zfsutils` is actually part of Ubuntu packaging and they've introduced there own cron, then I'd be happy to move/shift this report to there (where is that btw?); I tried to determine this actually before submitting the issue report here, but could not find it.

```
$ dpkg -S /etc/cron.d/zfsutils-linux
zfsutils-linux: /etc/cron.d/zfsutils-linux

$ dpkg -s zfsutils-linux
Package: zfsutils-linux
Status: install ok installed
Priority: optional
Section: contrib/admin
Installed-Size: 1109
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Source: zfs-linux
Version: 0.7.5-1ubuntu16.6
Provides: zfsutils
Depends: libblkid1 (>= 2.16), libc6 (>= 2.14), libnvpair1linux (>= 0.7.5), libuuid1 (>= 2.16), libuutil1linux (>= 0.7.5), libzfs2linux (>= 0.7.5), libzpool2linux (>= 0.7.5), python3:any, python3
Recommends: lsb-base, zfs-zed
Suggests: nfs-kernel-server, samba-common-bin (>= 3.0.23), zfs-initramfs | zfs-dracut, zfs-modules | zfs-dkms
Breaks: zfs-dkms (>> 0.7.5-1ubuntu16.6), zfs-dkms (<< 0.7.5-1ubuntu16.6)
Conflicts: zfs, zfs-fuse, zutils
Conffiles:
 /etc/cron.d/zfsutils-linux 27db3c2e738f030ab15d717cfda8261a
 /etc/default/zfs 5483fced1e3de63c0d35f433131c4f26
 /etc/sudoers.d/zfs ad829cd4055ab2a8d41f8b5f2b564a3f
 /etc/zfs/zfs-functions 87bbaa4b01e66f8d802795e6b5fe8b59
Description: command-line tools to manage OpenZFS filesystems
 The Z file system is a pooled filesystem designed for maximum data
 integrity, supporting data snapshots, multiple copies, and data
 checksums.
 .
 This package provides the zfs and zpool commands to create and administer
 OpenZFS filesystems.
Homepage: http://www.zfsonlinux.org/
Original-Maintainer: Debian ZFS on Linux maintainers <pkg-zfsonlinux-devel@lists.alioth.debian.org>
```

Clearly owned by Ubuntu (but I don't think they have a github for it do they ... only way is that devel mailing list?)

For this project, it may warranty documentation in any or more of
* https://github.com/zfsonlinux/zfs/wiki/Admin-Documentation
* https://github.com/zfsonlinux/zfs/wiki/FAQ
* https://github.com/zfsonlinux/zfs/wiki/Ubuntu

**Comment by fermulator** [comment]
Moved to https://bugs.launchpad.net/ubuntu/+source/zfs-linux/+bug/1860228

**Comment by freqlabs** [comment]
I'll close this since the discussion has moved to the appropriate bug tracker.

**Comment by fermulator** [comment]
Wouldn't it be prudent to add this "potential problem" or "information" to the FAQ or Ubuntu-specific documentation? @freqlabs

**Comment by freqlabs** [comment]
@rlaager
