### ISSUE TITLE
Wiki: Fedora 31 DKMS requires additonal config to autobuild for new kernels

### ISSUE THREAD

**Issue by mhjacks** [zfsonlinux/zfs#9868]
The Fedora Wiki page does not mention that Fedora 31 requires some other config along with DKMS to autobuild modules on kernel upgrade.

I found this out the hard way and installed grubby (which is an effective workaround).  This bug discusses some other options and history:  https://bugzilla.redhat.com/show_bug.cgi?id=1753044

This isn't an issue with ZFS per se, it's true of any dkms module under at least Fedora 31.  But since it's a useful thing to note for Fedora users, it might be nice to note it in the wiki.  I couldn't find a way to contribute to the wiki directly which is why I'm opening this issue.

Thanks for ZFS by the way!

**Comment by behlendorf** [comment]
Would you mind suggesting some text which could be added to the wiki.  From this recent https://github.com/zfsonlinux/zfs/issues/9374#issuecomment-571669834 it sounds like ZFS is building properly on kernel upgrade in Fedora 31.  However, the initramfs still needs to be manually rebuilt.

This is a duplicate of #9374.

**Comment by mhjacks** [comment]
Yes - let me look more into the other bug and the underlying causes.  I think both issues might stemp from a similar cause.  I will see if I can figure something out to post to the wiki.  Thanks!

**Comment by mhjacks** [comment]
I have found the following technique that does not require the installation of grubby.  (Grubby owns the hooks that will run the DKMS hooks where DKMS normally installs them, but won't handle creating the dracut image correctly even so.)

As suggested in https://bugzilla.redhat.com/show_bug.cgi?id=1753044:

After installing DKMS but before installing the zfs-dkms module:
Add the following script as `/etc/kernel/install.d/40-dkms.install`:

```----- BEGIN SCRIPT /etc/kernel/install.d/49-dkms.install -----
#!/usr/bin/bash

if [[ "$1" == "add" ]]; then
	/etc/kernel/postinst.d/dkms $2
fi

if [[ "$1" == "remove" ]]; then
	/etc/kernel/prerm.d/dkms $2
fi
----- END SCRIPT -----```

Installing and running this handles the upgrade case for module building but does not appear to handle the dracut case correctly.  I'm still looking into that and will post further when I find out how to handle that correctly as well.

**Comment by mhjacks** [comment]
OK, I've looked into the initramfs issue as well.  This will work with the scriplet above, but the user has to instruct dracut (the initramfs generator in fedora) to include the ZFS module (and it's dependencies) by creating `/etc/dracut.conf.d/zfs.conf` with the following contents:

`add_drivers+="zfs"`

This will cause ZFS to be added to the initramfs during the ordinary kernel installation process.  The initramfs process runs at priority 50.  I'll add another comment with suggested wording for the wiki.

**Comment by mhjacks** [comment]
On recent Fedora (i.e. Fedora 30+), the following action will ensure that the DKMS modules are built properly on kernel installs:

Create and make executable the file `/etc/kernel/install.d/40-dkms.install` with the following contents:

```#!/usr/bin/bash

if [[ "$1" == "add" ]]; then
	/etc/kernel/postinst.d/dkms $2
fi

if [[ "$1" == "remove" ]]; then
	/etc/kernel/prerm.d/dkms $2
fi
```

This file should be created after the installation of the DKMS package but before the installation of the zfs-dkms package.

Additionally, if you want to use ZFS on root, you can enable that by creating a file `/etc/dracut.conf.d/zfs.conf` with the following contents:

`add_drivers+="zfs"`

By default, the initramfs generation process will not add the ZFS module, but this configuration will cause ZFS and its dependencies to be included in new kernels added through the normal DNF upgrade process.

The dkms package seems to depend on a slightly older plugin mechanism for kernel installation called grubby, which is no longer installed by default on Fedora 30/31.  Potential improvements to the dkms package in Fedora are being requested/tracked at https://bugzilla.redhat.com/show_bug.cgi?id=1753044.

**Comment by behlendorf** [comment]
@mhjacks thank you for doing the research on this and the clear write up.

@tonyhutter can you verify the proposed approach on Fedora and update the wiki accordingly.

**Comment by tonyhutter** [comment]
@mhjacks are you planning to submit your `49-dkms.install` fix back to dkms?  The latest bugzilla comments sound like they would be open to it: https://bugzilla.redhat.com/show_bug.cgi?id=1753044

We should also open a PR to update:
https://github.com/zfsonlinux/zfs/blob/master/contrib/dracut/README.dracut.markdown
...with your `add_drivers+="zfs"` line.

**Comment by mhjacks** [comment]
Yes.  I didn't realize that the Fedora maintainer also had commit rights upstream.  I'll take a look at both upstream and the Fedora packaging and figure out where and how best to make the changes, and post here when something is released.

**Comment by gregory-lee-bartholomew** [comment]
@mhjacks thanks for getting this fixed.

A few small footnotes:

1. I think `add_drivers+="zfs"` should be `add_drivers+=" zfs "`. If you don't put the extra spaces around the driver name, it can get merged with the name of another driver the user may have added with another `add_drivers+="xxx"` drop-in. I was burnt by this once long ago.

2. The `/etc/kernel/install.d/40-dkms.install` script should have `#!/usr/bin/bash` as its first line. Older versions of bash used to allow that to be omitted from, e.g., /etc/rc.d/rc.local. But it is sometimes required on newer versions. Especially if the script gets called by a non-bash script/executable.

3. If you are updating https://github.com/zfsonlinux/zfs/blob/master/contrib/dracut/README.dracut.markdown , maybe you could update `root=ZFS:pool/dataset` to be `root=zfs:pool/dataset` in the "Kernel Command Line" section. The upper-case notation is for labels (UUID=, PARTLABEL=, etc.). Protocols have traditionally been lower-case (iscsi:, nbd:, etc.). The zfs prefix is really a protocol, so it should be zfs:... not ZFS=.... I've been using the "zfs:" prefix for years without issue. Apparently the parser is quite forgiving and allows many variations, but it would be nice if the documentation would encourage the right format.

I know the last request is a little nit-picky. Feel free to disregard it.

Thanks again for all your work.

**Comment by gregory-lee-bartholomew** [comment]
@mhjacks actually, I just had a look at `/usr/lib/dracut/modules.d/90zfs/parse-zfs.sh` and maybe that last point isn't "nit-picky". This is what is commented in the parser:
```
# root is explicit ZFS root.  Parse it now.  We can handle
# a root=... param in any of the following formats:
# root=ZFS=rpool/ROOT
# root=zfs:rpool/ROOT
# root=zfs:FILESYSTEM=rpool/ROOT
# root=FILESYSTEM=rpool/ROOT
# root=ZFS=pool+with+space/ROOT+WITH+SPACE (translates to root=ZFS=pool with space/ROOT WITH SPACE)
```

What's currently specified in the README (`root=ZFS:pool/dataset`) may be incorrect.

**Comment by mhjacks** [comment]
@gregory-lee-bartholomew The PR I put in for DKMS already has the proper shebang line. (It got swallowed by the triple quote, it seems.)  I edited my comment above to make both fixes as you've suggested.

**Comment by mhjacks** [comment]
The fix is now upstream in DKMS and  included in the base packaging for fedora - the update has been pushed for the next stable release (f32); we're currently working on getting updates issued for f31 and f30, as well as epel7 and epel8.

**Comment by mhjacks** [comment]
Packages have been built and submitted to the Fedora updates system across f33/f32/f31/f30 and epel7 and epel8.  I'll post again here when the updates hit stable.  (It will take a week for the Fedora releases and two for the epel releases, assuming no extra karma.)

**Comment by behlendorf** [comment]
@mhjacks that's great news, thanks for the update and pushing this work forward.

**Comment by gregory-lee-bartholomew** [comment]
@mhjacks I'm sure it is too late to address this concern in this patch, but I think it might be worth mentioning here to maybe get work started on a subsequent patch.

Your current patch, as I understand it, is still referencing the old dkms scripts in `/etc/kernel/{postinst.d,prerm.d}`. Since those directories are still "owned" by the grubby package, dkms is still effectively dependent on grubby. It might be worthwhile to look into merging the content in those older dkms scripts directly into the newer 40-dkms.install script that your patch has just created rather than calling the old ones in that (deprecated?) location. It looks like the new location -- `/usr/lib/kernel/install.d` is owned by systemd, so presumably it will work with any OS that uses systemd?

**Comment by mhjacks** [comment]
@gregory-lee-bartholomew I should say rather that the current code is compatible with grubby, as opposed to dependent on it.  Simone's (i.e. slaanesh/negativo17) wanted to deploy the same version to fedora 33 (current rawhide), 32 (just branched this week), 31 and 30 (current production releases) as well as epel7 and epel8 (which both use grubby).

RPM's don't "own" directories, exactly; the files in the %files section of an RPM will be installed to their target directories; the parent directories will be created as needed (owned root:root, 755 permissions as needed).

Thus, for systems that use grubby, grubby will invoke the scripts in /etc as before.  There will be nothing to invoke the script in /usr/lib/kernel/install.d, so it will sit there as a no-op.

For non-grubby systems, the kernel-install script will call the new script, which will in turn call the "legacy" scripts designed to be called by grubby.

I agree that once grubby is no longer a factor, that the /usr script should be refactored to incorporate the contents and logic of the scripts currently in /etc.  But that may be a while, as el7 has quite a bit of life left in it.  epel8 also installs grubby by default, but may choose to stop using it at some point during its lifecycle.

For now, though, I think we will have a codebase that will do the right thing for el7/el8, as well as F30+.  I am now an admin of the Fedora dkms package, so we have the ability to make further changes to the package if needed.  I find the current solution a bit inelegant, but I think it will be good to give Fedora users a fix for this problem.

If you have a FAS account, would you mind testing the update packages and seeing if they behave correctly on the OS versions you care about?  As the update sumbitter, I can't give karma to my own updates.

If no one does anything, the current packages should hit the stable repos in a week (for the fedora releases) or two weeks (for the epel releases).

**Comment by mhjacks** [comment]
The updated DKMS package for Fedora 31 has now hit the stable update repos:  https://bodhi.fedoraproject.org/updates/FEDORA-2020-d437098f26.   Please feel free to re-open if you feel that this is premature.

**Comment by behlendorf** [comment]
@mhjacks thank you.  You may also be interested in taking a look at issue 9891 which is related to this issue.
