### ISSUE TITLE
EL6 repository has zfs 0.8 packages

### ISSUE THREAD

**Issue by goatjam** [zfsonlinux/zfs#9915]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  CentOS
Distribution Version	|  6.11
Linux Kernel	|  2.6.32-642.11.1.el6.x86_64
Architecture	| x86_64
ZFS Version	| 0.6.5.7-1
SPL Version	| 0.6.5.7-1

### Describe the problem you're observing

This appears to be a regression of issue  #9369 from 2019

Using baseurl=http://download.zfsonlinux.org/epel/6/kmod/$basearch/

When I attempt to do 'yum update zfs" on an existing system I get the following output:

---> Package zfs.x86_64 0:0.8.3-1.el6 will be obsoleting
--> Processing Dependency: sysstat for package: zfs-0.8.3-1.el6.x86_64
--> Finished Dependency Resolution
Error: Package: zfs-0.8.3-1.el6.x86_64 (zfsonlinux)
           Requires: sysstat

### Describe how to reproduce the problem

yum update

**Comment by tonyhutter** [comment]
Centos 6, 7 & 8 are supported by 0.8.3.  It looks like you may be having trouble pulling in sysstat.  Can you post the full `yum update zfs` log?

**Comment by goatjam** [comment]
Thanks Tony. You are right, I wasn't aware that RHEL6 now supported 0.8. The problem was related to my yum cache
