### ISSUE TITLE
The Debian ZFS root installation guide may fail due to missing /run/lock directory

### ISSUE THREAD

**Issue by saveriomiroddi** [zfsonlinux/zfs#9945]
(I'm filing this bug here according to the suggestion on https://github.com/zfsonlinux/zfs/wiki/Debian-Buster-Root-on-ZFS#support. Pinging @rlaager)

I've searched issues for `debian /run/lock` and `debian guide` and couldn't find anything similar, but I'm no expert (eg. could https://github.com/zfsonlinux/zfs/issues/8549 be related?).

### System information
Type | Version/Name
 --- | --- 
Distribution Name	| Debian
Distribution Version	| 10.1/10.2
Linux Kernel	| 4.19
Architecture	| amd64
ZFS Version	| zfs-0.8.2-3~bpo10+1
SPL Version	| zfs-0.8.2-3~bpo10+1

### Describe the problem you're observing

The step(s) starting with `Verify that zed updated the cache` don't yield any cache update.

### Describe how to reproduce the problem

Try to install Debian 10.1/10.2 using the guide (I'm using a slightly modified version, but the problem shouldn't be relevant to this)

### Include any warning/errors/backtraces from the system logs

Bash log (artificially introduced by me):

```
zed_lock zfs-list
local lockfile=zfs-list
local fd=8
local umask_bak
local err
'[' -n zfs-list ']'
expr zfs-list : '.*/'
lockfile=/var/lock/zfs-list
+ umask
umask_bak=0022
umask 077
eval 'exec 8> '\''/var/lock/zfs-list'\'''
+ exec
```

now, check this out:

```sh
root@debian:/# ls -l /var/lock
lrwxrwxrwx 1 root root 9 Sep  7 12:44 /var/lock -> /run/lock

root@debian:/# ls -l /run
total 5
drwxr-xr-x 2 root root  4 Feb  4 21:55 blkid
drwxr-xr-x 2 root root  4 Feb  4 21:55 mount
-rw-r--r-- 1 root root  4 Feb  4 22:33 zed.pid
-rw-r--r-- 1 root root 24 Feb  4 22:34 zed.state
```

### Diagnosis

I'm no Debian expert, but at least in the installations I've attempted, `/run/lock` doesn't exist, so the zedlet `history_event-zfs-list-cacher.sh` fails. Simply creating the directory:

```sh
mkdir /run/lock # as sudo
```

solves the issue, but I'm not expert, so I'm not sure this is the (a) correct/appropriate/clean solution.

Since `/run` is not bound (by `mount --rbind`), I suppose this problem is general, and not strictly related to my installation.

**Comment by rlaager** [comment]
I don't know why it doesn't exist in the installed environment, but that seems like a reasonable solution. Fixed in the wiki. Thanks!

**Comment by saveriomiroddi** [comment]
> I don't know why it doesn't exist in the installed environment, but that seems like a reasonable solution. Fixed in the wiki. Thanks!

I've isolated the reason - it happens when the installation is performed via Calamares rather than debootstrap (all the rest being the same).

I think using `mkdir -p` rather than `mkdir` alone would make the UX a bit smoother for systems where the directory is present (as it doesn't raise an error in such case).

**Comment by rlaager** [comment]
If you're using something other than `debootstrap` per the instructions, then you're on your own. I don't mean that in a bad way, but the HOWTOs aren't expected to cover every scenario, especially if you're swapping out key parts.

**Comment by saveriomiroddi** [comment]
> If you're using something other than `debootstrap` per the instructions, then you're on your own. I don't mean that in a bad way, but the HOWTOs aren't expected to cover every scenario, especially if you're swapping out key parts.

Sure, I understand. Thanks for your work :smile:
