### ISSUE TITLE
linux kernel changed arguments of proc_create_data and deleted timespec64_trunc

### ISSUE THREAD

**Issue by knot-indicated** [zfsonlinux/zfs#9956]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Arch linux
Distribution Version	| n/a, rolling release
Linux Kernel	| 5.5.0-09560-g4c7d00ccf40d/
Architecture	| x86_64
ZFS Version	| 81acb1edcb595a7377a6ad188c65dd23f2702ce9
SPL Version	| 81acb1edcb595a7377a6ad188c65dd23f2702ce9

### Describe the problem you're observing
Latest zfs fails to build on latest kernel, due to kernel commits [97a32539b9568bb653683349e5a76d02ff3c3e2c](https://github.com/torvalds/linux/commit/97a32539b9568bb653683349e5a76d02ff3c3e2c) and [d56c0d45f0e27f814e87a1676b6bdccccbc252e9](https://github.com/torvalds/linux/commit/d56c0d45f0e27f814e87a1676b6bdccccbc252e9) to include/linux/proc_fs.h that changes "file_operations" to "proc_ops" in the arguments of proc_create and proc_create_data.

### Describe how to reproduce the problem
Try to build ZFS with a kernel that includes the commits 97a32539b9568bb653683349e5a76d02ff3c3e2c and d56c0d45f0e27f814e87a1676b6bdccccbc252e9, and it fails.

### Include any warning/errors/backtraces from the system logs

/home/thz/zfs/module/spl/../os/linux/spl/spl-kstat.c: In function ‘kstat_proc_entry_install’:
/home/thz/zfs/module/spl/../os/linux/spl/spl-kstat.c:693:24: error: passing argument 4 of ‘proc_create_data’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  693 |      module->ksm_proc, file_ops, data);
      |                        ^~~~~~~~
      |                        |
      |                        const struct file_operations *
In file included from /home/thz/zfs/include/os/linux/spl/sys/proc.h:28,
                 from /home/thz/zfs/include/os/linux/spl/sys/kstat.h:33,
                 from /home/thz/zfs/module/spl/../os/linux/spl/spl-kstat.c:28:
./include/linux/proc_fs.h:59:31: note: expected ‘const struct proc_ops *’ but argument is of type ‘const struct file_operations *’
   59 | extern struct proc_dir_entry *proc_create_data(const char *, umode_t,
      |                               ^~~~~~~~~~~~~~~~
```

**Comment by knot-indicated** [comment]
i changed the proc_ops stuff in [my commit here](https://github.com/knot-indicated/zfs/commit/323fe4f8e931bcf8651388b9ffbb3aa2b3f4d456), it seems to build OK; i'm going to reboot and make sure that the ZFS kernel module actually works.


Oh and there's a similar issue with timespec64_trunc being utterly nixed from the kernel (in commit [bddea11b1b9385f713006820f16a9fbe5efe6b47](https://github.com/torvalds/linux/commit/bddea11b1b9385f713006820f16a9fbe5efe6b47). i'm not sure whether the timestamp truncation should be removed altogether or whether timespec64_trunc should be implemented within ZFS. i copy-pasted its definition in my [commit](https://github.com/knot-indicated/zfs/commit/33526ef4cb90e39f19129513fd0269ed59aab851) but that's just because i wanted to make it build with the least effort, not because i believe that is the correct option.

**Comment by dreamcat4** [comment]
@behlendorf has raised a pr for this now https://github.com/zfsonlinux/zfs/pull/9961
