### ISSUE TITLE
Strict autotools API checks

### ISSUE THREAD

**Issue by ryao** [zfsonlinux/zfs#999]
Currently, many configure script checks for API changes make assumptions that if one interface is not used, the other must be used. Unfortunately, that assumption causes problems should the interface change again. Building --with-debug will address that through a compile time failure, but few end users do, which can result in difficult to debug runtime failures that are rather frustrating for users (e.g. issue #843). We can address that by changing the existing checks to check all known cases and forcing a failure if no known case is detected. Once that is done, all future configure script checks should be required to follow the same standard.

This is also related to issue #582, which could probably be tackled at the same time.

**Comment by behlendorf** [comment]
This remains a good idea if someone wants to work on it, but the existing system has been working well for several years now.
