### ISSUE TITLE
zfs 0.8.3: configure fails when /bin/sh is not bash

### ISSUE THREAD

**Issue by ahesford** [zfsonlinux/zfs#9990]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Void
Distribution Version	|  Rolling
Linux Kernel	|  5.4.18
Architecture	|  x86_64
ZFS Version	|  0.8.3
SPL Version	|  0.8.3

### Describe the problem you're observing

The `configure` script, using a function defined in `config/kernel.m4`, relies on a bashism to redirect `stdout` and `stderr` to a log file. However, the script shebang declares `/bin/sh` as the shell. For systems like Void or Alpine that install something other than bash at `/bin/sh`, this bashism is not recognized, and the `make` command is backgrounded instead of having its `stderr` redirected. As a consequence, `configure` checks too soon for build products and assumes the build has failed.

### Describe how to reproduce the problem

Try to run `configure` on a system where `/bin/sh` is something other than `bash`, such as `dash` (Void) or `ash` (Alpine, I believe). 

### Include any warning/errors/backtraces from the system logs

```
checking whether modules can be built... make: Entering directory '/usr/src/kernel-headers-5.5.3_1'
no
configure: error:
	*** Unable to build an empty module.
			
PROMPT%   CC [M]  /home/build/zfs-0.8.3/build/conftest/conftest.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC [M]  /home/build/zfs-0.8.3/build/conftest/conftest.mod.o
  LD [M]  /home/build/zfs-0.8.3/build/conftest/conftest.ko
make: Leaving directory '/usr/src/kernel-headers-5.5.3_1'
```

Note that `configure` has failed and returned to the shell `PROMPT%` before `make modules` has compiled the test kernel module.

### Solution

Either modify the `configure` script shebang to declare `/bin/bash` instead of `/bin/sh`, or modify line 606 of `config/kernel.m4` to replace the `bash`-style redirection `&>$1/build.log` with the POSIX variant `>$1/build.log 2>&1`. Full diff:

```
--- kernel.m4.orig	2020-02-12 16:06:36.072172253 -0500
+++ kernel.m4	2020-02-12 16:07:18.300276042 -0500
@@ -603,7 +603,7 @@
 	AC_TRY_COMMAND([
 	    KBUILD_MODPOST_NOFINAL="$5" KBUILD_MODPOST_WARN="$6"
 	    make modules -k -j$TEST_JOBS -C $LINUX_OBJ $ARCH_UM
-	    M=$PWD/$1 &>$1/build.log])
+	    M=$PWD/$1 >$1/build.log 2>&1])
 	AS_IF([AC_TRY_COMMAND([$2])], [$3], [$4])
 ])
```

**Comment by behlendorf** [comment]
@ahesford thanks for reporting this.  If you're comfortable doing so it would be great if you could open a new PR which switches the macro to use the POSIX style redirection.  Alternately, I'd be happy to do so if you prefer.

**Comment by ahesford** [comment]
> @ahesford thanks for reporting this. If you're comfortable doing so it would be great if you could open a new PR which switches the macro to use the POSIX style redirection. Alternately, I'd be happy to do so if you prefer.

@behlendorf Done: #9998
